LMMS: ringbuffer_reader_t< T >::seq_base< rb_ptr_type > Class Template Reference
ringbuffer_reader_t< T >::seq_base< rb_ptr_type > Class Template Reference
sequences help reading by providing a ringbuffer-suited operator[]
Public Member Functions
seq_base (const seq_base &other)=delete
seq_base (rb_ptr_type rb, std::size_t arg_range)
requests a read sequence of size range range can be assumed to be in bounds of read space, since sequences are only created by the safe routines below
seq_base (seq_base &&)=default
bool copy (char *buffer, size_t bsize)
copy the current sequence into a buffer
const T * first_half_ptr () const
std::size_t first_half_size () const
const T & operator[] (std::size_t idx) const
single member access
const T * second_half_ptr () const
std::size_t second_half_size () const
std::size_t size () const
Protected Attributes
rb_ptr_type reader_ref
Private Attributes
const T *const buf
std::size_t range
Detailed Description
template<class T>
template<class rb_ptr_type>
class ringbuffer_reader_t< T >::seq_base< rb_ptr_type >
sequences help reading by providing a ringbuffer-suited operator[]
Definition at line 258 of file ringbuffer.h.
Constructor & Destructor Documentation
seq_base() [1/3]
template<class T> template<class rb_ptr_type> ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::seq_base (rb_ptr_type rb, std::size_t arg_range) inline
requests a read sequence of size range range can be assumed to be in bounds of read space, since sequences are only created by the safe routines below
Definition at line 268 of file ringbuffer.h.
References buf, range, and reader_ref.
Referenced by seq_base(), and seq_base().
seq_base() [2/3]
template<class T> template<class rb_ptr_type> ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::seq_base (const seq_base< rb_ptr_type > & other) delete
References seq_base().
seq_base() [3/3]
template<class T> template<class rb_ptr_type> ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::seq_base (seq_base< rb_ptr_type > &&) default
References seq_base().
Member Function Documentation
copy()
template<class T> template<class rb_ptr_type> bool ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::copy (char * buffer, size_t bsize) inline
copy the current sequence into a buffer
Definition at line 299 of file ringbuffer.h.
References first_half_ptr(), first_half_size(), second_half_ptr(), and second_half_size().
first_half_ptr()
template<class T> template<class rb_ptr_type> const T * ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::first_half_ptr () const inline
Definition at line 286 of file ringbuffer.h.
References buf, and reader_ref.
Referenced by copy().
first_half_size()
template<class T> template<class rb_ptr_type> std::size_t ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::first_half_size () const inline
Definition at line 289 of file ringbuffer.h.
References range, and reader_ref.
Referenced by copy().
operator[]()
template<class T> template<class rb_ptr_type> const T & ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::operator[] (std::size_t idx) const inline
single member access
Definition at line 279 of file ringbuffer.h.
References buf, and reader_ref.
second_half_ptr()
template<class T> template<class rb_ptr_type> const T * ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::second_half_ptr () const inline
Definition at line 288 of file ringbuffer.h.
References buf.
Referenced by copy().
second_half_size()
template<class T> template<class rb_ptr_type> std::size_t ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::second_half_size () const inline
Definition at line 293 of file ringbuffer.h.
References range, and reader_ref.
Referenced by copy().
size()
template<class T> template<class rb_ptr_type> std::size_t ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::size () const inline
Definition at line 284 of file ringbuffer.h.
References range.
Member Data Documentation
buf
template<class T> template<class rb_ptr_type> const T* const ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::buf private
Definition at line 260 of file ringbuffer.h.
Referenced by seq_base(), first_half_ptr(), operator[](), and second_half_ptr().
range
template<class T> template<class rb_ptr_type> std::size_t ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::range private
Definition at line 261 of file ringbuffer.h.
Referenced by seq_base(), first_half_size(), second_half_size(), and size().
reader_ref
template<class T> template<class rb_ptr_type> rb_ptr_type ringbuffer_reader_t< T >::seq_base< rb_ptr_type >::reader_ref protected
Definition at line 263 of file ringbuffer.h.
Referenced by seq_base(), first_half_ptr(), first_half_size(), operator[](), and second_half_size().
The documentation for this class was generated from the following file:
src/3rdparty/ringbuffer/include/ringbuffer/ringbuffer.h