LMMS: lmms::Controller Class Reference
lmms::Controller Class Reference
#include <Controller.h>
Public Types
enum class ControllerType {
Dummy ,
Lfo ,
Midi ,
Peak
}
Public Slots
virtual gui::ControllerDialog * createDialog (QWidget *_parent)
virtual void setName (const QString &_new_name)
Signals
void valueChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
Controller (ControllerType _type, Model *_parent, const QString &_display_name)
~Controller () override
void addConnection (ControllerConnection *)
int connectionCount () const
virtual float currentValue (int _offset)
bool frequentUpdates () const
bool hasModel (const Model *m) const
bool isSampleExact () const
void loadSettings (const QDomElement &_this) override
virtual const QString & name () const
QString nodeName () const override
void removeConnection (ControllerConnection *)
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
void setSampleExact (bool _exact)
ControllerType type () const
virtual ValueBuffer * valueBuffer ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static Controller * create (const QDomElement &_this, Model *_parent)
static Controller * create (ControllerType _tt, Model *_parent)
static float fittedValue (float _val)
static void resetFrameCounter ()
static unsigned int runningFrames ()
static long runningPeriods ()
static float runningTime ()
static void triggerFrameCounter ()
Protected Member Functions
virtual void updateValueBuffer ()
virtual float value (int _offset)
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Attributes
long m_bufferLastUpdated
int m_connectionCount
float m_currentValue
QString m_name
bool m_sampleExact
ControllerType m_type
ValueBuffer m_valueBuffer
Static Protected Attributes
static ControllerVector s_controllers
static long s_periods = 0
Friends
class gui::ControllerDialog
Detailed Description
Definition at line 50 of file Controller.h.
Member Enumeration Documentation
ControllerType
enum class lmms::Controller::ControllerType strong
Enumerator
Dummy
Lfo
Midi
Peak
Definition at line 54 of file Controller.h.
Constructor & Destructor Documentation
Controller()
lmms::Controller::Controller (ControllerType _type, Model * _parent, const QString & _display_name)
Definition at line 47 of file Controller.cpp.
References Controller(), lmms::JournallingObject::JournallingObject(), lmms::Model::Model(), Dummy, i, m_bufferLastUpdated, m_connectionCount, m_name, m_type, m_valueBuffer, Midi, s_controllers, and updateValueBuffer().
Referenced by Controller(), lmms::LfoController::LfoController(), lmms::MidiController::MidiController(), lmms::PeakController::PeakController(), create(), create(), resetFrameCounter(), and triggerFrameCounter().
~Controller()
lmms::Controller::~Controller () override
Definition at line 87 of file Controller.cpp.
References m_valueBuffer, and s_controllers.
Member Function Documentation
addConnection()
void lmms::Controller::addConnection (ControllerConnection *)
Definition at line 295 of file Controller.cpp.
References m_connectionCount.
Referenced by lmms::ControllerConnection::setController().
connectionCount()
int lmms::Controller::connectionCount () const
Definition at line 312 of file Controller.cpp.
References m_connectionCount.
Referenced by lmms::gui::ControllerRackView::deleteController().
create() [1/2]
Controller * lmms::Controller::create (const QDomElement & _this, Model * _parent) static
Definition at line 221 of file Controller.cpp.
References Controller(), lmms::Model::Model(), create(), lmms::PeakController::getControllerBySetting(), and Peak.
create() [2/2]
Controller * lmms::Controller::create (ControllerType _tt, Model * _parent) static
Definition at line 185 of file Controller.cpp.
References Controller(), lmms::Model::Model(), Dummy, Lfo, Midi, and Peak.
Referenced by lmms::ControllerConnection::ControllerConnection(), create(), lmms::ControllerConnection::loadSettings(), lmms::Song::restoreControllerStates(), and lmms::ControllerConnection::setController().
createDialog
gui::ControllerDialog * lmms::Controller::createDialog (QWidget * _parent) virtual slot
Definition at line 285 of file Controller.cpp.
Referenced by lmms::gui::ControllerView::ControllerView().
currentValue()
float lmms::Controller::currentValue (int _offset) virtual
Definition at line 102 of file Controller.cpp.
References fittedValue(), isSampleExact(), m_currentValue, and value().
fittedValue()
float lmms::Controller::fittedValue (float _val) inline static
Definition at line 118 of file Controller.h.
Referenced by currentValue().
frequentUpdates()
bool lmms::Controller::frequentUpdates () const inline
Definition at line 92 of file Controller.h.
References Lfo, m_type, and Peak.
hasModel()
bool lmms::Controller::hasModel (const Model * m) const
Definition at line 233 of file Controller.cpp.
References lmms::Model::Model(), lmms::ControllerConnection::getController(), and hasModel().
Referenced by hasModel().
isSampleExact()
bool lmms::Controller::isSampleExact () const inline
Definition at line 75 of file Controller.h.
References m_sampleExact.
Referenced by currentValue(), and lmms::AutomatableModel::valueBuffer().
loadSettings()
void lmms::Controller::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Reimplemented in lmms::LfoController, lmms::MidiController, and lmms::PeakController.
Definition at line 266 of file Controller.cpp.
References setName(), and type().
Referenced by lmms::LfoController::loadSettings(), lmms::MidiController::loadSettings(), and lmms::PeakController::loadSettings().
name()
virtual const QString & lmms::Controller::name () const inline virtual
Definition at line 104 of file Controller.h.
References m_name.
Referenced by lmms::gui::ControllerView::ControllerView(), lmms::gui::LfoControllerDialog::LfoControllerDialog(), lmms::gui::AutomatableModelView::addDefaultActions(), lmms::gui::ControllerView::contextMenuEvent(), and saveSettings().
nodeName()
QString lmms::Controller::nodeName () const override virtual
Implements lmms::SerializingObject.
Reimplemented in lmms::LfoController, lmms::MidiController, and lmms::PeakController.
Definition at line 278 of file Controller.cpp.
removeConnection()
void lmms::Controller::removeConnection (ControllerConnection *)
Definition at line 303 of file Controller.cpp.
References m_connectionCount.
resetFrameCounter()
void lmms::Controller::resetFrameCounter () static
Definition at line 174 of file Controller.cpp.
References Controller(), s_controllers, and s_periods.
runningFrames()
unsigned int lmms::Controller::runningFrames () static
Definition at line 142 of file Controller.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), and s_periods.
Referenced by lmms::gui::FloatModelEditorBase::friendlyUpdate(), and runningTime().
runningPeriods()
long lmms::Controller::runningPeriods () inline static
Definition at line 123 of file Controller.h.
References s_periods.
runningTime()
float lmms::Controller::runningTime () static
Definition at line 150 of file Controller.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::outputSampleRate(), and runningFrames().
saveSettings()
void lmms::Controller::saveSettings (QDomDocument & _doc, QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Reimplemented in lmms::LfoController, lmms::MidiController, and lmms::PeakController.
Definition at line 258 of file Controller.cpp.
References name(), and type().
Referenced by lmms::LfoController::saveSettings(), lmms::MidiController::saveSettings(), and lmms::PeakController::saveSettings().
setName
virtual void lmms::Controller::setName (const QString & _new_name) inline virtual slot
Definition at line 143 of file Controller.h.
References m_name.
Referenced by loadSettings(), and lmms::MidiController::updateName().
setSampleExact()
void lmms::Controller::setSampleExact (bool _exact) inline
Definition at line 80 of file Controller.h.
References m_sampleExact.
Referenced by lmms::LfoController::LfoController(), lmms::MidiController::MidiController(), and lmms::PeakController::PeakController().
triggerFrameCounter()
void lmms::Controller::triggerFrameCounter () static
Definition at line 157 of file Controller.cpp.
References Controller(), s_controllers, and s_periods.
Referenced by lmms::AudioEngine::renderStageMix().
type()
ControllerType lmms::Controller::type () const inline
Definition at line 85 of file Controller.h.
References m_type.
Referenced by lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog(), lmms::ControllerConnection::finalizeConnections(), loadSettings(), saveSettings(), and lmms::ControllerConnection::setController().
updateValueBuffer()
void lmms::Controller::updateValueBuffer () protected virtual
Reimplemented in lmms::LfoController, lmms::MidiController, and lmms::PeakController.
Definition at line 134 of file Controller.cpp.
References m_bufferLastUpdated, m_valueBuffer, and s_periods.
Referenced by Controller(), value(), and valueBuffer().
value()
float lmms::Controller::value (int _offset) protected virtual
Definition at line 114 of file Controller.cpp.
References m_bufferLastUpdated, m_valueBuffer, s_periods, and updateValueBuffer().
Referenced by currentValue().
valueBuffer()
ValueBuffer * lmms::Controller::valueBuffer () virtual
Definition at line 124 of file Controller.cpp.
References m_bufferLastUpdated, m_valueBuffer, s_periods, and updateValueBuffer().
valueChanged
void lmms::Controller::valueChanged () signal
Referenced by lmms::AutoDetectMidiController::processInEvent(), and lmms::MidiController::processInEvent().
Friends And Related Symbol Documentation
gui::ControllerDialog
friend class gui::ControllerDialog friend
Definition at line 178 of file Controller.h.
Member Data Documentation
m_bufferLastUpdated
long lmms::Controller::m_bufferLastUpdated protected
Definition at line 160 of file Controller.h.
Referenced by Controller(), lmms::LfoController::updatePhase(), updateValueBuffer(), lmms::LfoController::updateValueBuffer(), lmms::MidiController::updateValueBuffer(), lmms::PeakController::updateValueBuffer(), value(), and valueBuffer().
m_connectionCount
int lmms::Controller::m_connectionCount protected
Definition at line 164 of file Controller.h.
Referenced by Controller(), addConnection(), connectionCount(), and removeConnection().
m_currentValue
float lmms::Controller::m_currentValue protected
Definition at line 162 of file Controller.h.
Referenced by currentValue().
m_name
QString lmms::Controller::m_name protected
Definition at line 166 of file Controller.h.
Referenced by Controller(), name(), and setName().
m_sampleExact
bool lmms::Controller::m_sampleExact protected
Definition at line 163 of file Controller.h.
Referenced by isSampleExact(), and setSampleExact().
m_type
ControllerType lmms::Controller::m_type protected
Definition at line 167 of file Controller.h.
Referenced by Controller(), frequentUpdates(), and type().
m_valueBuffer
ValueBuffer lmms::Controller::m_valueBuffer protected
Definition at line 158 of file Controller.h.
Referenced by Controller(), ~Controller(), updateValueBuffer(), lmms::LfoController::updateValueBuffer(), lmms::MidiController::updateValueBuffer(), lmms::PeakController::updateValueBuffer(), value(), and valueBuffer().
s_controllers
std::vector< Controller * > lmms::Controller::s_controllers static protected
Definition at line 169 of file Controller.h.
Referenced by Controller(), ~Controller(), resetFrameCounter(), and triggerFrameCounter().
s_periods
long lmms::Controller::s_periods = 0 static protected
Definition at line 171 of file Controller.h.
Referenced by resetFrameCounter(), runningFrames(), runningPeriods(), triggerFrameCounter(), lmms::LfoController::updatePhase(), updateValueBuffer(), lmms::LfoController::updateValueBuffer(), lmms::MidiController::updateValueBuffer(), lmms::PeakController::updateValueBuffer(), value(), and valueBuffer().
The documentation for this class was generated from the following files:
include/Controller.h
src/core/Controller.cpp