LMMS: lmms::gui::ControllerDialog Class Reference
lmms::gui::ControllerDialog Class Reference
#include <ControllerDialog.h>
Signals
void closed ()
Public Member Functions
ControllerDialog (Controller *_controller, QWidget *_parent)
~ControllerDialog () override=default
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
void closeEvent (QCloseEvent *_ce) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Detailed Description
Definition at line 41 of file ControllerDialog.h.
Constructor & Destructor Documentation
ControllerDialog()
lmms::gui::ControllerDialog::ControllerDialog (Controller * _controller, QWidget * _parent)
Definition at line 35 of file ControllerDialog.cpp.
References lmms::gui::ModelView::ModelView().
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog(), and lmms::gui::PeakControllerDialog::PeakControllerDialog().
~ControllerDialog()
lmms::gui::ControllerDialog::~ControllerDialog () override default
Member Function Documentation
closed
void lmms::gui::ControllerDialog::closed () signal
Referenced by closeEvent().
closeEvent()
void lmms::gui::ControllerDialog::closeEvent (QCloseEvent * _ce) override protected
Definition at line 44 of file ControllerDialog.cpp.
References closed().
The documentation for this class was generated from the following files:
include/ControllerDialog.h
src/gui/ControllerDialog.cpp