LMMS: lmms::NotePlayHandle Class Reference
lmms::NotePlayHandle Class Reference
#include <NotePlayHandle.h>
Classes
class BaseDetuning
Public Types
enum class Origin {
MidiClip ,
MidiInput ,
NoteStacking ,
Arpeggio
}
Public Types inherited from lmms::PlayHandle
enum class Type {
NotePlayHandle = 0x01 ,
InstrumentPlayHandle = 0x02 ,
SamplePlayHandle = 0x04 ,
PresetPreviewHandle = 0x08
}
using Types = Flags<Type>
Public Types inherited from lmms::ThreadableJob
enum class ProcessingState : int {
Unstarted ,
Queued ,
InProgress ,
Done
}
Public Types inherited from lmms::Note
enum class Type {
Regular = 0 ,
Step
}
Public Member Functions
NotePlayHandle (InstrumentTrack *instrumentTrack, const f_cnt_t offset, const f_cnt_t frames, const Note &noteToPlay, NotePlayHandle *parent=nullptr, int midiEventChannel=-1, Origin origin=Origin::MidiClip)
~NotePlayHandle () override
f_cnt_t actualReleaseFramesToDo () const
Returns the number of frames to be played after release according to the release times in the envelopes.
float currentDetuning () const
Get the current per-note detuning for this note.
f_cnt_t frames () const
Returns total numbers of frames to play (including release frames).
f_cnt_t framesBeforeRelease () const
Returns number of frames to be played until the note is going to be released.
f_cnt_t framesLeft () const
Returns number of frames left for playback.
fpp_t framesLeftForCurrentPeriod () const
Returns how many frames have to be rendered in current period.
const float & frequency () const
bool hasParent () const
Returns whether note has a parent, e.g.
int index () const
Returns index of NotePlayHandle in vector of note-play-handles belonging to this instrument track - used by arpeggiator.
InstrumentTrack * instrumentTrack ()
Returns instrument track which is being played by this handle.
const InstrumentTrack * instrumentTrack () const
Returns instrument track which is being played by this handle (const version).
bool isFinished () const override
Returns whether playback of note is finished and thus handle can be deleted.
bool isFromTrack (const Track *_track) const override
Returns whether the play handle plays on a certain track.
bool isMasterNote () const
Returns whether note has children.
bool isMuted () const
Returns whether note is muted.
bool isPatternTrackMuted ()
Returns whether NotePlayHandle belongs to pattern track and pattern track is muted.
bool isReleased () const
Returns whether note was released.
bool isReleaseStarted () const
int midiChannel () const
int midiKey () const
void mute ()
Mutes playback of note.
void noteOff (const f_cnt_t offset=0)
Releases the note (and plays release frames).
f_cnt_t noteOffset () const
convenience function that returns offset for the first period and zero otherwise, used by instruments to handle the offset: instruments have to check this property and add the correct number of empty frames in the beginning of the period
void * operator new (size_t size, void *p)
bool operator== (const NotePlayHandle &_nph) const
Returns whether given NotePlayHandle instance is equal to *this.
Origin origin () const
Returns origin of note.
void play (SampleFrame *buffer) override
Renders one chunk using the attached instrument into the buffer.
void processTimePos (const TimePos &time, float pitchValue, bool isRecording)
Process note detuning automation.
f_cnt_t releaseFramesDone () const
Returns how many frames were played since release.
void resize (const bpm_t newTempo)
Updates total length (m_frames) depending on a new tempo.
void setFrames (const f_cnt_t _frames)
Sets the total number of frames to play (including release frames).
void setFrequencyUpdate ()
void setMasterNote ()
void setPanning (panning_t panning) override
void setPatternTrack (Track *t)
Sets attached pattern track.
void setSongGlobalParentOffset (const TimePos &offset)
Set song-global offset (relative to containing MIDI clip) in order to properly perform the note detuning.
void setVolume (volume_t volume) override
const TimePos & songGlobalParentOffset () const
Returns song-global offset.
f_cnt_t totalFramesPlayed () const
Returns total numbers of frames played so far.
float unpitchedFrequency () const
Returns frequency without pitch wheel influence.
float volumeLevel (const f_cnt_t frame)
Returns volume level at given frame (envelope/LFO).
Public Member Functions inherited from lmms::PlayHandle
PlayHandle (const Type type, f_cnt_t offset=0)
virtual ~PlayHandle ()
const QThread * affinity () const
virtual bool affinityMatters () const
AudioBusHandle * audioBusHandle ()
SampleFrame * buffer ()
void doProcessing () override
void lock ()
f_cnt_t offset () const
PlayHandle & operator= (PlayHandle &p)
void releaseBuffer ()
bool requiresProcessing () const override
void setAudioBusHandle (AudioBusHandle *busHandle)
void setOffset (f_cnt_t _offset)
void setUsesBuffer (const bool b)
bool tryLock ()
Type type () const
void unlock ()
bool usesBuffer () const
Public Member Functions inherited from lmms::ThreadableJob
ThreadableJob ()
void done ()
void process ()
void queue ()
void reset ()
ProcessingState state () const
Public Member Functions inherited from lmms::Note
Note (const Note &note)
Note (const TimePos &length=TimePos(0), const TimePos &pos=TimePos(0), int key=DefaultKey, volume_t volume=DefaultVolume, panning_t panning=DefaultPanning, std::shared_ptr< DetuningHelper > detuning=nullptr)
~Note () override
Note * clone () const
Performs a deep copy and returns an owning raw pointer.
void createDetuning ()
const std::shared_ptr< DetuningHelper > & detuning () const
TimePos endPos () const
panning_t getPanning () const
volume_t getVolume () const
bool hasDetuningInfo () const
bool isPlaying () const
int key () const
const TimePos & length () const
int midiVelocity (int midiBaseVelocity) const
QString nodeName () const override
int oldKey () const
TimePos oldLength () const
TimePos oldPos () const
Note & operator= (const Note &note)
const TimePos & pos () const
TimePos pos (TimePos basePos) const
void quantizeLength (const int qGrid)
void quantizePos (const int qGrid)
bool selected () const
void setIsPlaying (const bool isPlaying)
void setKey (const int key)
void setLength (const TimePos &length)
void setOldKey (const int oldKey)
void setOldLength (const TimePos &oldLength)
void setOldPos (const TimePos &oldPos)
void setPos (const TimePos &pos)
void setSelected (const bool selected)
void setType (Type t)
Type type () const
bool withinRange (int tickStart, int tickEnd) const
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual void restoreState (const QDomElement &_this)
virtual QDomElement saveState (QDomDocument &_doc, QDomElement &_parent)
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static ConstNotePlayHandleList nphsOfInstrumentTrack (const InstrumentTrack *Track, bool allPlayHandles=false)
Returns list of note-play-handles belonging to given instrument track.
Static Public Member Functions inherited from lmms::Note
static QString classNodeName ()
static bool lessThan (const Note *lhs, const Note *rhs)
static TimePos quantized (const TimePos &m, const int qGrid)
Public Attributes
fpp_t m_fadeInLength
std::unique_ptr< BasicFilters<> > m_filter
void * m_pluginData
Private Member Functions
void updateFrequency ()
Private Attributes
BaseDetuning * m_baseDetuning
f_cnt_t m_frames
f_cnt_t m_framesBeforeRelease
float m_frequency
bool m_frequencyNeedsUpdate
bool m_hadChildren
bool m_hasMidiNote
bool m_hasParent
InstrumentTrack * m_instrumentTrack
int m_midiChannel
bool m_muted
int m_origBaseNote
f_cnt_t m_origFrames
Origin m_origin
bpm_t m_origTempo
NotePlayHandle * m_parent
Track * m_patternTrack
volatile bool m_released
f_cnt_t m_releaseFramesDone
f_cnt_t m_releaseFramesToDo
bool m_releaseStarted
TimePos m_songGlobalParentOffset
NotePlayHandleList m_subNotes
f_cnt_t m_totalFramesPlayed
float m_unpitchedFrequency
Additional Inherited Members
Static Public Attributes inherited from lmms::PlayHandle
static constexpr std::size_t MaxNumber = 1024
Protected Member Functions inherited from lmms::Note
void loadSettings (const QDomElement &_this) override
void saveSettings (QDomDocument &doc, QDomElement &parent) override
Protected Attributes inherited from lmms::ThreadableJob
std::atomic< ProcessingState > m_state
Detailed Description
Definition at line 47 of file NotePlayHandle.h.
Member Enumeration Documentation
Origin
enum class lmms::NotePlayHandle::Origin strong
Enumerator
MidiClip
MidiInput
playback of a note from a MIDI clip
NoteStacking
playback of a MIDI note input event
Arpeggio
created by note stacking instrument function
Definition at line 57 of file NotePlayHandle.h.
Constructor & Destructor Documentation
NotePlayHandle()
lmms::NotePlayHandle::NotePlayHandle (InstrumentTrack * instrumentTrack, const f_cnt_t offset, const f_cnt_t frames, const Note & noteToPlay, NotePlayHandle * parent = nullptr, int midiEventChannel = -1, Origin origin = Origin::MidiClip)
Definition at line 49 of file NotePlayHandle.cpp.
References lmms::Note::Note(), NotePlayHandle(), lmms::PlayHandle::PlayHandle(), lmms::Note::detuning(), hasParent(), instrumentTrack(), lmms::PlayHandle::lock(), m_baseDetuning, m_frames, m_framesBeforeRelease, m_frequency, m_frequencyNeedsUpdate, m_hadChildren, m_hasMidiNote, m_hasParent, m_instrumentTrack, m_midiChannel, m_muted, m_origBaseNote, m_origin, m_origTempo, m_parent, m_patternTrack, m_pluginData, m_released, m_releaseFramesDone, m_releaseFramesToDo, m_releaseStarted, m_songGlobalParentOffset, m_subNotes, m_totalFramesPlayed, m_unpitchedFrequency, MidiInput, origin(), lmms::PlayHandle::setAudioBusHandle(), setFrames(), lmms::PlayHandle::setUsesBuffer(), lmms::PlayHandle::unlock(), and updateFrequency().
Referenced by NotePlayHandle(), index(), noteOff(), nphsOfInstrumentTrack(), and operator==().
~NotePlayHandle()
lmms::NotePlayHandle::~NotePlayHandle () override
Definition at line 123 of file NotePlayHandle.cpp.
References lmms::PlayHandle::buffer(), hasParent(), lmms::Note::key(), lmms::PlayHandle::lock(), m_baseDetuning, m_instrumentTrack, m_parent, m_pluginData, m_subNotes, noteOff(), lmms::PlayHandle::releaseBuffer(), and lmms::PlayHandle::unlock().
Member Function Documentation
actualReleaseFramesToDo()
f_cnt_t lmms::NotePlayHandle::actualReleaseFramesToDo () const
Returns the number of frames to be played after release according to the release times in the envelopes.
Definition at line 414 of file NotePlayHandle.cpp.
References m_instrumentTrack.
Referenced by framesLeft(), and noteOff().
currentDetuning()
float lmms::NotePlayHandle::currentDetuning () const inline
Get the current per-note detuning for this note.
Definition at line 110 of file NotePlayHandle.h.
References m_baseDetuning.
frames()
f_cnt_t lmms::NotePlayHandle::frames () const inline
Returns total numbers of frames to play (including release frames).
Definition at line 150 of file NotePlayHandle.h.
References m_frames.
Referenced by lmms::InstrumentFunctionArpeggio::processNote(), and lmms::InstrumentFunctionNoteStacking::processNote().
framesBeforeRelease()
f_cnt_t lmms::NotePlayHandle::framesBeforeRelease () const inline
Returns number of frames to be played until the note is going to be released.
Definition at line 134 of file NotePlayHandle.h.
References m_framesBeforeRelease.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer(), and lmms::InstrumentSoundShaping::volumeLevel().
framesLeft()
f_cnt_t lmms::NotePlayHandle::framesLeft () const
Returns number of frames left for playback.
Definition at line 329 of file NotePlayHandle.cpp.
References actualReleaseFramesToDo(), lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), instrumentTrack(), m_frames, m_framesBeforeRelease, m_released, m_releaseFramesDone, m_releaseFramesToDo, and m_totalFramesPlayed.
Referenced by lmms::Instrument::applyRelease(), framesLeftForCurrentPeriod(), isFinished(), and play().
framesLeftForCurrentPeriod()
fpp_t lmms::NotePlayHandle::framesLeftForCurrentPeriod () const
Returns how many frames have to be rendered in current period.
Definition at line 349 of file NotePlayHandle.cpp.
References lmms::Engine::audioEngine(), framesLeft(), m_totalFramesPlayed, and lmms::PlayHandle::offset().
Referenced by lmms::Instrument::applyFadeIn(), and lmms::InstrumentTrack::playNote().
frequency()
const float & lmms::NotePlayHandle::frequency () const inline
Definition at line 98 of file NotePlayHandle.h.
References m_frequency.
Referenced by updateFrequency().
hasParent()
bool lmms::NotePlayHandle::hasParent () const inline
Returns whether note has a parent, e.g.
is not part of an arpeggio or a chord
Definition at line 191 of file NotePlayHandle.h.
References m_hasParent.
Referenced by NotePlayHandle(), ~NotePlayHandle(), play(), and lmms::InstrumentFunctionNoteStacking::processNote().
index()
int lmms::NotePlayHandle::index () const
Returns index of NotePlayHandle in vector of note-play-handles belonging to this instrument track - used by arpeggiator.
Ignores child note-play-handles, returns -1 when called on one
Definition at line 456 of file NotePlayHandle.cpp.
References NotePlayHandle(), lmms::Engine::audioEngine(), m_instrumentTrack, and lmms::AudioEngine::playHandles().
instrumentTrack() [1/2]
InstrumentTrack * lmms::NotePlayHandle::instrumentTrack () inline
Returns instrument track which is being played by this handle.
Definition at line 185 of file NotePlayHandle.h.
References m_instrumentTrack.
instrumentTrack() [2/2]
const InstrumentTrack * lmms::NotePlayHandle::instrumentTrack () const inline
Returns instrument track which is being played by this handle (const version).
Definition at line 179 of file NotePlayHandle.h.
References m_instrumentTrack.
Referenced by NotePlayHandle(), framesLeft(), midiKey(), noteOff(), play(), lmms::InstrumentSoundShaping::processAudioBuffer(), lmms::InstrumentFunctionArpeggio::processNote(), and lmms::InstrumentFunctionNoteStacking::processNote().
isFinished()
bool lmms::NotePlayHandle::isFinished () const inline override virtual
Returns whether playback of note is finished and thus handle can be deleted.
Implements lmms::PlayHandle.
Definition at line 116 of file NotePlayHandle.h.
References framesLeft(), and m_released.
isFromTrack()
bool lmms::NotePlayHandle::isFromTrack (const Track * _track) const override virtual
Returns whether the play handle plays on a certain track.
Implements lmms::PlayHandle.
Definition at line 361 of file NotePlayHandle.cpp.
References m_instrumentTrack, and m_patternTrack.
isMasterNote()
bool lmms::NotePlayHandle::isMasterNote () const inline
Returns whether note has children.
Definition at line 203 of file NotePlayHandle.h.
References m_hadChildren, and m_subNotes.
Referenced by lmms::InstrumentTrack::playNote().
isMuted()
bool lmms::NotePlayHandle::isMuted () const inline
Returns whether note is muted.
Definition at line 215 of file NotePlayHandle.h.
References m_muted.
isPatternTrackMuted()
bool lmms::NotePlayHandle::isPatternTrackMuted () inline
Returns whether NotePlayHandle belongs to pattern track and pattern track is muted.
Definition at line 237 of file NotePlayHandle.h.
References m_patternTrack.
Referenced by lmms::InstrumentTrack::processAudioBuffer().
isReleased()
bool lmms::NotePlayHandle::isReleased () const inline
Returns whether note was released.
Definition at line 159 of file NotePlayHandle.h.
References m_released.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), and lmms::InstrumentSoundShaping::volumeLevel().
isReleaseStarted()
bool lmms::NotePlayHandle::isReleaseStarted () const inline
Definition at line 164 of file NotePlayHandle.h.
References m_releaseStarted.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer().
midiChannel()
int lmms::NotePlayHandle::midiChannel () const inline
Definition at line 83 of file NotePlayHandle.h.
References m_midiChannel.
Referenced by noteOff(), play(), and setVolume().
midiKey()
int lmms::NotePlayHandle::midiKey () const
Definition at line 178 of file NotePlayHandle.cpp.
References lmms::InstrumentTrack::baseNote(), instrumentTrack(), lmms::Note::key(), and m_origBaseNote.
Referenced by noteOff(), play(), and setVolume().
mute()
void lmms::NotePlayHandle::mute ()
Mutes playback of note.
Definition at line 443 of file NotePlayHandle.cpp.
References m_muted, and m_subNotes.
noteOff()
void lmms::NotePlayHandle::noteOff (const f_cnt_t offset = 0)
Releases the note (and plays release frames).
Definition at line 369 of file NotePlayHandle.cpp.
References NotePlayHandle(), actualReleaseFramesToDo(), lmms::Engine::framesPerTick(), lmms::TimePos::fromFrames(), instrumentTrack(), m_framesBeforeRelease, m_hasMidiNote, m_instrumentTrack, m_origin, m_released, m_releaseFramesToDo, m_subNotes, midiChannel(), MidiInput, midiKey(), lmms::MidiNoteOff, lmms::Note::setLength(), and totalFramesPlayed().
Referenced by ~NotePlayHandle(), and play().
noteOffset()
f_cnt_t lmms::NotePlayHandle::noteOffset () const inline
convenience function that returns offset for the first period and zero otherwise, used by instruments to handle the offset: instruments have to check this property and add the correct number of empty frames in the beginning of the period
Definition at line 91 of file NotePlayHandle.h.
References m_totalFramesPlayed, and lmms::PlayHandle::offset().
Referenced by lmms::InstrumentTrack::playNote(), lmms::InstrumentTrack::processAudioBuffer(), and lmms::InstrumentFunctionArpeggio::processNote().
nphsOfInstrumentTrack()
ConstNotePlayHandleList lmms::NotePlayHandle::nphsOfInstrumentTrack (const InstrumentTrack * Track, bool allPlayHandles = false) static
Returns list of note-play-handles belonging to given instrument track.
If allPlayHandles = true, also released note-play-handles and children are returned
Definition at line 479 of file NotePlayHandle.cpp.
References NotePlayHandle(), lmms::Engine::audioEngine(), and lmms::AudioEngine::playHandles().
Referenced by lmms::InstrumentPlayHandle::play(), and lmms::InstrumentFunctionArpeggio::processNote().
operator new()
void * lmms::NotePlayHandle::operator new (size_t size, void * p) inline
Definition at line 74 of file NotePlayHandle.h.
operator==()
bool lmms::NotePlayHandle::operator== (const NotePlayHandle & _nph) const
Returns whether given NotePlayHandle instance is equal to *this.
Definition at line 498 of file NotePlayHandle.cpp.
References NotePlayHandle(), lmms::Note::getPanning(), lmms::Note::getVolume(), lmms::Note::key(), lmms::Note::length(), m_frames, m_hasParent, m_instrumentTrack, m_midiChannel, m_muted, m_origBaseNote, m_origin, m_released, m_totalFramesPlayed, lmms::PlayHandle::offset(), and lmms::Note::pos().
origin()
Origin lmms::NotePlayHandle::origin () const inline
Returns origin of note.
Definition at line 197 of file NotePlayHandle.h.
References m_origin.
Referenced by NotePlayHandle(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), and resize().
play()
void lmms::NotePlayHandle::play (SampleFrame * buffer) override virtual
Renders one chunk using the attached instrument into the buffer.
Implements lmms::PlayHandle.
Definition at line 186 of file NotePlayHandle.cpp.
References lmms::Engine::audioEngine(), framesLeft(), lmms::AudioEngine::framesPerPeriod(), lmms::Engine::framesPerTick(), lmms::TimePos::fromFrames(), hasParent(), instrumentTrack(), lmms::Note::key(), lmms::PlayHandle::lock(), m_frames, m_framesBeforeRelease, m_frequencyNeedsUpdate, m_hasMidiNote, m_instrumentTrack, m_muted, m_released, m_releaseFramesDone, m_releaseFramesToDo, m_releaseStarted, m_subNotes, m_totalFramesPlayed, midiChannel(), midiKey(), lmms::MidiNoteOn, lmms::Note::midiVelocity(), noteOff(), lmms::PlayHandle::offset(), lmms::PlayHandle::setOffset(), lmms::PlayHandle::unlock(), and updateFrequency().
processTimePos()
void lmms::NotePlayHandle::processTimePos (const TimePos & time, float pitchValue, bool isRecording)
Process note detuning automation.
Definition at line 560 of file NotePlayHandle.cpp.
References lmms::approximatelyEqual(), lmms::Note::detuning(), m_baseDetuning, m_origin, MidiInput, lmms::Note::pos(), songGlobalParentOffset(), and updateFrequency().
releaseFramesDone()
f_cnt_t lmms::NotePlayHandle::releaseFramesDone () const inline
Returns how many frames were played since release.
Definition at line 140 of file NotePlayHandle.h.
References m_releaseFramesDone.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer(), and lmms::InstrumentSoundShaping::volumeLevel().
resize()
void lmms::NotePlayHandle::resize (const bpm_t newTempo)
Updates total length (m_frames) depending on a new tempo.
Definition at line 582 of file NotePlayHandle.cpp.
References m_frames, m_origFrames, m_origTempo, m_parent, m_subNotes, m_totalFramesPlayed, MidiInput, NoteStacking, and origin().
setFrames()
void lmms::NotePlayHandle::setFrames (const f_cnt_t _frames)
Sets the total number of frames to play (including release frames).
Definition at line 422 of file NotePlayHandle.cpp.
References m_frames, m_instrumentTrack, and m_origFrames.
Referenced by NotePlayHandle().
setFrequencyUpdate()
void lmms::NotePlayHandle::setFrequencyUpdate () inline
Definition at line 266 of file NotePlayHandle.h.
References m_frequencyNeedsUpdate.
setMasterNote()
void lmms::NotePlayHandle::setMasterNote () inline
Definition at line 208 of file NotePlayHandle.h.
References m_hadChildren, and lmms::PlayHandle::setUsesBuffer().
Referenced by lmms::InstrumentFunctionArpeggio::processNote().
setPanning()
void lmms::NotePlayHandle::setPanning (panning_t panning) override virtual
Reimplemented from lmms::Note.
Definition at line 170 of file NotePlayHandle.cpp.
References lmms::Note::setPanning().
setPatternTrack()
void lmms::NotePlayHandle::setPatternTrack (Track * t) inline
Sets attached pattern track.
Definition at line 243 of file NotePlayHandle.h.
References m_patternTrack.
Referenced by lmms::InstrumentTrack::play().
setSongGlobalParentOffset()
void lmms::NotePlayHandle::setSongGlobalParentOffset (const TimePos & offset) inline
Set song-global offset (relative to containing MIDI clip) in order to properly perform the note detuning.
Definition at line 255 of file NotePlayHandle.h.
References m_songGlobalParentOffset, and lmms::PlayHandle::offset().
Referenced by lmms::InstrumentTrack::play().
setVolume()
void lmms::NotePlayHandle::setVolume (volume_t volume) override virtual
Reimplemented from lmms::Note.
Definition at line 158 of file NotePlayHandle.cpp.
References m_instrumentTrack, midiChannel(), midiKey(), lmms::MidiKeyPressure, lmms::Note::midiVelocity(), and lmms::Note::setVolume().
songGlobalParentOffset()
const TimePos & lmms::NotePlayHandle::songGlobalParentOffset () const inline
Returns song-global offset.
Definition at line 261 of file NotePlayHandle.h.
References m_songGlobalParentOffset.
Referenced by processTimePos().
totalFramesPlayed()
f_cnt_t lmms::NotePlayHandle::totalFramesPlayed () const inline
Returns total numbers of frames played so far.
Definition at line 170 of file NotePlayHandle.h.
References m_totalFramesPlayed.
Referenced by lmms::Instrument::applyFadeIn(), noteOff(), lmms::InstrumentSoundShaping::processAudioBuffer(), lmms::InstrumentFunctionArpeggio::processNote(), and lmms::InstrumentFunctionNoteStacking::processNote().
unpitchedFrequency()
float lmms::NotePlayHandle::unpitchedFrequency () const inline
Returns frequency without pitch wheel influence.
Definition at line 104 of file NotePlayHandle.h.
References m_unpitchedFrequency.
updateFrequency()
void lmms::NotePlayHandle::updateFrequency () private
Definition at line 520 of file NotePlayHandle.cpp.
References lmms::DefaultBaseFreq, frequency(), lmms::Engine::getSong(), lmms::Note::key(), m_baseDetuning, m_frequency, m_instrumentTrack, m_subNotes, and m_unpitchedFrequency.
Referenced by NotePlayHandle(), play(), and processTimePos().
volumeLevel()
float lmms::NotePlayHandle::volumeLevel (const f_cnt_t frame)
Returns volume level at given frame (envelope/LFO).
Definition at line 435 of file NotePlayHandle.cpp.
References m_instrumentTrack.
Member Data Documentation
m_baseDetuning
BaseDetuning* lmms::NotePlayHandle::m_baseDetuning private
Definition at line 326 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), ~NotePlayHandle(), currentDetuning(), processTimePos(), and updateFrequency().
m_fadeInLength
fpp_t lmms::NotePlayHandle::m_fadeInLength
Definition at line 54 of file NotePlayHandle.h.
Referenced by lmms::Instrument::applyFadeIn().
m_filter
std::unique_ptr<BasicFilters<> > lmms::NotePlayHandle::m_filter
Definition at line 51 of file NotePlayHandle.h.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer().
m_frames
f_cnt_t lmms::NotePlayHandle::m_frames private
Definition at line 297 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), frames(), framesLeft(), operator==(), play(), resize(), and setFrames().
m_framesBeforeRelease
f_cnt_t lmms::NotePlayHandle::m_framesBeforeRelease private
Definition at line 301 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), framesBeforeRelease(), framesLeft(), noteOff(), and play().
m_frequency
float lmms::NotePlayHandle::m_frequency private
Definition at line 323 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), frequency(), and updateFrequency().
m_frequencyNeedsUpdate
bool lmms::NotePlayHandle::m_frequencyNeedsUpdate private
Definition at line 332 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), play(), and setFrequencyUpdate().
m_hadChildren
bool lmms::NotePlayHandle::m_hadChildren private
Definition at line 313 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), isMasterNote(), and setMasterNote().
m_hasMidiNote
bool lmms::NotePlayHandle::m_hasMidiNote private
Definition at line 310 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), noteOff(), and play().
m_hasParent
bool lmms::NotePlayHandle::m_hasParent private
Definition at line 311 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), hasParent(), and operator==().
m_instrumentTrack
InstrumentTrack* lmms::NotePlayHandle::m_instrumentTrack private
Definition at line 295 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), ~NotePlayHandle(), actualReleaseFramesToDo(), index(), instrumentTrack(), instrumentTrack(), isFromTrack(), noteOff(), operator==(), play(), setFrames(), setVolume(), updateFrequency(), and volumeLevel().
m_midiChannel
int lmms::NotePlayHandle::m_midiChannel private
Definition at line 329 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), midiChannel(), and operator==().
m_muted
bool lmms::NotePlayHandle::m_muted private
Definition at line 314 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), isMuted(), mute(), operator==(), and play().
m_origBaseNote
int lmms::NotePlayHandle::m_origBaseNote private
Definition at line 321 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), midiKey(), and operator==().
m_origFrames
f_cnt_t lmms::NotePlayHandle::m_origFrames private
Definition at line 319 of file NotePlayHandle.h.
Referenced by resize(), and setFrames().
m_origin
Origin lmms::NotePlayHandle::m_origin private
Definition at line 330 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), noteOff(), operator==(), origin(), and processTimePos().
m_origTempo
bpm_t lmms::NotePlayHandle::m_origTempo private
Definition at line 318 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), and resize().
m_parent
NotePlayHandle* lmms::NotePlayHandle::m_parent private
Definition at line 312 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), ~NotePlayHandle(), and resize().
m_patternTrack
Track* lmms::NotePlayHandle::m_patternTrack private
Definition at line 315 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), isFromTrack(), isPatternTrackMuted(), and setPatternTrack().
m_pluginData
void* lmms::NotePlayHandle::m_pluginData
Definition at line 50 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), and ~NotePlayHandle().
m_released
volatile bool lmms::NotePlayHandle::m_released private
Definition at line 308 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), framesLeft(), isFinished(), isReleased(), noteOff(), operator==(), and play().
m_releaseFramesDone
f_cnt_t lmms::NotePlayHandle::m_releaseFramesDone private
Definition at line 305 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), framesLeft(), play(), and releaseFramesDone().
m_releaseFramesToDo
f_cnt_t lmms::NotePlayHandle::m_releaseFramesToDo private
Definition at line 303 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), framesLeft(), noteOff(), and play().
m_releaseStarted
bool lmms::NotePlayHandle::m_releaseStarted private
Definition at line 309 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), isReleaseStarted(), and play().
m_songGlobalParentOffset
TimePos lmms::NotePlayHandle::m_songGlobalParentOffset private
Definition at line 327 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), setSongGlobalParentOffset(), and songGlobalParentOffset().
m_subNotes
NotePlayHandleList lmms::NotePlayHandle::m_subNotes private
Definition at line 307 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), ~NotePlayHandle(), isMasterNote(), mute(), noteOff(), play(), resize(), and updateFrequency().
m_totalFramesPlayed
f_cnt_t lmms::NotePlayHandle::m_totalFramesPlayed private
Definition at line 298 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), framesLeft(), framesLeftForCurrentPeriod(), noteOffset(), operator==(), play(), resize(), and totalFramesPlayed().
m_unpitchedFrequency
float lmms::NotePlayHandle::m_unpitchedFrequency private
Definition at line 324 of file NotePlayHandle.h.
Referenced by NotePlayHandle(), unpitchedFrequency(), and updateFrequency().
The documentation for this class was generated from the following files:
include/NotePlayHandle.h
src/core/NotePlayHandle.cpp