LMMS: lmms::gui::VersionedSaveDialog Class Reference
lmms::gui::VersionedSaveDialog Class Reference
#include <VersionedSaveDialog.h>
Public Slots
void decrementVersion ()
void incrementVersion ()
Public Member Functions
VersionedSaveDialog (QWidget *parent=0, QWidget *saveOptionsWidget=nullptr, const QString &caption=QString(), const QString &directory=QString(), const QString &filter=QString())
Public Member Functions inherited from lmms::gui::FileDialog
FileDialog (QWidget *parent=0, const QString &caption=QString(), const QString &directory=QString(), const QString &filter=QString())
void clearSelection ()
Static Public Member Functions
static bool changeFileNameVersion (QString &fileName, bool increment)
static bool fileExistsQuery (QString FileName, QString WindowTitle)
Static Public Member Functions inherited from lmms::gui::FileDialog
static QString getExistingDirectory (QWidget *parent, const QString &caption, const QString &directory, QFileDialog::Options options=QFileDialog::ShowDirsOnly)
static QString getOpenFileName (QWidget *parent=0, const QString &caption=QString(), const QString &directory=QString(), const QString &filter=QString(), QString *selectedFilter=0)
Detailed Description
Definition at line 49 of file VersionedSaveDialog.h.
Constructor & Destructor Documentation
VersionedSaveDialog()
lmms::gui::VersionedSaveDialog::VersionedSaveDialog (QWidget * parent = 0, QWidget * saveOptionsWidget = nullptr, const QString & caption = QString(), const QString & directory = QString(), const QString & filter = QString()) explicit
Definition at line 42 of file VersionedSaveDialog.cpp.
References lmms::gui::FileDialog::FileDialog(), decrementVersion(), lmms::horizontalAdvance(), and incrementVersion().
Member Function Documentation
changeFileNameVersion()
bool lmms::gui::VersionedSaveDialog::changeFileNameVersion (QString & fileName, bool increment) static
Definition at line 91 of file VersionedSaveDialog.cpp.
Referenced by decrementVersion(), incrementVersion(), and lmms::gui::MainWindow::saveProjectAsNewVersion().
decrementVersion
void lmms::gui::VersionedSaveDialog::decrementVersion () slot
Definition at line 146 of file VersionedSaveDialog.cpp.
References changeFileNameVersion(), lmms::gui::FileDialog::clearSelection(), and file.
Referenced by VersionedSaveDialog().
fileExistsQuery()
bool lmms::gui::VersionedSaveDialog::fileExistsQuery (QString FileName, QString WindowTitle) static
Definition at line 160 of file VersionedSaveDialog.cpp.
Referenced by lmms::gui::MainWindow::exportProject(), and lmms::gui::MainWindow::saveProjectAs().
incrementVersion
void lmms::gui::VersionedSaveDialog::incrementVersion () slot
Definition at line 132 of file VersionedSaveDialog.cpp.
References changeFileNameVersion(), lmms::gui::FileDialog::clearSelection(), and file.
Referenced by VersionedSaveDialog().
The documentation for this class was generated from the following files:
include/VersionedSaveDialog.h
src/gui/modals/VersionedSaveDialog.cpp