LMMS: lmms::AudioFileFlac Class Reference
lmms::AudioFileFlac Class Reference
#include <AudioFileFlac.h>
Public Member Functions
AudioFileFlac (OutputSettings const &outputSettings, ch_cnt_t const channels, bool &successful, QString const &file, AudioEngine *audioEngine)
~AudioFileFlac () override
Public Member Functions inherited from lmms::AudioFileDevice
AudioFileDevice (OutputSettings const &outputSettings, const ch_cnt_t _channels, const QString &_file, AudioEngine *audioEngine)
~AudioFileDevice () override
OutputSettings const & getOutputSettings () const
QString outputFile () const
Public Member Functions inherited from lmms::AudioDevice
AudioDevice (const ch_cnt_t _channels, AudioEngine *audioEngine)
virtual ~AudioDevice ()
void lock ()
void processNextBuffer ()
virtual void registerPort (AudioBusHandle *port)
virtual void renamePort (AudioBusHandle *port)
sample_rate_t sampleRate () const
virtual void startProcessing ()
virtual void stopProcessing ()
bool supportsCapture () const
void unlock ()
virtual void unregisterPort (AudioBusHandle *port)
Static Public Member Functions
static AudioFileDevice * getInst (QString const &outputFilename, OutputSettings const &outputSettings, ch_cnt_t const channels, AudioEngine *audioEngine, bool &successful)
Private Member Functions
void finishEncoding ()
bool startEncoding ()
void writeBuffer (const SampleFrame *_ab, fpp_t const frames) override
Private Attributes
SNDFILE * m_sf
SF_INFO m_sfinfo
Additional Inherited Members
Protected Member Functions inherited from lmms::AudioFileDevice
int outputFileHandle () const
bool outputFileOpened () const
int writeData (const void *data, int len)
Protected Member Functions inherited from lmms::AudioDevice
AudioEngine * audioEngine ()
ch_cnt_t channels () const
void clearS16Buffer (int_sample_t *_outbuf, const fpp_t _frames)
int convertToS16 (const SampleFrame *_ab, const fpp_t _frames, int_sample_t *_output_buffer, const bool _convert_endian=false)
fpp_t getNextBuffer (SampleFrame *_ab)
void setSampleRate (const sample_rate_t _new_sr)
Static Protected Member Functions inherited from lmms::AudioDevice
static void stopProcessingThread (QThread *thread)
Protected Attributes inherited from lmms::AudioDevice
bool m_supportsCapture
Detailed Description
Definition at line 36 of file AudioFileFlac.h.
Constructor & Destructor Documentation
AudioFileFlac()
lmms::AudioFileFlac::AudioFileFlac (OutputSettings const & outputSettings, ch_cnt_t const channels, bool & successful, QString const & file, AudioEngine * audioEngine)
Definition at line 35 of file AudioFileFlac.cpp.
References lmms::AudioFileDevice::AudioFileDevice(), lmms::AudioDevice::audioEngine(), lmms::AudioDevice::channels(), file, m_sf, lmms::AudioFileDevice::outputFileOpened(), and startEncoding().
Referenced by getInst().
~AudioFileFlac()
lmms::AudioFileFlac::~AudioFileFlac () override
Definition at line 42 of file AudioFileFlac.cpp.
References finishEncoding().
Member Function Documentation
finishEncoding()
void lmms::AudioFileFlac::finishEncoding () private
Definition at line 120 of file AudioFileFlac.cpp.
References m_sf.
Referenced by ~AudioFileFlac().
getInst()
AudioFileDevice * lmms::AudioFileFlac::getInst (QString const & outputFilename, OutputSettings const & outputSettings, ch_cnt_t const channels, AudioEngine * audioEngine, bool & successful) inline static
Definition at line 48 of file AudioFileFlac.h.
References lmms::AudioFileDevice::AudioFileDevice(), AudioFileFlac(), lmms::AudioDevice::audioEngine(), and lmms::AudioDevice::channels().
startEncoding()
bool lmms::AudioFileFlac::startEncoding () private
Definition at line 47 of file AudioFileFlac.cpp.
References lmms::AudioDevice::audioEngine(), lmms::AudioDevice::channels(), lmms::OutputSettings::Depth24Bit, lmms::OutputSettings::Depth32Bit, lmms::AudioEngine::framesPerPeriod(), lmms::OutputSettings::getCompressionLevel(), lmms::AudioFileDevice::getOutputSettings(), m_sf, m_sfinfo, lmms::AudioFileDevice::outputFile(), and lmms::AudioDevice::sampleRate().
Referenced by AudioFileFlac().
writeBuffer()
void lmms::AudioFileFlac::writeBuffer (const SampleFrame * _ab, fpp_t const frames) override private virtual
Reimplemented from lmms::AudioDevice.
Definition at line 90 of file AudioFileFlac.cpp.
References lmms::AudioDevice::channels(), lmms::AudioDevice::convertToS16(), lmms::SampleFrame::data(), lmms::OutputSettings::Depth24Bit, lmms::OutputSettings::Depth32Bit, lmms::OutputSettings::getBitDepth(), lmms::AudioFileDevice::getOutputSettings(), lmms::isLittleEndian(), and m_sf.
Member Data Documentation
m_sf
SNDFILE* lmms::AudioFileFlac::m_sf private
Definition at line 66 of file AudioFileFlac.h.
Referenced by AudioFileFlac(), finishEncoding(), startEncoding(), and writeBuffer().
m_sfinfo
SF_INFO lmms::AudioFileFlac::m_sfinfo private
Definition at line 65 of file AudioFileFlac.h.
Referenced by startEncoding().
The documentation for this class was generated from the following files:
include/AudioFileFlac.h
src/core/audio/AudioFileFlac.cpp