LMMS: lmms::gui::SubWindow Class Reference
lmms::gui::SubWindow Class Reference
The SubWindow class.
#include <SubWindow.h>
Signals
void focusLost ()
Public Member Functions
SubWindow (QWidget *parent=nullptr, Qt::WindowFlags windowFlags=QFlag(0))
QBrush activeColor () const
QColor borderColor () const
int frameWidth () const
QRect getTrueNormalGeometry () const
SubWindow::getTrueNormalGeometry.
void setActiveColor (const QBrush &b)
void setBorderColor (const QColor &c)
void setTextShadowColor (const QColor &c)
QColor textShadowColor () const
int titleBarHeight () const
void updateTitleBar ()
Protected Member Functions
QPushButton * addTitleButton (const std::string &iconName, const QString &toolTip)
void changeEvent (QEvent *event) override
SubWindow::changeEvent.
void moveEvent (QMoveEvent *event) override
SubWindow::moveEvent.
void paintEvent (QPaintEvent *pe) override
SubWindow::paintEvent.
void resizeEvent (QResizeEvent *event) override
SubWindow::resizeEvent.
Properties
QBrush activeColor
QColor borderColor
QColor textShadowColor
Private Slots
void focusChanged (QMdiSubWindow *subWindow)
Private Member Functions
void adjustTitleBar ()
SubWindow::adjustTitleBar.
Static Private Member Functions
static void elideText (QLabel *label, QString text)
SubWindow::elideText.
Private Attributes
QBrush m_activeColor
QColor m_borderColor
const QSize m_buttonSize
QPushButton * m_closeBtn
bool m_hasFocus
QPushButton * m_maximizeBtn
QPoint m_position
QPushButton * m_restoreBtn
QGraphicsDropShadowEffect * m_shadow
QColor m_textShadowColor
const int m_titleBarHeight
QRect m_trackedNormalGeom
QLabel * m_windowTitle
Detailed Description
The SubWindow class.
Because of a bug in the QMdiSubWindow class to save the right position and size of a subwindow in a project and because of the inability for customizing the title bar appearance, lmms implements its own subwindow class.
Definition at line 52 of file SubWindow.h.
Constructor & Destructor Documentation
SubWindow()
lmms::gui::SubWindow::SubWindow (QWidget * parent = nullptr, Qt::WindowFlags windowFlags = QFlag(0))
Definition at line 45 of file SubWindow.cpp.
References addTitleButton(), focusChanged(), m_activeColor, m_borderColor, m_buttonSize, m_closeBtn, m_hasFocus, m_maximizeBtn, m_restoreBtn, m_shadow, m_textShadowColor, m_titleBarHeight, m_trackedNormalGeom, m_windowTitle, and titleBarHeight().
Member Function Documentation
activeColor()
QBrush lmms::gui::SubWindow::activeColor () const
Definition at line 183 of file SubWindow.cpp.
References m_activeColor.
addTitleButton()
QPushButton * lmms::gui::SubWindow::addTitleButton (const std::string & iconName, const QString & toolTip) protected
Definition at line 415 of file SubWindow.cpp.
References lmms::embed::getIconPixmap(), and m_buttonSize.
Referenced by SubWindow().
adjustTitleBar()
void lmms::gui::SubWindow::adjustTitleBar () private
SubWindow::adjustTitleBar.
Our title bar needs buttons for maximize/restore and close in the right upper corner. We check if the subwindow is maximizable and put the buttons on the right positions. At next we calculate the width of the title label and call elideText() for adding the window title to m_windowTitle (which is a QLabel)
Definition at line 286 of file SubWindow.cpp.
References elideText(), m_buttonSize, m_closeBtn, m_maximizeBtn, m_restoreBtn, m_titleBarHeight, and m_windowTitle.
Referenced by changeEvent(), resizeEvent(), and updateTitleBar().
borderColor()
QColor lmms::gui::SubWindow::borderColor () const
Definition at line 199 of file SubWindow.cpp.
References m_borderColor.
changeEvent()
void lmms::gui::SubWindow::changeEvent (QEvent * event) override protected
SubWindow::changeEvent.
Triggers if the window title changes and calls adjustTitleBar().
Parameters
event
Definition at line 134 of file SubWindow.cpp.
References adjustTitleBar().
elideText()
void lmms::gui::SubWindow::elideText (QLabel * label, QString text) static private
SubWindow::elideText.
Stores the given text into the given label. Shorts the text if it's too big for the labels width and adds three dots (...)
Parameters
label - holds a pointer to the QLabel
text - the text which will be stored (and if needed broken down) into the QLabel.
Definition at line 158 of file SubWindow.cpp.
Referenced by adjustTitleBar().
focusChanged
void lmms::gui::SubWindow::focusChanged (QMdiSubWindow * subWindow) private slot
Definition at line 369 of file SubWindow.cpp.
References focusLost(), and m_hasFocus.
Referenced by SubWindow().
focusLost
void lmms::gui::SubWindow::focusLost () signal
References focusLost().
Referenced by focusChanged(), and focusLost().
frameWidth()
int lmms::gui::SubWindow::frameWidth () const
Definition at line 242 of file SubWindow.cpp.
getTrueNormalGeometry()
QRect lmms::gui::SubWindow::getTrueNormalGeometry () const
SubWindow::getTrueNormalGeometry.
same as QWidet::normalGeometry, but works properly under X11 see https://bugreports.qt.io/browse/QTBUG-256
Definition at line 175 of file SubWindow.cpp.
References m_trackedNormalGeom.
moveEvent()
void lmms::gui::SubWindow::moveEvent (QMoveEvent * event) override protected
SubWindow::moveEvent.
overrides the QMdiSubWindow::moveEvent() for saving the position of the subwindow into m_trackedNormalGeom. This position will be saved with the project because of an Qt bug which doesn't save the right position. look at: https://bugreports.qt.io/browse/QTBUG-256
Parameters
event
Definition at line 264 of file SubWindow.cpp.
References m_trackedNormalGeom.
paintEvent()
void lmms::gui::SubWindow::paintEvent (QPaintEvent * pe) override protected
SubWindow::paintEvent.
This draws our new title bar with custom colors and draws a window icon on the left upper corner.
Definition at line 96 of file SubWindow.cpp.
References activeColor, borderColor, m_buttonSize, and m_titleBarHeight.
resizeEvent()
void lmms::gui::SubWindow::resizeEvent (QResizeEvent * event) override protected
SubWindow::resizeEvent.
At first we give the event to QMdiSubWindow::resizeEvent() which handles the event on its behavior.
On every resize event we have to adjust our title label.
At last we store the current size into m_trackedNormalGeom. This size will be saved with the project because of an Qt bug which doesn't save the right size. look at: https://bugreports.qt.io/browse/QTBUG-256
Parameters
event
Definition at line 399 of file SubWindow.cpp.
References adjustTitleBar(), and m_trackedNormalGeom.
setActiveColor()
void lmms::gui::SubWindow::setActiveColor (const QBrush & b)
Definition at line 207 of file SubWindow.cpp.
References m_activeColor.
setBorderColor()
void lmms::gui::SubWindow::setBorderColor (const QColor & c)
Definition at line 223 of file SubWindow.cpp.
References m_borderColor.
setTextShadowColor()
void lmms::gui::SubWindow::setTextShadowColor (const QColor & c)
Definition at line 215 of file SubWindow.cpp.
References m_textShadowColor.
textShadowColor()
QColor lmms::gui::SubWindow::textShadowColor () const
Definition at line 191 of file SubWindow.cpp.
References m_textShadowColor.
titleBarHeight()
int lmms::gui::SubWindow::titleBarHeight () const
Definition at line 231 of file SubWindow.cpp.
Referenced by SubWindow().
updateTitleBar()
void lmms::gui::SubWindow::updateTitleBar ()
Definition at line 249 of file SubWindow.cpp.
References adjustTitleBar().
Member Data Documentation
m_activeColor
QBrush lmms::gui::SubWindow::m_activeColor private
Definition at line 94 of file SubWindow.h.
Referenced by SubWindow(), activeColor(), and setActiveColor().
m_borderColor
QColor lmms::gui::SubWindow::m_borderColor private
Definition at line 96 of file SubWindow.h.
Referenced by SubWindow(), borderColor(), and setBorderColor().
m_buttonSize
const QSize lmms::gui::SubWindow::m_buttonSize private
Definition at line 89 of file SubWindow.h.
Referenced by SubWindow(), addTitleButton(), adjustTitleBar(), and paintEvent().
m_closeBtn
QPushButton* lmms::gui::SubWindow::m_closeBtn private
Definition at line 91 of file SubWindow.h.
Referenced by SubWindow(), and adjustTitleBar().
m_hasFocus
bool lmms::gui::SubWindow::m_hasFocus private
Definition at line 101 of file SubWindow.h.
Referenced by SubWindow(), and focusChanged().
m_maximizeBtn
QPushButton* lmms::gui::SubWindow::m_maximizeBtn private
Definition at line 92 of file SubWindow.h.
Referenced by SubWindow(), and adjustTitleBar().
m_position
QPoint lmms::gui::SubWindow::m_position private
Definition at line 97 of file SubWindow.h.
m_restoreBtn
QPushButton* lmms::gui::SubWindow::m_restoreBtn private
Definition at line 93 of file SubWindow.h.
Referenced by SubWindow(), and adjustTitleBar().
m_shadow
QGraphicsDropShadowEffect* lmms::gui::SubWindow::m_shadow private
Definition at line 100 of file SubWindow.h.
Referenced by SubWindow().
m_textShadowColor
QColor lmms::gui::SubWindow::m_textShadowColor private
Definition at line 95 of file SubWindow.h.
Referenced by SubWindow(), setTextShadowColor(), and textShadowColor().
m_titleBarHeight
const int lmms::gui::SubWindow::m_titleBarHeight private
Definition at line 90 of file SubWindow.h.
Referenced by SubWindow(), adjustTitleBar(), and paintEvent().
m_trackedNormalGeom
QRect lmms::gui::SubWindow::m_trackedNormalGeom private
Definition at line 98 of file SubWindow.h.
Referenced by SubWindow(), getTrueNormalGeometry(), moveEvent(), and resizeEvent().
m_windowTitle
QLabel* lmms::gui::SubWindow::m_windowTitle private
Definition at line 99 of file SubWindow.h.
Referenced by SubWindow(), and adjustTitleBar().
Property Documentation
activeColor
QBrush lmms::gui::SubWindow::activeColor read write
Definition at line 55 of file SubWindow.h.
Referenced by paintEvent().
borderColor
QColor lmms::gui::SubWindow::borderColor read write
Definition at line 57 of file SubWindow.h.
Referenced by paintEvent().
textShadowColor
QColor lmms::gui::SubWindow::textShadowColor read write
Definition at line 56 of file SubWindow.h.
The documentation for this class was generated from the following files:
include/SubWindow.h
src/gui/SubWindow.cpp