LMMS: lmms::TimePos Class Reference
lmms::TimePos Class Reference
Represents a position in time or length of a note or event, in ticks, beats, and bars.
#include <TimePos.h>
Public Member Functions
TimePos (const bar_t bar, const tick_t ticks)
TimePos (const tick_t ticks=0)
f_cnt_t frames (const float framesPerTick) const
bar_t getBar () const
tick_t getBeatWithinBar (const TimeSig &sig) const
tick_t getTicks () const
tick_t getTickWithinBar (const TimeSig &sig) const
tick_t getTickWithinBeat (const TimeSig &sig) const
double getTimeInMilliseconds (bpm_t beatsPerMinute) const
bar_t nextFullBar () const
operator int () const
TimePos & operator+= (const TimePos &time)
TimePos & operator-= (const TimePos &time)
TimePos quantize (float bars, bool forceRoundDown=false) const
void setTicks (tick_t ticks)
tick_t ticksPerBeat (const TimeSig &sig) const
TimePos toAbsoluteBar () const
Static Public Member Functions
static TimePos fromFrames (const f_cnt_t frames, const float framesPerTick)
static void setTicksPerBar (tick_t ticks)
static TimePos stepPosition (int step)
static int stepsPerBar ()
static tick_t ticksPerBar ()
static tick_t ticksPerBar (const TimeSig &sig)
static double ticksToMilliseconds (double ticks, bpm_t beatsPerMinute)
static double ticksToMilliseconds (tick_t ticks, bpm_t beatsPerMinute)
Private Attributes
tick_t m_ticks
Static Private Attributes
static tick_t s_ticksPerBar = DefaultTicksPerBar
Detailed Description
Represents a position in time or length of a note or event, in ticks, beats, and bars.
Definition at line 67 of file TimePos.h.
Constructor & Destructor Documentation
TimePos() [1/2]
lmms::TimePos::TimePos (const bar_t bar, const tick_t ticks)
Definition at line 45 of file TimePos.cpp.
References m_ticks, and s_ticksPerBar.
Referenced by lmms::Song::PlayPos::PlayPos(), fromFrames(), operator+=(), operator-=(), quantize(), stepPosition(), and toAbsoluteBar().
TimePos() [2/2]
lmms::TimePos::TimePos (const tick_t ticks = 0)
Definition at line 50 of file TimePos.cpp.
References m_ticks.
Member Function Documentation
frames()
f_cnt_t lmms::TimePos::frames (const float framesPerTick) const inline
Definition at line 111 of file TimePos.h.
References m_ticks.
Referenced by fromFrames().
fromFrames()
TimePos lmms::TimePos::fromFrames (const f_cnt_t frames, const float framesPerTick) inline static
Definition at line 122 of file TimePos.h.
References TimePos(), and frames().
Referenced by lmms::NotePlayHandle::noteOff(), and lmms::NotePlayHandle::play().
getBar()
bar_t lmms::TimePos::getBar () const inline
Definition at line 89 of file TimePos.h.
References m_ticks, and s_ticksPerBar.
Referenced by lmms::gui::PianoRoll::autoScroll(), lmms::gui::TrackContentWidget::canPasteSelection(), lmms::MidiClip::changeTimeSignature(), lmms::gui::ClipView::mouseMoveEvent(), lmms::Song::processNextBuffer(), toAbsoluteBar(), and lmms::gui::AutomationEditor::updatePosition().
getBeatWithinBar()
tick_t lmms::TimePos::getBeatWithinBar (const TimeSig & sig) const inline
Definition at line 105 of file TimePos.h.
References getTickWithinBar(), and ticksPerBeat().
getTicks()
tick_t lmms::TimePos::getTicks () const inline
Definition at line 95 of file TimePos.h.
References m_ticks.
Referenced by lmms::PatternStore::automatedValuesAt(), lmms::gui::PianoRoll::autoScroll(), lmms::gui::PianoRoll::dragNotes(), getTimeInMilliseconds(), lmms::gui::PianoRoll::mouseDoubleClickEvent(), lmms::gui::ClipView::mouseMoveEvent(), lmms::gui::TrackContentWidget::paintEvent(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::Song::processNextBuffer(), lmms::Song::setPlayPos(), lmms::StepRecorder::start(), lmms::gui::SongEditor::updatePosition(), lmms::gui::TimeDisplayWidget::updateTime(), and lmms::Note::withinRange().
getTickWithinBar()
tick_t lmms::TimePos::getTickWithinBar (const TimeSig & sig) const inline
Definition at line 102 of file TimePos.h.
References m_ticks, and ticksPerBar().
Referenced by getBeatWithinBar(), and getTickWithinBeat().
getTickWithinBeat()
tick_t lmms::TimePos::getTickWithinBeat (const TimeSig & sig) const inline
Definition at line 108 of file TimePos.h.
References getTickWithinBar(), and ticksPerBeat().
getTimeInMilliseconds()
double lmms::TimePos::getTimeInMilliseconds (bpm_t beatsPerMinute) const inline
Definition at line 120 of file TimePos.h.
References getTicks(), and ticksToMilliseconds().
nextFullBar()
bar_t lmms::TimePos::nextFullBar () const inline
Definition at line 92 of file TimePos.h.
References m_ticks, and s_ticksPerBar.
Referenced by lmms::MidiClip::beatClipLength(), lmms::MidiClip::changeTimeSignature(), and lmms::PatternStore::lengthOfPattern().
operator int()
lmms::TimePos::operator int () const inline
Definition at line 97 of file TimePos.h.
References m_ticks.
operator+=()
TimePos & lmms::TimePos::operator+= (const TimePos & time) inline
Definition at line 76 of file TimePos.h.
References TimePos(), and m_ticks.
operator-=()
TimePos & lmms::TimePos::operator-= (const TimePos & time) inline
Definition at line 82 of file TimePos.h.
References TimePos(), and m_ticks.
quantize()
TimePos lmms::TimePos::quantize (float bars, bool forceRoundDown = false) const
Definition at line 55 of file TimePos.cpp.
References TimePos(), m_ticks, and s_ticksPerBar.
Referenced by lmms::gui::ClipView::draggedClipPos(), lmms::gui::PianoRoll::dragNotes(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::ClipView::mouseMoveEvent(), lmms::gui::TrackContentWidget::mousePressEvent(), and lmms::gui::ClipView::quantizeSplitPos().
setTicks()
void lmms::TimePos::setTicks (tick_t ticks) inline
Definition at line 94 of file TimePos.h.
References m_ticks.
Referenced by lmms::Song::processNextBuffer(), lmms::gui::PianoRoll::setCurrentMidiClip(), lmms::Song::setPlayPos(), lmms::Song::startExport(), lmms::Song::stop(), and lmms::gui::PianoRoll::updatePositionAccompany().
setTicksPerBar()
void lmms::TimePos::setTicksPerBar (tick_t ticks) inline static
Definition at line 131 of file TimePos.h.
References s_ticksPerBar.
Referenced by lmms::Song::setTimeSignature().
stepPosition()
TimePos lmms::TimePos::stepPosition (int step) inline static
Definition at line 132 of file TimePos.h.
References TimePos(), stepsPerBar(), and ticksPerBar().
Referenced by lmms::MidiClip::addStepNote(), and lmms::MidiClip::noteAtStep().
stepsPerBar()
int lmms::TimePos::stepsPerBar () inline static
Definition at line 130 of file TimePos.h.
References lmms::DefaultBeatsPerBar, and ticksPerBar().
Referenced by lmms::MidiClip::addSteps(), lmms::MidiClip::beatClipLength(), lmms::MidiClip::changeTimeSignature(), lmms::MidiClip::loadSettings(), lmms::gui::MidiClipView::paintEvent(), lmms::MidiClip::removeSteps(), and stepPosition().
ticksPerBar() [1/2]
tick_t lmms::TimePos::ticksPerBar () inline static
Definition at line 127 of file TimePos.h.
References s_ticksPerBar.
Referenced by lmms::gui::SongEditor::SongEditor(), lmms::PatternStore::automatedValuesAt(), lmms::TrackContainer::automatedValuesFromTracks(), lmms::gui::PianoRoll::autoScroll(), lmms::MidiClip::beatClipLength(), lmms::gui::TrackContentWidget::changePosition(), lmms::MidiClip::changeTimeSignature(), lmms::gui::TimeLineWidget::contextMenuEvent(), lmms::gui::ClipView::draggedClipPos(), lmms::gui::PianoRoll::dragNotes(), lmms::gui::AutomationEditor::drawAutomationTangents(), lmms::gui::PianoRoll::drawDetuningInfo(), lmms::gui::AutomationTrackView::dropEvent(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackContentWidget::endPosition(), lmms::gui::PianoRoll::fitNoteLengths(), lmms::gui::TimeLineWidget::getClickedTime(), lmms::Track::getClip(), lmms::gui::AutomationEditor::getClosestNode(), lmms::gui::AutomationEditor::getNodeAt(), lmms::gui::TrackContentWidget::getPosition(), getTickWithinBar(), lmms::Track::insertBar(), lmms::gui::PianoRoll::keyPressEvent(), lmms::gui::SongEditor::keyPressEvent(), lmms::gui::ClipView::knifeMarkerPos(), lmms::Track::length(), lmms::PatternStore::lengthOfPattern(), lmms::gui::TimeLineWidget::markerX(), lmms::gui::PianoRoll::mouseDoubleClickEvent(), lmms::gui::AutomationEditor::mouseMoveEvent(), lmms::gui::ClipView::mouseMoveEvent(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::TimeLineWidget::mouseMoveEvent(), lmms::gui::AutomationEditor::mousePressEvent(), lmms::gui::ClipView::mousePressEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::gui::SongEditor::mousePressEvent(), lmms::gui::ClipView::mouseReleaseEvent(), lmms::gui::PianoRoll::noteUnderMouse(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::AutomationEditor::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::TimeLineWidget::paintEvent(), lmms::gui::TrackContentWidget::paintEvent(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::PatternStore::play(), lmms::PatternTrack::play(), lmms::Track::removeBar(), lmms::gui::PianoRoll::selectRegionFromPixels(), lmms::gui::SongEditor::selectRegionFromPixels(), lmms::gui::PianoRoll::setCurrentMidiClip(), stepPosition(), stepsPerBar(), lmms::Song::ticksPerBar(), ticksPerBeat(), lmms::gui::PianoRoll::updateKnifePos(), lmms::AutomationClip::updateLength(), lmms::gui::ClipView::updateLength(), lmms::MidiClip::updateLength(), lmms::gui::PatternEditor::updatePixelsPerBar(), lmms::gui::AutomationEditor::updatePosition(), lmms::gui::PianoRoll::updatePosition(), lmms::gui::SongEditor::updatePosition(), lmms::gui::SongEditor::updateRubberband(), lmms::gui::SongEditor::updateScrollBar(), lmms::gui::PianoRoll::updateStrumPos(), lmms::gui::AutomationEditor::wheelEvent(), lmms::gui::PianoRoll::wheelEvent(), lmms::gui::SongEditor::wheelEvent(), lmms::gui::AutomationEditor::xCoordOfTick(), and lmms::gui::StepRecorderWidget::xCoordOfTick().
ticksPerBar() [2/2]
tick_t lmms::TimePos::ticksPerBar (const TimeSig & sig) inline static
Definition at line 128 of file TimePos.h.
References lmms::DefaultTicksPerBar, lmms::TimeSig::denominator(), and lmms::TimeSig::numerator().
ticksPerBeat()
tick_t lmms::TimePos::ticksPerBeat (const TimeSig & sig) const inline
Definition at line 99 of file TimePos.h.
References lmms::TimeSig::numerator(), and ticksPerBar().
Referenced by getBeatWithinBar(), and getTickWithinBeat().
ticksToMilliseconds() [1/2]
double lmms::TimePos::ticksToMilliseconds (double ticks, bpm_t beatsPerMinute) inline static
Definition at line 139 of file TimePos.h.
ticksToMilliseconds() [2/2]
double lmms::TimePos::ticksToMilliseconds (tick_t ticks, bpm_t beatsPerMinute) inline static
Definition at line 134 of file TimePos.h.
References ticksToMilliseconds().
Referenced by getTimeInMilliseconds(), lmms::Song::processNextBuffer(), lmms::Song::setPlayPos(), lmms::Song::setToTimeByTicks(), and ticksToMilliseconds().
toAbsoluteBar()
TimePos lmms::TimePos::toAbsoluteBar () const inline
Definition at line 74 of file TimePos.h.
References TimePos(), getBar(), and s_ticksPerBar.
Referenced by lmms::gui::AutomationTrackView::dropEvent().
Member Data Documentation
m_ticks
tick_t lmms::TimePos::m_ticks private
Definition at line 142 of file TimePos.h.
Referenced by TimePos(), TimePos(), frames(), getBar(), getTicks(), getTickWithinBar(), nextFullBar(), operator int(), operator+=(), operator-=(), quantize(), and setTicks().
s_ticksPerBar
tick_t lmms::TimePos::s_ticksPerBar = DefaultTicksPerBar static private
Definition at line 144 of file TimePos.h.
Referenced by TimePos(), getBar(), nextFullBar(), quantize(), setTicksPerBar(), ticksPerBar(), and toAbsoluteBar().
The documentation for this class was generated from the following files:
include/TimePos.h
src/core/Song.cpp
src/core/TimePos.cpp