LMMS: lmms::gui::AutomatableModelView Class Reference
lmms::gui::AutomatableModelView Class Reference
#include <AutomatableModelView.h>
Public Member Functions
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
virtual void mousePressEvent (QMouseEvent *event)
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Protected Attributes
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 38 of file AutomatableModelView.h.
Constructor & Destructor Documentation
AutomatableModelView()
lmms::gui::AutomatableModelView::AutomatableModelView (Model * model, QWidget * _this)
Definition at line 47 of file AutomatableModelView.cpp.
References lmms::gui::ModelView::ModelView(), m_conversionFactor, lmms::gui::ModelView::model(), and lmms::gui::ModelView::widget().
Referenced by lmms::gui::TypedModelView< FloatModel >::TypedModelView().
~AutomatableModelView()
lmms::gui::AutomatableModelView::~AutomatableModelView () override default
Member Function Documentation
addDefaultActions()
void lmms::gui::AutomatableModelView::addDefaultActions (QMenu * menu)
Definition at line 55 of file AutomatableModelView.cpp.
References lmms::gui::floatFromClipboard(), lmms::embed::getIconPixmap(), m_conversionFactor, m_unit, lmms::gui::ModelView::model(), modelUntyped(), and lmms::Controller::name().
Referenced by lmms::gui::AutomatableButton::contextMenuEvent(), lmms::gui::AutomatableSlider::contextMenuEvent(), lmms::gui::ComboBox::contextMenuEvent(), lmms::gui::Fader::contextMenuEvent(), lmms::gui::FloatModelEditorBase::contextMenuEvent(), lmms::gui::LcdFloatSpinBox::contextMenuEvent(), lmms::gui::LcdSpinBox::contextMenuEvent(), lmms::gui::MixerChannelLcdSpinBox::contextMenuEvent(), lmms::gui::PianoView::contextMenuEvent(), lmms::gui::TempoSyncBarModelEditor::contextMenuEvent(), and lmms::gui::TempoSyncKnob::contextMenuEvent().
getConversionFactor()
float lmms::gui::AutomatableModelView::getConversionFactor ()
Definition at line 196 of file AutomatableModelView.cpp.
References m_conversionFactor.
modelUntyped() [1/2]
AutomatableModel * lmms::gui::AutomatableModelView::modelUntyped () inline
Definition at line 45 of file AutomatableModelView.h.
References lmms::gui::ModelView::castModel().
Referenced by addDefaultActions(), mousePressEvent(), and value().
modelUntyped() [2/2]
const AutomatableModel * lmms::gui::AutomatableModelView::modelUntyped () const inline
Definition at line 50 of file AutomatableModelView.h.
References lmms::gui::ModelView::castModel().
mousePressEvent()
void lmms::gui::AutomatableModelView::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented in lmms::gui::AutomatableButton, lmms::gui::AutomatableSlider, lmms::gui::ComboBox, lmms::gui::Fader, lmms::gui::FloatModelEditorBase, lmms::gui::GroupBox, lmms::gui::LcdFloatSpinBox, lmms::gui::LcdSpinBox, and lmms::gui::PixmapButton.
Definition at line 173 of file AutomatableModelView.cpp.
References lmms::KBD_COPY_MODIFIER, modelUntyped(), lmms::AutomatableModel::reset(), and lmms::gui::ModelView::widget().
Referenced by lmms::gui::AutomatableButton::mousePressEvent(), lmms::gui::AutomatableSlider::mousePressEvent(), lmms::gui::ComboBox::mousePressEvent(), lmms::gui::Fader::mousePressEvent(), lmms::gui::FloatModelEditorBase::mousePressEvent(), lmms::gui::LcdFloatSpinBox::mousePressEvent(), and lmms::gui::LcdSpinBox::mousePressEvent().
setConversionFactor()
void lmms::gui::AutomatableModelView::setConversionFactor (float factor)
Definition at line 187 of file AutomatableModelView.cpp.
References m_conversionFactor.
setDescription()
void lmms::gui::AutomatableModelView::setDescription (const QString & desc) inline
Definition at line 64 of file AutomatableModelView.h.
References m_description.
Referenced by lmms::gui::Fader::setHintText(), and lmms::gui::FloatModelEditorBase::setHintText().
setModel()
void lmms::gui::AutomatableModelView::setModel (Model * model, bool isOldModelValid = true) override virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 140 of file AutomatableModelView.cpp.
References lmms::gui::ModelView::model(), and lmms::gui::ModelView::setModel().
Referenced by lmms::gui::BarModelEditor::BarModelEditor(), lmms::gui::Draggable::Draggable(), lmms::gui::Fader::Fader(), lmms::gui::GroupBox::GroupBox(), lmms::gui::LadspaControlView::LadspaControlView(), and unsetModel().
setUnit()
void lmms::gui::AutomatableModelView::setUnit (const QString & unit) inline
Definition at line 69 of file AutomatableModelView.h.
References m_unit.
Referenced by lmms::gui::Fader::setHintText(), and lmms::gui::FloatModelEditorBase::setHintText().
unsetModel()
void lmms::gui::AutomatableModelView::unsetModel () override virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 150 of file AutomatableModelView.cpp.
References setModel(), and lmms::gui::ModelView::unsetModel().
value()
template<typename T> T lmms::gui::AutomatableModelView::value () const inline
Definition at line 59 of file AutomatableModelView.h.
References modelUntyped().
Referenced by lmms::gui::AutomatableButtonGroup::activateButton(), lmms::gui::Fader::adjustByDecibelDelta(), lmms::gui::Fader::adjustByDialog(), lmms::gui::Fader::adjustModelByDBDelta(), lmms::gui::Knob::angleFromValue(), lmms::gui::Fader::calculateKnobPosYFromModel(), lmms::gui::AutomatableSlider::changeValue(), lmms::gui::FloatModelEditorBase::dropEvent(), lmms::gui::LcdFloatSpinBox::enterValue(), lmms::gui::LcdSpinBox::enterValue(), lmms::gui::Fader::getModelValueAsDbString(), lmms::gui::FloatModelEditorBase::getValue(), lmms::gui::Draggable::handleMovement(), lmms::gui::PixmapButton::isActive(), lmms::gui::AutomatableButton::modelChanged(), lmms::gui::MixerChannelLcdSpinBox::mouseDoubleClickEvent(), lmms::gui::Draggable::mouseMoveEvent(), lmms::gui::FloatModelEditorBase::mouseMoveEvent(), lmms::gui::LcdFloatSpinBox::mouseMoveEvent(), lmms::gui::FloatModelEditorBase::mousePressEvent(), lmms::gui::GroupBox::mousePressEvent(), lmms::gui::AutomatableSlider::moveSlider(), lmms::gui::BarModelEditor::paintEvent(), lmms::gui::Draggable::paintEvent(), lmms::gui::Fader::paintEvent(), lmms::gui::LedCheckBox::paintLegacy(), lmms::gui::Fader::paintLevels(), lmms::gui::Fader::peakChanged(), lmms::gui::ComboBox::selectNext(), lmms::gui::ComboBox::selectPrevious(), lmms::gui::Draggable::setDefaultValPixmap(), lmms::gui::GroupBox::setLedButtonShown(), lmms::gui::Fader::setRenderUnityLine(), lmms::gui::FloatModelEditorBase::sliderMoved(), lmms::gui::AutomatableButton::toggle(), lmms::gui::AutomatableButton::update(), lmms::gui::LcdFloatSpinBox::update(), lmms::gui::LcdSpinBox::update(), lmms::gui::Knob::updateAngle(), lmms::gui::AutomatableButtonGroup::updateButtons(), lmms::gui::AutomatableSlider::updateSlider(), lmms::gui::Fader::updateTextFloat(), lmms::gui::ComboBox::wheelEvent(), lmms::gui::FloatModelEditorBase::wheelEvent(), lmms::gui::LcdFloatSpinBox::wheelEvent(), and lmms::gui::LcdSpinBox::wheelEvent().
Member Data Documentation
m_conversionFactor
float lmms::gui::AutomatableModelView::m_conversionFactor protected
Definition at line 85 of file AutomatableModelView.h.
Referenced by AutomatableModelView(), lmms::gui::Fader::Fader(), addDefaultActions(), lmms::gui::Fader::adjustByDialog(), getConversionFactor(), setConversionFactor(), lmms::gui::Fader::setDisplayConversion(), and lmms::gui::Fader::updateTextFloat().
m_description
QString lmms::gui::AutomatableModelView::m_description protected
Definition at line 83 of file AutomatableModelView.h.
Referenced by lmms::gui::CustomTextKnob::displayValue(), lmms::gui::FloatModelEditorBase::displayValue(), setDescription(), and lmms::gui::Fader::updateTextFloat().
m_unit
QString lmms::gui::AutomatableModelView::m_unit protected
Definition at line 84 of file AutomatableModelView.h.
Referenced by addDefaultActions(), lmms::gui::FloatModelEditorBase::displayValue(), setUnit(), and lmms::gui::Fader::updateTextFloat().
The documentation for this class was generated from the following files:
include/AutomatableModelView.h
src/gui/AutomatableModelView.cpp