LMMS: lmms::gui::SendButtonIndicator Class Reference
lmms::gui::SendButtonIndicator Class Reference
#include <SendButtonIndicator.h>
Public Member Functions
SendButtonIndicator (QWidget *parent, MixerChannelView *owner, MixerView *mv)
void mousePressEvent (QMouseEvent *e) override
void updateLightStatus ()
Private Member Functions
FloatModel * getSendModel ()
Private Attributes
MixerView * m_mv
MixerChannelView * m_parent
QPixmap m_qpmOff = embed::getIconPixmap("mixer_send_off", 29, 20)
QPixmap m_qpmOn = embed::getIconPixmap("mixer_send_on", 29, 20)
Detailed Description
Definition at line 43 of file SendButtonIndicator.h.
Constructor & Destructor Documentation
SendButtonIndicator()
lmms::gui::SendButtonIndicator::SendButtonIndicator (QWidget * parent, MixerChannelView * owner, MixerView * mv)
Definition at line 11 of file SendButtonIndicator.cpp.
References m_mv, m_parent, and m_qpmOff.
Member Function Documentation
getSendModel()
FloatModel * lmms::gui::SendButtonIndicator::getSendModel () private
Definition at line 43 of file SendButtonIndicator.cpp.
References lmms::Mixer::channelSendModel(), m_mv, m_parent, and lmms::Engine::mixer().
Referenced by updateLightStatus().
mousePressEvent()
void lmms::gui::SendButtonIndicator::mousePressEvent (QMouseEvent * e) override
Definition at line 22 of file SendButtonIndicator.cpp.
References lmms::Mixer::channelSendModel(), lmms::Mixer::createChannelSend(), lmms::Mixer::deleteChannelSend(), m_mv, m_parent, lmms::Engine::mixer(), and updateLightStatus().
updateLightStatus()
void lmms::gui::SendButtonIndicator::updateLightStatus ()
Definition at line 49 of file SendButtonIndicator.cpp.
References getSendModel(), m_qpmOff, and m_qpmOn.
Referenced by mousePressEvent().
Member Data Documentation
m_mv
MixerView* lmms::gui::SendButtonIndicator::m_mv private
Definition at line 54 of file SendButtonIndicator.h.
Referenced by SendButtonIndicator(), getSendModel(), and mousePressEvent().
m_parent
MixerChannelView* lmms::gui::SendButtonIndicator::m_parent private
Definition at line 53 of file SendButtonIndicator.h.
Referenced by SendButtonIndicator(), getSendModel(), and mousePressEvent().
m_qpmOff
QPixmap lmms::gui::SendButtonIndicator::m_qpmOff = embed::getIconPixmap("mixer_send_off", 29, 20) private
Definition at line 55 of file SendButtonIndicator.h.
Referenced by SendButtonIndicator(), and updateLightStatus().
m_qpmOn
QPixmap lmms::gui::SendButtonIndicator::m_qpmOn = embed::getIconPixmap("mixer_send_on", 29, 20) private
Definition at line 56 of file SendButtonIndicator.h.
Referenced by updateLightStatus().
The documentation for this class was generated from the following files:
include/SendButtonIndicator.h
src/gui/SendButtonIndicator.cpp