LMMS: Jack::JackLibSampleRateResampler Class Reference
Jack::JackLibSampleRateResampler Class Reference
Resampler using "libsamplerate" (http://www.mega-nerd.com/SRC/).
#include <JackLibSampleRateResampler.h>
Public Member Functions
JackLibSampleRateResampler ()
JackLibSampleRateResampler (unsigned int quality)
virtual ~JackLibSampleRateResampler ()
unsigned int ReadResample (jack_default_audio_sample_t *buffer, unsigned int frames)
void Reset (unsigned int new_size)
unsigned int WriteResample (jack_default_audio_sample_t *buffer, unsigned int frames)
Public Member Functions inherited from Jack::JackResampler
JackResampler ()
virtual ~JackResampler ()
double GetRatio ()
void SetRatio (double ratio)
Public Member Functions inherited from Jack::JackRingBuffer
JackRingBuffer (int size=DEFAULT_RB_SIZE)
virtual ~JackRingBuffer ()
unsigned int GetError ()
virtual unsigned int Read (jack_default_audio_sample_t *buffer, unsigned int frames)
virtual unsigned int Read (void *buffer, unsigned int bytes)
virtual unsigned int ReadSpace ()
virtual unsigned int Write (jack_default_audio_sample_t *buffer, unsigned int frames)
virtual unsigned int Write (void *buffer, unsigned int bytes)
virtual unsigned int WriteSpace ()
Private Attributes
SRC_STATE * fResampler
Additional Inherited Members
Protected Attributes inherited from Jack::JackResampler
double fRatio
Protected Attributes inherited from Jack::JackRingBuffer
jack_ringbuffer_t * fRingBuffer
unsigned int fRingBufferSize
Detailed Description
Resampler using "libsamplerate" (http://www.mega-nerd.com/SRC/).
Definition at line 33 of file JackLibSampleRateResampler.h.
Constructor & Destructor Documentation
JackLibSampleRateResampler() [1/2]
Jack::JackLibSampleRateResampler::JackLibSampleRateResampler ()
Definition at line 26 of file JackLibSampleRateResampler.cpp.
References Jack::JackResampler::JackResampler(), fResampler, and jack_error.
JackLibSampleRateResampler() [2/2]
Jack::JackLibSampleRateResampler::JackLibSampleRateResampler (unsigned int quality)
Definition at line 36 of file JackLibSampleRateResampler.cpp.
References Jack::JackResampler::JackResampler(), fResampler, and jack_error.
~JackLibSampleRateResampler()
Jack::JackLibSampleRateResampler::~JackLibSampleRateResampler () virtual
Definition at line 68 of file JackLibSampleRateResampler.cpp.
References fResampler.
Member Function Documentation
ReadResample()
unsigned int Jack::JackLibSampleRateResampler::ReadResample (jack_default_audio_sample_t * buffer, unsigned int frames) virtual
Reimplemented from Jack::JackResampler.
Definition at line 79 of file JackLibSampleRateResampler.cpp.
References Jack::JackResampler::fRatio, fResampler, Jack::JackRingBuffer::fRingBuffer, j, jack_error, jack_log(), jack_ringbuffer_get_read_vector(), and jack_ringbuffer_read_advance().
Reset()
void Jack::JackLibSampleRateResampler::Reset (unsigned int new_size) virtual
Reimplemented from Jack::JackRingBuffer.
Definition at line 73 of file JackLibSampleRateResampler.cpp.
References fResampler, and Jack::JackRingBuffer::Reset().
WriteResample()
unsigned int Jack::JackLibSampleRateResampler::WriteResample (jack_default_audio_sample_t * buffer, unsigned int frames) virtual
Reimplemented from Jack::JackResampler.
Definition at line 129 of file JackLibSampleRateResampler.cpp.
References Jack::JackResampler::fRatio, fResampler, Jack::JackRingBuffer::fRingBuffer, j, jack_error, jack_log(), jack_ringbuffer_get_write_vector(), and jack_ringbuffer_write_advance().
Member Data Documentation
fResampler
SRC_STATE* Jack::JackLibSampleRateResampler::fResampler private
Definition at line 38 of file JackLibSampleRateResampler.h.
Referenced by JackLibSampleRateResampler(), JackLibSampleRateResampler(), ~JackLibSampleRateResampler(), ReadResample(), Reset(), and WriteResample().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackLibSampleRateResampler.h
src/3rdparty/jack2/common/JackLibSampleRateResampler.cpp