LMMS: Jack::JackQuitException Class Reference
Jack::JackQuitException Class Reference
#include <JackException.h>
Public Member Functions
JackQuitException ()
JackQuitException (char *msg)
JackQuitException (const char *msg)
JackQuitException (const std::string &msg)
Public Member Functions inherited from Jack::JackException
JackException (char *msg)
JackException (const char *msg)
JackException (const std::string &msg)
std::string Message ()
void PrintMessage ()
Detailed Description
Definition at line 85 of file JackException.h.
Constructor & Destructor Documentation
JackQuitException() [1/4]
Jack::JackQuitException::JackQuitException (const std::string & msg) inline
Definition at line 89 of file JackException.h.
References Jack::JackException::JackException().
JackQuitException() [2/4]
Jack::JackQuitException::JackQuitException (char * msg) inline
Definition at line 91 of file JackException.h.
References Jack::JackException::JackException().
JackQuitException() [3/4]
Jack::JackQuitException::JackQuitException (const char * msg) inline
Definition at line 93 of file JackException.h.
References Jack::JackException::JackException().
JackQuitException() [4/4]
Jack::JackQuitException::JackQuitException () inline
Definition at line 95 of file JackException.h.
References Jack::JackException::JackException().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackException.h