LMMS: Jack::JackLoopFeedback< SIZE > Class Template Reference
Jack::JackLoopFeedback< SIZE > Class Template Reference
Utility class.
#include <JackConnectionManager.h>
Public Member Functions
JackLoopFeedback ()
bool DecConnection (int ref1, int ref2)
int GetConnectionIndex (int ref1, int ref2) const
Test if a connection between 2 refnum is a feedback connection.
bool IncConnection (int ref1, int ref2)
void Init ()
Private Member Functions
bool AddConnectionAux (int ref1, int ref2)
Add a feedback connection between 2 refnum.
int DecConnection (int index)
int IncConnection (int index)
bool RemoveConnectionAux (int ref1, int ref2)
Remove a feedback connection between 2 refnum.
Private Attributes
int fTable [SIZE][3]
Detailed Description
template<int SIZE>
class Jack::JackLoopFeedback< SIZE >
Utility class.
Definition at line 261 of file JackConnectionManager.h.
Constructor & Destructor Documentation
JackLoopFeedback()
template<int SIZE> Jack::JackLoopFeedback< SIZE >::JackLoopFeedback () inline
Definition at line 317 of file JackConnectionManager.h.
References Init().
Member Function Documentation
AddConnectionAux()
template<int SIZE> bool Jack::JackLoopFeedback< SIZE >::AddConnectionAux (int ref1, int ref2) inline private
Add a feedback connection between 2 refnum.
Definition at line 270 of file JackConnectionManager.h.
References EMPTY, fTable, i, jack_error, jack_log(), and SIZE.
Referenced by IncConnection().
DecConnection() [1/2]
template<int SIZE> int Jack::JackLoopFeedback< SIZE >::DecConnection (int index) inline private
Definition at line 309 of file JackConnectionManager.h.
References fTable.
Referenced by DecConnection().
DecConnection() [2/2]
template<int SIZE> bool Jack::JackLoopFeedback< SIZE >::DecConnection (int ref1, int ref2) inline
Definition at line 343 of file JackConnectionManager.h.
References DecConnection(), GetConnectionIndex(), jack_log(), and RemoveConnectionAux().
GetConnectionIndex()
template<int SIZE> int Jack::JackLoopFeedback< SIZE >::GetConnectionIndex (int ref1, int ref2) const inline
Test if a connection between 2 refnum is a feedback connection.
Definition at line 358 of file JackConnectionManager.h.
References fTable, i, and SIZE.
Referenced by DecConnection(), and IncConnection().
IncConnection() [1/2]
template<int SIZE> int Jack::JackLoopFeedback< SIZE >::IncConnection (int index) inline private
Definition at line 303 of file JackConnectionManager.h.
References fTable.
Referenced by IncConnection().
IncConnection() [2/2]
template<int SIZE> bool Jack::JackLoopFeedback< SIZE >::IncConnection (int ref1, int ref2) inline
Definition at line 331 of file JackConnectionManager.h.
References AddConnectionAux(), GetConnectionIndex(), and IncConnection().
Init()
template<int SIZE> void Jack::JackLoopFeedback< SIZE >::Init () inline
Definition at line 322 of file JackConnectionManager.h.
References EMPTY, fTable, i, and SIZE.
Referenced by JackLoopFeedback().
RemoveConnectionAux()
template<int SIZE> bool Jack::JackLoopFeedback< SIZE >::RemoveConnectionAux (int ref1, int ref2) inline private
Remove a feedback connection between 2 refnum.
Definition at line 288 of file JackConnectionManager.h.
References EMPTY, fTable, i, jack_error, jack_log(), and SIZE.
Referenced by DecConnection().
Member Data Documentation
fTable
template<int SIZE> int Jack::JackLoopFeedback< SIZE >::fTable[SIZE][3] private
Definition at line 265 of file JackConnectionManager.h.
Referenced by AddConnectionAux(), DecConnection(), GetConnectionIndex(), IncConnection(), Init(), and RemoveConnectionAux().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackConnectionManager.h