LMMS: hiir::StageProcF64Sse2< CUR > Class Template Reference
hiir::StageProcF64Sse2< CUR > Class Template Reference
#include <StageProcF64Sse2.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg_rec (__m128d &, StageDataF64Sse2 *) noexcept
hiir_FORCEINLINE void process_sample_pos_rec (__m128d &, StageDataF64Sse2 *) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (__m128d &x, StageDataF64Sse2 *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_neg_rec (__m128d &x, StageDataF64Sse2 *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (__m128d &x, StageDataF64Sse2 *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos_rec (__m128d &x, StageDataF64Sse2 *stage_arr) noexcept
Private Member Functions
StageProcF64Sse2 ()=delete
StageProcF64Sse2 (const StageProcF64Sse2 &other)=delete
StageProcF64Sse2 (StageProcF64Sse2 &&other)=delete
~StageProcF64Sse2 ()=delete
bool operator!= (const StageProcF64Sse2 &other) const =delete
StageProcF64Sse2 & operator= (const StageProcF64Sse2 &other)=delete
StageProcF64Sse2 & operator= (StageProcF64Sse2 &&other)=delete
bool operator== (const StageProcF64Sse2 &other) const =delete
Detailed Description
template<int CUR>
class hiir::StageProcF64Sse2< CUR >
Definition at line 40 of file StageProcF64Sse2.h.
Constructor & Destructor Documentation
StageProcF64Sse2() [1/3]
template<int CUR> hiir::StageProcF64Sse2< CUR >::StageProcF64Sse2 () private delete
Referenced by StageProcF64Sse2(), StageProcF64Sse2(), ~StageProcF64Sse2(), operator!=(), operator=(), operator=(), operator==(), process_sample_neg_rec(), and process_sample_pos_rec().
StageProcF64Sse2() [2/3]
template<int CUR> hiir::StageProcF64Sse2< CUR >::StageProcF64Sse2 (const StageProcF64Sse2< CUR > & other) private delete
References StageProcF64Sse2().
StageProcF64Sse2() [3/3]
template<int CUR> hiir::StageProcF64Sse2< CUR >::StageProcF64Sse2 (StageProcF64Sse2< CUR > && other) private delete
References StageProcF64Sse2().
~StageProcF64Sse2()
template<int CUR> hiir::StageProcF64Sse2< CUR >::~StageProcF64Sse2 () private delete
References StageProcF64Sse2().
Member Function Documentation
operator!=()
template<int CUR> bool hiir::StageProcF64Sse2< CUR >::operator!= (const StageProcF64Sse2< CUR > & other) const private delete
References StageProcF64Sse2().
operator=() [1/2]
template<int CUR> StageProcF64Sse2 & hiir::StageProcF64Sse2< CUR >::operator= (const StageProcF64Sse2< CUR > & other) private delete
References StageProcF64Sse2().
operator=() [2/2]
template<int CUR> StageProcF64Sse2 & hiir::StageProcF64Sse2< CUR >::operator= (StageProcF64Sse2< CUR > && other) private delete
References StageProcF64Sse2().
operator==()
template<int CUR> bool hiir::StageProcF64Sse2< CUR >::operator== (const StageProcF64Sse2< CUR > & other) const private delete
References StageProcF64Sse2().
process_sample_neg()
template<int CUR> void hiir::StageProcF64Sse2< CUR >::process_sample_neg (__m128d & x, StageDataF64Sse2 * stage_arr) static noexcept
Definition at line 46 of file StageProcF64Sse2.hpp.
References process_sample_neg_rec().
Referenced by hiir::PhaseHalfPiF64Sse2< NC >::process_block(), and hiir::PhaseHalfPiF64Sse2< NC >::process_sample().
process_sample_neg_rec() [1/2]
hiir_FORCEINLINE void hiir::StageProcF64Sse2< 0 >::process_sample_neg_rec (__m128d & , StageDataF64Sse2 *) noexcept
Definition at line 89 of file StageProcF64Sse2.hpp.
References hiir_FORCEINLINE.
process_sample_neg_rec() [2/2]
template<int CUR> void hiir::StageProcF64Sse2< CUR >::process_sample_neg_rec (__m128d & x, StageDataF64Sse2 * stage_arr) static noexcept
Definition at line 76 of file StageProcF64Sse2.hpp.
References StageProcF64Sse2(), and process_sample_neg_rec().
Referenced by process_sample_neg(), and process_sample_neg_rec().
process_sample_pos()
template<int CUR> void hiir::StageProcF64Sse2< CUR >::process_sample_pos (__m128d & x, StageDataF64Sse2 * stage_arr) static noexcept
Definition at line 37 of file StageProcF64Sse2.hpp.
References process_sample_pos_rec().
Referenced by hiir::HalfBandF64Sse2< NC >::process_2_paths(), hiir::HalfBandF64Sse2< NC >::process_block_2_paths(), hiir::Downsampler2xF64Sse2< NC >::process_block_double(), hiir::Upsampler2xF64Sse2< NC >::process_block_double(), hiir::Downsampler2xF64Sse2< NC >::process_sample(), hiir::Upsampler2xF64Sse2< NC >::process_sample(), and hiir::Downsampler2xF64Sse2< NC >::process_sample_split().
process_sample_pos_rec() [1/2]
hiir_FORCEINLINE void hiir::StageProcF64Sse2< 0 >::process_sample_pos_rec (__m128d & , StageDataF64Sse2 *) noexcept
Definition at line 68 of file StageProcF64Sse2.hpp.
References hiir_FORCEINLINE.
process_sample_pos_rec() [2/2]
template<int CUR> void hiir::StageProcF64Sse2< CUR >::process_sample_pos_rec (__m128d & x, StageDataF64Sse2 * stage_arr) static noexcept
Definition at line 55 of file StageProcF64Sse2.hpp.
References StageProcF64Sse2(), and process_sample_pos_rec().
Referenced by process_sample_pos(), and process_sample_pos_rec().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProcF64Sse2.h
src/3rdparty/hiir/hiir/StageProcF64Sse2.hpp