LMMS: lmms::gui::TextFloat Class Reference
lmms::gui::TextFloat Class Reference
#include <TextFloat.h>
Public Member Functions
TextFloat ()
~TextFloat () override=default
void moveGlobal (QWidget *w, const QPoint &offset)
void setPixmap (const QPixmap &pixmap)
void setText (const QString &text)
void setTitle (const QString &title)
void setVisibilityTimeOut (int msecs)
Static Public Member Functions
static TextFloat * displayMessage (const QString &title, const QString &msg, const QPixmap &pixmap=QPixmap(), int timeout=2000, QWidget *parent=nullptr)
Protected Member Functions
void mousePressEvent (QMouseEvent *me) override
Private Member Functions
TextFloat (const QString &title, const QString &text, const QPixmap &pixmap)
Private Attributes
QLabel * m_pixmapLabel
QLabel * m_textLabel
QLabel * m_titleLabel
Detailed Description
Definition at line 37 of file TextFloat.h.
Constructor & Destructor Documentation
TextFloat() [1/2]
lmms::gui::TextFloat::TextFloat ()
Definition at line 39 of file TextFloat.cpp.
References TextFloat().
Referenced by TextFloat(), ~TextFloat(), and displayMessage().
~TextFloat()
lmms::gui::TextFloat::~TextFloat () override default
References TextFloat(), displayMessage(), setPixmap(), setText(), setTitle(), and setVisibilityTimeOut().
TextFloat() [2/2]
lmms::gui::TextFloat::TextFloat (const QString & title, const QString & text, const QPixmap & pixmap) private
Definition at line 44 of file TextFloat.cpp.
References lmms::gui::getGUI(), m_pixmapLabel, m_textLabel, m_titleLabel, setPixmap(), setText(), and setTitle().
Member Function Documentation
displayMessage()
TextFloat * lmms::gui::TextFloat::displayMessage (const QString & title, const QString & msg, const QPixmap & pixmap = QPixmap(), int timeout = 2000, QWidget * parent = nullptr) static
Definition at line 98 of file TextFloat.cpp.
References TextFloat(), lmms::gui::getGUI(), and lmms::gui::GuiApplication::mainWindow().
Referenced by lmms::gui::LmmsStyle::LmmsStyle(), ~TextFloat(), lmms::gui::AutomationClipView::dropEvent(), lmms::gui::AutomationEditorWindow::dropEvent(), lmms::gui::PianoRollWindow::exportMidiClip(), lmms::gui::MainWindow::handleSaveResult(), lmms::gui::PianoRollWindow::importMidiClip(), lmms::gui::EnvelopeAndLfoView::lfoUserWaveChanged(), lmms::DataFile::loadData(), lmms::TrackContainer::loadSettings(), lmms::gui::ClipView::mousePressEvent(), lmms::gui::TimeLineWidget::mousePressEvent(), lmms::gui::FileBrowserTreeWidget::previewFileItem(), and lmms::gui::StepRecorderWidget::showHint().
mousePressEvent()
void lmms::gui::TextFloat::mousePressEvent (QMouseEvent * me) override protected
Definition at line 128 of file TextFloat.cpp.
moveGlobal()
void lmms::gui::TextFloat::moveGlobal (QWidget * w, const QPoint & offset) inline
Definition at line 56 of file TextFloat.h.
setPixmap()
void lmms::gui::TextFloat::setPixmap (const QPixmap & pixmap)
Definition at line 86 of file TextFloat.cpp.
References m_pixmapLabel.
Referenced by TextFloat(), and ~TextFloat().
setText()
void lmms::gui::TextFloat::setText (const QString & text)
Definition at line 80 of file TextFloat.cpp.
References m_textLabel.
Referenced by TextFloat(), and ~TextFloat().
setTitle()
void lmms::gui::TextFloat::setTitle (const QString & title)
Definition at line 74 of file TextFloat.cpp.
References m_titleLabel.
Referenced by TextFloat(), and ~TextFloat().
setVisibilityTimeOut()
void lmms::gui::TextFloat::setVisibilityTimeOut (int msecs)
Definition at line 92 of file TextFloat.cpp.
Referenced by ~TextFloat().
Member Data Documentation
m_pixmapLabel
QLabel* lmms::gui::TextFloat::m_pixmapLabel private
Definition at line 69 of file TextFloat.h.
Referenced by TextFloat(), and setPixmap().
m_textLabel
QLabel* lmms::gui::TextFloat::m_textLabel private
Definition at line 71 of file TextFloat.h.
Referenced by TextFloat(), and setText().
m_titleLabel
QLabel* lmms::gui::TextFloat::m_titleLabel private
Definition at line 70 of file TextFloat.h.
Referenced by TextFloat(), and setTitle().
The documentation for this class was generated from the following files:
include/TextFloat.h
src/gui/widgets/TextFloat.cpp