LMMS: lmms::gui::ToolPluginView Class Reference
lmms::gui::ToolPluginView Class Reference
#include <ToolPluginView.h>
Public Member Functions
ToolPluginView (ToolPlugin *_toolPlugin)
Public Member Functions inherited from lmms::gui::PluginView
PluginView (Plugin *_plugin, QWidget *_parent)
virtual bool isResizable () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Detailed Description
Definition at line 40 of file ToolPluginView.h.
Constructor & Destructor Documentation
ToolPluginView()
lmms::gui::ToolPluginView::ToolPluginView (ToolPlugin * _toolPlugin)
Definition at line 39 of file ToolPluginView.cpp.
References lmms::gui::PluginView::PluginView(), lmms::gui::MainWindow::addWindowedWidget(), lmms::Plugin::descriptor(), lmms::Plugin::displayName(), lmms::gui::getGUI(), lmms::Plugin::Descriptor::logo, lmms::gui::GuiApplication::mainWindow(), and lmms::PixmapLoader::pixmap().
The documentation for this class was generated from the following files:
include/ToolPluginView.h
src/gui/ToolPluginView.cpp