LMMS: lmms::gui::PluginDescWidget Class Reference
lmms::gui::PluginDescWidget Class Reference
#include <PluginBrowser.h>
Public Types
using PluginKey = Plugin::Descriptor::SubPluginFeatures::Key
Public Member Functions
PluginDescWidget (const PluginKey &_pk, QWidget *_parent)
QString name () const
void openInNewInstrumentTrack (QString value)
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e) override
void enterEvent (QEvent *_e) override
void leaveEvent (QEvent *_e) override
void mousePressEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *_pe) override
Private Attributes
QPixmap m_logo
bool m_mouseOver
PluginKey m_pluginKey
Static Private Attributes
static constexpr int DEFAULT_HEIGHT {24}
Detailed Description
Definition at line 58 of file PluginBrowser.h.
Member Typedef Documentation
PluginKey
using lmms::gui::PluginDescWidget::PluginKey = Plugin::Descriptor::SubPluginFeatures::Key
Definition at line 62 of file PluginBrowser.h.
Constructor & Destructor Documentation
PluginDescWidget()
lmms::gui::PluginDescWidget::PluginDescWidget (const PluginKey & _pk, QWidget * _parent)
Definition at line 206 of file PluginBrowser.cpp.
References DEFAULT_HEIGHT, lmms::Plugin::Descriptor::SubPluginFeatures::Key::desc, lmms::Plugin::Descriptor::description, lmms::Plugin::Descriptor::SubPluginFeatures::Key::description(), m_logo, m_mouseOver, m_pluginKey, and lmms::Plugin::Descriptor::subPluginFeatures.
Member Function Documentation
contextMenuEvent()
void lmms::gui::PluginDescWidget::contextMenuEvent (QContextMenuEvent * e) override protected
Definition at line 295 of file PluginBrowser.cpp.
References m_pluginKey, and openInNewInstrumentTrack().
enterEvent()
void lmms::gui::PluginDescWidget::enterEvent (QEvent * _e) override protected
Definition at line 263 of file PluginBrowser.cpp.
References m_mouseOver.
leaveEvent()
void lmms::gui::PluginDescWidget::leaveEvent (QEvent * _e) override protected
Definition at line 273 of file PluginBrowser.cpp.
References m_mouseOver.
Referenced by mousePressEvent().
mousePressEvent()
void lmms::gui::PluginDescWidget::mousePressEvent (QMouseEvent * _me) override protected
Definition at line 283 of file PluginBrowser.cpp.
References leaveEvent(), m_logo, m_pluginKey, and lmms::Engine::setDndPluginKey().
name()
QString lmms::gui::PluginDescWidget::name () const
Definition at line 224 of file PluginBrowser.cpp.
References m_pluginKey.
openInNewInstrumentTrack()
void lmms::gui::PluginDescWidget::openInNewInstrumentTrack (QString value)
Definition at line 306 of file PluginBrowser.cpp.
References lmms::Track::create(), lmms::Engine::getSong(), and lmms::Track::Instrument.
Referenced by contextMenuEvent().
paintEvent()
void lmms::gui::PluginDescWidget::paintEvent (QPaintEvent * _pe) override protected
Definition at line 232 of file PluginBrowser.cpp.
References m_logo, m_mouseOver, and m_pluginKey.
Member Data Documentation
DEFAULT_HEIGHT
int lmms::gui::PluginDescWidget::DEFAULT_HEIGHT {24} static constexpr private
Definition at line 75 of file PluginBrowser.h.
Referenced by PluginDescWidget().
m_logo
QPixmap lmms::gui::PluginDescWidget::m_logo private
Definition at line 78 of file PluginBrowser.h.
Referenced by PluginDescWidget(), mousePressEvent(), and paintEvent().
m_mouseOver
bool lmms::gui::PluginDescWidget::m_mouseOver private
Definition at line 80 of file PluginBrowser.h.
Referenced by PluginDescWidget(), enterEvent(), leaveEvent(), and paintEvent().
m_pluginKey
PluginKey lmms::gui::PluginDescWidget::m_pluginKey private
Definition at line 77 of file PluginBrowser.h.
Referenced by PluginDescWidget(), contextMenuEvent(), mousePressEvent(), name(), and paintEvent().
The documentation for this class was generated from the following files:
include/PluginBrowser.h
src/gui/PluginBrowser.cpp