LMMS: Jack::JackLibGlobals Struct Reference
Jack::JackLibGlobals Struct Reference
Global library static structure: singleton kind of pattern.
#include <JackLibGlobals.h>
Public Member Functions
JackLibGlobals ()
~JackLibGlobals ()
Static Public Member Functions
static void Destroy ()
static void Init ()
Public Attributes
JackShmReadWritePtr< JackEngineControl > fEngineControl
Shared memory Port manager.
JackShmReadWritePtr< JackGraphManager > fGraphManager
JackMetadata * fMetadata
Shared synchro table.
sigset_t fProcessSignals
Shared metadata base.
JackSynchro fSynchroTable [CLIENT_NUM]
Shared engine control.
Static Public Attributes
static int fClientCount = 0
static JackLibGlobals * fGlobals = NULL
Detailed Description
Global library static structure: singleton kind of pattern.
Definition at line 53 of file JackLibGlobals.h.
Constructor & Destructor Documentation
JackLibGlobals()
Jack::JackLibGlobals::JackLibGlobals () inline
Definition at line 64 of file JackLibGlobals.h.
References Jack::JackMessageBuffer::Create(), fEngineControl, fGraphManager, fMetadata, fProcessSignals, jack_error, and jack_log().
Referenced by Init().
~JackLibGlobals()
Jack::JackLibGlobals::~JackLibGlobals () inline
Definition at line 86 of file JackLibGlobals.h.
References CLIENT_NUM, Jack::JackMessageBuffer::Destroy(), fMetadata, fProcessSignals, fSynchroTable, i, and jack_log().
Member Function Documentation
Destroy()
void Jack::JackLibGlobals::Destroy () inline static
Definition at line 133 of file JackLibGlobals.h.
References EndTime(), fClientCount, fGlobals, and jack_log().
Referenced by jack_client_close(), jack_client_new_aux(), and jack_client_open_aux().
Init()
void Jack::JackLibGlobals::Init () inline static
Definition at line 105 of file JackLibGlobals.h.
References JackLibGlobals(), client(), CLIENT_NUM, fClientCount, Jack::JackGlobals::fClientTable, fGlobals, Jack::JackGlobals::fServerRunning, i, InitTime(), jack_error, and jack_log().
Referenced by jack_client_new_aux(), and jack_client_open_aux().
Member Data Documentation
fClientCount
int JackLibGlobals::fClientCount = 0 static
Definition at line 61 of file JackLibGlobals.h.
Referenced by Destroy(), and Init().
fEngineControl
JackShmReadWritePtr<JackEngineControl> Jack::JackLibGlobals::fEngineControl
Shared memory Port manager.
Definition at line 56 of file JackLibGlobals.h.
Referenced by JackLibGlobals().
fGlobals
JackLibGlobals * JackLibGlobals::fGlobals = NULL static
Definition at line 62 of file JackLibGlobals.h.
Referenced by Destroy(), Jack::JackLibClient::GetEngineControl(), Jack::JackLibClient::GetGraphManager(), Init(), and Jack::JackLibClient::Open().
fGraphManager
JackShmReadWritePtr<JackGraphManager> Jack::JackLibGlobals::fGraphManager
Definition at line 55 of file JackLibGlobals.h.
Referenced by JackLibGlobals().
fMetadata
JackMetadata* Jack::JackLibGlobals::fMetadata
Shared synchro table.
Definition at line 58 of file JackLibGlobals.h.
Referenced by JackLibGlobals(), and ~JackLibGlobals().
fProcessSignals
sigset_t Jack::JackLibGlobals::fProcessSignals
Shared metadata base.
Definition at line 59 of file JackLibGlobals.h.
Referenced by JackLibGlobals(), and ~JackLibGlobals().
fSynchroTable
JackSynchro Jack::JackLibGlobals::fSynchroTable[CLIENT_NUM]
Shared engine control.
Definition at line 57 of file JackLibGlobals.h.
Referenced by ~JackLibGlobals().
The documentation for this struct was generated from the following files:
src/3rdparty/jack2/common/JackLibGlobals.h
src/3rdparty/jack2/common/JackLibAPI.cpp