LMMS: lmms::Instrument Class Reference
lmms::Instrument Class Reference
#include <Instrument.h>
Public Types
enum class Flag {
NoFlags = 0x00 ,
IsSingleStreamed = 0x01 ,
IsMidiBased = 0x02 ,
IsNotBendable = 0x04
}
using Flags = lmms::Flags<Flag>
Public Types inherited from lmms::Plugin
using DescriptorList = QList<Descriptor*>
enum class Type {
Instrument ,
Effect ,
ImportFilter ,
ExportFilter ,
Tool ,
Library ,
Other ,
Undefined = 255
}
Public Member Functions
Instrument (InstrumentTrack *_instrument_track, const Descriptor *_descriptor, const Descriptor::SubPluginFeatures::Key *key=nullptr, Flags flags=Flag::NoFlags)
~Instrument () override=default
virtual f_cnt_t beatLen (NotePlayHandle *_n) const
virtual void deleteNotePluginData (NotePlayHandle *_note_to_play)
f_cnt_t desiredReleaseFrames () const
virtual float desiredReleaseTimeMs () const
QString fullDisplayName () const override
sample_rate_t getSampleRate () const
virtual bool handleMidiEvent (const MidiEvent &, const TimePos &=TimePos(), f_cnt_t offset=0)
virtual bool hasNoteInput () const
InstrumentTrack * instrumentTrack () const
bool isBendable () const
virtual bool isFromTrack (const Track *_track) const
bool isMidiBased () const
bool isSingleStreamed () const
virtual void play (SampleFrame *_working_buffer)
virtual void playNote (NotePlayHandle *, SampleFrame *)
Public Member Functions inherited from lmms::Plugin
Plugin (const Descriptor *descriptor, Model *parent, const Descriptor::SubPluginFeatures::Key *key=nullptr)
Constructor of a plugin.
~Plugin () override=default
virtual AutomatableModel * childModel (const QString &modelName)
Called if external source needs to change something but we cannot reference the class header.
gui::PluginView * createView (QWidget *parent)
Create a view for the model.
const Descriptor * descriptor () const
Return plugin Descriptor.
QString displayName () const override
Return display-name out of sub plugin or descriptor.
const Descriptor::SubPluginFeatures::Key & key () const
Return the key referencing this plugin.
virtual void loadFile (const QString &file)
Can be called if a file matching supportedFileTypes should be loaded/processed with the help of this plugin.
const PixmapLoader * logo () const
Return logo out of sub plugin or descriptor.
Type type () const
Return plugin type.
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static Instrument * instantiate (const QString &_plugin_name, InstrumentTrack *_instrument_track, const Plugin::Descriptor::SubPluginFeatures::Key *key, bool keyFromDnd=false)
instantiate instrument-plugin with given name or return NULL on failure
Static Public Member Functions inherited from lmms::Plugin
static Plugin * instantiate (const QString &pluginName, Model *parent, void *data)
Return an instance of a plugin whose name matches to given one if specified plugin couldn't be loaded, it creates a dummy-plugin.
static Plugin * instantiateWithKey (const QString &pluginName, Model *parent, const Descriptor::SubPluginFeatures::Key *key, bool keyFromDnd=false)
Overload if the argument passed to the plugin is a subPluginKey If you can not pass the key and are aware that it's stored in Engine::pickDndPluginKey(), use this function, too.
Protected Member Functions
void applyFadeIn (SampleFrame *buf, NotePlayHandle *n)
void applyRelease (SampleFrame *buf, const NotePlayHandle *_n)
float computeReleaseTimeMsByFrameCount (f_cnt_t frames) const
Protected Member Functions inherited from lmms::Plugin
void collectErrorForUI (QString errMsg)
virtual gui::PluginView * instantiateView (QWidget *)=0
Create a view for the model.
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Member Functions inherited from lmms::SerializingObject
virtual void loadSettings (const QDomElement &element)=0
virtual void saveSettings (QDomDocument &doc, QDomElement &element)=0
Private Attributes
Flags m_flags
InstrumentTrack * m_instrumentTrack
Additional Inherited Members
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Detailed Description
Definition at line 51 of file Instrument.h.
Member Typedef Documentation
Flags
using lmms::Instrument::Flags = lmms::Flags<Flag>
Definition at line 62 of file Instrument.h.
Member Enumeration Documentation
Flag
enum class lmms::Instrument::Flag strong
Enumerator
NoFlags
IsSingleStreamed
IsMidiBased
Instrument provides a single audio stream for all notes.
IsNotBendable
Instrument is controlled by MIDI events rather than NotePlayHandles.
Definition at line 54 of file Instrument.h.
Constructor & Destructor Documentation
Instrument()
lmms::Instrument::Instrument (InstrumentTrack * _instrument_track, const Descriptor * _descriptor, const Descriptor::SubPluginFeatures::Key * key = nullptr, Flags flags = Flag::NoFlags)
Definition at line 38 of file Instrument.cpp.
References lmms::Plugin::Plugin(), lmms::Plugin::key(), m_flags, and m_instrumentTrack.
Referenced by lmms::DummyInstrument::DummyInstrument(), and instantiate().
~Instrument()
lmms::Instrument::~Instrument () override default
Member Function Documentation
applyFadeIn()
void lmms::Instrument::applyFadeIn (SampleFrame * buf, NotePlayHandle * n) protected
Definition at line 131 of file Instrument.cpp.
References lmms::countZeroCrossings(), lmms::DEFAULT_CHANNELS, lmms::NotePlayHandle::framesLeftForCurrentPeriod(), lmms::getFadeInLength(), lmms::NotePlayHandle::m_fadeInLength, lmms::PlayHandle::offset(), and lmms::NotePlayHandle::totalFramesPlayed().
applyRelease()
void lmms::Instrument::applyRelease (SampleFrame * buf, const NotePlayHandle * _n) protected
Definition at line 182 of file Instrument.cpp.
References lmms::Engine::audioEngine(), lmms::DEFAULT_CHANNELS, desiredReleaseFrames(), lmms::NotePlayHandle::framesLeft(), and lmms::AudioEngine::framesPerPeriod().
beatLen()
f_cnt_t lmms::Instrument::beatLen (NotePlayHandle * _n) const virtual
Definition at line 62 of file Instrument.cpp.
computeReleaseTimeMsByFrameCount()
float lmms::Instrument::computeReleaseTimeMsByFrameCount (f_cnt_t frames) const protected
Definition at line 200 of file Instrument.cpp.
References getSampleRate().
deleteNotePluginData()
void lmms::Instrument::deleteNotePluginData (NotePlayHandle * _note_to_play) virtual
Definition at line 55 of file Instrument.cpp.
desiredReleaseFrames()
f_cnt_t lmms::Instrument::desiredReleaseFrames () const inline
Definition at line 110 of file Instrument.h.
References desiredReleaseTimeMs(), and getSampleRate().
Referenced by applyRelease().
desiredReleaseTimeMs()
virtual float lmms::Instrument::desiredReleaseTimeMs () const inline virtual
Definition at line 103 of file Instrument.h.
Referenced by desiredReleaseFrames().
fullDisplayName()
QString lmms::Instrument::fullDisplayName () const override virtual
Reimplemented from lmms::Model.
Definition at line 212 of file Instrument.cpp.
References lmms::Track::displayName(), and instrumentTrack().
getSampleRate()
sample_rate_t lmms::Instrument::getSampleRate () const
Definition at line 206 of file Instrument.cpp.
References lmms::Engine::audioEngine(), and lmms::AudioEngine::outputSampleRate().
Referenced by computeReleaseTimeMsByFrameCount(), and desiredReleaseFrames().
handleMidiEvent()
virtual bool lmms::Instrument::handleMidiEvent (const MidiEvent & , const TimePos & = TimePos(), f_cnt_t offset = 0) inline virtual
Definition at line 136 of file Instrument.h.
hasNoteInput()
virtual bool lmms::Instrument::hasNoteInput () const inline virtual
Definition at line 74 of file Instrument.h.
instantiate()
Instrument * lmms::Instrument::instantiate (const QString & _plugin_name, InstrumentTrack * _instrument_track, const Plugin::Descriptor::SubPluginFeatures::Key * key, bool keyFromDnd = false) static
instantiate instrument-plugin with given name or return NULL on failure
Definition at line 70 of file Instrument.cpp.
References Instrument(), lmms::Plugin::Plugin(), lmms::Plugin::instantiateWithKey(), and lmms::Plugin::key().
Referenced by lmms::InstrumentTrack::loadInstrument(), and lmms::InstrumentTrack::loadTrackSpecificSettings().
instrumentTrack()
InstrumentTrack * lmms::Instrument::instrumentTrack () const inline
Definition at line 156 of file Instrument.h.
References m_instrumentTrack.
Referenced by fullDisplayName().
isBendable()
bool lmms::Instrument::isBendable () const inline
Definition at line 129 of file Instrument.h.
References IsNotBendable, and m_flags.
isFromTrack()
bool lmms::Instrument::isFromTrack (const Track * _track) const virtual
Definition at line 86 of file Instrument.cpp.
References m_instrumentTrack.
isMidiBased()
bool lmms::Instrument::isMidiBased () const inline
Definition at line 124 of file Instrument.h.
References IsMidiBased, and m_flags.
isSingleStreamed()
bool lmms::Instrument::isSingleStreamed () const inline
Definition at line 119 of file Instrument.h.
References IsSingleStreamed, and m_flags.
play()
void lmms::Instrument::play (SampleFrame * _working_buffer) virtual
Definition at line 48 of file Instrument.cpp.
playNote()
virtual void lmms::Instrument::playNote (NotePlayHandle * , SampleFrame *) inline virtual
Reimplemented in lmms::DummyInstrument.
Definition at line 82 of file Instrument.h.
Member Data Documentation
m_flags
Flags lmms::Instrument::m_flags private
Definition at line 176 of file Instrument.h.
Referenced by Instrument(), isBendable(), isMidiBased(), and isSingleStreamed().
m_instrumentTrack
InstrumentTrack* lmms::Instrument::m_instrumentTrack private
Definition at line 175 of file Instrument.h.
Referenced by Instrument(), instrumentTrack(), and isFromTrack().
The documentation for this class was generated from the following files:
include/Instrument.h
src/core/Instrument.cpp