LMMS: Jack::JackWinMMEDriver Class Reference
Jack::JackWinMMEDriver Class Reference
#include <JackWinMMEDriver.h>
Public Member Functions
JackWinMMEDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
~JackWinMMEDriver ()
int Attach ()
int Close ()
int Open (bool capturing, bool playing, int num_inputs, int num_outputs, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
int Read ()
int Start ()
int Stop ()
int Write ()
Public Member Functions inherited from Jack::JackMidiDriver
JackMidiDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackMidiDriver ()
virtual int Detach ()
virtual int SetBufferSize (jack_nframes_t buffer_size)
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsFixedBufferSize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int ProcessRead ()
int ProcessReadSlaves ()
virtual int ProcessWrite ()
int ProcessWriteSlaves ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
virtual int SetSampleRate (jack_nframes_t sample_rate)
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Attributes
JackWinMMEInputPort ** input_ports
JackWinMMEOutputPort ** output_ports
UINT period
Additional Inherited Members
Protected Member Functions inherited from Jack::JackMidiDriver
JackMidiBuffer * GetInputBuffer (int port_index)
JackMidiBuffer * GetOutputBuffer (int port_index)
virtual int ProcessReadAsync ()
virtual int ProcessReadSync ()
virtual int ProcessWriteAsync ()
virtual int ProcessWriteSync ()
virtual void UpdateLatencies ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
Definition at line 30 of file JackWinMMEDriver.h.
Constructor & Destructor Documentation
JackWinMMEDriver()
JackWinMMEDriver::JackWinMMEDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table)
Definition at line 29 of file JackWinMMEDriver.cpp.
References Jack::JackMidiDriver::JackMidiDriver(), input_ports, output_ports, and period.
~JackWinMMEDriver()
JackWinMMEDriver::~JackWinMMEDriver ()
Definition at line 39 of file JackWinMMEDriver.cpp.
Member Function Documentation
Attach()
int JackWinMMEDriver::Attach () virtual
Reimplemented from Jack::JackMidiDriver.
Definition at line 43 of file JackWinMMEDriver.cpp.
References CaptureDriverFlags, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fClientControl, Jack::JackDriver::fEngine, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, Jack::JackWinMMEPort::GetAlias(), Jack::JackWinMMEPort::GetDeviceName(), Jack::JackWinMMEPort::GetName(), i, input_ports, JACK_DEFAULT_MIDI_TYPE, jack_error, jack_log(), JackCaptureLatency, JackPlaybackLatency, _jack_latency_range::max, _jack_latency_range::min, output_ports, period, PlaybackDriverFlags, Jack::JackPort::SetAlias(), and Jack::JackPort::SetLatencyRange().
Close()
int JackWinMMEDriver::Close () virtual
Reimplemented from Jack::JackDriver.
Definition at line 109 of file JackWinMMEDriver.cpp.
References Jack::JackClientInterface::Close(), Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fPlaybackChannels, i, input_ports, jack_error, output_ports, and period.
Open()
int JackWinMMEDriver::Open (bool capturing, bool playing, int num_inputs, int num_outputs, bool monitor, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency) virtual
Reimplemented from Jack::JackMidiDriver.
Definition at line 139 of file JackWinMMEDriver.cpp.
References capture_latency, Jack::JackDriver::fAliasName, Jack::JackDriver::fClientControl, i, input_ports, jack_error, jack_log(), Jack::JackMidiDriver::Open(), output_ports, period, and playback_latency.
Read()
int JackWinMMEDriver::Read () virtual
Reimplemented from Jack::JackDriver.
Definition at line 252 of file JackWinMMEDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fEngineControl, Jack::JackMidiDriver::GetInputBuffer(), i, and input_ports.
Start()
int JackWinMMEDriver::Start () virtual
Reimplemented from Jack::JackDriver.
Definition at line 274 of file JackWinMMEDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fPlaybackChannels, i, input_ports, jack_error, jack_log(), output_ports, Jack::JackDriverInterface::Start(), Start(), and Stop().
Referenced by Start().
Stop()
int JackWinMMEDriver::Stop () virtual
Reimplemented from Jack::JackDriver.
Definition at line 325 of file JackWinMMEDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fPlaybackChannels, i, input_ports, jack_error, jack_log(), output_ports, Jack::JackDriverInterface::Stop(), and Stop().
Referenced by Start(), and Stop().
Write()
int JackWinMMEDriver::Write () virtual
Reimplemented from Jack::JackDriver.
Definition at line 263 of file JackWinMMEDriver.cpp.
References Jack::JackDriver::fEngineControl, Jack::JackDriver::fPlaybackChannels, Jack::JackMidiDriver::GetOutputBuffer(), i, and output_ports.
Member Data Documentation
input_ports
JackWinMMEInputPort** Jack::JackWinMMEDriver::input_ports private
Definition at line 34 of file JackWinMMEDriver.h.
Referenced by JackWinMMEDriver(), Attach(), Close(), Open(), Read(), Start(), and Stop().
output_ports
JackWinMMEOutputPort** Jack::JackWinMMEDriver::output_ports private
Definition at line 35 of file JackWinMMEDriver.h.
Referenced by JackWinMMEDriver(), Attach(), Close(), Open(), Start(), Stop(), and Write().
period
UINT Jack::JackWinMMEDriver::period private
Definition at line 36 of file JackWinMMEDriver.h.
Referenced by JackWinMMEDriver(), Attach(), Close(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/winmme/JackWinMMEDriver.h
src/3rdparty/jack2/windows/winmme/JackWinMMEDriver.cpp