LMMS: src/3rdparty/jack2/common/JackServerLaunch.h File Reference
JackServerLaunch.h File Reference
#include "varargs.h"
#include "types.h"
Functions
int try_start_server (jack_varargs_t *va, jack_options_t options, jack_status_t *status)
Function Documentation
try_start_server()
int try_start_server (jack_varargs_t * va, jack_options_t options, jack_status_t * status)
Definition at line 253 of file JackPosixServerLaunch.cpp.
References JackFailure, JackServerFailed, JackServerStarted, server_connect(), server_connect(), jack_varargs_t::server_name, start_server(), and start_server().
Referenced by jack_client_new_aux(), and jack_client_open_aux().