LMMS: hiir::Upsampler2xNeonOld< NC > Class Template Reference
hiir::Upsampler2xNeonOld< NC > Class Template Reference
#include <Upsampler2xNeonOld.h>
Public Types
typedef float DataType
Public Member Functions
Upsampler2xNeonOld () noexcept
Upsampler2xNeonOld (const Upsampler2xNeonOld< NC > &other)=default
Upsampler2xNeonOld (Upsampler2xNeonOld< NC > &&other)=default
~Upsampler2xNeonOld ()=default
void clear_buffers () noexcept
Upsampler2xNeonOld< NC > & operator= (const Upsampler2xNeonOld< NC > &other)=default
Upsampler2xNeonOld< NC > & operator= (Upsampler2xNeonOld< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void process_sample (float &out_0, float &out_1, float input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 2
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataNeonV4, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Upsampler2xNeonOld< NC > &other) const =delete
bool operator== (const Upsampler2xNeonOld< NC > &other) const =delete
hiir_FORCEINLINE long process_block_quad (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void set_single_coef (int index, double coef) noexcept
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _coef_shift = ((NBR_COEFS & 1) * 2) ^ 3
static constexpr int _nbr_stages
static constexpr int _stage_width = 4
Detailed Description
template<int NC>
class hiir::Upsampler2xNeonOld< NC >
Definition at line 52 of file Upsampler2xNeonOld.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Upsampler2xNeonOld< NC >::DataType
Definition at line 61 of file Upsampler2xNeonOld.h.
Filter
template<int NC> typedef std::array<StageDataNeonV4, _nbr_stages + 1> hiir::Upsampler2xNeonOld< NC >::Filter private
Definition at line 99 of file Upsampler2xNeonOld.h.
Constructor & Destructor Documentation
Upsampler2xNeonOld() [1/3]
template<int NC> hiir::Upsampler2xNeonOld< NC >::Upsampler2xNeonOld () noexcept
Definition at line 57 of file Upsampler2xNeonOld.hpp.
References _filter, _nbr_stages, _stage_width, clear_buffers(), i, NBR_COEFS, set_single_coef(), and hiir::storea().
Referenced by Upsampler2xNeonOld(), Upsampler2xNeonOld(), ~Upsampler2xNeonOld(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2xNeonOld() [2/3]
template<int NC> hiir::Upsampler2xNeonOld< NC >::Upsampler2xNeonOld (const Upsampler2xNeonOld< NC > & other) default
References Upsampler2xNeonOld().
Upsampler2xNeonOld() [3/3]
template<int NC> hiir::Upsampler2xNeonOld< NC >::Upsampler2xNeonOld (Upsampler2xNeonOld< NC > && other) default
References Upsampler2xNeonOld().
~Upsampler2xNeonOld()
template<int NC> hiir::Upsampler2xNeonOld< NC >::~Upsampler2xNeonOld () default
References Upsampler2xNeonOld().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2xNeonOld< NC >::clear_buffers () noexcept
Definition at line 175 of file Upsampler2xNeonOld.hpp.
References _filter, _nbr_stages, i, and hiir::storea().
Referenced by Upsampler2xNeonOld(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2xNeonOld< NC >::operator!= (const Upsampler2xNeonOld< NC > & other) const private delete
References Upsampler2xNeonOld().
operator=() [1/2]
template<int NC> Upsampler2xNeonOld< NC > & hiir::Upsampler2xNeonOld< NC >::operator= (const Upsampler2xNeonOld< NC > & other) default
References Upsampler2xNeonOld().
operator=() [2/2]
template<int NC> Upsampler2xNeonOld< NC > & hiir::Upsampler2xNeonOld< NC >::operator= (Upsampler2xNeonOld< NC > && other) default
References Upsampler2xNeonOld(), clear_buffers(), inline, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2xNeonOld< NC >::operator== (const Upsampler2xNeonOld< NC > & other) const private delete
References Upsampler2xNeonOld().
process_block()
template<int NC> void hiir::Upsampler2xNeonOld< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 147 of file Upsampler2xNeonOld.hpp.
References pos, process_block_quad(), and process_sample().
Referenced by operator=().
process_block_quad()
template<int NC> long hiir::Upsampler2xNeonOld< NC >::process_block_quad (float out_ptr[], const float in_ptr[], long nbr_spl) private noexcept
Definition at line 216 of file Upsampler2xNeonOld.hpp.
References _filter, _nbr_stages, hiir::load4a(), hiir::load4u(), pos, hiir::StageProcNeonV4< CUR >::process_sample_pos(), hiir::storea(), and hiir::storeu().
Referenced by process_block().
process_sample()
template<int NC> void hiir::Upsampler2xNeonOld< NC >::process_sample (float & out_0, float & out_1, float input) inline noexcept
Definition at line 116 of file Upsampler2xNeonOld.hpp.
References _filter, _nbr_stages, hiir::load4a(), and hiir::StageProcNeonV4< CUR >::process_sample_pos().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::Upsampler2xNeonOld< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 89 of file Upsampler2xNeonOld.hpp.
References i, NBR_COEFS, and set_single_coef().
Referenced by operator=().
set_single_coef()
template<int NC> void hiir::Upsampler2xNeonOld< NC >::set_single_coef (int index, double coef) inline private noexcept
Definition at line 203 of file Upsampler2xNeonOld.hpp.
References _coef_shift, _filter, _nbr_stages, _stage_width, and pos.
Referenced by Upsampler2xNeonOld(), and set_coefs().
Member Data Documentation
_coef_shift
template<int NC> int hiir::Upsampler2xNeonOld< NC >::_coef_shift = ((NBR_COEFS & 1) * 2) ^ 3 static constexpr private
Definition at line 96 of file Upsampler2xNeonOld.h.
Referenced by set_single_coef().
_delay
template<int NC> double hiir::Upsampler2xNeonOld< NC >::_delay = 2 static constexpr
Definition at line 64 of file Upsampler2xNeonOld.h.
_filter
template<int NC> Filter hiir::Upsampler2xNeonOld< NC >::_filter private
Definition at line 107 of file Upsampler2xNeonOld.h.
Referenced by Upsampler2xNeonOld(), clear_buffers(), process_block_quad(), process_sample(), and set_single_coef().
_nbr_chn
template<int NC> int hiir::Upsampler2xNeonOld< NC >::_nbr_chn = 1 static constexpr
Definition at line 62 of file Upsampler2xNeonOld.h.
_nbr_stages
template<int NC> int hiir::Upsampler2xNeonOld< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 94 of file Upsampler2xNeonOld.h.
Referenced by Upsampler2xNeonOld(), clear_buffers(), process_block_quad(), process_sample(), and set_single_coef().
_stage_width
template<int NC> int hiir::Upsampler2xNeonOld< NC >::_stage_width = 4 static constexpr private
Definition at line 93 of file Upsampler2xNeonOld.h.
Referenced by Upsampler2xNeonOld(), and set_single_coef().
NBR_COEFS
template<int NC> int hiir::Upsampler2xNeonOld< NC >::NBR_COEFS = NC static constexpr
Definition at line 63 of file Upsampler2xNeonOld.h.
Referenced by Upsampler2xNeonOld(), operator=(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2xNeonOld.h
src/3rdparty/hiir/hiir/Upsampler2xNeonOld.hpp