LMMS: lmms::gui::MixerView Class Reference
lmms::gui::MixerView Class Reference
#include <MixerView.h>
Public Slots
int addNewChannel ()
Public Member Functions
MixerView (Mixer *mixer)
MixerChannelView * channelView (int index)
void clear ()
MixerChannelView * currentMixerChannel ()
void deleteChannel (int index)
void deleteUnusedChannels ()
void keyPressEvent (QKeyEvent *e) override
void loadSettings (const QDomElement &domElement) override
void moveChannelLeft (int index)
void moveChannelLeft (int index, int focusIndex)
void moveChannelRight (int index)
void refreshDisplay ()
void renameChannel (int index)
void saveSettings (QDomDocument &doc, QDomElement &domElement) override
void setCurrentMixerChannel (int channel)
void setCurrentMixerChannel (MixerChannelView *channel)
void updateMixerChannel (int index)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::SerializingObjectHook
SerializingObjectHook ()
virtual ~SerializingObjectHook ()
Protected Member Functions
void closeEvent (QCloseEvent *ce) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Private Slots
void toggledMute ()
void toggledSolo ()
void updateFaders ()
Private Member Functions
void connectToSoloAndMute (int channelIndex)
void disconnectFromSoloAndMute (int channelIndex)
Mixer * getMixer () const
void updateAllMixerChannels ()
void updateMaxChannelSelector ()
Private Attributes
QScrollArea * channelArea
QHBoxLayout * chLayout
QWidget * m_channelAreaWidget
MixerChannelView * m_currentMixerChannel
Mixer * m_mixer
QVector< MixerChannelView * > m_mixerChannelViews
QStackedLayout * m_racksLayout
QWidget * m_racksWidget
Friends
class MixerChannelView
Detailed Description
Definition at line 47 of file MixerView.h.
Constructor & Destructor Documentation
MixerView()
lmms::gui::MixerView::MixerView (Mixer * mixer)
Definition at line 58 of file MixerView.cpp.
References MixerView(), lmms::gui::ModelView::ModelView(), lmms::SerializingObjectHook::SerializingObjectHook(), addNewChannel(), channelArea, chLayout, connectToSoloAndMute(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), i, keyPressEvent(), m_channelAreaWidget, m_mixer, m_mixerChannelViews, m_racksLayout, m_racksWidget, lmms::gui::GuiApplication::mainWindow(), MixerChannelView, lmms::Mixer::numChannels(), lmms::gui::MainWindow::periodicUpdate(), setCurrentMixerChannel(), lmms::SerializingObject::setHook(), lmms::gui::ModelView::setModel(), and updateFaders().
Referenced by MixerView().
Member Function Documentation
addNewChannel
int lmms::gui::MixerView::addNewChannel () slot
Definition at line 190 of file MixerView.cpp.
References chLayout, connectToSoloAndMute(), lmms::Mixer::createChannel(), getMixer(), m_channelAreaWidget, m_mixerChannelViews, m_racksLayout, MixerChannelView, updateMaxChannelSelector(), and updateMixerChannel().
Referenced by MixerView(), lmms::gui::InstrumentTrackView::createMixerLine(), lmms::gui::SampleTrackView::createMixerLine(), and keyPressEvent().
channelView()
MixerChannelView * lmms::gui::MixerView::channelView (int index) inline
Definition at line 63 of file MixerView.h.
References m_mixerChannelViews, and MixerChannelView.
clear()
void lmms::gui::MixerView::clear ()
Definition at line 579 of file MixerView.cpp.
References lmms::Mixer::clearChannel(), deleteChannel(), getMixer(), i, m_mixerChannelViews, and refreshDisplay().
Referenced by lmms::Song::clearProject().
closeEvent()
void lmms::gui::MixerView::closeEvent (QCloseEvent * ce) override protected
Definition at line 554 of file MixerView.cpp.
connectToSoloAndMute()
void lmms::gui::MixerView::connectToSoloAndMute (int channelIndex) private
Definition at line 319 of file MixerView.cpp.
References lmms::Model::dataChanged(), getMixer(), lmms::Mixer::mixerChannel(), toggledMute(), and toggledSolo().
Referenced by MixerView(), addNewChannel(), and refreshDisplay().
currentMixerChannel()
MixerChannelView * lmms::gui::MixerView::currentMixerChannel () inline
Definition at line 58 of file MixerView.h.
References m_currentMixerChannel, and MixerChannelView.
Referenced by keyPressEvent().
deleteChannel()
void lmms::gui::MixerView::deleteChannel (int index)
Definition at line 389 of file MixerView.cpp.
References chLayout, lmms::Mixer::clearChannel(), lmms::Mixer::deleteChannel(), disconnectFromSoloAndMute(), getMixer(), i, m_channelAreaWidget, m_currentMixerChannel, m_mixerChannelViews, m_racksLayout, setCurrentMixerChannel(), and updateMaxChannelSelector().
Referenced by clear(), deleteUnusedChannels(), keyPressEvent(), and lmms::gui::MixerChannelView::removeChannel().
deleteUnusedChannels()
void lmms::gui::MixerView::deleteUnusedChannels ()
Definition at line 432 of file MixerView.cpp.
References deleteChannel(), getMixer(), i, lmms::Mixer::isChannelInUse(), and m_mixerChannelViews.
Referenced by lmms::gui::MixerChannelView::removeUnusedChannels().
disconnectFromSoloAndMute()
void lmms::gui::MixerView::disconnectFromSoloAndMute (int channelIndex) private
Definition at line 327 of file MixerView.cpp.
References lmms::Model::dataChanged(), getMixer(), lmms::Mixer::mixerChannel(), toggledMute(), and toggledSolo().
Referenced by deleteChannel(), and refreshDisplay().
getMixer()
Mixer * lmms::gui::MixerView::getMixer () const private
Definition at line 306 of file MixerView.cpp.
References m_mixer.
Referenced by addNewChannel(), clear(), connectToSoloAndMute(), deleteChannel(), deleteUnusedChannels(), disconnectFromSoloAndMute(), moveChannelLeft(), refreshDisplay(), toggledSolo(), updateFaders(), and updateMixerChannel().
keyPressEvent()
void lmms::gui::MixerView::keyPressEvent (QKeyEvent * e) override
Definition at line 488 of file MixerView.cpp.
References addNewChannel(), currentMixerChannel(), deleteChannel(), lmms::gui::Fader::Down, m_currentMixerChannel, moveChannelLeft(), moveChannelRight(), renameChannel(), setCurrentMixerChannel(), and lmms::gui::Fader::Up.
Referenced by MixerView().
loadSettings()
void lmms::gui::MixerView::loadSettings (const QDomElement & domElement) override virtual
Implements lmms::SerializingObjectHook.
Definition at line 284 of file MixerView.cpp.
References lmms::gui::MainWindow::restoreWidgetState().
moveChannelLeft() [1/2]
void lmms::gui::MixerView::moveChannelLeft (int index)
Definition at line 468 of file MixerView.cpp.
References moveChannelLeft().
Referenced by keyPressEvent(), lmms::gui::MixerChannelView::moveChannelLeft(), moveChannelLeft(), and moveChannelRight().
moveChannelLeft() [2/2]
void lmms::gui::MixerView::moveChannelLeft (int index, int focusIndex)
Definition at line 448 of file MixerView.cpp.
References getMixer(), m_mixerChannelViews, lmms::Mixer::moveChannelLeft(), and setCurrentMixerChannel().
moveChannelRight()
void lmms::gui::MixerView::moveChannelRight (int index)
Definition at line 475 of file MixerView.cpp.
References moveChannelLeft().
Referenced by keyPressEvent(), and lmms::gui::MixerChannelView::moveChannelRight().
refreshDisplay()
void lmms::gui::MixerView::refreshDisplay ()
Definition at line 209 of file MixerView.cpp.
References chLayout, connectToSoloAndMute(), disconnectFromSoloAndMute(), getMixer(), i, m_channelAreaWidget, m_mixerChannelViews, m_racksLayout, MixerChannelView, setCurrentMixerChannel(), updateMaxChannelSelector(), and updateMixerChannel().
Referenced by clear(), and lmms::Song::loadProject().
renameChannel()
void lmms::gui::MixerView::renameChannel (int index)
Definition at line 481 of file MixerView.cpp.
References m_mixerChannelViews.
Referenced by keyPressEvent().
saveSettings()
void lmms::gui::MixerView::saveSettings (QDomDocument & doc, QDomElement & domElement) override virtual
Implements lmms::SerializingObjectHook.
Definition at line 276 of file MixerView.cpp.
References lmms::gui::MainWindow::saveWidgetState().
setCurrentMixerChannel() [1/2]
void lmms::gui::MixerView::setCurrentMixerChannel (int channel)
Definition at line 569 of file MixerView.cpp.
References m_mixerChannelViews, and setCurrentMixerChannel().
setCurrentMixerChannel() [2/2]
void lmms::gui::MixerView::setCurrentMixerChannel (MixerChannelView * channel)
Definition at line 336 of file MixerView.cpp.
References lmms::gui::MixerChannelView::channelIndex(), i, m_currentMixerChannel, m_mixerChannelViews, m_racksLayout, MixerChannelView, and updateMixerChannel().
Referenced by MixerView(), lmms::gui::InstrumentTrackView::assignMixerLine(), lmms::gui::SampleTrackView::assignMixerLine(), deleteChannel(), keyPressEvent(), lmms::gui::MixerChannelLcdSpinBox::mouseDoubleClickEvent(), moveChannelLeft(), refreshDisplay(), and setCurrentMixerChannel().
toggledMute
void lmms::gui::MixerView::toggledMute () private slot
Definition at line 301 of file MixerView.cpp.
References updateAllMixerChannels().
Referenced by connectToSoloAndMute(), and disconnectFromSoloAndMute().
toggledSolo
void lmms::gui::MixerView::toggledSolo () private slot
Definition at line 293 of file MixerView.cpp.
References getMixer(), lmms::Mixer::toggledSolo(), and updateAllMixerChannels().
Referenced by connectToSoloAndMute(), and disconnectFromSoloAndMute().
updateAllMixerChannels()
void lmms::gui::MixerView::updateAllMixerChannels () private
Definition at line 311 of file MixerView.cpp.
References i, and m_mixerChannelViews.
Referenced by toggledMute(), and toggledSolo().
updateFaders
void lmms::gui::MixerView::updateFaders () private slot
Definition at line 592 of file MixerView.cpp.
References getMixer(), i, m_mixerChannelViews, lmms::MixerChannel::m_peakLeft, lmms::MixerChannel::m_peakRight, and lmms::Mixer::mixerChannel().
Referenced by MixerView().
updateMaxChannelSelector()
void lmms::gui::MixerView::updateMaxChannelSelector () private
Definition at line 250 of file MixerView.cpp.
References lmms::Engine::getSong(), lmms::Track::Instrument, m_mixerChannelViews, lmms::Engine::patternStore(), lmms::Track::Sample, and lmms::TrackContainer::tracks().
Referenced by addNewChannel(), deleteChannel(), and refreshDisplay().
updateMixerChannel()
void lmms::gui::MixerView::updateMixerChannel (int index)
Definition at line 350 of file MixerView.cpp.
References getMixer(), m_currentMixerChannel, and m_mixerChannelViews.
Referenced by addNewChannel(), refreshDisplay(), and setCurrentMixerChannel().
Friends And Related Symbol Documentation
MixerChannelView
friend class MixerChannelView friend
Definition at line 129 of file MixerView.h.
References MixerChannelView.
Referenced by MixerView(), addNewChannel(), channelView(), currentMixerChannel(), MixerChannelView, refreshDisplay(), and setCurrentMixerChannel().
Member Data Documentation
channelArea
QScrollArea* lmms::gui::MixerView::channelArea private
Definition at line 120 of file MixerView.h.
Referenced by MixerView().
chLayout
QHBoxLayout* lmms::gui::MixerView::chLayout private
Definition at line 121 of file MixerView.h.
Referenced by MixerView(), addNewChannel(), deleteChannel(), and refreshDisplay().
m_channelAreaWidget
QWidget* lmms::gui::MixerView::m_channelAreaWidget private
Definition at line 122 of file MixerView.h.
Referenced by MixerView(), addNewChannel(), deleteChannel(), and refreshDisplay().
m_currentMixerChannel
MixerChannelView* lmms::gui::MixerView::m_currentMixerChannel private
Definition at line 118 of file MixerView.h.
Referenced by currentMixerChannel(), deleteChannel(), keyPressEvent(), setCurrentMixerChannel(), and updateMixerChannel().
m_mixer
Mixer* lmms::gui::MixerView::m_mixer private
Definition at line 125 of file MixerView.h.
Referenced by MixerView(), and getMixer().
m_mixerChannelViews
QVector<MixerChannelView*> lmms::gui::MixerView::m_mixerChannelViews private
Definition at line 116 of file MixerView.h.
Referenced by MixerView(), addNewChannel(), channelView(), clear(), deleteChannel(), deleteUnusedChannels(), moveChannelLeft(), refreshDisplay(), renameChannel(), setCurrentMixerChannel(), setCurrentMixerChannel(), updateAllMixerChannels(), updateFaders(), updateMaxChannelSelector(), and updateMixerChannel().
m_racksLayout
QStackedLayout* lmms::gui::MixerView::m_racksLayout private
Definition at line 123 of file MixerView.h.
Referenced by MixerView(), addNewChannel(), deleteChannel(), refreshDisplay(), and setCurrentMixerChannel().
m_racksWidget
QWidget* lmms::gui::MixerView::m_racksWidget private
Definition at line 124 of file MixerView.h.
Referenced by lmms::gui::MixerChannelView::MixerChannelView(), and MixerView().
The documentation for this class was generated from the following files:
include/MixerView.h
src/gui/MixerView.cpp