LMMS: Jack::JackInternalClientHandleResult Struct Reference
Jack::JackInternalClientHandleResult Struct Reference
InternalClientHandle result.
#include <JackRequest.h>
Public Member Functions
JackInternalClientHandleResult ()
JackInternalClientHandleResult (int32_t result, int status, int int_ref)
int Read (detail::JackChannelTransactionInterface *trans)
int Size ()
int Write (detail::JackChannelTransactionInterface *trans)
Public Member Functions inherited from Jack::JackResult
JackResult ()
JackResult (int result)
virtual ~JackResult ()
Public Attributes
int fIntRefNum
int fStatus
Public Attributes inherited from Jack::JackResult
int fResult
Detailed Description
InternalClientHandle result.
Definition at line 1018 of file JackRequest.h.
Constructor & Destructor Documentation
JackInternalClientHandleResult() [1/2]
Jack::JackInternalClientHandleResult::JackInternalClientHandleResult () inline
Definition at line 1024 of file JackRequest.h.
References Jack::JackResult::JackResult(), fIntRefNum, and fStatus.
JackInternalClientHandleResult() [2/2]
Jack::JackInternalClientHandleResult::JackInternalClientHandleResult (int32_t result, int status, int int_ref) inline
Definition at line 1026 of file JackRequest.h.
References Jack::JackResult::JackResult(), fIntRefNum, and fStatus.
Member Function Documentation
Read()
int Jack::JackInternalClientHandleResult::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 1030 of file JackRequest.h.
References CheckRes, fIntRefNum, fStatus, Jack::detail::JackChannelTransactionInterface::Read(), and Jack::JackResult::Read().
Size()
int Jack::JackInternalClientHandleResult::Size () inline
Definition at line 1046 of file JackRequest.h.
Write()
int Jack::JackInternalClientHandleResult::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 1038 of file JackRequest.h.
References CheckRes, fIntRefNum, fStatus, Jack::detail::JackChannelTransactionInterface::Write(), and Jack::JackResult::Write().
Member Data Documentation
fIntRefNum
int Jack::JackInternalClientHandleResult::fIntRefNum
Definition at line 1022 of file JackRequest.h.
Referenced by JackInternalClientHandleResult(), JackInternalClientHandleResult(), Jack::JackRequestDecoder::HandleRequest(), Jack::JackGenericClientChannel::InternalClientHandle(), Read(), and Write().
fStatus
int Jack::JackInternalClientHandleResult::fStatus
Definition at line 1021 of file JackRequest.h.
Referenced by JackInternalClientHandleResult(), JackInternalClientHandleResult(), Jack::JackRequestDecoder::HandleRequest(), Jack::JackGenericClientChannel::InternalClientHandle(), Read(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h