LMMS: lmms::MidiClient Class Reference
lmms::MidiClient Class Reference abstract
#include <MidiClient.h>
Public Member Functions
MidiClient ()=default
virtual ~MidiClient ()
virtual void addPort (MidiPort *_port)
virtual void applyPortMode (MidiPort *_port)
virtual void applyPortName (MidiPort *_port)
virtual void connectRPChanged (QObject *, const char *)
virtual void connectWPChanged (QObject *, const char *)
virtual bool isRaw () const
virtual void processOutEvent (const MidiEvent &_me, const TimePos &_time, const MidiPort *_port)=0
virtual QStringList readablePorts () const
virtual void removePort (MidiPort *_port)
virtual QString sourcePortName (const MidiEvent &) const
virtual void subscribeReadablePort (MidiPort *_port, const QString &_dest, bool _subscribe=true)
virtual void subscribeWritablePort (MidiPort *_port, const QString &_dest, bool _subscribe=true)
virtual QStringList writablePorts () const
Static Public Member Functions
static MidiClient * openMidiClient ()
Protected Attributes
std::vector< MidiPort * > m_midiPorts
Detailed Description
Definition at line 45 of file MidiClient.h.
Constructor & Destructor Documentation
MidiClient()
lmms::MidiClient::MidiClient () default
Referenced by openMidiClient().
~MidiClient()
lmms::MidiClient::~MidiClient () virtual
Definition at line 35 of file MidiClient.cpp.
References m_midiPorts.
Member Function Documentation
addPort()
void lmms::MidiClient::addPort (MidiPort * _port) virtual
Definition at line 61 of file MidiClient.cpp.
References m_midiPorts.
applyPortMode()
void lmms::MidiClient::applyPortMode (MidiPort * _port) virtual
Definition at line 47 of file MidiClient.cpp.
applyPortName()
void lmms::MidiClient::applyPortName (MidiPort * _port) virtual
Definition at line 54 of file MidiClient.cpp.
connectRPChanged()
virtual void lmms::MidiClient::connectRPChanged (QObject * , const char *) inline virtual
Definition at line 101 of file MidiClient.h.
connectWPChanged()
virtual void lmms::MidiClient::connectWPChanged (QObject * , const char *) inline virtual
Definition at line 105 of file MidiClient.h.
isRaw()
virtual bool lmms::MidiClient::isRaw () const inline virtual
Reimplemented in lmms::MidiClientRaw.
Definition at line 69 of file MidiClient.h.
openMidiClient()
MidiClient * lmms::MidiClient::openMidiClient () static
References MidiClient().
processOutEvent()
virtual void lmms::MidiClient::processOutEvent (const MidiEvent & _me, const TimePos & _time, const MidiPort * _port) pure virtual
Implemented in lmms::MidiClientRaw.
readablePorts()
virtual QStringList lmms::MidiClient::readablePorts () const inline virtual
Definition at line 75 of file MidiClient.h.
removePort()
void lmms::MidiClient::removePort (MidiPort * _port) virtual
Definition at line 69 of file MidiClient.cpp.
References m_midiPorts.
sourcePortName()
virtual QString lmms::MidiClient::sourcePortName (const MidiEvent &) const inline virtual
Definition at line 85 of file MidiClient.h.
Referenced by lmms::AutoDetectMidiController::processInEvent().
subscribeReadablePort()
void lmms::MidiClient::subscribeReadablePort (MidiPort * _port, const QString & _dest, bool _subscribe = true) virtual
Definition at line 86 of file MidiClient.cpp.
subscribeWritablePort()
void lmms::MidiClient::subscribeWritablePort (MidiPort * _port, const QString & _dest, bool _subscribe = true) virtual
Definition at line 93 of file MidiClient.cpp.
writablePorts()
virtual QStringList lmms::MidiClient::writablePorts () const inline virtual
Definition at line 79 of file MidiClient.h.
Member Data Documentation
m_midiPorts
std::vector<MidiPort *> lmms::MidiClient::m_midiPorts protected
Definition at line 114 of file MidiClient.h.
Referenced by ~MidiClient(), addPort(), lmms::MidiClientRaw::processParsedEvent(), and removePort().
The documentation for this class was generated from the following files:
include/MidiClient.h
src/core/midi/MidiClient.cpp