LMMS: lmms::gui::InstrumentView Class Reference
lmms::gui::InstrumentView Class Reference
Instrument view with variable size.
#include <InstrumentView.h>
Public Member Functions
InstrumentView (Instrument *_instrument, QWidget *_parent)
~InstrumentView () override
InstrumentTrackWindow * instrumentTrackWindow ()
Instrument * model ()
const Instrument * model () const
void setModel (Model *_model, bool=false) override
Public Member Functions inherited from lmms::gui::PluginView
PluginView (Plugin *_plugin, QWidget *_parent)
virtual bool isResizable () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void unsetModel ()
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Detailed Description
Instrument view with variable size.
Definition at line 39 of file InstrumentView.h.
Constructor & Destructor Documentation
InstrumentView()
lmms::gui::InstrumentView::InstrumentView (Instrument * _instrument, QWidget * _parent)
Definition at line 34 of file InstrumentView.cpp.
References lmms::gui::PluginView::PluginView(), and setModel().
~InstrumentView()
lmms::gui::InstrumentView::~InstrumentView () override
Definition at line 45 of file InstrumentView.cpp.
References instrumentTrackWindow(), and lmms::gui::InstrumentTrackWindow::m_instrumentView.
Member Function Documentation
instrumentTrackWindow()
InstrumentTrackWindow * lmms::gui::InstrumentView::instrumentTrackWindow ()
Definition at line 69 of file InstrumentView.cpp.
Referenced by ~InstrumentView(), and setModel().
model() [1/2]
Instrument * lmms::gui::InstrumentView::model () inline
Definition at line 45 of file InstrumentView.h.
References lmms::gui::ModelView::castModel().
Referenced by setModel().
model() [2/2]
const Instrument * lmms::gui::InstrumentView::model () const inline
Definition at line 50 of file InstrumentView.h.
References lmms::gui::ModelView::castModel().
setModel()
void lmms::gui::InstrumentView::setModel (Model * _model, bool = false) override virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 56 of file InstrumentView.cpp.
References instrumentTrackWindow(), model(), and lmms::gui::ModelView::setModel().
Referenced by InstrumentView().
The documentation for this class was generated from the following files:
include/InstrumentView.h
src/gui/instrument/InstrumentView.cpp