LMMS: src/3rdparty/jack2/common/JackLibAPI.cpp File Reference
JackLibAPI.cpp File Reference
#include "JackDebugClient.h"
#include "JackLibClient.h"
#include "JackChannel.h"
#include "JackLibGlobals.h"
#include "JackGlobals.h"
#include "JackCompilerDeps.h"
#include "JackTools.h"
#include "JackSystemDeps.h"
#include "JackServerLaunch.h"
#include "JackMetadata.h"
#include <assert.h>
Functions
LIB_EXPORT int jack_client_close (jack_client_t *client)
Disconnects an external client from a JACK server.
jack_client_t * jack_client_new_aux (const char *client_name, jack_options_t options, jack_status_t *status)
LIB_EXPORT jack_client_t * jack_client_open (const char *client_name, jack_options_t options, jack_status_t *status,...)
Open an external client session with a JACK server.
static jack_client_t * jack_client_open_aux (const char *client_name, jack_options_t options, jack_status_t *status, va_list ap)
LIB_EXPORT int jack_get_client_pid (const char *name)
Function Documentation
jack_client_new_aux()
jack_client_t * jack_client_new_aux (const char * client_name, jack_options_t options, jack_status_t * status)
Definition at line 61 of file JackLibAPI.cpp.
jack_client_open_aux()
jack_client_t * jack_client_open_aux (const char * client_name, jack_options_t options, jack_status_t * status, va_list ap) static
Definition at line 114 of file JackLibAPI.cpp.
References client(), Jack::JackLibGlobals::Destroy(), Jack::GetSynchroTable(), Jack::JackLibGlobals::Init(), JACK_DEBUG, jack_error, jack_log(), jack_varargs_parse(), JackFailure, JackInvalidOption, JackOpenOptions, JackServerError, jack_varargs_t::server_name, jack_varargs_t::session_id, and try_start_server().
Referenced by jack_client_open().