LMMS: hiir::StageProcNeonV4< CUR > Class Template Reference
hiir::StageProcNeonV4< CUR > Class Template Reference
#include <StageProcNeonV4.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg_rec (StageDataNeonV4 *, float32x4_t &, float32x4_t &) noexcept
hiir_FORCEINLINE void process_sample_pos_rec (StageDataNeonV4 *, float32x4_t &, float32x4_t &) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (StageDataNeonV4 *stage_ptr, float32x4_t &y, float32x4_t &mem) noexcept
static hiir_FORCEINLINE void process_sample_neg_rec (StageDataNeonV4 *stage_ptr, float32x4_t &y, float32x4_t &mem) noexcept
static hiir_FORCEINLINE void process_sample_pos (StageDataNeonV4 *stage_ptr, float32x4_t &y, float32x4_t &mem) noexcept
static hiir_FORCEINLINE void process_sample_pos_rec (StageDataNeonV4 *stage_ptr, float32x4_t &y, float32x4_t &mem) noexcept
Private Member Functions
StageProcNeonV4 ()=delete
StageProcNeonV4 (const StageProcNeonV4< CUR > &other)=delete
StageProcNeonV4 (StageProcNeonV4< CUR > &&other)=delete
~StageProcNeonV4 ()=delete
bool operator!= (const StageProcNeonV4< CUR > &other) const =delete
StageProcNeonV4 & operator= (const StageProcNeonV4< CUR > &other)=delete
StageProcNeonV4 & operator= (StageProcNeonV4< CUR > &&other)=delete
bool operator== (const StageProcNeonV4< CUR > &other) const =delete
Detailed Description
template<int CUR>
class hiir::StageProcNeonV4< CUR >
Definition at line 45 of file StageProcNeonV4.h.
Constructor & Destructor Documentation
StageProcNeonV4() [1/3]
template<int CUR> hiir::StageProcNeonV4< CUR >::StageProcNeonV4 () private delete
Referenced by ~StageProcNeonV4(), operator=(), process_sample_neg_rec(), and process_sample_pos_rec().
StageProcNeonV4() [2/3]
template<int CUR> hiir::StageProcNeonV4< CUR >::StageProcNeonV4 (const StageProcNeonV4< CUR > & other) private delete
StageProcNeonV4() [3/3]
template<int CUR> hiir::StageProcNeonV4< CUR >::StageProcNeonV4 (StageProcNeonV4< CUR > && other) private delete
~StageProcNeonV4()
template<int CUR> hiir::StageProcNeonV4< CUR >::~StageProcNeonV4 () private delete
References StageProcNeonV4().
Member Function Documentation
operator!=()
template<int CUR> bool hiir::StageProcNeonV4< CUR >::operator!= (const StageProcNeonV4< CUR > & other) const private delete
operator=() [1/2]
template<int CUR> StageProcNeonV4 & hiir::StageProcNeonV4< CUR >::operator= (const StageProcNeonV4< CUR > & other) private delete
References StageProcNeonV4().
operator=() [2/2]
template<int CUR> StageProcNeonV4 & hiir::StageProcNeonV4< CUR >::operator= (StageProcNeonV4< CUR > && other) private delete
operator==()
template<int CUR> bool hiir::StageProcNeonV4< CUR >::operator== (const StageProcNeonV4< CUR > & other) const private delete
process_sample_neg()
template<int CUR> void hiir::StageProcNeonV4< CUR >::process_sample_neg (StageDataNeonV4 * stage_ptr, float32x4_t & y, float32x4_t & mem) static noexcept
Definition at line 49 of file StageProcNeonV4.hpp.
References process_sample_neg_rec(), and hiir::storea().
Referenced by hiir::PhaseHalfPiNeon< NC >::process_block_quad(), and hiir::PhaseHalfPiNeon< NC >::process_sample().
process_sample_neg_rec() [1/2]
hiir_FORCEINLINE void hiir::StageProcNeonV4< 0 >::process_sample_neg_rec (StageDataNeonV4 * , float32x4_t & , float32x4_t &) noexcept
Definition at line 92 of file StageProcNeonV4.hpp.
References hiir_FORCEINLINE.
process_sample_neg_rec() [2/2]
template<int CUR> void hiir::StageProcNeonV4< CUR >::process_sample_neg_rec (StageDataNeonV4 * stage_ptr, float32x4_t & y, float32x4_t & mem) static noexcept
Definition at line 78 of file StageProcNeonV4.hpp.
References StageProcNeonV4(), hiir::load4a(), process_sample_neg_rec(), and hiir::storea().
Referenced by process_sample_neg(), and process_sample_neg_rec().
process_sample_pos()
template<int CUR> void hiir::StageProcNeonV4< CUR >::process_sample_pos (StageDataNeonV4 * stage_ptr, float32x4_t & y, float32x4_t & mem) static noexcept
Definition at line 40 of file StageProcNeonV4.hpp.
References process_sample_pos_rec(), and hiir::storea().
Referenced by hiir::HalfBandNeon< NC >::process_2_paths(), hiir::Downsampler2xNeonOld< NC >::process_block_quad(), hiir::HalfBandNeon< NC >::process_block_quad(), hiir::Upsampler2xNeonOld< NC >::process_block_quad(), hiir::Downsampler2xNeonOld< NC >::process_sample(), hiir::Upsampler2xNeonOld< NC >::process_sample(), and hiir::Downsampler2xNeonOld< NC >::process_sample_split().
process_sample_pos_rec() [1/2]
hiir_FORCEINLINE void hiir::StageProcNeonV4< 0 >::process_sample_pos_rec (StageDataNeonV4 * , float32x4_t & , float32x4_t &) noexcept
Definition at line 70 of file StageProcNeonV4.hpp.
References hiir_FORCEINLINE.
process_sample_pos_rec() [2/2]
template<int CUR> void hiir::StageProcNeonV4< CUR >::process_sample_pos_rec (StageDataNeonV4 * stage_ptr, float32x4_t & y, float32x4_t & mem) static noexcept
Definition at line 58 of file StageProcNeonV4.hpp.
References StageProcNeonV4(), hiir::load4a(), process_sample_pos_rec(), and hiir::storea().
Referenced by process_sample_pos(), and process_sample_pos_rec().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProcNeonV4.h
src/3rdparty/hiir/hiir/StageProcNeonV4.hpp