LMMS: lmms::LinkedModelGroups Class Reference
lmms::LinkedModelGroups Class Reference abstract
Container for a group of linked models.
#include <LinkedModelGroups.h>
Public Member Functions
virtual ~LinkedModelGroups ()=default
virtual const LinkedModelGroup * getGroup (std::size_t idx) const =0
virtual LinkedModelGroup * getGroup (std::size_t idx)=0
Derived classes must return the group with index idx, or nullptr if is out of range.
void linkAllModels ()
void loadSettings (const class QDomElement &that)
void saveSettings (class QDomDocument &doc, class QDomElement &that)
Detailed Description
Container for a group of linked models.
Each group contains the same models and model types. The models are numbered, and equal numbered models are associated and always linked.
A typical application are two mono plugins making a stereo plugin.
Note
Though this class can contain multiple model groups, a corresponding view ("LinkedModelGroupViews") will only display one group, as they all have the same values
Though called "container", this class does not contain, but only know the single groups. The inheriting classes are responsible for storage.
Definition at line 155 of file LinkedModelGroups.h.
Constructor & Destructor Documentation
~LinkedModelGroups()
virtual lmms::LinkedModelGroups::~LinkedModelGroups () virtual default
Member Function Documentation
getGroup() [1/2]
virtual const LinkedModelGroup * lmms::LinkedModelGroups::getGroup (std::size_t idx) const pure virtual
See also
getGroup
getGroup() [2/2]
virtual LinkedModelGroup * lmms::LinkedModelGroups::getGroup (std::size_t idx) pure virtual
Derived classes must return the group with index idx, or nullptr if is out of range.
Referenced by linkAllModels(), loadSettings(), lmms::gui::LinkedModelGroupsView::modelChanged(), and saveSettings().
linkAllModels()
void lmms::LinkedModelGroups::linkAllModels ()
Definition at line 143 of file LinkedModelGroups.cpp.
References getGroup(), i, and lmms::LinkedModelGroup::linkControls().
loadSettings()
void lmms::LinkedModelGroups::loadSettings (const class QDomElement & that)
Definition at line 170 of file LinkedModelGroups.cpp.
References getGroup().
saveSettings()
void lmms::LinkedModelGroups::saveSettings (class QDomDocument & doc, class QDomElement & that)
Definition at line 155 of file LinkedModelGroups.cpp.
References getGroup(), and lmms::LinkedModelGroup::saveValues().
The documentation for this class was generated from the following files:
include/LinkedModelGroups.h
src/core/LinkedModelGroups.cpp