LMMS: lmms::AudioDummy::setupWidget Class Reference
lmms::AudioDummy::setupWidget Class Reference
#include <AudioDummy.h>
Public Member Functions
setupWidget (QWidget *_parent)
~setupWidget () override=default
void saveSettings () override
void show () override
Public Member Functions inherited from lmms::gui::AudioDeviceSetupWidget
AudioDeviceSetupWidget (const QString &_caption, QWidget *_parent)
~AudioDeviceSetupWidget () override=default
Detailed Description
Definition at line 57 of file AudioDummy.h.
Constructor & Destructor Documentation
setupWidget()
lmms::AudioDummy::setupWidget::setupWidget (QWidget * _parent) inline
Definition at line 60 of file AudioDummy.h.
References lmms::gui::AudioDeviceSetupWidget::AudioDeviceSetupWidget(), lmms::AudioDummy::AudioDummy(), and lmms::AudioDummy::name().
~setupWidget()
lmms::AudioDummy::setupWidget::~setupWidget () override default
Member Function Documentation
saveSettings()
void lmms::AudioDummy::setupWidget::saveSettings () inline override virtual
Implements lmms::gui::AudioDeviceSetupWidget.
Definition at line 67 of file AudioDummy.h.
show()
void lmms::AudioDummy::setupWidget::show () inline override virtual
Reimplemented from lmms::gui::AudioDeviceSetupWidget.
Definition at line 71 of file AudioDummy.h.
The documentation for this class was generated from the following file:
include/AudioDummy.h