LMMS: lmms::shmFifo Class Reference
lmms::shmFifo Class Reference
#include <RemotePluginBase.h>
Classes
union sem32_t
struct shmData
Public Member Functions
shmFifo ()
shmFifo (const std::string &shmKey)
void invalidate ()
bool isInvalid () const
bool isMaster () const
void lock ()
void messageSent ()
bool messagesLeft ()
int32_t readInt ()
std::string readString ()
const std::string & shmKey () const
void unlock ()
void waitForMessage ()
void writeInt (const int32_t &_i)
void writeString (const std::string &_s)
Private Member Functions
void read (void *_buf, int _len)
void write (const void *_buf, int _len)
Private Attributes
SharedMemory< shmData > m_data
SystemSemaphore m_dataSem
volatile bool m_invalid
std::atomic_int m_lockDepth
bool m_master
SystemSemaphore m_messageSem
Detailed Description
Definition at line 96 of file RemotePluginBase.h.
Constructor & Destructor Documentation
shmFifo() [1/2]
lmms::shmFifo::shmFifo () inline
Definition at line 118 of file RemotePluginBase.h.
References k, m_data, m_dataSem, m_invalid, m_lockDepth, m_master, and m_messageSem.
shmFifo() [2/2]
lmms::shmFifo::shmFifo (const std::string & shmKey) inline
Definition at line 135 of file RemotePluginBase.h.
References m_data, m_dataSem, m_invalid, m_lockDepth, m_master, m_messageSem, and shmKey().
Member Function Documentation
invalidate()
void lmms::shmFifo::invalidate () inline
Definition at line 150 of file RemotePluginBase.h.
References m_invalid.
isInvalid()
bool lmms::shmFifo::isInvalid () const inline
Definition at line 145 of file RemotePluginBase.h.
References m_invalid.
Referenced by lock(), messagesLeft(), read(), waitForMessage(), and write().
isMaster()
bool lmms::shmFifo::isMaster () const inline
Definition at line 156 of file RemotePluginBase.h.
References m_master.
lock()
void lmms::shmFifo::lock () inline
Definition at line 162 of file RemotePluginBase.h.
References isInvalid(), m_dataSem, and m_lockDepth.
Referenced by messagesLeft(), read(), and write().
messageSent()
void lmms::shmFifo::messageSent () inline
Definition at line 189 of file RemotePluginBase.h.
References m_messageSem.
messagesLeft()
bool lmms::shmFifo::messagesLeft () inline
Definition at line 231 of file RemotePluginBase.h.
References isInvalid(), lock(), m_data, and unlock().
read()
void lmms::shmFifo::read (void * _buf, int _len) inline private
Definition at line 251 of file RemotePluginBase.h.
References isInvalid(), lock(), m_data, and unlock().
Referenced by readInt(), and readString().
readInt()
int32_t lmms::shmFifo::readInt () inline
Definition at line 195 of file RemotePluginBase.h.
References i, and read().
Referenced by readString().
readString()
std::string lmms::shmFifo::readString () inline
Definition at line 207 of file RemotePluginBase.h.
References read(), and readInt().
shmKey()
const std::string & lmms::shmFifo::shmKey () const inline
Definition at line 244 of file RemotePluginBase.h.
References m_data.
Referenced by shmFifo().
unlock()
void lmms::shmFifo::unlock () inline
Definition at line 171 of file RemotePluginBase.h.
References m_dataSem, and m_lockDepth.
Referenced by messagesLeft(), read(), and write().
waitForMessage()
void lmms::shmFifo::waitForMessage () inline
Definition at line 180 of file RemotePluginBase.h.
References isInvalid(), and m_messageSem.
write()
void lmms::shmFifo::write (const void * _buf, int _len) inline private
Definition at line 279 of file RemotePluginBase.h.
References isInvalid(), lock(), m_data, lmms::SHM_FIFO_SIZE, and unlock().
Referenced by writeInt(), and writeString().
writeInt()
void lmms::shmFifo::writeInt (const int32_t & _i) inline
Definition at line 202 of file RemotePluginBase.h.
References write().
Referenced by writeString().
writeString()
void lmms::shmFifo::writeString (const std::string & _s) inline
Definition at line 223 of file RemotePluginBase.h.
References write(), and writeInt().
Member Data Documentation
m_data
SharedMemory<shmData> lmms::shmFifo::m_data private
Definition at line 311 of file RemotePluginBase.h.
Referenced by shmFifo(), shmFifo(), messagesLeft(), read(), shmKey(), and write().
m_dataSem
SystemSemaphore lmms::shmFifo::m_dataSem private
Definition at line 312 of file RemotePluginBase.h.
Referenced by shmFifo(), shmFifo(), lock(), and unlock().
m_invalid
volatile bool lmms::shmFifo::m_invalid private
Definition at line 309 of file RemotePluginBase.h.
Referenced by shmFifo(), shmFifo(), invalidate(), and isInvalid().
m_lockDepth
std::atomic_int lmms::shmFifo::m_lockDepth private
Definition at line 314 of file RemotePluginBase.h.
Referenced by shmFifo(), shmFifo(), lock(), and unlock().
m_master
bool lmms::shmFifo::m_master private
Definition at line 310 of file RemotePluginBase.h.
Referenced by shmFifo(), shmFifo(), and isMaster().
m_messageSem
SystemSemaphore lmms::shmFifo::m_messageSem private
Definition at line 313 of file RemotePluginBase.h.
Referenced by shmFifo(), shmFifo(), messageSent(), and waitForMessage().
The documentation for this class was generated from the following file:
include/RemotePluginBase.h