LMMS: src/3rdparty/jack2/common/JackDriverLoader.cpp File Reference
JackDriverLoader.cpp File Reference
#include "JackSystemDeps.h"
#include "JackDriverLoader.h"
#include "JackDriverInfo.h"
#include "JackConstants.h"
#include "JackError.h"
#include <getopt.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <dirent.h>
Macros
#define JACK_CONSTRAINT_COMPOSE_ENUM_IMPL(type, copy)
Typedefs
typedef char file_char_t
Functions
static void * check_symbol (const file_char_t *sofile, const char *symbol, const file_char_t *driver_dir, void **res_dllhandle=NULL)
SERVER_EXPORT int jack_constraint_add_enum (jack_driver_param_constraint_desc_t **constraint_ptr_ptr, uint32_t *array_size_ptr, jack_driver_param_value_t *value_ptr, const char *short_desc)
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (char, value.c=descr_ptr->value)
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (sint32, value.c=descr_ptr->value)
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (str, strcpy(value.str, descr_ptr->value))
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (uint32, value.c=descr_ptr->value)
SERVER_EXPORT void jack_constraint_free (jack_driver_param_constraint_desc_t *constraint_ptr)
SERVER_EXPORT int jack_driver_descriptor_add_parameter (jack_driver_desc_t *desc_ptr, jack_driver_desc_filler_t *filler_ptr, const char *name, char character, jack_driver_param_type_t type, const jack_driver_param_value_t *value_ptr, jack_driver_param_constraint_desc_t *constraint, const char *short_desc, const char *long_desc)
SERVER_EXPORT jack_driver_desc_t * jack_driver_descriptor_construct (const char *name, jack_driver_type_t type, const char *description, jack_driver_desc_filler_t *filler_ptr)
JSList * jack_drivers_load (JSList *drivers)
jack_driver_desc_t * jack_find_driver_descriptor (JSList *drivers, const char *name)
void jack_free_driver_params (JSList *driver_params)
static jack_driver_desc_t * jack_get_descriptor (JSList *drivers, const file_char_t *sofile, const char *symbol, const file_char_t *driver_dir)
JSList * jack_internals_load (JSList *internals)
int jack_parse_driver_params (jack_driver_desc_t *desc, int argc, char *argv[], JSList **param_ptr)
void jack_print_driver_options (jack_driver_desc_t *desc, FILE *file)
static void jack_print_driver_param_usage (jack_driver_desc_t *desc, unsigned long param, FILE *file)
jack_driver_desc_t * jackctl_driver_get_desc (jackctl_driver_t *driver)
SERVER_EXPORT int jackctl_driver_params_parse (jackctl_driver *driver_ptr, int argc, char *argv[])
Call this function to parse parameters for a driver.
Macro Definition Documentation
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL
#define JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (type, copy)
Value:
JACK_CONSTRAINT_COMPOSE_ENUM(type)                                      \
{                                                                       \
    jack_driver_param_constraint_desc_t * constraint_ptr;               \
    uint32_t array_size;                                                \
    jack_driver_param_value_t value;                                    \
    struct jack_constraint_enum_ ## type ## _descriptor * descr_ptr;    \
                                                                        \
    constraint_ptr = NULL;                                              \
    for (descr_ptr = descr_array_ptr;                                   \
         descr_ptr->value;                                              \
         descr_ptr++)                                                   \
    {                                                                   \
        copy;                                                           \
        if (!jack_constraint_add_enum(                                  \
                &constraint_ptr,                                        \
                &array_size,                                            \
                &value,                                                 \
                descr_ptr->short_desc))                                 \
        {                                                               \
            jack_constraint_free(constraint_ptr);                       \
            return NULL;                                                \
        }                                                               \
    }                                                                   \
                                                                        \
    constraint_ptr->flags = flags;                                      \
                                                                        \
    return constraint_ptr;                                              \
}
Definition at line 997 of file JackDriverLoader.cpp.
Typedef Documentation
file_char_t
typedef char file_char_t
Definition at line 38 of file JackDriverLoader.cpp.
Function Documentation
check_symbol()
void * check_symbol (const file_char_t * sofile, const char * symbol, const file_char_t * driver_dir, void ** res_dllhandle = NULL) static
Definition at line 421 of file JackDriverLoader.cpp.
References GetDriverProc, jack_error, LoadDriverModule, and UnloadDriverModule.
Referenced by jack_drivers_load(), jack_get_descriptor(), and jack_internals_load().
jack_constraint_add_enum()
SERVER_EXPORT int jack_constraint_add_enum (jack_driver_param_constraint_desc_t ** constraint_ptr_ptr, uint32_t * array_size_ptr, jack_driver_param_value_t * value_ptr, const char * short_desc)
Definition at line 915 of file JackDriverLoader.cpp.
References jack_driver_param_constraint_desc_t::constraint, jack_driver_param_constraint_desc_t::count, jack_driver_param_constraint_desc_t::enumeration, jack_error, jack_driver_param_constraint_desc_t::possible_values_array, jack_driver_param_value_enum_t::short_desc, and jack_driver_param_value_enum_t::value.
Referenced by enum_alsa_devices().
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL() [1/4]
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (char , value. c = descr_ptr->value)
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL() [2/4]
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (sint32 , value. c = descr_ptr->value)
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL() [3/4]
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (str , strcpy(value.str, descr_ptr->value))
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL() [4/4]
JACK_CONSTRAINT_COMPOSE_ENUM_IMPL (uint32 , value. c = descr_ptr->value)
jack_constraint_free()
SERVER_EXPORT void jack_constraint_free (jack_driver_param_constraint_desc_t * constraint_ptr)
Definition at line 983 of file JackDriverLoader.cpp.
References jack_driver_param_constraint_desc_t::constraint, jack_driver_param_constraint_desc_t::enumeration, jack_driver_param_constraint_desc_t::flags, JACK_CONSTRAINT_FLAG_RANGE, and jack_driver_param_constraint_desc_t::possible_values_array.
Referenced by enum_alsa_devices(), jackctl_free_driver_parameters(), and jackctl_server_free_parameters().
jack_driver_descriptor_add_parameter()
SERVER_EXPORT int jack_driver_descriptor_add_parameter (jack_driver_desc_t * desc_ptr, jack_driver_desc_filler_t * filler_ptr, const char * name, char character, jack_driver_param_type_t type, const jack_driver_param_value_t * value_ptr, jack_driver_param_constraint_desc_t * constraint, const char * short_desc, const char * long_desc)
Definition at line 853 of file JackDriverLoader.cpp.
References jack_driver_param_desc_t::character, jack_driver_param_desc_t::constraint, jack_error, jack_driver_param_desc_t::long_desc, jack_driver_param_desc_t::name, jack_driver_desc_t::nparams, jack_driver_desc_t::params, SERVER_EXPORT, jack_driver_param_desc_t::short_desc, jack_driver_desc_filler_t::size, jack_driver_param_desc_t::type, and jack_driver_param_desc_t::value.
Referenced by driver_get_descriptor(), Jack::driver_get_descriptor(), and jack_get_descriptor().
jack_driver_descriptor_construct()
SERVER_EXPORT jack_driver_desc_t * jack_driver_descriptor_construct (const char * name, jack_driver_type_t type, const char * description, jack_driver_desc_filler_t * filler_ptr)
Definition at line 815 of file JackDriverLoader.cpp.
References jack_driver_desc_t::desc, jack_error, jack_driver_desc_t::name, jack_driver_desc_t::nparams, SERVER_EXPORT, jack_driver_desc_filler_t::size, and jack_driver_desc_t::type.
Referenced by driver_get_descriptor(), Jack::driver_get_descriptor(), and jack_get_descriptor().
jack_drivers_load()
JSList * jack_drivers_load (JSList * drivers)
Definition at line 562 of file JackDriverLoader.cpp.
References ADDON_DIR, check_symbol(), jack_error, jack_get_descriptor(), and jack_slist_append().
Referenced by Jack::JackServerGlobals::Init(), and jackctl_drivers_load().
jack_find_driver_descriptor()
jack_driver_desc_t * jack_find_driver_descriptor (JSList * drivers, const char * name)
Definition at line 403 of file JackDriverLoader.cpp.
References _JSList::data, jack_slist_next, and jack_driver_desc_t::name.
Referenced by Jack::JackServerGlobals::Init().
jack_free_driver_params()
void jack_free_driver_params (JSList * driver_params)
Definition at line 130 of file JackDriverLoader.cpp.
References _JSList::data, and _JSList::next.
Referenced by Jack::JackServerGlobals::Init().
jack_get_descriptor()
jack_driver_desc_t * jack_get_descriptor (JSList * drivers, const file_char_t * sofile, const char * symbol, const file_char_t * driver_dir) static
Definition at line 450 of file JackDriverLoader.cpp.
References check_symbol(), _JSList::data, jack_driver_desc_t::file, jack_error, JACK_PATH_MAX, jack_slist_next, jack_driver_desc_t::name, and UnloadDriverModule.
jack_internals_load()
JSList * jack_internals_load (JSList * internals)
Definition at line 687 of file JackDriverLoader.cpp.
References ADDON_DIR, check_symbol(), jack_error, jack_get_descriptor(), and jack_slist_append().
Referenced by jackctl_internals_load().
jack_parse_driver_params()
int jack_parse_driver_params (jack_driver_desc_t * desc, int argc, char * argv[], JSList ** param_ptr)
Definition at line 143 of file JackDriverLoader.cpp.
References jack_driver_param_value_t::c, jack_driver_param_desc_t::character, jack_driver_param_t::character, option::flag, getopt_long(), option::has_arg, i, jack_driver_param_value_t::i, JACK_DRIVER_PARAM_STRING_MAX, jack_log(), jack_print_driver_options(), jack_print_driver_param_usage(), jack_slist_append(), JackDriverParamBool, JackDriverParamChar, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, jack_driver_desc_t::name, jack_driver_param_desc_t::name, option::name, jack_driver_desc_t::nparams, optarg, opterr, optind, optional_argument, optopt, jack_driver_desc_t::params, jack_driver_param_value_t::str, jack_driver_param_desc_t::type, jack_driver_param_value_t::ui, option::val, jack_driver_param_desc_t::value, and jack_driver_param_t::value.
Referenced by Jack::JackServerGlobals::Init().
jack_print_driver_options()
void jack_print_driver_options (jack_driver_desc_t * desc, FILE * file)
Definition at line 87 of file JackDriverLoader.cpp.
References jack_driver_param_value_t::c, jack_driver_param_desc_t::character, file, i, jack_driver_param_value_t::i, JACK_DRIVER_PARAM_STRING_MAX, JackDriverParamBool, JackDriverParamChar, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, jack_driver_param_desc_t::long_desc, jack_driver_param_desc_t::name, jack_driver_desc_t::nparams, jack_driver_desc_t::params, jack_driver_param_value_t::str, jack_driver_param_desc_t::type, jack_driver_param_value_t::ui, and jack_driver_param_desc_t::value.
Referenced by jack_parse_driver_params(), jackctl_driver_params_parse(), and Jack::JackArgParser::ParseParams().
jack_print_driver_param_usage()
void jack_print_driver_param_usage (jack_driver_desc_t * desc, unsigned long param, FILE * file) static
Definition at line 123 of file JackDriverLoader.cpp.
References file, jack_driver_param_desc_t::long_desc, jack_driver_desc_t::name, jack_driver_param_desc_t::name, and jack_driver_desc_t::params.
Referenced by jack_parse_driver_params(), and jackctl_driver_params_parse().
jackctl_driver_get_desc()
jack_driver_desc_t * jackctl_driver_get_desc (jackctl_driver_t * driver)
Definition at line 1142 of file JackControlAPI.cpp.
References jackctl_driver::desc_ptr, and SERVER_EXPORT.
Referenced by jackctl_driver_params_parse().