LMMS: Creating & manipulating ports
Creating & manipulating ports
Functions
int jack_connect (jack_client_t *client, const char *source_port, const char *destination_port) JACK_OPTIONAL_WEAK_EXPORT
Establish a connection between two ports.
int jack_disconnect (jack_client_t *client, const char *source_port, const char *destination_port) JACK_OPTIONAL_WEAK_EXPORT
Remove a connection between two ports.
int jack_port_connected (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_connected_to (const jack_port_t *port, const char *port_name) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_disconnect (jack_client_t *client, jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
Perform the same function as jack_disconnect() using port handles rather than names.
int jack_port_ensure_monitor (jack_port_t *port, int onoff) JACK_OPTIONAL_WEAK_EXPORT
If JackPortCanMonitor is set for a port, this function turns on input monitoring if it was off, and turns it off if only one request has been made to turn it on.
int jack_port_flags (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_get_aliases (const jack_port_t *port, char *const aliases[2]) JACK_OPTIONAL_WEAK_EXPORT
Get any aliases known for @port.
const char ** jack_port_get_all_connections (const jack_client_t *client, const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
void * jack_port_get_buffer (jack_port_t *port, jack_nframes_t) JACK_OPTIONAL_WEAK_EXPORT
This returns a pointer to the memory area associated with the specified port.
const char ** jack_port_get_connections (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_is_mine (const jack_client_t *client, const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_monitoring_input (jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
const char * jack_port_name (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_name_size (void) JACK_OPTIONAL_WEAK_EXPORT
jack_port_t * jack_port_register (jack_client_t *client, const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size) JACK_OPTIONAL_WEAK_EXPORT
Create a new port for the client.
int jack_port_rename (jack_client_t *client, jack_port_t *port, const char *port_name) JACK_OPTIONAL_WEAK_EXPORT
Modify a port's short name.
int jack_port_request_monitor (jack_port_t *port, int onoff) JACK_OPTIONAL_WEAK_EXPORT
If JackPortCanMonitor is set for this port, turn input monitoring on or off.
int jack_port_request_monitor_by_name (jack_client_t *client, const char *port_name, int onoff) JACK_OPTIONAL_WEAK_EXPORT
If JackPortCanMonitor is set for this port_name, turn input monitoring on or off.
int jack_port_set_alias (jack_port_t *port, const char *alias) JACK_OPTIONAL_WEAK_EXPORT
Set alias as an alias for port.
int jack_port_set_name (jack_port_t *port, const char *port_name) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS
const char * jack_port_short_name (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_tie (jack_port_t *src, jack_port_t *dst) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
const char * jack_port_type (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
size_t jack_port_type_get_buffer_size (jack_client_t *client, const char *port_type) JACK_WEAK_EXPORT
jack_port_type_id_t jack_port_type_id (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_type_size (void) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_unregister (jack_client_t *client, jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
Remove the port from the client, disconnecting any existing connections.
int jack_port_unset_alias (jack_port_t *port, const char *alias) JACK_OPTIONAL_WEAK_EXPORT
Remove alias as an alias for port.
int jack_port_untie (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
jack_uuid_t jack_port_uuid (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
Detailed Description
Function Documentation
jack_connect()
LIB_EXPORT int jack_connect (jack_client_t * client, const char * source_port, const char * destination_port)
#include <jack.h>
Establish a connection between two ports.
When a connection exists, data written to the source port will be available to be read at the destination port.
Precondition
The port types must be identical.
The JackPortFlags of the source_port must include JackPortIsOutput.
The JackPortFlags of the destination_port must include JackPortIsInput.
Returns
0 on success, EEXIST if the connection is already made, otherwise a non-zero error code
Definition at line 1215 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, and LIB_EXPORT.
Referenced by Jack::JackNetMaster::ConnectCallback(), Jack::JackAudioAdapter::ConnectPorts(), Jack::JackNetMaster::ConnectPorts(), Jack::JackProxyDriver::ConnectPorts(), Jack::JackNetMaster::LoadConnections(), Jack::JackProxyDriver::LoadSymbols(), main(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), and Jack::JackSapaProxy::Setup().
jack_disconnect()
LIB_EXPORT int jack_disconnect (jack_client_t * client, const char * source_port, const char * destination_port)
#include <jack.h>
Remove a connection between two ports.
Precondition
The port types must be identical.
The JackPortFlags of the source_port must include JackPortIsOutput.
The JackPortFlags of the destination_port must include JackPortIsInput.
Returns
0 on success, otherwise a non-zero error code
Definition at line 1231 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, and LIB_EXPORT.
Referenced by main().
jack_port_connected()
LIB_EXPORT int jack_port_connected (const jack_port_t * port)
#include <jack.h>
Returns
number of connections to or from port.
Precondition
The calling client must own port.
Definition at line 462 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::JackGraphManager::GetConnectionsNum(), Jack::GetGraphManager(), jack_error, LIB_EXPORT, and WaitGraphChange().
Referenced by main(), and Jack::JackNetMaster::Process().
jack_port_connected_to()
LIB_EXPORT int jack_port_connected_to (const jack_port_t * port, const char * port_name)
#include <jack.h>
Returns
TRUE if the locally-owned port is directly connected to the port_name.
See also
jack_port_name_size()
Definition at line 478 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), Jack::JackGraphManager::IsConnected(), jack_error, LIB_EXPORT, NO_PORT, and WaitGraphChange().
Referenced by main().
jack_port_disconnect()
LIB_EXPORT int jack_port_disconnect (jack_client_t * client, jack_port_t * port)
#include <jack.h>
Perform the same function as jack_disconnect() using port handles rather than names.
This avoids the name lookup inherent in the name-based version.
Clients connecting their own ports are likely to use this function, while generic connection clients (e.g. patchbays) would use jack_disconnect().
Definition at line 1247 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), client(), jack_error, and LIB_EXPORT.
Referenced by main().
jack_port_ensure_monitor()
LIB_EXPORT int jack_port_ensure_monitor (jack_port_t * port, int onoff)
#include <jack.h>
If JackPortCanMonitor is set for a port, this function turns on input monitoring if it was off, and turns it off if only one request has been made to turn it on.
Otherwise it does nothing.
Returns
0 on success, otherwise a non-zero error code
Definition at line 765 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::JackPort::EnsureMonitor(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, and LIB_EXPORT.
jack_port_flags()
LIB_EXPORT int jack_port_flags (const jack_port_t * port)
#include <jack.h>
Returns
the JackPortFlags of the jack_port_t.
Definition at line 417 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::JackPort::GetFlags(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, and LIB_EXPORT.
Referenced by main().
jack_port_get_aliases()
LIB_EXPORT int jack_port_get_aliases (const jack_port_t * port, char *const aliases[2])
#include <jack.h>
Get any aliases known for @port.
Returns
the number of aliases discovered for the port
Definition at line 713 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::JackPort::GetAliases(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, and LIB_EXPORT.
jack_port_get_all_connections()
LIB_EXPORT const char ** jack_port_get_all_connections (const jack_client_t * client, const jack_port_t * port)
#include <jack.h>
Returns
a null-terminated array of full port names to which the port is connected. If none, returns NULL.
The caller is responsible for calling jack_free() on any non-NULL returned value.
This differs from jack_port_get_connections() in two important respects:
1) You may not call this function from code that is
     executed in response to a JACK event. For example,
     you cannot use it in a GraphReordered handler.
2) You need not be the owner of the port to get information
     about its connections.
See also
jack_port_name_size()
Definition at line 1166 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), client(), Jack::JackGraphManager::GetConnections(), Jack::GetGraphManager(), jack_error, LIB_EXPORT, and WaitGraphChange().
Referenced by main(), and Jack::JackNetMaster::SaveConnections().
jack_port_get_buffer()
LIB_EXPORT void * jack_port_get_buffer (jack_port_t * port, jack_nframes_t frames)
#include <jack.h>
This returns a pointer to the memory area associated with the specified port.
For an output port, it will be a memory area that can be written to; for an input port, it will be an area containing the data from the port's connection(s), or zero-filled. if there are multiple inbound connections, the data will be mixed appropriately.
FOR OUTPUT PORTS ONLY : DEPRECATED in Jack 2.0 !!
You may cache the value returned, but only between calls to your "blocksize" callback. For this reason alone, you should either never cache the return value or ensure you have a "blocksize" callback and be sure to invalidate the cached address from there.
Caching output ports is DEPRECATED in Jack 2.0, due to some new optimization (like "pipelining"). Port buffers have to be retrieved in each callback for proper functioning.
Definition at line 358 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::JackGraphManager::GetBuffer(), Jack::GetGraphManager(), jack_error, and LIB_EXPORT.
Referenced by _process(), jack_callback(), Jack::JackProxyDriver::LoadSymbols(), main(), Jack::JackNetMaster::Process(), Jack::JackProfiler::Process(), Jack::JackSapaProxy::Process(), process1(), process2(), ExternalMetro::process_audio(), Jack::JackAudioAdapter::ProcessAux(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), Jack::JackProxyDriver::Read(), and Jack::JackProxyDriver::Write().
jack_port_get_connections()
LIB_EXPORT const char ** jack_port_get_connections (const jack_port_t * port)
#include <jack.h>
Returns
a null-terminated array of full port names to which the port is connected. If none, returns NULL.
The caller is responsible for calling jack_free() on any non-NULL returned value.
Parameters
port locally owned jack_port_t pointer.
See also
jack_port_name_size(), jack_port_get_all_connections()
Definition at line 1149 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::JackGraphManager::GetConnections(), Jack::GetGraphManager(), jack_error, LIB_EXPORT, and WaitGraphChange().
Referenced by main().
jack_port_is_mine()
LIB_EXPORT int jack_port_is_mine (const jack_client_t * client, const jack_port_t * port)
#include <jack.h>
Returns
TRUE if the jack_port_t belongs to the jack_client_t.
Definition at line 1131 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), client(), jack_error, and LIB_EXPORT.
Referenced by Jack::JackProxyDriver::connect_callback(), Jack::JackProxyDriver::LoadSymbols(), main(), and Jack::JackProxyDriver::PROXY_DEF_SYMBOL().
jack_port_monitoring_input()
LIB_EXPORT int jack_port_monitoring_input (jack_port_t * port)
#include <jack.h>
Returns
TRUE if input monitoring has been requested for port.
Definition at line 780 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, LIB_EXPORT, and Jack::JackPort::MonitoringInput().
jack_port_name()
LIB_EXPORT const char * jack_port_name (const jack_port_t * port)
#include <jack.h>
Returns
the full name of the jack_port_t (including the "client_name:" prefix).
See also
jack_port_name_size().
Definition at line 387 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackPort::GetName(), Jack::JackGraphManager::GetPort(), jack_error, and LIB_EXPORT.
Referenced by Jack::JackNetMaster::ConnectCallback(), Jack::JackAudioAdapter::ConnectPorts(), Jack::JackNetMaster::ConnectPorts(), Jack::JackProxyDriver::ConnectPorts(), Jack::JackProxyDriver::LoadSymbols(), main(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), Jack::JackNetMaster::SaveConnections(), and Jack::JackSapaProxy::Setup().
jack_port_name_size()
LIB_EXPORT int jack_port_name_size (void)
#include <jack.h>
Returns
the maximum number of characters in a full JACK port name including the final NULL character. This value is a constant.
A port's full name contains the owning client name concatenated with a colon (:) followed by its short name and a NULL character.
Definition at line 1491 of file JackAPI.cpp.
References LIB_EXPORT, and REAL_JACK_PORT_NAME_SIZE.
Referenced by main().
jack_port_register()
LIB_EXPORT jack_port_t * jack_port_register (jack_client_t * client, const char * port_name, const char * port_type, unsigned long flags, unsigned long buffer_size)
#include <jack.h>
Create a new port for the client.
This is an object used for moving data of any type in or out of the client. Ports may be connected in various ways.
Each port has a short name. The port's full name contains the name of the client concatenated with a colon (:) followed by its short name. The jack_port_name_size() is the maximum length of this full name. Exceeding that will cause the port registration to fail and return NULL.
The port_name must be unique among all ports owned by this client. If the name is not unique, the registration will fail.
All ports have a type, which may be any non-NULL and non-zero length string, passed as an argument. Some port types are built into the JACK API, currently only JACK_DEFAULT_AUDIO_TYPE.
Parameters
client pointer to JACK client structure.
port_name non-empty short name for the new port (not including the leading "client_name:"). Must be unique.
port_type port type name. If longer than jack_port_type_size(), only that many characters are significant.
flags JackPortFlags bit mask.
buffer_size must be non-zero if this is not a built-in port_type. Otherwise, it is ignored.
Returns
jack_port_t pointer on success, otherwise NULL.
Definition at line 1097 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, and LIB_EXPORT.
Referenced by ExternalMetro::ExternalMetro(), Jack::JackProfiler::JackProfiler(), Jack::JackProfilerClient::JackProfilerClient(), Jack::JackNetMaster::AllocPorts(), Jack::JackProxyDriver::AllocPorts(), Jack::JackProxyDriver::LoadSymbols(), main(), main(), Jack::JackAudioAdapter::Open(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), and Jack::JackSapaProxy::Setup().
jack_port_rename()
LIB_EXPORT int jack_port_rename (jack_client_t * client, jack_port_t * port, const char * port_name)
#include <jack.h>
Modify a port's short name.
May NOT be called from a callback handling a server event. If the resulting full name (including the "client_name:" prefix) is longer than jack_port_name_size(), it will be truncated.
Returns
0 on success, otherwise a non-zero error code.
This differs from jack_port_set_name() by triggering PortRename notifications to clients that have registered a port rename handler.
Definition at line 656 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), client(), jack_error, and LIB_EXPORT.
Referenced by jack_port_set_name().
jack_port_request_monitor()
LIB_EXPORT int jack_port_request_monitor (jack_port_t * port, int onoff)
#include <jack.h>
If JackPortCanMonitor is set for this port, turn input monitoring on or off.
Otherwise, do nothing.
Definition at line 728 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), jack_error, LIB_EXPORT, and Jack::JackGraphManager::RequestMonitor().
jack_port_request_monitor_by_name()
LIB_EXPORT int jack_port_request_monitor_by_name (jack_client_t * client, const char * port_name, int onoff)
#include <jack.h>
If JackPortCanMonitor is set for this port_name, turn input monitoring on or off.
Otherwise, do nothing.
Returns
0 on success, otherwise a non-zero error code.
See also
jack_port_name_size()
Definition at line 743 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), client(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, LIB_EXPORT, and Jack::JackGraphManager::RequestMonitor().
jack_port_set_alias()
LIB_EXPORT int jack_port_set_alias (jack_port_t * port, const char * alias)
#include <jack.h>
Set alias as an alias for port.
May be called at any time. If the alias is longer than jack_port_name_size(), it will be truncated.
After a successful call, and until JACK exits or @function jack_port_unset_alias() is called, @alias may be used as a alternate name for the port.
Ports can have up to two aliases - if both are already set, this function will return an error.
Returns
0 on success, otherwise a non-zero error code.
Definition at line 677 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, LIB_EXPORT, and Jack::JackPort::SetAlias().
jack_port_set_name()
LIB_EXPORT int jack_port_set_name (jack_port_t * port, const char * port_name)
#include <jack.h>
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS
Modify a port's short name. May be called at any time. If the resulting full name (including the "client_name:" prefix) is longer than jack_port_name_size(), it will be truncated.
Returns
0 on success, otherwise a non-zero error code.
Definition at line 640 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), CLIENT_NUM, Jack::JackGlobals::fClientTable, i, jack_error, jack_port_rename(), and LIB_EXPORT.
Referenced by main().
jack_port_short_name()
LIB_EXPORT const char * jack_port_short_name (const jack_port_t * port)
#include <jack.h>
Returns
the short name of the jack_port_t (not including the "client_name:" prefix).
See also
jack_port_name_size().
Definition at line 402 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), Jack::JackPort::GetShortName(), jack_error, and LIB_EXPORT.
Referenced by main().
jack_port_tie()
LIB_EXPORT int jack_port_tie (jack_port_t * src, jack_port_t * dst)
#include <jack.h>
Deprecated
This function will be removed from a future version of JACK. Do not use it. There is no replacement. It has turned out to serve essentially no purpose in real-life JACK clients.
Definition at line 503 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), Jack::JackPort::GetRefNum(), jack_error, LIB_EXPORT, and Jack::JackPort::Tie().
Referenced by main().
jack_port_type()
LIB_EXPORT const char * jack_port_type (const jack_port_t * port)
#include <jack.h>
Returns
the port type, at most jack_port_type_size() characters including a final NULL.
Definition at line 432 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), Jack::JackPort::GetType(), jack_error, and LIB_EXPORT.
Referenced by main().
jack_port_type_get_buffer_size()
LIB_EXPORT size_t jack_port_type_get_buffer_size (jack_client_t * client, const char * port_type)
#include <jack.h>
Returns
the buffersize of a port of type
port_type.
this function may only be called in a buffer_size callback.
Definition at line 1501 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::GetPortType(), Jack::GetPortTypeId(), jack_error, LIB_EXPORT, Jack::PORT_TYPES_MAX, and Jack::JackPortType::size.
jack_port_type_id()
LIB_EXPORT jack_port_type_id_t jack_port_type_id (const jack_port_t * port)
#include <jack.h>
Returns
the port type id.
Definition at line 447 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), Jack::GetPortTypeId(), Jack::JackPort::GetType(), jack_error, and LIB_EXPORT.
jack_port_type_size()
LIB_EXPORT int jack_port_type_size (void)
#include <jack.h>
Returns
the maximum number of characters in a JACK port type name including the final NULL character. This value is a constant.
Definition at line 1496 of file JackAPI.cpp.
References JACK_PORT_TYPE_SIZE, and LIB_EXPORT.
Referenced by Jack::JackNetOneDriver::render_jack_ports_to_payload_float(), and Jack::JackNetOneDriver::render_payload_to_jack_ports_float().
jack_port_unregister()
LIB_EXPORT int jack_port_unregister (jack_client_t * client, jack_port_t * port)
#include <jack.h>
Remove the port from the client, disconnecting any existing connections.
Returns
0 on success, otherwise a non-zero error code
Definition at line 1113 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), client(), jack_error, and LIB_EXPORT.
Referenced by ExternalMetro::~ExternalMetro(), Jack::JackProfilerClient::~JackProfilerClient(), Jack::JackAudioAdapter::FreePorts(), Jack::JackNetMaster::FreePorts(), Jack::JackProxyDriver::LoadSymbols(), main(), and Jack::JackProxyDriver::PROXY_DEF_SYMBOL().
jack_port_unset_alias()
LIB_EXPORT int jack_port_unset_alias (jack_port_t * port, const char * alias)
#include <jack.h>
Remove alias as an alias for port.
May be called at any time.
After a successful call, alias can no longer be used as a alternate name for the port.
Returns
0 on success, otherwise a non-zero error code.
Definition at line 695 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, LIB_EXPORT, and Jack::JackPort::UnsetAlias().
jack_port_untie()
LIB_EXPORT int jack_port_untie (jack_port_t * port)
#include <jack.h>
Deprecated
This function will be removed from a future version of JACK. Do not use it. There is no replacement. It has turned out to serve essentially no purpose in real-life JACK clients.
Definition at line 528 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, LIB_EXPORT, and Jack::JackPort::UnTie().
Referenced by main().
jack_port_uuid()
LIB_EXPORT jack_uuid_t jack_port_uuid (const jack_port_t * port)
#include <jack.h>
Returns
the UUID of the jack_port_t
See also
jack_uuid_to_string() to convert into a string representation
Definition at line 373 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), CheckPort(), jack_error, jack_port_uuid_generate(), and LIB_EXPORT.