LMMS: lmms::ConstModelVisitor Class Reference
lmms::ConstModelVisitor Class Reference
#include <ModelVisitor.h>
Public Member Functions
virtual ~ConstModelVisitor ()=default
virtual void visit (const AutomatableModel &)
virtual void visit (const BoolModel &m)
virtual void visit (const ComboBoxModel &m)
virtual void visit (const FloatModel &m)
virtual void visit (const IntModel &m)
virtual void visit (const TempoSyncKnobModel &m)
Private Member Functions
template<class ParentType = AutomatableModel, class ModelType>
void up (const ModelType &m)
Detailed Description
Definition at line 53 of file ModelVisitor.h.
Constructor & Destructor Documentation
~ConstModelVisitor()
virtual lmms::ConstModelVisitor::~ConstModelVisitor () virtual default
Member Function Documentation
up()
template<class ParentType = AutomatableModel, class ModelType> void lmms::ConstModelVisitor::up (const ModelType & m) inline private
Definition at line 56 of file ModelVisitor.h.
References visit().
Referenced by visit(), visit(), visit(), visit(), and visit().
visit() [1/6]
virtual void lmms::ConstModelVisitor::visit (const AutomatableModel &) inline virtual
Definition at line 59 of file ModelVisitor.h.
Referenced by up().
visit() [2/6]
void lmms::ConstModelVisitor::visit (const BoolModel & m) virtual
Definition at line 41 of file ModelVisitor.cpp.
References up().
visit() [3/6]
void lmms::ConstModelVisitor::visit (const ComboBoxModel & m) virtual
Definition at line 44 of file ModelVisitor.cpp.
References up().
visit() [4/6]
void lmms::ConstModelVisitor::visit (const FloatModel & m) virtual
Definition at line 43 of file ModelVisitor.cpp.
References up().
visit() [5/6]
void lmms::ConstModelVisitor::visit (const IntModel & m) virtual
Definition at line 42 of file ModelVisitor.cpp.
References up().
visit() [6/6]
void lmms::ConstModelVisitor::visit (const TempoSyncKnobModel & m) virtual
Definition at line 45 of file ModelVisitor.cpp.
References up().
The documentation for this class was generated from the following files:
include/ModelVisitor.h
src/core/ModelVisitor.cpp