LMMS: lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR > Class Template Reference
lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR > Class Template Reference
#include <DspEffectLibrary.h>
Public Member Functions
MonoToStereoAdaptor (const FXL &leftFX, const FXR &rightFX)
MonoToStereoAdaptor (const FXL &monoFX)
FXL & leftFX ()
void nextSample (sample_t &inLeft, sample_t &inRight)
void nextSample (SampleFrame &in)
FXR & rightFX ()
void setGain (float gain)
Private Attributes
FXL m_leftFX
FXR m_rightFX
Additional Inherited Members
Public Types inherited from lmms::DspEffectLibrary::StereoBase< MonoToStereoAdaptor< FXL, FXL > >
using bypassType
Static Public Member Functions inherited from lmms::DspEffectLibrary::StereoBase< MonoToStereoAdaptor< FXL, FXL > >
static void process (sample_t **_buf, const f_cnt_t _frames)
Detailed Description
template<class FXL, class FXR = FXL>
class lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >
Definition at line 69 of file DspEffectLibrary.h.
Constructor & Destructor Documentation
MonoToStereoAdaptor() [1/2]
template<class FXL, class FXR = FXL> lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::MonoToStereoAdaptor (const FXL & monoFX) inline
Definition at line 72 of file DspEffectLibrary.h.
References m_leftFX, and m_rightFX.
MonoToStereoAdaptor() [2/2]
template<class FXL, class FXR = FXL> lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::MonoToStereoAdaptor (const FXL & leftFX, const FXR & rightFX) inline
Definition at line 78 of file DspEffectLibrary.h.
References leftFX(), m_leftFX, m_rightFX, and rightFX().
Member Function Documentation
leftFX()
template<class FXL, class FXR = FXL> FXL & lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::leftFX () inline
Definition at line 101 of file DspEffectLibrary.h.
References m_leftFX.
Referenced by MonoToStereoAdaptor(), and setGain().
nextSample() [1/2]
template<class FXL, class FXR = FXL> void lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::nextSample (sample_t & inLeft, sample_t & inRight) inline
Definition at line 95 of file DspEffectLibrary.h.
References m_leftFX, and m_rightFX.
nextSample() [2/2]
template<class FXL, class FXR = FXL> void lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::nextSample (SampleFrame & in) inline
Definition at line 90 of file DspEffectLibrary.h.
References lmms::SampleFrame::left(), nextSample(), and lmms::SampleFrame::right().
Referenced by nextSample().
rightFX()
template<class FXL, class FXR = FXL> FXR & lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::rightFX () inline
Definition at line 106 of file DspEffectLibrary.h.
References m_rightFX.
Referenced by MonoToStereoAdaptor(), and setGain().
setGain()
template<class FXL, class FXR = FXL> void lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::setGain (float gain) inline
Definition at line 84 of file DspEffectLibrary.h.
References leftFX(), and rightFX().
Member Data Documentation
m_leftFX
template<class FXL, class FXR = FXL> FXL lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::m_leftFX private
Definition at line 112 of file DspEffectLibrary.h.
Referenced by MonoToStereoAdaptor(), MonoToStereoAdaptor(), leftFX(), and nextSample().
m_rightFX
template<class FXL, class FXR = FXL> FXR lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::m_rightFX private
Definition at line 113 of file DspEffectLibrary.h.
Referenced by MonoToStereoAdaptor(), MonoToStereoAdaptor(), nextSample(), and rightFX().
The documentation for this class was generated from the following file:
include/DspEffectLibrary.h