LMMS: lmms::anonymous_namespace{SampleDecoder.cpp} Namespace Reference
lmms::anonymous_namespace{SampleDecoder.cpp} Namespace Reference
Typedefs
using Decoder = std::optional<SampleDecoder::Result> (*)(const QString&)
Functions
auto decodeSampleDS (const QString &audioFile) -> std::optional< SampleDecoder::Result >
auto decodeSampleSF (const QString &audioFile) -> std::optional< SampleDecoder::Result >
Variables
static constexpr std::array< Decoder, 3 > decoders
Typedef Documentation
Decoder
using lmms::anonymous_namespace{SampleDecoder.cpp}::Decoder = std::optional<SampleDecoder::Result> (*)(const QString&)
Definition at line 45 of file SampleDecoder.cpp.
Function Documentation
decodeSampleDS()
auto lmms::anonymous_namespace{SampleDecoder.cpp}::decodeSampleDS (const QString & audioFile) ->std::optional< SampleDecoder::Result >
Definition at line 97 of file SampleDecoder.cpp.
References lmms::Engine::audioEngine(), decodeSampleDS(), lmms::DEFAULT_CHANNELS, and lmms::AudioEngine::outputSampleRate().
Referenced by decodeSampleDS().
decodeSampleSF()
auto lmms::anonymous_namespace{SampleDecoder.cpp}::decodeSampleSF (const QString & audioFile) ->std::optional< SampleDecoder::Result >
Definition at line 59 of file SampleDecoder.cpp.
References decodeSampleSF(), file, and i.
Referenced by decodeSampleSF().
Variable Documentation
decoders
std::array<Decoder, 3> lmms::anonymous_namespace{SampleDecoder.cpp}::decoders static constexpr
Initial value:
= {&decodeSampleSF,
    &decodeSampleDS}
Definition at line 53 of file SampleDecoder.cpp.