LMMS: lmms::UpgradeExtendedNoteRange Class Reference
lmms::UpgradeExtendedNoteRange Class Reference
#include <UpgradeExtendedNoteRange.h>
Public Member Functions
UpgradeExtendedNoteRange (QDomElement &domElement)
void upgrade ()
Private Attributes
QDomElement & m_domElement
Detailed Description
Definition at line 34 of file UpgradeExtendedNoteRange.h.
Constructor & Destructor Documentation
UpgradeExtendedNoteRange()
lmms::UpgradeExtendedNoteRange::UpgradeExtendedNoteRange (QDomElement & domElement)
Definition at line 377 of file UpgradeExtendedNoteRange.cpp.
References m_domElement.
Member Function Documentation
upgrade()
void lmms::UpgradeExtendedNoteRange::upgrade ()
Definition at line 382 of file UpgradeExtendedNoteRange.cpp.
References lmms::affected(), lmms::fixAutomationTracks(), lmms::fixTrack(), and m_domElement.
Referenced by lmms::DataFile::upgrade_extendedNoteRange().
Member Data Documentation
m_domElement
QDomElement& lmms::UpgradeExtendedNoteRange::m_domElement private
Definition at line 42 of file UpgradeExtendedNoteRange.h.
Referenced by UpgradeExtendedNoteRange(), and upgrade().
The documentation for this class was generated from the following files:
src/core/UpgradeExtendedNoteRange.h
src/core/UpgradeExtendedNoteRange.cpp