LMMS: ringbuffer_reader_t< T > Class Template Reference
ringbuffer_reader_t< T > Class Template Reference
#include <ringbuffer.h>
Classes
class peak_sequence_t
class read_sequence_t
class seq_base
sequences help reading by providing a ringbuffer-suited operator[]
Public Member Functions
ringbuffer_reader_t (ringbuffer_t< T > &arg_ref)
constuctor.
ringbuffer_reader_t (std::size_t sz)
constuctor.
void connect (ringbuffer_t< T > &_ref)
std::size_t get_size () const
return the size that the reader expects from the ringbuffer
peak_sequence_t peak (std::size_t range) const
peaks range objects if range <= read_space(), otherwise 0
peak_sequence_t peak_max (std::size_t range=std::numeric_limits< std::size_t >::max()) const
peaks min(range, read_space()) objects
read_sequence_t read (std::size_t range)
reads range objects if range <= read_space(), otherwise 0
read_sequence_t read_max (std::size_t range=std::numeric_limits< std::size_t >::max())
reads min(range, read_space()) objects
std::size_t read_space () const
returns number of objects that can be read at least
Private Member Functions
std::size_t _read_max_spc (std::size_t range) const
std::size_t _read_spc (std::size_t range) const
void try_inc (std::size_t range)
increases the read_ptr after reading from the buffer
Private Attributes
const T * buf
ringbuffer_t< T > * ref
Additional Inherited Members
Protected Member Functions inherited from ringbuffer_reader_base
ringbuffer_reader_base (std::size_t sz)
std::size_t read_space (std::size_t w) const
returns number of objects that can be read at least
std::size_t read_space_1 (std::size_t range) const
returns read space of first halve (the one starting at read ptr)
std::size_t read_space_2 (std::size_t range) const
returns read space of second halve
Protected Member Functions inherited from ringbuffer_common_t
ringbuffer_common_t (std::size_t sz)
Protected Attributes inherited from ringbuffer_reader_base
std::size_t read_ptr = 0
reader at buf[read_ptr]
Protected Attributes inherited from ringbuffer_common_t
const std::size_t size
< max number of objects in buffer (2^n for some n)
const std::size_t size_mask
= size - 1
Detailed Description
template<class T>
class ringbuffer_reader_t< T >
Definition at line 251 of file ringbuffer.h.
Constructor & Destructor Documentation
ringbuffer_reader_t() [1/2]
template<class T> ringbuffer_reader_t< T >::ringbuffer_reader_t (ringbuffer_t< T > & arg_ref) inline
constuctor.
registers this reader at the ringbuffer
Note
careful: this function is not thread-safe
Definition at line 369 of file ringbuffer.h.
References ringbuffer_reader_base::ringbuffer_reader_base(), buf, ringbuffer_base::num_readers, ref, and ringbuffer_common_t::size.
Referenced by lmms::LocklessRingBufferReader< T >::LocklessRingBufferReader(), and ringbuffer_reader_t< T >::read_sequence_t::~read_sequence_t().
ringbuffer_reader_t() [2/2]
template<class T> ringbuffer_reader_t< T >::ringbuffer_reader_t (std::size_t sz) inline
constuctor.
no registration yet thread safe
Definition at line 377 of file ringbuffer.h.
References ringbuffer_reader_base::ringbuffer_reader_base(), buf, and ref.
Member Function Documentation
_read_max_spc()
template<class T> std::size_t ringbuffer_reader_t< T >::_read_max_spc (std::size_t range) const inline private
Definition at line 315 of file ringbuffer.h.
References read_space().
Referenced by peak_max(), and read_max().
_read_spc()
template<class T> std::size_t ringbuffer_reader_t< T >::_read_spc (std::size_t range) const inline private
Definition at line 324 of file ringbuffer.h.
References detail::if_than_or_zero(), and read_space().
Referenced by peak(), and read().
connect()
template<class T> void ringbuffer_reader_t< T >::connect (ringbuffer_t< T > & _ref) inline
Note
careful: this function is not thread-safe
Definition at line 383 of file ringbuffer.h.
References buf, ringbuffer_t< T >::buf, ringbuffer_base::num_readers, ref, and ringbuffer_common_t::size.
get_size()
template<class T> std::size_t ringbuffer_reader_t< T >::get_size () const inline
return the size that the reader expects from the ringbuffer
Definition at line 424 of file ringbuffer.h.
References ringbuffer_common_t::size.
peak()
template<class T> peak_sequence_t ringbuffer_reader_t< T >::peak (std::size_t range) const inline
peaks range objects if range <= read_space(), otherwise 0
Definition at line 412 of file ringbuffer.h.
References _read_spc().
peak_max()
template<class T> peak_sequence_t ringbuffer_reader_t< T >::peak_max (std::size_t range = std::numeric_limits<std::size_t>::max()) const inline
peaks min(range, read_space()) objects
Definition at line 406 of file ringbuffer.h.
References _read_max_spc().
read()
template<class T> read_sequence_t ringbuffer_reader_t< T >::read (std::size_t range) inline
reads range objects if range <= read_space(), otherwise 0
Definition at line 401 of file ringbuffer.h.
References _read_spc().
read_max()
template<class T> read_sequence_t ringbuffer_reader_t< T >::read_max (std::size_t range = std::numeric_limits<std::size_t>::max()) inline
reads min(range, read_space()) objects
Definition at line 395 of file ringbuffer.h.
References _read_max_spc().
read_space()
template<class T> std::size_t ringbuffer_reader_t< T >::read_space () const inline
returns number of objects that can be read at least
Definition at line 417 of file ringbuffer.h.
References ringbuffer_reader_base::read_space(), and ref.
Referenced by _read_max_spc(), _read_spc(), and lmms::LocklessRingBufferReader< T >::empty().
try_inc()
template<class T> void ringbuffer_reader_t< T >::try_inc (std::size_t range) inline private
increases the read_ptr after reading from the buffer
Definition at line 330 of file ringbuffer.h.
References ringbuffer_reader_base::read_ptr, ref, ringbuffer_common_t::size, and ringbuffer_common_t::size_mask.
Referenced by ringbuffer_reader_t< T >::read_sequence_t::~read_sequence_t().
Member Data Documentation
buf
template<class T> const T* ringbuffer_reader_t< T >::buf private
Definition at line 253 of file ringbuffer.h.
Referenced by ringbuffer_reader_t(), ringbuffer_reader_t(), and connect().
ref
template<class T> ringbuffer_t<T>* ringbuffer_reader_t< T >::ref private
Definition at line 254 of file ringbuffer.h.
Referenced by ringbuffer_reader_t(), ringbuffer_reader_t(), connect(), read_space(), and try_inc().
The documentation for this class was generated from the following file:
src/3rdparty/ringbuffer/include/ringbuffer/ringbuffer.h