LMMS: Jack::JackFifo Class Reference
Jack::JackFifo Class Reference
Inter process synchronization using Fifo.
#include <JackFifo.h>
Public Member Functions
JackFifo ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Public Member Functions inherited from Jack::detail::JackSynchro
JackSynchro ()
~JackSynchro ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
void SetFlush (bool mode)
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Protected Member Functions
void BuildName (const char *name, const char *server_name, char *res, int size)
Private Member Functions
bool ConnectAux (const char *name, const char *server_name, int access)
Private Attributes
int fFifo
pollfd fPoll
Additional Inherited Members
Protected Attributes inherited from Jack::detail::JackSynchro
bool fFlush
char fName [SYNC_MAX_NAME_SIZE]
Detailed Description
Inter process synchronization using Fifo.
Definition at line 35 of file JackFifo.h.
Constructor & Destructor Documentation
JackFifo()
Jack::JackFifo::JackFifo () inline
Definition at line 51 of file JackFifo.h.
References Jack::detail::JackSynchro::JackSynchro(), and fFifo.
Member Function Documentation
Allocate()
bool Jack::JackFifo::Allocate (const char * name, const char * server_name, int value)
Definition at line 126 of file JackFifo.cpp.
References BuildName(), fFifo, Jack::detail::JackSynchro::fName, fPoll, jack_error, jack_log(), server_name, and Signal().
BuildName()
void Jack::JackFifo::BuildName (const char * name, const char * server_name, char * res, int size) protected
Definition at line 33 of file JackFifo.cpp.
References Jack::JackTools::GetUID(), jack_client_dir, Jack::JackTools::RewriteName(), server_name, and SYNC_MAX_NAME_SIZE.
Referenced by Allocate(), and ConnectAux().
Connect()
bool Jack::JackFifo::Connect (const char * name, const char * server_name)
Definition at line 185 of file JackFifo.cpp.
References ConnectAux(), and server_name.
ConnectAux()
bool Jack::JackFifo::ConnectAux (const char * name, const char * server_name, int access) private
Definition at line 164 of file JackFifo.cpp.
References BuildName(), fFifo, Jack::detail::JackSynchro::fName, fPoll, jack_error, jack_log(), and server_name.
Referenced by Connect(), ConnectInput(), and ConnectOutput().
ConnectInput()
bool Jack::JackFifo::ConnectInput (const char * name, const char * server_name)
Definition at line 195 of file JackFifo.cpp.
References ConnectAux(), and server_name.
ConnectOutput()
bool Jack::JackFifo::ConnectOutput (const char * name, const char * server_name)
Definition at line 190 of file JackFifo.cpp.
References ConnectAux(), and server_name.
Destroy()
void Jack::JackFifo::Destroy ()
Definition at line 217 of file JackFifo.cpp.
References fFifo, Jack::detail::JackSynchro::fName, jack_error, and jack_log().
Disconnect()
bool Jack::JackFifo::Disconnect ()
Definition at line 200 of file JackFifo.cpp.
References fFifo, Jack::detail::JackSynchro::fName, jack_error, and jack_log().
Signal()
bool Jack::JackFifo::Signal ()
Definition at line 40 of file JackFifo.cpp.
References fFifo, Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, and jack_error.
Referenced by Allocate().
SignalAll()
bool Jack::JackFifo::SignalAll ()
Definition at line 59 of file JackFifo.cpp.
References fFifo, Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, and jack_error.
TimedWait()
bool Jack::JackFifo::TimedWait (long usec)
Definition at line 102 of file JackFifo.cpp.
References fFifo, Jack::detail::JackSynchro::fName, fPoll, jack_error, jack_log(), and Wait().
Wait()
bool Jack::JackFifo::Wait ()
Definition at line 78 of file JackFifo.cpp.
References fFifo, Jack::detail::JackSynchro::fName, and jack_error.
Referenced by TimedWait().
Member Data Documentation
fFifo
int Jack::JackFifo::fFifo private
Definition at line 40 of file JackFifo.h.
Referenced by JackFifo(), Allocate(), ConnectAux(), Destroy(), Disconnect(), Signal(), SignalAll(), TimedWait(), and Wait().
fPoll
pollfd Jack::JackFifo::fPoll private
Definition at line 41 of file JackFifo.h.
Referenced by Allocate(), ConnectAux(), and TimedWait().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/posix/JackFifo.h
src/3rdparty/jack2/posix/JackFifo.cpp