LMMS: lmms::gui::PixmapButton Class Reference
lmms::gui::PixmapButton Class Reference
#include <PixmapButton.h>
Signals
void doubleClicked ()
Public Member Functions
PixmapButton (QWidget *_parent, const QString &_name=QString())
~PixmapButton () override=default
QSize minimumSizeHint () const override
void setActiveGraphic (const QPixmap &_pm)
void setInactiveGraphic (const QPixmap &_pm, bool _update=true)
QSize sizeHint () const override
Public Member Functions inherited from lmms::gui::AutomatableButton
AutomatableButton (QWidget *_parent, const QString &_name=QString())
~AutomatableButton () override
void modelChanged () override
void setCheckable (bool _on)
Public Member Functions inherited from lmms::gui::TypedModelView< BoolModel >
TypedModelView (Model *model, QWidget *_this)
BoolModel * model ()
const BoolModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void mouseDoubleClickEvent (QMouseEvent *_me) override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *_pe) override
Protected Member Functions inherited from lmms::gui::AutomatableButton
void contextMenuEvent (QContextMenuEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Member Functions
bool isActive () const
Private Attributes
QPixmap m_activePixmap
QPixmap m_inactivePixmap
bool m_pressed
Additional Inherited Members
Public Slots inherited from lmms::gui::AutomatableButton
virtual void setChecked (bool _on)
virtual void toggle ()
virtual void update ()
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 36 of file PixmapButton.h.
Constructor & Destructor Documentation
PixmapButton()
lmms::gui::PixmapButton::PixmapButton (QWidget * _parent, const QString & _name = QString())
Definition at line 37 of file PixmapButton.cpp.
References lmms::gui::AutomatableButton::AutomatableButton(), lmms::embed::getIconPixmap(), m_activePixmap, m_inactivePixmap, m_pressed, setActiveGraphic(), and setInactiveGraphic().
~PixmapButton()
lmms::gui::PixmapButton::~PixmapButton () override default
References minimumSizeHint(), setActiveGraphic(), setInactiveGraphic(), and sizeHint().
Member Function Documentation
doubleClicked
void lmms::gui::PixmapButton::doubleClicked () signal
References isActive(), mouseDoubleClickEvent(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
Referenced by mouseDoubleClickEvent().
isActive()
bool lmms::gui::PixmapButton::isActive () const private
Definition at line 132 of file PixmapButton.cpp.
References m_pressed, lmms::gui::TypedModelView< BoolModel >::model(), and lmms::gui::AutomatableModelView::value().
Referenced by doubleClicked(), and paintEvent().
minimumSizeHint()
QSize lmms::gui::PixmapButton::minimumSizeHint () const override
Definition at line 126 of file PixmapButton.cpp.
References lmms::embed::logicalSize(), m_activePixmap, and m_inactivePixmap.
Referenced by ~PixmapButton(), and sizeHint().
mouseDoubleClickEvent()
void lmms::gui::PixmapButton::mouseDoubleClickEvent (QMouseEvent * _me) override protected
Definition at line 98 of file PixmapButton.cpp.
References doubleClicked().
Referenced by doubleClicked().
mousePressEvent()
void lmms::gui::PixmapButton::mousePressEvent (QMouseEvent * _me) override protected virtual
Reimplemented from lmms::gui::AutomatableButton.
Definition at line 69 of file PixmapButton.cpp.
References m_pressed, lmms::gui::AutomatableButton::mousePressEvent(), and lmms::gui::AutomatableButton::update().
Referenced by doubleClicked().
mouseReleaseEvent()
void lmms::gui::PixmapButton::mouseReleaseEvent (QMouseEvent * _me) override protected
Definition at line 84 of file PixmapButton.cpp.
References m_pressed, lmms::gui::AutomatableButton::mouseReleaseEvent(), and lmms::gui::AutomatableButton::update().
Referenced by doubleClicked().
paintEvent()
void lmms::gui::PixmapButton::paintEvent (QPaintEvent * _pe) override protected
Definition at line 53 of file PixmapButton.cpp.
References isActive(), m_activePixmap, and m_inactivePixmap.
Referenced by doubleClicked().
setActiveGraphic()
void lmms::gui::PixmapButton::setActiveGraphic (const QPixmap & _pm)
Definition at line 105 of file PixmapButton.cpp.
References lmms::embed::logicalSize(), and m_activePixmap.
Referenced by PixmapButton(), and ~PixmapButton().
setInactiveGraphic()
void lmms::gui::PixmapButton::setInactiveGraphic (const QPixmap & _pm, bool _update = true)
Definition at line 112 of file PixmapButton.cpp.
References m_inactivePixmap, and lmms::gui::AutomatableButton::update().
Referenced by PixmapButton(), and ~PixmapButton().
sizeHint()
QSize lmms::gui::PixmapButton::sizeHint () const override
Definition at line 121 of file PixmapButton.cpp.
References minimumSizeHint().
Referenced by ~PixmapButton().
Member Data Documentation
m_activePixmap
QPixmap lmms::gui::PixmapButton::m_activePixmap private
Definition at line 64 of file PixmapButton.h.
Referenced by PixmapButton(), minimumSizeHint(), paintEvent(), and setActiveGraphic().
m_inactivePixmap
QPixmap lmms::gui::PixmapButton::m_inactivePixmap private
Definition at line 65 of file PixmapButton.h.
Referenced by PixmapButton(), minimumSizeHint(), paintEvent(), and setInactiveGraphic().
m_pressed
bool lmms::gui::PixmapButton::m_pressed private
Definition at line 66 of file PixmapButton.h.
Referenced by PixmapButton(), isActive(), mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
include/PixmapButton.h
src/gui/widgets/PixmapButton.cpp