LMMS: lmms::Plugin Class Reference
lmms::Plugin Class Reference abstract
Abstract representation of a plugin.
#include <Plugin.h>
Classes
struct Descriptor
Descriptor holds information about a plugin - every external plugin has to instantiate such a Descriptor in an extern "C"-section so that the plugin-loader is able to access information about the plugin.
Public Types
using DescriptorList = QList<Descriptor*>
enum class Type {
Instrument ,
Effect ,
ImportFilter ,
ExportFilter ,
Tool ,
Library ,
Other ,
Undefined = 255
}
Public Member Functions
Plugin (const Descriptor *descriptor, Model *parent, const Descriptor::SubPluginFeatures::Key *key=nullptr)
Constructor of a plugin.
~Plugin () override=default
virtual AutomatableModel * childModel (const QString &modelName)
Called if external source needs to change something but we cannot reference the class header.
gui::PluginView * createView (QWidget *parent)
Create a view for the model.
const Descriptor * descriptor () const
Return plugin Descriptor.
QString displayName () const override
Return display-name out of sub plugin or descriptor.
const Descriptor::SubPluginFeatures::Key & key () const
Return the key referencing this plugin.
virtual void loadFile (const QString &file)
Can be called if a file matching supportedFileTypes should be loaded/processed with the help of this plugin.
const PixmapLoader * logo () const
Return logo out of sub plugin or descriptor.
Type type () const
Return plugin type.
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static Plugin * instantiate (const QString &pluginName, Model *parent, void *data)
Return an instance of a plugin whose name matches to given one if specified plugin couldn't be loaded, it creates a dummy-plugin.
static Plugin * instantiateWithKey (const QString &pluginName, Model *parent, const Descriptor::SubPluginFeatures::Key *key, bool keyFromDnd=false)
Overload if the argument passed to the plugin is a subPluginKey If you can not pass the key and are aware that it's stored in Engine::pickDndPluginKey(), use this function, too.
Protected Member Functions
void collectErrorForUI (QString errMsg)
virtual gui::PluginView * instantiateView (QWidget *)=0
Create a view for the model.
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Member Functions inherited from lmms::SerializingObject
virtual void loadSettings (const QDomElement &element)=0
virtual void saveSettings (QDomDocument &doc, QDomElement &element)=0
Private Types
using InstantiationHook = Plugin* (*)(Model*, void*)
Private Attributes
const Descriptor * m_descriptor
Descriptor::SubPluginFeatures::Key m_key
Additional Inherited Members
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Detailed Description
Abstract representation of a plugin.
Such a plugin can be an Instrument, Effect, Tool plugin etc.
Plugins have descriptors, containing meta info, which is used especially by PluginFactory and friends.
There are also Plugin keys (class Key, confusingly under SubPluginFeatures), which contain pointers to the plugin descriptor.
Some plugins have sub plugins, e.g. there is one CALF Plugin and for each CALF effect, there is a CALF sub plugin. For those plugins, there are keys for each sub plugin. These keys also link to the superior Plugin::Descriptor. Additionally, they contain attributes that help the superior Plugin saving them and recognizing them when loading.
In case of sub plugins, the Descriptor has SubPluginFeatures. Those are a bit like values to the sub plugins' keys (in terms of a key-value- map).
Definition at line 71 of file Plugin.h.
Member Typedef Documentation
DescriptorList
using lmms::Plugin::DescriptorList = QList<Descriptor*>
Definition at line 235 of file Plugin.h.
InstantiationHook
using lmms::Plugin::InstantiationHook = Plugin* (*)(Model*, void*) private
Definition at line 307 of file Plugin.h.
Member Enumeration Documentation
Type
enum class lmms::Plugin::Type strong
Enumerator
Instrument
Effect
ImportFilter
ExportFilter
Tool
Library
Other
Undefined
Definition at line 75 of file Plugin.h.
Constructor & Destructor Documentation
Plugin()
lmms::Plugin::Plugin (const Descriptor * descriptor, Model * parent, const Descriptor::SubPluginFeatures::Key * key = nullptr)
Constructor of a plugin.
Parameters
key Sub plugins must pass a key here, optional otherwise. See the key() function
Definition at line 60 of file Plugin.cpp.
References lmms::JournallingObject::JournallingObject(), lmms::Model::Model(), descriptor(), lmms::dummyPluginDescriptor, key(), m_descriptor, and m_key.
Referenced by lmms::DummyPlugin::DummyPlugin(), lmms::Effect::Effect(), lmms::ExportFilter::ExportFilter(), lmms::ImportFilter::ImportFilter(), lmms::Instrument::Instrument(), lmms::ToolPlugin::ToolPlugin(), lmms::Effect::instantiate(), lmms::Instrument::instantiate(), instantiate(), lmms::ToolPlugin::instantiate(), and instantiateWithKey().
~Plugin()
lmms::Plugin::~Plugin () override default
References displayName(), and logo().
Member Function Documentation
childModel()
AutomatableModel * lmms::Plugin::childModel (const QString & modelName) virtual
Called if external source needs to change something but we cannot reference the class header.
Should return null if not key not found.
Definition at line 174 of file Plugin.cpp.
collectErrorForUI()
void lmms::Plugin::collectErrorForUI (QString errMsg) protected
Definition at line 255 of file Plugin.cpp.
References lmms::Song::collectError(), and lmms::Engine::getSong().
Referenced by instantiateView().
createView()
gui::PluginView * lmms::Plugin::createView (QWidget * parent)
Create a view for the model.
Definition at line 263 of file Plugin.cpp.
References instantiateView(), and lmms::gui::ModelView::setModel().
descriptor()
const Descriptor * lmms::Plugin::descriptor () const inline
Return plugin Descriptor.
Definition at line 257 of file Plugin.h.
References m_descriptor.
Referenced by Plugin(), lmms::gui::ToolPluginView::ToolPluginView(), and lmms::gui::InstrumentTrackView::determinePixmap().
displayName()
QString lmms::Plugin::displayName () const override virtual
Return display-name out of sub plugin or descriptor.
Reimplemented from lmms::Model.
Definition at line 93 of file Plugin.cpp.
References lmms::Model::displayName(), m_descriptor, and m_key.
Referenced by lmms::gui::ToolPluginView::ToolPluginView(), and ~Plugin().
instantiate()
Plugin * lmms::Plugin::instantiate (const QString & pluginName, Model * parent, void * data) static
Return an instance of a plugin whose name matches to given one if specified plugin couldn't be loaded, it creates a dummy-plugin.
Parameters
data Anything the plugin expects. If this is a pointer to a sub plugin key, use instantiateWithKey instead
Definition at line 208 of file Plugin.cpp.
References lmms::Model::Model(), Plugin(), lmms::gui::getGUI(), lmms::getPluginFactory(), lmms::PluginFactory::PluginInfo::isNull(), lmms::PluginFactory::PluginInfo::library, and lmms::PluginFactory::pluginInfo().
Referenced by lmms::Song::exportProjectMidi(), lmms::ImportFilter::import(), lmms::ToolPlugin::instantiate(), and instantiateWithKey().
instantiateView()
virtual gui::PluginView * lmms::Plugin::instantiateView (QWidget *) protected pure virtual
Create a view for the model.
Implemented in lmms::DummyInstrument, lmms::DummyPlugin, and lmms::Effect.
References collectErrorForUI().
Referenced by createView().
instantiateWithKey()
Plugin * lmms::Plugin::instantiateWithKey (const QString & pluginName, Model * parent, const Descriptor::SubPluginFeatures::Key * key, bool keyFromDnd = false) static
Overload if the argument passed to the plugin is a subPluginKey If you can not pass the key and are aware that it's stored in Engine::pickDndPluginKey(), use this function, too.
Definition at line 182 of file Plugin.cpp.
References lmms::Model::Model(), Plugin(), lmms::Plugin::Descriptor::SubPluginFeatures::Key::desc, lmms::PluginFactory::PluginInfo::descriptor, lmms::getPluginFactory(), instantiate(), key(), lmms::Engine::pickDndPluginKey(), and lmms::PluginFactory::pluginInfo().
Referenced by lmms::Effect::instantiate(), and lmms::Instrument::instantiate().
key()
const Descriptor::SubPluginFeatures::Key & lmms::Plugin::key () const inline
Return the key referencing this plugin.
If the Plugin has no sub plugin features, the key is pretty useless. If it has, this key will also contain the sub plugin attributes, and will be a key to those SubPluginFeatures.
Definition at line 266 of file Plugin.h.
References m_key.
Referenced by lmms::Instrument::Instrument(), lmms::Plugin::Descriptor::SubPluginFeatures::Key::Key(), Plugin(), lmms::gui::InstrumentTrackView::determinePixmap(), lmms::Instrument::instantiate(), and instantiateWithKey().
loadFile()
void lmms::Plugin::loadFile (const QString & file) virtual
Can be called if a file matching supportedFileTypes should be loaded/processed with the help of this plugin.
Definition at line 167 of file Plugin.cpp.
Referenced by lmms::gui::FileBrowserTreeWidget::openInSlicerT().
logo()
const PixmapLoader * lmms::Plugin::logo () const
Return logo out of sub plugin or descriptor.
Definition at line 107 of file Plugin.cpp.
References m_descriptor, and m_key.
Referenced by ~Plugin().
type()
Type lmms::Plugin::type () const inline
Return plugin type.
Definition at line 251 of file Plugin.h.
References m_descriptor.
Referenced by lmms::ToolPlugin::instantiate().
Member Data Documentation
m_descriptor
const Descriptor* lmms::Plugin::m_descriptor private
Definition at line 302 of file Plugin.h.
Referenced by Plugin(), descriptor(), displayName(), logo(), and type().
m_key
Descriptor::SubPluginFeatures::Key lmms::Plugin::m_key private
Definition at line 304 of file Plugin.h.
Referenced by Plugin(), displayName(), key(), and logo().
The documentation for this class was generated from the following files:
include/Plugin.h
src/core/Plugin.cpp