LMMS: lmms::SerializingObjectHook Class Reference
lmms::SerializingObjectHook Class Reference abstract
#include <SerializingObject.h>
Public Member Functions
SerializingObjectHook ()
virtual ~SerializingObjectHook ()
virtual void loadSettings (const QDomElement &_this)=0
virtual void saveSettings (QDomDocument &_doc, QDomElement &_this)=0
Private Attributes
SerializingObject * m_hookedIn
Friends
class SerializingObject
Detailed Description
Definition at line 76 of file SerializingObject.h.
Constructor & Destructor Documentation
SerializingObjectHook()
lmms::SerializingObjectHook::SerializingObjectHook () inline
Definition at line 79 of file SerializingObject.h.
References m_hookedIn.
Referenced by lmms::gui::MixerView::MixerView(), and lmms::gui::TrackContainerView::TrackContainerView().
~SerializingObjectHook()
virtual lmms::SerializingObjectHook::~SerializingObjectHook () inline virtual
Definition at line 83 of file SerializingObject.h.
References m_hookedIn.
Member Function Documentation
loadSettings()
virtual void lmms::SerializingObjectHook::loadSettings (const QDomElement & _this) pure virtual
Implemented in lmms::gui::InstrumentTrackWindow, lmms::gui::MixerView, lmms::gui::PatternEditor, lmms::gui::SampleTrackWindow, lmms::gui::SongEditor, and lmms::gui::TrackContainerView.
Referenced by lmms::SerializingObject::restoreState().
saveSettings()
virtual void lmms::SerializingObjectHook::saveSettings (QDomDocument & _doc, QDomElement & _this) pure virtual
Implemented in lmms::gui::InstrumentTrackWindow, lmms::gui::MixerView, lmms::gui::PatternEditor, lmms::gui::SampleTrackWindow, lmms::gui::SongEditor, and lmms::gui::TrackContainerView.
Referenced by lmms::SerializingObject::saveState().
Friends And Related Symbol Documentation
SerializingObject
friend class SerializingObject friend
Definition at line 97 of file SerializingObject.h.
References SerializingObject.
Referenced by SerializingObject.
Member Data Documentation
m_hookedIn
SerializingObject* lmms::SerializingObjectHook::m_hookedIn private
Definition at line 95 of file SerializingObject.h.
Referenced by SerializingObjectHook(), and ~SerializingObjectHook().
The documentation for this class was generated from the following file:
include/SerializingObject.h