LMMS: lmms::gui::LcdFloatSpinBox Class Reference
lmms::gui::LcdFloatSpinBox Class Reference
#include <LcdFloatSpinBox.h>
Public Slots
virtual void update ()
Signals
void manualChange ()
Public Member Functions
LcdFloatSpinBox (int numWhole, int numFrac, const QString &name=QString(), QWidget *parent=nullptr)
LcdFloatSpinBox (int numWhole, int numFrac, const QString &style, const QString &name, QWidget *parent=nullptr)
void modelChanged () override
void setLabel (const QString &label)
void setSeamless (bool left, bool right)
Public Member Functions inherited from lmms::gui::TypedModelView< FloatModel >
TypedModelView (Model *model, QWidget *_this)
FloatModel * model ()
const FloatModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *me) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
void paintEvent (QPaintEvent *pe) override
void wheelEvent (QWheelEvent *we) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Member Functions
void enterValue ()
float getStep () const
void layoutSetup (const QString &style=QString("19green"))
Private Attributes
int m_displayOffset
LcdWidget m_fractionDisplay
bool m_intStep
QString m_label
bool m_mouseMoving
QPoint m_origMousePos
LcdWidget m_wholeDisplay
Additional Inherited Members
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 38 of file LcdFloatSpinBox.h.
Constructor & Destructor Documentation
LcdFloatSpinBox() [1/2]
lmms::gui::LcdFloatSpinBox::LcdFloatSpinBox (int numWhole, int numFrac, const QString & name = QString(), QWidget * parent = nullptr)
Definition at line 53 of file LcdFloatSpinBox.cpp.
References layoutSetup(), m_displayOffset, m_fractionDisplay, m_intStep, m_mouseMoving, m_origMousePos, and m_wholeDisplay.
LcdFloatSpinBox() [2/2]
lmms::gui::LcdFloatSpinBox::LcdFloatSpinBox (int numWhole, int numFrac, const QString & style, const QString & name, QWidget * parent = nullptr)
Definition at line 67 of file LcdFloatSpinBox.cpp.
References layoutSetup(), m_displayOffset, m_fractionDisplay, m_intStep, m_mouseMoving, m_origMousePos, and m_wholeDisplay.
Member Function Documentation
contextMenuEvent()
void lmms::gui::LcdFloatSpinBox::contextMenuEvent (QContextMenuEvent * me) override protected
Definition at line 129 of file LcdFloatSpinBox.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), and lmms::gui::TypedModelView< FloatModel >::model().
enterValue()
void lmms::gui::LcdFloatSpinBox::enterValue () private
Definition at line 207 of file LcdFloatSpinBox.cpp.
References m_fractionDisplay, lmms::gui::TypedModelView< FloatModel >::model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Referenced by mouseDoubleClickEvent().
getStep()
float lmms::gui::LcdFloatSpinBox::getStep () const private
Definition at line 229 of file LcdFloatSpinBox.cpp.
References m_intStep, lmms::gui::TypedModelView< FloatModel >::model(), and lmms::AutomatableModel::step().
Referenced by mouseMoveEvent(), and wheelEvent().
layoutSetup()
void lmms::gui::LcdFloatSpinBox::layoutSetup (const QString & style = QString("19green")) private
Definition at line 81 of file LcdFloatSpinBox.cpp.
References lmms::embed::getIconPixmap(), m_fractionDisplay, and m_wholeDisplay.
Referenced by LcdFloatSpinBox(), and LcdFloatSpinBox().
manualChange
void lmms::gui::LcdFloatSpinBox::manualChange () signal
Referenced by mouseMoveEvent(), and wheelEvent().
modelChanged()
void lmms::gui::LcdFloatSpinBox::modelChanged () inline override virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 45 of file LcdFloatSpinBox.h.
References lmms::gui::ModelView::modelChanged(), and update().
mouseDoubleClickEvent()
void lmms::gui::LcdFloatSpinBox::mouseDoubleClickEvent (QMouseEvent * me) override protected
Definition at line 201 of file LcdFloatSpinBox.cpp.
References enterValue().
mouseMoveEvent()
void lmms::gui::LcdFloatSpinBox::mouseMoveEvent (QMouseEvent * me) override protected
Definition at line 163 of file LcdFloatSpinBox.cpp.
References lmms::gui::getGUI(), getStep(), m_mouseMoving, m_origMousePos, manualChange(), lmms::gui::TypedModelView< FloatModel >::model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
mousePressEvent()
void lmms::gui::LcdFloatSpinBox::mousePressEvent (QMouseEvent * me) override protected virtual
Reimplemented from lmms::gui::AutomatableModelView.
Definition at line 137 of file LcdFloatSpinBox.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), lmms::KBD_COPY_MODIFIER, m_intStep, m_mouseMoving, m_origMousePos, m_wholeDisplay, lmms::gui::TypedModelView< FloatModel >::model(), lmms::gui::AutomatableModelView::mousePressEvent(), and lmms::JournallingObject::saveJournallingState().
mouseReleaseEvent()
void lmms::gui::LcdFloatSpinBox::mouseReleaseEvent (QMouseEvent * me) override protected
Definition at line 179 of file LcdFloatSpinBox.cpp.
References m_mouseMoving, lmms::gui::TypedModelView< FloatModel >::model(), and lmms::JournallingObject::restoreJournallingState().
paintEvent()
void lmms::gui::LcdFloatSpinBox::paintEvent (QPaintEvent * pe) override protected
Definition at line 236 of file LcdFloatSpinBox.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, m_label, and m_wholeDisplay.
setLabel()
void lmms::gui::LcdFloatSpinBox::setLabel (const QString & label) inline
Definition at line 51 of file LcdFloatSpinBox.h.
References m_label.
setSeamless()
void lmms::gui::LcdFloatSpinBox::setSeamless (bool left, bool right) inline
Definition at line 53 of file LcdFloatSpinBox.h.
References m_fractionDisplay, and m_wholeDisplay.
update
void lmms::gui::LcdFloatSpinBox::update () virtual slot
Definition at line 112 of file LcdFloatSpinBox.cpp.
References lmms::fastPow10f(), lmms::fraction(), m_fractionDisplay, m_wholeDisplay, lmms::gui::TypedModelView< FloatModel >::model(), lmms::gui::AutomatableModelView::value(), and lmms::TypedAutomatableModel< T >::value().
Referenced by modelChanged().
wheelEvent()
void lmms::gui::LcdFloatSpinBox::wheelEvent (QWheelEvent * we) override protected
Definition at line 189 of file LcdFloatSpinBox.cpp.
References getStep(), m_intStep, m_wholeDisplay, manualChange(), lmms::gui::TypedModelView< FloatModel >::model(), lmms::position(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Member Data Documentation
m_displayOffset
int lmms::gui::LcdFloatSpinBox::m_displayOffset private
Definition at line 81 of file LcdFloatSpinBox.h.
Referenced by LcdFloatSpinBox(), and LcdFloatSpinBox().
m_fractionDisplay
LcdWidget lmms::gui::LcdFloatSpinBox::m_fractionDisplay private
Definition at line 77 of file LcdFloatSpinBox.h.
Referenced by LcdFloatSpinBox(), LcdFloatSpinBox(), enterValue(), layoutSetup(), setSeamless(), and update().
m_intStep
bool lmms::gui::LcdFloatSpinBox::m_intStep private
Definition at line 79 of file LcdFloatSpinBox.h.
Referenced by LcdFloatSpinBox(), LcdFloatSpinBox(), getStep(), mousePressEvent(), and wheelEvent().
m_label
QString lmms::gui::LcdFloatSpinBox::m_label private
Definition at line 82 of file LcdFloatSpinBox.h.
Referenced by paintEvent(), and setLabel().
m_mouseMoving
bool lmms::gui::LcdFloatSpinBox::m_mouseMoving private
Definition at line 78 of file LcdFloatSpinBox.h.
Referenced by LcdFloatSpinBox(), LcdFloatSpinBox(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_origMousePos
QPoint lmms::gui::LcdFloatSpinBox::m_origMousePos private
Definition at line 80 of file LcdFloatSpinBox.h.
Referenced by LcdFloatSpinBox(), LcdFloatSpinBox(), mouseMoveEvent(), and mousePressEvent().
m_wholeDisplay
LcdWidget lmms::gui::LcdFloatSpinBox::m_wholeDisplay private
Definition at line 76 of file LcdFloatSpinBox.h.
Referenced by LcdFloatSpinBox(), LcdFloatSpinBox(), layoutSetup(), mousePressEvent(), paintEvent(), setSeamless(), update(), and wheelEvent().
The documentation for this class was generated from the following files:
include/LcdFloatSpinBox.h
src/gui/widgets/LcdFloatSpinBox.cpp