LMMS: Jack::AtomicArrayCounter Struct Reference
Jack::AtomicArrayCounter Struct Reference
Counter for CAS.
#include <JackAtomicArrayState.h>
Public Member Functions
AtomicArrayCounter ()
AtomicArrayCounter (volatile AtomicArrayCounter &obj)
AtomicArrayCounter (volatile const AtomicArrayCounter &obj)
AtomicArrayCounter & operator= (AtomicArrayCounter &obj)
AtomicArrayCounter & operator= (volatile AtomicArrayCounter &obj)
Public Attributes
union {
UInt32 fLongVal
struct {
unsigned char fByteVal [4]
} scounter
} info
Detailed Description
Counter for CAS.
Definition at line 35 of file JackAtomicArrayState.h.
Constructor & Destructor Documentation
AtomicArrayCounter() [1/3]
Jack::AtomicArrayCounter::AtomicArrayCounter () inline
Definition at line 45 of file JackAtomicArrayState.h.
References info.
Referenced by AtomicArrayCounter(), AtomicArrayCounter(), operator=(), and operator=().
AtomicArrayCounter() [2/3]
Jack::AtomicArrayCounter::AtomicArrayCounter (volatile const AtomicArrayCounter & obj) inline
Definition at line 50 of file JackAtomicArrayState.h.
References AtomicArrayCounter(), fLongVal, and info.
AtomicArrayCounter() [3/3]
Jack::AtomicArrayCounter::AtomicArrayCounter (volatile AtomicArrayCounter & obj) inline
Definition at line 55 of file JackAtomicArrayState.h.
References AtomicArrayCounter(), fLongVal, and info.
Member Function Documentation
operator=() [1/2]
AtomicArrayCounter & Jack::AtomicArrayCounter::operator= (AtomicArrayCounter & obj) inline
Definition at line 66 of file JackAtomicArrayState.h.
References AtomicArrayCounter(), fLongVal, and info.
operator=() [2/2]
AtomicArrayCounter & Jack::AtomicArrayCounter::operator= (volatile AtomicArrayCounter & obj) inline
Definition at line 60 of file JackAtomicArrayState.h.
References AtomicArrayCounter(), fLongVal, and info.
Member Data Documentation
fByteVal
unsigned char Jack::AtomicArrayCounter::fByteVal[4]
Definition at line 39 of file JackAtomicArrayState.h.
fLongVal
UInt32 Jack::AtomicArrayCounter::fLongVal
Definition at line 42 of file JackAtomicArrayState.h.
Referenced by AtomicArrayCounter(), AtomicArrayCounter(), operator=(), and operator=().
[union]
union { ... } Jack::AtomicArrayCounter::info
Referenced by AtomicArrayCounter(), AtomicArrayCounter(), AtomicArrayCounter(), operator=(), and operator=().
[struct]
struct { ... } Jack::AtomicArrayCounter::scounter
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackAtomicArrayState.h