LMMS: lmms::gui::MainApplication Class Reference
lmms::gui::MainApplication Class Reference
#include <MainApplication.h>
Public Member Functions
MainApplication (int &argc, char **argv)
bool event (QEvent *event) override
QString & queuedFile ()
Private Attributes
QString m_queuedFile
Detailed Description
Definition at line 45 of file MainApplication.h.
Constructor & Destructor Documentation
MainApplication()
lmms::gui::MainApplication::MainApplication (int & argc, char ** argv)
Definition at line 38 of file MainApplication.cpp.
References m_queuedFile.
Member Function Documentation
event()
bool lmms::gui::MainApplication::event (QEvent * event) override
Definition at line 60 of file MainApplication.cpp.
References event(), lmms::gui::getGUI(), lmms::Engine::getSong(), lmms::Song::loadProject(), and m_queuedFile.
Referenced by event().
queuedFile()
QString & lmms::gui::MainApplication::queuedFile () inline
Definition at line 56 of file MainApplication.h.
References m_queuedFile.
Member Data Documentation
m_queuedFile
QString lmms::gui::MainApplication::m_queuedFile private
Definition at line 61 of file MainApplication.h.
Referenced by MainApplication(), event(), and queuedFile().
The documentation for this class was generated from the following files:
include/MainApplication.h
src/gui/MainApplication.cpp