LMMS: hiir::Upsampler2xSseOld< NC > Class Template Reference
hiir::Upsampler2xSseOld< NC > Class Template Reference
#include <Upsampler2xSseOld.h>
Public Types
typedef float DataType
Public Member Functions
Upsampler2xSseOld () noexcept
Upsampler2xSseOld (const Upsampler2xSseOld< NC > &other)=default
Upsampler2xSseOld (Upsampler2xSseOld< NC > &&other)=default
~Upsampler2xSseOld ()=default
void clear_buffers () noexcept
Upsampler2xSseOld< NC > & operator= (const Upsampler2xSseOld< NC > &other)=default
Upsampler2xSseOld< NC > & operator= (Upsampler2xSseOld< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (float &out_0, float &out_1, float input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 2
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataSse, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Upsampler2xSseOld< NC > &other) const =delete
bool operator== (const Upsampler2xSseOld< NC > &other) const =delete
hiir_FORCEINLINE long process_block_quad (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void set_single_coef (int index, double coef) noexcept
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _coef_shift = ((NBR_COEFS & 1) * 2) ^ 3
static constexpr int _nbr_stages
static constexpr int _stage_width = 4
Detailed Description
template<int NC>
class hiir::Upsampler2xSseOld< NC >
Definition at line 55 of file Upsampler2xSseOld.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Upsampler2xSseOld< NC >::DataType
Definition at line 64 of file Upsampler2xSseOld.h.
Filter
template<int NC> typedef std::array<StageDataSse, _nbr_stages + 1> hiir::Upsampler2xSseOld< NC >::Filter private
Definition at line 105 of file Upsampler2xSseOld.h.
Constructor & Destructor Documentation
Upsampler2xSseOld() [1/3]
template<int NC> hiir::Upsampler2xSseOld< NC >::Upsampler2xSseOld () noexcept
Definition at line 62 of file Upsampler2xSseOld.hpp.
References _filter, _nbr_stages, _stage_width, clear_buffers(), i, NBR_COEFS, and set_single_coef().
Referenced by Upsampler2xSseOld(), Upsampler2xSseOld(), ~Upsampler2xSseOld(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2xSseOld() [2/3]
template<int NC> hiir::Upsampler2xSseOld< NC >::Upsampler2xSseOld (const Upsampler2xSseOld< NC > & other) default
References Upsampler2xSseOld().
Upsampler2xSseOld() [3/3]
template<int NC> hiir::Upsampler2xSseOld< NC >::Upsampler2xSseOld (Upsampler2xSseOld< NC > && other) default
References Upsampler2xSseOld().
~Upsampler2xSseOld()
template<int NC> hiir::Upsampler2xSseOld< NC >::~Upsampler2xSseOld () default
References Upsampler2xSseOld().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2xSseOld< NC >::clear_buffers () noexcept
Definition at line 184 of file Upsampler2xSseOld.hpp.
References _filter, _nbr_stages, and i.
Referenced by Upsampler2xSseOld(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2xSseOld< NC >::operator!= (const Upsampler2xSseOld< NC > & other) const private delete
References Upsampler2xSseOld().
operator=() [1/2]
template<int NC> Upsampler2xSseOld< NC > & hiir::Upsampler2xSseOld< NC >::operator= (const Upsampler2xSseOld< NC > & other) default
References Upsampler2xSseOld().
operator=() [2/2]
template<int NC> Upsampler2xSseOld< NC > & hiir::Upsampler2xSseOld< NC >::operator= (Upsampler2xSseOld< NC > && other) default
References Upsampler2xSseOld(), clear_buffers(), hiir_FORCEINLINE, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2xSseOld< NC >::operator== (const Upsampler2xSseOld< NC > & other) const private delete
References Upsampler2xSseOld().
process_block()
template<int NC> void hiir::Upsampler2xSseOld< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 156 of file Upsampler2xSseOld.hpp.
References pos, process_block_quad(), and process_sample().
Referenced by operator=().
process_block_quad()
template<int NC> long hiir::Upsampler2xSseOld< NC >::process_block_quad (float out_ptr[], const float in_ptr[], long nbr_spl) private noexcept
Definition at line 225 of file Upsampler2xSseOld.hpp.
References _filter, _nbr_stages, pos, and hiir::StageProcSseV4< CUR >::process_sample_pos().
Referenced by process_block().
process_sample()
template<int NC> void hiir::Upsampler2xSseOld< NC >::process_sample (float & out_0, float & out_1, float input) noexcept
Definition at line 121 of file Upsampler2xSseOld.hpp.
References _filter, _nbr_stages, and hiir::StageProcSseV4< CUR >::process_sample_pos().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::Upsampler2xSseOld< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 94 of file Upsampler2xSseOld.hpp.
References i, NBR_COEFS, and set_single_coef().
Referenced by operator=().
set_single_coef()
template<int NC> void hiir::Upsampler2xSseOld< NC >::set_single_coef (int index, double coef) inline private noexcept
Definition at line 212 of file Upsampler2xSseOld.hpp.
References _coef_shift, _filter, _nbr_stages, _stage_width, and pos.
Referenced by Upsampler2xSseOld(), and set_coefs().
Member Data Documentation
_coef_shift
template<int NC> int hiir::Upsampler2xSseOld< NC >::_coef_shift = ((NBR_COEFS & 1) * 2) ^ 3 static constexpr private
Definition at line 102 of file Upsampler2xSseOld.h.
Referenced by set_single_coef().
_delay
template<int NC> double hiir::Upsampler2xSseOld< NC >::_delay = 2 static constexpr
Definition at line 67 of file Upsampler2xSseOld.h.
_filter
template<int NC> Filter hiir::Upsampler2xSseOld< NC >::_filter private
Definition at line 114 of file Upsampler2xSseOld.h.
Referenced by Upsampler2xSseOld(), clear_buffers(), process_block_quad(), process_sample(), and set_single_coef().
_nbr_chn
template<int NC> int hiir::Upsampler2xSseOld< NC >::_nbr_chn = 1 static constexpr
Definition at line 65 of file Upsampler2xSseOld.h.
_nbr_stages
template<int NC> int hiir::Upsampler2xSseOld< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 100 of file Upsampler2xSseOld.h.
Referenced by Upsampler2xSseOld(), clear_buffers(), process_block_quad(), process_sample(), and set_single_coef().
_stage_width
template<int NC> int hiir::Upsampler2xSseOld< NC >::_stage_width = 4 static constexpr private
Definition at line 99 of file Upsampler2xSseOld.h.
Referenced by Upsampler2xSseOld(), and set_single_coef().
NBR_COEFS
template<int NC> int hiir::Upsampler2xSseOld< NC >::NBR_COEFS = NC static constexpr
Definition at line 66 of file Upsampler2xSseOld.h.
Referenced by Upsampler2xSseOld(), operator=(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2xSseOld.h
src/3rdparty/hiir/hiir/Upsampler2xSseOld.hpp