LMMS: lmms::gui::SideBar Class Reference
lmms::gui::SideBar Class Reference
#include <SideBar.h>
Public Member Functions
SideBar (Qt::Orientation _orientation, QWidget *_parent)
~SideBar () override=default
void appendTab (SideBarWidget *_sbw)
Private Types
using ButtonMap = QMap<QToolButton*, QWidget*>
Private Slots
void toggleButton (QAbstractButton *_btn)
Private Attributes
QButtonGroup m_btnGroup
ButtonMap m_widgets
Detailed Description
Definition at line 40 of file SideBar.h.
Member Typedef Documentation
ButtonMap
using lmms::gui::SideBar::ButtonMap = QMap<QToolButton*, QWidget*> private
Definition at line 56 of file SideBar.h.
Constructor & Destructor Documentation
SideBar()
lmms::gui::SideBar::SideBar (Qt::Orientation _orientation, QWidget * _parent)
Definition at line 89 of file SideBar.cpp.
References m_btnGroup, and toggleButton().
~SideBar()
lmms::gui::SideBar::~SideBar () override default
Member Function Documentation
appendTab()
void lmms::gui::SideBar::appendTab (SideBarWidget * _sbw)
Definition at line 104 of file SideBar.cpp.
References lmms::gui::SideBarWidget::closeButtonClicked(), lmms::gui::SideBarWidget::icon(), m_btnGroup, m_widgets, and lmms::gui::SideBarWidget::title().
toggleButton
void lmms::gui::SideBar::toggleButton (QAbstractButton * _btn) private slot
Definition at line 127 of file SideBar.cpp.
References m_widgets.
Referenced by SideBar().
Member Data Documentation
m_btnGroup
QButtonGroup lmms::gui::SideBar::m_btnGroup private
Definition at line 55 of file SideBar.h.
Referenced by SideBar(), and appendTab().
m_widgets
ButtonMap lmms::gui::SideBar::m_widgets private
Definition at line 57 of file SideBar.h.
Referenced by appendTab(), and toggleButton().
The documentation for this class was generated from the following files:
include/SideBar.h
src/gui/SideBar.cpp