LMMS: src/3rdparty/jack2/common/varargs.h File Reference
varargs.h File Reference
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include "types.h"
Classes
struct jack_varargs_t
Functions
static const char * jack_default_server_name (void)
static void jack_varargs_init (jack_varargs_t *va)
static void jack_varargs_parse (jack_options_t options, va_list ap, jack_varargs_t *va)
Function Documentation
jack_default_server_name()
const char * jack_default_server_name (void) static
Definition at line 42 of file varargs.h.
References server_name.
Referenced by jack_varargs_init().
jack_varargs_init()
void jack_varargs_init (jack_varargs_t * va) inline static
Definition at line 50 of file varargs.h.
References jack_default_server_name(), and jack_varargs_t::server_name.
Referenced by jack_client_new_aux(), and jack_varargs_parse().
jack_varargs_parse()
void jack_varargs_parse (jack_options_t options, va_list ap, jack_varargs_t * va) inline static
Definition at line 56 of file varargs.h.
References jack_varargs_init(), JackLoadInit, JackLoadName, JackServerName, JackSessionID, jack_varargs_t::load_init, jack_varargs_t::load_name, jack_varargs_t::server_name, and jack_varargs_t::session_id.
Referenced by jack_client_open_aux(), jack_client_open_aux(), and jack_internal_client_load_aux().