LMMS: src/3rdparty/jack2/posix/JackPosixServerLaunch.cpp File Reference
JackPosixServerLaunch.cpp File Reference
#include "JackConstants.h"
#include "JackChannel.h"
#include "JackLibGlobals.h"
#include "JackServerLaunch.h"
#include "JackPlatformPlug.h"
#include <sys/wait.h>
Functions
static int server_connect (char *server_name)
static int start_server (const char *server_name, jack_options_t options)
int try_start_server (jack_varargs_t *va, jack_options_t options, jack_status_t *status)
Function Documentation
server_connect()
int server_connect (char * server_name) static
Definition at line 243 of file JackPosixServerLaunch.cpp.
References Jack::JackSocketClientChannel::Close(), JackSleep(), server_name, and Jack::JackGenericClientChannel::ServerCheck().
Referenced by try_start_server().
start_server()
int start_server (const char * server_name, jack_options_t options) static
Definition at line 227 of file JackPosixServerLaunch.cpp.
References JackNoStartServer, and server_name.
Referenced by try_start_server().
try_start_server()
int try_start_server (jack_varargs_t * va, jack_options_t options, jack_status_t * status)
Definition at line 253 of file JackPosixServerLaunch.cpp.