LMMS: Jack::JackWinEvent Class Reference
Jack::JackWinEvent Class Reference
Inter process synchronization using system wide events.
#include <JackWinEvent.h>
Public Member Functions
JackWinEvent ()
virtual ~JackWinEvent ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Public Member Functions inherited from Jack::JackAndroidSemaphore
JackAndroidSemaphore ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Public Member Functions inherited from Jack::detail::JackSynchro
JackSynchro ()
~JackSynchro ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
void SetFlush (bool mode)
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Protected Member Functions
void BuildName (const char *name, const char *server_name, char *res, int size)
Protected Member Functions inherited from Jack::JackAndroidSemaphore
void BuildName (const char *name, const char *server_name, char *res, int size)
Private Attributes
HANDLE fEvent
Additional Inherited Members
Protected Attributes inherited from Jack::detail::JackSynchro
bool fFlush
char fName [SYNC_MAX_NAME_SIZE]
Detailed Description
Inter process synchronization using system wide events.
Definition at line 39 of file JackWinEvent.h.
Constructor & Destructor Documentation
JackWinEvent()
Jack::JackWinEvent::JackWinEvent () inline
Definition at line 52 of file JackWinEvent.h.
References fEvent.
~JackWinEvent()
virtual Jack::JackWinEvent::~JackWinEvent () inline virtual
Definition at line 54 of file JackWinEvent.h.
Member Function Documentation
Allocate()
bool Jack::JackWinEvent::Allocate (const char * name, const char * server_name, int value)
Definition at line 131 of file JackWinEvent.cpp.
References BuildName(), FALSE, fEvent, Jack::detail::JackSynchro::fName, jack_error, jack_log(), and server_name.
BuildName()
void Jack::JackWinEvent::BuildName (const char * name, const char * server_name, char * res, int size) protected
Definition at line 32 of file JackWinEvent.cpp.
References server_name.
Referenced by Allocate(), and ConnectInput().
Connect()
bool Jack::JackWinEvent::Connect (const char * name, const char * server_name)
Definition at line 109 of file JackWinEvent.cpp.
References ConnectInput(), and server_name.
ConnectInput()
bool Jack::JackWinEvent::ConnectInput (const char * name, const char * server_name)
Definition at line 90 of file JackWinEvent.cpp.
References BuildName(), FALSE, fEvent, Jack::detail::JackSynchro::fName, jack_error, jack_log(), and server_name.
Referenced by Connect(), and ConnectOutput().
ConnectOutput()
bool Jack::JackWinEvent::ConnectOutput (const char * name, const char * server_name)
Definition at line 114 of file JackWinEvent.cpp.
References ConnectInput(), and server_name.
Destroy()
void Jack::JackWinEvent::Destroy ()
Definition at line 150 of file JackWinEvent.cpp.
References fEvent, Jack::detail::JackSynchro::fName, jack_error, and jack_log().
Disconnect()
bool Jack::JackWinEvent::Disconnect ()
Definition at line 119 of file JackWinEvent.cpp.
References fEvent, Jack::detail::JackSynchro::fName, and jack_log().
Signal()
bool Jack::JackWinEvent::Signal ()
Definition at line 37 of file JackWinEvent.cpp.
References fEvent, Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, and jack_error.
SignalAll()
bool Jack::JackWinEvent::SignalAll ()
Definition at line 52 of file JackWinEvent.cpp.
References fEvent, Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, and jack_error.
TimedWait()
bool Jack::JackWinEvent::TimedWait (long usec)
Definition at line 78 of file JackWinEvent.cpp.
References fEvent, Jack::detail::JackSynchro::fName, and jack_error.
Wait()
bool Jack::JackWinEvent::Wait ()
Definition at line 67 of file JackWinEvent.cpp.
References fEvent, Jack::detail::JackSynchro::fName, and jack_error.
Member Data Documentation
fEvent
HANDLE Jack::JackWinEvent::fEvent private
Definition at line 44 of file JackWinEvent.h.
Referenced by JackWinEvent(), Allocate(), ConnectInput(), Destroy(), Disconnect(), Signal(), SignalAll(), TimedWait(), and Wait().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinEvent.h
src/3rdparty/jack2/windows/JackWinEvent.cpp