LMMS: hiir::Upsampler2xSse< NC > Class Template Reference
hiir::Upsampler2xSse< NC > Class Template Reference
#include <Upsampler2xSse.h>
Public Types
typedef float DataType
Public Member Functions
Upsampler2xSse () noexcept
Upsampler2xSse (const Upsampler2xSse &other)=default
Upsampler2xSse (Upsampler2xSse &&other)=default
~Upsampler2xSse ()=default
void clear_buffers () noexcept
Upsampler2xSse & operator= (const Upsampler2xSse &other)=default
Upsampler2xSse & operator= (Upsampler2xSse &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (float &out_0, float &out_1, float input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataSse, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Upsampler2xSse &other) const =delete
bool operator== (const Upsampler2xSse &other) const =delete
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _nbr_stages
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::Upsampler2xSse< NC >
Definition at line 48 of file Upsampler2xSse.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Upsampler2xSse< NC >::DataType
Definition at line 57 of file Upsampler2xSse.h.
Filter
template<int NC> typedef std::array<StageDataSse, _nbr_stages + 1> hiir::Upsampler2xSse< NC >::Filter private
Definition at line 97 of file Upsampler2xSse.h.
Constructor & Destructor Documentation
Upsampler2xSse() [1/3]
template<int NC> hiir::Upsampler2xSse< NC >::Upsampler2xSse () noexcept
Definition at line 57 of file Upsampler2xSse.hpp.
References _filter, _nbr_stages, clear_buffers(), i, and NBR_COEFS.
Referenced by Upsampler2xSse(), Upsampler2xSse(), ~Upsampler2xSse(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2xSse() [2/3]
template<int NC> hiir::Upsampler2xSse< NC >::Upsampler2xSse (const Upsampler2xSse< NC > & other) default
References Upsampler2xSse().
Upsampler2xSse() [3/3]
template<int NC> hiir::Upsampler2xSse< NC >::Upsampler2xSse (Upsampler2xSse< NC > && other) default
References Upsampler2xSse().
~Upsampler2xSse()
template<int NC> hiir::Upsampler2xSse< NC >::~Upsampler2xSse () default
References Upsampler2xSse().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2xSse< NC >::clear_buffers () noexcept
Definition at line 201 of file Upsampler2xSse.hpp.
References _filter, _nbr_stages, and i.
Referenced by Upsampler2xSse(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2xSse< NC >::operator!= (const Upsampler2xSse< NC > & other) const private delete
References Upsampler2xSse().
operator=() [1/2]
template<int NC> Upsampler2xSse & hiir::Upsampler2xSse< NC >::operator= (const Upsampler2xSse< NC > & other) default
References Upsampler2xSse().
operator=() [2/2]
template<int NC> Upsampler2xSse & hiir::Upsampler2xSse< NC >::operator= (Upsampler2xSse< NC > && other) default
References Upsampler2xSse(), clear_buffers(), hiir_FORCEINLINE, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2xSse< NC >::operator== (const Upsampler2xSse< NC > & other) const private delete
References Upsampler2xSse().
process_block()
template<int NC> void hiir::Upsampler2xSse< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 145 of file Upsampler2xSse.hpp.
References _filter, pos, and hiir::StageProcSseV2< CUR >::process_sample_pos().
Referenced by operator=().
process_sample()
template<int NC> void hiir::Upsampler2xSse< NC >::process_sample (float & out_0, float & out_1, float input) noexcept
Definition at line 118 of file Upsampler2xSse.hpp.
References _filter, and hiir::StageProcSseV2< CUR >::process_sample_pos().
Referenced by operator=().
set_coefs()
template<int NC> void hiir::Upsampler2xSse< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 89 of file Upsampler2xSse.hpp.
References _filter, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Upsampler2xSse< NC >::_delay = 0 static constexpr
Definition at line 60 of file Upsampler2xSse.h.
_filter
template<int NC> Filter hiir::Upsampler2xSse< NC >::_filter private
Definition at line 99 of file Upsampler2xSse.h.
Referenced by Upsampler2xSse(), clear_buffers(), process_block(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Upsampler2xSse< NC >::_nbr_chn = 1 static constexpr
Definition at line 58 of file Upsampler2xSse.h.
_nbr_stages
template<int NC> int hiir::Upsampler2xSse< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 93 of file Upsampler2xSse.h.
Referenced by Upsampler2xSse(), and clear_buffers().
_stage_width
template<int NC> int hiir::Upsampler2xSse< NC >::_stage_width = 2 static constexpr private
Definition at line 92 of file Upsampler2xSse.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::Upsampler2xSse< NC >::NBR_COEFS = NC static constexpr
Definition at line 59 of file Upsampler2xSse.h.
Referenced by Upsampler2xSse(), operator=(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2xSse.h
src/3rdparty/hiir/hiir/Upsampler2xSse.hpp