LMMS: lmms::gui::NStateButton Class Reference
lmms::gui::NStateButton Class Reference
#include <NStateButton.h>
Public Slots
void changeState (int state)
Signals
void changedState (int state)
Public Member Functions
NStateButton (QWidget *_parent)
~NStateButton () override
void addState (const QPixmap &_pixmap, const QString &_tooltip="")
void setGeneralToolTip (const QString &_tooltip)
int state () const
Public Member Functions inherited from lmms::gui::ToolButton
ToolButton (const QPixmap &_pixmap, const QString &_tooltip, QObject *_receiver=nullptr, const char *_slot=nullptr, QWidget *_parent=nullptr)
ToolButton (QWidget *_parent)
~ToolButton () override=default
Protected Member Functions
void mousePressEvent (QMouseEvent *me) override
Private Attributes
int m_curState
QString m_generalToolTip
QVector< QPair< QPixmap, QString > > m_states
Detailed Description
Definition at line 38 of file NStateButton.h.
Constructor & Destructor Documentation
NStateButton()
lmms::gui::NStateButton::NStateButton (QWidget * _parent)
Definition at line 35 of file NStateButton.cpp.
References lmms::gui::ToolButton::ToolButton(), m_curState, and m_generalToolTip.
~NStateButton()
lmms::gui::NStateButton::~NStateButton () override
Definition at line 45 of file NStateButton.cpp.
References m_states.
Member Function Documentation
addState()
void lmms::gui::NStateButton::addState (const QPixmap & _pixmap, const QString & _tooltip = "")
Definition at line 56 of file NStateButton.cpp.
References changeState(), and m_states.
changedState
void lmms::gui::NStateButton::changedState (int state) signal
References state().
Referenced by lmms::gui::TimeLineWidget::addToolButtons(), and changeState().
changeState
void lmms::gui::NStateButton::changeState (int state) slot
Definition at line 70 of file NStateButton.cpp.
References changedState(), m_curState, m_generalToolTip, m_states, and state().
Referenced by addState(), lmms::gui::TimeLineWidget::addToolButtons(), and mousePressEvent().
mousePressEvent()
void lmms::gui::NStateButton::mousePressEvent (QMouseEvent * me) override protected
Definition at line 84 of file NStateButton.cpp.
References changeState(), m_curState, and m_states.
setGeneralToolTip()
void lmms::gui::NStateButton::setGeneralToolTip (const QString & _tooltip) inline
Definition at line 46 of file NStateButton.h.
References m_generalToolTip.
state()
int lmms::gui::NStateButton::state () const inline
Definition at line 51 of file NStateButton.h.
References m_curState.
Referenced by changedState(), and changeState().
Member Data Documentation
m_curState
int lmms::gui::NStateButton::m_curState private
Definition at line 70 of file NStateButton.h.
Referenced by NStateButton(), changeState(), mousePressEvent(), and state().
m_generalToolTip
QString lmms::gui::NStateButton::m_generalToolTip private
Definition at line 68 of file NStateButton.h.
Referenced by NStateButton(), changeState(), and setGeneralToolTip().
m_states
QVector<QPair<QPixmap, QString> > lmms::gui::NStateButton::m_states private
Definition at line 67 of file NStateButton.h.
Referenced by ~NStateButton(), addState(), changeState(), and mousePressEvent().
The documentation for this class was generated from the following files:
include/NStateButton.h
src/gui/widgets/NStateButton.cpp