LMMS: lmms::EffectControls Class Reference
lmms::EffectControls Class Reference abstract
#include <EffectControls.h>
Public Member Functions
EffectControls (Effect *_eff)
~EffectControls () override=default
virtual int controlCount ()=0
virtual gui::EffectControlDialog * createView ()=0
Effect * effect ()
bool isViewVisible () const
void setViewVisible (bool _visible)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
void setHook (SerializingObjectHook *_hook)
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Private Attributes
Effect * m_effect
bool m_viewVisible
Additional Inherited Members
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Member Functions inherited from lmms::SerializingObject
virtual void loadSettings (const QDomElement &element)=0
virtual void saveSettings (QDomDocument &doc, QDomElement &element)=0
Detailed Description
Definition at line 43 of file EffectControls.h.
Constructor & Destructor Documentation
EffectControls()
lmms::EffectControls::EffectControls (Effect * _eff) inline
Definition at line 46 of file EffectControls.h.
References lmms::JournallingObject::JournallingObject(), lmms::Model::Model(), m_effect, and m_viewVisible.
Referenced by lmms::DummyEffectControls::DummyEffectControls().
~EffectControls()
lmms::EffectControls::~EffectControls () override default
Member Function Documentation
controlCount()
virtual int lmms::EffectControls::controlCount () pure virtual
Implemented in lmms::DummyEffectControls.
createView()
virtual gui::EffectControlDialog * lmms::EffectControls::createView () pure virtual
Implemented in lmms::DummyEffectControls.
Referenced by lmms::gui::EffectView::EffectView().
effect()
Effect * lmms::EffectControls::effect () inline
Definition at line 70 of file EffectControls.h.
References m_effect.
isViewVisible()
bool lmms::EffectControls::isViewVisible () const inline
Definition at line 65 of file EffectControls.h.
References m_viewVisible.
setViewVisible()
void lmms::EffectControls::setViewVisible (bool _visible) inline
Definition at line 60 of file EffectControls.h.
References m_viewVisible.
Referenced by lmms::gui::EffectView::closeEffects(), and lmms::gui::EffectView::editControls().
Member Data Documentation
m_effect
Effect* lmms::EffectControls::m_effect private
Definition at line 77 of file EffectControls.h.
Referenced by EffectControls(), and effect().
m_viewVisible
bool lmms::EffectControls::m_viewVisible private
Definition at line 78 of file EffectControls.h.
Referenced by EffectControls(), isViewVisible(), and setViewVisible().
The documentation for this class was generated from the following file:
include/EffectControls.h