LMMS: lmms::MixerRoute Class Reference
lmms::MixerRoute Class Reference
#include <Mixer.h>
Public Member Functions
MixerRoute (MixerChannel *from, MixerChannel *to, float amount)
~MixerRoute () override=default
FloatModel * amount ()
MixerChannel * receiver () const
mix_ch_t receiverIndex () const
MixerChannel * sender () const
mix_ch_t senderIndex () const
void updateName ()
Private Attributes
FloatModel m_amount
MixerChannel * m_from
MixerChannel * m_to
Detailed Description
Definition at line 98 of file Mixer.h.
Constructor & Destructor Documentation
MixerRoute()
lmms::MixerRoute::MixerRoute (MixerChannel * from, MixerChannel * to, float amount)
Definition at line 42 of file Mixer.cpp.
References amount(), m_amount, m_from, and m_to.
~MixerRoute()
lmms::MixerRoute::~MixerRoute () override default
Member Function Documentation
amount()
FloatModel * lmms::MixerRoute::amount () inline
Definition at line 115 of file Mixer.h.
References m_amount.
Referenced by MixerRoute(), lmms::Mixer::channelSendModel(), and lmms::Mixer::loadSettings().
receiver()
MixerChannel * lmms::MixerRoute::receiver () const inline
Definition at line 125 of file Mixer.h.
References m_to.
Referenced by lmms::Mixer::channelSendModel(), and lmms::Mixer::deleteChannelSend().
receiverIndex()
mix_ch_t lmms::MixerRoute::receiverIndex () const inline
Definition at line 110 of file Mixer.h.
References m_to.
sender()
MixerChannel * lmms::MixerRoute::sender () const inline
Definition at line 120 of file Mixer.h.
References m_from.
Referenced by lmms::Mixer::deleteChannelSend().
senderIndex()
mix_ch_t lmms::MixerRoute::senderIndex () const inline
Definition at line 105 of file Mixer.h.
References m_from.
updateName()
void lmms::MixerRoute::updateName ()
Definition at line 53 of file Mixer.cpp.
References m_amount, m_from, and m_to.
Member Data Documentation
m_amount
FloatModel lmms::MixerRoute::m_amount private
Definition at line 135 of file Mixer.h.
Referenced by MixerRoute(), amount(), and updateName().
m_from
MixerChannel* lmms::MixerRoute::m_from private
Definition at line 133 of file Mixer.h.
Referenced by MixerRoute(), sender(), senderIndex(), and updateName().
m_to
MixerChannel* lmms::MixerRoute::m_to private
Definition at line 134 of file Mixer.h.
Referenced by MixerRoute(), receiver(), receiverIndex(), and updateName().
The documentation for this class was generated from the following files:
include/Mixer.h
src/core/Mixer.cpp