LMMS: src/3rdparty/jack2/common/jack/statistics.h File Reference
statistics.h File Reference
#include <jack/types.h>
Functions
float jack_get_max_delayed_usecs (jack_client_t *client)
float jack_get_xrun_delayed_usecs (jack_client_t *client)
void jack_reset_max_delayed_usecs (jack_client_t *client)
Reset the maximum delay counter.
Function Documentation
jack_get_max_delayed_usecs()
LIB_EXPORT float jack_get_max_delayed_usecs (jack_client_t * client)
Returns
the maximum delay reported by the backend since startup or reset. When compared to the period size in usecs, this can be used to estimate the ideal period size for a given setup.
Definition at line 1671 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fMaxDelayedUsecs, Jack::GetEngineControl(), jack_error, and LIB_EXPORT.
jack_get_xrun_delayed_usecs()
LIB_EXPORT float jack_get_xrun_delayed_usecs (jack_client_t * client)
Returns
the delay in microseconds due to the most recent XRUN occurrence. This probably only makes sense when called from a JackXRunCallback defined using jack_set_xrun_callback().
Definition at line 1685 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fXrunDelayedUsecs, Jack::GetEngineControl(), jack_error, and LIB_EXPORT.
jack_reset_max_delayed_usecs()
LIB_EXPORT void jack_reset_max_delayed_usecs (jack_client_t * client)
Reset the maximum delay counter.
This would be useful to estimate the effect that a change to the configuration of a running system (e.g. toggling kernel preemption) has on the delay experienced by JACK, without having to restart the JACK engine.
Definition at line 1699 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::GetEngineControl(), jack_error, LIB_EXPORT, and Jack::JackEngineControl::ResetXRun().