LMMS: src/3rdparty/jack2/tests/testSynchroServer.cpp File Reference
testSynchroServer.cpp File Reference
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <semaphore.h>
#include <sys/time.h>
#include <time.h>
#include "JackPlatformPlug.h"
Classes
class Test1< sync_type >
Macros
#define CLIENT "client3"
#define ITER 1000
#define SERVER "serveur3"
Functions
int main (int ac, char *av[])
Macro Definition Documentation
CLIENT
#define CLIENT "client3"
Definition at line 55 of file testSynchroServer.cpp.
ITER
#define ITER 1000
Definition at line 52 of file testSynchroServer.cpp.
SERVER
#define SERVER "serveur3"
Definition at line 54 of file testSynchroServer.cpp.
Function Documentation
main()
int main (int ac, char * av[])
Definition at line 137 of file testSynchroServer.cpp.
References Jack::JackAndroidThread::AcquireRealTime(), Jack::detail::JackSynchro::Allocate(), CLIENT, Jack::detail::JackSynchro::Destroy(), Jack::PTHREAD_CANCEL_DEFERRED, SERVER, Jack::JackAndroidThread::Start(), and Jack::JackAndroidThread::Stop().