LMMS: src/3rdparty/jack2/common/JackNetAdapter.cpp File Reference
JackNetAdapter.cpp File Reference
#include "JackNetAdapter.h"
#include "JackException.h"
#include "JackServerGlobals.h"
#include "JackEngineControl.h"
#include "JackArgParser.h"
#include <assert.h>
#include "driver_interface.h"
#include "JackAudioAdapter.h"
Namespaces
namespace Jack
Functions
SERVER_EXPORT void jack_finish (void *arg)
SERVER_EXPORT jack_driver_desc_t * jack_get_descriptor ()
SERVER_EXPORT int jack_initialize (jack_client_t *jack_client, const char *load_init)
SERVER_EXPORT int jack_internal_initialize (jack_client_t *client, const JSList *params)
Function Documentation
jack_finish()
SERVER_EXPORT void jack_finish (void * arg)
Definition at line 513 of file JackNetAdapter.cpp.
References Jack::JackAudioAdapter::Close(), jack_log(), and SERVER_EXPORT.
jack_get_descriptor()
SERVER_EXPORT jack_driver_desc_t * jack_get_descriptor ()
Definition at line 416 of file JackNetAdapter.cpp.
References DEFAULT_MTU, DEFAULT_MULTICAST_IP, DEFAULT_PORT, jack_driver_param_value_t::i, jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverNone, JackDriverParamBool, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, SERVER_EXPORT, jack_driver_param_value_t::str, and jack_driver_param_value_t::ui.
Referenced by jack_initialize().
jack_initialize()
SERVER_EXPORT int jack_initialize (jack_client_t * jack_client, const char * load_init)
Definition at line 494 of file JackNetAdapter.cpp.
References Jack::JackArgParser::FreeParams(), Jack::JackArgParser::GetArgc(), jack_get_descriptor(), jack_internal_initialize(), Jack::JackArgParser::ParseParams(), and SERVER_EXPORT.
jack_internal_initialize()
SERVER_EXPORT int jack_internal_initialize (jack_client_t * client, const JSList * params)
Definition at line 468 of file JackNetAdapter.cpp.
References client(), jack_get_buffer_size(), jack_get_sample_rate(), jack_info(), jack_log(), Jack::JackAudioAdapter::Open(), and SERVER_EXPORT.
Referenced by jack_initialize().