LMMS: lmms::ArrayVector< T, N > Class Template Reference
lmms::ArrayVector< T, N > Class Template Reference
A container that stores up to a maximum of N elements of type T directly within itself, rather than separately on the heap.
#include <ArrayVector.h>
Public Types
using const_iterator = const_pointer
using const_pointer = const T*
using const_reference = const T&
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using difference_type = std::ptrdiff_t
using iterator = pointer
using pointer = T*
using reference = T&
using reverse_iterator = std::reverse_iterator<iterator>
using size_type = std::size_t
using value_type = T
Public Member Functions
ArrayVector ()=default
ArrayVector (ArrayVector &&other) noexcept(std::is_nothrow_move_constructible_v< T >)
ArrayVector (const ArrayVector &other) noexcept(std::is_nothrow_copy_constructible_v< T >)
template<typename It, std::enable_if_t< detail::is_input_iterator_v< It >, int > = 0>
ArrayVector (It first, It last)
ArrayVector (size_type count) noexcept(std::is_nothrow_default_constructible_v< T >)
ArrayVector (size_type count, const T &value) noexcept(std::is_nothrow_copy_constructible_v< T >)
ArrayVector (std::initializer_list< T > il) noexcept(std::is_nothrow_copy_constructible_v< T >)
~ArrayVector ()
template<typename It, std::enable_if_t< detail::is_input_iterator_v< It >, int > = 0>
void assign (It first, It last)
void assign (size_type count, const T &value) noexcept(std::is_nothrow_copy_assignable_v< T > &&std::is_nothrow_copy_constructible_v< T >)
reference at (size_type index)
const_reference at (size_type index) const
const_reference back () const noexcept
reference back () noexcept
const_iterator begin () const noexcept
iterator begin () noexcept
size_type capacity () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
const_pointer data () const noexcept
pointer data () noexcept
template<typename... Args>
iterator emplace (const_iterator pos, Args &&... args)
template<typename... Args>
reference emplace_back (Args &&... args)
bool empty () const noexcept
const_iterator end () const noexcept
iterator end () noexcept
iterator erase (const_iterator first, const_iterator last)
iterator erase (const_iterator pos)
const_reference front () const noexcept
reference front () noexcept
bool full () const noexcept
iterator insert (const_iterator pos, const T &value)
template<typename It, std::enable_if_t< detail::is_input_iterator_v< It >, int > = 0>
iterator insert (const_iterator pos, It first, It last)
iterator insert (const_iterator pos, size_type count, const T &value)
iterator insert (const_iterator pos, std::initializer_list< T > il)
iterator insert (const_iterator pos, T &&value)
size_type max_size () const noexcept
ArrayVector & operator= (ArrayVector &&other) noexcept(std::is_nothrow_move_assignable_v< T > &&std::is_nothrow_move_constructible_v< T >)
ArrayVector & operator= (const ArrayVector &other) noexcept(std::is_nothrow_copy_assignable_v< T > &&std::is_nothrow_copy_constructible_v< T >)
ArrayVector & operator= (std::initializer_list< T > il) noexcept(std::is_nothrow_copy_assignable_v< T > &&std::is_nothrow_copy_constructible_v< T >)
const_reference operator[] (size_type index) const noexcept
reference operator[] (size_type index) noexcept
void pop_back ()
void push_back (const T &value)
void push_back (T &&value)
const_reverse_iterator rbegin () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rend () const noexcept
reverse_iterator rend () noexcept
void resize (size_type size)
void resize (size_type size, const value_type &value)
size_type size () const noexcept
void swap (ArrayVector &other) noexcept(std::is_nothrow_swappable_v< T > &&std::is_nothrow_move_constructible_v< T >)
Private Attributes
std::byte m_data [std::max(N *sizeof(T), std::size_t{1})]
size_type m_size = 0
Friends
bool operator!= (const ArrayVector &l, const ArrayVector &r)
bool operator< (const ArrayVector &l, const ArrayVector &r)
bool operator<= (const ArrayVector &l, const ArrayVector &r)
bool operator== (const ArrayVector &l, const ArrayVector &r)
bool operator> (const ArrayVector &l, const ArrayVector &r)
bool operator>= (const ArrayVector &l, const ArrayVector &r)
void swap (ArrayVector &a, ArrayVector &b) noexcept(std::is_nothrow_swappable_v< T > &&std::is_nothrow_move_constructible_v< T >)
Detailed Description
template<typename T, std::size_t N>
class lmms::ArrayVector< T, N >
A container that stores up to a maximum of N elements of type T directly within itself, rather than separately on the heap.
Useful when a dynamically resizeable container is needed for use in real-time code. Can be thought of as a hybrid between std::array and std::vector. The interface follows that of std::vector - see standard C++ documentation.
Definition at line 59 of file ArrayVector.h.
Member Typedef Documentation
const_iterator
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::const_iterator = const_pointer
Definition at line 70 of file ArrayVector.h.
const_pointer
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::const_pointer = const T*
Definition at line 68 of file ArrayVector.h.
const_reference
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::const_reference = const T&
Definition at line 66 of file ArrayVector.h.
const_reverse_iterator
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 72 of file ArrayVector.h.
difference_type
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::difference_type = std::ptrdiff_t
Definition at line 63 of file ArrayVector.h.
iterator
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::iterator = pointer
Definition at line 69 of file ArrayVector.h.
pointer
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::pointer = T*
Definition at line 67 of file ArrayVector.h.
reference
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::reference = T&
Definition at line 65 of file ArrayVector.h.
reverse_iterator
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 71 of file ArrayVector.h.
size_type
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::size_type = std::size_t
Definition at line 62 of file ArrayVector.h.
value_type
template<typename T, std::size_t N> using lmms::ArrayVector< T, N >::value_type = T
Definition at line 64 of file ArrayVector.h.
Constructor & Destructor Documentation
ArrayVector() [1/7]
template<typename T, std::size_t N> lmms::ArrayVector< T, N >::ArrayVector () default
Referenced by ArrayVector(), ArrayVector(), operator!=, operator<, operator<=, operator=(), operator=(), operator=(), operator==, operator>, operator>=, swap, and swap().
ArrayVector() [2/7]
template<typename T, std::size_t N> lmms::ArrayVector< T, N >::ArrayVector (const ArrayVector< T, N > & other) inline noexcept
Definition at line 76 of file ArrayVector.h.
References ArrayVector(), begin(), and m_size.
ArrayVector() [3/7]
template<typename T, std::size_t N> lmms::ArrayVector< T, N >::ArrayVector (ArrayVector< T, N > && other) inline noexcept
Definition at line 82 of file ArrayVector.h.
References ArrayVector(), begin(), and m_size.
ArrayVector() [4/7]
template<typename T, std::size_t N> lmms::ArrayVector< T, N >::ArrayVector (size_type count, const T & value) inline noexcept
Definition at line 89 of file ArrayVector.h.
References begin(), and m_size.
ArrayVector() [5/7]
template<typename T, std::size_t N> lmms::ArrayVector< T, N >::ArrayVector (size_type count) inline explicit noexcept
Definition at line 96 of file ArrayVector.h.
References begin(), and m_size.
ArrayVector() [6/7]
template<typename T, std::size_t N> template<typename It, std::enable_if_t< detail::is_input_iterator_v< It >, int > = 0> lmms::ArrayVector< T, N >::ArrayVector (It first, It last) inline
Definition at line 104 of file ArrayVector.h.
References begin(), end(), and m_size.
ArrayVector() [7/7]
template<typename T, std::size_t N> lmms::ArrayVector< T, N >::ArrayVector (std::initializer_list< T > il) inline noexcept
Definition at line 112 of file ArrayVector.h.
References begin(), m_size, and size().
~ArrayVector()
template<typename T, std::size_t N> lmms::ArrayVector< T, N >::~ArrayVector () inline
Definition at line 119 of file ArrayVector.h.
References begin(), and end().
Member Function Documentation
assign() [1/2]
template<typename T, std::size_t N> template<typename It, std::enable_if_t< detail::is_input_iterator_v< It >, int > = 0> void lmms::ArrayVector< T, N >::assign (It first, It last) inline
Definition at line 177 of file ArrayVector.h.
References begin(), end(), m_size, and pos.
assign() [2/2]
template<typename T, std::size_t N> void lmms::ArrayVector< T, N >::assign (size_type count, const T & value) inline noexcept
Definition at line 163 of file ArrayVector.h.
References begin(), end(), m_size, and size().
at() [1/2]
template<typename T, std::size_t N> reference lmms::ArrayVector< T, N >::at (size_type index) inline
Definition at line 190 of file ArrayVector.h.
References data(), and m_size.
at() [2/2]
template<typename T, std::size_t N> const_reference lmms::ArrayVector< T, N >::at (size_type index) const inline
Definition at line 196 of file ArrayVector.h.
References data(), and m_size.
back() [1/2]
template<typename T, std::size_t N> const_reference lmms::ArrayVector< T, N >::back () const inline noexcept
Definition at line 218 of file ArrayVector.h.
References m_size, and operator[]().
back() [2/2]
template<typename T, std::size_t N> reference lmms::ArrayVector< T, N >::back () inline noexcept
Definition at line 217 of file ArrayVector.h.
References m_size, and operator[]().
begin() [1/2]
template<typename T, std::size_t N> const_iterator lmms::ArrayVector< T, N >::begin () const inline noexcept
Definition at line 224 of file ArrayVector.h.
References data().
begin() [2/2]
template<typename T, std::size_t N> iterator lmms::ArrayVector< T, N >::begin () inline noexcept
Definition at line 223 of file ArrayVector.h.
References data().
Referenced by ArrayVector(), ArrayVector(), ArrayVector(), ArrayVector(), ArrayVector(), ArrayVector(), ~ArrayVector(), assign(), assign(), clear(), emplace(), erase(), insert(), insert(), operator<, operator=(), operator=(), operator=(), operator==, rend(), rend(), resize(), and resize().
capacity()
template<typename T, std::size_t N> size_type lmms::ArrayVector< T, N >::capacity () const inline noexcept
Definition at line 243 of file ArrayVector.h.
cbegin()
template<typename T, std::size_t N> const_iterator lmms::ArrayVector< T, N >::cbegin () const inline noexcept
Definition at line 225 of file ArrayVector.h.
References data().
Referenced by crend(), emplace(), erase(), insert(), and insert().
cend()
template<typename T, std::size_t N> const_iterator lmms::ArrayVector< T, N >::cend () const inline noexcept
Definition at line 229 of file ArrayVector.h.
References data(), and m_size.
Referenced by crbegin(), emplace(), erase(), insert(), and insert().
clear()
template<typename T, std::size_t N> void lmms::ArrayVector< T, N >::clear () inline noexcept
Definition at line 245 of file ArrayVector.h.
References begin(), end(), and m_size.
crbegin()
template<typename T, std::size_t N> const_reverse_iterator lmms::ArrayVector< T, N >::crbegin () const inline noexcept
Definition at line 233 of file ArrayVector.h.
References cend().
crend()
template<typename T, std::size_t N> const_reverse_iterator lmms::ArrayVector< T, N >::crend () const inline noexcept
Definition at line 237 of file ArrayVector.h.
References cbegin().
data() [1/2]
template<typename T, std::size_t N> const_pointer lmms::ArrayVector< T, N >::data () const inline noexcept
Definition at line 221 of file ArrayVector.h.
References m_data.
data() [2/2]
template<typename T, std::size_t N> pointer lmms::ArrayVector< T, N >::data () inline noexcept
Definition at line 220 of file ArrayVector.h.
References m_data.
Referenced by at(), at(), begin(), begin(), cbegin(), cend(), end(), end(), operator[](), and operator[]().
emplace()
template<typename T, std::size_t N> template<typename... Args> iterator lmms::ArrayVector< T, N >::emplace (const_iterator pos, Args &&... args) inline
Definition at line 281 of file ArrayVector.h.
References begin(), cbegin(), cend(), emplace_back(), end(), and pos.
Referenced by insert(), and insert().
emplace_back()
template<typename T, std::size_t N> template<typename... Args> reference lmms::ArrayVector< T, N >::emplace_back (Args &&... args) inline
Definition at line 306 of file ArrayVector.h.
References end(), full(), and m_size.
Referenced by emplace(), push_back(), and push_back().
empty()
template<typename T, std::size_t N> bool lmms::ArrayVector< T, N >::empty () const inline noexcept
Definition at line 239 of file ArrayVector.h.
References m_size.
Referenced by pop_back().
end() [1/2]
template<typename T, std::size_t N> const_iterator lmms::ArrayVector< T, N >::end () const inline noexcept
Definition at line 228 of file ArrayVector.h.
References data(), and m_size.
end() [2/2]
template<typename T, std::size_t N> iterator lmms::ArrayVector< T, N >::end () inline noexcept
Definition at line 227 of file ArrayVector.h.
References data(), and m_size.
Referenced by ArrayVector(), ~ArrayVector(), assign(), assign(), clear(), emplace(), emplace_back(), erase(), insert(), insert(), operator<, operator=(), operator=(), operator=(), operator==, pop_back(), rbegin(), rbegin(), resize(), and resize().
erase() [1/2]
template<typename T, std::size_t N> iterator lmms::ArrayVector< T, N >::erase (const_iterator first, const_iterator last) inline
Definition at line 291 of file ArrayVector.h.
References begin(), cbegin(), cend(), end(), and m_size.
erase() [2/2]
template<typename T, std::size_t N> iterator lmms::ArrayVector< T, N >::erase (const_iterator pos) inline
Definition at line 290 of file ArrayVector.h.
References erase(), and pos.
Referenced by erase().
front() [1/2]
template<typename T, std::size_t N> const_reference lmms::ArrayVector< T, N >::front () const inline noexcept
Definition at line 215 of file ArrayVector.h.
References operator[]().
front() [2/2]
template<typename T, std::size_t N> reference lmms::ArrayVector< T, N >::front () inline noexcept
Definition at line 214 of file ArrayVector.h.
References operator[]().
full()
template<typename T, std::size_t N> bool lmms::ArrayVector< T, N >::full () const inline noexcept
Definition at line 240 of file ArrayVector.h.
References m_size.
Referenced by emplace_back().
insert() [1/5]
template<typename T, std::size_t N> iterator lmms::ArrayVector< T, N >::insert (const_iterator pos, const T & value) inline
Definition at line 251 of file ArrayVector.h.
References emplace(), and pos.
insert() [2/5]
template<typename T, std::size_t N> template<typename It, std::enable_if_t< detail::is_input_iterator_v< It >, int > = 0> iterator lmms::ArrayVector< T, N >::insert (const_iterator pos, It first, It last) inline
Definition at line 266 of file ArrayVector.h.
References begin(), cbegin(), cend(), end(), m_size, and pos.
insert() [3/5]
template<typename T, std::size_t N> iterator lmms::ArrayVector< T, N >::insert (const_iterator pos, size_type count, const T & value) inline
Definition at line 254 of file ArrayVector.h.
References begin(), cbegin(), cend(), end(), m_size, and pos.
insert() [4/5]
template<typename T, std::size_t N> iterator lmms::ArrayVector< T, N >::insert (const_iterator pos, std::initializer_list< T > il) inline
Definition at line 278 of file ArrayVector.h.
References insert(), and pos.
Referenced by insert().
insert() [5/5]
template<typename T, std::size_t N> iterator lmms::ArrayVector< T, N >::insert (const_iterator pos, T && value) inline
Definition at line 252 of file ArrayVector.h.
References emplace(), and pos.
max_size()
template<typename T, std::size_t N> size_type lmms::ArrayVector< T, N >::max_size () const inline noexcept
Definition at line 242 of file ArrayVector.h.
operator=() [1/3]
template<typename T, std::size_t N> ArrayVector & lmms::ArrayVector< T, N >::operator= (ArrayVector< T, N > && other) inline noexcept
Definition at line 135 of file ArrayVector.h.
References ArrayVector(), begin(), end(), m_size, and size().
operator=() [2/3]
template<typename T, std::size_t N> ArrayVector & lmms::ArrayVector< T, N >::operator= (const ArrayVector< T, N > & other) inline noexcept
Definition at line 121 of file ArrayVector.h.
References ArrayVector(), begin(), end(), m_size, and size().
operator=() [3/3]
template<typename T, std::size_t N> ArrayVector & lmms::ArrayVector< T, N >::operator= (std::initializer_list< T > il) inline noexcept
Definition at line 150 of file ArrayVector.h.
References ArrayVector(), begin(), end(), m_size, and size().
operator[]() [1/2]
template<typename T, std::size_t N> const_reference lmms::ArrayVector< T, N >::operator[] (size_type index) const inline noexcept
Definition at line 208 of file ArrayVector.h.
References data(), and m_size.
operator[]() [2/2]
template<typename T, std::size_t N> reference lmms::ArrayVector< T, N >::operator[] (size_type index) inline noexcept
Definition at line 202 of file ArrayVector.h.
References data(), and m_size.
Referenced by back(), back(), front(), and front().
pop_back()
template<typename T, std::size_t N> void lmms::ArrayVector< T, N >::pop_back () inline
Definition at line 315 of file ArrayVector.h.
References empty(), end(), and m_size.
push_back() [1/2]
template<typename T, std::size_t N> void lmms::ArrayVector< T, N >::push_back (const T & value) inline
Definition at line 302 of file ArrayVector.h.
References emplace_back().
push_back() [2/2]
template<typename T, std::size_t N> void lmms::ArrayVector< T, N >::push_back (T && value) inline
Definition at line 303 of file ArrayVector.h.
References emplace_back().
rbegin() [1/2]
template<typename T, std::size_t N> const_reverse_iterator lmms::ArrayVector< T, N >::rbegin () const inline noexcept
Definition at line 232 of file ArrayVector.h.
References end().
rbegin() [2/2]
template<typename T, std::size_t N> reverse_iterator lmms::ArrayVector< T, N >::rbegin () inline noexcept
Definition at line 231 of file ArrayVector.h.
References end().
rend() [1/2]
template<typename T, std::size_t N> const_reverse_iterator lmms::ArrayVector< T, N >::rend () const inline noexcept
Definition at line 236 of file ArrayVector.h.
References begin().
rend() [2/2]
template<typename T, std::size_t N> reverse_iterator lmms::ArrayVector< T, N >::rend () inline noexcept
Definition at line 235 of file ArrayVector.h.
References begin().
resize() [1/2]
template<typename T, std::size_t N> void lmms::ArrayVector< T, N >::resize (size_type size) inline
Definition at line 322 of file ArrayVector.h.
References begin(), end(), m_size, and size().
resize() [2/2]
template<typename T, std::size_t N> void lmms::ArrayVector< T, N >::resize (size_type size, const value_type & value) inline
Definition at line 333 of file ArrayVector.h.
References begin(), end(), m_size, and size().
size()
template<typename T, std::size_t N> size_type lmms::ArrayVector< T, N >::size () const inline noexcept
Definition at line 241 of file ArrayVector.h.
References m_size.
Referenced by ArrayVector(), assign(), operator=(), operator=(), operator=(), resize(), and resize().
swap()
template<typename T, std::size_t N> void lmms::ArrayVector< T, N >::swap (ArrayVector< T, N > & other) inline noexcept
Definition at line 344 of file ArrayVector.h.
References ArrayVector(), and swap().
Referenced by swap().
Friends And Related Symbol Documentation
operator!=
template<typename T, std::size_t N> bool operator!= (const ArrayVector< T, N > & l, const ArrayVector< T, N > & r) friend
Definition at line 379 of file ArrayVector.h.
References ArrayVector().
operator<
template<typename T, std::size_t N> bool operator< (const ArrayVector< T, N > & l, const ArrayVector< T, N > & r) friend
Definition at line 366 of file ArrayVector.h.
References ArrayVector(), begin(), and end().
operator<=
template<typename T, std::size_t N> bool operator<= (const ArrayVector< T, N > & l, const ArrayVector< T, N > & r) friend
Definition at line 370 of file ArrayVector.h.
References ArrayVector().
operator==
template<typename T, std::size_t N> bool operator== (const ArrayVector< T, N > & l, const ArrayVector< T, N > & r) friend
Definition at line 374 of file ArrayVector.h.
References ArrayVector(), begin(), and end().
operator>
template<typename T, std::size_t N> bool operator> (const ArrayVector< T, N > & l, const ArrayVector< T, N > & r) friend
Definition at line 371 of file ArrayVector.h.
References ArrayVector().
operator>=
template<typename T, std::size_t N> bool operator>= (const ArrayVector< T, N > & l, const ArrayVector< T, N > & r) friend
Definition at line 372 of file ArrayVector.h.
References ArrayVector().
swap
template<typename T, std::size_t N> void swap (ArrayVector< T, N > & a, ArrayVector< T, N > & b) friend
Definition at line 351 of file ArrayVector.h.
References ArrayVector().
Member Data Documentation
m_data
template<typename T, std::size_t N> std::byte lmms::ArrayVector< T, N >::m_data[std::max(N *sizeof(T), std::size_t{1})] private
Definition at line 382 of file ArrayVector.h.
Referenced by data(), and data().
m_size
template<typename T, std::size_t N> size_type lmms::ArrayVector< T, N >::m_size = 0 private
Definition at line 383 of file ArrayVector.h.
Referenced by ArrayVector(), ArrayVector(), ArrayVector(), ArrayVector(), ArrayVector(), ArrayVector(), assign(), assign(), at(), at(), back(), back(), cend(), clear(), emplace_back(), empty(), end(), end(), erase(), full(), insert(), insert(), operator=(), operator=(), operator=(), operator[](), operator[](), pop_back(), resize(), resize(), and size().
The documentation for this class was generated from the following file:
include/ArrayVector.h