LMMS: Jack::detail::JackChannelTransactionInterface Class Reference
Jack::detail::JackChannelTransactionInterface Class Reference abstract
#include <JackChannel.h>
Public Member Functions
JackChannelTransactionInterface ()
virtual ~JackChannelTransactionInterface ()
virtual int Read (void *data, int len)=0
virtual int Write (void *data, int len)=0
Detailed Description
Definition at line 39 of file JackChannel.h.
Constructor & Destructor Documentation
JackChannelTransactionInterface()
Jack::detail::JackChannelTransactionInterface::JackChannelTransactionInterface () inline
Definition at line 44 of file JackChannel.h.
~JackChannelTransactionInterface()
virtual Jack::detail::JackChannelTransactionInterface::~JackChannelTransactionInterface () inline virtual
Definition at line 46 of file JackChannel.h.
Member Function Documentation
Read()
virtual int Jack::detail::JackChannelTransactionInterface::Read (void * data, int len) pure virtual
Implemented in Jack::detail::JackClientRequestInterface, Jack::JackClientSocket, Jack::JackWinAsyncNamedPipeClient, Jack::JackWinNamedPipe, and Jack::JackWinNamedPipeClient.
Referenced by Jack::JackActivateRequest::Read(), Jack::JackClientCheckRequest::Read(), Jack::JackClientCheckResult::Read(), Jack::JackClientCloseRequest::Read(), Jack::JackClientHasSessionCallbackRequest::Read(), Jack::JackClientNameResult::Read(), Jack::JackClientNotification::Read(), Jack::JackClientNotificationRequest::Read(), Jack::JackClientOpenRequest::Read(), Jack::JackClientOpenResult::Read(), Jack::JackDeactivateRequest::Read(), Jack::JackGetClientNameRequest::Read(), Jack::JackGetInternalClientNameRequest::Read(), Jack::JackGetInternalClientNameResult::Read(), Jack::JackGetUUIDRequest::Read(), Jack::JackInternalClientHandleRequest::Read(), Jack::JackInternalClientHandleResult::Read(), Jack::JackInternalClientLoadRequest::Read(), Jack::JackInternalClientLoadResult::Read(), Jack::JackInternalClientUnloadRequest::Read(), Jack::JackInternalClientUnloadResult::Read(), Jack::JackPortConnectNameRequest::Read(), Jack::JackPortConnectRequest::Read(), Jack::JackPortDisconnectNameRequest::Read(), Jack::JackPortDisconnectRequest::Read(), Jack::JackPortRegisterRequest::Read(), Jack::JackPortRegisterResult::Read(), Jack::JackPortRenameRequest::Read(), Jack::JackPortUnRegisterRequest::Read(), Jack::JackPropertyChangeNotifyRequest::Read(), Jack::JackReleaseTimebaseRequest::Read(), Jack::JackRequest::Read(), Jack::JackReserveNameRequest::Read(), Jack::JackResult::Read(), Jack::JackSessionNotifyRequest::Read(), Jack::JackSessionNotifyResult::Read(), Jack::JackSessionReplyRequest::Read(), Jack::JackSetBufferSizeRequest::Read(), Jack::JackSetFreeWheelRequest::Read(), Jack::JackSetTimebaseCallbackRequest::Read(), and Jack::JackUUIDResult::Read().
Write()
virtual int Jack::detail::JackChannelTransactionInterface::Write (void * data, int len) pure virtual
Implemented in Jack::detail::JackClientRequestInterface, Jack::JackClientSocket, Jack::JackWinAsyncNamedPipeClient, Jack::JackWinNamedPipe, and Jack::JackWinNamedPipeClient.
Referenced by Jack::JackActivateRequest::Write(), Jack::JackClientCheckRequest::Write(), Jack::JackClientCheckResult::Write(), Jack::JackClientCloseRequest::Write(), Jack::JackClientHasSessionCallbackRequest::Write(), Jack::JackClientNameResult::Write(), Jack::JackClientNotification::Write(), Jack::JackClientNotificationRequest::Write(), Jack::JackClientOpenRequest::Write(), Jack::JackClientOpenResult::Write(), Jack::JackDeactivateRequest::Write(), Jack::JackGetClientNameRequest::Write(), Jack::JackGetInternalClientNameRequest::Write(), Jack::JackGetInternalClientNameResult::Write(), Jack::JackGetUUIDRequest::Write(), Jack::JackInternalClientHandleRequest::Write(), Jack::JackInternalClientHandleResult::Write(), Jack::JackInternalClientLoadRequest::Write(), Jack::JackInternalClientLoadResult::Write(), Jack::JackInternalClientUnloadRequest::Write(), Jack::JackInternalClientUnloadResult::Write(), Jack::JackPortConnectNameRequest::Write(), Jack::JackPortConnectRequest::Write(), Jack::JackPortDisconnectNameRequest::Write(), Jack::JackPortDisconnectRequest::Write(), Jack::JackPortRegisterRequest::Write(), Jack::JackPortRegisterResult::Write(), Jack::JackPortRenameRequest::Write(), Jack::JackPortUnRegisterRequest::Write(), Jack::JackPropertyChangeNotifyRequest::Write(), Jack::JackReleaseTimebaseRequest::Write(), Jack::JackRequest::Write(), Jack::JackReserveNameRequest::Write(), Jack::JackResult::Write(), Jack::JackSessionNotifyRequest::Write(), Jack::JackSessionNotifyResult::Write(), Jack::JackSessionReplyRequest::Write(), Jack::JackSetBufferSizeRequest::Write(), Jack::JackSetFreeWheelRequest::Write(), Jack::JackSetTimebaseCallbackRequest::Write(), and Jack::JackUUIDResult::Write().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackChannel.h