LMMS: Jack::JackShmReadWritePtr1< T > Class Template Reference
Jack::JackShmReadWritePtr1< T > Class Template Reference
Pointer on shared memory segment in the client side: destroy the segment (used client control).
#include <JackShmMem.h>
Public Member Functions
JackShmReadWritePtr1 ()
JackShmReadWritePtr1 (int index, const char *server_name)
~JackShmReadWritePtr1 ()
T * GetShmAddress ()
int GetShmIndex ()
operator T* () const
T * operator-> () const
JackShmReadWritePtr1 & operator= (int index)
void SetShmIndex (int index, const char *server_name)
Private Member Functions
void Init (int index, const char *server_name=JACK_DEFAULT_SERVER_NAME)
Private Attributes
jack_shm_info_t fInfo
bool fInitDone
Detailed Description
template<class T>
class Jack::JackShmReadWritePtr1< T >
Pointer on shared memory segment in the client side: destroy the segment (used client control).
Definition at line 198 of file JackShmMem.h.
Constructor & Destructor Documentation
JackShmReadWritePtr1() [1/2]
template<class T> Jack::JackShmReadWritePtr1< T >::JackShmReadWritePtr1 () inline
Definition at line 230 of file JackShmMem.h.
References fInfo, and fInitDone.
Referenced by operator=().
JackShmReadWritePtr1() [2/2]
template<class T> Jack::JackShmReadWritePtr1< T >::JackShmReadWritePtr1 (int index, const char * server_name) inline
Definition at line 237 of file JackShmMem.h.
References Init(), and server_name.
~JackShmReadWritePtr1()
template<class T> Jack::JackShmReadWritePtr1< T >::~JackShmReadWritePtr1 () inline
Definition at line 242 of file JackShmMem.h.
References fInfo, fInitDone, GetShmAddress(), jack_error, jack_log(), and jack_release_lib_shm().
Member Function Documentation
GetShmAddress()
template<class T> T * Jack::JackShmReadWritePtr1< T >::GetShmAddress () inline
Definition at line 282 of file JackShmMem.h.
References fInfo.
Referenced by ~JackShmReadWritePtr1(), and Init().
GetShmIndex()
template<class T> int Jack::JackShmReadWritePtr1< T >::GetShmIndex () inline
Definition at line 277 of file JackShmMem.h.
References fInfo.
Init()
template<class T> void Jack::JackShmReadWritePtr1< T >::Init (int index, const char * server_name = JACK_DEFAULT_SERVER_NAME) inline private
Definition at line 206 of file JackShmMem.h.
References fInfo, fInitDone, GetShmAddress(), jack_attach_lib_shm(), JACK_DEFAULT_SERVER_NAME, jack_destroy_shm, jack_initialize_shm(), jack_log(), and server_name.
Referenced by JackShmReadWritePtr1(), operator=(), and SetShmIndex().
operator T*()
template<class T> Jack::JackShmReadWritePtr1< T >::operator T* () const inline
Definition at line 261 of file JackShmMem.h.
operator->()
template<class T> T * Jack::JackShmReadWritePtr1< T >::operator-> () const inline
Definition at line 256 of file JackShmMem.h.
References fInfo.
operator=()
template<class T> JackShmReadWritePtr1 & Jack::JackShmReadWritePtr1< T >::operator= (int index) inline
Definition at line 266 of file JackShmMem.h.
References JackShmReadWritePtr1(), and Init().
SetShmIndex()
template<class T> void Jack::JackShmReadWritePtr1< T >::SetShmIndex (int index, const char * server_name) inline
Definition at line 272 of file JackShmMem.h.
References Init(), and server_name.
Member Data Documentation
fInfo
template<class T> jack_shm_info_t Jack::JackShmReadWritePtr1< T >::fInfo private
Definition at line 203 of file JackShmMem.h.
Referenced by JackShmReadWritePtr1(), ~JackShmReadWritePtr1(), GetShmAddress(), GetShmIndex(), Init(), and operator->().
fInitDone
template<class T> bool Jack::JackShmReadWritePtr1< T >::fInitDone private
Definition at line 204 of file JackShmMem.h.
Referenced by JackShmReadWritePtr1(), ~JackShmReadWritePtr1(), and Init().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackShmMem.h