LMMS: Jack::JackNetMaster Class Reference
Jack::JackNetMaster Class Reference
#include <JackNetManager.h>
Public Member Functions
JackNetMaster (JackNetSocket &socket, session_params_t &params, const char *multicast_ip)
~JackNetMaster ()
bool IsSlaveReadyToRoll ()
Public Member Functions inherited from Jack::JackNetMasterInterface
JackNetMasterInterface ()
JackNetMasterInterface (session_params_t &params, JackNetSocket &socket, const char *multicast_ip)
virtual ~JackNetMasterInterface ()
Public Member Functions inherited from Jack::JackNetInterface
JackNetInterface ()
JackNetInterface (const char *multicast_ip, int port)
JackNetInterface (session_params_t &params, JackNetSocket &socket, const char *multicast_ip)
virtual ~JackNetInterface ()
Private Member Functions
int AllocPorts ()
void ConnectCallback (jack_port_id_t a, jack_port_id_t b, int connect)
void ConnectPorts ()
void DecodeTransportData ()
void EncodeTransportData ()
void FreePorts ()
bool Init (bool auto_connect)
void LoadConnections (const connections_list_t &connections)
int Process ()
void SaveConnections (connections_list_t &connections)
void TimebaseCallback (jack_position_t *pos)
Static Private Member Functions
static void LatencyCallback (jack_latency_callback_mode_t mode, void *arg)
static int SetBufferSize (jack_nframes_t nframes, void *arg)
static void SetConnectCallback (jack_port_id_t a, jack_port_id_t b, int connect, void *arg)
static int SetProcess (jack_nframes_t nframes, void *arg)
static int SetSampleRate (jack_nframes_t nframes, void *arg)
static void SetTimebaseCallback (jack_transport_state_t state, jack_nframes_t nframes, jack_position_t *pos, int new_pos, void *arg)
Private Attributes
jack_port_t ** fAudioCapturePorts
jack_port_t ** fAudioPlaybackPorts
jack_client_t * fClient
int fLastTransportState
jack_port_t ** fMidiCapturePorts
jack_port_t ** fMidiPlaybackPorts
const char * fName
Friends
class JackNetMasterManager
Additional Inherited Members
Protected Member Functions inherited from Jack::JackNetMasterInterface
int DataRecv ()
int DataSend ()
void DecodeSyncPacket (int &frames)
void EncodeSyncPacket (int frames=-1)
void Exit ()
void FatalRecvError ()
void FatalSendError ()
bool Init ()
int Recv (size_t size, int flags)
int Send (size_t size, int flags)
bool SetParams ()
int SyncRecv ()
int SyncSend ()
Protected Member Functions inherited from Jack::JackNetInterface
NetAudioBuffer * AudioBufferFactory (int nports, char *buffer)
int AudioRecv (packet_header_t *rx_head, NetAudioBuffer *buffer)
int AudioSend (NetAudioBuffer *buffer, int audio_channels)
int FinishRecv (NetAudioBuffer *buffer)
void FreeNetworkBuffers ()
void Initialize ()
int MidiRecv (packet_header_t *rx_head, NetMidiBuffer *buffer, uint &recvd_midi_pckt)
int MidiSend (NetMidiBuffer *buffer, int midi_channnels, int audio_channels)
int SetNetBufferSize ()
void SetPacketTimeOut (int time_out)
void SetRcvTimeOut ()
Protected Attributes inherited from Jack::JackNetMasterInterface
int fCurrentCycleOffset
int fMaxCycleOffset
bool fRunning
bool fSynched
Protected Attributes inherited from Jack::JackNetInterface
char fMulticastIP [32]
NetAudioBuffer * fNetAudioCaptureBuffer
NetAudioBuffer * fNetAudioPlaybackBuffer
NetMidiBuffer * fNetMidiCaptureBuffer
NetMidiBuffer * fNetMidiPlaybackBuffer
int fPacketTimeOut
session_params_t fParams
net_transport_data_t fReturnTransportData
char * fRxBuffer
char * fRxData
packet_header_t fRxHeader
net_transport_data_t fSendTransportData
bool fSetTimeOut
JackNetSocket fSocket
char * fTxBuffer
char * fTxData
packet_header_t fTxHeader
Detailed Description
Definition at line 38 of file JackNetManager.h.
Constructor & Destructor Documentation
JackNetMaster()
Jack::JackNetMaster::JackNetMaster (JackNetSocket & socket, session_params_t & params, const char * multicast_ip)
Definition at line 31 of file JackNetManager.cpp.
References Jack::JackNetMasterInterface::JackNetMasterInterface(), fAudioCapturePorts, fAudioPlaybackPorts, fClient, fLastTransportState, fMidiCapturePorts, fMidiPlaybackPorts, fName, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fReturnTransportData, Jack::JackNetInterface::fSendTransportData, and jack_log().
Referenced by LatencyCallback(), SetBufferSize(), SetConnectCallback(), SetProcess(), SetSampleRate(), and SetTimebaseCallback().
~JackNetMaster()
Jack::JackNetMaster::~JackNetMaster ()
Definition at line 91 of file JackNetManager.cpp.
References fAudioCapturePorts, fAudioPlaybackPorts, fClient, fMidiCapturePorts, fMidiPlaybackPorts, Jack::JackNetInterface::fParams, FreePorts(), jack_client_close(), jack_deactivate(), and jack_log().
Member Function Documentation
AllocPorts()
int Jack::JackNetMaster::AllocPorts () private
Definition at line 181 of file JackNetManager.cpp.
References fAudioCapturePorts, fAudioPlaybackPorts, fClient, fMidiCapturePorts, fMidiPlaybackPorts, Jack::JackNetInterface::fParams, i, JACK_DEFAULT_AUDIO_TYPE, JACK_DEFAULT_MIDI_TYPE, jack_log(), jack_port_register(), JackPortIsInput, JackPortIsOutput, and JackPortIsTerminal.
Referenced by Init().
ConnectCallback()
void Jack::JackNetMaster::ConnectCallback (jack_port_id_t a, jack_port_id_t b, int connect) private
Definition at line 443 of file JackNetManager.cpp.
References fClient, jack_connect(), jack_info(), jack_port_by_id(), and jack_port_name().
Referenced by SetConnectCallback().
ConnectPorts()
void Jack::JackNetMaster::ConnectPorts () private
Definition at line 219 of file JackNetManager.cpp.
References fAudioCapturePorts, fAudioPlaybackPorts, fClient, Jack::JackNetInterface::fParams, i, jack_connect(), JACK_DEFAULT_AUDIO_TYPE, jack_free(), jack_get_ports(), jack_port_name(), JackPortIsInput, JackPortIsOutput, and JackPortIsPhysical.
Referenced by Init().
DecodeTransportData()
void Jack::JackNetMaster::DecodeTransportData () private virtual
Implements Jack::JackNetInterface.
Definition at line 283 of file JackNetManager.cpp.
References Jack::CONDITIONAL_TIMEBASEMASTER, fClient, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fReturnTransportData, jack_error, jack_info(), jack_release_timebase(), jack_set_timebase_callback(), jack_transport_query(), jack_transport_reposition(), jack_transport_start(), jack_transport_stop(), JackTransportNetStarting, JackTransportRolling, JackTransportStarting, JackTransportStopped, Jack::NO_CHANGE, Jack::RELEASE_TIMEBASEMASTER, SetTimebaseCallback(), and Jack::TIMEBASEMASTER.
EncodeTransportData()
void Jack::JackNetMaster::EncodeTransportData () private virtual
Implements Jack::JackNetInterface.
Definition at line 266 of file JackNetManager.cpp.
References fClient, fLastTransportState, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fReturnTransportData, Jack::JackNetInterface::fSendTransportData, Jack::GetTransportState(), jack_info(), jack_transport_query(), and Jack::NO_CHANGE.
FreePorts()
void Jack::JackNetMaster::FreePorts () private
Definition at line 238 of file JackNetManager.cpp.
References fAudioCapturePorts, fAudioPlaybackPorts, fClient, fMidiCapturePorts, fMidiPlaybackPorts, Jack::JackNetInterface::fParams, jack_log(), and jack_port_unregister().
Referenced by ~JackNetMaster(), and Init().
Init()
bool Jack::JackNetMaster::Init (bool auto_connect) private
Definition at line 110 of file JackNetManager.cpp.
References AllocPorts(), ConnectPorts(), fClient, fName, FreePorts(), Jack::JackNetMasterInterface::fRunning, Jack::JackNetMasterInterface::Init(), jack_activate(), jack_client_close(), jack_client_open(), jack_error, jack_info(), jack_set_buffer_size_callback(), jack_set_latency_callback(), jack_set_process_callback(), jack_set_sample_rate_callback(), JackNullOption, LatencyCallback(), SetBufferSize(), Jack::JackNetMasterInterface::SetParams(), SetProcess(), and SetSampleRate().
Referenced by Jack::JackNetMasterManager::InitMaster().
IsSlaveReadyToRoll()
bool Jack::JackNetMaster::IsSlaveReadyToRoll ()
Definition at line 368 of file JackNetManager.cpp.
References Jack::JackNetInterface::fReturnTransportData, and JackTransportNetStarting.
LatencyCallback()
void Jack::JackNetMaster::LatencyCallback (jack_latency_callback_mode_t mode, void * arg) static private
Definition at line 393 of file JackNetManager.cpp.
References JackNetMaster(), fAudioCapturePorts, fAudioPlaybackPorts, fClient, fMidiCapturePorts, fMidiPlaybackPorts, Jack::_session_params::fNetworkLatency, Jack::JackNetInterface::fParams, Jack::_session_params::fReturnAudioChannels, Jack::_session_params::fReturnMidiChannels, Jack::_session_params::fSendAudioChannels, Jack::_session_params::fSendMidiChannels, Jack::_session_params::fSlaveSyncMode, i, jack_get_buffer_size(), jack_port_set_latency_range(), JackCaptureLatency, JackPlaybackLatency, _jack_latency_range::max, and _jack_latency_range::min.
Referenced by Init().
LoadConnections()
void Jack::JackNetMaster::LoadConnections (const connections_list_t & connections) private
Definition at line 624 of file JackNetManager.cpp.
References fClient, and jack_connect().
Referenced by Jack::JackNetMasterManager::InitMaster().
Process()
int Jack::JackNetMaster::Process () private
Definition at line 451 of file JackNetManager.cpp.
References ALL_CLIENTS, DATA_PACKET_ERROR, Jack::JackNetMasterInterface::DataRecv(), Jack::JackNetMasterInterface::DataSend(), Jack::JackNetMasterInterface::DecodeSyncPacket(), Jack::JackNetMasterInterface::EncodeSyncPacket(), fAudioCapturePorts, fAudioPlaybackPorts, Jack::JackServerGlobals::fInstance, fMidiCapturePorts, fMidiPlaybackPorts, Jack::JackNetInterface::fNetAudioCaptureBuffer, Jack::JackNetInterface::fNetAudioPlaybackBuffer, Jack::JackNetInterface::fNetMidiCaptureBuffer, Jack::JackNetInterface::fNetMidiPlaybackBuffer, Jack::JackNetInterface::fParams, Jack::JackNetMasterInterface::fRunning, GetMicroSeconds(), jack_port_connected(), jack_port_get_buffer(), NET_SYNCHING, SOCKET_ERROR, SYNC_PACKET_ERROR, Jack::JackNetMasterInterface::SyncRecv(), and Jack::JackNetMasterInterface::SyncSend().
Referenced by SetProcess().
SaveConnections()
void Jack::JackNetMaster::SaveConnections (connections_list_t & connections) private
Definition at line 575 of file JackNetManager.cpp.
References fAudioCapturePorts, fAudioPlaybackPorts, fClient, fMidiCapturePorts, fMidiPlaybackPorts, Jack::JackNetInterface::fParams, i, jack_free(), jack_log(), jack_port_get_all_connections(), and jack_port_name().
SetBufferSize()
int Jack::JackNetMaster::SetBufferSize (jack_nframes_t nframes, void * arg) static private
Definition at line 373 of file JackNetManager.cpp.
References JackNetMaster(), Jack::JackNetMasterInterface::Exit(), Jack::JackNetInterface::fParams, Jack::_session_params::fPeriodSize, and jack_error.
Referenced by Init().
SetConnectCallback()
void Jack::JackNetMaster::SetConnectCallback (jack_port_id_t a, jack_port_id_t b, int connect, void * arg) static private
Definition at line 438 of file JackNetManager.cpp.
References JackNetMaster(), and ConnectCallback().
SetProcess()
int Jack::JackNetMaster::SetProcess (jack_nframes_t nframes, void * arg) static private
Definition at line 429 of file JackNetManager.cpp.
References JackNetMaster(), and Process().
Referenced by Init().
SetSampleRate()
int Jack::JackNetMaster::SetSampleRate (jack_nframes_t nframes, void * arg) static private
Definition at line 383 of file JackNetManager.cpp.
References JackNetMaster(), Jack::JackNetMasterInterface::Exit(), Jack::JackNetInterface::fParams, Jack::_session_params::fSampleRate, and jack_error.
Referenced by Init().
SetTimebaseCallback()
void Jack::JackNetMaster::SetTimebaseCallback (jack_transport_state_t state, jack_nframes_t nframes, jack_position_t * pos, int new_pos, void * arg) static private
Definition at line 349 of file JackNetManager.cpp.
References JackNetMaster(), pos, and TimebaseCallback().
Referenced by DecodeTransportData().
TimebaseCallback()
void Jack::JackNetMaster::TimebaseCallback (jack_position_t * pos) private
Definition at line 354 of file JackNetManager.cpp.
References Jack::JackNetInterface::fReturnTransportData, and pos.
Referenced by SetTimebaseCallback().
Friends And Related Symbol Documentation
JackNetMasterManager
friend class JackNetMasterManager friend
Definition at line 40 of file JackNetManager.h.
References JackNetMasterManager, and pos.
Referenced by JackNetMasterManager.
Member Data Documentation
fAudioCapturePorts
jack_port_t** Jack::JackNetMaster::fAudioCapturePorts private
Definition at line 56 of file JackNetManager.h.
Referenced by JackNetMaster(), ~JackNetMaster(), AllocPorts(), ConnectPorts(), FreePorts(), LatencyCallback(), Process(), and SaveConnections().
fAudioPlaybackPorts
jack_port_t** Jack::JackNetMaster::fAudioPlaybackPorts private
Definition at line 57 of file JackNetManager.h.
Referenced by JackNetMaster(), ~JackNetMaster(), AllocPorts(), ConnectPorts(), FreePorts(), LatencyCallback(), Process(), and SaveConnections().
fClient
jack_client_t* Jack::JackNetMaster::fClient private
Definition at line 52 of file JackNetManager.h.
Referenced by JackNetMaster(), ~JackNetMaster(), AllocPorts(), ConnectCallback(), ConnectPorts(), DecodeTransportData(), EncodeTransportData(), FreePorts(), Init(), LatencyCallback(), LoadConnections(), and SaveConnections().
fLastTransportState
int Jack::JackNetMaster::fLastTransportState private
Definition at line 62 of file JackNetManager.h.
Referenced by JackNetMaster(), and EncodeTransportData().
fMidiCapturePorts
jack_port_t** Jack::JackNetMaster::fMidiCapturePorts private
Definition at line 58 of file JackNetManager.h.
Referenced by JackNetMaster(), ~JackNetMaster(), AllocPorts(), FreePorts(), LatencyCallback(), Process(), and SaveConnections().
fMidiPlaybackPorts
jack_port_t** Jack::JackNetMaster::fMidiPlaybackPorts private
Definition at line 59 of file JackNetManager.h.
Referenced by JackNetMaster(), ~JackNetMaster(), AllocPorts(), FreePorts(), LatencyCallback(), Process(), and SaveConnections().
fName
const char* Jack::JackNetMaster::fName private
Definition at line 53 of file JackNetManager.h.
Referenced by JackNetMaster(), and Init().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackNetManager.h
src/3rdparty/jack2/common/JackNetManager.cpp