LMMS: lmms::gui::LadspaControlView Class Reference
lmms::gui::LadspaControlView Class Reference
#include <LadspaControlView.h>
Public Member Functions
LadspaControlView (QWidget *_parent, LadspaControl *_ctl)
~LadspaControlView () override=default
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Private Attributes
LadspaControl * m_ctl
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Detailed Description
Definition at line 41 of file LadspaControlView.h.
Constructor & Destructor Documentation
LadspaControlView()
lmms::gui::LadspaControlView::LadspaControlView (QWidget * _parent, LadspaControl * _ctl)
Definition at line 39 of file LadspaControlView.cpp.
References lmms::gui::ModelView::ModelView(), lmms::gui::Bright26, lmms::Enum, lmms::Floating, lmms::gui::LedCheckBox::Green, lmms::Integer, m_ctl, lmms::gui::FloatModelEditorBase::setHintText(), lmms::gui::AutomatableModelView::setModel(), lmms::Time, lmms::Toggled, and lmms::gui::Knob::WidgetFont.
~LadspaControlView()
lmms::gui::LadspaControlView::~LadspaControlView () override default
Member Data Documentation
m_ctl
LadspaControl* lmms::gui::LadspaControlView::m_ctl private
Definition at line 49 of file LadspaControlView.h.
Referenced by LadspaControlView().
The documentation for this class was generated from the following files:
include/LadspaControlView.h
src/gui/LadspaControlView.cpp