LMMS: hiir::Upsampler2x4Sse< NC > Class Template Reference
hiir::Upsampler2x4Sse< NC > Class Template Reference
#include <Upsampler2x4Sse.h>
Public Types
typedef float DataType
Public Member Functions
Upsampler2x4Sse () noexcept
Upsampler2x4Sse (const Upsampler2x4Sse< NC > &other)=default
Upsampler2x4Sse (Upsampler2x4Sse< NC > &&other)=default
~Upsampler2x4Sse ()=default
void clear_buffers () noexcept
Upsampler2x4Sse< NC > & operator= (const Upsampler2x4Sse< NC > &other)=default
Upsampler2x4Sse< NC > & operator= (Upsampler2x4Sse< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (__m128 &out_0, __m128 &out_1, __m128 input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 4
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataSse, NBR_COEFS+2 > Filter
Private Member Functions
bool operator!= (const Upsampler2x4Sse< NC > &other) const =delete
bool operator== (const Upsampler2x4Sse< NC > &other) const =delete
Private Attributes
Filter _filter
Detailed Description
template<int NC>
class hiir::Upsampler2x4Sse< NC >
Definition at line 53 of file Upsampler2x4Sse.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Upsampler2x4Sse< NC >::DataType
Definition at line 62 of file Upsampler2x4Sse.h.
Filter
template<int NC> typedef std::array<StageDataSse, NBR_COEFS + 2> hiir::Upsampler2x4Sse< NC >::Filter private
Definition at line 95 of file Upsampler2x4Sse.h.
Constructor & Destructor Documentation
Upsampler2x4Sse() [1/3]
template<int NC> hiir::Upsampler2x4Sse< NC >::Upsampler2x4Sse () noexcept
Definition at line 55 of file Upsampler2x4Sse.hpp.
References _filter, clear_buffers(), i, and NBR_COEFS.
Referenced by Upsampler2x4Sse(), Upsampler2x4Sse(), ~Upsampler2x4Sse(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2x4Sse() [2/3]
template<int NC> hiir::Upsampler2x4Sse< NC >::Upsampler2x4Sse (const Upsampler2x4Sse< NC > & other) default
References Upsampler2x4Sse().
Upsampler2x4Sse() [3/3]
template<int NC> hiir::Upsampler2x4Sse< NC >::Upsampler2x4Sse (Upsampler2x4Sse< NC > && other) default
References Upsampler2x4Sse().
~Upsampler2x4Sse()
template<int NC> hiir::Upsampler2x4Sse< NC >::~Upsampler2x4Sse () default
References Upsampler2x4Sse().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2x4Sse< NC >::clear_buffers () noexcept
Definition at line 179 of file Upsampler2x4Sse.hpp.
References _filter, i, and NBR_COEFS.
Referenced by Upsampler2x4Sse(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2x4Sse< NC >::operator!= (const Upsampler2x4Sse< NC > & other) const private delete
References Upsampler2x4Sse().
operator=() [1/2]
template<int NC> Upsampler2x4Sse< NC > & hiir::Upsampler2x4Sse< NC >::operator= (const Upsampler2x4Sse< NC > & other) default
References Upsampler2x4Sse().
operator=() [2/2]
template<int NC> Upsampler2x4Sse< NC > & hiir::Upsampler2x4Sse< NC >::operator= (Upsampler2x4Sse< NC > && other) default
References Upsampler2x4Sse(), clear_buffers(), hiir_FORCEINLINE, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2x4Sse< NC >::operator== (const Upsampler2x4Sse< NC > & other) const private delete
References Upsampler2x4Sse().
process_block()
template<int NC> void hiir::Upsampler2x4Sse< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 144 of file Upsampler2x4Sse.hpp.
References _nbr_chn, pos, and process_sample().
Referenced by operator=().
process_sample()
template<int NC> void hiir::Upsampler2x4Sse< NC >::process_sample (__m128 & out_0, __m128 & out_1, __m128 input) noexcept
Definition at line 110 of file Upsampler2x4Sse.hpp.
References _filter, NBR_COEFS, and hiir::StageProc4Sse< REMAINING >::process_sample_pos().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::Upsampler2x4Sse< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 83 of file Upsampler2x4Sse.hpp.
References _filter, i, and NBR_COEFS.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Upsampler2x4Sse< NC >::_delay = 0 static constexpr
Definition at line 65 of file Upsampler2x4Sse.h.
_filter
template<int NC> Filter hiir::Upsampler2x4Sse< NC >::_filter private
Definition at line 97 of file Upsampler2x4Sse.h.
Referenced by Upsampler2x4Sse(), clear_buffers(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Upsampler2x4Sse< NC >::_nbr_chn = 4 static constexpr
Definition at line 63 of file Upsampler2x4Sse.h.
Referenced by process_block().
NBR_COEFS
template<int NC> int hiir::Upsampler2x4Sse< NC >::NBR_COEFS = NC static constexpr
Definition at line 64 of file Upsampler2x4Sse.h.
Referenced by Upsampler2x4Sse(), clear_buffers(), operator=(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2x4Sse.h
src/3rdparty/hiir/hiir/Upsampler2x4Sse.hpp