LMMS: src/core/main.cpp File Reference
main.cpp File Reference
#include "lmmsconfig.h"
#include "lmmsversion.h"
#include "versioninfo.h"
#include "denormals.h"
#include <QDebug>
#include <QFileInfo>
#include <QLocale>
#include <QTimer>
#include <QTranslator>
#include <QApplication>
#include <QMessageBox>
#include <QPushButton>
#include <QTextStream>
#include <csignal>
#include "MainApplication.h"
#include "ConfigManager.h"
#include "DataFile.h"
#include "NotePlayHandle.h"
#include "embed.h"
#include "Engine.h"
#include "GuiApplication.h"
#include "ImportFilter.h"
#include "MainWindow.h"
#include "MixHelpers.h"
#include "OutputSettings.h"
#include "ProjectRenderer.h"
#include "RenderManager.h"
#include "Song.h"
Functions
static QString baseName (const QString &file)
void fileCheck (QString &file)
void loadTranslation (const QString &tname, const QString &dir=lmms::ConfigManager::inst() ->localeDir())
int main (int argc, char **argv)
int noInputFileError ()
void printHelp ()
void printVersion (char *executableName)
int usageError (const QString &message)
Function Documentation
baseName()
QString baseName (const QString & file) inline static
Definition at line 102 of file main.cpp.
References file.
Referenced by lmms::gui::MicrotunerConfig::loadKeymapFromFile(), and main().
fileCheck()
void fileCheck (QString & file)
Definition at line 216 of file main.cpp.
References file.
Referenced by main().
loadTranslation()
void loadTranslation (const QString & tname, const QString & dir = lmms::ConfigManager::inst()->localeDir()) inline
Definition at line 126 of file main.cpp.
References lmms::ConfigManager::inst().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 247 of file main.cpp.
References lmms::Engine::audioEngine(), baseName(), lmms::OutputSettings::Depth16Bit, lmms::OutputSettings::Depth32Bit, lmms::Engine::destroy(), lmms::disable_denormals(), fileCheck(), lmms::ProjectRenderer::Flac, lmms::NotePlayHandleManager::free(), lmms::ProjectRenderer::getFileExtensionFromFormat(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::Engine::getSong(), i, lmms::ImportFilter::import(), lmms::Engine::init(), lmms::NotePlayHandleManager::init(), lmms::ConfigManager::inst(), lmms::OutputSettings::JointStereo, loadTranslation(), lmms::OutputSettings::Mono, lmms::ProjectRenderer::MP3, noInputFileError(), lmms::ProjectRenderer::Ogg, pos, printHelp(), printVersion(), lmms::gui::MainWindow::Recover, lmms::OutputSettings::setBitDepth(), lmms::OutputSettings::setBitrate(), lmms::MixHelpers::setNaNHandler(), lmms::OutputSettings::setSampleRate(), lmms::OutputSettings::setStereoMode(), lmms::gui::GuiApplication::sigintHandler(), sr, lmms::OutputSettings::Stereo, ts, usageError(), lmms::ProjectRenderer::Wave, lmms::DataFile::write(), and lmms::DataFile::writeFile().
noInputFileError()
int noInputFileError ()
Definition at line 241 of file main.cpp.
References usageError().
Referenced by main().
printHelp()
void printHelp ()
Definition at line 158 of file main.cpp.
Referenced by main().
printVersion()
void printVersion (char * executableName)
Definition at line 141 of file main.cpp.
References LMMS_BUILDCONF_COMPILER_VERSION, LMMS_BUILDCONF_MACHINE, and LMMS_BUILDCONF_PLATFORM.
Referenced by main().
usageError()
int usageError (const QString & message)
Definition at line 234 of file main.cpp.
Referenced by main(), and noInputFileError().