LMMS: src/3rdparty/jack2/common/JackError.cpp File Reference
JackError.cpp File Reference
#include <stdarg.h>
#include <stdio.h>
#include "JackError.h"
#include "JackGlobals.h"
#include "JackMessageBuffer.h"
Functions
static bool change_thread_log_function (jack_log_function_t log_function)
SERVER_EXPORT void default_jack_error_callback (const char *desc)
SERVER_EXPORT void default_jack_info_callback (const char *desc)
SERVER_EXPORT void jack_error (const char *fmt,...)
Call this function to log an error message.
static void jack_format_and_log (int level, const char *prefix, const char *fmt, va_list ap)
SERVER_EXPORT void jack_info (const char *fmt,...)
Call this function to log an information message.
SERVER_EXPORT void jack_log (const char *fmt,...)
Call this function to log an information message but only when verbose mode is enabled.
void jack_log_function (int level, const char *message)
SERVER_EXPORT int set_threaded_log_function ()
SERVER_EXPORT void silent_jack_error_callback (const char *desc)
SERVER_EXPORT void silent_jack_info_callback (const char *desc)
Variables
LIB_EXPORT void(* jack_error_callback)(const char *desc) = &default_jack_error_callback
Display JACK error message.
LIB_EXPORT void(* jack_info_callback)(const char *desc) = &default_jack_info_callback
Display JACK info message.
Function Documentation
change_thread_log_function()
bool change_thread_log_function (jack_log_function_t log_function) static
Definition at line 30 of file JackError.cpp.
References Jack::JackGlobals::fKeyLogFunction, jack_tls_get(), and jack_tls_set().
Referenced by set_threaded_log_function().
default_jack_error_callback()
SERVER_EXPORT void default_jack_error_callback (const char * desc)
Definition at line 118 of file JackError.cpp.
References SERVER_EXPORT.
default_jack_info_callback()
SERVER_EXPORT void default_jack_info_callback (const char * desc)
Definition at line 124 of file JackError.cpp.
References SERVER_EXPORT.
jack_format_and_log()
void jack_format_and_log (int level, const char * prefix, const char * fmt, va_list ap) static
Definition at line 60 of file JackError.cpp.
References Jack::JackGlobals::fKeyLogFunction, jack_log_function(), and jack_tls_get().
Referenced by jack_error(), jack_info(), and jack_log().
jack_log_function()
void jack_log_function (int level, const char * message)
Definition at line 41 of file JackError.cpp.
References jack_error_callback, jack_info_callback, LOG_LEVEL_ERROR, and LOG_LEVEL_INFO.
set_threaded_log_function()
SERVER_EXPORT int set_threaded_log_function ()
Definition at line 36 of file JackError.cpp.
References change_thread_log_function(), Jack::JackMessageBufferAdd(), and SERVER_EXPORT.
silent_jack_error_callback()
SERVER_EXPORT void silent_jack_error_callback (const char * desc)
Definition at line 130 of file JackError.cpp.
References SERVER_EXPORT.
silent_jack_info_callback()
SERVER_EXPORT void silent_jack_info_callback (const char * desc)
Definition at line 133 of file JackError.cpp.
References SERVER_EXPORT.