var dir_78fb9b2d77ed25c2db82979adaed87bd =
[
    [ "Alienwah.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Alienwah_8cpp.html", null ],
    [ "Alienwah.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Alienwah_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Alienwah_8h" ],
    [ "Chorus.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Chorus_8cpp.html", null ],
    [ "Chorus.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Chorus_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Chorus_8h" ],
    [ "Distorsion.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Distorsion_8cpp.html", null ],
    [ "Distorsion.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Distorsion_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Distorsion_8h" ],
    [ "DynamicFilter.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2DynamicFilter_8cpp.html", null ],
    [ "DynamicFilter.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2DynamicFilter_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2DynamicFilter_8h" ],
    [ "Echo.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Echo_8cpp.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Echo_8cpp" ],
    [ "Echo.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Echo_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Echo_8h" ],
    [ "Effect.cpp", "plugins_2ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Effect_8cpp.html", null ],
    [ "Effect.h", "plugins_2ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Effect_8h.html", "plugins_2ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Effect_8h" ],
    [ "EffectLFO.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EffectLFO_8cpp.html", null ],
    [ "EffectLFO.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EffectLFO_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EffectLFO_8h" ],
    [ "EffectMgr.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EffectMgr_8cpp.html", null ],
    [ "EffectMgr.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EffectMgr_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EffectMgr_8h" ],
    [ "EQ.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EQ_8cpp.html", null ],
    [ "EQ.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EQ_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2EQ_8h" ],
    [ "Phaser.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Phaser_8cpp.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Phaser_8cpp" ],
    [ "Phaser.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Phaser_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Phaser_8h" ],
    [ "Reverb.cpp", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Reverb_8cpp.html", null ],
    [ "Reverb.h", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Reverb_8h.html", "ZynAddSubFx_2zynaddsubfx_2src_2Effects_2Reverb_8h" ]
];