var group__lv2 =
[
    [ "State", "group__state.html", "group__state" ],
    [ "Atom", "group__atom.html", "group__atom" ],
    [ "Buffer Size", "group__buf-size.html", "group__buf-size" ],
    [ "Attributes", "group__attributes.html", "group__attributes" ],
    [ "LV2 Core", "group__lv2core.html", "group__lv2core" ],
    [ "Data Access", "group__data-access.html", "group__data-access" ],
    [ "Dynamic Manifest", "group__dynmanifest.html", "group__dynmanifest" ],
    [ "Event", "group__event.html", "group__event" ],
    [ "Instance Access", "group__instance-access.html", "group__instance-access" ],
    [ "Log", "group__log.html", "group__log" ],
    [ "MIDI", "group__midi.html", "group__midi" ],
    [ "Morph", "group__morph.html", "group__morph" ],
    [ "Options", "group__options.html", "group__options" ],
    [ "Parameters", "group__parameters.html", "group__parameters" ],
    [ "Patch", "group__patch.html", "group__patch" ],
    [ "Port Groups", "group__port-groups.html", "group__port-groups" ],
    [ "Port Properties", "group__port-props.html", "group__port-props" ],
    [ "Presets", "group__presets.html", "group__presets" ],
    [ "Resize Port", "group__resize-port.html", "group__resize-port" ],
    [ "Time", "group__time.html", "group__time" ],
    [ "User Interfaces", "group__ui.html", "group__ui" ],
    [ "Units", "group__units.html", "group__units" ],
    [ "URI Map", "group__uri-map.html", "group__uri-map" ],
    [ "URID", "group__urid.html", "group__urid" ],
    [ "Worker", "group__worker.html", "group__worker" ]
];