var gui__controls_8h =
[
    [ "calf_plugins::table_container", "structcalf__plugins_1_1table__container.html", "structcalf__plugins_1_1table__container" ],
    [ "calf_plugins::alignment_container", "structcalf__plugins_1_1alignment__container.html", "structcalf__plugins_1_1alignment__container" ],
    [ "calf_plugins::frame_container", "structcalf__plugins_1_1frame__container.html", "structcalf__plugins_1_1frame__container" ],
    [ "calf_plugins::box_container", "structcalf__plugins_1_1box__container.html", "structcalf__plugins_1_1box__container" ],
    [ "calf_plugins::vbox_container", "structcalf__plugins_1_1vbox__container.html", "structcalf__plugins_1_1vbox__container" ],
    [ "calf_plugins::hbox_container", "structcalf__plugins_1_1hbox__container.html", "structcalf__plugins_1_1hbox__container" ],
    [ "calf_plugins::scrolled_container", "structcalf__plugins_1_1scrolled__container.html", "structcalf__plugins_1_1scrolled__container" ],
    [ "calf_plugins::notebook_param_control", "structcalf__plugins_1_1notebook__param__control.html", "structcalf__plugins_1_1notebook__param__control" ],
    [ "calf_plugins::label_param_control", "structcalf__plugins_1_1label__param__control.html", "structcalf__plugins_1_1label__param__control" ],
    [ "calf_plugins::value_param_control", "structcalf__plugins_1_1value__param__control.html", "structcalf__plugins_1_1value__param__control" ],
    [ "calf_plugins::vumeter_param_control", "structcalf__plugins_1_1vumeter__param__control.html", "structcalf__plugins_1_1vumeter__param__control" ],
    [ "calf_plugins::led_param_control", "structcalf__plugins_1_1led__param__control.html", "structcalf__plugins_1_1led__param__control" ],
    [ "calf_plugins::tube_param_control", "structcalf__plugins_1_1tube__param__control.html", "structcalf__plugins_1_1tube__param__control" ],
    [ "calf_plugins::hscale_param_control", "structcalf__plugins_1_1hscale__param__control.html", "structcalf__plugins_1_1hscale__param__control" ],
    [ "calf_plugins::vscale_param_control", "structcalf__plugins_1_1vscale__param__control.html", "structcalf__plugins_1_1vscale__param__control" ],
    [ "calf_plugins::spin_param_control", "structcalf__plugins_1_1spin__param__control.html", "structcalf__plugins_1_1spin__param__control" ],
    [ "calf_plugins::check_param_control", "structcalf__plugins_1_1check__param__control.html", "structcalf__plugins_1_1check__param__control" ],
    [ "calf_plugins::toggle_param_control", "structcalf__plugins_1_1toggle__param__control.html", "structcalf__plugins_1_1toggle__param__control" ],
    [ "calf_plugins::tap_button_param_control", "structcalf__plugins_1_1tap__button__param__control.html", "structcalf__plugins_1_1tap__button__param__control" ],
    [ "calf_plugins::radio_param_control", "structcalf__plugins_1_1radio__param__control.html", "structcalf__plugins_1_1radio__param__control" ],
    [ "calf_plugins::button_param_control", "structcalf__plugins_1_1button__param__control.html", "structcalf__plugins_1_1button__param__control" ],
    [ "calf_plugins::combo_box_param_control", "structcalf__plugins_1_1combo__box__param__control.html", "structcalf__plugins_1_1combo__box__param__control" ],
    [ "calf_plugins::line_graph_param_control", "structcalf__plugins_1_1line__graph__param__control.html", "structcalf__plugins_1_1line__graph__param__control" ],
    [ "calf_plugins::phase_graph_param_control", "structcalf__plugins_1_1phase__graph__param__control.html", "structcalf__plugins_1_1phase__graph__param__control" ],
    [ "calf_plugins::tuner_param_control", "structcalf__plugins_1_1tuner__param__control.html", "structcalf__plugins_1_1tuner__param__control" ],
    [ "calf_plugins::pattern_param_control", "structcalf__plugins_1_1pattern__param__control.html", "structcalf__plugins_1_1pattern__param__control" ],
    [ "calf_plugins::knob_param_control", "structcalf__plugins_1_1knob__param__control.html", "structcalf__plugins_1_1knob__param__control" ],
    [ "calf_plugins::keyboard_param_control", "structcalf__plugins_1_1keyboard__param__control.html", "structcalf__plugins_1_1keyboard__param__control" ],
    [ "calf_plugins::curve_param_control", "structcalf__plugins_1_1curve__param__control.html", "structcalf__plugins_1_1curve__param__control" ],
    [ "calf_plugins::meter_scale_param_control", "structcalf__plugins_1_1meter__scale__param__control.html", "structcalf__plugins_1_1meter__scale__param__control" ],
    [ "calf_plugins::entry_param_control", "structcalf__plugins_1_1entry__param__control.html", "structcalf__plugins_1_1entry__param__control" ],
    [ "calf_plugins::filechooser_param_control", "structcalf__plugins_1_1filechooser__param__control.html", "structcalf__plugins_1_1filechooser__param__control" ],
    [ "calf_plugins::listview_param_control", "structcalf__plugins_1_1listview__param__control.html", "structcalf__plugins_1_1listview__param__control" ]
];