var JackRequest_8h =
[
    [ "Jack::JackRequest", "structJack_1_1JackRequest.html", "structJack_1_1JackRequest" ],
    [ "Jack::JackResult", "structJack_1_1JackResult.html", "structJack_1_1JackResult" ],
    [ "Jack::JackClientCheckRequest", "structJack_1_1JackClientCheckRequest.html", "structJack_1_1JackClientCheckRequest" ],
    [ "Jack::JackClientCheckResult", "structJack_1_1JackClientCheckResult.html", "structJack_1_1JackClientCheckResult" ],
    [ "Jack::JackClientOpenRequest", "structJack_1_1JackClientOpenRequest.html", "structJack_1_1JackClientOpenRequest" ],
    [ "Jack::JackClientOpenResult", "structJack_1_1JackClientOpenResult.html", "structJack_1_1JackClientOpenResult" ],
    [ "Jack::JackClientCloseRequest", "structJack_1_1JackClientCloseRequest.html", "structJack_1_1JackClientCloseRequest" ],
    [ "Jack::JackActivateRequest", "structJack_1_1JackActivateRequest.html", "structJack_1_1JackActivateRequest" ],
    [ "Jack::JackDeactivateRequest", "structJack_1_1JackDeactivateRequest.html", "structJack_1_1JackDeactivateRequest" ],
    [ "Jack::JackPortRegisterRequest", "structJack_1_1JackPortRegisterRequest.html", "structJack_1_1JackPortRegisterRequest" ],
    [ "Jack::JackPortRegisterResult", "structJack_1_1JackPortRegisterResult.html", "structJack_1_1JackPortRegisterResult" ],
    [ "Jack::JackPortUnRegisterRequest", "structJack_1_1JackPortUnRegisterRequest.html", "structJack_1_1JackPortUnRegisterRequest" ],
    [ "Jack::JackPortConnectNameRequest", "structJack_1_1JackPortConnectNameRequest.html", "structJack_1_1JackPortConnectNameRequest" ],
    [ "Jack::JackPortDisconnectNameRequest", "structJack_1_1JackPortDisconnectNameRequest.html", "structJack_1_1JackPortDisconnectNameRequest" ],
    [ "Jack::JackPortConnectRequest", "structJack_1_1JackPortConnectRequest.html", "structJack_1_1JackPortConnectRequest" ],
    [ "Jack::JackPortDisconnectRequest", "structJack_1_1JackPortDisconnectRequest.html", "structJack_1_1JackPortDisconnectRequest" ],
    [ "Jack::JackPortRenameRequest", "structJack_1_1JackPortRenameRequest.html", "structJack_1_1JackPortRenameRequest" ],
    [ "Jack::JackSetBufferSizeRequest", "structJack_1_1JackSetBufferSizeRequest.html", "structJack_1_1JackSetBufferSizeRequest" ],
    [ "Jack::JackSetFreeWheelRequest", "structJack_1_1JackSetFreeWheelRequest.html", "structJack_1_1JackSetFreeWheelRequest" ],
    [ "Jack::JackComputeTotalLatenciesRequest", "structJack_1_1JackComputeTotalLatenciesRequest.html", "structJack_1_1JackComputeTotalLatenciesRequest" ],
    [ "Jack::JackReleaseTimebaseRequest", "structJack_1_1JackReleaseTimebaseRequest.html", "structJack_1_1JackReleaseTimebaseRequest" ],
    [ "Jack::JackSetTimebaseCallbackRequest", "structJack_1_1JackSetTimebaseCallbackRequest.html", "structJack_1_1JackSetTimebaseCallbackRequest" ],
    [ "Jack::JackGetInternalClientNameRequest", "structJack_1_1JackGetInternalClientNameRequest.html", "structJack_1_1JackGetInternalClientNameRequest" ],
    [ "Jack::JackGetInternalClientNameResult", "structJack_1_1JackGetInternalClientNameResult.html", "structJack_1_1JackGetInternalClientNameResult" ],
    [ "Jack::JackInternalClientHandleRequest", "structJack_1_1JackInternalClientHandleRequest.html", "structJack_1_1JackInternalClientHandleRequest" ],
    [ "Jack::JackInternalClientHandleResult", "structJack_1_1JackInternalClientHandleResult.html", "structJack_1_1JackInternalClientHandleResult" ],
    [ "Jack::JackInternalClientLoadRequest", "structJack_1_1JackInternalClientLoadRequest.html", "structJack_1_1JackInternalClientLoadRequest" ],
    [ "Jack::JackInternalClientLoadResult", "structJack_1_1JackInternalClientLoadResult.html", "structJack_1_1JackInternalClientLoadResult" ],
    [ "Jack::JackInternalClientUnloadRequest", "structJack_1_1JackInternalClientUnloadRequest.html", "structJack_1_1JackInternalClientUnloadRequest" ],
    [ "Jack::JackInternalClientUnloadResult", "structJack_1_1JackInternalClientUnloadResult.html", "structJack_1_1JackInternalClientUnloadResult" ],
    [ "Jack::JackClientNotificationRequest", "structJack_1_1JackClientNotificationRequest.html", "structJack_1_1JackClientNotificationRequest" ],
    [ "Jack::JackSessionCommand", "structJack_1_1JackSessionCommand.html", "structJack_1_1JackSessionCommand" ],
    [ "Jack::JackSessionNotifyResult", "structJack_1_1JackSessionNotifyResult.html", "structJack_1_1JackSessionNotifyResult" ],
    [ "Jack::JackSessionNotifyRequest", "structJack_1_1JackSessionNotifyRequest.html", "structJack_1_1JackSessionNotifyRequest" ],
    [ "Jack::JackSessionReplyRequest", "structJack_1_1JackSessionReplyRequest.html", "structJack_1_1JackSessionReplyRequest" ],
    [ "Jack::JackClientNameResult", "structJack_1_1JackClientNameResult.html", "structJack_1_1JackClientNameResult" ],
    [ "Jack::JackUUIDResult", "structJack_1_1JackUUIDResult.html", "structJack_1_1JackUUIDResult" ],
    [ "Jack::JackGetUUIDRequest", "structJack_1_1JackGetUUIDRequest.html", "structJack_1_1JackGetUUIDRequest" ],
    [ "Jack::JackGetClientNameRequest", "structJack_1_1JackGetClientNameRequest.html", "structJack_1_1JackGetClientNameRequest" ],
    [ "Jack::JackReserveNameRequest", "structJack_1_1JackReserveNameRequest.html", "structJack_1_1JackReserveNameRequest" ],
    [ "Jack::JackClientHasSessionCallbackRequest", "structJack_1_1JackClientHasSessionCallbackRequest.html", "structJack_1_1JackClientHasSessionCallbackRequest" ],
    [ "Jack::JackPropertyChangeNotifyRequest", "structJack_1_1JackPropertyChangeNotifyRequest.html", "structJack_1_1JackPropertyChangeNotifyRequest" ],
    [ "Jack::JackClientNotification", "structJack_1_1JackClientNotification.html", "structJack_1_1JackClientNotification" ],
    [ "CheckRes", "JackRequest_8h.html#a821b8e564e307ca7c8143977c29f5b6e", null ],
    [ "CheckSize", "JackRequest_8h.html#a348b3c09b81eff29702d9d8c1cc92552", null ],
    [ "MAX_PATH", "JackRequest_8h.html#ab99ded389af74001a6298fc9e44e74e5", null ],
    [ "Jack::JackSessionReply", "namespaceJack.html#afacb877c1e8ba598de8cfc2c100bc6f1", [
      [ "Jack::kImmediateSessionReply", "namespaceJack.html#afacb877c1e8ba598de8cfc2c100bc6f1a0dd733c45eb961bcc6d86bc55a3ff474", null ],
      [ "Jack::kPendingSessionReply", "namespaceJack.html#afacb877c1e8ba598de8cfc2c100bc6f1a265e8c3d5cc3a12da72c8d6ad81e4024", null ]
    ] ]
];