var juce__SIMDRegister__test_8cpp =
[
    [ "juce::dsp::SIMDRegister_test_internal::RandomPrimitive&lt; type, typename &gt;", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomPrimitive.html", null ],
    [ "juce::dsp::SIMDRegister_test_internal::RandomPrimitive&lt; type, typename std::enable_if&lt; std::is_floating_point&lt; type &gt;::value &gt;::type &gt;", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomPrimitive_3_01type_00_01typename_01st97aa7bb836e9b9f6da5f09b7ecdae880.html", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomPrimitive_3_01type_00_01typename_01st97aa7bb836e9b9f6da5f09b7ecdae880" ],
    [ "juce::dsp::SIMDRegister_test_internal::RandomPrimitive&lt; type, typename std::enable_if&lt; std::is_integral&lt; type &gt;::value &gt;::type &gt;", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomPrimitive_3_01type_00_01typename_01st182121d27f1a40f8e1f92be04cab145c.html", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomPrimitive_3_01type_00_01typename_01st182121d27f1a40f8e1f92be04cab145c" ],
    [ "juce::dsp::SIMDRegister_test_internal::RandomValue&lt; type &gt;", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomValue.html", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomValue" ],
    [ "juce::dsp::SIMDRegister_test_internal::RandomValue&lt; std::complex&lt; type &gt; &gt;", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomValue_3_01std_1_1complex_3_01type_01_4_01_4.html", "structjuce_1_1dsp_1_1SIMDRegister__test__internal_1_1RandomValue_3_01std_1_1complex_3_01type_01_4_01_4" ],
    [ "juce::dsp::SIMDRegisterUnitTests", "classjuce_1_1dsp_1_1SIMDRegisterUnitTests.html", "classjuce_1_1dsp_1_1SIMDRegisterUnitTests" ],
    [ "juce::dsp::SIMDRegisterUnitTests::Tag&lt; typename &gt;", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1Tag.html", null ],
    [ "juce::dsp::SIMDRegisterUnitTests::Addition", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1Addition.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1Addition" ],
    [ "juce::dsp::SIMDRegisterUnitTests::Subtraction", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1Subtraction.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1Subtraction" ],
    [ "juce::dsp::SIMDRegisterUnitTests::Multiplication", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1Multiplication.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1Multiplication" ],
    [ "juce::dsp::SIMDRegisterUnitTests::BitAND", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1BitAND.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1BitAND" ],
    [ "juce::dsp::SIMDRegisterUnitTests::BitOR", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1BitOR.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1BitOR" ],
    [ "juce::dsp::SIMDRegisterUnitTests::BitXOR", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1BitXOR.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1BitXOR" ],
    [ "juce::dsp::SIMDRegisterUnitTests::InitializationTest", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1InitializationTest.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1InitializationTest" ],
    [ "juce::dsp::SIMDRegisterUnitTests::AccessTest", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1AccessTest.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1AccessTest" ],
    [ "juce::dsp::SIMDRegisterUnitTests::OperatorTests&lt; Operation &gt;", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1OperatorTests.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1OperatorTests" ],
    [ "juce::dsp::SIMDRegisterUnitTests::BitOperatorTests&lt; Operation &gt;", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1BitOperatorTests.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1BitOperatorTests" ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckComparisonOps", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckComparisonOps.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckComparisonOps" ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckMultiplyAdd", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckMultiplyAdd.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckMultiplyAdd" ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckMinMax", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckMinMax.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckMinMax" ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckSum", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckSum.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckSum" ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckAbs", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckAbs.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckAbs" ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckTruncate", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckTruncate.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckTruncate" ],
    [ "juce::dsp::SIMDRegisterUnitTests::CheckBoolEquals", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckBoolEquals.html", "structjuce_1_1dsp_1_1SIMDRegisterUnitTests_1_1CheckBoolEquals" ],
    [ "juce::dsp::SIMDRegister_test_internal::difference", "namespacejuce_1_1dsp_1_1SIMDRegister__test__internal.html#ab62c25e8c7bc53010f2acf9d6cde1475", null ],
    [ "juce::dsp::SIMDRegister_test_internal::difference", "namespacejuce_1_1dsp_1_1SIMDRegister__test__internal.html#a9971c38def6278c3e811720755515650", null ],
    [ "juce::dsp::SIMDRegister_test_internal::fillVec", "namespacejuce_1_1dsp_1_1SIMDRegister__test__internal.html#aec7c43116b2a5a896669a83d8640dfe1", null ],
    [ "juce::dsp::SIMDRegister_test_internal::safeAbs", "namespacejuce_1_1dsp_1_1SIMDRegister__test__internal.html#ac34e9ee1d030c5f19878048003c1a443", null ],
    [ "juce::dsp::SIMDRegister_test_internal::safeAbs", "namespacejuce_1_1dsp_1_1SIMDRegister__test__internal.html#afdf56ec857eddb0fe699ebca3aa06888", null ],
    [ "juce::dsp::SIMDRegisterUnitTests", "namespacejuce_1_1dsp.html#a38d74588136e3fb05d607a7c5600a75e", null ]
];