var juce__fallback__SIMDNativeOps_8h =
[
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; Primitive &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; float &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01float_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01float_01_4" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; double &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01double_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01double_01_4" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; char &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01char_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01char_01_4" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; int8_t &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01int8__t_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01int8__t_01_4" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; int16_t &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01int16__t_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01int16__t_01_4" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; int32_t &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01int32__t_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01int32__t_01_4" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; int64_t &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01int64__t_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01int64__t_01_4" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; std::complex&lt; float &gt; &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01std_1_1complex_3_01float_01_4_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01std_1_1complex_3_01float_01_4_01_4" ],
    [ "juce::dsp::SIMDInternal::MaskTypeFor&lt; std::complex&lt; double &gt; &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01std_1_1complex_3_01double_01_4_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1MaskTypeFor_3_01std_1_1complex_3_01double_01_4_01_4" ],
    [ "juce::dsp::SIMDInternal::PrimitiveType&lt; Primitive &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1PrimitiveType.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1PrimitiveType" ],
    [ "juce::dsp::SIMDInternal::PrimitiveType&lt; std::complex&lt; Primitive &gt; &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1PrimitiveType_3_01std_1_1complex_3_01Primitive_01_4_01_4.html", "structjuce_1_1dsp_1_1SIMDInternal_1_1PrimitiveType_3_01std_1_1complex_3_01Primitive_01_4_01_4" ],
    [ "juce::dsp::SIMDInternal::Log2Helper&lt; n &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1Log2Helper.html", null ],
    [ "juce::dsp::SIMDInternal::Log2Helper&lt; 1 &gt;", "structjuce_1_1dsp_1_1SIMDInternal_1_1Log2Helper_3_011_01_4.html", null ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;", "structjuce_1_1dsp_1_1SIMDFallbackOps.html", "structjuce_1_1dsp_1_1SIMDFallbackOps" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::UnionType", "unionjuce_1_1dsp_1_1SIMDFallbackOps_1_1UnionType.html", "unionjuce_1_1dsp_1_1SIMDFallbackOps_1_1UnionType" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::UnionMaskType", "unionjuce_1_1dsp_1_1SIMDFallbackOps_1_1UnionMaskType.html", "unionjuce_1_1dsp_1_1SIMDFallbackOps_1_1UnionMaskType" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarAdd", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarAdd.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarAdd" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarSub", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarSub.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarSub" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarMul", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarMul.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarMul" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarMin", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarMin.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarMin" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarMax", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarMax.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarMax" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarAnd", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarAnd.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarAnd" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarOr", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarOr.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarOr" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarXor", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarXor.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarXor" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarNot", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarNot.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarNot" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarEq", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarEq.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarEq" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarNeq", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarNeq.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarNeq" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarGt", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarGt.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarGt" ],
    [ "juce::dsp::SIMDFallbackOps&lt; ScalarType, vSIMDType &gt;::ScalarGeq", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarGeq.html", "structjuce_1_1dsp_1_1SIMDFallbackOps_1_1ScalarGeq" ]
];