LMMS: lmms::StepRecorder::StepNote Class Reference
lmms::StepRecorder::StepNote Class Reference
Public Member Functions
StepNote (const Note &note)
bool isPressed () const
bool isReleased () const
void setPressed ()
void setReleased ()
int timeSinceReleased ()
Public Attributes
Note m_note
Private Attributes
bool m_pressed
QElapsedTimer releasedTimer
Detailed Description
Definition at line 101 of file StepRecorder.h.
Constructor & Destructor Documentation
StepNote()
lmms::StepRecorder::StepNote::StepNote (const Note & note) inline
Definition at line 104 of file StepRecorder.h.
References m_note, and m_pressed.
Member Function Documentation
isPressed()
bool lmms::StepRecorder::StepNote::isPressed () const inline
Definition at line 122 of file StepRecorder.h.
References m_pressed.
Referenced by lmms::StepRecorder::noteReleased().
isReleased()
bool lmms::StepRecorder::StepNote::isReleased () const inline
Definition at line 127 of file StepRecorder.h.
References m_pressed.
Referenced by lmms::StepRecorder::notePressed().
setPressed()
void lmms::StepRecorder::StepNote::setPressed () inline
Definition at line 106 of file StepRecorder.h.
References m_pressed.
Referenced by lmms::StepRecorder::notePressed().
setReleased()
void lmms::StepRecorder::StepNote::setReleased () inline
Definition at line 111 of file StepRecorder.h.
References m_pressed, and releasedTimer.
Referenced by lmms::StepRecorder::noteReleased().
timeSinceReleased()
int lmms::StepRecorder::StepNote::timeSinceReleased () inline
Definition at line 117 of file StepRecorder.h.
References releasedTimer.
Member Data Documentation
m_note
Note lmms::StepRecorder::StepNote::m_note
Definition at line 132 of file StepRecorder.h.
Referenced by StepNote().
m_pressed
bool lmms::StepRecorder::StepNote::m_pressed private
Definition at line 135 of file StepRecorder.h.
Referenced by StepNote(), isPressed(), isReleased(), setPressed(), and setReleased().
releasedTimer
QElapsedTimer lmms::StepRecorder::StepNote::releasedTimer private
Definition at line 136 of file StepRecorder.h.
Referenced by setReleased(), and timeSinceReleased().
The documentation for this class was generated from the following file:
include/StepRecorder.h