LMMS: Jack::JackNetMasterInterface Class Reference
Jack::JackNetMasterInterface Class Reference
\Brief This class describes the Net Interface for masters (NetMaster)
#include <JackNetInterface.h>
Public Member Functions
JackNetMasterInterface ()
JackNetMasterInterface (session_params_t &params, JackNetSocket &socket, const char *multicast_ip)
virtual ~JackNetMasterInterface ()
Public Member Functions inherited from Jack::JackNetInterface
JackNetInterface ()
JackNetInterface (const char *multicast_ip, int port)
JackNetInterface (session_params_t &params, JackNetSocket &socket, const char *multicast_ip)
virtual ~JackNetInterface ()
Protected Member Functions
int DataRecv ()
int DataSend ()
void DecodeSyncPacket (int &frames)
void EncodeSyncPacket (int frames=-1)
void Exit ()
void FatalRecvError ()
void FatalSendError ()
bool Init ()
int Recv (size_t size, int flags)
int Send (size_t size, int flags)
bool SetParams ()
int SyncRecv ()
int SyncSend ()
Protected Member Functions inherited from Jack::JackNetInterface
NetAudioBuffer * AudioBufferFactory (int nports, char *buffer)
int AudioRecv (packet_header_t *rx_head, NetAudioBuffer *buffer)
int AudioSend (NetAudioBuffer *buffer, int audio_channels)
virtual void DecodeTransportData ()=0
virtual void EncodeTransportData ()=0
int FinishRecv (NetAudioBuffer *buffer)
void FreeNetworkBuffers ()
void Initialize ()
int MidiRecv (packet_header_t *rx_head, NetMidiBuffer *buffer, uint &recvd_midi_pckt)
int MidiSend (NetMidiBuffer *buffer, int midi_channnels, int audio_channels)
int SetNetBufferSize ()
void SetPacketTimeOut (int time_out)
void SetRcvTimeOut ()
Protected Attributes
int fCurrentCycleOffset
int fMaxCycleOffset
bool fRunning
bool fSynched
Protected Attributes inherited from Jack::JackNetInterface
char fMulticastIP [32]
NetAudioBuffer * fNetAudioCaptureBuffer
NetAudioBuffer * fNetAudioPlaybackBuffer
NetMidiBuffer * fNetMidiCaptureBuffer
NetMidiBuffer * fNetMidiPlaybackBuffer
int fPacketTimeOut
session_params_t fParams
net_transport_data_t fReturnTransportData
char * fRxBuffer
char * fRxData
packet_header_t fRxHeader
net_transport_data_t fSendTransportData
bool fSetTimeOut
JackNetSocket fSocket
char * fTxBuffer
char * fTxData
packet_header_t fTxHeader
Detailed Description
\Brief This class describes the Net Interface for masters (NetMaster)
Definition at line 143 of file JackNetInterface.h.
Constructor & Destructor Documentation
JackNetMasterInterface() [1/2]
Jack::JackNetMasterInterface::JackNetMasterInterface () inline
Definition at line 176 of file JackNetInterface.h.
References Jack::JackNetInterface::JackNetInterface(), fCurrentCycleOffset, fMaxCycleOffset, fRunning, and fSynched.
Referenced by Jack::JackNetMaster::JackNetMaster().
JackNetMasterInterface() [2/2]
Jack::JackNetMasterInterface::JackNetMasterInterface (session_params_t & params, JackNetSocket & socket, const char * multicast_ip) inline
Definition at line 183 of file JackNetInterface.h.
References Jack::JackNetInterface::JackNetInterface(), fCurrentCycleOffset, fMaxCycleOffset, fRunning, and fSynched.
~JackNetMasterInterface()
virtual Jack::JackNetMasterInterface::~JackNetMasterInterface () inline
Definition at line 191 of file JackNetInterface.h.
Member Function Documentation
DataRecv()
int Jack::JackNetMasterInterface::DataRecv () protected virtual
Implements Jack::JackNetInterface.
Definition at line 521 of file JackNetInterface.cpp.
References Jack::JackNetInterface::AudioRecv(), Jack::_packet_header::fDataStream, Jack::_packet_header::fDataType, Jack::_packet_header::fID, Jack::JackNetInterface::FinishRecv(), Jack::JackNetInterface::fNetAudioPlaybackBuffer, Jack::JackNetInterface::fNetMidiPlaybackBuffer, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fRxBuffer, Jack::JackNetInterface::fRxHeader, jack_info(), Jack::JackNetInterface::MidiRecv(), Recv(), and SOCKET_ERROR.
Referenced by Jack::JackNetMaster::Process(), and Jack::JackNetExtMaster::Read().
DataSend()
int Jack::JackNetMasterInterface::DataSend () protected virtual
Implements Jack::JackNetInterface.
Definition at line 474 of file JackNetInterface.cpp.
References Jack::JackNetInterface::AudioSend(), Jack::JackNetInterface::fNetAudioCaptureBuffer, Jack::JackNetInterface::fNetMidiCaptureBuffer, Jack::JackNetInterface::fParams, Jack::JackNetInterface::MidiSend(), and SOCKET_ERROR.
Referenced by Jack::JackNetMaster::Process(), and Jack::JackNetExtMaster::Write().
DecodeSyncPacket()
void Jack::JackNetMasterInterface::DecodeSyncPacket (int & frames) protected virtual
Implements Jack::JackNetInterface.
Definition at line 582 of file JackNetInterface.cpp.
References Jack::_packet_header::fActivePorts, Jack::_packet_header::fFrames, Jack::JackNetInterface::fNetAudioCaptureBuffer, Jack::JackNetInterface::fRxBuffer, and Jack::JackNetInterface::fRxData.
Referenced by Jack::JackNetMaster::Process(), and Jack::JackNetExtMaster::Read().
EncodeSyncPacket()
void Jack::JackNetMasterInterface::EncodeSyncPacket (int frames = -1) protected virtual
Implements Jack::JackNetInterface.
Definition at line 558 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fNetAudioPlaybackBuffer, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fTxData, Jack::JackNetInterface::fTxHeader, and PACKET_AVAILABLE_SIZE.
Referenced by Jack::JackNetMaster::Process(), and Jack::JackNetExtMaster::Write().
Exit()
void Jack::JackNetMasterInterface::Exit () protected
Definition at line 388 of file JackNetInterface.cpp.
References Jack::JackNetUnixSocket::Close(), Jack::JackNetInterface::fMulticastIP, Jack::JackNetInterface::fParams, fRunning, Jack::JackNetInterface::fSocket, jack_error, jack_info(), jack_log(), Jack::KILL_MASTER, NET_ERROR_CODE, Jack::JackNetUnixSocket::NewSocket(), Jack::JackNetUnixSocket::SendTo(), Jack::SessionParamsHToN(), Jack::SetPacketType(), SOCKET_ERROR, and StrError.
Referenced by FatalRecvError(), FatalSendError(), Jack::JackNetMaster::SetBufferSize(), and Jack::JackNetMaster::SetSampleRate().
FatalRecvError()
void Jack::JackNetMasterInterface::FatalRecvError () protected virtual
Implements Jack::JackNetInterface.
Definition at line 414 of file JackNetInterface.cpp.
References Exit(), Jack::JackNetInterface::fParams, jack_error, NET_ERROR_CODE, StrError, and Jack::ThreadExit().
Referenced by Recv().
FatalSendError()
void Jack::JackNetMasterInterface::FatalSendError () protected virtual
Implements Jack::JackNetInterface.
Definition at line 424 of file JackNetInterface.cpp.
References Exit(), Jack::JackNetInterface::fParams, jack_error, NET_ERROR_CODE, StrError, and Jack::ThreadExit().
Referenced by Send().
Init()
bool Jack::JackNetMasterInterface::Init () protected virtual
Implements Jack::JackNetInterface.
Definition at line 279 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fParams, Jack::JackNetInterface::fSocket, Jack::GetPacketType(), jack_error, jack_info(), jack_log(), MASTER_INIT_TIMEOUT, NET_ERROR_CODE, Jack::NET_NO_DATA, Jack::SessionParamsHToN(), Jack::SessionParamsNToH(), Jack::SetPacketType(), Jack::SLAVE_SETUP, SLAVE_SETUP_RETRY, SOCKET_ERROR, Jack::START_MASTER, and StrError.
Referenced by Jack::JackNetMaster::Init(), and Jack::JackNetExtMaster::InitMaster().
Recv()
int Jack::JackNetMasterInterface::Recv (size_t size, int flags) protected virtual
Implements Jack::JackNetInterface.
Definition at line 434 of file JackNetInterface.cpp.
References FatalRecvError(), fRunning, Jack::JackNetInterface::fRxBuffer, Jack::JackNetInterface::fSocket, Jack::PacketHeaderNToH(), and SOCKET_ERROR.
Referenced by DataRecv(), and SyncRecv().
Send()
int Jack::JackNetMasterInterface::Send (size_t size, int flags) protected virtual
Implements Jack::JackNetInterface.
Definition at line 447 of file JackNetInterface.cpp.
References FatalSendError(), fRunning, Jack::JackNetInterface::fSocket, Jack::JackNetInterface::fTxBuffer, Jack::PacketHeaderHToN(), and SOCKET_ERROR.
Referenced by SyncSend().
SetParams()
bool Jack::JackNetMasterInterface::SetParams () protected virtual
Reimplemented from Jack::JackNetInterface.
Definition at line 335 of file JackNetInterface.cpp.
References Jack::JackNetInterface::AudioBufferFactory(), fMaxCycleOffset, Jack::JackNetInterface::fNetAudioCaptureBuffer, Jack::JackNetInterface::fNetAudioPlaybackBuffer, Jack::JackNetInterface::fNetMidiCaptureBuffer, Jack::JackNetInterface::fNetMidiPlaybackBuffer, Jack::JackNetInterface::fParams, Jack::JackNetInterface::FreeNetworkBuffers(), Jack::JackNetInterface::fRxData, Jack::JackNetInterface::fRxHeader, Jack::JackNetInterface::fTxData, Jack::JackNetInterface::fTxHeader, jack_error, jack_log(), NET_ERROR_CODE, Jack::JackNetInterface::SetNetBufferSize(), Jack::JackNetInterface::SetParams(), SOCKET_ERROR, and StrError.
Referenced by Jack::JackNetMaster::Init(), and Jack::JackNetExtMaster::InitMaster().
SyncRecv()
int Jack::JackNetMasterInterface::SyncRecv () protected virtual
Implements Jack::JackNetInterface.
Definition at line 482 of file JackNetInterface.cpp.
References fCurrentCycleOffset, Jack::_packet_header::fCycle, Jack::_packet_header::fDataType, Jack::_packet_header::fIsLastPckt, fMaxCycleOffset, Jack::_packet_header::fPacketSize, Jack::_packet_header::fPacketType, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fRxBuffer, Jack::JackNetInterface::fRxHeader, fSynched, Jack::JackNetInterface::fTxHeader, jack_error, jack_info(), NET_SYNCHING, Recv(), SOCKET_ERROR, and SYNC_PACKET_ERROR.
Referenced by Jack::JackNetMaster::Process(), and Jack::JackNetExtMaster::Read().
SyncSend()
int Jack::JackNetMasterInterface::SyncSend () protected virtual
Implements Jack::JackNetInterface.
Definition at line 459 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fParams, Jack::JackNetInterface::fTxBuffer, Jack::JackNetInterface::fTxHeader, HEADER_SIZE, Send(), and Jack::JackNetInterface::SetRcvTimeOut().
Referenced by Jack::JackNetMaster::Process(), and Jack::JackNetExtMaster::Write().
Member Data Documentation
fCurrentCycleOffset
int Jack::JackNetMasterInterface::fCurrentCycleOffset protected
Definition at line 149 of file JackNetInterface.h.
Referenced by JackNetMasterInterface(), JackNetMasterInterface(), and SyncRecv().
fMaxCycleOffset
int Jack::JackNetMasterInterface::fMaxCycleOffset protected
Definition at line 150 of file JackNetInterface.h.
Referenced by JackNetMasterInterface(), JackNetMasterInterface(), SetParams(), and SyncRecv().
fRunning
bool Jack::JackNetMasterInterface::fRunning protected
Definition at line 148 of file JackNetInterface.h.
Referenced by Jack::JackNetExtMaster::JackNetExtMaster(), JackNetMasterInterface(), JackNetMasterInterface(), Exit(), Jack::JackNetMaster::Init(), Jack::JackNetExtMaster::Open(), Jack::JackNetMaster::Process(), Recv(), and Send().
fSynched
bool Jack::JackNetMasterInterface::fSynched protected
Definition at line 151 of file JackNetInterface.h.
Referenced by JackNetMasterInterface(), JackNetMasterInterface(), and SyncRecv().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackNetInterface.h
src/3rdparty/jack2/common/JackNetInterface.cpp