LMMS: lmms::Oscillator Class Reference
lmms::Oscillator Class Reference
#include <Oscillator.h>
Classes
struct wtSampleControl
Public Types
enum class ModulationAlgo {
PhaseModulation ,
AmplitudeModulation ,
SignalMix ,
SynchronizedBySubOsc ,
FrequencyModulation ,
Count
}
enum class WaveShape {
Sine ,
Triangle ,
Saw ,
Square ,
MoogSaw ,
Exponential ,
WhiteNoise ,
UserDefined ,
Count
}
Public Member Functions
Oscillator (const IntModel *wave_shape_model, const IntModel *mod_algo_model, const float &freq, const float &detuning_div_samplerate, const float &phase_offset, const float &volume, Oscillator *m_subOsc=nullptr)
virtual ~Oscillator ()
wtSampleControl getWtSampleControl (const float sample) const
void setUserAntiAliasWaveTable (std::shared_ptr< const OscillatorConstants::waveform_t > waveform)
void setUserWave (std::shared_ptr< const SampleBuffer > _wave)
void setUseWaveTable (bool n)
void update (SampleFrame *ab, const fpp_t frames, const ch_cnt_t chnl, bool modulator=false)
sample_t wtSample (const OscillatorConstants::waveform_t *table, const float sample) const
sample_t wtSample (const sample_t table[OscillatorConstants::WAVE_TABLES_PER_WAVEFORM_COUNT][OscillatorConstants::WAVETABLE_LENGTH], const float sample) const
sample_t wtSample (sample_t **table, const float sample) const
Static Public Member Functions
static void destroyFFTPlans ()
static sample_t expSample (const float _sample)
static float freqFromWaveTableBand (int band)
static std::unique_ptr< OscillatorConstants::waveform_t > generateAntiAliasUserWaveTable (const SampleBuffer *sampleBuffer)
static sample_t moogSawSample (const float _sample)
static sample_t noiseSample (const float)
static sample_t sawSample (const float _sample)
static sample_t sinSample (const float _sample)
static sample_t squareSample (const float _sample)
static sample_t triangleSample (const float _sample)
static sample_t userWaveSample (const SampleBuffer *buffer, const float sample)
static int waveTableBandFromFreq (float freq)
static void waveTableInit ()
Static Public Attributes
static constexpr auto FirstWaveShapeTable = static_cast<std::size_t>(WaveShape::Triangle)
First wave shape that has a pre-generated table.
static constexpr auto NumModulationAlgos = static_cast<std::size_t>(ModulationAlgo::Count)
static constexpr auto NumWaveShapes = static_cast<std::size_t>(WaveShape::Count)
static constexpr auto NumWaveShapeTables = static_cast<std::size_t>(WaveShape::WhiteNoise) - FirstWaveShapeTable
Number of band-limited wave shapes to be generated.
Private Member Functions
template<WaveShape W>
sample_t getSample (const float _sample)
void recalcPhase ()
float syncInit (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
bool syncOk (float _osc_coeff)
template<WaveShape W>
void updateAM (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
void updateAM (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
template<WaveShape W>
void updateFM (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
void updateFM (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
template<WaveShape W>
void updateMix (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
void updateMix (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
template<WaveShape W>
void updateNoSub (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
void updateNoSub (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
template<WaveShape W>
void updatePM (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
void updatePM (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
template<WaveShape W>
void updateSync (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
void updateSync (SampleFrame *_ab, const fpp_t _frames, const ch_cnt_t _chnl)
Static Private Member Functions
static void createFFTPlans ()
static void generateFromFFT (int bands, sample_t *table)
static void generateSawWaveTable (int bands, sample_t *table, int firstBand=1)
static void generateSquareWaveTable (int bands, sample_t *table, int firstBand=1)
static void generateTriangleWaveTable (int bands, sample_t *table, int firstBand=1)
static void generateWaveTables ()
Private Attributes
const float & m_detuning_div_samplerate
const float & m_ext_phaseOffset
const float & m_freq
bool m_isModulator
const IntModel * m_modulationAlgoModel
float m_phase
float m_phaseOffset
Oscillator * m_subOsc
std::shared_ptr< const OscillatorConstants::waveform_t > m_userAntiAliasWaveTable
std::shared_ptr< const SampleBuffer > m_userWave = SampleBuffer::emptyBuffer()
bool m_useWaveTable
const float & m_volume
const IntModel * m_waveShapeModel
Static Private Attributes
static fftwf_plan s_fftPlan
static fftwf_plan s_ifftPlan
static std::array< float, OscillatorConstants::WAVETABLE_LENGTH > s_sampleBuffer
static fftwf_complex * s_specBuf
static sample_t s_waveTables [NumWaveShapeTables][OscillatorConstants::WAVE_TABLES_PER_WAVEFORM_COUNT][OscillatorConstants::WAVETABLE_LENGTH]
Detailed Description
Definition at line 48 of file Oscillator.h.
Member Enumeration Documentation
ModulationAlgo
enum class lmms::Oscillator::ModulationAlgo strong
Enumerator
PhaseModulation
AmplitudeModulation
SignalMix
SynchronizedBySubOsc
FrequencyModulation
Count
Definition at line 69 of file Oscillator.h.
WaveShape
enum class lmms::Oscillator::WaveShape strong
Enumerator
Sine
Triangle
Saw
Square
MoogSaw
Exponential
WhiteNoise
UserDefined
Count
Number of all available wave shapes.
Definition at line 51 of file Oscillator.h.
Constructor & Destructor Documentation
Oscillator()
lmms::Oscillator::Oscillator (const IntModel * wave_shape_model, const IntModel * mod_algo_model, const float & freq, const float & detuning_div_samplerate, const float & phase_offset, const float & volume, Oscillator * m_subOsc = nullptr)
Definition at line 55 of file Oscillator.cpp.
References Oscillator(), m_detuning_div_samplerate, m_ext_phaseOffset, m_freq, m_isModulator, m_modulationAlgoModel, m_phase, m_phaseOffset, m_subOsc, m_userWave, m_useWaveTable, m_volume, and m_waveShapeModel.
Referenced by Oscillator().
~Oscillator()
virtual lmms::Oscillator::~Oscillator () inline virtual
Definition at line 87 of file Oscillator.h.
References m_subOsc.
Member Function Documentation
createFFTPlans()
void lmms::Oscillator::createFFTPlans () static private
Definition at line 223 of file Oscillator.cpp.
References i, s_fftPlan, s_ifftPlan, s_sampleBuffer, s_specBuf, and lmms::OscillatorConstants::WAVETABLE_LENGTH.
Referenced by waveTableInit().
destroyFFTPlans()
void lmms::Oscillator::destroyFFTPlans () static
Definition at line 236 of file Oscillator.cpp.
References s_fftPlan, s_ifftPlan, and s_specBuf.
Referenced by lmms::Engine::destroy().
expSample()
sample_t lmms::Oscillator::expSample (const float _sample) inline static
Definition at line 153 of file Oscillator.h.
References lmms::absFraction().
Referenced by generateWaveTables(), and lmms::LfoController::updateSampleFunction().
freqFromWaveTableBand()
float lmms::Oscillator::freqFromWaveTableBand (int band) inline static
Definition at line 238 of file Oscillator.h.
References lmms::OscillatorConstants::SEMITONES_PER_TABLE.
Referenced by generateAntiAliasUserWaveTable(), and generateWaveTables().
generateAntiAliasUserWaveTable()
std::unique_ptr< OscillatorConstants::waveform_t > lmms::Oscillator::generateAntiAliasUserWaveTable (const SampleBuffer * sampleBuffer) static
Definition at line 191 of file Oscillator.cpp.
References freqFromWaveTableBand(), generateFromFFT(), i, j, lmms::OscillatorConstants::MAX_FREQ, s_fftPlan, s_sampleBuffer, userWaveSample(), lmms::OscillatorConstants::WAVE_TABLES_PER_WAVEFORM_COUNT, and lmms::OscillatorConstants::WAVETABLE_LENGTH.
generateFromFFT()
void lmms::Oscillator::generateFromFFT (int bands, sample_t * table) static private
Definition at line 175 of file Oscillator.cpp.
References i, lmms::normalize(), s_ifftPlan, s_sampleBuffer, s_specBuf, and lmms::OscillatorConstants::WAVETABLE_LENGTH.
Referenced by generateAntiAliasUserWaveTable(), and generateWaveTables().
generateSawWaveTable()
void lmms::Oscillator::generateSawWaveTable (int bands, sample_t * table, int firstBand = 1) static private
Definition at line 119 of file Oscillator.cpp.
References i, and lmms::OscillatorConstants::WAVETABLE_LENGTH.
Referenced by generateWaveTables().
generateSquareWaveTable()
void lmms::Oscillator::generateSquareWaveTable (int bands, sample_t * table, int firstBand = 1) static private
Definition at line 155 of file Oscillator.cpp.
References i, and lmms::OscillatorConstants::WAVETABLE_LENGTH.
Referenced by generateWaveTables().
generateTriangleWaveTable()
void lmms::Oscillator::generateTriangleWaveTable (int bands, sample_t * table, int firstBand = 1) static private
Definition at line 137 of file Oscillator.cpp.
References i, and lmms::OscillatorConstants::WAVETABLE_LENGTH.
Referenced by generateWaveTables().
generateWaveTables()
void lmms::Oscillator::generateWaveTables () static private
Definition at line 243 of file Oscillator.cpp.
References Exponential, expSample(), FirstWaveShapeTable, freqFromWaveTableBand(), generateFromFFT(), generateSawWaveTable(), generateSquareWaveTable(), generateTriangleWaveTable(), i, lmms::OscillatorConstants::MAX_FREQ, MoogSaw, moogSawSample(), s_fftPlan, s_sampleBuffer, s_waveTables, Saw, Square, Triangle, lmms::OscillatorConstants::WAVE_TABLES_PER_WAVEFORM_COUNT, and lmms::OscillatorConstants::WAVETABLE_LENGTH.
Referenced by waveTableInit().
getSample()
template<WaveShape W> sample_t lmms::Oscillator::getSample (const float _sample) inline private
References recalcPhase().
Referenced by lmms::Oscillator::getSample< Oscillator::WaveShape::Exponential >(), lmms::Oscillator::getSample< Oscillator::WaveShape::MoogSaw >(), lmms::Oscillator::getSample< Oscillator::WaveShape::Saw >(), lmms::Oscillator::getSample< Oscillator::WaveShape::Sine >(), lmms::Oscillator::getSample< Oscillator::WaveShape::Square >(), lmms::Oscillator::getSample< Oscillator::WaveShape::Triangle >(), lmms::Oscillator::getSample< Oscillator::WaveShape::UserDefined >(), lmms::Oscillator::getSample< Oscillator::WaveShape::WhiteNoise >(), updateAM(), updateFM(), updateMix(), updateNoSub(), updatePM(), and updateSync().
getWtSampleControl()
wtSampleControl lmms::Oscillator::getWtSampleControl (const float sample) const inline
Definition at line 185 of file Oscillator.h.
References lmms::absFraction(), lmms::Engine::audioEngine(), lmms::Oscillator::wtSampleControl::band, lmms::Oscillator::wtSampleControl::f1, lmms::Oscillator::wtSampleControl::f2, lmms::Oscillator::wtSampleControl::frame, m_detuning_div_samplerate, m_freq, lmms::OscillatorConstants::WAVETABLE_LENGTH, and waveTableBandFromFreq().
Referenced by wtSample(), wtSample(), and wtSample().
moogSawSample()
sample_t lmms::Oscillator::moogSawSample (const float _sample) inline static
Definition at line 143 of file Oscillator.h.
References lmms::absFraction().
Referenced by generateWaveTables(), and lmms::LfoController::updateSampleFunction().
noiseSample()
sample_t lmms::Oscillator::noiseSample (const float) inline static
Definition at line 163 of file Oscillator.h.
Referenced by lmms::EnvelopeAndLfoParameters::lfoShapeSample(), lmms::gui::LfoGraph::paintEvent(), lmms::graphModel::setWaveToNoise(), and lmms::LfoController::updateSampleFunction().
recalcPhase()
void lmms::Oscillator::recalcPhase () inline private
Definition at line 542 of file Oscillator.cpp.
References lmms::absFraction(), lmms::approximatelyEqual(), m_ext_phaseOffset, m_phase, and m_phaseOffset.
Referenced by getSample(), syncInit(), updateAM(), updateFM(), updateMix(), updateNoSub(), updatePM(), and updateSync().
sawSample()
sample_t lmms::Oscillator::sawSample (const float _sample) inline static
Definition at line 133 of file Oscillator.h.
References lmms::absFraction().
Referenced by lmms::EnvelopeAndLfoParameters::lfoShapeSample(), lmms::gui::LfoGraph::paintEvent(), lmms::graphModel::setWaveToSaw(), and lmms::LfoController::updateSampleFunction().
setUserAntiAliasWaveTable()
void lmms::Oscillator::setUserAntiAliasWaveTable (std::shared_ptr< const OscillatorConstants::waveform_t > waveform) inline
Definition at line 106 of file Oscillator.h.
References m_userAntiAliasWaveTable.
setUserWave()
void lmms::Oscillator::setUserWave (std::shared_ptr< const SampleBuffer > _wave) inline
Definition at line 101 of file Oscillator.h.
References m_userWave.
setUseWaveTable()
void lmms::Oscillator::setUseWaveTable (bool n) inline
Definition at line 96 of file Oscillator.h.
References m_useWaveTable.
sinSample()
sample_t lmms::Oscillator::sinSample (const float _sample) inline static
Definition at line 114 of file Oscillator.h.
Referenced by lmms::EnvelopeAndLfoParameters::lfoShapeSample(), lmms::gui::LfoGraph::paintEvent(), lmms::graphModel::setWaveToSine(), and lmms::LfoController::updateSampleFunction().
squareSample()
sample_t lmms::Oscillator::squareSample (const float _sample) inline static
Definition at line 138 of file Oscillator.h.
References lmms::absFraction().
Referenced by lmms::EnvelopeAndLfoParameters::lfoShapeSample(), lmms::gui::LfoGraph::paintEvent(), lmms::graphModel::setWaveToSquare(), and lmms::LfoController::updateSampleFunction().
syncInit()
float lmms::Oscillator::syncInit (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 567 of file Oscillator.cpp.
References m_detuning_div_samplerate, m_freq, m_subOsc, and recalcPhase().
syncOk()
bool lmms::Oscillator::syncOk (float _osc_coeff) inline private
Definition at line 556 of file Oscillator.cpp.
References m_phase.
triangleSample()
sample_t lmms::Oscillator::triangleSample (const float _sample) inline static
Definition at line 119 of file Oscillator.h.
References lmms::absFraction().
Referenced by lmms::EnvelopeAndLfoParameters::lfoShapeSample(), lmms::gui::LfoGraph::paintEvent(), lmms::graphModel::setWaveToTriangle(), and lmms::LfoController::updateSampleFunction().
update()
void lmms::Oscillator::update (SampleFrame * ab, const fpp_t frames, const ch_cnt_t chnl, bool modulator = false)
Definition at line 80 of file Oscillator.cpp.
References AmplitudeModulation, lmms::Engine::audioEngine(), FrequencyModulation, m_freq, m_isModulator, m_modulationAlgoModel, m_subOsc, PhaseModulation, SignalMix, SynchronizedBySubOsc, updateAM(), updateFM(), updateMix(), updateNoSub(), updatePM(), updateSync(), and lmms::zeroSampleFrames().
updateAM() [1/2]
template<Oscillator::WaveShape W> void lmms::Oscillator::updateAM (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 622 of file Oscillator.cpp.
References getSample(), m_detuning_div_samplerate, m_freq, m_phase, m_subOsc, m_volume, and recalcPhase().
updateAM() [2/2]
void lmms::Oscillator::updateAM (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 397 of file Oscillator.cpp.
References Exponential, m_waveShapeModel, MoogSaw, Saw, Sine, Square, Triangle, updateAM(), UserDefined, and WhiteNoise.
Referenced by update(), and updateAM().
updateFM() [1/2]
template<Oscillator::WaveShape W> void lmms::Oscillator::updateFM (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 684 of file Oscillator.cpp.
References lmms::Engine::audioEngine(), getSample(), m_detuning_div_samplerate, m_freq, m_phase, m_subOsc, m_volume, lmms::AudioEngine::outputSampleRate(), and recalcPhase().
updateFM() [2/2]
void lmms::Oscillator::updateFM (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 505 of file Oscillator.cpp.
References Exponential, m_waveShapeModel, MoogSaw, Saw, Sine, Square, Triangle, updateFM(), UserDefined, and WhiteNoise.
Referenced by update(), and updateFM().
updateMix() [1/2]
template<Oscillator::WaveShape W> void lmms::Oscillator::updateMix (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 641 of file Oscillator.cpp.
References getSample(), m_detuning_div_samplerate, m_freq, m_phase, m_subOsc, m_volume, and recalcPhase().
updateMix() [2/2]
void lmms::Oscillator::updateMix (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 433 of file Oscillator.cpp.
References Exponential, m_waveShapeModel, MoogSaw, Saw, Sine, Square, Triangle, updateMix(), UserDefined, and WhiteNoise.
Referenced by update(), and updateMix().
updateNoSub() [1/2]
template<Oscillator::WaveShape W> void lmms::Oscillator::updateNoSub (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 583 of file Oscillator.cpp.
References getSample(), m_detuning_div_samplerate, m_freq, m_phase, m_volume, and recalcPhase().
updateNoSub() [2/2]
void lmms::Oscillator::updateNoSub (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 325 of file Oscillator.cpp.
References Exponential, m_waveShapeModel, MoogSaw, Saw, Sine, Square, Triangle, updateNoSub(), UserDefined, and WhiteNoise.
Referenced by update(), and updateNoSub().
updatePM() [1/2]
template<Oscillator::WaveShape W> void lmms::Oscillator::updatePM (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 601 of file Oscillator.cpp.
References getSample(), m_detuning_div_samplerate, m_freq, m_phase, m_subOsc, m_volume, and recalcPhase().
updatePM() [2/2]
void lmms::Oscillator::updatePM (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 361 of file Oscillator.cpp.
References Exponential, m_waveShapeModel, MoogSaw, Saw, Sine, Square, Triangle, updatePM(), UserDefined, and WhiteNoise.
Referenced by update(), and updatePM().
updateSync() [1/2]
template<Oscillator::WaveShape W> void lmms::Oscillator::updateSync (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 661 of file Oscillator.cpp.
References getSample(), m_detuning_div_samplerate, m_freq, m_phase, m_phaseOffset, m_subOsc, m_volume, and recalcPhase().
updateSync() [2/2]
void lmms::Oscillator::updateSync (SampleFrame * _ab, const fpp_t _frames, const ch_cnt_t _chnl) private
Definition at line 469 of file Oscillator.cpp.
References Exponential, m_waveShapeModel, MoogSaw, Saw, Sine, Square, Triangle, updateSync(), UserDefined, and WhiteNoise.
Referenced by update(), and updateSync().
userWaveSample()
sample_t lmms::Oscillator::userWaveSample (const SampleBuffer * buffer, const float sample) inline static
Definition at line 168 of file Oscillator.h.
References lmms::absFraction(), lmms::SampleBuffer::data(), lmms::fraction(), and lmms::SampleBuffer::size().
Referenced by generateAntiAliasUserWaveTable(), lmms::EnvelopeAndLfoParameters::lfoShapeSample(), lmms::gui::LfoGraph::paintEvent(), lmms::graphModel::setWaveToUser(), and lmms::LfoController::updateValueBuffer().
waveTableBandFromFreq()
int lmms::Oscillator::waveTableBandFromFreq (float freq) inline static
Definition at line 225 of file Oscillator.h.
References lmms::OscillatorConstants::SEMITONES_PER_TABLE, and lmms::OscillatorConstants::WAVE_TABLES_PER_WAVEFORM_COUNT.
Referenced by getWtSampleControl().
waveTableInit()
void lmms::Oscillator::waveTableInit () static
Definition at line 45 of file Oscillator.cpp.
References createFFTPlans(), and generateWaveTables().
Referenced by lmms::Engine::init().
wtSample() [1/3]
sample_t lmms::Oscillator::wtSample (const OscillatorConstants::waveform_t * table, const float sample) const inline
Definition at line 207 of file Oscillator.h.
References lmms::Oscillator::wtSampleControl::band, lmms::Oscillator::wtSampleControl::f1, lmms::Oscillator::wtSampleControl::f2, lmms::fraction(), lmms::Oscillator::wtSampleControl::frame, and getWtSampleControl().
wtSample() [2/3]
sample_t lmms::Oscillator::wtSample (const sample_t table[OscillatorConstants::WAVE_TABLES_PER_WAVEFORM_COUNT][OscillatorConstants::WAVETABLE_LENGTH], const float sample) const inline
Definition at line 198 of file Oscillator.h.
References lmms::Oscillator::wtSampleControl::band, lmms::Oscillator::wtSampleControl::f1, lmms::Oscillator::wtSampleControl::f2, lmms::fraction(), lmms::Oscillator::wtSampleControl::frame, getWtSampleControl(), lmms::OscillatorConstants::WAVE_TABLES_PER_WAVEFORM_COUNT, and lmms::OscillatorConstants::WAVETABLE_LENGTH.
wtSample() [3/3]
sample_t lmms::Oscillator::wtSample (sample_t ** table, const float sample) const inline
Definition at line 218 of file Oscillator.h.
References lmms::Oscillator::wtSampleControl::band, lmms::Oscillator::wtSampleControl::f1, lmms::Oscillator::wtSampleControl::f2, lmms::fraction(), lmms::Oscillator::wtSampleControl::frame, and getWtSampleControl().
Member Data Documentation
FirstWaveShapeTable
auto lmms::Oscillator::FirstWaveShapeTable = static_cast<std::size_t>(WaveShape::Triangle) static constexpr
First wave shape that has a pre-generated table.
Definition at line 65 of file Oscillator.h.
Referenced by generateWaveTables().
m_detuning_div_samplerate
const float& lmms::Oscillator::m_detuning_div_samplerate private
Definition at line 247 of file Oscillator.h.
Referenced by Oscillator(), getWtSampleControl(), syncInit(), updateAM(), updateFM(), updateMix(), updateNoSub(), updatePM(), and updateSync().
m_ext_phaseOffset
const float& lmms::Oscillator::m_ext_phaseOffset private
Definition at line 249 of file Oscillator.h.
Referenced by Oscillator(), and recalcPhase().
m_freq
const float& lmms::Oscillator::m_freq private
Definition at line 246 of file Oscillator.h.
Referenced by Oscillator(), getWtSampleControl(), syncInit(), update(), updateAM(), updateFM(), updateMix(), updateNoSub(), updatePM(), and updateSync().
m_isModulator
bool lmms::Oscillator::m_isModulator private
Definition at line 258 of file Oscillator.h.
Referenced by Oscillator(), and update().
m_modulationAlgoModel
const IntModel* lmms::Oscillator::m_modulationAlgoModel private
Definition at line 245 of file Oscillator.h.
Referenced by Oscillator(), and update().
m_phase
float lmms::Oscillator::m_phase private
Definition at line 252 of file Oscillator.h.
Referenced by Oscillator(), recalcPhase(), syncOk(), updateAM(), updateFM(), updateMix(), updateNoSub(), updatePM(), and updateSync().
m_phaseOffset
float lmms::Oscillator::m_phaseOffset private
Definition at line 251 of file Oscillator.h.
Referenced by Oscillator(), recalcPhase(), and updateSync().
m_subOsc
Oscillator* lmms::Oscillator::m_subOsc private
Definition at line 250 of file Oscillator.h.
Referenced by Oscillator(), ~Oscillator(), syncInit(), update(), updateAM(), updateFM(), updateMix(), updatePM(), and updateSync().
m_userAntiAliasWaveTable
std::shared_ptr<const OscillatorConstants::waveform_t> lmms::Oscillator::m_userAntiAliasWaveTable private
Definition at line 254 of file Oscillator.h.
Referenced by setUserAntiAliasWaveTable().
m_userWave
std::shared_ptr<const SampleBuffer> lmms::Oscillator::m_userWave = SampleBuffer::emptyBuffer() private
Definition at line 253 of file Oscillator.h.
Referenced by Oscillator(), and setUserWave().
m_useWaveTable
bool lmms::Oscillator::m_useWaveTable private
Definition at line 255 of file Oscillator.h.
Referenced by Oscillator(), and setUseWaveTable().
m_volume
const float& lmms::Oscillator::m_volume private
Definition at line 248 of file Oscillator.h.
Referenced by Oscillator(), updateAM(), updateFM(), updateMix(), updateNoSub(), updatePM(), and updateSync().
m_waveShapeModel
const IntModel* lmms::Oscillator::m_waveShapeModel private
Definition at line 244 of file Oscillator.h.
Referenced by Oscillator(), updateAM(), updateFM(), updateMix(), updateNoSub(), updatePM(), and updateSync().
NumModulationAlgos
auto lmms::Oscillator::NumModulationAlgos = static_cast<std::size_t>(ModulationAlgo::Count) static constexpr
Definition at line 78 of file Oscillator.h.
NumWaveShapes
auto lmms::Oscillator::NumWaveShapes = static_cast<std::size_t>(WaveShape::Count) static constexpr
Definition at line 63 of file Oscillator.h.
NumWaveShapeTables
auto lmms::Oscillator::NumWaveShapeTables = static_cast<std::size_t>(WaveShape::WhiteNoise) - FirstWaveShapeTable static constexpr
Number of band-limited wave shapes to be generated.
Definition at line 67 of file Oscillator.h.
s_fftPlan
fftwf_plan lmms::Oscillator::s_fftPlan static private
Definition at line 262 of file Oscillator.h.
Referenced by createFFTPlans(), destroyFFTPlans(), generateAntiAliasUserWaveTable(), and generateWaveTables().
s_ifftPlan
fftwf_plan lmms::Oscillator::s_ifftPlan static private
Definition at line 263 of file Oscillator.h.
Referenced by createFFTPlans(), destroyFFTPlans(), and generateFromFFT().
s_sampleBuffer
std::array< float, OscillatorConstants::WAVETABLE_LENGTH > lmms::Oscillator::s_sampleBuffer static private
Definition at line 265 of file Oscillator.h.
Referenced by createFFTPlans(), generateAntiAliasUserWaveTable(), generateFromFFT(), and generateWaveTables().
s_specBuf
fftwf_complex * lmms::Oscillator::s_specBuf static private
Definition at line 264 of file Oscillator.h.
Referenced by createFFTPlans(), destroyFFTPlans(), and generateFromFFT().
s_waveTables
sample_t lmms::Oscillator::s_waveTables static private
Definition at line 261 of file Oscillator.h.
Referenced by generateWaveTables().
The documentation for this class was generated from the following files:
include/Oscillator.h
src/core/Oscillator.cpp