LMMS: lmms::Clipboard Namespace Reference
lmms::Clipboard Namespace Reference
Enumerations
enum class MimeType {
StringPair ,
Default
}
Functions
void copyString (const QString &str, MimeType mT)
void copyStringPair (const QString &key, const QString &value)
QString decodeKey (const QMimeData *mimeData)
QString decodeValue (const QMimeData *mimeData)
const QMimeData * getMimeData ()
QString getString (MimeType mT)
bool hasFormat (MimeType mT)
const char * mimeType (MimeType type)
Enumeration Type Documentation
MimeType
enum class lmms::Clipboard::MimeType strong
Enumerator
StringPair
Default
Definition at line 38 of file Clipboard.h.
Function Documentation
copyString()
void LMMS_EXPORT lmms::Clipboard::copyString (const QString & str, MimeType mT)
Definition at line 51 of file Clipboard.cpp.
References mimeType().
copyStringPair()
void lmms::Clipboard::copyStringPair (const QString & key, const QString & value)
Definition at line 70 of file Clipboard.cpp.
References mimeType(), and StringPair.
decodeKey()
QString lmms::Clipboard::decodeKey (const QMimeData * mimeData)
Definition at line 82 of file Clipboard.cpp.
References mimeType(), and StringPair.
Referenced by lmms::gui::StringPairDrag::decodeKey().
decodeValue()
QString lmms::Clipboard::decodeValue (const QMimeData * mimeData)
Definition at line 90 of file Clipboard.cpp.
References mimeType(), and StringPair.
Referenced by lmms::gui::StringPairDrag::decodeValue().
getMimeData()
const QMimeData * lmms::Clipboard::getMimeData ()
Definition at line 35 of file Clipboard.cpp.
Referenced by getString(), and hasFormat().
getString()
QString lmms::Clipboard::getString (MimeType mT)
Definition at line 62 of file Clipboard.cpp.
References getMimeData(), and mimeType().
hasFormat()
bool lmms::Clipboard::hasFormat (MimeType mT)
Definition at line 43 of file Clipboard.cpp.
References getMimeData(), and mimeType().
mimeType()
const char * lmms::Clipboard::mimeType (MimeType type) inline
Definition at line 57 of file Clipboard.h.
References Default, and StringPair.
Referenced by copyString(), copyStringPair(), decodeKey(), decodeValue(), getString(), and hasFormat().