LMMS: src/3rdparty/jack2/windows/portaudio/JackPortAudioAdapter.h File Reference
JackPortAudioAdapter.h File Reference
#include "JackAudioAdapter.h"
#include "JackPortAudioDevices.h"
#include "jslist.h"
#include "JackCompilerDeps.h"
#include "driver_interface.h"
Classes
class Jack::JackPortAudioAdapter
Audio adapter using PortAudio API.
Namespaces
namespace Jack
Functions
SERVER_EXPORT jack_driver_desc_t * jack_get_descriptor ()
Function Documentation
jack_get_descriptor()
SERVER_EXPORT jack_driver_desc_t * jack_get_descriptor ()
Definition at line 39 of file JackSapaProxyIn.cpp.
References DEFAULT_MTU, DEFAULT_MULTICAST_IP, DEFAULT_PORT, FALSE, jack_driver_param_value_t::i, jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverNone, JackDriverParamBool, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, OSS_DRIVER_DEF_BITS, OSS_DRIVER_DEF_BLKSIZE, OSS_DRIVER_DEF_DEV, OSS_DRIVER_DEF_FS, OSS_DRIVER_DEF_INS, OSS_DRIVER_DEF_NPERIODS, OSS_DRIVER_DEF_OUTS, SERVER_EXPORT, jack_driver_param_value_t::str, and jack_driver_param_value_t::ui.
Referenced by jack_drivers_load(), jack_initialize(), and jack_internals_load().