LMMS: lmms::DrumSynth Class Reference
lmms::DrumSynth Class Reference
#include <DrumSynth.h>
Public Member Functions
DrumSynth ()=default
int GetDSFileSamples (QString dsfile, int16_t *&wave, int channels, sample_rate_t Fs)
Private Member Functions
void GetEnv (int env, const char *sec, const char *key, QString ini)
float GetPrivateProfileFloat (const char *sec, const char *key, float def, QString file)
int GetPrivateProfileInt (const char *sec, const char *key, int def, QString file)
std::size_t GetPrivateProfileString (const char *sec, const char *key, const char *def, char *buffer, std::size_t size, QString file)
int LongestEnv ()
float LoudestEnv ()
void UpdateEnv (int e, long t)
float waveform (float ph, int form)
Detailed Description
Definition at line 38 of file DrumSynth.h.
Constructor & Destructor Documentation
DrumSynth()
lmms::DrumSynth::DrumSynth () default
References file.
Member Function Documentation
GetDSFileSamples()
int lmms::DrumSynth::GetDSFileSamples (QString dsfile, int16_t *& wave, int channels, sample_rate_t Fs)
Definition at line 284 of file DrumSynth.cpp.
References lmms::chkOn, lmms::clippoint, lmms::dENV, lmms::DF, lmms::ENV, lmms::envData, lmms::fastPow10f(), GetEnv(), GetPrivateProfileFloat(), GetPrivateProfileInt(), GetPrivateProfileString(), i, j, LongestEnv(), LoudestEnv(), lmms::MAX, lmms::mem_b, lmms::mem_n, lmms::mem_o, lmms::mem_t, lmms::mem_time, lmms::mem_tune, lmms::NEXTT, lmms::phi, lmms::PNT, lmms::sliLev, lmms::timestretch, UpdateEnv(), waveform(), lmms::wavemode, and lmms::wavewords.
GetEnv()
void lmms::DrumSynth::GetEnv (int env, const char * sec, const char * key, QString ini) private
Definition at line 127 of file DrumSynth.cpp.
References lmms::envData, lmms::envpts, GetPrivateProfileString(), i, and lmms::MAX.
Referenced by GetDSFileSamples().
GetPrivateProfileFloat()
float lmms::DrumSynth::GetPrivateProfileFloat (const char * sec, const char * key, float def, QString file) private
Definition at line 264 of file DrumSynth.cpp.
References file, and GetPrivateProfileString().
Referenced by GetDSFileSamples().
GetPrivateProfileInt()
int lmms::DrumSynth::GetPrivateProfileInt (const char * sec, const char * key, int def, QString file) private
Definition at line 249 of file DrumSynth.cpp.
References file, GetPrivateProfileString(), and i.
Referenced by GetDSFileSamples().
GetPrivateProfileString()
std::size_t lmms::DrumSynth::GetPrivateProfileString (const char * sec, const char * key, const char * def, char * buffer, std::size_t size, QString file) private
Definition at line 189 of file DrumSynth.cpp.
References file, and k.
Referenced by GetDSFileSamples(), GetEnv(), GetPrivateProfileFloat(), and GetPrivateProfileInt().
LongestEnv()
int lmms::DrumSynth::LongestEnv () private
Definition at line 65 of file DrumSynth.cpp.
References lmms::chkOn, lmms::envData, lmms::envpts, lmms::MAX, and lmms::timestretch.
Referenced by GetDSFileSamples().
LoudestEnv()
float lmms::DrumSynth::LoudestEnv () private
Definition at line 92 of file DrumSynth.cpp.
References lmms::chkOn, i, and lmms::sliLev.
Referenced by GetDSFileSamples().
UpdateEnv()
void lmms::DrumSynth::UpdateEnv (int e, long t) private
Definition at line 108 of file DrumSynth.cpp.
References lmms::dENV, lmms::ENV, lmms::envData, lmms::envpts, lmms::NEXTT, lmms::PNT, and lmms::timestretch.
Referenced by GetDSFileSamples().
waveform()
float lmms::DrumSynth::waveform (float ph, int form) private
Definition at line 173 of file DrumSynth.cpp.
References lmms::absFraction().
Referenced by GetDSFileSamples().
The documentation for this class was generated from the following files:
include/DrumSynth.h
src/core/DrumSynth.cpp