LMMS: lmms::gui::AboutDialog Class Reference
lmms::gui::AboutDialog Class Reference
#include <AboutDialog.h>
Public Member Functions
AboutDialog (QWidget *parent=0)
Detailed Description
Definition at line 35 of file AboutDialog.h.
Constructor & Destructor Documentation
AboutDialog()
lmms::gui::AboutDialog::AboutDialog (QWidget * parent = 0)
Definition at line 35 of file AboutDialog.cpp.
References AboutDialog(), lmms::embed::getIconPixmap(), lmms::embed::getText(), LMMS_BUILDCONF_COMPILER_VERSION, LMMS_BUILDCONF_MACHINE, and LMMS_BUILDCONF_PLATFORM.
Referenced by AboutDialog().
The documentation for this class was generated from the following files:
include/AboutDialog.h
src/gui/modals/AboutDialog.cpp