LMMS: src/3rdparty/jack2/common/JackServerAPI.cpp File Reference
JackServerAPI.cpp File Reference
#include "JackSystemDeps.h"
#include "JackGraphManager.h"
#include "JackInternalClient.h"
#include "JackServer.h"
#include "JackDebugClient.h"
#include "JackServerGlobals.h"
#include "JackTools.h"
#include "JackCompilerDeps.h"
#include "JackLockedEngine.h"
Functions
SERVER_EXPORT int jack_client_close (jack_client_t *client)
Disconnects an external client from a JACK server.
jack_client_t * jack_client_new_aux (const char *client_name, jack_options_t options, jack_status_t *status)
SERVER_EXPORT jack_client_t * jack_client_open (const char *client_name, jack_options_t options, jack_status_t *status,...)
Open an external client session with a JACK server.
jack_client_t * jack_client_open_aux (const char *client_name, jack_options_t options, jack_status_t *status, va_list ap)
SERVER_EXPORT int jack_get_client_pid (const char *name)
Function Documentation
jack_client_new_aux()
jack_client_t * jack_client_new_aux (const char * client_name, jack_options_t options, jack_status_t * status)
Definition at line 50 of file JackServerAPI.cpp.
References client(), Jack::JackLibGlobals::Destroy(), Jack::JackServerGlobals::Destroy(), Jack::JackServerGlobals::fInstance, Jack::GetSynchroTable(), Jack::JackLibGlobals::Init(), Jack::JackServerGlobals::Init(), JACK_DEBUG, jack_error, jack_log(), jack_varargs_init(), JackFailure, JackInvalidOption, JackOpenOptions, JackServerError, jack_varargs_t::server_name, jack_varargs_t::session_id, and try_start_server().
Referenced by jack_client_new().
jack_client_open_aux()
jack_client_t * jack_client_open_aux (const char * client_name, jack_options_t options, jack_status_t * status, va_list ap)
Definition at line 101 of file JackServerAPI.cpp.
References client(), Jack::JackServerGlobals::Destroy(), Jack::JackServerGlobals::fInstance, Jack::GetSynchroTable(), Jack::JackServerGlobals::Init(), JACK_DEBUG, jack_error, jack_log(), jack_varargs_parse(), JackFailure, JackInvalidOption, JackOpenOptions, JackServerError, jack_varargs_t::server_name, and jack_varargs_t::session_id.
Referenced by jack_client_open().