LMMS: Jack::JackRequestDecoder Class Reference
Jack::JackRequestDecoder Class Reference
Request decoder.
#include <JackRequestDecoder.h>
Public Member Functions
JackRequestDecoder (JackServer *server, JackClientHandlerInterface *handler)
virtual ~JackRequestDecoder ()
int HandleRequest (detail::JackChannelTransactionInterface *socket, int type)
Private Attributes
JackClientHandlerInterface * fHandler
JackServer * fServer
Detailed Description
Request decoder.
Definition at line 46 of file JackRequestDecoder.h.
Constructor & Destructor Documentation
JackRequestDecoder()
Jack::JackRequestDecoder::JackRequestDecoder (JackServer * server, JackClientHandlerInterface * handler)
Definition at line 38 of file JackRequestDecoder.cpp.
References fHandler, fServer, and server().
~JackRequestDecoder()
Jack::JackRequestDecoder::~JackRequestDecoder () virtual
Definition at line 42 of file JackRequestDecoder.cpp.
Member Function Documentation
HandleRequest()
int Jack::JackRequestDecoder::HandleRequest (detail::JackChannelTransactionInterface * socket, int type)
Definition at line 45 of file JackRequestDecoder.cpp.
References CheckRead, CheckWrite, CheckWriteName, CheckWriteRefNum, Jack::JackPortRegisterRequest::fBufferSize, Jack::JackSetBufferSizeRequest::fBufferSize, Jack::JackPropertyChangeNotifyRequest::fChange, Jack::JackSetTimebaseCallbackRequest::fConditionnal, Jack::JackInternalClientLoadRequest::fDllName, Jack::JackPortConnectNameRequest::fDst, Jack::JackPortConnectRequest::fDst, Jack::JackPortDisconnectNameRequest::fDst, Jack::JackPortDisconnectRequest::fDst, Jack::JackSessionNotifyRequest::fDst, Jack::JackSessionNotifyRequest::fEventType, Jack::JackPortRegisterRequest::fFlags, fHandler, Jack::JackGetInternalClientNameRequest::fIntRefNum, Jack::JackInternalClientHandleResult::fIntRefNum, Jack::JackInternalClientLoadResult::fIntRefNum, Jack::JackInternalClientUnloadRequest::fIntRefNum, Jack::JackActivateRequest::fIsRealTime, Jack::JackPropertyChangeNotifyRequest::fKey, Jack::JackInternalClientLoadRequest::fLoadInitName, Jack::JackClientCheckRequest::fName, Jack::JackClientCheckResult::fName, Jack::JackClientHasSessionCallbackRequest::fName, Jack::JackClientNameResult::fName, Jack::JackGetInternalClientNameResult::fName, Jack::JackGetUUIDRequest::fName, Jack::JackInternalClientHandleRequest::fName, Jack::JackInternalClientLoadRequest::fName, Jack::JackPortRegisterRequest::fName, Jack::JackPortRenameRequest::fName, Jack::JackReserveNameRequest::fName, Jack::JackClientNotificationRequest::fNotify, Jack::JackSetFreeWheelRequest::fOnOff, Jack::JackClientCheckRequest::fOpen, Jack::JackClientCheckRequest::fOptions, Jack::JackInternalClientLoadRequest::fOptions, Jack::JackSessionNotifyRequest::fPath, Jack::JackPortRenameRequest::fPort, Jack::JackPortRegisterResult::fPortIndex, Jack::JackPortUnRegisterRequest::fPortIndex, Jack::JackPortRegisterRequest::fPortType, Jack::JackClientCheckRequest::fProtocol, Jack::JackActivateRequest::fRefNum, Jack::JackClientCloseRequest::fRefNum, Jack::JackClientNotificationRequest::fRefNum, Jack::JackDeactivateRequest::fRefNum, Jack::JackPortConnectNameRequest::fRefNum, Jack::JackPortConnectRequest::fRefNum, Jack::JackPortDisconnectNameRequest::fRefNum, Jack::JackPortDisconnectRequest::fRefNum, Jack::JackPortRegisterRequest::fRefNum, Jack::JackPortRenameRequest::fRefNum, Jack::JackPortUnRegisterRequest::fRefNum, Jack::JackReleaseTimebaseRequest::fRefNum, Jack::JackSessionNotifyRequest::fRefNum, Jack::JackSessionReplyRequest::fRefNum, Jack::JackSetTimebaseCallbackRequest::fRefNum, Jack::JackResult::fResult, fServer, Jack::JackPortConnectNameRequest::fSrc, Jack::JackPortConnectRequest::fSrc, Jack::JackPortDisconnectNameRequest::fSrc, Jack::JackPortDisconnectRequest::fSrc, Jack::JackClientCheckResult::fStatus, Jack::JackInternalClientHandleResult::fStatus, Jack::JackInternalClientLoadResult::fStatus, Jack::JackInternalClientUnloadResult::fStatus, Jack::JackPropertyChangeNotifyRequest::fSubject, Jack::JackRequest::fType, Jack::JackClientCheckRequest::fUUID, Jack::JackGetClientNameRequest::fUUID, Jack::JackInternalClientLoadRequest::fUUID, Jack::JackReserveNameRequest::fUUID, Jack::JackUUIDResult::fUUID, Jack::JackClientNotificationRequest::fValue, HandleRequest(), jack_error, jack_log(), Jack::JackRequest::kActivateClient, Jack::JackRequest::kClientCheck, Jack::JackRequest::kClientClose, Jack::JackRequest::kClientHasSessionCallback, Jack::JackRequest::kClientOpen, Jack::JackRequest::kComputeTotalLatencies, Jack::JackRequest::kConnectNamePorts, Jack::JackRequest::kConnectPorts, Jack::JackRequest::kDeactivateClient, Jack::JackRequest::kDisconnectNamePorts, Jack::JackRequest::kDisconnectPorts, Jack::JackRequest::kGetClientByUUID, Jack::JackRequest::kGetInternalClientName, Jack::JackRequest::kGetUUIDByClient, Jack::JackRequest::kInternalClientHandle, Jack::JackRequest::kInternalClientLoad, Jack::JackRequest::kInternalClientUnload, Jack::JackRequest::kNotification, Jack::JackRequest::kPortRename, Jack::JackRequest::kPropertyChangeNotify, Jack::kQUIT, Jack::JackRequest::kRegisterPort, Jack::JackRequest::kReleaseTimebase, Jack::JackRequest::kReserveClientName, Jack::JackRequest::kSessionNotify, Jack::JackRequest::kSessionReply, Jack::JackRequest::kSetBufferSize, Jack::JackRequest::kSetFreeWheel, Jack::JackRequest::kSetTimebaseCallback, Jack::JackRequest::kUnRegisterPort, and Jack::JackRequest::Read().
Referenced by HandleRequest().
Member Data Documentation
fHandler
JackClientHandlerInterface* Jack::JackRequestDecoder::fHandler private
Definition at line 51 of file JackRequestDecoder.h.
Referenced by JackRequestDecoder(), and HandleRequest().
fServer
JackServer* Jack::JackRequestDecoder::fServer private
Definition at line 50 of file JackRequestDecoder.h.
Referenced by JackRequestDecoder(), and HandleRequest().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackRequestDecoder.h
src/3rdparty/jack2/common/JackRequestDecoder.cpp