LMMS: lmms::DspEffectLibrary::StereoEnhancer Class Reference
lmms::DspEffectLibrary::StereoEnhancer Class Reference
#include <DspEffectLibrary.h>
Public Member Functions
StereoEnhancer (float wideCoeff)
void nextSample (sample_t &inLeft, sample_t &inRight)
void setWideCoeff (float wideCoeff)
float wideCoeff ()
Private Attributes
float m_wideCoeff
Additional Inherited Members
Public Types inherited from lmms::DspEffectLibrary::StereoBase< StereoEnhancer >
using bypassType
Static Public Member Functions inherited from lmms::DspEffectLibrary::StereoBase< StereoEnhancer >
static void process (sample_t **_buf, const f_cnt_t _frames)
Detailed Description
Definition at line 312 of file DspEffectLibrary.h.
Constructor & Destructor Documentation
StereoEnhancer()
lmms::DspEffectLibrary::StereoEnhancer::StereoEnhancer (float wideCoeff) inline
Definition at line 315 of file DspEffectLibrary.h.
References m_wideCoeff, and wideCoeff().
Member Function Documentation
nextSample()
void lmms::DspEffectLibrary::StereoEnhancer::nextSample (sample_t & inLeft, sample_t & inRight) inline
Definition at line 330 of file DspEffectLibrary.h.
References m_wideCoeff.
setWideCoeff()
void lmms::DspEffectLibrary::StereoEnhancer::setWideCoeff (float wideCoeff) inline
Definition at line 320 of file DspEffectLibrary.h.
References m_wideCoeff, and wideCoeff().
wideCoeff()
float lmms::DspEffectLibrary::StereoEnhancer::wideCoeff () inline
Definition at line 325 of file DspEffectLibrary.h.
References m_wideCoeff.
Referenced by StereoEnhancer(), and setWideCoeff().
Member Data Documentation
m_wideCoeff
float lmms::DspEffectLibrary::StereoEnhancer::m_wideCoeff private
Definition at line 339 of file DspEffectLibrary.h.
Referenced by StereoEnhancer(), nextSample(), setWideCoeff(), and wideCoeff().
The documentation for this class was generated from the following file:
include/DspEffectLibrary.h