LMMS: lmms::SampleThumbnail::Thumbnail Class Reference
lmms::SampleThumbnail::Thumbnail Class Reference
Classes
struct Peak
Public Member Functions
Thumbnail ()=default
Thumbnail (const float *buffer, size_t size, size_t width)
Thumbnail (std::vector< Peak > peaks, double samplesPerPeak)
Peak * data ()
Peak & operator[] (size_t index)
const Peak & operator[] (size_t index) const
double samplesPerPeak () const
int width () const
Thumbnail zoomOut (float factor) const
Private Attributes
std::vector< Peak > m_peaks
double m_samplesPerPeak = 0.0
Detailed Description
Definition at line 78 of file SampleThumbnail.h.
Constructor & Destructor Documentation
Thumbnail() [1/3]
lmms::SampleThumbnail::Thumbnail::Thumbnail () default
References Thumbnail(), samplesPerPeak(), width(), and zoomOut().
Referenced by Thumbnail(), and zoomOut().
Thumbnail() [2/3]
lmms::SampleThumbnail::Thumbnail::Thumbnail (std::vector< Peak > peaks, double samplesPerPeak)
Definition at line 40 of file SampleThumbnail.cpp.
References m_peaks, m_samplesPerPeak, and samplesPerPeak().
Thumbnail() [3/3]
lmms::SampleThumbnail::Thumbnail::Thumbnail (const float * buffer, size_t size, size_t width)
Definition at line 46 of file SampleThumbnail.cpp.
References m_peaks, m_samplesPerPeak, max, min, and width().
Member Function Documentation
data()
Peak * lmms::SampleThumbnail::Thumbnail::data () inline
Definition at line 110 of file SampleThumbnail.h.
References m_peaks.
operator[]() [1/2]
Peak & lmms::SampleThumbnail::Thumbnail::operator[] (size_t index) inline
Definition at line 111 of file SampleThumbnail.h.
References m_peaks.
operator[]() [2/2]
const Peak & lmms::SampleThumbnail::Thumbnail::operator[] (size_t index) const inline
Definition at line 112 of file SampleThumbnail.h.
References m_peaks.
samplesPerPeak()
double lmms::SampleThumbnail::Thumbnail::samplesPerPeak () const inline
Definition at line 115 of file SampleThumbnail.h.
References m_samplesPerPeak.
Referenced by Thumbnail(), and Thumbnail().
width()
int lmms::SampleThumbnail::Thumbnail::width () const inline
Definition at line 114 of file SampleThumbnail.h.
References m_peaks.
Referenced by Thumbnail(), and Thumbnail().
zoomOut()
SampleThumbnail::Thumbnail lmms::SampleThumbnail::Thumbnail::zoomOut (float factor) const
Definition at line 59 of file SampleThumbnail.cpp.
References Thumbnail(), m_peaks, and m_samplesPerPeak.
Referenced by Thumbnail().
Member Data Documentation
m_peaks
std::vector<Peak> lmms::SampleThumbnail::Thumbnail::m_peaks private
Definition at line 118 of file SampleThumbnail.h.
Referenced by Thumbnail(), Thumbnail(), data(), operator[](), operator[](), width(), and zoomOut().
m_samplesPerPeak
double lmms::SampleThumbnail::Thumbnail::m_samplesPerPeak = 0.0 private
Definition at line 119 of file SampleThumbnail.h.
Referenced by Thumbnail(), Thumbnail(), samplesPerPeak(), and zoomOut().
The documentation for this class was generated from the following files:
include/SampleThumbnail.h
src/gui/SampleThumbnail.cpp