LMMS: lmms::gui::MixerChannelView Class Reference
lmms::gui::MixerChannelView Class Reference
#include <MixerChannelView.h>
Public Slots
void randomizeColor ()
void renameChannel ()
void resetColor ()
void selectColor ()
Public Member Functions
MixerChannelView (QWidget *parent, MixerView *mixerView, int channelIndex)
QBrush backgroundActive () const
int channelIndex () const
void contextMenuEvent (QContextMenuEvent *) override
Fader * fader () const
void keyPressEvent (QKeyEvent *ke) override
void mouseDoubleClickEvent (QMouseEvent *) override
void mousePressEvent (QMouseEvent *) override
void paintEvent (QPaintEvent *event) override
void reset ()
void setBackgroundActive (const QBrush &c)
void setChannelIndex (int index)
void setStrokeInnerActive (const QColor &c)
void setStrokeInnerInactive (const QColor &c)
void setStrokeOuterActive (const QColor &c)
void setStrokeOuterInactive (const QColor &c)
QColor strokeInnerActive () const
QColor strokeInnerInactive () const
QColor strokeOuterActive () const
QColor strokeOuterInactive () const
Properties
QBrush backgroundActive
QColor strokeInnerActive
QColor strokeInnerInactive
QColor strokeOuterActive
QColor strokeOuterInactive
Private Slots
void moveChannelLeft ()
void moveChannelRight ()
void removeChannel ()
void removeUnusedChannels ()
void renameFinished ()
Private Member Functions
bool confirmRemoval (int index)
QString elideName (const QString &name)
auto isMasterChannel () const -> bool
MixerChannel * mixerChannel () const
Private Attributes
QBrush m_backgroundActive
int m_channelIndex = 0
LcdWidget * m_channelNumberLcd
EffectRackView * m_effectRackView
Fader * m_fader
bool m_inRename = false
MixerView * m_mixerView
AutomatableButton * m_muteButton
PeakIndicator * m_peakIndicator = nullptr
QLabel * m_receiveArrow
QStackedWidget * m_receiveArrowOrSendButton
int m_receiveArrowStackedIndex = -1
QLineEdit * m_renameLineEdit
QGraphicsView * m_renameLineEditView
QLabel * m_sendArrow
SendButtonIndicator * m_sendButton
int m_sendButtonStackedIndex = -1
Knob * m_sendKnob
AutomatableButton * m_soloButton
QColor m_strokeInnerActive
QColor m_strokeInnerInactive
QColor m_strokeOuterActive
QColor m_strokeOuterInactive
Friends
class MixerView
Detailed Description
Definition at line 50 of file MixerChannelView.h.
Constructor & Destructor Documentation
MixerChannelView()
lmms::gui::MixerChannelView::MixerChannelView (QWidget * parent, MixerView * mixerView, int channelIndex)
Definition at line 56 of file MixerChannelView.cpp.
References lmms::gui::adjustedToPixelSize(), lmms::gui::Bright26, channelIndex(), lmms::gui::EffectRackView::DEFAULT_WIDTH, lmms::embed::getIconPixmap(), LARGE_FONT_SIZE, m_channelIndex, m_channelNumberLcd, m_effectRackView, m_fader, m_mixerView, m_muteButton, m_peakIndicator, lmms::gui::MixerView::m_racksWidget, m_receiveArrow, m_receiveArrowOrSendButton, m_receiveArrowStackedIndex, m_renameLineEdit, m_renameLineEditView, m_sendArrow, m_sendButton, m_sendButtonStackedIndex, m_sendKnob, m_soloButton, lmms::Engine::mixer(), mixerChannel(), lmms::Mixer::mixerChannel(), MixerView, lmms::gui::Fader::peakChanged(), renameFinished(), and lmms::gui::PeakIndicator::updatePeak().
Member Function Documentation
backgroundActive()
QBrush lmms::gui::MixerChannelView::backgroundActive () const inline
Definition at line 70 of file MixerChannelView.h.
References m_backgroundActive.
channelIndex()
int lmms::gui::MixerChannelView::channelIndex () const inline
Definition at line 67 of file MixerChannelView.h.
References channelIndex(), and m_channelIndex.
Referenced by MixerChannelView(), channelIndex(), and lmms::gui::MixerView::setCurrentMixerChannel().
confirmRemoval()
bool lmms::gui::MixerChannelView::confirmRemoval (int index) private
Definition at line 330 of file MixerChannelView.cpp.
References lmms::gui::getGUI(), lmms::ConfigManager::inst(), lmms::ConfigManager::setValue(), and lmms::ConfigManager::value().
Referenced by removeChannel().
contextMenuEvent()
void lmms::gui::MixerChannelView::contextMenuEvent (QContextMenuEvent *) override
Definition at line 163 of file MixerChannelView.cpp.
References lmms::embed::getIconPixmap(), isMasterChannel(), mixerChannel(), moveChannelLeft(), moveChannelRight(), randomizeColor(), removeChannel(), removeUnusedChannels(), renameChannel(), resetColor(), and selectColor().
elideName()
QString lmms::gui::MixerChannelView::elideName (const QString & name) private
Definition at line 390 of file MixerChannelView.cpp.
References m_renameLineEdit.
Referenced by renameFinished(), and setChannelIndex().
fader()
Fader * lmms::gui::MixerChannelView::fader () const inline
Definition at line 85 of file MixerChannelView.h.
References m_fader.
isMasterChannel()
auto lmms::gui::MixerChannelView::isMasterChannel () const->bool inline private
Definition at line 104 of file MixerChannelView.h.
References m_channelIndex.
Referenced by contextMenuEvent().
keyPressEvent()
void lmms::gui::MixerChannelView::keyPressEvent (QKeyEvent * ke) override
Definition at line 234 of file MixerChannelView.cpp.
References m_inRename, and renameFinished().
mixerChannel()
MixerChannel * lmms::gui::MixerChannelView::mixerChannel () const private
Definition at line 398 of file MixerChannelView.cpp.
References m_channelIndex, lmms::Engine::mixer(), and lmms::Mixer::mixerChannel().
Referenced by MixerChannelView(), contextMenuEvent(), paintEvent(), randomizeColor(), renameChannel(), renameFinished(), resetColor(), selectColor(), and setChannelIndex().
mouseDoubleClickEvent()
void lmms::gui::MixerChannelView::mouseDoubleClickEvent (QMouseEvent *) override
Definition at line 229 of file MixerChannelView.cpp.
References renameChannel().
mousePressEvent()
void lmms::gui::MixerChannelView::mousePressEvent (QMouseEvent *) override
Definition at line 224 of file MixerChannelView.cpp.
References m_mixerView.
moveChannelLeft
void lmms::gui::MixerChannelView::moveChannelLeft () private slot
Definition at line 378 of file MixerChannelView.cpp.
References lmms::gui::getGUI(), m_channelIndex, lmms::gui::GuiApplication::mixerView(), and lmms::gui::MixerView::moveChannelLeft().
Referenced by contextMenuEvent().
moveChannelRight
void lmms::gui::MixerChannelView::moveChannelRight () private slot
Definition at line 384 of file MixerChannelView.cpp.
References lmms::gui::getGUI(), m_channelIndex, lmms::gui::GuiApplication::mixerView(), and lmms::gui::MixerView::moveChannelRight().
Referenced by contextMenuEvent().
paintEvent()
void lmms::gui::MixerChannelView::paintEvent (QPaintEvent * event) override
Definition at line 198 of file MixerChannelView.cpp.
References backgroundActive, m_mixerView, mixerChannel(), strokeInnerActive, strokeInnerInactive, strokeOuterActive, and strokeOuterInactive.
randomizeColor
void lmms::gui::MixerChannelView::randomizeColor () slot
Definition at line 322 of file MixerChannelView.cpp.
References lmms::gui::ColorChooser::getPalette(), lmms::Engine::getSong(), lmms::gui::ColorChooser::Mixer, mixerChannel(), and lmms::Song::setModified().
Referenced by contextMenuEvent().
removeChannel
void lmms::gui::MixerChannelView::removeChannel () private slot
Definition at line 365 of file MixerChannelView.cpp.
References confirmRemoval(), lmms::gui::MixerView::deleteChannel(), lmms::gui::getGUI(), m_channelIndex, and lmms::gui::GuiApplication::mixerView().
Referenced by contextMenuEvent().
removeUnusedChannels
void lmms::gui::MixerChannelView::removeUnusedChannels () private slot
Definition at line 372 of file MixerChannelView.cpp.
References lmms::gui::MixerView::deleteUnusedChannels(), lmms::gui::getGUI(), and lmms::gui::GuiApplication::mixerView().
Referenced by contextMenuEvent().
renameChannel
void lmms::gui::MixerChannelView::renameChannel () slot
Definition at line 261 of file MixerChannelView.cpp.
References m_channelNumberLcd, m_inRename, m_renameLineEdit, m_renameLineEditView, and mixerChannel().
Referenced by contextMenuEvent(), and mouseDoubleClickEvent().
renameFinished
void lmms::gui::MixerChannelView::renameFinished () private slot
Definition at line 276 of file MixerChannelView.cpp.
References elideName(), lmms::Engine::getSong(), m_channelNumberLcd, m_inRename, m_renameLineEdit, mixerChannel(), and lmms::Song::setModified().
Referenced by MixerChannelView(), and keyPressEvent().
reset()
void lmms::gui::MixerChannelView::reset ()
Definition at line 403 of file MixerChannelView.cpp.
References m_peakIndicator.
resetColor
void lmms::gui::MixerChannelView::resetColor () slot
Definition at line 299 of file MixerChannelView.cpp.
References lmms::Engine::getSong(), mixerChannel(), lmms::MixerChannel::setColor(), and lmms::Song::setModified().
Referenced by contextMenuEvent().
selectColor
void lmms::gui::MixerChannelView::selectColor () slot
Definition at line 306 of file MixerChannelView.cpp.
References backgroundActive, lmms::Engine::getSong(), lmms::gui::ColorChooser::Mixer, mixerChannel(), lmms::Song::setModified(), and lmms::gui::ColorChooser::withPalette().
Referenced by contextMenuEvent().
setBackgroundActive()
void lmms::gui::MixerChannelView::setBackgroundActive (const QBrush & c) inline
Definition at line 71 of file MixerChannelView.h.
References m_backgroundActive.
setChannelIndex()
void lmms::gui::MixerChannelView::setChannelIndex (int index)
Definition at line 249 of file MixerChannelView.cpp.
References elideName(), m_channelIndex, m_channelNumberLcd, m_effectRackView, m_fader, m_muteButton, m_renameLineEdit, m_soloButton, lmms::Engine::mixer(), mixerChannel(), and lmms::Mixer::mixerChannel().
setStrokeInnerActive()
void lmms::gui::MixerChannelView::setStrokeInnerActive (const QColor & c) inline
Definition at line 80 of file MixerChannelView.h.
References m_strokeInnerActive.
setStrokeInnerInactive()
void lmms::gui::MixerChannelView::setStrokeInnerInactive (const QColor & c) inline
Definition at line 83 of file MixerChannelView.h.
References m_strokeInnerInactive.
setStrokeOuterActive()
void lmms::gui::MixerChannelView::setStrokeOuterActive (const QColor & c) inline
Definition at line 74 of file MixerChannelView.h.
References m_strokeOuterActive.
setStrokeOuterInactive()
void lmms::gui::MixerChannelView::setStrokeOuterInactive (const QColor & c) inline
Definition at line 77 of file MixerChannelView.h.
References m_strokeOuterInactive.
strokeInnerActive()
QColor lmms::gui::MixerChannelView::strokeInnerActive () const inline
Definition at line 79 of file MixerChannelView.h.
References m_strokeInnerActive.
strokeInnerInactive()
QColor lmms::gui::MixerChannelView::strokeInnerInactive () const inline
Definition at line 82 of file MixerChannelView.h.
References m_strokeInnerInactive.
strokeOuterActive()
QColor lmms::gui::MixerChannelView::strokeOuterActive () const inline
Definition at line 73 of file MixerChannelView.h.
References m_strokeOuterActive.
strokeOuterInactive()
QColor lmms::gui::MixerChannelView::strokeOuterInactive () const inline
Definition at line 76 of file MixerChannelView.h.
References m_strokeOuterInactive.
Friends And Related Symbol Documentation
MixerView
friend class MixerView friend
Definition at line 133 of file MixerChannelView.h.
References MixerView.
Referenced by MixerChannelView(), and MixerView.
Member Data Documentation
m_backgroundActive
QBrush lmms::gui::MixerChannelView::m_backgroundActive private
Definition at line 127 of file MixerChannelView.h.
Referenced by backgroundActive(), and setBackgroundActive().
m_channelIndex
int lmms::gui::MixerChannelView::m_channelIndex = 0 private
Definition at line 124 of file MixerChannelView.h.
Referenced by MixerChannelView(), channelIndex(), isMasterChannel(), mixerChannel(), moveChannelLeft(), moveChannelRight(), removeChannel(), and setChannelIndex().
m_channelNumberLcd
LcdWidget* lmms::gui::MixerChannelView::m_channelNumberLcd private
Definition at line 114 of file MixerChannelView.h.
Referenced by MixerChannelView(), renameChannel(), renameFinished(), and setChannelIndex().
m_effectRackView
EffectRackView* lmms::gui::MixerChannelView::m_effectRackView private
Definition at line 122 of file MixerChannelView.h.
Referenced by MixerChannelView(), and setChannelIndex().
m_fader
Fader* lmms::gui::MixerChannelView::m_fader private
Definition at line 121 of file MixerChannelView.h.
Referenced by MixerChannelView(), fader(), and setChannelIndex().
m_inRename
bool lmms::gui::MixerChannelView::m_inRename = false private
Definition at line 125 of file MixerChannelView.h.
Referenced by keyPressEvent(), renameChannel(), and renameFinished().
m_mixerView
MixerView* lmms::gui::MixerChannelView::m_mixerView private
Definition at line 123 of file MixerChannelView.h.
Referenced by MixerChannelView(), mousePressEvent(), and paintEvent().
m_muteButton
AutomatableButton* lmms::gui::MixerChannelView::m_muteButton private
Definition at line 118 of file MixerChannelView.h.
Referenced by MixerChannelView(), and setChannelIndex().
m_peakIndicator
PeakIndicator* lmms::gui::MixerChannelView::m_peakIndicator = nullptr private
Definition at line 120 of file MixerChannelView.h.
Referenced by MixerChannelView(), and reset().
m_receiveArrow
QLabel* lmms::gui::MixerChannelView::m_receiveArrow private
Definition at line 108 of file MixerChannelView.h.
Referenced by MixerChannelView().
m_receiveArrowOrSendButton
QStackedWidget* lmms::gui::MixerChannelView::m_receiveArrowOrSendButton private
Definition at line 109 of file MixerChannelView.h.
Referenced by MixerChannelView().
m_receiveArrowStackedIndex
int lmms::gui::MixerChannelView::m_receiveArrowStackedIndex = -1 private
Definition at line 110 of file MixerChannelView.h.
Referenced by MixerChannelView().
m_renameLineEdit
QLineEdit* lmms::gui::MixerChannelView::m_renameLineEdit private
Definition at line 115 of file MixerChannelView.h.
Referenced by MixerChannelView(), elideName(), renameChannel(), renameFinished(), and setChannelIndex().
m_renameLineEditView
QGraphicsView* lmms::gui::MixerChannelView::m_renameLineEditView private
Definition at line 116 of file MixerChannelView.h.
Referenced by MixerChannelView(), and renameChannel().
m_sendArrow
QLabel* lmms::gui::MixerChannelView::m_sendArrow private
Definition at line 117 of file MixerChannelView.h.
Referenced by MixerChannelView().
m_sendButton
SendButtonIndicator* lmms::gui::MixerChannelView::m_sendButton private
Definition at line 107 of file MixerChannelView.h.
Referenced by MixerChannelView().
m_sendButtonStackedIndex
int lmms::gui::MixerChannelView::m_sendButtonStackedIndex = -1 private
Definition at line 111 of file MixerChannelView.h.
Referenced by MixerChannelView().
m_sendKnob
Knob* lmms::gui::MixerChannelView::m_sendKnob private
Definition at line 113 of file MixerChannelView.h.
Referenced by MixerChannelView().
m_soloButton
AutomatableButton* lmms::gui::MixerChannelView::m_soloButton private
Definition at line 119 of file MixerChannelView.h.
Referenced by MixerChannelView(), and setChannelIndex().
m_strokeInnerActive
QColor lmms::gui::MixerChannelView::m_strokeInnerActive private
Definition at line 130 of file MixerChannelView.h.
Referenced by setStrokeInnerActive(), and strokeInnerActive().
m_strokeInnerInactive
QColor lmms::gui::MixerChannelView::m_strokeInnerInactive private
Definition at line 131 of file MixerChannelView.h.
Referenced by setStrokeInnerInactive(), and strokeInnerInactive().
m_strokeOuterActive
QColor lmms::gui::MixerChannelView::m_strokeOuterActive private
Definition at line 128 of file MixerChannelView.h.
Referenced by setStrokeOuterActive(), and strokeOuterActive().
m_strokeOuterInactive
QColor lmms::gui::MixerChannelView::m_strokeOuterInactive private
Definition at line 129 of file MixerChannelView.h.
Referenced by setStrokeOuterInactive(), and strokeOuterInactive().
Property Documentation
backgroundActive
QBrush lmms::gui::MixerChannelView::backgroundActive read write
Definition at line 53 of file MixerChannelView.h.
Referenced by paintEvent(), and selectColor().
strokeInnerActive
QColor lmms::gui::MixerChannelView::strokeInnerActive read write
Definition at line 56 of file MixerChannelView.h.
Referenced by paintEvent().
strokeInnerInactive
QColor lmms::gui::MixerChannelView::strokeInnerInactive read write
Definition at line 57 of file MixerChannelView.h.
Referenced by paintEvent().
strokeOuterActive
QColor lmms::gui::MixerChannelView::strokeOuterActive read write
Definition at line 54 of file MixerChannelView.h.
Referenced by paintEvent().
strokeOuterInactive
QColor lmms::gui::MixerChannelView::strokeOuterInactive read write
Definition at line 55 of file MixerChannelView.h.
Referenced by paintEvent().
The documentation for this class was generated from the following files:
include/MixerChannelView.h
src/gui/MixerChannelView.cpp