LMMS: lmms::gui::PatternEditor Class Reference
lmms::gui::PatternEditor Class Reference
#include <PatternEditor.h>
Public Slots
void addAutomationTrack ()
void addSampleTrack ()
void addSteps ()
void cloneClip ()
void cloneSteps ()
void removeSteps ()
void updateMaxSteps ()
Public Slots inherited from lmms::gui::TrackContainerView
lmms::gui::TrackView * createTrackView (lmms::Track *_t)
void deleteTrackView (lmms::gui::TrackView *_tv)
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void realignTracks ()
void stopRubberBand ()
stopRubberBand Removes the rubber band from display when finished with.
Public Member Functions
PatternEditor (PatternStore *ps)
bool fixedClips () const override
void loadSettings (const QDomElement &element) override
void removeViewsForPattern (int pattern)
void saveSettings (QDomDocument &doc, QDomElement &element) override
Public Member Functions inherited from lmms::gui::TrackContainerView
TrackContainerView (TrackContainer *tc)
~TrackContainerView () override
TrackView * addTrackView (TrackView *_tv)
virtual bool allowRubberband () const
void clearAllTracks ()
QScrollArea * contentWidget ()
const TimePos & currentPosition () const
virtual bool knifeMode () const
void loadSettings (const QDomElement &_this) override
TrackContainer * model ()
const TrackContainer * model () const
void moveTrackView (TrackView *trackView, int indexTo)
void moveTrackViewDown (TrackView *trackView)
void moveTrackViewUp (TrackView *trackView)
QString nodeName () const override
float pixelsPerBar () const
void removeTrackView (TrackView *_tv)
RubberBand * rubberBand () const
bool rubberBandActive () const
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
void scrollToTrackView (TrackView *_tv)
QVector< selectableObject * > selectedObjects ()
void setPixelsPerBar (int ppb)
unsigned int totalHeightOfTracks () const
const TrackView * trackViewAt (const int _y) const
const QList< TrackView * > & trackViews () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Public Member Functions inherited from lmms::SerializingObjectHook
SerializingObjectHook ()
virtual ~SerializingObjectHook ()
Protected Slots
void dropEvent (QDropEvent *de) override
void resizeEvent (QResizeEvent *de) override
void updatePixelsPerBar ()
void updatePosition ()
Private Member Functions
void makeSteps (bool clone)
Private Attributes
tick_t m_maxClipLength
PatternStore * m_ps
TimeLineWidget * m_timeLine
int m_trackHeadWidth
Additional Inherited Members
Signals inherited from lmms::gui::TrackContainerView
void positionChanged (const lmms::TimePos &_pos)
void tracksRealigned ()
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Attributes inherited from lmms::gui::TrackContainerView
TimePos m_currentPosition
Static Protected Attributes inherited from lmms::gui::TrackContainerView
static const int DEFAULT_PIXELS_PER_BAR = 128
Detailed Description
Definition at line 43 of file PatternEditor.h.
Constructor & Destructor Documentation
PatternEditor()
lmms::gui::PatternEditor::PatternEditor (PatternStore * ps)
Definition at line 49 of file PatternEditor.cpp.
References lmms::gui::TrackContainerView::TrackContainerView(), lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT, lmms::Engine::getSong(), lmms::gui::TrackContainerView::m_currentPosition, m_maxClipLength, m_ps, m_timeLine, m_trackHeadWidth, lmms::Song::Pattern, lmms::gui::TrackContainerView::pixelsPerBar(), lmms::gui::TimeLineWidget::positionChanged(), lmms::gui::ModelView::setModel(), lmms::gui::TRACK_OP_WIDTH, lmms::gui::TRACK_OP_WIDTH_COMPACT, lmms::PatternStore::trackUpdated(), updateMaxSteps(), and updatePosition().
Member Function Documentation
addAutomationTrack
void lmms::gui::PatternEditor::addAutomationTrack () slot
Definition at line 116 of file PatternEditor.cpp.
References lmms::Track::Automation, lmms::Track::create(), and lmms::gui::TrackContainerView::model().
addSampleTrack
void lmms::gui::PatternEditor::addSampleTrack () slot
Definition at line 108 of file PatternEditor.cpp.
References lmms::Track::create(), lmms::gui::TrackContainerView::model(), and lmms::Track::Sample.
addSteps
void lmms::gui::PatternEditor::addSteps () slot
Definition at line 77 of file PatternEditor.cpp.
References makeSteps().
cloneClip
void lmms::gui::PatternEditor::cloneClip () slot
Definition at line 253 of file PatternEditor.cpp.
References lmms::Track::clone(), lmms::Track::deleteClips(), lmms::PatternTrack::findPatternTrack(), lmms::Track::lock(), lmms::gui::TrackContainerView::model(), and lmms::Track::unlock().
cloneSteps
void lmms::gui::PatternEditor::cloneSteps () slot
Definition at line 82 of file PatternEditor.cpp.
References makeSteps().
dropEvent
void lmms::gui::PatternEditor::dropEvent (QDropEvent * de) override protected slot
Definition at line 148 of file PatternEditor.cpp.
References lmms::DataFile::content(), lmms::Track::create(), lmms::Track::createClipsForPattern(), lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::Track::deleteClips(), lmms::gui::TrackContainerView::dropEvent(), lmms::Track::getClips(), i, m_ps, lmms::gui::TrackContainerView::model(), and updateMaxSteps().
fixedClips()
bool lmms::gui::PatternEditor::fixedClips () const inline override virtual
Reimplemented from lmms::gui::TrackContainerView.
Definition at line 49 of file PatternEditor.h.
loadSettings()
void lmms::gui::PatternEditor::loadSettings (const QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 139 of file PatternEditor.cpp.
References lmms::gui::MainWindow::restoreWidgetState(), and updateMaxSteps().
makeSteps()
void lmms::gui::PatternEditor::makeSteps (bool clone) private
Definition at line 230 of file PatternEditor.cpp.
References lmms::Track::Instrument, m_ps, lmms::gui::TrackContainerView::model(), lmms::TrackContainer::tracks(), and updateMaxSteps().
Referenced by addSteps(), and cloneSteps().
removeSteps
void lmms::gui::PatternEditor::removeSteps () slot
Definition at line 90 of file PatternEditor.cpp.
References lmms::Track::Instrument, m_ps, lmms::gui::TrackContainerView::model(), lmms::MidiClip::removeSteps(), lmms::TrackContainer::tracks(), and updateMaxSteps().
removeViewsForPattern()
void lmms::gui::PatternEditor::removeViewsForPattern (int pattern)
Definition at line 124 of file PatternEditor.cpp.
References lmms::gui::TrackContainerView::trackViews().
Referenced by lmms::gui::PatternTrackView::~PatternTrackView(), and lmms::gui::PatternTrackView::close().
resizeEvent
void lmms::gui::PatternEditor::resizeEvent (QResizeEvent * de) override protected slot
Definition at line 189 of file PatternEditor.cpp.
References updatePixelsPerBar().
saveSettings()
void lmms::gui::PatternEditor::saveSettings (QDomDocument & doc, QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 134 of file PatternEditor.cpp.
References lmms::gui::MainWindow::saveWidgetState().
updateMaxSteps
void lmms::gui::PatternEditor::updateMaxSteps () slot
Definition at line 213 of file PatternEditor.cpp.
References lmms::Track::Instrument, m_maxClipLength, m_ps, lmms::gui::TrackContainerView::model(), lmms::TrackContainer::tracks(), and updatePixelsPerBar().
Referenced by PatternEditor(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), dropEvent(), loadSettings(), makeSteps(), and removeSteps().
updatePixelsPerBar
void lmms::gui::PatternEditor::updatePixelsPerBar () protected slot
Definition at line 205 of file PatternEditor.cpp.
References m_maxClipLength, m_timeLine, m_trackHeadWidth, lmms::gui::TrackContainerView::pixelsPerBar(), lmms::gui::TrackContainerView::setPixelsPerBar(), and lmms::TimePos::ticksPerBar().
Referenced by resizeEvent(), and updateMaxSteps().
updatePosition
void lmms::gui::PatternEditor::updatePosition () protected slot
Definition at line 195 of file PatternEditor.cpp.
References lmms::gui::TrackContainerView::m_currentPosition, lmms::gui::TrackContainerView::positionChanged(), and lmms::gui::TrackContainerView::trackViews().
Referenced by PatternEditor().
Member Data Documentation
m_maxClipLength
tick_t lmms::gui::PatternEditor::m_maxClipLength private
Definition at line 78 of file PatternEditor.h.
Referenced by PatternEditor(), updateMaxSteps(), and updatePixelsPerBar().
m_ps
PatternStore* lmms::gui::PatternEditor::m_ps private
Definition at line 75 of file PatternEditor.h.
Referenced by PatternEditor(), dropEvent(), makeSteps(), removeSteps(), and updateMaxSteps().
m_timeLine
TimeLineWidget* lmms::gui::PatternEditor::m_timeLine private
Definition at line 76 of file PatternEditor.h.
Referenced by PatternEditor(), and updatePixelsPerBar().
m_trackHeadWidth
int lmms::gui::PatternEditor::m_trackHeadWidth private
Definition at line 77 of file PatternEditor.h.
Referenced by PatternEditor(), and updatePixelsPerBar().
The documentation for this class was generated from the following files:
include/PatternEditor.h
src/gui/editors/PatternEditor.cpp