LMMS: lmms Namespace Reference
lmms Namespace Reference
Namespaces
namespace anonymous_namespace{AudioResampler.cpp}
namespace anonymous_namespace{DataFile.cpp}
namespace anonymous_namespace{SampleDecoder.cpp}
namespace base64
namespace Clipboard
namespace detail
namespace DspEffectLibrary
namespace embed
namespace gui
namespace LocaleHelper
namespace MixHelpers
namespace OscillatorConstants
namespace PathUtil
Classes
class AllpassDelay
class ArrayVector
A container that stores up to a maximum of N elements of type T directly within itself, rather than separately on the heap.
class AudioBusHandle
Job between PlayHandle and MixerChannel.
class AudioDevice
class AudioDummy
class AudioEngine
class AudioEngineProfiler
class AudioEngineWorkerThread
class AudioFileDevice
class AudioFileFlac
class AudioFileWave
class AudioPortAudioSetupUtil
class AudioResampler
A utility class for resampling interleaved audio buffers using various resampling algorithms.
class AudioSampleRecorder
class AutoDetectMidiController
class AutomatableModel
class AutomationClip
class AutomationNode
class AutomationTrack
class BandLimitedWave
class BasicFilters
class BiQuad
class BoolModel
class BufferManager
class Clip
class CombFeedback
class CombFeedbackDualtap
class CombFeedfwd
class ComboBoxModel
class ConfigManager
class ConstModelVisitor
class Controller
class ControllerConnection
class DataFile
class DetuningHelper
class Downsampler
class DrumSynth
class DummyEffect
class DummyEffectControls
class DummyInstrument
class DummyPlugin
class Effect
class EffectChain
class EffectControls
class Engine
class EnvelopeAndLfoParameters
class ExportFilter
class FifoBuffer
class Flags
class FloatModel
class graphModel
2 dimensional function plot
class ImportFilter
class InlineAutomation
class Instrument
class InstrumentFunctionArpeggio
class InstrumentFunctionNoteStacking
class InstrumentLoaderThread
class InstrumentPlayHandle
class InstrumentSoundShaping
class InstrumentTrack
class InterleavedBufferView
Non-owning view for multi-channel interleaved audio data.
class Interval
class IntModel
class JournallingObject
class Keymap
class Ladspa2LMMS
Class responsible for sorting found plugins (by LadspaManager) into categories.
class LadspaControl
class LadspaManager
struct LadspaManagerDescription
class LfoController
class LinearMap
class LinkedModelGroup
Base class for a group of linked models.
class LinkedModelGroups
Container for a group of linked models.
class LinkwitzRiley
class LocklessAllocator
class LocklessAllocatorT
class LocklessList
class LocklessRingBuffer
A convenience layer for a realtime-safe and thread-safe multi-reader ringbuffer.
class LocklessRingBufferReader
Wrapper for lockless ringbuffer reader.
class MeterModel
class Metronome
class MicroTimer
class Microtuner
class MidiClient
class MidiClientRaw
class MidiClip
class MidiController
class MidiDummy
class MidiEvent
class MidiEventProcessor
class MidiPort
class Mixer
class MixerChannel
class MixerRoute
class Model
class ModelVisitor
class NoCopyNoMove
Inherit this class to make your class non-copyable and non-movable.
class Note
struct NoteBounds
class NotePlayHandle
class NotePlayHandleManager
class NullableResource
struct NullableResourceDeleter
class OnePole
class Oscillator
class OutputSettings
struct PatternAnalysisResult
Used by the helper function that analyzes automation patterns.
class PatternClip
Dummy clip for PatternTracks.
class PatternStore
class PatternTrack
Track type used in the Song (Editor) to reference a pattern in the PatternStore.
class PeakController
class PerfLogTimer
The PerfLog class.
class PerfTime
CPU time point.
class Piano
class PixmapLoader
class PlanarBufferView
Non-owning view for multi-channel non-interleaved audio data.
class PlayHandle
class Plugin
Abstract representation of a plugin.
class PluginFactory
class PluginIssue
Issue type bundled with informational string.
class PollParentThread
struct port_desc_t
This struct is used to hold port descriptions internally which where received from the ladspa plugin.
class PresetPreviewPlayHandle
class PreviewTrackContainer
class ProcessWatcher
class ProjectJournal
class ProjectRenderer
class ProjectVersion
Version number parsing and comparison.
class QuadratureLfo
class RemotePlugin
class RemotePluginBase
class RemotePluginClient
class RenderManager
class RingBuffer
A basic LMMS ring buffer for single-thread use.
class RmsHelper
class Sample
class SampleBuffer
class SampleClip
class SampleDecoder
class SampleFrame
class SamplePlayHandle
class SampleRecordHandle
class SampleThumbnail
Allows for visualizing sample data.
class SampleTrack
class Scale
class Semaphore
A counting semaphore.
class SerializingObject
class SerializingObjectHook
class SharedMemory
class SharedMemory< T[]>
class shmFifo
class Song
class StepRecorder
struct StereoVolumeVector
class SystemSemaphore
class TempoSyncKnobModel
class ThreadableJob
class ThreadPool
A thread pool that can be used for asynchronous processing.
class Timeline
class TimePos
Represents a position in time or length of a note or event, in ticks, beats, and bars.
class TimeSig
Represents a time signature, in which the numerator is the number of beats in a bar, while the denominator is the type of note representing a beat.
class ToolPlugin
class Track
Base-class for all tracks.
class TrackContainer
class TypedAutomatableModel
class unique_ptr
STL class.
class UpgradeExtendedNoteRange
class Upsampler
class ValueBuffer
class VstSyncController
struct VstSyncData
struct WaveMipMap
Concepts
concept AudioBufferView
Concept for any audio buffer view, interleaved or planar.
concept SampleType
Recognized sample types, either const or non-const.
Typedefs
using AudioFileDeviceInstantiaton = AudioFileDevice* (*)(const QString&, const OutputSettings&, const ch_cnt_t, AudioEngine*, bool&)
using AutomatedValueMap = QMap<AutomatableModel*, float>
using bar_t = std::int32_t
using bitrate_t = std::uint16_t
using bpm_t = std::uint16_t
using ch_cnt_t = std::uint8_t
using ConstNotePlayHandleList = QList<const NotePlayHandle*>
using ConstPlayHandleList = QList<const PlayHandle*>
using ControllerConnectionVector = std::vector<ControllerConnection*>
using ControllerVector = std::vector<Controller*>
using EffectKey = Effect::Descriptor::SubPluginFeatures::Key
using EffectKeyList = Effect::Descriptor::SubPluginFeatures::KeyList
using f_cnt_t = std::size_t
using fpp_t = std::size_t
using int_sample_t = std::int16_t
using jo_id_t = std::uint32_t
using l_ladspa_key_t = QList<ladspa_key_t>
using l_sortable_plugin_t = QList<sortable_plugin_t>
using ladspa_key_t = QPair<QString, QString>
using LocklessListElement = LocklessList<PlayHandle*>::Element
using MidiMetaEventType = MidiMetaEventTypes
using MidiPortList = QList<MidiPort*>
using mix_ch_t = std::uint16_t
using MixerRouteVector = std::vector<MixerRoute*>
using NotePlayHandleList = QList<NotePlayHandle*>
using NoteVector = std::vector<Note*>
using panning_t = std::int8_t
using PeakControllerEffectVector = std::vector<PeakControllerEffect*>
using pitch_t = int16_t
using PlayHandleList = QList<PlayHandle*>
using proc_ch_t = std::uint16_t
using sample_rate_t = std::uint32_t
using sample_t = float
using sortable_plugin_t = QPair<QString, ladspa_key_t>
using StereoAllpassDelay = AllpassDelay<2>
using StereoBiQuad = BiQuad<2>
using StereoCombFeedback = CombFeedback<2>
using StereoCombFeedbackDualtap = CombFeedbackDualtap<2>
using StereoCombFeedfwd = CombFeedfwd<2>
using StereoLinkwitzRiley = LinkwitzRiley<2>
using StereoOnePole = OnePole<2>
using tick_t = std::int32_t
using timeMap = AutomationClip::timeMap
using track_ch_t = std::uint16_t
template<typename T, T Null, auto Deleter>
using UniqueNullableResource = std::unique_ptr<T, NullableResourceDeleter<T, Null, Deleter>>
using volume_t = std::uint8_t
Enumerations
enum class AmplitudeRange {
Extended = 0 ,
Audible ,
Loud ,
Silent
}
enum class BufferDataType {
Toggled ,
Enum ,
Integer ,
Floating ,
Time ,
None
}
enum class BufferRate {
ChannelIn ,
ChannelOut ,
AudioRateInput ,
AudioRateOutput ,
ControlRateInput ,
ControlRateOutput
}
enum class FFTWindow {
Rectangular = 0 ,
BlackmanHarris ,
Hamming ,
Hanning
}
enum class FrequencyRange {
Full = 0 ,
Audible ,
Bass ,
Mids ,
High
}
enum class Key : int {
C = 0 ,
Cis = 1 ,
Des = 1 ,
D = 2 ,
Dis = 3 ,
Es = 3 ,
E = 4 ,
Fes = 4 ,
F = 5 ,
Fis = 6 ,
Ges = 6 ,
G = 7 ,
Gis = 8 ,
As = 8 ,
A = 9 ,
Ais = 10 ,
B = 10 ,
H = 11
}
enum class LadspaPluginType {
Source ,
Transfer ,
Valid ,
Invalid ,
Sink ,
Other
}
enum MidiControllerRegisteredParameterNumbers {
MidiPitchBendSensitivityRPN = 0x0000 ,
MidiChannelFineTuningRPN = 0x0001 ,
MidiChannelCoarseTuningRPN = 0x0002 ,
MidiTuningProgramChangeRPN = 0x0003 ,
MidiTuningBankSelectRPN = 0x0004 ,
MidiModulationDepthRangeRPN = 0x0005 ,
MidiNullFunctionNumberRPN = 0x7F7F
}
enum MidiEventTypes {
MidiNoteOff = 0x80 ,
MidiNoteOn = 0x90 ,
MidiKeyPressure = 0xA0 ,
MidiControlChange = 0xB0 ,
MidiProgramChange = 0xC0 ,
MidiChannelPressure = 0xD0 ,
MidiPitchBend = 0xE0 ,
MidiSysEx = 0xF0 ,
MidiTimeCode = 0xF1 ,
MidiSongPosition = 0xF2 ,
MidiSongSelect = 0xF3 ,
MidiTuneRequest = 0xF6 ,
MidiEOX = 0xF7 ,
MidiSync = 0xF8 ,
MidiTick = 0xF9 ,
MidiStart = 0xFA ,
MidiContinue = 0xFB ,
MidiStop = 0xFC ,
MidiActiveSensing = 0xFE ,
MidiSystemReset = 0xFF ,
MidiMetaEvent = 0xFF
}
enum MidiMetaEventTypes {
MidiMetaInvalid = 0x00 ,
MidiCopyright = 0x02 ,
MidiTrackName = 0x03 ,
MidiInstName = 0x04 ,
MidiLyric = 0x05 ,
MidiMarker = 0x06 ,
MidiCuePoint = 0x07 ,
MidiPortNumber = 0x21 ,
MidiEOT = 0x2f ,
MidiSetTempo = 0x51 ,
MidiSMPTEOffset = 0x54 ,
MidiTimeSignature = 0x58 ,
MidiKeySignature = 0x59 ,
MidiSequencerEvent = 0x7f ,
MidiMetaCustom = 0x80 ,
MidiNotePanning
}
enum MidiStandardControllers {
MidiControllerBankSelect = 0 ,
MidiControllerModulationWheel = 1 ,
MidiControllerBreathController = 2 ,
MidiControllerFootController = 4 ,
MidiControllerPortamentoTime = 5 ,
MidiControllerDataEntry = 6 ,
MidiControllerMainVolume = 7 ,
MidiControllerBalance = 8 ,
MidiControllerPan = 10 ,
MidiControllerEffectControl1 = 12 ,
MidiControllerEffectControl2 = 13 ,
MidiControllerSustain = 64 ,
MidiControllerPortamento = 65 ,
MidiControllerSostenuto = 66 ,
MidiControllerSoftPedal = 67 ,
MidiControllerLegatoFootswitch = 68 ,
MidiControllerRegisteredParameterNumberLSB = 100 ,
MidiControllerRegisteredParameterNumberMSB = 101 ,
MidiControllerAllSoundOff = 120 ,
MidiControllerResetAllControllers = 121 ,
MidiControllerLocalControl = 122 ,
MidiControllerAllNotesOff = 123 ,
MidiControllerOmniOn = 124 ,
MidiControllerOmniOff = 125 ,
MidiControllerMonoOn = 126 ,
MidiControllerPolyOn = 127
}
enum class Octave : int {
Octave_m1 ,
Octave_0 ,
Octave_1 ,
Octave_2 ,
Octave_3 ,
Octave_4 ,
Octave_5 ,
Octave_6 ,
Octave_7 ,
Octave_8 ,
Octave_9
}
enum class PluginIssueType {
UnknownPortFlow ,
UnknownPortType ,
TooManyInputChannels ,
TooManyOutputChannels ,
TooManyMidiInputChannels ,
TooManyMidiOutputChannels ,
NoOutputChannel ,
PortHasNoDef ,
PortHasNoMin ,
PortHasNoMax ,
MinGreaterMax ,
DefaultValueNotInRange ,
LogScaleMinMissing ,
LogScaleMaxMissing ,
LogScaleMinMaxDifferentSigns ,
FeatureNotSupported ,
BadPortType ,
Blocked ,
NoIssue
}
Types of issues that can cause LMMS to not load a plugin LMMS Plugins should use this to indicate errors.
enum RemoteMessageIDs {
IdUndefined ,
IdHostInfoGotten ,
IdInitDone ,
IdQuit ,
IdSyncKey ,
IdSampleRateInformation ,
IdBufferSizeInformation ,
IdInformationUpdated ,
IdMidiEvent ,
IdStartProcessing ,
IdProcessingDone ,
IdChangeSharedMemoryKey ,
IdChangeInputCount ,
IdChangeOutputCount ,
IdChangeInputOutputCount ,
IdShowUI ,
IdHideUI ,
IdToggleUI ,
IdIsUIVisible ,
IdSaveSettingsToString ,
IdSaveSettingsToFile ,
IdLoadSettingsFromString ,
IdLoadSettingsFromFile ,
IdSavePresetFile ,
IdLoadPresetFile ,
IdDebugMessage ,
IdIdle ,
IdUserBase = 64
}
Functions
auto absFraction (std::floating_point auto x) noexcept
Returns the wrapped fractional part of a float, a value between 0.0f and 1.0f.
int absspec (const fftwf_complex *complex_buffer, float *absspec_buffer, unsigned int compl_length)
Compute absolute values of complex_buffer, save to absspec_buffer.
static bool affected (QDomElement &instrument)
static size_t align (size_t size, size_t alignment)
float ampToDbfs (float amp)
Converts linear amplitude (>0-1.0) to dBFS scale.
static PatternAnalysisResult analyzeAutomationPattern (QDomElement const &automationPattern, std::set< unsigned int > const &automatedBaseNoteIds)
Helper function that checks for an automation pattern if it contains automation for targets that are base notes and/or other targets.
bool approximatelyEqual (float x, float y) noexcept
std::optional< NoteBounds > boundsForNotes (const NoteVector &notes)
Get the start/end/bottom/top positions of notes in a vector.
static QMap< QString, QString > buildReplacementMap ()
template<typename... Args, std::enable_if_t<(detail::IsKeyOrModifier< Args > &&...), bool > = true>
constexpr int combine (Args... args)
Combines Qt key and modifier arguments together, replacing A | B which was deprecated in C++20 due to the enums being different types.
int compressbands (const float *_absspec_buffer, float *_compressedband, int _num_old, int _num_new, int _bottom, int _top)
Build fewer subbands from many absolute spectrum values.
void copyFromSampleFrames (float *target, const SampleFrame *source, size_t frames)
void copyToSampleFrames (SampleFrame *target, const float *source, size_t frames)
float cosinusInterpolate (float v0, float v1, float x)
static int countZeroCrossings (SampleFrame *buf, fpp_t start, fpp_t frames)
float cubicInterpolate (float v0, float v1, float v2, float v3, float x)
float dbfsToAmp (float dbfs)
Converts dBFS-scale to linear amplitude with 0dBFS = 1.0.
void disable_denormals ()
static QString ensureTrailingSlash (const QString &s)
auto fastLog10f (float x)
double fastPow (double a, double b)
Source: http://martin.ankerl.com/2007/10/04/optimized-pow-approximation-for-java-and-c-c/.
auto fastPow10f (std::integral auto x)
template<std::floating_point T>
auto fastPow10f (T x)
auto fastRand () noexcept
template<std::floating_point T>
auto fastRand (T from, T to) noexcept
template<std::floating_point T>
auto fastRand (T range) noexcept
int fileToDescriptor (std::FILE *file, bool closeFile=true)
Returns the POSIX file descriptor of the given FILE.
static void findIds (const QDomElement &elem, QList< jo_id_t > &idList)
static void fixAutomationPattern (QDomElement &automationPattern)
Helper method that fixes the values and out values for an automation pattern.
static void fixAutomationTracks (QDomElement &song, std::set< unsigned int > const &automatedBaseNoteIds)
static void fixInstrumentBaseNoteAndCollectIds (QDomElement &instrument, std::set< unsigned int > &automatedBaseNoteIds)
static void fixNotePatterns (QDomNodeList &patterns)
static void fixTrack (QDomElement &track, std::set< unsigned int > &automatedBaseNoteIds)
std::FILE * fopenUtf8 (const std::string &filename, const char *mode)
std::fopen wrapper that expects UTF-8 encoded filename and mode
auto fraction (std::floating_point auto x) noexcept
Returns the fractional part of a float, a value between -1.0f and 1.0f.
SampleFrame getAbsPeakValues (SampleFrame *buffer, size_t frames)
fpp_t getFadeInLength (float maxLength, fpp_t frames, int zeroCrossings)
PluginFactory * getPluginFactory ()
float hermiteInterpolate (float x0, float x1, float x2, float x3, float frac_pos)
int horizontalAdvance (const QFontMetrics &metrics, const QString &text)
horizontalAdvance is a backwards-compatible adapter for QFontMetrics::horizontalAdvance and width functions.
float INTAN (AutomationClip::TimemapIterator it)
float INVAL (AutomationClip::TimemapIterator it)
bool isLittleEndian ()
template<class Ftor>
void iterate_ladspa_ports (QDomElement &effect, Ftor &ftor)
Helper function to call a functor for all effect ports' DomElements, providing the functor with lists to add and remove DomElements.
Plugin::Descriptor::SubPluginFeatures::Key ladspaKeyToSubPluginKey (const Plugin::Descriptor *_desc, const QString &_name, const ladspa_key_t &_key)
float lagrangeInterpolate (float v0, float v1, float v2, float v3, float x)
float linearToLogScale (float min, float max, float value)
Scales value from logarithmic to linear. Value should be in min-max range.
float LOCKEDTAN (AutomationClip::TimemapIterator it)
float logToLinearScale (float min, float max, float value)
Scales @value from linear to logarithmic.
float maximum (const float *abs_spectrum, unsigned int spec_size)
Returns biggest value from abs_spectrum[spec_size] array.
float maximum (const std::vector< float > &abs_spectrum)
QStringList nameFilters ("lib*.so")
int normalize (const float *abs_spectrum, float *norm_spectrum, unsigned int bin_count, unsigned int block_size)
Normalize the abs_spectrum array of absolute values to a 0..1 range based on supplied energy and stores it in the norm_spectrum array.
int normalize (const std::vector< float > &abs_spectrum, std::vector< float > &norm_spectrum, unsigned int block_size)
int notEmpty (const std::vector< float > &spectrum)
Check if the spectrum contains any non-zero value.
int numDigitsAsInt (float f)
float OFFSET (AutomationClip::TimemapIterator it)
bool operator!= (const ProjectVersion &v1, const ProjectVersion &v2)
constexpr auto operator+ (Octave octave, Key key) -> int
PerfTime operator- (const PerfTime &lhs, const PerfTime &rhs)
bool operator< (const ProjectVersion &v1, const ProjectVersion &v2)
QDataStream & operator<< (QDataStream &out, WaveMipMap &waveMipMap)
QDebug operator<< (QDebug dbg, const QDomNode &node)
QDebug operator<< (QDebug stream, const PluginIssue &iss)
bool operator<= (const ProjectVersion &v1, const ProjectVersion &v2)
bool operator== (const ProjectVersion &v1, const ProjectVersion &v2)
bool operator> (const ProjectVersion &v1, const ProjectVersion &v2)
bool operator>= (const ProjectVersion &v1, const ProjectVersion &v2)
QDataStream & operator>> (QDataStream &in, WaveMipMap &waveMipMap)
float optimal4pInterpolate (float v0, float v1, float v2, float v3, float x)
float optimalInterpolate (float v0, float v1, float x)
template<>
sample_t Oscillator::getSample< Oscillator::WaveShape::Exponential > (const float _sample)
template<>
sample_t Oscillator::getSample< Oscillator::WaveShape::MoogSaw > (const float _sample)
template<>
sample_t Oscillator::getSample< Oscillator::WaveShape::Saw > (const float _sample)
template<>
sample_t Oscillator::getSample< Oscillator::WaveShape::Sine > (const float sample)
template<>
sample_t Oscillator::getSample< Oscillator::WaveShape::Square > (const float _sample)
template<>
sample_t Oscillator::getSample< Oscillator::WaveShape::Triangle > (const float _sample)
template<>
sample_t Oscillator::getSample< Oscillator::WaveShape::UserDefined > (const float _sample)
template<>
sample_t Oscillator::getSample< Oscillator::WaveShape::WhiteNoise > (const float _sample)
float OUTTAN (AutomationClip::TimemapIterator it)
float OUTVAL (AutomationClip::TimemapIterator it)
int panningToMidi (panning_t _p)
StereoVolumeVector panningToVolumeVector (panning_t _p, float _scale=1.0f)
int POS (AutomationClip::TimemapIterator it)
QPoint position (QWheelEvent *wheelEvent)
position is a backwards-compatible adapter for QWheelEvent::position and pos functions.
int precomputeWindow (float *window, unsigned int length, FFTWindow type, bool normalized=true)
Precompute a window function for later real-time use.
std::string QSTR_TO_STDSTR (QString const &qstr)
template<class T>
static void roundAt (T &value, const T &where, const T &stepSize)
Round value to where depending on step size.
float safeAmpToDbfs (float amp)
Converts linear amplitude (0-1.0) to dBFS scale.
float safeDbfsToAmp (float dbfs)
Converts dBFS-scale to linear amplitude with 0dBFS = 1.0.
static void saveEnvelopeAndLFOParameters (EnvelopeAndLfoParameters &p, const QString &tagName, QDomDocument &_doc, QDomElement &_this)
template<typename T>
constexpr T sign (T val) noexcept
returns +1 if val >= 0, else -1
float signedPowf (float v, float e)
Exponential function that deals with negative bases.
float sqrt_neg (float val)
if val >= 0.0f, returns sqrt(val), else: -sqrt(-val)
void swap (SampleBuffer &first, SampleBuffer &second)
int16_t swap16IfBE (int16_t i)
int32_t swap32IfBE (int32_t i)
static void upgradeElement_1_2_0_rc2_42 (QDomElement &el)
QString use_this_or (QString this_param, QString or_param)
template<class T>
T use_this_or (T this_param, T or_param)
std::size_t LMMS_EXPORT writeToByteSeq (const class MidiEvent &ev, uint8_t *data, std::size_t bufsize)
Write MIDI event into byte sequence.
std::size_t writeToByteSeq (const MidiEvent &ev, uint8_t *data, std::size_t bufsize)
void zeroSampleFrames (SampleFrame *buffer, size_t frames)
Variables
constexpr auto ARANGE_AUDIBLE_END = 0
constexpr auto ARANGE_AUDIBLE_START = -50
constexpr auto ARANGE_EXTENDED_END = 20
constexpr auto ARANGE_EXTENDED_START = -80
constexpr auto ARANGE_LOUD_END = 0
constexpr auto ARANGE_LOUD_START = -30
constexpr auto ARANGE_SILENT_END = -10
constexpr auto ARANGE_SILENT_START = -60
constexpr int BYTES_PER_FRAME = sizeof(SampleFrame)
constexpr int BYTES_PER_INT_SAMPLE = sizeof(int_sample_t)
constexpr int BYTES_PER_SAMPLE = sizeof(sample_t)
constexpr pitch_t CentsPerSemitone = 100
int chkOn [8]
short clippoint
const float CUT_FREQ_MULTIPLIER = 6000.0f
short DD [1200]
constexpr fpp_t DEFAULT_BUFFER_SIZE = 256
constexpr ch_cnt_t DEFAULT_CHANNELS = 2
const QString DEFAULT_THEME_PATH = "themes/default/"
const int DEFAULT_TRACK_HEIGHT = 32
const float DefaultBaseFreq = 440.f
const int DefaultBaseKey = Octave::Octave_4 + Key::A
const int DefaultBeatsPerBar = DefaultTicksPerBar / DefaultStepsPerBar
const int DefaultKey = DefaultOctave + Key::A
const int DefaultMiddleKey = Octave::Octave_4 + Key::C
constexpr auto DefaultOctave = Octave::Octave_4
constexpr panning_t DefaultPanning = PanningCenter
constexpr pitch_t DefaultPitch = 0
const int DefaultStepsPerBar = 16
const bpm_t DefaultTempo = 140
const int DefaultTicksPerBar = 192
constexpr volume_t DefaultVolume = 100
const int dENV = 3
float DF [1200]
static PixmapLoader dummyLoader
static Plugin::Descriptor dummyPluginDescriptor
constexpr auto DynamicChannelCount = static_cast<proc_ch_t>(-1)
Use when the number of channels is not known at compile time.
const int ENV = 1
float envData [8][6]
float envpts [8][3][32]
static const int EO_ID_MSB = 1 << 23
Avoid clashes between loaded IDs (have the bit cleared) and newly created IDs (have the bit set).
constexpr float F_EPSILON = 1.0e-10f
const std::vector< unsigned int > FFT_BLOCK_SIZES = {256, 512, 1024, 2048, 4096, 8192, 16384}
constexpr auto FFT_BUFFER_SIZE = std::size_t{2048}
char const *const FILENAME_FILTER = "[\\0000-\x1f\"*/:<>?\\\\|\x7f]"
const int FirstOctave = -1
constexpr auto FRANGE_AUDIBLE_END = 20000
constexpr auto FRANGE_AUDIBLE_START = 20
constexpr auto FRANGE_BASS_END = 300
constexpr auto FRANGE_BASS_START = 20
constexpr auto FRANGE_HIGH_END = 20000
constexpr auto FRANGE_HIGH_START = 4000
constexpr auto FRANGE_MIDS_END = 5000
constexpr auto FRANGE_MIDS_START = 200
const QString GIG_PATH = "samples/gig/"
const int INITIAL_NPH_CACHE = 256
constexpr Qt::KeyboardModifier KBD_COPY_MODIFIER
static const auto KEY_ORDER
The black / white order of keys as they appear on the keyboard.
const int KeysPerOctave = 12
const QString LADSPA_PATH ="plugins/ladspa/"
constexpr char LADSPA_PATH_SEPERATOR
const QString LOCALE_PATH = "locale/"
constexpr auto LOWEST_LOG_FREQ = 5
const int MAX = 0
const float MaxDetuning = 5 * 12.0f
constexpr fpp_t MAXIMUM_BUFFER_SIZE = 4096
constexpr unsigned MaxKeymapCount = 10
number of keyboard mappings per project
constexpr int MAXLEN = 11
constexpr pitch_t MaxPitchDefault = CentsPerSemitone
constexpr unsigned MaxScaleCount = 10
number of scales per project
const tick_t MaxSongLength = 9999 * DefaultTicksPerBar
constexpr int MAXTBL = 23
const bpm_t MaxTempo = 999
constexpr int MAXTLEN = 3 << MAXLEN
constexpr volume_t MaxVolume = 200
float mem_b = 1.0f
float mem_n = 1.0f
float mem_o = 1.0f
float mem_t = 1.0f
float mem_time = 1.0f
float mem_tune = 1.0f
const int MidiChannelCount = 16
const int MidiControllerCount = 128
const int MidiDefaultVelocity = MidiMaxVelocity / 2
const int MidiMaxControllerValue = 127
const int MidiMaxKey = 127
const int MidiMaxPanning = 127
const int MidiMaxPitchBend = 16383
const int MidiMaxVelocity = 127
const int MidiMinPanning = -128
const int MidiMinPitchBend = 0
const int MidiProgramCount = 128
const int MINIMAL_TRACK_HEIGHT = 32
The minimum track height in pixels.
constexpr fpp_t MINIMUM_BUFFER_SIZE = 32
const f_cnt_t minimumFrames = 1
constexpr pitch_t MinPitchDefault = -CentsPerSemitone
const bpm_t MinTempo = 10
constexpr int MINTLEN = 2 << 0
constexpr volume_t MinVolume = 0
constexpr int MIPMAPSIZE = 2 << (MAXLEN + 1)
constexpr int MIPMAPSIZE3 = 3 << (MAXLEN + 1)
const int NEXTT = 4
const float NOHINT = -99342.2243f
const int NPH_CACHE_INCREMENT = 16
const int NumKeys = 128
Number of physical keys, limited to MIDI range (valid for both MIDI 1.0 and 2.0).
constexpr float OUTPUT_SAMPLE_MULTIPLIER = 32767.0f
constexpr panning_t PanningCenter = 0
constexpr panning_t PanningLeft = -PanningRight
constexpr panning_t PanningRight = 100
float phi [1200]
const int PNT = 2
const QString PORTABLE_MODE_FILE = "/portable_mode.txt"
const QString PRESETS_PATH = "presets/"
const QString PROJECTS_PATH = "projects/"
const uint32_t RAW_MIDI_PARSE_BUF_SIZE = 16
static const auto REMAINS_80E0
static const auto REMAINS_F0F6
const int REMOVE_RELEASED_NOTE_TIME_THRESHOLD_MS = 70
const float RES_MULTIPLIER = 2.0f
const float RES_PRECISION = 1000.0f
static MidiDummy s_dummyClient
static bool s_renderingThread = false
const QString SAMPLES_PATH = "samples/"
const float SECS_PER_ENV_SEGMENT = 5.0f
const float SECS_PER_LFO_OSCILLATION = 20.0f
const QString SF2_PATH = "samples/soundfonts/"
const int SHM_FIFO_SIZE = 512*1024
static const size_t SIZEOF_SET = sizeof(int) * 8
int sliLev [8]
constexpr auto SUPPORTED_SAMPLERATES = std::array{44100, 48000, 88200, 96000, 192000}
const QString TEMPLATE_PATH = "templates/"
float timestretch
const int TLENS [MAXTBL+1]
const QString TRACK_ICON_PATH = "track_icons/"
constexpr const char * UI_ALT_KEY
constexpr const char * UI_COPY_KEY
constexpr const char * UI_CTRL_KEY
long wavemode = 0
long wavewords
Typedef Documentation
AudioFileDeviceInstantiaton
using lmms::AudioFileDeviceInstantiaton = AudioFileDevice* (*)(const QString&, const OutputSettings&, const ch_cnt_t, AudioEngine*, bool&)
Definition at line 71 of file AudioFileDevice.h.
AutomatedValueMap
using lmms::AutomatedValueMap = QMap<AutomatableModel*, float>
Definition at line 505 of file AutomatableModel.h.
bar_t
using lmms::bar_t = std::int32_t
Definition at line 35 of file LmmsTypes.h.
bitrate_t
using lmms::bitrate_t = std::uint16_t
Definition at line 48 of file LmmsTypes.h.
bpm_t
using lmms::bpm_t = std::uint16_t
Definition at line 47 of file LmmsTypes.h.
ch_cnt_t
using lmms::ch_cnt_t = std::uint8_t
Definition at line 46 of file LmmsTypes.h.
ConstNotePlayHandleList
using lmms::ConstNotePlayHandleList = QList<const NotePlayHandle*>
Definition at line 45 of file NotePlayHandle.h.
ConstPlayHandleList
using lmms::ConstPlayHandleList = QList<const PlayHandle*>
Definition at line 163 of file PlayHandle.h.
ControllerConnectionVector
using lmms::ControllerConnectionVector = std::vector<ControllerConnection*>
Definition at line 50 of file ControllerConnection.h.
ControllerVector
using lmms::ControllerVector = std::vector<Controller*>
Definition at line 48 of file Controller.h.
EffectKey
using lmms::EffectKey = Effect::Descriptor::SubPluginFeatures::Key
Definition at line 210 of file Effect.h.
EffectKeyList
using lmms::EffectKeyList = Effect::Descriptor::SubPluginFeatures::KeyList
Definition at line 211 of file Effect.h.
f_cnt_t
using lmms::f_cnt_t = std::size_t
Definition at line 45 of file LmmsTypes.h.
fpp_t
using lmms::fpp_t = std::size_t
Definition at line 44 of file LmmsTypes.h.
int_sample_t
using lmms::int_sample_t = std::int16_t
Definition at line 41 of file LmmsTypes.h.
jo_id_t
using lmms::jo_id_t = std::uint32_t
Definition at line 53 of file LmmsTypes.h.
l_ladspa_key_t
using lmms::l_ladspa_key_t = QList<ladspa_key_t>
Definition at line 50 of file LadspaManager.h.
l_sortable_plugin_t
using lmms::l_sortable_plugin_t = QList<sortable_plugin_t>
Definition at line 49 of file LadspaManager.h.
ladspa_key_t
using lmms::ladspa_key_t = QPair<QString, QString>
Definition at line 47 of file LadspaManager.h.
LocklessListElement
using lmms::LocklessListElement = LocklessList<PlayHandle*>::Element
Definition at line 66 of file AudioEngine.cpp.
MidiMetaEventType
using lmms::MidiMetaEventType = MidiMetaEventTypes
Definition at line 82 of file Midi.h.
MidiPortList
using lmms::MidiPortList = QList<MidiPort*>
Definition at line 188 of file MidiPort.h.
mix_ch_t
using lmms::mix_ch_t = std::uint16_t
Definition at line 49 of file LmmsTypes.h.
MixerRouteVector
using lmms::MixerRouteVector = std::vector<MixerRoute*>
Definition at line 42 of file Mixer.h.
NotePlayHandleList
using lmms::NotePlayHandleList = QList<NotePlayHandle*>
Definition at line 44 of file NotePlayHandle.h.
NoteVector
using lmms::NoteVector = std::vector<Note*>
Definition at line 274 of file Note.h.
panning_t
using lmms::panning_t = std::int8_t
Definition at line 38 of file LmmsTypes.h.
PeakControllerEffectVector
using lmms::PeakControllerEffectVector = std::vector<PeakControllerEffect*>
Definition at line 39 of file PeakController.h.
pitch_t
using lmms::pitch_t = int16_t
Definition at line 33 of file Pitch.h.
PlayHandleList
using lmms::PlayHandleList = QList<PlayHandle*>
Definition at line 162 of file PlayHandle.h.
proc_ch_t
using lmms::proc_ch_t = std::uint16_t
Definition at line 51 of file LmmsTypes.h.
sample_rate_t
using lmms::sample_rate_t = std::uint32_t
Definition at line 43 of file LmmsTypes.h.
sample_t
using lmms::sample_t = float
Definition at line 40 of file LmmsTypes.h.
sortable_plugin_t
using lmms::sortable_plugin_t = QPair<QString, ladspa_key_t>
Definition at line 48 of file LadspaManager.h.
StereoAllpassDelay
using lmms::StereoAllpassDelay = AllpassDelay<2>
Definition at line 362 of file Delay.h.
StereoBiQuad
using lmms::StereoBiQuad = BiQuad<2>
Definition at line 187 of file BasicFilters.h.
StereoCombFeedback
using lmms::StereoCombFeedback = CombFeedback<2>
Definition at line 359 of file Delay.h.
StereoCombFeedbackDualtap
using lmms::StereoCombFeedbackDualtap = CombFeedbackDualtap<2>
Definition at line 361 of file Delay.h.
StereoCombFeedfwd
using lmms::StereoCombFeedfwd = CombFeedfwd<2>
Definition at line 360 of file Delay.h.
StereoLinkwitzRiley
using lmms::StereoLinkwitzRiley = LinkwitzRiley<2>
Definition at line 140 of file BasicFilters.h.
StereoOnePole
using lmms::StereoOnePole = OnePole<2>
Definition at line 220 of file BasicFilters.h.
tick_t
using lmms::tick_t = std::int32_t
Definition at line 36 of file LmmsTypes.h.
timeMap
using lmms::timeMap = AutomationClip::timeMap
Definition at line 80 of file PianoRoll.cpp.
track_ch_t
using lmms::track_ch_t = std::uint16_t
Definition at line 50 of file LmmsTypes.h.
UniqueNullableResource
template<typename T, T Null, auto Deleter> using lmms::UniqueNullableResource = std::unique_ptr<T, NullableResourceDeleter<T, Null, Deleter>>
Definition at line 63 of file RaiiHelpers.h.
volume_t
using lmms::volume_t = std::uint8_t
Definition at line 37 of file LmmsTypes.h.
Enumeration Type Documentation
AmplitudeRange
enum class lmms::AmplitudeRange strong
Enumerator
Extended
Audible
Loud
Silent
Definition at line 71 of file lmms_constants.h.
BufferDataType
enum class lmms::BufferDataType strong
Enumerator
Toggled
Enum
Integer
Floating
Time
None
Definition at line 49 of file LadspaBase.h.
BufferRate
enum class lmms::BufferRate strong
Enumerator
ChannelIn
ChannelOut
AudioRateInput
AudioRateOutput
ControlRateInput
ControlRateOutput
Definition at line 40 of file LadspaBase.h.
FFTWindow
enum class lmms::FFTWindow strong
Enumerator
Rectangular
BlackmanHarris
Hamming
Hanning
Definition at line 47 of file fft_helpers.h.
FrequencyRange
enum class lmms::FrequencyRange strong
Enumerator
Full
Audible
Bass
Mids
High
Definition at line 50 of file lmms_constants.h.
Key
enum class lmms::Key : int strong
Enumerator
C
Cis
Des
D
Dis
Es
E
Fes
F
Fis
Ges
G
Gis
As
A
Ais
B
H
Definition at line 46 of file Note.h.
LadspaPluginType
enum class lmms::LadspaPluginType strong
Enumerator
Source
Transfer
Valid
Invalid
Sink
Other
Definition at line 65 of file LadspaManager.h.
MidiControllerRegisteredParameterNumbers
enum lmms::MidiControllerRegisteredParameterNumbers
Enumerator
MidiPitchBendSensitivityRPN
MidiChannelFineTuningRPN
MidiChannelCoarseTuningRPN
MidiTuningProgramChangeRPN
MidiTuningBankSelectRPN
MidiModulationDepthRangeRPN
MidiNullFunctionNumberRPN
Definition at line 116 of file Midi.h.
MidiEventTypes
enum lmms::MidiEventTypes
Enumerator
MidiNoteOff
MidiNoteOn
MidiKeyPressure
MidiControlChange
MidiProgramChange
MidiChannelPressure
MidiPitchBend
MidiSysEx
MidiTimeCode
MidiSongPosition
MidiSongSelect
MidiTuneRequest
MidiEOX
MidiSync
MidiTick
MidiStart
MidiContinue
MidiStop
MidiActiveSensing
MidiSystemReset
MidiMetaEvent
Definition at line 33 of file Midi.h.
MidiMetaEventTypes
enum lmms::MidiMetaEventTypes
Enumerator
MidiMetaInvalid
MidiCopyright
MidiTrackName
MidiInstName
MidiLyric
MidiMarker
MidiCuePoint
MidiPortNumber
MidiEOT
MidiSetTempo
MidiSMPTEOffset
MidiTimeSignature
MidiKeySignature
MidiSequencerEvent
MidiMetaCustom
MidiNotePanning
Definition at line 63 of file Midi.h.
MidiStandardControllers
enum lmms::MidiStandardControllers
Enumerator
MidiControllerBankSelect
MidiControllerModulationWheel
MidiControllerBreathController
MidiControllerFootController
MidiControllerPortamentoTime
MidiControllerDataEntry
MidiControllerMainVolume
MidiControllerBalance
MidiControllerPan
MidiControllerEffectControl1
MidiControllerEffectControl2
MidiControllerSustain
MidiControllerPortamento
MidiControllerSostenuto
MidiControllerSoftPedal
MidiControllerLegatoFootswitch
MidiControllerRegisteredParameterNumberLSB
MidiControllerRegisteredParameterNumberMSB
MidiControllerAllSoundOff
MidiControllerResetAllControllers
MidiControllerLocalControl
MidiControllerAllNotesOff
MidiControllerOmniOn
MidiControllerOmniOff
MidiControllerMonoOn
MidiControllerPolyOn
Definition at line 84 of file Midi.h.
Octave
enum class lmms::Octave : int strong
Enumerator
Octave_m1
Octave_0
Octave_1
Octave_2
Octave_3
Octave_4
Octave_5
Octave_6
Octave_7
Octave_8
Octave_9
Definition at line 63 of file Note.h.
PluginIssueType
enum class lmms::PluginIssueType strong
Types of issues that can cause LMMS to not load a plugin LMMS Plugins should use this to indicate errors.
Enumerator
UnknownPortFlow
UnknownPortType
TooManyInputChannels
TooManyOutputChannels
TooManyMidiInputChannels
TooManyMidiOutputChannels
NoOutputChannel
PortHasNoDef
PortHasNoMin
PortHasNoMax
MinGreaterMax
DefaultValueNotInRange
LogScaleMinMissing
LogScaleMaxMissing
LogScaleMinMaxDifferentSigns
FeatureNotSupported
plugin requires functionality LMMS can't offer
BadPortType
port type not supported
Blocked
NoIssue
Definition at line 36 of file PluginIssue.h.
RemoteMessageIDs
enum lmms::RemoteMessageIDs
Enumerator
IdUndefined
IdHostInfoGotten
IdInitDone
IdQuit
IdSyncKey
IdSampleRateInformation
IdBufferSizeInformation
IdInformationUpdated
IdMidiEvent
IdStartProcessing
IdProcessingDone
IdChangeSharedMemoryKey
IdChangeInputCount
IdChangeOutputCount
IdChangeInputOutputCount
IdShowUI
IdHideUI
IdToggleUI
IdIsUIVisible
IdSaveSettingsToString
IdSaveSettingsToFile
IdLoadSettingsFromString
IdLoadSettingsFromFile
IdSavePresetFile
IdLoadPresetFile
IdDebugMessage
IdIdle
IdUserBase
Definition at line 320 of file RemotePluginBase.h.
Function Documentation
absFraction()
auto lmms::absFraction (std::floating_point auto x) inline noexcept
Returns the wrapped fractional part of a float, a value between 0.0f and 1.0f.
absFraction(2.3) => 0.3 absFraction(-2.3) => 0.7
Note that this not the same as the absolute value of the fraction (as the function name suggests). If the result is interpreted as a phase of an oscillator, it makes that negative phases are converted to positive phases.
Definition at line 79 of file lmms_math.h.
Referenced by lmms::Oscillator::expSample(), lmms::Oscillator::getWtSampleControl(), lmms::Oscillator::moogSawSample(), lmms::Oscillator::recalcPhase(), lmms::Oscillator::sawSample(), lmms::Oscillator::squareSample(), lmms::Oscillator::triangleSample(), lmms::LfoController::updateValueBuffer(), lmms::Oscillator::userWaveSample(), and lmms::DrumSynth::waveform().
absspec()
int LMMS_EXPORT lmms::absspec (const fftwf_complex * complex_buffer, float * absspec_buffer, unsigned int compl_length)
Compute absolute values of complex_buffer, save to absspec_buffer.
Take care that - compl_len is not bigger than complex_buffer!
absspec buffer is big enough!
Returns
0 on success, else -1
Definition at line 168 of file fft_helpers.cpp.
References i.
affected()
bool lmms::affected (QDomElement & instrument) static
Definition at line 169 of file UpgradeExtendedNoteRange.cpp.
Referenced by fixTrack(), and lmms::UpgradeExtendedNoteRange::upgrade().
align()
size_t lmms::align (size_t size, size_t alignment) static
Definition at line 42 of file LocklessAllocator.cpp.
Referenced by lmms::LocklessAllocator::LocklessAllocator().
ampToDbfs()
float lmms::ampToDbfs (float amp) inline
Converts linear amplitude (>0-1.0) to dBFS scale.
Parameters
amp Linear amplitude, where 1.0 = 0dBFS. ** Must be larger than zero! **
Returns
Amplitude in dBFS.
Definition at line 206 of file lmms_math.h.
References fastLog10f().
Referenced by lmms::gui::Fader::adjustByDialog(), lmms::gui::Fader::adjustModelByDBDelta(), lmms::gui::Fader::calculateKnobPosYFromModel(), lmms::gui::Fader::computeScaledRatio(), lmms::gui::FloatModelEditorBase::displayValue(), lmms::gui::FloatModelEditorBase::enterValue(), lmms::gui::Fader::getModelValueAsDbString(), lmms::gui::Fader::paintFaderTicks(), lmms::gui::Fader::paintLevels(), safeAmpToDbfs(), lmms::gui::Fader::setVolumeByLocalPixelValue(), and lmms::gui::PeakIndicator::updatePeakDisplay().
analyzeAutomationPattern()
PatternAnalysisResult lmms::analyzeAutomationPattern (QDomElement const & automationPattern, std::set< unsigned int > const & automatedBaseNoteIds) static
Helper function that checks for an automation pattern if it contains automation for targets that are base notes and/or other targets.
Parameters
automationPattern The automation pattern to be checked.
automatedBaseNoteIds A set of id of automated base notes that are used in the check.
Returns
A struct that contains the results.
Definition at line 57 of file UpgradeExtendedNoteRange.cpp.
Referenced by fixAutomationTracks().
approximatelyEqual()
bool lmms::approximatelyEqual (float x, float y) inline noexcept
Definition at line 47 of file lmms_math.h.
References F_EPSILON.
Referenced by lmms::AutomatableModel::controllerValue(), lmms::gui::Fader::paintFaderTicks(), lmms::NotePlayHandle::processTimePos(), lmms::Oscillator::recalcPhase(), and lmms::gui::FloatModelEditorBase::setPosition().
boundsForNotes()
std::optional< NoteBounds > lmms::boundsForNotes (const NoteVector & notes)
Get the start/end/bottom/top positions of notes in a vector.
Returns no value if there are no notes
Definition at line 264 of file Note.cpp.
Referenced by lmms::gui::MidiClipView::transposeSelection().
buildReplacementMap()
QMap< QString, QString > lmms::buildReplacementMap () static
Definition at line 1951 of file DataFile.cpp.
Referenced by lmms::DataFile::upgrade_loopsRename().
combine()
template<typename... Args, std::enable_if_t<(detail::IsKeyOrModifier< Args > &&...), bool > = true> int lmms::combine (Args... args) constexpr
Combines Qt key and modifier arguments together, replacing A | B which was deprecated in C++20 due to the enums being different types.
(P1120R0)
Parameters
args Any number of Qt::Key, Qt::Modifier, or Qt::KeyboardModifier
Returns
The combination of the given keys/modifiers as an int
Definition at line 89 of file DeprecationHelper.h.
Referenced by lmms::gui::AutomationEditorWindow::AutomationEditorWindow(), lmms::gui::Editor::Editor(), lmms::gui::PianoRollWindow::PianoRollWindow(), lmms::gui::ControllerRackView::addController(), lmms::gui::MainWindow::finalize(), and lmms::gui::EffectRackView::update().
compressbands()
int LMMS_EXPORT lmms::compressbands (const float * _absspec_buffer, float * _compressedband, int _num_old, int _num_new, int _bottom, int _top)
Build fewer subbands from many absolute spectrum values.
Take care that - compressedbands[] array num_new elements long
num_old > num_new
Returns
0 on success, else -1
Definition at line 189 of file fft_helpers.cpp.
References i, and j.
copyFromSampleFrames()
void lmms::copyFromSampleFrames (float * target, const SampleFrame * source, size_t frames) inline
Definition at line 221 of file SampleFrame.h.
References i, lmms::SampleFrame::left(), and lmms::SampleFrame::right().
Referenced by lmms::RemotePlugin::process().
copyToSampleFrames()
void lmms::copyToSampleFrames (SampleFrame * target, const float * source, size_t frames) inline
Definition at line 212 of file SampleFrame.h.
References i, lmms::SampleFrame::setLeft(), and lmms::SampleFrame::setRight().
Referenced by lmms::RemotePlugin::process().
cosinusInterpolate()
float lmms::cosinusInterpolate (float v0, float v1, float x) inline
Definition at line 78 of file interpolation.h.
countZeroCrossings()
int lmms::countZeroCrossings (SampleFrame * buf, fpp_t start, fpp_t frames) static
Definition at line 92 of file Instrument.cpp.
References DEFAULT_CHANNELS.
Referenced by lmms::Instrument::applyFadeIn().
cubicInterpolate()
float lmms::cubicInterpolate (float v0, float v1, float v2, float v3, float x) inline
Definition at line 65 of file interpolation.h.
dbfsToAmp()
float lmms::dbfsToAmp (float dbfs) inline
Converts dBFS-scale to linear amplitude with 0dBFS = 1.0.
Parameters
dbfs The dBFS value to convert. ** Must be a real number - not inf/nan! **
Returns
Linear amplitude
Definition at line 215 of file lmms_math.h.
References fastPow10f().
Referenced by lmms::gui::Fader::adjustByDialog(), lmms::gui::Fader::adjustModelByDBDelta(), lmms::gui::FloatModelEditorBase::enterValue(), lmms::gui::Fader::paintLevels(), safeDbfsToAmp(), lmms::gui::Fader::setVolumeByLocalPixelValue(), and lmms::gui::PeakIndicator::updatePeakDisplay().
disable_denormals()
void lmms::disable_denormals () inline
Definition at line 39 of file denormals.h.
Referenced by main(), lmms::AudioEngine::fifoWriter::run(), and lmms::AudioEngineWorkerThread::run().
ensureTrailingSlash()
QString lmms::ensureTrailingSlash (const QString & s) inline static
Definition at line 50 of file ConfigManager.cpp.
Referenced by lmms::ConfigManager::loadConfigFile(), lmms::ConfigManager::setSTKDir(), lmms::ConfigManager::setThemeDir(), lmms::ConfigManager::setVSTDir(), and lmms::ConfigManager::setWorkingDir().
fastLog10f()
auto lmms::fastLog10f (float x) inline
Definition at line 197 of file lmms_math.h.
Referenced by ampToDbfs().
fastPow()
double lmms::fastPow (double a, double b) inline
Source: http://martin.ankerl.com/2007/10/04/optimized-pow-approximation-for-java-and-c-c/.
Definition at line 115 of file lmms_math.h.
fastPow10f() [1/2]
auto lmms::fastPow10f (std::integral auto x) inline
Definition at line 191 of file lmms_math.h.
fastPow10f() [2/2]
template<std::floating_point T> auto lmms::fastPow10f (T x) inline
Definition at line 185 of file lmms_math.h.
Referenced by dbfsToAmp(), lmms::DrumSynth::GetDSFileSamples(), lmms::gui::LcdFloatSpinBox::update(), and lmms::gui::PianoRoll::updateStrumPos().
fastRand() [1/3]
auto lmms::fastRand () inline noexcept
Definition at line 84 of file lmms_math.h.
Referenced by fastRand(), and fastRand().
fastRand() [2/3]
template<std::floating_point T> auto lmms::fastRand (T from, T to) inline noexcept
Definition at line 99 of file lmms_math.h.
References fastRand().
fastRand() [3/3]
template<std::floating_point T> auto lmms::fastRand (T range) inline noexcept
Definition at line 92 of file lmms_math.h.
References fastRand().
fileToDescriptor()
int lmms::fileToDescriptor (std::FILE * file, bool closeFile = true) inline
Returns the POSIX file descriptor of the given FILE.
Definition at line 107 of file IoHelper.h.
References file.
findIds()
void lmms::findIds (const QDomElement & elem, QList< jo_id_t > & idList) static
Definition at line 2206 of file DataFile.cpp.
References findIds().
Referenced by findIds(), and lmms::DataFile::upgrade_1_0_99().
fixAutomationPattern()
void lmms::fixAutomationPattern (QDomElement & automationPattern) static
Helper method that fixes the values and out values for an automation pattern.
Parameters
automationPattern The automation pattern to be fixed.
Definition at line 150 of file UpgradeExtendedNoteRange.cpp.
Referenced by fixAutomationTracks().
fixAutomationTracks()
void lmms::fixAutomationTracks (QDomElement & song, std::set< unsigned int > const & automatedBaseNoteIds) static
Definition at line 223 of file UpgradeExtendedNoteRange.cpp.
References analyzeAutomationPattern(), lmms::Track::Automation, fixAutomationPattern(), and i.
Referenced by lmms::UpgradeExtendedNoteRange::upgrade().
fixInstrumentBaseNoteAndCollectIds()
void lmms::fixInstrumentBaseNoteAndCollectIds (QDomElement & instrument, std::set< unsigned int > & automatedBaseNoteIds) static
Definition at line 101 of file UpgradeExtendedNoteRange.cpp.
References j.
Referenced by fixTrack().
fixNotePatterns()
void lmms::fixNotePatterns (QDomNodeList & patterns) static
Definition at line 84 of file UpgradeExtendedNoteRange.cpp.
References i, and j.
Referenced by fixTrack().
fixTrack()
void lmms::fixTrack (QDomElement & track, std::set< unsigned int > & automatedBaseNoteIds) static
Definition at line 179 of file UpgradeExtendedNoteRange.cpp.
References affected(), fixInstrumentBaseNoteAndCollectIds(), fixNotePatterns(), fixTrack(), i, and lmms::Track::Pattern.
Referenced by fixTrack(), and lmms::UpgradeExtendedNoteRange::upgrade().
fopenUtf8()
std::FILE * lmms::fopenUtf8 (const std::string & filename, const char * mode) inline
std::fopen wrapper that expects UTF-8 encoded filename and mode
Definition at line 97 of file IoHelper.h.
fraction()
auto lmms::fraction (std::floating_point auto x) inline noexcept
Returns the fractional part of a float, a value between -1.0f and 1.0f.
fraction(2.3) => 0.3 fraction(-2.3) => -0.3
Note that if the return value is used as a phase of an oscillator, that the oscillator must support negative phases.
Definition at line 62 of file lmms_math.h.
Referenced by lmms::BandLimitedWave::oscillate(), lmms::gui::LcdFloatSpinBox::update(), lmms::Oscillator::userWaveSample(), lmms::Oscillator::wtSample(), lmms::Oscillator::wtSample(), and lmms::Oscillator::wtSample().
getAbsPeakValues()
SampleFrame lmms::getAbsPeakValues (SampleFrame * buffer, size_t frames) inline
Definition at line 200 of file SampleFrame.h.
References lmms::SampleFrame::absMax(), and i.
Referenced by lmms::MixerChannel::doProcessing(), and lmms::gui::Oscilloscope::paintEvent().
getFadeInLength()
fpp_t lmms::getFadeInLength (float maxLength, fpp_t frames, int zeroCrossings)
Definition at line 121 of file Instrument.cpp.
Referenced by lmms::Instrument::applyFadeIn().
getPluginFactory()
LMMS_EXPORT PluginFactory * lmms::getPluginFactory ()
Definition at line 103 of file PluginFactory.cpp.
References lmms::PluginFactory::instance().
Referenced by lmms::gui::EffectSelectDialog::EffectSelectDialog(), lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::gui::PluginBrowser::addPlugins(), lmms::gui::FileItem::determineFileType(), lmms::gui::InstrumentTrackWindow::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), lmms::gui::MainWindow::finalize(), lmms::gui::FileBrowserTreeWidget::handleFile(), lmms::ImportFilter::import(), lmms::Plugin::instantiate(), lmms::Plugin::instantiateWithKey(), lmms::gui::FileBrowserTreeWidget::previewFileItem(), and lmms::DataFile::validate().
hermiteInterpolate()
float lmms::hermiteInterpolate (float x0, float x1, float x2, float x3, float frac_pos) inline
Definition at line 34 of file interpolation.h.
horizontalAdvance()
int lmms::horizontalAdvance (const QFontMetrics & metrics, const QString & text) inline
horizontalAdvance is a backwards-compatible adapter for QFontMetrics::horizontalAdvance and width functions.
Parameters
metrics
text
Returns
text's horizontal advance based on metrics.
Definition at line 46 of file DeprecationHelper.h.
Referenced by lmms::gui::VersionedSaveDialog::VersionedSaveDialog(), lmms::gui::TabWidget::addTab(), lmms::gui::Knob::drawLabel(), lmms::gui::TabWidget::findTabAtPos(), lmms::gui::LedCheckBox::onTextUpdated(), lmms::gui::LcdWidget::paintEvent(), lmms::gui::TabWidget::paintEvent(), lmms::gui::Knob::updateFixedSize(), and lmms::gui::LcdWidget::updateSize().
INTAN()
float lmms::INTAN (AutomationClip::TimemapIterator it) inline
Definition at line 283 of file AutomationClip.h.
Referenced by lmms::gui::AutomationEditor::drawAutomationTangents(), lmms::AutomationClip::saveSettings(), lmms::AutomationClip::setDragValue(), and lmms::AutomationClip::valueAt().
INVAL()
float lmms::INVAL (AutomationClip::TimemapIterator it) inline
Definition at line 268 of file AutomationClip.h.
Referenced by lmms::gui::AutomationEditor::centerTopBottomScroll(), lmms::gui::AutomationEditor::drawAutomationPoint(), lmms::gui::AutomationEditor::drawAutomationTangents(), lmms::gui::PianoRoll::drawDetuningInfo(), lmms::gui::AutomationEditor::fineTuneValue(), lmms::AutomationClip::flipX(), lmms::AutomationClip::flipY(), lmms::AutomationClip::generateTangents(), lmms::gui::AutomationEditor::getNodeAt(), lmms::InlineAutomation::hasAutomation(), lmms::gui::AutomationEditor::mouseMoveEvent(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::AutomationEditor::paintEvent(), lmms::AutomationClip::saveSettings(), lmms::gui::AutomationClipView::scaleTimemapToFit(), and lmms::AutomationClip::valueAt().
isLittleEndian()
bool lmms::isLittleEndian () inline
Definition at line 36 of file endian_handling.h.
Referenced by swap16IfBE(), swap32IfBE(), lmms::AudioFileFlac::writeBuffer(), and lmms::AudioFileWave::writeBuffer().
iterate_ladspa_ports()
template<class Ftor> void lmms::iterate_ladspa_ports (QDomElement & effect, Ftor & ftor)
Helper function to call a functor for all effect ports' DomElements, providing the functor with lists to add and remove DomElements.
Helpful for patching port values from savefiles.
Definition at line 1256 of file DataFile.cpp.
Referenced by lmms::DataFile::upgrade_1_3_0().
ladspaKeyToSubPluginKey()
Plugin::Descriptor::SubPluginFeatures::Key lmms::ladspaKeyToSubPluginKey (const Plugin::Descriptor * _desc, const QString & _name, const ladspa_key_t & _key) inline
Definition at line 73 of file LadspaBase.h.
References file.
lagrangeInterpolate()
float lmms::lagrangeInterpolate (float v0, float v1, float v2, float v3, float x) inline
Definition at line 118 of file interpolation.h.
linearToLogScale()
float lmms::linearToLogScale (float min, float max, float value) inline
Scales value from logarithmic to linear. Value should be in min-max range.
Definition at line 168 of file lmms_math.h.
References max, min, and signedPowf().
Referenced by lmms::AutomatableModel::inverseScaledValue().
LOCKEDTAN()
float lmms::LOCKEDTAN (AutomationClip::TimemapIterator it) inline
Definition at line 293 of file AutomationClip.h.
Referenced by lmms::AutomationClip::generateTangents(), lmms::gui::AutomationEditor::paintEvent(), lmms::AutomationClip::saveSettings(), and lmms::AutomationClip::setDragValue().
logToLinearScale()
float lmms::logToLinearScale (float min, float max, float value) inline
Scales @value from linear to logarithmic.
Value should be within [0,1]
Definition at line 152 of file lmms_math.h.
References max, min, and signedPowf().
Referenced by lmms::AutomatableModel::logToLinearScale().
maximum() [1/2]
float LMMS_EXPORT lmms::maximum (const float * abs_spectrum, unsigned int spec_size)
Returns biggest value from abs_spectrum[spec_size] array.
Returns
-1 on error, 0 on success
Definition at line 40 of file fft_helpers.cpp.
References i.
Referenced by maximum().
maximum() [2/2]
float LMMS_EXPORT lmms::maximum (const std::vector< float > & abs_spectrum)
Definition at line 54 of file fft_helpers.cpp.
References maximum().
nameFilters()
QStringList lmms::nameFilters ("lib*.so")
References lmms::PluginFactory::s_instance.
Referenced by lmms::PluginFactory::discoverPlugins(), and lmms::gui::SampleLoader::openAudioFile().
normalize() [1/2]
int LMMS_EXPORT lmms::normalize (const float * abs_spectrum, float * norm_spectrum, unsigned int bin_count, unsigned int block_size)
Normalize the abs_spectrum array of absolute values to a 0..1 range based on supplied energy and stores it in the norm_spectrum array.
Returns
-1 on error
Definition at line 65 of file fft_helpers.cpp.
References i.
Referenced by lmms::Oscillator::generateFromFFT(), and normalize().
normalize() [2/2]
int LMMS_EXPORT lmms::normalize (const std::vector< float > & abs_spectrum, std::vector< float > & norm_spectrum, unsigned int block_size)
Definition at line 78 of file fft_helpers.cpp.
References normalize().
notEmpty()
int LMMS_EXPORT lmms::notEmpty (const std::vector< float > & spectrum)
Check if the spectrum contains any non-zero value.
Returns
1 if spectrum contains any non-zero value
0 otherwise
Definition at line 91 of file fft_helpers.cpp.
numDigitsAsInt()
int lmms::numDigitsAsInt (float f) inline
Definition at line 241 of file lmms_math.h.
References i.
OFFSET()
float lmms::OFFSET (AutomationClip::TimemapIterator it) inline
Definition at line 278 of file AutomationClip.h.
Referenced by lmms::gui::AutomationEditor::fineTuneValue(), lmms::AutomationClip::generateTangents(), lmms::InlineAutomation::hasAutomation(), and lmms::AutomationClip::setDragValue().
operator!=()
bool lmms::operator!= (const ProjectVersion & v1, const ProjectVersion & v2) inline
Definition at line 79 of file ProjectVersion.h.
References lmms::ProjectVersion::compare().
operator+()
auto lmms::operator+ (Octave octave, Key key)->int inline constexpr
Definition at line 81 of file Note.h.
References KeysPerOctave.
operator-()
PerfTime lmms::operator- (const PerfTime & lhs, const PerfTime & rhs)
Definition at line 94 of file PerfLog.cpp.
operator<()
bool lmms::operator< (const ProjectVersion & v1, const ProjectVersion & v2) inline
Definition at line 74 of file ProjectVersion.h.
References lmms::ProjectVersion::compare().
operator<<() [1/3]
QDataStream & lmms::operator<< (QDataStream & out, WaveMipMap & waveMipMap)
Definition at line 38 of file BandLimitedWave.cpp.
References i, MAXTBL, lmms::WaveMipMap::sampleAt(), and TLENS.
operator<<() [2/3]
QDebug lmms::operator<< (QDebug dbg, const QDomNode & node)
Definition at line 1302 of file DataFile.cpp.
operator<<() [3/3]
QDebug lmms::operator<< (QDebug stream, const PluginIssue & iss)
Definition at line 98 of file PluginIssue.cpp.
operator<=()
bool lmms::operator<= (const ProjectVersion & v1, const ProjectVersion & v2) inline
Definition at line 76 of file ProjectVersion.h.
References lmms::ProjectVersion::compare().
operator==()
bool lmms::operator== (const ProjectVersion & v1, const ProjectVersion & v2) inline
Definition at line 78 of file ProjectVersion.h.
References lmms::ProjectVersion::compare().
operator>()
bool lmms::operator> (const ProjectVersion & v1, const ProjectVersion & v2) inline
Definition at line 75 of file ProjectVersion.h.
References lmms::ProjectVersion::compare().
operator>=()
bool lmms::operator>= (const ProjectVersion & v1, const ProjectVersion & v2) inline
Definition at line 77 of file ProjectVersion.h.
References lmms::ProjectVersion::compare().
operator>>()
QDataStream & lmms::operator>> (QDataStream & in, WaveMipMap & waveMipMap)
Definition at line 50 of file BandLimitedWave.cpp.
References i, MAXTBL, lmms::WaveMipMap::setSampleAt(), and TLENS.
optimal4pInterpolate()
float lmms::optimal4pInterpolate (float v0, float v1, float v2, float v3, float x) inline
Definition at line 100 of file interpolation.h.
Referenced by lmms::BandLimitedWave::oscillate().
optimalInterpolate()
float lmms::optimalInterpolate (float v0, float v1, float x) inline
Definition at line 85 of file interpolation.h.
Oscillator::getSample< Oscillator::WaveShape::Exponential >()
template<> sample_t lmms::Oscillator::getSample< Oscillator::WaveShape::Exponential > (const float _sample) inline
Definition at line 790 of file Oscillator.cpp.
References lmms::Oscillator::getSample().
Oscillator::getSample< Oscillator::WaveShape::MoogSaw >()
template<> sample_t lmms::Oscillator::getSample< Oscillator::WaveShape::MoogSaw > (const float _sample) inline
Definition at line 773 of file Oscillator.cpp.
References lmms::Oscillator::getSample().
Oscillator::getSample< Oscillator::WaveShape::Saw >()
template<> sample_t lmms::Oscillator::getSample< Oscillator::WaveShape::Saw > (const float _sample) inline
Definition at line 739 of file Oscillator.cpp.
References lmms::Oscillator::getSample().
Oscillator::getSample< Oscillator::WaveShape::Sine >()
template<> sample_t lmms::Oscillator::getSample< Oscillator::WaveShape::Sine > (const float sample) inline
Definition at line 704 of file Oscillator.cpp.
References lmms::Engine::audioEngine(), lmms::Oscillator::getSample(), lmms::OscillatorConstants::MAX_FREQ, and lmms::AudioEngine::outputSampleRate().
Oscillator::getSample< Oscillator::WaveShape::Square >()
template<> sample_t lmms::Oscillator::getSample< Oscillator::WaveShape::Square > (const float _sample) inline
Definition at line 756 of file Oscillator.cpp.
References lmms::Oscillator::getSample().
Oscillator::getSample< Oscillator::WaveShape::Triangle >()
template<> sample_t lmms::Oscillator::getSample< Oscillator::WaveShape::Triangle > (const float _sample) inline
Definition at line 722 of file Oscillator.cpp.
References lmms::Oscillator::getSample().
Oscillator::getSample< Oscillator::WaveShape::UserDefined >()
template<> sample_t lmms::Oscillator::getSample< Oscillator::WaveShape::UserDefined > (const float _sample) inline
Definition at line 817 of file Oscillator.cpp.
References lmms::Oscillator::getSample().
Oscillator::getSample< Oscillator::WaveShape::WhiteNoise >()
template<> sample_t lmms::Oscillator::getSample< Oscillator::WaveShape::WhiteNoise > (const float _sample) inline
Definition at line 807 of file Oscillator.cpp.
References lmms::Oscillator::getSample().
OUTTAN()
float lmms::OUTTAN (AutomationClip::TimemapIterator it) inline
Definition at line 288 of file AutomationClip.h.
Referenced by lmms::gui::AutomationEditor::drawAutomationTangents(), lmms::AutomationClip::saveSettings(), lmms::AutomationClip::setDragValue(), and lmms::AutomationClip::valueAt().
OUTVAL()
float lmms::OUTVAL (AutomationClip::TimemapIterator it) inline
Definition at line 273 of file AutomationClip.h.
Referenced by lmms::gui::AutomationEditor::drawAutomationPoint(), lmms::gui::AutomationEditor::drawAutomationTangents(), lmms::gui::PianoRoll::drawDetuningInfo(), lmms::gui::AutomationEditor::fineTuneValue(), lmms::AutomationClip::flipX(), lmms::AutomationClip::flipY(), lmms::AutomationClip::generateTangents(), lmms::gui::AutomationEditor::getNodeAt(), lmms::gui::AutomationEditor::mouseMoveEvent(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::AutomationEditor::paintEvent(), lmms::AutomationClip::saveSettings(), lmms::AutomationClip::setDragValue(), lmms::AutomationClip::valueAt(), and lmms::AutomationClip::valueAt().
panningToMidi()
int lmms::panningToMidi (panning_t _p) inline
Definition at line 53 of file panning.h.
References MidiMaxPanning, MidiMinPanning, PanningLeft, and PanningRight.
Referenced by lmms::gui::PianoRoll::mouseMoveEvent(), and lmms::gui::PianoRoll::testPlayNote().
panningToVolumeVector()
StereoVolumeVector lmms::panningToVolumeVector (panning_t _p, float _scale = 1.0f) inline
Definition at line 43 of file panning.h.
References PanningCenter, and lmms::StereoVolumeVector::vol.
Referenced by lmms::InstrumentTrack::processAudioBuffer().
POS()
int lmms::POS (AutomationClip::TimemapIterator it) inline
Definition at line 298 of file AutomationClip.h.
Referenced by lmms::AutomationClip::AutomationClip(), lmms::gui::AutomationEditor::drawAutomationPoint(), lmms::gui::AutomationEditor::drawAutomationTangents(), lmms::gui::PianoRoll::drawDetuningInfo(), lmms::AutomationClip::flipX(), lmms::AutomationClip::generateTangents(), lmms::gui::AutomationEditor::getClosestNode(), lmms::gui::AutomationEditor::getNodeAt(), lmms::InlineAutomation::hasAutomation(), lmms::gui::AutomationEditor::mouseMoveEvent(), lmms::gui::AutomationEditor::mousePressEvent(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::AutomationEditor::paintEvent(), lmms::AutomationClip::removeNodes(), lmms::AutomationClip::saveSettings(), lmms::AutomationClip::timeMapLength(), lmms::AutomationClip::valueAt(), lmms::AutomationClip::valueAt(), and lmms::AutomationClip::valuesAfter().
position()
QPoint lmms::position (QWheelEvent * wheelEvent) inline
position is a backwards-compatible adapter for QWheelEvent::position and pos functions.
Parameters
wheelEvent
Returns
the position of wheelEvent
Definition at line 61 of file DeprecationHelper.h.
Referenced by lmms::Track::createClipsForPattern(), lmms::gui::ClipView::mouseMoveEvent(), lmms::Timeline::setPlayStartPosition(), lmms::gui::AutomationEditor::wheelEvent(), lmms::gui::LcdFloatSpinBox::wheelEvent(), lmms::gui::MidiClipView::wheelEvent(), lmms::gui::PianoRoll::wheelEvent(), lmms::gui::SongEditor::wheelEvent(), and lmms::gui::TabWidget::wheelEvent().
precomputeWindow()
int LMMS_EXPORT lmms::precomputeWindow (float * window, unsigned int length, FFTWindow type, bool normalized = true)
Precompute a window function for later real-time use.
Set normalized to false if you do not want to apply amplitude correction.
Returns
-1 on error
Definition at line 105 of file fft_helpers.cpp.
References BlackmanHarris, Hamming, Hanning, i, and Rectangular.
QSTR_TO_STDSTR()
std::string lmms::QSTR_TO_STDSTR (QString const & qstr) inline
Definition at line 195 of file RemotePlugin.h.
roundAt()
template<class T> void lmms::roundAt (T & value, const T & where, const T & stepSize) static
Round value to where depending on step size.
Definition at line 106 of file lmms_math.h.
References F_EPSILON.
Referenced by lmms::AutomatableModel::roundAt().
safeAmpToDbfs()
float lmms::safeAmpToDbfs (float amp) inline
Converts linear amplitude (0-1.0) to dBFS scale.
Handles zeroes as -inf.
Parameters
amp Linear amplitude, where 1.0 = 0dBFS.
Returns
Amplitude in dBFS. -inf for 0 amplitude.
Definition at line 224 of file lmms_math.h.
References ampToDbfs().
safeDbfsToAmp()
float lmms::safeDbfsToAmp (float dbfs) inline
Converts dBFS-scale to linear amplitude with 0dBFS = 1.0.
Handles infinity as zero.
Parameters
dbfs The dBFS value to convert: all infinites are treated as -inf and result in 0
Returns
Linear amplitude
Definition at line 233 of file lmms_math.h.
References dbfsToAmp().
saveEnvelopeAndLFOParameters()
void lmms::saveEnvelopeAndLFOParameters (EnvelopeAndLfoParameters & p, const QString & tagName, QDomDocument & _doc, QDomElement & _this) static
Definition at line 321 of file InstrumentSoundShaping.cpp.
References lmms::JournallingObject::saveState().
Referenced by lmms::InstrumentSoundShaping::saveSettings().
sign()
template<typename T> T lmms::sign (T val) constexpr noexcept
returns +1 if val >= 0, else -1
Definition at line 131 of file lmms_math.h.
Referenced by signedPowf(), and sqrt_neg().
signedPowf()
float lmms::signedPowf (float v, float e) inline
Exponential function that deals with negative bases.
Definition at line 144 of file lmms_math.h.
References sign().
Referenced by linearToLogScale(), and logToLinearScale().
sqrt_neg()
float lmms::sqrt_neg (float val) inline
if val >= 0.0f, returns sqrt(val), else: -sqrt(-val)
Definition at line 138 of file lmms_math.h.
References sign().
swap()
void lmms::swap (SampleBuffer & first, SampleBuffer & second) noexcept
Definition at line 72 of file SampleBuffer.cpp.
Referenced by lmms::SampleBuffer::swap.
swap16IfBE()
int16_t lmms::swap16IfBE (int16_t i) inline
Definition at line 42 of file endian_handling.h.
References i, and isLittleEndian().
swap32IfBE()
int32_t lmms::swap32IfBE (int32_t i) inline
Definition at line 48 of file endian_handling.h.
References i, and isLittleEndian().
upgradeElement_1_2_0_rc2_42()
void lmms::upgradeElement_1_2_0_rc2_42 (QDomElement & el) static
Definition at line 1186 of file DataFile.cpp.
References i, and upgradeElement_1_2_0_rc2_42().
Referenced by lmms::DataFile::upgrade_1_2_0_rc3(), and upgradeElement_1_2_0_rc2_42().
use_this_or() [1/2]
QString lmms::use_this_or (QString this_param, QString or_param)
Definition at line 85 of file Plugin.cpp.
use_this_or() [2/2]
template<class T> T lmms::use_this_or (T this_param, T or_param)
Definition at line 77 of file Plugin.cpp.
Referenced by lmms::Plugin::Descriptor::SubPluginFeatures::Key::description(), lmms::Plugin::Descriptor::SubPluginFeatures::Key::displayName(), and lmms::Plugin::Descriptor::SubPluginFeatures::Key::logo().
writeToByteSeq() [1/2]
std::size_t LMMS_EXPORT lmms::writeToByteSeq (const class MidiEvent & ev, uint8_t * data, std::size_t bufsize)
Write MIDI event into byte sequence.
Conforming to http://lv2plug.in/ns/ext/midi#MidiEvent
Parameters
data Pointer to the target buffer for the byte sequence. Must point to existing memory with at least 3 bytes size.
bufsize Available size of the target buffer.
Returns
Used size of the target buffer, or 0 if the MidiEvent could not be converted.
writeToByteSeq() [2/2]
std::size_t lmms::writeToByteSeq (const MidiEvent & ev, uint8_t * data, std::size_t bufsize)
Definition at line 36 of file MidiEventToByteSeq.cpp.
References lmms::MidiEvent::channel(), lmms::MidiEvent::channelPressure(), lmms::MidiEvent::controllerNumber(), lmms::MidiEvent::controllerValue(), lmms::MidiEvent::key(), MidiChannelPressure, MidiControlChange, MidiKeyPressure, MidiMaxKey, MidiNoteOff, MidiNoteOn, MidiPitchBend, MidiProgramChange, lmms::MidiEvent::pitchBend(), lmms::MidiEvent::program(), lmms::MidiEvent::type(), and lmms::MidiEvent::velocity().
zeroSampleFrames()
void lmms::zeroSampleFrames (SampleFrame * buffer, size_t frames) inline
Definition at line 192 of file SampleFrame.h.
Referenced by lmms::AudioEngine::AudioEngine(), lmms::MixerChannel::MixerChannel(), lmms::gui::Oscilloscope::Oscilloscope(), lmms::RingBuffer::RingBuffer(), lmms::RingBuffer::RingBuffer(), lmms::RingBuffer::changeSize(), lmms::AudioBusHandle::doProcessing(), lmms::PlayHandle::doProcessing(), lmms::Mixer::masterMix(), lmms::SamplePlayHandle::play(), lmms::DummyInstrument::playNote(), lmms::RingBuffer::pop(), lmms::Mixer::prepareMasterMix(), lmms::RemotePlugin::process(), lmms::RingBuffer::reset(), lmms::MixHelpers::sanitize(), lmms::AudioEngine::swapBuffers(), lmms::Oscillator::update(), and lmms::RingBuffer::updateSamplerate().
Variable Documentation
ARANGE_AUDIBLE_END
auto lmms::ARANGE_AUDIBLE_END = 0 inline constexpr
Definition at line 82 of file lmms_constants.h.
ARANGE_AUDIBLE_START
auto lmms::ARANGE_AUDIBLE_START = -50 inline constexpr
Definition at line 81 of file lmms_constants.h.
ARANGE_EXTENDED_END
auto lmms::ARANGE_EXTENDED_END = 20 inline constexpr
Definition at line 80 of file lmms_constants.h.
ARANGE_EXTENDED_START
auto lmms::ARANGE_EXTENDED_START = -80 inline constexpr
Definition at line 79 of file lmms_constants.h.
ARANGE_LOUD_END
auto lmms::ARANGE_LOUD_END = 0 inline constexpr
Definition at line 84 of file lmms_constants.h.
ARANGE_LOUD_START
auto lmms::ARANGE_LOUD_START = -30 inline constexpr
Definition at line 83 of file lmms_constants.h.
ARANGE_SILENT_END
auto lmms::ARANGE_SILENT_END = -10 inline constexpr
Definition at line 86 of file lmms_constants.h.
ARANGE_SILENT_START
auto lmms::ARANGE_SILENT_START = -60 inline constexpr
Definition at line 85 of file lmms_constants.h.
BYTES_PER_FRAME
int lmms::BYTES_PER_FRAME = sizeof(SampleFrame) constexpr
Definition at line 58 of file AudioEngine.h.
BYTES_PER_INT_SAMPLE
int lmms::BYTES_PER_INT_SAMPLE = sizeof(int_sample_t) constexpr
Definition at line 57 of file AudioEngine.h.
Referenced by lmms::AudioDevice::clearS16Buffer(), and lmms::AudioDevice::convertToS16().
BYTES_PER_SAMPLE
int lmms::BYTES_PER_SAMPLE = sizeof(sample_t) constexpr
Definition at line 56 of file AudioEngine.h.
CentsPerSemitone
pitch_t lmms::CentsPerSemitone = 100 constexpr
Definition at line 35 of file Pitch.h.
chkOn
int lmms::chkOn[8]
Definition at line 56 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), lmms::DrumSynth::LongestEnv(), and lmms::DrumSynth::LoudestEnv().
clippoint
short lmms::clippoint
Definition at line 58 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
CUT_FREQ_MULTIPLIER
const float lmms::CUT_FREQ_MULTIPLIER = 6000.0f
Definition at line 40 of file InstrumentSoundShaping.cpp.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer().
DD
short lmms::DD[1200]
Definition at line 58 of file DrumSynth.cpp.
DEFAULT_BUFFER_SIZE
fpp_t lmms::DEFAULT_BUFFER_SIZE = 256 constexpr
Definition at line 53 of file AudioEngine.h.
Referenced by lmms::AudioEngine::AudioEngine(), lmms::gui::SetupDialog::resetBufferSize(), and lmms::gui::SetupDialog::setBufferSize().
DEFAULT_CHANNELS
ch_cnt_t lmms::DEFAULT_CHANNELS = 2 inline constexpr
Definition at line 37 of file lmms_constants.h.
Referenced by lmms::AudioDummy::AudioDummy(), lmms::ProjectRenderer::ProjectRenderer(), lmms::RemotePlugin::RemotePlugin(), lmms::Instrument::applyFadeIn(), lmms::Instrument::applyRelease(), countZeroCrossings(), lmms::anonymous_namespace{SampleDecoder.cpp}::decodeSampleDS(), lmms::gui::Oscilloscope::paintEvent(), lmms::RemotePlugin::process(), lmms::AudioSampleRecorder::writeBuffer(), and lmms::SampleRecordHandle::writeBuffer().
DEFAULT_THEME_PATH
const QString lmms::DEFAULT_THEME_PATH = "themes/default/"
Definition at line 50 of file ConfigManager.h.
Referenced by lmms::ConfigManager::defaultThemeDir().
DEFAULT_TRACK_HEIGHT
const int lmms::DEFAULT_TRACK_HEIGHT = 32
Definition at line 61 of file Track.h.
Referenced by lmms::Track::getHeight(), lmms::gui::TrackView::mouseMoveEvent(), and lmms::gui::TrackView::mousePressEvent().
DefaultBaseFreq
const float lmms::DefaultBaseFreq = 440.f
Definition at line 93 of file Note.h.
Referenced by lmms::Keymap::Keymap(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::InstrumentTrack::baseFreq(), lmms::Sample::play(), and lmms::NotePlayHandle::updateFrequency().
DefaultBaseKey
const int lmms::DefaultBaseKey = Octave::Octave_4 + Key::A
Definition at line 92 of file Note.h.
Referenced by lmms::Keymap::Keymap(), and lmms::gui::MicrotunerConfig::MicrotunerConfig().
DefaultBeatsPerBar
const int lmms::DefaultBeatsPerBar = DefaultTicksPerBar / DefaultStepsPerBar
Definition at line 40 of file TimePos.h.
Referenced by lmms::TimePos::stepsPerBar().
DefaultKey
const int lmms::DefaultKey = DefaultOctave + Key::A
Definition at line 87 of file Note.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::gui::InstrumentTrackView::activityIndicatorPressed(), lmms::gui::InstrumentTrackView::activityIndicatorReleased(), and lmms::InstrumentTrack::masterKey().
DefaultMiddleKey
const int lmms::DefaultMiddleKey = Octave::Octave_4 + Key::C
Definition at line 91 of file Note.h.
Referenced by lmms::Keymap::Keymap(), and lmms::gui::MicrotunerConfig::MicrotunerConfig().
DefaultOctave
auto lmms::DefaultOctave = Octave::Octave_4 constexpr
Definition at line 86 of file Note.h.
Referenced by lmms::gui::PianoView::getKeyFromKeyEvent().
DefaultPanning
panning_t lmms::DefaultPanning = PanningCenter inline constexpr
Definition at line 41 of file panning.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::gui::PianoRoll::PianoRoll(), lmms::SampleTrack::SampleTrack(), lmms::gui::PianoRoll::mouseMoveEvent(), and lmms::gui::PianoRoll::reset().
DefaultPitch
pitch_t lmms::DefaultPitch = 0 constexpr
Definition at line 38 of file Pitch.h.
DefaultStepsPerBar
const int lmms::DefaultStepsPerBar = 16
Definition at line 39 of file TimePos.h.
DefaultTempo
const bpm_t lmms::DefaultTempo = 140
Definition at line 59 of file Song.h.
Referenced by lmms::Song::Song(), and lmms::Song::createNewProject().
DefaultTicksPerBar
const int lmms::DefaultTicksPerBar = 192
Definition at line 38 of file TimePos.h.
Referenced by lmms::gui::PianoRoll::PianoRoll(), lmms::Song::Song(), lmms::MidiClip::addStepNote(), lmms::gui::PianoRoll::dragNotes(), lmms::Engine::framesPerTick(), lmms::gui::PianoRoll::newNoteLen(), lmms::gui::AutomationEditor::paintEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::SampleClipView::paintEvent(), lmms::gui::PianoRoll::quantization(), lmms::PatternStore::removePattern(), lmms::gui::AutomationEditor::setQuantization(), lmms::SampleClip::setSampleFile(), lmms::TimePos::ticksPerBar(), lmms::Engine::updateFramesPerTick(), lmms::PatternStore::updatePatternTrack(), and lmms::DataFile::upgrade_noteTypes().
DefaultVolume
volume_t lmms::DefaultVolume = 100 constexpr
Definition at line 37 of file volume.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::gui::PianoRoll::PianoRoll(), lmms::SamplePlayHandle::SamplePlayHandle(), lmms::SampleTrack::SampleTrack(), lmms::gui::PianoRoll::loadGhostNotes(), lmms::Note::midiVelocity(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::InstrumentTrack::processAudioBuffer(), lmms::gui::PianoRoll::reset(), and lmms::MidiEvent::volume().
dENV
const int lmms::dENV = 3
Definition at line 49 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), and lmms::DrumSynth::UpdateEnv().
DF
float lmms::DF[1200]
Definition at line 59 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
dummyLoader
PixmapLoader lmms::dummyLoader static
Definition at line 43 of file Plugin.cpp.
dummyPluginDescriptor
Plugin::Descriptor lmms::dummyPluginDescriptor static
Initial value:
=
{
    "dummy",
    "dummy",
    QT_TRANSLATE_NOOP( "PluginBrowser", "no description" ),
    "Tobias Doerffel <tobydox/at/users.sf.net>",
    0x0100,
    Plugin::Type::Undefined,
    &dummyLoader,
    nullptr
}
Definition at line 45 of file Plugin.cpp.
Referenced by lmms::Plugin::Plugin().
DynamicChannelCount
auto lmms::DynamicChannelCount = static_cast<proc_ch_t>(-1) inline constexpr
Use when the number of channels is not known at compile time.
Definition at line 42 of file AudioBufferView.h.
Referenced by lmms::InterleavedBufferView< T, channelCount >::frame(), lmms::InterleavedBufferView< T, channelCount >::framesView(), lmms::InterleavedBufferView< T, channelCount >::framesView(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator+, lmms::detail::InterleavedFrameIterator< T, channelCount >::operator-(), and lmms::InterleavedBufferView< T, channelCount >::subspan().
ENV
const int lmms::ENV = 1
Definition at line 47 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), and lmms::DrumSynth::UpdateEnv().
envData
float lmms::envData[8][6]
Definition at line 55 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), lmms::DrumSynth::GetEnv(), lmms::DrumSynth::LongestEnv(), and lmms::DrumSynth::UpdateEnv().
envpts
float lmms::envpts[8][3][32]
Definition at line 54 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetEnv(), lmms::DrumSynth::LongestEnv(), and lmms::DrumSynth::UpdateEnv().
EO_ID_MSB
const int lmms::EO_ID_MSB = 1 << 23 static
Avoid clashes between loaded IDs (have the bit cleared) and newly created IDs (have the bit set).
Definition at line 39 of file ProjectJournal.cpp.
Referenced by lmms::ProjectJournal::allocID(), lmms::ProjectJournal::idFromSave(), and lmms::ProjectJournal::idToSave().
F_EPSILON
float lmms::F_EPSILON = 1.0e-10f inline constexpr
Definition at line 35 of file lmms_constants.h.
Referenced by approximatelyEqual(), roundAt(), lmms::BasicFilters< CHANNELS >::update(), and lmms::OnePole< 2 >::update().
FFT_BLOCK_SIZES
const std::vector<unsigned int> lmms::FFT_BLOCK_SIZES = {256, 512, 1024, 2048, 4096, 8192, 16384}
Definition at line 44 of file fft_helpers.h.
FFT_BUFFER_SIZE
auto lmms::FFT_BUFFER_SIZE = std::size_t{2048} constexpr
Definition at line 40 of file fft_helpers.h.
FILENAME_FILTER
char const* const lmms::FILENAME_FILTER = "[\\0000-\x1f\"*/:<>?\\\\|\x7f]"
Definition at line 63 of file Track.h.
Referenced by lmms::RenderManager::pathForTrack(), and lmms::gui::InstrumentTrackWindow::saveSettingsBtnClicked().
FirstOctave
const int lmms::FirstOctave = -1
Definition at line 78 of file Note.h.
Referenced by lmms::gui::getNoteString(), and lmms::gui::PianoView::paintEvent().
FRANGE_AUDIBLE_END
auto lmms::FRANGE_AUDIBLE_END = 20000 inline constexpr
Definition at line 60 of file lmms_constants.h.
FRANGE_AUDIBLE_START
auto lmms::FRANGE_AUDIBLE_START = 20 inline constexpr
Definition at line 59 of file lmms_constants.h.
FRANGE_BASS_END
auto lmms::FRANGE_BASS_END = 300 inline constexpr
Definition at line 62 of file lmms_constants.h.
FRANGE_BASS_START
auto lmms::FRANGE_BASS_START = 20 inline constexpr
Definition at line 61 of file lmms_constants.h.
FRANGE_HIGH_END
auto lmms::FRANGE_HIGH_END = 20000 inline constexpr
Definition at line 66 of file lmms_constants.h.
FRANGE_HIGH_START
auto lmms::FRANGE_HIGH_START = 4000 inline constexpr
Definition at line 65 of file lmms_constants.h.
FRANGE_MIDS_END
auto lmms::FRANGE_MIDS_END = 5000 inline constexpr
Definition at line 64 of file lmms_constants.h.
FRANGE_MIDS_START
auto lmms::FRANGE_MIDS_START = 200 inline constexpr
Definition at line 63 of file lmms_constants.h.
GIG_PATH
const QString lmms::GIG_PATH = "samples/gig/"
Definition at line 47 of file ConfigManager.h.
Referenced by lmms::ConfigManager::ConfigManager(), and lmms::ConfigManager::userGigDir().
INITIAL_NPH_CACHE
const int lmms::INITIAL_NPH_CACHE = 256
Definition at line 336 of file NotePlayHandle.h.
Referenced by lmms::NotePlayHandleManager::init().
KBD_COPY_MODIFIER
Qt::KeyboardModifier lmms::KBD_COPY_MODIFIER constexpr
Initial value:
=
Qt::ControlModifier
Definition at line 68 of file KeyboardShortcuts.h.
Referenced by lmms::gui::ClipView::mouseMoveEvent(), lmms::gui::AutomatableButton::mousePressEvent(), lmms::gui::AutomatableModelView::mousePressEvent(), lmms::gui::ClipView::mousePressEvent(), lmms::gui::Fader::mousePressEvent(), lmms::gui::FloatModelEditorBase::mousePressEvent(), lmms::gui::LcdFloatSpinBox::mousePressEvent(), lmms::gui::LcdSpinBox::mousePressEvent(), and lmms::gui::TrackOperationsWidget::mousePressEvent().
KEY_ORDER
const auto lmms::KEY_ORDER static
Initial value:
= std::array
{
    Piano::KeyType::White, Piano::KeyType::Black, Piano::KeyType::White, Piano::KeyType::Black,
    Piano::KeyType::White, Piano::KeyType::White, Piano::KeyType::Black, Piano::KeyType::White,
    Piano::KeyType::Black, Piano::KeyType::White, Piano::KeyType::Black, Piano::KeyType::White
}
The black / white order of keys as they appear on the keyboard.
Definition at line 50 of file Piano.cpp.
Referenced by lmms::Piano::isBlackKey().
KeysPerOctave
const int lmms::KeysPerOctave = 12
Definition at line 79 of file Note.h.
Referenced by lmms::gui::PianoView::getKeyFromKeyEvent(), lmms::gui::PianoView::getKeyFromMouse(), lmms::gui::getNoteString(), lmms::Piano::isBlackKey(), lmms::Note::loadSettings(), operator+(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::PianoView::paintEvent(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), and lmms::gui::PianoRoll::trackOctaveSize().
LADSPA_PATH
const QString lmms::LADSPA_PATH ="plugins/ladspa/"
Definition at line 49 of file ConfigManager.h.
Referenced by lmms::ConfigManager::userLadspaDir().
LADSPA_PATH_SEPERATOR
char lmms::LADSPA_PATH_SEPERATOR constexpr
Initial value:
=
':'
Definition at line 90 of file lmms_constants.h.
Referenced by lmms::LadspaManager::LadspaManager().
LOCALE_PATH
const QString lmms::LOCALE_PATH = "locale/"
Definition at line 52 of file ConfigManager.h.
Referenced by lmms::ConfigManager::localeDir().
LOWEST_LOG_FREQ
auto lmms::LOWEST_LOG_FREQ = 5 inline constexpr
Definition at line 47 of file lmms_constants.h.
MAX
const int lmms::MAX = 0
Definition at line 46 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), lmms::DrumSynth::GetEnv(), and lmms::DrumSynth::LongestEnv().
MaxDetuning
const float lmms::MaxDetuning = 5 * 12.0f
Definition at line 95 of file Note.h.
Referenced by lmms::Note::createDetuning().
MAXIMUM_BUFFER_SIZE
fpp_t lmms::MAXIMUM_BUFFER_SIZE = 4096 constexpr
Definition at line 54 of file AudioEngine.h.
Referenced by lmms::gui::SetupDialog::SetupDialog().
MaxKeymapCount
unsigned lmms::MaxKeymapCount = 10 inline constexpr
number of keyboard mappings per project
Definition at line 41 of file lmms_constants.h.
Referenced by lmms::Microtuner::Microtuner(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::Song::getKeymap(), lmms::Song::restoreKeymapStates(), lmms::Song::setKeymap(), lmms::gui::MicrotunerConfig::updateKeymapList(), and lmms::Microtuner::updateKeymapList().
MAXLEN
int lmms::MAXLEN = 11 constexpr
Definition at line 42 of file BandLimitedWave.h.
MaxPitchDefault
pitch_t lmms::MaxPitchDefault = CentsPerSemitone constexpr
Definition at line 37 of file Pitch.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), and lmms::InstrumentTrack::updatePitchRange().
MaxScaleCount
unsigned lmms::MaxScaleCount = 10 inline constexpr
number of scales per project
Definition at line 40 of file lmms_constants.h.
Referenced by lmms::Microtuner::Microtuner(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::Song::getScale(), lmms::Song::restoreScaleStates(), lmms::Song::setScale(), lmms::gui::MicrotunerConfig::updateScaleList(), and lmms::Microtuner::updateScaleList().
MaxSongLength
const tick_t lmms::MaxSongLength = 9999 * DefaultTicksPerBar
Definition at line 61 of file Song.h.
Referenced by lmms::gui::SongEditor::keyPressEvent().
MAXTBL
int lmms::MAXTBL = 23 constexpr
Definition at line 45 of file BandLimitedWave.h.
Referenced by lmms::BandLimitedWave::generateWaves(), operator<<(), and operator>>().
MaxTempo
const bpm_t lmms::MaxTempo = 999
Definition at line 60 of file Song.h.
Referenced by lmms::Song::Song().
MAXTLEN
int lmms::MAXTLEN = 3 << MAXLEN constexpr
Definition at line 47 of file BandLimitedWave.h.
MaxVolume
volume_t lmms::MaxVolume = 200 constexpr
Definition at line 36 of file volume.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::Note::Note(), lmms::SamplePlayHandle::SamplePlayHandle(), lmms::SampleTrack::SampleTrack(), lmms::gui::PianoRoll::drawNoteRect(), lmms::gui::PianoRoll::enterValue(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::Note::setVolume(), and lmms::gui::PianoRoll::wheelEvent().
mem_b
float lmms::mem_b = 1.0f
Definition at line 63 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
mem_n
float lmms::mem_n = 1.0f
Definition at line 63 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
mem_o
float lmms::mem_o = 1.0f
Definition at line 63 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
mem_t
float lmms::mem_t = 1.0f
Definition at line 63 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
mem_time
float lmms::mem_time = 1.0f
Definition at line 63 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
mem_tune
float lmms::mem_tune = 1.0f
Definition at line 63 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
MidiChannelCount
const int lmms::MidiChannelCount = 16
Definition at line 127 of file Midi.h.
Referenced by lmms::MidiPort::MidiPort().
MidiControllerCount
const int lmms::MidiControllerCount = 128
Definition at line 128 of file Midi.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::gui::MidiCCRackView::MidiCCRackView(), lmms::MidiPort::MidiPort(), lmms::InstrumentTrack::loadTrackSpecificSettings(), and lmms::InstrumentTrack::saveTrackSpecificSettings().
MidiDefaultVelocity
const int lmms::MidiDefaultVelocity = MidiMaxVelocity / 2
Definition at line 131 of file Midi.h.
Referenced by lmms::gui::InstrumentTrackView::activityIndicatorPressed(), lmms::gui::PianoRoll::mouseMoveEvent(), and lmms::gui::PianoRoll::mousePressEvent().
MidiMaxControllerValue
const int lmms::MidiMaxControllerValue = 127
Definition at line 132 of file Midi.h.
Referenced by lmms::InstrumentTrack::processInEvent().
MidiMaxKey
const int lmms::MidiMaxKey = 127
Definition at line 133 of file Midi.h.
Referenced by lmms::MidiPort::MidiPort(), and writeToByteSeq().
MidiMaxPanning
const int lmms::MidiMaxPanning = 127
Definition at line 135 of file Midi.h.
Referenced by lmms::MidiEvent::panning(), and panningToMidi().
MidiMaxPitchBend
const int lmms::MidiMaxPitchBend = 16383
Definition at line 139 of file Midi.h.
Referenced by lmms::InstrumentTrack::midiPitch(), and lmms::InstrumentTrack::processInEvent().
MidiMaxVelocity
const int lmms::MidiMaxVelocity = 127
Definition at line 130 of file Midi.h.
Referenced by lmms::MidiPort::MidiPort(), lmms::MidiPort::loadSettings(), and lmms::Note::midiVelocity().
MidiMinPanning
const int lmms::MidiMinPanning = -128
Definition at line 136 of file Midi.h.
Referenced by lmms::MidiEvent::panning(), and panningToMidi().
MidiMinPitchBend
const int lmms::MidiMinPitchBend = 0
Definition at line 138 of file Midi.h.
MidiProgramCount
const int lmms::MidiProgramCount = 128
Definition at line 129 of file Midi.h.
Referenced by lmms::MidiPort::MidiPort().
MINIMAL_TRACK_HEIGHT
const int lmms::MINIMAL_TRACK_HEIGHT = 32
The minimum track height in pixels.
Tracks can be resized by shift-dragging anywhere inside the track display. This sets the minimum size in pixels for a track.
Definition at line 60 of file Track.h.
Referenced by lmms::Track::getHeight(), lmms::Track::loadTrack(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::TrackView::resizeToHeight(), and lmms::Track::saveTrack().
MINIMUM_BUFFER_SIZE
fpp_t lmms::MINIMUM_BUFFER_SIZE = 32 constexpr
Definition at line 52 of file AudioEngine.h.
Referenced by lmms::AudioEngine::AudioEngine().
minimumFrames
const f_cnt_t lmms::minimumFrames = 1
Definition at line 45 of file EnvelopeAndLfoParameters.cpp.
Referenced by lmms::EnvelopeAndLfoParameters::fillLfoLevel(), and lmms::EnvelopeAndLfoParameters::updateSampleVars().
MinPitchDefault
pitch_t lmms::MinPitchDefault = -CentsPerSemitone constexpr
Definition at line 36 of file Pitch.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), and lmms::InstrumentTrack::updatePitchRange().
MinTempo
const bpm_t lmms::MinTempo = 10
Definition at line 58 of file Song.h.
Referenced by lmms::Song::Song().
MINTLEN
int lmms::MINTLEN = 2 << 0 constexpr
Definition at line 46 of file BandLimitedWave.h.
MinVolume
volume_t lmms::MinVolume = 0 constexpr
Definition at line 35 of file volume.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::Note::Note(), lmms::SamplePlayHandle::SamplePlayHandle(), lmms::SampleTrack::SampleTrack(), lmms::gui::PianoRoll::drawNoteRect(), lmms::gui::PianoRoll::enterValue(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::Note::setVolume(), and lmms::gui::PianoRoll::wheelEvent().
MIPMAPSIZE
int lmms::MIPMAPSIZE = 2 << (MAXLEN + 1) constexpr
Definition at line 43 of file BandLimitedWave.h.
MIPMAPSIZE3
int lmms::MIPMAPSIZE3 = 3 << (MAXLEN + 1) constexpr
Definition at line 44 of file BandLimitedWave.h.
NEXTT
const int lmms::NEXTT = 4
Definition at line 50 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), and lmms::DrumSynth::UpdateEnv().
NOHINT
const float lmms::NOHINT = -99342.2243f
Definition at line 45 of file LadspaManager.h.
Referenced by lmms::LadspaManager::getDefaultSetting(), lmms::LadspaManager::getLowerBound(), and lmms::LadspaManager::getUpperBound().
NPH_CACHE_INCREMENT
const int lmms::NPH_CACHE_INCREMENT = 16
Definition at line 337 of file NotePlayHandle.h.
Referenced by lmms::NotePlayHandleManager::acquire().
NumKeys
const int lmms::NumKeys = 128
Number of physical keys, limited to MIDI range (valid for both MIDI 1.0 and 2.0).
Definition at line 89 of file Note.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::Keymap::Keymap(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::Note::Note(), lmms::gui::PianoView::PianoView(), lmms::gui::PianoRoll::dragNotes(), lmms::gui::PianoRoll::focusOutEvent(), lmms::gui::PianoView::focusOutEvent(), lmms::gui::PianoRoll::getAllOctavesForKey(), lmms::gui::PianoRoll::getKey(), lmms::gui::PianoView::getKeyFromMouse(), lmms::Piano::isValidKey(), lmms::Microtuner::keyToFreq(), lmms::gui::PianoRoll::markSemiTone(), lmms::InstrumentTrack::masterKey(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::PianoView::paintEvent(), lmms::MidiPort::processInEvent(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), lmms::InstrumentTrack::processOutEvent(), lmms::gui::PianoRoll::setCurrentMidiClip(), lmms::Note::setKey(), lmms::InstrumentTrack::silenceAllNotes(), lmms::gui::MidiClipView::transposeSelection(), lmms::gui::PianoRoll::updateScrollbars(), and lmms::gui::PianoRoll::updateYScroll().
OUTPUT_SAMPLE_MULTIPLIER
float lmms::OUTPUT_SAMPLE_MULTIPLIER = 32767.0f constexpr
Definition at line 60 of file AudioEngine.h.
Referenced by lmms::AudioDevice::convertToS16().
PanningCenter
panning_t lmms::PanningCenter = 0 inline constexpr
Definition at line 40 of file panning.h.
Referenced by panningToVolumeVector().
PanningLeft
panning_t lmms::PanningLeft = -PanningRight inline constexpr
Definition at line 39 of file panning.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::Note::Note(), lmms::SampleTrack::SampleTrack(), lmms::gui::PianoRoll::drawNoteRect(), lmms::gui::PianoRoll::enterValue(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::MidiEvent::panning(), panningToMidi(), lmms::InstrumentTrack::processAudioBuffer(), lmms::Note::setPanning(), and lmms::gui::PianoRoll::wheelEvent().
PanningRight
panning_t lmms::PanningRight = 100 inline constexpr
Definition at line 38 of file panning.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::Note::Note(), lmms::SampleTrack::SampleTrack(), lmms::gui::PianoRoll::drawNoteRect(), lmms::gui::PianoRoll::enterValue(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::MidiEvent::panning(), panningToMidi(), lmms::InstrumentTrack::processAudioBuffer(), lmms::Note::setPanning(), and lmms::gui::PianoRoll::wheelEvent().
phi
float lmms::phi[1200]
Definition at line 60 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
PNT
const int lmms::PNT = 2
Definition at line 48 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), and lmms::DrumSynth::UpdateEnv().
PORTABLE_MODE_FILE
const QString lmms::PORTABLE_MODE_FILE = "/portable_mode.txt"
Definition at line 53 of file ConfigManager.h.
Referenced by lmms::ConfigManager::ConfigManager().
PRESETS_PATH
const QString lmms::PRESETS_PATH = "presets/"
Definition at line 45 of file ConfigManager.h.
Referenced by lmms::ConfigManager::factoryPresetsDir(), and lmms::ConfigManager::userPresetsDir().
PROJECTS_PATH
const QString lmms::PROJECTS_PATH = "projects/"
Definition at line 43 of file ConfigManager.h.
Referenced by lmms::ConfigManager::factoryProjectsDir(), and lmms::ConfigManager::userProjectsDir().
RAW_MIDI_PARSE_BUF_SIZE
const uint32_t lmms::RAW_MIDI_PARSE_BUF_SIZE = 16
Definition at line 121 of file MidiClient.h.
Referenced by lmms::MidiClientRaw::parseData().
REMAINS_80E0
const auto lmms::REMAINS_80E0 static
Initial value:
= std::array<unsigned char, 7>
{
    3,
    3,
    3,
    3,
    2,
    2,
    3
}
Definition at line 286 of file MidiClient.cpp.
Referenced by lmms::MidiClientRaw::eventLength().
REMAINS_F0F6
const auto lmms::REMAINS_F0F6 static
Initial value:
= std::array<unsigned char, 7>
{
    0,
    2,
    3,
    2,
    2,
    2,
    1
}
Definition at line 275 of file MidiClient.cpp.
Referenced by lmms::MidiClientRaw::eventLength().
REMOVE_RELEASED_NOTE_TIME_THRESHOLD_MS
const int lmms::REMOVE_RELEASED_NOTE_TIME_THRESHOLD_MS = 70
Definition at line 37 of file StepRecorder.cpp.
Referenced by lmms::StepRecorder::noteReleased(), and lmms::StepRecorder::removeNotesReleasedForTooLong().
RES_MULTIPLIER
const float lmms::RES_MULTIPLIER = 2.0f
Definition at line 41 of file InstrumentSoundShaping.cpp.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer().
RES_PRECISION
const float lmms::RES_PRECISION = 1000.0f
Definition at line 42 of file InstrumentSoundShaping.cpp.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer().
s_dummyClient
MidiDummy lmms::s_dummyClient static
Definition at line 41 of file MidiPort.cpp.
Referenced by lmms::MidiPort::invalidateCilent().
s_renderingThread
bool lmms::s_renderingThread = false thread_local static
Definition at line 68 of file AudioEngine.cpp.
Referenced by lmms::AudioEngine::doneChangeInModel(), lmms::AudioEngine::renderNextBuffer(), and lmms::AudioEngine::requestChangeInModel().
SAMPLES_PATH
const QString lmms::SAMPLES_PATH = "samples/"
Definition at line 46 of file ConfigManager.h.
Referenced by lmms::ConfigManager::factorySamplesDir(), and lmms::ConfigManager::userSamplesDir().
SECS_PER_ENV_SEGMENT
const float lmms::SECS_PER_ENV_SEGMENT = 5.0f extern
Referenced by lmms::EnvelopeAndLfoParameters::updateSampleVars().
SECS_PER_LFO_OSCILLATION
const float lmms::SECS_PER_LFO_OSCILLATION = 20.0f extern
Definition at line 40 of file LfoGraph.cpp.
Referenced by lmms::EnvelopeAndLfoParameters::EnvelopeAndLfoParameters(), lmms::gui::LfoGraph::drawInfoText(), lmms::gui::LfoGraph::paintEvent(), and lmms::EnvelopeAndLfoParameters::updateSampleVars().
SF2_PATH
const QString lmms::SF2_PATH = "samples/soundfonts/"
Definition at line 48 of file ConfigManager.h.
Referenced by lmms::ConfigManager::ConfigManager(), and lmms::ConfigManager::userSf2Dir().
SHM_FIFO_SIZE
const int lmms::SHM_FIFO_SIZE = 512*1024
Definition at line 92 of file RemotePluginBase.h.
Referenced by lmms::shmFifo::write().
SIZEOF_SET
const size_t lmms::SIZEOF_SET = sizeof(int) * 8 static
Definition at line 39 of file LocklessAllocator.cpp.
Referenced by lmms::LocklessAllocator::LocklessAllocator(), lmms::LocklessAllocator::alloc(), and lmms::LocklessAllocator::free().
sliLev
int lmms::sliLev[8]
Definition at line 56 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), and lmms::DrumSynth::LoudestEnv().
SUPPORTED_SAMPLERATES
auto lmms::SUPPORTED_SAMPLERATES = std::array{44100, 48000, 88200, 96000, 192000} constexpr
Definition at line 62 of file AudioEngine.h.
Referenced by lmms::AudioEngine::AudioEngine(), lmms::gui::ExportProjectDialog::ExportProjectDialog(), and lmms::gui::SetupDialog::SetupDialog().
TEMPLATE_PATH
const QString lmms::TEMPLATE_PATH = "templates/"
Definition at line 44 of file ConfigManager.h.
Referenced by lmms::ConfigManager::factoryTemplatesDir(), and lmms::ConfigManager::userTemplateDir().
timestretch
float lmms::timestretch
Definition at line 57 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples(), lmms::DrumSynth::LongestEnv(), and lmms::DrumSynth::UpdateEnv().
TLENS
const int lmms::TLENS[MAXTBL+1]
Initial value:
= { 2 << 0, 3 << 0, 2 << 1, 3 << 1,
                    2 << 2, 3 << 2, 2 << 3, 3 << 3,
                    2 << 4, 3 << 4, 2 << 5, 3 << 5,
                    2 << 6, 3 << 6, 2 << 7, 3 << 7,
                    2 << 8, 3 << 8, 2 << 9, 3 << 9,
                    2 << 10, 3 << 10, 2 << 11, 3 << 11 }
Definition at line 50 of file BandLimitedWave.h.
Referenced by lmms::BandLimitedWave::generateWaves(), operator<<(), operator>>(), lmms::BandLimitedWave::oscillate(), lmms::WaveMipMap::sampleAt(), and lmms::WaveMipMap::setSampleAt().
TRACK_ICON_PATH
const QString lmms::TRACK_ICON_PATH = "track_icons/"
Definition at line 51 of file ConfigManager.h.
Referenced by lmms::ConfigManager::trackIconsDir().
UI_ALT_KEY
const char* lmms::UI_ALT_KEY constexpr
Initial value:
=
"Alt"
Definition at line 50 of file KeyboardShortcuts.h.
UI_COPY_KEY
const char* lmms::UI_COPY_KEY constexpr
Initial value:
=
UI_CTRL_KEY
Definition at line 59 of file KeyboardShortcuts.h.
Referenced by lmms::gui::ClipView::mousePressEvent(), and lmms::AutomationClip::name().
UI_CTRL_KEY
const char* lmms::UI_CTRL_KEY constexpr
Initial value:
=
"Ctrl"
Definition at line 43 of file KeyboardShortcuts.h.
Referenced by lmms::gui::PianoRollWindow::PianoRollWindow(), lmms::gui::TrackOperationsWidget::TrackOperationsWidget(), lmms::gui::ClipView::contextMenuEvent(), lmms::gui::FileBrowserTreeWidget::getContextActions(), lmms::gui::TimeLineWidget::mousePressEvent(), and lmms::gui::ProjectNotes::setupActions().
wavemode
long lmms::wavemode = 0
Definition at line 62 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().
wavewords
long lmms::wavewords
Definition at line 62 of file DrumSynth.cpp.
Referenced by lmms::DrumSynth::GetDSFileSamples().