LMMS: src/3rdparty/jack2/common/JackAudioAdapterFactory.cpp File Reference
JackAudioAdapterFactory.cpp File Reference
#include "JackAudioAdapter.h"
#include "JackPlatformPlug.h"
#include "JackArgParser.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
Functions
SERVER_EXPORT void jack_finish (void *arg)
SERVER_EXPORT int jack_initialize (jack_client_t *jack_client, const char *load_init)
SERVER_EXPORT int jack_internal_initialize (jack_client_t *jack_client, const JSList *params)
Function Documentation
jack_finish()
SERVER_EXPORT void jack_finish (void * arg)
Definition at line 100 of file JackAudioAdapterFactory.cpp.
References Jack::JackAudioAdapter::Close(), jack_log(), and SERVER_EXPORT.
jack_initialize()
SERVER_EXPORT int jack_initialize (jack_client_t * jack_client, const char * load_init)
Definition at line 81 of file JackAudioAdapterFactory.cpp.
References Jack::JackArgParser::FreeParams(), Jack::JackArgParser::GetArgc(), jack_get_descriptor(), jack_internal_initialize(), Jack::JackArgParser::ParseParams(), and SERVER_EXPORT.
jack_internal_initialize()
SERVER_EXPORT int jack_internal_initialize (jack_client_t * jack_client, const JSList * params)
Definition at line 55 of file JackAudioAdapterFactory.cpp.
References jack_get_buffer_size(), jack_get_sample_rate(), jack_info(), jack_log(), Jack::JackAudioAdapter::Open(), and SERVER_EXPORT.
Referenced by jack_initialize().