LMMS: Jack::JackClientInterface Class Reference
Jack::JackClientInterface Class Reference abstract
Client interface.
#include <JackClientInterface.h>
Public Member Functions
JackClientInterface ()
virtual ~JackClientInterface ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)=0
virtual int Close ()=0
virtual JackClientControl * GetClientControl () const =0
Detailed Description
Client interface.
Definition at line 35 of file JackClientInterface.h.
Constructor & Destructor Documentation
JackClientInterface()
Jack::JackClientInterface::JackClientInterface () inline
Definition at line 40 of file JackClientInterface.h.
~JackClientInterface()
virtual Jack::JackClientInterface::~JackClientInterface () inline virtual
Definition at line 42 of file JackClientInterface.h.
Member Function Documentation
ClientNotify()
virtual int Jack::JackClientInterface::ClientNotify (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value2) pure virtual
Implemented in Jack::JackAudioDriver, Jack::JackClient, Jack::JackDebugClient, Jack::JackDriver, Jack::JackExternalClient, and Jack::JackThreadedDriver.
Close()
virtual int Jack::JackClientInterface::Close () pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackALSARawMidiDriver, Jack::JackBoomerDriver, Jack::JackClient, Jack::JackCoreAudioDriver, Jack::JackCoreMidiDriver, Jack::JackDebugClient, Jack::JackDriver, Jack::JackExternalClient, Jack::JackFFADODriver, Jack::JackGoldfishDriver, Jack::JackIIODriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackOpenSLESDriver, Jack::JackOSSDriver, Jack::JackOSSDriver, Jack::JackPortAudioDriver, Jack::JackProxyDriver, Jack::JackThreadedDriver, Jack::JackWinMMEDriver, JackAlsaDriver, JackALSARawMidiDriver, and JackWinMMEDriver.
Referenced by Jack::JackServer::AddSlave(), Jack::JackAlsaDriver::Close(), Jack::JackALSARawMidiDriver::Close(), Jack::JackBoomerDriver::Close(), Jack::JackFFADODriver::Close(), Jack::JackGoldfishDriver::Close(), Jack::JackIIODriver::Close(), Jack::JackNetDriver::Close(), Jack::JackNetOneDriver::Close(), Jack::JackOpenSLESDriver::Close(), Jack::JackOSSDriver::Close(), Jack::JackPortAudioDriver::Close(), Jack::JackProxyDriver::Close(), Jack::JackWinMMEDriver::Close(), Jack::JackFFADODriver::Open(), Jack::JackPortAudioDriver::Open(), and Jack::JackServer::RemoveSlave().
GetClientControl()
virtual JackClientControl * Jack::JackClientInterface::GetClientControl () const pure virtual
Implemented in Jack::JackDebugClient, Jack::JackDriver, Jack::JackExternalClient, Jack::JackInternalClient, Jack::JackLibClient, and Jack::JackThreadedDriver.
Referenced by Jack::JackClient::Activate(), Jack::JackClient::ActivateAux(), Jack::JackClient::CallSyncCallbackAux(), Jack::JackClient::CallTimebaseCallbackAux(), Jack::JackClient::ClientNotify(), Jack::JackClient::Close(), Jack::JackClient::Deactivate(), Jack::JackClient::End(), Jack::JackClient::Error(), Jack::JackClient::GetClientNameByUUID(), Jack::JackClient::GetInternalClientName(), Jack::JackClient::GetUUIDForClientName(), Jack::JackClient::InternalClientHandle(), Jack::JackClient::InternalClientLoad(), Jack::JackClient::InternalClientUnload(), Jack::JackClient::IsActive(), Jack::JackEngine::NotifyAddClient(), Jack::JackClient::OnInfoShutdown(), Jack::JackClient::OnShutdown(), Jack::JackClient::PortConnect(), Jack::JackClient::PortDisconnect(), Jack::JackClient::PortDisconnect(), Jack::JackClient::PortIsMine(), Jack::JackClient::PortRegister(), Jack::JackClient::PortRename(), Jack::JackClient::PortUnRegister(), Jack::JackClient::ReleaseTimebase(), Jack::JackClient::ReserveClientName(), Jack::JackClient::SessionNotify(), Jack::JackClient::SessionReply(), Jack::JackClient::SetBufferSizeCallback(), Jack::JackClient::SetFreewheelCallback(), Jack::JackClient::SetGraphOrderCallback(), Jack::JackClient::SetPortConnectCallback(), Jack::JackClient::SetPortRegistrationCallback(), Jack::JackClient::SetPortRenameCallback(), Jack::JackClient::SetSampleRateCallback(), Jack::JackClient::SetSessionCallback(), Jack::JackClient::SetSyncCallback(), Jack::JackClient::SetTimebaseCallback(), Jack::JackClient::SetXRunCallback(), Jack::JackClient::SignalSync(), and Jack::JackClient::WaitSync().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackClientInterface.h