LMMS: Jack::JackTemporaryException Class Reference
Jack::JackTemporaryException Class Reference
Exception thrown by JackEngine in temporary mode.
#include <JackException.h>
Public Member Functions
JackTemporaryException ()
JackTemporaryException (char *msg)
JackTemporaryException (const char *msg)
JackTemporaryException (const std::string &msg)
Public Member Functions inherited from Jack::JackException
JackException (char *msg)
JackException (const char *msg)
JackException (const std::string &msg)
std::string Message ()
void PrintMessage ()
Detailed Description
Exception thrown by JackEngine in temporary mode.
Definition at line 67 of file JackException.h.
Constructor & Destructor Documentation
JackTemporaryException() [1/4]
Jack::JackTemporaryException::JackTemporaryException (const std::string & msg) inline
Definition at line 71 of file JackException.h.
References Jack::JackException::JackException().
JackTemporaryException() [2/4]
Jack::JackTemporaryException::JackTemporaryException (char * msg) inline
Definition at line 73 of file JackException.h.
References Jack::JackException::JackException().
JackTemporaryException() [3/4]
Jack::JackTemporaryException::JackTemporaryException (const char * msg) inline
Definition at line 75 of file JackException.h.
References Jack::JackException::JackException().
JackTemporaryException() [4/4]
Jack::JackTemporaryException::JackTemporaryException () inline
Definition at line 77 of file JackException.h.
References Jack::JackException::JackException().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackException.h