LMMS: lmms::PeakController Class Reference
lmms::PeakController Class Reference
#include <PeakController.h>
Public Slots
gui::ControllerDialog * createDialog (QWidget *_parent) override
void handleDestroyedEffect ()
void updateCoeffs ()
Public Slots inherited from lmms::Controller
virtual gui::ControllerDialog * createDialog (QWidget *_parent)
virtual void setName (const QString &_new_name)
Public Member Functions
PeakController (Model *_parent, PeakControllerEffect *_peak_effect=nullptr)
~PeakController () override
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
Public Member Functions inherited from lmms::Controller
Controller (ControllerType _type, Model *_parent, const QString &_display_name)
~Controller () override
void addConnection (ControllerConnection *)
int connectionCount () const
virtual float currentValue (int _offset)
bool frequentUpdates () const
bool hasModel (const Model *m) const
bool isSampleExact () const
virtual const QString & name () const
void removeConnection (ControllerConnection *)
void setSampleExact (bool _exact)
ControllerType type () const
virtual ValueBuffer * valueBuffer ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static PeakController * getControllerBySetting (const QDomElement &_this)
static void initGetControllerBySetting ()
Static Public Member Functions inherited from lmms::Controller
static Controller * create (const QDomElement &_this, Model *_parent)
static Controller * create (ControllerType _tt, Model *_parent)
static float fittedValue (float _val)
static void resetFrameCounter ()
static unsigned int runningFrames ()
static long runningPeriods ()
static float runningTime ()
static void triggerFrameCounter ()
Static Public Attributes
static PeakControllerEffectVector s_effects
Protected Member Functions
void updateValueBuffer () override
Protected Member Functions inherited from lmms::Controller
virtual float value (int _offset)
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Attributes
PeakControllerEffect * m_peakEffect
Protected Attributes inherited from lmms::Controller
long m_bufferLastUpdated
int m_connectionCount
float m_currentValue
QString m_name
bool m_sampleExact
ControllerType m_type
ValueBuffer m_valueBuffer
Private Attributes
float m_attackCoeff
bool m_coeffNeedsUpdate
float m_currentSample
float m_decayCoeff
Static Private Attributes
static bool m_buggedFile
static int m_getCount
static int m_loadCount
Friends
class PeakControllerDialog
Additional Inherited Members
Public Types inherited from lmms::Controller
enum class ControllerType {
Dummy ,
Lfo ,
Midi ,
Peak
}
Signals inherited from lmms::Controller
void valueChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Protected Attributes inherited from lmms::Controller
static ControllerVector s_controllers
static long s_periods = 0
Detailed Description
Definition at line 41 of file PeakController.h.
Constructor & Destructor Documentation
PeakController()
lmms::PeakController::PeakController (Model * _parent, PeakControllerEffect * _peak_effect = nullptr)
Definition at line 46 of file PeakController.cpp.
References lmms::Controller::Controller(), lmms::Engine::audioEngine(), lmms::Model::dataChanged(), handleDestroyedEffect(), m_coeffNeedsUpdate, m_currentSample, m_peakEffect, lmms::Controller::setSampleExact(), and updateCoeffs().
Referenced by getControllerBySetting().
~PeakController()
lmms::PeakController::~PeakController () override
Definition at line 69 of file PeakController.cpp.
References m_peakEffect.
Member Function Documentation
createDialog
gui::ControllerDialog * lmms::PeakController::createDialog (QWidget * _parent) override slot
Definition at line 250 of file PeakController.cpp.
getControllerBySetting()
PeakController * lmms::PeakController::getControllerBySetting (const QDomElement & _this) static
Definition at line 187 of file PeakController.cpp.
References PeakController(), m_buggedFile, m_getCount, and s_effects.
Referenced by lmms::Controller::create().
handleDestroyedEffect
void lmms::PeakController::handleDestroyedEffect () slot
Definition at line 129 of file PeakController.cpp.
References m_peakEffect.
Referenced by PeakController().
initGetControllerBySetting()
void lmms::PeakController::initGetControllerBySetting () static
Definition at line 177 of file PeakController.cpp.
References m_buggedFile, m_getCount, and m_loadCount.
Referenced by lmms::Song::loadProject().
loadSettings()
void lmms::PeakController::loadSettings (const QDomElement & _this) override virtual
Reimplemented from lmms::Controller.
Definition at line 153 of file PeakController.cpp.
References lmms::Controller::loadSettings(), m_buggedFile, m_loadCount, m_peakEffect, and s_effects.
nodeName()
QString lmms::PeakController::nodeName () const override virtual
Reimplemented from lmms::Controller.
Definition at line 243 of file PeakController.cpp.
saveSettings()
void lmms::PeakController::saveSettings (QDomDocument & _doc, QDomElement & _this) override virtual
Reimplemented from lmms::Controller.
Definition at line 141 of file PeakController.cpp.
References m_peakEffect, and lmms::Controller::saveSettings().
updateCoeffs
void lmms::PeakController::updateCoeffs () slot
Definition at line 123 of file PeakController.cpp.
References m_coeffNeedsUpdate.
Referenced by PeakController().
updateValueBuffer()
void lmms::PeakController::updateValueBuffer () override protected virtual
Reimplemented from lmms::Controller.
Definition at line 78 of file PeakController.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), m_attackCoeff, lmms::Controller::m_bufferLastUpdated, m_coeffNeedsUpdate, m_currentSample, m_decayCoeff, m_peakEffect, lmms::Controller::m_valueBuffer, lmms::AudioEngine::outputSampleRate(), and lmms::Controller::s_periods.
Friends And Related Symbol Documentation
PeakControllerDialog
friend class PeakControllerDialog friend
Definition at line 72 of file PeakController.h.
References PeakControllerDialog.
Referenced by PeakControllerDialog.
Member Data Documentation
m_attackCoeff
float lmms::PeakController::m_attackCoeff private
Definition at line 81 of file PeakController.h.
Referenced by updateValueBuffer().
m_buggedFile
bool lmms::PeakController::m_buggedFile static private
Definition at line 79 of file PeakController.h.
Referenced by getControllerBySetting(), initGetControllerBySetting(), and loadSettings().
m_coeffNeedsUpdate
bool lmms::PeakController::m_coeffNeedsUpdate private
Definition at line 83 of file PeakController.h.
Referenced by PeakController(), updateCoeffs(), and updateValueBuffer().
m_currentSample
float lmms::PeakController::m_currentSample private
Definition at line 75 of file PeakController.h.
Referenced by PeakController(), and updateValueBuffer().
m_decayCoeff
float lmms::PeakController::m_decayCoeff private
Definition at line 82 of file PeakController.h.
Referenced by updateValueBuffer().
m_getCount
int lmms::PeakController::m_getCount static private
Definition at line 77 of file PeakController.h.
Referenced by getControllerBySetting(), and initGetControllerBySetting().
m_loadCount
int lmms::PeakController::m_loadCount static private
Definition at line 78 of file PeakController.h.
Referenced by initGetControllerBySetting(), and loadSettings().
m_peakEffect
PeakControllerEffect* lmms::PeakController::m_peakEffect protected
Definition at line 70 of file PeakController.h.
Referenced by PeakController(), ~PeakController(), handleDestroyedEffect(), loadSettings(), saveSettings(), and updateValueBuffer().
s_effects
PeakControllerEffectVector lmms::PeakController::s_effects static
Definition at line 58 of file PeakController.h.
Referenced by getControllerBySetting(), and loadSettings().
The documentation for this class was generated from the following files:
include/PeakController.h
src/core/PeakController.cpp