LMMS: lmms::AudioBusHandle Class Reference
lmms::AudioBusHandle Class Reference
Job between PlayHandle and MixerChannel.
#include <AudioBusHandle.h>
Public Member Functions
AudioBusHandle (const QString &name, bool hasEffectChain=true, FloatModel *volumeModel=nullptr, FloatModel *panningModel=nullptr, BoolModel *mutedModel=nullptr)
virtual ~AudioBusHandle ()
void addPlayHandle (PlayHandle *handle)
SampleFrame * buffer ()
void doProcessing () override
EffectChain * effects ()
bool extOutputEnabled () const
const QString & name () const
mix_ch_t nextMixerChannel () const
bool processEffects ()
void removePlayHandle (PlayHandle *handle)
bool requiresProcessing () const override
void setExtOutputEnabled (bool enabled)
void setName (const QString &newName)
void setNextMixerChannel (const mix_ch_t chnl)
Public Member Functions inherited from lmms::ThreadableJob
ThreadableJob ()
void done ()
void process ()
void queue ()
void reset ()
ProcessingState state () const
Private Attributes
SampleFrame *const m_buffer
volatile bool m_bufferUsage
std::unique_ptr< EffectChain > m_effects
bool m_extOutputEnabled
BoolModel * m_mutedModel
QString m_name
mix_ch_t m_nextMixerChannel
FloatModel * m_panningModel
QMutex m_playHandleLock
PlayHandleList m_playHandles
FloatModel * m_volumeModel
Friends
class AudioEngine
class AudioEngineWorkerThread
Additional Inherited Members
Public Types inherited from lmms::ThreadableJob
enum class ProcessingState : int {
Unstarted ,
Queued ,
InProgress ,
Done
}
Protected Attributes inherited from lmms::ThreadableJob
std::atomic< ProcessingState > m_state
Detailed Description
Job between PlayHandle and MixerChannel.
A ThreadableJob class located at the exit point of each PlayHandle into a MixerChannel (or into an audio device, in case of AudioJack, but this is not supported in AudioBusHandle yet). It contains an optional EffectChain which is e.g. visualized in the InstrumentTrackWindow or SampleTrackWindow. For processing, it adds all input play handles into an internal buffer, processes the EffectChain (if existing) on that buffer and finally merges the buffer into its MixerChannel.
Definition at line 53 of file AudioBusHandle.h.
Constructor & Destructor Documentation
AudioBusHandle()
lmms::AudioBusHandle::AudioBusHandle (const QString & name, bool hasEffectChain = true, FloatModel * volumeModel = nullptr, FloatModel * panningModel = nullptr, BoolModel * mutedModel = nullptr)
Definition at line 40 of file AudioBusHandle.cpp.
References lmms::AudioEngine::addAudioBusHandle(), lmms::Engine::audioEngine(), m_buffer, m_bufferUsage, m_effects, m_extOutputEnabled, m_mutedModel, m_name, m_nextMixerChannel, m_panningModel, m_volumeModel, name(), and setExtOutputEnabled().
~AudioBusHandle()
lmms::AudioBusHandle::~AudioBusHandle () virtual
Definition at line 60 of file AudioBusHandle.cpp.
References lmms::Engine::audioEngine(), m_buffer, lmms::BufferManager::release(), lmms::AudioEngine::removeAudioBusHandle(), and setExtOutputEnabled().
Member Function Documentation
addPlayHandle()
void lmms::AudioBusHandle::addPlayHandle (PlayHandle * handle)
Definition at line 237 of file AudioBusHandle.cpp.
References m_playHandleLock, and m_playHandles.
Referenced by lmms::AudioEngine::addPlayHandle().
buffer()
SampleFrame * lmms::AudioBusHandle::buffer () inline
Definition at line 61 of file AudioBusHandle.h.
References m_buffer.
doProcessing()
void lmms::AudioBusHandle::doProcessing () override virtual
Implements lmms::ThreadableJob.
Definition at line 109 of file AudioBusHandle.cpp.
References lmms::MixHelpers::add(), lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), lmms::MixHelpers::isSilent(), m_buffer, m_bufferUsage, m_mutedModel, m_nextMixerChannel, m_panningModel, m_playHandles, m_volumeModel, lmms::Engine::mixer(), lmms::Mixer::mixToChannel(), lmms::PlayHandle::NotePlayHandle, processEffects(), lmms::ValueBuffer::values(), and lmms::zeroSampleFrames().
effects()
EffectChain * lmms::AudioBusHandle::effects () inline
Definition at line 75 of file AudioBusHandle.h.
References m_effects.
Referenced by lmms::gui::SampleTrackWindow::SampleTrackWindow().
extOutputEnabled()
bool lmms::AudioBusHandle::extOutputEnabled () const inline
Definition at line 64 of file AudioBusHandle.h.
References m_extOutputEnabled.
name()
const QString & lmms::AudioBusHandle::name () const inline
Definition at line 72 of file AudioBusHandle.h.
References m_name.
Referenced by AudioBusHandle().
nextMixerChannel()
mix_ch_t lmms::AudioBusHandle::nextMixerChannel () const inline
Definition at line 69 of file AudioBusHandle.h.
References m_nextMixerChannel.
processEffects()
bool lmms::AudioBusHandle::processEffects ()
Definition at line 98 of file AudioBusHandle.cpp.
References lmms::Engine::audioEngine(), m_buffer, m_bufferUsage, and m_effects.
Referenced by doProcessing().
removePlayHandle()
void lmms::AudioBusHandle::removePlayHandle (PlayHandle * handle)
Definition at line 244 of file AudioBusHandle.cpp.
References m_playHandleLock, and m_playHandles.
Referenced by lmms::AudioEngine::removePlayHandle().
requiresProcessing()
bool lmms::AudioBusHandle::requiresProcessing () const inline override virtual
Implements lmms::ThreadableJob.
Definition at line 80 of file AudioBusHandle.h.
setExtOutputEnabled()
void lmms::AudioBusHandle::setExtOutputEnabled (bool enabled)
Definition at line 70 of file AudioBusHandle.cpp.
References lmms::AudioEngine::audioDev(), lmms::Engine::audioEngine(), m_extOutputEnabled, lmms::AudioDevice::registerPort(), and lmms::AudioDevice::unregisterPort().
Referenced by AudioBusHandle(), and ~AudioBusHandle().
setName()
void lmms::AudioBusHandle::setName (const QString & newName)
Definition at line 89 of file AudioBusHandle.cpp.
References lmms::AudioEngine::audioDev(), lmms::Engine::audioEngine(), m_name, and lmms::AudioDevice::renamePort().
setNextMixerChannel()
void lmms::AudioBusHandle::setNextMixerChannel (const mix_ch_t chnl) inline
Definition at line 70 of file AudioBusHandle.h.
References m_nextMixerChannel.
Friends And Related Symbol Documentation
AudioEngine
friend class AudioEngine friend
Definition at line 104 of file AudioBusHandle.h.
References AudioEngine.
Referenced by AudioEngine.
AudioEngineWorkerThread
friend class AudioEngineWorkerThread friend
Definition at line 105 of file AudioBusHandle.h.
References AudioEngineWorkerThread.
Referenced by AudioEngineWorkerThread.
Member Data Documentation
m_buffer
SampleFrame* const lmms::AudioBusHandle::m_buffer private
Definition at line 88 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), ~AudioBusHandle(), buffer(), doProcessing(), and processEffects().
m_bufferUsage
volatile bool lmms::AudioBusHandle::m_bufferUsage private
Definition at line 86 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), doProcessing(), and processEffects().
m_effects
std::unique_ptr<EffectChain> lmms::AudioBusHandle::m_effects private
Definition at line 95 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), effects(), and processEffects().
m_extOutputEnabled
bool lmms::AudioBusHandle::m_extOutputEnabled private
Definition at line 90 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), extOutputEnabled(), and setExtOutputEnabled().
m_mutedModel
BoolModel* lmms::AudioBusHandle::m_mutedModel private
Definition at line 102 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), and doProcessing().
m_name
QString lmms::AudioBusHandle::m_name private
Definition at line 93 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), name(), and setName().
m_nextMixerChannel
mix_ch_t lmms::AudioBusHandle::m_nextMixerChannel private
Definition at line 91 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), doProcessing(), nextMixerChannel(), and setNextMixerChannel().
m_panningModel
FloatModel* lmms::AudioBusHandle::m_panningModel private
Definition at line 101 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), and doProcessing().
m_playHandleLock
QMutex lmms::AudioBusHandle::m_playHandleLock private
Definition at line 98 of file AudioBusHandle.h.
Referenced by addPlayHandle(), and removePlayHandle().
m_playHandles
PlayHandleList lmms::AudioBusHandle::m_playHandles private
Definition at line 97 of file AudioBusHandle.h.
Referenced by addPlayHandle(), doProcessing(), and removePlayHandle().
m_volumeModel
FloatModel* lmms::AudioBusHandle::m_volumeModel private
Definition at line 100 of file AudioBusHandle.h.
Referenced by AudioBusHandle(), and doProcessing().
The documentation for this class was generated from the following files:
include/AudioBusHandle.h
src/core/AudioBusHandle.cpp