LMMS: lmms::gui::FileDialog Class Reference
lmms::gui::FileDialog Class Reference
#include <FileDialog.h>
Public Member Functions
FileDialog (QWidget *parent=0, const QString &caption=QString(), const QString &directory=QString(), const QString &filter=QString())
void clearSelection ()
Static Public Member Functions
static QString getExistingDirectory (QWidget *parent, const QString &caption, const QString &directory, QFileDialog::Options options=QFileDialog::ShowDirsOnly)
static QString getOpenFileName (QWidget *parent=0, const QString &caption=QString(), const QString &directory=QString(), const QString &filter=QString(), QString *selectedFilter=0)
Detailed Description
Definition at line 36 of file FileDialog.h.
Constructor & Destructor Documentation
FileDialog()
lmms::gui::FileDialog::FileDialog (QWidget * parent = 0, const QString & caption = QString(), const QString & directory = QString(), const QString & filter = QString()) explicit
Definition at line 39 of file FileDialog.cpp.
References lmms::ConfigManager::inst().
Referenced by lmms::gui::VersionedSaveDialog::VersionedSaveDialog(), getExistingDirectory(), and getOpenFileName().
Member Function Documentation
clearSelection()
void lmms::gui::FileDialog::clearSelection ()
Definition at line 141 of file FileDialog.cpp.
Referenced by lmms::gui::VersionedSaveDialog::decrementVersion(), and lmms::gui::VersionedSaveDialog::incrementVersion().
getExistingDirectory()
QString lmms::gui::FileDialog::getExistingDirectory (QWidget * parent, const QString & caption, const QString & directory, QFileDialog::Options options = QFileDialog::ShowDirsOnly) static
Definition at line 109 of file FileDialog.cpp.
References FileDialog().
Referenced by lmms::gui::SetupDialog::openGIGDir(), lmms::gui::SetupDialog::openLADSPADir(), lmms::gui::SetupDialog::openSF2Dir(), lmms::gui::SetupDialog::openThemeDir(), lmms::gui::SetupDialog::openVSTDir(), and lmms::gui::SetupDialog::openWorkingDir().
getOpenFileName()
QString lmms::gui::FileDialog::getOpenFileName (QWidget * parent = 0, const QString & caption = QString(), const QString & directory = QString(), const QString & filter = QString(), QString * selectedFilter = 0) static
Definition at line 123 of file FileDialog.cpp.
References FileDialog().
Referenced by lmms::gui::MicrotunerConfig::loadKeymapFromFile(), lmms::gui::MicrotunerConfig::loadScaleFromFile(), lmms::gui::SetupDialog::openBackgroundPicFile(), and lmms::gui::SetupDialog::openSF2File().
The documentation for this class was generated from the following files:
include/FileDialog.h
src/gui/modals/FileDialog.cpp