LMMS: lmms::Microtuner Class Reference
lmms::Microtuner Class Reference
#include <Microtuner.h>
Public Member Functions
Microtuner ()
float baseFreq () const
int baseKey () const
int currentKeymap () const
int currentScale () const
bool enabled () const
BoolModel * enabledModel ()
int firstKey () const
ComboBoxModel * keymapModel ()
bool keyRangeImport () const
BoolModel * keyRangeImportModel ()
float keyToFreq (int key, int userBaseNote) const
Return frequency for a given MIDI key, using the active mapping and scale.
int lastKey () const
void loadSettings (const QDomElement &element) override
QString nodeName () const override
int octaveSize () const
void saveSettings (QDomDocument &document, QDomElement &element) override
ComboBoxModel * scaleModel ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Slots
void updateKeymapList (int index)
Update keymap name displayed in the microtuner scale list.
void updateScaleList (int index)
Update scale name displayed in the microtuner scale list.
Private Attributes
BoolModel m_enabledModel
Enable microtuner (otherwise using 12-TET @440 Hz).
ComboBoxModel m_keymapModel
BoolModel m_keyRangeImportModel
ComboBoxModel m_scaleModel
Additional Inherited Members
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 35 of file Microtuner.h.
Constructor & Destructor Documentation
Microtuner()
lmms::Microtuner::Microtuner () explicit
Definition at line 40 of file Microtuner.cpp.
References lmms::Model::Model(), lmms::Engine::getSong(), i, m_enabledModel, m_keymapModel, m_keyRangeImportModel, m_scaleModel, lmms::MaxKeymapCount, lmms::MaxScaleCount, updateKeymapList(), and updateScaleList().
Member Function Documentation
baseFreq()
float lmms::Microtuner::baseFreq () const
References keyToFreq(), and octaveSize().
baseKey()
int lmms::Microtuner::baseKey () const
currentKeymap()
int lmms::Microtuner::currentKeymap () const inline
Definition at line 44 of file Microtuner.h.
References m_keymapModel.
Referenced by octaveSize().
currentScale()
int lmms::Microtuner::currentScale () const inline
Definition at line 43 of file Microtuner.h.
References m_scaleModel.
Referenced by octaveSize().
enabled()
bool lmms::Microtuner::enabled () const inline
Definition at line 41 of file Microtuner.h.
References m_enabledModel.
Referenced by keyRangeImport().
enabledModel()
BoolModel * lmms::Microtuner::enabledModel () inline
Definition at line 46 of file Microtuner.h.
References m_enabledModel.
Referenced by lmms::gui::InstrumentTuningView::InstrumentTuningView().
firstKey()
int lmms::Microtuner::firstKey () const
keymapModel()
ComboBoxModel * lmms::Microtuner::keymapModel () inline
Definition at line 48 of file Microtuner.h.
References m_keymapModel.
Referenced by lmms::gui::InstrumentTuningView::InstrumentTuningView().
keyRangeImport()
bool lmms::Microtuner::keyRangeImport () const inline
Definition at line 42 of file Microtuner.h.
References enabled(), and m_keyRangeImportModel.
keyRangeImportModel()
BoolModel * lmms::Microtuner::keyRangeImportModel () inline
Definition at line 49 of file Microtuner.h.
References m_keyRangeImportModel.
Referenced by lmms::gui::InstrumentTuningView::InstrumentTuningView().
keyToFreq()
float lmms::Microtuner::keyToFreq (int key, int userBaseNote) const
Return frequency for a given MIDI key, using the active mapping and scale.
Parameters
key A MIDI key number ranging from 0 to 127.
Returns
Frequency in Hz; 0 if key is out of range or not mapped.
Definition at line 65 of file Microtuner.cpp.
References lmms::Song::getKeymap(), lmms::Song::getScale(), lmms::Engine::getSong(), m_keymapModel, m_keyRangeImportModel, m_scaleModel, and lmms::NumKeys.
Referenced by baseFreq().
lastKey()
int lmms::Microtuner::lastKey () const
loadSettings()
void lmms::Microtuner::loadSettings (const QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 175 of file Microtuner.cpp.
References m_enabledModel, m_keymapModel, m_keyRangeImportModel, and m_scaleModel.
nodeName()
QString lmms::Microtuner::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 59 of file Microtuner.h.
octaveSize()
int lmms::Microtuner::octaveSize () const
Definition at line 111 of file Microtuner.cpp.
References currentKeymap(), currentScale(), lmms::Song::getKeymap(), lmms::Song::getScale(), and lmms::Engine::getSong().
Referenced by baseFreq().
saveSettings()
void lmms::Microtuner::saveSettings (QDomDocument & document, QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 166 of file Microtuner.cpp.
References m_enabledModel, m_keymapModel, m_keyRangeImportModel, and m_scaleModel.
scaleModel()
ComboBoxModel * lmms::Microtuner::scaleModel () inline
Definition at line 47 of file Microtuner.h.
References m_scaleModel.
Referenced by lmms::gui::InstrumentTuningView::InstrumentTuningView().
updateKeymapList
void lmms::Microtuner::updateKeymapList (int index) protected slot
Update keymap name displayed in the microtuner scale list.
Parameters
index Index of the keymap to update; update all keymaps if -1 or out of range.
Definition at line 148 of file Microtuner.cpp.
References lmms::Engine::getSong(), i, m_keymapModel, and lmms::MaxKeymapCount.
Referenced by Microtuner().
updateScaleList
void lmms::Microtuner::updateScaleList (int index) protected slot
Update scale name displayed in the microtuner scale list.
Parameters
index Index of the scale to update; update all scales if -1 or out of range.
Definition at line 127 of file Microtuner.cpp.
References lmms::Engine::getSong(), i, m_scaleModel, and lmms::MaxScaleCount.
Referenced by Microtuner().
Member Data Documentation
m_enabledModel
BoolModel lmms::Microtuner::m_enabledModel private
Enable microtuner (otherwise using 12-TET @440 Hz).
Definition at line 68 of file Microtuner.h.
Referenced by Microtuner(), enabled(), enabledModel(), loadSettings(), and saveSettings().
m_keymapModel
ComboBoxModel lmms::Microtuner::m_keymapModel private
Definition at line 70 of file Microtuner.h.
Referenced by Microtuner(), currentKeymap(), keymapModel(), keyToFreq(), loadSettings(), saveSettings(), and updateKeymapList().
m_keyRangeImportModel
BoolModel lmms::Microtuner::m_keyRangeImportModel private
Definition at line 71 of file Microtuner.h.
Referenced by Microtuner(), keyRangeImport(), keyRangeImportModel(), keyToFreq(), loadSettings(), and saveSettings().
m_scaleModel
ComboBoxModel lmms::Microtuner::m_scaleModel private
Definition at line 69 of file Microtuner.h.
Referenced by Microtuner(), currentScale(), keyToFreq(), loadSettings(), saveSettings(), scaleModel(), and updateScaleList().
The documentation for this class was generated from the following files:
include/Microtuner.h
src/core/Microtuner.cpp