LMMS: lmms::gui::GroupBox Class Reference
lmms::gui::GroupBox Class Reference
#include <GroupBox.h>
Public Member Functions
GroupBox (const QString &_caption, QWidget *_parent=nullptr)
~GroupBox () override
PixmapButton * ledButton ()
bool ledButtonShown () const
Returns whether the LED button is shown or not.
void modelChanged () override
void setLedButtonShown (bool value)
Sets if the LED check box is shown or not.
int titleBarHeight () const
Public Member Functions inherited from lmms::gui::TypedModelView< BoolModel >
TypedModelView (Model *model, QWidget *_this)
BoolModel * model ()
const BoolModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void mousePressEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *_pe) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Member Functions
void updatePixmap ()
Private Attributes
QString m_caption
PixmapButton * m_led
const int m_titleBarHeight
Additional Inherited Members
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 39 of file GroupBox.h.
Constructor & Destructor Documentation
GroupBox()
lmms::gui::GroupBox::GroupBox (const QString & _caption, QWidget * _parent = nullptr)
Definition at line 36 of file GroupBox.cpp.
References lmms::embed::getIconPixmap(), m_caption, m_led, m_titleBarHeight, and lmms::gui::AutomatableModelView::setModel().
~GroupBox()
lmms::gui::GroupBox::~GroupBox () override
Definition at line 56 of file GroupBox.cpp.
References m_led.
Member Function Documentation
ledButton()
PixmapButton * lmms::gui::GroupBox::ledButton () inline
Definition at line 48 of file GroupBox.h.
References m_led.
ledButtonShown()
bool lmms::gui::GroupBox::ledButtonShown () const
Returns whether the LED button is shown or not.
Returns
true LED button is shown
false LED button is hidden
Definition at line 70 of file GroupBox.cpp.
References m_led.
Referenced by mousePressEvent(), and paintEvent().
modelChanged()
void lmms::gui::GroupBox::modelChanged () override virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 64 of file GroupBox.cpp.
References m_led, and lmms::gui::TypedModelView< BoolModel >::model().
mousePressEvent()
void lmms::gui::GroupBox::mousePressEvent (QMouseEvent * _me) override protected virtual
Reimplemented from lmms::gui::AutomatableModelView.
Definition at line 82 of file GroupBox.cpp.
References ledButtonShown(), lmms::gui::TypedModelView< BoolModel >::model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
paintEvent()
void lmms::gui::GroupBox::paintEvent (QPaintEvent * _pe) override protected
Definition at line 93 of file GroupBox.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, ledButtonShown(), m_caption, and m_titleBarHeight.
setLedButtonShown()
void lmms::gui::GroupBox::setLedButtonShown (bool value)
Sets if the LED check box is shown or not.
Parameters
value Set to true to show the LED check box or to false to hide it.
Definition at line 76 of file GroupBox.cpp.
References m_led, and lmms::gui::AutomatableModelView::value().
titleBarHeight()
int lmms::gui::GroupBox::titleBarHeight () const inline
Definition at line 68 of file GroupBox.h.
References m_titleBarHeight.
updatePixmap()
void lmms::gui::GroupBox::updatePixmap () private
Member Data Documentation
m_caption
QString lmms::gui::GroupBox::m_caption private
Definition at line 83 of file GroupBox.h.
Referenced by GroupBox(), and paintEvent().
m_led
PixmapButton* lmms::gui::GroupBox::m_led private
Definition at line 82 of file GroupBox.h.
Referenced by GroupBox(), ~GroupBox(), ledButton(), ledButtonShown(), modelChanged(), and setLedButtonShown().
m_titleBarHeight
const int lmms::gui::GroupBox::m_titleBarHeight private
Definition at line 84 of file GroupBox.h.
Referenced by GroupBox(), paintEvent(), and titleBarHeight().
The documentation for this class was generated from the following files:
include/GroupBox.h
src/gui/widgets/GroupBox.cpp