LMMS: lmms::Track Class Reference
lmms::Track Class Reference abstract
Base-class for all tracks.
#include <Track.h>
Public Types
using clipVector = std::vector<Clip*>
enum class Type {
Instrument ,
Pattern ,
Sample ,
Event ,
Video ,
Automation ,
HiddenAutomation ,
Count
}
Public Slots
void setMutedBeforeSolo (const bool muted)
virtual void setName (const QString &newName)
void toggleSolo ()
Invert the track's solo state.
Signals
void clipAdded (lmms::Clip *)
void colorChanged ()
void dataChanged ()
void destroyedTrack ()
void nameChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
Track (Type type, TrackContainer *tc)
Create a new (empty) track object.
~Track () override
Destroy this track.
Clip * addClip (Clip *clip)
Add another Clip into this track.
Track * clone ()
Clone a track from this track.
auto color () const -> const std::optional< QColor > &
virtual Clip * createClip (const TimePos &pos)=0
void createClipsForPattern (int pattern)
virtual gui::TrackView * createView (gui::TrackContainerView *view)=0
void deleteClips ()
Remove all Clips from this track.
QString displayName () const override
auto getClip (std::size_t clipNum) -> Clip *
Get a Clip by number.
int getClipNum (const Clip *clip)
Determine the given Clip's number in our array.
const clipVector & getClips () const
void getClipsInRange (clipVector &clipV, const TimePos &start, const TimePos &end)
Retrieve a list of clips that fall within a period.
int getHeight ()
BoolModel * getMutedModel ()
void insertBar (const TimePos &pos)
Move all the clips after a certain time later by one bar.
bool isMutedBeforeSolo () const
bar_t length () const
Return the length of the entire track in bars.
void loadPreset (const QDomElement &element)
void loadSettings (const QDomElement &element) override
virtual void loadTrackSpecificSettings (const QDomElement &element)=0
void lock ()
virtual const QString & name () const
int numOfClips ()
Return the number of clips we contain.
virtual bool play (const TimePos &start, const fpp_t frames, const f_cnt_t frameBase, int clipNum=-1)=0
void removeBar (const TimePos &pos)
Move all the clips after a certain time earlier by one bar.
void removeClip (Clip *clip)
Remove a given Clip from this track.
void savePreset (QDomDocument &doc, QDomElement &element)
void saveSettings (QDomDocument &doc, QDomElement &element) override
virtual void saveTrackSpecificSettings (QDomDocument &doc, QDomElement &parent, bool presetMode)=0
void setColor (const std::optional< QColor > &color)
void setHeight (int height)
void swapPositionOfClips (int clipNum1, int clipNum2)
Swap the position of two clips.
TrackContainer * trackContainer () const
bool tryLock ()
Type type () const
void unlock ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static Track * create (const QDomElement &element, TrackContainer *tc)
Create a track inside TrackContainer from track type in a QDomElement and restore state from XML.
static Track * create (Type tt, TrackContainer *tc)
Create a track based on the given track type and container.
Protected Attributes
BoolModel m_mutedModel
BoolModel m_soloModel
Private Member Functions
void loadTrack (const QDomElement &element, bool presetMode)
Load the settings from a file.
mapPropertyFromModel (bool, isMuted, setMuted, m_mutedModel)
mapPropertyFromModel (bool, isSolo, setSolo, m_soloModel)
void saveTrack (QDomDocument &doc, QDomElement &element, bool presetMode)
Save this track's settings to file.
Private Attributes
clipVector m_clips
std::optional< QColor > m_color
int m_height
bool m_mutedBeforeSolo
QString m_name
QMutex m_processingLock
TrackContainer * m_trackContainer
Type m_type
Friends
class gui::TrackView
Additional Inherited Members
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Base-class for all tracks.
Definition at line 67 of file Track.h.
Member Typedef Documentation
clipVector
using lmms::Track::clipVector = std::vector<Clip*>
Definition at line 73 of file Track.h.
Member Enumeration Documentation
Type
enum class lmms::Track::Type strong
Enumerator
Instrument
Pattern
Sample
Event
Video
Automation
HiddenAutomation
Count
Definition at line 75 of file Track.h.
Constructor & Destructor Documentation
Track()
lmms::Track::Track (Type type, TrackContainer * tc)
Create a new (empty) track object.
The track object is the whole track, linking its contents, its automation, name, type, and so forth.
Parameters
type The type of track (Song Editor or Pattern Editor)
tc The track Container object to encapsulate in this track.
Todo
check the definitions of all the properties - are they OK?
< The track Model
< The track container object
< The track type
< The track's name
< For controlling track muting
< For controlling track soloing
< The clips (segments)
Definition at line 59 of file Track.cpp.
References lmms::Model::Model(), m_clips, m_height, m_mutedModel, m_name, m_soloModel, m_trackContainer, m_type, and type().
Referenced by lmms::AutomationTrack::AutomationTrack(), lmms::InstrumentTrack::InstrumentTrack(), lmms::PatternTrack::PatternTrack(), lmms::SampleTrack::SampleTrack(), lmms::PatternTrack::automationDisabled(), clone(), create(), create(), lmms::PatternTrack::disableAutomation(), lmms::PatternTrack::enableAutomation(), and lmms::PatternTrack::swapPatternTracks().
~Track()
lmms::Track::~Track () override
Destroy this track.
Delete the clips and remove this track from the track container.
Definition at line 79 of file Track.cpp.
References destroyedTrack(), lock(), m_clips, m_trackContainer, and unlock().
Member Function Documentation
addClip()
Clip * lmms::Track::addClip (Clip * clip)
Add another Clip into this track.
Parameters
clip The Clip to attach to this track.
Definition at line 341 of file Track.cpp.
References clipAdded(), and m_clips.
Referenced by lmms::Clip::Clip(), lmms::Clip::Clip(), and loadTrackSpecificSettings().
clipAdded
void lmms::Track::clipAdded (lmms::Clip *) signal
Referenced by addClip().
clone()
Track * lmms::Track::clone ()
Clone a track from this track.
Definition at line 163 of file Track.cpp.
References Track(), create(), m_trackContainer, lmms::AutomationClip::resolveAllIDs(), and lmms::JournallingObject::saveState().
Referenced by lmms::gui::PatternEditor::cloneClip().
color()
auto lmms::Track::color () const->conststd::optional< QColor > & inline
Definition at line 190 of file Track.h.
References m_color.
Referenced by setColor().
colorChanged
void lmms::Track::colorChanged () signal
Referenced by lmms::gui::ClipView::ClipView(), and setColor().
create() [1/2]
Track * lmms::Track::create (const QDomElement & element, TrackContainer * tc) static
Create a track inside TrackContainer from track type in a QDomElement and restore state from XML.
Parameters
element The QDomElement containing the type of track to create
tc The track container to attach to
Definition at line 140 of file Track.cpp.
References Track(), lmms::Engine::audioEngine(), create(), lmms::AudioEngine::doneChangeInModel(), lmms::AudioEngine::requestChangeInModel(), and lmms::JournallingObject::restoreState().
create() [2/2]
Track * lmms::Track::create (Type tt, TrackContainer * tc) static
Create a track based on the given track type and container.
Parameters
tt The type of track to create
tc The track container to attach to
Definition at line 101 of file Track.cpp.
References Track(), lmms::Engine::audioEngine(), Automation, createClipsForPattern(), lmms::AudioEngine::doneChangeInModel(), HiddenAutomation, Instrument, Pattern, lmms::Engine::patternStore(), lmms::AudioEngine::requestChangeInModel(), Sample, and lmms::TrackContainer::updateAfterTrackAdd().
Referenced by lmms::PreviewTrackContainer::PreviewTrackContainer(), lmms::gui::FileBrowserTreeWidget::activateListItem(), lmms::gui::PatternEditor::addAutomationTrack(), lmms::Song::addAutomationTrack(), lmms::Song::addPatternTrack(), lmms::gui::PatternEditor::addSampleTrack(), lmms::Song::addSampleTrack(), clone(), create(), lmms::Song::createNewProject(), lmms::gui::PatternEditor::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), lmms::TrackContainer::loadSettings(), lmms::gui::FileBrowserTreeWidget::openInNewInstrumentTrack(), lmms::gui::PluginDescWidget::openInNewInstrumentTrack(), lmms::gui::FileBrowserTreeWidget::openInNewSampleTrack(), and lmms::gui::FileBrowserTreeWidget::openInSlicerT().
createClip()
virtual Clip * lmms::Track::createClip (const TimePos & pos) pure virtual
Implemented in lmms::AutomationTrack, lmms::InstrumentTrack, lmms::PatternTrack, and lmms::SampleTrack.
References pos.
Referenced by createClipsForPattern(), lmms::gui::AutomationTrackView::dropEvent(), lmms::gui::SampleTrackView::dropEvent(), getClip(), loadTrack(), and lmms::gui::TrackContentWidget::mousePressEvent().
createClipsForPattern()
void lmms::Track::createClipsForPattern (int pattern)
Definition at line 497 of file Track.cpp.
References lmms::Clip::changeLength(), createClip(), numOfClips(), and lmms::position().
Referenced by create(), and lmms::gui::PatternEditor::dropEvent().
createView()
virtual gui::TrackView * lmms::Track::createView (gui::TrackContainerView * view) pure virtual
Implemented in lmms::AutomationTrack, lmms::InstrumentTrack, lmms::PatternTrack, and lmms::SampleTrack.
Referenced by lmms::gui::TrackContainerView::createTrackView().
dataChanged
void lmms::Model::dataChanged () signal
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::SampleTrack::SampleTrack(), and lmms::PatternStore::updatePatternTrack().
deleteClips()
void lmms::Track::deleteClips ()
Remove all Clips from this track.
Definition at line 373 of file Track.cpp.
References m_clips.
Referenced by lmms::gui::TrackOperationsWidget::clearTrack(), lmms::gui::PatternEditor::cloneClip(), lmms::gui::PatternEditor::dropEvent(), loadTrack(), and loadTrackSpecificSettings().
destroyedTrack
void lmms::Track::destroyedTrack () signal
Referenced by ~Track().
displayName()
QString lmms::Track::displayName () const inline override virtual
Reimplemented from lmms::Model.
Definition at line 159 of file Track.h.
References name().
Referenced by lmms::Instrument::fullDisplayName().
getClip()
auto lmms::Track::getClip (std::size_t clipNum) ->Clip *
Get a Clip by number.
If the Clip number is less than our Clip array size then fetch that numbered object from the array. Otherwise we warn the user that we've somehow requested a Clip that is too large, and create a new Clip for them.
Parameters
clipNum The number of the Clip to fetch.
Returns
the given Clip or a new one if out of range.
Todo
reject Clip numbers less than zero.
if we create a Clip here, should we somehow attach it to the track?
Definition at line 406 of file Track.cpp.
References createClip(), m_clips, and lmms::TimePos::ticksPerBar().
Referenced by loadTrackSpecificSettings(), lmms::InstrumentTrack::play(), lmms::SampleTrack::play(), and lmms::SampleTrack::setPlayingClips().
getClipNum()
int lmms::Track::getClipNum (const Clip * clip)
Determine the given Clip's number in our array.
Parameters
clip The Clip to search for.
Returns
its number in our array.
Definition at line 426 of file Track.cpp.
References m_clips.
Referenced by loadTrackSpecificSettings().
getClips()
const clipVector & lmms::Track::getClips () const inline
Definition at line 131 of file Track.h.
References m_clips.
Referenced by lmms::gui::PatternEditor::dropEvent(), lmms::AutomationClip::globalAutomationClip(), and lmms::gui::TrackOperationsWidget::toggleRecording().
getClipsInRange()
void lmms::Track::getClipsInRange (clipVector & clipV, const TimePos & start, const TimePos & end)
Retrieve a list of clips that fall within a period.
Here we're interested in a range of clips that intersect the given time period.
We return the Clips we find in order by time, earliest Clips first.
Parameters
clipV The list to contain the found clips.
start The MIDI start time of the range.
end The MIDI endi time of the range.
Definition at line 456 of file Track.cpp.
References lmms::Clip::comparePosition(), and m_clips.
Referenced by lmms::InstrumentTrack::play(), and lmms::PatternTrack::play().
getHeight()
int lmms::Track::getHeight () inline
Definition at line 166 of file Track.h.
References lmms::DEFAULT_TRACK_HEIGHT, m_height, and lmms::MINIMAL_TRACK_HEIGHT.
getMutedModel()
BoolModel * lmms::Track::getMutedModel ()
Definition at line 650 of file Track.cpp.
References m_mutedModel.
insertBar()
void lmms::Track::insertBar (const TimePos & pos)
Move all the clips after a certain time later by one bar.
Parameters
pos The time at which we want to insert the bar.
Todo
if we stepped through this list last to first, and the list was in ascending order by Clip time, once we hit a Clip that was earlier than the insert time, we could fall out of the loop early.
Definition at line 517 of file Track.cpp.
References m_clips, pos, and lmms::TimePos::ticksPerBar().
isMutedBeforeSolo()
bool lmms::Track::isMutedBeforeSolo () const inline
Definition at line 193 of file Track.h.
References m_mutedBeforeSolo.
Referenced by lmms::InstrumentTrack::replaceInstrument().
length()
bar_t lmms::Track::length () const
Return the length of the entire track in bars.
We step through our list of Clips and determine their end position, keeping track of the latest time found in ticks. Then we return that in bars by dividing by the number of ticks per bar.
Definition at line 559 of file Track.cpp.
References lmms::Engine::getSong(), m_clips, and lmms::TimePos::ticksPerBar().
Referenced by lmms::SampleTrack::play().
loadPreset()
void lmms::Track::loadPreset (const QDomElement & element)
Definition at line 317 of file Track.cpp.
References loadTrack().
Referenced by lmms::gui::TrackContainerView::dropEvent(), loadTrackSpecificSettings(), and lmms::InstrumentTrack::replaceInstrument().
loadSettings()
void lmms::Track::loadSettings (const QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 328 of file Track.cpp.
References loadTrack().
Referenced by loadTrackSpecificSettings().
loadTrack()
void lmms::Track::loadTrack (const QDomElement & element, bool presetMode) private
Load the settings from a file.
We load the track's type and muted state and solo state, then clear out our current Clip.
Then we step through the QDomElement's children and load the track-specific settings and clip states from it one at a time.
Parameters
element the QDomElement to load track settings from
presetMode Indicates if a preset or a full track is loaded
Todo
Load the track height.
Definition at line 241 of file Track.cpp.
References lmms::Engine::audioEngine(), createClip(), deleteClips(), loadTrackSpecificSettings(), m_height, m_mutedBeforeSolo, m_mutedModel, m_soloModel, lmms::MINIMAL_TRACK_HEIGHT, lmms::SerializingObject::nodeName(), lmms::AudioEngine::requestChangesGuard(), lmms::JournallingObject::restoreState(), setColor(), setName(), and type().
Referenced by loadPreset(), and loadSettings().
loadTrackSpecificSettings()
virtual void lmms::Track::loadTrackSpecificSettings (const QDomElement & element) pure virtual
Implemented in lmms::AutomationTrack, lmms::InstrumentTrack, lmms::PatternTrack, and lmms::SampleTrack.
References addClip(), deleteClips(), getClip(), getClipNum(), loadPreset(), loadSettings(), numOfClips(), removeClip(), savePreset(), and saveSettings().
Referenced by loadTrack().
lock()
void lmms::Track::lock () inline
Definition at line 177 of file Track.h.
References m_processingLock.
Referenced by ~Track(), lmms::MidiClip::addNote(), lmms::TrackContainer::addTrack(), lmms::MidiClip::clearNotes(), lmms::gui::TrackOperationsWidget::clearTrack(), lmms::gui::PatternEditor::cloneClip(), lmms::InstrumentTrack::loadInstrument(), lmms::InstrumentTrack::loadTrackSpecificSettings(), lmms::MidiClip::removeNote(), and lmms::MidiClip::removeNote().
mapPropertyFromModel() [1/2]
lmms::Track::mapPropertyFromModel (bool , isMuted , setMuted , m_mutedModel) private
References m_mutedModel.
mapPropertyFromModel() [2/2]
lmms::Track::mapPropertyFromModel (bool , isSolo , setSolo , m_soloModel) private
References m_soloModel.
name()
virtual const QString & lmms::Track::name () const inline virtual
Definition at line 154 of file Track.h.
References m_name.
Referenced by lmms::gui::ClipView::createClipDataFiles(), lmms::gui::InstrumentTrackView::createMixerLine(), lmms::gui::SampleTrackView::createMixerLine(), displayName(), lmms::RenderManager::pathForTrack(), saveTrack(), lmms::InstrumentTrack::setName(), and lmms::PatternStore::updateComboBox().
nameChanged
void lmms::Track::nameChanged () signal
Referenced by lmms::PatternTrack::PatternTrack(), and setName().
numOfClips()
int lmms::Track::numOfClips ()
Return the number of clips we contain.
Returns
the number of clips we currently contain.
Definition at line 386 of file Track.cpp.
References m_clips.
Referenced by createClipsForPattern(), loadTrackSpecificSettings(), lmms::SampleTrack::play(), and lmms::SampleTrack::setPlayingClips().
play()
virtual bool lmms::Track::play (const TimePos & start, const fpp_t frames, const f_cnt_t frameBase, int clipNum = -1) pure virtual
Implemented in lmms::AutomationTrack, lmms::InstrumentTrack, lmms::PatternTrack, and lmms::SampleTrack.
removeBar()
void lmms::Track::removeBar (const TimePos & pos)
Move all the clips after a certain time earlier by one bar.
Parameters
pos The time at which we want to remove the bar.
Definition at line 537 of file Track.cpp.
References m_clips, pos, and lmms::TimePos::ticksPerBar().
removeClip()
void lmms::Track::removeClip (Clip * clip)
Remove a given Clip from this track.
Parameters
clip The Clip to remove from this track.
Definition at line 357 of file Track.cpp.
References lmms::Engine::getSong(), m_clips, lmms::Song::setModified(), and lmms::Song::updateLength().
Referenced by lmms::Clip::~Clip(), and loadTrackSpecificSettings().
savePreset()
void lmms::Track::savePreset (QDomDocument & doc, QDomElement & element)
Definition at line 312 of file Track.cpp.
References saveTrack().
Referenced by loadTrackSpecificSettings().
saveSettings()
void lmms::Track::saveSettings (QDomDocument & doc, QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 322 of file Track.cpp.
References saveTrack().
Referenced by loadTrackSpecificSettings().
saveTrack()
void lmms::Track::saveTrack (QDomDocument & doc, QDomElement & element, bool presetMode) private
Save this track's settings to file.
We save the track type and its muted state and solo state, then append the track- specific settings. Then we iterate through the clips and save all their states in turn.
Parameters
doc The QDomDocument to use to save
element The The QDomElement to save into
presetMode Describes whether to save the track as a preset or not.
Todo
Does this accurately describe the parameters? I think not!?
Save the track height
Definition at line 188 of file Track.cpp.
References m_clips, m_color, m_height, m_mutedBeforeSolo, m_mutedModel, m_soloModel, lmms::MINIMAL_TRACK_HEIGHT, name(), lmms::SerializingObject::nodeName(), saveTrackSpecificSettings(), and type().
Referenced by savePreset(), and saveSettings().
saveTrackSpecificSettings()
virtual void lmms::Track::saveTrackSpecificSettings (QDomDocument & doc, QDomElement & parent, bool presetMode) pure virtual
Implemented in lmms::AutomationTrack, lmms::InstrumentTrack, lmms::PatternTrack, and lmms::SampleTrack.
Referenced by saveTrack().
setColor()
void lmms::Track::setColor (const std::optional< QColor > & color)
Definition at line 644 of file Track.cpp.
References color(), colorChanged(), and m_color.
Referenced by loadTrack().
setHeight()
void lmms::Track::setHeight (int height) inline
Definition at line 172 of file Track.h.
References m_height.
setMutedBeforeSolo
void lmms::Track::setMutedBeforeSolo (const bool muted) inline slot
Definition at line 203 of file Track.h.
References m_mutedBeforeSolo.
Referenced by lmms::InstrumentTrack::replaceInstrument().
setName
void lmms::Track::setName (const QString & newName) virtual slot
Reimplemented in lmms::InstrumentTrack.
Definition at line 655 of file Track.cpp.
References lmms::Engine::getSong(), m_name, and nameChanged().
Referenced by lmms::AutomationTrack::AutomationTrack(), lmms::PatternTrack::PatternTrack(), lmms::SampleTrack::SampleTrack(), loadTrack(), lmms::PatternTrack::loadTrackSpecificSettings(), and lmms::InstrumentTrack::setName().
swapPositionOfClips()
void lmms::Track::swapPositionOfClips (int clipNum1, int clipNum2)
Swap the position of two clips.
First, we arrange to swap the positions of the two Clips in the clips list. Then we swap their start times as well.
Parameters
clipNum1 The first Clip to swap.
clipNum2 The second Clip to swap.
Definition at line 484 of file Track.cpp.
References m_clips, and pos.
toggleSolo
void lmms::Track::toggleSolo () slot
Invert the track's solo state.
We have to go through all the tracks determining if any other track is already soloed. Then we have to save the mute state of all tracks, and set our mute state to on and all the others to off.
Definition at line 588 of file Track.cpp.
References Automation, lmms::ConfigManager::inst(), m_soloModel, m_trackContainer, and lmms::ConfigManager::value().
Referenced by lmms::gui::TrackOperationsWidget::cloneTrack().
trackContainer()
TrackContainer * lmms::Track::trackContainer () const inline
Definition at line 148 of file Track.h.
References m_trackContainer.
Referenced by lmms::MidiClip::MidiClip(), lmms::PatternTrack::~PatternTrack(), lmms::gui::TrackContentWidget::canPasteSelection(), lmms::gui::ClipView::createClipDataFiles(), lmms::Clip::hasTrackContainer(), lmms::Clip::isInPattern(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::InstrumentTrack::play(), and lmms::SampleTrack::play().
tryLock()
bool lmms::Track::tryLock () inline
Definition at line 185 of file Track.h.
References m_processingLock.
Referenced by lmms::InstrumentTrack::play().
type()
Type lmms::Track::type () const inline
Definition at line 97 of file Track.h.
References m_type.
Referenced by Track(), lmms::TrackContainer::addTrack(), lmms::gui::TrackContentWidget::canPasteSelection(), lmms::gui::ClipView::createClipDataFiles(), loadTrack(), lmms::AutomationTrack::loadTrackSpecificSettings(), and saveTrack().
unlock()
void lmms::Track::unlock () inline
Definition at line 181 of file Track.h.
References m_processingLock.
Referenced by ~Track(), lmms::MidiClip::addNote(), lmms::TrackContainer::addTrack(), lmms::MidiClip::clearNotes(), lmms::gui::TrackOperationsWidget::clearTrack(), lmms::gui::PatternEditor::cloneClip(), lmms::InstrumentTrack::loadInstrument(), lmms::InstrumentTrack::loadTrackSpecificSettings(), lmms::InstrumentTrack::play(), lmms::MidiClip::removeNote(), and lmms::MidiClip::removeNote().
Friends And Related Symbol Documentation
gui::TrackView
friend class gui::TrackView friend
Definition at line 233 of file Track.h.
Member Data Documentation
m_clips
clipVector lmms::Track::m_clips private
Definition at line 227 of file Track.h.
Referenced by Track(), ~Track(), addClip(), deleteClips(), getClip(), getClipNum(), getClips(), getClipsInRange(), insertBar(), length(), numOfClips(), removeBar(), removeClip(), saveTrack(), and swapPositionOfClips().
m_color
std::optional<QColor> lmms::Track::m_color private
Definition at line 231 of file Track.h.
Referenced by color(), saveTrack(), and setColor().
m_height
int lmms::Track::m_height private
Definition at line 218 of file Track.h.
Referenced by Track(), getHeight(), loadTrack(), saveTrack(), and setHeight().
m_mutedBeforeSolo
bool lmms::Track::m_mutedBeforeSolo private
Definition at line 225 of file Track.h.
Referenced by isMutedBeforeSolo(), loadTrack(), saveTrack(), and setMutedBeforeSolo().
m_mutedModel
BoolModel lmms::Track::m_mutedModel protected
Definition at line 221 of file Track.h.
Referenced by lmms::InstrumentTrack::InstrumentTrack(), lmms::SampleTrack::SampleTrack(), Track(), getMutedModel(), loadTrack(), mapPropertyFromModel(), and saveTrack().
m_name
QString lmms::Track::m_name private
Definition at line 217 of file Track.h.
Referenced by Track(), name(), and setName().
m_processingLock
QMutex lmms::Track::m_processingLock private
Definition at line 229 of file Track.h.
Referenced by lock(), tryLock(), and unlock().
m_soloModel
BoolModel lmms::Track::m_soloModel protected
Definition at line 222 of file Track.h.
Referenced by Track(), loadTrack(), mapPropertyFromModel(), saveTrack(), and toggleSolo().
m_trackContainer
TrackContainer* lmms::Track::m_trackContainer private
Definition at line 215 of file Track.h.
Referenced by Track(), ~Track(), clone(), toggleSolo(), and trackContainer().
m_type
Type lmms::Track::m_type private
Definition at line 216 of file Track.h.
Referenced by Track(), and type().
The documentation for this class was generated from the following files:
include/Track.h
src/core/Track.cpp