LMMS: lmms::gui::AutomationEditor Class Reference
lmms::gui::AutomationEditor Class Reference
#include <AutomationEditor.h>
Public Types
enum class EditMode {
Draw ,
Erase ,
DrawOutValues ,
EditTangents
}
Public Slots
void update ()
void updateAfterClipChange ()
Signals
void currentClipChanged ()
void positionChanged (const lmms::TimePos &)
Public Member Functions
const AutomationClip * currentClip () const
void loadSettings (const QDomElement &parent) override
QString nodeName () const override
void saveSettings (QDomDocument &doc, QDomElement &parent) override
void setCurrentClip (AutomationClip *new_clip)
void setGhostMidiClip (MidiClip *newMidiClip)
void setGhostSample (SampleClip *newSample)
bool validClip () const
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Types
using timeMap = AutomationClip::timeMap
Protected Slots
void horScrolled (int new_pos)
void play ()
void resetGhostNotes ()
void setEditMode (AutomationEditor::EditMode mode)
void setEditMode (int mode)
void setProgressionType (AutomationClip::ProgressionType type)
void setProgressionType (int type)
This method handles the AutomationEditorWindow event of changing progression types.
void setQuantization ()
Updates the clip's quantization using the current user selected value.
void setTension ()
void stop ()
void updatePosition (const lmms::TimePos &t)
void verScrolled (int new_pos)
void zoomingXChanged ()
void zoomingYChanged ()
Protected Member Functions
void drawLevelTick (QPainter &p, int tick, float value)
void drawLine (int x0, float y0, int x1, float y1)
bool fineTuneValue (timeMap::iterator node, bool editingOutValue)
timeMap::iterator getClosestNode (int x)
Given a mouse X coordinate, returns a timeMap::iterator that points to the closest node.
float getLevel (int y)
timeMap::iterator getNodeAt (int x, int y, bool outValue=false, int r=5)
Given a mouse coordinate, returns a timeMap::iterator that points to the first node inside a square of side "r" pixels from those coordinates.
void keyPressEvent (QKeyEvent *ke) override
void leaveEvent (QEvent *e) override
void mouseDoubleClickEvent (QMouseEvent *mouseEvent) override
void mouseMoveEvent (QMouseEvent *mouseEvent) override
void mousePressEvent (QMouseEvent *mouseEvent) override
void mouseReleaseEvent (QMouseEvent *mouseEvent) override
void paintEvent (QPaintEvent *pe) override
void resizeEvent (QResizeEvent *re) override
void wheelEvent (QWheelEvent *we) override
int xCoordOfTick (int tick)
float yCoordOfLevel (float level)
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Properties
QColor backgroundShade
QColor barLineColor
QColor beatLineColor
QColor crossColor
QColor detuningNoteColor
QColor ghostNoteColor
QColor ghostSampleColor
QBrush graphColor
QColor lineColor
QColor nodeInValueColor
QColor nodeOutValueColor
QColor nodeTangentLineColor
QColor outOfBoundsShade
QBrush scaleColor
Private Types
enum class Action {
None ,
MoveValue ,
EraseValues ,
MoveOutValue ,
ResetOutValues ,
DrawLine ,
MoveTangent ,
ResetTangents
}
Private Member Functions
AutomationEditor ()
AutomationEditor (const AutomationEditor &)
~AutomationEditor () override
void adjustLeftRightScoll (int value)
void centerTopBottomScroll ()
void drawAutomationPoint (QPainter &p, timeMap::iterator it)
void drawAutomationTangents (QPainter &p, timeMap::iterator it)
void drawCross (QPainter &p)
bool inPatternEditor ()
void updateTopBottomLevels ()
Private Attributes
Action m_action
QColor m_backgroundShade
QColor m_barLineColor
QColor m_beatLineColor
float m_bottomLevel
AutomationClip * m_clip
QColor m_crossColor
TimePos m_currentPosition
QColor m_detuningNoteColor
bool m_draggedOutTangent
int m_draggedOutValueKey
int m_draggedTangentTick
float m_drawLastLevel
tick_t m_drawLastTick
EditMode m_editMode
QColor m_ghostNoteColor
MidiClip * m_ghostNotes = nullptr
QPointer< SampleClip > m_ghostSample = nullptr
QColor m_ghostSampleColor
QBrush m_graphColor
QScrollBar * m_leftRightScroll
QColor m_lineColor
float m_maxLevel
float m_minLevel
bool m_mouseDownLeft
bool m_mouseDownRight
int m_moveXOffset
QColor m_nodeInValueColor
QColor m_nodeOutValueColor
QColor m_nodeTangentLineColor
QColor m_outOfBoundsShade
int m_ppb
ComboBoxModel m_quantizeModel
bool m_renderSample = false
SampleThumbnail m_sampleThumbnail
QBrush m_scaleColor
bool m_scrollBack
float m_scrollLevel
float m_step
FloatModel * m_tensionModel
TimeLineWidget * m_timeLine
QPixmap m_toolDraw = embed::getIconPixmap("edit_draw")
QPixmap m_toolDrawOut = embed::getIconPixmap("edit_draw_outvalue")
QPixmap m_toolEditTangents = embed::getIconPixmap("edit_tangent")
QPixmap m_toolErase = embed::getIconPixmap("edit_erase")
QPixmap m_toolMove = embed::getIconPixmap("edit_move")
QPixmap m_toolXFlip = embed::getIconPixmap("flip_x")
QPixmap m_toolYFlip = embed::getIconPixmap("flip_y")
QScrollBar * m_topBottomScroll
float m_topLevel
bool m_y_auto
int m_y_delta
ComboBoxModel m_zoomingXModel
ComboBoxModel m_zoomingYModel
Static Private Attributes
static const int DEFAULT_PPB = 12 * DEFAULT_STEPS_PER_BAR
static const int DEFAULT_STEPS_PER_BAR = 16
static const int DEFAULT_Y_DELTA = 6
static const std::array< float, 7 > m_zoomXLevels
static constexpr int MAX_SAMPLE_HEIGHT = 400
static const int MIN_NOTE_RANGE = 20
static const int NOTE_HEIGHT = 10
static const int NOTE_MARGIN = 40
static const int SAMPLE_MARGIN = 40
static const int SCROLLBAR_SIZE = 12
static const int TOP_MARGIN = 16
static const int VALUES_WIDTH = 64
Friends
class AutomationEditorWindow
Detailed Description
Definition at line 58 of file AutomationEditor.h.
Member Typedef Documentation
timeMap
using lmms::gui::AutomationEditor::timeMap = AutomationClip::timeMap protected
Definition at line 111 of file AutomationEditor.h.
Member Enumeration Documentation
Action
enum class lmms::gui::AutomationEditor::Action strong private
Enumerator
None
MoveValue
EraseValues
MoveOutValue
ResetOutValues
DrawLine
MoveTangent
ResetTangents
Definition at line 177 of file AutomationEditor.h.
EditMode
enum class lmms::gui::AutomationEditor::EditMode strong
Enumerator
Draw
Erase
DrawOutValues
EditTangents
Definition at line 97 of file AutomationEditor.h.
Constructor & Destructor Documentation
AutomationEditor() [1/2]
lmms::gui::AutomationEditor::AutomationEditor () private
Definition at line 72 of file AutomationEditor.cpp.
References lmms::Song::AutomationClip, currentClipChanged(), DEFAULT_PPB, DEFAULT_Y_DELTA, lmms::Engine::getSong(), horScrolled(), m_action, m_backgroundShade, m_barLineColor, m_beatLineColor, m_bottomLevel, m_clip, m_crossColor, m_currentPosition, m_drawLastLevel, m_drawLastTick, m_editMode, m_ghostNoteColor, m_graphColor, m_leftRightScroll, m_lineColor, m_maxLevel, m_minLevel, m_mouseDownLeft, m_mouseDownRight, m_nodeInValueColor, m_nodeOutValueColor, m_nodeTangentLineColor, m_outOfBoundsShade, m_ppb, m_quantizeModel, m_scaleColor, m_scrollBack, m_scrollLevel, m_step, m_tensionModel, m_timeLine, m_topBottomScroll, m_topLevel, m_y_auto, m_y_delta, m_zoomingXModel, m_zoomingYModel, None, positionChanged(), lmms::gui::Quantizations, setCurrentClip(), setQuantization(), setTension(), update(), updateAfterClipChange(), updatePosition(), lmms::gui::TimeLineWidget::updatePosition(), VALUES_WIDTH, and verScrolled().
Referenced by AutomationEditor().
AutomationEditor() [2/2]
lmms::gui::AutomationEditor::AutomationEditor (const AutomationEditor &) private
References AutomationEditor().
~AutomationEditor()
lmms::gui::AutomationEditor::~AutomationEditor () override private
Definition at line 164 of file AutomationEditor.cpp.
References m_quantizeModel, m_tensionModel, m_zoomingXModel, and m_zoomingYModel.
Member Function Documentation
adjustLeftRightScoll()
void lmms::gui::AutomationEditor::adjustLeftRightScoll (int value) private
Definition at line 1586 of file AutomationEditor.cpp.
References m_leftRightScroll, m_zoomingXModel, and m_zoomXLevels.
Referenced by wheelEvent().
centerTopBottomScroll()
void lmms::gui::AutomationEditor::centerTopBottomScroll () private
Definition at line 1529 of file AutomationEditor.cpp.
References lmms::INVAL(), m_clip, m_scrollLevel, m_topBottomScroll, and pos.
Referenced by resizeEvent(), and updateAfterClipChange().
currentClip()
const AutomationClip * lmms::gui::AutomationEditor::currentClip () const inline
Definition at line 80 of file AutomationEditor.h.
References currentClip(), inline, and m_clip.
Referenced by currentClip().
currentClipChanged
void lmms::gui::AutomationEditor::currentClipChanged () signal
Referenced by AutomationEditor(), and setCurrentClip().
drawAutomationPoint()
void lmms::gui::AutomationEditor::drawAutomationPoint (QPainter & p, timeMap::iterator it) inline private
Definition at line 956 of file AutomationEditor.cpp.
References lmms::INVAL(), m_nodeInValueColor, m_nodeOutValueColor, m_ppb, lmms::OUTVAL(), lmms::POS(), lmms::AutomationClip::quantization(), xCoordOfTick(), and yCoordOfLevel().
Referenced by paintEvent().
drawAutomationTangents()
void lmms::gui::AutomationEditor::drawAutomationTangents (QPainter & p, timeMap::iterator it) inline private
Definition at line 982 of file AutomationEditor.cpp.
References lmms::INTAN(), lmms::INVAL(), m_bottomLevel, m_nodeTangentLineColor, m_ppb, m_topLevel, lmms::OUTTAN(), lmms::OUTVAL(), lmms::POS(), SCROLLBAR_SIZE, lmms::TimePos::ticksPerBar(), TOP_MARGIN, xCoordOfTick(), and yCoordOfLevel().
Referenced by paintEvent().
drawCross()
void lmms::gui::AutomationEditor::drawCross (QPainter & p) inline private
Definition at line 921 of file AutomationEditor.cpp.
References getLevel(), m_bottomLevel, m_clip, m_crossColor, m_maxLevel, m_minLevel, m_y_auto, m_y_delta, SCROLLBAR_SIZE, TOP_MARGIN, and VALUES_WIDTH.
Referenced by paintEvent().
drawLevelTick()
void lmms::gui::AutomationEditor::drawLevelTick (QPainter & p, int tick, float value) inline protected
Definition at line 1499 of file AutomationEditor.cpp.
References m_bottomLevel, m_graphColor, m_maxLevel, m_minLevel, m_topLevel, m_y_auto, m_y_delta, SCROLLBAR_SIZE, TOP_MARGIN, xCoordOfTick(), and yCoordOfLevel().
Referenced by paintEvent().
drawLine()
void lmms::gui::AutomationEditor::drawLine (int x0, float y0, int x1, float y1) protected
Definition at line 314 of file AutomationEditor.cpp.
References i, m_clip, lmms::AutomationClip::quantization(), and lmms::Note::quantized().
Referenced by mousePressEvent().
fineTuneValue()
bool lmms::gui::AutomationEditor::fineTuneValue (timeMap::iterator node, bool editingOutValue) protected
Definition at line 348 of file AutomationEditor.cpp.
References lmms::Engine::getSong(), lmms::INVAL(), m_clip, lmms::OFFSET(), lmms::OUTVAL(), and lmms::Song::setModified().
Referenced by mouseDoubleClickEvent().
getClosestNode()
AutomationEditor::timeMap::iterator lmms::gui::AutomationEditor::getClosestNode (int x) protected
Given a mouse X coordinate, returns a timeMap::iterator that points to the closest node.
Parameters
Int X coordinate
Returns
timeMap::iterator with the closest node or timeMap.end() if there are no nodes.
Definition at line 1999 of file AutomationEditor.cpp.
References m_clip, m_currentPosition, m_ppb, lmms::POS(), lmms::TimePos::ticksPerBar(), and VALUES_WIDTH.
Referenced by mousePressEvent().
getLevel()
float lmms::gui::AutomationEditor::getLevel (int y) protected
Definition at line 1671 of file AutomationEditor.cpp.
References m_bottomLevel, m_maxLevel, m_minLevel, m_step, m_topLevel, m_y_auto, m_y_delta, SCROLLBAR_SIZE, and TOP_MARGIN.
Referenced by drawCross(), mouseMoveEvent(), and mousePressEvent().
getNodeAt()
AutomationEditor::timeMap::iterator lmms::gui::AutomationEditor::getNodeAt (int x, int y, bool outValue = false, int r = 5) protected
Given a mouse coordinate, returns a timeMap::iterator that points to the first node inside a square of side "r" pixels from those coordinates.
In simpler terms, returns the automation node on those coordinates.
Parameters
Int X coordinate
Int Y coordinate
Boolean. True to check if the outValue of the node was clicked instead (defaults to false)
Int R distance in pixels
Returns
timeMap::iterator with the clicked node, or timeMap.end() if none was clicked.
Definition at line 1958 of file AutomationEditor.cpp.
References lmms::INVAL(), m_clip, m_currentPosition, m_ppb, lmms::OUTVAL(), lmms::POS(), lmms::TimePos::ticksPerBar(), VALUES_WIDTH, and yCoordOfLevel().
Referenced by mouseDoubleClickEvent(), and mousePressEvent().
horScrolled
void lmms::gui::AutomationEditor::horScrolled (int new_pos) protected slot
Definition at line 1759 of file AutomationEditor.cpp.
References m_currentPosition, positionChanged(), and update().
Referenced by AutomationEditor().
inPatternEditor()
bool lmms::gui::AutomationEditor::inPatternEditor () inline private
Definition at line 1688 of file AutomationEditor.cpp.
References m_clip, lmms::Engine::patternStore(), and validClip().
Referenced by play(), and stop().
keyPressEvent()
void lmms::gui::AutomationEditor::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 257 of file AutomationEditor.cpp.
References m_timeLine, and m_topBottomScroll.
leaveEvent()
void lmms::gui::AutomationEditor::leaveEvent (QEvent * e) override protected
Definition at line 303 of file AutomationEditor.cpp.
References update().
loadSettings()
void lmms::gui::AutomationEditor::loadSettings (const QDomElement & parent) override virtual
Implements lmms::SerializingObject.
Definition at line 206 of file AutomationEditor.cpp.
References lmms::gui::MainWindow::restoreWidgetState().
mouseDoubleClickEvent()
void lmms::gui::AutomationEditor::mouseDoubleClickEvent (QMouseEvent * mouseEvent) override protected
Definition at line 664 of file AutomationEditor.cpp.
References Draw, DrawOutValues, fineTuneValue(), getNodeAt(), m_editMode, TOP_MARGIN, update(), validClip(), and VALUES_WIDTH.
mouseMoveEvent()
void lmms::gui::AutomationEditor::mouseMoveEvent (QMouseEvent * mouseEvent) override protected
Definition at line 723 of file AutomationEditor.cpp.
References Draw, DrawOutValues, EditTangents, Erase, EraseValues, getLevel(), lmms::Engine::getSong(), lmms::INVAL(), m_action, m_clip, m_currentPosition, m_draggedOutTangent, m_draggedOutValueKey, m_draggedTangentTick, m_drawLastLevel, m_drawLastTick, m_editMode, m_mouseDownLeft, m_mouseDownRight, m_moveXOffset, m_ppb, MoveOutValue, MoveTangent, MoveValue, lmms::OUTVAL(), lmms::POS(), ResetOutValues, ResetTangents, lmms::Song::setModified(), lmms::TimePos::ticksPerBar(), TOP_MARGIN, update(), validClip(), VALUES_WIDTH, and yCoordOfLevel().
mousePressEvent()
void lmms::gui::AutomationEditor::mousePressEvent (QMouseEvent * mouseEvent) override protected
Definition at line 395 of file AutomationEditor.cpp.
References Draw, DrawLine, drawLine(), DrawOutValues, EditTangents, Erase, EraseValues, getClosestNode(), getLevel(), getNodeAt(), lmms::Engine::getSong(), m_action, m_clip, m_currentPosition, m_draggedOutTangent, m_draggedOutValueKey, m_draggedTangentTick, m_drawLastLevel, m_drawLastTick, m_editMode, m_mouseDownLeft, m_mouseDownRight, m_moveXOffset, m_ppb, MoveOutValue, MoveTangent, MoveValue, lmms::POS(), lmms::Note::quantized(), ResetOutValues, ResetTangents, lmms::Song::setModified(), lmms::TimePos::ticksPerBar(), TOP_MARGIN, update(), validClip(), and VALUES_WIDTH.
mouseReleaseEvent()
void lmms::gui::AutomationEditor::mouseReleaseEvent (QMouseEvent * mouseEvent) override protected
Definition at line 689 of file AutomationEditor.cpp.
References Draw, m_action, m_clip, m_editMode, m_mouseDownLeft, m_mouseDownRight, MoveValue, and None.
nodeName()
QString lmms::gui::AutomationEditor::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 92 of file AutomationEditor.h.
paintEvent()
void lmms::gui::AutomationEditor::paintEvent (QPaintEvent * pe) override protected
Todo
move this horizontal line drawing code into the same loop as the value ticks?
Definition at line 1030 of file AutomationEditor.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, DEFAULT_Y_DELTA, lmms::DefaultTicksPerBar, lmms::AutomationClip::Discrete, Draw, drawAutomationPoint(), drawAutomationTangents(), drawCross(), drawLevelTick(), DrawOutValues, EditTangents, Erase, EraseValues, lmms::Engine::framesPerTick(), lmms::Engine::getSong(), lmms::Song::getTimeSigModel(), i, lmms::gui::GuiApplication::instance(), lmms::INVAL(), lmms::LOCKEDTAN(), m_action, m_backgroundShade, m_barLineColor, m_beatLineColor, m_bottomLevel, m_clip, m_currentPosition, m_detuningNoteColor, m_editMode, m_ghostNoteColor, m_ghostNotes, m_ghostSample, m_ghostSampleColor, m_graphColor, m_leftRightScroll, m_lineColor, m_maxLevel, m_minLevel, m_outOfBoundsShade, m_ppb, m_renderSample, m_sampleThumbnail, m_scaleColor, m_toolDraw, m_toolDrawOut, m_toolEditTangents, m_toolErase, m_toolMove, m_topLevel, m_y_auto, m_y_delta, m_zoomingXModel, m_zoomXLevels, MAX_SAMPLE_HEIGHT, MIN_NOTE_RANGE, MoveOutValue, MoveTangent, MoveValue, NOTE_HEIGHT, NOTE_MARGIN, lmms::OUTVAL(), lmms::POS(), lmms::AutomationClip::quantization(), ResetOutValues, SAMPLE_MARGIN, SCROLLBAR_SIZE, lmms::TimePos::ticksPerBar(), TOP_MARGIN, validClip(), VALUES_WIDTH, xCoordOfTick(), and yCoordOfLevel().
play
void lmms::gui::AutomationEditor::play () protected slot
Definition at line 1696 of file AutomationEditor.cpp.
References lmms::gui::getGUI(), lmms::Engine::getSong(), inPatternEditor(), m_clip, lmms::Song::MidiClip, lmms::Engine::patternStore(), lmms::PatternStore::play(), lmms::Song::playMidiClip(), lmms::Song::playSong(), lmms::Song::stop(), lmms::Song::togglePause(), and validClip().
positionChanged
void lmms::gui::AutomationEditor::positionChanged (const lmms::TimePos &) signal
Referenced by AutomationEditor(), and horScrolled().
resetGhostNotes
void lmms::gui::AutomationEditor::resetGhostNotes () inline protected slot
Definition at line 168 of file AutomationEditor.h.
References m_ghostNotes, m_ghostSample, and update().
Referenced by lmms::gui::AutomationEditorWindow::AutomationEditorWindow().
resizeEvent()
void lmms::gui::AutomationEditor::resizeEvent (QResizeEvent * re) override protected
Definition at line 1553 of file AutomationEditor.cpp.
References centerTopBottomScroll(), m_leftRightScroll, m_maxLevel, m_minLevel, m_scrollLevel, m_timeLine, m_topBottomScroll, m_y_auto, m_y_delta, SCROLLBAR_SIZE, TOP_MARGIN, update(), updateTopBottomLevels(), and VALUES_WIDTH.
Referenced by updateAfterClipChange(), and zoomingYChanged().
saveSettings()
void lmms::gui::AutomationEditor::saveSettings (QDomDocument & doc, QDomElement & parent) override virtual
Implements lmms::SerializingObject.
Definition at line 198 of file AutomationEditor.cpp.
References lmms::gui::MainWindow::saveWidgetState().
setCurrentClip()
void lmms::gui::AutomationEditor::setCurrentClip (AutomationClip * new_clip)
Definition at line 177 of file AutomationEditor.cpp.
References currentClipChanged(), lmms::Clip::lengthChanged(), m_clip, and update().
Referenced by AutomationEditor().
setEditMode [1/2]
void lmms::gui::AutomationEditor::setEditMode (AutomationEditor::EditMode mode) protected slot
Definition at line 1779 of file AutomationEditor.cpp.
References m_editMode, and update().
Referenced by setEditMode().
setEditMode [2/2]
void lmms::gui::AutomationEditor::setEditMode (int mode) protected slot
Definition at line 1792 of file AutomationEditor.cpp.
References setEditMode().
setGhostMidiClip()
void lmms::gui::AutomationEditor::setGhostMidiClip (MidiClip * newMidiClip)
Definition at line 1015 of file AutomationEditor.cpp.
References m_ghostNotes, and m_renderSample.
setGhostSample()
void lmms::gui::AutomationEditor::setGhostSample (SampleClip * newSample)
Definition at line 1022 of file AutomationEditor.cpp.
References m_ghostSample, m_renderSample, m_sampleThumbnail, and lmms::SampleClip::sample().
setProgressionType [1/2]
void lmms::gui::AutomationEditor::setProgressionType (AutomationClip::ProgressionType type) protected slot
Definition at line 1800 of file AutomationEditor.cpp.
References lmms::Engine::getSong(), m_clip, lmms::Song::setModified(), update(), and validClip().
Referenced by setProgressionType().
setProgressionType [2/2]
void lmms::gui::AutomationEditor::setProgressionType (int type) protected slot
This method handles the AutomationEditorWindow event of changing progression types.
After that, it calls updateEditTanButton so the edit tangents button is updated accordingly
Parameters
Int New progression type
Definition at line 1811 of file AutomationEditor.cpp.
References setProgressionType().
setQuantization
void lmms::gui::AutomationEditor::setQuantization () protected slot
Updates the clip's quantization using the current user selected value.
Definition at line 1889 of file AutomationEditor.cpp.
References lmms::DefaultTicksPerBar, m_quantizeModel, lmms::gui::Quantizations, lmms::AutomationClip::setQuantization(), and update().
Referenced by AutomationEditor().
setTension
void lmms::gui::AutomationEditor::setTension () protected slot
Definition at line 1819 of file AutomationEditor.cpp.
References m_clip, m_tensionModel, and update().
Referenced by AutomationEditor().
stop
void lmms::gui::AutomationEditor::stop () protected slot
Definition at line 1739 of file AutomationEditor.cpp.
References lmms::Engine::getSong(), inPatternEditor(), m_clip, m_scrollBack, lmms::Engine::patternStore(), lmms::PatternStore::stop(), lmms::Song::stop(), and validClip().
update
void lmms::gui::AutomationEditor::update () slot
Definition at line 243 of file AutomationEditor.cpp.
References lmms::gui::getGUI(), m_clip, and lmms::gui::GuiApplication::pianoRoll().
Referenced by AutomationEditor(), horScrolled(), leaveEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), resetGhostNotes(), resizeEvent(), setCurrentClip(), setEditMode(), setProgressionType(), setQuantization(), setTension(), updateAfterClipChange(), verScrolled(), wheelEvent(), and zoomingXChanged().
updateAfterClipChange
void lmms::gui::AutomationEditor::updateAfterClipChange () slot
Definition at line 214 of file AutomationEditor.cpp.
References centerTopBottomScroll(), m_clip, m_currentPosition, m_maxLevel, m_minLevel, m_scrollLevel, m_step, m_tensionModel, resizeEvent(), update(), and validClip().
Referenced by AutomationEditor(), lmms::Clip::copyStateTo(), and lmms::gui::AutomationClipView::disconnectObject().
updatePosition
void lmms::gui::AutomationEditor::updatePosition (const lmms::TimePos & t) protected slot
Definition at line 1831 of file AutomationEditor.cpp.
References lmms::Song::AutomationClip, lmms::TimePos::getBar(), lmms::Engine::getSong(), m_currentPosition, m_leftRightScroll, m_ppb, m_scrollBack, lmms::TimePos::ticksPerBar(), and VALUES_WIDTH.
Referenced by AutomationEditor().
updateTopBottomLevels()
void lmms::gui::AutomationEditor::updateTopBottomLevels () private
Definition at line 1899 of file AutomationEditor.cpp.
References m_bottomLevel, m_maxLevel, m_minLevel, m_scrollLevel, m_topLevel, m_y_auto, m_y_delta, SCROLLBAR_SIZE, and TOP_MARGIN.
Referenced by resizeEvent(), and verScrolled().
validClip()
bool lmms::gui::AutomationEditor::validClip () const inline
Definition at line 85 of file AutomationEditor.h.
References m_clip.
Referenced by inPatternEditor(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), paintEvent(), play(), setProgressionType(), stop(), and updateAfterClipChange().
verScrolled
void lmms::gui::AutomationEditor::verScrolled (int new_pos) protected slot
Definition at line 1769 of file AutomationEditor.cpp.
References m_scrollLevel, update(), and updateTopBottomLevels().
Referenced by AutomationEditor().
wheelEvent()
void lmms::gui::AutomationEditor::wheelEvent (QWheelEvent * we) override protected
Definition at line 1594 of file AutomationEditor.cpp.
References adjustLeftRightScoll(), DEFAULT_PPB, m_leftRightScroll, m_ppb, m_quantizeModel, m_topBottomScroll, m_zoomingXModel, m_zoomingYModel, m_zoomXLevels, lmms::position(), lmms::TimePos::ticksPerBar(), update(), and VALUES_WIDTH.
xCoordOfTick()
int lmms::gui::AutomationEditor::xCoordOfTick (int tick) protected
Definition at line 1474 of file AutomationEditor.cpp.
References m_currentPosition, m_ppb, lmms::TimePos::ticksPerBar(), and VALUES_WIDTH.
Referenced by drawAutomationPoint(), drawAutomationTangents(), drawLevelTick(), and paintEvent().
yCoordOfLevel()
float lmms::gui::AutomationEditor::yCoordOfLevel (float level) protected
Definition at line 1483 of file AutomationEditor.cpp.
References m_bottomLevel, m_maxLevel, m_minLevel, m_y_auto, m_y_delta, SCROLLBAR_SIZE, and TOP_MARGIN.
Referenced by drawAutomationPoint(), drawAutomationTangents(), drawLevelTick(), getNodeAt(), mouseMoveEvent(), and paintEvent().
zoomingXChanged
void lmms::gui::AutomationEditor::zoomingXChanged () protected slot
Definition at line 1858 of file AutomationEditor.cpp.
References DEFAULT_PPB, m_ppb, m_timeLine, m_zoomingXModel, m_zoomXLevels, and update().
zoomingYChanged
void lmms::gui::AutomationEditor::zoomingYChanged () protected slot
Definition at line 1871 of file AutomationEditor.cpp.
References DEFAULT_Y_DELTA, m_y_auto, m_y_delta, m_zoomingYModel, and resizeEvent().
Friends And Related Symbol Documentation
AutomationEditorWindow
friend class AutomationEditorWindow friend
Definition at line 296 of file AutomationEditor.h.
References AutomationEditorWindow.
Referenced by AutomationEditorWindow.
Member Data Documentation
DEFAULT_PPB
const int lmms::gui::AutomationEditor::DEFAULT_PPB = 12 * DEFAULT_STEPS_PER_BAR static private
Definition at line 195 of file AutomationEditor.h.
Referenced by AutomationEditor(), wheelEvent(), and zoomingXChanged().
DEFAULT_STEPS_PER_BAR
const int lmms::gui::AutomationEditor::DEFAULT_STEPS_PER_BAR = 16 static private
Definition at line 194 of file AutomationEditor.h.
DEFAULT_Y_DELTA
const int lmms::gui::AutomationEditor::DEFAULT_Y_DELTA = 6 static private
Definition at line 193 of file AutomationEditor.h.
Referenced by AutomationEditor(), paintEvent(), and zoomingYChanged().
m_action
Action lmms::gui::AutomationEditor::m_action private
Definition at line 247 of file AutomationEditor.h.
Referenced by AutomationEditor(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
m_backgroundShade
QColor lmms::gui::AutomationEditor::m_backgroundShade private
Definition at line 288 of file AutomationEditor.h.
Referenced by AutomationEditor(), and paintEvent().
m_barLineColor
QColor lmms::gui::AutomationEditor::m_barLineColor private
Definition at line 279 of file AutomationEditor.h.
Referenced by AutomationEditor(), and paintEvent().
m_beatLineColor
QColor lmms::gui::AutomationEditor::m_beatLineColor private
Definition at line 280 of file AutomationEditor.h.
Referenced by AutomationEditor(), and paintEvent().
m_bottomLevel
float lmms::gui::AutomationEditor::m_bottomLevel private
Definition at line 230 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawAutomationTangents(), drawCross(), drawLevelTick(), getLevel(), paintEvent(), updateTopBottomLevels(), and yCoordOfLevel().
m_clip
AutomationClip* lmms::gui::AutomationEditor::m_clip private
Definition at line 225 of file AutomationEditor.h.
Referenced by AutomationEditor(), centerTopBottomScroll(), currentClip(), drawCross(), drawLine(), fineTuneValue(), getClosestNode(), getNodeAt(), inPatternEditor(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), play(), setCurrentClip(), setProgressionType(), setTension(), stop(), update(), updateAfterClipChange(), and validClip().
m_crossColor
QColor lmms::gui::AutomationEditor::m_crossColor private
Definition at line 287 of file AutomationEditor.h.
Referenced by AutomationEditor(), and drawCross().
m_currentPosition
TimePos lmms::gui::AutomationEditor::m_currentPosition private
Definition at line 245 of file AutomationEditor.h.
Referenced by AutomationEditor(), getClosestNode(), getNodeAt(), horScrolled(), mouseMoveEvent(), mousePressEvent(), paintEvent(), updateAfterClipChange(), updatePosition(), and xCoordOfTick().
m_detuningNoteColor
QColor lmms::gui::AutomationEditor::m_detuningNoteColor private
Definition at line 290 of file AutomationEditor.h.
Referenced by paintEvent().
m_draggedOutTangent
bool lmms::gui::AutomationEditor::m_draggedOutTangent private
Definition at line 264 of file AutomationEditor.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_draggedOutValueKey
int lmms::gui::AutomationEditor::m_draggedOutValueKey private
Definition at line 259 of file AutomationEditor.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_draggedTangentTick
int lmms::gui::AutomationEditor::m_draggedTangentTick private
Definition at line 262 of file AutomationEditor.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_drawLastLevel
float lmms::gui::AutomationEditor::m_drawLastLevel private
Definition at line 251 of file AutomationEditor.h.
Referenced by AutomationEditor(), mouseMoveEvent(), and mousePressEvent().
m_drawLastTick
tick_t lmms::gui::AutomationEditor::m_drawLastTick private
Definition at line 252 of file AutomationEditor.h.
Referenced by AutomationEditor(), mouseMoveEvent(), and mousePressEvent().
m_editMode
EditMode lmms::gui::AutomationEditor::m_editMode private
Definition at line 266 of file AutomationEditor.h.
Referenced by AutomationEditor(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), and setEditMode().
m_ghostNoteColor
QColor lmms::gui::AutomationEditor::m_ghostNoteColor private
Definition at line 289 of file AutomationEditor.h.
Referenced by AutomationEditor(), and paintEvent().
m_ghostNotes
MidiClip* lmms::gui::AutomationEditor::m_ghostNotes = nullptr private
Definition at line 233 of file AutomationEditor.h.
Referenced by paintEvent(), resetGhostNotes(), and setGhostMidiClip().
m_ghostSample
QPointer<SampleClip> lmms::gui::AutomationEditor::m_ghostSample = nullptr private
Definition at line 234 of file AutomationEditor.h.
Referenced by paintEvent(), resetGhostNotes(), and setGhostSample().
m_ghostSampleColor
QColor lmms::gui::AutomationEditor::m_ghostSampleColor private
Definition at line 291 of file AutomationEditor.h.
Referenced by paintEvent().
m_graphColor
QBrush lmms::gui::AutomationEditor::m_graphColor private
Definition at line 282 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawLevelTick(), and paintEvent().
m_leftRightScroll
QScrollBar* lmms::gui::AutomationEditor::m_leftRightScroll private
Definition at line 240 of file AutomationEditor.h.
Referenced by AutomationEditor(), adjustLeftRightScoll(), paintEvent(), resizeEvent(), updatePosition(), and wheelEvent().
m_lineColor
QColor lmms::gui::AutomationEditor::m_lineColor private
Definition at line 281 of file AutomationEditor.h.
Referenced by AutomationEditor(), and paintEvent().
m_maxLevel
float lmms::gui::AutomationEditor::m_maxLevel private
Definition at line 227 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawCross(), drawLevelTick(), getLevel(), paintEvent(), resizeEvent(), updateAfterClipChange(), updateTopBottomLevels(), and yCoordOfLevel().
m_minLevel
float lmms::gui::AutomationEditor::m_minLevel private
Definition at line 226 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawCross(), drawLevelTick(), getLevel(), paintEvent(), resizeEvent(), updateAfterClipChange(), updateTopBottomLevels(), and yCoordOfLevel().
m_mouseDownLeft
bool lmms::gui::AutomationEditor::m_mouseDownLeft private
Definition at line 268 of file AutomationEditor.h.
Referenced by AutomationEditor(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_mouseDownRight
bool lmms::gui::AutomationEditor::m_mouseDownRight private
Definition at line 269 of file AutomationEditor.h.
Referenced by AutomationEditor(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_moveXOffset
int lmms::gui::AutomationEditor::m_moveXOffset private
Definition at line 249 of file AutomationEditor.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_nodeInValueColor
QColor lmms::gui::AutomationEditor::m_nodeInValueColor private
Definition at line 283 of file AutomationEditor.h.
Referenced by AutomationEditor(), and drawAutomationPoint().
m_nodeOutValueColor
QColor lmms::gui::AutomationEditor::m_nodeOutValueColor private
Definition at line 284 of file AutomationEditor.h.
Referenced by AutomationEditor(), and drawAutomationPoint().
m_nodeTangentLineColor
QColor lmms::gui::AutomationEditor::m_nodeTangentLineColor private
Definition at line 285 of file AutomationEditor.h.
Referenced by AutomationEditor(), and drawAutomationTangents().
m_outOfBoundsShade
QColor lmms::gui::AutomationEditor::m_outOfBoundsShade private
Definition at line 292 of file AutomationEditor.h.
Referenced by AutomationEditor(), and paintEvent().
m_ppb
int lmms::gui::AutomationEditor::m_ppb private
Definition at line 254 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawAutomationPoint(), drawAutomationTangents(), getClosestNode(), getNodeAt(), mouseMoveEvent(), mousePressEvent(), paintEvent(), updatePosition(), wheelEvent(), xCoordOfTick(), and zoomingXChanged().
m_quantizeModel
ComboBoxModel lmms::gui::AutomationEditor::m_quantizeModel private
Definition at line 219 of file AutomationEditor.h.
Referenced by AutomationEditor(), ~AutomationEditor(), setQuantization(), and wheelEvent().
m_renderSample
bool lmms::gui::AutomationEditor::m_renderSample = false private
Definition at line 235 of file AutomationEditor.h.
Referenced by paintEvent(), setGhostMidiClip(), and setGhostSample().
m_sampleThumbnail
SampleThumbnail lmms::gui::AutomationEditor::m_sampleThumbnail private
Definition at line 294 of file AutomationEditor.h.
Referenced by paintEvent(), and setGhostSample().
m_scaleColor
QBrush lmms::gui::AutomationEditor::m_scaleColor private
Definition at line 286 of file AutomationEditor.h.
Referenced by AutomationEditor(), and paintEvent().
m_scrollBack
bool lmms::gui::AutomationEditor::m_scrollBack private
Definition at line 272 of file AutomationEditor.h.
Referenced by AutomationEditor(), stop(), and updatePosition().
m_scrollLevel
float lmms::gui::AutomationEditor::m_scrollLevel private
Definition at line 229 of file AutomationEditor.h.
Referenced by AutomationEditor(), centerTopBottomScroll(), resizeEvent(), updateAfterClipChange(), updateTopBottomLevels(), and verScrolled().
m_step
float lmms::gui::AutomationEditor::m_step private
Definition at line 228 of file AutomationEditor.h.
Referenced by AutomationEditor(), getLevel(), and updateAfterClipChange().
m_tensionModel
FloatModel* lmms::gui::AutomationEditor::m_tensionModel private
Definition at line 223 of file AutomationEditor.h.
Referenced by AutomationEditor(), ~AutomationEditor(), setTension(), and updateAfterClipChange().
m_timeLine
TimeLineWidget* lmms::gui::AutomationEditor::m_timeLine private
Definition at line 271 of file AutomationEditor.h.
Referenced by AutomationEditor(), keyPressEvent(), resizeEvent(), and zoomingXChanged().
m_toolDraw
QPixmap lmms::gui::AutomationEditor::m_toolDraw = embed::getIconPixmap("edit_draw") private
Definition at line 209 of file AutomationEditor.h.
Referenced by paintEvent().
m_toolDrawOut
QPixmap lmms::gui::AutomationEditor::m_toolDrawOut = embed::getIconPixmap("edit_draw_outvalue") private
Definition at line 211 of file AutomationEditor.h.
Referenced by paintEvent().
m_toolEditTangents
QPixmap lmms::gui::AutomationEditor::m_toolEditTangents = embed::getIconPixmap("edit_tangent") private
Definition at line 212 of file AutomationEditor.h.
Referenced by paintEvent().
m_toolErase
QPixmap lmms::gui::AutomationEditor::m_toolErase = embed::getIconPixmap("edit_erase") private
Definition at line 210 of file AutomationEditor.h.
Referenced by paintEvent().
m_toolMove
QPixmap lmms::gui::AutomationEditor::m_toolMove = embed::getIconPixmap("edit_move") private
Definition at line 213 of file AutomationEditor.h.
Referenced by paintEvent().
m_toolXFlip
QPixmap lmms::gui::AutomationEditor::m_toolXFlip = embed::getIconPixmap("flip_x") private
Definition at line 215 of file AutomationEditor.h.
m_toolYFlip
QPixmap lmms::gui::AutomationEditor::m_toolYFlip = embed::getIconPixmap("flip_y") private
Definition at line 214 of file AutomationEditor.h.
m_topBottomScroll
QScrollBar* lmms::gui::AutomationEditor::m_topBottomScroll private
Definition at line 241 of file AutomationEditor.h.
Referenced by AutomationEditor(), centerTopBottomScroll(), keyPressEvent(), resizeEvent(), and wheelEvent().
m_topLevel
float lmms::gui::AutomationEditor::m_topLevel private
Definition at line 231 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawAutomationTangents(), drawLevelTick(), getLevel(), paintEvent(), and updateTopBottomLevels().
m_y_auto
bool lmms::gui::AutomationEditor::m_y_auto private
Definition at line 256 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawCross(), drawLevelTick(), getLevel(), paintEvent(), resizeEvent(), updateTopBottomLevels(), yCoordOfLevel(), and zoomingYChanged().
m_y_delta
int lmms::gui::AutomationEditor::m_y_delta private
Definition at line 255 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawCross(), drawLevelTick(), getLevel(), paintEvent(), resizeEvent(), updateTopBottomLevels(), yCoordOfLevel(), and zoomingYChanged().
m_zoomingXModel
ComboBoxModel lmms::gui::AutomationEditor::m_zoomingXModel private
Definition at line 217 of file AutomationEditor.h.
Referenced by AutomationEditor(), ~AutomationEditor(), adjustLeftRightScoll(), paintEvent(), wheelEvent(), and zoomingXChanged().
m_zoomingYModel
ComboBoxModel lmms::gui::AutomationEditor::m_zoomingYModel private
Definition at line 218 of file AutomationEditor.h.
Referenced by AutomationEditor(), ~AutomationEditor(), wheelEvent(), and zoomingYChanged().
m_zoomXLevels
const std::array< float, 7 > lmms::gui::AutomationEditor::m_zoomXLevels static private
Initial value:
=
        { 0.125f, 0.25f, 0.5f, 1.0f, 2.0f, 4.0f, 8.0f }
Definition at line 221 of file AutomationEditor.h.
Referenced by adjustLeftRightScoll(), paintEvent(), wheelEvent(), and zoomingXChanged().
MAX_SAMPLE_HEIGHT
int lmms::gui::AutomationEditor::MAX_SAMPLE_HEIGHT = 400 static constexpr private
Definition at line 203 of file AutomationEditor.h.
Referenced by paintEvent().
MIN_NOTE_RANGE
const int lmms::gui::AutomationEditor::MIN_NOTE_RANGE = 20 static private
Definition at line 201 of file AutomationEditor.h.
Referenced by paintEvent().
NOTE_HEIGHT
const int lmms::gui::AutomationEditor::NOTE_HEIGHT = 10 static private
Definition at line 199 of file AutomationEditor.h.
Referenced by paintEvent().
NOTE_MARGIN
const int lmms::gui::AutomationEditor::NOTE_MARGIN = 40 static private
Definition at line 200 of file AutomationEditor.h.
Referenced by paintEvent().
SAMPLE_MARGIN
const int lmms::gui::AutomationEditor::SAMPLE_MARGIN = 40 static private
Definition at line 202 of file AutomationEditor.h.
Referenced by paintEvent().
SCROLLBAR_SIZE
const int lmms::gui::AutomationEditor::SCROLLBAR_SIZE = 12 static private
Definition at line 190 of file AutomationEditor.h.
Referenced by drawAutomationTangents(), drawCross(), drawLevelTick(), getLevel(), paintEvent(), resizeEvent(), updateTopBottomLevels(), and yCoordOfLevel().
TOP_MARGIN
const int lmms::gui::AutomationEditor::TOP_MARGIN = 16 static private
Definition at line 191 of file AutomationEditor.h.
Referenced by drawAutomationTangents(), drawCross(), drawLevelTick(), getLevel(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), paintEvent(), resizeEvent(), updateTopBottomLevels(), and yCoordOfLevel().
VALUES_WIDTH
const int lmms::gui::AutomationEditor::VALUES_WIDTH = 64 static private
Definition at line 197 of file AutomationEditor.h.
Referenced by AutomationEditor(), drawCross(), getClosestNode(), getNodeAt(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), paintEvent(), resizeEvent(), updatePosition(), wheelEvent(), and xCoordOfTick().
Property Documentation
backgroundShade
QColor lmms::gui::AutomationEditor::backgroundShade
Definition at line 70 of file AutomationEditor.h.
barLineColor
QColor lmms::gui::AutomationEditor::barLineColor
Definition at line 61 of file AutomationEditor.h.
beatLineColor
QColor lmms::gui::AutomationEditor::beatLineColor
Definition at line 62 of file AutomationEditor.h.
crossColor
QColor lmms::gui::AutomationEditor::crossColor
Definition at line 69 of file AutomationEditor.h.
detuningNoteColor
QColor lmms::gui::AutomationEditor::detuningNoteColor
Definition at line 72 of file AutomationEditor.h.
ghostNoteColor
QColor lmms::gui::AutomationEditor::ghostNoteColor
Definition at line 71 of file AutomationEditor.h.
ghostSampleColor
QColor lmms::gui::AutomationEditor::ghostSampleColor
Definition at line 73 of file AutomationEditor.h.
graphColor
QBrush lmms::gui::AutomationEditor::graphColor
Definition at line 68 of file AutomationEditor.h.
lineColor
QColor lmms::gui::AutomationEditor::lineColor
Definition at line 63 of file AutomationEditor.h.
nodeInValueColor
QColor lmms::gui::AutomationEditor::nodeInValueColor
Definition at line 64 of file AutomationEditor.h.
nodeOutValueColor
QColor lmms::gui::AutomationEditor::nodeOutValueColor
Definition at line 65 of file AutomationEditor.h.
nodeTangentLineColor
QColor lmms::gui::AutomationEditor::nodeTangentLineColor
Definition at line 66 of file AutomationEditor.h.
outOfBoundsShade
QColor lmms::gui::AutomationEditor::outOfBoundsShade
Definition at line 74 of file AutomationEditor.h.
scaleColor
QBrush lmms::gui::AutomationEditor::scaleColor
Definition at line 67 of file AutomationEditor.h.
The documentation for this class was generated from the following files:
include/AutomationEditor.h
src/gui/editors/AutomationEditor.cpp