LMMS: Jack::JackConnectionManager Class Reference
Jack::JackConnectionManager Class Reference
Connection manager.
#include <JackConnectionManager.h>
Public Member Functions
JackConnectionManager ()
~JackConnectionManager ()
int AddInputPort (int refnum, jack_port_id_t port_index)
Add an input port to a client.
int AddOutputPort (int refnum, jack_port_id_t port_index)
Add an output port to a client.
int Connect (jack_port_id_t port_src, jack_port_id_t port_dst)
Connect port_src to port_dst.
jack_int_t Connections (jack_port_id_t port_index) const
Get the connection number of a given port.
void DecDirectConnection (jack_port_id_t port_src, jack_port_id_t port_dst)
Decrement the number of ports between 2 clients, if the 2 clients become disconnected, then the Activation counter is updated.
bool DecFeedbackConnection (jack_port_id_t port_src, jack_port_id_t port_dst)
void DirectConnect (int ref1, int ref2)
Directly connect 2 reference numbers.
void DirectDisconnect (int ref1, int ref2)
Directly disconnect 2 reference numbers.
int Disconnect (jack_port_id_t port_src, jack_port_id_t port_dst)
Disconnect port_src from port_dst.
int GetActivation (int refnum) const
const jack_int_t * GetConnections (jack_port_id_t port_index) const
Get the connection port array.
const jack_int_t * GetInputPorts (int refnum)
Get the input port array of a given refnum.
int GetInputRefNum (jack_port_id_t port_index) const
Get the client refnum of a given input port.
const jack_int_t * GetOutputPorts (int refnum)
Get the output port array of a given refnum.
int GetOutputRefNum (jack_port_id_t port_index) const
Get the client refnum of a given output port.
jack_port_id_t GetPort (jack_port_id_t port_index, int connection) const
void IncDirectConnection (jack_port_id_t port_src, jack_port_id_t port_dst)
Increment the number of ports between 2 clients, if the 2 clients become connected, then the Activation counter is updated.
bool IncFeedbackConnection (jack_port_id_t port_src, jack_port_id_t port_dst)
void InitRefNum (int refnum)
Init the refnum.
bool IsConnected (jack_port_id_t port_src, jack_port_id_t port_dst) const
Check if port_src and port_dst are connected.
bool IsDirectConnection (int ref1, int ref2) const
Returns the connections state between 2 refnum.
bool IsFeedbackConnection (jack_port_id_t port_src, jack_port_id_t port_dst) const
bool IsLoopPath (jack_port_id_t port_src, jack_port_id_t port_dst) const
Test is a connection path exists between port_src and port_dst.
int RemoveInputPort (int refnum, jack_port_id_t port_index)
Remove an input port from a client.
int RemoveOutputPort (int refnum, jack_port_id_t port_index)
Remove an output port from a client.
void ResetGraph (JackClientTiming *timing)
Reset all clients activation.
int ResumeRefNum (JackClientControl *control, JackSynchro *table, JackClientTiming *timing)
Signal clients connected to the given client.
int SuspendRefNum (JackClientControl *control, JackSynchro *table, JackClientTiming *timing, long time_out_usec)
Wait on the input synchro.
void TopologicalSort (std::vector< jack_int_t > &sorted)
Private Member Functions
bool IsLoopPathAux (int ref1, int ref2) const
Loop feedback connections.
Private Attributes
JackFixedArray< CONNECTION_NUM_FOR_PORT > fConnection [PORT_NUM_MAX]
JackFixedMatrix< CLIENT_NUM > fConnectionRef
Table of output port per refnum : to find a refnum for a given port.
JackActivationCount fInputCounter [CLIENT_NUM]
Table of port connections by (refnum , refnum).
JackFixedArray1< PORT_NUM_FOR_CLIENT > fInputPort [CLIENT_NUM]
Connection matrix: list of connected ports for a given port: needed to compute Mix buffer.
JackLoopFeedback< CONNECTION_NUM_FOR_PORT > fLoopFeedback
Activation counter per refnum.
JackFixedArray< PORT_NUM_FOR_CLIENT > fOutputPort [CLIENT_NUM]
Table of input port per refnum : to find a refnum for a given port.
Detailed Description
Connection manager.
The fConnection array contains the list (array line) of connected ports for a given port.
The fInputPort array contains the list (array line) of input connected ports for a given client.
The fOutputPort array contains the list (array line) of output connected ports for a given client.
The fConnectionRef array contains the number of ports connected between two clients.
The fInputCounter array contains the number of input clients connected to a given for activation purpose.
Definition at line 411 of file JackConnectionManager.h.
Constructor & Destructor Documentation
JackConnectionManager()
Jack::JackConnectionManager::JackConnectionManager ()
Definition at line 32 of file JackConnectionManager.cpp.
References JackConnectionManager(), CLIENT_NUM, fConnection, fInputCounter, fLoopFeedback, i, InitRefNum(), jack_log(), offsetof, and PORT_NUM_MAX.
Referenced by JackConnectionManager().
~JackConnectionManager()
Jack::JackConnectionManager::~JackConnectionManager ()
Definition at line 52 of file JackConnectionManager.cpp.
Member Function Documentation
AddInputPort()
int Jack::JackConnectionManager::AddInputPort (int refnum, jack_port_id_t port_index)
Add an input port to a client.
Definition at line 141 of file JackConnectionManager.cpp.
References fInputPort, jack_error, and jack_log().
Referenced by Jack::JackGraphManager::AllocatePort().
AddOutputPort()
int Jack::JackConnectionManager::AddOutputPort (int refnum, jack_port_id_t port_index)
Add an output port to a client.
Definition at line 155 of file JackConnectionManager.cpp.
References fOutputPort, jack_error, and jack_log().
Referenced by Jack::JackGraphManager::AllocatePort().
Connect()
int Jack::JackConnectionManager::Connect (jack_port_id_t port_src, jack_port_id_t port_dst)
Connect port_src to port_dst.
Definition at line 91 of file JackConnectionManager.cpp.
References fConnection, jack_error, and jack_log().
Referenced by Jack::JackGraphManager::Connect().
Connections()
jack_int_t Jack::JackConnectionManager::Connections (jack_port_id_t port_index) const inline
Get the connection number of a given port.
Definition at line 438 of file JackConnectionManager.h.
References fConnection.
Referenced by Jack::JackGraphManager::GetBuffer(), and Jack::JackGraphManager::GetConnectionsNum().
DecDirectConnection()
void Jack::JackConnectionManager::DecDirectConnection (jack_port_id_t port_src, jack_port_id_t port_dst)
Decrement the number of ports between 2 clients, if the 2 clients become disconnected, then the Activation counter is updated.
Definition at line 338 of file JackConnectionManager.cpp.
References DirectDisconnect(), GetInputRefNum(), GetOutputRefNum(), and jack_log().
Referenced by Jack::JackGraphManager::Disconnect().
DecFeedbackConnection()
bool Jack::JackConnectionManager::DecFeedbackConnection (jack_port_id_t port_src, jack_port_id_t port_dst)
Definition at line 441 of file JackConnectionManager.cpp.
References DirectDisconnect(), fLoopFeedback, GetInputRefNum(), GetOutputRefNum(), and jack_log().
Referenced by Jack::JackGraphManager::Disconnect().
DirectConnect()
void Jack::JackConnectionManager::DirectConnect (int ref1, int ref2)
Directly connect 2 reference numbers.
Definition at line 352 of file JackConnectionManager.cpp.
References fConnectionRef, fInputCounter, and jack_log().
Referenced by Jack::JackGraphManager::DirectConnect(), IncDirectConnection(), and IncFeedbackConnection().
DirectDisconnect()
void Jack::JackConnectionManager::DirectDisconnect (int ref1, int ref2)
Directly disconnect 2 reference numbers.
Definition at line 365 of file JackConnectionManager.cpp.
References fConnectionRef, fInputCounter, and jack_log().
Referenced by DecDirectConnection(), DecFeedbackConnection(), and Jack::JackGraphManager::DirectDisconnect().
Disconnect()
int Jack::JackConnectionManager::Disconnect (jack_port_id_t port_src, jack_port_id_t port_dst)
Disconnect port_src from port_dst.
Definition at line 106 of file JackConnectionManager.cpp.
References fConnection, jack_error, and jack_log().
Referenced by Jack::JackGraphManager::Disconnect().
GetActivation()
int Jack::JackConnectionManager::GetActivation (int refnum) const inline
Definition at line 479 of file JackConnectionManager.h.
References fInputCounter.
Referenced by Jack::JackGraphManager::IsFinishedGraph().
GetConnections()
const jack_int_t * Jack::JackConnectionManager::GetConnections (jack_port_id_t port_index) const
Get the connection port array.
Definition at line 129 of file JackConnectionManager.cpp.
References fConnection.
Referenced by Jack::JackGraphManager::ComputeTotalLatencyAux(), Jack::JackGraphManager::DisconnectAllOutput(), Jack::JackGraphManager::GetBuffer(), Jack::JackGraphManager::GetConnections(), Jack::JackGraphManager::GetConnectionsAux(), Jack::JackGraphManager::RecalculateLatencyAux(), and Jack::JackGraphManager::RequestMonitor().
GetInputPorts()
const jack_int_t * Jack::JackConnectionManager::GetInputPorts (int refnum)
Get the input port array of a given refnum.
Definition at line 199 of file JackConnectionManager.cpp.
References fInputPort.
Referenced by Jack::JackGraphManager::DisconnectAllPorts(), Jack::JackGraphManager::GetInputPorts(), and Jack::JackGraphManager::RemoveAllPorts().
GetInputRefNum()
int Jack::JackConnectionManager::GetInputRefNum (jack_port_id_t port_index) const
Get the client refnum of a given input port.
Definition at line 387 of file JackConnectionManager.cpp.
References CLIENT_NUM, fInputPort, and i.
Referenced by DecDirectConnection(), DecFeedbackConnection(), Jack::JackGraphManager::GetInputRefNum(), IncDirectConnection(), IncFeedbackConnection(), IsFeedbackConnection(), and IsLoopPath().
GetOutputPorts()
const jack_int_t * Jack::JackConnectionManager::GetOutputPorts (int refnum)
Get the output port array of a given refnum.
Definition at line 207 of file JackConnectionManager.cpp.
References fOutputPort.
Referenced by Jack::JackGraphManager::DisconnectAllPorts(), Jack::JackGraphManager::GetOutputPorts(), and Jack::JackGraphManager::RemoveAllPorts().
GetOutputRefNum()
int Jack::JackConnectionManager::GetOutputRefNum (jack_port_id_t port_index) const
Get the client refnum of a given output port.
Definition at line 401 of file JackConnectionManager.cpp.
References CLIENT_NUM, fOutputPort, and i.
Referenced by DecDirectConnection(), DecFeedbackConnection(), Jack::JackGraphManager::GetOutputRefNum(), IncDirectConnection(), IncFeedbackConnection(), IsFeedbackConnection(), and IsLoopPath().
GetPort()
jack_port_id_t Jack::JackConnectionManager::GetPort (jack_port_id_t port_index, int connection) const inline
Definition at line 443 of file JackConnectionManager.h.
References CONNECTION_NUM_FOR_PORT, and fConnection.
Referenced by Jack::JackGraphManager::GetBuffer().
IncDirectConnection()
void Jack::JackConnectionManager::IncDirectConnection (jack_port_id_t port_src, jack_port_id_t port_dst)
Increment the number of ports between 2 clients, if the 2 clients become connected, then the Activation counter is updated.
Definition at line 324 of file JackConnectionManager.cpp.
References DirectConnect(), GetInputRefNum(), GetOutputRefNum(), and jack_log().
Referenced by Jack::JackGraphManager::Connect().
IncFeedbackConnection()
bool Jack::JackConnectionManager::IncFeedbackConnection (jack_port_id_t port_src, jack_port_id_t port_dst)
Definition at line 425 of file JackConnectionManager.cpp.
References DirectConnect(), fLoopFeedback, GetInputRefNum(), GetOutputRefNum(), and jack_log().
Referenced by Jack::JackGraphManager::Connect().
InitRefNum()
void Jack::JackConnectionManager::InitRefNum (int refnum)
Init the refnum.
Definition at line 215 of file JackConnectionManager.cpp.
References fConnectionRef, fInputCounter, fInputPort, and fOutputPort.
Referenced by JackConnectionManager(), and Jack::JackGraphManager::InitRefNum().
IsConnected()
bool Jack::JackConnectionManager::IsConnected (jack_port_id_t port_src, jack_port_id_t port_dst) const
Check if port_src and port_dst are connected.
Definition at line 121 of file JackConnectionManager.cpp.
References fConnection.
Referenced by Jack::JackGraphManager::Connect(), Jack::JackGraphManager::Disconnect(), Jack::JackGraphManager::DisconnectAllInput(), and Jack::JackGraphManager::IsConnected().
IsDirectConnection()
bool Jack::JackConnectionManager::IsDirectConnection (int ref1, int ref2) const
Returns the connections state between 2 refnum.
Definition at line 378 of file JackConnectionManager.cpp.
References fConnectionRef.
Referenced by Jack::JackGraphManager::IsDirectConnection().
IsFeedbackConnection()
bool Jack::JackConnectionManager::IsFeedbackConnection (jack_port_id_t port_src, jack_port_id_t port_dst) const
Definition at line 420 of file JackConnectionManager.cpp.
References fLoopFeedback, GetInputRefNum(), and GetOutputRefNum().
Referenced by Jack::JackGraphManager::Disconnect().
IsLoopPath()
bool Jack::JackConnectionManager::IsLoopPath (jack_port_id_t port_src, jack_port_id_t port_dst) const
Test is a connection path exists between port_src and port_dst.
Definition at line 415 of file JackConnectionManager.cpp.
References GetInputRefNum(), GetOutputRefNum(), and IsLoopPathAux().
Referenced by Jack::JackGraphManager::Connect().
IsLoopPathAux()
bool Jack::JackConnectionManager::IsLoopPathAux (int ref1, int ref2) const private
Loop feedback connections.
Definition at line 59 of file JackConnectionManager.cpp.
References CLIENT_NUM, EMPTY, fConnectionRef, Jack::GetEngineControl(), i, IsLoopPathAux(), and jack_log().
Referenced by IsLoopPath(), and IsLoopPathAux().
RemoveInputPort()
int Jack::JackConnectionManager::RemoveInputPort (int refnum, jack_port_id_t port_index)
Remove an input port from a client.
Definition at line 169 of file JackConnectionManager.cpp.
References fInputPort, jack_error, and jack_log().
Referenced by Jack::JackGraphManager::ReleasePort().
RemoveOutputPort()
int Jack::JackConnectionManager::RemoveOutputPort (int refnum, jack_port_id_t port_index)
Remove an output port from a client.
Definition at line 184 of file JackConnectionManager.cpp.
References fOutputPort, jack_error, and jack_log().
Referenced by Jack::JackGraphManager::ReleasePort().
ResetGraph()
void Jack::JackConnectionManager::ResetGraph (JackClientTiming * timing)
Reset all clients activation.
Definition at line 226 of file JackConnectionManager.cpp.
References CLIENT_NUM, fInputCounter, Jack::JackClientTiming::fStatus, i, and NotTriggered.
Referenced by Jack::JackGraphManager::RunCurrentGraph(), and Jack::JackGraphManager::RunNextGraph().
ResumeRefNum()
int Jack::JackConnectionManager::ResumeRefNum (JackClientControl * control, JackSynchro * table, JackClientTiming * timing)
Signal clients connected to the given client.
Definition at line 251 of file JackConnectionManager.cpp.
References CLIENT_NUM, fConnectionRef, Jack::JackClientTiming::fFinishedAt, Finished, fInputCounter, Jack::JackClientControl::fRefNum, Jack::JackClientTiming::fSignaledAt, Jack::JackClientTiming::fStatus, GetMicroSeconds(), i, jack_log(), and Triggered.
Referenced by Jack::JackGraphManager::ResumeRefNum().
SuspendRefNum()
int Jack::JackConnectionManager::SuspendRefNum (JackClientControl * control, JackSynchro * table, JackClientTiming * timing, long time_out_usec)
Wait on the input synchro.
Definition at line 238 of file JackConnectionManager.cpp.
References Jack::JackClientTiming::fAwakeAt, Jack::JackClientControl::fRefNum, Jack::JackClientTiming::fStatus, GetMicroSeconds(), Running, and Jack::JackAndroidSemaphore::TimedWait().
Referenced by Jack::JackGraphManager::SuspendRefNum().
TopologicalSort()
void Jack::JackConnectionManager::TopologicalSort (std::vector< jack_int_t > & sorted)
Definition at line 290 of file JackConnectionManager.cpp.
References AUDIO_DRIVER_REFNUM, Jack::JackFixedMatrix< SIZE >::ClearItem(), CLIENT_NUM, fConnectionRef, FREEWHEEL_DRIVER_REFNUM, Jack::JackFixedMatrix< SIZE >::GetItems(), Jack::JackFixedMatrix< SIZE >::GetOutputTable1(), and Jack::HasNoConnection().
Referenced by Jack::JackGraphManager::TopologicalSort().
Member Data Documentation
fConnection
JackFixedArray<CONNECTION_NUM_FOR_PORT> Jack::JackConnectionManager::fConnection[PORT_NUM_MAX] private
Definition at line 416 of file JackConnectionManager.h.
Referenced by JackConnectionManager(), Connect(), Connections(), Disconnect(), GetConnections(), GetPort(), and IsConnected().
fConnectionRef
JackFixedMatrix<CLIENT_NUM> Jack::JackConnectionManager::fConnectionRef private
Table of output port per refnum : to find a refnum for a given port.
Definition at line 419 of file JackConnectionManager.h.
Referenced by DirectConnect(), DirectDisconnect(), InitRefNum(), IsDirectConnection(), IsLoopPathAux(), ResumeRefNum(), and TopologicalSort().
fInputCounter
JackActivationCount Jack::JackConnectionManager::fInputCounter[CLIENT_NUM] private
Table of port connections by (refnum , refnum).
Definition at line 420 of file JackConnectionManager.h.
Referenced by JackConnectionManager(), DirectConnect(), DirectDisconnect(), GetActivation(), InitRefNum(), ResetGraph(), and ResumeRefNum().
fInputPort
JackFixedArray1<PORT_NUM_FOR_CLIENT> Jack::JackConnectionManager::fInputPort[CLIENT_NUM] private
Connection matrix: list of connected ports for a given port: needed to compute Mix buffer.
Definition at line 417 of file JackConnectionManager.h.
Referenced by AddInputPort(), GetInputPorts(), GetInputRefNum(), InitRefNum(), and RemoveInputPort().
fLoopFeedback
JackLoopFeedback<CONNECTION_NUM_FOR_PORT> Jack::JackConnectionManager::fLoopFeedback private
Activation counter per refnum.
Definition at line 421 of file JackConnectionManager.h.
Referenced by JackConnectionManager(), DecFeedbackConnection(), IncFeedbackConnection(), and IsFeedbackConnection().
fOutputPort
JackFixedArray<PORT_NUM_FOR_CLIENT> Jack::JackConnectionManager::fOutputPort[CLIENT_NUM] private
Table of input port per refnum : to find a refnum for a given port.
Definition at line 418 of file JackConnectionManager.h.
Referenced by AddOutputPort(), GetOutputPorts(), GetOutputRefNum(), InitRefNum(), and RemoveOutputPort().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackConnectionManager.h
src/3rdparty/jack2/common/JackConnectionManager.cpp