LMMS: Jack::JackTransportEngine Class Reference
Jack::JackTransportEngine Class Reference
#include <JackTransportEngine.h>
Public Member Functions
JackTransportEngine ()
~JackTransportEngine ()
void CycleBegin (jack_nframes_t frame_rate, jack_time_t time)
void CycleEnd (JackClientInterface **table, jack_nframes_t frame_rate, jack_nframes_t buffer_size)
jack_unique_t GenerateUniqueID ()
jack_nframes_t GetCurrentFrame ()
bool GetNetworkSync () const
jack_transport_state_t GetState () const
void GetTimebaseMaster (int &refnum, bool &conditionnal)
jack_transport_state_t Query (jack_position_t *pos)
void ReadCurrentPos (jack_position_t *pos)
void RequestNewPos (jack_position_t *pos)
int ResetTimebase (int refnum)
void SetCommand (transport_command_t state)
void SetNetworkSync (bool sync)
void SetState (jack_transport_state_t state)
void SetSyncTimeout (jack_time_t timeout)
int SetTimebaseMaster (int refnum, bool conditionnal)
Public Member Functions inherited from Jack::JackAtomicArrayState< jack_position_t >
JackAtomicArrayState ()
~JackAtomicArrayState ()
UInt16 GetCurrentIndex ()
Returns the current switch counter.
jack_position_t * ReadCurrentState ()
Returns the current state : only valid in the RT reader thread.
jack_position_t * TrySwitchState (int state)
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
jack_position_t * WriteNextStateStart (int state)
Start write operation : setup and returns the next state to update, check for recursive write calls.
void WriteNextStateStop (int state)
Stop write operation : make the next state ready to be used by the RT thread.
Static Public Member Functions
static void CopyPosition (jack_position_t *from, jack_position_t *to)
Private Member Functions
bool CheckAllRolling (JackClientInterface **table)
void MakeAllLocating (JackClientInterface **table)
void MakeAllStartingLocating (JackClientInterface **table)
void MakeAllStopping (JackClientInterface **table)
void SyncTimeout (jack_nframes_t frame_rate, jack_nframes_t buffer_size)
Private Attributes
bool fConditionnal
bool fNetworkSync
bool fPendingPos
transport_command_t fPreviousCmd
int fSyncTimeLeft
jack_time_t fSyncTimeout
int fTimeBaseMaster
volatile transport_command_t fTransportCmd
jack_transport_state_t fTransportState
SInt32 fWriteCounter
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAtomicArrayState< jack_position_t >
UInt32 WriteNextStateStartAux (int state, bool *result)
void WriteNextStateStopAux (int state)
Protected Attributes inherited from Jack::JackAtomicArrayState< jack_position_t >
volatile AtomicArrayCounter fCounter
jack_position_t fState [3]
Detailed Description
Definition at line 93 of file JackTransportEngine.h.
Constructor & Destructor Documentation
JackTransportEngine()
Jack::JackTransportEngine::JackTransportEngine ()
Definition at line 37 of file JackTransportEngine.cpp.
References Jack::JackAtomicArrayState< jack_position_t >::JackAtomicArrayState(), JackTransportEngine(), fConditionnal, fNetworkSync, fPendingPos, fPreviousCmd, fSyncTimeLeft, fSyncTimeout, fTimeBaseMaster, fTransportCmd, fTransportState, fWriteCounter, JackTransportStopped, offsetof, and Jack::TransportCommandStop.
Referenced by JackTransportEngine().
~JackTransportEngine()
Jack::JackTransportEngine::~JackTransportEngine () inline
Definition at line 120 of file JackTransportEngine.h.
Member Function Documentation
CheckAllRolling()
bool Jack::JackTransportEngine::CheckAllRolling (JackClientInterface ** table) private
Definition at line 95 of file JackTransportEngine.cpp.
References client(), CLIENT_NUM, Jack::GetEngineControl(), i, jack_log(), and JackTransportRolling.
Referenced by CycleEnd().
CopyPosition()
void Jack::JackTransportEngine::CopyPosition (jack_position_t * from, jack_position_t * to) static
Definition at line 294 of file JackTransportEngine.cpp.
References jack_error, JackSleep(), _jack_position::unique_1, and _jack_position::unique_2.
Referenced by CycleEnd(), and RequestNewPos().
CycleBegin()
void Jack::JackTransportEngine::CycleBegin (jack_nframes_t frame_rate, jack_time_t time)
Definition at line 155 of file JackTransportEngine.cpp.
References _jack_position::frame_rate, _jack_position::usecs, Jack::JackAtomicArrayState< jack_position_t >::WriteNextStateStart(), and Jack::JackAtomicArrayState< jack_position_t >::WriteNextStateStop().
CycleEnd()
void Jack::JackTransportEngine::CycleEnd (JackClientInterface ** table, jack_nframes_t frame_rate, jack_nframes_t buffer_size)
Definition at line 164 of file JackTransportEngine.cpp.
References CheckAllRolling(), CopyPosition(), fNetworkSync, fPendingPos, fPreviousCmd, _jack_position::frame, fSyncTimeLeft, fTransportCmd, fTransportState, jack_error, jack_log(), JackTransportNetStarting, JackTransportRolling, JackTransportStarting, JackTransportStopped, MakeAllLocating(), MakeAllStartingLocating(), MakeAllStopping(), Jack::JackAtomicArrayState< jack_position_t >::ReadCurrentState(), SyncTimeout(), Jack::TransportCommandNone, Jack::TransportCommandStart, Jack::TransportCommandStop, Jack::JackAtomicArrayState< jack_position_t >::TrySwitchState(), Jack::JackAtomicArrayState< jack_position_t >::WriteNextStateStart(), and Jack::JackAtomicArrayState< jack_position_t >::WriteNextStateStop().
GenerateUniqueID()
jack_unique_t Jack::JackTransportEngine::GenerateUniqueID () inline
Definition at line 174 of file JackTransportEngine.h.
References fWriteCounter, and INC_ATOMIC().
Referenced by RequestNewPos().
GetCurrentFrame()
jack_nframes_t Jack::JackTransportEngine::GetCurrentFrame ()
Definition at line 279 of file JackTransportEngine.cpp.
References fTransportState, GetMicroSeconds(), JackTransportRolling, pos, and ReadCurrentPos().
Referenced by Jack::JackClient::GetCurrentTransportFrame().
GetNetworkSync()
bool Jack::JackTransportEngine::GetNetworkSync () const inline
Definition at line 187 of file JackTransportEngine.h.
References fNetworkSync.
GetState()
jack_transport_state_t Jack::JackTransportEngine::GetState () const inline
Definition at line 128 of file JackTransportEngine.h.
References fTransportState.
Referenced by Jack::JackClient::CallSyncCallbackAux(), Jack::JackClient::CallTimebaseCallbackAux(), and Query().
GetTimebaseMaster()
void Jack::JackTransportEngine::GetTimebaseMaster (int & refnum, bool & conditionnal) inline
Definition at line 148 of file JackTransportEngine.h.
References fConditionnal, and fTimeBaseMaster.
Referenced by Jack::JackClient::CallTimebaseCallbackAux().
MakeAllLocating()
void Jack::JackTransportEngine::MakeAllLocating (JackClientInterface ** table) private
Definition at line 140 of file JackTransportEngine.cpp.
References client(), CLIENT_NUM, Jack::JackClientControl::fTransportState, Jack::JackClientControl::fTransportSync, Jack::JackClientControl::fTransportTimebase, Jack::GetEngineControl(), i, jack_log(), and JackTransportStopped.
Referenced by CycleEnd().
MakeAllStartingLocating()
void Jack::JackTransportEngine::MakeAllStartingLocating (JackClientInterface ** table) private
Definition at line 109 of file JackTransportEngine.cpp.
References client(), CLIENT_NUM, Jack::JackClientControl::fActive, Jack::JackClientControl::fCallback, Jack::JackClientControl::fTransportState, Jack::JackClientControl::fTransportSync, Jack::JackClientControl::fTransportTimebase, Jack::GetEngineControl(), i, jack_log(), JackTransportRolling, JackTransportStarting, and Jack::kRealTimeCallback.
Referenced by CycleEnd().
MakeAllStopping()
void Jack::JackTransportEngine::MakeAllStopping (JackClientInterface ** table) private
Definition at line 125 of file JackTransportEngine.cpp.
References client(), CLIENT_NUM, Jack::JackClientControl::fTransportState, Jack::JackClientControl::fTransportSync, Jack::JackClientControl::fTransportTimebase, Jack::GetEngineControl(), i, jack_log(), and JackTransportStopped.
Referenced by CycleEnd().
Query()
jack_transport_state_t Jack::JackTransportEngine::Query (jack_position_t * pos)
Definition at line 272 of file JackTransportEngine.cpp.
References GetState(), pos, and ReadCurrentPos().
Referenced by Jack::JackClient::TransportQuery().
ReadCurrentPos()
void Jack::JackTransportEngine::ReadCurrentPos (jack_position_t * pos)
Definition at line 252 of file JackTransportEngine.cpp.
References Jack::JackAtomicArrayState< jack_position_t >::GetCurrentIndex(), pos, and Jack::JackAtomicArrayState< jack_position_t >::ReadCurrentState().
Referenced by GetCurrentFrame(), and Query().
RequestNewPos()
void Jack::JackTransportEngine::RequestNewPos (jack_position_t * pos)
Definition at line 263 of file JackTransportEngine.cpp.
References CopyPosition(), GenerateUniqueID(), jack_log(), pos, Jack::JackAtomicArrayState< jack_position_t >::WriteNextStateStart(), and Jack::JackAtomicArrayState< jack_position_t >::WriteNextStateStop().
Referenced by Jack::JackClient::TransportLocate(), and Jack::JackClient::TransportReposition().
ResetTimebase()
int Jack::JackTransportEngine::ResetTimebase (int refnum)
Definition at line 62 of file JackTransportEngine.cpp.
References fTimeBaseMaster, _jack_position::valid, Jack::JackAtomicArrayState< jack_position_t >::WriteNextStateStart(), and Jack::JackAtomicArrayState< jack_position_t >::WriteNextStateStop().
SetCommand()
void Jack::JackTransportEngine::SetCommand (transport_command_t state) inline
Definition at line 123 of file JackTransportEngine.h.
References fTransportCmd.
Referenced by Jack::JackClient::TransportStart(), and Jack::JackClient::TransportStop().
SetNetworkSync()
void Jack::JackTransportEngine::SetNetworkSync (bool sync) inline
Definition at line 192 of file JackTransportEngine.h.
References fNetworkSync.
SetState()
void Jack::JackTransportEngine::SetState (jack_transport_state_t state) inline
Definition at line 133 of file JackTransportEngine.h.
References fTransportState.
SetSyncTimeout()
void Jack::JackTransportEngine::SetSyncTimeout (jack_time_t timeout) inline
Definition at line 167 of file JackTransportEngine.h.
References fSyncTimeout.
Referenced by Jack::JackClient::SetSyncTimeout().
SetTimebaseMaster()
int Jack::JackTransportEngine::SetTimebaseMaster (int refnum, bool conditionnal)
Definition at line 76 of file JackTransportEngine.cpp.
References fConditionnal, fTimeBaseMaster, and jack_log().
SyncTimeout()
void Jack::JackTransportEngine::SyncTimeout (jack_nframes_t frame_rate, jack_nframes_t buffer_size) private
Definition at line 54 of file JackTransportEngine.cpp.
References fSyncTimeLeft, fSyncTimeout, and jack_log().
Referenced by CycleEnd().
Member Data Documentation
fConditionnal
bool Jack::JackTransportEngine::fConditionnal private
Definition at line 106 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), GetTimebaseMaster(), and SetTimebaseMaster().
fNetworkSync
bool Jack::JackTransportEngine::fNetworkSync private
Definition at line 105 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), CycleEnd(), GetNetworkSync(), and SetNetworkSync().
fPendingPos
bool Jack::JackTransportEngine::fPendingPos private
Definition at line 104 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), and CycleEnd().
fPreviousCmd
transport_command_t Jack::JackTransportEngine::fPreviousCmd private
Definition at line 100 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), and CycleEnd().
fSyncTimeLeft
int Jack::JackTransportEngine::fSyncTimeLeft private
Definition at line 102 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), CycleEnd(), and SyncTimeout().
fSyncTimeout
jack_time_t Jack::JackTransportEngine::fSyncTimeout private
Definition at line 101 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), SetSyncTimeout(), and SyncTimeout().
fTimeBaseMaster
int Jack::JackTransportEngine::fTimeBaseMaster private
Definition at line 103 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), GetTimebaseMaster(), ResetTimebase(), and SetTimebaseMaster().
fTransportCmd
volatile transport_command_t Jack::JackTransportEngine::fTransportCmd private
Definition at line 99 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), CycleEnd(), and SetCommand().
fTransportState
jack_transport_state_t Jack::JackTransportEngine::fTransportState private
Definition at line 98 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), CycleEnd(), GetCurrentFrame(), GetState(), and SetState().
fWriteCounter
SInt32 Jack::JackTransportEngine::fWriteCounter private
Definition at line 107 of file JackTransportEngine.h.
Referenced by JackTransportEngine(), and GenerateUniqueID().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackTransportEngine.h
src/3rdparty/jack2/common/JackTransportEngine.cpp