LMMS: lmms::gui::ClipView Class Reference
lmms::gui::ClipView Class Reference
#include <ClipView.h>
Public Slots
virtual bool close ()
Close a ClipView.
void randomizeColor ()
void remove ()
Removes a ClipView from its track view.
void resetColor ()
void selectColor ()
void update () override
Update a ClipView.
Public Slots inherited from lmms::gui::selectableObject
virtual void update ()
Public Member Functions
ClipView (Clip *clip, TrackView *tv)
Create a new ClipView.
~ClipView () override
Destroy a ClipView.
void copy (QVector< ClipView * > clipvs)
void cut (QVector< ClipView * > clipvs)
bool fixedClips ()
Does this ClipView have a fixed Clip?
QVector< ClipView * > getClickedClips ()
Clip * getClip ()
QColor getColorForDisplay (QColor)
TrackView * getTrackView ()
bool gradient () const
QColor markerColor () const
QColor mutedBackgroundColor () const
QColor mutedColor () const
CSS theming qproperty access method.
bool needsUpdate ()
void paste ()
QColor patternClipBackground () const
QColor selectedColor () const
void setGradient (const bool &b)
void setMarkerColor (const QColor &c)
void setMarkerEnabled (bool e)
void setMarkerPos (int x)
void setMutedBackgroundColor (const QColor &c)
void setMutedColor (const QColor &c)
CSS theming qproperty access method.
void setNeedsUpdate (bool b)
void setPatternClipBackground (const QColor &c)
void setSelectedColor (const QColor &c)
void setTextBackgroundColor (const QColor &c)
void setTextColor (const QColor &c)
void setTextShadowColor (const QColor &c)
QColor textBackgroundColor () const
QColor textColor () const
QColor textShadowColor () const
void toggleSelectedAutoResize ()
Public Member Functions inherited from lmms::gui::selectableObject
selectableObject (QWidget *_parent)
~selectableObject () override=default
bool isSelected () const
void setSelected (bool selected)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Static Public Member Functions
static void remove (QVector< ClipView * > clipvs)
static void toggleMute (QVector< ClipView * > clipvs)
Static Public Attributes
static const int BORDER_WIDTH = 2
Protected Types
enum class ContextMenuAction {
Remove ,
Cut ,
Copy ,
Paste ,
Mute
}
Protected Slots
void updateLength ()
Updates a ClipView's length.
void updatePosition ()
Updates a ClipView's position.
Protected Member Functions
virtual void constructContextMenu (QMenu *)
void contextMenuAction (ContextMenuAction action)
void contextMenuEvent (QContextMenuEvent *cme) override
Set up the context menu for this ClipView.
DataFile createClipDataFiles (const QVector< ClipView * > &clips) const
Create a DataFile suitable for copying multiple clips.
void dragEnterEvent (QDragEnterEvent *dee) override
Change the ClipView's display when something being dragged enters it.
void dropEvent (QDropEvent *de) override
Handle something being dropped on this ClipObjectView.
auto hasCustomColor () const -> bool
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse movement (drag) on this ClipView.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press on this ClipView.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release on this ClipView.
virtual void paintTextLabel (QString const &text, QPainter &painter)
float pixelsPerBar ()
How many pixels a bar takes for this ClipView.
TimePos quantizeSplitPos (TimePos)
void resizeEvent (QResizeEvent *re) override
bool unquantizedModHeld (QMouseEvent *me)
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Protected Attributes
TimePos m_initialClipEnd
TimePos m_initialClipPos
bool m_marker = false
int m_markerPos = 0
TrackView * m_trackView
Properties
bool gradient
QColor markerColor
QColor mutedBackgroundColor
QColor mutedColor
QColor patternClipBackground
QColor selectedColor
QColor textBackgroundColor
QColor textColor
QColor textShadowColor
Private Types
enum class Action {
None ,
Move ,
MoveSelection ,
Resize ,
ResizeLeft ,
Split ,
CopySelection ,
ToggleSelected
}
Private Member Functions
virtual bool destructiveSplitClip (const TimePos pos)
Destructively split this Clip into two clips.
TimePos draggedClipPos (QMouseEvent *me)
Calculate the new position of a dragged Clip from a mouse event.
virtual bool isResizableBeforeStart ()
Returns whether the user can left-resize this clip so that the start of the clip bounds is before the start of the clip content.
int knifeMarkerPos (QMouseEvent *me)
bool mouseMovedDistance (QMouseEvent *me, int distance)
Detect whether the mouse moved more than n pixels on screen.
void setColor (const std::optional< QColor > &color)
Change color of all selected clips.
void setInitialOffsets ()
Save the offsets between all selected tracks and a clicked track.
void setInitialPos (QPoint pos)
bool splitClip (const TimePos pos)
Split this Clip into two clips.
void updateCursor (QMouseEvent *me)
Private Attributes
Action m_action
Clip * m_clip
bool m_gradient
TextFloat * m_hint
QPoint m_initialMouseGlobalPos
QPoint m_initialMousePos
QVector< TimePos > m_initialOffsets
QColor m_markerColor
QColor m_mutedBackgroundColor
QColor m_mutedColor
bool m_needsUpdate
QColor m_patternClipBackground
QColor m_selectedColor
QColor m_textBackgroundColor
QColor m_textColor
QColor m_textShadowColor
Static Private Attributes
static TextFloat * s_textFloat = nullptr
A pointer for that text bubble used when moving segments, etc.
Detailed Description
Definition at line 51 of file ClipView.h.
Member Enumeration Documentation
Action
enum class lmms::gui::ClipView::Action strong private
Enumerator
None
Move
MoveSelection
Resize
ResizeLeft
Split
CopySelection
ToggleSelected
Definition at line 190 of file ClipView.h.
ContextMenuAction
enum class lmms::gui::ClipView::ContextMenuAction strong protected
Enumerator
Remove
Cut
Copy
Paste
Mute
Definition at line 139 of file ClipView.h.
Constructor & Destructor Documentation
ClipView()
lmms::gui::ClipView::ClipView (Clip * clip, TrackView * tv)
Create a new ClipView.
Creates a new clip view for the given clip in the given track view.
Parameters
_clip The clip to be displayed
_tv The track view that will contain the new object
Definition at line 78 of file ClipView.cpp.
References lmms::gui::ModelView::ModelView(), lmms::gui::selectableObject::selectableObject(), close(), lmms::Track::colorChanged(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::gui::TrackView::getTrackContentWidget(), m_action, m_clip, m_gradient, m_hint, m_initialClipEnd, m_initialClipPos, m_initialMouseGlobalPos, m_initialMousePos, m_initialOffsets, m_markerColor, m_mutedBackgroundColor, m_mutedColor, m_needsUpdate, m_patternClipBackground, m_selectedColor, m_textColor, m_textShadowColor, m_trackView, None, lmms::gui::SongEditor::pixelsPerBarChanged(), s_textFloat, lmms::gui::ModelView::setModel(), update(), updateLength(), and updatePosition().
Referenced by lmms::gui::AutomationClipView::AutomationClipView(), lmms::gui::MidiClipView::MidiClipView(), lmms::gui::PatternClipView::PatternClipView(), lmms::gui::SampleClipView::SampleClipView(), dropEvent(), getClickedClips(), lmms::gui::MidiClipView::mergeClips(), mouseMoveEvent(), setInitialOffsets(), and lmms::gui::MidiClipView::transposeSelection().
~ClipView()
lmms::gui::ClipView::~ClipView () override
Destroy a ClipView.
Destroys the given ClipView.
Definition at line 145 of file ClipView.cpp.
References ~ClipView(), m_hint, and m_trackView.
Referenced by ~ClipView().
Member Function Documentation
close
bool lmms::gui::ClipView::close () virtual slot
Close a ClipView.
Closes a ClipView by asking the track view to remove us and then asking the QWidget to close us.
Returns
Boolean state of whether the QWidget was able to close.
Definition at line 263 of file ClipView.cpp.
References close(), and m_trackView.
Referenced by ClipView(), close(), and remove().
constructContextMenu()
virtual void lmms::gui::ClipView::constructContextMenu (QMenu *) inline protected virtual
Reimplemented in lmms::gui::AutomationClipView, lmms::gui::MidiClipView, lmms::gui::PatternClipView, and lmms::gui::SampleClipView.
Definition at line 155 of file ClipView.h.
Referenced by contextMenuEvent().
contextMenuAction()
void lmms::gui::ClipView::contextMenuAction (ContextMenuAction action) protected
Definition at line 1129 of file ClipView.cpp.
References contextMenuAction(), Copy, copy(), Cut, cut(), getClickedClips(), Mute, Paste, paste(), Remove, remove(), and toggleMute().
Referenced by contextMenuAction(), and contextMenuEvent().
contextMenuEvent()
void lmms::gui::ClipView::contextMenuEvent (QContextMenuEvent * cme) override protected
Set up the context menu for this ClipView.
Set up the various context menu events that can apply to a ClipView.
Parameters
cme The QContextMenuEvent to add the actions to.
Definition at line 1053 of file ClipView.cpp.
References constructContextMenu(), contextMenuAction(), contextMenuEvent(), Copy, Cut, fixedClips(), getClickedClips(), lmms::embed::getIconPixmap(), m_clip, Mute, Paste, randomizeColor(), Remove, resetColor(), selectColor(), toggleSelectedAutoResize(), and lmms::UI_CTRL_KEY.
Referenced by contextMenuEvent().
copy()
void lmms::gui::ClipView::copy (QVector< ClipView * > clipvs)
Definition at line 1186 of file ClipView.cpp.
References copy(), createClipDataFiles(), and m_clip.
Referenced by contextMenuAction(), copy(), and cut().
createClipDataFiles()
DataFile lmms::gui::ClipView::createClipDataFiles (const QVector< ClipView * > & clipViews) const protected
Create a DataFile suitable for copying multiple clips.
Clips in the vector are written to the "clips" node in the DataFile. The ClipView's initial mouse position is written to the "initialMouseX" node in the DataFile. When dropped on a track, this is used to create copies of the Clips.
Parameters
clips The trackContectObjects to save in a DataFile
Definition at line 512 of file ClipView.cpp.
References lmms::DataFile::content(), createClipDataFiles(), lmms::DataFile::DragNDropData, lmms::JournallingObject::id(), m_clip, m_trackView, lmms::Track::name(), lmms::Track::trackContainer(), lmms::TrackContainer::tracks(), and lmms::Track::type().
Referenced by copy(), createClipDataFiles(), and mouseMoveEvent().
cut()
void lmms::gui::ClipView::cut (QVector< ClipView * > clipvs)
Definition at line 1199 of file ClipView.cpp.
References copy(), cut(), and remove().
Referenced by contextMenuAction(), and cut().
destructiveSplitClip()
virtual bool lmms::gui::ClipView::destructiveSplitClip (const TimePos pos) inline private virtual
Destructively split this Clip into two clips.
If the clip type does not implement this feature, it will default to normal splitting.
Parameters
pos the position of the split, relative to the start of the clip
Returns
true if the clip could be split
Reimplemented in lmms::gui::MidiClipView.
Definition at line 251 of file ClipView.h.
References pos, and splitClip().
Referenced by mouseReleaseEvent().
dragEnterEvent()
void lmms::gui::ClipView::dragEnterEvent (QDragEnterEvent * dee) override protected
Change the ClipView's display when something being dragged enters it.
We need to notify Qt to change our display if something being dragged has entered our 'airspace'.
Parameters
dee The QDragEnterEvent to watch.
Definition at line 406 of file ClipView.cpp.
References lmms::gui::TrackContentWidget::canPasteSelection(), dragEnterEvent(), getTrackView(), m_clip, and lmms::gui::StringPairDrag::processDragEnterEvent().
Referenced by lmms::gui::AutomationClipView::dragEnterEvent(), dragEnterEvent(), and lmms::gui::SampleClipView::dragEnterEvent().
draggedClipPos()
TimePos lmms::gui::ClipView::draggedClipPos (QMouseEvent * me) private
Calculate the new position of a dragged Clip from a mouse event.
Parameters
me The QMouseEvent
Definition at line 1306 of file ClipView.cpp.
References draggedClipPos(), lmms::gui::getGUI(), m_clip, m_initialClipPos, m_initialMouseGlobalPos, m_initialMousePos, m_trackView, lmms::TimePos::quantize(), setInitialPos(), lmms::TimePos::ticksPerBar(), and unquantizedModHeld().
Referenced by draggedClipPos(), and mouseMoveEvent().
dropEvent()
void lmms::gui::ClipView::dropEvent (QDropEvent * de) override protected
Handle something being dropped on this ClipObjectView.
When something has been dropped on this ClipView, and it's a clip, then use an instance of our dataFile reader to take the xml of the clip and turn it into something we can write over our current state.
Parameters
de The QDropEvent to handle.
Definition at line 434 of file ClipView.cpp.
References ClipView(), lmms::DataFile::content(), lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), dropEvent(), getTrackView(), m_clip, m_trackView, lmms::gui::TrackContentWidget::pasteSelection(), pos, and lmms::AutomationClip::resolveAllIDs().
Referenced by lmms::gui::AutomationClipView::dropEvent(), dropEvent(), and lmms::gui::SampleClipView::dropEvent().
fixedClips()
bool lmms::gui::ClipView::fixedClips ()
Does this ClipView have a fixed Clip?
Returns whether the containing trackView has fixed Clips.
Todo
In what circumstance are they fixed?
Definition at line 182 of file ClipView.cpp.
References fixedClips(), and m_trackView.
Referenced by contextMenuEvent(), fixedClips(), lmms::gui::MidiClipView::mouseDoubleClickEvent(), mousePressEvent(), lmms::gui::MidiClipView::mousePressEvent(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::SampleClipView::paintEvent(), update(), updateLength(), and lmms::gui::MidiClipView::wheelEvent().
getClickedClips()
QVector< ClipView * > lmms::gui::ClipView::getClickedClips ()
Definition at line 1154 of file ClipView.cpp.
References ClipView(), getClickedClips(), and lmms::gui::getGUI().
Referenced by lmms::gui::MidiClipView::constructContextMenu(), contextMenuAction(), contextMenuEvent(), getClickedClips(), mousePressEvent(), setColor(), toggleSelectedAutoResize(), and lmms::gui::MidiClipView::transposeSelection().
getClip()
Clip * lmms::gui::ClipView::getClip () inline
Definition at line 74 of file ClipView.h.
References getClip(), inline, and m_clip.
Referenced by lmms::gui::TrackContentWidget::addClipView(), getClip(), lmms::gui::SampleClipView::mousePressEvent(), and lmms::gui::SampleClipView::mouseReleaseEvent().
getColorForDisplay()
QColor lmms::gui::ClipView::getColorForDisplay (QColor defaultColor)
Definition at line 1382 of file ClipView.cpp.
References getColorForDisplay(), hasCustomColor(), lmms::gui::selectableObject::isSelected(), m_clip, mutedBackgroundColor, and selectedColor.
Referenced by getColorForDisplay(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), and lmms::gui::PatternClipView::paintEvent().
getTrackView()
TrackView * lmms::gui::ClipView::getTrackView () inline
Definition at line 79 of file ClipView.h.
References m_trackView.
Referenced by lmms::gui::MidiClipView::canMergeSelection(), dragEnterEvent(), dropEvent(), lmms::gui::MidiClipView::mergeClips(), lmms::gui::SampleClipView::paintEvent(), and paste().
gradient()
bool lmms::gui::ClipView::gradient () const
Definition at line 214 of file ClipView.cpp.
References gradient, and m_gradient.
hasCustomColor()
auto lmms::gui::ClipView::hasCustomColor () const->bool protected
Definition at line 1420 of file ClipView.cpp.
References hasCustomColor(), and m_clip.
Referenced by getColorForDisplay(), hasCustomColor(), and lmms::gui::MidiClipView::paintEvent().
isResizableBeforeStart()
virtual bool lmms::gui::ClipView::isResizableBeforeStart () inline private virtual
Returns whether the user can left-resize this clip so that the start of the clip bounds is before the start of the clip content.
Reimplemented in lmms::gui::AutomationClipView, and lmms::gui::MidiClipView.
Definition at line 239 of file ClipView.h.
Referenced by mouseMoveEvent().
knifeMarkerPos()
int lmms::gui::ClipView::knifeMarkerPos (QMouseEvent * me) private
Definition at line 1340 of file ClipView.cpp.
References knifeMarkerPos(), m_trackView, quantizeSplitPos(), lmms::TimePos::ticksPerBar(), and unquantizedModHeld().
Referenced by knifeMarkerPos(), mouseMoveEvent(), and mousePressEvent().
markerColor()
QColor lmms::gui::ClipView::markerColor () const
Definition at line 217 of file ClipView.cpp.
References m_markerColor, and markerColor.
mouseMovedDistance()
bool lmms::gui::ClipView::mouseMovedDistance (QMouseEvent * me, int distance) private
Detect whether the mouse moved more than n pixels on screen.
Parameters
_me The QMouseEvent.
distance The threshold distance that the mouse has moved to return true.
Definition at line 1283 of file ClipView.cpp.
References m_initialMouseGlobalPos, and mouseMovedDistance().
Referenced by mouseMovedDistance(), mouseMoveEvent(), and mouseReleaseEvent().
mouseMoveEvent()
void lmms::gui::ClipView::mouseMoveEvent (QMouseEvent * me) override protected
Handle a mouse movement (drag) on this ClipView.
Handles the various ways in which a ClipView can be used with a mouse drag.
If in move mode, move ourselves in the track,
or if in move-selection mode, move the entire selection,
or if in resize mode, resize ourselves,
otherwise ???
Parameters
me The QMouseEvent to handle.
Todo
what does the final else case do here?
Definition at line 776 of file ClipView.cpp.
References ClipView(), CopySelection, createClipDataFiles(), draggedClipPos(), lmms::TimePos::getBar(), lmms::gui::getGUI(), lmms::TimePos::getTicks(), isResizableBeforeStart(), lmms::KBD_COPY_MODIFIER, knifeMarkerPos(), lmms::PatternStore::lengthOfPattern(), m_action, m_clip, m_hint, m_initialClipEnd, m_initialClipPos, m_initialMousePos, m_initialOffsets, m_trackView, max, min, mouseMovedDistance(), mouseMoveEvent(), Move, MoveSelection, None, lmms::Engine::patternStore(), lmms::position(), lmms::TimePos::quantize(), Resize, ResizeLeft, s_textFloat, setInitialPos(), setMarkerPos(), Split, lmms::TimePos::ticksPerBar(), ToggleSelected, unquantizedModHeld(), update(), and updateCursor().
Referenced by mouseMoveEvent().
mousePressEvent()
void lmms::gui::ClipView::mousePressEvent (QMouseEvent * me) override protected
Handle a mouse press on this ClipView.
Handles the various ways in which a ClipView can be used with a click of a mouse button.
If our container supports rubber band selection then handle selection events.
or if shift-left button, add this object to the selection
or if ctrl-left button, start a drag-copy event
or if just plain left button, resize if we're resizeable
or if ctrl-middle button, mute the clip
or if middle button, maybe delete the clip.
Parameters
me The QMouseEvent to handle.
Definition at line 607 of file ClipView.cpp.
References CopySelection, lmms::gui::TextFloat::displayMessage(), fixedClips(), getClickedClips(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::gui::selectableObject::isSelected(), lmms::KBD_COPY_MODIFIER, knifeMarkerPos(), m_action, m_clip, m_hint, m_trackView, mousePressEvent(), Move, MoveSelection, None, remove(), Resize, lmms::gui::RESIZE_GRIP_WIDTH, ResizeLeft, s_textFloat, setInitialOffsets(), setInitialPos(), setMarkerEnabled(), setMarkerPos(), Split, lmms::TimePos::ticksPerBar(), toggleMute(), ToggleSelected, lmms::UI_COPY_KEY, and update().
Referenced by mousePressEvent(), lmms::gui::MidiClipView::mousePressEvent(), and lmms::gui::SampleClipView::mousePressEvent().
mouseReleaseEvent()
void lmms::gui::ClipView::mouseReleaseEvent (QMouseEvent * me) override protected
Handle a mouse release on this ClipView.
If we're in move or resize mode, journal the change as appropriate. Then tidy up.
Parameters
me The QMouseEvent to handle.
Definition at line 1004 of file ClipView.cpp.
References CopySelection, destructiveSplitClip(), lmms::gui::selectableObject::isSelected(), m_action, m_clip, m_hint, m_trackView, mouseMovedDistance(), mouseReleaseEvent(), Move, None, quantizeSplitPos(), Resize, ResizeLeft, s_textFloat, setMarkerEnabled(), lmms::gui::selectableObject::setSelected(), Split, splitClip(), lmms::TimePos::ticksPerBar(), ToggleSelected, unquantizedModHeld(), and updateCursor().
Referenced by mouseReleaseEvent(), and lmms::gui::SampleClipView::mouseReleaseEvent().
mutedBackgroundColor()
QColor lmms::gui::ClipView::mutedBackgroundColor () const
Definition at line 194 of file ClipView.cpp.
References m_mutedBackgroundColor, and mutedBackgroundColor.
mutedColor()
QColor lmms::gui::ClipView::mutedColor () const
CSS theming qproperty access method.
Definition at line 191 of file ClipView.cpp.
References m_mutedColor, and mutedColor.
needsUpdate()
bool lmms::gui::ClipView::needsUpdate ()
Definition at line 251 of file ClipView.cpp.
References m_needsUpdate, and needsUpdate().
Referenced by needsUpdate(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), and lmms::gui::SampleClipView::paintEvent().
paintTextLabel()
void lmms::gui::ClipView::paintTextLabel (QString const & text, QPainter & painter) protected virtual
Definition at line 559 of file ClipView.cpp.
References BORDER_WIDTH, paintTextLabel(), textBackgroundColor, textColor, and textShadowColor.
Referenced by lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::SampleClipView::paintEvent(), and paintTextLabel().
paste()
void lmms::gui::ClipView::paste ()
Definition at line 1208 of file ClipView.cpp.
References getTrackView(), m_clip, paste(), lmms::gui::TrackContentWidget::pasteSelection(), and remove().
Referenced by contextMenuAction(), and paste().
patternClipBackground()
QColor lmms::gui::ClipView::patternClipBackground () const
Definition at line 211 of file ClipView.cpp.
References m_patternClipBackground, and patternClipBackground.
pixelsPerBar()
float lmms::gui::ClipView::pixelsPerBar () protected
How many pixels a bar takes for this ClipView.
Returns
the number of pixels per bar.
Definition at line 1251 of file ClipView.cpp.
References m_trackView, and pixelsPerBar().
Referenced by lmms::gui::MidiClipView::mousePressEvent(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::SampleClipView::paintEvent(), pixelsPerBar(), updateLength(), and lmms::gui::MidiClipView::wheelEvent().
quantizeSplitPos()
TimePos lmms::gui::ClipView::quantizeSplitPos (TimePos midiPos) protected
Definition at line 1362 of file ClipView.cpp.
References lmms::gui::getGUI(), m_clip, m_initialClipPos, lmms::TimePos::quantize(), and quantizeSplitPos().
Referenced by knifeMarkerPos(), mouseReleaseEvent(), and quantizeSplitPos().
randomizeColor
void lmms::gui::ClipView::randomizeColor () slot
Definition at line 353 of file ClipView.cpp.
References lmms::gui::ColorChooser::getPalette(), lmms::gui::ColorChooser::Mixer, randomizeColor(), and setColor().
Referenced by contextMenuEvent(), and randomizeColor().
remove [1/2]
void lmms::gui::ClipView::remove () slot
Removes a ClipView from its track view.
Like the close() method, this asks the track view to remove this ClipView. However, the clip is scheduled for later deletion rather than closed immediately.
Definition at line 279 of file ClipView.cpp.
References lmms::Engine::audioEngine(), close(), m_clip, m_trackView, remove(), and lmms::AudioEngine::requestChangesGuard().
Referenced by lmms::gui::MidiClipView::clearNotesOutOfBounds(), and lmms::gui::MidiClipView::destructiveSplitClip().
remove() [2/2]
void lmms::gui::ClipView::remove (QVector< ClipView * > clipvs) static
Definition at line 1177 of file ClipView.cpp.
References remove().
Referenced by contextMenuAction(), cut(), lmms::gui::SongEditor::keyPressEvent(), mousePressEvent(), paste(), remove(), and remove().
resetColor
void lmms::gui::ClipView::resetColor () slot
Definition at line 358 of file ClipView.cpp.
References resetColor(), and setColor().
Referenced by contextMenuEvent(), and resetColor().
resizeEvent()
void lmms::gui::ClipView::resizeEvent (QResizeEvent * re) inline override protected
Definition at line 166 of file ClipView.h.
References m_needsUpdate.
selectColor
void lmms::gui::ClipView::selectColor () slot
Definition at line 344 of file ClipView.cpp.
References m_clip, selectColor(), setColor(), lmms::gui::ColorChooser::Track, and lmms::gui::ColorChooser::withPalette().
Referenced by contextMenuEvent(), and selectColor().
selectedColor()
QColor lmms::gui::ClipView::selectedColor () const
Definition at line 197 of file ClipView.cpp.
References m_selectedColor, and selectedColor.
setColor()
void lmms::gui::ClipView::setColor (const std::optional< QColor > & color) private
Change color of all selected clips.
Parameters
color The new color.
Definition at line 367 of file ClipView.cpp.
References getClickedClips(), lmms::Engine::getSong(), setColor(), and lmms::Song::setModified().
Referenced by randomizeColor(), resetColor(), selectColor(), and setColor().
setGradient()
void lmms::gui::ClipView::setGradient (const bool & b)
Definition at line 244 of file ClipView.cpp.
References m_gradient, and setGradient().
Referenced by setGradient().
setInitialOffsets()
void lmms::gui::ClipView::setInitialOffsets () private
Save the offsets between all selected tracks and a clicked track.
Definition at line 1258 of file ClipView.cpp.
References ClipView(), m_initialClipPos, m_initialOffsets, m_trackView, and setInitialOffsets().
Referenced by mousePressEvent(), and setInitialOffsets().
setInitialPos()
void lmms::gui::ClipView::setInitialPos (QPoint pos) inline private
Definition at line 224 of file ClipView.h.
References m_clip, m_initialClipEnd, m_initialClipPos, m_initialMouseGlobalPos, m_initialMousePos, and pos.
Referenced by draggedClipPos(), mouseMoveEvent(), and mousePressEvent().
setMarkerColor()
void lmms::gui::ClipView::setMarkerColor (const QColor & c)
Definition at line 247 of file ClipView.cpp.
References m_markerColor, and setMarkerColor().
Referenced by setMarkerColor().
setMarkerEnabled()
void lmms::gui::ClipView::setMarkerEnabled (bool e) inline
Definition at line 127 of file ClipView.h.
References m_marker.
Referenced by mousePressEvent(), and mouseReleaseEvent().
setMarkerPos()
void lmms::gui::ClipView::setMarkerPos (int x) inline
Definition at line 126 of file ClipView.h.
References m_markerPos.
Referenced by mouseMoveEvent(), and mousePressEvent().
setMutedBackgroundColor()
void lmms::gui::ClipView::setMutedBackgroundColor (const QColor & c)
Definition at line 224 of file ClipView.cpp.
References m_mutedBackgroundColor, and setMutedBackgroundColor().
Referenced by setMutedBackgroundColor().
setMutedColor()
void lmms::gui::ClipView::setMutedColor (const QColor & c)
CSS theming qproperty access method.
Definition at line 221 of file ClipView.cpp.
References m_mutedColor, and setMutedColor().
Referenced by setMutedColor().
setNeedsUpdate()
void lmms::gui::ClipView::setNeedsUpdate (bool b)
Definition at line 253 of file ClipView.cpp.
References m_needsUpdate, and setNeedsUpdate().
Referenced by lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::SampleClipView::paintEvent(), and setNeedsUpdate().
setPatternClipBackground()
void lmms::gui::ClipView::setPatternClipBackground (const QColor & c)
Definition at line 241 of file ClipView.cpp.
References m_patternClipBackground, and setPatternClipBackground().
Referenced by setPatternClipBackground().
setSelectedColor()
void lmms::gui::ClipView::setSelectedColor (const QColor & c)
Definition at line 227 of file ClipView.cpp.
References m_selectedColor, and setSelectedColor().
Referenced by setSelectedColor().
setTextBackgroundColor()
void lmms::gui::ClipView::setTextBackgroundColor (const QColor & c)
Definition at line 233 of file ClipView.cpp.
References m_textBackgroundColor, and setTextBackgroundColor().
Referenced by setTextBackgroundColor().
setTextColor()
void lmms::gui::ClipView::setTextColor (const QColor & c)
Definition at line 230 of file ClipView.cpp.
References m_textColor, and setTextColor().
Referenced by setTextColor().
setTextShadowColor()
void lmms::gui::ClipView::setTextShadowColor (const QColor & c)
Definition at line 238 of file ClipView.cpp.
References m_textShadowColor, and setTextShadowColor().
Referenced by setTextShadowColor().
splitClip()
bool lmms::gui::ClipView::splitClip (const TimePos pos) private
Split this Clip into two clips.
Parameters
pos the position of the split, relative to the start of the clip
Returns
true if the clip could be split
Definition at line 1425 of file ClipView.cpp.
References m_clip, m_initialClipEnd, m_initialClipPos, pos, and splitClip().
Referenced by destructiveSplitClip(), mouseReleaseEvent(), and splitClip().
textBackgroundColor()
QColor lmms::gui::ClipView::textBackgroundColor () const
Definition at line 203 of file ClipView.cpp.
References m_textBackgroundColor, and textBackgroundColor.
textColor()
QColor lmms::gui::ClipView::textColor () const
Definition at line 200 of file ClipView.cpp.
References m_textColor, and textColor.
textShadowColor()
QColor lmms::gui::ClipView::textShadowColor () const
Definition at line 208 of file ClipView.cpp.
References m_textShadowColor, and textShadowColor.
toggleMute()
void lmms::gui::ClipView::toggleMute (QVector< ClipView * > clipvs) static
Definition at line 1225 of file ClipView.cpp.
References toggleMute().
Referenced by contextMenuAction(), mousePressEvent(), and toggleMute().
toggleSelectedAutoResize()
void lmms::gui::ClipView::toggleSelectedAutoResize ()
Definition at line 1234 of file ClipView.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), getClickedClips(), lmms::Clip::getTrack(), m_clip, lmms::Clip::setAutoResize(), toggleSelectedAutoResize(), and lmms::Clip::updateLength().
Referenced by contextMenuEvent(), and toggleSelectedAutoResize().
unquantizedModHeld()
bool lmms::gui::ClipView::unquantizedModHeld (QMouseEvent * me) protected
Definition at line 1293 of file ClipView.cpp.
References unquantizedModHeld().
Referenced by draggedClipPos(), knifeMarkerPos(), mouseMoveEvent(), mouseReleaseEvent(), and unquantizedModHeld().
update
void lmms::gui::ClipView::update () override slot
Update a ClipView.
Clip's get drawn only when needed, and when a Clip is updated, it needs to be redrawn.
Definition at line 163 of file ClipView.cpp.
References fixedClips(), m_needsUpdate, update(), lmms::gui::selectableObject::update(), and updateLength().
Referenced by ClipView(), lmms::gui::SampleClipView::SampleClipView(), lmms::gui::SampleClipView::dropEvent(), mouseMoveEvent(), mousePressEvent(), lmms::gui::SampleClipView::reverseSample(), lmms::gui::AutomationClipView::update(), update(), lmms::gui::MidiClipView::update(), lmms::gui::PatternClipView::update(), and lmms::gui::SampleClipView::updateSample().
updateCursor()
void lmms::gui::ClipView::updateCursor (QMouseEvent * me) private
Definition at line 483 of file ClipView.cpp.
References lmms::gui::selectableObject::isSelected(), m_clip, m_trackView, lmms::gui::RESIZE_GRIP_WIDTH, and updateCursor().
Referenced by mouseMoveEvent(), mouseReleaseEvent(), and updateCursor().
updateLength
void lmms::gui::ClipView::updateLength () protected slot
Updates a ClipView's length.
If this ClipView has a fixed Clip, then we must keep the width of our parent. Otherwise, calculate our width from the clip's length in pixels adding in the border.
Definition at line 311 of file ClipView.cpp.
References fixedClips(), m_clip, m_trackView, pixelsPerBar(), lmms::TimePos::ticksPerBar(), and updateLength().
Referenced by ClipView(), update(), and updateLength().
updatePosition
void lmms::gui::ClipView::updatePosition () protected slot
Updates a ClipView's position.
Ask our track view to change our position. Then make sure that the track view is updated in case this position has changed the track view's length.
Definition at line 336 of file ClipView.cpp.
References m_trackView, and updatePosition().
Referenced by ClipView(), and updatePosition().
Member Data Documentation
BORDER_WIDTH
const int lmms::gui::ClipView::BORDER_WIDTH = 2 static
Definition at line 67 of file ClipView.h.
Referenced by lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::MidiClipView::mousePressEvent(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::SampleClipView::paintEvent(), paintTextLabel(), and lmms::gui::MidiClipView::wheelEvent().
m_action
Action lmms::gui::ClipView::m_action private
Definition at line 205 of file ClipView.h.
Referenced by ClipView(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_clip
Clip* lmms::gui::ClipView::m_clip private
Definition at line 204 of file ClipView.h.
Referenced by ClipView(), contextMenuEvent(), copy(), createClipDataFiles(), dragEnterEvent(), draggedClipPos(), dropEvent(), getClip(), getColorForDisplay(), hasCustomColor(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paste(), quantizeSplitPos(), remove(), selectColor(), setInitialPos(), splitClip(), toggleSelectedAutoResize(), updateCursor(), and updateLength().
m_gradient
bool lmms::gui::ClipView::m_gradient private
Definition at line 220 of file ClipView.h.
Referenced by ClipView(), gradient(), and setGradient().
m_hint
TextFloat* lmms::gui::ClipView::m_hint private
Definition at line 210 of file ClipView.h.
Referenced by ClipView(), ~ClipView(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_initialClipEnd
TimePos lmms::gui::ClipView::m_initialClipEnd protected
Definition at line 150 of file ClipView.h.
Referenced by ClipView(), lmms::gui::MidiClipView::destructiveSplitClip(), mouseMoveEvent(), setInitialPos(), and splitClip().
m_initialClipPos
TimePos lmms::gui::ClipView::m_initialClipPos protected
Definition at line 149 of file ClipView.h.
Referenced by ClipView(), lmms::gui::MidiClipView::destructiveSplitClip(), draggedClipPos(), mouseMoveEvent(), quantizeSplitPos(), setInitialOffsets(), setInitialPos(), and splitClip().
m_initialMouseGlobalPos
QPoint lmms::gui::ClipView::m_initialMouseGlobalPos private
Definition at line 207 of file ClipView.h.
Referenced by ClipView(), draggedClipPos(), mouseMovedDistance(), and setInitialPos().
m_initialMousePos
QPoint lmms::gui::ClipView::m_initialMousePos private
Definition at line 206 of file ClipView.h.
Referenced by ClipView(), draggedClipPos(), mouseMoveEvent(), and setInitialPos().
m_initialOffsets
QVector<TimePos> lmms::gui::ClipView::m_initialOffsets private
Definition at line 208 of file ClipView.h.
Referenced by ClipView(), mouseMoveEvent(), and setInitialOffsets().
m_marker
bool lmms::gui::ClipView::m_marker = false protected
Definition at line 152 of file ClipView.h.
Referenced by lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::SampleClipView::paintEvent(), and setMarkerEnabled().
m_markerColor
QColor lmms::gui::ClipView::m_markerColor private
Definition at line 221 of file ClipView.h.
Referenced by ClipView(), markerColor(), and setMarkerColor().
m_markerPos
int lmms::gui::ClipView::m_markerPos = 0 protected
Definition at line 153 of file ClipView.h.
Referenced by lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::SampleClipView::paintEvent(), and setMarkerPos().
m_mutedBackgroundColor
QColor lmms::gui::ClipView::m_mutedBackgroundColor private
Definition at line 214 of file ClipView.h.
Referenced by ClipView(), mutedBackgroundColor(), and setMutedBackgroundColor().
m_mutedColor
QColor lmms::gui::ClipView::m_mutedColor private
Definition at line 213 of file ClipView.h.
Referenced by ClipView(), mutedColor(), and setMutedColor().
m_needsUpdate
bool lmms::gui::ClipView::m_needsUpdate private
Definition at line 223 of file ClipView.h.
Referenced by ClipView(), needsUpdate(), resizeEvent(), setNeedsUpdate(), and update().
m_patternClipBackground
QColor lmms::gui::ClipView::m_patternClipBackground private
Definition at line 219 of file ClipView.h.
Referenced by ClipView(), patternClipBackground(), and setPatternClipBackground().
m_selectedColor
QColor lmms::gui::ClipView::m_selectedColor private
Definition at line 215 of file ClipView.h.
Referenced by ClipView(), selectedColor(), and setSelectedColor().
m_textBackgroundColor
QColor lmms::gui::ClipView::m_textBackgroundColor private
Definition at line 217 of file ClipView.h.
Referenced by setTextBackgroundColor(), and textBackgroundColor().
m_textColor
QColor lmms::gui::ClipView::m_textColor private
Definition at line 216 of file ClipView.h.
Referenced by ClipView(), setTextColor(), and textColor().
m_textShadowColor
QColor lmms::gui::ClipView::m_textShadowColor private
Definition at line 218 of file ClipView.h.
Referenced by ClipView(), setTextShadowColor(), and textShadowColor().
m_trackView
TrackView* lmms::gui::ClipView::m_trackView protected
Definition at line 148 of file ClipView.h.
Referenced by ClipView(), ~ClipView(), close(), createClipDataFiles(), draggedClipPos(), dropEvent(), fixedClips(), getTrackView(), knifeMarkerPos(), lmms::gui::AutomationClipView::mouseDoubleClickEvent(), lmms::gui::MidiClipView::mouseDoubleClickEvent(), lmms::gui::PatternClipView::mouseDoubleClickEvent(), lmms::gui::SampleClipView::mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), pixelsPerBar(), remove(), setInitialOffsets(), updateCursor(), updateLength(), and updatePosition().
s_textFloat
TextFloat * lmms::gui::ClipView::s_textFloat = nullptr static private
A pointer for that text bubble used when moving segments, etc.
In a number of situations, LMMS displays a floating text bubble beside the cursor as you move or resize elements of a track about. This pointer keeps track of it, as you only ever need one at a time.
Definition at line 202 of file ClipView.h.
Referenced by ClipView(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
Property Documentation
gradient
bool lmms::gui::ClipView::gradient read write
Definition at line 63 of file ClipView.h.
Referenced by gradient(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), and lmms::gui::SampleClipView::paintEvent().
markerColor
QColor lmms::gui::ClipView::markerColor read write
Definition at line 64 of file ClipView.h.
Referenced by markerColor(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), and lmms::gui::SampleClipView::paintEvent().
mutedBackgroundColor
QColor lmms::gui::ClipView::mutedBackgroundColor read write
Definition at line 57 of file ClipView.h.
Referenced by getColorForDisplay(), mutedBackgroundColor(), and lmms::gui::MidiClipView::paintEvent().
mutedColor
QColor lmms::gui::ClipView::mutedColor read write
Definition at line 56 of file ClipView.h.
Referenced by mutedColor(), and lmms::gui::AutomationClipView::paintEvent().
patternClipBackground
QColor lmms::gui::ClipView::patternClipBackground read write
Definition at line 62 of file ClipView.h.
Referenced by lmms::gui::MidiClipView::paintEvent(), and patternClipBackground().
selectedColor
QColor lmms::gui::ClipView::selectedColor read write
Definition at line 58 of file ClipView.h.
Referenced by getColorForDisplay(), and selectedColor().
textBackgroundColor
QColor lmms::gui::ClipView::textBackgroundColor read write
Definition at line 60 of file ClipView.h.
Referenced by paintTextLabel(), and textBackgroundColor().
textColor
QColor lmms::gui::ClipView::textColor read write
Definition at line 59 of file ClipView.h.
Referenced by paintTextLabel(), and textColor().
textShadowColor
QColor lmms::gui::ClipView::textShadowColor read write
Definition at line 61 of file ClipView.h.
Referenced by paintTextLabel(), and textShadowColor().
The documentation for this class was generated from the following files:
include/ClipView.h
src/gui/clips/ClipView.cpp