LMMS: lmms::gui::EffectView Class Reference
lmms::gui::EffectView Class Reference
#include <EffectView.h>
Public Slots
void closeEffects ()
void deletePlugin ()
void editControls ()
void moveDown ()
void moveUp ()
Signals
void deletedPlugin (EffectView *view)
void movedDown (EffectView *view)
void movedUp (EffectView *view)
Public Member Functions
EffectView (Effect *_model, QWidget *_parent)
~EffectView () override
Effect * effect ()
const Effect * effect () const
void mouseMoveEvent (QMouseEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
Public Member Functions inherited from lmms::gui::PluginView
PluginView (Plugin *_plugin, QWidget *_parent)
virtual bool isResizable () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Static Public Attributes
static constexpr int DEFAULT_HEIGHT = 60
static constexpr int DEFAULT_WIDTH = 215
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *_me) override
void modelChanged () override
void paintEvent (QPaintEvent *_pe) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Attributes
TempoSyncKnob * m_autoQuit
QPixmap m_bg
LedCheckBox * m_bypass
EffectControlDialog * m_controlView
bool m_dragging
QGraphicsOpacityEffect * m_opacityEffect
QMdiSubWindow * m_subWindow
Knob * m_wetDry
Detailed Description
Definition at line 48 of file EffectView.h.
Constructor & Destructor Documentation
EffectView()
lmms::gui::EffectView::EffectView (Effect * _model, QWidget * _parent)
Definition at line 48 of file EffectView.cpp.
References lmms::gui::PluginView::PluginView(), lmms::gui::MainWindow::addWindowedWidget(), lmms::gui::adjustedToPixelSize(), lmms::gui::Bright26, closeEffects(), lmms::Effect::controls(), lmms::EffectControls::createView(), DEFAULT_FONT_SIZE, DEFAULT_HEIGHT, DEFAULT_WIDTH, editControls(), effect(), lmms::gui::getGUI(), lmms::gui::LedCheckBox::Green, lmms::gui::Knob::LegacyFixedFontSize, m_autoQuit, m_bg, m_bypass, m_controlView, m_dragging, m_opacityEffect, m_subWindow, m_wetDry, lmms::gui::GuiApplication::mainWindow(), lmms::gui::LedCheckBox::Red, and lmms::gui::ModelView::setModel().
Referenced by deletedPlugin(), movedDown(), and movedUp().
~EffectView()
lmms::gui::EffectView::~EffectView () override
Definition at line 125 of file EffectView.cpp.
References m_subWindow.
Member Function Documentation
closeEffects
void lmms::gui::EffectView::closeEffects () slot
Definition at line 177 of file EffectView.cpp.
References lmms::Effect::controls(), effect(), m_subWindow, and lmms::EffectControls::setViewVisible().
Referenced by EffectView().
contextMenuEvent()
void lmms::gui::EffectView::contextMenuEvent (QContextMenuEvent * _me) override protected
Definition at line 188 of file EffectView.cpp.
References deletePlugin(), lmms::embed::getIconPixmap(), lmms::gui::ModelView::model(), moveDown(), and moveUp().
deletedPlugin
void lmms::gui::EffectView::deletedPlugin (EffectView * view) signal
References EffectView().
Referenced by deletePlugin(), and lmms::gui::EffectRackView::update().
deletePlugin
void lmms::gui::EffectView::deletePlugin () slot
Definition at line 169 of file EffectView.cpp.
References deletedPlugin().
Referenced by contextMenuEvent().
editControls
void lmms::gui::EffectView::editControls () slot
Definition at line 133 of file EffectView.cpp.
References lmms::Effect::controls(), effect(), m_subWindow, and lmms::EffectControls::setViewVisible().
Referenced by EffectView().
effect() [1/2]
Effect * lmms::gui::EffectView::effect () inline
Definition at line 55 of file EffectView.h.
References lmms::gui::ModelView::castModel().
Referenced by EffectView(), closeEffects(), lmms::gui::EffectRackView::deletePlugin(), editControls(), modelChanged(), and lmms::gui::EffectRackView::moveUp().
effect() [2/2]
const Effect * lmms::gui::EffectView::effect () const inline
Definition at line 59 of file EffectView.h.
References lmms::gui::ModelView::castModel().
modelChanged()
void lmms::gui::EffectView::modelChanged () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 266 of file EffectView.cpp.
References effect(), m_autoQuit, m_bypass, and m_wetDry.
mouseMoveEvent()
void lmms::gui::EffectView::mouseMoveEvent (QMouseEvent * event) override
Definition at line 231 of file EffectView.cpp.
References DEFAULT_HEIGHT, m_dragging, moveDown(), and moveUp().
mousePressEvent()
void lmms::gui::EffectView::mousePressEvent (QMouseEvent * event) override
Definition at line 208 of file EffectView.cpp.
References m_dragging, and m_opacityEffect.
mouseReleaseEvent()
void lmms::gui::EffectView::mouseReleaseEvent (QMouseEvent * event) override
Definition at line 220 of file EffectView.cpp.
References m_dragging, and m_opacityEffect.
movedDown
void lmms::gui::EffectView::movedDown (EffectView * view) signal
References EffectView().
Referenced by moveDown(), and lmms::gui::EffectRackView::update().
moveDown
void lmms::gui::EffectView::moveDown () slot
Definition at line 162 of file EffectView.cpp.
References movedDown().
Referenced by contextMenuEvent(), mouseMoveEvent(), and lmms::gui::EffectRackView::update().
movedUp
void lmms::gui::EffectView::movedUp (EffectView * view) signal
References EffectView().
Referenced by moveUp(), and lmms::gui::EffectRackView::update().
moveUp
void lmms::gui::EffectView::moveUp () slot
Definition at line 154 of file EffectView.cpp.
References movedUp().
Referenced by contextMenuEvent(), mouseMoveEvent(), and lmms::gui::EffectRackView::update().
paintEvent()
void lmms::gui::EffectView::paintEvent (QPaintEvent * _pe) override protected
Definition at line 246 of file EffectView.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, m_bg, and lmms::gui::ModelView::model().
Member Data Documentation
DEFAULT_HEIGHT
int lmms::gui::EffectView::DEFAULT_HEIGHT = 60 static constexpr
Definition at line 65 of file EffectView.h.
Referenced by EffectView(), and mouseMoveEvent().
DEFAULT_WIDTH
int lmms::gui::EffectView::DEFAULT_WIDTH = 215 static constexpr
Definition at line 64 of file EffectView.h.
Referenced by EffectView(), and lmms::gui::EffectRackView::update().
m_autoQuit
TempoSyncKnob* lmms::gui::EffectView::m_autoQuit private
Definition at line 94 of file EffectView.h.
Referenced by EffectView(), and modelChanged().
m_bg
QPixmap lmms::gui::EffectView::m_bg private
Definition at line 91 of file EffectView.h.
Referenced by EffectView(), and paintEvent().
m_bypass
LedCheckBox* lmms::gui::EffectView::m_bypass private
Definition at line 92 of file EffectView.h.
Referenced by EffectView(), and modelChanged().
m_controlView
EffectControlDialog* lmms::gui::EffectView::m_controlView private
Definition at line 96 of file EffectView.h.
Referenced by EffectView().
m_dragging
bool lmms::gui::EffectView::m_dragging private
Definition at line 98 of file EffectView.h.
Referenced by EffectView(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_opacityEffect
QGraphicsOpacityEffect* lmms::gui::EffectView::m_opacityEffect private
Definition at line 99 of file EffectView.h.
Referenced by EffectView(), mousePressEvent(), and mouseReleaseEvent().
m_subWindow
QMdiSubWindow* lmms::gui::EffectView::m_subWindow private
Definition at line 95 of file EffectView.h.
Referenced by EffectView(), ~EffectView(), closeEffects(), and editControls().
m_wetDry
Knob* lmms::gui::EffectView::m_wetDry private
Definition at line 93 of file EffectView.h.
Referenced by EffectView(), and modelChanged().
The documentation for this class was generated from the following files:
include/EffectView.h
src/gui/EffectView.cpp