var searchData=
[
  ['scale_20points_0',['Scale Points',['../group__lilv__scalepoint.html',1,'']]],
  ['serd_20c_20api_1',['Serd C API',['../group__serd.html',1,'']]],
  ['server_2',['The API for starting and controlling a JACK server',['../group__ControlAPI.html',1,'']]],
  ['server_20operation_3',['Controlling &amp;amp; querying JACK server operation',['../group__ServerClientControl.html',1,'']]],
  ['session_20api_20for_20clients_4',['Session API for clients.',['../group__SessionClientFunctions.html',1,'']]],
  ['session_20manager_5',['API for a session manager.',['../group__JackSessionManagerAPI.html',1,'']]],
  ['setting_20client_20callbacks_6',['Setting Client Callbacks',['../group__ClientCallbacks.html',1,'']]],
  ['setup_7',['Setup',['../group__setup.html',1,'']]],
  ['size_8',['Buffer Size',['../group__buf-size.html',1,'']]],
  ['sord_9',['Sord',['../group__sord.html',1,'']]],
  ['speaker_20arrangements_10',['Speaker Arrangements',['../group__speakerArrangements.html',1,'']]],
  ['sratom_11',['Sratom',['../group__sratom.html',1,'']]],
  ['starting_20and_20controlling_20a_20jack_20server_12',['The API for starting and controlling a JACK server',['../group__ControlAPI.html',1,'']]],
  ['state_13',['State',['../group__lilv__state.html',1,'Plugin State'],['../group__state.html',1,'State']]],
  ['state_20hints_14',['State Hints',['../group__StateHints.html',1,'']]],
  ['status_15',['Status',['../group__status.html',1,'']]],
  ['stream_20decoder_20interface_16',['FLAC/stream_decoder.h: stream decoder interface',['../group__flac__stream__decoder.html',1,'']]],
  ['stream_20encoder_20interface_17',['FLAC/stream_encoder.h: stream encoder interface',['../group__flac__stream__encoder.html',1,'']]],
  ['stream_5fdecoder_20h_3a_20stream_20decoder_20interface_18',['FLAC/stream_decoder.h: stream decoder interface',['../group__flac__stream__decoder.html',1,'']]],
  ['stream_5fencoder_20h_3a_20stream_20encoder_20interface_19',['FLAC/stream_encoder.h: stream encoder interface',['../group__flac__stream__encoder.html',1,'']]],
  ['streams_20',['Byte Streams',['../group__serd__streams.html',1,'']]],
  ['string_20print_20functions_21',['String print functions',['../group__StringPrintFunctions.html',1,'']]],
  ['string_20utilities_22',['String Utilities',['../group__serd__string.html',1,'']]],
  ['structs_23',['Base Plugin Structs',['../group__BasePluginStructs.html',1,'']]],
  ['structures_24',['FLAC/callback.h: I/O callback structures',['../group__flac__callbacks.html',1,'']]],
  ['stub_25',['Stub',['../group__stub.html',1,'']]],
  ['subcategories_26',['Plug-in Type used for subCategories',['../group__plugType.html',1,'']]],
  ['support_20for_20newer_20older_20versions_20of_20jack_27',['Managing support for newer/older versions of JACK',['../group__WeakLinkage.html',1,'']]],
  ['symbols_28',['FLAC/export.h: export symbols',['../group__flac__export.html',1,'']]]
];
