var searchData=
[
  ['c_20api_0',['C API',['../group__flac.html',1,'FLAC C API'],['../group__lilv.html',1,'Lilv C API'],['../group__pugl.html',1,'Pugl C API'],['../group__serd.html',1,'Serd C API']]],
  ['callback_20api_1',['The non-callback API',['../group__NonCallbackAPI.html',1,'']]],
  ['callback_20h_3a_20i_20o_20callback_20structures_2',['FLAC/callback.h: I/O callback structures',['../group__flac__callbacks.html',1,'']]],
  ['callback_20structures_3',['FLAC/callback.h: I/O callback structures',['../group__flac__callbacks.html',1,'']]],
  ['callbacks_4',['Setting Client Callbacks',['../group__ClientCallbacks.html',1,'']]],
  ['carla_20backend_20api_5',['Carla Backend API',['../group__CarlaBackendAPI.html',1,'']]],
  ['carla_20engine_20api_6',['Carla Engine API',['../group__CarlaEngineAPI.html',1,'']]],
  ['carla_20host_20api_7',['Carla Host API',['../group__CarlaHostAPI.html',1,'']]],
  ['carla_20native_20api_8',['Carla Native API',['../group__CarlaNativeAPI.html',1,'']]],
  ['carla_20plugin_20api_9',['Carla Plugin API',['../group__CarlaPluginAPI.html',1,'']]],
  ['carla_20ui_20bridge_20api_10',['Carla UI Bridge API',['../group__CarlaBridgeUIAPI.html',1,'']]],
  ['carla_20utils_20api_11',['Carla Utils API',['../group__CarlaUtilsAPI.html',1,'']]],
  ['classes_12',['Classes',['../group__MainClasses.html',1,'Main Classes'],['../group__lilv__class.html',1,'Plugin Classes']]],
  ['classes_13',['Plugin helper classes',['../group__PluginHelperClasses.html',1,'']]],
  ['client_20callbacks_14',['Setting Client Callbacks',['../group__ClientCallbacks.html',1,'']]],
  ['client_20threads_15',['Creating and managing client threads',['../group__ClientThreads.html',1,'']]],
  ['clients_16',['clients',['../group__ClientFunctions.html',1,'Creating &amp; manipulating clients'],['../group__SessionClientFunctions.html',1,'Session API for clients.']]],
  ['collections_17',['Collections',['../group__lilv__collections.html',1,'']]],
  ['completion_20condition_20function_20objects_18',['Completion Condition Function Objects',['../group__completion__condition.html',1,'']]],
  ['components_19',['FLAC/format.h: format components',['../group__flac__format.html',1,'']]],
  ['condition_20function_20objects_20',['Completion Condition Function Objects',['../group__completion__condition.html',1,'']]],
  ['control_21',['Transport and Timebase control',['../group__TransportControl.html',1,'']]],
  ['controlling_20a_20jack_20server_22',['The API for starting and controlling a JACK server',['../group__ControlAPI.html',1,'']]],
  ['controlling_20error_20information_20output_23',['Controlling error/information output',['../group__ErrorOutput.html',1,'']]],
  ['controlling_20querying_20jack_20server_20operation_24',['Controlling &amp;amp; querying JACK server operation',['../group__ServerClientControl.html',1,'']]],
  ['core_25',['LV2 Core',['../group__lv2core.html',1,'']]],
  ['creating_20and_20managing_20client_20threads_26',['Creating and managing client threads',['../group__ClientThreads.html',1,'']]],
  ['creating_20manipulating_20clients_27',['Creating &amp;amp; manipulating clients',['../group__ClientFunctions.html',1,'']]],
  ['creating_20manipulating_20ports_28',['Creating &amp;amp; manipulating ports',['../group__PortFunctions.html',1,'']]],
  ['custom_20data_20keys_29',['Custom Data Keys',['../group__CustomDataKeys.html',1,'']]],
  ['custom_20data_20types_30',['Custom Data Types',['../group__CustomDataTypes.html',1,'']]]
];
