LMMS: lmms::Plugin::Descriptor::SubPluginFeatures::Key Struct Reference
lmms::Plugin::Descriptor::SubPluginFeatures::Key Struct Reference
Key reference a Plugin::Descriptor, and, if the plugin has sub plugins, also reference its sub plugin (using the attributes).
#include <Plugin.h>
Public Types
using AttributeMap = QMap<QString, QString>
Public Member Functions
Key (const Plugin::Descriptor *desc=nullptr, const QString &name=QString(), const AttributeMap &am=AttributeMap())
Key (const QDomElement &key)
QString additionalFileExtensions () const
QString description () const
QString displayName () const
bool isValid () const
const PixmapLoader * logo () const
QDomElement saveXML (QDomDocument &doc) const
Public Attributes
AttributeMap attributes
Attributes that make up the key and identify the sub plugin.
const Plugin::Descriptor * desc
Key to subplugin: reference to parent descriptor Key to plugin: reference to its descriptor.
QString name
Descriptive name like "Calf Phaser".
Detailed Description
Key reference a Plugin::Descriptor, and, if the plugin has sub plugins, also reference its sub plugin (using the attributes).
When keys are saved, those attributes are written to XML in order to find the right sub plugin when realoading.
Note
Any data that is not required to reference the right Plugin or sub plugin should not be here (but rather in SubPluginFeatures, which are like values in a key-value map).
Definition at line 135 of file Plugin.h.
Member Typedef Documentation
AttributeMap
using lmms::Plugin::Descriptor::SubPluginFeatures::Key::AttributeMap = QMap<QString, QString>
Definition at line 137 of file Plugin.h.
Constructor & Destructor Documentation
Key() [1/2]
lmms::Plugin::Descriptor::SubPluginFeatures::Key::Key (const Plugin::Descriptor * desc = nullptr, const QString & name = QString(), const AttributeMap & am = AttributeMap()) inline
Definition at line 139 of file Plugin.h.
References attributes, desc, and name.
Key() [2/2]
lmms::Plugin::Descriptor::SubPluginFeatures::Key::Key (const QDomElement & key)
Definition at line 276 of file Plugin.cpp.
References attributes, desc, i, lmms::Plugin::key(), and name.
Member Function Documentation
additionalFileExtensions()
QString lmms::Plugin::Descriptor::SubPluginFeatures::Key::additionalFileExtensions () const
Definition at line 117 of file Plugin.cpp.
References desc, and isValid().
description()
QString lmms::Plugin::Descriptor::SubPluginFeatures::Key::description () const
Definition at line 155 of file Plugin.cpp.
References desc, isValid(), and lmms::use_this_or().
Referenced by lmms::gui::PluginDescWidget::PluginDescWidget().
displayName()
QString lmms::Plugin::Descriptor::SubPluginFeatures::Key::displayName () const
Definition at line 130 of file Plugin.cpp.
References desc, isValid(), and lmms::use_this_or().
isValid()
bool lmms::Plugin::Descriptor::SubPluginFeatures::Key::isValid () const inline
Definition at line 154 of file Plugin.h.
References desc.
Referenced by additionalFileExtensions(), description(), lmms::gui::InstrumentTrackView::determinePixmap(), displayName(), and logo().
logo()
const PixmapLoader * lmms::Plugin::Descriptor::SubPluginFeatures::Key::logo () const
Definition at line 144 of file Plugin.cpp.
References desc, isValid(), and lmms::use_this_or().
Referenced by lmms::gui::InstrumentTrackView::determinePixmap().
saveXML()
QDomElement lmms::Plugin::Descriptor::SubPluginFeatures::Key::saveXML (QDomDocument & doc) const
Definition at line 293 of file Plugin.cpp.
References attributes.
Member Data Documentation
attributes
AttributeMap lmms::Plugin::Descriptor::SubPluginFeatures::Key::attributes
Attributes that make up the key and identify the sub plugin.
They are being loaded and saved
Definition at line 170 of file Plugin.h.
Referenced by Key(), Key(), and saveXML().
desc
const Plugin::Descriptor* lmms::Plugin::Descriptor::SubPluginFeatures::Key::desc
Key to subplugin: reference to parent descriptor Key to plugin: reference to its descriptor.
Definition at line 161 of file Plugin.h.
Referenced by Key(), Key(), lmms::gui::PluginDescWidget::PluginDescWidget(), additionalFileExtensions(), description(), displayName(), lmms::Plugin::instantiateWithKey(), isValid(), and logo().
name
QString lmms::Plugin::Descriptor::SubPluginFeatures::Key::name
Descriptive name like "Calf Phaser".
Not required for key lookup and not saved only used sometimes to temporary store descriptive names
Todo
This is a bug, there should be a function in SubPluginFeatures (to get the name) instead
Definition at line 167 of file Plugin.h.
Referenced by Key(), and Key().
The documentation for this struct was generated from the following files:
include/Plugin.h
src/core/Plugin.cpp