LMMS: lmms::gui::TrackGrip Class Reference
lmms::gui::TrackGrip Class Reference
#include <TrackGrip.h>
Signals
void grabbed ()
void released ()
Public Member Functions
TrackGrip (Track *track, QWidget *parent=0)
~TrackGrip () override=default
Protected Member Functions
void mousePressEvent (QMouseEvent *) override
void mouseReleaseEvent (QMouseEvent *) override
void paintEvent (QPaintEvent *) override
Private Attributes
bool m_isGrabbed = false
Track * m_track = nullptr
Static Private Attributes
static QPixmap * s_grabbedPixmap = nullptr
static QPixmap * s_releasedPixmap = nullptr
Detailed Description
Definition at line 41 of file TrackGrip.h.
Constructor & Destructor Documentation
TrackGrip()
lmms::gui::TrackGrip::TrackGrip (Track * track, QWidget * parent = 0)
Definition at line 43 of file TrackGrip.cpp.
References lmms::gui::c_margin, lmms::embed::getIconPixmap(), m_track, s_grabbedPixmap, and s_releasedPixmap.
~TrackGrip()
lmms::gui::TrackGrip::~TrackGrip () override default
Member Function Documentation
grabbed
void lmms::gui::TrackGrip::grabbed () signal
Referenced by lmms::gui::TrackView::TrackView(), and mousePressEvent().
mousePressEvent()
void lmms::gui::TrackGrip::mousePressEvent (QMouseEvent * m) override protected
Definition at line 64 of file TrackGrip.cpp.
References grabbed(), and m_isGrabbed.
mouseReleaseEvent()
void lmms::gui::TrackGrip::mouseReleaseEvent (QMouseEvent * m) override protected
Definition at line 76 of file TrackGrip.cpp.
References m_isGrabbed, and released().
paintEvent()
void lmms::gui::TrackGrip::paintEvent (QPaintEvent *) override protected
Definition at line 88 of file TrackGrip.cpp.
References lmms::gui::c_margin, m_isGrabbed, m_track, s_grabbedPixmap, and s_releasedPixmap.
released
void lmms::gui::TrackGrip::released () signal
Referenced by lmms::gui::TrackView::TrackView(), and mouseReleaseEvent().
Member Data Documentation
m_isGrabbed
bool lmms::gui::TrackGrip::m_isGrabbed = false private
Definition at line 59 of file TrackGrip.h.
Referenced by mousePressEvent(), mouseReleaseEvent(), and paintEvent().
m_track
Track* lmms::gui::TrackGrip::m_track = nullptr private
Definition at line 58 of file TrackGrip.h.
Referenced by TrackGrip(), and paintEvent().
s_grabbedPixmap
QPixmap * lmms::gui::TrackGrip::s_grabbedPixmap = nullptr static private
Definition at line 60 of file TrackGrip.h.
Referenced by TrackGrip(), and paintEvent().
s_releasedPixmap
QPixmap * lmms::gui::TrackGrip::s_releasedPixmap = nullptr static private
Definition at line 61 of file TrackGrip.h.
Referenced by TrackGrip(), and paintEvent().
The documentation for this class was generated from the following files:
include/TrackGrip.h
src/gui/tracks/TrackGrip.cpp