LMMS: Jack::JackMetadata Class Reference
Jack::JackMetadata Class Reference
Metadata base.
#include <JackMetadata.h>
Public Member Functions
JackMetadata (bool isEngine)
~JackMetadata ()
void FreeDescription (jack_description_t *desc, int free_actual_description_too)
int GetAllDescriptions (jack_description_t **descs)
int GetAllProperties (jack_description_t **descriptions)
int GetDescription (jack_uuid_t subject, jack_description_t *desc)
int GetProperties (jack_uuid_t subject, jack_description_t *desc)
int GetProperty (jack_uuid_t subject, const char *key, char **value, char **type)
int RemoveAllProperties (JackClient *client)
int RemoveProperties (JackClient *client, jack_uuid_t subject)
int RemoveProperty (JackClient *client, jack_uuid_t subject, const char *key)
int SetProperty (JackClient *client, jack_uuid_t subject, const char *key, const char *value, const char *type)
Private Member Functions
int PropertyChangeNotify (JackClient *client, jack_uuid_t subject, const char *key, jack_property_change_t change)
int PropertyInit ()
Detailed Description
Metadata base.
Definition at line 84 of file JackMetadata.h.
Constructor & Destructor Documentation
JackMetadata()
Jack::JackMetadata::JackMetadata (bool isEngine)
Definition at line 47 of file JackMetadata.cpp.
References PropertyInit().
~JackMetadata()
Jack::JackMetadata::~JackMetadata ()
Definition at line 55 of file JackMetadata.cpp.
References Jack::JackTools::GetUID(), and PATH_MAX.
Member Function Documentation
FreeDescription()
void Jack::JackMetadata::FreeDescription (jack_description_t * desc, int free_actual_description_too)
Definition at line 657 of file JackMetadata.cpp.
References jack_property_t::data, jack_property_t::key, jack_description_t::properties, jack_description_t::property_cnt, and jack_property_t::type.
Referenced by jack_free_description().
GetAllDescriptions()
int Jack::JackMetadata::GetAllDescriptions (jack_description_t ** descs)
Definition at line 652 of file JackMetadata.cpp.
GetAllProperties()
int Jack::JackMetadata::GetAllProperties (jack_description_t ** descriptions)
Definition at line 509 of file JackMetadata.cpp.
References jack_property_t::data, jack_error, jack_uuid_compare(), jack_uuid_copy(), JACK_UUID_EMPTY_INITIALIZER, jack_uuid_parse(), JACK_UUID_STRING_SIZE, jack_property_t::key, jack_description_t::properties, jack_description_t::property_cnt, jack_description_t::property_size, PropertyInit(), and jack_property_t::type.
Referenced by jack_get_all_properties().
GetDescription()
int Jack::JackMetadata::GetDescription (jack_uuid_t subject, jack_description_t * desc)
Definition at line 647 of file JackMetadata.cpp.
GetProperties()
int Jack::JackMetadata::GetProperties (jack_uuid_t subject, jack_description_t * desc)
Definition at line 378 of file JackMetadata.cpp.
References jack_property_t::data, jack_error, jack_uuid_copy(), JACK_UUID_STRING_SIZE, jack_uuid_unparse(), jack_property_t::key, jack_description_t::properties, jack_description_t::property_cnt, PropertyInit(), jack_description_t::subject, and jack_property_t::type.
Referenced by jack_get_properties().
GetProperty()
int Jack::JackMetadata::GetProperty (jack_uuid_t subject, const char * key, char ** value, char ** type)
Definition at line 293 of file JackMetadata.cpp.
References jack_error, JACK_UUID_STRING_SIZE, jack_uuid_unparse(), and PropertyInit().
Referenced by jack_get_property().
PropertyChangeNotify()
int Jack::JackMetadata::PropertyChangeNotify (JackClient * client, jack_uuid_t subject, const char * key, jack_property_change_t change) private
Definition at line 181 of file JackMetadata.cpp.
References client().
Referenced by RemoveAllProperties(), RemoveProperties(), RemoveProperty(), and SetProperty().
PropertyInit()
int Jack::JackMetadata::PropertyInit () private
Definition at line 91 of file JackMetadata.cpp.
References Jack::JackTools::GetUID(), jack_error, jack_server_dir, and PATH_MAX.
Referenced by JackMetadata(), GetAllProperties(), GetProperties(), GetProperty(), RemoveAllProperties(), RemoveProperties(), RemoveProperty(), and SetProperty().
RemoveAllProperties()
int Jack::JackMetadata::RemoveAllProperties (JackClient * client)
Definition at line 792 of file JackMetadata.cpp.
References client(), jack_error, JACK_UUID_EMPTY_INITIALIZER, PropertyChangeNotify(), PropertyDeleted, and PropertyInit().
Referenced by jack_remove_all_properties().
RemoveProperties()
int Jack::JackMetadata::RemoveProperties (JackClient * client, jack_uuid_t subject)
Definition at line 709 of file JackMetadata.cpp.
References client(), jack_error, JACK_UUID_STRING_SIZE, jack_uuid_unparse(), PropertyChangeNotify(), PropertyDeleted, and PropertyInit().
Referenced by jack_remove_properties().
RemoveProperty()
int Jack::JackMetadata::RemoveProperty (JackClient * client, jack_uuid_t subject, const char * key)
Definition at line 676 of file JackMetadata.cpp.
References client(), jack_error, PropertyChangeNotify(), PropertyDeleted, and PropertyInit().
Referenced by jack_remove_property().
SetProperty()
int Jack::JackMetadata::SetProperty (JackClient * client, jack_uuid_t subject, const char * key, const char * value, const char * type)
Definition at line 211 of file JackMetadata.cpp.
References client(), jack_error, JACK_UUID_STRING_SIZE, jack_uuid_unparse(), PropertyChanged, PropertyChangeNotify(), PropertyCreated, and PropertyInit().
Referenced by jack_set_property().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackMetadata.h
src/3rdparty/jack2/common/JackMetadata.cpp