LMMS: lmms::gui::AutomatableButton Class Reference
lmms::gui::AutomatableButton Class Reference
#include <AutomatableButton.h>
Public Slots
virtual void setChecked (bool _on)
virtual void toggle ()
virtual void update ()
Public Member Functions
AutomatableButton (QWidget *_parent, const QString &_name=QString())
~AutomatableButton () override
void modelChanged () override
void setCheckable (bool _on)
Public Member Functions inherited from lmms::gui::TypedModelView< BoolModel >
TypedModelView (Model *model, QWidget *_this)
BoolModel * model ()
const BoolModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *_me) override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Attributes
AutomatableButtonGroup * m_group
Friends
class AutomatableButtonGroup
Additional Inherited Members
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 38 of file AutomatableButton.h.
Constructor & Destructor Documentation
AutomatableButton()
lmms::gui::AutomatableButton::AutomatableButton (QWidget * _parent, const QString & _name = QString())
Definition at line 38 of file AutomatableButton.cpp.
References lmms::gui::ModelView::doConnections(), and m_group.
Referenced by lmms::gui::LedCheckBox::LedCheckBox(), and lmms::gui::PixmapButton::PixmapButton().
~AutomatableButton()
lmms::gui::AutomatableButton::~AutomatableButton () override
Definition at line 52 of file AutomatableButton.cpp.
References m_group.
Member Function Documentation
contextMenuEvent()
void lmms::gui::AutomatableButton::contextMenuEvent (QContextMenuEvent * _me) override protected
Definition at line 86 of file AutomatableButton.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), m_group, lmms::gui::TypedModelView< BoolModel >::model(), and mouseReleaseEvent().
modelChanged()
void lmms::gui::AutomatableButton::modelChanged () override virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 63 of file AutomatableButton.cpp.
References lmms::gui::TypedModelView< BoolModel >::model(), and lmms::gui::AutomatableModelView::value().
mousePressEvent()
void lmms::gui::AutomatableButton::mousePressEvent (QMouseEvent * _me) override protected virtual
Reimplemented from lmms::gui::AutomatableModelView.
Reimplemented in lmms::gui::PixmapButton.
Definition at line 112 of file AutomatableButton.cpp.
References lmms::KBD_COPY_MODIFIER, m_group, lmms::gui::AutomatableModelView::mousePressEvent(), toggle(), and lmms::gui::ModelView::widget().
Referenced by lmms::gui::PixmapButton::mousePressEvent().
mouseReleaseEvent()
void lmms::gui::AutomatableButton::mouseReleaseEvent (QMouseEvent * _me) override protected
Definition at line 149 of file AutomatableButton.cpp.
Referenced by contextMenuEvent(), and lmms::gui::PixmapButton::mouseReleaseEvent().
setCheckable()
void lmms::gui::AutomatableButton::setCheckable (bool _on) inline
Definition at line 46 of file AutomatableButton.h.
References lmms::gui::TypedModelView< BoolModel >::model().
Referenced by lmms::gui::AutomatableButtonGroup::addButton(), and lmms::gui::LedCheckBox::initUi().
setChecked
virtual void lmms::gui::AutomatableButton::setChecked (bool _on) inline virtual slot
Definition at line 58 of file AutomatableButton.h.
References lmms::gui::TypedModelView< BoolModel >::model().
toggle
void lmms::gui::AutomatableButton::toggle () virtual slot
Definition at line 160 of file AutomatableButton.cpp.
References m_group, lmms::gui::TypedModelView< BoolModel >::model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Referenced by mousePressEvent().
update
void lmms::gui::AutomatableButton::update () virtual slot
Definition at line 74 of file AutomatableButton.cpp.
References lmms::gui::TypedModelView< BoolModel >::model(), and lmms::gui::AutomatableModelView::value().
Referenced by lmms::gui::PixmapButton::mousePressEvent(), lmms::gui::PixmapButton::mouseReleaseEvent(), and lmms::gui::PixmapButton::setInactiveGraphic().
Friends And Related Symbol Documentation
AutomatableButtonGroup
friend class AutomatableButtonGroup friend
Definition at line 75 of file AutomatableButton.h.
References AutomatableButtonGroup.
Referenced by AutomatableButtonGroup.
Member Data Documentation
m_group
AutomatableButtonGroup* lmms::gui::AutomatableButton::m_group private
Definition at line 72 of file AutomatableButton.h.
Referenced by AutomatableButton(), ~AutomatableButton(), lmms::gui::AutomatableButtonGroup::addButton(), contextMenuEvent(), mousePressEvent(), lmms::gui::AutomatableButtonGroup::removeButton(), and toggle().
The documentation for this class was generated from the following files:
include/AutomatableButton.h
src/gui/widgets/AutomatableButton.cpp