LMMS: lmms::InstrumentTrack Class Reference
lmms::InstrumentTrack Class Reference
#include <InstrumentTrack.h>
Signals
void endNote ()
void instrumentChanged ()
void midiNoteOff (const lmms::Note &)
void midiNoteOn (const lmms::Note &)
void newNote ()
Signals inherited from lmms::Track
void clipAdded (lmms::Clip *)
void colorChanged ()
void dataChanged ()
void destroyedTrack ()
void nameChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
InstrumentTrack (TrackContainer *tc)
~InstrumentTrack () override
MidiEvent applyMasterKey (const MidiEvent &event)
AudioBusHandle * audioBusHandle ()
void autoAssignMidiDevice (bool)
Automatically assign a midi controller to this track, based on the midiautoassign setting.
float baseFreq () const
Return frequency assigned to the base key, based on currently selected keymap.
int baseNote () const
Return base key number, based on currently selected keymap or user selection.
IntModel * baseNoteModel ()
const IntModel * baseNoteModel () const
f_cnt_t beatLen (NotePlayHandle *_n) const
Clip * createClip (const TimePos &pos) override
gui::TrackView * createView (gui::TrackContainerView *tcv) override
void deleteNotePluginData (NotePlayHandle *_n)
int firstKey () const
Return first mapped key, based on currently selected keymap or user selection.
IntModel * firstKeyModel ()
Instrument * instrument ()
const Instrument * instrument () const
QString instrumentName () const
bool isArpeggioEnabled () const
bool isKeyMapped (int key) const
Check if there is a valid mapping for the given key and it is within defined of range.
bool isPreviewMode () const
bool isSustainPedalPressed () const
bool keyRangeImport () const
int lastKey () const
Return last mapped key, based on currently selected keymap or user selection.
IntModel * lastKeyModel ()
Instrument * loadInstrument (const QString &_instrument_name, const Plugin::Descriptor::SubPluginFeatures::Key *key=nullptr, bool keyFromDnd=false)
void loadTrackSpecificSettings (const QDomElement &_this) override
int masterKey (int _midi_key) const
Microtuner * microtuner ()
int midiPitch () const
int midiPitchRange () const
Returns current range for pitch bend in semitones.
MidiPort * midiPort ()
IntModel * mixerChannelModel ()
FloatModel * panningModel ()
Piano * pianoModel ()
FloatModel * pitchModel ()
IntModel * pitchRangeModel ()
bool play (const TimePos &_start, const fpp_t _frames, const f_cnt_t _frame_base, int _clip_num=-1) override
void playNote (NotePlayHandle *_n, SampleFrame *_working_buffer)
void processAudioBuffer (SampleFrame *_buf, const fpp_t _frames, NotePlayHandle *_n)
void processInEvent (const MidiEvent &event, const TimePos &time=TimePos(), f_cnt_t offset=0) override
void processOutEvent (const MidiEvent &event, const TimePos &time=TimePos(), f_cnt_t offset=0) override
void replaceInstrument (DataFile dataFile)
void saveTrackSpecificSettings (QDomDocument &doc, QDomElement &parent, bool presetMode) override
void setName (const QString &_new_name) override
void setPreviewMode (const bool)
void silenceAllNotes (bool removeIPH=false)
BoolModel * useMasterPitchModel ()
FloatModel * volumeModel ()
Public Member Functions inherited from lmms::Track
Track (Type type, TrackContainer *tc)
Create a new (empty) track object.
~Track () override
Destroy this track.
Clip * addClip (Clip *clip)
Add another Clip into this track.
Track * clone ()
Clone a track from this track.
auto color () const -> const std::optional< QColor > &
void createClipsForPattern (int pattern)
void deleteClips ()
Remove all Clips from this track.
QString displayName () const override
auto getClip (std::size_t clipNum) -> Clip *
Get a Clip by number.
int getClipNum (const Clip *clip)
Determine the given Clip's number in our array.
const clipVector & getClips () const
void getClipsInRange (clipVector &clipV, const TimePos &start, const TimePos &end)
Retrieve a list of clips that fall within a period.
int getHeight ()
BoolModel * getMutedModel ()
void insertBar (const TimePos &pos)
Move all the clips after a certain time later by one bar.
bool isMutedBeforeSolo () const
bar_t length () const
Return the length of the entire track in bars.
void loadPreset (const QDomElement &element)
void loadSettings (const QDomElement &element) override
void lock ()
virtual const QString & name () const
int numOfClips ()
Return the number of clips we contain.
void removeBar (const TimePos &pos)
Move all the clips after a certain time earlier by one bar.
void removeClip (Clip *clip)
Remove a given Clip from this track.
void savePreset (QDomDocument &doc, QDomElement &element)
void saveSettings (QDomDocument &doc, QDomElement &element) override
void setColor (const std::optional< QColor > &color)
void setHeight (int height)
void swapPositionOfClips (int clipNum1, int clipNum2)
Swap the position of two clips.
TrackContainer * trackContainer () const
bool tryLock ()
Type type () const
void unlock ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Public Member Functions inherited from lmms::MidiEventProcessor
MidiEventProcessor ()=default
virtual ~MidiEventProcessor ()=default
Static Public Member Functions
static void removeMidiPortNode (DataFile &dataFile)
Static Public Member Functions inherited from lmms::Track
static Track * create (const QDomElement &element, TrackContainer *tc)
Create a track inside TrackContainer from track type in a QDomElement and restore state from XML.
static Track * create (Type tt, TrackContainer *tc)
Create a track based on the given track type and container.
Protected Slots
void updateBaseNote ()
void updateMixerChannel ()
void updatePitch ()
void updatePitchRange ()
Protected Member Functions
QString getSavedInstrumentName (const QDomElement &thisElement) const
QString nodeName () const override
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Member Functions
mapPropertyFromModel (int, getVolume, setVolume, m_volumeModel)
void processCCEvent (int controller)
Private Attributes
InstrumentFunctionArpeggio m_arpeggio
AudioBusHandle m_audioBusHandle
IntModel m_baseNoteModel
The "A4" or "440 Hz" key (default 69).
IntModel m_firstKeyModel
First key the instrument reacts to.
bool m_hasAutoMidiDev
Instrument * m_instrument
IntModel m_lastKeyModel
Last key the instrument reacts to.
Microtuner m_microtuner
std::unique_ptr< BoolModel > m_midiCCEnable
std::unique_ptr< FloatModel > m_midiCCModel [MidiControllerCount]
QMutex m_midiNotesMutex
MidiPort m_midiPort
IntModel m_mixerChannelModel
NotePlayHandle * m_notes [NumKeys]
InstrumentFunctionNoteStacking m_noteStacking
FloatModel m_panningModel
Piano m_piano
FloatModel m_pitchModel
IntModel m_pitchRangeModel
bool m_previewMode
NotePlayHandleList m_processHandles
int m_runningMidiNotes [NumKeys]
bool m_silentBuffersProcessed
InstrumentSoundShaping m_soundShaping
NotePlayHandleList m_sustainedNotes
bool m_sustainPedalPressed
BoolModel m_useMasterPitchModel
FloatModel m_volumeModel
Static Private Attributes
static InstrumentTrack * s_autoAssignedTrack = nullptr
Friends
class gui::InstrumentTrackView
class gui::InstrumentTrackWindow
class gui::InstrumentTuningView
class gui::MidiCCRackView
class NotePlayHandle
Additional Inherited Members
Public Types inherited from lmms::Track
using clipVector = std::vector<Clip*>
enum class Type {
Instrument ,
Pattern ,
Sample ,
Event ,
Video ,
Automation ,
HiddenAutomation ,
Count
}
Public Slots inherited from lmms::Track
void setMutedBeforeSolo (const bool muted)
void toggleSolo ()
Invert the track's solo state.
Protected Attributes inherited from lmms::Track
BoolModel m_mutedModel
BoolModel m_soloModel
Detailed Description
Definition at line 61 of file InstrumentTrack.h.
Constructor & Destructor Documentation
InstrumentTrack()
lmms::InstrumentTrack::InstrumentTrack (TrackContainer * tc)
Definition at line 49 of file InstrumentTrack.cpp.
References lmms::MidiEventProcessor::MidiEventProcessor(), lmms::Track::Track(), autoAssignMidiDevice(), lmms::Model::dataChanged(), lmms::Track::dataChanged(), lmms::DefaultKey, lmms::DefaultPanning, lmms::DefaultVolume, i, m_arpeggio, m_audioBusHandle, m_baseNoteModel, m_firstKeyModel, m_hasAutoMidiDev, m_instrument, m_lastKeyModel, m_microtuner, m_midiCCEnable, m_midiCCModel, m_midiPort, m_mixerChannelModel, lmms::Track::m_mutedModel, m_notes, m_noteStacking, m_panningModel, m_piano, m_pitchModel, m_pitchRangeModel, m_previewMode, m_runningMidiNotes, m_silentBuffersProcessed, m_soundShaping, m_sustainPedalPressed, m_useMasterPitchModel, m_volumeModel, lmms::MaxPitchDefault, lmms::MaxVolume, lmms::MidiControllerCount, lmms::MinPitchDefault, lmms::MinVolume, lmms::Engine::mixer(), lmms::NumKeys, lmms::PanningLeft, lmms::PanningRight, processCCEvent(), setName(), updateBaseNote(), updateMixerChannel(), updatePitch(), and updatePitchRange().
Referenced by mapPropertyFromModel().
~InstrumentTrack()
lmms::InstrumentTrack::~InstrumentTrack () override
Definition at line 205 of file InstrumentTrack.cpp.
References autoAssignMidiDevice(), m_hasAutoMidiDev, m_instrument, s_autoAssignedTrack, and silenceAllNotes().
Member Function Documentation
applyMasterKey()
MidiEvent lmms::InstrumentTrack::applyMasterKey (const MidiEvent & event)
Definition at line 286 of file InstrumentTrack.cpp.
References lmms::MidiEvent::key(), masterKey(), lmms::MidiKeyPressure, lmms::MidiNoteOff, lmms::MidiNoteOn, lmms::MidiEvent::setKey(), and lmms::MidiEvent::type().
Referenced by mapPropertyFromModel(), and processOutEvent().
audioBusHandle()
AudioBusHandle * lmms::InstrumentTrack::audioBusHandle () inline
Definition at line 146 of file InstrumentTrack.h.
References m_audioBusHandle.
Referenced by lmms::InstrumentPlayHandle::InstrumentPlayHandle().
autoAssignMidiDevice()
void lmms::InstrumentTrack::autoAssignMidiDevice (bool assign)
Automatically assign a midi controller to this track, based on the midiautoassign setting.
Parameters
assign set to true to connect the midi device, set to false to disconnect
Definition at line 1083 of file InstrumentTrack.cpp.
References lmms::Engine::audioEngine(), lmms::ConfigManager::inst(), m_hasAutoMidiDev, m_midiPort, s_autoAssignedTrack, and lmms::ConfigManager::value().
Referenced by InstrumentTrack(), ~InstrumentTrack(), and saveTrackSpecificSettings().
baseFreq()
float lmms::InstrumentTrack::baseFreq () const
Return frequency assigned to the base key, based on currently selected keymap.
Returns
Frequency in Hz
Definition at line 191 of file InstrumentTrack.cpp.
References lmms::DefaultBaseFreq, lmms::Song::getKeymap(), lmms::Engine::getSong(), and m_microtuner.
baseNote()
int lmms::InstrumentTrack::baseNote () const
Return base key number, based on currently selected keymap or user selection.
Returns
Number ranging from 0 to NumKeys -1
Definition at line 173 of file InstrumentTrack.cpp.
References lmms::Song::getKeymap(), lmms::Engine::getSong(), keyRangeImport(), m_baseNoteModel, m_microtuner, and m_useMasterPitchModel.
Referenced by masterKey(), and lmms::NotePlayHandle::midiKey().
baseNoteModel() [1/2]
IntModel * lmms::InstrumentTrack::baseNoteModel () inline
Definition at line 161 of file InstrumentTrack.h.
References m_baseNoteModel.
baseNoteModel() [2/2]
const IntModel * lmms::InstrumentTrack::baseNoteModel () const inline
Definition at line 156 of file InstrumentTrack.h.
References m_baseNoteModel.
beatLen()
f_cnt_t lmms::InstrumentTrack::beatLen (NotePlayHandle * _n) const
Definition at line 555 of file InstrumentTrack.cpp.
References m_instrument, m_soundShaping, and NotePlayHandle.
createClip()
Clip * lmms::InstrumentTrack::createClip (const TimePos & pos) override virtual
Implements lmms::Track.
Definition at line 815 of file InstrumentTrack.cpp.
References pos.
createView()
gui::TrackView * lmms::InstrumentTrack::createView (gui::TrackContainerView * tcv) override virtual
Implements lmms::Track.
Definition at line 825 of file InstrumentTrack.cpp.
deleteNotePluginData()
void lmms::InstrumentTrack::deleteNotePluginData (NotePlayHandle * _n)
Definition at line 613 of file InstrumentTrack.cpp.
References m_instrument, and NotePlayHandle.
endNote
void lmms::InstrumentTrack::endNote () signal
Referenced by processOutEvent().
firstKey()
int lmms::InstrumentTrack::firstKey () const
Return first mapped key, based on currently selected keymap or user selection.
Returns
Number ranging from 0 to NumKeys -1
Definition at line 141 of file InstrumentTrack.cpp.
References lmms::Song::getKeymap(), lmms::Engine::getSong(), keyRangeImport(), m_firstKeyModel, and m_microtuner.
Referenced by isKeyMapped(), and processInEvent().
firstKeyModel()
IntModel * lmms::InstrumentTrack::firstKeyModel () inline
Definition at line 166 of file InstrumentTrack.h.
References m_firstKeyModel.
getSavedInstrumentName()
QString lmms::InstrumentTrack::getSavedInstrumentName (const QDomElement & thisElement) const protected
Definition at line 1042 of file InstrumentTrack.cpp.
Referenced by loadTrackSpecificSettings().
instrument() [1/2]
Instrument * lmms::InstrumentTrack::instrument () inline
Definition at line 98 of file InstrumentTrack.h.
References m_instrument.
instrument() [2/2]
const Instrument * lmms::InstrumentTrack::instrument () const inline
Definition at line 93 of file InstrumentTrack.h.
References m_instrument.
Referenced by lmms::gui::InstrumentTrackView::determinePixmap(), lmms::gui::FileBrowserTreeWidget::handleFile(), and processInEvent().
instrumentChanged
void lmms::InstrumentTrack::instrumentChanged () signal
Referenced by loadInstrument(), and loadTrackSpecificSettings().
instrumentName()
QString lmms::InstrumentTrack::instrumentName () const
Definition at line 601 of file InstrumentTrack.cpp.
References m_instrument.
isArpeggioEnabled()
bool lmms::InstrumentTrack::isArpeggioEnabled () const inline
Definition at line 193 of file InstrumentTrack.h.
References m_arpeggio.
Referenced by lmms::InstrumentFunctionNoteStacking::processNote().
isKeyMapped()
bool lmms::InstrumentTrack::isKeyMapped (int key) const
Check if there is a valid mapping for the given key and it is within defined of range.
Definition at line 126 of file InstrumentTrack.cpp.
References firstKey(), lmms::Song::getKeymap(), lmms::Engine::getSong(), lastKey(), and m_microtuner.
isPreviewMode()
bool lmms::InstrumentTrack::isPreviewMode () const inline
Definition at line 233 of file InstrumentTrack.h.
References m_previewMode.
isSustainPedalPressed()
bool lmms::InstrumentTrack::isSustainPedalPressed () const inline
Definition at line 80 of file InstrumentTrack.h.
References m_sustainPedalPressed.
Referenced by lmms::InstrumentSoundShaping::processAudioBuffer(), and processInEvent().
keyRangeImport()
bool lmms::InstrumentTrack::keyRangeImport () const
Definition at line 118 of file InstrumentTrack.cpp.
References m_microtuner.
Referenced by baseNote(), firstKey(), and lastKey().
lastKey()
int lmms::InstrumentTrack::lastKey () const
Return last mapped key, based on currently selected keymap or user selection.
Returns
Number ranging from 0 to NumKeys -1
Definition at line 157 of file InstrumentTrack.cpp.
References lmms::Song::getKeymap(), lmms::Engine::getSong(), keyRangeImport(), m_lastKeyModel, and m_microtuner.
Referenced by isKeyMapped(), and processInEvent().
lastKeyModel()
IntModel * lmms::InstrumentTrack::lastKeyModel () inline
Definition at line 171 of file InstrumentTrack.h.
References m_lastKeyModel.
loadInstrument()
Instrument * lmms::InstrumentTrack::loadInstrument (const QString & _instrument_name, const Plugin::Descriptor::SubPluginFeatures::Key * key = nullptr, bool keyFromDnd = false)
Definition at line 1055 of file InstrumentTrack.cpp.
References lmms::Instrument::instantiate(), instrumentChanged(), lmms::Track::lock(), m_instrument, setName(), silenceAllNotes(), and lmms::Track::unlock().
Referenced by lmms::gui::FileBrowserTreeWidget::handleFile(), and lmms::gui::FileBrowserTreeWidget::openInSlicerT().
loadTrackSpecificSettings()
void lmms::InstrumentTrack::loadTrackSpecificSettings (const QDomElement & _this) override virtual
Implements lmms::Track.
Definition at line 895 of file InstrumentTrack.cpp.
References lmms::AutomationClip::classNodeName(), lmms::ControllerConnection::classNodeName(), getSavedInstrumentName(), i, lmms::Instrument::instantiate(), instrumentChanged(), lmms::Track::lock(), m_arpeggio, m_audioBusHandle, m_baseNoteModel, m_firstKeyModel, m_instrument, m_lastKeyModel, m_microtuner, m_midiCCEnable, m_midiCCModel, m_midiPort, m_mixerChannelModel, m_noteStacking, m_panningModel, m_pitchModel, m_pitchRangeModel, m_previewMode, m_soundShaping, m_useMasterPitchModel, m_volumeModel, lmms::MidiControllerCount, lmms::Engine::mixer(), silenceAllNotes(), lmms::Track::unlock(), and updatePitchRange().
mapPropertyFromModel()
lmms::InstrumentTrack::mapPropertyFromModel (int , getVolume , setVolume , m_volumeModel) private
References InstrumentTrack(), applyMasterKey(), m_volumeModel, NotePlayHandle, processAudioBuffer(), processInEvent(), processOutEvent(), and silenceAllNotes().
masterKey()
int lmms::InstrumentTrack::masterKey (int _midi_key) const
Definition at line 682 of file InstrumentTrack.cpp.
References baseNote(), lmms::DefaultKey, and lmms::NumKeys.
Referenced by applyMasterKey().
microtuner()
Microtuner * lmms::InstrumentTrack::microtuner () inline
Definition at line 188 of file InstrumentTrack.h.
References m_microtuner.
midiNoteOff
void lmms::InstrumentTrack::midiNoteOff (const lmms::Note &) signal
Referenced by processInEvent().
midiNoteOn
void lmms::InstrumentTrack::midiNoteOn (const lmms::Note &) signal
midiPitch()
int lmms::InstrumentTrack::midiPitch () const inline
Definition at line 113 of file InstrumentTrack.h.
References m_pitchModel, and lmms::MidiMaxPitchBend.
Referenced by updatePitch().
midiPitchRange()
int lmms::InstrumentTrack::midiPitchRange () const inline
Returns current range for pitch bend in semitones.
Definition at line 119 of file InstrumentTrack.h.
References m_pitchRangeModel.
Referenced by updatePitchRange().
midiPort()
MidiPort * lmms::InstrumentTrack::midiPort () inline
Definition at line 151 of file InstrumentTrack.h.
References m_midiPort.
Referenced by processCCEvent(), processInEvent(), processOutEvent(), updatePitch(), and updatePitchRange().
mixerChannelModel()
IntModel * lmms::InstrumentTrack::mixerChannelModel () inline
Definition at line 221 of file InstrumentTrack.h.
References m_mixerChannelModel.
Referenced by lmms::gui::InstrumentTrackView::assignMixerLine(), lmms::gui::InstrumentTrackView::createMixerMenu(), lmms::Mixer::deleteChannel(), and replaceInstrument().
newNote
void lmms::InstrumentTrack::newNote () signal
Referenced by processOutEvent().
nodeName()
QString lmms::InstrumentTrack::nodeName () const inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 250 of file InstrumentTrack.h.
panningModel()
FloatModel * lmms::InstrumentTrack::panningModel () inline
Definition at line 211 of file InstrumentTrack.h.
References m_panningModel.
pianoModel()
Piano * lmms::InstrumentTrack::pianoModel () inline
Definition at line 183 of file InstrumentTrack.h.
References m_piano.
pitchModel()
FloatModel * lmms::InstrumentTrack::pitchModel () inline
Definition at line 201 of file InstrumentTrack.h.
References m_pitchModel.
pitchRangeModel()
IntModel * lmms::InstrumentTrack::pitchRangeModel () inline
Definition at line 216 of file InstrumentTrack.h.
References m_pitchRangeModel.
play()
bool lmms::InstrumentTrack::play (const TimePos & _start, const fpp_t _frames, const f_cnt_t _frame_base, int _clip_num = -1) override virtual
Implements lmms::Track.
Definition at line 701 of file InstrumentTrack.cpp.
References lmms::NotePlayHandleManager::acquire(), lmms::AudioEngine::addPlayHandle(), lmms::Engine::audioEngine(), lmms::PatternTrack::findPatternTrack(), lmms::Engine::framesPerTick(), lmms::Track::getClip(), lmms::Track::getClipsInRange(), lmms::gui::getGUI(), lmms::Engine::getSong(), m_instrument, m_pitchModel, m_processHandles, lmms::Song::MidiClip, NotePlayHandle, lmms::Engine::patternStore(), lmms::NotePlayHandle::setPatternTrack(), lmms::NotePlayHandle::setSongGlobalParentOffset(), lmms::Note::Step, lmms::Track::trackContainer(), lmms::Track::tryLock(), and lmms::Track::unlock().
playNote()
void lmms::InstrumentTrack::playNote (NotePlayHandle * _n, SampleFrame * _working_buffer)
Definition at line 571 of file InstrumentTrack.cpp.
References lmms::NotePlayHandle::framesLeftForCurrentPeriod(), lmms::NotePlayHandle::isMasterNote(), m_arpeggio, m_instrument, m_noteStacking, lmms::NotePlayHandle::noteOffset(), NotePlayHandle, processAudioBuffer(), and lmms::PlayHandle::usesBuffer().
processAudioBuffer()
void lmms::InstrumentTrack::processAudioBuffer (SampleFrame * _buf, const fpp_t _frames, NotePlayHandle * _n)
Definition at line 224 of file InstrumentTrack.cpp.
References lmms::DefaultVolume, lmms::Note::getPanning(), lmms::Engine::getSong(), lmms::Note::getVolume(), lmms::NotePlayHandle::isPatternTrackMuted(), lmms::MixHelpers::isSilent(), m_audioBusHandle, m_instrument, m_silentBuffersProcessed, m_soundShaping, lmms::Song::MidiClip, lmms::NotePlayHandle::noteOffset(), NotePlayHandle, lmms::PanningLeft, lmms::PanningRight, lmms::panningToVolumeVector(), and lmms::StereoVolumeVector::vol.
Referenced by mapPropertyFromModel(), lmms::InstrumentPlayHandle::play(), and playNote().
processCCEvent()
void lmms::InstrumentTrack::processCCEvent (int controller) private
Definition at line 305 of file InstrumentTrack.cpp.
References lmms::MidiEvent::Internal, m_midiCCEnable, m_midiCCModel, lmms::MidiControlChange, midiPort(), processInEvent(), and lmms::MidiPort::realOutputChannel().
Referenced by InstrumentTrack().
processInEvent()
void lmms::InstrumentTrack::processInEvent (const MidiEvent & event, const TimePos & time = TimePos(), f_cnt_t offset = 0) override virtual
Implements lmms::MidiEventProcessor.
Definition at line 323 of file InstrumentTrack.cpp.
References lmms::NotePlayHandleManager::acquire(), lmms::Engine::audioEngine(), lmms::MidiEvent::channel(), lmms::MidiEvent::controllerNumber(), lmms::MidiEvent::controllerValue(), lmms::AudioEngine::doneChangeInModel(), lmms::MidiEvent::External, firstKey(), lmms::Engine::framesPerTick(), lmms::Engine::getSong(), instrument(), isSustainPedalPressed(), lmms::MidiEvent::key(), lastKey(), m_notes, m_pitchModel, m_sustainedNotes, m_sustainPedalPressed, lmms::MidiEvent::metaEvent(), lmms::MidiControlChange, lmms::MidiControllerAllNotesOff, lmms::MidiControllerAllSoundOff, lmms::MidiControllerMonoOn, lmms::MidiControllerOmniOff, lmms::MidiControllerOmniOn, lmms::MidiControllerPolyOn, lmms::MidiControllerSustain, lmms::NotePlayHandle::MidiInput, lmms::MidiKeyPressure, lmms::MidiMaxControllerValue, lmms::MidiMaxPitchBend, lmms::MidiMetaEvent, lmms::MidiNoteOff, midiNoteOff(), lmms::MidiNoteOn, lmms::MidiNotePanning, lmms::MidiPitchBend, midiPort(), NotePlayHandle, lmms::MidiEvent::panning(), lmms::MidiEvent::pitchBend(), lmms::AudioEngine::requestChangeInModel(), silenceAllNotes(), lmms::MidiEvent::source(), lmms::MidiEvent::type(), lmms::MidiEvent::velocity(), and lmms::MidiEvent::volume().
Referenced by lmms::gui::InstrumentTrackView::activityIndicatorPressed(), lmms::gui::InstrumentTrackView::activityIndicatorReleased(), mapPropertyFromModel(), and processCCEvent().
processOutEvent()
void lmms::InstrumentTrack::processOutEvent (const MidiEvent & event, const TimePos & time = TimePos(), f_cnt_t offset = 0) override virtual
Implements lmms::MidiEventProcessor.
Definition at line 468 of file InstrumentTrack.cpp.
References applyMasterKey(), endNote(), lmms::MidiEvent::key(), m_instrument, m_midiNotesMutex, m_midiPort, m_piano, m_runningMidiNotes, lmms::MidiNoteOff, lmms::MidiNoteOn, midiPort(), newNote(), lmms::NumKeys, lmms::MidiPort::realOutputChannel(), lmms::MidiEvent::type(), and lmms::MidiEvent::velocity().
Referenced by mapPropertyFromModel(), updatePitch(), and updatePitchRange().
removeMidiPortNode()
void lmms::InstrumentTrack::removeMidiPortNode (DataFile & dataFile) static
Definition at line 692 of file InstrumentTrack.cpp.
Referenced by replaceInstrument().
replaceInstrument()
void lmms::InstrumentTrack::replaceInstrument (DataFile dataFile)
Definition at line 1017 of file InstrumentTrack.cpp.
References lmms::DataFile::content(), lmms::Engine::getSong(), lmms::Track::isMutedBeforeSolo(), lmms::Track::loadPreset(), m_mixerChannelModel, mixerChannelModel(), removeMidiPortNode(), lmms::Song::setModified(), lmms::Track::setMutedBeforeSolo(), and lmms::TypedAutomatableModel< T >::value().
Referenced by lmms::gui::FileBrowserTreeWidget::handleFile().
saveTrackSpecificSettings()
void lmms::InstrumentTrack::saveTrackSpecificSettings (QDomDocument & doc, QDomElement & parent, bool presetMode) override virtual
Implements lmms::Track.
Definition at line 833 of file InstrumentTrack.cpp.
References autoAssignMidiDevice(), lmms::Engine::getSong(), i, m_arpeggio, m_audioBusHandle, m_baseNoteModel, m_firstKeyModel, m_hasAutoMidiDev, m_instrument, m_lastKeyModel, m_microtuner, m_midiCCEnable, m_midiCCModel, m_midiPort, m_mixerChannelModel, m_noteStacking, m_panningModel, m_pitchModel, m_pitchRangeModel, m_soundShaping, m_useMasterPitchModel, m_volumeModel, and lmms::MidiControllerCount.
setName()
void lmms::InstrumentTrack::setName (const QString & _new_name) override virtual
Reimplemented from lmms::Track.
Definition at line 624 of file InstrumentTrack.cpp.
References m_audioBusHandle, m_midiPort, lmms::Track::name(), and lmms::Track::setName().
Referenced by InstrumentTrack(), and loadInstrument().
setPreviewMode()
void lmms::InstrumentTrack::setPreviewMode (const bool value)
Definition at line 1009 of file InstrumentTrack.cpp.
References m_previewMode.
silenceAllNotes()
void lmms::InstrumentTrack::silenceAllNotes (bool removeIPH = false)
Definition at line 529 of file InstrumentTrack.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), i, lmms::PlayHandle::InstrumentPlayHandle, m_midiNotesMutex, m_notes, m_processHandles, m_runningMidiNotes, lmms::PlayHandle::NotePlayHandle, lmms::NumKeys, lmms::PlayHandle::PresetPreviewHandle, lmms::AudioEngine::removePlayHandlesOfTypes(), and lmms::AudioEngine::requestChangeInModel().
Referenced by ~InstrumentTrack(), loadInstrument(), loadTrackSpecificSettings(), mapPropertyFromModel(), and processInEvent().
updateBaseNote
void lmms::InstrumentTrack::updateBaseNote () protected slot
Definition at line 636 of file InstrumentTrack.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), m_processHandles, and lmms::AudioEngine::requestChangeInModel().
Referenced by InstrumentTrack(), and updatePitch().
updateMixerChannel
void lmms::InstrumentTrack::updateMixerChannel () protected slot
Definition at line 674 of file InstrumentTrack.cpp.
References m_audioBusHandle, and m_mixerChannelModel.
Referenced by InstrumentTrack().
updatePitch
void lmms::InstrumentTrack::updatePitch () protected slot
Definition at line 649 of file InstrumentTrack.cpp.
References midiPitch(), lmms::MidiPitchBend, midiPort(), processOutEvent(), and updateBaseNote().
Referenced by InstrumentTrack().
updatePitchRange
void lmms::InstrumentTrack::updatePitchRange () protected slot
Definition at line 659 of file InstrumentTrack.cpp.
References m_pitchModel, m_pitchRangeModel, lmms::MaxPitchDefault, lmms::MidiControlChange, lmms::MidiControllerDataEntry, lmms::MidiControllerRegisteredParameterNumberLSB, lmms::MidiControllerRegisteredParameterNumberMSB, lmms::MidiPitchBendSensitivityRPN, midiPitchRange(), midiPort(), lmms::MinPitchDefault, and processOutEvent().
Referenced by InstrumentTrack(), and loadTrackSpecificSettings().
useMasterPitchModel()
BoolModel * lmms::InstrumentTrack::useMasterPitchModel () inline
Definition at line 226 of file InstrumentTrack.h.
References m_useMasterPitchModel.
volumeModel()
FloatModel * lmms::InstrumentTrack::volumeModel () inline
Definition at line 206 of file InstrumentTrack.h.
References m_volumeModel.
Friends And Related Symbol Documentation
gui::InstrumentTrackView
friend class gui::InstrumentTrackView friend
Definition at line 314 of file InstrumentTrack.h.
gui::InstrumentTrackWindow
friend class gui::InstrumentTrackWindow friend
Definition at line 315 of file InstrumentTrack.h.
gui::InstrumentTuningView
friend class gui::InstrumentTuningView friend
Definition at line 317 of file InstrumentTrack.h.
gui::MidiCCRackView
friend class gui::MidiCCRackView friend
Definition at line 318 of file InstrumentTrack.h.
NotePlayHandle
friend class NotePlayHandle friend
Definition at line 316 of file InstrumentTrack.h.
References NotePlayHandle.
Referenced by beatLen(), deleteNotePluginData(), mapPropertyFromModel(), NotePlayHandle, play(), playNote(), processAudioBuffer(), and processInEvent().
Member Data Documentation
m_arpeggio
InstrumentFunctionArpeggio lmms::InstrumentTrack::m_arpeggio private
Definition at line 304 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), isArpeggioEnabled(), loadTrackSpecificSettings(), playNote(), and saveTrackSpecificSettings().
m_audioBusHandle
AudioBusHandle lmms::InstrumentTrack::m_audioBusHandle private
Definition at line 295 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), audioBusHandle(), loadTrackSpecificSettings(), processAudioBuffer(), saveTrackSpecificSettings(), setName(), and updateMixerChannel().
m_baseNoteModel
IntModel lmms::InstrumentTrack::m_baseNoteModel private
The "A4" or "440 Hz" key (default 69).
Definition at line 283 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), baseNote(), baseNoteModel(), baseNoteModel(), loadTrackSpecificSettings(), and saveTrackSpecificSettings().
m_firstKeyModel
IntModel lmms::InstrumentTrack::m_firstKeyModel private
First key the instrument reacts to.
Definition at line 284 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), firstKey(), firstKeyModel(), loadTrackSpecificSettings(), and saveTrackSpecificSettings().
m_hasAutoMidiDev
bool lmms::InstrumentTrack::m_hasAutoMidiDev private
Definition at line 287 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), ~InstrumentTrack(), autoAssignMidiDevice(), and saveTrackSpecificSettings().
m_instrument
Instrument* lmms::InstrumentTrack::m_instrument private
Definition at line 302 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), ~InstrumentTrack(), beatLen(), deleteNotePluginData(), instrument(), instrument(), instrumentName(), loadInstrument(), loadTrackSpecificSettings(), play(), playNote(), processAudioBuffer(), processOutEvent(), and saveTrackSpecificSettings().
m_lastKeyModel
IntModel lmms::InstrumentTrack::m_lastKeyModel private
Last key the instrument reacts to.
Definition at line 285 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), lastKey(), lastKeyModel(), loadTrackSpecificSettings(), and saveTrackSpecificSettings().
m_microtuner
Microtuner lmms::InstrumentTrack::m_microtuner private
Definition at line 309 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), lmms::gui::InstrumentTuningView::InstrumentTuningView(), baseFreq(), baseNote(), firstKey(), isKeyMapped(), keyRangeImport(), lastKey(), loadTrackSpecificSettings(), microtuner(), and saveTrackSpecificSettings().
m_midiCCEnable
std::unique_ptr<BoolModel> lmms::InstrumentTrack::m_midiCCEnable private
Definition at line 311 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), loadTrackSpecificSettings(), processCCEvent(), and saveTrackSpecificSettings().
m_midiCCModel
std::unique_ptr<FloatModel> lmms::InstrumentTrack::m_midiCCModel[MidiControllerCount] private
Definition at line 312 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), loadTrackSpecificSettings(), processCCEvent(), and saveTrackSpecificSettings().
m_midiNotesMutex
QMutex lmms::InstrumentTrack::m_midiNotesMutex private
Definition at line 275 of file InstrumentTrack.h.
Referenced by processOutEvent(), and silenceAllNotes().
m_midiPort
MidiPort lmms::InstrumentTrack::m_midiPort private
Definition at line 269 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), lmms::gui::InstrumentTrackView::~InstrumentTrackView(), autoAssignMidiDevice(), loadTrackSpecificSettings(), lmms::gui::InstrumentTrackView::midiInSelected(), lmms::gui::InstrumentTrackView::midiOutSelected(), midiPort(), processOutEvent(), saveTrackSpecificSettings(), and setName().
m_mixerChannelModel
IntModel lmms::InstrumentTrack::m_mixerChannelModel private
Definition at line 299 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), loadTrackSpecificSettings(), mixerChannelModel(), replaceInstrument(), saveTrackSpecificSettings(), and updateMixerChannel().
m_notes
NotePlayHandle* lmms::InstrumentTrack::m_notes[NumKeys] private
Definition at line 271 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), processInEvent(), and silenceAllNotes().
m_noteStacking
InstrumentFunctionNoteStacking lmms::InstrumentTrack::m_noteStacking private
Definition at line 305 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), loadTrackSpecificSettings(), playNote(), and saveTrackSpecificSettings().
m_panningModel
FloatModel lmms::InstrumentTrack::m_panningModel private
Definition at line 293 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), loadTrackSpecificSettings(), panningModel(), and saveTrackSpecificSettings().
m_piano
Piano lmms::InstrumentTrack::m_piano private
Definition at line 307 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), pianoModel(), and processOutEvent().
m_pitchModel
FloatModel lmms::InstrumentTrack::m_pitchModel private
Definition at line 297 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), loadTrackSpecificSettings(), midiPitch(), pitchModel(), play(), processInEvent(), saveTrackSpecificSettings(), and updatePitchRange().
m_pitchRangeModel
IntModel lmms::InstrumentTrack::m_pitchRangeModel private
Definition at line 298 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), loadTrackSpecificSettings(), midiPitchRange(), pitchRangeModel(), saveTrackSpecificSettings(), and updatePitchRange().
m_previewMode
bool lmms::InstrumentTrack::m_previewMode private
Definition at line 281 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), isPreviewMode(), loadTrackSpecificSettings(), and setPreviewMode().
m_processHandles
NotePlayHandleList lmms::InstrumentTrack::m_processHandles private
Definition at line 290 of file InstrumentTrack.h.
Referenced by play(), silenceAllNotes(), and updateBaseNote().
m_runningMidiNotes
int lmms::InstrumentTrack::m_runningMidiNotes[NumKeys] private
Definition at line 274 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), processOutEvent(), and silenceAllNotes().
m_silentBuffersProcessed
bool lmms::InstrumentTrack::m_silentBuffersProcessed private
Definition at line 279 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), and processAudioBuffer().
m_soundShaping
InstrumentSoundShaping lmms::InstrumentTrack::m_soundShaping private
Definition at line 303 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), beatLen(), loadTrackSpecificSettings(), processAudioBuffer(), and saveTrackSpecificSettings().
m_sustainedNotes
NotePlayHandleList lmms::InstrumentTrack::m_sustainedNotes private
Definition at line 272 of file InstrumentTrack.h.
Referenced by processInEvent().
m_sustainPedalPressed
bool lmms::InstrumentTrack::m_sustainPedalPressed private
Definition at line 277 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), isSustainPedalPressed(), and processInEvent().
m_useMasterPitchModel
BoolModel lmms::InstrumentTrack::m_useMasterPitchModel private
Definition at line 300 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), lmms::gui::InstrumentTuningView::InstrumentTuningView(), baseNote(), loadTrackSpecificSettings(), saveTrackSpecificSettings(), and useMasterPitchModel().
m_volumeModel
FloatModel lmms::InstrumentTrack::m_volumeModel private
Definition at line 292 of file InstrumentTrack.h.
Referenced by InstrumentTrack(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), loadTrackSpecificSettings(), mapPropertyFromModel(), saveTrackSpecificSettings(), and volumeModel().
s_autoAssignedTrack
InstrumentTrack * lmms::InstrumentTrack::s_autoAssignedTrack = nullptr static private
Definition at line 288 of file InstrumentTrack.h.
Referenced by ~InstrumentTrack(), and autoAssignMidiDevice().
The documentation for this class was generated from the following files:
include/InstrumentTrack.h
src/tracks/InstrumentTrack.cpp