LMMS: lmms::gui::RubberBand Class Reference
lmms::gui::RubberBand Class Reference
#include <Rubberband.h>
Public Member Functions
RubberBand (QWidget *_parent)
~RubberBand () override=default
QVector< selectableObject * > selectableObjects () const
QVector< selectableObject * > selectedObjects () const
Protected Member Functions
void resizeEvent (QResizeEvent *_re) override
Detailed Description
Definition at line 76 of file Rubberband.h.
Constructor & Destructor Documentation
RubberBand()
lmms::gui::RubberBand::RubberBand (QWidget * _parent)
Definition at line 33 of file Rubberband.cpp.
~RubberBand()
lmms::gui::RubberBand::~RubberBand () override default
Member Function Documentation
resizeEvent()
void lmms::gui::RubberBand::resizeEvent (QResizeEvent * _re) override protected
Definition at line 62 of file Rubberband.cpp.
selectableObjects()
QVector< selectableObject * > lmms::gui::RubberBand::selectableObjects () const
Definition at line 70 of file Rubberband.cpp.
Referenced by lmms::gui::SongEditor::selectAllClips(), and selectedObjects().
selectedObjects()
QVector< selectableObject * > lmms::gui::RubberBand::selectedObjects () const
Definition at line 41 of file Rubberband.cpp.
References selectableObjects().
Referenced by lmms::gui::SongEditor::selectAllClips().
The documentation for this class was generated from the following files:
include/Rubberband.h
src/gui/editors/Rubberband.cpp