LMMS: lmms::InterleavedBufferView< T, channelCount > Class Template Reference
lmms::InterleavedBufferView< T, channelCount > Class Template Reference
Non-owning view for multi-channel interleaved audio data.
#include <AudioBufferView.h>
Public Member Functions
template<typename U = T>
requires (std::is_const_v<U> && channelCount == DynamicChannelCount)
constexpr InterleavedBufferView (InterleavedBufferView< std::remove_const_t< U >, channelCount > other) noexcept
Construct const from mutable (dynamic channel count).
template<typename U = T>
requires (std::is_const_v<U> && channelCount != DynamicChannelCount)
constexpr InterleavedBufferView (InterleavedBufferView< std::remove_const_t< U >, channelCount > other) noexcept
Construct const from mutable (static channel count).
template<proc_ch_t otherChannels>
requires (channelCount == DynamicChannelCount && otherChannels != DynamicChannelCount)
constexpr InterleavedBufferView (InterleavedBufferView< T, otherChannels > other) noexcept
Construct dynamic channel count from static.
InterleavedBufferView (std::span< const SampleFrame > buffer) noexcept
Construct from std::span<const SampleFrame>.
InterleavedBufferView (std::span< SampleFrame > buffer) noexcept
Construct from std::span<SampleFrame>.
constexpr auto dataSizeBytes () const noexcept -> std::size_t
constexpr auto dataView () noexcept -> std::span< T >
constexpr auto empty () const noexcept -> bool
constexpr auto frame (f_cnt_t index) const noexcept
constexpr auto framePtr (f_cnt_t index) const noexcept -> T *
constexpr auto framesView () const noexcept -> std::ranges::subrange< ConstFrameIter, const T * >
constexpr auto framesView () noexcept -> std::ranges::subrange< FrameIter, T * >
constexpr auto operator[] (f_cnt_t index) const noexcept -> T *
auto sampleFrameAt (f_cnt_t index) const noexcept -> const SampleFrame &
auto sampleFrameAt (f_cnt_t index) noexcept -> SampleFrame &
constexpr auto subspan (f_cnt_t offset, f_cnt_t frames) const -> InterleavedBufferView< T, channelCount >
auto toSampleFrames () const noexcept -> std::span< const SampleFrame >
auto toSampleFrames () noexcept -> std::span< SampleFrame >
Public Member Functions inherited from lmms::detail::BufferViewData< T, DynamicChannelCount >
constexpr BufferViewData ()=default
constexpr BufferViewData (const BufferViewData &)=default
constexpr BufferViewData (T *data, proc_ch_t channels, f_cnt_t frames) noexcept
constexpr auto channels () const noexcept -> proc_ch_t
constexpr auto data () const noexcept -> T *
constexpr auto frames () const noexcept -> f_cnt_t
Static Public Attributes
static constexpr bool Interleaved = true
Use to distinguish between InterleavedBufferView and PlanarBufferView when using AudioBufferView.
Private Types
using Base = detail::BufferViewData<T, channelCount>
using ConstFrameIter = detail::InterleavedFrameIterator<const T, channelCount>
using FrameIter = detail::InterleavedFrameIterator<T, channelCount>
Additional Inherited Members
Protected Attributes inherited from lmms::detail::BufferViewData< T, DynamicChannelCount >
proc_ch_t m_channels = 0
T * m_data = nullptr
f_cnt_t m_frames = 0
Detailed Description
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount>
class lmms::InterleavedBufferView< T, channelCount >
Non-owning view for multi-channel interleaved audio data.
TODO C++23: Use std::mdspan?
Definition at line 290 of file AudioBufferView.h.
Member Typedef Documentation
Base
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> using lmms::InterleavedBufferView< T, channelCount >::Base = detail::BufferViewData<T, channelCount> private
Definition at line 292 of file AudioBufferView.h.
ConstFrameIter
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> using lmms::InterleavedBufferView< T, channelCount >::ConstFrameIter = detail::InterleavedFrameIterator<const T, channelCount> private
Definition at line 295 of file AudioBufferView.h.
FrameIter
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> using lmms::InterleavedBufferView< T, channelCount >::FrameIter = detail::InterleavedFrameIterator<T, channelCount> private
Definition at line 294 of file AudioBufferView.h.
Constructor & Destructor Documentation
InterleavedBufferView() [1/5]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> template<typename U = T> requires (std::is_const_v<U> && channelCount != DynamicChannelCount) lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView (InterleavedBufferView< std::remove_const_t< U >, channelCount > other) inline constexpr noexcept
Construct const from mutable (static channel count).
Definition at line 302 of file AudioBufferView.h.
References InterleavedBufferView().
Referenced by InterleavedBufferView(), InterleavedBufferView(), and subspan().
InterleavedBufferView() [2/5]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> template<typename U = T> requires (std::is_const_v<U> && channelCount == DynamicChannelCount) lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView (InterleavedBufferView< std::remove_const_t< U >, channelCount > other) inline constexpr noexcept
Construct const from mutable (dynamic channel count).
Definition at line 309 of file AudioBufferView.h.
References InterleavedBufferView().
InterleavedBufferView() [3/5]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> template<proc_ch_t otherChannels> requires (channelCount == DynamicChannelCount && otherChannels != DynamicChannelCount) lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView (InterleavedBufferView< T, otherChannels > other) inline constexpr noexcept
Construct dynamic channel count from static.
Definition at line 317 of file AudioBufferView.h.
References InterleavedBufferView(), lmms::detail::BufferViewData< T, DynamicChannelCount >::data(), and lmms::detail::BufferViewData< T, DynamicChannelCount >::frames().
InterleavedBufferView() [4/5]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView (std::span< SampleFrame > buffer) inline noexcept
Construct from std::span<SampleFrame>.
Definition at line 323 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, DynamicChannelCount >::data().
InterleavedBufferView() [5/5]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView (std::span< const SampleFrame > buffer) inline noexcept
Construct from std::span<const SampleFrame>.
Definition at line 330 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, DynamicChannelCount >::data().
Member Function Documentation
dataSizeBytes()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::dataSizeBytes () const->std::size_t inline constexpr noexcept
Definition at line 341 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, channelCount >::channels(), and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
dataView()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::dataView () ->std::span< T > inline constexpr noexcept
Definition at line 346 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, channelCount >::channels(), lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
empty()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::empty () const->bool inline constexpr noexcept
Definition at line 336 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, channelCount >::channels(), lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
frame()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::frame (f_cnt_t index) const inline constexpr noexcept
Returns
the frame at the given index
Definition at line 352 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, channelCount >::channels(), lmms::DynamicChannelCount, and framePtr().
framePtr()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::framePtr (f_cnt_t index) const->T * inline constexpr noexcept
Returns
pointer to the frame at the given index. The size of the frame is channels().
Definition at line 368 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, channelCount >::channels(), lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
Referenced by frame(), and operator[]().
framesView() [1/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::framesView () const->std::ranges::subrange< ConstFrameIter, constT * > inline constexpr noexcept
Returns
a const view over the frames. Iterates in chunks containing channels() elements.
Definition at line 399 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, channelCount >::channels(), lmms::DynamicChannelCount, lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
framesView() [2/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::framesView () ->std::ranges::subrange< FrameIter, T * > inline constexpr noexcept
Returns
a view over the frames. Iterates in chunks containing channels() elements.
Definition at line 413 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, channelCount >::channels(), lmms::DynamicChannelCount, lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
operator[]()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::operator[] (f_cnt_t index) const->T * inline constexpr noexcept
Returns
pointer to the frame at the given index. The size of the frame is channels().
Definition at line 378 of file AudioBufferView.h.
References framePtr().
sampleFrameAt() [1/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::sampleFrameAt (f_cnt_t index) const->constSampleFrame & inline noexcept
Definition at line 433 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
sampleFrameAt() [2/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::sampleFrameAt (f_cnt_t index) ->SampleFrame & inline noexcept
Definition at line 426 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
subspan()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::subspan (f_cnt_t offset, f_cnt_t frames) const->InterleavedBufferView< T, channelCount > inline constexpr
Returns
a subview at the given frame offset offset with a frame count of frames
Definition at line 384 of file AudioBufferView.h.
References InterleavedBufferView(), lmms::detail::BufferViewData< T, channelCount >::channels(), lmms::DynamicChannelCount, lmms::detail::BufferViewData< T, DynamicChannelCount >::frames(), lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
toSampleFrames() [1/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::toSampleFrames () const->std::span< constSampleFrame > inline noexcept
Definition at line 446 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
toSampleFrames() [2/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::InterleavedBufferView< T, channelCount >::toSampleFrames () ->std::span< SampleFrame > inline noexcept
Definition at line 440 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames.
Member Data Documentation
Interleaved
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> bool lmms::InterleavedBufferView< T, channelCount >::Interleaved = true static constexpr
Use to distinguish between InterleavedBufferView and PlanarBufferView when using AudioBufferView.
Definition at line 453 of file AudioBufferView.h.
The documentation for this class was generated from the following file:
include/AudioBufferView.h