LMMS: lmms::gui::EffectRackView Class Reference
lmms::gui::EffectRackView Class Reference
#include <EffectRackView.h>
Public Slots
void clearViews ()
void deletePlugin (EffectView *view)
void moveDown (EffectView *view)
void moveUp (EffectView *view)
Public Member Functions
EffectRackView (EffectChain *model, QWidget *parent=nullptr)
~EffectRackView () override
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Static Public Attributes
static constexpr int DEFAULT_WIDTH = 245
Private Slots
void addEffect ()
virtual void update ()
Private Member Functions
EffectChain * fxChain ()
const EffectChain * fxChain () const
QSize minimumSizeHint () const override
void modelChanged () override
QSize sizeHint () const override
Private Attributes
GroupBox * m_effectsGroupBox
QVector< EffectView * > m_effectViews
int m_lastY
QScrollArea * m_scrollArea
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Detailed Description
Definition at line 43 of file EffectRackView.h.
Constructor & Destructor Documentation
EffectRackView()
lmms::gui::EffectRackView::EffectRackView (EffectChain * model, QWidget * parent = nullptr)
Definition at line 43 of file EffectRackView.cpp.
References lmms::gui::ModelView::ModelView(), addEffect(), m_effectsGroupBox, m_lastY, m_scrollArea, lmms::gui::ModelView::model(), and lmms::gui::ModelView::setModel().
~EffectRackView()
lmms::gui::EffectRackView::~EffectRackView () override
Definition at line 82 of file EffectRackView.cpp.
References clearViews().
Member Function Documentation
addEffect
void lmms::gui::EffectRackView::addEffect () private slot
Definition at line 237 of file EffectRackView.cpp.
References lmms::EffectChain::appendEffect(), fxChain(), lmms::gui::EffectSelectDialog::instantiateSelectedPlugin(), m_effectViews, and update().
Referenced by EffectRackView().
clearViews
void lmms::gui::EffectRackView::clearViews () slot
Definition at line 91 of file EffectRackView.cpp.
References m_effectViews.
Referenced by ~EffectRackView(), and modelChanged().
deletePlugin
void lmms::gui::EffectRackView::deletePlugin (EffectView * view) slot
Definition at line 143 of file EffectRackView.cpp.
References lmms::gui::EffectView::effect(), fxChain(), m_effectViews, lmms::EffectChain::removeEffect(), and update().
Referenced by update().
fxChain() [1/2]
EffectChain * lmms::gui::EffectRackView::fxChain () inline private
Definition at line 68 of file EffectRackView.h.
References lmms::gui::ModelView::castModel().
Referenced by addEffect(), deletePlugin(), modelChanged(), moveUp(), and update().
fxChain() [2/2]
const EffectChain * lmms::gui::EffectRackView::fxChain () const inline private
Definition at line 73 of file EffectRackView.h.
References lmms::gui::ModelView::castModel().
minimumSizeHint()
QSize lmms::gui::EffectRackView::minimumSizeHint () const inline override private
Definition at line 66 of file EffectRackView.h.
References sizeHint().
modelChanged()
void lmms::gui::EffectRackView::modelChanged () override private virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 268 of file EffectRackView.cpp.
References clearViews(), fxChain(), m_effectsGroupBox, and update().
moveDown
void lmms::gui::EffectRackView::moveDown (EffectView * view) slot
Definition at line 131 of file EffectRackView.cpp.
References m_effectViews, and moveUp().
Referenced by update().
moveUp
void lmms::gui::EffectRackView::moveUp (EffectView * view) slot
Definition at line 104 of file EffectRackView.cpp.
References lmms::gui::EffectView::effect(), fxChain(), i, m_effectViews, lmms::EffectChain::moveUp(), and update().
Referenced by moveDown(), and update().
sizeHint()
QSize lmms::gui::EffectRackView::sizeHint () const override private
Definition at line 279 of file EffectRackView.cpp.
References DEFAULT_WIDTH.
Referenced by minimumSizeHint().
update
void lmms::gui::EffectRackView::update () private virtual slot
Definition at line 156 of file EffectRackView.cpp.
References lmms::combine(), lmms::gui::EffectView::DEFAULT_WIDTH, lmms::gui::EffectView::deletedPlugin(), deletePlugin(), fxChain(), i, m_effectViews, m_lastY, m_scrollArea, lmms::gui::EffectView::movedDown(), moveDown(), lmms::gui::EffectView::moveDown(), lmms::gui::EffectView::movedUp(), moveUp(), and lmms::gui::EffectView::moveUp().
Referenced by addEffect(), deletePlugin(), modelChanged(), and moveUp().
Member Data Documentation
DEFAULT_WIDTH
int lmms::gui::EffectRackView::DEFAULT_WIDTH = 245 static constexpr
Definition at line 50 of file EffectRackView.h.
Referenced by lmms::gui::MixerChannelView::MixerChannelView(), lmms::gui::SampleTrackWindow::SampleTrackWindow(), and sizeHint().
m_effectsGroupBox
GroupBox* lmms::gui::EffectRackView::m_effectsGroupBox private
Definition at line 81 of file EffectRackView.h.
Referenced by EffectRackView(), and modelChanged().
m_effectViews
QVector<EffectView *> lmms::gui::EffectRackView::m_effectViews private
Definition at line 79 of file EffectRackView.h.
Referenced by addEffect(), clearViews(), deletePlugin(), moveDown(), moveUp(), and update().
m_lastY
int lmms::gui::EffectRackView::m_lastY private
Definition at line 84 of file EffectRackView.h.
Referenced by EffectRackView(), and update().
m_scrollArea
QScrollArea* lmms::gui::EffectRackView::m_scrollArea private
Definition at line 82 of file EffectRackView.h.
Referenced by EffectRackView(), and update().
The documentation for this class was generated from the following files:
include/EffectRackView.h
src/gui/EffectRackView.cpp