LMMS: lmms::InstrumentFunctionNoteStacking Class Reference
lmms::InstrumentFunctionNoteStacking Class Reference
#include <InstrumentFunctions.h>
Classes
struct Chord
struct ChordTable
Public Member Functions
InstrumentFunctionNoteStacking (Model *_parent)
~InstrumentFunctionNoteStacking () override=default
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
void processNote (NotePlayHandle *n)
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Static Public Attributes
static const int MAX_CHORD_POLYPHONY = 13
static const int NUM_CHORD_TABLES = 95
Private Types
using ChordSemiTones = std::array<int8_t, MAX_CHORD_POLYPHONY>
Private Attributes
FloatModel m_chordRangeModel
BoolModel m_chordsEnabledModel
ComboBoxModel m_chordsModel
Friends
class gui::InstrumentFunctionNoteStackingView
Additional Inherited Members
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 50 of file InstrumentFunctions.h.
Member Typedef Documentation
ChordSemiTones
using lmms::InstrumentFunctionNoteStacking::ChordSemiTones = std::array<int8_t, MAX_CHORD_POLYPHONY> private
Definition at line 59 of file InstrumentFunctions.h.
Constructor & Destructor Documentation
InstrumentFunctionNoteStacking()
lmms::InstrumentFunctionNoteStacking::InstrumentFunctionNoteStacking (Model * _parent)
Definition at line 210 of file InstrumentFunctions.cpp.
References lmms::Model::Model(), lmms::InstrumentFunctionNoteStacking::ChordTable::chords(), lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance(), m_chordRangeModel, m_chordsEnabledModel, and m_chordsModel.
Referenced by lmms::InstrumentFunctionNoteStacking::Chord::Chord().
~InstrumentFunctionNoteStacking()
lmms::InstrumentFunctionNoteStacking::~InstrumentFunctionNoteStacking () override default
Member Function Documentation
loadSettings()
void lmms::InstrumentFunctionNoteStacking::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 288 of file InstrumentFunctions.cpp.
References m_chordRangeModel, m_chordsEnabledModel, and m_chordsModel.
nodeName()
QString lmms::InstrumentFunctionNoteStacking::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 71 of file InstrumentFunctions.h.
processNote()
void lmms::InstrumentFunctionNoteStacking::processNote (NotePlayHandle * n)
Definition at line 230 of file InstrumentFunctions.cpp.
References lmms::NotePlayHandleManager::acquire(), lmms::AudioEngine::addPlayHandle(), lmms::NotePlayHandle::Arpeggio, lmms::Engine::audioEngine(), lmms::InstrumentFunctionNoteStacking::ChordTable::chords(), lmms::Note::detuning(), lmms::NotePlayHandle::frames(), lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance(), lmms::Note::getPanning(), lmms::Note::getVolume(), lmms::NotePlayHandle::hasParent(), i, lmms::NotePlayHandle::instrumentTrack(), lmms::InstrumentTrack::isArpeggioEnabled(), lmms::NotePlayHandle::isReleased(), lmms::Note::key(), lmms::KeysPerOctave, lmms::Note::length(), m_chordRangeModel, m_chordsEnabledModel, m_chordsModel, lmms::NotePlayHandle::NoteStacking, lmms::NumKeys, lmms::PlayHandle::offset(), lmms::NotePlayHandle::origin(), and lmms::NotePlayHandle::totalFramesPlayed().
saveSettings()
void lmms::InstrumentFunctionNoteStacking::saveSettings (QDomDocument & _doc, QDomElement & _parent) override virtual
Implements lmms::SerializingObject.
Definition at line 278 of file InstrumentFunctions.cpp.
References m_chordRangeModel, m_chordsEnabledModel, and m_chordsModel.
Friends And Related Symbol Documentation
gui::InstrumentFunctionNoteStackingView
friend class gui::InstrumentFunctionNoteStackingView friend
Definition at line 169 of file InstrumentFunctions.h.
Member Data Documentation
m_chordRangeModel
FloatModel lmms::InstrumentFunctionNoteStacking::m_chordRangeModel private
Definition at line 166 of file InstrumentFunctions.h.
Referenced by InstrumentFunctionNoteStacking(), loadSettings(), processNote(), and saveSettings().
m_chordsEnabledModel
BoolModel lmms::InstrumentFunctionNoteStacking::m_chordsEnabledModel private
Definition at line 164 of file InstrumentFunctions.h.
Referenced by InstrumentFunctionNoteStacking(), loadSettings(), processNote(), and saveSettings().
m_chordsModel
ComboBoxModel lmms::InstrumentFunctionNoteStacking::m_chordsModel private
Definition at line 165 of file InstrumentFunctions.h.
Referenced by InstrumentFunctionNoteStacking(), loadSettings(), processNote(), and saveSettings().
MAX_CHORD_POLYPHONY
const int lmms::InstrumentFunctionNoteStacking::MAX_CHORD_POLYPHONY = 13 static
Definition at line 55 of file InstrumentFunctions.h.
Referenced by lmms::InstrumentFunctionNoteStacking::Chord::Chord().
NUM_CHORD_TABLES
const int lmms::InstrumentFunctionNoteStacking::NUM_CHORD_TABLES = 95 static
Definition at line 56 of file InstrumentFunctions.h.
The documentation for this class was generated from the following files:
include/InstrumentFunctions.h
src/core/InstrumentFunctions.cpp