LMMS: lmms::Clip Class Reference
lmms::Clip Class Reference abstract
#include <Clip.h>
Public Slots
void toggleMute ()
Mutes this Clip.
Signals
void colorChanged ()
void destroyedClip ()
void lengthChanged ()
void positionChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
Clip (Track *track)
Create a new Clip.
~Clip () override
Destroy a Clip.
virtual void changeLength (const TimePos &length)
Change the length of this Clip.
virtual Clip * clone ()=0
Creates a copy of this clip.
auto color () const -> const std::optional< QColor > &
virtual gui::ClipView * createView (gui::TrackView *tv)=0
QString displayName () const override
TimePos endPosition () const
bool getAutoResize () const
bool getSelectViewOnCreate ()
Track * getTrack () const
bool hasTrackContainer () const
bool isInPattern () const
const TimePos & length () const
bool manuallyResizable () const
virtual void movePosition (const TimePos &pos)
Move this Clip's position in time.
const QString & name () const
void selectViewOnCreate (bool select)
void setAutoResize (const bool r)
Set whether a clip has been resized yet by the user or the knife tool.
void setColor (const std::optional< QColor > &color)
void setName (const QString &name)
void setStartTimeOffset (const TimePos &startTimeOffset)
const TimePos & startPosition () const
TimePos startTimeOffset () const
virtual void updateLength ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static bool comparePosition (const Clip *a, const Clip *b)
Returns true if and only if a->startPosition() < b->startPosition().
static void copyStateTo (Clip *src, Clip *dst)
Copies the state of a Clip to another Clip.
Protected Member Functions
Clip (const Clip &other)
Copy a Clip.
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Member Functions inherited from lmms::SerializingObject
virtual void loadSettings (const QDomElement &element)=0
virtual void saveSettings (QDomDocument &doc, QDomElement &element)=0
Private Member Functions
mapPropertyFromModel (bool, isMuted, setMuted, m_mutedModel)
mapPropertyFromModel (bool, isSolo, setSolo, m_soloModel)
Private Attributes
bool m_autoResize = true
std::optional< QColor > m_color
TimePos m_length
BoolModel m_mutedModel
QString m_name
bool m_selectViewOnCreate
BoolModel m_soloModel
TimePos m_startPosition
TimePos m_startTimeOffset
Track * m_track
Friends
class ClipView
Detailed Description
Definition at line 49 of file Clip.h.
Constructor & Destructor Documentation
Clip() [1/2]
lmms::Clip::Clip (Track * track)
Create a new Clip.
Creates a new clip for the given track.
Parameters
_track The track that will contain the new object
Definition at line 47 of file Clip.cpp.
References lmms::Model::Model(), lmms::Track::addClip(), changeLength(), getTrack(), m_length, m_mutedModel, m_selectViewOnCreate, m_startPosition, m_track, movePosition(), and lmms::JournallingObject::setJournalling().
Referenced by lmms::AutomationClip::AutomationClip(), lmms::AutomationClip::AutomationClip(), Clip(), lmms::MidiClip::MidiClip(), lmms::MidiClip::MidiClip(), lmms::PatternClip::PatternClip(), lmms::SampleClip::SampleClip(), lmms::SampleClip::SampleClip(), clone(), colorChanged(), comparePosition(), copyStateTo(), and mapPropertyFromModel().
~Clip()
lmms::Clip::~Clip () override
Destroy a Clip.
Destroys the given clip.
Definition at line 95 of file Clip.cpp.
References destroyedClip(), getTrack(), and lmms::Track::removeClip().
Clip() [2/2]
lmms::Clip::Clip (const Clip & other) protected
Copy a Clip.
Creates a duplicate clip of the one provided.
Parameters
other The clip object which will be copied.
Definition at line 72 of file Clip.cpp.
References Clip(), lmms::Model::Model(), lmms::Track::addClip(), getTrack(), m_autoResize, m_color, m_length, m_mutedModel, m_name, m_selectViewOnCreate, m_startPosition, m_startTimeOffset, and m_track.
Member Function Documentation
changeLength()
void lmms::Clip::changeLength (const TimePos & length) virtual
Change the length of this Clip.
If the clip's length has changed, update it. We also add a journal entry for undo and update the display.
Parameters
_length The new length of the clip.
Reimplemented in lmms::SampleClip.
Definition at line 138 of file Clip.cpp.
References lmms::Engine::getSong(), length(), lengthChanged(), m_length, and lmms::Song::updateLength().
Referenced by lmms::AutomationClip::AutomationClip(), Clip(), lmms::PatternClip::PatternClip(), lmms::SampleClip::changeLength(), lmms::gui::TrackContentWidget::changePosition(), lmms::Track::createClipsForPattern(), lmms::AutomationClip::loadSettings(), lmms::MidiClip::loadSettings(), lmms::PatternClip::loadSettings(), lmms::AutomationClip::updateLength(), and lmms::MidiClip::updateLength().
clone()
virtual Clip * lmms::Clip::clone () pure virtual
Creates a copy of this clip.
Returns
pointer to the new clip object
Implemented in lmms::AutomationClip, lmms::MidiClip, lmms::PatternClip, and lmms::SampleClip.
References Clip(), and toggleMute().
color()
auto lmms::Clip::color () const->conststd::optional< QColor > & inline
Definition at line 119 of file Clip.h.
References m_color.
Referenced by lmms::MidiClip::exportToXML(), lmms::AutomationClip::saveSettings(), lmms::PatternClip::saveSettings(), lmms::SampleClip::saveSettings(), and setColor().
colorChanged
void lmms::Clip::colorChanged () signal
References Clip().
Referenced by setColor().
comparePosition()
bool lmms::Clip::comparePosition (const Clip * a, const Clip * b) static
Returns true if and only if a->startPosition() < b->startPosition().
Definition at line 148 of file Clip.cpp.
References Clip(), and startPosition().
Referenced by lmms::TrackContainer::automatedValuesFromTracks(), and lmms::Track::getClipsInRange().
copyStateTo()
void lmms::Clip::copyStateTo (Clip * src, Clip * dst) static
Copies the state of a Clip to another Clip.
This method copies the state of a Clip to another Clip
Definition at line 160 of file Clip.cpp.
References Clip(), lmms::gui::GuiApplication::automationEditor(), lmms::gui::getGUI(), lmms::gui::AutomationEditorWindow::m_editor, movePosition(), lmms::SerializingObject::nodeName(), pos, lmms::AutomationClip::resolveAllIDs(), lmms::JournallingObject::restoreState(), lmms::JournallingObject::saveState(), startPosition(), and lmms::gui::AutomationEditor::updateAfterClipChange().
Referenced by lmms::PatternTrack::loadTrackSpecificSettings().
createView()
virtual gui::ClipView * lmms::Clip::createView (gui::TrackView * tv) pure virtual
Implemented in lmms::AutomationClip, lmms::MidiClip, lmms::PatternClip, and lmms::SampleClip.
Referenced by lmms::gui::TrackView::createClipView().
destroyedClip
void lmms::Clip::destroyedClip () signal
Referenced by ~Clip().
displayName()
QString lmms::Clip::displayName () const inline override virtual
Reimplemented from lmms::Model.
Definition at line 74 of file Clip.h.
References name().
endPosition()
TimePos lmms::Clip::endPosition () const inline
Definition at line 85 of file Clip.h.
References m_length, and m_startPosition.
Referenced by lmms::gui::TrackContentWidget::changePosition().
getAutoResize()
bool lmms::Clip::getAutoResize () const inline
Definition at line 114 of file Clip.h.
References m_autoResize.
Referenced by lmms::MidiClip::exportToXML(), lmms::AutomationClip::saveSettings(), lmms::PatternClip::saveSettings(), lmms::SampleClip::saveSettings(), lmms::AutomationClip::updateLength(), lmms::MidiClip::updateLength(), and lmms::SampleClip::updateLength().
getSelectViewOnCreate()
bool lmms::Clip::getSelectViewOnCreate () inline
Definition at line 133 of file Clip.h.
References m_selectViewOnCreate.
Referenced by lmms::gui::TrackView::createClipView().
getTrack()
Track * lmms::Clip::getTrack () const inline
Definition at line 58 of file Clip.h.
References m_track.
Referenced by Clip(), Clip(), lmms::gui::PatternClipView::PatternClipView(), lmms::SampleClip::SampleClip(), lmms::SampleClip::SampleClip(), lmms::SamplePlayHandle::SamplePlayHandle(), ~Clip(), lmms::SampleClip::~SampleClip(), hasTrackContainer(), isInPattern(), lmms::PatternClip::patternIndex(), lmms::SampleClip::playbackPositionChanged(), lmms::gui::TrackOperationsWidget::toggleRecording(), lmms::gui::ClipView::toggleSelectedAutoResize(), lmms::MidiClip::updatePatternTrack(), and lmms::SampleClip::updateTrackClips().
hasTrackContainer()
bool lmms::Clip::hasTrackContainer () const
Definition at line 177 of file Clip.cpp.
References getTrack(), and lmms::Track::trackContainer().
Referenced by isInPattern().
isInPattern()
bool lmms::Clip::isInPattern () const
Definition at line 182 of file Clip.cpp.
References getTrack(), hasTrackContainer(), lmms::TrackContainer::Pattern, lmms::Track::trackContainer(), and lmms::TrackContainer::type().
Referenced by manuallyResizable().
length()
const TimePos & lmms::Clip::length () const inline
Definition at line 91 of file Clip.h.
References m_length.
Referenced by changeLength(), lmms::gui::TrackContentWidget::changePosition(), lmms::MidiClip::exportToXML(), lmms::AutomationClip::flipX(), lmms::AutomationClip::saveSettings(), lmms::PatternClip::saveSettings(), lmms::SampleClip::saveSettings(), and lmms::SampleClip::setSamplePlayLength().
lengthChanged
void lmms::Clip::lengthChanged () signal
Referenced by changeLength(), lmms::gui::AutomationEditor::setCurrentClip(), and lmms::gui::PianoRoll::setCurrentMidiClip().
manuallyResizable()
bool lmms::Clip::manuallyResizable () const
Definition at line 188 of file Clip.cpp.
References isInPattern().
mapPropertyFromModel() [1/2]
lmms::Clip::mapPropertyFromModel (bool , isMuted , setMuted , m_mutedModel) private
References m_mutedModel.
mapPropertyFromModel() [2/2]
lmms::Clip::mapPropertyFromModel (bool , isSolo , setSolo , m_soloModel) private
References Clip(), and m_soloModel.
movePosition()
void lmms::Clip::movePosition (const TimePos & pos) virtual
Move this Clip's position in time.
If the clip has moved, update its position. We also add a journal entry for undo and update the display.
Parameters
_pos The new position of the clip.
Definition at line 115 of file Clip.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), lmms::Engine::getSong(), m_startPosition, pos, positionChanged(), lmms::AudioEngine::requestChangeInModel(), and lmms::Song::updateLength().
Referenced by Clip(), copyStateTo(), lmms::AutomationClip::loadSettings(), lmms::MidiClip::loadSettings(), lmms::PatternClip::loadSettings(), lmms::SampleClip::loadSettings(), and lmms::gui::TrackContentWidget::pasteSelection().
name()
const QString & lmms::Clip::name () const inline
Definition at line 63 of file Clip.h.
References m_name.
Referenced by displayName(), lmms::MidiClip::exportToXML(), lmms::AutomationClip::name(), lmms::PatternClip::saveSettings(), lmms::gui::PianoRollWindow::setCurrentMidiClip(), and setName().
positionChanged
void lmms::Clip::positionChanged () signal
Referenced by lmms::SampleClip::SampleClip(), lmms::SampleClip::SampleClip(), and movePosition().
selectViewOnCreate()
void lmms::Clip::selectViewOnCreate (bool select) inline
Definition at line 128 of file Clip.h.
References m_selectViewOnCreate.
Referenced by lmms::gui::TrackView::createClipView(), and lmms::gui::TrackContentWidget::pasteSelection().
setAutoResize()
void lmms::Clip::setAutoResize (const bool r) inline
Set whether a clip has been resized yet by the user or the knife tool.
If a clip has been resized previously, it will not automatically resize when editing it.
Definition at line 109 of file Clip.h.
References m_autoResize.
Referenced by lmms::AutomationClip::loadSettings(), lmms::MidiClip::loadSettings(), lmms::PatternClip::loadSettings(), lmms::SampleClip::loadSettings(), and lmms::gui::ClipView::toggleSelectedAutoResize().
setColor()
void lmms::Clip::setColor (const std::optional< QColor > & color)
Definition at line 225 of file Clip.cpp.
References color(), colorChanged(), and m_color.
Referenced by lmms::AutomationClip::loadSettings(), lmms::MidiClip::loadSettings(), lmms::PatternClip::loadSettings(), and lmms::SampleClip::loadSettings().
setName()
void lmms::Clip::setName (const QString & name) inline
Definition at line 68 of file Clip.h.
References lmms::Model::dataChanged(), m_name, and name().
Referenced by lmms::AutomationClip::loadSettings(), lmms::MidiClip::loadSettings(), and lmms::PatternClip::loadSettings().
setStartTimeOffset()
void lmms::Clip::setStartTimeOffset (const TimePos & startTimeOffset)
Definition at line 220 of file Clip.cpp.
References m_startTimeOffset, and startTimeOffset().
Referenced by lmms::AutomationClip::loadSettings(), lmms::MidiClip::loadSettings(), lmms::PatternClip::loadSettings(), lmms::SampleClip::loadSettings(), lmms::SampleClip::setSampleFile(), lmms::AutomationClip::updateLength(), lmms::MidiClip::updateLength(), and lmms::SampleClip::updateLength().
startPosition()
const TimePos & lmms::Clip::startPosition () const inline
Definition at line 80 of file Clip.h.
References m_startPosition.
Referenced by lmms::gui::TrackContentWidget::changePosition(), comparePosition(), copyStateTo(), lmms::MidiClip::exportToXML(), lmms::AutomatableModel::globalAutomationValueAt(), lmms::AutomationClip::saveSettings(), lmms::PatternClip::saveSettings(), lmms::SampleClip::saveSettings(), and lmms::PatternStore::updatePatternTrack().
startTimeOffset()
TimePos lmms::Clip::startTimeOffset () const
Definition at line 212 of file Clip.cpp.
References m_startTimeOffset.
Referenced by lmms::MidiClip::exportToXML(), lmms::AutomationClip::flipX(), lmms::AutomatableModel::globalAutomationValueAt(), lmms::AutomationClip::recordValue(), lmms::AutomationClip::saveSettings(), lmms::PatternClip::saveSettings(), lmms::SampleClip::saveSettings(), and setStartTimeOffset().
toggleMute
void lmms::Clip::toggleMute () slot
Mutes this Clip.
Restore the previous state of this clip. This will restore the position or the length of the clip depending on what was changed.
Parameters
_je The journal entry to undo
Definition at line 203 of file Clip.cpp.
References lmms::Model::dataChanged(), and m_mutedModel.
Referenced by clone(), lmms::MidiClip::loadSettings(), and lmms::PatternClip::loadSettings().
updateLength()
virtual void lmms::Clip::updateLength () inline virtual
Reimplemented in lmms::AutomationClip, and lmms::MidiClip.
Definition at line 124 of file Clip.h.
Referenced by lmms::gui::ClipView::toggleSelectedAutoResize().
Friends And Related Symbol Documentation
ClipView
friend class ClipView friend
Definition at line 182 of file Clip.h.
References ClipView.
Referenced by ClipView.
Member Data Documentation
m_autoResize
bool lmms::Clip::m_autoResize = true private
Definition at line 176 of file Clip.h.
Referenced by Clip(), getAutoResize(), and setAutoResize().
m_color
std::optional<QColor> lmms::Clip::m_color private
Definition at line 180 of file Clip.h.
Referenced by Clip(), color(), and setColor().
m_length
TimePos lmms::Clip::m_length private
Definition at line 171 of file Clip.h.
Referenced by Clip(), Clip(), changeLength(), endPosition(), and length().
m_mutedModel
BoolModel lmms::Clip::m_mutedModel private
Definition at line 174 of file Clip.h.
Referenced by Clip(), Clip(), mapPropertyFromModel(), and toggleMute().
m_name
QString lmms::Clip::m_name private
Definition at line 168 of file Clip.h.
Referenced by Clip(), name(), and setName().
m_selectViewOnCreate
bool lmms::Clip::m_selectViewOnCreate private
Definition at line 178 of file Clip.h.
Referenced by Clip(), Clip(), getSelectViewOnCreate(), and selectViewOnCreate().
m_soloModel
BoolModel lmms::Clip::m_soloModel private
Definition at line 175 of file Clip.h.
Referenced by mapPropertyFromModel().
m_startPosition
TimePos lmms::Clip::m_startPosition private
Definition at line 170 of file Clip.h.
Referenced by Clip(), Clip(), endPosition(), movePosition(), and startPosition().
m_startTimeOffset
TimePos lmms::Clip::m_startTimeOffset private
Definition at line 172 of file Clip.h.
Referenced by Clip(), setStartTimeOffset(), and startTimeOffset().
m_track
Track* lmms::Clip::m_track private
Definition at line 167 of file Clip.h.
Referenced by Clip(), Clip(), and getTrack().
The documentation for this class was generated from the following files:
include/Clip.h
src/core/Clip.cpp