LMMS: lmms::gui::SongEditorWindow Class Reference
lmms::gui::SongEditorWindow Class Reference
#include <SongEditor.h>
Signals
void playTriggered ()
void resized ()
Public Member Functions
SongEditorWindow (Song *song)
QSize sizeHint () const override
void syncEditMode ()
Public Member Functions inherited from lmms::gui::Editor
QAction * playAction () const
void setPauseIcon (bool displayPauseIcon=true)
Public Attributes
SongEditor * m_editor
Protected Slots
void adjustUiAfterProjectLoad ()
void lostFocus ()
void play () override
void record () override
void recordAccompany () override
void stop () override
void updateSnapLabel ()
Protected Slots inherited from lmms::gui::Editor
virtual void play ()
virtual void record ()
virtual void recordAccompany ()
virtual void stop ()
virtual void toggleStepRecording ()
Protected Member Functions
void changeEvent (QEvent *) override
void resizeEvent (QResizeEvent *event) override
Protected Member Functions inherited from lmms::gui::Editor
Editor (bool record=false, bool record_step=false)
Constructor.
~Editor () override=default
DropToolBar * addDropToolBar (Qt::ToolBarArea whereToAdd, QString const &windowTitle)
DropToolBar * addDropToolBar (QWidget *parent, Qt::ToolBarArea whereToAdd, QString const &windowTitle)
DropToolBar * addDropToolBarToTop (QString const &windowTitle)
void closeEvent (QCloseEvent *event) override
void keyPressEvent (QKeyEvent *ke) override
Private Attributes
QAction * m_addAutomationTrackAction
QAction * m_addPatternTrackAction
QAction * m_addSampleTrackAction
QAction * m_crtlAction
QAction * m_drawModeAction
ActionGroup * m_editModeGroup
QAction * m_insertBarAction
QAction * m_knifeModeAction
QAction * m_removeBarAction
QAction * m_selectModeAction
QAction * m_setProportionalSnapAction
ComboBox * m_snappingComboBox
QLabel * m_snapSizeLabel
AutomatableSlider * m_zoomingSlider
Additional Inherited Members
Public Slots inherited from lmms::gui::Editor
void togglePause ()
Called by pressing shift+space. Toggles pause state.
void togglePlayStop ()
Called by pressing the space key. Plays or stops.
Static Public Member Functions inherited from lmms::gui::Editor
static Editor * lastPlayedEditor ()
Protected Attributes inherited from lmms::gui::Editor
QAction * m_playAction
QAction * m_recordAccompanyAction
QAction * m_recordAction
QAction * m_stopAction
QAction * m_toggleStepRecordingAction
DropToolBar * m_toolBar
Detailed Description
Definition at line 175 of file SongEditor.h.
Constructor & Destructor Documentation
SongEditorWindow()
lmms::gui::SongEditorWindow::SongEditorWindow (Song * song)
Definition at line 917 of file SongEditor.cpp.
References lmms::gui::Editor::Editor(), lmms::gui::Editor::addDropToolBarToTop(), adjustUiAfterProjectLoad(), lmms::gui::ComboBox::DEFAULT_HEIGHT, lmms::embed::getIconPixmap(), m_addAutomationTrackAction, m_addPatternTrackAction, m_addSampleTrackAction, m_crtlAction, m_drawModeAction, m_editModeGroup, m_editor, m_insertBarAction, m_knifeModeAction, lmms::gui::Editor::m_playAction, lmms::gui::Editor::m_recordAccompanyAction, lmms::gui::Editor::m_recordAction, m_removeBarAction, m_selectModeAction, m_setProportionalSnapAction, m_snappingComboBox, m_snapSizeLabel, lmms::gui::Editor::m_stopAction, lmms::gui::Editor::m_toolBar, m_zoomingSlider, resized(), and updateSnapLabel().
Member Function Documentation
adjustUiAfterProjectLoad
void lmms::gui::SongEditorWindow::adjustUiAfterProjectLoad () protected slot
Definition at line 1132 of file SongEditor.cpp.
References lmms::gui::getGUI(), lostFocus(), m_editor, lmms::gui::GuiApplication::mainWindow(), and lmms::gui::MainWindow::workspace().
Referenced by SongEditorWindow().
changeEvent()
void lmms::gui::SongEditorWindow::changeEvent (QEvent * event) override protected
Definition at line 1071 of file SongEditor.cpp.
References m_editor.
lostFocus
void lmms::gui::SongEditorWindow::lostFocus () protected slot
Definition at line 1120 of file SongEditor.cpp.
References m_crtlAction.
Referenced by adjustUiAfterProjectLoad().
play
void lmms::gui::SongEditorWindow::play () override protected slot
Definition at line 1081 of file SongEditor.cpp.
References lmms::Song::Song, lmms::Engine::getSong(), lmms::Song::playSong(), playTriggered(), and lmms::Song::togglePause().
playTriggered
void lmms::gui::SongEditorWindow::playTriggered () signal
Referenced by play().
record
void lmms::gui::SongEditorWindow::record () override protected slot
Definition at line 1095 of file SongEditor.cpp.
References m_editor.
recordAccompany
void lmms::gui::SongEditorWindow::recordAccompany () override protected slot
Definition at line 1103 of file SongEditor.cpp.
References m_editor.
resized
void lmms::gui::SongEditorWindow::resized () signal
Referenced by SongEditorWindow(), and resizeEvent().
resizeEvent()
void lmms::gui::SongEditorWindow::resizeEvent (QResizeEvent * event) override protected
Definition at line 1065 of file SongEditor.cpp.
References resized().
sizeHint()
QSize lmms::gui::SongEditorWindow::sizeHint () const override
Definition at line 1037 of file SongEditor.cpp.
stop
void lmms::gui::SongEditorWindow::stop () override protected slot
Definition at line 1111 of file SongEditor.cpp.
References lmms::gui::getGUI(), m_editor, lmms::gui::GuiApplication::pianoRoll(), and lmms::gui::PianoRollWindow::stopRecording().
syncEditMode()
void lmms::gui::SongEditorWindow::syncEditMode ()
Definition at line 1058 of file SongEditor.cpp.
References m_editModeGroup.
Referenced by lmms::gui::TrackContentWidget::mouseReleaseEvent().
updateSnapLabel
void lmms::gui::SongEditorWindow::updateSnapLabel () protected slot
Definition at line 1042 of file SongEditor.cpp.
References m_editor, m_setProportionalSnapAction, m_snappingComboBox, and m_snapSizeLabel.
Referenced by SongEditorWindow().
Member Data Documentation
m_addAutomationTrackAction
QAction* lmms::gui::SongEditorWindow::m_addAutomationTrackAction private
Definition at line 208 of file SongEditor.h.
Referenced by SongEditorWindow().
m_addPatternTrackAction
QAction* lmms::gui::SongEditorWindow::m_addPatternTrackAction private
Definition at line 206 of file SongEditor.h.
Referenced by SongEditorWindow().
m_addSampleTrackAction
QAction* lmms::gui::SongEditorWindow::m_addSampleTrackAction private
Definition at line 207 of file SongEditor.h.
Referenced by SongEditorWindow().
m_crtlAction
QAction* lmms::gui::SongEditorWindow::m_crtlAction private
Definition at line 215 of file SongEditor.h.
Referenced by SongEditorWindow(), and lostFocus().
m_drawModeAction
QAction* lmms::gui::SongEditorWindow::m_drawModeAction private
Definition at line 212 of file SongEditor.h.
Referenced by SongEditorWindow().
m_editModeGroup
ActionGroup* lmms::gui::SongEditorWindow::m_editModeGroup private
Definition at line 211 of file SongEditor.h.
Referenced by SongEditorWindow(), and syncEditMode().
m_editor
SongEditor* lmms::gui::SongEditorWindow::m_editor
Definition at line 183 of file SongEditor.h.
Referenced by SongEditorWindow(), adjustUiAfterProjectLoad(), changeEvent(), lmms::Song::clearProject(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackContentWidget::mousePressEvent(), lmms::gui::TrackContentWidget::pasteSelection(), record(), recordAccompany(), stop(), lmms::gui::TrackContentWidget::updateBackground(), and updateSnapLabel().
m_insertBarAction
QAction* lmms::gui::SongEditorWindow::m_insertBarAction private
Definition at line 221 of file SongEditor.h.
Referenced by SongEditorWindow().
m_knifeModeAction
QAction* lmms::gui::SongEditorWindow::m_knifeModeAction private
Definition at line 213 of file SongEditor.h.
Referenced by SongEditorWindow().
m_removeBarAction
QAction* lmms::gui::SongEditorWindow::m_removeBarAction private
Definition at line 222 of file SongEditor.h.
Referenced by SongEditorWindow().
m_selectModeAction
QAction* lmms::gui::SongEditorWindow::m_selectModeAction private
Definition at line 214 of file SongEditor.h.
Referenced by SongEditorWindow().
m_setProportionalSnapAction
QAction* lmms::gui::SongEditorWindow::m_setProportionalSnapAction private
Definition at line 209 of file SongEditor.h.
Referenced by SongEditorWindow(), and updateSnapLabel().
m_snappingComboBox
ComboBox* lmms::gui::SongEditorWindow::m_snappingComboBox private
Definition at line 218 of file SongEditor.h.
Referenced by SongEditorWindow(), and updateSnapLabel().
m_snapSizeLabel
QLabel* lmms::gui::SongEditorWindow::m_snapSizeLabel private
Definition at line 219 of file SongEditor.h.
Referenced by SongEditorWindow(), and updateSnapLabel().
m_zoomingSlider
AutomatableSlider* lmms::gui::SongEditorWindow::m_zoomingSlider private
Definition at line 217 of file SongEditor.h.
Referenced by SongEditorWindow().
The documentation for this class was generated from the following files:
include/SongEditor.h
src/gui/editors/SongEditor.cpp