LMMS: lmms::gui::LcdSpinBox Class Reference
lmms::gui::LcdSpinBox Class Reference
#include <LcdSpinBox.h>
Public Slots
virtual void update ()
Public Slots inherited from lmms::gui::LcdWidget
virtual void setMarginWidth (int width)
Signals
void manualChange ()
Public Member Functions
LcdSpinBox (int numDigits, const QString &style, QWidget *parent, const QString &name=QString())
LcdSpinBox (int numDigits, QWidget *parent, const QString &name=QString())
~LcdSpinBox () override=default
int displayOffset () const
Returns internal offset for displaying values.
void modelChanged () override
void setDisplayOffset (int offset)
Sets an offset which is always added to value of model so we can display values in a user-friendly way if they internally start at 0.
Public Member Functions inherited from lmms::gui::LcdWidget
LcdWidget (int numDigits, const QString &style, QWidget *parent, const QString &name=QString(), bool leadingZero=false)
LcdWidget (int numDigits, QWidget *parent, const QString &name=QString(), bool leadingZero=false)
LcdWidget (QWidget *parent, const QString &name=QString(), bool leadingZero=false)
void addTextForValue (int value, const QString &text)
int cellHeight () const
int numDigits () const
void setLabel (const QString &label)
void setNumDigits (int n)
void setSeamless (bool left, bool right)
void setTextColor (const QColor &c)
void setTextShadowColor (const QColor &c)
void setValue (float value)
void setValue (int value)
QColor textColor () const
QColor textShadowColor () const
Public Member Functions inherited from lmms::gui::TypedModelView< IntModel >
TypedModelView (Model *model, QWidget *_this)
IntModel * model ()
const IntModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *_me) override
void mouseDoubleClickEvent (QMouseEvent *_me) override
void mouseMoveEvent (QMouseEvent *_me) override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
void wheelEvent (QWheelEvent *_we) override
Protected Member Functions inherited from lmms::gui::LcdWidget
void paintEvent (QPaintEvent *pe) override
virtual void updateSize ()
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Member Functions
void enterValue ()
Private Attributes
int m_displayOffset
QPoint m_lastMousePos
mouse position in last mouseMoveEvent
bool m_mouseMoving
float m_remainder
floating offset of spinbox in [-0.5, 0.5]
Additional Inherited Members
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Properties inherited from lmms::gui::LcdWidget
int numDigits
QColor textColor
QColor textShadowColor
Detailed Description
Definition at line 34 of file LcdSpinBox.h.
Constructor & Destructor Documentation
LcdSpinBox() [1/2]
lmms::gui::LcdSpinBox::LcdSpinBox (int numDigits, QWidget * parent, const QString & name = QString())
Definition at line 38 of file LcdSpinBox.cpp.
References lmms::gui::LcdWidget::LcdWidget(), m_displayOffset, m_lastMousePos, m_mouseMoving, m_remainder, and lmms::gui::LcdWidget::numDigits.
Referenced by lmms::gui::MixerChannelLcdSpinBox::MixerChannelLcdSpinBox().
LcdSpinBox() [2/2]
lmms::gui::LcdSpinBox::LcdSpinBox (int numDigits, const QString & style, QWidget * parent, const QString & name = QString())
Definition at line 51 of file LcdSpinBox.cpp.
References lmms::gui::LcdWidget::LcdWidget(), m_displayOffset, m_lastMousePos, m_mouseMoving, m_remainder, and lmms::gui::LcdWidget::numDigits.
~LcdSpinBox()
lmms::gui::LcdSpinBox::~LcdSpinBox () override default
Member Function Documentation
contextMenuEvent()
void lmms::gui::LcdSpinBox::contextMenuEvent (QContextMenuEvent * _me) override protected
Definition at line 70 of file LcdSpinBox.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), and lmms::gui::TypedModelView< IntModel >::model().
displayOffset()
int lmms::gui::LcdSpinBox::displayOffset () const inline
Returns internal offset for displaying values.
Definition at line 58 of file LcdSpinBox.h.
References m_displayOffset.
enterValue()
void lmms::gui::LcdSpinBox::enterValue () private
Definition at line 156 of file LcdSpinBox.cpp.
References lmms::gui::TypedModelView< IntModel >::model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Referenced by mouseDoubleClickEvent().
manualChange
void lmms::gui::LcdSpinBox::manualChange () signal
Referenced by mouseMoveEvent(), and wheelEvent().
modelChanged()
void lmms::gui::LcdSpinBox::modelChanged () inline override virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 44 of file LcdSpinBox.h.
References lmms::gui::ModelView::modelChanged(), and update().
mouseDoubleClickEvent()
void lmms::gui::LcdSpinBox::mouseDoubleClickEvent (QMouseEvent * _me) override protected
Definition at line 151 of file LcdSpinBox.cpp.
References enterValue().
mouseMoveEvent()
void lmms::gui::LcdSpinBox::mouseMoveEvent (QMouseEvent * _me) override protected
Definition at line 105 of file LcdSpinBox.cpp.
References m_lastMousePos, m_mouseMoving, m_remainder, manualChange(), lmms::gui::TypedModelView< IntModel >::model(), lmms::AutomatableModel::setValue(), lmms::AutomatableModel::step(), and lmms::TypedAutomatableModel< T >::value().
mousePressEvent()
void lmms::gui::LcdSpinBox::mousePressEvent (QMouseEvent * _me) override protected virtual
Reimplemented from lmms::gui::AutomatableModelView.
Definition at line 80 of file LcdSpinBox.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), lmms::gui::LcdWidget::cellHeight(), lmms::KBD_COPY_MODIFIER, m_lastMousePos, m_mouseMoving, lmms::gui::TypedModelView< IntModel >::model(), lmms::gui::AutomatableModelView::mousePressEvent(), and lmms::JournallingObject::saveJournallingState().
mouseReleaseEvent()
void lmms::gui::LcdSpinBox::mouseReleaseEvent (QMouseEvent * _me) override protected
Definition at line 130 of file LcdSpinBox.cpp.
References m_mouseMoving, lmms::gui::TypedModelView< IntModel >::model(), and lmms::JournallingObject::restoreJournallingState().
Referenced by lmms::gui::MixerChannelLcdSpinBox::contextMenuEvent().
setDisplayOffset()
void lmms::gui::LcdSpinBox::setDisplayOffset (int offset) inline
Sets an offset which is always added to value of model so we can display values in a user-friendly way if they internally start at 0.
Definition at line 52 of file LcdSpinBox.h.
References m_displayOffset.
update
void lmms::gui::LcdSpinBox::update () virtual slot
Definition at line 61 of file LcdSpinBox.cpp.
References m_displayOffset, lmms::gui::TypedModelView< IntModel >::model(), lmms::gui::LcdWidget::setValue(), and lmms::gui::AutomatableModelView::value().
Referenced by modelChanged().
wheelEvent()
void lmms::gui::LcdSpinBox::wheelEvent (QWheelEvent * _we) override protected
Definition at line 142 of file LcdSpinBox.cpp.
References manualChange(), lmms::gui::TypedModelView< IntModel >::model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Member Data Documentation
m_displayOffset
int lmms::gui::LcdSpinBox::m_displayOffset private
Definition at line 80 of file LcdSpinBox.h.
Referenced by LcdSpinBox(), LcdSpinBox(), displayOffset(), setDisplayOffset(), and update().
m_lastMousePos
QPoint lmms::gui::LcdSpinBox::m_lastMousePos private
mouse position in last mouseMoveEvent
Definition at line 79 of file LcdSpinBox.h.
Referenced by LcdSpinBox(), LcdSpinBox(), mouseMoveEvent(), and mousePressEvent().
m_mouseMoving
bool lmms::gui::LcdSpinBox::m_mouseMoving private
Definition at line 78 of file LcdSpinBox.h.
Referenced by LcdSpinBox(), LcdSpinBox(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_remainder
float lmms::gui::LcdSpinBox::m_remainder private
floating offset of spinbox in [-0.5, 0.5]
Definition at line 77 of file LcdSpinBox.h.
Referenced by LcdSpinBox(), LcdSpinBox(), and mouseMoveEvent().
The documentation for this class was generated from the following files:
include/LcdSpinBox.h
src/gui/widgets/LcdSpinBox.cpp