LMMS: Jack::JackAtomicDelayLockedLoop Class Reference
Jack::JackAtomicDelayLockedLoop Class Reference
#include <JackFilters.h>
Public Member Functions
JackAtomicDelayLockedLoop (jack_nframes_t buffer_size, jack_nframes_t sample_rate)
jack_time_t Frames2Time (jack_nframes_t frames)
void IncFrame (jack_time_t callback_usecs)
void Init (jack_nframes_t buffer_size, jack_nframes_t sample_rate)
void Init (jack_time_t callback_usecs)
jack_nframes_t Time2Frames (jack_time_t time)
Public Member Functions inherited from Jack::JackAtomicState< JackDelayLockedLoop >
JackAtomicState ()
~JackAtomicState ()
UInt16 GetCurrentIndex ()
Returns the current state index.
bool IsPendingChange ()
JackDelayLockedLoop * ReadCurrentState ()
Returns the current state : only valid in the RT reader thread.
JackDelayLockedLoop * TrySwitchState ()
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
JackDelayLockedLoop * WriteNextStateStart ()
Start write operation : setup and returns the next state to update, check for recursive write calls.
void WriteNextStateStop ()
Stop write operation : make the next state ready to be used by the RT thread.
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAtomicState< JackDelayLockedLoop >
UInt32 WriteNextStateStartAux ()
void WriteNextStateStopAux ()
Protected Attributes inherited from Jack::JackAtomicState< JackDelayLockedLoop >
SInt32 fCallWriteCounter
volatile AtomicCounter fCounter
JackDelayLockedLoop fState [2]
Detailed Description
Definition at line 155 of file JackFilters.h.
Constructor & Destructor Documentation
JackAtomicDelayLockedLoop()
Jack::JackAtomicDelayLockedLoop::JackAtomicDelayLockedLoop (jack_nframes_t buffer_size, jack_nframes_t sample_rate) inline
Definition at line 159 of file JackFilters.h.
References Jack::JackAtomicState< JackDelayLockedLoop >::fState.
Member Function Documentation
Frames2Time()
jack_time_t Jack::JackAtomicDelayLockedLoop::Frames2Time (jack_nframes_t frames) inline
Definition at line 204 of file JackFilters.h.
References Jack::JackDelayLockedLoop::Frames2Time(), Jack::JackAtomicState< JackDelayLockedLoop >::GetCurrentIndex(), and Jack::JackAtomicState< JackDelayLockedLoop >::ReadCurrentState().
IncFrame()
void Jack::JackAtomicDelayLockedLoop::IncFrame (jack_time_t callback_usecs) inline
Definition at line 181 of file JackFilters.h.
References Jack::JackDelayLockedLoop::IncFrame(), Jack::JackAtomicState< JackDelayLockedLoop >::TrySwitchState(), Jack::JackAtomicState< JackDelayLockedLoop >::WriteNextStateStart(), and Jack::JackAtomicState< JackDelayLockedLoop >::WriteNextStateStop().
Init() [1/2]
void Jack::JackAtomicDelayLockedLoop::Init (jack_nframes_t buffer_size, jack_nframes_t sample_rate) inline
Definition at line 173 of file JackFilters.h.
References Jack::JackDelayLockedLoop::Init(), Jack::JackAtomicState< JackDelayLockedLoop >::TrySwitchState(), Jack::JackAtomicState< JackDelayLockedLoop >::WriteNextStateStart(), and Jack::JackAtomicState< JackDelayLockedLoop >::WriteNextStateStop().
Init() [2/2]
void Jack::JackAtomicDelayLockedLoop::Init (jack_time_t callback_usecs) inline
Definition at line 165 of file JackFilters.h.
References Jack::JackDelayLockedLoop::Init(), Jack::JackAtomicState< JackDelayLockedLoop >::TrySwitchState(), Jack::JackAtomicState< JackDelayLockedLoop >::WriteNextStateStart(), and Jack::JackAtomicState< JackDelayLockedLoop >::WriteNextStateStop().
Time2Frames()
jack_nframes_t Jack::JackAtomicDelayLockedLoop::Time2Frames (jack_time_t time) inline
Definition at line 189 of file JackFilters.h.
References Jack::JackAtomicState< JackDelayLockedLoop >::GetCurrentIndex(), Jack::JackAtomicState< JackDelayLockedLoop >::ReadCurrentState(), and Jack::JackDelayLockedLoop::Time2Frames().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackFilters.h