LMMS: Jack::JackAudioAdapter Class Reference
Jack::JackAudioAdapter Class Reference
Audio adapter : Jack client side.
#include <JackAudioAdapter.h>
Public Member Functions
JackAudioAdapter (jack_client_t *client, JackAudioAdapterInterface *audio_io, const JSList *params=NULL)
~JackAudioAdapter ()
int Close ()
int Open ()
Private Member Functions
void ConnectPorts ()
void FreePorts ()
int ProcessAux (jack_nframes_t frames)
void Reset ()
Static Private Member Functions
static int BufferSize (jack_nframes_t buffer_size, void *arg)
static void Latency (jack_latency_callback_mode_t mode, void *arg)
static int Process (jack_nframes_t, void *arg)
static int SampleRate (jack_nframes_t sample_rate, void *arg)
Private Attributes
JackAudioAdapterInterface * fAudioAdapter
bool fAutoConnect
jack_port_t ** fCapturePortList
jack_client_t * fClient
jack_default_audio_sample_t ** fInputBufferList
jack_default_audio_sample_t ** fOutputBufferList
jack_port_t ** fPlaybackPortList
Detailed Description
Audio adapter : Jack client side.
Definition at line 33 of file JackAudioAdapter.h.
Constructor & Destructor Documentation
JackAudioAdapter()
Jack::JackAudioAdapter::JackAudioAdapter (jack_client_t * client, JackAudioAdapterInterface * audio_io, const JSList * params = NULL)
Definition at line 93 of file JackAudioAdapter.cpp.
References jack_driver_param_t::character, client(), _JSList::data, fAudioAdapter, fAutoConnect, fClient, and jack_slist_next.
Referenced by BufferSize(), Latency(), Process(), and SampleRate().
~JackAudioAdapter()
Jack::JackAudioAdapter::~JackAudioAdapter ()
Definition at line 110 of file JackAudioAdapter.cpp.
References fAudioAdapter.
Member Function Documentation
BufferSize()
int Jack::JackAudioAdapter::BufferSize (jack_nframes_t buffer_size, void * arg) static private
Definition at line 57 of file JackAudioAdapter.cpp.
References JackAudioAdapter(), fAudioAdapter, Reset(), and Jack::JackAudioAdapterInterface::SetHostBufferSize().
Referenced by Open().
Close()
int Jack::JackAudioAdapter::Close ()
Definition at line 220 of file JackAudioAdapter.cpp.
References fAudioAdapter.
Referenced by jack_finish().
ConnectPorts()
void Jack::JackAudioAdapter::ConnectPorts () private
Definition at line 136 of file JackAudioAdapter.cpp.
References fAudioAdapter, fCapturePortList, fClient, fPlaybackPortList, i, jack_connect(), jack_free(), jack_get_ports(), jack_port_name(), JackPortIsInput, JackPortIsOutput, and JackPortIsPhysical.
Referenced by Open().
FreePorts()
void Jack::JackAudioAdapter::FreePorts () private
Definition at line 116 of file JackAudioAdapter.cpp.
References fAudioAdapter, fCapturePortList, fClient, fInputBufferList, fOutputBufferList, fPlaybackPortList, i, and jack_port_unregister().
Referenced by Open().
Latency()
void Jack::JackAudioAdapter::Latency (jack_latency_callback_mode_t mode, void * arg) static private
Definition at line 73 of file JackAudioAdapter.cpp.
References JackAudioAdapter(), fAudioAdapter, fCapturePortList, fPlaybackPortList, Jack::JackAudioAdapterInterface::GetInputLatency(), Jack::JackAudioAdapterInterface::GetInputs(), Jack::JackAudioAdapterInterface::GetOutputLatency(), Jack::JackAudioAdapterInterface::GetOutputs(), i, jack_port_set_latency_range(), JackCaptureLatency, JackPlaybackLatency, _jack_latency_range::max, and _jack_latency_range::min.
Referenced by Open().
Open()
int Jack::JackAudioAdapter::Open ()
Definition at line 162 of file JackAudioAdapter.cpp.
References BufferSize(), CaptureDriverFlags, ConnectPorts(), fAudioAdapter, fAutoConnect, fCapturePortList, fClient, fInputBufferList, fOutputBufferList, fPlaybackPortList, FreePorts(), i, jack_activate(), JACK_DEFAULT_AUDIO_TYPE, jack_log(), jack_port_register(), jack_set_buffer_size_callback(), jack_set_latency_callback(), jack_set_process_callback(), jack_set_sample_rate_callback(), Latency(), PlaybackDriverFlags, Process(), and SampleRate().
Referenced by jack_internal_initialize(), and jack_internal_initialize().
Process()
int Jack::JackAudioAdapter::Process (jack_nframes_t frames, void * arg) static private
Definition at line 35 of file JackAudioAdapter.cpp.
References JackAudioAdapter(), and ProcessAux().
Referenced by Open().
ProcessAux()
int Jack::JackAudioAdapter::ProcessAux (jack_nframes_t frames) private
Definition at line 41 of file JackAudioAdapter.cpp.
References fAudioAdapter, fCapturePortList, fInputBufferList, fOutputBufferList, fPlaybackPortList, i, and jack_port_get_buffer().
Referenced by Process().
Reset()
void Jack::JackAudioAdapter::Reset () private
Definition at line 157 of file JackAudioAdapter.cpp.
References fAudioAdapter.
Referenced by BufferSize(), and SampleRate().
SampleRate()
int Jack::JackAudioAdapter::SampleRate (jack_nframes_t sample_rate, void * arg) static private
Definition at line 65 of file JackAudioAdapter.cpp.
References JackAudioAdapter(), fAudioAdapter, Reset(), and Jack::JackAudioAdapterInterface::SetHostSampleRate().
Referenced by Open().
Member Data Documentation
fAudioAdapter
JackAudioAdapterInterface* Jack::JackAudioAdapter::fAudioAdapter private
Definition at line 49 of file JackAudioAdapter.h.
Referenced by JackAudioAdapter(), ~JackAudioAdapter(), BufferSize(), Close(), ConnectPorts(), FreePorts(), Latency(), Open(), ProcessAux(), Reset(), and SampleRate().
fAutoConnect
bool Jack::JackAudioAdapter::fAutoConnect private
Definition at line 50 of file JackAudioAdapter.h.
Referenced by JackAudioAdapter(), and Open().
fCapturePortList
jack_port_t** Jack::JackAudioAdapter::fCapturePortList private
Definition at line 42 of file JackAudioAdapter.h.
Referenced by ConnectPorts(), FreePorts(), Latency(), Open(), and ProcessAux().
fClient
jack_client_t* Jack::JackAudioAdapter::fClient private
Definition at line 48 of file JackAudioAdapter.h.
Referenced by JackAudioAdapter(), ConnectPorts(), FreePorts(), and Open().
fInputBufferList
jack_default_audio_sample_t** Jack::JackAudioAdapter::fInputBufferList private
Definition at line 45 of file JackAudioAdapter.h.
Referenced by FreePorts(), Open(), and ProcessAux().
fOutputBufferList
jack_default_audio_sample_t** Jack::JackAudioAdapter::fOutputBufferList private
Definition at line 46 of file JackAudioAdapter.h.
Referenced by FreePorts(), Open(), and ProcessAux().
fPlaybackPortList
jack_port_t** Jack::JackAudioAdapter::fPlaybackPortList private
Definition at line 43 of file JackAudioAdapter.h.
Referenced by ConnectPorts(), FreePorts(), Latency(), Open(), and ProcessAux().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackAudioAdapter.h
src/3rdparty/jack2/common/JackAudioAdapter.cpp