LMMS: lmms::TrackContainer Class Reference
lmms::TrackContainer Class Reference
#include <TrackContainer.h>
Public Types
using TrackList = std::vector<Track*>
enum class Type {
Pattern ,
Song
}
Signals
void trackAdded (lmms::Track *_track)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
TrackContainer ()
~TrackContainer () override
void addTrack (Track *_track)
virtual AutomatedValueMap automatedValuesAt (TimePos time, int clipNum=-1) const
void clearAllTracks ()
int countTracks (Track::Type _tt=Track::Type::Count) const
bool isEmpty () const
void loadSettings (const QDomElement &_this) override
void removeTrack (Track *_track)
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
void setType (Type newType)
const TrackList & tracks () const
Type type () const
virtual void updateAfterTrackAdd ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static const QString classNodeName ()
Static Protected Member Functions
static AutomatedValueMap automatedValuesFromTracks (const TrackList &tracks, TimePos timeStart, int clipNum=-1)
Protected Attributes
QReadWriteLock m_tracksMutex
Private Attributes
Type m_TrackContainerType
TrackList m_tracks
Friends
class gui::TrackContainerView
class Track
Additional Inherited Members
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 48 of file TrackContainer.h.
Member Typedef Documentation
TrackList
using lmms::TrackContainer::TrackList = std::vector<Track*>
Definition at line 52 of file TrackContainer.h.
Member Enumeration Documentation
Type
enum class lmms::TrackContainer::Type strong
Enumerator
Pattern
Song
Definition at line 53 of file TrackContainer.h.
Constructor & Destructor Documentation
TrackContainer()
lmms::TrackContainer::TrackContainer ()
Definition at line 48 of file TrackContainer.cpp.
References lmms::JournallingObject::JournallingObject(), lmms::Model::Model(), m_tracks, and m_tracksMutex.
Referenced by lmms::PatternStore::PatternStore(), lmms::Song::Song(), and lmms::Song::processAutomations().
~TrackContainer()
lmms::TrackContainer::~TrackContainer () override
Definition at line 59 of file TrackContainer.cpp.
References clearAllTracks().
Member Function Documentation
addTrack()
void lmms::TrackContainer::addTrack (Track * _track)
Definition at line 177 of file TrackContainer.cpp.
References lmms::Track::HiddenAutomation, lmms::Track::lock(), m_tracks, m_tracksMutex, Track, trackAdded(), lmms::Track::type(), and lmms::Track::unlock().
automatedValuesAt()
AutomatedValueMap lmms::TrackContainer::automatedValuesAt (TimePos time, int clipNum = -1) const virtual
Reimplemented in lmms::PatternStore, and lmms::Song.
Definition at line 253 of file TrackContainer.cpp.
References automatedValuesFromTracks(), and tracks().
Referenced by lmms::PatternStore::automatedValuesAt(), and lmms::Song::processAutomations().
automatedValuesFromTracks()
AutomatedValueMap lmms::TrackContainer::automatedValuesFromTracks (const TrackList & tracks, TimePos timeStart, int clipNum = -1) static protected
Definition at line 259 of file TrackContainer.cpp.
References lmms::Track::Automation, lmms::Clip::comparePosition(), lmms::Track::HiddenAutomation, lmms::Track::Pattern, lmms::PatternTrack::patternIndex(), lmms::Engine::patternStore(), lmms::TimePos::ticksPerBar(), Track, and tracks().
Referenced by lmms::Song::automatedValuesAt(), automatedValuesAt(), and trackAdded().
classNodeName()
const QString lmms::TrackContainer::classNodeName () inline static
Definition at line 83 of file TrackContainer.h.
Referenced by lmms::PatternTrack::loadTrackSpecificSettings(), and saveSettings().
clearAllTracks()
void lmms::TrackContainer::clearAllTracks ()
Definition at line 226 of file TrackContainer.cpp.
References m_tracks.
Referenced by ~TrackContainer(), lmms::Song::clearProject(), and loadSettings().
countTracks()
int lmms::TrackContainer::countTracks (Track::Type _tt = Track::Type::Count) const
Definition at line 159 of file TrackContainer.cpp.
References lmms::Track::Count, m_tracks, and m_tracksMutex.
Referenced by lmms::PatternStore::numOfPatterns().
isEmpty()
bool lmms::TrackContainer::isEmpty () const
Definition at line 239 of file TrackContainer.cpp.
References m_tracks.
Referenced by lmms::PathUtil::baseLocation().
loadSettings()
void lmms::TrackContainer::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 84 of file TrackContainer.cpp.
References clearAllTracks(), lmms::Track::create(), lmms::gui::TextFloat::displayMessage(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::Engine::getSong(), and lmms::Song::loadingCancelled().
removeTrack()
void lmms::TrackContainer::removeTrack (Track * _track)
Definition at line 193 of file TrackContainer.cpp.
References lmms::Engine::getSong(), m_tracks, m_tracksMutex, lmms::Song::setModified(), and Track.
Referenced by lmms::PatternTrack::~PatternTrack().
saveSettings()
void lmms::TrackContainer::saveSettings (QDomDocument & _doc, QDomElement & _parent) override virtual
Implements lmms::SerializingObject.
Definition at line 67 of file TrackContainer.cpp.
References classNodeName(), m_tracks, m_tracksMutex, and lmms::SerializingObject::nodeName().
setType()
void lmms::TrackContainer::setType (Type newType) inline
Definition at line 88 of file TrackContainer.h.
References m_TrackContainerType.
Referenced by lmms::PatternStore::PatternStore(), and lmms::Song::Song().
trackAdded
void lmms::TrackContainer::trackAdded (lmms::Track * _track) signal
References automatedValuesFromTracks(), and tracks().
Referenced by addTrack().
tracks()
const TrackList & lmms::TrackContainer::tracks () const inline
Definition at line 76 of file TrackContainer.h.
References m_tracks.
Referenced by lmms::Song::automatedValuesAt(), automatedValuesAt(), automatedValuesFromTracks(), lmms::gui::TrackContentWidget::canPasteSelection(), lmms::AutomationClip::combineAllTracks(), lmms::gui::ClipView::createClipDataFiles(), lmms::PatternStore::createClipsForPattern(), lmms::Mixer::deleteChannel(), lmms::Song::exportProjectMidi(), lmms::PatternStore::fixIncorrectPositions(), lmms::Song::insertBar(), lmms::Mixer::isChannelInUse(), lmms::PatternStore::lengthOfPattern(), lmms::gui::PatternEditor::makeSteps(), lmms::Mixer::moveChannelLeft(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::PatternStore::play(), lmms::Song::processAutomations(), lmms::Song::processNextBuffer(), lmms::Song::removeBar(), lmms::PatternStore::removePattern(), lmms::gui::PatternEditor::removeSteps(), lmms::RenderManager::renderTracks(), lmms::PatternStore::swapPattern(), trackAdded(), lmms::Song::updateLength(), lmms::gui::MixerView::updateMaxChannelSelector(), and lmms::gui::PatternEditor::updateMaxSteps().
type()
Type lmms::TrackContainer::type () const inline
Definition at line 93 of file TrackContainer.h.
References m_TrackContainerType.
Referenced by lmms::Clip::isInPattern().
updateAfterTrackAdd()
void lmms::TrackContainer::updateAfterTrackAdd () virtual
Reimplemented in lmms::PatternStore.
Definition at line 219 of file TrackContainer.cpp.
Referenced by lmms::Track::create().
Friends And Related Symbol Documentation
gui::TrackContainerView
friend class gui::TrackContainerView friend
Definition at line 114 of file TrackContainer.h.
Track
friend class Track friend
Definition at line 115 of file TrackContainer.h.
References Track.
Referenced by lmms::Song::Song(), lmms::Song::addPatternTrack(), addTrack(), automatedValuesFromTracks(), lmms::PatternStore::createClipsForPattern(), lmms::PatternStore::fixIncorrectPositions(), lmms::Song::insertBar(), lmms::PatternStore::lengthOfPattern(), lmms::PatternStore::play(), lmms::Song::processAutomations(), lmms::Song::removeBar(), lmms::PatternStore::removePattern(), removeTrack(), lmms::PatternStore::swapPattern(), and Track.
Member Data Documentation
m_TrackContainerType
Type lmms::TrackContainer::m_TrackContainerType private
Definition at line 111 of file TrackContainer.h.
Referenced by setType(), and type().
m_tracks
TrackList lmms::TrackContainer::m_tracks private
Definition at line 109 of file TrackContainer.h.
Referenced by TrackContainer(), addTrack(), clearAllTracks(), countTracks(), isEmpty(), removeTrack(), saveSettings(), and tracks().
m_tracksMutex
QReadWriteLock lmms::TrackContainer::m_tracksMutex mutable protected
Definition at line 106 of file TrackContainer.h.
Referenced by TrackContainer(), addTrack(), countTracks(), lmms::Song::insertBar(), lmms::Song::removeBar(), removeTrack(), saveSettings(), and lmms::Song::updateLength().
The documentation for this class was generated from the following files:
include/TrackContainer.h
src/core/TrackContainer.cpp