LMMS: lmms::gui::Control Class Reference
lmms::gui::Control Class Reference abstract
These classes provide.
#include <Controls.h>
Public Member Functions
virtual ~Control ()=default
virtual AutomatableModel * model ()=0
virtual AutomatableModelView * modelView ()=0
virtual void setModel (AutomatableModel *model)=0
virtual void setText (const QString &text)=0
virtual QWidget * topWidget ()=0
Detailed Description
These classes provide.
a control with a text label
a type safe way to set a model (justification: setting the wrong typed model to a widget will cause hard-to-find runtime errors)
Definition at line 55 of file Controls.h.
Constructor & Destructor Documentation
~Control()
virtual lmms::gui::Control::~Control () virtual default
Member Function Documentation
model()
virtual AutomatableModel * lmms::gui::Control::model () pure virtual
Implemented in lmms::gui::CheckControl, lmms::gui::ComboControl, lmms::gui::KnobControl, and lmms::gui::LcdControl.
Referenced by lmms::gui::LinkedModelGroupView::addControl(), and setModel().
modelView()
virtual AutomatableModelView * lmms::gui::Control::modelView () pure virtual
Implemented in lmms::gui::CheckControl, lmms::gui::ComboControl, lmms::gui::KnobControl, and lmms::gui::LcdControl.
setModel()
virtual void lmms::gui::Control::setModel (AutomatableModel * model) pure virtual
Implemented in lmms::gui::CheckControl, lmms::gui::ComboControl, lmms::gui::KnobControl, and lmms::gui::LcdControl.
References model().
setText()
virtual void lmms::gui::Control::setText (const QString & text) pure virtual
Implemented in lmms::gui::CheckControl, lmms::gui::ComboControl, lmms::gui::KnobControl, and lmms::gui::LcdControl.
topWidget()
virtual QWidget * lmms::gui::Control::topWidget () pure virtual
Implemented in lmms::gui::CheckControl, lmms::gui::ComboControl, lmms::gui::KnobControl, and lmms::gui::LcdControl.
Referenced by lmms::gui::LinkedModelGroupView::addControl().
The documentation for this class was generated from the following file:
include/Controls.h