LMMS: lmms::gui::SongEditor Class Reference
lmms::gui::SongEditor Class Reference
#include <SongEditor.h>
Public Types
enum class EditMode {
Draw ,
Knife ,
Select
}
Public Slots
void scrolled (int new_pos)
void selectAllClips (bool select)
void selectRegionFromPixels (int xStart, int xEnd)
void setEditMode (lmms::gui::SongEditor::EditMode mode)
void setEditModeDraw ()
void setEditModeKnife ()
void setEditModeSelect ()
void stopSelectRegion ()
void toggleProportionalSnap ()
void updatePosition (const lmms::TimePos &t)
void updatePositionLine ()
void updateRubberband ()
Public Slots inherited from lmms::gui::TrackContainerView
lmms::gui::TrackView * createTrackView (lmms::Track *_t)
void deleteTrackView (lmms::gui::TrackView *_tv)
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void realignTracks ()
void stopRubberBand ()
stopRubberBand Removes the rubber band from display when finished with.
Signals
void pixelsPerBarChanged (float)
void proportionalSnapChanged ()
Signals inherited from lmms::gui::TrackContainerView
void positionChanged (const lmms::TimePos &_pos)
void tracksRealigned ()
Public Member Functions
SongEditor (Song *song)
~SongEditor () override=default
float getSnapSize () const
Return grid size as number of bars.
QString getSnapSizeString () const
void loadSettings (const QDomElement &element) override
void saveSettings (QDomDocument &doc, QDomElement &element) override
ComboBoxModel * snappingModel () const
Public Member Functions inherited from lmms::gui::TrackContainerView
TrackContainerView (TrackContainer *tc)
~TrackContainerView () override
TrackView * addTrackView (TrackView *_tv)
void clearAllTracks ()
QScrollArea * contentWidget ()
const TimePos & currentPosition () const
virtual bool fixedClips () const
void loadSettings (const QDomElement &_this) override
TrackContainer * model ()
const TrackContainer * model () const
void moveTrackView (TrackView *trackView, int indexTo)
void moveTrackViewDown (TrackView *trackView)
void moveTrackViewUp (TrackView *trackView)
QString nodeName () const override
float pixelsPerBar () const
void removeTrackView (TrackView *_tv)
RubberBand * rubberBand () const
bool rubberBandActive () const
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
void scrollToTrackView (TrackView *_tv)
QVector< selectableObject * > selectedObjects ()
void setPixelsPerBar (int ppb)
unsigned int totalHeightOfTracks () const
const TrackView * trackViewAt (const int _y) const
const QList< TrackView * > & trackViews () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Public Member Functions inherited from lmms::SerializingObjectHook
SerializingObjectHook ()
virtual ~SerializingObjectHook ()
Protected Member Functions
void closeEvent (QCloseEvent *ce) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Slots
void hideMasterPitchFloat ()
void hideMasterVolumeFloat ()
void setMasterPitch (int new_val)
void setMasterVolume (int new_val)
void showMasterPitchFloat ()
void showMasterVolumeFloat ()
void updateMasterPitchFloat (int new_val)
void updateMasterVolumeFloat (int new_val)
void updateScrollBar (int len)
void zoomingChanged ()
Private Member Functions
void adjustLeftRightScoll (int value)
bool allowRubberband () const override
int calculatePixelsPerBar () const
Convert zoom slider's value to bar width in pixels.
int calculateZoomSliderValue (int pixelsPerBar) const
Convert bar width in pixels to zoom slider value.
int indexOfTrackView (const TrackView *tv)
void keyPressEvent (QKeyEvent *ke) override
bool knifeMode () const override
int trackIndexFromSelectionPoint (int yPos)
void wheelEvent (QWheelEvent *we) override
Private Attributes
EditMode m_ctrlMode
QScrollBar * m_leftRightScroll
AutomatableSlider * m_masterPitchSlider
AutomatableSlider * m_masterVolumeSlider
EditMode m_mode
QPoint m_mousePos
TextFloat * m_mpsStatus
TextFloat * m_mvsStatus
QPoint m_origin
PositionLine * m_positionLine
bool m_proportionalSnap
int m_rubberbandPixelsPerBar
pixels per bar when selection starts
TimePos m_rubberbandStartTimePos
int m_rubberBandStartTrackview
bool m_scrollBack
QPoint m_scrollPos
bool m_selectRegion
bool m_smoothScroll
ComboBoxModel * m_snappingModel
Song * m_song
LcdSpinBox * m_tempoSpinBox
TimeLineWidget * m_timeLine
MeterDialog * m_timeSigDisplay
int m_trackHeadWidth
IntModel * m_zoomingModel
Friends
class SongEditorWindow
Additional Inherited Members
Protected Attributes inherited from lmms::gui::TrackContainerView
TimePos m_currentPosition
Static Protected Attributes inherited from lmms::gui::TrackContainerView
static const int DEFAULT_PIXELS_PER_BAR = 128
Detailed Description
Definition at line 56 of file SongEditor.h.
Member Enumeration Documentation
EditMode
enum class lmms::gui::SongEditor::EditMode strong
Enumerator
Draw
Knife
Select
Definition at line 60 of file SongEditor.h.
Constructor & Destructor Documentation
SongEditor()
lmms::gui::SongEditor::SongEditor (Song * song)
Definition at line 77 of file SongEditor.cpp.
References lmms::Song::Song, lmms::gui::TrackContainerView::TrackContainerView(), lmms::gui::MainWindow::addSpacingToToolBar(), lmms::gui::MainWindow::addWidgetToToolBar(), calculateZoomSliderValue(), lmms::gui::TrackContainerView::contentWidget(), lmms::Model::dataChanged(), lmms::gui::TrackContainerView::DEFAULT_PIXELS_PER_BAR, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT, lmms::gui::getGUI(), lmms::embed::getIconPixmap(), getSnapSize(), hideMasterPitchFloat(), hideMasterVolumeFloat(), lmms::gui::TrackContainerView::m_currentPosition, m_leftRightScroll, m_masterPitchSlider, m_masterVolumeSlider, m_mode, m_mousePos, m_mpsStatus, m_mvsStatus, m_origin, m_positionLine, m_proportionalSnap, m_rubberbandPixelsPerBar, m_rubberbandStartTimePos, m_rubberBandStartTrackview, m_scrollBack, m_scrollPos, m_selectRegion, m_smoothScroll, m_snappingModel, m_song, m_tempoSpinBox, m_timeLine, m_timeSigDisplay, m_trackHeadWidth, m_zoomingModel, lmms::gui::GuiApplication::mainWindow(), lmms::gui::TrackContainerView::pixelsPerBar(), pixelsPerBarChanged(), lmms::gui::TrackContainerView::positionChanged(), scrolled(), selectRegionFromPixels(), setMasterPitch(), setMasterVolume(), showMasterPitchFloat(), showMasterVolumeFloat(), lmms::gui::TrackContainerView::stopRubberBand(), stopSelectRegion(), lmms::TimePos::ticksPerBar(), lmms::gui::MainWindow::toolBar(), lmms::gui::TRACK_OP_WIDTH, lmms::gui::TRACK_OP_WIDTH_COMPACT, lmms::gui::TrackContainerView::tracksRealigned(), updateMasterPitchFloat(), updateMasterVolumeFloat(), updatePosition(), lmms::gui::TimeLineWidget::updatePosition(), updatePositionLine(), updateRubberband(), updateScrollBar(), and zoomingChanged().
~SongEditor()
lmms::gui::SongEditor::~SongEditor () override default
References lmms::gui::TrackContainerView::pixelsPerBar().
Member Function Documentation
adjustLeftRightScoll()
void lmms::gui::SongEditor::adjustLeftRightScoll (int value) private
Definition at line 522 of file SongEditor.cpp.
References lmms::gui::TrackContainerView::DEFAULT_PIXELS_PER_BAR, m_leftRightScroll, and lmms::gui::TrackContainerView::pixelsPerBar().
Referenced by wheelEvent().
allowRubberband()
bool lmms::gui::SongEditor::allowRubberband () const override private virtual
Reimplemented from lmms::gui::TrackContainerView.
Definition at line 873 of file SongEditor.cpp.
References m_mode, and Select.
Referenced by mousePressEvent().
calculatePixelsPerBar()
int lmms::gui::SongEditor::calculatePixelsPerBar () const private
Convert zoom slider's value to bar width in pixels.
Definition at line 815 of file SongEditor.cpp.
References m_zoomingModel.
Referenced by zoomingChanged().
calculateZoomSliderValue()
int lmms::gui::SongEditor::calculateZoomSliderValue (int pixelsPerBar) const private
Convert bar width in pixels to zoom slider value.
Definition at line 832 of file SongEditor.cpp.
References lmms::gui::TrackContainerView::pixelsPerBar().
Referenced by SongEditor().
closeEvent()
void lmms::gui::SongEditor::closeEvent (QCloseEvent * ce) override protected
Definition at line 572 of file SongEditor.cpp.
getSnapSize()
float lmms::gui::SongEditor::getSnapSize () const
Return grid size as number of bars.
Definition at line 292 of file SongEditor.cpp.
References lmms::gui::TrackContainerView::DEFAULT_PIXELS_PER_BAR, m_proportionalSnap, m_snappingModel, and lmms::gui::TrackContainerView::pixelsPerBar().
Referenced by SongEditor(), lmms::gui::SampleTrackView::dropEvent(), getSnapSizeString(), lmms::gui::TrackContentWidget::mousePressEvent(), lmms::gui::TrackContentWidget::pasteSelection(), toggleProportionalSnap(), lmms::gui::TrackContentWidget::updateBackground(), and zoomingChanged().
getSnapSizeString()
QString lmms::gui::SongEditor::getSnapSizeString () const
Definition at line 310 of file SongEditor.cpp.
References getSnapSize().
hideMasterPitchFloat
void lmms::gui::SongEditor::hideMasterPitchFloat (void) private slot
Definition at line 713 of file SongEditor.cpp.
References m_mpsStatus.
Referenced by SongEditor().
hideMasterVolumeFloat
void lmms::gui::SongEditor::hideMasterVolumeFloat (void) private slot
Definition at line 670 of file SongEditor.cpp.
References m_mvsStatus.
Referenced by SongEditor().
indexOfTrackView()
int lmms::gui::SongEditor::indexOfTrackView (const TrackView * tv) private
Definition at line 900 of file SongEditor.cpp.
References lmms::gui::TrackContainerView::trackViews().
Referenced by trackIndexFromSelectionPoint(), and updateRubberband().
keyPressEvent()
void lmms::gui::SongEditor::keyPressEvent (QKeyEvent * ke) override private
Definition at line 460 of file SongEditor.cpp.
References lmms::Song::Song, m_song, m_zoomingModel, lmms::MaxSongLength, lmms::gui::ClipView::remove(), selectAllClips(), lmms::gui::TrackContainerView::selectedObjects(), and lmms::TimePos::ticksPerBar().
knifeMode()
bool lmms::gui::SongEditor::knifeMode () const override private virtual
Reimplemented from lmms::gui::TrackContainerView.
Definition at line 881 of file SongEditor.cpp.
References Knife, and m_mode.
loadSettings()
void lmms::gui::SongEditor::loadSettings (const QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 283 of file SongEditor.cpp.
References lmms::gui::MainWindow::restoreWidgetState().
mouseMoveEvent()
void lmms::gui::SongEditor::mouseMoveEvent (QMouseEvent * me) override protected
Definition at line 614 of file SongEditor.cpp.
References m_mousePos, and updateRubberband().
mousePressEvent()
void lmms::gui::SongEditor::mousePressEvent (QMouseEvent * me) override protected
Definition at line 588 of file SongEditor.cpp.
References allowRubberband(), lmms::gui::TrackContainerView::contentWidget(), lmms::gui::TrackContainerView::m_currentPosition, m_leftRightScroll, m_origin, m_rubberbandPixelsPerBar, m_rubberbandStartTimePos, m_rubberBandStartTrackview, m_scrollPos, m_trackHeadWidth, lmms::gui::TrackContainerView::pixelsPerBar(), lmms::gui::TrackContainerView::rubberBand(), lmms::TimePos::ticksPerBar(), and trackIndexFromSelectionPoint().
mouseReleaseEvent()
void lmms::gui::SongEditor::mouseReleaseEvent (QMouseEvent * me) override protected
Definition at line 624 of file SongEditor.cpp.
References lmms::gui::TrackContainerView::rubberBand().
pixelsPerBarChanged
void lmms::gui::SongEditor::pixelsPerBarChanged (float) signal
Referenced by lmms::gui::ClipView::ClipView(), SongEditor(), and zoomingChanged().
proportionalSnapChanged
void lmms::gui::SongEditor::proportionalSnapChanged () signal
Referenced by lmms::gui::TrackContentWidget::TrackContentWidget(), and toggleProportionalSnap().
saveSettings()
void lmms::gui::SongEditor::saveSettings (QDomDocument & doc, QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 278 of file SongEditor.cpp.
References lmms::gui::MainWindow::saveWidgetState().
scrolled
void lmms::gui::SongEditor::scrolled (int new_pos) slot
Definition at line 328 of file SongEditor.cpp.
References lmms::gui::TrackContainerView::m_currentPosition, and lmms::gui::TrackContainerView::positionChanged().
Referenced by SongEditor().
selectAllClips
void lmms::gui::SongEditor::selectAllClips (bool select) slot
Definition at line 861 of file SongEditor.cpp.
References i, lmms::gui::TrackContainerView::rubberBand(), lmms::gui::RubberBand::selectableObjects(), and lmms::gui::RubberBand::selectedObjects().
Referenced by keyPressEvent().
selectRegionFromPixels
void lmms::gui::SongEditor::selectRegionFromPixels (int xStart, int xEnd) slot
Definition at line 337 of file SongEditor.cpp.
References lmms::gui::TrackContainerView::contentWidget(), lmms::gui::TrackContainerView::m_currentPosition, m_leftRightScroll, m_mousePos, m_origin, m_rubberbandPixelsPerBar, m_rubberbandStartTimePos, m_rubberBandStartTrackview, m_scrollPos, m_selectRegion, m_trackHeadWidth, lmms::gui::TrackContainerView::pixelsPerBar(), lmms::gui::TrackContainerView::rubberBand(), lmms::TimePos::ticksPerBar(), and updateRubberband().
Referenced by SongEditor().
setEditMode
void lmms::gui::SongEditor::setEditMode (lmms::gui::SongEditor::EditMode mode) slot
Definition at line 429 of file SongEditor.cpp.
References m_mode.
Referenced by lmms::gui::TrackContentWidget::mousePressEvent(), setEditModeDraw(), setEditModeKnife(), and setEditModeSelect().
setEditModeDraw
void lmms::gui::SongEditor::setEditModeDraw () slot
Definition at line 434 of file SongEditor.cpp.
References Draw, and setEditMode().
setEditModeKnife
void lmms::gui::SongEditor::setEditModeKnife () slot
Definition at line 439 of file SongEditor.cpp.
References Knife, and setEditMode().
setEditModeSelect
void lmms::gui::SongEditor::setEditModeSelect () slot
Definition at line 444 of file SongEditor.cpp.
References Select, and setEditMode().
setMasterPitch
void lmms::gui::SongEditor::setMasterPitch (int new_val) private slot
Definition at line 678 of file SongEditor.cpp.
References m_masterPitchSlider, m_mpsStatus, m_song, and updateMasterPitchFloat().
Referenced by SongEditor().
setMasterVolume
void lmms::gui::SongEditor::setMasterVolume (int new_val) private slot
Definition at line 634 of file SongEditor.cpp.
References lmms::Engine::audioEngine(), m_masterVolumeSlider, m_mvsStatus, m_song, lmms::AudioEngine::setMasterGain(), and updateMasterVolumeFloat().
Referenced by SongEditor().
showMasterPitchFloat
void lmms::gui::SongEditor::showMasterPitchFloat (void) private slot
Definition at line 693 of file SongEditor.cpp.
References m_masterPitchSlider, m_mpsStatus, m_song, and updateMasterPitchFloat().
Referenced by SongEditor().
showMasterVolumeFloat
void lmms::gui::SongEditor::showMasterVolumeFloat (void) private slot
Definition at line 651 of file SongEditor.cpp.
References m_masterVolumeSlider, m_mvsStatus, m_song, and updateMasterVolumeFloat().
Referenced by SongEditor().
snappingModel()
ComboBoxModel * lmms::gui::SongEditor::snappingModel () const
Definition at line 909 of file SongEditor.cpp.
References m_snappingModel.
stopSelectRegion
void lmms::gui::SongEditor::stopSelectRegion () slot
Definition at line 369 of file SongEditor.cpp.
References m_selectRegion.
Referenced by SongEditor().
toggleProportionalSnap
void lmms::gui::SongEditor::toggleProportionalSnap () slot
Definition at line 449 of file SongEditor.cpp.
References getSnapSize(), m_proportionalSnap, m_timeLine, and proportionalSnapChanged().
trackIndexFromSelectionPoint()
int lmms::gui::SongEditor::trackIndexFromSelectionPoint (int yPos) private
Definition at line 889 of file SongEditor.cpp.
References indexOfTrackView(), m_timeLine, lmms::gui::TrackContainerView::trackViewAt(), and lmms::gui::TrackContainerView::trackViews().
Referenced by mousePressEvent(), and updateRubberband().
updateMasterPitchFloat
void lmms::gui::SongEditor::updateMasterPitchFloat (int new_val) private slot
Definition at line 704 of file SongEditor.cpp.
References m_mpsStatus.
Referenced by SongEditor(), setMasterPitch(), and showMasterPitchFloat().
updateMasterVolumeFloat
void lmms::gui::SongEditor::updateMasterVolumeFloat (int new_val) private slot
Definition at line 662 of file SongEditor.cpp.
References m_mvsStatus.
Referenced by SongEditor(), setMasterVolume(), and showMasterVolumeFloat().
updatePosition
void lmms::gui::SongEditor::updatePosition (const lmms::TimePos & t) slot
Definition at line 760 of file SongEditor.cpp.
References lmms::Song::Song, lmms::gui::animateScroll(), lmms::gui::TrackContainerView::contentWidget(), lmms::gui::TimeLineWidget::Continuous, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT, lmms::TimePos::getTicks(), lmms::ConfigManager::inst(), lmms::gui::TrackContainerView::m_currentPosition, m_leftRightScroll, m_positionLine, m_scrollBack, m_smoothScroll, m_song, m_timeLine, lmms::gui::TrackContainerView::pixelsPerBar(), lmms::gui::TimeLineWidget::Stepped, lmms::TimePos::ticksPerBar(), lmms::gui::TRACK_OP_WIDTH, lmms::gui::TRACK_OP_WIDTH_COMPACT, updatePositionLine(), and lmms::ConfigManager::value().
Referenced by SongEditor().
updatePositionLine
void lmms::gui::SongEditor::updatePositionLine () slot
Definition at line 806 of file SongEditor.cpp.
References m_positionLine, and lmms::gui::TrackContainerView::totalHeightOfTracks().
Referenced by SongEditor(), and updatePosition().
updateRubberband
void lmms::gui::SongEditor::updateRubberband () slot
Definition at line 377 of file SongEditor.cpp.
References lmms::gui::TrackContainerView::contentWidget(), indexOfTrackView(), lmms::gui::TrackContainerView::m_currentPosition, m_leftRightScroll, m_mousePos, m_origin, m_rubberbandPixelsPerBar, m_rubberbandStartTimePos, m_rubberBandStartTrackview, m_scrollPos, m_trackHeadWidth, lmms::gui::TrackContainerView::pixelsPerBar(), lmms::gui::TrackContainerView::rubberBand(), lmms::gui::TrackContainerView::rubberBandActive(), lmms::TimePos::ticksPerBar(), trackIndexFromSelectionPoint(), and lmms::gui::TrackContainerView::trackViews().
Referenced by SongEditor(), mouseMoveEvent(), selectRegionFromPixels(), and zoomingChanged().
updateScrollBar
void lmms::gui::SongEditor::updateScrollBar (int len) private slot
Definition at line 721 of file SongEditor.cpp.
References m_leftRightScroll, and lmms::TimePos::ticksPerBar().
Referenced by SongEditor().
wheelEvent()
void lmms::gui::SongEditor::wheelEvent (QWheelEvent * we) override private
Definition at line 529 of file SongEditor.cpp.
References adjustLeftRightScoll(), m_leftRightScroll, m_timeLine, m_trackHeadWidth, m_zoomingModel, lmms::gui::TrackContainerView::pixelsPerBar(), lmms::position(), lmms::gui::TrackContainerView::realignTracks(), and lmms::TimePos::ticksPerBar().
zoomingChanged
void lmms::gui::SongEditor::zoomingChanged () private slot
Definition at line 847 of file SongEditor.cpp.
References calculatePixelsPerBar(), getSnapSize(), m_timeLine, pixelsPerBarChanged(), lmms::gui::TrackContainerView::realignTracks(), lmms::gui::TrackContainerView::setPixelsPerBar(), and updateRubberband().
Referenced by SongEditor().
Friends And Related Symbol Documentation
SongEditorWindow
friend class SongEditorWindow friend
Definition at line 165 of file SongEditor.h.
References SongEditorWindow.
Referenced by SongEditorWindow.
Member Data Documentation
m_ctrlMode
EditMode lmms::gui::SongEditor::m_ctrlMode private
Definition at line 154 of file SongEditor.h.
m_leftRightScroll
QScrollBar* lmms::gui::SongEditor::m_leftRightScroll private
Definition at line 129 of file SongEditor.h.
Referenced by SongEditor(), adjustLeftRightScoll(), mousePressEvent(), selectRegionFromPixels(), updatePosition(), updateRubberband(), updateScrollBar(), and wheelEvent().
m_masterPitchSlider
AutomatableSlider* lmms::gui::SongEditor::m_masterPitchSlider private
Definition at line 139 of file SongEditor.h.
Referenced by SongEditor(), setMasterPitch(), and showMasterPitchFloat().
m_masterVolumeSlider
AutomatableSlider* lmms::gui::SongEditor::m_masterVolumeSlider private
Definition at line 138 of file SongEditor.h.
Referenced by SongEditor(), setMasterVolume(), and showMasterVolumeFloat().
m_mode
EditMode lmms::gui::SongEditor::m_mode private
Definition at line 153 of file SongEditor.h.
Referenced by SongEditor(), allowRubberband(), knifeMode(), and setEditMode().
m_mousePos
QPoint lmms::gui::SongEditor::m_mousePos private
Definition at line 158 of file SongEditor.h.
Referenced by SongEditor(), mouseMoveEvent(), selectRegionFromPixels(), and updateRubberband().
m_mpsStatus
TextFloat* lmms::gui::SongEditor::m_mpsStatus private
Definition at line 142 of file SongEditor.h.
Referenced by SongEditor(), hideMasterPitchFloat(), setMasterPitch(), showMasterPitchFloat(), and updateMasterPitchFloat().
m_mvsStatus
TextFloat* lmms::gui::SongEditor::m_mvsStatus private
Definition at line 141 of file SongEditor.h.
Referenced by SongEditor(), hideMasterVolumeFloat(), setMasterVolume(), showMasterVolumeFloat(), and updateMasterVolumeFloat().
m_origin
QPoint lmms::gui::SongEditor::m_origin private
Definition at line 156 of file SongEditor.h.
Referenced by SongEditor(), mousePressEvent(), selectRegionFromPixels(), and updateRubberband().
m_positionLine
PositionLine* lmms::gui::SongEditor::m_positionLine private
Definition at line 144 of file SongEditor.h.
Referenced by SongEditor(), updatePosition(), and updatePositionLine().
m_proportionalSnap
bool lmms::gui::SongEditor::m_proportionalSnap private
Definition at line 148 of file SongEditor.h.
Referenced by SongEditor(), getSnapSize(), and toggleProportionalSnap().
m_rubberbandPixelsPerBar
int lmms::gui::SongEditor::m_rubberbandPixelsPerBar private
pixels per bar when selection starts
Definition at line 161 of file SongEditor.h.
Referenced by SongEditor(), mousePressEvent(), selectRegionFromPixels(), and updateRubberband().
m_rubberbandStartTimePos
TimePos lmms::gui::SongEditor::m_rubberbandStartTimePos private
Definition at line 160 of file SongEditor.h.
Referenced by SongEditor(), mousePressEvent(), selectRegionFromPixels(), and updateRubberband().
m_rubberBandStartTrackview
int lmms::gui::SongEditor::m_rubberBandStartTrackview private
Definition at line 159 of file SongEditor.h.
Referenced by SongEditor(), mousePressEvent(), selectRegionFromPixels(), and updateRubberband().
m_scrollBack
bool lmms::gui::SongEditor::m_scrollBack private
Definition at line 150 of file SongEditor.h.
Referenced by SongEditor(), and updatePosition().
m_scrollPos
QPoint lmms::gui::SongEditor::m_scrollPos private
Definition at line 157 of file SongEditor.h.
Referenced by SongEditor(), mousePressEvent(), selectRegionFromPixels(), and updateRubberband().
m_selectRegion
bool lmms::gui::SongEditor::m_selectRegion private
Definition at line 163 of file SongEditor.h.
Referenced by SongEditor(), selectRegionFromPixels(), and stopSelectRegion().
m_smoothScroll
bool lmms::gui::SongEditor::m_smoothScroll private
Definition at line 151 of file SongEditor.h.
Referenced by SongEditor(), and updatePosition().
m_snappingModel
ComboBoxModel* lmms::gui::SongEditor::m_snappingModel private
Definition at line 147 of file SongEditor.h.
Referenced by SongEditor(), getSnapSize(), and snappingModel().
m_song
Song* lmms::gui::SongEditor::m_song private
Definition at line 127 of file SongEditor.h.
Referenced by SongEditor(), keyPressEvent(), setMasterPitch(), setMasterVolume(), showMasterPitchFloat(), showMasterVolumeFloat(), and updatePosition().
m_tempoSpinBox
LcdSpinBox* lmms::gui::SongEditor::m_tempoSpinBox private
Definition at line 133 of file SongEditor.h.
Referenced by SongEditor().
m_timeLine
TimeLineWidget* lmms::gui::SongEditor::m_timeLine private
Definition at line 135 of file SongEditor.h.
Referenced by SongEditor(), toggleProportionalSnap(), trackIndexFromSelectionPoint(), updatePosition(), wheelEvent(), and zoomingChanged().
m_timeSigDisplay
MeterDialog* lmms::gui::SongEditor::m_timeSigDisplay private
Definition at line 137 of file SongEditor.h.
Referenced by SongEditor().
m_trackHeadWidth
int lmms::gui::SongEditor::m_trackHeadWidth private
Definition at line 162 of file SongEditor.h.
Referenced by SongEditor(), mousePressEvent(), selectRegionFromPixels(), updateRubberband(), and wheelEvent().
m_zoomingModel
IntModel* lmms::gui::SongEditor::m_zoomingModel private
Definition at line 146 of file SongEditor.h.
Referenced by SongEditor(), calculatePixelsPerBar(), keyPressEvent(), and wheelEvent().
The documentation for this class was generated from the following files:
include/SongEditor.h
src/gui/editors/SongEditor.cpp