LMMS: hiir::HalfBandF64Sse2< NC > Class Template Reference
hiir::HalfBandF64Sse2< NC > Class Template Reference
#include <HalfBandF64Sse2.h>
Public Types
typedef double DataType
Public Member Functions
HalfBandF64Sse2 () noexcept
HalfBandF64Sse2 (const HalfBandF64Sse2< NC > &other)=default
HalfBandF64Sse2 (HalfBandF64Sse2< NC > &&other)=default
~HalfBandF64Sse2 ()=default
void clear_buffers () noexcept
HalfBandF64Sse2< NC > & operator= (const HalfBandF64Sse2< NC > &other)=default
HalfBandF64Sse2< NC > & operator= (HalfBandF64Sse2< NC > &&other)=default
void process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
void process_block_2_paths (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_hpf (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
void process_block_split (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE double process_sample (double input) noexcept
hiir_FORCEINLINE double process_sample_hpf (double input) noexcept
hiir_FORCEINLINE void process_sample_split (double &low, double &high, double input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Sse2, _nbr_stages+1 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const HalfBandF64Sse2< NC > &other)=delete
bool operator== (const HalfBandF64Sse2< NC > &other)=delete
hiir_FORCEINLINE std::array< double, 2 > process_2_paths (double input) noexcept
template<typename FL, typename FH>
hiir_FORCEINLINE void process_block_2_paths (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (double *, double, double) noexcept
static hiir_FORCEINLINE void store_high (double *ptr, double even, double odd) noexcept
static hiir_FORCEINLINE void store_low (double *ptr, double even, double odd) noexcept
Private Attributes
FilterBiPhase _bifilter
int _phase
double _prev
Static Private Attributes
static constexpr int _nbr_phases = 2
static constexpr int _nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::HalfBandF64Sse2< NC >
Definition at line 48 of file HalfBandF64Sse2.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::HalfBandF64Sse2< NC >::DataType
Definition at line 57 of file HalfBandF64Sse2.h.
Filter
template<int NC> typedef std::array<StageDataF64Sse2, _nbr_stages + 1> hiir::HalfBandF64Sse2< NC >::Filter private
Definition at line 105 of file HalfBandF64Sse2.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::HalfBandF64Sse2< NC >::FilterBiPhase private
Definition at line 106 of file HalfBandF64Sse2.h.
Constructor & Destructor Documentation
HalfBandF64Sse2() [1/3]
template<int NC> hiir::HalfBandF64Sse2< NC >::HalfBandF64Sse2 () noexcept
Definition at line 59 of file HalfBandF64Sse2.hpp.
References _bifilter, _nbr_phases, _nbr_stages, _phase, _prev, clear_buffers(), i, and NBR_COEFS.
Referenced by HalfBandF64Sse2(), HalfBandF64Sse2(), ~HalfBandF64Sse2(), operator=(), and operator=().
HalfBandF64Sse2() [2/3]
template<int NC> hiir::HalfBandF64Sse2< NC >::HalfBandF64Sse2 (const HalfBandF64Sse2< NC > & other) default
References HalfBandF64Sse2().
HalfBandF64Sse2() [3/3]
template<int NC> hiir::HalfBandF64Sse2< NC >::HalfBandF64Sse2 (HalfBandF64Sse2< NC > && other) default
References HalfBandF64Sse2().
~HalfBandF64Sse2()
template<int NC> hiir::HalfBandF64Sse2< NC >::~HalfBandF64Sse2 () default
References HalfBandF64Sse2().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::HalfBandF64Sse2< NC >::bypass (double * , double , double) inline static private noexcept
Definition at line 119 of file HalfBandF64Sse2.h.
References bypass().
Referenced by bypass(), process_block(), and process_block_hpf().
clear_buffers()
template<int NC> void hiir::HalfBandF64Sse2< NC >::clear_buffers () noexcept
Definition at line 289 of file HalfBandF64Sse2.hpp.
References _bifilter, _nbr_phases, _nbr_stages, _phase, _prev, and i.
Referenced by HalfBandF64Sse2(), and operator=().
operator!=()
template<int NC> bool hiir::HalfBandF64Sse2< NC >::operator!= (const HalfBandF64Sse2< NC > & other) private delete
operator=() [1/2]
template<int NC> HalfBandF64Sse2< NC > & hiir::HalfBandF64Sse2< NC >::operator= (const HalfBandF64Sse2< NC > & other) default
References HalfBandF64Sse2().
operator=() [2/2]
template<int NC> HalfBandF64Sse2< NC > & hiir::HalfBandF64Sse2< NC >::operator= (HalfBandF64Sse2< NC > && other) default
References HalfBandF64Sse2(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_hpf(), process_block_split(), process_sample(), process_sample_hpf(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::HalfBandF64Sse2< NC >::operator== (const HalfBandF64Sse2< NC > & other) private delete
process_2_paths()
template<int NC> std::array< double, 2 > hiir::HalfBandF64Sse2< NC >::process_2_paths (double input) private noexcept
Definition at line 325 of file HalfBandF64Sse2.hpp.
References _bifilter, _phase, _prev, and hiir::StageProcF64Sse2< CUR >::process_sample_pos().
Referenced by process_block_2_paths(), process_sample(), process_sample_hpf(), and process_sample_split().
process_block()
template<int NC> void hiir::HalfBandF64Sse2< NC >::process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 152 of file HalfBandF64Sse2.hpp.
References _nbr_chn, bypass(), process_block_2_paths(), and store_low().
Referenced by operator=().
process_block_2_paths() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE void hiir::HalfBandF64Sse2< NC >::process_block_2_paths (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE, process_block_2_paths(), store_high(), and store_low().
Referenced by process_block(), process_block_2_paths(), process_block_hpf(), and process_block_split().
process_block_2_paths() [2/2]
template<int NC> template<typename FL, typename FH> void hiir::HalfBandF64Sse2< NC >::process_block_2_paths (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 347 of file HalfBandF64Sse2.hpp.
References _bifilter, _nbr_phases, _phase, _prev, pos, process_2_paths(), and hiir::StageProcF64Sse2< CUR >::process_sample_pos().
process_block_hpf()
template<int NC> void hiir::HalfBandF64Sse2< NC >::process_block_hpf (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 203 of file HalfBandF64Sse2.hpp.
References _nbr_chn, bypass(), process_block_2_paths(), and store_high().
Referenced by operator=().
process_block_split()
template<int NC> void hiir::HalfBandF64Sse2< NC >::process_block_split (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 262 of file HalfBandF64Sse2.hpp.
References _nbr_chn, process_block_2_paths(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> double hiir::HalfBandF64Sse2< NC >::process_sample (double input) noexcept
Definition at line 126 of file HalfBandF64Sse2.hpp.
References process_2_paths().
Referenced by operator=().
process_sample_hpf()
template<int NC> double hiir::HalfBandF64Sse2< NC >::process_sample_hpf (double input) noexcept
Definition at line 177 of file HalfBandF64Sse2.hpp.
References process_2_paths().
Referenced by operator=().
process_sample_split()
template<int NC> void hiir::HalfBandF64Sse2< NC >::process_sample_split (double & low, double & high, double input) noexcept
Definition at line 232 of file HalfBandF64Sse2.hpp.
References process_2_paths().
Referenced by operator=().
set_coefs()
template<int NC> void hiir::HalfBandF64Sse2< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 96 of file HalfBandF64Sse2.hpp.
References _bifilter, _nbr_phases, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
store_high()
template<int NC> void hiir::HalfBandF64Sse2< NC >::store_high (double * ptr, double even, double odd) static private noexcept
Definition at line 417 of file HalfBandF64Sse2.hpp.
Referenced by process_block_2_paths(), process_block_hpf(), and process_block_split().
store_low()
template<int NC> void hiir::HalfBandF64Sse2< NC >::store_low (double * ptr, double even, double odd) static private noexcept
Definition at line 409 of file HalfBandF64Sse2.hpp.
Referenced by process_block(), process_block_2_paths(), and process_block_split().
Member Data Documentation
_bifilter
template<int NC> FilterBiPhase hiir::HalfBandF64Sse2< NC >::_bifilter private
Definition at line 123 of file HalfBandF64Sse2.h.
Referenced by HalfBandF64Sse2(), clear_buffers(), process_2_paths(), process_block_2_paths(), and set_coefs().
_delay
template<int NC> double hiir::HalfBandF64Sse2< NC >::_delay = 0 static constexpr
Definition at line 60 of file HalfBandF64Sse2.h.
_nbr_chn
template<int NC> int hiir::HalfBandF64Sse2< NC >::_nbr_chn = 1 static constexpr
Definition at line 58 of file HalfBandF64Sse2.h.
Referenced by process_block(), process_block_hpf(), and process_block_split().
_nbr_phases
template<int NC> int hiir::HalfBandF64Sse2< NC >::_nbr_phases = 2 static constexpr private
Definition at line 102 of file HalfBandF64Sse2.h.
Referenced by HalfBandF64Sse2(), clear_buffers(), process_block_2_paths(), and set_coefs().
_nbr_stages
template<int NC> int hiir::HalfBandF64Sse2< NC >::_nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width static constexpr private
Definition at line 101 of file HalfBandF64Sse2.h.
Referenced by HalfBandF64Sse2(), and clear_buffers().
_phase
template<int NC> int hiir::HalfBandF64Sse2< NC >::_phase private
Definition at line 125 of file HalfBandF64Sse2.h.
Referenced by HalfBandF64Sse2(), clear_buffers(), process_2_paths(), and process_block_2_paths().
_prev
template<int NC> double hiir::HalfBandF64Sse2< NC >::_prev private
Definition at line 124 of file HalfBandF64Sse2.h.
Referenced by HalfBandF64Sse2(), clear_buffers(), process_2_paths(), and process_block_2_paths().
_stage_width
template<int NC> int hiir::HalfBandF64Sse2< NC >::_stage_width = 2 static constexpr private
Definition at line 100 of file HalfBandF64Sse2.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::HalfBandF64Sse2< NC >::NBR_COEFS = NC static constexpr
Definition at line 59 of file HalfBandF64Sse2.h.
Referenced by HalfBandF64Sse2(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/HalfBandF64Sse2.h
src/3rdparty/hiir/hiir/HalfBandF64Sse2.hpp