LMMS: Jack::JackLibClient Class Reference
Jack::JackLibClient Class Reference
Client on the library side.
#include <JackLibClient.h>
Public Member Functions
JackLibClient (JackSynchro *table)
Shared client control.
virtual ~JackLibClient ()
int ClientNotifyImp (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
Notification received from the server.
JackClientControl * GetClientControl () const
JackEngineControl * GetEngineControl () const
JackGraphManager * GetGraphManager () const
JackMetadata * GetMetadata () const
int Open (const char *server_name, const char *name, jack_uuid_t uuid, jack_options_t options, jack_status_t *status)
void ShutDown (jack_status_t code, const char *message)
Public Member Functions inherited from Jack::JackClient
JackClient (JackSynchro *table)
virtual ~JackClient ()
virtual int Activate ()
We need to start thread before activating in the server, otherwise the FW driver connected to the client may not be activated.
virtual int ClientHasSessionCallback (const char *client_name)
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual int ComputeTotalLatencies ()
void CycleSignal (int status)
jack_nframes_t CycleWait ()
virtual int Deactivate ()
Need to stop thread after deactivating in the server.
bool Execute ()
RT thread.
virtual char * GetClientNameByUUID (const char *uuid)
virtual jack_nframes_t GetCurrentTransportFrame ()
virtual char * GetInternalClientName (int ref)
char * GetServerName ()
virtual jack_native_thread_t GetThreadID ()
virtual char * GetUUIDForClientName (const char *client_name)
bool Init ()
Called once when the thread starts.
virtual int InternalClientHandle (const char *client_name, jack_status_t *status)
virtual int InternalClientLoad (const char *client_name, jack_options_t options, jack_status_t *status, jack_varargs_t *va)
virtual void InternalClientUnload (int ref, jack_status_t *status)
virtual void OnInfoShutdown (JackInfoShutdownCallback callback, void *arg)
virtual void OnShutdown (JackShutdownCallback callback, void *arg)
virtual int PortConnect (const char *src, const char *dst)
virtual int PortDisconnect (const char *src, const char *dst)
virtual int PortDisconnect (jack_port_id_t src)
virtual int PortIsMine (jack_port_id_t port_index)
virtual int PortRegister (const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
virtual int PortRename (jack_port_id_t port_index, const char *name)
virtual int PortUnRegister (jack_port_id_t port)
virtual int PropertyChangeNotify (jack_uuid_t subject, const char *key, jack_property_change_t change)
virtual int ReleaseTimebase ()
virtual int ReserveClientName (const char *client_name, const char *uuid)
virtual jack_session_command_t * SessionNotify (const char *target, jack_session_event_type_t type, const char *path)
virtual int SessionReply (jack_session_event_t *ev)
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetBufferSizeCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetClientRegistrationCallback (JackClientRegistrationCallback callback, void *arg)
virtual int SetFreeWheel (int onoff)
virtual int SetFreewheelCallback (JackFreewheelCallback callback, void *arg)
virtual int SetGraphOrderCallback (JackGraphOrderCallback callback, void *arg)
virtual int SetInitCallback (JackThreadInitCallback callback, void *arg)
virtual int SetLatencyCallback (JackLatencyCallback callback, void *arg)
virtual int SetPortConnectCallback (JackPortConnectCallback callback, void *arg)
virtual int SetPortRegistrationCallback (JackPortRegistrationCallback callback, void *arg)
virtual int SetPortRenameCallback (JackPortRenameCallback callback, void *arg)
virtual int SetProcessCallback (JackProcessCallback callback, void *arg)
virtual int SetProcessThread (JackThreadCallback fun, void *arg)
virtual int SetPropertyChangeCallback (JackPropertyChangeCallback callback, void *arg)
virtual int SetSampleRateCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetSessionCallback (JackSessionCallback callback, void *arg)
virtual int SetSyncCallback (JackSyncCallback sync_callback, void *arg)
virtual int SetSyncTimeout (jack_time_t timeout)
virtual int SetTimebaseCallback (int conditional, JackTimebaseCallback timebase_callback, void *arg)
virtual int SetXRunCallback (JackXRunCallback callback, void *arg)
virtual void TransportLocate (jack_nframes_t frame)
virtual jack_transport_state_t TransportQuery (jack_position_t *pos)
virtual int TransportReposition (const jack_position_t *pos)
virtual void TransportStart ()
virtual void TransportStop ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Attributes
JackShmReadWritePtr1< JackClientControl > fClientControl
Additional Inherited Members
Protected Member Functions inherited from Jack::JackClient
int ActivateAux ()
int CallProcessCallback ()
void CallSyncCallback ()
void CallSyncCallbackAux ()
void CallTimebaseCallback ()
void CallTimebaseCallbackAux ()
void CycleSignalAux (int status)
jack_nframes_t CycleWaitAux ()
void DummyCycle ()
void End ()
void Error ()
void ExecuteThread ()
int HandleLatencyCallback (int status)
void InitAux ()
bool IsActive ()
void SetupDriverSync (bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
void SetupRealTime ()
void SignalSync ()
int StartThread ()
bool WaitSync ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Protected Attributes inherited from Jack::JackClient
JackBufferSizeCallback fBufferSize
void * fBufferSizeArg
detail::JackClientChannelInterface * fChannel
Thread to execute the Process function.
JackClientRegistrationCallback fClientRegistration
void * fClientRegistrationArg
JackFreewheelCallback fFreewheel
void * fFreewheelArg
JackGraphOrderCallback fGraphOrder
void * fGraphOrderArg
JackInfoShutdownCallback fInfoShutdown
void * fInfoShutdownArg
JackThreadInitCallback fInit
void * fInitArg
JackLatencyCallback fLatency
void * fLatencyArg
JackPortConnectCallback fPortConnect
void * fPortConnectArg
std::list< jack_port_id_t > fPortList
JackPortRegistrationCallback fPortRegistration
void * fPortRegistrationArg
JackPortRenameCallback fPortRename
void * fPortRenameArg
JackProcessCallback fProcess
void * fProcessArg
JackPropertyChangeCallback fPropertyChange
void * fPropertyChangeArg
JackSampleRateCallback fSampleRate
void * fSampleRateArg
char fServerName [JACK_SERVER_NAME_SIZE+1]
JackSessionCallback fSession
void * fSessionArg
JackSessionReply fSessionReply
JackShutdownCallback fShutdown
void * fShutdownArg
JackSyncCallback fSync
void * fSyncArg
JackSynchro * fSynchroTable
JackThread fThread
JackThreadCallback fThreadFun
void * fThreadFunArg
JackTimebaseCallback fTimebase
void * fTimebaseArg
JackXRunCallback fXrun
void * fXrunArg
Detailed Description
Client on the library side.
Definition at line 35 of file JackLibClient.h.
Constructor & Destructor Documentation
JackLibClient()
Jack::JackLibClient::JackLibClient (JackSynchro * table)
Shared client control.
Definition at line 81 of file JackLibClient.cpp.
References Jack::JackClient::JackClient(), Jack::JackClient::fChannel, and jack_log().
~JackLibClient()
Jack::JackLibClient::~JackLibClient () virtual
Definition at line 87 of file JackLibClient.cpp.
References Jack::JackClient::fChannel, and jack_log().
Member Function Documentation
ClientNotifyImp()
int Jack::JackLibClient::ClientNotifyImp (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value) virtual
Notification received from the server.
Reimplemented from Jack::JackClient.
Definition at line 167 of file JackLibClient.cpp.
References fName, Jack::JackClient::fServerName, Jack::JackGlobals::fSynchroMutex, Jack::JackClient::fSynchroTable, GetClientControl(), jack_log(), Jack::kAddClient, and Jack::kRemoveClient.
GetClientControl()
JackClientControl * Jack::JackLibClient::GetClientControl () const virtual
Implements Jack::JackClientInterface.
Definition at line 206 of file JackLibClient.cpp.
References fClientControl.
Referenced by ClientNotifyImp(), and Open().
GetEngineControl()
JackEngineControl * Jack::JackLibClient::GetEngineControl () const virtual
Implements Jack::JackClient.
Definition at line 200 of file JackLibClient.cpp.
References Jack::JackLibGlobals::fGlobals.
Referenced by Open().
GetGraphManager()
JackGraphManager * Jack::JackLibClient::GetGraphManager () const virtual
Implements Jack::JackClient.
Definition at line 194 of file JackLibClient.cpp.
References Jack::JackLibGlobals::fGlobals.
GetMetadata()
JackMetadata * Jack::JackLibClient::GetMetadata () const
Open()
int Jack::JackLibClient::Open (const char * server_name, const char * name, jack_uuid_t uuid, jack_options_t options, jack_status_t * status) virtual
Implements Jack::JackClient.
Definition at line 93 of file JackLibClient.cpp.
References Jack::JackClient::fChannel, fClientControl, Jack::JackGlobals::fClientTable, Jack::JackLibGlobals::fGlobals, Jack::JackClientControl::fRefNum, Jack::JackClient::fServerName, Jack::JackGlobals::fSynchroMutex, Jack::JackClient::fSynchroTable, Jack::JackEngineControl::fVerbose, Jack::JackGlobals::fVerbose, GetClientControl(), GetEngineControl(), Jack::JackTools::GetPID(), JACK_CLIENT_NAME_SIZE, jack_error, jack_log(), server_name, SetClockSource(), and Jack::JackClient::SetupDriverSync().
ShutDown()
void Jack::JackLibClient::ShutDown (jack_status_t code, const char * message) virtual
Reimplemented from Jack::JackClient.
Definition at line 74 of file JackLibClient.cpp.
References Jack::JackGlobals::fServerRunning, jack_log(), and Jack::JackClient::ShutDown().
Member Data Documentation
fClientControl
JackShmReadWritePtr1<JackClientControl> Jack::JackLibClient::fClientControl private
Definition at line 40 of file JackLibClient.h.
Referenced by GetClientControl(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackLibClient.h
src/3rdparty/jack2/common/JackLibClient.cpp