LMMS: lmms::RemotePluginBase::message Struct Reference
lmms::RemotePluginBase::message Struct Reference
#include <RemotePluginBase.h>
Public Member Functions
message ()
message (const message &_m)=default
message (int _id)
message & addFloat (float _f)
message & addInt (int _i)
message & addString (const std::string &_s)
float getFloat (int _p) const
int getInt (int _p=0) const
QString getQString (int _p=0) const
std::string getString (int _p=0) const
bool operator== (const message &_m) const
Public Attributes
int id
Private Attributes
std::vector< std::string > data
Friends
class RemotePluginBase
Detailed Description
Definition at line 357 of file RemotePluginBase.h.
Constructor & Destructor Documentation
message() [1/3]
lmms::RemotePluginBase::message::message () inline
Definition at line 359 of file RemotePluginBase.h.
References data, id, and lmms::IdUndefined.
Referenced by message(), addFloat(), addInt(), addString(), and operator==().
message() [2/3]
lmms::RemotePluginBase::message::message (const message & _m) default
References message().
message() [3/3]
lmms::RemotePluginBase::message::message (int _id) inline
Definition at line 367 of file RemotePluginBase.h.
References data, and id.
Member Function Documentation
addFloat()
message & lmms::RemotePluginBase::message::addFloat (float _f) inline
Definition at line 387 of file RemotePluginBase.h.
References message(), and data.
addInt()
message & lmms::RemotePluginBase::message::addInt (int _i) inline
Definition at line 379 of file RemotePluginBase.h.
References message(), and data.
Referenced by lmms::RemotePlugin::processMessage(), and lmms::RemotePlugin::processMidiEvent().
addString()
message & lmms::RemotePluginBase::message::addString (const std::string & _s) inline
Definition at line 373 of file RemotePluginBase.h.
References message(), and data.
getFloat()
float lmms::RemotePluginBase::message::getFloat (int _p) const inline
Definition at line 412 of file RemotePluginBase.h.
References data.
getInt()
int lmms::RemotePluginBase::message::getInt (int _p = 0) const inline
Definition at line 407 of file RemotePluginBase.h.
References data.
Referenced by lmms::RemotePlugin::isUIVisible(), lmms::RemotePlugin::processMessage(), and lmms::RemotePluginClient::processMessage().
getQString()
QString lmms::RemotePluginBase::message::getQString (int _p = 0) const inline
Definition at line 401 of file RemotePluginBase.h.
References getString().
getString()
std::string lmms::RemotePluginBase::message::getString (int _p = 0) const inline
Definition at line 395 of file RemotePluginBase.h.
References data.
Referenced by getQString(), lmms::RemotePlugin::processMessage(), and lmms::RemotePluginClient::processMessage().
operator==()
bool lmms::RemotePluginBase::message::operator== (const message & _m) const inline
Definition at line 417 of file RemotePluginBase.h.
References message(), and id.
Friends And Related Symbol Documentation
RemotePluginBase
friend class RemotePluginBase friend
Definition at line 427 of file RemotePluginBase.h.
References RemotePluginBase.
Referenced by RemotePluginBase.
Member Data Documentation
data
std::vector<std::string> lmms::RemotePluginBase::message::data private
Definition at line 425 of file RemotePluginBase.h.
Referenced by message(), message(), addFloat(), addInt(), addString(), getFloat(), getInt(), getString(), lmms::RemotePluginBase::receiveMessage(), and lmms::RemotePluginBase::sendMessage().
id
int lmms::RemotePluginBase::message::id
Definition at line 422 of file RemotePluginBase.h.
Referenced by message(), message(), lmms::RemotePlugin::isUIVisible(), operator==(), lmms::RemotePlugin::processMessage(), lmms::RemotePluginClient::processMessage(), lmms::RemotePluginBase::receiveMessage(), lmms::RemotePluginBase::sendMessage(), and lmms::RemotePluginBase::waitForMessage().
The documentation for this struct was generated from the following file:
include/RemotePluginBase.h