LMMS: lmms::gui::EffectControlDialog Class Reference
lmms::gui::EffectControlDialog Class Reference
#include <EffectControlDialog.h>
Signals
void closed ()
Public Member Functions
EffectControlDialog (EffectControls *_controls)
~EffectControlDialog () override=default
virtual bool isResizable () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
void closeEvent (QCloseEvent *_ce) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Protected Attributes
EffectControls * m_effectControls
Detailed Description
Definition at line 42 of file EffectControlDialog.h.
Constructor & Destructor Documentation
EffectControlDialog()
lmms::gui::EffectControlDialog::EffectControlDialog (EffectControls * _controls)
Definition at line 35 of file EffectControlDialog.cpp.
References lmms::gui::ModelView::ModelView(), and m_effectControls.
Referenced by lmms::gui::DummyEffectControlDialog::DummyEffectControlDialog().
~EffectControlDialog()
lmms::gui::EffectControlDialog::~EffectControlDialog () override default
Member Function Documentation
closed
void lmms::gui::EffectControlDialog::closed () signal
References closeEvent().
Referenced by closeEvent().
closeEvent()
void lmms::gui::EffectControlDialog::closeEvent (QCloseEvent * _ce) override protected
Definition at line 47 of file EffectControlDialog.cpp.
References closed().
Referenced by closed().
isResizable()
virtual bool lmms::gui::EffectControlDialog::isResizable () const inline virtual
Definition at line 49 of file EffectControlDialog.h.
Member Data Documentation
m_effectControls
EffectControls* lmms::gui::EffectControlDialog::m_effectControls protected
Definition at line 59 of file EffectControlDialog.h.
Referenced by EffectControlDialog().
The documentation for this class was generated from the following files:
include/EffectControlDialog.h
src/gui/EffectControlDialog.cpp