LMMS: ringbuffer_base Class Reference
ringbuffer_base Class Reference
#include <ringbuffer.h>
Classes
class rb_atomic
Public Member Functions
std::size_t write_space () const
returns number of objects that can be written at least
Protected Member Functions
void init_atomic_variables ()
void init_variables_for_write (std::size_t cnt, std::size_t &w, std::size_t &to_write, std::size_t &n1, std::size_t &n2)
bool mlock (const void *const buf, std::size_t each)
bool munlock (const void *const buf, std::size_t each)
ringbuffer_common_t (std::size_t sz)
Protected Member Functions inherited from ringbuffer_common_t
ringbuffer_common_t (std::size_t sz)
Protected Attributes
std::size_t num_readers = 0
to be const after initialisation
rb_atomic< std::size_t > readers_left
counts number of readers left in previous buffer half
rb_atomic< std::size_t > w_ptr
writer at buf[w_ptr]
Protected Attributes inherited from ringbuffer_common_t
const std::size_t size
< max number of objects in buffer (2^n for some n)
const std::size_t size_mask
= size - 1
Private Member Functions
std::size_t write_space_preloaded (std::size_t w, std::size_t rl) const
version for preloaded write ptr
Private Attributes
bool mlocked = false
Detailed Description
Definition at line 56 of file ringbuffer.h.
Member Function Documentation
init_atomic_variables()
void ringbuffer_base::init_atomic_variables () protected
Definition at line 99 of file ringbuffer.cpp.
References readers_left, and w_ptr.
Referenced by ringbuffer_t< T >::ringbuffer_t().
init_variables_for_write()
void ringbuffer_base::init_variables_for_write (std::size_t cnt, std::size_t & w, std::size_t & to_write, std::size_t & n1, std::size_t & n2) protected
Definition at line 111 of file ringbuffer.cpp.
References num_readers, readers_left, ringbuffer_common_t::size, ringbuffer_common_t::size_mask, w_ptr, and write_space_preloaded().
Referenced by ringbuffer_t< T >::write_func().
mlock()
bool ringbuffer_base::mlock (const void *const buf, std::size_t each) protected
Definition at line 68 of file ringbuffer.cpp.
References mlock(), mlocked, and ringbuffer_common_t::size.
Referenced by mlock(), and ringbuffer_t< T >::mlock().
munlock()
bool ringbuffer_base::munlock (const void *const buf, std::size_t each) protected
Definition at line 47 of file ringbuffer.cpp.
Referenced by ringbuffer_t< T >::munlock().
ringbuffer_common_t()
ringbuffer_common_t::ringbuffer_common_t (std::size_t sz) protected
Definition at line 49 of file ringbuffer.cpp.
References mlocked.
Referenced by ringbuffer_t< T >::ringbuffer_t().
write_space()
std::size_t ringbuffer_base::write_space () const
returns number of objects that can be written at least
Definition at line 105 of file ringbuffer.cpp.
References readers_left, w_ptr, and write_space_preloaded().
write_space_preloaded()
std::size_t ringbuffer_base::write_space_preloaded (std::size_t w, std::size_t rl) const private
version for preloaded write ptr
Definition at line 91 of file ringbuffer.cpp.
References ringbuffer_common_t::size, and ringbuffer_common_t::size_mask.
Referenced by init_variables_for_write(), and write_space().
Member Data Documentation
mlocked
bool ringbuffer_base::mlocked = false private
Definition at line 58 of file ringbuffer.h.
Referenced by mlock(), and ringbuffer_common_t().
num_readers
std::size_t ringbuffer_base::num_readers = 0 protected
to be const after initialisation
Definition at line 88 of file ringbuffer.h.
Referenced by ringbuffer_reader_t< T >::ringbuffer_reader_t(), ringbuffer_reader_t< T >::connect(), and init_variables_for_write().
readers_left
rb_atomic<std::size_t> ringbuffer_base::readers_left protected
counts number of readers left in previous buffer half
Definition at line 87 of file ringbuffer.h.
Referenced by init_atomic_variables(), init_variables_for_write(), ringbuffer_t< T >::touch(), and write_space().
w_ptr
rb_atomic<std::size_t> ringbuffer_base::w_ptr protected
writer at buf[w_ptr]
Definition at line 85 of file ringbuffer.h.
Referenced by init_atomic_variables(), init_variables_for_write(), ringbuffer_t< T >::touch(), ringbuffer_t< T >::write_func(), and write_space().
The documentation for this class was generated from the following files:
src/3rdparty/ringbuffer/include/ringbuffer/ringbuffer.h
src/3rdparty/ringbuffer/src/lib/ringbuffer.cpp