LMMS: API for a session manager.
API for a session manager.
Classes
struct jack_session_command_t
Functions
int jack_client_has_session_callback (jack_client_t *client, const char *client_name) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Find out whether a client has set up a session callback.
int jack_reserve_client_name (jack_client_t *client, const char *name, const char *uuid) JACK_WEAK_EXPORT
Reserve a client name and associate it with a UUID.
void jack_session_commands_free (jack_session_command_t *cmds) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Free the memory allocated by a session command.
jack_session_command_t * jack_session_notify (jack_client_t *client, const char *target, jack_session_event_type_t type, const char *path) JACK_WEAK_EXPORT
Send an event to all clients listening for session callbacks.
Detailed Description
Function Documentation
jack_client_has_session_callback()
LIB_EXPORT int jack_client_has_session_callback (jack_client_t * client, const char * client_name)
#include <session.h>
Find out whether a client has set up a session callback.
Deprecated
Use of JACK-Session is currently deprecated and unsupported. JACK developers recommend the use of NSM instead. See https://github.com/linuxaudio/new-session-manager
Returns
0 when the client has no session callback, 1 when it has one. -1 on error.
Definition at line 2073 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, jack_log(), and LIB_EXPORT.
jack_reserve_client_name()
LIB_EXPORT int jack_reserve_client_name (jack_client_t * client, const char * name, const char * uuid)
#include <session.h>
Reserve a client name and associate it with a UUID.
When a client later calls jack_client_open() and specifies the UUID, jackd will assign the reserved name. This allows a session manager to know in advance under which client name its managed clients will appear.
Returns
0 on success, otherwise a non-zero error code
Definition at line 2030 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, jack_log(), and LIB_EXPORT.
jack_session_commands_free()
LIB_EXPORT void jack_session_commands_free (jack_session_command_t * cmds)
#include <session.h>
Free the memory allocated by a session command.
Deprecated
Use of JACK-Session is currently deprecated and unsupported. JACK developers recommend the use of NSM instead. See https://github.com/linuxaudio/new-session-manager
Definition at line 2044 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), i, and LIB_EXPORT.
jack_session_notify()
LIB_EXPORT jack_session_command_t * jack_session_notify (jack_client_t * client, const char * target, jack_session_event_type_t type, const char * path)
#include <session.h>
Send an event to all clients listening for session callbacks.
The returned strings of the clients are accumulated and returned as an array of jack_session_command_t. its terminated by ret[i].uuid == NULL target == NULL means send to all interested clients. otherwise a clientname
Definition at line 1944 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, jack_log(), and LIB_EXPORT.