LMMS: TestStateUser Class Reference
TestStateUser Class Reference
The state wrapped with the 2 state atomic class.
Public Member Functions
TestStateUser ()
virtual ~TestStateUser ()
void TestReadMethod ()
void TestReadRTMethod1 ()
void TestReadRTMethod2 ()
void TestWriteMethod ()
Public Member Functions inherited from Jack::JackAtomicState< TestState >
JackAtomicState ()
~JackAtomicState ()
UInt16 GetCurrentIndex ()
Returns the current state index.
bool IsPendingChange ()
TestState * ReadCurrentState ()
Returns the current state : only valid in the RT reader thread.
TestState * TrySwitchState ()
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
TestState * WriteNextStateStart ()
Start write operation : setup and returns the next state to update, check for recursive write calls.
void WriteNextStateStop ()
Stop write operation : make the next state ready to be used by the RT thread.
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAtomicState< TestState >
UInt32 WriteNextStateStartAux ()
void WriteNextStateStopAux ()
Protected Attributes inherited from Jack::JackAtomicState< TestState >
SInt32 fCallWriteCounter
volatile AtomicCounter fCounter
TestState fState [2]
Detailed Description
The state wrapped with the 2 state atomic class.
Definition at line 105 of file testAtomic.cpp.
Constructor & Destructor Documentation
TestStateUser()
TestStateUser::TestStateUser () inline
Definition at line 109 of file testAtomic.cpp.
~TestStateUser()
virtual TestStateUser::~TestStateUser () inline virtual
Definition at line 110 of file testAtomic.cpp.
Member Function Documentation
TestReadMethod()
void TestStateUser::TestReadMethod () inline
Definition at line 121 of file testAtomic.cpp.
References TestState::Check(), Jack::JackAtomicState< TestState >::GetCurrentIndex(), TestState::ReadCopy(), Jack::JackAtomicState< TestState >::ReadCurrentState(), and SIZE.
TestReadRTMethod1()
void TestStateUser::TestReadRTMethod1 () inline
Definition at line 140 of file testAtomic.cpp.
References TestState::Read(), and Jack::JackAtomicState< TestState >::TrySwitchState().
TestReadRTMethod2()
void TestStateUser::TestReadRTMethod2 () inline
Definition at line 146 of file testAtomic.cpp.
References TestState::Read(), and Jack::JackAtomicState< TestState >::ReadCurrentState().
TestWriteMethod()
void TestStateUser::TestWriteMethod () inline
Definition at line 112 of file testAtomic.cpp.
References TestState::Write(), Jack::JackAtomicState< TestState >::WriteNextStateStart(), and Jack::JackAtomicState< TestState >::WriteNextStateStop().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/tests/testAtomic.cpp