LMMS: lmms::gui::SampleClipView Class Reference
lmms::gui::SampleClipView Class Reference
#include <SampleClipView.h>
Public Slots
void reverseSample ()
void setAutomationGhost ()
void updateSample ()
Public Slots inherited from lmms::gui::ClipView
virtual bool close ()
Close a ClipView.
void randomizeColor ()
void remove ()
Removes a ClipView from its track view.
void resetColor ()
void selectColor ()
void update () override
Update a ClipView.
Public Slots inherited from lmms::gui::selectableObject
virtual void update ()
Public Member Functions
SampleClipView (SampleClip *_clip, TrackView *_tv)
~SampleClipView () override=default
Public Member Functions inherited from lmms::gui::ClipView
ClipView (Clip *clip, TrackView *tv)
Create a new ClipView.
~ClipView () override
Destroy a ClipView.
void copy (QVector< ClipView * > clipvs)
void cut (QVector< ClipView * > clipvs)
bool fixedClips ()
Does this ClipView have a fixed Clip?
QVector< ClipView * > getClickedClips ()
Clip * getClip ()
QColor getColorForDisplay (QColor)
TrackView * getTrackView ()
bool gradient () const
QColor markerColor () const
QColor mutedBackgroundColor () const
QColor mutedColor () const
CSS theming qproperty access method.
bool needsUpdate ()
void paste ()
QColor patternClipBackground () const
QColor selectedColor () const
void setGradient (const bool &b)
void setMarkerColor (const QColor &c)
void setMarkerEnabled (bool e)
void setMarkerPos (int x)
void setMutedBackgroundColor (const QColor &c)
void setMutedColor (const QColor &c)
CSS theming qproperty access method.
void setNeedsUpdate (bool b)
void setPatternClipBackground (const QColor &c)
void setSelectedColor (const QColor &c)
void setTextBackgroundColor (const QColor &c)
void setTextColor (const QColor &c)
void setTextShadowColor (const QColor &c)
QColor textBackgroundColor () const
QColor textColor () const
QColor textShadowColor () const
void toggleSelectedAutoResize ()
Public Member Functions inherited from lmms::gui::selectableObject
selectableObject (QWidget *_parent)
~selectableObject () override=default
bool isSelected () const
void setSelected (bool selected)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
void constructContextMenu (QMenu *cm) override
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void mouseDoubleClickEvent (QMouseEvent *) override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *) override
Protected Member Functions inherited from lmms::gui::ClipView
void contextMenuAction (ContextMenuAction action)
void contextMenuEvent (QContextMenuEvent *cme) override
Set up the context menu for this ClipView.
DataFile createClipDataFiles (const QVector< ClipView * > &clips) const
Create a DataFile suitable for copying multiple clips.
void dragEnterEvent (QDragEnterEvent *dee) override
Change the ClipView's display when something being dragged enters it.
void dropEvent (QDropEvent *de) override
Handle something being dropped on this ClipObjectView.
auto hasCustomColor () const -> bool
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse movement (drag) on this ClipView.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press on this ClipView.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release on this ClipView.
virtual void paintTextLabel (QString const &text, QPainter &painter)
float pixelsPerBar ()
How many pixels a bar takes for this ClipView.
TimePos quantizeSplitPos (TimePos)
void resizeEvent (QResizeEvent *re) override
bool unquantizedModHeld (QMouseEvent *me)
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Private Attributes
SampleClip * m_clip
QPixmap m_paintPixmap
long m_paintPixmapXPosition
SampleThumbnail m_sampleThumbnail
Additional Inherited Members
Static Public Member Functions inherited from lmms::gui::ClipView
static void remove (QVector< ClipView * > clipvs)
static void toggleMute (QVector< ClipView * > clipvs)
Static Public Attributes inherited from lmms::gui::ClipView
static const int BORDER_WIDTH = 2
Protected Types inherited from lmms::gui::ClipView
enum class ContextMenuAction {
Remove ,
Cut ,
Copy ,
Paste ,
Mute
}
Protected Slots inherited from lmms::gui::ClipView
void updateLength ()
Updates a ClipView's length.
void updatePosition ()
Updates a ClipView's position.
Protected Attributes inherited from lmms::gui::ClipView
TimePos m_initialClipEnd
TimePos m_initialClipPos
bool m_marker = false
int m_markerPos = 0
TrackView * m_trackView
Properties inherited from lmms::gui::ClipView
bool gradient
QColor markerColor
QColor mutedBackgroundColor
QColor mutedColor
QColor patternClipBackground
QColor selectedColor
QColor textBackgroundColor
QColor textColor
QColor textShadowColor
Detailed Description
Definition at line 41 of file SampleClipView.h.
Constructor & Destructor Documentation
SampleClipView()
lmms::gui::SampleClipView::SampleClipView (SampleClip * _clip, TrackView * _tv)
Definition at line 47 of file SampleClipView.cpp.
References lmms::gui::ClipView::ClipView(), m_clip, m_paintPixmap, m_paintPixmapXPosition, lmms::gui::ClipView::update(), and updateSample().
~SampleClipView()
lmms::gui::SampleClipView::~SampleClipView () override default
Member Function Documentation
constructContextMenu()
void lmms::gui::SampleClipView::constructContextMenu (QMenu * cm) override protected virtual
Reimplemented from lmms::gui::ClipView.
Definition at line 82 of file SampleClipView.cpp.
References lmms::embed::getIconPixmap(), reverseSample(), and setAutomationGhost().
dragEnterEvent()
void lmms::gui::SampleClipView::dragEnterEvent (QDragEnterEvent * _dee) override protected
Definition at line 109 of file SampleClipView.cpp.
References lmms::gui::ClipView::dragEnterEvent(), and lmms::gui::StringPairDrag::processDragEnterEvent().
dropEvent()
void lmms::gui::SampleClipView::dropEvent (QDropEvent * _de) override protected
Definition at line 123 of file SampleClipView.cpp.
References lmms::gui::SampleLoader::createBufferFromBase64(), lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::gui::ClipView::dropEvent(), m_clip, and lmms::gui::ClipView::update().
mouseDoubleClickEvent()
void lmms::gui::SampleClipView::mouseDoubleClickEvent (QMouseEvent *) override protected
Definition at line 187 of file SampleClipView.cpp.
References lmms::gui::SampleLoader::createBufferFromFile(), lmms::SampleBuffer::emptyBuffer(), m_clip, lmms::gui::ClipView::m_trackView, and lmms::gui::SampleLoader::openAudioFile().
mousePressEvent()
void lmms::gui::SampleClipView::mousePressEvent (QMouseEvent * _me) override protected
Definition at line 146 of file SampleClipView.cpp.
References lmms::gui::ClipView::getClip(), m_clip, and lmms::gui::ClipView::mousePressEvent().
mouseReleaseEvent()
void lmms::gui::SampleClipView::mouseReleaseEvent (QMouseEvent * _me) override protected
Definition at line 171 of file SampleClipView.cpp.
References lmms::gui::ClipView::getClip(), and lmms::gui::ClipView::mouseReleaseEvent().
paintEvent()
void lmms::gui::SampleClipView::paintEvent (QPaintEvent * pe) override protected
Definition at line 209 of file SampleClipView.cpp.
References lmms::gui::ClipView::BORDER_WIDTH, lmms::PathUtil::cleanName(), lmms::DefaultTicksPerBar, lmms::gui::ClipView::fixedClips(), lmms::embed::getIconPixmap(), lmms::Engine::getSong(), lmms::Song::getTimeSigModel(), lmms::gui::ClipView::getTrackView(), lmms::gui::ClipView::gradient, lmms::gui::selectableObject::isSelected(), m_clip, lmms::gui::ClipView::m_marker, lmms::gui::ClipView::m_markerPos, m_paintPixmap, m_paintPixmapXPosition, m_sampleThumbnail, lmms::gui::ClipView::markerColor, lmms::gui::ClipView::needsUpdate(), lmms::gui::ClipView::paintTextLabel(), lmms::gui::ClipView::pixelsPerBar(), and lmms::gui::ClipView::setNeedsUpdate().
reverseSample
void lmms::gui::SampleClipView::reverseSample () slot
Definition at line 356 of file SampleClipView.cpp.
References lmms::Engine::getSong(), m_clip, lmms::Song::setModified(), and lmms::gui::ClipView::update().
Referenced by constructContextMenu().
setAutomationGhost
void lmms::gui::SampleClipView::setAutomationGhost () slot
Definition at line 366 of file SampleClipView.cpp.
References lmms::gui::GuiApplication::automationEditor(), lmms::gui::getGUI(), m_clip, and lmms::gui::AutomationEditorWindow::setGhostSample().
Referenced by constructContextMenu().
updateSample
void lmms::gui::SampleClipView::updateSample () slot
Definition at line 64 of file SampleClipView.cpp.
References m_clip, m_sampleThumbnail, lmms::PathUtil::toAbsolute(), and lmms::gui::ClipView::update().
Referenced by SampleClipView().
Member Data Documentation
m_clip
SampleClip* lmms::gui::SampleClipView::m_clip private
Definition at line 67 of file SampleClipView.h.
Referenced by SampleClipView(), dropEvent(), mouseDoubleClickEvent(), mousePressEvent(), paintEvent(), reverseSample(), setAutomationGhost(), and updateSample().
m_paintPixmap
QPixmap lmms::gui::SampleClipView::m_paintPixmap private
Definition at line 69 of file SampleClipView.h.
Referenced by SampleClipView(), and paintEvent().
m_paintPixmapXPosition
long lmms::gui::SampleClipView::m_paintPixmapXPosition private
Definition at line 70 of file SampleClipView.h.
Referenced by SampleClipView(), and paintEvent().
m_sampleThumbnail
SampleThumbnail lmms::gui::SampleClipView::m_sampleThumbnail private
Definition at line 68 of file SampleClipView.h.
Referenced by paintEvent(), and updateSample().
The documentation for this class was generated from the following files:
include/SampleClipView.h
src/gui/clips/SampleClipView.cpp