LMMS: lmms::SystemSemaphore Class Reference
lmms::SystemSemaphore Class Reference
#include <SystemSemaphore.h>
Public Member Functions
SystemSemaphore () noexcept
SystemSemaphore (std::string key)
SystemSemaphore (std::string key, unsigned int value)
SystemSemaphore (SystemSemaphore &&other) noexcept
~SystemSemaphore ()
auto acquire () noexcept -> bool
auto key () const noexcept -> const std::string &
auto operator= (SystemSemaphore &&other) noexcept -> SystemSemaphore &
auto release () noexcept -> bool
Private Attributes
std::unique_ptr< detail::SystemSemaphoreImpl > m_impl
std::string m_key
Detailed Description
Definition at line 38 of file SystemSemaphore.h.
Constructor & Destructor Documentation
SystemSemaphore() [1/4]
lmms::SystemSemaphore::SystemSemaphore () default noexcept
References SystemSemaphore(), and key().
Referenced by SystemSemaphore(), SystemSemaphore(), SystemSemaphore(), SystemSemaphore(), ~SystemSemaphore(), and operator=().
SystemSemaphore() [2/4]
lmms::SystemSemaphore::SystemSemaphore (std::string key, unsigned int value)
Definition at line 163 of file SystemSemaphore.cpp.
References SystemSemaphore(), key(), and m_key.
SystemSemaphore() [3/4]
lmms::SystemSemaphore::SystemSemaphore (std::string key) explicit
Definition at line 168 of file SystemSemaphore.cpp.
References SystemSemaphore(), key(), m_impl, and m_key.
~SystemSemaphore()
lmms::SystemSemaphore::~SystemSemaphore () default
References SystemSemaphore().
SystemSemaphore() [4/4]
lmms::SystemSemaphore::SystemSemaphore (SystemSemaphore && other) default noexcept
References SystemSemaphore().
Member Function Documentation
acquire()
auto lmms::SystemSemaphore::acquire () ->bool noexcept
Definition at line 178 of file SystemSemaphore.cpp.
References m_impl.
Referenced by operator=().
key()
auto lmms::SystemSemaphore::key () const->conststd::string & inline noexcept
Definition at line 52 of file SystemSemaphore.h.
References key(), and m_key.
Referenced by SystemSemaphore(), SystemSemaphore(), SystemSemaphore(), and key().
operator=()
auto lmms::SystemSemaphore::operator= (SystemSemaphore && other) ->SystemSemaphore & default noexcept
References SystemSemaphore(), acquire(), and release().
release()
auto lmms::SystemSemaphore::release () ->bool noexcept
Definition at line 179 of file SystemSemaphore.cpp.
References m_impl.
Referenced by operator=().
Member Data Documentation
m_impl
std::unique_ptr<detail::SystemSemaphoreImpl> lmms::SystemSemaphore::m_impl private
Definition at line 56 of file SystemSemaphore.h.
Referenced by SystemSemaphore(), acquire(), and release().
m_key
std::string lmms::SystemSemaphore::m_key private
Definition at line 55 of file SystemSemaphore.h.
Referenced by SystemSemaphore(), SystemSemaphore(), and key().
The documentation for this class was generated from the following files:
include/SystemSemaphore.h
src/common/SystemSemaphore.cpp