LMMS: src/3rdparty/jack2/common/JackNetAPI.cpp File Reference
JackNetAPI.cpp File Reference
#include <assert.h>
#include <stdarg.h>
#include "JackNetInterface.h"
#include "JackAudioAdapterInterface.h"
Classes
struct jack_master_t
struct jack_slave_t
struct Jack::JackNetAdapter
Net adapter.
struct Jack::JackNetExtMaster
struct Jack::JackNetExtSlave
Namespaces
namespace Jack
Macros
#define LOG_LEVEL_ERROR 2
#define LOG_LEVEL_INFO 1
#define MASTER_NAME_SIZE 256
Typedefs
typedef int(* JackNetSlaveBufferSizeCallback) (jack_nframes_t nframes, void *arg)
typedef void(* JackNetSlaveErrorCallback) (int error_code, void *arg)
typedef int(* JackNetSlaveProcessCallback) (jack_nframes_t buffer_size, int audio_input, float **audio_input_buffer, int midi_input, void **midi_input_buffer, int audio_output, float **audio_output_buffer, int midi_output, void **midi_output_buffer, void *data)
typedef int(* JackNetSlaveRestartCallback) (void *arg)
typedef int(* JackNetSlaveSampleRateCallback) (jack_nframes_t nframes, void *arg)
typedef void(* JackNetSlaveShutdownCallback) (void *arg)
Enumerations
enum JackNetEncoder {
JackFloatEncoder = 0 ,
JackIntEncoder = 1 ,
JackCeltEncoder = 2 ,
JackOpusEncoder = 3
}
Functions
LIB_EXPORT int jack_adapter_pull_and_push (jack_adapter_t *adapter, float **input, float **output, unsigned int frames)
Pull input from and push output to adapter ringbuffer.
LIB_EXPORT int jack_adapter_push_and_pull (jack_adapter_t *adapter, float **input, float **output, unsigned int frames)
Push input to and pull output from adapter ringbuffer.
LIB_EXPORT jack_adapter_t * jack_create_adapter (int input, int output, jack_nframes_t host_buffer_size, jack_nframes_t host_sample_rate, jack_nframes_t adapted_buffer_size, jack_nframes_t adapted_sample_rate)
Create an adapter.
LIB_EXPORT int jack_destroy_adapter (jack_adapter_t *adapter)
Destroy an adapter.
LIB_EXPORT void jack_error (const char *fmt,...)
Call this function to log an error message.
LIB_EXPORT void jack_flush_adapter (jack_adapter_t *adapter)
Flush internal state of an adapter.
static void jack_format_and_log (int level, const char *prefix, const char *fmt, va_list ap)
LIB_EXPORT void jack_info (const char *fmt,...)
Call this function to log an information message.
LIB_EXPORT void jack_log (const char *fmt,...)
Call this function to log an information message but only when verbose mode is enabled.
LIB_EXPORT int jack_net_master_close (jack_net_master_t *net)
Close the network connection with the slave machine.
LIB_EXPORT jack_net_master_t * jack_net_master_open (const char *ip, int port, jack_master_t *request, jack_slave_t *result)
Open a network connection with the slave machine.
LIB_EXPORT int jack_net_master_recv (jack_net_master_t *net, int audio_input, float **audio_input_buffer, int midi_input, void **midi_input_buffer)
Receive sync and data from the network (complete buffer).
LIB_EXPORT int jack_net_master_recv_slice (jack_net_master_t *net, int audio_input, float **audio_input_buffer, int midi_input, void **midi_input_buffer, int frames)
Receive sync and data from the network (incomplete buffer).
LIB_EXPORT int jack_net_master_send (jack_net_master_t *net, int audio_output, float **audio_output_buffer, int midi_output, void **midi_output_buffer)
Send sync and data to the network (complete buffer).
LIB_EXPORT int jack_net_master_send_slice (jack_net_master_t *net, int audio_output, float **audio_output_buffer, int midi_output, void **midi_output_buffer, int frames)
Send sync and data to the network (incomplete buffer).
LIB_EXPORT int jack_net_slave_activate (jack_net_slave_t *net)
Start processing thread, the net_callback will start to be called.
LIB_EXPORT int jack_net_slave_close (jack_net_slave_t *net)
Close the network connection with the master machine.
LIB_EXPORT int jack_net_slave_deactivate (jack_net_slave_t *net)
Stop processing thread.
LIB_EXPORT int jack_net_slave_is_active (jack_net_slave_t *net)
Test if slave is still active.
LIB_EXPORT jack_net_slave_t * jack_net_slave_open (const char *ip, int port, const char *name, jack_slave_t *request, jack_master_t *result)
Open a network connection with the master machine.
LIB_EXPORT int jack_set_net_slave_buffer_size_callback (jack_net_slave_t *net, JackNetSlaveBufferSizeCallback bufsize_callback, void *arg)
Set network buffer size callback.
LIB_EXPORT int jack_set_net_slave_error_callback (jack_net_slave_t *net, JackNetSlaveErrorCallback error_callback, void *arg)
Set error restart callback.
LIB_EXPORT int jack_set_net_slave_process_callback (jack_net_slave_t *net, JackNetSlaveProcessCallback net_callback, void *arg)
Set network process callback.
LIB_EXPORT int jack_set_net_slave_restart_callback (jack_net_slave_t *net, JackNetSlaveRestartCallback restart_callback, void *arg)
Set network restart callback.
LIB_EXPORT int jack_set_net_slave_sample_rate_callback (jack_net_slave_t *net, JackNetSlaveSampleRateCallback samplerate_callback, void *arg)
Set network sample rate callback.
LIB_EXPORT int jack_set_net_slave_shutdown_callback (jack_net_slave_t *net, JackNetSlaveShutdownCallback shutdown_callback, void *arg)
Set network shutdown callback.
Macro Definition Documentation
LOG_LEVEL_ERROR
#define LOG_LEVEL_ERROR 2
Definition at line 135 of file JackNetAPI.cpp.
LOG_LEVEL_INFO
#define LOG_LEVEL_INFO 1
Definition at line 134 of file JackNetAPI.cpp.
MASTER_NAME_SIZE
#define MASTER_NAME_SIZE 256
Definition at line 33 of file JackNetAPI.cpp.
Typedef Documentation
JackNetSlaveBufferSizeCallback
typedef int(* JackNetSlaveBufferSizeCallback) (jack_nframes_t nframes, void *arg)
Definition at line 86 of file JackNetAPI.cpp.
JackNetSlaveErrorCallback
typedef void(* JackNetSlaveErrorCallback) (int error_code, void *arg)
Definition at line 90 of file JackNetAPI.cpp.
JackNetSlaveProcessCallback
typedef int(* JackNetSlaveProcessCallback) (jack_nframes_t buffer_size, int audio_input, float **audio_input_buffer, int midi_input, void **midi_input_buffer, int audio_output, float **audio_output_buffer, int midi_output, void **midi_output_buffer, void *data)
Definition at line 75 of file JackNetAPI.cpp.
JackNetSlaveRestartCallback
typedef int(* JackNetSlaveRestartCallback) (void *arg)
Definition at line 89 of file JackNetAPI.cpp.
JackNetSlaveSampleRateCallback
typedef int(* JackNetSlaveSampleRateCallback) (jack_nframes_t nframes, void *arg)
Definition at line 87 of file JackNetAPI.cpp.
JackNetSlaveShutdownCallback
typedef void(* JackNetSlaveShutdownCallback) (void *arg)
Definition at line 88 of file JackNetAPI.cpp.
Enumeration Type Documentation
JackNetEncoder
enum JackNetEncoder
Enumerator
JackFloatEncoder
JackIntEncoder
JackCeltEncoder
JackOpusEncoder
Definition at line 35 of file JackNetAPI.cpp.
Function Documentation
jack_adapter_pull_and_push()
LIB_EXPORT int jack_adapter_pull_and_push (jack_adapter_t * adapter, float ** input, float ** output, unsigned int frames)
Pull input from and push output to adapter ringbuffer.
Parameters
adapter the adapter
input an array of audio input buffers
output an array of audio output buffers
frames number of frames
Returns
0 on success, otherwise a non-zero error code
Definition at line 1203 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackAudioAdapterInterface::PullAndPush().
jack_adapter_push_and_pull()
LIB_EXPORT int jack_adapter_push_and_pull (jack_adapter_t * adapter, float ** input, float ** output, unsigned int frames)
Push input to and pull output from adapter ringbuffer.
Parameters
adapter the adapter
input an array of audio input buffers
output an array of audio output buffers
frames number of frames
Returns
0 on success, otherwise a non-zero error code
Definition at line 1197 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackAudioAdapterInterface::PushAndPull().
jack_create_adapter()
LIB_EXPORT jack_adapter_t * jack_create_adapter (int input, int output, jack_nframes_t host_buffer_size, jack_nframes_t host_sample_rate, jack_nframes_t adapted_buffer_size, jack_nframes_t adapted_sample_rate)
Create an adapter.
Parameters
input number of audio inputs
output of audio outputs
host_buffer_size the host buffer size in frames
host_sample_rate the host buffer sample rate
adapted_buffer_size the adapted buffer size in frames
adapted_sample_rate the adapted buffer sample rate
Returns
0 on success, otherwise a non-zero error code
Definition at line 1172 of file JackNetAPI.cpp.
References LIB_EXPORT.
jack_destroy_adapter()
LIB_EXPORT int jack_destroy_adapter (jack_adapter_t * adapter)
Destroy an adapter.
Parameters
adapter the adapter to be destroyed
Returns
0 on success, otherwise a non-zero error code
Definition at line 1185 of file JackNetAPI.cpp.
References LIB_EXPORT.
jack_flush_adapter()
LIB_EXPORT void jack_flush_adapter (jack_adapter_t * adapter)
Flush internal state of an adapter.
Parameters
adapter the adapter to be flushed
Returns
0 on success, otherwise a non-zero error code
Definition at line 1191 of file JackNetAPI.cpp.
References Jack::JackNetAdapter::Flush(), and LIB_EXPORT.
jack_format_and_log()
void jack_format_and_log (int level, const char * prefix, const char * fmt, va_list ap) static
Definition at line 1209 of file JackNetAPI.cpp.
Referenced by jack_error(), jack_info(), and jack_log().
jack_net_master_close()
LIB_EXPORT int jack_net_master_close (jack_net_master_t * net)
Close the network connection with the slave machine.
Parameters
net the network connection to be closed
Returns
0 on success, otherwise a non-zero error code
Definition at line 1138 of file JackNetAPI.cpp.
References Jack::JackNetExtMaster::Close(), and LIB_EXPORT.
jack_net_master_open()
LIB_EXPORT jack_net_master_t * jack_net_master_open (const char * ip, int port, jack_master_t * request, jack_slave_t * result)
Open a network connection with the slave machine.
Parameters
ip the multicast address of the master
port the connection port
request a connection request structure
result a connection result structure
Returns
Opaque net handle if successful or NULL in case of error.
Definition at line 1127 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtMaster::Open().
jack_net_master_recv()
LIB_EXPORT int jack_net_master_recv (jack_net_master_t * net, int audio_input, float ** audio_input_buffer, int midi_input, void ** midi_input_buffer)
Receive sync and data from the network (complete buffer).
Parameters
net the network connection
audio_input number of audio inputs
audio_input_buffer an array of audio input buffers
midi_input number of MIDI inputs
midi_input_buffer an array of MIDI input buffers
Returns
zero on success, non-zero on error
Definition at line 1146 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtMaster::Read().
jack_net_master_recv_slice()
LIB_EXPORT int jack_net_master_recv_slice (jack_net_master_t * net, int audio_input, float ** audio_input_buffer, int midi_input, void ** midi_input_buffer, int frames)
Receive sync and data from the network (incomplete buffer).
Parameters
net the network connection
audio_input number of audio inputs
audio_input_buffer an array of audio input buffers
midi_input number of MIDI inputs
midi_input_buffer an array of MIDI input buffers
frames the number of frames to receive
Returns
zero on success, non-zero on error
Definition at line 1158 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtMaster::Read().
jack_net_master_send()
LIB_EXPORT int jack_net_master_send (jack_net_master_t * net, int audio_output, float ** audio_output_buffer, int midi_output, void ** midi_output_buffer)
Send sync and data to the network (complete buffer).
Parameters
net the network connection
audio_output number of audio outputs
audio_output_buffer an array of audio output buffers
midi_output number of MIDI outputs
midi_output_buffer an array of MIDI output buffers
Returns
zero on success, non-zero on error
Definition at line 1152 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtMaster::Write().
jack_net_master_send_slice()
LIB_EXPORT int jack_net_master_send_slice (jack_net_master_t * net, int audio_output, float ** audio_output_buffer, int midi_output, void ** midi_output_buffer, int frames)
Send sync and data to the network (incomplete buffer).
Parameters
net the network connection
audio_output number of audio outputs
audio_output_buffer an array of audio output buffers
midi_output number of MIDI outputs
midi_output_buffer an array of MIDI output buffers
frames the number of frames to send
Returns
zero on success, non-zero on error
Definition at line 1164 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtMaster::Write().
jack_net_slave_activate()
LIB_EXPORT int jack_net_slave_activate (jack_net_slave_t * net)
Start processing thread, the net_callback will start to be called.
Parameters
net the network connection
Returns
0 on success, otherwise a non-zero error code
Definition at line 1077 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::Start().
jack_net_slave_close()
LIB_EXPORT int jack_net_slave_close (jack_net_slave_t * net)
Close the network connection with the master machine.
Parameters
net the network connection to be closed
Returns
0 on success, otherwise a non-zero error code
Definition at line 1063 of file JackNetAPI.cpp.
References Jack::JackNetExtSlave::Close(), and LIB_EXPORT.
jack_net_slave_deactivate()
LIB_EXPORT int jack_net_slave_deactivate (jack_net_slave_t * net)
Stop processing thread.
Parameters
net the network connection
Returns
0 on success, otherwise a non-zero error code
Definition at line 1083 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::Stop().
jack_net_slave_is_active()
LIB_EXPORT int jack_net_slave_is_active (jack_net_slave_t * net)
Test if slave is still active.
Parameters
net the network connection
Returns
a boolean
Definition at line 1089 of file JackNetAPI.cpp.
References Jack::JackNetExtSlave::IsRunning(), and LIB_EXPORT.
jack_net_slave_open()
LIB_EXPORT jack_net_slave_t * jack_net_slave_open (const char * ip, int port, const char * name, jack_slave_t * request, jack_master_t * result)
Open a network connection with the master machine.
Parameters
ip the multicast address of the master
port the connection port
name the JACK client name
request a connection request structure
result a connection result structure
Returns
Opaque net handle if successful or NULL in case of error.
Definition at line 1052 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::Open().
jack_set_net_slave_buffer_size_callback()
LIB_EXPORT int jack_set_net_slave_buffer_size_callback (jack_net_slave_t * net, JackNetSlaveBufferSizeCallback bufsize_callback, void * arg)
Set network buffer size callback.
Parameters
net the network connection
bufsize_callback the buffer size callback
arg pointer to a client supplied structure
Returns
0 on success, otherwise a non-zero error code
Definition at line 1095 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::SetBufferSizeCallback().
jack_set_net_slave_error_callback()
LIB_EXPORT int jack_set_net_slave_error_callback (jack_net_slave_t * net, JackNetSlaveErrorCallback error_callback, void * arg)
Set error restart callback.
Parameters
net the network connection
error_callback the error callback
arg pointer to a client supplied structure
Returns
0 on success, otherwise a non-zero error code
Definition at line 1119 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::SetErrorCallback().
jack_set_net_slave_process_callback()
LIB_EXPORT int jack_set_net_slave_process_callback (jack_net_slave_t * net, JackNetSlaveProcessCallback net_callback, void * arg)
Set network process callback.
Parameters
net the network connection
net_callback the process callback
arg pointer to a client supplied structure
Returns
0 on success, otherwise a non-zero error code
Definition at line 1071 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::SetProcessCallback().
jack_set_net_slave_restart_callback()
LIB_EXPORT int jack_set_net_slave_restart_callback (jack_net_slave_t * net, JackNetSlaveRestartCallback restart_callback, void * arg)
Set network restart callback.
Parameters
net the network connection
restart_callback the shutdown callback
arg pointer to a client supplied structure
Returns
0 on success, otherwise a non-zero error code
Definition at line 1113 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::SetRestartCallback().
jack_set_net_slave_sample_rate_callback()
LIB_EXPORT int jack_set_net_slave_sample_rate_callback (jack_net_slave_t * net, JackNetSlaveSampleRateCallback samplerate_callback, void * arg)
Set network sample rate callback.
Parameters
net the network connection
samplerate_callback the sample rate callback
arg pointer to a client supplied structure
Returns
0 on success, otherwise a non-zero error code
Definition at line 1101 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::SetSampleRateCallback().
jack_set_net_slave_shutdown_callback()
LIB_EXPORT int jack_set_net_slave_shutdown_callback (jack_net_slave_t * net, JackNetSlaveShutdownCallback shutdown_callback, void * arg)
Set network shutdown callback.
Parameters
net the network connection
shutdown_callback the shutdown callback
arg pointer to a client supplied structure
Returns
0 on success, otherwise a non-zero error code
Definition at line 1107 of file JackNetAPI.cpp.
References LIB_EXPORT, and Jack::JackNetExtSlave::SetShutdownCallback().