LMMS: hiir::StageProc2F64Sse2< REMAINING > Class Template Reference
hiir::StageProc2F64Sse2< REMAINING > Class Template Reference
#include <StageProc2F64Sse2.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m128d &spl_0, __m128d &spl_1, StageDataF64Sse2 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m128d &spl_0, __m128d &spl_1, StageDataF64Sse2 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m128d &spl_0, __m128d &spl_1, StageDataF64Sse2 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m128d &spl_0, __m128d &spl_1, StageDataF64Sse2 *stage_arr) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m128d &spl_0, __m128d &spl_1, StageDataF64Sse2 *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m128d &spl_0, __m128d &spl_1, StageDataF64Sse2 *stage_arr) noexcept
Private Member Functions
StageProc2F64Sse2 ()=delete
StageProc2F64Sse2 (const StageProc2F64Sse2< REMAINING > &other)=delete
StageProc2F64Sse2 (StageProc2F64Sse2< REMAINING > &&other)=delete
~StageProc2F64Sse2 ()=delete
bool operator!= (const StageProc2F64Sse2< REMAINING > &other)=delete
StageProc2F64Sse2< REMAINING > & operator= (const StageProc2F64Sse2< REMAINING > &other)=delete
StageProc2F64Sse2< REMAINING > & operator= (StageProc2F64Sse2< REMAINING > &&other)=delete
bool operator== (const StageProc2F64Sse2< REMAINING > &other)=delete
Detailed Description
template<int REMAINING>
class hiir::StageProc2F64Sse2< REMAINING >
Definition at line 48 of file StageProc2F64Sse2.h.
Constructor & Destructor Documentation
StageProc2F64Sse2() [1/3]
template<int REMAINING> hiir::StageProc2F64Sse2< REMAINING >::StageProc2F64Sse2 () private delete
Referenced by process_sample_neg(), and process_sample_pos().
StageProc2F64Sse2() [2/3]
template<int REMAINING> hiir::StageProc2F64Sse2< REMAINING >::StageProc2F64Sse2 (const StageProc2F64Sse2< REMAINING > & other) private delete
StageProc2F64Sse2() [3/3]
template<int REMAINING> hiir::StageProc2F64Sse2< REMAINING >::StageProc2F64Sse2 (StageProc2F64Sse2< REMAINING > && other) private delete
~StageProc2F64Sse2()
template<int REMAINING> hiir::StageProc2F64Sse2< REMAINING >::~StageProc2F64Sse2 () private delete
Member Function Documentation
operator!=()
template<int REMAINING> bool hiir::StageProc2F64Sse2< REMAINING >::operator!= (const StageProc2F64Sse2< REMAINING > & other) private delete
operator=() [1/2]
template<int REMAINING> StageProc2F64Sse2< REMAINING > & hiir::StageProc2F64Sse2< REMAINING >::operator= (const StageProc2F64Sse2< REMAINING > & other) private delete
operator=() [2/2]
template<int REMAINING> StageProc2F64Sse2< REMAINING > & hiir::StageProc2F64Sse2< REMAINING >::operator= (StageProc2F64Sse2< REMAINING > && other) private delete
operator==()
template<int REMAINING> bool hiir::StageProc2F64Sse2< REMAINING >::operator== (const StageProc2F64Sse2< REMAINING > & other) private delete
process_sample_neg() [1/3]
template<int REMAINING> void hiir::StageProc2F64Sse2< REMAINING >::process_sample_neg (const int nbr_coefs, __m128d & spl_0, __m128d & spl_1, StageDataF64Sse2 * stage_arr) static noexcept
Definition at line 147 of file StageProc2F64Sse2.hpp.
References StageProc2F64Sse2(), and process_sample_neg().
Referenced by hiir::PhaseHalfPi2F64Sse2< NC >::process_block(), hiir::PhaseHalfPi2F64Sse2< NC >::process_sample(), and process_sample_neg().
process_sample_neg() [2/3]
hiir_FORCEINLINE void hiir::StageProc2F64Sse2< 0 >::process_sample_neg (const int nbr_coefs, __m128d & spl_0, __m128d & spl_1, StageDataF64Sse2 * stage_arr) noexcept
Definition at line 136 of file StageProc2F64Sse2.hpp.
References hiir_FORCEINLINE.
process_sample_neg() [3/3]
hiir_FORCEINLINE void hiir::StageProc2F64Sse2< 1 >::process_sample_neg (const int nbr_coefs, __m128d & spl_0, __m128d & spl_1, StageDataF64Sse2 * stage_arr) noexcept
Definition at line 114 of file StageProc2F64Sse2.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [1/3]
template<int REMAINING> void hiir::StageProc2F64Sse2< REMAINING >::process_sample_pos (const int nbr_coefs, __m128d & spl_0, __m128d & spl_1, StageDataF64Sse2 * stage_arr) static noexcept
Definition at line 78 of file StageProc2F64Sse2.hpp.
References StageProc2F64Sse2(), and process_sample_pos().
Referenced by hiir::HalfBand2F64Sse2< NC >::process_2_paths(), hiir::HalfBand2F64Sse2< NC >::process_block_2_paths(), hiir::Downsampler2x2F64Sse2< NC >::process_sample(), hiir::Upsampler2x2F64Sse2< NC >::process_sample(), process_sample_pos(), and hiir::Downsampler2x2F64Sse2< NC >::process_sample_split().
process_sample_pos() [2/3]
hiir_FORCEINLINE void hiir::StageProc2F64Sse2< 0 >::process_sample_pos (const int nbr_coefs, __m128d & spl_0, __m128d & spl_1, StageDataF64Sse2 * stage_arr) noexcept
Definition at line 67 of file StageProc2F64Sse2.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [3/3]
hiir_FORCEINLINE void hiir::StageProc2F64Sse2< 1 >::process_sample_pos (const int nbr_coefs, __m128d & spl_0, __m128d & spl_1, StageDataF64Sse2 * stage_arr) noexcept
Definition at line 45 of file StageProc2F64Sse2.hpp.
References hiir_FORCEINLINE.
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProc2F64Sse2.h
src/3rdparty/hiir/hiir/StageProc2F64Sse2.hpp