LMMS: lmms::gui::PatternTrackView Class Reference
lmms::gui::PatternTrackView Class Reference
#include <PatternTrackView.h>
Public Slots
void clickedTrackLabel ()
Public Member Functions
PatternTrackView (PatternTrack *pt, TrackContainerView *tcv)
~PatternTrackView () override
bool close () override
Close this track View.
const PatternTrack * getPatternTrack () const
Public Member Functions inherited from lmms::gui::TrackView
TrackView (Track *_track, TrackContainerView *tcv)
Create a new track View.
~TrackView () override=default
virtual QMenu * createMixerMenu (QString title, QString newMixerLabel)
Create a menu for assigning/creating channels for this track.
Track * getTrack ()
const Track * getTrack () const
TrackContentWidget * getTrackContentWidget ()
TrackOperationsWidget * getTrackOperationsWidget ()
QWidget * getTrackSettingsWidget ()
bool isMovingTrack () const
TrackContainerView * trackContainerView ()
virtual void update ()
Update this track View and all its content objects.
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Private Attributes
PatternTrack * m_patternTrack
TrackLabelButton * m_trackLabel
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::TrackView
void dragEnterEvent (QDragEnterEvent *dee) override
Start a drag event on this track View.
void dropEvent (QDropEvent *de) override
Accept a drop event on this track View.
void loadSettings (const QDomElement &element) override
void modelChanged () override
Register that the model of this track View has changed.
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse move event on this track View.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press event on this track View.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release event on this track View.
QString nodeName () const override
void paintEvent (QPaintEvent *pe) override
Repaint this track View.
void resizeEvent (QResizeEvent *re) override
Resize this track View.
void saveSettings (QDomDocument &doc, QDomElement &element) override
void wheelEvent (QWheelEvent *we) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 41 of file PatternTrackView.h.
Constructor & Destructor Documentation
PatternTrackView()
lmms::gui::PatternTrackView::PatternTrackView (PatternTrack * pt, TrackContainerView * tcv)
Definition at line 38 of file PatternTrackView.cpp.
References lmms::gui::TrackView::TrackView(), clickedTrackLabel(), lmms::embed::getIconPixmap(), lmms::gui::TrackView::getTrackSettingsWidget(), m_patternTrack, m_trackLabel, lmms::gui::ModelView::setModel(), and lmms::gui::TrackView::TrackLabelButton.
~PatternTrackView()
lmms::gui::PatternTrackView::~PatternTrackView () override
Definition at line 58 of file PatternTrackView.cpp.
References lmms::gui::getGUI(), lmms::gui::PatternEditorWindow::m_editor, m_patternTrack, lmms::gui::GuiApplication::patternEditor(), lmms::gui::PatternEditor::removeViewsForPattern(), and lmms::PatternTrack::s_infoMap.
Member Function Documentation
clickedTrackLabel
void lmms::gui::PatternTrackView::clickedTrackLabel () slot
Definition at line 75 of file PatternTrackView.cpp.
References lmms::gui::getGUI(), m_patternTrack, lmms::gui::GuiApplication::mainWindow(), lmms::Engine::patternStore(), and lmms::gui::MainWindow::togglePatternEditorWin().
Referenced by PatternTrackView().
close()
bool lmms::gui::PatternTrackView::close () override virtual
Close this track View.
Reimplemented from lmms::gui::TrackView.
Definition at line 66 of file PatternTrackView.cpp.
References lmms::gui::TrackView::close(), lmms::gui::getGUI(), lmms::gui::PatternEditorWindow::m_editor, m_patternTrack, lmms::gui::GuiApplication::patternEditor(), lmms::gui::PatternEditor::removeViewsForPattern(), and lmms::PatternTrack::s_infoMap.
getPatternTrack()
const PatternTrack * lmms::gui::PatternTrackView::getPatternTrack () const inline
Definition at line 50 of file PatternTrackView.h.
References m_patternTrack.
Member Data Documentation
m_patternTrack
PatternTrack* lmms::gui::PatternTrackView::m_patternTrack private
Definition at line 61 of file PatternTrackView.h.
Referenced by PatternTrackView(), ~PatternTrackView(), clickedTrackLabel(), close(), and getPatternTrack().
m_trackLabel
TrackLabelButton* lmms::gui::PatternTrackView::m_trackLabel private
Definition at line 62 of file PatternTrackView.h.
Referenced by PatternTrackView().
The documentation for this class was generated from the following files:
include/PatternTrackView.h
src/gui/tracks/PatternTrackView.cpp