LMMS: Jack::JackNetUnixSocket Class Reference
Jack::JackNetUnixSocket Class Reference
#include <JackNetUnixSocket.h>
Public Member Functions
JackNetUnixSocket ()
JackNetUnixSocket (const char *ip, int port)
JackNetUnixSocket (const JackNetUnixSocket &)
~JackNetUnixSocket ()
int Bind ()
int BindWith (const char *ip)
int BindWith (int port)
int CatchHost (void *buffer, size_t nbytes, int flags)
void Close ()
int Connect ()
int ConnectTo (const char *ip)
net_error_t GetError ()
int GetName (char *name)
int GetOption (int level, int optname, void *optval, socklen_t *optlen)
int GetPort ()
char * GetRecvIP ()
char * GetSendIP ()
bool IsLocal (char *ip)
bool IsSocket ()
int JoinMCastGroup (const char *mcast_ip)
int NewSocket ()
JackNetUnixSocket & operator= (const JackNetUnixSocket &socket)
void PrintError ()
int Recv (void *buffer, size_t nbytes, int flags)
int RecvFrom (void *buffer, size_t nbytes, int flags)
void Reset ()
int Send (const void *buffer, size_t nbytes, int flags)
int SendTo (const void *buffer, size_t nbytes, int flags)
int SendTo (const void *buffer, size_t nbytes, int flags, const char *ip)
int SetAddress (const char *ip, int port)
int SetLocalLoop ()
int SetOption (int level, int optname, const void *optval, socklen_t optlen)
void SetPort (int port)
int SetTimeOut (int us)
Private Attributes
int fPort
struct sockaddr_in fRecvAddr
struct sockaddr_in fSendAddr
int fSockfd
int fTimeOut
Detailed Description
Definition at line 40 of file JackNetUnixSocket.h.
Constructor & Destructor Documentation
JackNetUnixSocket() [1/3]
Jack::JackNetUnixSocket::JackNetUnixSocket ()
Definition at line 43 of file JackNetUnixSocket.cpp.
References fPort, fRecvAddr, fSendAddr, fSockfd, and fTimeOut.
Referenced by JackNetUnixSocket(), and operator=().
JackNetUnixSocket() [2/3]
Jack::JackNetUnixSocket::JackNetUnixSocket (const char * ip, int port)
Definition at line 56 of file JackNetUnixSocket.cpp.
References fPort, fRecvAddr, fSendAddr, fSockfd, and fTimeOut.
JackNetUnixSocket() [3/3]
Jack::JackNetUnixSocket::JackNetUnixSocket (const JackNetUnixSocket & socket)
Definition at line 71 of file JackNetUnixSocket.cpp.
References JackNetUnixSocket(), fPort, fRecvAddr, fSendAddr, fSockfd, and fTimeOut.
~JackNetUnixSocket()
Jack::JackNetUnixSocket::~JackNetUnixSocket ()
Definition at line 80 of file JackNetUnixSocket.cpp.
References Close().
Member Function Documentation
Bind()
int Jack::JackNetUnixSocket::Bind ()
Definition at line 163 of file JackNetUnixSocket.cpp.
References fRecvAddr, and fSockfd.
Referenced by BindWith(), and BindWith().
BindWith() [1/2]
int Jack::JackNetUnixSocket::BindWith (const char * ip)
Definition at line 168 of file JackNetUnixSocket.cpp.
References Bind(), and fRecvAddr.
BindWith() [2/2]
int Jack::JackNetUnixSocket::BindWith (int port)
Definition at line 177 of file JackNetUnixSocket.cpp.
References Bind(), and fRecvAddr.
CatchHost()
int Jack::JackNetUnixSocket::CatchHost (void * buffer, size_t nbytes, int flags)
Definition at line 462 of file JackNetUnixSocket.cpp.
References fSendAddr, fSockfd, and jack_log().
Close()
void Jack::JackNetUnixSocket::Close ()
Definition at line 197 of file JackNetUnixSocket.cpp.
References fSockfd.
Referenced by ~JackNetUnixSocket(), Jack::JackNetMasterInterface::Exit(), and NewSocket().
Connect()
int Jack::JackNetUnixSocket::Connect ()
Definition at line 183 of file JackNetUnixSocket.cpp.
References fSendAddr, and fSockfd.
Referenced by ConnectTo().
ConnectTo()
int Jack::JackNetUnixSocket::ConnectTo (const char * ip)
Definition at line 188 of file JackNetUnixSocket.cpp.
References Connect(), and fSendAddr.
GetError()
net_error_t Jack::JackNetUnixSocket::GetError ()
Definition at line 477 of file JackNetUnixSocket.cpp.
References Jack::NET_CONN_ERROR, and Jack::NET_NO_DATA.
GetName()
int Jack::JackNetUnixSocket::GetName (char * name)
Definition at line 257 of file JackNetUnixSocket.cpp.
GetOption()
int Jack::JackNetUnixSocket::GetOption (int level, int optname, void * optval, socklen_t * optlen)
Definition at line 276 of file JackNetUnixSocket.cpp.
References fSockfd.
GetPort()
int Jack::JackNetUnixSocket::GetPort ()
Definition at line 230 of file JackNetUnixSocket.cpp.
References fPort.
GetRecvIP()
char * Jack::JackNetUnixSocket::GetRecvIP ()
Definition at line 251 of file JackNetUnixSocket.cpp.
References fRecvAddr.
GetSendIP()
char * Jack::JackNetUnixSocket::GetSendIP ()
Definition at line 246 of file JackNetUnixSocket.cpp.
References fSendAddr.
IsLocal()
bool Jack::JackNetUnixSocket::IsLocal (char * ip)
Definition at line 139 of file JackNetUnixSocket.cpp.
References Jack::GetHostName(), and i.
IsSocket()
bool Jack::JackNetUnixSocket::IsSocket ()
Definition at line 217 of file JackNetUnixSocket.cpp.
References fSockfd.
JoinMCastGroup()
int Jack::JackNetUnixSocket::JoinMCastGroup (const char * mcast_ip)
Definition at line 262 of file JackNetUnixSocket.cpp.
References SetOption().
NewSocket()
int Jack::JackNetUnixSocket::NewSocket ()
Definition at line 97 of file JackNetUnixSocket.cpp.
References Close(), fSockfd, NET_ERROR_CODE, Reset(), and StrError.
Referenced by Jack::JackNetMasterInterface::Exit().
operator=()
JackNetUnixSocket & Jack::JackNetUnixSocket::operator= (const JackNetUnixSocket & socket)
Definition at line 85 of file JackNetUnixSocket.cpp.
References JackNetUnixSocket(), fPort, fRecvAddr, fSendAddr, and fSockfd.
PrintError()
void Jack::JackNetUnixSocket::PrintError ()
Definition at line 500 of file JackNetUnixSocket.cpp.
References jack_error.
Recv()
int Jack::JackNetUnixSocket::Recv (void * buffer, size_t nbytes, int flags)
Definition at line 448 of file JackNetUnixSocket.cpp.
References fSockfd, and jack_error.
RecvFrom()
int Jack::JackNetUnixSocket::RecvFrom (void * buffer, size_t nbytes, int flags)
Definition at line 433 of file JackNetUnixSocket.cpp.
References fRecvAddr, fSockfd, and jack_error.
Reset()
void Jack::JackNetUnixSocket::Reset ()
Definition at line 205 of file JackNetUnixSocket.cpp.
References fPort, fRecvAddr, and fSendAddr.
Referenced by NewSocket().
Send()
int Jack::JackNetUnixSocket::Send (const void * buffer, size_t nbytes, int flags)
Definition at line 419 of file JackNetUnixSocket.cpp.
References fSockfd, and jack_error.
SendTo() [1/2]
int Jack::JackNetUnixSocket::SendTo (const void * buffer, size_t nbytes, int flags)
Definition at line 390 of file JackNetUnixSocket.cpp.
References fSendAddr, fSockfd, and jack_error.
Referenced by Jack::JackNetMasterInterface::Exit(), and SendTo().
SendTo() [2/2]
int Jack::JackNetUnixSocket::SendTo (const void * buffer, size_t nbytes, int flags, const char * ip)
Definition at line 404 of file JackNetUnixSocket.cpp.
References fPort, fSendAddr, and SendTo().
SetAddress()
int Jack::JackNetUnixSocket::SetAddress (const char * ip, int port)
Definition at line 236 of file JackNetUnixSocket.cpp.
References fSendAddr.
SetLocalLoop()
int Jack::JackNetUnixSocket::SetLocalLoop ()
Definition at line 383 of file JackNetUnixSocket.cpp.
References SetOption().
SetOption()
int Jack::JackNetUnixSocket::SetOption (int level, int optname, const void * optval, socklen_t optlen)
Definition at line 271 of file JackNetUnixSocket.cpp.
References fSockfd.
Referenced by JoinMCastGroup(), SetLocalLoop(), and SetTimeOut().
SetPort()
void Jack::JackNetUnixSocket::SetPort (int port)
Definition at line 223 of file JackNetUnixSocket.cpp.
References fPort, fRecvAddr, and fSendAddr.
SetTimeOut()
int Jack::JackNetUnixSocket::SetTimeOut (int us)
Definition at line 362 of file JackNetUnixSocket.cpp.
References jack_log(), and SetOption().
Member Data Documentation
fPort
int Jack::JackNetUnixSocket::fPort private
Definition at line 45 of file JackNetUnixSocket.h.
Referenced by JackNetUnixSocket(), JackNetUnixSocket(), JackNetUnixSocket(), GetPort(), operator=(), Reset(), SendTo(), and SetPort().
fRecvAddr
struct sockaddr_in Jack::JackNetUnixSocket::fRecvAddr private
Definition at line 49 of file JackNetUnixSocket.h.
Referenced by JackNetUnixSocket(), JackNetUnixSocket(), JackNetUnixSocket(), Bind(), BindWith(), BindWith(), GetRecvIP(), operator=(), RecvFrom(), Reset(), and SetPort().
fSendAddr
struct sockaddr_in Jack::JackNetUnixSocket::fSendAddr private
Definition at line 48 of file JackNetUnixSocket.h.
Referenced by JackNetUnixSocket(), JackNetUnixSocket(), JackNetUnixSocket(), CatchHost(), Connect(), ConnectTo(), GetSendIP(), operator=(), Reset(), SendTo(), SendTo(), SetAddress(), and SetPort().
fSockfd
int Jack::JackNetUnixSocket::fSockfd private
Definition at line 44 of file JackNetUnixSocket.h.
Referenced by JackNetUnixSocket(), JackNetUnixSocket(), JackNetUnixSocket(), Bind(), CatchHost(), Close(), Connect(), GetOption(), IsSocket(), NewSocket(), operator=(), Recv(), RecvFrom(), Send(), SendTo(), and SetOption().
fTimeOut
int Jack::JackNetUnixSocket::fTimeOut private
Definition at line 46 of file JackNetUnixSocket.h.
Referenced by JackNetUnixSocket(), JackNetUnixSocket(), and JackNetUnixSocket().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/posix/JackNetUnixSocket.h
src/3rdparty/jack2/posix/JackNetUnixSocket.cpp