LMMS: lmms::ControllerConnection Class Reference
lmms::ControllerConnection Class Reference
#include <ControllerConnection.h>
Public Slots
void deleteConnection ()
Signals
void valueChanged ()
Public Member Functions
ControllerConnection (Controller *_controller)
ControllerConnection (int _controllerId)
~ControllerConnection () override
float currentValue (int _offset)
Controller * getController ()
bool isFinalized ()
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
void setController (Controller *_controller)
void setController (int _controllerId)
void setTargetName (const QString &_name)
QString targetName () const
ValueBuffer * valueBuffer ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static const QString classNodeName ()
static void finalizeConnections ()
Protected Attributes
Controller * m_controller
int m_controllerId
bool m_ownsController
QString m_targetName
Static Protected Attributes
static ControllerConnectionVector s_connections
Friends
class gui::ControllerConnectionDialog
Additional Inherited Members
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 52 of file ControllerConnection.h.
Constructor & Destructor Documentation
ControllerConnection() [1/2]
lmms::ControllerConnection::ControllerConnection (Controller * _controller)
Definition at line 42 of file ControllerConnection.cpp.
References lmms::Controller::create(), lmms::Controller::Dummy, m_controller, m_controllerId, m_ownsController, s_connections, and setController().
Referenced by finalizeConnections().
ControllerConnection() [2/2]
lmms::ControllerConnection::ControllerConnection (int _controllerId)
Definition at line 62 of file ControllerConnection.cpp.
References m_controller, m_controllerId, m_ownsController, and s_connections.
~ControllerConnection()
lmms::ControllerConnection::~ControllerConnection () override
Definition at line 73 of file ControllerConnection.cpp.
References lmms::Controller::Dummy, m_controller, m_ownsController, and s_connections.
Member Function Documentation
classNodeName()
const QString lmms::ControllerConnection::classNodeName () inline static
Definition at line 98 of file ControllerConnection.h.
Referenced by lmms::InstrumentTrack::loadTrackSpecificSettings(), and nodeName().
currentValue()
float lmms::ControllerConnection::currentValue (int _offset) inline
Definition at line 71 of file ControllerConnection.h.
References m_controller.
Referenced by lmms::AutomatableModel::controllerValue().
deleteConnection
void lmms::ControllerConnection::deleteConnection () slot
Definition at line 236 of file ControllerConnection.cpp.
Referenced by setController().
finalizeConnections()
void lmms::ControllerConnection::finalizeConnections () static
Definition at line 160 of file ControllerConnection.cpp.
References ControllerConnection(), lmms::Controller::Dummy, getController(), lmms::Engine::getSong(), i, isFinalized(), m_controllerId, s_connections, setController(), and lmms::Controller::type().
Referenced by lmms::Song::loadProject().
getController()
Controller * lmms::ControllerConnection::getController () inline
Definition at line 62 of file ControllerConnection.h.
References m_controller.
Referenced by lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog(), finalizeConnections(), lmms::Controller::hasModel(), and lmms::AutomatableModel::valueBuffer().
isFinalized()
bool lmms::ControllerConnection::isFinalized () inline
Definition at line 88 of file ControllerConnection.h.
References m_controllerId.
Referenced by finalizeConnections().
loadSettings()
void lmms::ControllerConnection::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 205 of file ControllerConnection.cpp.
References lmms::Controller::create(), lmms::Controller::Dummy, lmms::Engine::getSong(), m_controller, m_controllerId, and setController().
nodeName()
QString lmms::ControllerConnection::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 103 of file ControllerConnection.h.
References classNodeName().
saveSettings()
void lmms::ControllerConnection::saveSettings (QDomDocument & _doc, QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 181 of file ControllerConnection.cpp.
References lmms::Song::controllers(), lmms::Engine::getSong(), m_controller, and m_ownsController.
setController() [1/2]
void lmms::ControllerConnection::setController (Controller * _controller)
Definition at line 99 of file ControllerConnection.cpp.
References lmms::Controller::addConnection(), lmms::Controller::create(), deleteConnection(), lmms::Controller::Dummy, m_controller, m_controllerId, m_ownsController, lmms::Controller::Midi, lmms::Controller::type(), and valueChanged().
Referenced by ControllerConnection(), lmms::gui::AutomatableModelViewSlots::execConnectionDialog(), finalizeConnections(), and loadSettings().
setController() [2/2]
void lmms::ControllerConnection::setController (int _controllerId) inline
Definition at line 92 of file ControllerConnection.cpp.
setTargetName()
void lmms::ControllerConnection::setTargetName (const QString & _name) inline
Definition at line 142 of file ControllerConnection.cpp.
References m_controller, and m_targetName.
targetName()
QString lmms::ControllerConnection::targetName () const inline
Definition at line 83 of file ControllerConnection.h.
References m_targetName.
valueBuffer()
ValueBuffer * lmms::ControllerConnection::valueBuffer () inline
Definition at line 76 of file ControllerConnection.h.
References m_controller.
valueChanged
void lmms::ControllerConnection::valueChanged () signal
Referenced by setController().
Friends And Related Symbol Documentation
gui::ControllerConnectionDialog
friend class gui::ControllerConnectionDialog friend
Definition at line 125 of file ControllerConnection.h.
Member Data Documentation
m_controller
Controller* lmms::ControllerConnection::m_controller protected
Definition at line 113 of file ControllerConnection.h.
Referenced by ControllerConnection(), ControllerConnection(), ~ControllerConnection(), currentValue(), getController(), loadSettings(), saveSettings(), setController(), setTargetName(), and valueBuffer().
m_controllerId
int lmms::ControllerConnection::m_controllerId protected
Definition at line 115 of file ControllerConnection.h.
Referenced by ControllerConnection(), ControllerConnection(), finalizeConnections(), isFinalized(), loadSettings(), and setController().
m_ownsController
bool lmms::ControllerConnection::m_ownsController protected
Definition at line 117 of file ControllerConnection.h.
Referenced by ControllerConnection(), ControllerConnection(), ~ControllerConnection(), saveSettings(), and setController().
m_targetName
QString lmms::ControllerConnection::m_targetName protected
Definition at line 114 of file ControllerConnection.h.
Referenced by setTargetName(), and targetName().
s_connections
ControllerConnectionVector lmms::ControllerConnection::s_connections static protected
Definition at line 119 of file ControllerConnection.h.
Referenced by ControllerConnection(), ControllerConnection(), ~ControllerConnection(), and finalizeConnections().
The documentation for this class was generated from the following files:
include/ControllerConnection.h
src/core/ControllerConnection.cpp