LMMS: lmms::gui::MidiSetupWidget Class Reference
lmms::gui::MidiSetupWidget Class Reference
#include <MidiSetupWidget.h>
Public Member Functions
void saveSettings ()
void show ()
Static Public Member Functions
template<typename MidiClientType>
static MidiSetupWidget * create (QWidget *parent)
Private Member Functions
MidiSetupWidget (const QString &caption, const QString &configSection, const QString &devName, QWidget *parent)
Private Attributes
QString m_configSection
QLineEdit * m_device
Detailed Description
Definition at line 36 of file MidiSetupWidget.h.
Constructor & Destructor Documentation
MidiSetupWidget()
lmms::gui::MidiSetupWidget::MidiSetupWidget (const QString & caption, const QString & configSection, const QString & devName, QWidget * parent) private
Definition at line 37 of file MidiSetupWidget.cpp.
References m_configSection, and m_device.
Referenced by create().
Member Function Documentation
create()
template<typename MidiClientType> MidiSetupWidget * lmms::gui::MidiSetupWidget::create (QWidget * parent) inline static
Definition at line 43 of file MidiSetupWidget.h.
References MidiSetupWidget().
Referenced by lmms::gui::SetupDialog::SetupDialog().
saveSettings()
void lmms::gui::MidiSetupWidget::saveSettings ()
Definition at line 55 of file MidiSetupWidget.cpp.
References lmms::ConfigManager::inst(), m_configSection, m_device, and lmms::ConfigManager::setValue().
show()
void lmms::gui::MidiSetupWidget::show ()
Definition at line 64 of file MidiSetupWidget.cpp.
References m_configSection.
Member Data Documentation
m_configSection
QString lmms::gui::MidiSetupWidget::m_configSection private
Definition at line 54 of file MidiSetupWidget.h.
Referenced by MidiSetupWidget(), saveSettings(), and show().
m_device
QLineEdit* lmms::gui::MidiSetupWidget::m_device private
Definition at line 55 of file MidiSetupWidget.h.
Referenced by MidiSetupWidget(), and saveSettings().
The documentation for this class was generated from the following files:
include/MidiSetupWidget.h
src/gui/MidiSetupWidget.cpp