LMMS: lmms::MidiPort Class Reference
lmms::MidiPort Class Reference
#include <MidiPort.h>
Public Types
using Map = QMap<QString, bool>
enum class Mode {
Disabled ,
Input ,
Output ,
Duplex
}
Public Slots
void updateMidiPortMode ()
Signals
void modeChanged ()
void readablePortsChanged ()
void writablePortsChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
MidiPort (const QString &name, MidiClient *client, MidiEventProcessor *eventProcessor, Model *parent=nullptr, Mode mode=Mode::Disabled)
~MidiPort () override
void invalidateCilent ()
bool isInputEnabled () const
bool isOutputEnabled () const
void loadSettings (const QDomElement &thisElement) override
Mode mode () const
QString nodeName () const override
void processInEvent (const MidiEvent &event, const TimePos &time=TimePos())
void processOutEvent (const MidiEvent &event, const TimePos &time=TimePos())
const Map & readablePorts () const
int realOutputChannel () const
void saveSettings (QDomDocument &doc, QDomElement &thisElement) override
void setMode (Mode mode)
void setName (const QString &name)
void subscribeReadablePort (const QString &port, bool subscribe=true)
void subscribeWritablePort (const QString &port, bool subscribe=true)
const Map & writablePorts () const
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual void restoreState (const QDomElement &_this)
virtual QDomElement saveState (QDomDocument &_doc, QDomElement &_parent)
void setHook (SerializingObjectHook *_hook)
Public Attributes
gui::MidiPortMenu * m_readablePortsMenu
gui::MidiPortMenu * m_writablePortsMenu
Private Slots
void updateOutputProgram ()
void updateReadablePorts ()
void updateWritablePorts ()
Private Member Functions
mapPropertyFromModel (bool, isReadable, setReadable, m_readableModel)
mapPropertyFromModel (bool, isWritable, setWritable, m_writableModel)
mapPropertyFromModel (int, baseVelocity, setBaseVelocity, m_baseVelocityModel)
mapPropertyFromModel (int, fixedInputVelocity, setFixedInputVelocity, m_fixedInputVelocityModel)
mapPropertyFromModel (int, fixedOutputNote, setFixedOutputNote, m_fixedOutputNoteModel)
mapPropertyFromModel (int, fixedOutputVelocity, setFixedOutputVelocity, m_fixedOutputVelocityModel)
mapPropertyFromModel (int, inputChannel, setInputChannel, m_inputChannelModel)
mapPropertyFromModel (int, inputController, setInputController, m_inputControllerModel)
mapPropertyFromModel (int, outputChannel, setOutputChannel, m_outputChannelModel)
mapPropertyFromModel (int, outputController, setOutputController, m_outputControllerModel)
mapPropertyFromModel (int, outputProgram, setOutputProgram, m_outputProgramModel)
Private Attributes
IntModel m_baseVelocityModel
IntModel m_fixedInputVelocityModel
IntModel m_fixedOutputNoteModel
IntModel m_fixedOutputVelocityModel
IntModel m_inputChannelModel
IntModel m_inputControllerModel
MidiClient * m_midiClient
MidiEventProcessor * m_midiEventProcessor
Mode m_mode
IntModel m_outputChannelModel
IntModel m_outputControllerModel
IntModel m_outputProgramModel
BoolModel m_readableModel
Map m_readablePorts
BoolModel m_writableModel
Map m_writablePorts
Friends
class gui::ControllerConnectionDialog
class gui::InstrumentMidiIOView
Detailed Description
Definition at line 55 of file MidiPort.h.
Member Typedef Documentation
Map
using lmms::MidiPort::Map = QMap<QString, bool>
Definition at line 70 of file MidiPort.h.
Member Enumeration Documentation
Mode
enum class lmms::MidiPort::Mode strong
Enumerator
Disabled
Input
Output
Duplex
Definition at line 72 of file MidiPort.h.
Constructor & Destructor Documentation
MidiPort()
lmms::MidiPort::MidiPort (const QString & name, MidiClient * client, MidiEventProcessor * eventProcessor, Model * parent = nullptr, Mode mode = Mode::Disabled)
Definition at line 45 of file MidiPort.cpp.
References lmms::Model::Model(), client(), lmms::Model::dataChanged(), Duplex, Input, m_baseVelocityModel, m_fixedInputVelocityModel, m_fixedOutputNoteModel, m_fixedOutputVelocityModel, m_inputChannelModel, m_inputControllerModel, m_midiClient, m_midiEventProcessor, m_mode, m_outputChannelModel, m_outputControllerModel, m_outputProgramModel, m_readableModel, m_readablePortsMenu, m_writableModel, m_writablePortsMenu, lmms::MidiChannelCount, lmms::MidiControllerCount, lmms::MidiMaxKey, lmms::MidiMaxVelocity, lmms::MidiProgramCount, mode(), Output, updateMidiPortMode(), updateOutputProgram(), updateReadablePorts(), and updateWritablePorts().
~MidiPort()
lmms::MidiPort::~MidiPort () override
Definition at line 99 of file MidiPort.cpp.
References m_midiClient, m_readableModel, and m_writableModel.
Member Function Documentation
invalidateCilent()
void lmms::MidiPort::invalidateCilent ()
Definition at line 434 of file MidiPort.cpp.
References m_midiClient, and lmms::s_dummyClient.
isInputEnabled()
bool lmms::MidiPort::isInputEnabled () const inline
Definition at line 96 of file MidiPort.h.
References Duplex, Input, and mode().
Referenced by loadSettings(), processInEvent(), saveSettings(), subscribeReadablePort(), and updateMidiPortMode().
isOutputEnabled()
bool lmms::MidiPort::isOutputEnabled () const inline
Definition at line 101 of file MidiPort.h.
References Duplex, mode(), and Output.
Referenced by loadSettings(), processOutEvent(), saveSettings(), subscribeWritablePort(), and updateMidiPortMode().
loadSettings()
void lmms::MidiPort::loadSettings (const QDomElement & thisElement) override virtual
Implements lmms::SerializingObject.
Definition at line 240 of file MidiPort.cpp.
References isInputEnabled(), isOutputEnabled(), m_baseVelocityModel, m_fixedInputVelocityModel, m_fixedOutputNoteModel, m_fixedOutputVelocityModel, m_inputChannelModel, m_inputControllerModel, m_outputChannelModel, m_outputControllerModel, m_outputProgramModel, m_readableModel, m_readablePorts, m_writableModel, m_writablePorts, lmms::MidiMaxVelocity, readablePortsChanged(), subscribeReadablePort(), subscribeWritablePort(), and writablePortsChanged().
mapPropertyFromModel() [1/11]
lmms::MidiPort::mapPropertyFromModel (bool , isReadable , setReadable , m_readableModel) private
References m_readableModel.
mapPropertyFromModel() [2/11]
lmms::MidiPort::mapPropertyFromModel (bool , isWritable , setWritable , m_writableModel) private
References m_writableModel.
mapPropertyFromModel() [3/11]
lmms::MidiPort::mapPropertyFromModel (int , baseVelocity , setBaseVelocity , m_baseVelocityModel) private
References m_baseVelocityModel.
mapPropertyFromModel() [4/11]
lmms::MidiPort::mapPropertyFromModel (int , fixedInputVelocity , setFixedInputVelocity , m_fixedInputVelocityModel) private
References m_fixedInputVelocityModel.
mapPropertyFromModel() [5/11]
lmms::MidiPort::mapPropertyFromModel (int , fixedOutputNote , setFixedOutputNote , m_fixedOutputNoteModel) private
References m_fixedOutputNoteModel.
mapPropertyFromModel() [6/11]
lmms::MidiPort::mapPropertyFromModel (int , fixedOutputVelocity , setFixedOutputVelocity , m_fixedOutputVelocityModel) private
References m_fixedOutputVelocityModel.
mapPropertyFromModel() [7/11]
lmms::MidiPort::mapPropertyFromModel (int , inputChannel , setInputChannel , m_inputChannelModel) private
References m_inputChannelModel.
mapPropertyFromModel() [8/11]
lmms::MidiPort::mapPropertyFromModel (int , inputController , setInputController , m_inputControllerModel) private
References m_inputControllerModel.
mapPropertyFromModel() [9/11]
lmms::MidiPort::mapPropertyFromModel (int , outputChannel , setOutputChannel , m_outputChannelModel) private
References m_outputChannelModel.
mapPropertyFromModel() [10/11]
lmms::MidiPort::mapPropertyFromModel (int , outputController , setOutputController , m_outputControllerModel) private
References m_outputControllerModel.
mapPropertyFromModel() [11/11]
lmms::MidiPort::mapPropertyFromModel (int , outputProgram , setOutputProgram , m_outputProgramModel) private
References m_outputProgramModel.
mode()
Mode lmms::MidiPort::mode () const inline
Definition at line 89 of file MidiPort.h.
References m_mode.
Referenced by MidiPort(), isInputEnabled(), isOutputEnabled(), and setMode().
modeChanged
void lmms::MidiPort::modeChanged () signal
Referenced by updateMidiPortMode().
nodeName()
QString lmms::MidiPort::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 121 of file MidiPort.h.
processInEvent()
void lmms::MidiPort::processInEvent (const MidiEvent & event, const TimePos & time = TimePos())
Definition at line 130 of file MidiPort.cpp.
References lmms::MidiEvent::channel(), isInputEnabled(), lmms::MidiEvent::key(), m_midiEventProcessor, lmms::MidiKeyPressure, lmms::MidiNoteOff, lmms::MidiNoteOn, lmms::NumKeys, lmms::MidiEvent::setVelocity(), lmms::MidiEvent::type(), and lmms::MidiEvent::velocity().
processOutEvent()
void lmms::MidiPort::processOutEvent (const MidiEvent & event, const TimePos & time = TimePos())
Definition at line 159 of file MidiPort.cpp.
References lmms::MidiEvent::channel(), isOutputEnabled(), m_midiClient, lmms::MidiKeyPressure, lmms::MidiNoteOff, lmms::MidiNoteOn, realOutputChannel(), lmms::MidiEvent::setKey(), lmms::MidiEvent::setVelocity(), lmms::MidiEvent::type(), and lmms::MidiEvent::velocity().
Referenced by updateOutputProgram().
readablePorts()
const Map & lmms::MidiPort::readablePorts () const inline
Definition at line 129 of file MidiPort.h.
References m_readablePorts.
Referenced by lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog().
readablePortsChanged
void lmms::MidiPort::readablePortsChanged () signal
Referenced by loadSettings(), updateMidiPortMode(), and updateReadablePorts().
realOutputChannel()
int lmms::MidiPort::realOutputChannel () const inline
Definition at line 106 of file MidiPort.h.
Referenced by lmms::InstrumentTrack::processCCEvent(), lmms::InstrumentTrack::processOutEvent(), processOutEvent(), and updateOutputProgram().
saveSettings()
void lmms::MidiPort::saveSettings (QDomDocument & doc, QDomElement & thisElement) override virtual
Implements lmms::SerializingObject.
Definition at line 186 of file MidiPort.cpp.
References isInputEnabled(), isOutputEnabled(), m_baseVelocityModel, m_fixedInputVelocityModel, m_fixedOutputNoteModel, m_fixedOutputVelocityModel, m_inputChannelModel, m_inputControllerModel, m_outputChannelModel, m_outputControllerModel, m_outputProgramModel, m_readableModel, m_readablePorts, m_writableModel, and m_writablePorts.
setMode()
void lmms::MidiPort::setMode (Mode mode)
Definition at line 121 of file MidiPort.cpp.
References m_midiClient, m_mode, and mode().
Referenced by updateMidiPortMode().
setName()
void lmms::MidiPort::setName (const QString & name)
Definition at line 112 of file MidiPort.cpp.
References m_midiClient, and lmms::Model::setDisplayName().
subscribeReadablePort()
void lmms::MidiPort::subscribeReadablePort (const QString & port, bool subscribe = true)
Definition at line 295 of file MidiPort.cpp.
References isInputEnabled(), m_midiClient, m_readableModel, and m_readablePorts.
Referenced by loadSettings(), and updateMidiPortMode().
subscribeWritablePort()
void lmms::MidiPort::subscribeWritablePort (const QString & port, bool subscribe = true)
Definition at line 311 of file MidiPort.cpp.
References isOutputEnabled(), m_midiClient, m_writableModel, and m_writablePorts.
Referenced by loadSettings(), and updateMidiPortMode().
updateMidiPortMode
void lmms::MidiPort::updateMidiPortMode () slot
Definition at line 326 of file MidiPort.cpp.
References Disabled, Duplex, lmms::Engine::getSong(), Input, isInputEnabled(), isOutputEnabled(), m_readableModel, m_readablePorts, m_writableModel, m_writablePorts, modeChanged(), Output, readablePortsChanged(), setMode(), lmms::Song::setModified(), subscribeReadablePort(), subscribeWritablePort(), and writablePortsChanged().
Referenced by MidiPort().
updateOutputProgram
void lmms::MidiPort::updateOutputProgram () private slot
Definition at line 426 of file MidiPort.cpp.
References lmms::MidiProgramChange, processOutEvent(), and realOutputChannel().
Referenced by MidiPort().
updateReadablePorts
void lmms::MidiPort::updateReadablePorts () private slot
Definition at line 374 of file MidiPort.cpp.
References m_midiClient, m_readablePorts, and readablePortsChanged().
Referenced by MidiPort().
updateWritablePorts
void lmms::MidiPort::updateWritablePorts () private slot
Definition at line 400 of file MidiPort.cpp.
References m_midiClient, m_writablePorts, and writablePortsChanged().
Referenced by MidiPort().
writablePorts()
const Map & lmms::MidiPort::writablePorts () const inline
Definition at line 134 of file MidiPort.h.
References m_writablePorts.
writablePortsChanged
void lmms::MidiPort::writablePortsChanged () signal
Referenced by loadSettings(), updateMidiPortMode(), and updateWritablePorts().
Friends And Related Symbol Documentation
gui::ControllerConnectionDialog
friend class gui::ControllerConnectionDialog friend
Definition at line 177 of file MidiPort.h.
gui::InstrumentMidiIOView
friend class gui::InstrumentMidiIOView friend
Definition at line 178 of file MidiPort.h.
Member Data Documentation
m_baseVelocityModel
IntModel lmms::MidiPort::m_baseVelocityModel private
Definition at line 169 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_fixedInputVelocityModel
IntModel lmms::MidiPort::m_fixedInputVelocityModel private
Definition at line 165 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_fixedOutputNoteModel
IntModel lmms::MidiPort::m_fixedOutputNoteModel private
Definition at line 167 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_fixedOutputVelocityModel
IntModel lmms::MidiPort::m_fixedOutputVelocityModel private
Definition at line 166 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_inputChannelModel
IntModel lmms::MidiPort::m_inputChannelModel private
Definition at line 161 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_inputControllerModel
IntModel lmms::MidiPort::m_inputControllerModel private
Definition at line 163 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_midiClient
MidiClient* lmms::MidiPort::m_midiClient private
Definition at line 156 of file MidiPort.h.
Referenced by MidiPort(), ~MidiPort(), invalidateCilent(), processOutEvent(), setMode(), setName(), subscribeReadablePort(), subscribeWritablePort(), updateReadablePorts(), and updateWritablePorts().
m_midiEventProcessor
MidiEventProcessor* lmms::MidiPort::m_midiEventProcessor private
Definition at line 157 of file MidiPort.h.
Referenced by MidiPort(), and processInEvent().
m_mode
Mode lmms::MidiPort::m_mode private
Definition at line 159 of file MidiPort.h.
Referenced by MidiPort(), mode(), and setMode().
m_outputChannelModel
IntModel lmms::MidiPort::m_outputChannelModel private
Definition at line 162 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_outputControllerModel
IntModel lmms::MidiPort::m_outputControllerModel private
Definition at line 164 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_outputProgramModel
IntModel lmms::MidiPort::m_outputProgramModel private
Definition at line 168 of file MidiPort.h.
Referenced by MidiPort(), loadSettings(), mapPropertyFromModel(), and saveSettings().
m_readableModel
BoolModel lmms::MidiPort::m_readableModel private
Definition at line 170 of file MidiPort.h.
Referenced by MidiPort(), ~MidiPort(), loadSettings(), mapPropertyFromModel(), saveSettings(), subscribeReadablePort(), and updateMidiPortMode().
m_readablePorts
Map lmms::MidiPort::m_readablePorts private
Definition at line 173 of file MidiPort.h.
Referenced by loadSettings(), readablePorts(), saveSettings(), subscribeReadablePort(), updateMidiPortMode(), and updateReadablePorts().
m_readablePortsMenu
gui::MidiPortMenu* lmms::MidiPort::m_readablePortsMenu
Definition at line 141 of file MidiPort.h.
Referenced by lmms::gui::InstrumentTrackView::InstrumentTrackView(), MidiPort(), and lmms::gui::InstrumentTrackView::~InstrumentTrackView().
m_writableModel
BoolModel lmms::MidiPort::m_writableModel private
Definition at line 171 of file MidiPort.h.
Referenced by MidiPort(), ~MidiPort(), loadSettings(), mapPropertyFromModel(), saveSettings(), subscribeWritablePort(), and updateMidiPortMode().
m_writablePorts
Map lmms::MidiPort::m_writablePorts private
Definition at line 174 of file MidiPort.h.
Referenced by loadSettings(), saveSettings(), subscribeWritablePort(), updateMidiPortMode(), updateWritablePorts(), and writablePorts().
m_writablePortsMenu
gui::MidiPortMenu* lmms::MidiPort::m_writablePortsMenu
Definition at line 142 of file MidiPort.h.
Referenced by lmms::gui::InstrumentTrackView::InstrumentTrackView(), MidiPort(), and lmms::gui::InstrumentTrackView::~InstrumentTrackView().
The documentation for this class was generated from the following files:
include/MidiPort.h
src/core/midi/MidiPort.cpp