LMMS: hiir::HalfBandNeon< NC > Class Template Reference
hiir::HalfBandNeon< NC > Class Template Reference
#include <HalfBandNeon.h>
Public Types
typedef float DataType
Public Member Functions
HalfBandNeon () noexcept
HalfBandNeon (const HalfBandNeon< NC > &other)=default
HalfBandNeon (HalfBandNeon< NC > &&other)=default
~HalfBandNeon ()=default
void clear_buffers () noexcept
HalfBandNeon< NC > & operator= (const HalfBandNeon< NC > &other)=default
HalfBandNeon< NC > & operator= (HalfBandNeon< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void process_block_hpf (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE float process_sample (float input) noexcept
hiir_FORCEINLINE float process_sample_hpf (float input) noexcept
hiir_FORCEINLINE void process_sample_split (float &low, float &hi, float input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 2
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataNeonV4, _nbr_stages+1 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const HalfBandNeon< NC > &other) const =delete
bool operator== (const HalfBandNeon< NC > &other) const =delete
hiir_FORCEINLINE float32x2_t process_2_paths (float input) noexcept
template<typename FL, typename FH>
hiir_FORCEINLINE long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void set_single_coef (int index, double coef) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (float *, float32x4_t, float32x4_t, float32x4_t) noexcept
static hiir_FORCEINLINE void store_high (float *ptr, float32x4_t even, float32x4_t odd, float32x4_t half) noexcept
static hiir_FORCEINLINE void store_low (float *ptr, float32x4_t even, float32x4_t odd, float32x4_t half) noexcept
Private Attributes
FilterBiPhase _filter
int _phase
float _prev
Static Private Attributes
static constexpr int _coef_shift = ((NBR_COEFS & 1) * 2) ^ 3
static constexpr int _nbr_phases = 2
static constexpr int _nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width
static constexpr int _stage_width = 4
Detailed Description
template<int NC>
class hiir::HalfBandNeon< NC >
Definition at line 51 of file HalfBandNeon.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::HalfBandNeon< NC >::DataType
Definition at line 60 of file HalfBandNeon.h.
Filter
template<int NC> typedef std::array<StageDataNeonV4, _nbr_stages + 1> hiir::HalfBandNeon< NC >::Filter private
Definition at line 108 of file HalfBandNeon.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::HalfBandNeon< NC >::FilterBiPhase private
Definition at line 109 of file HalfBandNeon.h.
Constructor & Destructor Documentation
HalfBandNeon() [1/3]
template<int NC> hiir::HalfBandNeon< NC >::HalfBandNeon () noexcept
Definition at line 58 of file HalfBandNeon.hpp.
References _filter, _nbr_phases, _nbr_stages, _phase, _prev, _stage_width, clear_buffers(), i, NBR_COEFS, set_single_coef(), and hiir::storea().
Referenced by HalfBandNeon(), HalfBandNeon(), ~HalfBandNeon(), operator=(), and operator=().
HalfBandNeon() [2/3]
template<int NC> hiir::HalfBandNeon< NC >::HalfBandNeon (const HalfBandNeon< NC > & other) default
References HalfBandNeon().
HalfBandNeon() [3/3]
template<int NC> hiir::HalfBandNeon< NC >::HalfBandNeon (HalfBandNeon< NC > && other) default
References HalfBandNeon().
~HalfBandNeon()
template<int NC> hiir::HalfBandNeon< NC >::~HalfBandNeon () default
References HalfBandNeon().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::HalfBandNeon< NC >::bypass (float * , float32x4_t , float32x4_t , float32x4_t) inline static private noexcept
Definition at line 124 of file HalfBandNeon.h.
References bypass().
Referenced by bypass(), process_block(), and process_block_hpf().
clear_buffers()
template<int NC> void hiir::HalfBandNeon< NC >::clear_buffers () noexcept
Definition at line 343 of file HalfBandNeon.hpp.
References _filter, _nbr_phases, _nbr_stages, i, and hiir::storea().
Referenced by HalfBandNeon(), and operator=().
operator!=()
template<int NC> bool hiir::HalfBandNeon< NC >::operator!= (const HalfBandNeon< NC > & other) const private delete
operator=() [1/2]
template<int NC> HalfBandNeon< NC > & hiir::HalfBandNeon< NC >::operator= (const HalfBandNeon< NC > & other) default
References HalfBandNeon().
operator=() [2/2]
template<int NC> HalfBandNeon< NC > & hiir::HalfBandNeon< NC >::operator= (HalfBandNeon< NC > && other) default
References HalfBandNeon(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_hpf(), process_block_split(), process_sample(), process_sample_hpf(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::HalfBandNeon< NC >::operator== (const HalfBandNeon< NC > & other) const private delete
process_2_paths()
template<int NC> float32x2_t hiir::HalfBandNeon< NC >::process_2_paths (float input) private noexcept
Definition at line 395 of file HalfBandNeon.hpp.
References _filter, _nbr_stages, _phase, _prev, hiir::load2a(), hiir::load4a(), and hiir::StageProcNeonV4< CUR >::process_sample_pos().
Referenced by process_sample(), process_sample_hpf(), and process_sample_split().
process_block()
template<int NC> void hiir::HalfBandNeon< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 148 of file HalfBandNeon.hpp.
References _phase, bypass(), pos, process_block_quad(), process_sample(), and store_low().
Referenced by operator=().
process_block_hpf()
template<int NC> void hiir::HalfBandNeon< NC >::process_block_hpf (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 219 of file HalfBandNeon.hpp.
References _phase, bypass(), pos, process_block_quad(), process_sample_hpf(), and store_high().
Referenced by operator=().
process_block_quad() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE long hiir::HalfBandNeon< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE, process_block_quad(), store_high(), and store_low().
Referenced by process_block(), process_block_hpf(), process_block_quad(), and process_block_split().
process_block_quad() [2/2]
template<int NC> template<typename FL, typename FH> long hiir::HalfBandNeon< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 423 of file HalfBandNeon.hpp.
References _filter, _nbr_stages, _phase, _prev, hiir::load4a(), hiir::load4u(), pos, hiir::StageProcNeonV4< CUR >::process_sample_pos(), and hiir::storea().
process_block_split()
template<int NC> void hiir::HalfBandNeon< NC >::process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 298 of file HalfBandNeon.hpp.
References _phase, pos, process_block_quad(), process_sample_split(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> float hiir::HalfBandNeon< NC >::process_sample (float input) noexcept
Definition at line 120 of file HalfBandNeon.hpp.
References process_2_paths().
Referenced by operator=(), and process_block().
process_sample_hpf()
template<int NC> float hiir::HalfBandNeon< NC >::process_sample_hpf (float input) noexcept
Definition at line 191 of file HalfBandNeon.hpp.
References process_2_paths().
Referenced by operator=(), and process_block_hpf().
process_sample_split()
template<int NC> void hiir::HalfBandNeon< NC >::process_sample_split (float & low, float & hi, float input) noexcept
Definition at line 266 of file HalfBandNeon.hpp.
References process_2_paths().
Referenced by operator=(), and process_block_split().
set_coefs()
template<int NC> void hiir::HalfBandNeon< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 95 of file HalfBandNeon.hpp.
References i, NBR_COEFS, and set_single_coef().
Referenced by operator=().
set_single_coef()
template<int NC> void hiir::HalfBandNeon< NC >::set_single_coef (int index, double coef) inline private noexcept
Definition at line 376 of file HalfBandNeon.hpp.
References _coef_shift, _filter, _nbr_phases, _nbr_stages, _stage_width, and pos.
Referenced by HalfBandNeon(), and set_coefs().
store_high()
template<int NC> void hiir::HalfBandNeon< NC >::store_high (float * ptr, float32x4_t even, float32x4_t odd, float32x4_t half) static private noexcept
Definition at line 486 of file HalfBandNeon.hpp.
References hiir::storeu().
Referenced by process_block_hpf(), process_block_quad(), and process_block_split().
store_low()
template<int NC> void hiir::HalfBandNeon< NC >::store_low (float * ptr, float32x4_t even, float32x4_t odd, float32x4_t half) static private noexcept
Definition at line 477 of file HalfBandNeon.hpp.
References hiir::storeu().
Referenced by process_block(), process_block_quad(), and process_block_split().
Member Data Documentation
_coef_shift
template<int NC> int hiir::HalfBandNeon< NC >::_coef_shift = ((NBR_COEFS & 1) * 2) ^ 3 static constexpr private
Definition at line 106 of file HalfBandNeon.h.
Referenced by set_single_coef().
_delay
template<int NC> double hiir::HalfBandNeon< NC >::_delay = 2 static constexpr
Definition at line 63 of file HalfBandNeon.h.
_filter
template<int NC> FilterBiPhase hiir::HalfBandNeon< NC >::_filter private
Definition at line 126 of file HalfBandNeon.h.
Referenced by HalfBandNeon(), clear_buffers(), process_2_paths(), process_block_quad(), and set_single_coef().
_nbr_chn
template<int NC> int hiir::HalfBandNeon< NC >::_nbr_chn = 1 static constexpr
Definition at line 61 of file HalfBandNeon.h.
_nbr_phases
template<int NC> int hiir::HalfBandNeon< NC >::_nbr_phases = 2 static constexpr private
Definition at line 105 of file HalfBandNeon.h.
Referenced by HalfBandNeon(), clear_buffers(), and set_single_coef().
_nbr_stages
template<int NC> int hiir::HalfBandNeon< NC >::_nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width static constexpr private
Definition at line 104 of file HalfBandNeon.h.
Referenced by HalfBandNeon(), clear_buffers(), process_2_paths(), process_block_quad(), and set_single_coef().
_phase
template<int NC> int hiir::HalfBandNeon< NC >::_phase private
Definition at line 128 of file HalfBandNeon.h.
Referenced by HalfBandNeon(), process_2_paths(), process_block(), process_block_hpf(), process_block_quad(), and process_block_split().
_prev
template<int NC> float hiir::HalfBandNeon< NC >::_prev private
Definition at line 127 of file HalfBandNeon.h.
Referenced by HalfBandNeon(), process_2_paths(), and process_block_quad().
_stage_width
template<int NC> int hiir::HalfBandNeon< NC >::_stage_width = 4 static constexpr private
Definition at line 103 of file HalfBandNeon.h.
Referenced by HalfBandNeon(), and set_single_coef().
NBR_COEFS
template<int NC> int hiir::HalfBandNeon< NC >::NBR_COEFS = NC static constexpr
Definition at line 62 of file HalfBandNeon.h.
Referenced by HalfBandNeon(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/HalfBandNeon.h
src/3rdparty/hiir/hiir/HalfBandNeon.hpp