LMMS: hiir::StageProc8Avx< REMAINING > Class Template Reference
hiir::StageProc8Avx< REMAINING > Class Template Reference
#include <StageProc8Avx.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m256 &spl_0, __m256 &spl_1, StageDataAvx *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m256 &spl_0, __m256 &spl_1, StageDataAvx *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m256 &spl_0, __m256 &spl_1, StageDataAvx *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m256 &spl_0, __m256 &spl_1, StageDataAvx *stage_arr) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m256 &spl_0, __m256 &spl_1, StageDataAvx *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m256 &spl_0, __m256 &spl_1, StageDataAvx *stage_arr) noexcept
Private Member Functions
StageProc8Avx ()=delete
StageProc8Avx (const StageProc8Avx< REMAINING > &other)=delete
StageProc8Avx (StageProc8Avx< REMAINING > &&other)=delete
~StageProc8Avx ()=delete
bool operator!= (const StageProc8Avx< REMAINING > &other)=delete
StageProc8Avx< REMAINING > & operator= (const StageProc8Avx< REMAINING > &other)=delete
StageProc8Avx< REMAINING > & operator= (StageProc8Avx< REMAINING > &&other)=delete
bool operator== (const StageProc8Avx< REMAINING > &other)=delete
Detailed Description
template<int REMAINING>
class hiir::StageProc8Avx< REMAINING >
Definition at line 47 of file StageProc8Avx.h.
Constructor & Destructor Documentation
StageProc8Avx() [1/3]
template<int REMAINING> hiir::StageProc8Avx< REMAINING >::StageProc8Avx () private delete
Referenced by process_sample_neg(), and process_sample_pos().
StageProc8Avx() [2/3]
template<int REMAINING> hiir::StageProc8Avx< REMAINING >::StageProc8Avx (const StageProc8Avx< REMAINING > & other) private delete
StageProc8Avx() [3/3]
template<int REMAINING> hiir::StageProc8Avx< REMAINING >::StageProc8Avx (StageProc8Avx< REMAINING > && other) private delete
~StageProc8Avx()
template<int REMAINING> hiir::StageProc8Avx< REMAINING >::~StageProc8Avx () private delete
Member Function Documentation
operator!=()
template<int REMAINING> bool hiir::StageProc8Avx< REMAINING >::operator!= (const StageProc8Avx< REMAINING > & other) private delete
operator=() [1/2]
template<int REMAINING> StageProc8Avx< REMAINING > & hiir::StageProc8Avx< REMAINING >::operator= (const StageProc8Avx< REMAINING > & other) private delete
operator=() [2/2]
template<int REMAINING> StageProc8Avx< REMAINING > & hiir::StageProc8Avx< REMAINING >::operator= (StageProc8Avx< REMAINING > && other) private delete
operator==()
template<int REMAINING> bool hiir::StageProc8Avx< REMAINING >::operator== (const StageProc8Avx< REMAINING > & other) private delete
process_sample_neg() [1/3]
template<int REMAINING> void hiir::StageProc8Avx< REMAINING >::process_sample_neg (const int nbr_coefs, __m256 & spl_0, __m256 & spl_1, StageDataAvx * stage_arr) static noexcept
Definition at line 147 of file StageProc8Avx.hpp.
References StageProc8Avx(), and process_sample_neg().
Referenced by hiir::PhaseHalfPi8Avx< NC >::process_block(), hiir::PhaseHalfPi8Avx< NC >::process_sample(), and process_sample_neg().
process_sample_neg() [2/3]
hiir_FORCEINLINE void hiir::StageProc8Avx< 0 >::process_sample_neg (const int nbr_coefs, __m256 & spl_0, __m256 & spl_1, StageDataAvx * stage_arr) noexcept
Definition at line 136 of file StageProc8Avx.hpp.
References hiir_FORCEINLINE.
process_sample_neg() [3/3]
hiir_FORCEINLINE void hiir::StageProc8Avx< 1 >::process_sample_neg (const int nbr_coefs, __m256 & spl_0, __m256 & spl_1, StageDataAvx * stage_arr) noexcept
Definition at line 114 of file StageProc8Avx.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [1/3]
template<int REMAINING> void hiir::StageProc8Avx< REMAINING >::process_sample_pos (const int nbr_coefs, __m256 & spl_0, __m256 & spl_1, StageDataAvx * stage_arr) static noexcept
Definition at line 78 of file StageProc8Avx.hpp.
References StageProc8Avx(), and process_sample_pos().
Referenced by hiir::HalfBand8Avx< NC >::process_2_paths(), hiir::HalfBand8Avx< NC >::process_block_2_paths(), hiir::Downsampler2x8Avx< NC >::process_sample(), hiir::Upsampler2x8Avx< NC >::process_sample(), process_sample_pos(), and hiir::Downsampler2x8Avx< NC >::process_sample_split().
process_sample_pos() [2/3]
hiir_FORCEINLINE void hiir::StageProc8Avx< 0 >::process_sample_pos (const int nbr_coefs, __m256 & spl_0, __m256 & spl_1, StageDataAvx * stage_arr) noexcept
Definition at line 67 of file StageProc8Avx.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [3/3]
hiir_FORCEINLINE void hiir::StageProc8Avx< 1 >::process_sample_pos (const int nbr_coefs, __m256 & spl_0, __m256 & spl_1, StageDataAvx * stage_arr) noexcept
Definition at line 45 of file StageProc8Avx.hpp.
References hiir_FORCEINLINE.
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProc8Avx.h
src/3rdparty/hiir/hiir/StageProc8Avx.hpp