LMMS: lmms::ConfigManager Class Reference
lmms::ConfigManager Class Reference
#include <ConfigManager.h>
Signals
void favoritesChanged ()
void valueChanged (QString cls, QString attribute, QString value)
Public Member Functions
void addFavoriteItem (const QString &item)
void addRecentlyOpenedProject (const QString &_file)
const QString & backgroundPicFile () const
void createWorkingDir ()
const QString & dataDir () const
QString defaultThemeDir () const
QString defaultVersion () const
void deleteValue (const QString &cls, const QString &attribute)
QString factoryPresetsDir () const
QString factoryProjectsDir () const
QString factorySamplesDir () const
QString factoryTemplatesDir () const
const QStringList & favoriteItems ()
const QString & gigDir () const
bool hasWorkingDir () const
void initDevelopmentWorkingDir ()
void initInstalledWorkingDir ()
void initPortableWorkingDir ()
bool isFavoriteItem (const QString &item)
const QString & ladspaDir () const
unsigned int legacyConfigVersion ()
void loadConfigFile (const QString &configFile="")
QString localeDir () const
const QStringList & recentlyOpenedProjects () const
const QString recoveryFile () const
void removeFavoriteItem (const QString &item)
void saveConfigFile ()
void setBackgroundPicFile (const QString &backgroundPicFile)
void setGIGDir (const QString &gigDir)
void setLADSPADir (const QString &ladspaDir)
void setSF2Dir (const QString &sf2Dir)
void setSF2File (const QString &sf2File)
void setSTKDir (const QString &stkDir)
void setThemeDir (const QString &themeDir)
void setValue (const QString &cls, const QString &attribute, const QString &value)
void setVSTDir (const QString &vstDir)
void setWorkingDir (const QString &workingDir)
const QString & sf2Dir () const
QString themeDir () const
QString trackIconsDir () const
QString userGigDir () const
QString userLadspaDir () const
QString userPresetsDir () const
QString userProjectsDir () const
QString userSamplesDir () const
QString userSf2Dir () const
QString userTemplateDir () const
QString userVstDir () const
QString value (const QString &cls, const QString &attribute, const QString &defaultVal="") const
const QString & version () const
const QString & vstDir () const
QString vstEmbedMethod () const
const QString & workingDir () const
Static Public Member Functions
static QStringList availableVstEmbedMethods ()
static bool enableBlockedPlugins ()
static ConfigManager * inst ()
Private Types
using settingsMap = QMap<QString, stringPairVector>
using stringPairVector = std::vector<QPair<QString, QString>>
using UpgradeMethod = void(ConfigManager::*)()
Private Member Functions
ConfigManager ()
ConfigManager (const ConfigManager &_c)
~ConfigManager () override
void upgrade ()
void upgrade_1_1_90 ()
void upgrade_1_1_91 ()
void upgrade_1_2_2 ()
Private Attributes
QString m_backgroundPicFile
unsigned int m_configVersion
QString m_dataDir
QStringList m_favoriteItems
QString m_gigDir
QString m_ladspaDir
QString m_lmmsRcFile
QStringList m_recentlyOpenedProjects
settingsMap m_settings
QString m_sf2Dir
QString m_themeDir
QString m_version
QString m_vstDir
QString m_workingDir
Static Private Attributes
static ConfigManager * s_instanceOfMe = nullptr
static const std::vector< UpgradeMethod > UPGRADE_METHODS
Friends
class Engine
Detailed Description
Definition at line 55 of file ConfigManager.h.
Member Typedef Documentation
settingsMap
using lmms::ConfigManager::settingsMap = QMap<QString, stringPairVector> private
Definition at line 310 of file ConfigManager.h.
stringPairVector
using lmms::ConfigManager::stringPairVector = std::vector<QPair<QString, QString>> private
Definition at line 309 of file ConfigManager.h.
UpgradeMethod
using lmms::ConfigManager::UpgradeMethod = void(ConfigManager::*)() private
Definition at line 59 of file ConfigManager.h.
Constructor & Destructor Documentation
ConfigManager() [1/2]
lmms::ConfigManager::ConfigManager () private
Definition at line 63 of file ConfigManager.cpp.
References defaultThemeDir(), defaultVersion(), lmms::GIG_PATH, initDevelopmentWorkingDir(), m_configVersion, m_dataDir, m_gigDir, m_sf2Dir, m_themeDir, m_version, m_vstDir, m_workingDir, lmms::PORTABLE_MODE_FILE, lmms::SF2_PATH, and UPGRADE_METHODS.
Referenced by ConfigManager(), and inst().
ConfigManager() [2/2]
lmms::ConfigManager::ConfigManager (const ConfigManager & _c) private
References ConfigManager(), upgrade(), upgrade_1_1_90(), upgrade_1_1_91(), and upgrade_1_2_2().
~ConfigManager()
lmms::ConfigManager::~ConfigManager () override private
Definition at line 97 of file ConfigManager.cpp.
References saveConfigFile().
Member Function Documentation
addFavoriteItem()
void lmms::ConfigManager::addFavoriteItem (const QString & item)
Definition at line 335 of file ConfigManager.cpp.
References favoritesChanged(), m_favoriteItems, and saveConfigFile().
Referenced by lmms::gui::FileBrowserTreeWidget::contextMenuEvent().
addRecentlyOpenedProject()
void lmms::ConfigManager::addRecentlyOpenedProject (const QString & _file)
Definition at line 318 of file ConfigManager.cpp.
References file, inst(), m_recentlyOpenedProjects, and saveConfigFile().
Referenced by lmms::gui::MainWindow::handleSaveResult(), and lmms::Song::loadProject().
availableVstEmbedMethods()
QStringList lmms::ConfigManager::availableVstEmbedMethods () static
Definition at line 197 of file ConfigManager.cpp.
Referenced by lmms::gui::SetupDialog::SetupDialog(), and vstEmbedMethod().
backgroundPicFile()
const QString & lmms::ConfigManager::backgroundPicFile () const inline
Definition at line 195 of file ConfigManager.h.
References m_backgroundPicFile.
Referenced by lmms::gui::MainWindow::MainWindow(), and setBackgroundPicFile().
createWorkingDir()
void lmms::ConfigManager::createWorkingDir ()
Definition at line 302 of file ConfigManager.cpp.
References m_workingDir, userGigDir(), userLadspaDir(), userPresetsDir(), userProjectsDir(), userSamplesDir(), userSf2Dir(), userTemplateDir(), and userVstDir().
Referenced by lmms::gui::GuiApplication::GuiApplication(), and loadConfigFile().
dataDir()
const QString & lmms::ConfigManager::dataDir () const inline
Definition at line 83 of file ConfigManager.h.
References m_dataDir.
Referenced by factoryPresetsDir(), factoryProjectsDir(), and factorySamplesDir().
defaultThemeDir()
QString lmms::ConfigManager::defaultThemeDir () const inline
Definition at line 185 of file ConfigManager.h.
References lmms::DEFAULT_THEME_PATH, and m_dataDir.
Referenced by ConfigManager(), loadConfigFile(), and upgrade().
defaultVersion()
QString lmms::ConfigManager::defaultVersion () const
Definition at line 186 of file ConfigManager.cpp.
Referenced by ConfigManager().
deleteValue()
void lmms::ConfigManager::deleteValue (const QString & cls, const QString & attribute)
Definition at line 399 of file ConfigManager.cpp.
References deleteValue(), and m_settings.
Referenced by deleteValue(), upgrade_1_1_90(), upgrade_1_1_91(), and upgrade_1_2_2().
enableBlockedPlugins()
bool lmms::ConfigManager::enableBlockedPlugins () static
Definition at line 191 of file ConfigManager.cpp.
factoryPresetsDir()
QString lmms::ConfigManager::factoryPresetsDir () const inline
Definition at line 98 of file ConfigManager.h.
References dataDir(), and lmms::PRESETS_PATH.
Referenced by lmms::gui::MainWindow::MainWindow().
factoryProjectsDir()
QString lmms::ConfigManager::factoryProjectsDir () const inline
Definition at line 88 of file ConfigManager.h.
References dataDir(), and lmms::PROJECTS_PATH.
Referenced by lmms::gui::MainWindow::MainWindow(), lmms::Song::createNewProject(), and factoryTemplatesDir().
factorySamplesDir()
QString lmms::ConfigManager::factorySamplesDir () const inline
Definition at line 103 of file ConfigManager.h.
References dataDir(), and lmms::SAMPLES_PATH.
Referenced by lmms::gui::MainWindow::MainWindow().
factoryTemplatesDir()
QString lmms::ConfigManager::factoryTemplatesDir () const inline
Definition at line 93 of file ConfigManager.h.
References factoryProjectsDir(), and lmms::TEMPLATE_PATH.
favoriteItems()
const QStringList & lmms::ConfigManager::favoriteItems () inline
Definition at line 215 of file ConfigManager.h.
References m_favoriteItems.
Referenced by lmms::gui::FileBrowser::FileBrowser(), and isFavoriteItem().
favoritesChanged
void lmms::ConfigManager::favoritesChanged () signal
Referenced by lmms::gui::FileBrowser::FileBrowser(), addFavoriteItem(), and removeFavoriteItem().
gigDir()
const QString & lmms::ConfigManager::gigDir () const inline
Definition at line 159 of file ConfigManager.h.
References m_gigDir.
Referenced by lmms::PathUtil::baseLocation(), loadConfigFile(), and setGIGDir().
hasWorkingDir()
bool lmms::ConfigManager::hasWorkingDir () const
Definition at line 223 of file ConfigManager.cpp.
References m_workingDir.
Referenced by loadConfigFile().
initDevelopmentWorkingDir()
void lmms::ConfigManager::initDevelopmentWorkingDir ()
Definition at line 716 of file ConfigManager.cpp.
References initDevelopmentWorkingDir(), and m_lmmsRcFile.
Referenced by ConfigManager(), and initDevelopmentWorkingDir().
initInstalledWorkingDir()
void lmms::ConfigManager::initInstalledWorkingDir ()
Definition at line 707 of file ConfigManager.cpp.
References initInstalledWorkingDir(), m_lmmsRcFile, and m_workingDir.
Referenced by initInstalledWorkingDir().
initPortableWorkingDir()
void lmms::ConfigManager::initPortableWorkingDir ()
Definition at line 700 of file ConfigManager.cpp.
References initPortableWorkingDir(), m_lmmsRcFile, and m_workingDir.
Referenced by initPortableWorkingDir().
inst()
ConfigManager * lmms::ConfigManager::inst () inline static
Definition at line 62 of file ConfigManager.h.
References ConfigManager(), and s_instanceOfMe.
Referenced by lmms::AudioEngine::AudioEngine(), lmms::gui::FileBrowser::FileBrowser(), lmms::gui::FileDialog::FileDialog(), lmms::gui::GuiApplication::GuiApplication(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), lmms::LadspaManager::LadspaManager(), lmms::gui::MainWindow::MainWindow(), lmms::gui::Oscilloscope::Oscilloscope(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::PianoRoll::PianoRoll(), lmms::gui::SetupDialog::SetupDialog(), lmms::gui::SetupDialog::accept(), addRecentlyOpenedProject(), lmms::InstrumentTrack::autoAssignMidiDevice(), lmms::gui::MainWindow::autoSave(), lmms::gui::MainWindow::autoSaveTimerReset(), lmms::PathUtil::baseLocation(), lmms::gui::MainWindow::closeEvent(), lmms::gui::MixerChannelView::confirmRemoval(), lmms::gui::TrackOperationsWidget::confirmRemoval(), lmms::gui::FileBrowserTreeWidget::contextMenuEvent(), lmms::gui::TimeLineWidget::contextMenuEvent(), lmms::Song::createNewProject(), lmms::Engine::destroy(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::PianoRollWindow::exportMidiClip(), lmms::gui::MainWindow::exportProject(), lmms::gui::RecentProjectsMenu::fillMenu(), lmms::gui::TemplatesMenu::fillTemplatesMenu(), lmms::gui::MainWindow::finalize(), lmms::gui::TimeLineWidget::getLoopAction(), lmms::gui::MainWindow::handleSaveResult(), lmms::gui::TrackLabelButton::isInCompactMode(), lmms::Song::loadProject(), loadTranslation(), main(), lmms::gui::TrackView::mouseMoveEvent(), lmms::gui::TrackView::mousePressEvent(), lmms::gui::FileBrowserTreeWidget::mouseReleaseEvent(), lmms::DataFile::nameWithExtension(), lmms::gui::MainWindow::onExportProjectMidi(), lmms::gui::MainWindow::onImportProject(), lmms::gui::SampleLoader::openAudioFile(), lmms::gui::MainWindow::openProject(), lmms::gui::SampleLoader::openWaveformFile(), lmms::gui::Fader::paintEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::TimeLineWidget::paintEvent(), lmms::gui::TrackView::resizeEvent(), lmms::gui::MainWindow::saveProjectAs(), lmms::gui::MainWindow::saveProjectAsDefaultTemplate(), lmms::gui::MidiSetupWidget::saveSettings(), lmms::gui::InstrumentTrackWindow::saveSettingsBtnClicked(), lmms::gui::MainWindow::sessionCleanup(), lmms::PluginFactory::setupSearchPaths(), lmms::gui::InstrumentTrackView::toggleInstrumentWindow(), lmms::Track::toggleSolo(), lmms::AudioEngine::tryAudioDevices(), lmms::AudioEngine::tryMidiClients(), lmms::gui::Directory::update(), lmms::gui::MainWindow::updateConfig(), lmms::gui::SongEditor::updatePosition(), lmms::gui::MainWindow::updateViewMenu(), and lmms::DataFile::writeFile().
isFavoriteItem()
bool lmms::ConfigManager::isFavoriteItem (const QString & item)
Definition at line 349 of file ConfigManager.cpp.
References favoriteItems().
ladspaDir()
const QString & lmms::ConfigManager::ladspaDir () const inline
Definition at line 135 of file ConfigManager.h.
References m_ladspaDir.
Referenced by lmms::LadspaManager::LadspaManager(), lmms::PathUtil::baseLocation(), and setLADSPADir().
legacyConfigVersion()
unsigned int lmms::ConfigManager::legacyConfigVersion ()
Definition at line 759 of file ConfigManager.cpp.
References lmms::ProjectVersion::Build, legacyConfigVersion(), m_version, and lmms::ProjectVersion::setCompareType().
Referenced by legacyConfigVersion(), and loadConfigFile().
loadConfigFile()
void lmms::ConfigManager::loadConfigFile (const QString & configFile = "")
Definition at line 416 of file ConfigManager.cpp.
References createWorkingDir(), defaultThemeDir(), lmms::ensureTrailingSlash(), file, lmms::gui::getGUI(), gigDir(), hasWorkingDir(), i, legacyConfigVersion(), loadConfigFile(), m_configVersion, m_dataDir, m_favoriteItems, m_ladspaDir, m_lmmsRcFile, m_recentlyOpenedProjects, m_settings, m_themeDir, m_version, m_vstDir, m_workingDir, setBackgroundPicFile(), setGIGDir(), setLADSPADir(), setSF2Dir(), setSF2File(), setSTKDir(), setVSTDir(), setWorkingDir(), sf2Dir(), themeDir(), lmms::PathUtil::toAbsolute(), upgrade(), userLadspaDir(), and value().
Referenced by loadConfigFile().
localeDir()
QString lmms::ConfigManager::localeDir () const inline
Definition at line 217 of file ConfigManager.h.
References lmms::LOCALE_PATH, and m_dataDir.
recentlyOpenedProjects()
const QStringList & lmms::ConfigManager::recentlyOpenedProjects () const inline
Definition at line 210 of file ConfigManager.h.
References m_recentlyOpenedProjects.
Referenced by lmms::gui::RecentProjectsMenu::fillMenu().
recoveryFile()
const QString lmms::ConfigManager::recoveryFile () const inline
Definition at line 205 of file ConfigManager.h.
References m_workingDir.
removeFavoriteItem()
void lmms::ConfigManager::removeFavoriteItem (const QString & item)
Definition at line 342 of file ConfigManager.cpp.
References favoritesChanged(), m_favoriteItems, and saveConfigFile().
Referenced by lmms::gui::FileBrowserTreeWidget::contextMenuEvent().
saveConfigFile()
void lmms::ConfigManager::saveConfigFile ()
Definition at line 617 of file ConfigManager.cpp.
References lmms::gui::getGUI(), m_backgroundPicFile, m_configVersion, m_favoriteItems, m_gigDir, m_ladspaDir, m_lmmsRcFile, m_recentlyOpenedProjects, m_settings, m_sf2Dir, m_themeDir, m_version, m_vstDir, m_workingDir, saveConfigFile(), setValue(), and lmms::PathUtil::toShortestRelative().
Referenced by ~ConfigManager(), lmms::gui::SetupDialog::accept(), addFavoriteItem(), addRecentlyOpenedProject(), removeFavoriteItem(), and saveConfigFile().
setBackgroundPicFile()
void lmms::ConfigManager::setBackgroundPicFile (const QString & backgroundPicFile)
Definition at line 297 of file ConfigManager.cpp.
References backgroundPicFile(), and m_backgroundPicFile.
Referenced by lmms::gui::SetupDialog::accept(), and loadConfigFile().
setGIGDir()
void lmms::ConfigManager::setGIGDir (const QString & gigDir)
Definition at line 281 of file ConfigManager.cpp.
References gigDir(), and m_gigDir.
Referenced by lmms::gui::SetupDialog::accept(), and loadConfigFile().
setLADSPADir()
void lmms::ConfigManager::setLADSPADir (const QString & ladspaDir)
Definition at line 245 of file ConfigManager.cpp.
References ladspaDir(), and m_ladspaDir.
Referenced by lmms::gui::SetupDialog::accept(), and loadConfigFile().
setSF2Dir()
void lmms::ConfigManager::setSF2Dir (const QString & sf2Dir)
Definition at line 263 of file ConfigManager.cpp.
References m_sf2Dir, and sf2Dir().
Referenced by lmms::gui::SetupDialog::accept(), and loadConfigFile().
setSF2File()
void lmms::ConfigManager::setSF2File (const QString & sf2File)
Definition at line 271 of file ConfigManager.cpp.
Referenced by lmms::gui::SetupDialog::accept(), and loadConfigFile().
setSTKDir()
void lmms::ConfigManager::setSTKDir (const QString & stkDir)
Definition at line 253 of file ConfigManager.cpp.
References lmms::ensureTrailingSlash().
Referenced by loadConfigFile().
setThemeDir()
void lmms::ConfigManager::setThemeDir (const QString & themeDir)
Definition at line 289 of file ConfigManager.cpp.
References lmms::ensureTrailingSlash(), m_themeDir, and themeDir().
Referenced by lmms::gui::SetupDialog::accept().
setValue()
void lmms::ConfigManager::setValue (const QString & cls, const QString & attribute, const QString & value)
Definition at line 375 of file ConfigManager.cpp.
References m_settings, setValue(), value(), and valueChanged().
Referenced by lmms::AudioEngine::AudioEngine(), lmms::gui::SetupDialog::SetupDialog(), lmms::gui::SetupDialog::accept(), lmms::gui::MixerChannelView::confirmRemoval(), lmms::gui::TrackOperationsWidget::confirmRemoval(), lmms::gui::TimeLineWidget::contextMenuEvent(), lmms::gui::MainWindow::finalize(), saveConfigFile(), lmms::gui::MidiSetupWidget::saveSettings(), setValue(), lmms::gui::MainWindow::updateConfig(), upgrade_1_1_90(), upgrade_1_1_91(), and upgrade_1_2_2().
setVSTDir()
void lmms::ConfigManager::setVSTDir (const QString & vstDir)
Definition at line 237 of file ConfigManager.cpp.
References lmms::ensureTrailingSlash(), m_vstDir, and vstDir().
Referenced by lmms::gui::SetupDialog::accept(), and loadConfigFile().
setWorkingDir()
void lmms::ConfigManager::setWorkingDir (const QString & workingDir)
Definition at line 229 of file ConfigManager.cpp.
References lmms::ensureTrailingSlash(), m_workingDir, and workingDir().
Referenced by lmms::gui::SetupDialog::accept(), and loadConfigFile().
sf2Dir()
const QString & lmms::ConfigManager::sf2Dir () const inline
Definition at line 140 of file ConfigManager.h.
References m_sf2Dir.
Referenced by lmms::PathUtil::baseLocation(), loadConfigFile(), and setSF2Dir().
themeDir()
QString lmms::ConfigManager::themeDir () const inline
Definition at line 190 of file ConfigManager.h.
References m_themeDir.
Referenced by loadConfigFile(), and setThemeDir().
trackIconsDir()
QString lmms::ConfigManager::trackIconsDir () const inline
Definition at line 200 of file ConfigManager.h.
References m_dataDir, and lmms::TRACK_ICON_PATH.
upgrade()
void lmms::ConfigManager::upgrade () private
Definition at line 156 of file ConfigManager.cpp.
References defaultThemeDir(), m_configVersion, m_themeDir, m_version, max, lmms::ProjectVersion::Minor, lmms::ProjectVersion::setCompareType(), and UPGRADE_METHODS.
Referenced by ConfigManager(), and loadConfigFile().
upgrade_1_1_90()
void lmms::ConfigManager::upgrade_1_1_90 () private
Definition at line 103 of file ConfigManager.cpp.
References deleteValue(), setValue(), and value().
Referenced by ConfigManager().
upgrade_1_1_91()
void lmms::ConfigManager::upgrade_1_1_91 () private
Definition at line 126 of file ConfigManager.cpp.
References deleteValue(), setValue(), and value().
Referenced by ConfigManager().
upgrade_1_2_2()
void lmms::ConfigManager::upgrade_1_2_2 () private
Definition at line 136 of file ConfigManager.cpp.
References deleteValue(), m_settings, setValue(), and value().
Referenced by ConfigManager().
userGigDir()
QString lmms::ConfigManager::userGigDir () const inline
Definition at line 180 of file ConfigManager.h.
References lmms::GIG_PATH, and workingDir().
Referenced by lmms::PathUtil::baseLocation(), and createWorkingDir().
userLadspaDir()
QString lmms::ConfigManager::userLadspaDir () const inline
Definition at line 170 of file ConfigManager.h.
References lmms::LADSPA_PATH, and workingDir().
Referenced by lmms::PathUtil::baseLocation(), createWorkingDir(), and loadConfigFile().
userPresetsDir()
QString lmms::ConfigManager::userPresetsDir () const inline
Definition at line 119 of file ConfigManager.h.
References lmms::PRESETS_PATH, and workingDir().
Referenced by lmms::gui::MainWindow::MainWindow(), lmms::PathUtil::baseLocation(), createWorkingDir(), and lmms::gui::InstrumentTrackWindow::saveSettingsBtnClicked().
userProjectsDir()
QString lmms::ConfigManager::userProjectsDir () const inline
Definition at line 109 of file ConfigManager.h.
References lmms::PROJECTS_PATH, and workingDir().
Referenced by lmms::gui::MainWindow::MainWindow(), lmms::PathUtil::baseLocation(), and createWorkingDir().
userSamplesDir()
QString lmms::ConfigManager::userSamplesDir () const inline
Definition at line 124 of file ConfigManager.h.
References lmms::SAMPLES_PATH, and workingDir().
Referenced by lmms::gui::MainWindow::MainWindow(), lmms::PathUtil::baseLocation(), createWorkingDir(), and lmms::gui::SampleLoader::openAudioFile().
userSf2Dir()
QString lmms::ConfigManager::userSf2Dir () const inline
Definition at line 175 of file ConfigManager.h.
References lmms::SF2_PATH, and workingDir().
Referenced by lmms::PathUtil::baseLocation(), and createWorkingDir().
userTemplateDir()
QString lmms::ConfigManager::userTemplateDir () const inline
Definition at line 114 of file ConfigManager.h.
References lmms::TEMPLATE_PATH, and workingDir().
Referenced by lmms::Song::createNewProject(), createWorkingDir(), and lmms::gui::MainWindow::saveProjectAsDefaultTemplate().
userVstDir()
QString lmms::ConfigManager::userVstDir () const inline
Definition at line 165 of file ConfigManager.h.
References m_vstDir.
Referenced by lmms::PathUtil::baseLocation(), and createWorkingDir().
value()
QString lmms::ConfigManager::value (const QString & cls, const QString & attribute, const QString & defaultVal = "") const
Definition at line 357 of file ConfigManager.cpp.
References m_settings, and value().
Referenced by lmms::gui::MainWindow::MainWindow(), lmms::gui::SetupDialog::SetupDialog(), lmms::InstrumentTrack::autoAssignMidiDevice(), lmms::gui::MixerChannelView::confirmRemoval(), lmms::gui::TrackOperationsWidget::confirmRemoval(), lmms::gui::TimeLineWidget::contextMenuEvent(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::PianoRollWindow::exportMidiClip(), lmms::gui::TimeLineWidget::getLoopAction(), lmms::gui::TrackLabelButton::isInCompactMode(), loadConfigFile(), lmms::gui::TrackView::mouseMoveEvent(), lmms::gui::TrackView::mousePressEvent(), lmms::gui::FileBrowserTreeWidget::mouseReleaseEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::TimeLineWidget::paintEvent(), lmms::gui::MainWindow::saveProjectAs(), setValue(), lmms::Track::toggleSolo(), lmms::AudioEngine::tryAudioDevices(), lmms::AudioEngine::tryMidiClients(), lmms::gui::SongEditor::updatePosition(), upgrade_1_1_90(), upgrade_1_1_91(), upgrade_1_2_2(), value(), valueChanged(), and vstEmbedMethod().
valueChanged
void lmms::ConfigManager::valueChanged (QString cls, QString attribute, QString value) signal
References value().
Referenced by lmms::gui::PianoRoll::PianoRoll(), and setValue().
version()
const QString & lmms::ConfigManager::version () const inline
Definition at line 222 of file ConfigManager.h.
References m_version.
vstDir()
const QString & lmms::ConfigManager::vstDir () const inline
Definition at line 130 of file ConfigManager.h.
References m_vstDir.
Referenced by setVSTDir().
vstEmbedMethod()
QString lmms::ConfigManager::vstEmbedMethod () const
Definition at line 215 of file ConfigManager.cpp.
References availableVstEmbedMethods(), and value().
workingDir()
const QString & lmms::ConfigManager::workingDir () const inline
Definition at line 72 of file ConfigManager.h.
References m_workingDir.
Referenced by setWorkingDir(), userGigDir(), userLadspaDir(), userPresetsDir(), userProjectsDir(), userSamplesDir(), userSf2Dir(), and userTemplateDir().
Friends And Related Symbol Documentation
Engine
friend class Engine friend
Definition at line 314 of file ConfigManager.h.
References Engine.
Referenced by Engine.
Member Data Documentation
m_backgroundPicFile
QString lmms::ConfigManager::m_backgroundPicFile private
Definition at line 302 of file ConfigManager.h.
Referenced by backgroundPicFile(), saveConfigFile(), and setBackgroundPicFile().
m_configVersion
unsigned int lmms::ConfigManager::m_configVersion private
Definition at line 305 of file ConfigManager.h.
Referenced by ConfigManager(), loadConfigFile(), saveConfigFile(), and upgrade().
m_dataDir
QString lmms::ConfigManager::m_dataDir private
Definition at line 290 of file ConfigManager.h.
Referenced by ConfigManager(), dataDir(), defaultThemeDir(), loadConfigFile(), localeDir(), and trackIconsDir().
m_favoriteItems
QStringList lmms::ConfigManager::m_favoriteItems private
Definition at line 307 of file ConfigManager.h.
Referenced by addFavoriteItem(), favoriteItems(), loadConfigFile(), removeFavoriteItem(), and saveConfigFile().
m_gigDir
QString lmms::ConfigManager::m_gigDir private
Definition at line 300 of file ConfigManager.h.
Referenced by ConfigManager(), gigDir(), saveConfigFile(), and setGIGDir().
m_ladspaDir
QString lmms::ConfigManager::m_ladspaDir private
Definition at line 292 of file ConfigManager.h.
Referenced by ladspaDir(), loadConfigFile(), saveConfigFile(), and setLADSPADir().
m_lmmsRcFile
QString lmms::ConfigManager::m_lmmsRcFile private
Definition at line 303 of file ConfigManager.h.
Referenced by initDevelopmentWorkingDir(), initInstalledWorkingDir(), initPortableWorkingDir(), loadConfigFile(), and saveConfigFile().
m_recentlyOpenedProjects
QStringList lmms::ConfigManager::m_recentlyOpenedProjects private
Definition at line 306 of file ConfigManager.h.
Referenced by addRecentlyOpenedProject(), loadConfigFile(), recentlyOpenedProjects(), and saveConfigFile().
m_settings
settingsMap lmms::ConfigManager::m_settings private
Definition at line 311 of file ConfigManager.h.
Referenced by deleteValue(), loadConfigFile(), saveConfigFile(), setValue(), upgrade_1_2_2(), and value().
m_sf2Dir
QString lmms::ConfigManager::m_sf2Dir private
Definition at line 293 of file ConfigManager.h.
Referenced by ConfigManager(), saveConfigFile(), setSF2Dir(), and sf2Dir().
m_themeDir
QString lmms::ConfigManager::m_themeDir private
Definition at line 301 of file ConfigManager.h.
Referenced by ConfigManager(), loadConfigFile(), saveConfigFile(), setThemeDir(), themeDir(), and upgrade().
m_version
QString lmms::ConfigManager::m_version private
Definition at line 304 of file ConfigManager.h.
Referenced by ConfigManager(), legacyConfigVersion(), loadConfigFile(), saveConfigFile(), upgrade(), and version().
m_vstDir
QString lmms::ConfigManager::m_vstDir private
Definition at line 291 of file ConfigManager.h.
Referenced by ConfigManager(), loadConfigFile(), saveConfigFile(), setVSTDir(), userVstDir(), and vstDir().
m_workingDir
QString lmms::ConfigManager::m_workingDir private
Definition at line 289 of file ConfigManager.h.
Referenced by ConfigManager(), createWorkingDir(), hasWorkingDir(), initInstalledWorkingDir(), initPortableWorkingDir(), loadConfigFile(), recoveryFile(), saveConfigFile(), setWorkingDir(), and workingDir().
s_instanceOfMe
ConfigManager * lmms::ConfigManager::s_instanceOfMe = nullptr static private
Definition at line 275 of file ConfigManager.h.
Referenced by inst().
UPGRADE_METHODS
const std::vector< ConfigManager::UpgradeMethod > lmms::ConfigManager::UPGRADE_METHODS static private
Initial value:
= {
    &ConfigManager::upgrade_1_1_90    ,    &ConfigManager::upgrade_1_1_91,
    &ConfigManager::upgrade_1_2_2
}
Definition at line 287 of file ConfigManager.h.
Referenced by ConfigManager(), and upgrade().
The documentation for this class was generated from the following files:
include/ConfigManager.h
src/core/ConfigManager.cpp