LMMS: lmms::DataFile Class Reference
lmms::DataFile Class Reference
#include <DataFile.h>
Public Types
enum class Type {
Unknown ,
SongProject ,
SongProjectTemplate ,
InstrumentTrackSettings ,
DragNDropData ,
ClipboardData ,
JournalData ,
EffectSettings ,
MidiClip
}
Public Member Functions
DataFile (const QByteArray &data)
DataFile (const QString &fileName)
DataFile (Type type)
virtual ~DataFile ()=default
QDomElement & content ()
bool copyResources (const QString &resourcesDir)
Copies resources to the resourcesDir and changes the DataFile to use local paths to them.
bool hasLocalPlugins (QDomElement parent=QDomElement(), bool firstCall=true) const
This recursive method will go through all XML nodes of the DataFile and check whether any of them have local paths.
QDomElement & head ()
unsigned int legacyFileVersion ()
QString nameWithExtension (const QString &fn) const
Type type () const
bool validate (QString extension)
validate performs basic validation, compared to file extension.
void write (QTextStream &strm)
bool writeFile (const QString &fn, bool withResources=false)
Private Types
using ResourcesMap = std::map<QString, std::vector<QString>>
using UpgradeMethod = void(DataFile::*)()
Private Member Functions
void cleanMetaNodes (QDomElement de)
void findProblematicLadspaPlugins ()
void loadData (const QByteArray &_data, const QString &_sourceFile)
void mapSrcAttributeInElementsWithResources (const QMap< QString, QString > &map)
void upgrade ()
void upgrade_0_2_1_20070501 ()
void upgrade_0_2_1_20070508 ()
void upgrade_0_3_0 ()
void upgrade_0_3_0_rc2 ()
void upgrade_0_4_0_20080104 ()
void upgrade_0_4_0_20080118 ()
void upgrade_0_4_0_20080129 ()
void upgrade_0_4_0_20080409 ()
void upgrade_0_4_0_20080607 ()
void upgrade_0_4_0_20080622 ()
void upgrade_0_4_0_beta1 ()
void upgrade_0_4_0_rc2 ()
void upgrade_1_0_99 ()
void upgrade_1_1_0 ()
void upgrade_1_1_91 ()
void upgrade_1_2_0_rc3 ()
void upgrade_1_3_0 ()
void upgrade_automationNodes ()
void upgrade_bbTcoRename ()
void upgrade_defaultTripleOscillatorHQ ()
TripleOscillator switched to using high-quality, alias-free oscillators by default.
void upgrade_extendedNoteRange ()
Note range has been extended to match MIDI specification.
void upgrade_fixBassLoopsTypo ()
void upgrade_fixCMTDelays ()
void upgrade_loopsRename ()
void upgrade_midiCCIndexing ()
Update MIDI CC indexes, so that they are counted from 0.
void upgrade_mixerRename ()
void upgrade_noHiddenAutomationTracks ()
void upgrade_noHiddenClipNames ()
void upgrade_noteTypes ()
void upgrade_sampleAndHold ()
Static Private Member Functions
static Type type (const QString &typeName)
static QString typeName (Type type)
Private Attributes
QDomElement m_content
QString m_fileName
The origin file name or "" if this DataFile didn't originate from a file.
unsigned int m_fileVersion
QDomElement m_head
Type m_type
Static Private Attributes
static const ResourcesMap ELEMENTS_WITH_RESOURCES
static const std::vector< UpgradeMethod > UPGRADE_METHODS
static const std::vector< ProjectVersion > UPGRADE_VERSIONS
Detailed Description
Definition at line 43 of file DataFile.h.
Member Typedef Documentation
ResourcesMap
using lmms::DataFile::ResourcesMap = std::map<QString, std::vector<QString>> private
Definition at line 145 of file DataFile.h.
UpgradeMethod
using lmms::DataFile::UpgradeMethod = void(DataFile::*)() private
Definition at line 46 of file DataFile.h.
Member Enumeration Documentation
Type
enum class lmms::DataFile::Type strong
Enumerator
Unknown
SongProject
SongProjectTemplate
InstrumentTrackSettings
DragNDropData
ClipboardData
JournalData
EffectSettings
MidiClip
Definition at line 49 of file DataFile.h.
Constructor & Destructor Documentation
DataFile() [1/3]
lmms::DataFile::DataFile (const QString & fileName)
Definition at line 153 of file DataFile.cpp.
References lmms::gui::getGUI(), loadData(), m_content, m_fileName, m_fileVersion, m_head, and UPGRADE_METHODS.
DataFile() [2/3]
lmms::DataFile::DataFile (const QByteArray & data)
Definition at line 183 of file DataFile.cpp.
References loadData(), m_content, m_fileName, m_fileVersion, m_head, and UPGRADE_METHODS.
DataFile() [3/3]
lmms::DataFile::DataFile (Type type)
Definition at line 126 of file DataFile.cpp.
References m_content, m_fileName, m_fileVersion, m_head, m_type, type(), typeName(), and UPGRADE_METHODS.
~DataFile()
virtual lmms::DataFile::~DataFile () virtual default
References copyResources(), hasLocalPlugins(), nameWithExtension(), validate(), write(), and writeFile().
Member Function Documentation
cleanMetaNodes()
void lmms::DataFile::cleanMetaNodes (QDomElement de) private
Definition at line 627 of file DataFile.cpp.
References cleanMetaNodes().
Referenced by cleanMetaNodes(), and write().
content()
QDomElement & lmms::DataFile::content () inline
Definition at line 81 of file DataFile.h.
References m_content.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::ProjectJournal::addJournalCheckPoint(), lmms::gui::TrackContentWidget::canPasteSelection(), lmms::gui::PianoRoll::copyToClipboard(), lmms::gui::ClipView::createClipDataFiles(), lmms::gui::ClipView::dropEvent(), lmms::gui::EnvelopeAndLfoView::dropEvent(), lmms::gui::PatternEditor::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), lmms::gui::TrackView::dropEvent(), lmms::gui::PianoRollWindow::exportMidiClip(), lmms::gui::PianoRollWindow::importMidiClip(), lmms::Song::loadProject(), lmms::gui::TrackOperationsWidget::mousePressEvent(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::ProjectJournal::redo(), lmms::InstrumentTrack::replaceInstrument(), lmms::Song::saveProjectFile(), lmms::gui::InstrumentTrackWindow::saveSettingsBtnClicked(), and lmms::ProjectJournal::undo().
copyResources()
bool lmms::DataFile::copyResources (const QString & resourcesDir)
Copies resources to the resourcesDir and changes the DataFile to use local paths to them.
Definition at line 443 of file DataFile.cpp.
References lmms::PathUtil::basePrefix(), ELEMENTS_WITH_RESOURCES, i, lmms::PathUtil::LocalDir, m_fileName, and lmms::PathUtil::toAbsolute().
Referenced by ~DataFile(), and writeFile().
findProblematicLadspaPlugins()
void lmms::DataFile::findProblematicLadspaPlugins () private
Definition at line 2033 of file DataFile.cpp.
References i, and j.
hasLocalPlugins()
bool lmms::DataFile::hasLocalPlugins (QDomElement parent = QDomElement(), bool firstCall = true) const
This recursive method will go through all XML nodes of the DataFile and check whether any of them have local paths.
If they are not on our list of elements that can have local paths we return true, indicating that we potentially have plugins with local paths that would be a security issue. The Song class can then abort loading this project.
Parameters
parent The parent node being iterated. When called without arguments, this will be an empty element that will be ignored (since the second parameter will be true).
firstCall Defaults to true, and indicates to this recursive method whether this is the first call. If it is it will use the root element as the parent.
Definition at line 541 of file DataFile.cpp.
References lmms::PathUtil::basePrefix(), ELEMENTS_WITH_RESOURCES, hasLocalPlugins(), i, and lmms::PathUtil::LocalDir.
Referenced by ~DataFile(), hasLocalPlugins(), and lmms::Song::loadProject().
head()
QDomElement & lmms::DataFile::head () inline
Definition at line 86 of file DataFile.h.
References m_head.
Referenced by lmms::gui::PianoRollWindow::importMidiClip(), lmms::Song::loadProject(), and lmms::Song::saveProjectFile().
legacyFileVersion()
unsigned int lmms::DataFile::legacyFileVersion ()
Definition at line 2220 of file DataFile.cpp.
References UPGRADE_VERSIONS.
Referenced by loadData().
loadData()
void lmms::DataFile::loadData (const QByteArray & _data, const QString & _sourceFile) private
Definition at line 2123 of file DataFile.cpp.
References lmms::gui::TextFloat::displayMessage(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::ProjectVersion::getVersion(), legacyFileVersion(), m_content, m_fileVersion, m_head, m_type, lmms::ProjectVersion::Minor, lmms::ProjectVersion::setCompareType(), type(), typeName(), upgrade(), and UPGRADE_METHODS.
Referenced by DataFile(), and DataFile().
mapSrcAttributeInElementsWithResources()
void lmms::DataFile::mapSrcAttributeInElementsWithResources (const QMap< QString, QString > & map) private
Definition at line 650 of file DataFile.cpp.
References ELEMENTS_WITH_RESOURCES, and i.
Referenced by upgrade_fixBassLoopsTypo(), and upgrade_loopsRename().
nameWithExtension()
QString lmms::DataFile::nameWithExtension (const QString & fn) const
Definition at line 259 of file DataFile.cpp.
References lmms::ConfigManager::inst(), InstrumentTrackSettings, SongProject, SongProjectTemplate, and type().
Referenced by ~DataFile(), lmms::Song::guiSaveProjectAs(), and writeFile().
type() [1/2]
Type lmms::DataFile::type () const inline
Definition at line 91 of file DataFile.h.
References m_type.
Referenced by DataFile(), loadData(), nameWithExtension(), type(), typeName(), upgrade(), and write().
type() [2/2]
DataFile::Type lmms::DataFile::type (const QString & typeName) static private
Definition at line 596 of file DataFile.cpp.
References InstrumentTrackSettings, MidiClip, type(), typeName(), and Unknown.
typeName()
QString lmms::DataFile::typeName (Type type) static private
Definition at line 619 of file DataFile.cpp.
References type().
Referenced by DataFile(), loadData(), type(), and upgrade().
upgrade()
void lmms::DataFile::upgrade () private
Definition at line 2084 of file DataFile.cpp.
References m_fileVersion, m_head, max, SongProject, SongProjectTemplate, type(), typeName(), and UPGRADE_METHODS.
Referenced by loadData().
upgrade_0_2_1_20070501()
void lmms::DataFile::upgrade_0_2_1_20070501 () private
Definition at line 677 of file DataFile.cpp.
References i, m_head, and lmms::LocaleHelper::toFloat().
upgrade_0_2_1_20070508()
void lmms::DataFile::upgrade_0_2_1_20070508 () private
Definition at line 795 of file DataFile.cpp.
References i, j, and lmms::LocaleHelper::toFloat().
upgrade_0_3_0()
void lmms::DataFile::upgrade_0_3_0 () private
Definition at line 873 of file DataFile.cpp.
upgrade_0_3_0_rc2()
void lmms::DataFile::upgrade_0_3_0_rc2 () private
Definition at line 857 of file DataFile.cpp.
References i.
upgrade_0_4_0_20080104()
void lmms::DataFile::upgrade_0_4_0_20080104 () private
Definition at line 900 of file DataFile.cpp.
References i.
upgrade_0_4_0_20080118()
void lmms::DataFile::upgrade_0_4_0_20080118 () private
Definition at line 916 of file DataFile.cpp.
upgrade_0_4_0_20080129()
void lmms::DataFile::upgrade_0_4_0_20080129 () private
Definition at line 938 of file DataFile.cpp.
upgrade_0_4_0_20080409()
void lmms::DataFile::upgrade_0_4_0_20080409 () private
Definition at line 954 of file DataFile.cpp.
References i.
upgrade_0_4_0_20080607()
void lmms::DataFile::upgrade_0_4_0_20080607 () private
Definition at line 983 of file DataFile.cpp.
upgrade_0_4_0_20080622()
void lmms::DataFile::upgrade_0_4_0_20080622 () private
Definition at line 995 of file DataFile.cpp.
References i.
upgrade_0_4_0_beta1()
void lmms::DataFile::upgrade_0_4_0_beta1 () private
Definition at line 1017 of file DataFile.cpp.
References lmms::base64::decode(), i, and k.
upgrade_0_4_0_rc2()
void lmms::DataFile::upgrade_0_4_0_rc2 () private
Definition at line 1056 of file DataFile.cpp.
References i.
upgrade_1_0_99()
void lmms::DataFile::upgrade_1_0_99 () private
Definition at line 1082 of file DataFile.cpp.
References lmms::findIds(), and i.
upgrade_1_1_0()
void lmms::DataFile::upgrade_1_1_0 () private
Definition at line 1123 of file DataFile.cpp.
References i.
upgrade_1_1_91()
void lmms::DataFile::upgrade_1_1_91 () private
Definition at line 1137 of file DataFile.cpp.
References i, and j.
upgrade_1_2_0_rc3()
void lmms::DataFile::upgrade_1_2_0_rc3 () private
Definition at line 1218 of file DataFile.cpp.
References i, j, and lmms::upgradeElement_1_2_0_rc2_42().
upgrade_1_3_0()
void lmms::DataFile::upgrade_1_3_0 () private
Definition at line 1311 of file DataFile.cpp.
References i, lmms::iterate_ladspa_ports(), j, and k.
upgrade_automationNodes()
void lmms::DataFile::upgrade_automationNodes () private
Definition at line 1721 of file DataFile.cpp.
References i, j, and lmms::LocaleHelper::toFloat().
upgrade_bbTcoRename()
void lmms::DataFile::upgrade_bbTcoRename () private
Definition at line 1901 of file DataFile.cpp.
References i, and lmms::Track::Pattern.
upgrade_defaultTripleOscillatorHQ()
void lmms::DataFile::upgrade_defaultTripleOscillatorHQ () private
TripleOscillator switched to using high-quality, alias-free oscillators by default.
Older projects were made without this feature and would sound differently if loaded with the new default setting. This upgrade routine preserves their old behavior.
Definition at line 1823 of file DataFile.cpp.
References i, and j.
upgrade_extendedNoteRange()
void lmms::DataFile::upgrade_extendedNoteRange () private
Note range has been extended to match MIDI specification.
The non-standard note range previously affected all MIDI-based instruments except OpulenZ, and made them sound an octave lower than they should (#1857).
Definition at line 1809 of file DataFile.cpp.
References lmms::UpgradeExtendedNoteRange::upgrade().
upgrade_fixBassLoopsTypo()
void lmms::DataFile::upgrade_fixBassLoopsTypo () private
Definition at line 2066 of file DataFile.cpp.
References mapSrcAttributeInElementsWithResources().
upgrade_fixCMTDelays()
void lmms::DataFile::upgrade_fixCMTDelays () private
Definition at line 1765 of file DataFile.cpp.
References i, and j.
upgrade_loopsRename()
void lmms::DataFile::upgrade_loopsRename () private
Definition at line 2004 of file DataFile.cpp.
References lmms::buildReplacementMap(), and mapSrcAttributeInElementsWithResources().
upgrade_midiCCIndexing()
void lmms::DataFile::upgrade_midiCCIndexing () private
Update MIDI CC indexes, so that they are counted from 0.
Older releases of LMMS count the CCs from 1.
Definition at line 2013 of file DataFile.cpp.
References i.
upgrade_mixerRename()
void lmms::DataFile::upgrade_mixerRename () private
Definition at line 1841 of file DataFile.cpp.
References i.
upgrade_noHiddenAutomationTracks()
void lmms::DataFile::upgrade_noHiddenAutomationTracks () private
Definition at line 1647 of file DataFile.cpp.
References lmms::Track::Automation, lmms::Track::HiddenAutomation, and i.
upgrade_noHiddenClipNames()
void lmms::DataFile::upgrade_noHiddenClipNames () private
Definition at line 1692 of file DataFile.cpp.
References i, and j.
upgrade_noteTypes()
void lmms::DataFile::upgrade_noteTypes () private
Definition at line 1748 of file DataFile.cpp.
References lmms::DefaultTicksPerBar, i, and lmms::Note::Step.
upgrade_sampleAndHold()
void lmms::DataFile::upgrade_sampleAndHold () private
Definition at line 1935 of file DataFile.cpp.
References i.
validate()
bool lmms::DataFile::validate (QString extension)
validate performs basic validation, compared to file extension.
Definition at line 197 of file DataFile.cpp.
References lmms::getPluginFactory(), InstrumentTrackSettings, m_type, MidiClip, SongProject, SongProjectTemplate, and Unknown.
Referenced by ~DataFile(), and lmms::gui::FileBrowserTreeWidget::previewFileItem().
write()
void lmms::DataFile::write (QTextStream & strm)
Definition at line 298 of file DataFile.cpp.
References cleanMetaNodes(), InstrumentTrackSettings, SongProject, SongProjectTemplate, and type().
Referenced by ~DataFile(), main(), and writeFile().
writeFile()
bool lmms::DataFile::writeFile (const QString & fn, bool withResources = false)
Definition at line 312 of file DataFile.cpp.
References copyResources(), lmms::gui::getGUI(), lmms::ConfigManager::inst(), nameWithExtension(), ts, and write().
Referenced by ~DataFile(), lmms::gui::PianoRollWindow::exportMidiClip(), main(), lmms::Song::saveProjectFile(), and lmms::gui::InstrumentTrackWindow::saveSettingsBtnClicked().
Member Data Documentation
ELEMENTS_WITH_RESOURCES
const DataFile::ResourcesMap lmms::DataFile::ELEMENTS_WITH_RESOURCES static private
Initial value:
= {
{ "sampleclip", {"src"} },
{ "audiofileprocessor", {"src"} },
}
Definition at line 146 of file DataFile.h.
Referenced by copyResources(), hasLocalPlugins(), and mapSrcAttributeInElementsWithResources().
m_content
QDomElement lmms::DataFile::m_content private
Definition at line 153 of file DataFile.h.
Referenced by DataFile(), DataFile(), DataFile(), content(), and loadData().
m_fileName
QString lmms::DataFile::m_fileName private
The origin file name or "" if this DataFile didn't originate from a file.
Definition at line 152 of file DataFile.h.
Referenced by DataFile(), DataFile(), DataFile(), and copyResources().
m_fileVersion
unsigned int lmms::DataFile::m_fileVersion private
Definition at line 156 of file DataFile.h.
Referenced by DataFile(), DataFile(), DataFile(), loadData(), and upgrade().
m_head
QDomElement lmms::DataFile::m_head private
Definition at line 154 of file DataFile.h.
Referenced by DataFile(), DataFile(), DataFile(), head(), loadData(), upgrade(), and upgrade_0_2_1_20070501().
m_type
Type lmms::DataFile::m_type private
Definition at line 155 of file DataFile.h.
Referenced by DataFile(), loadData(), type(), and validate().
UPGRADE_METHODS
const std::vector< DataFile::UpgradeMethod > lmms::DataFile::UPGRADE_METHODS static private
Initial value:
= {
    &DataFile::upgrade_0_2_1_20070501   ,   &DataFile::upgrade_0_2_1_20070508,
    &DataFile::upgrade_0_3_0_rc2        ,   &DataFile::upgrade_0_3_0,
    &DataFile::upgrade_0_4_0_20080104   ,   &DataFile::upgrade_0_4_0_20080118,
    &DataFile::upgrade_0_4_0_20080129   ,   &DataFile::upgrade_0_4_0_20080409,
    &DataFile::upgrade_0_4_0_20080607   ,   &DataFile::upgrade_0_4_0_20080622,
    &DataFile::upgrade_0_4_0_beta1      ,   &DataFile::upgrade_0_4_0_rc2,
    &DataFile::upgrade_1_0_99           ,   &DataFile::upgrade_1_1_0,
    &DataFile::upgrade_1_1_91           ,   &DataFile::upgrade_1_2_0_rc3,
    &DataFile::upgrade_1_3_0            ,   &DataFile::upgrade_noHiddenClipNames,
    &DataFile::upgrade_automationNodes  ,   &DataFile::upgrade_extendedNoteRange,
    &DataFile::upgrade_defaultTripleOscillatorHQ,
    &DataFile::upgrade_mixerRename      ,   &DataFile::upgrade_bbTcoRename,
    &DataFile::upgrade_sampleAndHold    ,   &DataFile::upgrade_midiCCIndexing,
    &DataFile::upgrade_loopsRename      ,   &DataFile::upgrade_noteTypes,
    &DataFile::upgrade_fixCMTDelays     ,   &DataFile::upgrade_fixBassLoopsTypo,
    &DataFile::findProblematicLadspaPlugins,
    &DataFile::upgrade_noHiddenAutomationTracks
}
Definition at line 140 of file DataFile.h.
Referenced by DataFile(), DataFile(), DataFile(), loadData(), and upgrade().
UPGRADE_VERSIONS
const std::vector< ProjectVersion > lmms::DataFile::UPGRADE_VERSIONS static private
Initial value:
= {
    "0.2.1-20070501"   ,   "0.2.1-20070508"   ,   "0.3.0-rc2",
    "0.3.0"            ,   "0.4.0-20080104"   ,   "0.4.0-20080118",
    "0.4.0-20080129"   ,   "0.4.0-20080409"   ,   "0.4.0-20080607",
    "0.4.0-20080622"   ,   "0.4.0-beta1"      ,   "0.4.0-rc2",
    "1.0.99-0"         ,   "1.1.0-0"          ,   "1.1.91-0",
    "1.2.0-rc3"        ,   "1.3.0"
}
Definition at line 142 of file DataFile.h.
Referenced by legacyFileVersion().
The documentation for this class was generated from the following files:
include/DataFile.h
src/core/DataFile.cpp