LMMS: hiir::StageProc4F64Avx< REMAINING > Class Template Reference
hiir::StageProc4F64Avx< REMAINING > Class Template Reference
#include <StageProc4F64Avx.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m256d &spl_0, __m256d &spl_1, StageDataF64Avx *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m256d &spl_0, __m256d &spl_1, StageDataF64Avx *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m256d &spl_0, __m256d &spl_1, StageDataF64Avx *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m256d &spl_0, __m256d &spl_1, StageDataF64Avx *stage_arr) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m256d &spl_0, __m256d &spl_1, StageDataF64Avx *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m256d &spl_0, __m256d &spl_1, StageDataF64Avx *stage_arr) noexcept
Private Member Functions
StageProc4F64Avx ()=delete
StageProc4F64Avx (const StageProc4F64Avx< REMAINING > &other)=delete
StageProc4F64Avx (StageProc4F64Avx< REMAINING > &&other)=delete
~StageProc4F64Avx ()=delete
bool operator!= (const StageProc4F64Avx< REMAINING > &other)=delete
StageProc4F64Avx< REMAINING > & operator= (const StageProc4F64Avx< REMAINING > &other)=delete
StageProc4F64Avx< REMAINING > & operator= (StageProc4F64Avx< REMAINING > &&other)=delete
bool operator== (const StageProc4F64Avx< REMAINING > &other)=delete
Detailed Description
template<int REMAINING>
class hiir::StageProc4F64Avx< REMAINING >
Definition at line 48 of file StageProc4F64Avx.h.
Constructor & Destructor Documentation
StageProc4F64Avx() [1/3]
template<int REMAINING> hiir::StageProc4F64Avx< REMAINING >::StageProc4F64Avx () private delete
Referenced by process_sample_neg(), and process_sample_pos().
StageProc4F64Avx() [2/3]
template<int REMAINING> hiir::StageProc4F64Avx< REMAINING >::StageProc4F64Avx (const StageProc4F64Avx< REMAINING > & other) private delete
StageProc4F64Avx() [3/3]
template<int REMAINING> hiir::StageProc4F64Avx< REMAINING >::StageProc4F64Avx (StageProc4F64Avx< REMAINING > && other) private delete
~StageProc4F64Avx()
template<int REMAINING> hiir::StageProc4F64Avx< REMAINING >::~StageProc4F64Avx () private delete
Member Function Documentation
operator!=()
template<int REMAINING> bool hiir::StageProc4F64Avx< REMAINING >::operator!= (const StageProc4F64Avx< REMAINING > & other) private delete
operator=() [1/2]
template<int REMAINING> StageProc4F64Avx< REMAINING > & hiir::StageProc4F64Avx< REMAINING >::operator= (const StageProc4F64Avx< REMAINING > & other) private delete
operator=() [2/2]
template<int REMAINING> StageProc4F64Avx< REMAINING > & hiir::StageProc4F64Avx< REMAINING >::operator= (StageProc4F64Avx< REMAINING > && other) private delete
operator==()
template<int REMAINING> bool hiir::StageProc4F64Avx< REMAINING >::operator== (const StageProc4F64Avx< REMAINING > & other) private delete
process_sample_neg() [1/3]
template<int REMAINING> void hiir::StageProc4F64Avx< REMAINING >::process_sample_neg (const int nbr_coefs, __m256d & spl_0, __m256d & spl_1, StageDataF64Avx * stage_arr) static noexcept
Definition at line 147 of file StageProc4F64Avx.hpp.
References StageProc4F64Avx(), and process_sample_neg().
Referenced by hiir::PhaseHalfPi4F64Avx< NC >::process_block(), hiir::PhaseHalfPi4F64Avx< NC >::process_sample(), and process_sample_neg().
process_sample_neg() [2/3]
hiir_FORCEINLINE void hiir::StageProc4F64Avx< 0 >::process_sample_neg (const int nbr_coefs, __m256d & spl_0, __m256d & spl_1, StageDataF64Avx * stage_arr) noexcept
Definition at line 136 of file StageProc4F64Avx.hpp.
References hiir_FORCEINLINE.
process_sample_neg() [3/3]
hiir_FORCEINLINE void hiir::StageProc4F64Avx< 1 >::process_sample_neg (const int nbr_coefs, __m256d & spl_0, __m256d & spl_1, StageDataF64Avx * stage_arr) noexcept
Definition at line 114 of file StageProc4F64Avx.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [1/3]
template<int REMAINING> void hiir::StageProc4F64Avx< REMAINING >::process_sample_pos (const int nbr_coefs, __m256d & spl_0, __m256d & spl_1, StageDataF64Avx * stage_arr) static noexcept
Definition at line 78 of file StageProc4F64Avx.hpp.
References StageProc4F64Avx(), and process_sample_pos().
Referenced by hiir::HalfBand4F64Avx< NC >::process_2_paths(), hiir::HalfBand4F64Avx< NC >::process_block_2_paths(), hiir::Downsampler2x4F64Avx< NC >::process_sample(), hiir::Upsampler2x4F64Avx< NC >::process_sample(), process_sample_pos(), and hiir::Downsampler2x4F64Avx< NC >::process_sample_split().
process_sample_pos() [2/3]
hiir_FORCEINLINE void hiir::StageProc4F64Avx< 0 >::process_sample_pos (const int nbr_coefs, __m256d & spl_0, __m256d & spl_1, StageDataF64Avx * stage_arr) noexcept
Definition at line 67 of file StageProc4F64Avx.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [3/3]
hiir_FORCEINLINE void hiir::StageProc4F64Avx< 1 >::process_sample_pos (const int nbr_coefs, __m256d & spl_0, __m256d & spl_1, StageDataF64Avx * stage_arr) noexcept
Definition at line 45 of file StageProc4F64Avx.hpp.
References hiir_FORCEINLINE.
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProc4F64Avx.h
src/3rdparty/hiir/hiir/StageProc4F64Avx.hpp