LMMS: hiir::PolyphaseIir2Designer Class Reference
hiir::PolyphaseIir2Designer Class Reference
#include <PolyphaseIir2Designer.h>
Public Types
enum ResCode : int {
ResCode_FAIL_CONV = -3 ,
ResCode_FAIL_ATTEN = -2 ,
ResCode_FAIL_GD_TBW = -1 ,
ResCode_OK = 0
}
Static Public Member Functions
static double compute_atten_from_order_tbw (int nbr_coefs, double transition) noexcept
static int compute_coefs (double coef_arr[], double attenuation, double transition) noexcept
static ResCode compute_coefs_spec_order_gdly (double coef_arr[], double *attenuation_ptr, double *transition_ptr, int nbr_coefs, double group_delay, double f_rel, double prec=1e-6, double atten_lb=0.001, double atten_ub=10000.0, double trans_lb=0.001, double trans_ub=0.499) noexcept
static ResCode compute_coefs_spec_order_pdly (double coef_arr[], double *attenuation_ptr, double *transition_ptr, int nbr_coefs, double phase_delay, double f_rel, double prec=1e-6, double atten_lb=0.001, double atten_ub=10000.0, double trans_lb=0.001, double trans_ub=0.499) noexcept
static void compute_coefs_spec_order_tbw (double coef_arr[], int nbr_coefs, double transition) noexcept
static double compute_group_delay (const double coef_arr[], int nbr_coefs, double f_fs, bool ph_flag) noexcept
static int compute_nbr_coefs_from_proto (double attenuation, double transition) noexcept
static double compute_phase_delay (const double coef_arr[], int nbr_coefs, double f_fs, bool ph_flag) noexcept
static double compute_unit_group_delay (double a, double f_fs, bool ph_flag) noexcept
static double compute_unit_phase_delay (double a, double f_fs, bool ph_flag) noexcept
Static Public Attributes
static constexpr int _max_order = 256
Private Member Functions
PolyphaseIir2Designer ()=delete
PolyphaseIir2Designer (const PolyphaseIir2Designer &other)=delete
PolyphaseIir2Designer (PolyphaseIir2Designer &&other)=delete
~PolyphaseIir2Designer ()=delete
bool operator!= (const PolyphaseIir2Designer &other)=delete
PolyphaseIir2Designer & operator= (const PolyphaseIir2Designer &other)=delete
PolyphaseIir2Designer & operator= (PolyphaseIir2Designer &&other)=delete
bool operator== (const PolyphaseIir2Designer &other)=delete
Static Private Member Functions
static double compute_acc_den (double q, int order, int c) noexcept
static double compute_acc_num (double q, int order, int c) noexcept
static double compute_atten (double q, int order) noexcept
static double compute_coef (int index, double k, double q, int order) noexcept
template<typename F>
static ResCode compute_coefs_spec_order_delay (double coef_arr[], double *attenuation_ptr, double *transition_ptr, int nbr_coefs, double delay, double f_rel, double prec, double atten_lb, double atten_ub, double trans_lb, double trans_ub, F compute_delay) noexcept
static int compute_order (double attenuation, double q) noexcept
static void compute_transition_param (double &k, double &q, double transition) noexcept
Detailed Description
Definition at line 81 of file PolyphaseIir2Designer.h.
Member Enumeration Documentation
ResCode
enum hiir::PolyphaseIir2Designer::ResCode : int
Enumerator
ResCode_FAIL_CONV
ResCode_FAIL_ATTEN
ResCode_FAIL_GD_TBW
ResCode_OK
Definition at line 91 of file PolyphaseIir2Designer.h.
Constructor & Destructor Documentation
PolyphaseIir2Designer() [1/3]
hiir::PolyphaseIir2Designer::PolyphaseIir2Designer () private delete
References PolyphaseIir2Designer().
Referenced by PolyphaseIir2Designer(), PolyphaseIir2Designer(), PolyphaseIir2Designer(), ~PolyphaseIir2Designer(), operator!=(), operator=(), operator=(), and operator==().
~PolyphaseIir2Designer()
hiir::PolyphaseIir2Designer::~PolyphaseIir2Designer () private delete
References PolyphaseIir2Designer().
PolyphaseIir2Designer() [2/3]
hiir::PolyphaseIir2Designer::PolyphaseIir2Designer (const PolyphaseIir2Designer & other) private delete
References PolyphaseIir2Designer().
PolyphaseIir2Designer() [3/3]
hiir::PolyphaseIir2Designer::PolyphaseIir2Designer (PolyphaseIir2Designer && other) private delete
References PolyphaseIir2Designer().
Member Function Documentation
compute_acc_den()
double hiir::PolyphaseIir2Designer::compute_acc_den (double q, int order, int c) inline static private noexcept
Definition at line 797 of file PolyphaseIir2Designer.h.
References i, hiir::ipowp(), j, and hiir::PI.
Referenced by compute_coef().
compute_acc_num()
double hiir::PolyphaseIir2Designer::compute_acc_num (double q, int order, int c) inline static private noexcept
Definition at line 772 of file PolyphaseIir2Designer.h.
References i, hiir::ipowp(), j, and hiir::PI.
Referenced by compute_coef().
compute_atten()
double hiir::PolyphaseIir2Designer::compute_atten (double q, int order) inline static private noexcept
Definition at line 736 of file PolyphaseIir2Designer.h.
Referenced by compute_atten_from_order_tbw().
compute_atten_from_order_tbw()
double hiir::PolyphaseIir2Designer::compute_atten_from_order_tbw (int nbr_coefs, double transition) inline static noexcept
Definition at line 262 of file PolyphaseIir2Designer.h.
References compute_atten(), compute_transition_param(), and k.
Referenced by compute_coefs_spec_order_delay().
compute_coef()
double hiir::PolyphaseIir2Designer::compute_coef (int index, double k, double q, int order) inline static private noexcept
Definition at line 753 of file PolyphaseIir2Designer.h.
References compute_acc_den(), compute_acc_num(), and k.
Referenced by compute_coefs(), and compute_coefs_spec_order_tbw().
compute_coefs()
int hiir::PolyphaseIir2Designer::compute_coefs (double coef_arr[], double attenuation, double transition) inline static noexcept
Definition at line 298 of file PolyphaseIir2Designer.h.
References compute_coef(), compute_order(), compute_transition_param(), and k.
compute_coefs_spec_order_delay()
template<typename F> PolyphaseIir2Designer::ResCode hiir::PolyphaseIir2Designer::compute_coefs_spec_order_delay (double coef_arr[], double * attenuation_ptr, double * transition_ptr, int nbr_coefs, double delay, double f_rel, double prec, double atten_lb, double atten_ub, double trans_lb, double trans_ub, F compute_delay) static private noexcept
Definition at line 823 of file PolyphaseIir2Designer.h.
References _max_order, compute_atten_from_order_tbw(), compute_coefs_spec_order_tbw(), ResCode_FAIL_ATTEN, ResCode_FAIL_CONV, ResCode_FAIL_GD_TBW, and ResCode_OK.
Referenced by compute_coefs_spec_order_gdly(), and compute_coefs_spec_order_pdly().
compute_coefs_spec_order_gdly()
PolyphaseIir2Designer::ResCode hiir::PolyphaseIir2Designer::compute_coefs_spec_order_gdly (double coef_arr[], double * attenuation_ptr, double * transition_ptr, int nbr_coefs, double group_delay, double f_rel, double prec = 1e-6, double atten_lb = 0.001, double atten_ub = 10000.0, double trans_lb = 0.001, double trans_ub = 0.499) inline static noexcept
Definition at line 490 of file PolyphaseIir2Designer.h.
References compute_coefs_spec_order_delay(), and compute_group_delay().
compute_coefs_spec_order_pdly()
PolyphaseIir2Designer::ResCode hiir::PolyphaseIir2Designer::compute_coefs_spec_order_pdly (double coef_arr[], double * attenuation_ptr, double * transition_ptr, int nbr_coefs, double phase_delay, double f_rel, double prec = 1e-6, double atten_lb = 0.001, double atten_ub = 10000.0, double trans_lb = 0.001, double trans_ub = 0.499) inline static noexcept
Definition at line 413 of file PolyphaseIir2Designer.h.
References compute_coefs_spec_order_delay(), and compute_phase_delay().
compute_coefs_spec_order_tbw()
void hiir::PolyphaseIir2Designer::compute_coefs_spec_order_tbw (double coef_arr[], int nbr_coefs, double transition) inline static noexcept
Definition at line 344 of file PolyphaseIir2Designer.h.
References compute_coef(), compute_transition_param(), and k.
Referenced by compute_coefs_spec_order_delay(), lmms::Downsampler< MaxStages, MaxCoefs >::reset(), and lmms::Upsampler< MaxStages, MaxCoefs >::reset().
compute_group_delay()
double hiir::PolyphaseIir2Designer::compute_group_delay (const double coef_arr[], int nbr_coefs, double f_fs, bool ph_flag) inline static noexcept
Definition at line 582 of file PolyphaseIir2Designer.h.
References compute_unit_group_delay(), and k.
Referenced by compute_coefs_spec_order_gdly().
compute_nbr_coefs_from_proto()
int hiir::PolyphaseIir2Designer::compute_nbr_coefs_from_proto (double attenuation, double transition) inline static noexcept
Definition at line 230 of file PolyphaseIir2Designer.h.
References compute_order(), compute_transition_param(), and k.
compute_order()
int hiir::PolyphaseIir2Designer::compute_order (double attenuation, double q) inline static private noexcept
Definition at line 714 of file PolyphaseIir2Designer.h.
References hiir::ceil_int().
Referenced by compute_coefs(), and compute_nbr_coefs_from_proto().
compute_phase_delay()
double hiir::PolyphaseIir2Designer::compute_phase_delay (const double coef_arr[], int nbr_coefs, double f_fs, bool ph_flag) inline static noexcept
Definition at line 524 of file PolyphaseIir2Designer.h.
References compute_unit_phase_delay(), k, and hiir::PI.
Referenced by compute_coefs_spec_order_pdly().
compute_transition_param()
void hiir::PolyphaseIir2Designer::compute_transition_param (double & k, double & q, double transition) inline static private noexcept
Definition at line 695 of file PolyphaseIir2Designer.h.
References k, and hiir::PI.
Referenced by compute_atten_from_order_tbw(), compute_coefs(), compute_coefs_spec_order_tbw(), and compute_nbr_coefs_from_proto().
compute_unit_group_delay()
double hiir::PolyphaseIir2Designer::compute_unit_group_delay (double a, double f_fs, bool ph_flag) inline static noexcept
Definition at line 670 of file PolyphaseIir2Designer.h.
References hiir::PI.
Referenced by compute_group_delay().
compute_unit_phase_delay()
double hiir::PolyphaseIir2Designer::compute_unit_phase_delay (double a, double f_fs, bool ph_flag) inline static noexcept
Definition at line 622 of file PolyphaseIir2Designer.h.
References hiir::PI.
Referenced by compute_phase_delay().
operator!=()
bool hiir::PolyphaseIir2Designer::operator!= (const PolyphaseIir2Designer & other) private delete
References PolyphaseIir2Designer().
operator=() [1/2]
PolyphaseIir2Designer & hiir::PolyphaseIir2Designer::operator= (const PolyphaseIir2Designer & other) private delete
References PolyphaseIir2Designer().
operator=() [2/2]
PolyphaseIir2Designer & hiir::PolyphaseIir2Designer::operator= (PolyphaseIir2Designer && other) private delete
References PolyphaseIir2Designer().
operator==()
bool hiir::PolyphaseIir2Designer::operator== (const PolyphaseIir2Designer & other) private delete
References PolyphaseIir2Designer().
Member Data Documentation
_max_order
int hiir::PolyphaseIir2Designer::_max_order = 256 static constexpr
Definition at line 89 of file PolyphaseIir2Designer.h.
Referenced by compute_coefs_spec_order_delay().
The documentation for this class was generated from the following file:
src/3rdparty/hiir/hiir/PolyphaseIir2Designer.h