LMMS: lmms::SampleThumbnail Class Reference
lmms::SampleThumbnail Class Reference
Allows for visualizing sample data.
#include <SampleThumbnail.h>
Classes
struct Hash
struct SampleThumbnailEntry
class Thumbnail
struct VisualizeParameters
Public Member Functions
SampleThumbnail ()=default
SampleThumbnail (const Sample &sample)
void visualize (VisualizeParameters parameters, QPainter &painter) const
Private Types
using ThumbnailCache = std::vector<Thumbnail>
Private Attributes
std::shared_ptr< const SampleBuffer > m_buffer = SampleBuffer::emptyBuffer()
std::shared_ptr< ThumbnailCache > m_thumbnailCache = std::make_shared<ThumbnailCache>()
Static Private Attributes
static std::unordered_map< SampleThumbnailEntry, std::shared_ptr< ThumbnailCache >, Hash > s_sampleThumbnailCacheMap
Detailed Description
Allows for visualizing sample data.
On construction, thumbnails will be generated at logarathmic intervals of downsampling. Those cached thumbnails will then be further downsampled on the fly and transformed in various ways to create the desired waveform.
Given that we are dealing with far less data to generate the visualization however (i.e., we are not reading from original sample data when drawing), this provides a significant performance boost that wouldn't be possible otherwise.
Definition at line 54 of file SampleThumbnail.h.
Member Typedef Documentation
ThumbnailCache
using lmms::SampleThumbnail::ThumbnailCache = std::vector<Thumbnail> private
Definition at line 138 of file SampleThumbnail.h.
Constructor & Destructor Documentation
SampleThumbnail() [1/2]
lmms::SampleThumbnail::SampleThumbnail () default
References SampleThumbnail(), and visualize().
Referenced by SampleThumbnail().
SampleThumbnail() [2/2]
lmms::SampleThumbnail::SampleThumbnail (const Sample & sample)
Definition at line 74 of file SampleThumbnail.cpp.
References m_buffer, s_sampleThumbnailCacheMap, and lmms::Sample::sampleFile().
Member Function Documentation
visualize()
void lmms::SampleThumbnail::visualize (VisualizeParameters parameters, QPainter & painter) const
Definition at line 108 of file SampleThumbnail.cpp.
References lmms::SampleThumbnail::VisualizeParameters::amplification, i, m_buffer, m_thumbnailCache, max, min, lmms::SampleThumbnail::VisualizeParameters::reversed, lmms::SampleThumbnail::VisualizeParameters::sampleEnd, lmms::SampleThumbnail::VisualizeParameters::sampleRect, lmms::SampleThumbnail::VisualizeParameters::sampleStart, lmms::SampleThumbnail::VisualizeParameters::viewportRect, and visualize().
Referenced by SampleThumbnail(), and visualize().
Member Data Documentation
m_buffer
std::shared_ptr<const SampleBuffer> lmms::SampleThumbnail::m_buffer = SampleBuffer::emptyBuffer() private
Definition at line 140 of file SampleThumbnail.h.
Referenced by SampleThumbnail(), and visualize().
m_thumbnailCache
std::shared_ptr<ThumbnailCache> lmms::SampleThumbnail::m_thumbnailCache = std::make_shared<ThumbnailCache>() private
Definition at line 139 of file SampleThumbnail.h.
Referenced by visualize().
s_sampleThumbnailCacheMap
std::unordered_map<SampleThumbnailEntry, std::shared_ptr<ThumbnailCache>, Hash> lmms::SampleThumbnail::s_sampleThumbnailCacheMap inline static private
Definition at line 141 of file SampleThumbnail.h.
Referenced by SampleThumbnail().
The documentation for this class was generated from the following files:
include/SampleThumbnail.h
src/gui/SampleThumbnail.cpp