LMMS: src/3rdparty/jack2/common/promiscuous.h File Reference
promiscuous.h File Reference
Functions
int jack_group2gid (const char *group)
Lookup gid for a UNIX group in a thread-safe way.
int jack_promiscuous_perms (int fd, const char *path, gid_t gid)
Set promiscuous permissions on object referenced by fd and/or path.
Function Documentation
jack_group2gid()
int jack_group2gid (const char * group)
Lookup gid for a UNIX group in a thread-safe way.
Referenced by Jack::JackClientSocket::JackClientSocket(), Jack::JackLinuxFutex::JackLinuxFutex(), Jack::JackPosixSemaphore::JackPosixSemaphore(), and Jack::JackServerSocket::JackServerSocket().
jack_promiscuous_perms()
int jack_promiscuous_perms (int fd, const char * path, gid_t gid)
Set promiscuous permissions on object referenced by fd and/or path.
Referenced by Jack::JackLinuxFutex::Allocate(), Jack::JackPosixSemaphore::Allocate(), and Jack::JackServerSocket::Bind().