LMMS: lmms::gui::MidiPortMenu Class Reference
lmms::gui::MidiPortMenu Class Reference
#include <MidiPortMenu.h>
Public Slots
void updateMenu ()
Public Member Functions
MidiPortMenu (MidiPort::Mode _mode)
~MidiPortMenu () override=default
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Slots
void activatedPort (QAction *_item)
Private Member Functions
void modelChanged () override
Private Attributes
MidiPort::Mode m_mode
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Detailed Description
Definition at line 39 of file MidiPortMenu.h.
Constructor & Destructor Documentation
MidiPortMenu()
lmms::gui::MidiPortMenu::MidiPortMenu (MidiPort::Mode _mode)
Definition at line 32 of file MidiPortMenu.cpp.
References lmms::gui::ModelView::ModelView(), activatedPort(), and m_mode.
~MidiPortMenu()
lmms::gui::MidiPortMenu::~MidiPortMenu () override default
Member Function Documentation
activatedPort
void lmms::gui::MidiPortMenu::activatedPort (QAction * _item) protected slot
Definition at line 63 of file MidiPortMenu.cpp.
References lmms::gui::ModelView::castModel(), lmms::MidiPort::Input, m_mode, and lmms::MidiPort::Output.
Referenced by MidiPortMenu().
modelChanged()
void lmms::gui::MidiPortMenu::modelChanged () override private virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 44 of file MidiPortMenu.cpp.
References lmms::gui::ModelView::castModel(), lmms::MidiPort::Input, m_mode, lmms::MidiPort::Output, and updateMenu().
updateMenu
void lmms::gui::MidiPortMenu::updateMenu () slot
Definition at line 80 of file MidiPortMenu.cpp.
References lmms::gui::ModelView::castModel(), lmms::MidiPort::Input, and m_mode.
Referenced by modelChanged().
Member Data Documentation
m_mode
MidiPort::Mode lmms::gui::MidiPortMenu::m_mode private
Definition at line 58 of file MidiPortMenu.h.
Referenced by MidiPortMenu(), activatedPort(), modelChanged(), and updateMenu().
The documentation for this class was generated from the following files:
include/MidiPortMenu.h
src/gui/menus/MidiPortMenu.cpp