LMMS: lmms::gui::SampleTrackWindow Class Reference
lmms::gui::SampleTrackWindow Class Reference
#include <SampleTrackWindow.h>
Public Slots
void textChanged (const QString &new_name)
void toggleVisibility (bool on)
void updateName ()
Public Member Functions
SampleTrackWindow (SampleTrackView *tv)
~SampleTrackWindow () override=default
SampleTrack * model ()
const SampleTrack * model () const
SampleTrackView * sampleTrackView ()
void setSampleTrackView (SampleTrackView *tv)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::SerializingObjectHook
SerializingObjectHook ()
virtual ~SerializingObjectHook ()
Protected Member Functions
void closeEvent (QCloseEvent *ce) override
void loadSettings (const QDomElement &element) override
void saveSettings (QDomDocument &doc, QDomElement &element) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Member Functions
void modelChanged () override
Private Attributes
EffectRackView * m_effectRack
MixerChannelLcdSpinBox * m_mixerChannelNumber
AutomatableButton * m_muteBtn
QLineEdit * m_nameLineEdit
Knob * m_panningKnob
AutomatableButton * m_soloBtn
SampleTrackView * m_stv
SampleTrack * m_track
Knob * m_volumeKnob
Detailed Description
Definition at line 46 of file SampleTrackWindow.h.
Constructor & Destructor Documentation
SampleTrackWindow()
lmms::gui::SampleTrackWindow::SampleTrackWindow (SampleTrackView * tv)
Definition at line 50 of file SampleTrackWindow.cpp.
References lmms::gui::ModelView::ModelView(), lmms::gui::MainWindow::addWindowedWidget(), lmms::SampleTrack::audioBusHandle(), lmms::gui::Bright26, lmms::gui::EffectRackView::DEFAULT_WIDTH, lmms::AudioBusHandle::effects(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), m_effectRack, m_mixerChannelNumber, m_muteBtn, m_nameLineEdit, m_panningKnob, m_soloBtn, m_stv, m_track, m_volumeKnob, lmms::gui::GuiApplication::mainWindow(), lmms::gui::SampleTrackView::model(), model(), lmms::gui::ModelView::setModel(), and textChanged().
~SampleTrackWindow()
lmms::gui::SampleTrackWindow::~SampleTrackWindow () override default
Member Function Documentation
closeEvent()
void lmms::gui::SampleTrackWindow::closeEvent (QCloseEvent * ce) override protected
Definition at line 258 of file SampleTrackWindow.cpp.
References lmms::gui::getGUI(), and m_stv.
loadSettings()
void lmms::gui::SampleTrackWindow::loadSettings (const QDomElement & element) override protected virtual
Implements lmms::SerializingObjectHook.
Definition at line 285 of file SampleTrackWindow.cpp.
References m_stv, and lmms::gui::MainWindow::restoreWidgetState().
model() [1/2]
SampleTrack * lmms::gui::SampleTrackWindow::model () inline
Definition at line 53 of file SampleTrackWindow.h.
References lmms::gui::ModelView::castModel().
Referenced by SampleTrackWindow().
model() [2/2]
const SampleTrack * lmms::gui::SampleTrackWindow::model () const inline
Definition at line 58 of file SampleTrackWindow.h.
References lmms::gui::ModelView::castModel().
modelChanged()
void lmms::gui::SampleTrackWindow::modelChanged () override private virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 200 of file SampleTrackWindow.cpp.
References lmms::gui::ModelView::castModel(), m_mixerChannelNumber, m_nameLineEdit, m_panningKnob, m_track, m_volumeKnob, and updateName().
sampleTrackView()
SampleTrackView * lmms::gui::SampleTrackWindow::sampleTrackView () inline
Definition at line 65 of file SampleTrackWindow.h.
References m_stv.
saveSettings()
void lmms::gui::SampleTrackWindow::saveSettings (QDomDocument & doc, QDomElement & element) override protected virtual
Implements lmms::SerializingObjectHook.
Definition at line 277 of file SampleTrackWindow.cpp.
References lmms::gui::MainWindow::saveWidgetState().
setSampleTrackView()
void lmms::gui::SampleTrackWindow::setSampleTrackView (SampleTrackView * tv)
Definition at line 188 of file SampleTrackWindow.cpp.
References m_stv.
textChanged
void lmms::gui::SampleTrackWindow::textChanged (const QString & new_name) slot
Definition at line 233 of file SampleTrackWindow.cpp.
References lmms::Engine::getSong(), m_track, and lmms::Song::setModified().
Referenced by SampleTrackWindow().
toggleVisibility
void lmms::gui::SampleTrackWindow::toggleVisibility (bool on) slot
Definition at line 241 of file SampleTrackWindow.cpp.
updateName
void lmms::gui::SampleTrackWindow::updateName () slot
Definition at line 221 of file SampleTrackWindow.cpp.
References m_nameLineEdit, and m_track.
Referenced by modelChanged().
Member Data Documentation
m_effectRack
EffectRackView* lmms::gui::SampleTrackWindow::m_effectRack private
Definition at line 98 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow().
m_mixerChannelNumber
MixerChannelLcdSpinBox* lmms::gui::SampleTrackWindow::m_mixerChannelNumber private
Definition at line 96 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow(), and modelChanged().
m_muteBtn
AutomatableButton* lmms::gui::SampleTrackWindow::m_muteBtn private
Definition at line 94 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow().
m_nameLineEdit
QLineEdit* lmms::gui::SampleTrackWindow::m_nameLineEdit private
Definition at line 91 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow(), modelChanged(), and updateName().
m_panningKnob
Knob* lmms::gui::SampleTrackWindow::m_panningKnob private
Definition at line 93 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow(), and modelChanged().
m_soloBtn
AutomatableButton* lmms::gui::SampleTrackWindow::m_soloBtn private
Definition at line 95 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow().
m_stv
SampleTrackView* lmms::gui::SampleTrackWindow::m_stv private
Definition at line 88 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow(), closeEvent(), loadSettings(), sampleTrackView(), and setSampleTrackView().
m_track
SampleTrack* lmms::gui::SampleTrackWindow::m_track private
Definition at line 87 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow(), modelChanged(), textChanged(), and updateName().
m_volumeKnob
Knob* lmms::gui::SampleTrackWindow::m_volumeKnob private
Definition at line 92 of file SampleTrackWindow.h.
Referenced by SampleTrackWindow(), and modelChanged().
The documentation for this class was generated from the following files:
include/SampleTrackWindow.h
src/gui/SampleTrackWindow.cpp