LMMS: hiir::PhaseHalfPiNeon< NC > Class Template Reference
hiir::PhaseHalfPiNeon< NC > Class Template Reference
#include <PhaseHalfPiNeon.h>
Public Types
typedef float DataType
Public Member Functions
PhaseHalfPiNeon () noexcept
PhaseHalfPiNeon (const PhaseHalfPiNeon< NC > &other)=default
PhaseHalfPiNeon (PhaseHalfPiNeon< NC > &&other)=default
~PhaseHalfPiNeon ()=default
void clear_buffers () noexcept
PhaseHalfPiNeon< NC > & operator= (const PhaseHalfPiNeon< NC > &other)=default
PhaseHalfPiNeon< NC > & operator= (PhaseHalfPiNeon< NC > &&other)=default
void process_block (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (float &out_0, float &out_1, float input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 2
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataNeonV4, _nbr_stages+1 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const PhaseHalfPiNeon< NC > &other) const =delete
bool operator== (const PhaseHalfPiNeon< NC > &other) const =delete
hiir_FORCEINLINE long process_block_quad (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
void set_single_coef (int index, double coef) noexcept
Private Attributes
FilterBiPhase _filter
int _phase
float _prev
Static Private Attributes
static constexpr int _coef_shift = ((NBR_COEFS & 1) * 2) ^ 3
static constexpr int _nbr_phases = 2
static constexpr int _nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width
static constexpr int _stage_width = 4
Detailed Description
template<int NC>
class hiir::PhaseHalfPiNeon< NC >
Definition at line 56 of file PhaseHalfPiNeon.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::PhaseHalfPiNeon< NC >::DataType
Definition at line 65 of file PhaseHalfPiNeon.h.
Filter
template<int NC> typedef std::array<StageDataNeonV4, _nbr_stages + 1> hiir::PhaseHalfPiNeon< NC >::Filter private
Definition at line 106 of file PhaseHalfPiNeon.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::PhaseHalfPiNeon< NC >::FilterBiPhase private
Definition at line 107 of file PhaseHalfPiNeon.h.
Constructor & Destructor Documentation
PhaseHalfPiNeon() [1/3]
template<int NC> hiir::PhaseHalfPiNeon< NC >::PhaseHalfPiNeon () noexcept
Definition at line 58 of file PhaseHalfPiNeon.hpp.
References _filter, _nbr_phases, _nbr_stages, _phase, _prev, _stage_width, clear_buffers(), i, NBR_COEFS, set_single_coef(), and hiir::storea().
Referenced by PhaseHalfPiNeon(), PhaseHalfPiNeon(), ~PhaseHalfPiNeon(), operator!=(), operator=(), operator=(), and operator==().
PhaseHalfPiNeon() [2/3]
template<int NC> hiir::PhaseHalfPiNeon< NC >::PhaseHalfPiNeon (const PhaseHalfPiNeon< NC > & other) default
References PhaseHalfPiNeon().
PhaseHalfPiNeon() [3/3]
template<int NC> hiir::PhaseHalfPiNeon< NC >::PhaseHalfPiNeon (PhaseHalfPiNeon< NC > && other) default
References PhaseHalfPiNeon().
~PhaseHalfPiNeon()
template<int NC> hiir::PhaseHalfPiNeon< NC >::~PhaseHalfPiNeon () default
References PhaseHalfPiNeon().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::PhaseHalfPiNeon< NC >::clear_buffers () noexcept
Definition at line 211 of file PhaseHalfPiNeon.hpp.
References _filter, _nbr_phases, _nbr_stages, i, and hiir::storea().
Referenced by PhaseHalfPiNeon(), and operator=().
operator!=()
template<int NC> bool hiir::PhaseHalfPiNeon< NC >::operator!= (const PhaseHalfPiNeon< NC > & other) const private delete
References PhaseHalfPiNeon().
operator=() [1/2]
template<int NC> PhaseHalfPiNeon< NC > & hiir::PhaseHalfPiNeon< NC >::operator= (const PhaseHalfPiNeon< NC > & other) default
References PhaseHalfPiNeon().
operator=() [2/2]
template<int NC> PhaseHalfPiNeon< NC > & hiir::PhaseHalfPiNeon< NC >::operator= (PhaseHalfPiNeon< NC > && other) default
References PhaseHalfPiNeon(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::PhaseHalfPiNeon< NC >::operator== (const PhaseHalfPiNeon< NC > & other) const private delete
References PhaseHalfPiNeon().
process_block()
template<int NC> void hiir::PhaseHalfPiNeon< NC >::process_block (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 167 of file PhaseHalfPiNeon.hpp.
References _phase, pos, process_block_quad(), and process_sample().
Referenced by operator=().
process_block_quad()
template<int NC> long hiir::PhaseHalfPiNeon< NC >::process_block_quad (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) private noexcept
Definition at line 260 of file PhaseHalfPiNeon.hpp.
References _filter, _nbr_stages, _phase, _prev, hiir::load4a(), hiir::load4u(), pos, hiir::StageProcNeonV4< CUR >::process_sample_neg(), hiir::storea(), and hiir::storeu().
Referenced by process_block().
process_sample()
template<int NC> hiir_FORCEINLINE void hiir::PhaseHalfPiNeon< NC >::process_sample (float & out_0, float & out_1, float input) noexcept
Definition at line 122 of file PhaseHalfPiNeon.hpp.
References _filter, _nbr_stages, _phase, _prev, hiir_FORCEINLINE, hiir::load2a(), hiir::load4a(), and hiir::StageProcNeonV4< CUR >::process_sample_neg().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::PhaseHalfPiNeon< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 95 of file PhaseHalfPiNeon.hpp.
References i, NBR_COEFS, and set_single_coef().
Referenced by operator=().
set_single_coef()
template<int NC> void hiir::PhaseHalfPiNeon< NC >::set_single_coef (int index, double coef) inline private noexcept
Definition at line 244 of file PhaseHalfPiNeon.hpp.
References _coef_shift, _filter, _nbr_phases, _nbr_stages, _stage_width, and pos.
Referenced by PhaseHalfPiNeon(), and set_coefs().
Member Data Documentation
_coef_shift
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_coef_shift = ((NBR_COEFS & 1) * 2) ^ 3 static constexpr private
Definition at line 103 of file PhaseHalfPiNeon.h.
Referenced by set_single_coef().
_delay
template<int NC> double hiir::PhaseHalfPiNeon< NC >::_delay = 2 static constexpr
Definition at line 68 of file PhaseHalfPiNeon.h.
_filter
template<int NC> FilterBiPhase hiir::PhaseHalfPiNeon< NC >::_filter private
Definition at line 115 of file PhaseHalfPiNeon.h.
Referenced by PhaseHalfPiNeon(), clear_buffers(), process_block_quad(), process_sample(), and set_single_coef().
_nbr_chn
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_nbr_chn = 1 static constexpr
Definition at line 66 of file PhaseHalfPiNeon.h.
_nbr_phases
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_nbr_phases = 2 static constexpr private
Definition at line 102 of file PhaseHalfPiNeon.h.
Referenced by PhaseHalfPiNeon(), clear_buffers(), and set_single_coef().
_nbr_stages
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width static constexpr private
Definition at line 101 of file PhaseHalfPiNeon.h.
Referenced by PhaseHalfPiNeon(), clear_buffers(), process_block_quad(), process_sample(), and set_single_coef().
_phase
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_phase private
Definition at line 117 of file PhaseHalfPiNeon.h.
Referenced by PhaseHalfPiNeon(), process_block(), process_block_quad(), and process_sample().
_prev
template<int NC> float hiir::PhaseHalfPiNeon< NC >::_prev private
Definition at line 116 of file PhaseHalfPiNeon.h.
Referenced by PhaseHalfPiNeon(), process_block_quad(), and process_sample().
_stage_width
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_stage_width = 4 static constexpr private
Definition at line 100 of file PhaseHalfPiNeon.h.
Referenced by PhaseHalfPiNeon(), and set_single_coef().
NBR_COEFS
template<int NC> int hiir::PhaseHalfPiNeon< NC >::NBR_COEFS = NC static constexpr
Definition at line 67 of file PhaseHalfPiNeon.h.
Referenced by PhaseHalfPiNeon(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/PhaseHalfPiNeon.h
src/3rdparty/hiir/hiir/PhaseHalfPiNeon.hpp