LMMS: lmms::gui::PianoRollWindow Class Reference
lmms::gui::PianoRollWindow Class Reference
#include <PianoRoll.h>
Signals
void currentMidiClipChanged ()
Public Member Functions
PianoRollWindow ()
const MidiClip * currentMidiClip () const
bool hasFocus () const
bool isRecording () const
void loadSettings (const QDomElement &de) override
QString nodeName () const override
void play () override
int quantization () const
void record () override
void recordAccompany () override
void reset ()
Resets settings to default when e.g.
virtual void restoreState (const QDomElement &_this)
void saveSettings (QDomDocument &doc, QDomElement &de) override
virtual QDomElement saveState (QDomDocument &_doc, QDomElement &_parent)
void setCurrentMidiClip (MidiClip *clip)
void setGhostMidiClip (MidiClip *clip)
QSize sizeHint () const override
void stop () override
void stopRecording ()
void toggleStepRecording () override
Public Member Functions inherited from lmms::gui::Editor
QAction * playAction () const
void setPauseIcon (bool displayPauseIcon=true)
Private Slots
void exportMidiClip ()
void ghostClipSet (bool state)
void importMidiClip ()
void updateAfterMidiClipChange ()
Private Member Functions
void clipRenamed ()
void focusInEvent (QFocusEvent *event) override
void stopStepRecording ()
void updateStepRecordingIcon ()
Private Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Private Attributes
ComboBox * m_chordComboBox
QPushButton * m_clearGhostButton
PianoRoll * m_editor
QToolButton * m_fileToolsButton
ComboBox * m_keyComboBox
ComboBox * m_noteLenComboBox
ComboBox * m_quantizeComboBox
ComboBox * m_scaleComboBox
ComboBox * m_snapComboBox
ComboBox * m_zoomingComboBox
ComboBox * m_zoomingYComboBox
Additional Inherited Members
Public Slots inherited from lmms::gui::Editor
void togglePause ()
Called by pressing shift+space. Toggles pause state.
void togglePlayStop ()
Called by pressing the space key. Plays or stops.
Static Public Member Functions inherited from lmms::gui::Editor
static Editor * lastPlayedEditor ()
Protected Member Functions inherited from lmms::gui::Editor
Editor (bool record=false, bool record_step=false)
Constructor.
~Editor () override=default
DropToolBar * addDropToolBar (Qt::ToolBarArea whereToAdd, QString const &windowTitle)
DropToolBar * addDropToolBar (QWidget *parent, Qt::ToolBarArea whereToAdd, QString const &windowTitle)
DropToolBar * addDropToolBarToTop (QString const &windowTitle)
void closeEvent (QCloseEvent *event) override
void keyPressEvent (QKeyEvent *ke) override
Protected Attributes inherited from lmms::gui::Editor
QAction * m_playAction
QAction * m_recordAccompanyAction
QAction * m_recordAction
QAction * m_stopAction
QAction * m_toggleStepRecordingAction
DropToolBar * m_toolBar
Detailed Description
Definition at line 541 of file PianoRoll.h.
Constructor & Destructor Documentation
PianoRollWindow()
lmms::gui::PianoRollWindow::PianoRollWindow ()
Definition at line 4882 of file PianoRoll.cpp.
References lmms::gui::Editor::Editor(), PianoRollWindow(), lmms::gui::Editor::addDropToolBarToTop(), lmms::combine(), currentMidiClipChanged(), lmms::gui::ComboBox::DEFAULT_HEIGHT, exportMidiClip(), lmms::embed::getIconPixmap(), ghostClipSet(), importMidiClip(), lmms::gui::PianoRoll::Length, m_chordComboBox, m_clearGhostButton, m_editor, m_fileToolsButton, m_keyComboBox, m_noteLenComboBox, lmms::gui::Editor::m_playAction, m_quantizeComboBox, lmms::gui::Editor::m_recordAccompanyAction, lmms::gui::Editor::m_recordAction, m_scaleComboBox, m_snapComboBox, lmms::gui::Editor::m_stopAction, lmms::gui::Editor::m_toggleStepRecordingAction, lmms::gui::Editor::m_toolBar, m_zoomingComboBox, m_zoomingYComboBox, lmms::gui::PianoRoll::Pos, setCurrentMidiClip(), lmms::gui::PianoRoll::setKnifeAction(), lmms::gui::PianoRoll::setStrumAction(), lmms::UI_CTRL_KEY, and updateAfterMidiClipChange().
Referenced by PianoRollWindow().
Member Function Documentation
clipRenamed()
void lmms::gui::PianoRollWindow::clipRenamed () private
Definition at line 5388 of file PianoRoll.cpp.
References currentMidiClip(), and m_fileToolsButton.
Referenced by updateAfterMidiClipChange().
currentMidiClip()
const MidiClip * lmms::gui::PianoRollWindow::currentMidiClip () const
Definition at line 5191 of file PianoRoll.cpp.
References m_editor.
Referenced by clipRenamed(), and lmms::gui::MidiClipView::paintEvent().
currentMidiClipChanged
void lmms::gui::PianoRollWindow::currentMidiClipChanged () signal
Referenced by PianoRollWindow().
exportMidiClip
void lmms::gui::PianoRollWindow::exportMidiClip () private slot
Definition at line 5413 of file PianoRoll.cpp.
References lmms::DataFile::content(), lmms::gui::TextFloat::displayMessage(), lmms::embed::getIconPixmap(), lmms::ConfigManager::inst(), m_editor, lmms::DataFile::MidiClip, lmms::ConfigManager::value(), and lmms::DataFile::writeFile().
Referenced by PianoRollWindow().
focusInEvent()
void lmms::gui::PianoRollWindow::focusInEvent (QFocusEvent * event) override private
Definition at line 5505 of file PianoRoll.cpp.
References m_editor.
ghostClipSet
void lmms::gui::PianoRollWindow::ghostClipSet (bool state) private slot
Definition at line 5405 of file PianoRoll.cpp.
References m_clearGhostButton.
Referenced by PianoRollWindow().
hasFocus()
bool lmms::gui::PianoRollWindow::hasFocus () const
Definition at line 5375 of file PianoRoll.cpp.
References m_editor.
importMidiClip
void lmms::gui::PianoRollWindow::importMidiClip () private slot
Definition at line 5460 of file PianoRoll.cpp.
References lmms::DataFile::content(), lmms::gui::TextFloat::displayMessage(), lmms::embed::getIconPixmap(), lmms::DataFile::head(), m_editor, and pos.
Referenced by PianoRollWindow().
isRecording()
bool lmms::gui::PianoRollWindow::isRecording () const
Definition at line 5228 of file PianoRoll.cpp.
References m_editor.
Referenced by toggleStepRecording().
loadSettings()
void lmms::gui::PianoRollWindow::loadSettings (const QDomElement & de) override virtual
Implements lmms::SerializingObject.
Definition at line 5346 of file PianoRoll.cpp.
References lmms::Engine::getSong(), lmms::Song::getTimeline(), m_editor, lmms::Song::MidiClip, and lmms::gui::MainWindow::restoreWidgetState().
nodeName()
QString lmms::gui::PianoRollWindow::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 570 of file PianoRoll.h.
play()
void lmms::gui::PianoRollWindow::play () override virtual
Reimplemented from lmms::gui::Editor.
Definition at line 5244 of file PianoRoll.cpp.
References m_editor.
quantization()
int lmms::gui::PianoRollWindow::quantization () const
Definition at line 5236 of file PianoRoll.cpp.
References m_editor.
record()
void lmms::gui::PianoRollWindow::record () override virtual
Reimplemented from lmms::gui::Editor.
Definition at line 5260 of file PianoRoll.cpp.
References m_editor, and stopStepRecording().
recordAccompany()
void lmms::gui::PianoRollWindow::recordAccompany () override virtual
Reimplemented from lmms::gui::Editor.
Definition at line 5270 of file PianoRoll.cpp.
References m_editor, and stopStepRecording().
reset()
void lmms::gui::PianoRollWindow::reset ()
Resets settings to default when e.g.
creating a new project
Definition at line 5300 of file PianoRoll.cpp.
References m_editor.
Referenced by lmms::Song::clearProject().
restoreState()
void lmms::SerializingObject::restoreState (const QDomElement & _this) virtual
Reimplemented from lmms::SerializingObject.
Definition at line 50 of file SerializingObject.cpp.
Referenced by lmms::Song::loadProject().
saveSettings()
void lmms::gui::PianoRollWindow::saveSettings (QDomDocument & doc, QDomElement & de) override virtual
Implements lmms::SerializingObject.
Definition at line 5308 of file PianoRoll.cpp.
References lmms::Engine::getSong(), m_editor, lmms::Song::MidiClip, and lmms::gui::MainWindow::saveWidgetState().
saveState()
QDomElement lmms::SerializingObject::saveState (QDomDocument & _doc, QDomElement & _parent) virtual
Reimplemented from lmms::SerializingObject.
Definition at line 48 of file SerializingObject.cpp.
Referenced by lmms::Song::saveProjectFile().
setCurrentMidiClip()
void lmms::gui::PianoRollWindow::setCurrentMidiClip (MidiClip * clip)
Definition at line 5207 of file PianoRoll.cpp.
References lmms::MidiClip::instrumentTrack(), m_editor, m_fileToolsButton, lmms::Clip::name(), and updateAfterMidiClipChange().
Referenced by PianoRollWindow(), and lmms::gui::MidiClipView::openInPianoRoll().
setGhostMidiClip()
void lmms::gui::PianoRollWindow::setGhostMidiClip (MidiClip * clip)
Definition at line 5199 of file PianoRoll.cpp.
References m_editor.
Referenced by lmms::gui::MidiClipView::setGhostInPianoRoll().
sizeHint()
QSize lmms::gui::PianoRollWindow::sizeHint () const override
Definition at line 5368 of file PianoRoll.cpp.
References lmms::gui::INITIAL_PIANOROLL_HEIGHT, and lmms::gui::INITIAL_PIANOROLL_WIDTH.
stop()
void lmms::gui::PianoRollWindow::stop () override virtual
Reimplemented from lmms::gui::Editor.
Definition at line 5252 of file PianoRoll.cpp.
References m_editor.
Referenced by toggleStepRecording().
stopRecording()
void lmms::gui::PianoRollWindow::stopRecording ()
Definition at line 5292 of file PianoRoll.cpp.
References m_editor.
Referenced by lmms::gui::SongEditorWindow::stop().
stopStepRecording()
void lmms::gui::PianoRollWindow::stopStepRecording () private
Definition at line 5511 of file PianoRoll.cpp.
References m_editor, and updateStepRecordingIcon().
Referenced by record(), and recordAccompany().
toggleStepRecording()
void lmms::gui::PianoRollWindow::toggleStepRecording () override virtual
Reimplemented from lmms::gui::Editor.
Definition at line 5278 of file PianoRoll.cpp.
References isRecording(), m_editor, stop(), and updateStepRecordingIcon().
updateAfterMidiClipChange
void lmms::gui::PianoRollWindow::updateAfterMidiClipChange () private slot
Definition at line 5382 of file PianoRoll.cpp.
References clipRenamed(), and updateStepRecordingIcon().
Referenced by PianoRollWindow(), and setCurrentMidiClip().
updateStepRecordingIcon()
void lmms::gui::PianoRollWindow::updateStepRecordingIcon () private
Definition at line 5520 of file PianoRoll.cpp.
References lmms::embed::getIconPixmap(), m_editor, and lmms::gui::Editor::m_toggleStepRecordingAction.
Referenced by stopStepRecording(), toggleStepRecording(), and updateAfterMidiClipChange().
Member Data Documentation
m_chordComboBox
ComboBox* lmms::gui::PianoRollWindow::m_chordComboBox private
Definition at line 603 of file PianoRoll.h.
Referenced by PianoRollWindow().
m_clearGhostButton
QPushButton* lmms::gui::PianoRollWindow::m_clearGhostButton private
Definition at line 605 of file PianoRoll.h.
Referenced by PianoRollWindow(), and ghostClipSet().
m_editor
PianoRoll* lmms::gui::PianoRollWindow::m_editor private
Definition at line 594 of file PianoRoll.h.
Referenced by PianoRollWindow(), currentMidiClip(), exportMidiClip(), focusInEvent(), hasFocus(), importMidiClip(), isRecording(), loadSettings(), play(), quantization(), record(), recordAccompany(), reset(), saveSettings(), setCurrentMidiClip(), setGhostMidiClip(), stop(), stopRecording(), stopStepRecording(), toggleStepRecording(), and updateStepRecordingIcon().
m_fileToolsButton
QToolButton* lmms::gui::PianoRollWindow::m_fileToolsButton private
Definition at line 596 of file PianoRoll.h.
Referenced by PianoRollWindow(), clipRenamed(), and setCurrentMidiClip().
m_keyComboBox
ComboBox* lmms::gui::PianoRollWindow::m_keyComboBox private
Definition at line 601 of file PianoRoll.h.
Referenced by PianoRollWindow().
m_noteLenComboBox
ComboBox* lmms::gui::PianoRollWindow::m_noteLenComboBox private
Definition at line 600 of file PianoRoll.h.
Referenced by PianoRollWindow().
m_quantizeComboBox
ComboBox* lmms::gui::PianoRollWindow::m_quantizeComboBox private
Definition at line 599 of file PianoRoll.h.
Referenced by PianoRollWindow().
m_scaleComboBox
ComboBox* lmms::gui::PianoRollWindow::m_scaleComboBox private
Definition at line 602 of file PianoRoll.h.
Referenced by PianoRollWindow().
m_snapComboBox
ComboBox* lmms::gui::PianoRollWindow::m_snapComboBox private
Definition at line 604 of file PianoRoll.h.
Referenced by PianoRollWindow().
m_zoomingComboBox
ComboBox* lmms::gui::PianoRollWindow::m_zoomingComboBox private
Definition at line 597 of file PianoRoll.h.
Referenced by PianoRollWindow().
m_zoomingYComboBox
ComboBox* lmms::gui::PianoRollWindow::m_zoomingYComboBox private
Definition at line 598 of file PianoRoll.h.
Referenced by PianoRollWindow().
The documentation for this class was generated from the following files:
include/PianoRoll.h
src/gui/editors/PianoRoll.cpp