LMMS: lmms::detail::BufferViewData< T, DynamicChannelCount > Class Template Reference
lmms::detail::BufferViewData< T, DynamicChannelCount > Class Template Reference
#include <AudioBufferView.h>
Public Member Functions
constexpr BufferViewData ()=default
constexpr BufferViewData (const BufferViewData &)=default
constexpr BufferViewData (T *data, proc_ch_t channels, f_cnt_t frames) noexcept
constexpr auto channels () const noexcept -> proc_ch_t
constexpr auto data () const noexcept -> T *
constexpr auto frames () const noexcept -> f_cnt_t
Protected Attributes
proc_ch_t m_channels = 0
T * m_data = nullptr
f_cnt_t m_frames = 0
Detailed Description
template<typename T>
class lmms::detail::BufferViewData< T, DynamicChannelCount >
Definition at line 79 of file AudioBufferView.h.
Constructor & Destructor Documentation
BufferViewData() [1/3]
template<typename T> lmms::detail::BufferViewData< T, DynamicChannelCount >::BufferViewData () constexpr default
Referenced by BufferViewData().
BufferViewData() [2/3]
template<typename T> lmms::detail::BufferViewData< T, DynamicChannelCount >::BufferViewData (const BufferViewData< T, DynamicChannelCount > &) constexpr default
References BufferViewData().
BufferViewData() [3/3]
template<typename T> lmms::detail::BufferViewData< T, DynamicChannelCount >::BufferViewData (T * data, proc_ch_t channels, f_cnt_t frames) inline constexpr noexcept
Definition at line 85 of file AudioBufferView.h.
References channels(), data(), frames(), and m_data.
Member Function Documentation
channels()
template<typename T> auto lmms::detail::BufferViewData< T, DynamicChannelCount >::channels () const->proc_ch_t inline constexpr noexcept
Definition at line 94 of file AudioBufferView.h.
References m_channels.
Referenced by BufferViewData().
data()
template<typename T> auto lmms::detail::BufferViewData< T, DynamicChannelCount >::data () const->T * inline constexpr noexcept
Definition at line 93 of file AudioBufferView.h.
References m_data.
Referenced by BufferViewData(), lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView(), lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView(), and lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView().
frames()
template<typename T> auto lmms::detail::BufferViewData< T, DynamicChannelCount >::frames () const->f_cnt_t inline constexpr noexcept
Definition at line 95 of file AudioBufferView.h.
References m_frames.
Referenced by BufferViewData(), lmms::InterleavedBufferView< T, channelCount >::InterleavedBufferView(), and lmms::InterleavedBufferView< T, channelCount >::subspan().
Member Data Documentation
m_channels
template<typename T> proc_ch_t lmms::detail::BufferViewData< T, DynamicChannelCount >::m_channels = 0 protected
Definition at line 99 of file AudioBufferView.h.
Referenced by channels().
m_data
template<typename T> T* lmms::detail::BufferViewData< T, DynamicChannelCount >::m_data = nullptr protected
Definition at line 98 of file AudioBufferView.h.
Referenced by BufferViewData(), data(), lmms::InterleavedBufferView< T, channelCount >::dataView(), lmms::InterleavedBufferView< T, channelCount >::empty(), lmms::InterleavedBufferView< T, channelCount >::framePtr(), lmms::InterleavedBufferView< T, channelCount >::framesView(), lmms::InterleavedBufferView< T, channelCount >::framesView(), lmms::InterleavedBufferView< T, channelCount >::sampleFrameAt(), lmms::InterleavedBufferView< T, channelCount >::sampleFrameAt(), lmms::InterleavedBufferView< T, channelCount >::subspan(), lmms::InterleavedBufferView< T, channelCount >::toSampleFrames(), and lmms::InterleavedBufferView< T, channelCount >::toSampleFrames().
m_frames
template<typename T> f_cnt_t lmms::detail::BufferViewData< T, DynamicChannelCount >::m_frames = 0 protected
Definition at line 100 of file AudioBufferView.h.
Referenced by lmms::InterleavedBufferView< T, channelCount >::dataSizeBytes(), lmms::InterleavedBufferView< T, channelCount >::dataView(), lmms::InterleavedBufferView< T, channelCount >::empty(), lmms::InterleavedBufferView< T, channelCount >::framePtr(), frames(), lmms::InterleavedBufferView< T, channelCount >::framesView(), lmms::InterleavedBufferView< T, channelCount >::framesView(), lmms::InterleavedBufferView< T, channelCount >::sampleFrameAt(), lmms::InterleavedBufferView< T, channelCount >::sampleFrameAt(), lmms::InterleavedBufferView< T, channelCount >::subspan(), lmms::InterleavedBufferView< T, channelCount >::toSampleFrames(), and lmms::InterleavedBufferView< T, channelCount >::toSampleFrames().
The documentation for this class was generated from the following file:
include/AudioBufferView.h