LMMS: Creating and managing client threads
Creating and managing client threads
Typedefs
typedef int(* jack_thread_creator_t) (pthread_t *, const pthread_attr_t *, void *(*function) (void *), void *arg)
Functions
int jack_acquire_real_time_scheduling (jack_native_thread_t thread, int priority) JACK_OPTIONAL_WEAK_EXPORT
Attempt to enable realtime scheduling for a thread.
int jack_client_create_thread (jack_client_t *client, jack_native_thread_t *thread, int priority, int realtime, void *(*start_routine)(void *), void *arg) JACK_OPTIONAL_WEAK_EXPORT
Create a thread for JACK or one of its clients.
int jack_client_kill_thread (jack_client_t *client, jack_native_thread_t thread) JACK_OPTIONAL_WEAK_EXPORT
Kill the thread.
int jack_client_max_real_time_priority (jack_client_t *) JACK_OPTIONAL_WEAK_EXPORT
int jack_client_real_time_priority (jack_client_t *) JACK_OPTIONAL_WEAK_EXPORT
int jack_client_stop_thread (jack_client_t *client, jack_native_thread_t thread) JACK_OPTIONAL_WEAK_EXPORT
Stop the thread, waiting for the thread handler to terminate.
int jack_drop_real_time_scheduling (jack_native_thread_t thread) JACK_OPTIONAL_WEAK_EXPORT
Drop realtime scheduling for a thread.
void jack_set_thread_creator (jack_thread_creator_t creator) JACK_OPTIONAL_WEAK_EXPORT
This function can be used in very very specialized cases where it is necessary that client threads created by JACK are created by something other than pthread_create().
Detailed Description
Typedef Documentation
jack_thread_creator_t
typedef int(* jack_thread_creator_t) (pthread_t *, const pthread_attr_t *, void *(*function)(void *), void *arg)
#include <thread.h>
Definition at line 127 of file thread.h.
Function Documentation
jack_acquire_real_time_scheduling()
LIB_EXPORT int jack_acquire_real_time_scheduling (jack_native_thread_t thread, int priority)
#include <thread.h>
Attempt to enable realtime scheduling for a thread.
On some systems that may require special privileges.
Parameters
thread POSIX thread ID.
priority requested thread priority.
Returns
0, if successful; EPERM, if the calling process lacks required realtime privileges; otherwise some other error number.
Definition at line 1741 of file JackAPI.cpp.
References Jack::JackAndroidThread::AcquireRealTimeImp(), Jack::JackEngineControl::fComputation, Jack::JackEngineControl::fConstraint, Jack::JackEngineControl::fPeriod, Jack::GetEngineControl(), and LIB_EXPORT.
jack_client_create_thread()
LIB_EXPORT int jack_client_create_thread (jack_client_t * client, jack_native_thread_t * thread, int priority, int realtime, void *(* start_routine)(void *), void * arg)
#include <thread.h>
Create a thread for JACK or one of its clients.
The thread is created executing start_routine with arg as its sole argument.
Parameters
client the JACK client for whom the thread is being created. May be NULL if the client is being created within the JACK server.
thread place to return POSIX thread ID.
priority thread priority, if realtime.
realtime true for the thread to use realtime scheduling. On some systems that may require special privileges.
start_routine function the thread calls when it starts.
arg parameter passed to the start_routine.
Returns
0, if successful; otherwise some error number.
Definition at line 1749 of file JackAPI.cpp.
References Jack::JackAndroidThread::AcquireRealTimeImp(), Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fComputation, Jack::JackEngineControl::fConstraint, Jack::JackEngineControl::fPeriod, Jack::GetEngineControl(), LIB_EXPORT, and Jack::JackAndroidThread::StartImp().
Referenced by Jack::JackNetMasterManager::JackNetMasterManager(), and TestThread1::TestThread1().
jack_client_kill_thread()
LIB_EXPORT int jack_client_kill_thread (jack_client_t * client, jack_native_thread_t thread)
#include <thread.h>
Kill the thread.
Parameters
thread POSIX thread ID.
Returns
0, if successful; otherwise an error number.
Definition at line 1776 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackAndroidThread::KillImp(), and LIB_EXPORT.
Referenced by Jack::JackNetMasterManager::ShutDown().
jack_client_max_real_time_priority()
LIB_EXPORT int jack_client_max_real_time_priority (jack_client_t * ext_client)
#include <thread.h>
Returns
if JACK is running with realtime scheduling, this returns the maximum priority that a JACK client thread should use if the thread is subject to realtime scheduling. Otherwise returns -1.
Definition at line 1727 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fMaxClientPriority, Jack::JackEngineControl::fRealTime, Jack::GetEngineControl(), jack_error, and LIB_EXPORT.
jack_client_real_time_priority()
LIB_EXPORT int jack_client_real_time_priority (jack_client_t * ext_client)
#include <thread.h>
Returns
if JACK is running with realtime scheduling, this returns the priority that any JACK-created client threads will run at. Otherwise returns -1.
Definition at line 1713 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fClientPriority, Jack::JackEngineControl::fRealTime, Jack::GetEngineControl(), jack_error, and LIB_EXPORT.
jack_client_stop_thread()
LIB_EXPORT int jack_client_stop_thread (jack_client_t * client, jack_native_thread_t thread)
#include <thread.h>
Stop the thread, waiting for the thread handler to terminate.
Parameters
thread POSIX thread ID.
Returns
0, if successful; otherwise an error number.
Definition at line 1770 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), LIB_EXPORT, and Jack::JackAndroidThread::StopImp().
jack_drop_real_time_scheduling()
LIB_EXPORT int jack_drop_real_time_scheduling (jack_native_thread_t thread)
#include <thread.h>
Drop realtime scheduling for a thread.
Parameters
thread POSIX thread ID.
Returns
0, if successful; otherwise an error number.
Definition at line 1765 of file JackAPI.cpp.
References Jack::JackAndroidThread::DropRealTimeImp(), and LIB_EXPORT.
jack_set_thread_creator()
LIB_EXPORT void jack_set_thread_creator (jack_thread_creator_t creator)
#include <thread.h>
This function can be used in very very specialized cases where it is necessary that client threads created by JACK are created by something other than pthread_create().
After it is used, any threads that JACK needs for the client will will be created by calling the function passed to this function.
No normal application/client should consider calling this. The specific case for which it was created involves running win32/x86 plugins under Wine on Linux, where it is necessary that all threads that might call win32 functions are known to Wine.
Set it to NULL to restore thread creation function.
Parameters
creator a function that creates a new thread
Definition at line 1783 of file JackAPI.cpp.
References Jack::JackGlobals::fJackThreadCreator, and LIB_EXPORT.