LMMS: lmms::gui::InstrumentTrackView Class Reference
lmms::gui::InstrumentTrackView Class Reference
#include <InstrumentTrackView.h>
Public Member Functions
InstrumentTrackView (InstrumentTrack *_it, TrackContainerView *tc)
~InstrumentTrackView () override
QMenu * createMixerMenu (QString title, QString newMixerLabel) override
Create a menu for assigning/creating channels for this track.
InstrumentTrackWindow * getInstrumentTrackWindow ()
QMenu * midiMenu ()
InstrumentTrack * model ()
const InstrumentTrack * model () const
Public Member Functions inherited from lmms::gui::TrackView
TrackView (Track *_track, TrackContainerView *tcv)
Create a new track View.
~TrackView () override=default
Track * getTrack ()
const Track * getTrack () const
TrackContentWidget * getTrackContentWidget ()
TrackOperationsWidget * getTrackOperationsWidget ()
QWidget * getTrackSettingsWidget ()
bool isMovingTrack () const
TrackContainerView * trackContainerView ()
virtual void update ()
Update this track View and all its content objects.
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static InstrumentTrackWindow * topLevelInstrumentTrackWindow ()
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void modelChanged () override
Protected Member Functions inherited from lmms::gui::TrackView
void dragEnterEvent (QDragEnterEvent *dee) override
Start a drag event on this track View.
void dropEvent (QDropEvent *de) override
Accept a drop event on this track View.
void loadSettings (const QDomElement &element) override
void modelChanged () override
Register that the model of this track View has changed.
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse move event on this track View.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press event on this track View.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release event on this track View.
QString nodeName () const override
void paintEvent (QPaintEvent *pe) override
Repaint this track View.
void resizeEvent (QResizeEvent *re) override
Resize this track View.
void saveSettings (QDomDocument &doc, QDomElement &element) override
void wheelEvent (QWheelEvent *we) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Slots
void activityIndicatorPressed ()
void activityIndicatorReleased ()
void assignMixerLine (int channelIndex)
Assign a specific mixer Channel for this track.
void createMixerLine ()
Create and assign a new mixer Channel for this track.
void handleConfigChange (QString cls, QString attr, QString value)
void midiConfigChanged ()
void midiInSelected ()
void midiOutSelected ()
void toggleInstrumentWindow (bool _on)
void toggleMidiCCRack ()
Private Member Functions
FadeButton * getActivityIndicator () override
Static Private Member Functions
static QPixmap determinePixmap (InstrumentTrack *instrumentTrack)
Private Attributes
FadeButton * m_activityIndicator
QPoint m_lastPos
std::unique_ptr< MidiCCRackView > m_midiCCRackView
QAction * m_midiInputAction
QMenu * m_midiMenu
QAction * m_midiOutputAction
MixerChannelLcdSpinBox * m_mixerChannelNumber
Knob * m_panningKnob
TrackLabelButton * m_tlb
Knob * m_volumeKnob
InstrumentTrackWindow * m_window
Friends
class InstrumentTrackWindow
Additional Inherited Members
Public Slots inherited from lmms::gui::TrackView
virtual bool close ()
Close this track View.
Detailed Description
Definition at line 45 of file InstrumentTrackView.h.
Constructor & Destructor Documentation
InstrumentTrackView()
lmms::gui::InstrumentTrackView::InstrumentTrackView (InstrumentTrack * _it, TrackContainerView * tc)
Definition at line 59 of file InstrumentTrackView.cpp.
References lmms::gui::TrackView::TrackView(), activityIndicatorPressed(), activityIndicatorReleased(), lmms::Engine::audioEngine(), determinePixmap(), lmms::embed::getIconPixmap(), lmms::gui::TrackView::getTrackSettingsWidget(), handleConfigChange(), lmms::MidiPort::Input, lmms::ConfigManager::inst(), lmms::gui::Knob::LegacyFixedFontSize, m_activityIndicator, m_lastPos, m_midiInputAction, m_midiMenu, m_midiOutputAction, lmms::InstrumentTrack::m_midiPort, m_mixerChannelNumber, m_panningKnob, lmms::InstrumentTrack::m_panningModel, lmms::MidiPort::m_readablePortsMenu, m_tlb, m_volumeKnob, lmms::InstrumentTrack::m_volumeModel, m_window, lmms::MidiPort::m_writablePortsMenu, midiConfigChanged(), midiInSelected(), midiOutSelected(), lmms::MidiPort::Output, lmms::gui::ModelView::setModel(), lmms::gui::Small17, toggleInstrumentWindow(), toggleMidiCCRack(), lmms::gui::TrackView::TrackLabelButton, and lmms::gui::TrackView::update().
~InstrumentTrackView()
lmms::gui::InstrumentTrackView::~InstrumentTrackView () override
Definition at line 173 of file InstrumentTrackView.cpp.
References lmms::InstrumentTrack::m_midiPort, lmms::MidiPort::m_readablePortsMenu, m_window, lmms::MidiPort::m_writablePortsMenu, and model().
Member Function Documentation
activityIndicatorPressed
void lmms::gui::InstrumentTrackView::activityIndicatorPressed () private slot
Definition at line 316 of file InstrumentTrackView.cpp.
References lmms::DefaultKey, lmms::MidiDefaultVelocity, lmms::MidiNoteOn, model(), and lmms::InstrumentTrack::processInEvent().
Referenced by InstrumentTrackView().
activityIndicatorReleased
void lmms::gui::InstrumentTrackView::activityIndicatorReleased () private slot
Definition at line 324 of file InstrumentTrackView.cpp.
References lmms::DefaultKey, lmms::MidiNoteOff, model(), and lmms::InstrumentTrack::processInEvent().
Referenced by InstrumentTrackView().
assignMixerLine
void lmms::gui::InstrumentTrackView::assignMixerLine (int channelIndex) private slot
Assign a specific mixer Channel for this track.
Definition at line 243 of file InstrumentTrackView.cpp.
References lmms::gui::getGUI(), lmms::InstrumentTrack::mixerChannelModel(), lmms::gui::GuiApplication::mixerView(), model(), lmms::gui::MixerView::setCurrentMixerChannel(), and lmms::AutomatableModel::setValue().
Referenced by createMixerLine(), and createMixerMenu().
createMixerLine
void lmms::gui::InstrumentTrackView::createMixerLine () private slot
Create and assign a new mixer Channel for this track.
Definition at line 228 of file InstrumentTrackView.cpp.
References lmms::gui::MixerView::addNewChannel(), assignMixerLine(), lmms::gui::getGUI(), lmms::gui::TrackView::getTrack(), lmms::MixerChannel::m_name, lmms::Engine::mixer(), lmms::Mixer::mixerChannel(), lmms::gui::GuiApplication::mixerView(), and lmms::Track::name().
Referenced by createMixerMenu().
createMixerMenu()
QMenu * lmms::gui::InstrumentTrackView::createMixerMenu (QString title, QString newMixerLabel) override virtual
Create a menu for assigning/creating channels for this track.
Reimplemented from lmms::gui::TrackView.
Definition at line 365 of file InstrumentTrackView.cpp.
References assignMixerLine(), createMixerLine(), i, lmms::MixerChannel::index(), lmms::MixerChannel::m_name, lmms::Engine::mixer(), lmms::Mixer::mixerChannel(), lmms::InstrumentTrack::mixerChannelModel(), model(), lmms::Mixer::numChannels(), and lmms::TypedAutomatableModel< T >::value().
determinePixmap()
QPixmap lmms::gui::InstrumentTrackView::determinePixmap (InstrumentTrack * instrumentTrack) static private
Definition at line 399 of file InstrumentTrackView.cpp.
References lmms::Plugin::descriptor(), lmms::embed::getIconPixmap(), lmms::InstrumentTrack::instrument(), lmms::Plugin::Descriptor::SubPluginFeatures::Key::isValid(), lmms::Plugin::key(), lmms::Plugin::Descriptor::logo, lmms::Plugin::Descriptor::SubPluginFeatures::Key::logo(), and lmms::PixmapLoader::pixmap().
Referenced by InstrumentTrackView().
dragEnterEvent()
void lmms::gui::InstrumentTrackView::dragEnterEvent (QDragEnterEvent * _dee) override protected
Definition at line 279 of file InstrumentTrackView.cpp.
References lmms::gui::TrackView::dragEnterEvent(), and lmms::gui::InstrumentTrackWindow::dragEnterEventGeneric().
dropEvent()
void lmms::gui::InstrumentTrackView::dropEvent (QDropEvent * _de) override protected
Definition at line 291 of file InstrumentTrackView.cpp.
References lmms::gui::InstrumentTrackWindow::dropEvent(), lmms::gui::TrackView::dropEvent(), and getInstrumentTrackWindow().
getActivityIndicator()
FadeButton * lmms::gui::InstrumentTrackView::getActivityIndicator () inline override private virtual
Reimplemented from lmms::gui::TrackView.
Definition at line 118 of file InstrumentTrackView.h.
References m_activityIndicator.
getInstrumentTrackWindow()
InstrumentTrackWindow * lmms::gui::InstrumentTrackView::getInstrumentTrackWindow ()
Definition at line 252 of file InstrumentTrackView.cpp.
References InstrumentTrackWindow, and m_window.
Referenced by dropEvent(), toggleInstrumentWindow(), and lmms::gui::InstrumentTrackWindow::viewInstrumentInDirection().
handleConfigChange
void lmms::gui::InstrumentTrackView::handleConfigChange (QString cls, QString attr, QString value) private slot
Definition at line 262 of file InstrumentTrackView.cpp.
References m_tlb, m_window, and topLevelInstrumentTrackWindow().
Referenced by InstrumentTrackView().
midiConfigChanged
void lmms::gui::InstrumentTrackView::midiConfigChanged () private slot
Definition at line 355 of file InstrumentTrackView.cpp.
References m_midiInputAction, m_midiOutputAction, and model().
Referenced by InstrumentTrackView().
midiInSelected
void lmms::gui::InstrumentTrackView::midiInSelected () private slot
Definition at line 333 of file InstrumentTrackView.cpp.
References m_midiInputAction, lmms::InstrumentTrack::m_midiPort, and model().
Referenced by InstrumentTrackView().
midiMenu()
QMenu * lmms::gui::InstrumentTrackView::midiMenu () inline
Definition at line 66 of file InstrumentTrackView.h.
References m_midiMenu.
midiOutSelected
void lmms::gui::InstrumentTrackView::midiOutSelected () private slot
Definition at line 344 of file InstrumentTrackView.cpp.
References m_midiOutputAction, lmms::InstrumentTrack::m_midiPort, and model().
Referenced by InstrumentTrackView().
model() [1/2]
InstrumentTrack * lmms::gui::InstrumentTrackView::model () inline
Definition at line 54 of file InstrumentTrackView.h.
References lmms::gui::ModelView::castModel().
Referenced by lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow(), ~InstrumentTrackView(), activityIndicatorPressed(), activityIndicatorReleased(), assignMixerLine(), createMixerMenu(), midiConfigChanged(), midiInSelected(), midiOutSelected(), and toggleMidiCCRack().
model() [2/2]
const InstrumentTrack * lmms::gui::InstrumentTrackView::model () const inline
Definition at line 59 of file InstrumentTrackView.h.
References lmms::gui::ModelView::castModel().
modelChanged()
void lmms::gui::InstrumentTrackView::modelChanged () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 272 of file InstrumentTrackView.cpp.
References lmms::gui::ModelView::castModel(), m_mixerChannelNumber, and lmms::gui::TrackView::modelChanged().
toggleInstrumentWindow
void lmms::gui::InstrumentTrackView::toggleInstrumentWindow (bool _on) private slot
Definition at line 300 of file InstrumentTrackView.cpp.
References getInstrumentTrackWindow(), lmms::ConfigManager::inst(), lmms::gui::InstrumentTrackWindow::m_itv, m_tlb, lmms::gui::InstrumentTrackWindow::toggleVisibility(), and topLevelInstrumentTrackWindow().
Referenced by InstrumentTrackView().
toggleMidiCCRack
void lmms::gui::InstrumentTrackView::toggleMidiCCRack () private slot
Definition at line 185 of file InstrumentTrackView.cpp.
References m_midiCCRackView, and model().
Referenced by InstrumentTrackView().
topLevelInstrumentTrackWindow()
InstrumentTrackWindow * lmms::gui::InstrumentTrackView::topLevelInstrumentTrackWindow () static
Definition at line 208 of file InstrumentTrackView.cpp.
References lmms::gui::getGUI(), and InstrumentTrackWindow.
Referenced by handleConfigChange(), lmms::gui::MainWindow::keyPressEvent(), lmms::gui::MainWindow::keyReleaseEvent(), and toggleInstrumentWindow().
Friends And Related Symbol Documentation
InstrumentTrackWindow
friend class InstrumentTrackWindow friend
Definition at line 123 of file InstrumentTrackView.h.
References InstrumentTrackWindow.
Referenced by getInstrumentTrackWindow(), InstrumentTrackWindow, and topLevelInstrumentTrackWindow().
Member Data Documentation
m_activityIndicator
FadeButton* lmms::gui::InstrumentTrackView::m_activityIndicator private
Definition at line 107 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView(), and getActivityIndicator().
m_lastPos
QPoint lmms::gui::InstrumentTrackView::m_lastPos private
Definition at line 116 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView().
m_midiCCRackView
std::unique_ptr<MidiCCRackView> lmms::gui::InstrumentTrackView::m_midiCCRackView private
Definition at line 114 of file InstrumentTrackView.h.
Referenced by toggleMidiCCRack().
m_midiInputAction
QAction* lmms::gui::InstrumentTrackView::m_midiInputAction private
Definition at line 111 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView(), midiConfigChanged(), and midiInSelected().
m_midiMenu
QMenu* lmms::gui::InstrumentTrackView::m_midiMenu private
Definition at line 109 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView(), and midiMenu().
m_midiOutputAction
QAction* lmms::gui::InstrumentTrackView::m_midiOutputAction private
Definition at line 112 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView(), midiConfigChanged(), and midiOutSelected().
m_mixerChannelNumber
MixerChannelLcdSpinBox* lmms::gui::InstrumentTrackView::m_mixerChannelNumber private
Definition at line 104 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView(), and modelChanged().
m_panningKnob
Knob* lmms::gui::InstrumentTrackView::m_panningKnob private
Definition at line 106 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView().
m_tlb
TrackLabelButton* lmms::gui::InstrumentTrackView::m_tlb private
Definition at line 103 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView(), handleConfigChange(), toggleInstrumentWindow(), and lmms::gui::InstrumentTrackWindow::viewInstrumentInDirection().
m_volumeKnob
Knob* lmms::gui::InstrumentTrackView::m_volumeKnob private
Definition at line 105 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView().
m_window
InstrumentTrackWindow* lmms::gui::InstrumentTrackView::m_window private
Definition at line 100 of file InstrumentTrackView.h.
Referenced by InstrumentTrackView(), ~InstrumentTrackView(), getInstrumentTrackWindow(), and handleConfigChange().
The documentation for this class was generated from the following files:
include/InstrumentTrackView.h
src/gui/tracks/InstrumentTrackView.cpp