LMMS: lmms::AudioEngine::RequestChangesGuard Class Reference
lmms::AudioEngine::RequestChangesGuard Class Reference
RAII helper for requestChangesInModel.
#include <AudioEngine.h>
Public Member Functions
RequestChangesGuard ()
RequestChangesGuard (const RequestChangesGuard &)=delete
RequestChangesGuard (RequestChangesGuard &&other)
~RequestChangesGuard ()
RequestChangesGuard & operator= (const RequestChangesGuard &)=delete
Private Member Functions
RequestChangesGuard (AudioEngine *audioEngine)
Private Attributes
AudioEngine * m_audioEngine
Friends
class AudioEngine
Detailed Description
RAII helper for requestChangesInModel.
Used by AudioEngine::requestChangesGuard.
Definition at line 72 of file AudioEngine.h.
Constructor & Destructor Documentation
RequestChangesGuard() [1/4]
lmms::AudioEngine::RequestChangesGuard::RequestChangesGuard (AudioEngine * audioEngine) inline private
Definition at line 76 of file AudioEngine.h.
References AudioEngine, and m_audioEngine.
Referenced by RequestChangesGuard(), RequestChangesGuard(), and operator=().
RequestChangesGuard() [2/4]
lmms::AudioEngine::RequestChangesGuard::RequestChangesGuard () inline
Definition at line 83 of file AudioEngine.h.
References m_audioEngine.
RequestChangesGuard() [3/4]
lmms::AudioEngine::RequestChangesGuard::RequestChangesGuard (RequestChangesGuard && other) inline
Definition at line 88 of file AudioEngine.h.
References RequestChangesGuard(), and m_audioEngine.
RequestChangesGuard() [4/4]
lmms::AudioEngine::RequestChangesGuard::RequestChangesGuard (const RequestChangesGuard &) delete
References RequestChangesGuard().
~RequestChangesGuard()
lmms::AudioEngine::RequestChangesGuard::~RequestChangesGuard () inline
Definition at line 98 of file AudioEngine.h.
References m_audioEngine.
Member Function Documentation
operator=()
RequestChangesGuard & lmms::AudioEngine::RequestChangesGuard::operator= (const RequestChangesGuard &) delete
References RequestChangesGuard().
Friends And Related Symbol Documentation
AudioEngine
friend class AudioEngine friend
Definition at line 73 of file AudioEngine.h.
References AudioEngine.
Referenced by RequestChangesGuard(), and AudioEngine.
Member Data Documentation
m_audioEngine
AudioEngine* lmms::AudioEngine::RequestChangesGuard::m_audioEngine private
Definition at line 105 of file AudioEngine.h.
Referenced by RequestChangesGuard(), RequestChangesGuard(), RequestChangesGuard(), and ~RequestChangesGuard().
The documentation for this class was generated from the following file:
include/AudioEngine.h