LMMS: lmms::gui::Draggable Class Reference
lmms::gui::Draggable Class Reference
A pixmap that can be dragged from one location to another to control a FloatModel.
#include <Draggable.h>
Public Types
enum class DirectionOfManipulation
Public Types inherited from lmms::gui::FloatModelEditorBase
enum class DirectionOfManipulation {
Vertical ,
Horizontal
}
Public Member Functions
Draggable (DirectionOfManipulation directionOfManipulation, FloatModel *floatModel, const QPixmap &pixmap, int pointA, int pointB, QWidget *parent=nullptr)
void setDefaultValPixmap (const QPixmap &pixmap, float value=0.f)
void setPixmap (const QPixmap &pixmap)
QSize sizeHint () const override
Public Member Functions inherited from lmms::gui::FloatModelEditorBase
FloatModelEditorBase (const FloatModelEditorBase &other)=delete
FloatModelEditorBase (DirectionOfManipulation directionOfManipulation=DirectionOfManipulation::Vertical, QWidget *_parent=nullptr, const QString &_name=QString())
default ctor
void setHintText (const QString &txt_before, const QString &txt_after)
Public Member Functions inherited from lmms::gui::TypedModelView< FloatModel >
TypedModelView (Model *model, QWidget *_this)
FloatModel * model ()
const FloatModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Slots
void handleMovement ()
Protected Member Functions
void mouseMoveEvent (QMouseEvent *me) override
void paintEvent (QPaintEvent *event) override
Protected Member Functions inherited from lmms::gui::FloatModelEditorBase
void contextMenuEvent (QContextMenuEvent *me) override
virtual QString displayValue () const
void doConnections () override
void dragEnterEvent (QDragEnterEvent *dee) override
void dropEvent (QDropEvent *de) override
void enterEvent (QEvent *event) override
void focusOutEvent (QFocusEvent *fe) override
virtual float getValue (const QPoint &p)
void leaveEvent (QEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
float pageSize () const
void paintEvent (QPaintEvent *me) override
void setPosition (const QPoint &p)
void showTextFloat (int msecBeforeDisplay, int msecDisplayTime)
void wheelEvent (QWheelEvent *me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void modelChanged ()
QWidget * widget ()
Private Attributes
QPixmap m_defaultValPixmap
float m_defaultValue
bool m_hasDefaultValPixmap
QPixmap m_pixmap
float m_pointA
float m_pointB
Additional Inherited Members
Signals inherited from lmms::gui::FloatModelEditorBase
void sliderMoved (float value)
void sliderPressed ()
void sliderReleased ()
Protected Attributes inherited from lmms::gui::FloatModelEditorBase
bool m_buttonPressed
DirectionOfManipulation m_directionOfManipulation
QPoint m_lastMousePos
mouse position in last mouseMoveEvent
float m_leftOver
BoolModel m_volumeKnob
FloatModel m_volumeRatio
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Static Protected Attributes inherited from lmms::gui::FloatModelEditorBase
static SimpleTextFloat * s_textFloat = nullptr
Detailed Description
A pixmap that can be dragged from one location to another to control a FloatModel.
Definition at line 36 of file Draggable.h.
Member Enumeration Documentation
DirectionOfManipulation
enum class lmms::gui::FloatModelEditorBase::DirectionOfManipulation strong
Definition at line 50 of file FloatModelEditorBase.h.
Constructor & Destructor Documentation
Draggable()
lmms::gui::Draggable::Draggable (DirectionOfManipulation directionOfManipulation, FloatModel * floatModel, const QPixmap & pixmap, int pointA, int pointB, QWidget * parent = nullptr)
Parameters
directionOfManipulation Direction the user can drag the control
floatModel Pointer to the FloatModel this draggable modifies
pixmap The pixmap shown for this handle
pointA Starting pixel position (Y if vertical, X if horizontal)
pointB Ending pixel position (Y if vertical, X if horizontal)
parent Parent QWidget
Definition at line 36 of file Draggable.cpp.
References lmms::gui::FloatModelEditorBase::FloatModelEditorBase(), lmms::Model::dataChanged(), handleMovement(), m_defaultValPixmap, m_defaultValue, m_hasDefaultValPixmap, m_pixmap, m_pointA, m_pointB, lmms::gui::TypedModelView< FloatModel >::model(), and lmms::gui::AutomatableModelView::setModel().
Member Function Documentation
handleMovement
void lmms::gui::Draggable::handleMovement () protected slot
Definition at line 115 of file Draggable.cpp.
References lmms::gui::FloatModelEditorBase::m_directionOfManipulation, m_pixmap, m_pointA, m_pointB, lmms::gui::TypedModelView< FloatModel >::model(), and lmms::gui::AutomatableModelView::value().
Referenced by Draggable().
mouseMoveEvent()
void lmms::gui::Draggable::mouseMoveEvent (QMouseEvent * me) override protected
Definition at line 85 of file Draggable.cpp.
References lmms::gui::FloatModelEditorBase::displayValue(), lmms::gui::FloatModelEditorBase::m_buttonPressed, lmms::gui::FloatModelEditorBase::m_directionOfManipulation, lmms::gui::FloatModelEditorBase::m_lastMousePos, m_pointA, m_pointB, lmms::TypedAutomatableModel< T >::maxValue(), lmms::TypedAutomatableModel< T >::minValue(), lmms::gui::TypedModelView< FloatModel >::model(), lmms::gui::FloatModelEditorBase::s_textFloat, lmms::AutomatableModel::setValue(), lmms::gui::FloatModelEditorBase::sliderMoved(), and lmms::gui::AutomatableModelView::value().
paintEvent()
void lmms::gui::Draggable::paintEvent (QPaintEvent * event) override protected
Definition at line 70 of file Draggable.cpp.
References m_defaultValPixmap, m_defaultValue, m_hasDefaultValPixmap, m_pixmap, lmms::gui::TypedModelView< FloatModel >::model(), and lmms::gui::AutomatableModelView::value().
setDefaultValPixmap()
void lmms::gui::Draggable::setDefaultValPixmap (const QPixmap & pixmap, float value = 0.f)
Definition at line 62 of file Draggable.cpp.
References m_defaultValPixmap, m_defaultValue, m_hasDefaultValPixmap, and lmms::gui::AutomatableModelView::value().
setPixmap()
void lmms::gui::Draggable::setPixmap (const QPixmap & pixmap)
Definition at line 56 of file Draggable.cpp.
References m_pixmap.
sizeHint()
QSize lmms::gui::Draggable::sizeHint () const override
Definition at line 51 of file Draggable.cpp.
References m_pixmap.
Member Data Documentation
m_defaultValPixmap
QPixmap lmms::gui::Draggable::m_defaultValPixmap private
Definition at line 67 of file Draggable.h.
Referenced by Draggable(), paintEvent(), and setDefaultValPixmap().
m_defaultValue
float lmms::gui::Draggable::m_defaultValue private
Definition at line 70 of file Draggable.h.
Referenced by Draggable(), paintEvent(), and setDefaultValPixmap().
m_hasDefaultValPixmap
bool lmms::gui::Draggable::m_hasDefaultValPixmap private
Definition at line 71 of file Draggable.h.
Referenced by Draggable(), paintEvent(), and setDefaultValPixmap().
m_pixmap
QPixmap lmms::gui::Draggable::m_pixmap private
Definition at line 66 of file Draggable.h.
Referenced by Draggable(), handleMovement(), paintEvent(), setPixmap(), and sizeHint().
m_pointA
float lmms::gui::Draggable::m_pointA private
Definition at line 68 of file Draggable.h.
Referenced by Draggable(), handleMovement(), and mouseMoveEvent().
m_pointB
float lmms::gui::Draggable::m_pointB private
Definition at line 69 of file Draggable.h.
Referenced by Draggable(), handleMovement(), and mouseMoveEvent().
The documentation for this class was generated from the following files:
include/Draggable.h
src/gui/widgets/Draggable.cpp