LMMS: src/core/PluginFactory.cpp File Reference
PluginFactory.cpp File Reference
#include "PluginFactory.h"
#include <QCoreApplication>
#include <QDebug>
#include <QDir>
#include <QLibrary>
#include <QRegularExpression>
#include <memory>
#include "lmmsconfig.h"
#include "ConfigManager.h"
#include "Plugin.h"
Namespaces
namespace lmms
Functions
PluginFactory * lmms::getPluginFactory ()
QStringList lmms::nameFilters ("lib*.so")
qint64 qHash (const QFileInfo &fi)
Function Documentation
qHash()
qint64 qHash (const QFileInfo & fi)
Definition at line 39 of file PluginFactory.cpp.
References qHash().
Referenced by lmms::SampleThumbnail::Hash::operator()(), and qHash().