LMMS: lmms::SampleClip Class Reference
lmms::SampleClip Class Reference
#include <SampleClip.h>
Public Slots
void playbackPositionChanged ()
void setSampleFile (const QString &sf)
void toggleRecord ()
void updateLength ()
void updateTrackClips ()
Public Slots inherited from lmms::Clip
void toggleMute ()
Mutes this Clip.
Signals
void sampleChanged ()
void wasReversed ()
Signals inherited from lmms::Clip
void colorChanged ()
void destroyedClip ()
void lengthChanged ()
void positionChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
SampleClip (Track *track)
SampleClip (Track *track, Sample sample, bool isPlaying)
~SampleClip () override
void changeLength (const TimePos &_length) override
Change the length of this Clip.
SampleClip * clone () override
Creates a copy of this clip.
gui::ClipView * createView (gui::TrackView *_tv) override
bool hasSampleFileLoaded (const QString &filename) const
bool isPlaying () const
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
SampleClip & operator= (const SampleClip &that)=delete
Sample & sample ()
const QString & sampleFile () const
TimePos sampleLength () const
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
void setIsPlaying (bool isPlaying)
void setSampleBuffer (std::shared_ptr< const SampleBuffer > sb)
void setSamplePlayLength (f_cnt_t length)
void setSampleStartFrame (f_cnt_t startFrame)
Public Member Functions inherited from lmms::Clip
Clip (Track *track)
Create a new Clip.
~Clip () override
Destroy a Clip.
auto color () const -> const std::optional< QColor > &
QString displayName () const override
TimePos endPosition () const
bool getAutoResize () const
bool getSelectViewOnCreate ()
Track * getTrack () const
bool hasTrackContainer () const
bool isInPattern () const
const TimePos & length () const
bool manuallyResizable () const
virtual void movePosition (const TimePos &pos)
Move this Clip's position in time.
const QString & name () const
void selectViewOnCreate (bool select)
void setAutoResize (const bool r)
Set whether a clip has been resized yet by the user or the knife tool.
void setColor (const std::optional< QColor > &color)
void setName (const QString &name)
void setStartTimeOffset (const TimePos &startTimeOffset)
const TimePos & startPosition () const
TimePos startTimeOffset () const
virtual void updateLength ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Member Functions
SampleClip (const SampleClip &orig)
Protected Member Functions inherited from lmms::Clip
Clip (const Clip &other)
Copy a Clip.
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Member Functions
mapPropertyFromModel (bool, isRecord, setRecord, m_recordModel)
Private Attributes
bool m_isPlaying
BoolModel m_recordModel
Sample m_sample
Friends
class gui::SampleClipView
Additional Inherited Members
Static Public Member Functions inherited from lmms::Clip
static bool comparePosition (const Clip *a, const Clip *b)
Returns true if and only if a->startPosition() < b->startPosition().
static void copyStateTo (Clip *src, Clip *dst)
Copies the state of a Clip to another Clip.
Detailed Description
Definition at line 45 of file SampleClip.h.
Constructor & Destructor Documentation
SampleClip() [1/3]
lmms::SampleClip::SampleClip (Track * track, Sample sample, bool isPlaying)
Definition at line 39 of file SampleClip.cpp.
References lmms::Clip::Clip(), lmms::Model::dataChanged(), lmms::Engine::getSong(), lmms::Clip::getTrack(), isPlaying(), m_isPlaying, m_sample, playbackPositionChanged(), lmms::Clip::positionChanged(), lmms::JournallingObject::restoreJournallingState(), sample(), lmms::JournallingObject::saveJournallingState(), setSampleFile(), updateLength(), and updateTrackClips().
Referenced by SampleClip(), SampleClip(), clone(), and operator=().
SampleClip() [2/3]
lmms::SampleClip::SampleClip (Track * track)
Definition at line 72 of file SampleClip.cpp.
References SampleClip().
~SampleClip()
lmms::SampleClip::~SampleClip () override
Definition at line 113 of file SampleClip.cpp.
References lmms::Clip::getTrack().
SampleClip() [3/3]
lmms::SampleClip::SampleClip (const SampleClip & orig) protected
Definition at line 77 of file SampleClip.cpp.
References lmms::Clip::Clip(), SampleClip(), lmms::Model::dataChanged(), lmms::Engine::getSong(), lmms::Clip::getTrack(), m_isPlaying, m_sample, playbackPositionChanged(), lmms::Clip::positionChanged(), lmms::JournallingObject::restoreJournallingState(), lmms::JournallingObject::saveJournallingState(), setSampleFile(), updateLength(), and updateTrackClips().
Member Function Documentation
changeLength()
void lmms::SampleClip::changeLength (const TimePos & length) override virtual
Change the length of this Clip.
If the clip's length has changed, update it. We also add a journal entry for undo and update the display.
Parameters
_length The new length of the clip.
Reimplemented from lmms::Clip.
Definition at line 125 of file SampleClip.cpp.
References lmms::Clip::changeLength().
Referenced by loadSettings(), setSampleFile(), and updateLength().
clone()
SampleClip * lmms::SampleClip::clone () inline override virtual
Creates a copy of this clip.
Returns
pointer to the new clip object
Implements lmms::Clip.
Definition at line 82 of file SampleClip.h.
References SampleClip().
createView()
gui::ClipView * lmms::SampleClip::createView (gui::TrackView * _tv) override virtual
Implements lmms::Clip.
Definition at line 347 of file SampleClip.cpp.
hasSampleFileLoaded()
bool lmms::SampleClip::hasSampleFileLoaded (const QString & filename) const
Definition at line 137 of file SampleClip.cpp.
References m_sample.
isPlaying()
bool lmms::SampleClip::isPlaying () const
Definition at line 210 of file SampleClip.cpp.
References m_isPlaying.
Referenced by SampleClip(), mapPropertyFromModel(), lmms::SampleTrack::play(), and setIsPlaying().
loadSettings()
void lmms::SampleClip::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 303 of file SampleClip.cpp.
References lmms::Engine::audioEngine(), changeLength(), lmms::Song::collectError(), lmms::gui::SampleLoader::createBufferFromBase64(), lmms::Engine::getSong(), m_sample, lmms::Clip::movePosition(), lmms::AudioEngine::outputSampleRate(), sampleFile(), lmms::Clip::setAutoResize(), lmms::Clip::setColor(), setSampleFile(), lmms::Clip::setStartTimeOffset(), lmms::PathUtil::toAbsolute(), and wasReversed().
mapPropertyFromModel()
lmms::SampleClip::mapPropertyFromModel (bool , isRecord , setRecord , m_recordModel) private
References isPlaying(), m_recordModel, and sample().
nodeName()
QString lmms::SampleClip::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 62 of file SampleClip.h.
operator=()
SampleClip & lmms::SampleClip::operator= (const SampleClip & that) delete
References SampleClip().
playbackPositionChanged
void lmms::SampleClip::playbackPositionChanged () slot
Definition at line 188 of file SampleClip.cpp.
References lmms::Engine::audioEngine(), lmms::Clip::getTrack(), lmms::AudioEngine::removePlayHandlesOfTypes(), lmms::PlayHandle::SamplePlayHandle, and lmms::SampleTrack::setPlayingClips().
Referenced by SampleClip(), SampleClip(), and setSampleFile().
sample()
Sample & lmms::SampleClip::sample () inline
Definition at line 67 of file SampleClip.h.
References m_sample.
Referenced by SampleClip(), mapPropertyFromModel(), and lmms::gui::AutomationEditor::setGhostSample().
sampleChanged
void lmms::SampleClip::sampleChanged () signal
Referenced by setSampleBuffer(), setSampleFile(), and updateLength().
sampleFile()
const QString & lmms::SampleClip::sampleFile () const
Definition at line 132 of file SampleClip.cpp.
References m_sample.
Referenced by loadSettings(), and saveSettings().
sampleLength()
TimePos lmms::SampleClip::sampleLength () const
Definition at line 243 of file SampleClip.cpp.
References lmms::Engine::framesPerTick(), and m_sample.
Referenced by updateLength().
saveSettings()
void lmms::SampleClip::saveSettings (QDomDocument & _doc, QDomElement & _parent) override virtual
Implements lmms::SerializingObject.
Definition at line 267 of file SampleClip.cpp.
References lmms::Clip::color(), lmms::Clip::getAutoResize(), lmms::Clip::length(), m_sample, sampleFile(), lmms::Clip::startPosition(), and lmms::Clip::startTimeOffset().
setIsPlaying()
void lmms::SampleClip::setIsPlaying (bool isPlaying)
Definition at line 218 of file SampleClip.cpp.
References isPlaying(), and m_isPlaying.
Referenced by lmms::SampleTrack::setPlayingClips().
setSampleBuffer()
void lmms::SampleClip::setSampleBuffer (std::shared_ptr< const SampleBuffer > sb)
Definition at line 142 of file SampleClip.cpp.
References lmms::Engine::audioEngine(), lmms::Engine::getSong(), m_sample, lmms::AudioEngine::requestChangesGuard(), sampleChanged(), lmms::Song::setModified(), and updateLength().
setSampleFile
void lmms::SampleClip::setSampleFile (const QString & sf) slot
Definition at line 155 of file SampleClip.cpp.
References changeLength(), lmms::gui::SampleLoader::createBufferFromFile(), lmms::DefaultTicksPerBar, lmms::Engine::getSong(), lmms::Song::getTimeSigModel(), m_sample, playbackPositionChanged(), sampleChanged(), lmms::Clip::setStartTimeOffset(), and updateLength().
Referenced by SampleClip(), SampleClip(), loadSettings(), and lmms::gui::FileBrowserTreeWidget::openInNewSampleTrack().
setSamplePlayLength()
void lmms::SampleClip::setSamplePlayLength (f_cnt_t length)
Definition at line 259 of file SampleClip.cpp.
References lmms::Clip::length(), and m_sample.
setSampleStartFrame()
void lmms::SampleClip::setSampleStartFrame (f_cnt_t startFrame)
Definition at line 251 of file SampleClip.cpp.
References m_sample.
toggleRecord
void lmms::SampleClip::toggleRecord () slot
Definition at line 179 of file SampleClip.cpp.
References lmms::Model::dataChanged(), and m_recordModel.
updateLength
void lmms::SampleClip::updateLength () slot
Definition at line 226 of file SampleClip.cpp.
References changeLength(), lmms::Clip::getAutoResize(), lmms::Engine::getSong(), sampleChanged(), sampleLength(), lmms::Song::setModified(), and lmms::Clip::setStartTimeOffset().
Referenced by SampleClip(), SampleClip(), setSampleBuffer(), and setSampleFile().
updateTrackClips
void lmms::SampleClip::updateTrackClips () slot
Definition at line 198 of file SampleClip.cpp.
References lmms::Clip::getTrack().
Referenced by SampleClip(), and SampleClip().
wasReversed
void lmms::SampleClip::wasReversed () signal
Referenced by loadSettings().
Friends And Related Symbol Documentation
gui::SampleClipView
friend class gui::SampleClipView friend
Definition at line 102 of file SampleClip.h.
Member Data Documentation
m_isPlaying
bool lmms::SampleClip::m_isPlaying private
Definition at line 100 of file SampleClip.h.
Referenced by SampleClip(), SampleClip(), isPlaying(), and setIsPlaying().
m_recordModel
BoolModel lmms::SampleClip::m_recordModel private
Definition at line 99 of file SampleClip.h.
Referenced by mapPropertyFromModel(), and toggleRecord().
m_sample
Sample lmms::SampleClip::m_sample private
Definition at line 98 of file SampleClip.h.
Referenced by SampleClip(), SampleClip(), hasSampleFileLoaded(), loadSettings(), sample(), sampleFile(), sampleLength(), saveSettings(), setSampleBuffer(), setSampleFile(), setSamplePlayLength(), and setSampleStartFrame().
The documentation for this class was generated from the following files:
include/SampleClip.h
src/core/SampleClip.cpp