LMMS: Jack::NetFloatAudioBuffer Class Reference
Jack::NetFloatAudioBuffer Class Reference
#include <JackNetTool.h>
Public Member Functions
NetFloatAudioBuffer (session_params_t *params, uint32_t nports, char *net_buffer)
virtual ~NetFloatAudioBuffer ()
float GetCycleDuration ()
size_t GetCycleSize ()
int GetNumPackets (int active_ports)
int RenderFromNetwork (int cycle, int sub_cycle, uint32_t port_num)
int RenderToNetwork (int sub_cycle, uint32_t port_num)
Public Member Functions inherited from Jack::NetAudioBuffer
NetAudioBuffer (session_params_t *params, uint32_t nports, char *net_buffer)
virtual ~NetAudioBuffer ()
virtual void ActivePortsFromNetwork (char *net_buffer, uint32_t port_num)
virtual int ActivePortsToNetwork (char *net_buffer)
virtual sample_t * GetBuffer (int index)
bool GetConnected (int port_index)
virtual int RenderFromJackPorts (int nframes)
virtual void RenderToJackPorts (int nframes)
virtual void SetBuffer (int index, sample_t *buffer)
void SetConnected (int port_index, bool state)
Private Member Functions
void RenderFromNetwork (char *net_buffer, int active_port, int sub_cycle)
void RenderToNetwork (char *net_buffer, int active_port, int sub_cycle)
void UpdateParams (int active_ports)
Private Attributes
int fPacketSize
Additional Inherited Members
Protected Member Functions inherited from Jack::NetAudioBuffer
int CheckPacket (int cycle, int sub_cycle)
void Cleanup ()
void NextCycle ()
Protected Attributes inherited from Jack::NetAudioBuffer
bool * fConnectedPorts
size_t fCycleBytesSize
float fCycleDuration
int fLastSubCycle
char * fNetBuffer
int fNPorts
int fNumPackets
jack_nframes_t fPeriodSize
sample_t ** fPortBuffer
size_t fSubPeriodBytesSize
jack_nframes_t fSubPeriodSize
Detailed Description
Definition at line 337 of file JackNetTool.h.
Constructor & Destructor Documentation
NetFloatAudioBuffer()
Jack::NetFloatAudioBuffer::NetFloatAudioBuffer (session_params_t * params, uint32_t nports, char * net_buffer)
Definition at line 329 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::NetAudioBuffer(), Jack::NetAudioBuffer::fCycleBytesSize, Jack::NetAudioBuffer::fCycleDuration, Jack::NetAudioBuffer::fLastSubCycle, Jack::_session_params::fMtu, fPacketSize, Jack::_session_params::fPeriodSize, Jack::NetAudioBuffer::fPeriodSize, Jack::_session_params::fReturnAudioChannels, Jack::_session_params::fSampleRate, Jack::_session_params::fSendAudioChannels, Jack::NetAudioBuffer::fSubPeriodSize, max, PACKET_AVAILABLE_SIZE, and UpdateParams().
~NetFloatAudioBuffer()
Jack::NetFloatAudioBuffer::~NetFloatAudioBuffer () virtual
Definition at line 343 of file JackNetTool.cpp.
Member Function Documentation
GetCycleDuration()
float Jack::NetFloatAudioBuffer::GetCycleDuration () virtual
Implements Jack::NetAudioBuffer.
Definition at line 353 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fCycleDuration.
GetCycleSize()
size_t Jack::NetFloatAudioBuffer::GetCycleSize () virtual
Implements Jack::NetAudioBuffer.
Definition at line 347 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fCycleBytesSize.
GetNumPackets()
int Jack::NetFloatAudioBuffer::GetNumPackets (int active_ports) virtual
Implements Jack::NetAudioBuffer.
Definition at line 371 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fNumPackets, and UpdateParams().
RenderFromNetwork() [1/2]
void Jack::NetFloatAudioBuffer::RenderFromNetwork (char * net_buffer, int active_port, int sub_cycle) private
Definition at line 463 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fPortBuffer, Jack::NetAudioBuffer::fSubPeriodBytesSize, and Jack::NetAudioBuffer::fSubPeriodSize.
Referenced by RenderFromNetwork().
RenderFromNetwork() [2/2]
int Jack::NetFloatAudioBuffer::RenderFromNetwork (int cycle, int sub_cycle, uint32_t port_num) virtual
Implements Jack::NetAudioBuffer.
Definition at line 384 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::CheckPacket(), Jack::NetAudioBuffer::Cleanup(), Jack::NetAudioBuffer::fNetBuffer, Jack::NetAudioBuffer::fSubPeriodBytesSize, RenderFromNetwork(), and UpdateParams().
RenderToNetwork() [1/2]
void Jack::NetFloatAudioBuffer::RenderToNetwork (char * net_buffer, int active_port, int sub_cycle) private
Definition at line 470 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fPortBuffer, Jack::NetAudioBuffer::fSubPeriodBytesSize, and Jack::NetAudioBuffer::fSubPeriodSize.
Referenced by RenderToNetwork().
RenderToNetwork() [2/2]
int Jack::NetFloatAudioBuffer::RenderToNetwork (int sub_cycle, uint32_t port_num) virtual
Implements Jack::NetAudioBuffer.
Definition at line 404 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fNetBuffer, Jack::NetAudioBuffer::fNPorts, Jack::NetAudioBuffer::fPortBuffer, Jack::NetAudioBuffer::fSubPeriodBytesSize, and RenderToNetwork().
UpdateParams()
void Jack::NetFloatAudioBuffer::UpdateParams (int active_ports) private
Definition at line 358 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fNumPackets, fPacketSize, Jack::NetAudioBuffer::fPeriodSize, Jack::NetAudioBuffer::fSubPeriodBytesSize, and Jack::NetAudioBuffer::fSubPeriodSize.
Referenced by NetFloatAudioBuffer(), GetNumPackets(), and RenderFromNetwork().
Member Data Documentation
fPacketSize
int Jack::NetFloatAudioBuffer::fPacketSize private
Definition at line 342 of file JackNetTool.h.
Referenced by NetFloatAudioBuffer(), and UpdateParams().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackNetTool.h
src/3rdparty/jack2/common/JackNetTool.cpp