LMMS: Jack::JackMMCSS Class Reference
Jack::JackMMCSS Class Reference
MMCSS services.
#include <JackMMCSS.h>
Public Member Functions
JackMMCSS ()
~JackMMCSS ()
Static Public Member Functions
static int MMCSSAcquireRealTime (jack_native_thread_t thread, int priority)
static int MMCSSDropRealTime (jack_native_thread_t thread)
Static Private Attributes
static JACK_HANDLE fAvrtDll
static avSetMmThreadCharacteristics ffMMCSSFun1 = NULL
static avSetMmThreadPriority ffMMCSSFun2 = NULL
static avRevertMmThreadCharacteristics ffMMCSSFun3 = NULL
static std::map< jack_native_thread_t, HANDLE > fHandleTable
Detailed Description
MMCSS services.
Definition at line 53 of file JackMMCSS.h.
Constructor & Destructor Documentation
JackMMCSS()
Jack::JackMMCSS::JackMMCSS ()
Definition at line 35 of file JackMMCSS.cpp.
References fAvrtDll, ffMMCSSFun1, ffMMCSSFun2, ffMMCSSFun3, GetJackProc, and LoadJackModule.
Referenced by Jack::JackWinThread::JackWinThread().
~JackMMCSS()
Jack::JackMMCSS::~JackMMCSS ()
Definition at line 46 of file JackMMCSS.cpp.
Member Function Documentation
MMCSSAcquireRealTime()
int Jack::JackMMCSS::MMCSSAcquireRealTime (jack_native_thread_t thread, int priority) static
Definition at line 49 of file JackMMCSS.cpp.
References BASE_REALTIME_PRIORITY, ffMMCSSFun1, ffMMCSSFun2, fHandleTable, jack_error, and jack_log().
Referenced by Jack::JackWinThread::AcquireRealTimeImp().
MMCSSDropRealTime()
int Jack::JackMMCSS::MMCSSDropRealTime (jack_native_thread_t thread) static
Definition at line 72 of file JackMMCSS.cpp.
References ffMMCSSFun3, fHandleTable, jack_error, and jack_log().
Referenced by Jack::JackWinThread::DropRealTimeImp().
Member Data Documentation
fAvrtDll
JACK_HANDLE Jack::JackMMCSS::fAvrtDll static private
Definition at line 58 of file JackMMCSS.h.
Referenced by JackMMCSS().
ffMMCSSFun1
avSetMmThreadCharacteristics Jack::JackMMCSS::ffMMCSSFun1 = NULL static private
Definition at line 59 of file JackMMCSS.h.
Referenced by JackMMCSS(), and MMCSSAcquireRealTime().
ffMMCSSFun2
avSetMmThreadPriority Jack::JackMMCSS::ffMMCSSFun2 = NULL static private
Definition at line 60 of file JackMMCSS.h.
Referenced by JackMMCSS(), and MMCSSAcquireRealTime().
ffMMCSSFun3
avRevertMmThreadCharacteristics Jack::JackMMCSS::ffMMCSSFun3 = NULL static private
Definition at line 61 of file JackMMCSS.h.
Referenced by JackMMCSS(), and MMCSSDropRealTime().
fHandleTable
std::map< jack_native_thread_t, HANDLE > Jack::JackMMCSS::fHandleTable static private
Definition at line 62 of file JackMMCSS.h.
Referenced by MMCSSAcquireRealTime(), and MMCSSDropRealTime().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackMMCSS.h
src/3rdparty/jack2/windows/JackMMCSS.cpp