LMMS: ringbuffer_t< T > Class Template Reference
ringbuffer_t< T > Class Template Reference
TODO: specialization for only one reader.
#include <ringbuffer.h>
Classes
class std_copy
Standard copier for write_func Works for all T that are copyable (e.g.
Public Types
using value_type = T
Public Member Functions
ringbuffer_t (const ringbuffer_t &)=delete
ringbuffer_t (ringbuffer_t &&other)
move ctor.
ringbuffer_t (std::size_t sz)
allocating constructor
~ringbuffer_t ()
std::size_t maximum_eventual_write_space () const
size that is guaranteed to be writable once all readers are up to date
bool mlock ()
try to lock the data block using the syscall mlock
bool munlock ()
try to unlock the data block using the syscall munlock
void touch ()
overwrite the whole buffer with zeros this prevents page faults only allowed on startup (this is not fully checked!)
std::size_t write (const T *src, size_t cnt)
writes max(cnt, write_space) of src into the buffer overwrite this function in your subclass if you do not use the standard copier std_copy
template<class Func>
std::size_t write_func (Func &f, size_t cnt)
Public Member Functions inherited from ringbuffer_base
std::size_t write_space () const
returns number of objects that can be written at least
Private Attributes
T *const buf
Friends
template<class _T>
class ringbuffer_reader_t
Additional Inherited Members
Protected Member Functions inherited from ringbuffer_base
void init_atomic_variables ()
void init_variables_for_write (std::size_t cnt, std::size_t &w, std::size_t &to_write, std::size_t &n1, std::size_t &n2)
bool mlock (const void *const buf, std::size_t each)
bool munlock (const void *const buf, std::size_t each)
ringbuffer_common_t (std::size_t sz)
Protected Member Functions inherited from ringbuffer_common_t
ringbuffer_common_t (std::size_t sz)
Protected Attributes inherited from ringbuffer_base
std::size_t num_readers = 0
to be const after initialisation
rb_atomic< std::size_t > readers_left
counts number of readers left in previous buffer half
rb_atomic< std::size_t > w_ptr
writer at buf[w_ptr]
Protected Attributes inherited from ringbuffer_common_t
const std::size_t size
< max number of objects in buffer (2^n for some n)
const std::size_t size_mask
= size - 1
Detailed Description
template<class T>
class ringbuffer_t< T >
TODO: specialization for only one reader.
Definition at line 111 of file ringbuffer.h.
Member Typedef Documentation
value_type
template<class T> using ringbuffer_t< T >::value_type = T
Definition at line 114 of file ringbuffer.h.
Constructor & Destructor Documentation
ringbuffer_t() [1/3]
template<class T> ringbuffer_t< T >::ringbuffer_t (const ringbuffer_t< T > &) delete
References ringbuffer_t().
Referenced by ringbuffer_t(), and ringbuffer_t().
ringbuffer_t() [2/3]
template<class T> ringbuffer_t< T >::ringbuffer_t (ringbuffer_t< T > && other) inline
move ctor.
should only be used in sequential mode, i.e. for initialization
Definition at line 129 of file ringbuffer.h.
References ringbuffer_t(), and buf.
ringbuffer_t() [3/3]
template<class T> ringbuffer_t< T >::ringbuffer_t (std::size_t sz) inline
allocating constructor
Parameters
sz size of buffer being allocated
Definition at line 138 of file ringbuffer.h.
References buf, ringbuffer_base::init_atomic_variables(), ringbuffer_base::ringbuffer_common_t(), and ringbuffer_common_t::size.
~ringbuffer_t()
template<class T> ringbuffer_t< T >::~ringbuffer_t () inline
Definition at line 148 of file ringbuffer.h.
References buf, and munlock().
Member Function Documentation
maximum_eventual_write_space()
template<class T> std::size_t ringbuffer_t< T >::maximum_eventual_write_space () const inline
size that is guaranteed to be writable once all readers are up to date
Definition at line 153 of file ringbuffer.h.
References ringbuffer_common_t::size.
mlock()
template<class T> bool ringbuffer_t< T >::mlock () inline
try to lock the data block using the syscall mlock
Returns
true iff the pages are guaranteed to be locked in RAM now
Definition at line 206 of file ringbuffer.h.
References buf, and ringbuffer_base::mlock().
munlock()
template<class T> bool ringbuffer_t< T >::munlock () inline
try to unlock the data block using the syscall munlock
Returns
true iff the pages are guaranteed to be unlocked from RAM now
Definition at line 210 of file ringbuffer.h.
References buf, and ringbuffer_base::munlock().
Referenced by ~ringbuffer_t().
touch()
template<class T> void ringbuffer_t< T >::touch () inline
overwrite the whole buffer with zeros this prevents page faults only allowed on startup (this is not fully checked!)
Definition at line 215 of file ringbuffer.h.
References buf, ringbuffer_base::readers_left, ringbuffer_common_t::size, and ringbuffer_base::w_ptr.
write()
template<class T> std::size_t ringbuffer_t< T >::write (const T * src, size_t cnt) inline
writes max(cnt, write_space) of src into the buffer overwrite this function in your subclass if you do not use the standard copier std_copy
Returns
number of objects successfully written
Definition at line 162 of file ringbuffer.h.
References write_func().
write_func()
template<class T> template<class Func> std::size_t ringbuffer_t< T >::write_func (Func & f, size_t cnt) inline
Definition at line 168 of file ringbuffer.h.
References buf, ringbuffer_base::init_variables_for_write(), ringbuffer_common_t::size_mask, and ringbuffer_base::w_ptr.
Referenced by write().
Friends And Related Symbol Documentation
ringbuffer_reader_t
template<class T> template<class _T> friend class ringbuffer_reader_t friend
Definition at line 120 of file ringbuffer.h.
References ringbuffer_reader_t.
Referenced by ringbuffer_reader_t.
Member Data Documentation
buf
template<class T> T* const ringbuffer_t< T >::buf private
Definition at line 117 of file ringbuffer.h.
Referenced by ringbuffer_t(), ringbuffer_t(), ~ringbuffer_t(), ringbuffer_reader_t< T >::connect(), mlock(), munlock(), touch(), and write_func().
The documentation for this class was generated from the following file:
src/3rdparty/ringbuffer/include/ringbuffer/ringbuffer.h