LMMS: Jack::JackDriverInterface Class Reference
Jack::JackDriverInterface Class Reference abstract
The base interface for drivers.
#include <JackDriver.h>
Public Member Functions
JackDriverInterface ()
virtual ~JackDriverInterface ()
virtual void AddSlave (JackDriverInterface *slave)=0
virtual int Attach ()=0
virtual int Detach ()=0
virtual bool GetMaster ()=0
virtual std::list< JackDriverInterface * > GetSlaves ()=0
virtual bool IsFixedBufferSize ()=0
virtual bool IsRealTime () const =0
virtual bool IsRunning () const =0
virtual int Open ()=0
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)=0
virtual int Process ()=0
virtual int ProcessRead ()=0
virtual int ProcessReadAsync ()=0
virtual int ProcessReadSlaves ()=0
virtual int ProcessReadSync ()=0
virtual int ProcessWrite ()=0
virtual int ProcessWriteAsync ()=0
virtual int ProcessWriteSlaves ()=0
virtual int ProcessWriteSync ()=0
virtual int Read ()=0
virtual void RemoveSlave (JackDriverInterface *slave)=0
virtual int SetBufferSize (jack_nframes_t buffer_size)=0
virtual void SetMaster (bool onoff)=0
virtual int SetSampleRate (jack_nframes_t sample_rate)=0
virtual int Start ()=0
virtual int Stop ()=0
virtual int Write ()=0
Detailed Description
The base interface for drivers.
Definition at line 43 of file JackDriver.h.
Constructor & Destructor Documentation
JackDriverInterface()
Jack::JackDriverInterface::JackDriverInterface () inline
Definition at line 48 of file JackDriver.h.
Referenced by AddSlave(), and RemoveSlave().
~JackDriverInterface()
virtual Jack::JackDriverInterface::~JackDriverInterface () inline virtual
Definition at line 50 of file JackDriver.h.
Member Function Documentation
AddSlave()
virtual void Jack::JackDriverInterface::AddSlave (JackDriverInterface * slave) pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
References JackDriverInterface().
Referenced by Jack::JackServer::SwitchMaster().
Attach()
virtual int Jack::JackDriverInterface::Attach () pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackALSARawMidiDriver, Jack::JackAudioDriver, Jack::JackCoreAudioDriver, Jack::JackCoreMidiDriver, Jack::JackDriver, Jack::JackFFADODriver, Jack::JackMidiDriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackPortAudioDriver, Jack::JackProxyDriver, Jack::JackThreadedDriver, Jack::JackWinMMEDriver, JackAlsaDriver, JackALSARawMidiDriver, and JackWinMMEDriver.
Referenced by Jack::JackServer::AddSlave().
Detach()
virtual int Jack::JackDriverInterface::Detach () pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackAudioDriver, Jack::JackDriver, Jack::JackFFADODriver, Jack::JackMidiDriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackProxyDriver, Jack::JackThreadedDriver, and JackAlsaDriver.
Referenced by Jack::JackServer::RemoveSlave().
GetMaster()
virtual bool Jack::JackDriverInterface::GetMaster () pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
GetSlaves()
virtual std::list< JackDriverInterface * > Jack::JackDriverInterface::GetSlaves () pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
IsFixedBufferSize()
virtual bool Jack::JackDriverInterface::IsFixedBufferSize () pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackBoomerDriver, Jack::JackCoreAudioDriver, Jack::JackDriver, Jack::JackFFADODriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackOSSDriver, Jack::JackOSSDriver, Jack::JackPortAudioDriver, Jack::JackThreadedDriver, Jack::JackTimedDriver, and JackAlsaDriver.
IsRealTime()
virtual bool Jack::JackDriverInterface::IsRealTime () const pure virtual
Implemented in Jack::JackDriver, Jack::JackFreewheelDriver, and Jack::JackThreadedDriver.
IsRunning()
virtual bool Jack::JackDriverInterface::IsRunning () const pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
Referenced by Jack::JackDriver::ProcessReadSlaves(), and Jack::JackDriver::ProcessWriteSlaves().
Open() [1/2]
virtual int Jack::JackDriverInterface::Open () pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
Referenced by Jack::JackIIODriver::Open(), Jack::JackNetDriver::Open(), and Jack::JackProxyDriver::Open().
Open() [2/2]
virtual int Jack::JackDriverInterface::Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency) pure virtual
Implemented in Jack::JackAudioDriver, Jack::JackDriver, Jack::JackGoldfishDriver, Jack::JackIIODriver, Jack::JackNetDriver, Jack::JackOpenSLESDriver, Jack::JackPortAudioDriver, Jack::JackProxyDriver, and Jack::JackThreadedDriver.
References capture_latency, and playback_latency.
Process()
virtual int Jack::JackDriverInterface::Process () pure virtual
Implemented in Jack::JackAudioDriver, Jack::JackDriver, Jack::JackDummyDriver, Jack::JackFreewheelDriver, and Jack::JackThreadedDriver.
ProcessRead()
virtual int Jack::JackDriverInterface::ProcessRead () pure virtual
Implemented in Jack::JackCoreMidiDriver, Jack::JackDriver, and Jack::JackThreadedDriver.
Referenced by Jack::JackDriver::ProcessReadSlaves().
ProcessReadAsync()
virtual int Jack::JackDriverInterface::ProcessReadAsync () pure virtual
Implemented in Jack::JackDriver, Jack::JackFreewheelDriver, Jack::JackLoopbackDriver, Jack::JackMidiDriver, and Jack::JackThreadedDriver.
ProcessReadSlaves()
virtual int Jack::JackDriverInterface::ProcessReadSlaves () pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
ProcessReadSync()
virtual int Jack::JackDriverInterface::ProcessReadSync () pure virtual
Implemented in Jack::JackDriver, Jack::JackFreewheelDriver, Jack::JackLoopbackDriver, Jack::JackMidiDriver, and Jack::JackThreadedDriver.
ProcessWrite()
virtual int Jack::JackDriverInterface::ProcessWrite () pure virtual
Implemented in Jack::JackCoreMidiDriver, Jack::JackDriver, and Jack::JackThreadedDriver.
Referenced by Jack::JackDriver::ProcessWriteSlaves().
ProcessWriteAsync()
virtual int Jack::JackDriverInterface::ProcessWriteAsync () pure virtual
Implemented in Jack::JackDriver, Jack::JackFreewheelDriver, Jack::JackLoopbackDriver, Jack::JackMidiDriver, and Jack::JackThreadedDriver.
ProcessWriteSlaves()
virtual int Jack::JackDriverInterface::ProcessWriteSlaves () pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
ProcessWriteSync()
virtual int Jack::JackDriverInterface::ProcessWriteSync () pure virtual
Implemented in Jack::JackDriver, Jack::JackFreewheelDriver, Jack::JackLoopbackDriver, Jack::JackMidiDriver, and Jack::JackThreadedDriver.
Read()
virtual int Jack::JackDriverInterface::Read () pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackALSARawMidiDriver, Jack::JackCoreAudioDriver, Jack::JackCoreMidiDriver, Jack::JackDriver, Jack::JackFFADODriver, Jack::JackGoldfishDriver, Jack::JackIIODriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackOpenSLESDriver, Jack::JackOSSDriver, Jack::JackOSSDriver, Jack::JackPortAudioDriver, Jack::JackProxyDriver, Jack::JackThreadedDriver, Jack::JackWinMMEDriver, JackAlsaDriver, JackALSARawMidiDriver, and JackWinMMEDriver.
RemoveSlave()
virtual void Jack::JackDriverInterface::RemoveSlave (JackDriverInterface * slave) pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
References JackDriverInterface().
SetBufferSize()
virtual int Jack::JackDriverInterface::SetBufferSize (jack_nframes_t buffer_size) pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackAudioDriver, Jack::JackBoomerDriver, Jack::JackCoreAudioDriver, Jack::JackDriver, Jack::JackFFADODriver, Jack::JackGoldfishDriver, Jack::JackIIODriver, Jack::JackMidiDriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackOpenSLESDriver, Jack::JackOSSDriver, Jack::JackOSSDriver, Jack::JackPortAudioDriver, Jack::JackThreadedDriver, and JackAlsaDriver.
Referenced by Jack::JackDriver::SetBufferSize().
SetMaster()
virtual void Jack::JackDriverInterface::SetMaster (bool onoff) pure virtual
Implemented in Jack::JackDriver, and Jack::JackThreadedDriver.
Referenced by Jack::JackServer::AddSlave().
SetSampleRate()
virtual int Jack::JackDriverInterface::SetSampleRate (jack_nframes_t sample_rate) pure virtual
Implemented in Jack::JackAudioDriver, Jack::JackDriver, Jack::JackNetDriver, Jack::JackNetOneDriver, and Jack::JackThreadedDriver.
Referenced by Jack::JackDriver::SetSampleRate().
Start()
virtual int Jack::JackDriverInterface::Start () pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackALSARawMidiDriver, Jack::JackBoomerDriver, Jack::JackCoreAudioDriver, Jack::JackCoreMidiDriver, Jack::JackDriver, Jack::JackFFADODriver, Jack::JackPortAudioDriver, Jack::JackThreadedDriver, Jack::JackTimedDriver, Jack::JackWinMMEDriver, JackAlsaDriver, JackALSARawMidiDriver, and JackWinMMEDriver.
Referenced by Jack::JackAlsaDriver::Start(), Jack::JackALSARawMidiDriver::Start(), Jack::JackBoomerDriver::Start(), Jack::JackFFADODriver::Start(), Jack::JackPortAudioDriver::Start(), Jack::JackTimedDriver::Start(), Jack::JackWinMMEDriver::Start(), and Jack::JackDriver::StartSlaves().
Stop()
virtual int Jack::JackDriverInterface::Stop () pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackALSARawMidiDriver, Jack::JackBoomerDriver, Jack::JackCoreAudioDriver, Jack::JackCoreMidiDriver, Jack::JackDriver, Jack::JackFFADODriver, Jack::JackPortAudioDriver, Jack::JackProxyDriver, Jack::JackThreadedDriver, Jack::JackWinMMEDriver, JackAlsaDriver, JackALSARawMidiDriver, and JackWinMMEDriver.
Referenced by Jack::JackAlsaDriver::Start(), Jack::JackFFADODriver::Start(), Jack::JackPortAudioDriver::Start(), Jack::JackAlsaDriver::Stop(), Jack::JackALSARawMidiDriver::Stop(), Jack::JackFFADODriver::Stop(), Jack::JackPortAudioDriver::Stop(), Jack::JackWinMMEDriver::Stop(), and Jack::JackDriver::StopSlaves().
Write()
virtual int Jack::JackDriverInterface::Write () pure virtual
Implemented in Jack::JackAlsaDriver, Jack::JackALSARawMidiDriver, Jack::JackAudioDriver, Jack::JackCoreAudioDriver, Jack::JackCoreMidiDriver, Jack::JackDriver, Jack::JackFFADODriver, Jack::JackGoldfishDriver, Jack::JackIIODriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackOpenSLESDriver, Jack::JackOSSDriver, Jack::JackOSSDriver, Jack::JackPortAudioDriver, Jack::JackProxyDriver, Jack::JackThreadedDriver, Jack::JackWinMMEDriver, JackAlsaDriver, JackALSARawMidiDriver, and JackWinMMEDriver.
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackDriver.h