LMMS: Jack::JackExternalClient Class Reference
Jack::JackExternalClient Class Reference
Server side implementation of library clients.
#include <JackExternalClient.h>
Public Member Functions
JackExternalClient ()
Client control in shared memory.
virtual ~JackExternalClient ()
int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
int Close ()
JackClientControl * GetClientControl () const
int Open (const char *name, int pid, int refnum, jack_uuid_t uuid, int *shared_client)
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Attributes
JackNotifyChannel fChannel
JackClientControl * fClientControl
Server/client communication channel.
Detailed Description
Server side implementation of library clients.
Definition at line 36 of file JackExternalClient.h.
Constructor & Destructor Documentation
JackExternalClient()
Jack::JackExternalClient::JackExternalClient ()
Client control in shared memory.
Definition at line 30 of file JackExternalClient.cpp.
References fClientControl.
~JackExternalClient()
Jack::JackExternalClient::~JackExternalClient () virtual
Definition at line 33 of file JackExternalClient.cpp.
Member Function Documentation
ClientNotify()
int Jack::JackExternalClient::ClientNotify (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value2) virtual
Implements Jack::JackClientInterface.
Definition at line 36 of file JackExternalClient.cpp.
References fChannel, fClientControl, and jack_log().
Close()
int Jack::JackExternalClient::Close () virtual
Implements Jack::JackClientInterface.
Definition at line 72 of file JackExternalClient.cpp.
References fChannel, fClientControl, and jack_log().
GetClientControl()
JackClientControl * Jack::JackExternalClient::GetClientControl () const virtual
Implements Jack::JackClientInterface.
Definition at line 83 of file JackExternalClient.cpp.
References fClientControl.
Open()
int Jack::JackExternalClient::Open (const char * name, int pid, int refnum, jack_uuid_t uuid, int * shared_client)
Definition at line 44 of file JackExternalClient.cpp.
References fChannel, fClientControl, Jack::JackShmMemAble::GetShmAddress(), Jack::JackShmMemAble::GetShmIndex(), Jack::JackShmMemAble::Init(), jack_error, and jack_log().
Member Data Documentation
fChannel
JackNotifyChannel Jack::JackExternalClient::fChannel private
Definition at line 41 of file JackExternalClient.h.
Referenced by ClientNotify(), Close(), and Open().
fClientControl
JackClientControl* Jack::JackExternalClient::fClientControl private
Server/client communication channel.
Definition at line 42 of file JackExternalClient.h.
Referenced by JackExternalClient(), ClientNotify(), Close(), GetClientControl(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackExternalClient.h
src/3rdparty/jack2/common/JackExternalClient.cpp