LMMS: src/3rdparty/jack2/tests/testSem.cpp File Reference
testSem.cpp File Reference
#include <stdio.h>
#include <sys/time.h>
#include <stdlib.h>
#include <string.h>
#include "JackPosixSemaphore.h"
#include "JackFifo.h"
#include "JackPlatformPlug.h"
Classes
struct ClientThread
struct ServerThread
Macros
#define ITER 500000
Functions
void client (detail::JackSynchro *sem)
int main (int argc, char *const argv[])
void server (detail::JackSynchro *sem)
Macro Definition Documentation
ITER
#define ITER 500000
Definition at line 34 of file testSem.cpp.
Referenced by ClientThread::Execute(), and ServerThread::Execute().
Function Documentation
client()
void client (detail::JackSynchro * sem)
Definition at line 140 of file testSem.cpp.
References Jack::detail::JackSynchro::Connect(), Jack::detail::JackSynchro::Signal(), and Jack::detail::JackSynchro::Wait().
Referenced by Jack::JackAudioAdapter::JackAudioAdapter(), Jack::JackCoreMidiPhysicalInputPort::JackCoreMidiPhysicalInputPort(), Jack::JackCoreMidiPhysicalOutputPort::JackCoreMidiPhysicalOutputPort(), Jack::JackCoreMidiVirtualInputPort::JackCoreMidiVirtualInputPort(), Jack::JackCoreMidiVirtualOutputPort::JackCoreMidiVirtualOutputPort(), Jack::JackDebugClient::JackDebugClient(), Jack::JackNetMasterManager::JackNetMasterManager(), Jack::JackProfiler::JackProfiler(), Jack::JackProfilerClient::JackProfilerClient(), Jack::JackSapaProxy::JackSapaProxy(), lmms::MidiPort::MidiPort(), Jack::JackWinNamedPipeServerChannel::~JackWinNamedPipeServerChannel(), Jack::JackWinNamedPipeServer::AcceptClient(), alsa_driver_new(), Jack::JackEngineControl::CalcCPULoad(), Jack::JackTransportEngine::CheckAllRolling(), Jack::JackEngine::CheckXRun(), Jack::JackEngine::ClientActivate(), Jack::JackWinNamedPipeServerChannel::ClientAdd(), Jack::JackEngine::ClientCheckName(), Jack::JackEngine::ClientCloseAux(), Jack::JackEngine::ClientDeactivate(), Jack::JackEngine::ClientExternalClose(), Jack::JackEngine::ClientExternalOpen(), Jack::JackEngine::ClientHasSessionCallback(), Jack::JackEngine::ClientInternalOpen(), Jack::JackLockedEngine::ClientInternalOpen(), Jack::JackEngine::ClientNotify(), Jack::detail::JackClientChannelInterface::ClientOpen(), Jack::JackInternalClientChannel::ClientOpen(), Jack::JackEngine::EnsureUUID(), Jack::JackEngine::GetClientNameForUUID(), Jack::JackEngine::GetClientPID(), Jack::JackEngine::GetClientRefNum(), Jack::JackEngine::GetInternalClientName(), Jack::JackEngine::GetUUIDForClientName(), Jack::JackLibGlobals::Init(), Jack::JackEngine::InternalClientHandle(), Jack::JackServer::InternalClientLoad1(), Jack::JackServer::InternalClientLoad2(), Jack::JackServer::InternalClientLoadAux(), Jack::JackEngine::InternalClientUnload(), jack_activate(), jack_client_close(), jack_client_close(), JACK_client_create_thread(), jack_client_create_thread(), jack_client_get_uuid(), jack_client_has_session_callback(), jack_client_kill_thread(), jack_client_max_real_time_priority(), jack_client_new_aux(), jack_client_open_aux(), jack_client_open_aux(), jack_client_real_time_priority(), jack_client_stop_thread(), jack_client_thread_id(), jack_connect(), jack_cpu_load(), jack_cycle_signal(), jack_cycle_wait(), jack_deactivate(), jack_disconnect(), jack_engine_takeover_timebase(), JACK_frame_time(), jack_frames_to_time(), jack_get_buffer_size(), jack_get_client_name(), jack_get_client_name_by_uuid(), jack_get_current_transport_frame(), jack_get_cycle_times(), jack_get_internal_client_name(), jack_get_max_delayed_usecs(), jack_get_ports(), JACK_get_sample_rate(), jack_get_sample_rate(), jack_get_uuid_for_client_name(), jack_get_xrun_delayed_usecs(), jack_internal_client_handle(), jack_internal_client_load(), jack_internal_client_load_aux(), jack_internal_client_unload(), jack_internal_initialize(), JACK_is_realtime(), jack_is_realtime(), JACK_last_frame_time(), jack_on_info_shutdown(), jack_on_shutdown(), jack_port_by_name(), jack_port_disconnect(), jack_port_get_all_connections(), jack_port_get_total_latency(), jack_port_is_mine(), JACK_port_register(), jack_port_register(), jack_port_rename(), jack_port_request_monitor_by_name(), jack_port_set_name(), jack_port_type_get_buffer_size(), JACK_port_unregister(), jack_port_unregister(), jack_recompute_total_latencies(), jack_recompute_total_latency(), jack_release_timebase(), jack_remove_all_properties(), jack_remove_properties(), jack_remove_property(), jack_reserve_client_name(), jack_reset_max_delayed_usecs(), jack_session_notify(), jack_session_reply(), jack_set_buffer_size(), jack_set_buffer_size_callback(), jack_set_client_registration_callback(), jack_set_freewheel(), jack_set_freewheel_callback(), jack_set_graph_order_callback(), jack_set_latency_callback(), jack_set_port_connect_callback(), jack_set_port_registration_callback(), jack_set_port_rename_callback(), jack_set_process_callback(), jack_set_process_thread(), jack_set_property(), jack_set_property_change_callback(), jack_set_sample_rate_callback(), jack_set_session_callback(), jack_set_sync_callback(), jack_set_sync_timeout(), jack_set_thread_init_callback(), jack_set_timebase_callback(), jack_set_xrun_callback(), jack_thread(), jack_thread_wait(), jack_time_to_frames(), jack_transport_locate(), jack_transport_query(), jack_transport_reposition(), jack_transport_start(), jack_transport_stop(), main(), Jack::JackTransportEngine::MakeAllLocating(), Jack::JackTransportEngine::MakeAllStartingLocating(), Jack::JackTransportEngine::MakeAllStopping(), netjack_init(), Jack::JackEngine::NotifyClient(), Jack::JackEngine::NotifyRemoveClient(), Jack::JackSocketClientChannel::Open(), Jack::JackWinNamedPipeClientChannel::Open(), Jack::JackEngine::PortConnect(), Jack::JackEngine::PortRegister(), Jack::JackEngine::PortUnRegister(), process4(), process5(), Jack::JackEngineProfiling::Profile(), Jack::JackEngine::PropertyChangeNotify(), Jack::JackMetadata::PropertyChangeNotify(), Jack::JackMetadata::RemoveAllProperties(), Jack::JackMetadata::RemoveProperties(), Jack::JackMetadata::RemoveProperty(), Jack::JackEngine::SessionNotify(), Jack::JackEngine::SessionReply(), Jack::JackMetadata::SetProperty(), Jack::JackSapaProxy::Setup(), and Jack::JackDebugClient::TimeCallback().
main()
int main (int argc, char *const argv[])
Definition at line 166 of file testSem.cpp.
References client(), and server().
server()
void server (detail::JackSynchro * sem)
Definition at line 113 of file testSem.cpp.
References Jack::detail::JackSynchro::Allocate(), Jack::detail::JackSynchro::SignalAll(), and Jack::detail::JackSynchro::Wait().
Referenced by Jack::JackInternalClient::JackInternalClient(), Jack::JackInternalClientChannel::JackInternalClientChannel(), Jack::JackInternalSessionLoader::JackInternalSessionLoader(), Jack::JackLoadableInternalClient::JackLoadableInternalClient(), Jack::JackLoadableInternalClient1::JackLoadableInternalClient1(), Jack::JackLoadableInternalClient2::JackLoadableInternalClient2(), Jack::JackRequestDecoder::JackRequestDecoder(), jack_params_create(), jackctl_server_get_driver(), jackctl_server_get_internal(), main(), Jack::JackClientPipeThread::Open(), Jack::JackSocketServerChannel::Open(), Jack::JackWinNamedPipeServerChannel::Open(), print_server_drivers(), print_server_internals(), and usage().