LMMS: lmms::gui::PianoRoll Class Reference
lmms::gui::PianoRoll Class Reference
#include <PianoRoll.h>
Public Types
enum class EditMode {
Draw ,
Erase ,
Select ,
Detuning ,
Knife ,
Strum
}
Signals
void currentMidiClipChanged ()
void ghostClipSet (bool)
void positionChanged (const lmms::TimePos &)
void semiToneMarkerMenuChordSetEnabled (bool)
void semiToneMarkerMenuScaleSetEnabled (bool)
Public Member Functions
const MidiClip * currentMidiClip () const
Song::PlayMode desiredPlayModeForAccompany () const
bool hasValidMidiClip () const
bool isRecording () const
bool isStepRecording () const
void loadGhostNotes (const QDomElement &de)
void loadMarkedSemiTones (const QDomElement &de)
int quantization () const
void reset ()
Resets settings to default when e.g.
void setCurrentMidiClip (MidiClip *newMidiClip)
void setGhostMidiClip (MidiClip *newMidiClip)
void showPanTextFloat (panning_t pan, const QPoint &pos, int timeout=-1)
void showTextFloat (const QString &text, const QPoint &pos, int timeout=-1)
void showVolTextFloat (volume_t vol, const QPoint &pos, int timeout=-1)
void stopRecording ()
int trackOctaveSize () const
Protected Types
enum class QuantizeAction {
Both ,
Pos ,
Length
}
enum class SemiToneMarkerAction {
UnmarkAll ,
MarkCurrentSemiTone ,
MarkAllOctaveSemiTones ,
MarkCurrentScale ,
MarkCurrentChord ,
CopyAllNotesOnKey
}
Protected Slots
void changeNoteEditMode (int i)
void changeSnapMode ()
void clearGhostClip ()
void constrainNoteLengths (bool constrainMax)
void copySelectedNotes ()
void cutSelectedNotes ()
bool deleteSelectedNotes ()
void finishRecordNote (const lmms::Note &n)
void fitNoteLengths (bool fill)
void glueNotes ()
void hideMidiClip (lmms::MidiClip *clip)
void horScrolled (int new_pos)
void keyChanged ()
void markSemiTone (SemiToneMarkerAction i, bool fromMenu=true)
void noteLengthChanged ()
void pasteNotes ()
void play ()
void quantizeChanged ()
void quantizeNotes (QuantizeAction mode=QuantizeAction::Both)
void record ()
void recordAccompany ()
void reverseNotes ()
void selectRegionFromPixels (int xStart, int xEnd)
void setEditMode (int mode)
void startRecordNote (const lmms::Note &n)
void stop ()
bool toggleStepRecording ()
void updatePosition (const lmms::TimePos &t)
void updatePositionAccompany (const lmms::TimePos &t)
void updatePositionStepRecording (const lmms::TimePos &t)
void updateSemiToneMarkerMenu ()
void verScrolled (int new_pos)
void zoomingChanged ()
void zoomingYChanged ()
Protected Member Functions
void drawNoteRect (QPainter &p, int x, int y, int width, const Note *n, const QColor &noteCol, const QColor &noteTextColor, const QColor &selCol, const int noteOpc, const bool borderless, bool drawNoteName)
void enterValue (NoteVector *nv)
void focusInEvent (QFocusEvent *) override
void focusOutEvent (QFocusEvent *) override
NoteVector getSelectedNotes () const
void keyPressEvent (QKeyEvent *ke) override
void keyReleaseEvent (QKeyEvent *ke) override
void leaveEvent (QEvent *e) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
void paintEvent (QPaintEvent *pe) override
void removeSelection ()
void resizeEvent (QResizeEvent *re) override
void selectAll ()
void selectNotesOnKey ()
void updateYScroll ()
void wheelEvent (QWheelEvent *we) override
Properties
QColor backgroundShade
QColor barColor
QColor barLineColor
QColor beatLineColor
QBrush blackKeyActiveBackground
QBrush blackKeyDisabledBackground
QBrush blackKeyInactiveBackground
int blackKeyWidth
QColor currentStepNoteColor
bool ghostNoteBorders
QColor ghostNoteColor
int ghostNoteOpacity
QColor ghostNoteTextColor
QColor knifeCutLine
QColor lineColor
QColor markedSemitoneColor
bool noteBorders
QColor noteColor
QColor noteModeColor
int noteOpacity
QColor noteTextColor
QColor outOfBoundsShade
QColor selectedNoteColor
QColor stepNoteColor
QColor textColor
QColor textColorLight
QColor textShadow
QBrush whiteKeyActiveBackground
QColor whiteKeyActiveTextColor
QColor whiteKeyActiveTextShadow
QBrush whiteKeyDisabledBackground
QBrush whiteKeyInactiveBackground
QColor whiteKeyInactiveTextColor
QColor whiteKeyInactiveTextShadow
int whiteKeyWidth
Private Types
enum class Action {
None ,
MoveNote ,
ResizeNote ,
SelectNotes ,
ChangeNoteProperty ,
ResizeNoteEditArea ,
Knife ,
Strum
}
enum class GridMode {
Nudge ,
Snap
}
enum class KeyType {
WhiteSmall ,
WhiteBig ,
Black
}
enum class NoteEditMode {
Volume ,
Panning ,
Count
}
Private Member Functions
PianoRoll ()
PianoRoll (const PianoRoll &)
~PianoRoll () override=default
void adjustLeftRightScoll (int value)
void autoScroll (const TimePos &t)
void cancelKnifeAction ()
void cancelStrumAction ()
void clearSelectedNotes ()
void computeSelectedNotes (bool shift)
void copyToClipboard (const NoteVector &notes) const
void dragNotes (int x, int y, bool alt, bool shift, bool ctrl)
void drawDetuningInfo (QPainter &_p, const Note *_n, int _x, int _y) const
QList< int > getAllOctavesForKey (int keyToMirror) const
int getKey (int y) const
const NoteVector & ghostNotes () const
bool isSelection () const
int keyAreaBottom () const
int keyAreaTop () const
bool mouseOverNote ()
TimePos newNoteLen () const
int noteEditBottom () const
int noteEditLeft () const
int noteEditRight () const
int noteEditTop () const
Note * noteUnderMouse ()
void pauseChordNotes (int key)
void pauseTestNotes (bool pause=true)
void playChordNotes (int key, int velocity=-1)
int selectionCount () const
void setKnifeAction ()
void setStrumAction ()
void setupSelectedChords ()
Computes which notes belong to which chords from the selection.
void shiftPos (const NoteVector &notes, int amount)
void shiftPos (int amount)
void shiftSemiTone (const NoteVector &notes, int amount)
void shiftSemiTone (int amount)
void testPlayKey (int _key, int _vol, int _pan)
void testPlayNote (Note *n)
void updateKnifePos (QMouseEvent *me, bool initial)
void updatePositionLineHeight ()
void updateScrollbars ()
void updateStrumPos (QMouseEvent *me, bool initial, bool warp)
Handles updating all of the note positions when performing a strum.
int yCoordOfKey (int key) const
Private Attributes
Action m_action
QColor m_backgroundShade
QColor m_barColor
QColor m_barLineColor
QColor m_beatLineColor
QBrush m_blackKeyActiveBackground
QBrush m_blackKeyDisabledBackground
int m_blackKeyHeight
QBrush m_blackKeyInactiveBackground
int m_blackKeyWidth
ComboBoxModel m_chordModel
EditMode m_ctrlMode
Note * m_currentNote
TimePos m_currentPosition
QColor m_currentStepNoteColor
bool m_doAutoQuantization {false}
EditMode m_editMode
bool m_ghostNoteBorders
QColor m_ghostNoteColor
int m_ghostNoteOpacity
NoteVector m_ghostNotes
QColor m_ghostNoteTextColor
GridMode m_gridMode
int m_keyLineHeight
ComboBoxModel m_keyModel
QColor m_knifeCutLineColor
bool m_knifeDown
int m_knifeEndKey
TimePos m_knifeEndTickPos
EditMode m_knifeMode
int m_knifeStartKey
TimePos m_knifeStartTickPos
int m_lastKey
int m_lastMouseX
int m_lastMouseY
panning_t m_lastNotePanning
volume_t m_lastNoteVolume
QScrollBar * m_leftRightScroll
TimePos m_lenOfNewNotes
QColor m_lineColor
QColor m_markedSemitoneColor
QList< int > m_markedSemiTones
MidiClip * m_midiClip
TimePos m_minResizeLen
int m_mouseDownKey
bool m_mouseDownRight
int m_mouseDownTick
int m_moveBoundaryBottom
int m_moveBoundaryLeft
int m_moveBoundaryRight
int m_moveBoundaryTop
int m_moveStartX
int m_moveStartY
std::vector< QString > m_nemStr
bool m_noteBorders
QColor m_noteColor
QMenu * m_noteEditMenu
NoteEditMode m_noteEditMode
ComboBoxModel m_noteLenModel
QColor m_noteModeColor
int m_noteOpacity
int m_notesEditHeight
QColor m_noteTextColor
QColor m_outOfBoundsShade
int m_pianoKeySelected
int m_pianoKeysVisible
PositionLine * m_positionLine
int m_ppb
ComboBoxModel m_quantizeModel
bool m_recording
QList< Note > m_recordingNotes
ComboBoxModel m_scaleModel
bool m_scrollBack
std::vector< NoteVector > m_selectedChords
Stores the chords for the strum tool.
int m_selectedKeys
QColor m_selectedNoteColor
int m_selectedTick
int m_selectStartKey
int m_selectStartTick
QMenu * m_semiToneMarkerMenu
ComboBoxModel m_snapModel
bool m_startedWithShift
int m_startKey
QColor m_stepNoteColor
StepRecorder m_stepRecorder
StepRecorderWidget m_stepRecorderWidget
TimePos m_strumCurrentTime
int m_strumCurrentVertical = 0
bool m_strumEnabled = false
float m_strumHeightRatio = 0.0f
EditMode m_strumMode
TimePos m_strumStartTime
int m_strumStartVertical = 0
QColor m_textColor
QColor m_textColorLight
QColor m_textShadow
TimeLineWidget * m_timeLine
QPixmap m_toolDraw = embed::getIconPixmap("edit_draw")
QPixmap m_toolErase = embed::getIconPixmap("edit_erase")
QPixmap m_toolKnife = embed::getIconPixmap("edit_knife")
QPixmap m_toolMove = embed::getIconPixmap("edit_move")
QPixmap m_toolOpen = embed::getIconPixmap("automation")
QPixmap m_toolSelect = embed::getIconPixmap("edit_select")
QPixmap m_toolStrum = embed::getIconPixmap("arp_free")
QScrollBar * m_topBottomScroll
int m_totalKeysToScroll
int m_userSetNotesEditHeight
QBrush m_whiteKeyActiveBackground
QColor m_whiteKeyActiveTextColor
QColor m_whiteKeyActiveTextShadow
int m_whiteKeyBigHeight
QBrush m_whiteKeyDisabledBackground
QBrush m_whiteKeyInactiveBackground
QColor m_whiteKeyInactiveTextColor
QColor m_whiteKeyInactiveTextShadow
int m_whiteKeySmallHeight
int m_whiteKeyWidth
ComboBoxModel m_zoomingModel
ComboBoxModel m_zoomingYModel
Static Private Attributes
static const int cm_scrollAmtHoriz = 10
static const int cm_scrollAmtVert = 1
static const std::vector< float > m_zoomLevels
static const std::vector< float > m_zoomYLevels
static std::array< KeyType, 12 > prKeyOrder
static SimpleTextFloat * s_textFloat = nullptr
Friends
class PianoRollWindow
Detailed Description
Definition at line 64 of file PianoRoll.h.
Member Enumeration Documentation
Action
enum class lmms::gui::PianoRoll::Action strong private
Enumerator
None
MoveNote
ResizeNote
SelectNotes
ChangeNoteProperty
ResizeNoteEditArea
Knife
Strum
Definition at line 261 of file PianoRoll.h.
EditMode
enum class lmms::gui::PianoRoll::EditMode strong
Enumerator
Draw
Erase
Select
Detuning
Knife
Strum
Definition at line 106 of file PianoRoll.h.
GridMode
enum class lmms::gui::PianoRoll::GridMode strong private
Enumerator
Nudge
Snap
Definition at line 287 of file PianoRoll.h.
KeyType
enum class lmms::gui::PianoRoll::KeyType strong private
Enumerator
WhiteSmall
WhiteBig
Black
Definition at line 280 of file PianoRoll.h.
NoteEditMode
enum class lmms::gui::PianoRoll::NoteEditMode strong private
Enumerator
Volume
Panning
Count
Definition at line 273 of file PianoRoll.h.
QuantizeAction
enum class lmms::gui::PianoRoll::QuantizeAction strong protected
Enumerator
Both
Pos
Length
Definition at line 161 of file PianoRoll.h.
SemiToneMarkerAction
enum class lmms::gui::PianoRoll::SemiToneMarkerAction strong protected
Enumerator
UnmarkAll
MarkCurrentSemiTone
MarkAllOctaveSemiTones
MarkCurrentScale
MarkCurrentChord
CopyAllNotesOnKey
Definition at line 168 of file PianoRoll.h.
Constructor & Destructor Documentation
PianoRoll() [1/2]
lmms::gui::PianoRoll::PianoRoll () private
Definition at line 151 of file PianoRoll.cpp.
References lmms::gui::BLACK_KEY_WIDTH, changeNoteEditMode(), changeSnapMode(), lmms::InstrumentFunctionNoteStacking::ChordTable::chords(), CopyAllNotesOnKey, lmms::Model::dataChanged(), lmms::gui::DEFAULT_KEY_LINE_HEIGHT, lmms::gui::DEFAULT_PR_PPB, lmms::DefaultPanning, lmms::DefaultTicksPerBar, lmms::DefaultVolume, lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance(), lmms::Engine::getSong(), horScrolled(), i, lmms::gui::INITIAL_START_KEY, lmms::ConfigManager::inst(), keyChanged(), m_action, m_backgroundShade, m_barColor, m_barLineColor, m_beatLineColor, m_blackKeyHeight, m_blackKeyWidth, m_chordModel, m_ctrlMode, m_currentNote, m_currentPosition, m_currentStepNoteColor, m_doAutoQuantization, m_editMode, m_ghostNoteBorders, m_ghostNoteColor, m_ghostNoteOpacity, m_ghostNoteTextColor, m_keyLineHeight, m_keyModel, m_knifeCutLineColor, m_lastKey, m_lastMouseX, m_lastMouseY, m_lastNotePanning, m_lastNoteVolume, m_leftRightScroll, m_lenOfNewNotes, m_lineColor, m_markedSemitoneColor, m_midiClip, m_minResizeLen, m_mouseDownKey, m_mouseDownRight, m_mouseDownTick, m_moveBoundaryBottom, m_moveBoundaryLeft, m_moveBoundaryRight, m_moveBoundaryTop, m_nemStr, m_noteBorders, m_noteColor, m_noteEditMenu, m_noteEditMode, m_noteLenModel, m_noteModeColor, m_noteOpacity, m_notesEditHeight, m_noteTextColor, m_outOfBoundsShade, m_positionLine, m_ppb, m_quantizeModel, m_recording, m_scaleModel, m_scrollBack, m_selectedNoteColor, m_semiToneMarkerMenu, m_snapModel, m_startKey, m_stepNoteColor, m_stepRecorder, m_stepRecorderWidget, m_textColor, m_textColorLight, m_textShadow, m_timeLine, m_topBottomScroll, m_userSetNotesEditHeight, m_whiteKeyBigHeight, m_whiteKeySmallHeight, m_whiteKeyWidth, m_zoomingModel, m_zoomingYModel, m_zoomLevels, m_zoomYLevels, MarkAllOctaveSemiTones, MarkCurrentChord, MarkCurrentScale, MarkCurrentSemiTone, markSemiTone(), lmms::Song::MidiClip, None, noteLengthChanged(), lmms::gui::NUM_EVEN_LENGTHS, lmms::gui::NUM_TRIPLET_LENGTHS, positionChanged(), lmms::gui::TimeLineWidget::positionChanged(), lmms::gui::PR_BOTTOM_MARGIN, lmms::gui::PR_TOP_MARGIN, lmms::gui::Quantizations, quantizeChanged(), removeSelection(), lmms::gui::s_noteStrings, s_textFloat, selectRegionFromPixels(), semiToneMarkerMenuChordSetEnabled(), semiToneMarkerMenuScaleSetEnabled(), UnmarkAll, updatePosition(), lmms::gui::TimeLineWidget::updatePosition(), updatePositionAccompany(), updatePositionStepRecording(), updateSemiToneMarkerMenu(), lmms::ConfigManager::valueChanged(), verScrolled(), lmms::gui::WHITE_KEY_WIDTH, zoomingChanged(), and zoomingYChanged().
Referenced by PianoRoll().
PianoRoll() [2/2]
lmms::gui::PianoRoll::PianoRoll (const PianoRoll &) private
References PianoRoll().
~PianoRoll()
lmms::gui::PianoRoll::~PianoRoll () override private default
Member Function Documentation
adjustLeftRightScoll()
void lmms::gui::PianoRoll::adjustLeftRightScoll (int value) private
Definition at line 3864 of file PianoRoll.cpp.
References adjustLeftRightScoll(), m_leftRightScroll, m_zoomingModel, and m_zoomLevels.
Referenced by adjustLeftRightScoll(), and wheelEvent().
autoScroll()
void lmms::gui::PianoRoll::autoScroll (const TimePos & t) private
Definition at line 4605 of file PianoRoll.cpp.
References autoScroll(), lmms::gui::TimeLineWidget::Continuous, lmms::TimePos::getBar(), lmms::TimePos::getTicks(), m_currentPosition, m_leftRightScroll, m_ppb, m_scrollBack, m_timeLine, m_whiteKeyWidth, lmms::gui::TimeLineWidget::Stepped, and lmms::TimePos::ticksPerBar().
Referenced by autoScroll(), updatePosition(), updatePositionAccompany(), and updatePositionStepRecording().
cancelKnifeAction()
void lmms::gui::PianoRoll::cancelKnifeAction () private
Definition at line 2175 of file PianoRoll.cpp.
References cancelKnifeAction(), m_action, m_editMode, m_knifeDown, m_knifeMode, and None.
Referenced by cancelKnifeAction(), keyPressEvent(), and mouseReleaseEvent().
cancelStrumAction()
void lmms::gui::PianoRoll::cancelStrumAction () private
Definition at line 2197 of file PianoRoll.cpp.
References cancelStrumAction(), m_action, m_editMode, m_strumEnabled, m_strumMode, and None.
Referenced by cancelStrumAction(), keyPressEvent(), and mouseReleaseEvent().
changeNoteEditMode
void lmms::gui::PianoRoll::changeNoteEditMode (int i) protected slot
Definition at line 488 of file PianoRoll.cpp.
References i, and m_noteEditMode.
Referenced by PianoRoll().
changeSnapMode
void lmms::gui::PianoRoll::changeSnapMode () protected slot
Definition at line 4873 of file PianoRoll.cpp.
References changeSnapMode(), m_gridMode, and m_snapModel.
Referenced by PianoRoll(), and changeSnapMode().
clearGhostClip
void lmms::gui::PianoRoll::clearGhostClip () protected slot
Definition at line 634 of file PianoRoll.cpp.
References ghostClipSet(), and setGhostMidiClip().
Referenced by reset().
clearSelectedNotes()
void lmms::gui::PianoRoll::clearSelectedNotes () private
Definition at line 1175 of file PianoRoll.cpp.
References clearSelectedNotes(), and m_midiClip.
Referenced by clearSelectedNotes(), keyPressEvent(), mousePressEvent(), mouseReleaseEvent(), and pasteNotes().
computeSelectedNotes()
void lmms::gui::PianoRoll::computeSelectedNotes (bool shift) private
Definition at line 2225 of file PianoRoll.cpp.
References computeSelectedNotes(), hasValidMidiClip(), m_midiClip, m_selectedKeys, m_selectedTick, m_selectStartKey, m_selectStartTick, m_startKey, and removeSelection().
Referenced by computeSelectedNotes(), keyReleaseEvent(), mouseReleaseEvent(), and selectRegionFromPixels().
constrainNoteLengths
void lmms::gui::PianoRoll::constrainNoteLengths (bool constrainMax) protected slot
Definition at line 759 of file PianoRoll.cpp.
References constrainNoteLengths(), lmms::gui::getGUI(), getSelectedNotes(), lmms::Engine::getSong(), hasValidMidiClip(), m_lenOfNewNotes, m_midiClip, and lmms::Song::setModified().
Referenced by constrainNoteLengths().
copySelectedNotes
void lmms::gui::PianoRoll::copySelectedNotes () protected slot
Definition at line 4488 of file PianoRoll.cpp.
References copySelectedNotes(), copyToClipboard(), and getSelectedNotes().
Referenced by copySelectedNotes().
copyToClipboard()
void lmms::gui::PianoRoll::copyToClipboard (const NoteVector & notes) const private
Definition at line 4465 of file PianoRoll.cpp.
References lmms::DataFile::ClipboardData, lmms::DataFile::content(), copyToClipboard(), lmms::Note::pos(), lmms::SerializingObject::saveState(), and lmms::Note::setPos().
Referenced by copySelectedNotes(), copyToClipboard(), and cutSelectedNotes().
currentMidiClip()
const MidiClip * lmms::gui::PianoRoll::currentMidiClip () const inline
Definition at line 144 of file PianoRoll.h.
References m_midiClip.
currentMidiClipChanged
void lmms::gui::PianoRoll::currentMidiClipChanged () signal
Referenced by setCurrentMidiClip().
cutSelectedNotes
void lmms::gui::PianoRoll::cutSelectedNotes () protected slot
Definition at line 4501 of file PianoRoll.cpp.
References copyToClipboard(), cutSelectedNotes(), lmms::gui::getGUI(), getSelectedNotes(), lmms::Engine::getSong(), hasValidMidiClip(), m_midiClip, and lmms::Song::setModified().
Referenced by cutSelectedNotes().
deleteSelectedNotes
bool lmms::gui::PianoRoll::deleteSelectedNotes () protected slot
Definition at line 4585 of file PianoRoll.cpp.
References deleteSelectedNotes(), lmms::gui::getGUI(), getSelectedNotes(), lmms::Engine::getSong(), hasValidMidiClip(), m_midiClip, and lmms::Song::setModified().
Referenced by deleteSelectedNotes(), and keyPressEvent().
desiredPlayModeForAccompany()
Song::PlayMode lmms::gui::PianoRoll::desiredPlayModeForAccompany () const
Definition at line 4095 of file PianoRoll.cpp.
References lmms::Song::Song, desiredPlayModeForAccompany(), m_midiClip, lmms::Song::Pattern, and lmms::Engine::patternStore().
Referenced by desiredPlayModeForAccompany(), finishRecordNote(), and startRecordNote().
dragNotes()
void lmms::gui::PianoRoll::dragNotes (int x, int y, bool alt, bool shift, bool ctrl) private
Definition at line 2898 of file PianoRoll.cpp.
References lmms::DefaultTicksPerBar, dragNotes(), getKey(), getSelectedNotes(), lmms::Engine::getSong(), lmms::TimePos::getTicks(), lmms::Note::length(), m_action, m_currentNote, m_currentPosition, m_gridMode, m_lenOfNewNotes, m_midiClip, m_minResizeLen, m_mouseDownKey, m_mouseDownTick, m_moveBoundaryBottom, m_moveBoundaryLeft, m_moveBoundaryTop, m_moveStartX, m_moveStartY, m_ppb, m_startedWithShift, m_startKey, MoveNote, Nudge, lmms::NumKeys, lmms::Note::oldLength(), lmms::Note::oldPos(), lmms::Note::pos(), quantization(), lmms::TimePos::quantize(), lmms::Note::quantized(), ResizeNote, selectionCount(), lmms::Song::setModified(), Snap, and lmms::TimePos::ticksPerBar().
Referenced by dragNotes(), keyPressEvent(), and mouseMoveEvent().
drawDetuningInfo()
void lmms::gui::PianoRoll::drawDetuningInfo (QPainter & _p, const Note * _n, int _x, int _y) const private
Definition at line 1082 of file PianoRoll.cpp.
References lmms::AutomationClip::CubicHermite, lmms::Note::detuning(), lmms::AutomationClip::Discrete, drawDetuningInfo(), lmms::INVAL(), keyAreaBottom(), lmms::AutomationClip::Linear, m_keyLineHeight, m_noteColor, m_ppb, m_whiteKeyWidth, lmms::OUTVAL(), lmms::POS(), lmms::gui::PR_TOP_MARGIN, and lmms::TimePos::ticksPerBar().
Referenced by drawDetuningInfo(), and paintEvent().
drawNoteRect()
void lmms::gui::PianoRoll::drawNoteRect (QPainter & p, int x, int y, int width, const Note * n, const QColor & noteCol, const QColor & noteTextColor, const QColor & selCol, const int noteOpc, const bool borderless, bool drawNoteName) protected
Definition at line 972 of file PianoRoll.cpp.
References lmms::gui::adjustedToPixelSize(), drawNoteRect(), lmms::gui::getNoteString(), lmms::Note::getPanning(), lmms::Note::getVolume(), lmms::Note::key(), m_keyLineHeight, lmms::MaxVolume, lmms::MinVolume, noteTextColor, lmms::PanningLeft, lmms::PanningRight, and lmms::Note::selected().
Referenced by drawNoteRect(), and paintEvent().
enterValue()
void lmms::gui::PianoRoll::enterValue (NoteVector * nv) protected
Definition at line 4400 of file PianoRoll.cpp.
References enterValue(), m_lastNotePanning, m_lastNoteVolume, m_noteEditMode, lmms::MaxVolume, lmms::MinVolume, Panning, lmms::PanningLeft, lmms::PanningRight, and Volume.
Referenced by enterValue(), and mouseDoubleClickEvent().
finishRecordNote
void lmms::gui::PianoRoll::finishRecordNote (const lmms::Note & n) protected slot
Definition at line 4245 of file PianoRoll.cpp.
References desiredPlayModeForAccompany(), lmms::Note::detuning(), finishRecordNote(), lmms::Engine::getSong(), hasValidMidiClip(), lmms::Note::key(), lmms::Note::length(), m_doAutoQuantization, m_midiClip, m_recording, m_recordingNotes, m_stepRecorder, lmms::Song::MidiClip, quantization(), lmms::Note::quantizeLength(), and lmms::Note::quantizePos().
Referenced by finishRecordNote(), and setCurrentMidiClip().
fitNoteLengths
void lmms::gui::PianoRoll::fitNoteLengths (bool fill) protected slot
Definition at line 704 of file PianoRoll.cpp.
References fitNoteLengths(), lmms::gui::getGUI(), getSelectedNotes(), lmms::Engine::getSong(), hasValidMidiClip(), lmms::Note::lessThan(), m_midiClip, lmms::Song::setModified(), and lmms::TimePos::ticksPerBar().
Referenced by fitNoteLengths().
focusInEvent()
void lmms::gui::PianoRoll::focusInEvent (QFocusEvent * ev) override protected
Definition at line 4044 of file PianoRoll.cpp.
References focusInEvent(), hasValidMidiClip(), and m_midiClip.
Referenced by focusInEvent().
focusOutEvent()
void lmms::gui::PianoRoll::focusOutEvent (QFocusEvent *) override protected
Definition at line 4018 of file PianoRoll.cpp.
References focusOutEvent(), hasValidMidiClip(), i, Knife, m_action, m_ctrlMode, m_editMode, m_knifeMode, m_midiClip, m_strumMode, lmms::MidiNoteOff, None, lmms::NumKeys, and Strum.
Referenced by focusOutEvent().
getAllOctavesForKey()
QList< int > lmms::gui::PianoRoll::getAllOctavesForKey (int keyToMirror) const private
Definition at line 4082 of file PianoRoll.cpp.
References getAllOctavesForKey(), i, lmms::NumKeys, and trackOctaveSize().
Referenced by getAllOctavesForKey(), and markSemiTone().
getKey()
int lmms::gui::PianoRoll::getKey (int y) const private
Definition at line 4056 of file PianoRoll.cpp.
References getKey(), keyAreaBottom(), m_keyLineHeight, m_startKey, and lmms::NumKeys.
Referenced by dragNotes(), getKey(), mouseMoveEvent(), mousePressEvent(), noteUnderMouse(), and paintEvent().
getSelectedNotes()
NoteVector lmms::gui::PianoRoll::getSelectedNotes () const protected
Definition at line 4371 of file PianoRoll.cpp.
References getSelectedNotes(), hasValidMidiClip(), and m_midiClip.
Referenced by constrainNoteLengths(), copySelectedNotes(), cutSelectedNotes(), deleteSelectedNotes(), dragNotes(), fitNoteLengths(), getSelectedNotes(), glueNotes(), mousePressEvent(), mouseReleaseEvent(), quantizeNotes(), reverseNotes(), selectionCount(), setupSelectedChords(), shiftPos(), and shiftSemiTone().
ghostClipSet
void lmms::gui::PianoRoll::ghostClipSet (bool) signal
Referenced by clearGhostClip(), loadGhostNotes(), and setGhostMidiClip().
ghostNotes()
const NoteVector & lmms::gui::PianoRoll::ghostNotes () const inline private
Definition at line 376 of file PianoRoll.h.
References m_ghostNotes.
glueNotes
void lmms::gui::PianoRoll::glueNotes () protected slot
Definition at line 642 of file PianoRoll.cpp.
References getSelectedNotes(), hasValidMidiClip(), i, lmms::Note::key(), and m_midiClip.
hasValidMidiClip()
bool lmms::gui::PianoRoll::hasValidMidiClip () const inline
Definition at line 149 of file PianoRoll.h.
References m_midiClip.
Referenced by computeSelectedNotes(), constrainNoteLengths(), cutSelectedNotes(), deleteSelectedNotes(), finishRecordNote(), fitNoteLengths(), focusInEvent(), focusOutEvent(), getSelectedNotes(), glueNotes(), keyPressEvent(), keyReleaseEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mouseOverNote(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), pasteNotes(), play(), quantizeNotes(), record(), recordAccompany(), reverseNotes(), selectAll(), selectNotesOnKey(), setCurrentMidiClip(), setupSelectedChords(), shiftPos(), shiftSemiTone(), startRecordNote(), toggleStepRecording(), updatePositionAccompany(), updateStrumPos(), and wheelEvent().
hideMidiClip
void lmms::gui::PianoRoll::hideMidiClip (lmms::MidiClip * clip) protected slot
Definition at line 916 of file PianoRoll.cpp.
References hideMidiClip(), m_midiClip, and setCurrentMidiClip().
Referenced by hideMidiClip(), and setCurrentMidiClip().
horScrolled
void lmms::gui::PianoRoll::horScrolled (int new_pos) protected slot
Definition at line 4287 of file PianoRoll.cpp.
References horScrolled(), m_currentPosition, m_stepRecorderWidget, and positionChanged().
Referenced by PianoRoll(), and horScrolled().
isRecording()
bool lmms::gui::PianoRoll::isRecording () const inline
Definition at line 134 of file PianoRoll.h.
References m_recording.
isSelection()
bool lmms::gui::PianoRoll::isSelection () const private
Definition at line 1249 of file PianoRoll.cpp.
References isSelection(), and m_midiClip.
Referenced by isSelection(), mouseDoubleClickEvent(), and mouseMoveEvent().
isStepRecording()
bool lmms::gui::PianoRoll::isStepRecording () const inline
Definition at line 139 of file PianoRoll.h.
References m_stepRecorder.
keyAreaBottom()
int lmms::gui::PianoRoll::keyAreaBottom () const private
Definition at line 1617 of file PianoRoll.cpp.
References keyAreaBottom(), m_notesEditHeight, and lmms::gui::PR_BOTTOM_MARGIN.
Referenced by drawDetuningInfo(), getKey(), keyAreaBottom(), mouseMoveEvent(), mousePressEvent(), noteEditTop(), noteUnderMouse(), paintEvent(), updateKnifePos(), updatePositionLineHeight(), updateScrollbars(), updateYScroll(), and yCoordOfKey().
keyAreaTop()
int lmms::gui::PianoRoll::keyAreaTop () const private
Definition at line 1609 of file PianoRoll.cpp.
References keyAreaTop(), and lmms::gui::PR_TOP_MARGIN.
Referenced by keyAreaTop(), paintEvent(), updatePosition(), updatePositionLineHeight(), and updateYScroll().
keyChanged
void lmms::gui::PianoRoll::keyChanged () protected slot
Definition at line 4732 of file PianoRoll.cpp.
References keyChanged(), MarkCurrentScale, and markSemiTone().
Referenced by PianoRoll(), and keyChanged().
keyPressEvent()
void lmms::gui::PianoRoll::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 1271 of file PianoRoll.cpp.
References cancelKnifeAction(), cancelStrumAction(), clearSelectedNotes(), cm_scrollAmtHoriz, cm_scrollAmtVert, deleteSelectedNotes(), dragNotes(), lmms::gui::PianoView::getKeyFromKeyEvent(), hasValidMidiClip(), keyPressEvent(), Knife, m_action, m_ctrlMode, m_editMode, m_lastMouseX, m_lastMouseY, m_leftRightScroll, m_midiClip, m_noteLenModel, m_quantizeModel, m_stepRecorder, m_timeLine, m_topBottomScroll, MoveNote, None, playChordNotes(), quantization(), ResizeNote, Select, selectAll(), setCurrentMidiClip(), shiftPos(), shiftSemiTone(), Strum, and lmms::TimePos::ticksPerBar().
Referenced by keyPressEvent().
keyReleaseEvent()
void lmms::gui::PianoRoll::keyReleaseEvent (QKeyEvent * ke) override protected
Definition at line 1520 of file PianoRoll.cpp.
References computeSelectedNotes(), lmms::gui::PianoView::getKeyFromKeyEvent(), hasValidMidiClip(), keyReleaseEvent(), Knife, m_ctrlMode, m_editMode, m_midiClip, pauseChordNotes(), setupSelectedChords(), and Strum.
Referenced by keyReleaseEvent().
leaveEvent()
void lmms::gui::PianoRoll::leaveEvent (QEvent * e) override protected
Definition at line 1567 of file PianoRoll.cpp.
References leaveEvent(), and s_textFloat.
Referenced by leaveEvent().
loadGhostNotes()
void lmms::gui::PianoRoll::loadGhostNotes (const QDomElement & de)
Definition at line 615 of file PianoRoll.cpp.
References lmms::DefaultVolume, ghostClipSet(), m_ghostNotes, and lmms::SerializingObject::restoreState().
loadMarkedSemiTones()
void lmms::gui::PianoRoll::loadMarkedSemiTones (const QDomElement & de)
Definition at line 796 of file PianoRoll.cpp.
References loadMarkedSemiTones(), and m_markedSemiTones.
Referenced by loadMarkedSemiTones().
markSemiTone
void lmms::gui::PianoRoll::markSemiTone (SemiToneMarkerAction i, bool fromMenu = true) protected slot
Definition at line 495 of file PianoRoll.cpp.
References CopyAllNotesOnKey, getAllOctavesForKey(), lmms::InstrumentFunctionNoteStacking::ChordTable::getChordByName(), lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance(), lmms::InstrumentFunctionNoteStacking::ChordTable::getScaleByName(), lmms::InstrumentFunctionNoteStacking::Chord::hasSemiTone(), i, lmms::InstrumentFunctionNoteStacking::Chord::isEmpty(), lmms::InstrumentFunctionNoteStacking::Chord::isScale(), lmms::InstrumentFunctionNoteStacking::Chord::last(), m_chordModel, m_keyModel, m_markedSemiTones, m_pianoKeySelected, m_scaleModel, MarkAllOctaveSemiTones, MarkCurrentChord, MarkCurrentScale, MarkCurrentSemiTone, lmms::NumKeys, selectNotesOnKey(), trackOctaveSize(), and UnmarkAll.
Referenced by PianoRoll(), and keyChanged().
mouseDoubleClickEvent()
void lmms::gui::PianoRoll::mouseDoubleClickEvent (QMouseEvent * me) override protected
Definition at line 2009 of file PianoRoll.cpp.
References enterValue(), lmms::TimePos::getTicks(), hasValidMidiClip(), i, isSelection(), m_currentPosition, m_midiClip, m_ppb, m_whiteKeyWidth, mouseDoubleClickEvent(), noteEditBottom(), noteEditLeft(), noteEditRight(), noteEditTop(), lmms::Note::pos(), and lmms::TimePos::ticksPerBar().
Referenced by mouseDoubleClickEvent().
mouseMoveEvent()
void lmms::gui::PianoRoll::mouseMoveEvent (QMouseEvent * me) override protected
Definition at line 2402 of file PianoRoll.cpp.
References ChangeNoteProperty, lmms::DefaultPanning, lmms::DefaultVolume, dragNotes(), Draw, Erase, getKey(), lmms::Engine::getSong(), hasValidMidiClip(), lmms::Note::isPlaying(), isSelection(), lmms::Note::key(), lmms::gui::KEY_AREA_MIN_HEIGHT, keyAreaBottom(), Knife, lmms::Note::length(), m_action, m_currentPosition, m_editMode, m_lastKey, m_lastMouseX, m_lastMouseY, m_lastNotePanning, m_lastNoteVolume, m_midiClip, m_moveStartY, m_noteEditMode, m_notesEditHeight, m_pianoKeysVisible, m_ppb, m_selectedKeys, m_selectedTick, m_selectStartKey, m_selectStartTick, m_startedWithShift, m_stepRecorderWidget, m_strumEnabled, m_userSetNotesEditHeight, m_whiteKeyWidth, lmms::MaxVolume, lmms::MidiDefaultVelocity, lmms::MidiKeyPressure, lmms::MidiMetaEvent, lmms::MidiNotePanning, lmms::Note::midiVelocity(), lmms::MinVolume, mouseMoveEvent(), MoveNote, None, lmms::gui::NOTE_EDIT_LINE_WIDTH, lmms::gui::NOTE_EDIT_MIN_HEIGHT, noteEditBottom(), noteEditTop(), lmms::NumKeys, Panning, lmms::PanningLeft, lmms::PanningRight, lmms::panningToMidi(), pauseChordNotes(), pauseTestNotes(), lmms::Note::pos(), pos, lmms::gui::PR_BOTTOM_MARGIN, lmms::gui::PR_TOP_MARGIN, lmms::gui::RESIZE_AREA_WIDTH, ResizeNote, ResizeNoteEditArea, Select, lmms::Note::selected(), SelectNotes, lmms::Note::setIsPlaying(), lmms::MidiEvent::setMetaEvent(), lmms::Song::setModified(), lmms::Note::setPanning(), lmms::Note::setVolume(), showPanTextFloat(), showVolTextFloat(), Strum, testPlayKey(), testPlayNote(), lmms::TimePos::ticksPerBar(), updateKnifePos(), updatePositionLineHeight(), updateScrollbars(), updateStrumPos(), Volume, and lmms::Note::withinRange().
Referenced by mouseMoveEvent(), and mousePressEvent().
mouseOverNote()
bool lmms::gui::PianoRoll::mouseOverNote () private
Definition at line 4832 of file PianoRoll.cpp.
References hasValidMidiClip(), mouseOverNote(), and noteUnderMouse().
Referenced by mouseOverNote().
mousePressEvent()
void lmms::gui::PianoRoll::mousePressEvent (QMouseEvent * me) override protected
Definition at line 1625 of file PianoRoll.cpp.
References clearSelectedNotes(), Count, lmms::Note::createDetuning(), Detuning, lmms::Note::detuning(), Draw, Erase, lmms::InstrumentFunctionNoteStacking::ChordTable::getChordByName(), lmms::gui::getGUI(), lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance(), getKey(), lmms::Note::getPanning(), getSelectedNotes(), lmms::Engine::getSong(), lmms::Note::getVolume(), hasValidMidiClip(), i, lmms::InstrumentFunctionNoteStacking::Chord::isEmpty(), lmms::Note::key(), keyAreaBottom(), Knife, lmms::Note::length(), m_action, m_chordModel, m_ctrlMode, m_currentNote, m_currentPosition, m_editMode, m_knifeDown, m_lastKey, m_lastNotePanning, m_lastNoteVolume, m_lenOfNewNotes, m_midiClip, m_minResizeLen, m_mouseDownKey, m_mouseDownRight, m_mouseDownTick, m_moveBoundaryBottom, m_moveBoundaryLeft, m_moveBoundaryRight, m_moveBoundaryTop, m_moveStartX, m_moveStartY, m_noteEditMenu, m_noteEditMode, m_pianoKeySelected, m_ppb, m_selectedKeys, m_selectedTick, m_selectStartKey, m_selectStartTick, m_semiToneMarkerMenu, m_startedWithShift, m_startKey, m_strumEnabled, m_whiteKeyWidth, lmms::MidiDefaultVelocity, mouseMoveEvent(), mousePressEvent(), MoveNote, newNoteLen(), lmms::gui::NOTE_EDIT_LINE_WIDTH, noteEditTop(), noteUnderMouse(), playChordNotes(), lmms::Note::pos(), pos, lmms::gui::PR_TOP_MARGIN, quantization(), lmms::gui::RESIZE_AREA_WIDTH, ResizeNote, ResizeNoteEditArea, Select, SelectNotes, lmms::Song::setModified(), lmms::Note::setPanning(), lmms::Note::setSelected(), lmms::Note::setVolume(), lmms::InstrumentFunctionNoteStacking::Chord::size(), Strum, testPlayNote(), lmms::TimePos::ticksPerBar(), updateKnifePos(), and updateStrumPos().
Referenced by mousePressEvent().
mouseReleaseEvent()
void lmms::gui::PianoRoll::mouseReleaseEvent (QMouseEvent * me) override protected
Definition at line 2297 of file PianoRoll.cpp.
References cancelKnifeAction(), cancelStrumAction(), clearSelectedNotes(), computeSelectedNotes(), Draw, getSelectedNotes(), hasValidMidiClip(), Knife, m_action, m_currentNote, m_editMode, m_knifeDown, m_knifeEndKey, m_knifeEndTickPos, m_knifeStartKey, m_knifeStartTickPos, m_lastKey, m_midiClip, m_mouseDownRight, m_strumEnabled, mouseReleaseEvent(), MoveNote, None, pauseChordNotes(), ResizeNote, s_textFloat, Select, selectionCount(), SelectNotes, and Strum.
Referenced by mouseReleaseEvent().
newNoteLen()
TimePos lmms::gui::PianoRoll::newNoteLen () const private
Definition at line 4818 of file PianoRoll.cpp.
References lmms::DefaultTicksPerBar, m_lenOfNewNotes, m_noteLenModel, and newNoteLen().
Referenced by mousePressEvent(), newNoteLen(), noteLengthChanged(), quantization(), and toggleStepRecording().
noteEditBottom()
int lmms::gui::PianoRoll::noteEditBottom () const private
Definition at line 1585 of file PianoRoll.cpp.
References noteEditBottom(), and lmms::gui::PR_BOTTOM_MARGIN.
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), noteEditBottom(), paintEvent(), and wheelEvent().
noteEditLeft()
int lmms::gui::PianoRoll::noteEditLeft () const private
Definition at line 1601 of file PianoRoll.cpp.
References m_whiteKeyWidth, and noteEditLeft().
Referenced by mouseDoubleClickEvent(), noteEditLeft(), paintEvent(), and wheelEvent().
noteEditRight()
int lmms::gui::PianoRoll::noteEditRight () const private
Definition at line 1593 of file PianoRoll.cpp.
References noteEditRight(), and lmms::gui::PR_RIGHT_MARGIN.
Referenced by mouseDoubleClickEvent(), noteEditRight(), and wheelEvent().
noteEditTop()
int lmms::gui::PianoRoll::noteEditTop () const private
Definition at line 1577 of file PianoRoll.cpp.
References keyAreaBottom(), lmms::gui::NOTE_EDIT_RESIZE_BAR, and noteEditTop().
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), noteEditTop(), paintEvent(), and wheelEvent().
noteLengthChanged
void lmms::gui::PianoRoll::noteLengthChanged () protected slot
Definition at line 4726 of file PianoRoll.cpp.
References m_stepRecorder, newNoteLen(), and noteLengthChanged().
Referenced by PianoRoll(), and noteLengthChanged().
noteUnderMouse()
Note * lmms::gui::PianoRoll::noteUnderMouse () private
Definition at line 4840 of file PianoRoll.cpp.
References getKey(), keyAreaBottom(), m_currentPosition, m_midiClip, m_ppb, m_whiteKeyWidth, noteUnderMouse(), pos, lmms::gui::PR_TOP_MARGIN, lmms::gui::SCROLLBAR_SIZE, and lmms::TimePos::ticksPerBar().
Referenced by mouseOverNote(), mousePressEvent(), noteUnderMouse(), and updateStrumPos().
paintEvent()
void lmms::gui::PianoRoll::paintEvent (QPaintEvent * pe) override protected
Definition at line 3121 of file PianoRoll.cpp.
References lmms::gui::adjustedToPixelSize(), Black, lmms::C, lmms::DefaultTicksPerBar, Detuning, Draw, drawDetuningInfo(), drawNoteRect(), Erase, lmms::F, lmms::gui::getGUI(), getKey(), lmms::gui::getNoteString(), lmms::Engine::getSong(), lmms::Song::getTimeSigModel(), hasValidMidiClip(), lmms::ConfigManager::inst(), lmms::Piano::isWhiteKey(), lmms::gui::KEY_AREA_MIN_HEIGHT, keyAreaBottom(), keyAreaTop(), lmms::KeysPerOctave, Knife, m_action, m_backgroundShade, m_barColor, m_barLineColor, m_beatLineColor, m_blackKeyActiveBackground, m_blackKeyDisabledBackground, m_blackKeyHeight, m_blackKeyInactiveBackground, m_blackKeyWidth, m_currentPosition, m_currentStepNoteColor, m_editMode, m_ghostNoteBorders, m_ghostNoteColor, m_ghostNoteOpacity, m_ghostNotes, m_ghostNoteTextColor, m_keyLineHeight, m_knifeCutLineColor, m_knifeDown, m_knifeEndKey, m_knifeEndTickPos, m_knifeStartKey, m_knifeStartTickPos, m_leftRightScroll, m_lineColor, m_markedSemitoneColor, m_markedSemiTones, m_midiClip, m_mouseDownRight, m_nemStr, m_noteBorders, m_noteColor, m_noteEditMode, m_noteModeColor, m_noteOpacity, m_notesEditHeight, m_noteTextColor, m_outOfBoundsShade, m_pianoKeysVisible, m_ppb, m_selectedKeys, m_selectedNoteColor, m_selectedTick, m_selectStartKey, m_selectStartTick, m_startKey, m_stepNoteColor, m_stepRecorder, m_toolDraw, m_toolErase, m_toolKnife, m_toolMove, m_toolOpen, m_toolSelect, m_toolStrum, m_userSetNotesEditHeight, m_whiteKeyActiveBackground, m_whiteKeyActiveTextColor, m_whiteKeyActiveTextShadow, m_whiteKeyBigHeight, m_whiteKeyDisabledBackground, m_whiteKeyInactiveBackground, m_whiteKeyInactiveTextColor, m_whiteKeyInactiveTextShadow, m_whiteKeySmallHeight, m_whiteKeyWidth, m_zoomingModel, m_zoomingYModel, m_zoomLevels, m_zoomYLevels, lmms::MaxVolume, lmms::MinVolume, MoveNote, lmms::gui::NOTE_EDIT_LINE_WIDTH, lmms::gui::NOTE_EDIT_RESIZE_BAR, noteEditBottom(), noteEditLeft(), noteEditTop(), lmms::NumKeys, paintEvent(), Panning, lmms::PanningLeft, lmms::PanningRight, lmms::gui::PIANO_X, lmms::gui::PR_BOTTOM_MARGIN, lmms::gui::PR_RIGHT_MARGIN, lmms::gui::PR_TOP_MARGIN, prKeyOrder, quantization(), lmms::Note::Regular, ResizeNoteEditArea, Select, SMALL_FONT_SIZE, Strum, lmms::TimePos::ticksPerBar(), lmms::ConfigManager::value(), Volume, WhiteBig, WhiteSmall, and yCoordOfKey().
Referenced by paintEvent().
pasteNotes
void lmms::gui::PianoRoll::pasteNotes () protected slot
Definition at line 4533 of file PianoRoll.cpp.
References lmms::Note::classNodeName(), clearSelectedNotes(), lmms::gui::getGUI(), lmms::Engine::getSong(), hasValidMidiClip(), i, m_midiClip, m_timeLine, pasteNotes(), lmms::Note::pos(), quantization(), lmms::Note::quantized(), lmms::SerializingObject::restoreState(), lmms::Song::setModified(), lmms::Note::setPos(), and lmms::Note::setSelected().
Referenced by pasteNotes().
pauseChordNotes()
void lmms::gui::PianoRoll::pauseChordNotes (int key) private
Definition at line 2146 of file PianoRoll.cpp.
References lmms::InstrumentFunctionNoteStacking::ChordTable::getChordByName(), lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance(), lmms::Piano::handleKeyRelease(), i, lmms::InstrumentFunctionNoteStacking::Chord::isEmpty(), m_chordModel, m_midiClip, pauseChordNotes(), and lmms::InstrumentFunctionNoteStacking::Chord::size().
Referenced by keyReleaseEvent(), mouseMoveEvent(), mouseReleaseEvent(), pauseChordNotes(), pauseTestNotes(), and testPlayKey().
pauseTestNotes()
void lmms::gui::PianoRoll::pauseTestNotes (bool pause = true) private
Definition at line 2106 of file PianoRoll.cpp.
References m_midiClip, pauseChordNotes(), pauseTestNotes(), and testPlayNote().
Referenced by mouseMoveEvent(), and pauseTestNotes().
play
void lmms::gui::PianoRoll::play () protected slot
Definition at line 4107 of file PianoRoll.cpp.
References lmms::Engine::getSong(), hasValidMidiClip(), m_midiClip, lmms::Song::MidiClip, play(), lmms::Song::playMidiClip(), and lmms::Song::togglePause().
Referenced by play().
playChordNotes()
void lmms::gui::PianoRoll::playChordNotes (int key, int velocity = -1) private
Definition at line 2130 of file PianoRoll.cpp.
References lmms::InstrumentFunctionNoteStacking::ChordTable::getChordByName(), lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance(), lmms::Piano::handleKeyPress(), i, lmms::InstrumentFunctionNoteStacking::Chord::isEmpty(), m_chordModel, m_midiClip, playChordNotes(), and lmms::InstrumentFunctionNoteStacking::Chord::size().
Referenced by keyPressEvent(), mousePressEvent(), playChordNotes(), testPlayKey(), and testPlayNote().
positionChanged
void lmms::gui::PianoRoll::positionChanged (const lmms::TimePos &) signal
Referenced by PianoRoll(), and horScrolled().
quantization()
int lmms::gui::PianoRoll::quantization () const
Definition at line 4737 of file PianoRoll.cpp.
References lmms::DefaultTicksPerBar, m_noteLenModel, m_quantizeModel, newNoteLen(), quantization(), and lmms::gui::Quantizations.
Referenced by dragNotes(), finishRecordNote(), keyPressEvent(), mousePressEvent(), paintEvent(), pasteNotes(), quantization(), quantizeNotes(), and updateKnifePos().
quantizeChanged
void lmms::gui::PianoRoll::quantizeChanged () protected slot
Definition at line 4721 of file PianoRoll.cpp.
References quantizeChanged().
Referenced by PianoRoll(), and quantizeChanged().
quantizeNotes
void lmms::gui::PianoRoll::quantizeNotes (QuantizeAction mode = QuantizeAction::Both) protected slot
Definition at line 4755 of file PianoRoll.cpp.
References Both, lmms::gui::getGUI(), getSelectedNotes(), lmms::Engine::getSong(), hasValidMidiClip(), Length, m_midiClip, Pos, quantization(), lmms::Note::quantizeLength(), quantizeNotes(), lmms::Note::quantizePos(), and lmms::Song::setModified().
Referenced by quantizeNotes().
record
void lmms::gui::PianoRoll::record () protected slot
Definition at line 4127 of file PianoRoll.cpp.
References lmms::Engine::getSong(), hasValidMidiClip(), m_midiClip, m_recording, lmms::Song::playMidiClip(), record(), and stop().
Referenced by record().
recordAccompany
void lmms::gui::PianoRoll::recordAccompany () protected slot
Definition at line 4147 of file PianoRoll.cpp.
References lmms::Engine::getSong(), hasValidMidiClip(), m_midiClip, m_recording, lmms::Song::playPattern(), lmms::Song::playSong(), recordAccompany(), and stop().
Referenced by recordAccompany().
removeSelection()
void lmms::gui::PianoRoll::removeSelection () protected
Definition at line 1164 of file PianoRoll.cpp.
References m_selectedKeys, m_selectedTick, m_selectStartKey, m_selectStartTick, and removeSelection().
Referenced by PianoRoll(), computeSelectedNotes(), and removeSelection().
reset()
void lmms::gui::PianoRoll::reset ()
Resets settings to default when e.g.
creating a new project
Definition at line 444 of file PianoRoll.cpp.
References clearGhostClip(), lmms::DefaultPanning, lmms::DefaultVolume, m_lastNotePanning, and m_lastNoteVolume.
resizeEvent()
void lmms::gui::PianoRoll::resizeEvent (QResizeEvent * re) override protected
Definition at line 3855 of file PianoRoll.cpp.
References m_timeLine, resizeEvent(), updatePositionLineHeight(), and updateScrollbars().
Referenced by resizeEvent(), and setCurrentMidiClip().
reverseNotes
void lmms::gui::PianoRoll::reverseNotes () protected slot
Definition at line 781 of file PianoRoll.cpp.
References lmms::gui::getGUI(), getSelectedNotes(), lmms::Engine::getSong(), hasValidMidiClip(), m_midiClip, reverseNotes(), and lmms::Song::setModified().
Referenced by reverseNotes().
selectAll()
void lmms::gui::PianoRoll::selectAll () protected
Definition at line 4317 of file PianoRoll.cpp.
References hasValidMidiClip(), m_midiClip, m_selectedKeys, m_selectedTick, m_selectStartKey, m_selectStartTick, and selectAll().
Referenced by keyPressEvent(), and selectAll().
selectionCount()
int lmms::gui::PianoRoll::selectionCount () const private
Definition at line 1264 of file PianoRoll.cpp.
References getSelectedNotes(), and selectionCount().
Referenced by dragNotes(), mouseReleaseEvent(), and selectionCount().
selectNotesOnKey()
void lmms::gui::PianoRoll::selectNotesOnKey () protected
Definition at line 4389 of file PianoRoll.cpp.
References hasValidMidiClip(), m_lastKey, m_midiClip, and selectNotesOnKey().
Referenced by markSemiTone(), and selectNotesOnKey().
selectRegionFromPixels
void lmms::gui::PianoRoll::selectRegionFromPixels (int xStart, int xEnd) protected slot
Definition at line 933 of file PianoRoll.cpp.
References computeSelectedNotes(), m_currentPosition, m_ppb, m_selectedKeys, m_selectedTick, m_selectStartKey, m_selectStartTick, m_whiteKeyWidth, selectRegionFromPixels(), and lmms::TimePos::ticksPerBar().
Referenced by PianoRoll(), and selectRegionFromPixels().
semiToneMarkerMenuChordSetEnabled
void lmms::gui::PianoRoll::semiToneMarkerMenuChordSetEnabled (bool) signal
Referenced by PianoRoll(), and updateSemiToneMarkerMenu().
semiToneMarkerMenuScaleSetEnabled
void lmms::gui::PianoRoll::semiToneMarkerMenuScaleSetEnabled (bool) signal
Referenced by PianoRoll(), and updateSemiToneMarkerMenu().
setCurrentMidiClip()
void lmms::gui::PianoRoll::setCurrentMidiClip (MidiClip * newMidiClip)
Definition at line 822 of file PianoRoll.cpp.
References currentMidiClipChanged(), finishRecordNote(), lmms::Song::getPlayPos(), lmms::Engine::getSong(), hasValidMidiClip(), hideMidiClip(), lmms::gui::INITIAL_START_KEY, lmms::Clip::lengthChanged(), m_currentNote, m_currentPosition, m_leftRightScroll, m_midiClip, m_startKey, m_stepRecorder, m_totalKeysToScroll, lmms::Song::MidiClip, lmms::NumKeys, lmms::Song::playMidiClip(), resizeEvent(), setCurrentMidiClip(), lmms::TimePos::setTicks(), startRecordNote(), and lmms::TimePos::ticksPerBar().
Referenced by hideMidiClip(), keyPressEvent(), and setCurrentMidiClip().
setEditMode
void lmms::gui::PianoRoll::setEditMode (int mode) protected slot
Definition at line 4309 of file PianoRoll.cpp.
References m_ctrlMode, m_editMode, and setEditMode().
Referenced by setEditMode().
setGhostMidiClip()
void lmms::gui::PianoRoll::setGhostMidiClip (MidiClip * newMidiClip)
Definition at line 599 of file PianoRoll.cpp.
References ghostClipSet(), m_ghostNotes, and lmms::MidiClip::notes().
Referenced by clearGhostClip().
setKnifeAction()
void lmms::gui::PianoRoll::setKnifeAction () private
Definition at line 2162 of file PianoRoll.cpp.
References Knife, m_action, m_editMode, m_knifeDown, m_knifeMode, and setKnifeAction().
Referenced by lmms::gui::PianoRollWindow::PianoRollWindow(), and setKnifeAction().
setStrumAction()
void lmms::gui::PianoRoll::setStrumAction () private
Definition at line 2183 of file PianoRoll.cpp.
References m_action, m_editMode, m_strumEnabled, m_strumMode, setStrumAction(), setupSelectedChords(), and Strum.
Referenced by lmms::gui::PianoRollWindow::PianoRollWindow(), and setStrumAction().
setupSelectedChords()
void lmms::gui::PianoRoll::setupSelectedChords () private
Computes which notes belong to which chords from the selection.
Definition at line 2787 of file PianoRoll.cpp.
References getSelectedNotes(), hasValidMidiClip(), m_midiClip, m_selectedChords, and setupSelectedChords().
Referenced by keyReleaseEvent(), setStrumAction(), and setupSelectedChords().
shiftPos() [1/2]
void lmms::gui::PianoRoll::shiftPos (const NoteVector & notes, int amount) private
Definition at line 1223 of file PianoRoll.cpp.
References lmms::gui::getGUI(), m_midiClip, and shiftPos().
shiftPos() [2/2]
void lmms::gui::PianoRoll::shiftPos (int amount) private
Definition at line 1213 of file PianoRoll.cpp.
References getSelectedNotes(), hasValidMidiClip(), m_midiClip, and shiftPos().
Referenced by keyPressEvent(), shiftPos(), and shiftPos().
shiftSemiTone() [1/2]
void lmms::gui::PianoRoll::shiftSemiTone (const NoteVector & notes, int amount) private
Definition at line 1198 of file PianoRoll.cpp.
References lmms::gui::getGUI(), m_midiClip, and shiftSemiTone().
shiftSemiTone() [2/2]
void lmms::gui::PianoRoll::shiftSemiTone (int amount) private
Definition at line 1188 of file PianoRoll.cpp.
References getSelectedNotes(), hasValidMidiClip(), m_midiClip, and shiftSemiTone().
Referenced by keyPressEvent(), shiftSemiTone(), and shiftSemiTone().
showPanTextFloat()
void lmms::gui::PianoRoll::showPanTextFloat (panning_t pan, const QPoint & pos, int timeout = -1)
Definition at line 468 of file PianoRoll.cpp.
References pos, and showTextFloat().
Referenced by mouseMoveEvent(), and wheelEvent().
showTextFloat()
void lmms::gui::PianoRoll::showTextFloat (const QString & text, const QPoint & pos, int timeout = -1)
Definition at line 451 of file PianoRoll.cpp.
References pos, and s_textFloat.
Referenced by showPanTextFloat(), and showVolTextFloat().
showVolTextFloat()
void lmms::gui::PianoRoll::showVolTextFloat (volume_t vol, const QPoint & pos, int timeout = -1)
Todo
display velocity for MIDI-based instruments
Definition at line 460 of file PianoRoll.cpp.
References pos, and showTextFloat().
Referenced by mouseMoveEvent(), and wheelEvent().
startRecordNote
void lmms::gui::PianoRoll::startRecordNote (const lmms::Note & n) protected slot
Definition at line 4213 of file PianoRoll.cpp.
References lmms::Song::Song, desiredPlayModeForAccompany(), lmms::Note::getPanning(), lmms::Engine::getSong(), lmms::Note::getVolume(), hasValidMidiClip(), lmms::Note::key(), m_midiClip, m_recording, m_recordingNotes, m_stepRecorder, lmms::Song::MidiClip, lmms::Note::pos(), and startRecordNote().
Referenced by setCurrentMidiClip(), and startRecordNote().
stop
void lmms::gui::PianoRoll::stop () protected slot
Definition at line 4203 of file PianoRoll.cpp.
References lmms::gui::TimeLineWidget::Disabled, lmms::Engine::getSong(), m_recording, m_scrollBack, m_timeLine, stop(), and lmms::Song::stop().
Referenced by record(), recordAccompany(), and stop().
stopRecording()
void lmms::gui::PianoRoll::stopRecording () inline
Definition at line 129 of file PianoRoll.h.
References m_recording.
testPlayKey()
void lmms::gui::PianoRoll::testPlayKey (int _key, int _vol, int _pan) private
Definition at line 2205 of file PianoRoll.cpp.
References lmms::Piano::handleKeyPress(), lmms::Piano::handleKeyRelease(), m_lastKey, m_midiClip, pauseChordNotes(), playChordNotes(), and testPlayKey().
Referenced by mouseMoveEvent(), and testPlayKey().
testPlayNote()
void lmms::gui::PianoRoll::testPlayNote (Note * n) private
Definition at line 2080 of file PianoRoll.cpp.
References lmms::Note::getPanning(), lmms::Note::isPlaying(), lmms::Note::key(), m_lastKey, m_midiClip, m_recording, m_stepRecorder, lmms::MidiMetaEvent, lmms::MidiNotePanning, lmms::Note::midiVelocity(), lmms::panningToMidi(), playChordNotes(), lmms::Note::setIsPlaying(), and testPlayNote().
Referenced by mouseMoveEvent(), mousePressEvent(), pauseTestNotes(), and testPlayNote().
toggleStepRecording
bool lmms::gui::PianoRoll::toggleStepRecording () protected slot
Definition at line 4174 of file PianoRoll.cpp.
References lmms::Engine::getSong(), hasValidMidiClip(), m_stepRecorder, lmms::Song::MidiClip, newNoteLen(), and toggleStepRecording().
Referenced by toggleStepRecording().
trackOctaveSize()
int lmms::gui::PianoRoll::trackOctaveSize () const
Definition at line 925 of file PianoRoll.cpp.
References lmms::KeysPerOctave, m_midiClip, and trackOctaveSize().
Referenced by getAllOctavesForKey(), markSemiTone(), and trackOctaveSize().
updateKnifePos()
void lmms::gui::PianoRoll::updateKnifePos (QMouseEvent * me, bool initial) private
Definition at line 2758 of file PianoRoll.cpp.
References keyAreaBottom(), m_currentPosition, m_keyLineHeight, m_knifeEndKey, m_knifeEndTickPos, m_knifeStartKey, m_knifeStartTickPos, m_ppb, m_startKey, m_whiteKeyWidth, quantization(), lmms::TimePos::ticksPerBar(), and updateKnifePos().
Referenced by mouseMoveEvent(), mousePressEvent(), and updateKnifePos().
updatePosition
void lmms::gui::PianoRoll::updatePosition (const lmms::TimePos & t) protected slot
Definition at line 4630 of file PianoRoll.cpp.
References autoScroll(), lmms::gui::TimeLineWidget::Disabled, lmms::Engine::getSong(), keyAreaTop(), m_currentPosition, m_positionLine, m_ppb, m_scrollBack, m_timeLine, m_whiteKeyWidth, lmms::Song::MidiClip, pos, lmms::TimePos::ticksPerBar(), and updatePosition().
Referenced by PianoRoll(), and updatePosition().
updatePositionAccompany
void lmms::gui::PianoRoll::updatePositionAccompany (const lmms::TimePos & t) protected slot
Definition at line 4665 of file PianoRoll.cpp.
References autoScroll(), lmms::Song::getPlayPos(), lmms::Engine::getSong(), hasValidMidiClip(), m_midiClip, m_recording, lmms::Song::MidiClip, lmms::Song::Pattern, lmms::Song::playMode(), pos, lmms::TimePos::setTicks(), and updatePositionAccompany().
Referenced by PianoRoll(), and updatePositionAccompany().
updatePositionLineHeight()
void lmms::gui::PianoRoll::updatePositionLineHeight () private
Definition at line 4657 of file PianoRoll.cpp.
References keyAreaBottom(), keyAreaTop(), m_positionLine, and updatePositionLineHeight().
Referenced by mouseMoveEvent(), resizeEvent(), and updatePositionLineHeight().
updatePositionStepRecording
void lmms::gui::PianoRoll::updatePositionStepRecording (const lmms::TimePos & t) protected slot
Definition at line 4686 of file PianoRoll.cpp.
References autoScroll(), m_stepRecorder, and updatePositionStepRecording().
Referenced by PianoRoll(), and updatePositionStepRecording().
updateScrollbars()
void lmms::gui::PianoRoll::updateScrollbars () private
Definition at line 3829 of file PianoRoll.cpp.
References keyAreaBottom(), m_keyLineHeight, m_leftRightScroll, m_startKey, m_topBottomScroll, m_totalKeysToScroll, m_whiteKeyWidth, lmms::NumKeys, lmms::gui::PR_TOP_MARGIN, lmms::gui::SCROLLBAR_SIZE, and updateScrollbars().
Referenced by mouseMoveEvent(), resizeEvent(), and updateScrollbars().
updateSemiToneMarkerMenu
void lmms::gui::PianoRoll::updateSemiToneMarkerMenu () protected slot
Definition at line 4802 of file PianoRoll.cpp.
References lmms::InstrumentFunctionNoteStacking::ChordTable::getChordByName(), lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance(), lmms::InstrumentFunctionNoteStacking::ChordTable::getScaleByName(), lmms::InstrumentFunctionNoteStacking::Chord::isEmpty(), m_chordModel, m_scaleModel, semiToneMarkerMenuChordSetEnabled(), semiToneMarkerMenuScaleSetEnabled(), and updateSemiToneMarkerMenu().
Referenced by PianoRoll(), and updateSemiToneMarkerMenu().
updateStrumPos()
void lmms::gui::PianoRoll::updateStrumPos (QMouseEvent * me, bool initial, bool warp) private
Handles updating all of the note positions when performing a strum.
Definition at line 2823 of file PianoRoll.cpp.
References lmms::fastPow10f(), hasValidMidiClip(), i, m_currentPosition, m_midiClip, m_ppb, m_selectedChords, m_strumCurrentTime, m_strumCurrentVertical, m_strumHeightRatio, m_strumStartTime, m_strumStartVertical, m_whiteKeyWidth, noteUnderMouse(), lmms::TimePos::ticksPerBar(), and updateStrumPos().
Referenced by mouseMoveEvent(), mousePressEvent(), and updateStrumPos().
updateYScroll()
void lmms::gui::PianoRoll::updateYScroll () protected
Definition at line 4445 of file PianoRoll.cpp.
References keyAreaBottom(), keyAreaTop(), m_keyLineHeight, m_startKey, m_topBottomScroll, m_totalKeysToScroll, lmms::NumKeys, lmms::gui::PR_TOP_MARGIN, lmms::gui::SCROLLBAR_SIZE, and updateYScroll().
Referenced by updateYScroll(), and zoomingYChanged().
verScrolled
void lmms::gui::PianoRoll::verScrolled (int new_pos) protected slot
Definition at line 4298 of file PianoRoll.cpp.
References m_startKey, m_totalKeysToScroll, and verScrolled().
Referenced by PianoRoll(), and verScrolled().
wheelEvent()
void lmms::gui::PianoRoll::wheelEvent (QWheelEvent * we) override protected
Definition at line 3872 of file PianoRoll.cpp.
References adjustLeftRightScoll(), lmms::gui::DEFAULT_PR_PPB, hasValidMidiClip(), i, m_currentPosition, m_leftRightScroll, m_midiClip, m_noteEditMode, m_noteLenModel, m_ppb, m_quantizeModel, m_topBottomScroll, m_whiteKeyWidth, m_zoomingModel, m_zoomLevels, lmms::MaxVolume, lmms::MinVolume, noteEditBottom(), noteEditLeft(), noteEditRight(), noteEditTop(), Panning, lmms::PanningLeft, lmms::PanningRight, lmms::position(), showPanTextFloat(), showVolTextFloat(), lmms::TimePos::ticksPerBar(), Volume, and wheelEvent().
Referenced by wheelEvent().
yCoordOfKey()
int lmms::gui::PianoRoll::yCoordOfKey (int key) const private
Definition at line 4072 of file PianoRoll.cpp.
References keyAreaBottom(), m_keyLineHeight, m_startKey, and yCoordOfKey().
Referenced by paintEvent(), and yCoordOfKey().
zoomingChanged
void lmms::gui::PianoRoll::zoomingChanged () protected slot
Definition at line 4695 of file PianoRoll.cpp.
References lmms::gui::DEFAULT_PR_PPB, m_positionLine, m_ppb, m_stepRecorderWidget, m_timeLine, m_zoomingModel, m_zoomLevels, and zoomingChanged().
Referenced by PianoRoll(), and zoomingChanged().
zoomingYChanged
void lmms::gui::PianoRoll::zoomingYChanged () protected slot
Definition at line 4709 of file PianoRoll.cpp.
References lmms::gui::DEFAULT_KEY_LINE_HEIGHT, m_blackKeyHeight, m_keyLineHeight, m_whiteKeyBigHeight, m_whiteKeySmallHeight, m_zoomingYModel, m_zoomYLevels, updateYScroll(), and zoomingYChanged().
Referenced by PianoRoll(), and zoomingYChanged().
Friends And Related Symbol Documentation
PianoRollWindow
friend class PianoRollWindow friend
Definition at line 490 of file PianoRoll.h.
References PianoRollWindow.
Referenced by PianoRollWindow.
Member Data Documentation
cm_scrollAmtHoriz
const int lmms::gui::PianoRoll::cm_scrollAmtHoriz = 10 static private
Definition at line 346 of file PianoRoll.h.
Referenced by keyPressEvent().
cm_scrollAmtVert
const int lmms::gui::PianoRoll::cm_scrollAmtVert = 1 static private
Definition at line 347 of file PianoRoll.h.
Referenced by keyPressEvent().
m_action
Action lmms::gui::PianoRoll::m_action private
Definition at line 392 of file PianoRoll.h.
Referenced by PianoRoll(), cancelKnifeAction(), cancelStrumAction(), dragNotes(), focusOutEvent(), keyPressEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), setKnifeAction(), and setStrumAction().
m_backgroundShade
QColor lmms::gui::PianoRoll::m_backgroundShade private
Definition at line 517 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_barColor
QColor lmms::gui::PianoRoll::m_barColor private
Definition at line 506 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_barLineColor
QColor lmms::gui::PianoRoll::m_barLineColor private
Definition at line 496 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_beatLineColor
QColor lmms::gui::PianoRoll::m_beatLineColor private
Definition at line 497 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_blackKeyActiveBackground
QBrush lmms::gui::PianoRoll::m_blackKeyActiveBackground private
Definition at line 530 of file PianoRoll.h.
Referenced by paintEvent().
m_blackKeyDisabledBackground
QBrush lmms::gui::PianoRoll::m_blackKeyDisabledBackground private
Definition at line 532 of file PianoRoll.h.
Referenced by paintEvent().
m_blackKeyHeight
int lmms::gui::PianoRoll::m_blackKeyHeight private
Definition at line 429 of file PianoRoll.h.
Referenced by PianoRoll(), paintEvent(), and zoomingYChanged().
m_blackKeyInactiveBackground
QBrush lmms::gui::PianoRoll::m_blackKeyInactiveBackground private
Definition at line 531 of file PianoRoll.h.
Referenced by paintEvent().
m_blackKeyWidth
int lmms::gui::PianoRoll::m_blackKeyWidth private
Definition at line 529 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_chordModel
ComboBoxModel lmms::gui::PianoRoll::m_chordModel private
Definition at line 367 of file PianoRoll.h.
Referenced by PianoRoll(), markSemiTone(), mousePressEvent(), pauseChordNotes(), playChordNotes(), and updateSemiToneMarkerMenu().
m_ctrlMode
EditMode lmms::gui::PianoRoll::m_ctrlMode private
Definition at line 444 of file PianoRoll.h.
Referenced by PianoRoll(), focusOutEvent(), keyPressEvent(), keyReleaseEvent(), mousePressEvent(), and setEditMode().
m_currentNote
Note* lmms::gui::PianoRoll::m_currentNote private
Definition at line 391 of file PianoRoll.h.
Referenced by PianoRoll(), dragNotes(), mousePressEvent(), mouseReleaseEvent(), and setCurrentMidiClip().
m_currentPosition
TimePos lmms::gui::PianoRoll::m_currentPosition private
Definition at line 386 of file PianoRoll.h.
Referenced by PianoRoll(), autoScroll(), dragNotes(), horScrolled(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), noteUnderMouse(), paintEvent(), selectRegionFromPixels(), setCurrentMidiClip(), updateKnifePos(), updatePosition(), updateStrumPos(), and wheelEvent().
m_currentStepNoteColor
QColor lmms::gui::PianoRoll::m_currentStepNoteColor private
Definition at line 502 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_doAutoQuantization
bool lmms::gui::PianoRoll::m_doAutoQuantization {false} private
Definition at line 388 of file PianoRoll.h.
Referenced by PianoRoll(), and finishRecordNote().
m_editMode
EditMode lmms::gui::PianoRoll::m_editMode private
Definition at line 443 of file PianoRoll.h.
Referenced by PianoRoll(), cancelKnifeAction(), cancelStrumAction(), focusOutEvent(), keyPressEvent(), keyReleaseEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), setEditMode(), setKnifeAction(), and setStrumAction().
m_ghostNoteBorders
bool lmms::gui::PianoRoll::m_ghostNoteBorders private
Definition at line 516 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_ghostNoteColor
QColor lmms::gui::PianoRoll::m_ghostNoteColor private
Definition at line 504 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_ghostNoteOpacity
int lmms::gui::PianoRoll::m_ghostNoteOpacity private
Definition at line 514 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_ghostNotes
NoteVector lmms::gui::PianoRoll::m_ghostNotes private
Definition at line 374 of file PianoRoll.h.
Referenced by ghostNotes(), loadGhostNotes(), paintEvent(), and setGhostMidiClip().
m_ghostNoteTextColor
QColor lmms::gui::PianoRoll::m_ghostNoteTextColor private
Definition at line 505 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_gridMode
GridMode lmms::gui::PianoRoll::m_gridMode private
Definition at line 394 of file PianoRoll.h.
Referenced by changeSnapMode(), and dragNotes().
m_keyLineHeight
int lmms::gui::PianoRoll::m_keyLineHeight private
Definition at line 426 of file PianoRoll.h.
Referenced by PianoRoll(), drawDetuningInfo(), drawNoteRect(), getKey(), paintEvent(), updateKnifePos(), updateScrollbars(), updateYScroll(), yCoordOfKey(), and zoomingYChanged().
m_keyModel
ComboBoxModel lmms::gui::PianoRoll::m_keyModel private
Definition at line 365 of file PianoRoll.h.
Referenced by PianoRoll(), and markSemiTone().
m_knifeCutLineColor
QColor lmms::gui::PianoRoll::m_knifeCutLineColor private
Definition at line 512 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_knifeDown
bool lmms::gui::PianoRoll::m_knifeDown private
Definition at line 471 of file PianoRoll.h.
Referenced by cancelKnifeAction(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), and setKnifeAction().
m_knifeEndKey
int lmms::gui::PianoRoll::m_knifeEndKey private
Definition at line 470 of file PianoRoll.h.
Referenced by mouseReleaseEvent(), paintEvent(), and updateKnifePos().
m_knifeEndTickPos
TimePos lmms::gui::PianoRoll::m_knifeEndTickPos private
Definition at line 469 of file PianoRoll.h.
Referenced by mouseReleaseEvent(), paintEvent(), and updateKnifePos().
m_knifeMode
EditMode lmms::gui::PianoRoll::m_knifeMode private
Definition at line 445 of file PianoRoll.h.
Referenced by cancelKnifeAction(), focusOutEvent(), and setKnifeAction().
m_knifeStartKey
int lmms::gui::PianoRoll::m_knifeStartKey private
Definition at line 468 of file PianoRoll.h.
Referenced by mouseReleaseEvent(), paintEvent(), and updateKnifePos().
m_knifeStartTickPos
TimePos lmms::gui::PianoRoll::m_knifeStartTickPos private
Definition at line 467 of file PianoRoll.h.
Referenced by mouseReleaseEvent(), paintEvent(), and updateKnifePos().
m_lastKey
int lmms::gui::PianoRoll::m_lastKey private
Definition at line 441 of file PianoRoll.h.
Referenced by PianoRoll(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), selectNotesOnKey(), testPlayKey(), and testPlayNote().
m_lastMouseX
int lmms::gui::PianoRoll::m_lastMouseX private
Definition at line 413 of file PianoRoll.h.
Referenced by PianoRoll(), keyPressEvent(), and mouseMoveEvent().
m_lastMouseY
int lmms::gui::PianoRoll::m_lastMouseY private
Definition at line 414 of file PianoRoll.h.
Referenced by PianoRoll(), keyPressEvent(), and mouseMoveEvent().
m_lastNotePanning
panning_t lmms::gui::PianoRoll::m_lastNotePanning private
Definition at line 435 of file PianoRoll.h.
Referenced by PianoRoll(), enterValue(), mouseMoveEvent(), mousePressEvent(), and reset().
m_lastNoteVolume
volume_t lmms::gui::PianoRoll::m_lastNoteVolume private
Definition at line 434 of file PianoRoll.h.
Referenced by PianoRoll(), enterValue(), mouseMoveEvent(), mousePressEvent(), and reset().
m_leftRightScroll
QScrollBar* lmms::gui::PianoRoll::m_leftRightScroll private
Definition at line 381 of file PianoRoll.h.
Referenced by PianoRoll(), adjustLeftRightScoll(), autoScroll(), keyPressEvent(), paintEvent(), setCurrentMidiClip(), updateScrollbars(), and wheelEvent().
m_lenOfNewNotes
TimePos lmms::gui::PianoRoll::m_lenOfNewNotes private
Definition at line 433 of file PianoRoll.h.
Referenced by PianoRoll(), constrainNoteLengths(), dragNotes(), mousePressEvent(), and newNoteLen().
m_lineColor
QColor lmms::gui::PianoRoll::m_lineColor private
Definition at line 498 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_markedSemitoneColor
QColor lmms::gui::PianoRoll::m_markedSemitoneColor private
Definition at line 511 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_markedSemiTones
QList<int> lmms::gui::PianoRoll::m_markedSemiTones private
Definition at line 299 of file PianoRoll.h.
Referenced by loadMarkedSemiTones(), markSemiTone(), and paintEvent().
m_midiClip
MidiClip* lmms::gui::PianoRoll::m_midiClip private
Definition at line 373 of file PianoRoll.h.
Referenced by PianoRoll(), clearSelectedNotes(), computeSelectedNotes(), constrainNoteLengths(), currentMidiClip(), cutSelectedNotes(), deleteSelectedNotes(), desiredPlayModeForAccompany(), dragNotes(), finishRecordNote(), fitNoteLengths(), focusInEvent(), focusOutEvent(), getSelectedNotes(), glueNotes(), hasValidMidiClip(), hideMidiClip(), isSelection(), keyPressEvent(), keyReleaseEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), noteUnderMouse(), paintEvent(), pasteNotes(), pauseChordNotes(), pauseTestNotes(), play(), playChordNotes(), quantizeNotes(), record(), recordAccompany(), reverseNotes(), selectAll(), selectNotesOnKey(), setCurrentMidiClip(), setupSelectedChords(), shiftPos(), shiftPos(), shiftSemiTone(), shiftSemiTone(), startRecordNote(), testPlayKey(), testPlayNote(), trackOctaveSize(), updatePositionAccompany(), updateStrumPos(), and wheelEvent().
m_minResizeLen
TimePos lmms::gui::PianoRoll::m_minResizeLen private
Definition at line 438 of file PianoRoll.h.
Referenced by PianoRoll(), dragNotes(), and mousePressEvent().
m_mouseDownKey
int lmms::gui::PianoRoll::m_mouseDownKey private
Definition at line 409 of file PianoRoll.h.
Referenced by PianoRoll(), dragNotes(), and mousePressEvent().
m_mouseDownRight
bool lmms::gui::PianoRoll::m_mouseDownRight private
Definition at line 448 of file PianoRoll.h.
Referenced by PianoRoll(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
m_mouseDownTick
int lmms::gui::PianoRoll::m_mouseDownTick private
Definition at line 410 of file PianoRoll.h.
Referenced by PianoRoll(), dragNotes(), and mousePressEvent().
m_moveBoundaryBottom
int lmms::gui::PianoRoll::m_moveBoundaryBottom private
Definition at line 405 of file PianoRoll.h.
Referenced by PianoRoll(), dragNotes(), and mousePressEvent().
m_moveBoundaryLeft
int lmms::gui::PianoRoll::m_moveBoundaryLeft private
Definition at line 402 of file PianoRoll.h.
Referenced by PianoRoll(), dragNotes(), and mousePressEvent().
m_moveBoundaryRight
int lmms::gui::PianoRoll::m_moveBoundaryRight private
Definition at line 404 of file PianoRoll.h.
Referenced by PianoRoll(), and mousePressEvent().
m_moveBoundaryTop
int lmms::gui::PianoRoll::m_moveBoundaryTop private
Definition at line 403 of file PianoRoll.h.
Referenced by PianoRoll(), dragNotes(), and mousePressEvent().
m_moveStartX
int lmms::gui::PianoRoll::m_moveStartX private
Definition at line 417 of file PianoRoll.h.
Referenced by dragNotes(), and mousePressEvent().
m_moveStartY
int lmms::gui::PianoRoll::m_moveStartY private
Definition at line 418 of file PianoRoll.h.
Referenced by dragNotes(), mouseMoveEvent(), and mousePressEvent().
m_nemStr
std::vector<QString> lmms::gui::PianoRoll::m_nemStr private
Definition at line 296 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_noteBorders
bool lmms::gui::PianoRoll::m_noteBorders private
Definition at line 515 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_noteColor
QColor lmms::gui::PianoRoll::m_noteColor private
Definition at line 500 of file PianoRoll.h.
Referenced by PianoRoll(), drawDetuningInfo(), and paintEvent().
m_noteEditMenu
QMenu* lmms::gui::PianoRoll::m_noteEditMenu private
Definition at line 297 of file PianoRoll.h.
Referenced by PianoRoll(), and mousePressEvent().
m_noteEditMode
NoteEditMode lmms::gui::PianoRoll::m_noteEditMode private
Definition at line 393 of file PianoRoll.h.
Referenced by PianoRoll(), changeNoteEditMode(), enterValue(), mouseMoveEvent(), mousePressEvent(), paintEvent(), and wheelEvent().
m_noteLenModel
ComboBoxModel lmms::gui::PianoRoll::m_noteLenModel private
Definition at line 364 of file PianoRoll.h.
Referenced by PianoRoll(), keyPressEvent(), newNoteLen(), quantization(), and wheelEvent().
m_noteModeColor
QColor lmms::gui::PianoRoll::m_noteModeColor private
Definition at line 499 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_noteOpacity
int lmms::gui::PianoRoll::m_noteOpacity private
Definition at line 513 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_notesEditHeight
int lmms::gui::PianoRoll::m_notesEditHeight private
Definition at line 420 of file PianoRoll.h.
Referenced by PianoRoll(), keyAreaBottom(), mouseMoveEvent(), and paintEvent().
m_noteTextColor
QColor lmms::gui::PianoRoll::m_noteTextColor private
Definition at line 503 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_outOfBoundsShade
QColor lmms::gui::PianoRoll::m_outOfBoundsShade private
Definition at line 518 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_pianoKeySelected
int lmms::gui::PianoRoll::m_pianoKeySelected private
Definition at line 301 of file PianoRoll.h.
Referenced by markSemiTone(), and mousePressEvent().
m_pianoKeysVisible
int lmms::gui::PianoRoll::m_pianoKeysVisible private
Definition at line 424 of file PianoRoll.h.
Referenced by mouseMoveEvent(), and paintEvent().
m_positionLine
PositionLine* lmms::gui::PianoRoll::m_positionLine private
Definition at line 294 of file PianoRoll.h.
Referenced by PianoRoll(), updatePosition(), updatePositionLineHeight(), and zoomingChanged().
m_ppb
int lmms::gui::PianoRoll::m_ppb private
Definition at line 422 of file PianoRoll.h.
Referenced by PianoRoll(), autoScroll(), dragNotes(), drawDetuningInfo(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), noteUnderMouse(), paintEvent(), selectRegionFromPixels(), updateKnifePos(), updatePosition(), updateStrumPos(), wheelEvent(), and zoomingChanged().
m_quantizeModel
ComboBoxModel lmms::gui::PianoRoll::m_quantizeModel private
Definition at line 363 of file PianoRoll.h.
Referenced by PianoRoll(), keyPressEvent(), quantization(), and wheelEvent().
m_recording
bool lmms::gui::PianoRoll::m_recording private
Definition at line 387 of file PianoRoll.h.
Referenced by PianoRoll(), finishRecordNote(), isRecording(), record(), recordAccompany(), startRecordNote(), stop(), stopRecording(), testPlayNote(), and updatePositionAccompany().
m_recordingNotes
QList<Note> lmms::gui::PianoRoll::m_recordingNotes private
Definition at line 389 of file PianoRoll.h.
Referenced by finishRecordNote(), and startRecordNote().
m_scaleModel
ComboBoxModel lmms::gui::PianoRoll::m_scaleModel private
Definition at line 366 of file PianoRoll.h.
Referenced by PianoRoll(), markSemiTone(), and updateSemiToneMarkerMenu().
m_scrollBack
bool lmms::gui::PianoRoll::m_scrollBack private
Definition at line 451 of file PianoRoll.h.
Referenced by PianoRoll(), autoScroll(), stop(), and updatePosition().
m_selectedChords
std::vector<NoteVector> lmms::gui::PianoRoll::m_selectedChords private
Stores the chords for the strum tool.
Definition at line 476 of file PianoRoll.h.
Referenced by setupSelectedChords(), and updateStrumPos().
m_selectedKeys
int lmms::gui::PianoRoll::m_selectedKeys private
Definition at line 399 of file PianoRoll.h.
Referenced by computeSelectedNotes(), mouseMoveEvent(), mousePressEvent(), paintEvent(), removeSelection(), selectAll(), and selectRegionFromPixels().
m_selectedNoteColor
QColor lmms::gui::PianoRoll::m_selectedNoteColor private
Definition at line 507 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_selectedTick
int lmms::gui::PianoRoll::m_selectedTick private
Definition at line 397 of file PianoRoll.h.
Referenced by computeSelectedNotes(), mouseMoveEvent(), mousePressEvent(), paintEvent(), removeSelection(), selectAll(), and selectRegionFromPixels().
m_selectStartKey
int lmms::gui::PianoRoll::m_selectStartKey private
Definition at line 398 of file PianoRoll.h.
Referenced by computeSelectedNotes(), mouseMoveEvent(), mousePressEvent(), paintEvent(), removeSelection(), selectAll(), and selectRegionFromPixels().
m_selectStartTick
int lmms::gui::PianoRoll::m_selectStartTick private
Definition at line 396 of file PianoRoll.h.
Referenced by computeSelectedNotes(), mouseMoveEvent(), mousePressEvent(), paintEvent(), removeSelection(), selectAll(), and selectRegionFromPixels().
m_semiToneMarkerMenu
QMenu* lmms::gui::PianoRoll::m_semiToneMarkerMenu private
Definition at line 300 of file PianoRoll.h.
Referenced by PianoRoll(), and mousePressEvent().
m_snapModel
ComboBoxModel lmms::gui::PianoRoll::m_snapModel private
Definition at line 368 of file PianoRoll.h.
Referenced by PianoRoll(), and changeSnapMode().
m_startedWithShift
bool lmms::gui::PianoRoll::m_startedWithShift private
Definition at line 464 of file PianoRoll.h.
Referenced by dragNotes(), mouseMoveEvent(), and mousePressEvent().
m_startKey
int lmms::gui::PianoRoll::m_startKey private
Definition at line 440 of file PianoRoll.h.
Referenced by PianoRoll(), computeSelectedNotes(), dragNotes(), getKey(), mousePressEvent(), paintEvent(), setCurrentMidiClip(), updateKnifePos(), updateScrollbars(), updateYScroll(), verScrolled(), and yCoordOfKey().
m_stepNoteColor
QColor lmms::gui::PianoRoll::m_stepNoteColor private
Definition at line 501 of file PianoRoll.h.
Referenced by PianoRoll(), and paintEvent().
m_stepRecorder
StepRecorder lmms::gui::PianoRoll::m_stepRecorder private
Definition at line 493 of file PianoRoll.h.
Referenced by PianoRoll(), finishRecordNote(), isStepRecording(), keyPressEvent(), noteLengthChanged(), paintEvent(), setCurrentMidiClip(), startRecordNote(), testPlayNote(), toggleStepRecording(), and updatePositionStepRecording().
m_stepRecorderWidget
StepRecorderWidget lmms::gui::PianoRoll::m_stepRecorderWidget private
Definition at line 492 of file PianoRoll.h.
Referenced by PianoRoll(), horScrolled(), mouseMoveEvent(), and zoomingChanged().
m_strumCurrentTime
TimePos lmms::gui::PianoRoll::m_strumCurrentTime private
Definition at line 481 of file PianoRoll.h.
Referenced by updateStrumPos().
m_strumCurrentVertical
int lmms::gui::PianoRoll::m_strumCurrentVertical = 0 private
Definition at line 483 of file PianoRoll.h.
Referenced by updateStrumPos().
m_strumEnabled
bool lmms::gui::PianoRoll::m_strumEnabled = false private
Definition at line 485 of file PianoRoll.h.
Referenced by cancelStrumAction(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and setStrumAction().
m_strumHeightRatio
float lmms::gui::PianoRoll::m_strumHeightRatio = 0.0f private
Definition at line 484 of file PianoRoll.h.
Referenced by updateStrumPos().
m_strumMode
EditMode lmms::gui::PianoRoll::m_strumMode private
Definition at line 446 of file PianoRoll.h.
Referenced by cancelStrumAction(), focusOutEvent(), and setStrumAction().
m_strumStartTime
TimePos lmms::gui::PianoRoll::m_strumStartTime private
Definition at line 480 of file PianoRoll.h.
Referenced by updateStrumPos().
m_strumStartVertical
int lmms::gui::PianoRoll::m_strumStartVertical = 0 private
Definition at line 482 of file PianoRoll.h.
Referenced by updateStrumPos().
m_textColor
QColor lmms::gui::PianoRoll::m_textColor private
Definition at line 508 of file PianoRoll.h.
Referenced by PianoRoll().
m_textColorLight
QColor lmms::gui::PianoRoll::m_textColorLight private
Definition at line 509 of file PianoRoll.h.
Referenced by PianoRoll().
m_textShadow
QColor lmms::gui::PianoRoll::m_textShadow private
Definition at line 510 of file PianoRoll.h.
Referenced by PianoRoll().
m_timeLine
TimeLineWidget* lmms::gui::PianoRoll::m_timeLine private
Definition at line 450 of file PianoRoll.h.
Referenced by PianoRoll(), autoScroll(), keyPressEvent(), pasteNotes(), resizeEvent(), stop(), updatePosition(), and zoomingChanged().
m_toolDraw
QPixmap lmms::gui::PianoRoll::m_toolDraw = embed::getIconPixmap("edit_draw") private
Definition at line 349 of file PianoRoll.h.
Referenced by paintEvent().
m_toolErase
QPixmap lmms::gui::PianoRoll::m_toolErase = embed::getIconPixmap("edit_erase") private
Definition at line 350 of file PianoRoll.h.
Referenced by paintEvent().
m_toolKnife
QPixmap lmms::gui::PianoRoll::m_toolKnife = embed::getIconPixmap("edit_knife") private
Definition at line 354 of file PianoRoll.h.
Referenced by paintEvent().
m_toolMove
QPixmap lmms::gui::PianoRoll::m_toolMove = embed::getIconPixmap("edit_move") private
Definition at line 352 of file PianoRoll.h.
Referenced by paintEvent().
m_toolOpen
QPixmap lmms::gui::PianoRoll::m_toolOpen = embed::getIconPixmap("automation") private
Definition at line 353 of file PianoRoll.h.
Referenced by paintEvent().
m_toolSelect
QPixmap lmms::gui::PianoRoll::m_toolSelect = embed::getIconPixmap("edit_select") private
Definition at line 351 of file PianoRoll.h.
Referenced by paintEvent().
m_toolStrum
QPixmap lmms::gui::PianoRoll::m_toolStrum = embed::getIconPixmap("arp_free") private
Definition at line 355 of file PianoRoll.h.
Referenced by paintEvent().
m_topBottomScroll
QScrollBar* lmms::gui::PianoRoll::m_topBottomScroll private
Definition at line 382 of file PianoRoll.h.
Referenced by PianoRoll(), keyPressEvent(), updateScrollbars(), updateYScroll(), and wheelEvent().
m_totalKeysToScroll
int lmms::gui::PianoRoll::m_totalKeysToScroll private
Definition at line 423 of file PianoRoll.h.
Referenced by setCurrentMidiClip(), updateScrollbars(), updateYScroll(), and verScrolled().
m_userSetNotesEditHeight
int lmms::gui::PianoRoll::m_userSetNotesEditHeight private
Definition at line 421 of file PianoRoll.h.
Referenced by PianoRoll(), mouseMoveEvent(), and paintEvent().
m_whiteKeyActiveBackground
QBrush lmms::gui::PianoRoll::m_whiteKeyActiveBackground private
Definition at line 523 of file PianoRoll.h.
Referenced by paintEvent().
m_whiteKeyActiveTextColor
QColor lmms::gui::PianoRoll::m_whiteKeyActiveTextColor private
Definition at line 521 of file PianoRoll.h.
Referenced by paintEvent().
m_whiteKeyActiveTextShadow
QColor lmms::gui::PianoRoll::m_whiteKeyActiveTextShadow private
Definition at line 522 of file PianoRoll.h.
Referenced by paintEvent().
m_whiteKeyBigHeight
int lmms::gui::PianoRoll::m_whiteKeyBigHeight private
Definition at line 428 of file PianoRoll.h.
Referenced by PianoRoll(), paintEvent(), and zoomingYChanged().
m_whiteKeyDisabledBackground
QBrush lmms::gui::PianoRoll::m_whiteKeyDisabledBackground private
Definition at line 527 of file PianoRoll.h.
Referenced by paintEvent().
m_whiteKeyInactiveBackground
QBrush lmms::gui::PianoRoll::m_whiteKeyInactiveBackground private
Definition at line 526 of file PianoRoll.h.
Referenced by paintEvent().
m_whiteKeyInactiveTextColor
QColor lmms::gui::PianoRoll::m_whiteKeyInactiveTextColor private
Definition at line 524 of file PianoRoll.h.
Referenced by paintEvent().
m_whiteKeyInactiveTextShadow
QColor lmms::gui::PianoRoll::m_whiteKeyInactiveTextShadow private
Definition at line 525 of file PianoRoll.h.
Referenced by paintEvent().
m_whiteKeySmallHeight
int lmms::gui::PianoRoll::m_whiteKeySmallHeight private
Definition at line 427 of file PianoRoll.h.
Referenced by PianoRoll(), paintEvent(), and zoomingYChanged().
m_whiteKeyWidth
int lmms::gui::PianoRoll::m_whiteKeyWidth private
Definition at line 520 of file PianoRoll.h.
Referenced by PianoRoll(), autoScroll(), drawDetuningInfo(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), noteEditLeft(), noteUnderMouse(), paintEvent(), selectRegionFromPixels(), updateKnifePos(), updatePosition(), updateScrollbars(), updateStrumPos(), and wheelEvent().
m_zoomingModel
ComboBoxModel lmms::gui::PianoRoll::m_zoomingModel private
Definition at line 361 of file PianoRoll.h.
Referenced by PianoRoll(), adjustLeftRightScoll(), paintEvent(), wheelEvent(), and zoomingChanged().
m_zoomingYModel
ComboBoxModel lmms::gui::PianoRoll::m_zoomingYModel private
Definition at line 362 of file PianoRoll.h.
Referenced by PianoRoll(), paintEvent(), and zoomingYChanged().
m_zoomLevels
const std::vector< float > lmms::gui::PianoRoll::m_zoomLevels static private
Initial value:
=
        {0.125f, 0.25f, 0.5f, 1.0f, 1.5f, 2.0f, 4.0f, 8.0f}
Definition at line 370 of file PianoRoll.h.
Referenced by PianoRoll(), adjustLeftRightScoll(), paintEvent(), wheelEvent(), and zoomingChanged().
m_zoomYLevels
const std::vector< float > lmms::gui::PianoRoll::m_zoomYLevels static private
Initial value:
=
        {0.25f, 0.5f, 1.0f, 1.5f, 2.0f, 2.5f, 3.0f, 4.0f}
Definition at line 371 of file PianoRoll.h.
Referenced by PianoRoll(), paintEvent(), and zoomingYChanged().
prKeyOrder
std::array< PianoRoll::KeyType, 12 > lmms::gui::PianoRoll::prKeyOrder static private
Initial value:
{
    KeyType::WhiteSmall, KeyType::Black, KeyType::WhiteBig, KeyType::Black,
    KeyType::WhiteSmall, KeyType::WhiteSmall, KeyType::Black, KeyType::WhiteBig,
    KeyType::Black, KeyType::WhiteBig, KeyType::Black, KeyType::WhiteSmall
}
Definition at line 357 of file PianoRoll.h.
Referenced by paintEvent().
s_textFloat
SimpleTextFloat * lmms::gui::PianoRoll::s_textFloat = nullptr static private
Definition at line 359 of file PianoRoll.h.
Referenced by PianoRoll(), leaveEvent(), mouseReleaseEvent(), and showTextFloat().
Property Documentation
backgroundShade
QColor lmms::gui::PianoRoll::backgroundShade
Definition at line 88 of file PianoRoll.h.
barColor
QColor lmms::gui::PianoRoll::barColor
Definition at line 77 of file PianoRoll.h.
barLineColor
QColor lmms::gui::PianoRoll::barLineColor
Definition at line 67 of file PianoRoll.h.
beatLineColor
QColor lmms::gui::PianoRoll::beatLineColor
Definition at line 68 of file PianoRoll.h.
blackKeyActiveBackground
QBrush lmms::gui::PianoRoll::blackKeyActiveBackground
Definition at line 103 of file PianoRoll.h.
blackKeyDisabledBackground
QBrush lmms::gui::PianoRoll::blackKeyDisabledBackground
Definition at line 104 of file PianoRoll.h.
blackKeyInactiveBackground
QBrush lmms::gui::PianoRoll::blackKeyInactiveBackground
Definition at line 102 of file PianoRoll.h.
blackKeyWidth
int lmms::gui::PianoRoll::blackKeyWidth
Definition at line 101 of file PianoRoll.h.
currentStepNoteColor
QColor lmms::gui::PianoRoll::currentStepNoteColor
Definition at line 73 of file PianoRoll.h.
ghostNoteBorders
bool lmms::gui::PianoRoll::ghostNoteBorders
Definition at line 87 of file PianoRoll.h.
ghostNoteColor
QColor lmms::gui::PianoRoll::ghostNoteColor
Definition at line 74 of file PianoRoll.h.
ghostNoteOpacity
int lmms::gui::PianoRoll::ghostNoteOpacity
Definition at line 86 of file PianoRoll.h.
ghostNoteTextColor
QColor lmms::gui::PianoRoll::ghostNoteTextColor
Definition at line 76 of file PianoRoll.h.
knifeCutLine
QColor lmms::gui::PianoRoll::knifeCutLine
Definition at line 83 of file PianoRoll.h.
lineColor
QColor lmms::gui::PianoRoll::lineColor
Definition at line 69 of file PianoRoll.h.
markedSemitoneColor
QColor lmms::gui::PianoRoll::markedSemitoneColor
Definition at line 82 of file PianoRoll.h.
noteBorders
bool lmms::gui::PianoRoll::noteBorders
Definition at line 85 of file PianoRoll.h.
noteColor
QColor lmms::gui::PianoRoll::noteColor
Definition at line 71 of file PianoRoll.h.
noteModeColor
QColor lmms::gui::PianoRoll::noteModeColor
Definition at line 70 of file PianoRoll.h.
noteOpacity
int lmms::gui::PianoRoll::noteOpacity
Definition at line 84 of file PianoRoll.h.
noteTextColor
QColor lmms::gui::PianoRoll::noteTextColor
Definition at line 75 of file PianoRoll.h.
Referenced by drawNoteRect().
outOfBoundsShade
QColor lmms::gui::PianoRoll::outOfBoundsShade
Definition at line 89 of file PianoRoll.h.
selectedNoteColor
QColor lmms::gui::PianoRoll::selectedNoteColor
Definition at line 78 of file PianoRoll.h.
stepNoteColor
QColor lmms::gui::PianoRoll::stepNoteColor
Definition at line 72 of file PianoRoll.h.
textColor
QColor lmms::gui::PianoRoll::textColor
Definition at line 79 of file PianoRoll.h.
textColorLight
QColor lmms::gui::PianoRoll::textColorLight
Definition at line 80 of file PianoRoll.h.
textShadow
QColor lmms::gui::PianoRoll::textShadow
Definition at line 81 of file PianoRoll.h.
whiteKeyActiveBackground
QBrush lmms::gui::PianoRoll::whiteKeyActiveBackground
Definition at line 98 of file PianoRoll.h.
whiteKeyActiveTextColor
QColor lmms::gui::PianoRoll::whiteKeyActiveTextColor
Definition at line 96 of file PianoRoll.h.
whiteKeyActiveTextShadow
QColor lmms::gui::PianoRoll::whiteKeyActiveTextShadow
Definition at line 97 of file PianoRoll.h.
whiteKeyDisabledBackground
QBrush lmms::gui::PianoRoll::whiteKeyDisabledBackground
Definition at line 99 of file PianoRoll.h.
whiteKeyInactiveBackground
QBrush lmms::gui::PianoRoll::whiteKeyInactiveBackground
Definition at line 95 of file PianoRoll.h.
whiteKeyInactiveTextColor
QColor lmms::gui::PianoRoll::whiteKeyInactiveTextColor
Definition at line 93 of file PianoRoll.h.
whiteKeyInactiveTextShadow
QColor lmms::gui::PianoRoll::whiteKeyInactiveTextShadow
Definition at line 94 of file PianoRoll.h.
whiteKeyWidth
int lmms::gui::PianoRoll::whiteKeyWidth
Definition at line 92 of file PianoRoll.h.
The documentation for this class was generated from the following files:
include/PianoRoll.h
src/gui/editors/PianoRoll.cpp