LMMS: lmms::gui::TrackView Class Reference
lmms::gui::TrackView Class Reference
#include <TrackView.h>
Public Slots
virtual bool close ()
Close this track View.
Public Member Functions
TrackView (Track *_track, TrackContainerView *tcv)
Create a new track View.
~TrackView () override=default
virtual QMenu * createMixerMenu (QString title, QString newMixerLabel)
Create a menu for assigning/creating channels for this track.
Track * getTrack ()
const Track * getTrack () const
TrackContentWidget * getTrackContentWidget ()
TrackOperationsWidget * getTrackOperationsWidget ()
QWidget * getTrackSettingsWidget ()
bool isMovingTrack () const
TrackContainerView * trackContainerView ()
virtual void update ()
Update this track View and all its content objects.
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *dee) override
Start a drag event on this track View.
void dropEvent (QDropEvent *de) override
Accept a drop event on this track View.
void loadSettings (const QDomElement &element) override
void modelChanged () override
Register that the model of this track View has changed.
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse move event on this track View.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press event on this track View.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release event on this track View.
QString nodeName () const override
void paintEvent (QPaintEvent *pe) override
Repaint this track View.
void resizeEvent (QResizeEvent *re) override
Resize this track View.
void saveSettings (QDomDocument &doc, QDomElement &element) override
void wheelEvent (QWheelEvent *we) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Types
enum class Action {
None ,
Move ,
Resize
}
Private Slots
void createClipView (lmms::Clip *clip)
Create a Clip View in this track View.
void muteChanged ()
void onTrackGripGrabbed ()
void onTrackGripReleased ()
Private Member Functions
virtual FadeButton * getActivityIndicator ()
void resizeToHeight (int height)
void setIndicatorMute (FadeButton *indicator, bool muted)
Private Attributes
Action m_action
Track * m_track
TrackContainerView * m_trackContainerView
TrackContentWidget m_trackContentWidget
TrackOperationsWidget m_trackOperationsWidget
QWidget m_trackSettingsWidget
Friends
class TrackLabelButton
Detailed Description
Definition at line 59 of file TrackView.h.
Member Enumeration Documentation
Action
enum class lmms::gui::TrackView::Action strong private
Enumerator
None
Move
Resize
Definition at line 145 of file TrackView.h.
Constructor & Destructor Documentation
TrackView()
lmms::gui::TrackView::TrackView (Track * track, TrackContainerView * tcv)
Create a new track View.
The track View is handles the actual display of the track, including displaying its various widgets and the track segments.
Parameters
track The track to display.
tcv The track Container View for us to be displayed in.
Todo
Is my description of these properties correct?
< The Track Container View's content widget.
< The model view of this track
< The track we're displaying
< The track Container View we're displayed in
< Our trackOperationsWidget
< Our trackSettingsWidget
< Our trackContentWidget
< The action we're currently performing
Definition at line 60 of file TrackView.cpp.
References lmms::gui::ModelView::ModelView(), close(), createClipView(), lmms::gui::TrackGrip::grabbed(), m_action, m_track, m_trackContainerView, m_trackContentWidget, m_trackOperationsWidget, m_trackSettingsWidget, muteChanged(), None, onTrackGripGrabbed(), onTrackGripReleased(), lmms::gui::TrackGrip::released(), resizeEvent(), and update().
Referenced by lmms::gui::AutomationTrackView::AutomationTrackView(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), lmms::gui::PatternTrackView::PatternTrackView(), lmms::gui::SampleTrackView::SampleTrackView(), and mouseMoveEvent().
~TrackView()
lmms::gui::TrackView::~TrackView () override default
Member Function Documentation
close
bool lmms::gui::TrackView::close () virtual slot
Close this track View.
Reimplemented in lmms::gui::PatternTrackView.
Definition at line 181 of file TrackView.cpp.
References m_trackContainerView.
Referenced by TrackView(), lmms::gui::PatternTrackView::close(), and modelChanged().
createClipView
void lmms::gui::TrackView::createClipView (lmms::Clip * clip) private slot
Create a Clip View in this track View.
Parameters
clip the Clip to create the view for.
Todo
is this a good description for what this method does?
Definition at line 422 of file TrackView.cpp.
References lmms::Clip::createView(), lmms::Clip::getSelectViewOnCreate(), lmms::Clip::selectViewOnCreate(), and lmms::gui::selectableObject::setSelected().
Referenced by TrackView().
createMixerMenu()
QMenu * lmms::gui::TrackView::createMixerMenu (QString title, QString newMixerLabel) virtual
Create a menu for assigning/creating channels for this track.
Reimplemented in lmms::gui::InstrumentTrackView, and lmms::gui::SampleTrackView.
Definition at line 168 of file TrackView.cpp.
dragEnterEvent()
void lmms::gui::TrackView::dragEnterEvent (QDragEnterEvent * dee) override protected
Start a drag event on this track View.
Parameters
dee the DragEnterEvent to start.
Definition at line 211 of file TrackView.cpp.
References m_track, and lmms::gui::StringPairDrag::processDragEnterEvent().
Referenced by lmms::gui::InstrumentTrackView::dragEnterEvent().
dropEvent()
void lmms::gui::TrackView::dropEvent (QDropEvent * de) override protected
Accept a drop event on this track View.
We only accept drop events that are of the same type as this track. If so, we decode the data from the drop event by just feeding it back into the engine as a state.
Parameters
de the DropEvent to handle.
Definition at line 228 of file TrackView.cpp.
References lmms::Engine::audioEngine(), lmms::DataFile::content(), lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::AudioEngine::doneChangeInModel(), m_track, and lmms::AudioEngine::requestChangeInModel().
Referenced by lmms::gui::InstrumentTrackView::dropEvent().
getActivityIndicator()
virtual FadeButton * lmms::gui::TrackView::getActivityIndicator () inline private virtual
Reimplemented in lmms::gui::InstrumentTrackView, and lmms::gui::SampleTrackView.
Definition at line 161 of file TrackView.h.
Referenced by muteChanged().
getTrack() [1/2]
Track * lmms::gui::TrackView::getTrack () inline
Definition at line 71 of file TrackView.h.
References m_track.
getTrack() [2/2]
const Track * lmms::gui::TrackView::getTrack () const inline
Definition at line 66 of file TrackView.h.
References m_track.
Referenced by lmms::gui::TrackContainerView::clearAllTracks(), lmms::gui::InstrumentTrackView::createMixerLine(), lmms::gui::SampleTrackView::createMixerLine(), lmms::gui::TrackContainerView::deleteTrackView(), lmms::gui::AutomationTrackView::dropEvent(), lmms::gui::SampleTrackView::dropEvent(), and lmms::gui::TrackContainerView::moveTrackView().
getTrackContentWidget()
TrackContentWidget * lmms::gui::TrackView::getTrackContentWidget () inline
Definition at line 91 of file TrackView.h.
References m_trackContentWidget.
Referenced by lmms::gui::ClipView::ClipView(), lmms::gui::TrackContainerView::addTrackView(), and lmms::gui::AutomationTrackView::dropEvent().
getTrackOperationsWidget()
TrackOperationsWidget * lmms::gui::TrackView::getTrackOperationsWidget () inline
Definition at line 81 of file TrackView.h.
References m_trackOperationsWidget.
getTrackSettingsWidget()
QWidget * lmms::gui::TrackView::getTrackSettingsWidget () inline
Definition at line 86 of file TrackView.h.
References m_trackSettingsWidget.
Referenced by lmms::gui::AutomationTrackView::AutomationTrackView(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), lmms::gui::PatternTrackView::PatternTrackView(), and lmms::gui::SampleTrackView::SampleTrackView().
isMovingTrack()
bool lmms::gui::TrackView::isMovingTrack () const inline
Definition at line 96 of file TrackView.h.
References m_action, and Move.
loadSettings()
void lmms::gui::TrackView::loadSettings (const QDomElement & element) inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 121 of file TrackView.h.
modelChanged()
void lmms::gui::TrackView::modelChanged () override protected virtual
Register that the model of this track View has changed.
Reimplemented from lmms::gui::ModelView.
Definition at line 193 of file TrackView.cpp.
References lmms::gui::ModelView::castModel(), close(), m_track, m_trackOperationsWidget, and lmms::gui::ModelView::modelChanged().
Referenced by lmms::gui::InstrumentTrackView::modelChanged(), and lmms::gui::SampleTrackView::modelChanged().
mouseMoveEvent()
void lmms::gui::TrackView::mouseMoveEvent (QMouseEvent * me) override protected
Handle a mouse move event on this track View.
If this track container supports rubber band selection, let the widget handle that and don't bother with any other handling.
Otherwise if we've started the move process (from mousePressEvent()) then move ourselves into that position, reordering the track list with moveTrackViewUp() and moveTrackViewDown() to suit. We make a note of this in the undo journal in case the user wants to undo this move.
Likewise if we've started a resize process, handle this too, making sure that we never go below the minimum track height.
Parameters
me the MouseEvent to handle.
Definition at line 319 of file TrackView.cpp.
References TrackView(), lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT, lmms::DEFAULT_TRACK_HEIGHT, lmms::ConfigManager::inst(), m_action, m_track, m_trackContainerView, Move, Resize, resizeToHeight(), lmms::gui::TRACK_OP_WIDTH, lmms::gui::TRACK_OP_WIDTH_COMPACT, and lmms::ConfigManager::value().
mousePressEvent()
void lmms::gui::TrackView::mousePressEvent (QMouseEvent * me) override protected
Handle a mouse press event on this track View.
If this track container supports rubber band selection, let the widget handle that and don't bother with any other handling.
If the left mouse button is pressed, we handle two things. If SHIFT is pressed, then we resize vertically. Otherwise we start the process of moving this track to a new position.
Otherwise we let the widget handle the mouse event as normal.
Parameters
me the MouseEvent to handle.
Definition at line 260 of file TrackView.cpp.
References lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT, lmms::DEFAULT_TRACK_HEIGHT, lmms::ConfigManager::inst(), m_action, m_track, m_trackContainerView, Resize, lmms::gui::TRACK_OP_WIDTH, lmms::gui::TRACK_OP_WIDTH_COMPACT, and lmms::ConfigManager::value().
mouseReleaseEvent()
void lmms::gui::TrackView::mouseReleaseEvent (QMouseEvent * me) override protected
Handle a mouse release event on this track View.
Parameters
me the MouseEvent to handle.
Definition at line 370 of file TrackView.cpp.
References m_action, m_trackOperationsWidget, and None.
muteChanged
void lmms::gui::TrackView::muteChanged () private slot
Definition at line 435 of file TrackView.cpp.
References getActivityIndicator(), m_track, and setIndicatorMute().
Referenced by TrackView().
nodeName()
QString lmms::gui::TrackView::nodeName () const inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 126 of file TrackView.h.
onTrackGripGrabbed
void lmms::gui::TrackView::onTrackGripGrabbed () private slot
Definition at line 442 of file TrackView.cpp.
References m_action, and Move.
Referenced by TrackView().
onTrackGripReleased
void lmms::gui::TrackView::onTrackGripReleased () private slot
Definition at line 447 of file TrackView.cpp.
References m_action, and None.
Referenced by TrackView().
paintEvent()
void lmms::gui::TrackView::paintEvent (QPaintEvent * pe) override protected
Repaint this track View.
Parameters
pe the PaintEvent to start.
Definition at line 406 of file TrackView.cpp.
resizeEvent()
void lmms::gui::TrackView::resizeEvent (QResizeEvent * re) override protected
Resize this track View.
Parameters
re the Resize Event to handle.
Definition at line 130 of file TrackView.cpp.
References lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT, lmms::ConfigManager::inst(), m_trackContentWidget, m_trackOperationsWidget, m_trackSettingsWidget, lmms::gui::TRACK_OP_WIDTH, and lmms::gui::TRACK_OP_WIDTH_COMPACT.
Referenced by TrackView().
resizeToHeight()
void lmms::gui::TrackView::resizeToHeight (int height) private
Definition at line 461 of file TrackView.cpp.
References m_track, m_trackContainerView, and lmms::MINIMAL_TRACK_HEIGHT.
Referenced by mouseMoveEvent(), and wheelEvent().
saveSettings()
void lmms::gui::TrackView::saveSettings (QDomDocument & doc, QDomElement & element) inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 115 of file TrackView.h.
setIndicatorMute()
void lmms::gui::TrackView::setIndicatorMute (FadeButton * indicator, bool muted) private
Definition at line 454 of file TrackView.cpp.
References lmms::gui::FadeButton::setActiveColor().
Referenced by muteChanged().
trackContainerView()
TrackContainerView * lmms::gui::TrackView::trackContainerView () inline
Definition at line 76 of file TrackView.h.
References m_trackContainerView.
Referenced by lmms::gui::TrackContentWidget::TrackContentWidget(), lmms::gui::AutomationTrackView::dropEvent(), lmms::gui::SampleTrackView::dropEvent(), and lmms::gui::InstrumentTrackWindow::viewInstrumentInDirection().
update()
void lmms::gui::TrackView::update () virtual
Update this track View and all its content objects.
Definition at line 152 of file TrackView.cpp.
References m_trackContainerView, and m_trackContentWidget.
Referenced by lmms::gui::InstrumentTrackView::InstrumentTrackView(), TrackView(), and lmms::gui::AutomationTrackView::dropEvent().
wheelEvent()
void lmms::gui::TrackView::wheelEvent (QWheelEvent * we) override protected
Definition at line 382 of file TrackView.cpp.
References resizeToHeight().
Friends And Related Symbol Documentation
TrackLabelButton
friend class TrackLabelButton friend
Definition at line 168 of file TrackView.h.
References TrackLabelButton.
Referenced by lmms::gui::AutomationTrackView::AutomationTrackView(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), lmms::gui::PatternTrackView::PatternTrackView(), lmms::gui::SampleTrackView::SampleTrackView(), and TrackLabelButton.
Member Data Documentation
m_action
Action lmms::gui::TrackView::m_action private
Definition at line 159 of file TrackView.h.
Referenced by TrackView(), isMovingTrack(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), onTrackGripGrabbed(), and onTrackGripReleased().
m_track
Track* lmms::gui::TrackView::m_track private
Definition at line 152 of file TrackView.h.
Referenced by TrackView(), dragEnterEvent(), dropEvent(), getTrack(), getTrack(), modelChanged(), mouseMoveEvent(), mousePressEvent(), muteChanged(), and resizeToHeight().
m_trackContainerView
TrackContainerView* lmms::gui::TrackView::m_trackContainerView private
Definition at line 153 of file TrackView.h.
Referenced by TrackView(), close(), mouseMoveEvent(), mousePressEvent(), resizeToHeight(), trackContainerView(), and update().
m_trackContentWidget
TrackContentWidget lmms::gui::TrackView::m_trackContentWidget private
Definition at line 157 of file TrackView.h.
Referenced by TrackView(), getTrackContentWidget(), resizeEvent(), and update().
m_trackOperationsWidget
TrackOperationsWidget lmms::gui::TrackView::m_trackOperationsWidget private
Definition at line 155 of file TrackView.h.
Referenced by TrackView(), getTrackOperationsWidget(), modelChanged(), mouseReleaseEvent(), and resizeEvent().
m_trackSettingsWidget
QWidget lmms::gui::TrackView::m_trackSettingsWidget private
Definition at line 156 of file TrackView.h.
Referenced by TrackView(), getTrackSettingsWidget(), and resizeEvent().
The documentation for this class was generated from the following files:
include/TrackView.h
src/gui/tracks/TrackView.cpp