LMMS: lmms::gui::PatternEditorWindow Class Reference
lmms::gui::PatternEditorWindow Class Reference
#include <PatternEditor.h>
Public Slots
void play () override
void stop () override
Public Slots inherited from lmms::gui::Editor
void togglePause ()
Called by pressing shift+space. Toggles pause state.
void togglePlayStop ()
Called by pressing the space key. Plays or stops.
Public Member Functions
PatternEditorWindow (PatternStore *ps)
~PatternEditorWindow ()=default
QSize sizeHint () const override
Public Member Functions inherited from lmms::gui::Editor
QAction * playAction () const
void setPauseIcon (bool displayPauseIcon=true)
Public Attributes
PatternEditor * m_editor
Private Attributes
ComboBox * m_patternComboBox
Additional Inherited Members
Static Public Member Functions inherited from lmms::gui::Editor
static Editor * lastPlayedEditor ()
Protected Slots inherited from lmms::gui::Editor
virtual void play ()
virtual void record ()
virtual void recordAccompany ()
virtual void stop ()
virtual void toggleStepRecording ()
Protected Member Functions inherited from lmms::gui::Editor
Editor (bool record=false, bool record_step=false)
Constructor.
~Editor () override=default
DropToolBar * addDropToolBar (Qt::ToolBarArea whereToAdd, QString const &windowTitle)
DropToolBar * addDropToolBar (QWidget *parent, Qt::ToolBarArea whereToAdd, QString const &windowTitle)
DropToolBar * addDropToolBarToTop (QString const &windowTitle)
void closeEvent (QCloseEvent *event) override
void keyPressEvent (QKeyEvent *ke) override
Protected Attributes inherited from lmms::gui::Editor
QAction * m_playAction
QAction * m_recordAccompanyAction
QAction * m_recordAction
QAction * m_stopAction
QAction * m_toggleStepRecordingAction
DropToolBar * m_toolBar
Detailed Description
Definition at line 83 of file PatternEditor.h.
Constructor & Destructor Documentation
PatternEditorWindow()
lmms::gui::PatternEditorWindow::PatternEditorWindow (PatternStore * ps)
Definition at line 277 of file PatternEditor.cpp.
References lmms::gui::Editor::Editor(), lmms::gui::Editor::addDropToolBarToTop(), lmms::gui::ClipView::BORDER_WIDTH, lmms::Model::dataChanged(), lmms::gui::ComboBox::DEFAULT_HEIGHT, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT, lmms::embed::getIconPixmap(), lmms::Engine::getSong(), lmms::ConfigManager::inst(), m_editor, m_patternComboBox, lmms::PatternStore::m_patternComboBoxModel, lmms::gui::Editor::m_playAction, lmms::gui::Editor::m_stopAction, lmms::gui::Editor::m_toolBar, lmms::gui::TRACK_OP_WIDTH, lmms::gui::TRACK_OP_WIDTH_COMPACT, and lmms::gui::PatternEditor::updateMaxSteps().
~PatternEditorWindow()
lmms::gui::PatternEditorWindow::~PatternEditorWindow () default
Member Function Documentation
play
void lmms::gui::PatternEditorWindow::play () override slot
Definition at line 362 of file PatternEditor.cpp.
References lmms::Engine::getSong(), lmms::Song::Pattern, lmms::Song::playPattern(), and lmms::Song::togglePause().
sizeHint()
QSize lmms::gui::PatternEditorWindow::sizeHint () const override
Definition at line 356 of file PatternEditor.cpp.
stop
void lmms::gui::PatternEditorWindow::stop () override slot
Definition at line 375 of file PatternEditor.cpp.
References lmms::Engine::getSong(), and lmms::Song::stop().
Member Data Documentation
m_editor
PatternEditor* lmms::gui::PatternEditorWindow::m_editor
Definition at line 92 of file PatternEditor.h.
Referenced by PatternEditorWindow(), lmms::gui::PatternTrackView::~PatternTrackView(), lmms::Song::clearProject(), and lmms::gui::PatternTrackView::close().
m_patternComboBox
ComboBox* lmms::gui::PatternEditorWindow::m_patternComboBox private
Definition at line 99 of file PatternEditor.h.
Referenced by PatternEditorWindow().
The documentation for this class was generated from the following files:
include/PatternEditor.h
src/gui/editors/PatternEditor.cpp