LMMS: hiir::StageProcTpl< REMAINING, DT > Class Template Reference
hiir::StageProcTpl< REMAINING, DT > Class Template Reference
#include <StageProcTpl.h>
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, DT &spl_0, DT &spl_1, StageDataTpl< DT > *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, DT &spl_0, DT &spl_1, StageDataTpl< DT > *stage_arr) noexcept
Private Member Functions
StageProcTpl ()=delete
StageProcTpl (const StageProcTpl< REMAINING, DT > &other)=delete
StageProcTpl (StageProcTpl< REMAINING, DT > &&other)=delete
~StageProcTpl ()=delete
bool operator!= (const StageProcTpl< REMAINING, DT > &other)=delete
StageProcTpl< REMAINING, DT > & operator= (const StageProcTpl< REMAINING, DT > &other)=delete
StageProcTpl< REMAINING, DT > & operator= (StageProcTpl< REMAINING, DT > &&other)=delete
bool operator== (const StageProcTpl< REMAINING, DT > &other)=delete
Detailed Description
template<int REMAINING, typename DT>
class hiir::StageProcTpl< REMAINING, DT >
Definition at line 49 of file StageProcTpl.h.
Constructor & Destructor Documentation
StageProcTpl() [1/3]
template<int REMAINING, typename DT> hiir::StageProcTpl< REMAINING, DT >::StageProcTpl () private delete
Referenced by process_sample_neg(), and process_sample_pos().
StageProcTpl() [2/3]
template<int REMAINING, typename DT> hiir::StageProcTpl< REMAINING, DT >::StageProcTpl (const StageProcTpl< REMAINING, DT > & other) private delete
StageProcTpl() [3/3]
template<int REMAINING, typename DT> hiir::StageProcTpl< REMAINING, DT >::StageProcTpl (StageProcTpl< REMAINING, DT > && other) private delete
~StageProcTpl()
template<int REMAINING, typename DT> hiir::StageProcTpl< REMAINING, DT >::~StageProcTpl () private delete
Member Function Documentation
operator!=()
template<int REMAINING, typename DT> bool hiir::StageProcTpl< REMAINING, DT >::operator!= (const StageProcTpl< REMAINING, DT > & other) private delete
operator=() [1/2]
template<int REMAINING, typename DT> StageProcTpl< REMAINING, DT > & hiir::StageProcTpl< REMAINING, DT >::operator= (const StageProcTpl< REMAINING, DT > & other) private delete
operator=() [2/2]
template<int REMAINING, typename DT> StageProcTpl< REMAINING, DT > & hiir::StageProcTpl< REMAINING, DT >::operator= (StageProcTpl< REMAINING, DT > && other) private delete
operator==()
template<int REMAINING, typename DT> bool hiir::StageProcTpl< REMAINING, DT >::operator== (const StageProcTpl< REMAINING, DT > & other) private delete
process_sample_neg()
template<int REMAINING, typename DT> void hiir::StageProcTpl< REMAINING, DT >::process_sample_neg (const int nbr_coefs, DT & spl_0, DT & spl_1, StageDataTpl< DT > * stage_arr) static noexcept
Definition at line 99 of file StageProcTpl.hpp.
References StageProcTpl(), and process_sample_neg().
Referenced by hiir::PhaseHalfPiTpl< NC, DT, NCHN >::process_block(), hiir::PhaseHalfPiTpl< NC, DT, NCHN >::process_sample(), and process_sample_neg().
process_sample_pos()
template<int REMAINING, typename DT> void hiir::StageProcTpl< REMAINING, DT >::process_sample_pos (const int nbr_coefs, DT & spl_0, DT & spl_1, StageDataTpl< DT > * stage_arr) static noexcept
Definition at line 42 of file StageProcTpl.hpp.
References StageProcTpl(), and process_sample_pos().
Referenced by hiir::HalfBandTpl< NC, DT, NCHN >::process_2_paths(), hiir::Downsampler2xTpl< NC, DT, NCHN >::process_sample(), hiir::Upsampler2xTpl< NC, DT, NCHN >::process_sample(), process_sample_pos(), and hiir::Downsampler2xTpl< NC, DT, NCHN >::process_sample_split().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProcTpl.h
src/3rdparty/hiir/hiir/StageProcTpl.hpp