LMMS: hiir::Downsampler2xF64Sse2< NC > Class Template Reference
hiir::Downsampler2xF64Sse2< NC > Class Template Reference
#include <Downsampler2xF64Sse2.h>
Public Types
typedef double DataType
Public Member Functions
Downsampler2xF64Sse2 () noexcept
Downsampler2xF64Sse2 (const Downsampler2xF64Sse2< NC > &other)=default
Downsampler2xF64Sse2 (Downsampler2xF64Sse2< NC > &&other)=default
void clear_buffers () noexcept
Downsampler2xF64Sse2< NC > & operator= (const Downsampler2xF64Sse2< NC > &other)=default
Downsampler2xF64Sse2< NC > & operator= (Downsampler2xF64Sse2< NC > &&other)=default
void process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
long process_block_double (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_split (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE double process_sample (const double in_ptr[2]) noexcept
hiir_FORCEINLINE void process_sample_split (double &low, double &high, const double in_ptr[2]) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = -1
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Sse2, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Downsampler2xF64Sse2< NC > &other) const =delete
bool operator== (const Downsampler2xF64Sse2< NC > &other) const =delete
template<typename FL, typename FH>
hiir_FORCEINLINE long process_block_double (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (double *, __m128d, __m128d, __m128d) noexcept
static hiir_FORCEINLINE void store_high (double *ptr, __m128d even, __m128d odd, __m128d half) noexcept
static hiir_FORCEINLINE void store_low (double *ptr, __m128d even, __m128d odd, __m128d half) noexcept
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _nbr_stages
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::Downsampler2xF64Sse2< NC >
Definition at line 41 of file Downsampler2xF64Sse2.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::Downsampler2xF64Sse2< NC >::DataType
Definition at line 50 of file Downsampler2xF64Sse2.h.
Filter
template<int NC> typedef std::array<StageDataF64Sse2, _nbr_stages + 1> hiir::Downsampler2xF64Sse2< NC >::Filter private
Definition at line 104 of file Downsampler2xF64Sse2.h.
Constructor & Destructor Documentation
Downsampler2xF64Sse2() [1/3]
template<int NC> hiir::Downsampler2xF64Sse2< NC >::Downsampler2xF64Sse2 () noexcept
Definition at line 57 of file Downsampler2xF64Sse2.hpp.
References _filter, _nbr_stages, clear_buffers(), i, and NBR_COEFS.
Referenced by Downsampler2xF64Sse2(), Downsampler2xF64Sse2(), operator=(), and operator=().
Downsampler2xF64Sse2() [2/3]
template<int NC> hiir::Downsampler2xF64Sse2< NC >::Downsampler2xF64Sse2 (const Downsampler2xF64Sse2< NC > & other) default
References Downsampler2xF64Sse2().
Downsampler2xF64Sse2() [3/3]
template<int NC> hiir::Downsampler2xF64Sse2< NC >::Downsampler2xF64Sse2 (Downsampler2xF64Sse2< NC > && other) default
References Downsampler2xF64Sse2().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::Downsampler2xF64Sse2< NC >::bypass (double * , __m128d , __m128d , __m128d) inline static private noexcept
Definition at line 101 of file Downsampler2xF64Sse2.h.
References bypass().
Referenced by bypass(), and process_block().
clear_buffers()
template<int NC> void hiir::Downsampler2xF64Sse2< NC >::clear_buffers () noexcept
Definition at line 255 of file Downsampler2xF64Sse2.hpp.
References _filter, _nbr_stages, and i.
Referenced by Downsampler2xF64Sse2(), and operator=().
operator!=()
template<int NC> bool hiir::Downsampler2xF64Sse2< NC >::operator!= (const Downsampler2xF64Sse2< NC > & other) const private delete
operator=() [1/2]
template<int NC> Downsampler2xF64Sse2< NC > & hiir::Downsampler2xF64Sse2< NC >::operator= (const Downsampler2xF64Sse2< NC > & other) default
References Downsampler2xF64Sse2().
operator=() [2/2]
template<int NC> Downsampler2xF64Sse2< NC > & hiir::Downsampler2xF64Sse2< NC >::operator= (Downsampler2xF64Sse2< NC > && other) default
References Downsampler2xF64Sse2(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_split(), process_sample(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::Downsampler2xF64Sse2< NC >::operator== (const Downsampler2xF64Sse2< NC > & other) const private delete
process_block()
template<int NC> void hiir::Downsampler2xF64Sse2< NC >::process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 145 of file Downsampler2xF64Sse2.hpp.
References bypass(), process_block_double(), process_sample(), and store_low().
Referenced by operator=().
process_block_double() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE long hiir::Downsampler2xF64Sse2< NC >::process_block_double (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE, process_block_double(), store_high(), and store_low().
Referenced by process_block(), process_block_double(), and process_block_split().
process_block_double() [2/2]
template<int NC> template<typename FL, typename FH> long hiir::Downsampler2xF64Sse2< NC >::process_block_double (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 282 of file Downsampler2xF64Sse2.hpp.
References _filter, pos, and hiir::StageProcF64Sse2< CUR >::process_sample_pos().
process_block_split()
template<int NC> void hiir::Downsampler2xF64Sse2< NC >::process_block_split (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 223 of file Downsampler2xF64Sse2.hpp.
References process_block_double(), process_sample_split(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> double hiir::Downsampler2xF64Sse2< NC >::process_sample (const double in_ptr[2]) noexcept
Definition at line 115 of file Downsampler2xF64Sse2.hpp.
References _filter, and hiir::StageProcF64Sse2< CUR >::process_sample_pos().
Referenced by operator=(), and process_block().
process_sample_split()
template<int NC> void hiir::Downsampler2xF64Sse2< NC >::process_sample_split (double & low, double & high, const double in_ptr[2]) noexcept
Definition at line 184 of file Downsampler2xF64Sse2.hpp.
References _filter, and hiir::StageProcF64Sse2< CUR >::process_sample_pos().
Referenced by operator=(), and process_block_split().
set_coefs()
template<int NC> void hiir::Downsampler2xF64Sse2< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 88 of file Downsampler2xF64Sse2.hpp.
References _filter, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
store_high()
template<int NC> void hiir::Downsampler2xF64Sse2< NC >::store_high (double * ptr, __m128d even, __m128d odd, __m128d half) static private noexcept
Definition at line 314 of file Downsampler2xF64Sse2.hpp.
Referenced by process_block_double(), and process_block_split().
store_low()
template<int NC> void hiir::Downsampler2xF64Sse2< NC >::store_low (double * ptr, __m128d even, __m128d odd, __m128d half) static private noexcept
Definition at line 305 of file Downsampler2xF64Sse2.hpp.
Referenced by process_block(), process_block_double(), and process_block_split().
Member Data Documentation
_delay
template<int NC> double hiir::Downsampler2xF64Sse2< NC >::_delay = -1 static constexpr
Definition at line 53 of file Downsampler2xF64Sse2.h.
_filter
template<int NC> Filter hiir::Downsampler2xF64Sse2< NC >::_filter private
Definition at line 106 of file Downsampler2xF64Sse2.h.
Referenced by Downsampler2xF64Sse2(), clear_buffers(), process_block_double(), process_sample(), process_sample_split(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Downsampler2xF64Sse2< NC >::_nbr_chn = 1 static constexpr
Definition at line 51 of file Downsampler2xF64Sse2.h.
_nbr_stages
template<int NC> int hiir::Downsampler2xF64Sse2< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 89 of file Downsampler2xF64Sse2.h.
Referenced by Downsampler2xF64Sse2(), and clear_buffers().
_stage_width
template<int NC> int hiir::Downsampler2xF64Sse2< NC >::_stage_width = 2 static constexpr private
Definition at line 88 of file Downsampler2xF64Sse2.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::Downsampler2xF64Sse2< NC >::NBR_COEFS = NC static constexpr
Definition at line 52 of file Downsampler2xF64Sse2.h.
Referenced by Downsampler2xF64Sse2(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Downsampler2xF64Sse2.h
src/3rdparty/hiir/hiir/Downsampler2xF64Sse2.hpp