LMMS: lmms::LfoController Class Reference
lmms::LfoController Class Reference
#include <LfoController.h>
Public Slots
gui::ControllerDialog * createDialog (QWidget *_parent) override
Public Slots inherited from lmms::Controller
virtual gui::ControllerDialog * createDialog (QWidget *_parent)
virtual void setName (const QString &_new_name)
Public Member Functions
LfoController (Model *_parent)
~LfoController () override
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
Public Member Functions inherited from lmms::Controller
Controller (ControllerType _type, Model *_parent, const QString &_display_name)
~Controller () override
void addConnection (ControllerConnection *)
int connectionCount () const
virtual float currentValue (int _offset)
bool frequentUpdates () const
bool hasModel (const Model *m) const
bool isSampleExact () const
virtual const QString & name () const
void removeConnection (ControllerConnection *)
void setSampleExact (bool _exact)
ControllerType type () const
virtual ValueBuffer * valueBuffer ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Slots
void updateDuration ()
void updatePhase ()
void updateSampleFunction ()
Protected Member Functions
void updateValueBuffer () override
Protected Member Functions inherited from lmms::Controller
virtual float value (int _offset)
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Attributes
FloatModel m_amountModel
FloatModel m_baseModel
float m_currentPhase
float m_duration
IntModel m_multiplierModel
FloatModel m_phaseModel
float m_phaseOffset
sample_t(* m_sampleFunction)(const float)
TempoSyncKnobModel m_speedModel
IntModel m_waveModel
Protected Attributes inherited from lmms::Controller
long m_bufferLastUpdated
int m_connectionCount
float m_currentValue
QString m_name
bool m_sampleExact
ControllerType m_type
ValueBuffer m_valueBuffer
Private Attributes
float m_heldSample
std::shared_ptr< const SampleBuffer > m_userDefSampleBuffer = SampleBuffer::emptyBuffer()
Friends
class gui::LfoControllerDialog
Additional Inherited Members
Public Types inherited from lmms::Controller
enum class ControllerType {
Dummy ,
Lfo ,
Midi ,
Peak
}
Signals inherited from lmms::Controller
void valueChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Public Member Functions inherited from lmms::Controller
static Controller * create (const QDomElement &_this, Model *_parent)
static Controller * create (ControllerType _tt, Model *_parent)
static float fittedValue (float _val)
static void resetFrameCounter ()
static unsigned int runningFrames ()
static long runningPeriods ()
static float runningTime ()
static void triggerFrameCounter ()
Static Protected Attributes inherited from lmms::Controller
static ControllerVector s_controllers
static long s_periods = 0
Detailed Description
Definition at line 51 of file LfoController.h.
Constructor & Destructor Documentation
LfoController()
lmms::LfoController::LfoController (Model * _parent)
Definition at line 41 of file LfoController.cpp.
References lmms::Controller::Controller(), lmms::Engine::audioEngine(), lmms::Model::dataChanged(), lmms::Engine::getSong(), m_amountModel, m_baseModel, m_currentPhase, m_duration, m_multiplierModel, m_phaseModel, m_phaseOffset, m_sampleFunction, m_speedModel, m_userDefSampleBuffer, m_waveModel, lmms::Controller::setSampleExact(), updateDuration(), updatePhase(), and updateSampleFunction().
~LfoController()
lmms::LfoController::~LfoController () override
Definition at line 78 of file LfoController.cpp.
References m_amountModel, m_baseModel, m_multiplierModel, m_phaseModel, m_speedModel, and m_waveModel.
Member Function Documentation
createDialog
gui::ControllerDialog * lmms::LfoController::createDialog (QWidget * _parent) override slot
Definition at line 264 of file LfoController.cpp.
loadSettings()
void lmms::LfoController::loadSettings (const QDomElement & _this) override virtual
Reimplemented from lmms::Controller.
Definition at line 232 of file LfoController.cpp.
References lmms::Song::collectError(), lmms::gui::SampleLoader::createBufferFromFile(), lmms::Engine::getSong(), lmms::Controller::loadSettings(), m_amountModel, m_baseModel, m_multiplierModel, m_phaseModel, m_speedModel, m_userDefSampleBuffer, m_waveModel, lmms::PathUtil::toAbsolute(), and updateSampleFunction().
nodeName()
QString lmms::LfoController::nodeName () const override virtual
Reimplemented from lmms::Controller.
Definition at line 257 of file LfoController.cpp.
saveSettings()
void lmms::LfoController::saveSettings (QDomDocument & _doc, QDomElement & _this) override virtual
Reimplemented from lmms::Controller.
Definition at line 217 of file LfoController.cpp.
References m_amountModel, m_baseModel, m_multiplierModel, m_phaseModel, m_speedModel, m_userDefSampleBuffer, m_waveModel, and lmms::Controller::saveSettings().
updateDuration
void lmms::LfoController::updateDuration () protected slot
Definition at line 157 of file LfoController.cpp.
References lmms::Engine::audioEngine(), m_duration, m_multiplierModel, m_speedModel, and lmms::AudioEngine::outputSampleRate().
Referenced by LfoController().
updatePhase
void lmms::LfoController::updatePhase () protected slot
Definition at line 150 of file LfoController.cpp.
References lmms::Song::getFrames(), lmms::Engine::getSong(), lmms::Controller::m_bufferLastUpdated, m_currentPhase, m_duration, and lmms::Controller::s_periods.
Referenced by LfoController().
updateSampleFunction
void lmms::LfoController::updateSampleFunction () protected slot
Definition at line 178 of file LfoController.cpp.
References lmms::Oscillator::Exponential, lmms::Oscillator::expSample(), m_sampleFunction, m_waveModel, lmms::Oscillator::MoogSaw, lmms::Oscillator::moogSawSample(), lmms::Oscillator::noiseSample(), lmms::Oscillator::Saw, lmms::Oscillator::sawSample(), lmms::Oscillator::Sine, lmms::Oscillator::sinSample(), lmms::Oscillator::Square, lmms::Oscillator::squareSample(), lmms::Oscillator::Triangle, lmms::Oscillator::triangleSample(), lmms::Oscillator::UserDefined, and lmms::Oscillator::WhiteNoise.
Referenced by LfoController(), and loadSettings().
updateValueBuffer()
void lmms::LfoController::updateValueBuffer () override protected virtual
Reimplemented from lmms::Controller.
Definition at line 89 of file LfoController.cpp.
References lmms::absFraction(), lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), m_amountModel, m_baseModel, lmms::Controller::m_bufferLastUpdated, m_currentPhase, m_duration, m_heldSample, m_phaseModel, m_phaseOffset, m_sampleFunction, m_userDefSampleBuffer, lmms::Controller::m_valueBuffer, m_waveModel, lmms::Controller::s_periods, lmms::Oscillator::UserDefined, lmms::Oscillator::userWaveSample(), lmms::ValueBuffer::values(), and lmms::Oscillator::WhiteNoise.
Friends And Related Symbol Documentation
gui::LfoControllerDialog
friend class gui::LfoControllerDialog friend
Definition at line 94 of file LfoController.h.
Member Data Documentation
m_amountModel
FloatModel lmms::LfoController::m_amountModel protected
Definition at line 74 of file LfoController.h.
Referenced by LfoController(), ~LfoController(), loadSettings(), saveSettings(), and updateValueBuffer().
m_baseModel
FloatModel lmms::LfoController::m_baseModel protected
Definition at line 72 of file LfoController.h.
Referenced by LfoController(), ~LfoController(), loadSettings(), saveSettings(), and updateValueBuffer().
m_currentPhase
float lmms::LfoController::m_currentPhase protected
Definition at line 81 of file LfoController.h.
Referenced by LfoController(), updatePhase(), and updateValueBuffer().
m_duration
float lmms::LfoController::m_duration protected
Definition at line 79 of file LfoController.h.
Referenced by LfoController(), updateDuration(), updatePhase(), and updateValueBuffer().
m_heldSample
float lmms::LfoController::m_heldSample private
Definition at line 86 of file LfoController.h.
Referenced by updateValueBuffer().
m_multiplierModel
IntModel lmms::LfoController::m_multiplierModel protected
Definition at line 77 of file LfoController.h.
Referenced by LfoController(), ~LfoController(), loadSettings(), saveSettings(), and updateDuration().
m_phaseModel
FloatModel lmms::LfoController::m_phaseModel protected
Definition at line 75 of file LfoController.h.
Referenced by LfoController(), ~LfoController(), loadSettings(), saveSettings(), and updateValueBuffer().
m_phaseOffset
float lmms::LfoController::m_phaseOffset protected
Definition at line 80 of file LfoController.h.
Referenced by LfoController(), and updateValueBuffer().
m_sampleFunction
sample_t(* lmms::LfoController::m_sampleFunction) (const float) protected
Definition at line 83 of file LfoController.h.
Referenced by LfoController(), updateSampleFunction(), and updateValueBuffer().
m_speedModel
TempoSyncKnobModel lmms::LfoController::m_speedModel protected
Definition at line 73 of file LfoController.h.
Referenced by LfoController(), ~LfoController(), loadSettings(), saveSettings(), and updateDuration().
m_userDefSampleBuffer
std::shared_ptr<const SampleBuffer> lmms::LfoController::m_userDefSampleBuffer = SampleBuffer::emptyBuffer() private
Definition at line 87 of file LfoController.h.
Referenced by LfoController(), lmms::gui::LfoControllerDialog::askUserDefWave(), loadSettings(), saveSettings(), and updateValueBuffer().
m_waveModel
IntModel lmms::LfoController::m_waveModel protected
Definition at line 76 of file LfoController.h.
Referenced by LfoController(), ~LfoController(), loadSettings(), saveSettings(), updateSampleFunction(), and updateValueBuffer().
The documentation for this class was generated from the following files:
include/LfoController.h
src/core/LfoController.cpp