LMMS: src/3rdparty/jack2/common/JackControlAPI.cpp File Reference
JackControlAPI.cpp File Reference
#include <stdint.h>
#include <dirent.h>
#include <pthread.h>
#include "types.h"
#include <string.h>
#include <errno.h>
#include <stdio.h>
#include <assert.h>
#include <signal.h>
#include "jslist.h"
#include "driver_interface.h"
#include "JackError.h"
#include "JackServer.h"
#include "shm.h"
#include "JackTools.h"
#include "JackControlAPI.h"
#include "JackLockedEngine.h"
#include "JackConstants.h"
#include "JackDriverLoader.h"
#include "JackServerGlobals.h"
Classes
struct jackctl_driver
struct jackctl_internal
struct jackctl_parameter
struct jackctl_server
struct jackctl_sigmask
Functions
static jack_driver_param_constraint_desc_t * get_realtime_priority_constraint ()
const char * jack_get_self_connect_mode_description (char mode)
static bool jackctl_add_driver_parameters (struct jackctl_driver *driver_ptr)
static struct jackctl_parameter * jackctl_add_parameter (JSList **parameters_list_ptr_ptr, const char *name, const char *short_description, const char *long_description, jackctl_param_type_t type, union jackctl_parameter_value *value_ptr, union jackctl_parameter_value *default_value_ptr, union jackctl_parameter_value value, jack_driver_param_constraint_desc_t *constraint_ptr=NULL)
static bool jackctl_create_param_list (const JSList *paramlist, JSList **retparamlist)
static void jackctl_destroy_param_list (JSList *params)
SERVER_EXPORT jack_driver_desc_t * jackctl_driver_get_desc (jackctl_driver *driver_ptr)
SERVER_EXPORT const char * jackctl_driver_get_name (jackctl_driver *driver_ptr)
Call this function to get name of driver.
SERVER_EXPORT const JSList * jackctl_driver_get_parameters (jackctl_driver *driver_ptr)
Call this function to get list of driver parameters.
SERVER_EXPORT jackctl_driver_type_t jackctl_driver_get_type (jackctl_driver *driver_ptr)
Call this function to get type of driver.
static int jackctl_drivers_load (struct jackctl_server *server_ptr)
static void jackctl_free_driver_parameters (struct jackctl_driver *driver_ptr)
SERVER_EXPORT const char * jackctl_internal_get_name (jackctl_internal *internal_ptr)
Call this function to get name of internal client.
SERVER_EXPORT const JSList * jackctl_internal_get_parameters (jackctl_internal *internal_ptr)
Call this function to get list of internal parameters.
static int jackctl_internals_load (struct jackctl_server *server_ptr)
SERVER_EXPORT bool jackctl_parameter_constraint_is_fake_value (jackctl_parameter_t *parameter_ptr)
Call this function to check whether parameter has fake values, i.e.
SERVER_EXPORT bool jackctl_parameter_constraint_is_strict (jackctl_parameter_t *parameter_ptr)
Call this function to check whether parameter constraint is strict, i.e.
SERVER_EXPORT union jackctl_parameter_value jackctl_parameter_get_default_value (jackctl_parameter *parameter_ptr)
Call this function to get parameter default value.
SERVER_EXPORT const char * jackctl_parameter_get_enum_constraint_description (jackctl_parameter *parameter_ptr, uint32_t index)
Call this function to get parameter enumeration value description.
SERVER_EXPORT union jackctl_parameter_value jackctl_parameter_get_enum_constraint_value (jackctl_parameter *parameter_ptr, uint32_t index)
Call this function to get parameter enumeration value.
SERVER_EXPORT uint32_t jackctl_parameter_get_enum_constraints_count (jackctl_parameter *parameter_ptr)
Call this function get how many enumeration values parameter has.
SERVER_EXPORT char jackctl_parameter_get_id (jackctl_parameter_t *parameter_ptr)
Call this function to get parameter character.
SERVER_EXPORT const char * jackctl_parameter_get_long_description (jackctl_parameter *parameter_ptr)
Call this function to get parameter long description.
SERVER_EXPORT const char * jackctl_parameter_get_name (jackctl_parameter *parameter_ptr)
Call this function to get parameter name.
SERVER_EXPORT void jackctl_parameter_get_range_constraint (jackctl_parameter *parameter_ptr, union jackctl_parameter_value *min_ptr, union jackctl_parameter_value *max_ptr)
Call this function to get parameter range.
SERVER_EXPORT const char * jackctl_parameter_get_short_description (jackctl_parameter *parameter_ptr)
Call this function to get parameter short description.
SERVER_EXPORT jackctl_param_type_t jackctl_parameter_get_type (jackctl_parameter *parameter_ptr)
Call this function to get parameter type.
SERVER_EXPORT union jackctl_parameter_value jackctl_parameter_get_value (jackctl_parameter *parameter_ptr)
Call this function to get parameter value.
SERVER_EXPORT bool jackctl_parameter_has_enum_constraint (jackctl_parameter *parameter_ptr)
Call this function check whether parameter has enumeration constraint.
SERVER_EXPORT bool jackctl_parameter_has_range_constraint (jackctl_parameter *parameter_ptr)
Call this function check whether parameter has range constraint.
SERVER_EXPORT bool jackctl_parameter_is_set (jackctl_parameter *parameter_ptr)
Call this function to check whether parameter has been set, or its default value is being used.
SERVER_EXPORT bool jackctl_parameter_reset (jackctl_parameter *parameter_ptr)
Call this function to reset parameter to its default value.
SERVER_EXPORT bool jackctl_parameter_set_value (jackctl_parameter *parameter_ptr, const union jackctl_parameter_value *value_ptr)
Call this function to set parameter value.
SERVER_EXPORT bool jackctl_server_add_slave (jackctl_server *server_ptr, jackctl_driver *driver_ptr)
Call this function to add a slave in the driver slave list.
SERVER_EXPORT bool jackctl_server_close (jackctl_server *server_ptr)
Call this function to close JACK server.
SERVER_EXPORT jackctl_server_t * jackctl_server_create (bool(*on_device_acquire)(const char *device_name), void(*on_device_release)(const char *device_name))
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK PROJECTS
SERVER_EXPORT jackctl_server_t * jackctl_server_create2 (bool(*on_device_acquire)(const char *device_name), void(*on_device_release)(const char *device_name), void(*on_device_reservation_loop)(void))
Call this function to create server object.
SERVER_EXPORT void jackctl_server_destroy (jackctl_server *server_ptr)
Call this function to destroy server object.
static void jackctl_server_free_drivers (struct jackctl_server *server_ptr)
static void jackctl_server_free_internals (struct jackctl_server *server_ptr)
static void jackctl_server_free_parameters (struct jackctl_server *server_ptr)
SERVER_EXPORT const JSList * jackctl_server_get_drivers_list (jackctl_server *server_ptr)
Call this function to get list of available drivers.
SERVER_EXPORT const JSList * jackctl_server_get_internals_list (jackctl_server *server_ptr)
Call this function to get list of available internal clients.
SERVER_EXPORT const JSList * jackctl_server_get_parameters (jackctl_server *server_ptr)
Call this function to get list of server parameters.
SERVER_EXPORT bool jackctl_server_load_internal (jackctl_server *server_ptr, jackctl_internal *internal)
Call this function to load one internal client.
SERVER_EXPORT bool jackctl_server_load_session_file (jackctl_server *server_ptr, const char *file)
Call this function to load a session file.
SERVER_EXPORT bool jackctl_server_open (jackctl_server *server_ptr, jackctl_driver *driver_ptr)
Call this function to open JACK server.
SERVER_EXPORT bool jackctl_server_remove_slave (jackctl_server *server_ptr, jackctl_driver *driver_ptr)
Call this function to remove a slave from the driver slave list.
SERVER_EXPORT bool jackctl_server_start (jackctl_server *server_ptr)
Call this function to start JACK server.
SERVER_EXPORT bool jackctl_server_stop (jackctl_server *server_ptr)
Call this function to stop JACK server.
SERVER_EXPORT bool jackctl_server_switch_master (jackctl_server *server_ptr, jackctl_driver *driver_ptr)
Call this function to switch master driver.
SERVER_EXPORT bool jackctl_server_unload_internal (jackctl_server *server_ptr, jackctl_internal *internal)
Call this function to unload one internal client.
SERVER_EXPORT jackctl_sigmask_t * jackctl_setup_signals (unsigned int flags)
Call this function to setup process signal handling.
SERVER_EXPORT void jackctl_wait_signals (jackctl_sigmask_t *sigmask)
Call this function to wait on a signal set.
static void signal_handler (int sig)
Variables
static struct jack_constraint_enum_char_descriptor self_connect_mode_constraint_descr_array []
static jackctl_sigmask sigmask
Function Documentation
get_realtime_priority_constraint()
jack_driver_param_constraint_desc_t * get_realtime_priority_constraint () static
Definition at line 720 of file JackControlAPI.cpp.
References jack_driver_param_constraint_desc_t::constraint, jack_driver_param_constraint_desc_t::flags, jack_driver_param_value_t::i, JACK_CONSTRAINT_FLAG_RANGE, jack_error, jack_get_thread_realtime_priority_range(), jack_driver_param_constraint_desc_t::max, max, jack_driver_param_constraint_desc_t::min, min, and jack_driver_param_constraint_desc_t::range.
Referenced by jackctl_server_create2().
jack_get_self_connect_mode_description()
const char * jack_get_self_connect_mode_description (char mode)
Definition at line 145 of file JackControlAPI.cpp.
References self_connect_mode_constraint_descr_array, jack_constraint_enum_char_descriptor::short_desc, and jack_constraint_enum_char_descriptor::value.
Referenced by Jack::JackServer::JackServer().
jackctl_add_driver_parameters()
bool jackctl_add_driver_parameters (struct jackctl_driver * driver_ptr) static
Definition at line 231 of file JackControlAPI.cpp.
References jackctl_parameter_value::b, jack_driver_param_value_t::c, jackctl_parameter_value::c, jack_driver_param_desc_t::character, jack_driver_param_desc_t::constraint, jackctl_driver::desc_ptr, jackctl_parameter::driver_ptr, i, jack_driver_param_value_t::i, jackctl_parameter_value::i, jackctl_parameter::id, jack_error, jackctl_add_parameter(), jackctl_free_driver_parameters(), JackDriverParamBool, JackDriverParamChar, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, JackParamBool, JackParamChar, JackParamInt, JackParamString, JackParamUInt, jack_driver_param_desc_t::long_desc, jack_driver_param_desc_t::name, jack_driver_desc_t::nparams, jackctl_driver::parameters, jack_driver_desc_t::params, jack_driver_param_desc_t::short_desc, jack_driver_param_value_t::str, jackctl_parameter_value::str, jack_driver_param_desc_t::type, jack_driver_param_value_t::ui, jackctl_parameter_value::ui, and jack_driver_param_desc_t::value.
Referenced by jackctl_drivers_load(), and jackctl_internals_load().
jackctl_add_parameter()
struct jackctl_parameter * jackctl_add_parameter (JSList ** parameters_list_ptr_ptr, const char * name, const char * short_description, const char * long_description, jackctl_param_type_t type, union jackctl_parameter_value * value_ptr, union jackctl_parameter_value * default_value_ptr, union jackctl_parameter_value value, jack_driver_param_constraint_desc_t * constraint_ptr = NULL) static
Definition at line 159 of file JackControlAPI.cpp.
References jackctl_parameter::constraint_ptr, jackctl_parameter::default_value, jackctl_parameter::default_value_ptr, jackctl_parameter::driver_ptr, jackctl_parameter::id, jackctl_parameter::is_set, jack_error, jack_slist_append(), jackctl_parameter::long_description, jackctl_parameter::name, jackctl_parameter::short_description, jackctl_parameter::type, jackctl_parameter::value, and jackctl_parameter::value_ptr.
Referenced by jackctl_add_driver_parameters(), and jackctl_server_create2().
jackctl_create_param_list()
bool jackctl_create_param_list (const JSList * paramlist, JSList ** retparamlist) static
Definition at line 321 of file JackControlAPI.cpp.
References jackctl_parameter_value::b, jack_driver_param_value_t::c, jackctl_parameter_value::c, jack_driver_param_t::character, _JSList::data, jack_driver_param_value_t::i, jackctl_parameter_value::i, jackctl_parameter::id, jackctl_parameter::is_set, jack_error, jack_slist_append(), jackctl_destroy_param_list(), JackParamBool, JackParamChar, JackParamInt, JackParamString, JackParamUInt, _JSList::next, jack_driver_param_value_t::str, jackctl_parameter_value::str, jackctl_parameter::type, jack_driver_param_value_t::ui, jackctl_parameter_value::ui, jack_driver_param_t::value, and jackctl_parameter::value_ptr.
Referenced by jackctl_server_add_slave(), jackctl_server_load_internal(), jackctl_server_open(), and jackctl_server_switch_master().
jackctl_destroy_param_list()
void jackctl_destroy_param_list (JSList * params) static
Definition at line 303 of file JackControlAPI.cpp.
References _JSList::data, and _JSList::next.
Referenced by jackctl_create_param_list(), jackctl_server_add_slave(), jackctl_server_load_internal(), jackctl_server_open(), and jackctl_server_switch_master().
jackctl_driver_get_desc()
SERVER_EXPORT jack_driver_desc_t * jackctl_driver_get_desc (jackctl_driver * driver_ptr)
Definition at line 1142 of file JackControlAPI.cpp.
References jackctl_driver::desc_ptr, and SERVER_EXPORT.
Referenced by jackctl_driver_params_parse().
jackctl_drivers_load()
int jackctl_drivers_load (struct jackctl_server * server_ptr) static
Definition at line 383 of file JackControlAPI.cpp.
References _JSList::data, jackctl_driver::desc_ptr, jackctl_server::drivers, jackctl_driver::infos, jack_drivers_load(), jack_error, jack_slist_append(), jackctl_add_driver_parameters(), _JSList::next, and jackctl_driver::parameters.
Referenced by jackctl_server_create2().
jackctl_free_driver_parameters()
void jackctl_free_driver_parameters (struct jackctl_driver * driver_ptr) static
Definition at line 214 of file JackControlAPI.cpp.
References _JSList::data, jackctl_parameter::driver_ptr, jack_constraint_free(), _JSList::next, and jackctl_driver::parameters.
Referenced by jackctl_add_driver_parameters(), jackctl_server_free_drivers(), and jackctl_server_free_internals().
jackctl_internals_load()
int jackctl_internals_load (struct jackctl_server * server_ptr) static
Definition at line 452 of file JackControlAPI.cpp.
References _JSList::data, jackctl_internal::desc_ptr, jackctl_server::internals, jack_error, jack_internals_load(), jack_slist_append(), jackctl_add_driver_parameters(), _JSList::next, jackctl_driver::parameters, jackctl_internal::parameters, and jackctl_internal::refnum.
Referenced by jackctl_server_create2().
jackctl_server_free_drivers()
void jackctl_server_free_drivers (struct jackctl_server * server_ptr) static
Definition at line 430 of file JackControlAPI.cpp.
References _JSList::data, jackctl_driver::desc_ptr, jackctl_server::drivers, jackctl_free_driver_parameters(), _JSList::next, and jack_driver_desc_t::params.
Referenced by jackctl_server_destroy().
jackctl_server_free_internals()
void jackctl_server_free_internals (struct jackctl_server * server_ptr) static
Definition at line 499 of file JackControlAPI.cpp.
References _JSList::data, jackctl_driver::desc_ptr, jackctl_server::internals, jackctl_free_driver_parameters(), _JSList::next, and jack_driver_desc_t::params.
Referenced by jackctl_server_destroy().
jackctl_server_free_parameters()
void jackctl_server_free_parameters (struct jackctl_server * server_ptr) static
Definition at line 522 of file JackControlAPI.cpp.
References _JSList::data, jack_constraint_free(), _JSList::next, and jackctl_server::parameters.
Referenced by jackctl_server_create2(), and jackctl_server_destroy().
signal_handler()
void signal_handler (int sig) static
Definition at line 587 of file JackControlAPI.cpp.
Referenced by jackctl_setup_signals().
Variable Documentation
self_connect_mode_constraint_descr_array
struct jack_constraint_enum_char_descriptor self_connect_mode_constraint_descr_array[] static
Initial value:
=
{
    { ' ', "Don't restrict self connect requests" },
    { 'E', "Fail self connect requests to external ports only" },
    { 'e', "Ignore self connect requests to external ports only" },
    { 'A', "Fail all self connect requests" },
    { 'a', "Ignore all self connect requests" },
    { 0 }
}
Definition at line 51 of file JackControlAPI.cpp.
Referenced by jack_get_self_connect_mode_description(), and jackctl_server_create2().
sigmask
jackctl_sigmask sigmask static
Definition at line 583 of file JackControlAPI.cpp.