LMMS: Jack::JackActivationCount Class Reference
Jack::JackActivationCount Class Reference
Client activation counter.
#include <JackActivationCount.h>
Public Member Functions
JackActivationCount ()
void DecValue ()
int GetValue () const
void IncValue ()
void Reset ()
void SetValue (int val)
bool Signal (JackSynchro *synchro, JackClientControl *control)
Private Attributes
SInt32 fCount
SInt32 fValue
Detailed Description
Client activation counter.
Definition at line 37 of file JackActivationCount.h.
Constructor & Destructor Documentation
JackActivationCount()
Jack::JackActivationCount::JackActivationCount () inline
Definition at line 47 of file JackActivationCount.h.
References JackActivationCount(), fCount, fValue, and offsetof.
Referenced by JackActivationCount().
Member Function Documentation
DecValue()
void Jack::JackActivationCount::DecValue () inline
Definition at line 70 of file JackActivationCount.h.
References fCount.
GetValue()
int Jack::JackActivationCount::GetValue () const inline
Definition at line 75 of file JackActivationCount.h.
References fValue.
IncValue()
void Jack::JackActivationCount::IncValue () inline
Definition at line 65 of file JackActivationCount.h.
References fCount.
Reset()
void Jack::JackActivationCount::Reset () inline
Definition at line 55 of file JackActivationCount.h.
References fCount, and fValue.
SetValue()
void Jack::JackActivationCount::SetValue (int val) inline
Definition at line 60 of file JackActivationCount.h.
References fCount.
Signal()
bool Jack::JackActivationCount::Signal (JackSynchro * synchro, JackClientControl * control)
Definition at line 29 of file JackActivationCount.cpp.
References DEC_ATOMIC(), Jack::JackClientControl::fRefNum, fValue, jack_log(), and Jack::JackAndroidSemaphore::Signal().
Member Data Documentation
fCount
SInt32 Jack::JackActivationCount::fCount private
Definition at line 43 of file JackActivationCount.h.
Referenced by JackActivationCount(), DecValue(), IncValue(), Reset(), and SetValue().
fValue
SInt32 Jack::JackActivationCount::fValue private
Definition at line 42 of file JackActivationCount.h.
Referenced by JackActivationCount(), GetValue(), Reset(), and Signal().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackActivationCount.h
src/3rdparty/jack2/common/JackActivationCount.cpp