LMMS: Jack::JackEngine Class Reference
Jack::JackEngine Class Reference
Engine description.
#include <JackEngine.h>
Public Member Functions
JackEngine (JackGraphManager *manager, JackSynchro *table, JackEngineControl *controler, char self_connect_mode)
~JackEngine ()
int ClientActivate (int refnum, bool is_real_time, bool wait)
int ClientCheck (const char *name, jack_uuid_t uuid, char *name_res, int protocol, int options, int *status)
int ClientDeactivate (int refnum, bool wait)
int ClientExternalClose (int refnum)
int ClientExternalOpen (const char *name, int pid, jack_uuid_t uuid, int *ref, int *shared_engine, int *shared_client, int *shared_graph_manager)
int ClientHasSessionCallback (const char *name)
int ClientInternalClose (int refnum, bool wait)
int ClientInternalOpen (const char *name, int *ref, JackEngineControl **shared_engine, JackGraphManager **shared_manager, JackClientInterface *client, bool wait)
void ClientKill (int refnum)
int Close ()
int ComputeTotalLatencies ()
int GetClientNameForUUID (const char *uuid, char *name_res)
int GetClientPID (const char *name)
int GetClientRefNum (const char *name)
int GetInternalClientName (int int_ref, char *name_res)
int GetUUIDForClientName (const char *client_name, char *uuid_res)
int InternalClientHandle (const char *client_name, int *status, int *int_ref)
int InternalClientUnload (int refnum, int *status)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyClientXRun (int refnum)
void NotifyDriverXRun ()
void NotifyFailure (int code, const char *reason)
void NotifyFreewheel (bool onoff)
void NotifyGraphReorder ()
void NotifyQuit ()
void NotifySampleRate (jack_nframes_t sample_rate)
int Open ()
int PortConnect (int refnum, const char *src, const char *dst)
int PortConnect (int refnum, jack_port_id_t src, jack_port_id_t dst)
int PortDisconnect (int refnum, const char *src, const char *dst)
int PortDisconnect (int refnum, jack_port_id_t src, jack_port_id_t dst)
int PortRegister (int refnum, const char *name, const char *type, unsigned int flags, unsigned int buffer_size, jack_port_id_t *port)
int PortRename (int refnum, jack_port_id_t port, const char *name)
int PortSetDefaultMetadata (jack_port_id_t port, const char *pretty_name)
int PortUnRegister (int refnum, jack_port_id_t port)
bool Process (jack_time_t cur_cycle_begin, jack_time_t prev_cycle_end)
int PropertyChangeNotify (jack_uuid_t subject, const char *key, jack_property_change_t change)
int ReserveClientName (const char *name, const char *uuid)
void SessionNotify (int refnum, const char *target, jack_session_event_type_t type, const char *path, detail::JackChannelTransactionInterface *socket, JackSessionNotifyResult **result)
int SessionReply (int refnum)
Public Member Functions inherited from Jack::JackLockAble
bool Lock ()
bool Trylock ()
bool Unlock ()
Private Member Functions
int AllocateRefnum ()
bool CheckClient (int refnum)
int CheckPortsConnect (int refnum, jack_port_id_t src, jack_port_id_t dst)
void CheckXRun (jack_time_t callback_usecs)
bool ClientCheckName (const char *name)
int ClientCloseAux (int refnum, bool wait)
int ClientNotify (JackClientInterface *client, int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
void EnsureUUID (jack_uuid_t uuid)
bool GenerateUniqueName (char *name)
void NotifyActivate (int refnum)
int NotifyAddClient (JackClientInterface *new_client, const char *new_name, int refnum)
void NotifyClient (int refnum, int event, int sync, const char *message, int value1, int value2)
void NotifyClients (int event, int sync, const char *message, int value1, int value2)
void NotifyPortConnect (jack_port_id_t src, jack_port_id_t dst, bool onoff)
void NotifyPortRegistation (jack_port_id_t port_index, bool onoff)
void NotifyPortRename (jack_port_id_t src, const char *old_name)
void NotifyRemoveClient (const char *name, int refnum)
void ProcessCurrent (jack_time_t callback_usecs)
void ProcessNext (jack_time_t callback_usecs)
void ReleaseRefnum (int refnum)
Private Attributes
JackServerNotifyChannel fChannel
JackClientInterface * fClientTable [CLIENT_NUM]
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
jack_time_t fLastSwitchUsecs
JackMetadata fMetadata
std::map< int, std::string > fReservationMap
char fSelfConnectMode
int fSessionPendingReplies
JackSessionNotifyResult * fSessionResult
detail::JackChannelTransactionInterface * fSessionTransaction
JackProcessSync fSignal
To communicate between the RT thread and server.
JackSynchro * fSynchroTable
Friends
class JackLockedEngine
Additional Inherited Members
Protected Member Functions inherited from Jack::JackLockAble
JackLockAble (const char *name=NULL)
~JackLockAble ()
Protected Attributes inherited from Jack::JackLockAble
JackMutex fMutex
Detailed Description
Engine description.
Definition at line 44 of file JackEngine.h.
Constructor & Destructor Documentation
JackEngine()
Jack::JackEngine::JackEngine (JackGraphManager * manager, JackSynchro * table, JackEngineControl * controler, char self_connect_mode)
Definition at line 43 of file JackEngine.cpp.
References Jack::JackLockAble::JackLockAble(), CLIENT_NUM, fClientTable, fEngineControl, fGraphManager, fLastSwitchUsecs, fMetadata, fSelfConnectMode, fSessionPendingReplies, fSessionResult, fSessionTransaction, fSignal, fSynchroTable, and i.
~JackEngine()
Jack::JackEngine::~JackEngine ()
Definition at line 64 of file JackEngine.cpp.
Member Function Documentation
AllocateRefnum()
int Jack::JackEngine::AllocateRefnum () private
Definition at line 113 of file JackEngine.cpp.
References CLIENT_NUM, fClientTable, i, and jack_log().
Referenced by ClientExternalOpen(), and ClientInternalOpen().
CheckClient()
bool Jack::JackEngine::CheckClient (int refnum) inline private
Definition at line 92 of file JackEngine.h.
References CLIENT_NUM, and fClientTable.
CheckPortsConnect()
int Jack::JackEngine::CheckPortsConnect (int refnum, jack_port_id_t src, jack_port_id_t dst) private
Definition at line 935 of file JackEngine.cpp.
References fGraphManager, fSelfConnectMode, Jack::JackPort::GetName(), Jack::JackPort::GetRefNum(), jack_info(), and jack_log().
Referenced by PortConnect(), and PortDisconnect().
CheckXRun()
void Jack::JackEngine::CheckXRun (jack_time_t callback_usecs) private
Definition at line 215 of file JackEngine.cpp.
References ALL_CLIENTS, client(), CLIENT_NUM, fChannel, fClientTable, fEngineControl, Jack::JackClientTiming::fFinishedAt, fGraphManager, Finished, Jack::JackClientTiming::fStatus, i, jack_error, Jack::kXRunCallback, NotTriggered, and Jack::State2String().
Referenced by ProcessCurrent().
ClientActivate()
int Jack::JackEngine::ClientActivate (int refnum, bool is_real_time, bool wait)
Definition at line 792 of file JackEngine.cpp.
References client(), EMPTY, fClientTable, fEngineControl, fGraphManager, fSignal, i, jack_error, jack_log(), NotifyActivate(), NotifyPortRegistation(), and PORT_NUM_FOR_CLIENT.
ClientCheck()
int Jack::JackEngine::ClientCheck (const char * name, jack_uuid_t uuid, char * name_res, int protocol, int options, int * status)
Definition at line 482 of file JackEngine.cpp.
References ClientCheckName(), fReservationMap, GenerateUniqueName(), JACK_CLIENT_NAME_SIZE, jack_error, jack_log(), JACK_PROTOCOL_VERSION, JackFailure, JackNameNotUnique, JackUseExactName, and JackVersionError.
ClientCheckName()
bool Jack::JackEngine::ClientCheckName (const char * name) private
Definition at line 552 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, fReservationMap, and i.
Referenced by ClientCheck(), GenerateUniqueName(), and ReserveClientName().
ClientCloseAux()
int Jack::JackEngine::ClientCloseAux (int refnum, bool wait) private
Definition at line 739 of file JackEngine.cpp.
References client(), EMPTY, fClientTable, fEngineControl, fGraphManager, fMetadata, fSignal, fSynchroTable, i, jack_error, jack_log(), jack_uuid_copy(), JACK_UUID_EMPTY_INITIALIZER, NotifyRemoveClient(), PORT_NUM_FOR_CLIENT, PortUnRegister(), PropertyChangeNotify(), PropertyDeleted, and ReleaseRefnum().
Referenced by ClientExternalClose(), and ClientInternalClose().
ClientDeactivate()
int Jack::JackEngine::ClientDeactivate (int refnum, bool wait)
Definition at line 827 of file JackEngine.cpp.
References ALL_PORTS, client(), EMPTY, fClientTable, fEngineControl, fGraphManager, fLastSwitchUsecs, fSignal, i, jack_error, jack_log(), NotifyPortRegistation(), PORT_NUM_FOR_CLIENT, and PortDisconnect().
Referenced by ClientKill().
ClientExternalClose()
int Jack::JackEngine::ClientExternalClose (int refnum)
Definition at line 721 of file JackEngine.cpp.
References client(), ClientCloseAux(), fClientTable, and jack_log().
Referenced by ClientKill().
ClientExternalOpen()
int Jack::JackEngine::ClientExternalOpen (const char * name, int pid, jack_uuid_t uuid, int * ref, int * shared_engine, int * shared_client, int * shared_graph_manager)
Definition at line 610 of file JackEngine.cpp.
References AllocateRefnum(), client(), DRIVER_OPEN_TIMEOUT, EnsureUUID(), fClientTable, fEngineControl, fGraphManager, fReservationMap, fSignal, fSynchroTable, JACK_CLIENT_NAME_SIZE, jack_client_uuid_generate(), jack_error, jack_log(), jack_uuid_empty(), and NotifyAddClient().
ClientHasSessionCallback()
int Jack::JackEngine::ClientHasSessionCallback (const char * name)
Definition at line 1256 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, i, and Jack::kSessionCallback.
ClientInternalClose()
int Jack::JackEngine::ClientInternalClose (int refnum, bool wait)
Definition at line 733 of file JackEngine.cpp.
References ClientCloseAux(), and jack_log().
ClientInternalOpen()
int Jack::JackEngine::ClientInternalOpen (const char * name, int * ref, JackEngineControl ** shared_engine, JackGraphManager ** shared_manager, JackClientInterface * client, bool wait)
Definition at line 678 of file JackEngine.cpp.
References AllocateRefnum(), client(), DRIVER_OPEN_TIMEOUT, fClientTable, fEngineControl, fGraphManager, fSignal, fSynchroTable, jack_error, jack_log(), and NotifyAddClient().
ClientKill()
void Jack::JackEngine::ClientKill (int refnum)
Definition at line 865 of file JackEngine.cpp.
References ClientDeactivate(), ClientExternalClose(), jack_error, and jack_log().
ClientNotify()
int Jack::JackEngine::ClientNotify (JackClientInterface * client, int refnum, const char * name, int notify, int sync, const char * message, int value1, int value2) private
Definition at line 286 of file JackEngine.cpp.
References client(), jack_error, jack_log(), Jack::JackLockAble::Lock(), and Jack::JackLockAble::Unlock().
Referenced by NotifyAddClient(), NotifyClient(), and NotifyRemoveClient().
Close()
int Jack::JackEngine::Close ()
Definition at line 80 of file JackEngine.cpp.
References CLIENT_NUM, fChannel, fClientTable, fEngineControl, i, and jack_log().
ComputeTotalLatencies()
int Jack::JackEngine::ComputeTotalLatencies ()
Definition at line 237 of file JackEngine.cpp.
References fGraphManager, Jack::kLatencyCallback, and NotifyClient().
Referenced by NotifyGraphReorder().
EnsureUUID()
void Jack::JackEngine::EnsureUUID (jack_uuid_t uuid) private
Definition at line 570 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, i, jack_uuid_clear(), jack_uuid_compare(), and jack_uuid_empty().
Referenced by ClientExternalOpen(), and ReserveClientName().
GenerateUniqueName()
bool Jack::JackEngine::GenerateUniqueName (char * name) private
Definition at line 519 of file JackEngine.cpp.
References ClientCheckName(), JACK_CLIENT_NAME_SIZE, and jack_error.
Referenced by ClientCheck().
GetClientNameForUUID()
int Jack::JackEngine::GetClientNameForUUID (const char * uuid, char * name_res)
Definition at line 1214 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, i, JACK_CLIENT_NAME_SIZE, jack_uuid_compare(), and jack_uuid_parse().
GetClientPID()
int Jack::JackEngine::GetClientPID (const char * name)
Definition at line 585 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, and i.
GetClientRefNum()
int Jack::JackEngine::GetClientRefNum (const char * name)
Definition at line 597 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, and i.
GetInternalClientName()
int Jack::JackEngine::GetInternalClientName (int int_ref, char * name_res)
Definition at line 438 of file JackEngine.cpp.
References client(), fClientTable, and JACK_CLIENT_NAME_SIZE.
GetUUIDForClientName()
int Jack::JackEngine::GetUUIDForClientName (const char * client_name, char * uuid_res)
Definition at line 1200 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, i, and jack_uuid_unparse().
InternalClientHandle()
int Jack::JackEngine::InternalClientHandle (const char * client_name, int * status, int * int_ref)
Definition at line 446 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, i, jack_log(), JackFailure, and JackNoSuchClient.
InternalClientUnload()
int Jack::JackEngine::InternalClientUnload (int refnum, int * status)
Definition at line 464 of file JackEngine.cpp.
References client(), fClientTable, JackFailure, and JackNoSuchClient.
NotifyActivate()
void Jack::JackEngine::NotifyActivate (int refnum) private
Definition at line 429 of file JackEngine.cpp.
References Jack::kActivateClient, and NotifyClient().
Referenced by ClientActivate().
NotifyAddClient()
int Jack::JackEngine::NotifyAddClient (JackClientInterface * new_client, const char * new_name, int refnum) private
Definition at line 329 of file JackEngine.cpp.
References CLIENT_NUM, ClientNotify(), fClientTable, Jack::JackClientControl::fName, Jack::JackClientInterface::GetClientControl(), i, jack_error, jack_log(), and Jack::kAddClient.
Referenced by ClientExternalOpen(), and ClientInternalOpen().
NotifyBufferSize()
void Jack::JackEngine::NotifyBufferSize (jack_nframes_t buffer_size)
Definition at line 385 of file JackEngine.cpp.
References Jack::kBufferSizeCallback, and NotifyClients().
NotifyClient()
void Jack::JackEngine::NotifyClient (int refnum, int event, int sync, const char * message, int value1, int value2) private
Definition at line 314 of file JackEngine.cpp.
References client(), ClientNotify(), and fClientTable.
Referenced by ComputeTotalLatencies(), NotifyActivate(), NotifyClients(), and NotifyClientXRun().
NotifyClients()
void Jack::JackEngine::NotifyClients (int event, int sync, const char * message, int value1, int value2) private
Definition at line 322 of file JackEngine.cpp.
References CLIENT_NUM, i, and NotifyClient().
Referenced by NotifyBufferSize(), NotifyClientXRun(), NotifyFailure(), NotifyFreewheel(), NotifyGraphReorder(), NotifyPortConnect(), NotifyPortRegistation(), NotifyPortRename(), and NotifySampleRate().
NotifyClientXRun()
void Jack::JackEngine::NotifyClientXRun (int refnum)
Definition at line 370 of file JackEngine.cpp.
References ALL_CLIENTS, Jack::kXRunCallback, NotifyClient(), and NotifyClients().
NotifyDriverXRun()
void Jack::JackEngine::NotifyDriverXRun ()
Definition at line 364 of file JackEngine.cpp.
References ALL_CLIENTS, fChannel, and Jack::kXRunCallback.
NotifyFailure()
void Jack::JackEngine::NotifyFailure (int code, const char * reason)
Definition at line 395 of file JackEngine.cpp.
References Jack::kShutDownCallback, and NotifyClients().
NotifyFreewheel()
void Jack::JackEngine::NotifyFreewheel (bool onoff)
Definition at line 400 of file JackEngine.cpp.
References fEngineControl, Jack::kStartFreewheelCallback, Jack::kStopFreewheelCallback, and NotifyClients().
NotifyGraphReorder()
void Jack::JackEngine::NotifyGraphReorder ()
Definition at line 379 of file JackEngine.cpp.
References ComputeTotalLatencies(), Jack::kGraphOrderCallback, and NotifyClients().
NotifyPortConnect()
void Jack::JackEngine::NotifyPortConnect (jack_port_id_t src, jack_port_id_t dst, bool onoff) private
Definition at line 424 of file JackEngine.cpp.
References Jack::kPortConnectCallback, Jack::kPortDisconnectCallback, and NotifyClients().
Referenced by PortConnect(), and PortDisconnect().
NotifyPortRegistation()
void Jack::JackEngine::NotifyPortRegistation (jack_port_id_t port_index, bool onoff) private
Definition at line 414 of file JackEngine.cpp.
References Jack::kPortRegistrationOffCallback, Jack::kPortRegistrationOnCallback, and NotifyClients().
Referenced by ClientActivate(), ClientDeactivate(), PortRegister(), and PortUnRegister().
NotifyPortRename()
void Jack::JackEngine::NotifyPortRename (jack_port_id_t src, const char * old_name) private
Definition at line 419 of file JackEngine.cpp.
References Jack::kPortRenameCallback, and NotifyClients().
Referenced by PortRename().
NotifyQuit()
void Jack::JackEngine::NotifyQuit ()
Definition at line 103 of file JackEngine.cpp.
References fChannel.
NotifyRemoveClient()
void Jack::JackEngine::NotifyRemoveClient (const char * name, int refnum) private
Definition at line 352 of file JackEngine.cpp.
References client(), CLIENT_NUM, ClientNotify(), fClientTable, i, and Jack::kRemoveClient.
Referenced by ClientCloseAux().
NotifySampleRate()
void Jack::JackEngine::NotifySampleRate (jack_nframes_t sample_rate)
Definition at line 390 of file JackEngine.cpp.
References Jack::kSampleRateCallback, and NotifyClients().
Open()
int Jack::JackEngine::Open ()
Definition at line 67 of file JackEngine.cpp.
References fChannel, fEngineControl, jack_error, and jack_log().
PortConnect() [1/2]
int Jack::JackEngine::PortConnect (int refnum, const char * src, const char * dst)
Definition at line 975 of file JackEngine.cpp.
References fGraphManager, jack_log(), and PortConnect().
Referenced by PortConnect().
PortConnect() [2/2]
int Jack::JackEngine::PortConnect (int refnum, jack_port_id_t src, jack_port_id_t dst)
Definition at line 985 of file JackEngine.cpp.
References CheckPortsConnect(), client(), fClientTable, fGraphManager, jack_error, jack_log(), and NotifyPortConnect().
PortDisconnect() [1/2]
int Jack::JackEngine::PortDisconnect (int refnum, const char * src, const char * dst)
Definition at line 1027 of file JackEngine.cpp.
References fGraphManager, jack_log(), and PortDisconnect().
Referenced by ClientDeactivate(), PortDisconnect(), PortDisconnect(), and PortUnRegister().
PortDisconnect() [2/2]
int Jack::JackEngine::PortDisconnect (int refnum, jack_port_id_t src, jack_port_id_t dst)
Definition at line 1037 of file JackEngine.cpp.
References ALL_PORTS, CheckPortsConnect(), CONNECTION_NUM_FOR_PORT, EMPTY, fGraphManager, Jack::JackPort::GetFlags(), i, jack_log(), JackPortIsOutput, NotifyPortConnect(), and PortDisconnect().
PortRegister()
int Jack::JackEngine::PortRegister (int refnum, const char * name, const char * type, unsigned int flags, unsigned int buffer_size, jack_port_id_t * port)
Definition at line 880 of file JackEngine.cpp.
References client(), fClientTable, fEngineControl, fGraphManager, jack_error, jack_log(), NO_PORT, and NotifyPortRegistation().
PortRename()
int Jack::JackEngine::PortRename (int refnum, jack_port_id_t port, const char * name)
Definition at line 1080 of file JackEngine.cpp.
References fGraphManager, NotifyPortRename(), and REAL_JACK_PORT_NAME_SIZE.
PortSetDefaultMetadata()
int Jack::JackEngine::PortSetDefaultMetadata (jack_port_id_t port, const char * pretty_name)
Definition at line 1089 of file JackEngine.cpp.
References fMetadata, JACK_METADATA_HARDWARE, JACK_METADATA_PRETTY_NAME, and jack_port_uuid_generate().
PortUnRegister()
int Jack::JackEngine::PortUnRegister (int refnum, jack_port_id_t port)
Definition at line 903 of file JackEngine.cpp.
References ALL_PORTS, client(), fClientTable, fGraphManager, fMetadata, jack_log(), jack_port_uuid_generate(), jack_uuid_empty(), NotifyPortRegistation(), PortDisconnect(), PropertyChangeNotify(), and PropertyDeleted.
Referenced by ClientCloseAux().
Process()
bool Jack::JackEngine::Process (jack_time_t cur_cycle_begin, jack_time_t prev_cycle_end)
Definition at line 165 of file JackEngine.cpp.
References fClientTable, fEngineControl, fGraphManager, fLastSwitchUsecs, jack_log(), ProcessCurrent(), and ProcessNext().
ProcessCurrent()
void Jack::JackEngine::ProcessCurrent (jack_time_t callback_usecs) private
Definition at line 157 of file JackEngine.cpp.
References CheckXRun(), and fGraphManager.
Referenced by Process().
ProcessNext()
void Jack::JackEngine::ProcessNext (jack_time_t callback_usecs) private
Definition at line 148 of file JackEngine.cpp.
References ALL_CLIENTS, fChannel, fGraphManager, fLastSwitchUsecs, fSignal, and Jack::kGraphOrderCallback.
Referenced by Process().
PropertyChangeNotify()
int Jack::JackEngine::PropertyChangeNotify (jack_uuid_t subject, const char * key, jack_property_change_t change)
Definition at line 266 of file JackEngine.cpp.
References client(), CLIENT_NUM, fClientTable, i, jack_log(), JACK_UUID_STRING_SIZE, jack_uuid_unparse(), and Jack::kPropertyChangeCallback.
Referenced by ClientCloseAux(), and PortUnRegister().
ReleaseRefnum()
void Jack::JackEngine::ReleaseRefnum (int refnum) private
Definition at line 124 of file JackEngine.cpp.
References CLIENT_NUM, fClientTable, fEngineControl, i, and jack_log().
Referenced by ClientCloseAux().
ReserveClientName()
int Jack::JackEngine::ReserveClientName (const char * name, const char * uuid)
Definition at line 1236 of file JackEngine.cpp.
References ClientCheckName(), EnsureUUID(), fReservationMap, jack_error, jack_log(), and jack_uuid_parse().
SessionNotify()
void Jack::JackEngine::SessionNotify (int refnum, const char * target, jack_session_event_type_t type, const char * path, detail::JackChannelTransactionInterface * socket, JackSessionNotifyResult ** result)
Definition at line 1112 of file JackEngine.cpp.
References client(), CLIENT_NUM, DIR_SEPARATOR, fClientTable, fSessionPendingReplies, fSessionResult, fSessionTransaction, i, jack_client_uuid_generate(), jack_error, jack_log(), JACK_PORT_NAME_SIZE, jack_uuid_empty(), JACK_UUID_STRING_SIZE, jack_uuid_unparse(), Jack::kImmediateSessionReply, Jack::kPendingSessionReply, Jack::kSessionCallback, Jack::JackTools::MkDir(), and Jack::JackSessionNotifyResult::Write().
SessionReply()
int Jack::JackEngine::SessionReply (int refnum)
Definition at line 1177 of file JackEngine.cpp.
References client(), fClientTable, fSessionPendingReplies, fSessionResult, fSessionTransaction, JACK_UUID_STRING_SIZE, and jack_uuid_unparse().
Friends And Related Symbol Documentation
JackLockedEngine
friend class JackLockedEngine friend
Definition at line 46 of file JackEngine.h.
References JackLockedEngine.
Referenced by JackLockedEngine.
Member Data Documentation
fChannel
JackServerNotifyChannel Jack::JackEngine::fChannel private
Definition at line 55 of file JackEngine.h.
Referenced by CheckXRun(), Close(), NotifyDriverXRun(), NotifyQuit(), Open(), and ProcessNext().
fClientTable
JackClientInterface* Jack::JackEngine::fClientTable[CLIENT_NUM] private
Definition at line 53 of file JackEngine.h.
Referenced by JackEngine(), AllocateRefnum(), CheckClient(), CheckXRun(), ClientActivate(), ClientCheckName(), ClientCloseAux(), ClientDeactivate(), ClientExternalClose(), ClientExternalOpen(), ClientHasSessionCallback(), ClientInternalOpen(), Close(), EnsureUUID(), GetClientNameForUUID(), GetClientPID(), GetClientRefNum(), GetInternalClientName(), GetUUIDForClientName(), InternalClientHandle(), InternalClientUnload(), NotifyAddClient(), NotifyClient(), NotifyRemoveClient(), PortConnect(), PortRegister(), PortUnRegister(), Process(), PropertyChangeNotify(), ReleaseRefnum(), SessionNotify(), and SessionReply().
fEngineControl
JackEngineControl* Jack::JackEngine::fEngineControl private
Definition at line 51 of file JackEngine.h.
Referenced by JackEngine(), CheckXRun(), ClientActivate(), ClientCloseAux(), ClientDeactivate(), ClientExternalOpen(), ClientInternalOpen(), Close(), NotifyFreewheel(), Open(), PortRegister(), Process(), and ReleaseRefnum().
fGraphManager
JackGraphManager* Jack::JackEngine::fGraphManager private
Definition at line 50 of file JackEngine.h.
Referenced by JackEngine(), CheckPortsConnect(), CheckXRun(), ClientActivate(), ClientCloseAux(), ClientDeactivate(), ClientExternalOpen(), ClientInternalOpen(), ComputeTotalLatencies(), PortConnect(), PortConnect(), PortDisconnect(), PortDisconnect(), PortRegister(), PortRename(), PortUnRegister(), Process(), ProcessCurrent(), and ProcessNext().
fLastSwitchUsecs
jack_time_t Jack::JackEngine::fLastSwitchUsecs private
Definition at line 57 of file JackEngine.h.
Referenced by JackEngine(), ClientDeactivate(), Process(), and ProcessNext().
fMetadata
JackMetadata Jack::JackEngine::fMetadata private
Definition at line 58 of file JackEngine.h.
Referenced by JackEngine(), ClientCloseAux(), PortSetDefaultMetadata(), and PortUnRegister().
fReservationMap
std::map<int,std::string> Jack::JackEngine::fReservationMap private
Definition at line 63 of file JackEngine.h.
Referenced by ClientCheck(), ClientCheckName(), ClientExternalOpen(), and ReserveClientName().
fSelfConnectMode
char Jack::JackEngine::fSelfConnectMode private
Definition at line 52 of file JackEngine.h.
Referenced by JackEngine(), and CheckPortsConnect().
fSessionPendingReplies
int Jack::JackEngine::fSessionPendingReplies private
Definition at line 60 of file JackEngine.h.
Referenced by JackEngine(), SessionNotify(), and SessionReply().
fSessionResult
JackSessionNotifyResult* Jack::JackEngine::fSessionResult private
Definition at line 62 of file JackEngine.h.
Referenced by JackEngine(), SessionNotify(), and SessionReply().
fSessionTransaction
detail::JackChannelTransactionInterface* Jack::JackEngine::fSessionTransaction private
Definition at line 61 of file JackEngine.h.
Referenced by JackEngine(), SessionNotify(), and SessionReply().
fSignal
JackProcessSync Jack::JackEngine::fSignal private
To communicate between the RT thread and server.
Definition at line 56 of file JackEngine.h.
Referenced by JackEngine(), ClientActivate(), ClientCloseAux(), ClientDeactivate(), ClientExternalOpen(), ClientInternalOpen(), and ProcessNext().
fSynchroTable
JackSynchro* Jack::JackEngine::fSynchroTable private
Definition at line 54 of file JackEngine.h.
Referenced by JackEngine(), ClientCloseAux(), ClientExternalOpen(), and ClientInternalOpen().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackEngine.h
src/3rdparty/jack2/common/JackEngine.cpp