LMMS: lmms::SerializingObject Class Reference
lmms::SerializingObject Class Reference abstract
#include <SerializingObject.h>
Public Member Functions
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
virtual void restoreState (const QDomElement &_this)
virtual QDomElement saveState (QDomDocument &_doc, QDomElement &_parent)
void setHook (SerializingObjectHook *_hook)
Protected Member Functions
virtual void loadSettings (const QDomElement &element)=0
virtual void saveSettings (QDomDocument &doc, QDomElement &element)=0
Private Attributes
SerializingObjectHook * m_hook
Detailed Description
Definition at line 42 of file SerializingObject.h.
Constructor & Destructor Documentation
SerializingObject()
lmms::SerializingObject::SerializingObject ()
Definition at line 32 of file SerializingObject.cpp.
References m_hook.
Referenced by lmms::EffectChain::EffectChain(), lmms::JournallingObject::JournallingObject(), and lmms::Note::Note().
~SerializingObject()
lmms::SerializingObject::~SerializingObject () virtual
Definition at line 40 of file SerializingObject.cpp.
References m_hook.
Member Function Documentation
hook()
SerializingObjectHook * lmms::SerializingObject::hook () inline
Definition at line 58 of file SerializingObject.h.
References m_hook.
Referenced by restoreState(), saveState(), and setHook().
loadSettings()
void lmms::SerializingObject::loadSettings (const QDomElement & element) protected pure virtual
Implemented in lmms::AutomatableModel, lmms::AutomationClip, lmms::Controller, lmms::ControllerConnection, lmms::DummyEffectControls, lmms::DummyInstrument, lmms::DummyPlugin, lmms::Effect, lmms::EffectChain, lmms::EnvelopeAndLfoParameters, lmms::ExportFilter, lmms::gui::AutomationEditor, lmms::gui::ControllerRackView, lmms::gui::MicrotunerConfig, lmms::gui::MidiCCRackView, lmms::gui::PatternEditor, lmms::gui::PianoRollWindow, lmms::gui::ProjectNotes, lmms::gui::SongEditor, lmms::gui::TrackContainerView, lmms::gui::TrackContentWidget, lmms::gui::TrackView, lmms::ImportFilter, lmms::InlineAutomation, lmms::InstrumentFunctionArpeggio, lmms::InstrumentFunctionNoteStacking, lmms::InstrumentSoundShaping, lmms::Interval, lmms::Keymap, lmms::LadspaControl, lmms::LfoController, lmms::Microtuner, lmms::MidiClip, lmms::MidiController, lmms::MidiPort, lmms::Mixer, lmms::Note, lmms::PatternClip, lmms::PeakController, lmms::SampleClip, lmms::Scale, lmms::Timeline, lmms::Track, and lmms::TrackContainer.
Definition at line 109 of file SerializingObject.cpp.
Referenced by restoreState().
nodeName()
virtual QString lmms::SerializingObject::nodeName () const pure virtual
Implemented in lmms::AutomatableModel, lmms::AutomationClip, lmms::AutomationTrack, lmms::Controller, lmms::ControllerConnection, lmms::DetuningHelper, lmms::DummyEffectControls, lmms::DummyInstrument, lmms::DummyPlugin, lmms::Effect, lmms::EffectChain, lmms::EnvelopeAndLfoParameters, lmms::ExportFilter, lmms::gui::AutomationEditor, lmms::gui::ControllerRackView, lmms::gui::MicrotunerConfig, lmms::gui::MidiCCRackView, lmms::gui::PianoRollWindow, lmms::gui::ProjectNotes, lmms::gui::SampleTrackView, lmms::gui::TrackContainerView, lmms::gui::TrackContentWidget, lmms::gui::TrackView, lmms::ImportFilter, lmms::InstrumentFunctionArpeggio, lmms::InstrumentFunctionNoteStacking, lmms::InstrumentSoundShaping, lmms::InstrumentTrack, lmms::Interval, lmms::Keymap, lmms::LadspaControl, lmms::LfoController, lmms::Microtuner, lmms::MidiClip, lmms::MidiController, lmms::MidiPort, lmms::Mixer, lmms::Note, lmms::PatternClip, lmms::PatternStore, lmms::PatternTrack, lmms::PeakController, lmms::PreviewTrackContainer, lmms::SampleClip, lmms::SampleTrack, lmms::Scale, and lmms::Song.
References setHook().
Referenced by lmms::JournallingObject::changeID(), lmms::Clip::copyStateTo(), lmms::Effect::loadSettings(), lmms::Track::loadTrack(), lmms::TrackContainer::saveSettings(), saveState(), and lmms::Track::saveTrack().
restoreState()
void lmms::SerializingObject::restoreState (const QDomElement & _this) virtual
Reimplemented in lmms::gui::PianoRollWindow, and lmms::JournallingObject.
Definition at line 69 of file SerializingObject.cpp.
References hook(), loadSettings(), and lmms::SerializingObjectHook::loadSettings().
Referenced by lmms::gui::PianoRoll::loadGhostNotes(), lmms::Song::loadProject(), lmms::MidiClip::loadSettings(), lmms::Scale::loadSettings(), lmms::gui::PianoRoll::pasteNotes(), and lmms::JournallingObject::restoreState().
saveSettings()
void lmms::SerializingObject::saveSettings (QDomDocument & doc, QDomElement & element) protected pure virtual
Implemented in lmms::AutomatableModel, lmms::AutomationClip, lmms::Controller, lmms::ControllerConnection, lmms::DummyEffectControls, lmms::DummyInstrument, lmms::DummyPlugin, lmms::Effect, lmms::EffectChain, lmms::EnvelopeAndLfoParameters, lmms::ExportFilter, lmms::gui::AutomationEditor, lmms::gui::ControllerRackView, lmms::gui::MicrotunerConfig, lmms::gui::MidiCCRackView, lmms::gui::PatternEditor, lmms::gui::PianoRollWindow, lmms::gui::ProjectNotes, lmms::gui::SongEditor, lmms::gui::TrackContainerView, lmms::gui::TrackContentWidget, lmms::gui::TrackView, lmms::ImportFilter, lmms::InlineAutomation, lmms::InstrumentFunctionArpeggio, lmms::InstrumentFunctionNoteStacking, lmms::InstrumentSoundShaping, lmms::Interval, lmms::Keymap, lmms::LadspaControl, lmms::LfoController, lmms::Microtuner, lmms::MidiClip, lmms::MidiController, lmms::MidiPort, lmms::Mixer, lmms::Note, lmms::PatternClip, lmms::PeakController, lmms::SampleClip, lmms::Scale, lmms::Timeline, lmms::Track, and lmms::TrackContainer.
Definition at line 100 of file SerializingObject.cpp.
Referenced by saveState().
saveState()
QDomElement lmms::SerializingObject::saveState (QDomDocument & _doc, QDomElement & _parent) virtual
Reimplemented in lmms::gui::PianoRollWindow, and lmms::JournallingObject.
Definition at line 51 of file SerializingObject.cpp.
References hook(), nodeName(), saveSettings(), and lmms::SerializingObjectHook::saveSettings().
Referenced by lmms::gui::PianoRoll::copyToClipboard(), lmms::Song::saveProjectFile(), lmms::Mixer::saveSettings(), and lmms::JournallingObject::saveState().
setHook()
void lmms::SerializingObject::setHook (SerializingObjectHook * _hook)
Definition at line 82 of file SerializingObject.cpp.
References hook(), and m_hook.
Referenced by lmms::gui::MixerView::MixerView(), and nodeName().
Member Data Documentation
m_hook
SerializingObjectHook* lmms::SerializingObject::m_hook private
Definition at line 71 of file SerializingObject.h.
Referenced by SerializingObject(), ~SerializingObject(), hook(), and setHook().
The documentation for this class was generated from the following files:
include/SerializingObject.h
src/core/SerializingObject.cpp