LMMS: src/3rdparty/jack2/linux/alsa/JackAlsaDriver.cpp File Reference
JackAlsaDriver.cpp File Reference
#include <iostream>
#include <math.h>
#include <stdio.h>
#include <memory.h>
#include <unistd.h>
#include <stdlib.h>
#include <errno.h>
#include <stdarg.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/time.h>
#include <string.h>
#include "JackAlsaDriver.h"
#include "JackEngineControl.h"
#include "JackClientControl.h"
#include "JackPort.h"
#include "JackGraphManager.h"
#include "JackLockedEngine.h"
#include "JackPosixThread.h"
#include "JackCompilerDeps.h"
#include "JackServerGlobals.h"
Namespaces
namespace Jack
Macros
#define __STDC_FORMAT_MACROS
Functions
static int Jack::card_to_num (const char *device)
void ClearOutput ()
static int dither_opt (char c, DitherAlgorithm *dither)
SERVER_EXPORT const jack_driver_desc_t * driver_get_descriptor ()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine *engine, Jack::JackSynchro *table, const JSList *params)
static jack_driver_param_constraint_desc_t * enum_alsa_devices ()
char * Jack::get_control_device_name (const char *device_name)
void MonitorInput ()
static void * Jack::on_device_reservation_loop (void *)
void ReadInput (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nread)
int Restart ()
void SetTime (jack_time_t time)
void WriteOutput (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nwritten)
Variables
static volatile bool Jack::device_reservation_loop_running = false
static struct jack_constraint_enum_char_descriptor dither_constraint_descr_array []
static Jack::JackAlsaDriver * g_alsa_driver
static struct jack_constraint_enum_str_descriptor midi_constraint_descr_array []
Macro Definition Documentation
__STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
Definition at line 21 of file JackAlsaDriver.cpp.
Function Documentation
ClearOutput()
void ClearOutput ()
Definition at line 939 of file JackAlsaDriver.cpp.
References g_alsa_driver.
dither_opt()
int dither_opt (char c, DitherAlgorithm * dither) static
Definition at line 673 of file JackAlsaDriver.cpp.
References None, Rectangular, Shaped, and Triangular.
Referenced by driver_initialize().
driver_get_descriptor()
SERVER_EXPORT const jack_driver_desc_t * driver_get_descriptor ()
Definition at line 700 of file JackAlsaDriver.cpp.
References jack_driver_param_value_t::c, dither_constraint_descr_array, enum_alsa_devices(), FALSE, jack_driver_param_value_t::i, JACK_CONSTRAINT_FLAG_FAKE_VALUE, JACK_CONSTRAINT_FLAG_STRICT, jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverMaster, JackDriverParamBool, JackDriverParamChar, JackDriverParamString, JackDriverParamUInt, midi_constraint_descr_array, SERVER_EXPORT, jack_driver_param_value_t::str, and jack_driver_param_value_t::ui.
driver_initialize()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine * engine, Jack::JackSynchro * table, const JSList * params)
Definition at line 787 of file JackAlsaDriver.cpp.
References jack_driver_param_value_t::c, jack_driver_param_t::character, _JSList::data, dither_opt(), FALSE, g_alsa_driver, jack_driver_param_value_t::i, jack_log(), jack_slist_next, None, SERVER_EXPORT, jack_driver_param_value_t::str, TRUE, jack_driver_param_value_t::ui, and jack_driver_param_t::value.
enum_alsa_devices()
jack_driver_param_constraint_desc_t * enum_alsa_devices () static
Definition at line 584 of file JackAlsaDriver.cpp.
References jack_constraint_add_enum(), jack_constraint_free(), and jack_driver_param_value_t::str.
Referenced by driver_get_descriptor().
MonitorInput()
void MonitorInput ()
Definition at line 935 of file JackAlsaDriver.cpp.
References g_alsa_driver.
ReadInput()
void ReadInput (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nread)
Definition at line 931 of file JackAlsaDriver.cpp.
References g_alsa_driver.
Restart()
int Restart ()
Definition at line 952 of file JackAlsaDriver.cpp.
References g_alsa_driver.
SetTime()
void SetTime (jack_time_t time)
Definition at line 947 of file JackAlsaDriver.cpp.
References g_alsa_driver.
WriteOutput()
void WriteOutput (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nwritten)
Definition at line 943 of file JackAlsaDriver.cpp.
References g_alsa_driver.
Variable Documentation
dither_constraint_descr_array
struct jack_constraint_enum_char_descriptor dither_constraint_descr_array[] static
Initial value:
=
{
    { 'n', "none" },
    { 'r', "rectangular" },
    { 's', "shaped" },
    { 't', "triangular" },
    { 0 }
}
Definition at line 58 of file JackAlsaDriver.cpp.
Referenced by driver_get_descriptor().
g_alsa_driver
Jack::JackAlsaDriver* g_alsa_driver static
Definition at line 785 of file JackAlsaDriver.cpp.
Referenced by ClearOutput(), driver_initialize(), MonitorInput(), ReadInput(), Restart(), SetTime(), and WriteOutput().
midi_constraint_descr_array
struct jack_constraint_enum_str_descriptor midi_constraint_descr_array[] static
Initial value:
=
{
    { "none", "no MIDI driver" },
    { "seq", "ALSA Sequencer driver" },
    { "raw", "ALSA RawMIDI driver" },
    { 0 }
}
Definition at line 50 of file JackAlsaDriver.cpp.
Referenced by driver_get_descriptor().