LMMS: hiir::PhaseHalfPi3dnow< NC > Class Template Reference
hiir::PhaseHalfPi3dnow< NC > Class Template Reference
#include <PhaseHalfPi3dnow.h>
Public Types
typedef float DataType
Public Member Functions
PhaseHalfPi3dnow () noexcept
PhaseHalfPi3dnow (const PhaseHalfPi3dnow< NC > &other)=default
PhaseHalfPi3dnow (PhaseHalfPi3dnow< NC > &&other)=default
~PhaseHalfPi3dnow ()=default
void clear_buffers () noexcept
PhaseHalfPi3dnow< NC > & operator= (const PhaseHalfPi3dnow< NC > &other)=default
PhaseHalfPi3dnow< NC > & operator= (PhaseHalfPi3dnow< NC > &&other)=default
void process_block (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (float &out_0, float &out_1, float input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageData3dnow, _nbr_stages+1 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const PhaseHalfPi3dnow< NC > &other)=delete
bool operator== (const PhaseHalfPi3dnow< NC > &other)=delete
Private Attributes
FilterBiPhase _filter
int _phase
float _prev
Static Private Attributes
static constexpr int _nbr_phases = 2
static constexpr int _nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::PhaseHalfPi3dnow< NC >
Definition at line 49 of file PhaseHalfPi3dnow.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::PhaseHalfPi3dnow< NC >::DataType
Definition at line 58 of file PhaseHalfPi3dnow.h.
Filter
template<int NC> typedef std::array<StageData3dnow, _nbr_stages + 1> hiir::PhaseHalfPi3dnow< NC >::Filter private
Definition at line 97 of file PhaseHalfPi3dnow.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::PhaseHalfPi3dnow< NC >::FilterBiPhase private
Definition at line 98 of file PhaseHalfPi3dnow.h.
Constructor & Destructor Documentation
PhaseHalfPi3dnow() [1/3]
template<int NC> hiir::PhaseHalfPi3dnow< NC >::PhaseHalfPi3dnow () noexcept
Definition at line 71 of file PhaseHalfPi3dnow.hpp.
References _filter, _nbr_phases, _nbr_stages, _phase, _prev, clear_buffers(), i, and NBR_COEFS.
Referenced by PhaseHalfPi3dnow(), PhaseHalfPi3dnow(), ~PhaseHalfPi3dnow(), operator!=(), operator=(), operator=(), and operator==().
PhaseHalfPi3dnow() [2/3]
template<int NC> hiir::PhaseHalfPi3dnow< NC >::PhaseHalfPi3dnow (const PhaseHalfPi3dnow< NC > & other) default
References PhaseHalfPi3dnow().
PhaseHalfPi3dnow() [3/3]
template<int NC> hiir::PhaseHalfPi3dnow< NC >::PhaseHalfPi3dnow (PhaseHalfPi3dnow< NC > && other) default
References PhaseHalfPi3dnow().
~PhaseHalfPi3dnow()
template<int NC> hiir::PhaseHalfPi3dnow< NC >::~PhaseHalfPi3dnow () default
References PhaseHalfPi3dnow().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::PhaseHalfPi3dnow< NC >::clear_buffers () noexcept
Definition at line 294 of file PhaseHalfPi3dnow.hpp.
References _filter, _nbr_phases, _nbr_stages, and i.
Referenced by PhaseHalfPi3dnow(), and operator=().
operator!=()
template<int NC> bool hiir::PhaseHalfPi3dnow< NC >::operator!= (const PhaseHalfPi3dnow< NC > & other) private delete
References PhaseHalfPi3dnow().
operator=() [1/2]
template<int NC> PhaseHalfPi3dnow< NC > & hiir::PhaseHalfPi3dnow< NC >::operator= (const PhaseHalfPi3dnow< NC > & other) default
References PhaseHalfPi3dnow().
operator=() [2/2]
template<int NC> PhaseHalfPi3dnow< NC > & hiir::PhaseHalfPi3dnow< NC >::operator= (PhaseHalfPi3dnow< NC > && other) default
References PhaseHalfPi3dnow(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::PhaseHalfPi3dnow< NC >::operator== (const PhaseHalfPi3dnow< NC > & other) private delete
References PhaseHalfPi3dnow().
process_block()
template<int NC> void hiir::PhaseHalfPi3dnow< NC >::process_block (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 196 of file PhaseHalfPi3dnow.hpp.
References _filter, _nbr_stages, _phase, _prev, pos, process_sample(), and hiir::StageProc3dnow< CUR >::process_sample_neg().
Referenced by operator=().
process_sample()
template<int NC> void hiir::PhaseHalfPi3dnow< NC >::process_sample (float & out_0, float & out_1, float input) noexcept
Definition at line 141 of file PhaseHalfPi3dnow.hpp.
References _filter, hiir::StageData3dnow::_mem, _nbr_stages, _phase, _prev, and hiir::StageProc3dnow< CUR >::process_sample_neg().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::PhaseHalfPi3dnow< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 109 of file PhaseHalfPi3dnow.hpp.
References _filter, _nbr_phases, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::PhaseHalfPi3dnow< NC >::_delay = 0 static constexpr
Definition at line 61 of file PhaseHalfPi3dnow.h.
_filter
template<int NC> FilterBiPhase hiir::PhaseHalfPi3dnow< NC >::_filter private
Definition at line 100 of file PhaseHalfPi3dnow.h.
Referenced by PhaseHalfPi3dnow(), clear_buffers(), process_block(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_nbr_chn = 1 static constexpr
Definition at line 59 of file PhaseHalfPi3dnow.h.
_nbr_phases
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_nbr_phases = 2 static constexpr private
Definition at line 95 of file PhaseHalfPi3dnow.h.
Referenced by PhaseHalfPi3dnow(), clear_buffers(), and set_coefs().
_nbr_stages
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width static constexpr private
Definition at line 94 of file PhaseHalfPi3dnow.h.
Referenced by PhaseHalfPi3dnow(), clear_buffers(), process_block(), and process_sample().
_phase
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_phase private
Definition at line 102 of file PhaseHalfPi3dnow.h.
Referenced by PhaseHalfPi3dnow(), process_block(), and process_sample().
_prev
template<int NC> float hiir::PhaseHalfPi3dnow< NC >::_prev private
Definition at line 101 of file PhaseHalfPi3dnow.h.
Referenced by PhaseHalfPi3dnow(), process_block(), and process_sample().
_stage_width
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_stage_width = 2 static constexpr private
Definition at line 93 of file PhaseHalfPi3dnow.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::NBR_COEFS = NC static constexpr
Definition at line 60 of file PhaseHalfPi3dnow.h.
Referenced by PhaseHalfPi3dnow(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/PhaseHalfPi3dnow.h
src/3rdparty/hiir/hiir/PhaseHalfPi3dnow.hpp