LMMS: hiir::Upsampler2x2F64Sse2< NC > Class Template Reference
hiir::Upsampler2x2F64Sse2< NC > Class Template Reference
#include <Upsampler2x2F64Sse2.h>
Public Types
typedef double DataType
Public Member Functions
Upsampler2x2F64Sse2 () noexcept
Upsampler2x2F64Sse2 (const Upsampler2x2F64Sse2< NC > &other)=default
Upsampler2x2F64Sse2 (Upsampler2x2F64Sse2< NC > &&other)=default
~Upsampler2x2F64Sse2 ()=default
void clear_buffers () noexcept
Upsampler2x2F64Sse2< NC > & operator= (const Upsampler2x2F64Sse2< NC > &other)=default
Upsampler2x2F64Sse2< NC > & operator= (Upsampler2x2F64Sse2< NC > &&other)=default
void process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (__m128d &out_0, __m128d &out_1, __m128d input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 2
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Sse2, NBR_COEFS+2 > Filter
Private Member Functions
bool operator!= (const Upsampler2x2F64Sse2< NC > &other) const =delete
bool operator== (const Upsampler2x2F64Sse2< NC > &other) const =delete
Private Attributes
Filter _filter
Detailed Description
template<int NC>
class hiir::Upsampler2x2F64Sse2< NC >
Definition at line 54 of file Upsampler2x2F64Sse2.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::Upsampler2x2F64Sse2< NC >::DataType
Definition at line 63 of file Upsampler2x2F64Sse2.h.
Filter
template<int NC> typedef std::array<StageDataF64Sse2, NBR_COEFS + 2> hiir::Upsampler2x2F64Sse2< NC >::Filter private
Definition at line 97 of file Upsampler2x2F64Sse2.h.
Constructor & Destructor Documentation
Upsampler2x2F64Sse2() [1/3]
template<int NC> hiir::Upsampler2x2F64Sse2< NC >::Upsampler2x2F64Sse2 () noexcept
Definition at line 56 of file Upsampler2x2F64Sse2.hpp.
References _filter, clear_buffers(), i, and NBR_COEFS.
Referenced by Upsampler2x2F64Sse2(), Upsampler2x2F64Sse2(), ~Upsampler2x2F64Sse2(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2x2F64Sse2() [2/3]
template<int NC> hiir::Upsampler2x2F64Sse2< NC >::Upsampler2x2F64Sse2 (const Upsampler2x2F64Sse2< NC > & other) default
References Upsampler2x2F64Sse2().
Upsampler2x2F64Sse2() [3/3]
template<int NC> hiir::Upsampler2x2F64Sse2< NC >::Upsampler2x2F64Sse2 (Upsampler2x2F64Sse2< NC > && other) default
References Upsampler2x2F64Sse2().
~Upsampler2x2F64Sse2()
template<int NC> hiir::Upsampler2x2F64Sse2< NC >::~Upsampler2x2F64Sse2 () default
References Upsampler2x2F64Sse2().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2x2F64Sse2< NC >::clear_buffers () noexcept
Definition at line 182 of file Upsampler2x2F64Sse2.hpp.
References _filter, i, and NBR_COEFS.
Referenced by Upsampler2x2F64Sse2(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2x2F64Sse2< NC >::operator!= (const Upsampler2x2F64Sse2< NC > & other) const private delete
References Upsampler2x2F64Sse2().
operator=() [1/2]
template<int NC> Upsampler2x2F64Sse2< NC > & hiir::Upsampler2x2F64Sse2< NC >::operator= (const Upsampler2x2F64Sse2< NC > & other) default
References Upsampler2x2F64Sse2().
operator=() [2/2]
template<int NC> Upsampler2x2F64Sse2< NC > & hiir::Upsampler2x2F64Sse2< NC >::operator= (Upsampler2x2F64Sse2< NC > && other) default
References Upsampler2x2F64Sse2(), clear_buffers(), hiir_FORCEINLINE, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2x2F64Sse2< NC >::operator== (const Upsampler2x2F64Sse2< NC > & other) const private delete
References Upsampler2x2F64Sse2().
process_block()
template<int NC> void hiir::Upsampler2x2F64Sse2< NC >::process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 147 of file Upsampler2x2F64Sse2.hpp.
References _nbr_chn, pos, and process_sample().
Referenced by operator=().
process_sample()
template<int NC> void hiir::Upsampler2x2F64Sse2< NC >::process_sample (__m128d & out_0, __m128d & out_1, __m128d input) noexcept
Definition at line 113 of file Upsampler2x2F64Sse2.hpp.
References _filter, NBR_COEFS, and hiir::StageProc2F64Sse2< REMAINING >::process_sample_pos().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::Upsampler2x2F64Sse2< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 84 of file Upsampler2x2F64Sse2.hpp.
References _filter, i, and NBR_COEFS.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Upsampler2x2F64Sse2< NC >::_delay = 0 static constexpr
Definition at line 66 of file Upsampler2x2F64Sse2.h.
_filter
template<int NC> Filter hiir::Upsampler2x2F64Sse2< NC >::_filter private
Definition at line 99 of file Upsampler2x2F64Sse2.h.
Referenced by Upsampler2x2F64Sse2(), clear_buffers(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Upsampler2x2F64Sse2< NC >::_nbr_chn = 2 static constexpr
Definition at line 64 of file Upsampler2x2F64Sse2.h.
Referenced by process_block().
NBR_COEFS
template<int NC> int hiir::Upsampler2x2F64Sse2< NC >::NBR_COEFS = NC static constexpr
Definition at line 65 of file Upsampler2x2F64Sse2.h.
Referenced by Upsampler2x2F64Sse2(), clear_buffers(), operator=(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2x2F64Sse2.h
src/3rdparty/hiir/hiir/Upsampler2x2F64Sse2.hpp