LMMS: lmms::gui::AutomationTrackView Class Reference
lmms::gui::AutomationTrackView Class Reference
#include <AutomationTrackView.h>
Public Member Functions
AutomationTrackView (AutomationTrack *at, TrackContainerView *tcv)
~AutomationTrackView () override=default
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
Public Member Functions inherited from lmms::gui::TrackView
TrackView (Track *_track, TrackContainerView *tcv)
Create a new track View.
~TrackView () override=default
virtual QMenu * createMixerMenu (QString title, QString newMixerLabel)
Create a menu for assigning/creating channels for this track.
Track * getTrack ()
const Track * getTrack () const
TrackContentWidget * getTrackContentWidget ()
TrackOperationsWidget * getTrackOperationsWidget ()
QWidget * getTrackSettingsWidget ()
bool isMovingTrack () const
TrackContainerView * trackContainerView ()
virtual void update ()
Update this track View and all its content objects.
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Additional Inherited Members
Public Slots inherited from lmms::gui::TrackView
virtual bool close ()
Close this track View.
Protected Member Functions inherited from lmms::gui::TrackView
void dragEnterEvent (QDragEnterEvent *dee) override
Start a drag event on this track View.
void dropEvent (QDropEvent *de) override
Accept a drop event on this track View.
void loadSettings (const QDomElement &element) override
void modelChanged () override
Register that the model of this track View has changed.
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse move event on this track View.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press event on this track View.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release event on this track View.
QString nodeName () const override
void paintEvent (QPaintEvent *pe) override
Repaint this track View.
void resizeEvent (QResizeEvent *re) override
Resize this track View.
void saveSettings (QDomDocument &doc, QDomElement &element) override
void wheelEvent (QWheelEvent *we) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 40 of file AutomationTrackView.h.
Constructor & Destructor Documentation
AutomationTrackView()
lmms::gui::AutomationTrackView::AutomationTrackView (AutomationTrack * at, TrackContainerView * tcv)
Definition at line 39 of file AutomationTrackView.cpp.
References lmms::gui::TrackView::TrackView(), lmms::embed::getIconPixmap(), lmms::gui::TrackView::getTrackSettingsWidget(), lmms::gui::ModelView::setModel(), and lmms::gui::TrackView::TrackLabelButton.
~AutomationTrackView()
lmms::gui::AutomationTrackView::~AutomationTrackView () override default
Member Function Documentation
dragEnterEvent()
void lmms::gui::AutomationTrackView::dragEnterEvent (QDragEnterEvent * _dee) override
Definition at line 50 of file AutomationTrackView.cpp.
References lmms::gui::StringPairDrag::processDragEnterEvent().
dropEvent()
void lmms::gui::AutomationTrackView::dropEvent (QDropEvent * _de) override
Definition at line 58 of file AutomationTrackView.cpp.
References lmms::AutomationClip::addObject(), lmms::Track::createClip(), lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::gui::TrackView::getTrack(), lmms::gui::TrackView::getTrackContentWidget(), lmms::ProjectJournal::journallingObject(), pos, lmms::Engine::projectJournal(), lmms::TimePos::ticksPerBar(), lmms::TimePos::toAbsoluteBar(), lmms::gui::TrackView::trackContainerView(), and lmms::gui::TrackView::update().
The documentation for this class was generated from the following files:
include/AutomationTrackView.h
src/gui/tracks/AutomationTrackView.cpp