LMMS: lmms::gui::DropToolBar Class Reference
lmms::gui::DropToolBar Class Reference
Small helper class: A QToolBar that accepts and exposes drop events as signals.
#include <Editor.h>
Signals
void dragEntered (QDragEnterEvent *event)
void dropped (QDropEvent *event)
Public Member Functions
DropToolBar (QWidget *parent=0)
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *event) override
void dropEvent (QDropEvent *event) override
Detailed Description
Small helper class: A QToolBar that accepts and exposes drop events as signals.
Definition at line 102 of file Editor.h.
Constructor & Destructor Documentation
DropToolBar()
lmms::gui::DropToolBar::DropToolBar (QWidget * parent = 0)
Definition at line 175 of file Editor.cpp.
Member Function Documentation
dragEntered
void lmms::gui::DropToolBar::dragEntered (QDragEnterEvent * event) signal
Referenced by dragEnterEvent().
dragEnterEvent()
void lmms::gui::DropToolBar::dragEnterEvent (QDragEnterEvent * event) override protected
Definition at line 180 of file Editor.cpp.
References dragEntered().
dropEvent()
void lmms::gui::DropToolBar::dropEvent (QDropEvent * event) override protected
Definition at line 185 of file Editor.cpp.
References dropped().
dropped
void lmms::gui::DropToolBar::dropped (QDropEvent * event) signal
Referenced by dropEvent().
The documentation for this class was generated from the following files:
include/Editor.h
src/gui/editors/Editor.cpp