LMMS: lmms::gui::CustomTextKnob Class Reference
lmms::gui::CustomTextKnob Class Reference
#include <CustomTextKnob.h>
Public Member Functions
CustomTextKnob (const Knob &other)=delete
CustomTextKnob (KnobType _knob_num, const QString &label, QWidget *_parent=nullptr, const QString &_name=QString(), const QString &_value_text=QString())
void setValueText (const QString &_value_text)
Public Member Functions inherited from lmms::gui::Knob
Knob (const Knob &other)=delete
Knob (KnobType _knob_num, QWidget *_parent=nullptr, const QString &_name=QString())
Construct a Knob with the given style and no label.
Knob (KnobType knobNum, const QString &labelText, int labelPixelSize, QWidget *parent, const QString &name=QString())
Constructs a knob with a label font in the pixel size.
Knob (KnobType knobNum, const QString &labelText, QWidget *parent=nullptr, LabelRendering labelRendering=LabelRendering::WidgetFont, const QString &name=QString())
Construct a Knob with the given style and label text.
Knob (QWidget *_parent=nullptr, const QString &_name=QString())
default ctor
QPointF centerPoint () const
float centerPointX () const
float centerPointY () const
const QString & getLabel () const
float innerRadius () const
KnobType knobNum () const
float lineWidth () const
QColor outerColor () const
float outerRadius () const
void setCenterPointX (float c)
void setCenterPointY (float c)
void setInnerRadius (float r)
void setknobNum (KnobType k)
void setLabel (const QString &txt)
void setLineWidth (float w)
void setOuterColor (const QColor &c)
void setOuterRadius (float r)
void setTextColor (const QColor &c)
void setTotalAngle (float angle)
QColor textColor () const
Public Member Functions inherited from lmms::gui::FloatModelEditorBase
FloatModelEditorBase (const FloatModelEditorBase &other)=delete
FloatModelEditorBase (DirectionOfManipulation directionOfManipulation=DirectionOfManipulation::Vertical, QWidget *_parent=nullptr, const QString &_name=QString())
default ctor
void setHintText (const QString &txt_before, const QString &txt_after)
Public Member Functions inherited from lmms::gui::TypedModelView< FloatModel >
TypedModelView (Model *model, QWidget *_this)
FloatModel * model ()
const FloatModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void setHintText (const QString &_txt_before, const QString &_txt_after)
Protected Member Functions inherited from lmms::gui::Knob
void changeEvent (QEvent *ev) override
bool fixedFontSizeLabelRendering () const
Affects how the label of the knob is rendered.
void paintEvent (QPaintEvent *) override
void setFixedFontSizeLabelRendering ()
Set the button to legacy rendering mode which uses a fixed font size and that does not take the size of the widget's font into account.
Protected Member Functions inherited from lmms::gui::FloatModelEditorBase
void contextMenuEvent (QContextMenuEvent *me) override
void doConnections () override
void dragEnterEvent (QDragEnterEvent *dee) override
void dropEvent (QDropEvent *de) override
void enterEvent (QEvent *event) override
void focusOutEvent (QFocusEvent *fe) override
virtual float getValue (const QPoint &p)
void leaveEvent (QEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
float pageSize () const
void paintEvent (QPaintEvent *me) override
void setPosition (const QPoint &p)
void showTextFloat (int msecBeforeDisplay, int msecDisplayTime)
void wheelEvent (QWheelEvent *me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void modelChanged ()
QWidget * widget ()
Protected Attributes
QString m_value_text
Protected Attributes inherited from lmms::gui::FloatModelEditorBase
bool m_buttonPressed
DirectionOfManipulation m_directionOfManipulation
QPoint m_lastMousePos
mouse position in last mouseMoveEvent
float m_leftOver
BoolModel m_volumeKnob
FloatModel m_volumeRatio
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Private Member Functions
QString displayValue () const override
Additional Inherited Members
Public Types inherited from lmms::gui::Knob
enum class LabelRendering {
WidgetFont ,
LegacyFixedFontSize
}
Determines how the label of the knob is rendered.
Public Types inherited from lmms::gui::FloatModelEditorBase
enum class DirectionOfManipulation {
Vertical ,
Horizontal
}
Signals inherited from lmms::gui::FloatModelEditorBase
void sliderMoved (float value)
void sliderPressed ()
void sliderReleased ()
Static Protected Attributes inherited from lmms::gui::FloatModelEditorBase
static SimpleTextFloat * s_textFloat = nullptr
Properties inherited from lmms::gui::Knob
QColor arcActiveColor
QColor arcInactiveColor
float centerPointX
float centerPointY
float innerRadius
KnobType knobNum
QColor lineActiveColor
QColor lineInactiveColor
float lineWidth
QColor outerColor
float outerRadius
QColor textColor
Detailed Description
Definition at line 34 of file CustomTextKnob.h.
Constructor & Destructor Documentation
CustomTextKnob() [1/2]
lmms::gui::CustomTextKnob::CustomTextKnob (KnobType _knob_num, const QString & label, QWidget * _parent = nullptr, const QString & _name = QString(), const QString & _value_text = QString())
Definition at line 32 of file CustomTextKnob.cpp.
References lmms::gui::Knob::Knob(), lmms::gui::adjustedToPixelSize(), m_value_text, lmms::gui::Knob::setLabel(), and SMALL_FONT_SIZE.
CustomTextKnob() [2/2]
lmms::gui::CustomTextKnob::CustomTextKnob (const Knob & other) delete
References lmms::gui::Knob::Knob().
Member Function Documentation
displayValue()
QString lmms::gui::CustomTextKnob::displayValue () const override private virtual
Reimplemented from lmms::gui::FloatModelEditorBase.
Definition at line 40 of file CustomTextKnob.cpp.
References lmms::gui::AutomatableModelView::m_description, and m_value_text.
setHintText()
void lmms::gui::CustomTextKnob::setHintText (const QString & _txt_before, const QString & _txt_after) inline protected
Definition at line 37 of file CustomTextKnob.h.
setValueText()
void lmms::gui::CustomTextKnob::setValueText (const QString & _value_text) inline
Definition at line 43 of file CustomTextKnob.h.
References m_value_text.
Member Data Documentation
m_value_text
QString lmms::gui::CustomTextKnob::m_value_text protected
Definition at line 52 of file CustomTextKnob.h.
Referenced by CustomTextKnob(), displayValue(), and setValueText().
The documentation for this class was generated from the following files:
include/CustomTextKnob.h
src/gui/widgets/CustomTextKnob.cpp