LMMS: lmms::ValueBuffer Class Reference
lmms::ValueBuffer Class Reference
#include <ValueBuffer.h>
Public Member Functions
ValueBuffer ()=default
ValueBuffer (int length)
void fill (float value)
void interpolate (float start, float end)
int length () const
float value (int offset) const
float * values ()
const float * values () const
Detailed Description
Definition at line 37 of file ValueBuffer.h.
Constructor & Destructor Documentation
ValueBuffer() [1/2]
lmms::ValueBuffer::ValueBuffer () default
References ValueBuffer(), fill(), interpolate(), length(), value(), and values().
Referenced by ValueBuffer().
ValueBuffer() [2/2]
lmms::ValueBuffer::ValueBuffer (int length)
Definition at line 10 of file ValueBuffer.cpp.
References length().
Member Function Documentation
fill()
void lmms::ValueBuffer::fill (float value)
Definition at line 14 of file ValueBuffer.cpp.
References value().
Referenced by ValueBuffer().
interpolate()
void lmms::ValueBuffer::interpolate (float start, float end)
Definition at line 39 of file ValueBuffer.cpp.
References i, and length().
Referenced by ValueBuffer().
length()
int lmms::ValueBuffer::length () const
Definition at line 34 of file ValueBuffer.cpp.
Referenced by ValueBuffer(), ValueBuffer(), interpolate(), lmms::AutomatableModel::linkModels(), and value().
value()
float lmms::ValueBuffer::value (int offset) const
Definition at line 19 of file ValueBuffer.cpp.
References length().
Referenced by ValueBuffer(), and fill().
values() [1/2]
float * lmms::ValueBuffer::values ()
Definition at line 29 of file ValueBuffer.cpp.
values() [2/2]
const float * lmms::ValueBuffer::values () const
Definition at line 24 of file ValueBuffer.cpp.
Referenced by ValueBuffer(), lmms::MixHelpers::addMultipliedByBuffer(), lmms::MixHelpers::addMultipliedByBuffers(), lmms::MixHelpers::addSanitizedMultipliedByBuffer(), lmms::MixHelpers::addSanitizedMultipliedByBuffers(), lmms::AudioBusHandle::doProcessing(), lmms::Mixer::masterMix(), lmms::LfoController::updateValueBuffer(), and lmms::AutomatableModel::valueBuffer().
The documentation for this class was generated from the following files:
include/ValueBuffer.h
src/core/ValueBuffer.cpp