LMMS: lmms::gui::SideBarButton Class Reference
lmms::gui::SideBarButton Class Reference
Public Member Functions
SideBarButton (Qt::Orientation _orientation, QWidget *_parent)
~SideBarButton () override=default
Qt::Orientation orientation () const
QSize sizeHint () const override
Protected Member Functions
void paintEvent (QPaintEvent *) override
Private Attributes
Qt::Orientation m_orientation
Detailed Description
Definition at line 38 of file SideBar.cpp.
Constructor & Destructor Documentation
SideBarButton()
lmms::gui::SideBarButton::SideBarButton (Qt::Orientation _orientation, QWidget * _parent) inline
Definition at line 41 of file SideBar.cpp.
References m_orientation.
~SideBarButton()
lmms::gui::SideBarButton::~SideBarButton () override default
Member Function Documentation
orientation()
Qt::Orientation lmms::gui::SideBarButton::orientation () const inline
Definition at line 49 of file SideBar.cpp.
References m_orientation.
Referenced by paintEvent(), and sizeHint().
paintEvent()
void lmms::gui::SideBarButton::paintEvent (QPaintEvent *) inline override protected
Definition at line 67 of file SideBar.cpp.
References orientation(), and sizeHint().
sizeHint()
QSize lmms::gui::SideBarButton::sizeHint () const inline override
Definition at line 54 of file SideBar.cpp.
References orientation().
Referenced by paintEvent().
Member Data Documentation
m_orientation
Qt::Orientation lmms::gui::SideBarButton::m_orientation private
Definition at line 84 of file SideBar.cpp.
Referenced by SideBarButton(), and orientation().
The documentation for this class was generated from the following file:
src/gui/SideBar.cpp