LMMS: lmms::PlanarBufferView< T, channelCount > Class Template Reference
lmms::PlanarBufferView< T, channelCount > Class Template Reference
Non-owning view for multi-channel non-interleaved audio data.
#include <AudioBufferView.h>
Public Member Functions
template<typename U = T>
requires (std::is_const_v<U> && channelCount == DynamicChannelCount)
constexpr PlanarBufferView (PlanarBufferView< std::remove_const_t< U >, channelCount > other) noexcept
Construct const from mutable (dynamic channel count).
template<typename U = T>
requires (std::is_const_v<U> && channelCount != DynamicChannelCount)
constexpr PlanarBufferView (PlanarBufferView< std::remove_const_t< U >, channelCount > other) noexcept
Construct const from mutable (static channel count).
template<proc_ch_t otherChannels>
requires (channelCount == DynamicChannelCount && otherChannels != DynamicChannelCount)
constexpr PlanarBufferView (PlanarBufferView< T, otherChannels > other) noexcept
Construct dynamic channel count from static.
template<proc_ch_t channel>
requires (channelCount != DynamicChannelCount)
constexpr auto buffer () const noexcept -> std::span< T >
constexpr auto buffer (proc_ch_t channel) const noexcept -> std::span< T >
template<proc_ch_t channel>
requires (channelCount != DynamicChannelCount)
constexpr auto bufferPtr () const noexcept -> T *
constexpr auto bufferPtr (proc_ch_t channel) const noexcept -> T *
constexpr auto empty () const noexcept -> bool
constexpr auto operator[] (proc_ch_t channel) const noexcept -> T *
Public Member Functions inherited from lmms::detail::BufferViewData< T *const, DynamicChannelCount >
constexpr BufferViewData ()=default
constexpr auto data () const noexcept -> T *
constexpr auto frames () const noexcept -> f_cnt_t
Static Public Attributes
static constexpr bool Interleaved = false
Use to distinguish between InterleavedBufferView and PlanarBufferView when using AudioBufferView.
Private Types
using Base = detail::BufferViewData<T* const, channelCount>
Additional Inherited Members
Static Public Member Functions inherited from lmms::detail::BufferViewData< T *const, DynamicChannelCount >
static constexpr auto channels () noexcept -> proc_ch_t
Protected Attributes inherited from lmms::detail::BufferViewData< T *const, DynamicChannelCount >
T * m_data
f_cnt_t m_frames
Detailed Description
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount>
class lmms::PlanarBufferView< T, channelCount >
Non-owning view for multi-channel non-interleaved audio data.
The data type is T* const* which is a 2D array accessed as data[channel][frame index] where each channel's buffer contains frames() frames.
TODO C++23: Use std::mdspan?
Definition at line 470 of file AudioBufferView.h.
Member Typedef Documentation
Base
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> using lmms::PlanarBufferView< T, channelCount >::Base = detail::BufferViewData<T* const, channelCount> private
Definition at line 472 of file AudioBufferView.h.
Constructor & Destructor Documentation
PlanarBufferView() [1/3]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> template<typename U = T> requires (std::is_const_v<U> && channelCount != DynamicChannelCount) lmms::PlanarBufferView< T, channelCount >::PlanarBufferView (PlanarBufferView< std::remove_const_t< U >, channelCount > other) inline constexpr noexcept
Construct const from mutable (static channel count).
Definition at line 479 of file AudioBufferView.h.
References PlanarBufferView().
Referenced by PlanarBufferView(), and PlanarBufferView().
PlanarBufferView() [2/3]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> template<typename U = T> requires (std::is_const_v<U> && channelCount == DynamicChannelCount) lmms::PlanarBufferView< T, channelCount >::PlanarBufferView (PlanarBufferView< std::remove_const_t< U >, channelCount > other) inline constexpr noexcept
Construct const from mutable (dynamic channel count).
Definition at line 486 of file AudioBufferView.h.
References PlanarBufferView().
PlanarBufferView() [3/3]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> template<proc_ch_t otherChannels> requires (channelCount == DynamicChannelCount && otherChannels != DynamicChannelCount) lmms::PlanarBufferView< T, channelCount >::PlanarBufferView (PlanarBufferView< T, otherChannels > other) inline constexpr noexcept
Construct dynamic channel count from static.
Definition at line 494 of file AudioBufferView.h.
References PlanarBufferView(), lmms::detail::BufferViewData< T, channelCount >::data(), and lmms::detail::BufferViewData< T, channelCount >::frames().
Member Function Documentation
buffer() [1/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> template<proc_ch_t channel> requires (channelCount != DynamicChannelCount) auto lmms::PlanarBufferView< T, channelCount >::buffer () const->std::span< T > inline constexpr noexcept
Returns
the buffer of the given channel
Definition at line 512 of file AudioBufferView.h.
References bufferPtr(), and lmms::detail::BufferViewData< T *const, DynamicChannelCount >::m_frames.
buffer() [2/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::PlanarBufferView< T, channelCount >::buffer (proc_ch_t channel) const->std::span< T > inline constexpr noexcept
Returns
the buffer of the given channel
Definition at line 505 of file AudioBufferView.h.
References bufferPtr(), and lmms::detail::BufferViewData< T *const, DynamicChannelCount >::m_frames.
bufferPtr() [1/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> template<proc_ch_t channel> requires (channelCount != DynamicChannelCount) auto lmms::PlanarBufferView< T, channelCount >::bufferPtr () const->T * inline constexpr noexcept
Returns
pointer to the buffer of the given channel. The size of the buffer is frames().
Definition at line 533 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T *const, DynamicChannelCount >::m_data.
bufferPtr() [2/2]
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::PlanarBufferView< T, channelCount >::bufferPtr (proc_ch_t channel) const->T * inline constexpr noexcept
Returns
pointer to the buffer of the given channel. The size of the buffer is frames().
Definition at line 521 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T *const, channelCount >::channels(), and lmms::detail::BufferViewData< T *const, DynamicChannelCount >::m_data.
Referenced by buffer(), buffer(), and operator[]().
empty()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::PlanarBufferView< T, channelCount >::empty () const->bool inline constexpr noexcept
Definition at line 499 of file AudioBufferView.h.
References lmms::detail::BufferViewData< T *const, channelCount >::channels(), lmms::detail::BufferViewData< T *const, DynamicChannelCount >::m_data, and lmms::detail::BufferViewData< T *const, DynamicChannelCount >::m_frames.
operator[]()
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> auto lmms::PlanarBufferView< T, channelCount >::operator[] (proc_ch_t channel) const->T * inline constexpr noexcept
Returns
pointer to the buffer of a given channel. The size of the buffer is frames().
Definition at line 544 of file AudioBufferView.h.
References bufferPtr().
Member Data Documentation
Interleaved
template<SampleType T, proc_ch_t channelCount = DynamicChannelCount> bool lmms::PlanarBufferView< T, channelCount >::Interleaved = false static constexpr
Use to distinguish between InterleavedBufferView and PlanarBufferView when using AudioBufferView.
Definition at line 550 of file AudioBufferView.h.
The documentation for this class was generated from the following file:
include/AudioBufferView.h