LMMS: hiir::PhaseHalfPi4Neon< NC > Class Template Reference
hiir::PhaseHalfPi4Neon< NC > Class Template Reference
#include <PhaseHalfPi4Neon.h>
Public Types
typedef float DataType
Public Member Functions
PhaseHalfPi4Neon () noexcept
PhaseHalfPi4Neon (const PhaseHalfPi4Neon< NC > &other)=default
PhaseHalfPi4Neon (PhaseHalfPi4Neon< NC > &&other)=default
~PhaseHalfPi4Neon ()=default
void clear_buffers () noexcept
PhaseHalfPi4Neon< NC > & operator= (const PhaseHalfPi4Neon< NC > &other)=default
PhaseHalfPi4Neon< NC > & operator= (PhaseHalfPi4Neon< NC > &&other)=default
void process_block (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (float32x4_t &out_0, float32x4_t &out_1, float32x4_t input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 4
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataNeonV4, NBR_COEFS+2 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const PhaseHalfPi4Neon &other) const =delete
bool operator== (const PhaseHalfPi4Neon &other) const =delete
Private Attributes
FilterBiPhase _bifilter
int _phase
float _prev [_nbr_chn]
Static Private Attributes
static constexpr int _nbr_phases = 2
Detailed Description
template<int NC>
class hiir::PhaseHalfPi4Neon< NC >
Definition at line 49 of file PhaseHalfPi4Neon.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::PhaseHalfPi4Neon< NC >::DataType
Definition at line 58 of file PhaseHalfPi4Neon.h.
Filter
template<int NC> typedef std::array<StageDataNeonV4, NBR_COEFS + 2> hiir::PhaseHalfPi4Neon< NC >::Filter private
Definition at line 95 of file PhaseHalfPi4Neon.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::PhaseHalfPi4Neon< NC >::FilterBiPhase private
Definition at line 97 of file PhaseHalfPi4Neon.h.
Constructor & Destructor Documentation
PhaseHalfPi4Neon() [1/3]
template<int NC> hiir::PhaseHalfPi4Neon< NC >::PhaseHalfPi4Neon () noexcept
Definition at line 58 of file PhaseHalfPi4Neon.hpp.
References _bifilter, _phase, clear_buffers(), i, NBR_COEFS, and hiir::storea().
Referenced by PhaseHalfPi4Neon(), PhaseHalfPi4Neon(), ~PhaseHalfPi4Neon(), operator!=(), operator=(), operator=(), and operator==().
PhaseHalfPi4Neon() [2/3]
template<int NC> hiir::PhaseHalfPi4Neon< NC >::PhaseHalfPi4Neon (const PhaseHalfPi4Neon< NC > & other) default
References PhaseHalfPi4Neon().
PhaseHalfPi4Neon() [3/3]
template<int NC> hiir::PhaseHalfPi4Neon< NC >::PhaseHalfPi4Neon (PhaseHalfPi4Neon< NC > && other) default
References PhaseHalfPi4Neon().
~PhaseHalfPi4Neon()
template<int NC> hiir::PhaseHalfPi4Neon< NC >::~PhaseHalfPi4Neon () default
References PhaseHalfPi4Neon().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::PhaseHalfPi4Neon< NC >::clear_buffers () noexcept
Definition at line 227 of file PhaseHalfPi4Neon.hpp.
References _bifilter, _phase, _prev, i, NBR_COEFS, and hiir::storea().
Referenced by PhaseHalfPi4Neon(), and operator=().
operator!=()
template<int NC> bool hiir::PhaseHalfPi4Neon< NC >::operator!= (const PhaseHalfPi4Neon< NC > & other) const private delete
References PhaseHalfPi4Neon().
operator=() [1/2]
template<int NC> PhaseHalfPi4Neon< NC > & hiir::PhaseHalfPi4Neon< NC >::operator= (const PhaseHalfPi4Neon< NC > & other) default
References PhaseHalfPi4Neon().
operator=() [2/2]
template<int NC> PhaseHalfPi4Neon< NC > & hiir::PhaseHalfPi4Neon< NC >::operator= (PhaseHalfPi4Neon< NC > && other) default
References PhaseHalfPi4Neon(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::PhaseHalfPi4Neon< NC >::operator== (const PhaseHalfPi4Neon< NC > & other) const private delete
References PhaseHalfPi4Neon().
process_block()
template<int NC> void hiir::PhaseHalfPi4Neon< NC >::process_block (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 151 of file PhaseHalfPi4Neon.hpp.
References _bifilter, _nbr_chn, _nbr_phases, _phase, _prev, hiir::load4a(), hiir::load4u(), NBR_COEFS, pos, process_sample(), hiir::StageProc4Neon< REMAINING >::process_sample_neg(), hiir::storea(), and hiir::storeu().
Referenced by operator=().
process_sample()
template<int NC> void hiir::PhaseHalfPi4Neon< NC >::process_sample (float32x4_t & out_0, float32x4_t & out_1, float32x4_t input) noexcept
Definition at line 118 of file PhaseHalfPi4Neon.hpp.
References _bifilter, _phase, _prev, hiir::load4a(), NBR_COEFS, hiir::StageProc4Neon< REMAINING >::process_sample_neg(), and hiir::storea().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::PhaseHalfPi4Neon< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 88 of file PhaseHalfPi4Neon.hpp.
References _bifilter, i, NBR_COEFS, and hiir::storea().
Referenced by operator=().
Member Data Documentation
_bifilter
template<int NC> FilterBiPhase hiir::PhaseHalfPi4Neon< NC >::_bifilter private
Definition at line 99 of file PhaseHalfPi4Neon.h.
Referenced by PhaseHalfPi4Neon(), clear_buffers(), process_block(), process_sample(), and set_coefs().
_delay
template<int NC> double hiir::PhaseHalfPi4Neon< NC >::_delay = 0 static constexpr
Definition at line 61 of file PhaseHalfPi4Neon.h.
_nbr_chn
template<int NC> int hiir::PhaseHalfPi4Neon< NC >::_nbr_chn = 4 static constexpr
Definition at line 59 of file PhaseHalfPi4Neon.h.
Referenced by process_block().
_nbr_phases
template<int NC> int hiir::PhaseHalfPi4Neon< NC >::_nbr_phases = 2 static constexpr private
Definition at line 93 of file PhaseHalfPi4Neon.h.
Referenced by process_block().
_phase
template<int NC> int hiir::PhaseHalfPi4Neon< NC >::_phase private
Definition at line 102 of file PhaseHalfPi4Neon.h.
Referenced by PhaseHalfPi4Neon(), clear_buffers(), process_block(), and process_sample().
_prev
template<int NC> float hiir::PhaseHalfPi4Neon< NC >::_prev[_nbr_chn] private
Definition at line 101 of file PhaseHalfPi4Neon.h.
Referenced by clear_buffers(), process_block(), and process_sample().
NBR_COEFS
template<int NC> int hiir::PhaseHalfPi4Neon< NC >::NBR_COEFS = NC static constexpr
Definition at line 60 of file PhaseHalfPi4Neon.h.
Referenced by PhaseHalfPi4Neon(), clear_buffers(), process_block(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/PhaseHalfPi4Neon.h
src/3rdparty/hiir/hiir/PhaseHalfPi4Neon.hpp