LMMS: Jack::JackWinNamedPipeServerChannel Class Reference
Jack::JackWinNamedPipeServerChannel Class Reference
JackServerChannel using pipe.
#include <JackWinNamedPipeServerChannel.h>
Public Member Functions
JackWinNamedPipeServerChannel ()
~JackWinNamedPipeServerChannel ()
void Close ()
bool Execute ()
bool Init ()
Called once when the thread is started.
int Open (const char *server_name, JackServer *server)
int Start ()
void Stop ()
Private Member Functions
bool ClientAccept ()
void ClientAdd (JackWinNamedPipeClient *pipe)
bool ClientListen ()
Private Attributes
std::list< JackClientPipeThread * > fClientList
JackWinNamedPipeServer fRequestListenPipe
JackServer * fServer
char fServerName [JACK_SERVER_NAME_SIZE+1]
JackThread fThread
Additional Inherited Members
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Detailed Description
JackServerChannel using pipe.
Definition at line 75 of file JackWinNamedPipeServerChannel.h.
Constructor & Destructor Documentation
JackWinNamedPipeServerChannel()
Jack::JackWinNamedPipeServerChannel::JackWinNamedPipeServerChannel ()
Definition at line 145 of file JackWinNamedPipeServerChannel.cpp.
References fThread.
~JackWinNamedPipeServerChannel()
Jack::JackWinNamedPipeServerChannel::~JackWinNamedPipeServerChannel ()
Definition at line 148 of file JackWinNamedPipeServerChannel.cpp.
References client(), and fClientList.
Member Function Documentation
ClientAccept()
bool Jack::JackWinNamedPipeServerChannel::ClientAccept () private
Definition at line 219 of file JackWinNamedPipeServerChannel.cpp.
References ClientAdd(), fRequestListenPipe, and jack_error.
Referenced by Execute(), and Init().
ClientAdd()
void Jack::JackWinNamedPipeServerChannel::ClientAdd (JackWinNamedPipeClient * pipe) private
Definition at line 241 of file JackWinNamedPipeServerChannel.cpp.
References client(), fClientList, fServer, and jack_log().
Referenced by ClientAccept().
ClientListen()
bool Jack::JackWinNamedPipeServerChannel::ClientListen () private
Definition at line 209 of file JackWinNamedPipeServerChannel.cpp.
References fRequestListenPipe, fServerName, jack_error, and jack_server_dir.
Referenced by Execute(), and Open().
Close()
void Jack::JackWinNamedPipeServerChannel::Close ()
Definition at line 174 of file JackWinNamedPipeServerChannel.cpp.
References fRequestListenPipe.
Execute()
bool Jack::JackWinNamedPipeServerChannel::Execute () virtual
Implements Jack::JackRunnableInterface.
Definition at line 232 of file JackWinNamedPipeServerChannel.cpp.
References ClientAccept(), and ClientListen().
Init()
bool Jack::JackWinNamedPipeServerChannel::Init () virtual
Called once when the thread is started.
Reimplemented from Jack::JackRunnableInterface.
Definition at line 202 of file JackWinNamedPipeServerChannel.cpp.
References ClientAccept(), and jack_log().
Open()
int Jack::JackWinNamedPipeServerChannel::Open (const char * server_name, JackServer * server)
Definition at line 159 of file JackWinNamedPipeServerChannel.cpp.
References ClientListen(), fServer, fServerName, jack_error, jack_log(), server(), and server_name.
Start()
int Jack::JackWinNamedPipeServerChannel::Start ()
Definition at line 187 of file JackWinNamedPipeServerChannel.cpp.
References fThread, and jack_error.
Stop()
void Jack::JackWinNamedPipeServerChannel::Stop ()
Definition at line 197 of file JackWinNamedPipeServerChannel.cpp.
References fThread.
Member Data Documentation
fClientList
std::list<JackClientPipeThread*> Jack::JackWinNamedPipeServerChannel::fClientList private
Definition at line 85 of file JackWinNamedPipeServerChannel.h.
Referenced by ~JackWinNamedPipeServerChannel(), and ClientAdd().
fRequestListenPipe
JackWinNamedPipeServer Jack::JackWinNamedPipeServerChannel::fRequestListenPipe private
Definition at line 80 of file JackWinNamedPipeServerChannel.h.
Referenced by ClientAccept(), ClientListen(), and Close().
fServer
JackServer* Jack::JackWinNamedPipeServerChannel::fServer private
Definition at line 81 of file JackWinNamedPipeServerChannel.h.
Referenced by ClientAdd(), and Open().
fServerName
char Jack::JackWinNamedPipeServerChannel::fServerName[JACK_SERVER_NAME_SIZE+1] private
Definition at line 83 of file JackWinNamedPipeServerChannel.h.
Referenced by ClientListen(), and Open().
fThread
JackThread Jack::JackWinNamedPipeServerChannel::fThread private
Definition at line 82 of file JackWinNamedPipeServerChannel.h.
Referenced by JackWinNamedPipeServerChannel(), Start(), and Stop().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinNamedPipeServerChannel.h
src/3rdparty/jack2/windows/JackWinNamedPipeServerChannel.cpp