LMMS: Jack::JackWinNamedPipeNotifyChannel Class Reference
Jack::JackWinNamedPipeNotifyChannel Class Reference
JackNotifyChannel using named pipe.
#include <JackWinNamedPipeNotifyChannel.h>
Public Member Functions
JackWinNamedPipeNotifyChannel ()
void ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2, int *result)
void Close ()
int Open (const char *name)
Private Attributes
JackWinNamedPipeClient fNotifyPipe
Detailed Description
JackNotifyChannel using named pipe.
Definition at line 33 of file JackWinNamedPipeNotifyChannel.h.
Constructor & Destructor Documentation
JackWinNamedPipeNotifyChannel()
Jack::JackWinNamedPipeNotifyChannel::JackWinNamedPipeNotifyChannel () inline
Definition at line 42 of file JackWinNamedPipeNotifyChannel.h.
Member Function Documentation
ClientNotify()
void Jack::JackWinNamedPipeNotifyChannel::ClientNotify (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value2, int * result)
Definition at line 50 of file JackWinNamedPipeNotifyChannel.cpp.
References fNotifyPipe, Jack::JackResult::fResult, jack_error, Jack::JackResult::Read(), and Jack::JackClientNotification::Write().
Close()
void Jack::JackWinNamedPipeNotifyChannel::Close ()
Definition at line 44 of file JackWinNamedPipeNotifyChannel.cpp.
References fNotifyPipe, and jack_log().
Open()
int Jack::JackWinNamedPipeNotifyChannel::Open (const char * name)
Definition at line 30 of file JackWinNamedPipeNotifyChannel.cpp.
References fNotifyPipe, jack_client_dir, jack_error, jack_log(), and SOCKET_TIME_OUT.
Member Data Documentation
fNotifyPipe
JackWinNamedPipeClient Jack::JackWinNamedPipeNotifyChannel::fNotifyPipe private
Definition at line 38 of file JackWinNamedPipeNotifyChannel.h.
Referenced by ClientNotify(), Close(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinNamedPipeNotifyChannel.h
src/3rdparty/jack2/windows/JackWinNamedPipeNotifyChannel.cpp