LMMS: lmms::AutomatableModel Class Reference
lmms::AutomatableModel Class Reference abstract
#include <AutomatableModel.h>
Classes
struct ConstDCastVisitor
struct DCastVisitor
Public Types
using AutoModelVector = std::vector<AutomatableModel*>
enum class ScaleType {
Linear ,
Logarithmic ,
Decibel
}
Public Slots
virtual void reset ()
void setUseControllerValue (bool b=true)
void unlinkControllerConnection ()
Signals
void destroyed (lmms::jo_id_t id)
void initValueChanged (float val)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
~AutomatableModel () override
virtual void accept (ConstModelVisitor &v) const =0
virtual void accept (ModelVisitor &v)=0
float centerValue () const
ControllerConnection * controllerConnection () const
float controllerValue (int frameOffset) const
virtual QString displayValue (const float val) const =0
template<class Target>
Target * dynamicCast (bool doThrow=false)
Return this class casted to Target.
template<class Target>
const Target * dynamicCast (bool doThrow=false) const
const overload, see overloaded function
float globalAutomationValueAt (const TimePos &time)
bool hasLinkedModels () const
void incValue (int steps)
template<class T>
T initValue () const
float inverseScaledValue (float value) const
Returns value applied with the inverse of this model's scale type.
bool isAtInitValue () const
bool isAutomated () const
bool isAutomatedOrControlled () const
bool isScaleLogarithmic () const
bool isValueChanged ()
virtual void loadSettings (const QDomElement &element, const QString &name)
Loads settings (value, automation links and controller connections) of AutomatableModel from specified DOM element using <name> as attribute/node name.
template<class T>
T maxValue () const
template<class T>
T minValue () const
QString nodeName () const override
float range () const
virtual void saveSettings (QDomDocument &doc, QDomElement &element, const QString &name)
Saves settings (value, automation links and controller connections) of AutomatableModel into specified DOM element using <name> as attribute/node name.
float scaledValue (float value) const
Returns value scaled with the scale type and min/max values of this model.
void setAutomatedValue (const float value)
void setCenterValue (const float centerVal)
void setControllerConnection (ControllerConnection *c)
void setInitValue (const float value)
void setRange (const float min, const float max, const float step=1)
void setScaleLogarithmic (bool setToTrue=true)
void setScaleType (ScaleType sc)
void setStep (const float step)
void setStrictStepSize (const bool b)
void setValue (const float value)
template<class T>
T step () const
void unlinkAllModels ()
bool useControllerValue ()
template<class T>
T value (int frameOffset=0) const
ValueBuffer * valueBuffer ()
Function that returns sample-exact data as a ValueBuffer.
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
template<bool>
static bool castValue (const float v)
template<class T>
static T castValue (const float v)
static void incrementPeriodCounter ()
static void linkModels (AutomatableModel *m1, AutomatableModel *m2)
link m1 and m2, let m1 take the values of m2
static void resetPeriodCounter ()
static void unlinkModels (AutomatableModel *m1, AutomatableModel *m2)
Protected Member Functions
AutomatableModel (const float val=0, const float min=0, const float max=0, const float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
float fittedValue (float value) const
returns a value which is in range between min() and max() and aligned according to the step size (step size 0.05 -> value 0.12345 becomes 0.10 etc.).
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Member Functions
void linkModel (AutomatableModel *model)
void loadSettings (const QDomElement &element) override
template<class T>
T logToLinearScale (T value) const
Scales @value from linear to logarithmic.
template<class T>
void roundAt (T &value, const T &where) const
rounds value to where if it is close to it
void saveSettings (QDomDocument &doc, QDomElement &element) override
void unlinkModel (AutomatableModel *model)
Static Private Member Functions
static bool mustQuoteName (const QString &name)
Private Attributes
float m_centerValue
ControllerConnection * m_controllerConnection
NULL if not appended to controller, otherwise connection info.
bool m_hasSampleExactData
bool m_hasStrictStepSize
float m_initValue
long m_lastUpdatedPeriod
AutoModelVector m_linkedModels
float m_maxValue
float m_minValue
float m_oldValue
float m_range
ScaleType m_scaleType
scale type, linear by default
int m_setValueDepth
float m_step
bool m_useControllerValue
float m_value
ValueBuffer m_valueBuffer
QMutex m_valueBufferMutex
bool m_valueChanged
Static Private Attributes
static long s_periodCounter = 0
Detailed Description
Definition at line 76 of file AutomatableModel.h.
Member Typedef Documentation
AutoModelVector
using lmms::AutomatableModel::AutoModelVector = std::vector<AutomatableModel*>
Definition at line 80 of file AutomatableModel.h.
Member Enumeration Documentation
ScaleType
enum class lmms::AutomatableModel::ScaleType strong
Enumerator
Linear
Logarithmic
Decibel
Definition at line 82 of file AutomatableModel.h.
Constructor & Destructor Documentation
~AutomatableModel()
lmms::AutomatableModel::~AutomatableModel () override
Definition at line 72 of file AutomatableModel.cpp.
References destroyed(), m_controllerConnection, m_linkedModels, and m_valueBuffer.
AutomatableModel()
lmms::AutomatableModel::AutomatableModel (const float val = 0, const float min = 0, const float max = 0, const float step = 0, Model * parent = nullptr, const QString & displayName = QString(), bool defaultConstructed = false) protected
Definition at line 45 of file AutomatableModel.cpp.
References lmms::Model::Model(), lmms::Model::displayName(), fittedValue(), m_centerValue, m_controllerConnection, m_hasSampleExactData, m_hasStrictStepSize, m_lastUpdatedPeriod, m_maxValue, m_minValue, m_range, m_scaleType, m_setValueDepth, m_step, m_useControllerValue, m_value, m_valueBuffer, m_valueChanged, max, min, setInitValue(), and step().
Referenced by controllerValue(), linkModel(), linkModels(), unlinkAllModels(), unlinkModel(), unlinkModels(), and valueBuffer().
Member Function Documentation
accept() [1/2]
virtual void lmms::AutomatableModel::accept (ConstModelVisitor & v) const pure virtual
accept() [2/2]
virtual void lmms::AutomatableModel::accept (ModelVisitor & v) pure virtual
Referenced by dynamicCast(), and dynamicCast().
castValue() [1/2]
template<bool> bool lmms::AutomatableModel::castValue (const float v) inline static
Definition at line 144 of file AutomatableModel.h.
castValue() [2/2]
template<class T> T lmms::AutomatableModel::castValue (const float v) inline static
Definition at line 138 of file AutomatableModel.h.
Referenced by lmms::BoolModel::displayValue(), lmms::FloatModel::displayValue(), lmms::IntModel::displayValue(), initValue(), logToLinearScale(), maxValue(), minValue(), step(), and value().
centerValue()
float lmms::AutomatableModel::centerValue () const inline
Definition at line 242 of file AutomatableModel.h.
References m_centerValue.
controllerConnection()
ControllerConnection * lmms::AutomatableModel::controllerConnection () const inline
Definition at line 128 of file AutomatableModel.h.
References m_controllerConnection.
Referenced by controllerValue(), lmms::gui::AutomatableModelViewSlots::execConnectionDialog(), lmms::Song::processAutomations(), lmms::gui::AutomatableModelViewSlots::removeConnection(), and valueBuffer().
controllerValue()
float lmms::AutomatableModel::controllerValue (int frameOffset) const
Definition at line 556 of file AutomatableModel.cpp.
References AutomatableModel(), lmms::approximatelyEqual(), controllerConnection(), controllerValue(), lmms::ControllerConnection::currentValue(), fittedValue(), Linear, Logarithmic, logToLinearScale(), m_controllerConnection, m_hasStrictStepSize, m_linkedModels, m_scaleType, m_step, m_value, minValue(), range(), and useControllerValue().
Referenced by controllerValue(), and value().
destroyed
void lmms::AutomatableModel::destroyed (lmms::jo_id_t id) signal
Referenced by ~AutomatableModel(), lmms::LinkedModelGroup::addModel(), and setControllerConnection().
displayValue()
virtual QString lmms::AutomatableModel::displayValue (const float val) const pure virtual
Implemented in lmms::BoolModel, lmms::FloatModel, and lmms::IntModel.
dynamicCast() [1/2]
template<class Target> Target * lmms::AutomatableModel::dynamicCast (bool doThrow = false) inline
Return this class casted to Target.
Test
AutomatableModelTest.cpp
Parameters
doThrow throw an assertion if the cast fails, instead of returning a nullptr
Returns
the casted class if Target is the exact or a base class of this, nullptr otherwise
Definition at line 106 of file AutomatableModel.h.
References accept(), and lmms::AutomatableModel::DCastVisitor< Target >::result.
dynamicCast() [2/2]
template<class Target> const Target * lmms::AutomatableModel::dynamicCast (bool doThrow = false) const inline
const overload, see overloaded function
Definition at line 115 of file AutomatableModel.h.
References accept(), and lmms::AutomatableModel::ConstDCastVisitor< Target >::result.
fittedValue()
float lmms::AutomatableModel::fittedValue (float value) const protected
returns a value which is in range between min() and max() and aligned according to the step size (step size 0.05 -> value 0.12345 becomes 0.10 etc.).
You should always call it at the end after doing your own calculations.
Definition at line 434 of file AutomatableModel.cpp.
References m_hasStrictStepSize, m_maxValue, m_minValue, m_step, roundAt(), and value().
Referenced by AutomatableModel(), controllerValue(), globalAutomationValueAt(), setAutomatedValue(), setInitValue(), setValue(), and valueBuffer().
globalAutomationValueAt()
float lmms::AutomatableModel::globalAutomationValueAt (const TimePos & time)
Definition at line 711 of file AutomatableModel.cpp.
References lmms::AutomationClip::clipsForModel(), fittedValue(), m_value, scaledValue(), lmms::Clip::startPosition(), lmms::Clip::startTimeOffset(), value(), and lmms::AutomationClip::valueAt().
hasLinkedModels()
bool lmms::AutomatableModel::hasLinkedModels () const inline
Definition at line 279 of file AutomatableModel.h.
References m_linkedModels.
Referenced by linkModel(), value(), and valueBuffer().
incrementPeriodCounter()
void lmms::AutomatableModel::incrementPeriodCounter () inline static
Definition at line 304 of file AutomatableModel.h.
References s_periodCounter.
Referenced by lmms::AudioEngine::renderStageMix().
incValue()
void lmms::AutomatableModel::incValue (int steps) inline
Definition at line 217 of file AutomatableModel.h.
References m_step, m_value, and setValue().
Referenced by lmms::gui::FloatModelEditorBase::wheelEvent().
initValue()
template<class T> T lmms::AutomatableModel::initValue () const inline
Definition at line 179 of file AutomatableModel.h.
References castValue(), and m_initValue.
Referenced by lmms::TypedAutomatableModel< T >::initValue(), and reset().
initValueChanged
void lmms::AutomatableModel::initValueChanged (float val) signal
Referenced by setInitValue().
inverseScaledValue()
float lmms::AutomatableModel::inverseScaledValue (float value) const
Returns value applied with the inverse of this model's scale type.
Definition at line 346 of file AutomatableModel.cpp.
References Linear, lmms::linearToLogScale(), m_scaleType, maxValue(), minValue(), and value().
Referenced by lmms::AutomationClip::addObject(), lmms::gui::BarModelEditor::paintEvent(), and lmms::Song::processAutomations().
isAtInitValue()
bool lmms::AutomatableModel::isAtInitValue () const inline
Definition at line 184 of file AutomatableModel.h.
References m_initValue, and m_value.
Referenced by lmms::InlineAutomation::hasAutomation().
isAutomated()
bool lmms::AutomatableModel::isAutomated () const
Definition at line 93 of file AutomatableModel.cpp.
References lmms::AutomationClip::isAutomated().
Referenced by isAutomatedOrControlled(), and saveSettings().
isAutomatedOrControlled()
bool lmms::AutomatableModel::isAutomatedOrControlled () const inline
Definition at line 123 of file AutomatableModel.h.
References isAutomated(), and m_controllerConnection.
isScaleLogarithmic()
bool lmms::AutomatableModel::isScaleLogarithmic () const inline
Definition at line 235 of file AutomatableModel.h.
References Logarithmic, and m_scaleType.
isValueChanged()
bool lmms::AutomatableModel::isValueChanged () inline
Definition at line 287 of file AutomatableModel.h.
References m_valueChanged, and valueBuffer().
linkModel()
void lmms::AutomatableModel::linkModel (AutomatableModel * model) private
Definition at line 463 of file AutomatableModel.cpp.
References AutomatableModel(), lmms::Model::dataChanged(), hasLinkedModels(), and m_linkedModels.
Referenced by linkModels().
linkModels()
void lmms::AutomatableModel::linkModels (AutomatableModel * m1, AutomatableModel * m2) static
link m1 and m2, let m1 take the values of m2
Definition at line 495 of file AutomatableModel.cpp.
References AutomatableModel(), lmms::Model::dataChanged(), lmms::ValueBuffer::length(), linkModel(), m_linkedModels, m_value, and valueBuffer().
Referenced by lmms::gui::FloatModelEditorBase::dropEvent(), lmms::LadspaControl::linkControls(), and lmms::LinkedModelGroup::linkControls().
loadSettings() [1/2]
void lmms::AutomatableModel::loadSettings (const QDomElement & element) inline override private virtual
Implements lmms::SerializingObject.
Reimplemented in lmms::InlineAutomation.
Definition at line 365 of file AutomatableModel.h.
References loadSettings().
loadSettings() [2/2]
void lmms::AutomatableModel::loadSettings (const QDomElement & element, const QString & name) virtual
Loads settings (value, automation links and controller connections) of AutomatableModel from specified DOM element using <name> as attribute/node name.
Reimplemented in lmms::TempoSyncKnobModel.
Definition at line 181 of file AutomatableModel.cpp.
References lmms::JournallingObject::changeID(), lmms::AutomationClip::classNodeName(), lmms::AutomationClip::globalAutomationClip(), lmms::AutomationClip::hasAutomation(), Linear, lmms::AutomationClip::loadSettings(), Logarithmic, m_controllerConnection, reset(), setControllerConnection(), setInitValue(), setScaleType(), setValue(), lmms::LocaleHelper::toFloat(), and lmms::AutomationClip::valueAt().
Referenced by loadSettings(), lmms::Mixer::loadSettings(), lmms::TempoSyncKnobModel::loadSettings(), and lmms::LinkedModelGroup::loadValues().
logToLinearScale()
template<class T> T lmms::AutomatableModel::logToLinearScale (T value) const private
Scales @value from linear to logarithmic.
Value should be within [0,1]
Definition at line 332 of file AutomatableModel.cpp.
References castValue(), lmms::logToLinearScale(), maxValue(), minValue(), and value().
Referenced by controllerValue(), scaledValue(), and valueBuffer().
maxValue()
template<class T> T lmms::AutomatableModel::maxValue () const inline
Definition at line 196 of file AutomatableModel.h.
References castValue(), and m_maxValue.
Referenced by inverseScaledValue(), logToLinearScale(), and lmms::TypedAutomatableModel< T >::maxValue().
minValue()
template<class T> T lmms::AutomatableModel::minValue () const inline
Definition at line 190 of file AutomatableModel.h.
References castValue(), and m_minValue.
Referenced by controllerValue(), inverseScaledValue(), logToLinearScale(), lmms::TypedAutomatableModel< T >::minValue(), scaledValue(), and valueBuffer().
mustQuoteName()
bool lmms::AutomatableModel::mustQuoteName (const QString & name) static private
Definition at line 100 of file AutomatableModel.cpp.
Referenced by saveSettings().
nodeName()
QString lmms::AutomatableModel::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Reimplemented in lmms::DetuningHelper.
Definition at line 272 of file AutomatableModel.h.
Referenced by lmms::InlineAutomation::loadSettings(), and lmms::InlineAutomation::saveSettings().
range()
float lmms::AutomatableModel::range () const inline
Definition at line 222 of file AutomatableModel.h.
References m_range.
Referenced by controllerValue(), and valueBuffer().
reset
void lmms::AutomatableModel::reset () virtual slot
Definition at line 703 of file AutomatableModel.cpp.
References initValue(), and setValue().
Referenced by loadSettings(), and lmms::gui::AutomatableModelView::mousePressEvent().
resetPeriodCounter()
void lmms::AutomatableModel::resetPeriodCounter () inline static
Definition at line 309 of file AutomatableModel.h.
References s_periodCounter.
roundAt()
template<class T> void lmms::AutomatableModel::roundAt (T & value, const T & where) const private
rounds value to where if it is close to it
Parameters
value will be modified to rounded value
Definition at line 357 of file AutomatableModel.cpp.
References m_step, lmms::roundAt(), and value().
Referenced by fittedValue().
saveSettings() [1/2]
void lmms::AutomatableModel::saveSettings (QDomDocument & doc, QDomElement & element) inline override private virtual
Implements lmms::SerializingObject.
Reimplemented in lmms::InlineAutomation.
Definition at line 360 of file AutomatableModel.h.
References saveSettings().
saveSettings() [2/2]
void lmms::AutomatableModel::saveSettings (QDomDocument & doc, QDomElement & element, const QString & name) virtual
Saves settings (value, automation links and controller connections) of AutomatableModel into specified DOM element using <name> as attribute/node name.
Parameters
doc TODO
element Where this option shall be saved. Depending on the model, this can be done in an attribute or in a subnode.
name Name to store this model as.
Reimplemented in lmms::TempoSyncKnobModel.
Definition at line 106 of file AutomatableModel.cpp.
References lmms::Song::SaveOptions::discardMIDIConnections, lmms::Controller::Dummy, lmms::Song::getSaveOptions(), lmms::Engine::getSong(), lmms::ProjectJournal::idToSave(), isAutomated(), lmms::Song::isSavingProject(), Linear, Logarithmic, m_controllerConnection, m_scaleType, m_value, lmms::Controller::Midi, mustQuoteName(), and lmms::TypedAutomatableModel< T >::value().
Referenced by saveSettings(), lmms::Mixer::saveSettings(), lmms::TempoSyncKnobModel::saveSettings(), and lmms::LinkedModelGroup::saveValues().
scaledValue()
float lmms::AutomatableModel::scaledValue (float value) const
Returns value scaled with the scale type and min/max values of this model.
Definition at line 338 of file AutomatableModel.cpp.
References Linear, logToLinearScale(), m_range, m_scaleType, minValue(), and value().
Referenced by lmms::BoolModel::displayValue(), lmms::FloatModel::displayValue(), lmms::IntModel::displayValue(), globalAutomationValueAt(), setAutomatedValue(), lmms::gui::FloatModelEditorBase::setPosition(), and lmms::gui::FloatModelEditorBase::wheelEvent().
setAutomatedValue()
void lmms::AutomatableModel::setAutomatedValue (const float value)
Definition at line 365 of file AutomatableModel.cpp.
References lmms::Model::dataChanged(), fittedValue(), m_linkedModels, m_oldValue, m_setValueDepth, m_value, m_valueChanged, scaledValue(), setUseControllerValue(), and value().
setCenterValue()
void lmms::AutomatableModel::setCenterValue (const float centerVal) inline
Definition at line 247 of file AutomatableModel.h.
References m_centerValue.
setControllerConnection()
void lmms::AutomatableModel::setControllerConnection (ControllerConnection * c)
Definition at line 540 of file AutomatableModel.cpp.
References lmms::Model::dataChanged(), destroyed(), m_controllerConnection, m_valueChanged, and unlinkControllerConnection().
Referenced by lmms::gui::AutomatableModelViewSlots::execConnectionDialog(), loadSettings(), and lmms::gui::AutomatableModelViewSlots::removeConnection().
setInitValue()
void lmms::AutomatableModel::setInitValue (const float value)
Definition at line 690 of file AutomatableModel.cpp.
References fittedValue(), initValueChanged(), m_initValue, m_oldValue, m_value, lmms::JournallingObject::setJournalling(), setValue(), lmms::JournallingObject::testAndSetJournalling(), and value().
Referenced by AutomatableModel(), and loadSettings().
setRange()
void lmms::AutomatableModel::setRange (const float min, const float max, const float step = 1)
Definition at line 397 of file AutomatableModel.cpp.
References m_maxValue, m_minValue, m_range, max, min, lmms::Model::propertiesChanged(), setStep(), setValue(), step(), and value().
Referenced by lmms::gui::AutomatableButtonGroup::addButton(), lmms::ComboBoxModel::addItem(), lmms::ComboBoxModel::clear(), and lmms::gui::AutomatableButtonGroup::updateButtons().
setScaleLogarithmic()
void lmms::AutomatableModel::setScaleLogarithmic (bool setToTrue = true) inline
Definition at line 231 of file AutomatableModel.h.
References Linear, Logarithmic, and setScaleType().
Referenced by lmms::gui::FloatModelEditorBase::toggleScale().
setScaleType()
void lmms::AutomatableModel::setScaleType (ScaleType sc) inline
Definition at line 228 of file AutomatableModel.h.
References m_scaleType.
Referenced by loadSettings(), and setScaleLogarithmic().
setStep()
void lmms::AutomatableModel::setStep (const float step)
Definition at line 422 of file AutomatableModel.cpp.
References m_step, lmms::Model::propertiesChanged(), and step().
Referenced by setRange().
setStrictStepSize()
void lmms::AutomatableModel::setStrictStepSize (const bool b) inline
Definition at line 299 of file AutomatableModel.h.
References m_hasStrictStepSize.
setUseControllerValue
void lmms::AutomatableModel::setUseControllerValue (bool b = true) slot
Definition at line 769 of file AutomatableModel.cpp.
References lmms::Model::dataChanged(), m_controllerConnection, and m_useControllerValue.
Referenced by lmms::Song::processAutomations(), setAutomatedValue(), and lmms::Song::stop().
setValue()
void lmms::AutomatableModel::setValue (const float value)
Definition at line 297 of file AutomatableModel.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), lmms::Model::dataChanged(), lmms::Model::dataUnchanged(), fittedValue(), lmms::JournallingObject::isJournalling(), m_linkedModels, m_oldValue, m_setValueDepth, m_value, m_valueChanged, and value().
Referenced by lmms::gui::AutomatableButtonGroup::activateButton(), lmms::gui::AutomatableButtonGroup::addButton(), lmms::gui::Fader::adjustByDialog(), lmms::gui::Fader::adjustModelByDBDelta(), lmms::gui::InstrumentTrackView::assignMixerLine(), lmms::gui::SampleTrackView::assignMixerLine(), lmms::TempoSyncKnobModel::calculateTempoSyncTime(), lmms::gui::AutomatableSlider::changeValue(), lmms::Mixer::clearChannel(), lmms::gui::FloatModelEditorBase::dropEvent(), lmms::gui::FloatModelEditorBase::enterValue(), lmms::gui::LcdFloatSpinBox::enterValue(), lmms::gui::LcdSpinBox::enterValue(), lmms::gui::MixerChannelLcdSpinBox::enterValue(), incValue(), loadSettings(), lmms::gui::Draggable::mouseMoveEvent(), lmms::gui::LcdFloatSpinBox::mouseMoveEvent(), lmms::gui::LcdSpinBox::mouseMoveEvent(), lmms::gui::GroupBox::mousePressEvent(), lmms::gui::AutomatableSlider::moveSlider(), reset(), lmms::gui::ComboBox::selectNext(), lmms::gui::ComboBox::selectPrevious(), setInitValue(), lmms::gui::ComboBox::setItem(), lmms::gui::FloatModelEditorBase::setPosition(), setRange(), lmms::gui::Fader::setVolumeByLocalPixelValue(), lmms::gui::AutomatableButton::toggle(), lmms::gui::ComboBox::wheelEvent(), lmms::gui::LcdFloatSpinBox::wheelEvent(), and lmms::gui::LcdSpinBox::wheelEvent().
step()
template<class T> T lmms::AutomatableModel::step () const inline
Definition at line 202 of file AutomatableModel.h.
References castValue(), and m_step.
Referenced by AutomatableModel(), lmms::FloatModel::FloatModel(), lmms::InlineAutomation::InlineAutomation(), lmms::gui::MixerChannelLcdSpinBox::enterValue(), lmms::FloatModel::getDigitCount(), lmms::FloatModel::getRoundedValue(), lmms::gui::LcdFloatSpinBox::getStep(), lmms::gui::LcdSpinBox::mouseMoveEvent(), lmms::gui::FloatModelEditorBase::setPosition(), setRange(), and setStep().
unlinkAllModels()
void lmms::AutomatableModel::unlinkAllModels ()
Definition at line 529 of file AutomatableModel.cpp.
References AutomatableModel(), m_linkedModels, and unlinkModels().
unlinkControllerConnection
void lmms::AutomatableModel::unlinkControllerConnection () slot
Definition at line 677 of file AutomatableModel.cpp.
References m_controllerConnection.
Referenced by setControllerConnection().
unlinkModel()
void lmms::AutomatableModel::unlinkModel (AutomatableModel * model) private
Definition at line 481 of file AutomatableModel.cpp.
References AutomatableModel(), and m_linkedModels.
Referenced by unlinkModels().
unlinkModels()
void lmms::AutomatableModel::unlinkModels (AutomatableModel * m1, AutomatableModel * m2) static
Definition at line 520 of file AutomatableModel.cpp.
References AutomatableModel(), and unlinkModel().
Referenced by unlinkAllModels(), and lmms::LadspaControl::unlinkControls().
useControllerValue()
bool lmms::AutomatableModel::useControllerValue () inline
Definition at line 314 of file AutomatableModel.h.
References m_useControllerValue.
Referenced by controllerValue(), and valueBuffer().
value()
template<class T> T lmms::AutomatableModel::value (int frameOffset = 0) const inline
Definition at line 151 of file AutomatableModel.h.
References castValue(), controllerValue(), hasLinkedModels(), m_controllerConnection, m_useControllerValue, and m_value.
Referenced by lmms::AutomationClip::addObject(), fittedValue(), globalAutomationValueAt(), inverseScaledValue(), logToLinearScale(), lmms::Song::processAutomations(), roundAt(), scaledValue(), setAutomatedValue(), setInitValue(), setRange(), setValue(), and lmms::TypedAutomatableModel< T >::value().
valueBuffer()
ValueBuffer * lmms::AutomatableModel::valueBuffer ()
Function that returns sample-exact data as a ValueBuffer.
Returns
pointer to model's valueBuffer when s.ex.data exists, NULL otherwise
Definition at line 592 of file AutomatableModel.cpp.
References AutomatableModel(), controllerConnection(), fittedValue(), lmms::ControllerConnection::getController(), hasLinkedModels(), i, lmms::Controller::isSampleExact(), Linear, Logarithmic, logToLinearScale(), m_controllerConnection, m_hasSampleExactData, m_lastUpdatedPeriod, m_linkedModels, m_oldValue, m_scaleType, m_useControllerValue, m_value, m_valueBuffer, m_valueBufferMutex, minValue(), range(), s_periodCounter, useControllerValue(), valueBuffer(), and lmms::ValueBuffer::values().
Referenced by lmms::MixerChannel::doProcessing(), isValueChanged(), linkModels(), and valueBuffer().
Member Data Documentation
m_centerValue
float lmms::AutomatableModel::m_centerValue private
Definition at line 389 of file AutomatableModel.h.
Referenced by AutomatableModel(), centerValue(), and setCenterValue().
m_controllerConnection
ControllerConnection* lmms::AutomatableModel::m_controllerConnection private
NULL if not appended to controller, otherwise connection info.
Definition at line 405 of file AutomatableModel.h.
Referenced by AutomatableModel(), ~AutomatableModel(), controllerConnection(), controllerValue(), isAutomatedOrControlled(), loadSettings(), saveSettings(), setControllerConnection(), setUseControllerValue(), unlinkControllerConnection(), value(), and valueBuffer().
m_hasSampleExactData
bool lmms::AutomatableModel::m_hasSampleExactData private
Definition at line 412 of file AutomatableModel.h.
Referenced by AutomatableModel(), and valueBuffer().
m_hasStrictStepSize
bool lmms::AutomatableModel::m_hasStrictStepSize private
Definition at line 399 of file AutomatableModel.h.
Referenced by AutomatableModel(), controllerValue(), fittedValue(), and setStrictStepSize().
m_initValue
float lmms::AutomatableModel::m_initValue private
Definition at line 384 of file AutomatableModel.h.
Referenced by initValue(), isAtInitValue(), and setInitValue().
m_lastUpdatedPeriod
long lmms::AutomatableModel::m_lastUpdatedPeriod private
Definition at line 409 of file AutomatableModel.h.
Referenced by AutomatableModel(), and valueBuffer().
m_linkedModels
AutoModelVector lmms::AutomatableModel::m_linkedModels private
Definition at line 401 of file AutomatableModel.h.
Referenced by ~AutomatableModel(), controllerValue(), hasLinkedModels(), linkModel(), linkModels(), setAutomatedValue(), setValue(), unlinkAllModels(), unlinkModel(), and valueBuffer().
m_maxValue
float lmms::AutomatableModel::m_maxValue private
Definition at line 386 of file AutomatableModel.h.
Referenced by AutomatableModel(), fittedValue(), maxValue(), and setRange().
m_minValue
float lmms::AutomatableModel::m_minValue private
Definition at line 385 of file AutomatableModel.h.
Referenced by AutomatableModel(), fittedValue(), minValue(), and setRange().
m_oldValue
float lmms::AutomatableModel::m_oldValue private
Definition at line 394 of file AutomatableModel.h.
Referenced by setAutomatedValue(), setInitValue(), setValue(), and valueBuffer().
m_range
float lmms::AutomatableModel::m_range private
Definition at line 388 of file AutomatableModel.h.
Referenced by AutomatableModel(), range(), scaledValue(), and setRange().
m_scaleType
ScaleType lmms::AutomatableModel::m_scaleType private
scale type, linear by default
Definition at line 382 of file AutomatableModel.h.
Referenced by AutomatableModel(), controllerValue(), inverseScaledValue(), isScaleLogarithmic(), saveSettings(), scaledValue(), setScaleType(), and valueBuffer().
m_setValueDepth
int lmms::AutomatableModel::m_setValueDepth private
Definition at line 395 of file AutomatableModel.h.
Referenced by AutomatableModel(), lmms::TypedAutomatableModel< T >::AutomatableModel(), setAutomatedValue(), and setValue().
m_step
float lmms::AutomatableModel::m_step private
Definition at line 387 of file AutomatableModel.h.
Referenced by AutomatableModel(), controllerValue(), fittedValue(), incValue(), roundAt(), setStep(), and step().
m_useControllerValue
bool lmms::AutomatableModel::m_useControllerValue private
Definition at line 417 of file AutomatableModel.h.
Referenced by AutomatableModel(), setUseControllerValue(), useControllerValue(), value(), and valueBuffer().
m_value
float lmms::AutomatableModel::m_value private
Definition at line 383 of file AutomatableModel.h.
Referenced by AutomatableModel(), controllerValue(), globalAutomationValueAt(), incValue(), isAtInitValue(), linkModels(), saveSettings(), setAutomatedValue(), setInitValue(), setValue(), value(), and valueBuffer().
m_valueBuffer
ValueBuffer lmms::AutomatableModel::m_valueBuffer private
Definition at line 408 of file AutomatableModel.h.
Referenced by AutomatableModel(), ~AutomatableModel(), and valueBuffer().
m_valueBufferMutex
QMutex lmms::AutomatableModel::m_valueBufferMutex private
Definition at line 415 of file AutomatableModel.h.
Referenced by valueBuffer().
m_valueChanged
bool lmms::AutomatableModel::m_valueChanged private
Definition at line 391 of file AutomatableModel.h.
Referenced by AutomatableModel(), isValueChanged(), setAutomatedValue(), setControllerConnection(), and setValue().
s_periodCounter
long lmms::AutomatableModel::s_periodCounter = 0 static private
Definition at line 410 of file AutomatableModel.h.
Referenced by incrementPeriodCounter(), resetPeriodCounter(), and valueBuffer().
The documentation for this class was generated from the following files:
include/AutomatableModel.h
src/core/AutomatableModel.cpp