LMMS: Jack::JackRestartThreadedDriver Class Reference
Jack::JackRestartThreadedDriver Class Reference
Restart a driver after an exception is thrown.
#include <JackRestartThreadedDriver.h>
Public Member Functions
JackRestartThreadedDriver (JackDriver *driver)
virtual ~JackRestartThreadedDriver ()
virtual bool Execute ()
Public Member Functions inherited from Jack::JackThreadedDriver
JackThreadedDriver (JackDriver *driver)
virtual ~JackThreadedDriver ()
virtual void AddSlave (JackDriverInterface *slave)
virtual int Attach ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual int Detach ()
virtual JackClientControl * GetClientControl () const
virtual bool GetMaster ()
virtual std::list< JackDriverInterface * > GetSlaves ()
virtual bool Init ()
Called once when the thread is started.
virtual bool IsFixedBufferSize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
virtual int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
virtual int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
virtual int Read ()
virtual void RemoveSlave (JackDriverInterface *slave)
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual void SetMaster (bool onoff)
virtual int SetSampleRate (jack_nframes_t sample_rate)
virtual int Start ()
virtual int Stop ()
virtual int Write ()
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Additional Inherited Members
Protected Member Functions inherited from Jack::JackThreadedDriver
void SetRealTime ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Protected Attributes inherited from Jack::JackThreadedDriver
JackDriver * fDriver
JackThread fThread
Detailed Description
Restart a driver after an exception is thrown.
Definition at line 33 of file JackRestartThreadedDriver.h.
Constructor & Destructor Documentation
JackRestartThreadedDriver()
Jack::JackRestartThreadedDriver::JackRestartThreadedDriver (JackDriver * driver) inline
Definition at line 37 of file JackRestartThreadedDriver.h.
References Jack::JackThreadedDriver::JackThreadedDriver(), and driver.
~JackRestartThreadedDriver()
virtual Jack::JackRestartThreadedDriver::~JackRestartThreadedDriver () inline virtual
Definition at line 40 of file JackRestartThreadedDriver.h.
Member Function Documentation
Execute()
bool Jack::JackRestartThreadedDriver::Execute () virtual
Reimplemented from Jack::JackThreadedDriver.
Definition at line 28 of file JackRestartThreadedDriver.cpp.
References Jack::JackThreadedDriver::fThread, Jack::JackThreadedDriver::Init(), jack_info(), Jack::detail::JackThreadInterface::kIniting, Jack::detail::JackThreadInterface::kRunning, Jack::JackException::PrintMessage(), and Jack::JackThreadedDriver::Process().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackRestartThreadedDriver.h
src/3rdparty/jack2/common/JackRestartThreadedDriver.cpp