LMMS: src/3rdparty/jack2/linux/firewire/JackFFADODriver.cpp File Reference
JackFFADODriver.cpp File Reference
#include <iostream>
#include <unistd.h>
#include <math.h>
#include <stdio.h>
#include <memory.h>
#include <stdlib.h>
#include <errno.h>
#include <stdarg.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/time.h>
#include <regex.h>
#include <string.h>
#include "JackFFADODriver.h"
#include "JackFFADOMidiInputPort.h"
#include "JackFFADOMidiOutputPort.h"
#include "JackEngineControl.h"
#include "JackClientControl.h"
#include "JackPort.h"
#include "JackGraphManager.h"
#include "JackCompilerDeps.h"
#include "JackLockedEngine.h"
Namespaces
namespace Jack
Macros
#define FIREWIRE_REQUIRED_FFADO_API_VERSION 8
#define FIREWIRE_REQUIRED_FFADO_API_VERSION_FOR_SETBUFSIZE 9
#define jack_get_microseconds
Typedefs
typedef void(* Jack::JackDriverFinishFunction) (jack_driver_t *)
Functions
SERVER_EXPORT const jack_driver_desc_t * driver_get_descriptor ()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine *engine, Jack::JackSynchro *table, const JSList *params)
int ffado_streaming_set_period_size (ffado_device_t *dev, unsigned int period) __attribute__((__weak__))
Macro Definition Documentation
FIREWIRE_REQUIRED_FFADO_API_VERSION
#define FIREWIRE_REQUIRED_FFADO_API_VERSION 8
Definition at line 61 of file JackFFADODriver.cpp.
Referenced by Jack::JackFFADODriver::ffado_driver_new().
FIREWIRE_REQUIRED_FFADO_API_VERSION_FOR_SETBUFSIZE
#define FIREWIRE_REQUIRED_FFADO_API_VERSION_FOR_SETBUFSIZE 9
Definition at line 62 of file JackFFADODriver.cpp.
Referenced by Jack::JackFFADODriver::SetBufferSize().
jack_get_microseconds
#define jack_get_microseconds (void)
Value:
GetMicroSeconds
Definition at line 64 of file JackFFADODriver.cpp.
Referenced by Jack::JackFFADODriver::ffado_driver_wait().
Function Documentation
driver_get_descriptor()
SERVER_EXPORT const jack_driver_desc_t * driver_get_descriptor ()
Definition at line 834 of file JackFFADODriver.cpp.
References jack_driver_param_value_t::i, jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverMaster, JackDriverParamBool, JackDriverParamString, JackDriverParamUInt, jack_driver_param_value_t::str, and jack_driver_param_value_t::ui.
driver_initialize()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine * engine, Jack::JackSynchro * table, const JSList * params)
Definition at line 886 of file JackFFADODriver.cpp.
References _ffado_jack_settings::buffer_size, _ffado_jack_settings::buffer_size_set, _ffado_jack_settings::capture_frame_latency, _ffado_jack_settings::capture_ports, jack_driver_param_t::character, _JSList::data, _ffado_jack_settings::device_info, jack_driver_param_value_t::i, jack_slist_next, Jack::JackFFADODriver::Open(), _ffado_jack_settings::period_size, _ffado_jack_settings::period_size_set, _ffado_jack_settings::playback_frame_latency, _ffado_jack_settings::playback_ports, _ffado_jack_settings::sample_rate, _ffado_jack_settings::sample_rate_set, SERVER_EXPORT, _ffado_jack_settings::slave_mode, _ffado_jack_settings::snoop_mode, jack_driver_param_value_t::str, jack_driver_param_value_t::ui, jack_driver_param_t::value, and _ffado_jack_settings::verbose_level.
ffado_streaming_set_period_size()
int ffado_streaming_set_period_size (ffado_device_t * dev, unsigned int period)
Referenced by Jack::JackFFADODriver::SetBufferSize().