LMMS: Jack::JackPosixThread Class Reference
Jack::JackPosixThread Class Reference
The POSIX thread base class.
#include <JackPosixThread.h>
Public Member Functions
JackPosixThread (JackRunnableInterface *runnable, bool real_time, int priority, int cancellation)
JackPosixThread (JackRunnableInterface *runnable, int cancellation=PTHREAD_CANCEL_ASYNCHRONOUS)
int AcquireRealTime ()
int AcquireRealTime (int priority)
int AcquireSelfRealTime ()
int AcquireSelfRealTime (int priority)
int DropRealTime ()
int DropSelfRealTime ()
jack_native_thread_t GetThreadID ()
bool IsThread ()
int Kill ()
int Start ()
int StartSync ()
int Stop ()
void Terminate ()
Public Member Functions inherited from Jack::detail::JackThreadInterface
JackThreadInterface (JackRunnableInterface *runnable, int priority, bool real_time, int cancellation)
int AcquireRealTime ()
int AcquireRealTime (int priority)
int AcquireSelfRealTime ()
int AcquireSelfRealTime (int priority)
int DropRealTime ()
int DropSelfRealTime ()
kThreadState GetStatus ()
jack_native_thread_t GetThreadID ()
bool IsThread ()
int Kill ()
void SetParams (UInt64 period, UInt64 computation, UInt64 constraint)
void SetStatus (kThreadState status)
int Start ()
int StartSync ()
int Stop ()
void Terminate ()
Static Public Member Functions
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority)
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint)
static int DropRealTimeImp (jack_native_thread_t thread)
static int KillImp (jack_native_thread_t thread)
static int StartImp (jack_native_thread_t *thread, int priority, int realtime, void *(*start_routine)(void *), void *arg)
static int StopImp (jack_native_thread_t thread)
Static Public Member Functions inherited from Jack::detail::JackThreadInterface
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority)
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint)
static int DropRealTimeImp (jack_native_thread_t thread)
static int KillImp (jack_native_thread_t thread)
static int StartImp (jack_native_thread_t *thread, int priority, int realtime, void *(*start_routine)(void *), void *arg)
static int StopImp (jack_native_thread_t thread)
Static Protected Member Functions
static void * ThreadHandler (void *arg)
Protected Attributes
jack_native_thread_t fThread
Protected Attributes inherited from Jack::detail::JackThreadInterface
int fCancellation
int fPriority
bool fRealTime
JackRunnableInterface * fRunnable
volatile kThreadState fStatus
Additional Inherited Members
Public Types inherited from Jack::detail::JackThreadInterface
enum kThreadState {
kIdle ,
kStarting ,
kIniting ,
kRunning
}
Detailed Description
The POSIX thread base class.
Definition at line 38 of file JackPosixThread.h.
Constructor & Destructor Documentation
JackPosixThread() [1/2]
Jack::JackPosixThread::JackPosixThread (JackRunnableInterface * runnable, bool real_time, int priority, int cancellation) inline
Definition at line 48 of file JackPosixThread.h.
References Jack::detail::JackThreadInterface::JackThreadInterface(), and fThread.
Referenced by Jack::JackMachThread::JackMachThread(), Jack::JackMachThread::JackMachThread(), and ThreadHandler().
JackPosixThread() [2/2]
Jack::JackPosixThread::JackPosixThread (JackRunnableInterface * runnable, int cancellation = PTHREAD_CANCEL_ASYNCHRONOUS) inline
Definition at line 51 of file JackPosixThread.h.
References Jack::detail::JackThreadInterface::JackThreadInterface(), fThread, and Jack::PTHREAD_CANCEL_ASYNCHRONOUS.
Member Function Documentation
AcquireRealTime() [1/2]
int Jack::JackPosixThread::AcquireRealTime ()
Definition at line 214 of file JackPosixThread.cpp.
References AcquireRealTimeImp(), Jack::detail::JackThreadInterface::fPriority, and fThread.
Referenced by AcquireRealTime().
AcquireRealTime() [2/2]
int Jack::JackPosixThread::AcquireRealTime (int priority)
Definition at line 224 of file JackPosixThread.cpp.
References AcquireRealTime(), and Jack::detail::JackThreadInterface::fPriority.
AcquireRealTimeImp() [1/2]
int Jack::JackPosixThread::AcquireRealTimeImp (jack_native_thread_t thread, int priority) static
Definition at line 235 of file JackPosixThread.cpp.
References jack_error, jack_log(), and JACK_SCHED_POLICY.
Referenced by AcquireRealTime(), AcquireRealTimeImp(), and AcquireSelfRealTime().
AcquireRealTimeImp() [2/2]
int Jack::JackPosixThread::AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint) inline static
Definition at line 74 of file JackPosixThread.h.
References AcquireRealTimeImp().
AcquireSelfRealTime() [1/2]
int Jack::JackPosixThread::AcquireSelfRealTime ()
Definition at line 219 of file JackPosixThread.cpp.
References AcquireRealTimeImp(), and Jack::detail::JackThreadInterface::fPriority.
Referenced by AcquireSelfRealTime().
AcquireSelfRealTime() [2/2]
int Jack::JackPosixThread::AcquireSelfRealTime (int priority)
Definition at line 230 of file JackPosixThread.cpp.
References AcquireSelfRealTime(), and Jack::detail::JackThreadInterface::fPriority.
DropRealTime()
int Jack::JackPosixThread::DropRealTime ()
Definition at line 259 of file JackPosixThread.cpp.
References DropRealTimeImp(), and fThread.
DropRealTimeImp()
int Jack::JackPosixThread::DropRealTimeImp (jack_native_thread_t thread) static
Definition at line 269 of file JackPosixThread.cpp.
References jack_error.
Referenced by DropRealTime(), and DropSelfRealTime().
DropSelfRealTime()
int Jack::JackPosixThread::DropSelfRealTime ()
Definition at line 264 of file JackPosixThread.cpp.
References DropRealTimeImp().
GetThreadID()
jack_native_thread_t Jack::JackPosixThread::GetThreadID ()
Definition at line 283 of file JackPosixThread.cpp.
References fThread.
IsThread()
bool Jack::JackPosixThread::IsThread ()
Definition at line 288 of file JackPosixThread.cpp.
References fThread.
Kill()
int Jack::JackPosixThread::Kill ()
Definition at line 160 of file JackPosixThread.cpp.
References Jack::detail::JackThreadInterface::fStatus, fThread, jack_log(), and Jack::detail::JackThreadInterface::kIdle.
Referenced by main().
KillImp()
int Jack::JackPosixThread::KillImp (jack_native_thread_t thread) static
Definition at line 189 of file JackPosixThread.cpp.
References jack_log().
Start()
int Jack::JackPosixThread::Start ()
Definition at line 71 of file JackPosixThread.cpp.
References Jack::detail::JackThreadInterface::fPriority, Jack::detail::JackThreadInterface::fRealTime, Jack::detail::JackThreadInterface::fStatus, fThread, Jack::detail::JackThreadInterface::kIdle, Jack::detail::JackThreadInterface::kStarting, StartImp(), and ThreadHandler().
StartImp()
int Jack::JackPosixThread::StartImp (jack_native_thread_t * thread, int priority, int realtime, void *(* start_routine)(void *), void * arg) static
Definition at line 100 of file JackPosixThread.cpp.
References Jack::JackGlobals::fJackThreadCreator, jack_error, jack_log(), JACK_SCHED_POLICY, and THREAD_STACK.
Referenced by Jack::JackAlsaDriver::create_thread(), Jack::JackAlsaDriver::Open(), Jack::JackPortAudioDriver::Open(), Start(), and StartSync().
StartSync()
int Jack::JackPosixThread::StartSync ()
Definition at line 84 of file JackPosixThread.cpp.
References Jack::detail::JackThreadInterface::fPriority, Jack::detail::JackThreadInterface::fRealTime, Jack::detail::JackThreadInterface::fStatus, fThread, JackSleep(), Jack::detail::JackThreadInterface::kIdle, Jack::detail::JackThreadInterface::kStarting, StartImp(), and ThreadHandler().
Stop()
int Jack::JackPosixThread::Stop ()
Definition at line 175 of file JackPosixThread.cpp.
References Jack::detail::JackThreadInterface::fStatus, fThread, jack_log(), and Jack::detail::JackThreadInterface::kIdle.
StopImp()
int Jack::JackPosixThread::StopImp (jack_native_thread_t thread) static
Definition at line 202 of file JackPosixThread.cpp.
References jack_log().
Referenced by Jack::JackAlsaDriver::Close(), and Jack::JackPortAudioDriver::Close().
Terminate()
void Jack::JackPosixThread::Terminate ()
Definition at line 293 of file JackPosixThread.cpp.
References jack_log().
ThreadHandler()
void * Jack::JackPosixThread::ThreadHandler (void * arg) static protected
Definition at line 38 of file JackPosixThread.cpp.
References JackPosixThread(), Jack::JackRunnableInterface::Execute(), Jack::detail::JackThreadInterface::fCancellation, Jack::detail::JackThreadInterface::fRunnable, Jack::detail::JackThreadInterface::fStatus, Jack::JackRunnableInterface::Init(), jack_error, jack_log(), Jack::detail::JackThreadInterface::kIniting, Jack::detail::JackThreadInterface::kRunning, and pthread_setcanceltype.
Referenced by Start(), and StartSync().
Member Data Documentation
fThread
jack_native_thread_t Jack::JackPosixThread::fThread protected
Definition at line 43 of file JackPosixThread.h.
Referenced by JackPosixThread(), JackPosixThread(), AcquireRealTime(), DropRealTime(), GetThreadID(), IsThread(), Kill(), Start(), StartSync(), and Stop().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/posix/JackPosixThread.h
src/3rdparty/jack2/posix/JackPosixThread.cpp