LMMS: lmms::gui::ExportProjectDialog Class Reference
lmms::gui::ExportProjectDialog Class Reference
#include <ExportProjectDialog.h>
Public Member Functions
ExportProjectDialog (const QString &_file_name, QWidget *_parent, bool multi_export)
Protected Member Functions
void closeEvent (QCloseEvent *_ce) override
void reject () override
Private Slots
void accept () override
void onFileFormatChanged (int)
void startBtnClicked ()
void startExport ()
void updateTitleBar (int)
Private Attributes
QString m_dirName
QString m_fileExtension
QString m_fileName
ProjectRenderer::ExportFileFormat m_ft
bool m_multiExport
std::unique_ptr< RenderManager > m_renderManager
Detailed Description
Definition at line 40 of file ExportProjectDialog.h.
Constructor & Destructor Documentation
ExportProjectDialog()
lmms::gui::ExportProjectDialog::ExportProjectDialog (const QString & _file_name, QWidget * _parent, bool multi_export = false)
Definition at line 37 of file ExportProjectDialog.cpp.
References ExportProjectDialog(), lmms::Engine::audioEngine(), lmms::ProjectRenderer::fileEncodeDevices, i, m_fileExtension, m_fileName, m_multiExport, m_renderManager, lmms::ProjectRenderer::NumFileFormats, startBtnClicked(), and lmms::SUPPORTED_SAMPLERATES.
Referenced by ExportProjectDialog().
Member Function Documentation
accept
void lmms::gui::ExportProjectDialog::accept () override private slot
Definition at line 126 of file ExportProjectDialog.cpp.
References lmms::gui::getGUI(), m_renderManager, lmms::gui::GuiApplication::mainWindow(), and lmms::gui::MainWindow::resetWindowTitle().
Referenced by startExport().
closeEvent()
void lmms::gui::ExportProjectDialog::closeEvent (QCloseEvent * _ce) override protected
Definition at line 137 of file ExportProjectDialog.cpp.
References lmms::Engine::getSong(), m_renderManager, and lmms::Song::setLoopRenderCount().
onFileFormatChanged
void lmms::gui::ExportProjectDialog::onFileFormatChanged (int index) private slot
Definition at line 211 of file ExportProjectDialog.cpp.
References lmms::ProjectRenderer::Flac, lmms::ProjectRenderer::MP3, lmms::ProjectRenderer::Ogg, and lmms::ProjectRenderer::Wave.
reject()
void lmms::gui::ExportProjectDialog::reject () override protected
Definition at line 114 of file ExportProjectDialog.cpp.
References m_renderManager.
Referenced by startBtnClicked().
startBtnClicked
void lmms::gui::ExportProjectDialog::startBtnClicked () private slot
Definition at line 247 of file ExportProjectDialog.cpp.
References lmms::ProjectRenderer::Count, lmms::ProjectRenderer::fileEncodeDevices, i, m_fileExtension, m_ft, lmms::ProjectRenderer::NumFileFormats, reject(), startExport(), and updateTitleBar().
Referenced by ExportProjectDialog().
startExport
void lmms::gui::ExportProjectDialog::startExport () private slot
Definition at line 163 of file ExportProjectDialog.cpp.
References accept(), lmms::gui::getGUI(), lmms::Engine::getSong(), m_fileExtension, m_fileName, m_ft, m_multiExport, m_renderManager, lmms::gui::mapToStereoMode(), lmms::OutputSettings::setCompressionLevel(), lmms::Song::setExportLoop(), lmms::Song::setLoopRenderCount(), lmms::Song::setRenderBetweenMarkers(), and updateTitleBar().
Referenced by startBtnClicked().
updateTitleBar
void lmms::gui::ExportProjectDialog::updateTitleBar (int _prog) private slot
Definition at line 289 of file ExportProjectDialog.cpp.
References lmms::gui::getGUI(), and lmms::gui::GuiApplication::mainWindow().
Referenced by startBtnClicked(), and startExport().
Member Data Documentation
m_dirName
QString lmms::gui::ExportProjectDialog::m_dirName private
Definition at line 61 of file ExportProjectDialog.h.
m_fileExtension
QString lmms::gui::ExportProjectDialog::m_fileExtension private
Definition at line 62 of file ExportProjectDialog.h.
Referenced by ExportProjectDialog(), startBtnClicked(), and startExport().
m_fileName
QString lmms::gui::ExportProjectDialog::m_fileName private
Definition at line 60 of file ExportProjectDialog.h.
Referenced by ExportProjectDialog(), and startExport().
m_ft
ProjectRenderer::ExportFileFormat lmms::gui::ExportProjectDialog::m_ft private
Definition at line 65 of file ExportProjectDialog.h.
Referenced by startBtnClicked(), and startExport().
m_multiExport
bool lmms::gui::ExportProjectDialog::m_multiExport private
Definition at line 63 of file ExportProjectDialog.h.
Referenced by ExportProjectDialog(), and startExport().
m_renderManager
std::unique_ptr<RenderManager> lmms::gui::ExportProjectDialog::m_renderManager private
Definition at line 66 of file ExportProjectDialog.h.
Referenced by ExportProjectDialog(), accept(), closeEvent(), reject(), and startExport().
The documentation for this class was generated from the following files:
include/ExportProjectDialog.h
src/gui/modals/ExportProjectDialog.cpp