LMMS: Jack::JackWaitThreadedDriver Class Reference
Jack::JackWaitThreadedDriver Class Reference
Wrapper for a restartable threaded driver (e.g.
#include <JackWaitThreadedDriver.h>
Classes
struct JackDriverStarter
Public Member Functions
JackWaitThreadedDriver (JackDriver *net_driver)
virtual ~JackWaitThreadedDriver ()
bool Execute ()
bool Init ()
Called once when the thread is started.
Public Member Functions inherited from Jack::JackThreadedDriver
JackThreadedDriver (JackDriver *driver)
virtual ~JackThreadedDriver ()
virtual void AddSlave (JackDriverInterface *slave)
virtual int Attach ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual int Detach ()
virtual JackClientControl * GetClientControl () const
virtual bool GetMaster ()
virtual std::list< JackDriverInterface * > GetSlaves ()
virtual bool IsFixedBufferSize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
virtual int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
virtual int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
virtual int Read ()
virtual void RemoveSlave (JackDriverInterface *slave)
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual void SetMaster (bool onoff)
virtual int SetSampleRate (jack_nframes_t sample_rate)
virtual int Start ()
virtual int Stop ()
virtual int Write ()
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Protected Member Functions
virtual bool ExecuteReal ()
Real work to be done when the decorated driver has finish initializing.
Protected Member Functions inherited from Jack::JackThreadedDriver
void SetRealTime ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Private Attributes
JackDriverStarter fStarter
Additional Inherited Members
Protected Attributes inherited from Jack::JackThreadedDriver
JackDriver * fDriver
JackThread fThread
Detailed Description
Wrapper for a restartable threaded driver (e.g.
JackNetDriver).
The idea is to behave as the "dummy" driver, until the network connection is really started and processing starts. The Execute method will call the ProcessNull method from the base JackWaiterDriver, until the decorated driver Initialize method returns. A helper JackDriverStarter thread is used for that purpose.
Definition at line 38 of file JackWaitThreadedDriver.h.
Constructor & Destructor Documentation
JackWaitThreadedDriver()
Jack::JackWaitThreadedDriver::JackWaitThreadedDriver (JackDriver * net_driver) inline
Definition at line 83 of file JackWaitThreadedDriver.h.
References Jack::JackThreadedDriver::JackThreadedDriver(), and fStarter.
Referenced by Jack::JackWaitCallbackDriver::JackWaitCallbackDriver().
~JackWaitThreadedDriver()
virtual Jack::JackWaitThreadedDriver::~JackWaitThreadedDriver () inline virtual
Definition at line 86 of file JackWaitThreadedDriver.h.
Member Function Documentation
Execute()
bool Jack::JackWaitThreadedDriver::Execute () virtual
Reimplemented from Jack::JackThreadedDriver.
Definition at line 38 of file JackWaitThreadedDriver.cpp.
References ExecuteReal(), Jack::JackThreadedDriver::fDriver, fStarter, Jack::JackThreadedDriver::fThread, Jack::detail::JackThreadInterface::kRunning, and Jack::JackThreadedDriver::SetRealTime().
ExecuteReal()
bool Jack::JackWaitThreadedDriver::ExecuteReal () protected virtual
Real work to be done when the decorated driver has finish initializing.
Reimplemented in Jack::JackWaitCallbackDriver.
Definition at line 52 of file JackWaitThreadedDriver.cpp.
References Jack::JackThreadedDriver::fDriver, Jack::JackThreadedDriver::fThread, Init(), jack_info(), Jack::detail::JackThreadInterface::kIdle, Jack::detail::JackThreadInterface::kIniting, Jack::detail::JackThreadInterface::kRunning, and Jack::JackException::PrintMessage().
Referenced by Execute().
Init()
bool Jack::JackWaitThreadedDriver::Init () virtual
Called once when the thread is started.
Reimplemented from Jack::JackThreadedDriver.
Definition at line 33 of file JackWaitThreadedDriver.cpp.
References fStarter.
Referenced by ExecuteReal().
Member Data Documentation
fStarter
JackDriverStarter Jack::JackWaitThreadedDriver::fStarter private
Definition at line 79 of file JackWaitThreadedDriver.h.
Referenced by JackWaitThreadedDriver(), Execute(), and Init().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackWaitThreadedDriver.h
src/3rdparty/jack2/common/JackWaitThreadedDriver.cpp