LMMS: Jack::JackShmReadWritePtr< T > Class Template Reference
Jack::JackShmReadWritePtr< T > Class Template Reference
Pointer on shared memory segment in the client side.
#include <JackShmMem.h>
Public Member Functions
JackShmReadWritePtr ()
JackShmReadWritePtr (int index, const char *server_name)
~JackShmReadWritePtr ()
T * GetShmAddress ()
int GetShmIndex ()
operator T* () const
T * operator-> () const
JackShmReadWritePtr & operator= (int index)
void SetShmIndex (int index, const char *server_name)
Private Member Functions
void Init (int index, const char *server_name=JACK_DEFAULT_SERVER_NAME)
Private Attributes
jack_shm_info_t fInfo
bool fInitDone
Detailed Description
template<class T>
class Jack::JackShmReadWritePtr< T >
Pointer on shared memory segment in the client side.
Definition at line 109 of file JackShmMem.h.
Constructor & Destructor Documentation
JackShmReadWritePtr() [1/2]
template<class T> Jack::JackShmReadWritePtr< T >::JackShmReadWritePtr () inline
Definition at line 135 of file JackShmMem.h.
References fInfo, and fInitDone.
Referenced by operator=().
JackShmReadWritePtr() [2/2]
template<class T> Jack::JackShmReadWritePtr< T >::JackShmReadWritePtr (int index, const char * server_name) inline
Definition at line 142 of file JackShmMem.h.
References Init(), and server_name.
~JackShmReadWritePtr()
template<class T> Jack::JackShmReadWritePtr< T >::~JackShmReadWritePtr () inline
Definition at line 147 of file JackShmMem.h.
References fInfo, fInitDone, GetShmAddress(), jack_error, jack_log(), and jack_release_lib_shm().
Member Function Documentation
GetShmAddress()
template<class T> T * Jack::JackShmReadWritePtr< T >::GetShmAddress () inline
Definition at line 187 of file JackShmMem.h.
References fInfo.
Referenced by ~JackShmReadWritePtr(), and Init().
GetShmIndex()
template<class T> int Jack::JackShmReadWritePtr< T >::GetShmIndex () inline
Definition at line 182 of file JackShmMem.h.
References fInfo.
Init()
template<class T> void Jack::JackShmReadWritePtr< T >::Init (int index, const char * server_name = JACK_DEFAULT_SERVER_NAME) inline private
Definition at line 117 of file JackShmMem.h.
References fInfo, fInitDone, GetShmAddress(), jack_attach_lib_shm(), JACK_DEFAULT_SERVER_NAME, jack_initialize_shm(), jack_log(), and server_name.
Referenced by JackShmReadWritePtr(), operator=(), and SetShmIndex().
operator T*()
template<class T> Jack::JackShmReadWritePtr< T >::operator T* () const inline
Definition at line 166 of file JackShmMem.h.
operator->()
template<class T> T * Jack::JackShmReadWritePtr< T >::operator-> () const inline
Definition at line 161 of file JackShmMem.h.
References fInfo.
operator=()
template<class T> JackShmReadWritePtr & Jack::JackShmReadWritePtr< T >::operator= (int index) inline
Definition at line 171 of file JackShmMem.h.
References JackShmReadWritePtr(), and Init().
SetShmIndex()
template<class T> void Jack::JackShmReadWritePtr< T >::SetShmIndex (int index, const char * server_name) inline
Definition at line 177 of file JackShmMem.h.
References Init(), and server_name.
Member Data Documentation
fInfo
template<class T> jack_shm_info_t Jack::JackShmReadWritePtr< T >::fInfo private
Definition at line 114 of file JackShmMem.h.
Referenced by JackShmReadWritePtr(), ~JackShmReadWritePtr(), GetShmAddress(), GetShmIndex(), Init(), and operator->().
fInitDone
template<class T> bool Jack::JackShmReadWritePtr< T >::fInitDone private
Definition at line 115 of file JackShmMem.h.
Referenced by JackShmReadWritePtr(), ~JackShmReadWritePtr(), and Init().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackShmMem.h