LMMS: lmms::InstrumentSoundShaping Class Reference
lmms::InstrumentSoundShaping Class Reference
#include <InstrumentSoundShaping.h>
Public Member Functions
InstrumentSoundShaping (InstrumentTrack *_instrument_track)
~InstrumentSoundShaping () override=default
f_cnt_t envFrames (const bool _only_vol=false) const
EnvelopeAndLfoParameters & getCutoffParameters ()
const EnvelopeAndLfoParameters & getCutoffParameters () const
FloatModel & getFilterCutModel ()
BoolModel & getFilterEnabledModel ()
ComboBoxModel & getFilterModel ()
FloatModel & getFilterResModel ()
EnvelopeAndLfoParameters & getResonanceParameters ()
const EnvelopeAndLfoParameters & getResonanceParameters () const
EnvelopeAndLfoParameters & getVolumeParameters ()
const EnvelopeAndLfoParameters & getVolumeParameters () const
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
void processAudioBuffer (SampleFrame *_ab, const fpp_t _frames, NotePlayHandle *_n)
f_cnt_t releaseFrames () const
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
float volumeLevel (NotePlayHandle *_n, const f_cnt_t _frame)
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Private Member Functions
QString getCutoffNodeName () const
QString getResonanceNodeName () const
QString getVolumeNodeName () const
Private Attributes
EnvelopeAndLfoParameters m_cutoffParameters
FloatModel m_filterCutModel
BoolModel m_filterEnabledModel
ComboBoxModel m_filterModel
FloatModel m_filterResModel
InstrumentTrack * m_instrumentTrack
EnvelopeAndLfoParameters m_resonanceParameters
EnvelopeAndLfoParameters m_volumeParameters
Additional Inherited Members
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 45 of file InstrumentSoundShaping.h.
Constructor & Destructor Documentation
InstrumentSoundShaping()
lmms::InstrumentSoundShaping::InstrumentSoundShaping (InstrumentTrack * _instrument_track)
Definition at line 45 of file InstrumentSoundShaping.cpp.
References lmms::Model::Model(), m_cutoffParameters, m_filterCutModel, m_filterEnabledModel, m_filterModel, m_filterResModel, m_instrumentTrack, m_resonanceParameters, and m_volumeParameters.
~InstrumentSoundShaping()
lmms::InstrumentSoundShaping::~InstrumentSoundShaping () override default
Member Function Documentation
envFrames()
f_cnt_t lmms::InstrumentSoundShaping::envFrames (const bool _only_vol = false) const
Definition at line 259 of file InstrumentSoundShaping.cpp.
References getCutoffParameters(), getResonanceParameters(), getVolumeParameters(), and lmms::EnvelopeAndLfoParameters::PAHD_Frames().
getCutoffNodeName()
QString lmms::InstrumentSoundShaping::getCutoffNodeName () const private
Definition at line 377 of file InstrumentSoundShaping.cpp.
References getCutoffParameters(), and lmms::EnvelopeAndLfoParameters::nodeName().
Referenced by loadSettings(), and saveSettings().
getCutoffParameters() [1/2]
EnvelopeAndLfoParameters & lmms::InstrumentSoundShaping::getCutoffParameters () inline
Definition at line 59 of file InstrumentSoundShaping.h.
References m_cutoffParameters.
getCutoffParameters() [2/2]
const EnvelopeAndLfoParameters & lmms::InstrumentSoundShaping::getCutoffParameters () const inline
Definition at line 58 of file InstrumentSoundShaping.h.
References m_cutoffParameters.
Referenced by envFrames(), getCutoffNodeName(), loadSettings(), processAudioBuffer(), releaseFrames(), and saveSettings().
getFilterCutModel()
FloatModel & lmms::InstrumentSoundShaping::getFilterCutModel () inline
Definition at line 66 of file InstrumentSoundShaping.h.
References m_filterCutModel.
getFilterEnabledModel()
BoolModel & lmms::InstrumentSoundShaping::getFilterEnabledModel () inline
Definition at line 64 of file InstrumentSoundShaping.h.
References m_filterEnabledModel.
getFilterModel()
ComboBoxModel & lmms::InstrumentSoundShaping::getFilterModel () inline
Definition at line 65 of file InstrumentSoundShaping.h.
References m_filterModel.
getFilterResModel()
FloatModel & lmms::InstrumentSoundShaping::getFilterResModel () inline
Definition at line 67 of file InstrumentSoundShaping.h.
References m_filterResModel.
getResonanceNodeName()
QString lmms::InstrumentSoundShaping::getResonanceNodeName () const private
Definition at line 382 of file InstrumentSoundShaping.cpp.
References getResonanceParameters(), and lmms::EnvelopeAndLfoParameters::nodeName().
Referenced by loadSettings(), and saveSettings().
getResonanceParameters() [1/2]
EnvelopeAndLfoParameters & lmms::InstrumentSoundShaping::getResonanceParameters () inline
Definition at line 62 of file InstrumentSoundShaping.h.
References m_resonanceParameters.
getResonanceParameters() [2/2]
const EnvelopeAndLfoParameters & lmms::InstrumentSoundShaping::getResonanceParameters () const inline
Definition at line 61 of file InstrumentSoundShaping.h.
References m_resonanceParameters.
Referenced by envFrames(), getResonanceNodeName(), loadSettings(), processAudioBuffer(), releaseFrames(), and saveSettings().
getVolumeNodeName()
QString lmms::InstrumentSoundShaping::getVolumeNodeName () const private
Definition at line 372 of file InstrumentSoundShaping.cpp.
References getVolumeParameters(), and lmms::EnvelopeAndLfoParameters::nodeName().
Referenced by loadSettings(), and saveSettings().
getVolumeParameters() [1/2]
EnvelopeAndLfoParameters & lmms::InstrumentSoundShaping::getVolumeParameters () inline
Definition at line 56 of file InstrumentSoundShaping.h.
References m_volumeParameters.
getVolumeParameters() [2/2]
const EnvelopeAndLfoParameters & lmms::InstrumentSoundShaping::getVolumeParameters () const inline
Definition at line 55 of file InstrumentSoundShaping.h.
References m_volumeParameters.
Referenced by envFrames(), getVolumeNodeName(), loadSettings(), processAudioBuffer(), releaseFrames(), saveSettings(), and volumeLevel().
loadSettings()
void lmms::InstrumentSoundShaping::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 341 of file InstrumentSoundShaping.cpp.
References getCutoffNodeName(), getCutoffParameters(), getResonanceNodeName(), getResonanceParameters(), getVolumeNodeName(), getVolumeParameters(), m_filterCutModel, m_filterEnabledModel, m_filterModel, m_filterResModel, nodeName(), and lmms::JournallingObject::restoreState().
nodeName()
QString lmms::InstrumentSoundShaping::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 77 of file InstrumentSoundShaping.h.
Referenced by loadSettings().
processAudioBuffer()
void lmms::InstrumentSoundShaping::processAudioBuffer (SampleFrame * _ab, const fpp_t _frames, NotePlayHandle * _n)
Definition at line 108 of file InstrumentSoundShaping.cpp.
References lmms::Engine::audioEngine(), lmms::CUT_FREQ_MULTIPLIER, lmms::EnvelopeAndLfoParameters::expKnobVal(), lmms::NotePlayHandle::framesBeforeRelease(), getCutoffParameters(), getResonanceParameters(), getVolumeParameters(), lmms::NotePlayHandle::instrumentTrack(), lmms::NotePlayHandle::isReleased(), lmms::NotePlayHandle::isReleaseStarted(), lmms::InstrumentTrack::isSustainPedalPressed(), lmms::NotePlayHandle::m_filter, m_filterCutModel, m_filterEnabledModel, m_filterModel, m_filterResModel, lmms::AudioEngine::outputSampleRate(), lmms::NotePlayHandle::releaseFramesDone(), lmms::RES_MULTIPLIER, lmms::RES_PRECISION, and lmms::NotePlayHandle::totalFramesPlayed().
releaseFrames()
f_cnt_t lmms::InstrumentSoundShaping::releaseFrames () const
Definition at line 284 of file InstrumentSoundShaping.cpp.
References getCutoffParameters(), getResonanceParameters(), getVolumeParameters(), and m_instrumentTrack.
saveSettings()
void lmms::InstrumentSoundShaping::saveSettings (QDomDocument & _doc, QDomElement & _parent) override virtual
Implements lmms::SerializingObject.
Definition at line 326 of file InstrumentSoundShaping.cpp.
References getCutoffNodeName(), getCutoffParameters(), getResonanceNodeName(), getResonanceParameters(), getVolumeNodeName(), getVolumeParameters(), m_filterCutModel, m_filterEnabledModel, m_filterModel, m_filterResModel, and lmms::saveEnvelopeAndLFOParameters().
volumeLevel()
float lmms::InstrumentSoundShaping::volumeLevel (NotePlayHandle * _n, const f_cnt_t _frame)
Definition at line 90 of file InstrumentSoundShaping.cpp.
References lmms::Engine::audioEngine(), lmms::EnvelopeAndLfoParameters::fillLevel(), lmms::NotePlayHandle::framesBeforeRelease(), lmms::AudioEngine::framesPerPeriod(), getVolumeParameters(), lmms::NotePlayHandle::isReleased(), and lmms::NotePlayHandle::releaseFramesDone().
Member Data Documentation
m_cutoffParameters
EnvelopeAndLfoParameters lmms::InstrumentSoundShaping::m_cutoffParameters private
Definition at line 91 of file InstrumentSoundShaping.h.
Referenced by InstrumentSoundShaping(), getCutoffParameters(), and getCutoffParameters().
m_filterCutModel
FloatModel lmms::InstrumentSoundShaping::m_filterCutModel private
Definition at line 96 of file InstrumentSoundShaping.h.
Referenced by InstrumentSoundShaping(), getFilterCutModel(), loadSettings(), processAudioBuffer(), and saveSettings().
m_filterEnabledModel
BoolModel lmms::InstrumentSoundShaping::m_filterEnabledModel private
Definition at line 94 of file InstrumentSoundShaping.h.
Referenced by InstrumentSoundShaping(), getFilterEnabledModel(), loadSettings(), processAudioBuffer(), and saveSettings().
m_filterModel
ComboBoxModel lmms::InstrumentSoundShaping::m_filterModel private
Definition at line 95 of file InstrumentSoundShaping.h.
Referenced by InstrumentSoundShaping(), getFilterModel(), loadSettings(), processAudioBuffer(), and saveSettings().
m_filterResModel
FloatModel lmms::InstrumentSoundShaping::m_filterResModel private
Definition at line 97 of file InstrumentSoundShaping.h.
Referenced by InstrumentSoundShaping(), getFilterResModel(), loadSettings(), processAudioBuffer(), and saveSettings().
m_instrumentTrack
InstrumentTrack* lmms::InstrumentSoundShaping::m_instrumentTrack private
Definition at line 88 of file InstrumentSoundShaping.h.
Referenced by InstrumentSoundShaping(), and releaseFrames().
m_resonanceParameters
EnvelopeAndLfoParameters lmms::InstrumentSoundShaping::m_resonanceParameters private
Definition at line 92 of file InstrumentSoundShaping.h.
Referenced by InstrumentSoundShaping(), getResonanceParameters(), and getResonanceParameters().
m_volumeParameters
EnvelopeAndLfoParameters lmms::InstrumentSoundShaping::m_volumeParameters private
Definition at line 90 of file InstrumentSoundShaping.h.
Referenced by InstrumentSoundShaping(), getVolumeParameters(), and getVolumeParameters().
The documentation for this class was generated from the following files:
include/InstrumentSoundShaping.h
src/core/InstrumentSoundShaping.cpp