LMMS: Jack::JackNetWinSocket Class Reference
Jack::JackNetWinSocket Class Reference
#include <JackNetWinSocket.h>
Public Member Functions
JackNetWinSocket ()
JackNetWinSocket (const char *ip, int port)
JackNetWinSocket (const JackNetWinSocket &)
~JackNetWinSocket ()
int Bind ()
int BindWith (const char *ip)
int BindWith (int port)
int CatchHost (void *buffer, size_t nbytes, int flags)
void Close ()
int Connect ()
int ConnectTo (const char *ip)
net_error_t GetError ()
int GetName (char *name)
int GetOption (int level, int optname, void *optval, SOCKLEN *optlen)
int GetPort ()
char * GetRecvIP ()
char * GetSendIP ()
bool IsLocal (char *ip)
bool IsSocket ()
int JoinMCastGroup (const char *mcast_ip)
int NewSocket ()
JackNetWinSocket & operator= (const JackNetWinSocket &)
int Recv (void *buffer, size_t nbytes, int flags)
int RecvFrom (void *buffer, size_t nbytes, int flags)
void Reset ()
int Send (const void *buffer, size_t nbytes, int flags)
int SendTo (const void *buffer, size_t nbytes, int flags)
int SendTo (const void *buffer, size_t nbytes, int flags, const char *ip)
int SetAddress (const char *ip, int port)
int SetLocalLoop ()
int SetOption (int level, int optname, const void *optval, SOCKLEN optlen)
void SetPort (int port)
int SetTimeOut (int usec)
Private Attributes
int fPort
SOCKADDR_IN fRecvAddr
SOCKADDR_IN fSendAddr
int fSockfd
Detailed Description
Definition at line 50 of file JackNetWinSocket.h.
Constructor & Destructor Documentation
JackNetWinSocket() [1/3]
Jack::JackNetWinSocket::JackNetWinSocket ()
Definition at line 102 of file JackNetWinSocket.cpp.
References fRecvAddr, fSendAddr, and fSockfd.
Referenced by JackNetWinSocket(), and operator=().
JackNetWinSocket() [2/3]
Jack::JackNetWinSocket::JackNetWinSocket (const char * ip, int port)
Definition at line 113 of file JackNetWinSocket.cpp.
References fPort, fRecvAddr, fSendAddr, and fSockfd.
JackNetWinSocket() [3/3]
Jack::JackNetWinSocket::JackNetWinSocket (const JackNetWinSocket & socket)
Definition at line 127 of file JackNetWinSocket.cpp.
References JackNetWinSocket(), fPort, fRecvAddr, fSendAddr, and fSockfd.
~JackNetWinSocket()
Jack::JackNetWinSocket::~JackNetWinSocket ()
Definition at line 135 of file JackNetWinSocket.cpp.
References Close().
Member Function Documentation
Bind()
int Jack::JackNetWinSocket::Bind ()
Definition at line 186 of file JackNetWinSocket.cpp.
References fRecvAddr, and fSockfd.
Referenced by BindWith(), and BindWith().
BindWith() [1/2]
int Jack::JackNetWinSocket::BindWith (const char * ip)
Definition at line 191 of file JackNetWinSocket.cpp.
References Bind(), and fRecvAddr.
BindWith() [2/2]
int Jack::JackNetWinSocket::BindWith (int port)
Definition at line 197 of file JackNetWinSocket.cpp.
References Bind(), and fRecvAddr.
CatchHost()
int Jack::JackNetWinSocket::CatchHost (void * buffer, size_t nbytes, int flags)
Definition at line 345 of file JackNetWinSocket.cpp.
References fSendAddr, and fSockfd.
Close()
void Jack::JackNetWinSocket::Close ()
Definition at line 214 of file JackNetWinSocket.cpp.
References fSockfd.
Referenced by ~JackNetWinSocket(), and NewSocket().
Connect()
int Jack::JackNetWinSocket::Connect ()
Definition at line 203 of file JackNetWinSocket.cpp.
References fSendAddr, and fSockfd.
Referenced by ConnectTo().
ConnectTo()
int Jack::JackNetWinSocket::ConnectTo (const char * ip)
Definition at line 208 of file JackNetWinSocket.cpp.
References Connect(), and fSendAddr.
GetError()
net_error_t Jack::JackNetWinSocket::GetError ()
Definition at line 351 of file JackNetWinSocket.cpp.
References Jack::NET_CONN_ERROR, NET_ERROR_CODE, Jack::NET_NO_DATA, Jack::NET_NO_ERROR, and Jack::NET_OP_ERROR.
GetName()
int Jack::JackNetWinSocket::GetName (char * name)
Definition at line 270 of file JackNetWinSocket.cpp.
GetOption()
int Jack::JackNetWinSocket::GetOption (int level, int optname, void * optval, SOCKLEN * optlen)
Definition at line 290 of file JackNetWinSocket.cpp.
References fSockfd.
GetPort()
int Jack::JackNetWinSocket::GetPort ()
Definition at line 246 of file JackNetWinSocket.cpp.
References fPort.
GetRecvIP()
char * Jack::JackNetWinSocket::GetRecvIP ()
Definition at line 264 of file JackNetWinSocket.cpp.
References fRecvAddr.
GetSendIP()
char * Jack::JackNetWinSocket::GetSendIP ()
Definition at line 259 of file JackNetWinSocket.cpp.
References fSendAddr.
IsLocal()
bool Jack::JackNetWinSocket::IsLocal (char * ip)
Definition at line 162 of file JackNetWinSocket.cpp.
References i.
IsSocket()
bool Jack::JackNetWinSocket::IsSocket ()
Definition at line 233 of file JackNetWinSocket.cpp.
References fSockfd.
JoinMCastGroup()
int Jack::JackNetWinSocket::JoinMCastGroup (const char * mcast_ip)
Definition at line 275 of file JackNetWinSocket.cpp.
References SetOption().
NewSocket()
int Jack::JackNetWinSocket::NewSocket ()
Definition at line 152 of file JackNetWinSocket.cpp.
References Close(), fSockfd, and Reset().
operator=()
JackNetWinSocket & Jack::JackNetWinSocket::operator= (const JackNetWinSocket & socket)
Definition at line 140 of file JackNetWinSocket.cpp.
References JackNetWinSocket(), fPort, fRecvAddr, fSendAddr, and fSockfd.
Recv()
int Jack::JackNetWinSocket::Recv (void * buffer, size_t nbytes, int flags)
Definition at line 340 of file JackNetWinSocket.cpp.
References fSockfd.
RecvFrom()
int Jack::JackNetWinSocket::RecvFrom (void * buffer, size_t nbytes, int flags)
Definition at line 334 of file JackNetWinSocket.cpp.
References fRecvAddr, and fSockfd.
Reset()
void Jack::JackNetWinSocket::Reset ()
Definition at line 221 of file JackNetWinSocket.cpp.
References fPort, fRecvAddr, and fSendAddr.
Referenced by NewSocket().
Send()
int Jack::JackNetWinSocket::Send (const void * buffer, size_t nbytes, int flags)
Definition at line 329 of file JackNetWinSocket.cpp.
References fSockfd.
SendTo() [1/2]
int Jack::JackNetWinSocket::SendTo (const void * buffer, size_t nbytes, int flags)
Definition at line 317 of file JackNetWinSocket.cpp.
References fSendAddr, and fSockfd.
Referenced by SendTo().
SendTo() [2/2]
int Jack::JackNetWinSocket::SendTo (const void * buffer, size_t nbytes, int flags, const char * ip)
Definition at line 322 of file JackNetWinSocket.cpp.
References fPort, fSendAddr, and SendTo().
SetAddress()
int Jack::JackNetWinSocket::SetAddress (const char * ip, int port)
Definition at line 252 of file JackNetWinSocket.cpp.
References fSendAddr.
SetLocalLoop()
int Jack::JackNetWinSocket::SetLocalLoop ()
Definition at line 304 of file JackNetWinSocket.cpp.
References SetOption().
SetOption()
int Jack::JackNetWinSocket::SetOption (int level, int optname, const void * optval, SOCKLEN optlen)
Definition at line 285 of file JackNetWinSocket.cpp.
References fSockfd.
Referenced by JoinMCastGroup(), SetLocalLoop(), and SetTimeOut().
SetPort()
void Jack::JackNetWinSocket::SetPort (int port)
Definition at line 239 of file JackNetWinSocket.cpp.
References fPort, fRecvAddr, and fSendAddr.
SetTimeOut()
int Jack::JackNetWinSocket::SetTimeOut (int usec)
Definition at line 296 of file JackNetWinSocket.cpp.
References jack_log(), and SetOption().
Member Data Documentation
fPort
int Jack::JackNetWinSocket::fPort private
Definition at line 54 of file JackNetWinSocket.h.
Referenced by JackNetWinSocket(), JackNetWinSocket(), GetPort(), operator=(), Reset(), SendTo(), and SetPort().
fRecvAddr
SOCKADDR_IN Jack::JackNetWinSocket::fRecvAddr private
Definition at line 56 of file JackNetWinSocket.h.
Referenced by JackNetWinSocket(), JackNetWinSocket(), JackNetWinSocket(), Bind(), BindWith(), BindWith(), GetRecvIP(), operator=(), RecvFrom(), Reset(), and SetPort().
fSendAddr
SOCKADDR_IN Jack::JackNetWinSocket::fSendAddr private
Definition at line 55 of file JackNetWinSocket.h.
Referenced by JackNetWinSocket(), JackNetWinSocket(), JackNetWinSocket(), CatchHost(), Connect(), ConnectTo(), GetSendIP(), operator=(), Reset(), SendTo(), SendTo(), SetAddress(), and SetPort().
fSockfd
int Jack::JackNetWinSocket::fSockfd private
Definition at line 53 of file JackNetWinSocket.h.
Referenced by JackNetWinSocket(), JackNetWinSocket(), JackNetWinSocket(), Bind(), CatchHost(), Close(), Connect(), GetOption(), IsSocket(), NewSocket(), operator=(), Recv(), RecvFrom(), Send(), SendTo(), and SetOption().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackNetWinSocket.h
src/3rdparty/jack2/windows/JackNetWinSocket.cpp