LMMS: lmms::gui::MicrotunerConfig Class Reference
lmms::gui::MicrotunerConfig Class Reference
#include <MicrotunerConfig.h>
Public Slots
void updateKeymapForm ()
Fill all the keymap-related values based on currently selected keymap.
void updateKeymapList (int index)
Update list of available keymaps.
void updateScaleForm ()
Fill all the scale-related values based on currently selected scale.
void updateScaleList (int index)
Update list of available scales.
Public Member Functions
MicrotunerConfig ()
void loadSettings (const QDomElement &element) override
QString nodeName () const override
void saveSettings (QDomDocument &document, QDomElement &element) override
QSize sizeHint () const override
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual void restoreState (const QDomElement &_this)
virtual QDomElement saveState (QDomDocument &_doc, QDomElement &_parent)
void setHook (SerializingObjectHook *_hook)
Protected Member Functions
void closeEvent (QCloseEvent *ce) override
Private Slots
bool loadKeymapFromFile ()
Parse a .kbm file and apply the loaded keymap if it is valid.
bool loadScaleFromFile ()
Parse an .scl file and apply the loaded scale if it is valid.
bool saveKeymapToFile ()
Save currently entered keymap definition as .kbm file.
bool saveScaleToFile ()
Save currently entered scale definition as .scl file.
Private Member Functions
bool applyKeymap ()
Parse and apply the entered keymap definition.
bool applyScale ()
Parse and apply the entered scale definition.
bool validateKeymapForm ()
Validate the entered key mapping and other values.
bool validateScaleForm ()
Validate the scale name and entered interval definitions.
Private Attributes
FloatModel m_baseFreqModel
model for spinbox of currently edited base note frequency
IntModel m_baseKeyModel
model for spinbox of currently edited base key
IntModel m_firstKeyModel
model for spinbox of currently edited first key
ComboBoxModel m_keymapComboModel
ID of keymap currently selected for editing.
QLineEdit * m_keymapNameEdit
edit field for the keymap name or description
QPlainTextEdit * m_keymapTextEdit
text editor field for key mappings
IntModel m_lastKeyModel
model for spinbox of currently edited last key
IntModel m_middleKeyModel
model for spinbox of currently edited middle key
ComboBoxModel m_scaleComboModel
ID of scale currently selected for editing.
QLineEdit * m_scaleNameEdit
edit field for the scale name or description
QPlainTextEdit * m_scaleTextEdit
text editor field for interval definitions
Detailed Description
Definition at line 41 of file MicrotunerConfig.h.
Constructor & Destructor Documentation
MicrotunerConfig()
lmms::gui::MicrotunerConfig::MicrotunerConfig ()
Definition at line 57 of file MicrotunerConfig.cpp.
References lmms::gui::MainWindow::addWindowedWidget(), applyKeymap(), applyScale(), lmms::Model::dataChanged(), lmms::DefaultBaseFreq, lmms::DefaultBaseKey, lmms::DefaultMiddleKey, lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::Engine::getSong(), i, loadKeymapFromFile(), loadScaleFromFile(), m_baseFreqModel, m_baseKeyModel, m_firstKeyModel, m_keymapComboModel, m_keymapNameEdit, m_keymapTextEdit, m_lastKeyModel, m_middleKeyModel, m_scaleComboModel, m_scaleNameEdit, m_scaleTextEdit, lmms::gui::GuiApplication::mainWindow(), lmms::MaxKeymapCount, lmms::MaxScaleCount, lmms::NumKeys, saveKeymapToFile(), saveScaleToFile(), updateKeymapForm(), updateKeymapList(), updateScaleForm(), and updateScaleList().
Member Function Documentation
applyKeymap()
bool lmms::gui::MicrotunerConfig::applyKeymap () private
Parse and apply the entered keymap definition.
Returns
true if input is valid, false if problems were detected
Definition at line 458 of file MicrotunerConfig.cpp.
References lmms::Engine::getSong(), m_baseFreqModel, m_baseKeyModel, m_firstKeyModel, m_keymapComboModel, m_keymapNameEdit, m_keymapTextEdit, m_lastKeyModel, m_middleKeyModel, lmms::Song::setKeymap(), and validateKeymapForm().
Referenced by MicrotunerConfig(), loadKeymapFromFile(), and saveKeymapToFile().
applyScale()
bool lmms::gui::MicrotunerConfig::applyScale () private
Parse and apply the entered scale definition.
Returns
true if input is valid, false if problems were detected
Definition at line 411 of file MicrotunerConfig.cpp.
References lmms::Engine::getSong(), m_scaleComboModel, m_scaleNameEdit, m_scaleTextEdit, lmms::Song::setScale(), and validateScaleForm().
Referenced by MicrotunerConfig(), loadScaleFromFile(), and saveScaleToFile().
closeEvent()
void lmms::gui::MicrotunerConfig::closeEvent (QCloseEvent * ce) override protected
Definition at line 683 of file MicrotunerConfig.cpp.
loadKeymapFromFile
bool lmms::gui::MicrotunerConfig::loadKeymapFromFile () private slot
Parse a .kbm file and apply the loaded keymap if it is valid.
Returns
true if input is valid, false if problems were detected
Definition at line 542 of file MicrotunerConfig.cpp.
References applyKeymap(), baseName(), file, lmms::gui::FileDialog::getOpenFileName(), i, m_baseFreqModel, m_baseKeyModel, m_firstKeyModel, m_keymapNameEdit, m_keymapTextEdit, m_lastKeyModel, and m_middleKeyModel.
Referenced by MicrotunerConfig().
loadScaleFromFile
bool lmms::gui::MicrotunerConfig::loadScaleFromFile () private slot
Parse an .scl file and apply the loaded scale if it is valid.
Returns
true if input is valid, false if problems were detected
Definition at line 507 of file MicrotunerConfig.cpp.
References applyScale(), file, lmms::gui::FileDialog::getOpenFileName(), i, m_scaleNameEdit, and m_scaleTextEdit.
Referenced by MicrotunerConfig().
loadSettings()
void lmms::gui::MicrotunerConfig::loadSettings (const QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 677 of file MicrotunerConfig.cpp.
References lmms::gui::MainWindow::restoreWidgetState().
nodeName()
QString lmms::gui::MicrotunerConfig::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 50 of file MicrotunerConfig.h.
saveKeymapToFile
bool lmms::gui::MicrotunerConfig::saveKeymapToFile () private slot
Save currently entered keymap definition as .kbm file.
Returns
true if input is valid, false if problems were detected
Definition at line 626 of file MicrotunerConfig.cpp.
References applyKeymap(), file, lmms::Song::getKeymap(), lmms::Engine::getSong(), m_baseFreqModel, m_baseKeyModel, m_firstKeyModel, m_keymapComboModel, m_keymapNameEdit, m_keymapTextEdit, m_lastKeyModel, and m_middleKeyModel.
Referenced by MicrotunerConfig().
saveScaleToFile
bool lmms::gui::MicrotunerConfig::saveScaleToFile () private slot
Save currently entered scale definition as .scl file.
Returns
true if input is valid, false if problems were detected
Definition at line 590 of file MicrotunerConfig.cpp.
References applyScale(), file, lmms::Song::getScale(), lmms::Engine::getSong(), m_scaleComboModel, m_scaleNameEdit, and m_scaleTextEdit.
Referenced by MicrotunerConfig().
saveSettings()
void lmms::gui::MicrotunerConfig::saveSettings (QDomDocument & document, QDomElement & element) override virtual
Implements lmms::SerializingObject.
Definition at line 671 of file MicrotunerConfig.cpp.
References lmms::gui::MainWindow::saveWidgetState().
sizeHint()
QSize lmms::gui::MicrotunerConfig::sizeHint () const inline override
Definition at line 54 of file MicrotunerConfig.h.
updateKeymapForm
void lmms::gui::MicrotunerConfig::updateKeymapForm () slot
Fill all the keymap-related values based on currently selected keymap.
Definition at line 294 of file MicrotunerConfig.cpp.
References lmms::Song::getKeymap(), lmms::Engine::getSong(), m_baseFreqModel, m_baseKeyModel, m_firstKeyModel, m_keymapComboModel, m_keymapNameEdit, m_keymapTextEdit, m_lastKeyModel, and m_middleKeyModel.
Referenced by MicrotunerConfig().
updateKeymapList
void lmms::gui::MicrotunerConfig::updateKeymapList (int index) slot
Update list of available keymaps.
Parameters
index Index of the keymap to update; update all keymaps if -1 or out of range.
Definition at line 247 of file MicrotunerConfig.cpp.
References lmms::Engine::getSong(), i, m_keymapComboModel, and lmms::MaxKeymapCount.
Referenced by MicrotunerConfig().
updateScaleForm
void lmms::gui::MicrotunerConfig::updateScaleForm () slot
Fill all the scale-related values based on currently selected scale.
Definition at line 268 of file MicrotunerConfig.cpp.
References lmms::Song::getScale(), lmms::Engine::getSong(), i, m_scaleComboModel, m_scaleNameEdit, and m_scaleTextEdit.
Referenced by MicrotunerConfig().
updateScaleList
void lmms::gui::MicrotunerConfig::updateScaleList (int index) slot
Update list of available scales.
Parameters
index Index of the scale to update; update all scales if -1 or out of range.
Definition at line 225 of file MicrotunerConfig.cpp.
References lmms::Engine::getSong(), i, m_scaleComboModel, and lmms::MaxScaleCount.
Referenced by MicrotunerConfig().
validateKeymapForm()
bool lmms::gui::MicrotunerConfig::validateKeymapForm () private
Validate the entered key mapping and other values.
Returns
true if input is valid, false if problems were detected
Definition at line 374 of file MicrotunerConfig.cpp.
References m_keymapNameEdit, and m_keymapTextEdit.
Referenced by applyKeymap().
validateScaleForm()
bool lmms::gui::MicrotunerConfig::validateScaleForm () private
Validate the scale name and entered interval definitions.
Returns
true if input is valid, false if problems were detected
Definition at line 326 of file MicrotunerConfig.cpp.
References m_scaleNameEdit, and m_scaleTextEdit.
Referenced by applyScale().
Member Data Documentation
m_baseFreqModel
FloatModel lmms::gui::MicrotunerConfig::m_baseFreqModel private
model for spinbox of currently edited base note frequency
Definition at line 92 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyKeymap(), loadKeymapFromFile(), saveKeymapToFile(), and updateKeymapForm().
m_baseKeyModel
IntModel lmms::gui::MicrotunerConfig::m_baseKeyModel private
model for spinbox of currently edited base key
Definition at line 91 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyKeymap(), loadKeymapFromFile(), saveKeymapToFile(), and updateKeymapForm().
m_firstKeyModel
IntModel lmms::gui::MicrotunerConfig::m_firstKeyModel private
model for spinbox of currently edited first key
Definition at line 87 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyKeymap(), loadKeymapFromFile(), saveKeymapToFile(), and updateKeymapForm().
m_keymapComboModel
ComboBoxModel lmms::gui::MicrotunerConfig::m_keymapComboModel private
ID of keymap currently selected for editing.
Definition at line 79 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyKeymap(), saveKeymapToFile(), updateKeymapForm(), and updateKeymapList().
m_keymapNameEdit
QLineEdit* lmms::gui::MicrotunerConfig::m_keymapNameEdit private
edit field for the keymap name or description
Definition at line 82 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyKeymap(), loadKeymapFromFile(), saveKeymapToFile(), updateKeymapForm(), and validateKeymapForm().
m_keymapTextEdit
QPlainTextEdit* lmms::gui::MicrotunerConfig::m_keymapTextEdit private
text editor field for key mappings
Definition at line 85 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyKeymap(), loadKeymapFromFile(), saveKeymapToFile(), updateKeymapForm(), and validateKeymapForm().
m_lastKeyModel
IntModel lmms::gui::MicrotunerConfig::m_lastKeyModel private
model for spinbox of currently edited last key
Definition at line 88 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyKeymap(), loadKeymapFromFile(), saveKeymapToFile(), and updateKeymapForm().
m_middleKeyModel
IntModel lmms::gui::MicrotunerConfig::m_middleKeyModel private
model for spinbox of currently edited middle key
Definition at line 89 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyKeymap(), loadKeymapFromFile(), saveKeymapToFile(), and updateKeymapForm().
m_scaleComboModel
ComboBoxModel lmms::gui::MicrotunerConfig::m_scaleComboModel private
ID of scale currently selected for editing.
Definition at line 78 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyScale(), saveScaleToFile(), updateScaleForm(), and updateScaleList().
m_scaleNameEdit
QLineEdit* lmms::gui::MicrotunerConfig::m_scaleNameEdit private
edit field for the scale name or description
Definition at line 81 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyScale(), loadScaleFromFile(), saveScaleToFile(), updateScaleForm(), and validateScaleForm().
m_scaleTextEdit
QPlainTextEdit* lmms::gui::MicrotunerConfig::m_scaleTextEdit private
text editor field for interval definitions
Definition at line 84 of file MicrotunerConfig.h.
Referenced by MicrotunerConfig(), applyScale(), loadScaleFromFile(), saveScaleToFile(), updateScaleForm(), and validateScaleForm().
The documentation for this class was generated from the following files:
include/MicrotunerConfig.h
src/gui/MicrotunerConfig.cpp