LMMS: lmms::gui::LeftRightNav Class Reference
lmms::gui::LeftRightNav Class Reference
#include <LeftRightNav.h>
Signals
void onNavLeft ()
void onNavRight ()
Public Member Functions
LeftRightNav (QWidget *parent=nullptr)
PixmapButton * getLeftBtn ()
PixmapButton * getRightBtn ()
void setShortcuts (const QKeySequence &leftShortcut=Qt::Key_Minus, const QKeySequence &rightShortcut=Qt::Key_Plus)
Private Attributes
QHBoxLayout m_layout
PixmapButton m_leftBtn
PixmapButton m_rightBtn
Detailed Description
Definition at line 34 of file LeftRightNav.h.
Constructor & Destructor Documentation
LeftRightNav()
lmms::gui::LeftRightNav::LeftRightNav (QWidget * parent = nullptr)
Definition at line 35 of file LeftRightNav.cpp.
References lmms::embed::getIconPixmap(), m_layout, m_leftBtn, m_rightBtn, onNavLeft(), and onNavRight().
Member Function Documentation
getLeftBtn()
PixmapButton * lmms::gui::LeftRightNav::getLeftBtn ()
Definition at line 79 of file LeftRightNav.cpp.
References m_leftBtn.
getRightBtn()
PixmapButton * lmms::gui::LeftRightNav::getRightBtn ()
Definition at line 83 of file LeftRightNav.cpp.
References m_rightBtn.
onNavLeft
void lmms::gui::LeftRightNav::onNavLeft () signal
Referenced by LeftRightNav().
onNavRight
void lmms::gui::LeftRightNav::onNavRight () signal
Referenced by LeftRightNav().
setShortcuts()
void lmms::gui::LeftRightNav::setShortcuts (const QKeySequence & leftShortcut = Qt::Key_Minus, const QKeySequence & rightShortcut = Qt::Key_Plus)
Definition at line 88 of file LeftRightNav.cpp.
References m_leftBtn, and m_rightBtn.
Member Data Documentation
m_layout
QHBoxLayout lmms::gui::LeftRightNav::m_layout private
Definition at line 46 of file LeftRightNav.h.
Referenced by LeftRightNav().
m_leftBtn
PixmapButton lmms::gui::LeftRightNav::m_leftBtn private
Definition at line 47 of file LeftRightNav.h.
Referenced by LeftRightNav(), getLeftBtn(), and setShortcuts().
m_rightBtn
PixmapButton lmms::gui::LeftRightNav::m_rightBtn private
Definition at line 48 of file LeftRightNav.h.
Referenced by LeftRightNav(), getRightBtn(), and setShortcuts().
The documentation for this class was generated from the following files:
include/LeftRightNav.h
src/gui/widgets/LeftRightNav.cpp