LMMS: Jack::NetMidiBuffer Class Reference
Jack::NetMidiBuffer Class Reference
\Brief Midi buffer and operations class
#include <JackNetTool.h>
Public Member Functions
NetMidiBuffer (session_params_t *params, uint32_t nports, char *net_buffer)
~NetMidiBuffer ()
void DisplayEvents ()
JackMidiBuffer * GetBuffer (int index)
size_t GetCycleSize ()
int GetNumPackets (int data_sizen, int max_size)
int RenderFromJackPorts ()
void RenderFromNetwork (int sub_cycle, size_t copy_size)
void RenderToJackPorts ()
int RenderToNetwork (int sub_cycle, size_t total_size)
void Reset ()
void SetBuffer (int index, JackMidiBuffer *buffer)
Private Attributes
char * fBuffer
size_t fCycleBytesSize
size_t fMaxBufsize
int fMaxPcktSize
char * fNetBuffer
int fNPorts
JackMidiBuffer ** fPortBuffer
Detailed Description
\Brief Midi buffer and operations class
This class is a toolset to manipulate Midi buffers. A JackMidiBuffer has a fixed size, which is the same than an audio buffer size. An intermediate fixed size buffer allows to uninterleave midi data (from jack ports). But for a big majority of the process cycles, this buffer is filled less than 1%, Sending over a network 99% of useless data seems completely unappropriate. The idea is to count effective midi data, and then send the smallest packet we can. To do it, we use an intermediate buffer. We have two methods to convert data from jack ports to intermediate buffer, And two others to convert this intermediate buffer to a network buffer (header + payload data)
Definition at line 238 of file JackNetTool.h.
Constructor & Destructor Documentation
NetMidiBuffer()
Jack::NetMidiBuffer::NetMidiBuffer (session_params_t * params, uint32_t nports, char * net_buffer)
Definition at line 94 of file JackNetTool.cpp.
References fBuffer, fCycleBytesSize, fMaxBufsize, fMaxPcktSize, Jack::_session_params::fMtu, fNetBuffer, fNPorts, Jack::_session_params::fPeriodSize, fPortBuffer, Jack::_session_params::fReturnMidiChannels, Jack::_session_params::fSendMidiChannels, and max.
~NetMidiBuffer()
Jack::NetMidiBuffer::~NetMidiBuffer ()
Definition at line 110 of file JackNetTool.cpp.
References fBuffer, and fPortBuffer.
Member Function Documentation
DisplayEvents()
void Jack::NetMidiBuffer::DisplayEvents ()
Definition at line 138 of file JackNetTool.cpp.
References fNPorts, fPortBuffer, and jack_info().
Referenced by Reset().
GetBuffer()
JackMidiBuffer * Jack::NetMidiBuffer::GetBuffer (int index)
Definition at line 133 of file JackNetTool.cpp.
References fPortBuffer.
Referenced by Reset().
GetCycleSize()
size_t Jack::NetMidiBuffer::GetCycleSize ()
Definition at line 116 of file JackNetTool.cpp.
References fCycleBytesSize.
Referenced by Reset().
GetNumPackets()
int Jack::NetMidiBuffer::GetNumPackets (int data_sizen, int max_size)
Definition at line 121 of file JackNetTool.cpp.
Referenced by Jack::JackNetInterface::MidiSend(), and Reset().
RenderFromJackPorts()
int Jack::NetMidiBuffer::RenderFromJackPorts ()
Definition at line 151 of file JackNetTool.cpp.
References fBuffer, fNPorts, fPortBuffer, Jack::MidiBufferHToN(), and pos.
Referenced by Jack::JackNetInterface::MidiSend(), and Reset().
RenderFromNetwork()
void Jack::NetMidiBuffer::RenderFromNetwork (int sub_cycle, size_t copy_size)
Definition at line 189 of file JackNetTool.cpp.
References fBuffer, fMaxPcktSize, and fNetBuffer.
Referenced by Jack::JackNetInterface::MidiRecv(), and Reset().
RenderToJackPorts()
void Jack::NetMidiBuffer::RenderToJackPorts ()
Definition at line 171 of file JackNetTool.cpp.
References Jack::JackMidiBuffer::event_count, fBuffer, fNPorts, fPortBuffer, Jack::MidiBufferNToH(), and pos.
Referenced by Jack::JackNetInterface::MidiRecv(), and Reset().
RenderToNetwork()
int Jack::NetMidiBuffer::RenderToNetwork (int sub_cycle, size_t total_size)
Definition at line 194 of file JackNetTool.cpp.
References fBuffer, fMaxPcktSize, and fNetBuffer.
Referenced by Jack::JackNetInterface::MidiSend(), and Reset().
Reset()
void Jack::NetMidiBuffer::Reset ()
References DisplayEvents(), GetBuffer(), GetCycleSize(), GetNumPackets(), RenderFromJackPorts(), RenderFromNetwork(), RenderToJackPorts(), RenderToNetwork(), and SetBuffer().
SetBuffer()
void Jack::NetMidiBuffer::SetBuffer (int index, JackMidiBuffer * buffer)
Definition at line 128 of file JackNetTool.cpp.
References fPortBuffer.
Referenced by Reset().
Member Data Documentation
fBuffer
char* Jack::NetMidiBuffer::fBuffer private
Definition at line 246 of file JackNetTool.h.
Referenced by NetMidiBuffer(), ~NetMidiBuffer(), RenderFromJackPorts(), RenderFromNetwork(), RenderToJackPorts(), and RenderToNetwork().
fCycleBytesSize
size_t Jack::NetMidiBuffer::fCycleBytesSize private
Definition at line 250 of file JackNetTool.h.
Referenced by NetMidiBuffer(), and GetCycleSize().
fMaxBufsize
size_t Jack::NetMidiBuffer::fMaxBufsize private
Definition at line 243 of file JackNetTool.h.
Referenced by NetMidiBuffer().
fMaxPcktSize
int Jack::NetMidiBuffer::fMaxPcktSize private
Definition at line 244 of file JackNetTool.h.
Referenced by NetMidiBuffer(), RenderFromNetwork(), and RenderToNetwork().
fNetBuffer
char* Jack::NetMidiBuffer::fNetBuffer private
Definition at line 247 of file JackNetTool.h.
Referenced by NetMidiBuffer(), RenderFromNetwork(), and RenderToNetwork().
fNPorts
int Jack::NetMidiBuffer::fNPorts private
Definition at line 242 of file JackNetTool.h.
Referenced by NetMidiBuffer(), DisplayEvents(), RenderFromJackPorts(), and RenderToJackPorts().
fPortBuffer
JackMidiBuffer** Jack::NetMidiBuffer::fPortBuffer private
Definition at line 248 of file JackNetTool.h.
Referenced by NetMidiBuffer(), ~NetMidiBuffer(), DisplayEvents(), GetBuffer(), RenderFromJackPorts(), RenderToJackPorts(), and SetBuffer().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackNetTool.h
src/3rdparty/jack2/common/JackNetTool.cpp