LMMS: lmms::gui::EnvelopeGraph Class Reference
lmms::gui::EnvelopeGraph Class Reference
#include <EnvelopeGraph.h>
Public Types
enum class ScalingMode {
Dynamic ,
Absolute ,
Relative
}
Public Member Functions
EnvelopeGraph (QWidget *parent)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *) override
void modelChanged () override
void mousePressEvent (QMouseEvent *) override
void paintEvent (QPaintEvent *) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Properties
QColor fullAmountColor
QColor markerFillColor
QColor markerOutlineColor
QColor noAmountColor
Private Member Functions
void toggleAmountModel ()
Private Attributes
QPixmap m_envGraph = embed::getIconPixmap("envelope_graph")
QColor m_fullAmountColor
QColor m_markerFillColor
QColor m_markerOutlineColor
QColor m_noAmountColor
EnvelopeAndLfoParameters * m_params = nullptr
ScalingMode m_scaling = ScalingMode::Dynamic
Detailed Description
Definition at line 42 of file EnvelopeGraph.h.
Member Enumeration Documentation
ScalingMode
enum class lmms::gui::EnvelopeGraph::ScalingMode strong
Enumerator
Dynamic
Absolute
Relative
Definition at line 51 of file EnvelopeGraph.h.
Constructor & Destructor Documentation
EnvelopeGraph()
lmms::gui::EnvelopeGraph::EnvelopeGraph (QWidget * parent)
Definition at line 44 of file EnvelopeGraph.cpp.
References lmms::gui::ModelView::ModelView(), m_envGraph, m_fullAmountColor, m_markerFillColor, m_markerOutlineColor, and m_noAmountColor.
Member Function Documentation
contextMenuEvent()
void lmms::gui::EnvelopeGraph::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 65 of file EnvelopeGraph.cpp.
References Absolute, Dynamic, m_scaling, and Relative.
modelChanged()
void lmms::gui::EnvelopeGraph::modelChanged () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 55 of file EnvelopeGraph.cpp.
References lmms::gui::ModelView::castModel(), and m_params.
mousePressEvent()
void lmms::gui::EnvelopeGraph::mousePressEvent (QMouseEvent * me) override protected
Definition at line 60 of file EnvelopeGraph.cpp.
References toggleAmountModel().
paintEvent()
void lmms::gui::EnvelopeGraph::paintEvent (QPaintEvent *) override protected
Definition at line 104 of file EnvelopeGraph.cpp.
References Absolute, lmms::gui::ModelView::castModel(), Dynamic, lmms::gui::ColorHelper::interpolateInRgb(), m_envGraph, m_fullAmountColor, m_markerFillColor, m_markerOutlineColor, m_noAmountColor, m_scaling, and Relative.
toggleAmountModel()
void lmms::gui::EnvelopeGraph::toggleAmountModel () private
Definition at line 249 of file EnvelopeGraph.cpp.
References lmms::gui::ModelView::castModel().
Referenced by mousePressEvent().
Member Data Documentation
m_envGraph
QPixmap lmms::gui::EnvelopeGraph::m_envGraph = embed::getIconPixmap("envelope_graph") private
Definition at line 72 of file EnvelopeGraph.h.
Referenced by EnvelopeGraph(), and paintEvent().
m_fullAmountColor
QColor lmms::gui::EnvelopeGraph::m_fullAmountColor private
Definition at line 79 of file EnvelopeGraph.h.
Referenced by EnvelopeGraph(), and paintEvent().
m_markerFillColor
QColor lmms::gui::EnvelopeGraph::m_markerFillColor private
Definition at line 80 of file EnvelopeGraph.h.
Referenced by EnvelopeGraph(), and paintEvent().
m_markerOutlineColor
QColor lmms::gui::EnvelopeGraph::m_markerOutlineColor private
Definition at line 81 of file EnvelopeGraph.h.
Referenced by EnvelopeGraph(), and paintEvent().
m_noAmountColor
QColor lmms::gui::EnvelopeGraph::m_noAmountColor private
Definition at line 78 of file EnvelopeGraph.h.
Referenced by EnvelopeGraph(), and paintEvent().
m_params
EnvelopeAndLfoParameters* lmms::gui::EnvelopeGraph::m_params = nullptr private
Definition at line 74 of file EnvelopeGraph.h.
Referenced by modelChanged().
m_scaling
ScalingMode lmms::gui::EnvelopeGraph::m_scaling = ScalingMode::Dynamic private
Definition at line 76 of file EnvelopeGraph.h.
Referenced by contextMenuEvent(), and paintEvent().
Property Documentation
fullAmountColor
QColor lmms::gui::EnvelopeGraph::fullAmountColor
Definition at line 46 of file EnvelopeGraph.h.
markerFillColor
QColor lmms::gui::EnvelopeGraph::markerFillColor
Definition at line 47 of file EnvelopeGraph.h.
markerOutlineColor
QColor lmms::gui::EnvelopeGraph::markerOutlineColor
Definition at line 48 of file EnvelopeGraph.h.
noAmountColor
QColor lmms::gui::EnvelopeGraph::noAmountColor
Definition at line 45 of file EnvelopeGraph.h.
The documentation for this class was generated from the following files:
include/EnvelopeGraph.h
src/gui/instrument/EnvelopeGraph.cpp