LMMS: lmms::gui::LfoGraph Class Reference
lmms::gui::LfoGraph Class Reference
#include <LfoGraph.h>
Public Member Functions
LfoGraph (QWidget *parent)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
void mousePressEvent (QMouseEvent *me) override
void paintEvent (QPaintEvent *pe) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Properties
QColor fullAmountColor
QColor noAmountColor
Private Member Functions
void drawInfoText (const EnvelopeAndLfoParameters &)
void toggleAmountModel ()
Private Attributes
QColor m_fullAmountColor
QPixmap m_lfoGraph = embed::getIconPixmap("lfo_graph")
QColor m_noAmountColor
float m_randomGraph {0.}
Detailed Description
Definition at line 42 of file LfoGraph.h.
Constructor & Destructor Documentation
LfoGraph()
lmms::gui::LfoGraph::LfoGraph (QWidget * parent)
Definition at line 45 of file LfoGraph.cpp.
References lmms::gui::ModelView::ModelView(), m_fullAmountColor, m_lfoGraph, and m_noAmountColor.
Member Function Documentation
drawInfoText()
void lmms::gui::LfoGraph::drawInfoText (const EnvelopeAndLfoParameters & params) private
Definition at line 157 of file LfoGraph.cpp.
References lmms::gui::adjustedToPixelSize(), lmms::EnvelopeAndLfoParameters::getLfoSpeedModel(), lmms::EnvelopeAndLfoParameters::getX100Model(), lmms::SECS_PER_LFO_OSCILLATION, and lmms::TypedAutomatableModel< T >::value().
Referenced by paintEvent().
mousePressEvent()
void lmms::gui::LfoGraph::mousePressEvent (QMouseEvent * me) override protected
Definition at line 54 of file LfoGraph.cpp.
References toggleAmountModel().
paintEvent()
void lmms::gui::LfoGraph::paintEvent (QPaintEvent * pe) override protected
Definition at line 62 of file LfoGraph.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::baseSampleRate(), lmms::gui::ModelView::castModel(), drawInfoText(), lmms::gui::ColorHelper::interpolateInRgb(), m_fullAmountColor, m_lfoGraph, m_noAmountColor, m_randomGraph, lmms::Oscillator::noiseSample(), lmms::EnvelopeAndLfoParameters::RandomWave, lmms::Oscillator::sawSample(), lmms::EnvelopeAndLfoParameters::SawWave, lmms::SECS_PER_LFO_OSCILLATION, lmms::EnvelopeAndLfoParameters::SineWave, lmms::Oscillator::sinSample(), lmms::Oscillator::squareSample(), lmms::EnvelopeAndLfoParameters::SquareWave, lmms::Oscillator::triangleSample(), lmms::EnvelopeAndLfoParameters::TriangleWave, lmms::EnvelopeAndLfoParameters::UserDefinedWave, and lmms::Oscillator::userWaveSample().
toggleAmountModel()
void lmms::gui::LfoGraph::toggleAmountModel () private
Definition at line 186 of file LfoGraph.cpp.
References lmms::gui::ModelView::castModel().
Referenced by mousePressEvent().
Member Data Documentation
m_fullAmountColor
QColor lmms::gui::LfoGraph::m_fullAmountColor private
Definition at line 64 of file LfoGraph.h.
Referenced by LfoGraph(), and paintEvent().
m_lfoGraph
QPixmap lmms::gui::LfoGraph::m_lfoGraph = embed::getIconPixmap("lfo_graph") private
Definition at line 60 of file LfoGraph.h.
Referenced by LfoGraph(), and paintEvent().
m_noAmountColor
QColor lmms::gui::LfoGraph::m_noAmountColor private
Definition at line 63 of file LfoGraph.h.
Referenced by LfoGraph(), and paintEvent().
m_randomGraph
float lmms::gui::LfoGraph::m_randomGraph {0.} private
Definition at line 62 of file LfoGraph.h.
Referenced by paintEvent().
Property Documentation
fullAmountColor
QColor lmms::gui::LfoGraph::fullAmountColor
Definition at line 46 of file LfoGraph.h.
noAmountColor
QColor lmms::gui::LfoGraph::noAmountColor
Definition at line 45 of file LfoGraph.h.
The documentation for this class was generated from the following files:
include/LfoGraph.h
src/gui/instrument/LfoGraph.cpp