LMMS: lmms::Upsampler< MaxStages, MaxCoefs > Class Template Reference
lmms::Upsampler< MaxStages, MaxCoefs > Class Template Reference
#include <OversamplingHelpers.h>
Public Member Functions
float getPassband () const
float getSampleRate () const
int getStages () const
void processSample (float *outSamples, float inSample)
void reset ()
void setPassband (float passband)
void setSampleRate (float sampleRate)
void setStages (int stages)
void setup (int stages, float sampleRate, float passband=HIIR_DEFAULT_PASSBAND)
Private Attributes
float m_passband = HIIR_DEFAULT_PASSBAND
float m_sampleRate = 44100
int m_stages = 0
hiir::Upsampler2xFpu< s_firstCoefCount > m_upsampleFirst
std::array< hiir::Upsampler2xFpu< s_restCoefCount >, MaxStages - 2 > m_upsampleRest
hiir::Upsampler2xFpu< s_secondCoefCount > m_upsampleSecond
Static Private Attributes
static constexpr int s_firstCoefCount = MaxCoefs
static constexpr int s_restCoefCount = std::max(MaxCoefs / 4, 2)
static constexpr int s_secondCoefCount = std::max(MaxCoefs / 2, 2)
Detailed Description
template<int MaxStages, int MaxCoefs = 8>
class lmms::Upsampler< MaxStages, MaxCoefs >
Definition at line 49 of file OversamplingHelpers.h.
Member Function Documentation
getPassband()
template<int MaxStages, int MaxCoefs = 8> float lmms::Upsampler< MaxStages, MaxCoefs >::getPassband () const inline
Definition at line 123 of file OversamplingHelpers.h.
References m_passband.
getSampleRate()
template<int MaxStages, int MaxCoefs = 8> float lmms::Upsampler< MaxStages, MaxCoefs >::getSampleRate () const inline
Definition at line 122 of file OversamplingHelpers.h.
References m_sampleRate.
getStages()
template<int MaxStages, int MaxCoefs = 8> int lmms::Upsampler< MaxStages, MaxCoefs >::getStages () const inline
Definition at line 121 of file OversamplingHelpers.h.
References m_stages.
processSample()
template<int MaxStages, int MaxCoefs = 8> void lmms::Upsampler< MaxStages, MaxCoefs >::processSample (float * outSamples, float inSample) inline
Definition at line 91 of file OversamplingHelpers.h.
References i, j, m_stages, m_upsampleFirst, m_upsampleRest, and m_upsampleSecond.
reset()
template<int MaxStages, int MaxCoefs = 8> void lmms::Upsampler< MaxStages, MaxCoefs >::reset () inline
Definition at line 52 of file OversamplingHelpers.h.
References hiir::PolyphaseIir2Designer::compute_coefs_spec_order_tbw(), i, m_passband, m_sampleRate, m_stages, m_upsampleFirst, m_upsampleRest, m_upsampleSecond, s_firstCoefCount, s_restCoefCount, and s_secondCoefCount.
Referenced by setPassband(), setSampleRate(), setStages(), and setup().
setPassband()
template<int MaxStages, int MaxCoefs = 8> void lmms::Upsampler< MaxStages, MaxCoefs >::setPassband (float passband) inline
Definition at line 127 of file OversamplingHelpers.h.
References m_passband, and reset().
setSampleRate()
template<int MaxStages, int MaxCoefs = 8> void lmms::Upsampler< MaxStages, MaxCoefs >::setSampleRate (float sampleRate) inline
Definition at line 126 of file OversamplingHelpers.h.
References m_sampleRate, and reset().
setStages()
template<int MaxStages, int MaxCoefs = 8> void lmms::Upsampler< MaxStages, MaxCoefs >::setStages (int stages) inline
Definition at line 125 of file OversamplingHelpers.h.
References m_stages, and reset().
setup()
template<int MaxStages, int MaxCoefs = 8> void lmms::Upsampler< MaxStages, MaxCoefs >::setup (int stages, float sampleRate, float passband = HIIR_DEFAULT_PASSBAND) inline
Definition at line 81 of file OversamplingHelpers.h.
References HIIR_DEFAULT_PASSBAND, m_passband, m_sampleRate, m_stages, and reset().
Member Data Documentation
m_passband
template<int MaxStages, int MaxCoefs = 8> float lmms::Upsampler< MaxStages, MaxCoefs >::m_passband = HIIR_DEFAULT_PASSBAND private
Definition at line 145 of file OversamplingHelpers.h.
Referenced by getPassband(), reset(), setPassband(), and setup().
m_sampleRate
template<int MaxStages, int MaxCoefs = 8> float lmms::Upsampler< MaxStages, MaxCoefs >::m_sampleRate = 44100 private
Definition at line 144 of file OversamplingHelpers.h.
Referenced by getSampleRate(), reset(), setSampleRate(), and setup().
m_stages
template<int MaxStages, int MaxCoefs = 8> int lmms::Upsampler< MaxStages, MaxCoefs >::m_stages = 0 private
Definition at line 143 of file OversamplingHelpers.h.
Referenced by getStages(), processSample(), reset(), setStages(), and setup().
m_upsampleFirst
template<int MaxStages, int MaxCoefs = 8> hiir::Upsampler2xFpu<s_firstCoefCount> lmms::Upsampler< MaxStages, MaxCoefs >::m_upsampleFirst private
Definition at line 138 of file OversamplingHelpers.h.
Referenced by processSample(), and reset().
m_upsampleRest
template<int MaxStages, int MaxCoefs = 8> std::array<hiir::Upsampler2xFpu<s_restCoefCount>, MaxStages - 2> lmms::Upsampler< MaxStages, MaxCoefs >::m_upsampleRest private
Definition at line 140 of file OversamplingHelpers.h.
Referenced by processSample(), and reset().
m_upsampleSecond
template<int MaxStages, int MaxCoefs = 8> hiir::Upsampler2xFpu<s_secondCoefCount> lmms::Upsampler< MaxStages, MaxCoefs >::m_upsampleSecond private
Definition at line 139 of file OversamplingHelpers.h.
Referenced by processSample(), and reset().
s_firstCoefCount
template<int MaxStages, int MaxCoefs = 8> int lmms::Upsampler< MaxStages, MaxCoefs >::s_firstCoefCount = MaxCoefs static constexpr private
Definition at line 130 of file OversamplingHelpers.h.
Referenced by reset().
s_restCoefCount
template<int MaxStages, int MaxCoefs = 8> int lmms::Upsampler< MaxStages, MaxCoefs >::s_restCoefCount = std::max(MaxCoefs / 4, 2) static constexpr private
Definition at line 132 of file OversamplingHelpers.h.
Referenced by reset().
s_secondCoefCount
template<int MaxStages, int MaxCoefs = 8> int lmms::Upsampler< MaxStages, MaxCoefs >::s_secondCoefCount = std::max(MaxCoefs / 2, 2) static constexpr private
Definition at line 131 of file OversamplingHelpers.h.
Referenced by reset().
The documentation for this class was generated from the following file:
include/OversamplingHelpers.h