LMMS: src/3rdparty/jack2/common/jack/jack.h File Reference
jack.h File Reference
#include <jack/systemdeps.h>
#include <jack/types.h>
#include <jack/transport.h>
#include <jack/weakmacros.h>
Functions
int jack_activate (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
Tell the Jack server that the program is ready to start processing audio.
int jack_client_close (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
Disconnects an external client from a JACK server.
int jack_client_name_size (void) JACK_OPTIONAL_WEAK_EXPORT
jack_client_t * jack_client_new (const char *client_name) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS
jack_client_t * jack_client_open (const char *client_name, jack_options_t options, jack_status_t *status,...) JACK_OPTIONAL_WEAK_EXPORT
Open an external client session with a JACK server.
jack_native_thread_t jack_client_thread_id (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
int jack_connect (jack_client_t *client, const char *source_port, const char *destination_port) JACK_OPTIONAL_WEAK_EXPORT
Establish a connection between two ports.
float jack_cpu_load (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
void jack_cycle_signal (jack_client_t *client, int status) JACK_OPTIONAL_WEAK_EXPORT
Signal next clients in the graph.
jack_nframes_t jack_cycle_wait (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
Wait until this JACK client should process data.
int jack_deactivate (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
Tell the Jack server to remove this client from the process graph.
int jack_disconnect (jack_client_t *client, const char *source_port, const char *destination_port) JACK_OPTIONAL_WEAK_EXPORT
Remove a connection between two ports.
int jack_engine_takeover_timebase (jack_client_t *) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Old-style interface to become the timebase for the entire JACK subsystem.
jack_nframes_t jack_frame_time (const jack_client_t *) JACK_OPTIONAL_WEAK_EXPORT
jack_nframes_t jack_frames_since_cycle_start (const jack_client_t *) JACK_OPTIONAL_WEAK_EXPORT
jack_time_t jack_frames_to_time (const jack_client_t *client, jack_nframes_t) JACK_OPTIONAL_WEAK_EXPORT
void jack_free (void *ptr) JACK_OPTIONAL_WEAK_EXPORT
The free function to be used on memory returned by jack_port_get_connections, jack_port_get_all_connections, jack_get_ports and jack_get_internal_client_name functions.
jack_nframes_t jack_get_buffer_size (jack_client_t *) JACK_OPTIONAL_WEAK_EXPORT
char * jack_get_client_name (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
char * jack_get_client_name_by_uuid (jack_client_t *client, const char *client_uuid) JACK_WEAK_EXPORT
Get the client name for a session_id.
int jack_get_client_pid (const char *name) JACK_OPTIONAL_WEAK_EXPORT
int jack_get_cycle_times (const jack_client_t *client, jack_nframes_t *current_frames, jack_time_t *current_usecs, jack_time_t *next_usecs, float *period_usecs) JACK_OPTIONAL_WEAK_EXPORT
This function may only be used from the process callback.
const char ** jack_get_ports (jack_client_t *client, const char *port_name_pattern, const char *type_name_pattern, unsigned long flags) JACK_OPTIONAL_WEAK_EXPORT
jack_nframes_t jack_get_sample_rate (jack_client_t *) JACK_OPTIONAL_WEAK_EXPORT
jack_time_t jack_get_time (void) JACK_OPTIONAL_WEAK_EXPORT
char * jack_get_uuid_for_client_name (jack_client_t *client, const char *client_name) JACK_WEAK_EXPORT
Get the session ID for a client name.
void jack_get_version (int *major_ptr, int *minor_ptr, int *micro_ptr, int *proto_ptr) JACK_OPTIONAL_WEAK_EXPORT
Note: More documentation can be found in jack/types.h.
const char * jack_get_version_string (void) JACK_OPTIONAL_WEAK_EXPORT
Call this function to get version of the JACK, in form of a string.
void jack_internal_client_close (const char *client_name) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Remove an internal client from a JACK server.
int jack_internal_client_new (const char *client_name, const char *load_name, const char *load_init) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Load an internal client into the Jack server.
int jack_is_realtime (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
jack_nframes_t jack_last_frame_time (const jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
void jack_on_info_shutdown (jack_client_t *client, JackInfoShutdownCallback shutdown_callback, void *arg) JACK_WEAK_EXPORT
void jack_on_shutdown (jack_client_t *client, JackShutdownCallback shutdown_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
jack_port_t * jack_port_by_id (jack_client_t *client, jack_port_id_t port_id) JACK_OPTIONAL_WEAK_EXPORT
jack_port_t * jack_port_by_name (jack_client_t *client, const char *port_name) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_connected (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_connected_to (const jack_port_t *port, const char *port_name) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_disconnect (jack_client_t *client, jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
Perform the same function as jack_disconnect() using port handles rather than names.
int jack_port_ensure_monitor (jack_port_t *port, int onoff) JACK_OPTIONAL_WEAK_EXPORT
If JackPortCanMonitor is set for a port, this function turns on input monitoring if it was off, and turns it off if only one request has been made to turn it on.
int jack_port_flags (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_get_aliases (const jack_port_t *port, char *const aliases[2]) JACK_OPTIONAL_WEAK_EXPORT
Get any aliases known for @port.
const char ** jack_port_get_all_connections (const jack_client_t *client, const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
void * jack_port_get_buffer (jack_port_t *port, jack_nframes_t) JACK_OPTIONAL_WEAK_EXPORT
This returns a pointer to the memory area associated with the specified port.
const char ** jack_port_get_connections (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
jack_nframes_t jack_port_get_latency (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
void jack_port_get_latency_range (jack_port_t *port, jack_latency_callback_mode_t mode, jack_latency_range_t *range) JACK_WEAK_EXPORT
return the latency range defined by mode for port, in frames.
jack_nframes_t jack_port_get_total_latency (jack_client_t *client, jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
The maximum of the sum of the latencies in every connection path that can be drawn between the port and other ports with the JackPortIsTerminal flag set.
int jack_port_is_mine (const jack_client_t *client, const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_monitoring_input (jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
const char * jack_port_name (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_name_size (void) JACK_OPTIONAL_WEAK_EXPORT
jack_port_t * jack_port_register (jack_client_t *client, const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size) JACK_OPTIONAL_WEAK_EXPORT
Create a new port for the client.
int jack_port_rename (jack_client_t *client, jack_port_t *port, const char *port_name) JACK_OPTIONAL_WEAK_EXPORT
Modify a port's short name.
int jack_port_request_monitor (jack_port_t *port, int onoff) JACK_OPTIONAL_WEAK_EXPORT
If JackPortCanMonitor is set for this port, turn input monitoring on or off.
int jack_port_request_monitor_by_name (jack_client_t *client, const char *port_name, int onoff) JACK_OPTIONAL_WEAK_EXPORT
If JackPortCanMonitor is set for this port_name, turn input monitoring on or off.
int jack_port_set_alias (jack_port_t *port, const char *alias) JACK_OPTIONAL_WEAK_EXPORT
Set alias as an alias for port.
void jack_port_set_latency (jack_port_t *port, jack_nframes_t) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
The port latency is zero by default.
void jack_port_set_latency_range (jack_port_t *port, jack_latency_callback_mode_t mode, jack_latency_range_t *range) JACK_WEAK_EXPORT
set the minimum and maximum latencies defined by mode for port, in frames.
int jack_port_set_name (jack_port_t *port, const char *port_name) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS
const char * jack_port_short_name (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_tie (jack_port_t *src, jack_port_t *dst) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
const char * jack_port_type (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
size_t jack_port_type_get_buffer_size (jack_client_t *client, const char *port_type) JACK_WEAK_EXPORT
jack_port_type_id_t jack_port_type_id (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_type_size (void) JACK_OPTIONAL_WEAK_EXPORT
int jack_port_unregister (jack_client_t *client, jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
Remove the port from the client, disconnecting any existing connections.
int jack_port_unset_alias (jack_port_t *port, const char *alias) JACK_OPTIONAL_WEAK_EXPORT
Remove alias as an alias for port.
int jack_port_untie (jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
jack_uuid_t jack_port_uuid (const jack_port_t *port) JACK_OPTIONAL_WEAK_EXPORT
int jack_recompute_total_latencies (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
Request a complete recomputation of all port latencies.
int jack_recompute_total_latency (jack_client_t *, jack_port_t *port) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Request a complete recomputation of a port's total latency.
int jack_set_buffer_size (jack_client_t *client, jack_nframes_t nframes) JACK_OPTIONAL_WEAK_EXPORT
Change the buffer size passed to the process_callback.
int jack_set_buffer_size_callback (jack_client_t *client, JackBufferSizeCallback bufsize_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell JACK to call bufsize_callback whenever the size of the the buffer that will be passed to the process_callback is about to change.
int jack_set_client_registration_callback (jack_client_t *client, JackClientRegistrationCallback registration_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the JACK server to call client_registration_callback whenever a client is registered or unregistered, passing arg as a parameter.
void jack_set_error_function (void(*func)(const char *)) JACK_OPTIONAL_WEAK_EXPORT
Set the jack_error_callback for error message display.
int jack_set_freewheel (jack_client_t *client, int onoff) JACK_OPTIONAL_WEAK_EXPORT
Start/Stop JACK's "freewheel" mode.
int jack_set_freewheel_callback (jack_client_t *client, JackFreewheelCallback freewheel_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the Jack server to call freewheel_callback whenever we enter or leave "freewheel" mode, passing arg as the second argument.
int jack_set_graph_order_callback (jack_client_t *client, JackGraphOrderCallback graph_callback, void *) JACK_OPTIONAL_WEAK_EXPORT
Tell the JACK server to call graph_callback whenever the processing graph is reordered, passing arg as a parameter.
void jack_set_info_function (void(*func)(const char *)) JACK_OPTIONAL_WEAK_EXPORT
Set the jack_info_callback for info message display.
int jack_set_latency_callback (jack_client_t *client, JackLatencyCallback latency_callback, void *) JACK_WEAK_EXPORT
Tell the Jack server to call latency_callback whenever it is necessary to recompute the latencies for some or all Jack ports.
int jack_set_port_connect_callback (jack_client_t *client, JackPortConnectCallback connect_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the JACK server to call connect_callback whenever a port is connected or disconnected, passing arg as a parameter.
int jack_set_port_registration_callback (jack_client_t *client, JackPortRegistrationCallback registration_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the JACK server to call registration_callback whenever a port is registered or unregistered, passing arg as a parameter.
int jack_set_port_rename_callback (jack_client_t *client, JackPortRenameCallback rename_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the JACK server to call rename_callback whenever a port is renamed, passing arg as a parameter.
int jack_set_process_callback (jack_client_t *client, JackProcessCallback process_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the Jack server to call process_callback whenever there is work be done, passing arg as the second argument.
int jack_set_process_thread (jack_client_t *client, JackThreadCallback thread_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the Jack server to call thread_callback in the RT thread.
int jack_set_sample_rate_callback (jack_client_t *client, JackSampleRateCallback srate_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the Jack server to call srate_callback whenever the system sample rate changes.
int jack_set_thread_init_callback (jack_client_t *client, JackThreadInitCallback thread_init_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell JACK to call thread_init_callback once just after the creation of the thread in which all other callbacks will be handled.
int jack_set_xrun_callback (jack_client_t *client, JackXRunCallback xrun_callback, void *arg) JACK_OPTIONAL_WEAK_EXPORT
Tell the JACK server to call xrun_callback whenever there is a xrun, passing arg as a parameter.
jack_nframes_t jack_thread_wait (jack_client_t *client, int status) JACK_OPTIONAL_WEAK_EXPORT
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS.
jack_nframes_t jack_time_to_frames (const jack_client_t *client, jack_time_t) JACK_OPTIONAL_WEAK_EXPORT
Variables
void(* jack_error_callback)(const char *msg) JACK_OPTIONAL_WEAK_EXPORT
Display JACK error message.
void(* jack_info_callback)(const char *msg) JACK_OPTIONAL_WEAK_EXPORT
Display JACK info message.
Function Documentation
jack_free()
LIB_EXPORT void jack_free (void * ptr)
The free function to be used on memory returned by jack_port_get_connections, jack_port_get_all_connections, jack_get_ports and jack_get_internal_client_name functions.
This is MANDATORY on Windows when otherwise all nasty runtime version related crashes can occur. Developers are strongly encouraged to use this function instead of the standard "free" function in new code.
Parameters
ptr the memory pointer to be deallocated.
Definition at line 1920 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), and LIB_EXPORT.
Referenced by Jack::JackAudioAdapter::ConnectPorts(), Jack::JackNetMaster::ConnectPorts(), Jack::JackProxyDriver::ConnectPorts(), Jack::JackNetMasterManager::CountIO(), Jack::JackProxyDriver::CountIO(), jack_set_info_function(), Jack::JackProxyDriver::LoadSymbols(), main(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), Jack::JackNetMaster::SaveConnections(), and Jack::JackSapaProxy::Setup().
jack_get_version()
LIB_EXPORT void jack_get_version (int * major_ptr, int * minor_ptr, int * micro_ptr, int * proto_ptr)
Note: More documentation can be found in jack/types.h.
Call this function to get version of the JACK, in form of several numbers
Parameters
major_ptr pointer to variable receiving major version of JACK.
minor_ptr pointer to variable receiving minor version of JACK.
major_ptr pointer to variable receiving micro version of JACK.
major_ptr pointer to variable receiving protocol version of JACK.
Definition at line 1900 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), and LIB_EXPORT.
jack_get_version_string()
LIB_EXPORT const char * jack_get_version_string (void)
Call this function to get version of the JACK, in form of a string.
Returns
Human readable string describing JACK version being used.
Definition at line 1914 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), LIB_EXPORT, and VERSION.
jack_is_realtime()
LIB_EXPORT int jack_is_realtime (jack_client_t * client)
Parameters
client pointer to JACK client structure.
Check if the JACK subsystem is running with -R (–realtime).
Returns
1 if JACK is running realtime, 0 otherwise
Definition at line 795 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fRealTime, Jack::GetEngineControl(), jack_error, and LIB_EXPORT.
Referenced by main().