LMMS: lmms::PluginFactory::PluginInfo Struct Reference
lmms::PluginFactory::PluginInfo Struct Reference
#include <PluginFactory.h>
Public Member Functions
bool isNull () const
QString name () const
Public Attributes
Plugin::Descriptor * descriptor = nullptr
QFileInfo file
std::shared_ptr< QLibrary > library = nullptr
Detailed Description
Definition at line 47 of file PluginFactory.h.
Member Function Documentation
isNull()
bool lmms::PluginFactory::PluginInfo::isNull () const inline
Definition at line 54 of file PluginFactory.h.
References library.
Referenced by lmms::Plugin::instantiate().
name()
QString lmms::PluginFactory::PluginInfo::name () const
Definition at line 306 of file PluginFactory.cpp.
References descriptor.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::gui::InstrumentTrackWindow::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), and lmms::gui::FileBrowserTreeWidget::handleFile().
Member Data Documentation
descriptor
Plugin::Descriptor* lmms::PluginFactory::PluginInfo::descriptor = nullptr
Definition at line 52 of file PluginFactory.h.
Referenced by lmms::PluginFactory::discoverPlugins(), lmms::Plugin::instantiateWithKey(), and name().
file
QFileInfo lmms::PluginFactory::PluginInfo::file
Definition at line 50 of file PluginFactory.h.
Referenced by lmms::PluginFactory::discoverPlugins().
library
std::shared_ptr<QLibrary> lmms::PluginFactory::PluginInfo::library = nullptr
Definition at line 50 of file PluginFactory.h.
Referenced by lmms::PluginFactory::discoverPlugins(), lmms::Plugin::instantiate(), and isNull().
The documentation for this struct was generated from the following files:
include/PluginFactory.h
src/core/PluginFactory.cpp