LMMS: hiir::StageProc8F64Avx512< REMAINING > Class Template Reference
hiir::StageProc8F64Avx512< REMAINING > Class Template Reference
#include <StageProc8F64Avx512.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m512d &spl_0, __m512d &spl_1, StageDataF64Avx512 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m512d &spl_0, __m512d &spl_1, StageDataF64Avx512 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m512d &spl_0, __m512d &spl_1, StageDataF64Avx512 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m512d &spl_0, __m512d &spl_1, StageDataF64Avx512 *stage_arr) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m512d &spl_0, __m512d &spl_1, StageDataF64Avx512 *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m512d &spl_0, __m512d &spl_1, StageDataF64Avx512 *stage_arr) noexcept
Private Member Functions
StageProc8F64Avx512 ()=delete
StageProc8F64Avx512 (const StageProc8F64Avx512< REMAINING > &other)=delete
StageProc8F64Avx512 (StageProc8F64Avx512< REMAINING > &&other)=delete
~StageProc8F64Avx512 ()=delete
bool operator!= (const StageProc8F64Avx512< REMAINING > &other)=delete
StageProc8F64Avx512< REMAINING > & operator= (const StageProc8F64Avx512< REMAINING > &other)=delete
StageProc8F64Avx512< REMAINING > & operator= (StageProc8F64Avx512< REMAINING > &&other)=delete
bool operator== (const StageProc8F64Avx512< REMAINING > &other)=delete
Detailed Description
template<int REMAINING>
class hiir::StageProc8F64Avx512< REMAINING >
Definition at line 47 of file StageProc8F64Avx512.h.
Constructor & Destructor Documentation
StageProc8F64Avx512() [1/3]
template<int REMAINING> hiir::StageProc8F64Avx512< REMAINING >::StageProc8F64Avx512 () private delete
Referenced by process_sample_neg(), and process_sample_pos().
StageProc8F64Avx512() [2/3]
template<int REMAINING> hiir::StageProc8F64Avx512< REMAINING >::StageProc8F64Avx512 (const StageProc8F64Avx512< REMAINING > & other) private delete
StageProc8F64Avx512() [3/3]
template<int REMAINING> hiir::StageProc8F64Avx512< REMAINING >::StageProc8F64Avx512 (StageProc8F64Avx512< REMAINING > && other) private delete
~StageProc8F64Avx512()
template<int REMAINING> hiir::StageProc8F64Avx512< REMAINING >::~StageProc8F64Avx512 () private delete
Member Function Documentation
operator!=()
template<int REMAINING> bool hiir::StageProc8F64Avx512< REMAINING >::operator!= (const StageProc8F64Avx512< REMAINING > & other) private delete
operator=() [1/2]
template<int REMAINING> StageProc8F64Avx512< REMAINING > & hiir::StageProc8F64Avx512< REMAINING >::operator= (const StageProc8F64Avx512< REMAINING > & other) private delete
operator=() [2/2]
template<int REMAINING> StageProc8F64Avx512< REMAINING > & hiir::StageProc8F64Avx512< REMAINING >::operator= (StageProc8F64Avx512< REMAINING > && other) private delete
operator==()
template<int REMAINING> bool hiir::StageProc8F64Avx512< REMAINING >::operator== (const StageProc8F64Avx512< REMAINING > & other) private delete
process_sample_neg() [1/3]
template<int REMAINING> void hiir::StageProc8F64Avx512< REMAINING >::process_sample_neg (const int nbr_coefs, __m512d & spl_0, __m512d & spl_1, StageDataF64Avx512 * stage_arr) static noexcept
Definition at line 146 of file StageProc8F64Avx512.hpp.
References StageProc8F64Avx512(), and process_sample_neg().
Referenced by hiir::PhaseHalfPi8F64Avx512< NC >::process_block(), hiir::PhaseHalfPi8F64Avx512< NC >::process_sample(), and process_sample_neg().
process_sample_neg() [2/3]
hiir_FORCEINLINE void hiir::StageProc8F64Avx512< 0 >::process_sample_neg (const int nbr_coefs, __m512d & spl_0, __m512d & spl_1, StageDataF64Avx512 * stage_arr) noexcept
Definition at line 135 of file StageProc8F64Avx512.hpp.
References hiir_FORCEINLINE.
process_sample_neg() [3/3]
hiir_FORCEINLINE void hiir::StageProc8F64Avx512< 1 >::process_sample_neg (const int nbr_coefs, __m512d & spl_0, __m512d & spl_1, StageDataF64Avx512 * stage_arr) noexcept
Definition at line 113 of file StageProc8F64Avx512.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [1/3]
template<int REMAINING> void hiir::StageProc8F64Avx512< REMAINING >::process_sample_pos (const int nbr_coefs, __m512d & spl_0, __m512d & spl_1, StageDataF64Avx512 * stage_arr) static noexcept
Definition at line 77 of file StageProc8F64Avx512.hpp.
References StageProc8F64Avx512(), and process_sample_pos().
Referenced by hiir::HalfBand8F64Avx512< NC >::process_2_paths(), hiir::HalfBand8F64Avx512< NC >::process_block_2_paths(), hiir::Downsampler2x8F64Avx512< NC >::process_sample(), hiir::Upsampler2x8F64Avx512< NC >::process_sample(), process_sample_pos(), and hiir::Downsampler2x8F64Avx512< NC >::process_sample_split().
process_sample_pos() [2/3]
hiir_FORCEINLINE void hiir::StageProc8F64Avx512< 0 >::process_sample_pos (const int nbr_coefs, __m512d & spl_0, __m512d & spl_1, StageDataF64Avx512 * stage_arr) noexcept
Definition at line 66 of file StageProc8F64Avx512.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [3/3]
hiir_FORCEINLINE void hiir::StageProc8F64Avx512< 1 >::process_sample_pos (const int nbr_coefs, __m512d & spl_0, __m512d & spl_1, StageDataF64Avx512 * stage_arr) noexcept
Definition at line 44 of file StageProc8F64Avx512.hpp.
References hiir_FORCEINLINE.
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProc8F64Avx512.h
src/3rdparty/hiir/hiir/StageProc8F64Avx512.hpp