LMMS: lmms::gui::InstrumentTrackWindow Class Reference
lmms::gui::InstrumentTrackWindow Class Reference
#include <InstrumentTrackWindow.h>
Public Slots
void textChanged (const QString &_new_name)
void toggleVisibility (bool _on)
void updateInstrumentView ()
void updateName ()
Public Member Functions
InstrumentTrackWindow (InstrumentTrackView *_tv)
~InstrumentTrackWindow () override
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
InstrumentTrackView * instrumentTrackView ()
InstrumentTrack * model ()
const InstrumentTrack * model () const
PianoView * pianoView ()
void resizeEvent (QResizeEvent *event) override
void setInstrumentTrackView (InstrumentTrackView *_tv)
TabWidget * tabWidgetParent ()
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::SerializingObjectHook
SerializingObjectHook ()
virtual ~SerializingObjectHook ()
Static Public Member Functions
static void dragEnterEventGeneric (QDragEnterEvent *_dee)
Protected Slots
void saveSettingsBtnClicked ()
void viewNextInstrument ()
void viewPrevInstrument ()
Protected Member Functions
void closeEvent (QCloseEvent *_ce) override
void focusInEvent (QFocusEvent *_fe) override
void loadSettings (const QDomElement &_this) override
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Member Functions
void adjustTabSize (QWidget *w)
adjust size of any child widget of the main tab required to keep the old look when using a variable sized tab widget
QMdiSubWindow * findSubWindowInParents ()
void modelChanged () override
void updateSubWindow ()
void viewInstrumentInDirection (int d)
Private Attributes
InstrumentFunctionArpeggioView * m_arpeggioView
EffectRackView * m_effectView
QWidget * m_instrumentFunctionsView
PluginView * m_instrumentView
InstrumentTrackView * m_itv
LeftRightNav * m_leftRightNav
InstrumentMidiIOView * m_midiView
MixerChannelLcdSpinBox * m_mixerChannelNumber
AutomatableButton * m_muteBtn
QLineEdit * m_nameLineEdit
InstrumentFunctionNoteStackingView * m_noteStackingView
Knob * m_panningKnob
PianoView * m_pianoView
Knob * m_pitchKnob
QLabel * m_pitchLabel
QLabel * m_pitchRangeLabel
LcdSpinBox * m_pitchRangeSpinBox
AutomatableButton * m_soloBtn
InstrumentSoundShapingView * m_ssView
TabWidget * m_tabWidget
InstrumentTrack * m_track
InstrumentTuningView * m_tuningView
Knob * m_volumeKnob
Friends
class InstrumentTrackView
class InstrumentView
Detailed Description
Definition at line 61 of file InstrumentTrackWindow.h.
Constructor & Destructor Documentation
InstrumentTrackWindow()
lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow (InstrumentTrackView * _tv)
Definition at line 81 of file InstrumentTrackWindow.cpp.
References lmms::gui::ModelView::ModelView(), lmms::gui::MainWindow::addWindowedWidget(), lmms::gui::Bright26, lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::gui::GRAPHIC_TAB_HEIGHT, lmms::gui::INSTRUMENT_HEIGHT, InstrumentTrackView, m_arpeggioView, m_effectView, m_instrumentFunctionsView, m_instrumentView, m_itv, m_leftRightNav, m_midiView, m_mixerChannelNumber, m_muteBtn, m_nameLineEdit, m_noteStackingView, m_panningKnob, m_pianoView, m_pitchKnob, m_pitchLabel, m_pitchRangeLabel, m_pitchRangeSpinBox, m_soloBtn, m_ssView, m_tabWidget, m_track, m_tuningView, m_volumeKnob, lmms::gui::GuiApplication::mainWindow(), lmms::gui::InstrumentTrackView::model(), model(), lmms::gui::PIANO_HEIGHT, saveSettingsBtnClicked(), lmms::gui::ModelView::setModel(), textChanged(), updateInstrumentView(), updateSubWindow(), viewNextInstrument(), and viewPrevInstrument().
~InstrumentTrackWindow()
lmms::gui::InstrumentTrackWindow::~InstrumentTrackWindow () override
Definition at line 323 of file InstrumentTrackWindow.cpp.
References m_instrumentView.
Member Function Documentation
adjustTabSize()
void lmms::gui::InstrumentTrackWindow::adjustTabSize (QWidget * w) private
adjust size of any child widget of the main tab required to keep the old look when using a variable sized tab widget
Definition at line 708 of file InstrumentTrackWindow.cpp.
Referenced by resizeEvent(), and updateInstrumentView().
closeEvent()
void lmms::gui::InstrumentTrackWindow::closeEvent (QCloseEvent * _ce) override protected
Definition at line 531 of file InstrumentTrackWindow.cpp.
References lmms::gui::getGUI(), and m_itv.
dragEnterEvent()
void lmms::gui::InstrumentTrackWindow::dragEnterEvent (QDragEnterEvent * _dee) override
Definition at line 569 of file InstrumentTrackWindow.cpp.
References dragEnterEventGeneric().
dragEnterEventGeneric()
void lmms::gui::InstrumentTrackWindow::dragEnterEventGeneric (QDragEnterEvent * _dee) static
Definition at line 561 of file InstrumentTrackWindow.cpp.
References lmms::gui::StringPairDrag::processDragEnterEvent().
Referenced by lmms::gui::InstrumentTrackView::dragEnterEvent(), and dragEnterEvent().
dropEvent()
void lmms::gui::InstrumentTrackWindow::dropEvent (QDropEvent * _de) override
Definition at line 577 of file InstrumentTrackWindow.cpp.
References lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::gui::FileItem::extension(), lmms::getPluginFactory(), lmms::Engine::getSong(), i, lmms::PluginFactory::PluginInfoAndKey::info, lmms::PluginFactory::PluginInfoAndKey::key, m_track, lmms::PluginFactory::PluginInfo::name(), lmms::PluginFactory::pluginSupportingExtension(), and lmms::Song::setModified().
Referenced by lmms::gui::InstrumentTrackView::dropEvent().
findSubWindowInParents()
QMdiSubWindow * lmms::gui::InstrumentTrackWindow::findSubWindowInParents () private
Definition at line 717 of file InstrumentTrackWindow.cpp.
Referenced by updateSubWindow().
focusInEvent()
void lmms::gui::InstrumentTrackWindow::focusInEvent (QFocusEvent * _fe) override protected
Definition at line 551 of file InstrumentTrackWindow.cpp.
References m_pianoView.
instrumentTrackView()
InstrumentTrackView * lmms::gui::InstrumentTrackWindow::instrumentTrackView () inline
Definition at line 90 of file InstrumentTrackWindow.h.
References InstrumentTrackView, and m_itv.
loadSettings()
void lmms::gui::InstrumentTrackWindow::loadSettings (const QDomElement & _this) override protected virtual
Implements lmms::SerializingObjectHook.
Definition at line 629 of file InstrumentTrackWindow.cpp.
References m_itv, m_tabWidget, and lmms::gui::MainWindow::restoreWidgetState().
model() [1/2]
InstrumentTrack * lmms::gui::InstrumentTrackWindow::model () inline
Definition at line 78 of file InstrumentTrackWindow.h.
References lmms::gui::ModelView::castModel().
Referenced by InstrumentTrackWindow().
model() [2/2]
const InstrumentTrack * lmms::gui::InstrumentTrackWindow::model () const inline
Definition at line 83 of file InstrumentTrackWindow.h.
References lmms::gui::ModelView::castModel().
modelChanged()
void lmms::gui::InstrumentTrackWindow::modelChanged () override private virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 351 of file InstrumentTrackWindow.cpp.
References lmms::gui::ModelView::castModel(), m_arpeggioView, m_effectView, m_midiView, m_mixerChannelNumber, m_nameLineEdit, m_noteStackingView, m_panningKnob, m_pianoView, m_pitchKnob, m_pitchLabel, m_pitchRangeLabel, m_pitchRangeSpinBox, m_ssView, m_track, m_tuningView, m_volumeKnob, updateInstrumentView(), updateName(), and updateSubWindow().
Referenced by updateInstrumentView(), and viewInstrumentInDirection().
pianoView()
PianoView * lmms::gui::InstrumentTrackWindow::pianoView () inline
Definition at line 96 of file InstrumentTrackWindow.h.
References m_pianoView.
Referenced by lmms::gui::MainWindow::keyPressEvent().
resizeEvent()
void lmms::gui::InstrumentTrackWindow::resizeEvent (QResizeEvent * event) override
Definition at line 311 of file InstrumentTrackWindow.cpp.
References adjustTabSize(), m_effectView, m_instrumentFunctionsView, m_instrumentView, m_midiView, m_ssView, and m_tuningView.
saveSettings()
void lmms::gui::InstrumentTrackWindow::saveSettings (QDomDocument & _doc, QDomElement & _this) override protected virtual
Implements lmms::SerializingObjectHook.
Definition at line 620 of file InstrumentTrackWindow.cpp.
References m_tabWidget, and lmms::gui::MainWindow::saveWidgetState().
saveSettingsBtnClicked
void lmms::gui::InstrumentTrackWindow::saveSettingsBtnClicked () protected slot
Definition at line 418 of file InstrumentTrackWindow.cpp.
References lmms::DataFile::content(), lmms::FILENAME_FILTER, lmms::ConfigManager::inst(), lmms::DataFile::InstrumentTrackSettings, m_track, lmms::ConfigManager::userPresetsDir(), and lmms::DataFile::writeFile().
Referenced by InstrumentTrackWindow().
setInstrumentTrackView()
void lmms::gui::InstrumentTrackWindow::setInstrumentTrackView (InstrumentTrackView * _tv)
Definition at line 337 of file InstrumentTrackWindow.cpp.
References InstrumentTrackView, m_itv, and m_mixerChannelNumber.
tabWidgetParent()
TabWidget * lmms::gui::InstrumentTrackWindow::tabWidgetParent () inline
Definition at line 73 of file InstrumentTrackWindow.h.
References m_tabWidget.
textChanged
void lmms::gui::InstrumentTrackWindow::textChanged (const QString & _new_name) slot
Definition at line 505 of file InstrumentTrackWindow.cpp.
References lmms::Engine::getSong(), m_track, and lmms::Song::setModified().
Referenced by InstrumentTrackWindow().
toggleVisibility
void lmms::gui::InstrumentTrackWindow::toggleVisibility (bool _on) slot
Definition at line 514 of file InstrumentTrackWindow.cpp.
Referenced by lmms::gui::InstrumentTrackView::toggleInstrumentWindow().
updateInstrumentView
void lmms::gui::InstrumentTrackWindow::updateInstrumentView () slot
Definition at line 474 of file InstrumentTrackWindow.cpp.
References adjustTabSize(), m_instrumentView, m_pianoView, m_ssView, m_tabWidget, m_track, and modelChanged().
Referenced by InstrumentTrackWindow(), and modelChanged().
updateName
void lmms::gui::InstrumentTrackWindow::updateName () slot
Definition at line 460 of file InstrumentTrackWindow.cpp.
References m_nameLineEdit, and m_track.
Referenced by modelChanged().
updateSubWindow()
void lmms::gui::InstrumentTrackWindow::updateSubWindow () private
Definition at line 738 of file InstrumentTrackWindow.cpp.
References findSubWindowInParents(), and m_instrumentView.
Referenced by InstrumentTrackWindow(), and modelChanged().
viewInstrumentInDirection()
void lmms::gui::InstrumentTrackWindow::viewInstrumentInDirection (int d) private
Definition at line 639 of file InstrumentTrackWindow.cpp.
References lmms::gui::InstrumentTrackView::getInstrumentTrackWindow(), InstrumentTrackView, m_instrumentView, m_itv, lmms::gui::InstrumentTrackView::m_tlb, modelChanged(), lmms::gui::TrackContainerView::scrollToTrackView(), and lmms::gui::TrackView::trackContainerView().
Referenced by viewNextInstrument(), and viewPrevInstrument().
viewNextInstrument
void lmms::gui::InstrumentTrackWindow::viewNextInstrument () protected slot
Definition at line 699 of file InstrumentTrackWindow.cpp.
References viewInstrumentInDirection().
Referenced by InstrumentTrackWindow().
viewPrevInstrument
void lmms::gui::InstrumentTrackWindow::viewPrevInstrument () protected slot
Definition at line 703 of file InstrumentTrackWindow.cpp.
References viewInstrumentInDirection().
Referenced by InstrumentTrackWindow().
Friends And Related Symbol Documentation
InstrumentTrackView
friend class InstrumentTrackView friend
Definition at line 172 of file InstrumentTrackWindow.h.
References InstrumentTrackView.
Referenced by InstrumentTrackWindow(), InstrumentTrackView, instrumentTrackView(), setInstrumentTrackView(), and viewInstrumentInDirection().
InstrumentView
friend class InstrumentView friend
Definition at line 171 of file InstrumentTrackWindow.h.
References InstrumentView.
Referenced by InstrumentView.
Member Data Documentation
m_arpeggioView
InstrumentFunctionArpeggioView* lmms::gui::InstrumentTrackWindow::m_arpeggioView private
Definition at line 161 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and modelChanged().
m_effectView
EffectRackView* lmms::gui::InstrumentTrackWindow::m_effectView private
Definition at line 164 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), modelChanged(), and resizeEvent().
m_instrumentFunctionsView
QWidget* lmms::gui::InstrumentTrackWindow::m_instrumentFunctionsView private
Definition at line 162 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and resizeEvent().
m_instrumentView
PluginView* lmms::gui::InstrumentTrackWindow::m_instrumentView private
Definition at line 158 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), ~InstrumentTrackWindow(), lmms::gui::InstrumentView::~InstrumentView(), resizeEvent(), updateInstrumentView(), updateSubWindow(), and viewInstrumentInDirection().
m_itv
InstrumentTrackView* lmms::gui::InstrumentTrackWindow::m_itv private
Definition at line 139 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), closeEvent(), instrumentTrackView(), loadSettings(), setInstrumentTrackView(), lmms::gui::InstrumentTrackView::toggleInstrumentWindow(), and viewInstrumentInDirection().
m_leftRightNav
LeftRightNav* lmms::gui::InstrumentTrackWindow::m_leftRightNav private
Definition at line 143 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow().
m_midiView
InstrumentMidiIOView* lmms::gui::InstrumentTrackWindow::m_midiView private
Definition at line 163 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), modelChanged(), and resizeEvent().
m_mixerChannelNumber
MixerChannelLcdSpinBox* lmms::gui::InstrumentTrackWindow::m_mixerChannelNumber private
Definition at line 152 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), modelChanged(), and setInstrumentTrackView().
m_muteBtn
AutomatableButton* lmms::gui::InstrumentTrackWindow::m_muteBtn private
Definition at line 147 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow().
m_nameLineEdit
QLineEdit* lmms::gui::InstrumentTrackWindow::m_nameLineEdit private
Definition at line 142 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), modelChanged(), and updateName().
m_noteStackingView
InstrumentFunctionNoteStackingView* lmms::gui::InstrumentTrackWindow::m_noteStackingView private
Definition at line 160 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and modelChanged().
m_panningKnob
Knob* lmms::gui::InstrumentTrackWindow::m_panningKnob private
Definition at line 145 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and modelChanged().
m_pianoView
PianoView* lmms::gui::InstrumentTrackWindow::m_pianoView private
Definition at line 169 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), focusInEvent(), modelChanged(), pianoView(), and updateInstrumentView().
m_pitchKnob
Knob* lmms::gui::InstrumentTrackWindow::m_pitchKnob private
Definition at line 146 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and modelChanged().
m_pitchLabel
QLabel* lmms::gui::InstrumentTrackWindow::m_pitchLabel private
Definition at line 149 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and modelChanged().
m_pitchRangeLabel
QLabel* lmms::gui::InstrumentTrackWindow::m_pitchRangeLabel private
Definition at line 151 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and modelChanged().
m_pitchRangeSpinBox
LcdSpinBox* lmms::gui::InstrumentTrackWindow::m_pitchRangeSpinBox private
Definition at line 150 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and modelChanged().
m_soloBtn
AutomatableButton* lmms::gui::InstrumentTrackWindow::m_soloBtn private
Definition at line 148 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow().
m_ssView
InstrumentSoundShapingView* lmms::gui::InstrumentTrackWindow::m_ssView private
Definition at line 159 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), modelChanged(), resizeEvent(), and updateInstrumentView().
m_tabWidget
TabWidget* lmms::gui::InstrumentTrackWindow::m_tabWidget private
Definition at line 157 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), loadSettings(), saveSettings(), tabWidgetParent(), and updateInstrumentView().
m_track
InstrumentTrack* lmms::gui::InstrumentTrackWindow::m_track private
Definition at line 138 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), dropEvent(), modelChanged(), saveSettingsBtnClicked(), textChanged(), updateInstrumentView(), and updateName().
m_tuningView
InstrumentTuningView* lmms::gui::InstrumentTrackWindow::m_tuningView private
Definition at line 165 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), modelChanged(), and resizeEvent().
m_volumeKnob
Knob* lmms::gui::InstrumentTrackWindow::m_volumeKnob private
Definition at line 144 of file InstrumentTrackWindow.h.
Referenced by InstrumentTrackWindow(), and modelChanged().
The documentation for this class was generated from the following files:
include/InstrumentTrackWindow.h
src/gui/instrument/InstrumentTrackWindow.cpp