LMMS: lmms::gui::ControlLayout Class Reference
lmms::gui::ControlLayout Class Reference
Layout for controls (models).
#include <ControlLayout.h>
Public Member Functions
ControlLayout (QWidget *parent, int margin=-1, int hSpacing=-1, int vSpacing=-1)
~ControlLayout () override
void addItem (QLayoutItem *item) override
int count () const override
Qt::Orientations expandingDirections () const override
bool hasHeightForWidth () const override
int heightForWidth (int) const override
int horizontalSpacing () const
QLayoutItem * itemAt (int index) const override
QLayoutItem * itemByString (const QString &key) const
QSize minimumSize () const override
void removeFocusFromSearchBar ()
remove focus from QLineEdit search bar this may be useful if the mouse is outside the layout
void setGeometry (const QRect &rect) override
QSize sizeHint () const override
QLayoutItem * takeAt (int index) override
int verticalSpacing () const
Private Slots
void onTextChanged (const QString &)
Private Member Functions
int doLayout (const QRect &rect, bool testOnly) const
QMap< QString, QLayoutItem * >::const_iterator pairAt (int index) const
int smartSpacing (QStyle::PixelMetric pm) const
Private Attributes
int m_hSpace
QMultiMap< QString, QLayoutItem * > m_itemMap
QLineEdit * m_searchBar
int m_vSpace
Static Private Attributes
constexpr static const int m_minWidth = 400
static constexpr const char * s_searchBarName = "!!searchBar!!"
name of search bar, must be ASCII sorted before any alpha numerics
Detailed Description
Layout for controls (models).
Originally token from Qt's FlowLayout example. Modified.
Features a search bar, as well as looking up widgets with string keys Keys have to be provided in the widgets' objectNames
Definition at line 95 of file ControlLayout.h.
Constructor & Destructor Documentation
ControlLayout()
lmms::gui::ControlLayout::ControlLayout (QWidget * parent, int margin = -1, int hSpacing = -1, int vSpacing = -1) explicit
Definition at line 89 of file ControlLayout.cpp.
References m_hSpace, m_searchBar, m_vSpace, onTextChanged(), and s_searchBarName.
~ControlLayout()
lmms::gui::ControlLayout::~ControlLayout () override
Definition at line 102 of file ControlLayout.cpp.
References takeAt().
Member Function Documentation
addItem()
void lmms::gui::ControlLayout::addItem (QLayoutItem * item) override
Definition at line 113 of file ControlLayout.cpp.
References m_itemMap.
count()
int lmms::gui::ControlLayout::count () const override
Definition at line 139 of file ControlLayout.cpp.
References m_itemMap.
doLayout()
int lmms::gui::ControlLayout::doLayout (const QRect & rect, bool testOnly) const private
Definition at line 233 of file ControlLayout.cpp.
References horizontalSpacing(), m_itemMap, m_searchBar, and verticalSpacing().
Referenced by heightForWidth(), and setGeometry().
expandingDirections()
Qt::Orientations lmms::gui::ControlLayout::expandingDirections () const override
Definition at line 187 of file ControlLayout.cpp.
hasHeightForWidth()
bool lmms::gui::ControlLayout::hasHeightForWidth () const override
Definition at line 192 of file ControlLayout.cpp.
heightForWidth()
int lmms::gui::ControlLayout::heightForWidth (int width) const override
Definition at line 197 of file ControlLayout.cpp.
References doLayout().
horizontalSpacing()
int lmms::gui::ControlLayout::horizontalSpacing () const
Definition at line 121 of file ControlLayout.cpp.
References m_hSpace, and smartSpacing().
Referenced by doLayout().
itemAt()
QLayoutItem * lmms::gui::ControlLayout::itemAt (int index) const override
Definition at line 163 of file ControlLayout.cpp.
References m_itemMap, and pairAt().
itemByString()
QLayoutItem * lmms::gui::ControlLayout::itemByString (const QString & key) const
Definition at line 169 of file ControlLayout.cpp.
References m_itemMap.
minimumSize()
QSize lmms::gui::ControlLayout::minimumSize () const override
Definition at line 214 of file ControlLayout.cpp.
References m_itemMap, and m_minWidth.
Referenced by sizeHint().
onTextChanged
void lmms::gui::ControlLayout::onTextChanged (const QString &) private slot
Definition at line 107 of file ControlLayout.cpp.
Referenced by ControlLayout().
pairAt()
QMap< QString, QLayoutItem * >::const_iterator lmms::gui::ControlLayout::pairAt (int index) const private
Definition at line 145 of file ControlLayout.cpp.
References m_itemMap, and s_searchBarName.
Referenced by itemAt(), and takeAt().
removeFocusFromSearchBar()
void lmms::gui::ControlLayout::removeFocusFromSearchBar ()
remove focus from QLineEdit search bar this may be useful if the mouse is outside the layout
Definition at line 182 of file ControlLayout.cpp.
References m_searchBar.
setGeometry()
void lmms::gui::ControlLayout::setGeometry (const QRect & rect) override
Definition at line 203 of file ControlLayout.cpp.
References doLayout().
sizeHint()
QSize lmms::gui::ControlLayout::sizeHint () const override
Definition at line 209 of file ControlLayout.cpp.
References minimumSize().
smartSpacing()
int lmms::gui::ControlLayout::smartSpacing (QStyle::PixelMetric pm) const private
Definition at line 305 of file ControlLayout.cpp.
Referenced by horizontalSpacing(), and verticalSpacing().
takeAt()
QLayoutItem * lmms::gui::ControlLayout::takeAt (int index) override
Definition at line 176 of file ControlLayout.cpp.
References m_itemMap, and pairAt().
Referenced by ~ControlLayout().
verticalSpacing()
int lmms::gui::ControlLayout::verticalSpacing () const
Definition at line 130 of file ControlLayout.cpp.
References m_vSpace, and smartSpacing().
Referenced by doLayout().
Member Data Documentation
m_hSpace
int lmms::gui::ControlLayout::m_hSpace private
Definition at line 130 of file ControlLayout.h.
Referenced by ControlLayout(), and horizontalSpacing().
m_itemMap
QMultiMap<QString, QLayoutItem *> lmms::gui::ControlLayout::m_itemMap private
Definition at line 129 of file ControlLayout.h.
Referenced by addItem(), count(), doLayout(), itemAt(), itemByString(), minimumSize(), pairAt(), and takeAt().
m_minWidth
const int lmms::gui::ControlLayout::m_minWidth = 400 static constexpr private
Definition at line 134 of file ControlLayout.h.
Referenced by minimumSize().
m_searchBar
QLineEdit* lmms::gui::ControlLayout::m_searchBar private
Definition at line 135 of file ControlLayout.h.
Referenced by ControlLayout(), doLayout(), and removeFocusFromSearchBar().
m_vSpace
int lmms::gui::ControlLayout::m_vSpace private
Definition at line 131 of file ControlLayout.h.
Referenced by ControlLayout(), and verticalSpacing().
s_searchBarName
const char* lmms::gui::ControlLayout::s_searchBarName = "!!searchBar!!" static constexpr private
name of search bar, must be ASCII sorted before any alpha numerics
Definition at line 137 of file ControlLayout.h.
Referenced by ControlLayout(), and pairAt().
The documentation for this class was generated from the following files:
include/ControlLayout.h
src/gui/ControlLayout.cpp