LMMS: src/3rdparty/jack2/solaris/oss/JackBoomerDriver.cpp File Reference
JackBoomerDriver.cpp File Reference
#include "driver_interface.h"
#include "JackThreadedDriver.h"
#include "JackDriverLoader.h"
#include "JackBoomerDriver.h"
#include "JackEngineControl.h"
#include "JackGraphManager.h"
#include "JackError.h"
#include "JackTime.h"
#include "JackShmMem.h"
#include "JackGlobals.h"
#include "memops.h"
#include <sys/ioctl.h>
#include <sys/soundcard.h>
#include <fcntl.h>
#include <iostream>
#include <assert.h>
#include <stdio.h>
Namespaces
namespace Jack
Functions
static void Jack::CopyAndConvertIn (jack_sample_t *dst, void *src, size_t nframes, int channel, int byte_skip, int bits)
static void Jack::CopyAndConvertOut (void *dst, jack_sample_t *src, size_t nframes, int channel, int byte_skip, int bits)
SERVER_EXPORT jack_driver_desc_t * driver_get_descriptor ()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine *engine, Jack::JackSynchro *table, const JSList *params)
int Jack::int2pow2 (int x)
Function Documentation
driver_get_descriptor()
SERVER_EXPORT jack_driver_desc_t * driver_get_descriptor ()
Definition at line 818 of file JackBoomerDriver.cpp.
References jack_driver_param_value_t::i, jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverMaster, JackDriverParamBool, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, OSS_DRIVER_DEF_BITS, OSS_DRIVER_DEF_BLKSIZE, OSS_DRIVER_DEF_DEV, OSS_DRIVER_DEF_FS, OSS_DRIVER_DEF_INS, OSS_DRIVER_DEF_NPERIODS, OSS_DRIVER_DEF_OUTS, SERVER_EXPORT, jack_driver_param_value_t::str, and jack_driver_param_value_t::ui.
driver_initialize()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine * engine, Jack::JackSynchro * table, const JSList * params)
Definition at line 862 of file JackBoomerDriver.cpp.
References jack_driver_param_t::character, _JSList::data, jack_driver_param_value_t::i, jack_slist_next, Jack::JackBoomerDriver::Open(), OSS_DRIVER_DEF_BITS, OSS_DRIVER_DEF_BLKSIZE, OSS_DRIVER_DEF_DEV, OSS_DRIVER_DEF_FS, OSS_DRIVER_DEF_NPERIODS, SERVER_EXPORT, jack_driver_param_value_t::str, jack_driver_param_value_t::ui, and jack_driver_param_t::value.