LMMS: lmms::PresetPreviewPlayHandle Class Reference
lmms::PresetPreviewPlayHandle Class Reference
#include <PresetPreviewPlayHandle.h>
Public Member Functions
PresetPreviewPlayHandle (const QString &presetFile, bool loadByPlugin=false, DataFile *dataFile=0)
~PresetPreviewPlayHandle () override
bool affinityMatters () const override
bool isFinished () const override
bool isFromTrack (const Track *_track) const override
void play (SampleFrame *buffer) override
Public Member Functions inherited from lmms::PlayHandle
PlayHandle (const Type type, f_cnt_t offset=0)
virtual ~PlayHandle ()
const QThread * affinity () const
AudioBusHandle * audioBusHandle ()
SampleFrame * buffer ()
void doProcessing () override
void lock ()
f_cnt_t offset () const
PlayHandle & operator= (PlayHandle &p)
void releaseBuffer ()
bool requiresProcessing () const override
void setAudioBusHandle (AudioBusHandle *busHandle)
void setOffset (f_cnt_t _offset)
void setUsesBuffer (const bool b)
bool tryLock ()
Type type () const
void unlock ()
bool usesBuffer () const
Public Member Functions inherited from lmms::ThreadableJob
ThreadableJob ()
void done ()
void process ()
void queue ()
void reset ()
ProcessingState state () const
Static Public Member Functions
static void cleanup ()
static void init ()
static bool isPreviewing ()
static ConstNotePlayHandleList nphsOfInstrumentTrack (const InstrumentTrack *instrumentTrack)
Private Attributes
NotePlayHandle * m_previewNote
Static Private Attributes
static PreviewTrackContainer * s_previewTC
Additional Inherited Members
Public Types inherited from lmms::PlayHandle
enum class Type {
NotePlayHandle = 0x01 ,
InstrumentPlayHandle = 0x02 ,
SamplePlayHandle = 0x04 ,
PresetPreviewHandle = 0x08
}
using Types = Flags<Type>
Public Types inherited from lmms::ThreadableJob
enum class ProcessingState : int {
Unstarted ,
Queued ,
InProgress ,
Done
}
Static Public Attributes inherited from lmms::PlayHandle
static constexpr std::size_t MaxNumber = 1024
Protected Attributes inherited from lmms::ThreadableJob
std::atomic< ProcessingState > m_state
Detailed Description
Definition at line 39 of file PresetPreviewPlayHandle.h.
Constructor & Destructor Documentation
PresetPreviewPlayHandle()
lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle (const QString & presetFile, bool loadByPlugin = false, DataFile * dataFile = 0)
Definition at line 118 of file PresetPreviewPlayHandle.cpp.
References lmms::PlayHandle::PlayHandle(), lmms::NotePlayHandleManager::acquire(), lmms::AudioEngine::addPlayHandle(), lmms::Engine::audioEngine(), lmms::DataFile::content(), lmms::DefaultKey, lmms::MidiPort::Disabled, lmms::AudioEngine::doneChangeInModel(), lmms::getPluginFactory(), i, lmms::PluginFactory::PluginInfoAndKey::info, lmms::ProjectJournal::isJournalling(), j, lmms::PluginFactory::PluginInfoAndKey::key, m_previewNote, lmms::PluginFactory::PluginInfo::name(), lmms::PluginFactory::pluginSupportingExtension(), lmms::Engine::projectJournal(), lmms::AudioEngine::requestChangeInModel(), s_previewTC, lmms::PlayHandle::setAudioBusHandle(), lmms::ProjectJournal::setJournalling(), and lmms::PlayHandle::setUsesBuffer().
~PresetPreviewPlayHandle()
lmms::PresetPreviewPlayHandle::~PresetPreviewPlayHandle () override
Definition at line 195 of file PresetPreviewPlayHandle.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), m_previewNote, lmms::AudioEngine::requestChangeInModel(), and s_previewTC.
Member Function Documentation
affinityMatters()
bool lmms::PresetPreviewPlayHandle::affinityMatters () const inline override virtual
Reimplemented from lmms::PlayHandle.
Definition at line 45 of file PresetPreviewPlayHandle.h.
cleanup()
void lmms::PresetPreviewPlayHandle::cleanup () static
Definition at line 245 of file PresetPreviewPlayHandle.cpp.
References s_previewTC.
Referenced by lmms::Engine::destroy().
init()
void lmms::PresetPreviewPlayHandle::init () static
Definition at line 234 of file PresetPreviewPlayHandle.cpp.
References s_previewTC.
Referenced by lmms::Engine::init().
isFinished()
bool lmms::PresetPreviewPlayHandle::isFinished () const override virtual
Implements lmms::PlayHandle.
Definition at line 218 of file PresetPreviewPlayHandle.cpp.
References m_previewNote.
isFromTrack()
bool lmms::PresetPreviewPlayHandle::isFromTrack (const Track * _track) const override virtual
Implements lmms::PlayHandle.
Definition at line 226 of file PresetPreviewPlayHandle.cpp.
References s_previewTC.
isPreviewing()
bool lmms::PresetPreviewPlayHandle::isPreviewing () static
Definition at line 269 of file PresetPreviewPlayHandle.cpp.
References s_previewTC.
nphsOfInstrumentTrack()
ConstNotePlayHandleList lmms::PresetPreviewPlayHandle::nphsOfInstrumentTrack (const InstrumentTrack * instrumentTrack) static
Definition at line 254 of file PresetPreviewPlayHandle.cpp.
References s_previewTC.
Referenced by lmms::InstrumentFunctionArpeggio::processNote().
play()
void lmms::PresetPreviewPlayHandle::play (SampleFrame * buffer) override virtual
Implements lmms::PlayHandle.
Definition at line 209 of file PresetPreviewPlayHandle.cpp.
Member Data Documentation
m_previewNote
NotePlayHandle* lmms::PresetPreviewPlayHandle::m_previewNote private
Definition at line 65 of file PresetPreviewPlayHandle.h.
Referenced by PresetPreviewPlayHandle(), ~PresetPreviewPlayHandle(), and isFinished().
s_previewTC
PreviewTrackContainer * lmms::PresetPreviewPlayHandle::s_previewTC static private
Definition at line 63 of file PresetPreviewPlayHandle.h.
Referenced by PresetPreviewPlayHandle(), ~PresetPreviewPlayHandle(), cleanup(), init(), isFromTrack(), isPreviewing(), and nphsOfInstrumentTrack().
The documentation for this class was generated from the following files:
include/PresetPreviewPlayHandle.h
src/core/PresetPreviewPlayHandle.cpp