LMMS: Jack::JackAndroidThread Class Reference
Jack::JackAndroidThread Class Reference
The POSIX thread base class.
#include <JackAndroidThread.h>
Public Member Functions
JackAndroidThread (JackRunnableInterface *runnable, bool real_time, int priority, int cancellation)
JackAndroidThread (JackRunnableInterface *runnable, int cancellation=PTHREAD_CANCEL_ASYNCHRONOUS)
int AcquireRealTime ()
int AcquireRealTime (int priority)
int AcquireSelfRealTime ()
int AcquireSelfRealTime (int priority)
int DropRealTime ()
int DropSelfRealTime ()
jack_native_thread_t GetThreadID ()
bool IsThread ()
int Kill ()
int Start ()
int StartSync ()
int Stop ()
void Terminate ()
Public Member Functions inherited from Jack::detail::JackThreadInterface
JackThreadInterface (JackRunnableInterface *runnable, int priority, bool real_time, int cancellation)
int AcquireRealTime ()
int AcquireRealTime (int priority)
int AcquireSelfRealTime ()
int AcquireSelfRealTime (int priority)
int DropRealTime ()
int DropSelfRealTime ()
kThreadState GetStatus ()
jack_native_thread_t GetThreadID ()
bool IsThread ()
int Kill ()
void SetParams (UInt64 period, UInt64 computation, UInt64 constraint)
void SetStatus (kThreadState status)
int Start ()
int StartSync ()
int Stop ()
void Terminate ()
Static Public Member Functions
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority)
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint)
static int DropRealTimeImp (jack_native_thread_t thread)
static int KillImp (jack_native_thread_t thread)
static int StartImp (jack_native_thread_t *thread, int priority, int realtime, void *(*start_routine)(void *), void *arg)
static int StopImp (jack_native_thread_t thread)
Static Public Member Functions inherited from Jack::detail::JackThreadInterface
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority)
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint)
static int DropRealTimeImp (jack_native_thread_t thread)
static int KillImp (jack_native_thread_t thread)
static int StartImp (jack_native_thread_t *thread, int priority, int realtime, void *(*start_routine)(void *), void *arg)
static int StopImp (jack_native_thread_t thread)
Static Protected Member Functions
static void thread_exit_handler (int sig)
static void * ThreadHandler (void *arg)
Protected Attributes
jack_native_thread_t fThread
Protected Attributes inherited from Jack::detail::JackThreadInterface
int fCancellation
int fPriority
bool fRealTime
JackRunnableInterface * fRunnable
volatile kThreadState fStatus
Additional Inherited Members
Public Types inherited from Jack::detail::JackThreadInterface
enum kThreadState {
kIdle ,
kStarting ,
kIniting ,
kRunning
}
Detailed Description
The POSIX thread base class.
Definition at line 45 of file JackAndroidThread.h.
Constructor & Destructor Documentation
JackAndroidThread() [1/2]
Jack::JackAndroidThread::JackAndroidThread (JackRunnableInterface * runnable, bool real_time, int priority, int cancellation) inline
Definition at line 56 of file JackAndroidThread.h.
References Jack::detail::JackThreadInterface::JackThreadInterface(), and fThread.
Referenced by ThreadHandler().
JackAndroidThread() [2/2]
Jack::JackAndroidThread::JackAndroidThread (JackRunnableInterface * runnable, int cancellation = PTHREAD_CANCEL_ASYNCHRONOUS) inline
Definition at line 59 of file JackAndroidThread.h.
References Jack::detail::JackThreadInterface::JackThreadInterface(), fThread, and Jack::PTHREAD_CANCEL_ASYNCHRONOUS.
Member Function Documentation
AcquireRealTime() [1/2]
int Jack::JackAndroidThread::AcquireRealTime ()
Definition at line 218 of file JackAndroidThread.cpp.
References AcquireRealTimeImp(), Jack::detail::JackThreadInterface::fPriority, and fThread.
Referenced by AcquireRealTime(), and main().
AcquireRealTime() [2/2]
int Jack::JackAndroidThread::AcquireRealTime (int priority)
Definition at line 228 of file JackAndroidThread.cpp.
References AcquireRealTime(), and Jack::detail::JackThreadInterface::fPriority.
AcquireRealTimeImp() [1/2]
int Jack::JackAndroidThread::AcquireRealTimeImp (jack_native_thread_t thread, int priority) static
Definition at line 239 of file JackAndroidThread.cpp.
References jack_error, jack_log(), and JACK_SCHED_POLICY.
Referenced by AcquireRealTime(), AcquireRealTimeImp(), AcquireSelfRealTime(), jack_acquire_real_time_scheduling(), and jack_client_create_thread().
AcquireRealTimeImp() [2/2]
int Jack::JackAndroidThread::AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint) inline static
Definition at line 82 of file JackAndroidThread.h.
References AcquireRealTimeImp().
AcquireSelfRealTime() [1/2]
int Jack::JackAndroidThread::AcquireSelfRealTime ()
Definition at line 223 of file JackAndroidThread.cpp.
References AcquireRealTimeImp(), and Jack::detail::JackThreadInterface::fPriority.
Referenced by AcquireSelfRealTime().
AcquireSelfRealTime() [2/2]
int Jack::JackAndroidThread::AcquireSelfRealTime (int priority)
Definition at line 234 of file JackAndroidThread.cpp.
References AcquireSelfRealTime(), and Jack::detail::JackThreadInterface::fPriority.
DropRealTime()
int Jack::JackAndroidThread::DropRealTime ()
Definition at line 265 of file JackAndroidThread.cpp.
References DropRealTimeImp(), and fThread.
DropRealTimeImp()
int Jack::JackAndroidThread::DropRealTimeImp (jack_native_thread_t thread) static
Definition at line 275 of file JackAndroidThread.cpp.
References jack_error.
Referenced by DropRealTime(), DropSelfRealTime(), and jack_drop_real_time_scheduling().
DropSelfRealTime()
int Jack::JackAndroidThread::DropSelfRealTime ()
Definition at line 270 of file JackAndroidThread.cpp.
References DropRealTimeImp().
GetThreadID()
jack_native_thread_t Jack::JackAndroidThread::GetThreadID ()
Definition at line 289 of file JackAndroidThread.cpp.
References fThread.
IsThread()
bool Jack::JackAndroidThread::IsThread ()
Definition at line 294 of file JackAndroidThread.cpp.
References fThread.
Kill()
int Jack::JackAndroidThread::Kill ()
Definition at line 163 of file JackAndroidThread.cpp.
References Jack::detail::JackThreadInterface::fStatus, fThread, jack_log(), and Jack::detail::JackThreadInterface::kIdle.
Referenced by main().
KillImp()
int Jack::JackAndroidThread::KillImp (jack_native_thread_t thread) static
Definition at line 193 of file JackAndroidThread.cpp.
References jack_log().
Referenced by jack_client_kill_thread().
Start()
int Jack::JackAndroidThread::Start ()
Definition at line 75 of file JackAndroidThread.cpp.
References Jack::detail::JackThreadInterface::fPriority, Jack::detail::JackThreadInterface::fRealTime, Jack::detail::JackThreadInterface::fStatus, fThread, Jack::detail::JackThreadInterface::kIdle, Jack::detail::JackThreadInterface::kStarting, StartImp(), and ThreadHandler().
Referenced by main(), and run_tests().
StartImp()
int Jack::JackAndroidThread::StartImp (jack_native_thread_t * thread, int priority, int realtime, void *(* start_routine)(void *), void * arg) static
Definition at line 104 of file JackAndroidThread.cpp.
References Jack::JackGlobals::fJackThreadCreator, jack_error, jack_log(), JACK_SCHED_POLICY, thread_exit_handler(), and THREAD_STACK.
Referenced by Jack::JackAlsaDriver::create_thread(), jack_client_create_thread(), Start(), and StartSync().
StartSync()
int Jack::JackAndroidThread::StartSync ()
Definition at line 88 of file JackAndroidThread.cpp.
References Jack::detail::JackThreadInterface::fPriority, Jack::detail::JackThreadInterface::fRealTime, Jack::detail::JackThreadInterface::fStatus, fThread, JackSleep(), Jack::detail::JackThreadInterface::kIdle, Jack::detail::JackThreadInterface::kStarting, StartImp(), and ThreadHandler().
Stop()
int Jack::JackAndroidThread::Stop ()
Definition at line 179 of file JackAndroidThread.cpp.
References Jack::detail::JackThreadInterface::fStatus, fThread, jack_log(), and Jack::detail::JackThreadInterface::kIdle.
Referenced by main(), and run_tests().
StopImp()
int Jack::JackAndroidThread::StopImp (jack_native_thread_t thread) static
Definition at line 206 of file JackAndroidThread.cpp.
References jack_log().
Referenced by jack_client_stop_thread().
Terminate()
void Jack::JackAndroidThread::Terminate ()
Definition at line 299 of file JackAndroidThread.cpp.
References jack_log().
thread_exit_handler()
void Jack::JackAndroidThread::thread_exit_handler (int sig) static protected
Definition at line 40 of file JackAndroidThread.cpp.
Referenced by StartImp().
ThreadHandler()
void * Jack::JackAndroidThread::ThreadHandler (void * arg) static protected
Definition at line 46 of file JackAndroidThread.cpp.
References JackAndroidThread(), Jack::JackRunnableInterface::Execute(), Jack::detail::JackThreadInterface::fRunnable, Jack::detail::JackThreadInterface::fStatus, Jack::JackRunnableInterface::Init(), jack_error, jack_log(), Jack::detail::JackThreadInterface::kIniting, and Jack::detail::JackThreadInterface::kRunning.
Referenced by Start(), and StartSync().
Member Data Documentation
fThread
jack_native_thread_t Jack::JackAndroidThread::fThread protected
Definition at line 50 of file JackAndroidThread.h.
Referenced by JackAndroidThread(), JackAndroidThread(), AcquireRealTime(), DropRealTime(), GetThreadID(), IsThread(), Kill(), Start(), StartSync(), and Stop().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/android/JackAndroidThread.h
src/3rdparty/jack2/android/JackAndroidThread.cpp