LMMS: lmms::gui::TempoSyncBarModelEditor Class Reference
lmms::gui::TempoSyncBarModelEditor Class Reference
#include <TempoSyncBarModelEditor.h>
Signals
void syncDescriptionChanged (const QString &new_description)
void syncIconChanged ()
Signals inherited from lmms::gui::FloatModelEditorBase
void sliderMoved (float value)
void sliderPressed ()
void sliderReleased ()
Public Member Functions
TempoSyncBarModelEditor (QString text, FloatModel *floatModel, QWidget *parent=nullptr)
~TempoSyncBarModelEditor () override
TempoSyncKnobModel * model ()
void modelChanged () override
void setSyncDescription (const QString &new_description)
void setSyncIcon (const QPixmap &new_pix)
const QString & syncDescription ()
const QPixmap & syncIcon ()
Public Member Functions inherited from lmms::gui::BarModelEditor
BarModelEditor (QString text, FloatModel *floatModel, QWidget *parent=nullptr)
QBrush const & getBackgroundBrush () const
QBrush const & getBarBrush () const
QColor const & getTextColor () const
QSize minimumSizeHint () const override
void setBackgroundBrush (QBrush const &backgroundBrush)
void setBarBrush (QBrush const &barBrush)
void setTextColor (QColor const &textColor)
QSize sizeHint () const override
QSizePolicy sizePolicy () const
Public Member Functions inherited from lmms::gui::FloatModelEditorBase
FloatModelEditorBase (const FloatModelEditorBase &other)=delete
FloatModelEditorBase (DirectionOfManipulation directionOfManipulation=DirectionOfManipulation::Vertical, QWidget *_parent=nullptr, const QString &_name=QString())
default ctor
void setHintText (const QString &txt_before, const QString &txt_after)
Public Member Functions inherited from lmms::gui::TypedModelView< FloatModel >
TypedModelView (Model *model, QWidget *_this)
FloatModel * model ()
const FloatModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Slots
void showCustom ()
void updateDescAndIcon ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *me) override
Protected Member Functions inherited from lmms::gui::BarModelEditor
void paintEvent (QPaintEvent *event) override
Protected Member Functions inherited from lmms::gui::FloatModelEditorBase
void contextMenuEvent (QContextMenuEvent *me) override
virtual QString displayValue () const
void doConnections () override
void dragEnterEvent (QDragEnterEvent *dee) override
void dropEvent (QDropEvent *de) override
void enterEvent (QEvent *event) override
void focusOutEvent (QFocusEvent *fe) override
virtual float getValue (const QPoint &p)
void leaveEvent (QEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
float pageSize () const
void paintEvent (QPaintEvent *me) override
void setPosition (const QPoint &p)
void showTextFloat (int msecBeforeDisplay, int msecDisplayTime)
void wheelEvent (QWheelEvent *me) override
Protected Member Functions inherited from lmms::gui::ModelView
QWidget * widget ()
Private Member Functions
void updateIcon ()
void updateTextDescription ()
Private Attributes
QPointer< MeterDialog > m_custom
QString m_tempoSyncDescription
QPixmap m_tempoSyncIcon
Additional Inherited Members
Public Types inherited from lmms::gui::FloatModelEditorBase
enum class DirectionOfManipulation {
Vertical ,
Horizontal
}
Protected Attributes inherited from lmms::gui::FloatModelEditorBase
bool m_buttonPressed
DirectionOfManipulation m_directionOfManipulation
QPoint m_lastMousePos
mouse position in last mouseMoveEvent
float m_leftOver
BoolModel m_volumeKnob
FloatModel m_volumeRatio
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Static Protected Attributes inherited from lmms::gui::FloatModelEditorBase
static SimpleTextFloat * s_textFloat = nullptr
Properties inherited from lmms::gui::BarModelEditor
QBrush backgroundBrush
QBrush barBrush
QColor textColor
Detailed Description
Definition at line 41 of file TempoSyncBarModelEditor.h.
Constructor & Destructor Documentation
TempoSyncBarModelEditor()
lmms::gui::TempoSyncBarModelEditor::TempoSyncBarModelEditor (QString text, FloatModel * floatModel, QWidget * parent = nullptr)
Definition at line 44 of file TempoSyncBarModelEditor.cpp.
References lmms::gui::BarModelEditor::BarModelEditor(), m_custom, m_tempoSyncDescription, m_tempoSyncIcon, and modelChanged().
~TempoSyncBarModelEditor()
lmms::gui::TempoSyncBarModelEditor::~TempoSyncBarModelEditor () override
Definition at line 54 of file TempoSyncBarModelEditor.cpp.
References m_custom.
Member Function Documentation
contextMenuEvent()
void lmms::gui::TempoSyncBarModelEditor::contextMenuEvent (QContextMenuEvent * me) override protected
Definition at line 84 of file TempoSyncBarModelEditor.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), lmms::TempoSyncKnobModel::Custom, lmms::Model::displayName(), lmms::TempoSyncKnobModel::DoubleWholeNote, lmms::TempoSyncKnobModel::EighthNote, lmms::embed::getIconPixmap(), lmms::Engine::getSong(), lmms::Song::getTempo(), lmms::TempoSyncKnobModel::HalfNote, m_tempoSyncDescription, m_tempoSyncIcon, lmms::TypedAutomatableModel< T >::maxValue(), model(), lmms::gui::FloatModelEditorBase::mouseReleaseEvent(), lmms::TempoSyncKnobModel::None, lmms::TempoSyncKnobModel::QuarterNote, lmms::TempoSyncKnobModel::scale(), showCustom(), lmms::TempoSyncKnobModel::SixteenthNote, lmms::TempoSyncKnobModel::ThirtysecondNote, lmms::gui::FloatModelEditorBase::toggleScale(), and lmms::TempoSyncKnobModel::WholeNote.
Referenced by syncIconChanged().
model()
TempoSyncKnobModel * lmms::gui::TempoSyncBarModelEditor::model () inline
Definition at line 54 of file TempoSyncBarModelEditor.h.
References lmms::gui::ModelView::castModel().
Referenced by contextMenuEvent(), modelChanged(), showCustom(), updateDescAndIcon(), updateIcon(), and updateTextDescription().
modelChanged()
void lmms::gui::TempoSyncBarModelEditor::modelChanged () override virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 63 of file TempoSyncBarModelEditor.cpp.
References lmms::TempoSyncKnobModel::getCustomMeterModel(), m_custom, model(), lmms::gui::FloatModelEditorBase::sliderMoved(), lmms::TempoSyncKnobModel::syncModeChanged(), and updateDescAndIcon().
Referenced by TempoSyncBarModelEditor().
setSyncDescription()
void lmms::gui::TempoSyncBarModelEditor::setSyncDescription (const QString & new_description)
Definition at line 183 of file TempoSyncBarModelEditor.cpp.
References m_tempoSyncDescription, and syncDescriptionChanged().
setSyncIcon()
void lmms::gui::TempoSyncBarModelEditor::setSyncIcon (const QPixmap & new_pix)
Definition at line 196 of file TempoSyncBarModelEditor.cpp.
References m_tempoSyncIcon, and syncIconChanged().
showCustom
void lmms::gui::TempoSyncBarModelEditor::showCustom () protected slot
Definition at line 203 of file TempoSyncBarModelEditor.cpp.
References lmms::gui::MainWindow::addWindowedWidget(), lmms::TempoSyncKnobModel::Custom, lmms::gui::getGUI(), m_custom, lmms::gui::GuiApplication::mainWindow(), model(), and lmms::TempoSyncKnobModel::setTempoSync().
Referenced by contextMenuEvent(), and syncIconChanged().
syncDescription()
const QString & lmms::gui::TempoSyncBarModelEditor::syncDescription ()
Definition at line 177 of file TempoSyncBarModelEditor.cpp.
References m_tempoSyncDescription.
syncDescriptionChanged
void lmms::gui::TempoSyncBarModelEditor::syncDescriptionChanged (const QString & new_description) signal
Referenced by setSyncDescription(), and updateDescAndIcon().
syncIcon()
const QPixmap & lmms::gui::TempoSyncBarModelEditor::syncIcon ()
Definition at line 190 of file TempoSyncBarModelEditor.cpp.
References m_tempoSyncIcon.
syncIconChanged
void lmms::gui::TempoSyncBarModelEditor::syncIconChanged () signal
References contextMenuEvent(), showCustom(), updateDescAndIcon(), updateIcon(), and updateTextDescription().
Referenced by setSyncIcon(), and updateDescAndIcon().
updateDescAndIcon
void lmms::gui::TempoSyncBarModelEditor::updateDescAndIcon () protected slot
Definition at line 161 of file TempoSyncBarModelEditor.cpp.
References lmms::TempoSyncKnobModel::Custom, m_custom, m_tempoSyncDescription, model(), syncDescriptionChanged(), syncIconChanged(), updateIcon(), and updateTextDescription().
Referenced by modelChanged(), and syncIconChanged().
updateIcon()
void lmms::gui::TempoSyncBarModelEditor::updateIcon () private
Definition at line 266 of file TempoSyncBarModelEditor.cpp.
References lmms::TempoSyncKnobModel::Custom, lmms::TempoSyncKnobModel::DoubleWholeNote, lmms::TempoSyncKnobModel::EighthNote, lmms::embed::getIconPixmap(), lmms::TempoSyncKnobModel::HalfNote, m_tempoSyncIcon, model(), lmms::TempoSyncKnobModel::None, lmms::TempoSyncKnobModel::QuarterNote, lmms::TempoSyncKnobModel::SixteenthNote, lmms::TempoSyncKnobModel::ThirtysecondNote, and lmms::TempoSyncKnobModel::WholeNote.
Referenced by syncIconChanged(), and updateDescAndIcon().
updateTextDescription()
void lmms::gui::TempoSyncBarModelEditor::updateTextDescription () private
Definition at line 222 of file TempoSyncBarModelEditor.cpp.
References lmms::TempoSyncKnobModel::Custom, lmms::MeterModel::denominatorModel(), lmms::TempoSyncKnobModel::DoubleWholeNote, lmms::TempoSyncKnobModel::EighthNote, lmms::TempoSyncKnobModel::getCustomMeterModel(), lmms::TempoSyncKnobModel::HalfNote, m_tempoSyncDescription, model(), lmms::TempoSyncKnobModel::None, lmms::MeterModel::numeratorModel(), lmms::TempoSyncKnobModel::QuarterNote, lmms::TempoSyncKnobModel::SixteenthNote, lmms::TempoSyncKnobModel::syncMode(), lmms::TempoSyncKnobModel::ThirtysecondNote, lmms::TypedAutomatableModel< T >::value(), and lmms::TempoSyncKnobModel::WholeNote.
Referenced by syncIconChanged(), and updateDescAndIcon().
Member Data Documentation
m_custom
QPointer<MeterDialog> lmms::gui::TempoSyncBarModelEditor::m_custom private
Definition at line 85 of file TempoSyncBarModelEditor.h.
Referenced by TempoSyncBarModelEditor(), ~TempoSyncBarModelEditor(), modelChanged(), showCustom(), and updateDescAndIcon().
m_tempoSyncDescription
QString lmms::gui::TempoSyncBarModelEditor::m_tempoSyncDescription private
Definition at line 83 of file TempoSyncBarModelEditor.h.
Referenced by TempoSyncBarModelEditor(), contextMenuEvent(), setSyncDescription(), syncDescription(), updateDescAndIcon(), and updateTextDescription().
m_tempoSyncIcon
QPixmap lmms::gui::TempoSyncBarModelEditor::m_tempoSyncIcon private
Definition at line 82 of file TempoSyncBarModelEditor.h.
Referenced by TempoSyncBarModelEditor(), contextMenuEvent(), setSyncIcon(), syncIcon(), and updateIcon().
The documentation for this class was generated from the following files:
include/TempoSyncBarModelEditor.h
src/gui/widgets/TempoSyncBarModelEditor.cpp