LMMS: Jack::JackArgParser Class Reference
Jack::JackArgParser Class Reference
#include <JackArgParser.h>
Public Member Functions
JackArgParser (const char *arg)
~JackArgParser ()
void DeleteArgv (const char **argv)
void FreeParams (JSList *param_list)
int GetArgc ()
std::string GetArgString ()
int GetArgv (char **argv)
int GetArgv (std::vector< std::string > &argv)
int GetNumArgv ()
bool ParseParams (jack_driver_desc_t *desc, JSList **param_list)
Private Attributes
int fArgc
std::string fArgString
std::vector< std::string > fArgv
Detailed Description
Definition at line 37 of file JackArgParser.h.
Constructor & Destructor Documentation
JackArgParser()
Jack::JackArgParser::JackArgParser (const char * arg)
Definition at line 31 of file JackArgParser.cpp.
References fArgc, fArgString, fArgv, i, jack_log(), and pos.
~JackArgParser()
Jack::JackArgParser::~JackArgParser ()
Definition at line 100 of file JackArgParser.cpp.
Member Function Documentation
DeleteArgv()
void Jack::JackArgParser::DeleteArgv (const char ** argv)
Definition at line 144 of file JackArgParser.cpp.
References fArgv, and i.
FreeParams()
void Jack::JackArgParser::FreeParams (JSList * param_list)
Definition at line 221 of file JackArgParser.cpp.
References _JSList::data, and _JSList::next.
Referenced by jack_initialize().
GetArgc()
int Jack::JackArgParser::GetArgc ()
Definition at line 113 of file JackArgParser.cpp.
References fArgc.
Referenced by jack_initialize().
GetArgString()
string Jack::JackArgParser::GetArgString ()
Definition at line 103 of file JackArgParser.cpp.
References fArgString.
GetArgv() [1/2]
int Jack::JackArgParser::GetArgv (char ** argv)
Definition at line 124 of file JackArgParser.cpp.
References fArgv, and i.
GetArgv() [2/2]
int Jack::JackArgParser::GetArgv (std::vector< std::string > & argv)
Definition at line 118 of file JackArgParser.cpp.
References fArgv.
GetNumArgv()
int Jack::JackArgParser::GetNumArgv ()
Definition at line 108 of file JackArgParser.cpp.
References fArgv.
ParseParams()
bool Jack::JackArgParser::ParseParams (jack_driver_desc_t * desc, JSList ** param_list)
Definition at line 152 of file JackArgParser.cpp.
References jack_driver_param_value_t::c, jack_driver_param_desc_t::character, jack_driver_param_t::character, fArgv, i, jack_driver_param_value_t::i, JACK_DRIVER_PARAM_STRING_MAX, jack_error, jack_print_driver_options(), jack_slist_append(), JackDriverParamBool, JackDriverParamChar, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, min, jack_driver_desc_t::nparams, jack_driver_desc_t::params, jack_driver_param_value_t::str, jack_driver_param_desc_t::type, jack_driver_param_value_t::ui, and jack_driver_param_t::value.
Referenced by jack_initialize().
Member Data Documentation
fArgc
int Jack::JackArgParser::fArgc private
Definition at line 42 of file JackArgParser.h.
Referenced by JackArgParser(), and GetArgc().
fArgString
std::string Jack::JackArgParser::fArgString private
Definition at line 41 of file JackArgParser.h.
Referenced by JackArgParser(), and GetArgString().
fArgv
std::vector<std::string> Jack::JackArgParser::fArgv private
Definition at line 43 of file JackArgParser.h.
Referenced by JackArgParser(), DeleteArgv(), GetArgv(), GetArgv(), GetNumArgv(), and ParseParams().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackArgParser.h
src/3rdparty/jack2/common/JackArgParser.cpp