LMMS: lmms::DummyInstrument Class Reference
lmms::DummyInstrument Class Reference
#include <DummyInstrument.h>
Public Member Functions
DummyInstrument (InstrumentTrack *_instrument_track)
~DummyInstrument () override=default
gui::PluginView * instantiateView (QWidget *_parent) override
Create a view for the model.
void loadSettings (const QDomElement &) override
QString nodeName () const override
void playNote (NotePlayHandle *, SampleFrame *buffer) override
void saveSettings (QDomDocument &, QDomElement &) override
Public Member Functions inherited from lmms::Instrument
Instrument (InstrumentTrack *_instrument_track, const Descriptor *_descriptor, const Descriptor::SubPluginFeatures::Key *key=nullptr, Flags flags=Flag::NoFlags)
~Instrument () override=default
virtual f_cnt_t beatLen (NotePlayHandle *_n) const
virtual void deleteNotePluginData (NotePlayHandle *_note_to_play)
f_cnt_t desiredReleaseFrames () const
virtual float desiredReleaseTimeMs () const
QString fullDisplayName () const override
sample_rate_t getSampleRate () const
virtual bool handleMidiEvent (const MidiEvent &, const TimePos &=TimePos(), f_cnt_t offset=0)
virtual bool hasNoteInput () const
InstrumentTrack * instrumentTrack () const
bool isBendable () const
virtual bool isFromTrack (const Track *_track) const
bool isMidiBased () const
bool isSingleStreamed () const
virtual void play (SampleFrame *_working_buffer)
Public Member Functions inherited from lmms::Plugin
Plugin (const Descriptor *descriptor, Model *parent, const Descriptor::SubPluginFeatures::Key *key=nullptr)
Constructor of a plugin.
~Plugin () override=default
virtual AutomatableModel * childModel (const QString &modelName)
Called if external source needs to change something but we cannot reference the class header.
gui::PluginView * createView (QWidget *parent)
Create a view for the model.
const Descriptor * descriptor () const
Return plugin Descriptor.
QString displayName () const override
Return display-name out of sub plugin or descriptor.
const Descriptor::SubPluginFeatures::Key & key () const
Return the key referencing this plugin.
virtual void loadFile (const QString &file)
Can be called if a file matching supportedFileTypes should be loaded/processed with the help of this plugin.
const PixmapLoader * logo () const
Return logo out of sub plugin or descriptor.
Type type () const
Return plugin type.
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Additional Inherited Members
Public Types inherited from lmms::Instrument
enum class Flag {
NoFlags = 0x00 ,
IsSingleStreamed = 0x01 ,
IsMidiBased = 0x02 ,
IsNotBendable = 0x04
}
using Flags = lmms::Flags<Flag>
Public Types inherited from lmms::Plugin
using DescriptorList = QList<Descriptor*>
enum class Type {
Instrument ,
Effect ,
ImportFilter ,
ExportFilter ,
Tool ,
Library ,
Other ,
Undefined = 255
}
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Public Member Functions inherited from lmms::Instrument
static Instrument * instantiate (const QString &_plugin_name, InstrumentTrack *_instrument_track, const Plugin::Descriptor::SubPluginFeatures::Key *key, bool keyFromDnd=false)
instantiate instrument-plugin with given name or return NULL on failure
Static Public Member Functions inherited from lmms::Plugin
static Plugin * instantiate (const QString &pluginName, Model *parent, void *data)
Return an instance of a plugin whose name matches to given one if specified plugin couldn't be loaded, it creates a dummy-plugin.
static Plugin * instantiateWithKey (const QString &pluginName, Model *parent, const Descriptor::SubPluginFeatures::Key *key, bool keyFromDnd=false)
Overload if the argument passed to the plugin is a subPluginKey If you can not pass the key and are aware that it's stored in Engine::pickDndPluginKey(), use this function, too.
Protected Member Functions inherited from lmms::Instrument
void applyFadeIn (SampleFrame *buf, NotePlayHandle *n)
void applyRelease (SampleFrame *buf, const NotePlayHandle *_n)
float computeReleaseTimeMsByFrameCount (f_cnt_t frames) const
Protected Member Functions inherited from lmms::Plugin
void collectErrorForUI (QString errMsg)
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 42 of file DummyInstrument.h.
Constructor & Destructor Documentation
DummyInstrument()
lmms::DummyInstrument::DummyInstrument (InstrumentTrack * _instrument_track) inline
Definition at line 45 of file DummyInstrument.h.
References lmms::Instrument::Instrument().
~DummyInstrument()
lmms::DummyInstrument::~DummyInstrument () override default
Member Function Documentation
instantiateView()
gui::PluginView * lmms::DummyInstrument::instantiateView (QWidget *) inline override virtual
Create a view for the model.
Implements lmms::Plugin.
Definition at line 70 of file DummyInstrument.h.
loadSettings()
void lmms::DummyInstrument::loadSettings (const QDomElement &) inline override virtual
Implements lmms::SerializingObject.
Definition at line 61 of file DummyInstrument.h.
nodeName()
QString lmms::DummyInstrument::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 65 of file DummyInstrument.h.
playNote()
void lmms::DummyInstrument::playNote (NotePlayHandle * , SampleFrame * buffer) inline override virtual
Reimplemented from lmms::Instrument.
Definition at line 52 of file DummyInstrument.h.
References lmms::Engine::audioEngine(), and lmms::zeroSampleFrames().
saveSettings()
void lmms::DummyInstrument::saveSettings (QDomDocument & , QDomElement &) inline override virtual
Implements lmms::SerializingObject.
Definition at line 57 of file DummyInstrument.h.
The documentation for this class was generated from the following file:
include/DummyInstrument.h