LMMS: lmms::DetuningHelper Class Reference
lmms::DetuningHelper Class Reference
#include <DetuningHelper.h>
Public Member Functions
DetuningHelper ()
DetuningHelper (const DetuningHelper &_copy)
~DetuningHelper () override=default
float defaultValue () const override
QString displayName () const override
QString nodeName () const override
Public Member Functions inherited from lmms::InlineAutomation
InlineAutomation ()
InlineAutomation (const InlineAutomation &_copy)
~InlineAutomation () override
AutomationClip * automationClip ()
bool hasAutomation () const
void loadSettings (const QDomElement &_this) override
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
Public Member Functions inherited from lmms::FloatModel
FloatModel (float val=0, float min=0, float max=0, float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
QString displayValue (const float val) const override
int getDigitCount () const
float getRoundedValue () const
Public Member Functions inherited from lmms::TypedAutomatableModel< float >
AutomatableModel (const float val=0, const float min=0, const float max=0, const float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
float initValue () const
float maxValue () const
float minValue () const
float value (int frameOffset=0) const
Public Member Functions inherited from lmms::AutomatableModel
~AutomatableModel () override
virtual void accept (ConstModelVisitor &v) const =0
virtual void accept (ModelVisitor &v)=0
float centerValue () const
ControllerConnection * controllerConnection () const
float controllerValue (int frameOffset) const
template<class Target>
Target * dynamicCast (bool doThrow=false)
Return this class casted to Target.
template<class Target>
const Target * dynamicCast (bool doThrow=false) const
const overload, see overloaded function
float globalAutomationValueAt (const TimePos &time)
bool hasLinkedModels () const
void incValue (int steps)
template<class T>
T initValue () const
float inverseScaledValue (float value) const
Returns value applied with the inverse of this model's scale type.
bool isAtInitValue () const
bool isAutomated () const
bool isAutomatedOrControlled () const
bool isScaleLogarithmic () const
bool isValueChanged ()
virtual void loadSettings (const QDomElement &element, const QString &name)
Loads settings (value, automation links and controller connections) of AutomatableModel from specified DOM element using <name> as attribute/node name.
template<class T>
T maxValue () const
template<class T>
T minValue () const
float range () const
virtual void saveSettings (QDomDocument &doc, QDomElement &element, const QString &name)
Saves settings (value, automation links and controller connections) of AutomatableModel into specified DOM element using <name> as attribute/node name.
float scaledValue (float value) const
Returns value scaled with the scale type and min/max values of this model.
void setAutomatedValue (const float value)
void setCenterValue (const float centerVal)
void setControllerConnection (ControllerConnection *c)
void setInitValue (const float value)
void setRange (const float min, const float max, const float step=1)
void setScaleLogarithmic (bool setToTrue=true)
void setScaleType (ScaleType sc)
void setStep (const float step)
void setStrictStepSize (const bool b)
void setValue (const float value)
template<class T>
T step () const
void unlinkAllModels ()
bool useControllerValue ()
template<class T>
T value (int frameOffset=0) const
ValueBuffer * valueBuffer ()
Function that returns sample-exact data as a ValueBuffer.
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Additional Inherited Members
Public Types inherited from lmms::AutomatableModel
using AutoModelVector = std::vector<AutomatableModel*>
enum class ScaleType {
Linear ,
Logarithmic ,
Decibel
}
Public Slots inherited from lmms::AutomatableModel
virtual void reset ()
void setUseControllerValue (bool b=true)
void unlinkControllerConnection ()
Signals inherited from lmms::AutomatableModel
void destroyed (lmms::jo_id_t id)
void initValueChanged (float val)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Public Member Functions inherited from lmms::AutomatableModel
template<bool>
static bool castValue (const float v)
template<class T>
static T castValue (const float v)
static void incrementPeriodCounter ()
static void linkModels (AutomatableModel *m1, AutomatableModel *m2)
link m1 and m2, let m1 take the values of m2
static void resetPeriodCounter ()
static void unlinkModels (AutomatableModel *m1, AutomatableModel *m2)
Protected Member Functions inherited from lmms::AutomatableModel
AutomatableModel (const float val=0, const float min=0, const float max=0, const float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
float fittedValue (float value) const
returns a value which is in range between min() and max() and aligned according to the step size (step size 0.05 -> value 0.12345 becomes 0.10 etc.).
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 34 of file DetuningHelper.h.
Constructor & Destructor Documentation
DetuningHelper() [1/2]
lmms::DetuningHelper::DetuningHelper () inline
Definition at line 38 of file DetuningHelper.h.
References lmms::InlineAutomation::InlineAutomation().
Referenced by DetuningHelper().
DetuningHelper() [2/2]
lmms::DetuningHelper::DetuningHelper (const DetuningHelper & _copy) inline
Definition at line 42 of file DetuningHelper.h.
References DetuningHelper(), and lmms::InlineAutomation::InlineAutomation().
~DetuningHelper()
lmms::DetuningHelper::~DetuningHelper () override default
Member Function Documentation
defaultValue()
float lmms::DetuningHelper::defaultValue () const inline override virtual
Implements lmms::InlineAutomation.
Definition at line 49 of file DetuningHelper.h.
displayName()
QString lmms::DetuningHelper::displayName () const inline override virtual
Reimplemented from lmms::Model.
Definition at line 54 of file DetuningHelper.h.
nodeName()
QString lmms::DetuningHelper::nodeName () const inline override virtual
Reimplemented from lmms::AutomatableModel.
Definition at line 59 of file DetuningHelper.h.
The documentation for this class was generated from the following file:
include/DetuningHelper.h