LMMS: src/3rdparty/jack2/common/jack/uuid.h File Reference
uuid.h File Reference
#include <jack/types.h>
Macros
#define JACK_UUID_EMPTY_INITIALIZER 0
#define JACK_UUID_SIZE 36
#define JACK_UUID_STRING_SIZE (JACK_UUID_SIZE+1) /* includes trailing null */
Functions
jack_uuid_t jack_client_uuid_generate ()
jack_uuid_t jack_port_uuid_generate (uint32_t port_id)
void jack_uuid_clear (jack_uuid_t *)
int jack_uuid_compare (jack_uuid_t, jack_uuid_t)
void jack_uuid_copy (jack_uuid_t *dst, jack_uuid_t src)
int jack_uuid_empty (jack_uuid_t)
int jack_uuid_parse (const char *buf, jack_uuid_t *)
uint32_t jack_uuid_to_index (jack_uuid_t)
void jack_uuid_unparse (jack_uuid_t, char buf[JACK_UUID_STRING_SIZE])
Macro Definition Documentation
JACK_UUID_EMPTY_INITIALIZER
#define JACK_UUID_EMPTY_INITIALIZER 0
Definition at line 31 of file uuid.h.
Referenced by Jack::JackClientCheckRequest::JackClientCheckRequest(), Jack::JackClientControl::JackClientControl(), Jack::JackClientOpenRequest::JackClientOpenRequest(), Jack::JackInternalClientLoadRequest::JackInternalClientLoadRequest(), Jack::JackEngine::ClientCloseAux(), Jack::JackMetadata::GetAllProperties(), jack_uuid_clear(), jack_uuid_empty(), and Jack::JackMetadata::RemoveAllProperties().
JACK_UUID_SIZE
#define JACK_UUID_SIZE 36
Definition at line 29 of file uuid.h.
Referenced by Jack::JackGenericClientChannel::GetUUIDForClientName().
JACK_UUID_STRING_SIZE
#define JACK_UUID_STRING_SIZE (JACK_UUID_SIZE+1) /* includes trailing null */
Definition at line 30 of file uuid.h.
Referenced by Jack::JackClient::ClientNotify(), Jack::JackMetadata::GetAllProperties(), Jack::JackMetadata::GetProperties(), Jack::JackMetadata::GetProperty(), Jack::JackClient::GetUUIDForClientName(), jack_client_get_uuid(), jack_uuid_unparse(), Jack::JackEngine::PropertyChangeNotify(), Jack::JackMetadata::RemoveProperties(), Jack::JackEngine::SessionNotify(), Jack::JackEngine::SessionReply(), Jack::JackMetadata::SetProperty(), and Jack::JackSessionNotifyResult::Write().
Function Documentation
jack_client_uuid_generate()
LIB_EXPORT jack_uuid_t jack_client_uuid_generate () extern
Definition at line 2087 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by Jack::JackDriver::JackDriver(), Jack::JackEngine::ClientExternalOpen(), and Jack::JackEngine::SessionNotify().
jack_port_uuid_generate()
LIB_EXPORT jack_uuid_t jack_port_uuid_generate (uint32_t port_id) extern
Definition at line 2095 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by jack_port_uuid(), Jack::JackEngine::PortSetDefaultMetadata(), and Jack::JackEngine::PortUnRegister().
jack_uuid_clear()
LIB_EXPORT void jack_uuid_clear (jack_uuid_t * u) extern
Definition at line 2125 of file JackAPI.cpp.
References JACK_UUID_EMPTY_INITIALIZER, and LIB_EXPORT.
Referenced by Jack::JackPropertyChangeNotifyRequest::JackPropertyChangeNotifyRequest(), and Jack::JackEngine::EnsureUUID().
jack_uuid_compare()
LIB_EXPORT int jack_uuid_compare (jack_uuid_t a, jack_uuid_t b) extern
Definition at line 2107 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by Jack::JackEngine::EnsureUUID(), Jack::JackMetadata::GetAllProperties(), and Jack::JackEngine::GetClientNameForUUID().
jack_uuid_copy()
LIB_EXPORT void jack_uuid_copy (jack_uuid_t * dst, jack_uuid_t src) extern
Definition at line 2120 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by Jack::JackPropertyChangeNotifyRequest::JackPropertyChangeNotifyRequest(), Jack::JackEngine::ClientCloseAux(), Jack::JackMetadata::GetAllProperties(), and Jack::JackMetadata::GetProperties().
jack_uuid_empty()
LIB_EXPORT int jack_uuid_empty (jack_uuid_t u) extern
Definition at line 2150 of file JackAPI.cpp.
References JACK_UUID_EMPTY_INITIALIZER, and LIB_EXPORT.
Referenced by Jack::JackEngine::ClientExternalOpen(), Jack::JackEngine::EnsureUUID(), Jack::JackEngine::PortUnRegister(), and Jack::JackEngine::SessionNotify().
jack_uuid_parse()
LIB_EXPORT int jack_uuid_parse (const char * buf, jack_uuid_t * u) extern
Definition at line 2130 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by Jack::JackClient::ClientNotify(), Jack::JackMetadata::GetAllProperties(), Jack::JackEngine::GetClientNameForUUID(), and Jack::JackEngine::ReserveClientName().
jack_uuid_to_index()
LIB_EXPORT uint32_t jack_uuid_to_index (jack_uuid_t u) extern
Definition at line 2102 of file JackAPI.cpp.
References LIB_EXPORT.
jack_uuid_unparse()
LIB_EXPORT void jack_uuid_unparse (jack_uuid_t u, char buf[JACK_UUID_STRING_SIZE]) extern
Definition at line 2145 of file JackAPI.cpp.
References JACK_UUID_STRING_SIZE, and LIB_EXPORT.
Referenced by Jack::JackClient::ClientNotify(), Jack::JackMetadata::GetProperties(), Jack::JackMetadata::GetProperty(), Jack::JackEngine::GetUUIDForClientName(), jack_client_get_uuid(), Jack::JackEngine::PropertyChangeNotify(), Jack::JackMetadata::RemoveProperties(), Jack::JackEngine::SessionNotify(), Jack::JackEngine::SessionReply(), and Jack::JackMetadata::SetProperty().