LMMS: lmms::AutomationTrack Class Reference
lmms::AutomationTrack Class Reference
#include <AutomationTrack.h>
Public Member Functions
AutomationTrack (TrackContainer *tc, bool _hidden=false)
~AutomationTrack () override=default
Clip * createClip (const TimePos &pos) override
gui::TrackView * createView (gui::TrackContainerView *) override
void loadTrackSpecificSettings (const QDomElement &_this) override
QString nodeName () const override
bool play (const TimePos &_start, const fpp_t _frames, const f_cnt_t _frame_base, int _clip_num=-1) override
void saveTrackSpecificSettings (QDomDocument &doc, QDomElement &parent, bool presetMode) override
Public Member Functions inherited from lmms::Track
Track (Type type, TrackContainer *tc)
Create a new (empty) track object.
~Track () override
Destroy this track.
Clip * addClip (Clip *clip)
Add another Clip into this track.
Track * clone ()
Clone a track from this track.
auto color () const -> const std::optional< QColor > &
void createClipsForPattern (int pattern)
void deleteClips ()
Remove all Clips from this track.
QString displayName () const override
auto getClip (std::size_t clipNum) -> Clip *
Get a Clip by number.
int getClipNum (const Clip *clip)
Determine the given Clip's number in our array.
const clipVector & getClips () const
void getClipsInRange (clipVector &clipV, const TimePos &start, const TimePos &end)
Retrieve a list of clips that fall within a period.
int getHeight ()
BoolModel * getMutedModel ()
void insertBar (const TimePos &pos)
Move all the clips after a certain time later by one bar.
bool isMutedBeforeSolo () const
bar_t length () const
Return the length of the entire track in bars.
void loadPreset (const QDomElement &element)
void loadSettings (const QDomElement &element) override
void lock ()
virtual const QString & name () const
int numOfClips ()
Return the number of clips we contain.
void removeBar (const TimePos &pos)
Move all the clips after a certain time earlier by one bar.
void removeClip (Clip *clip)
Remove a given Clip from this track.
void savePreset (QDomDocument &doc, QDomElement &element)
void saveSettings (QDomDocument &doc, QDomElement &element) override
void setColor (const std::optional< QColor > &color)
void setHeight (int height)
void swapPositionOfClips (int clipNum1, int clipNum2)
Swap the position of two clips.
TrackContainer * trackContainer () const
bool tryLock ()
Type type () const
void unlock ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Friends
class AutomationTrackView
Additional Inherited Members
Public Types inherited from lmms::Track
using clipVector = std::vector<Clip*>
enum class Type {
Instrument ,
Pattern ,
Sample ,
Event ,
Video ,
Automation ,
HiddenAutomation ,
Count
}
Public Slots inherited from lmms::Track
void setMutedBeforeSolo (const bool muted)
virtual void setName (const QString &newName)
void toggleSolo ()
Invert the track's solo state.
Signals inherited from lmms::Track
void clipAdded (lmms::Clip *)
void colorChanged ()
void dataChanged ()
void destroyedTrack ()
void nameChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Public Member Functions inherited from lmms::Track
static Track * create (const QDomElement &element, TrackContainer *tc)
Create a track inside TrackContainer from track type in a QDomElement and restore state from XML.
static Track * create (Type tt, TrackContainer *tc)
Create a track based on the given track type and container.
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Attributes inherited from lmms::Track
BoolModel m_mutedModel
BoolModel m_soloModel
Detailed Description
Definition at line 35 of file AutomationTrack.h.
Constructor & Destructor Documentation
AutomationTrack()
lmms::AutomationTrack::AutomationTrack (TrackContainer * tc, bool _hidden = false)
Definition at line 36 of file AutomationTrack.cpp.
References lmms::Track::Track(), and lmms::Track::setName().
~AutomationTrack()
lmms::AutomationTrack::~AutomationTrack () override default
Member Function Documentation
createClip()
Clip * lmms::AutomationTrack::createClip (const TimePos & pos) override virtual
Implements lmms::Track.
Definition at line 59 of file AutomationTrack.cpp.
References pos.
createView()
gui::TrackView * lmms::AutomationTrack::createView (gui::TrackContainerView * tcv) override virtual
Implements lmms::Track.
Definition at line 51 of file AutomationTrack.cpp.
loadTrackSpecificSettings()
void lmms::AutomationTrack::loadTrackSpecificSettings (const QDomElement & _this) override virtual
Implements lmms::Track.
Definition at line 76 of file AutomationTrack.cpp.
References lmms::Track::HiddenAutomation, and lmms::Track::type().
nodeName()
QString lmms::AutomationTrack::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 45 of file AutomationTrack.h.
play()
bool lmms::AutomationTrack::play (const TimePos & _start, const fpp_t _frames, const f_cnt_t _frame_base, int _clip_num = -1) override virtual
Implements lmms::Track.
Definition at line 42 of file AutomationTrack.cpp.
saveTrackSpecificSettings()
void lmms::AutomationTrack::saveTrackSpecificSettings (QDomDocument & doc, QDomElement & parent, bool presetMode) override virtual
Implements lmms::Track.
Definition at line 69 of file AutomationTrack.cpp.
Friends And Related Symbol Documentation
AutomationTrackView
friend class AutomationTrackView friend
Definition at line 57 of file AutomationTrack.h.
References AutomationTrackView.
Referenced by AutomationTrackView.
The documentation for this class was generated from the following files:
include/AutomationTrack.h
src/tracks/AutomationTrack.cpp