LMMS: lmms::PathUtil Namespace Reference
lmms::PathUtil Namespace Reference
Enumerations
enum class Base {
Absolute ,
ProjectDir ,
FactoryProjects ,
FactorySample ,
UserSample ,
UserVST ,
Preset ,
FactoryPresets ,
UserLADSPA ,
DefaultLADSPA ,
UserSoundfont ,
DefaultSoundfont ,
UserGIG ,
DefaultGIG ,
LocalDir
}
Functions
QString baseLocation (const Base base, bool *error=nullptr)
Return the directory associated with a given base as a QString Optionally, if a pointer to boolean is given the method will use it to indicate whether the prefix could be resolved properly or not.
Base baseLookup (const QString &path)
Check the prefix of a path and return the base it corresponds to Defaults to Base::Absolute.
QString basePrefix (const Base base)
Return the prefix used to denote this base in path strings.
QDir baseQDir (const Base base, bool *error=nullptr)
Return the directory associated with a given base as a QDir.
QString cleanName (const QString &path)
Get the filename for a path, handling prefixed paths correctly.
QString oldRelativeUpgrade (const QString &input)
Upgrade prefix-less relative paths to the new format.
QString relativeOrAbsolute (const QString &input, const Base base)
Make this path relative to a given base, return an absolute path if that fails.
QString stripPrefix (const QString &path)
Remove the prefix from a path, iff there is one.
QString toAbsolute (const QString &input, bool *error=nullptr)
Make this path absolute.
QString toShortestRelative (const QString &input, bool allowLocal=false)
Make this path relative to any base, choosing the shortest if there are multiple options.
Variables
auto relativeBases
Enumeration Type Documentation
Base
enum class lmms::PathUtil::Base strong
Enumerator
Absolute
ProjectDir
FactoryProjects
FactorySample
UserSample
UserVST
Preset
FactoryPresets
UserLADSPA
DefaultLADSPA
UserSoundfont
DefaultSoundfont
UserGIG
DefaultGIG
LocalDir
Definition at line 34 of file PathUtil.h.
Function Documentation
baseLocation()
QString LMMS_EXPORT lmms::PathUtil::baseLocation (const Base base, bool * error)
Return the directory associated with a given base as a QString Optionally, if a pointer to boolean is given the method will use it to indicate whether the prefix could be resolved properly or not.
Definition at line 16 of file PathUtil.cpp.
References DefaultGIG, DefaultLADSPA, DefaultSoundfont, FactoryPresets, FactoryProjects, FactorySample, lmms::Engine::getSong(), lmms::ConfigManager::gigDir(), lmms::ConfigManager::inst(), lmms::TrackContainer::isEmpty(), lmms::ConfigManager::ladspaDir(), LocalDir, Preset, ProjectDir, lmms::Song::projectFileName(), lmms::ConfigManager::sf2Dir(), UserGIG, lmms::ConfigManager::userGigDir(), UserLADSPA, lmms::ConfigManager::userLadspaDir(), lmms::ConfigManager::userPresetsDir(), lmms::ConfigManager::userProjectsDir(), UserSample, lmms::ConfigManager::userSamplesDir(), lmms::ConfigManager::userSf2Dir(), UserSoundfont, UserVST, and lmms::ConfigManager::userVstDir().
Referenced by baseQDir(), oldRelativeUpgrade(), and toAbsolute().
baseLookup()
Base LMMS_EXPORT lmms::PathUtil::baseLookup (const QString & path)
Check the prefix of a path and return the base it corresponds to Defaults to Base::Absolute.
Definition at line 100 of file PathUtil.cpp.
References Absolute, basePrefix(), and relativeBases.
Referenced by stripPrefix(), and toAbsolute().
basePrefix()
QString LMMS_EXPORT lmms::PathUtil::basePrefix (const Base base)
Return the prefix used to denote this base in path strings.
Definition at line 78 of file PathUtil.cpp.
References DefaultGIG, DefaultLADSPA, DefaultSoundfont, FactoryPresets, FactoryProjects, FactorySample, LocalDir, Preset, ProjectDir, UserGIG, UserLADSPA, UserSample, UserSoundfont, and UserVST.
Referenced by baseLookup(), lmms::DataFile::copyResources(), lmms::DataFile::hasLocalPlugins(), oldRelativeUpgrade(), stripPrefix(), toAbsolute(), and toShortestRelative().
baseQDir()
QDir LMMS_EXPORT lmms::PathUtil::baseQDir (const Base base, bool * error = nullptr)
Return the directory associated with a given base as a QDir.
Optional pointer to boolean to indicate if the prefix could be resolved properly.
Definition at line 68 of file PathUtil.cpp.
References Absolute, and baseLocation().
Referenced by relativeOrAbsolute().
cleanName()
QString LMMS_EXPORT lmms::PathUtil::cleanName (const QString & path)
Get the filename for a path, handling prefixed paths correctly.
Definition at line 118 of file PathUtil.cpp.
References stripPrefix().
Referenced by lmms::gui::SampleClipView::paintEvent().
oldRelativeUpgrade()
QString LMMS_EXPORT lmms::PathUtil::oldRelativeUpgrade (const QString & input)
Upgrade prefix-less relative paths to the new format.
Definition at line 126 of file PathUtil.cpp.
References baseLocation(), basePrefix(), FactorySample, UserSample, and UserVST.
Referenced by toAbsolute().
relativeOrAbsolute()
QString LMMS_EXPORT lmms::PathUtil::relativeOrAbsolute (const QString & input, const Base base)
Make this path relative to a given base, return an absolute path if that fails.
Definition at line 166 of file PathUtil.cpp.
References Absolute, baseQDir(), and toAbsolute().
Referenced by toShortestRelative().
stripPrefix()
QString LMMS_EXPORT lmms::PathUtil::stripPrefix (const QString & path)
Remove the prefix from a path, iff there is one.
Definition at line 113 of file PathUtil.cpp.
References baseLookup(), and basePrefix().
Referenced by cleanName().
toAbsolute()
QString LMMS_EXPORT lmms::PathUtil::toAbsolute (const QString & input, bool * error = nullptr)
Make this path absolute.
If a pointer to boolean is given it will indicate whether the path was converted successfully
Definition at line 150 of file PathUtil.cpp.
References baseLocation(), baseLookup(), basePrefix(), and oldRelativeUpgrade().
Referenced by lmms::SampleBuffer::SampleBuffer(), lmms::DataFile::copyResources(), lmms::ConfigManager::loadConfigFile(), lmms::EnvelopeAndLfoParameters::loadSettings(), lmms::LfoController::loadSettings(), lmms::SampleClip::loadSettings(), lmms::gui::SampleLoader::openAudioFile(), relativeOrAbsolute(), lmms::gui::FileBrowser::reloadTree(), toShortestRelative(), and lmms::gui::SampleClipView::updateSample().
toShortestRelative()
QString LMMS_EXPORT lmms::PathUtil::toShortestRelative (const QString & input, bool allowLocal = false)
Make this path relative to any base, choosing the shortest if there are multiple options.
allowLocal defines whether local paths should be considered. Defaults to an absolute path if all bases fail.
Definition at line 180 of file PathUtil.cpp.
References Absolute, basePrefix(), LocalDir, relativeBases, relativeOrAbsolute(), and toAbsolute().
Referenced by lmms::SampleBuffer::SampleBuffer(), lmms::gui::FileBrowserTreeWidget::contextMenuEvent(), lmms::gui::SampleLoader::openAudioFile(), and lmms::ConfigManager::saveConfigFile().
Variable Documentation
relativeBases
auto lmms::PathUtil::relativeBases
Initial value:
= std::array{ Base::ProjectDir, Base::FactoryProjects, Base::FactorySample, Base::UserSample, Base::UserVST, Base::Preset,
        Base::FactoryPresets, Base::UserLADSPA, Base::DefaultLADSPA, Base::UserSoundfont, Base::DefaultSoundfont, Base::UserGIG, Base::DefaultGIG,
        Base::LocalDir }
Definition at line 12 of file PathUtil.cpp.
Referenced by baseLookup(), and toShortestRelative().