LMMS: src/3rdparty/jack2/linux/alsa/alsa_midi_jackmp.cpp File Reference
alsa_midi_jackmp.cpp File Reference
#include "JackAlsaDriver.h"
#include "JackPort.h"
#include "alsa_midi_impl.h"
Classes
struct fake_port_t
class JackAlsaDriver
The ALSA driver.
Functions
int JACK_client_create_thread (jack_client_t *client, pthread_t *thread, int priority, int realtime, void *(*start_routine)(void *), void *arg)
jack_nframes_t JACK_frame_time (jack_client_t *client)
jack_nframes_t JACK_get_sample_rate (jack_client_t *client)
int JACK_is_realtime (jack_client_t *client)
jack_nframes_t JACK_last_frame_time (jack_client_t *client)
void * JACK_port_get_buffer (jack_port_t *port, jack_nframes_t nframes)
jack_port_t * JACK_port_register (jack_client_t *client, const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
int JACK_port_set_alias (jack_port_t *port, const char *name)
int jack_port_set_default_metadata (jack_port_t *port, const char *pretty_name)
int JACK_port_unregister (jack_client_t *client, jack_port_t *port)
Function Documentation
JACK_client_create_thread()
int JACK_client_create_thread (jack_client_t * client, pthread_t * thread, int priority, int realtime, void *(* start_routine)(void *), void * arg)
Definition at line 38 of file alsa_midi_jackmp.cpp.
References client().
JACK_frame_time()
jack_nframes_t JACK_frame_time (jack_client_t * client)
Definition at line 85 of file alsa_midi_jackmp.cpp.
References client().
JACK_get_sample_rate()
jack_nframes_t JACK_get_sample_rate (jack_client_t * client)
Definition at line 80 of file alsa_midi_jackmp.cpp.
References client().
JACK_is_realtime()
int JACK_is_realtime (jack_client_t * client)
Definition at line 33 of file alsa_midi_jackmp.cpp.
References client().
JACK_last_frame_time()
jack_nframes_t JACK_last_frame_time (jack_client_t * client)
Definition at line 90 of file alsa_midi_jackmp.cpp.
References client().
JACK_port_get_buffer()
void * JACK_port_get_buffer (jack_port_t * port, jack_nframes_t nframes)
Definition at line 62 of file alsa_midi_jackmp.cpp.
References fake_port_t::driver, Jack::JackAlsaDriver::port_get_buffer(), and fake_port_t::port_id.
JACK_port_register()
jack_port_t * JACK_port_register (jack_client_t * client, const char * port_name, const char * port_type, unsigned long flags, unsigned long buffer_size)
Definition at line 43 of file alsa_midi_jackmp.cpp.
References client(), driver, and NO_PORT.
JACK_port_set_alias()
int JACK_port_set_alias (jack_port_t * port, const char * name)
Definition at line 68 of file alsa_midi_jackmp.cpp.
References fake_port_t::driver, fake_port_t::port_id, and Jack::JackAlsaDriver::port_set_alias().
jack_port_set_default_metadata()
int jack_port_set_default_metadata (jack_port_t * port, const char * pretty_name)
Definition at line 74 of file alsa_midi_jackmp.cpp.
References fake_port_t::driver, fake_port_t::port_id, and Jack::JackAlsaDriver::PortSetDefaultMetadata().
JACK_port_unregister()
int JACK_port_unregister (jack_client_t * client, jack_port_t * port)
Definition at line 54 of file alsa_midi_jackmp.cpp.
References client(), fake_port_t::driver, fake_port_t::port_id, and Jack::JackAlsaDriver::port_unregister().