LMMS: hiir::HalfBandTpl< NC, DT, NCHN > Class Template Reference
hiir::HalfBandTpl< NC, DT, NCHN > Class Template Reference
#include <HalfBandTpl.h>
Public Types
typedef DT DataType
Public Member Functions
void clear_buffers () noexcept
void process_block (DataType out_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
void process_block_hpf (DataType out_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
void process_block_split (DataType out_l_ptr[], DataType out_h_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE DataType process_sample (DataType in) noexcept
hiir_FORCEINLINE DataType process_sample_hpf (DataType in) noexcept
hiir_FORCEINLINE void process_sample_split (DataType &low, DataType &high, DataType in) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = NCHN
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataTpl< DataType >, NBR_COEFS+2 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const HalfBandTpl &other) const =delete
bool operator== (const HalfBandTpl &other) const =delete
hiir_FORCEINLINE std::array< DataType, 2 > process_2_paths (DataType input) noexcept
Private Attributes
FilterBiPhase _bifilter
int _phase { 0 }
DataType _prev { 0.f }
Static Private Attributes
static constexpr int _nbr_phases = 2
Detailed Description
template<int NC, typename DT, int NCHN>
class hiir::HalfBandTpl< NC, DT, NCHN >
Definition at line 60 of file HalfBandTpl.h.
Member Typedef Documentation
DataType
template<int NC, typename DT, int NCHN> typedef DT hiir::HalfBandTpl< NC, DT, NCHN >::DataType
Definition at line 70 of file HalfBandTpl.h.
Filter
template<int NC, typename DT, int NCHN> typedef std::array<StageDataTpl <DataType>, NBR_COEFS + 2> hiir::HalfBandTpl< NC, DT, NCHN >::Filter private
Definition at line 106 of file HalfBandTpl.h.
FilterBiPhase
template<int NC, typename DT, int NCHN> typedef std::array<Filter, _nbr_phases> hiir::HalfBandTpl< NC, DT, NCHN >::FilterBiPhase private
Definition at line 108 of file HalfBandTpl.h.
Member Function Documentation
clear_buffers()
template<int NC, typename DT, int NCHN> void hiir::HalfBandTpl< NC, DT, NCHN >::clear_buffers () noexcept
Definition at line 263 of file HalfBandTpl.hpp.
References _bifilter, _phase, _prev, i, and NBR_COEFS.
operator!=()
template<int NC, typename DT, int NCHN> bool hiir::HalfBandTpl< NC, DT, NCHN >::operator!= (const HalfBandTpl< NC, DT, NCHN > & other) const private delete
operator==()
template<int NC, typename DT, int NCHN> bool hiir::HalfBandTpl< NC, DT, NCHN >::operator== (const HalfBandTpl< NC, DT, NCHN > & other) const private delete
process_2_paths()
template<int NC, typename DT, int NCHN> std::array< typename HalfBandTpl< NC, DT, NCHN >::DataType, 2 > hiir::HalfBandTpl< NC, DT, NCHN >::process_2_paths (DataType input) private noexcept
Definition at line 292 of file HalfBandTpl.hpp.
References _bifilter, _phase, _prev, NBR_COEFS, and hiir::StageProcTpl< REMAINING, DT >::process_sample_pos().
Referenced by process_sample(), process_sample_hpf(), and process_sample_split().
process_block()
template<int NC, typename DT, int NCHN> void hiir::HalfBandTpl< NC, DT, NCHN >::process_block (DataType out_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
Definition at line 117 of file HalfBandTpl.hpp.
References pos, and process_sample().
process_block_hpf()
template<int NC, typename DT, int NCHN> void hiir::HalfBandTpl< NC, DT, NCHN >::process_block_hpf (DataType out_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
Definition at line 171 of file HalfBandTpl.hpp.
References pos, and process_sample_hpf().
process_block_split()
template<int NC, typename DT, int NCHN> void hiir::HalfBandTpl< NC, DT, NCHN >::process_block_split (DataType out_l_ptr[], DataType out_h_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
Definition at line 234 of file HalfBandTpl.hpp.
References pos, and process_sample_split().
process_sample()
template<int NC, typename DT, int NCHN> HalfBandTpl< NC, DT, NCHN >::DataType hiir::HalfBandTpl< NC, DT, NCHN >::process_sample (DataType in) noexcept
Definition at line 91 of file HalfBandTpl.hpp.
References process_2_paths().
Referenced by process_block().
process_sample_hpf()
template<int NC, typename DT, int NCHN> HalfBandTpl< NC, DT, NCHN >::DataType hiir::HalfBandTpl< NC, DT, NCHN >::process_sample_hpf (DataType in) noexcept
Definition at line 145 of file HalfBandTpl.hpp.
References process_2_paths().
Referenced by process_block_hpf().
process_sample_split()
template<int NC, typename DT, int NCHN> void hiir::HalfBandTpl< NC, DT, NCHN >::process_sample_split (DataType & low, DataType & high, DataType in) noexcept
Definition at line 203 of file HalfBandTpl.hpp.
References process_2_paths().
Referenced by process_block_split().
set_coefs()
template<int NC, typename DT, int NCHN> void hiir::HalfBandTpl< NC, DT, NCHN >::set_coefs (const double coef_arr[]) noexcept
Definition at line 64 of file HalfBandTpl.hpp.
References _bifilter, i, and NBR_COEFS.
Member Data Documentation
_bifilter
template<int NC, typename DT, int NCHN> FilterBiPhase hiir::HalfBandTpl< NC, DT, NCHN >::_bifilter private
Definition at line 113 of file HalfBandTpl.h.
Referenced by clear_buffers(), process_2_paths(), and set_coefs().
_delay
template<int NC, typename DT, int NCHN> double hiir::HalfBandTpl< NC, DT, NCHN >::_delay = 0 static constexpr
Definition at line 73 of file HalfBandTpl.h.
_nbr_chn
template<int NC, typename DT, int NCHN> int hiir::HalfBandTpl< NC, DT, NCHN >::_nbr_chn = NCHN static constexpr
Definition at line 71 of file HalfBandTpl.h.
_nbr_phases
template<int NC, typename DT, int NCHN> int hiir::HalfBandTpl< NC, DT, NCHN >::_nbr_phases = 2 static constexpr private
Definition at line 103 of file HalfBandTpl.h.
_phase
template<int NC, typename DT, int NCHN> int hiir::HalfBandTpl< NC, DT, NCHN >::_phase { 0 } private
Definition at line 115 of file HalfBandTpl.h.
Referenced by clear_buffers(), and process_2_paths().
_prev
template<int NC, typename DT, int NCHN> DataType hiir::HalfBandTpl< NC, DT, NCHN >::_prev { 0.f } private
Definition at line 114 of file HalfBandTpl.h.
Referenced by clear_buffers(), and process_2_paths().
NBR_COEFS
template<int NC, typename DT, int NCHN> int hiir::HalfBandTpl< NC, DT, NCHN >::NBR_COEFS = NC static constexpr
Definition at line 72 of file HalfBandTpl.h.
Referenced by clear_buffers(), process_2_paths(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/HalfBandTpl.h
src/3rdparty/hiir/hiir/HalfBandTpl.hpp