LMMS: lmms::gui::PluginView Class Reference
lmms::gui::PluginView Class Reference
#include <PluginView.h>
Public Member Functions
PluginView (Plugin *_plugin, QWidget *_parent)
virtual bool isResizable () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Detailed Description
Definition at line 35 of file PluginView.h.
Constructor & Destructor Documentation
PluginView()
lmms::gui::PluginView::PluginView (Plugin * _plugin, QWidget * _parent) inline
Definition at line 38 of file PluginView.h.
References lmms::gui::ModelView::ModelView().
Referenced by lmms::gui::EffectView::EffectView(), lmms::gui::InstrumentView::InstrumentView(), and lmms::gui::ToolPluginView::ToolPluginView().
Member Function Documentation
isResizable()
virtual bool lmms::gui::PluginView::isResizable () const inline virtual
Definition at line 44 of file PluginView.h.
The documentation for this class was generated from the following file:
include/PluginView.h