LMMS: lmms::gui::RecentProjectsMenu Class Reference
lmms::gui::RecentProjectsMenu Class Reference
#include <RecentProjectsMenu.h>
Public Member Functions
RecentProjectsMenu (QWidget *parent=nullptr)
Private Slots
void fillMenu ()
void openProject (QAction *_action)
Detailed Description
Definition at line 34 of file RecentProjectsMenu.h.
Constructor & Destructor Documentation
RecentProjectsMenu()
lmms::gui::RecentProjectsMenu::RecentProjectsMenu (QWidget * parent = nullptr)
Definition at line 17 of file RecentProjectsMenu.cpp.
References fillMenu(), lmms::embed::getIconPixmap(), and openProject().
Member Function Documentation
fillMenu
void lmms::gui::RecentProjectsMenu::fillMenu () private slot
Definition at line 31 of file RecentProjectsMenu.cpp.
References lmms::embed::getIconPixmap(), lmms::ConfigManager::inst(), and lmms::ConfigManager::recentlyOpenedProjects().
Referenced by RecentProjectsMenu().
openProject
void lmms::gui::RecentProjectsMenu::openProject (QAction * _action) private slot
Definition at line 72 of file RecentProjectsMenu.cpp.
References lmms::gui::getGUI(), lmms::Engine::getSong(), lmms::Song::loadProject(), and lmms::gui::GuiApplication::mainWindow().
Referenced by RecentProjectsMenu().
The documentation for this class was generated from the following files:
include/RecentProjectsMenu.h
src/gui/menus/RecentProjectsMenu.cpp