LMMS: lmms::gui::ControllerView Class Reference
lmms::gui::ControllerView Class Reference
#include <ControllerView.h>
Public Slots
void closeControls ()
void editControls ()
void moveDown ()
void moveUp ()
void removeController ()
void renameController ()
Signals
void movedDown (ControllerView *view)
void movedUp (ControllerView *view)
void removedController (ControllerView *view)
Public Member Functions
ControllerView (Controller *_controller, QWidget *_parent)
~ControllerView () override
Controller * getController ()
const Controller * getController () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *_me) override
void modelChanged () override
void mouseDoubleClickEvent (QMouseEvent *event) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Attributes
ControllerDialog * m_controllerDlg
QLabel * m_nameLabel
bool m_show
QMdiSubWindow * m_subWindow
Detailed Description
Definition at line 46 of file ControllerView.h.
Constructor & Destructor Documentation
ControllerView()
lmms::gui::ControllerView::ControllerView (Controller * _controller, QWidget * _parent)
Definition at line 47 of file ControllerView.cpp.
References lmms::gui::ModelView::ModelView(), lmms::gui::MainWindow::addWindowedWidget(), closeControls(), lmms::Controller::createDialog(), lmms::Model::displayName(), editControls(), getController(), lmms::gui::getGUI(), m_controllerDlg, m_nameLabel, m_show, m_subWindow, lmms::gui::GuiApplication::mainWindow(), lmms::Controller::name(), and lmms::gui::ModelView::setModel().
Referenced by movedDown(), movedUp(), and removedController().
~ControllerView()
lmms::gui::ControllerView::~ControllerView () override
Definition at line 101 of file ControllerView.cpp.
References m_subWindow.
Member Function Documentation
closeControls
void lmms::gui::ControllerView::closeControls () slot
Definition at line 130 of file ControllerView.cpp.
References m_show, and m_subWindow.
Referenced by ControllerView().
contextMenuEvent()
void lmms::gui::ControllerView::contextMenuEvent (QContextMenuEvent * _me) override protected
Definition at line 175 of file ControllerView.cpp.
References lmms::gui::ModelView::castModel(), lmms::embed::getIconPixmap(), moveDown(), moveUp(), lmms::Controller::name(), removeController(), and renameController().
editControls
void lmms::gui::ControllerView::editControls () slot
Definition at line 112 of file ControllerView.cpp.
References m_show, and m_subWindow.
Referenced by ControllerView().
getController() [1/2]
Controller * lmms::gui::ControllerView::getController () inline
Definition at line 53 of file ControllerView.h.
References lmms::gui::ModelView::castModel().
Referenced by ControllerView(), lmms::gui::ControllerRackView::deleteController(), lmms::gui::ControllerRackView::removeController(), and renameController().
getController() [2/2]
const Controller * lmms::gui::ControllerView::getController () const inline
Definition at line 58 of file ControllerView.h.
References lmms::gui::ModelView::castModel().
modelChanged()
void lmms::gui::ControllerView::modelChanged () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 169 of file ControllerView.cpp.
mouseDoubleClickEvent()
void lmms::gui::ControllerView::mouseDoubleClickEvent (QMouseEvent * event) override protected
Definition at line 162 of file ControllerView.cpp.
References renameController().
movedDown
void lmms::gui::ControllerView::movedDown (ControllerView * view) signal
References ControllerView().
Referenced by lmms::gui::ControllerRackView::addController(), and moveDown().
moveDown
void lmms::gui::ControllerView::moveDown () slot
Definition at line 138 of file ControllerView.cpp.
References movedDown().
Referenced by lmms::gui::ControllerRackView::addController(), and contextMenuEvent().
movedUp
void lmms::gui::ControllerView::movedUp (ControllerView * view) signal
References ControllerView().
Referenced by lmms::gui::ControllerRackView::addController(), and moveUp().
moveUp
void lmms::gui::ControllerView::moveUp () slot
Definition at line 136 of file ControllerView.cpp.
References movedUp().
Referenced by lmms::gui::ControllerRackView::addController(), and contextMenuEvent().
removeController
void lmms::gui::ControllerView::removeController () slot
Definition at line 140 of file ControllerView.cpp.
References removedController().
Referenced by contextMenuEvent().
removedController
void lmms::gui::ControllerView::removedController (ControllerView * view) signal
References ControllerView().
Referenced by lmms::gui::ControllerRackView::addController(), and removeController().
renameController
void lmms::gui::ControllerView::renameController () slot
Definition at line 142 of file ControllerView.cpp.
References lmms::gui::ModelView::castModel(), getController(), lmms::Controller::Lfo, m_controllerDlg, and m_nameLabel.
Referenced by contextMenuEvent(), and mouseDoubleClickEvent().
Member Data Documentation
m_controllerDlg
ControllerDialog* lmms::gui::ControllerView::m_controllerDlg private
Definition at line 86 of file ControllerView.h.
Referenced by ControllerView(), and renameController().
m_nameLabel
QLabel* lmms::gui::ControllerView::m_nameLabel private
Definition at line 87 of file ControllerView.h.
Referenced by ControllerView(), and renameController().
m_show
bool lmms::gui::ControllerView::m_show private
Definition at line 88 of file ControllerView.h.
Referenced by ControllerView(), closeControls(), and editControls().
m_subWindow
QMdiSubWindow* lmms::gui::ControllerView::m_subWindow private
Definition at line 85 of file ControllerView.h.
Referenced by ControllerView(), ~ControllerView(), closeControls(), and editControls().
The documentation for this class was generated from the following files:
include/ControllerView.h
src/gui/ControllerView.cpp