LMMS: hiir::Downsampler2xNeonOld< NC > Class Template Reference
hiir::Downsampler2xNeonOld< NC > Class Template Reference
#include <Downsampler2xNeonOld.h>
Public Types
typedef float DataType
Public Member Functions
Downsampler2xNeonOld () noexcept
Downsampler2xNeonOld (const Downsampler2xNeonOld< NC > &other)=default
Downsampler2xNeonOld (Downsampler2xNeonOld< NC > &&other)=default
~Downsampler2xNeonOld ()=default
void clear_buffers () noexcept
Downsampler2xNeonOld< NC > & operator= (const Downsampler2xNeonOld< NC > &other)=default
Downsampler2xNeonOld< NC > & operator= (Downsampler2xNeonOld< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE float process_sample (const float in_ptr[2]) noexcept
hiir_FORCEINLINE void process_sample_split (float &low, float &high, const float in_ptr[2]) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 2 - 1
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataNeonV4, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Downsampler2xNeonOld< NC > &other) const =delete
bool operator== (const Downsampler2xNeonOld< NC > &other) const =delete
template<typename FL, typename FH>
hiir_FORCEINLINE long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void set_single_coef (int index, double coef) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (float *, float32x4_t, float32x4_t, float32x4_t) noexcept
static hiir_FORCEINLINE void store_high (float *ptr, float32x4_t even, float32x4_t odd, float32x4_t half) noexcept
static hiir_FORCEINLINE void store_low (float *ptr, float32x4_t even, float32x4_t odd, float32x4_t half) noexcept
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _coef_shift = ((NBR_COEFS & 1) * 2) ^ 3
static constexpr int _nbr_stages
static constexpr int _stage_width = 4
Detailed Description
template<int NC>
class hiir::Downsampler2xNeonOld< NC >
Definition at line 53 of file Downsampler2xNeonOld.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Downsampler2xNeonOld< NC >::DataType
Definition at line 62 of file Downsampler2xNeonOld.h.
Filter
template<int NC> typedef std::array<StageDataNeonV4, _nbr_stages + 1> hiir::Downsampler2xNeonOld< NC >::Filter private
Definition at line 107 of file Downsampler2xNeonOld.h.
Constructor & Destructor Documentation
Downsampler2xNeonOld() [1/3]
template<int NC> hiir::Downsampler2xNeonOld< NC >::Downsampler2xNeonOld () noexcept
Definition at line 60 of file Downsampler2xNeonOld.hpp.
References _filter, _nbr_stages, _stage_width, clear_buffers(), i, NBR_COEFS, set_single_coef(), and hiir::storea().
Referenced by Downsampler2xNeonOld(), Downsampler2xNeonOld(), ~Downsampler2xNeonOld(), operator=(), and operator=().
Downsampler2xNeonOld() [2/3]
template<int NC> hiir::Downsampler2xNeonOld< NC >::Downsampler2xNeonOld (const Downsampler2xNeonOld< NC > & other) default
References Downsampler2xNeonOld().
Downsampler2xNeonOld() [3/3]
template<int NC> hiir::Downsampler2xNeonOld< NC >::Downsampler2xNeonOld (Downsampler2xNeonOld< NC > && other) default
References Downsampler2xNeonOld().
~Downsampler2xNeonOld()
template<int NC> hiir::Downsampler2xNeonOld< NC >::~Downsampler2xNeonOld () default
References Downsampler2xNeonOld().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::Downsampler2xNeonOld< NC >::bypass (float * , float32x4_t , float32x4_t , float32x4_t) inline static private noexcept
Definition at line 120 of file Downsampler2xNeonOld.h.
References bypass().
Referenced by bypass(), and process_block().
clear_buffers()
template<int NC> void hiir::Downsampler2xNeonOld< NC >::clear_buffers () noexcept
Definition at line 281 of file Downsampler2xNeonOld.hpp.
References _filter, _nbr_stages, i, and hiir::storea().
Referenced by Downsampler2xNeonOld(), and operator=().
operator!=()
template<int NC> bool hiir::Downsampler2xNeonOld< NC >::operator!= (const Downsampler2xNeonOld< NC > & other) const private delete
operator=() [1/2]
template<int NC> Downsampler2xNeonOld< NC > & hiir::Downsampler2xNeonOld< NC >::operator= (const Downsampler2xNeonOld< NC > & other) default
References Downsampler2xNeonOld().
operator=() [2/2]
template<int NC> Downsampler2xNeonOld< NC > & hiir::Downsampler2xNeonOld< NC >::operator= (Downsampler2xNeonOld< NC > && other) default
References Downsampler2xNeonOld(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_split(), process_sample(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::Downsampler2xNeonOld< NC >::operator== (const Downsampler2xNeonOld< NC > & other) const private delete
process_block()
template<int NC> void hiir::Downsampler2xNeonOld< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 158 of file Downsampler2xNeonOld.hpp.
References bypass(), pos, process_block_quad(), process_sample(), and store_low().
Referenced by operator=().
process_block_quad() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE long hiir::Downsampler2xNeonOld< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE, process_block_quad(), store_high(), and store_low().
Referenced by process_block(), process_block_quad(), and process_block_split().
process_block_quad() [2/2]
template<int NC> template<typename FL, typename FH> long hiir::Downsampler2xNeonOld< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 323 of file Downsampler2xNeonOld.hpp.
References _filter, _nbr_stages, hiir::load4a(), hiir::load4u(), pos, hiir::StageProcNeonV4< CUR >::process_sample_pos(), and hiir::storea().
process_block_split()
template<int NC> void hiir::Downsampler2xNeonOld< NC >::process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 248 of file Downsampler2xNeonOld.hpp.
References pos, process_block_quad(), process_sample_split(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> float hiir::Downsampler2xNeonOld< NC >::process_sample (const float in_ptr[2]) noexcept
Definition at line 117 of file Downsampler2xNeonOld.hpp.
References _filter, _nbr_stages, hiir::load4a(), and hiir::StageProcNeonV4< CUR >::process_sample_pos().
Referenced by operator=(), and process_block().
process_sample_split()
template<int NC> void hiir::Downsampler2xNeonOld< NC >::process_sample_split (float & low, float & high, const float in_ptr[2]) noexcept
Definition at line 198 of file Downsampler2xNeonOld.hpp.
References _filter, _nbr_stages, hiir::load4a(), and hiir::StageProcNeonV4< CUR >::process_sample_pos().
Referenced by operator=(), and process_block_split().
set_coefs()
template<int NC> void hiir::Downsampler2xNeonOld< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 92 of file Downsampler2xNeonOld.hpp.
References i, NBR_COEFS, and set_single_coef().
Referenced by operator=().
set_single_coef()
template<int NC> void hiir::Downsampler2xNeonOld< NC >::set_single_coef (int index, double coef) inline private noexcept
Definition at line 309 of file Downsampler2xNeonOld.hpp.
References _coef_shift, _filter, _nbr_stages, _stage_width, and pos.
Referenced by Downsampler2xNeonOld(), and set_coefs().
store_high()
template<int NC> void hiir::Downsampler2xNeonOld< NC >::store_high (float * ptr, float32x4_t even, float32x4_t odd, float32x4_t half) static private noexcept
Definition at line 380 of file Downsampler2xNeonOld.hpp.
References hiir::storeu().
Referenced by process_block_quad(), and process_block_split().
store_low()
template<int NC> void hiir::Downsampler2xNeonOld< NC >::store_low (float * ptr, float32x4_t even, float32x4_t odd, float32x4_t half) static private noexcept
Definition at line 371 of file Downsampler2xNeonOld.hpp.
References hiir::storeu().
Referenced by process_block(), process_block_quad(), and process_block_split().
Member Data Documentation
_coef_shift
template<int NC> int hiir::Downsampler2xNeonOld< NC >::_coef_shift = ((NBR_COEFS & 1) * 2) ^ 3 static constexpr private
Definition at line 104 of file Downsampler2xNeonOld.h.
Referenced by set_single_coef().
_delay
template<int NC> double hiir::Downsampler2xNeonOld< NC >::_delay = 2 - 1 static constexpr
Definition at line 65 of file Downsampler2xNeonOld.h.
_filter
template<int NC> Filter hiir::Downsampler2xNeonOld< NC >::_filter private
Definition at line 123 of file Downsampler2xNeonOld.h.
Referenced by Downsampler2xNeonOld(), clear_buffers(), process_block_quad(), process_sample(), process_sample_split(), and set_single_coef().
_nbr_chn
template<int NC> int hiir::Downsampler2xNeonOld< NC >::_nbr_chn = 1 static constexpr
Definition at line 63 of file Downsampler2xNeonOld.h.
_nbr_stages
template<int NC> int hiir::Downsampler2xNeonOld< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 102 of file Downsampler2xNeonOld.h.
Referenced by Downsampler2xNeonOld(), clear_buffers(), process_block_quad(), process_sample(), process_sample_split(), and set_single_coef().
_stage_width
template<int NC> int hiir::Downsampler2xNeonOld< NC >::_stage_width = 4 static constexpr private
Definition at line 101 of file Downsampler2xNeonOld.h.
Referenced by Downsampler2xNeonOld(), and set_single_coef().
NBR_COEFS
template<int NC> int hiir::Downsampler2xNeonOld< NC >::NBR_COEFS = NC static constexpr
Definition at line 64 of file Downsampler2xNeonOld.h.
Referenced by Downsampler2xNeonOld(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Downsampler2xNeonOld.h
src/3rdparty/hiir/hiir/Downsampler2xNeonOld.hpp