LMMS: hiir::Downsampler2xSse< NC > Class Template Reference
hiir::Downsampler2xSse< NC > Class Template Reference
#include <Downsampler2xSse.h>
Public Types
typedef float DataType
Public Member Functions
Downsampler2xSse () noexcept
Downsampler2xSse (const Downsampler2xSse< NC > &other)=default
Downsampler2xSse (Downsampler2xSse< NC > &&other)=default
void clear_buffers () noexcept
Downsampler2xSse< NC > & operator= (const Downsampler2xSse< NC > &other)=default
Downsampler2xSse< NC > & operator= (Downsampler2xSse< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE float process_sample (const float in_ptr[2]) noexcept
hiir_FORCEINLINE void process_sample_split (float &low, float &high, const float in_ptr[2]) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = -1
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataSse, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Downsampler2xSse< NC > &other) const =delete
bool operator== (const Downsampler2xSse< NC > &other) const =delete
template<typename FL, typename FH>
hiir_FORCEINLINE long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (float *, __m128, __m128, __m128) noexcept
static hiir_FORCEINLINE void store_high (float *ptr, __m128 even, __m128 odd, __m128 half) noexcept
static hiir_FORCEINLINE void store_low (float *ptr, __m128 even, __m128 odd, __m128 half) noexcept
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _nbr_stages = (NBR_COEFS + _stage_width - 1) / _stage_width
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::Downsampler2xSse< NC >
Definition at line 48 of file Downsampler2xSse.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Downsampler2xSse< NC >::DataType
Definition at line 57 of file Downsampler2xSse.h.
Filter
template<int NC> typedef std::array<StageDataSse, _nbr_stages + 1> hiir::Downsampler2xSse< NC >::Filter private
Definition at line 110 of file Downsampler2xSse.h.
Constructor & Destructor Documentation
Downsampler2xSse() [1/3]
template<int NC> hiir::Downsampler2xSse< NC >::Downsampler2xSse () noexcept
Definition at line 57 of file Downsampler2xSse.hpp.
References _filter, _nbr_stages, clear_buffers(), i, and NBR_COEFS.
Referenced by Downsampler2xSse(), Downsampler2xSse(), operator=(), and operator=().
Downsampler2xSse() [2/3]
template<int NC> hiir::Downsampler2xSse< NC >::Downsampler2xSse (const Downsampler2xSse< NC > & other) default
References Downsampler2xSse().
Downsampler2xSse() [3/3]
template<int NC> hiir::Downsampler2xSse< NC >::Downsampler2xSse (Downsampler2xSse< NC > && other) default
References Downsampler2xSse().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::Downsampler2xSse< NC >::bypass (float * , __m128 , __m128 , __m128) inline static private noexcept
Definition at line 107 of file Downsampler2xSse.h.
References bypass().
Referenced by bypass(), and process_block().
clear_buffers()
template<int NC> void hiir::Downsampler2xSse< NC >::clear_buffers () noexcept
Definition at line 330 of file Downsampler2xSse.hpp.
References _filter, _nbr_stages, and i.
Referenced by Downsampler2xSse(), and operator=().
operator!=()
template<int NC> bool hiir::Downsampler2xSse< NC >::operator!= (const Downsampler2xSse< NC > & other) const private delete
operator=() [1/2]
template<int NC> Downsampler2xSse< NC > & hiir::Downsampler2xSse< NC >::operator= (const Downsampler2xSse< NC > & other) default
References Downsampler2xSse().
operator=() [2/2]
template<int NC> Downsampler2xSse< NC > & hiir::Downsampler2xSse< NC >::operator= (Downsampler2xSse< NC > && other) default
References Downsampler2xSse(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_split(), process_sample(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::Downsampler2xSse< NC >::operator== (const Downsampler2xSse< NC > & other) const private delete
process_block()
template<int NC> void hiir::Downsampler2xSse< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 147 of file Downsampler2xSse.hpp.
References _filter, bypass(), pos, process_block_quad(), hiir::StageProcSseV2< CUR >::process_sample_pos(), and store_low().
Referenced by operator=().
process_block_quad() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE long hiir::Downsampler2xSse< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE, process_block_quad(), store_high(), and store_low().
Referenced by process_block(), process_block_quad(), and process_block_split().
process_block_quad() [2/2]
template<int NC> template<typename FL, typename FH> long hiir::Downsampler2xSse< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 357 of file Downsampler2xSse.hpp.
References _filter, pos, and hiir::StageProcSseV2< CUR >::process_sample_pos().
process_block_split()
template<int NC> void hiir::Downsampler2xSse< NC >::process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 262 of file Downsampler2xSse.hpp.
References _filter, pos, process_block_quad(), hiir::StageProcSseV2< CUR >::process_sample_pos(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> float hiir::Downsampler2xSse< NC >::process_sample (const float in_ptr[2]) noexcept
Definition at line 115 of file Downsampler2xSse.hpp.
References _filter, and hiir::StageProcSseV2< CUR >::process_sample_pos().
Referenced by operator=().
process_sample_split()
template<int NC> void hiir::Downsampler2xSse< NC >::process_sample_split (float & low, float & high, const float in_ptr[2]) noexcept
Definition at line 219 of file Downsampler2xSse.hpp.
References _filter, and hiir::StageProcSseV2< CUR >::process_sample_pos().
Referenced by operator=().
set_coefs()
template<int NC> void hiir::Downsampler2xSse< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 88 of file Downsampler2xSse.hpp.
References _filter, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
store_high()
template<int NC> void hiir::Downsampler2xSse< NC >::store_high (float * ptr, __m128 even, __m128 odd, __m128 half) static private noexcept
Definition at line 395 of file Downsampler2xSse.hpp.
Referenced by process_block_quad(), and process_block_split().
store_low()
template<int NC> void hiir::Downsampler2xSse< NC >::store_low (float * ptr, __m128 even, __m128 odd, __m128 half) static private noexcept
Definition at line 386 of file Downsampler2xSse.hpp.
Referenced by process_block(), process_block_quad(), and process_block_split().
Member Data Documentation
_delay
template<int NC> double hiir::Downsampler2xSse< NC >::_delay = -1 static constexpr
Definition at line 60 of file Downsampler2xSse.h.
_filter
template<int NC> Filter hiir::Downsampler2xSse< NC >::_filter private
Definition at line 112 of file Downsampler2xSse.h.
Referenced by Downsampler2xSse(), clear_buffers(), process_block(), process_block_quad(), process_block_split(), process_sample(), process_sample_split(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Downsampler2xSse< NC >::_nbr_chn = 1 static constexpr
Definition at line 58 of file Downsampler2xSse.h.
_nbr_stages
template<int NC> int hiir::Downsampler2xSse< NC >::_nbr_stages = (NBR_COEFS + _stage_width - 1) / _stage_width static constexpr private
Definition at line 96 of file Downsampler2xSse.h.
Referenced by Downsampler2xSse(), and clear_buffers().
_stage_width
template<int NC> int hiir::Downsampler2xSse< NC >::_stage_width = 2 static constexpr private
Definition at line 95 of file Downsampler2xSse.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::Downsampler2xSse< NC >::NBR_COEFS = NC static constexpr
Definition at line 59 of file Downsampler2xSse.h.
Referenced by Downsampler2xSse(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Downsampler2xSse.h
src/3rdparty/hiir/hiir/Downsampler2xSse.hpp