LMMS: src/3rdparty/jack2/common/Jackdmp.cpp File Reference
Jackdmp.cpp File Reference
#include <iostream>
#include <assert.h>
#include <cassert>
#include <csignal>
#include <sys/types.h>
#include <getopt.h>
#include <cstring>
#include <cstdio>
#include <list>
#include "types.h"
#include "jack.h"
#include "control.h"
#include "JackConstants.h"
#include "JackPlatformPlug.h"
Functions
static void copyright (FILE *file)
static jackctl_parameter_t * jackctl_get_parameter (const JSList *parameters_list, const char *parameter_name)
static jackctl_driver_t * jackctl_server_get_driver (jackctl_server_t *server, const char *driver_name)
static jackctl_internal_t * jackctl_server_get_internal (jackctl_server_t *server, const char *internal_name)
int main (int argc, char **argv)
static void notify_server_start (const char *server_name)
static void notify_server_stop (const char *server_name)
static void print_server_drivers (jackctl_server_t *server, FILE *file)
static void print_server_internals (jackctl_server_t *server, FILE *file)
void print_version ()
void silent_jack_error_callback (const char *desc)
static void usage (FILE *file, jackctl_server_t *server, bool full=true)
Function Documentation
copyright()
void copyright (FILE * file) static
Definition at line 95 of file Jackdmp.cpp.
References file, and VERSION.
Referenced by main().
jackctl_get_parameter()
jackctl_parameter_t * jackctl_get_parameter (const JSList * parameters_list, const char * parameter_name) static
Definition at line 134 of file Jackdmp.cpp.
References _JSList::data, jack_slist_next, and jackctl_parameter_get_name().
Referenced by main(), and usage().
jackctl_server_get_driver()
jackctl_driver_t * jackctl_server_get_driver (jackctl_server_t * server, const char * driver_name) static
Definition at line 106 of file Jackdmp.cpp.
References _JSList::data, jack_slist_next, jackctl_driver_get_name(), jackctl_server_get_drivers_list(), and server().
Referenced by main().
jackctl_server_get_internal()
jackctl_internal_t * jackctl_server_get_internal (jackctl_server_t * server, const char * internal_name) static
Definition at line 120 of file Jackdmp.cpp.
References _JSList::data, jack_slist_next, jackctl_internal_get_name(), jackctl_server_get_internals_list(), and server().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 258 of file Jackdmp.cpp.
References audio_acquire(), audio_release(), audio_reserve_loop(), jackctl_parameter_value::b, jackctl_parameter_value::c, copyright(), getopt_long(), i, jackctl_parameter_value::i, JACK_DEFAULT_SERVER_NAME, JACK_PARAM_STRING_MAX, jack_set_error_function(), JACK_TIMER_HPET, JACK_TIMER_SYSTEM_CLOCK, jackctl_driver_get_parameters(), jackctl_driver_get_type(), jackctl_driver_params_parse(), jackctl_get_parameter(), jackctl_parameter_get_enum_constraint_value(), jackctl_parameter_get_enum_constraints_count(), jackctl_parameter_set_value(), jackctl_server_add_slave(), jackctl_server_close(), jackctl_server_create2(), jackctl_server_destroy(), jackctl_server_get_driver(), jackctl_server_get_internal(), jackctl_server_get_parameters(), jackctl_server_load_internal(), jackctl_server_load_session_file(), jackctl_server_open(), jackctl_server_remove_slave(), jackctl_server_start(), jackctl_server_stop(), jackctl_server_unload_internal(), jackctl_setup_signals(), jackctl_wait_signals(), jackctl_wait_signals_and_return(), JackMaster, JackSlave, k, notify_server_start(), notify_server_stop(), optarg, opterr, optind, optopt, print_version(), server_name, sigmask, silent_jack_error_callback(), jackctl_parameter_value::str, jackctl_parameter_value::ui, and usage().
notify_server_start()
void notify_server_start (const char * server_name) static
Definition at line 88 of file Jackdmp.cpp.
References server_name.
Referenced by main().
notify_server_stop()
void notify_server_stop (const char * server_name) static
Definition at line 90 of file Jackdmp.cpp.
References server_name.
Referenced by main().
print_server_drivers()
void print_server_drivers (jackctl_server_t * server, FILE * file) static
Definition at line 165 of file Jackdmp.cpp.
References _JSList::data, driver, file, jack_slist_next, jackctl_driver_get_name(), jackctl_driver_get_type(), jackctl_server_get_drivers_list(), JackMaster, and server().
Referenced by usage().
print_server_internals()
void print_server_internals (jackctl_server_t * server, FILE * file) static
Definition at line 179 of file Jackdmp.cpp.
References _JSList::data, file, jack_slist_next, jackctl_internal_get_name(), jackctl_server_get_internals_list(), and server().
Referenced by usage().
print_version()
void print_version ()
Definition at line 251 of file Jackdmp.cpp.
References JACK_PROTOCOL_VERSION, jack_server_dir, and VERSION.
Referenced by main().
silent_jack_error_callback()
void silent_jack_error_callback (const char * desc)
Definition at line 146 of file JackError.cpp.
usage()
void usage (FILE * file, jackctl_server_t * server, bool full = true) static
Definition at line 193 of file Jackdmp.cpp.
References jackctl_parameter_value::c, file, i, JACK_DEFAULT_SELF_CONNECT_MODE, jackctl_get_parameter(), jackctl_parameter_get_enum_constraint_description(), jackctl_parameter_get_enum_constraint_value(), jackctl_parameter_get_enum_constraints_count(), jackctl_server_get_parameters(), print_server_drivers(), print_server_internals(), and server().