LMMS: lmms::embed Namespace Reference
lmms::embed Namespace Reference
Namespaces
namespace anonymous_namespace{embed.cpp}
Functions
auto getIconPixmap (std::string_view name, int width=-1, int height=-1, const char *const *xpm=nullptr) -> QPixmap
Return an image for the icon pixmap cache.
auto getText (std::string_view name) -> QString
auto logicalSize (const QPixmap &pixmap) noexcept
Temporary shim for QPixmap::deviceIndependentSize.
Function Documentation
getIconPixmap()
auto LMMS_EXPORT lmms::embed::getIconPixmap (std::string_view name, int width = -1, int height = -1, const char *const * xpm = nullptr)->QPixmap
Return an image for the icon pixmap cache.
Parameters
name Identifier for the pixmap. If it is not in the icon pixmap cache, it will be loaded from the artwork QDir search paths (exceptions are compiled-in XPMs, you need to provide xpm for loading them).
xpm Must be XPM data if the source should be raw XPM data instead of a file
Definition at line 107 of file embed.cpp.
Referenced by lmms::gui::AboutDialog::AboutDialog(), lmms::gui::AutomationEditorWindow::AutomationEditorWindow(), lmms::gui::AutomationTrackView::AutomationTrackView(), lmms::gui::ClipView::ClipView(), lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog(), lmms::gui::ControllerRackView::ControllerRackView(), lmms::gui::Editor::Editor(), lmms::gui::EffectSelectDialog::EffectSelectDialog(), lmms::gui::EnvelopeAndLfoView::EnvelopeAndLfoView(), lmms::gui::FileBrowser::FileBrowser(), lmms::gui::GroupBox::GroupBox(), lmms::gui::GuiApplication::GuiApplication(), lmms::gui::InstrumentMidiIOView::InstrumentMidiIOView(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow(), lmms::gui::InstrumentTuningView::InstrumentTuningView(), lmms::gui::LeftRightNav::LeftRightNav(), lmms::gui::LfoControllerDialog::LfoControllerDialog(), lmms::gui::LmmsStyle::LmmsStyle(), lmms::gui::MainWindow::MainWindow(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::gui::MidiCCRackView::MidiCCRackView(), lmms::gui::MixerChannelView::MixerChannelView(), lmms::gui::MixerView::MixerView(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::PatternTrackView::PatternTrackView(), lmms::gui::PeakControllerDialog::PeakControllerDialog(), lmms::gui::PianoRollWindow::PianoRollWindow(), lmms::gui::PixmapButton::PixmapButton(), lmms::gui::PluginBrowser::PluginBrowser(), lmms::gui::ProjectNotes::ProjectNotes(), lmms::gui::RecentProjectsMenu::RecentProjectsMenu(), lmms::gui::SampleTrackView::SampleTrackView(), lmms::gui::SampleTrackWindow::SampleTrackWindow(), lmms::gui::SetupDialog::SetupDialog(), lmms::gui::SideBarWidget::SideBarWidget(), lmms::gui::SongEditor::SongEditor(), lmms::gui::SongEditorWindow::SongEditorWindow(), lmms::gui::TemplatesMenu::TemplatesMenu(), lmms::gui::TrackGrip::TrackGrip(), lmms::gui::LinkedModelGroupView::addControl(), lmms::gui::AutomatableModelView::addDefaultActions(), lmms::gui::TemplatesMenu::addTemplatesFromDir(), lmms::gui::SubWindow::addTitleButton(), lmms::gui::TimeLineWidget::addToolButtons(), lmms::gui::AutomationClipView::constructContextMenu(), lmms::gui::MidiClipView::constructContextMenu(), lmms::gui::PatternClipView::constructContextMenu(), lmms::gui::SampleClipView::constructContextMenu(), lmms::gui::ClipView::contextMenuEvent(), lmms::gui::ControllerView::contextMenuEvent(), lmms::gui::EffectView::contextMenuEvent(), lmms::gui::FileBrowserTreeWidget::contextMenuEvent(), lmms::gui::MixerChannelView::contextMenuEvent(), lmms::gui::TempoSyncBarModelEditor::contextMenuEvent(), lmms::gui::TempoSyncKnob::contextMenuEvent(), lmms::gui::TrackContentWidget::contextMenuEvent(), lmms::gui::InstrumentTrackView::determinePixmap(), lmms::gui::AutomationClipView::dropEvent(), lmms::gui::AutomationEditorWindow::dropEvent(), lmms::gui::PianoRollWindow::exportMidiClip(), lmms::gui::RecentProjectsMenu::fillMenu(), lmms::gui::MainWindow::finalize(), lmms::gui::MainWindow::handleSaveResult(), lmms::gui::PianoRollWindow::importMidiClip(), lmms::gui::FileItem::initPixmaps(), lmms::gui::LcdWidget::initUi(), lmms::gui::LedCheckBox::initUi(), lmms::gui::LcdFloatSpinBox::layoutSetup(), lmms::gui::EnvelopeAndLfoView::lfoUserWaveChanged(), lmms::DataFile::loadData(), lmms::TrackContainer::loadSettings(), main(), lmms::gui::FileBrowserTreeWidget::mouseMoveEvent(), lmms::gui::ClipView::mousePressEvent(), lmms::gui::TimeLineWidget::mousePressEvent(), lmms::gui::Knob::onKnobNumUpdated(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::SampleClipView::paintEvent(), lmms::gui::TabWidget::paintEvent(), lmms::PixmapLoader::pixmap(), lmms::gui::FileBrowserTreeWidget::previewFileItem(), lmms::gui::Editor::setPauseIcon(), lmms::gui::ProjectNotes::setupActions(), lmms::gui::StepRecorderWidget::showHint(), lmms::gui::Directory::update(), lmms::gui::TempoSyncKnob::updateDescAndIcon(), lmms::gui::TempoSyncBarModelEditor::updateIcon(), lmms::gui::TrackOperationsWidget::updateMenu(), lmms::gui::PianoRollWindow::updateStepRecordingIcon(), and lmms::gui::MainWindow::updateViewMenu().
getText()
auto LMMS_EXPORT lmms::embed::getText (std::string_view name) ->QString
Definition at line 125 of file embed.cpp.
Referenced by lmms::gui::AboutDialog::AboutDialog().
logicalSize()
auto lmms::embed::logicalSize (const QPixmap & pixmap) inline noexcept
Temporary shim for QPixmap::deviceIndependentSize.
Parameters
pixmap The pixmap to get the size of.
Returns
The device-independent size of the pixmap.
Definition at line 65 of file embed.h.
Referenced by lmms::gui::PixmapButton::minimumSizeHint(), and lmms::gui::PixmapButton::setActiveGraphic().