LMMS: lmms::gui::PluginBrowser Class Reference
lmms::gui::PluginBrowser Class Reference
#include <PluginBrowser.h>
Public Member Functions
PluginBrowser (QWidget *_parent)
~PluginBrowser () override=default
Public Member Functions inherited from lmms::gui::SideBarWidget
SideBarWidget (const QString &_title, const QPixmap &_icon, QWidget *_parent)
~SideBarWidget () override=default
const QPixmap & icon () const
const QString & title () const
Private Slots
void onFilterChanged (const QString &filter)
Private Member Functions
void addPlugins ()
void updateRootVisibilities ()
void updateRootVisibility (int index)
Private Attributes
QTreeWidget * m_descTree
QWidget * m_view
Additional Inherited Members
Signals inherited from lmms::gui::SideBarWidget
void closeButtonClicked ()
Protected Member Functions inherited from lmms::gui::SideBarWidget
void addContentLayout (QLayout *_l)
void addContentWidget (QWidget *_w)
QWidget * contentParent ()
void contextMenuEvent (QContextMenuEvent *) override
void paintEvent (QPaintEvent *_pe) override
void resizeEvent (QResizeEvent *_re) override
Detailed Description
Definition at line 38 of file PluginBrowser.h.
Constructor & Destructor Documentation
PluginBrowser()
lmms::gui::PluginBrowser::PluginBrowser (QWidget * _parent)
Definition at line 48 of file PluginBrowser.cpp.
References lmms::gui::SideBarWidget::SideBarWidget(), lmms::gui::SideBarWidget::addContentWidget(), addPlugins(), lmms::gui::SideBarWidget::contentParent(), lmms::embed::getIconPixmap(), m_descTree, m_view, onFilterChanged(), and updateRootVisibilities().
~PluginBrowser()
lmms::gui::PluginBrowser::~PluginBrowser () override default
Member Function Documentation
addPlugins()
void lmms::gui::PluginBrowser::addPlugins () private
Definition at line 142 of file PluginBrowser.cpp.
References lmms::PluginFactory::descriptors(), lmms::getPluginFactory(), lmms::Plugin::Instrument, and m_descTree.
Referenced by PluginBrowser().
onFilterChanged
void lmms::gui::PluginBrowser::onFilterChanged (const QString & filter) private slot
Definition at line 117 of file PluginBrowser.cpp.
References m_descTree.
Referenced by PluginBrowser().
updateRootVisibilities()
void lmms::gui::PluginBrowser::updateRootVisibilities () private
Definition at line 107 of file PluginBrowser.cpp.
References m_descTree, and updateRootVisibility().
Referenced by PluginBrowser().
updateRootVisibility()
void lmms::gui::PluginBrowser::updateRootVisibility (int index) private
Definition at line 100 of file PluginBrowser.cpp.
References m_descTree.
Referenced by updateRootVisibilities().
Member Data Documentation
m_descTree
QTreeWidget* lmms::gui::PluginBrowser::m_descTree private
Definition at line 54 of file PluginBrowser.h.
Referenced by PluginBrowser(), addPlugins(), onFilterChanged(), updateRootVisibilities(), and updateRootVisibility().
m_view
QWidget* lmms::gui::PluginBrowser::m_view private
Definition at line 53 of file PluginBrowser.h.
Referenced by PluginBrowser().
The documentation for this class was generated from the following files:
include/PluginBrowser.h
src/gui/PluginBrowser.cpp