LMMS: lmms::gui::AutomationEditorWindow Class Reference
lmms::gui::AutomationEditorWindow Class Reference
#include <AutomationEditor.h>
Public Slots
void clearCurrentClip ()
Public Slots inherited from lmms::gui::Editor
void togglePause ()
Called by pressing shift+space. Toggles pause state.
void togglePlayStop ()
Called by pressing the space key. Plays or stops.
Signals
void currentClipChanged ()
Public Member Functions
AutomationEditorWindow ()
~AutomationEditorWindow () override=default
const AutomationClip * currentClip ()
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void open (AutomationClip *clip)
void setCurrentClip (AutomationClip *clip)
void setGhostMidiClip (MidiClip *clip)
void setGhostSample (SampleClip *newSample)
QSize sizeHint () const override
Public Member Functions inherited from lmms::gui::Editor
QAction * playAction () const
void setPauseIcon (bool displayPauseIcon=true)
Public Attributes
AutomationEditor * m_editor
Protected Slots
void play () override
void stop () override
Protected Slots inherited from lmms::gui::Editor
virtual void play ()
virtual void record ()
virtual void recordAccompany ()
virtual void stop ()
virtual void toggleStepRecording ()
Protected Member Functions
void focusInEvent (QFocusEvent *event) override
Protected Member Functions inherited from lmms::gui::Editor
Editor (bool record=false, bool record_step=false)
Constructor.
~Editor () override=default
DropToolBar * addDropToolBar (Qt::ToolBarArea whereToAdd, QString const &windowTitle)
DropToolBar * addDropToolBar (QWidget *parent, Qt::ToolBarArea whereToAdd, QString const &windowTitle)
DropToolBar * addDropToolBarToTop (QString const &windowTitle)
void closeEvent (QCloseEvent *event) override
void keyPressEvent (QKeyEvent *ke) override
Private Slots
void setProgressionType (int progType)
void updateEditTanButton ()
The Edit Tangent edit mode should only be available for Cubic Hermite progressions, so this method is responsible for disabling it for other edit modes and reenabling it when it changes back to the Edit Tangent mode.
void updateWindowTitle ()
Private Attributes
QAction * m_cubicHermiteAction
QAction * m_discreteAction
QAction * m_drawAction
QAction * m_drawOutAction
QAction * m_editTanAction
QAction * m_eraseAction
QAction * m_flipXAction
QAction * m_flipYAction
QAction * m_linearAction
ComboBox * m_quantizeComboBox
QPushButton * m_resetGhostNotes
Knob * m_tensionKnob
ComboBox * m_zoomingXComboBox
ComboBox * m_zoomingYComboBox
Static Private Attributes
static const int INITIAL_HEIGHT = 480
static const int INITIAL_WIDTH = 860
Additional Inherited Members
Static Public Member Functions inherited from lmms::gui::Editor
static Editor * lastPlayedEditor ()
Protected Attributes inherited from lmms::gui::Editor
QAction * m_playAction
QAction * m_recordAccompanyAction
QAction * m_recordAction
QAction * m_stopAction
QAction * m_toggleStepRecordingAction
DropToolBar * m_toolBar
Detailed Description
Definition at line 307 of file AutomationEditor.h.
Constructor & Destructor Documentation
AutomationEditorWindow()
lmms::gui::AutomationEditorWindow::AutomationEditorWindow ()
Definition at line 2045 of file AutomationEditor.cpp.
References lmms::gui::Editor::Editor(), lmms::gui::Editor::addDropToolBarToTop(), lmms::combine(), lmms::gui::ComboBox::DEFAULT_HEIGHT, lmms::embed::getIconPixmap(), i, m_cubicHermiteAction, m_discreteAction, m_drawAction, m_drawOutAction, m_editor, m_editTanAction, m_eraseAction, m_flipXAction, m_flipYAction, m_linearAction, lmms::gui::Editor::m_playAction, m_quantizeComboBox, m_resetGhostNotes, lmms::gui::Editor::m_stopAction, m_tensionKnob, lmms::gui::Editor::m_toolBar, m_zoomingXComboBox, m_zoomingYComboBox, lmms::gui::AutomationEditor::resetGhostNotes(), setProgressionType(), and lmms::gui::Small17.
~AutomationEditorWindow()
lmms::gui::AutomationEditorWindow::~AutomationEditorWindow () override default
Member Function Documentation
clearCurrentClip
void lmms::gui::AutomationEditorWindow::clearCurrentClip () slot
Definition at line 2308 of file AutomationEditor.cpp.
References m_editor, and setCurrentClip().
Referenced by setCurrentClip().
currentClip()
const AutomationClip * lmms::gui::AutomationEditorWindow::currentClip ()
Definition at line 2257 of file AutomationEditor.cpp.
References m_editor.
Referenced by lmms::gui::AutomationClipView::paintEvent(), setCurrentClip(), and updateEditTanButton().
currentClipChanged
void lmms::gui::AutomationEditorWindow::currentClipChanged () signal
Referenced by setCurrentClip().
dragEnterEvent()
void lmms::gui::AutomationEditorWindow::dragEnterEvent (QDragEnterEvent * _dee) override
Definition at line 2287 of file AutomationEditor.cpp.
References m_editor, and lmms::gui::StringPairDrag::processDragEnterEvent().
dropEvent()
void lmms::gui::AutomationEditorWindow::dropEvent (QDropEvent * _de) override
Definition at line 2262 of file AutomationEditor.cpp.
References lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::gui::TextFloat::displayMessage(), lmms::embed::getIconPixmap(), lmms::ProjectJournal::journallingObject(), m_editor, lmms::Engine::projectJournal(), and setCurrentClip().
focusInEvent()
void lmms::gui::AutomationEditorWindow::focusInEvent (QFocusEvent * event) override protected
Definition at line 2314 of file AutomationEditor.cpp.
References m_editor.
open()
void lmms::gui::AutomationEditorWindow::open (AutomationClip * clip)
Definition at line 2295 of file AutomationEditor.cpp.
References setCurrentClip().
Referenced by lmms::gui::AutomatableModelViewSlots::editSongGlobalAutomation(), and lmms::gui::AutomationClipView::openInAutomationEditor().
play
void lmms::gui::AutomationEditorWindow::play () override protected slot
Definition at line 2319 of file AutomationEditor.cpp.
References lmms::Engine::getSong(), m_editor, and lmms::gui::Editor::setPauseIcon().
setCurrentClip()
void lmms::gui::AutomationEditorWindow::setCurrentClip (AutomationClip * clip)
Definition at line 2203 of file AutomationEditor.cpp.
References clearCurrentClip(), lmms::AutomationClip::CubicHermite, currentClip(), currentClipChanged(), lmms::AutomationClip::Discrete, lmms::AutomationClip::Linear, m_cubicHermiteAction, m_discreteAction, m_editor, m_flipXAction, m_flipYAction, m_linearAction, m_tensionKnob, updateEditTanButton(), and updateWindowTitle().
Referenced by clearCurrentClip(), lmms::Song::clearProject(), lmms::gui::AutomationClipView::dropEvent(), dropEvent(), and open().
setGhostMidiClip()
void lmms::gui::AutomationEditorWindow::setGhostMidiClip (MidiClip * clip) inline
Definition at line 318 of file AutomationEditor.h.
References m_editor.
Referenced by lmms::gui::MidiClipView::setGhostInAutomationEditor().
setGhostSample()
void lmms::gui::AutomationEditorWindow::setGhostSample (SampleClip * newSample) inline
Definition at line 319 of file AutomationEditor.h.
References m_editor.
Referenced by lmms::gui::SampleClipView::setAutomationGhost().
setProgressionType
void lmms::gui::AutomationEditorWindow::setProgressionType (int progType) private slot
Definition at line 2341 of file AutomationEditor.cpp.
References m_editor, and updateEditTanButton().
Referenced by AutomationEditorWindow().
sizeHint()
QSize lmms::gui::AutomationEditorWindow::sizeHint () const override
Definition at line 2303 of file AutomationEditor.cpp.
References INITIAL_HEIGHT, and INITIAL_WIDTH.
stop
void lmms::gui::AutomationEditorWindow::stop () override protected slot
Definition at line 2325 of file AutomationEditor.cpp.
References m_editor.
updateEditTanButton
void lmms::gui::AutomationEditorWindow::updateEditTanButton () private slot
The Edit Tangent edit mode should only be available for Cubic Hermite progressions, so this method is responsible for disabling it for other edit modes and reenabling it when it changes back to the Edit Tangent mode.
Definition at line 2347 of file AutomationEditor.cpp.
References currentClip(), m_drawAction, m_editTanAction, lmms::AutomationClip::progressionType(), and lmms::AutomationClip::supportsTangentEditing().
Referenced by setCurrentClip(), and setProgressionType().
updateWindowTitle
void lmms::gui::AutomationEditorWindow::updateWindowTitle () private slot
Definition at line 2330 of file AutomationEditor.cpp.
References m_editor.
Referenced by setCurrentClip().
Member Data Documentation
INITIAL_HEIGHT
const int lmms::gui::AutomationEditorWindow::INITIAL_HEIGHT = 480 static private
Definition at line 312 of file AutomationEditor.h.
Referenced by sizeHint().
INITIAL_WIDTH
const int lmms::gui::AutomationEditorWindow::INITIAL_WIDTH = 860 static private
Definition at line 311 of file AutomationEditor.h.
Referenced by sizeHint().
m_cubicHermiteAction
QAction* lmms::gui::AutomationEditorWindow::m_cubicHermiteAction private
Definition at line 364 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), and setCurrentClip().
m_discreteAction
QAction* lmms::gui::AutomationEditorWindow::m_discreteAction private
Definition at line 362 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), and setCurrentClip().
m_drawAction
QAction* lmms::gui::AutomationEditorWindow::m_drawAction private
Definition at line 357 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), and updateEditTanButton().
m_drawOutAction
QAction* lmms::gui::AutomationEditorWindow::m_drawOutAction private
Definition at line 359 of file AutomationEditor.h.
Referenced by AutomationEditorWindow().
m_editor
AutomationEditor* lmms::gui::AutomationEditorWindow::m_editor
Definition at line 328 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), clearCurrentClip(), lmms::Clip::copyStateTo(), currentClip(), lmms::gui::AutomationClipView::disconnectObject(), dragEnterEvent(), dropEvent(), focusInEvent(), lmms::Song::loadProject(), play(), lmms::Song::saveProjectFile(), setCurrentClip(), setGhostMidiClip(), setGhostSample(), setProgressionType(), stop(), and updateWindowTitle().
m_editTanAction
QAction* lmms::gui::AutomationEditorWindow::m_editTanAction private
Definition at line 360 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), and updateEditTanButton().
m_eraseAction
QAction* lmms::gui::AutomationEditorWindow::m_eraseAction private
Definition at line 358 of file AutomationEditor.h.
Referenced by AutomationEditorWindow().
m_flipXAction
QAction* lmms::gui::AutomationEditorWindow::m_flipXAction private
Definition at line 367 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), and setCurrentClip().
m_flipYAction
QAction* lmms::gui::AutomationEditorWindow::m_flipYAction private
Definition at line 366 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), and setCurrentClip().
m_linearAction
QAction* lmms::gui::AutomationEditorWindow::m_linearAction private
Definition at line 363 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), and setCurrentClip().
m_quantizeComboBox
ComboBox* lmms::gui::AutomationEditorWindow::m_quantizeComboBox private
Definition at line 373 of file AutomationEditor.h.
Referenced by AutomationEditorWindow().
m_resetGhostNotes
QPushButton* lmms::gui::AutomationEditorWindow::m_resetGhostNotes private
Definition at line 375 of file AutomationEditor.h.
Referenced by AutomationEditorWindow().
m_tensionKnob
Knob* lmms::gui::AutomationEditorWindow::m_tensionKnob private
Definition at line 369 of file AutomationEditor.h.
Referenced by AutomationEditorWindow(), and setCurrentClip().
m_zoomingXComboBox
ComboBox* lmms::gui::AutomationEditorWindow::m_zoomingXComboBox private
Definition at line 371 of file AutomationEditor.h.
Referenced by AutomationEditorWindow().
m_zoomingYComboBox
ComboBox* lmms::gui::AutomationEditorWindow::m_zoomingYComboBox private
Definition at line 372 of file AutomationEditor.h.
Referenced by AutomationEditorWindow().
The documentation for this class was generated from the following files:
include/AutomationEditor.h
src/gui/editors/AutomationEditor.cpp