LMMS: hiir::StageProcSseV4< CUR > Class Template Reference
hiir::StageProcSseV4< CUR > Class Template Reference
#include <StageProcSseV4.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg (StageDataSse *, __m128 &, __m128 &) noexcept
hiir_FORCEINLINE void process_sample_pos (StageDataSse *, __m128 &, __m128 &) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (StageDataSse *stage_ptr, __m128 &y, __m128 &mem) noexcept
static hiir_FORCEINLINE void process_sample_pos (StageDataSse *stage_ptr, __m128 &y, __m128 &mem) noexcept
Private Member Functions
StageProcSseV4 ()=delete
StageProcSseV4 (const StageProcSseV4< CUR > &other)=delete
StageProcSseV4 (StageProcSseV4< CUR > &&other)=delete
~StageProcSseV4 ()=delete
bool operator!= (const StageProcSseV4< CUR > &other)=delete
StageProcSseV4< CUR > & operator= (const StageProcSseV4< CUR > &other)=delete
StageProcSseV4< CUR > & operator= (StageProcSseV4< CUR > &&other)=delete
bool operator== (const StageProcSseV4< CUR > &other)=delete
Static Private Attributes
static constexpr int PREV = CUR - 1
Detailed Description
template<int CUR>
class hiir::StageProcSseV4< CUR >
Definition at line 47 of file StageProcSseV4.h.
Constructor & Destructor Documentation
StageProcSseV4() [1/3]
template<int CUR> hiir::StageProcSseV4< CUR >::StageProcSseV4 () private delete
Referenced by process_sample_neg(), and process_sample_pos().
StageProcSseV4() [2/3]
template<int CUR> hiir::StageProcSseV4< CUR >::StageProcSseV4 (const StageProcSseV4< CUR > & other) private delete
StageProcSseV4() [3/3]
template<int CUR> hiir::StageProcSseV4< CUR >::StageProcSseV4 (StageProcSseV4< CUR > && other) private delete
~StageProcSseV4()
template<int CUR> hiir::StageProcSseV4< CUR >::~StageProcSseV4 () private delete
Member Function Documentation
operator!=()
template<int CUR> bool hiir::StageProcSseV4< CUR >::operator!= (const StageProcSseV4< CUR > & other) private delete
operator=() [1/2]
template<int CUR> StageProcSseV4< CUR > & hiir::StageProcSseV4< CUR >::operator= (const StageProcSseV4< CUR > & other) private delete
operator=() [2/2]
template<int CUR> StageProcSseV4< CUR > & hiir::StageProcSseV4< CUR >::operator= (StageProcSseV4< CUR > && other) private delete
operator==()
template<int CUR> bool hiir::StageProcSseV4< CUR >::operator== (const StageProcSseV4< CUR > & other) private delete
process_sample_neg() [1/2]
hiir_FORCEINLINE void hiir::StageProcSseV4< 0 >::process_sample_neg (StageDataSse * , __m128 & , __m128 &) noexcept
Definition at line 82 of file StageProcSseV4.hpp.
References hiir_FORCEINLINE.
process_sample_neg() [2/2]
template<int CUR> void hiir::StageProcSseV4< CUR >::process_sample_neg (StageDataSse * stage_ptr, __m128 & y, __m128 & mem) static noexcept
Definition at line 67 of file StageProcSseV4.hpp.
References StageProcSseV4(), PREV, and process_sample_neg().
Referenced by hiir::PhaseHalfPiSse< NC >::process_block_quad(), hiir::PhaseHalfPiSse< NC >::process_sample(), and process_sample_neg().
process_sample_pos() [1/2]
hiir_FORCEINLINE void hiir::StageProcSseV4< 0 >::process_sample_pos (StageDataSse * , __m128 & , __m128 &) noexcept
Definition at line 59 of file StageProcSseV4.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [2/2]
template<int CUR> void hiir::StageProcSseV4< CUR >::process_sample_pos (StageDataSse * stage_ptr, __m128 & y, __m128 & mem) static noexcept
Definition at line 44 of file StageProcSseV4.hpp.
References StageProcSseV4(), PREV, and process_sample_pos().
Referenced by hiir::HalfBandSse< NC >::process_2_paths(), hiir::Downsampler2xSseOld< NC >::process_block_quad(), hiir::HalfBandSse< NC >::process_block_quad(), hiir::Upsampler2xSseOld< NC >::process_block_quad(), hiir::Downsampler2xSseOld< NC >::process_sample(), hiir::Upsampler2xSseOld< NC >::process_sample(), process_sample_pos(), and hiir::Downsampler2xSseOld< NC >::process_sample_split().
Member Data Documentation
PREV
template<int CUR> int hiir::StageProcSseV4< CUR >::PREV = CUR - 1 static constexpr private
Definition at line 73 of file StageProcSseV4.h.
Referenced by process_sample_neg(), and process_sample_pos().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProcSseV4.h
src/3rdparty/hiir/hiir/StageProcSseV4.hpp