LMMS: lmms::PluginIssue Class Reference
lmms::PluginIssue Class Reference
Issue type bundled with informational string.
#include <PluginIssue.h>
Public Member Functions
PluginIssue (PluginIssueType it, std::string msg=std::string())
bool operator< (const PluginIssue &other) const
bool operator== (const PluginIssue &other) const
PluginIssueType type () const
Static Private Member Functions
static const char * msgFor (const PluginIssueType &it)
Private Attributes
std::string m_info
PluginIssueType m_issueType
Friends
QDebug operator<< (QDebug stream, const PluginIssue &iss)
Detailed Description
Issue type bundled with informational string.
Definition at line 65 of file PluginIssue.h.
Constructor & Destructor Documentation
PluginIssue()
lmms::PluginIssue::PluginIssue (PluginIssueType it, std::string msg = std::string()) inline
Definition at line 73 of file PluginIssue.h.
References m_info, and m_issueType.
Referenced by operator<(), operator<<, and operator==().
Member Function Documentation
msgFor()
const char * lmms::PluginIssue::msgFor (const PluginIssueType & it) static private
Definition at line 33 of file PluginIssue.cpp.
References lmms::BadPortType, lmms::Blocked, lmms::DefaultValueNotInRange, lmms::FeatureNotSupported, lmms::LogScaleMaxMissing, lmms::LogScaleMinMaxDifferentSigns, lmms::LogScaleMinMissing, lmms::MinGreaterMax, lmms::NoIssue, lmms::NoOutputChannel, lmms::PortHasNoDef, lmms::PortHasNoMax, lmms::PortHasNoMin, lmms::TooManyInputChannels, lmms::TooManyMidiInputChannels, lmms::TooManyMidiOutputChannels, lmms::TooManyOutputChannels, lmms::UnknownPortFlow, and lmms::UnknownPortType.
Referenced by operator<<.
operator<()
bool lmms::PluginIssue::operator< (const PluginIssue & other) const
Definition at line 90 of file PluginIssue.cpp.
References PluginIssue(), m_info, and m_issueType.
operator==()
bool lmms::PluginIssue::operator== (const PluginIssue & other) const
Definition at line 82 of file PluginIssue.cpp.
References PluginIssue(), m_info, and m_issueType.
type()
PluginIssueType lmms::PluginIssue::type () const inline
Definition at line 77 of file PluginIssue.h.
References m_issueType.
Friends And Related Symbol Documentation
operator<<
QDebug operator<< (QDebug stream, const PluginIssue & iss) friend
Definition at line 98 of file PluginIssue.cpp.
References PluginIssue(), m_info, m_issueType, and msgFor().
Member Data Documentation
m_info
std::string lmms::PluginIssue::m_info private
Definition at line 70 of file PluginIssue.h.
Referenced by PluginIssue(), operator<(), operator<<, and operator==().
m_issueType
PluginIssueType lmms::PluginIssue::m_issueType private
Definition at line 69 of file PluginIssue.h.
Referenced by PluginIssue(), operator<(), operator<<, operator==(), and type().
The documentation for this class was generated from the following files:
include/PluginIssue.h
src/core/PluginIssue.cpp