LMMS: src/3rdparty/jack2/freebsd/oss/JackOSSDriver.cpp File Reference
JackOSSDriver.cpp File Reference
#include "driver_interface.h"
#include "JackThreadedDriver.h"
#include "JackDriverLoader.h"
#include "JackOSSDriver.h"
#include "JackEngineControl.h"
#include "JackGraphManager.h"
#include "JackError.h"
#include "JackTime.h"
#include "JackShmMem.h"
#include "memops.h"
#include <sys/ioctl.h>
#include <sys/soundcard.h>
#include <fcntl.h>
#include <iostream>
#include <assert.h>
#include <stdio.h>
Namespaces
namespace anonymous_namespace{JackOSSDriver.cpp}
namespace Jack
Functions
static void Jack::CopyAndConvertIn (jack_sample_t *dst, void *src, size_t nframes, int channel, int chcount, int bits)
static void Jack::CopyAndConvertOut (void *dst, jack_sample_t *src, size_t nframes, int channel, int chcount, int bits)
SERVER_EXPORT jack_driver_desc_t * driver_get_descriptor ()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine *engine, Jack::JackSynchro *table, const JSList *params)
jack_time_t anonymous_namespace{JackOSSDriver.cpp}::FramesToTime (jack_nframes_t frames, jack_nframes_t sample_rate)
int anonymous_namespace{JackOSSDriver.cpp}::GetSampleFormat (int bits)
unsigned int anonymous_namespace{JackOSSDriver.cpp}::GetSampleSize (int format)
jack_time_t anonymous_namespace{JackOSSDriver.cpp}::RoundDown (jack_time_t time, jack_time_t interval)
jack_nframes_t anonymous_namespace{JackOSSDriver.cpp}::RoundUp (jack_nframes_t frames, jack_nframes_t block)
jack_nframes_t anonymous_namespace{JackOSSDriver.cpp}::TimeToFrames (jack_time_t time, jack_nframes_t sample_rate)
long long anonymous_namespace{JackOSSDriver.cpp}::TimeToOffset (jack_time_t time1, jack_time_t time2, jack_nframes_t sample_rate)
int anonymous_namespace{JackOSSDriver.cpp}::UpToPower2 (int x)
Function Documentation
driver_get_descriptor()
SERVER_EXPORT jack_driver_desc_t * driver_get_descriptor ()
Definition at line 1275 of file JackOSSDriver.cpp.
References jack_driver_param_value_t::i, jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverMaster, JackDriverParamBool, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, OSS_DRIVER_DEF_BITS, OSS_DRIVER_DEF_BLKSIZE, OSS_DRIVER_DEF_DEV, OSS_DRIVER_DEF_FS, OSS_DRIVER_DEF_INS, OSS_DRIVER_DEF_NPERIODS, OSS_DRIVER_DEF_OUTS, SERVER_EXPORT, jack_driver_param_value_t::str, and jack_driver_param_value_t::ui.
driver_initialize()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine * engine, Jack::JackSynchro * table, const JSList * params)
Definition at line 1319 of file JackOSSDriver.cpp.
References jack_driver_param_t::character, _JSList::data, jack_driver_param_value_t::i, jack_slist_next, Jack::JackOSSDriver::Open(), OSS_DRIVER_DEF_BITS, OSS_DRIVER_DEF_BLKSIZE, OSS_DRIVER_DEF_DEV, OSS_DRIVER_DEF_FS, OSS_DRIVER_DEF_NPERIODS, SERVER_EXPORT, jack_driver_param_value_t::str, jack_driver_param_value_t::ui, and jack_driver_param_t::value.