LMMS: Jack::JackShmReadPtr< T > Class Template Reference
Jack::JackShmReadPtr< T > Class Template Reference
Pointer on shared memory segment in the client side.
#include <JackShmMem.h>
Public Member Functions
JackShmReadPtr ()
JackShmReadPtr (int index, const char *server_name)
~JackShmReadPtr ()
T * GetShmAddress ()
int GetShmIndex ()
operator T* () const
T * operator-> () const
JackShmReadPtr & operator= (int index)
void SetShmIndex (int index, const char *server_name)
Private Member Functions
void Init (int index, const char *server_name=JACK_DEFAULT_SERVER_NAME)
Private Attributes
jack_shm_info_t fInfo
bool fInitDone
Detailed Description
template<class T>
class Jack::JackShmReadPtr< T >
Pointer on shared memory segment in the client side.
Definition at line 293 of file JackShmMem.h.
Constructor & Destructor Documentation
JackShmReadPtr() [1/2]
template<class T> Jack::JackShmReadPtr< T >::JackShmReadPtr () inline
Definition at line 319 of file JackShmMem.h.
References fInfo, and fInitDone.
Referenced by operator=().
JackShmReadPtr() [2/2]
template<class T> Jack::JackShmReadPtr< T >::JackShmReadPtr (int index, const char * server_name) inline
Definition at line 326 of file JackShmMem.h.
References Init(), and server_name.
~JackShmReadPtr()
template<class T> Jack::JackShmReadPtr< T >::~JackShmReadPtr () inline
Definition at line 331 of file JackShmMem.h.
References fInfo, fInitDone, GetShmAddress(), jack_error, jack_log(), and jack_release_lib_shm().
Member Function Documentation
GetShmAddress()
template<class T> T * Jack::JackShmReadPtr< T >::GetShmAddress () inline
Definition at line 371 of file JackShmMem.h.
References fInfo.
Referenced by ~JackShmReadPtr(), and Init().
GetShmIndex()
template<class T> int Jack::JackShmReadPtr< T >::GetShmIndex () inline
Definition at line 366 of file JackShmMem.h.
References fInfo.
Init()
template<class T> void Jack::JackShmReadPtr< T >::Init (int index, const char * server_name = JACK_DEFAULT_SERVER_NAME) inline private
Definition at line 301 of file JackShmMem.h.
References fInfo, fInitDone, GetShmAddress(), jack_attach_lib_shm_read(), JACK_DEFAULT_SERVER_NAME, jack_initialize_shm(), jack_log(), and server_name.
Referenced by JackShmReadPtr(), operator=(), and SetShmIndex().
operator T*()
template<class T> Jack::JackShmReadPtr< T >::operator T* () const inline
Definition at line 350 of file JackShmMem.h.
References fInfo.
operator->()
template<class T> T * Jack::JackShmReadPtr< T >::operator-> () const inline
Definition at line 345 of file JackShmMem.h.
References fInfo.
operator=()
template<class T> JackShmReadPtr & Jack::JackShmReadPtr< T >::operator= (int index) inline
Definition at line 355 of file JackShmMem.h.
References JackShmReadPtr(), and Init().
SetShmIndex()
template<class T> void Jack::JackShmReadPtr< T >::SetShmIndex (int index, const char * server_name) inline
Definition at line 361 of file JackShmMem.h.
References Init(), and server_name.
Member Data Documentation
fInfo
template<class T> jack_shm_info_t Jack::JackShmReadPtr< T >::fInfo private
Definition at line 298 of file JackShmMem.h.
Referenced by JackShmReadPtr(), ~JackShmReadPtr(), GetShmAddress(), GetShmIndex(), Init(), operator T*(), and operator->().
fInitDone
template<class T> bool Jack::JackShmReadPtr< T >::fInitDone private
Definition at line 299 of file JackShmMem.h.
Referenced by JackShmReadPtr(), ~JackShmReadPtr(), and Init().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackShmMem.h