LMMS: Jack::JackWinMMEInputPort Class Reference
Jack::JackWinMMEInputPort Class Reference
#include <JackWinMMEInputPort.h>
Public Member Functions
JackWinMMEInputPort (const char *alias_name, const char *client_name, const char *driver_name, UINT index, size_t max_bytes=4096, size_t max_messages=1024)
~JackWinMMEInputPort ()
void ProcessJack (JackMidiBuffer *port_buffer, jack_nframes_t frames)
bool Start ()
bool Stop ()
Public Member Functions inherited from Jack::JackWinMMEPort
JackWinMMEPort ()
~JackWinMMEPort ()
const char * GetAlias ()
const char * GetDeviceName ()
const char * GetName ()
void GetOSErrorString (LPTSTR text)
void WriteOSError (const char *jack_func, const char *os_func)
Private Member Functions
void EnqueueMessage (DWORD timestamp, size_t length, jack_midi_data_t *data)
void GetInErrorString (MMRESULT error, LPTSTR text)
void ProcessWinMME (UINT message, DWORD_PTR param1, DWORD_PTR param2)
void WriteInError (const char *jack_func, const char *mm_func, MMRESULT result)
Static Private Member Functions
static void CALLBACK HandleMidiInputEvent (HMIDIIN handle, UINT message, DWORD_PTR port, DWORD_PTR param1, DWORD_PTR param2)
Private Attributes
HMIDIIN handle
jack_midi_event_t * jack_event
jack_time_t start_time
bool started
jack_midi_data_t * sysex_buffer
MIDIHDR sysex_header
JackMidiAsyncQueue * thread_queue
JackMidiBufferWriteQueue * write_queue
Additional Inherited Members
Protected Attributes inherited from Jack::JackWinMMEPort
char alias [REAL_JACK_PORT_NAME_SIZE+1]
char device_name [REAL_JACK_PORT_NAME_SIZE+1]
char name [REAL_JACK_PORT_NAME_SIZE+1]
Detailed Description
Definition at line 31 of file JackWinMMEInputPort.h.
Constructor & Destructor Documentation
JackWinMMEInputPort()
JackWinMMEInputPort::JackWinMMEInputPort (const char * alias_name, const char * client_name, const char * driver_name, UINT index, size_t max_bytes = 4096, size_t max_messages = 1024)
Definition at line 49 of file JackWinMMEInputPort.cpp.
References Jack::JackWinMMEPort::alias, Jack::JackWinMMEPort::device_name, GetInErrorString(), handle, HandleMidiInputEvent(), jack_event, Jack::JackWinMMEPort::name, started, sysex_buffer, sysex_header, thread_queue, write_queue, and WriteInError().
Referenced by HandleMidiInputEvent().
~JackWinMMEInputPort()
JackWinMMEInputPort::~JackWinMMEInputPort ()
Definition at line 120 of file JackWinMMEInputPort.cpp.
References handle, sysex_buffer, sysex_header, thread_queue, write_queue, and WriteInError().
Member Function Documentation
EnqueueMessage()
void JackWinMMEInputPort::EnqueueMessage (DWORD timestamp, size_t length, jack_midi_data_t * data) private
Definition at line 141 of file JackWinMMEInputPort.cpp.
References Jack::JackMidiWriteQueue::BUFFER_FULL, Jack::JackMidiWriteQueue::BUFFER_TOO_SMALL, Jack::GetFramesFromTime(), GetMicroSeconds(), jack_error, jack_log(), start_time, and thread_queue.
Referenced by ProcessWinMME().
GetInErrorString()
void JackWinMMEInputPort::GetInErrorString (MMRESULT error, LPTSTR text) private
Definition at line 172 of file JackWinMMEInputPort.cpp.
Referenced by JackWinMMEInputPort(), and WriteInError().
HandleMidiInputEvent()
void CALLBACK JackWinMMEInputPort::HandleMidiInputEvent (HMIDIIN handle, UINT message, DWORD_PTR port, DWORD_PTR param1, DWORD_PTR param2) static private
Definition at line 37 of file JackWinMMEInputPort.cpp.
References JackWinMMEInputPort(), handle, and ProcessWinMME().
Referenced by JackWinMMEInputPort().
ProcessJack()
void JackWinMMEInputPort::ProcessJack (JackMidiBuffer * port_buffer, jack_nframes_t frames)
Definition at line 181 of file JackWinMMEInputPort.cpp.
References Jack::JackMidiWriteQueue::BUFFER_TOO_SMALL, jack_error, jack_event, Jack::JackMidiWriteQueue::OK, thread_queue, and write_queue.
ProcessWinMME()
void JackWinMMEInputPort::ProcessWinMME (UINT message, DWORD_PTR param1, DWORD_PTR param2) private
Definition at line 205 of file JackWinMMEInputPort.cpp.
References EnqueueMessage(), Jack::GetMessageLength(), handle, jack_error, jack_log(), set_threaded_log_function(), sysex_header, and WriteInError().
Referenced by HandleMidiInputEvent().
Start()
bool JackWinMMEInputPort::Start ()
Definition at line 283 of file JackWinMMEInputPort.cpp.
References GetMicroSeconds(), handle, start_time, started, and WriteInError().
Stop()
bool JackWinMMEInputPort::Stop ()
Definition at line 297 of file JackWinMMEInputPort.cpp.
References handle, started, and WriteInError().
WriteInError()
void JackWinMMEInputPort::WriteInError (const char * jack_func, const char * mm_func, MMRESULT result) private
Definition at line 310 of file JackWinMMEInputPort.cpp.
References GetInErrorString(), and jack_error.
Referenced by JackWinMMEInputPort(), ~JackWinMMEInputPort(), ProcessWinMME(), Start(), and Stop().
Member Data Documentation
handle
HMIDIIN Jack::JackWinMMEInputPort::handle private
Definition at line 54 of file JackWinMMEInputPort.h.
Referenced by JackWinMMEInputPort(), ~JackWinMMEInputPort(), HandleMidiInputEvent(), ProcessWinMME(), Start(), and Stop().
jack_event
jack_midi_event_t* Jack::JackWinMMEInputPort::jack_event private
Definition at line 55 of file JackWinMMEInputPort.h.
Referenced by JackWinMMEInputPort(), and ProcessJack().
start_time
jack_time_t Jack::JackWinMMEInputPort::start_time private
Definition at line 56 of file JackWinMMEInputPort.h.
Referenced by EnqueueMessage(), and Start().
started
bool Jack::JackWinMMEInputPort::started private
Definition at line 57 of file JackWinMMEInputPort.h.
Referenced by JackWinMMEInputPort(), Start(), and Stop().
sysex_buffer
jack_midi_data_t* Jack::JackWinMMEInputPort::sysex_buffer private
Definition at line 58 of file JackWinMMEInputPort.h.
Referenced by JackWinMMEInputPort(), and ~JackWinMMEInputPort().
sysex_header
MIDIHDR Jack::JackWinMMEInputPort::sysex_header private
Definition at line 59 of file JackWinMMEInputPort.h.
Referenced by JackWinMMEInputPort(), ~JackWinMMEInputPort(), and ProcessWinMME().
thread_queue
JackMidiAsyncQueue* Jack::JackWinMMEInputPort::thread_queue private
Definition at line 60 of file JackWinMMEInputPort.h.
Referenced by JackWinMMEInputPort(), ~JackWinMMEInputPort(), EnqueueMessage(), and ProcessJack().
write_queue
JackMidiBufferWriteQueue* Jack::JackWinMMEInputPort::write_queue private
Definition at line 61 of file JackWinMMEInputPort.h.
Referenced by JackWinMMEInputPort(), ~JackWinMMEInputPort(), and ProcessJack().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/winmme/JackWinMMEInputPort.h
src/3rdparty/jack2/windows/winmme/JackWinMMEInputPort.cpp