LMMS: Jack::JackWinSemaphore Class Reference
Jack::JackWinSemaphore Class Reference
Inter process synchronization using system wide semaphore.
#include <JackWinSemaphore.h>
Public Member Functions
JackWinSemaphore ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Public Member Functions inherited from Jack::detail::JackSynchro
JackSynchro ()
~JackSynchro ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
void SetFlush (bool mode)
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Protected Member Functions
void BuildName (const char *name, const char *server_name, char *res, int size)
Private Attributes
HANDLE fSemaphore
Additional Inherited Members
Protected Attributes inherited from Jack::detail::JackSynchro
bool fFlush
char fName [SYNC_MAX_NAME_SIZE]
Detailed Description
Inter process synchronization using system wide semaphore.
Definition at line 38 of file JackWinSemaphore.h.
Constructor & Destructor Documentation
JackWinSemaphore()
Jack::JackWinSemaphore::JackWinSemaphore () inline
Definition at line 51 of file JackWinSemaphore.h.
References Jack::detail::JackSynchro::JackSynchro(), and fSemaphore.
Member Function Documentation
Allocate()
bool Jack::JackWinSemaphore::Allocate (const char * name, const char * server_name, int value)
Definition at line 132 of file JackWinSemaphore.cpp.
References BuildName(), FALSE, Jack::detail::JackSynchro::fName, fSemaphore, jack_error, jack_log(), and server_name.
BuildName()
void Jack::JackWinSemaphore::BuildName (const char * name, const char * server_name, char * res, int size) protected
Definition at line 29 of file JackWinSemaphore.cpp.
References Jack::JackTools::RewriteName(), server_name, and SYNC_MAX_NAME_SIZE.
Referenced by Allocate(), and ConnectInput().
Connect()
bool Jack::JackWinSemaphore::Connect (const char * name, const char * server_name)
Definition at line 110 of file JackWinSemaphore.cpp.
References ConnectInput(), and server_name.
ConnectInput()
bool Jack::JackWinSemaphore::ConnectInput (const char * name, const char * server_name)
Definition at line 91 of file JackWinSemaphore.cpp.
References BuildName(), FALSE, Jack::detail::JackSynchro::fName, fSemaphore, jack_error, jack_log(), and server_name.
Referenced by Connect(), and ConnectOutput().
ConnectOutput()
bool Jack::JackWinSemaphore::ConnectOutput (const char * name, const char * server_name)
Definition at line 115 of file JackWinSemaphore.cpp.
References ConnectInput(), and server_name.
Destroy()
void Jack::JackWinSemaphore::Destroy ()
Definition at line 150 of file JackWinSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, jack_error, and jack_log().
Disconnect()
bool Jack::JackWinSemaphore::Disconnect ()
Definition at line 120 of file JackWinSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, and jack_log().
Signal()
bool Jack::JackWinSemaphore::Signal ()
Definition at line 36 of file JackWinSemaphore.cpp.
References Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
SignalAll()
bool Jack::JackWinSemaphore::SignalAll ()
Definition at line 52 of file JackWinSemaphore.cpp.
References Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
TimedWait()
bool Jack::JackWinSemaphore::TimedWait (long usec)
Definition at line 79 of file JackWinSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
Wait()
bool Jack::JackWinSemaphore::Wait ()
Definition at line 68 of file JackWinSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
Member Data Documentation
fSemaphore
HANDLE Jack::JackWinSemaphore::fSemaphore private
Definition at line 43 of file JackWinSemaphore.h.
Referenced by JackWinSemaphore(), Allocate(), ConnectInput(), Destroy(), Disconnect(), Signal(), SignalAll(), TimedWait(), and Wait().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinSemaphore.h
src/3rdparty/jack2/windows/JackWinSemaphore.cpp