LMMS: lmms::Mixer Class Reference
lmms::Mixer Class Reference
#include <Mixer.h>
Public Member Functions
Mixer ()
~Mixer () override
void activateSolo ()
FloatModel * channelSendModel (mix_ch_t fromChannel, mix_ch_t toChannel)
bool checkInfiniteLoop (MixerChannel *from, MixerChannel *to)
void clear ()
void clearChannel (mix_ch_t channelIndex)
int createChannel ()
MixerRoute * createChannelSend (mix_ch_t fromChannel, mix_ch_t toChannel, float amount=1.0f)
MixerRoute * createRoute (MixerChannel *from, MixerChannel *to, float amount)
void deactivateSolo ()
void deleteChannel (int index)
void deleteChannelSend (mix_ch_t fromChannel, mix_ch_t toChannel)
void deleteChannelSend (MixerRoute *route)
bool isChannelInUse (int index)
bool isInfiniteLoop (mix_ch_t fromChannel, mix_ch_t toChannel)
void loadSettings (const QDomElement &_this) override
void masterMix (SampleFrame *_buf)
MixerChannel * mixerChannel (int _ch)
void mixToChannel (const SampleFrame *_buf, mix_ch_t _ch)
void moveChannelLeft (int index)
void moveChannelRight (int index)
QString nodeName () const override
mix_ch_t numChannels () const
void prepareMasterMix ()
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
void toggledSolo ()
void validateChannelName (int index, int oldIndex)
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Public Attributes
MixerRouteVector m_mixerRoutes
Private Member Functions
void allocateChannelsTo (int num)
Private Attributes
int m_lastSoloed
std::vector< MixerChannel * > m_mixerChannels
Additional Inherited Members
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 139 of file Mixer.h.
Constructor & Destructor Documentation
Mixer()
lmms::Mixer::Mixer ()
Definition at line 235 of file Mixer.cpp.
References lmms::JournallingObject::JournallingObject(), lmms::Model::Model(), createChannel(), m_lastSoloed, and m_mixerChannels.
~Mixer()
lmms::Mixer::~Mixer () override
Definition at line 247 of file Mixer.cpp.
References deleteChannelSend(), m_mixerChannels, and m_mixerRoutes.
Member Function Documentation
activateSolo()
void lmms::Mixer::activateSolo ()
Definition at line 282 of file Mixer.cpp.
References i, and m_mixerChannels.
Referenced by toggledSolo().
allocateChannelsTo()
void lmms::Mixer::allocateChannelsTo (int num) private
Definition at line 821 of file Mixer.cpp.
References createChannel(), deleteChannelSend(), and m_mixerChannels.
Referenced by loadSettings().
channelSendModel()
FloatModel * lmms::Mixer::channelSendModel (mix_ch_t fromChannel, mix_ch_t toChannel)
Definition at line 623 of file Mixer.cpp.
References lmms::MixerRoute::amount(), m_mixerChannels, lmms::MixerChannel::m_sends, and lmms::MixerRoute::receiver().
Referenced by lmms::gui::SendButtonIndicator::getSendModel(), and lmms::gui::SendButtonIndicator::mousePressEvent().
checkInfiniteLoop()
bool lmms::Mixer::checkInfiniteLoop (MixerChannel * from, MixerChannel * to)
Definition at line 594 of file Mixer.cpp.
References checkInfiniteLoop(), m_mixerChannels, and lmms::MixerChannel::m_sends.
Referenced by checkInfiniteLoop(), and isInfiniteLoop().
clear()
void lmms::Mixer::clear ()
Definition at line 745 of file Mixer.cpp.
References clearChannel(), deleteChannel(), and m_mixerChannels.
Referenced by lmms::Song::clearProject(), and loadSettings().
clearChannel()
void lmms::Mixer::clearChannel (mix_ch_t channelIndex)
Definition at line 757 of file Mixer.cpp.
References lmms::EffectChain::clear(), createChannelSend(), deleteChannelSend(), lmms::MixerChannel::m_fxChain, m_mixerChannels, lmms::MixerChannel::m_muteModel, lmms::MixerChannel::m_name, lmms::MixerChannel::m_receives, lmms::MixerChannel::m_sends, lmms::MixerChannel::m_soloModel, lmms::MixerChannel::m_volumeModel, lmms::MixerChannel::setColor(), lmms::Model::setDisplayName(), and lmms::AutomatableModel::setValue().
Referenced by lmms::gui::MixerView::clear(), clear(), createChannel(), and lmms::gui::MixerView::deleteChannel().
createChannel()
int lmms::Mixer::createChannel ()
Definition at line 263 of file Mixer.cpp.
References clearChannel(), m_lastSoloed, and m_mixerChannels.
Referenced by Mixer(), lmms::gui::MixerView::addNewChannel(), and allocateChannelsTo().
createChannelSend()
MixerRoute * lmms::Mixer::createChannelSend (mix_ch_t fromChannel, mix_ch_t toChannel, float amount = 1.0f)
Definition at line 495 of file Mixer.cpp.
References createRoute(), m_mixerChannels, and lmms::MixerChannel::m_sends.
Referenced by clearChannel(), loadSettings(), and lmms::gui::SendButtonIndicator::mousePressEvent().
createRoute()
MixerRoute * lmms::Mixer::createRoute (MixerChannel * from, MixerChannel * to, float amount)
Definition at line 518 of file Mixer.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), m_mixerRoutes, lmms::MixerChannel::m_receives, lmms::MixerChannel::m_sends, lmms::Engine::mixer(), and lmms::AudioEngine::requestChangeInModel().
Referenced by createChannelSend().
deactivateSolo()
void lmms::Mixer::deactivateSolo ()
Definition at line 291 of file Mixer.cpp.
References i, and m_mixerChannels.
Referenced by toggledSolo().
deleteChannel()
void lmms::Mixer::deleteChannel (int index)
Definition at line 334 of file Mixer.cpp.
References lmms::Engine::audioEngine(), deleteChannelSend(), lmms::AudioEngine::doneChangeInModel(), lmms::Engine::getSong(), i, lmms::Track::Instrument, m_lastSoloed, m_mixerChannels, lmms::MixerChannel::m_receives, lmms::MixerChannel::m_sends, lmms::InstrumentTrack::mixerChannelModel(), lmms::SampleTrack::mixerChannelModel(), lmms::Engine::patternStore(), lmms::AudioEngine::requestChangeInModel(), lmms::Track::Sample, lmms::TrackContainer::tracks(), validateChannelName(), and lmms::TypedAutomatableModel< T >::value().
Referenced by clear(), and lmms::gui::MixerView::deleteChannel().
deleteChannelSend() [1/2]
void lmms::Mixer::deleteChannelSend (mix_ch_t fromChannel, mix_ch_t toChannel)
Definition at line 542 of file Mixer.cpp.
References deleteChannelSend(), m_mixerChannels, and lmms::MixerChannel::m_sends.
Referenced by ~Mixer(), allocateChannelsTo(), clearChannel(), deleteChannel(), deleteChannelSend(), and lmms::gui::SendButtonIndicator::mousePressEvent().
deleteChannelSend() [2/2]
void lmms::Mixer::deleteChannelSend (MixerRoute * route)
Definition at line 560 of file Mixer.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), m_mixerRoutes, lmms::MixerChannel::m_receives, lmms::MixerChannel::m_sends, lmms::Engine::mixer(), lmms::MixerRoute::receiver(), lmms::AudioEngine::requestChangeInModel(), and lmms::MixerRoute::sender().
isChannelInUse()
bool lmms::Mixer::isChannelInUse (int index)
Definition at line 892 of file Mixer.cpp.
References lmms::Engine::getSong(), lmms::Track::Instrument, m_mixerChannels, lmms::Engine::patternStore(), lmms::Track::Sample, and lmms::TrackContainer::tracks().
Referenced by lmms::gui::MixerView::deleteUnusedChannels().
isInfiniteLoop()
bool lmms::Mixer::isInfiniteLoop (mix_ch_t fromChannel, mix_ch_t toChannel)
Definition at line 584 of file Mixer.cpp.
References checkInfiniteLoop(), and m_mixerChannels.
loadSettings()
void lmms::Mixer::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 834 of file Mixer.cpp.
References allocateChannelsTo(), lmms::MixerRoute::amount(), clear(), createChannelSend(), lmms::Model::dataChanged(), i, lmms::AutomatableModel::loadSettings(), and m_mixerChannels.
masterMix()
void lmms::Mixer::masterMix (SampleFrame * _buf)
Definition at line 666 of file Mixer.cpp.
References lmms::AudioEngineWorkerThread::addJob(), lmms::MixHelpers::addSanitizedMultiplied(), lmms::Engine::audioEngine(), lmms::ThreadableJob::Done, lmms::AudioEngineWorkerThread::JobQueue::Dynamic, lmms::AudioEngine::framesPerPeriod(), i, lmms::ThreadableJob::InProgress, m_mixerChannels, numChannels(), lmms::ThreadableJob::Queued, lmms::AudioEngineWorkerThread::resetJobQueue(), lmms::AudioEngineWorkerThread::startAndWaitForJobs(), lmms::ValueBuffer::values(), and lmms::zeroSampleFrames().
Referenced by lmms::AudioEngine::renderStageMix().
mixerChannel()
MixerChannel * lmms::Mixer::mixerChannel (int _ch) inline
Definition at line 159 of file Mixer.h.
References m_mixerChannels.
Referenced by lmms::gui::MixerChannelView::MixerChannelView(), lmms::gui::MixerView::connectToSoloAndMute(), lmms::gui::InstrumentTrackView::createMixerLine(), lmms::gui::SampleTrackView::createMixerLine(), lmms::gui::InstrumentTrackView::createMixerMenu(), lmms::gui::SampleTrackView::createMixerMenu(), lmms::gui::MixerView::disconnectFromSoloAndMute(), lmms::gui::MixerChannelView::mixerChannel(), lmms::gui::MixerChannelView::setChannelIndex(), and lmms::gui::MixerView::updateFaders().
mixToChannel()
void lmms::Mixer::mixToChannel (const SampleFrame * _buf, mix_ch_t _ch)
Definition at line 645 of file Mixer.cpp.
References lmms::MixHelpers::add(), lmms::Engine::audioEngine(), and m_mixerChannels.
Referenced by lmms::AudioBusHandle::doProcessing().
moveChannelLeft()
void lmms::Mixer::moveChannelLeft (int index)
Definition at line 427 of file Mixer.cpp.
References lmms::Engine::getSong(), lmms::Track::Instrument, m_lastSoloed, m_mixerChannels, lmms::Engine::patternStore(), lmms::Track::Sample, and lmms::TrackContainer::tracks().
Referenced by lmms::gui::MixerView::moveChannelLeft(), and moveChannelRight().
moveChannelRight()
void lmms::Mixer::moveChannelRight (int index)
Definition at line 488 of file Mixer.cpp.
References moveChannelLeft().
nodeName()
QString lmms::Mixer::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 154 of file Mixer.h.
numChannels()
mix_ch_t lmms::Mixer::numChannels () const inline
Definition at line 211 of file Mixer.h.
References m_mixerChannels.
Referenced by lmms::gui::MixerView::MixerView(), lmms::gui::InstrumentTrackView::createMixerMenu(), lmms::gui::SampleTrackView::createMixerMenu(), and masterMix().
prepareMasterMix()
void lmms::Mixer::prepareMasterMix ()
Definition at line 659 of file Mixer.cpp.
References lmms::Engine::audioEngine(), m_mixerChannels, and lmms::zeroSampleFrames().
Referenced by lmms::AudioEngine::renderStageNoteSetup().
saveSettings()
void lmms::Mixer::saveSettings (QDomDocument & _doc, QDomElement & _parent) override virtual
Implements lmms::SerializingObject.
Definition at line 790 of file Mixer.cpp.
References lmms::MixerChannel::color(), i, lmms::MixerChannel::m_fxChain, m_mixerChannels, lmms::MixerChannel::m_muteModel, lmms::MixerChannel::m_name, lmms::MixerChannel::m_sends, lmms::MixerChannel::m_soloModel, lmms::MixerChannel::m_volumeModel, lmms::AutomatableModel::saveSettings(), and lmms::SerializingObject::saveState().
toggledSolo()
void lmms::Mixer::toggledSolo ()
Definition at line 299 of file Mixer.cpp.
References activateSolo(), deactivateSolo(), i, m_lastSoloed, and m_mixerChannels.
Referenced by lmms::gui::MixerView::toggledSolo().
validateChannelName()
void lmms::Mixer::validateChannelName (int index, int oldIndex)
Definition at line 884 of file Mixer.cpp.
References m_mixerChannels.
Referenced by deleteChannel().
Member Data Documentation
m_lastSoloed
int lmms::Mixer::m_lastSoloed private
Definition at line 225 of file Mixer.h.
Referenced by Mixer(), createChannel(), deleteChannel(), moveChannelLeft(), and toggledSolo().
m_mixerChannels
std::vector<MixerChannel*> lmms::Mixer::m_mixerChannels private
Definition at line 220 of file Mixer.h.
Referenced by Mixer(), ~Mixer(), activateSolo(), allocateChannelsTo(), channelSendModel(), checkInfiniteLoop(), clear(), clearChannel(), createChannel(), createChannelSend(), deactivateSolo(), deleteChannel(), deleteChannelSend(), isChannelInUse(), isInfiniteLoop(), loadSettings(), masterMix(), mixerChannel(), mixToChannel(), moveChannelLeft(), numChannels(), prepareMasterMix(), saveSettings(), toggledSolo(), and validateChannelName().
m_mixerRoutes
MixerRouteVector lmms::Mixer::m_mixerRoutes
Definition at line 216 of file Mixer.h.
Referenced by ~Mixer(), createRoute(), and deleteChannelSend().
The documentation for this class was generated from the following files:
include/Mixer.h
src/core/Mixer.cpp