LMMS: hiir::Upsampler2x3dnow< NC > Class Template Reference
hiir::Upsampler2x3dnow< NC > Class Template Reference
#include <Upsampler2x3dnow.h>
Public Types
typedef float DataType
Public Member Functions
Upsampler2x3dnow () noexcept
Upsampler2x3dnow (const Upsampler2x3dnow< NC > &other)=default
Upsampler2x3dnow (Upsampler2x3dnow< NC > &&other)=default
~Upsampler2x3dnow ()=default
void clear_buffers () noexcept
Upsampler2x3dnow< NC > & operator= (const Upsampler2x3dnow< NC > &other)=default
Upsampler2x3dnow< NC > & operator= (Upsampler2x3dnow< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (float &out_0, float &out_1, float input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageData3dnow, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Upsampler2x3dnow< NC > &other)=delete
bool operator== (const Upsampler2x3dnow< NC > &other)=delete
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _nbr_stages
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::Upsampler2x3dnow< NC >
Definition at line 48 of file Upsampler2x3dnow.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Upsampler2x3dnow< NC >::DataType
Definition at line 57 of file Upsampler2x3dnow.h.
Filter
template<int NC> typedef std::array<StageData3dnow, _nbr_stages + 1> hiir::Upsampler2x3dnow< NC >::Filter private
Definition at line 94 of file Upsampler2x3dnow.h.
Constructor & Destructor Documentation
Upsampler2x3dnow() [1/3]
template<int NC> hiir::Upsampler2x3dnow< NC >::Upsampler2x3dnow () noexcept
Definition at line 69 of file Upsampler2x3dnow.hpp.
References _filter, _nbr_stages, clear_buffers(), i, and NBR_COEFS.
Referenced by Upsampler2x3dnow(), Upsampler2x3dnow(), ~Upsampler2x3dnow(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2x3dnow() [2/3]
template<int NC> hiir::Upsampler2x3dnow< NC >::Upsampler2x3dnow (const Upsampler2x3dnow< NC > & other) default
References Upsampler2x3dnow().
Upsampler2x3dnow() [3/3]
template<int NC> hiir::Upsampler2x3dnow< NC >::Upsampler2x3dnow (Upsampler2x3dnow< NC > && other) default
References Upsampler2x3dnow().
~Upsampler2x3dnow()
template<int NC> hiir::Upsampler2x3dnow< NC >::~Upsampler2x3dnow () default
References Upsampler2x3dnow().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2x3dnow< NC >::clear_buffers () noexcept
Definition at line 305 of file Upsampler2x3dnow.hpp.
References _filter, _nbr_stages, and i.
Referenced by Upsampler2x3dnow(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2x3dnow< NC >::operator!= (const Upsampler2x3dnow< NC > & other) private delete
References Upsampler2x3dnow().
operator=() [1/2]
template<int NC> Upsampler2x3dnow< NC > & hiir::Upsampler2x3dnow< NC >::operator= (const Upsampler2x3dnow< NC > & other) default
References Upsampler2x3dnow().
operator=() [2/2]
template<int NC> Upsampler2x3dnow< NC > & hiir::Upsampler2x3dnow< NC >::operator= (Upsampler2x3dnow< NC > && other) default
References Upsampler2x3dnow(), clear_buffers(), hiir_FORCEINLINE, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2x3dnow< NC >::operator== (const Upsampler2x3dnow< NC > & other) private delete
References Upsampler2x3dnow().
process_block() [1/2]
template<int NC> void hiir::Upsampler2x3dnow< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 174 of file Upsampler2x3dnow.hpp.
References _filter, _nbr_stages, and hiir::StageProc3dnow< CUR >::process_sample_pos().
Referenced by operator=().
process_block() [2/2]
void hiir::Upsampler2x3dnow< 8 >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 224 of file Upsampler2x3dnow.hpp.
References _filter.
process_sample()
template<int NC> void hiir::Upsampler2x3dnow< NC >::process_sample (float & out_0, float & out_1, float input) noexcept
Definition at line 131 of file Upsampler2x3dnow.hpp.
References _filter, _nbr_stages, and hiir::StageProc3dnow< CUR >::process_sample_pos().
Referenced by operator=().
set_coefs()
template<int NC> void hiir::Upsampler2x3dnow< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 102 of file Upsampler2x3dnow.hpp.
References _filter, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Upsampler2x3dnow< NC >::_delay = 0 static constexpr
Definition at line 60 of file Upsampler2x3dnow.h.
_filter
template<int NC> Filter hiir::Upsampler2x3dnow< NC >::_filter private
Definition at line 96 of file Upsampler2x3dnow.h.
Referenced by Upsampler2x3dnow(), clear_buffers(), process_block(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Upsampler2x3dnow< NC >::_nbr_chn = 1 static constexpr
Definition at line 58 of file Upsampler2x3dnow.h.
_nbr_stages
template<int NC> int hiir::Upsampler2x3dnow< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 91 of file Upsampler2x3dnow.h.
Referenced by Upsampler2x3dnow(), clear_buffers(), process_block(), and process_sample().
_stage_width
template<int NC> int hiir::Upsampler2x3dnow< NC >::_stage_width = 2 static constexpr private
Definition at line 90 of file Upsampler2x3dnow.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::Upsampler2x3dnow< NC >::NBR_COEFS = NC static constexpr
Definition at line 59 of file Upsampler2x3dnow.h.
Referenced by Upsampler2x3dnow(), operator=(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2x3dnow.h
src/3rdparty/hiir/hiir/Upsampler2x3dnow.hpp