LMMS: lmms::gui::MixerChannelLcdSpinBox Class Reference
lmms::gui::MixerChannelLcdSpinBox Class Reference
#include <MixerChannelLcdSpinBox.h>
Public Member Functions
MixerChannelLcdSpinBox (int numDigits, QWidget *parent, const QString &name, TrackView *tv=nullptr)
~MixerChannelLcdSpinBox () override=default
void setTrackView (TrackView *tv)
Public Member Functions inherited from lmms::gui::LcdSpinBox
LcdSpinBox (int numDigits, const QString &style, QWidget *parent, const QString &name=QString())
LcdSpinBox (int numDigits, QWidget *parent, const QString &name=QString())
~LcdSpinBox () override=default
int displayOffset () const
Returns internal offset for displaying values.
void modelChanged () override
void setDisplayOffset (int offset)
Sets an offset which is always added to value of model so we can display values in a user-friendly way if they internally start at 0.
Public Member Functions inherited from lmms::gui::LcdWidget
LcdWidget (int numDigits, const QString &style, QWidget *parent, const QString &name=QString(), bool leadingZero=false)
LcdWidget (int numDigits, QWidget *parent, const QString &name=QString(), bool leadingZero=false)
LcdWidget (QWidget *parent, const QString &name=QString(), bool leadingZero=false)
void addTextForValue (int value, const QString &text)
int cellHeight () const
int numDigits () const
void setLabel (const QString &label)
void setNumDigits (int n)
void setSeamless (bool left, bool right)
void setTextColor (const QColor &c)
void setTextShadowColor (const QColor &c)
void setValue (float value)
void setValue (int value)
QColor textColor () const
QColor textShadowColor () const
Public Member Functions inherited from lmms::gui::TypedModelView< IntModel >
TypedModelView (Model *model, QWidget *_this)
IntModel * model ()
const IntModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *event) override
Protected Member Functions inherited from lmms::gui::LcdSpinBox
void contextMenuEvent (QContextMenuEvent *_me) override
void mouseDoubleClickEvent (QMouseEvent *_me) override
void mouseMoveEvent (QMouseEvent *_me) override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
void wheelEvent (QWheelEvent *_we) override
Protected Member Functions inherited from lmms::gui::LcdWidget
void paintEvent (QPaintEvent *pe) override
virtual void updateSize ()
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Member Functions
void enterValue ()
Private Attributes
TrackView * m_tv
Additional Inherited Members
Public Slots inherited from lmms::gui::LcdSpinBox
virtual void update ()
Public Slots inherited from lmms::gui::LcdWidget
virtual void setMarginWidth (int width)
Signals inherited from lmms::gui::LcdSpinBox
void manualChange ()
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Properties inherited from lmms::gui::LcdWidget
int numDigits
QColor textColor
QColor textShadowColor
Detailed Description
Definition at line 37 of file MixerChannelLcdSpinBox.h.
Constructor & Destructor Documentation
MixerChannelLcdSpinBox()
lmms::gui::MixerChannelLcdSpinBox::MixerChannelLcdSpinBox (int numDigits, QWidget * parent, const QString & name, TrackView * tv = nullptr) inline
Definition at line 41 of file MixerChannelLcdSpinBox.h.
References lmms::gui::LcdSpinBox::LcdSpinBox(), m_tv, and lmms::gui::LcdWidget::numDigits.
~MixerChannelLcdSpinBox()
lmms::gui::MixerChannelLcdSpinBox::~MixerChannelLcdSpinBox () override default
Member Function Documentation
contextMenuEvent()
void lmms::gui::MixerChannelLcdSpinBox::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 61 of file MixerChannelLcdSpinBox.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), m_tv, lmms::gui::TypedModelView< IntModel >::model(), and lmms::gui::LcdSpinBox::mouseReleaseEvent().
enterValue()
void lmms::gui::MixerChannelLcdSpinBox::enterValue () private
Definition at line 82 of file MixerChannelLcdSpinBox.cpp.
References max, lmms::TypedAutomatableModel< T >::maxValue(), min, lmms::TypedAutomatableModel< T >::minValue(), lmms::gui::TypedModelView< IntModel >::model(), lmms::AutomatableModel::setValue(), lmms::AutomatableModel::step(), and lmms::TypedAutomatableModel< T >::value().
Referenced by mouseDoubleClickEvent().
mouseDoubleClickEvent()
void lmms::gui::MixerChannelLcdSpinBox::mouseDoubleClickEvent (QMouseEvent * event) override protected
Definition at line 44 of file MixerChannelLcdSpinBox.cpp.
References enterValue(), lmms::gui::getGUI(), lmms::gui::GuiApplication::mixerView(), lmms::gui::TypedModelView< IntModel >::model(), lmms::gui::MixerView::setCurrentMixerChannel(), and lmms::gui::AutomatableModelView::value().
setTrackView()
void lmms::gui::MixerChannelLcdSpinBox::setTrackView (TrackView * tv)
Definition at line 39 of file MixerChannelLcdSpinBox.cpp.
References m_tv.
Member Data Documentation
m_tv
TrackView* lmms::gui::MixerChannelLcdSpinBox::m_tv private
Definition at line 55 of file MixerChannelLcdSpinBox.h.
Referenced by MixerChannelLcdSpinBox(), contextMenuEvent(), and setTrackView().
The documentation for this class was generated from the following files:
include/MixerChannelLcdSpinBox.h
src/gui/widgets/MixerChannelLcdSpinBox.cpp