LMMS: src/3rdparty/jack2/common/driver_interface.h File Reference
driver_interface.h File Reference
#include <limits.h>
#include "jslist.h"
#include "JackCompilerDeps.h"
#include "JackSystemDeps.h"
Classes
struct jack_constraint_enum_char_descriptor
struct jack_constraint_enum_sint32_descriptor
struct jack_constraint_enum_str_descriptor
struct jack_constraint_enum_uint32_descriptor
struct jack_driver_desc_filler_t
struct jack_driver_desc_t
A struct for describing a jack driver.
struct jack_driver_param_constraint_desc_t
struct jack_driver_param_desc_t
A driver parameter descriptor.
struct jack_driver_param_t
A driver parameter.
struct jack_driver_param_value_enum_t
union jack_driver_param_value_t
Driver parameter value.
Macros
#define JACK_CONSTRAINT_COMPOSE_ENUM(type)
#define JACK_CONSTRAINT_FLAG_FAKE_VALUE ((uint32_t)4)
if set, values have no user meaningful meaning
#define JACK_CONSTRAINT_FLAG_RANGE ((uint32_t)1)
if set, constraint is a range (min-max)
#define JACK_CONSTRAINT_FLAG_STRICT ((uint32_t)2)
if set, constraint is strict, i.e.
#define JACK_DRIVER_NAME_MAX 15
#define JACK_DRIVER_PARAM_DESC 255
#define JACK_DRIVER_PARAM_NAME_MAX 15
#define JACK_DRIVER_PARAM_STRING_MAX 127
#define JACK_PATH_MAX 511
Typedefs
typedef jack_driver_desc_t *(* JackDriverDescFunction) ()
Enumerations
enum jack_driver_param_type_t {
JackDriverParamInt = 1 ,
JackDriverParamUInt ,
JackDriverParamChar ,
JackDriverParamString ,
JackDriverParamBool
}
Driver parameter types.
enum jack_driver_type_t {
JackDriverMaster = 1 ,
JackDriverSlave ,
JackDriverNone
}
Driver types.
Functions
SERVER_EXPORT int jack_constraint_add_enum (jack_driver_param_constraint_desc_t **constraint_ptr_ptr, uint32_t *array_size_ptr, jack_driver_param_value_t *value_ptr, const char *short_desc)
JACK_CONSTRAINT_COMPOSE_ENUM (char)
JACK_CONSTRAINT_COMPOSE_ENUM (sint32)
JACK_CONSTRAINT_COMPOSE_ENUM (str)
JACK_CONSTRAINT_COMPOSE_ENUM (uint32)
SERVER_EXPORT void jack_constraint_free (jack_driver_param_constraint_desc_t *constraint_ptr)
SERVER_EXPORT int jack_driver_descriptor_add_parameter (jack_driver_desc_t *driver_descr, jack_driver_desc_filler_t *filler, const char *name, char character, jack_driver_param_type_t type, const jack_driver_param_value_t *value_ptr, jack_driver_param_constraint_desc_t *constraint, const char *short_desc, const char *long_desc)
SERVER_EXPORT jack_driver_desc_t * jack_driver_descriptor_construct (const char *name, jack_driver_type_t type, const char *description, jack_driver_desc_filler_t *filler)
int jack_parse_driver_params (jack_driver_desc_t *desc, int argc, char *argv[], JSList **param_ptr)
Macro Definition Documentation
JACK_CONSTRAINT_COMPOSE_ENUM
#define JACK_CONSTRAINT_COMPOSE_ENUM (type)
Value:
SERVER_EXPORT                              \
jack_driver_param_constraint_desc_t *      \
jack_constraint_compose_enum_ ## type(\
    uint32_t flags,                        \
    struct jack_constraint_enum_ ## type ## _descriptor * descr_array_ptr)
Definition at line 185 of file driver_interface.h.
JACK_CONSTRAINT_FLAG_FAKE_VALUE
#define JACK_CONSTRAINT_FLAG_FAKE_VALUE ((uint32_t)4)
if set, values have no user meaningful meaning
Definition at line 43 of file driver_interface.h.
Referenced by driver_get_descriptor(), jackctl_parameter_constraint_is_fake_value(), and jackctl_server_create2().
JACK_CONSTRAINT_FLAG_RANGE
#define JACK_CONSTRAINT_FLAG_RANGE ((uint32_t)1)
if set, constraint is a range (min-max)
Definition at line 41 of file driver_interface.h.
Referenced by get_realtime_priority_constraint(), jack_constraint_free(), jackctl_parameter_has_enum_constraint(), and jackctl_parameter_has_range_constraint().
JACK_CONSTRAINT_FLAG_STRICT
#define JACK_CONSTRAINT_FLAG_STRICT ((uint32_t)2)
if set, constraint is strict, i.e.
supplying non-matching value will not work
Definition at line 42 of file driver_interface.h.
Referenced by driver_get_descriptor(), jackctl_parameter_constraint_is_strict(), and jackctl_server_create2().
JACK_DRIVER_NAME_MAX
#define JACK_DRIVER_NAME_MAX 15
Definition at line 35 of file driver_interface.h.
JACK_DRIVER_PARAM_DESC
#define JACK_DRIVER_PARAM_DESC 255
Definition at line 38 of file driver_interface.h.
JACK_DRIVER_PARAM_NAME_MAX
#define JACK_DRIVER_PARAM_NAME_MAX 15
Definition at line 36 of file driver_interface.h.
JACK_DRIVER_PARAM_STRING_MAX
#define JACK_DRIVER_PARAM_STRING_MAX 127
Definition at line 37 of file driver_interface.h.
Referenced by jack_parse_driver_params(), jack_print_driver_options(), jackctl_driver_params_parse(), and Jack::JackArgParser::ParseParams().
JACK_PATH_MAX
#define JACK_PATH_MAX 511
Definition at line 39 of file driver_interface.h.
Referenced by Jack::JackTools::CleanupFiles(), Jack::JackTools::GetTmpdir(), Jack::JackLoadableInternalClient::Init(), Jack::JackClient::InternalClientLoad(), jack_get_descriptor(), Jack::JackTools::ServerDir(), and Jack::JackTools::UserDir().
Typedef Documentation
JackDriverDescFunction
typedef jack_driver_desc_t *(* JackDriverDescFunction) ()
Definition at line 197 of file driver_interface.h.
Enumeration Type Documentation
jack_driver_param_type_t
enum jack_driver_param_type_t
Driver parameter types.
Enumerator
JackDriverParamInt
JackDriverParamUInt
JackDriverParamChar
JackDriverParamString
JackDriverParamBool
Definition at line 46 of file driver_interface.h.
jack_driver_type_t
enum jack_driver_type_t
Driver types.
Enumerator
JackDriverMaster
JackDriverSlave
JackDriverNone
Definition at line 56 of file driver_interface.h.
Function Documentation
jack_constraint_add_enum()
SERVER_EXPORT int jack_constraint_add_enum (jack_driver_param_constraint_desc_t ** constraint_ptr_ptr, uint32_t * array_size_ptr, jack_driver_param_value_t * value_ptr, const char * short_desc)
Definition at line 915 of file JackDriverLoader.cpp.
References jack_driver_param_constraint_desc_t::constraint, jack_driver_param_constraint_desc_t::count, jack_driver_param_constraint_desc_t::enumeration, jack_error, jack_driver_param_constraint_desc_t::possible_values_array, jack_driver_param_value_enum_t::short_desc, and jack_driver_param_value_enum_t::value.
Referenced by enum_alsa_devices().
JACK_CONSTRAINT_COMPOSE_ENUM() [1/4]
JACK_CONSTRAINT_COMPOSE_ENUM (char)
JACK_CONSTRAINT_COMPOSE_ENUM() [2/4]
JACK_CONSTRAINT_COMPOSE_ENUM (sint32)
JACK_CONSTRAINT_COMPOSE_ENUM() [3/4]
JACK_CONSTRAINT_COMPOSE_ENUM (str)
JACK_CONSTRAINT_COMPOSE_ENUM() [4/4]
JACK_CONSTRAINT_COMPOSE_ENUM (uint32)
jack_constraint_free()
SERVER_EXPORT void jack_constraint_free (jack_driver_param_constraint_desc_t * constraint_ptr)
Definition at line 983 of file JackDriverLoader.cpp.
References jack_driver_param_constraint_desc_t::constraint, jack_driver_param_constraint_desc_t::enumeration, jack_driver_param_constraint_desc_t::flags, JACK_CONSTRAINT_FLAG_RANGE, and jack_driver_param_constraint_desc_t::possible_values_array.
Referenced by enum_alsa_devices(), jackctl_free_driver_parameters(), and jackctl_server_free_parameters().
jack_driver_descriptor_add_parameter()
SERVER_EXPORT int jack_driver_descriptor_add_parameter (jack_driver_desc_t * driver_descr, jack_driver_desc_filler_t * filler, const char * name, char character, jack_driver_param_type_t type, const jack_driver_param_value_t * value_ptr, jack_driver_param_constraint_desc_t * constraint, const char * short_desc, const char * long_desc)
Definition at line 853 of file JackDriverLoader.cpp.
References jack_driver_param_desc_t::character, jack_driver_param_desc_t::constraint, jack_error, jack_driver_param_desc_t::long_desc, jack_driver_param_desc_t::name, jack_driver_desc_t::nparams, jack_driver_desc_t::params, SERVER_EXPORT, jack_driver_param_desc_t::short_desc, jack_driver_desc_filler_t::size, jack_driver_param_desc_t::type, and jack_driver_param_desc_t::value.
Referenced by driver_get_descriptor(), Jack::driver_get_descriptor(), and jack_get_descriptor().
jack_driver_descriptor_construct()
SERVER_EXPORT jack_driver_desc_t * jack_driver_descriptor_construct (const char * name, jack_driver_type_t type, const char * description, jack_driver_desc_filler_t * filler)
Definition at line 815 of file JackDriverLoader.cpp.
References jack_driver_desc_t::desc, jack_error, jack_driver_desc_t::name, jack_driver_desc_t::nparams, SERVER_EXPORT, jack_driver_desc_filler_t::size, and jack_driver_desc_t::type.
Referenced by driver_get_descriptor(), Jack::driver_get_descriptor(), and jack_get_descriptor().
jack_parse_driver_params()
int jack_parse_driver_params (jack_driver_desc_t * desc, int argc, char * argv[], JSList ** param_ptr)
Definition at line 143 of file JackDriverLoader.cpp.
References jack_driver_param_value_t::c, jack_driver_param_desc_t::character, jack_driver_param_t::character, option::flag, getopt_long(), option::has_arg, i, jack_driver_param_value_t::i, JACK_DRIVER_PARAM_STRING_MAX, jack_log(), jack_print_driver_options(), jack_print_driver_param_usage(), jack_slist_append(), JackDriverParamBool, JackDriverParamChar, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, jack_driver_desc_t::name, jack_driver_param_desc_t::name, option::name, jack_driver_desc_t::nparams, optarg, opterr, optind, optional_argument, optopt, jack_driver_desc_t::params, jack_driver_param_value_t::str, jack_driver_param_desc_t::type, jack_driver_param_value_t::ui, option::val, jack_driver_param_desc_t::value, and jack_driver_param_t::value.
Referenced by Jack::JackServerGlobals::Init().