LMMS: ExternalMetro Struct Reference
ExternalMetro Struct Reference
A class to test external clients.
#include <external_metro.h>
Public Member Functions
ExternalMetro (int freq, double max_amp, int dur_arg, int bpm, const char *client_name="metro")
virtual ~ExternalMetro ()
Static Public Member Functions
static int process_audio (jack_nframes_t nframes, void *arg)
static void shutdown (void *arg)
Public Attributes
double * amp
int bpm
jack_client_t * client
int freq
jack_port_t * input_port
long offset
jack_port_t * output_port
unsigned long sr
jack_nframes_t tone_length
sample_t * wave
jack_nframes_t wave_length
Detailed Description
A class to test external clients.
Definition at line 45 of file external_metro.h.
Constructor & Destructor Documentation
ExternalMetro()
ExternalMetro::ExternalMetro (int freq, double max_amp, int dur_arg, int bpm, const char * client_name = "metro")
Definition at line 59 of file external_metro.cpp.
References amp, bpm, client, freq, i, input_port, jack_activate(), jack_client_open(), JACK_DEFAULT_AUDIO_TYPE, jack_get_sample_rate(), jack_on_shutdown(), jack_port_register(), jack_set_process_callback(), JackNullOption, JackPortIsInput, JackPortIsOutput, offset, output_port, PI, process_audio(), shutdown(), sr, tone_length, wave, and wave_length.
Referenced by process_audio().
~ExternalMetro()
ExternalMetro::~ExternalMetro () virtual
Definition at line 127 of file external_metro.cpp.
References amp, client, input_port, jack_client_close(), jack_deactivate(), jack_port_unregister(), output_port, and wave.
Member Function Documentation
process_audio()
int ExternalMetro::process_audio (jack_nframes_t nframes, void * arg) static
Definition at line 35 of file external_metro.cpp.
References ExternalMetro(), jack_port_get_buffer(), offset, output_port, wave, and wave_length.
Referenced by ExternalMetro().
shutdown()
void ExternalMetro::shutdown (void * arg) static
Definition at line 54 of file external_metro.cpp.
Referenced by ExternalMetro().
Member Data Documentation
amp
double* ExternalMetro::amp
Definition at line 56 of file external_metro.h.
Referenced by ExternalMetro(), and ~ExternalMetro().
bpm
int ExternalMetro::bpm
Definition at line 53 of file external_metro.h.
Referenced by ExternalMetro().
client
jack_client_t* ExternalMetro::client
Definition at line 47 of file external_metro.h.
Referenced by ExternalMetro(), and ~ExternalMetro().
freq
int ExternalMetro::freq
Definition at line 52 of file external_metro.h.
Referenced by ExternalMetro().
input_port
jack_port_t* ExternalMetro::input_port
Definition at line 48 of file external_metro.h.
Referenced by ExternalMetro(), and ~ExternalMetro().
offset
long ExternalMetro::offset
Definition at line 57 of file external_metro.h.
Referenced by ExternalMetro(), and process_audio().
output_port
jack_port_t* ExternalMetro::output_port
Definition at line 49 of file external_metro.h.
Referenced by ExternalMetro(), ~ExternalMetro(), and process_audio().
sr
unsigned long ExternalMetro::sr
Definition at line 51 of file external_metro.h.
Referenced by ExternalMetro().
tone_length
jack_nframes_t ExternalMetro::tone_length
Definition at line 54 of file external_metro.h.
Referenced by ExternalMetro().
wave
sample_t* ExternalMetro::wave
Definition at line 55 of file external_metro.h.
Referenced by ExternalMetro(), ~ExternalMetro(), and process_audio().
wave_length
jack_nframes_t ExternalMetro::wave_length
Definition at line 54 of file external_metro.h.
Referenced by ExternalMetro(), and process_audio().
The documentation for this struct was generated from the following files:
src/3rdparty/jack2/tests/external_metro.h
src/3rdparty/jack2/tests/external_metro.cpp