LMMS: Jack::JackMessageBuffer Class Reference
Jack::JackMessageBuffer Class Reference
Message buffer to be used from RT threads.
#include <JackMessageBuffer.h>
Public Member Functions
JackMessageBuffer ()
~JackMessageBuffer ()
void AddMessage (int level, const char *message)
bool Execute ()
int SetInitCallback (JackThreadInitCallback callback, void *arg)
Public Member Functions inherited from Jack::JackRunnableInterface
virtual bool Init ()
Called once when the thread is started.
Static Public Member Functions
static bool Create ()
static bool Destroy ()
Static Public Attributes
static JackMessageBuffer * fInstance = NULL
Private Member Functions
void Flush ()
bool Start ()
bool Stop ()
Private Attributes
JackMessage fBuffers [MB_BUFFERS]
JackProcessSync fGuard
volatile unsigned int fInBuffer
volatile JackThreadInitCallback fInit
void * fInitArg
volatile unsigned int fOutBuffer
SInt32 fOverruns
bool fRunning
JackThread fThread
Additional Inherited Members
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Detailed Description
Message buffer to be used from RT threads.
Definition at line 55 of file JackMessageBuffer.h.
Constructor & Destructor Documentation
JackMessageBuffer()
Jack::JackMessageBuffer::JackMessageBuffer ()
Definition at line 32 of file JackMessageBuffer.cpp.
References JackMessageBuffer(), fGuard, fInBuffer, fInit, fInitArg, fOutBuffer, fOverruns, fRunning, fThread, and offsetof.
Referenced by JackMessageBuffer(), and Create().
~JackMessageBuffer()
Jack::JackMessageBuffer::~JackMessageBuffer ()
Definition at line 46 of file JackMessageBuffer.cpp.
Member Function Documentation
AddMessage()
void Jack::JackMessageBuffer::AddMessage (int level, const char * message)
Definition at line 90 of file JackMessageBuffer.cpp.
References fBuffers, fGuard, fInBuffer, fOverruns, INC_ATOMIC(), MB_BUFFERSIZE, and MB_NEXT.
Create()
bool Jack::JackMessageBuffer::Create () static
Definition at line 131 of file JackMessageBuffer.cpp.
References JackMessageBuffer(), fInstance, and jack_error.
Referenced by Jack::JackLibGlobals::JackLibGlobals(), and Jack::JackServer::Open().
Destroy()
bool Jack::JackMessageBuffer::Destroy () static
Definition at line 146 of file JackMessageBuffer.cpp.
References fInstance.
Referenced by Jack::JackLibGlobals::~JackLibGlobals(), Jack::JackServer::Close(), and Jack::JackServer::Open().
Execute()
bool Jack::JackMessageBuffer::Execute () virtual
Implements Jack::JackRunnableInterface.
Definition at line 103 of file JackMessageBuffer.cpp.
References fGuard, fInit, fInitArg, Flush(), fRunning, and jack_error.
Flush()
void Jack::JackMessageBuffer::Flush () private
Definition at line 82 of file JackMessageBuffer.cpp.
References fBuffers, fInBuffer, fOutBuffer, jack_log_function(), and MB_NEXT.
Referenced by Execute(), and Stop().
SetInitCallback()
int Jack::JackMessageBuffer::SetInitCallback (JackThreadInitCallback callback, void * arg)
Definition at line 168 of file JackMessageBuffer.cpp.
References fGuard, fInit, fInitArg, fInstance, fRunning, jack_error, and JackSleep().
Start()
bool Jack::JackMessageBuffer::Start () private
Definition at line 49 of file JackMessageBuffer.cpp.
References fRunning, and fThread.
Stop()
bool Jack::JackMessageBuffer::Stop () private
Definition at line 61 of file JackMessageBuffer.cpp.
References fGuard, Flush(), fOverruns, fRunning, fThread, jack_error, and jack_log().
Member Data Documentation
fBuffers
JackMessage Jack::JackMessageBuffer::fBuffers[MB_BUFFERS] private
Definition at line 62 of file JackMessageBuffer.h.
Referenced by AddMessage(), and Flush().
fGuard
JackProcessSync Jack::JackMessageBuffer::fGuard private
Definition at line 64 of file JackMessageBuffer.h.
Referenced by JackMessageBuffer(), AddMessage(), Execute(), SetInitCallback(), and Stop().
fInBuffer
volatile unsigned int Jack::JackMessageBuffer::fInBuffer private
Definition at line 65 of file JackMessageBuffer.h.
Referenced by JackMessageBuffer(), AddMessage(), and Flush().
fInit
volatile JackThreadInitCallback Jack::JackMessageBuffer::fInit private
Definition at line 60 of file JackMessageBuffer.h.
Referenced by JackMessageBuffer(), Execute(), and SetInitCallback().
fInitArg
void* Jack::JackMessageBuffer::fInitArg private
Definition at line 61 of file JackMessageBuffer.h.
Referenced by JackMessageBuffer(), Execute(), and SetInitCallback().
fInstance
JackMessageBuffer * Jack::JackMessageBuffer::fInstance = NULL static
Definition at line 89 of file JackMessageBuffer.h.
Referenced by Create(), Destroy(), Jack::JackMessageBufferAdd(), Jack::JackClient::SetInitCallback(), and SetInitCallback().
fOutBuffer
volatile unsigned int Jack::JackMessageBuffer::fOutBuffer private
Definition at line 66 of file JackMessageBuffer.h.
Referenced by JackMessageBuffer(), and Flush().
fOverruns
SInt32 Jack::JackMessageBuffer::fOverruns private
Definition at line 67 of file JackMessageBuffer.h.
Referenced by JackMessageBuffer(), AddMessage(), and Stop().
fRunning
bool Jack::JackMessageBuffer::fRunning private
Definition at line 68 of file JackMessageBuffer.h.
Referenced by JackMessageBuffer(), Execute(), SetInitCallback(), Start(), and Stop().
fThread
JackThread Jack::JackMessageBuffer::fThread private
Definition at line 63 of file JackMessageBuffer.h.
Referenced by JackMessageBuffer(), Start(), and Stop().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackMessageBuffer.h
src/3rdparty/jack2/common/JackMessageBuffer.cpp