LMMS: lmms::gui::ActionGroup Class Reference
lmms::gui::ActionGroup Class Reference
Convenience subclass of QActionGroup.
#include <ActionGroup.h>
Signals
void triggered (int index)
This signal is emitted when the action at the given index is triggered.
Public Member Functions
ActionGroup (QObject *parent)
QAction * addAction (const QIcon &icon, const QString &text)
QAction * addAction (const QString &text)
QAction * addAction (QAction *a)
Private Slots
void actionTriggered_ (QAction *action)
Private Attributes
QList< QAction * > m_actions
Detailed Description
Convenience subclass of QActionGroup.
This class provides the same functionality as QActionGroup, but in addition has the actionTriggered(int) signal. It also sets every added action's checkable property to true.
Definition at line 38 of file ActionGroup.h.
Constructor & Destructor Documentation
ActionGroup()
lmms::gui::ActionGroup::ActionGroup (QObject * parent)
Definition at line 30 of file ActionGroup.cpp.
References actionTriggered_(), and triggered().
Member Function Documentation
actionTriggered_
void lmms::gui::ActionGroup::actionTriggered_ (QAction * action) private slot
Definition at line 52 of file ActionGroup.cpp.
References triggered().
Referenced by ActionGroup().
addAction() [1/3]
QAction * lmms::gui::ActionGroup::addAction (const QIcon & icon, const QString & text)
Definition at line 47 of file ActionGroup.cpp.
References addAction().
addAction() [2/3]
QAction * lmms::gui::ActionGroup::addAction (const QString & text)
Definition at line 42 of file ActionGroup.cpp.
References addAction().
addAction() [3/3]
QAction * lmms::gui::ActionGroup::addAction (QAction * a)
Definition at line 35 of file ActionGroup.cpp.
Referenced by addAction(), and addAction().
triggered
void lmms::gui::ActionGroup::triggered (int index) signal
This signal is emitted when the action at the given index is triggered.
Referenced by ActionGroup(), and actionTriggered_().
Member Data Documentation
m_actions
QList<QAction*> lmms::gui::ActionGroup::m_actions private
Definition at line 56 of file ActionGroup.h.
The documentation for this class was generated from the following files:
include/ActionGroup.h
src/gui/ActionGroup.cpp