LMMS: lmms::gui::ComboBox Class Reference
lmms::gui::ComboBox Class Reference
#include <ComboBox.h>
Public Slots
void selectNext ()
void selectPrevious ()
Public Member Functions
ComboBox (QWidget *parent=nullptr, const QString &name=QString())
~ComboBox () override=default
ComboBoxModel * model ()
const ComboBoxModel * model () const
Public Member Functions inherited from lmms::gui::TypedModelView< IntModel >
TypedModelView (Model *model, QWidget *_this)
IntModel * model ()
const IntModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Static Public Attributes
static constexpr int DEFAULT_HEIGHT = 22
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void paintEvent (QPaintEvent *event) override
void wheelEvent (QWheelEvent *event) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Private Slots
void setItem (QAction *item)
Private Attributes
QPixmap m_arrow = embed::getIconPixmap("combobox_arrow")
QPixmap m_arrowSelected = embed::getIconPixmap("combobox_arrow_selected")
QPixmap m_background = embed::getIconPixmap("combobox_bg")
QMenu m_menu
bool m_pressed
Additional Inherited Members
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 37 of file ComboBox.h.
Constructor & Destructor Documentation
ComboBox()
lmms::gui::ComboBox::ComboBox (QWidget * parent = nullptr, const QString & name = QString())
Definition at line 48 of file ComboBox.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, DEFAULT_HEIGHT, lmms::gui::ModelView::doConnections(), m_menu, m_pressed, and setItem().
~ComboBox()
lmms::gui::ComboBox::~ComboBox () override default
Member Function Documentation
contextMenuEvent()
void lmms::gui::ComboBox::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 85 of file ComboBox.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), lmms::gui::CB_ARROW_BTN_WIDTH, and model().
model() [1/2]
ComboBoxModel * lmms::gui::ComboBox::model () inline
Definition at line 44 of file ComboBox.h.
References lmms::gui::ModelView::castModel().
Referenced by contextMenuEvent(), mousePressEvent(), paintEvent(), selectNext(), selectPrevious(), setItem(), and wheelEvent().
model() [2/2]
const ComboBoxModel * lmms::gui::ComboBox::model () const inline
Definition at line 49 of file ComboBox.h.
References lmms::gui::ModelView::castModel().
mousePressEvent()
void lmms::gui::ComboBox::mousePressEvent (QMouseEvent * event) override protected virtual
Reimplemented from lmms::gui::AutomatableModelView.
Definition at line 101 of file ComboBox.cpp.
References lmms::gui::CB_ARROW_BTN_WIDTH, i, m_menu, m_pressed, model(), lmms::gui::AutomatableModelView::mousePressEvent(), selectNext(), selectPrevious(), and lmms::ComboBoxModel::size().
paintEvent()
void lmms::gui::ComboBox::paintEvent (QPaintEvent * event) override protected
Definition at line 163 of file ComboBox.cpp.
References lmms::gui::CB_ARROW_BTN_WIDTH, lmms::ComboBoxModel::currentData(), m_arrow, m_arrowSelected, m_background, m_pressed, model(), and lmms::PixmapLoader::pixmap().
selectNext
void lmms::gui::ComboBox::selectNext () slot
Definition at line 70 of file ComboBox.cpp.
References model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Referenced by mousePressEvent().
selectPrevious
void lmms::gui::ComboBox::selectPrevious () slot
Definition at line 78 of file ComboBox.cpp.
References model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Referenced by mousePressEvent().
setItem
void lmms::gui::ComboBox::setItem (QAction * item) private slot
Definition at line 233 of file ComboBox.cpp.
References model(), and lmms::AutomatableModel::setValue().
Referenced by ComboBox().
wheelEvent()
void lmms::gui::ComboBox::wheelEvent (QWheelEvent * event) override protected
Definition at line 219 of file ComboBox.cpp.
References model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Member Data Documentation
DEFAULT_HEIGHT
int lmms::gui::ComboBox::DEFAULT_HEIGHT = 22 static constexpr
Definition at line 54 of file ComboBox.h.
Referenced by lmms::gui::AutomationEditorWindow::AutomationEditorWindow(), ComboBox(), lmms::gui::ComboControl::ComboControl(), lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::PianoRollWindow::PianoRollWindow(), and lmms::gui::SongEditorWindow::SongEditorWindow().
m_arrow
QPixmap lmms::gui::ComboBox::m_arrow = embed::getIconPixmap("combobox_arrow") private
Definition at line 70 of file ComboBox.h.
Referenced by paintEvent().
m_arrowSelected
QPixmap lmms::gui::ComboBox::m_arrowSelected = embed::getIconPixmap("combobox_arrow_selected") private
Definition at line 71 of file ComboBox.h.
Referenced by paintEvent().
m_background
QPixmap lmms::gui::ComboBox::m_background = embed::getIconPixmap("combobox_bg") private
Definition at line 69 of file ComboBox.h.
Referenced by paintEvent().
m_menu
QMenu lmms::gui::ComboBox::m_menu private
Definition at line 73 of file ComboBox.h.
Referenced by ComboBox(), and mousePressEvent().
m_pressed
bool lmms::gui::ComboBox::m_pressed private
Definition at line 75 of file ComboBox.h.
Referenced by ComboBox(), mousePressEvent(), and paintEvent().
The documentation for this class was generated from the following files:
include/ComboBox.h
src/gui/widgets/ComboBox.cpp