LMMS: Jack::JackLinuxFutex Class Reference
Jack::JackLinuxFutex Class Reference
Inter process synchronization using Linux futex.
#include <JackLinuxFutex.h>
Classes
struct FutexData
Public Member Functions
JackLinuxFutex ()
bool Allocate (const char *name, const char *server_name, int value, bool internal=false)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
void MakePrivate (bool priv)
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Public Member Functions inherited from Jack::detail::JackSynchro
JackSynchro ()
~JackSynchro ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
void SetFlush (bool mode)
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Protected Member Functions
void BuildName (const char *name, const char *server_name, char *res, int size)
Private Attributes
FutexData * fFutex
bool fPrivate
bool fPromiscuous
int fPromiscuousGid
int fSharedMem
Additional Inherited Members
Protected Attributes inherited from Jack::detail::JackSynchro
bool fFlush
char fName [SYNC_MAX_NAME_SIZE]
Detailed Description
Inter process synchronization using Linux futex.
Based on the JackPosixSemaphore class. Adapted to work with linux futex to be as light as possible and also work in multiple architectures.
Adds a new 'MakePrivate' function that makes the sync happen in the local process only, making it even faster for internal clients.
Definition at line 41 of file JackLinuxFutex.h.
Constructor & Destructor Documentation
JackLinuxFutex()
Jack::JackLinuxFutex::JackLinuxFutex ()
Definition at line 40 of file JackLinuxFutex.cpp.
References Jack::detail::JackSynchro::JackSynchro(), fFutex, fPrivate, fPromiscuous, fPromiscuousGid, fSharedMem, and jack_group2gid().
Member Function Documentation
Allocate()
bool Jack::JackLinuxFutex::Allocate (const char * name, const char * server_name, int value, bool internal = false)
Definition at line 144 of file JackLinuxFutex.cpp.
References BuildName(), Jack::JackLinuxFutex::FutexData::externalCount, fFutex, Jack::detail::JackSynchro::fName, fPrivate, fPromiscuous, fPromiscuousGid, fSharedMem, Jack::JackLinuxFutex::FutexData::futex, Jack::JackLinuxFutex::FutexData::internal, jack_error, jack_log(), jack_promiscuous_perms(), Jack::JackLinuxFutex::FutexData::needsChange, server_name, and Jack::JackLinuxFutex::FutexData::wasInternal.
BuildName()
void Jack::JackLinuxFutex::BuildName (const char * name, const char * server_name, char * res, int size) protected
Definition at line 47 of file JackLinuxFutex.cpp.
References fPromiscuous, Jack::JackTools::GetUID(), Jack::JackTools::RewriteName(), server_name, and SYNC_MAX_NAME_SIZE.
Referenced by Allocate(), and Connect().
Connect()
bool Jack::JackLinuxFutex::Connect (const char * name, const char * server_name)
Definition at line 188 of file JackLinuxFutex.cpp.
References BuildName(), Jack::JackLinuxFutex::FutexData::externalCount, fFutex, Jack::detail::JackSynchro::fName, fPrivate, fSharedMem, jack_error, jack_log(), Jack::JackLinuxFutex::FutexData::needsChange, server_name, and Jack::JackLinuxFutex::FutexData::wasInternal.
Referenced by ConnectInput(), and ConnectOutput().
ConnectInput()
bool Jack::JackLinuxFutex::ConnectInput (const char * name, const char * server_name)
Definition at line 228 of file JackLinuxFutex.cpp.
References Connect(), and server_name.
ConnectOutput()
bool Jack::JackLinuxFutex::ConnectOutput (const char * name, const char * server_name)
Definition at line 233 of file JackLinuxFutex.cpp.
References Connect(), and server_name.
Destroy()
void Jack::JackLinuxFutex::Destroy ()
Definition at line 264 of file JackLinuxFutex.cpp.
References fFutex, Jack::detail::JackSynchro::fName, and fSharedMem.
Disconnect()
bool Jack::JackLinuxFutex::Disconnect ()
Definition at line 238 of file JackLinuxFutex.cpp.
References fFutex, Jack::detail::JackSynchro::fName, fPrivate, fSharedMem, and jack_error.
MakePrivate()
void Jack::JackLinuxFutex::MakePrivate (bool priv)
Signal()
bool Jack::JackLinuxFutex::Signal ()
Definition at line 58 of file JackLinuxFutex.cpp.
References Jack::detail::JackSynchro::fFlush, fFutex, Jack::detail::JackSynchro::fName, and jack_error.
Referenced by SignalAll().
SignalAll()
bool Jack::JackLinuxFutex::SignalAll ()
Definition at line 79 of file JackLinuxFutex.cpp.
References Signal().
TimedWait()
bool Jack::JackLinuxFutex::TimedWait (long usec)
Definition at line 110 of file JackLinuxFutex.cpp.
References fFutex, Jack::detail::JackSynchro::fName, jack_error, and Wait().
Wait()
bool Jack::JackLinuxFutex::Wait ()
Definition at line 84 of file JackLinuxFutex.cpp.
References fFutex, Jack::detail::JackSynchro::fName, and jack_error.
Referenced by TimedWait().
Member Data Documentation
fFutex
FutexData* Jack::JackLinuxFutex::fFutex private
Definition at line 54 of file JackLinuxFutex.h.
Referenced by JackLinuxFutex(), Allocate(), Connect(), Destroy(), Disconnect(), Signal(), TimedWait(), and Wait().
fPrivate
bool Jack::JackLinuxFutex::fPrivate private
Definition at line 55 of file JackLinuxFutex.h.
Referenced by JackLinuxFutex(), Allocate(), Connect(), and Disconnect().
fPromiscuous
bool Jack::JackLinuxFutex::fPromiscuous private
Definition at line 56 of file JackLinuxFutex.h.
Referenced by JackLinuxFutex(), Allocate(), and BuildName().
fPromiscuousGid
int Jack::JackLinuxFutex::fPromiscuousGid private
Definition at line 57 of file JackLinuxFutex.h.
Referenced by JackLinuxFutex(), and Allocate().
fSharedMem
int Jack::JackLinuxFutex::fSharedMem private
Definition at line 53 of file JackLinuxFutex.h.
Referenced by JackLinuxFutex(), Allocate(), Connect(), Destroy(), and Disconnect().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/linux/JackLinuxFutex.h
src/3rdparty/jack2/linux/JackLinuxFutex.cpp