LMMS: lmms::RenderManager Class Reference
lmms::RenderManager Class Reference
#include <RenderManager.h>
Signals
void finished ()
void progressChanged (int)
Public Member Functions
RenderManager (const OutputSettings &outputSettings, ProjectRenderer::ExportFileFormat fmt, QString outputPath)
~RenderManager () override
void abortProcessing ()
void renderProject ()
Export all unmuted tracks into a single file.
void renderTracks ()
Export all unmuted tracks into individual file.
Private Slots
void renderNextTrack ()
void updateConsoleProgress ()
Private Member Functions
QString pathForTrack (const Track *track, int num)
void render (QString outputPath)
void restoreMutedState ()
Private Attributes
std::unique_ptr< ProjectRenderer > m_activeRenderer
ProjectRenderer::ExportFileFormat m_format
QString m_outputPath
const OutputSettings m_outputSettings
std::vector< Track * > m_tracksToRender
std::vector< Track * > m_unmuted
Detailed Description
Definition at line 39 of file RenderManager.h.
Constructor & Destructor Documentation
RenderManager()
lmms::RenderManager::RenderManager (const OutputSettings & outputSettings, ProjectRenderer::ExportFileFormat fmt, QString outputPath)
Definition at line 37 of file RenderManager.cpp.
References lmms::Engine::audioEngine(), m_format, m_outputPath, m_outputSettings, and lmms::AudioEngine::storeAudioDevice().
~RenderManager()
lmms::RenderManager::~RenderManager () override
Definition at line 46 of file RenderManager.cpp.
References lmms::Engine::audioEngine(), and lmms::AudioEngine::restoreAudioDevice().
Member Function Documentation
abortProcessing()
void lmms::RenderManager::abortProcessing ()
Definition at line 51 of file RenderManager.cpp.
References finished(), m_activeRenderer, renderNextTrack(), and restoreMutedState().
finished
void lmms::RenderManager::finished () signal
Referenced by abortProcessing(), render(), and renderNextTrack().
pathForTrack()
QString lmms::RenderManager::pathForTrack (const Track * track, int num) private
Definition at line 171 of file RenderManager.cpp.
References lmms::FILENAME_FILTER, lmms::ProjectRenderer::getFileExtensionFromFormat(), m_format, m_outputPath, and lmms::Track::name().
Referenced by renderNextTrack().
progressChanged
void lmms::RenderManager::progressChanged (int) signal
Referenced by render().
render()
void lmms::RenderManager::render (QString outputPath) private
Definition at line 135 of file RenderManager.cpp.
References finished(), m_activeRenderer, m_format, m_outputSettings, progressChanged(), and renderNextTrack().
Referenced by renderNextTrack(), and renderProject().
renderNextTrack
void lmms::RenderManager::renderNextTrack () private slot
Definition at line 62 of file RenderManager.cpp.
References finished(), m_activeRenderer, m_tracksToRender, m_unmuted, pathForTrack(), render(), and restoreMutedState().
Referenced by abortProcessing(), render(), and renderTracks().
renderProject()
void lmms::RenderManager::renderProject ()
Export all unmuted tracks into a single file.
Definition at line 130 of file RenderManager.cpp.
References m_outputPath, and render().
renderTracks()
void lmms::RenderManager::renderTracks ()
Export all unmuted tracks into individual file.
Definition at line 92 of file RenderManager.cpp.
References lmms::Engine::getSong(), lmms::Track::Instrument, m_tracksToRender, m_unmuted, lmms::Engine::patternStore(), renderNextTrack(), lmms::Track::Sample, and lmms::TrackContainer::tracks().
restoreMutedState()
void lmms::RenderManager::restoreMutedState () private
Definition at line 160 of file RenderManager.cpp.
References m_unmuted.
Referenced by abortProcessing(), and renderNextTrack().
updateConsoleProgress
void lmms::RenderManager::updateConsoleProgress () private slot
Definition at line 180 of file RenderManager.cpp.
References m_activeRenderer, m_tracksToRender, and m_unmuted.
Member Data Documentation
m_activeRenderer
std::unique_ptr<ProjectRenderer> lmms::RenderManager::m_activeRenderer private
Definition at line 73 of file RenderManager.h.
Referenced by abortProcessing(), render(), renderNextTrack(), and updateConsoleProgress().
m_format
ProjectRenderer::ExportFileFormat lmms::RenderManager::m_format private
Definition at line 70 of file RenderManager.h.
Referenced by RenderManager(), pathForTrack(), and render().
m_outputPath
QString lmms::RenderManager::m_outputPath private
Definition at line 71 of file RenderManager.h.
Referenced by RenderManager(), pathForTrack(), and renderProject().
m_outputSettings
const OutputSettings lmms::RenderManager::m_outputSettings private
Definition at line 69 of file RenderManager.h.
Referenced by RenderManager(), and render().
m_tracksToRender
std::vector<Track*> lmms::RenderManager::m_tracksToRender private
Definition at line 75 of file RenderManager.h.
Referenced by renderNextTrack(), renderTracks(), and updateConsoleProgress().
m_unmuted
std::vector<Track*> lmms::RenderManager::m_unmuted private
Definition at line 76 of file RenderManager.h.
Referenced by renderNextTrack(), renderTracks(), restoreMutedState(), and updateConsoleProgress().
The documentation for this class was generated from the following files:
include/RenderManager.h
src/core/RenderManager.cpp