LMMS: Jack::JackMidiDriver Class Reference
Jack::JackMidiDriver Class Reference
The base class for MIDI drivers: drivers with MIDI ports.
#include <JackMidiDriver.h>
Public Member Functions
JackMidiDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackMidiDriver ()
virtual int Attach ()
virtual int Detach ()
virtual int Open (bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int SetBufferSize (jack_nframes_t buffer_size)
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsFixedBufferSize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int ProcessRead ()
int ProcessReadSlaves ()
virtual int ProcessWrite ()
int ProcessWriteSlaves ()
virtual int Read ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
virtual int SetSampleRate (jack_nframes_t sample_rate)
virtual int Start ()
virtual int Stop ()
virtual int Write ()
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Protected Member Functions
JackMidiBuffer * GetInputBuffer (int port_index)
JackMidiBuffer * GetOutputBuffer (int port_index)
virtual int ProcessReadAsync ()
virtual int ProcessReadSync ()
virtual int ProcessWriteAsync ()
virtual int ProcessWriteSync ()
virtual void UpdateLatencies ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Additional Inherited Members
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The base class for MIDI drivers: drivers with MIDI ports.
A concrete derived class will have to be defined with a real MIDI driver API, either callback based one (like CoreMIDI..) ones or blocking ones (like ALSA MIDI).
Definition at line 39 of file JackMidiDriver.h.
Constructor & Destructor Documentation
JackMidiDriver()
Jack::JackMidiDriver::JackMidiDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table)
Definition at line 35 of file JackMidiDriver.cpp.
References Jack::JackDriver::JackDriver().
Referenced by Jack::JackALSARawMidiDriver::JackALSARawMidiDriver(), and Jack::JackWinMMEDriver::JackWinMMEDriver().
~JackMidiDriver()
Jack::JackMidiDriver::~JackMidiDriver () virtual
Definition at line 39 of file JackMidiDriver.cpp.
Member Function Documentation
Attach()
int Jack::JackMidiDriver::Attach () virtual
Reimplemented from Jack::JackDriver.
Reimplemented in Jack::JackALSARawMidiDriver, Jack::JackCoreMidiDriver, Jack::JackWinMMEDriver, JackALSARawMidiDriver, and JackWinMMEDriver.
Definition at line 57 of file JackMidiDriver.cpp.
References CaptureDriverFlags, Jack::JackDriver::fAliasName, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCaptureDriverName, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fClientControl, Jack::JackDriver::fEngine, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackDriverName, Jack::JackDriver::fPlaybackPortList, i, JACK_DEFAULT_MIDI_TYPE, jack_error, jack_log(), PlaybackDriverFlags, REAL_JACK_PORT_NAME_SIZE, Jack::JackPort::SetAlias(), and UpdateLatencies().
Detach()
int Jack::JackMidiDriver::Detach () virtual
Reimplemented from Jack::JackDriver.
Definition at line 97 of file JackMidiDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fClientControl, Jack::JackDriver::fEngine, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, i, and jack_log().
GetInputBuffer()
JackMidiBuffer * Jack::JackMidiDriver::GetInputBuffer (int port_index) protected
Definition at line 201 of file JackMidiDriver.cpp.
References Jack::JackDriver::fCapturePortList, Jack::JackDriver::fEngineControl, and Jack::JackDriver::fGraphManager.
Referenced by Jack::JackALSARawMidiDriver::Read(), and Jack::JackWinMMEDriver::Read().
GetOutputBuffer()
JackMidiBuffer * Jack::JackMidiDriver::GetOutputBuffer (int port_index) protected
Definition at line 207 of file JackMidiDriver.cpp.
References Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, and Jack::JackDriver::fPlaybackPortList.
Referenced by Jack::JackALSARawMidiDriver::Write(), and Jack::JackWinMMEDriver::Write().
Open()
int Jack::JackMidiDriver::Open (bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency) virtual
Reimplemented in Jack::JackALSARawMidiDriver, Jack::JackCoreMidiDriver, Jack::JackWinMMEDriver, JackALSARawMidiDriver, and JackWinMMEDriver.
Definition at line 42 of file JackMidiDriver.cpp.
References capture_latency, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::Open(), and playback_latency.
Referenced by Jack::JackALSARawMidiDriver::Open(), and Jack::JackWinMMEDriver::Open().
ProcessReadAsync()
int Jack::JackMidiDriver::ProcessReadAsync () protected virtual
Reimplemented from Jack::JackDriver.
Definition at line 172 of file JackMidiDriver.cpp.
References jack_error, Jack::JackDriver::Read(), Jack::JackDriver::ResumeRefNum(), and Jack::JackDriver::Write().
ProcessReadSync()
int Jack::JackMidiDriver::ProcessReadSync () protected virtual
Reimplemented from Jack::JackDriver.
Definition at line 136 of file JackMidiDriver.cpp.
References jack_error, Jack::JackDriver::Read(), and Jack::JackDriver::ResumeRefNum().
ProcessWriteAsync()
int Jack::JackMidiDriver::ProcessWriteAsync () protected virtual
Reimplemented from Jack::JackDriver.
Definition at line 196 of file JackMidiDriver.cpp.
ProcessWriteSync()
int Jack::JackMidiDriver::ProcessWriteSync () protected virtual
Reimplemented from Jack::JackDriver.
Definition at line 154 of file JackMidiDriver.cpp.
References jack_error, Jack::JackDriver::SuspendRefNum(), and Jack::JackDriver::Write().
SetBufferSize()
int Jack::JackMidiDriver::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackDriver.
Definition at line 130 of file JackMidiDriver.cpp.
References UpdateLatencies().
UpdateLatencies()
void Jack::JackMidiDriver::UpdateLatencies () protected virtual
Definition at line 113 of file JackMidiDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, i, JackCaptureLatency, JackPlaybackLatency, _jack_latency_range::max, and _jack_latency_range::min.
Referenced by Attach(), and SetBufferSize().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackMidiDriver.h
src/3rdparty/jack2/common/JackMidiDriver.cpp