LMMS: Jack::JackWinNamedPipeServerNotifyChannel Class Reference
Jack::JackWinNamedPipeServerNotifyChannel Class Reference
JackServerNotifyChannel using pipes.
#include <JackWinNamedPipeServerNotifyChannel.h>
Public Member Functions
JackWinNamedPipeServerNotifyChannel ()
void Close ()
void Notify (int refnum, int notify, int value)
void NotifyQuit ()
int Open (const char *server_name)
Private Attributes
JackWinNamedPipeClient fRequestPipe
Detailed Description
JackServerNotifyChannel using pipes.
Definition at line 34 of file JackWinNamedPipeServerNotifyChannel.h.
Constructor & Destructor Documentation
JackWinNamedPipeServerNotifyChannel()
Jack::JackWinNamedPipeServerNotifyChannel::JackWinNamedPipeServerNotifyChannel () inline
Definition at line 42 of file JackWinNamedPipeServerNotifyChannel.h.
Member Function Documentation
Close()
void Jack::JackWinNamedPipeServerNotifyChannel::Close ()
Definition at line 39 of file JackWinNamedPipeServerNotifyChannel.cpp.
References fRequestPipe.
Notify()
void Jack::JackWinNamedPipeServerNotifyChannel::Notify (int refnum, int notify, int value)
Definition at line 50 of file JackWinNamedPipeServerNotifyChannel.cpp.
References fRequestPipe, jack_error, and Jack::JackClientNotificationRequest::Write().
Referenced by NotifyQuit().
NotifyQuit()
void Jack::JackWinNamedPipeServerNotifyChannel::NotifyQuit ()
Definition at line 58 of file JackWinNamedPipeServerNotifyChannel.cpp.
References Jack::kQUIT, and Notify().
Open()
int Jack::JackWinNamedPipeServerNotifyChannel::Open (const char * server_name)
Definition at line 29 of file JackWinNamedPipeServerNotifyChannel.cpp.
References fRequestPipe, jack_error, jack_server_dir, and server_name.
Member Data Documentation
fRequestPipe
JackWinNamedPipeClient Jack::JackWinNamedPipeServerNotifyChannel::fRequestPipe private
Definition at line 38 of file JackWinNamedPipeServerNotifyChannel.h.
Referenced by Close(), Notify(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinNamedPipeServerNotifyChannel.h
src/3rdparty/jack2/windows/JackWinNamedPipeServerNotifyChannel.cpp