LMMS: lmms::gui::FileBrowserTreeWidget Class Reference
lmms::gui::FileBrowserTreeWidget Class Reference
#include <FileBrowser.h>
Public Member Functions
FileBrowserTreeWidget (QWidget *parent)
~FileBrowserTreeWidget () override=default
QList< QString > expandedDirs (QTreeWidgetItem *item=nullptr) const
This method returns a QList with paths (QString's) of all directories that are expanded in the tree.
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e) override
void focusOutEvent (QFocusEvent *fe) override
void hideEvent (QHideEvent *he) override
void keyPressEvent (QKeyEvent *ke) override
void keyReleaseEvent (QKeyEvent *ke) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
Private Slots
void activateListItem (QTreeWidgetItem *item, int column)
void openInNewInstrumentTrack (FileItem *item, bool songEditor)
bool openInNewSampleTrack (FileItem *item)
void openInSlicerT (FileItem *item)
void sendToActiveInstrumentTrack (FileItem *item)
void updateDirectory (QTreeWidgetItem *item)
Private Member Functions
QList< QAction * > getContextActions (FileItem *item, bool songEditor)
void handleFile (FileItem *fi, InstrumentTrack *it)
void openInNewInstrumentTrack (TrackContainer *tc, FileItem *item)
void previewFileItem (FileItem *file)
Start a preview of a file item.
void stopPreview ()
If a preview is playing, stop it.
Private Attributes
bool m_mousePressed
QRecursiveMutex m_pphMutex
QPoint m_pressPos
PlayHandle * m_previewPlayHandle
This should only be accessed or modified when m_pphMutex is held.
Detailed Description
Definition at line 130 of file FileBrowser.h.
Constructor & Destructor Documentation
FileBrowserTreeWidget()
lmms::gui::FileBrowserTreeWidget::FileBrowserTreeWidget (QWidget * parent)
Definition at line 452 of file FileBrowser.cpp.
References activateListItem(), m_mousePressed, m_pphMutex, m_pressPos, m_previewPlayHandle, and updateDirectory().
~FileBrowserTreeWidget()
lmms::gui::FileBrowserTreeWidget::~FileBrowserTreeWidget () override default
References file.
Member Function Documentation
activateListItem
void lmms::gui::FileBrowserTreeWidget::activateListItem (QTreeWidgetItem * item, int column) private slot
Definition at line 953 of file FileBrowser.cpp.
References lmms::Track::create(), handleFile(), lmms::gui::FileItem::ImportAsProject, lmms::Track::Instrument, lmms::gui::FileItem::LoadAsProject, lmms::gui::FileItem::NotSupported, and lmms::Engine::patternStore().
Referenced by FileBrowserTreeWidget().
contextMenuEvent()
void lmms::gui::FileBrowserTreeWidget::contextMenuEvent (QContextMenuEvent * e) override protected
Definition at line 582 of file FileBrowser.cpp.
References lmms::ConfigManager::addFavoriteItem(), file, getContextActions(), lmms::embed::getIconPixmap(), lmms::ConfigManager::inst(), lmms::gui::FileRevealer::openDir(), lmms::ConfigManager::removeFavoriteItem(), lmms::gui::FileRevealer::reveal(), sendToActiveInstrumentTrack(), lmms::PathUtil::toShortestRelative(), lmms::gui::TypeDirectoryItem, and lmms::gui::TypeFileItem.
expandedDirs()
QList< QString > lmms::gui::FileBrowserTreeWidget::expandedDirs (QTreeWidgetItem * item = nullptr) const
This method returns a QList with paths (QString's) of all directories that are expanded in the tree.
Definition at line 484 of file FileBrowser.cpp.
References expandedDirs(), i, and lmms::gui::TypeDirectoryItem.
Referenced by expandedDirs().
focusOutEvent()
void lmms::gui::FileBrowserTreeWidget::focusOutEvent (QFocusEvent * fe) override protected
Definition at line 575 of file FileBrowser.cpp.
References stopPreview().
getContextActions()
QList< QAction * > lmms::gui::FileBrowserTreeWidget::getContextActions (FileItem * item, bool songEditor) private
Definition at line 685 of file FileBrowser.cpp.
References file, lmms::PluginFactory::instance(), openInNewInstrumentTrack(), openInNewSampleTrack(), openInSlicerT(), lmms::gui::FileItem::Sample, and lmms::UI_CTRL_KEY.
Referenced by contextMenuEvent().
handleFile()
void lmms::gui::FileBrowserTreeWidget::handleFile (FileItem * fi, InstrumentTrack * it) private
Definition at line 906 of file FileBrowser.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), lmms::gui::FileItem::extension(), lmms::gui::FileItem::fullName(), lmms::gui::getGUI(), lmms::getPluginFactory(), lmms::Engine::getSong(), lmms::gui::FileItem::handling(), i, lmms::ImportFilter::import(), lmms::gui::FileItem::ImportAsProject, lmms::PluginFactory::PluginInfoAndKey::info, lmms::InstrumentTrack::instrument(), lmms::PluginFactory::PluginInfoAndKey::key, lmms::gui::FileItem::LoadAsPreset, lmms::gui::FileItem::LoadAsProject, lmms::gui::FileItem::LoadByPlugin, lmms::InstrumentTrack::loadInstrument(), lmms::Song::loadProject(), lmms::PluginFactory::PluginInfo::name(), lmms::gui::FileItem::NotSupported, lmms::PluginFactory::pluginSupportingExtension(), lmms::InstrumentTrack::replaceInstrument(), and lmms::AudioEngine::requestChangeInModel().
Referenced by activateListItem(), openInNewInstrumentTrack(), and sendToActiveInstrumentTrack().
hideEvent()
void lmms::gui::FileBrowserTreeWidget::hideEvent (QHideEvent * he) override protected
Definition at line 565 of file FileBrowser.cpp.
References stopPreview().
keyPressEvent()
void lmms::gui::FileBrowserTreeWidget::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 509 of file FileBrowser.cpp.
References file, openInNewInstrumentTrack(), openInNewSampleTrack(), previewFileItem(), lmms::gui::FileItem::Sample, and stopPreview().
keyReleaseEvent()
void lmms::gui::FileBrowserTreeWidget::keyReleaseEvent (QKeyEvent * ke) override protected
Definition at line 556 of file FileBrowser.cpp.
References stopPreview().
mouseMoveEvent()
void lmms::gui::FileBrowserTreeWidget::mouseMoveEvent (QMouseEvent * me) override protected
Definition at line 831 of file FileBrowser.cpp.
References lmms::embed::getIconPixmap(), lmms::gui::FileItem::LoadAsPreset, m_mousePressed, m_pressPos, lmms::gui::FileItem::Midi, mouseReleaseEvent(), lmms::gui::FileItem::Patch, lmms::gui::FileItem::Preset, lmms::gui::FileItem::Project, lmms::gui::FileItem::Sample, lmms::gui::FileItem::SoundFont, and lmms::gui::FileItem::VstPlugin.
mousePressEvent()
void lmms::gui::FileBrowserTreeWidget::mousePressEvent (QMouseEvent * me) override protected
Definition at line 722 of file FileBrowser.cpp.
References i, m_mousePressed, m_pressPos, and previewFileItem().
mouseReleaseEvent()
void lmms::gui::FileBrowserTreeWidget::mouseReleaseEvent (QMouseEvent * me) override protected
Definition at line 887 of file FileBrowser.cpp.
References lmms::ConfigManager::inst(), m_mousePressed, m_pphMutex, m_previewPlayHandle, lmms::PlayHandle::SamplePlayHandle, stopPreview(), and lmms::ConfigManager::value().
Referenced by mouseMoveEvent().
openInNewInstrumentTrack [1/2]
void lmms::gui::FileBrowserTreeWidget::openInNewInstrumentTrack (FileItem * item, bool songEditor) private slot
Definition at line 989 of file FileBrowser.cpp.
References lmms::Engine::getSong(), openInNewInstrumentTrack(), and lmms::Engine::patternStore().
openInNewInstrumentTrack() [2/2]
void lmms::gui::FileBrowserTreeWidget::openInNewInstrumentTrack (TrackContainer * tc, FileItem * item) private
Definition at line 977 of file FileBrowser.cpp.
References lmms::Track::create(), handleFile(), lmms::Track::Instrument, and lmms::gui::FileItem::isTrack().
Referenced by getContextActions(), keyPressEvent(), and openInNewInstrumentTrack().
openInNewSampleTrack
bool lmms::gui::FileBrowserTreeWidget::openInNewSampleTrack (FileItem * item) private slot
Definition at line 1000 of file FileBrowser.cpp.
References lmms::Engine::audioEngine(), lmms::Track::create(), lmms::AudioEngine::doneChangeInModel(), lmms::gui::FileItem::fullName(), lmms::Engine::getSong(), lmms::AudioEngine::requestChangeInModel(), lmms::gui::FileItem::Sample, lmms::Track::Sample, lmms::SampleClip::setSampleFile(), and lmms::gui::FileItem::type().
Referenced by getContextActions(), and keyPressEvent().
openInSlicerT
void lmms::gui::FileBrowserTreeWidget::openInSlicerT (FileItem * item) private slot
Definition at line 675 of file FileBrowser.cpp.
References lmms::Track::create(), lmms::gui::FileItem::fullName(), lmms::Engine::getSong(), lmms::Track::Instrument, lmms::Plugin::loadFile(), and lmms::InstrumentTrack::loadInstrument().
Referenced by getContextActions().
previewFileItem()
void lmms::gui::FileBrowserTreeWidget::previewFileItem (FileItem * file) private
Start a preview of a file item.
Definition at line 751 of file FileBrowser.cpp.
References lmms::Engine::audioEngine(), lmms::gui::SampleLoader::createBufferFromFile(), lmms::gui::TextFloat::displayMessage(), file, lmms::embed::getIconPixmap(), lmms::getPluginFactory(), lmms::gui::FileItem::LoadByPlugin, m_pphMutex, m_previewPlayHandle, lmms::gui::FileItem::Sample, lmms::SamplePlayHandle::setDoneMayReturnTrue(), stopPreview(), lmms::DataFile::validate(), and lmms::gui::FileItem::VstPlugin.
Referenced by keyPressEvent(), and mousePressEvent().
sendToActiveInstrumentTrack
void lmms::gui::FileBrowserTreeWidget::sendToActiveInstrumentTrack (FileItem * item) private slot
Definition at line 1018 of file FileBrowser.cpp.
References lmms::gui::getGUI(), handleFile(), lmms::gui::GuiApplication::mainWindow(), and lmms::gui::MainWindow::workspace().
Referenced by contextMenuEvent().
stopPreview()
void lmms::gui::FileBrowserTreeWidget::stopPreview () private
If a preview is playing, stop it.
Definition at line 818 of file FileBrowser.cpp.
References lmms::Engine::audioEngine(), m_pphMutex, m_previewPlayHandle, and lmms::AudioEngine::removePlayHandle().
Referenced by focusOutEvent(), hideEvent(), keyPressEvent(), keyReleaseEvent(), mouseReleaseEvent(), and previewFileItem().
updateDirectory
void lmms::gui::FileBrowserTreeWidget::updateDirectory (QTreeWidgetItem * item) private slot
Definition at line 1042 of file FileBrowser.cpp.
Referenced by FileBrowserTreeWidget().
Member Data Documentation
m_mousePressed
bool lmms::gui::FileBrowserTreeWidget::m_mousePressed private
Definition at line 162 of file FileBrowser.h.
Referenced by FileBrowserTreeWidget(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_pphMutex
QRecursiveMutex lmms::gui::FileBrowserTreeWidget::m_pphMutex private
Definition at line 169 of file FileBrowser.h.
Referenced by FileBrowserTreeWidget(), mouseReleaseEvent(), previewFileItem(), and stopPreview().
m_pressPos
QPoint lmms::gui::FileBrowserTreeWidget::m_pressPos private
Definition at line 163 of file FileBrowser.h.
Referenced by FileBrowserTreeWidget(), mouseMoveEvent(), and mousePressEvent().
m_previewPlayHandle
PlayHandle* lmms::gui::FileBrowserTreeWidget::m_previewPlayHandle private
This should only be accessed or modified when m_pphMutex is held.
Definition at line 166 of file FileBrowser.h.
Referenced by FileBrowserTreeWidget(), mouseReleaseEvent(), previewFileItem(), and stopPreview().
The documentation for this class was generated from the following files:
include/FileBrowser.h
src/gui/FileBrowser.cpp