LMMS: Jack::JackInternalSessionLoader Class Reference
Jack::JackInternalSessionLoader Class Reference
#include <JackInternalSessionLoader.h>
Public Member Functions
JackInternalSessionLoader (JackServer *const server)
int Load (const char *file)
Private Member Functions
void ConnectPorts (std::istringstream &iss, const int linenr)
void LoadClient (std::istringstream &iss, const int linenr)
Private Attributes
JackServer *const fServer
Detailed Description
Definition at line 31 of file JackInternalSessionLoader.h.
Constructor & Destructor Documentation
JackInternalSessionLoader()
Jack::JackInternalSessionLoader::JackInternalSessionLoader (JackServer *const server)
Definition at line 28 of file JackInternalSessionLoader.cpp.
References fServer, and server().
Member Function Documentation
ConnectPorts()
void Jack::JackInternalSessionLoader::ConnectPorts (std::istringstream & iss, const int linenr) private
Definition at line 141 of file JackInternalSessionLoader.cpp.
References fServer, jack_error, jack_info(), and NO_PORT.
Referenced by Load().
Load()
int Jack::JackInternalSessionLoader::Load (const char * file)
Definition at line 33 of file JackInternalSessionLoader.cpp.
References ConnectPorts(), file, jack_error, and LoadClient().
Referenced by Jack::JackServer::LoadInternalSessionFile().
LoadClient()
void Jack::JackInternalSessionLoader::LoadClient (std::istringstream & iss, const int linenr) private
Definition at line 81 of file JackInternalSessionLoader.cpp.
References fServer, jack_error, jack_info(), JackLoadInit, JackLoadName, JackNameNotUnique, and JackUseExactName.
Referenced by Load().
Member Data Documentation
fServer
JackServer* const Jack::JackInternalSessionLoader::fServer private
Definition at line 41 of file JackInternalSessionLoader.h.
Referenced by JackInternalSessionLoader(), ConnectPorts(), and LoadClient().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackInternalSessionLoader.h
src/3rdparty/jack2/common/JackInternalSessionLoader.cpp