LMMS: src/3rdparty/jack2/common/shm.h File Reference
shm.h File Reference
#include <limits.h>
#include <sys/types.h>
#include "types.h"
#include "JackCompilerDeps.h"
#include "JackConstants.h"
Classes
struct _jack_shm_header
struct _jack_shm_info
a structure holding information about shared memory allocated by JACK.
struct _jack_shm_registry
struct _jack_shm_server
A structure holding information about shared memory allocated by JACK.
Macros
#define FALSE 0
#define JACK_SHM_MAGIC 0x4a41434b /* shm magic number: "JACK" */
#define JACK_SHM_NULL_INDEX -1 /* NULL SHM index */
#define JACK_SHM_REGISTRY_INDEX -2 /* pseudo SHM index for registry */
#define JACK_SHM_REGISTRY_SIZE
#define MAX_SERVERS 8 /* maximum concurrent servers */
#define MAX_SHM_ID 256 /* generally about 16 per server */
#define TRUE 1
Typedefs
typedef struct _jack_shm_header jack_shm_header_t
typedef int jack_shm_id_t
typedef struct _jack_shm_info jack_shm_info_t
typedef int16_t jack_shm_registry_index_t
typedef struct _jack_shm_registry jack_shm_registry_t
typedef struct _jack_shm_server jack_shm_server_t
A structure holding information about shared memory allocated by JACK.
Enumerations
enum jack_shmtype_t {
shm_POSIX = 1 ,
shm_SYSV = 2 ,
shm_WIN32 = 3 ,
shm_ANDROID = 4
}
Functions
int jack_attach_lib_shm (jack_shm_info_t *)
int jack_attach_lib_shm_read (jack_shm_info_t *)
int jack_attach_shm (jack_shm_info_t *)
int jack_attach_shm_read (jack_shm_info_t *)
int jack_cleanup_shm (void)
void jack_destroy_shm (jack_shm_info_t *)
int jack_initialize_shm (const char *server_name)
int jack_initialize_shm_client (void)
int jack_initialize_shm_server (void)
int jack_register_server (const char *server_name, int new_registry)
void jack_release_lib_shm (jack_shm_info_t *)
void jack_release_shm (jack_shm_info_t *)
int jack_release_shm_info (jack_shm_registry_index_t)
int jack_resize_shm (jack_shm_info_t *, jack_shmsize_t size)
char * jack_shm_addr (jack_shm_info_t *si)
void jack_shm_copy_from_registry (jack_shm_info_t *, jack_shm_registry_index_t)
void jack_shm_copy_to_registry (jack_shm_info_t *, jack_shm_registry_index_t *)
int jack_shmalloc (const char *shm_name, jack_shmsize_t size, jack_shm_info_t *result)
int jack_unregister_server (const char *server_name)
Variables
PRE_PACKED_STRUCTURE struct _jack_shm_info POST_PACKED_STRUCTURE
Macro Definition Documentation
FALSE
#define FALSE 0
Definition at line 44 of file shm.h.
Referenced by Jack::JackBaseWinMutex::JackBaseWinMutex(), Jack::JackClientPipeThread::JackClientPipeThread(), Jack::JackWinMutex::JackWinMutex(), Jack::JackWinProcessSync::JackWinProcessSync(), Jack::JackWinThread::JackWinThread(), android::Shm::access_registry(), Jack::JackWinEvent::Allocate(), Jack::JackWinSemaphore::Allocate(), android::Shm::cleanup_shm(), Jack::JackWinEvent::ConnectInput(), Jack::JackWinSemaphore::ConnectInput(), driver_get_descriptor(), driver_initialize(), Jack::JackWinAsyncNamedPipeClient::FinishIO(), jack_get_descriptor(), and Jack::JackWinMMEOutputPort::Start().
JACK_SHM_MAGIC
#define JACK_SHM_MAGIC 0x4a41434b /* shm magic number: "JACK" */
Definition at line 53 of file shm.h.
Referenced by android::Shm::shm_init_registry(), and android::Shm::shm_validate_registry().
JACK_SHM_NULL_INDEX
#define JACK_SHM_NULL_INDEX -1 /* NULL SHM index */
Definition at line 54 of file shm.h.
Referenced by android::Shm::destroy_shm().
JACK_SHM_REGISTRY_INDEX
#define JACK_SHM_REGISTRY_INDEX -2 /* pseudo SHM index for registry */
Definition at line 55 of file shm.h.
Referenced by android::Shm::access_registry(), and android::Shm::create_registry().
JACK_SHM_REGISTRY_SIZE
#define JACK_SHM_REGISTRY_SIZE
Value:
                (sizeof (jack_shm_header_t) \
                + sizeof (jack_shm_registry_t) * MAX_SHM_ID)
Definition at line 163 of file shm.h.
Referenced by android::Shm::create_registry(), android::Shm::shm_init_registry(), and android::Shm::shm_validate_registry().
MAX_SERVERS
#define MAX_SERVERS 8 /* maximum concurrent servers */
Definition at line 51 of file shm.h.
Referenced by android::Shm::register_server(), and android::Shm::unregister_server().
MAX_SHM_ID
#define MAX_SHM_ID 256 /* generally about 16 per server */
Definition at line 52 of file shm.h.
Referenced by android::Shm::cleanup_shm(), android::Shm::get_free_shm_info(), android::Shm::remove_shm(), and android::Shm::shm_init_registry().
TRUE
#define TRUE 1
Definition at line 43 of file shm.h.
Referenced by Jack::JackWinAsyncNamedPipeClient::JackWinAsyncNamedPipeClient(), Jack::JackWinAsyncNamedPipeClient::JackWinAsyncNamedPipeClient(), Jack::JackWinProcessSync::JackWinProcessSync(), android::Shm::cleanup_shm(), and driver_initialize().
Typedef Documentation
jack_shm_header_t
typedef struct _jack_shm_header jack_shm_header_t
jack_shm_id_t
typedef int jack_shm_id_t
Definition at line 97 of file shm.h.
jack_shm_info_t
typedef struct _jack_shm_info jack_shm_info_t
Definition at line 187 of file shm.h.
jack_shm_registry_index_t
typedef int16_t jack_shm_registry_index_t
Definition at line 112 of file shm.h.
jack_shm_registry_t
typedef struct _jack_shm_registry jack_shm_registry_t
jack_shm_server_t
typedef struct _jack_shm_server jack_shm_server_t
A structure holding information about shared memory allocated by JACK.
this persists across invocations of JACK, and can be used by multiple JACK servers. It contains no pointers and is valid across address spaces.
The registry consists of two parts: a header including an array of server names, followed by an array of segment registry entries.
Enumeration Type Documentation
jack_shmtype_t
enum jack_shmtype_t
Enumerator
shm_POSIX
shm_SYSV
shm_WIN32
shm_ANDROID
Definition at line 101 of file shm.h.
Function Documentation
jack_attach_lib_shm()
int jack_attach_lib_shm (jack_shm_info_t * si)
Definition at line 871 of file Shm.cpp.
References android::Shm::jack_attach_lib_shm().
Referenced by Jack::JackShmReadWritePtr1< T >::Init(), and Jack::JackShmReadWritePtr< T >::Init().
jack_attach_lib_shm_read()
int jack_attach_lib_shm_read (jack_shm_info_t * si)
Definition at line 877 of file Shm.cpp.
References android::Shm::jack_attach_lib_shm_read().
Referenced by Jack::JackShmReadPtr< T >::Init().
jack_attach_shm()
int jack_attach_shm (jack_shm_info_t * si)
Definition at line 868 of file Shm.cpp.
References android::Shm::jack_attach_shm().
Referenced by Jack::JackShmMem::operator new().
jack_attach_shm_read()
int jack_attach_shm_read (jack_shm_info_t * si)
Definition at line 874 of file Shm.cpp.
References android::Shm::jack_attach_shm_read().
jack_cleanup_shm()
int jack_cleanup_shm (void)
Definition at line 853 of file Shm.cpp.
References android::Shm::jack_cleanup_shm().
Referenced by Jack::JackServerGlobals::Destroy(), Jack::JackServerGlobals::Init(), jackctl_server_close(), and jackctl_server_open().
jack_destroy_shm()
void jack_destroy_shm (jack_shm_info_t * si)
Definition at line 865 of file Shm.cpp.
References android::Shm::jack_destroy_shm().
jack_initialize_shm()
int jack_initialize_shm (const char * server_name)
Definition at line 844 of file Shm.cpp.
References android::Shm::jack_initialize_shm(), and server_name.
Referenced by Jack::JackShmReadPtr< T >::Init(), Jack::JackShmReadWritePtr1< T >::Init(), and Jack::JackShmReadWritePtr< T >::Init().
jack_initialize_shm_client()
int jack_initialize_shm_client (void)
Definition at line 850 of file Shm.cpp.
References android::Shm::jack_initialize_shm_client().
jack_initialize_shm_server()
int jack_initialize_shm_server (void)
Definition at line 847 of file Shm.cpp.
References android::Shm::jack_initialize_shm_server().
jack_register_server()
int jack_register_server (const char * server_name, int new_registry)
Definition at line 838 of file Shm.cpp.
References android::Shm::jack_register_server(), and server_name.
Referenced by Jack::JackServerGlobals::Init(), and jackctl_server_open().
jack_release_lib_shm()
void jack_release_lib_shm (jack_shm_info_t * si)
Definition at line 862 of file Shm.cpp.
References android::Shm::jack_release_lib_shm().
Referenced by Jack::JackShmReadPtr< T >::~JackShmReadPtr(), Jack::JackShmReadWritePtr< T >::~JackShmReadWritePtr(), and Jack::JackShmReadWritePtr1< T >::~JackShmReadWritePtr1().
jack_release_shm()
void jack_release_shm (jack_shm_info_t * si)
Definition at line 859 of file Shm.cpp.
References android::Shm::jack_release_shm().
Referenced by Jack::JackShmMem::operator delete().
jack_release_shm_info()
int jack_release_shm_info (jack_shm_registry_index_t t)
Definition at line 832 of file Shm.cpp.
References android::Shm::jack_release_shm_info().
jack_resize_shm()
int jack_resize_shm (jack_shm_info_t * si, jack_shmsize_t size)
Definition at line 880 of file Shm.cpp.
References android::Shm::jack_resize_shm().
jack_shm_addr()
char * jack_shm_addr (jack_shm_info_t * si)
Definition at line 835 of file Shm.cpp.
References android::Shm::jack_shm_addr().
Referenced by Jack::JackShmMem::operator new().
jack_shm_copy_from_registry()
void jack_shm_copy_from_registry (jack_shm_info_t * si, jack_shm_registry_index_t t)
Definition at line 826 of file Shm.cpp.
References android::Shm::jack_shm_copy_from_registry().
jack_shm_copy_to_registry()
void jack_shm_copy_to_registry (jack_shm_info_t * si, jack_shm_registry_index_t * t)
Definition at line 829 of file Shm.cpp.
References android::Shm::jack_shm_copy_to_registry().
jack_shmalloc()
int jack_shmalloc (const char * shm_name, jack_shmsize_t size, jack_shm_info_t * result)
Definition at line 856 of file Shm.cpp.
References android::Shm::jack_shmalloc().
Referenced by Jack::JackShmMem::operator new().
jack_unregister_server()
int jack_unregister_server (const char * server_name)
Definition at line 841 of file Shm.cpp.
References android::Shm::jack_unregister_server(), and server_name.
Referenced by Jack::JackServerGlobals::Destroy(), Jack::JackServerGlobals::Init(), jackctl_server_close(), and jackctl_server_open().
Variable Documentation
POST_PACKED_STRUCTURE
PRE_PACKED_STRUCTURE struct _jack_shm_info POST_PACKED_STRUCTURE