LMMS: lmms::gui::selectableObject Class Reference
lmms::gui::selectableObject Class Reference
#include <Rubberband.h>
Public Slots
virtual void update ()
Public Member Functions
selectableObject (QWidget *_parent)
~selectableObject () override=default
bool isSelected () const
void setSelected (bool selected)
Private Attributes
bool m_selected
Detailed Description
Definition at line 36 of file Rubberband.h.
Constructor & Destructor Documentation
selectableObject()
lmms::gui::selectableObject::selectableObject (QWidget * _parent) inline
Definition at line 40 of file Rubberband.h.
References m_selected.
Referenced by lmms::gui::ClipView::ClipView().
~selectableObject()
lmms::gui::selectableObject::~selectableObject () override default
Member Function Documentation
isSelected()
bool lmms::gui::selectableObject::isSelected () const inline
Definition at line 55 of file Rubberband.h.
References m_selected.
Referenced by lmms::gui::ClipView::getColorForDisplay(), lmms::gui::ClipView::mousePressEvent(), lmms::gui::ClipView::mouseReleaseEvent(), lmms::gui::SampleClipView::paintEvent(), and lmms::gui::ClipView::updateCursor().
setSelected()
void lmms::gui::selectableObject::setSelected (bool selected) inline
Definition at line 48 of file Rubberband.h.
References m_selected, and update().
Referenced by lmms::gui::TrackView::createClipView(), and lmms::gui::ClipView::mouseReleaseEvent().
update
virtual void lmms::gui::selectableObject::update () inline virtual slot
Definition at line 62 of file Rubberband.h.
Referenced by setSelected(), and lmms::gui::ClipView::update().
Member Data Documentation
m_selected
bool lmms::gui::selectableObject::m_selected private
Definition at line 69 of file Rubberband.h.
Referenced by selectableObject(), isSelected(), and setSelected().
The documentation for this class was generated from the following file:
include/Rubberband.h