LMMS: Jack::JackProfiler Class Reference
Jack::JackProfiler Class Reference
Server real-time monitoring.
#include <JackProfiler.h>
Public Member Functions
JackProfiler (jack_client_t *jack_client, const JSList *params)
~JackProfiler ()
Static Public Member Functions
static void ClientRegistration (const char *name, int val, void *arg)
static int Process (jack_nframes_t nframes, void *arg)
Private Attributes
jack_client_t * fClient
jack_port_t * fCPULoadPort
jack_port_t * fDriverEndPort
jack_port_t * fDriverPeriodPort
Detailed Description
Server real-time monitoring.
Definition at line 53 of file JackProfiler.h.
Constructor & Destructor Documentation
JackProfiler()
Jack::JackProfiler::JackProfiler (jack_client_t * jack_client, const JSList * params)
Definition at line 53 of file JackProfiler.cpp.
References JackProfiler(), jack_driver_param_t::character, client(), ClientRegistration(), _JSList::data, fClient, fCPULoadPort, fDriverEndPort, fDriverPeriodPort, i, jack_activate(), JACK_DEFAULT_AUDIO_TYPE, jack_get_ports(), jack_log(), jack_port_register(), jack_set_client_registration_callback(), jack_set_process_callback(), jack_slist_next, JackPortIsOutput, and Process().
Referenced by JackProfiler(), ClientRegistration(), and Process().
~JackProfiler()
Jack::JackProfiler::~JackProfiler ()
Definition at line 96 of file JackProfiler.cpp.
References jack_log().
Member Function Documentation
ClientRegistration()
void Jack::JackProfiler::ClientRegistration (const char * name, int val, void * arg) static
Definition at line 101 of file JackProfiler.cpp.
References JackProfiler(), jack_get_client_name(), jack_log(), and profiler.
Referenced by JackProfiler().
Process()
int Jack::JackProfiler::Process (jack_nframes_t nframes, void * arg) static
Definition at line 129 of file JackProfiler.cpp.
References JackProfiler(), Jack::JackTimingMeasureClient::fAwakeAt, Jack::JackTimingMeasure::fClientTable, Jack::JackTimingMeasure::fCurCycleBegin, Jack::JackTimingMeasureClient::fFinishedAt, Jack::JackServerGlobals::fInstance, Jack::JackTimingMeasure::fPeriodUsecs, Jack::JackTimingMeasure::fPrevCycleEnd, Jack::JackTimingMeasureClient::fSignaledAt, Jack::JackEngineProfiling::GetCurMeasure(), i, jack_cpu_load(), jack_log(), jack_port_get_buffer(), and profiler.
Referenced by JackProfiler().
Member Data Documentation
fClient
jack_client_t* Jack::JackProfiler::fClient private
Definition at line 58 of file JackProfiler.h.
Referenced by JackProfiler().
fCPULoadPort
jack_port_t* Jack::JackProfiler::fCPULoadPort private
Definition at line 59 of file JackProfiler.h.
Referenced by JackProfiler().
fDriverEndPort
jack_port_t* Jack::JackProfiler::fDriverEndPort private
Definition at line 61 of file JackProfiler.h.
Referenced by JackProfiler().
fDriverPeriodPort
jack_port_t* Jack::JackProfiler::fDriverPeriodPort private
Definition at line 60 of file JackProfiler.h.
Referenced by JackProfiler().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackProfiler.h
src/3rdparty/jack2/common/JackProfiler.cpp