LMMS: Jack::JackWinMutex Class Reference
Jack::JackWinMutex Class Reference
#include <JackWinMutex.h>
Public Member Functions
JackWinMutex (const char *name=NULL)
virtual ~JackWinMutex ()
bool Lock ()
bool Trylock ()
bool Unlock ()
Protected Attributes
HANDLE fMutex
Detailed Description
Definition at line 66 of file JackWinMutex.h.
Constructor & Destructor Documentation
JackWinMutex()
Jack::JackWinMutex::JackWinMutex (const char * name = NULL) inline
Definition at line 75 of file JackWinMutex.h.
References FALSE, fMutex, MAX_PATH, and ThrowIf.
Referenced by Jack::JackWinProcessSync::JackWinProcessSync().
~JackWinMutex()
virtual Jack::JackWinMutex::~JackWinMutex () inline virtual
Definition at line 89 of file JackWinMutex.h.
References fMutex.
Member Function Documentation
Lock()
bool Jack::JackWinMutex::Lock ()
Definition at line 77 of file JackWinMutex.cpp.
References fMutex, and jack_log().
Trylock()
bool Jack::JackWinMutex::Trylock ()
Definition at line 87 of file JackWinMutex.cpp.
References fMutex, and jack_log().
Unlock()
bool Jack::JackWinMutex::Unlock ()
Definition at line 97 of file JackWinMutex.cpp.
References fMutex, and jack_log().
Member Data Documentation
fMutex
HANDLE Jack::JackWinMutex::fMutex protected
Definition at line 71 of file JackWinMutex.h.
Referenced by JackWinMutex(), ~JackWinMutex(), Lock(), Jack::JackWinProcessSync::LockedSignal(), Jack::JackWinProcessSync::TimedWait(), Trylock(), Unlock(), and Jack::JackWinProcessSync::Wait().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinMutex.h
src/3rdparty/jack2/windows/JackWinMutex.cpp