LMMS: Jack::JackGraphManager Class Reference
Jack::JackGraphManager Class Reference
Graph manager: contains the connection manager and the port array.
#include <JackGraphManager.h>
Public Member Functions
JackGraphManager (int port_max)
~JackGraphManager ()
void Activate (int refnum)
jack_port_id_t AllocatePort (int refnum, const char *port_name, const char *port_type, JackPortFlags flags, jack_nframes_t buffer_size)
int CheckPorts (jack_port_id_t port_src, jack_port_id_t port_dst)
int ComputeTotalLatencies ()
int ComputeTotalLatency (jack_port_id_t port_index)
int Connect (jack_port_id_t src_index, jack_port_id_t dst_index)
void Deactivate (int refnum)
void DirectConnect (int ref1, int ref2)
void DirectDisconnect (int ref1, int ref2)
int Disconnect (jack_port_id_t src_index, jack_port_id_t dst_index)
int DisconnectAll (jack_port_id_t port_index)
void DisconnectAllInput (jack_port_id_t port_index)
void DisconnectAllOutput (jack_port_id_t port_index)
void DisconnectAllPorts (int refnum)
void * GetBuffer (jack_port_id_t port_index, jack_nframes_t frames)
JackClientTiming * GetClientTiming (int refnum)
const char ** GetConnections (jack_port_id_t port_index)
void GetConnections (jack_port_id_t port_index, jack_int_t *connections)
int GetConnectionsNum (jack_port_id_t port_index)
void GetInputPorts (int refnum, jack_int_t *res)
int GetInputRefNum (jack_port_id_t port_index)
void GetOutputPorts (int refnum, jack_int_t *res)
int GetOutputRefNum (jack_port_id_t port_index)
jack_port_id_t GetPort (const char *name)
JackPort * GetPort (jack_port_id_t index)
const char ** GetPorts (const char *port_name_pattern, const char *type_name_pattern, unsigned long flags)
int GetTwoPorts (const char *src, const char *dst, jack_port_id_t *src_index, jack_port_id_t *dst_index)
void InitRefNum (int refnum)
int IsConnected (jack_port_id_t port_src, jack_port_id_t port_dst)
bool IsDirectConnection (int ref1, int ref2)
bool IsFinishedGraph ()
void RecalculateLatency (jack_port_id_t port_index, jack_latency_callback_mode_t mode)
int ReleasePort (int refnum, jack_port_id_t port_index)
void RemoveAllPorts (int refnum)
int RequestMonitor (jack_port_id_t port_index, bool onoff)
void Restore (JackConnectionManager *src)
int ResumeRefNum (JackClientControl *control, JackSynchro *table)
void RunCurrentGraph ()
bool RunNextGraph ()
void Save (JackConnectionManager *dst)
void SetBufferSize (jack_nframes_t buffer_size)
int SuspendRefNum (JackClientControl *control, JackSynchro *table, long usecs)
void TopologicalSort (std::vector< jack_int_t > &sorted)
Public Member Functions inherited from Jack::JackShmMem
void operator delete (void *p)
void operator delete (void *p, size_t size)
void * operator new (size_t size)
void * operator new (size_t size, void *memory)
Public Member Functions inherited from Jack::JackShmMemAble
char * GetShmAddress ()
int GetShmIndex ()
void Init ()
void LockMemory ()
void UnlockMemory ()
Public Member Functions inherited from Jack::JackAtomicState< JackConnectionManager >
JackAtomicState ()
~JackAtomicState ()
UInt16 GetCurrentIndex ()
Returns the current state index.
bool IsPendingChange ()
JackConnectionManager * ReadCurrentState ()
Returns the current state : only valid in the RT reader thread.
JackConnectionManager * TrySwitchState ()
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
JackConnectionManager * WriteNextStateStart ()
Start write operation : setup and returns the next state to update, check for recursive write calls.
void WriteNextStateStop ()
Stop write operation : make the next state ready to be used by the RT thread.
Static Public Member Functions
static JackGraphManager * Allocate (int port_max)
static void Destroy (JackGraphManager *manager)
Private Member Functions
jack_port_id_t AllocatePortAux (int refnum, const char *port_name, const char *port_type, JackPortFlags flags)
void AssertPort (jack_port_id_t port_index)
jack_nframes_t ComputeTotalLatencyAux (jack_port_id_t port_index, jack_port_id_t src_port_index, JackConnectionManager *manager, int hop_count)
jack_default_audio_sample_t * GetBuffer (jack_port_id_t port_index)
void * GetBufferAux (JackConnectionManager *manager, jack_port_id_t port_index, jack_nframes_t frames)
void GetConnectionsAux (JackConnectionManager *manager, const char **res, jack_port_id_t port_index)
Get the connection port name array.
void GetPortsAux (const char **matching_ports, const char *port_name_pattern, const char *type_name_pattern, unsigned long flags)
void RecalculateLatencyAux (jack_port_id_t port_index, jack_latency_callback_mode_t mode)
Private Attributes
JackClientTiming fClientTiming [CLIENT_NUM]
JackPort fPortArray [0]
unsigned int fPortMax
Additional Inherited Members
Protected Member Functions inherited from Jack::JackShmMem
JackShmMem ()
~JackShmMem ()
Protected Member Functions inherited from Jack::JackAtomicState< JackConnectionManager >
UInt32 WriteNextStateStartAux ()
void WriteNextStateStopAux ()
Protected Attributes inherited from Jack::JackShmMemAble
jack_shm_info_t fInfo
Protected Attributes inherited from Jack::JackAtomicState< JackConnectionManager >
SInt32 fCallWriteCounter
volatile AtomicCounter fCounter
JackConnectionManager fState [2]
Detailed Description
Graph manager: contains the connection manager and the port array.
Definition at line 40 of file JackGraphManager.h.
Constructor & Destructor Documentation
JackGraphManager()
Jack::JackGraphManager::JackGraphManager (int port_max)
Definition at line 66 of file JackGraphManager.cpp.
References fPortArray, fPortMax, i, and PORT_NUM_MAX.
Referenced by Allocate(), Destroy(), and GetBufferAux().
~JackGraphManager()
Jack::JackGraphManager::~JackGraphManager () inline
Definition at line 61 of file JackGraphManager.h.
Referenced by Destroy().
Member Function Documentation
Activate()
void Jack::JackGraphManager::Activate (int refnum)
Definition at line 560 of file JackGraphManager.cpp.
References DirectConnect(), and FREEWHEEL_DRIVER_REFNUM.
Allocate()
JackGraphManager * Jack::JackGraphManager::Allocate (int port_max) static
Definition at line 52 of file JackGraphManager.cpp.
References JackGraphManager().
Referenced by Jack::JackServer::JackServer().
AllocatePort()
jack_port_id_t Jack::JackGraphManager::AllocatePort (int refnum, const char * port_name, const char * port_type, JackPortFlags flags, jack_nframes_t buffer_size)
Definition at line 393 of file JackGraphManager.cpp.
References Jack::JackConnectionManager::AddInputPort(), Jack::JackConnectionManager::AddOutputPort(), AllocatePortAux(), Jack::JackPort::ClearBuffer(), GetPort(), JackPortIsOutput, NO_PORT, Jack::JackPort::Release(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
AllocatePortAux()
jack_port_id_t Jack::JackGraphManager::AllocatePortAux (int refnum, const char * port_name, const char * port_type, JackPortFlags flags) private
Definition at line 373 of file JackGraphManager.cpp.
References Jack::JackPort::Allocate(), FIRST_AVAILABLE_PORT, fPortMax, GetPort(), Jack::JackPort::IsUsed(), jack_log(), and NO_PORT.
Referenced by AllocatePort().
AssertPort()
void Jack::JackGraphManager::AssertPort (jack_port_id_t port_index) private
Definition at line 44 of file JackGraphManager.cpp.
References fPortMax, and jack_log().
Referenced by ComputeTotalLatency(), ComputeTotalLatencyAux(), DisconnectAll(), GetBuffer(), GetInputRefNum(), GetOutputRefNum(), GetPort(), RecalculateLatencyAux(), and RequestMonitor().
CheckPorts()
int Jack::JackGraphManager::CheckPorts (jack_port_id_t port_src, jack_port_id_t port_dst)
Definition at line 713 of file JackGraphManager.cpp.
References Jack::JackPort::fFlags, Jack::JackPort::fName, GetPort(), jack_error, JackPortIsInput, and JackPortIsOutput.
ComputeTotalLatencies()
int Jack::JackGraphManager::ComputeTotalLatencies ()
Definition at line 303 of file JackGraphManager.cpp.
References ComputeTotalLatency(), FIRST_AVAILABLE_PORT, fPortMax, GetPort(), and Jack::JackPort::IsUsed().
ComputeTotalLatency()
int Jack::JackGraphManager::ComputeTotalLatency (jack_port_id_t port_index)
Definition at line 285 of file JackGraphManager.cpp.
References AssertPort(), ComputeTotalLatencyAux(), Jack::JackPort::fTotalLatency, Jack::JackAtomicState< JackConnectionManager >::GetCurrentIndex(), GetPort(), jack_log(), and Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState().
Referenced by ComputeTotalLatencies(), jack_port_get_total_latency(), and jack_recompute_total_latency().
ComputeTotalLatencyAux()
jack_nframes_t Jack::JackGraphManager::ComputeTotalLatencyAux (jack_port_id_t port_index, jack_port_id_t src_port_index, JackConnectionManager * manager, int hop_count) private
Definition at line 261 of file JackGraphManager.cpp.
References AssertPort(), ComputeTotalLatencyAux(), CONNECTION_NUM_FOR_PORT, EMPTY, Jack::JackPort::fFlags, Jack::JackConnectionManager::GetConnections(), Jack::JackPort::GetLatency(), GetPort(), i, JackPortIsTerminal, and Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState().
Referenced by ComputeTotalLatency(), ComputeTotalLatencyAux(), and GetBufferAux().
Connect()
int Jack::JackGraphManager::Connect (jack_port_id_t src_index, jack_port_id_t dst_index)
Definition at line 609 of file JackGraphManager.cpp.
References Jack::JackConnectionManager::Connect(), Jack::JackPort::fInUse, fName, Jack::JackPort::fTypeId, GetPort(), Jack::JackConnectionManager::IncDirectConnection(), Jack::JackConnectionManager::IncFeedbackConnection(), Jack::JackConnectionManager::IsConnected(), Jack::JackConnectionManager::IsLoopPath(), jack_error, jack_log(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
Deactivate()
void Jack::JackGraphManager::Deactivate (int refnum)
Definition at line 572 of file JackGraphManager.cpp.
References DirectDisconnect(), FREEWHEEL_DRIVER_REFNUM, IsDirectConnection(), and jack_log().
Destroy()
void Jack::JackGraphManager::Destroy (JackGraphManager * manager) static
Definition at line 59 of file JackGraphManager.cpp.
References JackGraphManager(), and ~JackGraphManager().
Referenced by Jack::JackServer::~JackServer().
DirectConnect()
void Jack::JackGraphManager::DirectConnect (int ref1, int ref2)
Definition at line 147 of file JackGraphManager.cpp.
References CurIndex, Jack::JackConnectionManager::DirectConnect(), Jack::JackAtomicState< JackConnectionManager >::fCounter, jack_log(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
Referenced by Activate().
DirectDisconnect()
void Jack::JackGraphManager::DirectDisconnect (int ref1, int ref2)
Definition at line 156 of file JackGraphManager.cpp.
References CurIndex, Jack::JackConnectionManager::DirectDisconnect(), Jack::JackAtomicState< JackConnectionManager >::fCounter, jack_log(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
Referenced by Deactivate().
Disconnect()
int Jack::JackGraphManager::Disconnect (jack_port_id_t src_index, jack_port_id_t dst_index)
Definition at line 660 of file JackGraphManager.cpp.
References Jack::JackConnectionManager::DecDirectConnection(), Jack::JackConnectionManager::DecFeedbackConnection(), Jack::JackConnectionManager::Disconnect(), Jack::JackPort::fInUse, fName, GetPort(), Jack::JackConnectionManager::IsConnected(), Jack::JackConnectionManager::IsFeedbackConnection(), jack_error, jack_log(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
Referenced by DisconnectAllInput(), and DisconnectAllOutput().
DisconnectAll()
int Jack::JackGraphManager::DisconnectAll (jack_port_id_t port_index)
Definition at line 537 of file JackGraphManager.cpp.
References AssertPort(), DisconnectAllInput(), DisconnectAllOutput(), Jack::JackPort::fFlags, GetPort(), and JackPortIsOutput.
DisconnectAllInput()
void Jack::JackGraphManager::DisconnectAllInput (jack_port_id_t port_index)
Definition at line 509 of file JackGraphManager.cpp.
References Disconnect(), fPortMax, i, Jack::JackConnectionManager::IsConnected(), jack_log(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
Referenced by DisconnectAll(), DisconnectAllPorts(), and ReleasePort().
DisconnectAllOutput()
void Jack::JackGraphManager::DisconnectAllOutput (jack_port_id_t port_index)
Definition at line 524 of file JackGraphManager.cpp.
References Disconnect(), EMPTY, Jack::JackConnectionManager::GetConnections(), jack_log(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
Referenced by DisconnectAll(), DisconnectAllPorts(), and ReleasePort().
DisconnectAllPorts()
void Jack::JackGraphManager::DisconnectAllPorts (int refnum)
Definition at line 489 of file JackGraphManager.cpp.
References DisconnectAllInput(), DisconnectAllOutput(), EMPTY, Jack::JackConnectionManager::GetInputPorts(), Jack::JackConnectionManager::GetOutputPorts(), i, jack_log(), PORT_NUM_FOR_CLIENT, Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
GetBuffer() [1/2]
jack_default_audio_sample_t * Jack::JackGraphManager::GetBuffer (jack_port_id_t port_index) private
Definition at line 83 of file JackGraphManager.cpp.
References fPortArray.
Referenced by GetBuffer(), and jack_port_get_buffer().
GetBuffer() [2/2]
void * Jack::JackGraphManager::GetBuffer (jack_port_id_t port_index, jack_nframes_t frames)
Definition at line 172 of file JackGraphManager.cpp.
References Jack::AssertBufferSize(), AssertPort(), Jack::JackPort::ClearBuffer(), CONNECTION_NUM_FOR_PORT, Jack::JackConnectionManager::Connections(), EMPTY, Jack::JackPort::fFlags, Jack::JackPort::fTied, GetBuffer(), Jack::JackPort::GetBuffer(), Jack::JackConnectionManager::GetConnections(), Jack::JackConnectionManager::GetPort(), GetPort(), Jack::JackPort::GetRefNum(), i, Jack::JackPort::IsUsed(), jack_log(), JackPortIsOutput, Jack::JackPort::MixBuffers(), NO_PORT, and Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState().
GetBufferAux()
void * Jack::JackGraphManager::GetBufferAux (JackConnectionManager * manager, jack_port_id_t port_index, jack_nframes_t frames) private
References JackGraphManager(), ComputeTotalLatencyAux(), and RecalculateLatencyAux().
GetClientTiming()
JackClientTiming * Jack::JackGraphManager::GetClientTiming (int refnum) inline
Definition at line 129 of file JackGraphManager.h.
References fClientTiming.
Referenced by Jack::JackEngineControl::CalcCPULoad(), and Jack::JackEngineProfiling::Profile().
GetConnections() [1/2]
const char ** Jack::JackGraphManager::GetConnections (jack_port_id_t port_index)
Definition at line 789 of file JackGraphManager.cpp.
References CONNECTION_NUM_FOR_PORT, GetConnectionsAux(), Jack::JackAtomicState< JackConnectionManager >::GetCurrentIndex(), and Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState().
Referenced by jack_port_get_all_connections(), and jack_port_get_connections().
GetConnections() [2/2]
void Jack::JackGraphManager::GetConnections (jack_port_id_t port_index, jack_int_t * connections)
Definition at line 551 of file JackGraphManager.cpp.
References CONNECTION_NUM_FOR_PORT, Jack::JackConnectionManager::GetConnections(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
GetConnectionsAux()
void Jack::JackGraphManager::GetConnectionsAux (JackConnectionManager * manager, const char ** res, jack_port_id_t port_index) private
Get the connection port name array.
Definition at line 765 of file JackGraphManager.cpp.
References CONNECTION_NUM_FOR_PORT, EMPTY, Jack::JackPort::fName, Jack::JackConnectionManager::GetConnections(), GetPort(), and i.
Referenced by GetConnections().
GetConnectionsNum()
int Jack::JackGraphManager::GetConnectionsNum (jack_port_id_t port_index) inline
Definition at line 89 of file JackGraphManager.h.
References Jack::JackConnectionManager::Connections(), and Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState().
Referenced by jack_port_connected().
GetInputPorts()
void Jack::JackGraphManager::GetInputPorts (int refnum, jack_int_t * res)
Definition at line 440 of file JackGraphManager.cpp.
References Jack::JackConnectionManager::GetInputPorts(), PORT_NUM_FOR_CLIENT, Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
GetInputRefNum()
int Jack::JackGraphManager::GetInputRefNum (jack_port_id_t port_index)
Definition at line 590 of file JackGraphManager.cpp.
References AssertPort(), Jack::JackConnectionManager::GetInputRefNum(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
GetOutputPorts()
void Jack::JackGraphManager::GetOutputPorts (int refnum, jack_int_t * res)
Definition at line 448 of file JackGraphManager.cpp.
References Jack::JackConnectionManager::GetOutputPorts(), PORT_NUM_FOR_CLIENT, Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
GetOutputRefNum()
int Jack::JackGraphManager::GetOutputRefNum (jack_port_id_t port_index)
Definition at line 600 of file JackGraphManager.cpp.
References AssertPort(), Jack::JackConnectionManager::GetOutputRefNum(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
GetPort() [1/2]
jack_port_id_t Jack::JackGraphManager::GetPort (const char * name)
Definition at line 749 of file JackGraphManager.cpp.
References fPortMax, GetPort(), i, Jack::JackPort::IsUsed(), Jack::JackPort::NameEquals(), and NO_PORT.
GetPort() [2/2]
JackPort * Jack::JackGraphManager::GetPort (jack_port_id_t index)
Definition at line 77 of file JackGraphManager.cpp.
References AssertPort(), and fPortArray.
Referenced by AllocatePort(), AllocatePortAux(), CheckPorts(), ComputeTotalLatencies(), ComputeTotalLatency(), ComputeTotalLatencyAux(), Connect(), Disconnect(), DisconnectAll(), GetBuffer(), GetConnectionsAux(), GetPort(), GetPortsAux(), GetTwoPorts(), Jack::JackClient::HandleLatencyCallback(), jack_port_by_name(), jack_port_connected_to(), jack_port_ensure_monitor(), jack_port_flags(), jack_port_get_aliases(), jack_port_get_latency(), jack_port_get_latency_range(), jack_port_get_total_latency(), jack_port_monitoring_input(), jack_port_name(), jack_port_request_monitor_by_name(), jack_port_set_alias(), jack_port_set_latency(), jack_port_set_latency_range(), jack_port_short_name(), jack_port_tie(), jack_port_type(), jack_port_type_id(), jack_port_unset_alias(), jack_port_untie(), Jack::JackClient::PortIsMine(), RecalculateLatencyAux(), ReleasePort(), RequestMonitor(), and SetBufferSize().
GetPorts()
const char ** Jack::JackGraphManager::GetPorts (const char * port_name_pattern, const char * type_name_pattern, unsigned long flags)
Definition at line 878 of file JackGraphManager.cpp.
References fPortMax, Jack::JackAtomicState< JackConnectionManager >::GetCurrentIndex(), and GetPortsAux().
Referenced by jack_get_ports().
GetPortsAux()
void Jack::JackGraphManager::GetPortsAux (const char ** matching_ports, const char * port_name_pattern, const char * type_name_pattern, unsigned long flags) private
Definition at line 812 of file JackGraphManager.cpp.
References Jack::JackPort::fFlags, Jack::JackPort::fName, fPortMax, Jack::JackPort::GetName(), GetPort(), Jack::JackPort::GetType(), i, Jack::JackPort::IsUsed(), and jack_log().
Referenced by GetPorts().
GetTwoPorts()
int Jack::JackGraphManager::GetTwoPorts (const char * src, const char * dst, jack_port_id_t * src_index, jack_port_id_t * dst_index)
Definition at line 731 of file JackGraphManager.cpp.
References GetPort(), jack_error, jack_log(), and NO_PORT.
InitRefNum()
void Jack::JackGraphManager::InitRefNum (int refnum)
Definition at line 89 of file JackGraphManager.cpp.
References Jack::JackConnectionManager::InitRefNum(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
IsConnected()
int Jack::JackGraphManager::IsConnected (jack_port_id_t port_src, jack_port_id_t port_dst)
Definition at line 706 of file JackGraphManager.cpp.
References Jack::JackConnectionManager::IsConnected(), and Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState().
Referenced by jack_port_connected_to().
IsDirectConnection()
bool Jack::JackGraphManager::IsDirectConnection (int ref1, int ref2)
Definition at line 165 of file JackGraphManager.cpp.
References Jack::JackConnectionManager::IsDirectConnection(), and Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState().
Referenced by Deactivate().
IsFinishedGraph()
bool Jack::JackGraphManager::IsFinishedGraph ()
Definition at line 113 of file JackGraphManager.cpp.
References FREEWHEEL_DRIVER_REFNUM, Jack::JackConnectionManager::GetActivation(), and Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState().
RecalculateLatency()
void Jack::JackGraphManager::RecalculateLatency (jack_port_id_t port_index, jack_latency_callback_mode_t mode)
Definition at line 344 of file JackGraphManager.cpp.
References Jack::JackAtomicState< JackConnectionManager >::GetCurrentIndex(), and RecalculateLatencyAux().
Referenced by Jack::JackClient::HandleLatencyCallback().
RecalculateLatencyAux()
void Jack::JackGraphManager::RecalculateLatencyAux (jack_port_id_t port_index, jack_latency_callback_mode_t mode) private
Definition at line 315 of file JackGraphManager.cpp.
References AssertPort(), CONNECTION_NUM_FOR_PORT, EMPTY, Jack::JackConnectionManager::GetConnections(), Jack::JackPort::GetLatencyRange(), GetPort(), i, _jack_latency_range::max, _jack_latency_range::min, Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState(), Jack::JackPort::SetLatencyRange(), and UINT32_MAX.
Referenced by GetBufferAux(), and RecalculateLatency().
ReleasePort()
int Jack::JackGraphManager::ReleasePort (int refnum, jack_port_id_t port_index)
Definition at line 421 of file JackGraphManager.cpp.
References DisconnectAllInput(), DisconnectAllOutput(), Jack::JackPort::fFlags, GetPort(), JackPortIsOutput, Jack::JackPort::Release(), Jack::JackConnectionManager::RemoveInputPort(), Jack::JackConnectionManager::RemoveOutputPort(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
Referenced by RemoveAllPorts().
RemoveAllPorts()
void Jack::JackGraphManager::RemoveAllPorts (int refnum)
Definition at line 457 of file JackGraphManager.cpp.
References EMPTY, Jack::JackConnectionManager::GetInputPorts(), Jack::JackConnectionManager::GetOutputPorts(), jack_error, jack_log(), ReleasePort(), Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
RequestMonitor()
int Jack::JackGraphManager::RequestMonitor (jack_port_id_t port_index, bool onoff)
jackd.h If JackPortCanMonitor is set for this port, turn input monitoring on or off. Otherwise, do nothing.
if (!(fFlags & JackPortCanMonitor)) return -1;
Definition at line 232 of file JackGraphManager.cpp.
References AssertPort(), CONNECTION_NUM_FOR_PORT, EMPTY, Jack::JackPort::fFlags, Jack::JackConnectionManager::GetConnections(), GetPort(), i, JackPortIsOutput, Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState(), RequestMonitor(), and Jack::JackPort::RequestMonitor().
Referenced by jack_port_request_monitor(), jack_port_request_monitor_by_name(), and RequestMonitor().
Restore()
void Jack::JackGraphManager::Restore (JackConnectionManager * src)
Definition at line 909 of file JackGraphManager.cpp.
References Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
ResumeRefNum()
int Jack::JackGraphManager::ResumeRefNum (JackClientControl * control, JackSynchro * table)
Definition at line 120 of file JackGraphManager.cpp.
References fClientTiming, Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState(), and Jack::JackConnectionManager::ResumeRefNum().
RunCurrentGraph()
void Jack::JackGraphManager::RunCurrentGraph ()
Definition at line 97 of file JackGraphManager.cpp.
References fClientTiming, Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState(), and Jack::JackConnectionManager::ResetGraph().
RunNextGraph()
bool Jack::JackGraphManager::RunNextGraph ()
Definition at line 104 of file JackGraphManager.cpp.
References fClientTiming, Jack::JackConnectionManager::ResetGraph(), and Jack::JackAtomicState< JackConnectionManager >::TrySwitchState().
Save()
void Jack::JackGraphManager::Save (JackConnectionManager * dst)
Definition at line 901 of file JackGraphManager.cpp.
References Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStart(), and Jack::JackAtomicState< JackConnectionManager >::WriteNextStateStop().
SetBufferSize()
void Jack::JackGraphManager::SetBufferSize (jack_nframes_t buffer_size)
Definition at line 359 of file JackGraphManager.cpp.
References Jack::JackPort::ClearBuffer(), FIRST_AVAILABLE_PORT, fPortMax, GetPort(), Jack::JackPort::IsUsed(), and jack_log().
SuspendRefNum()
int Jack::JackGraphManager::SuspendRefNum (JackClientControl * control, JackSynchro * table, long usecs)
Definition at line 127 of file JackGraphManager.cpp.
References fClientTiming, Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState(), and Jack::JackConnectionManager::SuspendRefNum().
TopologicalSort()
void Jack::JackGraphManager::TopologicalSort (std::vector< jack_int_t > & sorted)
Definition at line 133 of file JackGraphManager.cpp.
References Jack::JackAtomicState< JackConnectionManager >::GetCurrentIndex(), Jack::JackAtomicState< JackConnectionManager >::ReadCurrentState(), and Jack::JackConnectionManager::TopologicalSort().
Member Data Documentation
fClientTiming
JackClientTiming Jack::JackGraphManager::fClientTiming[CLIENT_NUM] private
Definition at line 46 of file JackGraphManager.h.
Referenced by GetClientTiming(), ResumeRefNum(), RunCurrentGraph(), RunNextGraph(), and SuspendRefNum().
fPortArray
JackPort Jack::JackGraphManager::fPortArray[0] private
Definition at line 47 of file JackGraphManager.h.
Referenced by JackGraphManager(), GetBuffer(), and GetPort().
fPortMax
unsigned int Jack::JackGraphManager::fPortMax private
Definition at line 45 of file JackGraphManager.h.
Referenced by JackGraphManager(), AllocatePortAux(), AssertPort(), ComputeTotalLatencies(), DisconnectAllInput(), GetPort(), GetPorts(), GetPortsAux(), and SetBufferSize().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackGraphManager.h
src/3rdparty/jack2/common/JackGraphManager.cpp