LMMS: lmms::Downsampler< MaxStages, MaxCoefs > Class Template Reference
lmms::Downsampler< MaxStages, MaxCoefs > Class Template Reference
#include <OversamplingHelpers.h>
Public Member Functions
float getPassband () const
float getSampleRate () const
int getStages () const
float processSample (float *inSamples)
void reset ()
void setPassband (float passband)
void setSampleRate (float sampleRate)
void setStages (int stages)
void setup (int stages, float sampleRate, float passband=HIIR_DEFAULT_PASSBAND)
Private Attributes
hiir::Downsampler2xFpu< s_firstCoefCount > m_downsampleFirst
std::array< hiir::Downsampler2xFpu< s_restCoefCount >, MaxStages - 2 > m_downsampleRest
hiir::Downsampler2xFpu< s_secondCoefCount > m_downsampleSecond
float m_passband = HIIR_DEFAULT_PASSBAND
float m_sampleRate = 44100
int m_stages = 0
Static Private Attributes
static constexpr int s_firstCoefCount = MaxCoefs
static constexpr int s_restCoefCount = std::max(MaxCoefs / 4, 2)
static constexpr int s_secondCoefCount = std::max(MaxCoefs / 2, 2)
Detailed Description
template<int MaxStages, int MaxCoefs = 8>
class lmms::Downsampler< MaxStages, MaxCoefs >
Definition at line 150 of file OversamplingHelpers.h.
Member Function Documentation
getPassband()
template<int MaxStages, int MaxCoefs = 8> float lmms::Downsampler< MaxStages, MaxCoefs >::getPassband () const inline
Definition at line 220 of file OversamplingHelpers.h.
References m_passband.
getSampleRate()
template<int MaxStages, int MaxCoefs = 8> float lmms::Downsampler< MaxStages, MaxCoefs >::getSampleRate () const inline
Definition at line 219 of file OversamplingHelpers.h.
References m_sampleRate.
getStages()
template<int MaxStages, int MaxCoefs = 8> int lmms::Downsampler< MaxStages, MaxCoefs >::getStages () const inline
Definition at line 218 of file OversamplingHelpers.h.
References m_stages.
processSample()
template<int MaxStages, int MaxCoefs = 8> float lmms::Downsampler< MaxStages, MaxCoefs >::processSample (float * inSamples) inline
Definition at line 192 of file OversamplingHelpers.h.
References i, j, m_downsampleFirst, m_downsampleRest, m_downsampleSecond, and m_stages.
reset()
template<int MaxStages, int MaxCoefs = 8> void lmms::Downsampler< MaxStages, MaxCoefs >::reset () inline
Definition at line 153 of file OversamplingHelpers.h.
References hiir::PolyphaseIir2Designer::compute_coefs_spec_order_tbw(), i, m_downsampleFirst, m_downsampleRest, m_downsampleSecond, m_passband, m_sampleRate, m_stages, s_firstCoefCount, s_restCoefCount, and s_secondCoefCount.
Referenced by setPassband(), setSampleRate(), setStages(), and setup().
setPassband()
template<int MaxStages, int MaxCoefs = 8> void lmms::Downsampler< MaxStages, MaxCoefs >::setPassband (float passband) inline
Definition at line 224 of file OversamplingHelpers.h.
References m_passband, and reset().
setSampleRate()
template<int MaxStages, int MaxCoefs = 8> void lmms::Downsampler< MaxStages, MaxCoefs >::setSampleRate (float sampleRate) inline
Definition at line 223 of file OversamplingHelpers.h.
References m_sampleRate, and reset().
setStages()
template<int MaxStages, int MaxCoefs = 8> void lmms::Downsampler< MaxStages, MaxCoefs >::setStages (int stages) inline
Definition at line 222 of file OversamplingHelpers.h.
References m_stages, and reset().
setup()
template<int MaxStages, int MaxCoefs = 8> void lmms::Downsampler< MaxStages, MaxCoefs >::setup (int stages, float sampleRate, float passband = HIIR_DEFAULT_PASSBAND) inline
Definition at line 182 of file OversamplingHelpers.h.
References HIIR_DEFAULT_PASSBAND, m_passband, m_sampleRate, m_stages, and reset().
Member Data Documentation
m_downsampleFirst
template<int MaxStages, int MaxCoefs = 8> hiir::Downsampler2xFpu<s_firstCoefCount> lmms::Downsampler< MaxStages, MaxCoefs >::m_downsampleFirst private
Definition at line 235 of file OversamplingHelpers.h.
Referenced by processSample(), and reset().
m_downsampleRest
template<int MaxStages, int MaxCoefs = 8> std::array<hiir::Downsampler2xFpu<s_restCoefCount>, MaxStages - 2> lmms::Downsampler< MaxStages, MaxCoefs >::m_downsampleRest private
Definition at line 237 of file OversamplingHelpers.h.
Referenced by processSample(), and reset().
m_downsampleSecond
template<int MaxStages, int MaxCoefs = 8> hiir::Downsampler2xFpu<s_secondCoefCount> lmms::Downsampler< MaxStages, MaxCoefs >::m_downsampleSecond private
Definition at line 236 of file OversamplingHelpers.h.
Referenced by processSample(), and reset().
m_passband
template<int MaxStages, int MaxCoefs = 8> float lmms::Downsampler< MaxStages, MaxCoefs >::m_passband = HIIR_DEFAULT_PASSBAND private
Definition at line 242 of file OversamplingHelpers.h.
Referenced by getPassband(), reset(), setPassband(), and setup().
m_sampleRate
template<int MaxStages, int MaxCoefs = 8> float lmms::Downsampler< MaxStages, MaxCoefs >::m_sampleRate = 44100 private
Definition at line 241 of file OversamplingHelpers.h.
Referenced by getSampleRate(), reset(), setSampleRate(), and setup().
m_stages
template<int MaxStages, int MaxCoefs = 8> int lmms::Downsampler< MaxStages, MaxCoefs >::m_stages = 0 private
Definition at line 240 of file OversamplingHelpers.h.
Referenced by getStages(), processSample(), reset(), setStages(), and setup().
s_firstCoefCount
template<int MaxStages, int MaxCoefs = 8> int lmms::Downsampler< MaxStages, MaxCoefs >::s_firstCoefCount = MaxCoefs static constexpr private
Definition at line 227 of file OversamplingHelpers.h.
Referenced by reset().
s_restCoefCount
template<int MaxStages, int MaxCoefs = 8> int lmms::Downsampler< MaxStages, MaxCoefs >::s_restCoefCount = std::max(MaxCoefs / 4, 2) static constexpr private
Definition at line 229 of file OversamplingHelpers.h.
Referenced by reset().
s_secondCoefCount
template<int MaxStages, int MaxCoefs = 8> int lmms::Downsampler< MaxStages, MaxCoefs >::s_secondCoefCount = std::max(MaxCoefs / 2, 2) static constexpr private
Definition at line 228 of file OversamplingHelpers.h.
Referenced by reset().
The documentation for this class was generated from the following file:
include/OversamplingHelpers.h