LMMS: lmms::MidiController Class Reference
lmms::MidiController Class Reference
#include <MidiController.h>
Public Slots
gui::ControllerDialog * createDialog (QWidget *_parent) override
void updateName ()
Public Slots inherited from lmms::Controller
virtual gui::ControllerDialog * createDialog (QWidget *_parent)
virtual void setName (const QString &_new_name)
Public Member Functions
MidiController (Model *_parent)
~MidiController () override=default
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
void processInEvent (const MidiEvent &_me, const TimePos &_time, f_cnt_t offset=0) override
void processOutEvent (const MidiEvent &_me, const TimePos &_time, f_cnt_t offset=0) override
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
void subscribeReadablePorts (const MidiPort::Map &_map)
Public Member Functions inherited from lmms::Controller
Controller (ControllerType _type, Model *_parent, const QString &_display_name)
~Controller () override
void addConnection (ControllerConnection *)
int connectionCount () const
virtual float currentValue (int _offset)
bool frequentUpdates () const
bool hasModel (const Model *m) const
bool isSampleExact () const
virtual const QString & name () const
void removeConnection (ControllerConnection *)
void setSampleExact (bool _exact)
ControllerType type () const
virtual ValueBuffer * valueBuffer ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Public Member Functions inherited from lmms::MidiEventProcessor
MidiEventProcessor ()=default
virtual ~MidiEventProcessor ()=default
Static Public Attributes
static constexpr int NONE = -1
Protected Member Functions
void updateValueBuffer () override
Protected Member Functions inherited from lmms::Controller
virtual float value (int _offset)
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Attributes
float m_lastValue
MidiPort m_midiPort
float m_previousValue
Protected Attributes inherited from lmms::Controller
long m_bufferLastUpdated
int m_connectionCount
float m_currentValue
QString m_name
bool m_sampleExact
ControllerType m_type
ValueBuffer m_valueBuffer
Friends
class AutoDetectMidiController
class gui::ControllerConnectionDialog
Additional Inherited Members
Public Types inherited from lmms::Controller
enum class ControllerType {
Dummy ,
Lfo ,
Midi ,
Peak
}
Signals inherited from lmms::Controller
void valueChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Public Member Functions inherited from lmms::Controller
static Controller * create (const QDomElement &_this, Model *_parent)
static Controller * create (ControllerType _tt, Model *_parent)
static float fittedValue (float _val)
static void resetFrameCounter ()
static unsigned int runningFrames ()
static long runningPeriods ()
static float runningTime ()
static void triggerFrameCounter ()
Static Protected Attributes inherited from lmms::Controller
static ControllerVector s_controllers
static long s_periods = 0
Detailed Description
Definition at line 47 of file MidiController.h.
Constructor & Destructor Documentation
MidiController()
lmms::MidiController::MidiController (Model * _parent)
Definition at line 34 of file MidiController.cpp.
References lmms::Controller::Controller(), lmms::MidiEventProcessor::MidiEventProcessor(), m_lastValue, m_midiPort, m_previousValue, lmms::Controller::setSampleExact(), and updateName().
Referenced by lmms::AutoDetectMidiController::AutoDetectMidiController(), and lmms::AutoDetectMidiController::copyToMidiController().
~MidiController()
lmms::MidiController::~MidiController () override default
Member Function Documentation
createDialog
gui::ControllerDialog * lmms::MidiController::createDialog (QWidget * _parent) override slot
Definition at line 143 of file MidiController.cpp.
loadSettings()
void lmms::MidiController::loadSettings (const QDomElement & _this) override virtual
Reimplemented from lmms::Controller.
Definition at line 123 of file MidiController.cpp.
References lmms::Controller::loadSettings(), m_midiPort, and updateName().
nodeName()
QString lmms::MidiController::nodeName () const override virtual
Reimplemented from lmms::Controller.
Definition at line 135 of file MidiController.cpp.
processInEvent()
void lmms::MidiController::processInEvent (const MidiEvent & _me, const TimePos & _time, f_cnt_t offset = 0) override virtual
Implements lmms::MidiEventProcessor.
Definition at line 74 of file MidiController.cpp.
References lmms::MidiEvent::channel(), m_lastValue, m_midiPort, m_previousValue, lmms::MidiControlChange, lmms::MidiEvent::type(), and lmms::Controller::valueChanged().
processOutEvent()
void lmms::MidiController::processOutEvent (const MidiEvent & _me, const TimePos & _time, f_cnt_t offset = 0) inline override virtual
Implements lmms::MidiEventProcessor.
Definition at line 58 of file MidiController.h.
saveSettings()
void lmms::MidiController::saveSettings (QDomDocument & _doc, QDomElement & _this) override virtual
Reimplemented from lmms::Controller.
Definition at line 113 of file MidiController.cpp.
References m_midiPort, and lmms::Controller::saveSettings().
subscribeReadablePorts()
void lmms::MidiController::subscribeReadablePorts (const MidiPort::Map & _map)
Definition at line 101 of file MidiController.cpp.
References m_midiPort.
updateName
void lmms::MidiController::updateName () slot
Definition at line 64 of file MidiController.cpp.
References m_midiPort, and lmms::Controller::setName().
Referenced by lmms::AutoDetectMidiController::AutoDetectMidiController(), MidiController(), and loadSettings().
updateValueBuffer()
void lmms::MidiController::updateValueBuffer () override protected virtual
Reimplemented from lmms::Controller.
Definition at line 49 of file MidiController.cpp.
References lmms::Controller::m_bufferLastUpdated, m_lastValue, m_previousValue, lmms::Controller::m_valueBuffer, and lmms::Controller::s_periods.
Friends And Related Symbol Documentation
AutoDetectMidiController
friend class AutoDetectMidiController friend
Definition at line 89 of file MidiController.h.
References AutoDetectMidiController.
Referenced by AutoDetectMidiController.
gui::ControllerConnectionDialog
friend class gui::ControllerConnectionDialog friend
Definition at line 88 of file MidiController.h.
Member Data Documentation
m_lastValue
float lmms::MidiController::m_lastValue protected
Definition at line 85 of file MidiController.h.
Referenced by MidiController(), processInEvent(), and updateValueBuffer().
m_midiPort
MidiPort lmms::MidiController::m_midiPort protected
Definition at line 82 of file MidiController.h.
Referenced by lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog(), MidiController(), lmms::AutoDetectMidiController::copyToMidiController(), loadSettings(), lmms::AutoDetectMidiController::processInEvent(), processInEvent(), lmms::AutoDetectMidiController::reset(), saveSettings(), subscribeReadablePorts(), updateName(), and lmms::AutoDetectMidiController::useDetected().
m_previousValue
float lmms::MidiController::m_previousValue protected
Definition at line 86 of file MidiController.h.
Referenced by MidiController(), processInEvent(), and updateValueBuffer().
NONE
int lmms::MidiController::NONE = -1 static constexpr
Definition at line 51 of file MidiController.h.
Referenced by lmms::AutoDetectMidiController::AutoDetectMidiController(), and lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog().
The documentation for this class was generated from the following files:
include/MidiController.h
src/core/midi/MidiController.cpp