LMMS: lmms::RemotePluginBase Class Reference
lmms::RemotePluginBase Class Reference abstract
#include <RemotePluginBase.h>
Classes
struct message
Public Member Functions
RemotePluginBase (shmFifo *_in, shmFifo *_out)
virtual ~RemotePluginBase ()
void fetchAndProcessAllMessages ()
message fetchAndProcessNextMessage ()
bool isInvalid () const
bool messagesLeft ()
virtual bool processMessage (const message &_m)=0
message receiveMessage ()
void reset (shmFifo *in, shmFifo *out)
int sendMessage (const message &_m)
message waitForMessage (const message &_m, bool _busy_waiting=false)
Static Public Member Functions
static bool isMainThreadWaiting ()
Protected Member Functions
const shmFifo * in () const
void invalidate ()
const shmFifo * out () const
Static Private Member Functions
static int & waitDepthCounter ()
Private Attributes
shmFifo * m_in
shmFifo * m_out
Detailed Description
Definition at line 354 of file RemotePluginBase.h.
Constructor & Destructor Documentation
RemotePluginBase()
lmms::RemotePluginBase::RemotePluginBase (shmFifo * _in, shmFifo * _out)
Definition at line 38 of file RemotePluginBase.cpp.
References RemotePluginBase(), m_in, and m_out.
Referenced by lmms::RemotePlugin::RemotePlugin(), RemotePluginBase(), and lmms::RemotePluginClient::RemotePluginClient().
~RemotePluginBase()
lmms::RemotePluginBase::~RemotePluginBase () virtual
Definition at line 61 of file RemotePluginBase.cpp.
References m_in, and m_out.
Member Function Documentation
fetchAndProcessAllMessages()
void lmms::RemotePluginBase::fetchAndProcessAllMessages () inline
Definition at line 525 of file RemotePluginBase.h.
References fetchAndProcessNextMessage(), and messagesLeft().
Referenced by lmms::RemotePlugin::process().
fetchAndProcessNextMessage()
message lmms::RemotePluginBase::fetchAndProcessNextMessage () inline
Definition at line 463 of file RemotePluginBase.h.
References processMessage(), and receiveMessage().
Referenced by fetchAndProcessAllMessages().
in()
const shmFifo * lmms::RemotePluginBase::in () const inline protected
Definition at line 544 of file RemotePluginBase.h.
References m_in.
Referenced by lmms::RemotePlugin::init(), and reset().
invalidate()
void lmms::RemotePluginBase::invalidate () inline protected
Definition at line 555 of file RemotePluginBase.h.
References m_in, and m_out.
Referenced by lmms::RemotePlugin::init(), and lmms::RemotePlugin::processFinished().
isInvalid()
bool lmms::RemotePluginBase::isInvalid () const inline
Definition at line 451 of file RemotePluginBase.h.
References m_in, and m_out.
Referenced by waitForMessage().
isMainThreadWaiting()
bool lmms::RemotePluginBase::isMainThreadWaiting () inline static
Definition at line 533 of file RemotePluginBase.h.
References waitDepthCounter().
Referenced by lmms::gui::MainWindow::autoSave().
messagesLeft()
bool lmms::RemotePluginBase::messagesLeft () inline
Definition at line 508 of file RemotePluginBase.h.
References m_in.
Referenced by fetchAndProcessAllMessages(), and waitForMessage().
out()
const shmFifo * lmms::RemotePluginBase::out () const inline protected
Definition at line 549 of file RemotePluginBase.h.
References m_out.
Referenced by lmms::RemotePlugin::init(), and reset().
processMessage()
virtual bool lmms::RemotePluginBase::processMessage (const message & _m) pure virtual
Implemented in lmms::RemotePlugin, and lmms::RemotePluginClient.
Referenced by fetchAndProcessNextMessage(), and waitForMessage().
receiveMessage()
RemotePluginBase::message lmms::RemotePluginBase::receiveMessage ()
Definition at line 108 of file RemotePluginBase.cpp.
References lmms::RemotePluginBase::message::data, i, lmms::RemotePluginBase::message::id, and m_in.
Referenced by fetchAndProcessNextMessage(), and waitForMessage().
reset()
void lmms::RemotePluginBase::reset (shmFifo * in, shmFifo * out) inline
Definition at line 439 of file RemotePluginBase.h.
References in(), m_in, m_out, and out().
Referenced by lmms::RemotePlugin::init().
sendMessage()
int lmms::RemotePluginBase::sendMessage (const message & _m)
Definition at line 75 of file RemotePluginBase.cpp.
References lmms::RemotePluginBase::message::data, i, lmms::RemotePluginBase::message::id, j, and m_out.
Referenced by lmms::RemotePlugin::~RemotePlugin(), lmms::RemotePluginClient::~RemotePluginClient(), lmms::RemotePluginClient::debugMessage(), lmms::RemotePlugin::hideUI(), lmms::RemotePlugin::init(), lmms::RemotePlugin::isUIVisible(), lmms::RemotePlugin::process(), lmms::RemotePlugin::processMessage(), lmms::RemotePluginClient::processMessage(), lmms::RemotePlugin::processMidiEvent(), lmms::RemotePlugin::resizeSharedProcessingMemory(), lmms::RemotePluginClient::setInputCount(), lmms::RemotePluginClient::setInputOutputCount(), lmms::RemotePluginClient::setOutputCount(), lmms::RemotePlugin::showUI(), lmms::RemotePlugin::toggleUI(), and lmms::RemotePlugin::updateSampleRate().
waitDepthCounter()
int & lmms::RemotePluginBase::waitDepthCounter () inline static private
Definition at line 574 of file RemotePluginBase.h.
Referenced by isMainThreadWaiting(), and waitForMessage().
waitForMessage()
RemotePluginBase::message lmms::RemotePluginBase::waitForMessage (const message & _m, bool _busy_waiting = false)
Definition at line 138 of file RemotePluginBase.cpp.
References lmms::RemotePluginBase::message::id, lmms::IdUndefined, isInvalid(), messagesLeft(), processMessage(), receiveMessage(), and waitDepthCounter().
Referenced by lmms::RemotePlugin::isUIVisible(), lmms::RemotePlugin::process(), lmms::RemotePlugin::updateSampleRate(), lmms::RemotePlugin::waitForHostInfoGotten(), and lmms::RemotePlugin::waitForInitDone().
Member Data Documentation
m_in
shmFifo* lmms::RemotePluginBase::m_in private
Definition at line 582 of file RemotePluginBase.h.
Referenced by RemotePluginBase(), ~RemotePluginBase(), in(), invalidate(), isInvalid(), messagesLeft(), receiveMessage(), and reset().
m_out
shmFifo* lmms::RemotePluginBase::m_out private
Definition at line 583 of file RemotePluginBase.h.
Referenced by RemotePluginBase(), ~RemotePluginBase(), invalidate(), isInvalid(), out(), reset(), and sendMessage().
The documentation for this class was generated from the following files:
include/RemotePluginBase.h
src/common/RemotePluginBase.cpp