LMMS: lmms::EnvelopeAndLfoParameters::LfoInstances Class Reference
lmms::EnvelopeAndLfoParameters::LfoInstances Class Reference
#include <EnvelopeAndLfoParameters.h>
Public Member Functions
LfoInstances ()=default
~LfoInstances ()=default
void add (EnvelopeAndLfoParameters *lfo)
bool isEmpty () const
void remove (EnvelopeAndLfoParameters *lfo)
void reset ()
void trigger ()
Private Types
using LfoList = QList<EnvelopeAndLfoParameters*>
Private Attributes
QMutex m_lfoListMutex
LfoList m_lfos
Detailed Description
Definition at line 50 of file EnvelopeAndLfoParameters.h.
Member Typedef Documentation
LfoList
using lmms::EnvelopeAndLfoParameters::LfoInstances::LfoList = QList<EnvelopeAndLfoParameters*> private
Definition at line 70 of file EnvelopeAndLfoParameters.h.
Constructor & Destructor Documentation
LfoInstances()
lmms::EnvelopeAndLfoParameters::LfoInstances::LfoInstances () default
~LfoInstances()
lmms::EnvelopeAndLfoParameters::LfoInstances::~LfoInstances () default
Member Function Documentation
add()
void lmms::EnvelopeAndLfoParameters::LfoInstances::add (EnvelopeAndLfoParameters * lfo)
Definition at line 77 of file EnvelopeAndLfoParameters.cpp.
References lmms::EnvelopeAndLfoParameters::EnvelopeAndLfoParameters(), m_lfoListMutex, and m_lfos.
Referenced by lmms::EnvelopeAndLfoParameters::EnvelopeAndLfoParameters().
isEmpty()
bool lmms::EnvelopeAndLfoParameters::LfoInstances::isEmpty () const inline
Definition at line 57 of file EnvelopeAndLfoParameters.h.
References m_lfos.
remove()
void lmms::EnvelopeAndLfoParameters::LfoInstances::remove (EnvelopeAndLfoParameters * lfo)
Definition at line 86 of file EnvelopeAndLfoParameters.cpp.
References lmms::EnvelopeAndLfoParameters::EnvelopeAndLfoParameters(), m_lfoListMutex, and m_lfos.
Referenced by lmms::EnvelopeAndLfoParameters::~EnvelopeAndLfoParameters().
reset()
void lmms::EnvelopeAndLfoParameters::LfoInstances::reset ()
Definition at line 64 of file EnvelopeAndLfoParameters.cpp.
References m_lfoListMutex, and m_lfos.
Referenced by lmms::Song::processNextBuffer().
trigger()
void lmms::EnvelopeAndLfoParameters::LfoInstances::trigger ()
Definition at line 51 of file EnvelopeAndLfoParameters.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), m_lfoListMutex, and m_lfos.
Referenced by lmms::AudioEngine::renderStageMix().
Member Data Documentation
m_lfoListMutex
QMutex lmms::EnvelopeAndLfoParameters::LfoInstances::m_lfoListMutex private
Definition at line 69 of file EnvelopeAndLfoParameters.h.
Referenced by add(), remove(), reset(), and trigger().
m_lfos
LfoList lmms::EnvelopeAndLfoParameters::LfoInstances::m_lfos private
Definition at line 71 of file EnvelopeAndLfoParameters.h.
Referenced by add(), isEmpty(), remove(), reset(), and trigger().
The documentation for this class was generated from the following files:
include/EnvelopeAndLfoParameters.h
src/core/EnvelopeAndLfoParameters.cpp