LMMS: lmms::Sample Class Reference
lmms::Sample Class Reference
#include <Sample.h>
Classes
class PlaybackState
Public Types
enum class Loop {
Off ,
On ,
PingPong
}
Public Member Functions
Sample ()=default
Sample (const QByteArray &base64, int sampleRate=Engine::audioEngine() ->outputSampleRate())
Sample (const QString &audioFile)
Sample (const Sample &other)
Sample (const SampleFrame *data, size_t numFrames, int sampleRate=Engine::audioEngine() ->outputSampleRate())
Sample (Sample &&other) noexcept
Sample (std::shared_ptr< const SampleBuffer > buffer)
auto amplification () const -> float
auto buffer () const -> std::shared_ptr< const SampleBuffer >
auto data () const -> const SampleFrame *
auto endFrame () const -> int
auto frequency () const -> float
auto loopEndFrame () const -> int
auto loopStartFrame () const -> int
auto operator= (const Sample &) -> Sample &
auto operator= (Sample &&) noexcept -> Sample &
auto play (SampleFrame *dst, PlaybackState *state, size_t numFrames, Loop loopMode=Loop::Off, double ratio=1.0) const -> bool
auto reversed () const -> bool
auto sampleDuration () const -> std::chrono::milliseconds
auto sampleFile () const -> const QString &
auto sampleRate () const -> int
auto sampleSize () const -> size_t
void setAllPointFrames (int startFrame, int endFrame, int loopStartFrame, int loopEndFrame)
void setAmplification (float amplification)
void setEndFrame (int endFrame)
void setFrequency (float frequency)
void setLoopEndFrame (int loopEndFrame)
void setLoopStartFrame (int loopStartFrame)
void setReversed (bool reversed)
void setStartFrame (int startFrame)
auto startFrame () const -> int
auto toBase64 () const -> QString
Private Member Functions
f_cnt_t render (SampleFrame *dst, f_cnt_t size, PlaybackState *state, Loop loop) const
Private Attributes
std::atomic< float > m_amplification = 1.0f
std::shared_ptr< const SampleBuffer > m_buffer = SampleBuffer::emptyBuffer()
std::atomic< int > m_endFrame = 0
std::atomic< float > m_frequency = DefaultBaseFreq
std::atomic< int > m_loopEndFrame = 0
std::atomic< int > m_loopStartFrame = 0
std::atomic< bool > m_reversed = false
std::atomic< int > m_startFrame = 0
Detailed Description
Definition at line 36 of file Sample.h.
Member Enumeration Documentation
Loop
enum class lmms::Sample::Loop strong
Enumerator
Off
On
PingPong
Definition at line 39 of file Sample.h.
Constructor & Destructor Documentation
Sample() [1/7]
lmms::Sample::Sample () default
References Sample(), lmms::Engine::audioEngine(), buffer(), data(), operator=(), play(), sampleDuration(), and sampleRate().
Referenced by Sample(), Sample(), Sample(), operator=(), and operator=().
Sample() [2/7]
lmms::Sample::Sample (const QByteArray & base64, int sampleRate = Engine::audioEngine()->outputSampleRate())
Definition at line 38 of file Sample.cpp.
References m_buffer, m_endFrame, m_loopEndFrame, m_loopStartFrame, m_startFrame, and sampleRate().
Sample() [3/7]
lmms::Sample::Sample (const SampleFrame * data, size_t numFrames, int sampleRate = Engine::audioEngine()->outputSampleRate())
Definition at line 47 of file Sample.cpp.
References data(), m_buffer, m_endFrame, m_loopEndFrame, m_loopStartFrame, m_startFrame, and sampleRate().
Sample() [4/7]
lmms::Sample::Sample (const Sample & other)
Definition at line 65 of file Sample.cpp.
References Sample(), amplification(), endFrame(), frequency(), loopEndFrame(), loopStartFrame(), m_amplification, m_buffer, m_endFrame, m_frequency, m_loopEndFrame, m_loopStartFrame, m_reversed, m_startFrame, reversed(), and startFrame().
Sample() [5/7]
lmms::Sample::Sample (Sample && other) noexcept
Definition at line 77 of file Sample.cpp.
References Sample(), m_amplification, m_buffer, m_endFrame, m_frequency, m_loopEndFrame, m_loopStartFrame, m_reversed, and m_startFrame.
Sample() [6/7]
lmms::Sample::Sample (const QString & audioFile) explicit
Definition at line 29 of file Sample.cpp.
References m_buffer, m_endFrame, m_loopEndFrame, m_loopStartFrame, and m_startFrame.
Sample() [7/7]
lmms::Sample::Sample (std::shared_ptr< const SampleBuffer > buffer) explicit
Definition at line 56 of file Sample.cpp.
References buffer(), m_buffer, m_endFrame, m_loopEndFrame, m_loopStartFrame, and m_startFrame.
Member Function Documentation
amplification()
auto lmms::Sample::amplification () const->float inline
Definition at line 98 of file Sample.h.
References m_amplification.
Referenced by Sample(), and setAmplification().
buffer()
auto lmms::Sample::buffer () const->std::shared_ptr< constSampleBuffer > inline
Definition at line 93 of file Sample.h.
References m_buffer.
Referenced by Sample(), and Sample().
data()
auto lmms::Sample::data () const->constSampleFrame * inline
Definition at line 92 of file Sample.h.
References m_buffer.
Referenced by Sample(), and Sample().
endFrame()
auto lmms::Sample::endFrame () const->int inline
Definition at line 95 of file Sample.h.
References m_endFrame.
Referenced by Sample(), sampleDuration(), setAllPointFrames(), and setEndFrame().
frequency()
auto lmms::Sample::frequency () const->float inline
Definition at line 99 of file Sample.h.
References m_frequency.
Referenced by Sample(), play(), and setFrequency().
loopEndFrame()
auto lmms::Sample::loopEndFrame () const->int inline
Definition at line 97 of file Sample.h.
References m_loopEndFrame.
Referenced by Sample(), setAllPointFrames(), and setLoopEndFrame().
loopStartFrame()
auto lmms::Sample::loopStartFrame () const->int inline
Definition at line 96 of file Sample.h.
References m_loopStartFrame.
Referenced by Sample(), setAllPointFrames(), and setLoopStartFrame().
operator=() [1/2]
auto lmms::Sample::operator= (const Sample & other) ->Sample &
Definition at line 89 of file Sample.cpp.
References Sample(), m_amplification, m_buffer, m_endFrame, m_frequency, m_loopEndFrame, m_loopStartFrame, m_reversed, and m_startFrame.
Referenced by Sample().
operator=() [2/2]
auto lmms::Sample::operator= (Sample && other) ->Sample & noexcept
Definition at line 103 of file Sample.cpp.
References Sample(), m_amplification, m_buffer, m_endFrame, m_frequency, m_loopEndFrame, m_loopStartFrame, m_reversed, and m_startFrame.
play()
bool lmms::Sample::play (SampleFrame * dst, PlaybackState * state, size_t numFrames, Loop loopMode = Loop::Off, double ratio = 1.0) const->bool
Definition at line 117 of file Sample.cpp.
References lmms::Engine::audioEngine(), lmms::DefaultBaseFreq, lmms::AudioEngine::framesPerPeriod(), frequency(), m_buffer, lmms::Sample::PlaybackState::m_buffer, lmms::Sample::PlaybackState::m_bufferView, lmms::Sample::PlaybackState::m_frameIndex, lmms::Sample::PlaybackState::m_resampler, m_startFrame, lmms::AudioEngine::outputSampleRate(), lmms::AudioResampler::process(), render(), and lmms::AudioResampler::setRatio().
Referenced by Sample().
render()
f_cnt_t lmms::Sample::render (SampleFrame * dst, f_cnt_t size, PlaybackState * state, Loop loop) const private
Definition at line 152 of file Sample.cpp.
References m_amplification, lmms::Sample::PlaybackState::m_backwards, m_buffer, m_endFrame, lmms::Sample::PlaybackState::m_frameIndex, m_loopEndFrame, m_loopStartFrame, m_reversed, Off, On, and PingPong.
Referenced by play().
reversed()
auto lmms::Sample::reversed () const->bool inline
Definition at line 100 of file Sample.h.
References m_reversed.
Referenced by Sample(), and setReversed().
sampleDuration()
auto lmms::Sample::sampleDuration () const->std::chrono::milliseconds
Definition at line 194 of file Sample.cpp.
References endFrame(), m_buffer, and startFrame().
Referenced by Sample().
sampleFile()
auto lmms::Sample::sampleFile () const->constQString & inline
Definition at line 86 of file Sample.h.
References m_buffer, and sampleFile().
Referenced by lmms::SampleThumbnail::SampleThumbnail(), and sampleFile().
sampleRate()
auto lmms::Sample::sampleRate () const->int inline
Definition at line 87 of file Sample.h.
References m_buffer.
Referenced by Sample(), Sample(), and Sample().
sampleSize()
auto lmms::Sample::sampleSize () const->size_t inline
Definition at line 88 of file Sample.h.
References m_buffer.
setAllPointFrames()
void lmms::Sample::setAllPointFrames (int startFrame, int endFrame, int loopStartFrame, int loopEndFrame)
Definition at line 201 of file Sample.cpp.
References endFrame(), loopEndFrame(), loopStartFrame(), setEndFrame(), setLoopEndFrame(), setLoopStartFrame(), setStartFrame(), and startFrame().
setAmplification()
void lmms::Sample::setAmplification (float amplification) inline
Definition at line 107 of file Sample.h.
References amplification(), and m_amplification.
setEndFrame()
void lmms::Sample::setEndFrame (int endFrame) inline
Definition at line 103 of file Sample.h.
References endFrame(), and m_endFrame.
Referenced by setAllPointFrames().
setFrequency()
void lmms::Sample::setFrequency (float frequency) inline
Definition at line 108 of file Sample.h.
References frequency(), and m_frequency.
setLoopEndFrame()
void lmms::Sample::setLoopEndFrame (int loopEndFrame) inline
Definition at line 105 of file Sample.h.
References loopEndFrame(), and m_loopEndFrame.
Referenced by setAllPointFrames().
setLoopStartFrame()
void lmms::Sample::setLoopStartFrame (int loopStartFrame) inline
Definition at line 104 of file Sample.h.
References loopStartFrame(), and m_loopStartFrame.
Referenced by setAllPointFrames().
setReversed()
void lmms::Sample::setReversed (bool reversed) inline
Definition at line 109 of file Sample.h.
References m_reversed, and reversed().
setStartFrame()
void lmms::Sample::setStartFrame (int startFrame) inline
Definition at line 102 of file Sample.h.
References m_startFrame, and startFrame().
Referenced by setAllPointFrames().
startFrame()
auto lmms::Sample::startFrame () const->int inline
Definition at line 94 of file Sample.h.
References m_startFrame.
Referenced by Sample(), sampleDuration(), setAllPointFrames(), and setStartFrame().
toBase64()
auto lmms::Sample::toBase64 () const->QString inline
Definition at line 90 of file Sample.h.
References m_buffer.
Member Data Documentation
m_amplification
std::atomic<float> lmms::Sample::m_amplification = 1.0f private
Definition at line 118 of file Sample.h.
Referenced by Sample(), Sample(), amplification(), operator=(), operator=(), render(), and setAmplification().
m_buffer
std::shared_ptr<const SampleBuffer> lmms::Sample::m_buffer = SampleBuffer::emptyBuffer() private
Definition at line 113 of file Sample.h.
Referenced by Sample(), Sample(), Sample(), Sample(), Sample(), Sample(), buffer(), data(), operator=(), operator=(), play(), render(), sampleDuration(), sampleFile(), sampleRate(), sampleSize(), and toBase64().
m_endFrame
std::atomic<int> lmms::Sample::m_endFrame = 0 private
Definition at line 115 of file Sample.h.
Referenced by Sample(), Sample(), Sample(), Sample(), Sample(), Sample(), endFrame(), operator=(), operator=(), render(), and setEndFrame().
m_frequency
std::atomic<float> lmms::Sample::m_frequency = DefaultBaseFreq private
Definition at line 119 of file Sample.h.
Referenced by Sample(), Sample(), frequency(), operator=(), operator=(), and setFrequency().
m_loopEndFrame
std::atomic<int> lmms::Sample::m_loopEndFrame = 0 private
Definition at line 117 of file Sample.h.
Referenced by Sample(), Sample(), Sample(), Sample(), Sample(), Sample(), loopEndFrame(), operator=(), operator=(), render(), and setLoopEndFrame().
m_loopStartFrame
std::atomic<int> lmms::Sample::m_loopStartFrame = 0 private
Definition at line 116 of file Sample.h.
Referenced by Sample(), Sample(), Sample(), Sample(), Sample(), Sample(), loopStartFrame(), operator=(), operator=(), render(), and setLoopStartFrame().
m_reversed
std::atomic<bool> lmms::Sample::m_reversed = false private
Definition at line 120 of file Sample.h.
Referenced by Sample(), Sample(), operator=(), operator=(), render(), reversed(), and setReversed().
m_startFrame
std::atomic<int> lmms::Sample::m_startFrame = 0 private
Definition at line 114 of file Sample.h.
Referenced by Sample(), Sample(), Sample(), Sample(), Sample(), Sample(), operator=(), operator=(), play(), setStartFrame(), and startFrame().
The documentation for this class was generated from the following files:
include/Sample.h
src/core/Sample.cpp