LMMS: lmms::SamplePlayHandle Class Reference
lmms::SamplePlayHandle Class Reference
#include <SamplePlayHandle.h>
Public Member Functions
SamplePlayHandle (const QString &sampleFile)
SamplePlayHandle (Sample *sample, bool ownAudioBusHandle=true)
SamplePlayHandle (SampleClip *clip)
~SamplePlayHandle () override
bool affinityMatters () const override
f_cnt_t framesDone () const
bool isFinished () const override
bool isFromTrack (const Track *_track) const override
void play (SampleFrame *buffer) override
void setDoneMayReturnTrue (bool _enable)
void setPatternTrack (PatternTrack *pt)
void setVolumeModel (FloatModel *_model)
f_cnt_t totalFrames () const
Public Member Functions inherited from lmms::PlayHandle
PlayHandle (const Type type, f_cnt_t offset=0)
virtual ~PlayHandle ()
const QThread * affinity () const
AudioBusHandle * audioBusHandle ()
SampleFrame * buffer ()
void doProcessing () override
void lock ()
f_cnt_t offset () const
PlayHandle & operator= (PlayHandle &p)
void releaseBuffer ()
bool requiresProcessing () const override
void setAudioBusHandle (AudioBusHandle *busHandle)
void setOffset (f_cnt_t _offset)
void setUsesBuffer (const bool b)
bool tryLock ()
Type type () const
void unlock ()
bool usesBuffer () const
Public Member Functions inherited from lmms::ThreadableJob
ThreadableJob ()
void done ()
void process ()
void queue ()
void reset ()
ProcessingState state () const
Private Attributes
FloatModel m_defaultVolumeModel
bool m_doneMayReturnTrue
f_cnt_t m_frame
const bool m_ownAudioBusHandle
PatternTrack * m_patternTrack
Sample * m_sample
Sample::PlaybackState m_state
Track * m_track
FloatModel * m_volumeModel
Additional Inherited Members
Public Types inherited from lmms::PlayHandle
enum class Type {
NotePlayHandle = 0x01 ,
InstrumentPlayHandle = 0x02 ,
SamplePlayHandle = 0x04 ,
PresetPreviewHandle = 0x08
}
using Types = Flags<Type>
Public Types inherited from lmms::ThreadableJob
enum class ProcessingState : int {
Unstarted ,
Queued ,
InProgress ,
Done
}
Static Public Attributes inherited from lmms::PlayHandle
static constexpr std::size_t MaxNumber = 1024
Protected Attributes inherited from lmms::ThreadableJob
std::atomic< ProcessingState > m_state
Detailed Description
Definition at line 42 of file SamplePlayHandle.h.
Constructor & Destructor Documentation
SamplePlayHandle() [1/3]
lmms::SamplePlayHandle::SamplePlayHandle (Sample * sample, bool ownAudioBusHandle = true)
Definition at line 38 of file SamplePlayHandle.cpp.
References lmms::PlayHandle::PlayHandle(), SamplePlayHandle(), lmms::DefaultVolume, m_defaultVolumeModel, m_doneMayReturnTrue, m_frame, m_ownAudioBusHandle, m_patternTrack, m_sample, m_track, m_volumeModel, lmms::MaxVolume, lmms::MinVolume, and lmms::PlayHandle::setAudioBusHandle().
Referenced by SamplePlayHandle(), SamplePlayHandle(), and SamplePlayHandle().
SamplePlayHandle() [2/3]
lmms::SamplePlayHandle::SamplePlayHandle (const QString & sampleFile)
Definition at line 58 of file SamplePlayHandle.cpp.
References SamplePlayHandle().
SamplePlayHandle() [3/3]
lmms::SamplePlayHandle::SamplePlayHandle (SampleClip * clip)
Definition at line 66 of file SamplePlayHandle.cpp.
References SamplePlayHandle(), lmms::Clip::getTrack(), m_track, and lmms::PlayHandle::setAudioBusHandle().
~SamplePlayHandle()
lmms::SamplePlayHandle::~SamplePlayHandle () override
Definition at line 76 of file SamplePlayHandle.cpp.
References lmms::PlayHandle::audioBusHandle(), m_ownAudioBusHandle, and m_sample.
Member Function Documentation
affinityMatters()
bool lmms::SamplePlayHandle::affinityMatters () const inline override virtual
Reimplemented from lmms::PlayHandle.
Definition at line 50 of file SamplePlayHandle.h.
framesDone()
f_cnt_t lmms::SamplePlayHandle::framesDone () const inline
Definition at line 62 of file SamplePlayHandle.h.
References m_frame.
Referenced by isFinished(), and play().
isFinished()
bool lmms::SamplePlayHandle::isFinished () const override virtual
Implements lmms::PlayHandle.
Definition at line 129 of file SamplePlayHandle.cpp.
References framesDone(), m_doneMayReturnTrue, and totalFrames().
isFromTrack()
bool lmms::SamplePlayHandle::isFromTrack (const Track * _track) const override virtual
Implements lmms::PlayHandle.
Definition at line 137 of file SamplePlayHandle.cpp.
References m_patternTrack, and m_track.
play()
void lmms::SamplePlayHandle::play (SampleFrame * buffer) override virtual
Implements lmms::PlayHandle.
Definition at line 88 of file SamplePlayHandle.cpp.
References lmms::Engine::audioEngine(), lmms::PlayHandle::buffer(), framesDone(), lmms::AudioEngine::framesPerPeriod(), m_frame, m_patternTrack, m_sample, m_state, m_track, lmms::PlayHandle::offset(), totalFrames(), and lmms::zeroSampleFrames().
setDoneMayReturnTrue()
void lmms::SamplePlayHandle::setDoneMayReturnTrue (bool _enable) inline
Definition at line 66 of file SamplePlayHandle.h.
References m_doneMayReturnTrue.
Referenced by lmms::gui::FileBrowserTreeWidget::previewFileItem().
setPatternTrack()
void lmms::SamplePlayHandle::setPatternTrack (PatternTrack * pt) inline
Definition at line 71 of file SamplePlayHandle.h.
References m_patternTrack.
setVolumeModel()
void lmms::SamplePlayHandle::setVolumeModel (FloatModel * _model) inline
Definition at line 76 of file SamplePlayHandle.h.
References m_volumeModel.
totalFrames()
f_cnt_t lmms::SamplePlayHandle::totalFrames () const
Definition at line 145 of file SamplePlayHandle.cpp.
References lmms::Engine::audioEngine(), m_sample, and lmms::AudioEngine::outputSampleRate().
Referenced by isFinished(), and play().
Member Data Documentation
m_defaultVolumeModel
FloatModel lmms::SamplePlayHandle::m_defaultVolumeModel private
Definition at line 91 of file SamplePlayHandle.h.
Referenced by SamplePlayHandle().
m_doneMayReturnTrue
bool lmms::SamplePlayHandle::m_doneMayReturnTrue private
Definition at line 84 of file SamplePlayHandle.h.
Referenced by SamplePlayHandle(), isFinished(), and setDoneMayReturnTrue().
m_frame
f_cnt_t lmms::SamplePlayHandle::m_frame private
Definition at line 86 of file SamplePlayHandle.h.
Referenced by SamplePlayHandle(), framesDone(), and play().
m_ownAudioBusHandle
const bool lmms::SamplePlayHandle::m_ownAudioBusHandle private
Definition at line 89 of file SamplePlayHandle.h.
Referenced by SamplePlayHandle(), and ~SamplePlayHandle().
m_patternTrack
PatternTrack* lmms::SamplePlayHandle::m_patternTrack private
Definition at line 95 of file SamplePlayHandle.h.
Referenced by SamplePlayHandle(), isFromTrack(), play(), and setPatternTrack().
m_sample
Sample* lmms::SamplePlayHandle::m_sample private
Definition at line 83 of file SamplePlayHandle.h.
Referenced by SamplePlayHandle(), ~SamplePlayHandle(), play(), and totalFrames().
m_state
Sample::PlaybackState lmms::SamplePlayHandle::m_state private
Definition at line 87 of file SamplePlayHandle.h.
Referenced by play().
m_track
Track* lmms::SamplePlayHandle::m_track private
Definition at line 93 of file SamplePlayHandle.h.
Referenced by SamplePlayHandle(), SamplePlayHandle(), isFromTrack(), and play().
m_volumeModel
FloatModel* lmms::SamplePlayHandle::m_volumeModel private
Definition at line 92 of file SamplePlayHandle.h.
Referenced by SamplePlayHandle(), and setVolumeModel().
The documentation for this class was generated from the following files:
include/SamplePlayHandle.h
src/core/SamplePlayHandle.cpp