LMMS: Jack::JackShmMemAble Class Reference
Jack::JackShmMemAble Class Reference
A class which objects possibly want to be allocated in shared memory derives from this class.
#include <JackShmMem.h>
Public Member Functions
char * GetShmAddress ()
int GetShmIndex ()
void Init ()
void LockMemory ()
void UnlockMemory ()
Protected Attributes
jack_shm_info_t fInfo
Detailed Description
A class which objects possibly want to be allocated in shared memory derives from this class.
Definition at line 48 of file JackShmMem.h.
Member Function Documentation
GetShmAddress()
char * Jack::JackShmMemAble::GetShmAddress () inline
Definition at line 63 of file JackShmMem.h.
References fInfo.
Referenced by Jack::JackExternalClient::Open().
GetShmIndex()
int Jack::JackShmMemAble::GetShmIndex () inline
Definition at line 58 of file JackShmMem.h.
References fInfo.
Referenced by Jack::JackExternalClient::Open().
Init()
void Jack::JackShmMemAble::Init ()
Definition at line 41 of file JackShmMem.cpp.
References fInfo, and Jack::gInfo.
Referenced by Jack::JackClientControl::JackClientControl(), Jack::JackClientControl::JackClientControl(), Jack::JackClientControl::JackClientControl(), Jack::JackShmMem::JackShmMem(), and Jack::JackExternalClient::Open().
LockMemory()
void Jack::JackShmMemAble::LockMemory () inline
Definition at line 68 of file JackShmMem.h.
References fInfo, and Jack::LockMemoryImp().
Referenced by Jack::JackShmMem::JackShmMem().
UnlockMemory()
void Jack::JackShmMemAble::UnlockMemory () inline
Definition at line 73 of file JackShmMem.h.
References fInfo, and Jack::UnlockMemoryImp().
Referenced by Jack::JackShmMem::~JackShmMem().
Member Data Documentation
fInfo
jack_shm_info_t Jack::JackShmMemAble::fInfo protected
Definition at line 52 of file JackShmMem.h.
Referenced by GetShmAddress(), GetShmIndex(), Init(), LockMemory(), Jack::JackShmMem::operator delete(), and UnlockMemory().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackShmMem.h
src/3rdparty/jack2/common/JackShmMem.cpp