LMMS: Jack::JackAtomicState< T > Class Template Reference
Jack::JackAtomicState< T > Class Template Reference
A class to handle two states (switching from one to the other) in a lock-free manner.
#include <JackAtomicState.h>
Public Member Functions
JackAtomicState ()
~JackAtomicState ()
UInt16 GetCurrentIndex ()
Returns the current state index.
bool IsPendingChange ()
T * ReadCurrentState ()
Returns the current state : only valid in the RT reader thread.
T * TrySwitchState ()
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
T * TrySwitchState (bool *result)
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
T * WriteNextStateStart ()
Start write operation : setup and returns the next state to update, check for recursive write calls.
void WriteNextStateStop ()
Stop write operation : make the next state ready to be used by the RT thread.
Protected Member Functions
UInt32 WriteNextStateStartAux ()
void WriteNextStateStopAux ()
Protected Attributes
SInt32 fCallWriteCounter
volatile AtomicCounter fCounter
T fState [2]
Detailed Description
template<class T>
class Jack::JackAtomicState< T >
A class to handle two states (switching from one to the other) in a lock-free manner.
Definition at line 91 of file JackAtomicState.h.
Constructor & Destructor Documentation
JackAtomicState()
template<class T> Jack::JackAtomicState< T >::JackAtomicState () inline
Definition at line 133 of file JackAtomicState.h.
References JackAtomicState(), Counter, fCallWriteCounter, fCounter, and offsetof.
Referenced by JackAtomicState().
~JackAtomicState()
template<class T> Jack::JackAtomicState< T >::~JackAtomicState () inline
Definition at line 141 of file JackAtomicState.h.
Member Function Documentation
GetCurrentIndex()
template<class T> UInt16 Jack::JackAtomicState< T >::GetCurrentIndex () inline
Returns the current state index.
Definition at line 155 of file JackAtomicState.h.
References CurIndex, and fCounter.
IsPendingChange()
template<class T> bool Jack::JackAtomicState< T >::IsPendingChange () inline
Definition at line 211 of file JackAtomicState.h.
References CurIndex, fCounter, and NextIndex.
Referenced by WaitGraphChange().
ReadCurrentState()
template<class T> T * Jack::JackAtomicState< T >::ReadCurrentState () inline
Returns the current state : only valid in the RT reader thread.
Definition at line 147 of file JackAtomicState.h.
References CurArrayIndex, fCounter, and fState.
Referenced by jack_last_frame_time().
TrySwitchState() [1/2]
template<class T> T * Jack::JackAtomicState< T >::TrySwitchState () inline
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
Definition at line 163 of file JackAtomicState.h.
References CAS(), Counter, CurArrayIndex, CurIndex, fCounter, fState, and NextIndex.
TrySwitchState() [2/2]
template<class T> T * Jack::JackAtomicState< T >::TrySwitchState (bool * result) inline
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
Definition at line 178 of file JackAtomicState.h.
References CAS(), Counter, CurArrayIndex, CurIndex, fCounter, fState, and NextIndex.
WriteNextStateStart()
template<class T> T * Jack::JackAtomicState< T >::WriteNextStateStart () inline
Start write operation : setup and returns the next state to update, check for recursive write calls.
Definition at line 194 of file JackAtomicState.h.
References fCallWriteCounter, fCounter, fState, NextArrayIndex, and WriteNextStateStartAux().
WriteNextStateStartAux()
template<class T> UInt32 Jack::JackAtomicState< T >::WriteNextStateStartAux () inline protected
Definition at line 100 of file JackAtomicState.h.
References CAS(), Counter, CurArrayIndex, CurIndex, fCounter, fState, NextArrayIndex, and NextIndex.
Referenced by WriteNextStateStart().
WriteNextStateStop()
template<class T> void Jack::JackAtomicState< T >::WriteNextStateStop () inline
Stop write operation : make the next state ready to be used by the RT thread.
Definition at line 205 of file JackAtomicState.h.
References fCallWriteCounter, and WriteNextStateStopAux().
WriteNextStateStopAux()
template<class T> void Jack::JackAtomicState< T >::WriteNextStateStopAux () inline protected
Definition at line 120 of file JackAtomicState.h.
References CAS(), Counter, fCounter, and NextIndex.
Referenced by WriteNextStateStop().
Member Data Documentation
fCallWriteCounter
template<class T> SInt32 Jack::JackAtomicState< T >::fCallWriteCounter protected
Definition at line 98 of file JackAtomicState.h.
Referenced by JackAtomicState(), WriteNextStateStart(), and WriteNextStateStop().
fCounter
template<class T> volatile AtomicCounter Jack::JackAtomicState< T >::fCounter protected
Definition at line 97 of file JackAtomicState.h.
Referenced by JackAtomicState(), GetCurrentIndex(), IsPendingChange(), ReadCurrentState(), TrySwitchState(), TrySwitchState(), WriteNextStateStart(), WriteNextStateStartAux(), and WriteNextStateStopAux().
fState
template<class T> T Jack::JackAtomicState< T >::fState[2] protected
Definition at line 96 of file JackAtomicState.h.
Referenced by ReadCurrentState(), TrySwitchState(), TrySwitchState(), WriteNextStateStart(), and WriteNextStateStartAux().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackAtomicState.h