LMMS: Jack::JackGlobals Struct Reference
Jack::JackGlobals Struct Reference
#include <JackGlobals.h>
Static Public Member Functions
static void CheckContext (const char *name)
Static Public Attributes
static JackClient * fClientTable [CLIENT_NUM] = {}
static jack_thread_creator_t fJackThreadCreator = pthread_create
static jack_tls_key fKeyLogFunction
static jack_tls_key fNotificationThread
static JackMutex * fOpenMutex = new JackMutex()
static jack_tls_key fRealTimeThread
static volatile bool fServerRunning = false
static JackMutex * fSynchroMutex = new JackMutex()
static bool fVerbose = 0
Detailed Description
Definition at line 38 of file JackGlobals.h.
Member Function Documentation
CheckContext()
void Jack::JackGlobals::CheckContext (const char * name) static
Definition at line 76 of file JackGlobals.cpp.
Referenced by jack_activate(), jack_client_close(), jack_client_close(), jack_client_create_thread(), jack_client_get_uuid(), jack_client_has_session_callback(), jack_client_kill_thread(), jack_client_max_real_time_priority(), jack_client_new(), jack_client_open(), jack_client_open(), jack_client_real_time_priority(), jack_client_stop_thread(), jack_client_thread_id(), jack_connect(), jack_cpu_load(), jack_cycle_signal(), jack_cycle_wait(), jack_deactivate(), jack_disconnect(), jack_engine_takeover_timebase(), jack_frame_time(), jack_frames_since_cycle_start(), jack_frames_to_time(), jack_free(), jack_free_description(), jack_get_all_properties(), jack_get_buffer_size(), jack_get_client_name(), jack_get_client_name_by_uuid(), jack_get_current_transport_frame(), jack_get_cycle_times(), jack_get_internal_client_name(), jack_get_max_delayed_usecs(), jack_get_ports(), jack_get_properties(), jack_get_property(), jack_get_sample_rate(), jack_get_time(), jack_get_transport_info(), jack_get_uuid_for_client_name(), jack_get_version(), jack_get_version_string(), jack_get_xrun_delayed_usecs(), jack_internal_client_close(), jack_internal_client_handle(), jack_internal_client_load(), jack_internal_client_load_aux(), jack_internal_client_new(), jack_internal_client_unload(), jack_is_realtime(), jack_last_frame_time(), jack_on_info_shutdown(), jack_on_shutdown(), jack_port_by_id(), jack_port_by_name(), jack_port_connected(), jack_port_connected_to(), jack_port_disconnect(), jack_port_ensure_monitor(), jack_port_flags(), jack_port_get_aliases(), jack_port_get_all_connections(), jack_port_get_buffer(), jack_port_get_connections(), jack_port_get_latency(), jack_port_get_latency_range(), jack_port_get_total_latency(), jack_port_is_mine(), jack_port_monitoring_input(), jack_port_name(), jack_port_register(), jack_port_rename(), jack_port_request_monitor(), jack_port_request_monitor_by_name(), jack_port_set_alias(), jack_port_set_latency(), jack_port_set_latency_range(), jack_port_set_name(), jack_port_short_name(), jack_port_tie(), jack_port_type(), jack_port_type_get_buffer_size(), jack_port_type_id(), jack_port_unregister(), jack_port_unset_alias(), jack_port_untie(), jack_port_uuid(), jack_recompute_total_latencies(), jack_recompute_total_latency(), jack_release_timebase(), jack_remove_all_properties(), jack_remove_properties(), jack_remove_property(), jack_reserve_client_name(), jack_reset_max_delayed_usecs(), jack_session_commands_free(), jack_session_event_free(), jack_session_notify(), jack_session_reply(), jack_set_buffer_size(), jack_set_buffer_size_callback(), jack_set_client_registration_callback(), jack_set_freewheel(), jack_set_freewheel_callback(), jack_set_graph_order_callback(), jack_set_latency_callback(), jack_set_port_connect_callback(), jack_set_port_registration_callback(), jack_set_port_rename_callback(), jack_set_process_callback(), jack_set_process_thread(), jack_set_property(), jack_set_property_change_callback(), jack_set_sample_rate_callback(), jack_set_session_callback(), jack_set_sync_callback(), jack_set_sync_timeout(), jack_set_thread_init_callback(), jack_set_timebase_callback(), jack_set_transport_info(), jack_set_xrun_callback(), jack_thread_wait(), jack_time_to_frames(), jack_transport_locate(), jack_transport_query(), jack_transport_reposition(), jack_transport_start(), and jack_transport_stop().
Member Data Documentation
fClientTable
JackClient * Jack::JackGlobals::fClientTable = {} static
Definition at line 46 of file JackGlobals.h.
Referenced by Jack::JackClient::Close(), Jack::JackLibGlobals::Init(), jack_port_set_name(), Jack::JackInternalClient::Open(), and Jack::JackLibClient::Open().
fJackThreadCreator
jack_thread_creator_t Jack::JackGlobals::fJackThreadCreator = pthread_create static
Definition at line 49 of file JackGlobals.h.
Referenced by jack_set_thread_creator(), Jack::JackAndroidThread::StartImp(), and Jack::JackPosixThread::StartImp().
fKeyLogFunction
jack_tls_key Jack::JackGlobals::fKeyLogFunction static
Definition at line 42 of file JackGlobals.h.
Referenced by change_thread_log_function(), and jack_format_and_log().
fNotificationThread
jack_tls_key Jack::JackGlobals::fNotificationThread static
Definition at line 41 of file JackGlobals.h.
Referenced by Jack::JackSocketClientChannel::Init(), Jack::JackWinNamedPipeClientChannel::Init(), Jack::JackGenericClientChannel::ServerAsyncCall(), and Jack::JackGenericClientChannel::ServerSyncCall().
fOpenMutex
JackMutex * Jack::JackGlobals::fOpenMutex = new JackMutex() static
Definition at line 43 of file JackGlobals.h.
Referenced by jack_client_close(), jack_client_close(), jack_client_new(), jack_client_open(), and jack_client_open().
fRealTimeThread
jack_tls_key Jack::JackGlobals::fRealTimeThread static
Definition at line 40 of file JackGlobals.h.
Referenced by Jack::JackClient::Init(), and WaitGraphChange().
fServerRunning
volatile bool Jack::JackGlobals::fServerRunning = false static
Definition at line 45 of file JackGlobals.h.
Referenced by Jack::JackLibGlobals::Init(), Jack::JackInternalClient::Open(), Jack::JackSocketClientChannel::Open(), Jack::JackWinNamedPipeClientChannel::Open(), Jack::JackGenericClientChannel::ServerAsyncCall(), Jack::JackGenericClientChannel::ServerSyncCall(), and Jack::JackLibClient::ShutDown().
fSynchroMutex
JackMutex * Jack::JackGlobals::fSynchroMutex = new JackMutex() static
Definition at line 44 of file JackGlobals.h.
Referenced by Jack::JackLibClient::ClientNotifyImp(), Jack::JackClient::Close(), and Jack::JackLibClient::Open().
fVerbose
bool Jack::JackGlobals::fVerbose = 0 static
Definition at line 47 of file JackGlobals.h.
Referenced by Jack::JackServer::JackServer(), jack_log(), and Jack::JackLibClient::Open().
The documentation for this struct was generated from the following files:
src/3rdparty/jack2/common/JackGlobals.h
src/3rdparty/jack2/common/JackGlobals.cpp