LMMS: Jack::JackFreewheelDriver Class Reference
Jack::JackFreewheelDriver Class Reference
The FreeWheel driver : run Jack engine at full speed.
#include <JackFreewheelDriver.h>
Public Member Functions
JackFreewheelDriver (JackLockedEngine *engine, JackSynchro *table)
virtual ~JackFreewheelDriver ()
bool IsRealTime () const
int Process ()
int ProcessReadAsync ()
int ProcessReadSync ()
int ProcessWriteAsync ()
int ProcessWriteSync ()
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual int Attach ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual int Detach ()
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsFixedBufferSize ()
virtual bool IsRunning () const
virtual int Open ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int ProcessRead ()
int ProcessReadSlaves ()
virtual int ProcessWrite ()
int ProcessWriteSlaves ()
virtual int Read ()
void RemoveSlave (JackDriverInterface *slave)
virtual int SetBufferSize (jack_nframes_t buffer_size)
void SetMaster (bool onoff)
virtual int SetSampleRate (jack_nframes_t sample_rate)
virtual int Start ()
virtual int Stop ()
virtual int Write ()
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Protected Member Functions
int SuspendRefNum ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
Additional Inherited Members
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The FreeWheel driver : run Jack engine at full speed.
Definition at line 33 of file JackFreewheelDriver.h.
Constructor & Destructor Documentation
JackFreewheelDriver()
Jack::JackFreewheelDriver::JackFreewheelDriver (JackLockedEngine * engine, JackSynchro * table) inline
Definition at line 41 of file JackFreewheelDriver.h.
References Jack::JackDriver::JackDriver().
~JackFreewheelDriver()
virtual Jack::JackFreewheelDriver::~JackFreewheelDriver () inline virtual
Definition at line 43 of file JackFreewheelDriver.h.
Member Function Documentation
IsRealTime()
bool Jack::JackFreewheelDriver::IsRealTime () const inline virtual
Reimplemented from Jack::JackDriver.
Definition at line 46 of file JackFreewheelDriver.h.
Process()
int Jack::JackFreewheelDriver::Process () virtual
Reimplemented from Jack::JackDriver.
Definition at line 31 of file JackFreewheelDriver.cpp.
References Jack::JackDriver::CycleTakeBeginTime(), Jack::JackDriver::fBeginDateUst, Jack::JackDriver::fEndDateUst, Jack::JackDriver::fEngine, Jack::JackDriver::fEngineControl, jack_error, jack_log(), Jack::JackDriver::ResumeRefNum(), and SuspendRefNum().
ProcessReadAsync()
int Jack::JackFreewheelDriver::ProcessReadAsync () virtual
Reimplemented from Jack::JackDriver.
Definition at line 77 of file JackFreewheelDriver.cpp.
References jack_error, and Jack::JackDriver::ResumeRefNum().
ProcessReadSync()
int Jack::JackFreewheelDriver::ProcessReadSync () virtual
Reimplemented from Jack::JackDriver.
Definition at line 57 of file JackFreewheelDriver.cpp.
References jack_error, and Jack::JackDriver::ResumeRefNum().
ProcessWriteAsync()
int Jack::JackFreewheelDriver::ProcessWriteAsync () virtual
Reimplemented from Jack::JackDriver.
Definition at line 87 of file JackFreewheelDriver.cpp.
ProcessWriteSync()
int Jack::JackFreewheelDriver::ProcessWriteSync () virtual
Reimplemented from Jack::JackDriver.
Definition at line 67 of file JackFreewheelDriver.cpp.
References jack_error, and Jack::JackDriver::SuspendRefNum().
SuspendRefNum()
int Jack::JackFreewheelDriver::SuspendRefNum () protected virtual
Reimplemented from Jack::JackDriver.
Definition at line 92 of file JackFreewheelDriver.cpp.
References Jack::JackDriver::fClientControl, Jack::JackDriver::fGraphManager, FREEWHEEL_DRIVER_TIMEOUT, and Jack::JackDriver::fSynchroTable.
Referenced by Process().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackFreewheelDriver.h
src/3rdparty/jack2/common/JackFreewheelDriver.cpp