LMMS: lmms::LocklessAllocatorT< T > Class Template Reference
lmms::LocklessAllocatorT< T > Class Template Reference
#include <LocklessAllocator.h>
Public Member Functions
LocklessAllocatorT (size_t nmemb)
~LocklessAllocatorT () override=default
T * alloc ()
void free (T *ptr)
Additional Inherited Members
Private Member Functions inherited from lmms::LocklessAllocator
LocklessAllocator (size_t nmemb, size_t size)
virtual ~LocklessAllocator ()
void * alloc ()
void free (void *ptr)
Detailed Description
template<typename T>
class lmms::LocklessAllocatorT< T >
Definition at line 62 of file LocklessAllocator.h.
Constructor & Destructor Documentation
LocklessAllocatorT()
template<typename T> lmms::LocklessAllocatorT< T >::LocklessAllocatorT (size_t nmemb) inline
Definition at line 65 of file LocklessAllocator.h.
References lmms::LocklessAllocator::LocklessAllocator().
~LocklessAllocatorT()
template<typename T> lmms::LocklessAllocatorT< T >::~LocklessAllocatorT () override default
Member Function Documentation
alloc()
template<typename T> T * lmms::LocklessAllocatorT< T >::alloc () inline
Definition at line 72 of file LocklessAllocator.h.
References lmms::LocklessAllocator::alloc().
free()
template<typename T> void lmms::LocklessAllocatorT< T >::free (T * ptr) inline
Definition at line 77 of file LocklessAllocator.h.
References lmms::LocklessAllocator::free().
The documentation for this class was generated from the following file:
include/LocklessAllocator.h