LMMS: src/3rdparty/jack2/linux/alsa/jslist.h File Reference
jslist.h File Reference
#include <stdlib.h>
Classes
struct _JSList
Macros
#define jack_slist_next(slist)
Typedefs
typedef int(* JCompareFunc) (void *a, void *b)
Functions
static __inline__ JSList * jack_slist_alloc (void)
static __inline__ JSList * jack_slist_append (JSList *list, void *data)
static __inline__ JSList * jack_slist_copy (JSList *list)
static __inline__ JSList * jack_slist_find (JSList *list, void *data)
static __inline__ void jack_slist_free (JSList *list)
static __inline__ void jack_slist_free_1 (JSList *list)
static __inline__ JSList * jack_slist_last (JSList *list)
static __inline__ unsigned int jack_slist_length (JSList *list)
static __inline__ JSList * jack_slist_prepend (JSList *list, void *data)
static __inline__ JSList * jack_slist_remove (JSList *list, void *data)
static __inline__ JSList * jack_slist_remove_link (JSList *list, JSList *link)
static __inline__ JSList * jack_slist_sort (JSList *list, JCompareFunc compare_func)
static __inline__ JSList * jack_slist_sort_merge (JSList *l1, JSList *l2, JCompareFunc compare_func)
Macro Definition Documentation
jack_slist_next
#define jack_slist_next (slist)
Value:
((slist) ? (((JSList *)(slist))->next) : NULL)
Definition at line 68 of file jslist.h.
Typedef Documentation
JCompareFunc
typedef int(* JCompareFunc) (void *a, void *b)
Definition at line 33 of file jslist.h.
Function Documentation
jack_slist_alloc()
__inline__ JSList * jack_slist_alloc (void) static
Definition at line 43 of file jslist.h.
References _JSList::data, and _JSList::next.
jack_slist_append()
__inline__ JSList * jack_slist_append (JSList * list, void * data) static
Definition at line 216 of file jslist.h.
References _JSList::data, jack_slist_alloc(), jack_slist_last(), and _JSList::next.
jack_slist_copy()
__inline__ JSList * jack_slist_copy (JSList * list) static
Definition at line 192 of file jslist.h.
References _JSList::data, jack_slist_alloc(), and _JSList::next.
jack_slist_find()
__inline__ JSList * jack_slist_find (JSList * list, void * data) static
Definition at line 178 of file jslist.h.
References _JSList::data, and _JSList::next.
jack_slist_free()
__inline__ void jack_slist_free (JSList * list) static
Definition at line 112 of file jslist.h.
References _JSList::next.
jack_slist_free_1()
__inline__ void jack_slist_free_1 (JSList * list) static
Definition at line 123 of file jslist.h.
jack_slist_last()
__inline__ JSList * jack_slist_last (JSList * list) static
Definition at line 71 of file jslist.h.
References _JSList::next.
jack_slist_length()
__inline__ unsigned int jack_slist_length (JSList * list) static
Definition at line 163 of file jslist.h.
References _JSList::next.
jack_slist_prepend()
__inline__ JSList * jack_slist_prepend (JSList * list, void * data) static
Definition at line 56 of file jslist.h.
References _JSList::data, and _JSList::next.
jack_slist_remove()
__inline__ JSList * jack_slist_remove (JSList * list, void * data) static
Definition at line 132 of file jslist.h.
References _JSList::data, jack_slist_free(), and _JSList::next.
jack_slist_remove_link()
__inline__ JSList * jack_slist_remove_link (JSList * list, JSList * link) static
Definition at line 83 of file jslist.h.
References _JSList::next.
jack_slist_sort()
__inline__ JSList * jack_slist_sort (JSList * list, JCompareFunc compare_func) static
Definition at line 260 of file jslist.h.
References jack_slist_sort(), jack_slist_sort_merge(), and _JSList::next.
jack_slist_sort_merge()
__inline__ JSList * jack_slist_sort_merge (JSList * l1, JSList * l2, JCompareFunc compare_func) static
Definition at line 236 of file jslist.h.
References _JSList::data, and _JSList::next.