LMMS: lmms::SampleRecordHandle Class Reference
lmms::SampleRecordHandle Class Reference
#include <SampleRecordHandle.h>
Public Member Functions
SampleRecordHandle (SampleClip *clip)
~SampleRecordHandle () override
std::shared_ptr< const SampleBuffer > createSampleBuffer ()
f_cnt_t framesRecorded () const
bool isFinished () const override
bool isFromTrack (const Track *_track) const override
void play (SampleFrame *_working_buffer) override
Public Member Functions inherited from lmms::PlayHandle
PlayHandle (const Type type, f_cnt_t offset=0)
virtual ~PlayHandle ()
const QThread * affinity () const
virtual bool affinityMatters () const
AudioBusHandle * audioBusHandle ()
SampleFrame * buffer ()
void doProcessing () override
void lock ()
f_cnt_t offset () const
PlayHandle & operator= (PlayHandle &p)
void releaseBuffer ()
bool requiresProcessing () const override
void setAudioBusHandle (AudioBusHandle *busHandle)
void setOffset (f_cnt_t _offset)
void setUsesBuffer (const bool b)
bool tryLock ()
Type type () const
void unlock ()
bool usesBuffer () const
Public Member Functions inherited from lmms::ThreadableJob
ThreadableJob ()
void done ()
void process ()
void queue ()
void reset ()
ProcessingState state () const
Private Types
using bufferList = QList<QPair<SampleFrame*, f_cnt_t>>
Private Member Functions
virtual void writeBuffer (const SampleFrame *_ab, const f_cnt_t _frames)
Private Attributes
bufferList m_buffers
SampleClip * m_clip
f_cnt_t m_framesRecorded
TimePos m_minLength
PatternTrack * m_patternTrack
Track * m_track
Additional Inherited Members
Public Types inherited from lmms::PlayHandle
enum class Type {
NotePlayHandle = 0x01 ,
InstrumentPlayHandle = 0x02 ,
SamplePlayHandle = 0x04 ,
PresetPreviewHandle = 0x08
}
using Types = Flags<Type>
Public Types inherited from lmms::ThreadableJob
enum class ProcessingState : int {
Unstarted ,
Queued ,
InProgress ,
Done
}
Static Public Attributes inherited from lmms::PlayHandle
static constexpr std::size_t MaxNumber = 1024
Protected Attributes inherited from lmms::ThreadableJob
std::atomic< ProcessingState > m_state
Detailed Description
Definition at line 45 of file SampleRecordHandle.h.
Member Typedef Documentation
bufferList
using lmms::SampleRecordHandle::bufferList = QList<QPair<SampleFrame*, f_cnt_t>> private
Definition at line 64 of file SampleRecordHandle.h.
Constructor & Destructor Documentation
SampleRecordHandle()
lmms::SampleRecordHandle::SampleRecordHandle (SampleClip * clip)
Definition at line 38 of file SampleRecordHandle.cpp.
References lmms::PlayHandle::PlayHandle(), m_clip, m_framesRecorded, m_minLength, m_patternTrack, and m_track.
~SampleRecordHandle()
lmms::SampleRecordHandle::~SampleRecordHandle () override
Definition at line 51 of file SampleRecordHandle.cpp.
References createSampleBuffer(), m_buffers, and m_clip.
Member Function Documentation
createSampleBuffer()
std::shared_ptr< const SampleBuffer > lmms::SampleRecordHandle::createSampleBuffer ()
Definition at line 108 of file SampleRecordHandle.cpp.
References lmms::Engine::audioEngine(), framesRecorded(), and m_buffers.
Referenced by ~SampleRecordHandle().
framesRecorded()
f_cnt_t lmms::SampleRecordHandle::framesRecorded () const
Definition at line 100 of file SampleRecordHandle.cpp.
References m_framesRecorded.
Referenced by createSampleBuffer().
isFinished()
bool lmms::SampleRecordHandle::isFinished () const override virtual
Implements lmms::PlayHandle.
Definition at line 84 of file SampleRecordHandle.cpp.
isFromTrack()
bool lmms::SampleRecordHandle::isFromTrack (const Track * _track) const override virtual
Implements lmms::PlayHandle.
Definition at line 92 of file SampleRecordHandle.cpp.
References m_patternTrack, and m_track.
play()
void lmms::SampleRecordHandle::play (SampleFrame * _working_buffer) override virtual
Implements lmms::PlayHandle.
Definition at line 66 of file SampleRecordHandle.cpp.
References lmms::Engine::audioEngine(), lmms::Engine::framesPerTick(), lmms::AudioEngine::inputBuffer(), lmms::AudioEngine::inputBufferFrames(), m_framesRecorded, m_minLength, and writeBuffer().
writeBuffer()
void lmms::SampleRecordHandle::writeBuffer (const SampleFrame * _ab, const f_cnt_t _frames) private virtual
Definition at line 129 of file SampleRecordHandle.cpp.
References lmms::DEFAULT_CHANNELS, and m_buffers.
Referenced by play().
Member Data Documentation
m_buffers
bufferList lmms::SampleRecordHandle::m_buffers private
Definition at line 65 of file SampleRecordHandle.h.
Referenced by ~SampleRecordHandle(), createSampleBuffer(), and writeBuffer().
m_clip
SampleClip* lmms::SampleRecordHandle::m_clip private
Definition at line 71 of file SampleRecordHandle.h.
Referenced by SampleRecordHandle(), and ~SampleRecordHandle().
m_framesRecorded
f_cnt_t lmms::SampleRecordHandle::m_framesRecorded private
Definition at line 66 of file SampleRecordHandle.h.
Referenced by SampleRecordHandle(), framesRecorded(), and play().
m_minLength
TimePos lmms::SampleRecordHandle::m_minLength private
Definition at line 67 of file SampleRecordHandle.h.
Referenced by SampleRecordHandle(), and play().
m_patternTrack
PatternTrack* lmms::SampleRecordHandle::m_patternTrack private
Definition at line 70 of file SampleRecordHandle.h.
Referenced by SampleRecordHandle(), and isFromTrack().
m_track
Track* lmms::SampleRecordHandle::m_track private
Definition at line 69 of file SampleRecordHandle.h.
Referenced by SampleRecordHandle(), and isFromTrack().
The documentation for this class was generated from the following files:
include/SampleRecordHandle.h
src/core/SampleRecordHandle.cpp