LMMS: Jack::JackInternalClientHandleRequest Struct Reference
Jack::JackInternalClientHandleRequest Struct Reference
InternalClientHandle request.
#include <JackRequest.h>
Public Member Functions
JackInternalClientHandleRequest ()
JackInternalClientHandleRequest (int refnum, const char *client_name)
int Read (detail::JackChannelTransactionInterface *trans)
int Size ()
int Write (detail::JackChannelTransactionInterface *trans)
Public Member Functions inherited from Jack::JackRequest
JackRequest ()
JackRequest (RequestType type)
virtual ~JackRequest ()
virtual int Write (detail::JackChannelTransactionInterface *trans, int size)
Public Attributes
char fName [JACK_CLIENT_NAME_SIZE+1]
int fRefNum
Public Attributes inherited from Jack::JackRequest
int fSize
RequestType fType
Additional Inherited Members
Public Types inherited from Jack::JackRequest
enum RequestType {
kRegisterPort = 1 ,
kUnRegisterPort = 2 ,
kConnectPorts = 3 ,
kDisconnectPorts = 4 ,
kSetTimeBaseClient = 5 ,
kActivateClient = 6 ,
kDeactivateClient = 7 ,
kDisconnectPort = 8 ,
kSetClientCapabilities = 9 ,
kGetPortConnections = 10 ,
kGetPortNConnections = 11 ,
kReleaseTimebase = 12 ,
kSetTimebaseCallback = 13 ,
kSetBufferSize = 20 ,
kSetFreeWheel = 21 ,
kClientCheck = 22 ,
kClientOpen = 23 ,
kClientClose = 24 ,
kConnectNamePorts = 25 ,
kDisconnectNamePorts = 26 ,
kGetInternalClientName = 27 ,
kInternalClientHandle = 28 ,
kInternalClientLoad = 29 ,
kInternalClientUnload = 30 ,
kPortRename = 31 ,
kNotification = 32 ,
kSessionNotify = 33 ,
kSessionReply = 34 ,
kGetClientByUUID = 35 ,
kReserveClientName = 36 ,
kGetUUIDByClient = 37 ,
kClientHasSessionCallback = 38 ,
kComputeTotalLatencies = 39 ,
kPropertyChangeNotify = 40
}
Detailed Description
InternalClientHandle request.
Definition at line 980 of file JackRequest.h.
Constructor & Destructor Documentation
JackInternalClientHandleRequest() [1/2]
Jack::JackInternalClientHandleRequest::JackInternalClientHandleRequest () inline
Definition at line 986 of file JackRequest.h.
References fName, and fRefNum.
JackInternalClientHandleRequest() [2/2]
Jack::JackInternalClientHandleRequest::JackInternalClientHandleRequest (int refnum, const char * client_name) inline
Definition at line 990 of file JackRequest.h.
References Jack::JackRequest::JackRequest(), fName, fRefNum, and Jack::JackRequest::kInternalClientHandle.
Member Function Documentation
Read()
int Jack::JackInternalClientHandleRequest::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackRequest.
Definition at line 997 of file JackRequest.h.
References CheckRes, CheckSize, fName, fRefNum, and Jack::detail::JackChannelTransactionInterface::Read().
Size()
int Jack::JackInternalClientHandleRequest::Size () inline virtual
Reimplemented from Jack::JackRequest.
Definition at line 1011 of file JackRequest.h.
References fName.
Referenced by Write().
Write()
int Jack::JackInternalClientHandleRequest::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackRequest.
Definition at line 1004 of file JackRequest.h.
References CheckRes, fName, fRefNum, Size(), Jack::detail::JackChannelTransactionInterface::Write(), and Jack::JackRequest::Write().
Member Data Documentation
fName
char Jack::JackInternalClientHandleRequest::fName[JACK_CLIENT_NAME_SIZE+1]
Definition at line 984 of file JackRequest.h.
Referenced by JackInternalClientHandleRequest(), JackInternalClientHandleRequest(), Jack::JackRequestDecoder::HandleRequest(), Read(), Size(), and Write().
fRefNum
int Jack::JackInternalClientHandleRequest::fRefNum
Definition at line 983 of file JackRequest.h.
Referenced by JackInternalClientHandleRequest(), JackInternalClientHandleRequest(), Read(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h