LMMS: lmms::MicroTimer Class Reference
lmms::MicroTimer Class Reference
#include <MicroTimer.h>
Public Member Functions
MicroTimer ()
~MicroTimer ()=default
int elapsed () const
void reset ()
Private Types
using time_point = std::chrono::steady_clock::time_point
Private Attributes
time_point begin
Detailed Description
Definition at line 33 of file MicroTimer.h.
Member Typedef Documentation
time_point
using lmms::MicroTimer::time_point = std::chrono::steady_clock::time_point private
Definition at line 35 of file MicroTimer.h.
Constructor & Destructor Documentation
MicroTimer()
lmms::MicroTimer::MicroTimer ()
Definition at line 12 of file MicroTimer.cpp.
References reset().
~MicroTimer()
lmms::MicroTimer::~MicroTimer () default
Member Function Documentation
elapsed()
int lmms::MicroTimer::elapsed () const
Definition at line 22 of file MicroTimer.cpp.
References begin.
Referenced by lmms::AudioDummy::run().
reset()
void lmms::MicroTimer::reset ()
Definition at line 17 of file MicroTimer.cpp.
References begin.
Referenced by MicroTimer(), and lmms::AudioDummy::run().
Member Data Documentation
begin
time_point lmms::MicroTimer::begin private
Definition at line 45 of file MicroTimer.h.
Referenced by elapsed(), and reset().
The documentation for this class was generated from the following files:
include/MicroTimer.h
src/core/MicroTimer.cpp