LMMS: Jack::JackSocketNotifyChannel Class Reference
Jack::JackSocketNotifyChannel Class Reference
JackNotifyChannel using sockets.
#include <JackSocketNotifyChannel.h>
Public Member Functions
JackSocketNotifyChannel ()
void ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2, int *result)
void Close ()
int Open (const char *name)
Private Attributes
JackClientSocket fNotifySocket
Detailed Description
JackNotifyChannel using sockets.
Definition at line 33 of file JackSocketNotifyChannel.h.
Constructor & Destructor Documentation
JackSocketNotifyChannel()
Jack::JackSocketNotifyChannel::JackSocketNotifyChannel () inline
Definition at line 42 of file JackSocketNotifyChannel.h.
Member Function Documentation
ClientNotify()
void Jack::JackSocketNotifyChannel::ClientNotify (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value2, int * result)
Definition at line 50 of file JackSocketNotifyChannel.cpp.
References fNotifySocket, Jack::JackResult::fResult, jack_error, Jack::JackResult::Read(), and Jack::JackResult::Write().
Close()
void Jack::JackSocketNotifyChannel::Close ()
Definition at line 44 of file JackSocketNotifyChannel.cpp.
References fNotifySocket, and jack_log().
Open()
int Jack::JackSocketNotifyChannel::Open (const char * name)
Definition at line 29 of file JackSocketNotifyChannel.cpp.
References fNotifySocket, jack_client_dir, jack_error, jack_log(), and SOCKET_TIME_OUT.
Member Data Documentation
fNotifySocket
JackClientSocket Jack::JackSocketNotifyChannel::fNotifySocket private
Definition at line 38 of file JackSocketNotifyChannel.h.
Referenced by ClientNotify(), Close(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/posix/JackSocketNotifyChannel.h
src/3rdparty/jack2/posix/JackSocketNotifyChannel.cpp