LMMS: Jack::JackPosixSemaphore Class Reference
Jack::JackPosixSemaphore Class Reference
Inter process synchronization using POSIX semaphore.
#include <JackPosixSemaphore.h>
Public Member Functions
JackPosixSemaphore ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Public Member Functions inherited from Jack::detail::JackSynchro
JackSynchro ()
~JackSynchro ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
void SetFlush (bool mode)
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Protected Member Functions
void BuildName (const char *name, const char *server_name, char *res, int size)
Private Attributes
bool fPromiscuous
sem_t * fSemaphore
Additional Inherited Members
Protected Attributes inherited from Jack::detail::JackSynchro
bool fFlush
char fName [SYNC_MAX_NAME_SIZE]
Detailed Description
Inter process synchronization using POSIX semaphore.
Definition at line 36 of file JackPosixSemaphore.h.
Constructor & Destructor Documentation
JackPosixSemaphore()
Jack::JackPosixSemaphore::JackPosixSemaphore ()
Definition at line 43 of file JackPosixSemaphore.cpp.
References Jack::detail::JackSynchro::JackSynchro(), fPromiscuous, fSemaphore, and jack_group2gid().
Member Function Documentation
Allocate()
bool Jack::JackPosixSemaphore::Allocate (const char * name, const char * server_name, int value)
Definition at line 151 of file JackPosixSemaphore.cpp.
References BuildName(), Jack::detail::JackSynchro::fName, fPromiscuous, fSemaphore, jack_error, jack_log(), jack_promiscuous_perms(), SEM_DEFAULT_O, server_name, and SYNC_MAX_NAME_SIZE.
BuildName()
void Jack::JackPosixSemaphore::BuildName (const char * name, const char * server_name, char * res, int size) protected
Definition at line 52 of file JackPosixSemaphore.cpp.
References fPromiscuous, Jack::JackTools::GetUID(), JACK_SEM_PREFIX, Jack::JackTools::RewriteName(), server_name, and SYNC_MAX_NAME_SIZE.
Referenced by Allocate(), and ConnectInput().
Connect()
bool Jack::JackPosixSemaphore::Connect (const char * name, const char * server_name)
Definition at line 198 of file JackPosixSemaphore.cpp.
References ConnectInput(), and server_name.
ConnectInput()
bool Jack::JackPosixSemaphore::ConnectInput (const char * name, const char * server_name)
Definition at line 173 of file JackPosixSemaphore.cpp.
References BuildName(), Jack::detail::JackSynchro::fName, fSemaphore, jack_error, jack_log(), SEM_DEFAULT_O, and server_name.
Referenced by Connect(), and ConnectOutput().
ConnectOutput()
bool Jack::JackPosixSemaphore::ConnectOutput (const char * name, const char * server_name)
Definition at line 203 of file JackPosixSemaphore.cpp.
References ConnectInput(), and server_name.
Destroy()
void Jack::JackPosixSemaphore::Destroy ()
Definition at line 225 of file JackPosixSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, jack_error, and jack_log().
Disconnect()
bool Jack::JackPosixSemaphore::Disconnect ()
Definition at line 208 of file JackPosixSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, jack_error, and jack_log().
Signal()
bool Jack::JackPosixSemaphore::Signal ()
Definition at line 67 of file JackPosixSemaphore.cpp.
References Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
SignalAll()
bool Jack::JackPosixSemaphore::SignalAll ()
Definition at line 86 of file JackPosixSemaphore.cpp.
References Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
TimedWait()
bool Jack::JackPosixSemaphore::TimedWait (long usec)
Definition at line 123 of file JackPosixSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, jack_error, and jack_log().
Wait()
bool Jack::JackPosixSemaphore::Wait ()
Definition at line 105 of file JackPosixSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
Member Data Documentation
fPromiscuous
bool Jack::JackPosixSemaphore::fPromiscuous private
Definition at line 42 of file JackPosixSemaphore.h.
Referenced by JackPosixSemaphore(), Allocate(), and BuildName().
fSemaphore
sem_t* Jack::JackPosixSemaphore::fSemaphore private
Definition at line 41 of file JackPosixSemaphore.h.
Referenced by JackPosixSemaphore(), Allocate(), ConnectInput(), Destroy(), Disconnect(), Signal(), SignalAll(), TimedWait(), and Wait().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/posix/JackPosixSemaphore.h
src/3rdparty/jack2/posix/JackPosixSemaphore.cpp