LMMS: lmms::gui::MainWindow Class Reference
lmms::gui::MainWindow Class Reference
#include <MainWindow.h>
Classes
struct keyModifiers
class MovableQMdiArea
Public Types
enum class SessionState {
Normal ,
Recover
}
Public Slots
void aboutLMMS ()
void autoSave ()
void createNewProject ()
void emptySlot ()
void help ()
void openProject ()
void redo ()
void resetWindowTitle ()
bool saveProject ()
bool saveProjectAs ()
void saveProjectAsDefaultTemplate ()
bool saveProjectAsNewVersion ()
void showSettingsDialog ()
void toggleAutomationEditorWin ()
void toggleControllerRack ()
void toggleFullscreen ()
void toggleMicrotunerWin ()
void toggleMixerWin ()
void togglePatternEditorWin (bool forceShow=false)
void togglePianoRollWin ()
void toggleProjectNotesWin ()
void toggleSongEditorWin ()
void undo ()
void updatePlayPauseIcons ()
void updateUndoRedoButtons ()
Signals
void initProgress (const QString &msg)
void periodicUpdate ()
Public Member Functions
void addSpacingToToolBar (int _size)
int addWidgetToToolBar (QWidget *_w, int _row=-1, int _col=-1)
LMMS_EXPORT SubWindow * addWindowedWidget (QWidget *w, Qt::WindowFlags windowFlags=QFlag(0))
void autoSaveTimerReset (int msec=ConfigManager::inst() -> value("ui", "saveinterval").toInt() *60 *1000)
void clearKeyModifiers ()
bool eventFilter (QObject *watched, QEvent *event) override
int getAutoSaveTimerInterval ()
SessionState getSession ()
bool isShiftPressed ()
bool mayChangeProject (bool stopPlayback)
Asks whether changes made to the project are to be saved.
void refocus ()
void sessionCleanup ()
void setSession (SessionState session)
QWidget * toolBar ()
QMdiArea * workspace ()
Static Public Member Functions
static void restoreWidgetState (QWidget *_w, const QDomElement &_de)
static void saveWidgetState (QWidget *_w, QDomElement &_de)
Static Public Attributes
static const int DEFAULT_AUTO_SAVE_INTERVAL = DEFAULT_SAVE_INTERVAL_MINUTES * 60 * 1000
static const int DEFAULT_SAVE_INTERVAL_MINUTES = 2
static const int m_autoSaveShortTime = 10 * 1000
Protected Member Functions
void closeEvent (QCloseEvent *_ce) override
void focusOutEvent (QFocusEvent *_fe) override
void keyPressEvent (QKeyEvent *_ke) override
void keyReleaseEvent (QKeyEvent *_ke) override
void timerEvent (QTimerEvent *_ev) override
Private Slots
void browseHelp ()
void onExportProject ()
void onExportProjectMidi ()
void onExportProjectTracks ()
void onImportProject ()
void onProjectFileNameChanged ()
void onSongModified ()
void onToggleMetronome ()
void showTool (QAction *_idx)
void updateConfig (QAction *_who)
void updateViewMenu ()
Private Member Functions
MainWindow ()
MainWindow (const MainWindow &)
~MainWindow () override
void exportProject (bool multiExport=false)
void finalize ()
bool guiSaveProject ()
bool guiSaveProjectAs (const QString &filename)
void handleSaveResult (QString const &filename, bool songSavedSuccessfully)
void toggleWindow (QWidget *window, bool forceShow=false)
Private Attributes
int m_autoSaveInterval
QTimer m_autoSaveTimer
struct lmms::gui::MainWindow::keyModifiers m_keyMods
ToolButton * m_metronomeToggle
QAction * m_redoAction
SessionState m_session
QWidget * m_toolBar
QGridLayout * m_toolBarLayout
QList< PluginView * > m_tools
QMenu * m_toolsMenu
QAction * m_undoAction
QBasicTimer m_updateTimer
QMenu * m_viewMenu
MovableQMdiArea * m_workspace
bool maximized
Friends
class GuiApplication
Detailed Description
Definition at line 51 of file MainWindow.h.
Member Enumeration Documentation
SessionState
enum class lmms::gui::MainWindow::SessionState strong
Enumerator
Normal
Recover
Definition at line 115 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow() [1/2]
lmms::gui::MainWindow::MainWindow () private
Definition at line 82 of file MainWindow.cpp.
References autoSave(), lmms::ConfigManager::backgroundPicFile(), DEFAULT_AUTO_SAVE_INTERVAL, lmms::gui::FileItem::defaultFilters(), lmms::ConfigManager::factoryPresetsDir(), lmms::ConfigManager::factoryProjectsDir(), lmms::ConfigManager::factorySamplesDir(), lmms::gui::FileBrowser::Favorites, lmms::embed::getIconPixmap(), lmms::Engine::getSong(), initProgress(), lmms::ConfigManager::inst(), m_autoSaveInterval, m_autoSaveTimer, m_metronomeToggle, m_session, m_toolBar, m_toolBarLayout, m_toolsMenu, m_updateTimer, m_viewMenu, m_workspace, maximized, lmms::gui::FileBrowser::Normal, onProjectFileNameChanged(), onSongModified(), toggleFullscreen(), updatePlayPauseIcons(), lmms::ConfigManager::userPresetsDir(), lmms::ConfigManager::userProjectsDir(), lmms::ConfigManager::userSamplesDir(), and lmms::ConfigManager::value().
Referenced by MainWindow().
MainWindow() [2/2]
lmms::gui::MainWindow::MainWindow (const MainWindow &) private
References MainWindow().
~MainWindow()
lmms::gui::MainWindow::~MainWindow () override private
Definition at line 242 of file MainWindow.cpp.
References lmms::gui::GuiApplication::automationEditor(), lmms::Engine::destroy(), lmms::gui::getGUI(), m_tools, lmms::gui::GuiApplication::pianoRoll(), and lmms::gui::GuiApplication::songEditor().
Member Function Documentation
aboutLMMS
void lmms::gui::MainWindow::aboutLMMS () slot
Definition at line 902 of file MainWindow.cpp.
Referenced by finalize().
addSpacingToToolBar()
void lmms::gui::MainWindow::addSpacingToToolBar (int _size)
Definition at line 547 of file MainWindow.cpp.
References m_toolBarLayout.
Referenced by lmms::gui::SongEditor::SongEditor().
addWidgetToToolBar()
int lmms::gui::MainWindow::addWidgetToToolBar (QWidget * _w, int _row = -1, int _col = -1)
Definition at line 530 of file MainWindow.cpp.
References m_toolBarLayout.
Referenced by lmms::gui::SongEditor::SongEditor().
addWindowedWidget()
SubWindow * lmms::gui::MainWindow::addWindowedWidget (QWidget * w, Qt::WindowFlags windowFlags = QFlag(0))
Definition at line 556 of file MainWindow.cpp.
References m_workspace.
Referenced by lmms::gui::ControllerRackView::ControllerRackView(), lmms::gui::ControllerView::ControllerView(), lmms::gui::EffectView::EffectView(), lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::gui::MidiCCRackView::MidiCCRackView(), lmms::gui::ProjectNotes::ProjectNotes(), lmms::gui::SampleTrackWindow::SampleTrackWindow(), lmms::gui::ToolPluginView::ToolPluginView(), finalize(), lmms::gui::TempoSyncBarModelEditor::showCustom(), and lmms::gui::TempoSyncKnob::showCustom().
autoSave
void lmms::gui::MainWindow::autoSave () slot
Definition at line 1368 of file MainWindow.cpp.
References autoSaveTimerReset(), getAutoSaveTimerInterval(), lmms::Engine::getSong(), lmms::ConfigManager::inst(), lmms::RemotePluginBase::isMainThreadWaiting(), m_autoSaveShortTime, and lmms::Song::saveProjectFile().
Referenced by MainWindow().
autoSaveTimerReset()
void lmms::gui::MainWindow::autoSaveTimerReset (int msec = ConfigManager::inst()-> value("ui", "saveinterval").toInt() * 60 * 1000) inline
Definition at line 99 of file MainWindow.h.
References DEFAULT_AUTO_SAVE_INTERVAL, lmms::ConfigManager::inst(), m_autoSaveShortTime, and m_autoSaveTimer.
Referenced by autoSave().
browseHelp
void lmms::gui::MainWindow::browseHelp () private slot
Definition at line 1357 of file MainWindow.cpp.
Referenced by finalize().
clearKeyModifiers()
void lmms::gui::MainWindow::clearKeyModifiers ()
Definition at line 653 of file MainWindow.cpp.
References m_keyMods.
Referenced by lmms::gui::StringPairDrag::~StringPairDrag(), and focusOutEvent().
closeEvent()
void lmms::gui::MainWindow::closeEvent (QCloseEvent * _ce) override protected
Definition at line 1224 of file MainWindow.cpp.
References lmms::ConfigManager::inst(), mayChangeProject(), and sessionCleanup().
createNewProject
void lmms::gui::MainWindow::createNewProject () slot
Definition at line 740 of file MainWindow.cpp.
References lmms::Song::createNewProject(), lmms::Engine::getSong(), and mayChangeProject().
Referenced by finalize().
emptySlot
void lmms::gui::MainWindow::emptySlot () slot
Definition at line 734 of file MainWindow.cpp.
Referenced by finalize().
eventFilter()
bool lmms::gui::MainWindow::eventFilter (QObject * watched, QEvent * event) override
Definition at line 1255 of file MainWindow.cpp.
exportProject()
void lmms::gui::MainWindow::exportProject (bool multiExport = false) private
Definition at line 1430 of file MainWindow.cpp.
References lmms::ProjectRenderer::Count, lmms::ProjectRenderer::fileEncodeDevices, lmms::gui::VersionedSaveDialog::fileExistsQuery(), lmms::gui::getGUI(), lmms::Engine::getSong(), lmms::ConfigManager::inst(), and lmms::Song::projectFileName().
Referenced by onExportProject(), and onExportProjectTracks().
finalize()
void lmms::gui::MainWindow::finalize () private
Definition at line 262 of file MainWindow.cpp.
References aboutLMMS(), addWindowedWidget(), lmms::Engine::audioEngine(), lmms::gui::SetupDialog::AudioSettings, lmms::gui::GuiApplication::automationEditor(), browseHelp(), lmms::combine(), createNewProject(), emptySlot(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::getPluginFactory(), lmms::Engine::getSong(), help(), lmms::ConfigManager::inst(), lmms::ToolPlugin::instantiate(), lmms::AudioEngine::isAudioDevNameValid(), m_metronomeToggle, m_redoAction, m_toolBar, m_toolBarLayout, m_tools, m_toolsMenu, m_undoAction, m_viewMenu, onExportProject(), onExportProjectMidi(), onExportProjectTracks(), onImportProject(), onToggleMetronome(), openProject(), lmms::gui::GuiApplication::patternEditor(), lmms::gui::GuiApplication::pianoRoll(), redo(), resetWindowTitle(), saveProject(), saveProjectAs(), saveProjectAsDefaultTemplate(), saveProjectAsNewVersion(), lmms::ConfigManager::setValue(), showSettingsDialog(), showTool(), lmms::gui::GuiApplication::songEditor(), toggleAutomationEditorWin(), toggleControllerRack(), toggleMicrotunerWin(), toggleMixerWin(), togglePatternEditorWin(), togglePianoRollWin(), toggleProjectNotesWin(), toggleSongEditorWin(), lmms::Plugin::Tool, undo(), updateConfig(), updateUndoRedoButtons(), updateViewMenu(), and workspace().
focusOutEvent()
void lmms::gui::MainWindow::focusOutEvent (QFocusEvent * _fe) override protected
Definition at line 1267 of file MainWindow.cpp.
References clearKeyModifiers().
getAutoSaveTimerInterval()
int lmms::gui::MainWindow::getAutoSaveTimerInterval () inline
Definition at line 110 of file MainWindow.h.
References m_autoSaveTimer.
Referenced by autoSave().
getSession()
SessionState lmms::gui::MainWindow::getSession () inline
Definition at line 126 of file MainWindow.h.
References m_session.
Referenced by mayChangeProject(), resetWindowTitle(), saveProject(), and saveProjectAs().
guiSaveProject()
bool lmms::gui::MainWindow::guiSaveProject () private
Definition at line 1530 of file MainWindow.cpp.
References lmms::Engine::getSong(), lmms::Song::guiSaveProject(), handleSaveResult(), and lmms::Song::projectFileName().
Referenced by saveProject().
guiSaveProjectAs()
bool lmms::gui::MainWindow::guiSaveProjectAs (const QString & filename) private
Definition at line 1539 of file MainWindow.cpp.
References lmms::Engine::getSong(), lmms::Song::guiSaveProjectAs(), and handleSaveResult().
Referenced by saveProjectAs(), and saveProjectAsNewVersion().
handleSaveResult()
void lmms::gui::MainWindow::handleSaveResult (QString const & filename, bool songSavedSuccessfully) private
Definition at line 1514 of file MainWindow.cpp.
References lmms::ConfigManager::addRecentlyOpenedProject(), lmms::gui::TextFloat::displayMessage(), lmms::embed::getIconPixmap(), lmms::ConfigManager::inst(), and resetWindowTitle().
Referenced by guiSaveProject(), and guiSaveProjectAs().
help
void lmms::gui::MainWindow::help () slot
Definition at line 910 of file MainWindow.cpp.
Referenced by finalize().
initProgress
void lmms::gui::MainWindow::initProgress (const QString & msg) signal
Referenced by MainWindow().
isShiftPressed()
bool lmms::gui::MainWindow::isShiftPressed () inline
Definition at line 137 of file MainWindow.h.
References m_keyMods.
keyPressEvent()
void lmms::gui::MainWindow::keyPressEvent (QKeyEvent * _ke) override protected
Definition at line 1279 of file MainWindow.cpp.
References lmms::gui::PianoView::keyPressEvent(), lmms::gui::Editor::lastPlayedEditor(), m_keyMods, lmms::gui::InstrumentTrackWindow::pianoView(), lmms::gui::Editor::togglePause(), lmms::gui::Editor::togglePlayStop(), and lmms::gui::InstrumentTrackView::topLevelInstrumentTrackWindow().
keyReleaseEvent()
void lmms::gui::MainWindow::keyReleaseEvent (QKeyEvent * _ke) override protected
Definition at line 1314 of file MainWindow.cpp.
References m_keyMods, and lmms::gui::InstrumentTrackView::topLevelInstrumentTrackWindow().
mayChangeProject()
bool lmms::gui::MainWindow::mayChangeProject (bool stopPlayback)
Asks whether changes made to the project are to be saved.
Opens a dialog giving the user the choice to (a) confirm his choice (such as opening a new file), (b) save the current project before proceeding or (c) cancel the process.
Every function that replaces the current file (e.g. creates new file, opens another file...) must call this before and may only proceed if this function returns true.
Parameters
stopPlayback whether playback should be stopped upon prompting. If set to false, the caller should ensure that Engine::getSong()->stop() is called before unloading/loading a song.
Returns
true if the user allows the software to proceed, false if they cancel the action.
Definition at line 599 of file MainWindow.cpp.
References getSession(), lmms::Engine::getSong(), Recover, saveProject(), sessionCleanup(), and lmms::Song::stop().
Referenced by closeEvent(), createNewProject(), and openProject().
onExportProject
void lmms::gui::MainWindow::onExportProject () private slot
Definition at line 1548 of file MainWindow.cpp.
References exportProject().
Referenced by finalize().
onExportProjectMidi
void lmms::gui::MainWindow::onExportProjectMidi () private slot
Definition at line 1391 of file MainWindow.cpp.
References lmms::Song::exportProjectMidi(), lmms::Engine::getSong(), lmms::ConfigManager::inst(), and lmms::Song::projectFileName().
Referenced by finalize().
onExportProjectTracks
void lmms::gui::MainWindow::onExportProjectTracks () private slot
Definition at line 1553 of file MainWindow.cpp.
References exportProject().
Referenced by finalize().
onImportProject
void lmms::gui::MainWindow::onImportProject () private slot
Definition at line 1558 of file MainWindow.cpp.
References lmms::Engine::getSong(), lmms::ImportFilter::import(), lmms::ConfigManager::inst(), and lmms::Song::setLoadOnLaunch().
Referenced by finalize().
onProjectFileNameChanged
void lmms::gui::MainWindow::onProjectFileNameChanged () private slot
Definition at line 1595 of file MainWindow.cpp.
References resetWindowTitle().
Referenced by MainWindow().
onSongModified
void lmms::gui::MainWindow::onSongModified () private slot
Definition at line 1583 of file MainWindow.cpp.
References resetWindowTitle().
Referenced by MainWindow().
onToggleMetronome
void lmms::gui::MainWindow::onToggleMetronome () private slot
Definition at line 1148 of file MainWindow.cpp.
References lmms::Engine::getSong(), m_metronomeToggle, lmms::Song::metronome(), and lmms::Metronome::setActive().
Referenced by finalize().
openProject
void lmms::gui::MainWindow::openProject () slot
Definition at line 751 of file MainWindow.cpp.
References lmms::Engine::getSong(), lmms::ConfigManager::inst(), lmms::Song::loadProject(), mayChangeProject(), and lmms::Song::stop().
Referenced by finalize().
periodicUpdate
void lmms::gui::MainWindow::periodicUpdate () signal
Referenced by lmms::gui::MixerView::MixerView(), and timerEvent().
redo
void lmms::gui::MainWindow::redo () slot
Definition at line 1216 of file MainWindow.cpp.
References lmms::Engine::projectJournal(), and lmms::ProjectJournal::redo().
Referenced by finalize().
refocus()
void lmms::gui::MainWindow::refocus ()
Definition at line 965 of file MainWindow.cpp.
References lmms::gui::getGUI().
Referenced by lmms::gui::Editor::closeEvent(), and toggleWindow().
resetWindowTitle
void lmms::gui::MainWindow::resetWindowTitle () slot
Definition at line 573 of file MainWindow.cpp.
References getSession(), lmms::Engine::getSong(), and Recover.
Referenced by lmms::gui::ExportProjectDialog::accept(), finalize(), handleSaveResult(), onProjectFileNameChanged(), and onSongModified().
restoreWidgetState()
void lmms::gui::MainWindow::restoreWidgetState (QWidget * _w, const QDomElement & _de) static
Definition at line 694 of file MainWindow.cpp.
Referenced by lmms::gui::AutomationEditor::loadSettings(), lmms::gui::ControllerRackView::loadSettings(), lmms::gui::InstrumentTrackWindow::loadSettings(), lmms::gui::MicrotunerConfig::loadSettings(), lmms::gui::MixerView::loadSettings(), lmms::gui::PatternEditor::loadSettings(), lmms::gui::PianoRollWindow::loadSettings(), lmms::gui::ProjectNotes::loadSettings(), lmms::gui::SampleTrackWindow::loadSettings(), lmms::gui::SongEditor::loadSettings(), and lmms::gui::TrackContainerView::loadSettings().
saveProject
bool lmms::gui::MainWindow::saveProject () slot
Definition at line 775 of file MainWindow.cpp.
References getSession(), lmms::Engine::getSong(), guiSaveProject(), Recover, saveProjectAs(), and sessionCleanup().
Referenced by finalize(), and mayChangeProject().
saveProjectAs
bool lmms::gui::MainWindow::saveProjectAs () slot
Definition at line 795 of file MainWindow.cpp.
References lmms::gui::VersionedSaveDialog::fileExistsQuery(), getSession(), lmms::Engine::getSong(), guiSaveProjectAs(), lmms::ConfigManager::inst(), lmms::Song::projectFileName(), Recover, sessionCleanup(), and lmms::ConfigManager::value().
Referenced by finalize(), saveProject(), and saveProjectAsNewVersion().
saveProjectAsDefaultTemplate
void lmms::gui::MainWindow::saveProjectAsDefaultTemplate () slot
Definition at line 870 of file MainWindow.cpp.
References lmms::Engine::getSong(), lmms::ConfigManager::inst(), lmms::Song::saveProjectFile(), and lmms::ConfigManager::userTemplateDir().
Referenced by finalize().
saveProjectAsNewVersion
bool lmms::gui::MainWindow::saveProjectAsNewVersion () slot
Definition at line 851 of file MainWindow.cpp.
References lmms::gui::VersionedSaveDialog::changeFileNameVersion(), lmms::Engine::getSong(), guiSaveProjectAs(), lmms::Song::projectFileName(), and saveProjectAs().
Referenced by finalize().
saveWidgetState()
void lmms::gui::MainWindow::saveWidgetState (QWidget * _w, QDomElement & _de) static
Definition at line 663 of file MainWindow.cpp.
Referenced by lmms::gui::AutomationEditor::saveSettings(), lmms::gui::ControllerRackView::saveSettings(), lmms::gui::InstrumentTrackWindow::saveSettings(), lmms::gui::MicrotunerConfig::saveSettings(), lmms::gui::MixerView::saveSettings(), lmms::gui::PatternEditor::saveSettings(), lmms::gui::PianoRollWindow::saveSettings(), lmms::gui::ProjectNotes::saveSettings(), lmms::gui::SampleTrackWindow::saveSettings(), lmms::gui::SongEditor::saveSettings(), and lmms::gui::TrackContainerView::saveSettings().
sessionCleanup()
void lmms::gui::MainWindow::sessionCleanup ()
Definition at line 1245 of file MainWindow.cpp.
References lmms::ConfigManager::inst(), Normal, and setSession().
Referenced by closeEvent(), mayChangeProject(), saveProject(), and saveProjectAs().
setSession()
void lmms::gui::MainWindow::setSession (SessionState session) inline
Definition at line 121 of file MainWindow.h.
References m_session.
Referenced by sessionCleanup().
showSettingsDialog
void lmms::gui::MainWindow::showSettingsDialog () slot
Definition at line 893 of file MainWindow.cpp.
Referenced by finalize().
showTool
void lmms::gui::MainWindow::showTool (QAction * _idx) private slot
Definition at line 1346 of file MainWindow.cpp.
References m_tools, and m_toolsMenu.
Referenced by finalize().
timerEvent()
void lmms::gui::MainWindow::timerEvent (QTimerEvent * _ev) override protected
Definition at line 1337 of file MainWindow.cpp.
References periodicUpdate().
toggleAutomationEditorWin
void lmms::gui::MainWindow::toggleAutomationEditorWin () slot
Definition at line 1019 of file MainWindow.cpp.
References lmms::gui::getGUI(), and toggleWindow().
Referenced by finalize(), and updateViewMenu().
toggleControllerRack
void lmms::gui::MainWindow::toggleControllerRack () slot
Definition at line 1156 of file MainWindow.cpp.
References lmms::gui::getGUI(), and toggleWindow().
Referenced by finalize(), and updateViewMenu().
toggleFullscreen
void lmms::gui::MainWindow::toggleFullscreen () slot
Definition at line 945 of file MainWindow.cpp.
References maximized.
Referenced by MainWindow(), and updateViewMenu().
toggleMicrotunerWin
void lmms::gui::MainWindow::toggleMicrotunerWin () slot
Definition at line 1034 of file MainWindow.cpp.
References lmms::gui::getGUI(), and toggleWindow().
Referenced by finalize().
toggleMixerWin
void lmms::gui::MainWindow::toggleMixerWin () slot
Definition at line 1027 of file MainWindow.cpp.
References lmms::gui::getGUI(), and toggleWindow().
Referenced by finalize(), and updateViewMenu().
togglePatternEditorWin
void lmms::gui::MainWindow::togglePatternEditorWin (bool forceShow = false) slot
Definition at line 987 of file MainWindow.cpp.
References lmms::gui::getGUI(), and toggleWindow().
Referenced by lmms::gui::PatternTrackView::clickedTrackLabel(), finalize(), lmms::gui::PatternClipView::openInPatternEditor(), and updateViewMenu().
togglePianoRollWin
void lmms::gui::MainWindow::togglePianoRollWin () slot
Definition at line 1011 of file MainWindow.cpp.
References lmms::gui::getGUI(), and toggleWindow().
Referenced by finalize(), and updateViewMenu().
toggleProjectNotesWin
void lmms::gui::MainWindow::toggleProjectNotesWin () slot
Definition at line 1003 of file MainWindow.cpp.
References lmms::gui::getGUI(), and toggleWindow().
Referenced by finalize(), and updateViewMenu().
toggleSongEditorWin
void lmms::gui::MainWindow::toggleSongEditorWin () slot
Definition at line 995 of file MainWindow.cpp.
References lmms::gui::getGUI(), and toggleWindow().
Referenced by finalize(), and updateViewMenu().
toggleWindow()
void lmms::gui::MainWindow::toggleWindow (QWidget * window, bool forceShow = false) private
Definition at line 924 of file MainWindow.cpp.
References m_workspace, and refocus().
Referenced by toggleAutomationEditorWin(), toggleControllerRack(), toggleMicrotunerWin(), toggleMixerWin(), togglePatternEditorWin(), togglePianoRollWin(), toggleProjectNotesWin(), and toggleSongEditorWin().
toolBar()
QWidget * lmms::gui::MainWindow::toolBar () inline
Definition at line 60 of file MainWindow.h.
References m_toolBar.
Referenced by lmms::gui::SongEditor::SongEditor().
undo
void lmms::gui::MainWindow::undo () slot
Definition at line 1208 of file MainWindow.cpp.
References lmms::Engine::projectJournal(), and lmms::ProjectJournal::undo().
Referenced by finalize().
updateConfig
void lmms::gui::MainWindow::updateConfig (QAction * _who) private slot
Definition at line 1115 of file MainWindow.cpp.
References lmms::ConfigManager::inst(), and lmms::ConfigManager::setValue().
Referenced by finalize().
updatePlayPauseIcons
void lmms::gui::MainWindow::updatePlayPauseIcons () slot
Definition at line 1164 of file MainWindow.cpp.
References lmms::Song::Song, lmms::Song::AutomationClip, lmms::gui::GuiApplication::automationEditor(), lmms::gui::getGUI(), lmms::Engine::getSong(), lmms::Song::MidiClip, lmms::Song::Pattern, lmms::gui::GuiApplication::patternEditor(), lmms::gui::GuiApplication::pianoRoll(), lmms::gui::Editor::setPauseIcon(), and lmms::gui::GuiApplication::songEditor().
Referenced by MainWindow().
updateUndoRedoButtons
void lmms::gui::MainWindow::updateUndoRedoButtons () slot
Definition at line 1198 of file MainWindow.cpp.
References m_redoAction, m_undoAction, and lmms::Engine::projectJournal().
Referenced by finalize().
updateViewMenu
void lmms::gui::MainWindow::updateViewMenu () private slot
Definition at line 1042 of file MainWindow.cpp.
References lmms::embed::getIconPixmap(), lmms::ConfigManager::inst(), m_viewMenu, toggleAutomationEditorWin(), toggleControllerRack(), toggleFullscreen(), toggleMixerWin(), togglePatternEditorWin(), togglePianoRollWin(), toggleProjectNotesWin(), and toggleSongEditorWin().
Referenced by finalize().
workspace()
QMdiArea * lmms::gui::MainWindow::workspace () inline
Definition at line 55 of file MainWindow.h.
References m_workspace.
Referenced by lmms::gui::SongEditorWindow::adjustUiAfterProjectLoad(), finalize(), and lmms::gui::FileBrowserTreeWidget::sendToActiveInstrumentTrack().
Friends And Related Symbol Documentation
GuiApplication
friend class GuiApplication friend
Definition at line 245 of file MainWindow.h.
References GuiApplication.
Referenced by GuiApplication.
Member Data Documentation
DEFAULT_AUTO_SAVE_INTERVAL
const int lmms::gui::MainWindow::DEFAULT_AUTO_SAVE_INTERVAL = DEFAULT_SAVE_INTERVAL_MINUTES * 60 * 1000 static
Definition at line 95 of file MainWindow.h.
Referenced by MainWindow(), and autoSaveTimerReset().
DEFAULT_SAVE_INTERVAL_MINUTES
const int lmms::gui::MainWindow::DEFAULT_SAVE_INTERVAL_MINUTES = 2 static
Definition at line 94 of file MainWindow.h.
Referenced by lmms::gui::SetupDialog::resetAutoSave().
m_autoSaveInterval
int lmms::gui::MainWindow::m_autoSaveInterval private
Definition at line 243 of file MainWindow.h.
Referenced by MainWindow().
m_autoSaveShortTime
const int lmms::gui::MainWindow::m_autoSaveShortTime = 10 * 1000 static
Definition at line 97 of file MainWindow.h.
Referenced by autoSave(), and autoSaveTimerReset().
m_autoSaveTimer
QTimer lmms::gui::MainWindow::m_autoSaveTimer private
Definition at line 242 of file MainWindow.h.
Referenced by MainWindow(), autoSaveTimerReset(), and getAutoSaveTimerInterval().
m_keyMods
struct lmms::gui::MainWindow::keyModifiers lmms::gui::MainWindow::m_keyMods private
Referenced by clearKeyModifiers(), isShiftPressed(), keyPressEvent(), and keyReleaseEvent().
m_metronomeToggle
ToolButton* lmms::gui::MainWindow::m_metronomeToggle private
Definition at line 249 of file MainWindow.h.
Referenced by MainWindow(), finalize(), and onToggleMetronome().
m_redoAction
QAction* lmms::gui::MainWindow::m_redoAction private
Definition at line 238 of file MainWindow.h.
Referenced by finalize(), and updateUndoRedoButtons().
m_session
SessionState lmms::gui::MainWindow::m_session private
Definition at line 251 of file MainWindow.h.
Referenced by MainWindow(), getSession(), and setSession().
m_toolBar
QWidget* lmms::gui::MainWindow::m_toolBar private
Definition at line 220 of file MainWindow.h.
Referenced by MainWindow(), finalize(), and toolBar().
m_toolBarLayout
QGridLayout* lmms::gui::MainWindow::m_toolBarLayout private
Definition at line 221 of file MainWindow.h.
Referenced by MainWindow(), addSpacingToToolBar(), addWidgetToToolBar(), and finalize().
m_tools
QList<PluginView *> lmms::gui::MainWindow::m_tools private
Definition at line 239 of file MainWindow.h.
Referenced by ~MainWindow(), finalize(), and showTool().
m_toolsMenu
QMenu* lmms::gui::MainWindow::m_toolsMenu private
Definition at line 236 of file MainWindow.h.
Referenced by MainWindow(), finalize(), and showTool().
m_undoAction
QAction* lmms::gui::MainWindow::m_undoAction private
Definition at line 237 of file MainWindow.h.
Referenced by finalize(), and updateUndoRedoButtons().
m_updateTimer
QBasicTimer lmms::gui::MainWindow::m_updateTimer private
Definition at line 241 of file MainWindow.h.
Referenced by MainWindow().
m_viewMenu
QMenu* lmms::gui::MainWindow::m_viewMenu private
Definition at line 247 of file MainWindow.h.
Referenced by MainWindow(), finalize(), and updateViewMenu().
m_workspace
MovableQMdiArea* lmms::gui::MainWindow::m_workspace private
Definition at line 218 of file MainWindow.h.
Referenced by MainWindow(), addWindowedWidget(), toggleWindow(), and workspace().
maximized
bool lmms::gui::MainWindow::maximized private
Definition at line 253 of file MainWindow.h.
Referenced by MainWindow(), and toggleFullscreen().
The documentation for this class was generated from the following files:
include/MainWindow.h
src/gui/MainWindow.cpp