LMMS: lmms::AudioEngineWorkerThread Class Reference
lmms::AudioEngineWorkerThread Class Reference
#include <AudioEngineWorkerThread.h>
Classes
class JobQueue
Public Member Functions
AudioEngineWorkerThread (AudioEngine *audioEngine)
~AudioEngineWorkerThread () override
virtual void quit ()
Static Public Member Functions
static void addJob (ThreadableJob *_job)
template<typename T>
static void fillJobQueue (const T &_vec, JobQueue::OperationMode _opMode=JobQueue::OperationMode::Static)
static void resetJobQueue (JobQueue::OperationMode _opMode=JobQueue::OperationMode::Static)
static void startAndWaitForJobs ()
Private Member Functions
void run () override
Private Attributes
volatile bool m_quit
Static Private Attributes
static JobQueue globalJobQueue
static QWaitCondition * queueReadyWaitCond = nullptr
static QList< AudioEngineWorkerThread * > workerThreads
Detailed Description
Definition at line 40 of file AudioEngineWorkerThread.h.
Constructor & Destructor Documentation
AudioEngineWorkerThread()
lmms::AudioEngineWorkerThread::AudioEngineWorkerThread (AudioEngine * audioEngine)
Definition at line 116 of file AudioEngineWorkerThread.cpp.
References m_quit, queueReadyWaitCond, resetJobQueue(), and workerThreads.
~AudioEngineWorkerThread()
lmms::AudioEngineWorkerThread::~AudioEngineWorkerThread () override
Definition at line 137 of file AudioEngineWorkerThread.cpp.
References workerThreads.
Member Function Documentation
addJob()
void lmms::AudioEngineWorkerThread::addJob (ThreadableJob * _job) inline static
Definition at line 91 of file AudioEngineWorkerThread.h.
References globalJobQueue.
Referenced by fillJobQueue(), lmms::MixerChannel::incrementDeps(), and lmms::Mixer::masterMix().
fillJobQueue()
template<typename T> void lmms::AudioEngineWorkerThread::fillJobQueue (const T & _vec, JobQueue::OperationMode _opMode = JobQueue::OperationMode::Static) inline static
Definition at line 99 of file AudioEngineWorkerThread.h.
References addJob(), resetJobQueue(), and lmms::AudioEngineWorkerThread::JobQueue::Static.
Referenced by lmms::AudioEngine::renderStageEffects(), and lmms::AudioEngine::renderStageInstruments().
quit()
void lmms::AudioEngineWorkerThread::quit () virtual
Definition at line 145 of file AudioEngineWorkerThread.cpp.
References m_quit, and resetJobQueue().
resetJobQueue()
void lmms::AudioEngineWorkerThread::resetJobQueue (JobQueue::OperationMode _opMode = JobQueue::OperationMode::Static) inline static
Definition at line 85 of file AudioEngineWorkerThread.h.
References globalJobQueue, and lmms::AudioEngineWorkerThread::JobQueue::Static.
Referenced by AudioEngineWorkerThread(), fillJobQueue(), lmms::Mixer::masterMix(), and quit().
run()
void lmms::AudioEngineWorkerThread::run () override private
Definition at line 167 of file AudioEngineWorkerThread.cpp.
References lmms::disable_denormals(), globalJobQueue, m_quit, and queueReadyWaitCond.
startAndWaitForJobs()
void lmms::AudioEngineWorkerThread::startAndWaitForJobs () static
Definition at line 154 of file AudioEngineWorkerThread.cpp.
References globalJobQueue, and queueReadyWaitCond.
Referenced by lmms::AudioEngine::~AudioEngine(), lmms::Mixer::masterMix(), lmms::AudioEngine::renderStageEffects(), and lmms::AudioEngine::renderStageInstruments().
Member Data Documentation
globalJobQueue
AudioEngineWorkerThread::JobQueue lmms::AudioEngineWorkerThread::globalJobQueue static private
Definition at line 115 of file AudioEngineWorkerThread.h.
Referenced by addJob(), resetJobQueue(), run(), and startAndWaitForJobs().
m_quit
volatile bool lmms::AudioEngineWorkerThread::m_quit private
Definition at line 119 of file AudioEngineWorkerThread.h.
Referenced by AudioEngineWorkerThread(), quit(), and run().
queueReadyWaitCond
QWaitCondition * lmms::AudioEngineWorkerThread::queueReadyWaitCond = nullptr static private
Definition at line 116 of file AudioEngineWorkerThread.h.
Referenced by AudioEngineWorkerThread(), run(), and startAndWaitForJobs().
workerThreads
QList< AudioEngineWorkerThread * > lmms::AudioEngineWorkerThread::workerThreads static private
Definition at line 117 of file AudioEngineWorkerThread.h.
Referenced by AudioEngineWorkerThread(), and ~AudioEngineWorkerThread().
The documentation for this class was generated from the following files:
include/AudioEngineWorkerThread.h
src/core/AudioEngineWorkerThread.cpp