LMMS: lmms::AudioResampler Class Reference
lmms::AudioResampler Class Reference
A utility class for resampling interleaved audio buffers using various resampling algorithms.
#include <AudioResampler.h>
Classes
struct Result
Result of a resampling operation.
struct StateDeleter
Public Types
enum class Mode {
ZOH ,
Linear ,
SincFastest ,
SincMedium ,
SincBest
}
Defines the resampling method to use.
Public Member Functions
AudioResampler (Mode mode, ch_cnt_t channels=2)
Constructs an AudioResampler instance.
auto channels () const -> ch_cnt_t
auto mode () const -> Mode
auto process (InterleavedBufferView< const float > input, InterleavedBufferView< float > output) -> Result
Process a block of interleaved audio input from input and resample it into output.
auto ratio () const -> double
void reset ()
Resets the internal resampler state.
void setRatio (double ratio)
Sets the resampling ratio to ratio.
void setRatio (sample_rate_t input, sample_rate_t output)
Sets the resampling ratio to output / input.
Private Attributes
ch_cnt_t m_channels = 0
int m_error = 0
Mode m_mode
double m_ratio = 1.0
std::unique_ptr< void, StateDeleter > m_state
Detailed Description
A utility class for resampling interleaved audio buffers using various resampling algorithms.
This class provides support for zero-order hold, linear, and several levels of sinc-based resampling.
Definition at line 40 of file AudioResampler.h.
Member Enumeration Documentation
Mode
enum class lmms::AudioResampler::Mode strong
Defines the resampling method to use.
Enumerator
ZOH
Zero Order Hold (nearest-neighbor) interpolation.
Linear
Linear interpolation.
SincFastest
Fastest sinc-based resampling.
SincMedium
Medium quality sinc-based resampling.
SincBest
Highest quality sinc-based resampling.
Definition at line 47 of file AudioResampler.h.
Constructor & Destructor Documentation
AudioResampler()
lmms::AudioResampler::AudioResampler (Mode mode, ch_cnt_t channels = 2)
Constructs an AudioResampler instance.
Parameters
mode The resampling mode to use.
channels Number of audio channels. Defaults to 2 (stereo).
Definition at line 54 of file AudioResampler.cpp.
References channels(), m_channels, m_error, m_mode, m_state, and mode().
Member Function Documentation
channels()
auto lmms::AudioResampler::channels () const->ch_cnt_t inline
Returns
the number of channels expected by the resampler.
Definition at line 112 of file AudioResampler.h.
References m_channels.
Referenced by AudioResampler().
mode()
auto lmms::AudioResampler::mode () const->Mode inline
Returns
the interpolation mode used by this resampler.
Definition at line 115 of file AudioResampler.h.
References m_mode.
Referenced by AudioResampler().
process()
auto lmms::AudioResampler::process (InterleavedBufferView< const float > input, InterleavedBufferView< float > output)->Result nodiscard
Process a block of interleaved audio input from input and resample it into output.
Parameters
input The interleaved audio input.
output The interleaved audio output.
Exceptions
`std::invalid_argument` if a channel mismatch has been detected.
`std::runtime_error` if the resampling process has failed.
Remarks
This utility class does not cache the input and output buffers, making it stateless. In other words, input is directly resampled into the output.
Returns
the result of the resampling process. See Result for more details.
Definition at line 63 of file AudioResampler.cpp.
References m_channels, m_error, m_ratio, and m_state.
Referenced by lmms::Sample::play().
ratio()
auto lmms::AudioResampler::ratio () const->double inline
Returns
the resampling ratio.
Definition at line 109 of file AudioResampler.h.
References m_ratio.
Referenced by setRatio().
reset()
void lmms::AudioResampler::reset ()
Resets the internal resampler state.
Useful when working with unreleated pieces of audio.
Definition at line 89 of file AudioResampler.cpp.
References m_error, and m_state.
setRatio() [1/2]
void lmms::AudioResampler::setRatio (double ratio) inline
Sets the resampling ratio to ratio.
Parameters
ratio Output sample rate divided by input sample rate.
Definition at line 99 of file AudioResampler.h.
References m_ratio, and ratio().
Referenced by lmms::Sample::play().
setRatio() [2/2]
void lmms::AudioResampler::setRatio (sample_rate_t input, sample_rate_t output) inline
Sets the resampling ratio to output / input.
Parameters
input Input sample rate.
output Output sample rate.
Definition at line 106 of file AudioResampler.h.
References m_ratio.
Member Data Documentation
m_channels
ch_cnt_t lmms::AudioResampler::m_channels = 0 private
Definition at line 121 of file AudioResampler.h.
Referenced by AudioResampler(), channels(), and process().
m_error
int lmms::AudioResampler::m_error = 0 private
Definition at line 123 of file AudioResampler.h.
Referenced by AudioResampler(), process(), and reset().
m_mode
Mode lmms::AudioResampler::m_mode private
Definition at line 120 of file AudioResampler.h.
Referenced by AudioResampler(), and mode().
m_ratio
double lmms::AudioResampler::m_ratio = 1.0 private
Definition at line 122 of file AudioResampler.h.
Referenced by process(), ratio(), setRatio(), and setRatio().
m_state
std::unique_ptr<void, StateDeleter> lmms::AudioResampler::m_state private
Definition at line 119 of file AudioResampler.h.
Referenced by AudioResampler(), process(), and reset().
The documentation for this class was generated from the following files:
include/AudioResampler.h
src/core/AudioResampler.cpp