LMMS: src/3rdparty/jack2/common/JackTime.h File Reference
JackTime.h File Reference
#include "JackCompilerDeps.h"
#include "JackTypes.h"
Functions
const char * ClockSourceName (jack_timer_type_t source)
SERVER_EXPORT void EndTime ()
SERVER_EXPORT jack_time_t GetMicroSeconds (void)
SERVER_EXPORT void InitTime ()
SERVER_EXPORT void JackSleep (long usec)
void SetClockSource (jack_timer_type_t source)
Function Documentation
ClockSourceName()
const char * ClockSourceName (jack_timer_type_t source)
EndTime()
SERVER_EXPORT void EndTime ()
References SERVER_EXPORT.
Referenced by Jack::JackServer::Close(), and Jack::JackLibGlobals::Destroy().
GetMicroSeconds()
SERVER_EXPORT jack_time_t GetMicroSeconds (void)
References SERVER_EXPORT.
Referenced by Jack::JackDriver::CycleTakeBeginTime(), Jack::JackDriver::CycleTakeEndTime(), Jack::JackMidiAsyncWaitQueue::DequeueEvent(), Jack::JackWinMMEInputPort::EnqueueMessage(), Jack::JackALSARawMidiDriver::Execute(), Jack::JackBoomerDriver::JackBoomerDriverInput::Execute(), Jack::JackBoomerDriver::JackBoomerDriverOutput::Execute(), Jack::JackWinMMEOutputPort::Execute(), Jack::JackAlsaDriver::frame_time(), Jack::GetCurrentFrame(), Jack::JackTransportEngine::GetCurrentFrame(), jack_frame_time(), jack_frames_since_cycle_start(), jack_get_time(), Jack::JackNetMaster::Process(), Jack::JackTimedDriver::ProcessWait(), Jack::JackAudioAdapterInterface::PullAndPush(), Jack::JackAudioAdapterInterface::PushAndPull(), Jack::JackNetDriver::Read(), Jack::JackOSSDriver::Read(), Jack::JackPortAudioDriver::Render(), Jack::JackConnectionManager::ResumeRefNum(), Jack::JackWinMMEInputPort::Start(), Jack::JackConnectionManager::SuspendRefNum(), Jack::JackDebugClient::TimeCallback(), Jack::JackOSSDriver::WaitAndSync(), Jack::JackNetDriver::Write(), and Jack::JackOSSDriver::Write().
InitTime()
SERVER_EXPORT void InitTime ()
References SERVER_EXPORT.
Referenced by Jack::JackLibGlobals::Init(), and Jack::JackServer::Open().
JackSleep()
SERVER_EXPORT void JackSleep (long usec)
References SERVER_EXPORT.
Referenced by Jack::JackTransportEngine::CopyPosition(), Jack::JackSessionNotifyResult::GetCommands(), Jack::JackProxyDriver::Initialize(), Jack::JackDriver::LoadConnections(), Jack::JackTimedDriver::ProcessWait(), server_connect(), server_connect(), Jack::JackMessageBuffer::SetInitCallback(), Jack::JackAndroidThread::StartSync(), Jack::JackPosixThread::StartSync(), Jack::JackWinThread::StartSync(), and WaitGraphChange().
SetClockSource()
void SetClockSource (jack_timer_type_t source)
Referenced by Jack::JackLibClient::Open(), and Jack::JackServer::Open().