LMMS: Jack::JackClientSocket Class Reference
Jack::JackClientSocket Class Reference
Client socket.
#include <JackSocket.h>
Public Member Functions
JackClientSocket ()
JackClientSocket (int socket)
int Close ()
int Connect (const char *dir, const char *name, int which)
int GetFd ()
int Read (void *data, int len)
void SetNonBlocking (bool onoff)
void SetReadTimeOut (long sec)
void SetWriteTimeOut (long sec)
int Write (void *data, int len)
Public Member Functions inherited from Jack::detail::JackClientRequestInterface
JackClientRequestInterface ()
virtual ~JackClientRequestInterface ()
Public Member Functions inherited from Jack::detail::JackChannelTransactionInterface
JackChannelTransactionInterface ()
virtual ~JackChannelTransactionInterface ()
Public Member Functions inherited from Jack::detail::JackRequestInterface
JackRequestInterface ()
virtual ~JackRequestInterface ()
Private Attributes
bool fPromiscuous
int fPromiscuousGid
int fSocket
int fTimeOut
Detailed Description
Client socket.
Definition at line 41 of file JackSocket.h.
Constructor & Destructor Documentation
JackClientSocket() [1/2]
Jack::JackClientSocket::JackClientSocket ()
Definition at line 44 of file JackSocket.cpp.
References Jack::detail::JackClientRequestInterface::JackClientRequestInterface(), fPromiscuous, fPromiscuousGid, fSocket, fTimeOut, and jack_group2gid().
JackClientSocket() [2/2]
Jack::JackClientSocket::JackClientSocket (int socket)
Definition at line 51 of file JackSocket.cpp.
References Jack::detail::JackClientRequestInterface::JackClientRequestInterface(), fPromiscuous, fPromiscuousGid, fSocket, and fTimeOut.
Member Function Documentation
Close()
int Jack::JackClientSocket::Close () virtual
Reimplemented from Jack::detail::JackClientRequestInterface.
Definition at line 154 of file JackSocket.cpp.
References fSocket, and jack_log().
Referenced by Jack::JackSocketServerChannel::ClientKill(), Jack::JackSocketServerChannel::ClientRemove(), and Jack::JackSocketServerChannel::Close().
Connect()
int Jack::JackClientSocket::Connect (const char * dir, const char * name, int which) virtual
Reimplemented from Jack::detail::JackClientRequestInterface.
Definition at line 124 of file JackSocket.cpp.
References Jack::BuildName(), fPromiscuous, fSocket, jack_error, and jack_log().
GetFd()
int Jack::JackClientSocket::GetFd () inline
Definition at line 60 of file JackSocket.h.
References fSocket.
Referenced by Jack::JackSocketServerChannel::ClientCreate().
Read()
int Jack::JackClientSocket::Read (void * data, int len) virtual
Reimplemented from Jack::detail::JackClientRequestInterface.
Definition at line 167 of file JackSocket.cpp.
References fSocket, fTimeOut, jack_error, jack_log(), and JACK_REQUEST_ERR_ABORTED.
SetNonBlocking()
void Jack::JackClientSocket::SetNonBlocking (bool onoff)
Definition at line 114 of file JackSocket.cpp.
References fSocket, and jack_error.
SetReadTimeOut()
void Jack::JackClientSocket::SetReadTimeOut (long sec)
Definition at line 92 of file JackSocket.cpp.
References fSocket, and jack_error.
SetWriteTimeOut()
void Jack::JackClientSocket::SetWriteTimeOut (long sec)
Definition at line 102 of file JackSocket.cpp.
References fSocket, and jack_error.
Write()
int Jack::JackClientSocket::Write (void * data, int len) virtual
Reimplemented from Jack::detail::JackClientRequestInterface.
Definition at line 217 of file JackSocket.cpp.
References fSocket, fTimeOut, jack_error, and jack_log().
Member Data Documentation
fPromiscuous
bool Jack::JackClientSocket::fPromiscuous private
Definition at line 48 of file JackSocket.h.
Referenced by JackClientSocket(), JackClientSocket(), and Connect().
fPromiscuousGid
int Jack::JackClientSocket::fPromiscuousGid private
Definition at line 49 of file JackSocket.h.
Referenced by JackClientSocket(), and JackClientSocket().
fSocket
int Jack::JackClientSocket::fSocket private
Definition at line 46 of file JackSocket.h.
Referenced by JackClientSocket(), JackClientSocket(), Close(), Connect(), GetFd(), Read(), SetNonBlocking(), SetReadTimeOut(), SetWriteTimeOut(), and Write().
fTimeOut
int Jack::JackClientSocket::fTimeOut private
Definition at line 47 of file JackSocket.h.
Referenced by JackClientSocket(), JackClientSocket(), Read(), and Write().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/posix/JackSocket.h
src/3rdparty/jack2/posix/JackSocket.cpp