LMMS: hiir::PhaseHalfPi4F64Avx< NC > Class Template Reference
hiir::PhaseHalfPi4F64Avx< NC > Class Template Reference
#include <PhaseHalfPi4F64Avx.h>
Public Types
typedef double DataType
Public Member Functions
PhaseHalfPi4F64Avx () noexcept
PhaseHalfPi4F64Avx (const PhaseHalfPi4F64Avx< NC > &other)=default
PhaseHalfPi4F64Avx (PhaseHalfPi4F64Avx< NC > &&other)=default
~PhaseHalfPi4F64Avx ()=default
void clear_buffers () noexcept
PhaseHalfPi4F64Avx< NC > & operator= (const PhaseHalfPi4F64Avx< NC > &other)=default
PhaseHalfPi4F64Avx< NC > & operator= (PhaseHalfPi4F64Avx< NC > &&other)=default
void process_block (double out_0_ptr[], double out_1_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (__m256d &out_0, __m256d &out_1, __m256d input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 4
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Avx, NBR_COEFS+2 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const PhaseHalfPi4F64Avx &other) const =delete
bool operator== (const PhaseHalfPi4F64Avx &other) const =delete
Private Attributes
FilterBiPhase _bifilter
int _phase
double _prev [_nbr_chn]
Static Private Attributes
static constexpr int _nbr_phases = 2
Detailed Description
template<int NC>
class hiir::PhaseHalfPi4F64Avx< NC >
Definition at line 49 of file PhaseHalfPi4F64Avx.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::PhaseHalfPi4F64Avx< NC >::DataType
Definition at line 58 of file PhaseHalfPi4F64Avx.h.
Filter
template<int NC> typedef std::array<StageDataF64Avx, NBR_COEFS + 2> hiir::PhaseHalfPi4F64Avx< NC >::Filter private
Definition at line 95 of file PhaseHalfPi4F64Avx.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::PhaseHalfPi4F64Avx< NC >::FilterBiPhase private
Definition at line 97 of file PhaseHalfPi4F64Avx.h.
Constructor & Destructor Documentation
PhaseHalfPi4F64Avx() [1/3]
template<int NC> hiir::PhaseHalfPi4F64Avx< NC >::PhaseHalfPi4F64Avx () noexcept
Definition at line 57 of file PhaseHalfPi4F64Avx.hpp.
References _bifilter, _phase, clear_buffers(), i, and NBR_COEFS.
Referenced by PhaseHalfPi4F64Avx(), PhaseHalfPi4F64Avx(), ~PhaseHalfPi4F64Avx(), operator!=(), operator=(), operator=(), and operator==().
PhaseHalfPi4F64Avx() [2/3]
template<int NC> hiir::PhaseHalfPi4F64Avx< NC >::PhaseHalfPi4F64Avx (const PhaseHalfPi4F64Avx< NC > & other) default
References PhaseHalfPi4F64Avx().
PhaseHalfPi4F64Avx() [3/3]
template<int NC> hiir::PhaseHalfPi4F64Avx< NC >::PhaseHalfPi4F64Avx (PhaseHalfPi4F64Avx< NC > && other) default
References PhaseHalfPi4F64Avx().
~PhaseHalfPi4F64Avx()
template<int NC> hiir::PhaseHalfPi4F64Avx< NC >::~PhaseHalfPi4F64Avx () default
References PhaseHalfPi4F64Avx().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::PhaseHalfPi4F64Avx< NC >::clear_buffers () noexcept
Definition at line 226 of file PhaseHalfPi4F64Avx.hpp.
References _bifilter, _phase, _prev, i, and NBR_COEFS.
Referenced by PhaseHalfPi4F64Avx(), and operator=().
operator!=()
template<int NC> bool hiir::PhaseHalfPi4F64Avx< NC >::operator!= (const PhaseHalfPi4F64Avx< NC > & other) const private delete
References PhaseHalfPi4F64Avx().
operator=() [1/2]
template<int NC> PhaseHalfPi4F64Avx< NC > & hiir::PhaseHalfPi4F64Avx< NC >::operator= (const PhaseHalfPi4F64Avx< NC > & other) default
References PhaseHalfPi4F64Avx().
operator=() [2/2]
template<int NC> PhaseHalfPi4F64Avx< NC > & hiir::PhaseHalfPi4F64Avx< NC >::operator= (PhaseHalfPi4F64Avx< NC > && other) default
References PhaseHalfPi4F64Avx(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::PhaseHalfPi4F64Avx< NC >::operator== (const PhaseHalfPi4F64Avx< NC > & other) const private delete
References PhaseHalfPi4F64Avx().
process_block()
template<int NC> void hiir::PhaseHalfPi4F64Avx< NC >::process_block (double out_0_ptr[], double out_1_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 150 of file PhaseHalfPi4F64Avx.hpp.
References _bifilter, _nbr_chn, _nbr_phases, _phase, _prev, NBR_COEFS, pos, process_sample(), and hiir::StageProc4F64Avx< REMAINING >::process_sample_neg().
Referenced by operator=().
process_sample()
template<int NC> void hiir::PhaseHalfPi4F64Avx< NC >::process_sample (__m256d & out_0, __m256d & out_1, __m256d input) noexcept
Definition at line 117 of file PhaseHalfPi4F64Avx.hpp.
References _bifilter, _phase, _prev, NBR_COEFS, and hiir::StageProc4F64Avx< REMAINING >::process_sample_neg().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::PhaseHalfPi4F64Avx< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 87 of file PhaseHalfPi4F64Avx.hpp.
References _bifilter, i, and NBR_COEFS.
Referenced by operator=().
Member Data Documentation
_bifilter
template<int NC> FilterBiPhase hiir::PhaseHalfPi4F64Avx< NC >::_bifilter private
Definition at line 99 of file PhaseHalfPi4F64Avx.h.
Referenced by PhaseHalfPi4F64Avx(), clear_buffers(), process_block(), process_sample(), and set_coefs().
_delay
template<int NC> double hiir::PhaseHalfPi4F64Avx< NC >::_delay = 0 static constexpr
Definition at line 61 of file PhaseHalfPi4F64Avx.h.
_nbr_chn
template<int NC> int hiir::PhaseHalfPi4F64Avx< NC >::_nbr_chn = 4 static constexpr
Definition at line 59 of file PhaseHalfPi4F64Avx.h.
Referenced by process_block().
_nbr_phases
template<int NC> int hiir::PhaseHalfPi4F64Avx< NC >::_nbr_phases = 2 static constexpr private
Definition at line 93 of file PhaseHalfPi4F64Avx.h.
Referenced by process_block().
_phase
template<int NC> int hiir::PhaseHalfPi4F64Avx< NC >::_phase private
Definition at line 102 of file PhaseHalfPi4F64Avx.h.
Referenced by PhaseHalfPi4F64Avx(), clear_buffers(), process_block(), and process_sample().
_prev
template<int NC> double hiir::PhaseHalfPi4F64Avx< NC >::_prev[_nbr_chn] private
Definition at line 101 of file PhaseHalfPi4F64Avx.h.
Referenced by clear_buffers(), process_block(), and process_sample().
NBR_COEFS
template<int NC> int hiir::PhaseHalfPi4F64Avx< NC >::NBR_COEFS = NC static constexpr
Definition at line 60 of file PhaseHalfPi4F64Avx.h.
Referenced by PhaseHalfPi4F64Avx(), clear_buffers(), process_block(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/PhaseHalfPi4F64Avx.h
src/3rdparty/hiir/hiir/PhaseHalfPi4F64Avx.hpp