LMMS: Jack::JackSessionNotifyResult Struct Reference
Jack::JackSessionNotifyResult Struct Reference
#include <JackRequest.h>
Public Member Functions
JackSessionNotifyResult ()
JackSessionNotifyResult (int32_t result)
jack_session_command_t * GetCommands ()
int Read (detail::JackChannelTransactionInterface *trans)
int Write (detail::JackChannelTransactionInterface *trans)
Public Member Functions inherited from Jack::JackResult
JackResult ()
JackResult (int result)
virtual ~JackResult ()
Public Attributes
std::list< JackSessionCommand > fCommandList
bool fDone
Public Attributes inherited from Jack::JackResult
int fResult
Detailed Description
Definition at line 1277 of file JackRequest.h.
Constructor & Destructor Documentation
JackSessionNotifyResult() [1/2]
Jack::JackSessionNotifyResult::JackSessionNotifyResult () inline
Definition at line 1283 of file JackRequest.h.
References Jack::JackResult::JackResult(), and fDone.
JackSessionNotifyResult() [2/2]
Jack::JackSessionNotifyResult::JackSessionNotifyResult (int32_t result) inline
Definition at line 1285 of file JackRequest.h.
References Jack::JackResult::JackResult(), and fDone.
Member Function Documentation
GetCommands()
jack_session_command_t * Jack::JackSessionNotifyResult::GetCommands () inline
Definition at line 1338 of file JackRequest.h.
References jack_session_command_t::client_name, jack_session_command_t::command, fCommandList, fDone, jack_session_command_t::flags, i, JackSleep(), and jack_session_command_t::uuid.
Referenced by Jack::JackGenericClientChannel::SessionNotify(), and Jack::JackInternalClientChannel::SessionNotify().
Read()
int Jack::JackSessionNotifyResult::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 1289 of file JackRequest.h.
References CheckRes, Jack::JackSessionCommand::fClientName, Jack::JackSessionCommand::fCommand, fCommandList, fDone, Jack::JackSessionCommand::fFlags, Jack::JackSessionCommand::fUUID, Jack::detail::JackChannelTransactionInterface::Read(), and Jack::JackResult::Read().
Write()
int Jack::JackSessionNotifyResult::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 1316 of file JackRequest.h.
References CheckRes, fCommandList, fDone, i, JACK_UUID_STRING_SIZE, Jack::detail::JackChannelTransactionInterface::Write(), and Jack::JackResult::Write().
Referenced by Jack::JackEngine::SessionNotify().
Member Data Documentation
fCommandList
std::list<JackSessionCommand> Jack::JackSessionNotifyResult::fCommandList
Definition at line 1280 of file JackRequest.h.
Referenced by GetCommands(), Read(), and Write().
fDone
bool Jack::JackSessionNotifyResult::fDone
Definition at line 1281 of file JackRequest.h.
Referenced by JackSessionNotifyResult(), JackSessionNotifyResult(), GetCommands(), Read(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h