LMMS: lmms::detail::BufferViewData< T, channelCount > Class Template Reference
lmms::detail::BufferViewData< T, channelCount > Class Template Reference
#include <AudioBufferView.h>
Public Member Functions
constexpr BufferViewData ()=default
constexpr BufferViewData (const BufferViewData &)=default
constexpr BufferViewData (T *data, f_cnt_t frames) noexcept
constexpr BufferViewData (T *data, proc_ch_t channels, f_cnt_t frames) noexcept
constexpr auto data () const noexcept -> T *
constexpr auto frames () const noexcept -> f_cnt_t
Static Public Member Functions
static constexpr auto channels () noexcept -> proc_ch_t
Protected Attributes
T * m_data = nullptr
f_cnt_t m_frames = 0
Detailed Description
template<typename T, proc_ch_t channelCount>
class lmms::detail::BufferViewData< T, channelCount >
Definition at line 49 of file AudioBufferView.h.
Constructor & Destructor Documentation
BufferViewData() [1/4]
template<typename T, proc_ch_t channelCount> lmms::detail::BufferViewData< T, channelCount >::BufferViewData () constexpr default
BufferViewData() [2/4]
template<typename T, proc_ch_t channelCount> lmms::detail::BufferViewData< T, channelCount >::BufferViewData (const BufferViewData< T, channelCount > &) constexpr default
BufferViewData() [3/4]
template<typename T, proc_ch_t channelCount> lmms::detail::BufferViewData< T, channelCount >::BufferViewData (T * data, proc_ch_t channels, f_cnt_t frames) inline constexpr noexcept
Definition at line 55 of file AudioBufferView.h.
BufferViewData() [4/4]
template<typename T, proc_ch_t channelCount> lmms::detail::BufferViewData< T, channelCount >::BufferViewData (T * data, f_cnt_t frames) inline constexpr noexcept
Definition at line 62 of file AudioBufferView.h.
Member Function Documentation
channels()
template<typename T, proc_ch_t channelCount> constexpr auto lmms::detail::BufferViewData< T, channelCount >::channels () ->proc_ch_t inline static constexpr noexcept
Definition at line 69 of file AudioBufferView.h.
Referenced by lmms::InterleavedBufferView< T, channelCount >::dataSizeBytes(), lmms::InterleavedBufferView< T, channelCount >::dataView(), lmms::InterleavedBufferView< T, channelCount >::empty(), lmms::InterleavedBufferView< T, channelCount >::frame(), lmms::InterleavedBufferView< T, channelCount >::framePtr(), lmms::InterleavedBufferView< T, channelCount >::framesView(), lmms::InterleavedBufferView< T, channelCount >::framesView(), and lmms::InterleavedBufferView< T, channelCount >::subspan().
data()
template<typename T, proc_ch_t channelCount> auto lmms::detail::BufferViewData< T, channelCount >::data () const->T * inline constexpr noexcept
Definition at line 68 of file AudioBufferView.h.
Referenced by lmms::PlanarBufferView< T, channelCount >::PlanarBufferView().
frames()
template<typename T, proc_ch_t channelCount> auto lmms::detail::BufferViewData< T, channelCount >::frames () const->f_cnt_t inline constexpr noexcept
Definition at line 70 of file AudioBufferView.h.
Referenced by lmms::PlanarBufferView< T, channelCount >::PlanarBufferView().
Member Data Documentation
m_data
template<typename T, proc_ch_t channelCount> T* lmms::detail::BufferViewData< T, channelCount >::m_data = nullptr protected
Definition at line 73 of file AudioBufferView.h.
m_frames
template<typename T, proc_ch_t channelCount> f_cnt_t lmms::detail::BufferViewData< T, channelCount >::m_frames = 0 protected
Definition at line 74 of file AudioBufferView.h.
The documentation for this class was generated from the following file:
include/AudioBufferView.h