LMMS: lmms::gui::InstrumentTuningView Class Reference
lmms::gui::InstrumentTuningView Class Reference
#include <InstrumentTuningView.h>
Public Member Functions
InstrumentTuningView (InstrumentTrack *it, QWidget *parent)
ComboBox * keymapCombo ()
GroupBox * microtunerGroupBox ()
QLabel * microtunerNotSupportedLabel ()
GroupBox * pitchGroupBox ()
LedCheckBox * rangeImportCheckbox ()
ComboBox * scaleCombo ()
Private Attributes
ComboBox * m_keymapCombo
GroupBox * m_microtunerGroupBox
QLabel * m_microtunerNotSupportedLabel
GroupBox * m_pitchGroupBox
LedCheckBox * m_rangeImportCheckbox
ComboBox * m_scaleCombo
Detailed Description
Definition at line 47 of file InstrumentTuningView.h.
Constructor & Destructor Documentation
InstrumentTuningView()
lmms::gui::InstrumentTuningView::InstrumentTuningView (InstrumentTrack * it, QWidget * parent)
Definition at line 47 of file InstrumentTuningView.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, lmms::Microtuner::enabledModel(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::Microtuner::keymapModel(), lmms::Microtuner::keyRangeImportModel(), m_keymapCombo, lmms::InstrumentTrack::m_microtuner, m_microtunerGroupBox, m_microtunerNotSupportedLabel, m_pitchGroupBox, m_rangeImportCheckbox, m_scaleCombo, lmms::InstrumentTrack::m_useMasterPitchModel, and lmms::Microtuner::scaleModel().
Member Function Documentation
keymapCombo()
ComboBox * lmms::gui::InstrumentTuningView::keymapCombo () inline
Definition at line 59 of file InstrumentTuningView.h.
References m_keymapCombo.
microtunerGroupBox()
GroupBox * lmms::gui::InstrumentTuningView::microtunerGroupBox () inline
Definition at line 54 of file InstrumentTuningView.h.
References m_microtunerGroupBox.
microtunerNotSupportedLabel()
QLabel * lmms::gui::InstrumentTuningView::microtunerNotSupportedLabel () inline
Definition at line 56 of file InstrumentTuningView.h.
References m_microtunerNotSupportedLabel.
pitchGroupBox()
GroupBox * lmms::gui::InstrumentTuningView::pitchGroupBox () inline
Definition at line 53 of file InstrumentTuningView.h.
References m_pitchGroupBox.
rangeImportCheckbox()
LedCheckBox * lmms::gui::InstrumentTuningView::rangeImportCheckbox () inline
Definition at line 61 of file InstrumentTuningView.h.
References m_rangeImportCheckbox.
scaleCombo()
ComboBox * lmms::gui::InstrumentTuningView::scaleCombo () inline
Definition at line 58 of file InstrumentTuningView.h.
References m_scaleCombo.
Member Data Documentation
m_keymapCombo
ComboBox* lmms::gui::InstrumentTuningView::m_keymapCombo private
Definition at line 70 of file InstrumentTuningView.h.
Referenced by InstrumentTuningView(), and keymapCombo().
m_microtunerGroupBox
GroupBox* lmms::gui::InstrumentTuningView::m_microtunerGroupBox private
Definition at line 65 of file InstrumentTuningView.h.
Referenced by InstrumentTuningView(), and microtunerGroupBox().
m_microtunerNotSupportedLabel
QLabel* lmms::gui::InstrumentTuningView::m_microtunerNotSupportedLabel private
Definition at line 67 of file InstrumentTuningView.h.
Referenced by InstrumentTuningView(), and microtunerNotSupportedLabel().
m_pitchGroupBox
GroupBox* lmms::gui::InstrumentTuningView::m_pitchGroupBox private
Definition at line 64 of file InstrumentTuningView.h.
Referenced by InstrumentTuningView(), and pitchGroupBox().
m_rangeImportCheckbox
LedCheckBox* lmms::gui::InstrumentTuningView::m_rangeImportCheckbox private
Definition at line 72 of file InstrumentTuningView.h.
Referenced by InstrumentTuningView(), and rangeImportCheckbox().
m_scaleCombo
ComboBox* lmms::gui::InstrumentTuningView::m_scaleCombo private
Definition at line 69 of file InstrumentTuningView.h.
Referenced by InstrumentTuningView(), and scaleCombo().
The documentation for this class was generated from the following files:
include/InstrumentTuningView.h
src/gui/instrument/InstrumentTuningView.cpp