LMMS: lmms::gui::LfoControllerDialog Class Reference
lmms::gui::LfoControllerDialog Class Reference
#include <LfoController.h>
Public Member Functions
LfoControllerDialog (Controller *_controller, QWidget *_parent)
~LfoControllerDialog () override
Public Member Functions inherited from lmms::gui::ControllerDialog
ControllerDialog (Controller *_controller, QWidget *_parent)
~ControllerDialog () override=default
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *_me) override
void modelChanged () override
Protected Member Functions inherited from lmms::gui::ControllerDialog
void closeEvent (QCloseEvent *_ce) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Protected Attributes
Knob * m_amountKnob
Knob * m_baseKnob
LfoController * m_lfo
AutomatableButtonGroup * m_multiplierBtnGrp
Knob * m_phaseKnob
TempoSyncKnob * m_speedKnob
PixmapButton * m_userLfoBtn
AutomatableButtonGroup * m_waveBtnGrp
Private Slots
void askUserDefWave ()
Private Attributes
PixmapButton * m_userWaveBtn
Additional Inherited Members
Signals inherited from lmms::gui::ControllerDialog
void closed ()
Detailed Description
Definition at line 101 of file LfoController.h.
Constructor & Destructor Documentation
LfoControllerDialog()
lmms::gui::LfoControllerDialog::LfoControllerDialog (Controller * _controller, QWidget * _parent)
Definition at line 55 of file LfoControllerDialog.cpp.
References lmms::gui::ControllerDialog::ControllerDialog(), askUserDefWave(), lmms::gui::Bright26, lmms::gui::CD_LFO_AMOUNT_CD_KNOB_X, lmms::gui::CD_LFO_BASE_CD_KNOB_X, lmms::gui::CD_LFO_CD_KNOB_Y, lmms::gui::CD_LFO_MULTIPLIER_X, lmms::gui::CD_LFO_PHASE_CD_KNOB_X, lmms::gui::CD_LFO_SHAPES_X, lmms::gui::CD_LFO_SHAPES_Y, lmms::gui::CD_LFO_SPEED_CD_KNOB_X, lmms::embed::getIconPixmap(), m_amountKnob, m_baseKnob, m_multiplierBtnGrp, m_phaseKnob, m_speedKnob, m_userWaveBtn, m_waveBtnGrp, lmms::Controller::name(), lmms::gui::ModelView::setModel(), and SMALL_FONT_SIZE.
~LfoControllerDialog()
lmms::gui::LfoControllerDialog::~LfoControllerDialog () override
Definition at line 202 of file LfoControllerDialog.cpp.
References m_userWaveBtn.
Member Function Documentation
askUserDefWave
void lmms::gui::LfoControllerDialog::askUserDefWave () private slot
Definition at line 209 of file LfoControllerDialog.cpp.
References lmms::gui::SampleLoader::createBufferFromFile(), lmms::LfoController::m_userDefSampleBuffer, m_userWaveBtn, lmms::gui::ModelView::model(), and lmms::gui::SampleLoader::openWaveformFile().
Referenced by LfoControllerDialog().
contextMenuEvent()
void lmms::gui::LfoControllerDialog::contextMenuEvent (QContextMenuEvent * _me) override protected
Definition at line 223 of file LfoControllerDialog.cpp.
modelChanged()
void lmms::gui::LfoControllerDialog::modelChanged () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 248 of file LfoControllerDialog.cpp.
References lmms::gui::ModelView::castModel(), m_amountKnob, m_baseKnob, m_lfo, m_multiplierBtnGrp, m_phaseKnob, m_speedKnob, and m_waveBtnGrp.
Member Data Documentation
m_amountKnob
Knob* lmms::gui::LfoControllerDialog::m_amountKnob protected
Definition at line 117 of file LfoController.h.
Referenced by LfoControllerDialog(), and modelChanged().
m_baseKnob
Knob* lmms::gui::LfoControllerDialog::m_baseKnob protected
Definition at line 115 of file LfoController.h.
Referenced by LfoControllerDialog(), and modelChanged().
m_lfo
LfoController* lmms::gui::LfoControllerDialog::m_lfo protected
Definition at line 113 of file LfoController.h.
Referenced by modelChanged().
m_multiplierBtnGrp
AutomatableButtonGroup* lmms::gui::LfoControllerDialog::m_multiplierBtnGrp protected
Definition at line 121 of file LfoController.h.
Referenced by LfoControllerDialog(), and modelChanged().
m_phaseKnob
Knob* lmms::gui::LfoControllerDialog::m_phaseKnob protected
Definition at line 118 of file LfoController.h.
Referenced by LfoControllerDialog(), and modelChanged().
m_speedKnob
TempoSyncKnob* lmms::gui::LfoControllerDialog::m_speedKnob protected
Definition at line 116 of file LfoController.h.
Referenced by LfoControllerDialog(), and modelChanged().
m_userLfoBtn
PixmapButton* lmms::gui::LfoControllerDialog::m_userLfoBtn protected
Definition at line 119 of file LfoController.h.
m_userWaveBtn
PixmapButton* lmms::gui::LfoControllerDialog::m_userWaveBtn private
Definition at line 125 of file LfoController.h.
Referenced by LfoControllerDialog(), ~LfoControllerDialog(), and askUserDefWave().
m_waveBtnGrp
AutomatableButtonGroup* lmms::gui::LfoControllerDialog::m_waveBtnGrp protected
Definition at line 120 of file LfoController.h.
Referenced by LfoControllerDialog(), and modelChanged().
The documentation for this class was generated from the following files:
include/LfoController.h
src/gui/LfoControllerDialog.cpp