LMMS: lmms::LadspaManager Class Reference
lmms::LadspaManager Class Reference
#include <LadspaManager.h>
Public Member Functions
LadspaManager ()
virtual ~LadspaManager ()
bool activate (const ladspa_key_t &_plugin, LADSPA_Handle _instance)
bool areHintsSampleRateDependent (const ladspa_key_t &_plugin, uint32_t _port)
bool cleanup (const ladspa_key_t &_plugin, LADSPA_Handle _instance)
bool connectPort (const ladspa_key_t &_plugin, LADSPA_Handle _instance, uint32_t _port, LADSPA_Data *_data_location)
bool deactivate (const ladspa_key_t &_plugin, LADSPA_Handle _instance)
QString getCopyright (const ladspa_key_t &_plugin)
float getDefaultSetting (const ladspa_key_t &_plugin, uint32_t _port)
LadspaManagerDescription * getDescription (const ladspa_key_t &_plugin)
const LADSPA_Descriptor * getDescriptor (const ladspa_key_t &_plugin)
const void * getImplementationData (const ladspa_key_t &_plugin)
QString getLabel (const ladspa_key_t &_plugin)
float getLowerBound (const ladspa_key_t &_plugin, uint32_t _port)
QString getMaker (const ladspa_key_t &_plugin)
QString getName (const ladspa_key_t &_plugin)
uint32_t getPortCount (const ladspa_key_t &_plugin)
QString getPortName (const ladspa_key_t &_plugin, uint32_t _port)
l_sortable_plugin_t getSortedPlugins ()
float getUpperBound (const ladspa_key_t &_plugin, uint32_t _port)
bool hasRealTimeDependency (const ladspa_key_t &_plugin)
LADSPA_Handle instantiate (const ladspa_key_t &_plugin, uint32_t _sample_rate)
bool isEnum (const ladspa_key_t &_plugin, uint32_t _port)
bool isInplaceBroken (const ladspa_key_t &_plugin)
bool isInteger (const ladspa_key_t &_plugin, uint32_t _port)
bool isLogarithmic (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortAudio (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortControl (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortInput (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortOutput (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortToggled (const ladspa_key_t &_plugin, uint32_t _port)
bool isRealTimeCapable (const ladspa_key_t &_plugin)
bool run (const ladspa_key_t &_plugin, LADSPA_Handle _instance, uint32_t _sample_count)
bool runAdding (const ladspa_key_t &_plugin, LADSPA_Handle _instance, uint32_t _sample_count)
bool setRunAddingGain (const ladspa_key_t &_plugin, LADSPA_Handle _instance, LADSPA_Data _gain)
Private Types
using LadspaManagerMapType = QMap<ladspa_key_t, LadspaManagerDescription*>
Private Member Functions
void addPlugins (LADSPA_Descriptor_Function _descriptor_func, const QString &_file)
uint16_t getPluginInputs (const LADSPA_Descriptor *_descriptor)
uint16_t getPluginOutputs (const LADSPA_Descriptor *_descriptor)
const LADSPA_PortDescriptor * getPortDescriptor (const ladspa_key_t &_plugin, uint32_t _port)
const LADSPA_PortRangeHint * getPortRangeHint (const ladspa_key_t &_plugin, uint32_t _port)
Private Attributes
LadspaManagerMapType m_ladspaManagerMap
l_sortable_plugin_t m_sortedPlugins
Detailed Description
Definition at line 84 of file LadspaManager.h.
Member Typedef Documentation
LadspaManagerMapType
using lmms::LadspaManager::LadspaManagerMapType = QMap<ladspa_key_t, LadspaManagerDescription*> private
Definition at line 343 of file LadspaManager.h.
Constructor & Destructor Documentation
LadspaManager()
lmms::LadspaManager::LadspaManager ()
Definition at line 46 of file LadspaManager.cpp.
References addPlugins(), lmms::PluginFactory::getExcludePatterns(), getName(), lmms::ConfigManager::inst(), lmms::LADSPA_PATH_SEPERATOR, lmms::ConfigManager::ladspaDir(), m_ladspaManagerMap, m_sortedPlugins, and lmms::PluginFactory::setupSearchPaths().
~LadspaManager()
lmms::LadspaManager::~LadspaManager () virtual
Definition at line 123 of file LadspaManager.cpp.
References m_ladspaManagerMap.
Member Function Documentation
activate()
bool lmms::LadspaManager::activate (const ladspa_key_t & _plugin, LADSPA_Handle _instance)
Definition at line 614 of file LadspaManager.cpp.
References _LADSPA_Descriptor::activate, and getDescriptor().
addPlugins()
void lmms::LadspaManager::addPlugins (LADSPA_Descriptor_Function _descriptor_func, const QString & _file) private
Definition at line 145 of file LadspaManager.cpp.
References lmms::LadspaManagerDescription::descriptorFunction, getPluginInputs(), getPluginOutputs(), m_ladspaManagerMap, lmms::Other, lmms::Sink, lmms::Source, and lmms::Transfer.
Referenced by LadspaManager().
areHintsSampleRateDependent()
bool lmms::LadspaManager::areHintsSampleRateDependent (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 386 of file LadspaManager.cpp.
References getPortRangeHint(), and LADSPA_IS_HINT_SAMPLE_RATE.
cleanup()
bool lmms::LadspaManager::cleanup (const ladspa_key_t & _plugin, LADSPA_Handle _instance)
Definition at line 694 of file LadspaManager.cpp.
References _LADSPA_Descriptor::cleanup, and getDescriptor().
connectPort()
bool lmms::LadspaManager::connectPort (const ladspa_key_t & _plugin, LADSPA_Handle _instance, uint32_t _port, LADSPA_Data * _data_location)
Definition at line 595 of file LadspaManager.cpp.
References _LADSPA_Descriptor::connect_port, getDescriptor(), and getPortCount().
deactivate()
bool lmms::LadspaManager::deactivate (const ladspa_key_t & _plugin, LADSPA_Handle _instance)
Definition at line 679 of file LadspaManager.cpp.
References _LADSPA_Descriptor::deactivate, and getDescriptor().
getCopyright()
QString lmms::LadspaManager::getCopyright (const ladspa_key_t & _plugin)
Definition at line 328 of file LadspaManager.cpp.
References _LADSPA_Descriptor::Copyright, and getDescriptor().
getDefaultSetting()
float lmms::LadspaManager::getDefaultSetting (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 435 of file LadspaManager.cpp.
References getPortRangeHint(), LADSPA_HINT_DEFAULT_0, LADSPA_HINT_DEFAULT_1, LADSPA_HINT_DEFAULT_100, LADSPA_HINT_DEFAULT_440, LADSPA_HINT_DEFAULT_HIGH, LADSPA_HINT_DEFAULT_LOW, LADSPA_HINT_DEFAULT_MASK, LADSPA_HINT_DEFAULT_MAXIMUM, LADSPA_HINT_DEFAULT_MIDDLE, LADSPA_HINT_DEFAULT_MINIMUM, LADSPA_HINT_DEFAULT_NONE, LADSPA_IS_HINT_LOGARITHMIC, and lmms::NOHINT.
getDescription()
LadspaManagerDescription * lmms::LadspaManager::getDescription (const ladspa_key_t & _plugin)
Definition at line 135 of file LadspaManager.cpp.
References m_ladspaManagerMap.
Referenced by lmms::Ladspa2LMMS::Ladspa2LMMS().
getDescriptor()
const LADSPA_Descriptor * lmms::LadspaManager::getDescriptor (const ladspa_key_t & _plugin)
Definition at line 563 of file LadspaManager.cpp.
References m_ladspaManagerMap.
Referenced by activate(), cleanup(), connectPort(), deactivate(), getCopyright(), getImplementationData(), getLabel(), getMaker(), getName(), getPortCount(), getPortDescriptor(), getPortName(), getPortRangeHint(), hasRealTimeDependency(), instantiate(), isEnum(), isInplaceBroken(), isRealTimeCapable(), run(), runAdding(), and setRunAddingGain().
getImplementationData()
const void * lmms::LadspaManager::getImplementationData (const ladspa_key_t & _plugin)
Definition at line 553 of file LadspaManager.cpp.
References getDescriptor(), and _LADSPA_Descriptor::ImplementationData.
getLabel()
QString lmms::LadspaManager::getLabel (const ladspa_key_t & _plugin)
Definition at line 269 of file LadspaManager.cpp.
References getDescriptor(), and _LADSPA_Descriptor::Label.
getLowerBound()
float lmms::LadspaManager::getLowerBound (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 397 of file LadspaManager.cpp.
References getPortRangeHint(), LADSPA_IS_HINT_BOUNDED_BELOW, and lmms::NOHINT.
getMaker()
QString lmms::LadspaManager::getMaker (const ladspa_key_t & _plugin)
Definition at line 319 of file LadspaManager.cpp.
References getDescriptor(), and _LADSPA_Descriptor::Maker.
getName()
QString lmms::LadspaManager::getName (const ladspa_key_t & _plugin)
Definition at line 310 of file LadspaManager.cpp.
References getDescriptor(), and _LADSPA_Descriptor::Name.
Referenced by lmms::Ladspa2LMMS::Ladspa2LMMS(), LadspaManager(), and lmms::Ladspa2LMMS::getShortName().
getPluginInputs()
uint16_t lmms::LadspaManager::getPluginInputs (const LADSPA_Descriptor * _descriptor) private
Definition at line 189 of file LadspaManager.cpp.
References LADSPA_IS_PORT_AUDIO, LADSPA_IS_PORT_INPUT, _LADSPA_Descriptor::PortCount, _LADSPA_Descriptor::PortDescriptors, and _LADSPA_Descriptor::PortNames.
Referenced by addPlugins().
getPluginOutputs()
uint16_t lmms::LadspaManager::getPluginOutputs (const LADSPA_Descriptor * _descriptor) private
Definition at line 215 of file LadspaManager.cpp.
References LADSPA_IS_PORT_AUDIO, LADSPA_IS_PORT_OUTPUT, _LADSPA_Descriptor::PortCount, _LADSPA_Descriptor::PortDescriptors, and _LADSPA_Descriptor::PortNames.
Referenced by addPlugins().
getPortCount()
uint32_t lmms::LadspaManager::getPortCount (const ladspa_key_t & _plugin)
Definition at line 337 of file LadspaManager.cpp.
References getDescriptor(), and _LADSPA_Descriptor::PortCount.
Referenced by connectPort(), getPortDescriptor(), and getPortRangeHint().
getPortDescriptor()
const LADSPA_PortDescriptor * lmms::LadspaManager::getPortDescriptor (const ladspa_key_t & _plugin, uint32_t _port) private
Definition at line 238 of file LadspaManager.cpp.
References getDescriptor(), getPortCount(), and _LADSPA_Descriptor::PortDescriptors.
Referenced by isPortAudio(), isPortControl(), isPortInput(), and isPortOutput().
getPortName()
QString lmms::LadspaManager::getPortName (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 543 of file LadspaManager.cpp.
References getDescriptor(), and _LADSPA_Descriptor::PortNames.
getPortRangeHint()
const LADSPA_PortRangeHint * lmms::LadspaManager::getPortRangeHint (const ladspa_key_t & _plugin, uint32_t _port) private
Definition at line 248 of file LadspaManager.cpp.
References getDescriptor(), getPortCount(), and _LADSPA_Descriptor::PortRangeHints.
Referenced by areHintsSampleRateDependent(), getDefaultSetting(), getLowerBound(), getUpperBound(), isInteger(), isLogarithmic(), and isPortToggled().
getSortedPlugins()
l_sortable_plugin_t lmms::LadspaManager::getSortedPlugins ()
Definition at line 261 of file LadspaManager.cpp.
References m_sortedPlugins.
Referenced by lmms::Ladspa2LMMS::Ladspa2LMMS().
getUpperBound()
float lmms::LadspaManager::getUpperBound (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 411 of file LadspaManager.cpp.
References getPortRangeHint(), LADSPA_IS_HINT_BOUNDED_ABOVE, and lmms::NOHINT.
hasRealTimeDependency()
bool lmms::LadspaManager::hasRealTimeDependency (const ladspa_key_t & _plugin)
Definition at line 278 of file LadspaManager.cpp.
References getDescriptor(), LADSPA_IS_REALTIME, and _LADSPA_Descriptor::Properties.
instantiate()
LADSPA_Handle lmms::LadspaManager::instantiate (const ladspa_key_t & _plugin, uint32_t _sample_rate)
Definition at line 582 of file LadspaManager.cpp.
References getDescriptor(), and _LADSPA_Descriptor::instantiate.
isEnum()
bool lmms::LadspaManager::isEnum (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 526 of file LadspaManager.cpp.
References getDescriptor(), LADSPA_IS_HINT_INTEGER, and LADSPA_IS_HINT_TOGGLED.
isInplaceBroken()
bool lmms::LadspaManager::isInplaceBroken (const ladspa_key_t & _plugin)
Definition at line 289 of file LadspaManager.cpp.
References getDescriptor(), LADSPA_IS_INPLACE_BROKEN, and _LADSPA_Descriptor::Properties.
isInteger()
bool lmms::LadspaManager::isInteger (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 516 of file LadspaManager.cpp.
References getPortRangeHint(), and LADSPA_IS_HINT_INTEGER.
isLogarithmic()
bool lmms::LadspaManager::isLogarithmic (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 506 of file LadspaManager.cpp.
References getPortRangeHint(), and LADSPA_IS_HINT_LOGARITHMIC.
isPortAudio()
bool lmms::LadspaManager::isPortAudio (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 366 of file LadspaManager.cpp.
References getPortDescriptor(), and LADSPA_IS_PORT_AUDIO.
isPortControl()
bool lmms::LadspaManager::isPortControl (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 376 of file LadspaManager.cpp.
References getPortDescriptor(), and LADSPA_IS_PORT_CONTROL.
isPortInput()
bool lmms::LadspaManager::isPortInput (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 346 of file LadspaManager.cpp.
References getPortDescriptor(), and LADSPA_IS_PORT_INPUT.
isPortOutput()
bool lmms::LadspaManager::isPortOutput (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 356 of file LadspaManager.cpp.
References getPortDescriptor(), and LADSPA_IS_PORT_OUTPUT.
isPortToggled()
bool lmms::LadspaManager::isPortToggled (const ladspa_key_t & _plugin, uint32_t _port)
Definition at line 425 of file LadspaManager.cpp.
References getPortRangeHint(), and LADSPA_IS_HINT_TOGGLED.
isRealTimeCapable()
bool lmms::LadspaManager::isRealTimeCapable (const ladspa_key_t & _plugin)
Definition at line 299 of file LadspaManager.cpp.
References getDescriptor(), LADSPA_IS_HARD_RT_CAPABLE, and _LADSPA_Descriptor::Properties.
Referenced by lmms::Ladspa2LMMS::Ladspa2LMMS().
run()
bool lmms::LadspaManager::run (const ladspa_key_t & _plugin, LADSPA_Handle _instance, uint32_t _sample_count)
Definition at line 629 of file LadspaManager.cpp.
References getDescriptor(), and _LADSPA_Descriptor::run.
runAdding()
bool lmms::LadspaManager::runAdding (const ladspa_key_t & _plugin, LADSPA_Handle _instance, uint32_t _sample_count)
Definition at line 645 of file LadspaManager.cpp.
References getDescriptor(), _LADSPA_Descriptor::run_adding, and _LADSPA_Descriptor::set_run_adding_gain.
setRunAddingGain()
bool lmms::LadspaManager::setRunAddingGain (const ladspa_key_t & _plugin, LADSPA_Handle _instance, LADSPA_Data _gain)
Definition at line 662 of file LadspaManager.cpp.
References getDescriptor(), _LADSPA_Descriptor::run_adding, and _LADSPA_Descriptor::set_run_adding_gain.
Member Data Documentation
m_ladspaManagerMap
LadspaManagerMapType lmms::LadspaManager::m_ladspaManagerMap private
Definition at line 344 of file LadspaManager.h.
Referenced by LadspaManager(), ~LadspaManager(), addPlugins(), getDescription(), and getDescriptor().
m_sortedPlugins
l_sortable_plugin_t lmms::LadspaManager::m_sortedPlugins private
Definition at line 345 of file LadspaManager.h.
Referenced by LadspaManager(), and getSortedPlugins().
The documentation for this class was generated from the following files:
include/LadspaManager.h
src/core/LadspaManager.cpp