LMMS: src/3rdparty/jack2/common/memops.h File Reference
memops.h File Reference
#include "types.h"
Classes
struct dither_state_t
Macros
#define DITHER_BUF_MASK 7
#define DITHER_BUF_SIZE 8
Enumerations
enum DitherAlgorithm {
None ,
Rectangular ,
Triangular ,
Shaped
}
Functions
void memcpy_fake (char *dst, char *src, unsigned long src_bytes, unsigned long foo, unsigned long bar)
void memcpy_interleave_d16_s16 (char *dst, char *src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
void memcpy_interleave_d24_s24 (char *dst, char *src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
void memcpy_interleave_d32_s32 (char *dst, char *src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
void memset_interleave (char *dst, char val, unsigned long bytes, unsigned long unit_bytes, unsigned long skip_bytes)
void merge_memcpy_d16_s16 (char *dst, char *src, unsigned long src_bytes, unsigned long foo, unsigned long bar)
void merge_memcpy_d32_s32 (char *dst, char *src, unsigned long src_bytes, unsigned long foo, unsigned long bar)
void merge_memcpy_interleave_d16_s16 (char *dst, char *src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
void merge_memcpy_interleave_d24_s24 (char *dst, char *src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
void merge_memcpy_interleave_d32_s32 (char *dst, char *src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
static __inline__ void sample_memcpy (jack_default_audio_sample_t *dst, jack_default_audio_sample_t *src, unsigned long cnt)
static __inline__ void sample_merge (jack_default_audio_sample_t *dst, jack_default_audio_sample_t *src, unsigned long cnt)
void sample_merge_d16_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_merge_d32u24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d16_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d16_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d32_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d32_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d32l24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d32l24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d32u24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_d32u24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_rect_d16_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_rect_d16_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_rect_d24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_rect_d24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_rect_d32u24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_rect_d32u24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_shaped_d16_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_shaped_d16_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_shaped_d24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_shaped_d24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_shaped_d32u24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_shaped_d32u24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_tri_d16_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_tri_d16_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_tri_d24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_tri_d24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_tri_d32u24_sS (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dither_tri_d32u24_sSs (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dS_floatLE (char *dst, jack_default_audio_sample_t *src, unsigned long nsamples, unsigned long dst_skip, dither_state_t *state)
void sample_move_dS_s16 (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s16s (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s24 (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s24s (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s32 (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s32l24 (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s32l24s (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s32s (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s32u24 (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_dS_s32u24s (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long src_skip)
void sample_move_floatLE_sSs (jack_default_audio_sample_t *dst, char *src, unsigned long nsamples, unsigned long dst_skip)
Macro Definition Documentation
DITHER_BUF_MASK
#define DITHER_BUF_MASK 7
Definition at line 42 of file memops.h.
DITHER_BUF_SIZE
#define DITHER_BUF_SIZE 8
Definition at line 41 of file memops.h.
Enumeration Type Documentation
DitherAlgorithm
enum DitherAlgorithm
Enumerator
None
Rectangular
Triangular
Shaped
Definition at line 34 of file memops.h.
Function Documentation
memcpy_fake()
void memcpy_fake (char * dst, char * src, unsigned long src_bytes, unsigned long foo, unsigned long bar)
memcpy_interleave_d16_s16()
void memcpy_interleave_d16_s16 (char * dst, char * src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
memcpy_interleave_d24_s24()
void memcpy_interleave_d24_s24 (char * dst, char * src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
memcpy_interleave_d32_s32()
void memcpy_interleave_d32_s32 (char * dst, char * src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
memset_interleave()
void memset_interleave (char * dst, char val, unsigned long bytes, unsigned long unit_bytes, unsigned long skip_bytes)
Referenced by alsa_driver_silence_on_channel(), and alsa_driver_silence_on_channel_no_mark().
merge_memcpy_d16_s16()
void merge_memcpy_d16_s16 (char * dst, char * src, unsigned long src_bytes, unsigned long foo, unsigned long bar)
merge_memcpy_d32_s32()
void merge_memcpy_d32_s32 (char * dst, char * src, unsigned long src_bytes, unsigned long foo, unsigned long bar)
merge_memcpy_interleave_d16_s16()
void merge_memcpy_interleave_d16_s16 (char * dst, char * src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
merge_memcpy_interleave_d24_s24()
void merge_memcpy_interleave_d24_s24 (char * dst, char * src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
merge_memcpy_interleave_d32_s32()
void merge_memcpy_interleave_d32_s32 (char * dst, char * src, unsigned long src_bytes, unsigned long dst_skip_bytes, unsigned long src_skip_bytes)
sample_memcpy()
__inline__ void sample_memcpy (jack_default_audio_sample_t * dst, jack_default_audio_sample_t * src, unsigned long cnt) static
Definition at line 111 of file memops.h.
sample_merge()
__inline__ void sample_merge (jack_default_audio_sample_t * dst, jack_default_audio_sample_t * src, unsigned long cnt) static
Definition at line 101 of file memops.h.
sample_merge_d16_sS()
void sample_merge_d16_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_merge_d32u24_sS()
void sample_merge_d32u24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_d16_sS()
void sample_move_d16_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
Referenced by Jack::CopyAndConvertOut(), and Jack::CopyAndConvertOut().
sample_move_d16_sSs()
void sample_move_d16_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_d24_sS()
void sample_move_d24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
Referenced by Jack::CopyAndConvertOut(), and Jack::CopyAndConvertOut().
sample_move_d24_sSs()
void sample_move_d24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_d32_sS()
void sample_move_d32_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_d32_sSs()
void sample_move_d32_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_d32l24_sS()
void sample_move_d32l24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_d32l24_sSs()
void sample_move_d32l24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_d32u24_sS()
void sample_move_d32u24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
Referenced by Jack::CopyAndConvertOut(), and Jack::CopyAndConvertOut().
sample_move_d32u24_sSs()
void sample_move_d32u24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_rect_d16_sS()
void sample_move_dither_rect_d16_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_rect_d16_sSs()
void sample_move_dither_rect_d16_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_rect_d24_sS()
void sample_move_dither_rect_d24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_rect_d24_sSs()
void sample_move_dither_rect_d24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_rect_d32u24_sS()
void sample_move_dither_rect_d32u24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_rect_d32u24_sSs()
void sample_move_dither_rect_d32u24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_shaped_d16_sS()
void sample_move_dither_shaped_d16_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_shaped_d16_sSs()
void sample_move_dither_shaped_d16_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_shaped_d24_sS()
void sample_move_dither_shaped_d24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_shaped_d24_sSs()
void sample_move_dither_shaped_d24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_shaped_d32u24_sS()
void sample_move_dither_shaped_d32u24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_shaped_d32u24_sSs()
void sample_move_dither_shaped_d32u24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_tri_d16_sS()
void sample_move_dither_tri_d16_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_tri_d16_sSs()
void sample_move_dither_tri_d16_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_tri_d24_sS()
void sample_move_dither_tri_d24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_tri_d24_sSs()
void sample_move_dither_tri_d24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_tri_d32u24_sS()
void sample_move_dither_tri_d32u24_sS (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dither_tri_d32u24_sSs()
void sample_move_dither_tri_d32u24_sSs (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dS_floatLE()
void sample_move_dS_floatLE (char * dst, jack_default_audio_sample_t * src, unsigned long nsamples, unsigned long dst_skip, dither_state_t * state)
sample_move_dS_s16()
void sample_move_dS_s16 (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
Referenced by Jack::CopyAndConvertIn(), and Jack::CopyAndConvertIn().
sample_move_dS_s16s()
void sample_move_dS_s16s (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
sample_move_dS_s24()
void sample_move_dS_s24 (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
Referenced by Jack::CopyAndConvertIn(), and Jack::CopyAndConvertIn().
sample_move_dS_s24s()
void sample_move_dS_s24s (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
sample_move_dS_s32()
void sample_move_dS_s32 (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
sample_move_dS_s32l24()
void sample_move_dS_s32l24 (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
sample_move_dS_s32l24s()
void sample_move_dS_s32l24s (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
sample_move_dS_s32s()
void sample_move_dS_s32s (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
sample_move_dS_s32u24()
void sample_move_dS_s32u24 (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
Referenced by Jack::CopyAndConvertIn(), and Jack::CopyAndConvertIn().
sample_move_dS_s32u24s()
void sample_move_dS_s32u24s (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long src_skip)
sample_move_floatLE_sSs()
void sample_move_floatLE_sSs (jack_default_audio_sample_t * dst, char * src, unsigned long nsamples, unsigned long dst_skip)