LMMS: lmms::PatternStore Class Reference
lmms::PatternStore Class Reference
#include <PatternStore.h>
Public Slots
void play ()
void stop ()
void updateComboBox ()
Signals
void trackUpdated ()
Signals inherited from lmms::TrackContainer
void trackAdded (lmms::Track *_track)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
PatternStore ()
~PatternStore () override=default
AutomatedValueMap automatedValuesAt (TimePos time, int clipNum) const override
void createClipsForPattern (int pattern)
void fixIncorrectPositions ()
bar_t lengthOfCurrentPattern ()
bar_t lengthOfPattern (int pattern) const
QString nodeName () const override
int numOfPatterns () const
virtual bool play (TimePos start, const fpp_t frames, const f_cnt_t frameBase, int clipNum=-1)
void removePattern (int pattern)
void swapPattern (int p1, int p2)
void updateAfterTrackAdd () override
void updatePatternTrack (Clip *clip)
Public Member Functions inherited from lmms::TrackContainer
TrackContainer ()
~TrackContainer () override
void addTrack (Track *_track)
void clearAllTracks ()
int countTracks (Track::Type _tt=Track::Type::Count) const
bool isEmpty () const
void loadSettings (const QDomElement &_this) override
void removeTrack (Track *_track)
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
void setType (Type newType)
const TrackList & tracks () const
Type type () const
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Private Member Functions
mapPropertyFromModel (int, currentPattern, setCurrentPattern, m_patternComboBoxModel)
Private Attributes
ComboBoxModel m_patternComboBoxModel
Friends
class gui::PatternEditorWindow
Additional Inherited Members
Public Types inherited from lmms::TrackContainer
using TrackList = std::vector<Track*>
enum class Type {
Pattern ,
Song
}
Static Public Member Functions inherited from lmms::TrackContainer
static const QString classNodeName ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Static Protected Member Functions inherited from lmms::TrackContainer
static AutomatedValueMap automatedValuesFromTracks (const TrackList &tracks, TimePos timeStart, int clipNum=-1)
Protected Attributes inherited from lmms::TrackContainer
QReadWriteLock m_tracksMutex
Detailed Description
Definition at line 64 of file PatternStore.h.
Constructor & Destructor Documentation
PatternStore()
lmms::PatternStore::PatternStore ()
Definition at line 37 of file PatternStore.cpp.
References lmms::TrackContainer::TrackContainer(), m_patternComboBoxModel, lmms::TrackContainer::Pattern, and lmms::TrackContainer::setType().
Referenced by mapPropertyFromModel().
~PatternStore()
lmms::PatternStore::~PatternStore () override default
References play(), and updateAfterTrackAdd().
Member Function Documentation
automatedValuesAt()
AutomatedValueMap lmms::PatternStore::automatedValuesAt (TimePos time, int clipNum) const override virtual
Reimplemented from lmms::TrackContainer.
Definition at line 219 of file PatternStore.cpp.
References lmms::TrackContainer::automatedValuesAt(), lmms::TimePos::getTicks(), lengthOfPattern(), and lmms::TimePos::ticksPerBar().
createClipsForPattern()
void lmms::PatternStore::createClipsForPattern (int pattern)
Definition at line 210 of file PatternStore.cpp.
References lmms::TrackContainer::Track, and lmms::TrackContainer::tracks().
Referenced by lmms::PatternTrack::PatternTrack().
fixIncorrectPositions()
void lmms::PatternStore::fixIncorrectPositions ()
Definition at line 155 of file PatternStore.cpp.
References i, numOfPatterns(), lmms::TrackContainer::Track, and lmms::TrackContainer::tracks().
Referenced by lmms::Song::loadProject().
lengthOfCurrentPattern()
bar_t lmms::PatternStore::lengthOfCurrentPattern () inline
Definition at line 82 of file PatternStore.h.
References lengthOfPattern().
Referenced by lmms::Song::processNextBuffer().
lengthOfPattern()
bar_t lmms::PatternStore::lengthOfPattern (int pattern) const
Definition at line 84 of file PatternStore.cpp.
References lmms::TimePos::nextFullBar(), lmms::TimePos::ticksPerBar(), lmms::TrackContainer::Track, and lmms::TrackContainer::tracks().
Referenced by lmms::PatternClip::PatternClip(), automatedValuesAt(), lengthOfCurrentPattern(), lmms::gui::ClipView::mouseMoveEvent(), lmms::gui::PatternClipView::paintEvent(), play(), and lmms::PatternTrack::play().
mapPropertyFromModel()
lmms::PatternStore::mapPropertyFromModel (int , currentPattern , setCurrentPattern , m_patternComboBoxModel) private
References PatternStore(), and m_patternComboBoxModel.
nodeName()
QString lmms::PatternStore::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 76 of file PatternStore.h.
numOfPatterns()
int lmms::PatternStore::numOfPatterns () const
Definition at line 104 of file PatternStore.cpp.
References lmms::TrackContainer::countTracks(), lmms::Engine::getSong(), and lmms::Track::Pattern.
Referenced by fixIncorrectPositions(), updateAfterTrackAdd(), and updateComboBox().
play [1/2]
void lmms::PatternStore::play () slot
Definition at line 170 of file PatternStore.cpp.
References lmms::Engine::getSong(), lmms::Song::Pattern, lmms::Song::playPattern(), and lmms::Song::togglePause().
play() [2/2]
bool lmms::PatternStore::play (TimePos start, const fpp_t frames, const f_cnt_t frameBase, int clipNum = -1) virtual
Definition at line 47 of file PatternStore.cpp.
References lengthOfPattern(), lmms::TimePos::ticksPerBar(), lmms::TrackContainer::Track, and lmms::TrackContainer::tracks().
Referenced by ~PatternStore(), lmms::gui::AutomationEditor::play(), and lmms::PatternTrack::play().
removePattern()
void lmms::PatternStore::removePattern (int pattern)
Definition at line 112 of file PatternStore.cpp.
References lmms::DefaultTicksPerBar, lmms::TrackContainer::Track, and lmms::TrackContainer::tracks().
Referenced by lmms::PatternTrack::~PatternTrack().
stop
void lmms::PatternStore::stop () slot
Definition at line 185 of file PatternStore.cpp.
References lmms::Engine::getSong(), and lmms::Song::stop().
Referenced by lmms::gui::AutomationEditor::stop().
swapPattern()
void lmms::PatternStore::swapPattern (int p1, int p2)
Definition at line 129 of file PatternStore.cpp.
References lmms::TrackContainer::Track, lmms::TrackContainer::tracks(), and updateComboBox().
Referenced by lmms::PatternTrack::swapPatternTracks().
trackUpdated
void lmms::PatternStore::trackUpdated () signal
Referenced by lmms::gui::PatternEditor::PatternEditor(), and updatePatternTrack().
updateAfterTrackAdd()
void lmms::PatternStore::updateAfterTrackAdd () override virtual
Reimplemented from lmms::TrackContainer.
Definition at line 73 of file PatternStore.cpp.
References lmms::Song::addPatternTrack(), lmms::Engine::getSong(), and numOfPatterns().
Referenced by ~PatternStore(), and lmms::Song::createNewProject().
updateComboBox
void lmms::PatternStore::updateComboBox () slot
Definition at line 193 of file PatternStore.cpp.
References lmms::PatternTrack::findPatternTrack(), i, m_patternComboBoxModel, lmms::Track::name(), and numOfPatterns().
Referenced by lmms::PatternTrack::PatternTrack(), lmms::PatternTrack::~PatternTrack(), and swapPattern().
updatePatternTrack()
void lmms::PatternStore::updatePatternTrack (Clip * clip)
Definition at line 142 of file PatternStore.cpp.
References lmms::Track::dataChanged(), lmms::DefaultTicksPerBar, lmms::PatternTrack::findPatternTrack(), lmms::Clip::startPosition(), and trackUpdated().
Referenced by lmms::MidiClip::updatePatternTrack().
Friends And Related Symbol Documentation
gui::PatternEditorWindow
friend class gui::PatternEditorWindow friend
Definition at line 110 of file PatternStore.h.
Member Data Documentation
m_patternComboBoxModel
ComboBoxModel lmms::PatternStore::m_patternComboBoxModel private
Definition at line 106 of file PatternStore.h.
Referenced by lmms::gui::PatternEditorWindow::PatternEditorWindow(), PatternStore(), mapPropertyFromModel(), and updateComboBox().
The documentation for this class was generated from the following files:
include/PatternStore.h
src/core/PatternStore.cpp