LMMS: hiir::Downsampler2xTpl< NC, DT, NCHN > Class Template Reference
hiir::Downsampler2xTpl< NC, DT, NCHN > Class Template Reference
#include <Downsampler2xTpl.h>
Public Types
typedef DT DataType
Public Member Functions
void clear_buffers () noexcept
void process_block (DataType out_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
void process_block_split (DataType out_l_ptr[], DataType out_h_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE DataType process_sample (const DataType in_ptr[2]) noexcept
hiir_FORCEINLINE void process_sample_split (DataType &low, DataType &high, const DataType in_ptr[2]) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = -1
static constexpr int _nbr_chn = NCHN
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataTpl< DataType >, NBR_COEFS+2 > Filter
Private Member Functions
bool operator!= (const Downsampler2xTpl< NC, DT, NCHN > &other)=delete
bool operator== (const Downsampler2xTpl< NC, DT, NCHN > &other)=delete
Private Attributes
Filter _filter
Detailed Description
template<int NC, typename DT, int NCHN>
class hiir::Downsampler2xTpl< NC, DT, NCHN >
Definition at line 64 of file Downsampler2xTpl.h.
Member Typedef Documentation
DataType
template<int NC, typename DT, int NCHN> typedef DT hiir::Downsampler2xTpl< NC, DT, NCHN >::DataType
Definition at line 74 of file Downsampler2xTpl.h.
Filter
template<int NC, typename DT, int NCHN> typedef std::array<StageDataTpl <DataType>, NBR_COEFS + 2> hiir::Downsampler2xTpl< NC, DT, NCHN >::Filter private
Definition at line 104 of file Downsampler2xTpl.h.
Member Function Documentation
clear_buffers()
template<int NC, typename DT, int NCHN> void hiir::Downsampler2xTpl< NC, DT, NCHN >::clear_buffers () noexcept
Definition at line 243 of file Downsampler2xTpl.hpp.
References _filter, i, and NBR_COEFS.
operator!=()
template<int NC, typename DT, int NCHN> bool hiir::Downsampler2xTpl< NC, DT, NCHN >::operator!= (const Downsampler2xTpl< NC, DT, NCHN > & other) private delete
operator==()
template<int NC, typename DT, int NCHN> bool hiir::Downsampler2xTpl< NC, DT, NCHN >::operator== (const Downsampler2xTpl< NC, DT, NCHN > & other) private delete
process_block()
template<int NC, typename DT, int NCHN> void hiir::Downsampler2xTpl< NC, DT, NCHN >::process_block (DataType out_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
Definition at line 126 of file Downsampler2xTpl.hpp.
References pos, and process_sample().
process_block_split()
template<int NC, typename DT, int NCHN> void hiir::Downsampler2xTpl< NC, DT, NCHN >::process_block_split (DataType out_l_ptr[], DataType out_h_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
Definition at line 207 of file Downsampler2xTpl.hpp.
References pos, and process_sample_split().
process_sample()
template<int NC, typename DT, int NCHN> Downsampler2xTpl< NC, DT, NCHN >::DataType hiir::Downsampler2xTpl< NC, DT, NCHN >::process_sample (const DataType in_ptr[2]) noexcept
Definition at line 94 of file Downsampler2xTpl.hpp.
References _filter, NBR_COEFS, and hiir::StageProcTpl< REMAINING, DT >::process_sample_pos().
Referenced by process_block().
process_sample_split()
template<int NC, typename DT, int NCHN> void hiir::Downsampler2xTpl< NC, DT, NCHN >::process_sample_split (DataType & low, DataType & high, const DataType in_ptr[2]) noexcept
Definition at line 165 of file Downsampler2xTpl.hpp.
References _filter, NBR_COEFS, and hiir::StageProcTpl< REMAINING, DT >::process_sample_pos().
Referenced by process_block_split().
set_coefs()
template<int NC, typename DT, int NCHN> void hiir::Downsampler2xTpl< NC, DT, NCHN >::set_coefs (const double coef_arr[]) noexcept
Definition at line 69 of file Downsampler2xTpl.hpp.
References _filter, i, and NBR_COEFS.
Member Data Documentation
_delay
template<int NC, typename DT, int NCHN> double hiir::Downsampler2xTpl< NC, DT, NCHN >::_delay = -1 static constexpr
Definition at line 77 of file Downsampler2xTpl.h.
_filter
template<int NC, typename DT, int NCHN> Filter hiir::Downsampler2xTpl< NC, DT, NCHN >::_filter private
Definition at line 106 of file Downsampler2xTpl.h.
Referenced by clear_buffers(), process_sample(), process_sample_split(), and set_coefs().
_nbr_chn
template<int NC, typename DT, int NCHN> int hiir::Downsampler2xTpl< NC, DT, NCHN >::_nbr_chn = NCHN static constexpr
Definition at line 75 of file Downsampler2xTpl.h.
NBR_COEFS
template<int NC, typename DT, int NCHN> int hiir::Downsampler2xTpl< NC, DT, NCHN >::NBR_COEFS = NC static constexpr
Definition at line 76 of file Downsampler2xTpl.h.
Referenced by clear_buffers(), process_sample(), process_sample_split(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Downsampler2xTpl.h
src/3rdparty/hiir/hiir/Downsampler2xTpl.hpp