LMMS: lmms::gui::FileSearchJob Class Reference
lmms::gui::FileSearchJob Class Reference
The FileSearchJob class allows for searching for files on the filesystem.
#include <FileSearchJob.h>
Classes
struct Task
Represents a search task to be carried out by the search job.
Signals
void finished ()
Emitted when the search job has finished searching.
void foundMatch (const QString &path)
Emitted when the search job has found a matching path.
void started ()
Emitted when the search job has started searching.
Public Member Functions
FileSearchJob (QObject *parent=nullptr)
Create a search job with the given parent (if any).
~FileSearchJob ()
Stop processing and destroys the object.
void search (Task task)
Commit to searching with the given task.
Private Member Functions
void runSearch (Task task)
Private Attributes
std::atomic_flag m_stop = ATOMIC_FLAG_INIT
std::future< void > m_task
Detailed Description
The FileSearchJob class allows for searching for files on the filesystem.
Searching occurs on a background thread, and results are emitted as a Qt slot back to the user.
Definition at line 36 of file FileSearchJob.h.
Constructor & Destructor Documentation
FileSearchJob()
lmms::gui::FileSearchJob::FileSearchJob (QObject * parent = nullptr)
Create a search job with the given parent (if any).
Definition at line 33 of file FileSearchJob.cpp.
Referenced by finished().
~FileSearchJob()
lmms::gui::FileSearchJob::~FileSearchJob ()
Stop processing and destroys the object.
Definition at line 38 of file FileSearchJob.cpp.
References m_stop, and m_task.
Member Function Documentation
finished
void lmms::gui::FileSearchJob::finished () signal
Emitted when the search job has finished searching.
References FileSearchJob().
Referenced by lmms::gui::FileBrowser::FileBrowser(), and runSearch().
foundMatch
void lmms::gui::FileSearchJob::foundMatch (const QString & path) signal
Emitted when the search job has found a matching path.
Referenced by lmms::gui::FileBrowser::FileBrowser(), and runSearch().
runSearch()
void lmms::gui::FileSearchJob::runSearch (Task task) private
Definition at line 60 of file FileSearchJob.cpp.
References lmms::gui::FileSearchJob::Task::dirFilters, lmms::gui::FileSearchJob::Task::extensions, lmms::gui::FileSearchJob::Task::filter, finished(), foundMatch(), m_stop, lmms::gui::FileSearchJob::Task::paths, and started().
Referenced by search().
search()
void lmms::gui::FileSearchJob::search (Task task)
Commit to searching with the given task.
Cancels any previous search. Callers can connect to the provided signals to interact with the search and its progress.
Definition at line 47 of file FileSearchJob.cpp.
References lmms::ThreadPool::instance(), m_stop, m_task, and runSearch().
started
void lmms::gui::FileSearchJob::started () signal
Emitted when the search job has started searching.
Referenced by lmms::gui::FileBrowser::FileBrowser(), and runSearch().
Member Data Documentation
m_stop
std::atomic_flag lmms::gui::FileSearchJob::m_stop = ATOMIC_FLAG_INIT private
Definition at line 74 of file FileSearchJob.h.
Referenced by ~FileSearchJob(), runSearch(), and search().
m_task
std::future<void> lmms::gui::FileSearchJob::m_task private
Definition at line 73 of file FileSearchJob.h.
Referenced by ~FileSearchJob(), and search().
The documentation for this class was generated from the following files:
include/FileSearchJob.h
src/gui/FileSearchJob.cpp