LMMS: Controlling error/information output
Controlling error/information output
Functions
void jack_set_error_function (void(*func)(const char *)) JACK_OPTIONAL_WEAK_EXPORT
Set the jack_error_callback for error message display.
void jack_set_info_function (void(*func)(const char *)) JACK_OPTIONAL_WEAK_EXPORT
Set the jack_info_callback for info message display.
Variables
void(* jack_error_callback)(const char *msg) JACK_OPTIONAL_WEAK_EXPORT
Display JACK error message.
void(* jack_info_callback)(const char *msg) JACK_OPTIONAL_WEAK_EXPORT
Display JACK info message.
Detailed Description
Function Documentation
jack_set_error_function()
void jack_set_error_function (void(* func)(const char *))
#include <jack.h>
Set the jack_error_callback for error message display.
Set it to NULL to restore default_jack_error_callback function.
The JACK library provides two built-in callbacks for this purpose: default_jack_error_callback() and silent_jack_error_callback().
References jack_info_callback, JACK_OPTIONAL_WEAK_EXPORT, and jack_set_error_function().
Referenced by jack_set_error_function(), main(), and main().
jack_set_info_function()
void jack_set_info_function (void(* func)(const char *))
#include <jack.h>
Set the jack_info_callback for info message display.
Set it to NULL to restore default_jack_info_callback function.
The JACK library provides two built-in callbacks for this purpose: default_jack_info_callback() and silent_jack_info_callback().
References jack_free(), JACK_OPTIONAL_WEAK_EXPORT, and jack_set_info_function().
Referenced by jack_set_info_function().
Variable Documentation
jack_error_callback
void(* jack_error_callback) (const char *msg) JACK_OPTIONAL_WEAK_EXPORT (const char * msg) extern
#include <jack.h>
Display JACK error message.
Set via jack_set_error_function(), otherwise a JACK-provided default will print msg (plus a newline) to stderr.
Parameters
msg error message text (no newline at end).
Definition at line 152 of file JackError.cpp.
jack_info_callback
void(* jack_info_callback) (const char *msg) JACK_OPTIONAL_WEAK_EXPORT (const char * msg) extern
#include <jack.h>
Display JACK info message.
Set via jack_set_info_function(), otherwise a JACK-provided default will print msg (plus a newline) to stdout.
Parameters
msg info message text (no newline at end).
Definition at line 153 of file JackError.cpp.