LMMS: lmms::gui::LcdWidget Class Reference
lmms::gui::LcdWidget Class Reference
#include <LcdWidget.h>
Public Slots
virtual void setMarginWidth (int width)
Public Member Functions
LcdWidget (int numDigits, const QString &style, QWidget *parent, const QString &name=QString(), bool leadingZero=false)
LcdWidget (int numDigits, QWidget *parent, const QString &name=QString(), bool leadingZero=false)
LcdWidget (QWidget *parent, const QString &name=QString(), bool leadingZero=false)
void addTextForValue (int value, const QString &text)
int cellHeight () const
int numDigits () const
void setLabel (const QString &label)
void setNumDigits (int n)
void setSeamless (bool left, bool right)
void setTextColor (const QColor &c)
void setTextShadowColor (const QColor &c)
void setValue (float value)
void setValue (int value)
QColor textColor () const
QColor textShadowColor () const
Protected Member Functions
void paintEvent (QPaintEvent *pe) override
virtual void updateSize ()
Properties
int numDigits
QColor textColor
QColor textShadowColor
Private Member Functions
void initUi (const QString &name, const QString &style)
to be called by ctors
Private Attributes
int m_cellHeight
int m_cellWidth
QString m_display
QString m_label
QPixmap m_lcdPixmap
bool m_leadingZero
int m_marginWidth
int m_numDigits
bool m_seamlessLeft
bool m_seamlessRight
QColor m_textColor
QMap< int, QString > m_textForValue
QColor m_textShadowColor
Static Private Attributes
static const int charsPerPixmap = 12
Detailed Description
Definition at line 36 of file LcdWidget.h.
Constructor & Destructor Documentation
LcdWidget() [1/3]
lmms::gui::LcdWidget::LcdWidget (QWidget * parent, const QString & name = QString(), bool leadingZero = false) explicit
Definition at line 40 of file LcdWidget.cpp.
References LcdWidget().
Referenced by lmms::gui::LcdSpinBox::LcdSpinBox(), lmms::gui::LcdSpinBox::LcdSpinBox(), LcdWidget(), and LcdWidget().
LcdWidget() [2/3]
lmms::gui::LcdWidget::LcdWidget (int numDigits, QWidget * parent, const QString & name = QString(), bool leadingZero = false)
Definition at line 48 of file LcdWidget.cpp.
References LcdWidget(), and numDigits.
LcdWidget() [3/3]
lmms::gui::LcdWidget::LcdWidget (int numDigits, const QString & style, QWidget * parent, const QString & name = QString(), bool leadingZero = false)
Definition at line 56 of file LcdWidget.cpp.
References initUi(), m_label, m_leadingZero, m_numDigits, m_seamlessLeft, m_seamlessRight, m_textColor, m_textShadowColor, and numDigits.
Member Function Documentation
addTextForValue()
void lmms::gui::LcdWidget::addTextForValue (int value, const QString & text) inline
Definition at line 54 of file LcdWidget.h.
References addTextForValue(), and m_textForValue.
Referenced by addTextForValue().
cellHeight()
int lmms::gui::LcdWidget::cellHeight () const inline
Definition at line 71 of file LcdWidget.h.
References m_cellHeight.
Referenced by lmms::gui::LcdSpinBox::mousePressEvent().
initUi()
void lmms::gui::LcdWidget::initUi (const QString & name, const QString & style) private
to be called by ctors
Definition at line 276 of file LcdWidget.cpp.
References charsPerPixmap, lmms::embed::getIconPixmap(), m_cellHeight, m_cellWidth, m_lcdPixmap, m_marginWidth, and updateSize().
Referenced by LcdWidget().
numDigits()
int lmms::gui::LcdWidget::numDigits () const inline
Definition at line 62 of file LcdWidget.h.
References inline, m_numDigits, and numDigits.
paintEvent()
void lmms::gui::LcdWidget::paintEvent (QPaintEvent * pe) override protected
Definition at line 137 of file LcdWidget.cpp.
References lmms::gui::adjustedToPixelSize(), charsPerPixmap, DEFAULT_FONT_SIZE, lmms::horizontalAdvance(), i, m_cellHeight, m_cellWidth, m_display, m_label, m_lcdPixmap, m_marginWidth, m_numDigits, m_seamlessLeft, m_seamlessRight, textColor, and textShadowColor.
setLabel()
void lmms::gui::LcdWidget::setLabel (const QString & label)
Definition at line 228 of file LcdWidget.cpp.
References m_label, and updateSize().
setMarginWidth
void lmms::gui::LcdWidget::setMarginWidth (int width) virtual slot
Definition at line 237 of file LcdWidget.cpp.
References m_marginWidth, and updateSize().
setNumDigits()
void lmms::gui::LcdWidget::setNumDigits (int n) inline
Definition at line 63 of file LcdWidget.h.
References m_numDigits, and updateSize().
setSeamless()
void lmms::gui::LcdWidget::setSeamless (bool left, bool right) inline
Definition at line 73 of file LcdWidget.h.
References m_seamlessLeft, m_seamlessRight, and updateSize().
setTextColor()
void lmms::gui::LcdWidget::setTextColor (const QColor & c)
Definition at line 116 of file LcdWidget.cpp.
References m_textColor.
setTextShadowColor()
void lmms::gui::LcdWidget::setTextShadowColor (const QColor & c)
Definition at line 129 of file LcdWidget.cpp.
References m_textShadowColor.
setValue() [1/2]
void lmms::gui::LcdWidget::setValue (float value)
Definition at line 89 of file LcdWidget.cpp.
References m_display, and setValue().
setValue() [2/2]
void lmms::gui::LcdWidget::setValue (int value)
Definition at line 69 of file LcdWidget.cpp.
References m_display, m_leadingZero, m_numDigits, and m_textForValue.
Referenced by setValue(), and lmms::gui::LcdSpinBox::update().
textColor()
QColor lmms::gui::LcdWidget::textColor () const
Definition at line 111 of file LcdWidget.cpp.
References m_textColor.
textShadowColor()
QColor lmms::gui::LcdWidget::textShadowColor () const
Definition at line 124 of file LcdWidget.cpp.
References m_textShadowColor.
updateSize()
void lmms::gui::LcdWidget::updateSize () protected virtual
Definition at line 247 of file LcdWidget.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, lmms::horizontalAdvance(), m_cellHeight, m_cellWidth, m_label, m_marginWidth, m_numDigits, m_seamlessLeft, and m_seamlessRight.
Referenced by initUi(), setLabel(), setMarginWidth(), setNumDigits(), and setSeamless().
Member Data Documentation
charsPerPixmap
const int lmms::gui::LcdWidget::charsPerPixmap = 12 static private
Definition at line 92 of file LcdWidget.h.
Referenced by initUi(), and paintEvent().
m_cellHeight
int lmms::gui::LcdWidget::m_cellHeight private
Definition at line 105 of file LcdWidget.h.
Referenced by cellHeight(), initUi(), paintEvent(), and updateSize().
m_cellWidth
int lmms::gui::LcdWidget::m_cellWidth private
Definition at line 104 of file LcdWidget.h.
Referenced by initUi(), paintEvent(), and updateSize().
m_display
QString lmms::gui::LcdWidget::m_display private
Definition at line 96 of file LcdWidget.h.
Referenced by paintEvent(), setValue(), and setValue().
m_label
QString lmms::gui::LcdWidget::m_label private
Definition at line 98 of file LcdWidget.h.
Referenced by LcdWidget(), paintEvent(), setLabel(), and updateSize().
m_lcdPixmap
QPixmap lmms::gui::LcdWidget::m_lcdPixmap private
Definition at line 99 of file LcdWidget.h.
Referenced by initUi(), and paintEvent().
m_leadingZero
bool lmms::gui::LcdWidget::m_leadingZero private
Definition at line 110 of file LcdWidget.h.
Referenced by LcdWidget(), and setValue().
m_marginWidth
int lmms::gui::LcdWidget::m_marginWidth private
Definition at line 107 of file LcdWidget.h.
Referenced by initUi(), paintEvent(), setMarginWidth(), and updateSize().
m_numDigits
int lmms::gui::LcdWidget::m_numDigits private
Definition at line 106 of file LcdWidget.h.
Referenced by LcdWidget(), numDigits(), paintEvent(), setNumDigits(), setValue(), and updateSize().
m_seamlessLeft
bool lmms::gui::LcdWidget::m_seamlessLeft private
Definition at line 108 of file LcdWidget.h.
Referenced by LcdWidget(), paintEvent(), setSeamless(), and updateSize().
m_seamlessRight
bool lmms::gui::LcdWidget::m_seamlessRight private
Definition at line 109 of file LcdWidget.h.
Referenced by LcdWidget(), paintEvent(), setSeamless(), and updateSize().
m_textColor
QColor lmms::gui::LcdWidget::m_textColor private
Definition at line 101 of file LcdWidget.h.
Referenced by LcdWidget(), setTextColor(), and textColor().
m_textForValue
QMap<int, QString> lmms::gui::LcdWidget::m_textForValue private
Definition at line 94 of file LcdWidget.h.
Referenced by addTextForValue(), and setValue().
m_textShadowColor
QColor lmms::gui::LcdWidget::m_textShadowColor private
Definition at line 102 of file LcdWidget.h.
Referenced by LcdWidget(), setTextShadowColor(), and textShadowColor().
Property Documentation
numDigits
int lmms::gui::LcdWidget::numDigits read write
Definition at line 60 of file LcdWidget.h.
Referenced by lmms::gui::LcdSpinBox::LcdSpinBox(), lmms::gui::LcdSpinBox::LcdSpinBox(), LcdWidget(), LcdWidget(), lmms::gui::MixerChannelLcdSpinBox::MixerChannelLcdSpinBox(), and numDigits().
textColor
QColor lmms::gui::LcdWidget::textColor read write
Definition at line 41 of file LcdWidget.h.
Referenced by paintEvent().
textShadowColor
QColor lmms::gui::LcdWidget::textShadowColor read write
Definition at line 42 of file LcdWidget.h.
Referenced by paintEvent().
The documentation for this class was generated from the following files:
include/LcdWidget.h
src/gui/widgets/LcdWidget.cpp