LMMS: Jack::JackException Class Reference
Jack::JackException Class Reference
Exception base class.
#include <JackException.h>
Public Member Functions
JackException (char *msg)
JackException (const char *msg)
JackException (const std::string &msg)
std::string Message ()
void PrintMessage ()
Detailed Description
Exception base class.
Definition at line 43 of file JackException.h.
Constructor & Destructor Documentation
JackException() [1/3]
Jack::JackException::JackException (const std::string & msg) inline
Definition at line 47 of file JackException.h.
Referenced by Jack::JackNetException::JackNetException(), Jack::JackNetException::JackNetException(), Jack::JackNetException::JackNetException(), Jack::JackNetException::JackNetException(), Jack::JackQuitException::JackQuitException(), Jack::JackQuitException::JackQuitException(), Jack::JackQuitException::JackQuitException(), Jack::JackQuitException::JackQuitException(), Jack::JackTemporaryException::JackTemporaryException(), Jack::JackTemporaryException::JackTemporaryException(), Jack::JackTemporaryException::JackTemporaryException(), and Jack::JackTemporaryException::JackTemporaryException().
JackException() [2/3]
Jack::JackException::JackException (char * msg) inline
Definition at line 49 of file JackException.h.
JackException() [3/3]
Jack::JackException::JackException (const char * msg) inline
Definition at line 51 of file JackException.h.
Member Function Documentation
Message()
std::string Jack::JackException::Message () inline
Definition at line 54 of file JackException.h.
PrintMessage()
void Jack::JackException::PrintMessage ()
Definition at line 26 of file JackException.cpp.
References jack_info().
Referenced by Jack::JackNetAdapter::Execute(), Jack::JackNetExtSlave::Execute(), Jack::JackRestartThreadedDriver::Execute(), and Jack::JackWaitThreadedDriver::ExecuteReal().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackException.h
src/3rdparty/jack2/common/JackException.cpp