LMMS: lmms::SharedMemory< T > Class Template Reference
lmms::SharedMemory< T > Class Template Reference
#include <SharedMemory.h>
Public Member Functions
SharedMemory ()=default
SharedMemory (SharedMemory &&)=default
void attach (std::string key)
void create ()
void create (std::string key)
void detach () noexcept
T * get () const noexcept
const std::string & key () const noexcept
operator bool () const noexcept
T & operator* () const noexcept
T * operator-> () const noexcept
SharedMemory & operator= (SharedMemory &&)=default
std::size_t size () const noexcept
std::size_t size_bytes () const noexcept
Private Attributes
detail::SharedMemoryData m_data
Detailed Description
template<typename T>
class lmms::SharedMemory< T >
Definition at line 80 of file SharedMemory.h.
Constructor & Destructor Documentation
SharedMemory() [1/2]
template<typename T> lmms::SharedMemory< T >::SharedMemory () default
Referenced by SharedMemory(), and operator=().
SharedMemory() [2/2]
template<typename T> lmms::SharedMemory< T >::SharedMemory (SharedMemory< T > &&) default
References SharedMemory().
Member Function Documentation
attach()
template<typename T> void lmms::SharedMemory< T >::attach (std::string key) inline
Definition at line 90 of file SharedMemory.h.
References key(), and m_data.
create() [1/2]
template<typename T> void lmms::SharedMemory< T >::create () inline
Definition at line 100 of file SharedMemory.h.
References m_data.
create() [2/2]
template<typename T> void lmms::SharedMemory< T >::create (std::string key) inline
Definition at line 95 of file SharedMemory.h.
References key(), and m_data.
detach()
template<typename T> void lmms::SharedMemory< T >::detach () inline noexcept
Definition at line 105 of file SharedMemory.h.
References m_data.
get()
template<typename T> T * lmms::SharedMemory< T >::get () const inline noexcept
Definition at line 111 of file SharedMemory.h.
References m_data.
key()
template<typename T> const std::string & lmms::SharedMemory< T >::key () const inline noexcept
Definition at line 110 of file SharedMemory.h.
References m_data.
Referenced by attach(), and create().
operator bool()
template<typename T> lmms::SharedMemory< T >::operator bool () const inline explicit noexcept
Definition at line 118 of file SharedMemory.h.
References lmms::detail::SharedMemoryData::get().
operator*()
template<typename T> T & lmms::SharedMemory< T >::operator* () const inline noexcept
Definition at line 117 of file SharedMemory.h.
References lmms::detail::SharedMemoryData::get().
operator->()
template<typename T> T * lmms::SharedMemory< T >::operator-> () const inline noexcept
Definition at line 116 of file SharedMemory.h.
References lmms::detail::SharedMemoryData::get().
operator=()
template<typename T> SharedMemory & lmms::SharedMemory< T >::operator= (SharedMemory< T > &&) default
References SharedMemory().
size()
template<typename T> std::size_t lmms::SharedMemory< T >::size () const inline noexcept
Definition at line 113 of file SharedMemory.h.
References lmms::detail::SharedMemoryData::get().
size_bytes()
template<typename T> std::size_t lmms::SharedMemory< T >::size_bytes () const inline noexcept
Definition at line 114 of file SharedMemory.h.
References lmms::detail::SharedMemoryData::get().
Member Data Documentation
m_data
template<typename T> detail::SharedMemoryData lmms::SharedMemory< T >::m_data private
Definition at line 121 of file SharedMemory.h.
Referenced by attach(), create(), create(), detach(), get(), and key().
The documentation for this class was generated from the following file:
include/SharedMemory.h