LMMS: lmms::AudioSampleRecorder Class Reference
lmms::AudioSampleRecorder Class Reference
#include <AudioSampleRecorder.h>
Public Member Functions
AudioSampleRecorder (const ch_cnt_t _channels, bool &_success_ful, AudioEngine *audioEngine)
~AudioSampleRecorder () override
std::shared_ptr< const SampleBuffer > createSampleBuffer ()
f_cnt_t framesRecorded () const
Public Member Functions inherited from lmms::AudioDevice
AudioDevice (const ch_cnt_t _channels, AudioEngine *audioEngine)
virtual ~AudioDevice ()
void lock ()
void processNextBuffer ()
virtual void registerPort (AudioBusHandle *port)
virtual void renamePort (AudioBusHandle *port)
sample_rate_t sampleRate () const
virtual void startProcessing ()
virtual void stopProcessing ()
bool supportsCapture () const
void unlock ()
virtual void unregisterPort (AudioBusHandle *port)
Private Types
using BufferList = QList<QPair<SampleFrame*, fpp_t>>
Private Member Functions
void writeBuffer (const SampleFrame *_ab, const fpp_t _frames) override
Private Attributes
BufferList m_buffers
Additional Inherited Members
Protected Member Functions inherited from lmms::AudioDevice
AudioEngine * audioEngine ()
ch_cnt_t channels () const
void clearS16Buffer (int_sample_t *_outbuf, const fpp_t _frames)
int convertToS16 (const SampleFrame *_ab, const fpp_t _frames, int_sample_t *_output_buffer, const bool _convert_endian=false)
fpp_t getNextBuffer (SampleFrame *_ab)
void setSampleRate (const sample_rate_t _new_sr)
Static Protected Member Functions inherited from lmms::AudioDevice
static void stopProcessingThread (QThread *thread)
Protected Attributes inherited from lmms::AudioDevice
bool m_supportsCapture
Detailed Description
Definition at line 41 of file AudioSampleRecorder.h.
Member Typedef Documentation
BufferList
using lmms::AudioSampleRecorder::BufferList = QList<QPair<SampleFrame*, fpp_t>> private
Definition at line 53 of file AudioSampleRecorder.h.
Constructor & Destructor Documentation
AudioSampleRecorder()
lmms::AudioSampleRecorder::AudioSampleRecorder (const ch_cnt_t _channels, bool & _success_ful, AudioEngine * audioEngine)
Definition at line 35 of file AudioSampleRecorder.cpp.
References lmms::AudioDevice::AudioDevice(), and m_buffers.
~AudioSampleRecorder()
lmms::AudioSampleRecorder::~AudioSampleRecorder () override
Definition at line 47 of file AudioSampleRecorder.cpp.
References m_buffers.
Member Function Documentation
createSampleBuffer()
std::shared_ptr< const SampleBuffer > lmms::AudioSampleRecorder::createSampleBuffer ()
Definition at line 69 of file AudioSampleRecorder.cpp.
References framesRecorded(), m_buffers, and lmms::AudioDevice::sampleRate().
framesRecorded()
f_cnt_t lmms::AudioSampleRecorder::framesRecorded () const
Definition at line 59 of file AudioSampleRecorder.cpp.
References m_buffers.
Referenced by createSampleBuffer().
writeBuffer()
void lmms::AudioSampleRecorder::writeBuffer (const SampleFrame * _ab, const fpp_t _frames) override private virtual
Reimplemented from lmms::AudioDevice.
Definition at line 87 of file AudioSampleRecorder.cpp.
References lmms::DEFAULT_CHANNELS, and m_buffers.
Member Data Documentation
m_buffers
BufferList lmms::AudioSampleRecorder::m_buffers private
Definition at line 54 of file AudioSampleRecorder.h.
Referenced by AudioSampleRecorder(), ~AudioSampleRecorder(), createSampleBuffer(), framesRecorded(), and writeBuffer().
The documentation for this class was generated from the following files:
include/AudioSampleRecorder.h
src/core/audio/AudioSampleRecorder.cpp