LMMS: lmms::SharedMemory< T[]> Class Template Reference
lmms::SharedMemory< T[]> Class Template Reference
#include <SharedMemory.h>
Public Member Functions
SharedMemory ()=default
SharedMemory (SharedMemory &&)=default
void attach (std::string key)
void create (std::size_t size)
void create (std::string key, std::size_t size)
void detach () noexcept
T * get () const noexcept
const std::string & key () const noexcept
operator bool () const noexcept
T & operator* () const noexcept
T * operator-> () const noexcept
SharedMemory & operator= (SharedMemory &&)=default
T & operator[] (std::size_t index) const noexcept
std::size_t size () const noexcept
std::size_t size_bytes () const noexcept
Private Attributes
detail::SharedMemoryData m_data
Detailed Description
template<typename T>
class lmms::SharedMemory< T[]>
Definition at line 125 of file SharedMemory.h.
Constructor & Destructor Documentation
SharedMemory() [1/2]
template<typename T> lmms::SharedMemory< T[]>::SharedMemory () default
Referenced by SharedMemory(), and operator=().
SharedMemory() [2/2]
template<typename T> lmms::SharedMemory< T[]>::SharedMemory (SharedMemory< T[]> &&) default
References SharedMemory().
Member Function Documentation
attach()
template<typename T> void lmms::SharedMemory< T[]>::attach (std::string key) inline
Definition at line 135 of file SharedMemory.h.
References key(), and m_data.
create() [1/2]
template<typename T> void lmms::SharedMemory< T[]>::create (std::size_t size) inline
Definition at line 145 of file SharedMemory.h.
References m_data, and size().
create() [2/2]
template<typename T> void lmms::SharedMemory< T[]>::create (std::string key, std::size_t size) inline
Definition at line 140 of file SharedMemory.h.
References key(), m_data, and size().
detach()
template<typename T> void lmms::SharedMemory< T[]>::detach () inline noexcept
Definition at line 150 of file SharedMemory.h.
References m_data.
get()
template<typename T> T * lmms::SharedMemory< T[]>::get () const inline noexcept
Definition at line 156 of file SharedMemory.h.
References m_data.
Referenced by operator bool(), and operator[]().
key()
template<typename T> const std::string & lmms::SharedMemory< T[]>::key () const inline noexcept
Definition at line 155 of file SharedMemory.h.
References m_data.
Referenced by attach(), and create().
operator bool()
template<typename T> lmms::SharedMemory< T[]>::operator bool () const inline explicit noexcept
Definition at line 162 of file SharedMemory.h.
References get().
operator*()
T & lmms::SharedMemory< T >::operator* () const inline noexcept
Definition at line 117 of file SharedMemory.h.
operator->()
T * lmms::SharedMemory< T >::operator-> () const inline noexcept
Definition at line 116 of file SharedMemory.h.
operator=()
template<typename T> SharedMemory & lmms::SharedMemory< T[]>::operator= (SharedMemory< T[]> &&) default
References SharedMemory().
operator[]()
template<typename T> T & lmms::SharedMemory< T[]>::operator[] (std::size_t index) const inline noexcept
Definition at line 161 of file SharedMemory.h.
References get().
size()
template<typename T> std::size_t lmms::SharedMemory< T[]>::size () const inline noexcept
Definition at line 158 of file SharedMemory.h.
References m_data.
Referenced by create(), and create().
size_bytes()
template<typename T> std::size_t lmms::SharedMemory< T[]>::size_bytes () const inline noexcept
Definition at line 159 of file SharedMemory.h.
References m_data.
Member Data Documentation
m_data
template<typename T> detail::SharedMemoryData lmms::SharedMemory< T[]>::m_data private
Definition at line 165 of file SharedMemory.h.
Referenced by attach(), create(), create(), detach(), get(), key(), size(), and size_bytes().
The documentation for this class was generated from the following file:
include/SharedMemory.h