LMMS: lmms::PluginFactory Class Reference
lmms::PluginFactory Class Reference
#include <PluginFactory.h>
Classes
struct PluginInfo
struct PluginInfoAndKey
Public Types
using DescriptorMap = QMultiMap<Plugin::Type, Plugin::Descriptor*>
using PluginInfoList = QList<PluginInfo>
Public Slots
void discoverPlugins ()
Public Member Functions
PluginFactory ()
~PluginFactory ()=default
Plugin::DescriptorList descriptors () const
Returns a list of all found plugins' descriptors.
Plugin::DescriptorList descriptors (Plugin::Type type) const
QString errorString (QString pluginName) const
When loading a library fails during discovery, the error string is saved.
PluginInfo pluginInfo (const char *name) const
Returns the PluginInfo object of the plugin with the given name.
const PluginInfoList & pluginInfos () const
Returns a list of all found plugins' PluginFactory::PluginInfo objects.
PluginInfoAndKey pluginSupportingExtension (const QString &ext)
Returns a plugin that support the given file extension.
Static Public Member Functions
static QList< QRegularExpression > getExcludePatterns (const char *envVar)
static PluginFactory * instance ()
Returns the singleton instance of PluginFactory.
static void setupSearchPaths ()
Static Private Member Functions
static void filterPlugins (QSet< QFileInfo > &files)
Private Attributes
DescriptorMap m_descriptors
QHash< QString, QString > m_errors
std::vector< std::string > m_garbage
cleaned up at destruction
QMap< QString, PluginInfoAndKey > m_pluginByExt
PluginInfoList m_pluginInfos
Static Private Attributes
static std::unique_ptr< PluginFactory > s_instance
Detailed Description
Definition at line 44 of file PluginFactory.h.
Member Typedef Documentation
DescriptorMap
using lmms::PluginFactory::DescriptorMap = QMultiMap<Plugin::Type, Plugin::Descriptor*>
Definition at line 57 of file PluginFactory.h.
PluginInfoList
using lmms::PluginFactory::PluginInfoList = QList<PluginInfo>
Definition at line 56 of file PluginFactory.h.
Constructor & Destructor Documentation
PluginFactory()
lmms::PluginFactory::PluginFactory ()
Definition at line 56 of file PluginFactory.cpp.
References discoverPlugins(), and setupSearchPaths().
Referenced by ~PluginFactory(), and instance().
~PluginFactory()
lmms::PluginFactory::~PluginFactory () default
References PluginFactory(), descriptors(), getExcludePatterns(), instance(), and setupSearchPaths().
Member Function Documentation
descriptors() [1/2]
Plugin::DescriptorList lmms::PluginFactory::descriptors () const
Returns a list of all found plugins' descriptors.
Definition at line 108 of file PluginFactory.cpp.
References m_descriptors.
Referenced by ~PluginFactory(), lmms::gui::PluginBrowser::addPlugins(), and discoverPlugins().
descriptors() [2/2]
Plugin::DescriptorList lmms::PluginFactory::descriptors (Plugin::Type type) const
Definition at line 113 of file PluginFactory.cpp.
References m_descriptors.
discoverPlugins
void lmms::PluginFactory::discoverPlugins () slot
Definition at line 144 of file PluginFactory.cpp.
References lmms::PluginFactory::PluginInfo::descriptor, descriptors(), file, lmms::PluginFactory::PluginInfo::file, filterPlugins(), lmms::PluginFactory::PluginInfoAndKey::info, lmms::PluginFactory::PluginInfoAndKey::key, lmms::PluginFactory::PluginInfo::library, lmms::Plugin::Descriptor::SubPluginFeatures::listSubPluginKeys(), m_descriptors, m_errors, m_pluginByExt, m_pluginInfos, lmms::nameFilters(), pluginInfos(), lmms::Plugin::Descriptor::subPluginFeatures, lmms::Plugin::Descriptor::supportedFileTypes, and lmms::Plugin::Descriptor::type.
Referenced by PluginFactory().
errorString()
QString lmms::PluginFactory::errorString (QString pluginName) const
When loading a library fails during discovery, the error string is saved.
It can be retrieved by calling this function.
Definition at line 138 of file PluginFactory.cpp.
References m_errors.
filterPlugins()
void lmms::PluginFactory::filterPlugins (QSet< QFileInfo > & files) static private
Definition at line 275 of file PluginFactory.cpp.
References getExcludePatterns().
Referenced by discoverPlugins().
getExcludePatterns()
QList< QRegularExpression > lmms::PluginFactory::getExcludePatterns (const char * envVar) static
Definition at line 253 of file PluginFactory.cpp.
Referenced by lmms::LadspaManager::LadspaManager(), ~PluginFactory(), and filterPlugins().
instance()
PluginFactory * lmms::PluginFactory::instance () static
Returns the singleton instance of PluginFactory.
You won't need to call this directly, use pluginFactory instead.
Definition at line 95 of file PluginFactory.cpp.
References PluginFactory(), and s_instance.
Referenced by ~PluginFactory(), lmms::gui::FileBrowserTreeWidget::getContextActions(), and lmms::getPluginFactory().
pluginInfo()
PluginFactory::PluginInfo lmms::PluginFactory::pluginInfo (const char * name) const
Returns the PluginInfo object of the plugin with the given name.
If the plugin is not found, an empty PluginInfo is returned (use PluginInfo::isNull() to check this).
Definition at line 128 of file PluginFactory.cpp.
References m_pluginInfos.
Referenced by lmms::Plugin::instantiate(), and lmms::Plugin::instantiateWithKey().
pluginInfos()
const PluginFactory::PluginInfoList & lmms::PluginFactory::pluginInfos () const
Returns a list of all found plugins' PluginFactory::PluginInfo objects.
Definition at line 118 of file PluginFactory.cpp.
References m_pluginInfos.
Referenced by discoverPlugins().
pluginSupportingExtension()
PluginFactory::PluginInfoAndKey lmms::PluginFactory::pluginSupportingExtension (const QString & ext)
Returns a plugin that support the given file extension.
Definition at line 123 of file PluginFactory.cpp.
References m_pluginByExt.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::gui::InstrumentTrackWindow::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), and lmms::gui::FileBrowserTreeWidget::handleFile().
setupSearchPaths()
void lmms::PluginFactory::setupSearchPaths () static
Definition at line 62 of file PluginFactory.cpp.
References lmms::ConfigManager::inst().
Referenced by lmms::LadspaManager::LadspaManager(), PluginFactory(), and ~PluginFactory().
Member Data Documentation
m_descriptors
DescriptorMap lmms::PluginFactory::m_descriptors private
Definition at line 98 of file PluginFactory.h.
Referenced by descriptors(), descriptors(), and discoverPlugins().
m_errors
QHash<QString, QString> lmms::PluginFactory::m_errors private
Definition at line 104 of file PluginFactory.h.
Referenced by discoverPlugins(), and errorString().
m_garbage
std::vector<std::string> lmms::PluginFactory::m_garbage private
cleaned up at destruction
Definition at line 102 of file PluginFactory.h.
m_pluginByExt
QMap<QString, PluginInfoAndKey> lmms::PluginFactory::m_pluginByExt private
Definition at line 101 of file PluginFactory.h.
Referenced by discoverPlugins(), and pluginSupportingExtension().
m_pluginInfos
PluginInfoList lmms::PluginFactory::m_pluginInfos private
Definition at line 99 of file PluginFactory.h.
Referenced by discoverPlugins(), pluginInfo(), and pluginInfos().
s_instance
std::unique_ptr< PluginFactory > lmms::PluginFactory::s_instance static private
Definition at line 106 of file PluginFactory.h.
Referenced by instance(), and lmms::nameFilters().
The documentation for this class was generated from the following files:
include/PluginFactory.h
src/core/PluginFactory.cpp