LMMS: Jack::JackBoomerDriver::JackBoomerDriverInput Class Reference
Jack::JackBoomerDriver::JackBoomerDriverInput Class Reference
Public Member Functions
JackBoomerDriverInput (JackBoomerDriver *driver)
~JackBoomerDriverInput ()
bool Execute ()
bool Init ()
Called once when the thread is started.
Private Attributes
JackBoomerDriver * fDriver
Additional Inherited Members
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Detailed Description
Definition at line 52 of file JackBoomerDriver.h.
Constructor & Destructor Documentation
JackBoomerDriverInput()
Jack::JackBoomerDriver::JackBoomerDriverInput::JackBoomerDriverInput (JackBoomerDriver * driver) inline
Definition at line 60 of file JackBoomerDriver.h.
References Jack::JackBoomerDriver::JackBoomerDriver(), driver, and fDriver.
~JackBoomerDriverInput()
Jack::JackBoomerDriver::JackBoomerDriverInput::~JackBoomerDriverInput () inline
Definition at line 62 of file JackBoomerDriver.h.
Member Function Documentation
Execute()
bool Jack::JackBoomerDriver::JackBoomerDriverInput::Execute () virtual
Implements Jack::JackRunnableInterface.
Definition at line 639 of file JackBoomerDriver.cpp.
References Jack::CopyAndConvertIn(), fDriver, GetMicroSeconds(), i, jack_error, and jack_log().
Init()
bool Jack::JackBoomerDriver::JackBoomerDriverInput::Init () virtual
Called once when the thread is started.
Reimplemented from Jack::JackRunnableInterface.
Definition at line 624 of file JackBoomerDriver.cpp.
References fDriver, Jack::GetEngineControl(), jack_error, jack_log(), and set_threaded_log_function().
Member Data Documentation
fDriver
JackBoomerDriver* Jack::JackBoomerDriver::JackBoomerDriverInput::fDriver private
Definition at line 56 of file JackBoomerDriver.h.
Referenced by JackBoomerDriverInput(), Execute(), and Init().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/solaris/oss/JackBoomerDriver.h
src/3rdparty/jack2/solaris/oss/JackBoomerDriver.cpp