LMMS: lmms::PixmapLoader Class Reference
lmms::PixmapLoader Class Reference
#include <embed.h>
Public Member Functions
PixmapLoader ()=default
PixmapLoader (std::string name, const char *const *xpm=nullptr)
virtual ~PixmapLoader ()=default
auto pixmap (int width=-1, int height=-1) const -> QPixmap
auto pixmapName () const -> const std::string &
Private Attributes
std::string m_name
const char *const * m_xpm = nullptr
Detailed Description
Definition at line 76 of file embed.h.
Constructor & Destructor Documentation
PixmapLoader() [1/2]
lmms::PixmapLoader::PixmapLoader () default
PixmapLoader() [2/2]
lmms::PixmapLoader::PixmapLoader (std::string name, const char *const * xpm = nullptr) inline explicit
Definition at line 81 of file embed.h.
References m_name, and m_xpm.
~PixmapLoader()
virtual lmms::PixmapLoader::~PixmapLoader () virtual default
Member Function Documentation
pixmap()
auto lmms::PixmapLoader::pixmap (int width = -1, int height = -1) const->QPixmap inline
Definition at line 88 of file embed.h.
References lmms::embed::getIconPixmap(), m_name, and m_xpm.
Referenced by lmms::gui::ToolPluginView::ToolPluginView(), lmms::gui::InstrumentTrackView::determinePixmap(), lmms::gui::ComboBox::paintEvent(), lmms::gui::TrackLabelButton::paintEvent(), and lmms::gui::EffectSelectDialog::rowChanged().
pixmapName()
auto lmms::PixmapLoader::pixmapName () const->conststd::string & inline
Definition at line 93 of file embed.h.
References m_name.
Referenced by lmms::gui::TrackLabelButton::paintEvent().
Member Data Documentation
m_name
std::string lmms::PixmapLoader::m_name private
Definition at line 96 of file embed.h.
Referenced by PixmapLoader(), pixmap(), and pixmapName().
m_xpm
const char* const* lmms::PixmapLoader::m_xpm = nullptr private
Definition at line 97 of file embed.h.
Referenced by PixmapLoader(), and pixmap().
The documentation for this class was generated from the following file:
include/embed.h