LMMS: src/3rdparty/jack2/common/jack/jslist.h File Reference
jslist.h File Reference
#include <stdlib.h>
#include <jack/systemdeps.h>
Classes
struct _JSList
Macros
#define jack_slist_next(slist)
Typedefs
typedef int(* JCompareFunc) (void *a, void *b)
typedef struct _JSList JSList
Functions
static __inline__ JSList * jack_slist_alloc (void)
static __inline__ JSList * jack_slist_append (JSList *list, void *data)
static __inline__ JSList * jack_slist_copy (JSList *list)
static __inline__ JSList * jack_slist_find (JSList *list, void *data)
static __inline__ void jack_slist_free (JSList *list)
static __inline__ void jack_slist_free_1 (JSList *list)
static __inline__ JSList * jack_slist_last (JSList *list)
static __inline__ unsigned int jack_slist_length (JSList *list)
static __inline__ JSList * jack_slist_prepend (JSList *list, void *data)
static __inline__ JSList * jack_slist_remove (JSList *list, void *data)
static __inline__ JSList * jack_slist_remove_link (JSList *list, JSList *link)
static __inline__ JSList * jack_slist_sort (JSList *list, JCompareFunc compare_func)
static __inline__ JSList * jack_slist_sort_merge (JSList *l1, JSList *l2, JCompareFunc compare_func)
Macro Definition Documentation
jack_slist_next
#define jack_slist_next (slist)
Value:
((slist) ? (((JSList *)(slist))->next) : NULL)
Definition at line 74 of file jslist.h.
Referenced by Jack::JackAlsaAdapter::JackAlsaAdapter(), Jack::JackAudioAdapter::JackAudioAdapter(), Jack::JackNetAdapter::JackNetAdapter(), Jack::JackNetMasterManager::JackNetMasterManager(), Jack::JackOSSAdapter::JackOSSAdapter(), Jack::JackPortAudioAdapter::JackPortAudioAdapter(), Jack::JackProfiler::JackProfiler(), Jack::JackSapaProxy::JackSapaProxy(), driver_initialize(), Jack::driver_initialize(), jack_find_driver_descriptor(), jack_get_descriptor(), jackctl_get_parameter(), jackctl_server_get_driver(), jackctl_server_get_internal(), print_server_drivers(), print_server_internals(), Jack::JackNetOneDriver::render_jack_ports_to_payload_float(), and Jack::JackNetOneDriver::render_payload_to_jack_ports_float().
Typedef Documentation
JCompareFunc
typedef int(* JCompareFunc) (void *a, void *b)
Definition at line 37 of file jslist.h.
JSList
typedef struct _JSList JSList
Definition at line 35 of file jslist.h.
Function Documentation
jack_slist_alloc()
__inline__ JSList * jack_slist_alloc (void) static
Definition at line 46 of file jslist.h.
References _JSList::data, and _JSList::next.
Referenced by jack_slist_append(), and jack_slist_copy().
jack_slist_append()
__inline__ JSList * jack_slist_append (JSList * list, void * data) static
Definition at line 222 of file jslist.h.
References _JSList::data, jack_slist_alloc(), jack_slist_last(), and _JSList::next.
Referenced by Jack::JackNetOneDriver::AllocPorts(), jack_drivers_load(), jack_internals_load(), jack_parse_driver_params(), jackctl_add_parameter(), jackctl_create_param_list(), jackctl_drivers_load(), jackctl_internals_load(), jackctl_server_add_slave(), and Jack::JackArgParser::ParseParams().
jack_slist_copy()
__inline__ JSList * jack_slist_copy (JSList * list) static
Definition at line 198 of file jslist.h.
References _JSList::data, jack_slist_alloc(), and _JSList::next.
jack_slist_find()
__inline__ JSList * jack_slist_find (JSList * list, void * data) static
Definition at line 184 of file jslist.h.
References _JSList::data, and _JSList::next.
jack_slist_free()
__inline__ void jack_slist_free (JSList * list) static
Definition at line 118 of file jslist.h.
References _JSList::next.
Referenced by jack_slist_remove().
jack_slist_free_1()
__inline__ void jack_slist_free_1 (JSList * list) static
Definition at line 129 of file jslist.h.
Referenced by Jack::JackNetOneDriver::FreePorts().
jack_slist_last()
__inline__ JSList * jack_slist_last (JSList * list) static
Definition at line 77 of file jslist.h.
References _JSList::next.
Referenced by jack_slist_append().
jack_slist_length()
__inline__ unsigned int jack_slist_length (JSList * list) static
Definition at line 169 of file jslist.h.
References _JSList::next.
jack_slist_prepend()
__inline__ JSList * jack_slist_prepend (JSList * list, void * data) static
Definition at line 61 of file jslist.h.
References _JSList::data, and _JSList::next.
jack_slist_remove()
__inline__ JSList * jack_slist_remove (JSList * list, void * data) static
Definition at line 138 of file jslist.h.
References _JSList::data, jack_slist_free(), and _JSList::next.
Referenced by jackctl_server_remove_slave().
jack_slist_remove_link()
__inline__ JSList * jack_slist_remove_link (JSList * list, JSList * link) static
Definition at line 89 of file jslist.h.
References _JSList::next.
Referenced by Jack::JackNetOneDriver::FreePorts().
jack_slist_sort()
__inline__ JSList * jack_slist_sort (JSList * list, JCompareFunc compare_func) static
Definition at line 266 of file jslist.h.
References jack_slist_sort(), jack_slist_sort_merge(), and _JSList::next.
Referenced by jack_slist_sort().
jack_slist_sort_merge()
__inline__ JSList * jack_slist_sort_merge (JSList * l1, JSList * l2, JCompareFunc compare_func) static
Definition at line 242 of file jslist.h.
References _JSList::data, and _JSList::next.
Referenced by jack_slist_sort().