LMMS: lmms::gui::BarModelEditor Class Reference
lmms::gui::BarModelEditor Class Reference
#include <BarModelEditor.h>
Public Member Functions
BarModelEditor (QString text, FloatModel *floatModel, QWidget *parent=nullptr)
QBrush const & getBackgroundBrush () const
QBrush const & getBarBrush () const
QColor const & getTextColor () const
QSize minimumSizeHint () const override
void setBackgroundBrush (QBrush const &backgroundBrush)
void setBarBrush (QBrush const &barBrush)
void setTextColor (QColor const &textColor)
QSize sizeHint () const override
QSizePolicy sizePolicy () const
Public Member Functions inherited from lmms::gui::FloatModelEditorBase
FloatModelEditorBase (const FloatModelEditorBase &other)=delete
FloatModelEditorBase (DirectionOfManipulation directionOfManipulation=DirectionOfManipulation::Vertical, QWidget *_parent=nullptr, const QString &_name=QString())
default ctor
void setHintText (const QString &txt_before, const QString &txt_after)
Public Member Functions inherited from lmms::gui::TypedModelView< FloatModel >
TypedModelView (Model *model, QWidget *_this)
FloatModel * model ()
const FloatModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void paintEvent (QPaintEvent *event) override
Protected Member Functions inherited from lmms::gui::FloatModelEditorBase
void contextMenuEvent (QContextMenuEvent *me) override
virtual QString displayValue () const
void doConnections () override
void dragEnterEvent (QDragEnterEvent *dee) override
void dropEvent (QDropEvent *de) override
void enterEvent (QEvent *event) override
void focusOutEvent (QFocusEvent *fe) override
virtual float getValue (const QPoint &p)
void leaveEvent (QEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
float pageSize () const
void paintEvent (QPaintEvent *me) override
void setPosition (const QPoint &p)
void showTextFloat (int msecBeforeDisplay, int msecDisplayTime)
void wheelEvent (QWheelEvent *me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void modelChanged ()
QWidget * widget ()
Properties
QBrush backgroundBrush
QBrush barBrush
QColor textColor
Private Attributes
QBrush m_backgroundBrush
QBrush m_barBrush
QString const m_text
QColor m_textColor
Additional Inherited Members
Public Types inherited from lmms::gui::FloatModelEditorBase
enum class DirectionOfManipulation {
Vertical ,
Horizontal
}
Signals inherited from lmms::gui::FloatModelEditorBase
void sliderMoved (float value)
void sliderPressed ()
void sliderReleased ()
Protected Attributes inherited from lmms::gui::FloatModelEditorBase
bool m_buttonPressed
DirectionOfManipulation m_directionOfManipulation
QPoint m_lastMousePos
mouse position in last mouseMoveEvent
float m_leftOver
BoolModel m_volumeKnob
FloatModel m_volumeRatio
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Static Protected Attributes inherited from lmms::gui::FloatModelEditorBase
static SimpleTextFloat * s_textFloat = nullptr
Detailed Description
Definition at line 36 of file BarModelEditor.h.
Constructor & Destructor Documentation
BarModelEditor()
lmms::gui::BarModelEditor::BarModelEditor (QString text, FloatModel * floatModel, QWidget * parent = nullptr)
Definition at line 9 of file BarModelEditor.cpp.
References lmms::gui::FloatModelEditorBase::FloatModelEditorBase(), m_backgroundBrush, m_barBrush, m_text, m_textColor, and lmms::gui::AutomatableModelView::setModel().
Referenced by lmms::gui::TempoSyncBarModelEditor::TempoSyncBarModelEditor().
Member Function Documentation
getBackgroundBrush()
QBrush const & lmms::gui::BarModelEditor::getBackgroundBrush () const
Definition at line 35 of file BarModelEditor.cpp.
References m_backgroundBrush.
Referenced by paintEvent().
getBarBrush()
QBrush const & lmms::gui::BarModelEditor::getBarBrush () const
Definition at line 45 of file BarModelEditor.cpp.
References m_barBrush.
Referenced by paintEvent().
getTextColor()
QColor const & lmms::gui::BarModelEditor::getTextColor () const
Definition at line 55 of file BarModelEditor.cpp.
References m_textColor.
Referenced by paintEvent().
minimumSizeHint()
QSize lmms::gui::BarModelEditor::minimumSizeHint () const override
Definition at line 24 of file BarModelEditor.cpp.
Referenced by sizeHint().
paintEvent()
void lmms::gui::BarModelEditor::paintEvent (QPaintEvent * event) override protected
Definition at line 65 of file BarModelEditor.cpp.
References backgroundBrush, barBrush, getBackgroundBrush(), getBarBrush(), getTextColor(), lmms::AutomatableModel::inverseScaledValue(), m_text, lmms::gui::TypedModelView< FloatModel >::model(), and lmms::gui::AutomatableModelView::value().
setBackgroundBrush()
void lmms::gui::BarModelEditor::setBackgroundBrush (QBrush const & backgroundBrush)
Definition at line 40 of file BarModelEditor.cpp.
References backgroundBrush, and m_backgroundBrush.
setBarBrush()
void lmms::gui::BarModelEditor::setBarBrush (QBrush const & barBrush)
Definition at line 50 of file BarModelEditor.cpp.
References barBrush, and m_barBrush.
setTextColor()
void lmms::gui::BarModelEditor::setTextColor (QColor const & textColor)
Definition at line 60 of file BarModelEditor.cpp.
References m_textColor, and textColor.
sizeHint()
QSize lmms::gui::BarModelEditor::sizeHint () const override
Definition at line 30 of file BarModelEditor.cpp.
References minimumSizeHint().
sizePolicy()
QSizePolicy lmms::gui::BarModelEditor::sizePolicy () const
Definition at line 19 of file BarModelEditor.cpp.
Member Data Documentation
m_backgroundBrush
QBrush lmms::gui::BarModelEditor::m_backgroundBrush private
Definition at line 69 of file BarModelEditor.h.
Referenced by BarModelEditor(), getBackgroundBrush(), and setBackgroundBrush().
m_barBrush
QBrush lmms::gui::BarModelEditor::m_barBrush private
Definition at line 70 of file BarModelEditor.h.
Referenced by BarModelEditor(), getBarBrush(), and setBarBrush().
m_text
QString const lmms::gui::BarModelEditor::m_text private
Definition at line 67 of file BarModelEditor.h.
Referenced by BarModelEditor(), and paintEvent().
m_textColor
QColor lmms::gui::BarModelEditor::m_textColor private
Definition at line 71 of file BarModelEditor.h.
Referenced by BarModelEditor(), getTextColor(), and setTextColor().
Property Documentation
backgroundBrush
QBrush lmms::gui::BarModelEditor::backgroundBrush read write
Definition at line 41 of file BarModelEditor.h.
Referenced by paintEvent(), and setBackgroundBrush().
barBrush
QBrush lmms::gui::BarModelEditor::barBrush read write
Definition at line 42 of file BarModelEditor.h.
Referenced by paintEvent(), and setBarBrush().
textColor
QColor lmms::gui::BarModelEditor::textColor read write
Definition at line 43 of file BarModelEditor.h.
Referenced by setTextColor().
The documentation for this class was generated from the following files:
include/BarModelEditor.h
src/gui/widgets/BarModelEditor.cpp