LMMS: Creating & manipulating clients
Creating & manipulating clients
Functions
int jack_activate (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
Tell the Jack server that the program is ready to start processing audio.
int jack_client_close (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
Disconnects an external client from a JACK server.
int jack_client_name_size (void) JACK_OPTIONAL_WEAK_EXPORT
jack_client_t * jack_client_new (const char *client_name) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS
jack_client_t * jack_client_open (const char *client_name, jack_options_t options, jack_status_t *status,...) JACK_OPTIONAL_WEAK_EXPORT
Open an external client session with a JACK server.
jack_native_thread_t jack_client_thread_id (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
int jack_deactivate (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
Tell the Jack server to remove this client from the process graph.
char * jack_get_client_name (jack_client_t *client) JACK_OPTIONAL_WEAK_EXPORT
char * jack_get_client_name_by_uuid (jack_client_t *client, const char *client_uuid) JACK_WEAK_EXPORT
Get the client name for a session_id.
int jack_get_client_pid (const char *name) JACK_OPTIONAL_WEAK_EXPORT
char * jack_get_uuid_for_client_name (jack_client_t *client, const char *client_name) JACK_WEAK_EXPORT
Get the session ID for a client name.
void jack_internal_client_close (const char *client_name) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Remove an internal client from a JACK server.
int jack_internal_client_new (const char *client_name, const char *load_name, const char *load_init) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Load an internal client into the Jack server.
Detailed Description
Function Documentation
jack_activate()
LIB_EXPORT int jack_activate (jack_client_t * client)
#include <jack.h>
Tell the Jack server that the program is ready to start processing audio.
Returns
0 on success, otherwise a non-zero error code
Definition at line 1071 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, and LIB_EXPORT.
Referenced by ExternalMetro::ExternalMetro(), Jack::JackNetMasterManager::JackNetMasterManager(), Jack::JackProfiler::JackProfiler(), Jack::JackNetMaster::Init(), Jack::JackProxyDriver::Initialize(), Jack::JackProxyDriver::LoadSymbols(), main(), main(), Jack::JackAudioAdapter::Open(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), and Jack::JackSapaProxy::Setup().
jack_client_close()
SERVER_EXPORT int jack_client_close (jack_client_t * client)
#include <jack.h>
Disconnects an external client from a JACK server.
Returns
0 on success, otherwise a non-zero error code
Definition at line 189 of file JackLibAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackLibGlobals::Destroy(), Jack::JackServerGlobals::Destroy(), Jack::JackGlobals::fOpenMutex, jack_error, jack_log(), LIB_EXPORT, and SERVER_EXPORT.
Referenced by ExternalMetro::~ExternalMetro(), Jack::JackNetMaster::~JackNetMaster(), Jack::JackNetMaster::Init(), Jack::JackProxyDriver::Initialize(), Jack::JackProxyDriver::LoadSymbols(), main(), and Jack::JackProxyDriver::PROXY_DEF_SYMBOL().
jack_client_name_size()
LIB_EXPORT int jack_client_name_size (void)
#include <jack.h>
Returns
the maximum number of characters in a JACK client name including the final NULL character. This value is a constant.
Definition at line 1486 of file JackAPI.cpp.
References JACK_CLIENT_NAME_SIZE, and LIB_EXPORT.
Referenced by main().
jack_client_new()
LIB_EXPORT jack_client_t * jack_client_new (const char * client_name)
#include <jack.h>
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS
Deprecated
Please use jack_client_open().
Definition at line 334 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), Jack::JackGlobals::fOpenMutex, jack_client_new_aux(), jack_error, JackNoStartServer, JackUseExactName, and LIB_EXPORT.
Referenced by main().
jack_client_open()
SERVER_EXPORT jack_client_t * jack_client_open (const char * client_name, jack_options_t options, jack_status_t * status, ...)
#include <jack.h>
Open an external client session with a JACK server.
This interface is more complex but more powerful than jack_client_new(). With it, clients may choose which of several servers to connect, and control whether and how to start the server automatically, if it was not already running. There is also an option for JACK to generate a unique client name, when necessary.
Parameters
client_name of at most jack_client_name_size() characters. The name scope is local to each server. Unless forbidden by the JackUseExactName option, the server will modify this name to create a unique variant, if needed.
options formed by OR-ing together JackOptions bits. Only the JackOpenOptions bits are allowed.
status (if non-NULL) an address for JACK to return information from the open operation. This status word is formed by OR-ing together the relevant JackStatus bits.
Optional parameters: depending on corresponding [options bits] additional parameters may follow status (in this order).
[JackServerName] (char *) server_name selects from among several possible concurrent server instances. Server names are unique to each user. If unspecified, use "default" unless $JACK_DEFAULT_SERVER is defined in the process environment.
Returns
Opaque client handle if successful. If this is NULL, the open operation failed, *status includes JackFailure and the caller is not a JACK client.
Definition at line 167 of file JackLibAPI.cpp.
References Jack::JackGlobals::CheckContext(), Jack::JackGlobals::fOpenMutex, jack_client_open_aux(), jack_error, and LIB_EXPORT.
Referenced by ExternalMetro::ExternalMetro(), Jack::JackNetMaster::Init(), Jack::JackProxyDriver::Initialize(), Jack::JackProxyDriver::LoadSymbols(), main(), main(), and Jack::JackProxyDriver::PROXY_DEF_SYMBOL().
jack_client_thread_id()
LIB_EXPORT jack_native_thread_t jack_client_thread_id (jack_client_t * client)
#include <jack.h>
Returns
the pthread ID of the thread running the JACK client side real-time code.
Definition at line 1460 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, and LIB_EXPORT.
jack_deactivate()
LIB_EXPORT int jack_deactivate (jack_client_t * client)
#include <jack.h>
Tell the Jack server to remove this client from the process graph.
Also, disconnect all ports belonging to it, since inactive clients have no port connections.
Returns
0 on success, otherwise a non-zero error code
Definition at line 1084 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, and LIB_EXPORT.
Referenced by ExternalMetro::~ExternalMetro(), Jack::JackNetMaster::~JackNetMaster(), Jack::JackProxyDriver::LoadSymbols(), main(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), and Jack::JackProxyDriver::Stop().
jack_get_client_name()
LIB_EXPORT char * jack_get_client_name (jack_client_t * client)
#include <jack.h>
Returns
pointer to actual client name. This is useful when JackUseExactName is not specified on open and JackNameNotUnique status was returned. In that case, the actual name will differ from the client_name requested.
Definition at line 1473 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, and LIB_EXPORT.
Referenced by Jack::JackNetMasterManager::JackNetMasterManager(), Jack::JackProfiler::ClientRegistration(), and main().
jack_get_client_name_by_uuid()
LIB_EXPORT char * jack_get_client_name_by_uuid (jack_client_t * client, const char * client_uuid)
#include <jack.h>
Get the client name for a session_id.
In order to snapshot the graph connections, the session manager needs to map session_ids to client names.
The caller is responsible for calling jack_free(3) on any non-NULL returned value.
Definition at line 2016 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, jack_log(), and LIB_EXPORT.
jack_get_client_pid()
SERVER_EXPORT int jack_get_client_pid (const char * name)
#include <jack.h>
Returns
pid of client. If not available, 0 will be returned.
Definition at line 210 of file JackLibAPI.cpp.
References Jack::JackServerGlobals::fInstance, jack_error, LIB_EXPORT, and SERVER_EXPORT.
jack_get_uuid_for_client_name()
LIB_EXPORT char * jack_get_uuid_for_client_name (jack_client_t * client, const char * client_name)
#include <jack.h>
Get the session ID for a client name.
The session manager needs this to reassociate a client name to the session_id.
The caller is responsible for calling jack_free(3) on any non-NULL returned value.
Definition at line 2002 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, jack_log(), and LIB_EXPORT.
jack_internal_client_close()
LIB_EXPORT void jack_internal_client_close (const char * client_name)
#include <jack.h>
Remove an internal client from a JACK server.
Deprecated
Please use jack_internal_client_unload().
Definition at line 1803 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), jack_error, and LIB_EXPORT.
jack_internal_client_new()
LIB_EXPORT int jack_internal_client_new (const char * client_name, const char * load_name, const char * load_init)
#include <jack.h>
Load an internal client into the Jack server.
Internal clients run inside the JACK server process. They can use most of the same functions as external clients. Each internal client must declare jack_initialize() and jack_finish() entry points, called at load and unload times. See inprocess.c for an example of how to write an internal client.
Deprecated
Please use jack_internal_client_load().
Parameters
client_name of at most jack_client_name_size() characters.
load_name of a shared object file containing the code for the new client.
load_init an arbitrary string passed to the jack_initialize() routine of the new client (may be NULL).
Returns
0 if successful.
Definition at line 1794 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), jack_error, and LIB_EXPORT.