LMMS: PortAudioDevices Class Reference
PortAudioDevices Class Reference
A PortAudio Devices manager.
#include <JackPortAudioDevices.h>
Public Member Functions
PortAudioDevices ()
~PortAudioDevices ()
void DisplayDevicesNames ()
PaDeviceInfo * GetDeviceFromFullName (std::string fullname, PaDeviceIndex &id, bool isInput)
PaDeviceInfo * GetDeviceInfo (PaDeviceIndex id)
std::string GetDeviceName (PaDeviceIndex id)
std::string GetFullName (PaDeviceIndex id)
std::string GetFullName (std::string hostname, std::string devicename)
std::string GetHostFromDevice (PaDeviceIndex id)
std::string GetHostFromDevice (PaDeviceInfo *device)
int GetInputDeviceFromName (const char *name, PaDeviceIndex &device, int &in_max)
PaDeviceIndex GetNumDevice ()
int GetOutputDeviceFromName (const char *name, PaDeviceIndex &device, int &out_max)
int GetPreferredBufferSize (PaDeviceIndex id)
bool IsDuplex (PaDeviceIndex id)
void PrintSupportedStandardSampleRates (const PaStreamParameters *inputParameters, const PaStreamParameters *outputParameters)
Private Attributes
PaDeviceInfo ** fDeviceInfo
std::string * fHostName
PaDeviceIndex fNumDevice
PaHostApiIndex fNumHostApi
Detailed Description
A PortAudio Devices manager.
Definition at line 36 of file JackPortAudioDevices.h.
Constructor & Destructor Documentation
PortAudioDevices()
PortAudioDevices::PortAudioDevices ()
Definition at line 26 of file JackPortAudioDevices.cpp.
References fDeviceInfo, fHostName, fNumDevice, fNumHostApi, jack_error, and jack_log().
~PortAudioDevices()
PortAudioDevices::~PortAudioDevices ()
Definition at line 47 of file JackPortAudioDevices.cpp.
References fDeviceInfo, fHostName, and jack_log().
Member Function Documentation
DisplayDevicesNames()
void PortAudioDevices::DisplayDevicesNames ()
Definition at line 236 of file JackPortAudioDevices.cpp.
References fDeviceInfo, fNumDevice, GetFullName(), and jack_info().
Referenced by driver_initialize().
GetDeviceFromFullName()
PaDeviceInfo * PortAudioDevices::GetDeviceFromFullName (std::string fullname, PaDeviceIndex & id, bool isInput)
Definition at line 101 of file JackPortAudioDevices.cpp.
References fDeviceInfo, fNumDevice, GetDeviceName(), and GetHostFromDevice().
Referenced by GetInputDeviceFromName(), and GetOutputDeviceFromName().
GetDeviceInfo()
PaDeviceInfo * PortAudioDevices::GetDeviceInfo (PaDeviceIndex id)
Definition at line 61 of file JackPortAudioDevices.cpp.
References fDeviceInfo.
Referenced by GetInputDeviceFromName(), and GetOutputDeviceFromName().
GetDeviceName()
string PortAudioDevices::GetDeviceName (PaDeviceIndex id)
Definition at line 66 of file JackPortAudioDevices.cpp.
References fDeviceInfo.
Referenced by GetDeviceFromFullName(), GetFullName(), and IsDuplex().
GetFullName() [1/2]
string PortAudioDevices::GetFullName (PaDeviceIndex id)
Definition at line 81 of file JackPortAudioDevices.cpp.
References GetDeviceName(), and GetHostFromDevice().
Referenced by DisplayDevicesNames().
GetFullName() [2/2]
string PortAudioDevices::GetFullName (std::string hostname, std::string devicename)
Definition at line 92 of file JackPortAudioDevices.cpp.
GetHostFromDevice() [1/2]
string PortAudioDevices::GetHostFromDevice (PaDeviceIndex id)
Definition at line 76 of file JackPortAudioDevices.cpp.
References fDeviceInfo, and fHostName.
GetHostFromDevice() [2/2]
string PortAudioDevices::GetHostFromDevice (PaDeviceInfo * device)
Definition at line 71 of file JackPortAudioDevices.cpp.
References fHostName.
Referenced by GetDeviceFromFullName(), and GetFullName().
GetInputDeviceFromName()
int PortAudioDevices::GetInputDeviceFromName (const char * name, PaDeviceIndex & device, int & in_max)
Definition at line 171 of file JackPortAudioDevices.cpp.
References GetDeviceFromFullName(), GetDeviceInfo(), and jack_error.
GetNumDevice()
PaDeviceIndex PortAudioDevices::GetNumDevice ()
Definition at line 56 of file JackPortAudioDevices.cpp.
References fNumDevice.
GetOutputDeviceFromName()
int PortAudioDevices::GetOutputDeviceFromName (const char * name, PaDeviceIndex & device, int & out_max)
Definition at line 190 of file JackPortAudioDevices.cpp.
References GetDeviceFromFullName(), GetDeviceInfo(), and jack_error.
GetPreferredBufferSize()
int PortAudioDevices::GetPreferredBufferSize (PaDeviceIndex id)
Definition at line 209 of file JackPortAudioDevices.cpp.
References fDeviceInfo, and jack_info().
IsDuplex()
bool PortAudioDevices::IsDuplex (PaDeviceIndex id)
Definition at line 300 of file JackPortAudioDevices.cpp.
References fDeviceInfo, fNumDevice, GetDeviceName(), and i.
PrintSupportedStandardSampleRates()
void PortAudioDevices::PrintSupportedStandardSampleRates (const PaStreamParameters * inputParameters, const PaStreamParameters * outputParameters)
Definition at line 138 of file JackPortAudioDevices.cpp.
References i, and jack_info().
Member Data Documentation
fDeviceInfo
PaDeviceInfo** PortAudioDevices::fDeviceInfo private
Definition at line 42 of file JackPortAudioDevices.h.
Referenced by PortAudioDevices(), ~PortAudioDevices(), DisplayDevicesNames(), GetDeviceFromFullName(), GetDeviceInfo(), GetDeviceName(), GetHostFromDevice(), GetPreferredBufferSize(), and IsDuplex().
fHostName
std::string* PortAudioDevices::fHostName private
Definition at line 43 of file JackPortAudioDevices.h.
Referenced by PortAudioDevices(), ~PortAudioDevices(), GetHostFromDevice(), and GetHostFromDevice().
fNumDevice
PaDeviceIndex PortAudioDevices::fNumDevice private
Definition at line 41 of file JackPortAudioDevices.h.
Referenced by PortAudioDevices(), DisplayDevicesNames(), GetDeviceFromFullName(), GetNumDevice(), and IsDuplex().
fNumHostApi
PaHostApiIndex PortAudioDevices::fNumHostApi private
Definition at line 40 of file JackPortAudioDevices.h.
Referenced by PortAudioDevices().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/portaudio/JackPortAudioDevices.h
src/3rdparty/jack2/windows/portaudio/JackPortAudioDevices.cpp