LMMS: lmms::gui::LedCheckBox Class Reference
lmms::gui::LedCheckBox Class Reference
#include <LedCheckBox.h>
Public Types
enum class LedColor {
Yellow ,
Green ,
Red
}
Public Member Functions
LedCheckBox (const QString &_txt, QWidget *_parent, const QString &_name=QString(), LedColor _color=LedColor::Yellow, bool legacyMode=true)
LedCheckBox (QWidget *_parent, const QString &_name=QString(), LedColor _color=LedColor::Yellow, bool legacyMode=true)
void setText (const QString &s)
const QString & text ()
Public Member Functions inherited from lmms::gui::AutomatableButton
AutomatableButton (QWidget *_parent, const QString &_name=QString())
~AutomatableButton () override
void modelChanged () override
void setCheckable (bool _on)
Public Member Functions inherited from lmms::gui::TypedModelView< BoolModel >
TypedModelView (Model *model, QWidget *_this)
BoolModel * model ()
const BoolModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void paintEvent (QPaintEvent *_pe) override
Protected Member Functions inherited from lmms::gui::AutomatableButton
void contextMenuEvent (QContextMenuEvent *_me) override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Properties
QString text
Private Member Functions
void initUi (LedColor _color)
to be called by ctors
void onTextUpdated ()
to be called when you updated m_text
void paintLegacy (QPaintEvent *p)
void paintNonLegacy (QPaintEvent *p)
Private Attributes
QPixmap m_ledOffPixmap
QPixmap m_ledOnPixmap
bool m_legacyMode
QString m_text
Additional Inherited Members
Public Slots inherited from lmms::gui::AutomatableButton
virtual void setChecked (bool _on)
virtual void toggle ()
virtual void update ()
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 36 of file LedCheckBox.h.
Member Enumeration Documentation
LedColor
enum class lmms::gui::LedCheckBox::LedColor strong
Enumerator
Yellow
Green
Red
Definition at line 40 of file LedCheckBox.h.
Constructor & Destructor Documentation
LedCheckBox() [1/2]
lmms::gui::LedCheckBox::LedCheckBox (const QString & _txt, QWidget * _parent, const QString & _name = QString(), LedColor _color = LedColor::Yellow, bool legacyMode = true)
Definition at line 47 of file LedCheckBox.cpp.
References lmms::gui::AutomatableButton::AutomatableButton(), initUi(), m_legacyMode, and m_text.
Referenced by LedCheckBox().
LedCheckBox() [2/2]
lmms::gui::LedCheckBox::LedCheckBox (QWidget * _parent, const QString & _name = QString(), LedColor _color = LedColor::Yellow, bool legacyMode = true)
Definition at line 59 of file LedCheckBox.cpp.
References LedCheckBox().
Member Function Documentation
initUi()
void lmms::gui::LedCheckBox::initUi (LedColor _color) private
to be called by ctors
Definition at line 89 of file LedCheckBox.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, lmms::embed::getIconPixmap(), m_ledOffPixmap, m_ledOnPixmap, m_legacyMode, m_text, lmms::gui::names, lmms::gui::AutomatableButton::setCheckable(), and setText().
Referenced by LedCheckBox().
onTextUpdated()
void lmms::gui::LedCheckBox::onTextUpdated () private
to be called when you updated m_text
Definition at line 104 of file LedCheckBox.cpp.
References lmms::horizontalAdvance(), m_ledOffPixmap, m_legacyMode, and text.
Referenced by setText().
paintEvent()
void lmms::gui::LedCheckBox::paintEvent (QPaintEvent * _pe) override protected
Definition at line 74 of file LedCheckBox.cpp.
References m_legacyMode, paintLegacy(), and paintNonLegacy().
paintLegacy()
void lmms::gui::LedCheckBox::paintLegacy (QPaintEvent * p) private
Definition at line 114 of file LedCheckBox.cpp.
References lmms::gui::adjustedToPixelSize(), DEFAULT_FONT_SIZE, m_ledOffPixmap, m_ledOnPixmap, lmms::gui::TypedModelView< BoolModel >::model(), text, and lmms::gui::AutomatableModelView::value().
Referenced by paintEvent().
paintNonLegacy()
void lmms::gui::LedCheckBox::paintNonLegacy (QPaintEvent * p) private
Definition at line 127 of file LedCheckBox.cpp.
References m_ledOffPixmap, m_ledOnPixmap, lmms::gui::TypedModelView< BoolModel >::model(), text, and lmms::TypedAutomatableModel< T >::value().
Referenced by paintEvent().
setText()
void lmms::gui::LedCheckBox::setText (const QString & s)
Definition at line 65 of file LedCheckBox.cpp.
References m_text, and onTextUpdated().
Referenced by initUi().
text()
const QString & lmms::gui::LedCheckBox::text () inline
Definition at line 56 of file LedCheckBox.h.
References m_text.
Member Data Documentation
m_ledOffPixmap
QPixmap lmms::gui::LedCheckBox::m_ledOffPixmap private
Definition at line 71 of file LedCheckBox.h.
Referenced by initUi(), onTextUpdated(), paintLegacy(), and paintNonLegacy().
m_ledOnPixmap
QPixmap lmms::gui::LedCheckBox::m_ledOnPixmap private
Definition at line 70 of file LedCheckBox.h.
Referenced by initUi(), paintLegacy(), and paintNonLegacy().
m_legacyMode
bool lmms::gui::LedCheckBox::m_legacyMode private
Definition at line 75 of file LedCheckBox.h.
Referenced by LedCheckBox(), initUi(), onTextUpdated(), and paintEvent().
m_text
QString lmms::gui::LedCheckBox::m_text private
Definition at line 73 of file LedCheckBox.h.
Referenced by LedCheckBox(), initUi(), setText(), and text().
Property Documentation
text
QString lmms::gui::LedCheckBox::text read write
Definition at line 63 of file LedCheckBox.h.
Referenced by onTextUpdated(), paintLegacy(), and paintNonLegacy().
The documentation for this class was generated from the following files:
include/LedCheckBox.h
src/gui/widgets/LedCheckBox.cpp