LMMS: src/3rdparty/jack2/common/netjack_packet.h File Reference
netjack_packet.h File Reference
#include <jack/jack.h>
#include <jack/types.h>
#include <jack/jslist.h>
#include <jack/midiport.h>
Classes
struct _cache_packet
union _int_float
struct _jacknet_packet_header
struct _packet_cache
Macros
#define CELT_MODE 1000
#define MASTER_FREEWHEELS 0x80000000
#define OPUS_MODE 999
Typedefs
typedef struct _cache_packet cache_packet
typedef union _int_float int_float_t
typedef struct _jacknet_packet_header jacknet_packet_header
typedef struct _packet_cache packet_cache
Functions
void cache_packet_add_fragment (cache_packet *pack, char *packet_buf, int rcv_len)
int cache_packet_is_complete (cache_packet *pack)
void cache_packet_reset (cache_packet *pack)
void cache_packet_set_framecnt (cache_packet *pack, jack_nframes_t framecnt)
void decode_midi_buffer (uint32_t *buffer_uint32, unsigned int buffer_size_uint32, jack_default_audio_sample_t *buf)
void encode_midi_buffer (uint32_t *buffer_uint32, unsigned int buffer_size_uint32, jack_default_audio_sample_t *buf)
int get_sample_size (int bitdepth)
int netjack_poll (int sockfd, int timeout)
int netjack_poll_deadline (int sockfd, jack_time_t deadline)
void netjack_sendto (int sockfd, char *packet_buf, int pkt_size, int flags, struct sockaddr *addr, int addr_size, int mtu)
void packet_cache_drain_socket (packet_cache *pcache, int sockfd)
int packet_cache_find_latency (packet_cache *pcache, jack_nframes_t expected_framecnt, jack_nframes_t *framecnt)
void packet_cache_free (packet_cache *pkt_cache)
float packet_cache_get_fill (packet_cache *pcache, jack_nframes_t expected_framecnt)
cache_packet * packet_cache_get_free_packet (packet_cache *pkt_cache)
int packet_cache_get_highest_available_framecnt (packet_cache *pcache, jack_nframes_t *framecnt)
int packet_cache_get_next_available_framecnt (packet_cache *pcache, jack_nframes_t expected_framecnt, jack_nframes_t *framecnt)
cache_packet * packet_cache_get_oldest_packet (packet_cache *pkt_cache)
cache_packet * packet_cache_get_packet (packet_cache *pkt_cache, jack_nframes_t framecnt)
packet_cache * packet_cache_new (int num_packets, int pkt_size, int mtu)
int packet_cache_release_packet (packet_cache *pcache, jack_nframes_t framecnt)
void packet_cache_reset_master_address (packet_cache *pcache)
int packet_cache_retreive_packet_pointer (packet_cache *pcache, jack_nframes_t framecnt, char **packet_buf, int pkt_size, jack_time_t *timestamp)
void packet_header_hton (jacknet_packet_header *pkthdr)
void packet_header_ntoh (jacknet_packet_header *pkthdr)
void render_jack_ports_to_payload (int bitdepth, JSList *playback_ports, JSList *playback_srcs, jack_nframes_t nframes, void *packet_payload, jack_nframes_t net_period_up, int dont_htonl_floats)
void render_payload_to_jack_ports (int bitdepth, void *packet_payload, jack_nframes_t net_period_down, JSList *capture_ports, JSList *capture_srcs, jack_nframes_t nframes, int dont_htonl_floats)
Macro Definition Documentation
CELT_MODE
#define CELT_MODE 1000
Definition at line 42 of file netjack_packet.h.
Referenced by Jack::JackNetOneDriver::AllocPorts(), Jack::JackNetOneDriver::FreePorts(), Jack::JackNetOneDriver::render_jack_ports_to_payload(), and Jack::JackNetOneDriver::render_payload_to_jack_ports().
MASTER_FREEWHEELS
#define MASTER_FREEWHEELS 0x80000000
Definition at line 44 of file netjack_packet.h.
OPUS_MODE
#define OPUS_MODE 999
Definition at line 43 of file netjack_packet.h.
Referenced by Jack::JackNetOneDriver::AllocPorts(), Jack::JackNetOneDriver::FreePorts(), Jack::JackNetOneDriver::render_jack_ports_to_payload(), and Jack::JackNetOneDriver::render_payload_to_jack_ports().
Typedef Documentation
cache_packet
typedef struct _cache_packet cache_packet
Definition at line 79 of file netjack_packet.h.
int_float_t
typedef union _int_float int_float_t
Definition at line 71 of file netjack_packet.h.
jacknet_packet_header
typedef struct _jacknet_packet_header jacknet_packet_header
Definition at line 46 of file netjack_packet.h.
packet_cache
typedef struct _packet_cache packet_cache
Definition at line 92 of file netjack_packet.h.
Function Documentation
cache_packet_add_fragment()
void cache_packet_add_fragment (cache_packet * pack, char * packet_buf, int rcv_len)
cache_packet_is_complete()
int cache_packet_is_complete (cache_packet * pack)
cache_packet_reset()
void cache_packet_reset (cache_packet * pack)
cache_packet_set_framecnt()
void cache_packet_set_framecnt (cache_packet * pack, jack_nframes_t framecnt)
decode_midi_buffer()
void decode_midi_buffer (uint32_t * buffer_uint32, unsigned int buffer_size_uint32, jack_default_audio_sample_t * buf)
Referenced by Jack::JackNetOneDriver::render_payload_to_jack_ports_float().
encode_midi_buffer()
void encode_midi_buffer (uint32_t * buffer_uint32, unsigned int buffer_size_uint32, jack_default_audio_sample_t * buf)
Referenced by Jack::JackNetOneDriver::render_jack_ports_to_payload_float().
get_sample_size()
int get_sample_size (int bitdepth)
Referenced by Jack::JackNetOneDriver::Write().
netjack_poll()
int netjack_poll (int sockfd, int timeout)
netjack_poll_deadline()
int netjack_poll_deadline (int sockfd, jack_time_t deadline)
netjack_sendto()
void netjack_sendto (int sockfd, char * packet_buf, int pkt_size, int flags, struct sockaddr * addr, int addr_size, int mtu)
Referenced by Jack::JackNetOneDriver::Write().
packet_cache_drain_socket()
void packet_cache_drain_socket (packet_cache * pcache, int sockfd)
packet_cache_find_latency()
int packet_cache_find_latency (packet_cache * pcache, jack_nframes_t expected_framecnt, jack_nframes_t * framecnt)
packet_cache_free()
void packet_cache_free (packet_cache * pkt_cache)
packet_cache_get_fill()
float packet_cache_get_fill (packet_cache * pcache, jack_nframes_t expected_framecnt)
packet_cache_get_free_packet()
cache_packet * packet_cache_get_free_packet (packet_cache * pkt_cache)
packet_cache_get_highest_available_framecnt()
int packet_cache_get_highest_available_framecnt (packet_cache * pcache, jack_nframes_t * framecnt)
packet_cache_get_next_available_framecnt()
int packet_cache_get_next_available_framecnt (packet_cache * pcache, jack_nframes_t expected_framecnt, jack_nframes_t * framecnt)
packet_cache_get_oldest_packet()
cache_packet * packet_cache_get_oldest_packet (packet_cache * pkt_cache)
packet_cache_get_packet()
cache_packet * packet_cache_get_packet (packet_cache * pkt_cache, jack_nframes_t framecnt)
packet_cache_new()
packet_cache * packet_cache_new (int num_packets, int pkt_size, int mtu)
packet_cache_release_packet()
int packet_cache_release_packet (packet_cache * pcache, jack_nframes_t framecnt)
Referenced by Jack::JackNetOneDriver::Read().
packet_cache_reset_master_address()
void packet_cache_reset_master_address (packet_cache * pcache)
packet_cache_retreive_packet_pointer()
int packet_cache_retreive_packet_pointer (packet_cache * pcache, jack_nframes_t framecnt, char ** packet_buf, int pkt_size, jack_time_t * timestamp)
packet_header_hton()
void packet_header_hton (jacknet_packet_header * pkthdr)
Referenced by Jack::JackNetOneDriver::Write().
packet_header_ntoh()
void packet_header_ntoh (jacknet_packet_header * pkthdr)
render_jack_ports_to_payload()
void render_jack_ports_to_payload (int bitdepth, JSList * playback_ports, JSList * playback_srcs, jack_nframes_t nframes, void * packet_payload, jack_nframes_t net_period_up, int dont_htonl_floats)
render_payload_to_jack_ports()
void render_payload_to_jack_ports (int bitdepth, void * packet_payload, jack_nframes_t net_period_down, JSList * capture_ports, JSList * capture_srcs, jack_nframes_t nframes, int dont_htonl_floats)