LMMS: lmms::gui::FileBrowserWidgetItem Class Reference
lmms::gui::FileBrowserWidgetItem Class Reference abstract
#include <FileBrowser.h>
Public Member Functions
FileBrowserWidgetItem (const QStringList &strings, int type, QTreeWidget *parent=nullptr)
virtual QString fullName (QString path=QString{}) const =0
Detailed Description
Definition at line 186 of file FileBrowser.h.
Constructor & Destructor Documentation
FileBrowserWidgetItem()
lmms::gui::FileBrowserWidgetItem::FileBrowserWidgetItem (const QStringList & strings, int type, QTreeWidget * parent = nullptr)
Definition at line 1051 of file FileBrowser.cpp.
Referenced by lmms::gui::Directory::Directory(), lmms::gui::FileItem::FileItem(), and lmms::gui::FileItem::FileItem().
Member Function Documentation
fullName()
virtual QString lmms::gui::FileBrowserWidgetItem::fullName (QString path = QString{}) const pure virtual
Implemented in lmms::gui::Directory, and lmms::gui::FileItem.
The documentation for this class was generated from the following files:
include/FileBrowser.h
src/gui/FileBrowser.cpp