LMMS: lmms::gui::TrackContainerView Class Reference
lmms::gui::TrackContainerView Class Reference
#include <TrackContainerView.h>
Classes
class scrollArea
Public Slots
lmms::gui::TrackView * createTrackView (lmms::Track *_t)
void deleteTrackView (lmms::gui::TrackView *_tv)
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void realignTracks ()
void stopRubberBand ()
stopRubberBand Removes the rubber band from display when finished with.
Signals
void positionChanged (const lmms::TimePos &_pos)
void tracksRealigned ()
Public Member Functions
TrackContainerView (TrackContainer *tc)
~TrackContainerView () override
TrackView * addTrackView (TrackView *_tv)
virtual bool allowRubberband () const
void clearAllTracks ()
QScrollArea * contentWidget ()
const TimePos & currentPosition () const
virtual bool fixedClips () const
virtual bool knifeMode () const
void loadSettings (const QDomElement &_this) override
TrackContainer * model ()
const TrackContainer * model () const
void moveTrackView (TrackView *trackView, int indexTo)
void moveTrackViewDown (TrackView *trackView)
void moveTrackViewUp (TrackView *trackView)
QString nodeName () const override
float pixelsPerBar () const
void removeTrackView (TrackView *_tv)
RubberBand * rubberBand () const
bool rubberBandActive () const
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
void scrollToTrackView (TrackView *_tv)
QVector< selectableObject * > selectedObjects ()
void setPixelsPerBar (int ppb)
unsigned int totalHeightOfTracks () const
const TrackView * trackViewAt (const int _y) const
const QList< TrackView * > & trackViews () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Public Member Functions inherited from lmms::SerializingObjectHook
SerializingObjectHook ()
virtual ~SerializingObjectHook ()
Protected Attributes
TimePos m_currentPosition
Static Protected Attributes
static const int DEFAULT_PIXELS_PER_BAR = 128
Private Types
using trackViewList = QList<TrackView*>
Private Attributes
float m_ppb
RubberBand * m_rubberBand
scrollArea * m_scrollArea
QVBoxLayout * m_scrollLayout
TrackContainer * m_tc
trackViewList m_trackViews
Friends
class TrackContainerView::scrollArea
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 68 of file TrackContainerView.h.
Member Typedef Documentation
trackViewList
using lmms::gui::TrackContainerView::trackViewList = QList<TrackView*> private
Definition at line 191 of file TrackContainerView.h.
Constructor & Destructor Documentation
TrackContainerView()
lmms::gui::TrackContainerView::TrackContainerView (TrackContainer * tc)
Definition at line 77 of file TrackContainerView.cpp.
References lmms::JournallingObject::JournallingObject(), lmms::gui::ModelView::ModelView(), lmms::SerializingObjectHook::SerializingObjectHook(), createTrackView(), DEFAULT_PIXELS_PER_BAR, lmms::Engine::getSong(), m_currentPosition, m_ppb, m_rubberBand, m_scrollArea, m_scrollLayout, m_tc, m_trackViews, and realignTracks().
Referenced by lmms::gui::PatternEditor::PatternEditor(), lmms::gui::TrackContainerView::scrollArea::scrollArea(), and lmms::gui::SongEditor::SongEditor().
~TrackContainerView()
lmms::gui::TrackContainerView::~TrackContainerView () override
Definition at line 126 of file TrackContainerView.cpp.
References m_trackViews.
Member Function Documentation
addTrackView()
TrackView * lmms::gui::TrackContainerView::addTrackView (TrackView * _tv)
Definition at line 155 of file TrackContainerView.cpp.
References lmms::gui::TrackView::getTrackContentWidget(), m_scrollLayout, m_trackViews, positionChanged(), and realignTracks().
allowRubberband()
bool lmms::gui::TrackContainerView::allowRubberband () const virtual
Reimplemented in lmms::gui::SongEditor.
Definition at line 326 of file TrackContainerView.cpp.
clearAllTracks()
void lmms::gui::TrackContainerView::clearAllTracks ()
Definition at line 356 of file TrackContainerView.cpp.
References lmms::gui::TrackView::getTrack(), and m_trackViews.
Referenced by lmms::Song::clearProject().
contentWidget()
QScrollArea * lmms::gui::TrackContainerView::contentWidget () inline
Definition at line 80 of file TrackContainerView.h.
References m_scrollArea.
Referenced by lmms::gui::SongEditor::SongEditor(), lmms::gui::SongEditor::mousePressEvent(), lmms::gui::SongEditor::selectRegionFromPixels(), lmms::gui::SongEditor::updatePosition(), and lmms::gui::SongEditor::updateRubberband().
createTrackView
TrackView * lmms::gui::TrackContainerView::createTrackView (lmms::Track * _t) slot
Definition at line 274 of file TrackContainerView.cpp.
References lmms::Track::createView(), and m_trackViews.
Referenced by TrackContainerView(), and lmms::gui::TrackOperationsWidget::cloneTrack().
currentPosition()
const TimePos & lmms::gui::TrackContainerView::currentPosition () const inline
Definition at line 85 of file TrackContainerView.h.
References m_currentPosition.
Referenced by lmms::gui::TrackContentWidget::getPosition(), and lmms::gui::TrackContentWidget::paintEvent().
deleteTrackView
void lmms::gui::TrackContainerView::deleteTrackView (lmms::gui::TrackView * _tv) slot
Definition at line 290 of file TrackContainerView.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), lmms::gui::TrackView::getTrack(), removeTrackView(), and lmms::AudioEngine::requestChangeInModel().
dragEnterEvent
void lmms::gui::TrackContainerView::dragEnterEvent (QDragEnterEvent * _dee) override slot
Definition at line 370 of file TrackContainerView.cpp.
References lmms::Track::Instrument, lmms::gui::StringPairDrag::processDragEnterEvent(), and lmms::Track::Sample.
dropEvent
void lmms::gui::TrackContainerView::dropEvent (QDropEvent * _de) override slot
Definition at line 392 of file TrackContainerView.cpp.
References lmms::DataFile::content(), lmms::Track::create(), lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::gui::FileItem::extension(), lmms::gui::getGUI(), lmms::getPluginFactory(), lmms::Engine::getSong(), i, lmms::ImportFilter::import(), lmms::PluginFactory::PluginInfoAndKey::info, lmms::Track::Instrument, lmms::PluginFactory::PluginInfoAndKey::key, lmms::Track::loadPreset(), lmms::Song::loadProject(), m_tc, lmms::PluginFactory::PluginInfo::name(), and lmms::PluginFactory::pluginSupportingExtension().
Referenced by lmms::gui::PatternEditor::dropEvent().
fixedClips()
virtual bool lmms::gui::TrackContainerView::fixedClips () const inline virtual
Reimplemented in lmms::gui::PatternEditor.
Definition at line 90 of file TrackContainerView.h.
Referenced by lmms::gui::SampleTrackView::dropEvent().
knifeMode()
bool lmms::gui::TrackContainerView::knifeMode () const virtual
Reimplemented in lmms::gui::SongEditor.
Definition at line 334 of file TrackContainerView.cpp.
loadSettings()
void lmms::gui::TrackContainerView::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 147 of file TrackContainerView.cpp.
References lmms::gui::MainWindow::restoreWidgetState().
model() [1/2]
TrackContainer * lmms::gui::TrackContainerView::model () inline
Definition at line 118 of file TrackContainerView.h.
References m_tc.
Referenced by lmms::gui::PatternEditor::addAutomationTrack(), lmms::gui::PatternEditor::addSampleTrack(), lmms::gui::PatternEditor::cloneClip(), lmms::gui::PatternEditor::dropEvent(), lmms::gui::PatternEditor::makeSteps(), lmms::gui::PatternEditor::removeSteps(), and lmms::gui::PatternEditor::updateMaxSteps().
model() [2/2]
const TrackContainer * lmms::gui::TrackContainerView::model () const inline
Definition at line 123 of file TrackContainerView.h.
References m_tc.
moveTrackView()
void lmms::gui::TrackContainerView::moveTrackView (TrackView * trackView, int indexTo)
Definition at line 190 of file TrackContainerView.cpp.
References lmms::gui::TrackView::getTrack(), m_scrollLayout, m_tc, m_trackViews, realignTracks(), and lmms::PatternTrack::swapPatternTracks().
Referenced by lmms::gui::TrackOperationsWidget::cloneTrack(), moveTrackViewDown(), and moveTrackViewUp().
moveTrackViewDown()
void lmms::gui::TrackContainerView::moveTrackViewDown (TrackView * trackView)
Definition at line 227 of file TrackContainerView.cpp.
References m_trackViews, and moveTrackView().
moveTrackViewUp()
void lmms::gui::TrackContainerView::moveTrackViewUp (TrackView * trackView)
Definition at line 217 of file TrackContainerView.cpp.
References m_trackViews, and moveTrackView().
nodeName()
QString lmms::gui::TrackContainerView::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 145 of file TrackContainerView.h.
pixelsPerBar()
float lmms::gui::TrackContainerView::pixelsPerBar () const inline
Definition at line 95 of file TrackContainerView.h.
References m_ppb.
Referenced by lmms::gui::PatternEditor::PatternEditor(), lmms::gui::SongEditor::SongEditor(), lmms::gui::SongEditor::~SongEditor(), lmms::gui::SongEditor::adjustLeftRightScoll(), lmms::gui::SongEditor::calculateZoomSliderValue(), lmms::gui::TrackContentWidget::getPosition(), lmms::gui::SongEditor::getSnapSize(), lmms::gui::SongEditor::mousePressEvent(), lmms::gui::TrackContentWidget::paintEvent(), lmms::gui::SongEditor::selectRegionFromPixels(), lmms::gui::TrackContentWidget::updateBackground(), lmms::gui::PatternEditor::updatePixelsPerBar(), lmms::gui::SongEditor::updatePosition(), lmms::gui::SongEditor::updateRubberband(), and lmms::gui::SongEditor::wheelEvent().
positionChanged
void lmms::gui::TrackContainerView::positionChanged (const lmms::TimePos & _pos) signal
Referenced by lmms::gui::SongEditor::SongEditor(), addTrackView(), lmms::gui::SongEditor::scrolled(), and lmms::gui::PatternEditor::updatePosition().
realignTracks
void lmms::gui::TrackContainerView::realignTracks () slot
Definition at line 260 of file TrackContainerView.cpp.
References m_trackViews, and tracksRealigned().
Referenced by TrackContainerView(), addTrackView(), moveTrackView(), removeTrackView(), lmms::gui::SongEditor::wheelEvent(), and lmms::gui::SongEditor::zoomingChanged().
removeTrackView()
void lmms::gui::TrackContainerView::removeTrackView (TrackView * _tv)
Definition at line 169 of file TrackContainerView.cpp.
References lmms::Engine::getSong(), m_scrollLayout, m_trackViews, realignTracks(), and lmms::Song::setModified().
Referenced by deleteTrackView().
rubberBand()
RubberBand * lmms::gui::TrackContainerView::rubberBand () const
Definition at line 451 of file TrackContainerView.cpp.
References m_rubberBand.
Referenced by lmms::gui::SongEditor::mousePressEvent(), lmms::gui::SongEditor::mouseReleaseEvent(), lmms::gui::SongEditor::selectAllClips(), lmms::gui::SongEditor::selectRegionFromPixels(), and lmms::gui::SongEditor::updateRubberband().
rubberBandActive()
bool lmms::gui::TrackContainerView::rubberBandActive () const inline
Definition at line 107 of file TrackContainerView.h.
References m_rubberBand.
Referenced by lmms::gui::SongEditor::updateRubberband().
saveSettings()
void lmms::gui::TrackContainerView::saveSettings (QDomDocument & _doc, QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 138 of file TrackContainerView.cpp.
References lmms::gui::MainWindow::saveWidgetState().
scrollToTrackView()
void lmms::gui::TrackContainerView::scrollToTrackView (TrackView * _tv)
Definition at line 234 of file TrackContainerView.cpp.
References m_scrollArea, and m_trackViews.
Referenced by lmms::gui::InstrumentTrackWindow::viewInstrumentInDirection().
selectedObjects()
QVector< selectableObject * > lmms::gui::TrackContainerView::selectedObjects () inline
Definition at line 112 of file TrackContainerView.h.
References m_rubberBand.
Referenced by lmms::gui::SongEditor::keyPressEvent().
setPixelsPerBar()
void lmms::gui::TrackContainerView::setPixelsPerBar (int ppb)
Definition at line 342 of file TrackContainerView.cpp.
References m_ppb, and m_trackViews.
Referenced by lmms::gui::PatternEditor::updatePixelsPerBar(), and lmms::gui::SongEditor::zoomingChanged().
stopRubberBand
void lmms::gui::TrackContainerView::stopRubberBand () slot
stopRubberBand Removes the rubber band from display when finished with.
Definition at line 383 of file TrackContainerView.cpp.
References m_rubberBand.
Referenced by lmms::gui::SongEditor::SongEditor().
totalHeightOfTracks()
unsigned int lmms::gui::TrackContainerView::totalHeightOfTracks () const
Definition at line 486 of file TrackContainerView.cpp.
References m_trackViews.
Referenced by lmms::gui::SongEditor::updatePositionLine().
tracksRealigned
void lmms::gui::TrackContainerView::tracksRealigned () signal
Referenced by lmms::gui::SongEditor::SongEditor(), and realignTracks().
trackViewAt()
const TrackView * lmms::gui::TrackContainerView::trackViewAt (const int _y) const
Definition at line 306 of file TrackContainerView.cpp.
References m_scrollArea, and m_trackViews.
Referenced by lmms::gui::SongEditor::trackIndexFromSelectionPoint().
trackViews()
const QList< TrackView * > & lmms::gui::TrackContainerView::trackViews () const inline
Definition at line 128 of file TrackContainerView.h.
References m_trackViews.
Referenced by lmms::gui::TrackOperationsWidget::cloneTrack(), lmms::gui::SongEditor::indexOfTrackView(), lmms::gui::PatternEditor::removeViewsForPattern(), lmms::gui::SongEditor::trackIndexFromSelectionPoint(), lmms::gui::PatternEditor::updatePosition(), and lmms::gui::SongEditor::updateRubberband().
Friends And Related Symbol Documentation
TrackContainerView::scrollArea
friend class TrackContainerView::scrollArea friend
Definition at line 188 of file TrackContainerView.h.
Member Data Documentation
DEFAULT_PIXELS_PER_BAR
const int lmms::gui::TrackContainerView::DEFAULT_PIXELS_PER_BAR = 128 static protected
Definition at line 169 of file TrackContainerView.h.
Referenced by lmms::gui::SongEditor::SongEditor(), TrackContainerView(), lmms::gui::SongEditor::adjustLeftRightScoll(), and lmms::gui::SongEditor::getSnapSize().
m_currentPosition
TimePos lmms::gui::TrackContainerView::m_currentPosition protected
Definition at line 171 of file TrackContainerView.h.
Referenced by lmms::gui::PatternEditor::PatternEditor(), lmms::gui::SongEditor::SongEditor(), TrackContainerView(), currentPosition(), lmms::gui::SongEditor::mousePressEvent(), lmms::gui::SongEditor::scrolled(), lmms::gui::SongEditor::selectRegionFromPixels(), lmms::gui::PatternEditor::updatePosition(), lmms::gui::SongEditor::updatePosition(), and lmms::gui::SongEditor::updateRubberband().
m_ppb
float lmms::gui::TrackContainerView::m_ppb private
Definition at line 197 of file TrackContainerView.h.
Referenced by TrackContainerView(), pixelsPerBar(), and setPixelsPerBar().
m_rubberBand
RubberBand* lmms::gui::TrackContainerView::m_rubberBand private
Definition at line 199 of file TrackContainerView.h.
Referenced by TrackContainerView(), rubberBand(), rubberBandActive(), selectedObjects(), and stopRubberBand().
m_scrollArea
scrollArea* lmms::gui::TrackContainerView::m_scrollArea private
Definition at line 194 of file TrackContainerView.h.
Referenced by TrackContainerView(), contentWidget(), scrollToTrackView(), and trackViewAt().
m_scrollLayout
QVBoxLayout* lmms::gui::TrackContainerView::m_scrollLayout private
Definition at line 195 of file TrackContainerView.h.
Referenced by TrackContainerView(), addTrackView(), moveTrackView(), and removeTrackView().
m_tc
TrackContainer* lmms::gui::TrackContainerView::m_tc private
Definition at line 190 of file TrackContainerView.h.
Referenced by TrackContainerView(), dropEvent(), model(), model(), and moveTrackView().
m_trackViews
trackViewList lmms::gui::TrackContainerView::m_trackViews private
Definition at line 192 of file TrackContainerView.h.
Referenced by TrackContainerView(), ~TrackContainerView(), addTrackView(), clearAllTracks(), createTrackView(), moveTrackView(), moveTrackViewDown(), moveTrackViewUp(), realignTracks(), removeTrackView(), scrollToTrackView(), setPixelsPerBar(), totalHeightOfTracks(), trackViewAt(), and trackViews().
The documentation for this class was generated from the following files:
include/TrackContainerView.h
src/gui/editors/TrackContainerView.cpp