LMMS: Jack::JackInternalClient Class Reference
Jack::JackInternalClient Class Reference
Internal clients in the server.
#include <JackInternalClient.h>
Public Member Functions
JackInternalClient (JackServer *server, JackSynchro *table)
Client control.
virtual ~JackInternalClient ()
JackClientControl * GetClientControl () const
JackEngineControl * GetEngineControl () const
JackGraphManager * GetGraphManager () const
int Open (const char *server_name, const char *name, jack_uuid_t uuid, jack_options_t options, jack_status_t *status)
void ShutDown (jack_status_t code, const char *message)
Public Member Functions inherited from Jack::JackClient
JackClient (JackSynchro *table)
virtual ~JackClient ()
virtual int Activate ()
We need to start thread before activating in the server, otherwise the FW driver connected to the client may not be activated.
virtual int ClientHasSessionCallback (const char *client_name)
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual int ComputeTotalLatencies ()
void CycleSignal (int status)
jack_nframes_t CycleWait ()
virtual int Deactivate ()
Need to stop thread after deactivating in the server.
bool Execute ()
RT thread.
virtual char * GetClientNameByUUID (const char *uuid)
virtual jack_nframes_t GetCurrentTransportFrame ()
virtual char * GetInternalClientName (int ref)
char * GetServerName ()
virtual jack_native_thread_t GetThreadID ()
virtual char * GetUUIDForClientName (const char *client_name)
bool Init ()
Called once when the thread starts.
virtual int InternalClientHandle (const char *client_name, jack_status_t *status)
virtual int InternalClientLoad (const char *client_name, jack_options_t options, jack_status_t *status, jack_varargs_t *va)
virtual void InternalClientUnload (int ref, jack_status_t *status)
virtual void OnInfoShutdown (JackInfoShutdownCallback callback, void *arg)
virtual void OnShutdown (JackShutdownCallback callback, void *arg)
virtual int PortConnect (const char *src, const char *dst)
virtual int PortDisconnect (const char *src, const char *dst)
virtual int PortDisconnect (jack_port_id_t src)
virtual int PortIsMine (jack_port_id_t port_index)
virtual int PortRegister (const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
virtual int PortRename (jack_port_id_t port_index, const char *name)
virtual int PortUnRegister (jack_port_id_t port)
virtual int PropertyChangeNotify (jack_uuid_t subject, const char *key, jack_property_change_t change)
virtual int ReleaseTimebase ()
virtual int ReserveClientName (const char *client_name, const char *uuid)
virtual jack_session_command_t * SessionNotify (const char *target, jack_session_event_type_t type, const char *path)
virtual int SessionReply (jack_session_event_t *ev)
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetBufferSizeCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetClientRegistrationCallback (JackClientRegistrationCallback callback, void *arg)
virtual int SetFreeWheel (int onoff)
virtual int SetFreewheelCallback (JackFreewheelCallback callback, void *arg)
virtual int SetGraphOrderCallback (JackGraphOrderCallback callback, void *arg)
virtual int SetInitCallback (JackThreadInitCallback callback, void *arg)
virtual int SetLatencyCallback (JackLatencyCallback callback, void *arg)
virtual int SetPortConnectCallback (JackPortConnectCallback callback, void *arg)
virtual int SetPortRegistrationCallback (JackPortRegistrationCallback callback, void *arg)
virtual int SetPortRenameCallback (JackPortRenameCallback callback, void *arg)
virtual int SetProcessCallback (JackProcessCallback callback, void *arg)
virtual int SetProcessThread (JackThreadCallback fun, void *arg)
virtual int SetPropertyChangeCallback (JackPropertyChangeCallback callback, void *arg)
virtual int SetSampleRateCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetSessionCallback (JackSessionCallback callback, void *arg)
virtual int SetSyncCallback (JackSyncCallback sync_callback, void *arg)
virtual int SetSyncTimeout (jack_time_t timeout)
virtual int SetTimebaseCallback (int conditional, JackTimebaseCallback timebase_callback, void *arg)
virtual int SetXRunCallback (JackXRunCallback callback, void *arg)
virtual void TransportLocate (jack_nframes_t frame)
virtual jack_transport_state_t TransportQuery (jack_position_t *pos)
virtual int TransportReposition (const jack_position_t *pos)
virtual void TransportStart ()
virtual void TransportStop ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Static Public Attributes
static JackEngineControl * fEngineControl = NULL
Shared memory Port manager.
static JackGraphManager * fGraphManager = NULL
Private Attributes
JackClientControl fClientControl
Additional Inherited Members
Protected Member Functions inherited from Jack::JackClient
int ActivateAux ()
int CallProcessCallback ()
void CallSyncCallback ()
void CallSyncCallbackAux ()
void CallTimebaseCallback ()
void CallTimebaseCallbackAux ()
virtual int ClientNotifyImp (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value)
Notification received from the server.
void CycleSignalAux (int status)
jack_nframes_t CycleWaitAux ()
void DummyCycle ()
void End ()
void Error ()
void ExecuteThread ()
int HandleLatencyCallback (int status)
void InitAux ()
bool IsActive ()
void SetupDriverSync (bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
void SetupRealTime ()
void SignalSync ()
int StartThread ()
bool WaitSync ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Protected Attributes inherited from Jack::JackClient
JackBufferSizeCallback fBufferSize
void * fBufferSizeArg
detail::JackClientChannelInterface * fChannel
Thread to execute the Process function.
JackClientRegistrationCallback fClientRegistration
void * fClientRegistrationArg
JackFreewheelCallback fFreewheel
void * fFreewheelArg
JackGraphOrderCallback fGraphOrder
void * fGraphOrderArg
JackInfoShutdownCallback fInfoShutdown
void * fInfoShutdownArg
JackThreadInitCallback fInit
void * fInitArg
JackLatencyCallback fLatency
void * fLatencyArg
JackPortConnectCallback fPortConnect
void * fPortConnectArg
std::list< jack_port_id_t > fPortList
JackPortRegistrationCallback fPortRegistration
void * fPortRegistrationArg
JackPortRenameCallback fPortRename
void * fPortRenameArg
JackProcessCallback fProcess
void * fProcessArg
JackPropertyChangeCallback fPropertyChange
void * fPropertyChangeArg
JackSampleRateCallback fSampleRate
void * fSampleRateArg
char fServerName [JACK_SERVER_NAME_SIZE+1]
JackSessionCallback fSession
void * fSessionArg
JackSessionReply fSessionReply
JackShutdownCallback fShutdown
void * fShutdownArg
JackSyncCallback fSync
void * fSyncArg
JackSynchro * fSynchroTable
JackThread fThread
JackThreadCallback fThreadFun
void * fThreadFunArg
JackTimebaseCallback fTimebase
void * fTimebaseArg
JackXRunCallback fXrun
void * fXrunArg
Detailed Description
Internal clients in the server.
Definition at line 37 of file JackInternalClient.h.
Constructor & Destructor Documentation
JackInternalClient()
Jack::JackInternalClient::JackInternalClient (JackServer * server, JackSynchro * table)
Client control.
Definition at line 61 of file JackInternalClient.cpp.
References Jack::JackClient::JackClient(), Jack::JackClient::fChannel, and server().
Referenced by Jack::JackLoadableInternalClient::JackLoadableInternalClient().
~JackInternalClient()
Jack::JackInternalClient::~JackInternalClient () virtual
Definition at line 66 of file JackInternalClient.cpp.
References Jack::JackClient::fChannel.
Member Function Documentation
GetClientControl()
JackClientControl * Jack::JackInternalClient::GetClientControl () const virtual
Implements Jack::JackClientInterface.
Definition at line 138 of file JackInternalClient.cpp.
References fClientControl.
GetEngineControl()
JackEngineControl * Jack::JackInternalClient::GetEngineControl () const virtual
Implements Jack::JackClient.
Definition at line 132 of file JackInternalClient.cpp.
References fEngineControl.
GetGraphManager()
JackGraphManager * Jack::JackInternalClient::GetGraphManager () const virtual
Implements Jack::JackClient.
Definition at line 126 of file JackInternalClient.cpp.
References fGraphManager.
Open()
int Jack::JackInternalClient::Open (const char * server_name, const char * name, jack_uuid_t uuid, jack_options_t options, jack_status_t * status) virtual
Implements Jack::JackClient.
Reimplemented in Jack::JackLoadableInternalClient1, and Jack::JackLoadableInternalClient2.
Definition at line 71 of file JackInternalClient.cpp.
References Jack::JackClient::fChannel, fClientControl, Jack::JackGlobals::fClientTable, fEngineControl, fGraphManager, Jack::JackClient::fServerName, Jack::JackGlobals::fServerRunning, JACK_CLIENT_NAME_SIZE, jack_error, jack_log(), JACK_PROTOCOL_VERSION, JackVersionError, server_name, and Jack::JackClient::SetupDriverSync().
Referenced by Jack::JackLoadableInternalClient1::Open(), and Jack::JackLoadableInternalClient2::Open().
ShutDown()
void Jack::JackInternalClient::ShutDown (jack_status_t code, const char * message) virtual
Reimplemented from Jack::JackClient.
Definition at line 120 of file JackInternalClient.cpp.
References jack_log(), and Jack::JackClient::ShutDown().
Member Data Documentation
fClientControl
JackClientControl Jack::JackInternalClient::fClientControl private
Definition at line 42 of file JackInternalClient.h.
Referenced by GetClientControl(), and Open().
fEngineControl
JackEngineControl * Jack::JackInternalClient::fEngineControl = NULL static
Shared memory Port manager.
Definition at line 57 of file JackInternalClient.h.
Referenced by GetEngineControl(), and Open().
fGraphManager
JackGraphManager * Jack::JackInternalClient::fGraphManager = NULL static
Definition at line 56 of file JackInternalClient.h.
Referenced by GetGraphManager(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackInternalClient.h
src/3rdparty/jack2/common/JackInternalClient.cpp