LMMS: lmms::LinkedModelGroup Class Reference
lmms::LinkedModelGroup Class Reference
Base class for a group of linked models.
#include <LinkedModelGroups.h>
Classes
struct ModelInfo
Signals
void modelAdded (lmms::AutomatableModel *added)
void modelRemoved (lmms::AutomatableModel *removed)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
LinkedModelGroup (Model *parent)
void addModel (class AutomatableModel *model, const QString &name)
Register a further model.
void clearModels ()
Remove all models.
bool containsModel (const QString &name) const
bool eraseModel (const QString &name)
Unregister a model, return true if a model was erased.
template<class Functor>
void foreach_model (const Functor &ftor)
template<class Functor>
void foreach_model (const Functor &ftor) const
AutomatableModel * getModel (const std::string &s)
void linkControls (LinkedModelGroup *other)
void loadValues (const class QDomElement &that)
std::size_t modelNum () const
void removeControl (AutomatableModel *)
void saveValues (class QDomDocument &doc, class QDomElement &that)
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Private Attributes
std::map< std::string, ModelInfo > m_models
models for the controls
Detailed Description
Base class for a group of linked models.
See the LinkedModelGroup class for explanations
Features: Models are stored by their QObject::objectName Models are linked automatically
Definition at line 53 of file LinkedModelGroups.h.
Constructor & Destructor Documentation
LinkedModelGroup()
lmms::LinkedModelGroup::LinkedModelGroup (Model * parent) inline
Parameters
parent model of the LinkedModelGroups class
Definition at line 61 of file LinkedModelGroups.h.
References lmms::Model::Model().
Referenced by linkControls().
Member Function Documentation
addModel()
void lmms::LinkedModelGroup::addModel (class AutomatableModel * model, const QString & name)
Register a further model.
Definition at line 79 of file LinkedModelGroups.cpp.
References containsModel(), lmms::Model::dataChanged(), lmms::AutomatableModel::destroyed(), eraseModel(), m_models, modelAdded(), and modelRemoved().
clearModels()
void lmms::LinkedModelGroup::clearModels ()
Remove all models.
Definition at line 121 of file LinkedModelGroups.cpp.
References m_models.
containsModel()
bool lmms::LinkedModelGroup::containsModel (const QString & name) const
Definition at line 129 of file LinkedModelGroups.cpp.
References m_models.
Referenced by addModel(), and removeControl().
eraseModel()
bool lmms::LinkedModelGroup::eraseModel (const QString & name)
Unregister a model, return true if a model was erased.
Definition at line 113 of file LinkedModelGroups.cpp.
References m_models.
Referenced by addModel(), and removeControl().
foreach_model() [1/2]
template<class Functor> void lmms::LinkedModelGroup::foreach_model (const Functor & ftor) inline
Definition at line 82 of file LinkedModelGroups.h.
References m_models.
Referenced by linkControls(), loadValues(), lmms::gui::LinkedModelGroupView::modelChanged(), and saveValues().
foreach_model() [2/2]
template<class Functor> void lmms::LinkedModelGroup::foreach_model (const Functor & ftor) const inline
Definition at line 91 of file LinkedModelGroups.h.
References m_models.
getModel()
AutomatableModel * lmms::LinkedModelGroup::getModel (const std::string & s) inline
Definition at line 118 of file LinkedModelGroups.h.
References m_models.
linkControls()
void lmms::LinkedModelGroup::linkControls (LinkedModelGroup * other)
Definition at line 43 of file LinkedModelGroups.cpp.
References LinkedModelGroup(), foreach_model(), lmms::AutomatableModel::linkModels(), lmms::LinkedModelGroup::ModelInfo::m_model, and m_models.
Referenced by lmms::LinkedModelGroups::linkAllModels().
loadValues()
void lmms::LinkedModelGroup::loadValues (const class QDomElement & that)
Definition at line 67 of file LinkedModelGroups.cpp.
References foreach_model(), lmms::AutomatableModel::loadSettings(), lmms::LinkedModelGroup::ModelInfo::m_model, and lmms::LinkedModelGroup::ModelInfo::m_name.
modelAdded
void lmms::LinkedModelGroup::modelAdded (lmms::AutomatableModel * added) signal
Referenced by addModel().
modelNum()
std::size_t lmms::LinkedModelGroup::modelNum () const inline
Definition at line 99 of file LinkedModelGroups.h.
References m_models.
modelRemoved
void lmms::LinkedModelGroup::modelRemoved (lmms::AutomatableModel * removed) signal
Referenced by addModel(), and removeControl().
removeControl()
void lmms::LinkedModelGroup::removeControl (AutomatableModel * mdl)
Definition at line 101 of file LinkedModelGroups.cpp.
References containsModel(), eraseModel(), and modelRemoved().
saveValues()
void lmms::LinkedModelGroup::saveValues (class QDomDocument & doc, class QDomElement & that)
Definition at line 56 of file LinkedModelGroups.cpp.
References foreach_model(), lmms::LinkedModelGroup::ModelInfo::m_model, lmms::LinkedModelGroup::ModelInfo::m_name, and lmms::AutomatableModel::saveSettings().
Referenced by lmms::LinkedModelGroups::saveSettings().
Member Data Documentation
m_models
std::map<std::string, ModelInfo> lmms::LinkedModelGroup::m_models private
models for the controls
Note
The AutomatableModels behind the ModelInfo are not owned, but referenced after addModel is being called.
Definition at line 136 of file LinkedModelGroups.h.
Referenced by addModel(), clearModels(), containsModel(), eraseModel(), foreach_model(), foreach_model(), getModel(), linkControls(), and modelNum().
The documentation for this class was generated from the following files:
include/LinkedModelGroups.h
src/core/LinkedModelGroups.cpp