LMMS: ringbuffer_reader_base Class Reference
ringbuffer_reader_base Class Reference
#include <ringbuffer.h>
Protected Member Functions
ringbuffer_reader_base (std::size_t sz)
std::size_t read_space (std::size_t w) const
returns number of objects that can be read at least
std::size_t read_space_1 (std::size_t range) const
returns read space of first halve (the one starting at read ptr)
std::size_t read_space_2 (std::size_t range) const
returns read space of second halve
Protected Member Functions inherited from ringbuffer_common_t
ringbuffer_common_t (std::size_t sz)
Protected Attributes
std::size_t read_ptr = 0
reader at buf[read_ptr]
Protected Attributes inherited from ringbuffer_common_t
const std::size_t size
< max number of objects in buffer (2^n for some n)
const std::size_t size_mask
= size - 1
Detailed Description
Definition at line 235 of file ringbuffer.h.
Constructor & Destructor Documentation
ringbuffer_reader_base()
ringbuffer_reader_base::ringbuffer_reader_base (std::size_t sz) protected
Definition at line 146 of file ringbuffer.cpp.
References ringbuffer_common_t::ringbuffer_common_t().
Referenced by ringbuffer_reader_t< T >::ringbuffer_reader_t(), and ringbuffer_reader_t< T >::ringbuffer_reader_t().
Member Function Documentation
read_space()
std::size_t ringbuffer_reader_base::read_space (std::size_t w) const protected
returns number of objects that can be read at least
Definition at line 151 of file ringbuffer.cpp.
References read_ptr, ringbuffer_common_t::size, and ringbuffer_common_t::size_mask.
Referenced by ringbuffer_reader_t< T >::read_space().
read_space_1()
std::size_t ringbuffer_reader_base::read_space_1 (std::size_t range) const protected
returns read space of first halve (the one starting at read ptr)
Definition at line 161 of file ringbuffer.cpp.
References read_ptr, and ringbuffer_common_t::size.
read_space_2()
std::size_t ringbuffer_reader_base::read_space_2 (std::size_t range) const protected
returns read space of second halve
Definition at line 169 of file ringbuffer.cpp.
References read_ptr.
Member Data Documentation
read_ptr
std::size_t ringbuffer_reader_base::read_ptr = 0 protected
reader at buf[read_ptr]
Definition at line 238 of file ringbuffer.h.
Referenced by read_space(), read_space_1(), read_space_2(), and ringbuffer_reader_t< T >::try_inc().
The documentation for this class was generated from the following files:
src/3rdparty/ringbuffer/include/ringbuffer/ringbuffer.h
src/3rdparty/ringbuffer/src/lib/ringbuffer.cpp