LMMS: lmms::JournallingObject Class Reference
lmms::JournallingObject Class Reference
#include <JournallingObject.h>
Public Member Functions
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
void setHook (SerializingObjectHook *_hook)
Protected Member Functions
void changeID (jo_id_t _id)
Protected Member Functions inherited from lmms::SerializingObject
virtual void loadSettings (const QDomElement &element)=0
virtual void saveSettings (QDomDocument &doc, QDomElement &element)=0
Private Attributes
jo_id_t m_id
bool m_journalling
QStack< bool > m_journallingStateStack
Detailed Description
Definition at line 36 of file JournallingObject.h.
Constructor & Destructor Documentation
JournallingObject()
lmms::JournallingObject::JournallingObject ()
Definition at line 36 of file JournallingObject.cpp.
References lmms::SerializingObject::SerializingObject(), m_id, m_journalling, and m_journallingStateStack.
Referenced by lmms::Controller::Controller(), lmms::EffectControls::EffectControls(), lmms::Mixer::Mixer(), lmms::Plugin::Plugin(), lmms::TrackContainer::TrackContainer(), lmms::gui::TrackContainerView::TrackContainerView(), and changeID().
~JournallingObject()
lmms::JournallingObject::~JournallingObject () override
Definition at line 47 of file JournallingObject.cpp.
References lmms::ProjectJournal::freeID(), and lmms::Engine::projectJournal().
Member Function Documentation
addJournalCheckPoint()
void lmms::JournallingObject::addJournalCheckPoint ()
Definition at line 58 of file JournallingObject.cpp.
References lmms::ProjectJournal::addJournalCheckPoint(), isJournalling(), and lmms::Engine::projectJournal().
Referenced by lmms::MidiClip::clear(), lmms::gui::TrackOperationsWidget::clearTrack(), lmms::gui::MidiClipView::mergeClips(), lmms::gui::Fader::mousePressEvent(), lmms::gui::FloatModelEditorBase::mousePressEvent(), lmms::gui::LcdFloatSpinBox::mousePressEvent(), lmms::gui::LcdSpinBox::mousePressEvent(), lmms::gui::TrackContentWidget::mousePressEvent(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::MidiClip::reverseNotes(), lmms::AutomatableModel::setValue(), lmms::MidiClip::splitNotes(), lmms::MidiClip::splitNotesAlongLine(), and lmms::gui::ClipView::toggleSelectedAutoResize().
changeID()
void lmms::JournallingObject::changeID (jo_id_t _id) protected
Definition at line 117 of file JournallingObject.cpp.
References JournallingObject(), lmms::ProjectJournal::freeID(), m_id, lmms::SerializingObject::nodeName(), lmms::Engine::projectJournal(), and lmms::ProjectJournal::reallocID().
Referenced by lmms::AutomatableModel::loadSettings(), and restoreState().
id()
jo_id_t lmms::JournallingObject::id () const inline
Definition at line 42 of file JournallingObject.h.
References m_id.
Referenced by lmms::ProjectJournal::addJournalCheckPoint(), lmms::gui::TrackContentWidget::canPasteSelection(), and lmms::gui::ClipView::createClipDataFiles().
isJournalling()
bool lmms::JournallingObject::isJournalling () const inline
Definition at line 68 of file JournallingObject.h.
References m_journalling.
Referenced by addJournalCheckPoint(), saveState(), and lmms::AutomatableModel::setValue().
isJournallingStateStackEmpty()
bool lmms::JournallingObject::isJournallingStateStackEmpty () const inline
Definition at line 85 of file JournallingObject.h.
References m_journallingStateStack.
Referenced by restoreJournallingState().
restoreJournallingState()
void lmms::JournallingObject::restoreJournallingState () inline
Definition at line 53 of file JournallingObject.h.
References isJournallingStateStackEmpty(), m_journalling, and m_journallingStateStack.
Referenced by lmms::PatternClip::PatternClip(), lmms::SampleClip::SampleClip(), lmms::SampleClip::SampleClip(), lmms::gui::TrackContentWidget::addClipView(), lmms::MidiClip::init(), lmms::gui::Fader::mouseReleaseEvent(), lmms::gui::FloatModelEditorBase::mouseReleaseEvent(), lmms::gui::LcdFloatSpinBox::mouseReleaseEvent(), lmms::gui::LcdSpinBox::mouseReleaseEvent(), and restoreState().
restoreState()
void lmms::JournallingObject::restoreState (const QDomElement & _this) override virtual
Reimplemented from lmms::SerializingObject.
Definition at line 90 of file JournallingObject.cpp.
References changeID(), restoreJournallingState(), lmms::SerializingObject::restoreState(), and saveJournallingState().
Referenced by lmms::Clip::copyStateTo(), lmms::Track::create(), lmms::Song::loadProject(), lmms::Effect::loadSettings(), lmms::EffectChain::loadSettings(), lmms::InstrumentSoundShaping::loadSettings(), lmms::Track::loadTrack(), lmms::PatternTrack::loadTrackSpecificSettings(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::ProjectJournal::redo(), and lmms::ProjectJournal::undo().
saveJournallingState()
void lmms::JournallingObject::saveJournallingState (const bool newState) inline
Definition at line 47 of file JournallingObject.h.
References m_journalling, and m_journallingStateStack.
Referenced by lmms::PatternClip::PatternClip(), lmms::SampleClip::SampleClip(), lmms::SampleClip::SampleClip(), lmms::gui::TrackContentWidget::addClipView(), lmms::MidiClip::init(), lmms::gui::MidiClipView::mergeClips(), lmms::gui::Fader::mousePressEvent(), lmms::gui::FloatModelEditorBase::mousePressEvent(), lmms::gui::LcdFloatSpinBox::mousePressEvent(), lmms::gui::LcdSpinBox::mousePressEvent(), and restoreState().
saveState()
QDomElement lmms::JournallingObject::saveState (QDomDocument & _doc, QDomElement & _parent) override virtual
Reimplemented from lmms::SerializingObject.
Definition at line 69 of file JournallingObject.cpp.
References isJournalling(), and lmms::SerializingObject::saveState().
Referenced by lmms::ProjectJournal::addJournalCheckPoint(), lmms::Track::clone(), lmms::Clip::copyStateTo(), lmms::ProjectJournal::redo(), lmms::saveEnvelopeAndLFOParameters(), lmms::Song::saveProjectFile(), lmms::Effect::saveSettings(), lmms::PatternTrack::saveTrackSpecificSettings(), and lmms::ProjectJournal::undo().
setJournalling()
void lmms::JournallingObject::setJournalling (const bool _sr) inline
Definition at line 73 of file JournallingObject.h.
References m_journalling.
Referenced by lmms::Clip::Clip(), lmms::ComboBoxModel::ComboBoxModel(), lmms::PreviewTrackContainer::PreviewTrackContainer(), lmms::gui::AutomatableButtonGroup::addButton(), lmms::TempoSyncKnobModel::calculateTempoSyncTime(), and lmms::AutomatableModel::setInitValue().
testAndSetJournalling()
bool lmms::JournallingObject::testAndSetJournalling (const bool newState) inline
Definition at line 78 of file JournallingObject.h.
References m_journalling.
Referenced by lmms::TempoSyncKnobModel::calculateTempoSyncTime(), and lmms::AutomatableModel::setInitValue().
Member Data Documentation
m_id
jo_id_t lmms::JournallingObject::m_id private
Definition at line 95 of file JournallingObject.h.
Referenced by JournallingObject(), changeID(), and id().
m_journalling
bool lmms::JournallingObject::m_journalling private
Definition at line 97 of file JournallingObject.h.
Referenced by JournallingObject(), isJournalling(), restoreJournallingState(), saveJournallingState(), setJournalling(), and testAndSetJournalling().
m_journallingStateStack
QStack<bool> lmms::JournallingObject::m_journallingStateStack private
Definition at line 99 of file JournallingObject.h.
Referenced by JournallingObject(), isJournallingStateStackEmpty(), restoreJournallingState(), and saveJournallingState().
The documentation for this class was generated from the following files:
include/JournallingObject.h
src/core/JournallingObject.cpp