LMMS: hiir::Upsampler2x8F64Avx512< NC > Class Template Reference
hiir::Upsampler2x8F64Avx512< NC > Class Template Reference
#include <Upsampler2x8F64Avx512.h>
Public Types
typedef double DataType
Public Member Functions
Upsampler2x8F64Avx512 () noexcept
Upsampler2x8F64Avx512 (const Upsampler2x8F64Avx512< NC > &other)=default
Upsampler2x8F64Avx512 (Upsampler2x8F64Avx512< NC > &&other)=default
~Upsampler2x8F64Avx512 ()=default
void clear_buffers () noexcept
Upsampler2x8F64Avx512< NC > & operator= (const Upsampler2x8F64Avx512< NC > &other)=default
Upsampler2x8F64Avx512< NC > & operator= (Upsampler2x8F64Avx512< NC > &&other)=default
void process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (__m512d &out_0, __m512d &out_1, __m512d input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 8
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Avx512, NBR_COEFS+2 > Filter
Private Member Functions
bool operator!= (const Upsampler2x8F64Avx512< NC > &other) const =delete
bool operator== (const Upsampler2x8F64Avx512< NC > &other) const =delete
Private Attributes
Filter _filter
Detailed Description
template<int NC>
class hiir::Upsampler2x8F64Avx512< NC >
Definition at line 53 of file Upsampler2x8F64Avx512.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::Upsampler2x8F64Avx512< NC >::DataType
Definition at line 62 of file Upsampler2x8F64Avx512.h.
Filter
template<int NC> typedef std::array<StageDataF64Avx512, NBR_COEFS + 2> hiir::Upsampler2x8F64Avx512< NC >::Filter private
Definition at line 95 of file Upsampler2x8F64Avx512.h.
Constructor & Destructor Documentation
Upsampler2x8F64Avx512() [1/3]
template<int NC> hiir::Upsampler2x8F64Avx512< NC >::Upsampler2x8F64Avx512 () noexcept
Definition at line 55 of file Upsampler2x8F64Avx512.hpp.
References _filter, clear_buffers(), i, and NBR_COEFS.
Referenced by Upsampler2x8F64Avx512(), Upsampler2x8F64Avx512(), ~Upsampler2x8F64Avx512(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2x8F64Avx512() [2/3]
template<int NC> hiir::Upsampler2x8F64Avx512< NC >::Upsampler2x8F64Avx512 (const Upsampler2x8F64Avx512< NC > & other) default
References Upsampler2x8F64Avx512().
Upsampler2x8F64Avx512() [3/3]
template<int NC> hiir::Upsampler2x8F64Avx512< NC >::Upsampler2x8F64Avx512 (Upsampler2x8F64Avx512< NC > && other) default
References Upsampler2x8F64Avx512().
~Upsampler2x8F64Avx512()
template<int NC> hiir::Upsampler2x8F64Avx512< NC >::~Upsampler2x8F64Avx512 () default
References Upsampler2x8F64Avx512().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2x8F64Avx512< NC >::clear_buffers () noexcept
Definition at line 181 of file Upsampler2x8F64Avx512.hpp.
References _filter, i, and NBR_COEFS.
Referenced by Upsampler2x8F64Avx512(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2x8F64Avx512< NC >::operator!= (const Upsampler2x8F64Avx512< NC > & other) const private delete
References Upsampler2x8F64Avx512().
operator=() [1/2]
template<int NC> Upsampler2x8F64Avx512< NC > & hiir::Upsampler2x8F64Avx512< NC >::operator= (const Upsampler2x8F64Avx512< NC > & other) default
References Upsampler2x8F64Avx512().
operator=() [2/2]
template<int NC> Upsampler2x8F64Avx512< NC > & hiir::Upsampler2x8F64Avx512< NC >::operator= (Upsampler2x8F64Avx512< NC > && other) default
References Upsampler2x8F64Avx512(), clear_buffers(), hiir_FORCEINLINE, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2x8F64Avx512< NC >::operator== (const Upsampler2x8F64Avx512< NC > & other) const private delete
References Upsampler2x8F64Avx512().
process_block()
template<int NC> void hiir::Upsampler2x8F64Avx512< NC >::process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 146 of file Upsampler2x8F64Avx512.hpp.
References _nbr_chn, pos, and process_sample().
Referenced by operator=().
process_sample()
template<int NC> void hiir::Upsampler2x8F64Avx512< NC >::process_sample (__m512d & out_0, __m512d & out_1, __m512d input) noexcept
Definition at line 112 of file Upsampler2x8F64Avx512.hpp.
References _filter, NBR_COEFS, and hiir::StageProc8F64Avx512< REMAINING >::process_sample_pos().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::Upsampler2x8F64Avx512< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 83 of file Upsampler2x8F64Avx512.hpp.
References _filter, i, and NBR_COEFS.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Upsampler2x8F64Avx512< NC >::_delay = 0 static constexpr
Definition at line 65 of file Upsampler2x8F64Avx512.h.
_filter
template<int NC> Filter hiir::Upsampler2x8F64Avx512< NC >::_filter private
Definition at line 97 of file Upsampler2x8F64Avx512.h.
Referenced by Upsampler2x8F64Avx512(), clear_buffers(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Upsampler2x8F64Avx512< NC >::_nbr_chn = 8 static constexpr
Definition at line 63 of file Upsampler2x8F64Avx512.h.
Referenced by process_block().
NBR_COEFS
template<int NC> int hiir::Upsampler2x8F64Avx512< NC >::NBR_COEFS = NC static constexpr
Definition at line 64 of file Upsampler2x8F64Avx512.h.
Referenced by Upsampler2x8F64Avx512(), clear_buffers(), operator=(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2x8F64Avx512.h
src/3rdparty/hiir/hiir/Upsampler2x8F64Avx512.hpp