LMMS: hiir::HalfBand8F64Avx512< NC > Class Template Reference
hiir::HalfBand8F64Avx512< NC > Class Template Reference
#include <HalfBand8F64Avx512.h>
Classes
struct EvenOdd
Public Types
typedef double DataType
Public Member Functions
HalfBand8F64Avx512 () noexcept
HalfBand8F64Avx512 (const HalfBand8F64Avx512< NC > &other)=default
HalfBand8F64Avx512 (HalfBand8F64Avx512< NC > &&other)=default
~HalfBand8F64Avx512 ()=default
void clear_buffers () noexcept
HalfBand8F64Avx512< NC > & operator= (const HalfBand8F64Avx512< NC > &other)=default
HalfBand8F64Avx512< NC > & operator= (HalfBand8F64Avx512< NC > &&other)=default
void process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
void process_block_2_paths (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_hpf (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
void process_block_split (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE __m512d process_sample (__m512d input) noexcept
hiir_FORCEINLINE __m512d process_sample_hpf (__m512d input) noexcept
hiir_FORCEINLINE void process_sample_split (__m512d &low, __m512d &high, __m512d input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 8
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Avx512, NBR_COEFS+2 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const HalfBand8F64Avx512 &other) const =delete
bool operator== (const HalfBand8F64Avx512 &other) const =delete
hiir_FORCEINLINE EvenOdd process_2_paths (__m512d input) noexcept
template<typename FL, typename FH>
hiir_FORCEINLINE void process_block_2_paths (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (double *, __m512d, __m512d) noexcept
static hiir_FORCEINLINE void store_high (double *ptr, __m512d tmp_0, __m512d tmp_1) noexcept
static hiir_FORCEINLINE void store_low (double *ptr, __m512d tmp_0, __m512d tmp_1) noexcept
Private Attributes
FilterBiPhase _bifilter
int _phase
double _prev [_nbr_chn]
Static Private Attributes
static constexpr int _nbr_phases = 2
Detailed Description
template<int NC>
class hiir::HalfBand8F64Avx512< NC >
Definition at line 49 of file HalfBand8F64Avx512.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::HalfBand8F64Avx512< NC >::DataType
Definition at line 58 of file HalfBand8F64Avx512.h.
Filter
template<int NC> typedef std::array<StageDataF64Avx512, NBR_COEFS + 2> hiir::HalfBand8F64Avx512< NC >::Filter private
Definition at line 103 of file HalfBand8F64Avx512.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::HalfBand8F64Avx512< NC >::FilterBiPhase private
Definition at line 105 of file HalfBand8F64Avx512.h.
Constructor & Destructor Documentation
HalfBand8F64Avx512() [1/3]
template<int NC> hiir::HalfBand8F64Avx512< NC >::HalfBand8F64Avx512 () noexcept
Definition at line 57 of file HalfBand8F64Avx512.hpp.
References _bifilter, _phase, clear_buffers(), i, and NBR_COEFS.
Referenced by HalfBand8F64Avx512(), HalfBand8F64Avx512(), ~HalfBand8F64Avx512(), operator!=(), operator=(), operator=(), and operator==().
HalfBand8F64Avx512() [2/3]
template<int NC> hiir::HalfBand8F64Avx512< NC >::HalfBand8F64Avx512 (const HalfBand8F64Avx512< NC > & other) default
References HalfBand8F64Avx512().
HalfBand8F64Avx512() [3/3]
template<int NC> hiir::HalfBand8F64Avx512< NC >::HalfBand8F64Avx512 (HalfBand8F64Avx512< NC > && other) default
References HalfBand8F64Avx512().
~HalfBand8F64Avx512()
template<int NC> hiir::HalfBand8F64Avx512< NC >::~HalfBand8F64Avx512 () default
References HalfBand8F64Avx512().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::HalfBand8F64Avx512< NC >::bypass (double * , __m512d , __m512d) inline static private noexcept
Definition at line 124 of file HalfBand8F64Avx512.h.
Referenced by process_block(), and process_block_hpf().
clear_buffers()
template<int NC> void hiir::HalfBand8F64Avx512< NC >::clear_buffers () noexcept
Definition at line 278 of file HalfBand8F64Avx512.hpp.
References _bifilter, _phase, _prev, i, and NBR_COEFS.
Referenced by HalfBand8F64Avx512(), and operator=().
operator!=()
template<int NC> bool hiir::HalfBand8F64Avx512< NC >::operator!= (const HalfBand8F64Avx512< NC > & other) const private delete
References HalfBand8F64Avx512().
operator=() [1/2]
template<int NC> HalfBand8F64Avx512< NC > & hiir::HalfBand8F64Avx512< NC >::operator= (const HalfBand8F64Avx512< NC > & other) default
References HalfBand8F64Avx512().
operator=() [2/2]
template<int NC> HalfBand8F64Avx512< NC > & hiir::HalfBand8F64Avx512< NC >::operator= (HalfBand8F64Avx512< NC > && other) default
References HalfBand8F64Avx512(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_hpf(), process_block_split(), process_sample(), process_sample_hpf(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::HalfBand8F64Avx512< NC >::operator== (const HalfBand8F64Avx512< NC > & other) const private delete
References HalfBand8F64Avx512().
process_2_paths()
template<int NC> HalfBand8F64Avx512< NC >::EvenOdd hiir::HalfBand8F64Avx512< NC >::process_2_paths (__m512d input) private noexcept
Definition at line 307 of file HalfBand8F64Avx512.hpp.
References _bifilter, _phase, _prev, NBR_COEFS, and hiir::StageProc8F64Avx512< REMAINING >::process_sample_pos().
Referenced by process_block_2_paths(), process_sample(), process_sample_hpf(), and process_sample_split().
process_block()
template<int NC> void hiir::HalfBand8F64Avx512< NC >::process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 140 of file HalfBand8F64Avx512.hpp.
References _nbr_chn, bypass(), process_block_2_paths(), and store_low().
Referenced by operator=().
process_block_2_paths() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE void hiir::HalfBand8F64Avx512< NC >::process_block_2_paths (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE.
Referenced by process_block(), process_block_hpf(), and process_block_split().
process_block_2_paths() [2/2]
template<int NC> template<typename FL, typename FH> void hiir::HalfBand8F64Avx512< NC >::process_block_2_paths (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 329 of file HalfBand8F64Avx512.hpp.
References _bifilter, _nbr_chn, _nbr_phases, _phase, _prev, NBR_COEFS, pos, process_2_paths(), and hiir::StageProc8F64Avx512< REMAINING >::process_sample_pos().
process_block_hpf()
template<int NC> void hiir::HalfBand8F64Avx512< NC >::process_block_hpf (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 192 of file HalfBand8F64Avx512.hpp.
References _nbr_chn, bypass(), process_block_2_paths(), and store_high().
Referenced by operator=().
process_block_split()
template<int NC> void hiir::HalfBand8F64Avx512< NC >::process_block_split (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 251 of file HalfBand8F64Avx512.hpp.
References _nbr_chn, process_block_2_paths(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> __m512d hiir::HalfBand8F64Avx512< NC >::process_sample (__m512d input) noexcept
Definition at line 114 of file HalfBand8F64Avx512.hpp.
References process_2_paths().
Referenced by operator=().
process_sample_hpf()
template<int NC> __m512d hiir::HalfBand8F64Avx512< NC >::process_sample_hpf (__m512d input) noexcept
Definition at line 165 of file HalfBand8F64Avx512.hpp.
References process_2_paths().
Referenced by operator=().
process_sample_split()
template<int NC> void hiir::HalfBand8F64Avx512< NC >::process_sample_split (__m512d & low, __m512d & high, __m512d input) noexcept
Definition at line 221 of file HalfBand8F64Avx512.hpp.
References process_2_paths().
Referenced by operator=().
set_coefs()
template<int NC> void hiir::HalfBand8F64Avx512< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 87 of file HalfBand8F64Avx512.hpp.
References _bifilter, i, and NBR_COEFS.
Referenced by operator=().
store_high()
template<int NC> void hiir::HalfBand8F64Avx512< NC >::store_high (double * ptr, __m512d tmp_0, __m512d tmp_1) static private noexcept
Definition at line 401 of file HalfBand8F64Avx512.hpp.
Referenced by process_block_hpf(), and process_block_split().
store_low()
template<int NC> void hiir::HalfBand8F64Avx512< NC >::store_low (double * ptr, __m512d tmp_0, __m512d tmp_1) static private noexcept
Definition at line 392 of file HalfBand8F64Avx512.hpp.
Referenced by process_block(), and process_block_split().
Member Data Documentation
_bifilter
template<int NC> FilterBiPhase hiir::HalfBand8F64Avx512< NC >::_bifilter private
Definition at line 126 of file HalfBand8F64Avx512.h.
Referenced by HalfBand8F64Avx512(), clear_buffers(), process_2_paths(), process_block_2_paths(), and set_coefs().
_delay
template<int NC> double hiir::HalfBand8F64Avx512< NC >::_delay = 0 static constexpr
Definition at line 61 of file HalfBand8F64Avx512.h.
_nbr_chn
template<int NC> int hiir::HalfBand8F64Avx512< NC >::_nbr_chn = 8 static constexpr
Definition at line 59 of file HalfBand8F64Avx512.h.
Referenced by process_block(), process_block_2_paths(), process_block_hpf(), and process_block_split().
_nbr_phases
template<int NC> int hiir::HalfBand8F64Avx512< NC >::_nbr_phases = 2 static constexpr private
Definition at line 101 of file HalfBand8F64Avx512.h.
Referenced by process_block_2_paths().
_phase
template<int NC> int hiir::HalfBand8F64Avx512< NC >::_phase private
Definition at line 129 of file HalfBand8F64Avx512.h.
Referenced by HalfBand8F64Avx512(), clear_buffers(), process_2_paths(), and process_block_2_paths().
_prev
template<int NC> double hiir::HalfBand8F64Avx512< NC >::_prev[_nbr_chn] private
Definition at line 128 of file HalfBand8F64Avx512.h.
Referenced by clear_buffers(), process_2_paths(), and process_block_2_paths().
NBR_COEFS
template<int NC> int hiir::HalfBand8F64Avx512< NC >::NBR_COEFS = NC static constexpr
Definition at line 60 of file HalfBand8F64Avx512.h.
Referenced by HalfBand8F64Avx512(), clear_buffers(), process_2_paths(), process_block_2_paths(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/HalfBand8F64Avx512.h
src/3rdparty/hiir/hiir/HalfBand8F64Avx512.hpp