LMMS: android::Shm Class Reference
android::Shm Class Reference
#include <Shm.h>
Public Member Functions
virtual ~Shm ()
int attach_lib_shm (jack_shm_info_t *)
int attach_lib_shm_read (jack_shm_info_t *)
int attach_shm (jack_shm_info_t *)
int attach_shm_read (jack_shm_info_t *)
int cleanup_shm (void)
void destroy_shm (jack_shm_info_t *)
int initialize_shm (const char *server_name)
int initialize_shm_client (void)
int initialize_shm_server (void)
int register_server (const char *server_name, int new_registry)
void release_lib_shm (jack_shm_info_t *)
void release_shm (jack_shm_info_t *)
int release_shm_info (jack_shm_registry_index_t)
int resize_shm (jack_shm_info_t *, jack_shmsize_t size)
char * shm_addr (unsigned int fd)
void shm_copy_from_registry (jack_shm_info_t *, jack_shm_registry_index_t)
void shm_copy_to_registry (jack_shm_info_t *, jack_shm_registry_index_t *)
int shmalloc (const char *shm_name, jack_shmsize_t size, jack_shm_info_t *result)
int unregister_server (const char *server_name)
Static Public Member Functions
static sp< IAndroidShm > getShmService ()
static Shm * Instantiate ()
static int jack_attach_lib_shm (jack_shm_info_t *)
static int jack_attach_lib_shm_read (jack_shm_info_t *)
static int jack_attach_shm (jack_shm_info_t *)
static int jack_attach_shm_read (jack_shm_info_t *)
static int jack_cleanup_shm (void)
static void jack_destroy_shm (jack_shm_info_t *)
static int jack_initialize_shm (const char *server_name)
static int jack_initialize_shm_client (void)
static int jack_initialize_shm_server (void)
static int jack_register_server (const char *server_name, int new_registry)
static void jack_release_lib_shm (jack_shm_info_t *)
static void jack_release_shm (jack_shm_info_t *)
static int jack_release_shm_info (jack_shm_registry_index_t)
static int jack_resize_shm (jack_shm_info_t *, jack_shmsize_t size)
static char * jack_shm_addr (jack_shm_info_t *si)
static void jack_shm_copy_from_registry (jack_shm_info_t *, jack_shm_registry_index_t)
static void jack_shm_copy_to_registry (jack_shm_info_t *, jack_shm_registry_index_t *)
static int jack_shmalloc (const char *shm_name, jack_shmsize_t size, jack_shm_info_t *result)
static int jack_unregister_server (const char *server_name)
Private Member Functions
Shm ()
Shm (const Shm &)
int access_registry (jack_shm_info_t *ri)
int create_registry (jack_shm_info_t *ri)
jack_shm_registry_t * get_free_shm_info ()
int GetPID ()
int GetUID ()
void jack_release_shm_entry (jack_shm_registry_index_t index)
int jack_shm_lock_registry (void)
void jack_shm_unlock_registry (void)
Shm & operator= (const Shm)
void release_shm_entry (jack_shm_registry_index_t index)
void remove_shm (jack_shm_id_t *id)
int server_initialize_shm (int new_registry)
void set_server_prefix (const char *server_name)
void shm_init_registry ()
int shm_lock_registry (void)
void shm_unlock_registry (void)
int shm_validate_registry ()
Static Private Attributes
static jack_shm_header_t * jack_shm_header = NULL
static jack_shm_registry_t * jack_shm_registry = NULL
static char jack_shm_server_prefix [JACK_SERVER_NAME_SIZE+1] = ""
static jack_shmtype_t jack_shmtype = shm_ANDROID
static sp< IMemoryHeap > mShmMemBase [JACK_SHM_HEAP_ENOUGH_COUNT] = {0,}
static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
static Shm * ref = NULL
static jack_shm_fd_t registry_fd = JACK_SHM_REGISTRY_FD
static jack_shm_id_t registry_id
static jack_shm_info_t registry_info
static int semid = -1
Detailed Description
Definition at line 50 of file Shm.h.
Constructor & Destructor Documentation
~Shm()
android::Shm::~Shm () virtual
Definition at line 124 of file Shm.cpp.
Shm() [1/2]
android::Shm::Shm () private
Definition at line 122 of file Shm.cpp.
Referenced by Shm(), Instantiate(), and operator=().
Shm() [2/2]
android::Shm::Shm (const Shm &) private
References Shm().
Member Function Documentation
access_registry()
int android::Shm::access_registry (jack_shm_info_t * ri) private
Definition at line 241 of file Shm.cpp.
References _jack_shm_info::attached_at, FALSE, getShmService(), _jack_shm_info::index, jack_d, jack_error, JACK_REGISTRY_NAME, jack_shm_header, jack_shm_registry, JACK_SHM_REGISTRY_FD, JACK_SHM_REGISTRY_INDEX, _jack_shm_info::ptr, registry_fd, registry_id, and shm_addr().
Referenced by initialize_shm(), and server_initialize_shm().
attach_lib_shm()
int android::Shm::attach_lib_shm (jack_shm_info_t * si)
Definition at line 722 of file Shm.cpp.
References attach_shm(), _jack_shm_info::index, jack_shm_registry, and _jack_shm_info::size.
Referenced by jack_attach_lib_shm().
attach_lib_shm_read()
int android::Shm::attach_lib_shm_read (jack_shm_info_t * si)
Definition at line 740 of file Shm.cpp.
References attach_shm_read(), _jack_shm_info::index, jack_shm_registry, and _jack_shm_info::size.
Referenced by jack_attach_lib_shm_read().
attach_shm()
int android::Shm::attach_shm (jack_shm_info_t * si)
Definition at line 711 of file Shm.cpp.
References _jack_shm_info::attached_at, _jack_shm_registry::id, _jack_shm_info::index, jack_error, jack_shm_registry, _jack_shm_info::ptr, and shm_addr().
Referenced by attach_lib_shm(), jack_attach_shm(), and resize_shm().
attach_shm_read()
int android::Shm::attach_shm_read (jack_shm_info_t * si)
Definition at line 729 of file Shm.cpp.
References _jack_shm_info::attached_at, _jack_shm_registry::id, _jack_shm_info::index, jack_error, jack_shm_registry, _jack_shm_info::ptr, and shm_addr().
Referenced by attach_lib_shm_read(), and jack_attach_shm_read().
cleanup_shm()
int android::Shm::cleanup_shm (void)
Definition at line 564 of file Shm.cpp.
References _jack_shm_registry::allocator, FALSE, GetPID(), i, _jack_shm_info::index, jack_error, jack_shm_registry, MAX_SHM_ID, release_shm(), release_shm_entry(), remove_shm(), shm_lock_registry(), shm_unlock_registry(), _jack_shm_registry::size, and TRUE.
Referenced by jack_cleanup_shm().
create_registry()
int android::Shm::create_registry (jack_shm_info_t * ri) private
Definition at line 337 of file Shm.cpp.
References _jack_shm_info::attached_at, getShmService(), _jack_shm_info::index, jack_d, jack_error, JACK_REGISTRY_NAME, jack_shm_header, jack_shm_registry, JACK_SHM_REGISTRY_FD, JACK_SHM_REGISTRY_INDEX, JACK_SHM_REGISTRY_SIZE, _jack_shm_info::ptr, registry_fd, registry_id, shm_addr(), shm_init_registry(), and _jack_shm_info::size.
Referenced by server_initialize_shm().
destroy_shm()
void android::Shm::destroy_shm (jack_shm_info_t * si)
Definition at line 702 of file Shm.cpp.
References _jack_shm_info::index, JACK_SHM_NULL_INDEX, jack_shm_registry, release_shm_info(), and remove_shm().
Referenced by jack_destroy_shm(), and resize_shm().
get_free_shm_info()
jack_shm_registry_t * android::Shm::get_free_shm_info () private
Definition at line 623 of file Shm.cpp.
References i, jack_shm_registry, and MAX_SHM_ID.
Referenced by shmalloc().
GetPID()
int android::Shm::GetPID () private
Definition at line 289 of file Shm.cpp.
Referenced by cleanup_shm(), register_server(), release_shm_info(), shmalloc(), and unregister_server().
getShmService()
sp< IAndroidShm > android::Shm::getShmService () static
Definition at line 126 of file Shm.cpp.
Referenced by access_registry(), Jack::JackAndroidSemaphore::Allocate(), Jack::JackAndroidSemaphore::ConnectInput(), create_registry(), remove_shm(), shm_addr(), and shmalloc().
GetUID()
int android::Shm::GetUID () private
Definition at line 285 of file Shm.cpp.
Referenced by set_server_prefix(), and shmalloc().
initialize_shm()
int android::Shm::initialize_shm (const char * server_name)
Definition at line 530 of file Shm.cpp.
References access_registry(), jack_error, jack_shm_header, registry_info, server_name, set_server_prefix(), shm_lock_registry(), shm_unlock_registry(), and shm_validate_registry().
Referenced by jack_initialize_shm().
initialize_shm_client()
int android::Shm::initialize_shm_client (void)
Definition at line 559 of file Shm.cpp.
Referenced by jack_initialize_shm_client().
initialize_shm_server()
int android::Shm::initialize_shm_server (void)
Definition at line 554 of file Shm.cpp.
Referenced by jack_initialize_shm_server().
Instantiate()
Shm * android::Shm::Instantiate () static
Definition at line 113 of file Shm.cpp.
References Shm(), jack_d, and ref.
Referenced by jack_attach_lib_shm(), jack_attach_lib_shm_read(), jack_attach_shm(), jack_attach_shm_read(), jack_cleanup_shm(), jack_destroy_shm(), jack_initialize_shm(), jack_initialize_shm_client(), jack_initialize_shm_server(), jack_register_server(), jack_release_lib_shm(), jack_release_shm(), jack_release_shm_info(), jack_resize_shm(), jack_shm_copy_from_registry(), jack_shm_copy_to_registry(), jack_shmalloc(), and jack_unregister_server().
jack_attach_lib_shm()
int android::Shm::jack_attach_lib_shm (jack_shm_info_t * si) static
Definition at line 812 of file Shm.cpp.
References attach_lib_shm(), and Instantiate().
Referenced by jack_attach_lib_shm().
jack_attach_lib_shm_read()
int android::Shm::jack_attach_lib_shm_read (jack_shm_info_t * si) static
Definition at line 818 of file Shm.cpp.
References attach_lib_shm_read(), and Instantiate().
Referenced by jack_attach_lib_shm_read().
jack_attach_shm()
int android::Shm::jack_attach_shm (jack_shm_info_t * si) static
Definition at line 809 of file Shm.cpp.
References attach_shm(), and Instantiate().
Referenced by jack_attach_shm().
jack_attach_shm_read()
int android::Shm::jack_attach_shm_read (jack_shm_info_t * si) static
Definition at line 815 of file Shm.cpp.
References attach_shm_read(), and Instantiate().
Referenced by jack_attach_shm_read().
jack_cleanup_shm()
int android::Shm::jack_cleanup_shm (void) static
Definition at line 794 of file Shm.cpp.
References cleanup_shm(), and Instantiate().
Referenced by jack_cleanup_shm().
jack_destroy_shm()
void android::Shm::jack_destroy_shm (jack_shm_info_t * si) static
Definition at line 806 of file Shm.cpp.
References destroy_shm(), and Instantiate().
Referenced by jack_destroy_shm().
jack_initialize_shm()
int android::Shm::jack_initialize_shm (const char * server_name) static
Definition at line 785 of file Shm.cpp.
References initialize_shm(), Instantiate(), and server_name.
Referenced by jack_initialize_shm().
jack_initialize_shm_client()
int android::Shm::jack_initialize_shm_client (void) static
Definition at line 791 of file Shm.cpp.
References initialize_shm_client(), and Instantiate().
Referenced by jack_initialize_shm_client().
jack_initialize_shm_server()
int android::Shm::jack_initialize_shm_server (void) static
Definition at line 788 of file Shm.cpp.
References initialize_shm_server(), and Instantiate().
Referenced by jack_initialize_shm_server().
jack_register_server()
int android::Shm::jack_register_server (const char * server_name, int new_registry) static
Definition at line 779 of file Shm.cpp.
References Instantiate(), register_server(), and server_name.
Referenced by jack_register_server().
jack_release_lib_shm()
void android::Shm::jack_release_lib_shm (jack_shm_info_t * si) static
Definition at line 803 of file Shm.cpp.
References Instantiate(), and release_lib_shm().
Referenced by jack_release_lib_shm().
jack_release_shm()
void android::Shm::jack_release_shm (jack_shm_info_t * si) static
Definition at line 800 of file Shm.cpp.
References Instantiate(), and release_shm().
Referenced by jack_release_shm().
jack_release_shm_entry()
void android::Shm::jack_release_shm_entry (jack_shm_registry_index_t index) private
Definition at line 154 of file Shm.cpp.
References jack_shm_registry.
Referenced by release_shm_info().
jack_release_shm_info()
int android::Shm::jack_release_shm_info (jack_shm_registry_index_t t) static
Definition at line 768 of file Shm.cpp.
References Instantiate(), and release_shm_info().
Referenced by jack_release_shm_info().
jack_resize_shm()
int android::Shm::jack_resize_shm (jack_shm_info_t * si, jack_shmsize_t size) static
Definition at line 821 of file Shm.cpp.
References Instantiate(), and resize_shm().
Referenced by jack_resize_shm().
jack_shm_addr()
char * android::Shm::jack_shm_addr (jack_shm_info_t * si) static
Definition at line 771 of file Shm.cpp.
References _jack_shm_info::attached_at, jack_error, and _jack_shm_info::ptr.
Referenced by jack_shm_addr().
jack_shm_copy_from_registry()
void android::Shm::jack_shm_copy_from_registry (jack_shm_info_t * si, jack_shm_registry_index_t t) static
Definition at line 762 of file Shm.cpp.
References Instantiate(), and shm_copy_from_registry().
Referenced by jack_shm_copy_from_registry().
jack_shm_copy_to_registry()
void android::Shm::jack_shm_copy_to_registry (jack_shm_info_t * si, jack_shm_registry_index_t * t) static
Definition at line 765 of file Shm.cpp.
References Instantiate(), and shm_copy_to_registry().
Referenced by jack_shm_copy_to_registry().
jack_shm_lock_registry()
int android::Shm::jack_shm_lock_registry (void) private
Definition at line 293 of file Shm.cpp.
References mutex.
Referenced by release_shm_info().
jack_shm_unlock_registry()
void android::Shm::jack_shm_unlock_registry (void) private
Definition at line 299 of file Shm.cpp.
References mutex.
Referenced by release_shm_info().
jack_shmalloc()
int android::Shm::jack_shmalloc (const char * shm_name, jack_shmsize_t size, jack_shm_info_t * result) static
Definition at line 797 of file Shm.cpp.
References Instantiate(), and shmalloc().
Referenced by jack_shmalloc().
jack_unregister_server()
int android::Shm::jack_unregister_server (const char * server_name) static
Definition at line 782 of file Shm.cpp.
References Instantiate(), server_name, and unregister_server().
Referenced by jack_unregister_server().
operator=()
Shm & android::Shm::operator= (const Shm) private
References Shm(), and server_name.
register_server()
int android::Shm::register_server (const char * server_name, int new_registry)
Definition at line 448 of file Shm.cpp.
References GetPID(), i, jack_d, jack_error, JACK_SERVER_NAME_SIZE, jack_shm_header, jack_shm_server_prefix, MAX_SERVERS, server_initialize_shm(), server_name, set_server_prefix(), shm_lock_registry(), and shm_unlock_registry().
Referenced by jack_register_server().
release_lib_shm()
void android::Shm::release_lib_shm (jack_shm_info_t *)
Definition at line 698 of file Shm.cpp.
Referenced by jack_release_lib_shm().
release_shm()
void android::Shm::release_shm (jack_shm_info_t *)
Definition at line 694 of file Shm.cpp.
Referenced by cleanup_shm(), jack_release_shm(), resize_shm(), and server_initialize_shm().
release_shm_entry()
void android::Shm::release_shm_entry (jack_shm_registry_index_t index) private
Definition at line 208 of file Shm.cpp.
References jack_shm_registry.
Referenced by cleanup_shm().
release_shm_info()
int android::Shm::release_shm_info (jack_shm_registry_index_t index)
Definition at line 163 of file Shm.cpp.
References GetPID(), jack_d, jack_error, jack_release_shm_entry(), jack_shm_lock_registry(), jack_shm_registry, and jack_shm_unlock_registry().
Referenced by destroy_shm(), and jack_release_shm_info().
remove_shm()
void android::Shm::remove_shm (jack_shm_id_t * id) private
Definition at line 216 of file Shm.cpp.
References getShmService(), i, jack_d, jack_error, JACK_REGISTRY_NAME, jack_shm_registry, MAX_SHM_ID, and registry_fd.
Referenced by cleanup_shm(), destroy_shm(), and server_initialize_shm().
resize_shm()
int android::Shm::resize_shm (jack_shm_info_t * si, jack_shmsize_t size)
Definition at line 747 of file Shm.cpp.
References attach_shm(), destroy_shm(), _jack_shm_info::index, jack_shm_registry, release_shm(), and shmalloc().
Referenced by jack_resize_shm().
server_initialize_shm()
int android::Shm::server_initialize_shm (int new_registry) private
Definition at line 397 of file Shm.cpp.
References access_registry(), create_registry(), jack_d, jack_error, jack_shm_header, registry_id, registry_info, release_shm(), remove_shm(), shm_lock_registry(), shm_unlock_registry(), and shm_validate_registry().
Referenced by register_server().
set_server_prefix()
void android::Shm::set_server_prefix (const char * server_name) private
Definition at line 325 of file Shm.cpp.
References GetUID(), jack_shm_server_prefix, and server_name.
Referenced by initialize_shm(), and register_server().
shm_addr()
char * android::Shm::shm_addr (unsigned int fd)
Definition at line 179 of file Shm.cpp.
References getShmService(), jack_error, JACK_SHM_HEAP_ENOUGH_COUNT, and mShmMemBase.
Referenced by access_registry(), attach_shm(), attach_shm_read(), and create_registry().
shm_copy_from_registry()
void android::Shm::shm_copy_from_registry (jack_shm_info_t * , jack_shm_registry_index_t)
Definition at line 147 of file Shm.cpp.
Referenced by jack_shm_copy_from_registry().
shm_copy_to_registry()
void android::Shm::shm_copy_to_registry (jack_shm_info_t * , jack_shm_registry_index_t *)
Definition at line 150 of file Shm.cpp.
Referenced by jack_shm_copy_to_registry().
shm_init_registry()
void android::Shm::shm_init_registry () private
Definition at line 305 of file Shm.cpp.
References i, jack_shm_header, JACK_SHM_MAGIC, jack_shm_registry, JACK_SHM_REGISTRY_SIZE, jack_shmtype, and MAX_SHM_ID.
Referenced by create_registry().
shm_lock_registry()
int android::Shm::shm_lock_registry (void) private
Definition at line 199 of file Shm.cpp.
References mutex.
Referenced by cleanup_shm(), initialize_shm(), register_server(), server_initialize_shm(), shmalloc(), and unregister_server().
shm_unlock_registry()
void android::Shm::shm_unlock_registry (void) private
Definition at line 204 of file Shm.cpp.
References mutex.
Referenced by cleanup_shm(), initialize_shm(), register_server(), server_initialize_shm(), shmalloc(), and unregister_server().
shm_validate_registry()
int android::Shm::shm_validate_registry () private
Definition at line 378 of file Shm.cpp.
References jack_shm_header, JACK_SHM_MAGIC, JACK_SHM_REGISTRY_SIZE, and jack_shmtype.
Referenced by initialize_shm(), and server_initialize_shm().
shmalloc()
int android::Shm::shmalloc (const char * shm_name, jack_shmsize_t size, jack_shm_info_t * result)
Definition at line 641 of file Shm.cpp.
References _jack_shm_registry::allocator, _jack_shm_info::attached_at, get_free_shm_info(), GetPID(), getShmService(), GetUID(), _jack_shm_registry::id, _jack_shm_info::index, _jack_shm_registry::index, jack_d, jack_error, _jack_shm_info::ptr, shm_lock_registry(), shm_unlock_registry(), and _jack_shm_registry::size.
Referenced by jack_shmalloc(), and resize_shm().
unregister_server()
int android::Shm::unregister_server (const char * server_name)
Definition at line 512 of file Shm.cpp.
References GetPID(), i, jack_error, jack_shm_header, MAX_SERVERS, shm_lock_registry(), and shm_unlock_registry().
Referenced by jack_unregister_server().
Member Data Documentation
jack_shm_header
jack_shm_header_t * android::Shm::jack_shm_header = NULL static private
Definition at line 125 of file Shm.h.
Referenced by access_registry(), create_registry(), initialize_shm(), register_server(), server_initialize_shm(), shm_init_registry(), shm_validate_registry(), and unregister_server().
jack_shm_registry
jack_shm_registry_t * android::Shm::jack_shm_registry = NULL static private
Definition at line 126 of file Shm.h.
Referenced by access_registry(), attach_lib_shm(), attach_lib_shm_read(), attach_shm(), attach_shm_read(), cleanup_shm(), create_registry(), destroy_shm(), get_free_shm_info(), jack_release_shm_entry(), release_shm_entry(), release_shm_info(), remove_shm(), resize_shm(), and shm_init_registry().
jack_shm_server_prefix
char android::Shm::jack_shm_server_prefix = "" static private
Definition at line 127 of file Shm.h.
Referenced by register_server(), and set_server_prefix().
jack_shmtype
jack_shmtype_t android::Shm::jack_shmtype = shm_ANDROID static private
Definition at line 121 of file Shm.h.
Referenced by shm_init_registry(), and shm_validate_registry().
mShmMemBase
sp< IMemoryHeap > android::Shm::mShmMemBase = {0,} static private
Definition at line 137 of file Shm.h.
Referenced by shm_addr().
mutex
pthread_mutex_t android::Shm::mutex = PTHREAD_MUTEX_INITIALIZER static private
Definition at line 129 of file Shm.h.
Referenced by jack_shm_lock_registry(), jack_shm_unlock_registry(), shm_lock_registry(), and shm_unlock_registry().
ref
Shm * android::Shm::ref = NULL static private
Definition at line 130 of file Shm.h.
Referenced by Instantiate().
registry_fd
jack_shm_fd_t android::Shm::registry_fd = JACK_SHM_REGISTRY_FD static private
Definition at line 123 of file Shm.h.
Referenced by access_registry(), create_registry(), and remove_shm().
registry_id
jack_shm_id_t android::Shm::registry_id static private
Definition at line 122 of file Shm.h.
Referenced by access_registry(), create_registry(), and server_initialize_shm().
registry_info
jack_shm_info_t android::Shm::registry_info static private
Initial value:
= {
      JACK_SHM_NULL_INDEX, 0, 0, { MAP_FAILED }
    }
Definition at line 124 of file Shm.h.
Referenced by initialize_shm(), and server_initialize_shm().
semid
int android::Shm::semid = -1 static private
Definition at line 128 of file Shm.h.
The documentation for this class was generated from the following files:
src/3rdparty/jack2/android/Shm.h
src/3rdparty/jack2/android/Shm.cpp