LMMS: lmms::RemotePluginClient Class Reference
lmms::RemotePluginClient Class Reference abstract
#include <RemotePluginClient.h>
Public Member Functions
RemotePluginClient (const char *socketPath)
~RemotePluginClient () override
fpp_t bufferSize () const
void debugMessage (const std::string &_s)
const VstSyncData * getVstSyncData ()
virtual int inputCount () const
virtual int outputCount () const
virtual void process (const SampleFrame *_in_buf, SampleFrame *_out_buf)=0
bool processMessage (const message &_m) override
virtual void processMidiEvent (const MidiEvent &, const f_cnt_t)
sample_rate_t sampleRate () const
void setInputCount (int _i)
void setInputOutputCount (int i, int o)
void setOutputCount (int _i)
virtual void updateBufferSize ()
virtual void updateSampleRate ()
Public Member Functions inherited from lmms::RemotePluginBase
RemotePluginBase (shmFifo *_in, shmFifo *_out)
virtual ~RemotePluginBase ()
void fetchAndProcessAllMessages ()
message fetchAndProcessNextMessage ()
bool isInvalid () const
bool messagesLeft ()
message receiveMessage ()
void reset (shmFifo *in, shmFifo *out)
int sendMessage (const message &_m)
message waitForMessage (const message &_m, bool _busy_waiting=false)
Private Member Functions
void doProcessing ()
void setShmKey (const std::string &key)
Private Attributes
SharedMemory< float[]> m_audioBuffer
fpp_t m_bufferSize
int m_inputCount
int m_outputCount
sample_rate_t m_sampleRate
SharedMemory< const VstSyncData > m_vstSyncData
Additional Inherited Members
Static Public Member Functions inherited from lmms::RemotePluginBase
static bool isMainThreadWaiting ()
Protected Member Functions inherited from lmms::RemotePluginBase
const shmFifo * in () const
void invalidate ()
const shmFifo * out () const
Detailed Description
Definition at line 51 of file RemotePluginClient.h.
Constructor & Destructor Documentation
RemotePluginClient()
lmms::RemotePluginClient::RemotePluginClient (const char * socketPath)
Definition at line 186 of file RemotePluginClient.h.
References lmms::RemotePluginBase::RemotePluginBase(), RemotePluginClient(), m_bufferSize, m_inputCount, m_outputCount, and m_sampleRate.
Referenced by RemotePluginClient().
~RemotePluginClient()
lmms::RemotePluginClient::~RemotePluginClient () override
Definition at line 222 of file RemotePluginClient.h.
References ~RemotePluginClient(), lmms::IdQuit, and lmms::RemotePluginBase::sendMessage().
Referenced by ~RemotePluginClient().
Member Function Documentation
bufferSize()
fpp_t lmms::RemotePluginClient::bufferSize () const inline
Definition at line 85 of file RemotePluginClient.h.
References m_bufferSize.
debugMessage()
void lmms::RemotePluginClient::debugMessage (const std::string & _s) inline
Definition at line 121 of file RemotePluginClient.h.
References lmms::IdDebugMessage, and lmms::RemotePluginBase::sendMessage().
Referenced by doProcessing(), processMessage(), and setShmKey().
doProcessing()
void lmms::RemotePluginClient::doProcessing () private
Definition at line 345 of file RemotePluginClient.h.
References debugMessage(), doProcessing(), m_audioBuffer, m_bufferSize, m_inputCount, and process().
Referenced by doProcessing(), and processMessage().
getVstSyncData()
const VstSyncData * lmms::RemotePluginClient::getVstSyncData ()
Definition at line 237 of file RemotePluginClient.h.
References getVstSyncData(), and m_vstSyncData.
Referenced by getVstSyncData().
inputCount()
virtual int lmms::RemotePluginClient::inputCount () const inline virtual
Definition at line 111 of file RemotePluginClient.h.
References m_inputCount.
outputCount()
virtual int lmms::RemotePluginClient::outputCount () const inline virtual
Definition at line 116 of file RemotePluginClient.h.
References m_outputCount.
process()
virtual void lmms::RemotePluginClient::process (const SampleFrame * _in_buf, SampleFrame * _out_buf) pure virtual
Referenced by doProcessing().
processMessage()
bool lmms::RemotePluginClient::processMessage (const message & _m) override virtual
Implements lmms::RemotePluginBase.
Definition at line 245 of file RemotePluginClient.h.
References debugMessage(), doProcessing(), lmms::RemotePluginBase::message::getInt(), lmms::RemotePluginBase::message::getString(), lmms::RemotePluginBase::message::id, lmms::IdBufferSizeInformation, lmms::IdChangeSharedMemoryKey, lmms::IdHostInfoGotten, lmms::IdInformationUpdated, lmms::IdInitDone, lmms::IdMidiEvent, lmms::IdProcessingDone, lmms::IdQuit, lmms::IdSampleRateInformation, lmms::IdStartProcessing, lmms::IdSyncKey, lmms::IdUndefined, m_bufferSize, m_sampleRate, m_vstSyncData, processMessage(), processMidiEvent(), lmms::RemotePluginBase::sendMessage(), setShmKey(), updateBufferSize(), and updateSampleRate().
Referenced by processMessage().
processMidiEvent()
virtual void lmms::RemotePluginClient::processMidiEvent (const MidiEvent & , const f_cnt_t) inline virtual
Definition at line 68 of file RemotePluginClient.h.
Referenced by processMessage().
sampleRate()
sample_rate_t lmms::RemotePluginClient::sampleRate () const inline
Definition at line 80 of file RemotePluginClient.h.
References m_sampleRate.
setInputCount()
void lmms::RemotePluginClient::setInputCount (int _i) inline
Definition at line 90 of file RemotePluginClient.h.
References lmms::IdChangeInputCount, m_inputCount, and lmms::RemotePluginBase::sendMessage().
setInputOutputCount()
void lmms::RemotePluginClient::setInputOutputCount (int i, int o) inline
Definition at line 102 of file RemotePluginClient.h.
References i, lmms::IdChangeInputOutputCount, m_inputCount, m_outputCount, and lmms::RemotePluginBase::sendMessage().
setOutputCount()
void lmms::RemotePluginClient::setOutputCount (int _i) inline
Definition at line 96 of file RemotePluginClient.h.
References lmms::IdChangeOutputCount, m_outputCount, and lmms::RemotePluginBase::sendMessage().
setShmKey()
void lmms::RemotePluginClient::setShmKey (const std::string & key) private
Definition at line 330 of file RemotePluginClient.h.
References debugMessage(), m_audioBuffer, and setShmKey().
Referenced by processMessage(), and setShmKey().
updateBufferSize()
virtual void lmms::RemotePluginClient::updateBufferSize () inline virtual
Definition at line 76 of file RemotePluginClient.h.
Referenced by processMessage().
updateSampleRate()
virtual void lmms::RemotePluginClient::updateSampleRate () inline virtual
Definition at line 72 of file RemotePluginClient.h.
Referenced by processMessage().
Member Data Documentation
m_audioBuffer
SharedMemory<float[]> lmms::RemotePluginClient::m_audioBuffer private
Definition at line 131 of file RemotePluginClient.h.
Referenced by doProcessing(), and setShmKey().
m_bufferSize
fpp_t lmms::RemotePluginClient::m_bufferSize private
Definition at line 138 of file RemotePluginClient.h.
Referenced by RemotePluginClient(), bufferSize(), doProcessing(), and processMessage().
m_inputCount
int lmms::RemotePluginClient::m_inputCount private
Definition at line 134 of file RemotePluginClient.h.
Referenced by RemotePluginClient(), doProcessing(), inputCount(), setInputCount(), and setInputOutputCount().
m_outputCount
int lmms::RemotePluginClient::m_outputCount private
Definition at line 135 of file RemotePluginClient.h.
Referenced by RemotePluginClient(), outputCount(), setInputOutputCount(), and setOutputCount().
m_sampleRate
sample_rate_t lmms::RemotePluginClient::m_sampleRate private
Definition at line 137 of file RemotePluginClient.h.
Referenced by RemotePluginClient(), processMessage(), and sampleRate().
m_vstSyncData
SharedMemory<const VstSyncData> lmms::RemotePluginClient::m_vstSyncData private
Definition at line 132 of file RemotePluginClient.h.
Referenced by getVstSyncData(), and processMessage().
The documentation for this class was generated from the following file:
include/RemotePluginClient.h