LMMS: lmms::SampleFrame Class Reference
lmms::SampleFrame Class Reference
#include <SampleFrame.h>
Public Member Functions
SampleFrame ()
SampleFrame (sample_t left, sample_t right)
SampleFrame (sample_t value)
SampleFrame abs () const
SampleFrame absMax (const SampleFrame &other)
sample_t average () const
void clamp (sample_t low, sample_t high)
bool containsInf () const
bool containsNaN () const
sample_t * data ()
const sample_t * data () const
sample_t & left ()
const sample_t & left () const
SampleFrame operator* (const SampleFrame &other) const
SampleFrame operator* (float value) const
void operator*= (const SampleFrame &other)
SampleFrame & operator*= (float value)
SampleFrame operator+ (const SampleFrame &other) const
SampleFrame & operator+= (const SampleFrame &other)
sample_t & operator[] (size_t index)
const sample_t & operator[] (size_t index) const
sample_t & right ()
const sample_t & right () const
void setLeft (const sample_t &value)
void setRight (const sample_t &value)
sample_t sumOfSquaredAmplitudes () const
Private Attributes
std::array< sample_t, DEFAULT_CHANNELS > m_samples
Detailed Description
Definition at line 40 of file SampleFrame.h.
Constructor & Destructor Documentation
SampleFrame() [1/3]
lmms::SampleFrame::SampleFrame () inline
Definition at line 43 of file SampleFrame.h.
References SampleFrame().
Referenced by SampleFrame(), SampleFrame(), abs(), absMax(), operator*(), operator*(), operator*=(), operator*=(), operator+(), and operator+=().
SampleFrame() [2/3]
lmms::SampleFrame::SampleFrame (sample_t value) inline explicit
Definition at line 47 of file SampleFrame.h.
References SampleFrame().
SampleFrame() [3/3]
lmms::SampleFrame::SampleFrame (sample_t left, sample_t right) inline
Definition at line 51 of file SampleFrame.h.
References left(), m_samples, and right().
Member Function Documentation
abs()
SampleFrame lmms::SampleFrame::abs () const inline
Definition at line 151 of file SampleFrame.h.
References SampleFrame(), left(), and right().
Referenced by absMax().
absMax()
SampleFrame lmms::SampleFrame::absMax (const SampleFrame & other) inline
Definition at line 156 of file SampleFrame.h.
References SampleFrame(), and abs().
Referenced by lmms::getAbsPeakValues().
average()
sample_t lmms::SampleFrame::average () const inline
Definition at line 164 of file SampleFrame.h.
References left(), and right().
clamp()
void lmms::SampleFrame::clamp (sample_t low, sample_t high) inline
Definition at line 169 of file SampleFrame.h.
References left(), and right().
containsInf()
bool lmms::SampleFrame::containsInf () const inline
Definition at line 178 of file SampleFrame.h.
References left(), and right().
containsNaN()
bool lmms::SampleFrame::containsNaN () const inline
Definition at line 183 of file SampleFrame.h.
References left(), and right().
data() [1/2]
sample_t * lmms::SampleFrame::data () inline
Definition at line 56 of file SampleFrame.h.
References m_samples.
Referenced by lmms::AudioFileFlac::writeBuffer().
data() [2/2]
const sample_t * lmms::SampleFrame::data () const inline
Definition at line 61 of file SampleFrame.h.
References m_samples.
left() [1/2]
sample_t & lmms::SampleFrame::left () inline
Definition at line 66 of file SampleFrame.h.
References m_samples.
Referenced by SampleFrame(), abs(), average(), clamp(), containsInf(), containsNaN(), lmms::copyFromSampleFrames(), lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::nextSample(), operator*(), operator*(), operator*=(), operator*=(), operator+(), operator+=(), lmms::gui::Oscilloscope::paintEvent(), and sumOfSquaredAmplitudes().
left() [2/2]
const sample_t & lmms::SampleFrame::left () const inline
Definition at line 71 of file SampleFrame.h.
References m_samples.
operator*() [1/2]
SampleFrame lmms::SampleFrame::operator* (const SampleFrame & other) const inline
Definition at line 135 of file SampleFrame.h.
References SampleFrame(), left(), and right().
operator*() [2/2]
SampleFrame lmms::SampleFrame::operator* (float value) const inline
Definition at line 122 of file SampleFrame.h.
References SampleFrame(), left(), and right().
operator*=() [1/2]
void lmms::SampleFrame::operator*= (const SampleFrame & other) inline
Definition at line 140 of file SampleFrame.h.
References SampleFrame(), left(), and right().
operator*=() [2/2]
SampleFrame & lmms::SampleFrame::operator*= (float value) inline
Definition at line 127 of file SampleFrame.h.
References SampleFrame(), left(), right(), setLeft(), and setRight().
operator+()
SampleFrame lmms::SampleFrame::operator+ (const SampleFrame & other) const inline
Definition at line 106 of file SampleFrame.h.
References SampleFrame(), left(), and right().
operator+=()
SampleFrame & lmms::SampleFrame::operator+= (const SampleFrame & other) inline
Definition at line 111 of file SampleFrame.h.
References SampleFrame(), left(), and right().
operator[]() [1/2]
sample_t & lmms::SampleFrame::operator[] (size_t index) inline
Definition at line 96 of file SampleFrame.h.
References m_samples.
operator[]() [2/2]
const sample_t & lmms::SampleFrame::operator[] (size_t index) const inline
Definition at line 101 of file SampleFrame.h.
References m_samples.
right() [1/2]
sample_t & lmms::SampleFrame::right () inline
Definition at line 81 of file SampleFrame.h.
References m_samples.
Referenced by SampleFrame(), abs(), average(), clamp(), containsInf(), containsNaN(), lmms::copyFromSampleFrames(), lmms::DspEffectLibrary::MonoToStereoAdaptor< FXL, FXR >::nextSample(), operator*(), operator*(), operator*=(), operator*=(), operator+(), operator+=(), lmms::gui::Oscilloscope::paintEvent(), and sumOfSquaredAmplitudes().
right() [2/2]
const sample_t & lmms::SampleFrame::right () const inline
Definition at line 86 of file SampleFrame.h.
References m_samples.
setLeft()
void lmms::SampleFrame::setLeft (const sample_t & value) inline
Definition at line 76 of file SampleFrame.h.
References m_samples.
Referenced by lmms::copyToSampleFrames(), and operator*=().
setRight()
void lmms::SampleFrame::setRight (const sample_t & value) inline
Definition at line 91 of file SampleFrame.h.
References m_samples.
Referenced by lmms::copyToSampleFrames(), and operator*=().
sumOfSquaredAmplitudes()
sample_t lmms::SampleFrame::sumOfSquaredAmplitudes () const inline
Definition at line 146 of file SampleFrame.h.
References left(), and right().
Member Data Documentation
m_samples
std::array<sample_t, DEFAULT_CHANNELS> lmms::SampleFrame::m_samples private
Definition at line 189 of file SampleFrame.h.
Referenced by SampleFrame(), data(), data(), left(), left(), operator[](), operator[](), right(), right(), setLeft(), and setRight().
The documentation for this class was generated from the following file:
include/SampleFrame.h