LMMS: lmms::gui::EffectSelectDialog Class Reference
lmms::gui::EffectSelectDialog Class Reference
#include <EffectSelectDialog.h>
Public Member Functions
EffectSelectDialog (QWidget *parent)
Effect * instantiateSelectedPlugin (EffectChain *parent)
Protected Slots
void acceptSelection ()
bool eventFilter (QObject *obj, QEvent *event) override
void rowChanged (const QModelIndex &, const QModelIndex &)
void updateSelection ()
Private Attributes
EffectKey m_currentSelection
QWidget * m_descriptionWidget
EffectKeyList m_effectKeys
QLineEdit * m_filterEdit
DualColumnFilterProxyModel m_model
QTableView * m_pluginList
QScrollArea * m_scrollArea
QStandardItemModel m_sourceModel
Detailed Description
Definition at line 89 of file EffectSelectDialog.h.
Constructor & Destructor Documentation
EffectSelectDialog()
lmms::gui::EffectSelectDialog::EffectSelectDialog (QWidget * parent)
Definition at line 50 of file EffectSelectDialog.cpp.
References acceptSelection(), lmms::Plugin::Effect, lmms::embed::getIconPixmap(), lmms::getPluginFactory(), i, m_currentSelection, m_descriptionWidget, m_effectKeys, m_filterEdit, m_model, m_pluginList, m_scrollArea, m_sourceModel, rowChanged(), and updateSelection().
Member Function Documentation
acceptSelection
void lmms::gui::EffectSelectDialog::acceptSelection () protected slot
Definition at line 215 of file EffectSelectDialog.cpp.
References m_currentSelection.
Referenced by EffectSelectDialog().
eventFilter
bool lmms::gui::EffectSelectDialog::eventFilter (QObject * obj, QEvent * event) override protected slot
Definition at line 313 of file EffectSelectDialog.cpp.
References m_pluginList.
instantiateSelectedPlugin()
Effect * lmms::gui::EffectSelectDialog::instantiateSelectedPlugin (EffectChain * parent)
Definition at line 201 of file EffectSelectDialog.cpp.
References lmms::Effect::instantiate(), and m_currentSelection.
Referenced by lmms::gui::EffectRackView::addEffect().
rowChanged
void lmms::gui::EffectSelectDialog::rowChanged (const QModelIndex & idx, const QModelIndex &) protected slot
Definition at line 223 of file EffectSelectDialog.cpp.
References lmms::Plugin::Descriptor::author, lmms::Plugin::Descriptor::description, lmms::Plugin::Descriptor::displayName, m_currentSelection, m_descriptionWidget, m_effectKeys, m_model, m_scrollArea, and lmms::PixmapLoader::pixmap().
Referenced by EffectSelectDialog(), and updateSelection().
updateSelection
void lmms::gui::EffectSelectDialog::updateSelection () protected slot
Definition at line 301 of file EffectSelectDialog.cpp.
References m_model, m_pluginList, and rowChanged().
Referenced by EffectSelectDialog().
Member Data Documentation
m_currentSelection
EffectKey lmms::gui::EffectSelectDialog::m_currentSelection private
Definition at line 106 of file EffectSelectDialog.h.
Referenced by EffectSelectDialog(), acceptSelection(), instantiateSelectedPlugin(), and rowChanged().
m_descriptionWidget
QWidget* lmms::gui::EffectSelectDialog::m_descriptionWidget private
Definition at line 110 of file EffectSelectDialog.h.
Referenced by EffectSelectDialog(), and rowChanged().
m_effectKeys
EffectKeyList lmms::gui::EffectSelectDialog::m_effectKeys private
Definition at line 105 of file EffectSelectDialog.h.
Referenced by EffectSelectDialog(), and rowChanged().
m_filterEdit
QLineEdit* lmms::gui::EffectSelectDialog::m_filterEdit private
Definition at line 113 of file EffectSelectDialog.h.
Referenced by EffectSelectDialog().
m_model
DualColumnFilterProxyModel lmms::gui::EffectSelectDialog::m_model private
Definition at line 109 of file EffectSelectDialog.h.
Referenced by EffectSelectDialog(), rowChanged(), and updateSelection().
m_pluginList
QTableView* lmms::gui::EffectSelectDialog::m_pluginList private
Definition at line 111 of file EffectSelectDialog.h.
Referenced by EffectSelectDialog(), eventFilter(), and updateSelection().
m_scrollArea
QScrollArea* lmms::gui::EffectSelectDialog::m_scrollArea private
Definition at line 112 of file EffectSelectDialog.h.
Referenced by EffectSelectDialog(), and rowChanged().
m_sourceModel
QStandardItemModel lmms::gui::EffectSelectDialog::m_sourceModel private
Definition at line 108 of file EffectSelectDialog.h.
Referenced by EffectSelectDialog().
The documentation for this class was generated from the following files:
include/EffectSelectDialog.h
src/gui/modals/EffectSelectDialog.cpp