LMMS: lmms::ModelVisitor Class Reference
lmms::ModelVisitor Class Reference
#include <ModelVisitor.h>
Public Member Functions
virtual ~ModelVisitor ()=default
virtual void visit (AutomatableModel &)
virtual void visit (BoolModel &m)
virtual void visit (ComboBoxModel &m)
virtual void visit (FloatModel &m)
virtual void visit (IntModel &m)
virtual void visit (TempoSyncKnobModel &m)
Private Member Functions
template<class ParentType = AutomatableModel, class ModelType>
void up (ModelType &m)
Detailed Description
Definition at line 39 of file ModelVisitor.h.
Constructor & Destructor Documentation
~ModelVisitor()
virtual lmms::ModelVisitor::~ModelVisitor () virtual default
Member Function Documentation
up()
template<class ParentType = AutomatableModel, class ModelType> void lmms::ModelVisitor::up (ModelType & m) inline private
Definition at line 42 of file ModelVisitor.h.
References visit().
Referenced by visit(), visit(), visit(), visit(), and visit().
visit() [1/6]
virtual void lmms::ModelVisitor::visit (AutomatableModel &) inline virtual
Definition at line 44 of file ModelVisitor.h.
Referenced by up().
visit() [2/6]
void lmms::ModelVisitor::visit (BoolModel & m) virtual
Definition at line 35 of file ModelVisitor.cpp.
References up().
visit() [3/6]
void lmms::ModelVisitor::visit (ComboBoxModel & m) virtual
Definition at line 38 of file ModelVisitor.cpp.
References up().
visit() [4/6]
void lmms::ModelVisitor::visit (FloatModel & m) virtual
Definition at line 37 of file ModelVisitor.cpp.
References up().
visit() [5/6]
void lmms::ModelVisitor::visit (IntModel & m) virtual
Definition at line 36 of file ModelVisitor.cpp.
References up().
visit() [6/6]
void lmms::ModelVisitor::visit (TempoSyncKnobModel & m) virtual
Definition at line 39 of file ModelVisitor.cpp.
References up().
The documentation for this class was generated from the following files:
include/ModelVisitor.h
src/core/ModelVisitor.cpp