LMMS: Jack::JackAudioDriver Class Reference
Jack::JackAudioDriver Class Reference
The base class for audio drivers: drivers with audio ports.
#include <JackAudioDriver.h>
Public Member Functions
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int Attach ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Detach ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetSampleRate (jack_nframes_t sample_rate)
virtual int Write ()
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual int Close ()
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsFixedBufferSize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
virtual int Read ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
virtual int Start ()
virtual int Stop ()
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Protected Member Functions
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
virtual void UpdateLatencies ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Additional Inherited Members
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The base class for audio drivers: drivers with audio ports.
A concrete derived class will have to be defined with a real audio driver API, either callback based one (like CoreAudio, PortAudio..) ones or blocking ones (like ALSA).
Most of the generic audio handing code is part of this class :
concrete callback basedd derived subclasses typically have to Open/Close the underlying audio API, setup the audio callback and implement the Read/Write methods
concrete blocking based derived subclasses typically have to Open/Close the underlying audio API, implement the Read/Write methods and "wraps" the driver with the JackThreadDriver class.
Definition at line 42 of file JackAudioDriver.h.
Constructor & Destructor Documentation
JackAudioDriver()
Jack::JackAudioDriver::JackAudioDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table)
Definition at line 37 of file JackAudioDriver.cpp.
References Jack::JackDriver::JackDriver().
Referenced by Jack::JackAlsaDriver::JackAlsaDriver(), Jack::JackBoomerDriver::JackBoomerDriver(), Jack::JackFFADODriver::JackFFADODriver(), Jack::JackGoldfishDriver::JackGoldfishDriver(), Jack::JackIIODriver::JackIIODriver(), Jack::JackLoopbackDriver::JackLoopbackDriver(), Jack::JackOpenSLESDriver::JackOpenSLESDriver(), Jack::JackOSSDriver::JackOSSDriver(), Jack::JackPortAudioDriver::JackPortAudioDriver(), and Jack::JackTimedDriver::JackTimedDriver().
~JackAudioDriver()
Jack::JackAudioDriver::~JackAudioDriver () virtual
Definition at line 41 of file JackAudioDriver.cpp.
Member Function Documentation
Attach()
int Jack::JackAudioDriver::Attach () virtual
Reimplemented from Jack::JackDriver.
Reimplemented in Jack::JackAlsaDriver, Jack::JackCoreAudioDriver, Jack::JackFFADODriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackPortAudioDriver, Jack::JackProxyDriver, and JackAlsaDriver.
Definition at line 114 of file JackAudioDriver.cpp.
References CaptureDriverFlags, Jack::JackDriver::fAliasName, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCaptureDriverName, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fClientControl, Jack::JackDriver::fEngine, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackDriverName, Jack::JackDriver::fPlaybackPortList, Jack::JackDriver::fWithMonitorPorts, i, JACK_DEFAULT_AUDIO_TYPE, jack_error, jack_log(), JackPortIsOutput, PlaybackDriverFlags, REAL_JACK_PORT_NAME_SIZE, Jack::JackPort::SetAlias(), and UpdateLatencies().
Referenced by Jack::JackProxyDriver::AllocPorts(), and Jack::JackPortAudioDriver::Attach().
ClientNotify()
int Jack::JackAudioDriver::ClientNotify (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value2) virtual
Reimplemented from Jack::JackDriver.
Definition at line 379 of file JackAudioDriver.cpp.
References Jack::JackDriver::ClientNotify(), HandleLatencyCallback(), and Jack::kLatencyCallback.
Detach()
int Jack::JackAudioDriver::Detach () virtual
Reimplemented from Jack::JackDriver.
Reimplemented in Jack::JackAlsaDriver, Jack::JackFFADODriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackProxyDriver, and JackAlsaDriver.
Definition at line 166 of file JackAudioDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fClientControl, Jack::JackDriver::fEngine, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, Jack::JackDriver::fWithMonitorPorts, i, and jack_log().
Referenced by Jack::JackAlsaDriver::Detach(), and Jack::JackFFADODriver::Detach().
GetInputBuffer()
jack_default_audio_sample_t * Jack::JackAudioDriver::GetInputBuffer (int port_index) protected
Definition at line 358 of file JackAudioDriver.cpp.
References Jack::JackDriver::fCapturePortList, Jack::JackDriver::fEngineControl, and Jack::JackDriver::fGraphManager.
Referenced by Jack::JackLoopbackDriver::ProcessReadAsync(), Jack::JackLoopbackDriver::ProcessReadSync(), Jack::JackGoldfishDriver::Read(), Jack::JackIIODriver::Read(), Jack::JackNetDriver::Read(), Jack::JackOpenSLESDriver::Read(), Jack::JackOSSDriver::Read(), Jack::JackPortAudioDriver::Read(), and Jack::JackProxyDriver::Read().
GetMonitorBuffer()
jack_default_audio_sample_t * Jack::JackAudioDriver::GetMonitorBuffer (int port_index) protected
Definition at line 372 of file JackAudioDriver.cpp.
References Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, and Jack::JackDriver::fMonitorPortList.
Referenced by Write().
GetOutputBuffer()
jack_default_audio_sample_t * Jack::JackAudioDriver::GetOutputBuffer (int port_index) protected
Definition at line 365 of file JackAudioDriver.cpp.
References Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, and Jack::JackDriver::fPlaybackPortList.
Referenced by Jack::JackLoopbackDriver::ProcessReadAsync(), Jack::JackLoopbackDriver::ProcessReadSync(), Write(), Jack::JackGoldfishDriver::Write(), Jack::JackNetDriver::Write(), Jack::JackOpenSLESDriver::Write(), Jack::JackOSSDriver::Write(), Jack::JackPortAudioDriver::Write(), and Jack::JackProxyDriver::Write().
HandleLatencyCallback()
void Jack::JackAudioDriver::HandleLatencyCallback (int status) protected
Definition at line 395 of file JackAudioDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fGraphManager, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, i, JackCaptureLatency, and JackPlaybackLatency.
Referenced by ClientNotify().
Open()
int Jack::JackAudioDriver::Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency) virtual
Reimplemented from Jack::JackDriver.
Reimplemented in Jack::JackGoldfishDriver, Jack::JackIIODriver, Jack::JackNetDriver, Jack::JackOpenSLESDriver, Jack::JackPortAudioDriver, and Jack::JackProxyDriver.
Definition at line 66 of file JackAudioDriver.cpp.
References capture_latency, DRIVER_PORT_NUM, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, Jack::JackDriver::fWithMonitorPorts, Jack::JackDriver::Open(), and playback_latency.
Referenced by Jack::JackAlsaDriver::Open(), Jack::JackBoomerDriver::Open(), Jack::JackFFADODriver::Open(), Jack::JackGoldfishDriver::Open(), Jack::JackOpenSLESDriver::Open(), Jack::JackOSSDriver::Open(), and Jack::JackPortAudioDriver::Open().
Process()
int Jack::JackAudioDriver::Process () virtual
Reimplemented from Jack::JackDriver.
Reimplemented in Jack::JackDummyDriver.
Definition at line 200 of file JackAudioDriver.cpp.
References Jack::JackDriver::fEngineControl, ProcessAsync(), and ProcessSync().
Referenced by Jack::JackDummyDriver::Process(), Jack::JackProxyDriver::process_callback(), Jack::JackPortAudioDriver::Render(), and Jack::JackBoomerDriver::SynchronizeRead().
ProcessAsync()
int Jack::JackAudioDriver::ProcessAsync () protected
Definition at line 210 of file JackAudioDriver.cpp.
References Jack::JackDriver::CycleTakeEndTime(), jack_error, ProcessGraphAsync(), Jack::JackDriver::Read(), and Write().
Referenced by Process().
ProcessGraphAsync()
void Jack::JackAudioDriver::ProcessGraphAsync () protected
Definition at line 232 of file JackAudioDriver.cpp.
References Jack::JackDriver::fIsMaster, ProcessGraphAsyncMaster(), and ProcessGraphAsyncSlave().
Referenced by ProcessAsync(), and Jack::JackWaiterDriver::ProcessNull().
ProcessGraphAsyncMaster()
void Jack::JackAudioDriver::ProcessGraphAsyncMaster () protected
Definition at line 246 of file JackAudioDriver.cpp.
References Jack::JackDriver::fBeginDateUst, Jack::JackDriver::fEndDateUst, Jack::JackDriver::fEngine, jack_error, Jack::JackDriver::ProcessReadSlaves(), Jack::JackDriver::ProcessWriteSlaves(), and Jack::JackDriver::ResumeRefNum().
Referenced by ProcessGraphAsync().
ProcessGraphAsyncSlave()
void Jack::JackAudioDriver::ProcessGraphAsyncSlave () protected
Definition at line 272 of file JackAudioDriver.cpp.
References jack_error, and Jack::JackDriver::ResumeRefNum().
Referenced by ProcessGraphAsync().
ProcessGraphSync()
void Jack::JackAudioDriver::ProcessGraphSync () protected
Definition at line 306 of file JackAudioDriver.cpp.
References Jack::JackDriver::fIsMaster, ProcessGraphSyncMaster(), and ProcessGraphSyncSlave().
Referenced by Jack::JackWaiterDriver::ProcessNull(), ProcessSync(), and Jack::JackOSSDriver::ProcessSync().
ProcessGraphSyncMaster()
void Jack::JackAudioDriver::ProcessGraphSyncMaster () protected
Definition at line 320 of file JackAudioDriver.cpp.
References Jack::JackDriver::fBeginDateUst, Jack::JackDriver::fEndDateUst, Jack::JackDriver::fEngine, jack_error, Jack::JackDriver::ProcessReadSlaves(), Jack::JackDriver::ProcessWriteSlaves(), Jack::JackDriver::ResumeRefNum(), and Jack::JackDriver::SuspendRefNum().
Referenced by ProcessGraphSync().
ProcessGraphSyncSlave()
void Jack::JackAudioDriver::ProcessGraphSyncSlave () protected
Definition at line 351 of file JackAudioDriver.cpp.
References jack_error, and Jack::JackDriver::ResumeRefNum().
Referenced by ProcessGraphSync().
ProcessSync()
int Jack::JackAudioDriver::ProcessSync () protected
Definition at line 284 of file JackAudioDriver.cpp.
References Jack::JackDriver::CycleTakeEndTime(), jack_error, ProcessGraphSync(), Jack::JackDriver::Read(), and Write().
Referenced by Process().
SetBufferSize()
int Jack::JackAudioDriver::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackDriver.
Reimplemented in Jack::JackAlsaDriver, Jack::JackBoomerDriver, Jack::JackCoreAudioDriver, Jack::JackFFADODriver, Jack::JackGoldfishDriver, Jack::JackIIODriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackOpenSLESDriver, Jack::JackOSSDriver, Jack::JackOSSDriver, Jack::JackPortAudioDriver, and JackAlsaDriver.
Definition at line 44 of file JackAudioDriver.cpp.
References Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::SetBufferSize(), and UpdateLatencies().
Referenced by Jack::JackAlsaDriver::Attach(), Jack::JackProxyDriver::bufsize_callback(), Jack::JackNetDriver::Initialize(), Jack::JackNetOneDriver::Initialize(), Jack::JackAlsaDriver::SetBufferSize(), Jack::JackBoomerDriver::SetBufferSize(), Jack::JackFFADODriver::SetBufferSize(), Jack::JackGoldfishDriver::SetBufferSize(), Jack::JackIIODriver::SetBufferSize(), Jack::JackOpenSLESDriver::SetBufferSize(), Jack::JackOSSDriver::SetBufferSize(), and Jack::JackPortAudioDriver::SetBufferSize().
SetSampleRate()
int Jack::JackAudioDriver::SetSampleRate (jack_nframes_t sample_rate) virtual
Reimplemented from Jack::JackDriver.
Reimplemented in Jack::JackNetDriver, and Jack::JackNetOneDriver.
Definition at line 57 of file JackAudioDriver.cpp.
References Jack::JackDriver::fEngineControl, and Jack::JackDriver::SetSampleRate().
Referenced by Jack::JackAlsaDriver::Attach(), Jack::JackNetDriver::Initialize(), Jack::JackNetOneDriver::Initialize(), and Jack::JackProxyDriver::srate_callback().
UpdateLatencies()
void Jack::JackAudioDriver::UpdateLatencies (void) protected virtual
Reimplemented in Jack::JackAlsaDriver, Jack::JackCoreAudioDriver, Jack::JackFFADODriver, Jack::JackNetDriver, Jack::JackOSSDriver, Jack::JackPortAudioDriver, and JackAlsaDriver.
Definition at line 88 of file JackAudioDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCaptureLatency, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackLatency, Jack::JackDriver::fPlaybackPortList, Jack::JackDriver::fWithMonitorPorts, i, JackCaptureLatency, JackPlaybackLatency, _jack_latency_range::max, and _jack_latency_range::min.
Referenced by Attach(), and SetBufferSize().
Write()
int Jack::JackAudioDriver::Write () virtual
Reimplemented from Jack::JackDriver.
Reimplemented in Jack::JackAlsaDriver, Jack::JackCoreAudioDriver, Jack::JackFFADODriver, Jack::JackGoldfishDriver, Jack::JackIIODriver, Jack::JackNetDriver, Jack::JackNetOneDriver, Jack::JackOpenSLESDriver, Jack::JackOSSDriver, Jack::JackOSSDriver, Jack::JackPortAudioDriver, Jack::JackProxyDriver, and JackAlsaDriver.
Definition at line 185 of file JackAudioDriver.cpp.
References Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, Jack::JackDriver::fWithMonitorPorts, GetMonitorBuffer(), GetOutputBuffer(), and i.
Referenced by ProcessAsync(), and ProcessSync().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackAudioDriver.h
src/3rdparty/jack2/common/JackAudioDriver.cpp