LMMS: src/3rdparty/jack2/android/JackAndroidThread.cpp File Reference
JackAndroidThread.cpp File Reference
#include "JackAndroidThread.h"
#include "JackError.h"
#include "JackTime.h"
#include "JackGlobals.h"
#include <string.h>
#include <unistd.h>
#include <signal.h>
Namespaces
namespace Jack
Macros
#define JACK_SCHED_POLICY SCHED_FIFO
Functions
bool jack_get_thread_realtime_priority_range (int *min_ptr, int *max_ptr)
bool jack_tls_allocate_key (jack_tls_key *key_ptr)
bool jack_tls_free_key (jack_tls_key key)
void * jack_tls_get (jack_tls_key key)
bool jack_tls_set (jack_tls_key key, void *data_ptr)
SERVER_EXPORT void Jack::ThreadExit ()
Macro Definition Documentation
JACK_SCHED_POLICY
#define JACK_SCHED_POLICY SCHED_FIFO
Definition at line 35 of file JackAndroidThread.cpp.
Referenced by Jack::JackAndroidThread::AcquireRealTimeImp(), Jack::JackPosixThread::AcquireRealTimeImp(), jack_get_thread_realtime_priority_range(), Jack::JackAndroidThread::StartImp(), and Jack::JackPosixThread::StartImp().
Function Documentation
jack_get_thread_realtime_priority_range()
bool jack_get_thread_realtime_priority_range (int * min_ptr, int * max_ptr)
Definition at line 313 of file JackAndroidThread.cpp.
References jack_error, JACK_SCHED_POLICY, max, and min.
Referenced by get_realtime_priority_constraint().
jack_tls_allocate_key()
bool jack_tls_allocate_key (jack_tls_key * key_ptr)
Definition at line 341 of file JackAndroidThread.cpp.
References jack_error.
jack_tls_free_key()
bool jack_tls_free_key (jack_tls_key key)
Definition at line 355 of file JackAndroidThread.cpp.
References jack_error.
jack_tls_get()
void * jack_tls_get (jack_tls_key key)
Definition at line 383 of file JackAndroidThread.cpp.
Referenced by change_thread_log_function(), jack_format_and_log(), Jack::JackGenericClientChannel::ServerAsyncCall(), Jack::JackGenericClientChannel::ServerSyncCall(), and WaitGraphChange().
jack_tls_set()
bool jack_tls_set (jack_tls_key key, void * data_ptr)
Definition at line 369 of file JackAndroidThread.cpp.
References jack_error.
Referenced by change_thread_log_function(), Jack::JackClient::Init(), Jack::JackSocketClientChannel::Init(), and Jack::JackWinNamedPipeClientChannel::Init().