LMMS: lmms::ProjectJournal Class Reference
lmms::ProjectJournal Class Reference
#include <ProjectJournal.h>
Classes
struct CheckPoint
Public Member Functions
ProjectJournal ()
virtual ~ProjectJournal ()=default
void addJournalCheckPoint (JournallingObject *jo)
jo_id_t allocID (JournallingObject *_obj)
bool canRedo () const
bool canUndo () const
void clearJournal ()
void freeID (const jo_id_t _id)
bool isJournalling () const
JournallingObject * journallingObject (const jo_id_t _id)
void reallocID (const jo_id_t _id, JournallingObject *_obj)
void redo ()
void setJournalling (const bool _on)
void stopAllJournalling ()
void undo ()
Static Public Member Functions
static jo_id_t idFromSave (jo_id_t id)
hack, not used when loading a savefile
static jo_id_t idToSave (jo_id_t id)
hack, not used when saving a file
Static Public Attributes
static const int MAX_UNDO_STATES = 100
Private Types
using CheckPointStack = QStack<CheckPoint>
using JoIdMap = QHash<jo_id_t, JournallingObject*>
Private Attributes
JoIdMap m_joIDs
bool m_journalling
CheckPointStack m_redoCheckPoints
CheckPointStack m_undoCheckPoints
Detailed Description
Warning
many parts of this class may be rewritten soon
Definition at line 43 of file ProjectJournal.h.
Member Typedef Documentation
CheckPointStack
using lmms::ProjectJournal::CheckPointStack = QStack<CheckPoint> private
Definition at line 115 of file ProjectJournal.h.
JoIdMap
using lmms::ProjectJournal::JoIdMap = QHash<jo_id_t, JournallingObject*> private
Definition at line 103 of file ProjectJournal.h.
Constructor & Destructor Documentation
ProjectJournal()
lmms::ProjectJournal::ProjectJournal ()
Definition at line 43 of file ProjectJournal.cpp.
References m_joIDs, m_journalling, m_redoCheckPoints, and m_undoCheckPoints.
~ProjectJournal()
virtual lmms::ProjectJournal::~ProjectJournal () virtual default
Member Function Documentation
addJournalCheckPoint()
void lmms::ProjectJournal::addJournalCheckPoint (JournallingObject * jo)
Definition at line 120 of file ProjectJournal.cpp.
References lmms::DataFile::content(), lmms::JournallingObject::id(), isJournalling(), lmms::DataFile::JournalData, m_redoCheckPoints, m_undoCheckPoints, MAX_UNDO_STATES, and lmms::JournallingObject::saveState().
Referenced by lmms::JournallingObject::addJournalCheckPoint().
allocID()
jo_id_t lmms::ProjectJournal::allocID (JournallingObject * _obj)
Definition at line 140 of file ProjectJournal.cpp.
References lmms::EO_ID_MSB, and m_joIDs.
canRedo()
bool lmms::ProjectJournal::canRedo () const
Definition at line 113 of file ProjectJournal.cpp.
References m_redoCheckPoints.
canUndo()
bool lmms::ProjectJournal::canUndo () const
Definition at line 108 of file ProjectJournal.cpp.
References m_undoCheckPoints.
clearJournal()
void lmms::ProjectJournal::clearJournal ()
Definition at line 181 of file ProjectJournal.cpp.
References m_joIDs, m_redoCheckPoints, and m_undoCheckPoints.
Referenced by lmms::Song::clearProject().
freeID()
void lmms::ProjectJournal::freeID (const jo_id_t _id) inline
Definition at line 80 of file ProjectJournal.h.
References reallocID().
Referenced by lmms::JournallingObject::~JournallingObject(), and lmms::JournallingObject::changeID().
idFromSave()
jo_id_t lmms::ProjectJournal::idFromSave (jo_id_t id) static
hack, not used when loading a savefile
Definition at line 173 of file ProjectJournal.cpp.
References lmms::EO_ID_MSB.
Referenced by lmms::AutomationClip::resolveAllIDs().
idToSave()
jo_id_t lmms::ProjectJournal::idToSave (jo_id_t id) static
hack, not used when saving a file
Definition at line 168 of file ProjectJournal.cpp.
References lmms::EO_ID_MSB.
Referenced by lmms::AutomationClip::resolveAllIDs(), lmms::AutomatableModel::saveSettings(), and lmms::AutomationClip::saveSettings().
isJournalling()
bool lmms::ProjectJournal::isJournalling () const inline
Definition at line 59 of file ProjectJournal.h.
References m_journalling.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), addJournalCheckPoint(), lmms::ImportFilter::import(), redo(), and undo().
journallingObject()
JournallingObject * lmms::ProjectJournal::journallingObject (const jo_id_t _id) inline
Definition at line 92 of file ProjectJournal.h.
References m_joIDs.
Referenced by lmms::gui::AutomationClipView::dropEvent(), lmms::gui::AutomationEditorWindow::dropEvent(), lmms::gui::AutomationTrackView::dropEvent(), lmms::gui::FloatModelEditorBase::dropEvent(), and lmms::AutomationClip::resolveAllIDs().
reallocID()
void lmms::ProjectJournal::reallocID (const jo_id_t _id, JournallingObject * _obj)
Definition at line 156 of file ProjectJournal.cpp.
References m_joIDs.
Referenced by lmms::JournallingObject::changeID(), and freeID().
redo()
void lmms::ProjectJournal::redo ()
Definition at line 85 of file ProjectJournal.cpp.
References lmms::DataFile::content(), lmms::ProjectJournal::CheckPoint::data, lmms::Engine::getSong(), isJournalling(), lmms::ProjectJournal::CheckPoint::joID, lmms::DataFile::JournalData, m_joIDs, m_redoCheckPoints, m_undoCheckPoints, lmms::JournallingObject::restoreState(), lmms::JournallingObject::saveState(), setJournalling(), and lmms::Song::setModified().
Referenced by lmms::gui::MainWindow::redo().
setJournalling()
void lmms::ProjectJournal::setJournalling (const bool _on) inline
Definition at line 64 of file ProjectJournal.h.
References m_journalling.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::gui::SetupDialog::SetupDialog(), lmms::gui::SetupDialog::~SetupDialog(), lmms::Song::clearProject(), lmms::Song::createNewProject(), lmms::ImportFilter::import(), lmms::Song::loadProject(), redo(), stopAllJournalling(), and undo().
stopAllJournalling()
void lmms::ProjectJournal::stopAllJournalling ()
Definition at line 199 of file ProjectJournal.cpp.
References m_joIDs, and setJournalling().
undo()
void lmms::ProjectJournal::undo ()
Definition at line 54 of file ProjectJournal.cpp.
References lmms::DataFile::content(), lmms::ProjectJournal::CheckPoint::data, lmms::Engine::getSong(), isJournalling(), lmms::ProjectJournal::CheckPoint::joID, lmms::DataFile::JournalData, m_joIDs, m_redoCheckPoints, m_undoCheckPoints, lmms::AutomationClip::resolveAllIDs(), lmms::JournallingObject::restoreState(), lmms::JournallingObject::saveState(), setJournalling(), and lmms::Song::setModified().
Referenced by lmms::gui::MainWindow::undo().
Member Data Documentation
m_joIDs
JoIdMap lmms::ProjectJournal::m_joIDs private
Definition at line 117 of file ProjectJournal.h.
Referenced by ProjectJournal(), allocID(), clearJournal(), journallingObject(), reallocID(), redo(), stopAllJournalling(), and undo().
m_journalling
bool lmms::ProjectJournal::m_journalling private
Definition at line 122 of file ProjectJournal.h.
Referenced by ProjectJournal(), isJournalling(), and setJournalling().
m_redoCheckPoints
CheckPointStack lmms::ProjectJournal::m_redoCheckPoints private
Definition at line 120 of file ProjectJournal.h.
Referenced by ProjectJournal(), addJournalCheckPoint(), canRedo(), clearJournal(), redo(), and undo().
m_undoCheckPoints
CheckPointStack lmms::ProjectJournal::m_undoCheckPoints private
Definition at line 119 of file ProjectJournal.h.
Referenced by ProjectJournal(), addJournalCheckPoint(), canUndo(), clearJournal(), redo(), and undo().
MAX_UNDO_STATES
const int lmms::ProjectJournal::MAX_UNDO_STATES = 100 static
Definition at line 46 of file ProjectJournal.h.
Referenced by addJournalCheckPoint().
The documentation for this class was generated from the following files:
include/ProjectJournal.h
src/core/ProjectJournal.cpp