LMMS: Jack::JackPortRegisterResult Struct Reference
Jack::JackPortRegisterResult Struct Reference
PortRegister result.
#include <JackRequest.h>
Public Member Functions
JackPortRegisterResult ()
int Read (detail::JackChannelTransactionInterface *trans)
int Write (detail::JackChannelTransactionInterface *trans)
Public Member Functions inherited from Jack::JackResult
JackResult ()
JackResult (int result)
virtual ~JackResult ()
Public Attributes
jack_port_id_t fPortIndex
Public Attributes inherited from Jack::JackResult
int fResult
Detailed Description
PortRegister result.
Definition at line 484 of file JackRequest.h.
Constructor & Destructor Documentation
JackPortRegisterResult()
Jack::JackPortRegisterResult::JackPortRegisterResult () inline
Definition at line 489 of file JackRequest.h.
References Jack::JackResult::JackResult(), fPortIndex, and NO_PORT.
Member Function Documentation
Read()
int Jack::JackPortRegisterResult::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 492 of file JackRequest.h.
References CheckRes, fPortIndex, Jack::detail::JackChannelTransactionInterface::Read(), and Jack::JackResult::Read().
Write()
int Jack::JackPortRegisterResult::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 498 of file JackRequest.h.
References CheckRes, fPortIndex, Jack::detail::JackChannelTransactionInterface::Write(), and Jack::JackResult::Write().
Member Data Documentation
fPortIndex
jack_port_id_t Jack::JackPortRegisterResult::fPortIndex
Definition at line 487 of file JackRequest.h.
Referenced by JackPortRegisterResult(), Jack::JackRequestDecoder::HandleRequest(), Jack::JackGenericClientChannel::PortRegister(), Read(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h