LMMS: lmms::gui::FloatModelEditorBase Class Reference
lmms::gui::FloatModelEditorBase Class Reference
#include <FloatModelEditorBase.h>
Public Types
enum class DirectionOfManipulation {
Vertical ,
Horizontal
}
Signals
void sliderMoved (float value)
void sliderPressed ()
void sliderReleased ()
Public Member Functions
FloatModelEditorBase (const FloatModelEditorBase &other)=delete
FloatModelEditorBase (DirectionOfManipulation directionOfManipulation=DirectionOfManipulation::Vertical, QWidget *_parent=nullptr, const QString &_name=QString())
default ctor
void setHintText (const QString &txt_before, const QString &txt_after)
Public Member Functions inherited from lmms::gui::TypedModelView< FloatModel >
TypedModelView (Model *model, QWidget *_this)
FloatModel * model ()
const FloatModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *me) override
virtual QString displayValue () const
void doConnections () override
void dragEnterEvent (QDragEnterEvent *dee) override
void dropEvent (QDropEvent *de) override
void enterEvent (QEvent *event) override
void focusOutEvent (QFocusEvent *fe) override
virtual float getValue (const QPoint &p)
void leaveEvent (QEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
float pageSize () const
void paintEvent (QPaintEvent *me) override
void setPosition (const QPoint &p)
void showTextFloat (int msecBeforeDisplay, int msecDisplayTime)
void wheelEvent (QWheelEvent *me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void modelChanged ()
QWidget * widget ()
Protected Attributes
bool m_buttonPressed
DirectionOfManipulation m_directionOfManipulation
QPoint m_lastMousePos
mouse position in last mouseMoveEvent
float m_leftOver
BoolModel m_volumeKnob
FloatModel m_volumeRatio
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Static Protected Attributes
static SimpleTextFloat * s_textFloat = nullptr
Private Slots
virtual void enterValue ()
void friendlyUpdate ()
void toggleScale ()
Private Member Functions
void initUi (const QString &name)
to be called by ctors
mapPropertyFromModel (bool, isVolumeKnob, setVolumeKnob, m_volumeKnob)
mapPropertyFromModel (float, volumeRatio, setVolumeRatio, m_volumeRatio)
Detailed Description
Definition at line 40 of file FloatModelEditorBase.h.
Member Enumeration Documentation
DirectionOfManipulation
enum class lmms::gui::FloatModelEditorBase::DirectionOfManipulation strong
Enumerator
Vertical
Horizontal
Definition at line 50 of file FloatModelEditorBase.h.
Constructor & Destructor Documentation
FloatModelEditorBase() [1/2]
lmms::gui::FloatModelEditorBase::FloatModelEditorBase (DirectionOfManipulation directionOfManipulation = DirectionOfManipulation::Vertical, QWidget * _parent = nullptr, const QString & _name = QString())
default ctor
Definition at line 49 of file FloatModelEditorBase.cpp.
References initUi(), m_buttonPressed, m_directionOfManipulation, m_volumeKnob, and m_volumeRatio.
Referenced by lmms::gui::BarModelEditor::BarModelEditor(), lmms::gui::Draggable::Draggable(), FloatModelEditorBase(), and lmms::gui::Knob::Knob().
FloatModelEditorBase() [2/2]
lmms::gui::FloatModelEditorBase::FloatModelEditorBase (const FloatModelEditorBase & other) delete
References FloatModelEditorBase().
Member Function Documentation
contextMenuEvent()
void lmms::gui::FloatModelEditorBase::contextMenuEvent (QContextMenuEvent * me) override protected
Definition at line 103 of file FloatModelEditorBase.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), lmms::gui::TypedModelView< FloatModel >::model(), mouseReleaseEvent(), and toggleScale().
Referenced by sliderMoved().
displayValue()
QString lmms::gui::FloatModelEditorBase::displayValue () const protected virtual
Reimplemented in lmms::gui::CustomTextKnob.
Definition at line 430 of file FloatModelEditorBase.cpp.
References lmms::ampToDbfs(), lmms::FloatModel::getRoundedValue(), lmms::gui::AutomatableModelView::m_description, lmms::gui::AutomatableModelView::m_unit, and lmms::gui::TypedModelView< FloatModel >::model().
Referenced by lmms::gui::Draggable::mouseMoveEvent(), mouseMoveEvent(), mousePressEvent(), showTextFloat(), sliderMoved(), and wheelEvent().
doConnections()
void lmms::gui::FloatModelEditorBase::doConnections () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 447 of file FloatModelEditorBase.cpp.
References friendlyUpdate(), and lmms::gui::TypedModelView< FloatModel >::model().
Referenced by initUi(), and sliderMoved().
dragEnterEvent()
void lmms::gui::FloatModelEditorBase::dragEnterEvent (QDragEnterEvent * dee) override protected
Definition at line 128 of file FloatModelEditorBase.cpp.
References lmms::gui::StringPairDrag::processDragEnterEvent().
Referenced by sliderMoved().
dropEvent()
void lmms::gui::FloatModelEditorBase::dropEvent (QDropEvent * de) override protected
Definition at line 135 of file FloatModelEditorBase.cpp.
References lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::ProjectJournal::journallingObject(), lmms::AutomatableModel::linkModels(), lmms::gui::TypedModelView< FloatModel >::model(), lmms::Engine::projectJournal(), lmms::AutomatableModel::setValue(), lmms::LocaleHelper::toFloat(), and lmms::gui::AutomatableModelView::value().
Referenced by sliderMoved().
enterEvent()
void lmms::gui::FloatModelEditorBase::enterEvent (QEvent * event) override protected
Definition at line 233 of file FloatModelEditorBase.cpp.
References showTextFloat().
Referenced by sliderMoved().
enterValue
void lmms::gui::FloatModelEditorBase::enterValue () private virtual slot
Definition at line 374 of file FloatModelEditorBase.cpp.
References lmms::ampToDbfs(), lmms::dbfsToAmp(), lmms::FloatModel::getRoundedValue(), lmms::gui::TypedModelView< FloatModel >::model(), and lmms::AutomatableModel::setValue().
Referenced by mouseDoubleClickEvent().
focusOutEvent()
void lmms::gui::FloatModelEditorBase::focusOutEvent (QFocusEvent * fe) override protected
Definition at line 245 of file FloatModelEditorBase.cpp.
References mouseReleaseEvent().
Referenced by sliderMoved().
friendlyUpdate
void lmms::gui::FloatModelEditorBase::friendlyUpdate () private slot
Definition at line 419 of file FloatModelEditorBase.cpp.
References lmms::gui::TypedModelView< FloatModel >::model(), and lmms::Controller::runningFrames().
Referenced by doConnections().
getValue()
float lmms::gui::FloatModelEditorBase::getValue (const QPoint & p) protected virtual
Definition at line 84 of file FloatModelEditorBase.cpp.
References lmms::gui::getGUI(), m_directionOfManipulation, pageSize(), lmms::gui::AutomatableModelView::value(), and Vertical.
Referenced by setPosition(), and sliderMoved().
initUi()
void lmms::gui::FloatModelEditorBase::initUi (const QString & name) private
to be called by ctors
Definition at line 61 of file FloatModelEditorBase.cpp.
References doConnections(), and s_textFloat.
Referenced by FloatModelEditorBase(), and mapPropertyFromModel().
leaveEvent()
void lmms::gui::FloatModelEditorBase::leaveEvent (QEvent * event) override protected
Definition at line 239 of file FloatModelEditorBase.cpp.
References s_textFloat.
Referenced by sliderMoved().
mapPropertyFromModel() [1/2]
lmms::gui::FloatModelEditorBase::mapPropertyFromModel (bool , isVolumeKnob , setVolumeKnob , m_volumeKnob) private
References m_volumeKnob.
mapPropertyFromModel() [2/2]
lmms::gui::FloatModelEditorBase::mapPropertyFromModel (float , volumeRatio , setVolumeRatio , m_volumeRatio) private
References initUi(), and m_volumeRatio.
mouseDoubleClickEvent()
void lmms::gui::FloatModelEditorBase::mouseDoubleClickEvent (QMouseEvent * me) override protected
Definition at line 253 of file FloatModelEditorBase.cpp.
References enterValue().
Referenced by sliderMoved().
mouseMoveEvent()
void lmms::gui::FloatModelEditorBase::mouseMoveEvent (QMouseEvent * me) override protected
Definition at line 197 of file FloatModelEditorBase.cpp.
References displayValue(), m_buttonPressed, m_lastMousePos, lmms::gui::TypedModelView< FloatModel >::model(), s_textFloat, setPosition(), sliderMoved(), and lmms::gui::AutomatableModelView::value().
Referenced by sliderMoved().
mousePressEvent()
void lmms::gui::FloatModelEditorBase::mousePressEvent (QMouseEvent * me) override protected virtual
Reimplemented from lmms::gui::AutomatableModelView.
Definition at line 156 of file FloatModelEditorBase.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), displayValue(), lmms::KBD_COPY_MODIFIER, m_buttonPressed, m_lastMousePos, m_leftOver, lmms::gui::TypedModelView< FloatModel >::model(), lmms::gui::AutomatableModelView::mousePressEvent(), s_textFloat, lmms::JournallingObject::saveJournallingState(), showTextFloat(), sliderPressed(), and lmms::gui::AutomatableModelView::value().
Referenced by sliderMoved().
mouseReleaseEvent()
void lmms::gui::FloatModelEditorBase::mouseReleaseEvent (QMouseEvent * me) override protected
Definition at line 212 of file FloatModelEditorBase.cpp.
References m_buttonPressed, lmms::gui::TypedModelView< FloatModel >::model(), lmms::JournallingObject::restoreJournallingState(), s_textFloat, and sliderReleased().
Referenced by contextMenuEvent(), lmms::gui::TempoSyncBarModelEditor::contextMenuEvent(), lmms::gui::TempoSyncKnob::contextMenuEvent(), focusOutEvent(), and sliderMoved().
pageSize()
float lmms::gui::FloatModelEditorBase::pageSize () const inline protected
Definition at line 95 of file FloatModelEditorBase.h.
References lmms::gui::TypedModelView< FloatModel >::model().
Referenced by getValue().
paintEvent()
void lmms::gui::FloatModelEditorBase::paintEvent (QPaintEvent * me) override protected
Definition at line 259 of file FloatModelEditorBase.cpp.
References lmms::gui::TypedModelView< FloatModel >::model().
Referenced by sliderMoved().
setHintText()
void lmms::gui::FloatModelEditorBase::setHintText (const QString & txt_before, const QString & txt_after) inline
Definition at line 60 of file FloatModelEditorBase.h.
References lmms::gui::AutomatableModelView::setDescription(), and lmms::gui::AutomatableModelView::setUnit().
Referenced by lmms::gui::LadspaControlView::LadspaControlView().
setPosition()
void lmms::gui::FloatModelEditorBase::setPosition (const QPoint & p) protected
Definition at line 347 of file FloatModelEditorBase.cpp.
References lmms::approximatelyEqual(), getValue(), m_leftOver, lmms::gui::TypedModelView< FloatModel >::model(), lmms::AutomatableModel::scaledValue(), lmms::AutomatableModel::setValue(), lmms::AutomatableModel::step(), and lmms::TypedAutomatableModel< T >::value().
Referenced by mouseMoveEvent(), and sliderMoved().
showTextFloat()
void lmms::gui::FloatModelEditorBase::showTextFloat (int msecBeforeDisplay, int msecDisplayTime) protected
Definition at line 76 of file FloatModelEditorBase.cpp.
References displayValue(), and s_textFloat.
Referenced by enterEvent(), mousePressEvent(), and sliderMoved().
sliderMoved
void lmms::gui::FloatModelEditorBase::sliderMoved (float value) signal
References contextMenuEvent(), displayValue(), doConnections(), dragEnterEvent(), dropEvent(), enterEvent(), focusOutEvent(), getValue(), leaveEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), setPosition(), showTextFloat(), lmms::gui::AutomatableModelView::value(), and wheelEvent().
Referenced by lmms::gui::TempoSyncBarModelEditor::modelChanged(), lmms::gui::TempoSyncKnob::modelChanged(), lmms::gui::Draggable::mouseMoveEvent(), mouseMoveEvent(), and wheelEvent().
sliderPressed
void lmms::gui::FloatModelEditorBase::sliderPressed () signal
Referenced by mousePressEvent().
sliderReleased
void lmms::gui::FloatModelEditorBase::sliderReleased () signal
Referenced by mouseReleaseEvent().
toggleScale
void lmms::gui::FloatModelEditorBase::toggleScale () private slot
Definition at line 121 of file FloatModelEditorBase.cpp.
References lmms::gui::TypedModelView< FloatModel >::model(), and lmms::AutomatableModel::setScaleLogarithmic().
Referenced by contextMenuEvent(), lmms::gui::TempoSyncBarModelEditor::contextMenuEvent(), and lmms::gui::TempoSyncKnob::contextMenuEvent().
wheelEvent()
void lmms::gui::FloatModelEditorBase::wheelEvent (QWheelEvent * me) override protected
Definition at line 281 of file FloatModelEditorBase.cpp.
References displayValue(), lmms::AutomatableModel::incValue(), lmms::gui::TypedModelView< FloatModel >::model(), s_textFloat, lmms::AutomatableModel::scaledValue(), sliderMoved(), lmms::gui::AutomatableModelView::value(), and lmms::TypedAutomatableModel< T >::value().
Referenced by sliderMoved().
Member Data Documentation
m_buttonPressed
bool lmms::gui::FloatModelEditorBase::m_buttonPressed protected
Definition at line 107 of file FloatModelEditorBase.h.
Referenced by FloatModelEditorBase(), lmms::gui::Draggable::mouseMoveEvent(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_directionOfManipulation
DirectionOfManipulation lmms::gui::FloatModelEditorBase::m_directionOfManipulation protected
Definition at line 109 of file FloatModelEditorBase.h.
Referenced by FloatModelEditorBase(), getValue(), lmms::gui::Draggable::handleMovement(), and lmms::gui::Draggable::mouseMoveEvent().
m_lastMousePos
QPoint lmms::gui::FloatModelEditorBase::m_lastMousePos protected
mouse position in last mouseMoveEvent
Definition at line 105 of file FloatModelEditorBase.h.
Referenced by lmms::gui::Draggable::mouseMoveEvent(), mouseMoveEvent(), and mousePressEvent().
m_leftOver
float lmms::gui::FloatModelEditorBase::m_leftOver protected
Definition at line 106 of file FloatModelEditorBase.h.
Referenced by mousePressEvent(), and setPosition().
m_volumeKnob
BoolModel lmms::gui::FloatModelEditorBase::m_volumeKnob protected
Definition at line 102 of file FloatModelEditorBase.h.
Referenced by FloatModelEditorBase(), and mapPropertyFromModel().
m_volumeRatio
FloatModel lmms::gui::FloatModelEditorBase::m_volumeRatio protected
Definition at line 103 of file FloatModelEditorBase.h.
Referenced by FloatModelEditorBase(), and mapPropertyFromModel().
s_textFloat
SimpleTextFloat * lmms::gui::FloatModelEditorBase::s_textFloat = nullptr static protected
Definition at line 100 of file FloatModelEditorBase.h.
Referenced by initUi(), leaveEvent(), lmms::gui::Draggable::mouseMoveEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), showTextFloat(), and wheelEvent().
The documentation for this class was generated from the following files:
include/FloatModelEditorBase.h
src/gui/widgets/FloatModelEditorBase.cpp