LMMS: Jack::JackALSARawMidiPort Class Reference
Jack::JackALSARawMidiPort Class Reference
#include <JackALSARawMidiPort.h>
Public Member Functions
JackALSARawMidiPort (const char *client_name, snd_rawmidi_info_t *info, size_t index, unsigned short io_mask)
virtual ~JackALSARawMidiPort ()
const char * GetAlias ()
const char * GetDeviceName ()
const char * GetName ()
int GetPollDescriptorCount ()
void PopulatePollDescriptors (struct pollfd *poll_fd)
Protected Member Functions
int GetIOPollEvent ()
int GetQueuePollEvent ()
void SetIOEventsEnabled (bool enabled)
void SetQueueEventsEnabled (bool enabled)
bool TriggerQueueEvent ()
Protected Attributes
snd_rawmidi_t * rawmidi
Private Attributes
char alias [REAL_JACK_PORT_NAME_SIZE+1]
int alsa_poll_fd_count
struct pollfd * alsa_poll_fds
char device_name [REAL_JACK_PORT_NAME_SIZE+1]
int fds [2]
unsigned short io_mask
char name [REAL_JACK_PORT_NAME_SIZE+1]
struct pollfd * queue_poll_fd
Detailed Description
Definition at line 30 of file JackALSARawMidiPort.h.
Constructor & Destructor Documentation
JackALSARawMidiPort()
JackALSARawMidiPort::JackALSARawMidiPort (const char * client_name, snd_rawmidi_info_t * info, size_t index, unsigned short io_mask)
Definition at line 30 of file JackALSARawMidiPort.cpp.
References alias, alsa_poll_fd_count, Jack::CreateNonBlockingPipe(), device_name, fds, io_mask, name, and rawmidi.
Referenced by Jack::JackALSARawMidiInputPort::JackALSARawMidiInputPort(), and Jack::JackALSARawMidiOutputPort::JackALSARawMidiOutputPort().
~JackALSARawMidiPort()
JackALSARawMidiPort::~JackALSARawMidiPort () virtual
Definition at line 132 of file JackALSARawMidiPort.cpp.
References Jack::DestroyNonBlockingPipe(), fds, jack_error, and rawmidi.
Member Function Documentation
GetAlias()
const char * JackALSARawMidiPort::GetAlias ()
Definition at line 146 of file JackALSARawMidiPort.cpp.
References alias.
Referenced by Jack::JackALSARawMidiDriver::Attach().
GetDeviceName()
const char * JackALSARawMidiPort::GetDeviceName ()
Definition at line 184 of file JackALSARawMidiPort.cpp.
References device_name.
Referenced by Jack::JackALSARawMidiDriver::Attach().
GetIOPollEvent()
int JackALSARawMidiPort::GetIOPollEvent () protected
Definition at line 152 of file JackALSARawMidiPort.cpp.
References alsa_poll_fd_count, alsa_poll_fds, io_mask, jack_error, and rawmidi.
Referenced by Jack::JackALSARawMidiInputPort::ProcessPollEvents(), and Jack::JackALSARawMidiOutputPort::ProcessPollEvents().
GetName()
const char * JackALSARawMidiPort::GetName ()
Definition at line 178 of file JackALSARawMidiPort.cpp.
References name.
Referenced by Jack::JackALSARawMidiDriver::Attach().
GetPollDescriptorCount()
int JackALSARawMidiPort::GetPollDescriptorCount ()
Definition at line 190 of file JackALSARawMidiPort.cpp.
References alsa_poll_fd_count.
Referenced by Jack::JackALSARawMidiDriver::Start().
GetQueuePollEvent()
int JackALSARawMidiPort::GetQueuePollEvent () protected
Definition at line 196 of file JackALSARawMidiPort.cpp.
References fds, jack_error, and queue_poll_fd.
Referenced by Jack::JackALSARawMidiInputPort::ProcessPollEvents(), and Jack::JackALSARawMidiOutputPort::ProcessPollEvents().
PopulatePollDescriptors()
void JackALSARawMidiPort::PopulatePollDescriptors (struct pollfd * poll_fd)
Definition at line 225 of file JackALSARawMidiPort.cpp.
References alsa_poll_fd_count, alsa_poll_fds, fds, queue_poll_fd, rawmidi, and SetIOEventsEnabled().
Referenced by Jack::JackALSARawMidiDriver::Start().
SetIOEventsEnabled()
void JackALSARawMidiPort::SetIOEventsEnabled (bool enabled) protected
Definition at line 238 of file JackALSARawMidiPort.cpp.
References alsa_poll_fd_count, alsa_poll_fds, i, and io_mask.
Referenced by PopulatePollDescriptors(), Jack::JackALSARawMidiInputPort::ProcessPollEvents(), and Jack::JackALSARawMidiOutputPort::ProcessPollEvents().
SetQueueEventsEnabled()
void Jack::JackALSARawMidiPort::SetQueueEventsEnabled (bool enabled) protected
References io_mask.
TriggerQueueEvent()
bool JackALSARawMidiPort::TriggerQueueEvent () protected
Definition at line 247 of file JackALSARawMidiPort.cpp.
References fds, and jack_error.
Referenced by Jack::JackALSARawMidiInputPort::ProcessJack(), and Jack::JackALSARawMidiOutputPort::ProcessJack().
Member Data Documentation
alias
char Jack::JackALSARawMidiPort::alias[REAL_JACK_PORT_NAME_SIZE+1] private
Definition at line 34 of file JackALSARawMidiPort.h.
Referenced by JackALSARawMidiPort(), and GetAlias().
alsa_poll_fd_count
int Jack::JackALSARawMidiPort::alsa_poll_fd_count private
Definition at line 36 of file JackALSARawMidiPort.h.
Referenced by JackALSARawMidiPort(), GetIOPollEvent(), GetPollDescriptorCount(), PopulatePollDescriptors(), and SetIOEventsEnabled().
alsa_poll_fds
struct pollfd* Jack::JackALSARawMidiPort::alsa_poll_fds private
Definition at line 35 of file JackALSARawMidiPort.h.
Referenced by GetIOPollEvent(), PopulatePollDescriptors(), and SetIOEventsEnabled().
device_name
char Jack::JackALSARawMidiPort::device_name[REAL_JACK_PORT_NAME_SIZE+1] private
Definition at line 40 of file JackALSARawMidiPort.h.
Referenced by JackALSARawMidiPort(), and GetDeviceName().
fds
int Jack::JackALSARawMidiPort::fds[2] private
Definition at line 37 of file JackALSARawMidiPort.h.
Referenced by JackALSARawMidiPort(), ~JackALSARawMidiPort(), GetQueuePollEvent(), PopulatePollDescriptors(), and TriggerQueueEvent().
io_mask
unsigned short Jack::JackALSARawMidiPort::io_mask private
Definition at line 38 of file JackALSARawMidiPort.h.
Referenced by JackALSARawMidiPort(), GetIOPollEvent(), SetIOEventsEnabled(), and SetQueueEventsEnabled().
name
char Jack::JackALSARawMidiPort::name[REAL_JACK_PORT_NAME_SIZE+1] private
Definition at line 39 of file JackALSARawMidiPort.h.
Referenced by JackALSARawMidiPort(), and GetName().
queue_poll_fd
struct pollfd* Jack::JackALSARawMidiPort::queue_poll_fd private
Definition at line 41 of file JackALSARawMidiPort.h.
Referenced by GetQueuePollEvent(), and PopulatePollDescriptors().
rawmidi
snd_rawmidi_t* Jack::JackALSARawMidiPort::rawmidi protected
Definition at line 45 of file JackALSARawMidiPort.h.
Referenced by Jack::JackALSARawMidiInputPort::JackALSARawMidiInputPort(), Jack::JackALSARawMidiOutputPort::JackALSARawMidiOutputPort(), JackALSARawMidiPort(), ~JackALSARawMidiPort(), GetIOPollEvent(), and PopulatePollDescriptors().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/linux/alsarawmidi/JackALSARawMidiPort.h
src/3rdparty/jack2/linux/alsarawmidi/JackALSARawMidiPort.cpp