LMMS: Jack::JackRunnableInterface Class Reference
Jack::JackRunnableInterface Class Reference abstract
The base class for runnable objects, that have an Init and Execute method to be called in a thread.
#include <JackThread.h>
Public Member Functions
virtual bool Execute ()=0
virtual bool Init ()
Called once when the thread is started.
Protected Member Functions
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Detailed Description
The base class for runnable objects, that have an Init and Execute method to be called in a thread.
Definition at line 34 of file JackThread.h.
Constructor & Destructor Documentation
JackRunnableInterface()
Jack::JackRunnableInterface::JackRunnableInterface () inline protected
Definition at line 39 of file JackThread.h.
~JackRunnableInterface()
virtual Jack::JackRunnableInterface::~JackRunnableInterface () inline protected virtual
Definition at line 41 of file JackThread.h.
Member Function Documentation
Execute()
virtual bool Jack::JackRunnableInterface::Execute () pure virtual
Implemented in ClientThread, Jack::JackAlsaAdapter, Jack::JackALSARawMidiDriver, Jack::JackBoomerDriver::JackBoomerDriverInput, Jack::JackBoomerDriver::JackBoomerDriverOutput, Jack::JackClient, Jack::JackClientPipeThread, Jack::JackCoreMidiDriver, Jack::JackCoreMidiOutputPort, Jack::JackMachSemaphoreServer, Jack::JackMessageBuffer, Jack::JackNetAdapter, Jack::JackNetExtSlave, Jack::JackOSSAdapter, Jack::JackRestartThreadedDriver, Jack::JackSocketClientChannel, Jack::JackSocketServerChannel, Jack::JackThreadedDriver, Jack::JackWaitThreadedDriver, Jack::JackWaitThreadedDriver::JackDriverStarter, Jack::JackWinMMEOutputPort, Jack::JackWinNamedPipeClientChannel, Jack::JackWinNamedPipeServerChannel, JackALSARawMidiDriver, JackWinMMEOutputPort, ReaderThread, RTReaderThread, ServerThread, Test1< sync_type >, Test1< sync_type >, Test2< sync_type >, Test2< sync_type >, TestThread1, TestThread, and WriterThread.
Referenced by Jack::JackAndroidThread::ThreadHandler(), Jack::JackPosixThread::ThreadHandler(), and Jack::JackWinThread::ThreadHandler().
Init()
virtual bool Jack::JackRunnableInterface::Init () inline virtual
Called once when the thread is started.
Reimplemented in Jack::JackAlsaAdapter, Jack::JackALSARawMidiDriver, Jack::JackBoomerDriver::JackBoomerDriverInput, Jack::JackBoomerDriver::JackBoomerDriverOutput, Jack::JackClient, Jack::JackCoreMidiDriver, Jack::JackCoreMidiOutputPort, Jack::JackNetAdapter, Jack::JackNetExtSlave, Jack::JackSocketClientChannel, Jack::JackSocketServerChannel, Jack::JackThreadedDriver, Jack::JackWaitThreadedDriver, Jack::JackWinMMEOutputPort, Jack::JackWinNamedPipeClientChannel, Jack::JackWinNamedPipeServerChannel, JackALSARawMidiDriver, and JackWinMMEOutputPort.
Definition at line 46 of file JackThread.h.
Referenced by Jack::JackAndroidThread::ThreadHandler(), Jack::JackPosixThread::ThreadHandler(), and Jack::JackWinThread::ThreadHandler().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackThread.h