LMMS: lmms::AudioDummy Class Reference
lmms::AudioDummy Class Reference
#include <AudioDummy.h>
Classes
class setupWidget
Public Member Functions
AudioDummy (bool &_success_ful, AudioEngine *audioEngine)
~AudioDummy () override
Public Member Functions inherited from lmms::AudioDevice
AudioDevice (const ch_cnt_t _channels, AudioEngine *audioEngine)
virtual ~AudioDevice ()
void lock ()
void processNextBuffer ()
virtual void registerPort (AudioBusHandle *port)
virtual void renamePort (AudioBusHandle *port)
sample_rate_t sampleRate () const
bool supportsCapture () const
void unlock ()
virtual void unregisterPort (AudioBusHandle *port)
Static Public Member Functions
static QString name ()
Private Member Functions
void run () override
void startProcessing () override
void stopProcessing () override
Additional Inherited Members
Protected Member Functions inherited from lmms::AudioDevice
AudioEngine * audioEngine ()
ch_cnt_t channels () const
void clearS16Buffer (int_sample_t *_outbuf, const fpp_t _frames)
int convertToS16 (const SampleFrame *_ab, const fpp_t _frames, int_sample_t *_output_buffer, const bool _convert_endian=false)
fpp_t getNextBuffer (SampleFrame *_ab)
void setSampleRate (const sample_rate_t _new_sr)
virtual void writeBuffer (const SampleFrame *, const fpp_t)
Static Protected Member Functions inherited from lmms::AudioDevice
static void stopProcessingThread (QThread *thread)
Protected Attributes inherited from lmms::AudioDevice
bool m_supportsCapture
Detailed Description
Definition at line 36 of file AudioDummy.h.
Constructor & Destructor Documentation
AudioDummy()
lmms::AudioDummy::AudioDummy (bool & _success_ful, AudioEngine * audioEngine) inline
Definition at line 40 of file AudioDummy.h.
References lmms::AudioDevice::AudioDevice(), lmms::AudioDevice::audioEngine(), and lmms::DEFAULT_CHANNELS.
Referenced by lmms::AudioDummy::setupWidget::setupWidget().
~AudioDummy()
lmms::AudioDummy::~AudioDummy () inline override
Definition at line 46 of file AudioDummy.h.
References stopProcessing().
Member Function Documentation
name()
QString lmms::AudioDummy::name () inline static
Definition at line 51 of file AudioDummy.h.
Referenced by lmms::gui::SetupDialog::SetupDialog(), lmms::AudioDummy::setupWidget::setupWidget(), lmms::AudioEngine::initDevices(), lmms::AudioEngine::isAudioDevNameValid(), and lmms::AudioEngine::tryAudioDevices().
run()
void lmms::AudioDummy::run () inline override private
Definition at line 91 of file AudioDummy.h.
References lmms::AudioDevice::audioEngine(), lmms::MicroTimer::elapsed(), lmms::AudioEngine::framesPerPeriod(), lmms::AudioEngine::nextBuffer(), lmms::AudioEngine::outputSampleRate(), and lmms::MicroTimer::reset().
startProcessing()
void lmms::AudioDummy::startProcessing () inline override private virtual
Reimplemented from lmms::AudioDevice.
Definition at line 81 of file AudioDummy.h.
stopProcessing()
void lmms::AudioDummy::stopProcessing () inline override private virtual
Reimplemented from lmms::AudioDevice.
Definition at line 86 of file AudioDummy.h.
References lmms::AudioDevice::stopProcessingThread().
Referenced by ~AudioDummy().
The documentation for this class was generated from the following file:
include/AudioDummy.h