LMMS: Jack::JackShmMem Class Reference
Jack::JackShmMem Class Reference
The base class for shared memory management.
#include <JackShmMem.h>
Public Member Functions
void operator delete (void *p)
void operator delete (void *p, size_t size)
void * operator new (size_t size)
void * operator new (size_t size, void *memory)
Public Member Functions inherited from Jack::JackShmMemAble
char * GetShmAddress ()
int GetShmIndex ()
void Init ()
void LockMemory ()
void UnlockMemory ()
Protected Member Functions
JackShmMem ()
~JackShmMem ()
Additional Inherited Members
Protected Attributes inherited from Jack::JackShmMemAble
jack_shm_info_t fInfo
Detailed Description
The base class for shared memory management.
A class which objects need to be allocated in shared memory derives from this class.
Definition at line 86 of file JackShmMem.h.
Constructor & Destructor Documentation
JackShmMem()
Jack::JackShmMem::JackShmMem () protected
Definition at line 30 of file JackShmMem.cpp.
References Jack::JackShmMemAble::Init(), and Jack::JackShmMemAble::LockMemory().
Referenced by operator delete(), and operator new().
~JackShmMem()
Jack::JackShmMem::~JackShmMem () protected
Definition at line 36 of file JackShmMem.cpp.
References Jack::JackShmMemAble::UnlockMemory().
Member Function Documentation
operator delete() [1/2]
void Jack::JackShmMem::operator delete (void * p)
Definition at line 101 of file JackShmMem.cpp.
operator delete() [2/2]
void Jack::JackShmMem::operator delete (void * p, size_t size)
Definition at line 88 of file JackShmMem.cpp.
References JackShmMem(), _jack_shm_info::attached_at, Jack::JackShmMemAble::fInfo, _jack_shm_info::index, jack_destroy_shm, jack_log(), jack_release_shm(), and _jack_shm_info::ptr.
operator new() [1/2]
void * Jack::JackShmMem::operator new (size_t size)
Definition at line 54 of file JackShmMem.cpp.
References JackShmMem(), _jack_shm_info::attached_at, Jack::fSegmentNum, Jack::gInfo, _jack_shm_info::index, jack_attach_shm(), jack_destroy_shm, jack_error, jack_log(), jack_shm_addr(), jack_shmalloc(), and _jack_shm_info::ptr.
operator new() [2/2]
void * Jack::JackShmMem::operator new (size_t size, void * memory)
Definition at line 48 of file JackShmMem.cpp.
References jack_log().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackShmMem.h
src/3rdparty/jack2/common/JackShmMem.cpp