LMMS: Jack::JackClientPipeThread Class Reference
Jack::JackClientPipeThread Class Reference
#include <JackWinNamedPipeServerChannel.h>
Public Member Functions
JackClientPipeThread (JackWinNamedPipeClient *pipe)
virtual ~JackClientPipeThread ()
void Close ()
bool Execute ()
bool IsRunning ()
int Open (JackServer *server)
Public Member Functions inherited from Jack::JackRunnableInterface
virtual bool Init ()
Called once when the thread is started.
Public Member Functions inherited from Jack::JackClientHandlerInterface
virtual ~JackClientHandlerInterface ()
Private Member Functions
void ClientAdd (detail::JackChannelTransactionInterface *socket, JackClientOpenRequest *req, JackClientOpenResult *res)
void ClientKill ()
void ClientRemove (detail::JackChannelTransactionInterface *socket, int refnum)
Private Attributes
JackRequestDecoder * fDecoder
JackWinNamedPipeClient * fPipe
int fRefNum
JackServer * fServer
JackThread fThread
Static Private Attributes
static HANDLE fMutex = NULL
Additional Inherited Members
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Detailed Description
Definition at line 34 of file JackWinNamedPipeServerChannel.h.
Constructor & Destructor Documentation
JackClientPipeThread()
Jack::JackClientPipeThread::JackClientPipeThread (JackWinNamedPipeClient * pipe)
Definition at line 41 of file JackWinNamedPipeServerChannel.cpp.
References FALSE, fDecoder, fMutex, fPipe, fRefNum, fServer, and fThread.
~JackClientPipeThread()
Jack::JackClientPipeThread::~JackClientPipeThread () virtual
Definition at line 50 of file JackWinNamedPipeServerChannel.cpp.
References fPipe, and jack_log().
Member Function Documentation
ClientAdd()
void Jack::JackClientPipeThread::ClientAdd (detail::JackChannelTransactionInterface * socket, JackClientOpenRequest * req, JackClientOpenResult * res) private virtual
Implements Jack::JackClientHandlerInterface.
Definition at line 117 of file JackWinNamedPipeServerChannel.cpp.
References Jack::JackClientOpenRequest::fName, Jack::JackClientOpenRequest::fPID, fRefNum, Jack::JackResult::fResult, fServer, Jack::JackClientOpenResult::fSharedClient, Jack::JackClientOpenResult::fSharedEngine, Jack::JackClientOpenResult::fSharedGraph, Jack::JackClientOpenRequest::fUUID, and jack_log().
ClientKill()
void Jack::JackClientPipeThread::ClientKill () private
Definition at line 130 of file JackWinNamedPipeServerChannel.cpp.
References Close(), fRefNum, fServer, and jack_log().
Referenced by Execute().
ClientRemove()
void Jack::JackClientPipeThread::ClientRemove (detail::JackChannelTransactionInterface * socket, int refnum) private virtual
Implements Jack::JackClientHandlerInterface.
Definition at line 124 of file JackWinNamedPipeServerChannel.cpp.
References Close(), and jack_log().
Close()
void Jack::JackClientPipeThread::Close ()
Definition at line 69 of file JackWinNamedPipeServerChannel.cpp.
References fDecoder, fPipe, fRefNum, and jack_log().
Referenced by ClientKill(), and ClientRemove().
Execute()
bool Jack::JackClientPipeThread::Execute () virtual
Implements Jack::JackRunnableInterface.
Definition at line 81 of file JackWinNamedPipeServerChannel.cpp.
References ClientKill(), fDecoder, fMutex, fPipe, Jack::JackRequest::fType, jack_error, jack_log(), and Jack::JackRequest::Read().
IsRunning()
bool Jack::JackClientPipeThread::IsRunning () inline
Definition at line 64 of file JackWinNamedPipeServerChannel.h.
References fRefNum.
Open()
int Jack::JackClientPipeThread::Open (JackServer * server)
Definition at line 56 of file JackWinNamedPipeServerChannel.cpp.
References fDecoder, fServer, fThread, jack_error, and server().
Member Data Documentation
fDecoder
JackRequestDecoder* Jack::JackClientPipeThread::fDecoder private
Definition at line 40 of file JackWinNamedPipeServerChannel.h.
Referenced by JackClientPipeThread(), Close(), Execute(), and Open().
fMutex
HANDLE Jack::JackClientPipeThread::fMutex = NULL static private
Definition at line 50 of file JackWinNamedPipeServerChannel.h.
Referenced by JackClientPipeThread(), and Execute().
fPipe
JackWinNamedPipeClient* Jack::JackClientPipeThread::fPipe private
Definition at line 39 of file JackWinNamedPipeServerChannel.h.
Referenced by JackClientPipeThread(), ~JackClientPipeThread(), Close(), and Execute().
fRefNum
int Jack::JackClientPipeThread::fRefNum private
Definition at line 43 of file JackWinNamedPipeServerChannel.h.
Referenced by JackClientPipeThread(), ClientAdd(), ClientKill(), Close(), and IsRunning().
fServer
JackServer* Jack::JackClientPipeThread::fServer private
Definition at line 41 of file JackWinNamedPipeServerChannel.h.
Referenced by JackClientPipeThread(), ClientAdd(), ClientKill(), and Open().
fThread
JackThread Jack::JackClientPipeThread::fThread private
Definition at line 42 of file JackWinNamedPipeServerChannel.h.
Referenced by JackClientPipeThread(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinNamedPipeServerChannel.h
src/3rdparty/jack2/windows/JackWinNamedPipeServerChannel.cpp