LMMS: Jack::JackLockAble Class Reference
Jack::JackLockAble Class Reference
Base class for "lockable" objects.
#include <JackMutex.h>
Public Member Functions
bool Lock ()
bool Trylock ()
bool Unlock ()
Protected Member Functions
JackLockAble (const char *name=NULL)
~JackLockAble ()
Protected Attributes
JackMutex fMutex
Detailed Description
Base class for "lockable" objects.
Definition at line 36 of file JackMutex.h.
Constructor & Destructor Documentation
JackLockAble()
Jack::JackLockAble::JackLockAble (const char * name = NULL) inline protected
Definition at line 43 of file JackMutex.h.
References fMutex.
Referenced by Jack::JackEngine::JackEngine().
~JackLockAble()
Jack::JackLockAble::~JackLockAble () inline protected
Definition at line 46 of file JackMutex.h.
Member Function Documentation
Lock()
bool Jack::JackLockAble::Lock () inline
Definition at line 51 of file JackMutex.h.
References fMutex.
Referenced by Jack::JackEngine::ClientNotify(), LockedObject::LockedMethod1(), LockedObject::LockedMethod2(), and LockedObject::LockedMethod3().
Trylock()
bool Jack::JackLockAble::Trylock () inline
Definition at line 56 of file JackMutex.h.
References fMutex.
Unlock()
bool Jack::JackLockAble::Unlock () inline
Definition at line 61 of file JackMutex.h.
References fMutex.
Referenced by CleanupHandler(), Jack::JackEngine::ClientNotify(), LockedObject::LockedMethod1(), LockedObject::LockedMethod2(), and LockedObject::LockedMethod3().
Member Data Documentation
fMutex
JackMutex Jack::JackLockAble::fMutex protected
Definition at line 41 of file JackMutex.h.
Referenced by JackLockAble(), Lock(), Trylock(), and Unlock().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackMutex.h