LMMS: ringbuffer_base::rb_atomic< T > Class Template Reference
ringbuffer_base::rb_atomic< T > Class Template Reference
Public Member Functions
rb_atomic ()
rb_atomic (rb_atomic &&other)
this shall only be used for construction
T load (std::memory_order mo=std::memory_order_acquire) const
rb_atomic< T > & operator-- ()
void store (const T &t, std::memory_order mo=std::memory_order_release)
Private Attributes
std::atomic< T > var
Detailed Description
template<class T>
class ringbuffer_base::rb_atomic< T >
Definition at line 61 of file ringbuffer.h.
Constructor & Destructor Documentation
rb_atomic() [1/2]
template<class T> ringbuffer_base::rb_atomic< T >::rb_atomic () inline
Definition at line 73 of file ringbuffer.h.
Referenced by rb_atomic(), and operator--().
rb_atomic() [2/2]
template<class T> ringbuffer_base::rb_atomic< T >::rb_atomic (rb_atomic< T > && other) inline
this shall only be used for construction
Definition at line 75 of file ringbuffer.h.
References rb_atomic(), and store().
Member Function Documentation
load()
template<class T> T ringbuffer_base::rb_atomic< T >::load (std::memory_order mo = std::memory_order_acquire) const inline
Definition at line 65 of file ringbuffer.h.
References var.
operator--()
template<class T> rb_atomic< T > & ringbuffer_base::rb_atomic< T >::operator-- () inline
Definition at line 77 of file ringbuffer.h.
References rb_atomic(), and var.
store()
template<class T> void ringbuffer_base::rb_atomic< T >::store (const T & t, std::memory_order mo = std::memory_order_release) inline
Definition at line 69 of file ringbuffer.h.
References var.
Referenced by rb_atomic().
Member Data Documentation
var
template<class T> std::atomic<T> ringbuffer_base::rb_atomic< T >::var private
Definition at line 63 of file ringbuffer.h.
Referenced by load(), operator--(), and store().
The documentation for this class was generated from the following file:
src/3rdparty/ringbuffer/include/ringbuffer/ringbuffer.h