LMMS: hiir::StageProc16Avx512< REMAINING > Class Template Reference
hiir::StageProc16Avx512< REMAINING > Class Template Reference
#include <StageProc16Avx512.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m512 &spl_0, __m512 &spl_1, StageDataAvx512 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m512 &spl_0, __m512 &spl_1, StageDataAvx512 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m512 &spl_0, __m512 &spl_1, StageDataAvx512 *stage_arr) noexcept
hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m512 &spl_0, __m512 &spl_1, StageDataAvx512 *stage_arr) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, __m512 &spl_0, __m512 &spl_1, StageDataAvx512 *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, __m512 &spl_0, __m512 &spl_1, StageDataAvx512 *stage_arr) noexcept
Private Member Functions
StageProc16Avx512 ()=delete
StageProc16Avx512 (const StageProc16Avx512< REMAINING > &other)=delete
StageProc16Avx512 (StageProc16Avx512< REMAINING > &&other)=delete
~StageProc16Avx512 ()=delete
bool operator!= (const StageProc16Avx512< REMAINING > &other)=delete
StageProc16Avx512< REMAINING > & operator= (const StageProc16Avx512< REMAINING > &other)=delete
StageProc16Avx512< REMAINING > & operator= (StageProc16Avx512< REMAINING > &&other)=delete
bool operator== (const StageProc16Avx512< REMAINING > &other)=delete
Detailed Description
template<int REMAINING>
class hiir::StageProc16Avx512< REMAINING >
Definition at line 46 of file StageProc16Avx512.h.
Constructor & Destructor Documentation
StageProc16Avx512() [1/3]
template<int REMAINING> hiir::StageProc16Avx512< REMAINING >::StageProc16Avx512 () private delete
Referenced by process_sample_neg(), and process_sample_pos().
StageProc16Avx512() [2/3]
template<int REMAINING> hiir::StageProc16Avx512< REMAINING >::StageProc16Avx512 (const StageProc16Avx512< REMAINING > & other) private delete
StageProc16Avx512() [3/3]
template<int REMAINING> hiir::StageProc16Avx512< REMAINING >::StageProc16Avx512 (StageProc16Avx512< REMAINING > && other) private delete
~StageProc16Avx512()
template<int REMAINING> hiir::StageProc16Avx512< REMAINING >::~StageProc16Avx512 () private delete
Member Function Documentation
operator!=()
template<int REMAINING> bool hiir::StageProc16Avx512< REMAINING >::operator!= (const StageProc16Avx512< REMAINING > & other) private delete
operator=() [1/2]
template<int REMAINING> StageProc16Avx512< REMAINING > & hiir::StageProc16Avx512< REMAINING >::operator= (const StageProc16Avx512< REMAINING > & other) private delete
operator=() [2/2]
template<int REMAINING> StageProc16Avx512< REMAINING > & hiir::StageProc16Avx512< REMAINING >::operator= (StageProc16Avx512< REMAINING > && other) private delete
operator==()
template<int REMAINING> bool hiir::StageProc16Avx512< REMAINING >::operator== (const StageProc16Avx512< REMAINING > & other) private delete
process_sample_neg() [1/3]
template<int REMAINING> void hiir::StageProc16Avx512< REMAINING >::process_sample_neg (const int nbr_coefs, __m512 & spl_0, __m512 & spl_1, StageDataAvx512 * stage_arr) static noexcept
Definition at line 146 of file StageProc16Avx512.hpp.
References StageProc16Avx512(), and process_sample_neg().
Referenced by hiir::PhaseHalfPi16Avx512< NC >::process_block(), hiir::PhaseHalfPi16Avx512< NC >::process_sample(), and process_sample_neg().
process_sample_neg() [2/3]
hiir_FORCEINLINE void hiir::StageProc16Avx512< 0 >::process_sample_neg (const int nbr_coefs, __m512 & spl_0, __m512 & spl_1, StageDataAvx512 * stage_arr) noexcept
Definition at line 135 of file StageProc16Avx512.hpp.
References hiir_FORCEINLINE.
process_sample_neg() [3/3]
hiir_FORCEINLINE void hiir::StageProc16Avx512< 1 >::process_sample_neg (const int nbr_coefs, __m512 & spl_0, __m512 & spl_1, StageDataAvx512 * stage_arr) noexcept
Definition at line 113 of file StageProc16Avx512.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [1/3]
template<int REMAINING> void hiir::StageProc16Avx512< REMAINING >::process_sample_pos (const int nbr_coefs, __m512 & spl_0, __m512 & spl_1, StageDataAvx512 * stage_arr) static noexcept
Definition at line 77 of file StageProc16Avx512.hpp.
References StageProc16Avx512(), and process_sample_pos().
Referenced by hiir::HalfBand16Avx512< NC >::process_2_paths(), hiir::HalfBand16Avx512< NC >::process_block_2_paths(), hiir::Downsampler2x16Avx512< NC >::process_sample(), hiir::Upsampler2x16Avx512< NC >::process_sample(), process_sample_pos(), and hiir::Downsampler2x16Avx512< NC >::process_sample_split().
process_sample_pos() [2/3]
hiir_FORCEINLINE void hiir::StageProc16Avx512< 0 >::process_sample_pos (const int nbr_coefs, __m512 & spl_0, __m512 & spl_1, StageDataAvx512 * stage_arr) noexcept
Definition at line 66 of file StageProc16Avx512.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [3/3]
hiir_FORCEINLINE void hiir::StageProc16Avx512< 1 >::process_sample_pos (const int nbr_coefs, __m512 & spl_0, __m512 & spl_1, StageDataAvx512 * stage_arr) noexcept
Definition at line 44 of file StageProc16Avx512.hpp.
References hiir_FORCEINLINE.
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProc16Avx512.h
src/3rdparty/hiir/hiir/StageProc16Avx512.hpp