LMMS: lmms::gui Namespace Reference
lmms::gui Namespace Reference
Namespaces
namespace anonymous_namespace{SongEditor.cpp}
namespace anonymous_namespace{TimeLineWidget.cpp}
Classes
class AboutDialog
class ActionGroup
Convenience subclass of QActionGroup.
class AudioDeviceSetupWidget
class AutomatableButton
class AutomatableButtonGroup
class AutomatableModelView
class AutomatableModelViewSlots
class AutomatableSlider
class AutomationClipView
class AutomationEditor
class AutomationEditorWindow
class AutomationTrackView
class BarModelEditor
class CaptionMenu
A context menu with a caption.
class CheckControl
class ClipView
class ColorChooser
class ColorHelper
class ComboBox
class ComboControl
class Control
These classes provide.
class ControlLayout
Layout for controls (models).
class ControllerConnectionDialog
class ControllerDialog
class ControllerRackView
class ControllerView
class CPULoadWidget
class CustomTextKnob
class Directory
class Draggable
A pixmap that can be dragged from one location to another to control a FloatModel.
class DropToolBar
Small helper class: A QToolBar that accepts and exposes drop events as signals.
class DualColumnFilterProxyModel
class DummyEffectControlDialog
class Editor
Superclass for editors with a toolbar.
class EffectControlDialog
class EffectRackView
class EffectSelectDialog
class EffectView
class EnvelopeAndLfoView
class EnvelopeGraph
class ExportProjectDialog
class FadeButton
class Fader
class FileBrowser
class FileBrowserTreeWidget
class FileBrowserWidgetItem
class FileDialog
class FileItem
class FileRevealer
A utility class for revealing files and directories in the system's file manager.
class FileSearchJob
The FileSearchJob class allows for searching for files on the filesystem.
class FloatModelEditorBase
class Graph
class GroupBox
class GuiApplication
class InstrumentFunctionArpeggioView
class InstrumentFunctionNoteStackingView
class InstrumentMidiIOView
class InstrumentSoundShapingView
class InstrumentTrackView
class InstrumentTrackWindow
class InstrumentTuningView
class InstrumentView
Instrument view with variable size.
class InstrumentViewFixedSize
Instrument view with fixed LMMS-default size.
class Knob
class KnobControl
class LadspaControlView
class LcdControl
class LcdFloatSpinBox
class LcdSpinBox
class LcdWidget
class LedCheckBox
class LeftRightNav
class LfoControllerDialog
class LfoGraph
class LinkedModelGroupsView
Container class for one LinkedModelGroupView.
class LinkedModelGroupView
View for a representative processor.
class LmmsPalette
class LmmsStyle
class MainApplication
class MainWindow
class MeterDialog
class MicrotunerConfig
class MidiCCRackView
class MidiClipView
class MidiPortMenu
class MidiSetupWidget
class MixerChannelLcdSpinBox
class MixerChannelView
class MixerView
class ModelView
class NStateButton
class Oscilloscope
class PatternClipView
class PatternEditor
class PatternEditorWindow
class PatternTrackView
class PeakControllerDialog
class PeakIndicator
class PianoRoll
class PianoRollWindow
class PianoView
class PixmapButton
class PluginBrowser
class PluginDescWidget
class PluginView
class PositionLine
class ProjectNotes
class RecentProjectsMenu
class RenameDialog
class RowDelegate
class RowTableView
class RubberBand
class SampleClipView
class SampleLoader
class SampleTrackView
class SampleTrackWindow
class SaveOptionsWidget
class selectableObject
class SendButtonIndicator
class SetupDialog
class SideBar
class SideBarButton
class SideBarWidget
class SimpleTextFloat
class SongEditor
class SongEditorWindow
class StepRecorderWidget
class StringPairDrag
class SubWindow
The SubWindow class.
class TabBar
class TabButton
class TabWidget
class TemplatesMenu
class TempoSyncBarModelEditor
class TempoSyncKnob
class TextFloat
class TimeDisplayWidget
class TimeLineWidget
class ToolButton
class ToolPluginView
class TrackContainerView
class TrackContentWidget
class TrackGrip
class TrackLabelButton
class TrackOperationsWidget
class TrackRenameLineEdit
class TrackView
class TypedModelView
class VersionedSaveDialog
Typedefs
using BoolModelView = TypedModelView<BoolModel>
using FloatModelView = TypedModelView<FloatModel>
using IntModelView = TypedModelView<IntModel>
using LcdFloatSpinBoxModel = FloatModel
using LcdSpinBoxModel = IntModel
using sliderModel = IntModel
Enumerations
enum class KnobType {
Dark28 ,
Bright26 ,
Small17 ,
Vintage32 ,
Styled
}
enum TreeWidgetItemTypes {
TypeFileItem = QTreeWidgetItem::UserType ,
TypeDirectoryItem
}
Functions
QFont adjustedToPixelSize (QFont font, int size)
static void animateScroll (QScrollBar *scrollBar, int newVal, bool smoothScroll)
static int computeNoteRange (int minKey, int maxKey)
void convertPixmapToGrayScale (QPixmap &pixMap)
QLinearGradient darken (const QLinearGradient &_gradient)
void drawPath (QPainter *p, const QPainterPath &path, const QColor &col, const QColor &borderCol, bool dark=false)
static float floatFromClipboard (bool *ok)
Attempt to parse a float from the clipboard.
QLinearGradient getGradient (const QColor &_col, const QRectF &_rect)
GuiApplication * getGUI ()
static int getKeyOffsetFromKeyEvent (QKeyEvent *_ke)
static QString getNoteString (int key)
void labelWidget (QWidget *w, const QString &txt)
OutputSettings::StereoMode mapToStereoMode (int index)
Variables
const int BARS_PER_GROUP = 4
Alternate between a darker and a lighter background color every 4 bars.
constexpr int BeatStepButtonOffset = 4
const int BLACK_KEY_WIDTH = 41
constexpr int BUFFERSIZE_RESOLUTION = 32
constexpr int c_margin = 2
const int CB_ARROW_BTN_WIDTH = 18
const int CD_ENV_KNOBS_LBL_Y = 11
const int CD_KNOB_X_SPACING = 32
const int CD_LFO_AMOUNT_CD_KNOB_X = CD_LFO_SPEED_CD_KNOB_X+CD_KNOB_X_SPACING
const int CD_LFO_BASE_CD_KNOB_X = CD_LFO_SHAPES_X + 68
const int CD_LFO_CD_KNOB_Y = CD_LFO_GRAPH_Y-2
const int CD_LFO_GRAPH_Y = CD_ENV_KNOBS_LBL_Y+3
const int CD_LFO_MULTIPLIER_X = CD_LFO_PHASE_CD_KNOB_X+CD_KNOB_X_SPACING+3
const int CD_LFO_PHASE_CD_KNOB_X = CD_LFO_AMOUNT_CD_KNOB_X+CD_KNOB_X_SPACING
const int CD_LFO_SHAPES_X = 6
const int CD_LFO_SHAPES_Y = CD_ENV_KNOBS_LBL_Y + 4
const int CD_LFO_SPEED_CD_KNOB_X = CD_LFO_BASE_CD_KNOB_X+CD_KNOB_X_SPACING
const int DEFAULT_CELL_WIDTH = 12
const int DEFAULT_KEY_LINE_HEIGHT = 12
const int DEFAULT_PR_PPB = DEFAULT_CELL_WIDTH * DefaultStepsPerBar
const int DEFAULT_SETTINGS_WIDGET_WIDTH = 260
const int DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT = 136
const float FadeDuration = 300
const int GRAPHIC_TAB_HEIGHT = 17
const int INITIAL_PIANOROLL_HEIGHT = 485
const int INITIAL_PIANOROLL_WIDTH = 970
const int INITIAL_START_KEY = Octave::Octave_4 + Key::C
const int INSTRUMENT_HEIGHT = INSTRUMENT_WIDTH
const int INSTRUMENT_WIDTH = 254
const int KEY_AREA_MIN_HEIGHT = DEFAULT_KEY_LINE_HEIGHT * 10
const int LABEL_TEXT_SIZE = 8
The height of the key label text.
const int MIN_PIXELS_BETWEEN_LINES = 4
static const auto names
const int NOTE_EDIT_LINE_WIDTH = 3
const int NOTE_EDIT_MIN_HEIGHT = 50
const int NOTE_EDIT_RESIZE_BAR = 6
const int NUM_EVEN_LENGTHS = 6
const int NUM_TRIPLET_LENGTHS = 5
const int PIANO_BASE = 11
The height of the root note display.
const int PIANO_HEIGHT = 80
const int PIANO_X = 0
const int PR_BOTTOM_MARGIN = SCROLLBAR_SIZE
const int PR_RIGHT_MARGIN = SCROLLBAR_SIZE
const int PR_TOP_MARGIN = 18
const int PW_BLACK_KEY_HEIGHT = 38
The height of a black key.
const int PW_BLACK_KEY_WIDTH = 8
The width of a black key.
const int PW_WHITE_KEY_HEIGHT = 57
The height of a white key.
const int PW_WHITE_KEY_WIDTH = 10
The width of a white key.
static const int Quantizations []
const int RESIZE_AREA_WIDTH = 9
const int RESIZE_GRIP_WIDTH = 4
The width of the resize grip in pixels.
static std::array< QString, 12 > s_noteStrings
const int SCROLLBAR_SIZE = 12
const int TEXT_TAB_HEIGHT = 14
const int TRACK_OP_WIDTH = 78
const int TRACK_OP_WIDTH_COMPACT = TRACK_OP_WIDTH
const int WHITE_KEY_WIDTH = 64
auto WhiteKeys
The scale of C Major - white keys only.
Typedef Documentation
BoolModelView
using lmms::gui::BoolModelView = TypedModelView<BoolModel>
Definition at line 136 of file AutomatableModelView.h.
FloatModelView
using lmms::gui::FloatModelView = TypedModelView<FloatModel>
Definition at line 134 of file AutomatableModelView.h.
IntModelView
using lmms::gui::IntModelView = TypedModelView<IntModel>
Definition at line 135 of file AutomatableModelView.h.
LcdFloatSpinBoxModel
using lmms::gui::LcdFloatSpinBoxModel = FloatModel
Definition at line 89 of file LcdFloatSpinBox.h.
LcdSpinBoxModel
using lmms::gui::LcdSpinBoxModel = IntModel
Definition at line 88 of file LcdSpinBox.h.
sliderModel
using lmms::gui::sliderModel = IntModel
Definition at line 75 of file AutomatableSlider.h.
Enumeration Type Documentation
KnobType
enum class lmms::gui::KnobType strong
Enumerator
Dark28
Bright26
Small17
Vintage32
Styled
Definition at line 38 of file Knob.h.
TreeWidgetItemTypes
enum lmms::gui::TreeWidgetItemTypes
Enumerator
TypeFileItem
TypeDirectoryItem
Definition at line 76 of file FileBrowser.cpp.
Function Documentation
adjustedToPixelSize()
QFont lmms::gui::adjustedToPixelSize (QFont font, int size) inline
Definition at line 39 of file FontHelper.h.
Referenced by lmms::gui::ComboBox::ComboBox(), lmms::gui::CustomTextKnob::CustomTextKnob(), lmms::gui::EffectView::EffectView(), lmms::gui::InstrumentFunctionArpeggioView::InstrumentFunctionArpeggioView(), lmms::gui::InstrumentFunctionNoteStackingView::InstrumentFunctionNoteStackingView(), lmms::gui::InstrumentSoundShapingView::InstrumentSoundShapingView(), lmms::gui::InstrumentTuningView::InstrumentTuningView(), lmms::gui::Knob::Knob(), lmms::gui::MixerChannelView::MixerChannelView(), lmms::gui::TabWidget::TabWidget(), lmms::gui::TempoSyncKnob::TempoSyncKnob(), lmms::gui::LfoGraph::drawInfoText(), lmms::gui::Knob::drawLabel(), lmms::gui::PianoRoll::drawNoteRect(), lmms::gui::LedCheckBox::initUi(), lmms::gui::AutomationEditor::paintEvent(), lmms::gui::EffectView::paintEvent(), lmms::gui::GroupBox::paintEvent(), lmms::gui::LcdFloatSpinBox::paintEvent(), lmms::gui::LcdWidget::paintEvent(), lmms::gui::Oscilloscope::paintEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::PianoView::paintEvent(), lmms::gui::SideBarWidget::paintEvent(), lmms::gui::TabWidget::paintEvent(), lmms::gui::LedCheckBox::paintLegacy(), lmms::gui::Knob::updateFixedSize(), and lmms::gui::LcdWidget::updateSize().
animateScroll()
void lmms::gui::animateScroll (QScrollBar * scrollBar, int newVal, bool smoothScroll) inline static
Definition at line 729 of file SongEditor.cpp.
Referenced by lmms::gui::SongEditor::updatePosition().
computeNoteRange()
int lmms::gui::computeNoteRange (int minKey, int maxKey) static
Definition at line 547 of file MidiClipView.cpp.
Referenced by lmms::gui::MidiClipView::paintEvent().
convertPixmapToGrayScale()
void lmms::gui::convertPixmapToGrayScale (QPixmap & pixMap)
Definition at line 534 of file Knob.cpp.
References i, and j.
Referenced by lmms::gui::Knob::onKnobNumUpdated().
darken()
QLinearGradient lmms::gui::darken (const QLinearGradient & _gradient)
Definition at line 75 of file LmmsStyle.cpp.
Referenced by drawPath().
drawPath()
void lmms::gui::drawPath (QPainter * p, const QPainterPath & path, const QColor & col, const QColor & borderCol, bool dark = false)
Definition at line 91 of file LmmsStyle.cpp.
References darken(), and getGradient().
floatFromClipboard()
float lmms::gui::floatFromClipboard (bool * ok = nullptr) static
Attempt to parse a float from the clipboard.
Definition at line 302 of file AutomatableModelView.cpp.
Referenced by lmms::gui::AutomatableModelView::addDefaultActions(), and lmms::gui::AutomatableModelViewSlots::pasteFromClipboard().
getGradient()
QLinearGradient lmms::gui::getGradient (const QColor & _col, const QRectF & _rect)
Definition at line 47 of file LmmsStyle.cpp.
Referenced by drawPath().
getGUI()
LMMS_EXPORT GuiApplication * lmms::gui::getGUI ()
Definition at line 69 of file GuiApplication.cpp.
References lmms::gui::GuiApplication::instance().
Referenced by lmms::AudioFileDevice::AudioFileDevice(), lmms::gui::AutomationClipView::AutomationClipView(), lmms::gui::ClipView::ClipView(), lmms::gui::ControllerRackView::ControllerRackView(), lmms::gui::ControllerView::ControllerView(), lmms::DataFile::DataFile(), lmms::gui::EffectView::EffectView(), lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow(), lmms::gui::InstrumentTuningView::InstrumentTuningView(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::gui::MidiCCRackView::MidiCCRackView(), lmms::gui::MidiClipView::MidiClipView(), lmms::gui::MixerView::MixerView(), lmms::gui::ProjectNotes::ProjectNotes(), lmms::gui::SampleTrackWindow::SampleTrackWindow(), lmms::gui::SimpleTextFloat::SimpleTextFloat(), lmms::gui::SongEditor::SongEditor(), lmms::gui::TextFloat::TextFloat(), lmms::gui::TimeDisplayWidget::TimeDisplayWidget(), lmms::gui::ToolPluginView::ToolPluginView(), lmms::gui::TrackContentWidget::TrackContentWidget(), lmms::gui::MainWindow::~MainWindow(), lmms::gui::PatternTrackView::~PatternTrackView(), lmms::gui::StringPairDrag::~StringPairDrag(), lmms::gui::ExportProjectDialog::accept(), lmms::MidiClip::addNote(), lmms::gui::SongEditorWindow::adjustUiAfterProjectLoad(), lmms::gui::InstrumentTrackView::assignMixerLine(), lmms::gui::SampleTrackView::assignMixerLine(), lmms::gui::MidiClipView::bulkClearNotesOutOfBounds(), lmms::gui::TrackContentWidget::changePosition(), lmms::Song::clearProject(), lmms::gui::PatternTrackView::clickedTrackLabel(), lmms::gui::PatternTrackView::close(), lmms::gui::Editor::closeEvent(), lmms::gui::InstrumentTrackWindow::closeEvent(), lmms::gui::SampleTrackWindow::closeEvent(), lmms::gui::MixerChannelView::confirmRemoval(), lmms::gui::PianoRoll::constrainNoteLengths(), lmms::Clip::copyStateTo(), lmms::gui::SampleLoader::createBufferFromBase64(), lmms::gui::SampleLoader::createBufferFromFile(), lmms::gui::InstrumentTrackView::createMixerLine(), lmms::gui::SampleTrackView::createMixerLine(), lmms::gui::TemplatesMenu::createNewProjectFromTemplate(), lmms::gui::PianoRoll::cutSelectedNotes(), lmms::gui::PianoRoll::deleteSelectedNotes(), lmms::gui::AutomationClipView::disconnectObject(), lmms::gui::TextFloat::displayMessage(), lmms::gui::ClipView::draggedClipPos(), lmms::gui::AutomationClipView::dropEvent(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), lmms::gui::AutomatableModelViewSlots::editSongGlobalAutomation(), lmms::gui::MainApplication::event(), lmms::gui::AutomatableModelViewSlots::execConnectionDialog(), lmms::gui::MainWindow::exportProject(), lmms::gui::MainWindow::finalize(), lmms::gui::PianoRoll::fitNoteLengths(), lmms::gui::ClipView::getClickedClips(), lmms::gui::FloatModelEditorBase::getValue(), lmms::gui::FileBrowserTreeWidget::handleFile(), lmms::Plugin::instantiate(), lmms::ConfigManager::loadConfigFile(), lmms::DataFile::loadData(), lmms::Song::loadProject(), lmms::TrackContainer::loadSettings(), main(), lmms::gui::MidiClipView::mergeClips(), lmms::gui::MixerChannelLcdSpinBox::mouseDoubleClickEvent(), lmms::gui::ClipView::mouseMoveEvent(), lmms::gui::LcdFloatSpinBox::mouseMoveEvent(), lmms::gui::ClipView::mousePressEvent(), lmms::gui::MidiClipView::mousePressEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::gui::TrackContentWidget::mousePressEvent(), lmms::gui::TrackContentWidget::mouseReleaseEvent(), lmms::gui::MixerChannelView::moveChannelLeft(), lmms::gui::MixerChannelView::moveChannelRight(), lmms::gui::AutomationClipView::openInAutomationEditor(), lmms::gui::PatternClipView::openInPatternEditor(), lmms::gui::MidiClipView::openInPianoRoll(), lmms::gui::RecentProjectsMenu::openProject(), lmms::gui::AutomationClipView::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::TrackContentWidget::paintEvent(), lmms::gui::PianoRoll::pasteNotes(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::gui::AutomationEditor::play(), lmms::InstrumentTrack::play(), lmms::gui::PianoRoll::quantizeNotes(), lmms::gui::ClipView::quantizeSplitPos(), lmms::gui::MainWindow::refocus(), lmms::gui::MixerChannelView::removeChannel(), lmms::gui::MixerChannelView::removeUnusedChannels(), lmms::gui::PianoRoll::reverseNotes(), lmms::ConfigManager::saveConfigFile(), lmms::Song::saveProjectFile(), lmms::gui::FileBrowserTreeWidget::sendToActiveInstrumentTrack(), lmms::gui::Oscilloscope::setActive(), lmms::gui::SampleClipView::setAutomationGhost(), lmms::gui::MidiClipView::setGhostInAutomationEditor(), lmms::gui::MidiClipView::setGhostInPianoRoll(), lmms::gui::PianoRoll::shiftPos(), lmms::gui::PianoRoll::shiftSemiTone(), lmms::gui::TempoSyncBarModelEditor::showCustom(), lmms::gui::TempoSyncKnob::showCustom(), lmms::gui::ExportProjectDialog::startExport(), lmms::gui::SongEditorWindow::stop(), lmms::gui::MainWindow::toggleAutomationEditorWin(), lmms::gui::MainWindow::toggleControllerRack(), lmms::gui::MainWindow::toggleMicrotunerWin(), lmms::gui::MainWindow::toggleMixerWin(), lmms::gui::MainWindow::togglePatternEditorWin(), lmms::gui::MainWindow::togglePianoRollWin(), lmms::gui::MainWindow::toggleProjectNotesWin(), lmms::gui::MainWindow::toggleSongEditorWin(), lmms::gui::InstrumentTrackView::topLevelInstrumentTrackWindow(), lmms::gui::AutomationEditor::update(), lmms::gui::TrackContentWidget::updateBackground(), lmms::MidiClip::updatePatternTrack(), lmms::gui::MainWindow::updatePlayPauseIcons(), lmms::gui::ExportProjectDialog::updateTitleBar(), lmms::gui::MidiClipView::wheelEvent(), and lmms::DataFile::writeFile().
getKeyOffsetFromKeyEvent()
int lmms::gui::getKeyOffsetFromKeyEvent (QKeyEvent * _ke) static
Definition at line 122 of file PianoView.cpp.
References k.
Referenced by lmms::gui::PianoView::getKeyFromKeyEvent().
getNoteString()
QString lmms::gui::getNoteString (int key) static
Definition at line 128 of file PianoRoll.cpp.
References lmms::FirstOctave, lmms::KeysPerOctave, and s_noteStrings.
Referenced by lmms::gui::PianoRoll::drawNoteRect(), and lmms::gui::PianoRoll::paintEvent().
labelWidget()
void lmms::gui::labelWidget (QWidget * w, const QString & txt) inline
Definition at line 76 of file SetupDialog.cpp.
Referenced by lmms::gui::SetupDialog::SetupDialog().
mapToStereoMode()
OutputSettings::StereoMode lmms::gui::mapToStereoMode (int index)
Definition at line 148 of file ExportProjectDialog.cpp.
References lmms::OutputSettings::JointStereo, lmms::OutputSettings::Mono, and lmms::OutputSettings::Stereo.
Referenced by lmms::gui::ExportProjectDialog::startExport().
Variable Documentation
BARS_PER_GROUP
const int lmms::gui::BARS_PER_GROUP = 4
Alternate between a darker and a lighter background color every 4 bars.
Definition at line 51 of file TrackContentWidget.cpp.
Referenced by lmms::gui::TrackContentWidget::updateBackground().
BeatStepButtonOffset
int lmms::gui::BeatStepButtonOffset = 4 constexpr
Definition at line 51 of file MidiClipView.cpp.
Referenced by lmms::gui::MidiClipView::mousePressEvent(), and lmms::gui::MidiClipView::paintEvent().
BLACK_KEY_WIDTH
const int lmms::gui::BLACK_KEY_WIDTH = 41
Definition at line 94 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll().
BUFFERSIZE_RESOLUTION
int lmms::gui::BUFFERSIZE_RESOLUTION = 32 constexpr
Definition at line 74 of file SetupDialog.cpp.
Referenced by lmms::gui::SetupDialog::SetupDialog(), lmms::gui::SetupDialog::resetBufferSize(), and lmms::gui::SetupDialog::setBufferSize().
c_margin
int lmms::gui::c_margin = 2 constexpr
Definition at line 41 of file TrackGrip.cpp.
Referenced by lmms::gui::TrackGrip::TrackGrip(), and lmms::gui::TrackGrip::paintEvent().
CB_ARROW_BTN_WIDTH
const int lmms::gui::CB_ARROW_BTN_WIDTH = 18
Definition at line 45 of file ComboBox.cpp.
Referenced by lmms::gui::ComboBox::contextMenuEvent(), lmms::gui::ComboBox::mousePressEvent(), and lmms::gui::ComboBox::paintEvent().
CD_ENV_KNOBS_LBL_Y
const int lmms::gui::CD_ENV_KNOBS_LBL_Y = 11
Definition at line 41 of file LfoControllerDialog.cpp.
CD_KNOB_X_SPACING
const int lmms::gui::CD_KNOB_X_SPACING = 32
Definition at line 42 of file LfoControllerDialog.cpp.
CD_LFO_AMOUNT_CD_KNOB_X
const int lmms::gui::CD_LFO_AMOUNT_CD_KNOB_X = CD_LFO_SPEED_CD_KNOB_X+CD_KNOB_X_SPACING
Definition at line 51 of file LfoControllerDialog.cpp.
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog().
CD_LFO_BASE_CD_KNOB_X
const int lmms::gui::CD_LFO_BASE_CD_KNOB_X = CD_LFO_SHAPES_X + 68
Definition at line 49 of file LfoControllerDialog.cpp.
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog().
CD_LFO_CD_KNOB_Y
const int lmms::gui::CD_LFO_CD_KNOB_Y = CD_LFO_GRAPH_Y-2
Definition at line 48 of file LfoControllerDialog.cpp.
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog().
CD_LFO_GRAPH_Y
const int lmms::gui::CD_LFO_GRAPH_Y = CD_ENV_KNOBS_LBL_Y+3
Definition at line 47 of file LfoControllerDialog.cpp.
CD_LFO_MULTIPLIER_X
const int lmms::gui::CD_LFO_MULTIPLIER_X = CD_LFO_PHASE_CD_KNOB_X+CD_KNOB_X_SPACING+3
Definition at line 53 of file LfoControllerDialog.cpp.
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog().
CD_LFO_PHASE_CD_KNOB_X
const int lmms::gui::CD_LFO_PHASE_CD_KNOB_X = CD_LFO_AMOUNT_CD_KNOB_X+CD_KNOB_X_SPACING
Definition at line 52 of file LfoControllerDialog.cpp.
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog().
CD_LFO_SHAPES_X
const int lmms::gui::CD_LFO_SHAPES_X = 6
Definition at line 44 of file LfoControllerDialog.cpp.
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog().
CD_LFO_SHAPES_Y
const int lmms::gui::CD_LFO_SHAPES_Y = CD_ENV_KNOBS_LBL_Y + 4
Definition at line 45 of file LfoControllerDialog.cpp.
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog().
CD_LFO_SPEED_CD_KNOB_X
const int lmms::gui::CD_LFO_SPEED_CD_KNOB_X = CD_LFO_BASE_CD_KNOB_X+CD_KNOB_X_SPACING
Definition at line 50 of file LfoControllerDialog.cpp.
Referenced by lmms::gui::LfoControllerDialog::LfoControllerDialog().
DEFAULT_CELL_WIDTH
const int lmms::gui::DEFAULT_CELL_WIDTH = 12
Definition at line 97 of file PianoRoll.cpp.
DEFAULT_KEY_LINE_HEIGHT
const int lmms::gui::DEFAULT_KEY_LINE_HEIGHT = 12
Definition at line 96 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll(), and lmms::gui::PianoRoll::zoomingYChanged().
DEFAULT_PR_PPB
const int lmms::gui::DEFAULT_PR_PPB = DEFAULT_CELL_WIDTH * DefaultStepsPerBar
Definition at line 142 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll(), lmms::gui::PianoRoll::wheelEvent(), and lmms::gui::PianoRoll::zoomingChanged().
DEFAULT_SETTINGS_WIDGET_WIDTH
const int lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH = 260
Definition at line 51 of file TrackView.h.
Referenced by lmms::gui::PatternEditor::PatternEditor(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::SongEditor::SongEditor(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackView::mouseMoveEvent(), lmms::gui::TrackView::mousePressEvent(), lmms::gui::TrackView::resizeEvent(), and lmms::gui::SongEditor::updatePosition().
DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT
const int lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT = 136
Definition at line 55 of file TrackView.h.
Referenced by lmms::gui::PatternEditor::PatternEditor(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::SongEditor::SongEditor(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackView::mouseMoveEvent(), lmms::gui::TrackView::mousePressEvent(), lmms::gui::TrackView::resizeEvent(), and lmms::gui::SongEditor::updatePosition().
FadeDuration
const float lmms::gui::FadeDuration = 300
Definition at line 36 of file FadeButton.cpp.
Referenced by lmms::gui::FadeButton::paintEvent().
GRAPHIC_TAB_HEIGHT
const int lmms::gui::GRAPHIC_TAB_HEIGHT = 17
Definition at line 35 of file TabWidget.h.
Referenced by lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow(), and lmms::gui::TabWidget::TabWidget().
INITIAL_PIANOROLL_HEIGHT
const int lmms::gui::INITIAL_PIANOROLL_HEIGHT = 485
Definition at line 88 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRollWindow::sizeHint().
INITIAL_PIANOROLL_WIDTH
const int lmms::gui::INITIAL_PIANOROLL_WIDTH = 970
Definition at line 87 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRollWindow::sizeHint().
INITIAL_START_KEY
const int lmms::gui::INITIAL_START_KEY = Octave::Octave_4 + Key::C
Definition at line 115 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll(), and lmms::gui::PianoRoll::setCurrentMidiClip().
INSTRUMENT_HEIGHT
const int lmms::gui::INSTRUMENT_HEIGHT = INSTRUMENT_WIDTH
Definition at line 77 of file InstrumentTrackWindow.cpp.
Referenced by lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow().
INSTRUMENT_WIDTH
const int lmms::gui::INSTRUMENT_WIDTH = 254
Definition at line 76 of file InstrumentTrackWindow.cpp.
KEY_AREA_MIN_HEIGHT
const int lmms::gui::KEY_AREA_MIN_HEIGHT = DEFAULT_KEY_LINE_HEIGHT * 10
Definition at line 102 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::mouseMoveEvent(), and lmms::gui::PianoRoll::paintEvent().
LABEL_TEXT_SIZE
const int lmms::gui::LABEL_TEXT_SIZE = 8
The height of the key label text.
Definition at line 74 of file PianoView.cpp.
Referenced by lmms::gui::PianoView::paintEvent().
MIN_PIXELS_BETWEEN_LINES
const int lmms::gui::MIN_PIXELS_BETWEEN_LINES = 4
Definition at line 54 of file TrackContentWidget.cpp.
Referenced by lmms::gui::TrackContentWidget::updateBackground().
names
const auto lmms::gui::names static
Initial value:
= std::array<QString, 3>
{
    "led_yellow", "led_green", "led_red"
}
Definition at line 39 of file LedCheckBox.cpp.
Referenced by lmms::gui::LedCheckBox::initUi().
NOTE_EDIT_LINE_WIDTH
const int lmms::gui::NOTE_EDIT_LINE_WIDTH = 3
Definition at line 112 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::mousePressEvent(), and lmms::gui::PianoRoll::paintEvent().
NOTE_EDIT_MIN_HEIGHT
const int lmms::gui::NOTE_EDIT_MIN_HEIGHT = 50
Definition at line 101 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::mouseMoveEvent().
NOTE_EDIT_RESIZE_BAR
const int lmms::gui::NOTE_EDIT_RESIZE_BAR = 6
Definition at line 100 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::noteEditTop(), and lmms::gui::PianoRoll::paintEvent().
NUM_EVEN_LENGTHS
const int lmms::gui::NUM_EVEN_LENGTHS = 6
Definition at line 118 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll().
NUM_TRIPLET_LENGTHS
const int lmms::gui::NUM_TRIPLET_LENGTHS = 5
Definition at line 119 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll().
PIANO_BASE
const int lmms::gui::PIANO_BASE = 11
The height of the root note display.
Definition at line 69 of file PianoView.cpp.
Referenced by lmms::gui::PianoView::PianoView(), lmms::gui::PianoView::contextMenuEvent(), lmms::gui::PianoView::getKeyFromMouse(), lmms::gui::PianoView::mouseMoveEvent(), lmms::gui::PianoView::mousePressEvent(), and lmms::gui::PianoView::paintEvent().
PIANO_HEIGHT
const int lmms::gui::PIANO_HEIGHT = 80
Definition at line 78 of file InstrumentTrackWindow.cpp.
Referenced by lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow().
PIANO_X
const int lmms::gui::PIANO_X = 0
Definition at line 91 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::paintEvent().
PR_BOTTOM_MARGIN
const int lmms::gui::PR_BOTTOM_MARGIN = SCROLLBAR_SIZE
Definition at line 103 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll(), lmms::gui::PianoRoll::keyAreaBottom(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::noteEditBottom(), and lmms::gui::PianoRoll::paintEvent().
PR_RIGHT_MARGIN
const int lmms::gui::PR_RIGHT_MARGIN = SCROLLBAR_SIZE
Definition at line 105 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::noteEditRight(), and lmms::gui::PianoRoll::paintEvent().
PR_TOP_MARGIN
const int lmms::gui::PR_TOP_MARGIN = 18
Definition at line 104 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll(), lmms::gui::PianoRoll::drawDetuningInfo(), lmms::gui::PianoRoll::keyAreaTop(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::gui::PianoRoll::noteUnderMouse(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::PianoRoll::updateScrollbars(), and lmms::gui::PianoRoll::updateYScroll().
PW_BLACK_KEY_HEIGHT
const int lmms::gui::PW_BLACK_KEY_HEIGHT = 38
The height of a black key.
Definition at line 73 of file PianoView.cpp.
Referenced by lmms::gui::PianoView::getKeyFromMouse(), lmms::gui::PianoView::getKeyHeight(), and lmms::gui::PianoView::mouseMoveEvent().
PW_BLACK_KEY_WIDTH
const int lmms::gui::PW_BLACK_KEY_WIDTH = 8
The width of a black key.
Definition at line 71 of file PianoView.cpp.
Referenced by lmms::gui::PianoView::PianoView(), lmms::gui::PianoView::getKeyFromMouse(), and lmms::gui::PianoView::getKeyWidth().
PW_WHITE_KEY_HEIGHT
const int lmms::gui::PW_WHITE_KEY_HEIGHT = 57
The height of a white key.
Definition at line 72 of file PianoView.cpp.
Referenced by lmms::gui::PianoView::PianoView(), lmms::gui::PianoView::getKeyHeight(), and lmms::gui::PianoView::mouseMoveEvent().
PW_WHITE_KEY_WIDTH
const int lmms::gui::PW_WHITE_KEY_WIDTH = 10
The width of a white key.
Definition at line 70 of file PianoView.cpp.
Referenced by lmms::gui::PianoView::PianoView(), lmms::gui::PianoView::getKeyFromMouse(), lmms::gui::PianoView::getKeyWidth(), lmms::gui::PianoView::getKeyX(), lmms::gui::PianoView::paintEvent(), and lmms::gui::PianoView::resizeEvent().
Quantizations
const int lmms::gui::Quantizations[] static
Initial value:
= {
    1, 2, 4, 8, 16, 32, 64,
    3, 6, 12, 24, 48, 96, 192
}
Definition at line 36 of file Editor.h.
Referenced by lmms::gui::AutomationEditor::AutomationEditor(), lmms::gui::PianoRoll::PianoRoll(), lmms::gui::PianoRoll::quantization(), and lmms::gui::AutomationEditor::setQuantization().
RESIZE_AREA_WIDTH
const int lmms::gui::RESIZE_AREA_WIDTH = 9
Definition at line 109 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::mouseMoveEvent(), and lmms::gui::PianoRoll::mousePressEvent().
RESIZE_GRIP_WIDTH
const int lmms::gui::RESIZE_GRIP_WIDTH = 4
The width of the resize grip in pixels.
Definition at line 59 of file ClipView.cpp.
Referenced by lmms::gui::ClipView::mousePressEvent(), and lmms::gui::ClipView::updateCursor().
s_noteStrings
std::array<QString, 12> lmms::gui::s_noteStrings static
Initial value:
{
    "C", "C\u266F / D\u266D", "D", "D\u266F / E\u266D", "E", "F", "F\u266F / G\u266D",
    "G", "G\u266F / A\u266D", "A", "A\u266F / B\u266D", "B"
}
Definition at line 123 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll(), and getNoteString().
SCROLLBAR_SIZE
const int lmms::gui::SCROLLBAR_SIZE = 12
Definition at line 90 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::noteUnderMouse(), lmms::gui::PianoRoll::updateScrollbars(), and lmms::gui::PianoRoll::updateYScroll().
TEXT_TAB_HEIGHT
const int lmms::gui::TEXT_TAB_HEIGHT = 14
Definition at line 34 of file TabWidget.h.
Referenced by lmms::gui::TabWidget::TabWidget().
TRACK_OP_WIDTH
const int lmms::gui::TRACK_OP_WIDTH = 78
Definition at line 52 of file TrackView.h.
Referenced by lmms::gui::PatternEditor::PatternEditor(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::SongEditor::SongEditor(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackView::mouseMoveEvent(), lmms::gui::TrackView::mousePressEvent(), lmms::gui::TrackView::resizeEvent(), and lmms::gui::SongEditor::updatePosition().
TRACK_OP_WIDTH_COMPACT
const int lmms::gui::TRACK_OP_WIDTH_COMPACT = TRACK_OP_WIDTH
Definition at line 56 of file TrackView.h.
Referenced by lmms::gui::PatternEditor::PatternEditor(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::SongEditor::SongEditor(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackView::mouseMoveEvent(), lmms::gui::TrackView::mousePressEvent(), lmms::gui::TrackView::resizeEvent(), and lmms::gui::SongEditor::updatePosition().
WHITE_KEY_WIDTH
const int lmms::gui::WHITE_KEY_WIDTH = 64
Definition at line 93 of file PianoRoll.cpp.
Referenced by lmms::gui::PianoRoll::PianoRoll().
WhiteKeys
auto lmms::gui::WhiteKeys
Initial value:
= std::array
{
    Key::C, Key::D, Key::E, Key::F, Key::G, Key::A, Key::H
}
The scale of C Major - white keys only.
Definition at line 64 of file PianoView.cpp.
Referenced by lmms::gui::PianoView::getKeyFromMouse(), and lmms::gui::PianoView::pianoScrolled().