LMMS: lmms::gui::PeakControllerDialog Class Reference
lmms::gui::PeakControllerDialog Class Reference
#include <PeakController.h>
Public Member Functions
PeakControllerDialog (Controller *_controller, QWidget *_parent)
~PeakControllerDialog () override=default
Public Member Functions inherited from lmms::gui::ControllerDialog
ControllerDialog (Controller *_controller, QWidget *_parent)
~ControllerDialog () override=default
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *_me) override
void modelChanged () override
void paintEvent (QPaintEvent *_pe) override
Protected Member Functions inherited from lmms::gui::ControllerDialog
void closeEvent (QCloseEvent *_ce) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Protected Attributes
PeakController * m_peakController
Additional Inherited Members
Signals inherited from lmms::gui::ControllerDialog
void closed ()
Detailed Description
Definition at line 89 of file PeakController.h.
Constructor & Destructor Documentation
PeakControllerDialog()
lmms::gui::PeakControllerDialog::PeakControllerDialog (Controller * _controller, QWidget * _parent)
Definition at line 39 of file PeakControllerDialog.cpp.
References lmms::gui::ControllerDialog::ControllerDialog(), lmms::embed::getIconPixmap(), and lmms::gui::ModelView::setModel().
~PeakControllerDialog()
lmms::gui::PeakControllerDialog::~PeakControllerDialog () override default
Member Function Documentation
contextMenuEvent()
void lmms::gui::PeakControllerDialog::contextMenuEvent (QContextMenuEvent * _me) override protected
Definition at line 67 of file PeakControllerDialog.cpp.
modelChanged()
void lmms::gui::PeakControllerDialog::modelChanged () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 81 of file PeakControllerDialog.cpp.
References lmms::gui::ModelView::castModel(), and m_peakController.
paintEvent()
void lmms::gui::PeakControllerDialog::paintEvent (QPaintEvent * _pe) override protected
Definition at line 74 of file PeakControllerDialog.cpp.
Member Data Documentation
m_peakController
PeakController* lmms::gui::PeakControllerDialog::m_peakController protected
Definition at line 101 of file PeakController.h.
Referenced by modelChanged().
The documentation for this class was generated from the following files:
include/PeakController.h
src/gui/PeakControllerDialog.cpp