LMMS: Jack::JackClientNotificationRequest Struct Reference
Jack::JackClientNotificationRequest Struct Reference
ClientNotification request.
#include <JackRequest.h>
Public Member Functions
JackClientNotificationRequest ()
JackClientNotificationRequest (int refnum, int notify, int value)
int Read (detail::JackChannelTransactionInterface *trans)
int Size ()
int Write (detail::JackChannelTransactionInterface *trans)
Public Member Functions inherited from Jack::JackRequest
JackRequest ()
JackRequest (RequestType type)
virtual ~JackRequest ()
virtual int Write (detail::JackChannelTransactionInterface *trans, int size)
Public Attributes
int fNotify
int fRefNum
int fValue
Public Attributes inherited from Jack::JackRequest
int fSize
RequestType fType
Additional Inherited Members
Public Types inherited from Jack::JackRequest
enum RequestType {
kRegisterPort = 1 ,
kUnRegisterPort = 2 ,
kConnectPorts = 3 ,
kDisconnectPorts = 4 ,
kSetTimeBaseClient = 5 ,
kActivateClient = 6 ,
kDeactivateClient = 7 ,
kDisconnectPort = 8 ,
kSetClientCapabilities = 9 ,
kGetPortConnections = 10 ,
kGetPortNConnections = 11 ,
kReleaseTimebase = 12 ,
kSetTimebaseCallback = 13 ,
kSetBufferSize = 20 ,
kSetFreeWheel = 21 ,
kClientCheck = 22 ,
kClientOpen = 23 ,
kClientClose = 24 ,
kConnectNamePorts = 25 ,
kDisconnectNamePorts = 26 ,
kGetInternalClientName = 27 ,
kInternalClientHandle = 28 ,
kInternalClientLoad = 29 ,
kInternalClientUnload = 30 ,
kPortRename = 31 ,
kNotification = 32 ,
kSessionNotify = 33 ,
kSessionReply = 34 ,
kGetClientByUUID = 35 ,
kReserveClientName = 36 ,
kGetUUIDByClient = 37 ,
kClientHasSessionCallback = 38 ,
kComputeTotalLatencies = 39 ,
kPropertyChangeNotify = 40
}
Detailed Description
ClientNotification request.
Definition at line 1217 of file JackRequest.h.
Constructor & Destructor Documentation
JackClientNotificationRequest() [1/2]
Jack::JackClientNotificationRequest::JackClientNotificationRequest () inline
Definition at line 1224 of file JackRequest.h.
References fNotify, fRefNum, and fValue.
JackClientNotificationRequest() [2/2]
Jack::JackClientNotificationRequest::JackClientNotificationRequest (int refnum, int notify, int value) inline
Definition at line 1226 of file JackRequest.h.
References Jack::JackRequest::JackRequest(), fNotify, fRefNum, fValue, and Jack::JackRequest::kNotification.
Member Function Documentation
Read()
int Jack::JackClientNotificationRequest::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackRequest.
Definition at line 1230 of file JackRequest.h.
References CheckRes, CheckSize, fNotify, fRefNum, fValue, and Jack::detail::JackChannelTransactionInterface::Read().
Size()
int Jack::JackClientNotificationRequest::Size () inline virtual
Reimplemented from Jack::JackRequest.
Definition at line 1248 of file JackRequest.h.
Referenced by Write().
Write()
int Jack::JackClientNotificationRequest::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackRequest.
Definition at line 1239 of file JackRequest.h.
References CheckRes, fNotify, fRefNum, fValue, Size(), Jack::detail::JackChannelTransactionInterface::Write(), and Jack::JackRequest::Write().
Referenced by Jack::JackSocketServerNotifyChannel::Notify(), and Jack::JackWinNamedPipeServerNotifyChannel::Notify().
Member Data Documentation
fNotify
int Jack::JackClientNotificationRequest::fNotify
Definition at line 1221 of file JackRequest.h.
Referenced by JackClientNotificationRequest(), JackClientNotificationRequest(), Jack::JackRequestDecoder::HandleRequest(), Read(), and Write().
fRefNum
int Jack::JackClientNotificationRequest::fRefNum
Definition at line 1220 of file JackRequest.h.
Referenced by JackClientNotificationRequest(), JackClientNotificationRequest(), Jack::JackRequestDecoder::HandleRequest(), Read(), and Write().
fValue
int Jack::JackClientNotificationRequest::fValue
Definition at line 1222 of file JackRequest.h.
Referenced by JackClientNotificationRequest(), JackClientNotificationRequest(), Jack::JackRequestDecoder::HandleRequest(), Read(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h