LMMS: Jack::JackWinNamedPipeClientChannel Class Reference
Jack::JackWinNamedPipeClientChannel Class Reference
JackClientChannel using pipes.
#include <JackWinNamedPipeClientChannel.h>
Public Member Functions
JackWinNamedPipeClientChannel ()
virtual ~JackWinNamedPipeClientChannel ()
void Close ()
bool Execute ()
bool Init ()
Called once when the thread is started.
bool IsChannelThread ()
int Open (const char *server_name, const char *name, jack_uuid_t uuid, char *name_res, JackClient *client, jack_options_t options, jack_status_t *status)
int Start ()
void Stop ()
Public Member Functions inherited from Jack::JackGenericClientChannel
JackGenericClientChannel ()
virtual ~JackGenericClientChannel ()
void ClientActivate (int refnum, int is_real_time, int *result)
void ClientCheck (const char *name, jack_uuid_t uuid, char *name_res, int protocol, int options, int *status, int *result, int open)
void ClientClose (int refnum, int *result)
void ClientDeactivate (int refnum, int *result)
void ClientHasSessionCallback (const char *client_name, int *result)
void ClientOpen (const char *name, int pid, jack_uuid_t uuid, int *shared_engine, int *shared_client, int *shared_graph, int *result)
void ComputeTotalLatencies (int *result)
void GetClientNameForUUID (int refnum, const char *uuid, char *name_res, int *result)
void GetInternalClientName (int refnum, int int_ref, char *name_res, int *result)
void GetUUIDForClientName (int refnum, const char *client_name, char *uuid_res, int *result)
void InternalClientHandle (int refnum, const char *client_name, int *status, int *int_ref, int *result)
void InternalClientLoad (int refnum, const char *client_name, const char *so_name, const char *objet_data, int options, int *status, int *int_ref, jack_uuid_t uuid, int *result)
void InternalClientUnload (int refnum, int int_ref, int *status, int *result)
void PortConnect (int refnum, const char *src, const char *dst, int *result)
void PortConnect (int refnum, jack_port_id_t src, jack_port_id_t dst, int *result)
void PortDisconnect (int refnum, const char *src, const char *dst, int *result)
void PortDisconnect (int refnum, jack_port_id_t src, jack_port_id_t dst, int *result)
void PortRegister (int refnum, const char *name, const char *type, unsigned int flags, unsigned int buffer_size, jack_port_id_t *port_index, int *result)
void PortRename (int refnum, jack_port_id_t port, const char *name, int *result)
void PortUnRegister (int refnum, jack_port_id_t port_index, int *result)
void PropertyChangeNotify (jack_uuid_t subject, const char *key, jack_property_change_t change, int *result)
void ReleaseTimebase (int refnum, int *result)
void ReserveClientName (int refnum, const char *client_name, const char *uuid, int *result)
int ServerCheck (const char *server_name)
void SessionNotify (int refnum, const char *target, jack_session_event_type_t type, const char *path, jack_session_command_t **result)
void SessionReply (int refnum, int *result)
void SetBufferSize (jack_nframes_t buffer_size, int *result)
void SetFreewheel (int onoff, int *result)
void SetTimebaseCallback (int refnum, int conditional, int *result)
Public Member Functions inherited from Jack::detail::JackClientChannelInterface
JackClientChannelInterface ()
virtual ~JackClientChannelInterface ()
virtual void ClientOpen (const char *name, int *ref, JackEngineControl **shared_engine, JackGraphManager **shared_manager, JackClientInterface *client, int *result)
Private Attributes
JackClient * fClient
JackWinNamedPipeServer fNotificationListenPipe
JackThread fThread
Additional Inherited Members
Protected Member Functions inherited from Jack::JackGenericClientChannel
void ServerAsyncCall (JackRequest *req, JackResult *res, int *result)
void ServerSyncCall (JackRequest *req, JackResult *res, int *result)
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Protected Attributes inherited from Jack::JackGenericClientChannel
detail::JackClientRequestInterface * fRequest
Detailed Description
JackClientChannel using pipes.
Definition at line 38 of file JackWinNamedPipeClientChannel.h.
Constructor & Destructor Documentation
JackWinNamedPipeClientChannel()
Jack::JackWinNamedPipeClientChannel::JackWinNamedPipeClientChannel ()
Definition at line 30 of file JackWinNamedPipeClientChannel.cpp.
References Jack::JackGenericClientChannel::JackGenericClientChannel(), Jack::JackGenericClientChannel::fRequest, and fThread.
~JackWinNamedPipeClientChannel()
Jack::JackWinNamedPipeClientChannel::~JackWinNamedPipeClientChannel () virtual
Definition at line 36 of file JackWinNamedPipeClientChannel.cpp.
References Jack::JackGenericClientChannel::fRequest.
Member Function Documentation
Close()
void Jack::JackWinNamedPipeClientChannel::Close () virtual
Reimplemented from Jack::JackGenericClientChannel.
Definition at line 89 of file JackWinNamedPipeClientChannel.cpp.
References fNotificationListenPipe, Jack::JackGenericClientChannel::fRequest, and fThread.
Execute()
bool Jack::JackWinNamedPipeClientChannel::Execute () virtual
Implements Jack::JackRunnableInterface.
Definition at line 134 of file JackWinNamedPipeClientChannel.cpp.
References fClient, Jack::JackClientNotification::fMessage, Jack::JackClientNotification::fName, fNotificationListenPipe, Jack::JackClientNotification::fNotify, Jack::JackClientNotification::fRefNum, Jack::JackGenericClientChannel::fRequest, Jack::JackResult::fResult, Jack::JackClientNotification::fSync, Jack::JackClientNotification::fValue1, Jack::JackClientNotification::fValue2, jack_error, JACK_SERVER_FAILURE, JackFailure, JackServerError, Jack::JackClientNotification::Read(), and Jack::JackResult::Write().
Init()
bool Jack::JackWinNamedPipeClientChannel::Init () virtual
Called once when the thread is started.
Reimplemented from Jack::JackRunnableInterface.
Definition at line 117 of file JackWinNamedPipeClientChannel.cpp.
References fNotificationListenPipe, Jack::JackGlobals::fNotificationThread, jack_error, jack_log(), and jack_tls_set().
IsChannelThread()
bool Jack::JackWinNamedPipeClientChannel::IsChannelThread () inline virtual
Reimplemented from Jack::detail::JackClientChannelInterface.
Definition at line 62 of file JackWinNamedPipeClientChannel.h.
References fThread.
Open()
int Jack::JackWinNamedPipeClientChannel::Open (const char * server_name, const char * name, jack_uuid_t uuid, char * name_res, JackClient * client, jack_options_t options, jack_status_t * status) virtual
Reimplemented from Jack::JackGenericClientChannel.
Definition at line 41 of file JackWinNamedPipeClientChannel.cpp.
References client(), Jack::JackGenericClientChannel::ClientCheck(), fClient, fNotificationListenPipe, Jack::JackGenericClientChannel::fRequest, Jack::JackGlobals::fServerRunning, jack_client_dir, jack_error, jack_log(), JACK_PROTOCOL_VERSION, jack_server_dir, JackVersionError, and server_name.
Start()
int Jack::JackWinNamedPipeClientChannel::Start () virtual
Reimplemented from Jack::JackGenericClientChannel.
Definition at line 97 of file JackWinNamedPipeClientChannel.cpp.
References fThread, jack_error, and jack_log().
Stop()
void Jack::JackWinNamedPipeClientChannel::Stop () virtual
Reimplemented from Jack::JackGenericClientChannel.
Definition at line 111 of file JackWinNamedPipeClientChannel.cpp.
References fThread, and jack_log().
Member Data Documentation
fClient
JackClient* Jack::JackWinNamedPipeClientChannel::fClient private
Definition at line 45 of file JackWinNamedPipeClientChannel.h.
Referenced by Execute(), and Open().
fNotificationListenPipe
JackWinNamedPipeServer Jack::JackWinNamedPipeClientChannel::fNotificationListenPipe private
Definition at line 43 of file JackWinNamedPipeClientChannel.h.
Referenced by Close(), Execute(), Init(), and Open().
fThread
JackThread Jack::JackWinNamedPipeClientChannel::fThread private
Definition at line 44 of file JackWinNamedPipeClientChannel.h.
Referenced by JackWinNamedPipeClientChannel(), Close(), IsChannelThread(), Start(), and Stop().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinNamedPipeClientChannel.h
src/3rdparty/jack2/windows/JackWinNamedPipeClientChannel.cpp