LMMS: lmms::gui::GuiApplication Class Reference
lmms::gui::GuiApplication Class Reference
#include <GuiApplication.h>
Public Slots
void displayInitProgress (const QString &msg)
Public Member Functions
GuiApplication ()
~GuiApplication () override
AutomationEditorWindow * automationEditor ()
void createSocketNotifier ()
ControllerRackView * getControllerRackView ()
MicrotunerConfig * getMicrotunerConfig ()
ProjectNotes * getProjectNotes ()
MainWindow * mainWindow ()
MixerView * mixerView ()
PatternEditorWindow * patternEditor ()
PianoRollWindow * pianoRoll ()
SongEditorWindow * songEditor ()
Static Public Member Functions
static GuiApplication * instance ()
static bool isWayland ()
static void sigintHandler (int)
Called from main when SIGINT is fired.
Static Public Attributes
static int s_sigintFd [2]
File descriptors for unix socketpair, used to receive SIGINT.
Private Slots
void childDestroyed (QObject *obj)
void sigintOccurred ()
Private Attributes
AutomationEditorWindow * m_automationEditor
ControllerRackView * m_controllerRackView
QLabel * m_loadingProgressLabel
MainWindow * m_mainWindow
MicrotunerConfig * m_microtunerConfig
MixerView * m_mixerView
PatternEditorWindow * m_patternEditor
PianoRollWindow * m_pianoRoll
ProjectNotes * m_projectNotes
QSocketNotifier * m_sigintNotifier
SongEditorWindow * m_songEditor
Static Private Attributes
static GuiApplication * s_instance = nullptr
Detailed Description
Definition at line 49 of file GuiApplication.h.
Constructor & Destructor Documentation
GuiApplication()
lmms::gui::GuiApplication::GuiApplication () explicit
Definition at line 89 of file GuiApplication.cpp.
References childDestroyed(), createSocketNotifier(), lmms::ConfigManager::createWorkingDir(), displayInitProgress(), lmms::embed::getIconPixmap(), lmms::Engine::getSong(), lmms::Engine::init(), lmms::ConfigManager::inst(), lmms::Engine::inst(), m_automationEditor, m_controllerRackView, m_loadingProgressLabel, m_mainWindow, m_microtunerConfig, m_mixerView, m_patternEditor, m_pianoRoll, m_projectNotes, m_songEditor, lmms::Engine::mixer(), lmms::Engine::patternStore(), s_instance, and lmms::gui::LmmsStyle::s_palette.
Referenced by instance().
~GuiApplication()
lmms::gui::GuiApplication::~GuiApplication () override
Definition at line 201 of file GuiApplication.cpp.
References s_instance.
Member Function Documentation
automationEditor()
AutomationEditorWindow * lmms::gui::GuiApplication::automationEditor () inline
Definition at line 72 of file GuiApplication.h.
References m_automationEditor.
Referenced by lmms::gui::MainWindow::~MainWindow(), lmms::Song::clearProject(), lmms::Clip::copyStateTo(), lmms::gui::AutomationClipView::disconnectObject(), lmms::gui::AutomationClipView::dropEvent(), lmms::gui::AutomatableModelViewSlots::editSongGlobalAutomation(), lmms::gui::MainWindow::finalize(), lmms::Song::loadProject(), lmms::gui::AutomationClipView::openInAutomationEditor(), lmms::gui::AutomationClipView::paintEvent(), lmms::Song::saveProjectFile(), lmms::gui::SampleClipView::setAutomationGhost(), lmms::gui::MidiClipView::setGhostInAutomationEditor(), and lmms::gui::MainWindow::updatePlayPauseIcons().
childDestroyed
void lmms::gui::GuiApplication::childDestroyed (QObject * obj) private slot
Definition at line 217 of file GuiApplication.cpp.
References m_automationEditor, m_controllerRackView, m_mainWindow, m_microtunerConfig, m_mixerView, m_patternEditor, m_pianoRoll, m_projectNotes, and m_songEditor.
Referenced by GuiApplication().
createSocketNotifier()
void lmms::gui::GuiApplication::createSocketNotifier ()
Definition at line 278 of file GuiApplication.cpp.
References activated, m_sigintNotifier, s_sigintFd, and sigintOccurred().
Referenced by GuiApplication().
displayInitProgress
void lmms::gui::GuiApplication::displayInitProgress (const QString & msg) slot
Definition at line 207 of file GuiApplication.cpp.
References m_loadingProgressLabel.
Referenced by GuiApplication().
getControllerRackView()
ControllerRackView * lmms::gui::GuiApplication::getControllerRackView () inline
Definition at line 73 of file GuiApplication.h.
References m_controllerRackView.
Referenced by lmms::Song::loadProject(), and lmms::Song::saveProjectFile().
getMicrotunerConfig()
MicrotunerConfig * lmms::gui::GuiApplication::getMicrotunerConfig () inline
Definition at line 71 of file GuiApplication.h.
References m_microtunerConfig.
getProjectNotes()
ProjectNotes * lmms::gui::GuiApplication::getProjectNotes () inline
Definition at line 70 of file GuiApplication.h.
References m_projectNotes.
Referenced by lmms::Song::clearProject(), lmms::Song::loadProject(), and lmms::Song::saveProjectFile().
instance()
GuiApplication * lmms::gui::GuiApplication::instance () static
Definition at line 77 of file GuiApplication.cpp.
References GuiApplication(), and s_instance.
Referenced by lmms::gui::getGUI(), and lmms::gui::AutomationEditor::paintEvent().
isWayland()
bool lmms::gui::GuiApplication::isWayland () static
Definition at line 82 of file GuiApplication.cpp.
mainWindow()
MainWindow * lmms::gui::GuiApplication::mainWindow () inline
Definition at line 65 of file GuiApplication.h.
References m_mainWindow.
Referenced by lmms::gui::ControllerRackView::ControllerRackView(), lmms::gui::ControllerView::ControllerView(), lmms::gui::EffectView::EffectView(), lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::gui::MidiCCRackView::MidiCCRackView(), lmms::gui::MixerView::MixerView(), lmms::gui::ProjectNotes::ProjectNotes(), lmms::gui::SampleTrackWindow::SampleTrackWindow(), lmms::gui::SongEditor::SongEditor(), lmms::gui::ToolPluginView::ToolPluginView(), lmms::gui::StringPairDrag::~StringPairDrag(), lmms::gui::ExportProjectDialog::accept(), lmms::gui::SongEditorWindow::adjustUiAfterProjectLoad(), lmms::gui::PatternTrackView::clickedTrackLabel(), lmms::gui::Editor::closeEvent(), lmms::gui::TextFloat::displayMessage(), lmms::gui::PatternClipView::openInPatternEditor(), lmms::gui::RecentProjectsMenu::openProject(), lmms::gui::FileBrowserTreeWidget::sendToActiveInstrumentTrack(), lmms::gui::TempoSyncBarModelEditor::showCustom(), lmms::gui::TempoSyncKnob::showCustom(), and lmms::gui::ExportProjectDialog::updateTitleBar().
mixerView()
MixerView * lmms::gui::GuiApplication::mixerView () inline
Definition at line 66 of file GuiApplication.h.
References m_mixerView.
Referenced by lmms::gui::InstrumentTrackView::assignMixerLine(), lmms::gui::SampleTrackView::assignMixerLine(), lmms::Song::clearProject(), lmms::gui::InstrumentTrackView::createMixerLine(), lmms::gui::SampleTrackView::createMixerLine(), lmms::Song::loadProject(), lmms::gui::MixerChannelLcdSpinBox::mouseDoubleClickEvent(), lmms::gui::MixerChannelView::moveChannelLeft(), lmms::gui::MixerChannelView::moveChannelRight(), lmms::gui::MixerChannelView::removeChannel(), and lmms::gui::MixerChannelView::removeUnusedChannels().
patternEditor()
PatternEditorWindow * lmms::gui::GuiApplication::patternEditor () inline
Definition at line 68 of file GuiApplication.h.
References m_patternEditor.
Referenced by lmms::gui::PatternTrackView::~PatternTrackView(), lmms::Song::clearProject(), lmms::gui::PatternTrackView::close(), lmms::gui::MainWindow::finalize(), and lmms::gui::MainWindow::updatePlayPauseIcons().
pianoRoll()
PianoRollWindow * lmms::gui::GuiApplication::pianoRoll () inline
Definition at line 69 of file GuiApplication.h.
References m_pianoRoll.
Referenced by lmms::gui::MainWindow::~MainWindow(), lmms::Song::clearProject(), lmms::gui::MainWindow::finalize(), lmms::Song::loadProject(), lmms::gui::MidiClipView::mousePressEvent(), lmms::gui::MidiClipView::openInPianoRoll(), lmms::gui::MidiClipView::paintEvent(), lmms::Song::saveProjectFile(), lmms::gui::MidiClipView::setGhostInPianoRoll(), lmms::gui::SongEditorWindow::stop(), lmms::gui::AutomationEditor::update(), lmms::MidiClip::updatePatternTrack(), lmms::gui::MainWindow::updatePlayPauseIcons(), and lmms::gui::MidiClipView::wheelEvent().
sigintHandler()
void lmms::gui::GuiApplication::sigintHandler (int) static
Called from main when SIGINT is fired.
Unix signal handlers can only call async-signal-safe functions: write(fd) --> QSocketNotifier --> SLOT sigintOccurred()
See https://doc.qt.io/qt-6/unix-signals.html
Definition at line 266 of file GuiApplication.cpp.
References s_sigintFd.
Referenced by main().
sigintOccurred
void lmms::gui::GuiApplication::sigintOccurred () private slot
Definition at line 296 of file GuiApplication.cpp.
References m_sigintNotifier.
Referenced by createSocketNotifier().
songEditor()
SongEditorWindow * lmms::gui::GuiApplication::songEditor () inline
Definition at line 67 of file GuiApplication.h.
References m_songEditor.
Referenced by lmms::gui::MainWindow::~MainWindow(), lmms::gui::MidiClipView::bulkClearNotesOutOfBounds(), lmms::Song::clearProject(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::MainWindow::finalize(), lmms::gui::MidiClipView::mergeClips(), lmms::gui::TrackContentWidget::mousePressEvent(), lmms::gui::TrackContentWidget::mouseReleaseEvent(), lmms::gui::TrackContentWidget::pasteSelection(), lmms::gui::TrackContentWidget::updateBackground(), and lmms::gui::MainWindow::updatePlayPauseIcons().
Member Data Documentation
m_automationEditor
AutomationEditorWindow* lmms::gui::GuiApplication::m_automationEditor private
Definition at line 91 of file GuiApplication.h.
Referenced by GuiApplication(), automationEditor(), and childDestroyed().
m_controllerRackView
ControllerRackView* lmms::gui::GuiApplication::m_controllerRackView private
Definition at line 96 of file GuiApplication.h.
Referenced by GuiApplication(), childDestroyed(), and getControllerRackView().
m_loadingProgressLabel
QLabel* lmms::gui::GuiApplication::m_loadingProgressLabel private
Definition at line 97 of file GuiApplication.h.
Referenced by GuiApplication(), and displayInitProgress().
m_mainWindow
MainWindow* lmms::gui::GuiApplication::m_mainWindow private
Definition at line 88 of file GuiApplication.h.
Referenced by GuiApplication(), childDestroyed(), and mainWindow().
m_microtunerConfig
MicrotunerConfig* lmms::gui::GuiApplication::m_microtunerConfig private
Definition at line 95 of file GuiApplication.h.
Referenced by GuiApplication(), childDestroyed(), and getMicrotunerConfig().
m_mixerView
MixerView* lmms::gui::GuiApplication::m_mixerView private
Definition at line 89 of file GuiApplication.h.
Referenced by GuiApplication(), childDestroyed(), and mixerView().
m_patternEditor
PatternEditorWindow* lmms::gui::GuiApplication::m_patternEditor private
Definition at line 92 of file GuiApplication.h.
Referenced by GuiApplication(), childDestroyed(), and patternEditor().
m_pianoRoll
PianoRollWindow* lmms::gui::GuiApplication::m_pianoRoll private
Definition at line 93 of file GuiApplication.h.
Referenced by GuiApplication(), childDestroyed(), and pianoRoll().
m_projectNotes
ProjectNotes* lmms::gui::GuiApplication::m_projectNotes private
Definition at line 94 of file GuiApplication.h.
Referenced by GuiApplication(), childDestroyed(), and getProjectNotes().
m_sigintNotifier
QSocketNotifier* lmms::gui::GuiApplication::m_sigintNotifier private
Definition at line 98 of file GuiApplication.h.
Referenced by createSocketNotifier(), and sigintOccurred().
m_songEditor
SongEditorWindow* lmms::gui::GuiApplication::m_songEditor private
Definition at line 90 of file GuiApplication.h.
Referenced by GuiApplication(), childDestroyed(), and songEditor().
s_instance
GuiApplication * lmms::gui::GuiApplication::s_instance = nullptr static private
Definition at line 86 of file GuiApplication.h.
Referenced by GuiApplication(), ~GuiApplication(), and instance().
s_sigintFd
int lmms::gui::GuiApplication::s_sigintFd[2] inline static
File descriptors for unix socketpair, used to receive SIGINT.
Definition at line 76 of file GuiApplication.h.
Referenced by createSocketNotifier(), and sigintHandler().
The documentation for this class was generated from the following files:
include/GuiApplication.h
src/gui/GuiApplication.cpp