LMMS: lmms::AutoDetectMidiController Class Reference
lmms::AutoDetectMidiController Class Reference
Public Slots
void reset ()
Public Slots inherited from lmms::MidiController
gui::ControllerDialog * createDialog (QWidget *_parent) override
void updateName ()
Public Slots inherited from lmms::Controller
virtual gui::ControllerDialog * createDialog (QWidget *_parent)
virtual void setName (const QString &_new_name)
Public Member Functions
AutoDetectMidiController (Model *parent)
~AutoDetectMidiController () override=default
MidiController * copyToMidiController (Model *parent)
void processInEvent (const MidiEvent &event, const TimePos &time, f_cnt_t offset=0) override
void useDetected ()
Public Member Functions inherited from lmms::MidiController
MidiController (Model *_parent)
~MidiController () override=default
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
void processInEvent (const MidiEvent &_me, const TimePos &_time, f_cnt_t offset=0) override
void processOutEvent (const MidiEvent &_me, const TimePos &_time, f_cnt_t offset=0) override
void saveSettings (QDomDocument &_doc, QDomElement &_this) override
void subscribeReadablePorts (const MidiPort::Map &_map)
Public Member Functions inherited from lmms::Controller
Controller (ControllerType _type, Model *_parent, const QString &_display_name)
~Controller () override
void addConnection (ControllerConnection *)
int connectionCount () const
virtual float currentValue (int _offset)
bool frequentUpdates () const
bool hasModel (const Model *m) const
bool isSampleExact () const
virtual const QString & name () const
void removeConnection (ControllerConnection *)
void setSampleExact (bool _exact)
ControllerType type () const
virtual ValueBuffer * valueBuffer ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Public Member Functions inherited from lmms::MidiEventProcessor
MidiEventProcessor ()=default
virtual ~MidiEventProcessor ()=default
Private Attributes
int m_detectedMidiChannel
int m_detectedMidiController
QString m_detectedMidiPort
Additional Inherited Members
Public Types inherited from lmms::Controller
enum class ControllerType {
Dummy ,
Lfo ,
Midi ,
Peak
}
Signals inherited from lmms::Controller
void valueChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Public Member Functions inherited from lmms::Controller
static Controller * create (const QDomElement &_this, Model *_parent)
static Controller * create (ControllerType _tt, Model *_parent)
static float fittedValue (float _val)
static void resetFrameCounter ()
static unsigned int runningFrames ()
static long runningPeriods ()
static float runningTime ()
static void triggerFrameCounter ()
Static Public Attributes inherited from lmms::MidiController
static constexpr int NONE = -1
Protected Member Functions inherited from lmms::MidiController
void updateValueBuffer () override
Protected Member Functions inherited from lmms::Controller
virtual float value (int _offset)
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Attributes inherited from lmms::MidiController
float m_lastValue
MidiPort m_midiPort
float m_previousValue
Protected Attributes inherited from lmms::Controller
long m_bufferLastUpdated
int m_connectionCount
float m_currentValue
QString m_name
bool m_sampleExact
ControllerType m_type
ValueBuffer m_valueBuffer
Static Protected Attributes inherited from lmms::Controller
static ControllerVector s_controllers
static long s_periods = 0
Detailed Description
Definition at line 51 of file ControllerConnectionDialog.cpp.
Constructor & Destructor Documentation
AutoDetectMidiController()
lmms::AutoDetectMidiController::AutoDetectMidiController (Model * parent) inline
Definition at line 54 of file ControllerConnectionDialog.cpp.
References lmms::MidiController::MidiController(), m_detectedMidiChannel, m_detectedMidiController, lmms::MidiController::NONE, and lmms::MidiController::updateName().
~AutoDetectMidiController()
lmms::AutoDetectMidiController::~AutoDetectMidiController () override default
Member Function Documentation
copyToMidiController()
MidiController * lmms::AutoDetectMidiController::copyToMidiController (Model * parent) inline
Definition at line 82 of file ControllerConnectionDialog.cpp.
References lmms::MidiController::MidiController(), and lmms::MidiController::m_midiPort.
processInEvent()
void lmms::AutoDetectMidiController::processInEvent (const MidiEvent & event, const TimePos & time, f_cnt_t offset = 0) inline override virtual
Implements lmms::MidiEventProcessor.
Definition at line 66 of file ControllerConnectionDialog.cpp.
References lmms::Engine::audioEngine(), lmms::MidiEvent::channel(), m_detectedMidiChannel, m_detectedMidiController, m_detectedMidiPort, lmms::MidiController::m_midiPort, lmms::AudioEngine::midiClient(), lmms::MidiControlChange, lmms::MidiClient::sourcePortName(), lmms::MidiEvent::type(), and lmms::Controller::valueChanged().
reset
void lmms::AutoDetectMidiController::reset () inline slot
Definition at line 109 of file ControllerConnectionDialog.cpp.
References lmms::MidiController::m_midiPort.
useDetected()
void lmms::AutoDetectMidiController::useDetected () inline
Definition at line 94 of file ControllerConnectionDialog.cpp.
References m_detectedMidiChannel, m_detectedMidiController, m_detectedMidiPort, and lmms::MidiController::m_midiPort.
Member Data Documentation
m_detectedMidiChannel
int lmms::AutoDetectMidiController::m_detectedMidiChannel private
Definition at line 117 of file ControllerConnectionDialog.cpp.
Referenced by AutoDetectMidiController(), processInEvent(), and useDetected().
m_detectedMidiController
int lmms::AutoDetectMidiController::m_detectedMidiController private
Definition at line 118 of file ControllerConnectionDialog.cpp.
Referenced by AutoDetectMidiController(), processInEvent(), and useDetected().
m_detectedMidiPort
QString lmms::AutoDetectMidiController::m_detectedMidiPort private
Definition at line 119 of file ControllerConnectionDialog.cpp.
Referenced by processInEvent(), and useDetected().
The documentation for this class was generated from the following file:
src/gui/modals/ControllerConnectionDialog.cpp