LMMS: lmms::LadspaControl Class Reference
lmms::LadspaControl Class Reference
#include <LadspaControl.h>
Signals
void changed (int _port, LADSPA_Data _value)
void linkChanged (int _port, bool _state)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
LadspaControl (Model *_parent, port_desc_t *_port, bool _link=false)
~LadspaControl () override=default
FloatModel * knobModel ()
void linkControls (LadspaControl *_control)
virtual void loadSettings (const QDomElement &_this, const QString &_name)
QString nodeName () const override
port_desc_t * port ()
virtual void saveSettings (QDomDocument &_doc, QDomElement &_parent, const QString &_name)
void setLink (bool _state)
void setValue (LADSPA_Data _value)
TempoSyncKnobModel * tempoSyncKnobModel ()
BoolModel * toggledModel ()
void unlinkControls (LadspaControl *_control)
LADSPA_Data value ()
ValueBuffer * valueBuffer ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Slots
void knobChanged ()
void ledChanged ()
void linkStateChanged ()
void tempoKnobChanged ()
Protected Member Functions
void loadSettings (const QDomElement &element) override
void saveSettings (QDomDocument &doc, QDomElement &element) override
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Attributes
FloatModel m_knobModel
bool m_link
BoolModel m_linkEnabledModel
port_desc_t * m_port
TempoSyncKnobModel m_tempoSyncKnobModel
BoolModel m_toggledModel
Friends
class gui::LadspaControlView
class gui::LadspaMatrixControlDialog
Detailed Description
Definition at line 49 of file LadspaControl.h.
Constructor & Destructor Documentation
LadspaControl()
lmms::LadspaControl::LadspaControl (Model * _parent, port_desc_t * _port, bool _link = false)
Definition at line 37 of file LadspaControl.cpp.
References lmms::Model::Model(), lmms::Model::dataChanged(), lmms::Enum, lmms::Floating, lmms::Integer, knobChanged(), linkStateChanged(), m_knobModel, m_link, m_linkEnabledModel, m_port, m_tempoSyncKnobModel, m_toggledModel, max, tempoKnobChanged(), and lmms::Time.
Referenced by ~LadspaControl(), linkControls(), and unlinkControls().
~LadspaControl()
lmms::LadspaControl::~LadspaControl () override default
References LadspaControl(), linkControls(), setLink(), setValue(), unlinkControls(), value(), and valueBuffer().
Member Function Documentation
changed
void lmms::LadspaControl::changed (int _port, LADSPA_Data _value) signal
Referenced by knobChanged(), ledChanged(), and tempoKnobChanged().
knobChanged
void lmms::LadspaControl::knobChanged () protected slot
Definition at line 322 of file LadspaControl.cpp.
References changed(), knobChanged(), m_knobModel, and m_port.
Referenced by LadspaControl(), knobChanged(), and linkChanged().
knobModel()
FloatModel * lmms::LadspaControl::knobModel () inline
Definition at line 70 of file LadspaControl.h.
References m_knobModel.
Referenced by linkControls(), and unlinkControls().
ledChanged
void lmms::LadspaControl::ledChanged () protected slot
Definition at line 313 of file LadspaControl.cpp.
References changed(), ledChanged(), m_port, and m_toggledModel.
Referenced by ledChanged(), and linkChanged().
linkChanged
void lmms::LadspaControl::linkChanged (int _port, bool _state) signal
References knobChanged(), ledChanged(), linkStateChanged(), and tempoKnobChanged().
Referenced by linkStateChanged().
linkControls()
void lmms::LadspaControl::linkControls (LadspaControl * _control)
Definition at line 289 of file LadspaControl.cpp.
References LadspaControl(), lmms::Enum, lmms::Floating, lmms::Integer, knobModel(), linkControls(), lmms::AutomatableModel::linkModels(), m_knobModel, m_port, m_tempoSyncKnobModel, m_toggledModel, tempoSyncKnobModel(), lmms::Time, lmms::Toggled, and toggledModel().
Referenced by ~LadspaControl(), and linkControls().
linkStateChanged
void lmms::LadspaControl::linkStateChanged () protected slot
Definition at line 364 of file LadspaControl.cpp.
References linkChanged(), linkStateChanged(), m_linkEnabledModel, and m_port.
Referenced by LadspaControl(), linkChanged(), and linkStateChanged().
loadSettings() [1/2]
void lmms::LadspaControl::loadSettings (const QDomElement & _this, const QString & _name) virtual
Definition at line 219 of file LadspaControl.cpp.
References lmms::Enum, lmms::Floating, lmms::Integer, loadSettings(), m_knobModel, m_link, m_linkEnabledModel, m_port, m_tempoSyncKnobModel, m_toggledModel, lmms::Time, and lmms::Toggled.
Referenced by loadSettings().
loadSettings() [2/2]
void lmms::LadspaControl::loadSettings (const QDomElement & element) inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 111 of file LadspaControl.h.
nodeName()
QString lmms::LadspaControl::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 87 of file LadspaControl.h.
port()
port_desc_t * lmms::LadspaControl::port () inline
Definition at line 80 of file LadspaControl.h.
References m_port.
saveSettings() [1/2]
void lmms::LadspaControl::saveSettings (QDomDocument & _doc, QDomElement & _parent, const QString & _name) virtual
Definition at line 185 of file LadspaControl.cpp.
References lmms::Enum, lmms::Floating, lmms::Integer, m_knobModel, m_link, m_linkEnabledModel, m_port, m_tempoSyncKnobModel, m_toggledModel, saveSettings(), lmms::Time, and lmms::Toggled.
Referenced by saveSettings().
saveSettings() [2/2]
void lmms::LadspaControl::saveSettings (QDomDocument & doc, QDomElement & element) inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 105 of file LadspaControl.h.
setLink()
void lmms::LadspaControl::setLink (bool _state)
Definition at line 372 of file LadspaControl.cpp.
References m_linkEnabledModel, and setLink().
Referenced by ~LadspaControl(), and setLink().
setValue()
void lmms::LadspaControl::setValue (LADSPA_Data _value)
Definition at line 158 of file LadspaControl.cpp.
References lmms::Enum, lmms::Floating, lmms::Integer, m_knobModel, m_port, m_tempoSyncKnobModel, m_toggledModel, setValue(), lmms::Time, and lmms::Toggled.
Referenced by ~LadspaControl(), and setValue().
tempoKnobChanged
void lmms::LadspaControl::tempoKnobChanged () protected slot
Definition at line 331 of file LadspaControl.cpp.
References changed(), m_port, m_tempoSyncKnobModel, and tempoKnobChanged().
Referenced by LadspaControl(), linkChanged(), and tempoKnobChanged().
tempoSyncKnobModel()
TempoSyncKnobModel * lmms::LadspaControl::tempoSyncKnobModel () inline
Definition at line 75 of file LadspaControl.h.
References m_tempoSyncKnobModel.
Referenced by linkControls(), and unlinkControls().
toggledModel()
BoolModel * lmms::LadspaControl::toggledModel () inline
Definition at line 65 of file LadspaControl.h.
References m_toggledModel.
Referenced by linkControls(), and unlinkControls().
unlinkControls()
void lmms::LadspaControl::unlinkControls (LadspaControl * _control)
Definition at line 340 of file LadspaControl.cpp.
References LadspaControl(), lmms::Enum, lmms::Floating, lmms::Integer, knobModel(), m_knobModel, m_port, m_tempoSyncKnobModel, m_toggledModel, tempoSyncKnobModel(), lmms::Time, lmms::Toggled, toggledModel(), unlinkControls(), and lmms::AutomatableModel::unlinkModels().
Referenced by ~LadspaControl(), and unlinkControls().
value()
LADSPA_Data lmms::LadspaControl::value ()
Definition at line 115 of file LadspaControl.cpp.
References lmms::Enum, lmms::Floating, lmms::Integer, m_knobModel, m_port, m_tempoSyncKnobModel, m_toggledModel, lmms::Time, lmms::Toggled, and value().
Referenced by ~LadspaControl(), and value().
valueBuffer()
ValueBuffer * lmms::LadspaControl::valueBuffer ()
Definition at line 136 of file LadspaControl.cpp.
References lmms::Enum, lmms::Floating, lmms::Integer, m_knobModel, m_port, m_tempoSyncKnobModel, lmms::Time, lmms::Toggled, and valueBuffer().
Referenced by ~LadspaControl(), and valueBuffer().
Friends And Related Symbol Documentation
gui::LadspaControlView
friend class gui::LadspaControlView friend
Definition at line 128 of file LadspaControl.h.
gui::LadspaMatrixControlDialog
friend class gui::LadspaMatrixControlDialog friend
Definition at line 129 of file LadspaControl.h.
Member Data Documentation
m_knobModel
FloatModel lmms::LadspaControl::m_knobModel private
Definition at line 124 of file LadspaControl.h.
Referenced by LadspaControl(), knobChanged(), knobModel(), linkControls(), loadSettings(), saveSettings(), setValue(), unlinkControls(), value(), and valueBuffer().
m_link
bool lmms::LadspaControl::m_link private
Definition at line 119 of file LadspaControl.h.
Referenced by LadspaControl(), loadSettings(), and saveSettings().
m_linkEnabledModel
BoolModel lmms::LadspaControl::m_linkEnabledModel private
Definition at line 122 of file LadspaControl.h.
Referenced by LadspaControl(), linkStateChanged(), loadSettings(), saveSettings(), and setLink().
m_port
port_desc_t* lmms::LadspaControl::m_port private
Definition at line 120 of file LadspaControl.h.
Referenced by LadspaControl(), knobChanged(), ledChanged(), linkControls(), linkStateChanged(), loadSettings(), port(), saveSettings(), setValue(), tempoKnobChanged(), unlinkControls(), value(), and valueBuffer().
m_tempoSyncKnobModel
TempoSyncKnobModel lmms::LadspaControl::m_tempoSyncKnobModel private
Definition at line 125 of file LadspaControl.h.
Referenced by LadspaControl(), linkControls(), loadSettings(), saveSettings(), setValue(), tempoKnobChanged(), tempoSyncKnobModel(), unlinkControls(), value(), and valueBuffer().
m_toggledModel
BoolModel lmms::LadspaControl::m_toggledModel private
Definition at line 123 of file LadspaControl.h.
Referenced by LadspaControl(), ledChanged(), linkControls(), loadSettings(), saveSettings(), setValue(), toggledModel(), unlinkControls(), and value().
The documentation for this class was generated from the following files:
include/LadspaControl.h
src/core/LadspaControl.cpp