LMMS: lmms::InstrumentFunctionNoteStacking::Chord Struct Reference
lmms::InstrumentFunctionNoteStacking::Chord Struct Reference
#include <InstrumentFunctions.h>
Public Member Functions
Chord ()
Chord (const char *n, const ChordSemiTones &semi_tones)
const QString & getName () const
bool hasSemiTone (int8_t semiTone) const
bool isEmpty () const
bool isScale () const
int8_t last () const
int8_t operator[] (int n) const
int size () const
Private Attributes
QString m_name
ChordSemiTones m_semiTones
int m_size
Detailed Description
Definition at line 77 of file InstrumentFunctions.h.
Constructor & Destructor Documentation
Chord() [1/2]
lmms::InstrumentFunctionNoteStacking::Chord::Chord () inline
Definition at line 85 of file InstrumentFunctions.h.
References m_size.
Chord() [2/2]
lmms::InstrumentFunctionNoteStacking::Chord::Chord (const char * n, const ChordSemiTones & semi_tones)
Definition at line 150 of file InstrumentFunctions.cpp.
References lmms::InstrumentFunctionNoteStacking::InstrumentFunctionNoteStacking(), m_name, m_semiTones, m_size, and lmms::InstrumentFunctionNoteStacking::MAX_CHORD_POLYPHONY.
Member Function Documentation
getName()
const QString & lmms::InstrumentFunctionNoteStacking::Chord::getName () const inline
Definition at line 111 of file InstrumentFunctions.h.
References m_name.
hasSemiTone()
bool lmms::InstrumentFunctionNoteStacking::Chord::hasSemiTone (int8_t semiTone) const
Definition at line 167 of file InstrumentFunctions.cpp.
References i, m_semiTones, and size().
Referenced by lmms::gui::PianoRoll::markSemiTone().
isEmpty()
bool lmms::InstrumentFunctionNoteStacking::Chord::isEmpty () const inline
Definition at line 99 of file InstrumentFunctions.h.
References size().
Referenced by lmms::gui::PianoRoll::markSemiTone(), lmms::gui::PianoRoll::mousePressEvent(), lmms::gui::PianoRoll::pauseChordNotes(), lmms::gui::PianoRoll::playChordNotes(), and lmms::gui::PianoRoll::updateSemiToneMarkerMenu().
isScale()
bool lmms::InstrumentFunctionNoteStacking::Chord::isScale () const inline
Definition at line 94 of file InstrumentFunctions.h.
References size().
Referenced by lmms::gui::PianoRoll::markSemiTone().
last()
int8_t lmms::InstrumentFunctionNoteStacking::Chord::last () const inline
Definition at line 106 of file InstrumentFunctions.h.
References m_semiTones, and size().
Referenced by lmms::gui::PianoRoll::markSemiTone().
operator[]()
int8_t lmms::InstrumentFunctionNoteStacking::Chord::operator[] (int n) const inline
Definition at line 116 of file InstrumentFunctions.h.
References m_semiTones.
size()
int lmms::InstrumentFunctionNoteStacking::Chord::size () const inline
Definition at line 89 of file InstrumentFunctions.h.
References m_size.
Referenced by hasSemiTone(), isEmpty(), isScale(), last(), lmms::gui::PianoRoll::mousePressEvent(), lmms::gui::PianoRoll::pauseChordNotes(), and lmms::gui::PianoRoll::playChordNotes().
Member Data Documentation
m_name
QString lmms::InstrumentFunctionNoteStacking::Chord::m_name private
Definition at line 80 of file InstrumentFunctions.h.
Referenced by Chord(), and getName().
m_semiTones
ChordSemiTones lmms::InstrumentFunctionNoteStacking::Chord::m_semiTones private
Definition at line 81 of file InstrumentFunctions.h.
Referenced by Chord(), hasSemiTone(), last(), and operator[]().
m_size
int lmms::InstrumentFunctionNoteStacking::Chord::m_size private
Definition at line 82 of file InstrumentFunctions.h.
Referenced by Chord(), Chord(), and size().
The documentation for this struct was generated from the following files:
include/InstrumentFunctions.h
src/core/InstrumentFunctions.cpp