LMMS: Reading and writing MIDI data
Reading and writing MIDI data
Functions
void jack_midi_clear_buffer (void *port_buffer) JACK_OPTIONAL_WEAK_EXPORT
Clear an event buffer.
int jack_midi_event_get (jack_midi_event_t *event, void *port_buffer, uint32_t event_index) JACK_OPTIONAL_WEAK_EXPORT
Get a MIDI event from an event port buffer.
jack_midi_data_t * jack_midi_event_reserve (void *port_buffer, jack_nframes_t time, size_t data_size) JACK_OPTIONAL_WEAK_EXPORT
Allocate space for an event to be written to an event port buffer.
int jack_midi_event_write (void *port_buffer, jack_nframes_t time, const jack_midi_data_t *data, size_t data_size) JACK_OPTIONAL_WEAK_EXPORT
Write an event into an event port buffer.
uint32_t jack_midi_get_event_count (void *port_buffer) JACK_OPTIONAL_WEAK_EXPORT
Get number of events in a port buffer.
uint32_t jack_midi_get_lost_event_count (void *port_buffer) JACK_OPTIONAL_WEAK_EXPORT
Get the number of events that could not be written to port_buffer.
size_t jack_midi_max_event_size (void *port_buffer) JACK_OPTIONAL_WEAK_EXPORT
Get the size of the largest event that can be stored by the port.
void jack_midi_reset_buffer (void *port_buffer) JACK_OPTIONAL_WEAK_DEPRECATED_EXPORT
Reset an event buffer (from data allocated outside of JACK).
Detailed Description
Function Documentation
jack_midi_clear_buffer()
LIB_EXPORT void jack_midi_clear_buffer (void * port_buffer)
#include <midiport.h>
Clear an event buffer.
This should be called at the beginning of each process cycle before calling jack_midi_event_reserve or jack_midi_event_write. This function may not be called on an input port's buffer.
Parameters
port_buffer Port buffer to clear (must be an output port buffer).
Definition at line 84 of file JackMidiAPI.cpp.
References Jack::JackMidiBuffer::IsValid(), Jack::JackMidiBuffer::nframes, and Jack::JackMidiBuffer::Reset().
jack_midi_event_get()
LIB_EXPORT int jack_midi_event_get (jack_midi_event_t * event, void * port_buffer, uint32_t event_index)
#include <midiport.h>
Get a MIDI event from an event port buffer.
Jack MIDI is normalised, the MIDI event returned by this function is guaranteed to be a complete MIDI event (the status byte will always be present, and no realtime events will interspered with the event).
This rule does not apply to System Exclusive MIDI messages since they can be of arbitrary length. To maintain smooth realtime operation such events CAN be deliverd as multiple, non-normalised events. The maximum size of one event "chunk" depends on the MIDI backend in use. For example the midiseq driver will create chunks of 256 bytes. The first SysEx "chunked" event starts with 0xF0 and the last delivered chunk ends with 0xF7. To receive the full SysEx message, a caller of jack_midi_event_get() must concatenate chunks until a chunk ends with 0xF7.
Parameters
event Event structure to store retrieved event in.
port_buffer Port buffer from which to retrieve event.
event_index Index of event to retrieve.
Returns
0 on success, ENODATA if buffer is empty.
Definition at line 67 of file JackMidiAPI.cpp.
References ENOBUFS, Jack::JackMidiBuffer::event_count, Jack::JackMidiBuffer::events, Jack::JackMidiEvent::GetData(), Jack::JackMidiBuffer::IsValid(), Jack::JackMidiEvent::size, and Jack::JackMidiEvent::time.
jack_midi_event_reserve()
LIB_EXPORT jack_midi_data_t * jack_midi_event_reserve (void * port_buffer, jack_nframes_t time, size_t data_size)
#include <midiport.h>
Allocate space for an event to be written to an event port buffer.
Clients are to write the actual event data to be written starting at the pointer returned by this function. Clients must not write more than data_size bytes into this buffer. Clients must write normalised MIDI data to the port - no running status and no (1-byte) realtime messages interspersed with other messages (realtime messages are fine when they occur on their own, like other messages).
Events must be written in order, sorted by their sample offsets. JACK will not sort the events for you, and will refuse to store out-of-order events.
Parameters
port_buffer Buffer to write event to.
time Sample offset of event.
data_size Length of event's raw data in bytes.
Returns
Pointer to the beginning of the reserved event's data buffer, or NULL on error (ie not enough space).
Definition at line 109 of file JackMidiAPI.cpp.
References Jack::JackMidiBuffer::event_count, Jack::JackMidiBuffer::events, Jack::JackMidiBuffer::IsValid(), jack_error, Jack::JackMidiBuffer::nframes, Jack::JackMidiBuffer::ReserveEvent(), and Jack::JackMidiEvent::time.
jack_midi_event_write()
LIB_EXPORT int jack_midi_event_write (void * port_buffer, jack_nframes_t time, const jack_midi_data_t * data, size_t data_size)
#include <midiport.h>
Write an event into an event port buffer.
This function is simply a wrapper for jack_midi_event_reserve which writes the event data into the space reserved in the buffer.
Clients must not write more than data_size bytes into this buffer. Clients must write normalised MIDI data to the port - no running status and no (1-byte) realtime messages interspersed with other messages (realtime messages are fine when they occur on their own, like other messages).
Events must be written in order, sorted by their sample offsets. JACK will not sort the events for you, and will refuse to store out-of-order events.
Parameters
port_buffer Buffer to write event to.
time Sample offset of event.
data Message data to be written.
data_size Length of data in bytes.
Returns
0 on success, ENOBUFS if there's not enough space in buffer for event.
Definition at line 134 of file JackMidiAPI.cpp.
References ENOBUFS, Jack::JackMidiBuffer::event_count, Jack::JackMidiBuffer::events, Jack::JackMidiBuffer::IsValid(), Jack::JackMidiBuffer::nframes, Jack::JackMidiBuffer::ReserveEvent(), and Jack::JackMidiEvent::time.
Referenced by midi_unpack_buf().
jack_midi_get_event_count()
LIB_EXPORT uint32_t jack_midi_get_event_count (void * port_buffer)
#include <midiport.h>
Get number of events in a port buffer.
Parameters
port_buffer Port buffer from which to retrieve event.
Returns
number of events inside port_buffer
Definition at line 57 of file JackMidiAPI.cpp.
References Jack::JackMidiBuffer::event_count, and Jack::JackMidiBuffer::IsValid().
jack_midi_get_lost_event_count()
LIB_EXPORT uint32_t jack_midi_get_lost_event_count (void * port_buffer)
#include <midiport.h>
Get the number of events that could not be written to port_buffer.
This function returning a non-zero value implies port_buffer is full. Currently the only way this can happen is if events are lost on port mixdown.
Parameters
port_buffer Port to receive count for.
Returns
Number of events that could not be written to port_buffer.
Definition at line 153 of file JackMidiAPI.cpp.
References Jack::JackMidiBuffer::IsValid(), and Jack::JackMidiBuffer::lost_events.
jack_midi_max_event_size()
LIB_EXPORT size_t jack_midi_max_event_size (void * port_buffer)
#include <midiport.h>
Get the size of the largest event that can be stored by the port.
This function returns the current space available, taking into account events already stored in the port.
Parameters
port_buffer Port buffer to check size of.
Definition at line 99 of file JackMidiAPI.cpp.
References Jack::JackMidiBuffer::IsValid(), and Jack::JackMidiBuffer::MaxEventSize().
jack_midi_reset_buffer()
LIB_EXPORT void jack_midi_reset_buffer (void * port_buffer)
#include <midiport.h>
Reset an event buffer (from data allocated outside of JACK).
This should be called at the beginning of each process cycle before calling jack_midi_event_reserve or jack_midi_event_write. This function may not be called on an input port's buffer.
Deprecated
Please use jack_midi_clear_buffer().
Parameters
port_buffer Port buffer to reset.
Definition at line 93 of file JackMidiAPI.cpp.
References BUFFER_SIZE_MAX, and Jack::MidiBufferInit().