LMMS: Jack::JackGetInternalClientNameResult Struct Reference
Jack::JackGetInternalClientNameResult Struct Reference
GetInternalClient result.
#include <JackRequest.h>
Public Member Functions
JackGetInternalClientNameResult ()
JackGetInternalClientNameResult (int32_t result, const char *name)
int Read (detail::JackChannelTransactionInterface *trans)
int Size ()
int Write (detail::JackChannelTransactionInterface *trans)
Public Member Functions inherited from Jack::JackResult
JackResult ()
JackResult (int result)
virtual ~JackResult ()
Public Attributes
char fName [JACK_CLIENT_NAME_SIZE+1]
Public Attributes inherited from Jack::JackResult
int fResult
Detailed Description
GetInternalClient result.
Definition at line 943 of file JackRequest.h.
Constructor & Destructor Documentation
JackGetInternalClientNameResult() [1/2]
Jack::JackGetInternalClientNameResult::JackGetInternalClientNameResult () inline
Definition at line 948 of file JackRequest.h.
References Jack::JackResult::JackResult(), and fName.
JackGetInternalClientNameResult() [2/2]
Jack::JackGetInternalClientNameResult::JackGetInternalClientNameResult (int32_t result, const char * name) inline
Definition at line 952 of file JackRequest.h.
References Jack::JackResult::JackResult(), and fName.
Member Function Documentation
Read()
int Jack::JackGetInternalClientNameResult::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 959 of file JackRequest.h.
References CheckRes, fName, Jack::detail::JackChannelTransactionInterface::Read(), and Jack::JackResult::Read().
Size()
int Jack::JackGetInternalClientNameResult::Size () inline
Definition at line 973 of file JackRequest.h.
References fName.
Write()
int Jack::JackGetInternalClientNameResult::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 966 of file JackRequest.h.
References CheckRes, fName, Jack::detail::JackChannelTransactionInterface::Write(), and Jack::JackResult::Write().
Member Data Documentation
fName
char Jack::JackGetInternalClientNameResult::fName[JACK_CLIENT_NAME_SIZE+1]
Definition at line 946 of file JackRequest.h.
Referenced by JackGetInternalClientNameResult(), JackGetInternalClientNameResult(), Jack::JackGenericClientChannel::GetInternalClientName(), Jack::JackRequestDecoder::HandleRequest(), Read(), Size(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h