LMMS: lmms::gui::ControllerConnectionDialog Class Reference
lmms::gui::ControllerConnectionDialog Class Reference
#include <ControllerConnectionDialog.h>
Public Slots
void autoDetectToggled ()
void enableAutoDetect (QAction *_a)
void midiToggled ()
void selectController ()
void userSelected ()
void userToggled ()
Public Member Functions
ControllerConnectionDialog (QWidget *_parent, const AutomatableModel *_target_model)
~ControllerConnectionDialog () override
Controller * chosenController ()
Protected Slots
void midiValueChanged ()
Private Attributes
Controller * m_controller
TabWidget * m_mappingBox
QLineEdit * m_mappingFunction
BoolModel m_midiAutoDetect
LedCheckBox * m_midiAutoDetectCheckBox
LcdSpinBox * m_midiChannelSpinBox
AutoDetectMidiController * m_midiController
LcdSpinBox * m_midiControllerSpinBox
GroupBox * m_midiGroupBox
MidiPortMenu * m_readablePorts
const AutomatableModel * m_targetModel
ComboBox * m_userController
GroupBox * m_userGroupBox
Detailed Description
Definition at line 57 of file ControllerConnectionDialog.h.
Constructor & Destructor Documentation
ControllerConnectionDialog()
lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog (QWidget * _parent, const AutomatableModel * _target_model)
Definition at line 128 of file ControllerConnectionDialog.cpp.
References lmms::Engine::audioEngine(), autoDetectToggled(), lmms::Song::controllers(), lmms::gui::ComboBox::DEFAULT_HEIGHT, lmms::Controller::Dummy, enableAutoDetect(), lmms::ControllerConnection::getController(), lmms::embed::getIconPixmap(), lmms::Engine::getSong(), lmms::MidiPort::Input, m_controller, m_mappingBox, m_mappingFunction, m_midiAutoDetect, m_midiAutoDetectCheckBox, m_midiChannelSpinBox, m_midiController, m_midiControllerSpinBox, m_midiGroupBox, lmms::MidiController::m_midiPort, m_readablePorts, m_targetModel, m_userController, m_userGroupBox, lmms::Controller::Midi, midiToggled(), lmms::MidiController::NONE, lmms::MidiPort::readablePorts(), selectController(), lmms::Controller::type(), userSelected(), and userToggled().
~ControllerConnectionDialog()
lmms::gui::ControllerConnectionDialog::~ControllerConnectionDialog () override
Definition at line 285 of file ControllerConnectionDialog.cpp.
References m_midiController, and m_readablePorts.
Member Function Documentation
autoDetectToggled
void lmms::gui::ControllerConnectionDialog::autoDetectToggled () slot
Definition at line 407 of file ControllerConnectionDialog.cpp.
References m_midiAutoDetect, and m_midiController.
Referenced by ControllerConnectionDialog().
chosenController()
Controller * lmms::gui::ControllerConnectionDialog::chosenController () inline
Definition at line 65 of file ControllerConnectionDialog.h.
References m_controller.
Referenced by lmms::gui::AutomatableModelViewSlots::execConnectionDialog().
enableAutoDetect
void lmms::gui::ControllerConnectionDialog::enableAutoDetect (QAction * _a) slot
Definition at line 432 of file ControllerConnectionDialog.cpp.
References m_midiAutoDetectCheckBox.
Referenced by ControllerConnectionDialog().
midiToggled
void lmms::gui::ControllerConnectionDialog::midiToggled () slot
Definition at line 344 of file ControllerConnectionDialog.cpp.
References lmms::Engine::getSong(), m_midiAutoDetect, m_midiAutoDetectCheckBox, m_midiChannelSpinBox, m_midiController, m_midiControllerSpinBox, m_midiGroupBox, m_readablePorts, m_userGroupBox, and midiValueChanged().
Referenced by ControllerConnectionDialog().
midiValueChanged
void lmms::gui::ControllerConnectionDialog::midiValueChanged () protected slot
Definition at line 418 of file ControllerConnectionDialog.cpp.
References m_midiAutoDetect, m_midiController, and m_readablePorts.
Referenced by midiToggled().
selectController
void lmms::gui::ControllerConnectionDialog::selectController () slot
Definition at line 295 of file ControllerConnectionDialog.cpp.
References lmms::Song::controllers(), lmms::Engine::getSong(), m_controller, m_midiController, m_midiControllerSpinBox, m_midiGroupBox, m_targetModel, m_userController, and m_userGroupBox.
Referenced by ControllerConnectionDialog().
userSelected
void lmms::gui::ControllerConnectionDialog::userSelected () slot
Definition at line 398 of file ControllerConnectionDialog.cpp.
References m_userGroupBox, and userToggled().
Referenced by ControllerConnectionDialog().
userToggled
void lmms::gui::ControllerConnectionDialog::userToggled () slot
Definition at line 386 of file ControllerConnectionDialog.cpp.
References m_midiGroupBox, and m_userGroupBox.
Referenced by ControllerConnectionDialog(), and userSelected().
Member Data Documentation
m_controller
Controller* lmms::gui::ControllerConnectionDialog::m_controller private
Definition at line 101 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), chosenController(), and selectController().
m_mappingBox
TabWidget* lmms::gui::ControllerConnectionDialog::m_mappingBox private
Definition at line 98 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog().
m_mappingFunction
QLineEdit* lmms::gui::ControllerConnectionDialog::m_mappingFunction private
Definition at line 99 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog().
m_midiAutoDetect
BoolModel lmms::gui::ControllerConnectionDialog::m_midiAutoDetect private
Definition at line 91 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), autoDetectToggled(), midiToggled(), and midiValueChanged().
m_midiAutoDetectCheckBox
LedCheckBox* lmms::gui::ControllerConnectionDialog::m_midiAutoDetectCheckBox private
Definition at line 89 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), enableAutoDetect(), and midiToggled().
m_midiChannelSpinBox
LcdSpinBox* lmms::gui::ControllerConnectionDialog::m_midiChannelSpinBox private
Definition at line 87 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), and midiToggled().
m_midiController
AutoDetectMidiController* lmms::gui::ControllerConnectionDialog::m_midiController private
Definition at line 105 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), ~ControllerConnectionDialog(), autoDetectToggled(), midiToggled(), midiValueChanged(), and selectController().
m_midiControllerSpinBox
LcdSpinBox* lmms::gui::ControllerConnectionDialog::m_midiControllerSpinBox private
Definition at line 88 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), midiToggled(), and selectController().
m_midiGroupBox
GroupBox* lmms::gui::ControllerConnectionDialog::m_midiGroupBox private
Definition at line 86 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), midiToggled(), selectController(), and userToggled().
m_readablePorts
MidiPortMenu* lmms::gui::ControllerConnectionDialog::m_readablePorts private
Definition at line 90 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), ~ControllerConnectionDialog(), midiToggled(), and midiValueChanged().
m_targetModel
const AutomatableModel* lmms::gui::ControllerConnectionDialog::m_targetModel private
Definition at line 102 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), and selectController().
m_userController
ComboBox* lmms::gui::ControllerConnectionDialog::m_userController private
Definition at line 95 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), and selectController().
m_userGroupBox
GroupBox* lmms::gui::ControllerConnectionDialog::m_userGroupBox private
Definition at line 94 of file ControllerConnectionDialog.h.
Referenced by ControllerConnectionDialog(), midiToggled(), selectController(), userSelected(), and userToggled().
The documentation for this class was generated from the following files:
include/ControllerConnectionDialog.h
src/gui/modals/ControllerConnectionDialog.cpp