LMMS: lmms::gui::TrackOperationsWidget Class Reference
lmms::gui::TrackOperationsWidget Class Reference
#include <TrackOperationsWidget.h>
Signals
void trackRemovalScheduled (lmms::gui::TrackView *t)
Public Member Functions
TrackOperationsWidget (TrackView *parent)
Create a new trackOperationsWidget.
~TrackOperationsWidget () override=default
TrackGrip * getTrackGrip () const
Protected Member Functions
bool confirmRemoval ()
Show a message box warning the user that this track is about to be closed.
void mousePressEvent (QMouseEvent *me) override
Respond to trackOperationsWidget mouse events.
void paintEvent (QPaintEvent *pe) override
Repaint the trackOperationsWidget.
Private Slots
void clearTrack ()
Clear this track - clears all Clips from the track.
void cloneTrack ()
Clone this track.
void randomizeTrackColor ()
void recordingOff ()
void recordingOn ()
void removeTrack ()
Remove this track from the track list.
void resetClipColors ()
void resetTrackColor ()
void selectTrackColor ()
void toggleRecording (bool on)
void updateMenu ()
Update the trackOperationsWidget context menu.
Private Attributes
AutomatableButton * m_muteBtn
AutomatableButton * m_soloBtn
TrackGrip * m_trackGrip
QPushButton * m_trackOps
TrackView * m_trackView
Friends
class TrackView
Detailed Description
Definition at line 39 of file TrackOperationsWidget.h.
Constructor & Destructor Documentation
TrackOperationsWidget()
lmms::gui::TrackOperationsWidget::TrackOperationsWidget (TrackView * parent)
Create a new trackOperationsWidget.
The trackOperationsWidget is the grip and the mute button of a track.
Parameters
parent the trackView to contain this widget
< The parent widget
< The parent track view
Definition at line 61 of file TrackOperationsWidget.cpp.
References m_muteBtn, m_soloBtn, m_trackGrip, m_trackOps, m_trackView, trackRemovalScheduled(), TrackView, lmms::UI_CTRL_KEY, and updateMenu().
~TrackOperationsWidget()
lmms::gui::TrackOperationsWidget::~TrackOperationsWidget () override default
Member Function Documentation
clearTrack
void lmms::gui::TrackOperationsWidget::clearTrack () private slot
Clear this track - clears all Clips from the track.
Definition at line 222 of file TrackOperationsWidget.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), lmms::Track::deleteClips(), lmms::Track::lock(), m_trackView, and lmms::Track::unlock().
Referenced by updateMenu().
cloneTrack
void lmms::gui::TrackOperationsWidget::cloneTrack () private slot
Clone this track.
Definition at line 198 of file TrackOperationsWidget.cpp.
References lmms::gui::TrackContainerView::createTrackView(), i, m_soloBtn, m_trackView, lmms::gui::TrackContainerView::moveTrackView(), lmms::Track::toggleSolo(), TrackView, and lmms::gui::TrackContainerView::trackViews().
Referenced by updateMenu().
confirmRemoval()
bool lmms::gui::TrackOperationsWidget::confirmRemoval () protected
Show a message box warning the user that this track is about to be closed.
Definition at line 167 of file TrackOperationsWidget.cpp.
References lmms::ConfigManager::inst(), m_trackView, lmms::ConfigManager::setValue(), and lmms::ConfigManager::value().
Referenced by removeTrack().
getTrackGrip()
TrackGrip * lmms::gui::TrackOperationsWidget::getTrackGrip () const inline
Definition at line 46 of file TrackOperationsWidget.h.
References m_trackGrip.
mousePressEvent()
void lmms::gui::TrackOperationsWidget::mousePressEvent (QMouseEvent * me) override protected
Respond to trackOperationsWidget mouse events.
If it's the left mouse button, and Ctrl is held down, and we're not a Pattern Editor track, then start a new drag event to copy this track.
Otherwise, ignore all other events.
Parameters
me The mouse event to respond to.
Definition at line 132 of file TrackOperationsWidget.cpp.
References lmms::DataFile::content(), lmms::DataFile::DragNDropData, lmms::KBD_COPY_MODIFIER, m_trackView, and lmms::Track::Pattern.
paintEvent()
void lmms::gui::TrackOperationsWidget::paintEvent (QPaintEvent * pe) override protected
Repaint the trackOperationsWidget.
Only things that's done for now is to paint the background with the brush of the window from the palette.
Definition at line 158 of file TrackOperationsWidget.cpp.
randomizeTrackColor
void lmms::gui::TrackOperationsWidget::randomizeTrackColor () private slot
Definition at line 265 of file TrackOperationsWidget.cpp.
References lmms::gui::ColorChooser::getPalette(), lmms::Engine::getSong(), m_trackView, lmms::Song::setModified(), and lmms::gui::ColorChooser::Track.
Referenced by updateMenu().
recordingOff
void lmms::gui::TrackOperationsWidget::recordingOff () private slot
Definition at line 358 of file TrackOperationsWidget.cpp.
References toggleRecording().
Referenced by updateMenu().
recordingOn
void lmms::gui::TrackOperationsWidget::recordingOn () private slot
Definition at line 352 of file TrackOperationsWidget.cpp.
References toggleRecording().
Referenced by updateMenu().
removeTrack
void lmms::gui::TrackOperationsWidget::removeTrack () private slot
Remove this track from the track list.
Definition at line 235 of file TrackOperationsWidget.cpp.
References confirmRemoval(), m_trackView, and trackRemovalScheduled().
Referenced by updateMenu().
resetClipColors
void lmms::gui::TrackOperationsWidget::resetClipColors () private slot
Definition at line 274 of file TrackOperationsWidget.cpp.
References lmms::Engine::getSong(), m_trackView, and lmms::Song::setModified().
Referenced by updateMenu().
resetTrackColor
void lmms::gui::TrackOperationsWidget::resetTrackColor () private slot
Definition at line 257 of file TrackOperationsWidget.cpp.
References lmms::Engine::getSong(), m_trackView, and lmms::Song::setModified().
Referenced by updateMenu().
selectTrackColor
void lmms::gui::TrackOperationsWidget::selectTrackColor () private slot
Definition at line 243 of file TrackOperationsWidget.cpp.
References lmms::Engine::getSong(), m_trackView, lmms::Song::setModified(), lmms::gui::ColorChooser::Track, and lmms::gui::ColorChooser::withPalette().
Referenced by updateMenu().
toggleRecording
void lmms::gui::TrackOperationsWidget::toggleRecording (bool on) private slot
Definition at line 337 of file TrackOperationsWidget.cpp.
References lmms::Track::getClips(), lmms::Clip::getTrack(), and m_trackView.
Referenced by recordingOff(), and recordingOn().
trackRemovalScheduled
void lmms::gui::TrackOperationsWidget::trackRemovalScheduled (lmms::gui::TrackView * t) signal
Referenced by TrackOperationsWidget(), and removeTrack().
updateMenu
void lmms::gui::TrackOperationsWidget::updateMenu () private slot
Update the trackOperationsWidget context menu.
For all track types, we have the Clone and Remove options. For instrument-tracks we also offer the MIDI-control-menu For automation tracks, extra options: turn on/off recording on all Clips (same should be added for sample tracks when sampletrack recording is implemented)
Definition at line 294 of file TrackOperationsWidget.cpp.
References clearTrack(), cloneTrack(), lmms::embed::getIconPixmap(), m_trackOps, m_trackView, randomizeTrackColor(), recordingOff(), recordingOn(), removeTrack(), resetClipColors(), resetTrackColor(), and selectTrackColor().
Referenced by TrackOperationsWidget().
Friends And Related Symbol Documentation
TrackView
friend class TrackView friend
Definition at line 76 of file TrackOperationsWidget.h.
References TrackView.
Referenced by TrackOperationsWidget(), cloneTrack(), and TrackView.
Member Data Documentation
m_muteBtn
AutomatableButton* lmms::gui::TrackOperationsWidget::m_muteBtn private
Definition at line 72 of file TrackOperationsWidget.h.
Referenced by TrackOperationsWidget().
m_soloBtn
AutomatableButton* lmms::gui::TrackOperationsWidget::m_soloBtn private
Definition at line 73 of file TrackOperationsWidget.h.
Referenced by TrackOperationsWidget(), and cloneTrack().
m_trackGrip
TrackGrip* lmms::gui::TrackOperationsWidget::m_trackGrip private
Definition at line 70 of file TrackOperationsWidget.h.
Referenced by TrackOperationsWidget(), and getTrackGrip().
m_trackOps
QPushButton* lmms::gui::TrackOperationsWidget::m_trackOps private
Definition at line 71 of file TrackOperationsWidget.h.
Referenced by TrackOperationsWidget(), and updateMenu().
m_trackView
TrackView* lmms::gui::TrackOperationsWidget::m_trackView private
Definition at line 68 of file TrackOperationsWidget.h.
Referenced by TrackOperationsWidget(), clearTrack(), cloneTrack(), confirmRemoval(), mousePressEvent(), randomizeTrackColor(), removeTrack(), resetClipColors(), resetTrackColor(), selectTrackColor(), toggleRecording(), and updateMenu().
The documentation for this class was generated from the following files:
include/TrackOperationsWidget.h
src/gui/tracks/TrackOperationsWidget.cpp