LMMS: lmms::gui::Directory Class Reference
lmms::gui::Directory Class Reference
#include <FileBrowser.h>
Public Member Functions
Directory (const QString &filename, const QString &path, const QString &filter)
void addDirectory (const QString &dir)
QString fullName (QString path=QString{}) const override
void update ()
Public Member Functions inherited from lmms::gui::FileBrowserWidgetItem
FileBrowserWidgetItem (const QStringList &strings, int type, QTreeWidget *parent=nullptr)
Private Member Functions
bool addItems (const QString &path)
Private Attributes
int m_dirCount
QStringList m_directories
Directories that lead here Initially, this is just set to the current path of a directory If, however, you have e.g.
QString m_filter
Filter as used in QDir::match().
QPixmap m_folderLockedPixmap = embed::getIconPixmap("folder_locked")
QPixmap m_folderOpenedPixmap = embed::getIconPixmap("folder_opened")
QPixmap m_folderPixmap = embed::getIconPixmap("folder")
Detailed Description
Definition at line 194 of file FileBrowser.h.
Constructor & Destructor Documentation
Directory()
lmms::gui::Directory::Directory (const QString & filename, const QString & path, const QString & filter)
Definition at line 1056 of file FileBrowser.cpp.
References lmms::gui::FileBrowserWidgetItem::FileBrowserWidgetItem(), fullName(), m_dirCount, m_directories, m_filter, m_folderLockedPixmap, m_folderPixmap, and lmms::gui::TypeDirectoryItem.
Referenced by addItems().
Member Function Documentation
addDirectory()
void lmms::gui::Directory::addDirectory (const QString & dir) inline
Definition at line 214 of file FileBrowser.h.
References m_directories.
addItems()
bool lmms::gui::Directory::addItems (const QString & path) private
Definition at line 1106 of file FileBrowser.cpp.
References Directory(), lmms::gui::FileBrowser::dirFilters(), m_dirCount, m_filter, and lmms::gui::FileBrowser::sortFlags().
Referenced by update().
fullName()
QString lmms::gui::Directory::fullName (QString path = QString{}) const inline override virtual
Implements lmms::gui::FileBrowserWidgetItem.
Definition at line 201 of file FileBrowser.h.
Referenced by Directory(), and update().
update()
void lmms::gui::Directory::update ()
Definition at line 1066 of file FileBrowser.cpp.
References addItems(), fullName(), lmms::embed::getIconPixmap(), lmms::ConfigManager::inst(), m_dirCount, m_directories, m_folderOpenedPixmap, and m_folderPixmap.
Member Data Documentation
m_dirCount
int lmms::gui::Directory::m_dirCount private
Definition at line 238 of file FileBrowser.h.
Referenced by Directory(), addItems(), and update().
m_directories
QStringList lmms::gui::Directory::m_directories private
Directories that lead here Initially, this is just set to the current path of a directory If, however, you have e.g.
'TripleOscillator/xyz' in two of the file browser's search directories 'a' and 'b', this will have two entries 'a/TripleOscillator' and 'b/TripleOscillator' and 'xyz' in the tree widget
Definition at line 234 of file FileBrowser.h.
Referenced by Directory(), addDirectory(), and update().
m_filter
QString lmms::gui::Directory::m_filter private
Filter as used in QDir::match().
Definition at line 236 of file FileBrowser.h.
Referenced by Directory(), and addItems().
m_folderLockedPixmap
QPixmap lmms::gui::Directory::m_folderLockedPixmap = embed::getIconPixmap("folder_locked") private
Definition at line 226 of file FileBrowser.h.
Referenced by Directory().
m_folderOpenedPixmap
QPixmap lmms::gui::Directory::m_folderOpenedPixmap = embed::getIconPixmap("folder_opened") private
Definition at line 225 of file FileBrowser.h.
Referenced by update().
m_folderPixmap
QPixmap lmms::gui::Directory::m_folderPixmap = embed::getIconPixmap("folder") private
Definition at line 224 of file FileBrowser.h.
Referenced by Directory(), and update().
The documentation for this class was generated from the following files:
include/FileBrowser.h
src/gui/FileBrowser.cpp