LMMS: lmms::gui::TabButton Class Reference
lmms::gui::TabButton Class Reference
#include <TabButton.h>
Signals
void clicked (int)
Public Member Functions
TabButton (const QString &_text, int _id, QWidget *_parent)
~TabButton () override=default
Protected Slots
void slotClicked ()
Private Attributes
int m_id
Detailed Description
Definition at line 34 of file TabButton.h.
Constructor & Destructor Documentation
TabButton()
lmms::gui::TabButton::TabButton (const QString & _text, int _id, QWidget * _parent) inline
Definition at line 38 of file TabButton.h.
References clicked(), m_id, and slotClicked().
~TabButton()
lmms::gui::TabButton::~TabButton () override default
Member Function Documentation
clicked
void lmms::gui::TabButton::clicked (int) signal
Referenced by TabButton(), and slotClicked().
slotClicked
void lmms::gui::TabButton::slotClicked () inline protected slot
Definition at line 55 of file TabButton.h.
References clicked(), and m_id.
Referenced by TabButton().
Member Data Documentation
m_id
int lmms::gui::TabButton::m_id private
Definition at line 62 of file TabButton.h.
Referenced by TabButton(), and slotClicked().
The documentation for this class was generated from the following file:
include/TabButton.h