LMMS: lmms::MidiEvent Class Reference
lmms::MidiEvent Class Reference
#include <MidiEvent.h>
Public Types
enum class Source {
Internal ,
External
}
Public Member Functions
MidiEvent (const MidiEvent &other)=default
MidiEvent (MidiEventTypes type, const char *sysExData, std::size_t dataLen, Source source=Source::External)
MidiEvent (MidiEventTypes type=MidiActiveSensing, int8_t channel=0, int16_t param1=0, int16_t param2=0, const void *sourcePort=nullptr, Source source=Source::External)
int8_t channel () const
uint8_t channelPressure () const
uint8_t controllerNumber () const
uint8_t controllerValue () const
int16_t key () const
MidiMetaEventType metaEvent () const
int16_t midiPanning () const
panning_t panning () const
int16_t param (int i) const
int16_t pitchBend () const
uint8_t program () const
void setChannel (int8_t channel)
void setControllerNumber (uint8_t num)
void setControllerValue (uint8_t value)
void setKey (int16_t key)
void setMetaEvent (MidiMetaEventType metaEvent)
void setParam (int i, uint16_t value)
void setPitchBend (uint16_t pitchBend)
void setSource (Source value)
void setType (MidiEventTypes type)
void setVelocity (int16_t velocity)
Source source () const
const void * sourcePort () const
auto sysExData () const -> const char *
MidiEventTypes type () const
uint8_t velocity () const
volume_t volume (int midiBaseVelocity) const
Private Attributes
int8_t m_channel
union {
uint8_t m_bytes [4]
int16_t m_param [2]
int32_t m_sysExDataLen
} m_data
MidiMetaEventType m_metaEvent
Source m_source
const void * m_sourcePort
const char * m_sysExData
MidiEventTypes m_type
Detailed Description
Definition at line 36 of file MidiEvent.h.
Member Enumeration Documentation
Source
enum class lmms::MidiEvent::Source strong
Enumerator
Internal
External
Definition at line 39 of file MidiEvent.h.
Constructor & Destructor Documentation
MidiEvent() [1/3]
lmms::MidiEvent::MidiEvent (MidiEventTypes type = MidiActiveSensing, int8_t channel = 0, int16_t param1 = 0, int16_t param2 = 0, const void * sourcePort = nullptr, Source source = Source::External) inline
Definition at line 41 of file MidiEvent.h.
References channel(), External, m_channel, m_data, m_metaEvent, m_source, m_sourcePort, m_sysExData, m_type, lmms::MidiActiveSensing, lmms::MidiMetaInvalid, source(), sourcePort(), and type().
Referenced by MidiEvent().
MidiEvent() [2/3]
lmms::MidiEvent::MidiEvent (MidiEventTypes type, const char * sysExData, std::size_t dataLen, Source source = Source::External) inline
Definition at line 58 of file MidiEvent.h.
References External, m_channel, m_data, m_metaEvent, m_source, m_sourcePort, m_sysExData, m_type, lmms::MidiMetaInvalid, source(), sysExData(), and type().
MidiEvent() [3/3]
lmms::MidiEvent::MidiEvent (const MidiEvent & other) default
References MidiEvent().
Member Function Documentation
channel()
int8_t lmms::MidiEvent::channel () const inline
Definition at line 91 of file MidiEvent.h.
References m_channel.
Referenced by MidiEvent(), lmms::AutoDetectMidiController::processInEvent(), lmms::InstrumentTrack::processInEvent(), lmms::MidiController::processInEvent(), lmms::MidiPort::processInEvent(), lmms::RemotePlugin::processMidiEvent(), lmms::MidiClientRaw::processOutEvent(), lmms::MidiPort::processOutEvent(), setChannel(), and lmms::writeToByteSeq().
channelPressure()
uint8_t lmms::MidiEvent::channelPressure () const inline
Definition at line 178 of file MidiEvent.h.
References param().
Referenced by lmms::writeToByteSeq().
controllerNumber()
uint8_t lmms::MidiEvent::controllerNumber () const inline
Definition at line 153 of file MidiEvent.h.
References param().
Referenced by lmms::InstrumentTrack::processInEvent(), and lmms::writeToByteSeq().
controllerValue()
uint8_t lmms::MidiEvent::controllerValue () const inline
Definition at line 163 of file MidiEvent.h.
References param().
Referenced by lmms::InstrumentTrack::processInEvent(), and lmms::writeToByteSeq().
key()
int16_t lmms::MidiEvent::key () const inline
Definition at line 111 of file MidiEvent.h.
References param().
Referenced by lmms::InstrumentTrack::applyMasterKey(), lmms::InstrumentTrack::processInEvent(), lmms::MidiPort::processInEvent(), lmms::InstrumentTrack::processOutEvent(), lmms::MidiClientRaw::processOutEvent(), setKey(), and lmms::writeToByteSeq().
metaEvent()
MidiMetaEventType lmms::MidiEvent::metaEvent () const inline
Definition at line 86 of file MidiEvent.h.
References m_metaEvent.
Referenced by lmms::InstrumentTrack::processInEvent(), and setMetaEvent().
midiPanning()
int16_t lmms::MidiEvent::midiPanning () const inline
Definition at line 138 of file MidiEvent.h.
References m_data.
Referenced by panning().
panning()
panning_t lmms::MidiEvent::panning () const inline
Definition at line 131 of file MidiEvent.h.
References lmms::MidiMaxPanning, lmms::MidiMinPanning, midiPanning(), lmms::PanningLeft, and lmms::PanningRight.
Referenced by lmms::InstrumentTrack::processInEvent().
param()
int16_t lmms::MidiEvent::param (int i) const inline
Definition at line 101 of file MidiEvent.h.
References i, and m_data.
Referenced by channelPressure(), controllerNumber(), controllerValue(), key(), pitchBend(), lmms::RemotePlugin::processMidiEvent(), and program().
pitchBend()
int16_t lmms::MidiEvent::pitchBend () const inline
Definition at line 183 of file MidiEvent.h.
References param().
Referenced by lmms::InstrumentTrack::processInEvent(), setPitchBend(), and lmms::writeToByteSeq().
program()
uint8_t lmms::MidiEvent::program () const inline
Definition at line 173 of file MidiEvent.h.
References param().
Referenced by lmms::writeToByteSeq().
setChannel()
void lmms::MidiEvent::setChannel (int8_t channel) inline
Definition at line 96 of file MidiEvent.h.
References channel(), and m_channel.
setControllerNumber()
void lmms::MidiEvent::setControllerNumber (uint8_t num) inline
Definition at line 158 of file MidiEvent.h.
References setParam().
setControllerValue()
void lmms::MidiEvent::setControllerValue (uint8_t value) inline
Definition at line 168 of file MidiEvent.h.
References setParam().
setKey()
void lmms::MidiEvent::setKey (int16_t key) inline
Definition at line 116 of file MidiEvent.h.
References key(), and m_data.
Referenced by lmms::InstrumentTrack::applyMasterKey(), and lmms::MidiPort::processOutEvent().
setMetaEvent()
void lmms::MidiEvent::setMetaEvent (MidiMetaEventType metaEvent) inline
Definition at line 81 of file MidiEvent.h.
References m_metaEvent, and metaEvent().
Referenced by lmms::gui::PianoRoll::mouseMoveEvent().
setParam()
void lmms::MidiEvent::setParam (int i, uint16_t value) inline
Definition at line 106 of file MidiEvent.h.
References i, and m_data.
Referenced by setControllerNumber(), setControllerValue(), and setPitchBend().
setPitchBend()
void lmms::MidiEvent::setPitchBend (uint16_t pitchBend) inline
Definition at line 188 of file MidiEvent.h.
References pitchBend(), and setParam().
setSource()
void lmms::MidiEvent::setSource (Source value) inline
Definition at line 200 of file MidiEvent.h.
References m_source.
setType()
void lmms::MidiEvent::setType (MidiEventTypes type) inline
Definition at line 76 of file MidiEvent.h.
References m_type, and type().
setVelocity()
void lmms::MidiEvent::setVelocity (int16_t velocity) inline
Definition at line 126 of file MidiEvent.h.
References m_data, and velocity().
Referenced by lmms::MidiPort::processInEvent(), and lmms::MidiPort::processOutEvent().
source()
Source lmms::MidiEvent::source () const inline
Definition at line 195 of file MidiEvent.h.
References m_source.
Referenced by MidiEvent(), MidiEvent(), and lmms::InstrumentTrack::processInEvent().
sourcePort()
const void * lmms::MidiEvent::sourcePort () const inline
Definition at line 148 of file MidiEvent.h.
References m_sourcePort.
Referenced by MidiEvent().
sysExData()
auto lmms::MidiEvent::sysExData () const->constchar * inline
Definition at line 193 of file MidiEvent.h.
References m_sysExData.
Referenced by MidiEvent().
type()
MidiEventTypes lmms::MidiEvent::type () const inline
Definition at line 71 of file MidiEvent.h.
References m_type.
Referenced by MidiEvent(), MidiEvent(), lmms::InstrumentTrack::applyMasterKey(), lmms::AutoDetectMidiController::processInEvent(), lmms::InstrumentTrack::processInEvent(), lmms::MidiController::processInEvent(), lmms::MidiPort::processInEvent(), lmms::RemotePlugin::processMidiEvent(), lmms::InstrumentTrack::processOutEvent(), lmms::MidiClientRaw::processOutEvent(), lmms::MidiPort::processOutEvent(), setType(), and lmms::writeToByteSeq().
velocity()
uint8_t lmms::MidiEvent::velocity () const inline
Definition at line 121 of file MidiEvent.h.
References m_data.
Referenced by lmms::InstrumentTrack::processInEvent(), lmms::MidiPort::processInEvent(), lmms::InstrumentTrack::processOutEvent(), lmms::MidiClientRaw::processOutEvent(), lmms::MidiPort::processOutEvent(), setVelocity(), volume(), and lmms::writeToByteSeq().
volume()
volume_t lmms::MidiEvent::volume (int midiBaseVelocity) const inline
Definition at line 143 of file MidiEvent.h.
References lmms::DefaultVolume, and velocity().
Referenced by lmms::InstrumentTrack::processInEvent().
Member Data Documentation
m_bytes
uint8_t lmms::MidiEvent::m_bytes[4]
Definition at line 213 of file MidiEvent.h.
m_channel
int8_t lmms::MidiEvent::m_channel private
Definition at line 209 of file MidiEvent.h.
Referenced by MidiEvent(), MidiEvent(), channel(), and setChannel().
[union]
union { ... } lmms::MidiEvent::m_data
Referenced by MidiEvent(), MidiEvent(), midiPanning(), param(), setKey(), setParam(), setVelocity(), and velocity().
m_metaEvent
MidiMetaEventType lmms::MidiEvent::m_metaEvent private
Definition at line 208 of file MidiEvent.h.
Referenced by MidiEvent(), MidiEvent(), metaEvent(), and setMetaEvent().
m_param
int16_t lmms::MidiEvent::m_param[2]
Definition at line 212 of file MidiEvent.h.
m_source
Source lmms::MidiEvent::m_source private
Definition at line 221 of file MidiEvent.h.
Referenced by MidiEvent(), MidiEvent(), setSource(), and source().
m_sourcePort
const void* lmms::MidiEvent::m_sourcePort private
Definition at line 218 of file MidiEvent.h.
Referenced by MidiEvent(), MidiEvent(), and sourcePort().
m_sysExData
const char* lmms::MidiEvent::m_sysExData private
Definition at line 217 of file MidiEvent.h.
Referenced by MidiEvent(), MidiEvent(), and sysExData().
m_sysExDataLen
int32_t lmms::MidiEvent::m_sysExDataLen
Definition at line 214 of file MidiEvent.h.
m_type
MidiEventTypes lmms::MidiEvent::m_type private
Definition at line 207 of file MidiEvent.h.
Referenced by MidiEvent(), MidiEvent(), setType(), and type().
The documentation for this class was generated from the following file:
include/MidiEvent.h