LMMS: Jack::JackResult Struct Reference
Jack::JackResult Struct Reference
Result from the server.
#include <JackRequest.h>
Public Member Functions
JackResult ()
JackResult (int result)
virtual ~JackResult ()
virtual int Read (detail::JackChannelTransactionInterface *trans)
virtual int Write (detail::JackChannelTransactionInterface *trans)
Public Attributes
int fResult
Detailed Description
Result from the server.
Definition at line 144 of file JackRequest.h.
Constructor & Destructor Documentation
JackResult() [1/2]
Jack::JackResult::JackResult () inline
Definition at line 149 of file JackRequest.h.
References fResult.
Referenced by Jack::JackClientCheckResult::JackClientCheckResult(), Jack::JackClientCheckResult::JackClientCheckResult(), Jack::JackClientNameResult::JackClientNameResult(), Jack::JackClientNameResult::JackClientNameResult(), Jack::JackClientOpenResult::JackClientOpenResult(), Jack::JackClientOpenResult::JackClientOpenResult(), Jack::JackGetInternalClientNameResult::JackGetInternalClientNameResult(), Jack::JackGetInternalClientNameResult::JackGetInternalClientNameResult(), Jack::JackInternalClientHandleResult::JackInternalClientHandleResult(), Jack::JackInternalClientHandleResult::JackInternalClientHandleResult(), Jack::JackInternalClientLoadResult::JackInternalClientLoadResult(), Jack::JackInternalClientLoadResult::JackInternalClientLoadResult(), Jack::JackInternalClientUnloadResult::JackInternalClientUnloadResult(), Jack::JackInternalClientUnloadResult::JackInternalClientUnloadResult(), Jack::JackPortRegisterResult::JackPortRegisterResult(), Jack::JackSessionNotifyResult::JackSessionNotifyResult(), Jack::JackSessionNotifyResult::JackSessionNotifyResult(), Jack::JackUUIDResult::JackUUIDResult(), and Jack::JackUUIDResult::JackUUIDResult().
JackResult() [2/2]
Jack::JackResult::JackResult (int result) inline
Definition at line 151 of file JackRequest.h.
References fResult.
~JackResult()
virtual Jack::JackResult::~JackResult () inline virtual
Definition at line 153 of file JackRequest.h.
Member Function Documentation
Read()
virtual int Jack::JackResult::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented in Jack::JackClientCheckResult, Jack::JackClientNameResult, Jack::JackClientOpenResult, Jack::JackGetInternalClientNameResult, Jack::JackInternalClientHandleResult, Jack::JackInternalClientLoadResult, Jack::JackInternalClientUnloadResult, Jack::JackPortRegisterResult, Jack::JackSessionNotifyResult, and Jack::JackUUIDResult.
Definition at line 156 of file JackRequest.h.
References fResult, and Jack::detail::JackChannelTransactionInterface::Read().
Referenced by Jack::JackSocketNotifyChannel::ClientNotify(), Jack::JackWinNamedPipeNotifyChannel::ClientNotify(), Jack::JackSocketClientChannel::Execute(), Jack::JackClientCheckResult::Read(), Jack::JackClientNameResult::Read(), Jack::JackClientOpenResult::Read(), Jack::JackGetInternalClientNameResult::Read(), Jack::JackInternalClientHandleResult::Read(), Jack::JackInternalClientLoadResult::Read(), Jack::JackInternalClientUnloadResult::Read(), Jack::JackPortRegisterResult::Read(), Jack::JackSessionNotifyResult::Read(), Jack::JackUUIDResult::Read(), and Jack::JackGenericClientChannel::ServerSyncCall().
Write()
virtual int Jack::JackResult::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented in Jack::JackClientCheckResult, Jack::JackClientNameResult, Jack::JackClientOpenResult, Jack::JackGetInternalClientNameResult, Jack::JackInternalClientHandleResult, Jack::JackInternalClientLoadResult, Jack::JackInternalClientUnloadResult, Jack::JackPortRegisterResult, Jack::JackSessionNotifyResult, and Jack::JackUUIDResult.
Definition at line 161 of file JackRequest.h.
References fResult, and Jack::detail::JackChannelTransactionInterface::Write().
Referenced by Jack::JackSocketNotifyChannel::ClientNotify(), Jack::JackSocketClientChannel::Execute(), Jack::JackWinNamedPipeClientChannel::Execute(), Jack::JackClientCheckResult::Write(), Jack::JackClientNameResult::Write(), Jack::JackClientOpenResult::Write(), Jack::JackGetInternalClientNameResult::Write(), Jack::JackInternalClientHandleResult::Write(), Jack::JackInternalClientLoadResult::Write(), Jack::JackInternalClientUnloadResult::Write(), Jack::JackPortRegisterResult::Write(), Jack::JackSessionNotifyResult::Write(), and Jack::JackUUIDResult::Write().
Member Data Documentation
fResult
int Jack::JackResult::fResult
Definition at line 147 of file JackRequest.h.
Referenced by JackResult(), JackResult(), Jack::JackClientPipeThread::ClientAdd(), Jack::JackSocketServerChannel::ClientAdd(), Jack::JackSocketNotifyChannel::ClientNotify(), Jack::JackWinNamedPipeNotifyChannel::ClientNotify(), Jack::JackSocketClientChannel::Execute(), Jack::JackWinNamedPipeClientChannel::Execute(), Jack::JackRequestDecoder::HandleRequest(), Read(), Jack::JackGenericClientChannel::ServerSyncCall(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h