LMMS: Jack::JackAlsaDriver Class Reference
Jack::JackAlsaDriver Class Reference
The ALSA driver.
#include <JackAlsaDriver.h>
Public Member Functions
JackAlsaDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAlsaDriver ()
int Attach ()
void ClearOutputAux ()
int Close ()
int create_thread (pthread_t *thread, int prio, int rt, void *(*start_func)(void *), void *arg)
int Detach ()
jack_nframes_t frame_time () const
jack_nframes_t get_sample_rate () const
int is_realtime () const
bool IsFixedBufferSize ()
jack_nframes_t last_frame_time () const
void MonitorInputAux ()
int Open (jack_nframes_t buffer_size, jack_nframes_t user_nperiods, jack_nframes_t samplerate, bool hw_monitoring, bool hw_metering, bool capturing, bool playing, DitherAlgorithm dither, bool soft_mode, bool monitor, int inchannels, int outchannels, bool shorts_first, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency, const char *midi_driver_name)
void * port_get_buffer (int port, jack_nframes_t nframes)
jack_port_id_t port_register (const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
int port_set_alias (int port, const char *name)
int port_unregister (jack_port_id_t port_index)
int PortSetDefaultMetadata (jack_port_id_t port_id, const char *pretty_name)
int Read ()
void ReadInputAux (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nread)
int SetBufferSize (jack_nframes_t buffer_size)
void SetTimetAux (jack_time_t time)
int Start ()
int Stop ()
int Write ()
void WriteOutputAux (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nwritten)
Public Member Functions inherited from Jack::JackAudioDriver
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int SetSampleRate (jack_nframes_t sample_rate)
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Member Functions
void UpdateLatencies ()
Private Attributes
jack_driver_t * fDriver
jack_native_thread_t fReservationLoopThread
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAudioDriver
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The ALSA driver.
Definition at line 36 of file JackAlsaDriver.h.
Constructor & Destructor Documentation
JackAlsaDriver()
Jack::JackAlsaDriver::JackAlsaDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table) inline
Definition at line 48 of file JackAlsaDriver.h.
References Jack::JackAudioDriver::JackAudioDriver(), and fDriver.
~JackAlsaDriver()
virtual Jack::JackAlsaDriver::~JackAlsaDriver () inline virtual
Definition at line 51 of file JackAlsaDriver.h.
Member Function Documentation
Attach()
int Jack::JackAlsaDriver::Attach () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 126 of file JackAlsaDriver.cpp.
References alsa_midi_t::attach, CaptureDriverFlags, DRIVER_PORT_NUM, Jack::JackDriver::fAliasName, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCaptureDriverName, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fClientControl, fDriver, Jack::JackDriver::fEngine, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackDriverName, Jack::JackDriver::fPlaybackPortList, _alsa_driver::frame_rate, _alsa_driver::frames_per_cycle, Jack::JackDriver::fWithMonitorPorts, _alsa_driver::has_hw_monitoring, i, JACK_DEFAULT_AUDIO_TYPE, jack_error, jack_log(), JackPortCanMonitor, _alsa_driver::midi, MonitorDriverFlags, PlaybackDriverFlags, REAL_JACK_PORT_NAME_SIZE, Jack::JackPort::SetAlias(), Jack::JackAudioDriver::SetBufferSize(), Jack::JackAudioDriver::SetSampleRate(), and UpdateLatencies().
ClearOutputAux()
void Jack::JackAlsaDriver::ClearOutputAux ()
Definition at line 484 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fPlaybackChannels, and Jack::JackDriver::fPlaybackPortList.
Close()
int Jack::JackAlsaDriver::Close () virtual
Reimplemented from Jack::JackDriver.
Definition at line 373 of file JackAlsaDriver.cpp.
References alsa_driver_delete(), Jack::card_to_num(), Jack::JackClientInterface::Close(), Jack::device_reservation_loop_running, Jack::JackDriver::fCaptureDriverName, fDriver, Jack::JackDriver::fPlaybackDriverName, fReservationLoopThread, Jack::JackServerGlobals::on_device_release, and Jack::JackPosixThread::StopImp().
Referenced by Open().
create_thread()
int Jack::JackAlsaDriver::create_thread (pthread_t * thread, int prio, int rt, void *(* start_func)(void *), void * arg)
Definition at line 524 of file JackAlsaDriver.cpp.
References Jack::JackAndroidThread::StartImp(), and Jack::JackPosixThread::StartImp().
Detach()
int Jack::JackAlsaDriver::Detach () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 198 of file JackAlsaDriver.cpp.
References Jack::JackAudioDriver::Detach(), alsa_midi_t::detach, fDriver, and _alsa_driver::midi.
frame_time()
jack_nframes_t Jack::JackAlsaDriver::frame_time () const
Definition at line 560 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fEngineControl, GetMicroSeconds(), and Jack::JackTimer::Time2Frames().
get_sample_rate()
jack_nframes_t Jack::JackAlsaDriver::get_sample_rate () const
Definition at line 555 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fEngineControl.
is_realtime()
int Jack::JackAlsaDriver::is_realtime () const
Definition at line 519 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fEngineControl.
IsFixedBufferSize()
bool Jack::JackAlsaDriver::IsFixedBufferSize () inline virtual
Reimplemented from Jack::JackDriver.
Definition at line 84 of file JackAlsaDriver.h.
last_frame_time()
jack_nframes_t Jack::JackAlsaDriver::last_frame_time () const
Definition at line 567 of file JackAlsaDriver.cpp.
References Jack::JackTimer::CurFrame(), and Jack::JackDriver::fEngineControl.
MonitorInputAux()
void Jack::JackAlsaDriver::MonitorInputAux ()
Definition at line 474 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, fDriver, Jack::JackDriver::fGraphManager, and Jack::JackPort::MonitoringInput().
Open()
int Jack::JackAlsaDriver::Open (jack_nframes_t buffer_size, jack_nframes_t user_nperiods, jack_nframes_t samplerate, bool hw_monitoring, bool hw_metering, bool capturing, bool playing, DitherAlgorithm dither, bool soft_mode, bool monitor, int inchannels, int outchannels, bool shorts_first, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency, const char * midi_driver_name)
Definition at line 277 of file JackAlsaDriver.cpp.
References alsa_driver_new(), alsa_rawmidi_new(), alsa_seqmidi_new(), capture_latency, Jack::card_to_num(), Close(), Jack::device_reservation_loop_running, Jack::JackDriver::fCaptureChannels, fDriver, Jack::JackDriver::fPlaybackChannels, fReservationLoopThread, jack_error, Jack::JackServerGlobals::on_device_acquire, Jack::JackServerGlobals::on_device_release, Jack::JackServerGlobals::on_device_reservation_loop, Jack::on_device_reservation_loop(), Jack::JackAudioDriver::Open(), playback_latency, and Jack::JackPosixThread::StartImp().
port_get_buffer()
void * Jack::JackAlsaDriver::port_get_buffer (int port, jack_nframes_t nframes)
Definition at line 545 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fGraphManager.
Referenced by JACK_port_get_buffer().
port_register()
jack_port_id_t Jack::JackAlsaDriver::port_register (const char * port_name, const char * port_type, unsigned long flags, unsigned long buffer_size)
Definition at line 533 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fClientControl, and Jack::JackDriver::fEngine.
port_set_alias()
int Jack::JackAlsaDriver::port_set_alias (int port, const char * name)
Definition at line 550 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fGraphManager.
Referenced by JACK_port_set_alias().
port_unregister()
int Jack::JackAlsaDriver::port_unregister (jack_port_id_t port_index)
Definition at line 540 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fClientControl, and Jack::JackDriver::fEngine.
Referenced by JACK_port_unregister().
PortSetDefaultMetadata()
int Jack::JackAlsaDriver::PortSetDefaultMetadata (jack_port_id_t port_id, const char * pretty_name)
Definition at line 498 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fClientControl, and Jack::JackDriver::fEngine.
Referenced by jack_port_set_default_metadata().
Read()
int Jack::JackAlsaDriver::Read () virtual
Reimplemented from Jack::JackDriver.
Definition at line 427 of file JackAlsaDriver.cpp.
References alsa_driver_read(), alsa_driver_wait(), Jack::JackDriver::CycleIncTime(), Jack::JackDriver::fBeginDateUst, Jack::JackDriver::fDelayedUsecs, fDriver, Jack::JackDriver::fEngineControl, jack_log(), and Jack::JackDriver::NotifyXRun().
ReadInputAux()
void Jack::JackAlsaDriver::ReadInputAux (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nread)
Definition at line 464 of file JackAlsaDriver.cpp.
References alsa_driver_read_from_channel(), Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, fDriver, and Jack::JackDriver::fGraphManager.
SetBufferSize()
int Jack::JackAlsaDriver::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 82 of file JackAlsaDriver.cpp.
References alsa_driver_reset_parameters(), fDriver, Jack::JackDriver::fEngineControl, jack_log(), Jack::JackAudioDriver::SetBufferSize(), and UpdateLatencies().
SetTimetAux()
void Jack::JackAlsaDriver::SetTimetAux (jack_time_t time)
Definition at line 493 of file JackAlsaDriver.cpp.
References Jack::JackDriver::fBeginDateUst.
Start()
int Jack::JackAlsaDriver::Start () virtual
Reimplemented from Jack::JackDriver.
Definition at line 406 of file JackAlsaDriver.cpp.
References alsa_driver_start(), fDriver, Jack::JackDriverInterface::Start(), and Jack::JackDriverInterface::Stop().
Stop()
int Jack::JackAlsaDriver::Stop () virtual
Reimplemented from Jack::JackDriver.
Definition at line 418 of file JackAlsaDriver.cpp.
References alsa_driver_stop(), fDriver, and Jack::JackDriverInterface::Stop().
UpdateLatencies()
void Jack::JackAlsaDriver::UpdateLatencies (void) private virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 103 of file JackAlsaDriver.cpp.
References _alsa_driver::capture_frame_latency, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, fDriver, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, _alsa_driver::frames_per_cycle, Jack::JackDriver::fWithMonitorPorts, i, JackCaptureLatency, JackPlaybackLatency, _jack_latency_range::max, _jack_latency_range::min, _alsa_driver::playback_frame_latency, and _alsa_driver::user_nperiods.
Referenced by Attach(), and SetBufferSize().
Write()
int Jack::JackAlsaDriver::Write () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 459 of file JackAlsaDriver.cpp.
References alsa_driver_write(), fDriver, and Jack::JackDriver::fEngineControl.
WriteOutputAux()
void Jack::JackAlsaDriver::WriteOutputAux (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nwritten)
Definition at line 503 of file JackAlsaDriver.cpp.
References alsa_driver_write_to_channel(), fDriver, Jack::JackDriver::fGraphManager, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, and Jack::JackDriver::fWithMonitorPorts.
Member Data Documentation
fDriver
jack_driver_t* Jack::JackAlsaDriver::fDriver private
Definition at line 41 of file JackAlsaDriver.h.
Referenced by JackAlsaDriver(), Attach(), Close(), Detach(), MonitorInputAux(), Open(), Read(), ReadInputAux(), SetBufferSize(), Start(), Stop(), UpdateLatencies(), Write(), and WriteOutputAux().
fReservationLoopThread
jack_native_thread_t Jack::JackAlsaDriver::fReservationLoopThread private
Definition at line 42 of file JackAlsaDriver.h.
Referenced by Close(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/linux/alsa/JackAlsaDriver.h
src/3rdparty/jack2/linux/alsa/JackAlsaDriver.cpp