LMMS: lmms::Engine Class Reference
lmms::Engine Class Reference
#include <Engine.h>
Signals
void initProgress (const QString &msg)
Static Public Member Functions
static AudioEngine * audioEngine ()
static void destroy ()
static float framesPerTick ()
static float framesPerTick (sample_rate_t sample_rate)
static Ladspa2LMMS * getLADSPAManager ()
static Song * getSong ()
static void init (bool renderOnly)
static Engine * inst ()
static Mixer * mixer ()
static PatternStore * patternStore ()
static void * pickDndPluginKey ()
static ProjectJournal * projectJournal ()
static void setDndPluginKey (void *newKey)
static void updateFramesPerTick ()
Static Private Member Functions
template<class T>
static void deleteHelper (T **ptr)
Static Private Attributes
static AudioEngine * s_audioEngine = nullptr
static void * s_dndPluginKey = nullptr
static float s_framesPerTick
static Engine * s_instanceOfMe = nullptr
static Ladspa2LMMS * s_ladspaManager = nullptr
static Mixer * s_mixer = nullptr
static PatternStore * s_patternStore = nullptr
static ProjectJournal * s_projectJournal = nullptr
static Song * s_song = nullptr
Friends
class gui::GuiApplication
Detailed Description
Definition at line 51 of file Engine.h.
Member Function Documentation
audioEngine()
AudioEngine * lmms::Engine::audioEngine () inline static
Definition at line 59 of file Engine.h.
References s_audioEngine.
Referenced by lmms::AudioBusHandle::AudioBusHandle(), lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog(), lmms::EnvelopeAndLfoParameters::EnvelopeAndLfoParameters(), lmms::gui::ExportProjectDialog::ExportProjectDialog(), lmms::gui::InstrumentMidiIOView::InstrumentMidiIOView(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), lmms::LfoController::LfoController(), lmms::MixerChannel::MixerChannel(), lmms::gui::Oscilloscope::Oscilloscope(), lmms::PeakController::PeakController(), lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::ProjectRenderer::ProjectRenderer(), lmms::RenderManager::RenderManager(), lmms::Sample::Sample(), lmms::SampleBuffer::SampleBuffer(), lmms::gui::SetupDialog::SetupDialog(), lmms::Song::Song(), lmms::VstSyncController::VstSyncController(), lmms::AudioBusHandle::~AudioBusHandle(), lmms::PatternTrack::~PatternTrack(), lmms::PresetPreviewPlayHandle::~PresetPreviewPlayHandle(), lmms::RenderManager::~RenderManager(), lmms::SampleTrack::~SampleTrack(), lmms::EffectChain::appendEffect(), lmms::Instrument::applyRelease(), lmms::InstrumentTrack::autoAssignMidiDevice(), lmms::EffectChain::clear(), lmms::Song::clearProject(), lmms::Track::create(), lmms::Track::create(), lmms::Mixer::createRoute(), lmms::SampleRecordHandle::createSampleBuffer(), lmms::anonymous_namespace{SampleDecoder.cpp}::decodeSampleDS(), lmms::Mixer::deleteChannel(), lmms::Mixer::deleteChannelSend(), lmms::gui::TrackContainerView::deleteTrackView(), lmms::AudioBusHandle::doProcessing(), lmms::MixerChannel::doProcessing(), lmms::PlayHandle::doProcessing(), lmms::gui::TrackView::dropEvent(), lmms::gui::MainWindow::finalize(), lmms::NotePlayHandle::framesLeft(), lmms::NotePlayHandle::framesLeftForCurrentPeriod(), lmms::BandLimitedWave::freqToLen(), lmms::Instrument::getSampleRate(), lmms::Oscillator::getWtSampleControl(), lmms::gui::FileBrowserTreeWidget::handleFile(), lmms::NotePlayHandle::index(), lmms::Song::loadingCancelled(), lmms::Song::loadProject(), lmms::SampleClip::loadSettings(), lmms::Track::loadTrack(), main(), lmms::Mixer::masterMix(), lmms::Song::masterVolumeChanged(), lmms::Mixer::mixToChannel(), lmms::Clip::movePosition(), lmms::NotePlayHandle::nphsOfInstrumentTrack(), lmms::gui::FileBrowserTreeWidget::openInNewSampleTrack(), lmms::Oscillator::getSample< Oscillator::WaveShape::Sine >(), lmms::gui::LfoGraph::paintEvent(), lmms::gui::Oscilloscope::paintEvent(), lmms::InstrumentPlayHandle::play(), lmms::InstrumentTrack::play(), lmms::NotePlayHandle::play(), lmms::Sample::play(), lmms::SamplePlayHandle::play(), lmms::SampleRecordHandle::play(), lmms::SampleTrack::play(), lmms::SampleClip::playbackPositionChanged(), lmms::DummyInstrument::playNote(), lmms::Mixer::prepareMasterMix(), lmms::gui::FileBrowserTreeWidget::previewFileItem(), lmms::RemotePlugin::process(), lmms::InstrumentSoundShaping::processAudioBuffer(), lmms::AudioBusHandle::processEffects(), lmms::AutoDetectMidiController::processInEvent(), lmms::InstrumentTrack::processInEvent(), lmms::RemotePlugin::processMessage(), lmms::Song::processNextBuffer(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), lmms::Metronome::processTick(), lmms::gui::ClipView::remove(), lmms::EffectChain::removeEffect(), lmms::RemotePlugin::resizeSharedProcessingMemory(), lmms::ProjectRenderer::run(), lmms::Controller::runningFrames(), lmms::Controller::runningTime(), lmms::gui::Oscilloscope::setActive(), lmms::gui::SetupDialog::setBufferSize(), lmms::AudioBusHandle::setExtOutputEnabled(), lmms::Song::setKeymap(), lmms::gui::SongEditor::setMasterVolume(), lmms::AudioBusHandle::setName(), lmms::SampleClip::setSampleBuffer(), lmms::RingBuffer::setSamplerateAware(), lmms::Song::setScale(), lmms::Song::setTempo(), lmms::InstrumentTrack::silenceAllNotes(), lmms::ProjectRenderer::startProcessing(), lmms::Song::stop(), lmms::gui::FileBrowserTreeWidget::stopPreview(), lmms::Effect::timeout(), lmms::Song::togglePause(), lmms::SamplePlayHandle::totalFrames(), lmms::EnvelopeAndLfoParameters::LfoInstances::trigger(), lmms::Oscillator::update(), lmms::VstSyncController::update(), lmms::gui::Oscilloscope::updateAudioBuffer(), lmms::InstrumentTrack::updateBaseNote(), lmms::SampleTrack::updateClips(), lmms::gui::CPULoadWidget::updateCpuLoad(), lmms::LfoController::updateDuration(), lmms::Oscillator::updateFM(), lmms::EnvelopeAndLfoParameters::updateLfoShapeData(), lmms::VstSyncController::updateSampleRate(), lmms::RingBuffer::updateSamplerate(), lmms::EnvelopeAndLfoParameters::updateSampleVars(), lmms::LfoController::updateValueBuffer(), lmms::PeakController::updateValueBuffer(), and lmms::InstrumentSoundShaping::volumeLevel().
deleteHelper()
template<class T> void lmms::Engine::deleteHelper (T ** ptr) inline static private
Definition at line 125 of file Engine.h.
Referenced by destroy().
destroy()
void lmms::Engine::destroy () static
Definition at line 95 of file Engine.cpp.
References lmms::PresetPreviewPlayHandle::cleanup(), deleteHelper(), lmms::Oscillator::destroyFFTPlans(), lmms::ConfigManager::inst(), s_audioEngine, s_ladspaManager, s_mixer, s_patternStore, s_projectJournal, and s_song.
Referenced by lmms::gui::MainWindow::~MainWindow(), and main().
framesPerTick() [1/2]
float lmms::Engine::framesPerTick () inline static
Definition at line 96 of file Engine.h.
References s_framesPerTick.
Referenced by lmms::Song::currentFrame(), lmms::NotePlayHandle::noteOff(), lmms::gui::AutomationEditor::paintEvent(), lmms::InstrumentTrack::play(), lmms::NotePlayHandle::play(), lmms::PatternTrack::play(), lmms::SampleRecordHandle::play(), lmms::SampleTrack::play(), lmms::InstrumentTrack::processInEvent(), lmms::Song::processNextBuffer(), lmms::SampleClip::sampleLength(), and lmms::Song::stop().
framesPerTick() [2/2]
float lmms::Engine::framesPerTick (sample_rate_t sample_rate) static
Definition at line 129 of file Engine.cpp.
References lmms::DefaultTicksPerBar, and s_song.
getLADSPAManager()
Ladspa2LMMS * lmms::Engine::getLADSPAManager () inline static
Definition at line 91 of file Engine.h.
References s_ladspaManager.
getSong()
Song * lmms::Engine::getSong () inline static
Definition at line 69 of file Engine.h.
References s_song.
Referenced by lmms::gui::AutomationEditor::AutomationEditor(), lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog(), lmms::gui::ControllerRackView::ControllerRackView(), lmms::gui::GuiApplication::GuiApplication(), lmms::LfoController::LfoController(), lmms::gui::MainWindow::MainWindow(), lmms::Microtuner::Microtuner(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::gui::PatternEditor::PatternEditor(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::gui::PianoRoll::PianoRoll(), lmms::gui::PianoView::PianoView(), lmms::gui::ProjectNotes::ProjectNotes(), lmms::SampleClip::SampleClip(), lmms::SampleClip::SampleClip(), lmms::TempoSyncKnobModel::TempoSyncKnobModel(), lmms::gui::TimeLineWidget::TimeLineWidget(), lmms::gui::TrackContainerView::TrackContainerView(), lmms::gui::ControllerRackView::addController(), lmms::gui::ProjectNotes::alignmentChanged(), lmms::gui::MicrotunerConfig::applyKeymap(), lmms::gui::MicrotunerConfig::applyScale(), lmms::StepRecorder::applyStep(), lmms::gui::MainWindow::autoSave(), lmms::InstrumentTrack::baseFreq(), lmms::PathUtil::baseLocation(), lmms::InstrumentTrack::baseNote(), lmms::gui::MidiClipView::bulkClearNotesOutOfBounds(), lmms::Clip::changeLength(), lmms::gui::ExportProjectDialog::closeEvent(), lmms::Plugin::collectErrorForUI(), lmms::AutomationClip::combineAllTracks(), lmms::gui::PianoRoll::constrainNoteLengths(), lmms::gui::TempoSyncBarModelEditor::contextMenuEvent(), lmms::gui::TempoSyncKnob::contextMenuEvent(), lmms::gui::MainWindow::createNewProject(), lmms::gui::TemplatesMenu::createNewProjectFromTemplate(), lmms::AudioEngine::criticalXRuns(), lmms::gui::PianoRoll::cutSelectedNotes(), lmms::Mixer::deleteChannel(), lmms::gui::ControllerRackView::deleteController(), lmms::gui::PianoRoll::deleteSelectedNotes(), lmms::gui::PianoRoll::dragNotes(), lmms::gui::InstrumentTrackWindow::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), lmms::gui::MainApplication::event(), lmms::gui::MainWindow::exportProject(), lmms::gui::MainWindow::finalize(), lmms::ControllerConnection::finalizeConnections(), lmms::gui::AutomationEditor::fineTuneValue(), lmms::gui::PianoRoll::finishRecordNote(), lmms::InstrumentTrack::firstKey(), lmms::gui::PianoRoll::fitNoteLengths(), lmms::gui::ProjectNotes::formatChanged(), lmms::AutomationClip::globalAutomationClip(), lmms::gui::MainWindow::guiSaveProject(), lmms::gui::MainWindow::guiSaveProjectAs(), lmms::gui::FileBrowserTreeWidget::handleFile(), lmms::MidiClip::init(), lmms::RemotePlugin::init(), lmms::Mixer::isChannelInUse(), lmms::InstrumentTrack::isKeyMapped(), lmms::Microtuner::keyToFreq(), lmms::InstrumentTrack::lastKey(), lmms::Track::length(), lmms::Song::loadProject(), lmms::ControllerConnection::loadSettings(), lmms::EnvelopeAndLfoParameters::loadSettings(), lmms::gui::PianoRollWindow::loadSettings(), lmms::LfoController::loadSettings(), lmms::SampleClip::loadSettings(), lmms::TrackContainer::loadSettings(), main(), lmms::gui::MainWindow::mayChangeProject(), lmms::gui::MidiClipView::mergeClips(), lmms::gui::ControllerConnectionDialog::midiToggled(), lmms::gui::AutomationEditor::mouseMoveEvent(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::TimeLineWidget::mouseMoveEvent(), lmms::gui::AutomationEditor::mousePressEvent(), lmms::gui::MidiClipView::mousePressEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::Mixer::moveChannelLeft(), lmms::Clip::movePosition(), lmms::PatternStore::numOfPatterns(), lmms::Microtuner::octaveSize(), lmms::gui::MainWindow::onExportProjectMidi(), lmms::gui::MainWindow::onImportProject(), lmms::gui::MainWindow::onToggleMetronome(), lmms::gui::FileBrowserTreeWidget::openInNewInstrumentTrack(), lmms::gui::PluginDescWidget::openInNewInstrumentTrack(), lmms::gui::FileBrowserTreeWidget::openInNewSampleTrack(), lmms::gui::FileBrowserTreeWidget::openInSlicerT(), lmms::gui::MainWindow::openProject(), lmms::gui::RecentProjectsMenu::openProject(), lmms::gui::AutomationEditor::paintEvent(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::Oscilloscope::paintEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::PositionLine::paintEvent(), lmms::gui::SampleClipView::paintEvent(), lmms::gui::PianoRoll::pasteNotes(), lmms::gui::AutomationEditor::play(), lmms::gui::AutomationEditorWindow::play(), lmms::gui::PatternEditorWindow::play(), lmms::gui::PianoRoll::play(), lmms::gui::SongEditorWindow::play(), lmms::InstrumentTrack::play(), lmms::PatternStore::play(), lmms::SampleTrack::play(), lmms::InstrumentTrack::processAudioBuffer(), lmms::InstrumentTrack::processInEvent(), lmms::gui::PianoRoll::quantizeNotes(), lmms::gui::MixerChannelView::randomizeColor(), lmms::gui::TrackOperationsWidget::randomizeTrackColor(), lmms::gui::PianoRoll::record(), lmms::gui::PianoRoll::recordAccompany(), lmms::ProjectJournal::redo(), lmms::Track::removeClip(), lmms::gui::TrackContentWidget::removeClipView(), lmms::TrackContainer::removeTrack(), lmms::gui::TrackContainerView::removeTrackView(), lmms::gui::MixerChannelView::renameFinished(), lmms::AudioEngine::renderStageNoteSetup(), lmms::RenderManager::renderTracks(), lmms::InstrumentTrack::replaceInstrument(), lmms::gui::TrackOperationsWidget::resetClipColors(), lmms::gui::MixerChannelView::resetColor(), lmms::gui::TrackOperationsWidget::resetTrackColor(), lmms::gui::MainWindow::resetWindowTitle(), lmms::gui::PianoRoll::reverseNotes(), lmms::gui::SampleClipView::reverseSample(), lmms::ProjectRenderer::run(), lmms::gui::MicrotunerConfig::saveKeymapToFile(), lmms::gui::MainWindow::saveProject(), lmms::gui::MainWindow::saveProjectAs(), lmms::gui::MainWindow::saveProjectAsDefaultTemplate(), lmms::gui::MainWindow::saveProjectAsNewVersion(), lmms::gui::MicrotunerConfig::saveScaleToFile(), lmms::AutomatableModel::saveSettings(), lmms::ControllerConnection::saveSettings(), lmms::gui::PianoRollWindow::saveSettings(), lmms::InstrumentTrack::saveTrackSpecificSettings(), lmms::gui::MixerChannelView::selectColor(), lmms::gui::ControllerConnectionDialog::selectController(), lmms::gui::TrackOperationsWidget::selectTrackColor(), lmms::gui::ClipView::setColor(), lmms::gui::PianoRoll::setCurrentMidiClip(), lmms::Track::setName(), lmms::gui::AutomationEditor::setProgressionType(), lmms::SampleClip::setSampleBuffer(), lmms::SampleClip::setSampleFile(), lmms::TempoSyncKnobModel::setScale(), lmms::TempoSyncKnobModel::setSyncMode(), lmms::TempoSyncKnobModel::setTempoSync(), lmms::gui::ExportProjectDialog::startExport(), lmms::gui::PianoRoll::startRecordNote(), lmms::gui::AutomationEditor::stop(), lmms::gui::PatternEditorWindow::stop(), lmms::gui::PianoRoll::stop(), lmms::PatternStore::stop(), lmms::gui::ProjectNotes::textBold(), lmms::gui::InstrumentTrackWindow::textChanged(), lmms::gui::SampleTrackWindow::textChanged(), lmms::gui::ProjectNotes::textFamily(), lmms::gui::ProjectNotes::textItalic(), lmms::gui::ProjectNotes::textSize(), lmms::gui::ProjectNotes::textUnderline(), lmms::gui::Editor::togglePause(), lmms::gui::Editor::togglePlayStop(), lmms::gui::PianoRoll::toggleStepRecording(), lmms::gui::MidiClipView::transposeSelection(), lmms::ProjectJournal::undo(), lmms::PatternStore::updateAfterTrackAdd(), lmms::gui::Oscilloscope::updateAudioBuffer(), lmms::NotePlayHandle::updateFrequency(), lmms::gui::MicrotunerConfig::updateKeymapForm(), lmms::gui::MicrotunerConfig::updateKeymapList(), lmms::Microtuner::updateKeymapList(), lmms::SampleClip::updateLength(), lmms::gui::MixerView::updateMaxChannelSelector(), lmms::MidiPort::updateMidiPortMode(), lmms::LfoController::updatePhase(), lmms::gui::MainWindow::updatePlayPauseIcons(), lmms::gui::AutomationEditor::updatePosition(), lmms::gui::PianoRoll::updatePosition(), lmms::gui::PianoRoll::updatePositionAccompany(), lmms::gui::MicrotunerConfig::updateScaleForm(), lmms::gui::MicrotunerConfig::updateScaleList(), lmms::Microtuner::updateScaleList(), lmms::gui::TimeDisplayWidget::updateTime(), and lmms::gui::MidiClipView::wheelEvent().
init()
void lmms::Engine::init (bool renderOnly) static
Definition at line 58 of file Engine.cpp.
References lmms::BandLimitedWave::generateWaves(), lmms::PresetPreviewPlayHandle::init(), initProgress(), inst(), s_audioEngine, s_ladspaManager, s_mixer, s_patternStore, s_projectJournal, s_song, and lmms::Oscillator::waveTableInit().
Referenced by lmms::gui::GuiApplication::GuiApplication(), and main().
initProgress
void lmms::Engine::initProgress (const QString & msg) signal
Referenced by init().
inst()
Engine * lmms::Engine::inst () inline static
Definition at line 105 of file Engine.h.
References s_instanceOfMe.
Referenced by lmms::gui::GuiApplication::GuiApplication(), and init().
mixer()
Mixer * lmms::Engine::mixer () inline static
Definition at line 64 of file Engine.h.
References s_mixer.
Referenced by lmms::gui::GuiApplication::GuiApplication(), lmms::InstrumentTrack::InstrumentTrack(), lmms::gui::MixerChannelView::MixerChannelView(), lmms::SampleTrack::SampleTrack(), lmms::Song::clearProject(), lmms::gui::InstrumentTrackView::createMixerLine(), lmms::gui::SampleTrackView::createMixerLine(), lmms::gui::InstrumentTrackView::createMixerMenu(), lmms::gui::SampleTrackView::createMixerMenu(), lmms::Mixer::createRoute(), lmms::Mixer::deleteChannelSend(), lmms::AudioBusHandle::doProcessing(), lmms::gui::SendButtonIndicator::getSendModel(), lmms::Song::loadProject(), lmms::InstrumentTrack::loadTrackSpecificSettings(), lmms::SampleTrack::loadTrackSpecificSettings(), lmms::gui::MixerChannelView::mixerChannel(), lmms::gui::SendButtonIndicator::mousePressEvent(), lmms::AudioEngine::renderStageMix(), lmms::AudioEngine::renderStageNoteSetup(), lmms::Song::saveProjectFile(), and lmms::gui::MixerChannelView::setChannelIndex().
patternStore()
PatternStore * lmms::Engine::patternStore () inline static
Definition at line 74 of file Engine.h.
References s_patternStore.
Referenced by lmms::gui::GuiApplication::GuiApplication(), lmms::MidiClip::MidiClip(), lmms::PatternClip::PatternClip(), lmms::PatternTrack::PatternTrack(), lmms::PatternTrack::~PatternTrack(), lmms::gui::FileBrowserTreeWidget::activateListItem(), lmms::Song::addPatternTrack(), lmms::TrackContainer::automatedValuesFromTracks(), lmms::gui::TrackContentWidget::changePosition(), lmms::Song::clearProject(), lmms::gui::PatternTrackView::clickedTrackLabel(), lmms::AutomationClip::combineAllTracks(), lmms::Track::create(), lmms::Song::createNewProject(), lmms::Mixer::deleteChannel(), lmms::gui::PianoRoll::desiredPlayModeForAccompany(), lmms::Song::exportProjectMidi(), lmms::gui::AutomationEditor::inPatternEditor(), lmms::Mixer::isChannelInUse(), lmms::Song::loadProject(), lmms::PatternTrack::loadTrackSpecificSettings(), lmms::gui::ClipView::mouseMoveEvent(), lmms::Mixer::moveChannelLeft(), lmms::gui::FileBrowserTreeWidget::openInNewInstrumentTrack(), lmms::gui::PatternClipView::openInPatternEditor(), lmms::gui::PatternClipView::paintEvent(), lmms::gui::AutomationEditor::play(), lmms::InstrumentTrack::play(), lmms::PatternTrack::play(), lmms::SampleTrack::play(), lmms::Song::processAutomations(), lmms::Song::processNextBuffer(), lmms::RenderManager::renderTracks(), lmms::PatternTrack::saveTrackSpecificSettings(), lmms::gui::AutomationEditor::stop(), lmms::PatternTrack::swapPatternTracks(), lmms::gui::MixerView::updateMaxChannelSelector(), and lmms::MidiClip::updatePatternTrack().
pickDndPluginKey()
void * lmms::Engine::pickDndPluginKey () static
Definition at line 155 of file Engine.cpp.
References s_dndPluginKey.
Referenced by lmms::Plugin::instantiateWithKey().
projectJournal()
ProjectJournal * lmms::Engine::projectJournal () inline static
Definition at line 79 of file Engine.h.
References s_projectJournal.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::gui::SetupDialog::SetupDialog(), lmms::JournallingObject::~JournallingObject(), lmms::gui::SetupDialog::~SetupDialog(), lmms::JournallingObject::addJournalCheckPoint(), lmms::JournallingObject::changeID(), lmms::Song::clearProject(), lmms::Song::createNewProject(), lmms::gui::AutomationClipView::disconnectObject(), lmms::gui::AutomationClipView::dropEvent(), lmms::gui::AutomationEditorWindow::dropEvent(), lmms::gui::AutomationTrackView::dropEvent(), lmms::gui::FloatModelEditorBase::dropEvent(), lmms::ImportFilter::import(), lmms::Song::loadProject(), lmms::gui::MainWindow::redo(), lmms::AutomationClip::resolveAllIDs(), lmms::gui::MainWindow::undo(), and lmms::gui::MainWindow::updateUndoRedoButtons().
setDndPluginKey()
void lmms::Engine::setDndPluginKey (void * newKey) static
Definition at line 146 of file Engine.cpp.
References s_dndPluginKey.
Referenced by lmms::gui::PluginDescWidget::mousePressEvent().
updateFramesPerTick()
void lmms::Engine::updateFramesPerTick () static
Definition at line 138 of file Engine.cpp.
References lmms::DefaultTicksPerBar, s_audioEngine, s_framesPerTick, and s_song.
Referenced by lmms::Song::setTempo(), and lmms::Song::updateFramesPerTick().
Friends And Related Symbol Documentation
gui::GuiApplication
friend class gui::GuiApplication friend
Definition at line 150 of file Engine.h.
Member Data Documentation
s_audioEngine
AudioEngine * lmms::Engine::s_audioEngine = nullptr static private
Definition at line 135 of file Engine.h.
Referenced by audioEngine(), destroy(), init(), and updateFramesPerTick().
s_dndPluginKey
void * lmms::Engine::s_dndPluginKey = nullptr static private
Definition at line 145 of file Engine.h.
Referenced by pickDndPluginKey(), and setDndPluginKey().
s_framesPerTick
float lmms::Engine::s_framesPerTick static private
Definition at line 132 of file Engine.h.
Referenced by framesPerTick(), and updateFramesPerTick().
s_instanceOfMe
Engine * lmms::Engine::s_instanceOfMe = nullptr static private
Definition at line 148 of file Engine.h.
Referenced by inst().
s_ladspaManager
Ladspa2LMMS * lmms::Engine::s_ladspaManager = nullptr static private
Definition at line 144 of file Engine.h.
Referenced by destroy(), getLADSPAManager(), and init().
s_mixer
Mixer * lmms::Engine::s_mixer = nullptr static private
Definition at line 136 of file Engine.h.
Referenced by destroy(), init(), and mixer().
s_patternStore
PatternStore * lmms::Engine::s_patternStore = nullptr static private
Definition at line 138 of file Engine.h.
Referenced by destroy(), init(), and patternStore().
s_projectJournal
ProjectJournal * lmms::Engine::s_projectJournal = nullptr static private
Definition at line 139 of file Engine.h.
Referenced by destroy(), init(), and projectJournal().
s_song
Song * lmms::Engine::s_song = nullptr static private
Definition at line 137 of file Engine.h.
Referenced by destroy(), framesPerTick(), getSong(), init(), and updateFramesPerTick().
The documentation for this class was generated from the following files:
include/Engine.h
src/core/Engine.cpp