LMMS: lmms::AudioEngine Class Reference
lmms::AudioEngine Class Reference
#include <AudioEngine.h>
Classes
class fifoWriter
class RequestChangesGuard
RAII helper for requestChangesInModel.
Signals
void nextAudioBuffer (const lmms::SampleFrame *buffer)
void qualitySettingsChanged ()
void sampleRateChanged ()
Public Member Functions
void addAudioBusHandle (AudioBusHandle *busHandle)
bool addPlayHandle (PlayHandle *handle)
AudioDevice * audioDev ()
const QString & audioDevName () const
bool audioDevStartFailed () const
sample_rate_t baseSampleRate () const
void clear ()
void clearNewPlayHandles ()
int cpuLoad () const
bool criticalXRuns () const
int detailLoad (const AudioEngineProfiler::DetailType type) const
void doneChangeInModel ()
fpp_t framesPerPeriod () const
bool hasFifoWriter () const
void initDevices ()
const SampleFrame * inputBuffer ()
f_cnt_t inputBufferFrames () const
sample_rate_t inputSampleRate () const
float masterGain () const
MidiClient * midiClient ()
const QString & midiClientName () const
const SampleFrame * nextBuffer ()
sample_rate_t outputSampleRate () const
PlayHandleList & playHandles ()
AudioEngineProfiler & profiler ()
void pushInputFrames (SampleFrame *_ab, const f_cnt_t _frames)
void removeAudioBusHandle (AudioBusHandle *busHandle)
void removePlayHandle (PlayHandle *handle)
void removePlayHandlesOfTypes (Track *track, PlayHandle::Types types)
bool renderOnly () const
void requestChangeInModel ()
Block until a change in model can be done (i.e. wait for audio thread).
RequestChangesGuard requestChangesGuard ()
void restoreAudioDevice ()
void setAudioDevice (AudioDevice *_dev, bool _needs_fifo, bool startNow)
Set new audio device.
void setMasterGain (const float mo)
void storeAudioDevice ()
Static Public Member Functions
static sample_t clip (const sample_t s)
static bool isAudioDevNameValid (QString name)
static bool isMidiDevNameValid (QString name)
Private Types
using Fifo = FifoBuffer<SampleFrame*>
Private Member Functions
AudioEngine (bool renderOnly)
~AudioEngine () override
void clearInternal ()
void doSetAudioDevice (AudioDevice *_dev)
const SampleFrame * renderNextBuffer ()
void renderStageEffects ()
void renderStageInstruments ()
void renderStageMix ()
void renderStageNoteSetup ()
void startProcessing (bool needsFifo=true)
void stopProcessing ()
void swapBuffers ()
AudioDevice * tryAudioDevices ()
MidiClient * tryMidiClients ()
Private Attributes
std::vector< AudioBusHandle * > m_audioBusHandles
AudioDevice * m_audioDev
QString m_audioDevName
bool m_audioDevStartFailed
sample_rate_t m_baseSampleRate
std::recursive_mutex m_changeMutex
bool m_clearSignal
Fifo * m_fifo
fifoWriter * m_fifoWriter
fpp_t m_framesPerPeriod
SampleFrame * m_inputBuffer [2]
f_cnt_t m_inputBufferFrames [2]
int m_inputBufferRead
f_cnt_t m_inputBufferSize [2]
int m_inputBufferWrite
float m_masterGain
MidiClient * m_midiClient
QString m_midiClientName
LocklessList< PlayHandle * > m_newPlayHandles
int m_numWorkers
AudioDevice * m_oldAudioDev
std::unique_ptr< SampleFrame[]> m_outputBufferRead
std::unique_ptr< SampleFrame[]> m_outputBufferWrite
PlayHandleList m_playHandles
ConstPlayHandleList m_playHandlesToRemove
AudioEngineProfiler m_profiler
bool m_renderOnly
std::vector< AudioEngineWorkerThread * > m_workers
Friends
class AudioEngineWorkerThread
class Engine
class ProjectRenderer
Detailed Description
Definition at line 64 of file AudioEngine.h.
Member Typedef Documentation
Fifo
using lmms::AudioEngine::Fifo = FifoBuffer<SampleFrame*> private
Definition at line 280 of file AudioEngine.h.
Constructor & Destructor Documentation
AudioEngine()
lmms::AudioEngine::AudioEngine (bool renderOnly) private
Definition at line 73 of file AudioEngine.cpp.
References AudioEngineWorkerThread, lmms::DEFAULT_BUFFER_SIZE, i, lmms::BufferManager::init(), lmms::ConfigManager::inst(), m_audioDev, m_audioDevStartFailed, m_baseSampleRate, m_clearSignal, m_fifo, m_framesPerPeriod, m_inputBuffer, m_inputBufferFrames, m_inputBufferRead, m_inputBufferSize, m_inputBufferWrite, m_masterGain, m_newPlayHandles, m_numWorkers, m_oldAudioDev, m_outputBufferRead, m_outputBufferWrite, m_profiler, m_renderOnly, m_workers, max, lmms::MINIMUM_BUFFER_SIZE, renderOnly(), lmms::ConfigManager::setValue(), lmms::SUPPORTED_SAMPLERATES, and lmms::zeroSampleFrames().
Referenced by lmms::AudioEngine::fifoWriter::fifoWriter().
~AudioEngine()
lmms::AudioEngine::~AudioEngine () override private
Definition at line 154 of file AudioEngine.cpp.
References m_audioDev, m_fifo, m_inputBuffer, m_midiClient, m_numWorkers, m_workers, and lmms::AudioEngineWorkerThread::startAndWaitForJobs().
Member Function Documentation
addAudioBusHandle()
void lmms::AudioEngine::addAudioBusHandle (AudioBusHandle * busHandle) inline
Definition at line 139 of file AudioEngine.h.
References doneChangeInModel(), m_audioBusHandles, and requestChangeInModel().
Referenced by lmms::AudioBusHandle::AudioBusHandle().
addPlayHandle()
bool lmms::AudioEngine::addPlayHandle (PlayHandle * handle)
Definition at line 543 of file AudioEngine.cpp.
References lmms::AudioBusHandle::addPlayHandle(), lmms::PlayHandle::audioBusHandle(), criticalXRuns(), lmms::PlayHandle::InstrumentPlayHandle, m_newPlayHandles, lmms::PlayHandle::NotePlayHandle, lmms::NotePlayHandleManager::release(), and lmms::PlayHandle::type().
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::InstrumentTrack::play(), lmms::SampleTrack::play(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), and lmms::Metronome::processTick().
audioDev()
AudioDevice * lmms::AudioEngine::audioDev () inline
Definition at line 132 of file AudioEngine.h.
References m_audioDev.
Referenced by lmms::AudioBusHandle::setExtOutputEnabled(), and lmms::AudioBusHandle::setName().
audioDevName()
const QString & lmms::AudioEngine::audioDevName () const inline
Definition at line 118 of file AudioEngine.h.
References m_audioDevName.
Referenced by lmms::gui::SetupDialog::SetupDialog().
audioDevStartFailed()
bool lmms::AudioEngine::audioDevStartFailed () const inline
Definition at line 122 of file AudioEngine.h.
References m_audioDevStartFailed.
baseSampleRate()
sample_rate_t lmms::AudioEngine::baseSampleRate () const inline
Definition at line 196 of file AudioEngine.h.
References m_baseSampleRate.
Referenced by lmms::gui::LfoGraph::paintEvent().
clear()
void lmms::AudioEngine::clear ()
Definition at line 430 of file AudioEngine.cpp.
References m_clearSignal.
Referenced by lmms::Song::stop(), and lmms::Song::togglePause().
clearInternal()
void lmms::AudioEngine::clearInternal () private
Definition at line 454 of file AudioEngine.cpp.
References lmms::PlayHandle::InstrumentPlayHandle, m_playHandles, and m_playHandlesToRemove.
Referenced by renderStageNoteSetup().
clearNewPlayHandles()
void lmms::AudioEngine::clearNewPlayHandles ()
Definition at line 438 of file AudioEngine.cpp.
References doneChangeInModel(), m_newPlayHandles, and requestChangeInModel().
clip()
sample_t lmms::AudioEngine::clip (const sample_t s) inline static
Definition at line 222 of file AudioEngine.h.
Referenced by lmms::AudioDevice::convertToS16(), and lmms::gui::Oscilloscope::paintEvent().
cpuLoad()
int lmms::AudioEngine::cpuLoad () const inline
Definition at line 186 of file AudioEngine.h.
References m_profiler.
Referenced by criticalXRuns(), and lmms::gui::CPULoadWidget::updateCpuLoad().
criticalXRuns()
bool lmms::AudioEngine::criticalXRuns () const
Definition at line 243 of file AudioEngine.cpp.
References cpuLoad(), lmms::Engine::getSong(), and lmms::Song::isExporting().
Referenced by addPlayHandle().
detailLoad()
int lmms::AudioEngine::detailLoad (const AudioEngineProfiler::DetailType type) const inline
Definition at line 191 of file AudioEngine.h.
References m_profiler.
doneChangeInModel()
void lmms::AudioEngine::doneChangeInModel ()
Definition at line 656 of file AudioEngine.cpp.
References m_changeMutex, and lmms::s_renderingThread.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::PresetPreviewPlayHandle::~PresetPreviewPlayHandle(), addAudioBusHandle(), lmms::EffectChain::appendEffect(), lmms::EffectChain::clear(), clearNewPlayHandles(), lmms::Song::clearProject(), lmms::Track::create(), lmms::Track::create(), lmms::Mixer::createRoute(), lmms::Mixer::deleteChannel(), lmms::Mixer::deleteChannelSend(), lmms::gui::TrackContainerView::deleteTrackView(), lmms::gui::TrackView::dropEvent(), lmms::gui::FileBrowserTreeWidget::handleFile(), lmms::Song::loadProject(), lmms::Clip::movePosition(), lmms::gui::FileBrowserTreeWidget::openInNewSampleTrack(), lmms::InstrumentTrack::processInEvent(), pushInputFrames(), removeAudioBusHandle(), lmms::EffectChain::removeEffect(), removePlayHandle(), removePlayHandlesOfTypes(), lmms::Song::setKeymap(), lmms::Song::setScale(), lmms::Song::setTempo(), lmms::InstrumentTrack::silenceAllNotes(), lmms::Song::stop(), and lmms::InstrumentTrack::updateBaseNote().
doSetAudioDevice()
void lmms::AudioEngine::doSetAudioDevice (AudioDevice * _dev) private
Definition at line 466 of file AudioEngine.cpp.
References m_audioDev, m_oldAudioDev, and tryAudioDevices().
Referenced by setAudioDevice().
framesPerPeriod()
fpp_t lmms::AudioEngine::framesPerPeriod () const inline
Definition at line 175 of file AudioEngine.h.
References m_framesPerPeriod.
Referenced by lmms::EnvelopeAndLfoParameters::EnvelopeAndLfoParameters(), lmms::gui::Oscilloscope::Oscilloscope(), lmms::VstSyncController::VstSyncController(), lmms::Instrument::applyRelease(), lmms::AudioBusHandle::doProcessing(), lmms::MixerChannel::doProcessing(), lmms::NotePlayHandle::framesLeft(), lmms::AudioDevice::getNextBuffer(), lmms::Mixer::masterMix(), lmms::gui::Oscilloscope::paintEvent(), lmms::InstrumentPlayHandle::play(), lmms::NotePlayHandle::play(), lmms::Sample::play(), lmms::SamplePlayHandle::play(), lmms::RemotePlugin::process(), lmms::Song::processNextBuffer(), lmms::AudioDummy::run(), lmms::Controller::runningFrames(), lmms::AudioFileFlac::startEncoding(), lmms::AudioFileWave::startEncoding(), lmms::EnvelopeAndLfoParameters::LfoInstances::trigger(), lmms::VstSyncController::update(), lmms::gui::Oscilloscope::updateAudioBuffer(), lmms::EnvelopeAndLfoParameters::updateLfoShapeData(), lmms::LfoController::updateValueBuffer(), lmms::PeakController::updateValueBuffer(), and lmms::InstrumentSoundShaping::volumeLevel().
hasFifoWriter()
bool lmms::AudioEngine::hasFifoWriter () const inline
Definition at line 238 of file AudioEngine.h.
References m_fifoWriter.
Referenced by nextBuffer().
initDevices()
void lmms::AudioEngine::initDevices ()
Definition at line 187 of file AudioEngine.cpp.
References m_audioDev, m_audioDevName, m_midiClient, m_midiClientName, m_renderOnly, lmms::AudioDummy::name(), lmms::MidiDummy::name(), sampleRateChanged(), tryAudioDevices(), and tryMidiClients().
inputBuffer()
const SampleFrame * lmms::AudioEngine::inputBuffer () inline
Definition at line 245 of file AudioEngine.h.
References m_inputBuffer, and m_inputBufferRead.
Referenced by lmms::SampleRecordHandle::play().
inputBufferFrames()
f_cnt_t lmms::AudioEngine::inputBufferFrames () const inline
Definition at line 250 of file AudioEngine.h.
References m_inputBufferFrames, and m_inputBufferRead.
Referenced by lmms::SampleRecordHandle::play().
inputSampleRate()
sample_rate_t lmms::AudioEngine::inputSampleRate () const inline
Definition at line 205 of file AudioEngine.h.
References m_audioDev, and m_baseSampleRate.
isAudioDevNameValid()
bool lmms::AudioEngine::isAudioDevNameValid (QString name) static
Definition at line 662 of file AudioEngine.cpp.
References lmms::AudioDummy::name().
Referenced by lmms::gui::MainWindow::finalize(), and tryAudioDevices().
isMidiDevNameValid()
bool lmms::AudioEngine::isMidiDevNameValid (QString name) static
Definition at line 733 of file AudioEngine.cpp.
References lmms::MidiDummy::name().
Referenced by tryMidiClients().
masterGain()
float lmms::AudioEngine::masterGain () const inline
Definition at line 211 of file AudioEngine.h.
References m_masterGain.
Referenced by lmms::gui::Oscilloscope::paintEvent().
midiClient()
MidiClient * lmms::AudioEngine::midiClient () inline
Definition at line 155 of file AudioEngine.h.
References m_midiClient.
Referenced by lmms::AutoDetectMidiController::processInEvent().
midiClientName()
const QString & lmms::AudioEngine::midiClientName () const inline
Definition at line 150 of file AudioEngine.h.
References m_midiClientName.
Referenced by lmms::gui::SetupDialog::SetupDialog().
nextAudioBuffer
void lmms::AudioEngine::nextAudioBuffer (const lmms::SampleFrame * buffer) signal
Referenced by renderStageMix().
nextBuffer()
const SampleFrame * lmms::AudioEngine::nextBuffer () inline
Definition at line 255 of file AudioEngine.h.
References hasFifoWriter(), m_fifo, and renderNextBuffer().
Referenced by lmms::AudioDevice::getNextBuffer(), lmms::AudioDummy::run(), and lmms::ProjectRenderer::run().
outputSampleRate()
sample_rate_t lmms::AudioEngine::outputSampleRate () const inline
Definition at line 199 of file AudioEngine.h.
References m_audioDev, and m_baseSampleRate.
Referenced by lmms::anonymous_namespace{SampleDecoder.cpp}::decodeSampleDS(), lmms::Instrument::getSampleRate(), lmms::SampleClip::loadSettings(), lmms::Oscillator::getSample< Oscillator::WaveShape::Sine >(), lmms::Sample::play(), lmms::InstrumentSoundShaping::processAudioBuffer(), renderNextBuffer(), lmms::AudioDummy::run(), lmms::Controller::runningTime(), lmms::SamplePlayHandle::totalFrames(), lmms::LfoController::updateDuration(), lmms::Oscillator::updateFM(), lmms::VstSyncController::updateSampleRate(), lmms::RingBuffer::updateSamplerate(), lmms::EnvelopeAndLfoParameters::updateSampleVars(), and lmms::PeakController::updateValueBuffer().
playHandles()
PlayHandleList & lmms::AudioEngine::playHandles () inline
Definition at line 166 of file AudioEngine.h.
References m_playHandles.
Referenced by lmms::NotePlayHandle::index(), lmms::NotePlayHandle::nphsOfInstrumentTrack(), and lmms::Song::setTempo().
profiler()
AudioEngineProfiler & lmms::AudioEngine::profiler () inline
Definition at line 181 of file AudioEngine.h.
References m_profiler.
pushInputFrames()
void lmms::AudioEngine::pushInputFrames (SampleFrame * _ab, const f_cnt_t _frames)
Definition at line 251 of file AudioEngine.cpp.
References doneChangeInModel(), m_inputBuffer, m_inputBufferFrames, m_inputBufferSize, m_inputBufferWrite, and requestChangeInModel().
qualitySettingsChanged
void lmms::AudioEngine::qualitySettingsChanged () signal
Referenced by setAudioDevice().
removeAudioBusHandle()
void lmms::AudioEngine::removeAudioBusHandle (AudioBusHandle * busHandle)
Definition at line 530 of file AudioEngine.cpp.
References doneChangeInModel(), m_audioBusHandles, and requestChangeInModel().
Referenced by lmms::AudioBusHandle::~AudioBusHandle().
removePlayHandle()
void lmms::AudioEngine::removePlayHandle (PlayHandle * handle)
Definition at line 565 of file AudioEngine.cpp.
References lmms::PlayHandle::affinity(), lmms::PlayHandle::affinityMatters(), lmms::PlayHandle::audioBusHandle(), doneChangeInModel(), m_newPlayHandles, m_playHandles, m_playHandlesToRemove, lmms::PlayHandle::NotePlayHandle, lmms::NotePlayHandleManager::release(), lmms::AudioBusHandle::removePlayHandle(), requestChangeInModel(), and lmms::PlayHandle::type().
Referenced by lmms::gui::FileBrowserTreeWidget::stopPreview().
removePlayHandlesOfTypes()
void lmms::AudioEngine::removePlayHandlesOfTypes (Track * track, PlayHandle::Types types)
Definition at line 623 of file AudioEngine.cpp.
References doneChangeInModel(), m_playHandles, lmms::PlayHandle::NotePlayHandle, lmms::NotePlayHandleManager::release(), and requestChangeInModel().
Referenced by lmms::PatternTrack::~PatternTrack(), lmms::SampleTrack::~SampleTrack(), lmms::SampleClip::playbackPositionChanged(), lmms::InstrumentTrack::silenceAllNotes(), and lmms::SampleTrack::updateClips().
renderNextBuffer()
const SampleFrame * lmms::AudioEngine::renderNextBuffer () private
Definition at line 399 of file AudioEngine.cpp.
References m_changeMutex, m_framesPerPeriod, m_outputBufferRead, m_profiler, outputSampleRate(), renderStageEffects(), renderStageInstruments(), renderStageMix(), renderStageNoteSetup(), and lmms::s_renderingThread.
Referenced by nextBuffer().
renderOnly()
bool lmms::AudioEngine::renderOnly () const inline
Definition at line 115 of file AudioEngine.h.
References m_renderOnly.
Referenced by AudioEngine().
renderStageEffects()
void lmms::AudioEngine::renderStageEffects () private
Definition at line 343 of file AudioEngine.cpp.
References lmms::AudioEngineProfiler::Effects, lmms::AudioEngineWorkerThread::fillJobQueue(), m_audioBusHandles, m_playHandles, m_profiler, lmms::PlayHandle::NotePlayHandle, lmms::NotePlayHandleManager::release(), and lmms::AudioEngineWorkerThread::startAndWaitForJobs().
Referenced by renderNextBuffer().
renderStageInstruments()
void lmms::AudioEngine::renderStageInstruments () private
Definition at line 333 of file AudioEngine.cpp.
References lmms::AudioEngineWorkerThread::fillJobQueue(), lmms::AudioEngineProfiler::Instruments, m_playHandles, m_profiler, and lmms::AudioEngineWorkerThread::startAndWaitForJobs().
Referenced by renderNextBuffer().
renderStageMix()
void lmms::AudioEngine::renderStageMix () private
Definition at line 380 of file AudioEngine.cpp.
References lmms::AutomatableModel::incrementPeriodCounter(), lmms::EnvelopeAndLfoParameters::instances(), m_framesPerPeriod, m_masterGain, m_outputBufferRead, m_outputBufferWrite, m_profiler, lmms::Mixer::masterMix(), lmms::Engine::mixer(), lmms::AudioEngineProfiler::Mixing, lmms::MixHelpers::multiply(), nextAudioBuffer(), lmms::EnvelopeAndLfoParameters::LfoInstances::trigger(), and lmms::Controller::triggerFrameCounter().
Referenced by renderNextBuffer().
renderStageNoteSetup()
void lmms::AudioEngine::renderStageNoteSetup () private
Definition at line 280 of file AudioEngine.cpp.
References clearInternal(), lmms::Engine::getSong(), m_clearSignal, m_newPlayHandles, m_playHandles, m_playHandlesToRemove, m_profiler, lmms::Engine::mixer(), lmms::PlayHandle::NotePlayHandle, lmms::AudioEngineProfiler::NoteSetup, lmms::Mixer::prepareMasterMix(), lmms::Song::processNextBuffer(), lmms::NotePlayHandleManager::release(), and swapBuffers().
Referenced by renderNextBuffer().
requestChangeInModel()
void lmms::AudioEngine::requestChangeInModel ()
Block until a change in model can be done (i.e. wait for audio thread).
Definition at line 650 of file AudioEngine.cpp.
References m_changeMutex, and lmms::s_renderingThread.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::PresetPreviewPlayHandle::~PresetPreviewPlayHandle(), addAudioBusHandle(), lmms::EffectChain::appendEffect(), lmms::EffectChain::clear(), clearNewPlayHandles(), lmms::Song::clearProject(), lmms::Track::create(), lmms::Track::create(), lmms::Mixer::createRoute(), lmms::Mixer::deleteChannel(), lmms::Mixer::deleteChannelSend(), lmms::gui::TrackContainerView::deleteTrackView(), lmms::gui::TrackView::dropEvent(), lmms::gui::FileBrowserTreeWidget::handleFile(), lmms::Song::loadProject(), lmms::Clip::movePosition(), lmms::gui::FileBrowserTreeWidget::openInNewSampleTrack(), lmms::InstrumentTrack::processInEvent(), pushInputFrames(), removeAudioBusHandle(), lmms::EffectChain::removeEffect(), removePlayHandle(), removePlayHandlesOfTypes(), lmms::Song::setKeymap(), lmms::Song::setScale(), lmms::Song::setTempo(), lmms::InstrumentTrack::silenceAllNotes(), lmms::Song::stop(), and lmms::InstrumentTrack::updateBaseNote().
requestChangesGuard()
RequestChangesGuard lmms::AudioEngine::requestChangesGuard () inline
Definition at line 264 of file AudioEngine.h.
Referenced by lmms::Track::loadTrack(), lmms::gui::ClipView::remove(), and lmms::SampleClip::setSampleBuffer().
restoreAudioDevice()
void lmms::AudioEngine::restoreAudioDevice ()
Definition at line 512 of file AudioEngine.cpp.
References m_audioDev, m_oldAudioDev, sampleRateChanged(), startProcessing(), and stopProcessing().
Referenced by lmms::RenderManager::~RenderManager().
sampleRateChanged
void lmms::AudioEngine::sampleRateChanged () signal
Referenced by lmms::VstSyncController::VstSyncController(), initDevices(), restoreAudioDevice(), and setAudioDevice().
setAudioDevice()
void lmms::AudioEngine::setAudioDevice (AudioDevice * _dev, bool _needs_fifo, bool startNow)
Set new audio device.
Old device will be deleted, unless it's stored using storeAudioDevice
Definition at line 486 of file AudioEngine.cpp.
References doSetAudioDevice(), qualitySettingsChanged(), sampleRateChanged(), startProcessing(), and stopProcessing().
Referenced by lmms::ProjectRenderer::startProcessing().
setMasterGain()
void lmms::AudioEngine::setMasterGain (const float mo) inline
Definition at line 216 of file AudioEngine.h.
References m_masterGain.
Referenced by lmms::Song::masterVolumeChanged(), and lmms::gui::SongEditor::setMasterVolume().
startProcessing()
void lmms::AudioEngine::startProcessing (bool needsFifo = true) private
Definition at line 206 of file AudioEngine.cpp.
References m_audioDev, m_fifo, and m_fifoWriter.
Referenced by restoreAudioDevice(), lmms::ProjectRenderer::run(), and setAudioDevice().
stopProcessing()
void lmms::AudioEngine::stopProcessing () private
Definition at line 224 of file AudioEngine.cpp.
References m_audioDev, and m_fifoWriter.
Referenced by restoreAudioDevice(), lmms::ProjectRenderer::run(), and setAudioDevice().
storeAudioDevice()
void lmms::AudioEngine::storeAudioDevice ()
Definition at line 501 of file AudioEngine.cpp.
References m_audioDev, and m_oldAudioDev.
Referenced by lmms::RenderManager::RenderManager().
swapBuffers()
void lmms::AudioEngine::swapBuffers () private
Definition at line 420 of file AudioEngine.cpp.
References m_framesPerPeriod, m_inputBufferFrames, m_inputBufferRead, m_inputBufferWrite, m_outputBufferRead, m_outputBufferWrite, and lmms::zeroSampleFrames().
Referenced by renderStageNoteSetup().
tryAudioDevices()
AudioDevice * lmms::AudioEngine::tryAudioDevices () private
Definition at line 785 of file AudioEngine.cpp.
References lmms::ConfigManager::inst(), isAudioDevNameValid(), m_audioDevName, m_audioDevStartFailed, lmms::AudioDummy::name(), and lmms::ConfigManager::value().
Referenced by doSetAudioDevice(), and initDevices().
tryMidiClients()
MidiClient * lmms::AudioEngine::tryMidiClients () private
Definition at line 933 of file AudioEngine.cpp.
References lmms::ConfigManager::inst(), isMidiDevNameValid(), m_midiClientName, lmms::MidiDummy::name(), and lmms::ConfigManager::value().
Referenced by initDevices().
Friends And Related Symbol Documentation
AudioEngineWorkerThread
friend class AudioEngineWorkerThread friend
Definition at line 372 of file AudioEngine.h.
References AudioEngineWorkerThread.
Referenced by AudioEngine(), and AudioEngineWorkerThread.
Engine
friend class Engine friend
Definition at line 371 of file AudioEngine.h.
References Engine.
Referenced by Engine.
ProjectRenderer
friend class ProjectRenderer friend
Definition at line 373 of file AudioEngine.h.
References ProjectRenderer.
Referenced by ProjectRenderer.
Member Data Documentation
m_audioBusHandles
std::vector<AudioBusHandle*> lmms::AudioEngine::m_audioBusHandles private
Definition at line 324 of file AudioEngine.h.
Referenced by addAudioBusHandle(), removeAudioBusHandle(), and renderStageEffects().
m_audioDev
AudioDevice* lmms::AudioEngine::m_audioDev private
Definition at line 352 of file AudioEngine.h.
Referenced by AudioEngine(), ~AudioEngine(), audioDev(), doSetAudioDevice(), initDevices(), inputSampleRate(), outputSampleRate(), restoreAudioDevice(), startProcessing(), stopProcessing(), and storeAudioDevice().
m_audioDevName
QString lmms::AudioEngine::m_audioDevName private
Definition at line 354 of file AudioEngine.h.
Referenced by audioDevName(), initDevices(), and tryAudioDevices().
m_audioDevStartFailed
bool lmms::AudioEngine::m_audioDevStartFailed private
Definition at line 355 of file AudioEngine.h.
Referenced by AudioEngine(), audioDevStartFailed(), and tryAudioDevices().
m_baseSampleRate
sample_rate_t lmms::AudioEngine::m_baseSampleRate private
Definition at line 331 of file AudioEngine.h.
Referenced by AudioEngine(), baseSampleRate(), inputSampleRate(), and outputSampleRate().
m_changeMutex
std::recursive_mutex lmms::AudioEngine::m_changeMutex private
Definition at line 369 of file AudioEngine.h.
Referenced by doneChangeInModel(), renderNextBuffer(), and requestChangeInModel().
m_clearSignal
bool lmms::AudioEngine::m_clearSignal private
Definition at line 367 of file AudioEngine.h.
Referenced by AudioEngine(), clear(), and renderStageNoteSetup().
m_fifo
Fifo* lmms::AudioEngine::m_fifo private
Definition at line 362 of file AudioEngine.h.
Referenced by AudioEngine(), ~AudioEngine(), nextBuffer(), and startProcessing().
m_fifoWriter
fifoWriter* lmms::AudioEngine::m_fifoWriter private
Definition at line 363 of file AudioEngine.h.
Referenced by hasFifoWriter(), startProcessing(), and stopProcessing().
m_framesPerPeriod
fpp_t lmms::AudioEngine::m_framesPerPeriod private
Definition at line 326 of file AudioEngine.h.
Referenced by AudioEngine(), framesPerPeriod(), renderNextBuffer(), renderStageMix(), and swapBuffers().
m_inputBuffer
SampleFrame* lmms::AudioEngine::m_inputBuffer[2] private
Definition at line 328 of file AudioEngine.h.
Referenced by AudioEngine(), ~AudioEngine(), inputBuffer(), and pushInputFrames().
m_inputBufferFrames
f_cnt_t lmms::AudioEngine::m_inputBufferFrames[2] private
Definition at line 329 of file AudioEngine.h.
Referenced by AudioEngine(), inputBufferFrames(), pushInputFrames(), and swapBuffers().
m_inputBufferRead
int lmms::AudioEngine::m_inputBufferRead private
Definition at line 332 of file AudioEngine.h.
Referenced by AudioEngine(), inputBuffer(), inputBufferFrames(), and swapBuffers().
m_inputBufferSize
f_cnt_t lmms::AudioEngine::m_inputBufferSize[2] private
Definition at line 330 of file AudioEngine.h.
Referenced by AudioEngine(), and pushInputFrames().
m_inputBufferWrite
int lmms::AudioEngine::m_inputBufferWrite private
Definition at line 333 of file AudioEngine.h.
Referenced by AudioEngine(), pushInputFrames(), and swapBuffers().
m_masterGain
float lmms::AudioEngine::m_masterGain private
Definition at line 348 of file AudioEngine.h.
Referenced by AudioEngine(), masterGain(), renderStageMix(), and setMasterGain().
m_midiClient
MidiClient* lmms::AudioEngine::m_midiClient private
Definition at line 358 of file AudioEngine.h.
Referenced by ~AudioEngine(), initDevices(), and midiClient().
m_midiClientName
QString lmms::AudioEngine::m_midiClientName private
Definition at line 359 of file AudioEngine.h.
Referenced by initDevices(), midiClientName(), and tryMidiClients().
m_newPlayHandles
LocklessList<PlayHandle *> lmms::AudioEngine::m_newPlayHandles private
Definition at line 345 of file AudioEngine.h.
Referenced by AudioEngine(), addPlayHandle(), clearNewPlayHandles(), removePlayHandle(), and renderStageNoteSetup().
m_numWorkers
int lmms::AudioEngine::m_numWorkers private
Definition at line 340 of file AudioEngine.h.
Referenced by AudioEngine(), and ~AudioEngine().
m_oldAudioDev
AudioDevice* lmms::AudioEngine::m_oldAudioDev private
Definition at line 353 of file AudioEngine.h.
Referenced by AudioEngine(), doSetAudioDevice(), restoreAudioDevice(), and storeAudioDevice().
m_outputBufferRead
std::unique_ptr<SampleFrame[]> lmms::AudioEngine::m_outputBufferRead private
Definition at line 335 of file AudioEngine.h.
Referenced by AudioEngine(), renderNextBuffer(), renderStageMix(), and swapBuffers().
m_outputBufferWrite
std::unique_ptr<SampleFrame[]> lmms::AudioEngine::m_outputBufferWrite private
Definition at line 336 of file AudioEngine.h.
Referenced by AudioEngine(), renderStageMix(), and swapBuffers().
m_playHandles
PlayHandleList lmms::AudioEngine::m_playHandles private
Definition at line 343 of file AudioEngine.h.
Referenced by clearInternal(), playHandles(), removePlayHandle(), removePlayHandlesOfTypes(), renderStageEffects(), renderStageInstruments(), and renderStageNoteSetup().
m_playHandlesToRemove
ConstPlayHandleList lmms::AudioEngine::m_playHandlesToRemove private
Definition at line 346 of file AudioEngine.h.
Referenced by clearInternal(), removePlayHandle(), and renderStageNoteSetup().
m_profiler
AudioEngineProfiler lmms::AudioEngine::m_profiler private
Definition at line 365 of file AudioEngine.h.
Referenced by AudioEngine(), cpuLoad(), detailLoad(), profiler(), renderNextBuffer(), renderStageEffects(), renderStageInstruments(), renderStageMix(), and renderStageNoteSetup().
m_renderOnly
bool lmms::AudioEngine::m_renderOnly private
Definition at line 322 of file AudioEngine.h.
Referenced by AudioEngine(), initDevices(), and renderOnly().
m_workers
std::vector<AudioEngineWorkerThread *> lmms::AudioEngine::m_workers private
Definition at line 339 of file AudioEngine.h.
Referenced by AudioEngine(), and ~AudioEngine().
The documentation for this class was generated from the following files:
include/AudioEngine.h
src/core/AudioEngine.cpp