LMMS: lmms::VstSyncController Class Reference
lmms::VstSyncController Class Reference
#include <VstSyncController.h>
Public Member Functions
VstSyncController ()
void setAbsolutePosition (double ticks)
void setPlaybackJumped (bool jumped)
void setPlaybackState (bool enabled)
void setTempo (int newTempo)
void setTimeSignature (int num, int denom)
const std::string & sharedMemoryKey () const noexcept
void startCycle (int startTick, int endTick)
void stopCycle ()
void update ()
Private Slots
void updateSampleRate ()
Private Attributes
SharedMemory< VstSyncData > m_syncData
Detailed Description
Definition at line 37 of file VstSyncController.h.
Constructor & Destructor Documentation
VstSyncController()
lmms::VstSyncController::VstSyncController ()
Definition at line 40 of file VstSyncController.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), m_syncData, lmms::AudioEngine::sampleRateChanged(), and updateSampleRate().
Member Function Documentation
setAbsolutePosition()
void lmms::VstSyncController::setAbsolutePosition (double ticks)
Definition at line 63 of file VstSyncController.cpp.
References m_syncData.
setPlaybackJumped()
void lmms::VstSyncController::setPlaybackJumped (bool jumped)
Definition at line 129 of file VstSyncController.cpp.
References m_syncData.
setPlaybackState()
void lmms::VstSyncController::setPlaybackState (bool enabled)
Definition at line 76 of file VstSyncController.cpp.
References m_syncData.
setTempo()
void lmms::VstSyncController::setTempo (int newTempo)
Definition at line 85 of file VstSyncController.cpp.
References m_syncData.
setTimeSignature()
void lmms::VstSyncController::setTimeSignature (int num, int denom)
Definition at line 99 of file VstSyncController.cpp.
References m_syncData.
sharedMemoryKey()
const std::string & lmms::VstSyncController::sharedMemoryKey () const inline noexcept
Definition at line 52 of file VstSyncController.h.
References m_syncData.
startCycle()
void lmms::VstSyncController::startCycle (int startTick, int endTick)
Definition at line 109 of file VstSyncController.cpp.
References m_syncData.
stopCycle()
void lmms::VstSyncController::stopCycle ()
Definition at line 120 of file VstSyncController.cpp.
References m_syncData.
update()
void lmms::VstSyncController::update ()
Definition at line 138 of file VstSyncController.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), and m_syncData.
updateSampleRate
void lmms::VstSyncController::updateSampleRate () private slot
Definition at line 151 of file VstSyncController.cpp.
References lmms::Engine::audioEngine(), m_syncData, and lmms::AudioEngine::outputSampleRate().
Referenced by VstSyncController().
Member Data Documentation
m_syncData
SharedMemory<VstSyncData> lmms::VstSyncController::m_syncData private
Definition at line 58 of file VstSyncController.h.
Referenced by VstSyncController(), setAbsolutePosition(), setPlaybackJumped(), setPlaybackState(), setTempo(), setTimeSignature(), sharedMemoryKey(), startCycle(), stopCycle(), update(), and updateSampleRate().
The documentation for this class was generated from the following files:
include/VstSyncController.h
src/core/VstSyncController.cpp