LMMS: hiir::Upsampler2xF64Sse2< NC > Class Template Reference
hiir::Upsampler2xF64Sse2< NC > Class Template Reference
#include <Upsampler2xF64Sse2.h>
Public Types
typedef double DataType
Public Member Functions
Upsampler2xF64Sse2 () noexcept
Upsampler2xF64Sse2 (const Upsampler2xF64Sse2< NC > &other)=default
Upsampler2xF64Sse2 (Upsampler2xF64Sse2< NC > &&other)=default
void clear_buffers () noexcept
Upsampler2xF64Sse2< NC > & operator= (const Upsampler2xF64Sse2< NC > &other)=default
Upsampler2xF64Sse2< NC > & operator= (Upsampler2xF64Sse2< NC > &&other)=default
void process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (double &out_0, double &out_1, double input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Sse2, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Upsampler2xF64Sse2< NC > &other) const =delete
bool operator== (const Upsampler2xF64Sse2< NC > &other) const =delete
hiir_FORCEINLINE long process_block_double (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _nbr_stages
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::Upsampler2xF64Sse2< NC >
Definition at line 41 of file Upsampler2xF64Sse2.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::Upsampler2xF64Sse2< NC >::DataType
Definition at line 50 of file Upsampler2xF64Sse2.h.
Filter
template<int NC> typedef std::array<StageDataF64Sse2, _nbr_stages + 1> hiir::Upsampler2xF64Sse2< NC >::Filter private
Definition at line 89 of file Upsampler2xF64Sse2.h.
Constructor & Destructor Documentation
Upsampler2xF64Sse2() [1/3]
template<int NC> hiir::Upsampler2xF64Sse2< NC >::Upsampler2xF64Sse2 () noexcept
Definition at line 55 of file Upsampler2xF64Sse2.hpp.
References _filter, _nbr_stages, clear_buffers(), i, and NBR_COEFS.
Referenced by Upsampler2xF64Sse2(), Upsampler2xF64Sse2(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2xF64Sse2() [2/3]
template<int NC> hiir::Upsampler2xF64Sse2< NC >::Upsampler2xF64Sse2 (const Upsampler2xF64Sse2< NC > & other) default
References Upsampler2xF64Sse2().
Upsampler2xF64Sse2() [3/3]
template<int NC> hiir::Upsampler2xF64Sse2< NC >::Upsampler2xF64Sse2 (Upsampler2xF64Sse2< NC > && other) default
References Upsampler2xF64Sse2().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2xF64Sse2< NC >::clear_buffers () noexcept
Definition at line 170 of file Upsampler2xF64Sse2.hpp.
References _filter, _nbr_stages, and i.
Referenced by Upsampler2xF64Sse2(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2xF64Sse2< NC >::operator!= (const Upsampler2xF64Sse2< NC > & other) const private delete
References Upsampler2xF64Sse2().
operator=() [1/2]
template<int NC> Upsampler2xF64Sse2< NC > & hiir::Upsampler2xF64Sse2< NC >::operator= (const Upsampler2xF64Sse2< NC > & other) default
References Upsampler2xF64Sse2().
operator=() [2/2]
template<int NC> Upsampler2xF64Sse2< NC > & hiir::Upsampler2xF64Sse2< NC >::operator= (Upsampler2xF64Sse2< NC > && other) default
References Upsampler2xF64Sse2(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2xF64Sse2< NC >::operator== (const Upsampler2xF64Sse2< NC > & other) const private delete
References Upsampler2xF64Sse2().
process_block()
template<int NC> void hiir::Upsampler2xF64Sse2< NC >::process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 143 of file Upsampler2xF64Sse2.hpp.
References process_block_double(), and process_sample().
Referenced by operator=().
process_block_double()
template<int NC> long hiir::Upsampler2xF64Sse2< NC >::process_block_double (double out_ptr[], const double in_ptr[], long nbr_spl) private noexcept
Definition at line 196 of file Upsampler2xF64Sse2.hpp.
References _filter, pos, and hiir::StageProcF64Sse2< CUR >::process_sample_pos().
Referenced by process_block().
process_sample()
template<int NC> void hiir::Upsampler2xF64Sse2< NC >::process_sample (double & out_0, double & out_1, double input) noexcept
Definition at line 117 of file Upsampler2xF64Sse2.hpp.
References _filter, and hiir::StageProcF64Sse2< CUR >::process_sample_pos().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::Upsampler2xF64Sse2< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 88 of file Upsampler2xF64Sse2.hpp.
References _filter, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Upsampler2xF64Sse2< NC >::_delay = 0 static constexpr
Definition at line 53 of file Upsampler2xF64Sse2.h.
_filter
template<int NC> Filter hiir::Upsampler2xF64Sse2< NC >::_filter private
Definition at line 94 of file Upsampler2xF64Sse2.h.
Referenced by Upsampler2xF64Sse2(), clear_buffers(), process_block_double(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Upsampler2xF64Sse2< NC >::_nbr_chn = 1 static constexpr
Definition at line 51 of file Upsampler2xF64Sse2.h.
_nbr_stages
template<int NC> int hiir::Upsampler2xF64Sse2< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 85 of file Upsampler2xF64Sse2.h.
Referenced by Upsampler2xF64Sse2(), and clear_buffers().
_stage_width
template<int NC> int hiir::Upsampler2xF64Sse2< NC >::_stage_width = 2 static constexpr private
Definition at line 84 of file Upsampler2xF64Sse2.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::Upsampler2xF64Sse2< NC >::NBR_COEFS = NC static constexpr
Definition at line 52 of file Upsampler2xF64Sse2.h.
Referenced by Upsampler2xF64Sse2(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2xF64Sse2.h
src/3rdparty/hiir/hiir/Upsampler2xF64Sse2.hpp