LMMS: Jack::JackLoadableInternalClient1 Class Reference
Jack::JackLoadableInternalClient1 Class Reference
#include <JackInternalClient.h>
Public Member Functions
JackLoadableInternalClient1 (JackServer *server, JackSynchro *table, const char *object_data)
virtual ~JackLoadableInternalClient1 ()
int Init (const char *so_name)
int Open (const char *server_name, const char *name, jack_uuid_t uuid, jack_options_t options, jack_status_t *status)
Public Member Functions inherited from Jack::JackLoadableInternalClient
JackLoadableInternalClient (JackServer *server, JackSynchro *table)
virtual ~JackLoadableInternalClient ()
Public Member Functions inherited from Jack::JackInternalClient
JackInternalClient (JackServer *server, JackSynchro *table)
Client control.
virtual ~JackInternalClient ()
JackClientControl * GetClientControl () const
JackEngineControl * GetEngineControl () const
JackGraphManager * GetGraphManager () const
void ShutDown (jack_status_t code, const char *message)
Public Member Functions inherited from Jack::JackClient
JackClient (JackSynchro *table)
virtual ~JackClient ()
virtual int Activate ()
We need to start thread before activating in the server, otherwise the FW driver connected to the client may not be activated.
virtual int ClientHasSessionCallback (const char *client_name)
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual int ComputeTotalLatencies ()
void CycleSignal (int status)
jack_nframes_t CycleWait ()
virtual int Deactivate ()
Need to stop thread after deactivating in the server.
bool Execute ()
RT thread.
virtual char * GetClientNameByUUID (const char *uuid)
virtual jack_nframes_t GetCurrentTransportFrame ()
virtual char * GetInternalClientName (int ref)
char * GetServerName ()
virtual jack_native_thread_t GetThreadID ()
virtual char * GetUUIDForClientName (const char *client_name)
bool Init ()
Called once when the thread starts.
virtual int InternalClientHandle (const char *client_name, jack_status_t *status)
virtual int InternalClientLoad (const char *client_name, jack_options_t options, jack_status_t *status, jack_varargs_t *va)
virtual void InternalClientUnload (int ref, jack_status_t *status)
virtual void OnInfoShutdown (JackInfoShutdownCallback callback, void *arg)
virtual void OnShutdown (JackShutdownCallback callback, void *arg)
virtual int PortConnect (const char *src, const char *dst)
virtual int PortDisconnect (const char *src, const char *dst)
virtual int PortDisconnect (jack_port_id_t src)
virtual int PortIsMine (jack_port_id_t port_index)
virtual int PortRegister (const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
virtual int PortRename (jack_port_id_t port_index, const char *name)
virtual int PortUnRegister (jack_port_id_t port)
virtual int PropertyChangeNotify (jack_uuid_t subject, const char *key, jack_property_change_t change)
virtual int ReleaseTimebase ()
virtual int ReserveClientName (const char *client_name, const char *uuid)
virtual jack_session_command_t * SessionNotify (const char *target, jack_session_event_type_t type, const char *path)
virtual int SessionReply (jack_session_event_t *ev)
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetBufferSizeCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetClientRegistrationCallback (JackClientRegistrationCallback callback, void *arg)
virtual int SetFreeWheel (int onoff)
virtual int SetFreewheelCallback (JackFreewheelCallback callback, void *arg)
virtual int SetGraphOrderCallback (JackGraphOrderCallback callback, void *arg)
virtual int SetInitCallback (JackThreadInitCallback callback, void *arg)
virtual int SetLatencyCallback (JackLatencyCallback callback, void *arg)
virtual int SetPortConnectCallback (JackPortConnectCallback callback, void *arg)
virtual int SetPortRegistrationCallback (JackPortRegistrationCallback callback, void *arg)
virtual int SetPortRenameCallback (JackPortRenameCallback callback, void *arg)
virtual int SetProcessCallback (JackProcessCallback callback, void *arg)
virtual int SetProcessThread (JackThreadCallback fun, void *arg)
virtual int SetPropertyChangeCallback (JackPropertyChangeCallback callback, void *arg)
virtual int SetSampleRateCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetSessionCallback (JackSessionCallback callback, void *arg)
virtual int SetSyncCallback (JackSyncCallback sync_callback, void *arg)
virtual int SetSyncTimeout (jack_time_t timeout)
virtual int SetTimebaseCallback (int conditional, JackTimebaseCallback timebase_callback, void *arg)
virtual int SetXRunCallback (JackXRunCallback callback, void *arg)
virtual void TransportLocate (jack_nframes_t frame)
virtual jack_transport_state_t TransportQuery (jack_position_t *pos)
virtual int TransportReposition (const jack_position_t *pos)
virtual void TransportStart ()
virtual void TransportStop ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Attributes
InitializeCallback fInitialize
char fObjectData [JACK_LOAD_INIT_LIMIT]
Additional Inherited Members
Static Public Attributes inherited from Jack::JackInternalClient
static JackEngineControl * fEngineControl = NULL
Shared memory Port manager.
static JackGraphManager * fGraphManager = NULL
Protected Member Functions inherited from Jack::JackClient
int ActivateAux ()
int CallProcessCallback ()
void CallSyncCallback ()
void CallSyncCallbackAux ()
void CallTimebaseCallback ()
void CallTimebaseCallbackAux ()
virtual int ClientNotifyImp (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value)
Notification received from the server.
void CycleSignalAux (int status)
jack_nframes_t CycleWaitAux ()
void DummyCycle ()
void End ()
void Error ()
void ExecuteThread ()
int HandleLatencyCallback (int status)
void InitAux ()
bool IsActive ()
void SetupDriverSync (bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
void SetupRealTime ()
void SignalSync ()
int StartThread ()
bool WaitSync ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Protected Attributes inherited from Jack::JackLoadableInternalClient
JackDriverDescFunction fDescriptor
FinishCallback fFinish
JACK_HANDLE fHandle
Protected Attributes inherited from Jack::JackClient
JackBufferSizeCallback fBufferSize
void * fBufferSizeArg
detail::JackClientChannelInterface * fChannel
Thread to execute the Process function.
JackClientRegistrationCallback fClientRegistration
void * fClientRegistrationArg
JackFreewheelCallback fFreewheel
void * fFreewheelArg
JackGraphOrderCallback fGraphOrder
void * fGraphOrderArg
JackInfoShutdownCallback fInfoShutdown
void * fInfoShutdownArg
JackThreadInitCallback fInit
void * fInitArg
JackLatencyCallback fLatency
void * fLatencyArg
JackPortConnectCallback fPortConnect
void * fPortConnectArg
std::list< jack_port_id_t > fPortList
JackPortRegistrationCallback fPortRegistration
void * fPortRegistrationArg
JackPortRenameCallback fPortRename
void * fPortRenameArg
JackProcessCallback fProcess
void * fProcessArg
JackPropertyChangeCallback fPropertyChange
void * fPropertyChangeArg
JackSampleRateCallback fSampleRate
void * fSampleRateArg
char fServerName [JACK_SERVER_NAME_SIZE+1]
JackSessionCallback fSession
void * fSessionArg
JackSessionReply fSessionReply
JackShutdownCallback fShutdown
void * fShutdownArg
JackSyncCallback fSync
void * fSyncArg
JackSynchro * fSynchroTable
JackThread fThread
JackThreadCallback fThreadFun
void * fThreadFunArg
JackTimebaseCallback fTimebase
void * fTimebaseArg
JackXRunCallback fXrun
void * fXrunArg
Detailed Description
Definition at line 88 of file JackInternalClient.h.
Constructor & Destructor Documentation
JackLoadableInternalClient1()
Jack::JackLoadableInternalClient1::JackLoadableInternalClient1 (JackServer * server, JackSynchro * table, const char * object_data)
Definition at line 202 of file JackInternalClient.cpp.
References Jack::JackLoadableInternalClient::JackLoadableInternalClient(), fObjectData, JACK_LOAD_INIT_LIMIT, and server().
~JackLoadableInternalClient1()
virtual Jack::JackLoadableInternalClient1::~JackLoadableInternalClient1 () inline virtual
Definition at line 99 of file JackInternalClient.h.
Member Function Documentation
Init()
int Jack::JackLoadableInternalClient1::Init (const char * so_name) virtual
Reimplemented from Jack::JackLoadableInternalClient.
Definition at line 170 of file JackInternalClient.cpp.
References Jack::JackLoadableInternalClient::fHandle, fInitialize, GetJackProc, Jack::JackLoadableInternalClient::Init(), jack_error, and UnloadJackModule.
Open()
int Jack::JackLoadableInternalClient1::Open (const char * server_name, const char * name, jack_uuid_t uuid, jack_options_t options, jack_status_t * status) virtual
Reimplemented from Jack::JackInternalClient.
Definition at line 227 of file JackInternalClient.cpp.
References Jack::JackClient::Close(), Jack::JackLoadableInternalClient::fFinish, fInitialize, fObjectData, Jack::JackInternalClient::Open(), and server_name.
Member Data Documentation
fInitialize
InitializeCallback Jack::JackLoadableInternalClient1::fInitialize private
Definition at line 93 of file JackInternalClient.h.
Referenced by Init(), and Open().
fObjectData
char Jack::JackLoadableInternalClient1::fObjectData[JACK_LOAD_INIT_LIMIT] private
Definition at line 94 of file JackInternalClient.h.
Referenced by JackLoadableInternalClient1(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackInternalClient.h
src/3rdparty/jack2/common/JackInternalClient.cpp