LMMS: lmms::gui::AutomatableModelViewSlots Class Reference
lmms::gui::AutomatableModelViewSlots Class Reference
#include <AutomatableModelView.h>
Public Slots
void editSongGlobalAutomation ()
void execConnectionDialog ()
void removeConnection ()
void removeSongGlobalAutomation ()
void unlinkAllModels ()
Public Member Functions
AutomatableModelViewSlots (AutomatableModelView *amv, QObject *parent)
Protected Attributes
AutomatableModelView * m_amv
Private Slots
void copyToClipboard ()
Copy the model's value to the clipboard.
void pasteFromClipboard ()
Paste the model's value from the clipboard.
Detailed Description
Definition at line 91 of file AutomatableModelView.h.
Constructor & Destructor Documentation
AutomatableModelViewSlots()
lmms::gui::AutomatableModelViewSlots::AutomatableModelViewSlots (AutomatableModelView * amv, QObject * parent)
Definition at line 202 of file AutomatableModelView.cpp.
References m_amv.
Member Function Documentation
copyToClipboard
void lmms::gui::AutomatableModelViewSlots::copyToClipboard () private slot
Copy the model's value to the clipboard.
Definition at line 284 of file AutomatableModelView.cpp.
References m_amv.
editSongGlobalAutomation
void lmms::gui::AutomatableModelViewSlots::editSongGlobalAutomation () slot
Definition at line 264 of file AutomatableModelView.cpp.
References lmms::gui::GuiApplication::automationEditor(), lmms::gui::getGUI(), lmms::AutomationClip::globalAutomationClip(), m_amv, and lmms::gui::AutomationEditorWindow::open().
execConnectionDialog
void lmms::gui::AutomatableModelViewSlots::execConnectionDialog () slot
Definition at line 212 of file AutomatableModelView.cpp.
References lmms::gui::ControllerConnectionDialog::chosenController(), lmms::AutomatableModel::controllerConnection(), lmms::Model::displayName(), lmms::gui::getGUI(), m_amv, removeConnection(), lmms::ControllerConnection::setController(), and lmms::AutomatableModel::setControllerConnection().
pasteFromClipboard
void lmms::gui::AutomatableModelViewSlots::pasteFromClipboard () private slot
Paste the model's value from the clipboard.
Definition at line 292 of file AutomatableModelView.cpp.
References lmms::gui::floatFromClipboard(), and m_amv.
removeConnection
void lmms::gui::AutomatableModelViewSlots::removeConnection () slot
Definition at line 250 of file AutomatableModelView.cpp.
References lmms::AutomatableModel::controllerConnection(), m_amv, and lmms::AutomatableModel::setControllerConnection().
Referenced by execConnectionDialog().
removeSongGlobalAutomation
void lmms::gui::AutomatableModelViewSlots::removeSongGlobalAutomation () slot
Definition at line 273 of file AutomatableModelView.cpp.
References lmms::AutomationClip::globalAutomationClip(), and m_amv.
unlinkAllModels
void lmms::gui::AutomatableModelViewSlots::unlinkAllModels () slot
Definition at line 279 of file AutomatableModelView.cpp.
References m_amv.
Member Data Documentation
m_amv
AutomatableModelView* lmms::gui::AutomatableModelViewSlots::m_amv protected
Definition at line 111 of file AutomatableModelView.h.
Referenced by AutomatableModelViewSlots(), copyToClipboard(), editSongGlobalAutomation(), execConnectionDialog(), pasteFromClipboard(), removeConnection(), removeSongGlobalAutomation(), and unlinkAllModels().
The documentation for this class was generated from the following files:
include/AutomatableModelView.h
src/gui/AutomatableModelView.cpp