LMMS: lmms::AudioEngineProfiler::Probe Class Reference
lmms::AudioEngineProfiler::Probe Class Reference
#include <AudioEngineProfiler.h>
Public Member Functions
Probe (AudioEngineProfiler &profiler, AudioEngineProfiler::DetailType type)
Probe (const Probe &)=delete
Probe (Probe &&)=delete
~Probe ()
Probe & operator= (const Probe &)=delete
Private Attributes
AudioEngineProfiler & m_profiler
const AudioEngineProfiler::DetailType m_type
Detailed Description
Definition at line 73 of file AudioEngineProfiler.h.
Constructor & Destructor Documentation
Probe() [1/3]
lmms::AudioEngineProfiler::Probe::Probe (AudioEngineProfiler & profiler, AudioEngineProfiler::DetailType type) inline
Definition at line 76 of file AudioEngineProfiler.h.
References lmms::AudioEngineProfiler::AudioEngineProfiler(), m_profiler, m_type, and profiler.
Referenced by Probe(), Probe(), and operator=().
~Probe()
lmms::AudioEngineProfiler::Probe::~Probe () inline
Definition at line 82 of file AudioEngineProfiler.h.
References m_profiler, and m_type.
Probe() [2/3]
lmms::AudioEngineProfiler::Probe::Probe (const Probe &) delete
References Probe().
Probe() [3/3]
lmms::AudioEngineProfiler::Probe::Probe (Probe &&) delete
References Probe().
Member Function Documentation
operator=()
Probe & lmms::AudioEngineProfiler::Probe::operator= (const Probe &) delete
References Probe().
Member Data Documentation
m_profiler
AudioEngineProfiler& lmms::AudioEngineProfiler::Probe::m_profiler private
Definition at line 88 of file AudioEngineProfiler.h.
Referenced by Probe(), and ~Probe().
m_type
const AudioEngineProfiler::DetailType lmms::AudioEngineProfiler::Probe::m_type private
Definition at line 89 of file AudioEngineProfiler.h.
Referenced by Probe(), and ~Probe().
The documentation for this class was generated from the following file:
include/AudioEngineProfiler.h