LMMS: lmms::gui::AutomatableSlider Class Reference
lmms::gui::AutomatableSlider Class Reference
#include <AutomatableSlider.h>
Signals
void logicSliderMoved (int _value)
void logicValueChanged (int _value)
Public Member Functions
AutomatableSlider (QWidget *_parent, const QString &_name=QString())
~AutomatableSlider () override=default
bool showStatus ()
Public Member Functions inherited from lmms::gui::TypedModelView< IntModel >
TypedModelView (Model *model, QWidget *_this)
IntModel * model ()
const IntModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *_me) override
void modelChanged () override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
void wheelEvent (QWheelEvent *_me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Slots
void changeValue (int _value)
void moveSlider (int _value)
void updateSlider ()
Private Attributes
bool m_showStatus
Additional Inherited Members
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 36 of file AutomatableSlider.h.
Constructor & Destructor Documentation
AutomatableSlider()
lmms::gui::AutomatableSlider::AutomatableSlider (QWidget * _parent, const QString & _name = QString())
Definition at line 37 of file AutomatableSlider.cpp.
References changeValue(), m_showStatus, and moveSlider().
~AutomatableSlider()
lmms::gui::AutomatableSlider::~AutomatableSlider () override default
Member Function Documentation
changeValue
void lmms::gui::AutomatableSlider::changeValue (int _value) private slot
Definition at line 115 of file AutomatableSlider.cpp.
References logicValueChanged(), lmms::gui::TypedModelView< IntModel >::model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Referenced by AutomatableSlider().
contextMenuEvent()
void lmms::gui::AutomatableSlider::contextMenuEvent (QContextMenuEvent * _me) override protected
Definition at line 57 of file AutomatableSlider.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), and lmms::gui::TypedModelView< IntModel >::model().
logicSliderMoved
void lmms::gui::AutomatableSlider::logicSliderMoved (int _value) signal
Referenced by moveSlider().
logicValueChanged
void lmms::gui::AutomatableSlider::logicValueChanged (int _value) signal
Referenced by changeValue().
modelChanged()
void lmms::gui::AutomatableSlider::modelChanged () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 104 of file AutomatableSlider.cpp.
References lmms::gui::TypedModelView< IntModel >::model(), and updateSlider().
mousePressEvent()
void lmms::gui::AutomatableSlider::mousePressEvent (QMouseEvent * _me) override protected virtual
Reimplemented from lmms::gui::AutomatableModelView.
Definition at line 67 of file AutomatableSlider.cpp.
References m_showStatus, and lmms::gui::AutomatableModelView::mousePressEvent().
mouseReleaseEvent()
void lmms::gui::AutomatableSlider::mouseReleaseEvent (QMouseEvent * _me) override protected
Definition at line 84 of file AutomatableSlider.cpp.
References m_showStatus.
moveSlider
void lmms::gui::AutomatableSlider::moveSlider (int _value) private slot
Definition at line 124 of file AutomatableSlider.cpp.
References logicSliderMoved(), lmms::gui::TypedModelView< IntModel >::model(), lmms::AutomatableModel::setValue(), and lmms::gui::AutomatableModelView::value().
Referenced by AutomatableSlider().
showStatus()
bool lmms::gui::AutomatableSlider::showStatus () inline
Definition at line 43 of file AutomatableSlider.h.
References m_showStatus.
updateSlider
void lmms::gui::AutomatableSlider::updateSlider () private slot
Definition at line 133 of file AutomatableSlider.cpp.
References lmms::gui::TypedModelView< IntModel >::model(), and lmms::gui::AutomatableModelView::value().
Referenced by modelChanged().
wheelEvent()
void lmms::gui::AutomatableSlider::wheelEvent (QWheelEvent * _me) override protected
Definition at line 93 of file AutomatableSlider.cpp.
References m_showStatus.
Member Data Documentation
m_showStatus
bool lmms::gui::AutomatableSlider::m_showStatus private
Definition at line 64 of file AutomatableSlider.h.
Referenced by AutomatableSlider(), mousePressEvent(), mouseReleaseEvent(), showStatus(), and wheelEvent().
The documentation for this class was generated from the following files:
include/AutomatableSlider.h
src/gui/widgets/AutomatableSlider.cpp