LMMS: lmms::Ladspa2LMMS Class Reference
lmms::Ladspa2LMMS Class Reference
Class responsible for sorting found plugins (by LadspaManager) into categories.
#include <Ladspa2LMMS.h>
Public Member Functions
l_sortable_plugin_t getAnalysisTools ()
l_sortable_plugin_t getInstruments ()
l_sortable_plugin_t getInvalidEffects ()
l_sortable_plugin_t getOthers ()
QString getShortName (const ladspa_key_t &_key)
l_sortable_plugin_t getValidEffects ()
Public Member Functions inherited from lmms::LadspaManager
LadspaManager ()
virtual ~LadspaManager ()
bool activate (const ladspa_key_t &_plugin, LADSPA_Handle _instance)
bool areHintsSampleRateDependent (const ladspa_key_t &_plugin, uint32_t _port)
bool cleanup (const ladspa_key_t &_plugin, LADSPA_Handle _instance)
bool connectPort (const ladspa_key_t &_plugin, LADSPA_Handle _instance, uint32_t _port, LADSPA_Data *_data_location)
bool deactivate (const ladspa_key_t &_plugin, LADSPA_Handle _instance)
QString getCopyright (const ladspa_key_t &_plugin)
float getDefaultSetting (const ladspa_key_t &_plugin, uint32_t _port)
LadspaManagerDescription * getDescription (const ladspa_key_t &_plugin)
const LADSPA_Descriptor * getDescriptor (const ladspa_key_t &_plugin)
const void * getImplementationData (const ladspa_key_t &_plugin)
QString getLabel (const ladspa_key_t &_plugin)
float getLowerBound (const ladspa_key_t &_plugin, uint32_t _port)
QString getMaker (const ladspa_key_t &_plugin)
QString getName (const ladspa_key_t &_plugin)
uint32_t getPortCount (const ladspa_key_t &_plugin)
QString getPortName (const ladspa_key_t &_plugin, uint32_t _port)
l_sortable_plugin_t getSortedPlugins ()
float getUpperBound (const ladspa_key_t &_plugin, uint32_t _port)
bool hasRealTimeDependency (const ladspa_key_t &_plugin)
LADSPA_Handle instantiate (const ladspa_key_t &_plugin, uint32_t _sample_rate)
bool isEnum (const ladspa_key_t &_plugin, uint32_t _port)
bool isInplaceBroken (const ladspa_key_t &_plugin)
bool isInteger (const ladspa_key_t &_plugin, uint32_t _port)
bool isLogarithmic (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortAudio (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortControl (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortInput (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortOutput (const ladspa_key_t &_plugin, uint32_t _port)
bool isPortToggled (const ladspa_key_t &_plugin, uint32_t _port)
bool isRealTimeCapable (const ladspa_key_t &_plugin)
bool run (const ladspa_key_t &_plugin, LADSPA_Handle _instance, uint32_t _sample_count)
bool runAdding (const ladspa_key_t &_plugin, LADSPA_Handle _instance, uint32_t _sample_count)
bool setRunAddingGain (const ladspa_key_t &_plugin, LADSPA_Handle _instance, LADSPA_Data _gain)
Private Member Functions
Ladspa2LMMS ()
~Ladspa2LMMS () override=default
Private Attributes
l_sortable_plugin_t m_analysisTools
l_sortable_plugin_t m_instruments
l_sortable_plugin_t m_invalidEffects
l_sortable_plugin_t m_otherPlugins
l_sortable_plugin_t m_validEffects
Friends
class Engine
Detailed Description
Class responsible for sorting found plugins (by LadspaManager) into categories.
Definition at line 36 of file Ladspa2LMMS.h.
Constructor & Destructor Documentation
Ladspa2LMMS()
lmms::Ladspa2LMMS::Ladspa2LMMS () private
Definition at line 34 of file Ladspa2LMMS.cpp.
References lmms::LadspaManager::getDescription(), lmms::LadspaManager::getName(), lmms::LadspaManager::getSortedPlugins(), lmms::LadspaManagerDescription::inputChannels, lmms::LadspaManager::isRealTimeCapable(), m_analysisTools, m_instruments, m_invalidEffects, m_otherPlugins, m_validEffects, lmms::Other, lmms::LadspaManagerDescription::outputChannels, lmms::Sink, lmms::Source, lmms::Transfer, and lmms::LadspaManagerDescription::type.
~Ladspa2LMMS()
lmms::Ladspa2LMMS::~Ladspa2LMMS () override private default
Member Function Documentation
getAnalysisTools()
l_sortable_plugin_t lmms::Ladspa2LMMS::getAnalysisTools () inline
Definition at line 55 of file Ladspa2LMMS.h.
References m_analysisTools.
getInstruments()
l_sortable_plugin_t lmms::Ladspa2LMMS::getInstruments () inline
Definition at line 40 of file Ladspa2LMMS.h.
References m_instruments.
getInvalidEffects()
l_sortable_plugin_t lmms::Ladspa2LMMS::getInvalidEffects () inline
Definition at line 50 of file Ladspa2LMMS.h.
References m_invalidEffects.
getOthers()
l_sortable_plugin_t lmms::Ladspa2LMMS::getOthers () inline
Definition at line 60 of file Ladspa2LMMS.h.
References m_otherPlugins.
getShortName()
QString lmms::Ladspa2LMMS::getShortName (const ladspa_key_t & _key)
Definition at line 84 of file Ladspa2LMMS.cpp.
References lmms::LadspaManager::getName(), and i.
getValidEffects()
l_sortable_plugin_t lmms::Ladspa2LMMS::getValidEffects () inline
Definition at line 45 of file Ladspa2LMMS.h.
References m_validEffects.
Friends And Related Symbol Documentation
Engine
friend class Engine friend
Definition at line 77 of file Ladspa2LMMS.h.
References Engine.
Referenced by Engine.
Member Data Documentation
m_analysisTools
l_sortable_plugin_t lmms::Ladspa2LMMS::m_analysisTools private
Definition at line 74 of file Ladspa2LMMS.h.
Referenced by Ladspa2LMMS(), and getAnalysisTools().
m_instruments
l_sortable_plugin_t lmms::Ladspa2LMMS::m_instruments private
Definition at line 71 of file Ladspa2LMMS.h.
Referenced by Ladspa2LMMS(), and getInstruments().
m_invalidEffects
l_sortable_plugin_t lmms::Ladspa2LMMS::m_invalidEffects private
Definition at line 73 of file Ladspa2LMMS.h.
Referenced by Ladspa2LMMS(), and getInvalidEffects().
m_otherPlugins
l_sortable_plugin_t lmms::Ladspa2LMMS::m_otherPlugins private
Definition at line 75 of file Ladspa2LMMS.h.
Referenced by Ladspa2LMMS(), and getOthers().
m_validEffects
l_sortable_plugin_t lmms::Ladspa2LMMS::m_validEffects private
Definition at line 72 of file Ladspa2LMMS.h.
Referenced by Ladspa2LMMS(), and getValidEffects().
The documentation for this class was generated from the following files:
include/Ladspa2LMMS.h
src/core/Ladspa2LMMS.cpp