LMMS: ringbuffer_reader_t< T >::read_sequence_t Class Reference
ringbuffer_reader_t< T >::read_sequence_t Class Reference
#include <ringbuffer.h>
Public Member Functions
read_sequence_t (read_sequence_t &&)=default
~read_sequence_t ()
increases the read_ptr after reading
Public Member Functions inherited from ringbuffer_reader_t< T >::seq_base< ringbuffer_reader_t< T > * >
seq_base (ringbuffer_reader_t< T > *rb, std::size_t arg_range)
requests a read sequence of size range range can be assumed to be in bounds of read space, since sequences are only created by the safe routines below
bool copy (char *buffer, size_t bsize)
copy the current sequence into a buffer
const T * first_half_ptr () const
std::size_t first_half_size () const
const T & operator[] (std::size_t idx) const
single member access
const T * second_half_ptr () const
std::size_t second_half_size () const
std::size_t size () const
Additional Inherited Members
Protected Attributes inherited from ringbuffer_reader_t< T >::seq_base< ringbuffer_reader_t< T > * >
ringbuffer_reader_t< T > * reader_ref
Detailed Description
template<class T>
class ringbuffer_reader_t< T >::read_sequence_t
Definition at line 353 of file ringbuffer.h.
Constructor & Destructor Documentation
~read_sequence_t()
template<class T> ringbuffer_reader_t< T >::read_sequence_t::~read_sequence_t () inline
increases the read_ptr after reading
Definition at line 359 of file ringbuffer.h.
References ringbuffer_reader_t< T >::ringbuffer_reader_t(), ringbuffer_reader_t< T >::seq_base< ringbuffer_reader_t< T > * >::seq_base(), ringbuffer_reader_t< T >::seq_base< ringbuffer_reader_t< T > * >::reader_ref, ringbuffer_reader_t< T >::seq_base< ringbuffer_reader_t< T > * >::size(), and ringbuffer_reader_t< T >::try_inc().
read_sequence_t()
template<class T> ringbuffer_reader_t< T >::read_sequence_t::read_sequence_t (read_sequence_t &&) default
References read_sequence_t().
Referenced by read_sequence_t().
The documentation for this class was generated from the following file:
src/3rdparty/ringbuffer/include/ringbuffer/ringbuffer.h