LMMS: lmms::OscillatorConstants Namespace Reference
lmms::OscillatorConstants Namespace Reference
Typedefs
using waveform_t = std::array<wavetable_t, WAVE_TABLES_PER_WAVEFORM_COUNT>
using wavetable_t = std::array<sample_t, WAVETABLE_LENGTH>
Variables
const int MAX_FREQ = 20000
const int SEMITONES_PER_TABLE = 1
const int WAVE_TABLES_PER_WAVEFORM_COUNT = 128 / SEMITONES_PER_TABLE
constexpr int WAVETABLE_LENGTH = static_cast<int>(MAX_FREQ / 8.176)
Typedef Documentation
waveform_t
using lmms::OscillatorConstants::waveform_t = std::array<wavetable_t, WAVE_TABLES_PER_WAVEFORM_COUNT>
Definition at line 54 of file OscillatorConstants.h.
wavetable_t
using lmms::OscillatorConstants::wavetable_t = std::array<sample_t, WAVETABLE_LENGTH>
Definition at line 53 of file OscillatorConstants.h.
Variable Documentation
MAX_FREQ
const int lmms::OscillatorConstants::MAX_FREQ = 20000
Definition at line 37 of file OscillatorConstants.h.
Referenced by lmms::Oscillator::generateAntiAliasUserWaveTable(), lmms::Oscillator::generateWaveTables(), and lmms::Oscillator::getSample< Oscillator::WaveShape::Sine >().
SEMITONES_PER_TABLE
const int lmms::OscillatorConstants::SEMITONES_PER_TABLE = 1
Definition at line 45 of file OscillatorConstants.h.
Referenced by lmms::Oscillator::freqFromWaveTableBand(), and lmms::Oscillator::waveTableBandFromFreq().
WAVE_TABLES_PER_WAVEFORM_COUNT
const int lmms::OscillatorConstants::WAVE_TABLES_PER_WAVEFORM_COUNT = 128 / SEMITONES_PER_TABLE
Definition at line 46 of file OscillatorConstants.h.
Referenced by lmms::Oscillator::generateAntiAliasUserWaveTable(), lmms::Oscillator::generateWaveTables(), lmms::Oscillator::waveTableBandFromFreq(), and lmms::Oscillator::wtSample().
WAVETABLE_LENGTH
int lmms::OscillatorConstants::WAVETABLE_LENGTH = static_cast<int>(MAX_FREQ / 8.176) constexpr
Definition at line 39 of file OscillatorConstants.h.
Referenced by lmms::Oscillator::createFFTPlans(), lmms::Oscillator::generateAntiAliasUserWaveTable(), lmms::Oscillator::generateFromFFT(), lmms::Oscillator::generateSawWaveTable(), lmms::Oscillator::generateSquareWaveTable(), lmms::Oscillator::generateTriangleWaveTable(), lmms::Oscillator::generateWaveTables(), lmms::Oscillator::getWtSampleControl(), and lmms::Oscillator::wtSample().