LMMS: lmms::gui::AutomationClipView Class Reference
lmms::gui::AutomationClipView Class Reference
#include <AutomationClipView.h>
Public Slots
void openInAutomationEditor ()
Opens this view's clip in the global automation editor.
void update () override
Public Slots inherited from lmms::gui::ClipView
virtual bool close ()
Close a ClipView.
void randomizeColor ()
void remove ()
Removes a ClipView from its track view.
void resetColor ()
void selectColor ()
void update () override
Update a ClipView.
Public Slots inherited from lmms::gui::selectableObject
virtual void update ()
Public Member Functions
AutomationClipView (AutomationClip *_clip, TrackView *_parent)
~AutomationClipView () override=default
Public Member Functions inherited from lmms::gui::ClipView
ClipView (Clip *clip, TrackView *tv)
Create a new ClipView.
~ClipView () override
Destroy a ClipView.
void copy (QVector< ClipView * > clipvs)
void cut (QVector< ClipView * > clipvs)
bool fixedClips ()
Does this ClipView have a fixed Clip?
QVector< ClipView * > getClickedClips ()
Clip * getClip ()
QColor getColorForDisplay (QColor)
TrackView * getTrackView ()
bool gradient () const
QColor markerColor () const
QColor mutedBackgroundColor () const
QColor mutedColor () const
CSS theming qproperty access method.
bool needsUpdate ()
void paste ()
QColor patternClipBackground () const
QColor selectedColor () const
void setGradient (const bool &b)
void setMarkerColor (const QColor &c)
void setMarkerEnabled (bool e)
void setMarkerPos (int x)
void setMutedBackgroundColor (const QColor &c)
void setMutedColor (const QColor &c)
CSS theming qproperty access method.
void setNeedsUpdate (bool b)
void setPatternClipBackground (const QColor &c)
void setSelectedColor (const QColor &c)
void setTextBackgroundColor (const QColor &c)
void setTextColor (const QColor &c)
void setTextShadowColor (const QColor &c)
QColor textBackgroundColor () const
QColor textColor () const
QColor textShadowColor () const
void toggleSelectedAutoResize ()
Public Member Functions inherited from lmms::gui::selectableObject
selectableObject (QWidget *_parent)
~selectableObject () override=default
bool isSelected () const
void setSelected (bool selected)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Slots
void changeName ()
void disconnectObject (QAction *_a)
void flipX ()
void flipY ()
void resetName ()
void toggleRecording ()
Protected Slots inherited from lmms::gui::ClipView
void updateLength ()
Updates a ClipView's length.
void updatePosition ()
Updates a ClipView's position.
Protected Member Functions
void constructContextMenu (QMenu *) override
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void paintEvent (QPaintEvent *pe) override
Protected Member Functions inherited from lmms::gui::ClipView
void contextMenuAction (ContextMenuAction action)
void contextMenuEvent (QContextMenuEvent *cme) override
Set up the context menu for this ClipView.
DataFile createClipDataFiles (const QVector< ClipView * > &clips) const
Create a DataFile suitable for copying multiple clips.
void dragEnterEvent (QDragEnterEvent *dee) override
Change the ClipView's display when something being dragged enters it.
void dropEvent (QDropEvent *de) override
Handle something being dropped on this ClipObjectView.
auto hasCustomColor () const -> bool
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse movement (drag) on this ClipView.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press on this ClipView.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release on this ClipView.
virtual void paintTextLabel (QString const &text, QPainter &painter)
float pixelsPerBar ()
How many pixels a bar takes for this ClipView.
TimePos quantizeSplitPos (TimePos)
void resizeEvent (QResizeEvent *re) override
bool unquantizedModHeld (QMouseEvent *me)
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Private Member Functions
bool isResizableBeforeStart () override
Returns whether the user can left-resize this clip so that the start of the clip bounds is before the start of the clip content.
void scaleTimemapToFit (float oldMin, float oldMax)
Preserves the auto points over different scale.
Private Attributes
AutomationClip * m_clip
QPixmap m_paintPixmap
QStaticText m_staticTextName
Additional Inherited Members
Static Public Member Functions inherited from lmms::gui::ClipView
static void remove (QVector< ClipView * > clipvs)
static void toggleMute (QVector< ClipView * > clipvs)
Static Public Attributes inherited from lmms::gui::ClipView
static const int BORDER_WIDTH = 2
Protected Types inherited from lmms::gui::ClipView
enum class ContextMenuAction {
Remove ,
Cut ,
Copy ,
Paste ,
Mute
}
Protected Attributes inherited from lmms::gui::ClipView
TimePos m_initialClipEnd
TimePos m_initialClipPos
bool m_marker = false
int m_markerPos = 0
TrackView * m_trackView
Properties inherited from lmms::gui::ClipView
bool gradient
QColor markerColor
QColor mutedBackgroundColor
QColor mutedColor
QColor patternClipBackground
QColor selectedColor
QColor textBackgroundColor
QColor textColor
QColor textShadowColor
Detailed Description
Definition at line 41 of file AutomationClipView.h.
Constructor & Destructor Documentation
AutomationClipView()
lmms::gui::AutomationClipView::AutomationClipView (AutomationClip * _clip, TrackView * _parent)
Definition at line 49 of file AutomationClipView.cpp.
References lmms::gui::ClipView::ClipView(), lmms::gui::getGUI(), m_clip, m_paintPixmap, and update().
~AutomationClipView()
lmms::gui::AutomationClipView::~AutomationClipView () override default
Member Function Documentation
changeName
void lmms::gui::AutomationClipView::changeName () protected slot
Definition at line 92 of file AutomationClipView.cpp.
References m_clip, and update().
Referenced by constructContextMenu().
constructContextMenu()
void lmms::gui::AutomationClipView::constructContextMenu (QMenu * _cm) override protected virtual
Reimplemented from lmms::gui::ClipView.
Definition at line 161 of file AutomationClipView.cpp.
References changeName(), disconnectObject(), flipX(), flipY(), lmms::embed::getIconPixmap(), m_clip, openInAutomationEditor(), resetName(), and toggleRecording().
disconnectObject
void lmms::gui::AutomationClipView::disconnectObject (QAction * _a) protected slot
Definition at line 104 of file AutomationClipView.cpp.
References lmms::gui::GuiApplication::automationEditor(), lmms::gui::getGUI(), j, m_clip, lmms::gui::AutomationEditorWindow::m_editor, lmms::Engine::projectJournal(), scaleTimemapToFit(), update(), and lmms::gui::AutomationEditor::updateAfterClipChange().
Referenced by constructContextMenu().
dragEnterEvent()
void lmms::gui::AutomationClipView::dragEnterEvent (QDragEnterEvent * _dee) override protected
Definition at line 411 of file AutomationClipView.cpp.
References lmms::gui::ClipView::dragEnterEvent(), and lmms::gui::StringPairDrag::processDragEnterEvent().
dropEvent()
void lmms::gui::AutomationClipView::dropEvent (QDropEvent * _de) override protected
Definition at line 423 of file AutomationClipView.cpp.
References lmms::gui::GuiApplication::automationEditor(), lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::gui::TextFloat::displayMessage(), lmms::gui::ClipView::dropEvent(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::ProjectJournal::journallingObject(), m_clip, lmms::Engine::projectJournal(), lmms::gui::AutomationEditorWindow::setCurrentClip(), and update().
flipX
void lmms::gui::AutomationClipView::flipX () protected slot
Definition at line 152 of file AutomationClipView.cpp.
References m_clip, and update().
Referenced by constructContextMenu().
flipY
void lmms::gui::AutomationClipView::flipY () protected slot
Definition at line 143 of file AutomationClipView.cpp.
References m_clip, and update().
Referenced by constructContextMenu().
isResizableBeforeStart()
bool lmms::gui::AutomationClipView::isResizableBeforeStart () inline override private virtual
Returns whether the user can left-resize this clip so that the start of the clip bounds is before the start of the clip content.
Reimplemented from lmms::gui::ClipView.
Definition at line 79 of file AutomationClipView.h.
mouseDoubleClickEvent()
void lmms::gui::AutomationClipView::mouseDoubleClickEvent (QMouseEvent * me) override protected
Definition at line 211 of file AutomationClipView.cpp.
References lmms::gui::ClipView::m_trackView, and openInAutomationEditor().
openInAutomationEditor
void lmms::gui::AutomationClipView::openInAutomationEditor () slot
Opens this view's clip in the global automation editor.
Definition at line 68 of file AutomationClipView.cpp.
References lmms::gui::GuiApplication::automationEditor(), lmms::gui::getGUI(), m_clip, and lmms::gui::AutomationEditorWindow::open().
Referenced by constructContextMenu(), and mouseDoubleClickEvent().
paintEvent()
void lmms::gui::AutomationClipView::paintEvent (QPaintEvent * pe) override protected
Definition at line 226 of file AutomationClipView.cpp.
References lmms::gui::GuiApplication::automationEditor(), lmms::gui::ClipView::BORDER_WIDTH, lmms::gui::AutomationEditorWindow::currentClip(), lmms::AutomationClip::Discrete, lmms::gui::ClipView::fixedClips(), lmms::gui::ClipView::getColorForDisplay(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::gui::ClipView::gradient, i, lmms::INVAL(), m_clip, lmms::gui::ClipView::m_marker, lmms::gui::ClipView::m_markerPos, m_paintPixmap, lmms::gui::ClipView::markerColor, max, min, lmms::gui::ClipView::mutedColor, lmms::gui::ClipView::needsUpdate(), lmms::OUTVAL(), lmms::gui::ClipView::paintTextLabel(), lmms::gui::ClipView::pixelsPerBar(), lmms::POS(), lmms::gui::ClipView::setNeedsUpdate(), and lmms::TimePos::ticksPerBar().
resetName
void lmms::gui::AutomationClipView::resetName () protected slot
Definition at line 84 of file AutomationClipView.cpp.
References m_clip.
Referenced by constructContextMenu().
scaleTimemapToFit()
void lmms::gui::AutomationClipView::scaleTimemapToFit (float oldMin, float oldMax) private
Preserves the auto points over different scale.
Definition at line 462 of file AutomationClipView.cpp.
References lmms::INVAL(), and m_clip.
Referenced by disconnectObject().
toggleRecording
void lmms::gui::AutomationClipView::toggleRecording () protected slot
Definition at line 134 of file AutomationClipView.cpp.
References m_clip, and update().
Referenced by constructContextMenu().
update
void lmms::gui::AutomationClipView::update () override slot
Definition at line 75 of file AutomationClipView.cpp.
References m_clip, and lmms::gui::ClipView::update().
Referenced by AutomationClipView(), changeName(), disconnectObject(), dropEvent(), flipX(), flipY(), and toggleRecording().
Member Data Documentation
m_clip
AutomationClip* lmms::gui::AutomationClipView::m_clip private
Definition at line 73 of file AutomationClipView.h.
Referenced by AutomationClipView(), changeName(), constructContextMenu(), disconnectObject(), dropEvent(), flipX(), flipY(), openInAutomationEditor(), paintEvent(), resetName(), scaleTimemapToFit(), toggleRecording(), and update().
m_paintPixmap
QPixmap lmms::gui::AutomationClipView::m_paintPixmap private
Definition at line 74 of file AutomationClipView.h.
Referenced by AutomationClipView(), and paintEvent().
m_staticTextName
QStaticText lmms::gui::AutomationClipView::m_staticTextName private
Definition at line 76 of file AutomationClipView.h.
The documentation for this class was generated from the following files:
include/AutomationClipView.h
src/gui/clips/AutomationClipView.cpp