LMMS: lmms::Metronome Class Reference
lmms::Metronome Class Reference
#include <Metronome.h>
Public Member Functions
bool active () const
void processTick (int currentTick, int ticksPerBar, int beatsPerBar, size_t bufferOffset)
void setActive (bool active)
Private Attributes
bool m_active = false
Detailed Description
Definition at line 31 of file Metronome.h.
Member Function Documentation
active()
bool lmms::Metronome::active () const inline
Definition at line 34 of file Metronome.h.
References m_active.
Referenced by setActive().
processTick()
void lmms::Metronome::processTick (int currentTick, int ticksPerBar, int beatsPerBar, size_t bufferOffset)
Definition at line 31 of file Metronome.cpp.
References lmms::AudioEngine::addPlayHandle(), lmms::Engine::audioEngine(), and m_active.
setActive()
void lmms::Metronome::setActive (bool active) inline
Definition at line 35 of file Metronome.h.
References active(), and m_active.
Referenced by lmms::gui::MainWindow::onToggleMetronome().
Member Data Documentation
m_active
bool lmms::Metronome::m_active = false private
Definition at line 39 of file Metronome.h.
Referenced by active(), processTick(), and setActive().
The documentation for this class was generated from the following files:
include/Metronome.h
src/core/Metronome.cpp