LMMS: Jack::JackAndroidSemaphore Class Reference
Jack::JackAndroidSemaphore Class Reference
Inter process synchronization using POSIX semaphore.
#include <JackAndroidSemaphore.h>
Public Member Functions
JackAndroidSemaphore ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Public Member Functions inherited from Jack::detail::JackSynchro
JackSynchro ()
~JackSynchro ()
bool Allocate (const char *name, const char *server_name, int value)
bool Connect (const char *name, const char *server_name)
bool ConnectInput (const char *name, const char *server_name)
bool ConnectOutput (const char *name, const char *server_name)
void Destroy ()
bool Disconnect ()
void SetFlush (bool mode)
bool Signal ()
bool SignalAll ()
bool TimedWait (long usec)
bool Wait ()
Protected Member Functions
void BuildName (const char *name, const char *server_name, char *res, int size)
Private Attributes
sem_t * fSemaphore
android::sp< android::IMemoryHeap > fSemaphoreMemory
Static Private Attributes
static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER
Additional Inherited Members
Protected Attributes inherited from Jack::detail::JackSynchro
bool fFlush
char fName [SYNC_MAX_NAME_SIZE]
Detailed Description
Inter process synchronization using POSIX semaphore.
Definition at line 41 of file JackAndroidSemaphore.h.
Constructor & Destructor Documentation
JackAndroidSemaphore()
Jack::JackAndroidSemaphore::JackAndroidSemaphore () inline
Definition at line 56 of file JackAndroidSemaphore.h.
References Jack::detail::JackSynchro::JackSynchro(), and fSemaphore.
Member Function Documentation
Allocate()
bool Jack::JackAndroidSemaphore::Allocate (const char * name, const char * server_name, int value)
Definition at line 165 of file JackAndroidSemaphore.cpp.
References BuildName(), Jack::detail::JackSynchro::fName, fSemaphore, fSemaphoreMemory, android::Shm::getShmService(), jack_error, jack_log(), mutex, and server_name.
BuildName()
void Jack::JackAndroidSemaphore::BuildName (const char * name, const char * server_name, char * res, int size) protected
Definition at line 37 of file JackAndroidSemaphore.cpp.
References Jack::JackTools::GetUID(), Jack::JackTools::RewriteName(), server_name, and SYNC_MAX_NAME_SIZE.
Referenced by Allocate(), and ConnectInput().
Connect()
bool Jack::JackAndroidSemaphore::Connect (const char * name, const char * server_name)
Definition at line 231 of file JackAndroidSemaphore.cpp.
References ConnectInput(), and server_name.
ConnectInput()
bool Jack::JackAndroidSemaphore::ConnectInput (const char * name, const char * server_name)
Definition at line 194 of file JackAndroidSemaphore.cpp.
References BuildName(), Jack::detail::JackSynchro::fName, fSemaphore, fSemaphoreMemory, android::Shm::getShmService(), jack_error, jack_log(), mutex, and server_name.
Referenced by Connect(), and ConnectOutput().
ConnectOutput()
bool Jack::JackAndroidSemaphore::ConnectOutput (const char * name, const char * server_name)
Definition at line 236 of file JackAndroidSemaphore.cpp.
References ConnectInput(), and server_name.
Destroy()
void Jack::JackAndroidSemaphore::Destroy ()
Definition at line 251 of file JackAndroidSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, jack_error, and jack_log().
Disconnect()
bool Jack::JackAndroidSemaphore::Disconnect ()
Definition at line 241 of file JackAndroidSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, and jack_log().
Signal()
bool Jack::JackAndroidSemaphore::Signal ()
Definition at line 48 of file JackAndroidSemaphore.cpp.
References Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
Referenced by Jack::JackActivationCount::Signal().
SignalAll()
bool Jack::JackAndroidSemaphore::SignalAll ()
Definition at line 66 of file JackAndroidSemaphore.cpp.
References Jack::detail::JackSynchro::fFlush, Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
TimedWait()
bool Jack::JackAndroidSemaphore::TimedWait (long usec)
Definition at line 114 of file JackAndroidSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, jack_error, jack_log(), and ts.
Referenced by Jack::JackConnectionManager::SuspendRefNum().
Wait()
bool Jack::JackAndroidSemaphore::Wait ()
Definition at line 101 of file JackAndroidSemaphore.cpp.
References Jack::detail::JackSynchro::fName, fSemaphore, and jack_error.
Member Data Documentation
fSemaphore
sem_t* Jack::JackAndroidSemaphore::fSemaphore private
Definition at line 46 of file JackAndroidSemaphore.h.
Referenced by JackAndroidSemaphore(), Allocate(), ConnectInput(), Destroy(), Disconnect(), Signal(), SignalAll(), TimedWait(), and Wait().
fSemaphoreMemory
android::sp<android::IMemoryHeap> Jack::JackAndroidSemaphore::fSemaphoreMemory private
Definition at line 47 of file JackAndroidSemaphore.h.
Referenced by Allocate(), and ConnectInput().
mutex
pthread_mutex_t Jack::JackAndroidSemaphore::mutex = PTHREAD_MUTEX_INITIALIZER static private
Definition at line 48 of file JackAndroidSemaphore.h.
Referenced by Allocate(), and ConnectInput().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/android/JackAndroidSemaphore.h
src/3rdparty/jack2/android/JackAndroidSemaphore.cpp