LMMS: lmms::ComboBoxModel Class Reference
lmms::ComboBoxModel Class Reference
#include <ComboBoxModel.h>
Public Member Functions
ComboBoxModel (Model *parent=nullptr, const QString &displayName=QString(), bool isDefaultConstructed=false)
void addItem (QString item, std::unique_ptr< PixmapLoader > loader=nullptr)
void clear ()
const PixmapLoader * currentData () const
QString currentText () const
int findText (const QString &txt) const
const PixmapLoader * itemPixmap (int i) const
const QString & itemText (int i) const
void replaceItem (std::size_t index, QString item, std::unique_ptr< PixmapLoader > loader=nullptr)
int size () const
Public Member Functions inherited from lmms::IntModel
IntModel (int val=0, int min=0, int max=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
QString displayValue (const float val) const override
Public Member Functions inherited from lmms::TypedAutomatableModel< int >
AutomatableModel (const float val=0, const float min=0, const float max=0, const float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
int initValue () const
int maxValue () const
int minValue () const
int value (int frameOffset=0) const
Public Member Functions inherited from lmms::AutomatableModel
~AutomatableModel () override
virtual void accept (ConstModelVisitor &v) const =0
virtual void accept (ModelVisitor &v)=0
float centerValue () const
ControllerConnection * controllerConnection () const
float controllerValue (int frameOffset) const
template<class Target>
Target * dynamicCast (bool doThrow=false)
Return this class casted to Target.
template<class Target>
const Target * dynamicCast (bool doThrow=false) const
const overload, see overloaded function
float globalAutomationValueAt (const TimePos &time)
bool hasLinkedModels () const
void incValue (int steps)
template<class T>
T initValue () const
float inverseScaledValue (float value) const
Returns value applied with the inverse of this model's scale type.
bool isAtInitValue () const
bool isAutomated () const
bool isAutomatedOrControlled () const
bool isScaleLogarithmic () const
bool isValueChanged ()
virtual void loadSettings (const QDomElement &element, const QString &name)
Loads settings (value, automation links and controller connections) of AutomatableModel from specified DOM element using <name> as attribute/node name.
template<class T>
T maxValue () const
template<class T>
T minValue () const
QString nodeName () const override
float range () const
virtual void saveSettings (QDomDocument &doc, QDomElement &element, const QString &name)
Saves settings (value, automation links and controller connections) of AutomatableModel into specified DOM element using <name> as attribute/node name.
float scaledValue (float value) const
Returns value scaled with the scale type and min/max values of this model.
void setAutomatedValue (const float value)
void setCenterValue (const float centerVal)
void setControllerConnection (ControllerConnection *c)
void setInitValue (const float value)
void setRange (const float min, const float max, const float step=1)
void setScaleLogarithmic (bool setToTrue=true)
void setScaleType (ScaleType sc)
void setStep (const float step)
void setStrictStepSize (const bool b)
void setValue (const float value)
template<class T>
T step () const
void unlinkAllModels ()
bool useControllerValue ()
template<class T>
T value (int frameOffset=0) const
ValueBuffer * valueBuffer ()
Function that returns sample-exact data as a ValueBuffer.
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Private Types
using Item = std::pair<QString, std::unique_ptr<PixmapLoader>>
Private Attributes
std::vector< Item > m_items
Additional Inherited Members
Public Types inherited from lmms::AutomatableModel
using AutoModelVector = std::vector<AutomatableModel*>
enum class ScaleType {
Linear ,
Logarithmic ,
Decibel
}
Public Slots inherited from lmms::AutomatableModel
virtual void reset ()
void setUseControllerValue (bool b=true)
void unlinkControllerConnection ()
Signals inherited from lmms::AutomatableModel
void destroyed (lmms::jo_id_t id)
void initValueChanged (float val)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Public Member Functions inherited from lmms::AutomatableModel
template<bool>
static bool castValue (const float v)
template<class T>
static T castValue (const float v)
static void incrementPeriodCounter ()
static void linkModels (AutomatableModel *m1, AutomatableModel *m2)
link m1 and m2, let m1 take the values of m2
static void resetPeriodCounter ()
static void unlinkModels (AutomatableModel *m1, AutomatableModel *m2)
Protected Member Functions inherited from lmms::AutomatableModel
AutomatableModel (const float val=0, const float min=0, const float max=0, const float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
float fittedValue (float value) const
returns a value which is in range between min() and max() and aligned according to the step size (step size 0.05 -> value 0.12345 becomes 0.10 etc.).
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 38 of file ComboBoxModel.h.
Member Typedef Documentation
Item
using lmms::ComboBoxModel::Item = std::pair<QString, std::unique_ptr<PixmapLoader>> private
Definition at line 86 of file ComboBoxModel.h.
Constructor & Destructor Documentation
ComboBoxModel()
lmms::ComboBoxModel::ComboBoxModel (Model * parent = nullptr, const QString & displayName = QString(), bool isDefaultConstructed = false) inline
Definition at line 43 of file ComboBoxModel.h.
References lmms::IntModel::IntModel(), lmms::Model::displayName(), lmms::Model::isDefaultConstructed(), and lmms::JournallingObject::setJournalling().
Member Function Documentation
addItem()
void lmms::ComboBoxModel::addItem (QString item, std::unique_ptr< PixmapLoader > loader = nullptr)
Definition at line 32 of file ComboBoxModel.cpp.
References m_items, and lmms::AutomatableModel::setRange().
clear()
void lmms::ComboBoxModel::clear ()
Definition at line 47 of file ComboBoxModel.cpp.
References m_items, lmms::Model::propertiesChanged(), and lmms::AutomatableModel::setRange().
currentData()
const PixmapLoader * lmms::ComboBoxModel::currentData () const inline
Definition at line 64 of file ComboBoxModel.h.
References m_items, and lmms::TypedAutomatableModel< int >::value().
Referenced by lmms::gui::ComboBox::paintEvent().
currentText()
QString lmms::ComboBoxModel::currentText () const inline
Definition at line 59 of file ComboBoxModel.h.
References m_items, size(), and lmms::TypedAutomatableModel< int >::value().
findText()
int lmms::ComboBoxModel::findText (const QString & txt) const
Definition at line 59 of file ComboBoxModel.cpp.
References m_items.
itemPixmap()
const PixmapLoader * lmms::ComboBoxModel::itemPixmap (int i) const inline
Definition at line 74 of file ComboBoxModel.h.
References i, m_items, lmms::TypedAutomatableModel< int >::maxValue(), and lmms::TypedAutomatableModel< int >::minValue().
itemText()
const QString & lmms::ComboBoxModel::itemText (int i) const inline
Definition at line 69 of file ComboBoxModel.h.
References i, m_items, lmms::TypedAutomatableModel< int >::maxValue(), and lmms::TypedAutomatableModel< int >::minValue().
replaceItem()
void lmms::ComboBoxModel::replaceItem (std::size_t index, QString item, std::unique_ptr< PixmapLoader > loader = nullptr)
Definition at line 39 of file ComboBoxModel.cpp.
References m_items, and lmms::Model::propertiesChanged().
size()
int lmms::ComboBoxModel::size () const inline
Definition at line 79 of file ComboBoxModel.h.
References m_items.
Referenced by currentText(), and lmms::gui::ComboBox::mousePressEvent().
Member Data Documentation
m_items
std::vector<Item> lmms::ComboBoxModel::m_items private
Definition at line 88 of file ComboBoxModel.h.
Referenced by addItem(), clear(), currentData(), currentText(), findText(), itemPixmap(), itemText(), replaceItem(), and size().
The documentation for this class was generated from the following files:
include/ComboBoxModel.h
src/core/ComboBoxModel.cpp