LMMS: lmms::gui::ModelView Class Reference
lmms::gui::ModelView Class Reference
#include <ModelView.h>
Public Member Functions
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Member Functions
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Private Attributes
QPointer< Model > m_model
QWidget * m_widget
Detailed Description
Definition at line 34 of file ModelView.h.
Constructor & Destructor Documentation
ModelView()
lmms::gui::ModelView::ModelView (Model * model, QWidget * widget)
Definition at line 33 of file ModelView.cpp.
References m_model, m_widget, model(), and widget().
Referenced by lmms::gui::AutomatableModelView::AutomatableModelView(), lmms::gui::ClipView::ClipView(), lmms::gui::ControllerDialog::ControllerDialog(), lmms::gui::ControllerView::ControllerView(), lmms::gui::EffectControlDialog::EffectControlDialog(), lmms::gui::EffectRackView::EffectRackView(), lmms::gui::EnvelopeAndLfoView::EnvelopeAndLfoView(), lmms::gui::EnvelopeGraph::EnvelopeGraph(), lmms::gui::Graph::Graph(), lmms::gui::InstrumentFunctionArpeggioView::InstrumentFunctionArpeggioView(), lmms::gui::InstrumentFunctionNoteStackingView::InstrumentFunctionNoteStackingView(), lmms::gui::InstrumentMidiIOView::InstrumentMidiIOView(), lmms::gui::InstrumentSoundShapingView::InstrumentSoundShapingView(), lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow(), lmms::gui::LadspaControlView::LadspaControlView(), lmms::gui::LfoGraph::LfoGraph(), lmms::gui::MeterDialog::MeterDialog(), lmms::gui::MidiPortMenu::MidiPortMenu(), lmms::gui::MixerView::MixerView(), lmms::gui::PianoView::PianoView(), lmms::gui::PluginView::PluginView(), lmms::gui::SampleTrackWindow::SampleTrackWindow(), lmms::gui::TrackContainerView::TrackContainerView(), and lmms::gui::TrackView::TrackView().
~ModelView()
lmms::gui::ModelView::~ModelView () virtual
Definition at line 42 of file ModelView.cpp.
References m_model.
Member Function Documentation
castModel() [1/2]
template<class T> T * lmms::gui::ModelView::castModel () inline
Definition at line 54 of file ModelView.h.
References model().
Referenced by lmms::gui::Graph::Graph(), lmms::gui::MidiPortMenu::activatedPort(), lmms::gui::ControllerView::contextMenuEvent(), lmms::gui::EffectView::effect(), lmms::gui::EffectView::effect(), lmms::gui::EffectRackView::fxChain(), lmms::gui::EffectRackView::fxChain(), lmms::gui::ControllerView::getController(), lmms::gui::ControllerView::getController(), lmms::gui::ComboBox::model(), lmms::gui::ComboBox::model(), lmms::gui::Graph::model(), lmms::gui::InstrumentTrackView::model(), lmms::gui::InstrumentTrackView::model(), lmms::gui::InstrumentTrackWindow::model(), lmms::gui::InstrumentTrackWindow::model(), lmms::gui::InstrumentView::model(), lmms::gui::InstrumentView::model(), lmms::gui::SampleTrackView::model(), lmms::gui::SampleTrackView::model(), lmms::gui::SampleTrackWindow::model(), lmms::gui::SampleTrackWindow::model(), lmms::gui::TempoSyncBarModelEditor::model(), lmms::gui::TempoSyncKnob::model(), lmms::gui::TypedModelView< FloatModel >::model(), lmms::gui::TypedModelView< FloatModel >::model(), lmms::gui::EnvelopeAndLfoView::modelChanged(), lmms::gui::EnvelopeGraph::modelChanged(), lmms::gui::Graph::modelChanged(), lmms::gui::InstrumentFunctionArpeggioView::modelChanged(), lmms::gui::InstrumentFunctionNoteStackingView::modelChanged(), lmms::gui::InstrumentMidiIOView::modelChanged(), lmms::gui::InstrumentSoundShapingView::modelChanged(), lmms::gui::InstrumentTrackView::modelChanged(), lmms::gui::InstrumentTrackWindow::modelChanged(), lmms::gui::LfoControllerDialog::modelChanged(), lmms::gui::MeterDialog::modelChanged(), lmms::gui::MidiPortMenu::modelChanged(), lmms::gui::PeakControllerDialog::modelChanged(), lmms::gui::PianoView::modelChanged(), lmms::gui::SampleTrackView::modelChanged(), lmms::gui::SampleTrackWindow::modelChanged(), lmms::gui::TrackView::modelChanged(), lmms::gui::AutomatableModelView::modelUntyped(), lmms::gui::AutomatableModelView::modelUntyped(), lmms::gui::EnvelopeGraph::paintEvent(), lmms::gui::LfoGraph::paintEvent(), lmms::gui::ControllerView::renameController(), lmms::gui::EnvelopeGraph::toggleAmountModel(), lmms::gui::LfoGraph::toggleAmountModel(), and lmms::gui::MidiPortMenu::updateMenu().
castModel() [2/2]
template<class T> const T * lmms::gui::ModelView::castModel () const inline
Definition at line 60 of file ModelView.h.
References model().
doConnections()
void lmms::gui::ModelView::doConnections () protected virtual
Reimplemented in lmms::gui::FloatModelEditorBase.
Definition at line 89 of file ModelView.cpp.
References m_model, and widget().
Referenced by lmms::gui::AutomatableButton::AutomatableButton(), lmms::gui::ComboBox::ComboBox(), and setModel().
model() [1/2]
Model * lmms::gui::ModelView::model () inline
Definition at line 43 of file ModelView.h.
References m_model.
Referenced by lmms::gui::AutomatableModelView::AutomatableModelView(), lmms::gui::EffectRackView::EffectRackView(), ModelView(), lmms::gui::AutomatableModelView::addDefaultActions(), lmms::gui::LfoControllerDialog::askUserDefWave(), castModel(), castModel(), lmms::gui::EffectView::contextMenuEvent(), lmms::gui::EffectView::paintEvent(), lmms::gui::AutomatableModelView::setModel(), and setModel().
model() [2/2]
const Model * lmms::gui::ModelView::model () const inline
Definition at line 48 of file ModelView.h.
References m_model.
modelChanged()
virtual void lmms::gui::ModelView::modelChanged () inline protected virtual
Reimplemented in lmms::gui::AutomatableButton, lmms::gui::AutomatableButtonGroup, lmms::gui::AutomatableSlider, lmms::gui::ControllerView, lmms::gui::EffectRackView, lmms::gui::EffectView, lmms::gui::EnvelopeAndLfoView, lmms::gui::EnvelopeGraph, lmms::gui::Graph, lmms::gui::GroupBox, lmms::gui::InstrumentFunctionArpeggioView, lmms::gui::InstrumentFunctionNoteStackingView, lmms::gui::InstrumentMidiIOView, lmms::gui::InstrumentSoundShapingView, lmms::gui::InstrumentTrackView, lmms::gui::InstrumentTrackWindow, lmms::gui::LcdFloatSpinBox, lmms::gui::LcdSpinBox, lmms::gui::LfoControllerDialog, lmms::gui::MeterDialog, lmms::gui::MidiPortMenu, lmms::gui::PeakControllerDialog, lmms::gui::PianoView, lmms::gui::SampleTrackView, lmms::gui::SampleTrackWindow, lmms::gui::TempoSyncBarModelEditor, lmms::gui::TempoSyncKnob, and lmms::gui::TrackView.
Definition at line 68 of file ModelView.h.
Referenced by lmms::gui::AutomatableButtonGroup::modelChanged(), lmms::gui::LcdFloatSpinBox::modelChanged(), lmms::gui::LcdSpinBox::modelChanged(), lmms::gui::TrackView::modelChanged(), and setModel().
setModel()
void lmms::gui::ModelView::setModel (Model * model, bool isOldModelValid = true) virtual
Reimplemented in lmms::gui::AutomatableModelView, and lmms::gui::InstrumentView.
Definition at line 53 of file ModelView.cpp.
References doConnections(), m_model, model(), modelChanged(), and widget().
Referenced by lmms::gui::AutomationTrackView::AutomationTrackView(), lmms::gui::ClipView::ClipView(), lmms::gui::ControllerView::ControllerView(), lmms::gui::EffectRackView::EffectRackView(), lmms::gui::EffectView::EffectView(), lmms::gui::InstrumentTrackView::InstrumentTrackView(), lmms::gui::InstrumentTrackWindow::InstrumentTrackWindow(), lmms::gui::LfoControllerDialog::LfoControllerDialog(), lmms::gui::MixerView::MixerView(), lmms::gui::PatternEditor::PatternEditor(), lmms::gui::PatternTrackView::PatternTrackView(), lmms::gui::PeakControllerDialog::PeakControllerDialog(), lmms::gui::SampleTrackView::SampleTrackView(), lmms::gui::SampleTrackWindow::SampleTrackWindow(), lmms::Plugin::createView(), lmms::gui::AutomatableModelView::setModel(), lmms::gui::InstrumentView::setModel(), and unsetModel().
unsetModel()
void lmms::gui::ModelView::unsetModel () virtual
Reimplemented in lmms::gui::AutomatableModelView.
Definition at line 81 of file ModelView.cpp.
References setModel().
Referenced by lmms::gui::AutomatableModelView::unsetModel().
widget()
QWidget * lmms::gui::ModelView::widget () inline protected
Definition at line 72 of file ModelView.h.
References m_widget.
Referenced by lmms::gui::AutomatableModelView::AutomatableModelView(), ModelView(), doConnections(), lmms::gui::AutomatableButton::mousePressEvent(), lmms::gui::AutomatableModelView::mousePressEvent(), and setModel().
Member Data Documentation
m_model
QPointer<Model> lmms::gui::ModelView::m_model private
Definition at line 82 of file ModelView.h.
Referenced by ModelView(), ~ModelView(), doConnections(), model(), model(), and setModel().
m_widget
QWidget* lmms::gui::ModelView::m_widget private
Definition at line 81 of file ModelView.h.
Referenced by ModelView(), and widget().
The documentation for this class was generated from the following files:
include/ModelView.h
src/gui/ModelView.cpp