LMMS: src/3rdparty/jack2/android/JackSapaProxyOut.cpp File Reference
JackSapaProxyOut.cpp File Reference
#include "JackSapaProxy.h"
#include "JackServerGlobals.h"
#include "JackEngineControl.h"
#include "JackLockedEngine.h"
#include "JackArgParser.h"
#include <assert.h>
#include <string>
#include "driver_interface.h"
Functions
SERVER_EXPORT void jack_finish (void *arg)
SERVER_EXPORT jack_driver_desc_t * jack_get_descriptor ()
SERVER_EXPORT int jack_initialize (jack_client_t *jack_client, const char *load_init)
SERVER_EXPORT int jack_internal_initialize (jack_client_t *jack_client, const JSList *params)
Variables
static Jack::JackSapaProxy * sapaproxy = NULL
Function Documentation
jack_finish()
SERVER_EXPORT void jack_finish (void * arg)
Definition at line 90 of file JackSapaProxyOut.cpp.
References jack_log(), sapaproxy, and SERVER_EXPORT.
jack_get_descriptor()
SERVER_EXPORT jack_driver_desc_t * jack_get_descriptor ()
Definition at line 39 of file JackSapaProxyOut.cpp.
References jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverNone, JackDriverParamUInt, SERVER_EXPORT, and jack_driver_param_value_t::ui.
Referenced by jack_initialize().
jack_initialize()
SERVER_EXPORT int jack_initialize (jack_client_t * jack_client, const char * load_init)
Definition at line 72 of file JackSapaProxyOut.cpp.
References Jack::JackArgParser::FreeParams(), Jack::JackArgParser::GetArgc(), jack_get_descriptor(), jack_internal_initialize(), Jack::JackArgParser::ParseParams(), and SERVER_EXPORT.
jack_internal_initialize()
SERVER_EXPORT int jack_internal_initialize (jack_client_t * jack_client, const JSList * params)
Definition at line 54 of file JackSapaProxyOut.cpp.
References jack_info(), jack_log(), sapaproxy, and SERVER_EXPORT.
Referenced by jack_initialize().
Variable Documentation
sapaproxy
Jack::JackSapaProxy* sapaproxy = NULL static
Definition at line 37 of file JackSapaProxyOut.cpp.