LMMS: src/3rdparty/jack2/dbus/audio_reserve.h File Reference
audio_reserve.h File Reference
#include "JackCompilerDeps.h"
#include <stdbool.h>
Functions
SERVER_EXPORT bool audio_acquire (const char *device_name)
SERVER_EXPORT void audio_release (const char *device_name)
SERVER_EXPORT int audio_reservation_finish ()
SERVER_EXPORT int audio_reservation_init ()
SERVER_EXPORT void audio_reserve_loop ()
Function Documentation
audio_acquire()
SERVER_EXPORT bool audio_acquire (const char * device_name)
References SERVER_EXPORT.
Referenced by main().
audio_release()
SERVER_EXPORT void audio_release (const char * device_name)
References SERVER_EXPORT.
Referenced by main().
audio_reservation_finish()
SERVER_EXPORT int audio_reservation_finish ()
References SERVER_EXPORT.
audio_reservation_init()
SERVER_EXPORT int audio_reservation_init ()
References SERVER_EXPORT.
audio_reserve_loop()
SERVER_EXPORT void audio_reserve_loop ()
References SERVER_EXPORT.
Referenced by main().