LMMS: Jack::JackDebugClient Class Reference
Jack::JackDebugClient Class Reference
A "decorator" debug client to validate API use.
#include <JackDebugClient.h>
Public Member Functions
JackDebugClient (JackClient *fTheClient)
virtual ~JackDebugClient ()
int Activate ()
We need to start thread before activating in the server, otherwise the FW driver connected to the client may not be activated.
void CheckClient (const char *function_name) const
int ClientHasSessionCallback (const char *client_name)
int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
Notification received from the server.
int Close ()
int ComputeTotalLatencies ()
int Deactivate ()
Need to stop thread after deactivating in the server.
JackClientControl * GetClientControl () const
char * GetClientNameByUUID (const char *uuid)
jack_nframes_t GetCurrentTransportFrame ()
virtual JackEngineControl * GetEngineControl () const
virtual JackGraphManager * GetGraphManager () const
char * GetInternalClientName (int ref)
jack_native_thread_t GetThreadID ()
char * GetUUIDForClientName (const char *client_name)
int InternalClientHandle (const char *client_name, jack_status_t *status)
int InternalClientLoad (const char *client_name, jack_options_t options, jack_status_t *status, jack_varargs_t *va)
void InternalClientUnload (int ref, jack_status_t *status)
void OnInfoShutdown (JackInfoShutdownCallback callback, void *arg)
void OnShutdown (JackShutdownCallback callback, void *arg)
virtual int Open (const char *server_name, const char *name, jack_uuid_t uuid, jack_options_t options, jack_status_t *status)
int PortConnect (const char *src, const char *dst)
int PortDisconnect (const char *src, const char *dst)
int PortDisconnect (jack_port_id_t src)
int PortIsMine (jack_port_id_t port_index)
int PortRegister (const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
int PortRename (jack_port_id_t port_index, const char *name)
int PortUnRegister (jack_port_id_t port)
int ReleaseTimebase ()
int ReserveClientName (const char *client_name, const char *uuid)
jack_session_command_t * SessionNotify (const char *target, jack_session_event_type_t type, const char *path)
int SessionReply (jack_session_event_t *ev)
int SetBufferSize (jack_nframes_t buffer_size)
int SetBufferSizeCallback (JackBufferSizeCallback callback, void *arg)
int SetClientRegistrationCallback (JackClientRegistrationCallback callback, void *arg)
int SetFreeWheel (int onoff)
int SetFreewheelCallback (JackFreewheelCallback callback, void *arg)
int SetGraphOrderCallback (JackGraphOrderCallback callback, void *arg)
int SetInitCallback (JackThreadInitCallback callback, void *arg)
int SetLatencyCallback (JackLatencyCallback callback, void *arg)
int SetPortConnectCallback (JackPortConnectCallback callback, void *arg)
int SetPortRegistrationCallback (JackPortRegistrationCallback callback, void *arg)
int SetPortRenameCallback (JackPortRenameCallback callback, void *arg)
int SetProcessCallback (JackProcessCallback callback, void *arg)
int SetProcessThread (JackThreadCallback fun, void *arg)
int SetSessionCallback (JackSessionCallback callback, void *arg)
int SetSyncCallback (JackSyncCallback sync_callback, void *arg)
int SetSyncTimeout (jack_time_t timeout)
int SetTimebaseCallback (int conditional, JackTimebaseCallback timebase_callback, void *arg)
int SetXRunCallback (JackXRunCallback callback, void *arg)
void ShutDown (jack_status_t code, const char *message)
void TransportLocate (jack_nframes_t frame)
jack_transport_state_t TransportQuery (jack_position_t *pos)
int TransportReposition (const jack_position_t *pos)
void TransportStart ()
void TransportStop ()
Public Member Functions inherited from Jack::JackClient
JackClient (JackSynchro *table)
virtual ~JackClient ()
void CycleSignal (int status)
jack_nframes_t CycleWait ()
bool Execute ()
RT thread.
char * GetServerName ()
bool Init ()
Called once when the thread starts.
virtual int PropertyChangeNotify (jack_uuid_t subject, const char *key, jack_property_change_t change)
virtual int SetPropertyChangeCallback (JackPropertyChangeCallback callback, void *arg)
virtual int SetSampleRateCallback (JackBufferSizeCallback callback, void *arg)
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Static Public Member Functions
static int TimeCallback (jack_nframes_t nframes, void *arg)
Protected Attributes
JackClient * fClient
char fClientName [JACK_CLIENT_NAME_SIZE+1]
bool fFreewheel
int fIsActivated
int fIsClosed
int fIsDeactivated
int fOpenPortNumber
PortFollower fPortList [MAX_PORT_HISTORY]
JackProcessCallback fProcessTimeCallback
void * fProcessTimeCallbackArg
std::ofstream * fStream
int fTotalPortNumber
Protected Attributes inherited from Jack::JackClient
JackBufferSizeCallback fBufferSize
void * fBufferSizeArg
detail::JackClientChannelInterface * fChannel
Thread to execute the Process function.
JackClientRegistrationCallback fClientRegistration
void * fClientRegistrationArg
JackFreewheelCallback fFreewheel
void * fFreewheelArg
JackGraphOrderCallback fGraphOrder
void * fGraphOrderArg
JackInfoShutdownCallback fInfoShutdown
void * fInfoShutdownArg
JackThreadInitCallback fInit
void * fInitArg
JackLatencyCallback fLatency
void * fLatencyArg
JackPortConnectCallback fPortConnect
void * fPortConnectArg
std::list< jack_port_id_t > fPortList
JackPortRegistrationCallback fPortRegistration
void * fPortRegistrationArg
JackPortRenameCallback fPortRename
void * fPortRenameArg
JackProcessCallback fProcess
void * fProcessArg
JackPropertyChangeCallback fPropertyChange
void * fPropertyChangeArg
JackSampleRateCallback fSampleRate
void * fSampleRateArg
char fServerName [JACK_SERVER_NAME_SIZE+1]
JackSessionCallback fSession
void * fSessionArg
JackSessionReply fSessionReply
JackShutdownCallback fShutdown
void * fShutdownArg
JackSyncCallback fSync
void * fSyncArg
JackSynchro * fSynchroTable
JackThread fThread
JackThreadCallback fThreadFun
void * fThreadFunArg
JackTimebaseCallback fTimebase
void * fTimebaseArg
JackXRunCallback fXrun
void * fXrunArg
Additional Inherited Members
Protected Member Functions inherited from Jack::JackClient
int ActivateAux ()
int CallProcessCallback ()
void CallSyncCallback ()
void CallSyncCallbackAux ()
void CallTimebaseCallback ()
void CallTimebaseCallbackAux ()
virtual int ClientNotifyImp (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value)
Notification received from the server.
void CycleSignalAux (int status)
jack_nframes_t CycleWaitAux ()
void DummyCycle ()
void End ()
void Error ()
void ExecuteThread ()
int HandleLatencyCallback (int status)
void InitAux ()
bool IsActive ()
void SetupDriverSync (bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
void SetupRealTime ()
void SignalSync ()
int StartThread ()
bool WaitSync ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Detailed Description
A "decorator" debug client to validate API use.
Definition at line 49 of file JackDebugClient.h.
Constructor & Destructor Documentation
JackDebugClient()
Jack::JackDebugClient::JackDebugClient (JackClient * fTheClient)
Definition at line 37 of file JackDebugClient.cpp.
References Jack::JackClient::JackClient(), client(), fClient, fFreewheel, fIsActivated, fIsClosed, fIsDeactivated, fOpenPortNumber, Jack::JackClient::fSynchroTable, and fTotalPortNumber.
Referenced by TimeCallback().
~JackDebugClient()
Jack::JackDebugClient::~JackDebugClient () virtual
Definition at line 49 of file JackDebugClient.cpp.
References fClient, fIsActivated, fIsClosed, fIsDeactivated, fOpenPortNumber, fPortList, fStream, fTotalPortNumber, and i.
Member Function Documentation
Activate()
int Jack::JackDebugClient::Activate () virtual
We need to start thread before activating in the server, otherwise the FW driver connected to the client may not be activated.
Reimplemented from Jack::JackClient.
Definition at line 160 of file JackDebugClient.cpp.
References CheckClient(), fClient, fClientName, fIsActivated, fIsDeactivated, and fStream.
CheckClient()
void Jack::JackDebugClient::CheckClient (const char * function_name) const
Definition at line 117 of file JackDebugClient.cpp.
References fClientName, fIsClosed, and fStream.
Referenced by Activate(), ClientHasSessionCallback(), ClientNotify(), ComputeTotalLatencies(), Deactivate(), GetClientControl(), GetClientNameByUUID(), GetCurrentTransportFrame(), GetEngineControl(), GetGraphManager(), GetInternalClientName(), GetThreadID(), GetUUIDForClientName(), InternalClientHandle(), InternalClientLoad(), InternalClientUnload(), OnInfoShutdown(), OnShutdown(), PortConnect(), PortDisconnect(), PortDisconnect(), PortIsMine(), PortRegister(), PortRename(), PortUnRegister(), ReleaseTimebase(), ReserveClientName(), SessionNotify(), SessionReply(), SetBufferSize(), SetBufferSizeCallback(), SetClientRegistrationCallback(), SetFreeWheel(), SetFreewheelCallback(), SetGraphOrderCallback(), SetInitCallback(), SetLatencyCallback(), SetPortConnectCallback(), SetPortRegistrationCallback(), SetPortRenameCallback(), SetProcessCallback(), SetProcessThread(), SetSessionCallback(), SetSyncCallback(), SetSyncTimeout(), SetTimebaseCallback(), SetXRunCallback(), ShutDown(), TransportLocate(), TransportQuery(), TransportReposition(), TransportStart(), and TransportStop().
ClientHasSessionCallback()
int Jack::JackDebugClient::ClientHasSessionCallback (const char * client_name) virtual
Reimplemented from Jack::JackClient.
Definition at line 592 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
ClientNotify()
int Jack::JackDebugClient::ClientNotify (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value2) virtual
Notification received from the server.
Reimplemented from Jack::JackClient.
Definition at line 154 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
Close()
int Jack::JackDebugClient::Close () virtual
Reimplemented from Jack::JackClient.
Definition at line 109 of file JackDebugClient.cpp.
References fClient, fClientName, fIsClosed, and fStream.
ComputeTotalLatencies()
int Jack::JackDebugClient::ComputeTotalLatencies () virtual
Reimplemented from Jack::JackClient.
Definition at line 354 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
Deactivate()
int Jack::JackDebugClient::Deactivate () virtual
Need to stop thread after deactivating in the server.
Reimplemented from Jack::JackClient.
Definition at line 173 of file JackDebugClient.cpp.
References CheckClient(), fClient, fClientName, fIsActivated, fIsDeactivated, and fStream.
GetClientControl()
JackClientControl * Jack::JackDebugClient::GetClientControl () const virtual
Implements Jack::JackClientInterface.
Definition at line 599 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
GetClientNameByUUID()
char * Jack::JackDebugClient::GetClientNameByUUID (const char * uuid) virtual
Reimplemented from Jack::JackClient.
Definition at line 578 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
GetCurrentTransportFrame()
jack_nframes_t Jack::JackDebugClient::GetCurrentTransportFrame () virtual
Reimplemented from Jack::JackClient.
Definition at line 415 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
GetEngineControl()
JackEngineControl * Jack::JackDebugClient::GetEngineControl () const virtual
Implements Jack::JackClient.
Definition at line 145 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
GetGraphManager()
JackGraphManager * Jack::JackDebugClient::GetGraphManager () const virtual
Implements Jack::JackClient.
Definition at line 140 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
GetInternalClientName()
char * Jack::JackDebugClient::GetInternalClientName (int ref) virtual
Reimplemented from Jack::JackClient.
Definition at line 606 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
GetThreadID()
jack_native_thread_t Jack::JackDebugClient::GetThreadID () virtual
Reimplemented from Jack::JackClient.
Definition at line 134 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
GetUUIDForClientName()
char * Jack::JackDebugClient::GetUUIDForClientName (const char * client_name) virtual
Reimplemented from Jack::JackClient.
Definition at line 571 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
InternalClientHandle()
int Jack::JackDebugClient::InternalClientHandle (const char * client_name, jack_status_t * status) virtual
Reimplemented from Jack::JackClient.
Definition at line 612 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
InternalClientLoad()
int Jack::JackDebugClient::InternalClientLoad (const char * client_name, jack_options_t options, jack_status_t * status, jack_varargs_t * va) virtual
Reimplemented from Jack::JackClient.
Definition at line 618 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
InternalClientUnload()
void Jack::JackDebugClient::InternalClientUnload (int ref, jack_status_t * status) virtual
Reimplemented from Jack::JackClient.
Definition at line 624 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
OnInfoShutdown()
void Jack::JackDebugClient::OnInfoShutdown (JackInfoShutdownCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 449 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
OnShutdown()
void Jack::JackDebugClient::OnShutdown (JackShutdownCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 443 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
Open()
int Jack::JackDebugClient::Open (const char * server_name, const char * name, jack_uuid_t uuid, jack_options_t options, jack_status_t * status) virtual
Implements Jack::JackClient.
Definition at line 82 of file JackDebugClient.cpp.
References fClient, fClientName, fStream, jack_log(), and server_name.
PortConnect()
int Jack::JackDebugClient::PortConnect (const char * src, const char * dst) virtual
Reimplemented from Jack::JackClient.
Definition at line 234 of file JackDebugClient.cpp.
References CheckClient(), fClient, fClientName, fIsActivated, fPortList, fStream, fTotalPortNumber, and i.
PortDisconnect() [1/2]
int Jack::JackDebugClient::PortDisconnect (const char * src, const char * dst) virtual
Reimplemented from Jack::JackClient.
Definition at line 264 of file JackDebugClient.cpp.
References CheckClient(), fClient, fClientName, fIsActivated, fPortList, fStream, fTotalPortNumber, and i.
PortDisconnect() [2/2]
int Jack::JackDebugClient::PortDisconnect (jack_port_id_t src) virtual
Reimplemented from Jack::JackClient.
Definition at line 294 of file JackDebugClient.cpp.
References CheckClient(), fClient, fClientName, fIsActivated, fPortList, fStream, fTotalPortNumber, and i.
PortIsMine()
int Jack::JackDebugClient::PortIsMine (jack_port_id_t port_index) virtual
Reimplemented from Jack::JackClient.
Definition at line 318 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
PortRegister()
int Jack::JackDebugClient::PortRegister (const char * port_name, const char * port_type, unsigned long flags, unsigned long buffer_size) virtual
Reimplemented from Jack::JackClient.
Definition at line 190 of file JackDebugClient.cpp.
References CheckClient(), fClient, fClientName, fOpenPortNumber, fPortList, fStream, fTotalPortNumber, and MAX_PORT_HISTORY.
PortRename()
int Jack::JackDebugClient::PortRename (jack_port_id_t port_index, const char * name) virtual
Reimplemented from Jack::JackClient.
Definition at line 325 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
PortUnRegister()
int Jack::JackDebugClient::PortUnRegister (jack_port_id_t port) virtual
Reimplemented from Jack::JackClient.
Definition at line 212 of file JackDebugClient.cpp.
References CheckClient(), fClient, fClientName, fOpenPortNumber, fPortList, fStream, fTotalPortNumber, and i.
ReleaseTimebase()
int Jack::JackDebugClient::ReleaseTimebase () virtual
Reimplemented from Jack::JackClient.
Definition at line 377 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
ReserveClientName()
int Jack::JackDebugClient::ReserveClientName (const char * client_name, const char * uuid) virtual
Reimplemented from Jack::JackClient.
Definition at line 585 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
SessionNotify()
jack_session_command_t * Jack::JackDebugClient::SessionNotify (const char * target, jack_session_event_type_t type, const char * path) virtual
Reimplemented from Jack::JackClient.
Definition at line 558 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
SessionReply()
int Jack::JackDebugClient::SessionReply (jack_session_event_t * ev) virtual
Reimplemented from Jack::JackClient.
Definition at line 565 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetBufferSize()
int Jack::JackDebugClient::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackClient.
Definition at line 336 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
SetBufferSizeCallback()
int Jack::JackDebugClient::SetBufferSizeCallback (JackBufferSizeCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 504 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetClientRegistrationCallback()
int Jack::JackDebugClient::SetClientRegistrationCallback (JackClientRegistrationCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 510 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetFreeWheel()
int Jack::JackDebugClient::SetFreeWheel (int onoff) virtual
Reimplemented from Jack::JackClient.
Definition at line 343 of file JackDebugClient.cpp.
References CheckClient(), fClient, fFreewheel, and fStream.
SetFreewheelCallback()
int Jack::JackDebugClient::SetFreewheelCallback (JackFreewheelCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 516 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetGraphOrderCallback()
int Jack::JackDebugClient::SetGraphOrderCallback (JackGraphOrderCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 498 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetInitCallback()
int Jack::JackDebugClient::SetInitCallback (JackThreadInitCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 492 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetLatencyCallback()
int Jack::JackDebugClient::SetLatencyCallback (JackLatencyCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 546 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetPortConnectCallback()
int Jack::JackDebugClient::SetPortConnectCallback (JackPortConnectCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 528 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetPortRegistrationCallback()
int Jack::JackDebugClient::SetPortRegistrationCallback (JackPortRegistrationCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 522 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetPortRenameCallback()
int Jack::JackDebugClient::SetPortRenameCallback (JackPortRenameCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 534 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetProcessCallback()
int Jack::JackDebugClient::SetProcessCallback (JackProcessCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 470 of file JackDebugClient.cpp.
References CheckClient(), fClient, fProcessTimeCallback, fProcessTimeCallbackArg, and TimeCallback().
SetProcessThread()
int Jack::JackDebugClient::SetProcessThread (JackThreadCallback fun, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 552 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetSessionCallback()
int Jack::JackDebugClient::SetSessionCallback (JackSessionCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 540 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetSyncCallback()
int Jack::JackDebugClient::SetSyncCallback (JackSyncCallback sync_callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 383 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetSyncTimeout()
int Jack::JackDebugClient::SetSyncTimeout (jack_time_t timeout) virtual
Reimplemented from Jack::JackClient.
Definition at line 389 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
SetTimebaseCallback()
int Jack::JackDebugClient::SetTimebaseCallback (int conditional, JackTimebaseCallback timebase_callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 396 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
SetXRunCallback()
int Jack::JackDebugClient::SetXRunCallback (JackXRunCallback callback, void * arg) virtual
Reimplemented from Jack::JackClient.
Definition at line 486 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
ShutDown()
void Jack::JackDebugClient::ShutDown (jack_status_t code, const char * message) virtual
Reimplemented from Jack::JackClient.
Definition at line 367 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
TimeCallback()
int Jack::JackDebugClient::TimeCallback (jack_nframes_t nframes, void * arg) static
Definition at line 455 of file JackDebugClient.cpp.
References JackDebugClient(), client(), and GetMicroSeconds().
Referenced by SetProcessCallback().
TransportLocate()
void Jack::JackDebugClient::TransportLocate (jack_nframes_t frame) virtual
Reimplemented from Jack::JackClient.
Definition at line 402 of file JackDebugClient.cpp.
References CheckClient(), fClient, and fStream.
TransportQuery()
jack_transport_state_t Jack::JackDebugClient::TransportQuery (jack_position_t * pos) virtual
Reimplemented from Jack::JackClient.
Definition at line 409 of file JackDebugClient.cpp.
References CheckClient(), fClient, and pos.
TransportReposition()
int Jack::JackDebugClient::TransportReposition (const jack_position_t * pos) virtual
Reimplemented from Jack::JackClient.
Definition at line 421 of file JackDebugClient.cpp.
References CheckClient(), fClient, and pos.
TransportStart()
void Jack::JackDebugClient::TransportStart () virtual
Reimplemented from Jack::JackClient.
Definition at line 427 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
TransportStop()
void Jack::JackDebugClient::TransportStop () virtual
Reimplemented from Jack::JackClient.
Definition at line 433 of file JackDebugClient.cpp.
References CheckClient(), and fClient.
Member Data Documentation
fClient
JackClient* Jack::JackDebugClient::fClient protected
Definition at line 53 of file JackDebugClient.h.
Referenced by JackDebugClient(), ~JackDebugClient(), Activate(), ClientHasSessionCallback(), ClientNotify(), Close(), ComputeTotalLatencies(), Deactivate(), GetClientControl(), GetClientNameByUUID(), GetCurrentTransportFrame(), GetEngineControl(), GetGraphManager(), GetInternalClientName(), GetThreadID(), GetUUIDForClientName(), InternalClientHandle(), InternalClientLoad(), InternalClientUnload(), OnInfoShutdown(), OnShutdown(), Open(), PortConnect(), PortDisconnect(), PortDisconnect(), PortIsMine(), PortRegister(), PortRename(), PortUnRegister(), ReleaseTimebase(), ReserveClientName(), SessionNotify(), SessionReply(), SetBufferSize(), SetBufferSizeCallback(), SetClientRegistrationCallback(), SetFreeWheel(), SetFreewheelCallback(), SetGraphOrderCallback(), SetInitCallback(), SetLatencyCallback(), SetPortConnectCallback(), SetPortRegistrationCallback(), SetPortRenameCallback(), SetProcessCallback(), SetProcessThread(), SetSessionCallback(), SetSyncCallback(), SetSyncTimeout(), SetTimebaseCallback(), SetXRunCallback(), ShutDown(), TransportLocate(), TransportQuery(), TransportReposition(), TransportStart(), and TransportStop().
fClientName
char Jack::JackDebugClient::fClientName[JACK_CLIENT_NAME_SIZE+1] protected
Definition at line 62 of file JackDebugClient.h.
Referenced by Activate(), CheckClient(), Close(), Deactivate(), Open(), PortConnect(), PortDisconnect(), PortDisconnect(), PortRegister(), and PortUnRegister().
fFreewheel
bool Jack::JackDebugClient::fFreewheel protected
Definition at line 61 of file JackDebugClient.h.
Referenced by JackDebugClient(), and SetFreeWheel().
fIsActivated
int Jack::JackDebugClient::fIsActivated protected
Definition at line 58 of file JackDebugClient.h.
Referenced by JackDebugClient(), ~JackDebugClient(), Activate(), Deactivate(), PortConnect(), PortDisconnect(), and PortDisconnect().
fIsClosed
int Jack::JackDebugClient::fIsClosed protected
Definition at line 60 of file JackDebugClient.h.
Referenced by JackDebugClient(), ~JackDebugClient(), CheckClient(), and Close().
fIsDeactivated
int Jack::JackDebugClient::fIsDeactivated protected
Definition at line 59 of file JackDebugClient.h.
Referenced by JackDebugClient(), ~JackDebugClient(), Activate(), and Deactivate().
fOpenPortNumber
int Jack::JackDebugClient::fOpenPortNumber protected
Definition at line 57 of file JackDebugClient.h.
Referenced by JackDebugClient(), ~JackDebugClient(), PortRegister(), and PortUnRegister().
fPortList
PortFollower Jack::JackDebugClient::fPortList[MAX_PORT_HISTORY] protected
Definition at line 55 of file JackDebugClient.h.
Referenced by ~JackDebugClient(), PortConnect(), PortDisconnect(), PortDisconnect(), PortRegister(), and PortUnRegister().
fProcessTimeCallback
JackProcessCallback Jack::JackDebugClient::fProcessTimeCallback protected
Definition at line 63 of file JackDebugClient.h.
Referenced by SetProcessCallback().
fProcessTimeCallbackArg
void* Jack::JackDebugClient::fProcessTimeCallbackArg protected
Definition at line 64 of file JackDebugClient.h.
Referenced by SetProcessCallback().
fStream
std::ofstream* Jack::JackDebugClient::fStream protected
Definition at line 54 of file JackDebugClient.h.
Referenced by ~JackDebugClient(), Activate(), CheckClient(), ClientHasSessionCallback(), Close(), Deactivate(), GetClientNameByUUID(), GetUUIDForClientName(), Open(), PortConnect(), PortDisconnect(), PortDisconnect(), PortIsMine(), PortRegister(), PortRename(), PortUnRegister(), ReserveClientName(), SessionNotify(), SetBufferSize(), SetFreeWheel(), SetSyncTimeout(), and TransportLocate().
fTotalPortNumber
int Jack::JackDebugClient::fTotalPortNumber protected
Definition at line 56 of file JackDebugClient.h.
Referenced by JackDebugClient(), ~JackDebugClient(), PortConnect(), PortDisconnect(), PortDisconnect(), PortRegister(), and PortUnRegister().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackDebugClient.h
src/3rdparty/jack2/common/JackDebugClient.cpp