LMMS: hiir::Upsampler2xTpl< NC, DT, NCHN > Class Template Reference
hiir::Upsampler2xTpl< NC, DT, NCHN > Class Template Reference
#include <Upsampler2xTpl.h>
Public Types
typedef DT DataType
Public Member Functions
void clear_buffers () noexcept
void process_block (DataType out_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (DataType &out_0, DataType &out_1, DataType input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = NCHN
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataTpl< DataType >, NBR_COEFS+2 > Filter
Private Member Functions
bool operator!= (const Upsampler2xTpl< NC, DT, NCHN > &other)=delete
bool operator== (const Upsampler2xTpl< NC, DT, NCHN > &other)=delete
Private Attributes
Filter _filter
Detailed Description
template<int NC, typename DT, int NCHN>
class hiir::Upsampler2xTpl< NC, DT, NCHN >
Definition at line 64 of file Upsampler2xTpl.h.
Member Typedef Documentation
DataType
template<int NC, typename DT, int NCHN> typedef DT hiir::Upsampler2xTpl< NC, DT, NCHN >::DataType
Definition at line 74 of file Upsampler2xTpl.h.
Filter
template<int NC, typename DT, int NCHN> typedef std::array<StageDataTpl <DataType>, NBR_COEFS + 2> hiir::Upsampler2xTpl< NC, DT, NCHN >::Filter private
Definition at line 98 of file Upsampler2xTpl.h.
Member Function Documentation
clear_buffers()
template<int NC, typename DT, int NCHN> void hiir::Upsampler2xTpl< NC, DT, NCHN >::clear_buffers () noexcept
Definition at line 159 of file Upsampler2xTpl.hpp.
References _filter, i, and NBR_COEFS.
operator!=()
template<int NC, typename DT, int NCHN> bool hiir::Upsampler2xTpl< NC, DT, NCHN >::operator!= (const Upsampler2xTpl< NC, DT, NCHN > & other) private delete
operator==()
template<int NC, typename DT, int NCHN> bool hiir::Upsampler2xTpl< NC, DT, NCHN >::operator== (const Upsampler2xTpl< NC, DT, NCHN > & other) private delete
process_block()
template<int NC, typename DT, int NCHN> void hiir::Upsampler2xTpl< NC, DT, NCHN >::process_block (DataType out_ptr[], const DataType in_ptr[], long nbr_spl) noexcept
Definition at line 126 of file Upsampler2xTpl.hpp.
References pos, and process_sample().
process_sample()
template<int NC, typename DT, int NCHN> void hiir::Upsampler2xTpl< NC, DT, NCHN >::process_sample (DataType & out_0, DataType & out_1, DataType input) noexcept
Definition at line 94 of file Upsampler2xTpl.hpp.
References _filter, NBR_COEFS, and hiir::StageProcTpl< REMAINING, DT >::process_sample_pos().
Referenced by process_block().
set_coefs()
template<int NC, typename DT, int NCHN> void hiir::Upsampler2xTpl< NC, DT, NCHN >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 67 of file Upsampler2xTpl.hpp.
References _filter, i, and NBR_COEFS.
Member Data Documentation
_delay
template<int NC, typename DT, int NCHN> double hiir::Upsampler2xTpl< NC, DT, NCHN >::_delay = 0 static constexpr
Definition at line 77 of file Upsampler2xTpl.h.
_filter
template<int NC, typename DT, int NCHN> Filter hiir::Upsampler2xTpl< NC, DT, NCHN >::_filter private
Definition at line 100 of file Upsampler2xTpl.h.
Referenced by clear_buffers(), process_sample(), and set_coefs().
_nbr_chn
template<int NC, typename DT, int NCHN> int hiir::Upsampler2xTpl< NC, DT, NCHN >::_nbr_chn = NCHN static constexpr
Definition at line 75 of file Upsampler2xTpl.h.
NBR_COEFS
template<int NC, typename DT, int NCHN> int hiir::Upsampler2xTpl< NC, DT, NCHN >::NBR_COEFS = NC static constexpr
Definition at line 76 of file Upsampler2xTpl.h.
Referenced by clear_buffers(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2xTpl.h
src/3rdparty/hiir/hiir/Upsampler2xTpl.hpp