LMMS: Looking up ports
Looking up ports
Functions
const char ** jack_get_ports (jack_client_t *client, const char *port_name_pattern, const char *type_name_pattern, unsigned long flags) JACK_OPTIONAL_WEAK_EXPORT
jack_port_t * jack_port_by_id (jack_client_t *client, jack_port_id_t port_id) JACK_OPTIONAL_WEAK_EXPORT
jack_port_t * jack_port_by_name (jack_client_t *client, const char *port_name) JACK_OPTIONAL_WEAK_EXPORT
Detailed Description
Function Documentation
jack_get_ports()
LIB_EXPORT const char ** jack_get_ports (jack_client_t * client, const char * port_name_pattern, const char * type_name_pattern, unsigned long flags)
#include <jack.h>
Parameters
port_name_pattern A regular expression used to select ports by name. If NULL or of zero length, no selection based on name will be carried out.
type_name_pattern A regular expression used to select ports by type. If NULL or of zero length, no selection based on type will be carried out.
flags A value used to select ports by their flags. If zero, no selection based on flags will be carried out.
Returns
a NULL-terminated array of ports that match the specified arguments. The caller is responsible for calling jack_free() any non-NULL returned value.
See also
jack_port_name_size(), jack_port_type_size()
Definition at line 1293 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPorts(), jack_error, and LIB_EXPORT.
Referenced by Jack::JackProfiler::JackProfiler(), Jack::JackAudioAdapter::ConnectPorts(), Jack::JackNetMaster::ConnectPorts(), Jack::JackProxyDriver::ConnectPorts(), Jack::JackNetMasterManager::CountIO(), Jack::JackProxyDriver::CountIO(), Jack::JackProxyDriver::LoadSymbols(), main(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), and Jack::JackSapaProxy::Setup().
jack_port_by_id()
LIB_EXPORT jack_port_t * jack_port_by_id (jack_client_t * client, jack_port_id_t port_id)
#include <jack.h>
Returns
address of the jack_port_t of a port_id.
Definition at line 1330 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), and LIB_EXPORT.
Referenced by Jack::JackProxyDriver::connect_callback(), Jack::JackNetMaster::ConnectCallback(), Jack::JackProxyDriver::LoadSymbols(), and Jack::JackProxyDriver::PROXY_DEF_SYMBOL().
jack_port_by_name()
LIB_EXPORT jack_port_t * jack_port_by_name (jack_client_t * client, const char * port_name)
#include <jack.h>
Returns
address of the jack_port_t named port_name.
See also
jack_port_name_size()
Definition at line 1306 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::GetGraphManager(), Jack::JackGraphManager::GetPort(), jack_error, LIB_EXPORT, and NO_PORT.
Referenced by main().