LMMS: lmms::NoCopyNoMove Class Reference
lmms::NoCopyNoMove Class Reference
Inherit this class to make your class non-copyable and non-movable.
#include <NoCopyNoMove.h>
Protected Member Functions
NoCopyNoMove ()=default
NoCopyNoMove (const NoCopyNoMove &other)=delete
NoCopyNoMove (NoCopyNoMove &&other)=delete
NoCopyNoMove & operator= (const NoCopyNoMove &other)=delete
NoCopyNoMove & operator= (NoCopyNoMove &&other)=delete
Detailed Description
Inherit this class to make your class non-copyable and non-movable.
Definition at line 34 of file NoCopyNoMove.h.
Constructor & Destructor Documentation
NoCopyNoMove() [1/3]
lmms::NoCopyNoMove::NoCopyNoMove () protected default
Referenced by NoCopyNoMove(), NoCopyNoMove(), operator=(), and operator=().
NoCopyNoMove() [2/3]
lmms::NoCopyNoMove::NoCopyNoMove (const NoCopyNoMove & other) protected delete
References NoCopyNoMove().
NoCopyNoMove() [3/3]
lmms::NoCopyNoMove::NoCopyNoMove (NoCopyNoMove && other) protected delete
References NoCopyNoMove().
Member Function Documentation
operator=() [1/2]
NoCopyNoMove & lmms::NoCopyNoMove::operator= (const NoCopyNoMove & other) protected delete
References NoCopyNoMove().
operator=() [2/2]
NoCopyNoMove & lmms::NoCopyNoMove::operator= (NoCopyNoMove && other) protected delete
References NoCopyNoMove().
The documentation for this class was generated from the following file:
include/NoCopyNoMove.h