LMMS: lmms::MidiDummy Class Reference
lmms::MidiDummy Class Reference
#include <MidiDummy.h>
Public Member Functions
MidiDummy ()=default
~MidiDummy () override=default
Public Member Functions inherited from lmms::MidiClientRaw
MidiClientRaw ()=default
~MidiClientRaw () override=default
bool isRaw () const override
Public Member Functions inherited from lmms::MidiClient
MidiClient ()=default
virtual ~MidiClient ()
virtual void addPort (MidiPort *_port)
virtual void applyPortMode (MidiPort *_port)
virtual void applyPortName (MidiPort *_port)
virtual void connectRPChanged (QObject *, const char *)
virtual void connectWPChanged (QObject *, const char *)
virtual QStringList readablePorts () const
virtual void removePort (MidiPort *_port)
virtual QString sourcePortName (const MidiEvent &) const
virtual void subscribeReadablePort (MidiPort *_port, const QString &_dest, bool _subscribe=true)
virtual void subscribeWritablePort (MidiPort *_port, const QString &_dest, bool _subscribe=true)
virtual QStringList writablePorts () const
Static Public Member Functions
static QString configSection ()
static QString name ()
static QString probeDevice ()
Static Public Member Functions inherited from lmms::MidiClient
static MidiClient * openMidiClient ()
Protected Member Functions
void sendByte (const unsigned char) override
Protected Member Functions inherited from lmms::MidiClientRaw
void parseData (const unsigned char c)
Additional Inherited Members
Protected Attributes inherited from lmms::MidiClient
std::vector< MidiPort * > m_midiPorts
Detailed Description
Definition at line 35 of file MidiDummy.h.
Constructor & Destructor Documentation
MidiDummy()
lmms::MidiDummy::MidiDummy () default
~MidiDummy()
lmms::MidiDummy::~MidiDummy () override default
Member Function Documentation
configSection()
QString lmms::MidiDummy::configSection () inline static
Definition at line 52 of file MidiDummy.h.
name()
QString lmms::MidiDummy::name () inline static
Definition at line 41 of file MidiDummy.h.
Referenced by lmms::gui::SetupDialog::SetupDialog(), lmms::AudioEngine::initDevices(), lmms::AudioEngine::isMidiDevNameValid(), and lmms::AudioEngine::tryMidiClients().
probeDevice()
QString lmms::MidiDummy::probeDevice () inline static
Definition at line 47 of file MidiDummy.h.
sendByte()
void lmms::MidiDummy::sendByte (const unsigned char) inline override protected virtual
Implements lmms::MidiClientRaw.
Definition at line 59 of file MidiDummy.h.
The documentation for this class was generated from the following file:
include/MidiDummy.h