LMMS: lmms::gui::SampleLoader Class Reference
lmms::gui::SampleLoader Class Reference
#include <SampleLoader.h>
Static Public Member Functions
static std::shared_ptr< const SampleBuffer > createBufferFromBase64 (const QString &base64, int sampleRate=Engine::audioEngine() ->outputSampleRate())
static std::shared_ptr< const SampleBuffer > createBufferFromFile (const QString &filePath)
static QString openAudioFile (const QString &previousFile="")
static QString openWaveformFile (const QString &previousFile="")
Static Private Member Functions
static void displayError (const QString &message)
Detailed Description
Definition at line 35 of file SampleLoader.h.
Member Function Documentation
createBufferFromBase64()
std::shared_ptr< const SampleBuffer > lmms::gui::SampleLoader::createBufferFromBase64 (const QString & base64, int sampleRate = Engine::audioEngine()->outputSampleRate()) static
Definition at line 105 of file SampleLoader.cpp.
References displayError(), lmms::SampleBuffer::emptyBuffer(), and lmms::gui::getGUI().
Referenced by lmms::gui::SampleClipView::dropEvent(), and lmms::SampleClip::loadSettings().
createBufferFromFile()
std::shared_ptr< const SampleBuffer > lmms::gui::SampleLoader::createBufferFromFile (const QString & filePath) static
Definition at line 90 of file SampleLoader.cpp.
References displayError(), lmms::SampleBuffer::emptyBuffer(), and lmms::gui::getGUI().
Referenced by lmms::gui::LfoControllerDialog::askUserDefWave(), lmms::gui::EnvelopeAndLfoView::dropEvent(), lmms::EnvelopeAndLfoParameters::loadSettings(), lmms::LfoController::loadSettings(), lmms::gui::SampleClipView::mouseDoubleClickEvent(), lmms::gui::FileBrowserTreeWidget::previewFileItem(), lmms::SampleClip::setSampleFile(), and lmms::graphModel::setWaveToUser().
displayError()
void lmms::gui::SampleLoader::displayError (const QString & message) static private
Definition at line 120 of file SampleLoader.cpp.
Referenced by createBufferFromBase64(), and createBufferFromFile().
openAudioFile()
QString lmms::gui::SampleLoader::openAudioFile (const QString & previousFile = "") static
Definition at line 38 of file SampleLoader.cpp.
References lmms::ConfigManager::inst(), lmms::nameFilters(), lmms::SampleDecoder::supportedAudioTypes(), lmms::PathUtil::toAbsolute(), lmms::PathUtil::toShortestRelative(), and lmms::ConfigManager::userSamplesDir().
Referenced by lmms::gui::SampleClipView::mouseDoubleClickEvent(), and openWaveformFile().
openWaveformFile()
QString lmms::gui::SampleLoader::openWaveformFile (const QString & previousFile = "") static
Definition at line 84 of file SampleLoader.cpp.
References lmms::ConfigManager::inst(), and openAudioFile().
Referenced by lmms::gui::LfoControllerDialog::askUserDefWave(), and lmms::graphModel::setWaveToUser().
The documentation for this class was generated from the following files:
include/SampleLoader.h
src/gui/SampleLoader.cpp