LMMS: src/3rdparty/jack2/linux/alsa/alsa_driver.h File Reference
alsa_driver.h File Reference
#include <alsa/asoundlib.h>
#include "bitset.h"
#include "types.h"
#include "hardware.h"
#include "driver.h"
#include "memops.h"
#include "alsa_midi.h"
Classes
struct _alsa_driver
Macros
#define FALSE 0
#define IS_BE 1
#define IS_LE 0
#define TRUE 1
Typedefs
typedef struct _alsa_driver alsa_driver_t
typedef void(* ReadCopyFunction) (jack_default_audio_sample_t *dst, char *src, unsigned long src_bytes, unsigned long src_skip_bytes)
typedef void(* WriteCopyFunction) (char *dst, jack_default_audio_sample_t *src, unsigned long src_bytes, unsigned long dst_skip_bytes, dither_state_t *state)
Functions
void alsa_driver_clock_sync_notify (alsa_driver_t *, channel_t chn, ClockSyncStatus)
void alsa_driver_delete (alsa_driver_t *driver)
int alsa_driver_listen_for_clock_sync_status (alsa_driver_t *, ClockSyncListenerFunction, void *arg)
static void alsa_driver_mark_channel_done (alsa_driver_t *driver, channel_t chn)
jack_driver_t * alsa_driver_new (char *name, char *playback_alsa_device, char *capture_alsa_device, jack_client_t *client, jack_nframes_t frames_per_cycle, jack_nframes_t user_nperiods, jack_nframes_t rate, int hw_monitoring, int hw_metering, int capturing, int playing, DitherAlgorithm dither, int soft_mode, int monitor, int user_capture_nchnls, int user_playback_nchnls, int shorts_first, jack_nframes_t capture_latency, jack_nframes_t playback_latency, alsa_midi_t *midi_driver)
int alsa_driver_read (alsa_driver_t *driver, jack_nframes_t nframes)
static void alsa_driver_read_from_channel (alsa_driver_t *driver, channel_t channel, jack_default_audio_sample_t *buf, jack_nframes_t nsamples)
int alsa_driver_reset_parameters (alsa_driver_t *driver, jack_nframes_t frames_per_cycle, jack_nframes_t user_nperiods, jack_nframes_t rate)
void alsa_driver_set_clock_sync_status (alsa_driver_t *driver, channel_t chn, ClockSyncStatus status)
static void alsa_driver_silence_on_channel (alsa_driver_t *driver, channel_t chn, jack_nframes_t nframes)
static void alsa_driver_silence_on_channel_no_mark (alsa_driver_t *driver, channel_t chn, jack_nframes_t nframes)
void alsa_driver_silence_untouched_channels (alsa_driver_t *driver, jack_nframes_t nframes)
int alsa_driver_start (alsa_driver_t *driver)
int alsa_driver_stop (alsa_driver_t *driver)
int alsa_driver_stop_listen_for_clock_sync_status (alsa_driver_t *, unsigned int)
jack_nframes_t alsa_driver_wait (alsa_driver_t *driver, int extra_fd, int *status, float *delayed_usecs)
int alsa_driver_write (alsa_driver_t *driver, jack_nframes_t nframes)
static void alsa_driver_write_to_channel (alsa_driver_t *driver, channel_t channel, jack_default_audio_sample_t *buf, jack_nframes_t nsamples)
void ClearOutput ()
jack_time_t jack_get_microseconds (void)
void MonitorInput ()
void ReadInput (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nread)
int Restart ()
void SetTime (jack_time_t time)
void WriteOutput (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nwritten)
Macro Definition Documentation
FALSE
#define FALSE 0
Definition at line 36 of file alsa_driver.h.
IS_BE
#define IS_BE 1
Definition at line 29 of file alsa_driver.h.
IS_LE
#define IS_LE 0
Definition at line 28 of file alsa_driver.h.
TRUE
#define TRUE 1
Definition at line 35 of file alsa_driver.h.
Typedef Documentation
alsa_driver_t
typedef struct _alsa_driver alsa_driver_t
ReadCopyFunction
typedef void(* ReadCopyFunction) (jack_default_audio_sample_t *dst, char *src, unsigned long src_bytes, unsigned long src_skip_bytes)
Definition at line 49 of file alsa_driver.h.
WriteCopyFunction
typedef void(* WriteCopyFunction) (char *dst, jack_default_audio_sample_t *src, unsigned long src_bytes, unsigned long dst_skip_bytes, dither_state_t *state)
Definition at line 52 of file alsa_driver.h.
Function Documentation
alsa_driver_clock_sync_notify()
void alsa_driver_clock_sync_notify (alsa_driver_t * , channel_t chn, ClockSyncStatus)
alsa_driver_delete()
void alsa_driver_delete (alsa_driver_t * driver)
References driver.
Referenced by Jack::JackAlsaDriver::Close().
alsa_driver_listen_for_clock_sync_status()
int alsa_driver_listen_for_clock_sync_status (alsa_driver_t * , ClockSyncListenerFunction , void * arg)
alsa_driver_mark_channel_done()
void alsa_driver_mark_channel_done (alsa_driver_t * driver, channel_t chn) inline static
Definition at line 151 of file alsa_driver.h.
References bitset_remove(), and driver.
Referenced by alsa_driver_silence_on_channel(), and alsa_driver_write_to_channel().
alsa_driver_new()
jack_driver_t * alsa_driver_new (char * name, char * playback_alsa_device, char * capture_alsa_device, jack_client_t * client, jack_nframes_t frames_per_cycle, jack_nframes_t user_nperiods, jack_nframes_t rate, int hw_monitoring, int hw_metering, int capturing, int playing, DitherAlgorithm dither, int soft_mode, int monitor, int user_capture_nchnls, int user_playback_nchnls, int shorts_first, jack_nframes_t capture_latency, jack_nframes_t playback_latency, alsa_midi_t * midi_driver)
References capture_latency, client(), and playback_latency.
Referenced by Jack::JackAlsaDriver::Open().
alsa_driver_read()
int alsa_driver_read (alsa_driver_t * driver, jack_nframes_t nframes)
References driver.
Referenced by Jack::JackAlsaDriver::Read().
alsa_driver_read_from_channel()
void alsa_driver_read_from_channel (alsa_driver_t * driver, channel_t channel, jack_default_audio_sample_t * buf, jack_nframes_t nsamples) inline static
Definition at line 188 of file alsa_driver.h.
References driver.
Referenced by Jack::JackAlsaDriver::ReadInputAux().
alsa_driver_reset_parameters()
int alsa_driver_reset_parameters (alsa_driver_t * driver, jack_nframes_t frames_per_cycle, jack_nframes_t user_nperiods, jack_nframes_t rate)
References driver.
Referenced by Jack::JackAlsaDriver::SetBufferSize().
alsa_driver_set_clock_sync_status()
void alsa_driver_set_clock_sync_status (alsa_driver_t * driver, channel_t chn, ClockSyncStatus status)
References driver.
alsa_driver_silence_on_channel()
void alsa_driver_silence_on_channel (alsa_driver_t * driver, channel_t chn, jack_nframes_t nframes) inline static
Definition at line 157 of file alsa_driver.h.
References alsa_driver_mark_channel_done(), driver, and memset_interleave().
alsa_driver_silence_on_channel_no_mark()
void alsa_driver_silence_on_channel_no_mark (alsa_driver_t * driver, channel_t chn, jack_nframes_t nframes) inline static
Definition at line 173 of file alsa_driver.h.
References driver, and memset_interleave().
alsa_driver_silence_untouched_channels()
void alsa_driver_silence_untouched_channels (alsa_driver_t * driver, jack_nframes_t nframes)
References driver.
alsa_driver_start()
int alsa_driver_start (alsa_driver_t * driver)
References driver.
Referenced by Jack::JackAlsaDriver::Start().
alsa_driver_stop()
int alsa_driver_stop (alsa_driver_t * driver)
References driver.
Referenced by Jack::JackAlsaDriver::Stop().
alsa_driver_stop_listen_for_clock_sync_status()
int alsa_driver_stop_listen_for_clock_sync_status (alsa_driver_t * , unsigned int)
alsa_driver_wait()
jack_nframes_t alsa_driver_wait (alsa_driver_t * driver, int extra_fd, int * status, float * delayed_usecs)
References driver.
Referenced by Jack::JackAlsaDriver::Read().
alsa_driver_write()
int alsa_driver_write (alsa_driver_t * driver, jack_nframes_t nframes)
References driver.
Referenced by Jack::JackAlsaDriver::Write().
alsa_driver_write_to_channel()
void alsa_driver_write_to_channel (alsa_driver_t * driver, channel_t channel, jack_default_audio_sample_t * buf, jack_nframes_t nsamples) inline static
Definition at line 200 of file alsa_driver.h.
References alsa_driver_mark_channel_done(), and driver.
Referenced by Jack::JackAlsaDriver::WriteOutputAux().
ClearOutput()
void ClearOutput ()
Definition at line 939 of file JackAlsaDriver.cpp.
References g_alsa_driver.
jack_get_microseconds()
jack_time_t jack_get_microseconds (void)
MonitorInput()
void MonitorInput ()
Definition at line 935 of file JackAlsaDriver.cpp.
References g_alsa_driver.
ReadInput()
void ReadInput (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nread)
Definition at line 931 of file JackAlsaDriver.cpp.
References g_alsa_driver.
Restart()
int Restart ()
Definition at line 952 of file JackAlsaDriver.cpp.
References g_alsa_driver.
SetTime()
void SetTime (jack_time_t time)
Definition at line 947 of file JackAlsaDriver.cpp.
References g_alsa_driver.
WriteOutput()
void WriteOutput (jack_nframes_t orig_nframes, snd_pcm_sframes_t contiguous, snd_pcm_sframes_t nwritten)
Definition at line 943 of file JackAlsaDriver.cpp.
References g_alsa_driver.