LMMS: Jack::JackAC3Encoder Class Reference
Jack::JackAC3Encoder Class Reference
#include <JackAC3Encoder.h>
Public Member Functions
JackAC3Encoder (const JackAC3EncoderParams &params)
virtual ~JackAC3Encoder ()
void GetChannelName (const char *name, const char *alias, char *portname, int channel)
bool Init (jack_nframes_t sample_rate)
void Process (float **inputs, float **outputs, int nframes)
Private Member Functions
void FillSpdifHeader (unsigned char *buf, int outsize)
int Output2Driver (float **outputs, jack_nframes_t nframes)
void sample_move_dS_s16 (jack_default_audio_sample_t *dst, char *src, jack_nframes_t nsamples, unsigned long src_skip)
void sample_move_dS_s16_24ph (jack_default_audio_sample_t *dst, char *src, jack_nframes_t nsamples, unsigned long src_skip)
Private Attributes
unsigned char * fAC3Buffer
AftenContext fAftenContext
jack_nframes_t fByteRate
jack_nframes_t fFramePos
int fOutSizeByte
jack_ringbuffer_t * fRingBuffer
float * fSampleBuffer
jack_nframes_t fSampleRate
unsigned char * fZeroBuffer
Detailed Description
Definition at line 51 of file JackAC3Encoder.h.
Constructor & Destructor Documentation
JackAC3Encoder()
Jack::JackAC3Encoder::JackAC3Encoder (const JackAC3EncoderParams & params)
Definition at line 35 of file JackAC3Encoder.cpp.
References Jack::JackAC3EncoderParams::bitrate, Jack::JackAC3EncoderParams::channels, fAC3Buffer, fAftenContext, fByteRate, fFramePos, fOutSizeByte, fRingBuffer, fSampleBuffer, fSampleRate, fZeroBuffer, jack_ringbuffer_create(), Jack::JackAC3EncoderParams::lfe, MAX_AC3_CHANNELS, Jack::JackAC3EncoderParams::sample_rate, and SPDIF_FRAME_SIZE.
~JackAC3Encoder()
Jack::JackAC3Encoder::~JackAC3Encoder () virtual
Definition at line 93 of file JackAC3Encoder.cpp.
References fAC3Buffer, fAftenContext, fRingBuffer, fSampleBuffer, fZeroBuffer, and jack_ringbuffer_free().
Member Function Documentation
FillSpdifHeader()
void Jack::JackAC3Encoder::FillSpdifHeader (unsigned char * buf, int outsize) private
Definition at line 173 of file JackAC3Encoder.cpp.
References SPDIF_HEADER_SIZE.
Referenced by Process().
GetChannelName()
void Jack::JackAC3Encoder::GetChannelName (const char * name, const char * alias, char * portname, int channel)
Definition at line 257 of file JackAC3Encoder.cpp.
References fAftenContext.
Init()
bool Jack::JackAC3Encoder::Init (jack_nframes_t sample_rate)
Definition at line 86 of file JackAC3Encoder.cpp.
References fAftenContext, fByteRate, and fSampleRate.
Output2Driver()
int Jack::JackAC3Encoder::Output2Driver (float ** outputs, jack_nframes_t nframes) private
Definition at line 190 of file JackAC3Encoder.cpp.
References fRingBuffer, jack_ringbuffer_get_read_vector(), jack_ringbuffer_read_advance(), jack_ringbuffer_read_space(), min, sample_move_dS_s16(), and sample_move_dS_s16_24ph().
Referenced by Process().
Process()
void Jack::JackAC3Encoder::Process (float ** inputs, float ** outputs, int nframes)
Definition at line 106 of file JackAC3Encoder.cpp.
References fAC3Buffer, fAftenContext, fByteRate, fFramePos, FillSpdifHeader(), fOutSizeByte, fRingBuffer, fSampleBuffer, fSampleRate, fZeroBuffer, i, jack_error, jack_ringbuffer_write(), Output2Driver(), pos, and SPDIF_HEADER_SIZE.
sample_move_dS_s16()
void Jack::JackAC3Encoder::sample_move_dS_s16 (jack_default_audio_sample_t * dst, char * src, jack_nframes_t nsamples, unsigned long src_skip) private
Definition at line 237 of file JackAC3Encoder.cpp.
References SAMPLE_MAX_16BIT.
Referenced by Output2Driver().
sample_move_dS_s16_24ph()
void Jack::JackAC3Encoder::sample_move_dS_s16_24ph (jack_default_audio_sample_t * dst, char * src, jack_nframes_t nsamples, unsigned long src_skip) private
Definition at line 247 of file JackAC3Encoder.cpp.
References SAMPLE_MAX_24BIT.
Referenced by Output2Driver().
Member Data Documentation
fAC3Buffer
unsigned char* Jack::JackAC3Encoder::fAC3Buffer private
Definition at line 60 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), ~JackAC3Encoder(), and Process().
fAftenContext
AftenContext Jack::JackAC3Encoder::fAftenContext private
Definition at line 56 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), ~JackAC3Encoder(), GetChannelName(), Init(), and Process().
fByteRate
jack_nframes_t Jack::JackAC3Encoder::fByteRate private
Definition at line 67 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), Init(), and Process().
fFramePos
jack_nframes_t Jack::JackAC3Encoder::fFramePos private
Definition at line 65 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), and Process().
fOutSizeByte
int Jack::JackAC3Encoder::fOutSizeByte private
Definition at line 63 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), and Process().
fRingBuffer
jack_ringbuffer_t* Jack::JackAC3Encoder::fRingBuffer private
Definition at line 57 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), ~JackAC3Encoder(), Output2Driver(), and Process().
fSampleBuffer
float* Jack::JackAC3Encoder::fSampleBuffer private
Definition at line 59 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), ~JackAC3Encoder(), and Process().
fSampleRate
jack_nframes_t Jack::JackAC3Encoder::fSampleRate private
Definition at line 66 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), Init(), and Process().
fZeroBuffer
unsigned char* Jack::JackAC3Encoder::fZeroBuffer private
Definition at line 61 of file JackAC3Encoder.h.
Referenced by JackAC3Encoder(), ~JackAC3Encoder(), and Process().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackAC3Encoder.h
src/3rdparty/jack2/common/JackAC3Encoder.cpp