LMMS: hiir::StageProcSseV2< CUR > Class Template Reference
hiir::StageProcSseV2< CUR > Class Template Reference
#include <StageProcSseV2.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg_rec (__m128 &, StageDataSse *) noexcept
hiir_FORCEINLINE void process_sample_pos_rec (__m128 &, StageDataSse *) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (__m128 &x, StageDataSse *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_neg_rec (__m128 &x, StageDataSse *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (__m128 &x, StageDataSse *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos_rec (__m128 &x, StageDataSse *stage_arr) noexcept
Private Member Functions
StageProcSseV2 ()=delete
StageProcSseV2 (const StageProcSseV2 &other)=delete
StageProcSseV2 (StageProcSseV2 &&other)=delete
~StageProcSseV2 ()=delete
bool operator!= (const StageProcSseV2 &other) const =delete
StageProcSseV2 & operator= (const StageProcSseV2 &other)=delete
StageProcSseV2 & operator= (StageProcSseV2 &&other)=delete
bool operator== (const StageProcSseV2 &other) const =delete
Detailed Description
template<int CUR>
class hiir::StageProcSseV2< CUR >
Definition at line 40 of file StageProcSseV2.h.
Constructor & Destructor Documentation
StageProcSseV2() [1/3]
template<int CUR> hiir::StageProcSseV2< CUR >::StageProcSseV2 () private delete
Referenced by StageProcSseV2(), StageProcSseV2(), ~StageProcSseV2(), operator!=(), operator=(), operator=(), operator==(), process_sample_neg_rec(), and process_sample_pos_rec().
StageProcSseV2() [2/3]
template<int CUR> hiir::StageProcSseV2< CUR >::StageProcSseV2 (const StageProcSseV2< CUR > & other) private delete
References StageProcSseV2().
StageProcSseV2() [3/3]
template<int CUR> hiir::StageProcSseV2< CUR >::StageProcSseV2 (StageProcSseV2< CUR > && other) private delete
References StageProcSseV2().
~StageProcSseV2()
template<int CUR> hiir::StageProcSseV2< CUR >::~StageProcSseV2 () private delete
References StageProcSseV2().
Member Function Documentation
operator!=()
template<int CUR> bool hiir::StageProcSseV2< CUR >::operator!= (const StageProcSseV2< CUR > & other) const private delete
References StageProcSseV2().
operator=() [1/2]
template<int CUR> StageProcSseV2 & hiir::StageProcSseV2< CUR >::operator= (const StageProcSseV2< CUR > & other) private delete
References StageProcSseV2().
operator=() [2/2]
template<int CUR> StageProcSseV2 & hiir::StageProcSseV2< CUR >::operator= (StageProcSseV2< CUR > && other) private delete
References StageProcSseV2().
operator==()
template<int CUR> bool hiir::StageProcSseV2< CUR >::operator== (const StageProcSseV2< CUR > & other) const private delete
References StageProcSseV2().
process_sample_neg()
template<int CUR> void hiir::StageProcSseV2< CUR >::process_sample_neg (__m128 & x, StageDataSse * stage_arr) static noexcept
Definition at line 46 of file StageProcSseV2.hpp.
References process_sample_neg_rec().
process_sample_neg_rec() [1/2]
hiir_FORCEINLINE void hiir::StageProcSseV2< 0 >::process_sample_neg_rec (__m128 & , StageDataSse *) noexcept
Definition at line 89 of file StageProcSseV2.hpp.
References hiir_FORCEINLINE.
process_sample_neg_rec() [2/2]
template<int CUR> void hiir::StageProcSseV2< CUR >::process_sample_neg_rec (__m128 & x, StageDataSse * stage_arr) static noexcept
Definition at line 76 of file StageProcSseV2.hpp.
References StageProcSseV2(), and process_sample_neg_rec().
Referenced by process_sample_neg(), and process_sample_neg_rec().
process_sample_pos()
template<int CUR> void hiir::StageProcSseV2< CUR >::process_sample_pos (__m128 & x, StageDataSse * stage_arr) static noexcept
Definition at line 37 of file StageProcSseV2.hpp.
References process_sample_pos_rec().
Referenced by hiir::Downsampler2xSse< NC >::process_block(), hiir::Upsampler2xSse< NC >::process_block(), hiir::Downsampler2xSse< NC >::process_block_quad(), hiir::Downsampler2xSse< NC >::process_block_split(), hiir::Downsampler2xSse< NC >::process_sample(), hiir::Upsampler2xSse< NC >::process_sample(), and hiir::Downsampler2xSse< NC >::process_sample_split().
process_sample_pos_rec() [1/2]
hiir_FORCEINLINE void hiir::StageProcSseV2< 0 >::process_sample_pos_rec (__m128 & , StageDataSse *) noexcept
Definition at line 68 of file StageProcSseV2.hpp.
References hiir_FORCEINLINE.
process_sample_pos_rec() [2/2]
template<int CUR> void hiir::StageProcSseV2< CUR >::process_sample_pos_rec (__m128 & x, StageDataSse * stage_arr) static noexcept
Definition at line 55 of file StageProcSseV2.hpp.
References StageProcSseV2(), and process_sample_pos_rec().
Referenced by process_sample_pos(), and process_sample_pos_rec().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProcSseV2.h
src/3rdparty/hiir/hiir/StageProcSseV2.hpp