LMMS: lmms::RemotePlugin Class Reference
lmms::RemotePlugin Class Reference
#include <RemotePlugin.h>
Public Slots
virtual void hideUI ()
virtual void showUI ()
Public Member Functions
RemotePlugin ()
~RemotePlugin () override
bool failed () const
bool init (const QString &pluginExecutable, bool waitForInitDoneMsg, QStringList extraArgs={})
bool isRunning ()
int isUIVisible ()
void lock ()
bool process (const SampleFrame *_in_buf, SampleFrame *_out_buf)
bool processMessage (const message &_m) override
void processMidiEvent (const MidiEvent &, const f_cnt_t _offset)
virtual void toggleUI ()
void unlock ()
void updateSampleRate (sample_rate_t _sr)
void waitForHostInfoGotten ()
void waitForInitDone (bool _busyWaiting=true)
Public Member Functions inherited from lmms::RemotePluginBase
RemotePluginBase (shmFifo *_in, shmFifo *_out)
virtual ~RemotePluginBase ()
void fetchAndProcessAllMessages ()
message fetchAndProcessNextMessage ()
bool isInvalid () const
bool messagesLeft ()
message receiveMessage ()
void reset (shmFifo *in, shmFifo *out)
int sendMessage (const message &_m)
message waitForMessage (const message &_m, bool _busy_waiting=false)
Protected Member Functions
void setSplittedChannels (bool _on)
Protected Member Functions inherited from lmms::RemotePluginBase
const shmFifo * in () const
void invalidate ()
const shmFifo * out () const
Protected Attributes
bool m_failed
Private Slots
void processErrored (QProcess::ProcessError err)
void processFinished (int exitCode, QProcess::ExitStatus exitStatus)
Private Member Functions
void resizeSharedProcessingMemory ()
Private Attributes
QStringList m_args
SharedMemory< float[]> m_audioBuffer
std::size_t m_audioBufferSize
QRecursiveMutex m_commMutex
QString m_exec
int m_inputCount
int m_outputCount
QProcess m_process
int m_server
QString m_socketFile
bool m_splitChannels
ProcessWatcher m_watcher
Friends
class ProcessWatcher
Additional Inherited Members
Static Public Member Functions inherited from lmms::RemotePluginBase
static bool isMainThreadWaiting ()
Detailed Description
Definition at line 72 of file RemotePlugin.h.
Constructor & Destructor Documentation
RemotePlugin()
lmms::RemotePlugin::RemotePlugin ()
Definition at line 133 of file RemotePlugin.cpp.
References lmms::RemotePluginBase::RemotePluginBase(), lmms::DEFAULT_CHANNELS, m_audioBufferSize, m_commMutex, m_failed, m_inputCount, m_outputCount, m_process, m_server, m_socketFile, m_splitChannels, m_watcher, processErrored(), processFinished(), and SYNC_WITH_SHM_FIFO.
~RemotePlugin()
lmms::RemotePlugin::~RemotePlugin () override
Definition at line 192 of file RemotePlugin.cpp.
References lmms::IdQuit, isRunning(), lock(), m_failed, m_process, m_server, m_socketFile, m_watcher, lmms::RemotePluginBase::sendMessage(), and unlock().
Member Function Documentation
failed()
bool lmms::RemotePlugin::failed () const inline
Definition at line 132 of file RemotePlugin.h.
References m_failed.
Referenced by init().
hideUI
void lmms::RemotePlugin::hideUI () virtual slot
Definition at line 473 of file RemotePlugin.cpp.
References lmms::IdHideUI, lock(), lmms::RemotePluginBase::sendMessage(), and unlock().
init()
bool lmms::RemotePlugin::init (const QString & pluginExecutable, bool waitForInitDoneMsg, QStringList extraArgs = {})
Definition at line 226 of file RemotePlugin.cpp.
References failed(), lmms::Engine::getSong(), lmms::IdSyncKey, lmms::RemotePluginBase::in(), lmms::RemotePluginBase::invalidate(), lock(), m_args, m_exec, m_failed, m_process, m_server, m_socketFile, m_watcher, lmms::RemotePluginBase::out(), lmms::RemotePluginBase::reset(), resizeSharedProcessingMemory(), lmms::RemotePluginBase::sendMessage(), unlock(), and waitForInitDone().
isRunning()
bool lmms::RemotePlugin::isRunning () inline
Definition at line 79 of file RemotePlugin.h.
References m_process.
Referenced by ~RemotePlugin(), and process().
isUIVisible()
int lmms::RemotePlugin::isUIVisible () inline
Definition at line 123 of file RemotePlugin.h.
References lmms::RemotePluginBase::message::getInt(), lmms::RemotePluginBase::message::id, lmms::IdIsUIVisible, lock(), lmms::RemotePluginBase::sendMessage(), unlock(), and lmms::RemotePluginBase::waitForMessage().
lock()
void lmms::RemotePlugin::lock () inline
Definition at line 137 of file RemotePlugin.h.
References m_commMutex.
Referenced by ~RemotePlugin(), hideUI(), init(), isUIVisible(), process(), processMessage(), processMidiEvent(), showUI(), toggleUI(), and updateSampleRate().
process()
bool lmms::RemotePlugin::process (const SampleFrame * _in_buf, SampleFrame * _out_buf)
Definition at line 333 of file RemotePlugin.cpp.
References lmms::Engine::audioEngine(), lmms::copyFromSampleFrames(), lmms::copyToSampleFrames(), lmms::DEFAULT_CHANNELS, lmms::RemotePluginBase::fetchAndProcessAllMessages(), lmms::AudioEngine::framesPerPeriod(), lmms::IdProcessingDone, lmms::IdStartProcessing, isRunning(), lock(), m_audioBuffer, m_audioBufferSize, m_failed, m_inputCount, m_outputCount, m_splitChannels, lmms::RemotePluginBase::sendMessage(), unlock(), lmms::RemotePluginBase::waitForMessage(), and lmms::zeroSampleFrames().
processErrored
void lmms::RemotePlugin::processErrored (QProcess::ProcessError err) private slot
Definition at line 519 of file RemotePlugin.cpp.
Referenced by RemotePlugin(), and ProcessWatcher.
processFinished
void lmms::RemotePlugin::processFinished (int exitCode, QProcess::ExitStatus exitStatus) private slot
Definition at line 503 of file RemotePlugin.cpp.
References lmms::RemotePluginBase::invalidate().
Referenced by RemotePlugin(), and ProcessWatcher.
processMessage()
bool lmms::RemotePlugin::processMessage (const message & _m) override virtual
Implements lmms::RemotePluginBase.
Definition at line 527 of file RemotePlugin.cpp.
References lmms::RemotePluginBase::message::addInt(), lmms::Engine::audioEngine(), lmms::RemotePluginBase::message::getInt(), lmms::RemotePluginBase::message::getString(), lmms::RemotePluginBase::message::id, lmms::IdBufferSizeInformation, lmms::IdChangeInputCount, lmms::IdChangeInputOutputCount, lmms::IdChangeOutputCount, lmms::IdDebugMessage, lmms::IdInitDone, lmms::IdProcessingDone, lmms::IdQuit, lmms::IdSampleRateInformation, lmms::IdUndefined, lock(), m_inputCount, m_outputCount, resizeSharedProcessingMemory(), lmms::RemotePluginBase::sendMessage(), and unlock().
processMidiEvent()
void lmms::RemotePlugin::processMidiEvent (const MidiEvent & _e, const f_cnt_t _offset)
Definition at line 452 of file RemotePlugin.cpp.
References lmms::RemotePluginBase::message::addInt(), lmms::MidiEvent::channel(), lmms::IdMidiEvent, lock(), lmms::MidiEvent::param(), lmms::RemotePluginBase::sendMessage(), lmms::MidiEvent::type(), and unlock().
resizeSharedProcessingMemory()
void lmms::RemotePlugin::resizeSharedProcessingMemory () private
Definition at line 483 of file RemotePlugin.cpp.
References lmms::Engine::audioEngine(), lmms::IdChangeSharedMemoryKey, m_audioBuffer, m_audioBufferSize, m_inputCount, m_outputCount, and lmms::RemotePluginBase::sendMessage().
Referenced by init(), and processMessage().
setSplittedChannels()
void lmms::RemotePlugin::setSplittedChannels (bool _on) inline protected
Definition at line 152 of file RemotePlugin.h.
References m_splitChannels.
showUI
void lmms::RemotePlugin::showUI () virtual slot
Definition at line 466 of file RemotePlugin.cpp.
References lmms::IdShowUI, lock(), lmms::RemotePluginBase::sendMessage(), and unlock().
toggleUI()
virtual void lmms::RemotePlugin::toggleUI () inline virtual
Definition at line 116 of file RemotePlugin.h.
References lmms::IdToggleUI, lock(), lmms::RemotePluginBase::sendMessage(), and unlock().
unlock()
void lmms::RemotePlugin::unlock () inline
Definition at line 142 of file RemotePlugin.h.
References m_commMutex.
Referenced by ~RemotePlugin(), hideUI(), init(), isUIVisible(), process(), processMessage(), processMidiEvent(), showUI(), toggleUI(), and updateSampleRate().
updateSampleRate()
void lmms::RemotePlugin::updateSampleRate (sample_rate_t _sr) inline
Definition at line 107 of file RemotePlugin.h.
References lmms::IdInformationUpdated, lmms::IdSampleRateInformation, lock(), lmms::RemotePluginBase::sendMessage(), unlock(), and lmms::RemotePluginBase::waitForMessage().
waitForHostInfoGotten()
void lmms::RemotePlugin::waitForHostInfoGotten () inline
Definition at line 90 of file RemotePlugin.h.
References lmms::IdHostInfoGotten, m_failed, and lmms::RemotePluginBase::waitForMessage().
waitForInitDone()
void lmms::RemotePlugin::waitForInitDone (bool _busyWaiting = true) inline
Definition at line 96 of file RemotePlugin.h.
References lmms::IdInitDone, m_failed, and lmms::RemotePluginBase::waitForMessage().
Referenced by init().
Friends And Related Symbol Documentation
ProcessWatcher
friend class ProcessWatcher friend
Definition at line 187 of file RemotePlugin.h.
References processErrored(), processFinished(), and ProcessWatcher.
Referenced by ProcessWatcher.
Member Data Documentation
m_args
QStringList lmms::RemotePlugin::m_args private
Definition at line 167 of file RemotePlugin.h.
Referenced by init().
m_audioBuffer
SharedMemory<float[]> lmms::RemotePlugin::m_audioBuffer private
Definition at line 176 of file RemotePlugin.h.
Referenced by process(), and resizeSharedProcessingMemory().
m_audioBufferSize
std::size_t lmms::RemotePlugin::m_audioBufferSize private
Definition at line 177 of file RemotePlugin.h.
Referenced by RemotePlugin(), process(), and resizeSharedProcessingMemory().
m_commMutex
QRecursiveMutex lmms::RemotePlugin::m_commMutex private
Definition at line 170 of file RemotePlugin.h.
Referenced by RemotePlugin(), lock(), and unlock().
m_exec
QString lmms::RemotePlugin::m_exec private
Definition at line 166 of file RemotePlugin.h.
Referenced by init().
m_failed
bool lmms::RemotePlugin::m_failed protected
Definition at line 158 of file RemotePlugin.h.
Referenced by RemotePlugin(), ~RemotePlugin(), failed(), init(), process(), waitForHostInfoGotten(), and waitForInitDone().
m_inputCount
int lmms::RemotePlugin::m_inputCount private
Definition at line 179 of file RemotePlugin.h.
Referenced by RemotePlugin(), process(), processMessage(), and resizeSharedProcessingMemory().
m_outputCount
int lmms::RemotePlugin::m_outputCount private
Definition at line 180 of file RemotePlugin.h.
Referenced by RemotePlugin(), process(), processMessage(), and resizeSharedProcessingMemory().
m_process
QProcess lmms::RemotePlugin::m_process private
Definition at line 163 of file RemotePlugin.h.
Referenced by RemotePlugin(), ~RemotePlugin(), init(), and isRunning().
m_server
int lmms::RemotePlugin::m_server private
Definition at line 183 of file RemotePlugin.h.
Referenced by RemotePlugin(), ~RemotePlugin(), and init().
m_socketFile
QString lmms::RemotePlugin::m_socketFile private
Definition at line 184 of file RemotePlugin.h.
Referenced by RemotePlugin(), ~RemotePlugin(), and init().
m_splitChannels
bool lmms::RemotePlugin::m_splitChannels private
Definition at line 174 of file RemotePlugin.h.
Referenced by RemotePlugin(), process(), and setSplittedChannels().
m_watcher
ProcessWatcher lmms::RemotePlugin::m_watcher private
Definition at line 164 of file RemotePlugin.h.
Referenced by RemotePlugin(), ~RemotePlugin(), and init().
The documentation for this class was generated from the following files:
include/RemotePlugin.h
src/core/RemotePlugin.cpp