LMMS: hiir::Downsampler2x8F64Avx512< NC > Class Template Reference
hiir::Downsampler2x8F64Avx512< NC > Class Template Reference
#include <Downsampler2x8F64Avx512.h>
Public Types
typedef double DataType
Public Member Functions
Downsampler2x8F64Avx512 () noexcept
Downsampler2x8F64Avx512 (const Downsampler2x8F64Avx512< NC > &other)=default
Downsampler2x8F64Avx512 (Downsampler2x8F64Avx512< NC > &&other)=default
~Downsampler2x8F64Avx512 ()=default
void clear_buffers () noexcept
Downsampler2x8F64Avx512< NC > & operator= (const Downsampler2x8F64Avx512< NC > &other)=default
Downsampler2x8F64Avx512< NC > & operator= (Downsampler2x8F64Avx512< NC > &&other)=default
void process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
void process_block_split (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE __m512d process_sample (__m512d in_0, __m512d in_1) noexcept
hiir_FORCEINLINE __m512d process_sample (const double in_ptr[_nbr_chn *2]) noexcept
hiir_FORCEINLINE void process_sample_split (__m512d &low, __m512d &high, __m512d in_0, __m512d in_1) noexcept
hiir_FORCEINLINE void process_sample_split (__m512d &low, __m512d &high, const double in_ptr[_nbr_chn *2]) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = -1
static constexpr int _nbr_chn = 8
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Avx512, NBR_COEFS+2 > Filter
Private Member Functions
bool operator!= (const Downsampler2x8F64Avx512< NC > &other) const =delete
bool operator== (const Downsampler2x8F64Avx512< NC > &other) const =delete
Private Attributes
Filter _filter
Detailed Description
template<int NC>
class hiir::Downsampler2x8F64Avx512< NC >
Definition at line 53 of file Downsampler2x8F64Avx512.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::Downsampler2x8F64Avx512< NC >::DataType
Definition at line 62 of file Downsampler2x8F64Avx512.h.
Filter
template<int NC> typedef std::array<StageDataF64Avx512, NBR_COEFS + 2> hiir::Downsampler2x8F64Avx512< NC >::Filter private
Definition at line 105 of file Downsampler2x8F64Avx512.h.
Constructor & Destructor Documentation
Downsampler2x8F64Avx512() [1/3]
template<int NC> hiir::Downsampler2x8F64Avx512< NC >::Downsampler2x8F64Avx512 () noexcept
Definition at line 57 of file Downsampler2x8F64Avx512.hpp.
References _filter, clear_buffers(), i, and NBR_COEFS.
Referenced by Downsampler2x8F64Avx512(), Downsampler2x8F64Avx512(), ~Downsampler2x8F64Avx512(), operator!=(), operator=(), operator=(), and operator==().
Downsampler2x8F64Avx512() [2/3]
template<int NC> hiir::Downsampler2x8F64Avx512< NC >::Downsampler2x8F64Avx512 (const Downsampler2x8F64Avx512< NC > & other) default
References Downsampler2x8F64Avx512().
Downsampler2x8F64Avx512() [3/3]
template<int NC> hiir::Downsampler2x8F64Avx512< NC >::Downsampler2x8F64Avx512 (Downsampler2x8F64Avx512< NC > && other) default
References Downsampler2x8F64Avx512().
~Downsampler2x8F64Avx512()
template<int NC> hiir::Downsampler2x8F64Avx512< NC >::~Downsampler2x8F64Avx512 () default
References Downsampler2x8F64Avx512().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Downsampler2x8F64Avx512< NC >::clear_buffers () noexcept
Definition at line 329 of file Downsampler2x8F64Avx512.hpp.
References _filter, i, and NBR_COEFS.
Referenced by Downsampler2x8F64Avx512(), and operator=().
operator!=()
template<int NC> bool hiir::Downsampler2x8F64Avx512< NC >::operator!= (const Downsampler2x8F64Avx512< NC > & other) const private delete
References Downsampler2x8F64Avx512().
operator=() [1/2]
template<int NC> Downsampler2x8F64Avx512< NC > & hiir::Downsampler2x8F64Avx512< NC >::operator= (const Downsampler2x8F64Avx512< NC > & other) default
References Downsampler2x8F64Avx512().
operator=() [2/2]
template<int NC> Downsampler2x8F64Avx512< NC > & hiir::Downsampler2x8F64Avx512< NC >::operator= (Downsampler2x8F64Avx512< NC > && other) default
References Downsampler2x8F64Avx512(), _nbr_chn, clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_split(), process_sample(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::Downsampler2x8F64Avx512< NC >::operator== (const Downsampler2x8F64Avx512< NC > & other) const private delete
References Downsampler2x8F64Avx512().
process_block()
template<int NC> void hiir::Downsampler2x8F64Avx512< NC >::process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 175 of file Downsampler2x8F64Avx512.hpp.
References _nbr_chn, pos, and process_sample().
Referenced by operator=().
process_block_split()
template<int NC> void hiir::Downsampler2x8F64Avx512< NC >::process_block_split (double out_l_ptr[], double out_h_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 293 of file Downsampler2x8F64Avx512.hpp.
References _nbr_chn, pos, and process_sample_split().
Referenced by operator=().
process_sample() [1/2]
template<int NC> __m512d hiir::Downsampler2x8F64Avx512< NC >::process_sample (__m512d in_0, __m512d in_1) noexcept
Definition at line 140 of file Downsampler2x8F64Avx512.hpp.
References _filter, NBR_COEFS, and hiir::StageProc8F64Avx512< REMAINING >::process_sample_pos().
process_sample() [2/2]
template<int NC> __m512d hiir::Downsampler2x8F64Avx512< NC >::process_sample (const double in_ptr[_nbr_chn *2]) noexcept
Definition at line 113 of file Downsampler2x8F64Avx512.hpp.
References _nbr_chn, and process_sample().
Referenced by operator=(), process_block(), and process_sample().
process_sample_split() [1/2]
template<int NC> void hiir::Downsampler2x8F64Avx512< NC >::process_sample_split (__m512d & low, __m512d & high, __m512d in_0, __m512d in_1) noexcept
Definition at line 249 of file Downsampler2x8F64Avx512.hpp.
References _filter, NBR_COEFS, and hiir::StageProc8F64Avx512< REMAINING >::process_sample_pos().
process_sample_split() [2/2]
template<int NC> void hiir::Downsampler2x8F64Avx512< NC >::process_sample_split (__m512d & low, __m512d & high, const double in_ptr[_nbr_chn *2]) noexcept
Definition at line 215 of file Downsampler2x8F64Avx512.hpp.
References _nbr_chn, and process_sample_split().
Referenced by operator=(), process_block_split(), and process_sample_split().
set_coefs()
template<int NC> void hiir::Downsampler2x8F64Avx512< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 85 of file Downsampler2x8F64Avx512.hpp.
References _filter, i, and NBR_COEFS.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Downsampler2x8F64Avx512< NC >::_delay = -1 static constexpr
Definition at line 65 of file Downsampler2x8F64Avx512.h.
_filter
template<int NC> Filter hiir::Downsampler2x8F64Avx512< NC >::_filter private
Definition at line 107 of file Downsampler2x8F64Avx512.h.
Referenced by Downsampler2x8F64Avx512(), clear_buffers(), process_sample(), process_sample_split(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Downsampler2x8F64Avx512< NC >::_nbr_chn = 8 static constexpr
Definition at line 63 of file Downsampler2x8F64Avx512.h.
Referenced by operator=(), process_block(), process_block_split(), process_sample(), and process_sample_split().
NBR_COEFS
template<int NC> int hiir::Downsampler2x8F64Avx512< NC >::NBR_COEFS = NC static constexpr
Definition at line 64 of file Downsampler2x8F64Avx512.h.
Referenced by Downsampler2x8F64Avx512(), clear_buffers(), process_sample(), process_sample_split(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Downsampler2x8F64Avx512.h
src/3rdparty/hiir/hiir/Downsampler2x8F64Avx512.hpp