LMMS: Jack::JackAtomicArrayState< T > Class Template Reference
Jack::JackAtomicArrayState< T > Class Template Reference
A class to handle several states in a lock-free manner.
#include <JackAtomicArrayState.h>
Public Member Functions
JackAtomicArrayState ()
~JackAtomicArrayState ()
UInt16 GetCurrentIndex ()
Returns the current switch counter.
T * ReadCurrentState ()
Returns the current state : only valid in the RT reader thread.
T * TrySwitchState (int state)
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
T * TrySwitchState (int state, bool *result)
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
T * WriteNextStateStart (int state)
Start write operation : setup and returns the next state to update, check for recursive write calls.
T * WriteNextStateStart (int state, bool *result)
void WriteNextStateStop (int state)
Stop write operation : make the next state ready to be used by the RT thread.
Protected Member Functions
UInt32 WriteNextStateStartAux (int state, bool *result)
void WriteNextStateStopAux (int state)
Protected Attributes
volatile AtomicArrayCounter fCounter
T fState [3]
Detailed Description
template<class T>
class Jack::JackAtomicArrayState< T >
A class to handle several states in a lock-free manner.
Requirement:
- a "current" state
- several possible "pending" state
- an TrySwitchState(int state) operation to atomically switch a "pending" to the "current" state (the pending becomes the current).
The TrySwitchState operation returns a "current" state (either the same if switch fails or the new one, one can know if the switch has succeeded)
- a WriteNextStartState(int state) returns a "pending" state to be written into
- a WriteNextStartStop(int state) make the written "pending" state become "switchable"
Different pending states can be written independently and concurrently.
GetCurrentIndex() *must* return an increasing value to be able to check reading current state coherency
The fCounter is an array of indexes to access the current and 3 different "pending" states.
  WriteNextStateStart(int index) must return a valid state to be written into, and must invalidate state "index" ==> cur state switch.
  WriteNextStateStop(int index) makes the "index" state become "switchable" with the current state.
  TrySwitchState(int index) must detect that pending state is a new state, and does the switch
  ReadCurrentState() must return the state
  GetCurrentIndex() must return an index increased each new switch.
  WriteNextStateStart(int index1) and WriteNextStateStart(int index2) can be interleaved
[switch counter][index state][index state][cur index]
Definition at line 115 of file JackAtomicArrayState.h.
Constructor & Destructor Documentation
JackAtomicArrayState()
template<class T> Jack::JackAtomicArrayState< T >::JackAtomicArrayState () inline
Definition at line 161 of file JackAtomicArrayState.h.
References JackAtomicArrayState(), Counter1, fCounter, and offsetof.
Referenced by JackAtomicArrayState().
~JackAtomicArrayState()
template<class T> Jack::JackAtomicArrayState< T >::~JackAtomicArrayState () inline
Definition at line 168 of file JackAtomicArrayState.h.
Member Function Documentation
GetCurrentIndex()
template<class T> UInt16 Jack::JackAtomicArrayState< T >::GetCurrentIndex () inline
Returns the current switch counter.
Definition at line 184 of file JackAtomicArrayState.h.
References fCounter, and GetIndex1.
ReadCurrentState()
template<class T> T * Jack::JackAtomicArrayState< T >::ReadCurrentState () inline
Returns the current state : only valid in the RT reader thread.
Definition at line 175 of file JackAtomicArrayState.h.
References fCounter, fState, and GetIndex1.
Referenced by Jack::JackClient::CallSyncCallbackAux().
TrySwitchState() [1/2]
template<class T> T * Jack::JackAtomicArrayState< T >::TrySwitchState (int state) inline
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
Definition at line 193 of file JackAtomicArrayState.h.
References CAS(), Counter1, fCounter, fState, GetIndex1, IncIndex1, SetIndex1, and SwapIndex1.
TrySwitchState() [2/2]
template<class T> T * Jack::JackAtomicArrayState< T >::TrySwitchState (int state, bool * result) inline
Tries to switch to the next state and returns the new current state (either the same as before if case of switch failure or the new one).
Definition at line 213 of file JackAtomicArrayState.h.
References CAS(), Counter1, fCounter, fState, GetIndex1, IncIndex1, SetIndex1, and SwapIndex1.
WriteNextStateStart() [1/2]
template<class T> T * Jack::JackAtomicArrayState< T >::WriteNextStateStart (int state) inline
Start write operation : setup and returns the next state to update, check for recursive write calls.
Definition at line 233 of file JackAtomicArrayState.h.
References fState, and WriteNextStateStartAux().
Referenced by Jack::JackClient::CallTimebaseCallbackAux().
WriteNextStateStart() [2/2]
template<class T> T * Jack::JackAtomicArrayState< T >::WriteNextStateStart (int state, bool * result) inline
Definition at line 240 of file JackAtomicArrayState.h.
References fState, and WriteNextStateStartAux().
WriteNextStateStartAux()
template<class T> UInt32 Jack::JackAtomicArrayState< T >::WriteNextStateStartAux (int state, bool * result) inline protected
Definition at line 127 of file JackAtomicArrayState.h.
References CAS(), Counter1, fCounter, fState, GetIndex1, SetIndex1, and SwapIndex1.
Referenced by WriteNextStateStart(), and WriteNextStateStart().
WriteNextStateStop()
template<class T> void Jack::JackAtomicArrayState< T >::WriteNextStateStop (int state) inline
Stop write operation : make the next state ready to be used by the RT thread.
Definition at line 250 of file JackAtomicArrayState.h.
References WriteNextStateStopAux().
Referenced by Jack::JackClient::CallTimebaseCallbackAux().
WriteNextStateStopAux()
template<class T> void Jack::JackAtomicArrayState< T >::WriteNextStateStopAux (int state) inline protected
Definition at line 148 of file JackAtomicArrayState.h.
References CAS(), Counter1, fCounter, and SetIndex1.
Referenced by WriteNextStateStop().
Member Data Documentation
fCounter
template<class T> volatile AtomicArrayCounter Jack::JackAtomicArrayState< T >::fCounter protected
Definition at line 125 of file JackAtomicArrayState.h.
Referenced by JackAtomicArrayState(), GetCurrentIndex(), ReadCurrentState(), TrySwitchState(), TrySwitchState(), WriteNextStateStartAux(), and WriteNextStateStopAux().
fState
template<class T> T Jack::JackAtomicArrayState< T >::fState[3] protected
Definition at line 124 of file JackAtomicArrayState.h.
Referenced by ReadCurrentState(), TrySwitchState(), TrySwitchState(), WriteNextStateStart(), WriteNextStateStart(), and WriteNextStateStartAux().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackAtomicArrayState.h