LMMS: Jack::JackTimedDriver Class Reference
Jack::JackTimedDriver Class Reference
The timed driver.
#include <JackTimedDriver.h>
Public Member Functions
JackTimedDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackTimedDriver ()
bool IsFixedBufferSize ()
int Start ()
Public Member Functions inherited from Jack::JackAudioDriver
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int Attach ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Detach ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetSampleRate (jack_nframes_t sample_rate)
virtual int Write ()
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual int Close ()
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
virtual int Read ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
virtual int Stop ()
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Protected Member Functions
int CurrentCycle (jack_time_t cur_time)
int FirstCycle (jack_time_t cur_time)
void ProcessWait ()
Protected Member Functions inherited from Jack::JackAudioDriver
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
virtual void UpdateLatencies ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes
jack_time_t fAnchorTimeUsec
int fCycleCount
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The timed driver.
Definition at line 33 of file JackTimedDriver.h.
Constructor & Destructor Documentation
JackTimedDriver()
Jack::JackTimedDriver::JackTimedDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table) inline
Definition at line 47 of file JackTimedDriver.h.
References Jack::JackAudioDriver::JackAudioDriver(), fAnchorTimeUsec, and fCycleCount.
Referenced by Jack::JackDummyDriver::JackDummyDriver(), and Jack::JackWaiterDriver::JackWaiterDriver().
~JackTimedDriver()
virtual Jack::JackTimedDriver::~JackTimedDriver () inline virtual
Definition at line 50 of file JackTimedDriver.h.
Member Function Documentation
CurrentCycle()
int Jack::JackTimedDriver::CurrentCycle (jack_time_t cur_time) protected
Definition at line 38 of file JackTimedDriver.cpp.
References fAnchorTimeUsec, fCycleCount, and Jack::JackDriver::fEngineControl.
Referenced by ProcessWait().
FirstCycle()
int Jack::JackTimedDriver::FirstCycle (jack_time_t cur_time) protected
Definition at line 32 of file JackTimedDriver.cpp.
References fAnchorTimeUsec, and Jack::JackDriver::fEngineControl.
Referenced by ProcessWait().
IsFixedBufferSize()
bool Jack::JackTimedDriver::IsFixedBufferSize () inline virtual
Reimplemented from Jack::JackDriver.
Definition at line 54 of file JackTimedDriver.h.
ProcessWait()
void Jack::JackTimedDriver::ProcessWait () protected
Definition at line 49 of file JackTimedDriver.cpp.
References CurrentCycle(), Jack::JackDriver::fBeginDateUst, fCycleCount, FirstCycle(), GetMicroSeconds(), jack_error, JackSleep(), and Jack::JackDriver::NotifyXRun().
Referenced by Jack::JackDummyDriver::Process(), and Jack::JackWaiterDriver::ProcessNull().
Start()
int Jack::JackTimedDriver::Start () virtual
Reimplemented from Jack::JackDriver.
Definition at line 43 of file JackTimedDriver.cpp.
References fCycleCount, and Jack::JackDriverInterface::Start().
Member Data Documentation
fAnchorTimeUsec
jack_time_t Jack::JackTimedDriver::fAnchorTimeUsec protected
Definition at line 38 of file JackTimedDriver.h.
Referenced by JackTimedDriver(), CurrentCycle(), and FirstCycle().
fCycleCount
int Jack::JackTimedDriver::fCycleCount protected
Definition at line 37 of file JackTimedDriver.h.
Referenced by JackTimedDriver(), CurrentCycle(), ProcessWait(), and Start().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackTimedDriver.h
src/3rdparty/jack2/common/JackTimedDriver.cpp