LMMS: lmms::gui::SampleTrackView Class Reference
lmms::gui::SampleTrackView Class Reference
#include <SampleTrackView.h>
Public Slots
void showEffects ()
void updateIndicator ()
Public Slots inherited from lmms::gui::TrackView
virtual bool close ()
Close this track View.
Public Member Functions
SampleTrackView (SampleTrack *Track, TrackContainerView *tcv)
~SampleTrackView () override
QMenu * createMixerMenu (QString title, QString newMixerLabel) override
Create a menu for assigning/creating channels for this track.
SampleTrackWindow * getSampleTrackWindow ()
SampleTrack * model ()
const SampleTrack * model () const
Public Member Functions inherited from lmms::gui::TrackView
TrackView (Track *_track, TrackContainerView *tcv)
Create a new track View.
~TrackView () override=default
Track * getTrack ()
const Track * getTrack () const
TrackContentWidget * getTrackContentWidget ()
TrackOperationsWidget * getTrackOperationsWidget ()
QWidget * getTrackSettingsWidget ()
bool isMovingTrack () const
TrackContainerView * trackContainerView ()
virtual void update ()
Update this track View and all its content objects.
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *dee) override
void dropEvent (QDropEvent *de) override
void modelChanged () override
QString nodeName () const override
Protected Member Functions inherited from lmms::gui::TrackView
void dragEnterEvent (QDragEnterEvent *dee) override
Start a drag event on this track View.
void dropEvent (QDropEvent *de) override
Accept a drop event on this track View.
void loadSettings (const QDomElement &element) override
void modelChanged () override
Register that the model of this track View has changed.
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse move event on this track View.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press event on this track View.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release event on this track View.
QString nodeName () const override
void paintEvent (QPaintEvent *pe) override
Repaint this track View.
void resizeEvent (QResizeEvent *re) override
Resize this track View.
void saveSettings (QDomDocument &doc, QDomElement &element) override
void wheelEvent (QWheelEvent *we) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Slots
void assignMixerLine (int channelIndex)
Assign a specific mixer Channel for this track.
void createMixerLine ()
Create and assign a new mixer Channel for this track.
Private Member Functions
FadeButton * getActivityIndicator () override
Private Attributes
FadeButton * m_activityIndicator
MixerChannelLcdSpinBox * m_mixerChannelNumber
Knob * m_panningKnob
TrackLabelButton * m_tlb
Knob * m_volumeKnob
SampleTrackWindow * m_window
Friends
class SampleTrackWindow
Detailed Description
Definition at line 44 of file SampleTrackView.h.
Constructor & Destructor Documentation
SampleTrackView()
lmms::gui::SampleTrackView::SampleTrackView (SampleTrack * Track, TrackContainerView * tcv)
Definition at line 54 of file SampleTrackView.cpp.
References lmms::gui::TrackView::TrackView(), lmms::embed::getIconPixmap(), lmms::gui::TrackView::getTrackSettingsWidget(), lmms::gui::Knob::LegacyFixedFontSize, m_activityIndicator, m_mixerChannelNumber, m_panningKnob, lmms::SampleTrack::m_panningModel, m_tlb, m_volumeKnob, lmms::SampleTrack::m_volumeModel, m_window, SampleTrackWindow, lmms::gui::ModelView::setModel(), showEffects(), lmms::gui::Small17, lmms::gui::TrackView::TrackLabelButton, and updateIndicator().
~SampleTrackView()
lmms::gui::SampleTrackView::~SampleTrackView () override
Definition at line 122 of file SampleTrackView.cpp.
References m_window.
Member Function Documentation
assignMixerLine
void lmms::gui::SampleTrackView::assignMixerLine (int channelIndex) private slot
Assign a specific mixer Channel for this track.
Definition at line 245 of file SampleTrackView.cpp.
References lmms::gui::getGUI(), lmms::SampleTrack::mixerChannelModel(), lmms::gui::GuiApplication::mixerView(), model(), lmms::gui::MixerView::setCurrentMixerChannel(), and lmms::AutomatableModel::setValue().
Referenced by createMixerLine(), and createMixerMenu().
createMixerLine
void lmms::gui::SampleTrackView::createMixerLine () private slot
Create and assign a new mixer Channel for this track.
Definition at line 230 of file SampleTrackView.cpp.
References lmms::gui::MixerView::addNewChannel(), assignMixerLine(), lmms::gui::getGUI(), lmms::gui::TrackView::getTrack(), lmms::MixerChannel::m_name, lmms::Engine::mixer(), lmms::Mixer::mixerChannel(), lmms::gui::GuiApplication::mixerView(), and lmms::Track::name().
Referenced by createMixerMenu().
createMixerMenu()
QMenu * lmms::gui::SampleTrackView::createMixerMenu (QString title, QString newMixerLabel) override virtual
Create a menu for assigning/creating channels for this track.
Reimplemented from lmms::gui::TrackView.
Definition at line 135 of file SampleTrackView.cpp.
References assignMixerLine(), createMixerLine(), i, lmms::MixerChannel::index(), lmms::MixerChannel::m_name, lmms::Engine::mixer(), lmms::Mixer::mixerChannel(), lmms::SampleTrack::mixerChannelModel(), model(), lmms::Mixer::numChannels(), and lmms::TypedAutomatableModel< T >::value().
dragEnterEvent()
void lmms::gui::SampleTrackView::dragEnterEvent (QDragEnterEvent * dee) override protected
Definition at line 191 of file SampleTrackView.cpp.
References lmms::gui::StringPairDrag::processDragEnterEvent().
dropEvent()
void lmms::gui::SampleTrackView::dropEvent (QDropEvent * de) override protected
Definition at line 199 of file SampleTrackView.cpp.
References lmms::Track::createClip(), lmms::gui::StringPairDrag::decodeKey(), lmms::gui::StringPairDrag::decodeValue(), lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH, lmms::gui::DEFAULT_SETTINGS_WIDGET_WIDTH_COMPACT, lmms::gui::TrackContainerView::fixedClips(), lmms::gui::getGUI(), lmms::gui::SongEditor::getSnapSize(), lmms::gui::TrackView::getTrack(), lmms::ConfigManager::inst(), lmms::gui::SongEditorWindow::m_editor, lmms::TimePos::quantize(), lmms::gui::GuiApplication::songEditor(), lmms::TimePos::ticksPerBar(), lmms::gui::TRACK_OP_WIDTH, lmms::gui::TRACK_OP_WIDTH_COMPACT, lmms::gui::TrackView::trackContainerView(), and lmms::ConfigManager::value().
getActivityIndicator()
FadeButton * lmms::gui::SampleTrackView::getActivityIndicator () inline override private virtual
Reimplemented from lmms::gui::TrackView.
Definition at line 99 of file SampleTrackView.h.
References m_activityIndicator.
getSampleTrackWindow()
SampleTrackWindow * lmms::gui::SampleTrackView::getSampleTrackWindow () inline
Definition at line 51 of file SampleTrackView.h.
References m_window, and SampleTrackWindow.
model() [1/2]
SampleTrack * lmms::gui::SampleTrackView::model () inline
Definition at line 56 of file SampleTrackView.h.
References lmms::gui::ModelView::castModel().
Referenced by lmms::gui::SampleTrackWindow::SampleTrackWindow(), assignMixerLine(), createMixerMenu(), and updateIndicator().
model() [2/2]
const SampleTrack * lmms::gui::SampleTrackView::model () const inline
Definition at line 61 of file SampleTrackView.h.
References lmms::gui::ModelView::castModel().
modelChanged()
void lmms::gui::SampleTrackView::modelChanged () override protected virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 179 of file SampleTrackView.cpp.
References lmms::gui::ModelView::castModel(), m_mixerChannelNumber, m_volumeKnob, and lmms::gui::TrackView::modelChanged().
nodeName()
QString lmms::gui::SampleTrackView::nodeName () const inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 77 of file SampleTrackView.h.
showEffects
void lmms::gui::SampleTrackView::showEffects () slot
Definition at line 172 of file SampleTrackView.cpp.
References m_window.
Referenced by SampleTrackView().
updateIndicator
void lmms::gui::SampleTrackView::updateIndicator () slot
Definition at line 113 of file SampleTrackView.cpp.
References m_activityIndicator, and model().
Referenced by SampleTrackView().
Friends And Related Symbol Documentation
SampleTrackWindow
friend class SampleTrackWindow friend
Definition at line 104 of file SampleTrackView.h.
References SampleTrackWindow.
Referenced by SampleTrackView(), getSampleTrackWindow(), and SampleTrackWindow.
Member Data Documentation
m_activityIndicator
FadeButton* lmms::gui::SampleTrackView::m_activityIndicator private
Definition at line 95 of file SampleTrackView.h.
Referenced by SampleTrackView(), getActivityIndicator(), and updateIndicator().
m_mixerChannelNumber
MixerChannelLcdSpinBox* lmms::gui::SampleTrackView::m_mixerChannelNumber private
Definition at line 92 of file SampleTrackView.h.
Referenced by SampleTrackView(), and modelChanged().
m_panningKnob
Knob* lmms::gui::SampleTrackView::m_panningKnob private
Definition at line 94 of file SampleTrackView.h.
Referenced by SampleTrackView().
m_tlb
TrackLabelButton* lmms::gui::SampleTrackView::m_tlb private
Definition at line 97 of file SampleTrackView.h.
Referenced by SampleTrackView().
m_volumeKnob
Knob* lmms::gui::SampleTrackView::m_volumeKnob private
Definition at line 93 of file SampleTrackView.h.
Referenced by SampleTrackView(), and modelChanged().
m_window
SampleTrackWindow* lmms::gui::SampleTrackView::m_window private
Definition at line 91 of file SampleTrackView.h.
Referenced by SampleTrackView(), ~SampleTrackView(), getSampleTrackWindow(), and showEffects().
The documentation for this class was generated from the following files:
include/SampleTrackView.h
src/gui/tracks/SampleTrackView.cpp