LMMS: hiir::PhaseHalfPiSse< NC > Class Template Reference
hiir::PhaseHalfPiSse< NC > Class Template Reference
#include <PhaseHalfPiSse.h>
Public Types
typedef float DataType
Public Member Functions
PhaseHalfPiSse () noexcept
PhaseHalfPiSse (const PhaseHalfPiSse< NC > &other)=default
PhaseHalfPiSse (PhaseHalfPiSse< NC > &&other)=default
~PhaseHalfPiSse ()=default
void clear_buffers () noexcept
PhaseHalfPiSse< NC > & operator= (const PhaseHalfPiSse< NC > &other)=default
PhaseHalfPiSse< NC > & operator= (PhaseHalfPiSse< NC > &&other)=default
void process_block (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (float &out_0, float &out_1, float input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 2
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataSse, _nbr_stages+1 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const PhaseHalfPiSse< NC > &other)=delete
bool operator== (const PhaseHalfPiSse< NC > &other)=delete
hiir_FORCEINLINE long process_block_quad (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
void set_single_coef (int index, double coef) noexcept
Private Attributes
FilterBiPhase _filter
int _phase
float _prev
Static Private Attributes
static constexpr int _coef_shift = ((NBR_COEFS & 1) * 2) ^ 3
static constexpr int _nbr_phases = 2
static constexpr int _nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width
static constexpr int _stage_width = 4
Detailed Description
template<int NC>
class hiir::PhaseHalfPiSse< NC >
Definition at line 56 of file PhaseHalfPiSse.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::PhaseHalfPiSse< NC >::DataType
Definition at line 65 of file PhaseHalfPiSse.h.
Filter
template<int NC> typedef std::array<StageDataSse, _nbr_stages + 1> hiir::PhaseHalfPiSse< NC >::Filter private
Definition at line 106 of file PhaseHalfPiSse.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::PhaseHalfPiSse< NC >::FilterBiPhase private
Definition at line 107 of file PhaseHalfPiSse.h.
Constructor & Destructor Documentation
PhaseHalfPiSse() [1/3]
template<int NC> hiir::PhaseHalfPiSse< NC >::PhaseHalfPiSse () noexcept
Definition at line 64 of file PhaseHalfPiSse.hpp.
References _filter, _nbr_phases, _nbr_stages, _phase, _prev, _stage_width, clear_buffers(), i, NBR_COEFS, and set_single_coef().
Referenced by PhaseHalfPiSse(), PhaseHalfPiSse(), ~PhaseHalfPiSse(), operator!=(), operator=(), operator=(), and operator==().
PhaseHalfPiSse() [2/3]
template<int NC> hiir::PhaseHalfPiSse< NC >::PhaseHalfPiSse (const PhaseHalfPiSse< NC > & other) default
References PhaseHalfPiSse().
PhaseHalfPiSse() [3/3]
template<int NC> hiir::PhaseHalfPiSse< NC >::PhaseHalfPiSse (PhaseHalfPiSse< NC > && other) default
References PhaseHalfPiSse().
~PhaseHalfPiSse()
template<int NC> hiir::PhaseHalfPiSse< NC >::~PhaseHalfPiSse () default
References PhaseHalfPiSse().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::PhaseHalfPiSse< NC >::clear_buffers () noexcept
Definition at line 216 of file PhaseHalfPiSse.hpp.
References _filter, _nbr_phases, _nbr_stages, and i.
Referenced by PhaseHalfPiSse(), and operator=().
operator!=()
template<int NC> bool hiir::PhaseHalfPiSse< NC >::operator!= (const PhaseHalfPiSse< NC > & other) private delete
References PhaseHalfPiSse().
operator=() [1/2]
template<int NC> PhaseHalfPiSse< NC > & hiir::PhaseHalfPiSse< NC >::operator= (const PhaseHalfPiSse< NC > & other) default
References PhaseHalfPiSse().
operator=() [2/2]
template<int NC> PhaseHalfPiSse< NC > & hiir::PhaseHalfPiSse< NC >::operator= (PhaseHalfPiSse< NC > && other) default
References PhaseHalfPiSse(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::PhaseHalfPiSse< NC >::operator== (const PhaseHalfPiSse< NC > & other) private delete
References PhaseHalfPiSse().
process_block()
template<int NC> void hiir::PhaseHalfPiSse< NC >::process_block (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 172 of file PhaseHalfPiSse.hpp.
References _phase, pos, process_block_quad(), and process_sample().
Referenced by operator=().
process_block_quad()
template<int NC> long hiir::PhaseHalfPiSse< NC >::process_block_quad (float out_0_ptr[], float out_1_ptr[], const float in_ptr[], long nbr_spl) private noexcept
Definition at line 265 of file PhaseHalfPiSse.hpp.
References _filter, _nbr_stages, _phase, _prev, pos, and hiir::StageProcSseV4< CUR >::process_sample_neg().
Referenced by process_block().
process_sample()
template<int NC> hiir_FORCEINLINE void hiir::PhaseHalfPiSse< NC >::process_sample (float & out_0, float & out_1, float input) noexcept
Definition at line 128 of file PhaseHalfPiSse.hpp.
References _filter, _nbr_stages, _phase, _prev, hiir_FORCEINLINE, and hiir::StageProcSseV4< CUR >::process_sample_neg().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::PhaseHalfPiSse< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 101 of file PhaseHalfPiSse.hpp.
References i, NBR_COEFS, and set_single_coef().
Referenced by operator=().
set_single_coef()
template<int NC> void hiir::PhaseHalfPiSse< NC >::set_single_coef (int index, double coef) inline private noexcept
Definition at line 249 of file PhaseHalfPiSse.hpp.
References _coef_shift, _filter, _nbr_phases, _nbr_stages, _stage_width, and pos.
Referenced by PhaseHalfPiSse(), and set_coefs().
Member Data Documentation
_coef_shift
template<int NC> int hiir::PhaseHalfPiSse< NC >::_coef_shift = ((NBR_COEFS & 1) * 2) ^ 3 static constexpr private
Definition at line 103 of file PhaseHalfPiSse.h.
Referenced by set_single_coef().
_delay
template<int NC> double hiir::PhaseHalfPiSse< NC >::_delay = 2 static constexpr
Definition at line 68 of file PhaseHalfPiSse.h.
_filter
template<int NC> FilterBiPhase hiir::PhaseHalfPiSse< NC >::_filter private
Definition at line 116 of file PhaseHalfPiSse.h.
Referenced by PhaseHalfPiSse(), clear_buffers(), process_block_quad(), process_sample(), and set_single_coef().
_nbr_chn
template<int NC> int hiir::PhaseHalfPiSse< NC >::_nbr_chn = 1 static constexpr
Definition at line 66 of file PhaseHalfPiSse.h.
_nbr_phases
template<int NC> int hiir::PhaseHalfPiSse< NC >::_nbr_phases = 2 static constexpr private
Definition at line 102 of file PhaseHalfPiSse.h.
Referenced by PhaseHalfPiSse(), clear_buffers(), and set_single_coef().
_nbr_stages
template<int NC> int hiir::PhaseHalfPiSse< NC >::_nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width static constexpr private
Definition at line 101 of file PhaseHalfPiSse.h.
Referenced by PhaseHalfPiSse(), clear_buffers(), process_block_quad(), process_sample(), and set_single_coef().
_phase
template<int NC> int hiir::PhaseHalfPiSse< NC >::_phase private
Definition at line 118 of file PhaseHalfPiSse.h.
Referenced by PhaseHalfPiSse(), process_block(), process_block_quad(), and process_sample().
_prev
template<int NC> float hiir::PhaseHalfPiSse< NC >::_prev private
Definition at line 117 of file PhaseHalfPiSse.h.
Referenced by PhaseHalfPiSse(), process_block_quad(), and process_sample().
_stage_width
template<int NC> int hiir::PhaseHalfPiSse< NC >::_stage_width = 4 static constexpr private
Definition at line 100 of file PhaseHalfPiSse.h.
Referenced by PhaseHalfPiSse(), and set_single_coef().
NBR_COEFS
template<int NC> int hiir::PhaseHalfPiSse< NC >::NBR_COEFS = NC static constexpr
Definition at line 67 of file PhaseHalfPiSse.h.
Referenced by PhaseHalfPiSse(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/PhaseHalfPiSse.h
src/3rdparty/hiir/hiir/PhaseHalfPiSse.hpp