LMMS: hiir::HalfBandSse< NC > Class Template Reference
hiir::HalfBandSse< NC > Class Template Reference
#include <HalfBandSse.h>
Public Types
typedef float DataType
Public Member Functions
HalfBandSse () noexcept
HalfBandSse (const HalfBandSse< NC > &other)=default
HalfBandSse (HalfBandSse< NC > &&other)=default
~HalfBandSse ()=default
void clear_buffers () noexcept
HalfBandSse< NC > & operator= (const HalfBandSse< NC > &other)=default
HalfBandSse< NC > & operator= (HalfBandSse< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void process_block_hpf (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE float process_sample (float input) noexcept
hiir_FORCEINLINE float process_sample_hpf (float input) noexcept
hiir_FORCEINLINE void process_sample_split (float &low, float &hi, float input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 2
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataSse, _nbr_stages+1 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const HalfBandSse< NC > &other)=delete
bool operator== (const HalfBandSse< NC > &other)=delete
hiir_FORCEINLINE std::array< float, 2 > process_2_paths (float input) noexcept
template<typename FL, typename FH>
hiir_FORCEINLINE long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void set_single_coef (int index, double coef) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (float *, __m128, __m128, __m128) noexcept
static hiir_FORCEINLINE void store_high (float *ptr, __m128 even, __m128 odd, __m128 half) noexcept
static hiir_FORCEINLINE void store_low (float *ptr, __m128 even, __m128 odd, __m128 half) noexcept
Private Attributes
FilterBiPhase _filter
int _phase
float _prev
Static Private Attributes
static constexpr int _coef_shift = ((NBR_COEFS & 1) * 2) ^ 3
static constexpr int _nbr_phases = 2
static constexpr int _nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width
static constexpr int _stage_width = 4
Detailed Description
template<int NC>
class hiir::HalfBandSse< NC >
Definition at line 51 of file HalfBandSse.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::HalfBandSse< NC >::DataType
Definition at line 60 of file HalfBandSse.h.
Filter
template<int NC> typedef std::array<StageDataSse, _nbr_stages + 1> hiir::HalfBandSse< NC >::Filter private
Definition at line 109 of file HalfBandSse.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::HalfBandSse< NC >::FilterBiPhase private
Definition at line 110 of file HalfBandSse.h.
Constructor & Destructor Documentation
HalfBandSse() [1/3]
template<int NC> hiir::HalfBandSse< NC >::HalfBandSse () noexcept
Definition at line 65 of file HalfBandSse.hpp.
References _filter, _nbr_phases, _nbr_stages, _phase, _prev, _stage_width, clear_buffers(), i, NBR_COEFS, and set_single_coef().
Referenced by HalfBandSse(), HalfBandSse(), ~HalfBandSse(), operator=(), and operator=().
HalfBandSse() [2/3]
template<int NC> hiir::HalfBandSse< NC >::HalfBandSse (const HalfBandSse< NC > & other) default
References HalfBandSse().
HalfBandSse() [3/3]
template<int NC> hiir::HalfBandSse< NC >::HalfBandSse (HalfBandSse< NC > && other) default
References HalfBandSse().
~HalfBandSse()
template<int NC> hiir::HalfBandSse< NC >::~HalfBandSse () default
References HalfBandSse().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::HalfBandSse< NC >::bypass (float * , __m128 , __m128 , __m128) inline static private noexcept
Definition at line 125 of file HalfBandSse.h.
References bypass().
Referenced by bypass(), process_block(), and process_block_hpf().
clear_buffers()
template<int NC> void hiir::HalfBandSse< NC >::clear_buffers () noexcept
Definition at line 344 of file HalfBandSse.hpp.
References _filter, _nbr_phases, _nbr_stages, _phase, _prev, and i.
Referenced by HalfBandSse(), and operator=().
operator!=()
template<int NC> bool hiir::HalfBandSse< NC >::operator!= (const HalfBandSse< NC > & other) private delete
operator=() [1/2]
template<int NC> HalfBandSse< NC > & hiir::HalfBandSse< NC >::operator= (const HalfBandSse< NC > & other) default
References HalfBandSse().
operator=() [2/2]
template<int NC> HalfBandSse< NC > & hiir::HalfBandSse< NC >::operator= (HalfBandSse< NC > && other) default
References HalfBandSse(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_hpf(), process_block_split(), process_sample(), process_sample_hpf(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::HalfBandSse< NC >::operator== (const HalfBandSse< NC > & other) private delete
process_2_paths()
template<int NC> std::array< float, 2 > hiir::HalfBandSse< NC >::process_2_paths (float input) private noexcept
Definition at line 398 of file HalfBandSse.hpp.
References _filter, _nbr_stages, _phase, _prev, and hiir::StageProcSseV4< CUR >::process_sample_pos().
Referenced by process_sample(), process_sample_hpf(), and process_sample_split().
process_block()
template<int NC> void hiir::HalfBandSse< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 153 of file HalfBandSse.hpp.
References _phase, bypass(), pos, process_block_quad(), process_sample(), and store_low().
Referenced by operator=().
process_block_hpf()
template<int NC> void hiir::HalfBandSse< NC >::process_block_hpf (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 222 of file HalfBandSse.hpp.
References _phase, bypass(), pos, process_block_quad(), process_sample_hpf(), and store_high().
Referenced by operator=().
process_block_quad() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE long hiir::HalfBandSse< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE, process_block_quad(), store_high(), and store_low().
Referenced by process_block(), process_block_hpf(), process_block_quad(), and process_block_split().
process_block_quad() [2/2]
template<int NC> template<typename FL, typename FH> long hiir::HalfBandSse< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 429 of file HalfBandSse.hpp.
References _filter, _nbr_stages, _phase, _prev, pos, and hiir::StageProcSseV4< CUR >::process_sample_pos().
process_block_split()
template<int NC> void hiir::HalfBandSse< NC >::process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 299 of file HalfBandSse.hpp.
References _phase, pos, process_block_quad(), process_sample_split(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> float hiir::HalfBandSse< NC >::process_sample (float input) noexcept
Definition at line 127 of file HalfBandSse.hpp.
References process_2_paths().
Referenced by operator=(), and process_block().
process_sample_hpf()
template<int NC> float hiir::HalfBandSse< NC >::process_sample_hpf (float input) noexcept
Definition at line 196 of file HalfBandSse.hpp.
References process_2_paths().
Referenced by operator=(), and process_block_hpf().
process_sample_split()
template<int NC> void hiir::HalfBandSse< NC >::process_sample_split (float & low, float & hi, float input) noexcept
Definition at line 269 of file HalfBandSse.hpp.
References process_2_paths().
Referenced by operator=(), and process_block_split().
set_coefs()
template<int NC> void hiir::HalfBandSse< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 102 of file HalfBandSse.hpp.
References i, NBR_COEFS, and set_single_coef().
Referenced by operator=().
set_single_coef()
template<int NC> void hiir::HalfBandSse< NC >::set_single_coef (int index, double coef) inline private noexcept
Definition at line 380 of file HalfBandSse.hpp.
References _coef_shift, _filter, _nbr_phases, _nbr_stages, _stage_width, and pos.
Referenced by HalfBandSse(), and set_coefs().
store_high()
template<int NC> void hiir::HalfBandSse< NC >::store_high (float * ptr, __m128 even, __m128 odd, __m128 half) static private noexcept
Definition at line 494 of file HalfBandSse.hpp.
Referenced by process_block_hpf(), process_block_quad(), and process_block_split().
store_low()
template<int NC> void hiir::HalfBandSse< NC >::store_low (float * ptr, __m128 even, __m128 odd, __m128 half) static private noexcept
Definition at line 485 of file HalfBandSse.hpp.
Referenced by process_block(), process_block_quad(), and process_block_split().
Member Data Documentation
_coef_shift
template<int NC> int hiir::HalfBandSse< NC >::_coef_shift = ((NBR_COEFS & 1) * 2) ^ 3 static constexpr private
Definition at line 106 of file HalfBandSse.h.
Referenced by set_single_coef().
_delay
template<int NC> double hiir::HalfBandSse< NC >::_delay = 2 static constexpr
Definition at line 63 of file HalfBandSse.h.
_filter
template<int NC> FilterBiPhase hiir::HalfBandSse< NC >::_filter private
Definition at line 129 of file HalfBandSse.h.
Referenced by HalfBandSse(), clear_buffers(), process_2_paths(), process_block_quad(), and set_single_coef().
_nbr_chn
template<int NC> int hiir::HalfBandSse< NC >::_nbr_chn = 1 static constexpr
Definition at line 61 of file HalfBandSse.h.
_nbr_phases
template<int NC> int hiir::HalfBandSse< NC >::_nbr_phases = 2 static constexpr private
Definition at line 105 of file HalfBandSse.h.
Referenced by HalfBandSse(), clear_buffers(), and set_single_coef().
_nbr_stages
template<int NC> int hiir::HalfBandSse< NC >::_nbr_stages = (NBR_COEFS + _stage_width-1) / _stage_width static constexpr private
Definition at line 104 of file HalfBandSse.h.
Referenced by HalfBandSse(), clear_buffers(), process_2_paths(), process_block_quad(), and set_single_coef().
_phase
template<int NC> int hiir::HalfBandSse< NC >::_phase private
Definition at line 131 of file HalfBandSse.h.
Referenced by HalfBandSse(), clear_buffers(), process_2_paths(), process_block(), process_block_hpf(), process_block_quad(), and process_block_split().
_prev
template<int NC> float hiir::HalfBandSse< NC >::_prev private
Definition at line 130 of file HalfBandSse.h.
Referenced by HalfBandSse(), clear_buffers(), process_2_paths(), and process_block_quad().
_stage_width
template<int NC> int hiir::HalfBandSse< NC >::_stage_width = 4 static constexpr private
Definition at line 103 of file HalfBandSse.h.
Referenced by HalfBandSse(), and set_single_coef().
NBR_COEFS
template<int NC> int hiir::HalfBandSse< NC >::NBR_COEFS = NC static constexpr
Definition at line 62 of file HalfBandSse.h.
Referenced by HalfBandSse(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/HalfBandSse.h
src/3rdparty/hiir/hiir/HalfBandSse.hpp