LMMS: lmms::AudioDevice Class Reference
lmms::AudioDevice Class Reference
#include <AudioDevice.h>
Public Member Functions
AudioDevice (const ch_cnt_t _channels, AudioEngine *audioEngine)
virtual ~AudioDevice ()
void lock ()
void processNextBuffer ()
virtual void registerPort (AudioBusHandle *port)
virtual void renamePort (AudioBusHandle *port)
sample_rate_t sampleRate () const
virtual void startProcessing ()
virtual void stopProcessing ()
bool supportsCapture () const
void unlock ()
virtual void unregisterPort (AudioBusHandle *port)
Protected Member Functions
AudioEngine * audioEngine ()
ch_cnt_t channels () const
void clearS16Buffer (int_sample_t *_outbuf, const fpp_t _frames)
int convertToS16 (const SampleFrame *_ab, const fpp_t _frames, int_sample_t *_output_buffer, const bool _convert_endian=false)
fpp_t getNextBuffer (SampleFrame *_ab)
void setSampleRate (const sample_rate_t _new_sr)
virtual void writeBuffer (const SampleFrame *, const fpp_t)
Static Protected Member Functions
static void stopProcessingThread (QThread *thread)
Protected Attributes
bool m_supportsCapture
Private Attributes
AudioEngine * m_audioEngine
SampleFrame * m_buffer
ch_cnt_t m_channels
QMutex m_devMutex
bool m_inProcess
sample_rate_t m_sampleRate
Detailed Description
Definition at line 43 of file AudioDevice.h.
Constructor & Destructor Documentation
AudioDevice()
lmms::AudioDevice::AudioDevice (const ch_cnt_t _channels, AudioEngine * audioEngine)
Definition at line 33 of file AudioDevice.cpp.
References audioEngine(), m_audioEngine, m_buffer, m_channels, m_sampleRate, and m_supportsCapture.
Referenced by lmms::AudioDummy::AudioDummy(), lmms::AudioFileDevice::AudioFileDevice(), and lmms::AudioSampleRecorder::AudioSampleRecorder().
~AudioDevice()
lmms::AudioDevice::~AudioDevice () virtual
Definition at line 45 of file AudioDevice.cpp.
References m_buffer, m_devMutex, and unlock().
Member Function Documentation
audioEngine()
AudioEngine * lmms::AudioDevice::audioEngine () inline protected
Definition at line 116 of file AudioDevice.h.
References m_audioEngine.
Referenced by AudioDevice(), lmms::AudioDummy::AudioDummy(), lmms::AudioFileFlac::AudioFileFlac(), lmms::AudioFileWave::AudioFileWave(), lmms::AudioFileFlac::getInst(), lmms::AudioFileWave::getInst(), getNextBuffer(), lmms::AudioDummy::run(), lmms::AudioFileFlac::startEncoding(), lmms::AudioFileWave::startEncoding(), and stopProcessing().
channels()
ch_cnt_t lmms::AudioDevice::channels () const inline protected
Definition at line 106 of file AudioDevice.h.
References m_channels.
Referenced by lmms::AudioFileFlac::AudioFileFlac(), lmms::AudioFileWave::AudioFileWave(), clearS16Buffer(), convertToS16(), lmms::AudioFileFlac::getInst(), lmms::AudioFileWave::getInst(), lmms::AudioFileFlac::startEncoding(), lmms::AudioFileWave::startEncoding(), lmms::AudioFileFlac::writeBuffer(), and lmms::AudioFileWave::writeBuffer().
clearS16Buffer()
void lmms::AudioDevice::clearS16Buffer (int_sample_t * _outbuf, const fpp_t _frames) protected
Definition at line 165 of file AudioDevice.cpp.
References lmms::BYTES_PER_INT_SAMPLE, and channels().
convertToS16()
int lmms::AudioDevice::convertToS16 (const SampleFrame * _ab, const fpp_t _frames, int_sample_t * _output_buffer, const bool _convert_endian = false) protected
Definition at line 128 of file AudioDevice.cpp.
References lmms::BYTES_PER_INT_SAMPLE, channels(), lmms::AudioEngine::clip(), and lmms::OUTPUT_SAMPLE_MULTIPLIER.
Referenced by lmms::AudioFileFlac::writeBuffer(), and lmms::AudioFileWave::writeBuffer().
getNextBuffer()
fpp_t lmms::AudioDevice::getNextBuffer (SampleFrame * _ab) protected
Definition at line 65 of file AudioDevice.cpp.
References audioEngine(), lmms::AudioEngine::framesPerPeriod(), and lmms::AudioEngine::nextBuffer().
Referenced by processNextBuffer().
lock()
void lmms::AudioDevice::lock () inline
Definition at line 49 of file AudioDevice.h.
References m_devMutex.
processNextBuffer()
void lmms::AudioDevice::processNextBuffer ()
Definition at line 55 of file AudioDevice.cpp.
References getNextBuffer(), m_buffer, m_inProcess, and writeBuffer().
Referenced by stopProcessing().
registerPort()
void lmms::AudioDevice::registerPort (AudioBusHandle * port) virtual
Definition at line 110 of file AudioDevice.cpp.
Referenced by lmms::AudioBusHandle::setExtOutputEnabled().
renamePort()
void lmms::AudioDevice::renamePort (AudioBusHandle * port) virtual
Definition at line 124 of file AudioDevice.cpp.
Referenced by lmms::AudioBusHandle::setName().
sampleRate()
sample_rate_t lmms::AudioDevice::sampleRate () const inline
Definition at line 73 of file AudioDevice.h.
References m_sampleRate.
Referenced by lmms::AudioSampleRecorder::createSampleBuffer(), lmms::AudioFileFlac::startEncoding(), and lmms::AudioFileWave::startEncoding().
setSampleRate()
void lmms::AudioDevice::setSampleRate (const sample_rate_t _new_sr) inline protected
Definition at line 111 of file AudioDevice.h.
References m_sampleRate.
Referenced by lmms::AudioFileDevice::AudioFileDevice().
startProcessing()
virtual void lmms::AudioDevice::startProcessing () inline virtual
Reimplemented in lmms::AudioDummy.
Definition at line 80 of file AudioDevice.h.
References m_inProcess.
stopProcessing()
void lmms::AudioDevice::stopProcessing () virtual
Reimplemented in lmms::AudioDummy.
Definition at line 81 of file AudioDevice.cpp.
References audioEngine(), m_inProcess, and processNextBuffer().
stopProcessingThread()
void lmms::AudioDevice::stopProcessingThread (QThread * thread) static protected
Definition at line 95 of file AudioDevice.cpp.
Referenced by lmms::AudioDummy::stopProcessing().
supportsCapture()
bool lmms::AudioDevice::supportsCapture () const inline
Definition at line 68 of file AudioDevice.h.
References m_supportsCapture.
unlock()
void lmms::AudioDevice::unlock () inline
Definition at line 54 of file AudioDevice.h.
References m_devMutex.
Referenced by ~AudioDevice().
unregisterPort()
void lmms::AudioDevice::unregisterPort (AudioBusHandle * port) virtual
Definition at line 117 of file AudioDevice.cpp.
Referenced by lmms::AudioBusHandle::setExtOutputEnabled().
writeBuffer()
virtual void lmms::AudioDevice::writeBuffer (const SampleFrame * , const fpp_t) inline protected virtual
Reimplemented in lmms::AudioFileFlac, lmms::AudioFileWave, and lmms::AudioSampleRecorder.
Definition at line 90 of file AudioDevice.h.
Referenced by processNextBuffer().
Member Data Documentation
m_audioEngine
AudioEngine* lmms::AudioDevice::m_audioEngine private
Definition at line 131 of file AudioDevice.h.
Referenced by AudioDevice(), and audioEngine().
m_buffer
SampleFrame* lmms::AudioDevice::m_buffer private
Definition at line 136 of file AudioDevice.h.
Referenced by AudioDevice(), ~AudioDevice(), and processNextBuffer().
m_channels
ch_cnt_t lmms::AudioDevice::m_channels private
Definition at line 130 of file AudioDevice.h.
Referenced by AudioDevice(), and channels().
m_devMutex
QMutex lmms::AudioDevice::m_devMutex private
Definition at line 134 of file AudioDevice.h.
Referenced by ~AudioDevice(), lock(), and unlock().
m_inProcess
bool lmms::AudioDevice::m_inProcess private
Definition at line 132 of file AudioDevice.h.
Referenced by processNextBuffer(), startProcessing(), and stopProcessing().
m_sampleRate
sample_rate_t lmms::AudioDevice::m_sampleRate private
Definition at line 129 of file AudioDevice.h.
Referenced by AudioDevice(), sampleRate(), and setSampleRate().
m_supportsCapture
bool lmms::AudioDevice::m_supportsCapture protected
Definition at line 125 of file AudioDevice.h.
Referenced by AudioDevice(), and supportsCapture().
The documentation for this class was generated from the following files:
include/AudioDevice.h
src/core/audio/AudioDevice.cpp