LMMS: hiir::HalfBand8Avx< NC > Class Template Reference
hiir::HalfBand8Avx< NC > Class Template Reference
#include <HalfBand8Avx.h>
Classes
struct EvenOdd
Public Types
typedef float DataType
Public Member Functions
HalfBand8Avx () noexcept
HalfBand8Avx (const HalfBand8Avx< NC > &other)=default
HalfBand8Avx (HalfBand8Avx< NC > &&other)=default
~HalfBand8Avx ()=default
void clear_buffers () noexcept
HalfBand8Avx< NC > & operator= (const HalfBand8Avx< NC > &other)=default
HalfBand8Avx< NC > & operator= (HalfBand8Avx< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
void process_block_2_paths (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_hpf (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE __m256 process_sample (__m256 input) noexcept
hiir_FORCEINLINE __m256 process_sample_hpf (__m256 input) noexcept
hiir_FORCEINLINE void process_sample_split (__m256 &low, __m256 &high, __m256 input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 8
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataAvx, NBR_COEFS+2 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const HalfBand8Avx &other) const =delete
bool operator== (const HalfBand8Avx &other) const =delete
hiir_FORCEINLINE EvenOdd process_2_paths (__m256 input) noexcept
template<typename FL, typename FH>
hiir_FORCEINLINE void process_block_2_paths (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (float *, __m256, __m256) noexcept
static hiir_FORCEINLINE void store_high (float *ptr, __m256 tmp_0, __m256 tmp_1) noexcept
static hiir_FORCEINLINE void store_low (float *ptr, __m256 tmp_0, __m256 tmp_1) noexcept
Private Attributes
FilterBiPhase _bifilter
int _phase
float _prev [_nbr_chn]
Static Private Attributes
static constexpr int _nbr_phases = 2
Detailed Description
template<int NC>
class hiir::HalfBand8Avx< NC >
Definition at line 49 of file HalfBand8Avx.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::HalfBand8Avx< NC >::DataType
Definition at line 58 of file HalfBand8Avx.h.
Filter
template<int NC> typedef std::array<StageDataAvx, NBR_COEFS + 2> hiir::HalfBand8Avx< NC >::Filter private
Definition at line 103 of file HalfBand8Avx.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::HalfBand8Avx< NC >::FilterBiPhase private
Definition at line 105 of file HalfBand8Avx.h.
Constructor & Destructor Documentation
HalfBand8Avx() [1/3]
template<int NC> hiir::HalfBand8Avx< NC >::HalfBand8Avx () noexcept
Definition at line 57 of file HalfBand8Avx.hpp.
References _bifilter, _phase, clear_buffers(), i, and NBR_COEFS.
Referenced by HalfBand8Avx(), HalfBand8Avx(), ~HalfBand8Avx(), operator!=(), operator=(), operator=(), and operator==().
HalfBand8Avx() [2/3]
template<int NC> hiir::HalfBand8Avx< NC >::HalfBand8Avx (const HalfBand8Avx< NC > & other) default
References HalfBand8Avx().
HalfBand8Avx() [3/3]
template<int NC> hiir::HalfBand8Avx< NC >::HalfBand8Avx (HalfBand8Avx< NC > && other) default
References HalfBand8Avx().
~HalfBand8Avx()
template<int NC> hiir::HalfBand8Avx< NC >::~HalfBand8Avx () default
References HalfBand8Avx().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::HalfBand8Avx< NC >::bypass (float * , __m256 , __m256) inline static private noexcept
Definition at line 124 of file HalfBand8Avx.h.
Referenced by process_block(), and process_block_hpf().
clear_buffers()
template<int NC> void hiir::HalfBand8Avx< NC >::clear_buffers () noexcept
Definition at line 278 of file HalfBand8Avx.hpp.
References _bifilter, _phase, _prev, i, and NBR_COEFS.
Referenced by HalfBand8Avx(), and operator=().
operator!=()
template<int NC> bool hiir::HalfBand8Avx< NC >::operator!= (const HalfBand8Avx< NC > & other) const private delete
References HalfBand8Avx().
operator=() [1/2]
template<int NC> HalfBand8Avx< NC > & hiir::HalfBand8Avx< NC >::operator= (const HalfBand8Avx< NC > & other) default
References HalfBand8Avx().
operator=() [2/2]
template<int NC> HalfBand8Avx< NC > & hiir::HalfBand8Avx< NC >::operator= (HalfBand8Avx< NC > && other) default
References HalfBand8Avx(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_hpf(), process_block_split(), process_sample(), process_sample_hpf(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::HalfBand8Avx< NC >::operator== (const HalfBand8Avx< NC > & other) const private delete
References HalfBand8Avx().
process_2_paths()
template<int NC> HalfBand8Avx< NC >::EvenOdd hiir::HalfBand8Avx< NC >::process_2_paths (__m256 input) private noexcept
Definition at line 307 of file HalfBand8Avx.hpp.
References _bifilter, _phase, _prev, NBR_COEFS, and hiir::StageProc8Avx< REMAINING >::process_sample_pos().
Referenced by process_block_2_paths(), process_sample(), process_sample_hpf(), and process_sample_split().
process_block()
template<int NC> void hiir::HalfBand8Avx< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 140 of file HalfBand8Avx.hpp.
References _nbr_chn, bypass(), process_block_2_paths(), and store_low().
Referenced by operator=().
process_block_2_paths() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE void hiir::HalfBand8Avx< NC >::process_block_2_paths (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE.
Referenced by process_block(), process_block_hpf(), and process_block_split().
process_block_2_paths() [2/2]
template<int NC> template<typename FL, typename FH> void hiir::HalfBand8Avx< NC >::process_block_2_paths (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 329 of file HalfBand8Avx.hpp.
References _bifilter, _nbr_chn, _nbr_phases, _phase, _prev, NBR_COEFS, pos, process_2_paths(), and hiir::StageProc8Avx< REMAINING >::process_sample_pos().
process_block_hpf()
template<int NC> void hiir::HalfBand8Avx< NC >::process_block_hpf (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 192 of file HalfBand8Avx.hpp.
References _nbr_chn, bypass(), process_block_2_paths(), and store_high().
Referenced by operator=().
process_block_split()
template<int NC> void hiir::HalfBand8Avx< NC >::process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 251 of file HalfBand8Avx.hpp.
References _nbr_chn, process_block_2_paths(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> __m256 hiir::HalfBand8Avx< NC >::process_sample (__m256 input) noexcept
Definition at line 114 of file HalfBand8Avx.hpp.
References process_2_paths().
Referenced by operator=().
process_sample_hpf()
template<int NC> __m256 hiir::HalfBand8Avx< NC >::process_sample_hpf (__m256 input) noexcept
Definition at line 165 of file HalfBand8Avx.hpp.
References process_2_paths().
Referenced by operator=().
process_sample_split()
template<int NC> void hiir::HalfBand8Avx< NC >::process_sample_split (__m256 & low, __m256 & high, __m256 input) noexcept
Definition at line 221 of file HalfBand8Avx.hpp.
References process_2_paths().
Referenced by operator=().
set_coefs()
template<int NC> void hiir::HalfBand8Avx< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 87 of file HalfBand8Avx.hpp.
References _bifilter, i, and NBR_COEFS.
Referenced by operator=().
store_high()
template<int NC> void hiir::HalfBand8Avx< NC >::store_high (float * ptr, __m256 tmp_0, __m256 tmp_1) static private noexcept
Definition at line 401 of file HalfBand8Avx.hpp.
Referenced by process_block_hpf(), and process_block_split().
store_low()
template<int NC> void hiir::HalfBand8Avx< NC >::store_low (float * ptr, __m256 tmp_0, __m256 tmp_1) static private noexcept
Definition at line 392 of file HalfBand8Avx.hpp.
Referenced by process_block(), and process_block_split().
Member Data Documentation
_bifilter
template<int NC> FilterBiPhase hiir::HalfBand8Avx< NC >::_bifilter private
Definition at line 126 of file HalfBand8Avx.h.
Referenced by HalfBand8Avx(), clear_buffers(), process_2_paths(), process_block_2_paths(), and set_coefs().
_delay
template<int NC> double hiir::HalfBand8Avx< NC >::_delay = 0 static constexpr
Definition at line 61 of file HalfBand8Avx.h.
_nbr_chn
template<int NC> int hiir::HalfBand8Avx< NC >::_nbr_chn = 8 static constexpr
Definition at line 59 of file HalfBand8Avx.h.
Referenced by process_block(), process_block_2_paths(), process_block_hpf(), and process_block_split().
_nbr_phases
template<int NC> int hiir::HalfBand8Avx< NC >::_nbr_phases = 2 static constexpr private
Definition at line 101 of file HalfBand8Avx.h.
Referenced by process_block_2_paths().
_phase
template<int NC> int hiir::HalfBand8Avx< NC >::_phase private
Definition at line 129 of file HalfBand8Avx.h.
Referenced by HalfBand8Avx(), clear_buffers(), process_2_paths(), and process_block_2_paths().
_prev
template<int NC> float hiir::HalfBand8Avx< NC >::_prev[_nbr_chn] private
Definition at line 128 of file HalfBand8Avx.h.
Referenced by clear_buffers(), process_2_paths(), and process_block_2_paths().
NBR_COEFS
template<int NC> int hiir::HalfBand8Avx< NC >::NBR_COEFS = NC static constexpr
Definition at line 60 of file HalfBand8Avx.h.
Referenced by HalfBand8Avx(), clear_buffers(), process_2_paths(), process_block_2_paths(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/HalfBand8Avx.h
src/3rdparty/hiir/hiir/HalfBand8Avx.hpp