LMMS: src/3rdparty/jack2/tests/testMutex.cpp File Reference
testMutex.cpp File Reference
#include <stdio.h>
#include <sys/time.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "JackPosixThread.h"
#include "JackMutex.h"
#include "thread.h"
Classes
struct LockedObject
struct TestThread
Base class for reader/writer threads.
struct TestThread1
Functions
static void CleanupHandler (void *arg)
int main (int argc, char *const argv[])
static void * TestThread1_Execute (void *arg)
Function Documentation
CleanupHandler()
void CleanupHandler (void * arg) static
Definition at line 36 of file testMutex.cpp.
References Jack::JackLockAble::Unlock().
Referenced by LockedObject::LockedMethod1(), LockedObject::LockedMethod2(), and LockedObject::LockedMethod3().
main()
int main (int argc, char *const argv[])
Definition at line 269 of file testMutex.cpp.
References TestThread::fThread, and Jack::JackPosixThread::Kill().
TestThread1_Execute()
void * TestThread1_Execute (void * arg) static
Definition at line 242 of file testMutex.cpp.
References TestThread1::fNum, TestThread1::fObject, LockedObject::LockedMethod1(), LockedObject::LockedMethod2(), and LockedObject::LockedMethod3().
Referenced by TestThread1::TestThread1().