LMMS: lmms::gui::SetupDialog Class Reference
lmms::gui::SetupDialog Class Reference
#include <SetupDialog.h>
Public Types
enum class ConfigTab {
GeneralSettings ,
PerformanceSettings ,
AudioSettings ,
MidiSettings ,
PathsSettings
}
Public Member Functions
SetupDialog (ConfigTab tab_to_open=ConfigTab::GeneralSettings)
~SetupDialog () override
Protected Slots
void accept () override
Private Types
using AswMap = QMap<QString, AudioDeviceSetupWidget*>
using MswMap = QMap<QString, MidiSetupWidget*>
using trMap = QMap<QString, QString>
Private Slots
void audioInterfaceChanged (const QString &driver)
void loopMarkerModeChanged ()
void midiInterfaceChanged (const QString &driver)
void openBackgroundPicFile ()
void openGIGDir ()
void openLADSPADir ()
void openSF2Dir ()
void openSF2File ()
void openThemeDir ()
void openVSTDir ()
void openWorkingDir ()
void resetAutoSave ()
void resetBufferSize ()
void setAutoSaveInterval (int time)
void setBackgroundPicFile (const QString &backgroundPicFile)
void setBufferSize (int value)
void setGIGDir (const QString &gigDir)
void setLADSPADir (const QString &ladspaDir)
void setLanguage (int lang)
void setSF2Dir (const QString &sf2Dir)
void setSF2File (const QString &sf2File)
void setThemeDir (const QString &themeDir)
void setVSTDir (const QString &vstDir)
void setWorkingDir (const QString &workingDir)
void showRestartWarning ()
void toggleAnimateAFP (bool enabled)
void toggleAutoSave (bool enabled)
void toggleCompactTrackButtons (bool enabled)
void toggleDisableAutoQuit (bool enabled)
void toggleDisableBackup (bool enabled)
void toggleDisplayWaveform (bool enabled)
void toggleLetPreviewsFinish (bool enabled)
void toggleMidiAutoQuantization (bool enabled)
void toggleMixerChannelDeletionWarning (bool enabled)
void toggleMMPZ (bool enabled)
void toggleNoteLabels (bool enabled)
void toggleOneInstrumentTrackWindow (bool enabled)
void toggleOpenLastProject (bool enabled)
void toggleRunningAutoSave (bool enabled)
void toggleShowFaderTicks (bool enabled)
void toggleSideBarOnRight (bool enabled)
void toggleSmoothScroll (bool enabled)
void toggleSoloLegacyBehavior (bool enabled)
void toggleTooltips (bool enabled)
void toggleTrackDeletionWarning (bool enabled)
void toggleVSTAlwaysOnTop (bool en)
void updateBufferSizeWarning (int value)
void vstEmbedMethodChanged ()
Private Attributes
bool m_animateAFP
QComboBox * m_assignableMidiDevices
trMap m_audioIfaceNames
AswMap m_audioIfaceSetupWidgets
QComboBox * m_audioInterfaces
QCheckBox * m_autoSave
QString m_backgroundPicFile
QLineEdit * m_backgroundPicFileLineEdit
int m_bufferSize
QLabel * m_bufferSizeLbl
QSlider * m_bufferSizeSlider
QLabel * m_bufferSizeWarnLbl
bool m_compactTrackButtons
bool m_disableAutoQuit
bool m_disableBackup
bool m_displayWaveform
bool m_enableAutoSave
bool m_enableRunningAutoSave
QString m_gigDir
QLineEdit * m_gigDirLineEdit
QString m_ladspaDir
QLineEdit * m_ladspaDirLineEdit
QString m_lang
QStringList m_languages
bool m_letPreviewsFinish
QComboBox * m_loopMarkerComboBox
QString m_loopMarkerMode
bool m_midiAutoQuantize
trMap m_midiIfaceNames
MswMap m_midiIfaceSetupWidgets
QComboBox * m_midiInterfaces
bool m_mixerChannelDeletionWarning
bool m_MMPZ
bool m_NaNHandler
bool m_oneInstrumentTrackWindow
bool m_openLastProject
bool m_printNoteLabels
QCheckBox * m_runningAutoSave
int m_sampleRate
QSlider * m_sampleRateSlider
int m_saveInterval
QLabel * m_saveIntervalLbl
QSlider * m_saveIntervalSlider
QString m_sf2Dir
QLineEdit * m_sf2DirLineEdit
bool m_showFaderTicks
bool m_sideBarOnRight
bool m_smoothScroll
bool m_soloLegacyBehavior
TabBar * m_tabBar
QString m_themeDir
QLineEdit * m_themeDirLineEdit
bool m_tooltips
bool m_trackDeletionWarning
bool m_vstAlwaysOnTop
QCheckBox * m_vstAlwaysOnTopCheckBox
QString m_vstDir
QLineEdit * m_vstDirLineEdit
QComboBox * m_vstEmbedComboBox
QLabel * m_vstEmbedLbl
QString m_vstEmbedMethod
QString m_workingDir
QLineEdit * m_workingDirLineEdit
QLabel * restartWarningLbl
Detailed Description
Definition at line 50 of file SetupDialog.h.
Member Typedef Documentation
AswMap
using lmms::gui::SetupDialog::AswMap = QMap<QString, AudioDeviceSetupWidget*> private
Definition at line 172 of file SetupDialog.h.
MswMap
using lmms::gui::SetupDialog::MswMap = QMap<QString, MidiSetupWidget*> private
Definition at line 173 of file SetupDialog.h.
trMap
using lmms::gui::SetupDialog::trMap = QMap<QString, QString> private
Definition at line 174 of file SetupDialog.h.
Member Enumeration Documentation
ConfigTab
enum class lmms::gui::SetupDialog::ConfigTab strong
Enumerator
GeneralSettings
PerformanceSettings
AudioSettings
MidiSettings
PathsSettings
Definition at line 55 of file SetupDialog.h.
Constructor & Destructor Documentation
SetupDialog()
lmms::gui::SetupDialog::SetupDialog (ConfigTab tab_to_open = ConfigTab::GeneralSettings)
Definition at line 92 of file SetupDialog.cpp.
References accept(), activated, lmms::AudioEngine::audioDevName(), lmms::Engine::audioEngine(), audioInterfaceChanged(), lmms::ConfigManager::availableVstEmbedMethods(), lmms::gui::BUFFERSIZE_RESOLUTION, lmms::gui::MidiSetupWidget::create(), lmms::embed::getIconPixmap(), i, lmms::ConfigManager::inst(), lmms::gui::labelWidget(), loopMarkerModeChanged(), m_animateAFP, m_assignableMidiDevices, m_audioIfaceNames, m_audioIfaceSetupWidgets, m_audioInterfaces, m_autoSave, m_backgroundPicFile, m_backgroundPicFileLineEdit, m_bufferSize, m_bufferSizeLbl, m_bufferSizeSlider, m_bufferSizeWarnLbl, m_compactTrackButtons, m_disableAutoQuit, m_disableBackup, m_displayWaveform, m_enableAutoSave, m_enableRunningAutoSave, m_gigDir, m_gigDirLineEdit, m_ladspaDir, m_ladspaDirLineEdit, m_lang, m_languages, m_letPreviewsFinish, m_loopMarkerComboBox, m_loopMarkerMode, m_midiAutoQuantize, m_midiIfaceNames, m_midiIfaceSetupWidgets, m_midiInterfaces, m_mixerChannelDeletionWarning, m_MMPZ, m_NaNHandler, m_oneInstrumentTrackWindow, m_openLastProject, m_printNoteLabels, m_runningAutoSave, m_sampleRate, m_sampleRateSlider, m_saveInterval, m_saveIntervalLbl, m_saveIntervalSlider, m_sf2Dir, m_sf2DirLineEdit, m_showFaderTicks, m_sideBarOnRight, m_smoothScroll, m_soloLegacyBehavior, m_tabBar, m_themeDir, m_themeDirLineEdit, m_tooltips, m_trackDeletionWarning, m_vstAlwaysOnTop, m_vstAlwaysOnTopCheckBox, m_vstDir, m_vstDirLineEdit, m_vstEmbedComboBox, m_vstEmbedLbl, m_vstEmbedMethod, m_workingDir, m_workingDirLineEdit, lmms::MAXIMUM_BUFFER_SIZE, lmms::AudioEngine::midiClientName(), midiInterfaceChanged(), lmms::AudioDummy::name(), lmms::MidiDummy::name(), openBackgroundPicFile(), openGIGDir(), openLADSPADir(), openSF2Dir(), openSF2File(), openThemeDir(), openVSTDir(), openWorkingDir(), lmms::Engine::projectJournal(), resetAutoSave(), resetBufferSize(), restartWarningLbl, setAutoSaveInterval(), setBackgroundPicFile(), setBufferSize(), setGIGDir(), lmms::ProjectJournal::setJournalling(), setLADSPADir(), setLanguage(), setSF2Dir(), setSF2File(), setThemeDir(), lmms::ConfigManager::setValue(), setVSTDir(), setWorkingDir(), showRestartWarning(), lmms::SUPPORTED_SAMPLERATES, toggleAnimateAFP(), toggleAutoSave(), toggleCompactTrackButtons(), toggleDisableAutoQuit(), toggleDisableBackup(), toggleDisplayWaveform(), toggleLetPreviewsFinish(), toggleMidiAutoQuantization(), toggleMixerChannelDeletionWarning(), toggleMMPZ(), toggleNoteLabels(), toggleOneInstrumentTrackWindow(), toggleOpenLastProject(), toggleRunningAutoSave(), toggleShowFaderTicks(), toggleSideBarOnRight(), toggleSmoothScroll(), toggleSoloLegacyBehavior(), toggleTooltips(), toggleTrackDeletionWarning(), toggleVSTAlwaysOnTop(), lmms::ConfigManager::value(), and vstEmbedMethodChanged().
~SetupDialog()
lmms::gui::SetupDialog::~SetupDialog () override
Definition at line 941 of file SetupDialog.cpp.
References lmms::Engine::projectJournal(), and lmms::ProjectJournal::setJournalling().
Member Function Documentation
accept
void lmms::gui::SetupDialog::accept () override protected slot
Definition at line 949 of file SetupDialog.cpp.
References lmms::ConfigManager::inst(), m_animateAFP, m_assignableMidiDevices, m_audioIfaceNames, m_audioIfaceSetupWidgets, m_audioInterfaces, m_backgroundPicFile, m_bufferSize, m_compactTrackButtons, m_disableAutoQuit, m_disableBackup, m_displayWaveform, m_enableAutoSave, m_enableRunningAutoSave, m_gigDir, m_ladspaDir, m_lang, m_letPreviewsFinish, m_loopMarkerMode, m_midiAutoQuantize, m_midiIfaceNames, m_midiIfaceSetupWidgets, m_midiInterfaces, m_mixerChannelDeletionWarning, m_MMPZ, m_NaNHandler, m_oneInstrumentTrackWindow, m_openLastProject, m_printNoteLabels, m_sampleRate, m_saveInterval, m_sf2Dir, m_showFaderTicks, m_sideBarOnRight, m_smoothScroll, m_soloLegacyBehavior, m_themeDir, m_tooltips, m_trackDeletionWarning, m_vstAlwaysOnTop, m_vstDir, m_vstEmbedComboBox, m_workingDir, lmms::ConfigManager::saveConfigFile(), lmms::ConfigManager::setBackgroundPicFile(), lmms::ConfigManager::setGIGDir(), lmms::ConfigManager::setLADSPADir(), lmms::ConfigManager::setSF2Dir(), lmms::ConfigManager::setSF2File(), lmms::ConfigManager::setThemeDir(), lmms::ConfigManager::setValue(), lmms::ConfigManager::setVSTDir(), and lmms::ConfigManager::setWorkingDir().
Referenced by SetupDialog().
audioInterfaceChanged
void lmms::gui::SetupDialog::audioInterfaceChanged (const QString & driver) private slot
Definition at line 1208 of file SetupDialog.cpp.
References m_audioIfaceNames, and m_audioIfaceSetupWidgets.
Referenced by SetupDialog().
loopMarkerModeChanged
void lmms::gui::SetupDialog::loopMarkerModeChanged () private slot
Definition at line 1123 of file SetupDialog.cpp.
References m_loopMarkerComboBox, and m_loopMarkerMode.
Referenced by SetupDialog().
midiInterfaceChanged
void lmms::gui::SetupDialog::midiInterfaceChanged (const QString & driver) private slot
Definition at line 1279 of file SetupDialog.cpp.
References m_midiIfaceNames, and m_midiIfaceSetupWidgets.
Referenced by SetupDialog().
openBackgroundPicFile
void lmms::gui::SetupDialog::openBackgroundPicFile () private slot
Definition at line 1430 of file SetupDialog.cpp.
References lmms::gui::FileDialog::getOpenFileName(), i, m_backgroundPicFile, m_backgroundPicFileLineEdit, and m_themeDir.
Referenced by SetupDialog().
openGIGDir
void lmms::gui::SetupDialog::openGIGDir () private slot
Definition at line 1396 of file SetupDialog.cpp.
References lmms::gui::FileDialog::getExistingDirectory(), m_gigDir, and m_gigDirLineEdit.
Referenced by SetupDialog().
openLADSPADir
void lmms::gui::SetupDialog::openLADSPADir () private slot
Definition at line 1332 of file SetupDialog.cpp.
References lmms::gui::FileDialog::getExistingDirectory(), m_ladspaDir, and m_ladspaDirLineEdit.
Referenced by SetupDialog().
openSF2Dir
void lmms::gui::SetupDialog::openSF2Dir () private slot
Definition at line 1357 of file SetupDialog.cpp.
References lmms::gui::FileDialog::getExistingDirectory(), m_sf2Dir, and m_sf2DirLineEdit.
Referenced by SetupDialog().
openSF2File
void lmms::gui::SetupDialog::openSF2File () private slot
Definition at line 1374 of file SetupDialog.cpp.
References lmms::gui::FileDialog::getOpenFileName().
Referenced by SetupDialog().
openThemeDir
void lmms::gui::SetupDialog::openThemeDir () private slot
Definition at line 1413 of file SetupDialog.cpp.
References lmms::gui::FileDialog::getExistingDirectory(), m_themeDir, and m_themeDirLineEdit.
Referenced by SetupDialog().
openVSTDir
void lmms::gui::SetupDialog::openVSTDir () private slot
Definition at line 1315 of file SetupDialog.cpp.
References lmms::gui::FileDialog::getExistingDirectory(), m_vstDir, and m_vstDirLineEdit.
Referenced by SetupDialog().
openWorkingDir
void lmms::gui::SetupDialog::openWorkingDir () private slot
Definition at line 1298 of file SetupDialog.cpp.
References lmms::gui::FileDialog::getExistingDirectory(), m_workingDir, and m_workingDirLineEdit.
Referenced by SetupDialog().
resetAutoSave
void lmms::gui::SetupDialog::resetAutoSave () private slot
Definition at line 1170 of file SetupDialog.cpp.
References lmms::gui::MainWindow::DEFAULT_SAVE_INTERVAL_MINUTES, m_autoSave, m_runningAutoSave, and setAutoSaveInterval().
Referenced by SetupDialog().
resetBufferSize
void lmms::gui::SetupDialog::resetBufferSize () private slot
Definition at line 1271 of file SetupDialog.cpp.
References lmms::gui::BUFFERSIZE_RESOLUTION, lmms::DEFAULT_BUFFER_SIZE, and setBufferSize().
Referenced by SetupDialog().
setAutoSaveInterval
void lmms::gui::SetupDialog::setAutoSaveInterval (int time) private slot
Definition at line 1143 of file SetupDialog.cpp.
References m_enableAutoSave, m_saveInterval, m_saveIntervalLbl, and m_saveIntervalSlider.
Referenced by SetupDialog(), resetAutoSave(), and toggleAutoSave().
setBackgroundPicFile
void lmms::gui::SetupDialog::setBackgroundPicFile (const QString & backgroundPicFile) private slot
Definition at line 1459 of file SetupDialog.cpp.
References m_backgroundPicFile.
Referenced by SetupDialog().
setBufferSize
void lmms::gui::SetupDialog::setBufferSize (int value) private slot
Definition at line 1242 of file SetupDialog.cpp.
References lmms::Engine::audioEngine(), lmms::gui::BUFFERSIZE_RESOLUTION, lmms::DEFAULT_BUFFER_SIZE, m_bufferSize, m_bufferSizeLbl, m_bufferSizeSlider, and updateBufferSizeWarning().
Referenced by SetupDialog(), and resetBufferSize().
setGIGDir
void lmms::gui::SetupDialog::setGIGDir (const QString & gigDir) private slot
Definition at line 1407 of file SetupDialog.cpp.
References m_gigDir.
Referenced by SetupDialog().
setLADSPADir
void lmms::gui::SetupDialog::setLADSPADir (const QString & ladspaDir) private slot
Definition at line 1351 of file SetupDialog.cpp.
References m_ladspaDir.
Referenced by SetupDialog().
setLanguage
void lmms::gui::SetupDialog::setLanguage (int lang) private slot
Definition at line 1129 of file SetupDialog.cpp.
References m_lang, and m_languages.
Referenced by SetupDialog().
setSF2Dir
void lmms::gui::SetupDialog::setSF2Dir (const QString & sf2Dir) private slot
Definition at line 1368 of file SetupDialog.cpp.
References m_sf2Dir.
Referenced by SetupDialog().
setSF2File
void lmms::gui::SetupDialog::setSF2File (const QString & sf2File) private slot
Definition at line 1388 of file SetupDialog.cpp.
Referenced by SetupDialog().
setThemeDir
void lmms::gui::SetupDialog::setThemeDir (const QString & themeDir) private slot
Definition at line 1424 of file SetupDialog.cpp.
References m_themeDir.
Referenced by SetupDialog().
setVSTDir
void lmms::gui::SetupDialog::setVSTDir (const QString & vstDir) private slot
Definition at line 1326 of file SetupDialog.cpp.
References m_vstDir.
Referenced by SetupDialog().
setWorkingDir
void lmms::gui::SetupDialog::setWorkingDir (const QString & workingDir) private slot
Definition at line 1309 of file SetupDialog.cpp.
References m_workingDir.
Referenced by SetupDialog().
showRestartWarning
void lmms::gui::SetupDialog::showRestartWarning () private slot
Definition at line 1467 of file SetupDialog.cpp.
References restartWarningLbl.
Referenced by SetupDialog().
toggleAnimateAFP
void lmms::gui::SetupDialog::toggleAnimateAFP (bool enabled) private slot
Definition at line 1184 of file SetupDialog.cpp.
References m_animateAFP.
Referenced by SetupDialog().
toggleAutoSave
void lmms::gui::SetupDialog::toggleAutoSave (bool enabled) private slot
Definition at line 1155 of file SetupDialog.cpp.
References m_enableAutoSave, m_runningAutoSave, m_saveIntervalSlider, and setAutoSaveInterval().
Referenced by SetupDialog().
toggleCompactTrackButtons
void lmms::gui::SetupDialog::toggleCompactTrackButtons (bool enabled) private slot
Definition at line 1070 of file SetupDialog.cpp.
References m_compactTrackButtons.
Referenced by SetupDialog().
toggleDisableAutoQuit
void lmms::gui::SetupDialog::toggleDisableAutoQuit (bool enabled) private slot
Definition at line 1203 of file SetupDialog.cpp.
References m_disableAutoQuit.
Referenced by SetupDialog().
toggleDisableBackup
void lmms::gui::SetupDialog::toggleDisableBackup (bool enabled) private slot
Definition at line 1111 of file SetupDialog.cpp.
References m_disableBackup.
Referenced by SetupDialog().
toggleDisplayWaveform
void lmms::gui::SetupDialog::toggleDisplayWaveform (bool enabled) private slot
Definition at line 1054 of file SetupDialog.cpp.
References m_displayWaveform.
Referenced by SetupDialog().
toggleLetPreviewsFinish
void lmms::gui::SetupDialog::toggleLetPreviewsFinish (bool enabled) private slot
Definition at line 1088 of file SetupDialog.cpp.
References m_letPreviewsFinish.
Referenced by SetupDialog().
toggleMidiAutoQuantization
void lmms::gui::SetupDialog::toggleMidiAutoQuantization (bool enabled) private slot
Definition at line 1290 of file SetupDialog.cpp.
References m_midiAutoQuantize.
Referenced by SetupDialog().
toggleMixerChannelDeletionWarning
void lmms::gui::SetupDialog::toggleMixerChannelDeletionWarning (bool enabled) private slot
Definition at line 1099 of file SetupDialog.cpp.
References m_mixerChannelDeletionWarning.
Referenced by SetupDialog().
toggleMMPZ
void lmms::gui::SetupDialog::toggleMMPZ (bool enabled) private slot
Definition at line 1105 of file SetupDialog.cpp.
References m_MMPZ.
Referenced by SetupDialog().
toggleNoteLabels
void lmms::gui::SetupDialog::toggleNoteLabels (bool enabled) private slot
Definition at line 1060 of file SetupDialog.cpp.
References m_printNoteLabels.
Referenced by SetupDialog().
toggleOneInstrumentTrackWindow
void lmms::gui::SetupDialog::toggleOneInstrumentTrackWindow (bool enabled) private slot
Definition at line 1076 of file SetupDialog.cpp.
References m_oneInstrumentTrackWindow.
Referenced by SetupDialog().
toggleOpenLastProject
void lmms::gui::SetupDialog::toggleOpenLastProject (bool enabled) private slot
Definition at line 1117 of file SetupDialog.cpp.
References m_openLastProject.
Referenced by SetupDialog().
toggleRunningAutoSave
void lmms::gui::SetupDialog::toggleRunningAutoSave (bool enabled) private slot
Definition at line 1164 of file SetupDialog.cpp.
References m_enableRunningAutoSave.
Referenced by SetupDialog().
toggleShowFaderTicks
void lmms::gui::SetupDialog::toggleShowFaderTicks (bool enabled) private slot
Definition at line 1065 of file SetupDialog.cpp.
References m_showFaderTicks.
Referenced by SetupDialog().
toggleSideBarOnRight
void lmms::gui::SetupDialog::toggleSideBarOnRight (bool enabled) private slot
Definition at line 1082 of file SetupDialog.cpp.
References m_sideBarOnRight.
Referenced by SetupDialog().
toggleSmoothScroll
void lmms::gui::SetupDialog::toggleSmoothScroll (bool enabled) private slot
Definition at line 1178 of file SetupDialog.cpp.
References m_smoothScroll.
Referenced by SetupDialog().
toggleSoloLegacyBehavior
void lmms::gui::SetupDialog::toggleSoloLegacyBehavior (bool enabled) private slot
Definition at line 1135 of file SetupDialog.cpp.
References m_soloLegacyBehavior.
Referenced by SetupDialog().
toggleTooltips
void lmms::gui::SetupDialog::toggleTooltips (bool enabled) private slot
Definition at line 1048 of file SetupDialog.cpp.
References m_tooltips.
Referenced by SetupDialog().
toggleTrackDeletionWarning
void lmms::gui::SetupDialog::toggleTrackDeletionWarning (bool enabled) private slot
Definition at line 1094 of file SetupDialog.cpp.
References m_trackDeletionWarning.
Referenced by SetupDialog().
toggleVSTAlwaysOnTop
void lmms::gui::SetupDialog::toggleVSTAlwaysOnTop (bool en) private slot
Definition at line 1197 of file SetupDialog.cpp.
References m_vstAlwaysOnTop.
Referenced by SetupDialog().
updateBufferSizeWarning
void lmms::gui::SetupDialog::updateBufferSizeWarning (int value) private slot
Definition at line 1220 of file SetupDialog.cpp.
References m_bufferSizeWarnLbl.
Referenced by setBufferSize().
vstEmbedMethodChanged
void lmms::gui::SetupDialog::vstEmbedMethodChanged () private slot
Definition at line 1190 of file SetupDialog.cpp.
References m_vstAlwaysOnTopCheckBox, m_vstEmbedComboBox, and m_vstEmbedMethod.
Referenced by SetupDialog().
Member Data Documentation
m_animateAFP
bool lmms::gui::SetupDialog::m_animateAFP private
Definition at line 164 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleAnimateAFP().
m_assignableMidiDevices
QComboBox* lmms::gui::SetupDialog::m_assignableMidiDevices private
Definition at line 192 of file SetupDialog.h.
Referenced by SetupDialog(), and accept().
m_audioIfaceNames
trMap lmms::gui::SetupDialog::m_audioIfaceNames private
Definition at line 179 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and audioInterfaceChanged().
m_audioIfaceSetupWidgets
AswMap lmms::gui::SetupDialog::m_audioIfaceSetupWidgets private
Definition at line 178 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and audioInterfaceChanged().
m_audioInterfaces
QComboBox* lmms::gui::SetupDialog::m_audioInterfaces private
Definition at line 177 of file SetupDialog.h.
Referenced by SetupDialog(), and accept().
m_autoSave
QCheckBox* lmms::gui::SetupDialog::m_autoSave private
Definition at line 161 of file SetupDialog.h.
Referenced by SetupDialog(), and resetAutoSave().
m_backgroundPicFile
QString lmms::gui::SetupDialog::m_backgroundPicFile private
Definition at line 205 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), openBackgroundPicFile(), and setBackgroundPicFile().
m_backgroundPicFileLineEdit
QLineEdit* lmms::gui::SetupDialog::m_backgroundPicFileLineEdit private
Definition at line 216 of file SetupDialog.h.
Referenced by SetupDialog(), and openBackgroundPicFile().
m_bufferSize
int lmms::gui::SetupDialog::m_bufferSize private
Definition at line 181 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and setBufferSize().
m_bufferSizeLbl
QLabel* lmms::gui::SetupDialog::m_bufferSizeLbl private
Definition at line 183 of file SetupDialog.h.
Referenced by SetupDialog(), and setBufferSize().
m_bufferSizeSlider
QSlider* lmms::gui::SetupDialog::m_bufferSizeSlider private
Definition at line 182 of file SetupDialog.h.
Referenced by SetupDialog(), and setBufferSize().
m_bufferSizeWarnLbl
QLabel* lmms::gui::SetupDialog::m_bufferSizeWarnLbl private
Definition at line 184 of file SetupDialog.h.
Referenced by SetupDialog(), and updateBufferSizeWarning().
m_compactTrackButtons
bool lmms::gui::SetupDialog::m_compactTrackButtons private
Definition at line 140 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleCompactTrackButtons().
m_disableAutoQuit
bool lmms::gui::SetupDialog::m_disableAutoQuit private
Definition at line 170 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleDisableAutoQuit().
m_disableBackup
bool lmms::gui::SetupDialog::m_disableBackup private
Definition at line 148 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleDisableBackup().
m_displayWaveform
bool lmms::gui::SetupDialog::m_displayWaveform private
Definition at line 137 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleDisplayWaveform().
m_enableAutoSave
bool lmms::gui::SetupDialog::m_enableAutoSave private
Definition at line 157 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), setAutoSaveInterval(), and toggleAutoSave().
m_enableRunningAutoSave
bool lmms::gui::SetupDialog::m_enableRunningAutoSave private
Definition at line 158 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleRunningAutoSave().
m_gigDir
QString lmms::gui::SetupDialog::m_gigDir private
Definition at line 199 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), openGIGDir(), and setGIGDir().
m_gigDirLineEdit
QLineEdit* lmms::gui::SetupDialog::m_gigDirLineEdit private
Definition at line 211 of file SetupDialog.h.
Referenced by SetupDialog(), and openGIGDir().
m_ladspaDir
QString lmms::gui::SetupDialog::m_ladspaDir private
Definition at line 198 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), openLADSPADir(), and setLADSPADir().
m_ladspaDirLineEdit
QLineEdit* lmms::gui::SetupDialog::m_ladspaDirLineEdit private
Definition at line 210 of file SetupDialog.h.
Referenced by SetupDialog(), and openLADSPADir().
m_lang
QString lmms::gui::SetupDialog::m_lang private
Definition at line 152 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and setLanguage().
m_languages
QStringList lmms::gui::SetupDialog::m_languages private
Definition at line 153 of file SetupDialog.h.
Referenced by SetupDialog(), and setLanguage().
m_letPreviewsFinish
bool lmms::gui::SetupDialog::m_letPreviewsFinish private
Definition at line 143 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleLetPreviewsFinish().
m_loopMarkerComboBox
QComboBox* lmms::gui::SetupDialog::m_loopMarkerComboBox private
Definition at line 151 of file SetupDialog.h.
Referenced by SetupDialog(), and loopMarkerModeChanged().
m_loopMarkerMode
QString lmms::gui::SetupDialog::m_loopMarkerMode private
Definition at line 150 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and loopMarkerModeChanged().
m_midiAutoQuantize
bool lmms::gui::SetupDialog::m_midiAutoQuantize private
Definition at line 193 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleMidiAutoQuantization().
m_midiIfaceNames
trMap lmms::gui::SetupDialog::m_midiIfaceNames private
Definition at line 191 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and midiInterfaceChanged().
m_midiIfaceSetupWidgets
MswMap lmms::gui::SetupDialog::m_midiIfaceSetupWidgets private
Definition at line 190 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and midiInterfaceChanged().
m_midiInterfaces
QComboBox* lmms::gui::SetupDialog::m_midiInterfaces private
Definition at line 189 of file SetupDialog.h.
Referenced by SetupDialog(), and accept().
m_mixerChannelDeletionWarning
bool lmms::gui::SetupDialog::m_mixerChannelDeletionWarning private
Definition at line 146 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleMixerChannelDeletionWarning().
m_MMPZ
bool lmms::gui::SetupDialog::m_MMPZ private
Definition at line 147 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleMMPZ().
m_NaNHandler
bool lmms::gui::SetupDialog::m_NaNHandler private
Definition at line 180 of file SetupDialog.h.
Referenced by SetupDialog(), and accept().
m_oneInstrumentTrackWindow
bool lmms::gui::SetupDialog::m_oneInstrumentTrackWindow private
Definition at line 141 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleOneInstrumentTrackWindow().
m_openLastProject
bool lmms::gui::SetupDialog::m_openLastProject private
Definition at line 149 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleOpenLastProject().
m_printNoteLabels
bool lmms::gui::SetupDialog::m_printNoteLabels private
Definition at line 138 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleNoteLabels().
m_runningAutoSave
QCheckBox* lmms::gui::SetupDialog::m_runningAutoSave private
Definition at line 162 of file SetupDialog.h.
Referenced by SetupDialog(), resetAutoSave(), and toggleAutoSave().
m_sampleRate
int lmms::gui::SetupDialog::m_sampleRate private
Definition at line 185 of file SetupDialog.h.
Referenced by SetupDialog(), and accept().
m_sampleRateSlider
QSlider* lmms::gui::SetupDialog::m_sampleRateSlider private
Definition at line 186 of file SetupDialog.h.
Referenced by SetupDialog().
m_saveInterval
int lmms::gui::SetupDialog::m_saveInterval private
Definition at line 156 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and setAutoSaveInterval().
m_saveIntervalLbl
QLabel* lmms::gui::SetupDialog::m_saveIntervalLbl private
Definition at line 160 of file SetupDialog.h.
Referenced by SetupDialog(), and setAutoSaveInterval().
m_saveIntervalSlider
QSlider* lmms::gui::SetupDialog::m_saveIntervalSlider private
Definition at line 159 of file SetupDialog.h.
Referenced by SetupDialog(), setAutoSaveInterval(), and toggleAutoSave().
m_sf2Dir
QString lmms::gui::SetupDialog::m_sf2Dir private
Definition at line 200 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), openSF2Dir(), and setSF2Dir().
m_sf2DirLineEdit
QLineEdit* lmms::gui::SetupDialog::m_sf2DirLineEdit private
Definition at line 212 of file SetupDialog.h.
Referenced by SetupDialog(), and openSF2Dir().
m_showFaderTicks
bool lmms::gui::SetupDialog::m_showFaderTicks private
Definition at line 139 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleShowFaderTicks().
m_sideBarOnRight
bool lmms::gui::SetupDialog::m_sideBarOnRight private
Definition at line 142 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleSideBarOnRight().
m_smoothScroll
bool lmms::gui::SetupDialog::m_smoothScroll private
Definition at line 163 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleSmoothScroll().
m_soloLegacyBehavior
bool lmms::gui::SetupDialog::m_soloLegacyBehavior private
Definition at line 144 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleSoloLegacyBehavior().
m_tabBar
TabBar* lmms::gui::SetupDialog::m_tabBar private
Definition at line 133 of file SetupDialog.h.
Referenced by SetupDialog().
m_themeDir
QString lmms::gui::SetupDialog::m_themeDir private
Definition at line 204 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), openBackgroundPicFile(), openThemeDir(), and setThemeDir().
m_themeDirLineEdit
QLineEdit* lmms::gui::SetupDialog::m_themeDirLineEdit private
Definition at line 209 of file SetupDialog.h.
Referenced by SetupDialog(), and openThemeDir().
m_tooltips
bool lmms::gui::SetupDialog::m_tooltips private
Definition at line 136 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleTooltips().
m_trackDeletionWarning
bool lmms::gui::SetupDialog::m_trackDeletionWarning private
Definition at line 145 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleTrackDeletionWarning().
m_vstAlwaysOnTop
bool lmms::gui::SetupDialog::m_vstAlwaysOnTop private
Definition at line 169 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and toggleVSTAlwaysOnTop().
m_vstAlwaysOnTopCheckBox
QCheckBox* lmms::gui::SetupDialog::m_vstAlwaysOnTopCheckBox private
Definition at line 168 of file SetupDialog.h.
Referenced by SetupDialog(), and vstEmbedMethodChanged().
m_vstDir
QString lmms::gui::SetupDialog::m_vstDir private
Definition at line 197 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), openVSTDir(), and setVSTDir().
m_vstDirLineEdit
QLineEdit* lmms::gui::SetupDialog::m_vstDirLineEdit private
Definition at line 208 of file SetupDialog.h.
Referenced by SetupDialog(), and openVSTDir().
m_vstEmbedComboBox
QComboBox* lmms::gui::SetupDialog::m_vstEmbedComboBox private
Definition at line 166 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), and vstEmbedMethodChanged().
m_vstEmbedLbl
QLabel* lmms::gui::SetupDialog::m_vstEmbedLbl private
Definition at line 165 of file SetupDialog.h.
Referenced by SetupDialog().
m_vstEmbedMethod
QString lmms::gui::SetupDialog::m_vstEmbedMethod private
Definition at line 167 of file SetupDialog.h.
Referenced by SetupDialog(), and vstEmbedMethodChanged().
m_workingDir
QString lmms::gui::SetupDialog::m_workingDir private
Definition at line 196 of file SetupDialog.h.
Referenced by SetupDialog(), accept(), openWorkingDir(), and setWorkingDir().
m_workingDirLineEdit
QLineEdit* lmms::gui::SetupDialog::m_workingDirLineEdit private
Definition at line 207 of file SetupDialog.h.
Referenced by SetupDialog(), and openWorkingDir().
restartWarningLbl
QLabel* lmms::gui::SetupDialog::restartWarningLbl private
Definition at line 218 of file SetupDialog.h.
Referenced by SetupDialog(), and showRestartWarning().
The documentation for this class was generated from the following files:
include/SetupDialog.h
src/gui/modals/SetupDialog.cpp