LMMS: Jack::JackLoadableInternalClient Class Reference
Jack::JackLoadableInternalClient Class Reference
#include <JackInternalClient.h>
Public Member Functions
JackLoadableInternalClient (JackServer *server, JackSynchro *table)
virtual ~JackLoadableInternalClient ()
virtual int Init (const char *so_name)
Public Member Functions inherited from Jack::JackInternalClient
JackInternalClient (JackServer *server, JackSynchro *table)
Client control.
virtual ~JackInternalClient ()
JackClientControl * GetClientControl () const
JackEngineControl * GetEngineControl () const
JackGraphManager * GetGraphManager () const
int Open (const char *server_name, const char *name, jack_uuid_t uuid, jack_options_t options, jack_status_t *status)
void ShutDown (jack_status_t code, const char *message)
Public Member Functions inherited from Jack::JackClient
JackClient (JackSynchro *table)
virtual ~JackClient ()
virtual int Activate ()
We need to start thread before activating in the server, otherwise the FW driver connected to the client may not be activated.
virtual int ClientHasSessionCallback (const char *client_name)
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual int ComputeTotalLatencies ()
void CycleSignal (int status)
jack_nframes_t CycleWait ()
virtual int Deactivate ()
Need to stop thread after deactivating in the server.
bool Execute ()
RT thread.
virtual char * GetClientNameByUUID (const char *uuid)
virtual jack_nframes_t GetCurrentTransportFrame ()
virtual char * GetInternalClientName (int ref)
char * GetServerName ()
virtual jack_native_thread_t GetThreadID ()
virtual char * GetUUIDForClientName (const char *client_name)
bool Init ()
Called once when the thread starts.
virtual int InternalClientHandle (const char *client_name, jack_status_t *status)
virtual int InternalClientLoad (const char *client_name, jack_options_t options, jack_status_t *status, jack_varargs_t *va)
virtual void InternalClientUnload (int ref, jack_status_t *status)
virtual void OnInfoShutdown (JackInfoShutdownCallback callback, void *arg)
virtual void OnShutdown (JackShutdownCallback callback, void *arg)
virtual int PortConnect (const char *src, const char *dst)
virtual int PortDisconnect (const char *src, const char *dst)
virtual int PortDisconnect (jack_port_id_t src)
virtual int PortIsMine (jack_port_id_t port_index)
virtual int PortRegister (const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
virtual int PortRename (jack_port_id_t port_index, const char *name)
virtual int PortUnRegister (jack_port_id_t port)
virtual int PropertyChangeNotify (jack_uuid_t subject, const char *key, jack_property_change_t change)
virtual int ReleaseTimebase ()
virtual int ReserveClientName (const char *client_name, const char *uuid)
virtual jack_session_command_t * SessionNotify (const char *target, jack_session_event_type_t type, const char *path)
virtual int SessionReply (jack_session_event_t *ev)
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetBufferSizeCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetClientRegistrationCallback (JackClientRegistrationCallback callback, void *arg)
virtual int SetFreeWheel (int onoff)
virtual int SetFreewheelCallback (JackFreewheelCallback callback, void *arg)
virtual int SetGraphOrderCallback (JackGraphOrderCallback callback, void *arg)
virtual int SetInitCallback (JackThreadInitCallback callback, void *arg)
virtual int SetLatencyCallback (JackLatencyCallback callback, void *arg)
virtual int SetPortConnectCallback (JackPortConnectCallback callback, void *arg)
virtual int SetPortRegistrationCallback (JackPortRegistrationCallback callback, void *arg)
virtual int SetPortRenameCallback (JackPortRenameCallback callback, void *arg)
virtual int SetProcessCallback (JackProcessCallback callback, void *arg)
virtual int SetProcessThread (JackThreadCallback fun, void *arg)
virtual int SetPropertyChangeCallback (JackPropertyChangeCallback callback, void *arg)
virtual int SetSampleRateCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetSessionCallback (JackSessionCallback callback, void *arg)
virtual int SetSyncCallback (JackSyncCallback sync_callback, void *arg)
virtual int SetSyncTimeout (jack_time_t timeout)
virtual int SetTimebaseCallback (int conditional, JackTimebaseCallback timebase_callback, void *arg)
virtual int SetXRunCallback (JackXRunCallback callback, void *arg)
virtual void TransportLocate (jack_nframes_t frame)
virtual jack_transport_state_t TransportQuery (jack_position_t *pos)
virtual int TransportReposition (const jack_position_t *pos)
virtual void TransportStart ()
virtual void TransportStop ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Protected Attributes
JackDriverDescFunction fDescriptor
FinishCallback fFinish
JACK_HANDLE fHandle
Protected Attributes inherited from Jack::JackClient
JackBufferSizeCallback fBufferSize
void * fBufferSizeArg
detail::JackClientChannelInterface * fChannel
Thread to execute the Process function.
JackClientRegistrationCallback fClientRegistration
void * fClientRegistrationArg
JackFreewheelCallback fFreewheel
void * fFreewheelArg
JackGraphOrderCallback fGraphOrder
void * fGraphOrderArg
JackInfoShutdownCallback fInfoShutdown
void * fInfoShutdownArg
JackThreadInitCallback fInit
void * fInitArg
JackLatencyCallback fLatency
void * fLatencyArg
JackPortConnectCallback fPortConnect
void * fPortConnectArg
std::list< jack_port_id_t > fPortList
JackPortRegistrationCallback fPortRegistration
void * fPortRegistrationArg
JackPortRenameCallback fPortRename
void * fPortRenameArg
JackProcessCallback fProcess
void * fProcessArg
JackPropertyChangeCallback fPropertyChange
void * fPropertyChangeArg
JackSampleRateCallback fSampleRate
void * fSampleRateArg
char fServerName [JACK_SERVER_NAME_SIZE+1]
JackSessionCallback fSession
void * fSessionArg
JackSessionReply fSessionReply
JackShutdownCallback fShutdown
void * fShutdownArg
JackSyncCallback fSync
void * fSyncArg
JackSynchro * fSynchroTable
JackThread fThread
JackThreadCallback fThreadFun
void * fThreadFunArg
JackTimebaseCallback fTimebase
void * fTimebaseArg
JackXRunCallback fXrun
void * fXrunArg
Additional Inherited Members
Static Public Attributes inherited from Jack::JackInternalClient
static JackEngineControl * fEngineControl = NULL
Shared memory Port manager.
static JackGraphManager * fGraphManager = NULL
Protected Member Functions inherited from Jack::JackClient
int ActivateAux ()
int CallProcessCallback ()
void CallSyncCallback ()
void CallSyncCallbackAux ()
void CallTimebaseCallback ()
void CallTimebaseCallbackAux ()
virtual int ClientNotifyImp (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value)
Notification received from the server.
void CycleSignalAux (int status)
jack_nframes_t CycleWaitAux ()
void DummyCycle ()
void End ()
void Error ()
void ExecuteThread ()
int HandleLatencyCallback (int status)
void InitAux ()
bool IsActive ()
void SetupDriverSync (bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
void SetupRealTime ()
void SignalSync ()
int StartThread ()
bool WaitSync ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Detailed Description
Definition at line 68 of file JackInternalClient.h.
Constructor & Destructor Documentation
JackLoadableInternalClient()
Jack::JackLoadableInternalClient::JackLoadableInternalClient (JackServer * server, JackSynchro * table) inline
Definition at line 79 of file JackInternalClient.h.
References Jack::JackInternalClient::JackInternalClient(), fDescriptor, fFinish, fHandle, and server().
Referenced by Jack::JackLoadableInternalClient1::JackLoadableInternalClient1(), and Jack::JackLoadableInternalClient2::JackLoadableInternalClient2().
~JackLoadableInternalClient()
Jack::JackLoadableInternalClient::~JackLoadableInternalClient () virtual
Definition at line 217 of file JackInternalClient.cpp.
References fFinish, fHandle, Jack::JackClient::fProcessArg, and UnloadJackModule.
Member Function Documentation
Init()
int Jack::JackLoadableInternalClient::Init (const char * so_name) virtual
Reimplemented in Jack::JackLoadableInternalClient1, and Jack::JackLoadableInternalClient2.
Definition at line 143 of file JackInternalClient.cpp.
References Jack::BuildClientPath(), fDescriptor, fFinish, fHandle, GetJackProc, jack_error, jack_log(), JACK_PATH_MAX, LoadJackModule, Jack::PrintLoadError(), and UnloadJackModule.
Referenced by Jack::JackLoadableInternalClient1::Init(), and Jack::JackLoadableInternalClient2::Init().
Member Data Documentation
fDescriptor
JackDriverDescFunction Jack::JackLoadableInternalClient::fDescriptor protected
Definition at line 75 of file JackInternalClient.h.
Referenced by JackLoadableInternalClient(), and Init().
fFinish
FinishCallback Jack::JackLoadableInternalClient::fFinish protected
Definition at line 74 of file JackInternalClient.h.
Referenced by JackLoadableInternalClient(), ~JackLoadableInternalClient(), Init(), Jack::JackLoadableInternalClient1::Open(), and Jack::JackLoadableInternalClient2::Open().
fHandle
JACK_HANDLE Jack::JackLoadableInternalClient::fHandle protected
Definition at line 73 of file JackInternalClient.h.
Referenced by JackLoadableInternalClient(), ~JackLoadableInternalClient(), Jack::JackLoadableInternalClient1::Init(), Jack::JackLoadableInternalClient2::Init(), and Init().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackInternalClient.h
src/3rdparty/jack2/common/JackInternalClient.cpp