LMMS: Jack::JackGoldfishDriver Class Reference
Jack::JackGoldfishDriver Class Reference
The goldfish driver.
#include <JackGoldfishDriver.h>
Public Member Functions
JackGoldfishDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackGoldfishDriver ()
int Close ()
int Open (jack_nframes_t buffe_size, jack_nframes_t samplerate, bool capturing, bool playing, int chan_in, int chan_out, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
int Read ()
int SetBufferSize (jack_nframes_t buffer_size)
int Write ()
Public Member Functions inherited from Jack::JackAudioDriver
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int Attach ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Detach ()
virtual int Process ()
virtual int SetSampleRate (jack_nframes_t sample_rate)
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsFixedBufferSize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
virtual int Start ()
virtual int Stop ()
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Attributes
short * mBuffer
int mFd
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAudioDriver
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
virtual void UpdateLatencies ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The goldfish driver.
Definition at line 34 of file JackGoldfishDriver.h.
Constructor & Destructor Documentation
JackGoldfishDriver()
Jack::JackGoldfishDriver::JackGoldfishDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table) inline
Definition at line 39 of file JackGoldfishDriver.h.
References Jack::JackAudioDriver::JackAudioDriver(), mBuffer, and mFd.
~JackGoldfishDriver()
virtual Jack::JackGoldfishDriver::~JackGoldfishDriver () inline virtual
Definition at line 42 of file JackGoldfishDriver.h.
Member Function Documentation
Close()
int Jack::JackGoldfishDriver::Close () virtual
Reimplemented from Jack::JackDriver.
Definition at line 71 of file JackGoldfishDriver.cpp.
References Jack::JackClientInterface::Close(), jack_log(), mBuffer, and mFd.
Open()
int Jack::JackGoldfishDriver::Open (jack_nframes_t buffe_size, jack_nframes_t samplerate, bool capturing, bool playing, int chan_in, int chan_out, bool monitor, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency) virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 40 of file JackGoldfishDriver.cpp.
References capture_latency, JACK_GOLDFISH_BUFFER_SIZE, jack_log(), Jack::kAudioDeviceName, mBuffer, mFd, Jack::JackAudioDriver::Open(), and playback_latency.
Read()
int Jack::JackGoldfishDriver::Read () virtual
Reimplemented from Jack::JackDriver.
Definition at line 87 of file JackGoldfishDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackAudioDriver::GetInputBuffer(), i, JACK_GOLDFISH_BUFFER_SIZE, and jack_log().
SetBufferSize()
int Jack::JackGoldfishDriver::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 112 of file JackGoldfishDriver.cpp.
References jack_log(), and Jack::JackAudioDriver::SetBufferSize().
Write()
int Jack::JackGoldfishDriver::Write () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 96 of file JackGoldfishDriver.cpp.
References Jack::JackAudioDriver::GetOutputBuffer(), i, j, JACK_GOLDFISH_BUFFER_SIZE, jack_log(), mBuffer, and mFd.
Member Data Documentation
mBuffer
short* Jack::JackGoldfishDriver::mBuffer private
Definition at line 64 of file JackGoldfishDriver.h.
Referenced by JackGoldfishDriver(), Close(), Open(), and Write().
mFd
int Jack::JackGoldfishDriver::mFd private
Definition at line 63 of file JackGoldfishDriver.h.
Referenced by JackGoldfishDriver(), Close(), Open(), and Write().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/android/JackGoldfishDriver.h
src/3rdparty/jack2/android/JackGoldfishDriver.cpp