LMMS: lmms::SampleThumbnail::Thumbnail::Peak Struct Reference
lmms::SampleThumbnail::Thumbnail::Peak Struct Reference
#include <SampleThumbnail.h>
Public Member Functions
Peak ()=default
Peak (const SampleFrame &frame)
Peak (float min, float max)
Peak operator+ (const Peak &other) const
Peak operator+ (const SampleFrame &frame) const
Public Attributes
float max = -std::numeric_limits<float>::infinity()
float min = std::numeric_limits<float>::infinity()
Detailed Description
Definition at line 81 of file SampleThumbnail.h.
Constructor & Destructor Documentation
Peak() [1/3]
lmms::SampleThumbnail::Thumbnail::Peak::Peak () default
Referenced by operator+(), and operator+().
Peak() [2/3]
lmms::SampleThumbnail::Thumbnail::Peak::Peak (float min, float max) inline
Definition at line 85 of file SampleThumbnail.h.
References max, and min.
Peak() [3/3]
lmms::SampleThumbnail::Thumbnail::Peak::Peak (const SampleFrame & frame) inline
Definition at line 91 of file SampleThumbnail.h.
References max, and min.
Member Function Documentation
operator+() [1/2]
Peak lmms::SampleThumbnail::Thumbnail::Peak::operator+ (const Peak & other) const inline
Definition at line 97 of file SampleThumbnail.h.
References Peak(), max, and min.
operator+() [2/2]
Peak lmms::SampleThumbnail::Thumbnail::Peak::operator+ (const SampleFrame & frame) const inline
Definition at line 98 of file SampleThumbnail.h.
References Peak().
Member Data Documentation
max
float lmms::SampleThumbnail::Thumbnail::Peak::max = -std::numeric_limits<float>::infinity()
Definition at line 101 of file SampleThumbnail.h.
Referenced by Peak(), Peak(), and operator+().
min
float lmms::SampleThumbnail::Thumbnail::Peak::min = std::numeric_limits<float>::infinity()
Definition at line 100 of file SampleThumbnail.h.
Referenced by Peak(), Peak(), and operator+().
The documentation for this struct was generated from the following file:
include/SampleThumbnail.h