LMMS: lmms::PlayHandle Class Reference
lmms::PlayHandle Class Reference abstract
#include <PlayHandle.h>
Public Types
enum class Type {
NotePlayHandle = 0x01 ,
InstrumentPlayHandle = 0x02 ,
SamplePlayHandle = 0x04 ,
PresetPreviewHandle = 0x08
}
using Types = Flags<Type>
Public Types inherited from lmms::ThreadableJob
enum class ProcessingState : int {
Unstarted ,
Queued ,
InProgress ,
Done
}
Public Member Functions
PlayHandle (const Type type, f_cnt_t offset=0)
virtual ~PlayHandle ()
const QThread * affinity () const
virtual bool affinityMatters () const
AudioBusHandle * audioBusHandle ()
SampleFrame * buffer ()
void doProcessing () override
virtual bool isFinished () const =0
virtual bool isFromTrack (const Track *_track) const =0
void lock ()
f_cnt_t offset () const
PlayHandle & operator= (PlayHandle &p)
virtual void play (SampleFrame *buffer)=0
void releaseBuffer ()
bool requiresProcessing () const override
void setAudioBusHandle (AudioBusHandle *busHandle)
void setOffset (f_cnt_t _offset)
void setUsesBuffer (const bool b)
bool tryLock ()
Type type () const
void unlock ()
bool usesBuffer () const
Public Member Functions inherited from lmms::ThreadableJob
ThreadableJob ()
void done ()
void process ()
void queue ()
void reset ()
ProcessingState state () const
Static Public Attributes
static constexpr std::size_t MaxNumber = 1024
Private Attributes
QThread * m_affinity
AudioBusHandle * m_audioBusHandle
bool m_bufferReleased
f_cnt_t m_offset
SampleFrame * m_playHandleBuffer
QMutex m_processingLock
Type m_type
bool m_usesBuffer
Additional Inherited Members
Protected Attributes inherited from lmms::ThreadableJob
std::atomic< ProcessingState > m_state
Detailed Description
Definition at line 46 of file PlayHandle.h.
Member Typedef Documentation
Types
using lmms::PlayHandle::Types = Flags<Type>
Definition at line 56 of file PlayHandle.h.
Member Enumeration Documentation
Type
enum class lmms::PlayHandle::Type strong
Enumerator
NotePlayHandle
InstrumentPlayHandle
SamplePlayHandle
PresetPreviewHandle
Definition at line 49 of file PlayHandle.h.
Constructor & Destructor Documentation
PlayHandle()
lmms::PlayHandle::PlayHandle (const Type type, f_cnt_t offset = 0)
Definition at line 36 of file PlayHandle.cpp.
References m_affinity, m_bufferReleased, m_offset, m_playHandleBuffer, m_type, m_usesBuffer, offset(), and type().
Referenced by lmms::InstrumentPlayHandle::InstrumentPlayHandle(), lmms::NotePlayHandle::NotePlayHandle(), lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::SamplePlayHandle::SamplePlayHandle(), lmms::SampleRecordHandle::SampleRecordHandle(), and operator=().
~PlayHandle()
lmms::PlayHandle::~PlayHandle () virtual
Definition at line 47 of file PlayHandle.cpp.
References m_playHandleBuffer, and lmms::BufferManager::release().
Member Function Documentation
affinity()
const QThread * lmms::PlayHandle::affinity () const inline
Definition at line 79 of file PlayHandle.h.
References m_affinity.
Referenced by lmms::AudioEngine::removePlayHandle().
affinityMatters()
virtual bool lmms::PlayHandle::affinityMatters () const inline virtual
Reimplemented in lmms::PresetPreviewPlayHandle, and lmms::SamplePlayHandle.
Definition at line 74 of file PlayHandle.h.
Referenced by lmms::AudioEngine::removePlayHandle().
audioBusHandle()
AudioBusHandle * lmms::PlayHandle::audioBusHandle () inline
Definition at line 137 of file PlayHandle.h.
References m_audioBusHandle.
Referenced by lmms::SamplePlayHandle::~SamplePlayHandle(), lmms::AudioEngine::addPlayHandle(), and lmms::AudioEngine::removePlayHandle().
buffer()
SampleFrame * lmms::PlayHandle::buffer ()
Definition at line 73 of file PlayHandle.cpp.
References m_bufferReleased, and m_playHandleBuffer.
Referenced by lmms::NotePlayHandle::~NotePlayHandle(), doProcessing(), play(), and lmms::SamplePlayHandle::play().
doProcessing()
void lmms::PlayHandle::doProcessing () override virtual
Implements lmms::ThreadableJob.
Definition at line 53 of file PlayHandle.cpp.
References lmms::Engine::audioEngine(), buffer(), m_bufferReleased, m_playHandleBuffer, m_usesBuffer, play(), and lmms::zeroSampleFrames().
isFinished()
virtual bool lmms::PlayHandle::isFinished () const pure virtual
Implemented in lmms::InstrumentPlayHandle, lmms::NotePlayHandle, lmms::PresetPreviewPlayHandle, lmms::SamplePlayHandle, and lmms::SampleRecordHandle.
Referenced by requiresProcessing().
isFromTrack()
virtual bool lmms::PlayHandle::isFromTrack (const Track * _track) const pure virtual
Implemented in lmms::InstrumentPlayHandle, lmms::NotePlayHandle, lmms::PresetPreviewPlayHandle, lmms::SamplePlayHandle, and lmms::SampleRecordHandle.
lock()
void lmms::PlayHandle::lock () inline
Definition at line 97 of file PlayHandle.h.
References m_processingLock.
Referenced by lmms::NotePlayHandle::NotePlayHandle(), lmms::NotePlayHandle::~NotePlayHandle(), and lmms::NotePlayHandle::play().
offset()
f_cnt_t lmms::PlayHandle::offset () const inline
Definition at line 114 of file PlayHandle.h.
References m_offset.
Referenced by PlayHandle(), lmms::Instrument::applyFadeIn(), lmms::NotePlayHandle::framesLeftForCurrentPeriod(), lmms::NotePlayHandle::noteOffset(), lmms::NotePlayHandle::operator==(), lmms::NotePlayHandle::play(), lmms::SamplePlayHandle::play(), lmms::InstrumentFunctionNoteStacking::processNote(), and lmms::NotePlayHandle::setSongGlobalParentOffset().
operator=()
PlayHandle & lmms::PlayHandle::operator= (PlayHandle & p) inline
Definition at line 62 of file PlayHandle.h.
References PlayHandle(), m_affinity, m_audioBusHandle, m_offset, m_type, and m_usesBuffer.
play()
virtual void lmms::PlayHandle::play (SampleFrame * buffer) pure virtual
Implemented in lmms::InstrumentPlayHandle, lmms::NotePlayHandle, lmms::PresetPreviewPlayHandle, lmms::SamplePlayHandle, and lmms::SampleRecordHandle.
References buffer().
Referenced by doProcessing().
releaseBuffer()
void lmms::PlayHandle::releaseBuffer ()
Definition at line 68 of file PlayHandle.cpp.
References m_bufferReleased.
Referenced by lmms::NotePlayHandle::~NotePlayHandle().
requiresProcessing()
bool lmms::PlayHandle::requiresProcessing () const inline override virtual
Implements lmms::ThreadableJob.
Definition at line 92 of file PlayHandle.h.
References isFinished().
setAudioBusHandle()
void lmms::PlayHandle::setAudioBusHandle (AudioBusHandle * busHandle) inline
Definition at line 142 of file PlayHandle.h.
References m_audioBusHandle.
Referenced by lmms::InstrumentPlayHandle::InstrumentPlayHandle(), lmms::NotePlayHandle::NotePlayHandle(), lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::SamplePlayHandle::SamplePlayHandle(), and lmms::SamplePlayHandle::SamplePlayHandle().
setOffset()
void lmms::PlayHandle::setOffset (f_cnt_t _offset) inline
Definition at line 119 of file PlayHandle.h.
References m_offset.
Referenced by lmms::NotePlayHandle::play(), and lmms::SampleTrack::play().
setUsesBuffer()
void lmms::PlayHandle::setUsesBuffer (const bool b) inline
Definition at line 132 of file PlayHandle.h.
References m_usesBuffer.
Referenced by lmms::NotePlayHandle::NotePlayHandle(), lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), and lmms::NotePlayHandle::setMasterNote().
tryLock()
bool lmms::PlayHandle::tryLock () inline
Definition at line 105 of file PlayHandle.h.
References m_processingLock.
type()
Type lmms::PlayHandle::type () const inline
Definition at line 84 of file PlayHandle.h.
References m_type.
Referenced by PlayHandle(), lmms::AudioEngine::addPlayHandle(), and lmms::AudioEngine::removePlayHandle().
unlock()
void lmms::PlayHandle::unlock () inline
Definition at line 101 of file PlayHandle.h.
References m_processingLock.
Referenced by lmms::NotePlayHandle::NotePlayHandle(), lmms::NotePlayHandle::~NotePlayHandle(), and lmms::NotePlayHandle::play().
usesBuffer()
bool lmms::PlayHandle::usesBuffer () const inline
Definition at line 127 of file PlayHandle.h.
References m_usesBuffer.
Referenced by lmms::InstrumentTrack::playNote().
Member Data Documentation
m_affinity
QThread* lmms::PlayHandle::m_affinity private
Definition at line 154 of file PlayHandle.h.
Referenced by PlayHandle(), affinity(), and operator=().
m_audioBusHandle
AudioBusHandle* lmms::PlayHandle::m_audioBusHandle private
Definition at line 159 of file PlayHandle.h.
Referenced by audioBusHandle(), operator=(), and setAudioBusHandle().
m_bufferReleased
bool lmms::PlayHandle::m_bufferReleased private
Definition at line 157 of file PlayHandle.h.
Referenced by PlayHandle(), buffer(), doProcessing(), and releaseBuffer().
m_offset
f_cnt_t lmms::PlayHandle::m_offset private
Definition at line 153 of file PlayHandle.h.
Referenced by PlayHandle(), offset(), operator=(), and setOffset().
m_playHandleBuffer
SampleFrame* lmms::PlayHandle::m_playHandleBuffer private
Definition at line 156 of file PlayHandle.h.
Referenced by PlayHandle(), ~PlayHandle(), buffer(), and doProcessing().
m_processingLock
QMutex lmms::PlayHandle::m_processingLock private
Definition at line 155 of file PlayHandle.h.
Referenced by lock(), tryLock(), and unlock().
m_type
Type lmms::PlayHandle::m_type private
Definition at line 152 of file PlayHandle.h.
Referenced by PlayHandle(), operator=(), and type().
m_usesBuffer
bool lmms::PlayHandle::m_usesBuffer private
Definition at line 158 of file PlayHandle.h.
Referenced by PlayHandle(), doProcessing(), operator=(), setUsesBuffer(), and usesBuffer().
MaxNumber
std::size_t lmms::PlayHandle::MaxNumber = 1024 static constexpr
Definition at line 58 of file PlayHandle.h.
The documentation for this class was generated from the following files:
include/PlayHandle.h
src/core/PlayHandle.cpp