LMMS: Jack::JackFFADODriver Class Reference
Jack::JackFFADODriver Class Reference
The FFADO driver.
#include <JackFFADODriver.h>
Public Member Functions
JackFFADODriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackFFADODriver ()
int Attach ()
int Close ()
int Detach ()
bool IsFixedBufferSize ()
int Open (ffado_jack_settings_t *cmlparams)
int Read ()
int SetBufferSize (jack_nframes_t nframes)
int Start ()
int Stop ()
int Write ()
Public Member Functions inherited from Jack::JackAudioDriver
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int SetSampleRate (jack_nframes_t sample_rate)
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Member Functions
int ffado_driver_attach (ffado_driver_t *driver)
void ffado_driver_delete (ffado_driver_t *driver)
int ffado_driver_detach (ffado_driver_t *driver)
ffado_driver_t * ffado_driver_new (const char *name, ffado_jack_settings_t *params)
int ffado_driver_read (ffado_driver_t *driver, jack_nframes_t nframes)
int ffado_driver_restart (ffado_driver_t *driver)
int ffado_driver_start (ffado_driver_t *driver)
int ffado_driver_stop (ffado_driver_t *driver)
jack_nframes_t ffado_driver_wait (ffado_driver_t *driver, int extra_fd, int *status, float *delayed_usecs)
int ffado_driver_write (ffado_driver_t *driver, jack_nframes_t nframes)
void jack_driver_init (jack_driver_t *driver)
void jack_driver_nt_init (jack_driver_nt_t *driver)
void UpdateLatencies ()
Private Attributes
jack_driver_t * fDriver
int g_verbose
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAudioDriver
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The FFADO driver.
Definition at line 39 of file JackFFADODriver.h.
Constructor & Destructor Documentation
JackFFADODriver()
Jack::JackFFADODriver::JackFFADODriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table) inline
Definition at line 67 of file JackFFADODriver.h.
References Jack::JackAudioDriver::JackAudioDriver().
~JackFFADODriver()
virtual Jack::JackFFADODriver::~JackFFADODriver () inline virtual
Definition at line 70 of file JackFFADODriver.h.
Member Function Documentation
Attach()
int Jack::JackFFADODriver::Attach () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 436 of file JackFFADODriver.cpp.
References CaptureDriverFlags, driver, DRIVER_PORT_NUM, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fClientControl, fDriver, Jack::JackDriver::fEngine, Jack::JackDriver::fEngineControl, FFADO_RT_PRIORITY_PACKETIZER_RELATIVE, Jack::JackDriver::fGraphManager, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, g_verbose, JACK_DEFAULT_AUDIO_TYPE, JACK_DEFAULT_MIDI_TYPE, jack_error, jack_log(), PlaybackDriverFlags, printError, printMessage, REAL_JACK_PORT_NAME_SIZE, Jack::JackPort::SetAlias(), and UpdateLatencies().
Close()
int Jack::JackFFADODriver::Close () virtual
Reimplemented from Jack::JackDriver.
Definition at line 713 of file JackFFADODriver.cpp.
References Jack::JackClientInterface::Close(), fDriver, and ffado_driver_delete().
Detach()
int Jack::JackFFADODriver::Detach () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 656 of file JackFFADODriver.cpp.
References Jack::JackAudioDriver::Detach(), driver, fDriver, and jack_log().
ffado_driver_attach()
int Jack::JackFFADODriver::ffado_driver_attach (ffado_driver_t * driver) private
References driver.
ffado_driver_delete()
void Jack::JackFFADODriver::ffado_driver_delete (ffado_driver_t * driver) private
Definition at line 431 of file JackFFADODriver.cpp.
References driver.
Referenced by Close().
ffado_driver_detach()
int Jack::JackFFADODriver::ffado_driver_detach (ffado_driver_t * driver) private
References driver.
ffado_driver_new()
ffado_driver_t * Jack::JackFFADODriver::ffado_driver_new (const char * name, ffado_jack_settings_t * params) private
Definition at line 362 of file JackFFADODriver.cpp.
References _ffado_jack_settings::buffer_size, _ffado_jack_settings::capture_frame_latency, DEBUG_LEVEL_STARTUP, debugPrint, _ffado_jack_settings::device_info, driver, Jack::JackDriver::fBeginDateUst, FIREWIRE_REQUIRED_FFADO_API_VERSION, jack_driver_nt_init(), _ffado_jack_settings::period_size, _ffado_jack_settings::playback_frame_latency, printError, printMessage, _ffado_jack_settings::sample_rate, _ffado_jack_settings::snoop_mode, and _ffado_jack_settings::verbose_level.
Referenced by Open().
ffado_driver_read()
int Jack::JackFFADODriver::ffado_driver_read (ffado_driver_t * driver, jack_nframes_t nframes) private
Definition at line 67 of file JackFFADODriver.cpp.
References driver, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fGraphManager, printEnter, printExit, and Jack::JackFFADOMidiInputPort::Process().
Referenced by Read().
ffado_driver_restart()
int Jack::JackFFADODriver::ffado_driver_restart (ffado_driver_t * driver) private
Definition at line 260 of file JackFFADODriver.cpp.
References driver, Start(), and Stop().
ffado_driver_start()
int Jack::JackFFADODriver::ffado_driver_start (ffado_driver_t * driver) private
Definition at line 234 of file JackFFADODriver.cpp.
References driver, and printError.
Referenced by Start().
ffado_driver_stop()
int Jack::JackFFADODriver::ffado_driver_stop (ffado_driver_t * driver) private
Definition at line 247 of file JackFFADODriver.cpp.
References driver, and printError.
Referenced by Stop().
ffado_driver_wait()
jack_nframes_t Jack::JackFFADODriver::ffado_driver_wait (ffado_driver_t * driver, int extra_fd, int * status, float * delayed_usecs) private
Definition at line 164 of file JackFFADODriver.cpp.
References driver, Jack::JackDriver::fBeginDateUst, jack_error, jack_get_microseconds, printEnter, and printExit.
Referenced by Read().
ffado_driver_write()
int Jack::JackFFADODriver::ffado_driver_write (ffado_driver_t * driver, jack_nframes_t nframes) private
Definition at line 120 of file JackFFADODriver.cpp.
References driver, Jack::JackDriver::fGraphManager, Jack::JackDriver::fPlaybackPortList, printEnter, printExit, and Jack::JackFFADOMidiOutputPort::Process().
Referenced by Write().
IsFixedBufferSize()
bool Jack::JackFFADODriver::IsFixedBufferSize () inline virtual
Reimplemented from Jack::JackDriver.
Definition at line 86 of file JackFFADODriver.h.
jack_driver_init()
void Jack::JackFFADODriver::jack_driver_init (jack_driver_t * driver) private
Definition at line 790 of file JackFFADODriver.cpp.
References driver.
Referenced by jack_driver_nt_init().
jack_driver_nt_init()
void Jack::JackFFADODriver::jack_driver_nt_init (jack_driver_nt_t * driver) private
Definition at line 805 of file JackFFADODriver.cpp.
References driver, and jack_driver_init().
Referenced by ffado_driver_new().
Open()
int Jack::JackFFADODriver::Open (ffado_jack_settings_t * cmlparams)
Definition at line 689 of file JackFFADODriver.cpp.
References _ffado_jack_settings::capture_frame_latency, Jack::JackClientInterface::Close(), fDriver, ffado_driver_new(), Jack::JackAudioDriver::Open(), _ffado_jack_settings::period_size, _ffado_jack_settings::playback_frame_latency, _ffado_jack_settings::playback_ports, and _ffado_jack_settings::sample_rate.
Referenced by driver_initialize().
Read()
int Jack::JackFFADODriver::Read () virtual
Reimplemented from Jack::JackDriver.
Definition at line 743 of file JackFFADODriver.cpp.
References Jack::JackDriver::CycleIncTime(), driver, Jack::JackDriver::fBeginDateUst, Jack::JackDriver::fDelayedUsecs, fDriver, Jack::JackDriver::fEngineControl, ffado_driver_read(), ffado_driver_wait(), jack_log(), Jack::JackDriver::NotifyXRun(), printEnter, printError, and printExit.
SetBufferSize()
int Jack::JackFFADODriver::SetBufferSize (jack_nframes_t nframes) virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 293 of file JackFFADODriver.cpp.
References driver, fDriver, ffado_streaming_set_period_size(), FIREWIRE_REQUIRED_FFADO_API_VERSION_FOR_SETBUFSIZE, printError, Jack::JackAudioDriver::SetBufferSize(), and UpdateLatencies().
Start()
int Jack::JackFFADODriver::Start () virtual
Reimplemented from Jack::JackDriver.
Definition at line 722 of file JackFFADODriver.cpp.
References fDriver, ffado_driver_start(), Jack::JackDriverInterface::Start(), and Jack::JackDriverInterface::Stop().
Referenced by ffado_driver_restart().
Stop()
int Jack::JackFFADODriver::Stop () virtual
Reimplemented from Jack::JackDriver.
Definition at line 734 of file JackFFADODriver.cpp.
References fDriver, ffado_driver_stop(), and Jack::JackDriverInterface::Stop().
Referenced by ffado_driver_restart().
UpdateLatencies()
void Jack::JackFFADODriver::UpdateLatencies (void) private virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 268 of file JackFFADODriver.cpp.
References driver, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, fDriver, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, Jack::JackDriver::fWithMonitorPorts, i, JackCaptureLatency, JackPlaybackLatency, _jack_latency_range::max, and _jack_latency_range::min.
Referenced by Attach(), and SetBufferSize().
Write()
int Jack::JackFFADODriver::Write () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 781 of file JackFFADODriver.cpp.
References fDriver, Jack::JackDriver::fEngineControl, ffado_driver_write(), printEnter, and printExit.
Member Data Documentation
fDriver
jack_driver_t* Jack::JackFFADODriver::fDriver private
Definition at line 47 of file JackFFADODriver.h.
Referenced by Attach(), Close(), Detach(), Open(), Read(), SetBufferSize(), Start(), Stop(), UpdateLatencies(), and Write().
g_verbose
int Jack::JackFFADODriver::g_verbose private
Definition at line 45 of file JackFFADODriver.h.
Referenced by Attach().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/linux/firewire/JackFFADODriver.h
src/3rdparty/jack2/linux/firewire/JackFFADODriver.cpp