LMMS: hiir::Upsampler2x4Neon< NC > Class Template Reference
hiir::Upsampler2x4Neon< NC > Class Template Reference
#include <Upsampler2x4Neon.h>
Public Types
typedef float DataType
Public Member Functions
Upsampler2x4Neon () noexcept
Upsampler2x4Neon (const Upsampler2x4Neon< NC > &other)=default
Upsampler2x4Neon (Upsampler2x4Neon< NC > &&other)=default
~Upsampler2x4Neon ()=default
void clear_buffers () noexcept
Upsampler2x4Neon< NC > & operator= (const Upsampler2x4Neon< NC > &other)=default
Upsampler2x4Neon< NC > & operator= (Upsampler2x4Neon< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (float32x4_t &out_0, float32x4_t &out_1, float32x4_t input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 4
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataNeonV4, NBR_COEFS+2 > Filter
Private Member Functions
bool operator!= (const Upsampler2x4Neon< NC > &other) const =delete
bool operator== (const Upsampler2x4Neon< NC > &other) const =delete
Private Attributes
Filter _filter
Detailed Description
template<int NC>
class hiir::Upsampler2x4Neon< NC >
Definition at line 53 of file Upsampler2x4Neon.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Upsampler2x4Neon< NC >::DataType
Definition at line 62 of file Upsampler2x4Neon.h.
Filter
template<int NC> typedef std::array<StageDataNeonV4, NBR_COEFS + 2> hiir::Upsampler2x4Neon< NC >::Filter private
Definition at line 96 of file Upsampler2x4Neon.h.
Constructor & Destructor Documentation
Upsampler2x4Neon() [1/3]
template<int NC> hiir::Upsampler2x4Neon< NC >::Upsampler2x4Neon () noexcept
Definition at line 56 of file Upsampler2x4Neon.hpp.
References _filter, clear_buffers(), i, NBR_COEFS, and hiir::storea().
Referenced by Upsampler2x4Neon(), Upsampler2x4Neon(), ~Upsampler2x4Neon(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2x4Neon() [2/3]
template<int NC> hiir::Upsampler2x4Neon< NC >::Upsampler2x4Neon (const Upsampler2x4Neon< NC > & other) default
References Upsampler2x4Neon().
Upsampler2x4Neon() [3/3]
template<int NC> hiir::Upsampler2x4Neon< NC >::Upsampler2x4Neon (Upsampler2x4Neon< NC > && other) default
References Upsampler2x4Neon().
~Upsampler2x4Neon()
template<int NC> hiir::Upsampler2x4Neon< NC >::~Upsampler2x4Neon () default
References Upsampler2x4Neon().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2x4Neon< NC >::clear_buffers () noexcept
Definition at line 180 of file Upsampler2x4Neon.hpp.
References _filter, i, NBR_COEFS, and hiir::storea().
Referenced by Upsampler2x4Neon(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2x4Neon< NC >::operator!= (const Upsampler2x4Neon< NC > & other) const private delete
References Upsampler2x4Neon().
operator=() [1/2]
template<int NC> Upsampler2x4Neon< NC > & hiir::Upsampler2x4Neon< NC >::operator= (const Upsampler2x4Neon< NC > & other) default
References Upsampler2x4Neon().
operator=() [2/2]
template<int NC> Upsampler2x4Neon< NC > & hiir::Upsampler2x4Neon< NC >::operator= (Upsampler2x4Neon< NC > && other) default
References Upsampler2x4Neon(), clear_buffers(), hiir_FORCEINLINE, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2x4Neon< NC >::operator== (const Upsampler2x4Neon< NC > & other) const private delete
References Upsampler2x4Neon().
process_block()
template<int NC> void hiir::Upsampler2x4Neon< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 145 of file Upsampler2x4Neon.hpp.
References _nbr_chn, hiir::load4u(), pos, process_sample(), and hiir::storeu().
Referenced by operator=().
process_sample()
template<int NC> void hiir::Upsampler2x4Neon< NC >::process_sample (float32x4_t & out_0, float32x4_t & out_1, float32x4_t input) noexcept
Definition at line 111 of file Upsampler2x4Neon.hpp.
References _filter, NBR_COEFS, and hiir::StageProc4Neon< REMAINING >::process_sample_pos().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::Upsampler2x4Neon< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 84 of file Upsampler2x4Neon.hpp.
References _filter, i, NBR_COEFS, and hiir::storea().
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Upsampler2x4Neon< NC >::_delay = 0 static constexpr
Definition at line 65 of file Upsampler2x4Neon.h.
_filter
template<int NC> Filter hiir::Upsampler2x4Neon< NC >::_filter private
Definition at line 98 of file Upsampler2x4Neon.h.
Referenced by Upsampler2x4Neon(), clear_buffers(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Upsampler2x4Neon< NC >::_nbr_chn = 4 static constexpr
Definition at line 63 of file Upsampler2x4Neon.h.
Referenced by process_block().
NBR_COEFS
template<int NC> int hiir::Upsampler2x4Neon< NC >::NBR_COEFS = NC static constexpr
Definition at line 64 of file Upsampler2x4Neon.h.
Referenced by Upsampler2x4Neon(), clear_buffers(), operator=(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2x4Neon.h
src/3rdparty/hiir/hiir/Upsampler2x4Neon.hpp