LMMS: src/3rdparty/jack2/android/JackError.cpp File Reference
JackError.cpp File Reference
#include <stdarg.h>
#include <stdio.h>
#include "JackError.h"
#include "JackGlobals.h"
#include "JackMessageBuffer.h"
#include <utils/Log.h>
Macros
#define LOG_BUF_SIZE 1024
#define LOG_TAG "JackAudioClient"
Functions
static bool change_thread_log_function (jack_log_function_t log_function)
SERVER_EXPORT void default_jack_error_callback (const char *desc)
SERVER_EXPORT void default_jack_info_callback (const char *desc)
SERVER_EXPORT void jack_error (const char *fmt,...)
Call this function to log an error message.
static void jack_format_and_log (int level, const char *prefix, const char *fmt, va_list ap)
SERVER_EXPORT void jack_info (const char *fmt,...)
Call this function to log an information message.
SERVER_EXPORT void jack_log (const char *fmt,...)
Call this function to log an information message but only when verbose mode is enabled.
void jack_log_function (int level, const char *message)
SERVER_EXPORT int set_threaded_log_function ()
SERVER_EXPORT void silent_jack_error_callback (const char *desc)
SERVER_EXPORT void silent_jack_info_callback (const char *desc)
Variables
SERVER_EXPORT void(* jack_error_callback)(const char *desc) = &default_jack_error_callback
Display JACK error message.
SERVER_EXPORT void(* jack_info_callback)(const char *desc) = &default_jack_info_callback
Display JACK info message.
Macro Definition Documentation
LOG_BUF_SIZE
#define LOG_BUF_SIZE 1024
Definition at line 29 of file JackError.cpp.
Referenced by jack_error(), jack_info(), and jack_log().
LOG_TAG
#define LOG_TAG "JackAudioClient"
Definition at line 34 of file JackError.cpp.
Function Documentation
change_thread_log_function()
bool change_thread_log_function (jack_log_function_t log_function) static
Definition at line 40 of file JackError.cpp.
References Jack::JackGlobals::fKeyLogFunction, jack_tls_get(), and jack_tls_set().
Referenced by set_threaded_log_function().
default_jack_error_callback()
SERVER_EXPORT void default_jack_error_callback (const char * desc)
Definition at line 134 of file JackError.cpp.
References SERVER_EXPORT.
Referenced by jack_set_error_function().
default_jack_info_callback()
SERVER_EXPORT void default_jack_info_callback (const char * desc)
Definition at line 140 of file JackError.cpp.
References SERVER_EXPORT.
Referenced by jack_set_info_function().
jack_format_and_log()
void jack_format_and_log (int level, const char * prefix, const char * fmt, va_list ap) static
Definition at line 70 of file JackError.cpp.
References Jack::JackGlobals::fKeyLogFunction, jack_log_function(), and jack_tls_get().
jack_log_function()
void jack_log_function (int level, const char * message)
Definition at line 51 of file JackError.cpp.
References jack_error_callback, jack_info_callback, LOG_LEVEL_ERROR, and LOG_LEVEL_INFO.
Referenced by Jack::JackMessageBuffer::Flush(), jack_format_and_log(), and Jack::JackMessageBufferAdd().
set_threaded_log_function()
SERVER_EXPORT int set_threaded_log_function ()
Definition at line 46 of file JackError.cpp.
References change_thread_log_function(), Jack::JackMessageBufferAdd(), and SERVER_EXPORT.
Referenced by Jack::JackWinMMEOutputPort::HandleMessage(), Jack::JackALSARawMidiDriver::Init(), Jack::JackBoomerDriver::JackBoomerDriverInput::Init(), Jack::JackBoomerDriver::JackBoomerDriverOutput::Init(), Jack::JackClient::Init(), Jack::JackNetAdapter::Init(), Jack::JackWinMMEOutputPort::Init(), Jack::JackWinMMEInputPort::ProcessWinMME(), Jack::JackPortAudioDriver::Render(), and Jack::JackThreadedDriver::SetRealTime().
silent_jack_error_callback()
SERVER_EXPORT void silent_jack_error_callback (const char * desc)
Definition at line 146 of file JackError.cpp.
References SERVER_EXPORT.
Referenced by main().
silent_jack_info_callback()
SERVER_EXPORT void silent_jack_info_callback (const char * desc)
Definition at line 149 of file JackError.cpp.
References SERVER_EXPORT.