LMMS: lmms::gui::ProjectNotes Class Reference
lmms::gui::ProjectNotes Class Reference
#include <ProjectNotes.h>
Public Member Functions
ProjectNotes ()
~ProjectNotes () override=default
void clear ()
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
void setText (const QString &_text)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual void restoreState (const QDomElement &_this)
virtual QDomElement saveState (QDomDocument &_doc, QDomElement &_parent)
void setHook (SerializingObjectHook *_hook)
Protected Member Functions
void closeEvent (QCloseEvent *_ce) override
void setupActions ()
Private Slots
void alignmentChanged (int _a)
void formatChanged (const QTextCharFormat &_f)
void textAlign (QAction *_a)
void textBold ()
void textColor ()
void textFamily (const QString &_f)
void textItalic ()
void textSize (const QString &_p)
void textUnderline ()
Private Attributes
QAction * m_actionAlignCenter
QAction * m_actionAlignJustify
QAction * m_actionAlignLeft
QAction * m_actionAlignRight
QAction * m_actionTextBold
QAction * m_actionTextColor
QAction * m_actionTextItalic
QAction * m_actionTextUnderline
QComboBox * m_comboFont
QComboBox * m_comboSize
QTextEdit * m_edit
Detailed Description
Definition at line 41 of file ProjectNotes.h.
Constructor & Destructor Documentation
ProjectNotes()
lmms::gui::ProjectNotes::ProjectNotes ()
Definition at line 52 of file ProjectNotes.cpp.
References lmms::gui::MainWindow::addWindowedWidget(), clear(), formatChanged(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), lmms::Engine::getSong(), m_edit, lmms::gui::GuiApplication::mainWindow(), and setupActions().
~ProjectNotes()
lmms::gui::ProjectNotes::~ProjectNotes () override default
References clear(), loadSettings(), saveSettings(), and setText().
Member Function Documentation
alignmentChanged
void lmms::gui::ProjectNotes::alignmentChanged (int _a) private slot
Definition at line 350 of file ProjectNotes.cpp.
References lmms::Engine::getSong(), m_actionAlignCenter, m_actionAlignJustify, m_actionAlignLeft, m_actionAlignRight, and lmms::Song::setModified().
clear()
void lmms::gui::ProjectNotes::clear ()
Definition at line 88 of file ProjectNotes.cpp.
References m_edit.
Referenced by ProjectNotes(), ~ProjectNotes(), and lmms::Song::clearProject().
closeEvent()
void lmms::gui::ProjectNotes::closeEvent (QCloseEvent * _ce) override protected
Definition at line 394 of file ProjectNotes.cpp.
formatChanged
void lmms::gui::ProjectNotes::formatChanged (const QTextCharFormat & _f) private slot
Definition at line 331 of file ProjectNotes.cpp.
References lmms::Engine::getSong(), m_actionTextBold, m_actionTextColor, m_actionTextItalic, m_actionTextUnderline, m_comboFont, m_comboSize, and lmms::Song::setModified().
Referenced by ProjectNotes().
loadSettings()
void lmms::gui::ProjectNotes::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 385 of file ProjectNotes.cpp.
References m_edit, and lmms::gui::MainWindow::restoreWidgetState().
Referenced by ~ProjectNotes().
nodeName()
QString lmms::gui::ProjectNotes::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 54 of file ProjectNotes.h.
saveSettings()
void lmms::gui::ProjectNotes::saveSettings (QDomDocument & _doc, QDomElement & _parent) override virtual
Implements lmms::SerializingObject.
Definition at line 374 of file ProjectNotes.cpp.
References m_edit, and lmms::gui::MainWindow::saveWidgetState().
Referenced by ~ProjectNotes().
setText()
void lmms::gui::ProjectNotes::setText (const QString & _text)
Definition at line 101 of file ProjectNotes.cpp.
References m_edit.
Referenced by ~ProjectNotes().
setupActions()
void lmms::gui::ProjectNotes::setupActions () protected
Definition at line 109 of file ProjectNotes.cpp.
References activated, lmms::embed::getIconPixmap(), m_actionAlignCenter, m_actionAlignJustify, m_actionAlignLeft, m_actionAlignRight, m_actionTextBold, m_actionTextColor, m_actionTextItalic, m_actionTextUnderline, m_comboFont, m_comboSize, m_edit, textAlign(), textBold(), textColor(), textItalic(), textSize(), textUnderline(), and lmms::UI_CTRL_KEY.
Referenced by ProjectNotes().
textAlign
void lmms::gui::ProjectNotes::textAlign (QAction * _a) private slot
Definition at line 308 of file ProjectNotes.cpp.
References m_actionAlignCenter, m_actionAlignJustify, m_actionAlignLeft, m_actionAlignRight, and m_edit.
Referenced by setupActions().
textBold
void lmms::gui::ProjectNotes::textBold () private slot
Definition at line 244 of file ProjectNotes.cpp.
References lmms::Engine::getSong(), m_actionTextBold, m_edit, and lmms::Song::setModified().
Referenced by setupActions().
textColor
void lmms::gui::ProjectNotes::textColor () private slot
Definition at line 292 of file ProjectNotes.cpp.
References m_actionTextColor, and m_edit.
Referenced by setupActions().
textFamily
void lmms::gui::ProjectNotes::textFamily (const QString & _f) private slot
Definition at line 272 of file ProjectNotes.cpp.
References lmms::Engine::getSong(), m_edit, and lmms::Song::setModified().
textItalic
void lmms::gui::ProjectNotes::textItalic () private slot
Definition at line 263 of file ProjectNotes.cpp.
References lmms::Engine::getSong(), m_actionTextItalic, m_edit, and lmms::Song::setModified().
Referenced by setupActions().
textSize
void lmms::gui::ProjectNotes::textSize (const QString & _p) private slot
Definition at line 282 of file ProjectNotes.cpp.
References lmms::Engine::getSong(), m_edit, and lmms::Song::setModified().
Referenced by setupActions().
textUnderline
void lmms::gui::ProjectNotes::textUnderline () private slot
Definition at line 254 of file ProjectNotes.cpp.
References lmms::Engine::getSong(), m_actionTextUnderline, m_edit, and lmms::Song::setModified().
Referenced by setupActions().
Member Data Documentation
m_actionAlignCenter
QAction * lmms::gui::ProjectNotes::m_actionAlignCenter private
Definition at line 85 of file ProjectNotes.h.
Referenced by alignmentChanged(), setupActions(), and textAlign().
m_actionAlignJustify
QAction * lmms::gui::ProjectNotes::m_actionAlignJustify private
Definition at line 87 of file ProjectNotes.h.
Referenced by alignmentChanged(), setupActions(), and textAlign().
m_actionAlignLeft
QAction * lmms::gui::ProjectNotes::m_actionAlignLeft private
Definition at line 84 of file ProjectNotes.h.
Referenced by alignmentChanged(), setupActions(), and textAlign().
m_actionAlignRight
QAction * lmms::gui::ProjectNotes::m_actionAlignRight private
Definition at line 86 of file ProjectNotes.h.
Referenced by alignmentChanged(), setupActions(), and textAlign().
m_actionTextBold
QAction* lmms::gui::ProjectNotes::m_actionTextBold private
Definition at line 80 of file ProjectNotes.h.
Referenced by formatChanged(), setupActions(), and textBold().
m_actionTextColor
QAction * lmms::gui::ProjectNotes::m_actionTextColor private
Definition at line 83 of file ProjectNotes.h.
Referenced by formatChanged(), setupActions(), and textColor().
m_actionTextItalic
QAction * lmms::gui::ProjectNotes::m_actionTextItalic private
Definition at line 82 of file ProjectNotes.h.
Referenced by formatChanged(), setupActions(), and textItalic().
m_actionTextUnderline
QAction * lmms::gui::ProjectNotes::m_actionTextUnderline private
Definition at line 81 of file ProjectNotes.h.
Referenced by formatChanged(), setupActions(), and textUnderline().
m_comboFont
QComboBox* lmms::gui::ProjectNotes::m_comboFont private
Definition at line 88 of file ProjectNotes.h.
Referenced by formatChanged(), and setupActions().
m_comboSize
QComboBox* lmms::gui::ProjectNotes::m_comboSize private
Definition at line 89 of file ProjectNotes.h.
Referenced by formatChanged(), and setupActions().
m_edit
QTextEdit* lmms::gui::ProjectNotes::m_edit private
Definition at line 79 of file ProjectNotes.h.
Referenced by ProjectNotes(), clear(), loadSettings(), saveSettings(), setText(), setupActions(), textAlign(), textBold(), textColor(), textFamily(), textItalic(), textSize(), and textUnderline().
The documentation for this class was generated from the following files:
include/ProjectNotes.h
src/gui/ProjectNotes.cpp