LMMS: Jack::JackNetSlaveInterface Class Reference
Jack::JackNetSlaveInterface Class Reference
\Brief This class describes the Net Interface for slaves (NetDriver and NetAdapter)
#include <JackNetInterface.h>
Public Member Functions
JackNetSlaveInterface ()
JackNetSlaveInterface (const char *ip, int port)
virtual ~JackNetSlaveInterface ()
Public Member Functions inherited from Jack::JackNetInterface
JackNetInterface ()
JackNetInterface (const char *multicast_ip, int port)
JackNetInterface (session_params_t &params, JackNetSocket &socket, const char *multicast_ip)
virtual ~JackNetInterface ()
Protected Member Functions
int DataRecv ()
int DataSend ()
void DecodeSyncPacket (int &frames)
void EncodeSyncPacket (int frames=-1)
void FatalRecvError ()
void FatalSendError ()
bool Init ()
void InitAPI ()
bool InitConnection (int time_out_sec)
bool InitRendering ()
int Recv (size_t size, int flags)
int Send (size_t size, int flags)
net_status_t SendAvailableToMaster (int count=INT_MAX)
net_status_t SendStartToMaster ()
bool SetParams ()
int SyncRecv ()
int SyncSend ()
Protected Member Functions inherited from Jack::JackNetInterface
NetAudioBuffer * AudioBufferFactory (int nports, char *buffer)
int AudioRecv (packet_header_t *rx_head, NetAudioBuffer *buffer)
int AudioSend (NetAudioBuffer *buffer, int audio_channels)
virtual void DecodeTransportData ()=0
virtual void EncodeTransportData ()=0
int FinishRecv (NetAudioBuffer *buffer)
void FreeNetworkBuffers ()
void Initialize ()
int MidiRecv (packet_header_t *rx_head, NetMidiBuffer *buffer, uint &recvd_midi_pckt)
int MidiSend (NetMidiBuffer *buffer, int midi_channnels, int audio_channels)
int SetNetBufferSize ()
void SetPacketTimeOut (int time_out)
void SetRcvTimeOut ()
Static Protected Attributes
static uint fSlaveCounter = 0
Additional Inherited Members
Protected Attributes inherited from Jack::JackNetInterface
char fMulticastIP [32]
NetAudioBuffer * fNetAudioCaptureBuffer
NetAudioBuffer * fNetAudioPlaybackBuffer
NetMidiBuffer * fNetMidiCaptureBuffer
NetMidiBuffer * fNetMidiPlaybackBuffer
int fPacketTimeOut
session_params_t fParams
net_transport_data_t fReturnTransportData
char * fRxBuffer
char * fRxData
packet_header_t fRxHeader
net_transport_data_t fSendTransportData
bool fSetTimeOut
JackNetSocket fSocket
char * fTxBuffer
char * fTxData
packet_header_t fTxHeader
Detailed Description
\Brief This class describes the Net Interface for slaves (NetDriver and NetAdapter)
Definition at line 199 of file JackNetInterface.h.
Constructor & Destructor Documentation
JackNetSlaveInterface() [1/2]
Jack::JackNetSlaveInterface::JackNetSlaveInterface () inline
Definition at line 235 of file JackNetInterface.h.
References Jack::JackNetInterface::JackNetInterface(), and InitAPI().
Referenced by Jack::JackNetAdapter::JackNetAdapter(), and Jack::JackNetDriver::JackNetDriver().
JackNetSlaveInterface() [2/2]
Jack::JackNetSlaveInterface::JackNetSlaveInterface (const char * ip, int port) inline
Definition at line 240 of file JackNetInterface.h.
References Jack::JackNetInterface::JackNetInterface(), and InitAPI().
~JackNetSlaveInterface()
virtual Jack::JackNetSlaveInterface::~JackNetSlaveInterface () inline virtual
Definition at line 245 of file JackNetInterface.h.
References fSlaveCounter, and Jack::SocketAPIEnd().
Member Function Documentation
DataRecv()
int Jack::JackNetSlaveInterface::DataRecv () protected virtual
Implements Jack::JackNetInterface.
Definition at line 896 of file JackNetInterface.cpp.
References Jack::JackNetInterface::AudioRecv(), Jack::_packet_header::fCycle, Jack::_packet_header::fDataStream, Jack::_packet_header::fDataType, Jack::_packet_header::fID, Jack::JackNetInterface::FinishRecv(), Jack::JackNetInterface::fNetAudioCaptureBuffer, Jack::JackNetInterface::fNetMidiCaptureBuffer, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fRxBuffer, Jack::JackNetInterface::fRxHeader, jack_info(), Jack::JackNetInterface::MidiRecv(), Recv(), and SOCKET_ERROR.
Referenced by Jack::JackNetAdapter::Read(), Jack::JackNetDriver::Read(), and Jack::JackNetExtSlave::Read().
DataSend()
int Jack::JackNetSlaveInterface::DataSend () protected virtual
Implements Jack::JackNetInterface.
Definition at line 952 of file JackNetInterface.cpp.
References Jack::JackNetInterface::AudioSend(), Jack::JackNetInterface::fNetAudioPlaybackBuffer, Jack::JackNetInterface::fNetMidiPlaybackBuffer, Jack::JackNetInterface::fParams, Jack::JackNetInterface::MidiSend(), and SOCKET_ERROR.
Referenced by Jack::JackNetAdapter::Write(), Jack::JackNetDriver::Write(), and Jack::JackNetExtSlave::Write().
DecodeSyncPacket()
void Jack::JackNetSlaveInterface::DecodeSyncPacket (int & frames) protected virtual
Implements Jack::JackNetInterface.
Definition at line 985 of file JackNetInterface.cpp.
References Jack::_packet_header::fActivePorts, Jack::_packet_header::fFrames, Jack::JackNetInterface::fNetAudioPlaybackBuffer, Jack::JackNetInterface::fRxBuffer, and Jack::JackNetInterface::fRxData.
Referenced by Jack::JackNetAdapter::Read(), Jack::JackNetDriver::Read(), and Jack::JackNetExtSlave::Read().
EncodeSyncPacket()
void Jack::JackNetSlaveInterface::EncodeSyncPacket (int frames = -1) protected virtual
Implements Jack::JackNetInterface.
Definition at line 961 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fNetAudioCaptureBuffer, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fTxData, Jack::JackNetInterface::fTxHeader, and PACKET_AVAILABLE_SIZE.
Referenced by Jack::JackNetAdapter::Write(), Jack::JackNetDriver::Write(), and Jack::JackNetExtSlave::Write().
FatalRecvError()
void Jack::JackNetSlaveInterface::FatalRecvError () protected virtual
Implements Jack::JackNetInterface.
Definition at line 829 of file JackNetInterface.cpp.
Referenced by Recv().
FatalSendError()
void Jack::JackNetSlaveInterface::FatalSendError () protected virtual
Implements Jack::JackNetInterface.
Definition at line 834 of file JackNetInterface.cpp.
Referenced by Send().
Init()
bool Jack::JackNetSlaveInterface::Init () protected virtual
Implements Jack::JackNetInterface.
Definition at line 623 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fParams, jack_info(), jack_log(), Jack::NET_CONNECTED, Jack::NET_ERROR, Jack::NET_ROLLING, Jack::NET_SOCKET_ERROR, NETWORK_PROTOCOL, SendAvailableToMaster(), SendStartToMaster(), Jack::SetPacketType(), and Jack::SLAVE_AVAILABLE.
Referenced by Jack::JackNetAdapter::Init(), and Jack::JackNetDriver::Initialize().
InitAPI()
void Jack::JackNetSlaveInterface::InitAPI () protected
Definition at line 612 of file JackNetInterface.cpp.
References fSlaveCounter, jack_error, and Jack::SocketAPIInit().
Referenced by JackNetSlaveInterface(), and JackNetSlaveInterface().
InitConnection()
bool Jack::JackNetSlaveInterface::InitConnection (int time_out_sec) protected
Definition at line 657 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fParams, jack_log(), Jack::NET_CONNECTED, NETWORK_PROTOCOL, SendAvailableToMaster(), Jack::SetPacketType(), Jack::SLAVE_AVAILABLE, and SLAVE_INIT_TIMEOUT.
Referenced by Jack::JackNetExtSlave::Open(), and Jack::JackNetExtSlave::Restart().
InitRendering()
bool Jack::JackNetSlaveInterface::InitRendering () protected
Definition at line 670 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fParams, jack_info(), jack_log(), Jack::NET_ERROR, Jack::NET_ROLLING, and SendStartToMaster().
Referenced by Jack::JackNetExtSlave::Open(), and Jack::JackNetExtSlave::Restart().
Recv()
int Jack::JackNetSlaveInterface::Recv (size_t size, int flags) protected virtual
Implements Jack::JackNetInterface.
Definition at line 839 of file JackNetInterface.cpp.
References FatalRecvError(), Jack::JackNetInterface::fRxBuffer, Jack::JackNetInterface::fSocket, Jack::PacketHeaderNToH(), and SOCKET_ERROR.
Referenced by DataRecv(), and SyncRecv().
Send()
int Jack::JackNetSlaveInterface::Send (size_t size, int flags) protected virtual
Implements Jack::JackNetInterface.
Definition at line 853 of file JackNetInterface.cpp.
References FatalSendError(), Jack::JackNetInterface::fSocket, Jack::JackNetInterface::fTxBuffer, Jack::PacketHeaderHToN(), and SOCKET_ERROR.
Referenced by SyncSend().
SendAvailableToMaster()
net_status_t Jack::JackNetSlaveInterface::SendAvailableToMaster (int count = INT_MAX) protected
Definition at line 688 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fMulticastIP, Jack::_session_params::fPacketType, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fSocket, Jack::GetPacketType(), jack_error, jack_info(), jack_log(), Jack::NET_CONNECT_ERROR, Jack::NET_CONNECTED, NET_ERROR_CODE, Jack::NET_NO_DATA, Jack::NET_RECV_ERROR, Jack::NET_SOCKET_ERROR, Jack::SessionParamsHToN(), Jack::SessionParamsNToH(), SLAVE_INIT_TIMEOUT, Jack::SLAVE_SETUP, SOCKET_ERROR, and StrError.
Referenced by Init(), and InitConnection().
SendStartToMaster()
net_status_t Jack::JackNetSlaveInterface::SendStartToMaster () protected
Definition at line 762 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fParams, Jack::JackNetInterface::fSocket, jack_error, jack_log(), Jack::NET_CONN_ERROR, Jack::NET_ERROR, NET_ERROR_CODE, Jack::NET_ROLLING, Jack::NET_SEND_ERROR, Jack::SessionParamsHToN(), Jack::SetPacketType(), SOCKET_ERROR, Jack::START_MASTER, and StrError.
Referenced by Init(), and InitRendering().
SetParams()
bool Jack::JackNetSlaveInterface::SetParams () protected virtual
Reimplemented from Jack::JackNetInterface.
Definition at line 778 of file JackNetInterface.cpp.
References Jack::JackNetInterface::AudioBufferFactory(), Jack::JackNetInterface::fNetAudioCaptureBuffer, Jack::JackNetInterface::fNetAudioPlaybackBuffer, Jack::JackNetInterface::fNetMidiCaptureBuffer, Jack::JackNetInterface::fNetMidiPlaybackBuffer, Jack::JackNetInterface::fParams, Jack::JackNetInterface::FreeNetworkBuffers(), Jack::JackNetInterface::fRxData, Jack::JackNetInterface::fRxHeader, Jack::JackNetInterface::fTxData, Jack::JackNetInterface::fTxHeader, jack_error, jack_log(), NET_ERROR_CODE, Jack::JackNetInterface::SetNetBufferSize(), Jack::JackNetInterface::SetParams(), SOCKET_ERROR, and StrError.
Referenced by Jack::JackNetAdapter::Init(), Jack::JackNetDriver::Initialize(), Jack::JackNetExtSlave::Open(), and Jack::JackNetExtSlave::Restart().
SyncRecv()
int Jack::JackNetSlaveInterface::SyncRecv () protected virtual
Implements Jack::JackNetInterface.
Definition at line 867 of file JackNetInterface.cpp.
References Jack::_packet_header::fDataType, Jack::_packet_header::fIsLastPckt, Jack::_packet_header::fPacketType, Jack::JackNetInterface::fParams, Jack::JackNetInterface::fRxBuffer, Jack::JackNetInterface::fRxHeader, jack_error, Recv(), Jack::JackNetInterface::SetRcvTimeOut(), SOCKET_ERROR, and SYNC_PACKET_ERROR.
Referenced by Jack::JackNetAdapter::Read(), Jack::JackNetDriver::Read(), and Jack::JackNetExtSlave::Read().
SyncSend()
int Jack::JackNetSlaveInterface::SyncSend () protected virtual
Implements Jack::JackNetInterface.
Definition at line 934 of file JackNetInterface.cpp.
References Jack::JackNetInterface::fParams, Jack::JackNetInterface::fRxHeader, Jack::JackNetInterface::fTxBuffer, Jack::JackNetInterface::fTxHeader, HEADER_SIZE, and Send().
Referenced by Jack::JackNetAdapter::Write(), Jack::JackNetDriver::Write(), and Jack::JackNetExtSlave::Write().
Member Data Documentation
fSlaveCounter
uint Jack::JackNetSlaveInterface::fSlaveCounter = 0 static protected
Definition at line 204 of file JackNetInterface.h.
Referenced by ~JackNetSlaveInterface(), and InitAPI().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackNetInterface.h
src/3rdparty/jack2/common/JackNetInterface.cpp