LMMS: Jack::NetIntAudioBuffer Class Reference
Jack::NetIntAudioBuffer Class Reference
#include <JackNetTool.h>
Public Member Functions
NetIntAudioBuffer (session_params_t *params, uint32_t nports, char *net_buffer)
virtual ~NetIntAudioBuffer ()
float GetCycleDuration ()
size_t GetCycleSize ()
int GetNumPackets (int active_ports)
int RenderFromJackPorts (int nframes)
int RenderFromNetwork (int cycle, int sub_cycle, uint32_t port_num)
void RenderToJackPorts (int nframes)
int RenderToNetwork (int sub_cycle, uint32_t port_num)
Public Member Functions inherited from Jack::NetAudioBuffer
NetAudioBuffer (session_params_t *params, uint32_t nports, char *net_buffer)
virtual ~NetAudioBuffer ()
virtual void ActivePortsFromNetwork (char *net_buffer, uint32_t port_num)
virtual int ActivePortsToNetwork (char *net_buffer)
virtual sample_t * GetBuffer (int index)
bool GetConnected (int port_index)
virtual void SetBuffer (int index, sample_t *buffer)
void SetConnected (int port_index, bool state)
Private Attributes
int fCompressedSizeByte
short ** fIntBuffer
size_t fLastSubPeriodBytesSize
Additional Inherited Members
Protected Member Functions inherited from Jack::NetAudioBuffer
int CheckPacket (int cycle, int sub_cycle)
void Cleanup ()
void NextCycle ()
Protected Attributes inherited from Jack::NetAudioBuffer
bool * fConnectedPorts
size_t fCycleBytesSize
float fCycleDuration
int fLastSubCycle
char * fNetBuffer
int fNPorts
int fNumPackets
jack_nframes_t fPeriodSize
sample_t ** fPortBuffer
size_t fSubPeriodBytesSize
jack_nframes_t fSubPeriodSize
Detailed Description
Definition at line 454 of file JackNetTool.h.
Constructor & Destructor Documentation
NetIntAudioBuffer()
Jack::NetIntAudioBuffer::NetIntAudioBuffer (session_params_t * params, uint32_t nports, char * net_buffer)
Definition at line 949 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::NetAudioBuffer(), fCompressedSizeByte, Jack::NetAudioBuffer::fCycleBytesSize, Jack::NetAudioBuffer::fCycleDuration, fIntBuffer, Jack::NetAudioBuffer::fLastSubCycle, fLastSubPeriodBytesSize, Jack::_session_params::fMtu, Jack::NetAudioBuffer::fNPorts, Jack::NetAudioBuffer::fNumPackets, Jack::_session_params::fPeriodSize, Jack::NetAudioBuffer::fPeriodSize, Jack::_session_params::fSampleRate, Jack::NetAudioBuffer::fSubPeriodBytesSize, Jack::NetAudioBuffer::fSubPeriodSize, jack_log(), and PACKET_AVAILABLE_SIZE.
~NetIntAudioBuffer()
Jack::NetIntAudioBuffer::~NetIntAudioBuffer () virtual
Definition at line 983 of file JackNetTool.cpp.
References fIntBuffer, and Jack::NetAudioBuffer::fNPorts.
Member Function Documentation
GetCycleDuration()
float Jack::NetIntAudioBuffer::GetCycleDuration () virtual
Implements Jack::NetAudioBuffer.
Definition at line 997 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fCycleDuration.
GetCycleSize()
size_t Jack::NetIntAudioBuffer::GetCycleSize () virtual
Implements Jack::NetAudioBuffer.
Definition at line 992 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fCycleBytesSize.
GetNumPackets()
int Jack::NetIntAudioBuffer::GetNumPackets (int active_ports) virtual
Implements Jack::NetAudioBuffer.
Definition at line 1002 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::fNumPackets.
RenderFromJackPorts()
int Jack::NetIntAudioBuffer::RenderFromJackPorts (int nframes) virtual
Reimplemented from Jack::NetAudioBuffer.
Definition at line 1007 of file JackNetTool.cpp.
References fIntBuffer, Jack::NetAudioBuffer::fNPorts, Jack::NetAudioBuffer::fPeriodSize, and Jack::NetAudioBuffer::fPortBuffer.
RenderFromNetwork()
int Jack::NetIntAudioBuffer::RenderFromNetwork (int cycle, int sub_cycle, uint32_t port_num) virtual
Implements Jack::NetAudioBuffer.
Definition at line 1038 of file JackNetTool.cpp.
References Jack::NetAudioBuffer::CheckPacket(), Jack::NetAudioBuffer::Cleanup(), fIntBuffer, fLastSubPeriodBytesSize, Jack::NetAudioBuffer::fNetBuffer, Jack::NetAudioBuffer::fNPorts, Jack::NetAudioBuffer::fNumPackets, Jack::NetAudioBuffer::fSubPeriodBytesSize, and Jack::NetAudioBuffer::fSubPeriodSize.
RenderToJackPorts()
void Jack::NetIntAudioBuffer::RenderToJackPorts (int nframes) virtual
Reimplemented from Jack::NetAudioBuffer.
Definition at line 1023 of file JackNetTool.cpp.
References fIntBuffer, Jack::NetAudioBuffer::fNPorts, Jack::NetAudioBuffer::fPortBuffer, and Jack::NetAudioBuffer::NextCycle().
RenderToNetwork()
int Jack::NetIntAudioBuffer::RenderToNetwork (int sub_cycle, uint32_t port_num) virtual
Implements Jack::NetAudioBuffer.
Definition at line 1063 of file JackNetTool.cpp.
References fIntBuffer, fLastSubPeriodBytesSize, Jack::NetAudioBuffer::fNetBuffer, Jack::NetAudioBuffer::fNPorts, Jack::NetAudioBuffer::fNumPackets, Jack::NetAudioBuffer::fSubPeriodBytesSize, and Jack::NetAudioBuffer::fSubPeriodSize.
Member Data Documentation
fCompressedSizeByte
int Jack::NetIntAudioBuffer::fCompressedSizeByte private
Definition at line 458 of file JackNetTool.h.
Referenced by NetIntAudioBuffer().
fIntBuffer
short** Jack::NetIntAudioBuffer::fIntBuffer private
Definition at line 462 of file JackNetTool.h.
Referenced by NetIntAudioBuffer(), ~NetIntAudioBuffer(), RenderFromJackPorts(), RenderFromNetwork(), RenderToJackPorts(), and RenderToNetwork().
fLastSubPeriodBytesSize
size_t Jack::NetIntAudioBuffer::fLastSubPeriodBytesSize private
Definition at line 460 of file JackNetTool.h.
Referenced by NetIntAudioBuffer(), RenderFromNetwork(), and RenderToNetwork().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackNetTool.h
src/3rdparty/jack2/common/JackNetTool.cpp