LMMS: lmms::gui::SideBarWidget Class Reference
lmms::gui::SideBarWidget Class Reference
#include <SideBarWidget.h>
Signals
void closeButtonClicked ()
Public Member Functions
SideBarWidget (const QString &_title, const QPixmap &_icon, QWidget *_parent)
~SideBarWidget () override=default
const QPixmap & icon () const
const QString & title () const
Protected Member Functions
void addContentLayout (QLayout *_l)
void addContentWidget (QWidget *_w)
QWidget * contentParent ()
void contextMenuEvent (QContextMenuEvent *) override
void paintEvent (QPaintEvent *_pe) override
void resizeEvent (QResizeEvent *_re) override
Private Attributes
const QSize m_buttonSize
QPushButton * m_closeBtn
QWidget * m_contents
QPixmap m_icon
QVBoxLayout * m_layout
QString m_title
Detailed Description
Definition at line 38 of file SideBarWidget.h.
Constructor & Destructor Documentation
SideBarWidget()
lmms::gui::SideBarWidget::SideBarWidget (const QString & _title, const QPixmap & _icon, QWidget * _parent)
Definition at line 38 of file SideBarWidget.cpp.
References closeButtonClicked(), lmms::embed::getIconPixmap(), m_buttonSize, m_closeBtn, m_contents, m_icon, m_layout, and m_title.
Referenced by lmms::gui::FileBrowser::FileBrowser(), and lmms::gui::PluginBrowser::PluginBrowser().
~SideBarWidget()
lmms::gui::SideBarWidget::~SideBarWidget () override default
Member Function Documentation
addContentLayout()
void lmms::gui::SideBarWidget::addContentLayout (QLayout * _l) inline protected
Definition at line 75 of file SideBarWidget.h.
References m_layout.
addContentWidget()
void lmms::gui::SideBarWidget::addContentWidget (QWidget * _w) inline protected
Definition at line 70 of file SideBarWidget.h.
References m_layout.
Referenced by lmms::gui::FileBrowser::FileBrowser(), lmms::gui::PluginBrowser::PluginBrowser(), and lmms::gui::FileBrowser::addContentCheckBox().
closeButtonClicked
void lmms::gui::SideBarWidget::closeButtonClicked () signal
Referenced by SideBarWidget(), and lmms::gui::SideBar::appendTab().
contentParent()
QWidget * lmms::gui::SideBarWidget::contentParent () inline protected
Definition at line 65 of file SideBarWidget.h.
References m_contents.
Referenced by lmms::gui::FileBrowser::FileBrowser(), lmms::gui::PluginBrowser::PluginBrowser(), and lmms::gui::FileBrowser::addContentCheckBox().
contextMenuEvent()
void lmms::gui::SideBarWidget::contextMenuEvent (QContextMenuEvent *) inline override protected
Definition at line 61 of file SideBarWidget.h.
icon()
const QPixmap & lmms::gui::SideBarWidget::icon () const inline
Definition at line 46 of file SideBarWidget.h.
References m_icon.
Referenced by lmms::gui::SideBar::appendTab().
paintEvent()
void lmms::gui::SideBarWidget::paintEvent (QPaintEvent * _pe) override protected
Definition at line 59 of file SideBarWidget.cpp.
References lmms::gui::adjustedToPixelSize(), LARGE_FONT_SIZE, m_icon, and m_title.
resizeEvent()
void lmms::gui::SideBarWidget::resizeEvent (QResizeEvent * _re) override protected
Definition at line 82 of file SideBarWidget.cpp.
References m_closeBtn, and m_contents.
title()
const QString & lmms::gui::SideBarWidget::title () const inline
Definition at line 50 of file SideBarWidget.h.
References m_title.
Referenced by lmms::gui::FileBrowser::FileBrowser(), and lmms::gui::SideBar::appendTab().
Member Data Documentation
m_buttonSize
const QSize lmms::gui::SideBarWidget::m_buttonSize private
Definition at line 86 of file SideBarWidget.h.
Referenced by SideBarWidget().
m_closeBtn
QPushButton* lmms::gui::SideBarWidget::m_closeBtn private
Definition at line 85 of file SideBarWidget.h.
Referenced by SideBarWidget(), and resizeEvent().
m_contents
QWidget* lmms::gui::SideBarWidget::m_contents private
Definition at line 81 of file SideBarWidget.h.
Referenced by SideBarWidget(), contentParent(), and resizeEvent().
m_icon
QPixmap lmms::gui::SideBarWidget::m_icon private
Definition at line 84 of file SideBarWidget.h.
Referenced by SideBarWidget(), icon(), and paintEvent().
m_layout
QVBoxLayout* lmms::gui::SideBarWidget::m_layout private
Definition at line 82 of file SideBarWidget.h.
Referenced by SideBarWidget(), addContentLayout(), and addContentWidget().
m_title
QString lmms::gui::SideBarWidget::m_title private
Definition at line 83 of file SideBarWidget.h.
Referenced by SideBarWidget(), paintEvent(), and title().
The documentation for this class was generated from the following files:
include/SideBarWidget.h
src/gui/SideBarWidget.cpp