LMMS: hiir::Downsampler2xNeon< NC > Class Template Reference
hiir::Downsampler2xNeon< NC > Class Template Reference
#include <Downsampler2xNeon.h>
Public Types
typedef float DataType
Public Member Functions
Downsampler2xNeon () noexcept
Downsampler2xNeon (const Downsampler2xNeon< NC > &other)=default
Downsampler2xNeon (Downsampler2xNeon< NC > &&other)=default
~Downsampler2xNeon ()=default
void clear_buffers () noexcept
Downsampler2xNeon< NC > & operator= (const Downsampler2xNeon< NC > &other)=default
Downsampler2xNeon< NC > & operator= (Downsampler2xNeon< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
template<typename FL, typename FH>
long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
void process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE float process_sample (const float in_ptr[2]) noexcept
hiir_FORCEINLINE void process_sample_split (float &low, float &high, const float in_ptr[2]) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = -1
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataNeonV2, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Downsampler2xNeon< NC > &other) const =delete
bool operator== (const Downsampler2xNeon< NC > &other) const =delete
template<typename FL, typename FH>
hiir_FORCEINLINE long process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Static Private Member Functions
static hiir_FORCEINLINE void bypass (float *, float32x4_t, float32x4_t, float32x4_t) noexcept
static hiir_FORCEINLINE void store_high (float *ptr, float32x4_t even, float32x4_t odd, float32x4_t half) noexcept
static hiir_FORCEINLINE void store_low (float *ptr, float32x4_t even, float32x4_t odd, float32x4_t half) noexcept
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _nbr_stages
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::Downsampler2xNeon< NC >
Definition at line 50 of file Downsampler2xNeon.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Downsampler2xNeon< NC >::DataType
Definition at line 59 of file Downsampler2xNeon.h.
Filter
template<int NC> typedef std::array<StageDataNeonV2, _nbr_stages + 1> hiir::Downsampler2xNeon< NC >::Filter private
Definition at line 103 of file Downsampler2xNeon.h.
Constructor & Destructor Documentation
Downsampler2xNeon() [1/3]
template<int NC> hiir::Downsampler2xNeon< NC >::Downsampler2xNeon () noexcept
Definition at line 60 of file Downsampler2xNeon.hpp.
References _filter, _nbr_stages, _stage_width, clear_buffers(), i, NBR_COEFS, pos, and hiir::storea().
Referenced by Downsampler2xNeon(), Downsampler2xNeon(), ~Downsampler2xNeon(), operator=(), and operator=().
Downsampler2xNeon() [2/3]
template<int NC> hiir::Downsampler2xNeon< NC >::Downsampler2xNeon (const Downsampler2xNeon< NC > & other) default
References Downsampler2xNeon().
Downsampler2xNeon() [3/3]
template<int NC> hiir::Downsampler2xNeon< NC >::Downsampler2xNeon (Downsampler2xNeon< NC > && other) default
References Downsampler2xNeon().
~Downsampler2xNeon()
template<int NC> hiir::Downsampler2xNeon< NC >::~Downsampler2xNeon () default
References Downsampler2xNeon().
Member Function Documentation
bypass()
template<int NC> hiir_FORCEINLINE void hiir::Downsampler2xNeon< NC >::bypass (float * , float32x4_t , float32x4_t , float32x4_t) inline static private noexcept
Definition at line 114 of file Downsampler2xNeon.h.
References bypass().
Referenced by bypass(), and process_block().
clear_buffers()
template<int NC> void hiir::Downsampler2xNeon< NC >::clear_buffers () noexcept
Definition at line 266 of file Downsampler2xNeon.hpp.
References _filter, _nbr_stages, i, and hiir::storea().
Referenced by Downsampler2xNeon(), and operator=().
operator!=()
template<int NC> bool hiir::Downsampler2xNeon< NC >::operator!= (const Downsampler2xNeon< NC > & other) const private delete
operator=() [1/2]
template<int NC> Downsampler2xNeon< NC > & hiir::Downsampler2xNeon< NC >::operator= (const Downsampler2xNeon< NC > & other) default
References Downsampler2xNeon().
operator=() [2/2]
template<int NC> Downsampler2xNeon< NC > & hiir::Downsampler2xNeon< NC >::operator= (Downsampler2xNeon< NC > && other) default
References Downsampler2xNeon(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_split(), process_sample(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::Downsampler2xNeon< NC >::operator== (const Downsampler2xNeon< NC > & other) const private delete
process_block()
template<int NC> void hiir::Downsampler2xNeon< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 153 of file Downsampler2xNeon.hpp.
References bypass(), pos, process_block_quad(), process_sample(), and store_low().
Referenced by operator=().
process_block_quad() [1/2]
template<int NC> template<typename FL, typename FH> hiir_FORCEINLINE long hiir::Downsampler2xNeon< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) private noexcept
References hiir_FORCEINLINE, process_block_quad(), store_high(), and store_low().
Referenced by process_block(), process_block_quad(), and process_block_split().
process_block_quad() [2/2]
template<int NC> template<typename FL, typename FH> long hiir::Downsampler2xNeon< NC >::process_block_quad (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl, FL fnc_l, FH fnc_h) noexcept
Definition at line 293 of file Downsampler2xNeon.hpp.
References _filter, hiir::load4u(), pos, and hiir::StageProcNeonV2< CUR >::process_sample_pos().
process_block_split()
template<int NC> void hiir::Downsampler2xNeon< NC >::process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 233 of file Downsampler2xNeon.hpp.
References pos, process_block_quad(), process_sample_split(), store_high(), and store_low().
Referenced by operator=().
process_sample()
template<int NC> float hiir::Downsampler2xNeon< NC >::process_sample (const float in_ptr[2]) noexcept
Definition at line 120 of file Downsampler2xNeon.hpp.
References _filter, hiir::load2u(), and hiir::StageProcNeonV2< CUR >::process_sample_pos().
Referenced by operator=(), and process_block().
process_sample_split()
template<int NC> void hiir::Downsampler2xNeon< NC >::process_sample_split (float & low, float & high, const float in_ptr[2]) noexcept
Definition at line 193 of file Downsampler2xNeon.hpp.
References _filter, hiir::load2u(), and hiir::StageProcNeonV2< CUR >::process_sample_pos().
Referenced by operator=(), and process_block_split().
set_coefs()
template<int NC> void hiir::Downsampler2xNeon< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 93 of file Downsampler2xNeon.hpp.
References _filter, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
store_high()
template<int NC> void hiir::Downsampler2xNeon< NC >::store_high (float * ptr, float32x4_t even, float32x4_t odd, float32x4_t half) static private noexcept
Definition at line 338 of file Downsampler2xNeon.hpp.
References hiir::storeu().
Referenced by process_block_quad(), and process_block_split().
store_low()
template<int NC> void hiir::Downsampler2xNeon< NC >::store_low (float * ptr, float32x4_t even, float32x4_t odd, float32x4_t half) static private noexcept
Definition at line 329 of file Downsampler2xNeon.hpp.
References hiir::storeu().
Referenced by process_block(), process_block_quad(), and process_block_split().
Member Data Documentation
_delay
template<int NC> double hiir::Downsampler2xNeon< NC >::_delay = -1 static constexpr
Definition at line 62 of file Downsampler2xNeon.h.
_filter
template<int NC> Filter hiir::Downsampler2xNeon< NC >::_filter private
Definition at line 116 of file Downsampler2xNeon.h.
Referenced by Downsampler2xNeon(), clear_buffers(), process_block_quad(), process_sample(), process_sample_split(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Downsampler2xNeon< NC >::_nbr_chn = 1 static constexpr
Definition at line 60 of file Downsampler2xNeon.h.
_nbr_stages
template<int NC> int hiir::Downsampler2xNeon< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 99 of file Downsampler2xNeon.h.
Referenced by Downsampler2xNeon(), and clear_buffers().
_stage_width
template<int NC> int hiir::Downsampler2xNeon< NC >::_stage_width = 2 static constexpr private
Definition at line 98 of file Downsampler2xNeon.h.
Referenced by Downsampler2xNeon(), and set_coefs().
NBR_COEFS
template<int NC> int hiir::Downsampler2xNeon< NC >::NBR_COEFS = NC static constexpr
Definition at line 61 of file Downsampler2xNeon.h.
Referenced by Downsampler2xNeon(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Downsampler2xNeon.h
src/3rdparty/hiir/hiir/Downsampler2xNeon.hpp