LMMS: hiir::StageProc4Neon< REMAINING > Class Template Reference
hiir::StageProc4Neon< REMAINING > Class Template Reference
#include <StageProc4Neon.h>
Public Member Functions
void process_sample_neg (const int nbr_coefs, float32x4_t &spl_0, float32x4_t &spl_1, StageDataNeonV4 *stage_arr) noexcept
void process_sample_neg (const int nbr_coefs, float32x4_t &spl_0, float32x4_t &spl_1, StageDataNeonV4 *stage_arr) noexcept
void process_sample_pos (const int nbr_coefs, float32x4_t &spl_0, float32x4_t &spl_1, StageDataNeonV4 *stage_arr) noexcept
void process_sample_pos (const int nbr_coefs, float32x4_t &spl_0, float32x4_t &spl_1, StageDataNeonV4 *stage_arr) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (const int nbr_coefs, float32x4_t &spl_0, float32x4_t &spl_1, StageDataNeonV4 *stage_arr) noexcept
static hiir_FORCEINLINE void process_sample_pos (const int nbr_coefs, float32x4_t &spl_0, float32x4_t &spl_1, StageDataNeonV4 *stage_arr) noexcept
Private Member Functions
StageProc4Neon ()=delete
StageProc4Neon (const StageProc4Neon< REMAINING > &other)=delete
StageProc4Neon (StageProc4Neon< REMAINING > &&other)=delete
~StageProc4Neon ()=delete
bool operator!= (const StageProc4Neon< REMAINING > &other) const =delete
StageProc4Neon< REMAINING > & operator= (const StageProc4Neon< REMAINING > &other)=delete
StageProc4Neon< REMAINING > & operator= (StageProc4Neon< REMAINING > &&other)=delete
bool operator== (const StageProc4Neon< REMAINING > &other) const =delete
Detailed Description
template<int REMAINING>
class hiir::StageProc4Neon< REMAINING >
Definition at line 45 of file StageProc4Neon.h.
Constructor & Destructor Documentation
StageProc4Neon() [1/3]
template<int REMAINING> hiir::StageProc4Neon< REMAINING >::StageProc4Neon () private delete
Referenced by process_sample_neg(), and process_sample_pos().
StageProc4Neon() [2/3]
template<int REMAINING> hiir::StageProc4Neon< REMAINING >::StageProc4Neon (const StageProc4Neon< REMAINING > & other) private delete
StageProc4Neon() [3/3]
template<int REMAINING> hiir::StageProc4Neon< REMAINING >::StageProc4Neon (StageProc4Neon< REMAINING > && other) private delete
~StageProc4Neon()
template<int REMAINING> hiir::StageProc4Neon< REMAINING >::~StageProc4Neon () private delete
Member Function Documentation
operator!=()
template<int REMAINING> bool hiir::StageProc4Neon< REMAINING >::operator!= (const StageProc4Neon< REMAINING > & other) const private delete
operator=() [1/2]
template<int REMAINING> StageProc4Neon< REMAINING > & hiir::StageProc4Neon< REMAINING >::operator= (const StageProc4Neon< REMAINING > & other) private delete
operator=() [2/2]
template<int REMAINING> StageProc4Neon< REMAINING > & hiir::StageProc4Neon< REMAINING >::operator= (StageProc4Neon< REMAINING > && other) private delete
operator==()
template<int REMAINING> bool hiir::StageProc4Neon< REMAINING >::operator== (const StageProc4Neon< REMAINING > & other) const private delete
process_sample_neg() [1/3]
template<int REMAINING> void hiir::StageProc4Neon< REMAINING >::process_sample_neg (const int nbr_coefs, float32x4_t & spl_0, float32x4_t & spl_1, StageDataNeonV4 * stage_arr) static noexcept
Definition at line 128 of file StageProc4Neon.hpp.
References StageProc4Neon(), hiir::load4a(), process_sample_neg(), and hiir::storea().
Referenced by hiir::PhaseHalfPi4Neon< NC >::process_block(), hiir::PhaseHalfPi4Neon< NC >::process_sample(), and process_sample_neg().
process_sample_neg() [2/3]
void hiir::StageProc4Neon< 0 >::process_sample_neg (const int nbr_coefs, float32x4_t & spl_0, float32x4_t & spl_1, StageDataNeonV4 * stage_arr) inline noexcept
Definition at line 119 of file StageProc4Neon.hpp.
References hiir::storea().
process_sample_neg() [3/3]
void hiir::StageProc4Neon< 1 >::process_sample_neg (const int nbr_coefs, float32x4_t & spl_0, float32x4_t & spl_1, StageDataNeonV4 * stage_arr) inline noexcept
Definition at line 102 of file StageProc4Neon.hpp.
References hiir::load4a(), and hiir::storea().
process_sample_pos() [1/3]
template<int REMAINING> void hiir::StageProc4Neon< REMAINING >::process_sample_pos (const int nbr_coefs, float32x4_t & spl_0, float32x4_t & spl_1, StageDataNeonV4 * stage_arr) static noexcept
Definition at line 70 of file StageProc4Neon.hpp.
References StageProc4Neon(), hiir::load4a(), process_sample_pos(), and hiir::storea().
Referenced by hiir::HalfBand4Neon< NC >::process_2_paths(), hiir::HalfBand4Neon< NC >::process_block_2_paths(), hiir::Downsampler2x4Neon< NC >::process_sample(), hiir::Upsampler2x4Neon< NC >::process_sample(), process_sample_pos(), and hiir::Downsampler2x4Neon< NC >::process_sample_split().
process_sample_pos() [2/3]
void hiir::StageProc4Neon< 0 >::process_sample_pos (const int nbr_coefs, float32x4_t & spl_0, float32x4_t & spl_1, StageDataNeonV4 * stage_arr) inline noexcept
Definition at line 59 of file StageProc4Neon.hpp.
References hiir::storea().
process_sample_pos() [3/3]
void hiir::StageProc4Neon< 1 >::process_sample_pos (const int nbr_coefs, float32x4_t & spl_0, float32x4_t & spl_1, StageDataNeonV4 * stage_arr) inline noexcept
Definition at line 39 of file StageProc4Neon.hpp.
References hiir::load4a(), and hiir::storea().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProc4Neon.h
src/3rdparty/hiir/hiir/StageProc4Neon.hpp