LMMS: src/3rdparty/jack2/common/JackAPI.cpp File Reference
JackAPI.cpp File Reference
#include <inttypes.h>
#include "JackClient.h"
#include "JackError.h"
#include "JackGraphManager.h"
#include "JackEngineControl.h"
#include "JackClientControl.h"
#include "JackGlobals.h"
#include "JackTime.h"
#include "JackPortType.h"
#include "JackMetadata.h"
#include <math.h>
Macros
#define __STDC_FORMAT_MACROS 1
Typedefs
typedef void(* print_function) (const char *)
typedef void *(* thread_routine) (void *)
Functions
static bool CheckBufferSize (jack_nframes_t buffer_size)
static bool CheckPort (jack_port_id_t port_index)
LIB_EXPORT int jack_acquire_real_time_scheduling (jack_native_thread_t thread, int priority)
Attempt to enable realtime scheduling for a thread.
LIB_EXPORT int jack_activate (jack_client_t *client)
Tell the Jack server that the program is ready to start processing audio.
LIB_EXPORT int jack_client_create_thread (jack_client_t *client, jack_native_thread_t *thread, int priority, int realtime, thread_routine routine, void *arg)
Create a thread for JACK or one of its clients.
LIB_EXPORT char * jack_client_get_uuid (jack_client_t *client)
Get the assigned uuid for client.
LIB_EXPORT int jack_client_has_session_callback (jack_client_t *client, const char *client_name)
Find out whether a client has set up a session callback.
LIB_EXPORT int jack_client_kill_thread (jack_client_t *client, jack_native_thread_t thread)
Kill the thread.
LIB_EXPORT int jack_client_max_real_time_priority (jack_client_t *)
LIB_EXPORT int jack_client_name_size (void)
LIB_EXPORT jack_client_t * jack_client_new (const char *client_name)
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS
jack_client_t * jack_client_new_aux (const char *client_name, jack_options_t options, jack_status_t *status)
LIB_EXPORT jack_client_t * jack_client_open (const char *client_name, jack_options_t options, jack_status_t *status,...)
Open an external client session with a JACK server.
LIB_EXPORT int jack_client_real_time_priority (jack_client_t *)
LIB_EXPORT int jack_client_stop_thread (jack_client_t *client, jack_native_thread_t thread)
Stop the thread, waiting for the thread handler to terminate.
LIB_EXPORT jack_native_thread_t jack_client_thread_id (jack_client_t *)
LIB_EXPORT jack_uuid_t jack_client_uuid_generate ()
LIB_EXPORT int jack_connect (jack_client_t *, const char *source_port, const char *destination_port)
Establish a connection between two ports.
LIB_EXPORT float jack_cpu_load (jack_client_t *client)
LIB_EXPORT void jack_cycle_signal (jack_client_t *, int status)
Signal next clients in the graph.
LIB_EXPORT jack_nframes_t jack_cycle_wait (jack_client_t *)
Wait until this JACK client should process data.
LIB_EXPORT int jack_deactivate (jack_client_t *client)
Tell the Jack server to remove this client from the process graph.
LIB_EXPORT int jack_disconnect (jack_client_t *, const char *source_port, const char *destination_port)
Remove a connection between two ports.
LIB_EXPORT int jack_drop_real_time_scheduling (jack_native_thread_t thread)
Drop realtime scheduling for a thread.
LIB_EXPORT int jack_engine_takeover_timebase (jack_client_t *)
Old-style interface to become the timebase for the entire JACK subsystem.
LIB_EXPORT jack_nframes_t jack_frame_time (const jack_client_t *)
LIB_EXPORT jack_nframes_t jack_frames_since_cycle_start (const jack_client_t *)
LIB_EXPORT jack_time_t jack_frames_to_time (const jack_client_t *client, jack_nframes_t frames)
LIB_EXPORT void jack_free (void *ptr)
The free function to be used on memory returned by jack_port_get_connections, jack_port_get_all_connections, jack_get_ports and jack_get_internal_client_name functions.
LIB_EXPORT void jack_free_description (jack_description_t *desc, int free_description_itself)
Free a description.
LIB_EXPORT int jack_get_all_properties (jack_description_t **descs)
Get descriptions for all subjects with metadata.
LIB_EXPORT jack_nframes_t jack_get_buffer_size (jack_client_t *)
LIB_EXPORT char * jack_get_client_name (jack_client_t *client)
LIB_EXPORT char * jack_get_client_name_by_uuid (jack_client_t *ext_client, const char *client_uuid)
Get the client name for a session_id.
LIB_EXPORT jack_nframes_t jack_get_current_transport_frame (const jack_client_t *client)
Return an estimate of the current transport frame, including any time elapsed since the last transport positional update.
LIB_EXPORT int jack_get_cycle_times (const jack_client_t *client, jack_nframes_t *current_frames, jack_time_t *current_usecs, jack_time_t *next_usecs, float *period_usecs)
This function may only be used from the process callback.
LIB_EXPORT char * jack_get_internal_client_name (jack_client_t *client, jack_intclient_t intclient)
Get an internal client's name.
LIB_EXPORT float jack_get_max_delayed_usecs (jack_client_t *client)
LIB_EXPORT const char ** jack_get_ports (jack_client_t *, const char *port_name_pattern, const char *type_name_pattern, unsigned long flags)
LIB_EXPORT int jack_get_properties (jack_uuid_t subject, jack_description_t *desc)
Get a description of subject.
LIB_EXPORT int jack_get_property (jack_uuid_t subject, const char *key, char **value, char **type)
Get a property on subject.
LIB_EXPORT jack_nframes_t jack_get_sample_rate (jack_client_t *)
LIB_EXPORT jack_time_t jack_get_time ()
LIB_EXPORT void jack_get_transport_info (jack_client_t *client, jack_transport_info_t *tinfo)
Gets the current transport info structure (deprecated).
LIB_EXPORT char * jack_get_uuid_for_client_name (jack_client_t *ext_client, const char *client_name)
Get the session ID for a client name.
LIB_EXPORT void jack_get_version (int *major_ptr, int *minor_ptr, int *micro_ptr, int *proto_ptr)
Note: More documentation can be found in jack/types.h.
LIB_EXPORT const char * jack_get_version_string ()
Call this function to get version of the JACK, in form of a string.
LIB_EXPORT float jack_get_xrun_delayed_usecs (jack_client_t *client)
LIB_EXPORT void jack_internal_client_close (const char *client_name)
Remove an internal client from a JACK server.
LIB_EXPORT jack_intclient_t jack_internal_client_handle (jack_client_t *client, const char *client_name, jack_status_t *status)
Return the jack_intclient_t handle for an internal client running in the JACK server.
LIB_EXPORT jack_intclient_t jack_internal_client_load (jack_client_t *client, const char *client_name, jack_options_t options, jack_status_t *status,...)
Load an internal client into the JACK server.
static jack_intclient_t jack_internal_client_load_aux (jack_client_t *ext_client, const char *client_name, jack_options_t options, jack_status_t *status, va_list ap)
LIB_EXPORT int jack_internal_client_new (const char *client_name, const char *load_name, const char *load_init)
Load an internal client into the Jack server.
LIB_EXPORT jack_status_t jack_internal_client_unload (jack_client_t *client, jack_intclient_t intclient)
Unload an internal client from a JACK server.
LIB_EXPORT int jack_is_realtime (jack_client_t *client)
LIB_EXPORT jack_nframes_t jack_last_frame_time (const jack_client_t *client)
LIB_EXPORT void jack_on_info_shutdown (jack_client_t *client, JackInfoShutdownCallback shutdown_callback, void *arg)
LIB_EXPORT void jack_on_shutdown (jack_client_t *client, JackShutdownCallback shutdown_callback, void *arg)
LIB_EXPORT jack_port_t * jack_port_by_id (jack_client_t *client, jack_port_id_t port_id)
LIB_EXPORT jack_port_t * jack_port_by_name (jack_client_t *, const char *port_name)
LIB_EXPORT int jack_port_connected (const jack_port_t *port)
LIB_EXPORT int jack_port_connected_to (const jack_port_t *port, const char *port_name)
LIB_EXPORT int jack_port_disconnect (jack_client_t *, jack_port_t *)
Perform the same function as jack_disconnect() using port handles rather than names.
LIB_EXPORT int jack_port_ensure_monitor (jack_port_t *port, int onoff)
If JackPortCanMonitor is set for a port, this function turns on input monitoring if it was off, and turns it off if only one request has been made to turn it on.
LIB_EXPORT int jack_port_flags (const jack_port_t *port)
LIB_EXPORT int jack_port_get_aliases (const jack_port_t *port, char *const aliases[2])
Get any aliases known for @port.
LIB_EXPORT const char ** jack_port_get_all_connections (const jack_client_t *client, const jack_port_t *port)
LIB_EXPORT void * jack_port_get_buffer (jack_port_t *, jack_nframes_t)
This returns a pointer to the memory area associated with the specified port.
LIB_EXPORT const char ** jack_port_get_connections (const jack_port_t *port)
LIB_EXPORT jack_nframes_t jack_port_get_latency (jack_port_t *port)
LIB_EXPORT void jack_port_get_latency_range (jack_port_t *port, jack_latency_callback_mode_t mode, jack_latency_range_t *range)
return the latency range defined by mode for port, in frames.
LIB_EXPORT jack_nframes_t jack_port_get_total_latency (jack_client_t *, jack_port_t *port)
The maximum of the sum of the latencies in every connection path that can be drawn between the port and other ports with the JackPortIsTerminal flag set.
LIB_EXPORT int jack_port_is_mine (const jack_client_t *, const jack_port_t *port)
LIB_EXPORT int jack_port_monitoring_input (jack_port_t *port)
LIB_EXPORT const char * jack_port_name (const jack_port_t *port)
LIB_EXPORT int jack_port_name_size (void)
LIB_EXPORT jack_port_t * jack_port_register (jack_client_t *client, const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
Create a new port for the client.
LIB_EXPORT int jack_port_rename (jack_client_t *client, jack_port_t *port, const char *port_name)
Modify a port's short name.
LIB_EXPORT int jack_port_request_monitor (jack_port_t *port, int onoff)
If JackPortCanMonitor is set for this port, turn input monitoring on or off.
LIB_EXPORT int jack_port_request_monitor_by_name (jack_client_t *client, const char *port_name, int onoff)
If JackPortCanMonitor is set for this port_name, turn input monitoring on or off.
LIB_EXPORT int jack_port_set_alias (jack_port_t *port, const char *alias)
Set alias as an alias for port.
LIB_EXPORT void jack_port_set_latency (jack_port_t *, jack_nframes_t)
The port latency is zero by default.
LIB_EXPORT void jack_port_set_latency_range (jack_port_t *port, jack_latency_callback_mode_t mode, jack_latency_range_t *range)
set the minimum and maximum latencies defined by mode for port, in frames.
LIB_EXPORT int jack_port_set_name (jack_port_t *port, const char *port_name)
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS
LIB_EXPORT const char * jack_port_short_name (const jack_port_t *port)
LIB_EXPORT int jack_port_tie (jack_port_t *src, jack_port_t *dst)
LIB_EXPORT const char * jack_port_type (const jack_port_t *port)
LIB_EXPORT size_t jack_port_type_get_buffer_size (jack_client_t *client, const char *port_type)
LIB_EXPORT jack_port_type_id_t jack_port_type_id (const jack_port_t *port)
LIB_EXPORT int jack_port_type_size (void)
LIB_EXPORT int jack_port_unregister (jack_client_t *, jack_port_t *)
Remove the port from the client, disconnecting any existing connections.
LIB_EXPORT int jack_port_unset_alias (jack_port_t *port, const char *alias)
Remove alias as an alias for port.
LIB_EXPORT int jack_port_untie (jack_port_t *port)
LIB_EXPORT jack_uuid_t jack_port_uuid (const jack_port_t *)
LIB_EXPORT jack_uuid_t jack_port_uuid_generate (uint32_t port_id)
LIB_EXPORT int jack_recompute_total_latencies (jack_client_t *)
Request a complete recomputation of all port latencies.
LIB_EXPORT int jack_recompute_total_latency (jack_client_t *, jack_port_t *port)
Request a complete recomputation of a port's total latency.
LIB_EXPORT int jack_release_timebase (jack_client_t *client)
Called by the timebase master to release itself from that responsibility.
LIB_EXPORT int jack_remove_all_properties (jack_client_t *client)
Remove all properties.
LIB_EXPORT int jack_remove_properties (jack_client_t *client, jack_uuid_t subject)
Remove all properties on a subject.
LIB_EXPORT int jack_remove_property (jack_client_t *client, jack_uuid_t subject, const char *key)
Remove a single property on a subject.
LIB_EXPORT int jack_reserve_client_name (jack_client_t *ext_client, const char *name, const char *uuid)
Reserve a client name and associate it with a UUID.
LIB_EXPORT void jack_reset_max_delayed_usecs (jack_client_t *client)
Reset the maximum delay counter.
LIB_EXPORT void jack_session_commands_free (jack_session_command_t *cmds)
Free the memory allocated by a session command.
LIB_EXPORT void jack_session_event_free (jack_session_event_t *ev)
Free memory used by a jack_session_event_t.
LIB_EXPORT jack_session_command_t * jack_session_notify (jack_client_t *ext_client, const char *target, jack_session_event_type_t ev_type, const char *path)
Send an event to all clients listening for session callbacks.
LIB_EXPORT int jack_session_reply (jack_client_t *ext_client, jack_session_event_t *event)
Reply to a session event.
LIB_EXPORT int jack_set_buffer_size (jack_client_t *client, jack_nframes_t nframes)
Change the buffer size passed to the process_callback.
LIB_EXPORT int jack_set_buffer_size_callback (jack_client_t *client, JackBufferSizeCallback bufsize_callback, void *arg)
Tell JACK to call bufsize_callback whenever the size of the the buffer that will be passed to the process_callback is about to change.
LIB_EXPORT int jack_set_client_registration_callback (jack_client_t *, JackClientRegistrationCallback registration_callback, void *arg)
Tell the JACK server to call client_registration_callback whenever a client is registered or unregistered, passing arg as a parameter.
LIB_EXPORT void jack_set_error_function (print_function)
LIB_EXPORT int jack_set_freewheel (jack_client_t *client, int onoff)
Start/Stop JACK's "freewheel" mode.
LIB_EXPORT int jack_set_freewheel_callback (jack_client_t *client, JackFreewheelCallback freewheel_callback, void *arg)
Tell the Jack server to call freewheel_callback whenever we enter or leave "freewheel" mode, passing arg as the second argument.
LIB_EXPORT int jack_set_graph_order_callback (jack_client_t *, JackGraphOrderCallback graph_callback, void *)
Tell the JACK server to call graph_callback whenever the processing graph is reordered, passing arg as a parameter.
LIB_EXPORT void jack_set_info_function (print_function)
LIB_EXPORT int jack_set_latency_callback (jack_client_t *client, JackLatencyCallback latency_callback, void *arg)
Tell the Jack server to call latency_callback whenever it is necessary to recompute the latencies for some or all Jack ports.
LIB_EXPORT int jack_set_port_connect_callback (jack_client_t *, JackPortConnectCallback connect_callback, void *arg)
Tell the JACK server to call connect_callback whenever a port is connected or disconnected, passing arg as a parameter.
LIB_EXPORT int jack_set_port_registration_callback (jack_client_t *, JackPortRegistrationCallback registration_callback, void *arg)
Tell the JACK server to call registration_callback whenever a port is registered or unregistered, passing arg as a parameter.
LIB_EXPORT int jack_set_port_rename_callback (jack_client_t *, JackPortRenameCallback rename_callback, void *arg)
Tell the JACK server to call rename_callback whenever a port is renamed, passing arg as a parameter.
LIB_EXPORT int jack_set_process_callback (jack_client_t *client, JackProcessCallback process_callback, void *arg)
Tell the Jack server to call process_callback whenever there is work be done, passing arg as the second argument.
LIB_EXPORT int jack_set_process_thread (jack_client_t *client, JackThreadCallback fun, void *arg)
Tell the Jack server to call thread_callback in the RT thread.
LIB_EXPORT int jack_set_property (jack_client_t *, jack_uuid_t subject, const char *key, const char *value, const char *type)
Set a property on subject.
LIB_EXPORT int jack_set_property_change_callback (jack_client_t *client, JackPropertyChangeCallback callback, void *arg)
Arrange for client to call callback whenever a property is created, changed or deleted.
LIB_EXPORT int jack_set_sample_rate_callback (jack_client_t *client, JackSampleRateCallback srate_callback, void *arg)
Tell the Jack server to call srate_callback whenever the system sample rate changes.
LIB_EXPORT int jack_set_session_callback (jack_client_t *ext_client, JackSessionCallback session_callback, void *arg)
Tell the JACK server to call session_callback when a session event is to be delivered.
LIB_EXPORT int jack_set_sync_callback (jack_client_t *client, JackSyncCallback sync_callback, void *arg)
Register (or unregister) as a slow-sync client, one that cannot respond immediately to transport position changes.
LIB_EXPORT int jack_set_sync_timeout (jack_client_t *client, jack_time_t timeout)
Set the timeout value for slow-sync clients.
LIB_EXPORT void jack_set_thread_creator (jack_thread_creator_t jtc)
This function can be used in very very specialized cases where it is necessary that client threads created by JACK are created by something other than pthread_create().
LIB_EXPORT int jack_set_thread_init_callback (jack_client_t *client, JackThreadInitCallback thread_init_callback, void *arg)
Tell JACK to call thread_init_callback once just after the creation of the thread in which all other callbacks will be handled.
LIB_EXPORT int jack_set_timebase_callback (jack_client_t *client, int conditional, JackTimebaseCallback timebase_callback, void *arg)
Register as timebase master for the JACK subsystem.
LIB_EXPORT void jack_set_transport_info (jack_client_t *client, jack_transport_info_t *tinfo)
Set the transport info structure (deprecated).
LIB_EXPORT int jack_set_xrun_callback (jack_client_t *, JackXRunCallback xrun_callback, void *arg)
Tell the JACK server to call xrun_callback whenever there is a xrun, passing arg as a parameter.
LIB_EXPORT jack_nframes_t jack_thread_wait (jack_client_t *client, int status)
\bold THIS FUNCTION IS DEPRECATED AND SHOULD NOT BE USED IN NEW JACK CLIENTS.
LIB_EXPORT jack_nframes_t jack_time_to_frames (const jack_client_t *client, jack_time_t usecs)
LIB_EXPORT int jack_transport_locate (jack_client_t *client, jack_nframes_t frame)
Reposition the transport to a new frame number.
LIB_EXPORT jack_transport_state_t jack_transport_query (const jack_client_t *client, jack_position_t *pos)
Query the current transport state and position.
LIB_EXPORT int jack_transport_reposition (jack_client_t *client, const jack_position_t *pos)
Request a new transport position.
LIB_EXPORT void jack_transport_start (jack_client_t *client)
Start the JACK transport rolling.
LIB_EXPORT void jack_transport_stop (jack_client_t *client)
Stop the JACK transport.
LIB_EXPORT void jack_uuid_clear (jack_uuid_t *)
LIB_EXPORT int jack_uuid_compare (jack_uuid_t, jack_uuid_t)
LIB_EXPORT void jack_uuid_copy (jack_uuid_t *dst, jack_uuid_t src)
LIB_EXPORT int jack_uuid_empty (jack_uuid_t)
LIB_EXPORT int jack_uuid_parse (const char *buf, jack_uuid_t *)
LIB_EXPORT uint32_t jack_uuid_to_index (jack_uuid_t)
LIB_EXPORT void jack_uuid_unparse (jack_uuid_t, char buf[JACK_UUID_STRING_SIZE])
static void WaitGraphChange ()
Macro Definition Documentation
__STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS 1
Definition at line 21 of file JackAPI.cpp.
Typedef Documentation
print_function
typedef void(* print_function) (const char *)
Definition at line 41 of file JackAPI.cpp.
thread_routine
typedef void *(* thread_routine) (void *)
Definition at line 42 of file JackAPI.cpp.
Function Documentation
CheckBufferSize()
bool CheckBufferSize (jack_nframes_t buffer_size) inline static
Definition at line 300 of file JackAPI.cpp.
References BUFFER_SIZE_MAX.
Referenced by jack_set_buffer_size().
CheckPort()
bool CheckPort (jack_port_id_t port_index) inline static
Definition at line 295 of file JackAPI.cpp.
References PORT_NUM_MAX.
Referenced by jack_port_connected(), jack_port_connected_to(), jack_port_disconnect(), jack_port_ensure_monitor(), jack_port_flags(), jack_port_get_aliases(), jack_port_get_all_connections(), jack_port_get_buffer(), jack_port_get_connections(), jack_port_get_latency(), jack_port_get_latency_range(), jack_port_get_total_latency(), jack_port_is_mine(), jack_port_monitoring_input(), jack_port_name(), jack_port_rename(), jack_port_request_monitor(), jack_port_request_monitor_by_name(), jack_port_set_alias(), jack_port_set_latency(), jack_port_set_latency_range(), jack_port_short_name(), jack_port_tie(), jack_port_type(), jack_port_type_id(), jack_port_unregister(), jack_port_unset_alias(), jack_port_untie(), jack_port_uuid(), and jack_recompute_total_latency().
jack_client_new_aux()
jack_client_t * jack_client_new_aux (const char * client_name, jack_options_t options, jack_status_t * status)
Definition at line 61 of file JackLibAPI.cpp.
References client(), Jack::JackLibGlobals::Destroy(), Jack::JackServerGlobals::Destroy(), Jack::JackServerGlobals::fInstance, Jack::GetSynchroTable(), Jack::JackLibGlobals::Init(), Jack::JackServerGlobals::Init(), JACK_DEBUG, jack_error, jack_log(), jack_varargs_init(), JackFailure, JackInvalidOption, JackOpenOptions, JackServerError, jack_varargs_t::server_name, jack_varargs_t::session_id, and try_start_server().
Referenced by jack_client_new().
jack_client_uuid_generate()
LIB_EXPORT jack_uuid_t jack_client_uuid_generate ()
Definition at line 2087 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by Jack::JackDriver::JackDriver(), Jack::JackEngine::ClientExternalOpen(), and Jack::JackEngine::SessionNotify().
jack_free()
LIB_EXPORT void jack_free (void * ptr)
The free function to be used on memory returned by jack_port_get_connections, jack_port_get_all_connections, jack_get_ports and jack_get_internal_client_name functions.
This is MANDATORY on Windows when otherwise all nasty runtime version related crashes can occur. Developers are strongly encouraged to use this function instead of the standard "free" function in new code.
Parameters
ptr the memory pointer to be deallocated.
Definition at line 1920 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), and LIB_EXPORT.
Referenced by Jack::JackAudioAdapter::ConnectPorts(), Jack::JackNetMaster::ConnectPorts(), Jack::JackProxyDriver::ConnectPorts(), Jack::JackNetMasterManager::CountIO(), Jack::JackProxyDriver::CountIO(), jack_set_info_function(), Jack::JackProxyDriver::LoadSymbols(), main(), Jack::JackProxyDriver::PROXY_DEF_SYMBOL(), Jack::JackNetMaster::SaveConnections(), and Jack::JackSapaProxy::Setup().
jack_get_internal_client_name()
LIB_EXPORT char * jack_get_internal_client_name (jack_client_t * client, jack_intclient_t intclient)
Get an internal client's name.
This is useful when JackUseExactName was not specified on jack_internal_client_load() and JackNameNotUnique status was returned. In that case, the actual name will differ from the client_name requested.
Parameters
client requesting JACK client's handle.
intclient handle returned from jack_internal_client_load() or jack_internal_client_handle().
Returns
NULL if unsuccessful, otherwise pointer to the internal client name obtained from the heap via malloc(). The caller should jack_free() this storage when no longer needed.
Definition at line 1809 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), CLIENT_NUM, jack_error, and LIB_EXPORT.
Referenced by main().
jack_get_max_delayed_usecs()
LIB_EXPORT float jack_get_max_delayed_usecs (jack_client_t * client)
Returns
the maximum delay reported by the backend since startup or reset. When compared to the period size in usecs, this can be used to estimate the ideal period size for a given setup.
Definition at line 1671 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fMaxDelayedUsecs, Jack::GetEngineControl(), jack_error, and LIB_EXPORT.
jack_get_version()
LIB_EXPORT void jack_get_version (int * major_ptr, int * minor_ptr, int * micro_ptr, int * proto_ptr)
Note: More documentation can be found in jack/types.h.
Call this function to get version of the JACK, in form of several numbers
Parameters
major_ptr pointer to variable receiving major version of JACK.
minor_ptr pointer to variable receiving minor version of JACK.
major_ptr pointer to variable receiving micro version of JACK.
major_ptr pointer to variable receiving protocol version of JACK.
Definition at line 1900 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), and LIB_EXPORT.
jack_get_version_string()
LIB_EXPORT const char * jack_get_version_string (void)
Call this function to get version of the JACK, in form of a string.
Returns
Human readable string describing JACK version being used.
Definition at line 1914 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), LIB_EXPORT, and VERSION.
jack_get_xrun_delayed_usecs()
LIB_EXPORT float jack_get_xrun_delayed_usecs (jack_client_t * client)
Returns
the delay in microseconds due to the most recent XRUN occurrence. This probably only makes sense when called from a JackXRunCallback defined using jack_set_xrun_callback().
Definition at line 1685 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fXrunDelayedUsecs, Jack::GetEngineControl(), jack_error, and LIB_EXPORT.
jack_internal_client_handle()
LIB_EXPORT jack_intclient_t jack_internal_client_handle (jack_client_t * client, const char * client_name, jack_status_t * status)
Return the jack_intclient_t handle for an internal client running in the JACK server.
Parameters
client requesting JACK client's handle.
client_name for the internal client of no more than jack_client_name_size() characters. The name scope is local to the current server.
status (if non-NULL) an address for JACK to return information from this operation. This status word is formed by OR-ing together the relevant JackStatus bits.
Returns
Opaque internal client handle if successful. If 0, the internal client was not found, and *status includes the JackNoSuchClient and JackFailure bits.
Definition at line 1825 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, and LIB_EXPORT.
Referenced by main().
jack_internal_client_load()
LIB_EXPORT jack_intclient_t jack_internal_client_load (jack_client_t * client, const char * client_name, jack_options_t options, jack_status_t * status, ...)
Load an internal client into the JACK server.
Internal clients run inside the JACK server process. They can use most of the same functions as external clients. Each internal client is built as a shared object module, which must declare jack_initialize() and jack_finish() entry points called at load and unload times. See inprocess.c for an example.
Parameters
client loading JACK client's handle.
client_name of at most jack_client_name_size() characters for the internal client to load. The name scope is local to the current server.
options formed by OR-ing together JackOptions bits. Only the JackLoadOptions bits are valid.
status (if non-NULL) an address for JACK to return information from the load operation. This status word is formed by OR-ing together the relevant JackStatus bits.
Optional parameters: depending on corresponding [options bits] additional parameters may follow status (in this order).
[JackLoadName] (char *) load_name is the shared object file from which to load the new internal client (otherwise use the client_name).
[JackLoadInit] (char *) load_init an arbitrary string passed to the internal client's jack_initialize() routine (otherwise NULL), of no more than JACK_LOAD_INIT_LIMIT bytes.
Returns
Opaque internal client handle if successful. If this is 0, the load operation failed, the internal client was not loaded, and *status includes the JackFailure bit.
Definition at line 1871 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_internal_client_load_aux(), and LIB_EXPORT.
Referenced by main().
jack_internal_client_load_aux()
jack_intclient_t jack_internal_client_load_aux (jack_client_t * ext_client, const char * client_name, jack_options_t options, jack_status_t * status, va_list ap) static
Definition at line 1842 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), jack_error, jack_varargs_parse(), JackFailure, JackInvalidOption, and JackLoadOptions.
Referenced by jack_internal_client_load().
jack_internal_client_unload()
LIB_EXPORT jack_status_t jack_internal_client_unload (jack_client_t * client, jack_intclient_t intclient)
Unload an internal client from a JACK server.
This calls the intclient's jack_finish() entry point then removes it. See inprocess.c for an example.
Parameters
client unloading JACK client's handle.
intclient handle returned from jack_internal_client_load() or jack_internal_client_handle().
Returns
0 if successful, otherwise JackStatus bits.
Definition at line 1882 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), CLIENT_NUM, jack_error, JackFailure, JackNoSuchClient, and LIB_EXPORT.
Referenced by main().
jack_is_realtime()
LIB_EXPORT int jack_is_realtime (jack_client_t * client)
Parameters
client pointer to JACK client structure.
Check if the JACK subsystem is running with -R (–realtime).
Returns
1 if JACK is running realtime, 0 otherwise
Definition at line 795 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::JackEngineControl::fRealTime, Jack::GetEngineControl(), jack_error, and LIB_EXPORT.
Referenced by main().
jack_port_uuid_generate()
LIB_EXPORT jack_uuid_t jack_port_uuid_generate (uint32_t port_id)
Definition at line 2095 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by jack_port_uuid(), Jack::JackEngine::PortSetDefaultMetadata(), and Jack::JackEngine::PortUnRegister().
jack_reset_max_delayed_usecs()
LIB_EXPORT void jack_reset_max_delayed_usecs (jack_client_t * client)
Reset the maximum delay counter.
This would be useful to estimate the effect that a change to the configuration of a running system (e.g. toggling kernel preemption) has on the delay experienced by JACK, without having to restart the JACK engine.
Definition at line 1699 of file JackAPI.cpp.
References Jack::JackGlobals::CheckContext(), client(), Jack::GetEngineControl(), jack_error, LIB_EXPORT, and Jack::JackEngineControl::ResetXRun().
jack_set_error_function()
LIB_EXPORT void jack_set_error_function (print_function func)
Definition at line 324 of file JackAPI.cpp.
References default_jack_error_callback(), jack_error_callback, and LIB_EXPORT.
jack_set_info_function()
LIB_EXPORT void jack_set_info_function (print_function func)
Definition at line 329 of file JackAPI.cpp.
References default_jack_info_callback(), jack_info_callback, and LIB_EXPORT.
jack_uuid_clear()
LIB_EXPORT void jack_uuid_clear (jack_uuid_t * u)
Definition at line 2125 of file JackAPI.cpp.
References JACK_UUID_EMPTY_INITIALIZER, and LIB_EXPORT.
Referenced by Jack::JackPropertyChangeNotifyRequest::JackPropertyChangeNotifyRequest(), and Jack::JackEngine::EnsureUUID().
jack_uuid_compare()
LIB_EXPORT int jack_uuid_compare (jack_uuid_t a, jack_uuid_t b)
Definition at line 2107 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by Jack::JackEngine::EnsureUUID(), Jack::JackMetadata::GetAllProperties(), and Jack::JackEngine::GetClientNameForUUID().
jack_uuid_copy()
LIB_EXPORT void jack_uuid_copy (jack_uuid_t * dst, jack_uuid_t src)
Definition at line 2120 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by Jack::JackPropertyChangeNotifyRequest::JackPropertyChangeNotifyRequest(), Jack::JackEngine::ClientCloseAux(), Jack::JackMetadata::GetAllProperties(), and Jack::JackMetadata::GetProperties().
jack_uuid_empty()
LIB_EXPORT int jack_uuid_empty (jack_uuid_t u)
Definition at line 2150 of file JackAPI.cpp.
References JACK_UUID_EMPTY_INITIALIZER, and LIB_EXPORT.
Referenced by Jack::JackEngine::ClientExternalOpen(), Jack::JackEngine::EnsureUUID(), Jack::JackEngine::PortUnRegister(), and Jack::JackEngine::SessionNotify().
jack_uuid_parse()
LIB_EXPORT int jack_uuid_parse (const char * buf, jack_uuid_t * u)
Definition at line 2130 of file JackAPI.cpp.
References LIB_EXPORT.
Referenced by Jack::JackClient::ClientNotify(), Jack::JackMetadata::GetAllProperties(), Jack::JackEngine::GetClientNameForUUID(), and Jack::JackEngine::ReserveClientName().
jack_uuid_to_index()
LIB_EXPORT uint32_t jack_uuid_to_index (jack_uuid_t u)
Definition at line 2102 of file JackAPI.cpp.
References LIB_EXPORT.
jack_uuid_unparse()
LIB_EXPORT void jack_uuid_unparse (jack_uuid_t u, char buf[JACK_UUID_STRING_SIZE])
Definition at line 2145 of file JackAPI.cpp.
References JACK_UUID_STRING_SIZE, and LIB_EXPORT.
Referenced by Jack::JackClient::ClientNotify(), Jack::JackMetadata::GetProperties(), Jack::JackMetadata::GetProperty(), Jack::JackEngine::GetUUIDForClientName(), jack_client_get_uuid(), Jack::JackEngine::PropertyChangeNotify(), Jack::JackMetadata::RemoveProperties(), Jack::JackEngine::SessionNotify(), Jack::JackEngine::SessionReply(), and Jack::JackMetadata::SetProperty().
WaitGraphChange()
void WaitGraphChange () inline static
Definition at line 305 of file JackAPI.cpp.
References Jack::JackEngineControl::fPeriodUsecs, Jack::JackGlobals::fRealTimeThread, Jack::GetEngineControl(), Jack::GetGraphManager(), Jack::JackAtomicState< T >::IsPendingChange(), jack_log(), jack_tls_get(), and JackSleep().
Referenced by jack_port_connected(), jack_port_connected_to(), jack_port_get_all_connections(), jack_port_get_connections(), jack_port_get_latency(), jack_port_get_latency_range(), jack_port_get_total_latency(), jack_port_set_latency_range(), and jack_recompute_total_latency().