LMMS: lmms::InstrumentFunctionNoteStacking::ChordTable Struct Reference
lmms::InstrumentFunctionNoteStacking::ChordTable Struct Reference
#include <InstrumentFunctions.h>
Classes
struct Init
Public Member Functions
const std::vector< Chord > & chords () const
const Chord & getByName (const QString &name, bool is_scale=false) const
const Chord & getChordByName (const QString &name) const
const Chord & getScaleByName (const QString &name) const
Static Public Member Functions
static const ChordTable & getInstance ()
Private Member Functions
ChordTable ()
Private Attributes
std::vector< Chord > m_chords
Static Private Attributes
static std::array< Init, NUM_CHORD_TABLES > s_initTable
Detailed Description
Definition at line 123 of file InstrumentFunctions.h.
Constructor & Destructor Documentation
ChordTable()
lmms::InstrumentFunctionNoteStacking::ChordTable::ChordTable () private
Definition at line 182 of file InstrumentFunctions.cpp.
References m_chords, and s_initTable.
Referenced by getInstance().
Member Function Documentation
chords()
const std::vector< Chord > & lmms::InstrumentFunctionNoteStacking::ChordTable::chords () const inline
Definition at line 156 of file InstrumentFunctions.h.
References m_chords.
Referenced by lmms::InstrumentFunctionArpeggio::InstrumentFunctionArpeggio(), lmms::InstrumentFunctionNoteStacking::InstrumentFunctionNoteStacking(), lmms::gui::PianoRoll::PianoRoll(), lmms::InstrumentFunctionArpeggio::processNote(), and lmms::InstrumentFunctionNoteStacking::processNote().
getByName()
const InstrumentFunctionNoteStacking::Chord & lmms::InstrumentFunctionNoteStacking::ChordTable::getByName (const QString & name, bool is_scale = false) const
Definition at line 193 of file InstrumentFunctions.cpp.
References m_chords.
Referenced by getChordByName(), and getScaleByName().
getChordByName()
const Chord & lmms::InstrumentFunctionNoteStacking::ChordTable::getChordByName (const QString & name) const inline
Definition at line 151 of file InstrumentFunctions.h.
References getByName().
Referenced by lmms::gui::PianoRoll::markSemiTone(), lmms::gui::PianoRoll::mousePressEvent(), lmms::gui::PianoRoll::pauseChordNotes(), lmms::gui::PianoRoll::playChordNotes(), and lmms::gui::PianoRoll::updateSemiToneMarkerMenu().
getInstance()
const ChordTable & lmms::InstrumentFunctionNoteStacking::ChordTable::getInstance () inline static
Definition at line 138 of file InstrumentFunctions.h.
References ChordTable().
Referenced by lmms::InstrumentFunctionArpeggio::InstrumentFunctionArpeggio(), lmms::InstrumentFunctionNoteStacking::InstrumentFunctionNoteStacking(), lmms::gui::PianoRoll::PianoRoll(), lmms::gui::PianoRoll::markSemiTone(), lmms::gui::PianoRoll::mousePressEvent(), lmms::gui::PianoRoll::pauseChordNotes(), lmms::gui::PianoRoll::playChordNotes(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), and lmms::gui::PianoRoll::updateSemiToneMarkerMenu().
getScaleByName()
const Chord & lmms::InstrumentFunctionNoteStacking::ChordTable::getScaleByName (const QString & name) const inline
Definition at line 146 of file InstrumentFunctions.h.
References getByName().
Referenced by lmms::gui::PianoRoll::markSemiTone(), and lmms::gui::PianoRoll::updateSemiToneMarkerMenu().
Member Data Documentation
m_chords
std::vector<Chord> lmms::InstrumentFunctionNoteStacking::ChordTable::m_chords private
Definition at line 135 of file InstrumentFunctions.h.
Referenced by ChordTable(), chords(), and getByName().
s_initTable
std::array< InstrumentFunctionNoteStacking::ChordTable::Init, InstrumentFunctionNoteStacking::NUM_CHORD_TABLES > lmms::InstrumentFunctionNoteStacking::ChordTable::s_initTable static private
Definition at line 134 of file InstrumentFunctions.h.
Referenced by ChordTable().
The documentation for this struct was generated from the following files:
include/InstrumentFunctions.h
src/core/InstrumentFunctions.cpp