LMMS: lmms::gui::PianoView Class Reference
lmms::gui::PianoView Class Reference
#include <PianoView.h>
Signals
void baseNoteChanged ()
void keyPressed (int)
Public Member Functions
PianoView (QWidget *_parent)
Create a new keyboard display view.
~PianoView () override=default
void keyPressEvent (QKeyEvent *ke) override
Handle a key press event on the piano display view.
void keyReleaseEvent (QKeyEvent *ke) override
Handle a key release event on the piano display view.
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Static Public Member Functions
static int getKeyFromKeyEvent (QKeyEvent *_ke)
Map a keyboard key being pressed to a note in our keyboard view.
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *_me) override
Handle a context menu selection on the piano display view.
void focusInEvent (QFocusEvent *fe) override
void focusOutEvent (QFocusEvent *_fe) override
Handle the focus leaving the piano display view.
void modelChanged () override
Register a change to this piano display view.
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse move event on the piano display view.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse click on this piano display view.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release event on the piano display view.
void paintEvent (QPaintEvent *) override
Paint the piano display view in response to an event.
void resizeEvent (QResizeEvent *_event) override
update scrollbar range after resize
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Slots
void pianoScrolled (int _new_pos)
Handle the scrolling on the piano display view.
Private Member Functions
int getKeyFromMouse (const QPoint &_p) const
Get the key from the mouse position in the piano display.
int getKeyHeight (int key_num) const
Return the height of a given key.
int getKeyWidth (int key_num) const
Return the width of a given key.
int getKeyX (int _key_num) const
Convert a key number to an X coordinate in the piano display view.
IntModel * getNearestMarker (int key, QString *title=nullptr)
Return model and title of the marker closest to the given key.
Private Attributes
QPixmap m_blackKeyDisabledPm = embed::getIconPixmap("black_key_disabled")
QPixmap m_blackKeyPm = embed::getIconPixmap("black_key")
QPixmap m_blackKeyPressedPm = embed::getIconPixmap("black_key_pressed")
int m_lastKey
previously pressed key
IntModel * m_movedNoteModel
note marker which is being moved
Piano * m_piano
QScrollBar * m_pianoScroll
int m_startKey
first key when drawing
QPixmap m_whiteKeyDisabledPm = embed::getIconPixmap("white_key_disabled")
QPixmap m_whiteKeyPm = embed::getIconPixmap("white_key")
QPixmap m_whiteKeyPressedPm = embed::getIconPixmap("white_key_pressed")
Detailed Description
Definition at line 43 of file PianoView.h.
Constructor & Destructor Documentation
PianoView()
lmms::gui::PianoView::PianoView (QWidget * parent)
Create a new keyboard display view.
Parameters
_parent the parent instrument plugin window
Todo
are the descriptions of the m_startkey and m_lastkey properties correct?
< Our parent
< Our view Model
< Our piano Model
< The first key displayed?
< The last key displayed?
< Key marker which is being moved
Definition at line 84 of file PianoView.cpp.
References lmms::gui::ModelView::ModelView(), lmms::Engine::getSong(), lmms::Piano::isBlackKey(), m_lastKey, m_movedNoteModel, m_piano, m_pianoScroll, m_startKey, lmms::NumKeys, lmms::Piano::NumWhiteKeys, lmms::Octave_3, lmms::gui::PIANO_BASE, pianoScrolled(), lmms::gui::PW_BLACK_KEY_WIDTH, lmms::gui::PW_WHITE_KEY_HEIGHT, lmms::gui::PW_WHITE_KEY_WIDTH, and lmms::Piano::WhiteKeysPerOctave.
~PianoView()
lmms::gui::PianoView::~PianoView () override default
Member Function Documentation
baseNoteChanged
void lmms::gui::PianoView::baseNoteChanged () signal
Referenced by mousePressEvent().
contextMenuEvent()
void lmms::gui::PianoView::contextMenuEvent (QContextMenuEvent * me) override protected
Handle a context menu selection on the piano display view.
Parameters
me the ContextMenuEvent to handle.
Todo
Is this right, or does this create the context menu?
Definition at line 376 of file PianoView.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions(), getKeyFromMouse(), getNearestMarker(), m_piano, and lmms::gui::PIANO_BASE.
focusInEvent()
void lmms::gui::PianoView::focusInEvent (QFocusEvent * fe) override protected
Definition at line 677 of file PianoView.cpp.
References m_piano.
focusOutEvent()
void lmms::gui::PianoView::focusOutEvent (QFocusEvent * _fe) override protected
Handle the focus leaving the piano display view.
Turn off all notes if we lose focus.
Todo
Is there supposed to be a parameter given here?
Definition at line 642 of file PianoView.cpp.
References i, m_piano, lmms::MidiNoteOff, and lmms::NumKeys.
getKeyFromKeyEvent()
int lmms::gui::PianoView::getKeyFromKeyEvent (QKeyEvent * _ke) static
Map a keyboard key being pressed to a note in our keyboard view.
Definition at line 263 of file PianoView.cpp.
References lmms::DefaultOctave, lmms::gui::getKeyOffsetFromKeyEvent(), and lmms::KeysPerOctave.
Referenced by lmms::gui::PianoRoll::keyPressEvent(), keyPressEvent(), lmms::gui::PianoRoll::keyReleaseEvent(), and keyReleaseEvent().
getKeyFromMouse()
int lmms::gui::PianoView::getKeyFromMouse (const QPoint & p) const private
Get the key from the mouse position in the piano display.
Parameters
p The point that the mouse was pressed.
Definition at line 294 of file PianoView.cpp.
References lmms::KeysPerOctave, m_pianoScroll, lmms::NumKeys, lmms::gui::PIANO_BASE, lmms::gui::PW_BLACK_KEY_HEIGHT, lmms::gui::PW_BLACK_KEY_WIDTH, lmms::gui::PW_WHITE_KEY_WIDTH, lmms::gui::WhiteKeys, and lmms::Piano::WhiteKeysPerOctave.
Referenced by contextMenuEvent(), mouseMoveEvent(), and mousePressEvent().
getKeyHeight()
int lmms::gui::PianoView::getKeyHeight (int key_num) const private
Return the height of a given key.
Definition at line 764 of file PianoView.cpp.
References lmms::Piano::isWhiteKey(), lmms::gui::PW_BLACK_KEY_HEIGHT, and lmms::gui::PW_WHITE_KEY_HEIGHT.
Referenced by mousePressEvent().
getKeyWidth()
int lmms::gui::PianoView::getKeyWidth (int key_num) const private
Return the width of a given key.
Definition at line 757 of file PianoView.cpp.
References lmms::Piano::isWhiteKey(), lmms::gui::PW_BLACK_KEY_WIDTH, and lmms::gui::PW_WHITE_KEY_WIDTH.
Referenced by paintEvent().
getKeyX()
int lmms::gui::PianoView::getKeyX (int _key_num) const private
Convert a key number to an X coordinate in the piano display view.
We can immediately discard the trivial case of when the key number is less than our starting key. We then iterate through the keys from the start key to this key, adding the width of each key as we go. For black keys, and the first white key if there is no black key between two white keys, we add half a white key width; for that second white key, we add a whole width. That takes us to the boundary of a white key - subtract half a width to get to the middle.
Parameters
_key_num the keyboard key to translate
Todo
is this description of what the method does correct?
replace the final subtract with initialising x to width/2.
Definition at line 715 of file PianoView.cpp.
References lmms::Piano::isWhiteKey(), k, m_startKey, and lmms::gui::PW_WHITE_KEY_WIDTH.
Referenced by paintEvent().
getNearestMarker()
IntModel * lmms::gui::PianoView::getNearestMarker (int key, QString * title = nullptr) private
Return model and title of the marker closest to the given key.
Definition at line 772 of file PianoView.cpp.
References m_piano.
Referenced by contextMenuEvent(), and mousePressEvent().
keyPressed
void lmms::gui::PianoView::keyPressed (int) signal
Referenced by mousePressEvent().
keyPressEvent()
void lmms::gui::PianoView::keyPressEvent (QKeyEvent * _ke) override
Handle a key press event on the piano display view.
We determine our key number from the getKeyFromKeyEvent() method, and pass the event on to the piano's handleKeyPress() method if auto-repeat is off.
Parameters
_ke the KeyEvent to handle.
Definition at line 587 of file PianoView.cpp.
References getKeyFromKeyEvent(), and m_piano.
Referenced by lmms::gui::MainWindow::keyPressEvent().
keyReleaseEvent()
void lmms::gui::PianoView::keyReleaseEvent (QKeyEvent * _ke) override
Handle a key release event on the piano display view.
The same logic as the keyPressEvent() method.
Parameters
_ke the KeyEvent to handle.
Definition at line 615 of file PianoView.cpp.
References getKeyFromKeyEvent(), and m_piano.
modelChanged()
void lmms::gui::PianoView::modelChanged () override protected virtual
Register a change to this piano display view.
Reimplemented from lmms::gui::ModelView.
Definition at line 272 of file PianoView.cpp.
References lmms::gui::ModelView::castModel(), and m_piano.
mouseMoveEvent()
void lmms::gui::PianoView::mouseMoveEvent (QMouseEvent * _me) override protected
Handle a mouse move event on the piano display view.
This handles the user dragging the mouse across the keys. It uses code from mousePressEvent() and mouseReleaseEvent(), also correcting for if the mouse movement has stayed within one key and if the mouse has moved outside the vertical area of the keyboard (which is still allowed but won't make the volume go up to 11).
Parameters
_me the ContextMenuEvent to handle.
Todo
Paul Wayper thinks that this code should be refactored to reduce or remove the duplication between this, the mousePressEvent() and mouseReleaseEvent() methods.
Definition at line 515 of file PianoView.cpp.
References getKeyFromMouse(), lmms::Piano::isWhiteKey(), m_lastKey, m_movedNoteModel, m_piano, lmms::MidiKeyPressure, lmms::MidiNoteOff, lmms::MidiNoteOn, lmms::gui::PIANO_BASE, lmms::gui::PW_BLACK_KEY_HEIGHT, and lmms::gui::PW_WHITE_KEY_HEIGHT.
mousePressEvent()
void lmms::gui::PianoView::mousePressEvent (QMouseEvent * me) override protected
Handle a mouse click on this piano display view.
We first determine the key number using the getKeyFromMouse() method.
If we're below the 'root key selection' area, we set the volume of the note to be proportional to the vertical position on the keyboard - lower down the key is louder, within the boundaries of the (white or black) key pressed. We then tell the instrument to play that note, scaling for MIDI max loudness = 127.
If we're in the 'root key selection' area, of course, we set the root key to be that key.
We finally update ourselves to show the key press
Parameters
me the mouse click to handle.
Definition at line 416 of file PianoView.cpp.
References baseNoteChanged(), getKeyFromMouse(), getKeyHeight(), getNearestMarker(), keyPressed(), m_lastKey, m_movedNoteModel, m_piano, lmms::MidiNoteOn, and lmms::gui::PIANO_BASE.
mouseReleaseEvent()
void lmms::gui::PianoView::mouseReleaseEvent (QMouseEvent * me) override protected
Handle a mouse release event on the piano display view.
If a key was pressed by the in the mousePressEvent() function, we turn the note off.
Parameters
_me the mousePressEvent to handle.
Definition at line 480 of file PianoView.cpp.
References m_lastKey, m_movedNoteModel, m_piano, and lmms::MidiNoteOff.
paintEvent()
void lmms::gui::PianoView::paintEvent (QPaintEvent *) override protected
Paint the piano display view in response to an event.
This method draws the piano and the 'root note' base. It draws the base first, then all the white keys, then all the black keys.
Todo
Is there supposed to be a parameter given here?
Definition at line 803 of file PianoView.cpp.
References lmms::gui::adjustedToPixelSize(), lmms::C, lmms::FirstOctave, getKeyWidth(), getKeyX(), lmms::Piano::isBlackKey(), lmms::KeysPerOctave, lmms::gui::LABEL_TEXT_SIZE, m_blackKeyDisabledPm, m_blackKeyPm, m_blackKeyPressedPm, m_piano, m_startKey, m_whiteKeyDisabledPm, m_whiteKeyPm, m_whiteKeyPressedPm, lmms::NumKeys, lmms::gui::PIANO_BASE, and lmms::gui::PW_WHITE_KEY_WIDTH.
pianoScrolled
void lmms::gui::PianoView::pianoScrolled (int newPos) private slot
Handle the scrolling on the piano display view.
We need to update our start key position based on the new position.
Parameters
newPos the new key position, counting only white keys.
Definition at line 360 of file PianoView.cpp.
References m_startKey, lmms::gui::WhiteKeys, and lmms::Piano::WhiteKeysPerOctave.
Referenced by PianoView().
resizeEvent()
void lmms::gui::PianoView::resizeEvent (QResizeEvent * event) override protected
update scrollbar range after resize
After resizing we need to adjust range of scrollbar for not allowing to scroll too far to the right.
Parameters
event resize-event object (unused)
Definition at line 691 of file PianoView.cpp.
References m_pianoScroll, lmms::Piano::NumWhiteKeys, and lmms::gui::PW_WHITE_KEY_WIDTH.
Member Data Documentation
m_blackKeyDisabledPm
QPixmap lmms::gui::PianoView::m_blackKeyDisabledPm = embed::getIconPixmap("black_key_disabled") private
Definition at line 82 of file PianoView.h.
Referenced by paintEvent().
m_blackKeyPm
QPixmap lmms::gui::PianoView::m_blackKeyPm = embed::getIconPixmap("black_key") private
Definition at line 78 of file PianoView.h.
Referenced by paintEvent().
m_blackKeyPressedPm
QPixmap lmms::gui::PianoView::m_blackKeyPressedPm = embed::getIconPixmap("black_key_pressed") private
Definition at line 80 of file PianoView.h.
Referenced by paintEvent().
m_lastKey
int lmms::gui::PianoView::m_lastKey private
previously pressed key
Definition at line 88 of file PianoView.h.
Referenced by PianoView(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_movedNoteModel
IntModel* lmms::gui::PianoView::m_movedNoteModel private
note marker which is being moved
Definition at line 89 of file PianoView.h.
Referenced by PianoView(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_piano
Piano* lmms::gui::PianoView::m_piano private
Definition at line 84 of file PianoView.h.
Referenced by PianoView(), contextMenuEvent(), focusInEvent(), focusOutEvent(), getNearestMarker(), keyPressEvent(), keyReleaseEvent(), modelChanged(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
m_pianoScroll
QScrollBar* lmms::gui::PianoView::m_pianoScroll private
Definition at line 86 of file PianoView.h.
Referenced by PianoView(), getKeyFromMouse(), and resizeEvent().
m_startKey
int lmms::gui::PianoView::m_startKey private
first key when drawing
Definition at line 87 of file PianoView.h.
Referenced by PianoView(), getKeyX(), paintEvent(), and pianoScrolled().
m_whiteKeyDisabledPm
QPixmap lmms::gui::PianoView::m_whiteKeyDisabledPm = embed::getIconPixmap("white_key_disabled") private
Definition at line 81 of file PianoView.h.
Referenced by paintEvent().
m_whiteKeyPm
QPixmap lmms::gui::PianoView::m_whiteKeyPm = embed::getIconPixmap("white_key") private
Definition at line 77 of file PianoView.h.
Referenced by paintEvent().
m_whiteKeyPressedPm
QPixmap lmms::gui::PianoView::m_whiteKeyPressedPm = embed::getIconPixmap("white_key_pressed") private
Definition at line 79 of file PianoView.h.
Referenced by paintEvent().
The documentation for this class was generated from the following files:
include/PianoView.h
src/gui/instrument/PianoView.cpp