LMMS: lmms::SampleTrack Class Reference
lmms::SampleTrack Class Reference
#include <SampleTrack.h>
Public Slots
void setPlayingClips (bool isPlaying)
void updateClips ()
void updateMixerChannel ()
Public Slots inherited from lmms::Track
void setMutedBeforeSolo (const bool muted)
virtual void setName (const QString &newName)
void toggleSolo ()
Invert the track's solo state.
Signals
void playingChanged ()
Signals inherited from lmms::Track
void clipAdded (lmms::Clip *)
void colorChanged ()
void dataChanged ()
void destroyedTrack ()
void nameChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
SampleTrack (TrackContainer *tc)
~SampleTrack () override
AudioBusHandle * audioBusHandle ()
Clip * createClip (const TimePos &pos) override
gui::TrackView * createView (gui::TrackContainerView *tcv) override
bool isPlaying ()
void loadTrackSpecificSettings (const QDomElement &_this) override
IntModel * mixerChannelModel ()
QString nodeName () const override
bool play (const TimePos &_start, const fpp_t _frames, const f_cnt_t _frame_base, int _clip_num=-1) override
void saveTrackSpecificSettings (QDomDocument &doc, QDomElement &parent, bool presetMode) override
void setPlaying (bool playing)
Public Member Functions inherited from lmms::Track
Track (Type type, TrackContainer *tc)
Create a new (empty) track object.
~Track () override
Destroy this track.
Clip * addClip (Clip *clip)
Add another Clip into this track.
Track * clone ()
Clone a track from this track.
auto color () const -> const std::optional< QColor > &
void createClipsForPattern (int pattern)
void deleteClips ()
Remove all Clips from this track.
QString displayName () const override
auto getClip (std::size_t clipNum) -> Clip *
Get a Clip by number.
int getClipNum (const Clip *clip)
Determine the given Clip's number in our array.
const clipVector & getClips () const
void getClipsInRange (clipVector &clipV, const TimePos &start, const TimePos &end)
Retrieve a list of clips that fall within a period.
int getHeight ()
BoolModel * getMutedModel ()
void insertBar (const TimePos &pos)
Move all the clips after a certain time later by one bar.
bool isMutedBeforeSolo () const
bar_t length () const
Return the length of the entire track in bars.
void loadPreset (const QDomElement &element)
void loadSettings (const QDomElement &element) override
void lock ()
virtual const QString & name () const
int numOfClips ()
Return the number of clips we contain.
void removeBar (const TimePos &pos)
Move all the clips after a certain time earlier by one bar.
void removeClip (Clip *clip)
Remove a given Clip from this track.
void savePreset (QDomDocument &doc, QDomElement &element)
void saveSettings (QDomDocument &doc, QDomElement &element) override
void setColor (const std::optional< QColor > &color)
void setHeight (int height)
void swapPositionOfClips (int clipNum1, int clipNum2)
Swap the position of two clips.
TrackContainer * trackContainer () const
bool tryLock ()
Type type () const
void unlock ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Private Attributes
AudioBusHandle m_audioBusHandle
bool m_isPlaying
IntModel m_mixerChannelModel
FloatModel m_panningModel
FloatModel m_volumeModel
Friends
class gui::SampleTrackView
class gui::SampleTrackWindow
Additional Inherited Members
Public Types inherited from lmms::Track
using clipVector = std::vector<Clip*>
enum class Type {
Instrument ,
Pattern ,
Sample ,
Event ,
Video ,
Automation ,
HiddenAutomation ,
Count
}
Static Public Member Functions inherited from lmms::Track
static Track * create (const QDomElement &element, TrackContainer *tc)
Create a track inside TrackContainer from track type in a QDomElement and restore state from XML.
static Track * create (Type tt, TrackContainer *tc)
Create a track based on the given track type and container.
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Protected Attributes inherited from lmms::Track
BoolModel m_mutedModel
BoolModel m_soloModel
Detailed Description
Definition at line 44 of file SampleTrack.h.
Constructor & Destructor Documentation
SampleTrack()
lmms::SampleTrack::SampleTrack (TrackContainer * tc)
Definition at line 47 of file SampleTrack.cpp.
References lmms::Track::Track(), lmms::Track::dataChanged(), lmms::DefaultPanning, lmms::DefaultVolume, m_audioBusHandle, m_isPlaying, m_mixerChannelModel, lmms::Track::m_mutedModel, m_panningModel, m_volumeModel, lmms::MaxVolume, lmms::MinVolume, lmms::Engine::mixer(), lmms::PanningLeft, lmms::PanningRight, lmms::Track::setName(), and updateMixerChannel().
~SampleTrack()
lmms::SampleTrack::~SampleTrack () override
Definition at line 65 of file SampleTrack.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::removePlayHandlesOfTypes(), and lmms::PlayHandle::SamplePlayHandle.
Member Function Documentation
audioBusHandle()
AudioBusHandle * lmms::SampleTrack::audioBusHandle () inline
Definition at line 65 of file SampleTrack.h.
References m_audioBusHandle.
Referenced by lmms::gui::SampleTrackWindow::SampleTrackWindow().
createClip()
Clip * lmms::SampleTrack::createClip (const TimePos & pos) override virtual
Implements lmms::Track.
Definition at line 181 of file SampleTrack.cpp.
References pos.
createView()
gui::TrackView * lmms::SampleTrack::createView (gui::TrackContainerView * tcv) override virtual
Implements lmms::Track.
Definition at line 173 of file SampleTrack.cpp.
isPlaying()
bool lmms::SampleTrack::isPlaying () inline
Definition at line 75 of file SampleTrack.h.
References m_isPlaying.
Referenced by playingChanged(), and setPlayingClips().
loadTrackSpecificSettings()
void lmms::SampleTrack::loadTrackSpecificSettings (const QDomElement & _this) override virtual
Implements lmms::Track.
Definition at line 202 of file SampleTrack.cpp.
References m_audioBusHandle, m_mixerChannelModel, m_panningModel, m_volumeModel, and lmms::Engine::mixer().
mixerChannelModel()
IntModel * lmms::SampleTrack::mixerChannelModel () inline
Definition at line 60 of file SampleTrack.h.
References m_mixerChannelModel.
Referenced by lmms::gui::SampleTrackView::assignMixerLine(), lmms::gui::SampleTrackView::createMixerMenu(), and lmms::Mixer::deleteChannel().
nodeName()
QString lmms::SampleTrack::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 70 of file SampleTrack.h.
play()
bool lmms::SampleTrack::play (const TimePos & _start, const fpp_t _frames, const f_cnt_t _frame_base, int _clip_num = -1) override virtual
Implements lmms::Track.
Definition at line 73 of file SampleTrack.cpp.
References lmms::AudioEngine::addPlayHandle(), lmms::Engine::audioEngine(), lmms::PatternTrack::findPatternTrack(), lmms::Engine::framesPerTick(), lmms::Track::getClip(), lmms::Engine::getSong(), i, lmms::SampleClip::isPlaying(), lmms::Track::length(), m_audioBusHandle, m_volumeModel, lmms::Track::numOfClips(), lmms::Engine::patternStore(), lmms::PlayHandle::setOffset(), setPlaying(), and lmms::Track::trackContainer().
playingChanged
void lmms::SampleTrack::playingChanged () signal
References isPlaying().
Referenced by setPlaying().
saveTrackSpecificSettings()
void lmms::SampleTrack::saveTrackSpecificSettings (QDomDocument & doc, QDomElement & parent, bool presetMode) override virtual
Implements lmms::Track.
Definition at line 191 of file SampleTrack.cpp.
References m_audioBusHandle, m_mixerChannelModel, m_panningModel, and m_volumeModel.
setPlaying()
void lmms::SampleTrack::setPlaying (bool playing) inline
Definition at line 80 of file SampleTrack.h.
References m_isPlaying, and playingChanged().
Referenced by play().
setPlayingClips
void lmms::SampleTrack::setPlayingClips (bool isPlaying) slot
Definition at line 235 of file SampleTrack.cpp.
References lmms::Track::getClip(), i, isPlaying(), lmms::Track::numOfClips(), and lmms::SampleClip::setIsPlaying().
Referenced by lmms::SampleClip::playbackPositionChanged(), and updateClips().
updateClips
void lmms::SampleTrack::updateClips () slot
Definition at line 226 of file SampleTrack.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::removePlayHandlesOfTypes(), lmms::PlayHandle::SamplePlayHandle, and setPlayingClips().
updateMixerChannel
void lmms::SampleTrack::updateMixerChannel () slot
Definition at line 248 of file SampleTrack.cpp.
References m_audioBusHandle, and m_mixerChannelModel.
Referenced by SampleTrack().
Friends And Related Symbol Documentation
gui::SampleTrackView
friend class gui::SampleTrackView friend
Definition at line 103 of file SampleTrack.h.
gui::SampleTrackWindow
friend class gui::SampleTrackWindow friend
Definition at line 104 of file SampleTrack.h.
Member Data Documentation
m_audioBusHandle
AudioBusHandle lmms::SampleTrack::m_audioBusHandle private
Definition at line 98 of file SampleTrack.h.
Referenced by SampleTrack(), audioBusHandle(), loadTrackSpecificSettings(), play(), saveTrackSpecificSettings(), and updateMixerChannel().
m_isPlaying
bool lmms::SampleTrack::m_isPlaying private
Definition at line 99 of file SampleTrack.h.
Referenced by SampleTrack(), isPlaying(), and setPlaying().
m_mixerChannelModel
IntModel lmms::SampleTrack::m_mixerChannelModel private
Definition at line 97 of file SampleTrack.h.
Referenced by SampleTrack(), loadTrackSpecificSettings(), mixerChannelModel(), saveTrackSpecificSettings(), and updateMixerChannel().
m_panningModel
FloatModel lmms::SampleTrack::m_panningModel private
Definition at line 96 of file SampleTrack.h.
Referenced by SampleTrack(), lmms::gui::SampleTrackView::SampleTrackView(), loadTrackSpecificSettings(), and saveTrackSpecificSettings().
m_volumeModel
FloatModel lmms::SampleTrack::m_volumeModel private
Definition at line 95 of file SampleTrack.h.
Referenced by SampleTrack(), lmms::gui::SampleTrackView::SampleTrackView(), loadTrackSpecificSettings(), play(), and saveTrackSpecificSettings().
The documentation for this class was generated from the following files:
include/SampleTrack.h
src/tracks/SampleTrack.cpp