LMMS: Jack::JackPortAudioAdapter Class Reference
Jack::JackPortAudioAdapter Class Reference
Audio adapter using PortAudio API.
#include <JackPortAudioAdapter.h>
Public Member Functions
JackPortAudioAdapter (jack_nframes_t buffer_size, jack_nframes_t sample_rate, const JSList *params)
~JackPortAudioAdapter ()
int Close ()
int Open ()
int SetBufferSize (jack_nframes_t buffer_size)
int SetSampleRate (jack_nframes_t sample_rate)
Public Member Functions inherited from Jack::JackAudioAdapterInterface
JackAudioAdapterInterface (jack_nframes_t buffer_size, jack_nframes_t sample_rate, jack_nframes_t ring_buffer_size=DEFAULT_ADAPTATIVE_SIZE)
JackAudioAdapterInterface (jack_nframes_t host_buffer_size, jack_nframes_t host_sample_rate, jack_nframes_t adapted_buffer_size, jack_nframes_t adapted_sample_rate, jack_nframes_t ring_buffer_size=DEFAULT_ADAPTATIVE_SIZE)
virtual ~JackAudioAdapterInterface ()
virtual void Create ()
virtual void Destroy ()
virtual int GetInputLatency (int port_index)
int GetInputs ()
virtual int GetOutputLatency (int port_index)
int GetOutputs ()
int PullAndPush (jack_default_audio_sample_t **inputBuffer, jack_default_audio_sample_t **outputBuffer, unsigned int frames)
int PushAndPull (jack_default_audio_sample_t **inputBuffer, jack_default_audio_sample_t **outputBuffer, unsigned int frames)
virtual void Reset ()
virtual int SetAdaptedBufferSize (jack_nframes_t buffer_size)
virtual int SetAdaptedSampleRate (jack_nframes_t sample_rate)
virtual int SetHostBufferSize (jack_nframes_t buffer_size)
virtual int SetHostSampleRate (jack_nframes_t sample_rate)
void SetInputs (int inputs)
void SetOutputs (int outputs)
Static Private Member Functions
static int Render (const void *inputBuffer, void *outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
Private Attributes
PaDeviceIndex fInputDevice
PaDeviceIndex fOutputDevice
PortAudioDevices fPaDevices
PaStream * fStream
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAudioAdapterInterface
void AdaptRingBufferSize ()
void GrowRingBufferSize ()
void ResetRingBuffers ()
Protected Attributes inherited from Jack::JackAudioAdapterInterface
bool fAdaptative
jack_nframes_t fAdaptedBufferSize
jack_nframes_t fAdaptedSampleRate
int fCaptureChannels
JackResampler ** fCaptureRingBuffer
jack_nframes_t fHostBufferSize
jack_nframes_t fHostSampleRate
JackPIControler fPIControler
int fPlaybackChannels
JackResampler ** fPlaybackRingBuffer
jack_time_t fPullAndPushTime
unsigned int fQuality
unsigned int fRingbufferCurSize
bool fRunning
Detailed Description
Audio adapter using PortAudio API.
Definition at line 34 of file JackPortAudioAdapter.h.
Constructor & Destructor Documentation
JackPortAudioAdapter()
Jack::JackPortAudioAdapter::JackPortAudioAdapter (jack_nframes_t buffer_size, jack_nframes_t sample_rate, const JSList * params)
Definition at line 37 of file JackPortAudioAdapter.cpp.
References Jack::JackAudioAdapterInterface::JackAudioAdapterInterface(), jack_driver_param_t::character, _JSList::data, Jack::JackAudioAdapterInterface::fAdaptative, Jack::JackAudioAdapterInterface::fCaptureChannels, fInputDevice, fOutputDevice, fPaDevices, Jack::JackAudioAdapterInterface::fPlaybackChannels, Jack::JackAudioAdapterInterface::fQuality, Jack::JackAudioAdapterInterface::fRingbufferCurSize, jack_error, jack_log(), jack_slist_next, Jack::JackAudioAdapterInterface::SetAdaptedBufferSize(), Jack::JackAudioAdapterInterface::SetAdaptedSampleRate(), Jack::JackAudioAdapterInterface::SetInputs(), Jack::JackAudioAdapterInterface::SetOutputs(), jack_driver_param_value_t::str, jack_driver_param_value_t::ui, and jack_driver_param_t::value.
Referenced by Render().
~JackPortAudioAdapter()
Jack::JackPortAudioAdapter::~JackPortAudioAdapter () inline
Definition at line 53 of file JackPortAudioAdapter.h.
Member Function Documentation
Close()
int Jack::JackPortAudioAdapter::Close () virtual
Reimplemented from Jack::JackAudioAdapterInterface.
Definition at line 171 of file JackPortAudioAdapter.cpp.
References Jack::JackAudioAdapterInterface::fAdaptedBufferSize, Jack::JackAudioAdapterInterface::fAdaptedSampleRate, Jack::JackAudioAdapterInterface::fHostBufferSize, Jack::JackAudioAdapterInterface::fHostSampleRate, fStream, and jack_log().
Referenced by SetBufferSize(), and SetSampleRate().
Open()
int Jack::JackPortAudioAdapter::Open () virtual
Reimplemented from Jack::JackAudioAdapterInterface.
Definition at line 115 of file JackPortAudioAdapter.cpp.
References Jack::JackAudioAdapterInterface::fAdaptedBufferSize, Jack::JackAudioAdapterInterface::fAdaptedSampleRate, Jack::JackAudioAdapterInterface::fCaptureChannels, fInputDevice, fOutputDevice, fPaDevices, Jack::JackAudioAdapterInterface::fPlaybackChannels, fStream, jack_error, jack_log(), and Render().
Referenced by SetBufferSize(), and SetSampleRate().
Render()
int Jack::JackPortAudioAdapter::Render (const void * inputBuffer, void * outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData) static private
Definition at line 26 of file JackPortAudioAdapter.cpp.
References JackPortAudioAdapter(), and Jack::JackAudioAdapterInterface::PushAndPull().
Referenced by Open().
SetBufferSize()
int Jack::JackPortAudioAdapter::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackAudioAdapterInterface.
Definition at line 191 of file JackPortAudioAdapter.cpp.
References Close(), Open(), and Jack::JackAudioAdapterInterface::SetHostBufferSize().
SetSampleRate()
int Jack::JackPortAudioAdapter::SetSampleRate (jack_nframes_t sample_rate) virtual
Reimplemented from Jack::JackAudioAdapterInterface.
Definition at line 184 of file JackPortAudioAdapter.cpp.
References Close(), Open(), and Jack::JackAudioAdapterInterface::SetHostSampleRate().
Member Data Documentation
fInputDevice
PaDeviceIndex Jack::JackPortAudioAdapter::fInputDevice private
Definition at line 41 of file JackPortAudioAdapter.h.
Referenced by JackPortAudioAdapter(), and Open().
fOutputDevice
PaDeviceIndex Jack::JackPortAudioAdapter::fOutputDevice private
Definition at line 42 of file JackPortAudioAdapter.h.
Referenced by JackPortAudioAdapter(), and Open().
fPaDevices
PortAudioDevices Jack::JackPortAudioAdapter::fPaDevices private
Definition at line 39 of file JackPortAudioAdapter.h.
Referenced by JackPortAudioAdapter(), and Open().
fStream
PaStream* Jack::JackPortAudioAdapter::fStream private
Definition at line 40 of file JackPortAudioAdapter.h.
Referenced by Close(), and Open().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/portaudio/JackPortAudioAdapter.h
src/3rdparty/jack2/windows/portaudio/JackPortAudioAdapter.cpp