LMMS: Jack::JackProxyDriver Class Reference
Jack::JackProxyDriver Class Reference
\Brief This class describes the Proxy Backend
#include <JackProxyDriver.h>
Public Member Functions
JackProxyDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table, const char *upstream, const char *promiscuous, char *client_name, bool auto_connect, bool auto_save)
virtual ~JackProxyDriver ()
int Attach ()
int Close ()
int Detach ()
int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
int Read ()
int Stop ()
int Write ()
Public Member Functions inherited from Jack::JackRestarterDriver
JackRestarterDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackRestarterDriver ()
int RestartWait ()
Restart the wrapper thread.
void SetRestartDriver (JackDriver *driver)
Let the wrapper register itself.
Public Member Functions inherited from Jack::JackWaiterDriver
JackWaiterDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackWaiterDriver ()
virtual int ProcessNull ()
Public Member Functions inherited from Jack::JackTimedDriver
JackTimedDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackTimedDriver ()
bool IsFixedBufferSize ()
int Start ()
Public Member Functions inherited from Jack::JackAudioDriver
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Process ()
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetSampleRate (jack_nframes_t sample_rate)
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Member Functions
int AllocPorts ()
int bufsize_callback (jack_nframes_t)
void connect_callback (jack_port_id_t, jack_port_id_t, int)
void ConnectPorts ()
int CountIO (const char *, int)
int FreePorts ()
bool Initialize ()
int LoadClientLib ()
load the client library
void LoadSymbols ()
load the needed library symbols
PROXY_DEF_SYMBOL (const char **, jack_get_ports, jack_client_t *, const char *, const char *, unsigned long)
PROXY_DEF_SYMBOL (const char *, jack_port_name, const jack_port_t *)
PROXY_DEF_SYMBOL (int, jack_activate, jack_client_t *)
PROXY_DEF_SYMBOL (int, jack_client_close, jack_client_t *)
PROXY_DEF_SYMBOL (int, jack_connect, jack_client_t *, const char *, const char *)
PROXY_DEF_SYMBOL (int, jack_deactivate, jack_client_t *)
PROXY_DEF_SYMBOL (int, jack_port_is_mine, const jack_client_t *, const jack_port_t *)
PROXY_DEF_SYMBOL (int, jack_port_unregister, jack_client_t *, jack_port_t *)
PROXY_DEF_SYMBOL (int, jack_set_buffer_size_callback, jack_client_t *, JackBufferSizeCallback, void *)
PROXY_DEF_SYMBOL (int, jack_set_port_connect_callback, jack_client_t *, JackPortConnectCallback, void *)
PROXY_DEF_SYMBOL (int, jack_set_process_callback, jack_client_t *, JackProcessCallback, void *)
PROXY_DEF_SYMBOL (int, jack_set_sample_rate_callback, jack_client_t *, JackSampleRateCallback, void *)
PROXY_DEF_SYMBOL (jack_client_t *, jack_client_open, const char *, jack_options_t, jack_status_t *,...)
PROXY_DEF_SYMBOL (jack_nframes_t, jack_get_buffer_size, jack_client_t *)
PROXY_DEF_SYMBOL (jack_nframes_t, jack_get_sample_rate, jack_client_t *)
PROXY_DEF_SYMBOL (jack_port_t *, jack_port_by_id, jack_client_t *, jack_port_id_t)
PROXY_DEF_SYMBOL (jack_port_t *, jack_port_register, jack_client_t *, const char *, const char *, unsigned long, unsigned long)
PROXY_DEF_SYMBOL (void *, jack_port_get_buffer, jack_port_t *, jack_nframes_t)
PROXY_DEF_SYMBOL (void, jack_free, void *)
PROXY_DEF_SYMBOL (void, jack_on_shutdown, jack_client_t *, JackShutdownCallback, void *)
int srate_callback (jack_nframes_t)
Static Private Member Functions
static int bufsize_callback (jack_nframes_t, void *)
static void connect_callback (jack_port_id_t, jack_port_id_t, int, void *)
static int process_callback (jack_nframes_t, void *)
static void shutdown_callback (void *)
static int srate_callback (jack_nframes_t, void *)
Private Attributes
bool fAutoConnect
bool fAutoSave
jack_client_t * fClient
char fClientName [JACK_CLIENT_NAME_SIZE+1]
bool fDetectCaptureChannels
bool fDetectPlaybackChannels
JACK_HANDLE fHandle
const char * fPromiscuous
char fUpstream [JACK_CLIENT_NAME_SIZE+1]
int * fUpstreamCapturePortConnected
jack_port_t ** fUpstreamCapturePorts
int * fUpstreamPlaybackPortConnected
jack_port_t ** fUpstreamPlaybackPorts
Additional Inherited Members
Protected Member Functions inherited from Jack::JackTimedDriver
int CurrentCycle (jack_time_t cur_time)
int FirstCycle (jack_time_t cur_time)
void ProcessWait ()
Protected Member Functions inherited from Jack::JackAudioDriver
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
virtual void UpdateLatencies ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes inherited from Jack::JackTimedDriver
jack_time_t fAnchorTimeUsec
int fCycleCount
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
\Brief This class describes the Proxy Backend
It uses plain Jack API to connect to an upstream server. The latter is either running as the same user, or is running in promiscuous mode.
The main use case is the multi-user, multi-session, shared workstation:
a classic server with hw driver is launched system-wide at boot time, in promiscuous mode, optionally restricted to the audio group
in each user session, a jackdbus server is automatically started with JackProxyDriver as master driver, automatically connected to the system-wide one
optionally, each user run PulseAudio with a pulse-jack bridge
Definition at line 60 of file JackProxyDriver.h.
Constructor & Destructor Documentation
JackProxyDriver()
Jack::JackProxyDriver::JackProxyDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table, const char * upstream, const char * promiscuous, char * client_name, bool auto_connect, bool auto_save)
Definition at line 31 of file JackProxyDriver.cpp.
References Jack::JackRestarterDriver::JackRestarterDriver(), fAutoConnect, fAutoSave, fClientName, fPromiscuous, fUpstream, JACK_CLIENT_NAME_SIZE, and jack_log().
Referenced by bufsize_callback(), connect_callback(), process_callback(), shutdown_callback(), and srate_callback().
~JackProxyDriver()
Jack::JackProxyDriver::~JackProxyDriver () virtual
Definition at line 52 of file JackProxyDriver.cpp.
References fHandle, and UnloadJackModule.
Member Function Documentation
AllocPorts()
int Jack::JackProxyDriver::AllocPorts () private
Definition at line 346 of file JackProxyDriver.cpp.
References Jack::JackAudioDriver::Attach(), Jack::JackDriver::fCaptureChannels, fClient, fClientName, Jack::JackDriver::fEngineControl, Jack::JackDriver::fPlaybackChannels, fUpstreamCapturePortConnected, fUpstreamCapturePorts, fUpstreamPlaybackPortConnected, fUpstreamPlaybackPorts, i, JACK_DEFAULT_AUDIO_TYPE, jack_error, jack_log(), jack_port_register(), JackPortIsInput, JackPortIsOutput, JackPortIsTerminal, and REAL_JACK_PORT_NAME_SIZE.
Referenced by Initialize().
Attach()
int Jack::JackProxyDriver::Attach () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 110 of file JackProxyDriver.cpp.
bufsize_callback() [1/2]
int Jack::JackProxyDriver::bufsize_callback (jack_nframes_t nframes) private
Definition at line 272 of file JackProxyDriver.cpp.
References Jack::JackDriver::NotifyBufferSize(), and Jack::JackAudioDriver::SetBufferSize().
bufsize_callback() [2/2]
int Jack::JackProxyDriver::bufsize_callback (jack_nframes_t nframes, void * arg) static private
Definition at line 267 of file JackProxyDriver.cpp.
References JackProxyDriver(), and bufsize_callback().
Referenced by bufsize_callback(), and Initialize().
Close()
int Jack::JackProxyDriver::Close () virtual
Reimplemented from Jack::JackDriver.
Definition at line 103 of file JackProxyDriver.cpp.
References Jack::JackClientInterface::Close(), and FreePorts().
connect_callback() [1/2]
void Jack::JackProxyDriver::connect_callback (jack_port_id_t a, jack_port_id_t b, int connect) private
Definition at line 300 of file JackProxyDriver.cpp.
References Jack::JackDriver::fCaptureChannels, fClient, Jack::JackDriver::fPlaybackChannels, fUpstreamCapturePortConnected, fUpstreamCapturePorts, fUpstreamPlaybackPortConnected, fUpstreamPlaybackPorts, i, jack_port_by_id(), and jack_port_is_mine().
connect_callback() [2/2]
void Jack::JackProxyDriver::connect_callback (jack_port_id_t a, jack_port_id_t b, int connect, void * arg) static private
Definition at line 295 of file JackProxyDriver.cpp.
References JackProxyDriver(), and connect_callback().
Referenced by connect_callback(), and Initialize().
ConnectPorts()
void Jack::JackProxyDriver::ConnectPorts () private
Definition at line 420 of file JackProxyDriver.cpp.
References Jack::JackDriver::fCaptureChannels, fClient, Jack::JackDriver::fPlaybackChannels, fUpstreamCapturePorts, fUpstreamPlaybackPorts, i, jack_connect(), JACK_DEFAULT_AUDIO_TYPE, jack_free(), jack_get_ports(), jack_log(), jack_port_name(), JackPortIsInput, JackPortIsOutput, and JackPortIsPhysical.
Referenced by Initialize().
CountIO()
int Jack::JackProxyDriver::CountIO (const char * type, int flags) private
Definition at line 335 of file JackProxyDriver.cpp.
References fClient, jack_free(), and jack_get_ports().
Referenced by Initialize().
Detach()
int Jack::JackProxyDriver::Detach () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 115 of file JackProxyDriver.cpp.
FreePorts()
int Jack::JackProxyDriver::FreePorts () private
Definition at line 381 of file JackProxyDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fClientControl, Jack::JackDriver::fEngine, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, fUpstreamCapturePortConnected, fUpstreamCapturePorts, fUpstreamPlaybackPortConnected, fUpstreamPlaybackPorts, i, and jack_log().
Referenced by Close(), and Initialize().
Initialize()
bool Jack::JackProxyDriver::Initialize () private virtual
Reimplemented from Jack::JackDriver.
Definition at line 126 of file JackProxyDriver.cpp.
References AllocPorts(), bufsize_callback(), connect_callback(), ConnectPorts(), CountIO(), fAutoConnect, fAutoSave, Jack::JackDriver::fCaptureChannels, fClient, fClientName, fDetectCaptureChannels, fDetectPlaybackChannels, Jack::JackDriver::fEngineControl, Jack::JackDriver::fPlaybackChannels, fPromiscuous, FreePorts(), fUpstream, jack_activate(), jack_client_close(), jack_client_open(), JACK_DEFAULT_AUDIO_TYPE, jack_error, jack_get_buffer_size(), jack_get_sample_rate(), jack_info(), jack_log(), jack_on_shutdown(), jack_set_buffer_size_callback(), jack_set_port_connect_callback(), jack_set_process_callback(), jack_set_sample_rate_callback(), JackNoStartServer, JackPortIsInput, JackPortIsOutput, JackPortIsPhysical, JackServerName, JackSleep(), Jack::JackDriver::LoadConnections(), process_callback(), Jack::JackDriver::SaveConnections(), setenv(), shutdown_callback(), srate_callback(), and unsetenv().
LoadClientLib()
int Jack::JackProxyDriver::LoadClientLib () private
load the client library
Definition at line 59 of file JackProxyDriver.cpp.
References fHandle, JACK_PROXY_CLIENT_LIB, LoadJackModule, and LoadSymbols().
Referenced by Open().
LoadSymbols()
void Jack::JackProxyDriver::LoadSymbols () inline private
load the needed library symbols
Definition at line 126 of file JackProxyDriver.h.
References jack_activate(), jack_client_close(), jack_client_open(), jack_connect(), jack_deactivate(), jack_free(), jack_get_buffer_size(), jack_get_ports(), jack_get_sample_rate(), jack_on_shutdown(), jack_port_by_id(), jack_port_get_buffer(), jack_port_is_mine(), jack_port_name(), jack_port_register(), jack_port_unregister(), jack_set_buffer_size_callback(), jack_set_port_connect_callback(), jack_set_process_callback(), jack_set_sample_rate_callback(), and PROXY_LOAD_SYMBOL.
Referenced by LoadClientLib().
Open()
int Jack::JackProxyDriver::Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency) virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 75 of file JackProxyDriver.cpp.
References capture_latency, fDetectCaptureChannels, fDetectPlaybackChannels, jack_error, LoadClientLib(), Jack::JackDriverInterface::Open(), and playback_latency.
process_callback()
int Jack::JackProxyDriver::process_callback (jack_nframes_t nframes, void * arg) static private
Definition at line 261 of file JackProxyDriver.cpp.
References JackProxyDriver(), and Jack::JackAudioDriver::Process().
Referenced by Initialize().
PROXY_DEF_SYMBOL() [1/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (const char ** , jack_get_ports , jack_client_t * , const char * , const char * , unsigned long) private
References jack_get_ports().
PROXY_DEF_SYMBOL() [2/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (const char * , jack_port_name , const jack_port_t *) private
References jack_port_name().
PROXY_DEF_SYMBOL() [3/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_activate , jack_client_t *) private
References jack_activate().
PROXY_DEF_SYMBOL() [4/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_client_close , jack_client_t *) private
References jack_client_close().
PROXY_DEF_SYMBOL() [5/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_connect , jack_client_t * , const char * , const char *) private
References jack_connect().
PROXY_DEF_SYMBOL() [6/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_deactivate , jack_client_t *) private
References jack_deactivate().
PROXY_DEF_SYMBOL() [7/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_port_is_mine , const jack_client_t * , const jack_port_t *) private
References jack_port_is_mine().
PROXY_DEF_SYMBOL() [8/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_port_unregister , jack_client_t * , jack_port_t *) private
References jack_port_unregister().
PROXY_DEF_SYMBOL() [9/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_set_buffer_size_callback , jack_client_t * , JackBufferSizeCallback , void *) private
References jack_set_buffer_size_callback().
PROXY_DEF_SYMBOL() [10/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_set_port_connect_callback , jack_client_t * , JackPortConnectCallback , void *) private
References jack_set_port_connect_callback().
PROXY_DEF_SYMBOL() [11/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_set_process_callback , jack_client_t * , JackProcessCallback , void *) private
References jack_set_process_callback().
PROXY_DEF_SYMBOL() [12/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (int , jack_set_sample_rate_callback , jack_client_t * , JackSampleRateCallback , void *) private
References jack_set_sample_rate_callback().
PROXY_DEF_SYMBOL() [13/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (jack_client_t * , jack_client_open , const char * , jack_options_t , jack_status_t * , ...) private
References jack_client_open().
PROXY_DEF_SYMBOL() [14/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (jack_nframes_t , jack_get_buffer_size , jack_client_t *) private
References jack_get_buffer_size().
PROXY_DEF_SYMBOL() [15/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (jack_nframes_t , jack_get_sample_rate , jack_client_t *) private
References jack_get_sample_rate().
PROXY_DEF_SYMBOL() [16/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (jack_port_t * , jack_port_by_id , jack_client_t * , jack_port_id_t) private
References jack_port_by_id().
PROXY_DEF_SYMBOL() [17/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (jack_port_t * , jack_port_register , jack_client_t * , const char * , const char * , unsigned long , unsigned long) private
References jack_port_register().
PROXY_DEF_SYMBOL() [18/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (void * , jack_port_get_buffer , jack_port_t * , jack_nframes_t) private
References jack_port_get_buffer().
PROXY_DEF_SYMBOL() [19/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (void , jack_free , void *) private
References jack_free().
PROXY_DEF_SYMBOL() [20/20]
Jack::JackProxyDriver::PROXY_DEF_SYMBOL (void , jack_on_shutdown , jack_client_t * , JackShutdownCallback , void *) private
References jack_on_shutdown().
Read()
int Jack::JackProxyDriver::Read () virtual
Reimplemented from Jack::JackDriver.
Definition at line 442 of file JackProxyDriver.cpp.
References Jack::JackDriver::CycleTakeBeginTime(), Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fEngineControl, fUpstreamPlaybackPortConnected, fUpstreamPlaybackPorts, Jack::JackAudioDriver::GetInputBuffer(), i, and jack_port_get_buffer().
shutdown_callback()
void Jack::JackProxyDriver::shutdown_callback (void * arg) static private
Definition at line 327 of file JackProxyDriver.cpp.
References JackProxyDriver(), and Jack::JackRestarterDriver::RestartWait().
Referenced by Initialize().
srate_callback() [1/2]
int Jack::JackProxyDriver::srate_callback (jack_nframes_t nframes) private
Definition at line 286 of file JackProxyDriver.cpp.
References Jack::JackDriver::NotifySampleRate(), and Jack::JackAudioDriver::SetSampleRate().
srate_callback() [2/2]
int Jack::JackProxyDriver::srate_callback (jack_nframes_t nframes, void * arg) static private
Definition at line 281 of file JackProxyDriver.cpp.
References JackProxyDriver(), and srate_callback().
Referenced by Initialize(), and srate_callback().
Stop()
int Jack::JackProxyDriver::Stop () virtual
Reimplemented from Jack::JackDriver.
Definition at line 250 of file JackProxyDriver.cpp.
References fClient, jack_deactivate(), and jack_error.
Write()
int Jack::JackProxyDriver::Write () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 462 of file JackProxyDriver.cpp.
References Jack::JackDriver::fEngineControl, Jack::JackDriver::fPlaybackChannels, fUpstreamCapturePortConnected, fUpstreamCapturePorts, Jack::JackAudioDriver::GetOutputBuffer(), i, and jack_port_get_buffer().
Member Data Documentation
fAutoConnect
bool Jack::JackProxyDriver::fAutoConnect private
Definition at line 77 of file JackProxyDriver.h.
Referenced by JackProxyDriver(), and Initialize().
fAutoSave
bool Jack::JackProxyDriver::fAutoSave private
Definition at line 76 of file JackProxyDriver.h.
Referenced by JackProxyDriver(), and Initialize().
fClient
jack_client_t* Jack::JackProxyDriver::fClient private
Definition at line 70 of file JackProxyDriver.h.
Referenced by AllocPorts(), connect_callback(), ConnectPorts(), CountIO(), Initialize(), and Stop().
fClientName
char Jack::JackProxyDriver::fClientName[JACK_CLIENT_NAME_SIZE+1] private
Definition at line 66 of file JackProxyDriver.h.
Referenced by JackProxyDriver(), AllocPorts(), and Initialize().
fDetectCaptureChannels
bool Jack::JackProxyDriver::fDetectCaptureChannels private
Definition at line 79 of file JackProxyDriver.h.
Referenced by Initialize(), and Open().
fDetectPlaybackChannels
bool Jack::JackProxyDriver::fDetectPlaybackChannels private
Definition at line 78 of file JackProxyDriver.h.
Referenced by Initialize(), and Open().
fHandle
JACK_HANDLE Jack::JackProxyDriver::fHandle private
Definition at line 101 of file JackProxyDriver.h.
Referenced by ~JackProxyDriver(), and LoadClientLib().
fPromiscuous
const char* Jack::JackProxyDriver::fPromiscuous private
Definition at line 67 of file JackProxyDriver.h.
Referenced by JackProxyDriver(), and Initialize().
fUpstream
char Jack::JackProxyDriver::fUpstream[JACK_CLIENT_NAME_SIZE+1] private
Definition at line 65 of file JackProxyDriver.h.
Referenced by JackProxyDriver(), and Initialize().
fUpstreamCapturePortConnected
int* Jack::JackProxyDriver::fUpstreamCapturePortConnected private
Definition at line 73 of file JackProxyDriver.h.
Referenced by AllocPorts(), connect_callback(), FreePorts(), and Write().
fUpstreamCapturePorts
jack_port_t** Jack::JackProxyDriver::fUpstreamCapturePorts private
Definition at line 71 of file JackProxyDriver.h.
Referenced by AllocPorts(), connect_callback(), ConnectPorts(), FreePorts(), and Write().
fUpstreamPlaybackPortConnected
int* Jack::JackProxyDriver::fUpstreamPlaybackPortConnected private
Definition at line 74 of file JackProxyDriver.h.
Referenced by AllocPorts(), connect_callback(), FreePorts(), and Read().
fUpstreamPlaybackPorts
jack_port_t** Jack::JackProxyDriver::fUpstreamPlaybackPorts private
Definition at line 72 of file JackProxyDriver.h.
Referenced by AllocPorts(), connect_callback(), ConnectPorts(), FreePorts(), and Read().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackProxyDriver.h
src/3rdparty/jack2/common/JackProxyDriver.cpp