LMMS: lmms::gui::TabBar Class Reference
lmms::gui::TabBar Class Reference
#include <TabBar.h>
Public Slots
void setActiveTab (int _id)
Signals
void allWidgetsHidden ()
void widgetShown ()
Public Member Functions
TabBar (QWidget *_parent, QBoxLayout::Direction _dir=QBoxLayout::LeftToRight)
~TabBar () override=default
int activeTab ()
TabButton * addTab (QWidget *_w, const QString &_text, int _id, bool _add_stretch=false, bool _text_is_tooltip=false, bool fixWidgetToParentSize=true)
void removeTab (int _id)
void setExclusive (bool _on)
Protected Slots
void hideAll (int _exception=-1)
void tabClicked (int _id)
Protected Member Functions
bool allHidden ()
void setTabState (int _id, bool _checked)
bool tabState (int _id)
Private Attributes
bool m_exclusive
QBoxLayout * m_layout
QMap< int, QPair< TabButton *, QWidget * > > m_tabs
Detailed Description
Definition at line 42 of file TabBar.h.
Constructor & Destructor Documentation
TabBar()
lmms::gui::TabBar::TabBar (QWidget * _parent, QBoxLayout::Direction _dir = QBoxLayout::LeftToRight)
Definition at line 34 of file TabBar.cpp.
References m_exclusive, and m_layout.
~TabBar()
lmms::gui::TabBar::~TabBar () override default
References addTab(), and removeTab().
Member Function Documentation
activeTab()
int lmms::gui::TabBar::activeTab ()
Definition at line 128 of file TabBar.cpp.
References m_tabs, and tabState().
Referenced by tabClicked().
addTab()
TabButton * lmms::gui::TabBar::addTab (QWidget * _w, const QString & _text, int _id, bool _add_stretch = false, bool _text_is_tooltip = false, bool fixWidgetToParentSize = true)
Definition at line 45 of file TabBar.cpp.
References m_layout, m_tabs, removeTab(), and tabClicked().
Referenced by ~TabBar().
allHidden()
bool lmms::gui::TabBar::allHidden () protected
Definition at line 220 of file TabBar.cpp.
References m_tabs.
Referenced by setActiveTab(), and tabClicked().
allWidgetsHidden
void lmms::gui::TabBar::allWidgetsHidden () signal
Referenced by setActiveTab(), and tabClicked().
hideAll
void lmms::gui::TabBar::hideAll (int _exception = -1) protected slot
Definition at line 167 of file TabBar.cpp.
References m_tabs, setTabState(), and tabState().
Referenced by setActiveTab(), and tabClicked().
removeTab()
void lmms::gui::TabBar::removeTab (int _id)
Definition at line 98 of file TabBar.cpp.
References m_tabs.
Referenced by ~TabBar(), and addTab().
setActiveTab
void lmms::gui::TabBar::setActiveTab (int _id) slot
Definition at line 111 of file TabBar.cpp.
References allHidden(), allWidgetsHidden(), hideAll(), setTabState(), and widgetShown().
Referenced by tabClicked().
setExclusive()
void lmms::gui::TabBar::setExclusive (bool _on) inline
Definition at line 60 of file TabBar.h.
References m_exclusive.
setTabState()
void lmms::gui::TabBar::setTabState (int _id, bool _checked) protected
Definition at line 156 of file TabBar.cpp.
References m_tabs.
Referenced by hideAll(), and setActiveTab().
tabClicked
void lmms::gui::TabBar::tabClicked (int _id) protected slot
Definition at line 194 of file TabBar.cpp.
References activeTab(), allHidden(), allWidgetsHidden(), hideAll(), m_exclusive, setActiveTab(), and widgetShown().
Referenced by addTab().
tabState()
bool lmms::gui::TabBar::tabState (int _id) protected
Definition at line 144 of file TabBar.cpp.
References m_tabs.
Referenced by activeTab(), and hideAll().
widgetShown
void lmms::gui::TabBar::widgetShown () signal
Referenced by setActiveTab(), and tabClicked().
Member Data Documentation
m_exclusive
bool lmms::gui::TabBar::m_exclusive private
Definition at line 86 of file TabBar.h.
Referenced by TabBar(), setExclusive(), and tabClicked().
m_layout
QBoxLayout* lmms::gui::TabBar::m_layout private
Definition at line 85 of file TabBar.h.
Referenced by TabBar(), and addTab().
m_tabs
QMap<int, QPair<TabButton *, QWidget *> > lmms::gui::TabBar::m_tabs private
Definition at line 84 of file TabBar.h.
Referenced by activeTab(), addTab(), allHidden(), hideAll(), removeTab(), setTabState(), and tabState().
The documentation for this class was generated from the following files:
include/TabBar.h
src/gui/widgets/TabBar.cpp