LMMS: lmms::gui::TrackLabelButton Class Reference
lmms::gui::TrackLabelButton Class Reference
#include <TrackLabelButton.h>
Public Slots
void nameChanged ()
void rename ()
void renameFinished ()
Public Member Functions
TrackLabelButton (TrackView *_tv, QWidget *_parent)
~TrackLabelButton () override=default
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void mouseDoubleClickEvent (QMouseEvent *_me) override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *pe) override
void resizeEvent (QResizeEvent *_re) override
Private Member Functions
QString elideName (const QString &name)
bool isInCompactMode () const
Private Attributes
QRect m_buttonRect
std::string m_iconName
TrackRenameLineEdit * m_renameLineEdit
TrackView * m_trackView
Detailed Description
Definition at line 40 of file TrackLabelButton.h.
Constructor & Destructor Documentation
TrackLabelButton()
lmms::gui::TrackLabelButton::TrackLabelButton (TrackView * _tv, QWidget * _parent)
Definition at line 43 of file TrackLabelButton.cpp.
References isInCompactMode(), m_iconName, m_renameLineEdit, m_trackView, nameChanged(), and renameFinished().
~TrackLabelButton()
lmms::gui::TrackLabelButton::~TrackLabelButton () override default
Member Function Documentation
dragEnterEvent()
void lmms::gui::TrackLabelButton::dragEnterEvent (QDragEnterEvent * _dee) override protected
Definition at line 140 of file TrackLabelButton.cpp.
References m_trackView.
dropEvent()
void lmms::gui::TrackLabelButton::dropEvent (QDropEvent * _de) override protected
Definition at line 148 of file TrackLabelButton.cpp.
References m_trackView.
elideName()
QString lmms::gui::TrackLabelButton::elideName (const QString & name) private
Definition at line 228 of file TrackLabelButton.cpp.
References m_trackView.
Referenced by nameChanged(), renameFinished(), and resizeEvent().
isInCompactMode()
bool lmms::gui::TrackLabelButton::isInCompactMode () const private
Definition at line 243 of file TrackLabelButton.cpp.
References lmms::ConfigManager::inst(), and lmms::ConfigManager::value().
Referenced by TrackLabelButton(), rename(), and renameFinished().
mouseDoubleClickEvent()
void lmms::gui::TrackLabelButton::mouseDoubleClickEvent (QMouseEvent * _me) override protected
Definition at line 174 of file TrackLabelButton.cpp.
References rename().
mousePressEvent()
void lmms::gui::TrackLabelButton::mousePressEvent (QMouseEvent * _me) override protected
Definition at line 158 of file TrackLabelButton.cpp.
References m_buttonRect, pos, and rename().
mouseReleaseEvent()
void lmms::gui::TrackLabelButton::mouseReleaseEvent (QMouseEvent * _me) override protected
Definition at line 182 of file TrackLabelButton.cpp.
References m_buttonRect, and m_renameLineEdit.
nameChanged
void lmms::gui::TrackLabelButton::nameChanged () slot
Definition at line 132 of file TrackLabelButton.cpp.
References elideName(), and m_trackView.
Referenced by TrackLabelButton().
paintEvent()
void lmms::gui::TrackLabelButton::paintEvent (QPaintEvent * pe) override protected
Definition at line 193 of file TrackLabelButton.cpp.
References lmms::Track::Instrument, m_iconName, m_trackView, lmms::PixmapLoader::pixmap(), and lmms::PixmapLoader::pixmapName().
rename
void lmms::gui::TrackLabelButton::rename () slot
Definition at line 76 of file TrackLabelButton.cpp.
References isInCompactMode(), m_renameLineEdit, and m_trackView.
Referenced by mouseDoubleClickEvent(), and mousePressEvent().
renameFinished
void lmms::gui::TrackLabelButton::renameFinished () slot
Definition at line 112 of file TrackLabelButton.cpp.
References elideName(), isInCompactMode(), m_renameLineEdit, and m_trackView.
Referenced by TrackLabelButton().
resizeEvent()
void lmms::gui::TrackLabelButton::resizeEvent (QResizeEvent * _re) override protected
Definition at line 220 of file TrackLabelButton.cpp.
References elideName(), and m_trackView.
Member Data Documentation
m_buttonRect
QRect lmms::gui::TrackLabelButton::m_buttonRect private
Definition at line 70 of file TrackLabelButton.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
m_iconName
std::string lmms::gui::TrackLabelButton::m_iconName private
Definition at line 68 of file TrackLabelButton.h.
Referenced by TrackLabelButton(), and paintEvent().
m_renameLineEdit
TrackRenameLineEdit* lmms::gui::TrackLabelButton::m_renameLineEdit private
Definition at line 69 of file TrackLabelButton.h.
Referenced by TrackLabelButton(), mouseReleaseEvent(), rename(), and renameFinished().
m_trackView
TrackView* lmms::gui::TrackLabelButton::m_trackView private
Definition at line 67 of file TrackLabelButton.h.
Referenced by TrackLabelButton(), dragEnterEvent(), dropEvent(), elideName(), nameChanged(), paintEvent(), rename(), renameFinished(), and resizeEvent().
The documentation for this class was generated from the following files:
include/TrackLabelButton.h
src/gui/tracks/TrackLabelButton.cpp