LMMS: src/3rdparty/jack2/windows/portaudio/JackPortAudioDriver.cpp File Reference
JackPortAudioDriver.cpp File Reference
#include "JackDriverLoader.h"
#include "driver_interface.h"
#include "JackPortAudioDriver.h"
#include "JackEngineControl.h"
#include "JackGraphManager.h"
#include "JackError.h"
#include "JackTime.h"
#include "JackTools.h"
#include "JackCompilerDeps.h"
#include <iostream>
#include <assert.h>
Namespaces
namespace Jack
Functions
SERVER_EXPORT jack_driver_desc_t * driver_get_descriptor ()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine *engine, Jack::JackSynchro *table, const JSList *params)
Function Documentation
driver_get_descriptor()
SERVER_EXPORT jack_driver_desc_t * driver_get_descriptor ()
Definition at line 444 of file JackPortAudioDriver.cpp.
References jack_driver_param_value_t::i, jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverMaster, JackDriverParamBool, JackDriverParamString, JackDriverParamUInt, SERVER_EXPORT, and jack_driver_param_value_t::ui.
driver_initialize()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine * engine, Jack::JackSynchro * table, const JSList * params)
Definition at line 485 of file JackPortAudioDriver.cpp.
References jack_driver_param_t::character, _JSList::data, PortAudioDevices::DisplayDevicesNames(), driver, jack_driver_param_value_t::i, jack_slist_next, SERVER_EXPORT, jack_driver_param_value_t::str, jack_driver_param_value_t::ui, and jack_driver_param_t::value.