LMMS: Jack::JackTools Struct Reference
Jack::JackTools Struct Reference
Utility functions.
#include <JackTools.h>
Static Public Member Functions
static void CleanupFiles (const char *server_name)
static int ComputationMicroSec (int buffer_size)
static const char * DefaultServerName ()
static int GetPID ()
static int GetTmpdir ()
static int GetUID ()
static void KillServer ()
static int MkDir (const char *path)
static void RewriteName (const char *name, char *new_name)
static const char * ServerDir (const char *server_name, char *server_dir)
static void ThrowJackNetException ()
static const char * UserDir ()
Detailed Description
Utility functions.
Definition at line 55 of file JackTools.h.
Member Function Documentation
CleanupFiles()
void Jack::JackTools::CleanupFiles (const char * server_name) static
Definition at line 135 of file JackTools.cpp.
References jack_error, JACK_PATH_MAX, server_name, ServerDir(), and UserDir().
Referenced by Jack::JackServerGlobals::Destroy(), Jack::JackServerGlobals::Init(), jackctl_server_close(), and jackctl_server_open().
ComputationMicroSec()
int Jack::JackTools::ComputationMicroSec (int buffer_size) inline static
Definition at line 72 of file JackTools.h.
Referenced by Jack::JackNetExtSlave::Init(), Jack::JackPortAudioDriver::Open(), and Jack::JackThreadedDriver::SetRealTime().
DefaultServerName()
const char * Jack::JackTools::DefaultServerName () static
Definition at line 79 of file JackTools.cpp.
References JACK_DEFAULT_SERVER_NAME, and server_name.
Referenced by Jack::JackServerGlobals::Init(), Jack::JackServer::InternalClientLoadAux(), and jackctl_server_create2().
GetPID()
int Jack::JackTools::GetPID () static
Definition at line 60 of file JackTools.cpp.
Referenced by KillServer(), and Jack::JackLibClient::Open().
GetTmpdir()
int Jack::JackTools::GetTmpdir () static
Definition at line 194 of file JackTools.cpp.
References JACK_PATH_MAX, and Jack::jack_tmpdir.
GetUID()
int Jack::JackTools::GetUID () static
Definition at line 69 of file JackTools.cpp.
Referenced by Jack::JackMetadata::~JackMetadata(), Jack::BuildName(), Jack::JackAndroidSemaphore::BuildName(), Jack::JackFifo::BuildName(), Jack::JackLinuxFutex::BuildName(), Jack::JackPosixSemaphore::BuildName(), Jack::JackMetadata::PropertyInit(), and UserDir().
KillServer()
void Jack::JackTools::KillServer () static
Definition at line 39 of file JackTools.cpp.
References GetPID().
MkDir()
int Jack::JackTools::MkDir (const char * path) static
Definition at line 48 of file JackTools.cpp.
Referenced by Jack::JackEngine::SessionNotify().
RewriteName()
void Jack::JackTools::RewriteName (const char * name, char * new_name) static
Definition at line 226 of file JackTools.cpp.
References i.
Referenced by Jack::BuildName(), Jack::JackAndroidSemaphore::BuildName(), Jack::JackFifo::BuildName(), Jack::JackLinuxFutex::BuildName(), Jack::JackPosixSemaphore::BuildName(), and Jack::JackWinSemaphore::BuildName().
ServerDir()
const char * Jack::JackTools::ServerDir (const char * server_name, char * server_dir) static
Definition at line 126 of file JackTools.cpp.
References JACK_PATH_MAX, server_name, and UserDir().
Referenced by CleanupFiles().
ThrowJackNetException()
void Jack::JackTools::ThrowJackNetException () static
UserDir()
const char * Jack::JackTools::UserDir () static
Definition at line 109 of file JackTools.cpp.
References GetUID(), JACK_PATH_MAX, and Jack::jack_tmpdir.
Referenced by CleanupFiles(), and ServerDir().
The documentation for this struct was generated from the following files:
src/3rdparty/jack2/common/JackTools.h
src/3rdparty/jack2/common/JackTools.cpp