LMMS: lmms::graphModel Class Reference
lmms::graphModel Class Reference
2 dimensional function plot
#include <Graph.h>
Public Slots
void clear ()
void clearInvisible ()
void invert ()
void normalize ()
void setLength (int _size)
void setRange (float ymin, float ymax)
Set range of y values.
void setSampleAt (int x, float val)
Update one sample.
void setSamples (const float *_value)
Update samples array.
void setWaveToNoise ()
void setWaveToSaw ()
void setWaveToSine ()
void setWaveToSquare ()
void setWaveToTriangle ()
QString setWaveToUser ()
void shiftPhase (int _deg)
void smooth ()
void smoothNonCyclic ()
Signals
void lengthChanged ()
void rangeChanged ()
void samplesChanged (int startPos, int endPos)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
graphModel (float _min, float _max, int _size, Model *_parent, bool _default_constructed=false, float _step=0.0)
Constructor.
~graphModel () override=default
void convolve (const float *convolution, const int convolutionLength, const int centerOffset)
Make cyclic convolution.
int length () const
float maxValue () const
float minValue () const
const float * samples () const
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Private Member Functions
void drawSampleAt (int x, float val)
Private Attributes
int m_length
float m_maxValue
float m_minValue
QVector< float > m_samples
float m_step
Friends
class gui::Graph
Detailed Description
2 dimensional function plot
Function plot graph with discrete x scale and continous y scale This makes it possible to display "#x" samples
Definition at line 133 of file Graph.h.
Constructor & Destructor Documentation
graphModel()
lmms::graphModel::graphModel (float _min, float _max, int _size, Model * _parent, bool _default_constructed = false, float _step = 0.0)
Constructor.
Parameters
_min Minimum y value to display
_max Maximum y value to display
_size Number of samples (e.g. x value)
_step Step size on y axis where values snap to, or 0.0f for "no snapping"
Definition at line 461 of file Graph.cpp.
References lmms::Model::Model(), length(), m_length, m_maxValue, m_minValue, m_samples, and m_step.
~graphModel()
lmms::graphModel::~graphModel () override default
Member Function Documentation
clear
void lmms::graphModel::clear () slot
Definition at line 707 of file Graph.cpp.
References i, length(), m_samples, and samplesChanged().
clearInvisible
void lmms::graphModel::clearInvisible () slot
Definition at line 717 of file Graph.cpp.
References i, length(), m_samples, and samplesChanged().
convolve()
void lmms::graphModel::convolve (const float * convolution, const int convolutionLength, const int centerOffset)
Make cyclic convolution.
Parameters
convolution Samples to convolve with
convolutionLength Number of samples to take for each sum
centerOffset Offset for resulting values
Definition at line 631 of file Graph.cpp.
References i, j, length(), m_samples, and samplesChanged().
drawSampleAt()
void lmms::graphModel::drawSampleAt (int x, float val) private
Definition at line 726 of file Graph.cpp.
References length(), m_samples, m_step, maxValue(), and minValue().
Referenced by lmms::gui::Graph::drawLineAt(), rangeChanged(), and setSampleAt().
invert
void lmms::graphModel::invert () slot
Definition at line 676 of file Graph.cpp.
References i, length(), m_maxValue, m_minValue, m_samples, and samplesChanged().
length()
int lmms::graphModel::length () const inline
Definition at line 166 of file Graph.h.
References m_length.
Referenced by graphModel(), lmms::gui::Graph::changeSampleAt(), clear(), clearInvisible(), convolve(), lmms::gui::Graph::drawLineAt(), drawSampleAt(), invert(), normalize(), lmms::gui::Graph::paintEvent(), setSamples(), setWaveToNoise(), setWaveToSaw(), setWaveToSine(), setWaveToSquare(), setWaveToTriangle(), setWaveToUser(), shiftPhase(), smooth(), and smoothNonCyclic().
lengthChanged
void lmms::graphModel::lengthChanged () signal
Referenced by setLength().
maxValue()
float lmms::graphModel::maxValue () const inline
Definition at line 161 of file Graph.h.
References m_maxValue.
Referenced by lmms::gui::Graph::changeSampleAt(), lmms::gui::Graph::drawLineAt(), drawSampleAt(), and lmms::gui::Graph::paintEvent().
minValue()
float lmms::graphModel::minValue () const inline
Definition at line 156 of file Graph.h.
References m_minValue.
Referenced by lmms::gui::Graph::changeSampleAt(), lmms::gui::Graph::drawLineAt(), drawSampleAt(), and lmms::gui::Graph::paintEvent().
normalize
void lmms::graphModel::normalize () slot
Definition at line 650 of file Graph.cpp.
References i, length(), m_maxValue, m_minValue, m_samples, max, and samplesChanged().
rangeChanged
void lmms::graphModel::rangeChanged () signal
References drawSampleAt().
Referenced by setRange().
samples()
const float * lmms::graphModel::samples () const inline
Definition at line 171 of file Graph.h.
References m_samples.
samplesChanged
void lmms::graphModel::samplesChanged (int startPos, int endPos) signal
Referenced by clear(), clearInvisible(), convolve(), lmms::gui::Graph::drawLineAt(), invert(), normalize(), setSampleAt(), setSamples(), setWaveToNoise(), setWaveToSaw(), setWaveToSine(), setWaveToSquare(), setWaveToTriangle(), setWaveToUser(), shiftPhase(), smooth(), and smoothNonCyclic().
setLength
void lmms::graphModel::setLength (int _size) slot
Definition at line 486 of file Graph.cpp.
References lengthChanged(), m_length, and m_samples.
setRange
void lmms::graphModel::setRange (float ymin, float ymax) slot
Set range of y values.
Definition at line 471 of file Graph.cpp.
References m_maxValue, m_minValue, m_samples, m_step, and rangeChanged().
setSampleAt
void lmms::graphModel::setSampleAt (int x, float val) slot
Update one sample.
Definition at line 501 of file Graph.cpp.
References drawSampleAt(), and samplesChanged().
Referenced by lmms::gui::Graph::changeSampleAt().
setSamples
void lmms::graphModel::setSamples (const float * _value) slot
Update samples array.
Definition at line 509 of file Graph.cpp.
References length(), m_samples, and samplesChanged().
setWaveToNoise
void lmms::graphModel::setWaveToNoise () slot
Definition at line 570 of file Graph.cpp.
References i, length(), m_samples, lmms::Oscillator::noiseSample(), and samplesChanged().
setWaveToSaw
void lmms::graphModel::setWaveToSaw () slot
Definition at line 544 of file Graph.cpp.
References i, length(), m_samples, samplesChanged(), and lmms::Oscillator::sawSample().
setWaveToSine
void lmms::graphModel::setWaveToSine () slot
Definition at line 518 of file Graph.cpp.
References i, length(), m_samples, samplesChanged(), and lmms::Oscillator::sinSample().
setWaveToSquare
void lmms::graphModel::setWaveToSquare () slot
Definition at line 557 of file Graph.cpp.
References i, length(), m_samples, samplesChanged(), and lmms::Oscillator::squareSample().
setWaveToTriangle
void lmms::graphModel::setWaveToTriangle () slot
Definition at line 531 of file Graph.cpp.
References i, length(), m_samples, samplesChanged(), and lmms::Oscillator::triangleSample().
setWaveToUser
QString lmms::graphModel::setWaveToUser () slot
Definition at line 581 of file Graph.cpp.
References lmms::gui::SampleLoader::createBufferFromFile(), i, length(), m_samples, lmms::gui::SampleLoader::openWaveformFile(), samplesChanged(), and lmms::Oscillator::userWaveSample().
shiftPhase
void lmms::graphModel::shiftPhase (int _deg) slot
Definition at line 688 of file Graph.cpp.
References i, length(), m_samples, and samplesChanged().
smooth
void lmms::graphModel::smooth () slot
Definition at line 599 of file Graph.cpp.
References i, length(), m_samples, and samplesChanged().
smoothNonCyclic
void lmms::graphModel::smoothNonCyclic () slot
Definition at line 615 of file Graph.cpp.
References i, length(), m_samples, and samplesChanged().
Friends And Related Symbol Documentation
gui::Graph
friend class gui::Graph friend
Definition at line 222 of file Graph.h.
Member Data Documentation
m_length
int lmms::graphModel::m_length private
Definition at line 217 of file Graph.h.
Referenced by graphModel(), length(), and setLength().
m_maxValue
float lmms::graphModel::m_maxValue private
Definition at line 219 of file Graph.h.
Referenced by graphModel(), invert(), maxValue(), normalize(), and setRange().
m_minValue
float lmms::graphModel::m_minValue private
Definition at line 218 of file Graph.h.
Referenced by graphModel(), invert(), minValue(), normalize(), and setRange().
m_samples
QVector<float> lmms::graphModel::m_samples private
Definition at line 216 of file Graph.h.
Referenced by graphModel(), clear(), clearInvisible(), convolve(), drawSampleAt(), invert(), normalize(), lmms::gui::Graph::paintEvent(), samples(), setLength(), setRange(), setSamples(), setWaveToNoise(), setWaveToSaw(), setWaveToSine(), setWaveToSquare(), setWaveToTriangle(), setWaveToUser(), shiftPhase(), smooth(), and smoothNonCyclic().
m_step
float lmms::graphModel::m_step private
Definition at line 220 of file Graph.h.
Referenced by graphModel(), drawSampleAt(), and setRange().
The documentation for this class was generated from the following files:
include/Graph.h
src/gui/widgets/Graph.cpp