LMMS: Jack::JackResampler Class Reference
Jack::JackResampler Class Reference
Base class for Resampler.
#include <JackResampler.h>
Public Member Functions
JackResampler ()
virtual ~JackResampler ()
double GetRatio ()
virtual unsigned int ReadResample (jack_default_audio_sample_t *buffer, unsigned int frames)
void SetRatio (double ratio)
virtual unsigned int WriteResample (jack_default_audio_sample_t *buffer, unsigned int frames)
Public Member Functions inherited from Jack::JackRingBuffer
JackRingBuffer (int size=DEFAULT_RB_SIZE)
virtual ~JackRingBuffer ()
unsigned int GetError ()
virtual unsigned int Read (jack_default_audio_sample_t *buffer, unsigned int frames)
virtual unsigned int Read (void *buffer, unsigned int bytes)
virtual unsigned int ReadSpace ()
virtual void Reset (unsigned int new_size)
virtual unsigned int Write (jack_default_audio_sample_t *buffer, unsigned int frames)
virtual unsigned int Write (void *buffer, unsigned int bytes)
virtual unsigned int WriteSpace ()
Protected Attributes
double fRatio
Protected Attributes inherited from Jack::JackRingBuffer
jack_ringbuffer_t * fRingBuffer
unsigned int fRingBufferSize
Detailed Description
Base class for Resampler.
Definition at line 79 of file JackResampler.h.
Constructor & Destructor Documentation
JackResampler()
Jack::JackResampler::JackResampler () inline
Definition at line 88 of file JackResampler.h.
References Jack::JackRingBuffer::JackRingBuffer(), and fRatio.
Referenced by Jack::JackLibSampleRateResampler::JackLibSampleRateResampler(), and Jack::JackLibSampleRateResampler::JackLibSampleRateResampler().
~JackResampler()
virtual Jack::JackResampler::~JackResampler () inline virtual
Definition at line 90 of file JackResampler.h.
Member Function Documentation
GetRatio()
double Jack::JackResampler::GetRatio () inline
Definition at line 101 of file JackResampler.h.
References fRatio.
ReadResample()
unsigned int Jack::JackResampler::ReadResample (jack_default_audio_sample_t * buffer, unsigned int frames) virtual
Reimplemented in Jack::JackLibSampleRateResampler.
Definition at line 114 of file JackResampler.cpp.
References Jack::JackRingBuffer::Read().
SetRatio()
void Jack::JackResampler::SetRatio (double ratio) inline
Definition at line 96 of file JackResampler.h.
References fRatio, and Jack::Range().
WriteResample()
unsigned int Jack::JackResampler::WriteResample (jack_default_audio_sample_t * buffer, unsigned int frames) virtual
Reimplemented in Jack::JackLibSampleRateResampler.
Definition at line 119 of file JackResampler.cpp.
References Jack::JackRingBuffer::Write().
Member Data Documentation
fRatio
double Jack::JackResampler::fRatio protected
Definition at line 84 of file JackResampler.h.
Referenced by JackResampler(), GetRatio(), Jack::JackLibSampleRateResampler::ReadResample(), SetRatio(), and Jack::JackLibSampleRateResampler::WriteResample().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackResampler.h
src/3rdparty/jack2/common/JackResampler.cpp