LMMS: Jack::JackSapaProxy Class Reference
Jack::JackSapaProxy Class Reference
#include <JackSapaProxy.h>
Public Member Functions
JackSapaProxy (jack_client_t *jack_client, const JSList *params)
~JackSapaProxy ()
int Setup (jack_client_t *jack_client)
Static Public Member Functions
static int Process (jack_nframes_t nframes, void *arg)
Public Attributes
unsigned int fCapturePorts
unsigned int fPlaybackPorts
Private Attributes
jack_client_t * fClient
jack_port_t * fInputPorts [SAPAPROXY_PORT_NUM_FOR_CLIENT]
jack_port_t * fOutputPorts [SAPAPROXY_PORT_NUM_FOR_CLIENT]
Detailed Description
Definition at line 35 of file JackSapaProxy.h.
Constructor & Destructor Documentation
JackSapaProxy()
Jack::JackSapaProxy::JackSapaProxy (jack_client_t * jack_client, const JSList * params)
Definition at line 45 of file JackSapaProxy.cpp.
References jack_driver_param_t::character, client(), _JSList::data, fCapturePorts, fClient, fPlaybackPorts, jack_log(), jack_slist_next, SAPAPROXY_PORT_NUM_FOR_CLIENT, jack_driver_param_value_t::ui, and jack_driver_param_t::value.
Referenced by Process().
~JackSapaProxy()
Jack::JackSapaProxy::~JackSapaProxy ()
Definition at line 69 of file JackSapaProxy.cpp.
References jack_log().
Member Function Documentation
Process()
int Jack::JackSapaProxy::Process (jack_nframes_t nframes, void * arg) static
Definition at line 130 of file JackSapaProxy.cpp.
References JackSapaProxy(), i, jack_port_get_buffer(), and sapaproxy.
Referenced by Setup().
Setup()
int Jack::JackSapaProxy::Setup (jack_client_t * jack_client)
Definition at line 74 of file JackSapaProxy.cpp.
References client(), fCapturePorts, fInputPorts, fOutputPorts, fPlaybackPorts, i, j, jack_activate(), jack_connect(), JACK_DEFAULT_AUDIO_TYPE, jack_free(), jack_get_ports(), jack_log(), jack_port_name(), JACK_PORT_NAME_SIZE, jack_port_register(), jack_set_process_callback(), JackPortIsInput, JackPortIsOutput, JackPortIsPhysical, and Process().
Member Data Documentation
fCapturePorts
unsigned int Jack::JackSapaProxy::fCapturePorts
Definition at line 46 of file JackSapaProxy.h.
Referenced by JackSapaProxy(), and Setup().
fClient
jack_client_t* Jack::JackSapaProxy::fClient private
Definition at line 40 of file JackSapaProxy.h.
Referenced by JackSapaProxy().
fInputPorts
jack_port_t* Jack::JackSapaProxy::fInputPorts[SAPAPROXY_PORT_NUM_FOR_CLIENT] private
Definition at line 41 of file JackSapaProxy.h.
Referenced by Setup().
fOutputPorts
jack_port_t* Jack::JackSapaProxy::fOutputPorts[SAPAPROXY_PORT_NUM_FOR_CLIENT] private
Definition at line 42 of file JackSapaProxy.h.
Referenced by Setup().
fPlaybackPorts
unsigned int Jack::JackSapaProxy::fPlaybackPorts
Definition at line 47 of file JackSapaProxy.h.
Referenced by JackSapaProxy(), and Setup().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/android/JackSapaProxy.h
src/3rdparty/jack2/android/JackSapaProxy.cpp