LMMS: hiir::StageProc3dnow< CUR > Class Template Reference
hiir::StageProc3dnow< CUR > Class Template Reference
#include <StageProc3dnow.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg () noexcept
hiir_FORCEINLINE void process_sample_pos () noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg () noexcept
static hiir_FORCEINLINE void process_sample_pos () noexcept
Private Member Functions
StageProc3dnow ()=delete
StageProc3dnow (const StageProc3dnow< CUR > &other)=delete
StageProc3dnow (StageProc3dnow< CUR > &&other)=delete
~StageProc3dnow ()=delete
bool operator!= (const StageProc3dnow< CUR > &other) const =delete
StageProc3dnow & operator= (const StageProc3dnow< CUR > &other)=delete
StageProc3dnow & operator= (StageProc3dnow< CUR > &&other)=delete
bool operator== (const StageProc3dnow< CUR > &other) const =delete
Detailed Description
template<int CUR>
class hiir::StageProc3dnow< CUR >
Definition at line 43 of file StageProc3dnow.h.
Constructor & Destructor Documentation
StageProc3dnow() [1/3]
template<int CUR> hiir::StageProc3dnow< CUR >::StageProc3dnow () private delete
Referenced by ~StageProc3dnow(), operator=(), process_sample_neg(), and process_sample_pos().
StageProc3dnow() [2/3]
template<int CUR> hiir::StageProc3dnow< CUR >::StageProc3dnow (const StageProc3dnow< CUR > & other) private delete
StageProc3dnow() [3/3]
template<int CUR> hiir::StageProc3dnow< CUR >::StageProc3dnow (StageProc3dnow< CUR > && other) private delete
~StageProc3dnow()
template<int CUR> hiir::StageProc3dnow< CUR >::~StageProc3dnow () private delete
References StageProc3dnow().
Member Function Documentation
operator!=()
template<int CUR> bool hiir::StageProc3dnow< CUR >::operator!= (const StageProc3dnow< CUR > & other) const private delete
operator=() [1/2]
template<int CUR> StageProc3dnow & hiir::StageProc3dnow< CUR >::operator= (const StageProc3dnow< CUR > & other) private delete
References StageProc3dnow().
operator=() [2/2]
template<int CUR> StageProc3dnow & hiir::StageProc3dnow< CUR >::operator= (StageProc3dnow< CUR > && other) private delete
operator==()
template<int CUR> bool hiir::StageProc3dnow< CUR >::operator== (const StageProc3dnow< CUR > & other) const private delete
process_sample_neg() [1/2]
template<int CUR> void hiir::StageProc3dnow< CUR >::process_sample_neg () static noexcept
Definition at line 78 of file StageProc3dnow.hpp.
References StageProc3dnow(), and process_sample_neg().
Referenced by hiir::PhaseHalfPi3dnow< NC >::process_block(), hiir::PhaseHalfPi3dnow< NC >::process_sample(), and process_sample_neg().
process_sample_neg() [2/2]
hiir_FORCEINLINE void hiir::StageProc3dnow< 0 >::process_sample_neg () noexcept
Definition at line 97 of file StageProc3dnow.hpp.
References hiir_FORCEINLINE.
process_sample_pos() [1/2]
template<int CUR> void hiir::StageProc3dnow< CUR >::process_sample_pos () static noexcept
Definition at line 51 of file StageProc3dnow.hpp.
References StageProc3dnow(), and process_sample_pos().
Referenced by hiir::Downsampler2x3dnow< NC >::process_block(), hiir::Upsampler2x3dnow< NC >::process_block(), hiir::Downsampler2x3dnow< NC >::process_block_split(), hiir::Downsampler2x3dnow< NC >::process_sample(), hiir::Upsampler2x3dnow< NC >::process_sample(), process_sample_pos(), and hiir::Downsampler2x3dnow< NC >::process_sample_split().
process_sample_pos() [2/2]
hiir_FORCEINLINE void hiir::StageProc3dnow< 0 >::process_sample_pos () noexcept
Definition at line 70 of file StageProc3dnow.hpp.
References hiir_FORCEINLINE.
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProc3dnow.h
src/3rdparty/hiir/hiir/StageProc3dnow.hpp