LMMS: Jack::JackServer Class Reference
Jack::JackServer Class Reference
The Jack server.
#include <JackServer.h>
Public Member Functions
JackServer (bool sync, bool temporary, int timeout, bool rt, int priority, int port_max, bool verbose, jack_timer_type_t clock, char self_connect_mode, const char *server_name)
~JackServer ()
JackDriverInfo * AddSlave (jack_driver_desc_t *driver_desc, JSList *driver_params)
int Close ()
JackLockedEngine * GetEngine ()
JackEngineControl * GetEngineControl ()
JackGraphManager * GetGraphManager ()
JackMetadata * GetMetadata ()
JackSynchro * GetSynchroTable ()
int InternalClientLoad1 (const char *client_name, const char *so_name, const char *objet_data, int options, int *int_ref, jack_uuid_t uuid, int *status)
int InternalClientLoad2 (const char *client_name, const char *so_name, const JSList *parameters, int options, int *int_ref, jack_uuid_t uuid, int *status)
bool IsRunning ()
int LoadInternalSessionFile (const char *file)
void Notify (int refnum, int notify, int value)
int Open (jack_driver_desc_t *driver_desc, JSList *driver_params)
int ReleaseTimebase (int refnum)
void RemoveSlave (JackDriverInfo *info)
int SetBufferSize (jack_nframes_t buffer_size)
int SetFreewheel (bool onoff)
int SetTimebaseCallback (int refnum, int conditional)
int Start ()
int Stop ()
int SwitchMaster (jack_driver_desc_t *driver_desc, JSList *driver_params)
Private Member Functions
int InternalClientLoadAux (JackLoadableInternalClient *client, const char *so_name, const char *client_name, int options, int *int_ref, jack_uuid_t uuid, int *status)
Private Attributes
JackDriverClientInterface * fAudioDriver
JackConnectionManager fConnectionState
JackDriverInfo * fDriverInfo
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
bool fFreewheel
JackDriverClientInterface * fFreewheelDriver
JackGraphManager * fGraphManager
JackMetadata * fMetadata
JackServerChannel fRequestChannel
JackSynchro fSynchroTable [CLIENT_NUM]
JackDriverClientInterface * fThreadedFreewheelDriver
Detailed Description
The Jack server.
Definition at line 47 of file JackServer.h.
Constructor & Destructor Documentation
JackServer()
Jack::JackServer::JackServer (bool sync, bool temporary, int timeout, bool rt, int priority, int port_max, bool verbose, jack_timer_type_t clock, char self_connect_mode, const char * server_name)
Definition at line 46 of file JackServer.cpp.
References Jack::JackGraphManager::Allocate(), fAudioDriver, fDriverInfo, fEngine, fEngineControl, fFreewheel, fFreewheelDriver, fGraphManager, Jack::JackServerGlobals::fInstance, fMetadata, fThreadedFreewheelDriver, Jack::JackServerGlobals::fUserCount, Jack::JackGlobals::fVerbose, GetSynchroTable(), jack_get_self_connect_mode_description(), jack_info(), and server_name.
~JackServer()
Jack::JackServer::~JackServer ()
Definition at line 77 of file JackServer.cpp.
References Jack::JackGraphManager::Destroy(), fDriverInfo, fEngine, fEngineControl, fGraphManager, fMetadata, and fThreadedFreewheelDriver.
Member Function Documentation
AddSlave()
JackDriverInfo * Jack::JackServer::AddSlave (jack_driver_desc_t * driver_desc, JSList * driver_params)
Definition at line 352 of file JackServer.cpp.
References Jack::JackDriverInterface::Attach(), Jack::JackClientInterface::Close(), fAudioDriver, fEngine, GetSynchroTable(), JackDriverInfo::Open(), and Jack::JackDriverInterface::SetMaster().
Referenced by jackctl_server_add_slave().
Close()
int Jack::JackServer::Close ()
Definition at line 143 of file JackServer.cpp.
References Jack::JackMessageBuffer::Destroy(), EndTime(), fAudioDriver, fEngine, fFreewheelDriver, fRequestChannel, and jack_log().
Referenced by jackctl_server_close().
GetEngine()
JackLockedEngine * Jack::JackServer::GetEngine ()
Definition at line 449 of file JackServer.cpp.
References fEngine.
Referenced by jackctl_server_unload_internal().
GetEngineControl()
JackEngineControl * Jack::JackServer::GetEngineControl ()
Definition at line 459 of file JackServer.cpp.
References fEngineControl.
GetGraphManager()
JackGraphManager * Jack::JackServer::GetGraphManager ()
Definition at line 464 of file JackServer.cpp.
References fGraphManager.
GetMetadata()
JackMetadata * Jack::JackServer::GetMetadata ()
Definition at line 469 of file JackServer.cpp.
References fMetadata.
GetSynchroTable()
JackSynchro * Jack::JackServer::GetSynchroTable ()
Definition at line 454 of file JackServer.cpp.
References fSynchroTable.
Referenced by JackServer(), AddSlave(), InternalClientLoad1(), InternalClientLoad2(), Open(), and SwitchMaster().
InternalClientLoad1()
int Jack::JackServer::InternalClientLoad1 (const char * client_name, const char * so_name, const char * objet_data, int options, int * int_ref, jack_uuid_t uuid, int * status)
Definition at line 199 of file JackServer.cpp.
References client(), Jack::JackServerGlobals::fInstance, GetSynchroTable(), and InternalClientLoadAux().
InternalClientLoad2()
int Jack::JackServer::InternalClientLoad2 (const char * client_name, const char * so_name, const JSList * parameters, int options, int * int_ref, jack_uuid_t uuid, int * status)
Definition at line 206 of file JackServer.cpp.
References client(), Jack::JackServerGlobals::fInstance, GetSynchroTable(), and InternalClientLoadAux().
Referenced by jackctl_server_load_internal().
InternalClientLoadAux()
int Jack::JackServer::InternalClientLoadAux (JackLoadableInternalClient * client, const char * so_name, const char * client_name, int options, int * int_ref, jack_uuid_t uuid, int * status) private
Definition at line 213 of file JackServer.cpp.
References client(), Jack::JackTools::DefaultServerName(), and JackFailure.
Referenced by InternalClientLoad1(), and InternalClientLoad2().
IsRunning()
bool Jack::JackServer::IsRunning ()
Definition at line 188 of file JackServer.cpp.
References fAudioDriver, and jack_log().
Referenced by jackctl_server_add_slave(), and jackctl_server_remove_slave().
LoadInternalSessionFile()
int Jack::JackServer::LoadInternalSessionFile (const char * file)
Definition at line 235 of file JackServer.cpp.
References file, and Jack::JackInternalSessionLoader::Load().
Referenced by jackctl_server_load_session_file().
Notify()
void Jack::JackServer::Notify (int refnum, int notify, int value)
Definition at line 334 of file JackServer.cpp.
References fEngine, Jack::kGraphOrderCallback, and Jack::kXRunCallback.
Open()
int Jack::JackServer::Open (jack_driver_desc_t * driver_desc, JSList * driver_params)
Definition at line 87 of file JackServer.cpp.
References Jack::JackMessageBuffer::Create(), Jack::JackMessageBuffer::Destroy(), fAudioDriver, fDriverInfo, fEngine, fEngineControl, fFreewheelDriver, fRequestChannel, GetSynchroTable(), InitTime(), jack_error, and SetClockSource().
Referenced by jackctl_server_open().
ReleaseTimebase()
int Jack::JackServer::ReleaseTimebase (int refnum)
Definition at line 439 of file JackServer.cpp.
References fEngineControl.
RemoveSlave()
void Jack::JackServer::RemoveSlave (JackDriverInfo * info)
Definition at line 376 of file JackServer.cpp.
References Jack::JackClientInterface::Close(), Jack::JackDriverInterface::Detach(), fAudioDriver, and JackDriverInfo::GetBackend().
Referenced by jackctl_server_remove_slave().
SetBufferSize()
int Jack::JackServer::SetBufferSize (jack_nframes_t buffer_size)
Definition at line 245 of file JackServer.cpp.
References fAudioDriver, fEngine, fEngineControl, jack_error, and jack_log().
SetFreewheel()
int Jack::JackServer::SetFreewheel (bool onoff)
Definition at line 289 of file JackServer.cpp.
References fAudioDriver, fConnectionState, fEngine, fFreewheel, fFreewheelDriver, fGraphManager, Jack::JackClientControl::fRefNum, fThreadedFreewheelDriver, Jack::JackDriver::GetClientControl(), and jack_log().
SetTimebaseCallback()
int Jack::JackServer::SetTimebaseCallback (int refnum, int conditional)
Definition at line 444 of file JackServer.cpp.
References fEngineControl.
Start()
int Jack::JackServer::Start ()
Definition at line 157 of file JackServer.cpp.
References fAudioDriver, fRequestChannel, and jack_log().
Referenced by jackctl_server_start().
Stop()
int Jack::JackServer::Stop ()
Definition at line 166 of file JackServer.cpp.
References fAudioDriver, fEngine, fFreewheel, fRequestChannel, fThreadedFreewheelDriver, jack_log(), JACK_SERVER_FAILURE, JackFailure, and JackServerError.
Referenced by jackctl_server_stop().
SwitchMaster()
int Jack::JackServer::SwitchMaster (jack_driver_desc_t * driver_desc, JSList * driver_params)
Definition at line 384 of file JackServer.cpp.
References Jack::JackDriverInterface::AddSlave(), fAudioDriver, fDriverInfo, fEngine, fEngineControl, GetSynchroTable(), and JackDriverInfo::Open().
Referenced by jackctl_server_switch_master().
Member Data Documentation
fAudioDriver
JackDriverClientInterface* Jack::JackServer::fAudioDriver private
Definition at line 53 of file JackServer.h.
Referenced by JackServer(), AddSlave(), Close(), IsRunning(), Open(), RemoveSlave(), SetBufferSize(), SetFreewheel(), Start(), Stop(), and SwitchMaster().
fConnectionState
JackConnectionManager Jack::JackServer::fConnectionState private
Definition at line 61 of file JackServer.h.
Referenced by SetFreewheel().
fDriverInfo
JackDriverInfo* Jack::JackServer::fDriverInfo private
Definition at line 52 of file JackServer.h.
Referenced by JackServer(), ~JackServer(), Open(), and SwitchMaster().
fEngine
JackLockedEngine* Jack::JackServer::fEngine private
Definition at line 56 of file JackServer.h.
Referenced by JackServer(), ~JackServer(), AddSlave(), Close(), GetEngine(), Notify(), Open(), SetBufferSize(), SetFreewheel(), Stop(), and SwitchMaster().
fEngineControl
JackEngineControl* Jack::JackServer::fEngineControl private
Definition at line 57 of file JackServer.h.
Referenced by JackServer(), ~JackServer(), GetEngineControl(), Open(), ReleaseTimebase(), SetBufferSize(), SetTimebaseCallback(), and SwitchMaster().
fFreewheel
bool Jack::JackServer::fFreewheel private
Definition at line 63 of file JackServer.h.
Referenced by JackServer(), SetFreewheel(), and Stop().
fFreewheelDriver
JackDriverClientInterface* Jack::JackServer::fFreewheelDriver private
Definition at line 54 of file JackServer.h.
Referenced by JackServer(), Close(), Open(), and SetFreewheel().
fGraphManager
JackGraphManager* Jack::JackServer::fGraphManager private
Definition at line 58 of file JackServer.h.
Referenced by JackServer(), ~JackServer(), GetGraphManager(), and SetFreewheel().
fMetadata
JackMetadata* Jack::JackServer::fMetadata private
Definition at line 59 of file JackServer.h.
Referenced by JackServer(), ~JackServer(), and GetMetadata().
fRequestChannel
JackServerChannel Jack::JackServer::fRequestChannel private
Definition at line 60 of file JackServer.h.
Referenced by Close(), Open(), Start(), and Stop().
fSynchroTable
JackSynchro Jack::JackServer::fSynchroTable[CLIENT_NUM] private
Definition at line 62 of file JackServer.h.
Referenced by GetSynchroTable().
fThreadedFreewheelDriver
JackDriverClientInterface* Jack::JackServer::fThreadedFreewheelDriver private
Definition at line 55 of file JackServer.h.
Referenced by JackServer(), ~JackServer(), SetFreewheel(), and Stop().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackServer.h
src/3rdparty/jack2/common/JackServer.cpp