LMMS: Jack::JackWinProcessSync Class Reference
Jack::JackWinProcessSync Class Reference
A synchronization primitive built using a condition variable.
#include <JackWinProcessSync.h>
Public Member Functions
JackWinProcessSync (const char *name=NULL)
virtual ~JackWinProcessSync ()
void LockedSignal ()
void LockedSignalAll ()
bool LockedTimedWait (long usec)
void LockedWait ()
void Signal ()
void SignalAll ()
bool TimedWait (long usec)
void Wait ()
Public Member Functions inherited from Jack::JackWinMutex
JackWinMutex (const char *name=NULL)
virtual ~JackWinMutex ()
bool Lock ()
bool Trylock ()
bool Unlock ()
Private Attributes
HANDLE fEvent
Additional Inherited Members
Protected Attributes inherited from Jack::JackWinMutex
HANDLE fMutex
Detailed Description
A synchronization primitive built using a condition variable.
Definition at line 32 of file JackWinProcessSync.h.
Constructor & Destructor Documentation
JackWinProcessSync()
Jack::JackWinProcessSync::JackWinProcessSync (const char * name = NULL) inline
Definition at line 41 of file JackWinProcessSync.h.
References Jack::JackWinMutex::JackWinMutex(), FALSE, fEvent, MAX_PATH, ThrowIf, and TRUE.
~JackWinProcessSync()
virtual Jack::JackWinProcessSync::~JackWinProcessSync () inline virtual
Definition at line 55 of file JackWinProcessSync.h.
References fEvent.
Member Function Documentation
LockedSignal()
void Jack::JackWinProcessSync::LockedSignal ()
Definition at line 33 of file JackWinProcessSync.cpp.
References fEvent, Jack::JackWinMutex::fMutex, and jack_error.
Referenced by LockedSignalAll().
LockedSignalAll()
void Jack::JackWinProcessSync::LockedSignalAll ()
Definition at line 52 of file JackWinProcessSync.cpp.
References LockedSignal().
LockedTimedWait()
bool Jack::JackWinProcessSync::LockedTimedWait (long usec)
Definition at line 91 of file JackWinProcessSync.cpp.
References TimedWait().
LockedWait()
void Jack::JackWinProcessSync::LockedWait ()
Definition at line 70 of file JackWinProcessSync.cpp.
References Wait().
Signal()
void Jack::JackWinProcessSync::Signal ()
Definition at line 26 of file JackWinProcessSync.cpp.
References fEvent, and jack_error.
Referenced by SignalAll().
SignalAll()
void Jack::JackWinProcessSync::SignalAll ()
Definition at line 47 of file JackWinProcessSync.cpp.
References Signal().
TimedWait()
bool Jack::JackWinProcessSync::TimedWait (long usec)
Definition at line 120 of file JackWinProcessSync.cpp.
References fEvent, Jack::JackWinMutex::fMutex, and jack_error.
Referenced by LockedTimedWait().
Wait()
void Jack::JackWinProcessSync::Wait ()
Definition at line 97 of file JackWinProcessSync.cpp.
References fEvent, Jack::JackWinMutex::fMutex, and jack_error.
Referenced by LockedWait().
Member Data Documentation
fEvent
HANDLE Jack::JackWinProcessSync::fEvent private
Definition at line 37 of file JackWinProcessSync.h.
Referenced by JackWinProcessSync(), ~JackWinProcessSync(), LockedSignal(), Signal(), TimedWait(), and Wait().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinProcessSync.h
src/3rdparty/jack2/windows/JackWinProcessSync.cpp