LMMS: lmms::AudioFileDevice Class Reference
lmms::AudioFileDevice Class Reference
#include <AudioFileDevice.h>
Public Member Functions
AudioFileDevice (OutputSettings const &outputSettings, const ch_cnt_t _channels, const QString &_file, AudioEngine *audioEngine)
~AudioFileDevice () override
OutputSettings const & getOutputSettings () const
QString outputFile () const
Public Member Functions inherited from lmms::AudioDevice
AudioDevice (const ch_cnt_t _channels, AudioEngine *audioEngine)
virtual ~AudioDevice ()
void lock ()
void processNextBuffer ()
virtual void registerPort (AudioBusHandle *port)
virtual void renamePort (AudioBusHandle *port)
sample_rate_t sampleRate () const
virtual void startProcessing ()
virtual void stopProcessing ()
bool supportsCapture () const
void unlock ()
virtual void unregisterPort (AudioBusHandle *port)
Protected Member Functions
int outputFileHandle () const
bool outputFileOpened () const
int writeData (const void *data, int len)
Protected Member Functions inherited from lmms::AudioDevice
AudioEngine * audioEngine ()
ch_cnt_t channels () const
void clearS16Buffer (int_sample_t *_outbuf, const fpp_t _frames)
int convertToS16 (const SampleFrame *_ab, const fpp_t _frames, int_sample_t *_output_buffer, const bool _convert_endian=false)
fpp_t getNextBuffer (SampleFrame *_ab)
void setSampleRate (const sample_rate_t _new_sr)
virtual void writeBuffer (const SampleFrame *, const fpp_t)
Private Attributes
QFile m_outputFile
OutputSettings m_outputSettings
Additional Inherited Members
Static Protected Member Functions inherited from lmms::AudioDevice
static void stopProcessingThread (QThread *thread)
Protected Attributes inherited from lmms::AudioDevice
bool m_supportsCapture
Detailed Description
Definition at line 37 of file AudioFileDevice.h.
Constructor & Destructor Documentation
AudioFileDevice()
lmms::AudioFileDevice::AudioFileDevice (OutputSettings const & outputSettings, const ch_cnt_t _channels, const QString & _file, AudioEngine * audioEngine)
Definition at line 35 of file AudioFileDevice.cpp.
References lmms::AudioDevice::AudioDevice(), lmms::gui::getGUI(), lmms::OutputSettings::getSampleRate(), m_outputFile, m_outputSettings, and lmms::AudioDevice::setSampleRate().
Referenced by lmms::AudioFileFlac::AudioFileFlac(), lmms::AudioFileWave::AudioFileWave(), lmms::AudioFileFlac::getInst(), and lmms::AudioFileWave::getInst().
~AudioFileDevice()
lmms::AudioFileDevice::~AudioFileDevice () override
Definition at line 76 of file AudioFileDevice.cpp.
References m_outputFile.
Member Function Documentation
getOutputSettings()
OutputSettings const & lmms::AudioFileDevice::getOutputSettings () const inline
Definition at line 50 of file AudioFileDevice.h.
References m_outputSettings.
Referenced by lmms::AudioFileFlac::startEncoding(), lmms::AudioFileWave::startEncoding(), lmms::AudioFileFlac::writeBuffer(), and lmms::AudioFileWave::writeBuffer().
outputFile()
QString lmms::AudioFileDevice::outputFile () const inline
Definition at line 45 of file AudioFileDevice.h.
References m_outputFile.
Referenced by lmms::AudioFileFlac::startEncoding().
outputFileHandle()
int lmms::AudioFileDevice::outputFileHandle () const inline protected
Definition at line 61 of file AudioFileDevice.h.
References m_outputFile.
Referenced by lmms::AudioFileWave::startEncoding().
outputFileOpened()
bool lmms::AudioFileDevice::outputFileOpened () const inline protected
Definition at line 56 of file AudioFileDevice.h.
References m_outputFile.
Referenced by lmms::AudioFileFlac::AudioFileFlac(), and lmms::AudioFileWave::AudioFileWave().
writeData()
int lmms::AudioFileDevice::writeData (const void * data, int len) protected
Definition at line 84 of file AudioFileDevice.cpp.
References m_outputFile.
Member Data Documentation
m_outputFile
QFile lmms::AudioFileDevice::m_outputFile private
Definition at line 67 of file AudioFileDevice.h.
Referenced by AudioFileDevice(), ~AudioFileDevice(), outputFile(), outputFileHandle(), outputFileOpened(), and writeData().
m_outputSettings
OutputSettings lmms::AudioFileDevice::m_outputSettings private
Definition at line 68 of file AudioFileDevice.h.
Referenced by AudioFileDevice(), and getOutputSettings().
The documentation for this class was generated from the following files:
include/AudioFileDevice.h
src/core/audio/AudioFileDevice.cpp