LMMS: lmms::detail::InterleavedFrameIteratorData< T, channelCount > Class Template Reference
lmms::detail::InterleavedFrameIteratorData< T, channelCount > Class Template Reference
#include <AudioBufferView.h>
Public Member Functions
constexpr InterleavedFrameIteratorData ()=default
constexpr InterleavedFrameIteratorData (const InterleavedFrameIteratorData &)=default
constexpr InterleavedFrameIteratorData (T *data) noexcept
Static Public Member Functions
static constexpr auto channels () noexcept -> proc_ch_t
Protected Attributes
T * m_data = nullptr
Detailed Description
template<typename T, proc_ch_t channelCount>
class lmms::detail::InterleavedFrameIteratorData< T, channelCount >
Definition at line 105 of file AudioBufferView.h.
Constructor & Destructor Documentation
InterleavedFrameIteratorData() [1/3]
template<typename T, proc_ch_t channelCount> lmms::detail::InterleavedFrameIteratorData< T, channelCount >::InterleavedFrameIteratorData () constexpr default
Referenced by InterleavedFrameIteratorData().
InterleavedFrameIteratorData() [2/3]
template<typename T, proc_ch_t channelCount> lmms::detail::InterleavedFrameIteratorData< T, channelCount >::InterleavedFrameIteratorData (const InterleavedFrameIteratorData< T, channelCount > &) constexpr default
References InterleavedFrameIteratorData().
InterleavedFrameIteratorData() [3/3]
template<typename T, proc_ch_t channelCount> lmms::detail::InterleavedFrameIteratorData< T, channelCount >::InterleavedFrameIteratorData (T * data) inline explicit constexpr noexcept
Definition at line 111 of file AudioBufferView.h.
References m_data.
Member Function Documentation
channels()
template<typename T, proc_ch_t channelCount> constexpr auto lmms::detail::InterleavedFrameIteratorData< T, channelCount >::channels () ->proc_ch_t inline static constexpr noexcept
Definition at line 116 of file AudioBufferView.h.
Referenced by lmms::detail::InterleavedFrameIterator< T, channelCount >::operator+, lmms::detail::InterleavedFrameIterator< T, channelCount >::operator++(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator+=(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator-(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator--(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator-=(), and lmms::detail::InterleavedFrameIterator< T, channelCount >::operator[]().
Member Data Documentation
m_data
template<typename T, proc_ch_t channelCount> T* lmms::detail::InterleavedFrameIteratorData< T, channelCount >::m_data = nullptr protected
Definition at line 119 of file AudioBufferView.h.
Referenced by InterleavedFrameIteratorData(), lmms::detail::InterleavedFrameIterator< T, channelCount >::base(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator*(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator++(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator+=(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator-(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator-(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator--(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator-=(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator==(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator==(), and lmms::detail::InterleavedFrameIterator< T, channelCount >::operator[]().
The documentation for this class was generated from the following file:
include/AudioBufferView.h