LMMS: Jack::JackClient Class Reference
Jack::JackClient Class Reference abstract
The base class for clients: share part of the implementation for JackInternalClient and JackLibClient.
#include <JackClient.h>
Public Member Functions
JackClient (JackSynchro *table)
virtual ~JackClient ()
virtual int Activate ()
We need to start thread before activating in the server, otherwise the FW driver connected to the client may not be activated.
virtual int ClientHasSessionCallback (const char *client_name)
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Close ()
virtual int ComputeTotalLatencies ()
void CycleSignal (int status)
jack_nframes_t CycleWait ()
virtual int Deactivate ()
Need to stop thread after deactivating in the server.
bool Execute ()
RT thread.
virtual char * GetClientNameByUUID (const char *uuid)
virtual jack_nframes_t GetCurrentTransportFrame ()
virtual JackEngineControl * GetEngineControl () const =0
virtual JackGraphManager * GetGraphManager () const =0
virtual char * GetInternalClientName (int ref)
char * GetServerName ()
virtual jack_native_thread_t GetThreadID ()
virtual char * GetUUIDForClientName (const char *client_name)
bool Init ()
Called once when the thread starts.
virtual int InternalClientHandle (const char *client_name, jack_status_t *status)
virtual int InternalClientLoad (const char *client_name, jack_options_t options, jack_status_t *status, jack_varargs_t *va)
virtual void InternalClientUnload (int ref, jack_status_t *status)
virtual void OnInfoShutdown (JackInfoShutdownCallback callback, void *arg)
virtual void OnShutdown (JackShutdownCallback callback, void *arg)
virtual int Open (const char *server_name, const char *name, jack_uuid_t uuid, jack_options_t options, jack_status_t *status)=0
virtual int PortConnect (const char *src, const char *dst)
virtual int PortDisconnect (const char *src, const char *dst)
virtual int PortDisconnect (jack_port_id_t src)
virtual int PortIsMine (jack_port_id_t port_index)
virtual int PortRegister (const char *port_name, const char *port_type, unsigned long flags, unsigned long buffer_size)
virtual int PortRename (jack_port_id_t port_index, const char *name)
virtual int PortUnRegister (jack_port_id_t port)
virtual int PropertyChangeNotify (jack_uuid_t subject, const char *key, jack_property_change_t change)
virtual int ReleaseTimebase ()
virtual int ReserveClientName (const char *client_name, const char *uuid)
virtual jack_session_command_t * SessionNotify (const char *target, jack_session_event_type_t type, const char *path)
virtual int SessionReply (jack_session_event_t *ev)
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetBufferSizeCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetClientRegistrationCallback (JackClientRegistrationCallback callback, void *arg)
virtual int SetFreeWheel (int onoff)
virtual int SetFreewheelCallback (JackFreewheelCallback callback, void *arg)
virtual int SetGraphOrderCallback (JackGraphOrderCallback callback, void *arg)
virtual int SetInitCallback (JackThreadInitCallback callback, void *arg)
virtual int SetLatencyCallback (JackLatencyCallback callback, void *arg)
virtual int SetPortConnectCallback (JackPortConnectCallback callback, void *arg)
virtual int SetPortRegistrationCallback (JackPortRegistrationCallback callback, void *arg)
virtual int SetPortRenameCallback (JackPortRenameCallback callback, void *arg)
virtual int SetProcessCallback (JackProcessCallback callback, void *arg)
virtual int SetProcessThread (JackThreadCallback fun, void *arg)
virtual int SetPropertyChangeCallback (JackPropertyChangeCallback callback, void *arg)
virtual int SetSampleRateCallback (JackBufferSizeCallback callback, void *arg)
virtual int SetSessionCallback (JackSessionCallback callback, void *arg)
virtual int SetSyncCallback (JackSyncCallback sync_callback, void *arg)
virtual int SetSyncTimeout (jack_time_t timeout)
virtual int SetTimebaseCallback (int conditional, JackTimebaseCallback timebase_callback, void *arg)
virtual int SetXRunCallback (JackXRunCallback callback, void *arg)
virtual void ShutDown (jack_status_t code, const char *message)
virtual void TransportLocate (jack_nframes_t frame)
virtual jack_transport_state_t TransportQuery (jack_position_t *pos)
virtual int TransportReposition (const jack_position_t *pos)
virtual void TransportStart ()
virtual void TransportStop ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
virtual JackClientControl * GetClientControl () const =0
Protected Member Functions
int ActivateAux ()
int CallProcessCallback ()
void CallSyncCallback ()
void CallSyncCallbackAux ()
void CallTimebaseCallback ()
void CallTimebaseCallbackAux ()
virtual int ClientNotifyImp (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value)
Notification received from the server.
void CycleSignalAux (int status)
jack_nframes_t CycleWaitAux ()
void DummyCycle ()
void End ()
void Error ()
void ExecuteThread ()
int HandleLatencyCallback (int status)
void InitAux ()
bool IsActive ()
void SetupDriverSync (bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
void SetupRealTime ()
void SignalSync ()
int StartThread ()
bool WaitSync ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Protected Attributes
JackBufferSizeCallback fBufferSize
void * fBufferSizeArg
detail::JackClientChannelInterface * fChannel
Thread to execute the Process function.
JackClientRegistrationCallback fClientRegistration
void * fClientRegistrationArg
JackFreewheelCallback fFreewheel
void * fFreewheelArg
JackGraphOrderCallback fGraphOrder
void * fGraphOrderArg
JackInfoShutdownCallback fInfoShutdown
void * fInfoShutdownArg
JackThreadInitCallback fInit
void * fInitArg
JackLatencyCallback fLatency
void * fLatencyArg
JackPortConnectCallback fPortConnect
void * fPortConnectArg
std::list< jack_port_id_t > fPortList
JackPortRegistrationCallback fPortRegistration
void * fPortRegistrationArg
JackPortRenameCallback fPortRename
void * fPortRenameArg
JackProcessCallback fProcess
void * fProcessArg
JackPropertyChangeCallback fPropertyChange
void * fPropertyChangeArg
JackSampleRateCallback fSampleRate
void * fSampleRateArg
char fServerName [JACK_SERVER_NAME_SIZE+1]
JackSessionCallback fSession
void * fSessionArg
JackSessionReply fSessionReply
JackShutdownCallback fShutdown
void * fShutdownArg
JackSyncCallback fSync
void * fSyncArg
JackSynchro * fSynchroTable
JackThread fThread
JackThreadCallback fThreadFun
void * fThreadFunArg
JackTimebaseCallback fTimebase
void * fTimebaseArg
JackXRunCallback fXrun
void * fXrunArg
Friends
class JackDebugClient
Detailed Description
The base class for clients: share part of the implementation for JackInternalClient and JackLibClient.
Definition at line 48 of file JackClient.h.
Constructor & Destructor Documentation
JackClient()
Jack::JackClient::JackClient (JackSynchro * table)
Definition at line 44 of file JackClient.cpp.
References fBufferSize, fBufferSizeArg, fClientRegistration, fClientRegistrationArg, fFreewheel, fFreewheelArg, fGraphOrder, fGraphOrderArg, fInfoShutdown, fInfoShutdownArg, fInit, fInitArg, fLatency, fLatencyArg, fPortConnect, fPortConnectArg, fPortRegistration, fPortRegistrationArg, fPortRename, fPortRenameArg, fProcess, fProcessArg, fPropertyChange, fPropertyChangeArg, fSession, fSessionArg, fSessionReply, fShutdown, fShutdownArg, fSync, fSyncArg, fSynchroTable, fThread, fThreadFun, fThreadFunArg, fTimebase, fTimebaseArg, fXrun, fXrunArg, and Jack::kPendingSessionReply.
Referenced by Jack::JackDebugClient::JackDebugClient(), Jack::JackInternalClient::JackInternalClient(), and Jack::JackLibClient::JackLibClient().
~JackClient()
Jack::JackClient::~JackClient () virtual
Definition at line 88 of file JackClient.cpp.
Member Function Documentation
Activate()
int Jack::JackClient::Activate () virtual
We need to start thread before activating in the server, otherwise the FW driver connected to the client may not be activated.
Reimplemented in Jack::JackDebugClient.
Definition at line 443 of file JackClient.cpp.
References Jack::JackClientControl::fActive, Jack::JackClientControl::fCallback, fChannel, Jack::JackClientControl::fTransportSync, Jack::JackClientControl::fTransportTimebase, Jack::JackClientInterface::GetClientControl(), IsActive(), IsRealTime, jack_log(), Jack::kRealTimeCallback, and StartThread().
Referenced by GetEngineControl().
ActivateAux()
int Jack::JackClient::ActivateAux () inline protected
Definition at line 822 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fChannel, fThread, Jack::JackClientInterface::GetClientControl(), IsActive(), IsRealTime, jack_log(), Jack::kRealTimeCallback, Jack::detail::JackThreadInterface::kRunning, and StartThread().
Referenced by SetSyncCallback(), and SetTimebaseCallback().
CallProcessCallback()
int Jack::JackClient::CallProcessCallback () inline protected
Definition at line 633 of file JackClient.cpp.
References fBufferSize, fProcess, fProcessArg, and GetEngineControl().
Referenced by ExecuteThread().
CallSyncCallback()
void Jack::JackClient::CallSyncCallback () protected
Definition at line 936 of file JackClient.cpp.
References CallSyncCallbackAux().
CallSyncCallbackAux()
void Jack::JackClient::CallSyncCallbackAux () inline protected
Definition at line 941 of file JackClient.cpp.
References cur_pos, fSync, fSyncArg, Jack::JackEngineControl::fTransport, Jack::JackClientControl::fTransportState, Jack::JackClientControl::fTransportSync, Jack::JackClientInterface::GetClientControl(), GetEngineControl(), Jack::JackTransportEngine::GetState(), JackTransportRolling, and Jack::JackAtomicArrayState< T >::ReadCurrentState().
Referenced by CallSyncCallback(), and CycleWaitAux().
CallTimebaseCallback()
void Jack::JackClient::CallTimebaseCallback () protected
Definition at line 961 of file JackClient.cpp.
References CallTimebaseCallbackAux().
CallTimebaseCallbackAux()
void Jack::JackClient::CallTimebaseCallbackAux () inline protected
Definition at line 966 of file JackClient.cpp.
References cur_pos, fBufferSize, fTimebase, fTimebaseArg, Jack::JackEngineControl::fTransport, Jack::JackClientControl::fTransportTimebase, Jack::JackClientInterface::GetClientControl(), GetEngineControl(), Jack::JackTransportEngine::GetState(), Jack::JackTransportEngine::GetTimebaseMaster(), JackTransportRolling, Jack::JackAtomicArrayState< T >::WriteNextStateStart(), and Jack::JackAtomicArrayState< T >::WriteNextStateStop().
Referenced by CallTimebaseCallback(), and CycleSignalAux().
ClientHasSessionCallback()
int Jack::JackClient::ClientHasSessionCallback (const char * client_name) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1339 of file JackClient.cpp.
References fChannel.
Referenced by GetEngineControl().
ClientNotify()
int Jack::JackClient::ClientNotify (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value2) virtual
Implements Jack::JackClientInterface.
Reimplemented in Jack::JackDebugClient.
Definition at line 166 of file JackClient.cpp.
References ClientNotifyImp(), fBufferSize, fBufferSizeArg, fClientRegistration, fClientRegistrationArg, fFreewheel, fFreewheelArg, fGraphOrder, fGraphOrderArg, fName, fPortConnect, fPortConnectArg, fPortRegistration, fPortRegistrationArg, fPortRename, fPortRenameArg, fPropertyChange, fPropertyChangeArg, fSampleRate, fSampleRateArg, fSession, fSessionArg, fSessionReply, fThread, fXrun, fXrunArg, Jack::JackClientInterface::GetClientControl(), GetEngineControl(), GetGraphManager(), HandleLatencyCallback(), InitAux(), IsActive(), jack_error, jack_log(), jack_uuid_parse(), JACK_UUID_STRING_SIZE, jack_uuid_unparse(), Jack::kActivateClient, Jack::kAddClient, Jack::kBufferSizeCallback, Jack::kGraphOrderCallback, Jack::kLatencyCallback, Jack::kPendingSessionReply, Jack::kPortConnectCallback, Jack::kPortDisconnectCallback, Jack::kPortRegistrationOffCallback, Jack::kPortRegistrationOnCallback, Jack::kPortRenameCallback, Jack::kPropertyChangeCallback, Jack::kRemoveClient, Jack::detail::JackThreadInterface::kRunning, Jack::kSampleRateCallback, Jack::kSessionCallback, Jack::kShutDownCallback, Jack::kStartFreewheelCallback, Jack::kStopFreewheelCallback, Jack::kXRunCallback, SetupDriverSync(), and ShutDown().
Referenced by GetEngineControl().
ClientNotifyImp()
int Jack::JackClient::ClientNotifyImp (int refnum, const char * name, int notify, int sync, const char * message, int value1, int value) protected virtual
Notification received from the server.
Reimplemented in Jack::JackLibClient.
Definition at line 161 of file JackClient.cpp.
Referenced by ClientNotify().
Close()
int Jack::JackClient::Close () virtual
Implements Jack::JackClientInterface.
Reimplemented in Jack::JackDebugClient.
Definition at line 106 of file JackClient.cpp.
References Deactivate(), fChannel, Jack::JackGlobals::fClientTable, Jack::JackClientControl::fRefNum, Jack::JackGlobals::fSynchroMutex, fSynchroTable, Jack::JackClientInterface::GetClientControl(), and jack_log().
Referenced by Open(), Jack::JackLoadableInternalClient1::Open(), and Jack::JackLoadableInternalClient2::Open().
ComputeTotalLatencies()
int Jack::JackClient::ComputeTotalLatencies () virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 811 of file JackClient.cpp.
References fChannel.
Referenced by GetEngineControl().
CycleSignal()
void Jack::JackClient::CycleSignal (int status)
Definition at line 628 of file JackClient.cpp.
References CycleSignalAux().
Referenced by GetEngineControl().
CycleSignalAux()
void Jack::JackClient::CycleSignalAux (int status) inline protected
Definition at line 612 of file JackClient.cpp.
References CallTimebaseCallbackAux(), End(), and SignalSync().
Referenced by CycleSignal(), and ExecuteThread().
CycleWait()
jack_nframes_t Jack::JackClient::CycleWait ()
Definition at line 623 of file JackClient.cpp.
References CycleWaitAux().
Referenced by GetEngineControl().
CycleWaitAux()
jack_nframes_t Jack::JackClient::CycleWaitAux () inline protected
Definition at line 603 of file JackClient.cpp.
References CallSyncCallbackAux(), Error(), Jack::JackEngineControl::fBufferSize, GetEngineControl(), and WaitSync().
Referenced by CycleWait(), and ExecuteThread().
Deactivate()
int Jack::JackClient::Deactivate () virtual
Need to stop thread after deactivating in the server.
Reimplemented in Jack::JackDebugClient.
Definition at line 476 of file JackClient.cpp.
References Jack::JackClientControl::fActive, fChannel, fThread, Jack::JackClientControl::fTransportSync, Jack::JackClientControl::fTransportTimebase, Jack::JackClientInterface::GetClientControl(), IsActive(), IsRealTime, and jack_log().
Referenced by Close(), and GetEngineControl().
DummyCycle()
void Jack::JackClient::DummyCycle () inline protected
Definition at line 589 of file JackClient.cpp.
References SignalSync(), and WaitSync().
Referenced by Execute().
End()
void Jack::JackClient::End () inline protected
Definition at line 664 of file JackClient.cpp.
References Jack::JackClientControl::fActive, fChannel, fName, fThread, Jack::JackClientInterface::GetClientControl(), and jack_log().
Referenced by CycleSignalAux().
Error()
void Jack::JackClient::Error () inline protected
Definition at line 675 of file JackClient.cpp.
References Jack::JackClientControl::fActive, fChannel, fName, fThread, Jack::JackClientInterface::GetClientControl(), jack_error, JACK_SERVER_FAILURE, JackFailure, JackServerError, and ShutDown().
Referenced by CycleWaitAux().
Execute()
bool Jack::JackClient::Execute () virtual
RT thread.
Implements Jack::JackRunnableInterface.
Definition at line 576 of file JackClient.cpp.
References DummyCycle(), ExecuteThread(), fThreadFun, and fThreadFunArg.
Referenced by GetEngineControl().
ExecuteThread()
void Jack::JackClient::ExecuteThread () inline protected
Definition at line 595 of file JackClient.cpp.
References CallProcessCallback(), CycleSignalAux(), and CycleWaitAux().
Referenced by Execute().
GetClientNameByUUID()
char * Jack::JackClient::GetClientNameByUUID (const char * uuid) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1324 of file JackClient.cpp.
References fChannel, Jack::JackClientInterface::GetClientControl(), and JACK_CLIENT_NAME_SIZE.
Referenced by GetEngineControl().
GetCurrentTransportFrame()
jack_nframes_t Jack::JackClient::GetCurrentTransportFrame () virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 916 of file JackClient.cpp.
References Jack::JackEngineControl::fTransport, Jack::JackTransportEngine::GetCurrentFrame(), and GetEngineControl().
Referenced by GetEngineControl().
GetEngineControl()
virtual JackEngineControl * Jack::JackClient::GetEngineControl () const pure virtual
Implemented in Jack::JackDebugClient, Jack::JackInternalClient, and Jack::JackLibClient.
References Activate(), ClientHasSessionCallback(), ClientNotify(), ComputeTotalLatencies(), CycleSignal(), CycleWait(), Deactivate(), Execute(), GetClientNameByUUID(), GetCurrentTransportFrame(), GetInternalClientName(), GetThreadID(), GetUUIDForClientName(), Init(), InternalClientHandle(), InternalClientLoad(), InternalClientUnload(), OnInfoShutdown(), OnShutdown(), PortConnect(), PortDisconnect(), PortIsMine(), PortRegister(), PortRename(), PortUnRegister(), pos, PropertyChangeNotify(), ReleaseTimebase(), ReserveClientName(), SessionNotify(), SessionReply(), SetBufferSize(), SetBufferSizeCallback(), SetClientRegistrationCallback(), SetFreeWheel(), SetFreewheelCallback(), SetGraphOrderCallback(), SetInitCallback(), SetLatencyCallback(), SetPortConnectCallback(), SetPortRegistrationCallback(), SetPortRenameCallback(), SetProcessCallback(), SetProcessThread(), SetPropertyChangeCallback(), SetSampleRateCallback(), SetSessionCallback(), SetSyncCallback(), SetSyncTimeout(), SetTimebaseCallback(), SetXRunCallback(), ShutDown(), TransportLocate(), TransportQuery(), TransportReposition(), TransportStart(), and TransportStop().
Referenced by CallProcessCallback(), CallSyncCallbackAux(), CallTimebaseCallbackAux(), ClientNotify(), CycleWaitAux(), GetCurrentTransportFrame(), Init(), SetSampleRateCallback(), SetSyncTimeout(), SetupDriverSync(), SetupRealTime(), TransportLocate(), TransportQuery(), TransportReposition(), TransportStart(), and TransportStop().
GetGraphManager()
virtual JackGraphManager * Jack::JackClient::GetGraphManager () const pure virtual
Implemented in Jack::JackDebugClient, Jack::JackInternalClient, and Jack::JackLibClient.
Referenced by ClientNotify(), HandleLatencyCallback(), PortIsMine(), SignalSync(), and WaitSync().
GetInternalClientName()
char * Jack::JackClient::GetInternalClientName (int ref) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1227 of file JackClient.cpp.
References fChannel, Jack::JackClientInterface::GetClientControl(), and JACK_CLIENT_NAME_SIZE.
Referenced by GetEngineControl().
GetServerName()
char * Jack::JackClient::GetServerName () inline
Definition at line 134 of file JackClient.h.
References fServerName.
GetThreadID()
jack_native_thread_t Jack::JackClient::GetThreadID () virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 132 of file JackClient.cpp.
References fThread.
Referenced by GetEngineControl().
GetUUIDForClientName()
char * Jack::JackClient::GetUUIDForClientName (const char * client_name) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1316 of file JackClient.cpp.
References fChannel, Jack::JackClientInterface::GetClientControl(), and JACK_UUID_STRING_SIZE.
Referenced by GetEngineControl().
HandleLatencyCallback()
int Jack::JackClient::HandleLatencyCallback (int status) protected
Definition at line 343 of file JackClient.cpp.
References fLatency, fLatencyArg, fPortList, Jack::JackPort::GetFlags(), GetGraphManager(), Jack::JackPort::GetLatencyRange(), Jack::JackGraphManager::GetPort(), JackCaptureLatency, JackPlaybackLatency, JackPortIsInput, JackPortIsOutput, _jack_latency_range::max, _jack_latency_range::min, Jack::JackGraphManager::RecalculateLatency(), Jack::JackPort::SetLatencyRange(), and UINT32_MAX.
Referenced by ClientNotify().
Init()
bool Jack::JackClient::Init () virtual
Called once when the thread starts.
Reimplemented from Jack::JackRunnableInterface.
Definition at line 516 of file JackClient.cpp.
References fBufferSize, fBufferSizeArg, Jack::JackGlobals::fRealTimeThread, GetEngineControl(), InitAux(), jack_error, jack_log(), jack_tls_set(), set_threaded_log_function(), and SetupRealTime().
Referenced by GetEngineControl().
InitAux()
void Jack::JackClient::InitAux () inline protected
Definition at line 505 of file JackClient.cpp.
References fInit, fInitArg, and jack_log().
Referenced by ClientNotify(), and Init().
InternalClientHandle()
int Jack::JackClient::InternalClientHandle (const char * client_name, jack_status_t * status) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1235 of file JackClient.cpp.
References fChannel, and Jack::JackClientInterface::GetClientControl().
Referenced by GetEngineControl().
InternalClientLoad()
int Jack::JackClient::InternalClientLoad (const char * client_name, jack_options_t options, jack_status_t * status, jack_varargs_t * va) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1242 of file JackClient.cpp.
References fChannel, Jack::JackClientInterface::GetClientControl(), JACK_CLIENT_NAME_SIZE, jack_error, JACK_LOAD_INIT_LIMIT, JACK_PATH_MAX, JackFailure, JackInvalidOption, jack_varargs_t::load_init, and jack_varargs_t::load_name.
Referenced by GetEngineControl().
InternalClientUnload()
void Jack::JackClient::InternalClientUnload (int ref, jack_status_t * status) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1274 of file JackClient.cpp.
References fChannel, and Jack::JackClientInterface::GetClientControl().
Referenced by GetEngineControl().
IsActive()
bool Jack::JackClient::IsActive () protected
Definition at line 127 of file JackClient.cpp.
References Jack::JackClientControl::fActive, and Jack::JackClientInterface::GetClientControl().
Referenced by Activate(), ActivateAux(), ClientNotify(), Deactivate(), OnInfoShutdown(), OnShutdown(), SetBufferSizeCallback(), SetClientRegistrationCallback(), SetFreewheelCallback(), SetGraphOrderCallback(), SetInitCallback(), SetLatencyCallback(), SetPortConnectCallback(), SetPortRegistrationCallback(), SetPortRenameCallback(), SetProcessCallback(), SetProcessThread(), SetPropertyChangeCallback(), SetSampleRateCallback(), SetSessionCallback(), and SetXRunCallback().
OnInfoShutdown()
void Jack::JackClient::OnInfoShutdown (JackInfoShutdownCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1006 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fInfoShutdown, fInfoShutdownArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, and Jack::kShutDownCallback.
Referenced by GetEngineControl().
OnShutdown()
void Jack::JackClient::OnShutdown (JackShutdownCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 994 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fShutdown, fShutdownArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, and Jack::kShutDownCallback.
Referenced by GetEngineControl().
Open()
virtual int Jack::JackClient::Open (const char * server_name, const char * name, jack_uuid_t uuid, jack_options_t options, jack_status_t * status) pure virtual
Implemented in Jack::JackDebugClient, Jack::JackInternalClient, Jack::JackLibClient, Jack::JackLoadableInternalClient1, and Jack::JackLoadableInternalClient2.
References Close(), and server_name.
PortConnect()
int Jack::JackClient::PortConnect (const char * src, const char * dst) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 740 of file JackClient.cpp.
References fChannel, Jack::JackClientInterface::GetClientControl(), jack_error, jack_log(), and REAL_JACK_PORT_NAME_SIZE.
Referenced by GetEngineControl().
PortDisconnect() [1/2]
int Jack::JackClient::PortDisconnect (const char * src, const char * dst) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 756 of file JackClient.cpp.
References fChannel, Jack::JackClientInterface::GetClientControl(), jack_error, jack_log(), and REAL_JACK_PORT_NAME_SIZE.
Referenced by GetEngineControl().
PortDisconnect() [2/2]
int Jack::JackClient::PortDisconnect (jack_port_id_t src) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 772 of file JackClient.cpp.
References ALL_PORTS, fChannel, Jack::JackClientInterface::GetClientControl(), and jack_log().
PortIsMine()
int Jack::JackClient::PortIsMine (jack_port_id_t port_index) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 780 of file JackClient.cpp.
References Jack::JackClientControl::fRefNum, Jack::JackClientInterface::GetClientControl(), GetGraphManager(), Jack::JackGraphManager::GetPort(), and Jack::JackPort::GetRefNum().
Referenced by GetEngineControl().
PortRegister()
int Jack::JackClient::PortRegister (const char * port_name, const char * port_type, unsigned long flags, unsigned long buffer_size) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 691 of file JackClient.cpp.
References fChannel, fName, fPortList, Jack::JackClientInterface::GetClientControl(), jack_error, jack_log(), JACK_PORT_NAME_SIZE, NO_PORT, and REAL_JACK_PORT_NAME_SIZE.
Referenced by GetEngineControl().
PortRename()
int Jack::JackClient::PortRename (jack_port_id_t port_index, const char * name) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 786 of file JackClient.cpp.
References fChannel, and Jack::JackClientInterface::GetClientControl().
Referenced by GetEngineControl().
PortUnRegister()
int Jack::JackClient::PortUnRegister (jack_port_id_t port) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 724 of file JackClient.cpp.
References fChannel, fPortList, Jack::JackClientInterface::GetClientControl(), jack_error, and jack_log().
Referenced by GetEngineControl().
PropertyChangeNotify()
int Jack::JackClient::PropertyChangeNotify (jack_uuid_t subject, const char * key, jack_property_change_t change) virtual
Definition at line 1350 of file JackClient.cpp.
References fChannel.
Referenced by GetEngineControl().
ReleaseTimebase()
int Jack::JackClient::ReleaseTimebase () virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 844 of file JackClient.cpp.
References fChannel, fTimebase, fTimebaseArg, Jack::JackClientControl::fTransportTimebase, and Jack::JackClientInterface::GetClientControl().
Referenced by GetEngineControl().
ReserveClientName()
int Jack::JackClient::ReserveClientName (const char * client_name, const char * uuid) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1332 of file JackClient.cpp.
References fChannel, and Jack::JackClientInterface::GetClientControl().
Referenced by GetEngineControl().
SessionNotify()
jack_session_command_t * Jack::JackClient::SessionNotify (const char * target, jack_session_event_type_t type, const char * path) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1284 of file JackClient.cpp.
References fChannel, and Jack::JackClientInterface::GetClientControl().
Referenced by GetEngineControl().
SessionReply()
int Jack::JackClient::SessionReply (jack_session_event_t * ev) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1291 of file JackClient.cpp.
References _jack_session_event::command_line, fChannel, _jack_session_event::flags, Jack::JackClientControl::fSessionCommand, Jack::JackClientControl::fSessionFlags, fSessionReply, Jack::JackClientInterface::GetClientControl(), jack_log(), and Jack::kImmediateSessionReply.
Referenced by GetEngineControl().
SetBufferSize()
int Jack::JackClient::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 797 of file JackClient.cpp.
References fChannel.
Referenced by GetEngineControl().
SetBufferSizeCallback()
int Jack::JackClient::SetBufferSizeCallback (JackBufferSizeCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1072 of file JackClient.cpp.
References fBufferSize, fBufferSizeArg, Jack::JackClientControl::fCallback, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, and Jack::kBufferSizeCallback.
Referenced by GetEngineControl().
SetClientRegistrationCallback()
int Jack::JackClient::SetClientRegistrationCallback (JackClientRegistrationCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1102 of file JackClient.cpp.
References fClientRegistration, fClientRegistrationArg, IsActive(), and jack_error.
Referenced by GetEngineControl().
SetFreeWheel()
int Jack::JackClient::SetFreeWheel (int onoff) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 804 of file JackClient.cpp.
References fChannel.
Referenced by GetEngineControl().
SetFreewheelCallback()
int Jack::JackClient::SetFreewheelCallback (JackFreewheelCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1115 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fFreewheel, fFreewheelArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, Jack::kStartFreewheelCallback, and Jack::kStopFreewheelCallback.
Referenced by GetEngineControl().
SetGraphOrderCallback()
int Jack::JackClient::SetGraphOrderCallback (JackGraphOrderCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1059 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fGraphOrder, fGraphOrderArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, and Jack::kGraphOrderCallback.
Referenced by GetEngineControl().
SetInitCallback()
int Jack::JackClient::SetInitCallback (JackThreadInitCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1046 of file JackClient.cpp.
References fInit, fInitArg, Jack::JackMessageBuffer::fInstance, IsActive(), and jack_error.
Referenced by GetEngineControl().
SetLatencyCallback()
int Jack::JackClient::SetLatencyCallback (JackLatencyCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1198 of file JackClient.cpp.
References fLatency, fLatencyArg, IsActive(), and jack_error.
Referenced by GetEngineControl().
SetPortConnectCallback()
int Jack::JackClient::SetPortConnectCallback (JackPortConnectCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1143 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fPortConnect, fPortConnectArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, Jack::kPortConnectCallback, and Jack::kPortDisconnectCallback.
Referenced by GetEngineControl().
SetPortRegistrationCallback()
int Jack::JackClient::SetPortRegistrationCallback (JackPortRegistrationCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1129 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fPortRegistration, fPortRegistrationArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, Jack::kPortRegistrationOffCallback, and Jack::kPortRegistrationOnCallback.
Referenced by GetEngineControl().
SetPortRenameCallback()
int Jack::JackClient::SetPortRenameCallback (JackPortRenameCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1157 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fPortRename, fPortRenameArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, and Jack::kPortRenameCallback.
Referenced by GetEngineControl().
SetProcessCallback()
int Jack::JackClient::SetProcessCallback (JackProcessCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1018 of file JackClient.cpp.
References fProcess, fProcessArg, fThreadFun, IsActive(), and jack_error.
Referenced by GetEngineControl().
SetProcessThread()
int Jack::JackClient::SetProcessThread (JackThreadCallback fun, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1170 of file JackClient.cpp.
References fProcess, fThreadFun, fThreadFunArg, IsActive(), and jack_error.
Referenced by GetEngineControl().
SetPropertyChangeCallback()
int Jack::JackClient::SetPropertyChangeCallback (JackPropertyChangeCallback callback, void * arg) virtual
Definition at line 1211 of file JackClient.cpp.
References fPropertyChange, fPropertyChangeArg, IsActive(), and jack_error.
Referenced by GetEngineControl().
SetSampleRateCallback()
int Jack::JackClient::SetSampleRateCallback (JackBufferSizeCallback callback, void * arg) virtual
Definition at line 1085 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fSampleRate, fSampleRateArg, Jack::JackClientInterface::GetClientControl(), GetEngineControl(), IsActive(), jack_error, and Jack::kSampleRateCallback.
Referenced by GetEngineControl().
SetSessionCallback()
int Jack::JackClient::SetSessionCallback (JackSessionCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1185 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fSession, fSessionArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, and Jack::kSessionCallback.
Referenced by GetEngineControl().
SetSyncCallback()
int Jack::JackClient::SetSyncCallback (JackSyncCallback sync_callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 857 of file JackClient.cpp.
References ActivateAux(), fSync, fSyncArg, Jack::JackClientControl::fTransportSync, and Jack::JackClientInterface::GetClientControl().
Referenced by GetEngineControl().
SetSyncTimeout()
int Jack::JackClient::SetSyncTimeout (jack_time_t timeout) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 882 of file JackClient.cpp.
References Jack::JackEngineControl::fTransport, GetEngineControl(), and Jack::JackTransportEngine::SetSyncTimeout().
Referenced by GetEngineControl().
SetTimebaseCallback()
int Jack::JackClient::SetTimebaseCallback (int conditional, JackTimebaseCallback timebase_callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 865 of file JackClient.cpp.
References ActivateAux(), fChannel, fTimebase, fTimebaseArg, Jack::JackClientControl::fTransportTimebase, and Jack::JackClientInterface::GetClientControl().
Referenced by GetEngineControl().
SetupDriverSync()
void Jack::JackClient::SetupDriverSync (bool freewheel) protected
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
The synchronization primitives for drivers are setup in "flush" mode that to not keep unneeded activations. Drivers synchro are setup in "flush" mode if server is "async" and NOT freewheel.
Definition at line 142 of file JackClient.cpp.
References Jack::JackEngineControl::fDriverNum, fSynchroTable, GetEngineControl(), i, and jack_log().
Referenced by ClientNotify(), Jack::JackInternalClient::Open(), and Jack::JackLibClient::Open().
SetupRealTime()
void Jack::JackClient::SetupRealTime () inline protected
Definition at line 547 of file JackClient.cpp.
References fThread, GetEngineControl(), jack_error, and jack_log().
Referenced by Init().
SetXRunCallback()
int Jack::JackClient::SetXRunCallback (JackXRunCallback callback, void * arg) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 1033 of file JackClient.cpp.
References Jack::JackClientControl::fCallback, fXrun, fXrunArg, Jack::JackClientInterface::GetClientControl(), IsActive(), jack_error, and Jack::kXRunCallback.
Referenced by GetEngineControl().
ShutDown()
void Jack::JackClient::ShutDown (jack_status_t code, const char * message) virtual
Reimplemented in Jack::JackDebugClient, Jack::JackInternalClient, and Jack::JackLibClient.
Definition at line 91 of file JackClient.cpp.
References fInfoShutdown, fInfoShutdownArg, fShutdown, fShutdownArg, and jack_log().
Referenced by ClientNotify(), Error(), GetEngineControl(), Jack::JackInternalClient::ShutDown(), and Jack::JackLibClient::ShutDown().
SignalSync()
void Jack::JackClient::SignalSync () inline protected
Definition at line 656 of file JackClient.cpp.
References fSynchroTable, Jack::JackClientInterface::GetClientControl(), GetGraphManager(), and jack_error.
Referenced by CycleSignalAux(), and DummyCycle().
StartThread()
int Jack::JackClient::StartThread () protected
Definition at line 562 of file JackClient.cpp.
References fThread, and jack_error.
Referenced by Activate(), and ActivateAux().
TransportLocate()
void Jack::JackClient::TransportLocate (jack_nframes_t frame) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 890 of file JackClient.cpp.
References Jack::JackEngineControl::fTransport, GetEngineControl(), jack_log(), pos, and Jack::JackTransportEngine::RequestNewPos().
Referenced by GetEngineControl().
TransportQuery()
jack_transport_state_t Jack::JackClient::TransportQuery (jack_position_t * pos) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 911 of file JackClient.cpp.
References Jack::JackEngineControl::fTransport, GetEngineControl(), pos, and Jack::JackTransportEngine::Query().
Referenced by GetEngineControl().
TransportReposition()
int Jack::JackClient::TransportReposition (const jack_position_t * pos) virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 899 of file JackClient.cpp.
References Jack::JackEngineControl::fTransport, GetEngineControl(), jack_log(), JACK_POSITION_MASK, pos, Jack::JackTransportEngine::RequestNewPos(), and _jack_position::valid.
Referenced by GetEngineControl().
TransportStart()
void Jack::JackClient::TransportStart () virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 922 of file JackClient.cpp.
References Jack::JackEngineControl::fTransport, GetEngineControl(), Jack::JackTransportEngine::SetCommand(), and Jack::TransportCommandStart.
Referenced by GetEngineControl().
TransportStop()
void Jack::JackClient::TransportStop () virtual
Reimplemented in Jack::JackDebugClient.
Definition at line 928 of file JackClient.cpp.
References Jack::JackEngineControl::fTransport, GetEngineControl(), Jack::JackTransportEngine::SetCommand(), and Jack::TransportCommandStop.
Referenced by GetEngineControl().
WaitSync()
bool Jack::JackClient::WaitSync () inline protected
Definition at line 638 of file JackClient.cpp.
References fSynchroTable, fThread, Jack::JackClientInterface::GetClientControl(), GetGraphManager(), and jack_error.
Referenced by CycleWaitAux(), and DummyCycle().
Friends And Related Symbol Documentation
JackDebugClient
friend class JackDebugClient friend
Definition at line 50 of file JackClient.h.
References JackDebugClient.
Referenced by JackDebugClient.
Member Data Documentation
fBufferSize
JackBufferSizeCallback Jack::JackClient::fBufferSize protected
Definition at line 60 of file JackClient.h.
Referenced by JackClient(), CallProcessCallback(), CallTimebaseCallbackAux(), ClientNotify(), Init(), and SetBufferSizeCallback().
fBufferSizeArg
void* Jack::JackClient::fBufferSizeArg protected
Definition at line 80 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), Init(), and SetBufferSizeCallback().
fChannel
detail::JackClientChannelInterface* Jack::JackClient::fChannel protected
Thread to execute the Process function.
Definition at line 97 of file JackClient.h.
Referenced by Jack::JackInternalClient::JackInternalClient(), Jack::JackLibClient::JackLibClient(), Jack::JackInternalClient::~JackInternalClient(), Jack::JackLibClient::~JackLibClient(), Activate(), ActivateAux(), ClientHasSessionCallback(), Close(), ComputeTotalLatencies(), Deactivate(), End(), Error(), GetClientNameByUUID(), GetInternalClientName(), GetUUIDForClientName(), InternalClientHandle(), InternalClientLoad(), InternalClientUnload(), Jack::JackInternalClient::Open(), Jack::JackLibClient::Open(), PortConnect(), PortDisconnect(), PortDisconnect(), PortRegister(), PortRename(), PortUnRegister(), PropertyChangeNotify(), ReleaseTimebase(), ReserveClientName(), SessionNotify(), SessionReply(), SetBufferSize(), SetFreeWheel(), and SetTimebaseCallback().
fClientRegistration
JackClientRegistrationCallback Jack::JackClient::fClientRegistration protected
Definition at line 62 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetClientRegistrationCallback().
fClientRegistrationArg
void* Jack::JackClient::fClientRegistrationArg protected
Definition at line 82 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetClientRegistrationCallback().
fFreewheel
JackFreewheelCallback Jack::JackClient::fFreewheel protected
Definition at line 63 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetFreewheelCallback().
fFreewheelArg
void* Jack::JackClient::fFreewheelArg protected
Definition at line 83 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetFreewheelCallback().
fGraphOrder
JackGraphOrderCallback Jack::JackClient::fGraphOrder protected
Definition at line 55 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetGraphOrderCallback().
fGraphOrderArg
void* Jack::JackClient::fGraphOrderArg protected
Definition at line 75 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetGraphOrderCallback().
fInfoShutdown
JackInfoShutdownCallback Jack::JackClient::fInfoShutdown protected
Definition at line 58 of file JackClient.h.
Referenced by JackClient(), OnInfoShutdown(), and ShutDown().
fInfoShutdownArg
void* Jack::JackClient::fInfoShutdownArg protected
Definition at line 78 of file JackClient.h.
Referenced by JackClient(), OnInfoShutdown(), and ShutDown().
fInit
JackThreadInitCallback Jack::JackClient::fInit protected
Definition at line 59 of file JackClient.h.
Referenced by JackClient(), InitAux(), and SetInitCallback().
fInitArg
void* Jack::JackClient::fInitArg protected
Definition at line 79 of file JackClient.h.
Referenced by JackClient(), InitAux(), and SetInitCallback().
fLatency
JackLatencyCallback Jack::JackClient::fLatency protected
Definition at line 71 of file JackClient.h.
Referenced by JackClient(), HandleLatencyCallback(), and SetLatencyCallback().
fLatencyArg
void* Jack::JackClient::fLatencyArg protected
Definition at line 91 of file JackClient.h.
Referenced by JackClient(), HandleLatencyCallback(), and SetLatencyCallback().
fPortConnect
JackPortConnectCallback Jack::JackClient::fPortConnect protected
Definition at line 65 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetPortConnectCallback().
fPortConnectArg
void* Jack::JackClient::fPortConnectArg protected
Definition at line 85 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetPortConnectCallback().
fPortList
std::list<jack_port_id_t> Jack::JackClient::fPortList protected
Definition at line 99 of file JackClient.h.
Referenced by HandleLatencyCallback(), PortRegister(), and PortUnRegister().
fPortRegistration
JackPortRegistrationCallback Jack::JackClient::fPortRegistration protected
Definition at line 64 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetPortRegistrationCallback().
fPortRegistrationArg
void* Jack::JackClient::fPortRegistrationArg protected
Definition at line 84 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetPortRegistrationCallback().
fPortRename
JackPortRenameCallback Jack::JackClient::fPortRename protected
Definition at line 66 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetPortRenameCallback().
fPortRenameArg
void* Jack::JackClient::fPortRenameArg protected
Definition at line 86 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetPortRenameCallback().
fProcess
JackProcessCallback Jack::JackClient::fProcess protected
Definition at line 54 of file JackClient.h.
Referenced by JackClient(), CallProcessCallback(), SetProcessCallback(), and SetProcessThread().
fProcessArg
void* Jack::JackClient::fProcessArg protected
Definition at line 74 of file JackClient.h.
Referenced by JackClient(), Jack::JackLoadableInternalClient::~JackLoadableInternalClient(), CallProcessCallback(), and SetProcessCallback().
fPropertyChange
JackPropertyChangeCallback Jack::JackClient::fPropertyChange protected
Definition at line 72 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetPropertyChangeCallback().
fPropertyChangeArg
void* Jack::JackClient::fPropertyChangeArg protected
Definition at line 92 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetPropertyChangeCallback().
fSampleRate
JackSampleRateCallback Jack::JackClient::fSampleRate protected
Definition at line 61 of file JackClient.h.
Referenced by ClientNotify(), and SetSampleRateCallback().
fSampleRateArg
void* Jack::JackClient::fSampleRateArg protected
Definition at line 81 of file JackClient.h.
Referenced by ClientNotify(), and SetSampleRateCallback().
fServerName
char Jack::JackClient::fServerName[JACK_SERVER_NAME_SIZE+1] protected
Definition at line 94 of file JackClient.h.
Referenced by Jack::JackLibClient::ClientNotifyImp(), GetServerName(), Jack::JackInternalClient::Open(), and Jack::JackLibClient::Open().
fSession
JackSessionCallback Jack::JackClient::fSession protected
Definition at line 70 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetSessionCallback().
fSessionArg
void* Jack::JackClient::fSessionArg protected
Definition at line 90 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetSessionCallback().
fSessionReply
JackSessionReply Jack::JackClient::fSessionReply protected
Definition at line 101 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SessionReply().
fShutdown
JackShutdownCallback Jack::JackClient::fShutdown protected
Definition at line 57 of file JackClient.h.
Referenced by JackClient(), OnShutdown(), and ShutDown().
fShutdownArg
void* Jack::JackClient::fShutdownArg protected
Definition at line 77 of file JackClient.h.
Referenced by JackClient(), OnShutdown(), and ShutDown().
fSync
JackSyncCallback Jack::JackClient::fSync protected
Definition at line 68 of file JackClient.h.
Referenced by JackClient(), CallSyncCallbackAux(), and SetSyncCallback().
fSyncArg
void* Jack::JackClient::fSyncArg protected
Definition at line 88 of file JackClient.h.
Referenced by JackClient(), CallSyncCallbackAux(), and SetSyncCallback().
fSynchroTable
JackSynchro* Jack::JackClient::fSynchroTable protected
Definition at line 98 of file JackClient.h.
Referenced by JackClient(), Jack::JackDebugClient::JackDebugClient(), Jack::JackLibClient::ClientNotifyImp(), Close(), Jack::JackLibClient::Open(), SetupDriverSync(), SignalSync(), and WaitSync().
fThread
JackThread Jack::JackClient::fThread protected
Definition at line 96 of file JackClient.h.
Referenced by JackClient(), ActivateAux(), ClientNotify(), Deactivate(), End(), Error(), GetThreadID(), SetupRealTime(), StartThread(), and WaitSync().
fThreadFun
JackThreadCallback Jack::JackClient::fThreadFun protected
Definition at line 69 of file JackClient.h.
Referenced by JackClient(), Execute(), SetProcessCallback(), and SetProcessThread().
fThreadFunArg
void* Jack::JackClient::fThreadFunArg protected
Definition at line 89 of file JackClient.h.
Referenced by JackClient(), Execute(), and SetProcessThread().
fTimebase
JackTimebaseCallback Jack::JackClient::fTimebase protected
Definition at line 67 of file JackClient.h.
Referenced by JackClient(), CallTimebaseCallbackAux(), ReleaseTimebase(), and SetTimebaseCallback().
fTimebaseArg
void* Jack::JackClient::fTimebaseArg protected
Definition at line 87 of file JackClient.h.
Referenced by JackClient(), CallTimebaseCallbackAux(), ReleaseTimebase(), and SetTimebaseCallback().
fXrun
JackXRunCallback Jack::JackClient::fXrun protected
Definition at line 56 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetXRunCallback().
fXrunArg
void* Jack::JackClient::fXrunArg protected
Definition at line 76 of file JackClient.h.
Referenced by JackClient(), ClientNotify(), and SetXRunCallback().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackClient.h
src/3rdparty/jack2/common/JackClient.cpp