LMMS: lmms::gui::FileBrowser Class Reference
lmms::gui::FileBrowser Class Reference
#include <FileBrowser.h>
Public Types
enum class Type {
Normal ,
Favorites
}
Public Member Functions
FileBrowser (Type type, const QString &directories, const QString &filter, const QString &title, const QPixmap &pm, QWidget *parent, bool dirs_as_items=false, const QString &userDir="", const QString &factoryDir="")
Create a file browser side bar widget.
~FileBrowser () override=default
Public Member Functions inherited from lmms::gui::SideBarWidget
SideBarWidget (const QString &_title, const QPixmap &_icon, QWidget *_parent)
~SideBarWidget () override=default
const QPixmap & icon () const
const QString & title () const
Static Public Member Functions
static QDir::Filters dirFilters ()
static QDir::SortFlags sortFlags ()
Private Slots
void expandItems (const QList< QString > &expandedDirs, QTreeWidgetItem *item=nullptr)
void giveFocusToFilter ()
void reloadTree ()
Private Member Functions
void addContentCheckBox ()
void addItems (const QString &path)
void keyPressEvent (QKeyEvent *ke) override
void onSearch (const QString &filter)
void onSearchFinished ()
void onSearchMatch (const QString &path)
void onSearchStarted ()
void restoreDirectoriesStates ()
void saveDirectoriesStates ()
Private Attributes
QBoxLayout * filterWidgetLayout = nullptr
QBoxLayout * hiddenWidgetLayout = nullptr
QString m_directories
Directories to search, split with '*'.
bool m_dirsAsItems
QString m_factoryDir
FileBrowserTreeWidget * m_fileBrowserTreeWidget
QString m_filter
Filter as used in QDir::match().
QLineEdit * m_filterEdit
QString m_previousFilterValue
QList< QString > m_savedExpandedDirs
QProgressBar * m_searchIndicator = nullptr
FileSearchJob m_searchJob
FileBrowserTreeWidget * m_searchTreeWidget
QCheckBox * m_showFactoryContent = nullptr
QCheckBox * m_showHiddenContent = nullptr
QCheckBox * m_showUserContent = nullptr
Type m_type
QString m_userDir
QBoxLayout * outerLayout = nullptr
Additional Inherited Members
Signals inherited from lmms::gui::SideBarWidget
void closeButtonClicked ()
Protected Member Functions inherited from lmms::gui::SideBarWidget
void addContentLayout (QLayout *_l)
void addContentWidget (QWidget *_w)
QWidget * contentParent ()
void contextMenuEvent (QContextMenuEvent *) override
void paintEvent (QPaintEvent *_pe) override
void resizeEvent (QResizeEvent *_re) override
Detailed Description
Definition at line 57 of file FileBrowser.h.
Member Enumeration Documentation
Type
enum class lmms::gui::FileBrowser::Type strong
Enumerator
Normal
Favorites
Definition at line 61 of file FileBrowser.h.
Constructor & Destructor Documentation
FileBrowser()
lmms::gui::FileBrowser::FileBrowser (Type type, const QString & directories, const QString & filter, const QString & title, const QPixmap & pm, QWidget * parent, bool dirs_as_items = false, const QString & userDir = "", const QString & factoryDir = "")
Create a file browser side bar widget.
Parameters
directories '*'-separated list of directories to search for. If a directory of factory files should be in the list it must be the last one (for the factory files delimiter to work)
filter Filter as used in QDir::match
recurse to be documented
Definition at line 82 of file FileBrowser.cpp.
References lmms::gui::SideBarWidget::SideBarWidget(), addContentCheckBox(), lmms::gui::SideBarWidget::addContentWidget(), lmms::gui::SideBarWidget::contentParent(), lmms::ConfigManager::favoriteItems(), Favorites, lmms::ConfigManager::favoritesChanged(), lmms::gui::FileSearchJob::finished(), lmms::gui::FileSearchJob::foundMatch(), lmms::embed::getIconPixmap(), giveFocusToFilter(), lmms::ConfigManager::inst(), m_directories, m_dirsAsItems, m_factoryDir, m_fileBrowserTreeWidget, m_filter, m_filterEdit, m_previousFilterValue, m_searchIndicator, m_searchJob, m_searchTreeWidget, m_type, m_userDir, onSearch(), onSearchFinished(), onSearchMatch(), onSearchStarted(), reloadTree(), lmms::gui::FileSearchJob::started(), and lmms::gui::SideBarWidget::title().
~FileBrowser()
lmms::gui::FileBrowser::~FileBrowser () override default
Member Function Documentation
addContentCheckBox()
void lmms::gui::FileBrowser::addContentCheckBox () private
Definition at line 152 of file FileBrowser.cpp.
References lmms::gui::SideBarWidget::addContentWidget(), lmms::gui::SideBarWidget::contentParent(), filterWidgetLayout, hiddenWidgetLayout, m_factoryDir, m_showFactoryContent, m_showHiddenContent, m_showUserContent, m_userDir, outerLayout, and reloadTree().
Referenced by FileBrowser().
addItems()
void lmms::gui::FileBrowser::addItems (const QString & path) private
Definition at line 360 of file FileBrowser.cpp.
References dirFilters(), i, m_dirsAsItems, m_fileBrowserTreeWidget, m_filter, and m_showHiddenContent.
Referenced by reloadTree().
dirFilters()
QDir::Filters lmms::gui::FileBrowser::dirFilters () inline static
Definition at line 80 of file FileBrowser.h.
Referenced by lmms::gui::Directory::addItems(), and addItems().
expandItems
void lmms::gui::FileBrowser::expandItems (const QList< QString > & expandedDirs, QTreeWidgetItem * item = nullptr) private slot
Definition at line 324 of file FileBrowser.cpp.
References expandItems(), i, and m_fileBrowserTreeWidget.
Referenced by expandItems(), and restoreDirectoriesStates().
giveFocusToFilter
void lmms::gui::FileBrowser::giveFocusToFilter () private slot
Definition at line 348 of file FileBrowser.cpp.
References m_filterEdit.
Referenced by FileBrowser().
keyPressEvent()
void lmms::gui::FileBrowser::keyPressEvent (QKeyEvent * ke) override private
Definition at line 434 of file FileBrowser.cpp.
References reloadTree().
onSearch()
void lmms::gui::FileBrowser::onSearch (const QString & filter) private
Definition at line 210 of file FileBrowser.cpp.
References lmms::gui::FileItem::defaultFilters(), m_directories, m_factoryDir, m_fileBrowserTreeWidget, m_searchJob, m_searchTreeWidget, m_showFactoryContent, m_showHiddenContent, m_showUserContent, and m_userDir.
Referenced by FileBrowser(), and reloadTree().
onSearchFinished()
void lmms::gui::FileBrowser::onSearchFinished () private
Definition at line 253 of file FileBrowser.cpp.
References m_searchIndicator.
Referenced by FileBrowser().
onSearchMatch()
void lmms::gui::FileBrowser::onSearchMatch (const QString & path) private
Definition at line 238 of file FileBrowser.cpp.
References m_filter, and m_searchTreeWidget.
Referenced by FileBrowser().
onSearchStarted()
void lmms::gui::FileBrowser::onSearchStarted () private
Definition at line 248 of file FileBrowser.cpp.
References m_searchIndicator.
Referenced by FileBrowser().
reloadTree
void lmms::gui::FileBrowser::reloadTree () private slot
Definition at line 258 of file FileBrowser.cpp.
References addItems(), Favorites, file, m_directories, m_factoryDir, m_fileBrowserTreeWidget, m_filter, m_filterEdit, m_showFactoryContent, m_showUserContent, m_type, m_userDir, Normal, onSearch(), restoreDirectoriesStates(), saveDirectoriesStates(), and lmms::PathUtil::toAbsolute().
Referenced by FileBrowser(), addContentCheckBox(), and keyPressEvent().
restoreDirectoriesStates()
void lmms::gui::FileBrowser::restoreDirectoriesStates () private
Definition at line 205 of file FileBrowser.cpp.
References expandItems(), and m_savedExpandedDirs.
Referenced by reloadTree().
saveDirectoriesStates()
void lmms::gui::FileBrowser::saveDirectoriesStates () private
Definition at line 200 of file FileBrowser.cpp.
References m_fileBrowserTreeWidget, and m_savedExpandedDirs.
Referenced by reloadTree().
sortFlags()
QDir::SortFlags lmms::gui::FileBrowser::sortFlags () inline static
Definition at line 81 of file FileBrowser.h.
Referenced by lmms::gui::Directory::addItems().
Member Data Documentation
filterWidgetLayout
QBoxLayout* lmms::gui::FileBrowser::filterWidgetLayout = nullptr private
Definition at line 121 of file FileBrowser.h.
Referenced by addContentCheckBox().
hiddenWidgetLayout
QBoxLayout* lmms::gui::FileBrowser::hiddenWidgetLayout = nullptr private
Definition at line 122 of file FileBrowser.h.
Referenced by addContentCheckBox().
m_directories
QString lmms::gui::FileBrowser::m_directories private
Directories to search, split with '*'.
Definition at line 112 of file FileBrowser.h.
Referenced by FileBrowser(), onSearch(), and reloadTree().
m_dirsAsItems
bool lmms::gui::FileBrowser::m_dirsAsItems private
Definition at line 115 of file FileBrowser.h.
Referenced by FileBrowser(), and addItems().
m_factoryDir
QString lmms::gui::FileBrowser::m_factoryDir private
Definition at line 125 of file FileBrowser.h.
Referenced by FileBrowser(), addContentCheckBox(), onSearch(), and reloadTree().
m_fileBrowserTreeWidget
FileBrowserTreeWidget* lmms::gui::FileBrowser::m_fileBrowserTreeWidget private
Definition at line 103 of file FileBrowser.h.
Referenced by FileBrowser(), addItems(), expandItems(), onSearch(), reloadTree(), and saveDirectoriesStates().
m_filter
QString lmms::gui::FileBrowser::m_filter private
Filter as used in QDir::match().
Definition at line 113 of file FileBrowser.h.
Referenced by FileBrowser(), addItems(), onSearchMatch(), and reloadTree().
m_filterEdit
QLineEdit* lmms::gui::FileBrowser::m_filterEdit private
Definition at line 106 of file FileBrowser.h.
Referenced by FileBrowser(), giveFocusToFilter(), and reloadTree().
m_previousFilterValue
QString lmms::gui::FileBrowser::m_previousFilterValue private
Definition at line 127 of file FileBrowser.h.
Referenced by FileBrowser().
m_savedExpandedDirs
QList<QString> lmms::gui::FileBrowser::m_savedExpandedDirs private
Definition at line 126 of file FileBrowser.h.
Referenced by restoreDirectoriesStates(), and saveDirectoriesStates().
m_searchIndicator
QProgressBar* lmms::gui::FileBrowser::m_searchIndicator = nullptr private
Definition at line 109 of file FileBrowser.h.
Referenced by FileBrowser(), onSearchFinished(), and onSearchStarted().
m_searchJob
FileSearchJob lmms::gui::FileBrowser::m_searchJob private
Definition at line 110 of file FileBrowser.h.
Referenced by FileBrowser(), and onSearch().
m_searchTreeWidget
FileBrowserTreeWidget* lmms::gui::FileBrowser::m_searchTreeWidget private
Definition at line 104 of file FileBrowser.h.
Referenced by FileBrowser(), onSearch(), and onSearchMatch().
m_showFactoryContent
QCheckBox* lmms::gui::FileBrowser::m_showFactoryContent = nullptr private
Definition at line 118 of file FileBrowser.h.
Referenced by addContentCheckBox(), onSearch(), and reloadTree().
m_showHiddenContent
QCheckBox* lmms::gui::FileBrowser::m_showHiddenContent = nullptr private
Definition at line 119 of file FileBrowser.h.
Referenced by addContentCheckBox(), addItems(), and onSearch().
m_showUserContent
QCheckBox* lmms::gui::FileBrowser::m_showUserContent = nullptr private
Definition at line 117 of file FileBrowser.h.
Referenced by addContentCheckBox(), onSearch(), and reloadTree().
m_type
Type lmms::gui::FileBrowser::m_type private
Definition at line 107 of file FileBrowser.h.
Referenced by FileBrowser(), and reloadTree().
m_userDir
QString lmms::gui::FileBrowser::m_userDir private
Definition at line 124 of file FileBrowser.h.
Referenced by FileBrowser(), addContentCheckBox(), onSearch(), and reloadTree().
outerLayout
QBoxLayout* lmms::gui::FileBrowser::outerLayout = nullptr private
Definition at line 123 of file FileBrowser.h.
Referenced by addContentCheckBox().
The documentation for this class was generated from the following files:
include/FileBrowser.h
src/gui/FileBrowser.cpp