LMMS: Jack::JackNetAdapter Struct Reference
Jack::JackNetAdapter Struct Reference
Net adapter.
#include <JackNetAdapter.h>
Public Member Functions
JackNetAdapter (int input, int output, jack_nframes_t host_buffer_size, jack_nframes_t host_sample_rate, jack_nframes_t adapted_buffer_size, jack_nframes_t adapted_sample_rate)
JackNetAdapter (jack_client_t *jack_client, jack_nframes_t buffer_size, jack_nframes_t sample_rate, const JSList *params)
~JackNetAdapter ()
virtual ~JackNetAdapter ()
int Close ()
void Create ()
bool Execute ()
void Flush ()
bool Init ()
int Open ()
int Process ()
int Read ()
int SetBufferSize (jack_nframes_t buffer_size)
int Write ()
Public Member Functions inherited from Jack::JackAudioAdapterInterface
JackAudioAdapterInterface (jack_nframes_t buffer_size, jack_nframes_t sample_rate, jack_nframes_t ring_buffer_size=DEFAULT_ADAPTATIVE_SIZE)
JackAudioAdapterInterface (jack_nframes_t host_buffer_size, jack_nframes_t host_sample_rate, jack_nframes_t adapted_buffer_size, jack_nframes_t adapted_sample_rate, jack_nframes_t ring_buffer_size=DEFAULT_ADAPTATIVE_SIZE)
virtual ~JackAudioAdapterInterface ()
virtual void Destroy ()
virtual int GetInputLatency (int port_index)
int GetInputs ()
virtual int GetOutputLatency (int port_index)
int GetOutputs ()
int PullAndPush (jack_default_audio_sample_t **inputBuffer, jack_default_audio_sample_t **outputBuffer, unsigned int frames)
int PushAndPull (jack_default_audio_sample_t **inputBuffer, jack_default_audio_sample_t **outputBuffer, unsigned int frames)
virtual void Reset ()
virtual int SetAdaptedBufferSize (jack_nframes_t buffer_size)
virtual int SetAdaptedSampleRate (jack_nframes_t sample_rate)
virtual int SetHostBufferSize (jack_nframes_t buffer_size)
virtual int SetHostSampleRate (jack_nframes_t sample_rate)
void SetInputs (int inputs)
void SetOutputs (int outputs)
virtual int SetSampleRate (jack_nframes_t sample_rate)
Public Member Functions inherited from Jack::JackNetSlaveInterface
JackNetSlaveInterface ()
JackNetSlaveInterface (const char *ip, int port)
virtual ~JackNetSlaveInterface ()
Public Member Functions inherited from Jack::JackNetInterface
JackNetInterface ()
JackNetInterface (const char *multicast_ip, int port)
JackNetInterface (session_params_t &params, JackNetSocket &socket, const char *multicast_ip)
virtual ~JackNetInterface ()
Private Member Functions
void DecodeTransportData ()
void EncodeTransportData ()
Private Attributes
jack_client_t * fClient
int fLastTimebaseMaster
int fLastTransportState
sample_t ** fSoftCaptureBuffer
sample_t ** fSoftPlaybackBuffer
JackThread fThread
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAudioAdapterInterface
void AdaptRingBufferSize ()
void GrowRingBufferSize ()
void ResetRingBuffers ()
Protected Member Functions inherited from Jack::JackNetSlaveInterface
int DataRecv ()
int DataSend ()
void DecodeSyncPacket (int &frames)
void EncodeSyncPacket (int frames=-1)
void FatalRecvError ()
void FatalSendError ()
bool Init ()
void InitAPI ()
bool InitConnection (int time_out_sec)
bool InitRendering ()
int Recv (size_t size, int flags)
int Send (size_t size, int flags)
net_status_t SendAvailableToMaster (int count=INT_MAX)
net_status_t SendStartToMaster ()
bool SetParams ()
int SyncRecv ()
int SyncSend ()
Protected Member Functions inherited from Jack::JackNetInterface
NetAudioBuffer * AudioBufferFactory (int nports, char *buffer)
int AudioRecv (packet_header_t *rx_head, NetAudioBuffer *buffer)
int AudioSend (NetAudioBuffer *buffer, int audio_channels)
int FinishRecv (NetAudioBuffer *buffer)
void FreeNetworkBuffers ()
void Initialize ()
int MidiRecv (packet_header_t *rx_head, NetMidiBuffer *buffer, uint &recvd_midi_pckt)
int MidiSend (NetMidiBuffer *buffer, int midi_channnels, int audio_channels)
int SetNetBufferSize ()
void SetPacketTimeOut (int time_out)
void SetRcvTimeOut ()
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Protected Attributes inherited from Jack::JackAudioAdapterInterface
bool fAdaptative
jack_nframes_t fAdaptedBufferSize
jack_nframes_t fAdaptedSampleRate
int fCaptureChannels
JackResampler ** fCaptureRingBuffer
jack_nframes_t fHostBufferSize
jack_nframes_t fHostSampleRate
JackPIControler fPIControler
int fPlaybackChannels
JackResampler ** fPlaybackRingBuffer
jack_time_t fPullAndPushTime
unsigned int fQuality
unsigned int fRingbufferCurSize
bool fRunning
Protected Attributes inherited from Jack::JackNetInterface
char fMulticastIP [32]
NetAudioBuffer * fNetAudioCaptureBuffer
NetAudioBuffer * fNetAudioPlaybackBuffer
NetMidiBuffer * fNetMidiCaptureBuffer
NetMidiBuffer * fNetMidiPlaybackBuffer
int fPacketTimeOut
session_params_t fParams
net_transport_data_t fReturnTransportData
char * fRxBuffer
char * fRxData
packet_header_t fRxHeader
net_transport_data_t fSendTransportData
bool fSetTimeOut
JackNetSocket fSocket
char * fTxBuffer
char * fTxData
packet_header_t fTxHeader
Static Protected Attributes inherited from Jack::JackNetSlaveInterface
static uint fSlaveCounter = 0
Detailed Description
Net adapter.
Definition at line 33 of file JackNetAdapter.h.
Constructor & Destructor Documentation
JackNetAdapter() [1/2]
Jack::JackNetAdapter::JackNetAdapter (jack_client_t * jack_client, jack_nframes_t buffer_size, jack_nframes_t sample_rate, const JSList * params)
Definition at line 28 of file JackNetAdapter.cpp.
References Jack::JackAudioAdapterInterface::JackAudioAdapterInterface(), Jack::JackNetSlaveInterface::JackNetSlaveInterface(), jack_driver_param_t::character, _JSList::data, DEFAULT_MTU, DEFAULT_MULTICAST_IP, DEFAULT_PORT, Jack::JackAudioAdapterInterface::fAdaptative, fClient, Jack::JackNetInterface::fMulticastIP, Jack::JackNetInterface::fParams, Jack::JackAudioAdapterInterface::fQuality, Jack::JackAudioAdapterInterface::fRingbufferCurSize, Jack::JackNetInterface::fSocket, fSoftCaptureBuffer, fSoftPlaybackBuffer, fThread, Jack::GetHostName(), jack_driver_param_value_t::i, JACK_CLIENT_NAME_SIZE, jack_error, jack_log(), jack_slist_next, Jack::JackCeltEncoder, Jack::JackFloatEncoder, Jack::JackOpusEncoder, NETWORK_DEFAULT_LATENCY, NETWORK_MAX_LATENCY, Jack::JackAudioAdapterInterface::SetInputs(), Jack::JackAudioAdapterInterface::SetOutputs(), jack_driver_param_value_t::str, jack_driver_param_value_t::ui, and jack_driver_param_t::value.
~JackNetAdapter() [1/2]
Jack::JackNetAdapter::~JackNetAdapter ()
Definition at line 151 of file JackNetAdapter.cpp.
References Jack::JackAudioAdapterInterface::fCaptureChannels, Jack::JackAudioAdapterInterface::fPlaybackChannels, fSoftCaptureBuffer, fSoftPlaybackBuffer, and jack_log().
JackNetAdapter() [2/2]
Jack::JackNetAdapter::JackNetAdapter (int input, int output, jack_nframes_t host_buffer_size, jack_nframes_t host_sample_rate, jack_nframes_t adapted_buffer_size, jack_nframes_t adapted_sample_rate) inline
Definition at line 980 of file JackNetAPI.cpp.
References Jack::JackAudioAdapterInterface::JackAudioAdapterInterface(), Create(), Jack::JackAudioAdapterInterface::fCaptureChannels, and Jack::JackAudioAdapterInterface::fPlaybackChannels.
~JackNetAdapter() [2/2]
virtual Jack::JackNetAdapter::~JackNetAdapter () inline virtual
Definition at line 1030 of file JackNetAPI.cpp.
References Jack::JackAudioAdapterInterface::Destroy().
Member Function Documentation
Close()
int Jack::JackNetAdapter::Close () virtual
Reimplemented from Jack::JackAudioAdapterInterface.
Definition at line 183 of file JackNetAdapter.cpp.
References Jack::JackAudioAdapterInterface::fAdaptedBufferSize, Jack::JackAudioAdapterInterface::fAdaptedSampleRate, Jack::JackAudioAdapterInterface::fHostBufferSize, Jack::JackAudioAdapterInterface::fHostSampleRate, Jack::JackNetInterface::fSocket, fThread, jack_error, and jack_log().
Create()
void Jack::JackNetAdapter::Create () inline virtual
Reimplemented from Jack::JackAudioAdapterInterface.
Definition at line 992 of file JackNetAPI.cpp.
References Jack::JackAudioAdapterInterface::AdaptRingBufferSize(), DEFAULT_RB_SIZE, Jack::JackAudioAdapterInterface::fAdaptative, Jack::JackAudioAdapterInterface::fCaptureChannels, Jack::JackAudioAdapterInterface::fCaptureRingBuffer, Jack::JackAudioAdapterInterface::fPlaybackChannels, Jack::JackAudioAdapterInterface::fPlaybackRingBuffer, Jack::JackAudioAdapterInterface::fRingbufferCurSize, i, jack_info(), and jack_log().
Referenced by JackNetAdapter().
DecodeTransportData()
void Jack::JackNetAdapter::DecodeTransportData () private virtual
Implements Jack::JackNetInterface.
Definition at line 288 of file JackNetAdapter.cpp.
References fClient, Jack::JackNetInterface::fSendTransportData, jack_info(), jack_transport_query(), jack_transport_reposition(), jack_transport_start(), jack_transport_stop(), JackTransportRolling, JackTransportStarting, and JackTransportStopped.
EncodeTransportData()
void Jack::JackNetAdapter::EncodeTransportData () private virtual
Implements Jack::JackNetInterface.
Definition at line 317 of file JackNetAdapter.cpp.
References Jack::CONDITIONAL_TIMEBASEMASTER, fClient, fLastTimebaseMaster, fLastTransportState, Jack::JackNetInterface::fReturnTransportData, Jack::JackNetInterface::fSendTransportData, Jack::GetTransportState(), jack_info(), jack_transport_query(), Jack::NO_CHANGE, Jack::RELEASE_TIMEBASEMASTER, and Jack::TIMEBASEMASTER.
Execute()
bool Jack::JackNetAdapter::Execute () virtual
Implements Jack::JackRunnableInterface.
Definition at line 261 of file JackNetAdapter.cpp.
References fThread, Init(), jack_info(), Jack::detail::JackThreadInterface::kIniting, Jack::detail::JackThreadInterface::kRunning, Jack::JackException::PrintMessage(), Process(), Jack::JackAudioAdapterInterface::Reset(), and SOCKET_ERROR.
Flush()
void Jack::JackNetAdapter::Flush () inline
Definition at line 1035 of file JackNetAPI.cpp.
References Jack::JackAudioAdapterInterface::fCaptureChannels, Jack::JackAudioAdapterInterface::fCaptureRingBuffer, Jack::JackAudioAdapterInterface::fPlaybackChannels, Jack::JackAudioAdapterInterface::fPlaybackRingBuffer, Jack::JackAudioAdapterInterface::fRingbufferCurSize, and i.
Referenced by jack_flush_adapter().
Init()
bool Jack::JackNetAdapter::Init () virtual
Implements Jack::JackNetInterface.
Definition at line 210 of file JackNetAdapter.cpp.
References Jack::JackAudioAdapterInterface::fCaptureChannels, Jack::JackNetInterface::fNetAudioCaptureBuffer, Jack::JackNetInterface::fNetAudioPlaybackBuffer, Jack::JackNetInterface::fParams, Jack::JackAudioAdapterInterface::fPlaybackChannels, fSoftCaptureBuffer, fSoftPlaybackBuffer, fThread, Jack::GetEngineControl(), Jack::JackNetSlaveInterface::Init(), jack_error, jack_log(), Jack::SessionParamsDisplay(), set_threaded_log_function(), Jack::JackAudioAdapterInterface::SetAdaptedBufferSize(), Jack::JackAudioAdapterInterface::SetAdaptedSampleRate(), and Jack::JackNetSlaveInterface::SetParams().
Referenced by Execute().
Open()
int Jack::JackNetAdapter::Open () virtual
Reimplemented from Jack::JackAudioAdapterInterface.
Definition at line 170 of file JackNetAdapter.cpp.
References Jack::JackNetInterface::fParams, fThread, jack_error, and jack_info().
Process()
int Jack::JackNetAdapter::Process ()
Definition at line 384 of file JackNetAdapter.cpp.
References Jack::JackAudioAdapterInterface::fAdaptedBufferSize, fSoftCaptureBuffer, fSoftPlaybackBuffer, Jack::JackAudioAdapterInterface::PushAndPull(), Read(), SOCKET_ERROR, and Write().
Referenced by Execute().
Read()
int Jack::JackNetAdapter::Read ()
Definition at line 351 of file JackNetAdapter.cpp.
References Jack::JackNetSlaveInterface::DataRecv(), Jack::JackNetSlaveInterface::DecodeSyncPacket(), SOCKET_ERROR, SYNC_PACKET_ERROR, and Jack::JackNetSlaveInterface::SyncRecv().
Referenced by Process().
SetBufferSize()
int Jack::JackNetAdapter::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackAudioAdapterInterface.
Definition at line 201 of file JackNetAdapter.cpp.
References Jack::JackAudioAdapterInterface::SetHostBufferSize().
Write()
int Jack::JackNetAdapter::Write ()
Definition at line 372 of file JackNetAdapter.cpp.
References Jack::JackNetSlaveInterface::DataSend(), Jack::JackNetSlaveInterface::EncodeSyncPacket(), SOCKET_ERROR, and Jack::JackNetSlaveInterface::SyncSend().
Referenced by Process().
Member Data Documentation
fClient
jack_client_t* Jack::JackNetAdapter::fClient private
Definition at line 41 of file JackNetAdapter.h.
Referenced by JackNetAdapter(), DecodeTransportData(), and EncodeTransportData().
fLastTimebaseMaster
int Jack::JackNetAdapter::fLastTimebaseMaster private
Definition at line 45 of file JackNetAdapter.h.
Referenced by EncodeTransportData().
fLastTransportState
int Jack::JackNetAdapter::fLastTransportState private
Definition at line 44 of file JackNetAdapter.h.
Referenced by EncodeTransportData().
fSoftCaptureBuffer
sample_t** Jack::JackNetAdapter::fSoftCaptureBuffer private
Definition at line 48 of file JackNetAdapter.h.
Referenced by JackNetAdapter(), ~JackNetAdapter(), Init(), and Process().
fSoftPlaybackBuffer
sample_t** Jack::JackNetAdapter::fSoftPlaybackBuffer private
Definition at line 49 of file JackNetAdapter.h.
Referenced by JackNetAdapter(), ~JackNetAdapter(), Init(), and Process().
fThread
JackThread Jack::JackNetAdapter::fThread private
Definition at line 52 of file JackNetAdapter.h.
Referenced by JackNetAdapter(), Close(), Execute(), Init(), and Open().
The documentation for this struct was generated from the following files:
src/3rdparty/jack2/common/JackNetAdapter.h
src/3rdparty/jack2/common/JackNetAPI.cpp
src/3rdparty/jack2/common/JackNetAdapter.cpp