LMMS: Jack::AtomicCounter Struct Reference
Jack::AtomicCounter Struct Reference
Counter for CAS.
#include <JackAtomicState.h>
Public Member Functions
AtomicCounter ()
AtomicCounter (volatile AtomicCounter &obj)
AtomicCounter (volatile const AtomicCounter &obj)
AtomicCounter & operator= (AtomicCounter &obj)
AtomicCounter & operator= (volatile AtomicCounter &obj)
Public Attributes
union {
UInt32 fLongVal
struct {
UInt16 fShortVal1
UInt16 fShortVal2
} scounter
} info
Detailed Description
Counter for CAS.
Definition at line 36 of file JackAtomicState.h.
Constructor & Destructor Documentation
AtomicCounter() [1/3]
Jack::AtomicCounter::AtomicCounter () inline
Definition at line 47 of file JackAtomicState.h.
References info.
Referenced by AtomicCounter(), AtomicCounter(), operator=(), and operator=().
AtomicCounter() [2/3]
Jack::AtomicCounter::AtomicCounter (volatile const AtomicCounter & obj) inline
Definition at line 52 of file JackAtomicState.h.
References AtomicCounter(), fLongVal, and info.
AtomicCounter() [3/3]
Jack::AtomicCounter::AtomicCounter (volatile AtomicCounter & obj) inline
Definition at line 57 of file JackAtomicState.h.
References AtomicCounter(), fLongVal, and info.
Member Function Documentation
operator=() [1/2]
AtomicCounter & Jack::AtomicCounter::operator= (AtomicCounter & obj) inline
Definition at line 62 of file JackAtomicState.h.
References AtomicCounter(), fLongVal, and info.
operator=() [2/2]
AtomicCounter & Jack::AtomicCounter::operator= (volatile AtomicCounter & obj) inline
Definition at line 68 of file JackAtomicState.h.
References AtomicCounter(), fLongVal, and info.
Member Data Documentation
fLongVal
UInt32 Jack::AtomicCounter::fLongVal
Definition at line 44 of file JackAtomicState.h.
Referenced by AtomicCounter(), AtomicCounter(), operator=(), and operator=().
fShortVal1
UInt16 Jack::AtomicCounter::fShortVal1
Definition at line 40 of file JackAtomicState.h.
fShortVal2
UInt16 Jack::AtomicCounter::fShortVal2
Definition at line 41 of file JackAtomicState.h.
[union]
union { ... } Jack::AtomicCounter::info
Referenced by AtomicCounter(), AtomicCounter(), AtomicCounter(), operator=(), and operator=().
[struct]
struct { ... } Jack::AtomicCounter::scounter
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackAtomicState.h