LMMS: Jack::JackNetMasterManager Class Reference
Jack::JackNetMasterManager Class Reference
\Brief This class describer the Network Manager
#include <JackNetManager.h>
Public Member Functions
JackNetMasterManager (jack_client_t *jack_client, const JSList *params)
~JackNetMasterManager ()
Private Member Functions
int CountIO (const char *type, int flags)
master_list_it_t FindMaster (uint32_t client_id)
JackNetMaster * InitMaster (session_params_t &params)
int KillMaster (session_params_t *params)
void Run ()
void ShutDown ()
int SyncCallback (jack_transport_state_t state, jack_position_t *pos)
Static Private Member Functions
static void * NetManagerThread (void *arg)
static void SetShutDown (void *arg)
static int SetSyncCallback (jack_transport_state_t state, jack_position_t *pos, void *arg)
Private Attributes
bool fAutoConnect
bool fAutoSave
jack_client_t * fClient
uint32_t fGlobalID
master_connections_list_t fMasterConnectionList
master_list_t fMasterList
char fMulticastIP [32]
const char * fName
bool fRunning
JackNetSocket fSocket
jack_native_thread_t fThread
Friends
class JackNetMaster
Detailed Description
\Brief This class describer the Network Manager
Definition at line 102 of file JackNetManager.h.
Constructor & Destructor Documentation
JackNetMasterManager()
Jack::JackNetMasterManager::JackNetMasterManager (jack_client_t * jack_client, const JSList * params)
Definition at line 636 of file JackNetManager.cpp.
References jack_driver_param_t::character, client(), _JSList::data, DEFAULT_MULTICAST_IP, DEFAULT_PORT, fAutoConnect, fAutoSave, fClient, fGlobalID, fMulticastIP, fName, fRunning, fSocket, fThread, jack_activate(), jack_client_create_thread(), jack_error, jack_get_client_name(), jack_log(), jack_on_shutdown(), jack_set_sync_callback(), jack_slist_next, NetManagerThread(), SetShutDown(), SetSyncCallback(), jack_driver_param_value_t::str, jack_driver_param_value_t::ui, and jack_driver_param_t::value.
Referenced by NetManagerThread(), SetShutDown(), and SetSyncCallback().
~JackNetMasterManager()
Jack::JackNetMasterManager::~JackNetMasterManager ()
Definition at line 703 of file JackNetManager.cpp.
References jack_log(), and ShutDown().
Member Function Documentation
CountIO()
int Jack::JackNetMasterManager::CountIO (const char * type, int flags) private
Definition at line 709 of file JackNetManager.cpp.
References fClient, jack_free(), and jack_get_ports().
Referenced by InitMaster().
FindMaster()
master_list_it_t Jack::JackNetMasterManager::FindMaster (uint32_t client_id) private
Definition at line 903 of file JackNetManager.cpp.
References fMasterList, and jack_log().
Referenced by KillMaster().
InitMaster()
JackNetMaster * Jack::JackNetMasterManager::InitMaster (session_params_t & params) private
Definition at line 853 of file JackNetManager.cpp.
References CountIO(), fAutoConnect, fAutoSave, fClient, fGlobalID, Jack::_session_params::fID, fMasterConnectionList, fMasterList, Jack::_session_params::fMasterNetName, fMulticastIP, Jack::_session_params::fName, Jack::_session_params::fPeriodSize, Jack::_session_params::fProtocolVersion, Jack::_session_params::fReturnAudioChannels, Jack::_session_params::fReturnMidiChannels, Jack::_session_params::fSampleRate, Jack::_session_params::fSendAudioChannels, Jack::_session_params::fSendMidiChannels, fSocket, Jack::JackNetMaster::Init(), JACK_DEFAULT_AUDIO_TYPE, JACK_DEFAULT_MIDI_TYPE, jack_error, jack_get_buffer_size(), jack_get_sample_rate(), jack_info(), jack_log(), JackNetMaster, JackPortIsInput, JackPortIsOutput, JackPortIsPhysical, Jack::JackNetMaster::LoadConnections(), and NETWORK_PROTOCOL.
Referenced by Run().
KillMaster()
int Jack::JackNetMasterManager::KillMaster (session_params_t * params) private
Definition at line 916 of file JackNetManager.cpp.
References fAutoSave, Jack::_session_params::fID, FindMaster(), fMasterConnectionList, fMasterList, Jack::_session_params::fName, and jack_log().
Referenced by Run().
NetManagerThread()
void * Jack::JackNetMasterManager::NetManagerThread (void * arg) static private
Definition at line 760 of file JackNetManager.cpp.
References JackNetMasterManager(), jack_info(), and master_manager.
Referenced by JackNetMasterManager().
Run()
void Jack::JackNetMasterManager::Run () private
Definition at line 769 of file JackNetManager.cpp.
References fMulticastIP, Jack::JackNetInterface::fParams, fRunning, fSocket, Jack::GetPacketType(), InitMaster(), jack_error, jack_info(), jack_log(), JackNetMaster, Jack::KILL_MASTER, KillMaster(), MANAGER_INIT_TIMEOUT, NET_ERROR_CODE, Jack::NET_NO_DATA, Jack::SessionParamsDisplay(), Jack::SessionParamsNToH(), Jack::SLAVE_AVAILABLE, SOCKET_ERROR, Jack::SocketAPIInit(), and StrError.
SetShutDown()
void Jack::JackNetMasterManager::SetShutDown (void * arg) static private
Definition at line 720 of file JackNetManager.cpp.
References JackNetMasterManager(), and ShutDown().
Referenced by JackNetMasterManager().
SetSyncCallback()
int Jack::JackNetMasterManager::SetSyncCallback (jack_transport_state_t state, jack_position_t * pos, void * arg) static private
Definition at line 741 of file JackNetManager.cpp.
References JackNetMasterManager(), pos, and SyncCallback().
Referenced by JackNetMasterManager().
ShutDown()
void Jack::JackNetMasterManager::ShutDown () private
Definition at line 725 of file JackNetManager.cpp.
References fClient, fMasterList, fRunning, fSocket, fThread, jack_client_kill_thread(), jack_log(), and Jack::SocketAPIEnd().
Referenced by ~JackNetMasterManager(), and SetShutDown().
SyncCallback()
int Jack::JackNetMasterManager::SyncCallback (jack_transport_state_t state, jack_position_t * pos) private
Definition at line 746 of file JackNetManager.cpp.
References fMasterList, jack_log(), and pos.
Referenced by SetSyncCallback().
Friends And Related Symbol Documentation
JackNetMaster
friend class JackNetMaster friend
Definition at line 104 of file JackNetManager.h.
References JackNetMaster, and pos.
Referenced by InitMaster(), JackNetMaster, and Run().
Member Data Documentation
fAutoConnect
bool Jack::JackNetMasterManager::fAutoConnect private
Definition at line 121 of file JackNetManager.h.
Referenced by JackNetMasterManager(), and InitMaster().
fAutoSave
bool Jack::JackNetMasterManager::fAutoSave private
Definition at line 122 of file JackNetManager.h.
Referenced by JackNetMasterManager(), InitMaster(), and KillMaster().
fClient
jack_client_t* Jack::JackNetMasterManager::fClient private
Definition at line 112 of file JackNetManager.h.
Referenced by JackNetMasterManager(), CountIO(), InitMaster(), and ShutDown().
fGlobalID
uint32_t Jack::JackNetMasterManager::fGlobalID private
Definition at line 119 of file JackNetManager.h.
Referenced by JackNetMasterManager(), and InitMaster().
fMasterConnectionList
master_connections_list_t Jack::JackNetMasterManager::fMasterConnectionList private
Definition at line 118 of file JackNetManager.h.
Referenced by InitMaster(), and KillMaster().
fMasterList
master_list_t Jack::JackNetMasterManager::fMasterList private
Definition at line 117 of file JackNetManager.h.
Referenced by FindMaster(), InitMaster(), KillMaster(), ShutDown(), and SyncCallback().
fMulticastIP
char Jack::JackNetMasterManager::fMulticastIP[32] private
Definition at line 114 of file JackNetManager.h.
Referenced by JackNetMasterManager(), InitMaster(), and Run().
fName
const char* Jack::JackNetMasterManager::fName private
Definition at line 113 of file JackNetManager.h.
Referenced by JackNetMasterManager().
fRunning
bool Jack::JackNetMasterManager::fRunning private
Definition at line 120 of file JackNetManager.h.
Referenced by JackNetMasterManager(), Run(), and ShutDown().
fSocket
JackNetSocket Jack::JackNetMasterManager::fSocket private
Definition at line 115 of file JackNetManager.h.
Referenced by JackNetMasterManager(), InitMaster(), Run(), and ShutDown().
fThread
jack_native_thread_t Jack::JackNetMasterManager::fThread private
Definition at line 116 of file JackNetManager.h.
Referenced by JackNetMasterManager(), and ShutDown().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackNetManager.h
src/3rdparty/jack2/common/JackNetManager.cpp