LMMS: Jack::JackSocketServerChannel Class Reference
Jack::JackSocketServerChannel Class Reference
JackServerChannel using sockets.
#include <JackSocketServerChannel.h>
Public Member Functions
JackSocketServerChannel ()
~JackSocketServerChannel ()
void Close ()
bool Execute ()
bool Init ()
Called once when the thread is started.
int Open (const char *server_name, JackServer *server)
int Start ()
void Stop ()
Public Member Functions inherited from Jack::JackClientHandlerInterface
virtual ~JackClientHandlerInterface ()
Private Member Functions
void BuildPoolTable ()
void ClientAdd (detail::JackChannelTransactionInterface *socket, JackClientOpenRequest *req, JackClientOpenResult *res)
void ClientCreate ()
void ClientKill (int fd)
void ClientRemove (detail::JackChannelTransactionInterface *socket, int refnum)
int GetFd (JackClientSocket *socket)
Private Attributes
JackRequestDecoder * fDecoder
pollfd * fPollTable
bool fRebuild
JackServerSocket fRequestListenSocket
JackServer * fServer
std::map< int, std::pair< int, JackClientSocket * > > fSocketTable
JackThread fThread
Additional Inherited Members
Protected Member Functions inherited from Jack::JackRunnableInterface
JackRunnableInterface ()
virtual ~JackRunnableInterface ()
Detailed Description
JackServerChannel using sockets.
Definition at line 39 of file JackSocketServerChannel.h.
Constructor & Destructor Documentation
JackSocketServerChannel()
Jack::JackSocketServerChannel::JackSocketServerChannel ()
Definition at line 38 of file JackSocketServerChannel.cpp.
References fDecoder, fPollTable, fRebuild, and fThread.
~JackSocketServerChannel()
Jack::JackSocketServerChannel::~JackSocketServerChannel ()
Definition at line 45 of file JackSocketServerChannel.cpp.
References fPollTable.
Member Function Documentation
BuildPoolTable()
void Jack::JackSocketServerChannel::BuildPoolTable () private
Definition at line 185 of file JackSocketServerChannel.cpp.
References fPollTable, fRebuild, fRequestListenSocket, fSocketTable, i, and jack_log().
Referenced by Execute(), and Open().
ClientAdd()
void Jack::JackSocketServerChannel::ClientAdd (detail::JackChannelTransactionInterface * socket, JackClientOpenRequest * req, JackClientOpenResult * res) private virtual
Implements Jack::JackClientHandlerInterface.
Definition at line 128 of file JackSocketServerChannel.cpp.
References Jack::JackClientOpenRequest::fName, Jack::JackClientOpenRequest::fPID, fRebuild, Jack::JackResult::fResult, fServer, Jack::JackClientOpenResult::fSharedClient, Jack::JackClientOpenResult::fSharedEngine, Jack::JackClientOpenResult::fSharedGraph, fSocketTable, Jack::JackClientOpenRequest::fUUID, GetFd(), jack_error, and jack_log().
ClientCreate()
void Jack::JackSocketServerChannel::ClientCreate () private
Definition at line 102 of file JackSocketServerChannel.cpp.
References fRebuild, fRequestListenSocket, fSocketTable, Jack::JackClientSocket::GetFd(), jack_error, and jack_log().
Referenced by Execute().
ClientKill()
void Jack::JackSocketServerChannel::ClientKill (int fd) private
Definition at line 165 of file JackSocketServerChannel.cpp.
References Jack::JackClientSocket::Close(), fRebuild, fServer, fSocketTable, and jack_log().
Referenced by Execute().
ClientRemove()
void Jack::JackSocketServerChannel::ClientRemove (detail::JackChannelTransactionInterface * socket, int refnum) private virtual
Implements Jack::JackClientHandlerInterface.
Definition at line 151 of file JackSocketServerChannel.cpp.
References Jack::JackClientSocket::Close(), fRebuild, fSocketTable, GetFd(), and jack_log().
Close()
void Jack::JackSocketServerChannel::Close ()
Definition at line 68 of file JackSocketServerChannel.cpp.
References Jack::JackClientSocket::Close(), fDecoder, fRequestListenSocket, and fSocketTable.
Execute()
bool Jack::JackSocketServerChannel::Execute () virtual
Implements Jack::JackRunnableInterface.
Definition at line 219 of file JackSocketServerChannel.cpp.
References BuildPoolTable(), ClientCreate(), ClientKill(), fDecoder, fPollTable, fSocketTable, Jack::JackRequest::fType, i, jack_error, jack_log(), and Jack::JackRequest::Read().
GetFd()
int Jack::JackSocketServerChannel::GetFd (JackClientSocket * socket) private
Definition at line 114 of file JackSocketServerChannel.cpp.
References fSocketTable.
Referenced by ClientAdd(), and ClientRemove().
Init()
bool Jack::JackSocketServerChannel::Init () virtual
Called once when the thread is started.
Reimplemented from Jack::JackRunnableInterface.
Definition at line 210 of file JackSocketServerChannel.cpp.
Open()
int Jack::JackSocketServerChannel::Open (const char * server_name, JackServer * server)
Definition at line 50 of file JackSocketServerChannel.cpp.
References BuildPoolTable(), fDecoder, fRequestListenSocket, fServer, jack_log(), jack_server_dir, server(), and server_name.
Start()
int Jack::JackSocketServerChannel::Start ()
Definition at line 87 of file JackSocketServerChannel.cpp.
References fThread, and jack_error.
Stop()
void Jack::JackSocketServerChannel::Stop ()
Definition at line 97 of file JackSocketServerChannel.cpp.
References fThread.
Member Data Documentation
fDecoder
JackRequestDecoder* Jack::JackSocketServerChannel::fDecoder private
Definition at line 46 of file JackSocketServerChannel.h.
Referenced by JackSocketServerChannel(), Close(), Execute(), and Open().
fPollTable
pollfd* Jack::JackSocketServerChannel::fPollTable private
Definition at line 49 of file JackSocketServerChannel.h.
Referenced by JackSocketServerChannel(), ~JackSocketServerChannel(), BuildPoolTable(), and Execute().
fRebuild
bool Jack::JackSocketServerChannel::fRebuild private
Definition at line 50 of file JackSocketServerChannel.h.
Referenced by JackSocketServerChannel(), BuildPoolTable(), ClientAdd(), ClientCreate(), ClientKill(), and ClientRemove().
fRequestListenSocket
JackServerSocket Jack::JackSocketServerChannel::fRequestListenSocket private
Definition at line 44 of file JackSocketServerChannel.h.
Referenced by BuildPoolTable(), ClientCreate(), Close(), and Open().
fServer
JackServer* Jack::JackSocketServerChannel::fServer private
Definition at line 47 of file JackSocketServerChannel.h.
Referenced by ClientAdd(), ClientKill(), and Open().
fSocketTable
std::map<int, std::pair<int, JackClientSocket*> > Jack::JackSocketServerChannel::fSocketTable private
Definition at line 51 of file JackSocketServerChannel.h.
Referenced by BuildPoolTable(), ClientAdd(), ClientCreate(), ClientKill(), ClientRemove(), Close(), Execute(), and GetFd().
fThread
JackThread Jack::JackSocketServerChannel::fThread private
Definition at line 45 of file JackSocketServerChannel.h.
Referenced by JackSocketServerChannel(), Start(), and Stop().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/posix/JackSocketServerChannel.h
src/3rdparty/jack2/posix/JackSocketServerChannel.cpp