LMMS: lmms::gui::TrackContentWidget Class Reference
lmms::gui::TrackContentWidget Class Reference
#include <TrackContentWidget.h>
Public Slots
void changePosition (const lmms::TimePos &newPos=TimePos(-1))
Move the trackContentWidget to a new place in time.
void update ()
Update ourselves by updating all the ClipViews attached.
void updateBackground ()
Updates the background tile pixmap.
Public Member Functions
TrackContentWidget (TrackView *parent)
Create a new trackContentWidget.
~TrackContentWidget () override=default
void addClipView (ClipView *clipv)
Adds a ClipView to this widget.
bool canPasteSelection (TimePos clipPos, const QDropEvent *de)
Returns whether a selection of Clips can be pasted into this.
bool canPasteSelection (TimePos clipPos, const QMimeData *md, bool allowSameBar=false)
QBrush coarseGridColor () const
CSS theming qproperty access method.
int coarseGridWidth () const
CSS theming qproperty access method.
QBrush darkerColor () const
CSS theming qproperty access method.
QBrush embossColor () const
CSS theming qproperty access method.
int embossOffset () const
CSS theming qproperty access method.
int embossWidth () const
CSS theming qproperty access method.
TimePos endPosition (const TimePos &posStart)
Return the end position of the trackContentWidget in Bars.
QBrush fineGridColor () const
CSS theming qproperty access method.
int fineGridWidth () const
CSS theming qproperty access method.
QBrush horizontalColor () const
CSS theming qproperty access method.
int horizontalWidth () const
CSS theming qproperty access method.
QBrush lighterColor () const
CSS theming qproperty access method.
bool pasteSelection (TimePos clipPos, const QMimeData *md, bool skipSafetyCheck=false)
bool pasteSelection (TimePos clipPos, QDropEvent *de)
Pastes a selection of Clips onto the track.
void removeClipView (ClipView *clipv)
Removes the given ClipView from this widget.
void removeClipView (int clipNum)
void setCoarseGridColor (const QBrush &c)
CSS theming qproperty access method.
void setCoarseGridWidth (int c)
CSS theming qproperty access method.
void setDarkerColor (const QBrush &c)
CSS theming qproperty access method.
void setEmbossColor (const QBrush &c)
CSS theming qproperty access method.
void setEmbossOffset (int c)
CSS theming qproperty access method.
void setEmbossWidth (int c)
CSS theming qproperty access method.
void setFineGridColor (const QBrush &c)
CSS theming qproperty access method.
void setFineGridWidth (int c)
CSS theming qproperty access method.
void setHorizontalColor (const QBrush &c)
CSS theming qproperty access method.
void setHorizontalWidth (int c)
CSS theming qproperty access method.
void setLighterColor (const QBrush &c)
CSS theming qproperty access method.
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Types
enum class ContextMenuAction { Paste }
Protected Member Functions
void contextMenuAction (QContextMenuEvent *cme, ContextMenuAction action)
void contextMenuEvent (QContextMenuEvent *cme) override
void dragEnterEvent (QDragEnterEvent *dee) override
Respond to a drag enter event on the trackContentWidget.
void dropEvent (QDropEvent *de) override
Respond to a drop event on the trackContentWidget.
void loadSettings (const QDomElement &element) override
void mousePressEvent (QMouseEvent *me) override
Respond to a mouse press on the trackContentWidget.
void mouseReleaseEvent (QMouseEvent *me) override
QString nodeName () const override
void paintEvent (QPaintEvent *pe) override
Repaint the trackContentWidget on command.
void resizeEvent (QResizeEvent *re) override
Updates the background tile pixmap on size changes.
void saveSettings (QDomDocument &doc, QDomElement &element) override
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Properties
QBrush coarseGridColor
int coarseGridWidth
QBrush darkerColor
QBrush embossColor
int embossOffset
int embossWidth
QBrush fineGridColor
int fineGridWidth
QBrush horizontalColor
int horizontalWidth
QBrush lighterColor
Private Types
using clipViewVector = QVector<ClipView*>
Private Member Functions
TimePos getPosition (int mouseX)
Return the position of the trackContentWidget in bars.
Track * getTrack ()
Return the track shown by the trackContentWidget.
Private Attributes
QPixmap m_background
clipViewVector m_clipViews
QBrush m_coarseGridColor
int m_coarseGridWidth
QBrush m_darkerColor
QBrush m_embossColor
int m_embossOffset
int m_embossWidth
QBrush m_fineGridColor
int m_fineGridWidth
QBrush m_horizontalColor
int m_horizontalWidth
QBrush m_lighterColor
TrackView * m_trackView
Detailed Description
Definition at line 47 of file TrackContentWidget.h.
Member Typedef Documentation
clipViewVector
using lmms::gui::TrackContentWidget::clipViewVector = QVector<ClipView*> private
Definition at line 161 of file TrackContentWidget.h.
Member Enumeration Documentation
ContextMenuAction
enum class lmms::gui::TrackContentWidget::ContextMenuAction strong protected
Enumerator
Paste
Definition at line 124 of file TrackContentWidget.h.
Constructor & Destructor Documentation
TrackContentWidget()
lmms::gui::TrackContentWidget::TrackContentWidget (TrackView * parent)
Create a new trackContentWidget.
Creates a new track content widget for the given track. The content widget comprises the 'grip bar' and the 'tools' button for the track's context menu.
Parameters
parent The parent track.
Definition at line 64 of file TrackContentWidget.cpp.
References changePosition(), lmms::Model::dataChanged(), lmms::gui::getGUI(), m_coarseGridColor, m_coarseGridWidth, m_darkerColor, m_embossColor, m_embossOffset, m_embossWidth, m_fineGridColor, m_fineGridWidth, m_horizontalColor, m_horizontalWidth, m_lighterColor, m_trackView, lmms::gui::SongEditor::proportionalSnapChanged(), lmms::gui::TrackView::trackContainerView(), and updateBackground().
Referenced by ~TrackContentWidget().
~TrackContentWidget()
lmms::gui::TrackContentWidget::~TrackContentWidget () override default
References TrackContentWidget(), addClipView(), and removeClipView().
Member Function Documentation
addClipView()
void lmms::gui::TrackContentWidget::addClipView (ClipView * clipv)
Adds a ClipView to this widget.
Adds a(nother) ClipView to our list of views. We also check that our position is up-to-date.
Parameters
clipv The ClipView to add.
Definition at line 174 of file TrackContentWidget.cpp.
References changePosition(), lmms::gui::ClipView::getClip(), m_clipViews, lmms::JournallingObject::restoreJournallingState(), and lmms::JournallingObject::saveJournallingState().
Referenced by ~TrackContentWidget().
canPasteSelection() [1/2]
bool lmms::gui::TrackContentWidget::canPasteSelection (TimePos clipPos, const QDropEvent * de)
Returns whether a selection of Clips can be pasted into this.
Parameters
clipPos the position of the Clip slot being pasted on
de the DropEvent generated
Definition at line 344 of file TrackContentWidget.cpp.
References canPasteSelection().
Referenced by canPasteSelection(), contextMenuEvent(), lmms::gui::ClipView::dragEnterEvent(), dragEnterEvent(), pasteSelection(), and pasteSelection().
canPasteSelection() [2/2]
bool lmms::gui::TrackContentWidget::canPasteSelection (TimePos clipPos, const QMimeData * md, bool allowSameBar = false)
Definition at line 356 of file TrackContentWidget.cpp.
References lmms::DataFile::content(), lmms::TimePos::getBar(), getTrack(), i, lmms::JournallingObject::id(), m_trackView, lmms::Track::trackContainer(), lmms::TrackContainer::tracks(), and lmms::Track::type().
changePosition
void lmms::gui::TrackContentWidget::changePosition (const lmms::TimePos & newPos = TimePos(-1)) slot
Move the trackContentWidget to a new place in time.
Parameters
newPos The MIDI time to move to.
Definition at line 231 of file TrackContentWidget.cpp.
References lmms::Clip::changeLength(), lmms::Clip::endPosition(), endPosition(), lmms::gui::getGUI(), lmms::Clip::length(), m_clipViews, m_trackView, lmms::Engine::patternStore(), pos, lmms::Clip::startPosition(), lmms::TimePos::ticksPerBar(), ts, and updateBackground().
Referenced by TrackContentWidget(), and addClipView().
coarseGridColor()
QBrush lmms::gui::TrackContentWidget::coarseGridColor () const
CSS theming qproperty access method.
Definition at line 731 of file TrackContentWidget.cpp.
References m_coarseGridColor.
coarseGridWidth()
int lmms::gui::TrackContentWidget::coarseGridWidth () const
CSS theming qproperty access method.
Definition at line 747 of file TrackContentWidget.cpp.
References m_coarseGridWidth.
contextMenuAction()
void lmms::gui::TrackContentWidget::contextMenuAction (QContextMenuEvent * cme, ContextMenuAction action) protected
Definition at line 703 of file TrackContentWidget.cpp.
References getPosition(), Paste, and pasteSelection().
Referenced by contextMenuEvent().
contextMenuEvent()
void lmms::gui::TrackContentWidget::contextMenuEvent (QContextMenuEvent * cme) override protected
Definition at line 677 of file TrackContentWidget.cpp.
References canPasteSelection(), contextMenuAction(), lmms::embed::getIconPixmap(), getPosition(), and Paste.
darkerColor()
QBrush lmms::gui::TrackContentWidget::darkerColor () const
CSS theming qproperty access method.
Definition at line 723 of file TrackContentWidget.cpp.
References m_darkerColor.
dragEnterEvent()
void lmms::gui::TrackContentWidget::dragEnterEvent (QDragEnterEvent * dee) override protected
Respond to a drag enter event on the trackContentWidget.
Parameters
dee the Drag Enter Event to respond to
Definition at line 322 of file TrackContentWidget.cpp.
References canPasteSelection(), getPosition(), getTrack(), and lmms::gui::StringPairDrag::processDragEnterEvent().
dropEvent()
void lmms::gui::TrackContentWidget::dropEvent (QDropEvent * de) override protected
Respond to a drop event on the trackContentWidget.
Parameters
de the Drop Event to respond to
Definition at line 558 of file TrackContentWidget.cpp.
References getPosition(), and pasteSelection().
embossColor()
QBrush lmms::gui::TrackContentWidget::embossColor () const
CSS theming qproperty access method.
Definition at line 743 of file TrackContentWidget.cpp.
References m_embossColor.
embossOffset()
int lmms::gui::TrackContentWidget::embossOffset () const
CSS theming qproperty access method.
Definition at line 763 of file TrackContentWidget.cpp.
References m_embossOffset.
embossWidth()
int lmms::gui::TrackContentWidget::embossWidth () const
CSS theming qproperty access method.
Definition at line 759 of file TrackContentWidget.cpp.
References m_embossWidth.
endPosition()
TimePos lmms::gui::TrackContentWidget::endPosition (const TimePos & posStart)
Return the end position of the trackContentWidget in Bars.
Parameters
posStart the starting position of the Widget (from getPosition())
Definition at line 670 of file TrackContentWidget.cpp.
References m_trackView, and lmms::TimePos::ticksPerBar().
Referenced by changePosition().
fineGridColor()
QBrush lmms::gui::TrackContentWidget::fineGridColor () const
CSS theming qproperty access method.
Definition at line 735 of file TrackContentWidget.cpp.
References m_fineGridColor.
fineGridWidth()
int lmms::gui::TrackContentWidget::fineGridWidth () const
CSS theming qproperty access method.
Definition at line 751 of file TrackContentWidget.cpp.
References m_fineGridWidth.
getPosition()
TimePos lmms::gui::TrackContentWidget::getPosition (int mouseX) private
Return the position of the trackContentWidget in bars.
Parameters
mouseX the mouse's current X position in pixels.
Definition at line 306 of file TrackContentWidget.cpp.
References lmms::gui::TrackContainerView::currentPosition(), m_trackView, lmms::gui::TrackContainerView::pixelsPerBar(), and lmms::TimePos::ticksPerBar().
Referenced by contextMenuAction(), contextMenuEvent(), dragEnterEvent(), dropEvent(), and mousePressEvent().
getTrack()
Track * lmms::gui::TrackContentWidget::getTrack () private
Return the track shown by the trackContentWidget.
Definition at line 658 of file TrackContentWidget.cpp.
References m_trackView.
Referenced by canPasteSelection(), dragEnterEvent(), mousePressEvent(), and pasteSelection().
horizontalColor()
QBrush lmms::gui::TrackContentWidget::horizontalColor () const
CSS theming qproperty access method.
Definition at line 739 of file TrackContentWidget.cpp.
References m_horizontalColor.
horizontalWidth()
int lmms::gui::TrackContentWidget::horizontalWidth () const
CSS theming qproperty access method.
Definition at line 755 of file TrackContentWidget.cpp.
References m_horizontalWidth.
lighterColor()
QBrush lmms::gui::TrackContentWidget::lighterColor () const
CSS theming qproperty access method.
Definition at line 727 of file TrackContentWidget.cpp.
References m_lighterColor.
loadSettings()
void lmms::gui::TrackContentWidget::loadSettings (const QDomElement & element) inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 149 of file TrackContentWidget.h.
mousePressEvent()
void lmms::gui::TrackContentWidget::mousePressEvent (QMouseEvent * me) override protected
Respond to a mouse press on the trackContentWidget.
Parameters
me the mouse press event to respond to
Definition at line 574 of file TrackContentWidget.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), lmms::Track::createClip(), lmms::gui::getGUI(), getPosition(), lmms::gui::SongEditor::getSnapSize(), getTrack(), i, lmms::gui::SongEditorWindow::m_editor, m_trackView, pos, lmms::TimePos::quantize(), lmms::gui::SongEditor::Select, lmms::gui::SongEditor::setEditMode(), and lmms::gui::GuiApplication::songEditor().
mouseReleaseEvent()
void lmms::gui::TrackContentWidget::mouseReleaseEvent (QMouseEvent * me) override protected
Definition at line 610 of file TrackContentWidget.cpp.
References lmms::gui::getGUI(), lmms::gui::GuiApplication::songEditor(), and lmms::gui::SongEditorWindow::syncEditMode().
nodeName()
QString lmms::gui::TrackContentWidget::nodeName () const inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 138 of file TrackContentWidget.h.
paintEvent()
void lmms::gui::TrackContentWidget::paintEvent (QPaintEvent * pe) override protected
Repaint the trackContentWidget on command.
Parameters
pe the Paint Event to respond to
Definition at line 623 of file TrackContentWidget.cpp.
References lmms::gui::TrackContainerView::currentPosition(), lmms::gui::getGUI(), lmms::TimePos::getTicks(), m_background, m_trackView, lmms::gui::TrackContainerView::pixelsPerBar(), and lmms::TimePos::ticksPerBar().
pasteSelection() [1/2]
bool lmms::gui::TrackContentWidget::pasteSelection (TimePos clipPos, const QMimeData * md, bool skipSafetyCheck = false)
Definition at line 453 of file TrackContentWidget.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), canPasteSelection(), lmms::DataFile::content(), lmms::gui::getGUI(), lmms::gui::SongEditor::getSnapSize(), lmms::TimePos::getTicks(), getTrack(), i, lmms::gui::SongEditorWindow::m_editor, m_trackView, lmms::Clip::movePosition(), pos, lmms::AutomationClip::resolveAllIDs(), lmms::JournallingObject::restoreState(), lmms::Clip::selectViewOnCreate(), lmms::gui::GuiApplication::songEditor(), lmms::TimePos::ticksPerBar(), lmms::Track::trackContainer(), and lmms::TrackContainer::tracks().
pasteSelection() [2/2]
bool lmms::gui::TrackContentWidget::pasteSelection (TimePos clipPos, QDropEvent * de)
Pastes a selection of Clips onto the track.
Parameters
clipPos the position of the Clip slot being pasted on
de the DropEvent generated
Definition at line 439 of file TrackContentWidget.cpp.
References canPasteSelection(), and pasteSelection().
Referenced by contextMenuAction(), lmms::gui::ClipView::dropEvent(), dropEvent(), lmms::gui::ClipView::paste(), and pasteSelection().
removeClipView() [1/2]
void lmms::gui::TrackContentWidget::removeClipView (ClipView * clipv)
Removes the given ClipView from this widget.
Removes the given ClipView from our list of views.
Parameters
clipv The ClipView to add.
Definition at line 194 of file TrackContentWidget.cpp.
References lmms::Engine::getSong(), m_clipViews, and lmms::Song::setModified().
Referenced by ~TrackContentWidget(), and removeClipView().
removeClipView() [2/2]
void lmms::gui::TrackContentWidget::removeClipView (int clipNum) inline
Definition at line 72 of file TrackContentWidget.h.
References m_clipViews, and removeClipView().
resizeEvent()
void lmms::gui::TrackContentWidget::resizeEvent (QResizeEvent * resizeEvent) override protected
Updates the background tile pixmap on size changes.
Parameters
resizeEvent the resize event to pass to base class
Definition at line 644 of file TrackContentWidget.cpp.
References resizeEvent(), and updateBackground().
Referenced by resizeEvent().
saveSettings()
void lmms::gui::TrackContentWidget::saveSettings (QDomDocument & doc, QDomElement & element) inline override protected virtual
Implements lmms::SerializingObject.
Definition at line 143 of file TrackContentWidget.h.
setCoarseGridColor()
void lmms::gui::TrackContentWidget::setCoarseGridColor (const QBrush & c)
CSS theming qproperty access method.
Definition at line 775 of file TrackContentWidget.cpp.
References m_coarseGridColor.
setCoarseGridWidth()
void lmms::gui::TrackContentWidget::setCoarseGridWidth (int c)
CSS theming qproperty access method.
Definition at line 791 of file TrackContentWidget.cpp.
References m_coarseGridWidth.
setDarkerColor()
void lmms::gui::TrackContentWidget::setDarkerColor (const QBrush & c)
CSS theming qproperty access method.
Definition at line 767 of file TrackContentWidget.cpp.
References m_darkerColor.
setEmbossColor()
void lmms::gui::TrackContentWidget::setEmbossColor (const QBrush & c)
CSS theming qproperty access method.
Definition at line 787 of file TrackContentWidget.cpp.
References m_embossColor.
setEmbossOffset()
void lmms::gui::TrackContentWidget::setEmbossOffset (int c)
CSS theming qproperty access method.
Definition at line 807 of file TrackContentWidget.cpp.
References m_embossOffset.
setEmbossWidth()
void lmms::gui::TrackContentWidget::setEmbossWidth (int c)
CSS theming qproperty access method.
Definition at line 803 of file TrackContentWidget.cpp.
References m_embossWidth.
setFineGridColor()
void lmms::gui::TrackContentWidget::setFineGridColor (const QBrush & c)
CSS theming qproperty access method.
Definition at line 779 of file TrackContentWidget.cpp.
References m_fineGridColor.
setFineGridWidth()
void lmms::gui::TrackContentWidget::setFineGridWidth (int c)
CSS theming qproperty access method.
Definition at line 795 of file TrackContentWidget.cpp.
References m_fineGridWidth.
setHorizontalColor()
void lmms::gui::TrackContentWidget::setHorizontalColor (const QBrush & c)
CSS theming qproperty access method.
Definition at line 783 of file TrackContentWidget.cpp.
References m_horizontalColor.
setHorizontalWidth()
void lmms::gui::TrackContentWidget::setHorizontalWidth (int c)
CSS theming qproperty access method.
Definition at line 799 of file TrackContentWidget.cpp.
References m_horizontalWidth.
setLighterColor()
void lmms::gui::TrackContentWidget::setLighterColor (const QBrush & c)
CSS theming qproperty access method.
Definition at line 771 of file TrackContentWidget.cpp.
References m_lighterColor.
update
void lmms::gui::TrackContentWidget::update () slot
Update ourselves by updating all the ClipViews attached.
Definition at line 212 of file TrackContentWidget.cpp.
References m_clipViews.
Referenced by updateBackground().
updateBackground
void lmms::gui::TrackContentWidget::updateBackground () slot
Updates the background tile pixmap.
Definition at line 101 of file TrackContentWidget.cpp.
References lmms::gui::BARS_PER_GROUP, coarseGridColor, coarseGridWidth, darkerColor, embossColor, embossOffset, embossWidth, fineGridColor, fineGridWidth, lmms::gui::getGUI(), lmms::gui::SongEditor::getSnapSize(), horizontalColor, horizontalWidth, lighterColor, m_background, lmms::gui::SongEditorWindow::m_editor, m_trackView, lmms::gui::MIN_PIXELS_BETWEEN_LINES, lmms::gui::TrackContainerView::pixelsPerBar(), lmms::gui::GuiApplication::songEditor(), and update().
Referenced by TrackContentWidget(), changePosition(), and resizeEvent().
Member Data Documentation
m_background
QPixmap lmms::gui::TrackContentWidget::m_background private
Definition at line 164 of file TrackContentWidget.h.
Referenced by paintEvent(), and updateBackground().
m_clipViews
clipViewVector lmms::gui::TrackContentWidget::m_clipViews private
Definition at line 162 of file TrackContentWidget.h.
Referenced by addClipView(), changePosition(), removeClipView(), removeClipView(), and update().
m_coarseGridColor
QBrush lmms::gui::TrackContentWidget::m_coarseGridColor private
Definition at line 169 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), coarseGridColor(), and setCoarseGridColor().
m_coarseGridWidth
int lmms::gui::TrackContentWidget::m_coarseGridWidth private
Definition at line 174 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), coarseGridWidth(), and setCoarseGridWidth().
m_darkerColor
QBrush lmms::gui::TrackContentWidget::m_darkerColor private
Definition at line 167 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), darkerColor(), and setDarkerColor().
m_embossColor
QBrush lmms::gui::TrackContentWidget::m_embossColor private
Definition at line 172 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), embossColor(), and setEmbossColor().
m_embossOffset
int lmms::gui::TrackContentWidget::m_embossOffset private
Definition at line 179 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), embossOffset(), and setEmbossOffset().
m_embossWidth
int lmms::gui::TrackContentWidget::m_embossWidth private
Definition at line 177 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), embossWidth(), and setEmbossWidth().
m_fineGridColor
QBrush lmms::gui::TrackContentWidget::m_fineGridColor private
Definition at line 170 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), fineGridColor(), and setFineGridColor().
m_fineGridWidth
int lmms::gui::TrackContentWidget::m_fineGridWidth private
Definition at line 175 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), fineGridWidth(), and setFineGridWidth().
m_horizontalColor
QBrush lmms::gui::TrackContentWidget::m_horizontalColor private
Definition at line 171 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), horizontalColor(), and setHorizontalColor().
m_horizontalWidth
int lmms::gui::TrackContentWidget::m_horizontalWidth private
Definition at line 176 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), horizontalWidth(), and setHorizontalWidth().
m_lighterColor
QBrush lmms::gui::TrackContentWidget::m_lighterColor private
Definition at line 168 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), lighterColor(), and setLighterColor().
m_trackView
TrackView* lmms::gui::TrackContentWidget::m_trackView private
Definition at line 159 of file TrackContentWidget.h.
Referenced by TrackContentWidget(), canPasteSelection(), changePosition(), endPosition(), getPosition(), getTrack(), mousePressEvent(), paintEvent(), pasteSelection(), and updateBackground().
Property Documentation
coarseGridColor
QBrush lmms::gui::TrackContentWidget::coarseGridColor read write
Definition at line 54 of file TrackContentWidget.h.
Referenced by updateBackground().
coarseGridWidth
int lmms::gui::TrackContentWidget::coarseGridWidth read write
Definition at line 59 of file TrackContentWidget.h.
Referenced by updateBackground().
darkerColor
QBrush lmms::gui::TrackContentWidget::darkerColor read write
Definition at line 52 of file TrackContentWidget.h.
Referenced by updateBackground().
embossColor
QBrush lmms::gui::TrackContentWidget::embossColor read write
Definition at line 57 of file TrackContentWidget.h.
Referenced by updateBackground().
embossOffset
int lmms::gui::TrackContentWidget::embossOffset read write
Definition at line 64 of file TrackContentWidget.h.
Referenced by updateBackground().
embossWidth
int lmms::gui::TrackContentWidget::embossWidth read write
Definition at line 62 of file TrackContentWidget.h.
Referenced by updateBackground().
fineGridColor
QBrush lmms::gui::TrackContentWidget::fineGridColor read write
Definition at line 55 of file TrackContentWidget.h.
Referenced by updateBackground().
fineGridWidth
int lmms::gui::TrackContentWidget::fineGridWidth read write
Definition at line 60 of file TrackContentWidget.h.
Referenced by updateBackground().
horizontalColor
QBrush lmms::gui::TrackContentWidget::horizontalColor read write
Definition at line 56 of file TrackContentWidget.h.
Referenced by updateBackground().
horizontalWidth
int lmms::gui::TrackContentWidget::horizontalWidth read write
Definition at line 61 of file TrackContentWidget.h.
Referenced by updateBackground().
lighterColor
QBrush lmms::gui::TrackContentWidget::lighterColor read write
Definition at line 53 of file TrackContentWidget.h.
Referenced by updateBackground().
The documentation for this class was generated from the following files:
include/TrackContentWidget.h
src/gui/tracks/TrackContentWidget.cpp