LMMS: lmms::BandLimitedWave Class Reference
lmms::BandLimitedWave Class Reference
#include <BandLimitedWave.h>
Public Types
enum class Waveform {
BLSaw ,
BLSquare ,
BLTriangle ,
BLMoog ,
Count
}
Public Member Functions
BandLimitedWave ()=default
virtual ~BandLimitedWave ()=default
Static Public Member Functions
static float freqToLen (float f)
This method converts frequency to wavelength.
static float freqToLen (float f, sample_rate_t sr)
This method converts frequency to wavelength, but you can use any custom sample rate with it.
static void generateWaves ()
static sample_t oscillate (float _ph, float _wavelen, Waveform _wave)
This method provides interpolated samples of bandlimited waveforms.
static float pdToLen (float pd)
This method converts phase delta to wavelength.
Static Public Attributes
static constexpr auto NumWaveforms = static_cast<std::size_t>(Waveform::Count)
static std::array< WaveMipMap, NumWaveforms > s_waveforms = { }
static bool s_wavesGenerated = false
static QString s_wavetableDir = ""
Detailed Description
Definition at line 89 of file BandLimitedWave.h.
Member Enumeration Documentation
Waveform
enum class lmms::BandLimitedWave::Waveform strong
Enumerator
BLSaw
BLSquare
BLTriangle
BLMoog
Count
Definition at line 92 of file BandLimitedWave.h.
Constructor & Destructor Documentation
BandLimitedWave()
lmms::BandLimitedWave::BandLimitedWave () default
~BandLimitedWave()
virtual lmms::BandLimitedWave::~BandLimitedWave () virtual default
Member Function Documentation
freqToLen() [1/2]
float lmms::BandLimitedWave::freqToLen (float f) inline static
This method converts frequency to wavelength.
The oscillate function takes wavelength as argument so use this to convert your note frequency to wavelength before using it.
Definition at line 108 of file BandLimitedWave.h.
References lmms::Engine::audioEngine(), and freqToLen().
Referenced by freqToLen().
freqToLen() [2/2]
float lmms::BandLimitedWave::freqToLen (float f, sample_rate_t sr) inline static
This method converts frequency to wavelength, but you can use any custom sample rate with it.
Definition at line 115 of file BandLimitedWave.h.
References sr.
generateWaves()
void lmms::BandLimitedWave::generateWaves () static
Definition at line 65 of file BandLimitedWave.cpp.
References BLMoog, BLSaw, BLSquare, BLTriangle, i, max, lmms::MAXTBL, s_waveforms, s_wavesGenerated, s_wavetableDir, and lmms::TLENS.
Referenced by lmms::Engine::init().
oscillate()
sample_t lmms::BandLimitedWave::oscillate (float _ph, float _wavelen, Waveform _wave) inline static
This method provides interpolated samples of bandlimited waveforms.
Parameters
_ph The phase of the sample.
_wavelen The wavelength (length of one cycle, ie. the inverse of frequency) of the wanted oscillation, measured in sample frames
_wave The wanted waveform. Options currently are saw, triangle, square and moog saw.
Definition at line 131 of file BandLimitedWave.h.
References lmms::fraction(), lmms::optimal4pInterpolate(), s_waveforms, sr, and lmms::TLENS.
pdToLen()
float lmms::BandLimitedWave::pdToLen (float pd) inline static
This method converts phase delta to wavelength.
It assumes a phase scale of 0 to 1.
Definition at line 121 of file BandLimitedWave.h.
Member Data Documentation
NumWaveforms
auto lmms::BandLimitedWave::NumWaveforms = static_cast<std::size_t>(Waveform::Count) static constexpr
Definition at line 100 of file BandLimitedWave.h.
s_waveforms
std::array< WaveMipMap, BandLimitedWave::NumWaveforms > lmms::BandLimitedWave::s_waveforms = { } static
Definition at line 172 of file BandLimitedWave.h.
Referenced by generateWaves(), and oscillate().
s_wavesGenerated
bool lmms::BandLimitedWave::s_wavesGenerated = false static
Definition at line 170 of file BandLimitedWave.h.
Referenced by generateWaves().
s_wavetableDir
QString lmms::BandLimitedWave::s_wavetableDir = "" static
Definition at line 174 of file BandLimitedWave.h.
Referenced by generateWaves().
The documentation for this class was generated from the following files:
include/BandLimitedWave.h
src/core/BandLimitedWave.cpp