LMMS: hiir::PhaseHalfPiF64Sse2< NC > Class Template Reference
hiir::PhaseHalfPiF64Sse2< NC > Class Template Reference
#include <PhaseHalfPiF64Sse2.h>
Public Types
typedef double DataType
Public Member Functions
PhaseHalfPiF64Sse2 () noexcept
PhaseHalfPiF64Sse2 (const PhaseHalfPiF64Sse2< NC > &other)=default
PhaseHalfPiF64Sse2 (PhaseHalfPiF64Sse2< NC > &&other)=default
void clear_buffers () noexcept
PhaseHalfPiF64Sse2< NC > & operator= (const PhaseHalfPiF64Sse2< NC > &other)=default
PhaseHalfPiF64Sse2< NC > & operator= (PhaseHalfPiF64Sse2< NC > &&other)=default
void process_block (double out_0_ptr[], double out_1_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (double &out_0, double &out_1, double input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Sse2, _nbr_stages+1 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const PhaseHalfPiF64Sse2< NC > &other) const =delete
bool operator== (const PhaseHalfPiF64Sse2< NC > &other) const =delete
Private Attributes
FilterBiPhase _bifilter
int _phase
DataType _prev
Static Private Attributes
static constexpr int _nbr_phases = 2
static constexpr int _nbr_stages
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::PhaseHalfPiF64Sse2< NC >
Definition at line 49 of file PhaseHalfPiF64Sse2.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::PhaseHalfPiF64Sse2< NC >::DataType
Definition at line 58 of file PhaseHalfPiF64Sse2.h.
Filter
template<int NC> typedef std::array<StageDataF64Sse2, _nbr_stages + 1> hiir::PhaseHalfPiF64Sse2< NC >::Filter private
Definition at line 98 of file PhaseHalfPiF64Sse2.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::PhaseHalfPiF64Sse2< NC >::FilterBiPhase private
Definition at line 100 of file PhaseHalfPiF64Sse2.h.
Constructor & Destructor Documentation
PhaseHalfPiF64Sse2() [1/3]
template<int NC> hiir::PhaseHalfPiF64Sse2< NC >::PhaseHalfPiF64Sse2 () noexcept
Definition at line 57 of file PhaseHalfPiF64Sse2.hpp.
References _bifilter, _nbr_phases, _nbr_stages, _phase, _prev, clear_buffers(), i, and NBR_COEFS.
Referenced by PhaseHalfPiF64Sse2(), PhaseHalfPiF64Sse2(), operator!=(), operator=(), operator=(), and operator==().
PhaseHalfPiF64Sse2() [2/3]
template<int NC> hiir::PhaseHalfPiF64Sse2< NC >::PhaseHalfPiF64Sse2 (const PhaseHalfPiF64Sse2< NC > & other) default
References PhaseHalfPiF64Sse2().
PhaseHalfPiF64Sse2() [3/3]
template<int NC> hiir::PhaseHalfPiF64Sse2< NC >::PhaseHalfPiF64Sse2 (PhaseHalfPiF64Sse2< NC > && other) default
References PhaseHalfPiF64Sse2().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::PhaseHalfPiF64Sse2< NC >::clear_buffers () noexcept
Definition at line 222 of file PhaseHalfPiF64Sse2.hpp.
References _bifilter, _nbr_phases, _nbr_stages, and i.
Referenced by PhaseHalfPiF64Sse2(), and operator=().
operator!=()
template<int NC> bool hiir::PhaseHalfPiF64Sse2< NC >::operator!= (const PhaseHalfPiF64Sse2< NC > & other) const private delete
References PhaseHalfPiF64Sse2().
operator=() [1/2]
template<int NC> PhaseHalfPiF64Sse2< NC > & hiir::PhaseHalfPiF64Sse2< NC >::operator= (const PhaseHalfPiF64Sse2< NC > & other) default
References PhaseHalfPiF64Sse2().
operator=() [2/2]
template<int NC> PhaseHalfPiF64Sse2< NC > & hiir::PhaseHalfPiF64Sse2< NC >::operator= (PhaseHalfPiF64Sse2< NC > && other) default
References PhaseHalfPiF64Sse2(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::PhaseHalfPiF64Sse2< NC >::operator== (const PhaseHalfPiF64Sse2< NC > & other) const private delete
References PhaseHalfPiF64Sse2().
process_block()
template<int NC> void hiir::PhaseHalfPiF64Sse2< NC >::process_block (double out_0_ptr[], double out_1_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 159 of file PhaseHalfPiF64Sse2.hpp.
References _bifilter, _nbr_phases, _phase, _prev, pos, process_sample(), and hiir::StageProcF64Sse2< CUR >::process_sample_neg().
Referenced by operator=().
process_sample()
template<int NC> void hiir::PhaseHalfPiF64Sse2< NC >::process_sample (double & out_0, double & out_1, double input) noexcept
Definition at line 126 of file PhaseHalfPiF64Sse2.hpp.
References _bifilter, _phase, _prev, and hiir::StageProcF64Sse2< CUR >::process_sample_neg().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::PhaseHalfPiF64Sse2< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 94 of file PhaseHalfPiF64Sse2.hpp.
References _bifilter, _nbr_phases, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
Member Data Documentation
_bifilter
template<int NC> FilterBiPhase hiir::PhaseHalfPiF64Sse2< NC >::_bifilter private
Definition at line 103 of file PhaseHalfPiF64Sse2.h.
Referenced by PhaseHalfPiF64Sse2(), clear_buffers(), process_block(), process_sample(), and set_coefs().
_delay
template<int NC> double hiir::PhaseHalfPiF64Sse2< NC >::_delay = 0 static constexpr
Definition at line 61 of file PhaseHalfPiF64Sse2.h.
_nbr_chn
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_nbr_chn = 1 static constexpr
Definition at line 59 of file PhaseHalfPiF64Sse2.h.
_nbr_phases
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_nbr_phases = 2 static constexpr private
Definition at line 95 of file PhaseHalfPiF64Sse2.h.
Referenced by PhaseHalfPiF64Sse2(), clear_buffers(), process_block(), and set_coefs().
_nbr_stages
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 93 of file PhaseHalfPiF64Sse2.h.
Referenced by PhaseHalfPiF64Sse2(), and clear_buffers().
_phase
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_phase private
Definition at line 105 of file PhaseHalfPiF64Sse2.h.
Referenced by PhaseHalfPiF64Sse2(), process_block(), and process_sample().
_prev
template<int NC> DataType hiir::PhaseHalfPiF64Sse2< NC >::_prev private
Definition at line 104 of file PhaseHalfPiF64Sse2.h.
Referenced by PhaseHalfPiF64Sse2(), process_block(), and process_sample().
_stage_width
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_stage_width = 2 static constexpr private
Definition at line 92 of file PhaseHalfPiF64Sse2.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::NBR_COEFS = NC static constexpr
Definition at line 60 of file PhaseHalfPiF64Sse2.h.
Referenced by PhaseHalfPiF64Sse2(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/PhaseHalfPiF64Sse2.h
src/3rdparty/hiir/hiir/PhaseHalfPiF64Sse2.hpp