LMMS: Jack::JackRestarterDriver Class Reference
Jack::JackRestarterDriver Class Reference
A restartable driver.
#include <JackTimedDriver.h>
Public Member Functions
JackRestarterDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackRestarterDriver ()
int RestartWait ()
Restart the wrapper thread.
void SetRestartDriver (JackDriver *driver)
Let the wrapper register itself.
Public Member Functions inherited from Jack::JackWaiterDriver
JackWaiterDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackWaiterDriver ()
virtual int ProcessNull ()
Public Member Functions inherited from Jack::JackTimedDriver
JackTimedDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackTimedDriver ()
bool IsFixedBufferSize ()
int Start ()
Public Member Functions inherited from Jack::JackAudioDriver
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int Attach ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Detach ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int SetBufferSize (jack_nframes_t buffer_size)
virtual int SetSampleRate (jack_nframes_t sample_rate)
virtual int Write ()
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual int Close ()
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
virtual int Read ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
virtual int Stop ()
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Attributes
JackDriver * fRestartDriver
The wrapper driver.
Additional Inherited Members
Protected Member Functions inherited from Jack::JackTimedDriver
int CurrentCycle (jack_time_t cur_time)
int FirstCycle (jack_time_t cur_time)
void ProcessWait ()
Protected Member Functions inherited from Jack::JackAudioDriver
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
virtual void UpdateLatencies ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes inherited from Jack::JackTimedDriver
jack_time_t fAnchorTimeUsec
int fCycleCount
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
A restartable driver.
When wrapped into a JackWaitCallbackDriver, this driver can restart the wrapper thread which will wait again for the Initialize method to return.
Definition at line 84 of file JackTimedDriver.h.
Constructor & Destructor Documentation
JackRestarterDriver()
Jack::JackRestarterDriver::JackRestarterDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table) inline
Definition at line 93 of file JackTimedDriver.h.
References Jack::JackWaiterDriver::JackWaiterDriver(), and fRestartDriver.
Referenced by Jack::JackProxyDriver::JackProxyDriver().
~JackRestarterDriver()
virtual Jack::JackRestarterDriver::~JackRestarterDriver () inline virtual
Definition at line 96 of file JackTimedDriver.h.
Member Function Documentation
RestartWait()
int Jack::JackRestarterDriver::RestartWait ()
Restart the wrapper thread.
Definition at line 94 of file JackTimedDriver.cpp.
References fRestartDriver, and jack_error.
Referenced by Jack::JackProxyDriver::shutdown_callback().
SetRestartDriver()
void Jack::JackRestarterDriver::SetRestartDriver (JackDriver * driver)
Let the wrapper register itself.
Definition at line 89 of file JackTimedDriver.cpp.
References driver, and fRestartDriver.
Member Data Documentation
fRestartDriver
JackDriver* Jack::JackRestarterDriver::fRestartDriver private
The wrapper driver.
Definition at line 89 of file JackTimedDriver.h.
Referenced by JackRestarterDriver(), RestartWait(), and SetRestartDriver().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackTimedDriver.h
src/3rdparty/jack2/common/JackTimedDriver.cpp