LMMS: lmms::MixHelpers Namespace Reference
lmms::MixHelpers Namespace Reference
Classes
struct AddMultipliedOp
struct AddMultipliedStereoOp
struct AddOp
struct AddSanitizedMultipliedOp
struct AddSwappedMultipliedOp
struct MultiplyAndAddMultipliedOp
Functions
void add (SampleFrame *dst, const SampleFrame *src, int frames)
Add samples from src to dst.
void addMultiplied (SampleFrame *dst, const SampleFrame *src, float coeffSrc, int frames)
Add samples from src multiplied by coeffSrc to dst.
void addMultipliedByBuffer (SampleFrame *dst, const SampleFrame *src, float coeffSrc, ValueBuffer *coeffSrcBuf, int frames)
Add samples from src multiplied by coeffSrc and coeffSrcBuf to dst.
void addMultipliedByBuffers (SampleFrame *dst, const SampleFrame *src, ValueBuffer *coeffSrcBuf1, ValueBuffer *coeffSrcBuf2, int frames)
Add samples from src multiplied by coeffSrc and coeffSrcBuf to dst.
void addMultipliedStereo (SampleFrame *dst, const SampleFrame *src, float coeffSrcLeft, float coeffSrcRight, int frames)
Add samples from src multiplied by coeffSrcLeft/coeffSrcRight to dst.
void addSanitizedMultiplied (SampleFrame *dst, const SampleFrame *src, float coeffSrc, int frames)
Same as addMultiplied, but sanitize output (strip out infs/nans).
void addSanitizedMultipliedByBuffer (SampleFrame *dst, const SampleFrame *src, float coeffSrc, ValueBuffer *coeffSrcBuf, int frames)
Add samples from src multiplied by coeffSrc and coeffSrcBuf to dst - sanitized version.
void addSanitizedMultipliedByBuffers (SampleFrame *dst, const SampleFrame *src, ValueBuffer *coeffSrcBuf1, ValueBuffer *coeffSrcBuf2, int frames)
Add samples from src multiplied by coeffSrc and coeffSrcBuf to dst - sanitized version.
void addSwappedMultiplied (SampleFrame *dst, const SampleFrame *src, float coeffSrc, int frames)
Add samples from src multiplied by coeffSrc to dst, swap inputs.
bool isSilent (const SampleFrame *src, int frames)
void multiply (SampleFrame *dst, float coeff, int frames)
Multiply samples from dst by coeff.
void multiplyAndAddMultiplied (SampleFrame *dst, const SampleFrame *src, float coeffDst, float coeffSrc, int frames)
Multiply dst by coeffDst and add samples from src multiplied by coeffSrc.
void multiplyAndAddMultipliedJoined (SampleFrame *dst, const sample_t *srcLeft, const sample_t *srcRight, float coeffDst, float coeffSrc, int frames)
Multiply dst by coeffDst and add samples from srcLeft/srcRight multiplied by coeffSrc.
template<typename MIXOP>
static void run (SampleFrame *dst, const sample_t *srcLeft, const sample_t *srcRight, int frames, const MIXOP &OP)
Function for applying MIXOP on all sample frames - split source.
template<typename MIXOP>
static void run (SampleFrame *dst, const SampleFrame *src, int frames, const MIXOP &OP)
Function for applying MIXOP on all sample frames.
bool sanitize (SampleFrame *src, int frames)
Function for sanitizing a buffer of infs/nans - returns true if those are found.
void setNaNHandler (bool use)
bool useNaNHandler ()
Function Documentation
add()
void lmms::MixHelpers::add (SampleFrame * dst, const SampleFrame * src, int frames)
Add samples from src to dst.
Definition at line 135 of file MixHelpers.cpp.
References run().
Referenced by lmms::AudioBusHandle::doProcessing(), lmms::Mixer::mixToChannel(), and lmms::RingBuffer::writeAdding().
addMultiplied()
void lmms::MixHelpers::addMultiplied (SampleFrame * dst, const SampleFrame * src, float coeffSrc, int frames)
Add samples from src multiplied by coeffSrc to dst.
Definition at line 155 of file MixHelpers.cpp.
References run().
Referenced by addSanitizedMultiplied(), and lmms::RingBuffer::writeAddingMultiplied().
addMultipliedByBuffer()
void lmms::MixHelpers::addMultipliedByBuffer (SampleFrame * dst, const SampleFrame * src, float coeffSrc, ValueBuffer * coeffSrcBuf, int frames)
Add samples from src multiplied by coeffSrc and coeffSrcBuf to dst.
Definition at line 188 of file MixHelpers.cpp.
References lmms::ValueBuffer::values().
Referenced by addSanitizedMultipliedByBuffer().
addMultipliedByBuffers()
void lmms::MixHelpers::addMultipliedByBuffers (SampleFrame * dst, const SampleFrame * src, ValueBuffer * coeffSrcBuf1, ValueBuffer * coeffSrcBuf2, int frames)
Add samples from src multiplied by coeffSrc and coeffSrcBuf to dst.
Definition at line 197 of file MixHelpers.cpp.
References lmms::ValueBuffer::values().
Referenced by addSanitizedMultipliedByBuffers().
addMultipliedStereo()
void lmms::MixHelpers::addMultipliedStereo (SampleFrame * dst, const SampleFrame * src, float coeffSrcLeft, float coeffSrcRight, int frames)
Add samples from src multiplied by coeffSrcLeft/coeffSrcRight to dst.
Definition at line 289 of file MixHelpers.cpp.
References run().
addSanitizedMultiplied()
void lmms::MixHelpers::addSanitizedMultiplied (SampleFrame * dst, const SampleFrame * src, float coeffSrc, int frames)
Same as addMultiplied, but sanitize output (strip out infs/nans).
Definition at line 258 of file MixHelpers.cpp.
References addMultiplied(), run(), and useNaNHandler().
Referenced by lmms::MixerChannel::doProcessing(), and lmms::Mixer::masterMix().
addSanitizedMultipliedByBuffer()
void lmms::MixHelpers::addSanitizedMultipliedByBuffer (SampleFrame * dst, const SampleFrame * src, float coeffSrc, ValueBuffer * coeffSrcBuf, int frames)
Add samples from src multiplied by coeffSrc and coeffSrcBuf to dst - sanitized version.
Definition at line 207 of file MixHelpers.cpp.
References addMultipliedByBuffer(), useNaNHandler(), and lmms::ValueBuffer::values().
Referenced by lmms::MixerChannel::doProcessing().
addSanitizedMultipliedByBuffers()
void lmms::MixHelpers::addSanitizedMultipliedByBuffers (SampleFrame * dst, const SampleFrame * src, ValueBuffer * coeffSrcBuf1, ValueBuffer * coeffSrcBuf2, int frames)
Add samples from src multiplied by coeffSrc and coeffSrcBuf to dst - sanitized version.
Definition at line 223 of file MixHelpers.cpp.
References addMultipliedByBuffers(), useNaNHandler(), and lmms::ValueBuffer::values().
Referenced by lmms::MixerChannel::doProcessing().
addSwappedMultiplied()
void lmms::MixHelpers::addSwappedMultiplied (SampleFrame * dst, const SampleFrame * src, float coeffSrc, int frames)
Add samples from src multiplied by coeffSrc to dst, swap inputs.
Definition at line 182 of file MixHelpers.cpp.
References run().
Referenced by lmms::RingBuffer::writeSwappedAddingMultiplied().
isSilent()
bool lmms::MixHelpers::isSilent (const SampleFrame * src, int frames)
Definition at line 67 of file MixHelpers.cpp.
References i.
Referenced by lmms::AudioBusHandle::doProcessing(), and lmms::InstrumentTrack::processAudioBuffer().
multiply()
void lmms::MixHelpers::multiply (SampleFrame * dst, float coeff, int frames)
Multiply samples from dst by coeff.
Definition at line 174 of file MixHelpers.cpp.
References i.
Referenced by lmms::AudioEngine::renderStageMix().
multiplyAndAddMultiplied()
void lmms::MixHelpers::multiplyAndAddMultiplied (SampleFrame * dst, const SampleFrame * src, float coeffDst, float coeffSrc, int frames)
Multiply dst by coeffDst and add samples from src multiplied by coeffSrc.
Definition at line 317 of file MixHelpers.cpp.
References run().
multiplyAndAddMultipliedJoined()
void lmms::MixHelpers::multiplyAndAddMultipliedJoined (SampleFrame * dst, const sample_t * srcLeft, const sample_t * srcRight, float coeffDst, float coeffSrc, int frames)
Multiply dst by coeffDst and add samples from srcLeft/srcRight multiplied by coeffSrc.
Definition at line 324 of file MixHelpers.cpp.
References run().
run() [1/2]
template<typename MIXOP> void lmms::MixHelpers::run (SampleFrame * dst, const sample_t * srcLeft, const sample_t * srcRight, int frames, const MIXOP & OP) inline static
Function for applying MIXOP on all sample frames - split source.
Definition at line 56 of file MixHelpers.cpp.
References i.
run() [2/2]
template<typename MIXOP> void lmms::MixHelpers::run (SampleFrame * dst, const SampleFrame * src, int frames, const MIXOP & OP) inline static
Function for applying MIXOP on all sample frames.
Definition at line 46 of file MixHelpers.cpp.
References i.
Referenced by add(), addMultiplied(), addMultipliedStereo(), addSanitizedMultiplied(), addSwappedMultiplied(), multiplyAndAddMultiplied(), and multiplyAndAddMultipliedJoined().
sanitize()
bool lmms::MixHelpers::sanitize (SampleFrame * src, int frames)
Function for sanitizing a buffer of infs/nans - returns true if those are found.
Definition at line 93 of file MixHelpers.cpp.
References useNaNHandler(), and lmms::zeroSampleFrames().
Referenced by lmms::EffectChain::processAudioBuffer().
setNaNHandler()
void lmms::MixHelpers::setNaNHandler (bool use)
Definition at line 87 of file MixHelpers.cpp.
References s_NaNHandler.
Referenced by main().
useNaNHandler()
bool lmms::MixHelpers::useNaNHandler ()
Definition at line 82 of file MixHelpers.cpp.
References s_NaNHandler.
Referenced by addSanitizedMultiplied(), addSanitizedMultipliedByBuffer(), addSanitizedMultipliedByBuffers(), and sanitize().