LMMS: lmms::gui::MidiClipView Class Reference
lmms::gui::MidiClipView Class Reference
#include <MidiClipView.h>
Public Slots
lmms::MidiClip * getMidiClip ()
void update () override
Public Slots inherited from lmms::gui::ClipView
virtual bool close ()
Close a ClipView.
void randomizeColor ()
void remove ()
Removes a ClipView from its track view.
void resetColor ()
void selectColor ()
void update () override
Update a ClipView.
Public Slots inherited from lmms::gui::selectableObject
virtual void update ()
Public Member Functions
MidiClipView (MidiClip *clip, TrackView *parent)
~MidiClipView () override=default
QColor const & getMutedNoteBorderColor () const
QColor const & getMutedNoteFillColor () const
QColor const & getNoteBorderColor () const
QColor const & getNoteFillColor () const
void setMutedNoteBorderColor (QColor const &color)
void setMutedNoteFillColor (QColor const &color)
void setNoteBorderColor (QColor const &color)
void setNoteFillColor (QColor const &color)
Public Member Functions inherited from lmms::gui::ClipView
ClipView (Clip *clip, TrackView *tv)
Create a new ClipView.
~ClipView () override
Destroy a ClipView.
void copy (QVector< ClipView * > clipvs)
void cut (QVector< ClipView * > clipvs)
bool fixedClips ()
Does this ClipView have a fixed Clip?
QVector< ClipView * > getClickedClips ()
Clip * getClip ()
QColor getColorForDisplay (QColor)
TrackView * getTrackView ()
bool gradient () const
QColor markerColor () const
QColor mutedBackgroundColor () const
QColor mutedColor () const
CSS theming qproperty access method.
bool needsUpdate ()
void paste ()
QColor patternClipBackground () const
QColor selectedColor () const
void setGradient (const bool &b)
void setMarkerColor (const QColor &c)
void setMarkerEnabled (bool e)
void setMarkerPos (int x)
void setMutedBackgroundColor (const QColor &c)
void setMutedColor (const QColor &c)
CSS theming qproperty access method.
void setNeedsUpdate (bool b)
void setPatternClipBackground (const QColor &c)
void setSelectedColor (const QColor &c)
void setTextBackgroundColor (const QColor &c)
void setTextColor (const QColor &c)
void setTextShadowColor (const QColor &c)
QColor textBackgroundColor () const
QColor textColor () const
QColor textShadowColor () const
void toggleSelectedAutoResize ()
Public Member Functions inherited from lmms::gui::selectableObject
selectableObject (QWidget *_parent)
~selectableObject () override=default
bool isSelected () const
void setSelected (bool selected)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Static Public Member Functions
static void bulkClearNotesOutOfBounds (QVector< ClipView * > clipvs)
static bool canMergeSelection (QVector< ClipView * > clipvs)
static void mergeClips (QVector< ClipView * > clipvs)
Static Public Member Functions inherited from lmms::gui::ClipView
static void remove (QVector< ClipView * > clipvs)
static void toggleMute (QVector< ClipView * > clipvs)
Protected Slots
void changeName ()
void clearNotesOutOfBounds ()
void openInPianoRoll ()
void resetName ()
void setGhostInAutomationEditor ()
void setGhostInPianoRoll ()
void transposeSelection ()
Protected Slots inherited from lmms::gui::ClipView
void updateLength ()
Updates a ClipView's length.
void updatePosition ()
Updates a ClipView's position.
Protected Member Functions
void constructContextMenu (QMenu *) override
void mouseDoubleClickEvent (QMouseEvent *_me) override
void mousePressEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *pe) override
void wheelEvent (QWheelEvent *_we) override
Protected Member Functions inherited from lmms::gui::ClipView
void contextMenuAction (ContextMenuAction action)
void contextMenuEvent (QContextMenuEvent *cme) override
Set up the context menu for this ClipView.
DataFile createClipDataFiles (const QVector< ClipView * > &clips) const
Create a DataFile suitable for copying multiple clips.
void dragEnterEvent (QDragEnterEvent *dee) override
Change the ClipView's display when something being dragged enters it.
void dropEvent (QDropEvent *de) override
Handle something being dropped on this ClipObjectView.
auto hasCustomColor () const -> bool
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse movement (drag) on this ClipView.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press on this ClipView.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release on this ClipView.
virtual void paintTextLabel (QString const &text, QPainter &painter)
float pixelsPerBar ()
How many pixels a bar takes for this ClipView.
TimePos quantizeSplitPos (TimePos)
void resizeEvent (QResizeEvent *re) override
bool unquantizedModHeld (QMouseEvent *me)
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Properties
QColor mutedNoteBorderColor
QColor mutedNoteFillColor
QColor noteBorderColor
QColor noteFillColor
Properties inherited from lmms::gui::ClipView
bool gradient
QColor markerColor
QColor mutedBackgroundColor
QColor mutedColor
QColor patternClipBackground
QColor selectedColor
QColor textBackgroundColor
QColor textColor
QColor textShadowColor
Private Member Functions
bool destructiveSplitClip (const TimePos pos) override
Destructively split this Clip into two clips.
bool isResizableBeforeStart () override
Returns whether the user can left-resize this clip so that the start of the clip bounds is before the start of the clip content.
Private Attributes
MidiClip * m_clip
bool m_legacySEPattern
QColor m_mutedNoteBorderColor
QColor m_mutedNoteFillColor
QColor m_noteBorderColor
QColor m_noteFillColor
QPixmap m_paintPixmap
QStaticText m_staticTextName
QPixmap m_stepBtnHighlight = embed::getIconPixmap("step_btn_highlight")
QPixmap m_stepBtnOff = embed::getIconPixmap("step_btn_off")
QPixmap m_stepBtnOffLight = embed::getIconPixmap("step_btn_off_light")
QPixmap m_stepBtnOn0 = embed::getIconPixmap("step_btn_on_0")
QPixmap m_stepBtnOn200 = embed::getIconPixmap("step_btn_on_200")
Additional Inherited Members
Static Public Attributes inherited from lmms::gui::ClipView
static const int BORDER_WIDTH = 2
Protected Types inherited from lmms::gui::ClipView
enum class ContextMenuAction {
Remove ,
Cut ,
Copy ,
Paste ,
Mute
}
Protected Attributes inherited from lmms::gui::ClipView
TimePos m_initialClipEnd
TimePos m_initialClipPos
bool m_marker = false
int m_markerPos = 0
TrackView * m_trackView
Detailed Description
Definition at line 41 of file MidiClipView.h.
Constructor & Destructor Documentation
MidiClipView()
lmms::gui::MidiClipView::MidiClipView (MidiClip * clip, TrackView * parent)
Definition at line 53 of file MidiClipView.cpp.
References lmms::gui::ClipView::ClipView(), lmms::gui::getGUI(), m_clip, m_legacySEPattern, m_mutedNoteBorderColor, m_mutedNoteFillColor, m_noteBorderColor, m_noteFillColor, m_paintPixmap, and update().
Referenced by bulkClearNotesOutOfBounds(), and mergeClips().
~MidiClipView()
lmms::gui::MidiClipView::~MidiClipView () override default
Member Function Documentation
bulkClearNotesOutOfBounds()
void lmms::gui::MidiClipView::bulkClearNotesOutOfBounds (QVector< ClipView * > clipvs) static
Definition at line 404 of file MidiClipView.cpp.
References MidiClipView(), lmms::gui::getGUI(), lmms::Engine::getSong(), lmms::Song::setModified(), and lmms::gui::GuiApplication::songEditor().
Referenced by constructContextMenu().
canMergeSelection()
bool lmms::gui::MidiClipView::canMergeSelection (QVector< ClipView * > clipvs) static
Definition at line 259 of file MidiClipView.cpp.
References lmms::gui::ClipView::getTrackView().
Referenced by constructContextMenu().
changeName
void lmms::gui::MidiClipView::changeName () protected slot
Definition at line 128 of file MidiClipView.cpp.
References m_clip.
Referenced by constructContextMenu().
clearNotesOutOfBounds
void lmms::gui::MidiClipView::clearNotesOutOfBounds () protected slot
Definition at line 372 of file MidiClipView.cpp.
References lmms::Note::endPos(), m_clip, lmms::Note::pos(), lmms::gui::ClipView::remove(), lmms::Note::setLength(), and lmms::Note::setPos().
constructContextMenu()
void lmms::gui::MidiClipView::constructContextMenu (QMenu * _cm) override protected virtual
Reimplemented from lmms::gui::ClipView.
Definition at line 195 of file MidiClipView.cpp.
References lmms::MidiClip::BeatClip, bulkClearNotesOutOfBounds(), canMergeSelection(), changeName(), lmms::gui::ClipView::getClickedClips(), lmms::embed::getIconPixmap(), m_clip, mergeClips(), openInPianoRoll(), resetName(), setGhostInAutomationEditor(), setGhostInPianoRoll(), and transposeSelection().
destructiveSplitClip()
bool lmms::gui::MidiClipView::destructiveSplitClip (const TimePos pos) override private virtual
Destructively split this Clip into two clips.
If the clip type does not implement this feature, it will default to normal splitting.
Parameters
pos the position of the split, relative to the start of the clip
Returns
true if the clip could be split
Reimplemented from lmms::gui::ClipView.
Definition at line 874 of file MidiClipView.cpp.
References lmms::Note::endPos(), m_clip, lmms::gui::ClipView::m_initialClipEnd, lmms::gui::ClipView::m_initialClipPos, lmms::Note::pos(), pos, lmms::gui::ClipView::remove(), lmms::Note::setLength(), and lmms::Note::setPos().
getMidiClip
MidiClip * lmms::gui::MidiClipView::getMidiClip () slot
Definition at line 74 of file MidiClipView.cpp.
References m_clip.
getMutedNoteBorderColor()
QColor const & lmms::gui::MidiClipView::getMutedNoteBorderColor () const inline
Definition at line 63 of file MidiClipView.h.
References m_mutedNoteBorderColor.
Referenced by paintEvent().
getMutedNoteFillColor()
QColor const & lmms::gui::MidiClipView::getMutedNoteFillColor () const inline
Definition at line 60 of file MidiClipView.h.
References m_mutedNoteFillColor.
Referenced by paintEvent().
getNoteBorderColor()
QColor const & lmms::gui::MidiClipView::getNoteBorderColor () const inline
Definition at line 57 of file MidiClipView.h.
References m_noteBorderColor.
Referenced by paintEvent().
getNoteFillColor()
QColor const & lmms::gui::MidiClipView::getNoteFillColor () const inline
Definition at line 54 of file MidiClipView.h.
References getNoteFillColor(), and m_noteFillColor.
Referenced by getNoteFillColor(), and paintEvent().
isResizableBeforeStart()
bool lmms::gui::MidiClipView::isResizableBeforeStart () inline override private virtual
Returns whether the user can left-resize this clip so that the start of the clip bounds is before the start of the clip content.
Reimplemented from lmms::gui::ClipView.
Definition at line 114 of file MidiClipView.h.
mergeClips()
void lmms::gui::MidiClipView::mergeClips (QVector< ClipView * > clipvs) static
Definition at line 275 of file MidiClipView.cpp.
References lmms::gui::ClipView::ClipView(), MidiClipView(), lmms::JournallingObject::addJournalCheckPoint(), lmms::gui::getGUI(), lmms::Engine::getSong(), lmms::gui::ClipView::getTrackView(), lmms::JournallingObject::saveJournallingState(), lmms::Note::setLength(), lmms::Song::setModified(), lmms::Note::setPos(), and lmms::gui::GuiApplication::songEditor().
Referenced by constructContextMenu().
mouseDoubleClickEvent()
void lmms::gui::MidiClipView::mouseDoubleClickEvent (QMouseEvent * _me) override protected
Definition at line 476 of file MidiClipView.cpp.
References lmms::gui::ClipView::fixedClips(), m_clip, lmms::gui::ClipView::m_trackView, lmms::MidiClip::MelodyClip, and openInPianoRoll().
mousePressEvent()
void lmms::gui::MidiClipView::mousePressEvent (QMouseEvent * _me) override protected
Definition at line 422 of file MidiClipView.cpp.
References lmms::MidiClip::BeatClip, lmms::gui::BeatStepButtonOffset, lmms::gui::ClipView::BORDER_WIDTH, lmms::gui::ClipView::fixedClips(), lmms::gui::getGUI(), lmms::Engine::getSong(), m_clip, m_legacySEPattern, m_stepBtnOff, lmms::gui::ClipView::mousePressEvent(), lmms::gui::GuiApplication::pianoRoll(), lmms::gui::ClipView::pixelsPerBar(), lmms::Song::setModified(), and update().
openInPianoRoll
void lmms::gui::MidiClipView::openInPianoRoll () protected slot
Definition at line 92 of file MidiClipView.cpp.
References lmms::gui::getGUI(), m_clip, lmms::gui::GuiApplication::pianoRoll(), and lmms::gui::PianoRollWindow::setCurrentMidiClip().
Referenced by constructContextMenu(), and mouseDoubleClickEvent().
paintEvent()
void lmms::gui::MidiClipView::paintEvent (QPaintEvent * pe) override protected
Definition at line 552 of file MidiClipView.cpp.
References lmms::MidiClip::BeatClip, lmms::gui::BeatStepButtonOffset, lmms::gui::ClipView::BORDER_WIDTH, lmms::gui::computeNoteRange(), lmms::gui::PianoRollWindow::currentMidiClip(), lmms::gui::ClipView::fixedClips(), lmms::gui::ClipView::getColorForDisplay(), lmms::gui::getGUI(), lmms::embed::getIconPixmap(), getMutedNoteBorderColor(), getMutedNoteFillColor(), getNoteBorderColor(), getNoteFillColor(), lmms::Song::getPlayPos(), lmms::Engine::getSong(), lmms::Note::getVolume(), lmms::gui::ClipView::gradient, lmms::gui::ClipView::hasCustomColor(), m_clip, m_legacySEPattern, lmms::gui::ClipView::m_marker, lmms::gui::ClipView::m_markerPos, m_paintPixmap, m_stepBtnHighlight, m_stepBtnOff, m_stepBtnOffLight, m_stepBtnOn0, m_stepBtnOn200, lmms::gui::ClipView::markerColor, lmms::MidiClip::MelodyClip, lmms::MINIMAL_TRACK_HEIGHT, lmms::gui::ClipView::mutedBackgroundColor, lmms::gui::ClipView::needsUpdate(), noteBorderColor, noteFillColor, lmms::gui::ClipView::paintTextLabel(), lmms::Song::Pattern, lmms::gui::ClipView::patternClipBackground, lmms::gui::GuiApplication::pianoRoll(), lmms::gui::ClipView::pixelsPerBar(), lmms::Song::playMode(), lmms::gui::ClipView::setNeedsUpdate(), lmms::TimePos::stepsPerBar(), and lmms::TimePos::ticksPerBar().
resetName
void lmms::gui::MidiClipView::resetName () protected slot
Definition at line 123 of file MidiClipView.cpp.
References m_clip.
Referenced by constructContextMenu().
setGhostInAutomationEditor
void lmms::gui::MidiClipView::setGhostInAutomationEditor () protected slot
Definition at line 114 of file MidiClipView.cpp.
References lmms::gui::GuiApplication::automationEditor(), lmms::gui::getGUI(), m_clip, and lmms::gui::AutomationEditorWindow::setGhostMidiClip().
Referenced by constructContextMenu().
setGhostInPianoRoll
void lmms::gui::MidiClipView::setGhostInPianoRoll () protected slot
Definition at line 105 of file MidiClipView.cpp.
References lmms::gui::getGUI(), m_clip, lmms::gui::GuiApplication::pianoRoll(), and lmms::gui::PianoRollWindow::setGhostMidiClip().
Referenced by constructContextMenu().
setMutedNoteBorderColor()
void lmms::gui::MidiClipView::setMutedNoteBorderColor (QColor const & color) inline
Definition at line 64 of file MidiClipView.h.
References m_mutedNoteBorderColor.
setMutedNoteFillColor()
void lmms::gui::MidiClipView::setMutedNoteFillColor (QColor const & color) inline
Definition at line 61 of file MidiClipView.h.
References m_mutedNoteFillColor.
setNoteBorderColor()
void lmms::gui::MidiClipView::setNoteBorderColor (QColor const & color) inline
Definition at line 58 of file MidiClipView.h.
References m_noteBorderColor.
setNoteFillColor()
void lmms::gui::MidiClipView::setNoteFillColor (QColor const & color) inline
Definition at line 55 of file MidiClipView.h.
References m_noteFillColor.
transposeSelection
void lmms::gui::MidiClipView::transposeSelection () protected slot
Definition at line 139 of file MidiClipView.cpp.
References lmms::gui::ClipView::ClipView(), lmms::boundsForNotes(), lmms::gui::ClipView::getClickedClips(), lmms::Engine::getSong(), lmms::NumKeys, and lmms::Song::setModified().
Referenced by constructContextMenu().
update
void lmms::gui::MidiClipView::update () override slot
Definition at line 82 of file MidiClipView.cpp.
References m_clip, and lmms::gui::ClipView::update().
Referenced by MidiClipView(), mousePressEvent(), and wheelEvent().
wheelEvent()
void lmms::gui::MidiClipView::wheelEvent (QWheelEvent * _we) override protected
Definition at line 494 of file MidiClipView.cpp.
References lmms::MidiClip::BeatClip, lmms::gui::ClipView::BORDER_WIDTH, lmms::gui::ClipView::fixedClips(), lmms::gui::getGUI(), lmms::Engine::getSong(), lmms::Note::getVolume(), m_clip, m_stepBtnOff, lmms::gui::GuiApplication::pianoRoll(), lmms::gui::ClipView::pixelsPerBar(), lmms::position(), lmms::Song::setModified(), lmms::Note::setVolume(), and update().
Member Data Documentation
m_clip
MidiClip* lmms::gui::MidiClipView::m_clip private
Definition at line 102 of file MidiClipView.h.
Referenced by MidiClipView(), changeName(), clearNotesOutOfBounds(), constructContextMenu(), destructiveSplitClip(), getMidiClip(), mouseDoubleClickEvent(), mousePressEvent(), openInPianoRoll(), paintEvent(), resetName(), setGhostInAutomationEditor(), setGhostInPianoRoll(), update(), and wheelEvent().
m_legacySEPattern
bool lmms::gui::MidiClipView::m_legacySEPattern private
Definition at line 112 of file MidiClipView.h.
Referenced by MidiClipView(), mousePressEvent(), and paintEvent().
m_mutedNoteBorderColor
QColor lmms::gui::MidiClipView::m_mutedNoteBorderColor private
Definition at line 108 of file MidiClipView.h.
Referenced by MidiClipView(), getMutedNoteBorderColor(), and setMutedNoteBorderColor().
m_mutedNoteFillColor
QColor lmms::gui::MidiClipView::m_mutedNoteFillColor private
Definition at line 107 of file MidiClipView.h.
Referenced by MidiClipView(), getMutedNoteFillColor(), and setMutedNoteFillColor().
m_noteBorderColor
QColor lmms::gui::MidiClipView::m_noteBorderColor private
Definition at line 106 of file MidiClipView.h.
Referenced by MidiClipView(), getNoteBorderColor(), and setNoteBorderColor().
m_noteFillColor
QColor lmms::gui::MidiClipView::m_noteFillColor private
Definition at line 105 of file MidiClipView.h.
Referenced by MidiClipView(), getNoteFillColor(), and setNoteFillColor().
m_paintPixmap
QPixmap lmms::gui::MidiClipView::m_paintPixmap private
Definition at line 103 of file MidiClipView.h.
Referenced by MidiClipView(), and paintEvent().
m_staticTextName
QStaticText lmms::gui::MidiClipView::m_staticTextName private
Definition at line 110 of file MidiClipView.h.
m_stepBtnHighlight
QPixmap lmms::gui::MidiClipView::m_stepBtnHighlight = embed::getIconPixmap("step_btn_highlight") private
Definition at line 100 of file MidiClipView.h.
Referenced by paintEvent().
m_stepBtnOff
QPixmap lmms::gui::MidiClipView::m_stepBtnOff = embed::getIconPixmap("step_btn_off") private
Definition at line 98 of file MidiClipView.h.
Referenced by mousePressEvent(), paintEvent(), and wheelEvent().
m_stepBtnOffLight
QPixmap lmms::gui::MidiClipView::m_stepBtnOffLight = embed::getIconPixmap("step_btn_off_light") private
Definition at line 99 of file MidiClipView.h.
Referenced by paintEvent().
m_stepBtnOn0
QPixmap lmms::gui::MidiClipView::m_stepBtnOn0 = embed::getIconPixmap("step_btn_on_0") private
Definition at line 96 of file MidiClipView.h.
Referenced by paintEvent().
m_stepBtnOn200
QPixmap lmms::gui::MidiClipView::m_stepBtnOn200 = embed::getIconPixmap("step_btn_on_200") private
Definition at line 97 of file MidiClipView.h.
Referenced by paintEvent().
Property Documentation
mutedNoteBorderColor
QColor lmms::gui::MidiClipView::mutedNoteBorderColor read write
Definition at line 52 of file MidiClipView.h.
mutedNoteFillColor
QColor lmms::gui::MidiClipView::mutedNoteFillColor read write
Definition at line 51 of file MidiClipView.h.
noteBorderColor
QColor lmms::gui::MidiClipView::noteBorderColor read write
Definition at line 50 of file MidiClipView.h.
Referenced by paintEvent().
noteFillColor
QColor lmms::gui::MidiClipView::noteFillColor read write
Definition at line 49 of file MidiClipView.h.
Referenced by paintEvent().
The documentation for this class was generated from the following files:
include/MidiClipView.h
src/gui/clips/MidiClipView.cpp