LMMS: lmms::EffectChain Class Reference
lmms::EffectChain Class Reference
#include <EffectChain.h>
Signals
void aboutToClear ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
EffectChain (Model *_parent)
~EffectChain () override
void appendEffect (Effect *_effect)
void clear ()
void loadSettings (const QDomElement &_this) override
void moveDown (Effect *_effect)
void moveUp (Effect *_effect)
QString nodeName () const override
bool processAudioBuffer (SampleFrame *_buf, const fpp_t _frames, bool hasInputNoise)
void removeEffect (Effect *_effect)
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
void startRunning ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual void restoreState (const QDomElement &_this)
virtual QDomElement saveState (QDomDocument &_doc, QDomElement &_parent)
void setHook (SerializingObjectHook *_hook)
Private Types
using EffectList = std::vector<Effect*>
Private Attributes
EffectList m_effects
BoolModel m_enabledModel
Friends
class gui::EffectRackView
Detailed Description
Definition at line 47 of file EffectChain.h.
Member Typedef Documentation
EffectList
using lmms::EffectChain::EffectList = std::vector<Effect*> private
Definition at line 73 of file EffectChain.h.
Constructor & Destructor Documentation
EffectChain()
lmms::EffectChain::EffectChain (Model * _parent)
Definition at line 39 of file EffectChain.cpp.
References lmms::Model::Model(), lmms::SerializingObject::SerializingObject(), and m_enabledModel.
~EffectChain()
lmms::EffectChain::~EffectChain () override
Definition at line 49 of file EffectChain.cpp.
References clear().
Member Function Documentation
aboutToClear
void lmms::EffectChain::aboutToClear () signal
Referenced by clear().
appendEffect()
void lmms::EffectChain::appendEffect (Effect * _effect)
Definition at line 122 of file EffectChain.cpp.
References lmms::Engine::audioEngine(), lmms::Model::dataChanged(), lmms::AudioEngine::doneChangeInModel(), m_effects, m_enabledModel, and lmms::AudioEngine::requestChangeInModel().
Referenced by lmms::gui::EffectRackView::addEffect().
clear()
void lmms::EffectChain::clear ()
Definition at line 228 of file EffectChain.cpp.
References aboutToClear(), lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), m_effects, m_enabledModel, and lmms::AudioEngine::requestChangeInModel().
Referenced by ~EffectChain(), lmms::Mixer::clearChannel(), and loadSettings().
loadSettings()
void lmms::EffectChain::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 77 of file EffectChain.cpp.
References clear(), lmms::Model::dataChanged(), lmms::Effect::instantiate(), lmms::Effect::isOkay(), m_effects, m_enabledModel, lmms::Effect::nodeName(), lmms::Model::parentModel(), and lmms::JournallingObject::restoreState().
moveDown()
void lmms::EffectChain::moveDown (Effect * _effect)
Definition at line 161 of file EffectChain.cpp.
References m_effects.
moveUp()
void lmms::EffectChain::moveUp (Effect * _effect)
Definition at line 174 of file EffectChain.cpp.
References m_effects.
Referenced by lmms::gui::EffectRackView::moveUp().
nodeName()
QString lmms::EffectChain::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 57 of file EffectChain.h.
processAudioBuffer()
bool lmms::EffectChain::processAudioBuffer (SampleFrame * _buf, const fpp_t _frames, bool hasInputNoise)
Definition at line 187 of file EffectChain.cpp.
References m_effects, m_enabledModel, and lmms::MixHelpers::sanitize().
removeEffect()
void lmms::EffectChain::removeEffect (Effect * _effect)
Definition at line 136 of file EffectChain.cpp.
References lmms::Engine::audioEngine(), lmms::Model::dataChanged(), lmms::AudioEngine::doneChangeInModel(), m_effects, m_enabledModel, and lmms::AudioEngine::requestChangeInModel().
Referenced by lmms::gui::EffectRackView::deletePlugin().
saveSettings()
void lmms::EffectChain::saveSettings (QDomDocument & _doc, QDomElement & _parent) override virtual
Implements lmms::SerializingObject.
Definition at line 57 of file EffectChain.cpp.
References m_effects, and m_enabledModel.
startRunning()
void lmms::EffectChain::startRunning ()
Definition at line 212 of file EffectChain.cpp.
References m_effects, and m_enabledModel.
Friends And Related Symbol Documentation
gui::EffectRackView
friend class gui::EffectRackView friend
Definition at line 79 of file EffectChain.h.
Member Data Documentation
m_effects
EffectList lmms::EffectChain::m_effects private
Definition at line 74 of file EffectChain.h.
Referenced by appendEffect(), clear(), loadSettings(), moveDown(), moveUp(), processAudioBuffer(), removeEffect(), saveSettings(), and startRunning().
m_enabledModel
BoolModel lmms::EffectChain::m_enabledModel private
Definition at line 76 of file EffectChain.h.
Referenced by EffectChain(), appendEffect(), clear(), loadSettings(), processAudioBuffer(), removeEffect(), saveSettings(), and startRunning().
The documentation for this class was generated from the following files:
include/EffectChain.h
src/core/EffectChain.cpp