LMMS: hiir::StageProcNeonV2< CUR > Class Template Reference
hiir::StageProcNeonV2< CUR > Class Template Reference
#include <StageProcNeonV2.h>
Public Member Functions
hiir_FORCEINLINE void process_sample_neg_rec (float32x2_t &, StageDataNeonV2 *) noexcept
hiir_FORCEINLINE void process_sample_pos_rec (float32x2_t &, StageDataNeonV2 *) noexcept
Static Public Member Functions
static hiir_FORCEINLINE void process_sample_neg (float32x2_t &x, StageDataNeonV2 *stage_ptr) noexcept
static hiir_FORCEINLINE void process_sample_neg_rec (float32x2_t &x, StageDataNeonV2 *stage_ptr) noexcept
static hiir_FORCEINLINE void process_sample_pos (float32x2_t &x, StageDataNeonV2 *stage_ptr) noexcept
static hiir_FORCEINLINE void process_sample_pos_rec (float32x2_t &x, StageDataNeonV2 *stage_ptr) noexcept
Private Member Functions
StageProcNeonV2 ()=delete
StageProcNeonV2 (const StageProcNeonV2< CUR > &other)=delete
StageProcNeonV2 (StageProcNeonV2< CUR > &&other)=delete
~StageProcNeonV2 ()=delete
bool operator!= (const StageProcNeonV2< CUR > &other) const =delete
StageProcNeonV2 & operator= (const StageProcNeonV2< CUR > &other)=delete
StageProcNeonV2 & operator= (StageProcNeonV2< CUR > &&other)=delete
bool operator== (const StageProcNeonV2< CUR > &other) const =delete
Detailed Description
template<int CUR>
class hiir::StageProcNeonV2< CUR >
Definition at line 45 of file StageProcNeonV2.h.
Constructor & Destructor Documentation
StageProcNeonV2() [1/3]
template<int CUR> hiir::StageProcNeonV2< CUR >::StageProcNeonV2 () private delete
Referenced by ~StageProcNeonV2(), operator=(), process_sample_neg_rec(), and process_sample_pos_rec().
StageProcNeonV2() [2/3]
template<int CUR> hiir::StageProcNeonV2< CUR >::StageProcNeonV2 (const StageProcNeonV2< CUR > & other) private delete
StageProcNeonV2() [3/3]
template<int CUR> hiir::StageProcNeonV2< CUR >::StageProcNeonV2 (StageProcNeonV2< CUR > && other) private delete
~StageProcNeonV2()
template<int CUR> hiir::StageProcNeonV2< CUR >::~StageProcNeonV2 () private delete
References StageProcNeonV2().
Member Function Documentation
operator!=()
template<int CUR> bool hiir::StageProcNeonV2< CUR >::operator!= (const StageProcNeonV2< CUR > & other) const private delete
operator=() [1/2]
template<int CUR> StageProcNeonV2 & hiir::StageProcNeonV2< CUR >::operator= (const StageProcNeonV2< CUR > & other) private delete
References StageProcNeonV2().
operator=() [2/2]
template<int CUR> StageProcNeonV2 & hiir::StageProcNeonV2< CUR >::operator= (StageProcNeonV2< CUR > && other) private delete
operator==()
template<int CUR> bool hiir::StageProcNeonV2< CUR >::operator== (const StageProcNeonV2< CUR > & other) const private delete
process_sample_neg()
template<int CUR> void hiir::StageProcNeonV2< CUR >::process_sample_neg (float32x2_t & x, StageDataNeonV2 * stage_ptr) static noexcept
Definition at line 49 of file StageProcNeonV2.hpp.
References process_sample_neg_rec(), and hiir::storea().
process_sample_neg_rec() [1/2]
hiir_FORCEINLINE void hiir::StageProcNeonV2< 0 >::process_sample_neg_rec (float32x2_t & , StageDataNeonV2 *) noexcept
Definition at line 94 of file StageProcNeonV2.hpp.
References hiir_FORCEINLINE.
process_sample_neg_rec() [2/2]
template<int CUR> void hiir::StageProcNeonV2< CUR >::process_sample_neg_rec (float32x2_t & x, StageDataNeonV2 * stage_ptr) static noexcept
Definition at line 81 of file StageProcNeonV2.hpp.
References StageProcNeonV2(), hiir::load2a(), process_sample_neg_rec(), and hiir::storea().
Referenced by process_sample_neg(), and process_sample_neg_rec().
process_sample_pos()
template<int CUR> void hiir::StageProcNeonV2< CUR >::process_sample_pos (float32x2_t & x, StageDataNeonV2 * stage_ptr) static noexcept
Definition at line 40 of file StageProcNeonV2.hpp.
References process_sample_pos_rec(), and hiir::storea().
Referenced by hiir::Downsampler2xNeon< NC >::process_block_quad(), hiir::Upsampler2xNeon< NC >::process_block_quad(), hiir::Downsampler2xNeon< NC >::process_sample(), hiir::Upsampler2xNeon< NC >::process_sample(), and hiir::Downsampler2xNeon< NC >::process_sample_split().
process_sample_pos_rec() [1/2]
hiir_FORCEINLINE void hiir::StageProcNeonV2< 0 >::process_sample_pos_rec (float32x2_t & , StageDataNeonV2 *) noexcept
Definition at line 73 of file StageProcNeonV2.hpp.
References hiir_FORCEINLINE.
process_sample_pos_rec() [2/2]
template<int CUR> void hiir::StageProcNeonV2< CUR >::process_sample_pos_rec (float32x2_t & x, StageDataNeonV2 * stage_ptr) static noexcept
Definition at line 58 of file StageProcNeonV2.hpp.
References StageProcNeonV2(), hiir::load2a(), process_sample_pos_rec(), and hiir::storea().
Referenced by process_sample_pos(), and process_sample_pos_rec().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/StageProcNeonV2.h
src/3rdparty/hiir/hiir/StageProcNeonV2.hpp