LMMS: lmms::gui::TemplatesMenu Class Reference
lmms::gui::TemplatesMenu Class Reference
#include <TemplatesMenu.h>
Public Member Functions
TemplatesMenu (QWidget *parent=nullptr)
~TemplatesMenu () override=default
Private Slots
void addTemplatesFromDir (const QDir &dir)
static void createNewProjectFromTemplate (QAction *_action)
void fillTemplatesMenu ()
Detailed Description
Definition at line 36 of file TemplatesMenu.h.
Constructor & Destructor Documentation
TemplatesMenu()
lmms::gui::TemplatesMenu::TemplatesMenu (QWidget * parent = nullptr)
Definition at line 16 of file TemplatesMenu.cpp.
References createNewProjectFromTemplate(), fillTemplatesMenu(), and lmms::embed::getIconPixmap().
~TemplatesMenu()
lmms::gui::TemplatesMenu::~TemplatesMenu () override default
Member Function Documentation
addTemplatesFromDir
void lmms::gui::TemplatesMenu::addTemplatesFromDir (const QDir & dir) private slot
Definition at line 53 of file TemplatesMenu.cpp.
References lmms::embed::getIconPixmap().
Referenced by fillTemplatesMenu().
createNewProjectFromTemplate
void lmms::gui::TemplatesMenu::createNewProjectFromTemplate (QAction * _action) static private slot
Definition at line 29 of file TemplatesMenu.cpp.
References lmms::Song::createNewProjectFromTemplate(), lmms::gui::getGUI(), and lmms::Engine::getSong().
Referenced by TemplatesMenu().
fillTemplatesMenu
void lmms::gui::TemplatesMenu::fillTemplatesMenu () private slot
Definition at line 42 of file TemplatesMenu.cpp.
References addTemplatesFromDir(), and lmms::ConfigManager::inst().
Referenced by TemplatesMenu().
The documentation for this class was generated from the following files:
include/TemplatesMenu.h
src/gui/menus/TemplatesMenu.cpp