LMMS: Jack::JackMidiAsyncWaitQueue Class Reference
Jack::JackMidiAsyncWaitQueue Class Reference
This is an asynchronous wait queue that allows a thread to wait for a message, either indefinitely or for a specified time.
#include <JackMidiAsyncWaitQueue.h>
Public Member Functions
JackMidiAsyncWaitQueue (size_t max_bytes=4096, size_t max_messages=1024)
Creates a new asynchronous MIDI wait message queue.
~JackMidiAsyncWaitQueue ()
jack_midi_event_t * DequeueEvent ()
Dequeues and returns a MIDI event.
jack_midi_event_t * DequeueEvent (jack_nframes_t frame)
Waits until the specified frame for a MIDI event to be available.
jack_midi_event_t * DequeueEvent (long usecs)
Waits a specified time for a MIDI event to be available, or indefinitely if the time is negative.
EnqueueResult EnqueueEvent (jack_midi_event_t *event, jack_nframes_t frame_offset=0)
A wrapper method for the EnqueueEvent method above.
EnqueueResult EnqueueEvent (jack_nframes_t time, size_t size, jack_midi_data_t *buffer)
Enqueues the MIDI event specified by the arguments.
Public Member Functions inherited from Jack::JackMidiAsyncQueue
JackMidiAsyncQueue (size_t max_bytes=4096, size_t max_messages=1024)
Creates a new asynchronous MIDI message queue.
virtual ~JackMidiAsyncQueue ()
EnqueueResult EnqueueEvent (jack_midi_event_t *event, jack_nframes_t frame_offset=0)
A wrapper method for the EnqueueEvent method above.
size_t GetAvailableSpace ()
Returns the maximum size event that can be enqueued right now.
Public Member Functions inherited from Jack::JackMidiReadQueue
virtual ~JackMidiReadQueue ()
Public Member Functions inherited from Jack::JackMidiWriteQueue
virtual ~JackMidiWriteQueue ()
EnqueueResult EnqueueEvent (jack_midi_event_t *event, jack_nframes_t frame_offset=0)
A wrapper method for the EnqueueEvent method above.
Private Attributes
JackSynchro semaphore
Additional Inherited Members
Public Types inherited from Jack::JackMidiWriteQueue
enum EnqueueResult {
BUFFER_FULL ,
BUFFER_TOO_SMALL ,
EVENT_EARLY ,
EN_ERROR ,
OK
}
Detailed Description
This is an asynchronous wait queue that allows a thread to wait for a message, either indefinitely or for a specified time.
This is one example of a way that the JackMidiAsyncQueue class can be extended so that process threads can interact with non-process threads to send MIDI events.
XXX: As of right now, this code hasn't been tested. Also, note the warning in the JackMidiAsyncWaitQueue.cpp about semaphore wait resolution.
Definition at line 39 of file JackMidiAsyncWaitQueue.h.
Constructor & Destructor Documentation
JackMidiAsyncWaitQueue()
JackMidiAsyncWaitQueue::JackMidiAsyncWaitQueue (size_t max_bytes = 4096, size_t max_messages = 1024)
Creates a new asynchronous MIDI wait message queue.
The queue can store up to max_messages MIDI messages and up to max_bytes of MIDI data before it starts rejecting messages.
Definition at line 28 of file JackMidiAsyncWaitQueue.cpp.
References Jack::JackMidiAsyncQueue::JackMidiAsyncQueue(), Jack::JackMidiAsyncQueue::max_bytes, and semaphore.
~JackMidiAsyncWaitQueue()
JackMidiAsyncWaitQueue::~JackMidiAsyncWaitQueue ()
Definition at line 37 of file JackMidiAsyncWaitQueue.cpp.
References semaphore.
Member Function Documentation
DequeueEvent() [1/3]
jack_midi_event_t * JackMidiAsyncWaitQueue::DequeueEvent () virtual
Dequeues and returns a MIDI event.
Returns '0' if there are no MIDI events available right now.
Reimplemented from Jack::JackMidiAsyncQueue.
Definition at line 43 of file JackMidiAsyncWaitQueue.cpp.
References DequeueEvent().
Referenced by DequeueEvent(), and DequeueEvent().
DequeueEvent() [2/3]
jack_midi_event_t * JackMidiAsyncWaitQueue::DequeueEvent (jack_nframes_t frame)
Waits until the specified frame for a MIDI event to be available.
Returns the MIDI event, or '0' if time runs out and no MIDI event is available.
Definition at line 49 of file JackMidiAsyncWaitQueue.cpp.
References DequeueEvent(), GetMicroSeconds(), and Jack::GetTimeFromFrames().
DequeueEvent() [3/3]
jack_midi_event_t * JackMidiAsyncWaitQueue::DequeueEvent (long usecs)
Waits a specified time for a MIDI event to be available, or indefinitely if the time is negative.
Returns the MIDI event, or '0' if time runs out and no MIDI event is available.
Definition at line 69 of file JackMidiAsyncWaitQueue.cpp.
References Jack::JackMidiAsyncQueue::DequeueEvent(), and semaphore.
EnqueueEvent() [1/2]
EnqueueResult Jack::JackMidiWriteQueue::EnqueueEvent (jack_midi_event_t * event, jack_nframes_t frame_offset = 0) inline
A wrapper method for the EnqueueEvent method above.
The optional 'frame_offset' argument is an amount of frames to add to the event's time.
Definition at line 56 of file JackMidiWriteQueue.h.
EnqueueEvent() [2/2]
Jack::JackMidiWriteQueue::EnqueueResult JackMidiAsyncWaitQueue::EnqueueEvent (jack_nframes_t time, size_t size, jack_midi_data_t * buffer) virtual
Enqueues the MIDI event specified by the arguments.
The return value indicates whether or not the event was successfully enqueued.
Reimplemented from Jack::JackMidiAsyncQueue.
Definition at line 76 of file JackMidiAsyncWaitQueue.cpp.
References Jack::JackMidiAsyncQueue::EnqueueEvent(), Jack::JackMidiWriteQueue::OK, and semaphore.
Member Data Documentation
semaphore
JackSynchro Jack::JackMidiAsyncWaitQueue::semaphore private
Definition at line 43 of file JackMidiAsyncWaitQueue.h.
Referenced by JackMidiAsyncWaitQueue(), ~JackMidiAsyncWaitQueue(), DequeueEvent(), and EnqueueEvent().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackMidiAsyncWaitQueue.h
src/3rdparty/jack2/common/JackMidiAsyncWaitQueue.cpp