LMMS: lmms::MeterModel Class Reference
lmms::MeterModel Class Reference
#include <MeterModel.h>
Public Member Functions
MeterModel (Model *_parent)
~MeterModel () override=default
IntModel & denominatorModel ()
void loadSettings (const QDomElement &_this, const QString &_name)
IntModel & numeratorModel ()
void reset ()
void saveSettings (QDomDocument &_doc, QDomElement &_this, const QString &_name)
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Private Member Functions
mapPropertyFromModel (int, getDenominator, setDenominator, m_denominatorModel)
mapPropertyFromModel (int, getNumerator, setNumerator, m_numeratorModel)
Private Attributes
IntModel m_denominatorModel
IntModel m_numeratorModel
Additional Inherited Members
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Detailed Description
Definition at line 34 of file MeterModel.h.
Constructor & Destructor Documentation
MeterModel()
lmms::MeterModel::MeterModel (Model * _parent)
Definition at line 33 of file MeterModel.cpp.
References lmms::Model::Model(), lmms::Model::dataChanged(), m_denominatorModel, and m_numeratorModel.
Referenced by mapPropertyFromModel().
~MeterModel()
lmms::MeterModel::~MeterModel () override default
References loadSettings(), reset(), and saveSettings().
Member Function Documentation
denominatorModel()
IntModel & lmms::MeterModel::denominatorModel () inline
Definition at line 56 of file MeterModel.h.
References m_denominatorModel.
Referenced by lmms::gui::TempoSyncBarModelEditor::updateTextDescription().
loadSettings()
void lmms::MeterModel::loadSettings (const QDomElement & _this, const QString & _name)
Definition at line 67 of file MeterModel.cpp.
References m_denominatorModel, and m_numeratorModel.
Referenced by ~MeterModel().
mapPropertyFromModel() [1/2]
lmms::MeterModel::mapPropertyFromModel (int , getDenominator , setDenominator , m_denominatorModel) private
References MeterModel(), lmms::Model::Model(), and m_denominatorModel.
mapPropertyFromModel() [2/2]
lmms::MeterModel::mapPropertyFromModel (int , getNumerator , setNumerator , m_numeratorModel) private
References m_numeratorModel.
numeratorModel()
IntModel & lmms::MeterModel::numeratorModel () inline
Definition at line 51 of file MeterModel.h.
References m_numeratorModel.
Referenced by lmms::gui::TempoSyncBarModelEditor::updateTextDescription().
reset()
void lmms::MeterModel::reset ()
Definition at line 45 of file MeterModel.cpp.
References lmms::AutomationClip::clear(), lmms::AutomationClip::globalAutomationClip(), m_denominatorModel, and m_numeratorModel.
Referenced by ~MeterModel().
saveSettings()
void lmms::MeterModel::saveSettings (QDomDocument & _doc, QDomElement & _this, const QString & _name)
Definition at line 57 of file MeterModel.cpp.
References m_denominatorModel, and m_numeratorModel.
Referenced by ~MeterModel().
Member Data Documentation
m_denominatorModel
IntModel lmms::MeterModel::m_denominatorModel private
Definition at line 64 of file MeterModel.h.
Referenced by MeterModel(), denominatorModel(), loadSettings(), mapPropertyFromModel(), reset(), and saveSettings().
m_numeratorModel
IntModel lmms::MeterModel::m_numeratorModel private
Definition at line 63 of file MeterModel.h.
Referenced by MeterModel(), loadSettings(), mapPropertyFromModel(), numeratorModel(), reset(), and saveSettings().
The documentation for this class was generated from the following files:
include/MeterModel.h
src/core/MeterModel.cpp