LMMS: lmms::gui::Knob Class Reference
lmms::gui::Knob Class Reference
#include <Knob.h>
Public Types
enum class LabelRendering {
WidgetFont ,
LegacyFixedFontSize
}
Determines how the label of the knob is rendered.
Public Types inherited from lmms::gui::FloatModelEditorBase
enum class DirectionOfManipulation {
Vertical ,
Horizontal
}
Public Member Functions
Knob (const Knob &other)=delete
Knob (KnobType _knob_num, QWidget *_parent=nullptr, const QString &_name=QString())
Construct a Knob with the given style and no label.
Knob (KnobType knobNum, const QString &labelText, int labelPixelSize, QWidget *parent, const QString &name=QString())
Constructs a knob with a label font in the pixel size.
Knob (KnobType knobNum, const QString &labelText, QWidget *parent=nullptr, LabelRendering labelRendering=LabelRendering::WidgetFont, const QString &name=QString())
Construct a Knob with the given style and label text.
Knob (QWidget *_parent=nullptr, const QString &_name=QString())
default ctor
QPointF centerPoint () const
float centerPointX () const
float centerPointY () const
const QString & getLabel () const
float innerRadius () const
KnobType knobNum () const
float lineWidth () const
QColor outerColor () const
float outerRadius () const
void setCenterPointX (float c)
void setCenterPointY (float c)
void setInnerRadius (float r)
void setknobNum (KnobType k)
void setLabel (const QString &txt)
void setLineWidth (float w)
void setOuterColor (const QColor &c)
void setOuterRadius (float r)
void setTextColor (const QColor &c)
void setTotalAngle (float angle)
QColor textColor () const
Public Member Functions inherited from lmms::gui::FloatModelEditorBase
FloatModelEditorBase (const FloatModelEditorBase &other)=delete
FloatModelEditorBase (DirectionOfManipulation directionOfManipulation=DirectionOfManipulation::Vertical, QWidget *_parent=nullptr, const QString &_name=QString())
default ctor
void setHintText (const QString &txt_before, const QString &txt_after)
Public Member Functions inherited from lmms::gui::TypedModelView< FloatModel >
TypedModelView (Model *model, QWidget *_this)
FloatModel * model ()
const FloatModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Protected Member Functions
void changeEvent (QEvent *ev) override
bool fixedFontSizeLabelRendering () const
Affects how the label of the knob is rendered.
void paintEvent (QPaintEvent *) override
void setFixedFontSizeLabelRendering ()
Set the button to legacy rendering mode which uses a fixed font size and that does not take the size of the widget's font into account.
Protected Member Functions inherited from lmms::gui::FloatModelEditorBase
void contextMenuEvent (QContextMenuEvent *me) override
virtual QString displayValue () const
void doConnections () override
void dragEnterEvent (QDragEnterEvent *dee) override
void dropEvent (QDropEvent *de) override
void enterEvent (QEvent *event) override
void focusOutEvent (QFocusEvent *fe) override
virtual float getValue (const QPoint &p)
void leaveEvent (QEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *me) override
void mouseMoveEvent (QMouseEvent *me) override
void mousePressEvent (QMouseEvent *me) override
void mouseReleaseEvent (QMouseEvent *me) override
float pageSize () const
void paintEvent (QPaintEvent *me) override
void setPosition (const QPoint &p)
void showTextFloat (int msecBeforeDisplay, int msecDisplayTime)
void wheelEvent (QWheelEvent *me) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void modelChanged ()
QWidget * widget ()
Properties
QColor arcActiveColor
QColor arcInactiveColor
float centerPointX
float centerPointY
float innerRadius
KnobType knobNum
QColor lineActiveColor
QColor lineInactiveColor
float lineWidth
QColor outerColor
float outerRadius
QColor textColor
Private Member Functions
int angleFromValue (float value, float minValue, float maxValue, float totalAngle) const
QLineF calculateLine (const QPointF &_mid, float _radius, float _innerRadius=1) const
void drawKnob (QPainter *_p)
void drawLabel (QPainter &p)
void initUi (const QString &_name)
to be called by ctors
void onKnobNumUpdated ()
to be called when you updated m_knobNum
bool updateAngle ()
void updateFixedSize ()
Private Attributes
int m_angle
QColor m_arcActiveColor
QColor m_arcInactiveColor
QImage m_cache
QPointF m_centerPoint
bool m_fixedFontSizeLabelRendering = false
float m_innerRadius
KnobType m_knobNum
std::unique_ptr< QPixmap > m_knobPixmap
QString m_label
QColor m_lineActiveColor
QColor m_lineInactiveColor
float m_lineWidth
QColor m_outerColor
float m_outerRadius
QColor m_textColor
float m_totalAngle
Additional Inherited Members
Signals inherited from lmms::gui::FloatModelEditorBase
void sliderMoved (float value)
void sliderPressed ()
void sliderReleased ()
Protected Attributes inherited from lmms::gui::FloatModelEditorBase
bool m_buttonPressed
DirectionOfManipulation m_directionOfManipulation
QPoint m_lastMousePos
mouse position in last mouseMoveEvent
float m_leftOver
BoolModel m_volumeKnob
FloatModel m_volumeRatio
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Static Protected Attributes inherited from lmms::gui::FloatModelEditorBase
static SimpleTextFloat * s_textFloat = nullptr
Detailed Description
Definition at line 46 of file Knob.h.
Member Enumeration Documentation
LabelRendering
enum class lmms::gui::Knob::LabelRendering strong
Determines how the label of the knob is rendered.
Labels can be rendered using the font that is set for the knob or using a font with a fixed size which is determined by SMALL_FONT_SIZE.
Enumerator
WidgetFont
Renders the label using the font that is set for the widget.
The space that's needed for the label is determined using the font metrics of the knob's font.
LegacyFixedFontSize
Renders the labels in legacy mode.
This uses a fixed font size and does not adhere to the font size that's set for the widget's font.
Deprecated
Do not use this mode in new code as it is considered deprecated and might be removed in the future.
Definition at line 82 of file Knob.h.
Constructor & Destructor Documentation
Knob() [1/5]
lmms::gui::Knob::Knob (KnobType _knob_num, QWidget * _parent = nullptr, const QString & _name = QString())
Construct a Knob with the given style and no label.
Parameters
_knob_num Style of the knob
_parent Parent widget
_name Object name of the widget
Definition at line 40 of file Knob.cpp.
References lmms::gui::FloatModelEditorBase::FloatModelEditorBase(), initUi(), m_angle, m_knobNum, m_label, m_lineWidth, and m_textColor.
Referenced by lmms::gui::CustomTextKnob::CustomTextKnob(), lmms::gui::CustomTextKnob::CustomTextKnob(), Knob(), Knob(), Knob(), Knob(), and lmms::gui::TempoSyncKnob::TempoSyncKnob().
Knob() [2/5]
lmms::gui::Knob::Knob (KnobType knobNum, const QString & labelText, QWidget * parent = nullptr, LabelRendering labelRendering = LabelRendering::WidgetFont, const QString & name = QString())
Construct a Knob with the given style and label text.
Parameters
knobNum Style of the knob
labelText Text for the label
parent Parent widget
labelRendering Determines if the label uses the widget font or a font with a fixed size of 12 pixels (LegacyFixedFontSize). The default is to use the widget font.
name Object name of the widget
Definition at line 51 of file Knob.cpp.
References Knob(), knobNum, LegacyFixedFontSize, setFixedFontSizeLabelRendering(), and setLabel().
Knob() [3/5]
lmms::gui::Knob::Knob (KnobType knobNum, const QString & labelText, int labelPixelSize, QWidget * parent, const QString & name = QString())
Constructs a knob with a label font in the pixel size.
Parameters
knobNum Style of the knob
labelText Text for the label
labelPixelSize Pixel size for the label
parent Parent widget
name Object name of the widget
Definition at line 62 of file Knob.cpp.
References Knob(), lmms::gui::adjustedToPixelSize(), knobNum, and setLabel().
Knob() [4/5]
lmms::gui::Knob::Knob (QWidget * _parent = nullptr, const QString & _name = QString())
default ctor
Definition at line 69 of file Knob.cpp.
References Knob().
Knob() [5/5]
lmms::gui::Knob::Knob (const Knob & other) delete
References Knob(), centerPoint(), centerPointX, centerPointY, changeEvent(), getLabel(), innerRadius, k, knobNum, lineWidth, outerColor, outerRadius, paintEvent(), setCenterPointX(), setCenterPointY(), setInnerRadius(), setknobNum(), setLabel(), setLineWidth(), setOuterColor(), setOuterRadius(), setTextColor(), setTotalAngle(), and textColor.
Member Function Documentation
angleFromValue()
int lmms::gui::Knob::angleFromValue (float value, float minValue, float maxValue, float totalAngle) const inline private
Definition at line 205 of file Knob.h.
References m_totalAngle, and lmms::gui::AutomatableModelView::value().
Referenced by drawKnob(), and updateAngle().
calculateLine()
QLineF lmms::gui::Knob::calculateLine (const QPointF & _mid, float _radius, float _innerRadius = 1) const private
Definition at line 349 of file Knob.cpp.
References m_angle.
Referenced by drawKnob().
centerPoint()
QPointF lmms::gui::Knob::centerPoint () const
Definition at line 272 of file Knob.cpp.
References m_centerPoint.
Referenced by Knob(), and drawKnob().
centerPointX()
float lmms::gui::Knob::centerPointX () const
Definition at line 279 of file Knob.cpp.
References m_centerPoint.
centerPointY()
float lmms::gui::Knob::centerPointY () const
Definition at line 293 of file Knob.cpp.
References m_centerPoint.
changeEvent()
void lmms::gui::Knob::changeEvent (QEvent * ev) override protected
Definition at line 511 of file Knob.cpp.
References m_cache, m_label, onKnobNumUpdated(), setLabel(), and updateFixedSize().
Referenced by Knob().
drawKnob()
void lmms::gui::Knob::drawKnob (QPainter * _p) private
Definition at line 379 of file Knob.cpp.
References angleFromValue(), lmms::gui::Bright26, calculateLine(), centerPoint(), lmms::gui::Dark28, innerRadius, lineWidth, m_angle, m_arcActiveColor, m_arcInactiveColor, m_cache, m_knobNum, m_knobPixmap, m_lineActiveColor, m_lineInactiveColor, m_outerColor, m_totalAngle, lmms::gui::TypedModelView< FloatModel >::model(), outerRadius, lmms::gui::Small17, lmms::gui::Styled, updateAngle(), and lmms::gui::Vintage32.
Referenced by paintEvent().
drawLabel()
void lmms::gui::Knob::drawLabel (QPainter & p) private
Definition at line 485 of file Knob.cpp.
References lmms::gui::adjustedToPixelSize(), fixedFontSizeLabelRendering(), lmms::horizontalAdvance(), m_label, SMALL_FONT_SIZE, and textColor.
Referenced by paintEvent().
fixedFontSizeLabelRendering()
bool lmms::gui::Knob::fixedFontSizeLabelRendering () const inline protected
Affects how the label of the knob is rendered.
The default mode returns false. The height of the label text is taken into account when a new fixed size is computed for the Knob. When the label text is painted the descent of the font is used to compute the base line. The default mode returns false.
Enabling fixed font size rendering mode leads to the following behavior:
The height of the label is not taken into account when the new fixed height of the Knob is computed. Instead a fixed size of 10 is added for the label.
When the knob is painted the baseline of the font is always set to 2 pixels away from the lower side of the Knob's rectangle.
The label is always rendered with a size of SMALL_FONT_SIZE.
Definition at line 185 of file Knob.h.
References m_fixedFontSizeLabelRendering.
Referenced by drawLabel(), and updateFixedSize().
getLabel()
const QString & lmms::gui::Knob::getLabel () const
Definition at line 146 of file Knob.cpp.
References m_label.
Referenced by Knob().
initUi()
void lmms::gui::Knob::initUi (const QString & _name) private
to be called by ctors
Definition at line 76 of file Knob.cpp.
References lmms::gui::Bright26, lmms::gui::Dark28, knobNum, m_arcActiveColor, m_lineActiveColor, onKnobNumUpdated(), setInnerRadius(), setOuterRadius(), setTotalAngle(), lmms::gui::Small17, and lmms::gui::Vintage32.
Referenced by Knob().
innerRadius()
float lmms::gui::Knob::innerRadius () const
Definition at line 223 of file Knob.cpp.
References m_innerRadius.
knobNum()
KnobType lmms::gui::Knob::knobNum () const
Definition at line 252 of file Knob.cpp.
References m_knobNum.
lineWidth()
float lmms::gui::Knob::lineWidth () const
Definition at line 307 of file Knob.cpp.
References m_lineWidth.
onKnobNumUpdated()
void lmms::gui::Knob::onKnobNumUpdated () private
to be called when you updated m_knobNum
Definition at line 112 of file Knob.cpp.
References lmms::gui::Bright26, lmms::gui::convertPixmapToGrayScale(), lmms::gui::Dark28, lmms::embed::getIconPixmap(), m_knobNum, m_knobPixmap, lmms::gui::Small17, lmms::gui::Styled, and lmms::gui::Vintage32.
Referenced by changeEvent(), initUi(), and setknobNum().
outerColor()
QColor lmms::gui::Knob::outerColor () const
Definition at line 321 of file Knob.cpp.
References m_outerColor.
outerRadius()
float lmms::gui::Knob::outerRadius () const
Definition at line 237 of file Knob.cpp.
References m_outerRadius.
paintEvent()
void lmms::gui::Knob::paintEvent (QPaintEvent *) override protected
Definition at line 503 of file Knob.cpp.
References drawKnob(), and drawLabel().
Referenced by Knob().
setCenterPointX()
void lmms::gui::Knob::setCenterPointX (float c)
Definition at line 286 of file Knob.cpp.
References m_centerPoint.
Referenced by Knob().
setCenterPointY()
void lmms::gui::Knob::setCenterPointY (float c)
Definition at line 300 of file Knob.cpp.
References m_centerPoint.
Referenced by Knob().
setFixedFontSizeLabelRendering()
void lmms::gui::Knob::setFixedFontSizeLabelRendering () protected
Set the button to legacy rendering mode which uses a fixed font size and that does not take the size of the widget's font into account.
This can be thought of as a legacy mode which reinstates the old behavior of the knob.
See also
fixedFontSizeLabelRendering().
Definition at line 162 of file Knob.cpp.
References m_fixedFontSizeLabelRendering, and updateFixedSize().
Referenced by Knob(), and lmms::gui::TempoSyncKnob::TempoSyncKnob().
setInnerRadius()
void lmms::gui::Knob::setInnerRadius (float r)
Definition at line 230 of file Knob.cpp.
References m_innerRadius.
Referenced by Knob(), and initUi().
setknobNum()
void lmms::gui::Knob::setknobNum (KnobType k)
Definition at line 260 of file Knob.cpp.
References k, m_knobNum, and onKnobNumUpdated().
Referenced by Knob().
setLabel()
void lmms::gui::Knob::setLabel (const QString & txt)
Definition at line 152 of file Knob.cpp.
References m_label, and updateFixedSize().
Referenced by lmms::gui::CustomTextKnob::CustomTextKnob(), Knob(), Knob(), Knob(), lmms::gui::TempoSyncKnob::TempoSyncKnob(), lmms::gui::TempoSyncKnob::TempoSyncKnob(), and changeEvent().
setLineWidth()
void lmms::gui::Knob::setLineWidth (float w)
Definition at line 314 of file Knob.cpp.
References m_lineWidth.
Referenced by Knob().
setOuterColor()
void lmms::gui::Knob::setOuterColor (const QColor & c)
Definition at line 328 of file Knob.cpp.
References m_outerColor.
Referenced by Knob().
setOuterRadius()
void lmms::gui::Knob::setOuterRadius (float r)
Definition at line 244 of file Knob.cpp.
References m_outerRadius.
Referenced by Knob(), and initUi().
setTextColor()
void lmms::gui::Knob::setTextColor (const QColor & c)
Definition at line 342 of file Knob.cpp.
References m_textColor.
Referenced by Knob().
setTotalAngle()
void lmms::gui::Knob::setTotalAngle (float angle)
Definition at line 206 of file Knob.cpp.
References m_totalAngle.
Referenced by Knob(), and initUi().
textColor()
QColor lmms::gui::Knob::textColor () const
Definition at line 335 of file Knob.cpp.
References m_textColor.
updateAngle()
bool lmms::gui::Knob::updateAngle () private
Definition at line 361 of file Knob.cpp.
References angleFromValue(), m_angle, m_totalAngle, lmms::gui::TypedModelView< FloatModel >::model(), and lmms::gui::AutomatableModelView::value().
Referenced by drawKnob().
updateFixedSize()
void lmms::gui::Knob::updateFixedSize () private
Definition at line 171 of file Knob.cpp.
References lmms::gui::adjustedToPixelSize(), fixedFontSizeLabelRendering(), lmms::horizontalAdvance(), knobNum, m_knobPixmap, m_label, SMALL_FONT_SIZE, and lmms::gui::Styled.
Referenced by changeEvent(), setFixedFontSizeLabelRendering(), and setLabel().
Member Data Documentation
m_angle
int lmms::gui::Knob::m_angle private
Definition at line 218 of file Knob.h.
Referenced by Knob(), calculateLine(), drawKnob(), and updateAngle().
m_arcActiveColor
QColor lmms::gui::Knob::m_arcActiveColor private
Definition at line 230 of file Knob.h.
Referenced by drawKnob(), and initUi().
m_arcInactiveColor
QColor lmms::gui::Knob::m_arcInactiveColor private
Definition at line 231 of file Knob.h.
Referenced by drawKnob().
m_cache
QImage lmms::gui::Knob::m_cache private
Definition at line 219 of file Knob.h.
Referenced by changeEvent(), and drawKnob().
m_centerPoint
QPointF lmms::gui::Knob::m_centerPoint private
Definition at line 222 of file Knob.h.
Referenced by centerPoint(), centerPointX(), centerPointY(), setCenterPointX(), and setCenterPointY().
m_fixedFontSizeLabelRendering
bool lmms::gui::Knob::m_fixedFontSizeLabelRendering = false private
Definition at line 213 of file Knob.h.
Referenced by fixedFontSizeLabelRendering(), and setFixedFontSizeLabelRendering().
m_innerRadius
float lmms::gui::Knob::m_innerRadius private
Definition at line 223 of file Knob.h.
Referenced by innerRadius(), and setInnerRadius().
m_knobNum
KnobType lmms::gui::Knob::m_knobNum private
Definition at line 235 of file Knob.h.
Referenced by Knob(), drawKnob(), knobNum(), onKnobNumUpdated(), and setknobNum().
m_knobPixmap
std::unique_ptr<QPixmap> lmms::gui::Knob::m_knobPixmap private
Definition at line 215 of file Knob.h.
Referenced by drawKnob(), onKnobNumUpdated(), and updateFixedSize().
m_label
QString lmms::gui::Knob::m_label private
Definition at line 212 of file Knob.h.
Referenced by Knob(), changeEvent(), drawLabel(), getLabel(), setLabel(), and updateFixedSize().
m_lineActiveColor
QColor lmms::gui::Knob::m_lineActiveColor private
Definition at line 228 of file Knob.h.
Referenced by drawKnob(), and initUi().
m_lineInactiveColor
QColor lmms::gui::Knob::m_lineInactiveColor private
Definition at line 229 of file Knob.h.
Referenced by drawKnob().
m_lineWidth
float lmms::gui::Knob::m_lineWidth private
Definition at line 225 of file Knob.h.
Referenced by Knob(), lineWidth(), and setLineWidth().
m_outerColor
QColor lmms::gui::Knob::m_outerColor private
Definition at line 226 of file Knob.h.
Referenced by drawKnob(), outerColor(), and setOuterColor().
m_outerRadius
float lmms::gui::Knob::m_outerRadius private
Definition at line 224 of file Knob.h.
Referenced by outerRadius(), and setOuterRadius().
m_textColor
QColor lmms::gui::Knob::m_textColor private
Definition at line 233 of file Knob.h.
Referenced by Knob(), setTextColor(), and textColor().
m_totalAngle
float lmms::gui::Knob::m_totalAngle private
Definition at line 217 of file Knob.h.
Referenced by angleFromValue(), drawKnob(), setTotalAngle(), and updateAngle().
Property Documentation
arcActiveColor
QColor lmms::gui::Knob::arcActiveColor
Definition at line 65 of file Knob.h.
arcInactiveColor
QColor lmms::gui::Knob::arcInactiveColor
Definition at line 66 of file Knob.h.
centerPointX
float lmms::gui::Knob::centerPointX read write
Definition at line 54 of file Knob.h.
Referenced by Knob().
centerPointY
float lmms::gui::Knob::centerPointY read write
Definition at line 55 of file Knob.h.
Referenced by Knob().
innerRadius
float lmms::gui::Knob::innerRadius read write
Definition at line 51 of file Knob.h.
Referenced by Knob(), and drawKnob().
knobNum
KnobType lmms::gui::Knob::knobNum read write
Definition at line 68 of file Knob.h.
Referenced by Knob(), Knob(), Knob(), lmms::gui::TempoSyncKnob::TempoSyncKnob(), lmms::gui::TempoSyncKnob::TempoSyncKnob(), initUi(), and updateFixedSize().
lineActiveColor
QColor lmms::gui::Knob::lineActiveColor
Definition at line 63 of file Knob.h.
lineInactiveColor
QColor lmms::gui::Knob::lineInactiveColor
Definition at line 64 of file Knob.h.
lineWidth
float lmms::gui::Knob::lineWidth read write
Definition at line 57 of file Knob.h.
Referenced by Knob(), and drawKnob().
outerColor
QColor lmms::gui::Knob::outerColor read write
Definition at line 61 of file Knob.h.
Referenced by Knob().
outerRadius
float lmms::gui::Knob::outerRadius read write
Definition at line 52 of file Knob.h.
Referenced by Knob(), and drawKnob().
textColor
QColor lmms::gui::Knob::textColor read write
Definition at line 70 of file Knob.h.
Referenced by Knob(), and drawLabel().
The documentation for this class was generated from the following files:
include/Knob.h
src/gui/widgets/Knob.cpp