LMMS: lmms::SampleBuffer Class Reference
lmms::SampleBuffer Class Reference
#include <SampleBuffer.h>
Public Types
using const_iterator = std::vector<SampleFrame>::const_iterator
using const_reference = const SampleFrame&
using const_reverse_iterator = std::vector<SampleFrame>::const_reverse_iterator
using difference_type = std::vector<SampleFrame>::difference_type
using iterator = std::vector<SampleFrame>::iterator
using reference = SampleFrame&
using reverse_iterator = std::vector<SampleFrame>::reverse_iterator
using size_type = std::vector<SampleFrame>::size_type
using value_type = SampleFrame
Public Member Functions
SampleBuffer ()=default
SampleBuffer (const QString &audioFile)
SampleBuffer (const QString &base64, int sampleRate)
SampleBuffer (const SampleFrame *data, size_t numFrames, int sampleRate=Engine::audioEngine() ->outputSampleRate())
SampleBuffer (std::vector< SampleFrame > data, int sampleRate)
auto audioFile () const -> const QString &
auto begin () -> iterator
auto begin () const -> const_iterator
auto cbegin () const -> const_iterator
auto cend () const -> const_iterator
auto crbegin () const -> const_reverse_iterator
auto crend () const -> const_reverse_iterator
auto data () const -> const SampleFrame *
auto empty () const -> bool
auto end () -> iterator
auto end () const -> const_iterator
auto rbegin () -> reverse_iterator
auto rbegin () const -> const_reverse_iterator
auto rend () -> reverse_iterator
auto rend () const -> const_reverse_iterator
auto sampleRate () const -> sample_rate_t
auto size () const -> size_type
auto toBase64 () const -> QString
Static Public Member Functions
static auto emptyBuffer () -> std::shared_ptr< const SampleBuffer >
Private Attributes
QString m_audioFile
std::vector< SampleFrame > m_data
sample_rate_t m_sampleRate = Engine::audioEngine()->outputSampleRate()
Friends
void swap (SampleBuffer &first, SampleBuffer &second)
Detailed Description
Definition at line 38 of file SampleBuffer.h.
Member Typedef Documentation
const_iterator
using lmms::SampleBuffer::const_iterator = std::vector<SampleFrame>::const_iterator
Definition at line 45 of file SampleBuffer.h.
const_reference
using lmms::SampleBuffer::const_reference = const SampleFrame&
Definition at line 43 of file SampleBuffer.h.
const_reverse_iterator
using lmms::SampleBuffer::const_reverse_iterator = std::vector<SampleFrame>::const_reverse_iterator
Definition at line 49 of file SampleBuffer.h.
difference_type
using lmms::SampleBuffer::difference_type = std::vector<SampleFrame>::difference_type
Definition at line 46 of file SampleBuffer.h.
iterator
using lmms::SampleBuffer::iterator = std::vector<SampleFrame>::iterator
Definition at line 44 of file SampleBuffer.h.
reference
using lmms::SampleBuffer::reference = SampleFrame&
Definition at line 42 of file SampleBuffer.h.
reverse_iterator
using lmms::SampleBuffer::reverse_iterator = std::vector<SampleFrame>::reverse_iterator
Definition at line 48 of file SampleBuffer.h.
size_type
using lmms::SampleBuffer::size_type = std::vector<SampleFrame>::size_type
Definition at line 47 of file SampleBuffer.h.
value_type
using lmms::SampleBuffer::value_type = SampleFrame
Definition at line 41 of file SampleBuffer.h.
Constructor & Destructor Documentation
SampleBuffer() [1/5]
lmms::SampleBuffer::SampleBuffer () default
References SampleBuffer(), lmms::Engine::audioEngine(), audioFile(), data(), sampleRate(), swap, and toBase64().
Referenced by SampleBuffer(), and swap.
SampleBuffer() [2/5]
lmms::SampleBuffer::SampleBuffer (const QString & audioFile) explicit
Definition at line 39 of file SampleBuffer.cpp.
References audioFile(), data(), lmms::SampleDecoder::decode(), m_audioFile, m_data, m_sampleRate, sampleRate(), lmms::PathUtil::toAbsolute(), and lmms::PathUtil::toShortestRelative().
SampleBuffer() [3/5]
lmms::SampleBuffer::SampleBuffer (const QString & base64, int sampleRate)
Definition at line 57 of file SampleBuffer.cpp.
References m_data, m_sampleRate, and sampleRate().
SampleBuffer() [4/5]
lmms::SampleBuffer::SampleBuffer (std::vector< SampleFrame > data, int sampleRate)
Definition at line 66 of file SampleBuffer.cpp.
References data(), m_data, m_sampleRate, and sampleRate().
SampleBuffer() [5/5]
lmms::SampleBuffer::SampleBuffer (const SampleFrame * data, size_t numFrames, int sampleRate = Engine::audioEngine()->outputSampleRate())
Definition at line 33 of file SampleBuffer.cpp.
References data(), m_data, m_sampleRate, and sampleRate().
Member Function Documentation
audioFile()
auto lmms::SampleBuffer::audioFile () const->constQString & inline
Definition at line 61 of file SampleBuffer.h.
References audioFile(), and m_audioFile.
Referenced by SampleBuffer(), SampleBuffer(), and audioFile().
begin() [1/2]
auto lmms::SampleBuffer::begin () ->iterator inline
Definition at line 64 of file SampleBuffer.h.
References m_data.
begin() [2/2]
auto lmms::SampleBuffer::begin () const->const_iterator inline
Definition at line 67 of file SampleBuffer.h.
References m_data.
cbegin()
auto lmms::SampleBuffer::cbegin () const->const_iterator inline
Definition at line 70 of file SampleBuffer.h.
References m_data.
cend()
auto lmms::SampleBuffer::cend () const->const_iterator inline
Definition at line 71 of file SampleBuffer.h.
References m_data.
crbegin()
auto lmms::SampleBuffer::crbegin () const->const_reverse_iterator inline
Definition at line 79 of file SampleBuffer.h.
References m_data.
crend()
auto lmms::SampleBuffer::crend () const->const_reverse_iterator inline
Definition at line 80 of file SampleBuffer.h.
References m_data.
data()
auto lmms::SampleBuffer::data () const->constSampleFrame * inline
Definition at line 82 of file SampleBuffer.h.
References m_data.
Referenced by SampleBuffer(), SampleBuffer(), SampleBuffer(), SampleBuffer(), toBase64(), and lmms::Oscillator::userWaveSample().
empty()
auto lmms::SampleBuffer::empty () const->bool inline
Definition at line 84 of file SampleBuffer.h.
References m_data.
emptyBuffer()
auto lmms::SampleBuffer::emptyBuffer () ->std::shared_ptr< constSampleBuffer > static
Definition at line 89 of file SampleBuffer.cpp.
Referenced by lmms::gui::SampleLoader::createBufferFromBase64(), lmms::gui::SampleLoader::createBufferFromFile(), and lmms::gui::SampleClipView::mouseDoubleClickEvent().
end() [1/2]
auto lmms::SampleBuffer::end () ->iterator inline
Definition at line 65 of file SampleBuffer.h.
References m_data.
end() [2/2]
auto lmms::SampleBuffer::end () const->const_iterator inline
Definition at line 68 of file SampleBuffer.h.
References m_data.
rbegin() [1/2]
auto lmms::SampleBuffer::rbegin () ->reverse_iterator inline
Definition at line 73 of file SampleBuffer.h.
References m_data.
rbegin() [2/2]
auto lmms::SampleBuffer::rbegin () const->const_reverse_iterator inline
Definition at line 76 of file SampleBuffer.h.
References m_data.
rend() [1/2]
auto lmms::SampleBuffer::rend () ->reverse_iterator inline
Definition at line 74 of file SampleBuffer.h.
References m_data.
rend() [2/2]
auto lmms::SampleBuffer::rend () const->const_reverse_iterator inline
Definition at line 77 of file SampleBuffer.h.
References m_data.
sampleRate()
auto lmms::SampleBuffer::sampleRate () const->sample_rate_t inline
Definition at line 62 of file SampleBuffer.h.
References m_sampleRate.
Referenced by SampleBuffer(), SampleBuffer(), SampleBuffer(), SampleBuffer(), and SampleBuffer().
size()
auto lmms::SampleBuffer::size () const->size_type inline
Definition at line 83 of file SampleBuffer.h.
References m_data.
Referenced by toBase64(), and lmms::Oscillator::userWaveSample().
toBase64()
QString lmms::SampleBuffer::toBase64 () const->QString
Definition at line 80 of file SampleBuffer.cpp.
References data(), m_data, and size().
Referenced by SampleBuffer().
Friends And Related Symbol Documentation
swap
void swap (SampleBuffer & first, SampleBuffer & second) friend
Definition at line 72 of file SampleBuffer.cpp.
References SampleBuffer(), and lmms::swap().
Referenced by SampleBuffer().
Member Data Documentation
m_audioFile
QString lmms::SampleBuffer::m_audioFile private
Definition at line 90 of file SampleBuffer.h.
Referenced by SampleBuffer(), and audioFile().
m_data
std::vector<SampleFrame> lmms::SampleBuffer::m_data private
Definition at line 89 of file SampleBuffer.h.
Referenced by SampleBuffer(), SampleBuffer(), SampleBuffer(), SampleBuffer(), begin(), begin(), cbegin(), cend(), crbegin(), crend(), data(), empty(), end(), end(), rbegin(), rbegin(), rend(), rend(), size(), and toBase64().
m_sampleRate
sample_rate_t lmms::SampleBuffer::m_sampleRate = Engine::audioEngine()->outputSampleRate() private
Definition at line 91 of file SampleBuffer.h.
Referenced by SampleBuffer(), SampleBuffer(), SampleBuffer(), SampleBuffer(), and sampleRate().
The documentation for this class was generated from the following files:
include/SampleBuffer.h
src/core/SampleBuffer.cpp