LMMS: lmms::ThreadableJob Class Reference
lmms::ThreadableJob Class Reference abstract
#include <ThreadableJob.h>
Public Types
enum class ProcessingState : int {
Unstarted ,
Queued ,
InProgress ,
Done
}
Public Member Functions
ThreadableJob ()
void done ()
void process ()
void queue ()
virtual bool requiresProcessing () const =0
void reset ()
ProcessingState state () const
Protected Member Functions
virtual void doProcessing ()=0
Protected Attributes
std::atomic< ProcessingState > m_state
Detailed Description
Definition at line 35 of file ThreadableJob.h.
Member Enumeration Documentation
ProcessingState
enum class lmms::ThreadableJob::ProcessingState : int strong
Enumerator
Unstarted
Queued
InProgress
Done
Definition at line 39 of file ThreadableJob.h.
Constructor & Destructor Documentation
ThreadableJob()
lmms::ThreadableJob::ThreadableJob () inline
Definition at line 47 of file ThreadableJob.h.
References m_state.
Member Function Documentation
done()
void lmms::ThreadableJob::done () inline
Definition at line 67 of file ThreadableJob.h.
References Done, and m_state.
doProcessing()
virtual void lmms::ThreadableJob::doProcessing () protected pure virtual
Implemented in lmms::AudioBusHandle, lmms::MixerChannel, and lmms::PlayHandle.
Referenced by process().
process()
void lmms::ThreadableJob::process () inline
Definition at line 72 of file ThreadableJob.h.
References Done, doProcessing(), InProgress, m_state, and Queued.
Referenced by lmms::InstrumentPlayHandle::play(), and lmms::AudioEngineWorkerThread::JobQueue::run().
queue()
void lmms::ThreadableJob::queue () inline
Definition at line 62 of file ThreadableJob.h.
References m_state, and Queued.
Referenced by lmms::AudioEngineWorkerThread::JobQueue::addJob().
requiresProcessing()
virtual bool lmms::ThreadableJob::requiresProcessing () const pure virtual
Implemented in lmms::AudioBusHandle, lmms::MixerChannel, and lmms::PlayHandle.
Referenced by lmms::AudioEngineWorkerThread::JobQueue::addJob().
reset()
void lmms::ThreadableJob::reset () inline
Definition at line 57 of file ThreadableJob.h.
References m_state, and Unstarted.
state()
ProcessingState lmms::ThreadableJob::state () const inline
Definition at line 52 of file ThreadableJob.h.
References m_state.
Member Data Documentation
m_state
std::atomic<ProcessingState> lmms::ThreadableJob::m_state protected
Definition at line 88 of file ThreadableJob.h.
Referenced by ThreadableJob(), done(), process(), queue(), reset(), and state().
The documentation for this class was generated from the following file:
include/ThreadableJob.h