LMMS: lmms::ProjectVersion Class Reference
lmms::ProjectVersion Class Reference
Version number parsing and comparison.
#include <ProjectVersion.h>
Public Types
enum class CompareType : int {
None = 0 ,
Major =1 ,
Minor =2 ,
Release =3 ,
Stage =4 ,
Build =5 ,
All = std::numeric_limits<int>::max()
}
Public Member Functions
ProjectVersion (const char *version, CompareType c=CompareType::All)
ProjectVersion (QString version, CompareType c=CompareType::All)
CompareType getCompareType () const
const QStringList & getLabels () const
int getMajor () const
int getMinor () const
int getPatch () const
const QString & getVersion () const
ProjectVersion setCompareType (CompareType compareType)
Static Public Member Functions
static int compare (const ProjectVersion &a, const ProjectVersion &b, CompareType c)
static int compare (ProjectVersion v1, ProjectVersion v2)
Private Attributes
CompareType m_compareType
QStringList m_labels
int m_major = 0
int m_minor = 0
int m_patch = 0
QString m_version
Detailed Description
Version number parsing and comparison.
Parses and compares version information. i.e. "1.0.3" < "1.0.10"
Definition at line 42 of file ProjectVersion.h.
Member Enumeration Documentation
CompareType
enum class lmms::ProjectVersion::CompareType : int strong
Enumerator
None
Major
Minor
Release
Stage
Build
All
Definition at line 45 of file ProjectVersion.h.
Constructor & Destructor Documentation
ProjectVersion() [1/2]
lmms::ProjectVersion::ProjectVersion (QString version, CompareType c = CompareType::All)
Definition at line 35 of file ProjectVersion.cpp.
References m_compareType, m_major, m_minor, m_patch, and m_version.
Referenced by ProjectVersion(), compare(), compare(), and setCompareType().
ProjectVersion() [2/2]
lmms::ProjectVersion::ProjectVersion (const char * version, CompareType c = CompareType::All)
Definition at line 73 of file ProjectVersion.cpp.
References ProjectVersion().
Member Function Documentation
compare() [1/2]
int lmms::ProjectVersion::compare (const ProjectVersion & a, const ProjectVersion & b, CompareType c) static
Parameters
c Determines the number of identifiers to check when comparing
Definition at line 81 of file ProjectVersion.cpp.
References ProjectVersion(), getLabels(), getMajor(), getMinor(), getPatch(), and i.
Referenced by compare(), lmms::operator!=(), lmms::operator<(), lmms::operator<=(), lmms::operator==(), lmms::operator>(), and lmms::operator>=().
compare() [2/2]
int lmms::ProjectVersion::compare (ProjectVersion v1, ProjectVersion v2) static
Definition at line 136 of file ProjectVersion.cpp.
References ProjectVersion(), compare(), and getCompareType().
getCompareType()
CompareType lmms::ProjectVersion::getCompareType () const inline
Definition at line 56 of file ProjectVersion.h.
References m_compareType.
Referenced by compare().
getLabels()
const QStringList & lmms::ProjectVersion::getLabels () const inline
Definition at line 55 of file ProjectVersion.h.
References m_labels.
Referenced by compare().
getMajor()
int lmms::ProjectVersion::getMajor () const inline
Definition at line 52 of file ProjectVersion.h.
References m_major.
Referenced by compare().
getMinor()
int lmms::ProjectVersion::getMinor () const inline
Definition at line 53 of file ProjectVersion.h.
References m_minor.
Referenced by compare().
getPatch()
int lmms::ProjectVersion::getPatch () const inline
Definition at line 54 of file ProjectVersion.h.
References m_patch.
Referenced by compare().
getVersion()
const QString & lmms::ProjectVersion::getVersion () const inline
Definition at line 51 of file ProjectVersion.h.
References m_version.
Referenced by lmms::DataFile::loadData().
setCompareType()
ProjectVersion lmms::ProjectVersion::setCompareType (CompareType compareType) inline
Definition at line 57 of file ProjectVersion.h.
References ProjectVersion(), and m_compareType.
Referenced by lmms::ConfigManager::legacyConfigVersion(), lmms::DataFile::loadData(), and lmms::ConfigManager::upgrade().
Member Data Documentation
m_compareType
CompareType lmms::ProjectVersion::m_compareType private
Definition at line 68 of file ProjectVersion.h.
Referenced by ProjectVersion(), getCompareType(), and setCompareType().
m_labels
QStringList lmms::ProjectVersion::m_labels private
Definition at line 67 of file ProjectVersion.h.
Referenced by getLabels().
m_major
int lmms::ProjectVersion::m_major = 0 private
Definition at line 64 of file ProjectVersion.h.
Referenced by ProjectVersion(), and getMajor().
m_minor
int lmms::ProjectVersion::m_minor = 0 private
Definition at line 65 of file ProjectVersion.h.
Referenced by ProjectVersion(), and getMinor().
m_patch
int lmms::ProjectVersion::m_patch = 0 private
Definition at line 66 of file ProjectVersion.h.
Referenced by ProjectVersion(), and getPatch().
m_version
QString lmms::ProjectVersion::m_version private
Definition at line 63 of file ProjectVersion.h.
Referenced by ProjectVersion(), and getVersion().
The documentation for this class was generated from the following files:
include/ProjectVersion.h
src/core/ProjectVersion.cpp