LMMS: _LADSPA_Descriptor Struct Reference
_LADSPA_Descriptor Struct Reference
#include <ladspa.h>
Public Attributes
void(* activate)(LADSPA_Handle Instance)
void(* cleanup)(LADSPA_Handle Instance)
void(* connect_port)(LADSPA_Handle Instance, unsigned long Port, LADSPA_Data *DataLocation)
const char * Copyright
void(* deactivate)(LADSPA_Handle Instance)
void * ImplementationData
LADSPA_Handle(* instantiate)(const struct _LADSPA_Descriptor *Descriptor, unsigned long SampleRate)
const char * Label
const char * Maker
const char * Name
unsigned long PortCount
const LADSPA_PortDescriptor * PortDescriptors
const char *const * PortNames
const LADSPA_PortRangeHint * PortRangeHints
LADSPA_Properties Properties
void(* run)(LADSPA_Handle Instance, unsigned long SampleCount)
void(* run_adding)(LADSPA_Handle Instance, unsigned long SampleCount)
void(* set_run_adding_gain)(LADSPA_Handle Instance, LADSPA_Data Gain)
unsigned long UniqueID
Detailed Description
Definition at line 373 of file ladspa.h.
Member Data Documentation
activate
void(* _LADSPA_Descriptor::activate) (LADSPA_Handle Instance)
Definition at line 489 of file ladspa.h.
Referenced by lmms::LadspaManager::activate().
cleanup
void(* _LADSPA_Descriptor::cleanup) (LADSPA_Handle Instance)
Definition at line 558 of file ladspa.h.
Referenced by lmms::LadspaManager::cleanup().
connect_port
void(* _LADSPA_Descriptor::connect_port) (LADSPA_Handle Instance, unsigned long Port, LADSPA_Data *DataLocation)
Definition at line 466 of file ladspa.h.
Referenced by lmms::LadspaManager::connectPort().
Copyright
const char* _LADSPA_Descriptor::Copyright
Definition at line 402 of file ladspa.h.
Referenced by lmms::LadspaManager::getCopyright().
deactivate
void(* _LADSPA_Descriptor::deactivate) (LADSPA_Handle Instance)
Definition at line 549 of file ladspa.h.
Referenced by lmms::LadspaManager::deactivate().
ImplementationData
void* _LADSPA_Descriptor::ImplementationData
Definition at line 426 of file ladspa.h.
Referenced by lmms::LadspaManager::getImplementationData().
instantiate
LADSPA_Handle(* _LADSPA_Descriptor::instantiate) (const struct _LADSPA_Descriptor *Descriptor, unsigned long SampleRate)
Definition at line 437 of file ladspa.h.
Referenced by lmms::LadspaManager::instantiate().
Label
const char* _LADSPA_Descriptor::Label
Definition at line 386 of file ladspa.h.
Referenced by lmms::LadspaManager::getLabel().
Maker
const char* _LADSPA_Descriptor::Maker
Definition at line 397 of file ladspa.h.
Referenced by lmms::LadspaManager::getMaker().
Name
const char* _LADSPA_Descriptor::Name
Definition at line 393 of file ladspa.h.
Referenced by lmms::LadspaManager::getName().
PortCount
unsigned long _LADSPA_Descriptor::PortCount
Definition at line 406 of file ladspa.h.
Referenced by lmms::LadspaManager::getPluginInputs(), lmms::LadspaManager::getPluginOutputs(), and lmms::LadspaManager::getPortCount().
PortDescriptors
const LADSPA_PortDescriptor* _LADSPA_Descriptor::PortDescriptors
Definition at line 410 of file ladspa.h.
Referenced by lmms::LadspaManager::getPluginInputs(), lmms::LadspaManager::getPluginOutputs(), and lmms::LadspaManager::getPortDescriptor().
PortNames
const char* const* _LADSPA_Descriptor::PortNames
Definition at line 415 of file ladspa.h.
Referenced by lmms::LadspaManager::getPluginInputs(), lmms::LadspaManager::getPluginOutputs(), and lmms::LadspaManager::getPortName().
PortRangeHints
const LADSPA_PortRangeHint* _LADSPA_Descriptor::PortRangeHints
Definition at line 419 of file ladspa.h.
Referenced by lmms::LadspaManager::getPortRangeHint().
Properties
LADSPA_Properties _LADSPA_Descriptor::Properties
Definition at line 389 of file ladspa.h.
Referenced by lmms::LadspaManager::hasRealTimeDependency(), lmms::LadspaManager::isInplaceBroken(), and lmms::LadspaManager::isRealTimeCapable().
run
void(* _LADSPA_Descriptor::run) (LADSPA_Handle Instance, unsigned long SampleCount)
Definition at line 505 of file ladspa.h.
Referenced by lmms::LadspaManager::run().
run_adding
void(* _LADSPA_Descriptor::run_adding) (LADSPA_Handle Instance, unsigned long SampleCount)
Definition at line 521 of file ladspa.h.
Referenced by lmms::LadspaManager::runAdding(), and lmms::LadspaManager::setRunAddingGain().
set_run_adding_gain
void(* _LADSPA_Descriptor::set_run_adding_gain) (LADSPA_Handle Instance, LADSPA_Data Gain)
Definition at line 533 of file ladspa.h.
Referenced by lmms::LadspaManager::runAdding(), and lmms::LadspaManager::setRunAddingGain().
UniqueID
unsigned long _LADSPA_Descriptor::UniqueID
Definition at line 379 of file ladspa.h.
The documentation for this struct was generated from the following file:
include/ladspa.h