LMMS: src/3rdparty/qt5-x11embed/src/X11EmbedContainer.cpp File Reference
X11EmbedContainer.cpp File Reference
#include "X11EmbedContainer.h"
#include <QAbstractNativeEventFilter>
#include <qcoreapplication.h>
#include <qevent.h>
#include <qpainter.h>
#include <qelapsedtimer.h>
#include <qpointer.h>
#include <qdebug.h>
#include <QtX11Extras/QX11Info>
#include <QThread>
#include <QtCore/QMutex>
#include <QtCore/private/qobject_p.h>
#include <QtWidgets/private/qwidget_p.h>
#include <QtGui/private/qguiapplication_p.h>
#include <QWindow>
#include <QGuiApplication>
#include <qpa/qplatformintegration.h>
#include <queue>
#include <cstring>
#include <X11/Xlib-xcb.h>
#include <X11/Xutil.h>
#include <xcb/xcb.h>
#include <xcb/xcb_atom.h>
#include <xcb/xcb_util.h>
#include <xcb/xcb_keysyms.h>
#include <xcb/xproto.h>
Classes
class QHackWidget
class QX11EmbedContainerPrivate
class X11EventFilter
struct xembed_info
Macros
#define None 0
#define XK_ISO_Left_Tab 0xFE20
#define XK_LATIN1
#define XK_MISCELLANY
Enumerations
enum ATOM_ID : int {
_XEMBED ,
_XEMBED_INFO ,
WM_PROTOCOLS ,
WM_DELETE_WINDOW ,
WM_STATE
}
enum QX11EmbedAccelFlags { XEMBED_ACCELERATOR_OVERLOADED = (1 << 0) }
enum QX11EmbedAccelModifiers {
XEMBED_MODIFIER_SHIFT = (1 << 0) ,
XEMBED_MODIFIER_CONTROL = (1 << 1) ,
XEMBED_MODIFIER_ALT = (1 << 2) ,
XEMBED_MODIFIER_SUPER = (1 << 3) ,
XEMBED_MODIFIER_HYPER = (1 << 4)
}
enum QX11EmbedFocusInDetail {
XEMBED_FOCUS_CURRENT = 0 ,
XEMBED_FOCUS_FIRST = 1 ,
XEMBED_FOCUS_LAST = 2
}
enum QX11EmbedFocusInFlags {
XEMBED_FOCUS_OTHER = (0 << 0) ,
XEMBED_FOCUS_WRAPAROUND = (1 << 0)
}
enum QX11EmbedInfoFlags { XEMBED_MAPPED = (1 << 0) }
enum QX11EmbedMessageType {
XEMBED_EMBEDDED_NOTIFY = 0 ,
XEMBED_WINDOW_ACTIVATE = 1 ,
XEMBED_WINDOW_DEACTIVATE = 2 ,
XEMBED_REQUEST_FOCUS = 3 ,
XEMBED_FOCUS_IN = 4 ,
XEMBED_FOCUS_OUT = 5 ,
XEMBED_FOCUS_NEXT = 6 ,
XEMBED_FOCUS_PREV = 7 ,
XEMBED_MODALITY_ON = 10 ,
XEMBED_MODALITY_OFF = 11 ,
XEMBED_REGISTER_ACCELERATOR = 12 ,
XEMBED_UNREGISTER_ACCELERATOR = 13 ,
XEMBED_ACTIVATE_ACCELERATOR = 14
}
Functions
xcb_atom_t ATOM (int atomID)
static const std::vector< std::pair< int, std::string > > atom_list ({ {_XEMBED, "_XEMBED"}, {_XEMBED_INFO, "_XEMBED_INFO"}, {WM_PROTOCOLS, "WM_PROTOCOLS"}, {WM_DELETE_WINDOW, "WM_DELETE_WINDOW"}, {WM_STATE, "WM_STATE"}, })
xembed_info * get_xembed_info (xcb_window_t window)
void initAtoms ()
static void sendXEmbedMessage (WId window, long message, long detail=0, long data1=0, long data2=0)
static xcb_timestamp_t x11Time ()
Variables
static QMap< int, xcb_atom_t > atoms
static QMutex atoms_lock
static xcb_key_press_event_t lastKeyEvent
X11EventFilter x11EventFilter
static unsigned int XEMBED_VERSION = 0
static const int XRevertToParent = RevertToParent
Macro Definition Documentation
None
#define None 0
Definition at line 54 of file X11EmbedContainer.cpp.
Referenced by lmms::gui::AutomationEditor::AutomationEditor(), lmms::gui::ClipView::ClipView(), lmms::gui::PianoRoll::PianoRoll(), lmms::Song::Song(), lmms::TempoSyncKnobModel::TempoSyncKnobModel(), lmms::gui::TrackView::TrackView(), QX11EmbedContainerPrivate::checkGrab(), dither_opt(), and driver_initialize().
XK_ISO_Left_Tab
#define XK_ISO_Left_Tab 0xFE20
Definition at line 64 of file X11EmbedContainer.cpp.
XK_LATIN1
#define XK_LATIN1
Definition at line 53 of file X11EmbedContainer.cpp.
XK_MISCELLANY
#define XK_MISCELLANY
Definition at line 52 of file X11EmbedContainer.cpp.
Enumeration Type Documentation
ATOM_ID
enum ATOM_ID : int
Enumerator
_XEMBED
_XEMBED_INFO
WM_PROTOCOLS
WM_DELETE_WINDOW
WM_STATE
Definition at line 174 of file X11EmbedContainer.cpp.
QX11EmbedAccelFlags
enum QX11EmbedAccelFlags
Enumerator
XEMBED_ACCELERATOR_OVERLOADED
Definition at line 305 of file X11EmbedContainer.cpp.
QX11EmbedAccelModifiers
enum QX11EmbedAccelModifiers
Enumerator
XEMBED_MODIFIER_SHIFT
XEMBED_MODIFIER_CONTROL
XEMBED_MODIFIER_ALT
XEMBED_MODIFIER_SUPER
XEMBED_MODIFIER_HYPER
Definition at line 297 of file X11EmbedContainer.cpp.
QX11EmbedFocusInDetail
enum QX11EmbedFocusInDetail
Enumerator
XEMBED_FOCUS_CURRENT
XEMBED_FOCUS_FIRST
XEMBED_FOCUS_LAST
Definition at line 282 of file X11EmbedContainer.cpp.
QX11EmbedFocusInFlags
enum QX11EmbedFocusInFlags
Enumerator
XEMBED_FOCUS_OTHER
XEMBED_FOCUS_WRAPAROUND
Definition at line 288 of file X11EmbedContainer.cpp.
QX11EmbedInfoFlags
enum QX11EmbedInfoFlags
Enumerator
XEMBED_MAPPED
Definition at line 293 of file X11EmbedContainer.cpp.
QX11EmbedMessageType
enum QX11EmbedMessageType
Enumerator
XEMBED_EMBEDDED_NOTIFY
XEMBED_WINDOW_ACTIVATE
XEMBED_WINDOW_DEACTIVATE
XEMBED_REQUEST_FOCUS
XEMBED_FOCUS_IN
XEMBED_FOCUS_OUT
XEMBED_FOCUS_NEXT
XEMBED_FOCUS_PREV
XEMBED_MODALITY_ON
XEMBED_MODALITY_OFF
XEMBED_REGISTER_ACCELERATOR
XEMBED_UNREGISTER_ACCELERATOR
XEMBED_ACTIVATE_ACCELERATOR
Definition at line 266 of file X11EmbedContainer.cpp.
Function Documentation
ATOM()
xcb_atom_t ATOM (int atomID)
Definition at line 222 of file X11EmbedContainer.cpp.
References atoms.
Referenced by get_xembed_info(), and sendXEmbedMessage().
atom_list()
const std::vector< std::pair< int, std::string > > atom_list ({ {_XEMBED, "_XEMBED"}, {_XEMBED_INFO, "_XEMBED_INFO"}, {WM_PROTOCOLS, "WM_PROTOCOLS"}, {WM_DELETE_WINDOW, "WM_DELETE_WINDOW"}, {WM_STATE, "WM_STATE"}, }) static
References _XEMBED, _XEMBED_INFO, WM_DELETE_WINDOW, WM_PROTOCOLS, and WM_STATE.
Referenced by initAtoms().
get_xembed_info()
xembed_info * get_xembed_info (xcb_window_t window)
Definition at line 234 of file X11EmbedContainer.cpp.
References _XEMBED_INFO, and ATOM().
Referenced by QX11EmbedContainerPrivate::acceptClient().
initAtoms()
void initAtoms ()
Definition at line 193 of file X11EmbedContainer.cpp.
References atom_list(), atoms, and atoms_lock.
sendXEmbedMessage()
void sendXEmbedMessage (WId window, long message, long detail = 0, long data1 = 0, long data2 = 0) static
Definition at line 324 of file X11EmbedContainer.cpp.
References _XEMBED, ATOM(), and x11Time().
Referenced by QX11EmbedContainerPrivate::acceptClient().
x11Time()
xcb_timestamp_t x11Time () static
Definition at line 317 of file X11EmbedContainer.cpp.
Referenced by sendXEmbedMessage().
Variable Documentation
atoms
QMap<int, xcb_atom_t> atoms static
Definition at line 190 of file X11EmbedContainer.cpp.
Referenced by ATOM(), and initAtoms().
atoms_lock
QMutex atoms_lock static
Definition at line 191 of file X11EmbedContainer.cpp.
Referenced by initAtoms().
lastKeyEvent
xcb_key_press_event_t lastKeyEvent static
Definition at line 350 of file X11EmbedContainer.cpp.
Referenced by X11EventFilter::nativeEventFilter().
x11EventFilter
X11EventFilter x11EventFilter
XEMBED_VERSION
unsigned int XEMBED_VERSION = 0 static
Definition at line 264 of file X11EmbedContainer.cpp.
Referenced by QX11EmbedContainerPrivate::acceptClient().
XRevertToParent
const int XRevertToParent = RevertToParent static
Definition at line 169 of file X11EmbedContainer.cpp.
Referenced by QX11EmbedContainerPrivate::moveInputToProxy().