LMMS: Jack::JackInternalClientUnloadResult Struct Reference
Jack::JackInternalClientUnloadResult Struct Reference
InternalClientLoad result.
#include <JackRequest.h>
Public Member Functions
JackInternalClientUnloadResult ()
JackInternalClientUnloadResult (int32_t result, int status)
int Read (detail::JackChannelTransactionInterface *trans)
int Size ()
int Write (detail::JackChannelTransactionInterface *trans)
Public Member Functions inherited from Jack::JackResult
JackResult ()
JackResult (int result)
virtual ~JackResult ()
Public Attributes
int fStatus
Public Attributes inherited from Jack::JackResult
int fResult
Detailed Description
InternalClientLoad result.
Definition at line 1185 of file JackRequest.h.
Constructor & Destructor Documentation
JackInternalClientUnloadResult() [1/2]
Jack::JackInternalClientUnloadResult::JackInternalClientUnloadResult () inline
Definition at line 1190 of file JackRequest.h.
References Jack::JackResult::JackResult(), and fStatus.
JackInternalClientUnloadResult() [2/2]
Jack::JackInternalClientUnloadResult::JackInternalClientUnloadResult (int32_t result, int status) inline
Definition at line 1192 of file JackRequest.h.
References Jack::JackResult::JackResult(), and fStatus.
Member Function Documentation
Read()
int Jack::JackInternalClientUnloadResult::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 1196 of file JackRequest.h.
References CheckRes, fStatus, Jack::detail::JackChannelTransactionInterface::Read(), and Jack::JackResult::Read().
Size()
int Jack::JackInternalClientUnloadResult::Size () inline
Definition at line 1210 of file JackRequest.h.
Write()
int Jack::JackInternalClientUnloadResult::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 1203 of file JackRequest.h.
References CheckRes, fStatus, Jack::detail::JackChannelTransactionInterface::Write(), and Jack::JackResult::Write().
Member Data Documentation
fStatus
int Jack::JackInternalClientUnloadResult::fStatus
Definition at line 1188 of file JackRequest.h.
Referenced by JackInternalClientUnloadResult(), JackInternalClientUnloadResult(), Jack::JackRequestDecoder::HandleRequest(), Jack::JackGenericClientChannel::InternalClientUnload(), Read(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h