LMMS: lmms::gui::PatternClipView Class Reference
lmms::gui::PatternClipView Class Reference
#include <PatternClipView.h>
Public Slots
void update () override
Public Slots inherited from lmms::gui::ClipView
virtual bool close ()
Close a ClipView.
void randomizeColor ()
void remove ()
Removes a ClipView from its track view.
void resetColor ()
void selectColor ()
void update () override
Update a ClipView.
Public Slots inherited from lmms::gui::selectableObject
virtual void update ()
Public Member Functions
PatternClipView (Clip *clip, TrackView *tv)
~PatternClipView () override=default
Public Member Functions inherited from lmms::gui::ClipView
ClipView (Clip *clip, TrackView *tv)
Create a new ClipView.
~ClipView () override
Destroy a ClipView.
void copy (QVector< ClipView * > clipvs)
void cut (QVector< ClipView * > clipvs)
bool fixedClips ()
Does this ClipView have a fixed Clip?
QVector< ClipView * > getClickedClips ()
Clip * getClip ()
QColor getColorForDisplay (QColor)
TrackView * getTrackView ()
bool gradient () const
QColor markerColor () const
QColor mutedBackgroundColor () const
QColor mutedColor () const
CSS theming qproperty access method.
bool needsUpdate ()
void paste ()
QColor patternClipBackground () const
QColor selectedColor () const
void setGradient (const bool &b)
void setMarkerColor (const QColor &c)
void setMarkerEnabled (bool e)
void setMarkerPos (int x)
void setMutedBackgroundColor (const QColor &c)
void setMutedColor (const QColor &c)
CSS theming qproperty access method.
void setNeedsUpdate (bool b)
void setPatternClipBackground (const QColor &c)
void setSelectedColor (const QColor &c)
void setTextBackgroundColor (const QColor &c)
void setTextColor (const QColor &c)
void setTextShadowColor (const QColor &c)
QColor textBackgroundColor () const
QColor textColor () const
QColor textShadowColor () const
void toggleSelectedAutoResize ()
Public Member Functions inherited from lmms::gui::selectableObject
selectableObject (QWidget *_parent)
~selectableObject () override=default
bool isSelected () const
void setSelected (bool selected)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Slots
void changeName ()
void openInPatternEditor ()
void resetName ()
Protected Slots inherited from lmms::gui::ClipView
void updateLength ()
Updates a ClipView's length.
void updatePosition ()
Updates a ClipView's position.
Protected Member Functions
void constructContextMenu (QMenu *) override
void mouseDoubleClickEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *pe) override
Protected Member Functions inherited from lmms::gui::ClipView
void contextMenuAction (ContextMenuAction action)
void contextMenuEvent (QContextMenuEvent *cme) override
Set up the context menu for this ClipView.
DataFile createClipDataFiles (const QVector< ClipView * > &clips) const
Create a DataFile suitable for copying multiple clips.
void dragEnterEvent (QDragEnterEvent *dee) override
Change the ClipView's display when something being dragged enters it.
void dropEvent (QDropEvent *de) override
Handle something being dropped on this ClipObjectView.
auto hasCustomColor () const -> bool
void mouseMoveEvent (QMouseEvent *me) override
Handle a mouse movement (drag) on this ClipView.
void mousePressEvent (QMouseEvent *me) override
Handle a mouse press on this ClipView.
void mouseReleaseEvent (QMouseEvent *me) override
Handle a mouse release on this ClipView.
virtual void paintTextLabel (QString const &text, QPainter &painter)
float pixelsPerBar ()
How many pixels a bar takes for this ClipView.
TimePos quantizeSplitPos (TimePos)
void resizeEvent (QResizeEvent *re) override
bool unquantizedModHeld (QMouseEvent *me)
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Private Attributes
QPixmap m_paintPixmap
PatternClip * m_patternClip
QStaticText m_staticTextName
Additional Inherited Members
Static Public Member Functions inherited from lmms::gui::ClipView
static void remove (QVector< ClipView * > clipvs)
static void toggleMute (QVector< ClipView * > clipvs)
Static Public Attributes inherited from lmms::gui::ClipView
static const int BORDER_WIDTH = 2
Protected Types inherited from lmms::gui::ClipView
enum class ContextMenuAction {
Remove ,
Cut ,
Copy ,
Paste ,
Mute
}
Protected Attributes inherited from lmms::gui::ClipView
TimePos m_initialClipEnd
TimePos m_initialClipPos
bool m_marker = false
int m_markerPos = 0
TrackView * m_trackView
Properties inherited from lmms::gui::ClipView
bool gradient
QColor markerColor
QColor mutedBackgroundColor
QColor mutedColor
QColor patternClipBackground
QColor selectedColor
QColor textBackgroundColor
QColor textColor
QColor textShadowColor
Detailed Description
Definition at line 40 of file PatternClipView.h.
Constructor & Destructor Documentation
PatternClipView()
lmms::gui::PatternClipView::PatternClipView (Clip * clip, TrackView * tv)
Definition at line 44 of file PatternClipView.cpp.
References lmms::gui::ClipView::ClipView(), lmms::Clip::getTrack(), m_paintPixmap, m_patternClip, and update().
~PatternClipView()
lmms::gui::PatternClipView::~PatternClipView () override default
Member Function Documentation
changeName
void lmms::gui::PatternClipView::changeName () protected slot
Definition at line 191 of file PatternClipView.cpp.
References m_patternClip.
Referenced by constructContextMenu().
constructContextMenu()
void lmms::gui::PatternClipView::constructContextMenu (QMenu * _cm) override protected virtual
Reimplemented from lmms::gui::ClipView.
Definition at line 55 of file PatternClipView.cpp.
References changeName(), lmms::embed::getIconPixmap(), openInPatternEditor(), and resetName().
mouseDoubleClickEvent()
void lmms::gui::PatternClipView::mouseDoubleClickEvent (QMouseEvent * _me) override protected
Definition at line 73 of file PatternClipView.cpp.
References lmms::gui::ClipView::m_trackView, and openInPatternEditor().
openInPatternEditor
void lmms::gui::PatternClipView::openInPatternEditor () protected slot
Definition at line 176 of file PatternClipView.cpp.
References lmms::gui::getGUI(), m_patternClip, lmms::gui::GuiApplication::mainWindow(), lmms::Engine::patternStore(), and lmms::gui::MainWindow::togglePatternEditorWin().
Referenced by constructContextMenu(), and mouseDoubleClickEvent().
paintEvent()
void lmms::gui::PatternClipView::paintEvent (QPaintEvent * pe) override protected
Definition at line 83 of file PatternClipView.cpp.
References lmms::gui::ClipView::BORDER_WIDTH, lmms::gui::ClipView::getColorForDisplay(), lmms::embed::getIconPixmap(), lmms::gui::ClipView::gradient, lmms::PatternStore::lengthOfPattern(), lmms::gui::ClipView::m_marker, lmms::gui::ClipView::m_markerPos, m_paintPixmap, m_patternClip, lmms::gui::ClipView::markerColor, lmms::gui::ClipView::needsUpdate(), lmms::gui::ClipView::paintTextLabel(), lmms::Engine::patternStore(), lmms::gui::ClipView::pixelsPerBar(), lmms::gui::ClipView::setNeedsUpdate(), and lmms::TimePos::ticksPerBar().
resetName
void lmms::gui::PatternClipView::resetName () protected slot
Definition at line 186 of file PatternClipView.cpp.
References m_patternClip.
Referenced by constructContextMenu().
update
void lmms::gui::PatternClipView::update () override slot
Definition at line 201 of file PatternClipView.cpp.
References m_patternClip, and lmms::gui::ClipView::update().
Referenced by PatternClipView().
Member Data Documentation
m_paintPixmap
QPixmap lmms::gui::PatternClipView::m_paintPixmap private
Definition at line 65 of file PatternClipView.h.
Referenced by PatternClipView(), and paintEvent().
m_patternClip
PatternClip* lmms::gui::PatternClipView::m_patternClip private
Definition at line 64 of file PatternClipView.h.
Referenced by PatternClipView(), changeName(), openInPatternEditor(), paintEvent(), resetName(), and update().
m_staticTextName
QStaticText lmms::gui::PatternClipView::m_staticTextName private
Definition at line 67 of file PatternClipView.h.
The documentation for this class was generated from the following files:
include/PatternClipView.h
src/gui/clips/PatternClipView.cpp