LMMS: src/3rdparty/jack2/common/JackDriverLoader.h File Reference
JackDriverLoader.h File Reference
#include "driver_interface.h"
#include "JackControlAPI.h"
#include "JackPlatformPlug.h"
Functions
JSList * jack_drivers_load (JSList *drivers)
jack_driver_desc_t * jack_find_driver_descriptor (JSList *drivers, const char *name)
void jack_free_driver_params (JSList *param_ptr)
JSList * jack_internals_load (JSList *internals)
void jack_print_driver_options (jack_driver_desc_t *desc, FILE *file)
SERVER_EXPORT int jackctl_driver_params_parse (jackctl_driver *driver, int argc, char *argv[])
Call this function to parse parameters for a driver.
Function Documentation
jack_drivers_load()
JSList * jack_drivers_load (JSList * drivers)
Definition at line 562 of file JackDriverLoader.cpp.
References ADDON_DIR, check_symbol(), jack_error, jack_get_descriptor(), and jack_slist_append().
Referenced by Jack::JackServerGlobals::Init(), and jackctl_drivers_load().
jack_find_driver_descriptor()
jack_driver_desc_t * jack_find_driver_descriptor (JSList * drivers, const char * name)
Definition at line 403 of file JackDriverLoader.cpp.
References _JSList::data, jack_slist_next, and jack_driver_desc_t::name.
Referenced by Jack::JackServerGlobals::Init().
jack_free_driver_params()
void jack_free_driver_params (JSList * param_ptr)
Definition at line 130 of file JackDriverLoader.cpp.
References _JSList::data, and _JSList::next.
Referenced by Jack::JackServerGlobals::Init().
jack_internals_load()
JSList * jack_internals_load (JSList * internals)
Definition at line 687 of file JackDriverLoader.cpp.
References ADDON_DIR, check_symbol(), jack_error, jack_get_descriptor(), and jack_slist_append().
Referenced by jackctl_internals_load().
jack_print_driver_options()
void jack_print_driver_options (jack_driver_desc_t * desc, FILE * file)
Definition at line 87 of file JackDriverLoader.cpp.
References jack_driver_param_value_t::c, jack_driver_param_desc_t::character, file, i, jack_driver_param_value_t::i, JACK_DRIVER_PARAM_STRING_MAX, JackDriverParamBool, JackDriverParamChar, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, jack_driver_param_desc_t::long_desc, jack_driver_param_desc_t::name, jack_driver_desc_t::nparams, jack_driver_desc_t::params, jack_driver_param_value_t::str, jack_driver_param_desc_t::type, jack_driver_param_value_t::ui, and jack_driver_param_desc_t::value.
Referenced by jack_parse_driver_params(), jackctl_driver_params_parse(), and Jack::JackArgParser::ParseParams().