LMMS: lmms::PatternClip Class Reference
lmms::PatternClip Class Reference
Dummy clip for PatternTracks.
#include <PatternClip.h>
Public Member Functions
PatternClip (Track *track)
~PatternClip () override=default
PatternClip * clone () override
Creates a copy of this clip.
gui::ClipView * createView (gui::TrackView *_tv) override
void loadSettings (const QDomElement &_this) override
QString nodeName () const override
int patternIndex ()
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
Public Member Functions inherited from lmms::Clip
Clip (Track *track)
Create a new Clip.
~Clip () override
Destroy a Clip.
virtual void changeLength (const TimePos &length)
Change the length of this Clip.
auto color () const -> const std::optional< QColor > &
QString displayName () const override
TimePos endPosition () const
bool getAutoResize () const
bool getSelectViewOnCreate ()
Track * getTrack () const
bool hasTrackContainer () const
bool isInPattern () const
const TimePos & length () const
bool manuallyResizable () const
virtual void movePosition (const TimePos &pos)
Move this Clip's position in time.
const QString & name () const
void selectViewOnCreate (bool select)
void setAutoResize (const bool r)
Set whether a clip has been resized yet by the user or the knife tool.
void setColor (const std::optional< QColor > &color)
void setName (const QString &name)
void setStartTimeOffset (const TimePos &startTimeOffset)
const TimePos & startPosition () const
TimePos startTimeOffset () const
virtual void updateLength ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Friends
class PatternClipView
Additional Inherited Members
Public Slots inherited from lmms::Clip
void toggleMute ()
Mutes this Clip.
Signals inherited from lmms::Clip
void colorChanged ()
void destroyedClip ()
void lengthChanged ()
void positionChanged ()
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Static Public Member Functions inherited from lmms::Clip
static bool comparePosition (const Clip *a, const Clip *b)
Returns true if and only if a->startPosition() < b->startPosition().
static void copyStateTo (Clip *src, Clip *dst)
Copies the state of a Clip to another Clip.
Protected Member Functions inherited from lmms::Clip
Clip (const Clip &other)
Copy a Clip.
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Dummy clip for PatternTracks.
Only used in the Song (Editor). See PatternStore.h for more info.
Definition at line 37 of file PatternClip.h.
Constructor & Destructor Documentation
PatternClip()
lmms::PatternClip::PatternClip (Track * track)
Definition at line 38 of file PatternClip.cpp.
References lmms::Clip::Clip(), lmms::Clip::changeLength(), lmms::PatternStore::lengthOfPattern(), patternIndex(), lmms::Engine::patternStore(), lmms::JournallingObject::restoreJournallingState(), and lmms::JournallingObject::saveJournallingState().
Referenced by clone().
~PatternClip()
lmms::PatternClip::~PatternClip () override default
Member Function Documentation
clone()
PatternClip * lmms::PatternClip::clone () inline override virtual
Creates a copy of this clip.
Returns
pointer to the new clip object
Implements lmms::Clip.
Definition at line 54 of file PatternClip.h.
References PatternClip().
createView()
gui::ClipView * lmms::PatternClip::createView (gui::TrackView * _tv) override virtual
Implements lmms::Clip.
Definition at line 113 of file PatternClip.cpp.
loadSettings()
void lmms::PatternClip::loadSettings (const QDomElement & _this) override virtual
Implements lmms::SerializingObject.
Definition at line 74 of file PatternClip.cpp.
References lmms::Clip::changeLength(), lmms::Clip::movePosition(), lmms::Clip::setAutoResize(), lmms::Clip::setColor(), lmms::Clip::setName(), lmms::Clip::setStartTimeOffset(), and lmms::Clip::toggleMute().
nodeName()
QString lmms::PatternClip::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 45 of file PatternClip.h.
patternIndex()
int lmms::PatternClip::patternIndex ()
Definition at line 106 of file PatternClip.cpp.
References lmms::Clip::getTrack(), and patternIndex().
Referenced by PatternClip(), and patternIndex().
saveSettings()
void lmms::PatternClip::saveSettings (QDomDocument & _doc, QDomElement & _parent) override virtual
Implements lmms::SerializingObject.
Definition at line 50 of file PatternClip.cpp.
References lmms::Clip::color(), lmms::Clip::getAutoResize(), lmms::Clip::length(), lmms::Clip::name(), lmms::Clip::startPosition(), and lmms::Clip::startTimeOffset().
Friends And Related Symbol Documentation
PatternClipView
friend class PatternClipView friend
Definition at line 60 of file PatternClip.h.
References PatternClipView.
Referenced by PatternClipView.
The documentation for this class was generated from the following files:
include/PatternClip.h
src/core/PatternClip.cpp