LMMS: Jack::JackServerGlobals Struct Reference
Jack::JackServerGlobals Struct Reference
Global server static structure: singleton kind of pattern.
#include <JackServerGlobals.h>
Public Member Functions
JackServerGlobals ()
~JackServerGlobals ()
Static Public Member Functions
static void Delete ()
static void Destroy ()
static bool Init ()
static int Start (const char *server_name, jack_driver_desc_t *driver_desc, JSList *driver_params, int sync, int temporary, int time_out_ms, int rt, int priority, int port_max, int verbose, jack_timer_type_t clock, char self_connect_mode)
static void Stop ()
Static Public Attributes
static JackServer * fInstance
static std::map< std::string, int > fInternalsList
static std::map< std::string, JackDriverInfo * > fSlavesList
static unsigned int fUserCount
static bool(* on_device_acquire)(const char *device_name) = NULL
static void(* on_device_release)(const char *device_name) = NULL
static void(* on_device_reservation_loop)(void) = NULL
Detailed Description
Global server static structure: singleton kind of pattern.
Definition at line 38 of file JackServerGlobals.h.
Constructor & Destructor Documentation
JackServerGlobals()
Jack::JackServerGlobals::JackServerGlobals ()
~JackServerGlobals()
Jack::JackServerGlobals::~JackServerGlobals ()
References Delete(), Destroy(), Init(), server_name, Start(), and Stop().
Member Function Documentation
Delete()
void Jack::JackServerGlobals::Delete () static
Definition at line 67 of file JackServerGlobals.cpp.
References fInstance, fInternalsList, fSlavesList, and jack_log().
Referenced by ~JackServerGlobals(), Destroy(), and Init().
Destroy()
void Jack::JackServerGlobals::Destroy () static
Definition at line 407 of file JackServerGlobals.cpp.
References Jack::JackTools::CleanupFiles(), Delete(), fUserCount, jack_cleanup_shm(), jack_log(), jack_unregister_server(), server_name, and Stop().
Referenced by ~JackServerGlobals(), Init(), jack_client_close(), jack_client_new_aux(), and jack_client_open_aux().
Init()
bool Jack::JackServerGlobals::Init () static
Definition at line 98 of file JackServerGlobals.cpp.
References Jack::JackTools::CleanupFiles(), Jack::JackTools::DefaultServerName(), Delete(), Destroy(), fInstance, fInternalsList, fSlavesList, fUserCount, getopt_long(), i, jack_cleanup_shm(), JACK_DEFAULT_SELF_CONNECT_MODE, jack_drivers_load(), jack_error, jack_find_driver_descriptor(), jack_free_driver_params(), jack_info(), jack_log(), jack_parse_driver_params(), jack_register_server(), JACK_TIMER_HPET, JACK_TIMER_SYSTEM_CLOCK, jack_unregister_server(), JackNullOption, optarg, opterr, optind, optopt, server_name, and Start().
Referenced by ~JackServerGlobals(), jack_client_new_aux(), and jack_client_open_aux().
Start()
int Jack::JackServerGlobals::Start (const char * server_name, jack_driver_desc_t * driver_desc, JSList * driver_params, int sync, int temporary, int time_out_ms, int rt, int priority, int port_max, int verbose, jack_timer_type_t clock, char self_connect_mode) static
Definition at line 41 of file JackServerGlobals.cpp.
References fInstance, jack_log(), and server_name.
Referenced by ~JackServerGlobals(), and Init().
Stop()
void Jack::JackServerGlobals::Stop () static
Definition at line 60 of file JackServerGlobals.cpp.
References fInstance, and jack_log().
Referenced by ~JackServerGlobals(), and Destroy().
Member Data Documentation
fInstance
JackServer * Jack::JackServerGlobals::fInstance static
Definition at line 40 of file JackServerGlobals.h.
Referenced by Jack::JackProfilerClient::JackProfilerClient(), Jack::JackServer::JackServer(), Delete(), Jack::GetEngineControl(), Jack::GetGraphManager(), Jack::GetMetadata(), Jack::GetSynchroTable(), Init(), Jack::JackServer::InternalClientLoad1(), Jack::JackServer::InternalClientLoad2(), jack_client_new_aux(), jack_client_open_aux(), jack_get_client_pid(), Jack::JackOSSAdapter::Open(), Jack::JackNetMaster::Process(), Jack::JackProfiler::Process(), Start(), and Stop().
fInternalsList
std::map< std::string, int > Jack::JackServerGlobals::fInternalsList static
Definition at line 43 of file JackServerGlobals.h.
Referenced by Delete(), and Init().
fSlavesList
std::map< std::string, JackDriverInfo * > Jack::JackServerGlobals::fSlavesList static
Definition at line 42 of file JackServerGlobals.h.
Referenced by Delete(), and Init().
fUserCount
unsigned int Jack::JackServerGlobals::fUserCount static
Definition at line 41 of file JackServerGlobals.h.
Referenced by Jack::JackServer::JackServer(), Destroy(), and Init().
on_device_acquire
bool(* Jack::JackServerGlobals::on_device_acquire)(const char *device_name) = NULL static
Definition at line 45 of file JackServerGlobals.h.
Referenced by jackctl_server_create2(), Jack::JackAlsaDriver::Open(), and Jack::JackPortAudioDriver::Open().
on_device_release
void(* Jack::JackServerGlobals::on_device_release)(const char *device_name) = NULL static
Definition at line 46 of file JackServerGlobals.h.
Referenced by Jack::JackAlsaDriver::Close(), Jack::JackPortAudioDriver::Close(), jackctl_server_create2(), and Jack::JackAlsaDriver::Open().
on_device_reservation_loop
void(* Jack::JackServerGlobals::on_device_reservation_loop)(void) (void) = NULL static
Definition at line 47 of file JackServerGlobals.h.
Referenced by jackctl_server_create2(), Jack::on_device_reservation_loop(), Jack::JackAlsaDriver::Open(), and Jack::JackPortAudioDriver::Open().
The documentation for this struct was generated from the following files:
src/3rdparty/jack2/common/JackServerGlobals.h
src/3rdparty/jack2/common/JackServerGlobals.cpp