LMMS: lmms::TempoSyncKnobModel Class Reference
lmms::TempoSyncKnobModel Class Reference
#include <TempoSyncKnobModel.h>
Public Types
enum class SyncMode {
None ,
DoubleWholeNote ,
WholeNote ,
HalfNote ,
QuarterNote ,
EighthNote ,
SixteenthNote ,
ThirtysecondNote ,
Custom
}
Public Types inherited from lmms::AutomatableModel
using AutoModelVector = std::vector<AutomatableModel*>
enum class ScaleType {
Linear ,
Logarithmic ,
Decibel
}
Public Slots
void disableSync ()
void setTempoSync (QAction *_item)
void setTempoSync (SyncMode _note_type)
Public Slots inherited from lmms::AutomatableModel
virtual void reset ()
void setUseControllerValue (bool b=true)
void unlinkControllerConnection ()
Signals
void scaleChanged (float _new_scale)
void syncModeChanged (lmms::TempoSyncKnobModel::SyncMode _new_mode)
Signals inherited from lmms::AutomatableModel
void destroyed (lmms::jo_id_t id)
void initValueChanged (float val)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
TempoSyncKnobModel (const float _val, const float _min, const float _max, const float _step, const float _scale, Model *_parent, const QString &_display_name=QString())
~TempoSyncKnobModel () override=default
MeterModel & getCustomMeterModel ()
MeterModel const & getCustomMeterModel () const
void loadSettings (const QDomElement &_this, const QString &name) override
Loads settings (value, automation links and controller connections) of AutomatableModel from specified DOM element using <name> as attribute/node name.
void saveSettings (QDomDocument &_doc, QDomElement &_this, const QString &name) override
Saves settings (value, automation links and controller connections) of AutomatableModel into specified DOM element using <name> as attribute/node name.
float scale () const
void setScale (float _new_scale)
void setSyncMode (SyncMode _new_mode)
SyncMode syncMode () const
Public Member Functions inherited from lmms::FloatModel
FloatModel (float val=0, float min=0, float max=0, float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
QString displayValue (const float val) const override
int getDigitCount () const
float getRoundedValue () const
Public Member Functions inherited from lmms::TypedAutomatableModel< float >
AutomatableModel (const float val=0, const float min=0, const float max=0, const float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
float initValue () const
float maxValue () const
float minValue () const
float value (int frameOffset=0) const
Public Member Functions inherited from lmms::AutomatableModel
~AutomatableModel () override
virtual void accept (ConstModelVisitor &v) const =0
virtual void accept (ModelVisitor &v)=0
float centerValue () const
ControllerConnection * controllerConnection () const
float controllerValue (int frameOffset) const
template<class Target>
Target * dynamicCast (bool doThrow=false)
Return this class casted to Target.
template<class Target>
const Target * dynamicCast (bool doThrow=false) const
const overload, see overloaded function
float globalAutomationValueAt (const TimePos &time)
bool hasLinkedModels () const
void incValue (int steps)
template<class T>
T initValue () const
float inverseScaledValue (float value) const
Returns value applied with the inverse of this model's scale type.
bool isAtInitValue () const
bool isAutomated () const
bool isAutomatedOrControlled () const
bool isScaleLogarithmic () const
bool isValueChanged ()
template<class T>
T maxValue () const
template<class T>
T minValue () const
QString nodeName () const override
float range () const
float scaledValue (float value) const
Returns value scaled with the scale type and min/max values of this model.
void setAutomatedValue (const float value)
void setCenterValue (const float centerVal)
void setControllerConnection (ControllerConnection *c)
void setInitValue (const float value)
void setRange (const float min, const float max, const float step=1)
void setScaleLogarithmic (bool setToTrue=true)
void setScaleType (ScaleType sc)
void setStep (const float step)
void setStrictStepSize (const bool b)
void setValue (const float value)
template<class T>
T step () const
void unlinkAllModels ()
bool useControllerValue ()
template<class T>
T value (int frameOffset=0) const
ValueBuffer * valueBuffer ()
Function that returns sample-exact data as a ValueBuffer.
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Protected Slots
void calculateTempoSyncTime (lmms::bpm_t _bpm)
void updateCustom ()
Private Attributes
MeterModel m_custom
float m_scale
SyncMode m_tempoLastSyncMode
SyncMode m_tempoSyncMode
Friends
class gui::TempoSyncKnob
Additional Inherited Members
Static Public Member Functions inherited from lmms::AutomatableModel
template<bool>
static bool castValue (const float v)
template<class T>
static T castValue (const float v)
static void incrementPeriodCounter ()
static void linkModels (AutomatableModel *m1, AutomatableModel *m2)
link m1 and m2, let m1 take the values of m2
static void resetPeriodCounter ()
static void unlinkModels (AutomatableModel *m1, AutomatableModel *m2)
Protected Member Functions inherited from lmms::AutomatableModel
AutomatableModel (const float val=0, const float min=0, const float max=0, const float step=0, Model *parent=nullptr, const QString &displayName=QString(), bool defaultConstructed=false)
float fittedValue (float value) const
returns a value which is in range between min() and max() and aligned according to the step size (step size 0.05 -> value 0.12345 becomes 0.10 etc.).
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Detailed Description
Definition at line 44 of file TempoSyncKnobModel.h.
Member Enumeration Documentation
SyncMode
enum class lmms::TempoSyncKnobModel::SyncMode strong
Enumerator
None
DoubleWholeNote
WholeNote
HalfNote
QuarterNote
EighthNote
SixteenthNote
ThirtysecondNote
Custom
Definition at line 49 of file TempoSyncKnobModel.h.
Constructor & Destructor Documentation
TempoSyncKnobModel()
lmms::TempoSyncKnobModel::TempoSyncKnobModel (const float _val, const float _min, const float _max, const float _step, const float _scale, Model * _parent, const QString & _display_name = QString())
Definition at line 38 of file TempoSyncKnobModel.cpp.
References lmms::FloatModel::FloatModel(), calculateTempoSyncTime(), lmms::Engine::getSong(), m_custom, m_scale, m_tempoLastSyncMode, m_tempoSyncMode, and None.
~TempoSyncKnobModel()
lmms::TempoSyncKnobModel::~TempoSyncKnobModel () override default
References loadSettings(), and saveSettings().
Member Function Documentation
calculateTempoSyncTime
void lmms::TempoSyncKnobModel::calculateTempoSyncTime (lmms::bpm_t _bpm) protected slot
Definition at line 73 of file TempoSyncKnobModel.cpp.
References Custom, DoubleWholeNote, EighthNote, HalfNote, m_custom, m_scale, m_tempoLastSyncMode, m_tempoSyncMode, lmms::TypedAutomatableModel< float >::maxValue(), None, QuarterNote, lmms::JournallingObject::setJournalling(), lmms::AutomatableModel::setValue(), SixteenthNote, syncModeChanged(), lmms::JournallingObject::testAndSetJournalling(), ThirtysecondNote, and WholeNote.
Referenced by TempoSyncKnobModel(), setScale(), and setSyncMode().
disableSync
void lmms::TempoSyncKnobModel::disableSync () inline slot
Definition at line 94 of file TempoSyncKnobModel.h.
References None, and setTempoSync().
getCustomMeterModel() [1/2]
MeterModel & lmms::TempoSyncKnobModel::getCustomMeterModel () inline
Definition at line 85 of file TempoSyncKnobModel.h.
References m_custom.
Referenced by lmms::gui::TempoSyncBarModelEditor::modelChanged(), and lmms::gui::TempoSyncBarModelEditor::updateTextDescription().
getCustomMeterModel() [2/2]
MeterModel const & lmms::TempoSyncKnobModel::getCustomMeterModel () const inline
Definition at line 86 of file TempoSyncKnobModel.h.
References m_custom.
loadSettings()
void lmms::TempoSyncKnobModel::loadSettings (const QDomElement & element, const QString & name) override virtual
Loads settings (value, automation links and controller connections) of AutomatableModel from specified DOM element using <name> as attribute/node name.
Reimplemented from lmms::AutomatableModel.
Definition at line 140 of file TempoSyncKnobModel.cpp.
References lmms::AutomatableModel::loadSettings(), m_custom, and setSyncMode().
Referenced by ~TempoSyncKnobModel().
saveSettings()
void lmms::TempoSyncKnobModel::saveSettings (QDomDocument & doc, QDomElement & element, const QString & name) override virtual
Saves settings (value, automation links and controller connections) of AutomatableModel into specified DOM element using <name> as attribute/node name.
Parameters
doc TODO
element Where this option shall be saved. Depending on the model, this can be done in an attribute or in a subnode.
name Name to store this model as.
Reimplemented from lmms::AutomatableModel.
Definition at line 129 of file TempoSyncKnobModel.cpp.
References m_custom, lmms::AutomatableModel::saveSettings(), and syncMode().
Referenced by ~TempoSyncKnobModel().
scale()
float lmms::TempoSyncKnobModel::scale () const inline
Definition at line 78 of file TempoSyncKnobModel.h.
References m_scale.
Referenced by lmms::gui::TempoSyncBarModelEditor::contextMenuEvent().
scaleChanged
void lmms::TempoSyncKnobModel::scaleChanged (float _new_scale) signal
Referenced by setScale().
setScale()
void lmms::TempoSyncKnobModel::setScale (float _new_scale)
Definition at line 169 of file TempoSyncKnobModel.cpp.
References calculateTempoSyncTime(), lmms::Engine::getSong(), m_scale, and scaleChanged().
setSyncMode()
void lmms::TempoSyncKnobModel::setSyncMode (SyncMode _new_mode)
Definition at line 151 of file TempoSyncKnobModel.cpp.
References calculateTempoSyncTime(), Custom, lmms::Model::dataChanged(), lmms::Engine::getSong(), m_custom, m_tempoSyncMode, and updateCustom().
Referenced by loadSettings(), setTempoSync(), and updateCustom().
setTempoSync [1/2]
void lmms::TempoSyncKnobModel::setTempoSync (QAction * _item) slot
Definition at line 56 of file TempoSyncKnobModel.cpp.
References setTempoSync().
setTempoSync [2/2]
void lmms::TempoSyncKnobModel::setTempoSync (SyncMode _note_type) slot
Definition at line 64 of file TempoSyncKnobModel.cpp.
References lmms::Engine::getSong(), lmms::Song::setModified(), and setSyncMode().
Referenced by disableSync(), setTempoSync(), lmms::gui::TempoSyncBarModelEditor::showCustom(), and lmms::gui::TempoSyncKnob::showCustom().
syncMode()
SyncMode lmms::TempoSyncKnobModel::syncMode () const inline
Definition at line 71 of file TempoSyncKnobModel.h.
References m_tempoSyncMode.
Referenced by saveSettings(), and lmms::gui::TempoSyncBarModelEditor::updateTextDescription().
syncModeChanged
void lmms::TempoSyncKnobModel::syncModeChanged (lmms::TempoSyncKnobModel::SyncMode _new_mode) signal
Referenced by calculateTempoSyncTime(), lmms::gui::TempoSyncBarModelEditor::modelChanged(), and lmms::gui::TempoSyncKnob::modelChanged().
updateCustom
void lmms::TempoSyncKnobModel::updateCustom () protected slot
Definition at line 179 of file TempoSyncKnobModel.cpp.
References Custom, and setSyncMode().
Referenced by setSyncMode().
Friends And Related Symbol Documentation
gui::TempoSyncKnob
friend class gui::TempoSyncKnob friend
Definition at line 115 of file TempoSyncKnobModel.h.
Member Data Documentation
m_custom
MeterModel lmms::TempoSyncKnobModel::m_custom private
Definition at line 112 of file TempoSyncKnobModel.h.
Referenced by TempoSyncKnobModel(), calculateTempoSyncTime(), getCustomMeterModel(), getCustomMeterModel(), loadSettings(), saveSettings(), and setSyncMode().
m_scale
float lmms::TempoSyncKnobModel::m_scale private
Definition at line 110 of file TempoSyncKnobModel.h.
Referenced by TempoSyncKnobModel(), calculateTempoSyncTime(), lmms::gui::TempoSyncKnob::contextMenuEvent(), scale(), and setScale().
m_tempoLastSyncMode
SyncMode lmms::TempoSyncKnobModel::m_tempoLastSyncMode private
Definition at line 109 of file TempoSyncKnobModel.h.
Referenced by TempoSyncKnobModel(), and calculateTempoSyncTime().
m_tempoSyncMode
SyncMode lmms::TempoSyncKnobModel::m_tempoSyncMode private
Definition at line 108 of file TempoSyncKnobModel.h.
Referenced by TempoSyncKnobModel(), calculateTempoSyncTime(), setSyncMode(), and syncMode().
The documentation for this class was generated from the following files:
include/TempoSyncKnobModel.h
src/core/TempoSyncKnobModel.cpp