LMMS: lmms::gui::Oscilloscope Class Reference
lmms::gui::Oscilloscope Class Reference
#include <Oscilloscope.h>
Public Member Functions
Oscilloscope (QWidget *_parent)
~Oscilloscope () override
QColor const & clippingColor () const
QColor const & leftChannelColor () const
QColor const & otherChannelsColor () const
QColor const & rightChannelColor () const
void setActive (bool _active)
void setClippingColor (QColor const &clippingColor)
void setLeftChannelColor (QColor const &leftChannelColor)
void setOtherChannelsColor (QColor const &otherChannelsColor)
void setRightChannelColor (QColor const &rightChannelColor)
Protected Slots
void updateAudioBuffer (const lmms::SampleFrame *buffer)
Protected Member Functions
void mousePressEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *_pe) override
Properties
QColor clippingColor
QColor leftChannelColor
QColor otherChannelsColor
QColor rightChannelColor
Private Member Functions
bool clips (float level) const
Private Attributes
bool m_active
QPixmap m_background
SampleFrame * m_buffer
QColor m_clippingColor
QColor m_leftChannelColor
QColor m_otherChannelsColor
QPointF * m_points
QColor m_rightChannelColor
Detailed Description
Definition at line 44 of file Oscilloscope.h.
Constructor & Destructor Documentation
Oscilloscope()
lmms::gui::Oscilloscope::Oscilloscope (QWidget * _parent)
Definition at line 42 of file Oscilloscope.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), lmms::ConfigManager::inst(), m_active, m_background, m_buffer, m_clippingColor, m_leftChannelColor, m_otherChannelsColor, m_points, m_rightChannelColor, setActive(), and lmms::zeroSampleFrames().
~Oscilloscope()
lmms::gui::Oscilloscope::~Oscilloscope () override
Definition at line 67 of file Oscilloscope.cpp.
References m_buffer, and m_points.
Member Function Documentation
clippingColor()
QColor const & lmms::gui::Oscilloscope::clippingColor () const
Definition at line 145 of file Oscilloscope.cpp.
References m_clippingColor.
clips()
bool lmms::gui::Oscilloscope::clips (float level) const private
Definition at line 220 of file Oscilloscope.cpp.
Referenced by paintEvent().
leftChannelColor()
QColor const & lmms::gui::Oscilloscope::leftChannelColor () const
Definition at line 115 of file Oscilloscope.cpp.
References m_leftChannelColor.
mousePressEvent()
void lmms::gui::Oscilloscope::mousePressEvent (QMouseEvent * _me) override protected
Definition at line 212 of file Oscilloscope.cpp.
References m_active, and setActive().
otherChannelsColor()
QColor const & lmms::gui::Oscilloscope::otherChannelsColor () const
Definition at line 135 of file Oscilloscope.cpp.
References m_otherChannelsColor.
paintEvent()
void lmms::gui::Oscilloscope::paintEvent (QPaintEvent * _pe) override protected
Definition at line 156 of file Oscilloscope.cpp.
References lmms::gui::adjustedToPixelSize(), lmms::Engine::audioEngine(), lmms::AudioEngine::clip(), clippingColor, clips(), lmms::DEFAULT_CHANNELS, DEFAULT_FONT_SIZE, lmms::AudioEngine::framesPerPeriod(), lmms::getAbsPeakValues(), lmms::Engine::getSong(), lmms::SampleFrame::left(), leftChannelColor, m_active, m_background, m_buffer, m_points, lmms::AudioEngine::masterGain(), otherChannelsColor, lmms::SampleFrame::right(), and rightChannelColor.
rightChannelColor()
QColor const & lmms::gui::Oscilloscope::rightChannelColor () const
Definition at line 125 of file Oscilloscope.cpp.
References m_rightChannelColor.
setActive()
void lmms::gui::Oscilloscope::setActive (bool _active)
Definition at line 88 of file Oscilloscope.cpp.
References lmms::Engine::audioEngine(), lmms::gui::getGUI(), m_active, and updateAudioBuffer().
Referenced by Oscilloscope(), and mousePressEvent().
setClippingColor()
void lmms::gui::Oscilloscope::setClippingColor (QColor const & clippingColor)
Definition at line 150 of file Oscilloscope.cpp.
References clippingColor, and m_clippingColor.
setLeftChannelColor()
void lmms::gui::Oscilloscope::setLeftChannelColor (QColor const & leftChannelColor)
Definition at line 120 of file Oscilloscope.cpp.
References leftChannelColor, and m_leftChannelColor.
setOtherChannelsColor()
void lmms::gui::Oscilloscope::setOtherChannelsColor (QColor const & otherChannelsColor)
Definition at line 140 of file Oscilloscope.cpp.
References m_otherChannelsColor, and otherChannelsColor.
setRightChannelColor()
void lmms::gui::Oscilloscope::setRightChannelColor (QColor const & rightChannelColor)
Definition at line 130 of file Oscilloscope.cpp.
References m_rightChannelColor, and rightChannelColor.
updateAudioBuffer
void lmms::gui::Oscilloscope::updateAudioBuffer (const lmms::SampleFrame * buffer) protected slot
Definition at line 76 of file Oscilloscope.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::framesPerPeriod(), lmms::Engine::getSong(), and m_buffer.
Referenced by setActive().
Member Data Documentation
m_active
bool lmms::gui::Oscilloscope::m_active private
Definition at line 87 of file Oscilloscope.h.
Referenced by Oscilloscope(), mousePressEvent(), paintEvent(), and setActive().
m_background
QPixmap lmms::gui::Oscilloscope::m_background private
Definition at line 83 of file Oscilloscope.h.
Referenced by Oscilloscope(), and paintEvent().
m_buffer
SampleFrame* lmms::gui::Oscilloscope::m_buffer private
Definition at line 86 of file Oscilloscope.h.
Referenced by Oscilloscope(), ~Oscilloscope(), paintEvent(), and updateAudioBuffer().
m_clippingColor
QColor lmms::gui::Oscilloscope::m_clippingColor private
Definition at line 92 of file Oscilloscope.h.
Referenced by Oscilloscope(), clippingColor(), and setClippingColor().
m_leftChannelColor
QColor lmms::gui::Oscilloscope::m_leftChannelColor private
Definition at line 89 of file Oscilloscope.h.
Referenced by Oscilloscope(), leftChannelColor(), and setLeftChannelColor().
m_otherChannelsColor
QColor lmms::gui::Oscilloscope::m_otherChannelsColor private
Definition at line 91 of file Oscilloscope.h.
Referenced by Oscilloscope(), otherChannelsColor(), and setOtherChannelsColor().
m_points
QPointF* lmms::gui::Oscilloscope::m_points private
Definition at line 84 of file Oscilloscope.h.
Referenced by Oscilloscope(), ~Oscilloscope(), and paintEvent().
m_rightChannelColor
QColor lmms::gui::Oscilloscope::m_rightChannelColor private
Definition at line 90 of file Oscilloscope.h.
Referenced by Oscilloscope(), rightChannelColor(), and setRightChannelColor().
Property Documentation
clippingColor
QColor lmms::gui::Oscilloscope::clippingColor read write
Definition at line 51 of file Oscilloscope.h.
Referenced by paintEvent(), and setClippingColor().
leftChannelColor
QColor lmms::gui::Oscilloscope::leftChannelColor read write
Definition at line 48 of file Oscilloscope.h.
Referenced by paintEvent(), and setLeftChannelColor().
otherChannelsColor
QColor lmms::gui::Oscilloscope::otherChannelsColor read write
Definition at line 50 of file Oscilloscope.h.
Referenced by paintEvent(), and setOtherChannelsColor().
rightChannelColor
QColor lmms::gui::Oscilloscope::rightChannelColor read write
Definition at line 49 of file Oscilloscope.h.
Referenced by paintEvent(), and setRightChannelColor().
The documentation for this class was generated from the following files:
include/Oscilloscope.h
src/gui/widgets/Oscilloscope.cpp