LMMS: lmms::gui::Fader Class Reference
lmms::gui::Fader Class Reference
#include <Fader.h>
Public Types
enum class AdjustmentDirection {
Up ,
Down
}
Signals
void peakChanged (float peak)
Public Member Functions
Fader (FloatModel *model, const QString &name, QWidget *parent, bool modelIsLinear=true)
Fader (FloatModel *model, const QString &name, QWidget *parent, const QPixmap &knob, bool modelIsLinear=true)
~Fader () override=default
void adjust (const Qt::KeyboardModifiers &modifiers, AdjustmentDirection direction)
void adjustByDecibelDelta (float value)
void adjustByDialog ()
float getMaxPeak () const
float getMinPeak () const
float getPeak_L ()
float getPeak_R ()
bool getRenderUnityLine () const
void setDisplayConversion (bool b)
void setHintText (const QString &txt_before, const QString &txt_after)
void setMaxPeak (float maxPeak)
void setMinPeak (float minPeak)
void setPeak_L (float fPeak)
void setPeak_R (float fPeak)
void setRenderUnityLine (bool value=true)
Public Member Functions inherited from lmms::gui::TypedModelView< FloatModel >
TypedModelView (Model *model, QWidget *_this)
FloatModel * model ()
const FloatModel * model () const
Public Member Functions inherited from lmms::gui::AutomatableModelView
AutomatableModelView (Model *model, QWidget *_this)
~AutomatableModelView () override=default
void addDefaultActions (QMenu *menu)
float getConversionFactor ()
AutomatableModel * modelUntyped ()
const AutomatableModel * modelUntyped () const
void setConversionFactor (float factor)
void setDescription (const QString &desc)
void setModel (Model *model, bool isOldModelValid=true) override
void setUnit (const QString &unit)
void unsetModel () override
template<typename T>
T value () const
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
Properties
bool levelsDisplayedInDBFS
QColor peakClip
QColor peakOk
QColor peakWarn
bool renderUnityLine
QColor unityMarker
Private Member Functions
void adjustModelByDBDelta (float value)
int calculateKnobPosYFromModel () const
float computeScaledRatio (float dBValue) const
Computes the scaled ratio between the maximum dB value supported by the model and the minimum dB value that's supported by the fader from the given actual dB value.
void contextMenuEvent (QContextMenuEvent *me) override
float determineAdjustmentDelta (const Qt::KeyboardModifiers &modifiers) const
QString getModelValueAsDbString () const
bool modelIsLinear () const
void modelValueChanged ()
void mouseDoubleClickEvent (QMouseEvent *mouseEvent) override
void mouseMoveEvent (QMouseEvent *ev) override
void mousePressEvent (QMouseEvent *ev) override
void mouseReleaseEvent (QMouseEvent *me) override
void paintEvent (QPaintEvent *ev) override
void paintFaderTicks (QPainter &painter)
void paintLevels (QPaintEvent *ev, QPainter &painter, bool linear=false)
void setPeak (float fPeak, float &targetPeak, float &persistentPeak, QElapsedTimer &lastPeakTimer)
Set peak value (0.0 .
void setVolumeByLocalPixelValue (int y)
void updateTextFloat ()
void wheelEvent (QWheelEvent *ev) override
Private Attributes
float m_fMaxPeak {dbfsToAmp(9)}
float m_fMinPeak {dbfsToAmp(-42)}
float m_fPeakValue_L {0.}
float m_fPeakValue_R {0.}
QPixmap m_knob {embed::getIconPixmap("fader_knob")}
int m_knobCenterOffset {0}
Stores the offset to the knob center when the user drags the fader knob.
QSize m_knobSize
QElapsedTimer m_lastPeakTimer_L
QElapsedTimer m_lastPeakTimer_R
bool m_levelsDisplayedInDBFS {true}
bool m_modelIsLinear {false}
QColor m_peakClip {193, 32, 56}
QColor m_peakOk {10, 212, 92}
QColor m_peakWarn {214, 236, 82}
float m_persistentPeak_L {0.}
float m_persistentPeak_R {0.}
bool m_renderUnityLine {true}
QColor m_unityMarker {63, 63, 63, 255}
Static Private Attributes
static SimpleTextFloat * s_textFloat = nullptr
Additional Inherited Members
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
virtual void modelChanged ()
QWidget * widget ()
Protected Attributes inherited from lmms::gui::AutomatableModelView
float m_conversionFactor
QString m_description
QString m_unit
Detailed Description
Definition at line 66 of file Fader.h.
Member Enumeration Documentation
AdjustmentDirection
enum class lmms::gui::Fader::AdjustmentDirection strong
Enumerator
Up
Down
Definition at line 96 of file Fader.h.
Constructor & Destructor Documentation
Fader() [1/2]
lmms::gui::Fader::Fader (FloatModel * model, const QString & name, QWidget * parent, bool modelIsLinear = true)
Definition at line 72 of file Fader.cpp.
References lmms::Model::dataChanged(), lmms::gui::AutomatableModelView::m_conversionFactor, m_knob, m_knobSize, m_modelIsLinear, lmms::gui::TypedModelView< FloatModel >::model(), modelIsLinear(), modelValueChanged(), s_textFloat, setHintText(), and lmms::gui::AutomatableModelView::setModel().
Referenced by Fader(), and ~Fader().
Fader() [2/2]
lmms::gui::Fader::Fader (FloatModel * model, const QString & name, QWidget * parent, const QPixmap & knob, bool modelIsLinear = true)
Definition at line 107 of file Fader.cpp.
References Fader(), m_knob, lmms::gui::TypedModelView< FloatModel >::model(), and modelIsLinear().
~Fader()
lmms::gui::Fader::~Fader () override default
References Fader(), and setPeak_L().
Member Function Documentation
adjust()
void lmms::gui::Fader::adjust (const Qt::KeyboardModifiers & modifiers, AdjustmentDirection direction)
Definition at line 113 of file Fader.cpp.
References adjustByDecibelDelta(), determineAdjustmentDelta(), and Down.
adjustByDecibelDelta()
void lmms::gui::Fader::adjustByDecibelDelta (float value)
Definition at line 119 of file Fader.cpp.
References adjustModelByDBDelta(), s_textFloat, updateTextFloat(), and lmms::gui::AutomatableModelView::value().
Referenced by adjust(), and wheelEvent().
adjustByDialog()
void lmms::gui::Fader::adjustByDialog ()
Definition at line 127 of file Fader.cpp.
References lmms::ampToDbfs(), lmms::dbfsToAmp(), lmms::gui::AutomatableModelView::m_conversionFactor, lmms::TypedAutomatableModel< T >::maxValue(), lmms::TypedAutomatableModel< T >::minValue(), lmms::gui::TypedModelView< FloatModel >::model(), modelIsLinear(), lmms::AutomatableModel::setValue(), lmms::gui::AutomatableModelView::value(), and lmms::TypedAutomatableModel< T >::value().
Referenced by mouseDoubleClickEvent().
adjustModelByDBDelta()
void lmms::gui::Fader::adjustModelByDBDelta (float value) private
Definition at line 299 of file Fader.cpp.
References lmms::ampToDbfs(), lmms::dbfsToAmp(), lmms::gui::TypedModelView< FloatModel >::model(), modelIsLinear(), lmms::AutomatableModel::setValue(), lmms::gui::AutomatableModelView::value(), and lmms::TypedAutomatableModel< T >::value().
Referenced by adjustByDecibelDelta(), and peakChanged().
calculateKnobPosYFromModel()
int lmms::gui::Fader::calculateKnobPosYFromModel () const private
Definition at line 332 of file Fader.cpp.
References lmms::ampToDbfs(), computeScaledRatio(), m_knobSize, lmms::gui::TypedModelView< FloatModel >::model(), modelIsLinear(), and lmms::gui::AutomatableModelView::value().
Referenced by mousePressEvent(), paintEvent(), peakChanged(), and updateTextFloat().
computeScaledRatio()
float lmms::gui::Fader::computeScaledRatio (float dBValue) const private
Computes the scaled ratio between the maximum dB value supported by the model and the minimum dB value that's supported by the fader from the given actual dB value.
If the provided input value lies inside the aforementioned interval then the result will be a value between 0 (value == minimum value) and 1 (value == maximum model value). If you look at the graphical representation of the fader then 0 represents a point at the bottom of the fader and 1 a point at the top of the fader. The ratio is scaled by an internal exponent which is an implementation detail that cannot be changed for now.
Definition at line 442 of file Fader.cpp.
References lmms::ampToDbfs(), and lmms::gui::TypedModelView< FloatModel >::model().
Referenced by calculateKnobPosYFromModel(), paintFaderTicks(), and peakChanged().
contextMenuEvent()
void lmms::gui::Fader::contextMenuEvent (QContextMenuEvent * me) override private
Definition at line 162 of file Fader.cpp.
References lmms::gui::AutomatableModelView::addDefaultActions().
Referenced by peakChanged().
determineAdjustmentDelta()
float lmms::gui::Fader::determineAdjustmentDelta (const Qt::KeyboardModifiers & modifiers) const private
Definition at line 277 of file Fader.cpp.
Referenced by adjust(), peakChanged(), and wheelEvent().
getMaxPeak()
float lmms::gui::Fader::getMaxPeak () const inline
Definition at line 90 of file Fader.h.
References m_fMaxPeak.
getMinPeak()
float lmms::gui::Fader::getMinPeak () const inline
Definition at line 87 of file Fader.h.
References m_fMinPeak.
getModelValueAsDbString()
QString lmms::gui::Fader::getModelValueAsDbString () const private
Definition at line 513 of file Fader.cpp.
References lmms::ampToDbfs(), lmms::gui::TypedModelView< FloatModel >::model(), modelIsLinear(), and lmms::gui::AutomatableModelView::value().
Referenced by modelValueChanged(), peakChanged(), and updateTextFloat().
getPeak_L()
float lmms::gui::Fader::getPeak_L () inline
Definition at line 82 of file Fader.h.
References getPeak_L(), and m_fPeakValue_L.
Referenced by getPeak_L().
getPeak_R()
float lmms::gui::Fader::getPeak_R () inline
Definition at line 85 of file Fader.h.
References m_fPeakValue_R.
getRenderUnityLine()
bool lmms::gui::Fader::getRenderUnityLine () const inline
Definition at line 93 of file Fader.h.
References m_renderUnityLine.
Referenced by paintLevels().
modelIsLinear()
bool lmms::gui::Fader::modelIsLinear () const inline private
Definition at line 159 of file Fader.h.
References m_modelIsLinear.
Referenced by Fader(), Fader(), adjustByDialog(), adjustModelByDBDelta(), calculateKnobPosYFromModel(), getModelValueAsDbString(), paintEvent(), and setVolumeByLocalPixelValue().
modelValueChanged()
void lmms::gui::Fader::modelValueChanged () private
Definition at line 508 of file Fader.cpp.
References getModelValueAsDbString().
Referenced by Fader(), and peakChanged().
mouseDoubleClickEvent()
void lmms::gui::Fader::mouseDoubleClickEvent (QMouseEvent * mouseEvent) override private
Definition at line 239 of file Fader.cpp.
References adjustByDialog().
Referenced by peakChanged().
mouseMoveEvent()
void lmms::gui::Fader::mouseMoveEvent (QMouseEvent * ev) override private
Definition at line 173 of file Fader.cpp.
References setVolumeByLocalPixelValue(), and updateTextFloat().
Referenced by peakChanged().
mousePressEvent()
void lmms::gui::Fader::mousePressEvent (QMouseEvent * ev) override private virtual
Reimplemented from lmms::gui::AutomatableModelView.
Definition at line 187 of file Fader.cpp.
References lmms::JournallingObject::addJournalCheckPoint(), calculateKnobPosYFromModel(), lmms::KBD_COPY_MODIFIER, m_knobCenterOffset, m_knobSize, lmms::gui::TypedModelView< FloatModel >::model(), lmms::gui::AutomatableModelView::mousePressEvent(), s_textFloat, lmms::JournallingObject::saveJournallingState(), setVolumeByLocalPixelValue(), and updateTextFloat().
Referenced by peakChanged().
mouseReleaseEvent()
void lmms::gui::Fader::mouseReleaseEvent (QMouseEvent * me) override private
Definition at line 248 of file Fader.cpp.
References m_knobCenterOffset, lmms::gui::TypedModelView< FloatModel >::model(), lmms::JournallingObject::restoreJournallingState(), and s_textFloat.
Referenced by peakChanged().
paintEvent()
void lmms::gui::Fader::paintEvent (QPaintEvent * ev) override private
Definition at line 543 of file Fader.cpp.
References calculateKnobPosYFromModel(), lmms::ConfigManager::inst(), m_knob, m_knobSize, m_levelsDisplayedInDBFS, modelIsLinear(), paintFaderTicks(), paintLevels(), and lmms::gui::AutomatableModelView::value().
Referenced by peakChanged().
paintFaderTicks()
void lmms::gui::Fader::paintFaderTicks (QPainter & painter) private
Definition at line 712 of file Fader.cpp.
References lmms::ampToDbfs(), lmms::approximatelyEqual(), computeScaledRatio(), i, m_knobSize, and lmms::gui::TypedModelView< FloatModel >::model().
Referenced by paintEvent(), and peakChanged().
paintLevels()
void lmms::gui::Fader::paintLevels (QPaintEvent * ev, QPainter & painter, bool linear = false) private
Definition at line 559 of file Fader.cpp.
References lmms::ampToDbfs(), lmms::dbfsToAmp(), getRenderUnityLine(), m_fMaxPeak, m_fMinPeak, m_fPeakValue_L, m_fPeakValue_R, m_peakClip, m_peakOk, m_peakWarn, m_persistentPeak_L, m_persistentPeak_R, m_unityMarker, lmms::LinearMap< T >::map(), and lmms::gui::AutomatableModelView::value().
Referenced by paintEvent(), and peakChanged().
peakChanged
void lmms::gui::Fader::peakChanged (float peak) signal
References adjustModelByDBDelta(), calculateKnobPosYFromModel(), computeScaledRatio(), contextMenuEvent(), determineAdjustmentDelta(), getModelValueAsDbString(), modelValueChanged(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), paintFaderTicks(), paintLevels(), setPeak(), setVolumeByLocalPixelValue(), updateTextFloat(), lmms::gui::AutomatableModelView::value(), and wheelEvent().
Referenced by lmms::gui::MixerChannelView::MixerChannelView(), and setPeak().
setDisplayConversion()
void lmms::gui::Fader::setDisplayConversion (bool b) inline
Definition at line 107 of file Fader.h.
References lmms::gui::AutomatableModelView::m_conversionFactor.
setHintText()
void lmms::gui::Fader::setHintText (const QString & txt_before, const QString & txt_after) inline
Definition at line 112 of file Fader.h.
References lmms::gui::AutomatableModelView::setDescription(), and lmms::gui::AutomatableModelView::setUnit().
Referenced by Fader().
setMaxPeak()
void lmms::gui::Fader::setMaxPeak (float maxPeak) inline
Definition at line 91 of file Fader.h.
References m_fMaxPeak.
setMinPeak()
void lmms::gui::Fader::setMinPeak (float minPeak) inline
Definition at line 88 of file Fader.h.
References m_fMinPeak.
setPeak()
void lmms::gui::Fader::setPeak (float fPeak, float & targetPeak, float & persistentPeak, QElapsedTimer & lastPeakTimer) private
Set peak value (0.0 .
. 1.0)
Definition at line 455 of file Fader.cpp.
References peakChanged().
Referenced by peakChanged(), setPeak_L(), and setPeak_R().
setPeak_L()
void lmms::gui::Fader::setPeak_L (float fPeak)
Definition at line 479 of file Fader.cpp.
References m_fPeakValue_L, m_lastPeakTimer_L, m_persistentPeak_L, and setPeak().
Referenced by ~Fader().
setPeak_R()
void lmms::gui::Fader::setPeak_R (float fPeak)
Definition at line 486 of file Fader.cpp.
References m_fPeakValue_R, m_lastPeakTimer_R, m_persistentPeak_R, and setPeak().
setRenderUnityLine()
void lmms::gui::Fader::setRenderUnityLine (bool value = true) inline
Definition at line 94 of file Fader.h.
References m_renderUnityLine, and lmms::gui::AutomatableModelView::value().
setVolumeByLocalPixelValue()
void lmms::gui::Fader::setVolumeByLocalPixelValue (int y) private
Definition at line 385 of file Fader.cpp.
References lmms::ampToDbfs(), lmms::dbfsToAmp(), m_knobCenterOffset, m_knobSize, lmms::LinearMap< T >::map(), lmms::gui::TypedModelView< FloatModel >::model(), modelIsLinear(), and lmms::AutomatableModel::setValue().
Referenced by mouseMoveEvent(), mousePressEvent(), and peakChanged().
updateTextFloat()
void lmms::gui::Fader::updateTextFloat () private
Definition at line 494 of file Fader.cpp.
References calculateKnobPosYFromModel(), getModelValueAsDbString(), lmms::gui::AutomatableModelView::m_conversionFactor, lmms::gui::AutomatableModelView::m_description, lmms::gui::AutomatableModelView::m_unit, lmms::gui::TypedModelView< FloatModel >::model(), s_textFloat, and lmms::gui::AutomatableModelView::value().
Referenced by adjustByDecibelDelta(), mouseMoveEvent(), mousePressEvent(), and peakChanged().
wheelEvent()
void lmms::gui::Fader::wheelEvent (QWheelEvent * ev) override private
Definition at line 266 of file Fader.cpp.
References adjustByDecibelDelta(), and determineAdjustmentDelta().
Referenced by peakChanged().
Member Data Documentation
m_fMaxPeak
float lmms::gui::Fader::m_fMaxPeak {dbfsToAmp(9)} private
Definition at line 168 of file Fader.h.
Referenced by getMaxPeak(), paintLevels(), and setMaxPeak().
m_fMinPeak
float lmms::gui::Fader::m_fMinPeak {dbfsToAmp(-42)} private
Definition at line 167 of file Fader.h.
Referenced by getMinPeak(), paintLevels(), and setMinPeak().
m_fPeakValue_L
float lmms::gui::Fader::m_fPeakValue_L {0.} private
Definition at line 163 of file Fader.h.
Referenced by getPeak_L(), paintLevels(), and setPeak_L().
m_fPeakValue_R
float lmms::gui::Fader::m_fPeakValue_R {0.} private
Definition at line 164 of file Fader.h.
Referenced by getPeak_R(), paintLevels(), and setPeak_R().
m_knob
QPixmap lmms::gui::Fader::m_knob {embed::getIconPixmap("fader_knob")} private
Definition at line 173 of file Fader.h.
Referenced by Fader(), Fader(), and paintEvent().
m_knobCenterOffset
int lmms::gui::Fader::m_knobCenterOffset {0} private
Stores the offset to the knob center when the user drags the fader knob.
This is needed to make it feel like the users drag the knob without it jumping immediately to the click position.
Definition at line 182 of file Fader.h.
Referenced by mousePressEvent(), mouseReleaseEvent(), and setVolumeByLocalPixelValue().
m_knobSize
QSize lmms::gui::Fader::m_knobSize private
Definition at line 174 of file Fader.h.
Referenced by Fader(), calculateKnobPosYFromModel(), mousePressEvent(), paintEvent(), paintFaderTicks(), and setVolumeByLocalPixelValue().
m_lastPeakTimer_L
QElapsedTimer lmms::gui::Fader::m_lastPeakTimer_L private
Definition at line 170 of file Fader.h.
Referenced by setPeak_L().
m_lastPeakTimer_R
QElapsedTimer lmms::gui::Fader::m_lastPeakTimer_R private
Definition at line 171 of file Fader.h.
Referenced by setPeak_R().
m_levelsDisplayedInDBFS
bool lmms::gui::Fader::m_levelsDisplayedInDBFS {true} private
Definition at line 184 of file Fader.h.
Referenced by paintEvent().
m_modelIsLinear
bool lmms::gui::Fader::m_modelIsLinear {false} private
Definition at line 185 of file Fader.h.
Referenced by Fader(), and modelIsLinear().
m_peakClip
QColor lmms::gui::Fader::m_peakClip {193, 32, 56} private
Definition at line 190 of file Fader.h.
Referenced by paintLevels().
m_peakOk
QColor lmms::gui::Fader::m_peakOk {10, 212, 92} private
Definition at line 189 of file Fader.h.
Referenced by paintLevels().
m_peakWarn
QColor lmms::gui::Fader::m_peakWarn {214, 236, 82} private
Definition at line 191 of file Fader.h.
Referenced by paintLevels().
m_persistentPeak_L
float lmms::gui::Fader::m_persistentPeak_L {0.} private
Definition at line 165 of file Fader.h.
Referenced by paintLevels(), and setPeak_L().
m_persistentPeak_R
float lmms::gui::Fader::m_persistentPeak_R {0.} private
Definition at line 166 of file Fader.h.
Referenced by paintLevels(), and setPeak_R().
m_renderUnityLine
bool lmms::gui::Fader::m_renderUnityLine {true} private
Definition at line 194 of file Fader.h.
Referenced by getRenderUnityLine(), and setRenderUnityLine().
m_unityMarker
QColor lmms::gui::Fader::m_unityMarker {63, 63, 63, 255} private
Definition at line 192 of file Fader.h.
Referenced by paintLevels().
s_textFloat
SimpleTextFloat * lmms::gui::Fader::s_textFloat = nullptr static private
Definition at line 187 of file Fader.h.
Referenced by Fader(), adjustByDecibelDelta(), mousePressEvent(), mouseReleaseEvent(), and updateTextFloat().
Property Documentation
levelsDisplayedInDBFS
bool lmms::gui::Fader::levelsDisplayedInDBFS
Definition at line 73 of file Fader.h.
peakClip
QColor lmms::gui::Fader::peakClip
Definition at line 71 of file Fader.h.
peakOk
QColor lmms::gui::Fader::peakOk
Definition at line 70 of file Fader.h.
peakWarn
QColor lmms::gui::Fader::peakWarn
Definition at line 72 of file Fader.h.
renderUnityLine
bool lmms::gui::Fader::renderUnityLine read write
Definition at line 74 of file Fader.h.
unityMarker
QColor lmms::gui::Fader::unityMarker
Definition at line 75 of file Fader.h.
The documentation for this class was generated from the following files:
include/Fader.h
src/gui/widgets/Fader.cpp