LMMS: Jack::JackPort Class Reference
Jack::JackPort Class Reference
Base class for port.
#include <JackPort.h>
Public Member Functions
JackPort ()
bool Allocate (int refnum, const char *port_name, const char *port_type, JackPortFlags flags)
int EnsureMonitor (bool onoff)
int GetAliases (char *const aliases[2])
jack_default_audio_sample_t * GetBuffer ()
int GetFlags () const
jack_nframes_t GetLatency () const
void GetLatencyRange (jack_latency_callback_mode_t mode, jack_latency_range_t *range) const
const char * GetName () const
int GetRefNum () const
const char * GetShortName () const
jack_nframes_t GetTotalLatency () const
const char * GetType () const
bool MonitoringInput ()
bool NameEquals (const char *target)
void Release ()
int RequestMonitor (bool onoff)
int SetAlias (const char *alias)
void SetLatency (jack_nframes_t latency)
void SetLatencyRange (jack_latency_callback_mode_t mode, jack_latency_range_t *range)
void SetName (const char *name)
int Tie (jack_port_id_t port_index)
int UnsetAlias (const char *alias)
int UnTie ()
Private Member Functions
void ClearBuffer (jack_nframes_t frames)
bool IsUsed () const
void MixBuffers (void **src_buffers, int src_count, jack_nframes_t frames)
Private Attributes
char fAlias1 [REAL_JACK_PORT_NAME_SIZE+1]
char fAlias2 [REAL_JACK_PORT_NAME_SIZE+1]
jack_default_audio_sample_t fBuffer [BUFFER_SIZE_MAX+8]
jack_latency_range_t fCaptureLatency
enum JackPortFlags fFlags
bool fInUse
jack_nframes_t fLatency
uint8_t fMonitorRequests
char fName [REAL_JACK_PORT_NAME_SIZE+1]
jack_latency_range_t fPlaybackLatency
int fRefNum
jack_port_id_t fTied
jack_nframes_t fTotalLatency
int fTypeId
Friends
class JackGraphManager
Detailed Description
Base class for port.
Definition at line 39 of file JackPort.h.
Constructor & Destructor Documentation
JackPort()
Jack::JackPort::JackPort ()
Definition at line 30 of file JackPort.cpp.
References Release().
Member Function Documentation
Allocate()
bool Jack::JackPort::Allocate (int refnum, const char * port_name, const char * port_type, JackPortFlags flags)
Definition at line 35 of file JackPort.cpp.
References ClearBuffer(), fAlias1, fAlias2, fCaptureLatency, fFlags, fInUse, fLatency, fMonitorRequests, fName, fPlaybackLatency, fRefNum, fTied, fTotalLatency, fTypeId, Jack::GetPortTypeId(), NO_PORT, and Jack::PORT_TYPES_MAX.
Referenced by Jack::JackGraphManager::AllocatePortAux().
ClearBuffer()
void Jack::JackPort::ClearBuffer (jack_nframes_t frames) private
Definition at line 295 of file JackPort.cpp.
References fTypeId, GetBuffer(), Jack::GetPortType(), and Jack::JackPortType::init.
Referenced by Allocate(), Jack::JackGraphManager::AllocatePort(), Jack::JackGraphManager::GetBuffer(), and Jack::JackGraphManager::SetBufferSize().
EnsureMonitor()
int Jack::JackPort::EnsureMonitor (bool onoff)
jackd.h If JackPortCanMonitor is set for this port, turn input monitoring on or off. Otherwise, do nothing.
if (!(fFlags & JackPortCanMonitor)) return -1;
Definition at line 176 of file JackPort.cpp.
References fMonitorRequests.
Referenced by jack_port_ensure_monitor().
GetAliases()
int Jack::JackPort::GetAliases (char *const aliases[2])
Definition at line 252 of file JackPort.cpp.
References fAlias1, fAlias2, and REAL_JACK_PORT_NAME_SIZE.
Referenced by jack_port_get_aliases(), Jack::JackDriver::MatchPortName(), and Jack::JackDriver::SaveConnections().
GetBuffer()
jack_default_audio_sample_t * Jack::JackPort::GetBuffer () inline
Definition at line 109 of file JackPort.h.
References fBuffer.
Referenced by ClearBuffer(), Jack::JackGraphManager::GetBuffer(), and MixBuffers().
GetFlags()
int Jack::JackPort::GetFlags () const
Definition at line 213 of file JackPort.cpp.
References fFlags.
Referenced by Jack::JackClient::HandleLatencyCallback(), jack_port_flags(), and Jack::JackEngine::PortDisconnect().
GetLatency()
jack_nframes_t Jack::JackPort::GetLatency () const
Definition at line 85 of file JackPort.cpp.
References fLatency.
Referenced by Jack::JackNetDriver::AllocPorts(), Jack::JackGraphManager::ComputeTotalLatencyAux(), and jack_port_get_latency().
GetLatencyRange()
void Jack::JackPort::GetLatencyRange (jack_latency_callback_mode_t mode, jack_latency_range_t * range) const
Definition at line 135 of file JackPort.cpp.
References fCaptureLatency, fPlaybackLatency, and JackCaptureLatency.
Referenced by Jack::JackClient::HandleLatencyCallback(), jack_port_get_latency_range(), and Jack::JackGraphManager::RecalculateLatencyAux().
GetName()
const char * Jack::JackPort::GetName () const
Definition at line 200 of file JackPort.cpp.
References fName.
Referenced by Jack::JackEngine::CheckPortsConnect(), Jack::JackGraphManager::GetPortsAux(), jack_port_name(), and Jack::JackDriver::SaveConnections().
GetRefNum()
int Jack::JackPort::GetRefNum () const
Definition at line 80 of file JackPort.cpp.
References fRefNum.
Referenced by Jack::JackEngine::CheckPortsConnect(), Jack::JackGraphManager::GetBuffer(), jack_port_tie(), and Jack::JackClient::PortIsMine().
GetShortName()
const char * Jack::JackPort::GetShortName () const
Definition at line 205 of file JackPort.cpp.
References fName.
Referenced by jack_port_short_name().
GetTotalLatency()
jack_nframes_t Jack::JackPort::GetTotalLatency () const
Definition at line 90 of file JackPort.cpp.
References fTotalLatency.
Referenced by jack_port_get_total_latency().
GetType()
const char * Jack::JackPort::GetType () const
Definition at line 218 of file JackPort.cpp.
References Jack::JackPortType::fName, fTypeId, and Jack::GetPortType().
Referenced by Jack::JackGraphManager::GetPortsAux(), jack_port_type(), jack_port_type_id(), Jack::JackDriver::MatchPortName(), Jack::JackNetOneDriver::render_jack_ports_to_payload_float(), Jack::JackNetOneDriver::render_payload_to_jack_ports_float(), Jack::JackDriver::SaveConnections(), and Jack::JackNetDriver::SaveConnections().
IsUsed()
bool Jack::JackPort::IsUsed () const inline private
Definition at line 63 of file JackPort.h.
References fInUse.
Referenced by Jack::JackGraphManager::AllocatePortAux(), Jack::JackGraphManager::ComputeTotalLatencies(), Jack::JackGraphManager::GetBuffer(), Jack::JackGraphManager::GetPort(), Jack::JackGraphManager::GetPortsAux(), and Jack::JackGraphManager::SetBufferSize().
MixBuffers()
void Jack::JackPort::MixBuffers (void ** src_buffers, int src_count, jack_nframes_t frames) private
Definition at line 301 of file JackPort.cpp.
References fTypeId, GetBuffer(), Jack::GetPortType(), and Jack::JackPortType::mixdown.
Referenced by Jack::JackGraphManager::GetBuffer().
MonitoringInput()
bool Jack::JackPort::MonitoringInput () inline
Definition at line 103 of file JackPort.h.
References fMonitorRequests.
Referenced by jack_port_monitoring_input(), and Jack::JackAlsaDriver::MonitorInputAux().
NameEquals()
bool Jack::JackPort::NameEquals (const char * target)
Definition at line 231 of file JackPort.cpp.
References fAlias1, fAlias2, fName, and REAL_JACK_PORT_NAME_SIZE.
Referenced by Jack::JackGraphManager::GetPort().
Release()
void Jack::JackPort::Release ()
Definition at line 64 of file JackPort.cpp.
References fAlias1, fAlias2, fCaptureLatency, fFlags, fInUse, fLatency, fMonitorRequests, fPlaybackLatency, fRefNum, fTied, fTotalLatency, fTypeId, JackPortIsInput, and NO_PORT.
Referenced by JackPort(), Jack::JackGraphManager::AllocatePort(), and Jack::JackGraphManager::ReleasePort().
RequestMonitor()
int Jack::JackPort::RequestMonitor (bool onoff)
jackd.h If JackPortCanMonitor is set for this port, turn input monitoring on or off. Otherwise, do nothing.
if (!(fFlags & JackPortCanMonitor)) return -1;
Definition at line 156 of file JackPort.cpp.
References fMonitorRequests.
Referenced by Jack::JackGraphManager::RequestMonitor().
SetAlias()
int Jack::JackPort::SetAlias (const char * alias)
Definition at line 269 of file JackPort.cpp.
References fAlias1, and fAlias2.
Referenced by Jack::JackNetDriver::AllocPorts(), Jack::JackAlsaDriver::Attach(), Jack::JackALSARawMidiDriver::Attach(), Jack::JackAudioDriver::Attach(), Jack::JackFFADODriver::Attach(), Jack::JackMidiDriver::Attach(), Jack::JackPortAudioDriver::Attach(), Jack::JackWinMMEDriver::Attach(), and jack_port_set_alias().
SetLatency()
void Jack::JackPort::SetLatency (jack_nframes_t latency)
Definition at line 95 of file JackPort.cpp.
References fCaptureLatency, fFlags, fLatency, fPlaybackLatency, JackPortIsInput, and JackPortIsOutput.
Referenced by jack_port_set_latency().
SetLatencyRange()
void Jack::JackPort::SetLatencyRange (jack_latency_callback_mode_t mode, jack_latency_range_t * range)
Definition at line 112 of file JackPort.cpp.
References fCaptureLatency, fFlags, fLatency, fPlaybackLatency, JackCaptureLatency, JackPortIsInput, JackPortIsOutput, JackPortIsPhysical, _jack_latency_range::max, and _jack_latency_range::min.
Referenced by Jack::JackALSARawMidiDriver::Attach(), Jack::JackWinMMEDriver::Attach(), Jack::JackClient::HandleLatencyCallback(), jack_port_set_latency_range(), and Jack::JackGraphManager::RecalculateLatencyAux().
SetName()
void Jack::JackPort::SetName (const char * name)
Definition at line 224 of file JackPort.cpp.
References fName.
Tie()
int Jack::JackPort::Tie (jack_port_id_t port_index)
Definition at line 144 of file JackPort.cpp.
References fTied.
Referenced by jack_port_tie().
UnsetAlias()
int Jack::JackPort::UnsetAlias (const char * alias)
Definition at line 282 of file JackPort.cpp.
References fAlias1, and fAlias2.
Referenced by jack_port_unset_alias().
UnTie()
int Jack::JackPort::UnTie ()
Definition at line 150 of file JackPort.cpp.
References fTied, and NO_PORT.
Referenced by jack_port_untie().
Friends And Related Symbol Documentation
JackGraphManager
friend class JackGraphManager friend
Definition at line 42 of file JackPort.h.
References JackGraphManager.
Referenced by JackGraphManager.
Member Data Documentation
fAlias1
char Jack::JackPort::fAlias1[REAL_JACK_PORT_NAME_SIZE+1] private
Definition at line 49 of file JackPort.h.
Referenced by Allocate(), GetAliases(), NameEquals(), Release(), SetAlias(), and UnsetAlias().
fAlias2
char Jack::JackPort::fAlias2[REAL_JACK_PORT_NAME_SIZE+1] private
Definition at line 50 of file JackPort.h.
Referenced by Allocate(), GetAliases(), NameEquals(), Release(), SetAlias(), and UnsetAlias().
fBuffer
jack_default_audio_sample_t Jack::JackPort::fBuffer[BUFFER_SIZE_MAX+8] private
Definition at line 61 of file JackPort.h.
Referenced by GetBuffer().
fCaptureLatency
jack_latency_range_t Jack::JackPort::fCaptureLatency private
Definition at line 56 of file JackPort.h.
Referenced by Allocate(), GetLatencyRange(), Release(), SetLatency(), and SetLatencyRange().
fFlags
enum JackPortFlags Jack::JackPort::fFlags private
Definition at line 47 of file JackPort.h.
Referenced by Allocate(), Jack::JackGraphManager::CheckPorts(), Jack::JackGraphManager::ComputeTotalLatencyAux(), Jack::JackGraphManager::DisconnectAll(), Jack::JackGraphManager::GetBuffer(), GetFlags(), Jack::JackGraphManager::GetPortsAux(), Release(), Jack::JackGraphManager::ReleasePort(), Jack::JackGraphManager::RequestMonitor(), SetLatency(), and SetLatencyRange().
fInUse
bool Jack::JackPort::fInUse private
Definition at line 59 of file JackPort.h.
Referenced by Allocate(), Jack::JackGraphManager::Connect(), Jack::JackGraphManager::Disconnect(), IsUsed(), and Release().
fLatency
jack_nframes_t Jack::JackPort::fLatency private
Definition at line 53 of file JackPort.h.
Referenced by Allocate(), GetLatency(), Release(), SetLatency(), and SetLatencyRange().
fMonitorRequests
uint8_t Jack::JackPort::fMonitorRequests private
Definition at line 57 of file JackPort.h.
Referenced by Allocate(), EnsureMonitor(), MonitoringInput(), Release(), and RequestMonitor().
fName
char Jack::JackPort::fName[REAL_JACK_PORT_NAME_SIZE+1] private
Definition at line 48 of file JackPort.h.
Referenced by Allocate(), Jack::JackGraphManager::CheckPorts(), Jack::JackGraphManager::GetConnectionsAux(), GetName(), Jack::JackGraphManager::GetPortsAux(), GetShortName(), NameEquals(), and SetName().
fPlaybackLatency
jack_latency_range_t Jack::JackPort::fPlaybackLatency private
Definition at line 55 of file JackPort.h.
Referenced by Allocate(), GetLatencyRange(), Release(), SetLatency(), and SetLatencyRange().
fRefNum
int Jack::JackPort::fRefNum private
Definition at line 51 of file JackPort.h.
Referenced by Allocate(), GetRefNum(), and Release().
fTied
jack_port_id_t Jack::JackPort::fTied private
Definition at line 60 of file JackPort.h.
Referenced by Allocate(), Jack::JackGraphManager::GetBuffer(), Release(), Tie(), and UnTie().
fTotalLatency
jack_nframes_t Jack::JackPort::fTotalLatency private
Definition at line 54 of file JackPort.h.
Referenced by Allocate(), Jack::JackGraphManager::ComputeTotalLatency(), GetTotalLatency(), and Release().
fTypeId
int Jack::JackPort::fTypeId private
Definition at line 46 of file JackPort.h.
Referenced by Allocate(), ClearBuffer(), Jack::JackGraphManager::Connect(), GetType(), MixBuffers(), and Release().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/common/JackPort.h
src/3rdparty/jack2/common/JackPort.cpp