LMMS: Jack Namespace Reference
Jack Namespace Reference
Namespaces
namespace detail
Classes
struct _net_transport_data
\Brief This structure contains transport data to be sent over the network
struct _packet_header
\Brief This structure is a complete header
struct _session_params
This structure contains master/slave connection parameters, it's used to setup the whole system.
struct _win_net_error
struct AtomicArrayCounter
Counter for CAS.
struct AtomicCounter
Counter for CAS.
class AudioInterface
An ALSA audio interface.
class AudioParam
A convenient class to pass parameters to AudioInterface.
class JackAC3Encoder
struct JackAC3EncoderParams
struct JackActivateRequest
Activate request.
class JackActivationCount
Client activation counter.
class JackAlsaAdapter
Audio adapter using ALSA API.
class JackAlsaDriver
The ALSA driver.
class JackALSARawMidiDriver
class JackALSARawMidiInputPort
class JackALSARawMidiOutputPort
class JackALSARawMidiPort
class JackALSARawMidiReceiveQueue
class JackALSARawMidiSendQueue
class JackAndroidSemaphore
Inter process synchronization using POSIX semaphore.
class JackAndroidThread
The POSIX thread base class.
class JackArgParser
class JackAtomicArrayState
A class to handle several states in a lock-free manner.
class JackAtomicDelayLockedLoop
class JackAtomicState
A class to handle two states (switching from one to the other) in a lock-free manner.
class JackAudioAdapter
Audio adapter : Jack client side.
class JackAudioAdapterInterface
Base class for audio adapters.
class JackAudioDriver
The base class for audio drivers: drivers with audio ports.
class JackBasePosixMutex
Mutex abstraction.
class JackBaseWinMutex
Mutex abstraction.
class JackBoomerDriver
The Boomer driver.
class JackClient
The base class for clients: share part of the implementation for JackInternalClient and JackLibClient.
struct JackClientCheckRequest
CheckClient request.
struct JackClientCheckResult
CheckClient result.
struct JackClientCloseRequest
CloseClient request.
struct JackClientControl
Client control possibly in shared memory.
struct JackClientHandlerInterface
struct JackClientHasSessionCallbackRequest
class JackClientInterface
Client interface.
struct JackClientNameResult
struct JackClientNotification
ClientNotification.
struct JackClientNotificationRequest
ClientNotification request.
struct JackClientOpenRequest
NewClient request.
struct JackClientOpenResult
NewClient result.
class JackClientPipeThread
class JackClientSocket
Client socket.
struct JackClientTiming
For client timing measurements.
struct JackComputeTotalLatenciesRequest
ComputeTotalLatencies request.
class JackConnectionManager
Connection manager.
class JackCoreAudioAdapter
Audio adapter using CoreAudio API.
class JackCoreAudioDriver
class JackCoreMidiDriver
class JackCoreMidiInputPort
class JackCoreMidiOutputPort
class JackCoreMidiPhysicalInputPort
class JackCoreMidiPhysicalOutputPort
class JackCoreMidiPort
class JackCoreMidiVirtualInputPort
class JackCoreMidiVirtualOutputPort
struct JackDeactivateRequest
Deactivate request.
class JackDebugClient
A "decorator" debug client to validate API use.
class JackDelayLockedLoop
class JackDriver
class JackDriverClientInterface
The base interface for drivers clients.
class JackDriverInterface
The base interface for drivers.
class JackDummyDriver
The dummy driver.
class JackEngine
Engine description.
struct JackEngineControl
Engine control in shared memory.
class JackEngineProfiling
class JackException
Exception base class.
class JackExternalClient
Server side implementation of library clients.
class JackFFADODriver
The FFADO driver.
class JackFFADOMidiInputPort
class JackFFADOMidiOutputPort
class JackFFADOMidiReceiveQueue
class JackFFADOMidiSendQueue
class JackFifo
Inter process synchronization using Fifo.
struct JackFilter
class JackFixedArray
Utility class.
class JackFixedArray1
Utility class.
class JackFixedMatrix
Utility class.
class JackFrameTimer
A class using the JackAtomicState to manage jack time.
class JackFreewheelDriver
The FreeWheel driver : run Jack engine at full speed.
class JackGenericClientChannel
Generic JackClientChannel class.
struct JackGetClientNameRequest
struct JackGetInternalClientNameRequest
GetInternalClientName request.
struct JackGetInternalClientNameResult
GetInternalClient result.
struct JackGetUUIDRequest
struct JackGlobals
class JackGnuPlotMonitor
Generic monitoring class.
class JackGoldfishDriver
The goldfish driver.
class JackGraphManager
Graph manager: contains the connection manager and the port array.
class JackIIODriver
The Linux Industrial IO (IIO) subsystem driver for Jack.
class JackInternalClient
Internal clients in the server.
class JackInternalClientChannel
JackClientChannel for server internal clients.
struct JackInternalClientHandleRequest
InternalClientHandle request.
struct JackInternalClientHandleResult
InternalClientHandle result.
struct JackInternalClientLoadRequest
InternalClientLoad request.
struct JackInternalClientLoadResult
InternalClientLoad result.
struct JackInternalClientUnloadRequest
InternalClientUnload request.
struct JackInternalClientUnloadResult
InternalClientLoad result.
class JackInternalSessionLoader
class JackLibClient
Client on the library side.
struct JackLibGlobals
Global library static structure: singleton kind of pattern.
class JackLibSampleRateResampler
Resampler using "libsamplerate" (http://www.mega-nerd.com/SRC/).
class JackLinuxFutex
Inter process synchronization using Linux futex.
class JackLoadableInternalClient
class JackLoadableInternalClient1
class JackLoadableInternalClient2
class JackLock
class JackLockAble
Base class for "lockable" objects.
class JackLockedEngine
Locked Engine, access to methods is serialized using a mutex.
class JackLoopbackDriver
The loopback driver : to be used to "pipeline" applications connected in sequence.
class JackLoopFeedback
Utility class.
class JackMachSemaphore
Inter process synchronization using using Mach semaphore.
class JackMachSemaphoreServer
A runnable thread which listens for IPC messages and replies with a semaphore send right.
class JackMachThread
Darwin threads.
struct JackMessage
class JackMessageBuffer
Message buffer to be used from RT threads.
class JackMetadata
Metadata base.
class JackMidiAsyncQueue
This is a MIDI message queue designed to allow one thread to pass MIDI messages to another thread (though it can also be used to buffer events internally).
class JackMidiAsyncWaitQueue
This is an asynchronous wait queue that allows a thread to wait for a message, either indefinitely or for a specified time.
struct JackMidiBuffer
class JackMidiBufferReadQueue
Wrapper class to present a JackMidiBuffer in a read queue interface.
class JackMidiBufferWriteQueue
Wrapper class to present a JackMidiBuffer in a write queue interface.
class JackMidiDriver
The base class for MIDI drivers: drivers with MIDI ports.
struct JackMidiEvent
class JackMidiRawInputWriteQueue
This queue enqueues raw, unparsed MIDI packets, and outputs complete MIDI messages to a write queue.
class JackMidiRawOutputWriteQueue
This queue enqueues valid MIDI events and modifies them for raw output to a write queue.
class JackMidiReadQueue
Interface for objects that MIDI events can be read from.
class JackMidiReceiveQueue
Implemented by MIDI input connections.
class JackMidiSendQueue
Implemented by MIDI output connections.
class JackMidiWriteQueue
Interface for classes that act as write queues for MIDI messages.
class JackMMCSS
MMCSS services.
struct JackNetAdapter
Net adapter.
class JackNetDriver
\Brief This class describes the Net Backend
class JackNetException
Exception possibly thrown by Net slaves.
struct JackNetExtMaster
struct JackNetExtSlave
class JackNetInterface
\Brief This class describes the basic Net Interface, used by both master and slave.
class JackNetMaster
class JackNetMasterInterface
\Brief This class describes the Net Interface for masters (NetMaster)
class JackNetMasterManager
\Brief This class describer the Network Manager
class JackNetOneDriver
\Brief This class describes the Net Backend
class JackNetSlaveInterface
\Brief This class describes the Net Interface for slaves (NetDriver and NetAdapter)
class JackNetUnixSocket
class JackNetWinSocket
class JackOpenSLESDriver
The OpenSLES driver.
class JackOSSAdapter
The OSS adapter.
class JackOSSDriver
The OSS driver.
struct JackPIControler
class JackPort
Base class for port.
class JackPortAudioAdapter
Audio adapter using PortAudio API.
class JackPortAudioDriver
The PortAudio driver.
struct JackPortConnectNameRequest
PortConnectName request.
struct JackPortConnectRequest
PortConnect request.
struct JackPortDisconnectNameRequest
PortDisconnectName request.
struct JackPortDisconnectRequest
PortDisconnect request.
struct JackPortRegisterRequest
PortRegister request.
struct JackPortRegisterResult
PortRegister result.
struct JackPortRenameRequest
PortRename request.
struct JackPortType
struct JackPortUnRegisterRequest
PortUnregister request.
class JackPosixMutex
class JackPosixProcessSync
A synchronization primitive built using a condition variable.
class JackPosixSemaphore
Inter process synchronization using POSIX semaphore.
class JackPosixThread
The POSIX thread base class.
class JackProfiler
Server real-time monitoring.
struct JackProfilerClient
struct JackPropertyChangeNotifyRequest
class JackProxyDriver
\Brief This class describes the Proxy Backend
class JackQuitException
struct JackReleaseTimebaseRequest
ReleaseTimebase request.
struct JackRequest
Request from client to server.
class JackRequestDecoder
Request decoder.
class JackResampler
Base class for Resampler.
struct JackReserveNameRequest
class JackRestarterDriver
A restartable driver.
class JackRestartThreadedDriver
Restart a driver after an exception is thrown.
struct JackResult
Result from the server.
class JackRingBuffer
Base class for RingBuffer in frames.
class JackRunnableInterface
The base class for runnable objects, that have an Init and Execute method to be called in a thread.
class JackSapaProxy
class JackServer
The Jack server.
struct JackServerGlobals
Global server static structure: singleton kind of pattern.
class JackServerSocket
struct JackSessionCommand
struct JackSessionNotifyRequest
SessionNotify request.
struct JackSessionNotifyResult
struct JackSessionReplyRequest
struct JackSetBufferSizeRequest
SetBufferSize request.
struct JackSetFreeWheelRequest
SetFreeWheel request.
struct JackSetTimebaseCallbackRequest
SetTimebaseCallback request.
class JackShmMem
The base class for shared memory management.
class JackShmMemAble
A class which objects possibly want to be allocated in shared memory derives from this class.
class JackShmReadPtr
Pointer on shared memory segment in the client side.
class JackShmReadWritePtr
Pointer on shared memory segment in the client side.
class JackShmReadWritePtr1
Pointer on shared memory segment in the client side: destroy the segment (used client control).
class JackSocketClientChannel
JackClientChannel using sockets.
class JackSocketNotifyChannel
JackNotifyChannel using sockets.
class JackSocketServerChannel
JackServerChannel using sockets.
class JackSocketServerNotifyChannel
JackServerNotifyChannel using sockets.
class JackTemporaryException
Exception thrown by JackEngine in temporary mode.
class JackThreadedDriver
The base class for threaded drivers using a "decorator" pattern.
class JackTimedDriver
The timed driver.
class JackTimer
A structure used for time management.
struct JackTimingClientInterval
Timing interval in the global table for a given client.
struct JackTimingMeasure
Timing structure for a table of clients.
struct JackTimingMeasureClient
Timing structure for a client.
struct JackTools
Utility functions.
class JackTransportEngine
struct JackUUIDResult
class JackWaitCallbackDriver
Wrapper for a restartable non-threaded driver (e.g.
class JackWaiterDriver
class JackWaitThreadedDriver
Wrapper for a restartable threaded driver (e.g.
class JackWinAsyncNamedPipeClient
class JackWinAsyncNamedPipeServer
Server async named pipe.
class JackWinCriticalSection
class JackWinEvent
Inter process synchronization using system wide events.
class JackWinMMEDriver
class JackWinMMEInputPort
class JackWinMMEOutputPort
class JackWinMMEPort
class JackWinMutex
class JackWinNamedPipe
class JackWinNamedPipeAux
class JackWinNamedPipeClient
Client named pipe.
class JackWinNamedPipeClientChannel
JackClientChannel using pipes.
class JackWinNamedPipeNotifyChannel
JackNotifyChannel using named pipe.
class JackWinNamedPipeServer
Server named pipe.
class JackWinNamedPipeServerChannel
JackServerChannel using pipe.
class JackWinNamedPipeServerNotifyChannel
JackServerNotifyChannel using pipes.
class JackWinProcessSync
A synchronization primitive built using a condition variable.
class JackWinSemaphore
Inter process synchronization using system wide semaphore.
class JackWinThread
Windows threads.
class NetAudioBuffer
class NetFloatAudioBuffer
class NetIntAudioBuffer
class NetMidiBuffer
\Brief Midi buffer and operations class
struct PortFollower
Follow a single port.
Typedefs
typedef struct in_addr address_t
typedef BOOL(WINAPI * avRevertMmThreadCharacteristics) (HANDLE)
typedef enum Jack::_AVRT_PRIORITY AVRT_PRIORITY
typedef HANDLE(WINAPI * avSetMmThreadCharacteristics) (LPCTSTR, LPDWORD)
typedef BOOL(WINAPI * avSetMmThreadPriority) (HANDLE, AVRT_PRIORITY)
typedef UInt8 CAAudioHardwareDeviceSectionID
typedef std::list< std::pair< std::string, std::string > > connections_list_t
\Brief This class describes a Net Master
typedef std::list< std::pair< std::string, std::pair< std::string, std::string > > > driver_connections_list_t
typedef void(* FinishCallback) (void *)
typedef int(* InitializeCallback) (jack_client_t *, const char *)
Loadable internal clients in the server.
typedef int(* InternalInitializeCallback) (jack_client_t *, const JSList *params)
typedef jack_default_audio_sample_t jack_sample_t
typedef JackAC3Encoder * JackAC3EncoderPtr
typedef JackClientSocket JackChannelTransaction
typedef JackSocketClientChannel JackClientChannel
typedef void(* JackDriverFinishFunction) (jack_driver_t *)
typedef JackPosixMutex JackMutex
typedef JackNetUnixSocket JackNetSocket
typedef JackSocketNotifyChannel JackNotifyChannel
typedef JackPosixProcessSync JackProcessSync
typedef JackSocketServerChannel JackServerChannel
typedef JackSocketServerNotifyChannel JackServerNotifyChannel
typedef JackAndroidSemaphore JackSynchro
typedef JackAndroidThread JackThread
typedef std::map< std::string, connections_list_t > master_connections_list_t
typedef master_list_t::iterator master_list_it_t
typedef std::list< JackNetMaster * > master_list_t
typedef enum _net_error net_error_t
typedef enum _net_status net_status_t
typedef enum _net_timebase_master net_timebase_master_t
typedef struct _net_transport_data net_transport_data_t
typedef struct _packet_header packet_header_t
typedef enum Jack::_AVRT_PRIORITY * PAVRT_PRIORITY
typedef jack_default_audio_sample_t sample_t
typedef struct _session_params session_params_t
typedef struct sockaddr socket_address_t
typedef int SOCKLEN
typedef enum _sync_packet_type sync_packet_type_t
typedef DWORD(WINAPI * ThreadCallback) (void *arg)
typedef uint32_t uint
typedef struct _win_net_error win_net_error_t
Enumerations
enum {
PTHREAD_CANCEL_DEFERRED ,
PTHREAD_CANCEL_ASYNCHRONOUS
}
enum _AVRT_PRIORITY {
AVRT_PRIORITY_LOW = -1 ,
AVRT_PRIORITY_NORMAL ,
AVRT_PRIORITY_HIGH ,
AVRT_PRIORITY_CRITICAL
}
enum _net_error {
NET_CONN_ERROR = 10000 ,
NET_OP_ERROR ,
NET_NO_DATA ,
NET_NO_NETWORK ,
NET_NO_ERROR
}
enum _net_status {
NET_SOCKET_ERROR = 0 ,
NET_CONNECT_ERROR ,
NET_ERROR ,
NET_SEND_ERROR ,
NET_RECV_ERROR ,
NET_CONNECTED ,
NET_ROLLING
}
\Brief This enum groups network error by type
enum _net_timebase_master {
NO_CHANGE = 0 ,
RELEASE_TIMEBASEMASTER = 1 ,
TIMEBASEMASTER = 2 ,
CONDITIONAL_TIMEBASEMASTER = 3
}
\Brief This enum describes timebase master's type
enum _sync_packet_type {
INVALID = 0 ,
SLAVE_AVAILABLE ,
SLAVE_SETUP ,
START_MASTER ,
START_SLAVE ,
KILL_MASTER
}
\Brief This enum indicates the type of a sync packet (used in the initialization phase)
enum JackNetEncoder {
JackFloatEncoder = 0 ,
JackIntEncoder = 1 ,
JackCeltEncoder = 2 ,
JackOpusEncoder = 3
}
enum JackSessionReply {
kImmediateSessionReply = 1 ,
kPendingSessionReply = 2
}
Session API constants.
enum NotificationType {
kAddClient = 0 ,
kRemoveClient = 1 ,
kActivateClient = 2 ,
kXRunCallback = 3 ,
kGraphOrderCallback = 4 ,
kBufferSizeCallback = 5 ,
kSampleRateCallback = 6 ,
kStartFreewheelCallback = 7 ,
kStopFreewheelCallback = 8 ,
kPortRegistrationOnCallback = 9 ,
kPortRegistrationOffCallback = 10 ,
kPortConnectCallback = 11 ,
kPortDisconnectCallback = 12 ,
kPortRenameCallback = 13 ,
kRealTimeCallback = 14 ,
kShutDownCallback = 15 ,
kQUIT = 16 ,
kSessionCallback = 17 ,
kLatencyCallback = 18 ,
kPropertyChangeCallback = 19 ,
kMaxNotification = 64
}
Notifications sent by the server for clients.
enum transport_command_t {
TransportCommandNone = 0 ,
TransportCommandStart = 1 ,
TransportCommandStop = 2
}
Functions
void * aligned_calloc (size_t nmemb, size_t size)
SERVER_EXPORT jack_midi_data_t ApplyRunningStatus (jack_midi_event_t *event, jack_midi_data_t running_status)
A wrapper function for the above ApplyRunningStatus function.
SERVER_EXPORT jack_midi_data_t ApplyRunningStatus (size_t *size, jack_midi_data_t **buffer, jack_midi_data_t running_status=0)
Use this function to optimize MIDI output by omitting unnecessary status bytes.
static void AssertBufferSize (jack_nframes_t buffer_size)
static void AudioBufferInit (void *buffer, size_t buffer_size, jack_nframes_t)
static void AudioBufferMixdown (void *mixbuffer, void **src_buffers, int src_count, jack_nframes_t nframes)
static size_t AudioBufferSize ()
void BuildClientPath (char *path_to_so, int path_len, const char *so_name)
static void BuildName (const char *client_name, char *res, const char *dir, int which, int size, bool promiscuous)
static int card_to_num (const char *device)
static void CopyAndConvertIn (jack_sample_t *dst, void *src, size_t nframes, int channel, int byte_skip, int bits)
static void CopyAndConvertIn (jack_sample_t *dst, void *src, size_t nframes, int channel, int chcount, int bits)
static void CopyAndConvertIn (jack_sample_t *dst, void *src, size_t nframes, int channel, int chcount, int bits)
static void CopyAndConvertIn (jack_sample_t *dst, void *src, size_t nframes, int channel, int chcount, int bits)
static void CopyAndConvertOut (void *dst, jack_sample_t *src, size_t nframes, int channel, int byte_skip, int bits)
static void CopyAndConvertOut (void *dst, jack_sample_t *src, size_t nframes, int channel, int chcount, int bits)
static void CopyAndConvertOut (void *dst, jack_sample_t *src, size_t nframes, int channel, int chcount, int bits)
static void CopyAndConvertOut (void *dst, jack_sample_t *src, size_t nframes, int channel, int chcount, int bits)
void CreateNonBlockingPipe (int *fds)
void DestroyNonBlockingPipe (int *fds)
SERVER_EXPORT jack_driver_desc_t * driver_get_descriptor ()
SERVER_EXPORT Jack::JackDriverClientInterface * driver_initialize (Jack::JackLockedEngine *engine, Jack::JackSynchro *table, const JSList *params)
char * get_control_device_name (const char *device_name)
SERVER_EXPORT jack_nframes_t GetCurrentFrame ()
Gets the estimated current time in frames.
SERVER_EXPORT JackEngineControl * GetEngineControl ()
SERVER_EXPORT jack_nframes_t GetFramesFromTime (jack_time_t time)
Gets the estimated frame that will be occurring at the given time.
SERVER_EXPORT JackGraphManager * GetGraphManager ()
SERVER_EXPORT int GetHostName (char *name, int size)
SERVER_EXPORT jack_nframes_t GetLastFrame ()
Gets the precise time at the start of the current process cycle.
std::string GetMacOSErrorString (OSStatus status)
SERVER_EXPORT int GetMessageLength (jack_midi_data_t status_byte)
Returns the expected message length for the status byte.
SERVER_EXPORT JackMetadata * GetMetadata ()
SERVER_EXPORT sync_packet_type_t GetPacketType (session_params_t *params)
const JackPortType * GetPortType (jack_port_type_id_t type_id)
jack_port_type_id_t GetPortTypeId (const char *port_type)
SERVER_EXPORT JackSynchro * GetSynchroTable ()
SERVER_EXPORT jack_time_t GetTimeFromFrames (jack_nframes_t frames)
Gets the estimated time at which the given frame will occur.
SERVER_EXPORT const char * GetTransportState (int transport_state)
static bool HasNoConnection (jack_int_t *table)
void InitLockMemoryImp (void *ptr, size_t size)
int int2pow2 (int x)
static jack_time_t JACK_MAX (jack_time_t a, jack_time_t b)
void JackMessageBufferAdd (int level, const char *message)
void LockAllMemory ()
void LockMemoryImp (void *ptr, size_t size)
SERVER_EXPORT void MidiBufferHToN (JackMidiBuffer *src_buffer, JackMidiBuffer *dst_buffer)
void MidiBufferInit (void *buffer, size_t buffer_size, jack_nframes_t nframes)
static void MidiBufferMixdown (void *mixbuffer, void **src_buffers, int src_count, jack_nframes_t nframes)
SERVER_EXPORT void MidiBufferNToH (JackMidiBuffer *src_buffer, JackMidiBuffer *dst_buffer)
static size_t MidiBufferSize ()
static void MixAudioBuffer (jack_default_audio_sample_t *mixbuffer, jack_default_audio_sample_t *buffer, jack_nframes_t frames)
SERVER_EXPORT void NetTransportDataDisplay (net_transport_data_t *data)
static void * on_device_reservation_loop (void *)
SERVER_EXPORT void PacketHeaderDisplay (packet_header_t *header)
SERVER_EXPORT void PacketHeaderHToN (packet_header_t *src_header, packet_header_t *dst_header)
SERVER_EXPORT void PacketHeaderNToH (packet_header_t *src_header, packet_header_t *dst_header)
SERVER_EXPORT const char * PrintError (int error)
void PrintLoadError (const char *so_name)
float Range (float min, float max, float val)
static string RemoveLast (const string &name)
SERVER_EXPORT void SessionParamsDisplay (session_params_t *params)
SERVER_EXPORT void SessionParamsHToN (session_params_t *src_params, session_params_t *dst_params)
SERVER_EXPORT void SessionParamsNToH (session_params_t *src_params, session_params_t *dst_params)
void SetNonBlocking (int fd)
SERVER_EXPORT int SetPacketType (session_params_t *params, sync_packet_type_t packet_type)
SERVER_EXPORT int SocketAPIEnd ()
SERVER_EXPORT int SocketAPIInit ()
static const char * State2String (jack_client_state_t state)
SERVER_EXPORT void ThreadExit ()
SERVER_EXPORT void TransportDataHToN (net_transport_data_t *src_params, net_transport_data_t *dst_params)
SERVER_EXPORT void TransportDataNToH (net_transport_data_t *src_params, net_transport_data_t *dst_params)
void UnlockAllMemory ()
void UnlockMemoryImp (void *ptr, size_t size)
void WriteMacOSError (const char *jack_function, const char *mac_function, OSStatus status)
Variables
static volatile bool device_reservation_loop_running = false
static bool fKeyLogFunctionInitialized = jack_tls_allocate_key(&JackGlobals::fKeyLogFunction)
static unsigned int fSegmentNum = 0
const JackPortType gAudioPortType
static jack_shm_info_t gInfo
static bool gKeyNotificationThreadInitialized = jack_tls_allocate_key(&JackGlobals::fNotificationThread)
static bool gKeyRealtimeThreadInitialized = jack_tls_allocate_key(&JackGlobals::fRealTimeThread)
const JackPortType gMidiPortType
static const JackPortType * gPortTypes []
char * jack_tmpdir = (char*)DEFAULT_TMP_DIR
static char const *const kAudioDeviceName = "/dev/eac"
win_net_error_t NetErrorList []
static OPENSL_STREAM * pOpenSL_stream
const jack_port_type_id_t PORT_TYPES_MAX = sizeof(gPortTypes) / sizeof(gPortTypes[0])
PRE_PACKED_STRUCTURE class Jack::JackActivationCount POST_PACKED_STRUCTURE
Typedef Documentation
address_t
typedef struct in_addr Jack::address_t
Definition at line 60 of file JackNetTool.h.
avRevertMmThreadCharacteristics
typedef BOOL(WINAPI * Jack::avRevertMmThreadCharacteristics) (HANDLE)
Definition at line 46 of file JackMMCSS.h.
AVRT_PRIORITY
typedef enum Jack::_AVRT_PRIORITY Jack::AVRT_PRIORITY
avSetMmThreadCharacteristics
typedef HANDLE(WINAPI * Jack::avSetMmThreadCharacteristics) (LPCTSTR, LPDWORD)
Definition at line 45 of file JackMMCSS.h.
avSetMmThreadPriority
typedef BOOL(WINAPI * Jack::avSetMmThreadPriority) (HANDLE, AVRT_PRIORITY)
Definition at line 47 of file JackMMCSS.h.
CAAudioHardwareDeviceSectionID
typedef UInt8 Jack::CAAudioHardwareDeviceSectionID
Definition at line 37 of file JackCoreAudioAdapter.h.
connections_list_t
typedef std::list<std::pair<std::string, std::string> > Jack::connections_list_t
\Brief This class describes a Net Master
Definition at line 36 of file JackNetManager.h.
driver_connections_list_t
typedef std::list<std::pair<std::string, std::pair<std::string, std::string> > > Jack::driver_connections_list_t
Definition at line 125 of file JackDriver.h.
FinishCallback
typedef void(* Jack::FinishCallback) (void *)
Definition at line 66 of file JackInternalClient.h.
InitializeCallback
typedef int(* Jack::InitializeCallback) (jack_client_t *, const char *)
Loadable internal clients in the server.
Definition at line 64 of file JackInternalClient.h.
InternalInitializeCallback
typedef int(* Jack::InternalInitializeCallback) (jack_client_t *, const JSList *params)
Definition at line 65 of file JackInternalClient.h.
jack_sample_t
typedef jack_default_audio_sample_t Jack::jack_sample_t
Definition at line 29 of file JackOSSDriver.h.
JackAC3EncoderPtr
typedef JackAC3Encoder* Jack::JackAC3EncoderPtr
Definition at line 96 of file JackAC3Encoder.h.
JackChannelTransaction
typedef JackWinNamedPipe Jack::JackChannelTransaction
Definition at line 59 of file JackPlatformPlug_os.h.
JackClientChannel
typedef JackWinNamedPipeClientChannel Jack::JackClientChannel
Definition at line 77 of file JackPlatformPlug_os.h.
JackDriverFinishFunction
typedef void(* Jack::JackDriverFinishFunction) (jack_driver_t *)
Definition at line 359 of file JackFFADODriver.cpp.
JackMutex
typedef JackWinMutex Jack::JackMutex
Definition at line 46 of file JackPlatformPlug_os.h.
JackNetSocket
typedef JackNetWinSocket Jack::JackNetSocket
Definition at line 89 of file JackPlatformPlug_os.h.
JackNotifyChannel
typedef JackWinNamedPipeNotifyChannel Jack::JackNotifyChannel
Definition at line 85 of file JackPlatformPlug_os.h.
JackProcessSync
typedef JackWinProcessSync Jack::JackProcessSync
Definition at line 69 of file JackPlatformPlug_os.h.
JackServerChannel
typedef JackWinNamedPipeServerChannel Jack::JackServerChannel
Definition at line 73 of file JackPlatformPlug_os.h.
JackServerNotifyChannel
typedef JackWinNamedPipeServerNotifyChannel Jack::JackServerNotifyChannel
Definition at line 81 of file JackPlatformPlug_os.h.
JackSynchro
typedef JackWinSemaphore Jack::JackSynchro
Definition at line 59 of file JackPlatformPlug_os.h.
JackThread
typedef JackWinThread Jack::JackThread
Definition at line 50 of file JackPlatformPlug_os.h.
master_connections_list_t
typedef std::map<std::string, connections_list_t> Jack::master_connections_list_t
Definition at line 96 of file JackNetManager.h.
master_list_it_t
typedef master_list_t::iterator Jack::master_list_it_t
Definition at line 95 of file JackNetManager.h.
master_list_t
typedef std::list<JackNetMaster*> Jack::master_list_t
Definition at line 94 of file JackNetManager.h.
net_error_t
typedef enum _net_error Jack::net_error_t
Definition at line 45 of file JackNetSocket.h.
net_status_t
typedef enum _net_status Jack::net_status_t
Definition at line 131 of file JackNetTool.h.
net_timebase_master_t
typedef enum _net_timebase_master Jack::net_timebase_master_t
Definition at line 203 of file JackNetTool.h.
net_transport_data_t
typedef struct _net_transport_data Jack::net_transport_data_t
Definition at line 58 of file JackNetTool.h.
packet_header_t
typedef struct _packet_header Jack::packet_header_t
Definition at line 57 of file JackNetTool.h.
PAVRT_PRIORITY
typedef enum Jack::_AVRT_PRIORITY * Jack::PAVRT_PRIORITY
sample_t
typedef jack_default_audio_sample_t Jack::sample_t
Definition at line 61 of file JackNetTool.h.
session_params_t
typedef struct _session_params Jack::session_params_t
Definition at line 56 of file JackNetTool.h.
socket_address_t
typedef struct sockaddr Jack::socket_address_t
Definition at line 59 of file JackNetTool.h.
SOCKLEN
typedef int Jack::SOCKLEN
Definition at line 38 of file JackNetWinSocket.h.
sync_packet_type_t
typedef enum _sync_packet_type Jack::sync_packet_type_t
Definition at line 149 of file JackNetTool.h.
ThreadCallback
typedef DWORD(WINAPI * Jack::ThreadCallback) (void *arg)
Definition at line 35 of file JackWinThread.h.
uint
typedef uint32_t Jack::uint
Definition at line 37 of file JackNetWinSocket.h.
win_net_error_t
typedef struct _win_net_error Jack::win_net_error_t
Definition at line 39 of file JackNetWinSocket.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PTHREAD_CANCEL_DEFERRED
PTHREAD_CANCEL_ASYNCHRONOUS
Definition at line 35 of file JackAndroidThread.h.
_AVRT_PRIORITY
enum Jack::_AVRT_PRIORITY
Enumerator
AVRT_PRIORITY_LOW
AVRT_PRIORITY_NORMAL
AVRT_PRIORITY_HIGH
AVRT_PRIORITY_CRITICAL
Definition at line 36 of file JackMMCSS.h.
_net_error
enum Jack::_net_error
Enumerator
NET_CONN_ERROR
NET_OP_ERROR
NET_NO_DATA
NET_NO_NETWORK
NET_NO_ERROR
Definition at line 36 of file JackNetSocket.h.
_net_status
enum Jack::_net_status
\Brief This enum groups network error by type
Enumerator
NET_SOCKET_ERROR
NET_CONNECT_ERROR
NET_ERROR
NET_SEND_ERROR
NET_RECV_ERROR
NET_CONNECTED
NET_ROLLING
Definition at line 120 of file JackNetTool.h.
_net_timebase_master
enum Jack::_net_timebase_master
\Brief This enum describes timebase master's type
Enumerator
NO_CHANGE
RELEASE_TIMEBASEMASTER
TIMEBASEMASTER
CONDITIONAL_TIMEBASEMASTER
Definition at line 195 of file JackNetTool.h.
_sync_packet_type
enum Jack::_sync_packet_type
\Brief This enum indicates the type of a sync packet (used in the initialization phase)
Enumerator
INVALID
SLAVE_AVAILABLE
SLAVE_SETUP
START_MASTER
START_SLAVE
KILL_MASTER
Definition at line 139 of file JackNetTool.h.
JackNetEncoder
enum Jack::JackNetEncoder
Enumerator
JackFloatEncoder
JackIntEncoder
JackCeltEncoder
JackOpusEncoder
Definition at line 63 of file JackNetTool.h.
JackSessionReply
enum Jack::JackSessionReply
Session API constants.
Enumerator
kImmediateSessionReply
kPendingSessionReply
Definition at line 59 of file JackRequest.h.
NotificationType
enum Jack::NotificationType
Notifications sent by the server for clients.
Enumerator
kAddClient
kRemoveClient
kActivateClient
kXRunCallback
kGraphOrderCallback
kBufferSizeCallback
kSampleRateCallback
kStartFreewheelCallback
kStopFreewheelCallback
kPortRegistrationOnCallback
kPortRegistrationOffCallback
kPortConnectCallback
kPortDisconnectCallback
kPortRenameCallback
kRealTimeCallback
kShutDownCallback
kQUIT
kSessionCallback
kLatencyCallback
kPropertyChangeCallback
kMaxNotification
Definition at line 30 of file JackNotification.h.
transport_command_t
enum Jack::transport_command_t
Enumerator
TransportCommandNone
TransportCommandStart
TransportCommandStop
Definition at line 31 of file JackTransportEngine.h.
Function Documentation
aligned_calloc()
void * Jack::aligned_calloc (size_t nmemb, size_t size) inline
Definition at line 36 of file JackAlsaAdapter.h.
Referenced by Jack::AudioInterface::open().
ApplyRunningStatus() [1/2]
jack_midi_data_t Jack::ApplyRunningStatus (jack_midi_event_t * event, jack_midi_data_t running_status)
A wrapper function for the above ApplyRunningStatus function.
Definition at line 48 of file JackMidiUtil.cpp.
References ApplyRunningStatus(), jack_midi_event_t::buffer, and jack_midi_event_t::size.
ApplyRunningStatus() [2/2]
jack_midi_data_t Jack::ApplyRunningStatus (size_t * size, jack_midi_data_t ** buffer, jack_midi_data_t running_status = 0)
Use this function to optimize MIDI output by omitting unnecessary status bytes.
This can't be used with all MIDI APIs, so before using this function, make sure that your MIDI API doesn't require complete MIDI messages to be sent.
To start using this function, call this method with pointers to the size and buffer arguments of the MIDI message you want to send, and set the running_status argument to '0'. For each subsequent MIDI message, call this method with pointers to its size and buffer arguments, and set the running_status argument to the return value of the previous call to this function.
Note: This function will alter the size and buffer of your MIDI message for each message that can be optimized.
Definition at line 27 of file JackMidiUtil.cpp.
Referenced by ApplyRunningStatus(), and Jack::JackMidiRawOutputWriteQueue::DequeueNonRealtimeEvent().
AssertBufferSize()
void Jack::AssertBufferSize (jack_nframes_t buffer_size) static
Definition at line 36 of file JackGraphManager.cpp.
References BUFFER_SIZE_MAX, and jack_log().
Referenced by Jack::JackGraphManager::GetBuffer().
AudioBufferInit()
void Jack::AudioBufferInit (void * buffer, size_t buffer_size, jack_nframes_t) static
Definition at line 38 of file JackAudioPort.cpp.
AudioBufferMixdown()
void Jack::AudioBufferMixdown (void * mixbuffer, void ** src_buffers, int src_count, jack_nframes_t nframes) static
Definition at line 105 of file JackAudioPort.cpp.
References i, and MixAudioBuffer().
AudioBufferSize()
size_t Jack::AudioBufferSize () static
Definition at line 157 of file JackAudioPort.cpp.
References Jack::JackEngineControl::fBufferSize, and GetEngineControl().
BuildClientPath()
void Jack::BuildClientPath (char * path_to_so, int path_len, const char * so_name)
Definition at line 282 of file JackTools.cpp.
References ADDON_DIR.
Referenced by Jack::JackLoadableInternalClient::Init().
BuildName()
void Jack::BuildName (const char * client_name, char * res, const char * dir, int which, int size, bool promiscuous) static
Definition at line 33 of file JackSocket.cpp.
References Jack::JackTools::GetUID(), Jack::JackTools::RewriteName(), and SYNC_MAX_NAME_SIZE.
Referenced by Jack::JackServerSocket::Bind(), and Jack::JackClientSocket::Connect().
card_to_num()
int Jack::card_to_num (const char * device) static
Definition at line 237 of file JackAlsaDriver.cpp.
References get_control_device_name(), i, and jack_error.
Referenced by Jack::JackAlsaDriver::Close(), and Jack::JackAlsaDriver::Open().
CopyAndConvertIn() [1/4]
void Jack::CopyAndConvertIn (jack_sample_t * dst, void * src, size_t nframes, int channel, int byte_skip, int bits) inline static
Definition at line 71 of file JackBoomerDriver.cpp.
References sample_move_dS_s16(), sample_move_dS_s24(), and sample_move_dS_s32u24().
CopyAndConvertIn() [2/4]
void Jack::CopyAndConvertIn (jack_sample_t * dst, void * src, size_t nframes, int channel, int chcount, int bits) inline static
Definition at line 147 of file JackOSSDriver.cpp.
References sample_move_dS_s16(), sample_move_dS_s24(), and sample_move_dS_s32u24().
Referenced by Jack::JackBoomerDriver::JackBoomerDriverInput::Execute(), Jack::JackOSSAdapter::Read(), and Jack::JackOSSDriver::Read().
CopyAndConvertIn() [3/4]
void Jack::CopyAndConvertIn (jack_sample_t * dst, void * src, size_t nframes, int channel, int chcount, int bits) inline static
Definition at line 36 of file JackOSSAdapter.cpp.
References sample_move_dS_s16(), sample_move_dS_s24(), and sample_move_dS_s32u24().
CopyAndConvertIn() [4/4]
void Jack::CopyAndConvertIn (jack_sample_t * dst, void * src, size_t nframes, int channel, int chcount, int bits) inline static
Definition at line 70 of file JackOSSDriver.cpp.
References sample_move_dS_s16(), sample_move_dS_s24(), and sample_move_dS_s32u24().
CopyAndConvertOut() [1/4]
void Jack::CopyAndConvertOut (void * dst, jack_sample_t * src, size_t nframes, int channel, int byte_skip, int bits) inline static
Definition at line 96 of file JackBoomerDriver.cpp.
References sample_move_d16_sS(), sample_move_d24_sS(), and sample_move_d32u24_sS().
CopyAndConvertOut() [2/4]
void Jack::CopyAndConvertOut (void * dst, jack_sample_t * src, size_t nframes, int channel, int chcount, int bits) inline static
Definition at line 172 of file JackOSSDriver.cpp.
References sample_move_d16_sS(), sample_move_d24_sS(), and sample_move_d32u24_sS().
Referenced by Jack::JackBoomerDriver::JackBoomerDriverOutput::Execute(), Jack::JackOSSAdapter::Write(), and Jack::JackOSSDriver::Write().
CopyAndConvertOut() [3/4]
void Jack::CopyAndConvertOut (void * dst, jack_sample_t * src, size_t nframes, int channel, int chcount, int bits) inline static
Definition at line 61 of file JackOSSAdapter.cpp.
References sample_move_d16_sS(), sample_move_d24_sS(), and sample_move_d32u24_sS().
CopyAndConvertOut() [4/4]
void Jack::CopyAndConvertOut (void * dst, jack_sample_t * src, size_t nframes, int channel, int chcount, int bits) inline static
Definition at line 95 of file JackOSSDriver.cpp.
References sample_move_d16_sS(), sample_move_d24_sS(), and sample_move_d32u24_sS().
CreateNonBlockingPipe()
void Jack::CreateNonBlockingPipe (int * fds)
Definition at line 11 of file JackALSARawMidiUtil.cpp.
References SetNonBlocking().
Referenced by Jack::JackALSARawMidiPort::JackALSARawMidiPort(), and Jack::JackALSARawMidiDriver::Start().
DestroyNonBlockingPipe()
void Jack::DestroyNonBlockingPipe (int * fds)
Definition at line 27 of file JackALSARawMidiUtil.cpp.
Referenced by Jack::JackALSARawMidiPort::~JackALSARawMidiPort(), and Jack::JackALSARawMidiDriver::Start().
driver_get_descriptor()
SERVER_EXPORT jack_driver_desc_t * Jack::driver_get_descriptor ()
Definition at line 668 of file JackNetDriver.cpp.
References DEFAULT_MTU, DEFAULT_MULTICAST_IP, DEFAULT_PORT, jack_driver_param_value_t::i, jack_driver_descriptor_add_parameter(), jack_driver_descriptor_construct(), JackDriverMaster, JackDriverParamBool, JackDriverParamInt, JackDriverParamString, JackDriverParamUInt, SERVER_EXPORT, jack_driver_param_value_t::str, and jack_driver_param_value_t::ui.
driver_initialize()
SERVER_EXPORT Jack::JackDriverClientInterface * Jack::driver_initialize (Jack::JackLockedEngine * engine, Jack::JackSynchro * table, const JSList * params)
Definition at line 720 of file JackNetDriver.cpp.
References jack_driver_param_t::character, _JSList::data, DEFAULT_MTU, DEFAULT_MULTICAST_IP, DEFAULT_PORT, driver, jack_driver_param_value_t::i, JACK_CLIENT_NAME_SIZE, jack_slist_next, NETWORK_MAX_LATENCY, SERVER_EXPORT, jack_driver_param_value_t::str, jack_driver_param_value_t::ui, and jack_driver_param_t::value.
get_control_device_name()
char * Jack::get_control_device_name (const char * device_name)
Definition at line 207 of file JackAlsaDriver.cpp.
References jack_error.
Referenced by card_to_num().
GetCurrentFrame()
jack_nframes_t Jack::GetCurrentFrame ()
Gets the estimated current time in frames.
This function has the same functionality as the JACK client API function jack_frame_time.
Definition at line 56 of file JackMidiUtil.cpp.
References Jack::JackEngineControl::fBufferSize, GetEngineControl(), GetMicroSeconds(), Jack::JackEngineControl::ReadFrameTime(), and Jack::JackTimer::Time2Frames().
Referenced by Jack::JackALSARawMidiReceiveQueue::DequeueEvent(), Jack::JackALSARawMidiSendQueue::EnqueueEvent(), Jack::JackALSARawMidiDriver::Execute(), and Jack::JackMidiSendQueue::GetNextScheduleFrame().
GetEngineControl()
JackEngineControl * Jack::GetEngineControl () extern
Definition at line 46 of file JackInternalClient.cpp.
References Jack::JackServerGlobals::fInstance, and SERVER_EXPORT.
Referenced by AudioBufferSize(), Jack::JackTransportEngine::CheckAllRolling(), GetCurrentFrame(), GetFramesFromTime(), GetLastFrame(), GetTimeFromFrames(), Jack::JackBoomerDriver::JackBoomerDriverInput::Init(), Jack::JackBoomerDriver::JackBoomerDriverOutput::Init(), Jack::JackNetAdapter::Init(), Jack::JackWinMMEOutputPort::Init(), Jack::JackConnectionManager::IsLoopPathAux(), jack_acquire_real_time_scheduling(), jack_client_create_thread(), jack_client_max_real_time_priority(), jack_client_real_time_priority(), jack_cpu_load(), jack_frames_since_cycle_start(), jack_frames_to_time(), jack_get_buffer_size(), jack_get_cycle_times(), jack_get_max_delayed_usecs(), jack_get_sample_rate(), jack_get_xrun_delayed_usecs(), jack_is_realtime(), jack_last_frame_time(), jack_reset_max_delayed_usecs(), jack_time_to_frames(), Jack::JackTransportEngine::MakeAllLocating(), Jack::JackTransportEngine::MakeAllStartingLocating(), Jack::JackTransportEngine::MakeAllStopping(), Jack::JackAlsaAdapter::Open(), Jack::JackOSSAdapter::Open(), Jack::JackEngineProfiling::Profile(), Jack::JackThreadedDriver::SetRealTime(), and WaitGraphChange().
GetFramesFromTime()
jack_nframes_t Jack::GetFramesFromTime (jack_time_t time)
Gets the estimated frame that will be occurring at the given time.
This function has the same functionality as the JACK client API function jack_time_to_frames.
Definition at line 66 of file JackMidiUtil.cpp.
References Jack::JackEngineControl::fBufferSize, GetEngineControl(), Jack::JackEngineControl::ReadFrameTime(), and Jack::JackTimer::Time2Frames().
Referenced by Jack::JackWinMMEInputPort::EnqueueMessage(), and Jack::JackWinMMEOutputPort::Execute().
GetGraphManager()
JackGraphManager * Jack::GetGraphManager () extern
Definition at line 41 of file JackInternalClient.cpp.
References Jack::JackServerGlobals::fInstance, and SERVER_EXPORT.
Referenced by jack_get_ports(), jack_port_by_name(), jack_port_connected(), jack_port_connected_to(), jack_port_ensure_monitor(), jack_port_flags(), jack_port_get_aliases(), jack_port_get_all_connections(), jack_port_get_buffer(), jack_port_get_connections(), jack_port_get_latency(), jack_port_get_latency_range(), jack_port_get_total_latency(), jack_port_monitoring_input(), jack_port_name(), jack_port_request_monitor(), jack_port_request_monitor_by_name(), jack_port_set_alias(), jack_port_set_latency(), jack_port_set_latency_range(), jack_port_short_name(), jack_port_tie(), jack_port_type(), jack_port_type_id(), jack_port_unset_alias(), jack_port_untie(), jack_recompute_total_latency(), and WaitGraphChange().
GetHostName()
SERVER_EXPORT int Jack::GetHostName (char * name, int size)
Definition at line 32 of file JackNetUnixSocket.cpp.
References jack_error, NET_ERROR_CODE, and SOCKET_ERROR.
Referenced by Jack::JackNetAdapter::JackNetAdapter(), Jack::JackNetDriver::JackNetDriver(), Jack::JackNetExtSlave::JackNetExtSlave(), and Jack::JackNetUnixSocket::IsLocal().
GetLastFrame()
jack_nframes_t Jack::GetLastFrame ()
Gets the precise time at the start of the current process cycle.
This function has the same functionality as the JACK client API function jack_last_frame_time.
Definition at line 75 of file JackMidiUtil.cpp.
References GetEngineControl().
Referenced by Jack::JackFFADOMidiInputPort::Process(), Jack::JackFFADOMidiOutputPort::Process(), Jack::JackFFADOMidiReceiveQueue::ResetInputBuffer(), Jack::JackMidiBufferReadQueue::ResetMidiBuffer(), Jack::JackMidiBufferWriteQueue::ResetMidiBuffer(), and Jack::JackFFADOMidiSendQueue::ResetOutputBuffer().
GetMacOSErrorString()
std::string Jack::GetMacOSErrorString (OSStatus status)
GetMessageLength()
int Jack::GetMessageLength (jack_midi_data_t status_byte)
Returns the expected message length for the status byte.
Returns 0 if the status byte is a system exclusive status byte, or -1 if the status byte is invalid.
Definition at line 81 of file JackMidiUtil.cpp.
Referenced by Jack::JackWinMMEInputPort::ProcessWinMME().
GetMetadata()
JackMetadata * Jack::GetMetadata () extern
Definition at line 56 of file JackInternalClient.cpp.
References Jack::JackServerGlobals::fInstance, and SERVER_EXPORT.
Referenced by jack_free_description(), jack_get_all_properties(), jack_get_properties(), jack_get_property(), jack_remove_all_properties(), jack_remove_properties(), jack_remove_property(), and jack_set_property().
GetPacketType()
SERVER_EXPORT sync_packet_type_t Jack::GetPacketType (session_params_t * params)
Definition at line 1174 of file JackNetTool.cpp.
References Jack::_session_params::fPacketID, INVALID, KILL_MASTER, SERVER_EXPORT, SLAVE_AVAILABLE, SLAVE_SETUP, START_MASTER, and START_SLAVE.
Referenced by Jack::JackNetMasterInterface::Init(), Jack::JackNetExtMaster::Open(), Jack::JackNetMasterManager::Run(), and Jack::JackNetSlaveInterface::SendAvailableToMaster().
GetPortType()
const struct JackPortType * Jack::GetPortType (jack_port_type_id_t type_id)
Definition at line 47 of file JackPortType.cpp.
References gPortTypes, and PORT_TYPES_MAX.
Referenced by Jack::JackPort::ClearBuffer(), Jack::JackPort::GetType(), jack_port_type_get_buffer_size(), and Jack::JackPort::MixBuffers().
GetPortTypeId()
jack_port_type_id_t Jack::GetPortTypeId (const char * port_type)
Definition at line 35 of file JackPortType.cpp.
References Jack::JackPortType::fName, gPortTypes, i, and PORT_TYPES_MAX.
Referenced by Jack::JackPort::Allocate(), jack_port_type_get_buffer_size(), and jack_port_type_id().
GetSynchroTable()
JackSynchro * Jack::GetSynchroTable () extern
Definition at line 51 of file JackInternalClient.cpp.
References Jack::JackServerGlobals::fInstance, and SERVER_EXPORT.
Referenced by jack_client_new_aux(), jack_client_open_aux(), and jack_client_open_aux().
GetTimeFromFrames()
jack_time_t Jack::GetTimeFromFrames (jack_nframes_t frames)
Gets the estimated time at which the given frame will occur.
This function has the same functionality as the JACK client API function jack_frames_to_time.
Definition at line 115 of file JackMidiUtil.cpp.
References Jack::JackEngineControl::fBufferSize, Jack::JackTimer::Frames2Time(), GetEngineControl(), and Jack::JackEngineControl::ReadFrameTime().
Referenced by Jack::JackMidiAsyncWaitQueue::DequeueEvent(), Jack::JackALSARawMidiDriver::Execute(), and Jack::JackWinMMEOutputPort::Execute().
GetTransportState()
SERVER_EXPORT const char * Jack::GetTransportState (int transport_state)
Definition at line 1375 of file JackNetTool.cpp.
References JackTransportNetStarting, JackTransportRolling, JackTransportStarting, JackTransportStopped, and SERVER_EXPORT.
Referenced by Jack::JackNetAdapter::EncodeTransportData(), Jack::JackNetDriver::EncodeTransportData(), and Jack::JackNetMaster::EncodeTransportData().
HasNoConnection()
bool Jack::HasNoConnection (jack_int_t * table) static
Definition at line 280 of file JackConnectionManager.cpp.
References CLIENT_NUM.
Referenced by Jack::JackConnectionManager::TopologicalSort().
InitLockMemoryImp()
void Jack::InitLockMemoryImp (void * ptr, size_t size)
Definition at line 117 of file JackShmMem.cpp.
References CHECK_MLOCK, jack_error, and jack_log().
int2pow2()
int Jack::int2pow2 (int x) inline
Definition at line 69 of file JackBoomerDriver.cpp.
Referenced by Jack::JackBoomerDriver::OpenInput(), Jack::JackOSSAdapter::OpenInput(), Jack::JackBoomerDriver::OpenOutput(), and Jack::JackOSSAdapter::OpenOutput().
JACK_MAX()
jack_time_t Jack::JACK_MAX (jack_time_t a, jack_time_t b) inline static
Definition at line 31 of file JackEngineControl.cpp.
Referenced by Jack::JackEngineControl::CalcCPULoad().
JackMessageBufferAdd()
void Jack::JackMessageBufferAdd (int level, const char * message)
Definition at line 158 of file JackMessageBuffer.cpp.
References Jack::JackMessageBuffer::fInstance, jack_log_function(), and LOG_LEVEL_ERROR.
Referenced by set_threaded_log_function().
LockAllMemory()
void Jack::LockAllMemory ()
Definition at line 136 of file JackShmMem.cpp.
References CHECK_MLOCKALL, jack_error, and jack_log().
LockMemoryImp()
void Jack::LockMemoryImp (void * ptr, size_t size)
Definition at line 108 of file JackShmMem.cpp.
References CHECK_MLOCK, jack_error, and jack_log().
Referenced by Jack::JackShmMemAble::LockMemory().
MidiBufferHToN()
SERVER_EXPORT void Jack::MidiBufferHToN (JackMidiBuffer * src_buffer, JackMidiBuffer * dst_buffer)
Definition at line 1273 of file JackNetTool.cpp.
References Jack::JackMidiBuffer::buffer_size, Jack::JackMidiBuffer::event_count, Jack::JackMidiBuffer::lost_events, Jack::JackMidiBuffer::magic, Jack::JackMidiBuffer::nframes, SERVER_EXPORT, and Jack::JackMidiBuffer::write_pos.
Referenced by Jack::NetMidiBuffer::RenderFromJackPorts().
MidiBufferInit()
void Jack::MidiBufferInit (void * buffer, size_t buffer_size, jack_nframes_t nframes)
Definition at line 75 of file JackMidiPort.cpp.
References Jack::JackMidiBuffer::buffer_size, BUFFER_SIZE_MAX, Jack::JackMidiBuffer::MAGIC, Jack::JackMidiBuffer::magic, and Jack::JackMidiBuffer::Reset().
Referenced by jack_midi_reset_buffer().
MidiBufferMixdown()
void Jack::MidiBufferMixdown (void * mixbuffer, void ** src_buffers, int src_count, jack_nframes_t nframes) static
Definition at line 94 of file JackMidiPort.cpp.
References Jack::JackMidiBuffer::event_count, Jack::JackMidiBuffer::events, Jack::JackMidiEvent::GetData(), i, Jack::JackMidiBuffer::IsValid(), jack_error, Jack::JackMidiBuffer::lost_events, Jack::JackMidiBuffer::ReserveEvent(), Jack::JackMidiBuffer::Reset(), Jack::JackMidiEvent::size, and Jack::JackMidiEvent::time.
MidiBufferNToH()
SERVER_EXPORT void Jack::MidiBufferNToH (JackMidiBuffer * src_buffer, JackMidiBuffer * dst_buffer)
Definition at line 1283 of file JackNetTool.cpp.
References Jack::JackMidiBuffer::buffer_size, Jack::JackMidiBuffer::event_count, Jack::JackMidiBuffer::lost_events, Jack::JackMidiBuffer::magic, Jack::JackMidiBuffer::nframes, SERVER_EXPORT, and Jack::JackMidiBuffer::write_pos.
Referenced by Jack::NetMidiBuffer::RenderToJackPorts().
MidiBufferSize()
size_t Jack::MidiBufferSize () static
Definition at line 149 of file JackMidiPort.cpp.
References BUFFER_SIZE_MAX.
MixAudioBuffer()
void Jack::MixAudioBuffer (jack_default_audio_sample_t * mixbuffer, jack_default_audio_sample_t * buffer, jack_nframes_t frames) inline static
Definition at line 43 of file JackAudioPort.cpp.
Referenced by AudioBufferMixdown().
NetTransportDataDisplay()
SERVER_EXPORT void Jack::NetTransportDataDisplay (net_transport_data_t * data)
Definition at line 1264 of file JackNetTool.cpp.
References Jack::_net_transport_data::fNewState, Jack::_net_transport_data::fState, Jack::_net_transport_data::fTimebaseMaster, jack_info(), and SERVER_EXPORT.
on_device_reservation_loop()
void * Jack::on_device_reservation_loop (void *) static
Definition at line 72 of file JackAlsaDriver.cpp.
References device_reservation_loop_running, and Jack::JackServerGlobals::on_device_reservation_loop.
Referenced by jackctl_server_create2(), Jack::JackAlsaDriver::Open(), and Jack::JackPortAudioDriver::Open().
PacketHeaderDisplay()
SERVER_EXPORT void Jack::PacketHeaderDisplay (packet_header_t * header)
Definition at line 1248 of file JackNetTool.cpp.
References Jack::_packet_header::fActivePorts, Jack::_packet_header::fCycle, Jack::_packet_header::fDataStream, Jack::_packet_header::fDataType, Jack::_packet_header::fFrames, Jack::_packet_header::fID, Jack::_packet_header::fIsLastPckt, Jack::_packet_header::fNumPacket, Jack::_packet_header::fPacketSize, Jack::_packet_header::fSubCycle, jack_info(), and SERVER_EXPORT.
PacketHeaderHToN()
SERVER_EXPORT void Jack::PacketHeaderHToN (packet_header_t * src_header, packet_header_t * dst_header)
Definition at line 1218 of file JackNetTool.cpp.
References Jack::_packet_header::fActivePorts, Jack::_packet_header::fCycle, Jack::_packet_header::fDataStream, Jack::_packet_header::fDataType, Jack::_packet_header::fFrames, Jack::_packet_header::fID, Jack::_packet_header::fIsLastPckt, Jack::_packet_header::fNumPacket, Jack::_packet_header::fPacketSize, Jack::_packet_header::fSubCycle, and SERVER_EXPORT.
Referenced by Jack::JackNetMasterInterface::Send(), and Jack::JackNetSlaveInterface::Send().
PacketHeaderNToH()
SERVER_EXPORT void Jack::PacketHeaderNToH (packet_header_t * src_header, packet_header_t * dst_header)
Definition at line 1233 of file JackNetTool.cpp.
References Jack::_packet_header::fActivePorts, Jack::_packet_header::fCycle, Jack::_packet_header::fDataStream, Jack::_packet_header::fDataType, Jack::_packet_header::fFrames, Jack::_packet_header::fID, Jack::_packet_header::fIsLastPckt, Jack::_packet_header::fNumPacket, Jack::_packet_header::fPacketSize, Jack::_packet_header::fSubCycle, and SERVER_EXPORT.
Referenced by Jack::JackNetMasterInterface::Recv(), and Jack::JackNetSlaveInterface::Recv().
PrintError()
SERVER_EXPORT const char * Jack::PrintError (int error)
Definition at line 91 of file JackNetWinSocket.cpp.
References i, NetErrorList, and SERVER_EXPORT.
PrintLoadError()
void Jack::PrintLoadError (const char * so_name)
Definition at line 277 of file JackTools.cpp.
References jack_log().
Referenced by Jack::JackLoadableInternalClient::Init().
Range()
float Jack::Range (float min, float max, float val) inline
Definition at line 32 of file JackResampler.h.
References max, and min.
Referenced by Jack::JackResampler::SetRatio().
RemoveLast()
string Jack::RemoveLast (const string & name) static
Definition at line 419 of file JackDriver.cpp.
Referenced by Jack::JackDriver::MatchPortName().
SessionParamsDisplay()
SERVER_EXPORT void Jack::SessionParamsDisplay (session_params_t * params)
Definition at line 1122 of file JackNetTool.cpp.
References Jack::_session_params::fID, Jack::_session_params::fKBps, Jack::_session_params::fMasterNetName, Jack::_session_params::fMtu, Jack::_session_params::fName, Jack::_session_params::fNetworkLatency, Jack::_session_params::fPeriodSize, Jack::_session_params::fProtocolVersion, Jack::_session_params::fReturnAudioChannels, Jack::_session_params::fReturnMidiChannels, Jack::_session_params::fSampleEncoder, Jack::_session_params::fSampleRate, Jack::_session_params::fSendAudioChannels, Jack::_session_params::fSendMidiChannels, Jack::_session_params::fSlaveNetName, Jack::_session_params::fSlaveSyncMode, Jack::_session_params::fTransportSync, jack_info(), JackCeltEncoder, JackFloatEncoder, JackIntEncoder, JackOpusEncoder, and SERVER_EXPORT.
Referenced by Jack::JackNetAdapter::Init(), Jack::JackNetDriver::Initialize(), Jack::JackNetExtMaster::Open(), Jack::JackNetExtSlave::Open(), and Jack::JackNetMasterManager::Run().
SessionParamsHToN()
SERVER_EXPORT void Jack::SessionParamsHToN (session_params_t * src_params, session_params_t * dst_params)
Definition at line 1082 of file JackNetTool.cpp.
References Jack::_session_params::fID, Jack::_session_params::fKBps, Jack::_session_params::fMtu, Jack::_session_params::fNetworkLatency, Jack::_session_params::fPacketID, Jack::_session_params::fPeriodSize, Jack::_session_params::fProtocolVersion, Jack::_session_params::fReturnAudioChannels, Jack::_session_params::fReturnMidiChannels, Jack::_session_params::fSampleEncoder, Jack::_session_params::fSampleRate, Jack::_session_params::fSendAudioChannels, Jack::_session_params::fSendMidiChannels, Jack::_session_params::fSlaveSyncMode, Jack::_session_params::fTransportSync, and SERVER_EXPORT.
Referenced by Jack::JackNetMasterInterface::Exit(), Jack::JackNetMasterInterface::Init(), Jack::JackNetSlaveInterface::SendAvailableToMaster(), and Jack::JackNetSlaveInterface::SendStartToMaster().
SessionParamsNToH()
SERVER_EXPORT void Jack::SessionParamsNToH (session_params_t * src_params, session_params_t * dst_params)
Definition at line 1102 of file JackNetTool.cpp.
References Jack::_session_params::fID, Jack::_session_params::fKBps, Jack::_session_params::fMtu, Jack::_session_params::fNetworkLatency, Jack::_session_params::fPacketID, Jack::_session_params::fPeriodSize, Jack::_session_params::fProtocolVersion, Jack::_session_params::fReturnAudioChannels, Jack::_session_params::fReturnMidiChannels, Jack::_session_params::fSampleEncoder, Jack::_session_params::fSampleRate, Jack::_session_params::fSendAudioChannels, Jack::_session_params::fSendMidiChannels, Jack::_session_params::fSlaveSyncMode, Jack::_session_params::fTransportSync, and SERVER_EXPORT.
Referenced by Jack::JackNetMasterInterface::Init(), Jack::JackNetExtMaster::Open(), Jack::JackNetMasterManager::Run(), and Jack::JackNetSlaveInterface::SendAvailableToMaster().
SetNonBlocking()
void Jack::SetNonBlocking (int fd)
Definition at line 34 of file JackALSARawMidiUtil.cpp.
Referenced by CreateNonBlockingPipe().
SetPacketType()
SERVER_EXPORT int Jack::SetPacketType (session_params_t * params, sync_packet_type_t packet_type)
Definition at line 1192 of file JackNetTool.cpp.
References Jack::_session_params::fPacketID, INVALID, KILL_MASTER, SERVER_EXPORT, SLAVE_AVAILABLE, SLAVE_SETUP, START_MASTER, and START_SLAVE.
Referenced by Jack::JackNetMasterInterface::Exit(), Jack::JackNetMasterInterface::Init(), Jack::JackNetSlaveInterface::Init(), Jack::JackNetSlaveInterface::InitConnection(), and Jack::JackNetSlaveInterface::SendStartToMaster().
SocketAPIEnd()
SERVER_EXPORT int Jack::SocketAPIEnd ()
Definition at line 1367 of file JackNetTool.cpp.
References SERVER_EXPORT.
Referenced by Jack::JackNetSlaveInterface::~JackNetSlaveInterface(), and Jack::JackNetMasterManager::ShutDown().
SocketAPIInit()
SERVER_EXPORT int Jack::SocketAPIInit ()
Definition at line 1347 of file JackNetTool.cpp.
References jack_error, NET_ERROR_CODE, and SERVER_EXPORT.
Referenced by Jack::JackNetSlaveInterface::InitAPI(), Jack::JackNetExtMaster::Open(), and Jack::JackNetMasterManager::Run().
State2String()
const char * Jack::State2String (jack_client_state_t state) static
Definition at line 199 of file JackEngine.cpp.
References Finished, NotTriggered, Running, and Triggered.
Referenced by Jack::JackEngine::CheckXRun().
ThreadExit()
SERVER_EXPORT void Jack::ThreadExit ()
Definition at line 305 of file JackAndroidThread.cpp.
References jack_log(), and SERVER_EXPORT.
Referenced by Jack::JackNetMasterInterface::FatalRecvError(), and Jack::JackNetMasterInterface::FatalSendError().
TransportDataHToN()
SERVER_EXPORT void Jack::TransportDataHToN (net_transport_data_t * src_params, net_transport_data_t * dst_params)
Definition at line 1293 of file JackNetTool.cpp.
References _jack_position::audio_frames_per_video_frame, _jack_position::bar, _jack_position::bar_start_tick, _jack_position::bbt_offset, _jack_position::beat, _jack_position::beat_type, _jack_position::beats_per_bar, _jack_position::beats_per_minute, Jack::_net_transport_data::fNewState, Jack::_net_transport_data::fPosition, _jack_position::frame, _jack_position::frame_rate, _jack_position::frame_time, Jack::_net_transport_data::fState, Jack::_net_transport_data::fTimebaseMaster, htonll, _jack_position::next_time, SERVER_EXPORT, _jack_position::tick, _jack_position::ticks_per_beat, _jack_position::unique_1, _jack_position::unique_2, _jack_position::usecs, _jack_position::valid, and _jack_position::video_offset.
TransportDataNToH()
SERVER_EXPORT void Jack::TransportDataNToH (net_transport_data_t * src_params, net_transport_data_t * dst_params)
Definition at line 1319 of file JackNetTool.cpp.
References _jack_position::audio_frames_per_video_frame, _jack_position::bar, _jack_position::bar_start_tick, _jack_position::bbt_offset, _jack_position::beat, _jack_position::beat_type, _jack_position::beats_per_bar, _jack_position::beats_per_minute, Jack::_net_transport_data::fNewState, Jack::_net_transport_data::fPosition, _jack_position::frame, _jack_position::frame_rate, _jack_position::frame_time, Jack::_net_transport_data::fState, Jack::_net_transport_data::fTimebaseMaster, _jack_position::next_time, ntohll, SERVER_EXPORT, _jack_position::tick, _jack_position::ticks_per_beat, _jack_position::unique_1, _jack_position::unique_2, _jack_position::usecs, _jack_position::valid, and _jack_position::video_offset.
UnlockAllMemory()
void Jack::UnlockAllMemory ()
Definition at line 145 of file JackShmMem.cpp.
References CHECK_MUNLOCKALL, jack_error, and jack_log().
UnlockMemoryImp()
void Jack::UnlockMemoryImp (void * ptr, size_t size)
Definition at line 127 of file JackShmMem.cpp.
References CHECK_MUNLOCK, jack_error, and jack_log().
Referenced by Jack::JackShmMemAble::UnlockMemory().
WriteMacOSError()
void Jack::WriteMacOSError (const char * jack_function, const char * mac_function, OSStatus status)
Variable Documentation
device_reservation_loop_running
volatile bool Jack::device_reservation_loop_running = false static
Definition at line 70 of file JackAlsaDriver.cpp.
Referenced by Jack::JackAlsaDriver::Close(), Jack::JackPortAudioDriver::Close(), on_device_reservation_loop(), Jack::JackAlsaDriver::Open(), and Jack::JackPortAudioDriver::Open().
fKeyLogFunctionInitialized
bool Jack::fKeyLogFunctionInitialized = jack_tls_allocate_key(&JackGlobals::fKeyLogFunction) static
Definition at line 34 of file JackGlobals.cpp.
fSegmentNum
unsigned int Jack::fSegmentNum = 0 static
Definition at line 27 of file JackShmMem.cpp.
Referenced by Jack::JackShmMem::operator new().
gAudioPortType
const struct JackPortType Jack::gAudioPortType
Initial value:
=
{
    JACK_DEFAULT_AUDIO_TYPE,
    AudioBufferSize,
    AudioBufferInit,
    AudioBufferMixdown
}
Definition at line 162 of file JackAudioPort.cpp.
gInfo
jack_shm_info_t Jack::gInfo static
Definition at line 28 of file JackShmMem.cpp.
Referenced by Jack::JackShmMemAble::Init(), and Jack::JackShmMem::operator new().
gKeyNotificationThreadInitialized
bool Jack::gKeyNotificationThreadInitialized = jack_tls_allocate_key(&JackGlobals::fNotificationThread) static
Definition at line 31 of file JackGlobals.cpp.
gKeyRealtimeThreadInitialized
bool Jack::gKeyRealtimeThreadInitialized = jack_tls_allocate_key(&JackGlobals::fRealTimeThread) static
Definition at line 28 of file JackGlobals.cpp.
gMidiPortType
const struct JackPortType Jack::gMidiPortType
Initial value:
=
{
    JACK_DEFAULT_MIDI_TYPE,
    MidiBufferSize,
    MidiBufferInit,
    MidiBufferMixdown
}
Definition at line 154 of file JackMidiPort.cpp.
gPortTypes
const JackPortType* Jack::gPortTypes[] static
Initial value:
=
{
    &gAudioPortType,
    &gMidiPortType,
}
Definition at line 27 of file JackPortType.cpp.
Referenced by GetPortType(), and GetPortTypeId().
jack_tmpdir
char* Jack::jack_tmpdir = (char*)DEFAULT_TMP_DIR
Definition at line 58 of file JackTools.cpp.
Referenced by Jack::JackTools::GetTmpdir(), and Jack::JackTools::UserDir().
kAudioDeviceName
char const* const Jack::kAudioDeviceName = "/dev/eac" static
Definition at line 38 of file JackGoldfishDriver.cpp.
Referenced by Jack::JackGoldfishDriver::Open().
NetErrorList
win_net_error_t Jack::NetErrorList[]
Definition at line 36 of file JackNetWinSocket.cpp.
Referenced by PrintError().
pOpenSL_stream
OPENSL_STREAM* Jack::pOpenSL_stream static
Definition at line 42 of file JackOpenSLESDriver.cpp.
Referenced by Jack::JackOpenSLESDriver::Close(), Jack::JackOpenSLESDriver::Open(), Jack::JackOpenSLESDriver::Read(), and Jack::JackOpenSLESDriver::Write().
PORT_TYPES_MAX
const jack_port_type_id_t Jack::PORT_TYPES_MAX = sizeof(gPortTypes) / sizeof(gPortTypes[0])
Definition at line 33 of file JackPortType.cpp.
Referenced by Jack::JackPort::Allocate(), GetPortType(), GetPortTypeId(), and jack_port_type_get_buffer_size().
POST_PACKED_STRUCTURE
Jack::JackTransportEngine Jack::POST_PACKED_STRUCTURE