LMMS: hiir::Downsampler2x3dnow< NC > Class Template Reference
hiir::Downsampler2x3dnow< NC > Class Template Reference
#include <Downsampler2x3dnow.h>
Public Types
typedef float DataType
Public Member Functions
Downsampler2x3dnow () noexcept
Downsampler2x3dnow (const Downsampler2x3dnow< NC > &other)=default
Downsampler2x3dnow (Downsampler2x3dnow< NC > &&other)=default
~Downsampler2x3dnow ()=default
void clear_buffers () noexcept
Downsampler2x3dnow< NC > & operator= (const Downsampler2x3dnow< NC > &other)=default
Downsampler2x3dnow< NC > & operator= (Downsampler2x3dnow< NC > &&other)=default
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
void process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE float process_sample (const float in_ptr[2]) noexcept
hiir_FORCEINLINE void process_sample_split (float &low, float &high, const float in_ptr[2]) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = -1
static constexpr int _nbr_chn = 1
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageData3dnow, _nbr_stages+1 > Filter
Private Member Functions
bool operator!= (const Downsampler2x3dnow< NC > &other)=delete
bool operator== (const Downsampler2x3dnow< NC > &other)=delete
Private Attributes
Filter _filter
Static Private Attributes
static constexpr int _nbr_stages
static constexpr int _stage_width = 2
Detailed Description
template<int NC>
class hiir::Downsampler2x3dnow< NC >
Definition at line 48 of file Downsampler2x3dnow.h.
Member Typedef Documentation
DataType
template<int NC> typedef float hiir::Downsampler2x3dnow< NC >::DataType
Definition at line 57 of file Downsampler2x3dnow.h.
Filter
template<int NC> typedef std::array<StageData3dnow, _nbr_stages + 1> hiir::Downsampler2x3dnow< NC >::Filter private
Definition at line 100 of file Downsampler2x3dnow.h.
Constructor & Destructor Documentation
Downsampler2x3dnow() [1/3]
template<int NC> hiir::Downsampler2x3dnow< NC >::Downsampler2x3dnow () noexcept
Definition at line 75 of file Downsampler2x3dnow.hpp.
References _filter, _nbr_stages, clear_buffers(), i, and NBR_COEFS.
Referenced by Downsampler2x3dnow(), Downsampler2x3dnow(), ~Downsampler2x3dnow(), operator!=(), operator=(), operator=(), and operator==().
Downsampler2x3dnow() [2/3]
template<int NC> hiir::Downsampler2x3dnow< NC >::Downsampler2x3dnow (const Downsampler2x3dnow< NC > & other) default
References Downsampler2x3dnow().
Downsampler2x3dnow() [3/3]
template<int NC> hiir::Downsampler2x3dnow< NC >::Downsampler2x3dnow (Downsampler2x3dnow< NC > && other) default
References Downsampler2x3dnow().
~Downsampler2x3dnow()
template<int NC> hiir::Downsampler2x3dnow< NC >::~Downsampler2x3dnow () default
References Downsampler2x3dnow().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Downsampler2x3dnow< NC >::clear_buffers () noexcept
Definition at line 455 of file Downsampler2x3dnow.hpp.
References _filter, _nbr_stages, and i.
Referenced by Downsampler2x3dnow(), and operator=().
operator!=()
template<int NC> bool hiir::Downsampler2x3dnow< NC >::operator!= (const Downsampler2x3dnow< NC > & other) private delete
References Downsampler2x3dnow().
operator=() [1/2]
template<int NC> Downsampler2x3dnow< NC > & hiir::Downsampler2x3dnow< NC >::operator= (const Downsampler2x3dnow< NC > & other) default
References Downsampler2x3dnow().
operator=() [2/2]
template<int NC> Downsampler2x3dnow< NC > & hiir::Downsampler2x3dnow< NC >::operator= (Downsampler2x3dnow< NC > && other) default
References Downsampler2x3dnow(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_block_split(), process_sample(), process_sample_split(), and set_coefs().
operator==()
template<int NC> bool hiir::Downsampler2x3dnow< NC >::operator== (const Downsampler2x3dnow< NC > & other) private delete
References Downsampler2x3dnow().
process_block() [1/2]
template<int NC> void hiir::Downsampler2x3dnow< NC >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 183 of file Downsampler2x3dnow.hpp.
References _filter, _nbr_stages, hiir::Downsampler2x3dnow_half, and hiir::StageProc3dnow< CUR >::process_sample_pos().
Referenced by operator=().
process_block() [2/2]
void hiir::Downsampler2x3dnow< 8 >::process_block (float out_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 232 of file Downsampler2x3dnow.hpp.
References _filter, and hiir::Downsampler2x3dnow_half.
process_block_split()
template<int NC> void hiir::Downsampler2x3dnow< NC >::process_block_split (float out_l_ptr[], float out_h_ptr[], const float in_ptr[], long nbr_spl) noexcept
Definition at line 383 of file Downsampler2x3dnow.hpp.
References _filter, _nbr_stages, hiir::Downsampler2x3dnow_half, and hiir::StageProc3dnow< CUR >::process_sample_pos().
Referenced by operator=().
process_sample()
template<int NC> float hiir::Downsampler2x3dnow< NC >::process_sample (const float in_ptr[2]) noexcept
Definition at line 135 of file Downsampler2x3dnow.hpp.
References _filter, _nbr_stages, hiir::Downsampler2x3dnow_half, and hiir::StageProc3dnow< CUR >::process_sample_pos().
Referenced by operator=().
process_sample_split()
template<int NC> void hiir::Downsampler2x3dnow< NC >::process_sample_split (float & low, float & high, const float in_ptr[2]) noexcept
Definition at line 322 of file Downsampler2x3dnow.hpp.
References _filter, _nbr_stages, hiir::Downsampler2x3dnow_half, and hiir::StageProc3dnow< CUR >::process_sample_pos().
Referenced by operator=().
set_coefs()
template<int NC> void hiir::Downsampler2x3dnow< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 108 of file Downsampler2x3dnow.hpp.
References _filter, _stage_width, i, NBR_COEFS, and pos.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Downsampler2x3dnow< NC >::_delay = -1 static constexpr
Definition at line 60 of file Downsampler2x3dnow.h.
_filter
template<int NC> Filter hiir::Downsampler2x3dnow< NC >::_filter private
Definition at line 102 of file Downsampler2x3dnow.h.
Referenced by Downsampler2x3dnow(), clear_buffers(), process_block(), process_block_split(), process_sample(), process_sample_split(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Downsampler2x3dnow< NC >::_nbr_chn = 1 static constexpr
Definition at line 58 of file Downsampler2x3dnow.h.
_nbr_stages
template<int NC> int hiir::Downsampler2x3dnow< NC >::_nbr_stages static constexpr private
Initial value:
=
        (NBR_COEFS + _stage_width - 1) / _stage_width
Definition at line 97 of file Downsampler2x3dnow.h.
Referenced by Downsampler2x3dnow(), clear_buffers(), process_block(), process_block_split(), process_sample(), and process_sample_split().
_stage_width
template<int NC> int hiir::Downsampler2x3dnow< NC >::_stage_width = 2 static constexpr private
Definition at line 96 of file Downsampler2x3dnow.h.
Referenced by set_coefs().
NBR_COEFS
template<int NC> int hiir::Downsampler2x3dnow< NC >::NBR_COEFS = NC static constexpr
Definition at line 59 of file Downsampler2x3dnow.h.
Referenced by Downsampler2x3dnow(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Downsampler2x3dnow.h
src/3rdparty/hiir/hiir/Downsampler2x3dnow.hpp