LMMS: hiir::PhaseHalfPi2F64Sse2< NC > Class Template Reference
hiir::PhaseHalfPi2F64Sse2< NC > Class Template Reference
#include <PhaseHalfPi2F64Sse2.h>
Public Types
typedef double DataType
Public Member Functions
PhaseHalfPi2F64Sse2 () noexcept
PhaseHalfPi2F64Sse2 (const PhaseHalfPi2F64Sse2< NC > &other)=default
PhaseHalfPi2F64Sse2 (PhaseHalfPi2F64Sse2< NC > &&other)=default
~PhaseHalfPi2F64Sse2 ()=default
void clear_buffers () noexcept
PhaseHalfPi2F64Sse2< NC > & operator= (const PhaseHalfPi2F64Sse2< NC > &other)=default
PhaseHalfPi2F64Sse2< NC > & operator= (PhaseHalfPi2F64Sse2< NC > &&other)=default
void process_block (double out_0_ptr[], double out_1_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (__m128d &out_0, __m128d &out_1, __m128d input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 2
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Sse2, NBR_COEFS+2 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const PhaseHalfPi2F64Sse2 &other) const =delete
bool operator== (const PhaseHalfPi2F64Sse2 &other) const =delete
Private Attributes
FilterBiPhase _bifilter
int _phase
double _prev [_nbr_chn]
Static Private Attributes
static constexpr int _nbr_phases = 2
Detailed Description
template<int NC>
class hiir::PhaseHalfPi2F64Sse2< NC >
Definition at line 49 of file PhaseHalfPi2F64Sse2.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::PhaseHalfPi2F64Sse2< NC >::DataType
Definition at line 58 of file PhaseHalfPi2F64Sse2.h.
Filter
template<int NC> typedef std::array<StageDataF64Sse2, NBR_COEFS + 2> hiir::PhaseHalfPi2F64Sse2< NC >::Filter private
Definition at line 96 of file PhaseHalfPi2F64Sse2.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::PhaseHalfPi2F64Sse2< NC >::FilterBiPhase private
Definition at line 98 of file PhaseHalfPi2F64Sse2.h.
Constructor & Destructor Documentation
PhaseHalfPi2F64Sse2() [1/3]
template<int NC> hiir::PhaseHalfPi2F64Sse2< NC >::PhaseHalfPi2F64Sse2 () noexcept
Definition at line 55 of file PhaseHalfPi2F64Sse2.hpp.
References _bifilter, _phase, clear_buffers(), i, and NBR_COEFS.
Referenced by PhaseHalfPi2F64Sse2(), PhaseHalfPi2F64Sse2(), ~PhaseHalfPi2F64Sse2(), operator!=(), operator=(), operator=(), and operator==().
PhaseHalfPi2F64Sse2() [2/3]
template<int NC> hiir::PhaseHalfPi2F64Sse2< NC >::PhaseHalfPi2F64Sse2 (const PhaseHalfPi2F64Sse2< NC > & other) default
References PhaseHalfPi2F64Sse2().
PhaseHalfPi2F64Sse2() [3/3]
template<int NC> hiir::PhaseHalfPi2F64Sse2< NC >::PhaseHalfPi2F64Sse2 (PhaseHalfPi2F64Sse2< NC > && other) default
References PhaseHalfPi2F64Sse2().
~PhaseHalfPi2F64Sse2()
template<int NC> hiir::PhaseHalfPi2F64Sse2< NC >::~PhaseHalfPi2F64Sse2 () default
References PhaseHalfPi2F64Sse2().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::PhaseHalfPi2F64Sse2< NC >::clear_buffers () noexcept
Definition at line 224 of file PhaseHalfPi2F64Sse2.hpp.
References _bifilter, _phase, _prev, i, and NBR_COEFS.
Referenced by PhaseHalfPi2F64Sse2(), and operator=().
operator!=()
template<int NC> bool hiir::PhaseHalfPi2F64Sse2< NC >::operator!= (const PhaseHalfPi2F64Sse2< NC > & other) const private delete
References PhaseHalfPi2F64Sse2().
operator=() [1/2]
template<int NC> PhaseHalfPi2F64Sse2< NC > & hiir::PhaseHalfPi2F64Sse2< NC >::operator= (const PhaseHalfPi2F64Sse2< NC > & other) default
References PhaseHalfPi2F64Sse2().
operator=() [2/2]
template<int NC> PhaseHalfPi2F64Sse2< NC > & hiir::PhaseHalfPi2F64Sse2< NC >::operator= (PhaseHalfPi2F64Sse2< NC > && other) default
References PhaseHalfPi2F64Sse2(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::PhaseHalfPi2F64Sse2< NC >::operator== (const PhaseHalfPi2F64Sse2< NC > & other) const private delete
References PhaseHalfPi2F64Sse2().
process_block()
template<int NC> void hiir::PhaseHalfPi2F64Sse2< NC >::process_block (double out_0_ptr[], double out_1_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 148 of file PhaseHalfPi2F64Sse2.hpp.
References _bifilter, _nbr_chn, _nbr_phases, _phase, _prev, NBR_COEFS, pos, process_sample(), and hiir::StageProc2F64Sse2< REMAINING >::process_sample_neg().
Referenced by operator=().
process_sample()
template<int NC> void hiir::PhaseHalfPi2F64Sse2< NC >::process_sample (__m128d & out_0, __m128d & out_1, __m128d input) noexcept
Definition at line 115 of file PhaseHalfPi2F64Sse2.hpp.
References _bifilter, _phase, _prev, NBR_COEFS, and hiir::StageProc2F64Sse2< REMAINING >::process_sample_neg().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::PhaseHalfPi2F64Sse2< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 85 of file PhaseHalfPi2F64Sse2.hpp.
References _bifilter, i, and NBR_COEFS.
Referenced by operator=().
Member Data Documentation
_bifilter
template<int NC> FilterBiPhase hiir::PhaseHalfPi2F64Sse2< NC >::_bifilter private
Definition at line 100 of file PhaseHalfPi2F64Sse2.h.
Referenced by PhaseHalfPi2F64Sse2(), clear_buffers(), process_block(), process_sample(), and set_coefs().
_delay
template<int NC> double hiir::PhaseHalfPi2F64Sse2< NC >::_delay = 0 static constexpr
Definition at line 61 of file PhaseHalfPi2F64Sse2.h.
_nbr_chn
template<int NC> int hiir::PhaseHalfPi2F64Sse2< NC >::_nbr_chn = 2 static constexpr
Definition at line 59 of file PhaseHalfPi2F64Sse2.h.
Referenced by process_block().
_nbr_phases
template<int NC> int hiir::PhaseHalfPi2F64Sse2< NC >::_nbr_phases = 2 static constexpr private
Definition at line 93 of file PhaseHalfPi2F64Sse2.h.
Referenced by process_block().
_phase
template<int NC> int hiir::PhaseHalfPi2F64Sse2< NC >::_phase private
Definition at line 103 of file PhaseHalfPi2F64Sse2.h.
Referenced by PhaseHalfPi2F64Sse2(), clear_buffers(), process_block(), and process_sample().
_prev
template<int NC> double hiir::PhaseHalfPi2F64Sse2< NC >::_prev[_nbr_chn] private
Definition at line 102 of file PhaseHalfPi2F64Sse2.h.
Referenced by clear_buffers(), process_block(), and process_sample().
NBR_COEFS
template<int NC> int hiir::PhaseHalfPi2F64Sse2< NC >::NBR_COEFS = NC static constexpr
Definition at line 60 of file PhaseHalfPi2F64Sse2.h.
Referenced by PhaseHalfPi2F64Sse2(), clear_buffers(), process_block(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/PhaseHalfPi2F64Sse2.h
src/3rdparty/hiir/hiir/PhaseHalfPi2F64Sse2.hpp