LMMS: hiir Namespace Reference
hiir Namespace Reference
Classes
class Downsampler2x16Avx512
class Downsampler2x2F64Sse2
class Downsampler2x3dnow
class Downsampler2x4F64Avx
class Downsampler2x4Neon
class Downsampler2x4Sse
class Downsampler2x8Avx
class Downsampler2x8F64Avx512
class Downsampler2xF64Sse2
class Downsampler2xNeon
class Downsampler2xNeonOld
class Downsampler2xSse
class Downsampler2xSseOld
class Downsampler2xTpl
class HalfBand16Avx512
class HalfBand2F64Sse2
class HalfBand4F64Avx
class HalfBand4Neon
class HalfBand4Sse
class HalfBand8Avx
class HalfBand8F64Avx512
class HalfBandF64Sse2
class HalfBandNeon
class HalfBandSse
class HalfBandTpl
class PhaseHalfPi16Avx512
class PhaseHalfPi2F64Sse2
class PhaseHalfPi3dnow
class PhaseHalfPi4F64Avx
class PhaseHalfPi4Neon
class PhaseHalfPi4Sse
class PhaseHalfPi8Avx
class PhaseHalfPi8F64Avx512
class PhaseHalfPiF64Sse2
class PhaseHalfPiNeon
class PhaseHalfPiSse
class PhaseHalfPiTpl
class PolyphaseIir2Designer
class StageData3dnow
class StageDataAvx
class StageDataAvx512
class StageDataF64Avx
class StageDataF64Avx512
class StageDataF64Sse2
class StageDataNeonV2
class StageDataNeonV4
class StageDataSse
class StageDataTpl
class StageProc16Avx512
class StageProc2F64Sse2
class StageProc3dnow
class StageProc4F64Avx
class StageProc4Neon
class StageProc4Sse
class StageProc8Avx
class StageProc8F64Avx512
class StageProcF64Sse2
class StageProcNeonV2
class StageProcNeonV4
class StageProcSseV2
class StageProcSseV4
class StageProcTpl
class StageProcTpl< 0, DT >
class StageProcTpl< 1, DT >
class Upsampler2x16Avx512
class Upsampler2x2F64Sse2
class Upsampler2x3dnow
class Upsampler2x4F64Avx
class Upsampler2x4Neon
class Upsampler2x4Sse
class Upsampler2x8Avx
class Upsampler2x8F64Avx512
class Upsampler2xF64Sse2
class Upsampler2xNeon
class Upsampler2xNeonOld
class Upsampler2xSse
class Upsampler2xSseOld
class Upsampler2xTpl
Typedefs
template<int NC>
using Downsampler2xF64Fpu = Downsampler2xTpl <NC, double, 1>
template<int NC>
using Downsampler2xFpu = Downsampler2xTpl <NC, float, 1>
template<int NC>
using HalfBandF64Fpu = HalfBandTpl <NC, double, 1>
template<int NC>
using HalfBandFpu = HalfBandTpl <NC, float, 1>
template<int NC>
using PhaseHalfPiF64Fpu = PhaseHalfPiTpl <NC, double, 1>
template<int NC>
using PhaseHalfPiFpu = PhaseHalfPiTpl <NC, float, 1>
template<int NC>
using Upsampler2xF64Fpu = Upsampler2xTpl <NC, double, 1>
template<int NC>
using Upsampler2xFpu = Upsampler2xTpl <NC, float, 1>
Functions
int ceil_int (double x)
template<class T>
T ipowp (T x, long n) noexcept
hiir_FORCEINLINE float32x2_t load2a (const float *ptr) noexcept
hiir_FORCEINLINE float32x2_t load2u (const float *ptr) noexcept
hiir_FORCEINLINE float32x4_t load4a (const float *ptr) noexcept
hiir_FORCEINLINE float32x4_t load4u (const float *ptr) noexcept
int round_int (double x)
hiir_FORCEINLINE void storea (float *ptr, float32x2_t x) noexcept
hiir_FORCEINLINE void storea (float *ptr, float32x4_t x) noexcept
hiir_FORCEINLINE void storeu (float *ptr, float32x2_t x) noexcept
hiir_FORCEINLINE void storeu (float *ptr, float32x4_t x) noexcept
Variables
template<int NC>
constexpr double Downsampler2x16Avx512< NC >::_delay
template<int NC>
constexpr int Downsampler2x16Avx512< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2x16Avx512< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2x2F64Sse2< NC >::_delay
template<int NC>
constexpr int Downsampler2x2F64Sse2< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2x2F64Sse2< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2x3dnow< NC >::_delay
template<int NC>
constexpr int Downsampler2x3dnow< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2x3dnow< NC >::_nbr_stages
template<int NC>
constexpr int Downsampler2x3dnow< NC >::_stage_width
template<int NC>
constexpr int Downsampler2x3dnow< NC >::NBR_COEFS
static const float Downsampler2x3dnow_half [2] = { 0.5f, 0.5f }
template<int NC>
constexpr double Downsampler2x4F64Avx< NC >::_delay
template<int NC>
constexpr int Downsampler2x4F64Avx< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2x4F64Avx< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2x4Neon< NC >::_delay
template<int NC>
constexpr int Downsampler2x4Neon< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2x4Neon< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2x4Sse< NC >::_delay
template<int NC>
constexpr int Downsampler2x4Sse< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2x4Sse< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2x8Avx< NC >::_delay
template<int NC>
constexpr int Downsampler2x8Avx< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2x8Avx< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2x8F64Avx512< NC >::_delay
template<int NC>
constexpr int Downsampler2x8F64Avx512< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2x8F64Avx512< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2xF64Sse2< NC >::_delay
template<int NC>
constexpr int Downsampler2xF64Sse2< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2xF64Sse2< NC >::_nbr_stages
template<int NC>
constexpr int Downsampler2xF64Sse2< NC >::_stage_width
template<int NC>
constexpr int Downsampler2xF64Sse2< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2xNeon< NC >::_delay
template<int NC>
constexpr int Downsampler2xNeon< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2xNeon< NC >::_nbr_stages
template<int NC>
constexpr int Downsampler2xNeon< NC >::_stage_width
template<int NC>
constexpr int Downsampler2xNeon< NC >::NBR_COEFS
template<int NC>
constexpr int Downsampler2xNeonOld< NC >::_coef_shift
template<int NC>
constexpr double Downsampler2xNeonOld< NC >::_delay
template<int NC>
constexpr int Downsampler2xNeonOld< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2xNeonOld< NC >::_nbr_stages
template<int NC>
constexpr int Downsampler2xNeonOld< NC >::_stage_width
template<int NC>
constexpr int Downsampler2xNeonOld< NC >::NBR_COEFS
template<int NC>
constexpr double Downsampler2xSse< NC >::_delay
template<int NC>
constexpr int Downsampler2xSse< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2xSse< NC >::_nbr_stages
template<int NC>
constexpr int Downsampler2xSse< NC >::_stage_width
template<int NC>
constexpr int Downsampler2xSse< NC >::NBR_COEFS
template<int NC>
constexpr int Downsampler2xSseOld< NC >::_coef_shift
template<int NC>
constexpr double Downsampler2xSseOld< NC >::_delay
template<int NC>
constexpr int Downsampler2xSseOld< NC >::_nbr_chn
template<int NC>
constexpr int Downsampler2xSseOld< NC >::_nbr_stages
template<int NC>
constexpr int Downsampler2xSseOld< NC >::_stage_width
template<int NC>
constexpr int Downsampler2xSseOld< NC >::NBR_COEFS
template<int NC, typename DT, int NCHN>
constexpr double Downsampler2xTpl< NC, DT, NCHN >::_delay
template<int NC, typename DT, int NCHN>
constexpr int Downsampler2xTpl< NC, DT, NCHN >::_nbr_chn
template<int NC, typename DT, int NCHN>
constexpr int Downsampler2xTpl< NC, DT, NCHN >::NBR_COEFS
template<int NC>
constexpr double HalfBand16Avx512< NC >::_delay
template<int NC>
constexpr int HalfBand16Avx512< NC >::_nbr_chn
template<int NC>
constexpr int HalfBand16Avx512< NC >::_nbr_phases
template<int NC>
constexpr int HalfBand16Avx512< NC >::NBR_COEFS
template<int NC>
constexpr double HalfBand2F64Sse2< NC >::_delay
template<int NC>
constexpr int HalfBand2F64Sse2< NC >::_nbr_chn
template<int NC>
constexpr int HalfBand2F64Sse2< NC >::_nbr_phases
template<int NC>
constexpr int HalfBand2F64Sse2< NC >::NBR_COEFS
template<int NC>
constexpr double HalfBand4F64Avx< NC >::_delay
template<int NC>
constexpr int HalfBand4F64Avx< NC >::_nbr_chn
template<int NC>
constexpr int HalfBand4F64Avx< NC >::_nbr_phases
template<int NC>
constexpr int HalfBand4F64Avx< NC >::NBR_COEFS
template<int NC>
constexpr double HalfBand4Neon< NC >::_delay
template<int NC>
constexpr int HalfBand4Neon< NC >::_nbr_chn
template<int NC>
constexpr int HalfBand4Neon< NC >::_nbr_phases
template<int NC>
constexpr int HalfBand4Neon< NC >::NBR_COEFS
template<int NC>
constexpr double HalfBand4Sse< NC >::_delay
template<int NC>
constexpr int HalfBand4Sse< NC >::_nbr_chn
template<int NC>
constexpr int HalfBand4Sse< NC >::_nbr_phases
template<int NC>
constexpr int HalfBand4Sse< NC >::NBR_COEFS
template<int NC>
constexpr double HalfBand8Avx< NC >::_delay
template<int NC>
constexpr int HalfBand8Avx< NC >::_nbr_chn
template<int NC>
constexpr int HalfBand8Avx< NC >::_nbr_phases
template<int NC>
constexpr int HalfBand8Avx< NC >::NBR_COEFS
template<int NC>
constexpr double HalfBand8F64Avx512< NC >::_delay
template<int NC>
constexpr int HalfBand8F64Avx512< NC >::_nbr_chn
template<int NC>
constexpr int HalfBand8F64Avx512< NC >::_nbr_phases
template<int NC>
constexpr int HalfBand8F64Avx512< NC >::NBR_COEFS
template<int NC>
constexpr double HalfBandF64Sse2< NC >::_delay
template<int NC>
constexpr int HalfBandF64Sse2< NC >::_nbr_chn
template<int NC>
constexpr int HalfBandF64Sse2< NC >::_nbr_phases
template<int NC>
constexpr int HalfBandF64Sse2< NC >::_nbr_stages
template<int NC>
constexpr int HalfBandF64Sse2< NC >::_stage_width
template<int NC>
constexpr int HalfBandF64Sse2< NC >::NBR_COEFS
template<int NC>
constexpr int HalfBandNeon< NC >::_coef_shift
template<int NC>
constexpr double HalfBandNeon< NC >::_delay
template<int NC>
constexpr int HalfBandNeon< NC >::_nbr_chn
template<int NC>
constexpr int HalfBandNeon< NC >::_nbr_phases
template<int NC>
constexpr int HalfBandNeon< NC >::_nbr_stages
template<int NC>
constexpr int HalfBandNeon< NC >::_stage_width
template<int NC>
constexpr int HalfBandNeon< NC >::NBR_COEFS
template<int NC>
constexpr int HalfBandSse< NC >::_coef_shift
template<int NC>
constexpr double HalfBandSse< NC >::_delay
template<int NC>
constexpr int HalfBandSse< NC >::_nbr_chn
template<int NC>
constexpr int HalfBandSse< NC >::_nbr_phases
template<int NC>
constexpr int HalfBandSse< NC >::_nbr_stages
template<int NC>
constexpr int HalfBandSse< NC >::_stage_width
template<int NC>
constexpr int HalfBandSse< NC >::NBR_COEFS
template<int NC, typename DT, int NCHN>
constexpr double HalfBandTpl< NC, DT, NCHN >::_delay
template<int NC, typename DT, int NCHN>
constexpr int HalfBandTpl< NC, DT, NCHN >::_nbr_chn
template<int NC, typename DT, int NCHN>
constexpr int HalfBandTpl< NC, DT, NCHN >::_nbr_phases
template<int NC, typename DT, int NCHN>
constexpr int HalfBandTpl< NC, DT, NCHN >::NBR_COEFS
template<int NC>
constexpr double PhaseHalfPi16Avx512< NC >::_delay
template<int NC>
constexpr int PhaseHalfPi16Avx512< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPi16Avx512< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPi16Avx512< NC >::NBR_COEFS
template<int NC>
constexpr int PhaseHalfPi2F64Sse2< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPi2F64Sse2< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPi2F64Sse2< NC >::NBR_COEFS
template<int NC>
constexpr double PhaseHalfPi3dnow< NC >::_delay
template<int NC>
constexpr int PhaseHalfPi3dnow< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPi3dnow< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPi3dnow< NC >::_nbr_stages
template<int NC>
constexpr int PhaseHalfPi3dnow< NC >::_stage_width
template<int NC>
constexpr int PhaseHalfPi3dnow< NC >::NBR_COEFS
template<int NC>
constexpr double PhaseHalfPi4F64Avx< NC >::_delay
template<int NC>
constexpr int PhaseHalfPi4F64Avx< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPi4F64Avx< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPi4F64Avx< NC >::NBR_COEFS
template<int NC>
constexpr double PhaseHalfPi4Neon< NC >::_delay
template<int NC>
constexpr int PhaseHalfPi4Neon< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPi4Neon< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPi4Neon< NC >::NBR_COEFS
template<int NC>
constexpr double PhaseHalfPi4Sse< NC >::_delay
template<int NC>
constexpr int PhaseHalfPi4Sse< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPi4Sse< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPi4Sse< NC >::NBR_COEFS
template<int NC>
constexpr double PhaseHalfPi8Avx< NC >::_delay
template<int NC>
constexpr int PhaseHalfPi8Avx< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPi8Avx< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPi8Avx< NC >::NBR_COEFS
template<int NC>
constexpr double PhaseHalfPi8F64Avx512< NC >::_delay
template<int NC>
constexpr int PhaseHalfPi8F64Avx512< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPi8F64Avx512< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPi8F64Avx512< NC >::NBR_COEFS
template<int NC>
constexpr double PhaseHalfPiF64Sse2< NC >::_delay
template<int NC>
constexpr int PhaseHalfPiF64Sse2< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPiF64Sse2< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPiF64Sse2< NC >::_nbr_stages
template<int NC>
constexpr int PhaseHalfPiF64Sse2< NC >::_stage_width
template<int NC>
constexpr int PhaseHalfPiF64Sse2< NC >::NBR_COEFS
template<int NC>
constexpr int PhaseHalfPiNeon< NC >::_coef_shift
template<int NC>
constexpr double PhaseHalfPiNeon< NC >::_delay
template<int NC>
constexpr int PhaseHalfPiNeon< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPiNeon< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPiNeon< NC >::_nbr_stages
template<int NC>
constexpr int PhaseHalfPiNeon< NC >::_stage_width
template<int NC>
constexpr int PhaseHalfPiNeon< NC >::NBR_COEFS
template<int NC>
constexpr int PhaseHalfPiSse< NC >::_coef_shift
template<int NC>
constexpr double PhaseHalfPiSse< NC >::_delay
template<int NC>
constexpr int PhaseHalfPiSse< NC >::_nbr_chn
template<int NC>
constexpr int PhaseHalfPiSse< NC >::_nbr_phases
template<int NC>
constexpr int PhaseHalfPiSse< NC >::_nbr_stages
template<int NC>
constexpr int PhaseHalfPiSse< NC >::_stage_width
template<int NC>
constexpr int PhaseHalfPiSse< NC >::NBR_COEFS
template<int NC, typename DT, int NCHN>
constexpr double PhaseHalfPiTpl< NC, DT, NCHN >::_delay
template<int NC, typename DT, int NCHN>
constexpr int PhaseHalfPiTpl< NC, DT, NCHN >::_nbr_chn
template<int NC, typename DT, int NCHN>
constexpr int PhaseHalfPiTpl< NC, DT, NCHN >::_nbr_phases
template<int NC, typename DT, int NCHN>
constexpr int PhaseHalfPiTpl< NC, DT, NCHN >::NBR_COEFS
const double PI = 3.1415926535897932384626433832795
template<int NC>
constexpr int Upsampler2x16Avx512< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2x16Avx512< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2x2F64Sse2< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2x2F64Sse2< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2x3dnow< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2x3dnow< NC >::_nbr_stages
template<int NC>
constexpr int Upsampler2x3dnow< NC >::_stage_width
template<int NC>
constexpr int Upsampler2x3dnow< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2x4F64Avx< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2x4F64Avx< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2x4Neon< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2x4Neon< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2x4Sse< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2x4Sse< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2x8Avx< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2x8Avx< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2x8F64Avx512< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2x8F64Avx512< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2xF64Sse2< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2xF64Sse2< NC >::_nbr_stages
template<int NC>
constexpr int Upsampler2xF64Sse2< NC >::_stage_width
template<int NC>
constexpr int Upsampler2xF64Sse2< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2xNeon< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2xNeon< NC >::_nbr_stages
template<int NC>
constexpr int Upsampler2xNeon< NC >::_stage_width
template<int NC>
constexpr int Upsampler2xNeon< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2xNeonOld< NC >::_coef_shift
template<int NC>
constexpr int Upsampler2xNeonOld< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2xNeonOld< NC >::_nbr_stages
template<int NC>
constexpr int Upsampler2xNeonOld< NC >::_stage_width
template<int NC>
constexpr int Upsampler2xNeonOld< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2xSse< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2xSse< NC >::_nbr_stages
template<int NC>
constexpr int Upsampler2xSse< NC >::_stage_width
template<int NC>
constexpr int Upsampler2xSse< NC >::NBR_COEFS
template<int NC>
constexpr int Upsampler2xSseOld< NC >::_coef_shift
template<int NC>
constexpr int Upsampler2xSseOld< NC >::_nbr_chn
template<int NC>
constexpr int Upsampler2xSseOld< NC >::_nbr_stages
template<int NC>
constexpr int Upsampler2xSseOld< NC >::_stage_width
template<int NC>
constexpr int Upsampler2xSseOld< NC >::NBR_COEFS
template<int NC, typename DT, int NCHN>
constexpr int Upsampler2xTpl< NC, DT, NCHN >::_nbr_chn
template<int NC, typename DT, int NCHN>
constexpr int Upsampler2xTpl< NC, DT, NCHN >::NBR_COEFS
Typedef Documentation
Downsampler2xF64Fpu
template<int NC> using hiir::Downsampler2xF64Fpu = Downsampler2xTpl <NC, double, 1>
Definition at line 36 of file Downsampler2xF64Fpu.h.
Downsampler2xFpu
template<int NC> using hiir::Downsampler2xFpu = Downsampler2xTpl <NC, float, 1>
Definition at line 36 of file Downsampler2xFpu.h.
HalfBandF64Fpu
template<int NC> using hiir::HalfBandF64Fpu = HalfBandTpl <NC, double, 1>
Definition at line 36 of file HalfBandF64Fpu.h.
HalfBandFpu
template<int NC> using hiir::HalfBandFpu = HalfBandTpl <NC, float, 1>
Definition at line 36 of file HalfBandFpu.h.
PhaseHalfPiF64Fpu
template<int NC> using hiir::PhaseHalfPiF64Fpu = PhaseHalfPiTpl <NC, double, 1>
Definition at line 36 of file PhaseHalfPiF64Fpu.h.
PhaseHalfPiFpu
template<int NC> using hiir::PhaseHalfPiFpu = PhaseHalfPiTpl <NC, float, 1>
Definition at line 36 of file PhaseHalfPiFpu.h.
Upsampler2xF64Fpu
template<int NC> using hiir::Upsampler2xF64Fpu = Upsampler2xTpl <NC, double, 1>
Definition at line 36 of file Upsampler2xF64Fpu.h.
Upsampler2xFpu
template<int NC> using hiir::Upsampler2xFpu = Upsampler2xTpl <NC, float, 1>
Definition at line 36 of file Upsampler2xFpu.h.
Function Documentation
ceil_int()
int hiir::ceil_int (double x) inline
Definition at line 47 of file fnc.hpp.
Referenced by hiir::PolyphaseIir2Designer::compute_order().
ipowp()
template<class T> T hiir::ipowp (T x, long n) noexcept
Definition at line 55 of file fnc.hpp.
Referenced by hiir::PolyphaseIir2Designer::compute_acc_den(), and hiir::PolyphaseIir2Designer::compute_acc_num().
load2a()
float32x2_t hiir::load2a (const float * ptr) noexcept
Definition at line 52 of file fnc_neon.hpp.
Referenced by hiir::HalfBandNeon< NC >::process_2_paths(), hiir::PhaseHalfPiNeon< NC >::process_sample(), hiir::StageProcNeonV2< CUR >::process_sample_neg_rec(), and hiir::StageProcNeonV2< CUR >::process_sample_pos_rec().
load2u()
float32x2_t hiir::load2u (const float * ptr) noexcept
Definition at line 59 of file fnc_neon.hpp.
Referenced by hiir::Downsampler2xNeon< NC >::process_sample(), and hiir::Downsampler2xNeon< NC >::process_sample_split().
load4a()
float32x4_t hiir::load4a (const float * ptr) noexcept
Definition at line 36 of file fnc_neon.hpp.
Referenced by hiir::HalfBand4Neon< NC >::process_2_paths(), hiir::HalfBandNeon< NC >::process_2_paths(), hiir::PhaseHalfPi4Neon< NC >::process_block(), hiir::HalfBand4Neon< NC >::process_block_2_paths(), hiir::Downsampler2xNeonOld< NC >::process_block_quad(), hiir::HalfBandNeon< NC >::process_block_quad(), hiir::PhaseHalfPiNeon< NC >::process_block_quad(), hiir::Upsampler2xNeonOld< NC >::process_block_quad(), hiir::Downsampler2xNeonOld< NC >::process_sample(), hiir::PhaseHalfPi4Neon< NC >::process_sample(), hiir::PhaseHalfPiNeon< NC >::process_sample(), hiir::Upsampler2xNeonOld< NC >::process_sample(), hiir::StageProc4Neon< REMAINING >::process_sample_neg(), hiir::StageProcNeonV4< CUR >::process_sample_neg_rec(), hiir::StageProc4Neon< REMAINING >::process_sample_pos(), hiir::StageProcNeonV4< CUR >::process_sample_pos_rec(), and hiir::Downsampler2xNeonOld< NC >::process_sample_split().
load4u()
float32x4_t hiir::load4u (const float * ptr) noexcept
Definition at line 43 of file fnc_neon.hpp.
Referenced by hiir::PhaseHalfPi4Neon< NC >::process_block(), hiir::Upsampler2x4Neon< NC >::process_block(), hiir::HalfBand4Neon< NC >::process_block_2_paths(), hiir::Downsampler2xNeon< NC >::process_block_quad(), hiir::Downsampler2xNeonOld< NC >::process_block_quad(), hiir::HalfBandNeon< NC >::process_block_quad(), hiir::PhaseHalfPiNeon< NC >::process_block_quad(), hiir::Upsampler2xNeon< NC >::process_block_quad(), hiir::Upsampler2xNeonOld< NC >::process_block_quad(), hiir::Downsampler2x4Neon< NC >::process_sample(), and hiir::Downsampler2x4Neon< NC >::process_sample_split().
round_int()
int hiir::round_int (double x) inline
Definition at line 40 of file fnc.hpp.
storea() [1/2]
void hiir::storea (float * ptr, float32x2_t x) noexcept
Definition at line 82 of file fnc_neon.hpp.
storea() [2/2]
void hiir::storea (float * ptr, float32x4_t x) noexcept
Definition at line 68 of file fnc_neon.hpp.
Referenced by hiir::Downsampler2x4Neon< NC >::Downsampler2x4Neon(), hiir::Downsampler2xNeon< NC >::Downsampler2xNeon(), hiir::Downsampler2xNeonOld< NC >::Downsampler2xNeonOld(), hiir::HalfBand4Neon< NC >::HalfBand4Neon(), hiir::HalfBandNeon< NC >::HalfBandNeon(), hiir::PhaseHalfPi4Neon< NC >::PhaseHalfPi4Neon(), hiir::PhaseHalfPiNeon< NC >::PhaseHalfPiNeon(), hiir::Upsampler2x4Neon< NC >::Upsampler2x4Neon(), hiir::Upsampler2xNeon< NC >::Upsampler2xNeon(), hiir::Upsampler2xNeonOld< NC >::Upsampler2xNeonOld(), hiir::Downsampler2x4Neon< NC >::clear_buffers(), hiir::Downsampler2xNeon< NC >::clear_buffers(), hiir::Downsampler2xNeonOld< NC >::clear_buffers(), hiir::HalfBand4Neon< NC >::clear_buffers(), hiir::HalfBandNeon< NC >::clear_buffers(), hiir::PhaseHalfPi4Neon< NC >::clear_buffers(), hiir::PhaseHalfPiNeon< NC >::clear_buffers(), hiir::Upsampler2x4Neon< NC >::clear_buffers(), hiir::Upsampler2xNeon< NC >::clear_buffers(), hiir::Upsampler2xNeonOld< NC >::clear_buffers(), hiir::HalfBand4Neon< NC >::process_2_paths(), hiir::PhaseHalfPi4Neon< NC >::process_block(), hiir::HalfBand4Neon< NC >::process_block_2_paths(), hiir::Downsampler2xNeonOld< NC >::process_block_quad(), hiir::HalfBandNeon< NC >::process_block_quad(), hiir::PhaseHalfPiNeon< NC >::process_block_quad(), hiir::Upsampler2xNeonOld< NC >::process_block_quad(), hiir::PhaseHalfPi4Neon< NC >::process_sample(), hiir::StageProc4Neon< REMAINING >::process_sample_neg(), hiir::StageProcNeonV2< CUR >::process_sample_neg(), hiir::StageProcNeonV4< CUR >::process_sample_neg(), hiir::StageProcNeonV2< CUR >::process_sample_neg_rec(), hiir::StageProcNeonV4< CUR >::process_sample_neg_rec(), hiir::StageProc4Neon< REMAINING >::process_sample_pos(), hiir::StageProcNeonV2< CUR >::process_sample_pos(), hiir::StageProcNeonV4< CUR >::process_sample_pos(), hiir::StageProcNeonV2< CUR >::process_sample_pos_rec(), hiir::StageProcNeonV4< CUR >::process_sample_pos_rec(), hiir::Downsampler2x4Neon< NC >::set_coefs(), hiir::HalfBand4Neon< NC >::set_coefs(), hiir::PhaseHalfPi4Neon< NC >::set_coefs(), and hiir::Upsampler2x4Neon< NC >::set_coefs().
storeu() [1/2]
void hiir::storeu (float * ptr, float32x2_t x) noexcept
Definition at line 89 of file fnc_neon.hpp.
storeu() [2/2]
void hiir::storeu (float * ptr, float32x4_t x) noexcept
Definition at line 75 of file fnc_neon.hpp.
Referenced by hiir::Downsampler2x4Neon< NC >::process_block(), hiir::PhaseHalfPi4Neon< NC >::process_block(), hiir::Upsampler2x4Neon< NC >::process_block(), hiir::PhaseHalfPiNeon< NC >::process_block_quad(), hiir::Upsampler2xNeon< NC >::process_block_quad(), hiir::Upsampler2xNeonOld< NC >::process_block_quad(), hiir::Downsampler2x4Neon< NC >::process_block_split(), hiir::Downsampler2xNeon< NC >::store_high(), hiir::Downsampler2xNeonOld< NC >::store_high(), hiir::HalfBand4Neon< NC >::store_high(), hiir::HalfBandNeon< NC >::store_high(), hiir::Downsampler2xNeon< NC >::store_low(), hiir::Downsampler2xNeonOld< NC >::store_low(), hiir::HalfBand4Neon< NC >::store_low(), and hiir::HalfBandNeon< NC >::store_low().
Variable Documentation
Downsampler2x16Avx512< NC >::_delay
template<int NC> double hiir::Downsampler2x16Avx512< NC >::_delay constexpr
Definition at line 45 of file Downsampler2x16Avx512.hpp.
Downsampler2x16Avx512< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2x16Avx512< NC >::_nbr_chn constexpr
Definition at line 41 of file Downsampler2x16Avx512.hpp.
Downsampler2x16Avx512< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2x16Avx512< NC >::NBR_COEFS constexpr
Definition at line 43 of file Downsampler2x16Avx512.hpp.
Downsampler2x2F64Sse2< NC >::_delay
template<int NC> double hiir::Downsampler2x2F64Sse2< NC >::_delay constexpr
Definition at line 46 of file Downsampler2x2F64Sse2.hpp.
Downsampler2x2F64Sse2< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2x2F64Sse2< NC >::_nbr_chn constexpr
Definition at line 42 of file Downsampler2x2F64Sse2.hpp.
Downsampler2x2F64Sse2< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2x2F64Sse2< NC >::NBR_COEFS constexpr
Definition at line 44 of file Downsampler2x2F64Sse2.hpp.
Downsampler2x3dnow< NC >::_delay
template<int NC> double hiir::Downsampler2x3dnow< NC >::_delay constexpr
Definition at line 63 of file Downsampler2x3dnow.hpp.
Downsampler2x3dnow< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2x3dnow< NC >::_nbr_chn constexpr
Definition at line 59 of file Downsampler2x3dnow.hpp.
Downsampler2x3dnow< NC >::_nbr_stages
template<int NC> int hiir::Downsampler2x3dnow< NC >::_nbr_stages constexpr
Definition at line 477 of file Downsampler2x3dnow.hpp.
Downsampler2x3dnow< NC >::_stage_width
template<int NC> int hiir::Downsampler2x3dnow< NC >::_stage_width constexpr
Definition at line 475 of file Downsampler2x3dnow.hpp.
Downsampler2x3dnow< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2x3dnow< NC >::NBR_COEFS constexpr
Definition at line 61 of file Downsampler2x3dnow.hpp.
Downsampler2x3dnow_half
const float hiir::Downsampler2x3dnow_half[2] = { 0.5f, 0.5f } static
Definition at line 50 of file Downsampler2x3dnow.hpp.
Referenced by hiir::Downsampler2x3dnow< NC >::process_block(), hiir::Downsampler2x3dnow< NC >::process_block_split(), hiir::Downsampler2x3dnow< NC >::process_sample(), and hiir::Downsampler2x3dnow< NC >::process_sample_split().
Downsampler2x4F64Avx< NC >::_delay
template<int NC> double hiir::Downsampler2x4F64Avx< NC >::_delay constexpr
Definition at line 46 of file Downsampler2x4F64Avx.hpp.
Downsampler2x4F64Avx< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2x4F64Avx< NC >::_nbr_chn constexpr
Definition at line 42 of file Downsampler2x4F64Avx.hpp.
Downsampler2x4F64Avx< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2x4F64Avx< NC >::NBR_COEFS constexpr
Definition at line 44 of file Downsampler2x4F64Avx.hpp.
Downsampler2x4Neon< NC >::_delay
template<int NC> double hiir::Downsampler2x4Neon< NC >::_delay constexpr
Definition at line 46 of file Downsampler2x4Neon.hpp.
Downsampler2x4Neon< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2x4Neon< NC >::_nbr_chn constexpr
Definition at line 42 of file Downsampler2x4Neon.hpp.
Downsampler2x4Neon< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2x4Neon< NC >::NBR_COEFS constexpr
Definition at line 44 of file Downsampler2x4Neon.hpp.
Downsampler2x4Sse< NC >::_delay
template<int NC> double hiir::Downsampler2x4Sse< NC >::_delay constexpr
Definition at line 45 of file Downsampler2x4Sse.hpp.
Downsampler2x4Sse< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2x4Sse< NC >::_nbr_chn constexpr
Definition at line 41 of file Downsampler2x4Sse.hpp.
Downsampler2x4Sse< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2x4Sse< NC >::NBR_COEFS constexpr
Definition at line 43 of file Downsampler2x4Sse.hpp.
Downsampler2x8Avx< NC >::_delay
template<int NC> double hiir::Downsampler2x8Avx< NC >::_delay constexpr
Definition at line 46 of file Downsampler2x8Avx.hpp.
Downsampler2x8Avx< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2x8Avx< NC >::_nbr_chn constexpr
Definition at line 42 of file Downsampler2x8Avx.hpp.
Downsampler2x8Avx< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2x8Avx< NC >::NBR_COEFS constexpr
Definition at line 44 of file Downsampler2x8Avx.hpp.
Downsampler2x8F64Avx512< NC >::_delay
template<int NC> double hiir::Downsampler2x8F64Avx512< NC >::_delay constexpr
Definition at line 45 of file Downsampler2x8F64Avx512.hpp.
Downsampler2x8F64Avx512< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2x8F64Avx512< NC >::_nbr_chn constexpr
Definition at line 41 of file Downsampler2x8F64Avx512.hpp.
Downsampler2x8F64Avx512< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2x8F64Avx512< NC >::NBR_COEFS constexpr
Definition at line 43 of file Downsampler2x8F64Avx512.hpp.
Downsampler2xF64Sse2< NC >::_delay
template<int NC> double hiir::Downsampler2xF64Sse2< NC >::_delay constexpr
Definition at line 45 of file Downsampler2xF64Sse2.hpp.
Downsampler2xF64Sse2< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2xF64Sse2< NC >::_nbr_chn constexpr
Definition at line 41 of file Downsampler2xF64Sse2.hpp.
Downsampler2xF64Sse2< NC >::_nbr_stages
template<int NC> int hiir::Downsampler2xF64Sse2< NC >::_nbr_stages constexpr
Definition at line 276 of file Downsampler2xF64Sse2.hpp.
Downsampler2xF64Sse2< NC >::_stage_width
template<int NC> int hiir::Downsampler2xF64Sse2< NC >::_stage_width constexpr
Definition at line 274 of file Downsampler2xF64Sse2.hpp.
Downsampler2xF64Sse2< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2xF64Sse2< NC >::NBR_COEFS constexpr
Definition at line 43 of file Downsampler2xF64Sse2.hpp.
Downsampler2xNeon< NC >::_delay
template<int NC> double hiir::Downsampler2xNeon< NC >::_delay constexpr
Definition at line 48 of file Downsampler2xNeon.hpp.
Downsampler2xNeon< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2xNeon< NC >::_nbr_chn constexpr
Definition at line 44 of file Downsampler2xNeon.hpp.
Downsampler2xNeon< NC >::_nbr_stages
template<int NC> int hiir::Downsampler2xNeon< NC >::_nbr_stages constexpr
Definition at line 287 of file Downsampler2xNeon.hpp.
Downsampler2xNeon< NC >::_stage_width
template<int NC> int hiir::Downsampler2xNeon< NC >::_stage_width constexpr
Definition at line 285 of file Downsampler2xNeon.hpp.
Downsampler2xNeon< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2xNeon< NC >::NBR_COEFS constexpr
Definition at line 46 of file Downsampler2xNeon.hpp.
Downsampler2xNeonOld< NC >::_coef_shift
template<int NC> int hiir::Downsampler2xNeonOld< NC >::_coef_shift constexpr
Definition at line 304 of file Downsampler2xNeonOld.hpp.
Downsampler2xNeonOld< NC >::_delay
template<int NC> double hiir::Downsampler2xNeonOld< NC >::_delay constexpr
Definition at line 48 of file Downsampler2xNeonOld.hpp.
Downsampler2xNeonOld< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2xNeonOld< NC >::_nbr_chn constexpr
Definition at line 44 of file Downsampler2xNeonOld.hpp.
Downsampler2xNeonOld< NC >::_nbr_stages
template<int NC> int hiir::Downsampler2xNeonOld< NC >::_nbr_stages constexpr
Definition at line 302 of file Downsampler2xNeonOld.hpp.
Downsampler2xNeonOld< NC >::_stage_width
template<int NC> int hiir::Downsampler2xNeonOld< NC >::_stage_width constexpr
Definition at line 300 of file Downsampler2xNeonOld.hpp.
Downsampler2xNeonOld< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2xNeonOld< NC >::NBR_COEFS constexpr
Definition at line 46 of file Downsampler2xNeonOld.hpp.
Downsampler2xSse< NC >::_delay
template<int NC> double hiir::Downsampler2xSse< NC >::_delay constexpr
Definition at line 45 of file Downsampler2xSse.hpp.
Downsampler2xSse< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2xSse< NC >::_nbr_chn constexpr
Definition at line 41 of file Downsampler2xSse.hpp.
Downsampler2xSse< NC >::_nbr_stages
template<int NC> int hiir::Downsampler2xSse< NC >::_nbr_stages constexpr
Definition at line 351 of file Downsampler2xSse.hpp.
Downsampler2xSse< NC >::_stage_width
template<int NC> int hiir::Downsampler2xSse< NC >::_stage_width constexpr
Definition at line 349 of file Downsampler2xSse.hpp.
Downsampler2xSse< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2xSse< NC >::NBR_COEFS constexpr
Definition at line 43 of file Downsampler2xSse.hpp.
Downsampler2xSseOld< NC >::_coef_shift
template<int NC> int hiir::Downsampler2xSseOld< NC >::_coef_shift constexpr
Definition at line 314 of file Downsampler2xSseOld.hpp.
Downsampler2xSseOld< NC >::_delay
template<int NC> double hiir::Downsampler2xSseOld< NC >::_delay constexpr
Definition at line 52 of file Downsampler2xSseOld.hpp.
Downsampler2xSseOld< NC >::_nbr_chn
template<int NC> int hiir::Downsampler2xSseOld< NC >::_nbr_chn constexpr
Definition at line 48 of file Downsampler2xSseOld.hpp.
Downsampler2xSseOld< NC >::_nbr_stages
template<int NC> int hiir::Downsampler2xSseOld< NC >::_nbr_stages constexpr
Definition at line 312 of file Downsampler2xSseOld.hpp.
Downsampler2xSseOld< NC >::_stage_width
template<int NC> int hiir::Downsampler2xSseOld< NC >::_stage_width constexpr
Definition at line 310 of file Downsampler2xSseOld.hpp.
Downsampler2xSseOld< NC >::NBR_COEFS
template<int NC> int hiir::Downsampler2xSseOld< NC >::NBR_COEFS constexpr
Definition at line 50 of file Downsampler2xSseOld.hpp.
Downsampler2xTpl< NC, DT, NCHN >::_delay
template<int NC, typename DT, int NCHN> double hiir::Downsampler2xTpl< NC, DT, NCHN >::_delay constexpr
Definition at line 50 of file Downsampler2xTpl.hpp.
Downsampler2xTpl< NC, DT, NCHN >::_nbr_chn
template<int NC, typename DT, int NCHN> int hiir::Downsampler2xTpl< NC, DT, NCHN >::_nbr_chn constexpr
Definition at line 46 of file Downsampler2xTpl.hpp.
Downsampler2xTpl< NC, DT, NCHN >::NBR_COEFS
template<int NC, typename DT, int NCHN> int hiir::Downsampler2xTpl< NC, DT, NCHN >::NBR_COEFS constexpr
Definition at line 48 of file Downsampler2xTpl.hpp.
HalfBand16Avx512< NC >::_delay
template<int NC> double hiir::HalfBand16Avx512< NC >::_delay constexpr
Definition at line 45 of file HalfBand16Avx512.hpp.
HalfBand16Avx512< NC >::_nbr_chn
template<int NC> int hiir::HalfBand16Avx512< NC >::_nbr_chn constexpr
Definition at line 41 of file HalfBand16Avx512.hpp.
HalfBand16Avx512< NC >::_nbr_phases
template<int NC> int hiir::HalfBand16Avx512< NC >::_nbr_phases constexpr
Definition at line 300 of file HalfBand16Avx512.hpp.
HalfBand16Avx512< NC >::NBR_COEFS
template<int NC> int hiir::HalfBand16Avx512< NC >::NBR_COEFS constexpr
Definition at line 43 of file HalfBand16Avx512.hpp.
HalfBand2F64Sse2< NC >::_delay
template<int NC> double hiir::HalfBand2F64Sse2< NC >::_delay constexpr
Definition at line 45 of file HalfBand2F64Sse2.hpp.
HalfBand2F64Sse2< NC >::_nbr_chn
template<int NC> int hiir::HalfBand2F64Sse2< NC >::_nbr_chn constexpr
Definition at line 41 of file HalfBand2F64Sse2.hpp.
HalfBand2F64Sse2< NC >::_nbr_phases
template<int NC> int hiir::HalfBand2F64Sse2< NC >::_nbr_phases constexpr
Definition at line 300 of file HalfBand2F64Sse2.hpp.
HalfBand2F64Sse2< NC >::NBR_COEFS
template<int NC> int hiir::HalfBand2F64Sse2< NC >::NBR_COEFS constexpr
Definition at line 43 of file HalfBand2F64Sse2.hpp.
HalfBand4F64Avx< NC >::_delay
template<int NC> double hiir::HalfBand4F64Avx< NC >::_delay constexpr
Definition at line 45 of file HalfBand4F64Avx.hpp.
HalfBand4F64Avx< NC >::_nbr_chn
template<int NC> int hiir::HalfBand4F64Avx< NC >::_nbr_chn constexpr
Definition at line 41 of file HalfBand4F64Avx.hpp.
HalfBand4F64Avx< NC >::_nbr_phases
template<int NC> int hiir::HalfBand4F64Avx< NC >::_nbr_phases constexpr
Definition at line 300 of file HalfBand4F64Avx.hpp.
HalfBand4F64Avx< NC >::NBR_COEFS
template<int NC> int hiir::HalfBand4F64Avx< NC >::NBR_COEFS constexpr
Definition at line 43 of file HalfBand4F64Avx.hpp.
HalfBand4Neon< NC >::_delay
template<int NC> double hiir::HalfBand4Neon< NC >::_delay constexpr
Definition at line 46 of file HalfBand4Neon.hpp.
HalfBand4Neon< NC >::_nbr_chn
template<int NC> int hiir::HalfBand4Neon< NC >::_nbr_chn constexpr
Definition at line 42 of file HalfBand4Neon.hpp.
HalfBand4Neon< NC >::_nbr_phases
template<int NC> int hiir::HalfBand4Neon< NC >::_nbr_phases constexpr
Definition at line 301 of file HalfBand4Neon.hpp.
HalfBand4Neon< NC >::NBR_COEFS
template<int NC> int hiir::HalfBand4Neon< NC >::NBR_COEFS constexpr
Definition at line 44 of file HalfBand4Neon.hpp.
HalfBand4Sse< NC >::_delay
template<int NC> double hiir::HalfBand4Sse< NC >::_delay constexpr
Definition at line 45 of file HalfBand4Sse.hpp.
HalfBand4Sse< NC >::_nbr_chn
template<int NC> int hiir::HalfBand4Sse< NC >::_nbr_chn constexpr
Definition at line 41 of file HalfBand4Sse.hpp.
HalfBand4Sse< NC >::_nbr_phases
template<int NC> int hiir::HalfBand4Sse< NC >::_nbr_phases constexpr
Definition at line 300 of file HalfBand4Sse.hpp.
HalfBand4Sse< NC >::NBR_COEFS
template<int NC> int hiir::HalfBand4Sse< NC >::NBR_COEFS constexpr
Definition at line 43 of file HalfBand4Sse.hpp.
HalfBand8Avx< NC >::_delay
template<int NC> double hiir::HalfBand8Avx< NC >::_delay constexpr
Definition at line 45 of file HalfBand8Avx.hpp.
HalfBand8Avx< NC >::_nbr_chn
template<int NC> int hiir::HalfBand8Avx< NC >::_nbr_chn constexpr
Definition at line 41 of file HalfBand8Avx.hpp.
HalfBand8Avx< NC >::_nbr_phases
template<int NC> int hiir::HalfBand8Avx< NC >::_nbr_phases constexpr
Definition at line 300 of file HalfBand8Avx.hpp.
HalfBand8Avx< NC >::NBR_COEFS
template<int NC> int hiir::HalfBand8Avx< NC >::NBR_COEFS constexpr
Definition at line 43 of file HalfBand8Avx.hpp.
HalfBand8F64Avx512< NC >::_delay
template<int NC> double hiir::HalfBand8F64Avx512< NC >::_delay constexpr
Definition at line 45 of file HalfBand8F64Avx512.hpp.
HalfBand8F64Avx512< NC >::_nbr_chn
template<int NC> int hiir::HalfBand8F64Avx512< NC >::_nbr_chn constexpr
Definition at line 41 of file HalfBand8F64Avx512.hpp.
HalfBand8F64Avx512< NC >::_nbr_phases
template<int NC> int hiir::HalfBand8F64Avx512< NC >::_nbr_phases constexpr
Definition at line 300 of file HalfBand8F64Avx512.hpp.
HalfBand8F64Avx512< NC >::NBR_COEFS
template<int NC> int hiir::HalfBand8F64Avx512< NC >::NBR_COEFS constexpr
Definition at line 43 of file HalfBand8F64Avx512.hpp.
HalfBandF64Sse2< NC >::_delay
template<int NC> double hiir::HalfBandF64Sse2< NC >::_delay constexpr
Definition at line 47 of file HalfBandF64Sse2.hpp.
HalfBandF64Sse2< NC >::_nbr_chn
template<int NC> int hiir::HalfBandF64Sse2< NC >::_nbr_chn constexpr
Definition at line 43 of file HalfBandF64Sse2.hpp.
HalfBandF64Sse2< NC >::_nbr_phases
template<int NC> int hiir::HalfBandF64Sse2< NC >::_nbr_phases constexpr
Definition at line 318 of file HalfBandF64Sse2.hpp.
HalfBandF64Sse2< NC >::_nbr_stages
template<int NC> int hiir::HalfBandF64Sse2< NC >::_nbr_stages constexpr
Definition at line 316 of file HalfBandF64Sse2.hpp.
HalfBandF64Sse2< NC >::_stage_width
template<int NC> int hiir::HalfBandF64Sse2< NC >::_stage_width constexpr
Definition at line 314 of file HalfBandF64Sse2.hpp.
HalfBandF64Sse2< NC >::NBR_COEFS
template<int NC> int hiir::HalfBandF64Sse2< NC >::NBR_COEFS constexpr
Definition at line 45 of file HalfBandF64Sse2.hpp.
HalfBandNeon< NC >::_coef_shift
template<int NC> int hiir::HalfBandNeon< NC >::_coef_shift constexpr
Definition at line 371 of file HalfBandNeon.hpp.
HalfBandNeon< NC >::_delay
template<int NC> double hiir::HalfBandNeon< NC >::_delay constexpr
Definition at line 46 of file HalfBandNeon.hpp.
HalfBandNeon< NC >::_nbr_chn
template<int NC> int hiir::HalfBandNeon< NC >::_nbr_chn constexpr
Definition at line 42 of file HalfBandNeon.hpp.
HalfBandNeon< NC >::_nbr_phases
template<int NC> int hiir::HalfBandNeon< NC >::_nbr_phases constexpr
Definition at line 369 of file HalfBandNeon.hpp.
HalfBandNeon< NC >::_nbr_stages
template<int NC> int hiir::HalfBandNeon< NC >::_nbr_stages constexpr
Definition at line 367 of file HalfBandNeon.hpp.
HalfBandNeon< NC >::_stage_width
template<int NC> int hiir::HalfBandNeon< NC >::_stage_width constexpr
Definition at line 365 of file HalfBandNeon.hpp.
HalfBandNeon< NC >::NBR_COEFS
template<int NC> int hiir::HalfBandNeon< NC >::NBR_COEFS constexpr
Definition at line 44 of file HalfBandNeon.hpp.
HalfBandSse< NC >::_coef_shift
template<int NC> int hiir::HalfBandSse< NC >::_coef_shift constexpr
Definition at line 375 of file HalfBandSse.hpp.
HalfBandSse< NC >::_delay
template<int NC> double hiir::HalfBandSse< NC >::_delay constexpr
Definition at line 53 of file HalfBandSse.hpp.
HalfBandSse< NC >::_nbr_chn
template<int NC> int hiir::HalfBandSse< NC >::_nbr_chn constexpr
Definition at line 49 of file HalfBandSse.hpp.
HalfBandSse< NC >::_nbr_phases
template<int NC> int hiir::HalfBandSse< NC >::_nbr_phases constexpr
Definition at line 373 of file HalfBandSse.hpp.
HalfBandSse< NC >::_nbr_stages
template<int NC> int hiir::HalfBandSse< NC >::_nbr_stages constexpr
Definition at line 371 of file HalfBandSse.hpp.
HalfBandSse< NC >::_stage_width
template<int NC> int hiir::HalfBandSse< NC >::_stage_width constexpr
Definition at line 369 of file HalfBandSse.hpp.
HalfBandSse< NC >::NBR_COEFS
template<int NC> int hiir::HalfBandSse< NC >::NBR_COEFS constexpr
Definition at line 51 of file HalfBandSse.hpp.
HalfBandTpl< NC, DT, NCHN >::_delay
template<int NC, typename DT, int NCHN> double hiir::HalfBandTpl< NC, DT, NCHN >::_delay constexpr
Definition at line 45 of file HalfBandTpl.hpp.
HalfBandTpl< NC, DT, NCHN >::_nbr_chn
template<int NC, typename DT, int NCHN> int hiir::HalfBandTpl< NC, DT, NCHN >::_nbr_chn constexpr
Definition at line 41 of file HalfBandTpl.hpp.
HalfBandTpl< NC, DT, NCHN >::_nbr_phases
template<int NC, typename DT, int NCHN> int hiir::HalfBandTpl< NC, DT, NCHN >::_nbr_phases constexpr
Definition at line 286 of file HalfBandTpl.hpp.
HalfBandTpl< NC, DT, NCHN >::NBR_COEFS
template<int NC, typename DT, int NCHN> int hiir::HalfBandTpl< NC, DT, NCHN >::NBR_COEFS constexpr
Definition at line 43 of file HalfBandTpl.hpp.
PhaseHalfPi16Avx512< NC >::_delay
template<int NC> double hiir::PhaseHalfPi16Avx512< NC >::_delay constexpr
Definition at line 45 of file PhaseHalfPi16Avx512.hpp.
PhaseHalfPi16Avx512< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPi16Avx512< NC >::_nbr_chn constexpr
Definition at line 41 of file PhaseHalfPi16Avx512.hpp.
PhaseHalfPi16Avx512< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPi16Avx512< NC >::_nbr_phases constexpr
Definition at line 248 of file PhaseHalfPi16Avx512.hpp.
PhaseHalfPi16Avx512< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPi16Avx512< NC >::NBR_COEFS constexpr
Definition at line 43 of file PhaseHalfPi16Avx512.hpp.
PhaseHalfPi2F64Sse2< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPi2F64Sse2< NC >::_nbr_chn constexpr
Definition at line 41 of file PhaseHalfPi2F64Sse2.hpp.
PhaseHalfPi2F64Sse2< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPi2F64Sse2< NC >::_nbr_phases constexpr
Definition at line 246 of file PhaseHalfPi2F64Sse2.hpp.
PhaseHalfPi2F64Sse2< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPi2F64Sse2< NC >::NBR_COEFS constexpr
Definition at line 43 of file PhaseHalfPi2F64Sse2.hpp.
PhaseHalfPi3dnow< NC >::_delay
template<int NC> double hiir::PhaseHalfPi3dnow< NC >::_delay constexpr
Definition at line 59 of file PhaseHalfPi3dnow.hpp.
PhaseHalfPi3dnow< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_nbr_chn constexpr
Definition at line 55 of file PhaseHalfPi3dnow.hpp.
PhaseHalfPi3dnow< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_nbr_phases constexpr
Definition at line 321 of file PhaseHalfPi3dnow.hpp.
PhaseHalfPi3dnow< NC >::_nbr_stages
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_nbr_stages constexpr
Definition at line 319 of file PhaseHalfPi3dnow.hpp.
PhaseHalfPi3dnow< NC >::_stage_width
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::_stage_width constexpr
Definition at line 317 of file PhaseHalfPi3dnow.hpp.
PhaseHalfPi3dnow< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPi3dnow< NC >::NBR_COEFS constexpr
Definition at line 57 of file PhaseHalfPi3dnow.hpp.
PhaseHalfPi4F64Avx< NC >::_delay
template<int NC> double hiir::PhaseHalfPi4F64Avx< NC >::_delay constexpr
Definition at line 45 of file PhaseHalfPi4F64Avx.hpp.
PhaseHalfPi4F64Avx< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPi4F64Avx< NC >::_nbr_chn constexpr
Definition at line 41 of file PhaseHalfPi4F64Avx.hpp.
PhaseHalfPi4F64Avx< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPi4F64Avx< NC >::_nbr_phases constexpr
Definition at line 248 of file PhaseHalfPi4F64Avx.hpp.
PhaseHalfPi4F64Avx< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPi4F64Avx< NC >::NBR_COEFS constexpr
Definition at line 43 of file PhaseHalfPi4F64Avx.hpp.
PhaseHalfPi4Neon< NC >::_delay
template<int NC> double hiir::PhaseHalfPi4Neon< NC >::_delay constexpr
Definition at line 46 of file PhaseHalfPi4Neon.hpp.
PhaseHalfPi4Neon< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPi4Neon< NC >::_nbr_chn constexpr
Definition at line 42 of file PhaseHalfPi4Neon.hpp.
PhaseHalfPi4Neon< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPi4Neon< NC >::_nbr_phases constexpr
Definition at line 249 of file PhaseHalfPi4Neon.hpp.
PhaseHalfPi4Neon< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPi4Neon< NC >::NBR_COEFS constexpr
Definition at line 44 of file PhaseHalfPi4Neon.hpp.
PhaseHalfPi4Sse< NC >::_delay
template<int NC> double hiir::PhaseHalfPi4Sse< NC >::_delay constexpr
Definition at line 45 of file PhaseHalfPi4Sse.hpp.
PhaseHalfPi4Sse< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPi4Sse< NC >::_nbr_chn constexpr
Definition at line 41 of file PhaseHalfPi4Sse.hpp.
PhaseHalfPi4Sse< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPi4Sse< NC >::_nbr_phases constexpr
Definition at line 248 of file PhaseHalfPi4Sse.hpp.
PhaseHalfPi4Sse< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPi4Sse< NC >::NBR_COEFS constexpr
Definition at line 43 of file PhaseHalfPi4Sse.hpp.
PhaseHalfPi8Avx< NC >::_delay
template<int NC> double hiir::PhaseHalfPi8Avx< NC >::_delay constexpr
Definition at line 45 of file PhaseHalfPi8Avx.hpp.
PhaseHalfPi8Avx< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPi8Avx< NC >::_nbr_chn constexpr
Definition at line 41 of file PhaseHalfPi8Avx.hpp.
PhaseHalfPi8Avx< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPi8Avx< NC >::_nbr_phases constexpr
Definition at line 248 of file PhaseHalfPi8Avx.hpp.
PhaseHalfPi8Avx< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPi8Avx< NC >::NBR_COEFS constexpr
Definition at line 43 of file PhaseHalfPi8Avx.hpp.
PhaseHalfPi8F64Avx512< NC >::_delay
template<int NC> double hiir::PhaseHalfPi8F64Avx512< NC >::_delay constexpr
Definition at line 45 of file PhaseHalfPi8F64Avx512.hpp.
PhaseHalfPi8F64Avx512< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPi8F64Avx512< NC >::_nbr_chn constexpr
Definition at line 41 of file PhaseHalfPi8F64Avx512.hpp.
PhaseHalfPi8F64Avx512< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPi8F64Avx512< NC >::_nbr_phases constexpr
Definition at line 248 of file PhaseHalfPi8F64Avx512.hpp.
PhaseHalfPi8F64Avx512< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPi8F64Avx512< NC >::NBR_COEFS constexpr
Definition at line 43 of file PhaseHalfPi8F64Avx512.hpp.
PhaseHalfPiF64Sse2< NC >::_delay
template<int NC> double hiir::PhaseHalfPiF64Sse2< NC >::_delay constexpr
Definition at line 45 of file PhaseHalfPiF64Sse2.hpp.
PhaseHalfPiF64Sse2< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_nbr_chn constexpr
Definition at line 41 of file PhaseHalfPiF64Sse2.hpp.
PhaseHalfPiF64Sse2< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_nbr_phases constexpr
Definition at line 248 of file PhaseHalfPiF64Sse2.hpp.
PhaseHalfPiF64Sse2< NC >::_nbr_stages
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_nbr_stages constexpr
Definition at line 246 of file PhaseHalfPiF64Sse2.hpp.
PhaseHalfPiF64Sse2< NC >::_stage_width
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::_stage_width constexpr
Definition at line 244 of file PhaseHalfPiF64Sse2.hpp.
PhaseHalfPiF64Sse2< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPiF64Sse2< NC >::NBR_COEFS constexpr
Definition at line 43 of file PhaseHalfPiF64Sse2.hpp.
PhaseHalfPiNeon< NC >::_coef_shift
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_coef_shift constexpr
Definition at line 239 of file PhaseHalfPiNeon.hpp.
PhaseHalfPiNeon< NC >::_delay
template<int NC> double hiir::PhaseHalfPiNeon< NC >::_delay constexpr
Definition at line 46 of file PhaseHalfPiNeon.hpp.
PhaseHalfPiNeon< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_nbr_chn constexpr
Definition at line 42 of file PhaseHalfPiNeon.hpp.
PhaseHalfPiNeon< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_nbr_phases constexpr
Definition at line 237 of file PhaseHalfPiNeon.hpp.
PhaseHalfPiNeon< NC >::_nbr_stages
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_nbr_stages constexpr
Definition at line 235 of file PhaseHalfPiNeon.hpp.
PhaseHalfPiNeon< NC >::_stage_width
template<int NC> int hiir::PhaseHalfPiNeon< NC >::_stage_width constexpr
Definition at line 233 of file PhaseHalfPiNeon.hpp.
PhaseHalfPiNeon< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPiNeon< NC >::NBR_COEFS constexpr
Definition at line 44 of file PhaseHalfPiNeon.hpp.
PhaseHalfPiSse< NC >::_coef_shift
template<int NC> int hiir::PhaseHalfPiSse< NC >::_coef_shift constexpr
Definition at line 244 of file PhaseHalfPiSse.hpp.
PhaseHalfPiSse< NC >::_delay
template<int NC> double hiir::PhaseHalfPiSse< NC >::_delay constexpr
Definition at line 52 of file PhaseHalfPiSse.hpp.
PhaseHalfPiSse< NC >::_nbr_chn
template<int NC> int hiir::PhaseHalfPiSse< NC >::_nbr_chn constexpr
Definition at line 48 of file PhaseHalfPiSse.hpp.
PhaseHalfPiSse< NC >::_nbr_phases
template<int NC> int hiir::PhaseHalfPiSse< NC >::_nbr_phases constexpr
Definition at line 242 of file PhaseHalfPiSse.hpp.
PhaseHalfPiSse< NC >::_nbr_stages
template<int NC> int hiir::PhaseHalfPiSse< NC >::_nbr_stages constexpr
Definition at line 240 of file PhaseHalfPiSse.hpp.
PhaseHalfPiSse< NC >::_stage_width
template<int NC> int hiir::PhaseHalfPiSse< NC >::_stage_width constexpr
Definition at line 238 of file PhaseHalfPiSse.hpp.
PhaseHalfPiSse< NC >::NBR_COEFS
template<int NC> int hiir::PhaseHalfPiSse< NC >::NBR_COEFS constexpr
Definition at line 50 of file PhaseHalfPiSse.hpp.
PhaseHalfPiTpl< NC, DT, NCHN >::_delay
template<int NC, typename DT, int NCHN> double hiir::PhaseHalfPiTpl< NC, DT, NCHN >::_delay constexpr
Definition at line 48 of file PhaseHalfPiTpl.hpp.
PhaseHalfPiTpl< NC, DT, NCHN >::_nbr_chn
template<int NC, typename DT, int NCHN> int hiir::PhaseHalfPiTpl< NC, DT, NCHN >::_nbr_chn constexpr
Definition at line 44 of file PhaseHalfPiTpl.hpp.
PhaseHalfPiTpl< NC, DT, NCHN >::_nbr_phases
template<int NC, typename DT, int NCHN> int hiir::PhaseHalfPiTpl< NC, DT, NCHN >::_nbr_phases constexpr
Definition at line 216 of file PhaseHalfPiTpl.hpp.
PhaseHalfPiTpl< NC, DT, NCHN >::NBR_COEFS
template<int NC, typename DT, int NCHN> int hiir::PhaseHalfPiTpl< NC, DT, NCHN >::NBR_COEFS constexpr
Definition at line 46 of file PhaseHalfPiTpl.hpp.
PI
const double hiir::PI = 3.1415926535897932384626433832795
Definition at line 75 of file def.h.
Referenced by hiir::PolyphaseIir2Designer::compute_acc_den(), hiir::PolyphaseIir2Designer::compute_acc_num(), hiir::PolyphaseIir2Designer::compute_phase_delay(), hiir::PolyphaseIir2Designer::compute_transition_param(), hiir::PolyphaseIir2Designer::compute_unit_group_delay(), and hiir::PolyphaseIir2Designer::compute_unit_phase_delay().
Upsampler2x16Avx512< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2x16Avx512< NC >::_nbr_chn constexpr
Definition at line 41 of file Upsampler2x16Avx512.hpp.
Upsampler2x16Avx512< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2x16Avx512< NC >::NBR_COEFS constexpr
Definition at line 43 of file Upsampler2x16Avx512.hpp.
Upsampler2x2F64Sse2< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2x2F64Sse2< NC >::_nbr_chn constexpr
Definition at line 42 of file Upsampler2x2F64Sse2.hpp.
Upsampler2x2F64Sse2< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2x2F64Sse2< NC >::NBR_COEFS constexpr
Definition at line 44 of file Upsampler2x2F64Sse2.hpp.
Upsampler2x3dnow< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2x3dnow< NC >::_nbr_chn constexpr
Definition at line 55 of file Upsampler2x3dnow.hpp.
Upsampler2x3dnow< NC >::_nbr_stages
template<int NC> int hiir::Upsampler2x3dnow< NC >::_nbr_stages constexpr
Definition at line 327 of file Upsampler2x3dnow.hpp.
Upsampler2x3dnow< NC >::_stage_width
template<int NC> int hiir::Upsampler2x3dnow< NC >::_stage_width constexpr
Definition at line 325 of file Upsampler2x3dnow.hpp.
Upsampler2x3dnow< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2x3dnow< NC >::NBR_COEFS constexpr
Definition at line 57 of file Upsampler2x3dnow.hpp.
Upsampler2x4F64Avx< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2x4F64Avx< NC >::_nbr_chn constexpr
Definition at line 42 of file Upsampler2x4F64Avx.hpp.
Upsampler2x4F64Avx< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2x4F64Avx< NC >::NBR_COEFS constexpr
Definition at line 44 of file Upsampler2x4F64Avx.hpp.
Upsampler2x4Neon< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2x4Neon< NC >::_nbr_chn constexpr
Definition at line 42 of file Upsampler2x4Neon.hpp.
Upsampler2x4Neon< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2x4Neon< NC >::NBR_COEFS constexpr
Definition at line 44 of file Upsampler2x4Neon.hpp.
Upsampler2x4Sse< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2x4Sse< NC >::_nbr_chn constexpr
Definition at line 41 of file Upsampler2x4Sse.hpp.
Upsampler2x4Sse< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2x4Sse< NC >::NBR_COEFS constexpr
Definition at line 43 of file Upsampler2x4Sse.hpp.
Upsampler2x8Avx< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2x8Avx< NC >::_nbr_chn constexpr
Definition at line 42 of file Upsampler2x8Avx.hpp.
Upsampler2x8Avx< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2x8Avx< NC >::NBR_COEFS constexpr
Definition at line 44 of file Upsampler2x8Avx.hpp.
Upsampler2x8F64Avx512< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2x8F64Avx512< NC >::_nbr_chn constexpr
Definition at line 41 of file Upsampler2x8F64Avx512.hpp.
Upsampler2x8F64Avx512< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2x8F64Avx512< NC >::NBR_COEFS constexpr
Definition at line 43 of file Upsampler2x8F64Avx512.hpp.
Upsampler2xF64Sse2< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2xF64Sse2< NC >::_nbr_chn constexpr
Definition at line 41 of file Upsampler2xF64Sse2.hpp.
Upsampler2xF64Sse2< NC >::_nbr_stages
template<int NC> int hiir::Upsampler2xF64Sse2< NC >::_nbr_stages constexpr
Definition at line 191 of file Upsampler2xF64Sse2.hpp.
Upsampler2xF64Sse2< NC >::_stage_width
template<int NC> int hiir::Upsampler2xF64Sse2< NC >::_stage_width constexpr
Definition at line 189 of file Upsampler2xF64Sse2.hpp.
Upsampler2xF64Sse2< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2xF64Sse2< NC >::NBR_COEFS constexpr
Definition at line 43 of file Upsampler2xF64Sse2.hpp.
Upsampler2xNeon< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2xNeon< NC >::_nbr_chn constexpr
Definition at line 43 of file Upsampler2xNeon.hpp.
Upsampler2xNeon< NC >::_nbr_stages
template<int NC> int hiir::Upsampler2xNeon< NC >::_nbr_stages constexpr
Definition at line 194 of file Upsampler2xNeon.hpp.
Upsampler2xNeon< NC >::_stage_width
template<int NC> int hiir::Upsampler2xNeon< NC >::_stage_width constexpr
Definition at line 192 of file Upsampler2xNeon.hpp.
Upsampler2xNeon< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2xNeon< NC >::NBR_COEFS constexpr
Definition at line 45 of file Upsampler2xNeon.hpp.
Upsampler2xNeonOld< NC >::_coef_shift
template<int NC> int hiir::Upsampler2xNeonOld< NC >::_coef_shift constexpr
Definition at line 198 of file Upsampler2xNeonOld.hpp.
Upsampler2xNeonOld< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2xNeonOld< NC >::_nbr_chn constexpr
Definition at line 43 of file Upsampler2xNeonOld.hpp.
Upsampler2xNeonOld< NC >::_nbr_stages
template<int NC> int hiir::Upsampler2xNeonOld< NC >::_nbr_stages constexpr
Definition at line 196 of file Upsampler2xNeonOld.hpp.
Upsampler2xNeonOld< NC >::_stage_width
template<int NC> int hiir::Upsampler2xNeonOld< NC >::_stage_width constexpr
Definition at line 194 of file Upsampler2xNeonOld.hpp.
Upsampler2xNeonOld< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2xNeonOld< NC >::NBR_COEFS constexpr
Definition at line 45 of file Upsampler2xNeonOld.hpp.
Upsampler2xSse< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2xSse< NC >::_nbr_chn constexpr
Definition at line 43 of file Upsampler2xSse.hpp.
Upsampler2xSse< NC >::_nbr_stages
template<int NC> int hiir::Upsampler2xSse< NC >::_nbr_stages constexpr
Definition at line 222 of file Upsampler2xSse.hpp.
Upsampler2xSse< NC >::_stage_width
template<int NC> int hiir::Upsampler2xSse< NC >::_stage_width constexpr
Definition at line 220 of file Upsampler2xSse.hpp.
Upsampler2xSse< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2xSse< NC >::NBR_COEFS constexpr
Definition at line 45 of file Upsampler2xSse.hpp.
Upsampler2xSseOld< NC >::_coef_shift
template<int NC> int hiir::Upsampler2xSseOld< NC >::_coef_shift constexpr
Definition at line 207 of file Upsampler2xSseOld.hpp.
Upsampler2xSseOld< NC >::_nbr_chn
template<int NC> int hiir::Upsampler2xSseOld< NC >::_nbr_chn constexpr
Definition at line 48 of file Upsampler2xSseOld.hpp.
Upsampler2xSseOld< NC >::_nbr_stages
template<int NC> int hiir::Upsampler2xSseOld< NC >::_nbr_stages constexpr
Definition at line 205 of file Upsampler2xSseOld.hpp.
Upsampler2xSseOld< NC >::_stage_width
template<int NC> int hiir::Upsampler2xSseOld< NC >::_stage_width constexpr
Definition at line 203 of file Upsampler2xSseOld.hpp.
Upsampler2xSseOld< NC >::NBR_COEFS
template<int NC> int hiir::Upsampler2xSseOld< NC >::NBR_COEFS constexpr
Definition at line 50 of file Upsampler2xSseOld.hpp.
Upsampler2xTpl< NC, DT, NCHN >::_nbr_chn
template<int NC, typename DT, int NCHN> int hiir::Upsampler2xTpl< NC, DT, NCHN >::_nbr_chn constexpr
Definition at line 46 of file Upsampler2xTpl.hpp.
Upsampler2xTpl< NC, DT, NCHN >::NBR_COEFS
template<int NC, typename DT, int NCHN> int hiir::Upsampler2xTpl< NC, DT, NCHN >::NBR_COEFS constexpr
Definition at line 48 of file Upsampler2xTpl.hpp.