LMMS: lmms::StepRecorder Class Reference
lmms::StepRecorder Class Reference
#include <StepRecorder.h>
Classes
class StepNote
Public Member Functions
StepRecorder (gui::PianoRoll &pianoRoll, gui::StepRecorderWidget &stepRecorderWidget)
std::vector< Note * > getCurStepNotes ()
void initialize ()
bool isRecording () const
bool keyPressEvent (QKeyEvent *ke)
bool mousePressEvent (QMouseEvent *ke)
void notePressed (const Note &n)
void noteReleased (const Note &n)
void setCurrentMidiClip (MidiClip *newMidiClip)
void setStepsLength (const TimePos &newLength)
void start (const TimePos &currentPosition, const TimePos &stepLength)
void stop ()
Private Slots
void removeNotesReleasedForTooLong ()
Private Member Functions
bool allCurStepNotesReleased ()
void applyStep ()
void dismissStep ()
StepNote * findCurStepNote (const int key)
TimePos getCurStepEndPos ()
void prepareNewStep ()
void stepBackwards ()
void stepForwards ()
void updateCurStepNotes ()
void updateWidget ()
Private Attributes
TimePos m_curStepEndPos = 0
TimePos m_curStepLength
std::vector< StepNote * > m_curStepNotes
TimePos m_curStepStartPos = 0
bool m_isRecording = false
bool m_isStepInProgress = false
MidiClip * m_midiClip
gui::PianoRoll & m_pianoRoll
gui::StepRecorderWidget & m_stepRecorderWidget
TimePos m_stepsLength
QTimer m_updateReleasedTimer
Detailed Description
Definition at line 44 of file StepRecorder.h.
Constructor & Destructor Documentation
StepRecorder()
lmms::StepRecorder::StepRecorder (gui::PianoRoll & pianoRoll, gui::StepRecorderWidget & stepRecorderWidget)
Definition at line 39 of file StepRecorder.cpp.
References m_midiClip, m_pianoRoll, and m_stepRecorderWidget.
Member Function Documentation
allCurStepNotesReleased()
bool lmms::StepRecorder::allCurStepNotesReleased () private
Definition at line 355 of file StepRecorder.cpp.
References allCurStepNotesReleased(), and m_curStepNotes.
Referenced by allCurStepNotesReleased(), and noteReleased().
applyStep()
void lmms::StepRecorder::applyStep () private
Definition at line 233 of file StepRecorder.cpp.
References lmms::Engine::getSong(), m_curStepNotes, m_midiClip, prepareNewStep(), and lmms::Song::setModified().
Referenced by noteReleased().
dismissStep()
void lmms::StepRecorder::dismissStep () private
Definition at line 250 of file StepRecorder.cpp.
References m_isStepInProgress, and prepareNewStep().
Referenced by noteReleased(), and setCurrentMidiClip().
findCurStepNote()
StepRecorder::StepNote * lmms::StepRecorder::findCurStepNote (const int key) private
Definition at line 368 of file StepRecorder.cpp.
References findCurStepNote(), and m_curStepNotes.
Referenced by findCurStepNote(), notePressed(), and noteReleased().
getCurStepEndPos()
TimePos lmms::StepRecorder::getCurStepEndPos () private
Definition at line 334 of file StepRecorder.cpp.
References getCurStepEndPos(), m_curStepLength, and m_curStepStartPos.
Referenced by getCurStepEndPos(), prepareNewStep(), and updateWidget().
getCurStepNotes()
std::vector< Note * > lmms::StepRecorder::getCurStepNotes ()
Definition at line 178 of file StepRecorder.cpp.
References m_curStepNotes, and m_isStepInProgress.
initialize()
void lmms::StepRecorder::initialize ()
Definition at line 47 of file StepRecorder.cpp.
References m_updateReleasedTimer, and removeNotesReleasedForTooLong().
isRecording()
bool lmms::StepRecorder::isRecording () const inline
Definition at line 63 of file StepRecorder.h.
References m_isRecording.
keyPressEvent()
bool lmms::StepRecorder::keyPressEvent (QKeyEvent * ke)
Definition at line 133 of file StepRecorder.cpp.
References stepBackwards(), and stepForwards().
mousePressEvent()
bool lmms::StepRecorder::mousePressEvent (QMouseEvent * ke)
notePressed()
void lmms::StepRecorder::notePressed (const Note & n)
Definition at line 80 of file StepRecorder.cpp.
References findCurStepNote(), lmms::Note::getPanning(), lmms::Note::getVolume(), lmms::StepRecorder::StepNote::isReleased(), lmms::Note::key(), m_curStepLength, m_curStepNotes, m_curStepStartPos, m_isStepInProgress, m_pianoRoll, lmms::StepRecorder::StepNote::setPressed(), and stepForwards().
noteReleased()
void lmms::StepRecorder::noteReleased (const Note & n)
Definition at line 103 of file StepRecorder.cpp.
References allCurStepNotesReleased(), applyStep(), dismissStep(), findCurStepNote(), lmms::StepRecorder::StepNote::isPressed(), lmms::Note::key(), m_curStepLength, m_updateReleasedTimer, lmms::REMOVE_RELEASED_NOTE_TIME_THRESHOLD_MS, and lmms::StepRecorder::StepNote::setReleased().
prepareNewStep()
void lmms::StepRecorder::prepareNewStep () private
Definition at line 260 of file StepRecorder.cpp.
References getCurStepEndPos(), m_curStepLength, m_curStepNotes, m_curStepStartPos, m_isStepInProgress, and updateWidget().
Referenced by applyStep(), dismissStep(), and start().
removeNotesReleasedForTooLong
void lmms::StepRecorder::removeNotesReleasedForTooLong () private slot
Definition at line 286 of file StepRecorder.cpp.
References m_curStepNotes, min, and lmms::REMOVE_RELEASED_NOTE_TIME_THRESHOLD_MS.
Referenced by initialize().
setCurrentMidiClip()
void lmms::StepRecorder::setCurrentMidiClip (MidiClip * newMidiClip)
Definition at line 276 of file StepRecorder.cpp.
References dismissStep(), and m_midiClip.
setStepsLength()
void lmms::StepRecorder::setStepsLength (const TimePos & newLength)
Definition at line 163 of file StepRecorder.cpp.
References m_curStepLength, m_isStepInProgress, m_stepsLength, updateCurStepNotes(), and updateWidget().
Referenced by start().
start()
void lmms::StepRecorder::start (const TimePos & currentPosition, const TimePos & stepLength)
Definition at line 52 of file StepRecorder.cpp.
References lmms::TimePos::getTicks(), m_curStepLength, m_curStepStartPos, m_isRecording, m_pianoRoll, m_stepRecorderWidget, prepareNewStep(), and setStepsLength().
stepBackwards()
void lmms::StepRecorder::stepBackwards () private
Definition at line 209 of file StepRecorder.cpp.
References m_curStepLength, m_curStepStartPos, m_isStepInProgress, m_stepsLength, max, updateCurStepNotes(), and updateWidget().
Referenced by keyPressEvent().
stepForwards()
void lmms::StepRecorder::stepForwards () private
Definition at line 193 of file StepRecorder.cpp.
References m_curStepLength, m_curStepStartPos, m_isStepInProgress, m_stepsLength, updateCurStepNotes(), and updateWidget().
Referenced by keyPressEvent(), and notePressed().
stop()
void lmms::StepRecorder::stop ()
Definition at line 74 of file StepRecorder.cpp.
References m_isRecording, and m_stepRecorderWidget.
updateCurStepNotes()
void lmms::StepRecorder::updateCurStepNotes () private
Definition at line 339 of file StepRecorder.cpp.
References m_curStepLength, m_curStepNotes, m_curStepStartPos, and updateCurStepNotes().
Referenced by setStepsLength(), stepBackwards(), stepForwards(), and updateCurStepNotes().
updateWidget()
void lmms::StepRecorder::updateWidget () private
Definition at line 348 of file StepRecorder.cpp.
References getCurStepEndPos(), m_curStepStartPos, m_stepRecorderWidget, m_stepsLength, and updateWidget().
Referenced by prepareNewStep(), setStepsLength(), stepBackwards(), stepForwards(), and updateWidget().
Member Data Documentation
m_curStepEndPos
TimePos lmms::StepRecorder::m_curStepEndPos = 0 private
Definition at line 91 of file StepRecorder.h.
m_curStepLength
TimePos lmms::StepRecorder::m_curStepLength private
Definition at line 94 of file StepRecorder.h.
Referenced by getCurStepEndPos(), notePressed(), noteReleased(), prepareNewStep(), setStepsLength(), start(), stepBackwards(), stepForwards(), and updateCurStepNotes().
m_curStepNotes
std::vector<StepNote*> lmms::StepRecorder::m_curStepNotes private
Definition at line 139 of file StepRecorder.h.
Referenced by allCurStepNotesReleased(), applyStep(), findCurStepNote(), getCurStepNotes(), notePressed(), prepareNewStep(), removeNotesReleasedForTooLong(), and updateCurStepNotes().
m_curStepStartPos
TimePos lmms::StepRecorder::m_curStepStartPos = 0 private
Definition at line 90 of file StepRecorder.h.
Referenced by getCurStepEndPos(), notePressed(), prepareNewStep(), start(), stepBackwards(), stepForwards(), updateCurStepNotes(), and updateWidget().
m_isRecording
bool lmms::StepRecorder::m_isRecording = false private
Definition at line 89 of file StepRecorder.h.
Referenced by isRecording(), start(), and stop().
m_isStepInProgress
bool lmms::StepRecorder::m_isStepInProgress = false private
Definition at line 143 of file StepRecorder.h.
Referenced by dismissStep(), getCurStepNotes(), notePressed(), prepareNewStep(), setStepsLength(), stepBackwards(), and stepForwards().
m_midiClip
MidiClip* lmms::StepRecorder::m_midiClip private
Definition at line 99 of file StepRecorder.h.
Referenced by StepRecorder(), applyStep(), and setCurrentMidiClip().
m_pianoRoll
gui::PianoRoll& lmms::StepRecorder::m_pianoRoll private
Definition at line 86 of file StepRecorder.h.
Referenced by StepRecorder(), notePressed(), and start().
m_stepRecorderWidget
gui::StepRecorderWidget& lmms::StepRecorder::m_stepRecorderWidget private
Definition at line 87 of file StepRecorder.h.
Referenced by StepRecorder(), start(), stop(), and updateWidget().
m_stepsLength
TimePos lmms::StepRecorder::m_stepsLength private
Definition at line 93 of file StepRecorder.h.
Referenced by setStepsLength(), stepBackwards(), stepForwards(), and updateWidget().
m_updateReleasedTimer
QTimer lmms::StepRecorder::m_updateReleasedTimer private
Definition at line 97 of file StepRecorder.h.
Referenced by initialize(), and noteReleased().
The documentation for this class was generated from the following files:
include/StepRecorder.h
src/core/StepRecorder.cpp