LMMS: lmms::gui::SimpleTextFloat Class Reference
lmms::gui::SimpleTextFloat Class Reference
#include <SimpleTextFloat.h>
Public Member Functions
SimpleTextFloat ()
~SimpleTextFloat () override=default
void hide ()
void moveGlobal (QWidget *w, const QPoint &offset)
void setText (const QString &text)
void showWithDelay (int msecBeforeDisplay, int msecDisplayTime)
void showWithTimeout (int msec)
Private Attributes
QTimer * m_hideTimer
QTimer * m_showTimer
QLabel * m_textLabel
Detailed Description
Definition at line 39 of file SimpleTextFloat.h.
Constructor & Destructor Documentation
SimpleTextFloat()
lmms::gui::SimpleTextFloat::SimpleTextFloat ()
Definition at line 38 of file SimpleTextFloat.cpp.
References lmms::gui::getGUI(), hide(), m_hideTimer, m_showTimer, and m_textLabel.
~SimpleTextFloat()
lmms::gui::SimpleTextFloat::~SimpleTextFloat () override default
References setText(), and showWithDelay().
Member Function Documentation
hide()
void lmms::gui::SimpleTextFloat::hide ()
Definition at line 79 of file SimpleTextFloat.cpp.
References m_hideTimer, and m_showTimer.
Referenced by SimpleTextFloat().
moveGlobal()
void lmms::gui::SimpleTextFloat::moveGlobal (QWidget * w, const QPoint & offset) inline
Definition at line 55 of file SimpleTextFloat.h.
setText()
void lmms::gui::SimpleTextFloat::setText (const QString & text)
Definition at line 57 of file SimpleTextFloat.cpp.
References m_textLabel.
Referenced by ~SimpleTextFloat().
showWithDelay()
void lmms::gui::SimpleTextFloat::showWithDelay (int msecBeforeDisplay, int msecDisplayTime)
Definition at line 62 of file SimpleTextFloat.cpp.
References m_hideTimer, and m_showTimer.
Referenced by ~SimpleTextFloat(), and showWithTimeout().
showWithTimeout()
void lmms::gui::SimpleTextFloat::showWithTimeout (int msec) inline
Definition at line 50 of file SimpleTextFloat.h.
References showWithDelay().
Member Data Documentation
m_hideTimer
QTimer* lmms::gui::SimpleTextFloat::m_hideTimer private
Definition at line 65 of file SimpleTextFloat.h.
Referenced by SimpleTextFloat(), hide(), and showWithDelay().
m_showTimer
QTimer* lmms::gui::SimpleTextFloat::m_showTimer private
Definition at line 64 of file SimpleTextFloat.h.
Referenced by SimpleTextFloat(), hide(), and showWithDelay().
m_textLabel
QLabel* lmms::gui::SimpleTextFloat::m_textLabel private
Definition at line 63 of file SimpleTextFloat.h.
Referenced by SimpleTextFloat(), and setText().
The documentation for this class was generated from the following files:
include/SimpleTextFloat.h
src/gui/widgets/SimpleTextFloat.cpp