LMMS: lmms::NullableResource< T, Null > Class Template Reference
lmms::NullableResource< T, Null > Class Template Reference
#include <RaiiHelpers.h>
Public Member Functions
NullableResource ()=default
NullableResource (std::nullptr_t) noexcept
NullableResource (T value) noexcept
operator bool () const noexcept
operator T () const noexcept
Private Attributes
T m_value = Null
Friends
bool operator!= (NullableResource a, NullableResource b) noexcept
bool operator!= (NullableResource a, T b) noexcept
bool operator!= (T a, NullableResource b) noexcept
bool operator== (NullableResource a, NullableResource b) noexcept
bool operator== (NullableResource a, T b) noexcept
bool operator== (T a, NullableResource b) noexcept
Detailed Description
template<typename T, T Null>
class lmms::NullableResource< T, Null >
Definition at line 36 of file RaiiHelpers.h.
Constructor & Destructor Documentation
NullableResource() [1/3]
template<typename T, T Null> lmms::NullableResource< T, Null >::NullableResource () default
Referenced by operator!=, operator!=, operator!=, operator==, operator==, and operator==.
NullableResource() [2/3]
template<typename T, T Null> lmms::NullableResource< T, Null >::NullableResource (std::nullptr_t) inline noexcept
Definition at line 40 of file RaiiHelpers.h.
NullableResource() [3/3]
template<typename T, T Null> lmms::NullableResource< T, Null >::NullableResource (T value) inline noexcept
Definition at line 41 of file RaiiHelpers.h.
References m_value.
Member Function Documentation
operator bool()
template<typename T, T Null> lmms::NullableResource< T, Null >::operator bool () const inline explicit noexcept
Definition at line 43 of file RaiiHelpers.h.
References m_value.
operator T()
template<typename T, T Null> lmms::NullableResource< T, Null >::operator T () const inline noexcept
Definition at line 42 of file RaiiHelpers.h.
References m_value.
Friends And Related Symbol Documentation
operator!= [1/3]
template<typename T, T Null> bool operator!= (NullableResource< T, Null > a, NullableResource< T, Null > b) friend
Definition at line 47 of file RaiiHelpers.h.
References NullableResource().
operator!= [2/3]
template<typename T, T Null> bool operator!= (NullableResource< T, Null > a, T b) friend
Definition at line 48 of file RaiiHelpers.h.
References NullableResource().
operator!= [3/3]
template<typename T, T Null> bool operator!= (T a, NullableResource< T, Null > b) friend
Definition at line 49 of file RaiiHelpers.h.
References NullableResource().
operator== [1/3]
template<typename T, T Null> bool operator== (NullableResource< T, Null > a, NullableResource< T, Null > b) friend
Definition at line 44 of file RaiiHelpers.h.
References NullableResource().
operator== [2/3]
template<typename T, T Null> bool operator== (NullableResource< T, Null > a, T b) friend
Definition at line 45 of file RaiiHelpers.h.
References NullableResource().
operator== [3/3]
template<typename T, T Null> bool operator== (T a, NullableResource< T, Null > b) friend
Definition at line 46 of file RaiiHelpers.h.
References NullableResource().
Member Data Documentation
m_value
template<typename T, T Null> T lmms::NullableResource< T, Null >::m_value = Null private
Definition at line 52 of file RaiiHelpers.h.
Referenced by NullableResource(), operator bool(), and operator T().
The documentation for this class was generated from the following file:
include/RaiiHelpers.h