LMMS: Jack::JackPortAudioDriver Class Reference
Jack::JackPortAudioDriver Class Reference
The PortAudio driver.
#include <JackPortAudioDriver.h>
Public Member Functions
JackPortAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table, PortAudioDevices *pa_devices)
virtual ~JackPortAudioDriver ()
int Attach ()
int Close ()
bool IsFixedBufferSize ()
int Open (jack_nframes_t buffe_size, jack_nframes_t samplerate, bool capturing, bool playing, int chan_in, int chan_out, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
int Read ()
int SetBufferSize (jack_nframes_t buffer_size)
int Start ()
int Stop ()
int Write ()
Public Member Functions inherited from Jack::JackAudioDriver
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Detach ()
virtual int Process ()
virtual int SetSampleRate (jack_nframes_t sample_rate)
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Member Functions
PaError OpenStream (jack_nframes_t buffer_size)
int Render (const void *inputBuffer, void *outputBuffer, PaStreamCallbackFlags statusFlags)
void UpdateLatencies ()
Static Private Member Functions
static int Render (const void *inputBuffer, void *outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
Private Attributes
jack_default_audio_sample_t ** fInputBuffer
PaDeviceIndex fInputDevice
jack_default_audio_sample_t ** fOutputBuffer
PaDeviceIndex fOutputDevice
PortAudioDevices * fPaDevices
jack_native_thread_t fReservationLoopThread
PaStream * fStream
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAudioDriver
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The PortAudio driver.
Definition at line 37 of file JackPortAudioDriver.h.
Constructor & Destructor Documentation
JackPortAudioDriver()
Jack::JackPortAudioDriver::JackPortAudioDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table, PortAudioDevices * pa_devices) inline
Definition at line 66 of file JackPortAudioDriver.h.
References Jack::JackAudioDriver::JackAudioDriver(), fInputBuffer, fInputDevice, fOutputBuffer, fOutputDevice, fPaDevices, and fStream.
Referenced by Render().
~JackPortAudioDriver()
virtual Jack::JackPortAudioDriver::~JackPortAudioDriver () inline virtual
Definition at line 74 of file JackPortAudioDriver.h.
References fPaDevices.
Member Function Documentation
Attach()
int Jack::JackPortAudioDriver::Attach () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 352 of file JackPortAudioDriver.cpp.
References Jack::JackAudioDriver::Attach(), Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fGraphManager, fInputDevice, fOutputDevice, fPaDevices, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackPortList, i, and Jack::JackPort::SetAlias().
Close()
int Jack::JackPortAudioDriver::Close () virtual
Reimplemented from Jack::JackDriver.
Definition at line 316 of file JackPortAudioDriver.cpp.
References Jack::JackClientInterface::Close(), Jack::device_reservation_loop_running, Jack::JackDriver::fCaptureDriverName, fPaDevices, Jack::JackDriver::fPlaybackDriverName, fReservationLoopThread, fStream, jack_error, jack_log(), Jack::JackServerGlobals::on_device_release, and Jack::JackPosixThread::StopImp().
IsFixedBufferSize()
bool Jack::JackPortAudioDriver::IsFixedBufferSize () inline virtual
Reimplemented from Jack::JackDriver.
Definition at line 102 of file JackPortAudioDriver.h.
Open()
int Jack::JackPortAudioDriver::Open (jack_nframes_t buffe_size, jack_nframes_t samplerate, bool capturing, bool playing, int chan_in, int chan_out, bool monitor, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency) virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 186 of file JackPortAudioDriver.cpp.
References capture_latency, Jack::JackClientInterface::Close(), Jack::JackTools::ComputationMicroSec(), Jack::device_reservation_loop_running, Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCaptureLatency, Jack::JackDriver::fEngineControl, fInputDevice, fOutputDevice, fPaDevices, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackLatency, fReservationLoopThread, JACK_CLIENT_NAME_SIZE, jack_error, jack_log(), Jack::JackServerGlobals::on_device_acquire, Jack::JackServerGlobals::on_device_reservation_loop, Jack::on_device_reservation_loop(), Jack::JackAudioDriver::Open(), OpenStream(), playback_latency, and Jack::JackPosixThread::StartImp().
OpenStream()
PaError Jack::JackPortAudioDriver::OpenStream (jack_nframes_t buffer_size) private
Definition at line 123 of file JackPortAudioDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fEngineControl, fInputDevice, fOutputDevice, fPaDevices, Jack::JackDriver::fPlaybackChannels, fStream, jack_log(), and Render().
Referenced by Open(), and SetBufferSize().
Read()
int Jack::JackPortAudioDriver::Read () virtual
Reimplemented from Jack::JackDriver.
Definition at line 107 of file JackPortAudioDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fEngineControl, fInputBuffer, Jack::JackAudioDriver::GetInputBuffer(), and i.
Render() [1/2]
int Jack::JackPortAudioDriver::Render (const void * inputBuffer, void * outputBuffer, PaStreamCallbackFlags statusFlags) private
Definition at line 78 of file JackPortAudioDriver.cpp.
References Jack::JackDriver::CycleTakeBeginTime(), Jack::JackDriver::fBeginDateUst, fInputBuffer, fOutputBuffer, GetMicroSeconds(), jack_error, Jack::JackDriver::NotifyXRun(), Jack::JackAudioDriver::Process(), and set_threaded_log_function().
Render() [2/2]
int Jack::JackPortAudioDriver::Render (const void * inputBuffer, void * outputBuffer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData) static private
Definition at line 69 of file JackPortAudioDriver.cpp.
References JackPortAudioDriver(), and Render().
Referenced by OpenStream(), and Render().
SetBufferSize()
int Jack::JackPortAudioDriver::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 412 of file JackPortAudioDriver.cpp.
References fStream, jack_error, OpenStream(), and Jack::JackAudioDriver::SetBufferSize().
Start()
int Jack::JackPortAudioDriver::Start () virtual
Reimplemented from Jack::JackDriver.
Definition at line 384 of file JackPortAudioDriver.cpp.
References fStream, jack_error, jack_log(), Jack::JackDriverInterface::Start(), and Jack::JackDriverInterface::Stop().
Stop()
int Jack::JackPortAudioDriver::Stop () virtual
Reimplemented from Jack::JackDriver.
Definition at line 398 of file JackPortAudioDriver.cpp.
References fStream, jack_error, jack_log(), and Jack::JackDriverInterface::Stop().
UpdateLatencies()
void Jack::JackPortAudioDriver::UpdateLatencies (void) private virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 157 of file JackPortAudioDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCaptureLatency, Jack::JackDriver::fCapturePortList, Jack::JackDriver::fEngineControl, Jack::JackDriver::fGraphManager, Jack::JackDriver::fMonitorPortList, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackLatency, Jack::JackDriver::fPlaybackPortList, fStream, Jack::JackDriver::fWithMonitorPorts, i, JackCaptureLatency, JackPlaybackLatency, _jack_latency_range::max, and _jack_latency_range::min.
Write()
int Jack::JackPortAudioDriver::Write () virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 115 of file JackPortAudioDriver.cpp.
References Jack::JackDriver::fEngineControl, fOutputBuffer, Jack::JackDriver::fPlaybackChannels, Jack::JackAudioDriver::GetOutputBuffer(), and i.
Member Data Documentation
fInputBuffer
jack_default_audio_sample_t** Jack::JackPortAudioDriver::fInputBuffer private
Definition at line 47 of file JackPortAudioDriver.h.
Referenced by JackPortAudioDriver(), Read(), and Render().
fInputDevice
PaDeviceIndex Jack::JackPortAudioDriver::fInputDevice private
Definition at line 49 of file JackPortAudioDriver.h.
Referenced by JackPortAudioDriver(), Attach(), Open(), and OpenStream().
fOutputBuffer
jack_default_audio_sample_t** Jack::JackPortAudioDriver::fOutputBuffer private
Definition at line 48 of file JackPortAudioDriver.h.
Referenced by JackPortAudioDriver(), Render(), and Write().
fOutputDevice
PaDeviceIndex Jack::JackPortAudioDriver::fOutputDevice private
Definition at line 50 of file JackPortAudioDriver.h.
Referenced by JackPortAudioDriver(), Attach(), Open(), and OpenStream().
fPaDevices
PortAudioDevices* Jack::JackPortAudioDriver::fPaDevices private
Definition at line 51 of file JackPortAudioDriver.h.
Referenced by JackPortAudioDriver(), ~JackPortAudioDriver(), Attach(), Close(), Open(), and OpenStream().
fReservationLoopThread
jack_native_thread_t Jack::JackPortAudioDriver::fReservationLoopThread private
Definition at line 52 of file JackPortAudioDriver.h.
Referenced by Close(), and Open().
fStream
PaStream* Jack::JackPortAudioDriver::fStream private
Definition at line 46 of file JackPortAudioDriver.h.
Referenced by JackPortAudioDriver(), Close(), OpenStream(), SetBufferSize(), Start(), Stop(), and UpdateLatencies().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/portaudio/JackPortAudioDriver.h
src/3rdparty/jack2/windows/portaudio/JackPortAudioDriver.cpp