LMMS: lmms::PerfLogTimer Class Reference
lmms::PerfLogTimer Class Reference
The PerfLog class.
#include <PerfLog.h>
Public Member Functions
PerfLogTimer (const QString &name)
~PerfLogTimer ()
void begin ()
void end ()
Private Attributes
PerfTime begin_time
QString name
Detailed Description
The PerfLog class.
Measures time between construction and destruction and prints the result to stderr, along with name. Alternatively, call begin() and end() explicitly.
Definition at line 63 of file PerfLog.h.
Constructor & Destructor Documentation
PerfLogTimer()
lmms::PerfLogTimer::PerfLogTimer (const QString & name)
Definition at line 103 of file PerfLog.cpp.
References begin(), and name.
~PerfLogTimer()
lmms::PerfLogTimer::~PerfLogTimer ()
Definition at line 109 of file PerfLog.cpp.
References end().
Member Function Documentation
begin()
void lmms::PerfLogTimer::begin ()
Definition at line 114 of file PerfLog.cpp.
References begin_time, and lmms::PerfTime::now().
Referenced by PerfLogTimer().
end()
void lmms::PerfLogTimer::end ()
Definition at line 119 of file PerfLog.cpp.
References begin_time, name, lmms::PerfTime::now(), lmms::PerfTime::real(), lmms::PerfTime::system(), lmms::PerfTime::ticksPerSecond(), and lmms::PerfTime::user().
Referenced by ~PerfLogTimer(), and lmms::ProjectRenderer::run().
Member Data Documentation
begin_time
PerfTime lmms::PerfLogTimer::begin_time private
Definition at line 74 of file PerfLog.h.
Referenced by begin(), and end().
name
QString lmms::PerfLogTimer::name private
Definition at line 73 of file PerfLog.h.
Referenced by PerfLogTimer(), and end().
The documentation for this class was generated from the following files:
include/PerfLog.h
src/core/PerfLog.cpp