LMMS: lmms::gui::Graph Class Reference
lmms::gui::Graph Class Reference
#include <Graph.h>
Public Types
enum class Style {
Nearest ,
Linear ,
LinearNonCyclic ,
Bar
}
Signals
void drawn ()
Public Member Functions
Graph (QWidget *_parent, Style _style=Style::Linear, int _width=132, int _height=104)
Constructor.
~Graph () override=default
Style getGraphStyle ()
graphModel * model ()
void setForeground (const QPixmap &_pixmap)
void setGraphColor (const QColor)
void setGraphStyle (Style _s)
Public Member Functions inherited from lmms::gui::ModelView
ModelView (Model *model, QWidget *widget)
virtual ~ModelView ()
template<class T>
T * castModel ()
template<class T>
const T * castModel () const
Model * model ()
const Model * model () const
virtual void setModel (Model *model, bool isOldModelValid=true)
virtual void unsetModel ()
Protected Slots
void updateGraph ()
void updateGraph (int _startPos, int _endPos)
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *_dee) override
void dropEvent (QDropEvent *_de) override
void mouseMoveEvent (QMouseEvent *_me) override
void mousePressEvent (QMouseEvent *_me) override
void mouseReleaseEvent (QMouseEvent *_me) override
void paintEvent (QPaintEvent *_pe) override
Protected Member Functions inherited from lmms::gui::ModelView
virtual void doConnections ()
QWidget * widget ()
Private Member Functions
void changeSampleAt (int _x, int _y)
void drawLineAt (int _x, int _y, int _lastx)
void modelChanged () override
Private Attributes
QPixmap m_foreground
QColor m_graphColor
Style m_graphStyle
int m_lastCursorX
bool m_mouseDown
Detailed Description
Definition at line 47 of file Graph.h.
Member Enumeration Documentation
Style
enum class lmms::gui::Graph::Style strong
Enumerator
Nearest
draw as stairs
Linear
connect each 2 samples with a line, with wrapping
LinearNonCyclic
Linear without wrapping.
Bar
draw thick bars
Definition at line 51 of file Graph.h.
Constructor & Destructor Documentation
Graph()
lmms::gui::Graph::Graph (QWidget * _parent, Style _style = Style::Linear, int _width = 132, int _height = 104)
Constructor.
Parameters
_width Pixel width of widget
_height Pixel height of widget
Definition at line 39 of file Graph.cpp.
References lmms::gui::ModelView::ModelView(), lmms::gui::ModelView::castModel(), m_graphColor, m_graphStyle, m_mouseDown, and updateGraph().
~Graph()
lmms::gui::Graph::~Graph () override default
References setForeground(), and setGraphColor().
Member Function Documentation
changeSampleAt()
void lmms::gui::Graph::changeSampleAt (int _x, int _y) private
Definition at line 246 of file Graph.cpp.
References lmms::graphModel::length(), lmms::graphModel::maxValue(), lmms::graphModel::minValue(), model(), and lmms::graphModel::setSampleAt().
Referenced by drawn(), and mousePressEvent().
dragEnterEvent()
void lmms::gui::Graph::dragEnterEvent (QDragEnterEvent * _dee) override protected
Definition at line 423 of file Graph.cpp.
References lmms::gui::StringPairDrag::processDragEnterEvent().
Referenced by drawn().
drawLineAt()
void lmms::gui::Graph::drawLineAt (int _x, int _y, int _lastx) private
Definition at line 181 of file Graph.cpp.
References lmms::graphModel::drawSampleAt(), i, lmms::graphModel::length(), lmms::graphModel::maxValue(), lmms::graphModel::minValue(), model(), and lmms::graphModel::samplesChanged().
Referenced by drawn(), mouseMoveEvent(), and mousePressEvent().
drawn
void lmms::gui::Graph::drawn () signal
References changeSampleAt(), dragEnterEvent(), drawLineAt(), dropEvent(), modelChanged(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), and updateGraph().
Referenced by mouseReleaseEvent().
dropEvent()
void lmms::gui::Graph::dropEvent (QDropEvent * _de) override protected
Definition at line 410 of file Graph.cpp.
References lmms::gui::StringPairDrag::decodeKey(), and lmms::gui::StringPairDrag::decodeValue().
Referenced by drawn().
getGraphStyle()
Style lmms::gui::Graph::getGraphStyle () inline
Definition at line 80 of file Graph.h.
References m_graphStyle.
model()
graphModel * lmms::gui::Graph::model () inline
Definition at line 75 of file Graph.h.
References lmms::gui::ModelView::castModel().
Referenced by changeSampleAt(), drawLineAt(), paintEvent(), and updateGraph().
modelChanged()
void lmms::gui::Graph::modelChanged () override private virtual
Reimplemented from lmms::gui::ModelView.
Definition at line 434 of file Graph.cpp.
References lmms::gui::ModelView::castModel(), and updateGraph().
Referenced by drawn().
mouseMoveEvent()
void lmms::gui::Graph::mouseMoveEvent (QMouseEvent * _me) override protected
Definition at line 100 of file Graph.cpp.
References drawLineAt(), and m_lastCursorX.
Referenced by drawn().
mousePressEvent()
void lmms::gui::Graph::mousePressEvent (QMouseEvent * _me) override protected
Definition at line 147 of file Graph.cpp.
References changeSampleAt(), drawLineAt(), m_lastCursorX, and m_mouseDown.
Referenced by drawn().
mouseReleaseEvent()
void lmms::gui::Graph::mouseReleaseEvent (QMouseEvent * _me) override protected
Definition at line 273 of file Graph.cpp.
References drawn(), and m_mouseDown.
Referenced by drawn().
paintEvent()
void lmms::gui::Graph::paintEvent (QPaintEvent * _pe) override protected
Definition at line 287 of file Graph.cpp.
References Bar, i, lmms::graphModel::length(), Linear, LinearNonCyclic, m_foreground, m_graphColor, m_graphStyle, m_mouseDown, lmms::graphModel::m_samples, lmms::graphModel::maxValue(), lmms::graphModel::minValue(), model(), and Nearest.
Referenced by drawn().
setForeground()
void lmms::gui::Graph::setForeground (const QPixmap & _pixmap)
Definition at line 62 of file Graph.cpp.
References m_foreground.
Referenced by ~Graph().
setGraphColor()
void lmms::gui::Graph::setGraphColor (const QColor _graphcol)
Definition at line 67 of file Graph.cpp.
References m_graphColor.
Referenced by ~Graph().
setGraphStyle()
void lmms::gui::Graph::setGraphStyle (Style _s) inline
Definition at line 86 of file Graph.h.
References m_graphStyle.
updateGraph [1/2]
void lmms::gui::Graph::updateGraph () protected slot
Definition at line 453 of file Graph.cpp.
References model(), and updateGraph().
Referenced by Graph(), modelChanged(), and updateGraph().
updateGraph [2/2]
void lmms::gui::Graph::updateGraph (int _startPos, int _endPos) protected slot
Definition at line 446 of file Graph.cpp.
Referenced by drawn().
Member Data Documentation
m_foreground
QPixmap lmms::gui::Graph::m_foreground private
Definition at line 113 of file Graph.h.
Referenced by paintEvent(), and setForeground().
m_graphColor
QColor lmms::gui::Graph::m_graphColor private
Definition at line 114 of file Graph.h.
Referenced by Graph(), paintEvent(), and setGraphColor().
m_graphStyle
Style lmms::gui::Graph::m_graphStyle private
Definition at line 116 of file Graph.h.
Referenced by Graph(), getGraphStyle(), paintEvent(), and setGraphStyle().
m_lastCursorX
int lmms::gui::Graph::m_lastCursorX private
Definition at line 119 of file Graph.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_mouseDown
bool lmms::gui::Graph::m_mouseDown private
Definition at line 118 of file Graph.h.
Referenced by Graph(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
The documentation for this class was generated from the following files:
include/Graph.h
src/gui/widgets/Graph.cpp