LMMS: Jack::JackFixedArray1< SIZE > Class Template Reference
Jack::JackFixedArray1< SIZE > Class Template Reference
Utility class.
#include <JackConnectionManager.h>
Public Member Functions
JackFixedArray1 ()
void Init ()
bool IsAvailable ()
Public Member Functions inherited from Jack::JackFixedArray< SIZE >
JackFixedArray ()
bool AddItem (jack_int_t index)
bool CheckItem (jack_int_t index) const
jack_int_t GetItem (jack_int_t index) const
uint32_t GetItemCount () const
const jack_int_t * GetItems () const
void Init ()
bool RemoveItem (jack_int_t index)
Private Attributes
bool fUsed
Detailed Description
template<int SIZE>
class Jack::JackFixedArray1< SIZE >
Utility class.
Definition at line 128 of file JackConnectionManager.h.
Constructor & Destructor Documentation
JackFixedArray1()
template<int SIZE> Jack::JackFixedArray1< SIZE >::JackFixedArray1 () inline
Definition at line 136 of file JackConnectionManager.h.
References Init().
Member Function Documentation
Init()
template<int SIZE> void Jack::JackFixedArray1< SIZE >::Init () inline
Definition at line 141 of file JackConnectionManager.h.
References fUsed, and Jack::JackFixedArray< SIZE >::Init().
Referenced by JackFixedArray1().
IsAvailable()
template<int SIZE> bool Jack::JackFixedArray1< SIZE >::IsAvailable () inline
Definition at line 147 of file JackConnectionManager.h.
References fUsed.
Member Data Documentation
fUsed
template<int SIZE> bool Jack::JackFixedArray1< SIZE >::fUsed private
Definition at line 132 of file JackConnectionManager.h.
Referenced by Init(), and IsAvailable().
The documentation for this class was generated from the following file:
src/3rdparty/jack2/common/JackConnectionManager.h