LMMS: lmms::ProjectRenderer Class Reference
lmms::ProjectRenderer Class Reference
#include <ProjectRenderer.h>
Classes
struct FileEncodeDevice
Public Types
enum class ExportFileFormat : int {
Wave ,
Flac ,
Ogg ,
MP3 ,
Count
}
Public Slots
void abortProcessing ()
void startProcessing ()
void updateConsoleProgress ()
Signals
void progressChanged (int)
Public Member Functions
ProjectRenderer (const OutputSettings &_os, ExportFileFormat _file_format, const QString &_out_file)
~ProjectRenderer () override=default
bool isReady () const
Static Public Member Functions
static QString getFileExtensionFromFormat (ExportFileFormat fmt)
static ExportFileFormat getFileFormatFromExtension (const QString &_ext)
Static Public Attributes
static const std::array< FileEncodeDevice, 5 > fileEncodeDevices
static constexpr auto NumFileFormats = static_cast<std::size_t>(ExportFileFormat::Count)
Private Member Functions
void run () override
Private Attributes
volatile bool m_abort
AudioFileDevice * m_fileDev
volatile int m_progress
Detailed Description
Definition at line 38 of file ProjectRenderer.h.
Member Enumeration Documentation
ExportFileFormat
enum class lmms::ProjectRenderer::ExportFileFormat : int strong
Enumerator
Wave
Flac
Ogg
MP3
Count
Definition at line 42 of file ProjectRenderer.h.
Constructor & Destructor Documentation
ProjectRenderer()
lmms::ProjectRenderer::ProjectRenderer (const OutputSettings & _os, ExportFileFormat _file_format, const QString & _out_file)
Definition at line 78 of file ProjectRenderer.cpp.
References lmms::Engine::audioEngine(), lmms::DEFAULT_CHANNELS, fileEncodeDevices, m_abort, m_fileDev, and m_progress.
~ProjectRenderer()
lmms::ProjectRenderer::~ProjectRenderer () override default
Member Function Documentation
abortProcessing
void lmms::ProjectRenderer::abortProcessing () slot
Definition at line 197 of file ProjectRenderer.cpp.
References m_abort.
getFileExtensionFromFormat()
QString lmms::ProjectRenderer::getFileExtensionFromFormat (ExportFileFormat fmt) static
Definition at line 126 of file ProjectRenderer.cpp.
References fileEncodeDevices.
Referenced by main(), and lmms::RenderManager::pathForTrack().
getFileFormatFromExtension()
ProjectRenderer::ExportFileFormat lmms::ProjectRenderer::getFileFormatFromExtension (const QString & _ext) static
Definition at line 107 of file ProjectRenderer.cpp.
References Count, fileEncodeDevices, and Wave.
isReady()
bool lmms::ProjectRenderer::isReady () const inline
Definition at line 65 of file ProjectRenderer.h.
References m_fileDev.
Referenced by startProcessing().
progressChanged
void lmms::ProjectRenderer::progressChanged (int) signal
References run().
Referenced by run().
run()
void lmms::ProjectRenderer::run () override private
Definition at line 154 of file ProjectRenderer.cpp.
References lmms::Engine::audioEngine(), lmms::PerfLogTimer::end(), lmms::Song::getExportProgress(), lmms::Engine::getSong(), m_abort, m_fileDev, m_progress, lmms::AudioEngine::nextBuffer(), progressChanged(), lmms::Song::startExport(), lmms::AudioEngine::startProcessing(), lmms::Song::stopExport(), and lmms::AudioEngine::stopProcessing().
Referenced by progressChanged().
startProcessing
void lmms::ProjectRenderer::startProcessing () slot
Definition at line 135 of file ProjectRenderer.cpp.
References lmms::Engine::audioEngine(), isReady(), m_fileDev, and lmms::AudioEngine::setAudioDevice().
updateConsoleProgress
void lmms::ProjectRenderer::updateConsoleProgress () slot
Definition at line 205 of file ProjectRenderer.cpp.
References i, and m_progress.
Member Data Documentation
fileEncodeDevices
const std::array< ProjectRenderer::FileEncodeDevice, 5 > lmms::ProjectRenderer::fileEncodeDevices static
Definition at line 75 of file ProjectRenderer.h.
Referenced by lmms::gui::ExportProjectDialog::ExportProjectDialog(), ProjectRenderer(), lmms::gui::MainWindow::exportProject(), getFileExtensionFromFormat(), getFileFormatFromExtension(), and lmms::gui::ExportProjectDialog::startBtnClicked().
m_abort
volatile bool lmms::ProjectRenderer::m_abort private
Definition at line 94 of file ProjectRenderer.h.
Referenced by ProjectRenderer(), abortProcessing(), and run().
m_fileDev
AudioFileDevice* lmms::ProjectRenderer::m_fileDev private
Definition at line 91 of file ProjectRenderer.h.
Referenced by ProjectRenderer(), isReady(), run(), and startProcessing().
m_progress
volatile int lmms::ProjectRenderer::m_progress private
Definition at line 93 of file ProjectRenderer.h.
Referenced by ProjectRenderer(), run(), and updateConsoleProgress().
NumFileFormats
auto lmms::ProjectRenderer::NumFileFormats = static_cast<std::size_t>(ExportFileFormat::Count) static constexpr
Definition at line 50 of file ProjectRenderer.h.
Referenced by lmms::gui::ExportProjectDialog::ExportProjectDialog(), and lmms::gui::ExportProjectDialog::startBtnClicked().
The documentation for this class was generated from the following files:
include/ProjectRenderer.h
src/core/ProjectRenderer.cpp