LMMS: lmms::Note Class Reference
lmms::Note Class Reference
#include <Note.h>
Public Types
enum class Type {
Regular = 0 ,
Step
}
Public Member Functions
Note (const Note &note)
Note (const TimePos &length=TimePos(0), const TimePos &pos=TimePos(0), int key=DefaultKey, volume_t volume=DefaultVolume, panning_t panning=DefaultPanning, std::shared_ptr< DetuningHelper > detuning=nullptr)
~Note () override
Note * clone () const
Performs a deep copy and returns an owning raw pointer.
void createDetuning ()
const std::shared_ptr< DetuningHelper > & detuning () const
TimePos endPos () const
panning_t getPanning () const
volume_t getVolume () const
bool hasDetuningInfo () const
bool isPlaying () const
int key () const
const TimePos & length () const
int midiVelocity (int midiBaseVelocity) const
QString nodeName () const override
int oldKey () const
TimePos oldLength () const
TimePos oldPos () const
Note & operator= (const Note &note)
const TimePos & pos () const
TimePos pos (TimePos basePos) const
void quantizeLength (const int qGrid)
void quantizePos (const int qGrid)
bool selected () const
void setIsPlaying (const bool isPlaying)
void setKey (const int key)
void setLength (const TimePos &length)
void setOldKey (const int oldKey)
void setOldLength (const TimePos &oldLength)
void setOldPos (const TimePos &oldPos)
virtual void setPanning (panning_t panning)
void setPos (const TimePos &pos)
void setSelected (const bool selected)
void setType (Type t)
virtual void setVolume (volume_t volume)
Type type () const
bool withinRange (int tickStart, int tickEnd) const
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual void restoreState (const QDomElement &_this)
virtual QDomElement saveState (QDomDocument &_doc, QDomElement &_parent)
void setHook (SerializingObjectHook *_hook)
Static Public Member Functions
static QString classNodeName ()
static bool lessThan (const Note *lhs, const Note *rhs)
static TimePos quantized (const TimePos &m, const int qGrid)
Protected Member Functions
void loadSettings (const QDomElement &_this) override
void saveSettings (QDomDocument &doc, QDomElement &parent) override
Private Attributes
std::shared_ptr< DetuningHelper > m_detuning
bool m_isPlaying
int m_key
TimePos m_length
int m_oldKey
TimePos m_oldLength
TimePos m_oldPos
panning_t m_panning
TimePos m_pos
bool m_selected
Type m_type = Type::Regular
volume_t m_volume
Detailed Description
Definition at line 99 of file Note.h.
Member Enumeration Documentation
Type
enum class lmms::Note::Type strong
Enumerator
Regular
Step
Definition at line 117 of file Note.h.
Constructor & Destructor Documentation
Note() [1/2]
lmms::Note::Note (const TimePos & length = TimePos(0), const TimePos & pos = TimePos(0), int key = DefaultKey, volume_t volume = DefaultVolume, panning_t panning = DefaultPanning, std::shared_ptr< DetuningHelper > detuning = nullptr)
Definition at line 37 of file Note.cpp.
References createDetuning(), detuning(), key(), length(), m_detuning, m_isPlaying, m_key, m_length, m_oldKey, m_oldLength, m_oldPos, m_panning, m_pos, m_selected, m_volume, lmms::MaxVolume, lmms::MinVolume, lmms::NumKeys, lmms::PanningLeft, lmms::PanningRight, and pos().
Referenced by Note(), lmms::NotePlayHandle::NotePlayHandle(), clone(), lessThan(), and operator=().
Note() [2/2]
lmms::Note::Note (const Note & note)
Definition at line 61 of file Note.cpp.
References Note(), lmms::SerializingObject::SerializingObject(), m_detuning, m_isPlaying, m_key, m_length, m_oldKey, m_oldLength, m_oldPos, m_panning, m_pos, m_selected, m_type, and m_volume.
~Note()
lmms::Note::~Note () override
Definition at line 106 of file Note.cpp.
Member Function Documentation
classNodeName()
QString lmms::Note::classNodeName () inline static
Definition at line 231 of file Note.h.
Referenced by nodeName(), and lmms::gui::PianoRoll::pasteNotes().
clone()
Note * lmms::Note::clone () const
Performs a deep copy and returns an owning raw pointer.
Definition at line 97 of file Note.cpp.
References Note(), and m_detuning.
Referenced by lmms::MidiClip::addNote().
createDetuning()
void lmms::Note::createDetuning ()
Definition at line 230 of file Note.cpp.
References lmms::AutomationClip::Linear, m_detuning, and lmms::MaxDetuning.
Referenced by Note(), loadSettings(), and lmms::gui::PianoRoll::mousePressEvent().
detuning()
const std::shared_ptr< DetuningHelper > & lmms::Note::detuning () const inline
Definition at line 243 of file Note.h.
References m_detuning.
Referenced by lmms::NotePlayHandle::BaseDetuning::BaseDetuning(), Note(), lmms::NotePlayHandle::NotePlayHandle(), lmms::gui::PianoRoll::drawDetuningInfo(), lmms::gui::PianoRoll::finishRecordNote(), lmms::gui::PianoRoll::mousePressEvent(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), and lmms::NotePlayHandle::processTimePos().
endPos()
TimePos lmms::Note::endPos () const inline
Definition at line 189 of file Note.h.
References length(), and pos.
Referenced by lmms::gui::MidiClipView::clearNotesOutOfBounds(), and lmms::gui::MidiClipView::destructiveSplitClip().
getPanning()
panning_t lmms::Note::getPanning () const inline
Definition at line 226 of file Note.h.
References m_panning.
Referenced by lmms::MidiClip::cloneSteps(), lmms::gui::PianoRoll::drawNoteRect(), lmms::gui::PianoRoll::mousePressEvent(), lmms::StepRecorder::notePressed(), lmms::NotePlayHandle::operator==(), lmms::InstrumentTrack::processAudioBuffer(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), lmms::gui::PianoRoll::startRecordNote(), and lmms::gui::PianoRoll::testPlayNote().
getVolume()
volume_t lmms::Note::getVolume () const inline
Definition at line 216 of file Note.h.
References m_volume.
Referenced by lmms::MidiClip::cloneSteps(), lmms::gui::PianoRoll::drawNoteRect(), midiVelocity(), lmms::gui::PianoRoll::mousePressEvent(), lmms::StepRecorder::notePressed(), lmms::NotePlayHandle::operator==(), lmms::gui::MidiClipView::paintEvent(), lmms::InstrumentTrack::processAudioBuffer(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), lmms::gui::PianoRoll::startRecordNote(), and lmms::gui::MidiClipView::wheelEvent().
hasDetuningInfo()
bool lmms::Note::hasDetuningInfo () const
Definition at line 244 of file Note.cpp.
References m_detuning.
isPlaying()
bool lmms::Note::isPlaying () const inline
Definition at line 184 of file Note.h.
References m_isPlaying.
Referenced by lmms::gui::PianoRoll::mouseMoveEvent(), setIsPlaying(), and lmms::gui::PianoRoll::testPlayNote().
key()
int lmms::Note::key () const inline
Definition at line 211 of file Note.h.
References m_key.
Referenced by Note(), lmms::NotePlayHandle::~NotePlayHandle(), lmms::MidiClip::cloneSteps(), lmms::gui::PianoRoll::drawNoteRect(), lmms::gui::PianoRoll::finishRecordNote(), lmms::gui::PianoRoll::glueNotes(), lmms::NotePlayHandle::midiKey(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::StepRecorder::notePressed(), lmms::StepRecorder::noteReleased(), lmms::NotePlayHandle::operator==(), lmms::NotePlayHandle::play(), lmms::InstrumentFunctionArpeggio::processNote(), lmms::InstrumentFunctionNoteStacking::processNote(), setKey(), lmms::gui::PianoRoll::startRecordNote(), lmms::gui::PianoRoll::testPlayNote(), and lmms::NotePlayHandle::updateFrequency().
length()
const TimePos & lmms::Note::length () const inline
Definition at line 195 of file Note.h.
References m_length.
Referenced by Note(), lmms::MidiClip::cloneSteps(), lmms::gui::PianoRoll::dragNotes(), endPos(), lmms::gui::PianoRoll::finishRecordNote(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::NotePlayHandle::operator==(), lmms::InstrumentFunctionNoteStacking::processNote(), quantizeLength(), setLength(), and withinRange().
lessThan()
bool lmms::Note::lessThan (const Note * lhs, const Note * rhs) inline static
Definition at line 149 of file Note.h.
References Note().
Referenced by lmms::MidiClip::addNote(), lmms::gui::PianoRoll::fitNoteLengths(), and lmms::MidiClip::rearrangeAllNotes().
loadSettings()
void lmms::Note::loadSettings (const QDomElement & _this) override protected virtual
Implements lmms::SerializingObject.
Definition at line 207 of file Note.cpp.
References createDetuning(), lmms::KeysPerOctave, m_detuning, m_key, m_length, m_panning, m_pos, m_type, m_volume, oldKey(), and Regular.
midiVelocity()
int lmms::Note::midiVelocity (int midiBaseVelocity) const inline
Definition at line 221 of file Note.h.
References lmms::DefaultVolume, getVolume(), and lmms::MidiMaxVelocity.
Referenced by lmms::gui::PianoRoll::mouseMoveEvent(), lmms::NotePlayHandle::play(), lmms::NotePlayHandle::setVolume(), and lmms::gui::PianoRoll::testPlayNote().
nodeName()
QString lmms::Note::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 236 of file Note.h.
References classNodeName().
oldKey()
int lmms::Note::oldKey () const inline
Definition at line 169 of file Note.h.
References m_oldKey.
Referenced by loadSettings(), and setOldKey().
oldLength()
TimePos lmms::Note::oldLength () const inline
Definition at line 179 of file Note.h.
References m_oldLength.
Referenced by lmms::gui::PianoRoll::dragNotes(), and setOldLength().
oldPos()
TimePos lmms::Note::oldPos () const inline
Definition at line 174 of file Note.h.
References m_oldPos.
Referenced by lmms::gui::PianoRoll::dragNotes(), and setOldPos().
operator=()
Note & lmms::Note::operator= (const Note & note)
Definition at line 78 of file Note.cpp.
References Note(), m_detuning, m_isPlaying, m_key, m_length, m_oldKey, m_oldLength, m_oldPos, m_panning, m_pos, m_selected, m_type, and m_volume.
pos() [1/2]
const TimePos & lmms::Note::pos () const inline
Definition at line 200 of file Note.h.
References m_pos.
Referenced by Note(), lmms::gui::MidiClipView::clearNotesOutOfBounds(), lmms::gui::PianoRoll::copyToClipboard(), lmms::gui::MidiClipView::destructiveSplitClip(), lmms::gui::PianoRoll::dragNotes(), lmms::gui::PianoRoll::mouseDoubleClickEvent(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::NotePlayHandle::operator==(), lmms::gui::PianoRoll::pasteNotes(), lmms::NotePlayHandle::processTimePos(), quantizePos(), setPos(), lmms::gui::PianoRoll::startRecordNote(), and withinRange().
pos() [2/2]
TimePos lmms::Note::pos (TimePos basePos) const inline
Definition at line 205 of file Note.h.
References m_pos.
quantized()
TimePos lmms::Note::quantized (const TimePos & m, const int qGrid) static
Definition at line 156 of file Note.cpp.
Referenced by lmms::gui::PianoRoll::dragNotes(), lmms::gui::AutomationEditor::drawLine(), lmms::gui::AutomationEditor::mousePressEvent(), lmms::gui::PianoRoll::pasteNotes(), lmms::AutomationClip::putValue(), lmms::AutomationClip::putValues(), quantizeLength(), quantizePos(), and lmms::AutomationClip::setDragValue().
quantizeLength()
void lmms::Note::quantizeLength (const int qGrid)
Definition at line 169 of file Note.cpp.
References length(), quantized(), and setLength().
Referenced by lmms::gui::PianoRoll::finishRecordNote(), and lmms::gui::PianoRoll::quantizeNotes().
quantizePos()
void lmms::Note::quantizePos (const int qGrid)
Definition at line 181 of file Note.cpp.
References pos(), quantized(), and setPos().
Referenced by lmms::gui::PianoRoll::finishRecordNote(), and lmms::gui::PianoRoll::quantizeNotes().
saveSettings()
void lmms::Note::saveSettings (QDomDocument & doc, QDomElement & parent) override protected virtual
Implements lmms::SerializingObject.
Definition at line 189 of file Note.cpp.
References m_detuning, m_key, m_length, m_panning, m_pos, m_type, and m_volume.
selected()
bool lmms::Note::selected () const inline
Definition at line 164 of file Note.h.
References m_selected.
Referenced by lmms::gui::PianoRoll::drawNoteRect(), lmms::gui::PianoRoll::mouseMoveEvent(), and setSelected().
setIsPlaying()
void lmms::Note::setIsPlaying (const bool isPlaying) inline
Definition at line 135 of file Note.h.
References isPlaying(), and m_isPlaying.
Referenced by lmms::gui::PianoRoll::mouseMoveEvent(), and lmms::gui::PianoRoll::testPlayNote().
setKey()
void lmms::Note::setKey (const int key)
Definition at line 129 of file Note.cpp.
References k, key(), m_key, and lmms::NumKeys.
Referenced by lmms::MidiClip::cloneSteps().
setLength()
void lmms::Note::setLength (const TimePos & length)
Definition at line 113 of file Note.cpp.
References length(), and m_length.
Referenced by lmms::gui::MidiClipView::clearNotesOutOfBounds(), lmms::MidiClip::cloneSteps(), lmms::gui::MidiClipView::destructiveSplitClip(), lmms::gui::MidiClipView::mergeClips(), lmms::NotePlayHandle::noteOff(), quantizeLength(), lmms::MidiClip::splitNotes(), and lmms::MidiClip::splitNotesAlongLine().
setOldKey()
void lmms::Note::setOldKey (const int oldKey) inline
Definition at line 128 of file Note.h.
References m_oldKey, and oldKey().
setOldLength()
void lmms::Note::setOldLength (const TimePos & oldLength) inline
Definition at line 131 of file Note.h.
References m_oldLength, and oldLength().
setOldPos()
void lmms::Note::setOldPos (const TimePos & oldPos) inline
Definition at line 129 of file Note.h.
References m_oldPos, and oldPos().
setPanning()
void lmms::Note::setPanning (panning_t panning) virtual
Reimplemented in lmms::NotePlayHandle.
Definition at line 147 of file Note.cpp.
References m_panning, lmms::PanningLeft, and lmms::PanningRight.
Referenced by lmms::MidiClip::cloneSteps(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::mousePressEvent(), and lmms::NotePlayHandle::setPanning().
setPos()
void lmms::Note::setPos (const TimePos & pos)
Definition at line 121 of file Note.cpp.
References m_pos, and pos().
Referenced by lmms::gui::MidiClipView::clearNotesOutOfBounds(), lmms::gui::PianoRoll::copyToClipboard(), lmms::gui::MidiClipView::destructiveSplitClip(), lmms::gui::MidiClipView::mergeClips(), lmms::gui::PianoRoll::pasteNotes(), quantizePos(), lmms::MidiClip::splitNotes(), and lmms::MidiClip::splitNotesAlongLine().
setSelected()
void lmms::Note::setSelected (const bool selected) inline
Definition at line 127 of file Note.h.
References m_selected, and selected().
Referenced by lmms::gui::PianoRoll::mousePressEvent(), and lmms::gui::PianoRoll::pasteNotes().
setType()
void lmms::Note::setType (Type t) inline
Definition at line 124 of file Note.h.
References m_type.
Referenced by lmms::MidiClip::addStepNote().
setVolume()
void lmms::Note::setVolume (volume_t volume) virtual
Reimplemented in lmms::NotePlayHandle.
Definition at line 138 of file Note.cpp.
References m_volume, lmms::MaxVolume, and lmms::MinVolume.
Referenced by lmms::MidiClip::cloneSteps(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::NotePlayHandle::setVolume(), and lmms::gui::MidiClipView::wheelEvent().
type()
Type lmms::Note::type () const inline
Definition at line 123 of file Note.h.
References m_type.
withinRange()
bool lmms::Note::withinRange (int tickStart, int tickEnd) const
Definition at line 251 of file Note.cpp.
References lmms::TimePos::getTicks(), length(), and pos().
Referenced by lmms::gui::PianoRoll::mouseMoveEvent().
Member Data Documentation
m_detuning
std::shared_ptr<DetuningHelper> lmms::Note::m_detuning private
Definition at line 269 of file Note.h.
Referenced by Note(), Note(), clone(), createDetuning(), detuning(), hasDetuningInfo(), loadSettings(), operator=(), and saveSettings().
m_isPlaying
bool lmms::Note::m_isPlaying private
Definition at line 262 of file Note.h.
Referenced by Note(), Note(), isPlaying(), operator=(), and setIsPlaying().
m_key
int lmms::Note::m_key private
Definition at line 264 of file Note.h.
Referenced by Note(), Note(), key(), loadSettings(), operator=(), saveSettings(), and setKey().
m_length
TimePos lmms::Note::m_length private
Definition at line 267 of file Note.h.
Referenced by Note(), Note(), length(), loadSettings(), operator=(), saveSettings(), and setLength().
m_oldKey
int lmms::Note::m_oldKey private
Definition at line 259 of file Note.h.
Referenced by Note(), Note(), oldKey(), operator=(), and setOldKey().
m_oldLength
TimePos lmms::Note::m_oldLength private
Definition at line 261 of file Note.h.
Referenced by Note(), Note(), oldLength(), operator=(), and setOldLength().
m_oldPos
TimePos lmms::Note::m_oldPos private
Definition at line 260 of file Note.h.
Referenced by Note(), Note(), oldPos(), operator=(), and setOldPos().
m_panning
panning_t lmms::Note::m_panning private
Definition at line 266 of file Note.h.
Referenced by Note(), Note(), getPanning(), loadSettings(), operator=(), saveSettings(), and setPanning().
m_pos
TimePos lmms::Note::m_pos private
Definition at line 268 of file Note.h.
Referenced by Note(), Note(), loadSettings(), operator=(), pos(), pos(), saveSettings(), and setPos().
m_selected
bool lmms::Note::m_selected private
Definition at line 258 of file Note.h.
Referenced by Note(), Note(), operator=(), selected(), and setSelected().
m_type
Type lmms::Note::m_type = Type::Regular private
Definition at line 271 of file Note.h.
Referenced by Note(), loadSettings(), operator=(), saveSettings(), setType(), and type().
m_volume
volume_t lmms::Note::m_volume private
Definition at line 265 of file Note.h.
Referenced by Note(), Note(), getVolume(), loadSettings(), operator=(), saveSettings(), and setVolume().
The documentation for this class was generated from the following files:
include/Note.h
src/core/Note.cpp