LMMS: Jack::JackBoomerDriver Class Reference
Jack::JackBoomerDriver Class Reference
The Boomer driver.
#include <JackBoomerDriver.h>
Classes
class JackBoomerDriverInput
class JackBoomerDriverOutput
Public Member Functions
JackBoomerDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackBoomerDriver ()
int Close ()
bool IsFixedBufferSize ()
int Open (jack_nframes_t frames_per_cycle, int user_nperiods, jack_nframes_t rate, bool capturing, bool playing, int chan_in, int chan_out, bool excl, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency, int bits, bool syncio)
int SetBufferSize (jack_nframes_t buffer_size)
int Start ()
int Stop ()
Public Member Functions inherited from Jack::JackAudioDriver
JackAudioDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackAudioDriver ()
virtual int Attach ()
virtual int ClientNotify (int refnum, const char *name, int notify, int sync, const char *message, int value1, int value2)
virtual int Detach ()
virtual int Open (jack_nframes_t buffer_size, jack_nframes_t samplerate, bool capturing, bool playing, int inchannels, int outchannels, bool monitor, const char *capture_driver_name, const char *playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency)
virtual int Process ()
virtual int SetSampleRate (jack_nframes_t sample_rate)
virtual int Write ()
Public Member Functions inherited from Jack::JackDriver
JackDriver (const char *name, const char *alias, JackLockedEngine *engine, JackSynchro *table)
virtual ~JackDriver ()
void AddSlave (JackDriverInterface *slave)
virtual JackClientControl * GetClientControl () const
bool GetMaster ()
std::list< JackDriverInterface * > GetSlaves ()
virtual bool Initialize ()
virtual bool IsRealTime () const
virtual bool IsRunning () const
virtual int Open ()
virtual int ProcessRead ()
virtual int ProcessReadAsync ()
int ProcessReadSlaves ()
virtual int ProcessReadSync ()
virtual int ProcessWrite ()
virtual int ProcessWriteAsync ()
int ProcessWriteSlaves ()
virtual int ProcessWriteSync ()
virtual int Read ()
void RemoveSlave (JackDriverInterface *slave)
void SetMaster (bool onoff)
Public Member Functions inherited from Jack::JackDriverInterface
JackDriverInterface ()
virtual ~JackDriverInterface ()
Public Member Functions inherited from Jack::JackClientInterface
JackClientInterface ()
virtual ~JackClientInterface ()
Private Types
enum {
kRead = 1 ,
kWrite = 2 ,
kReadWrite = 3
}
Private Member Functions
void CloseAux ()
void DisplayDeviceInfo ()
int OpenAux ()
int OpenInput ()
int OpenOutput ()
void SetSampleFormat ()
void SynchronizeRead ()
void SynchronizeWrite ()
Private Attributes
int fBits
bool fExcl
unsigned int fFragmentSize
int fInFD
void * fInputBuffer
unsigned int fInputBufferSize
JackBoomerDriverInput fInputHandler
JackThread fInputThread
int fNperiods
int fOutFD
void * fOutputBuffer
unsigned int fOutputBufferSize
JackBoomerDriverOutput fOutputHandler
JackThread fOutputThread
sem_t fReadSema
int fRWMode
int fSampleFormat
unsigned int fSampleSize
bool fSyncIO
sem_t fWriteSema
Additional Inherited Members
Protected Member Functions inherited from Jack::JackAudioDriver
jack_default_audio_sample_t * GetInputBuffer (int port_index)
jack_default_audio_sample_t * GetMonitorBuffer (int port_index)
jack_default_audio_sample_t * GetOutputBuffer (int port_index)
void HandleLatencyCallback (int status)
int ProcessAsync ()
void ProcessGraphAsync ()
void ProcessGraphAsyncMaster ()
void ProcessGraphAsyncSlave ()
void ProcessGraphSync ()
void ProcessGraphSyncMaster ()
void ProcessGraphSyncSlave ()
int ProcessSync ()
virtual void UpdateLatencies ()
Protected Member Functions inherited from Jack::JackDriver
void CycleIncTime ()
void CycleTakeBeginTime ()
void CycleTakeEndTime ()
virtual void LoadConnections (int alias, bool full_name=true)
std::string MatchPortName (const char *name, const char **ports, int alias, const std::string &type)
void NotifyBufferSize (jack_nframes_t buffer_size)
void NotifyFailure (int code, const char *reason)
void NotifySampleRate (jack_nframes_t sample_rate)
void NotifyXRun (jack_time_t callback_usecs, float delayed_usecs)
virtual int ResumeRefNum ()
virtual void SaveConnections (int alias)
void SetupDriverSync (int ref, bool freewheel)
In "async" mode, the server does not synchronize itself on the output drivers, thus it would never "consume" the activations.
virtual int StartSlaves ()
virtual int StopSlaves ()
virtual int SuspendRefNum ()
Protected Attributes inherited from Jack::JackDriver
char fAliasName [JACK_CLIENT_NAME_SIZE+1]
jack_time_t fBeginDateUst
int fCaptureChannels
char fCaptureDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fCaptureLatency
jack_port_id_t fCapturePortList [DRIVER_PORT_NUM]
JackClientControl fClientControl
driver_connections_list_t fConnections
float fDelayedUsecs
jack_time_t fEndDateUst
JackLockedEngine * fEngine
JackEngineControl * fEngineControl
JackGraphManager * fGraphManager
bool fIsMaster
bool fIsRunning
jack_port_id_t fMonitorPortList [DRIVER_PORT_NUM]
int fPlaybackChannels
char fPlaybackDriverName [JACK_CLIENT_NAME_SIZE+1]
jack_nframes_t fPlaybackLatency
jack_port_id_t fPlaybackPortList [DRIVER_PORT_NUM]
std::list< JackDriverInterface * > fSlaveList
JackSynchro * fSynchroTable
bool fWithMonitorPorts
Detailed Description
The Boomer driver.
Definition at line 45 of file JackBoomerDriver.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
kRead
kWrite
kReadWrite
Definition at line 48 of file JackBoomerDriver.h.
Constructor & Destructor Documentation
JackBoomerDriver()
Jack::JackBoomerDriver::JackBoomerDriver (const char * name, const char * alias, JackLockedEngine * engine, JackSynchro * table)
Definition at line 234 of file JackBoomerDriver.cpp.
References Jack::JackAudioDriver::JackAudioDriver(), fBits, fExcl, fFragmentSize, fInFD, fInputBuffer, fInputBufferSize, fInputHandler, fInputThread, fNperiods, fOutFD, fOutputBuffer, fOutputBufferSize, fOutputHandler, fOutputThread, fReadSema, fRWMode, fSampleFormat, fSampleSize, fSyncIO, and fWriteSema.
Referenced by Jack::JackBoomerDriver::JackBoomerDriverInput::JackBoomerDriverInput(), and Jack::JackBoomerDriver::JackBoomerDriverOutput::JackBoomerDriverOutput().
~JackBoomerDriver()
Jack::JackBoomerDriver::~JackBoomerDriver () virtual
Definition at line 248 of file JackBoomerDriver.cpp.
References fReadSema, and fWriteSema.
Member Function Documentation
Close()
int Jack::JackBoomerDriver::Close () virtual
Reimplemented from Jack::JackDriver.
Definition at line 441 of file JackBoomerDriver.cpp.
References Jack::JackClientInterface::Close(), CloseAux(), file, i, jack_error, and jack_info().
Referenced by Open().
CloseAux()
void Jack::JackBoomerDriver::CloseAux () private
Definition at line 511 of file JackBoomerDriver.cpp.
References fInFD, fInputBuffer, fOutFD, fOutputBuffer, fRWMode, kRead, and kWrite.
Referenced by Close(), and SetBufferSize().
DisplayDeviceInfo()
void Jack::JackBoomerDriver::DisplayDeviceInfo () private
Definition at line 141 of file JackBoomerDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fEngineControl, fFragmentSize, fInFD, fInputBufferSize, fOutFD, fOutputBufferSize, Jack::JackDriver::fPlaybackChannels, fRWMode, fSampleFormat, jack_error, jack_info(), kRead, and kWrite.
Referenced by OpenAux().
IsFixedBufferSize()
bool Jack::JackBoomerDriver::IsFixedBufferSize () inline virtual
Reimplemented from Jack::JackDriver.
Definition at line 148 of file JackBoomerDriver.h.
Open()
int Jack::JackBoomerDriver::Open (jack_nframes_t frames_per_cycle, int user_nperiods, jack_nframes_t rate, bool capturing, bool playing, int chan_in, int chan_out, bool excl, bool monitor, const char * capture_driver_name, const char * playback_driver_name, jack_nframes_t capture_latency, jack_nframes_t playback_latency, int bits, bool syncio)
Definition at line 394 of file JackBoomerDriver.cpp.
References capture_latency, Close(), fBits, Jack::JackDriver::fEngineControl, fExcl, fNperiods, fRWMode, fSyncIO, jack_error, kRead, kWrite, Jack::JackAudioDriver::Open(), OpenAux(), and playback_latency.
Referenced by driver_initialize().
OpenAux()
int Jack::JackBoomerDriver::OpenAux () private
Definition at line 495 of file JackBoomerDriver.cpp.
References DisplayDeviceInfo(), fRWMode, kRead, kWrite, OpenInput(), OpenOutput(), and SetSampleFormat().
Referenced by Open(), and SetBufferSize().
OpenInput()
int Jack::JackBoomerDriver::OpenInput () private
Definition at line 254 of file JackBoomerDriver.cpp.
References Jack::JackDriver::fCaptureChannels, Jack::JackDriver::fCaptureDriverName, Jack::JackDriver::fEngineControl, fExcl, fInFD, fInputBuffer, fInputBufferSize, fSampleFormat, fSampleSize, Jack::int2pow2(), jack_error, jack_info(), and jack_log().
Referenced by OpenAux().
OpenOutput()
int Jack::JackBoomerDriver::OpenOutput () private
Definition at line 324 of file JackBoomerDriver.cpp.
References Jack::JackDriver::fEngineControl, fExcl, fOutFD, fOutputBuffer, fOutputBufferSize, Jack::JackDriver::fPlaybackChannels, Jack::JackDriver::fPlaybackDriverName, fSampleFormat, fSampleSize, Jack::int2pow2(), jack_error, jack_info(), and jack_log().
Referenced by OpenAux().
SetBufferSize()
int Jack::JackBoomerDriver::SetBufferSize (jack_nframes_t buffer_size) virtual
Reimplemented from Jack::JackAudioDriver.
Definition at line 804 of file JackBoomerDriver.cpp.
References CloseAux(), OpenAux(), and Jack::JackAudioDriver::SetBufferSize().
SetSampleFormat()
void Jack::JackBoomerDriver::SetSampleFormat () private
Definition at line 121 of file JackBoomerDriver.cpp.
References fBits, fSampleFormat, and fSampleSize.
Referenced by OpenAux().
Start()
int Jack::JackBoomerDriver::Start () virtual
Reimplemented from Jack::JackDriver.
Definition at line 532 of file JackBoomerDriver.cpp.
References fFragmentSize, fInFD, fInputThread, fNperiods, fOutFD, fOutputBuffer, fOutputBufferSize, fOutputThread, fSyncIO, i, jack_error, jack_log(), and Jack::JackDriverInterface::Start().
Stop()
int Jack::JackBoomerDriver::Stop () virtual
Reimplemented from Jack::JackDriver.
Definition at line 609 of file JackBoomerDriver.cpp.
References fInFD, fInputThread, fOutFD, and fOutputThread.
SynchronizeRead()
void Jack::JackBoomerDriver::SynchronizeRead () private
Definition at line 791 of file JackBoomerDriver.cpp.
References fReadSema, fWriteSema, and Jack::JackAudioDriver::Process().
SynchronizeWrite()
void Jack::JackBoomerDriver::SynchronizeWrite () private
Definition at line 798 of file JackBoomerDriver.cpp.
References fReadSema, and fWriteSema.
Member Data Documentation
fBits
int Jack::JackBoomerDriver::fBits private
Definition at line 89 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), Open(), and SetSampleFormat().
fExcl
bool Jack::JackBoomerDriver::fExcl private
Definition at line 95 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), Open(), OpenInput(), and OpenOutput().
fFragmentSize
unsigned int Jack::JackBoomerDriver::fFragmentSize private
Definition at line 93 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), DisplayDeviceInfo(), and Start().
fInFD
int Jack::JackBoomerDriver::fInFD private
Definition at line 86 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), CloseAux(), DisplayDeviceInfo(), OpenInput(), Start(), and Stop().
fInputBuffer
void* Jack::JackBoomerDriver::fInputBuffer private
Definition at line 101 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), CloseAux(), and OpenInput().
fInputBufferSize
unsigned int Jack::JackBoomerDriver::fInputBufferSize private
Definition at line 98 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), DisplayDeviceInfo(), and OpenInput().
fInputHandler
JackBoomerDriverInput Jack::JackBoomerDriver::fInputHandler private
Definition at line 110 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver().
fInputThread
JackThread Jack::JackBoomerDriver::fInputThread private
Definition at line 107 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), Start(), and Stop().
fNperiods
int Jack::JackBoomerDriver::fNperiods private
Definition at line 91 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), Open(), and Start().
fOutFD
int Jack::JackBoomerDriver::fOutFD private
Definition at line 87 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), CloseAux(), DisplayDeviceInfo(), OpenOutput(), Start(), and Stop().
fOutputBuffer
void* Jack::JackBoomerDriver::fOutputBuffer private
Definition at line 102 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), CloseAux(), OpenOutput(), and Start().
fOutputBufferSize
unsigned int Jack::JackBoomerDriver::fOutputBufferSize private
Definition at line 99 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), DisplayDeviceInfo(), OpenOutput(), and Start().
fOutputHandler
JackBoomerDriverOutput Jack::JackBoomerDriver::fOutputHandler private
Definition at line 111 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver().
fOutputThread
JackThread Jack::JackBoomerDriver::fOutputThread private
Definition at line 108 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), Start(), and Stop().
fReadSema
sem_t Jack::JackBoomerDriver::fReadSema private
Definition at line 104 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), ~JackBoomerDriver(), SynchronizeRead(), and SynchronizeWrite().
fRWMode
int Jack::JackBoomerDriver::fRWMode private
Definition at line 94 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), CloseAux(), DisplayDeviceInfo(), Open(), and OpenAux().
fSampleFormat
int Jack::JackBoomerDriver::fSampleFormat private
Definition at line 90 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), DisplayDeviceInfo(), OpenInput(), OpenOutput(), and SetSampleFormat().
fSampleSize
unsigned int Jack::JackBoomerDriver::fSampleSize private
Definition at line 92 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), OpenInput(), OpenOutput(), and SetSampleFormat().
fSyncIO
bool Jack::JackBoomerDriver::fSyncIO private
Definition at line 96 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), Open(), and Start().
fWriteSema
sem_t Jack::JackBoomerDriver::fWriteSema private
Definition at line 105 of file JackBoomerDriver.h.
Referenced by JackBoomerDriver(), ~JackBoomerDriver(), SynchronizeRead(), and SynchronizeWrite().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/solaris/oss/JackBoomerDriver.h
src/3rdparty/jack2/solaris/oss/JackBoomerDriver.cpp