LMMS: src/3rdparty/jack2/common/netjack.h File Reference
netjack.h File Reference
#include <unistd.h>
#include <jack/types.h>
#include <jack/jack.h>
#include <jack/transport.h>
#include "jack/jslist.h"
Classes
struct _netjack_driver_state
Typedefs
typedef struct _netjack_driver_state netjack_driver_state_t
Functions
void netjack_attach (netjack_driver_state_t *netj)
void netjack_detach (netjack_driver_state_t *netj)
netjack_driver_state_t * netjack_init (netjack_driver_state_t *netj, jack_client_t *client, const char *name, unsigned int capture_ports, unsigned int playback_ports, unsigned int capture_ports_midi, unsigned int playback_ports_midi, jack_nframes_t sample_rate, jack_nframes_t period_size, unsigned int listen_port, unsigned int transport_sync, unsigned int resample_factor, unsigned int resample_factor_up, unsigned int bitdepth, unsigned int use_autoconfig, unsigned int latency, unsigned int redundancy, int dont_htonl_floats, int always_deadline, int jitter_val)
void netjack_read (netjack_driver_state_t *netj, jack_nframes_t nframes)
void netjack_release (netjack_driver_state_t *netj)
void netjack_send_silence (netjack_driver_state_t *netj, int syncstate)
int netjack_startup (netjack_driver_state_t *netj)
int netjack_wait (netjack_driver_state_t *netj)
void netjack_write (netjack_driver_state_t *netj, jack_nframes_t nframes, int syncstate)
Typedef Documentation
netjack_driver_state_t
typedef struct _netjack_driver_state netjack_driver_state_t
Definition at line 47 of file netjack.h.
Function Documentation
netjack_attach()
void netjack_attach (netjack_driver_state_t * netj)
netjack_detach()
void netjack_detach (netjack_driver_state_t * netj)
netjack_init()
netjack_driver_state_t * netjack_init (netjack_driver_state_t * netj, jack_client_t * client, const char * name, unsigned int capture_ports, unsigned int playback_ports, unsigned int capture_ports_midi, unsigned int playback_ports_midi, jack_nframes_t sample_rate, jack_nframes_t period_size, unsigned int listen_port, unsigned int transport_sync, unsigned int resample_factor, unsigned int resample_factor_up, unsigned int bitdepth, unsigned int use_autoconfig, unsigned int latency, unsigned int redundancy, int dont_htonl_floats, int always_deadline, int jitter_val)
References client().
Referenced by Jack::JackNetOneDriver::JackNetOneDriver().
netjack_read()
void netjack_read (netjack_driver_state_t * netj, jack_nframes_t nframes)
netjack_release()
void netjack_release (netjack_driver_state_t * netj)
Referenced by Jack::JackNetOneDriver::Close(), and Jack::JackNetOneDriver::Initialize().
netjack_send_silence()
void netjack_send_silence (netjack_driver_state_t * netj, int syncstate)
netjack_startup()
int netjack_startup (netjack_driver_state_t * netj)
Referenced by Jack::JackNetOneDriver::Initialize().
netjack_wait()
int netjack_wait (netjack_driver_state_t * netj)
Referenced by Jack::JackNetOneDriver::Read().
netjack_write()
void netjack_write (netjack_driver_state_t * netj, jack_nframes_t nframes, int syncstate)