LMMS: lmms::NotePlayHandleManager Class Reference
lmms::NotePlayHandleManager Class Reference
#include <NotePlayHandle.h>
Static Public Member Functions
static NotePlayHandle * acquire (InstrumentTrack *instrumentTrack, const f_cnt_t offset, const f_cnt_t frames, const Note &noteToPlay, NotePlayHandle *parent=nullptr, int midiEventChannel=-1, NotePlayHandle::Origin origin=NotePlayHandle::Origin::MidiClip)
static void extend (int i)
static void free ()
static void init ()
static void release (NotePlayHandle *nph)
Static Private Attributes
static NotePlayHandle ** s_available
static std::atomic_int s_availableIndex
static QReadWriteLock s_mutex
static int s_size
Detailed Description
Definition at line 339 of file NotePlayHandle.h.
Member Function Documentation
acquire()
NotePlayHandle * lmms::NotePlayHandleManager::acquire (InstrumentTrack * instrumentTrack, const f_cnt_t offset, const f_cnt_t frames, const Note & noteToPlay, NotePlayHandle * parent = nullptr, int midiEventChannel = -1, NotePlayHandle::Origin origin = NotePlayHandle::Origin::MidiClip) static
Definition at line 627 of file NotePlayHandle.cpp.
References extend(), lmms::NPH_CACHE_INCREMENT, s_available, s_availableIndex, and s_mutex.
Referenced by lmms::PresetPreviewPlayHandle::PresetPreviewPlayHandle(), lmms::InstrumentTrack::play(), lmms::InstrumentTrack::processInEvent(), lmms::InstrumentFunctionArpeggio::processNote(), and lmms::InstrumentFunctionNoteStacking::processNote().
extend()
void lmms::NotePlayHandleManager::extend (int i) static
Definition at line 655 of file NotePlayHandle.cpp.
References i, s_available, s_availableIndex, and s_size.
Referenced by acquire().
free()
void lmms::NotePlayHandleManager::free () static
Definition at line 671 of file NotePlayHandle.cpp.
References s_available.
Referenced by main().
init()
void lmms::NotePlayHandleManager::init () static
Definition at line 611 of file NotePlayHandle.cpp.
References i, lmms::INITIAL_NPH_CACHE, s_available, s_availableIndex, and s_size.
Referenced by main().
release()
void lmms::NotePlayHandleManager::release (NotePlayHandle * nph) static
Definition at line 646 of file NotePlayHandle.cpp.
References s_available, s_availableIndex, and s_mutex.
Referenced by lmms::AudioEngine::addPlayHandle(), lmms::AudioEngine::removePlayHandle(), lmms::AudioEngine::removePlayHandlesOfTypes(), lmms::AudioEngine::renderStageEffects(), and lmms::AudioEngine::renderStageNoteSetup().
Member Data Documentation
s_available
NotePlayHandle ** lmms::NotePlayHandleManager::s_available static private
Definition at line 355 of file NotePlayHandle.h.
Referenced by acquire(), extend(), free(), init(), and release().
s_availableIndex
std::atomic_int lmms::NotePlayHandleManager::s_availableIndex static private
Definition at line 357 of file NotePlayHandle.h.
Referenced by acquire(), extend(), init(), and release().
s_mutex
QReadWriteLock lmms::NotePlayHandleManager::s_mutex static private
Definition at line 356 of file NotePlayHandle.h.
Referenced by acquire(), and release().
s_size
int lmms::NotePlayHandleManager::s_size static private
Definition at line 358 of file NotePlayHandle.h.
Referenced by extend(), and init().
The documentation for this class was generated from the following files:
include/NotePlayHandle.h
src/core/NotePlayHandle.cpp