LMMS: Jack::JackRequest Struct Reference
Jack::JackRequest Struct Reference
Request from client to server.
#include <JackRequest.h>
Public Types
enum RequestType {
kRegisterPort = 1 ,
kUnRegisterPort = 2 ,
kConnectPorts = 3 ,
kDisconnectPorts = 4 ,
kSetTimeBaseClient = 5 ,
kActivateClient = 6 ,
kDeactivateClient = 7 ,
kDisconnectPort = 8 ,
kSetClientCapabilities = 9 ,
kGetPortConnections = 10 ,
kGetPortNConnections = 11 ,
kReleaseTimebase = 12 ,
kSetTimebaseCallback = 13 ,
kSetBufferSize = 20 ,
kSetFreeWheel = 21 ,
kClientCheck = 22 ,
kClientOpen = 23 ,
kClientClose = 24 ,
kConnectNamePorts = 25 ,
kDisconnectNamePorts = 26 ,
kGetInternalClientName = 27 ,
kInternalClientHandle = 28 ,
kInternalClientLoad = 29 ,
kInternalClientUnload = 30 ,
kPortRename = 31 ,
kNotification = 32 ,
kSessionNotify = 33 ,
kSessionReply = 34 ,
kGetClientByUUID = 35 ,
kReserveClientName = 36 ,
kGetUUIDByClient = 37 ,
kClientHasSessionCallback = 38 ,
kComputeTotalLatencies = 39 ,
kPropertyChangeNotify = 40
}
Public Member Functions
JackRequest ()
JackRequest (RequestType type)
virtual ~JackRequest ()
virtual int Read (detail::JackChannelTransactionInterface *trans)
virtual int Size ()
virtual int Write (detail::JackChannelTransactionInterface *trans)
virtual int Write (detail::JackChannelTransactionInterface *trans, int size)
Public Attributes
int fSize
RequestType fType
Detailed Description
Request from client to server.
Definition at line 70 of file JackRequest.h.
Member Enumeration Documentation
RequestType
enum Jack::JackRequest::RequestType
Enumerator
kRegisterPort
kUnRegisterPort
kConnectPorts
kDisconnectPorts
kSetTimeBaseClient
kActivateClient
kDeactivateClient
kDisconnectPort
kSetClientCapabilities
kGetPortConnections
kGetPortNConnections
kReleaseTimebase
kSetTimebaseCallback
kSetBufferSize
kSetFreeWheel
kClientCheck
kClientOpen
kClientClose
kConnectNamePorts
kDisconnectNamePorts
kGetInternalClientName
kInternalClientHandle
kInternalClientLoad
kInternalClientUnload
kPortRename
kNotification
kSessionNotify
kSessionReply
kGetClientByUUID
kReserveClientName
kGetUUIDByClient
kClientHasSessionCallback
kComputeTotalLatencies
kPropertyChangeNotify
Definition at line 73 of file JackRequest.h.
Constructor & Destructor Documentation
JackRequest() [1/2]
Jack::JackRequest::JackRequest () inline
Definition at line 113 of file JackRequest.h.
References fSize, and fType.
Referenced by Jack::JackActivateRequest::JackActivateRequest(), Jack::JackClientCheckRequest::JackClientCheckRequest(), Jack::JackClientCloseRequest::JackClientCloseRequest(), Jack::JackClientHasSessionCallbackRequest::JackClientHasSessionCallbackRequest(), Jack::JackClientNotificationRequest::JackClientNotificationRequest(), Jack::JackClientOpenRequest::JackClientOpenRequest(), Jack::JackComputeTotalLatenciesRequest::JackComputeTotalLatenciesRequest(), Jack::JackDeactivateRequest::JackDeactivateRequest(), Jack::JackGetClientNameRequest::JackGetClientNameRequest(), Jack::JackGetInternalClientNameRequest::JackGetInternalClientNameRequest(), Jack::JackGetUUIDRequest::JackGetUUIDRequest(), Jack::JackInternalClientHandleRequest::JackInternalClientHandleRequest(), Jack::JackInternalClientLoadRequest::JackInternalClientLoadRequest(), Jack::JackInternalClientUnloadRequest::JackInternalClientUnloadRequest(), Jack::JackPortConnectNameRequest::JackPortConnectNameRequest(), Jack::JackPortConnectRequest::JackPortConnectRequest(), Jack::JackPortDisconnectNameRequest::JackPortDisconnectNameRequest(), Jack::JackPortDisconnectRequest::JackPortDisconnectRequest(), Jack::JackPortRegisterRequest::JackPortRegisterRequest(), Jack::JackPortRenameRequest::JackPortRenameRequest(), Jack::JackPortUnRegisterRequest::JackPortUnRegisterRequest(), Jack::JackPropertyChangeNotifyRequest::JackPropertyChangeNotifyRequest(), Jack::JackReleaseTimebaseRequest::JackReleaseTimebaseRequest(), Jack::JackReserveNameRequest::JackReserveNameRequest(), Jack::JackSessionNotifyRequest::JackSessionNotifyRequest(), Jack::JackSessionReplyRequest::JackSessionReplyRequest(), Jack::JackSetBufferSizeRequest::JackSetBufferSizeRequest(), Jack::JackSetFreeWheelRequest::JackSetFreeWheelRequest(), and Jack::JackSetTimebaseCallbackRequest::JackSetTimebaseCallbackRequest().
JackRequest() [2/2]
Jack::JackRequest::JackRequest (RequestType type) inline
Definition at line 116 of file JackRequest.h.
References fSize, and fType.
~JackRequest()
virtual Jack::JackRequest::~JackRequest () inline virtual
Definition at line 119 of file JackRequest.h.
Member Function Documentation
Read()
virtual int Jack::JackRequest::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented in Jack::JackActivateRequest, Jack::JackClientCheckRequest, Jack::JackClientCloseRequest, Jack::JackClientHasSessionCallbackRequest, Jack::JackClientNotificationRequest, Jack::JackClientOpenRequest, Jack::JackComputeTotalLatenciesRequest, Jack::JackDeactivateRequest, Jack::JackGetClientNameRequest, Jack::JackGetInternalClientNameRequest, Jack::JackGetUUIDRequest, Jack::JackInternalClientHandleRequest, Jack::JackInternalClientLoadRequest, Jack::JackInternalClientUnloadRequest, Jack::JackPortConnectNameRequest, Jack::JackPortConnectRequest, Jack::JackPortDisconnectNameRequest, Jack::JackPortDisconnectRequest, Jack::JackPortRegisterRequest, Jack::JackPortRenameRequest, Jack::JackPortUnRegisterRequest, Jack::JackPropertyChangeNotifyRequest, Jack::JackReleaseTimebaseRequest, Jack::JackReserveNameRequest, Jack::JackSessionNotifyRequest, Jack::JackSessionReplyRequest, Jack::JackSetBufferSizeRequest, Jack::JackSetFreeWheelRequest, and Jack::JackSetTimebaseCallbackRequest.
Definition at line 122 of file JackRequest.h.
References fType, and Jack::detail::JackChannelTransactionInterface::Read().
Referenced by Jack::JackClientPipeThread::Execute(), Jack::JackSocketServerChannel::Execute(), and Jack::JackRequestDecoder::HandleRequest().
Size()
virtual int Jack::JackRequest::Size () inline virtual
Reimplemented in Jack::JackActivateRequest, Jack::JackClientCheckRequest, Jack::JackClientCloseRequest, Jack::JackClientHasSessionCallbackRequest, Jack::JackClientNotificationRequest, Jack::JackClientOpenRequest, Jack::JackComputeTotalLatenciesRequest, Jack::JackDeactivateRequest, Jack::JackGetClientNameRequest, Jack::JackGetInternalClientNameRequest, Jack::JackGetUUIDRequest, Jack::JackInternalClientHandleRequest, Jack::JackInternalClientLoadRequest, Jack::JackInternalClientUnloadRequest, Jack::JackPortConnectNameRequest, Jack::JackPortConnectRequest, Jack::JackPortDisconnectNameRequest, Jack::JackPortDisconnectRequest, Jack::JackPortRegisterRequest, Jack::JackPortRenameRequest, Jack::JackPortUnRegisterRequest, Jack::JackPropertyChangeNotifyRequest, Jack::JackReleaseTimebaseRequest, Jack::JackReserveNameRequest, Jack::JackSessionNotifyRequest, Jack::JackSessionReplyRequest, Jack::JackSetBufferSizeRequest, Jack::JackSetFreeWheelRequest, and Jack::JackSetTimebaseCallbackRequest.
Definition at line 136 of file JackRequest.h.
Write() [1/2]
virtual int Jack::JackRequest::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented in Jack::JackActivateRequest, Jack::JackClientCheckRequest, Jack::JackClientCloseRequest, Jack::JackClientHasSessionCallbackRequest, Jack::JackClientNotificationRequest, Jack::JackClientOpenRequest, Jack::JackComputeTotalLatenciesRequest, Jack::JackDeactivateRequest, Jack::JackGetClientNameRequest, Jack::JackGetInternalClientNameRequest, Jack::JackGetUUIDRequest, Jack::JackInternalClientHandleRequest, Jack::JackInternalClientLoadRequest, Jack::JackInternalClientUnloadRequest, Jack::JackPortConnectNameRequest, Jack::JackPortConnectRequest, Jack::JackPortDisconnectNameRequest, Jack::JackPortDisconnectRequest, Jack::JackPortRegisterRequest, Jack::JackPortRenameRequest, Jack::JackPortUnRegisterRequest, Jack::JackPropertyChangeNotifyRequest, Jack::JackReleaseTimebaseRequest, Jack::JackReserveNameRequest, Jack::JackSessionNotifyRequest, Jack::JackSessionReplyRequest, Jack::JackSetBufferSizeRequest, Jack::JackSetFreeWheelRequest, and Jack::JackSetTimebaseCallbackRequest.
Definition at line 127 of file JackRequest.h.
Referenced by Jack::JackGenericClientChannel::ServerAsyncCall(), Jack::JackGenericClientChannel::ServerSyncCall(), Jack::JackActivateRequest::Write(), Jack::JackClientCheckRequest::Write(), Jack::JackClientCloseRequest::Write(), Jack::JackClientHasSessionCallbackRequest::Write(), Jack::JackClientNotificationRequest::Write(), Jack::JackClientOpenRequest::Write(), Jack::JackComputeTotalLatenciesRequest::Write(), Jack::JackDeactivateRequest::Write(), Jack::JackGetClientNameRequest::Write(), Jack::JackGetInternalClientNameRequest::Write(), Jack::JackGetUUIDRequest::Write(), Jack::JackInternalClientHandleRequest::Write(), Jack::JackInternalClientLoadRequest::Write(), Jack::JackInternalClientUnloadRequest::Write(), Jack::JackPortConnectNameRequest::Write(), Jack::JackPortConnectRequest::Write(), Jack::JackPortDisconnectNameRequest::Write(), Jack::JackPortDisconnectRequest::Write(), Jack::JackPortRegisterRequest::Write(), Jack::JackPortRenameRequest::Write(), Jack::JackPortUnRegisterRequest::Write(), Jack::JackPropertyChangeNotifyRequest::Write(), Jack::JackReleaseTimebaseRequest::Write(), Jack::JackReserveNameRequest::Write(), Jack::JackSessionNotifyRequest::Write(), Jack::JackSessionReplyRequest::Write(), Jack::JackSetBufferSizeRequest::Write(), Jack::JackSetFreeWheelRequest::Write(), and Jack::JackSetTimebaseCallbackRequest::Write().
Write() [2/2]
virtual int Jack::JackRequest::Write (detail::JackChannelTransactionInterface * trans, int size) inline virtual
Definition at line 129 of file JackRequest.h.
References CheckRes, fSize, fType, and Jack::detail::JackChannelTransactionInterface::Write().
Member Data Documentation
fSize
int Jack::JackRequest::fSize
Definition at line 111 of file JackRequest.h.
Referenced by JackRequest(), JackRequest(), and Write().
fType
RequestType Jack::JackRequest::fType
Definition at line 110 of file JackRequest.h.
Referenced by JackRequest(), JackRequest(), Jack::JackClientPipeThread::Execute(), Jack::JackSocketServerChannel::Execute(), Jack::JackRequestDecoder::HandleRequest(), Read(), Jack::JackGenericClientChannel::ServerAsyncCall(), Jack::JackGenericClientChannel::ServerSyncCall(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h