LMMS: lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount > Class Template Reference
lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount > Class Template Reference
#include <AudioBufferView.h>
Public Member Functions
constexpr InterleavedFrameIteratorData ()=default
constexpr InterleavedFrameIteratorData (const InterleavedFrameIteratorData &)=default
constexpr InterleavedFrameIteratorData (T *data, proc_ch_t channels) noexcept
constexpr auto channels () const noexcept -> proc_ch_t
Protected Attributes
proc_ch_t m_channels = 0
T * m_data = nullptr
Detailed Description
template<typename T>
class lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount >
Definition at line 124 of file AudioBufferView.h.
Constructor & Destructor Documentation
InterleavedFrameIteratorData() [1/3]
template<typename T> lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount >::InterleavedFrameIteratorData () constexpr default
Referenced by InterleavedFrameIteratorData().
InterleavedFrameIteratorData() [2/3]
template<typename T> lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount >::InterleavedFrameIteratorData (const InterleavedFrameIteratorData< T, DynamicChannelCount > &) constexpr default
References InterleavedFrameIteratorData().
InterleavedFrameIteratorData() [3/3]
template<typename T> lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount >::InterleavedFrameIteratorData (T * data, proc_ch_t channels) inline constexpr noexcept
Definition at line 130 of file AudioBufferView.h.
References channels(), and m_data.
Member Function Documentation
channels()
template<typename T> auto lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount >::channels () const->proc_ch_t inline constexpr noexcept
Definition at line 136 of file AudioBufferView.h.
References m_channels.
Referenced by InterleavedFrameIteratorData().
Member Data Documentation
m_channels
template<typename T> proc_ch_t lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount >::m_channels = 0 protected
Definition at line 140 of file AudioBufferView.h.
Referenced by channels().
m_data
template<typename T> T* lmms::detail::InterleavedFrameIteratorData< T, DynamicChannelCount >::m_data = nullptr protected
Definition at line 139 of file AudioBufferView.h.
Referenced by InterleavedFrameIteratorData(), lmms::detail::InterleavedFrameIterator< T, channelCount >::operator<=>(), and lmms::detail::InterleavedFrameIterator< T, channelCount >::operator<=>().
The documentation for this class was generated from the following file:
include/AudioBufferView.h