LMMS: lmms::ThreadPool Class Reference
lmms::ThreadPool Class Reference
A thread pool that can be used for asynchronous processing.
#include <ThreadPool.h>
Public Member Functions
~ThreadPool ()
Destroys the ThreadPool object.
template<typename Fn, typename... Args>
auto enqueue (Fn &&fn, Args &&... args) -> std::future< std::invoke_result_t< Fn, Args... > >
Enqueue function fn with arguments args to be ran asynchronously.
auto numWorkers () const -> size_t
Return the number of worker threads used.
Static Public Member Functions
static auto instance () -> ThreadPool &
Return the global ThreadPool instance.
Private Member Functions
ThreadPool (size_t numWorkers)
void run ()
Private Attributes
std::atomic< bool > m_done = false
std::queue< std::function< void()> > m_queue
std::condition_variable m_runCond
std::mutex m_runMutex
std::vector< std::thread > m_workers
Static Private Attributes
static size_t s_numWorkers = std::thread::hardware_concurrency()
Detailed Description
A thread pool that can be used for asynchronous processing.
Definition at line 41 of file ThreadPool.h.
Constructor & Destructor Documentation
~ThreadPool()
lmms::ThreadPool::~ThreadPool ()
Destroys the ThreadPool object.
This blocks until all workers have finished executing.
Definition at line 40 of file ThreadPool.cpp.
References m_done, m_runCond, m_runMutex, and m_workers.
ThreadPool()
lmms::ThreadPool::ThreadPool (size_t numWorkers) private
Definition at line 29 of file ThreadPool.cpp.
References i, m_workers, numWorkers(), and run().
Referenced by instance().
Member Function Documentation
enqueue()
template<typename Fn, typename... Args> auto lmms::ThreadPool::enqueue (Fn && fn, Args &&... args)->std::future< std::invoke_result_t< Fn, Args... > > inline
Enqueue function fn with arguments args to be ran asynchronously.
Definition at line 50 of file ThreadPool.h.
References m_queue, m_runCond, and m_runMutex.
instance()
auto lmms::ThreadPool::instance () ->ThreadPool & static
Return the global ThreadPool instance.
Definition at line 77 of file ThreadPool.cpp.
References ThreadPool(), and s_numWorkers.
Referenced by lmms::gui::FileSearchJob::search().
numWorkers()
auto lmms::ThreadPool::numWorkers () const->size_t
Return the number of worker threads used.
Definition at line 55 of file ThreadPool.cpp.
References m_workers.
Referenced by ThreadPool().
run()
void lmms::ThreadPool::run () private
Definition at line 60 of file ThreadPool.cpp.
References m_done, m_queue, m_runCond, and m_runMutex.
Referenced by ThreadPool().
Member Data Documentation
m_done
std::atomic<bool> lmms::ThreadPool::m_done = false private
Definition at line 86 of file ThreadPool.h.
Referenced by ~ThreadPool(), and run().
m_queue
std::queue<std::function<void()> > lmms::ThreadPool::m_queue private
Definition at line 85 of file ThreadPool.h.
Referenced by enqueue(), and run().
m_runCond
std::condition_variable lmms::ThreadPool::m_runCond private
Definition at line 87 of file ThreadPool.h.
Referenced by ~ThreadPool(), enqueue(), and run().
m_runMutex
std::mutex lmms::ThreadPool::m_runMutex private
Definition at line 88 of file ThreadPool.h.
Referenced by ~ThreadPool(), enqueue(), and run().
m_workers
std::vector<std::thread> lmms::ThreadPool::m_workers private
Definition at line 84 of file ThreadPool.h.
Referenced by ThreadPool(), ~ThreadPool(), and numWorkers().
s_numWorkers
size_t lmms::ThreadPool::s_numWorkers = std::thread::hardware_concurrency() inline static private
Definition at line 89 of file ThreadPool.h.
Referenced by instance().
The documentation for this class was generated from the following files:
include/ThreadPool.h
src/core/ThreadPool.cpp