LMMS: lmms::Timeline Class Reference
lmms::Timeline Class Reference
#include <Timeline.h>
Public Types
enum class StopBehaviour {
BackToZero ,
BackToStart ,
KeepPosition
}
Signals
void loopEnabledChanged (bool enabled)
void stopBehaviourChanged (lmms::Timeline::StopBehaviour behaviour)
Public Member Functions
auto loopBegin () const -> TimePos
auto loopEnabled () const -> bool
auto loopEnd () const -> TimePos
auto nodeName () const -> QString override
auto playStartPosition () const -> TimePos
void setLoopBegin (TimePos begin)
void setLoopEnabled (bool enabled)
void setLoopEnd (TimePos end)
void setLoopPoints (TimePos begin, TimePos end)
void setPlayStartPosition (TimePos position)
void setStopBehaviour (StopBehaviour behaviour)
auto stopBehaviour () const -> StopBehaviour
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
virtual QString nodeName () const =0
void setHook (SerializingObjectHook *_hook)
Protected Member Functions
void loadSettings (const QDomElement &element) override
void saveSettings (QDomDocument &doc, QDomElement &element) override
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Private Attributes
TimePos m_loopBegin = TimePos{0}
bool m_loopEnabled = false
TimePos m_loopEnd = TimePos{DefaultTicksPerBar}
TimePos m_playStartPosition = TimePos{-1}
StopBehaviour m_stopBehaviour = StopBehaviour::BackToStart
Detailed Description
Definition at line 34 of file Timeline.h.
Member Enumeration Documentation
StopBehaviour
enum class lmms::Timeline::StopBehaviour strong
Enumerator
BackToZero
BackToStart
KeepPosition
Definition at line 39 of file Timeline.h.
Member Function Documentation
loadSettings()
void lmms::Timeline::loadSettings (const QDomElement & element) override protected virtual
Implements lmms::SerializingObject.
Definition at line 72 of file Timeline.cpp.
References setLoopEnabled(), setLoopPoints(), and setStopBehaviour().
loopBegin()
auto lmms::Timeline::loopBegin () const->TimePos inline
Definition at line 46 of file Timeline.h.
References m_loopBegin.
Referenced by saveSettings().
loopEnabled()
auto lmms::Timeline::loopEnabled () const->bool inline
Definition at line 48 of file Timeline.h.
References m_loopEnabled.
Referenced by saveSettings().
loopEnabledChanged
void lmms::Timeline::loopEnabledChanged (bool enabled) signal
Referenced by lmms::gui::TimeLineWidget::addToolButtons(), and setLoopEnabled().
loopEnd()
auto lmms::Timeline::loopEnd () const->TimePos inline
Definition at line 47 of file Timeline.h.
References m_loopEnd.
Referenced by saveSettings().
nodeName()
auto lmms::Timeline::nodeName () const->QString inline override
Definition at line 61 of file Timeline.h.
playStartPosition()
auto lmms::Timeline::playStartPosition () const->TimePos inline
Definition at line 55 of file Timeline.h.
References m_playStartPosition.
saveSettings()
void lmms::Timeline::saveSettings (QDomDocument & doc, QDomElement & element) override protected virtual
Implements lmms::SerializingObject.
Definition at line 64 of file Timeline.cpp.
References loopBegin(), loopEnabled(), loopEnd(), and stopBehaviour().
setLoopBegin()
void lmms::Timeline::setLoopBegin (TimePos begin)
Definition at line 33 of file Timeline.cpp.
References m_loopBegin, and m_loopEnd.
setLoopEnabled()
void lmms::Timeline::setLoopEnabled (bool enabled)
Definition at line 48 of file Timeline.cpp.
References loopEnabledChanged(), and m_loopEnabled.
Referenced by lmms::gui::TimeLineWidget::addToolButtons(), and loadSettings().
setLoopEnd()
void lmms::Timeline::setLoopEnd (TimePos end)
Definition at line 38 of file Timeline.cpp.
References m_loopBegin, and m_loopEnd.
setLoopPoints()
void lmms::Timeline::setLoopPoints (TimePos begin, TimePos end)
Definition at line 43 of file Timeline.cpp.
References m_loopBegin, and m_loopEnd.
Referenced by loadSettings().
setPlayStartPosition()
void lmms::Timeline::setPlayStartPosition (TimePos position) inline
Definition at line 58 of file Timeline.h.
References m_playStartPosition, and lmms::position().
setStopBehaviour()
void lmms::Timeline::setStopBehaviour (StopBehaviour behaviour)
Definition at line 56 of file Timeline.cpp.
References m_stopBehaviour, and stopBehaviourChanged().
Referenced by loadSettings().
stopBehaviour()
auto lmms::Timeline::stopBehaviour () const->StopBehaviour inline
Definition at line 56 of file Timeline.h.
References m_stopBehaviour.
Referenced by saveSettings().
stopBehaviourChanged
void lmms::Timeline::stopBehaviourChanged (lmms::Timeline::StopBehaviour behaviour) signal
Referenced by lmms::gui::TimeLineWidget::addToolButtons(), and setStopBehaviour().
Member Data Documentation
m_loopBegin
TimePos lmms::Timeline::m_loopBegin = TimePos{0} private
Definition at line 72 of file Timeline.h.
Referenced by loopBegin(), setLoopBegin(), setLoopEnd(), and setLoopPoints().
m_loopEnabled
bool lmms::Timeline::m_loopEnabled = false private
Definition at line 74 of file Timeline.h.
Referenced by loopEnabled(), and setLoopEnabled().
m_loopEnd
TimePos lmms::Timeline::m_loopEnd = TimePos{DefaultTicksPerBar} private
Definition at line 73 of file Timeline.h.
Referenced by loopEnd(), setLoopBegin(), setLoopEnd(), and setLoopPoints().
m_playStartPosition
TimePos lmms::Timeline::m_playStartPosition = TimePos{-1} private
Definition at line 77 of file Timeline.h.
Referenced by playStartPosition(), and setPlayStartPosition().
m_stopBehaviour
StopBehaviour lmms::Timeline::m_stopBehaviour = StopBehaviour::BackToStart private
Definition at line 76 of file Timeline.h.
Referenced by setStopBehaviour(), and stopBehaviour().
The documentation for this class was generated from the following files:
include/Timeline.h
src/core/Timeline.cpp