LMMS: Jack::JackClientNameResult Struct Reference
Jack::JackClientNameResult Struct Reference
#include <JackRequest.h>
Public Member Functions
JackClientNameResult ()
JackClientNameResult (int32_t result, const char *name)
int Read (detail::JackChannelTransactionInterface *trans)
int Write (detail::JackChannelTransactionInterface *trans)
Public Member Functions inherited from Jack::JackResult
JackResult ()
JackResult (int result)
virtual ~JackResult ()
Public Attributes
char fName [JACK_CLIENT_NAME_SIZE+1]
Public Attributes inherited from Jack::JackResult
int fResult
Detailed Description
Definition at line 1442 of file JackRequest.h.
Constructor & Destructor Documentation
JackClientNameResult() [1/2]
Jack::JackClientNameResult::JackClientNameResult () inline
Definition at line 1446 of file JackRequest.h.
References Jack::JackResult::JackResult(), and fName.
JackClientNameResult() [2/2]
Jack::JackClientNameResult::JackClientNameResult (int32_t result, const char * name) inline
Definition at line 1450 of file JackRequest.h.
References Jack::JackResult::JackResult(), and fName.
Member Function Documentation
Read()
int Jack::JackClientNameResult::Read (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 1457 of file JackRequest.h.
References CheckRes, fName, Jack::detail::JackChannelTransactionInterface::Read(), and Jack::JackResult::Read().
Write()
int Jack::JackClientNameResult::Write (detail::JackChannelTransactionInterface * trans) inline virtual
Reimplemented from Jack::JackResult.
Definition at line 1464 of file JackRequest.h.
References CheckRes, fName, Jack::detail::JackChannelTransactionInterface::Write(), and Jack::JackResult::Write().
Member Data Documentation
fName
char Jack::JackClientNameResult::fName[JACK_CLIENT_NAME_SIZE+1]
Definition at line 1444 of file JackRequest.h.
Referenced by JackClientNameResult(), JackClientNameResult(), Jack::JackGenericClientChannel::GetClientNameForUUID(), Jack::JackRequestDecoder::HandleRequest(), Read(), and Write().
The documentation for this struct was generated from the following file:
src/3rdparty/jack2/common/JackRequest.h