LMMS: lmms::MidiClientRaw Class Reference
lmms::MidiClientRaw Class Reference abstract
#include <MidiClient.h>
Classes
struct midiParserData
Public Member Functions
MidiClientRaw ()=default
~MidiClientRaw () override=default
bool isRaw () const override
Public Member Functions inherited from lmms::MidiClient
MidiClient ()=default
virtual ~MidiClient ()
virtual void addPort (MidiPort *_port)
virtual void applyPortMode (MidiPort *_port)
virtual void applyPortName (MidiPort *_port)
virtual void connectRPChanged (QObject *, const char *)
virtual void connectWPChanged (QObject *, const char *)
virtual QStringList readablePorts () const
virtual void removePort (MidiPort *_port)
virtual QString sourcePortName (const MidiEvent &) const
virtual void subscribeReadablePort (MidiPort *_port, const QString &_dest, bool _subscribe=true)
virtual void subscribeWritablePort (MidiPort *_port, const QString &_dest, bool _subscribe=true)
virtual QStringList writablePorts () const
Protected Member Functions
void parseData (const unsigned char c)
virtual void sendByte (const unsigned char c)=0
Private Member Functions
void processOutEvent (const MidiEvent &event, const TimePos &time, const MidiPort *port) override
void processParsedEvent ()
Static Private Member Functions
static int eventLength (const unsigned char event)
Private Attributes
struct lmms::MidiClientRaw::midiParserData m_midiParseData
Additional Inherited Members
Static Public Member Functions inherited from lmms::MidiClient
static MidiClient * openMidiClient ()
Protected Attributes inherited from lmms::MidiClient
std::vector< MidiPort * > m_midiPorts
Detailed Description
Definition at line 124 of file MidiClient.h.
Constructor & Destructor Documentation
MidiClientRaw()
lmms::MidiClientRaw::MidiClientRaw () default
~MidiClientRaw()
lmms::MidiClientRaw::~MidiClientRaw () override default
Member Function Documentation
eventLength()
int lmms::MidiClientRaw::eventLength (const unsigned char event) static private
Definition at line 301 of file MidiClient.cpp.
References lmms::REMAINS_80E0, and lmms::REMAINS_F0F6.
Referenced by parseData().
isRaw()
bool lmms::MidiClientRaw::isRaw () const inline override virtual
Reimplemented from lmms::MidiClient.
Definition at line 131 of file MidiClient.h.
parseData()
void lmms::MidiClientRaw::parseData (const unsigned char c) protected
Definition at line 103 of file MidiClient.cpp.
References eventLength(), m_midiParseData, lmms::MidiChannelPressure, lmms::MidiControlChange, lmms::MidiKeyPressure, lmms::MidiNoteOff, lmms::MidiNoteOn, lmms::MidiPitchBend, lmms::MidiProgramChange, lmms::MidiSystemReset, processParsedEvent(), and lmms::RAW_MIDI_PARSE_BUF_SIZE.
processOutEvent()
void lmms::MidiClientRaw::processOutEvent (const MidiEvent & event, const TimePos & time, const MidiPort * port) override private virtual
Implements lmms::MidiClient.
Definition at line 250 of file MidiClient.cpp.
References lmms::MidiEvent::channel(), lmms::MidiEvent::key(), lmms::MidiKeyPressure, lmms::MidiNoteOff, lmms::MidiNoteOn, sendByte(), lmms::MidiEvent::type(), and lmms::MidiEvent::velocity().
processParsedEvent()
void lmms::MidiClientRaw::processParsedEvent () private
Definition at line 239 of file MidiClient.cpp.
References m_midiParseData, and lmms::MidiClient::m_midiPorts.
Referenced by parseData().
sendByte()
virtual void lmms::MidiClientRaw::sendByte (const unsigned char c) protected pure virtual
Implemented in lmms::MidiDummy.
Referenced by processOutEvent().
Member Data Documentation
m_midiParseData
struct lmms::MidiClientRaw::midiParserData lmms::MidiClientRaw::m_midiParseData private
Referenced by parseData(), and processParsedEvent().
The documentation for this class was generated from the following files:
include/MidiClient.h
src/core/midi/MidiClient.cpp