LMMS: lmms::gui::TimeDisplayWidget Class Reference
lmms::gui::TimeDisplayWidget Class Reference
#include <TimeDisplayWidget.h>
Public Member Functions
TimeDisplayWidget ()
~TimeDisplayWidget () override=default
Protected Member Functions
void mousePressEvent (QMouseEvent *mouseEvent) override
Private Types
enum class DisplayMode {
MinutesSeconds ,
BarsTicks
}
Private Slots
void updateTime ()
Private Member Functions
void setDisplayMode (DisplayMode displayMode)
Private Attributes
DisplayMode m_displayMode
LcdWidget m_majorLCD
LcdWidget m_milliSecondsLCD
LcdWidget m_minorLCD
QHBoxLayout m_spinBoxesLayout
Detailed Description
Definition at line 37 of file TimeDisplayWidget.h.
Member Enumeration Documentation
DisplayMode
enum class lmms::gui::TimeDisplayWidget::DisplayMode strong private
Enumerator
MinutesSeconds
BarsTicks
Definition at line 54 of file TimeDisplayWidget.h.
Constructor & Destructor Documentation
TimeDisplayWidget()
lmms::gui::TimeDisplayWidget::TimeDisplayWidget ()
Definition at line 37 of file TimeDisplayWidget.cpp.
References lmms::gui::getGUI(), m_displayMode, m_majorLCD, m_milliSecondsLCD, m_minorLCD, m_spinBoxesLayout, setDisplayMode(), and updateTime().
~TimeDisplayWidget()
lmms::gui::TimeDisplayWidget::~TimeDisplayWidget () override default
Member Function Documentation
mousePressEvent()
void lmms::gui::TimeDisplayWidget::mousePressEvent (QMouseEvent * mouseEvent) override protected
Definition at line 119 of file TimeDisplayWidget.cpp.
References BarsTicks, m_displayMode, MinutesSeconds, and setDisplayMode().
setDisplayMode()
void lmms::gui::TimeDisplayWidget::setDisplayMode (DisplayMode displayMode) private
Definition at line 62 of file TimeDisplayWidget.cpp.
References BarsTicks, m_displayMode, m_majorLCD, m_milliSecondsLCD, m_minorLCD, and MinutesSeconds.
Referenced by TimeDisplayWidget(), and mousePressEvent().
updateTime
void lmms::gui::TimeDisplayWidget::updateTime () private slot
Definition at line 87 of file TimeDisplayWidget.cpp.
References BarsTicks, lmms::Song::getMilliseconds(), lmms::Song::getPlayPos(), lmms::Engine::getSong(), lmms::TimePos::getTicks(), lmms::Song::getTimeSigModel(), m_displayMode, m_majorLCD, m_milliSecondsLCD, m_minorLCD, MinutesSeconds, and lmms::Song::ticksPerBar().
Referenced by TimeDisplayWidget().
Member Data Documentation
m_displayMode
DisplayMode lmms::gui::TimeDisplayWidget::m_displayMode private
Definition at line 62 of file TimeDisplayWidget.h.
Referenced by TimeDisplayWidget(), mousePressEvent(), setDisplayMode(), and updateTime().
m_majorLCD
LcdWidget lmms::gui::TimeDisplayWidget::m_majorLCD private
Definition at line 64 of file TimeDisplayWidget.h.
Referenced by TimeDisplayWidget(), setDisplayMode(), and updateTime().
m_milliSecondsLCD
LcdWidget lmms::gui::TimeDisplayWidget::m_milliSecondsLCD private
Definition at line 66 of file TimeDisplayWidget.h.
Referenced by TimeDisplayWidget(), setDisplayMode(), and updateTime().
m_minorLCD
LcdWidget lmms::gui::TimeDisplayWidget::m_minorLCD private
Definition at line 65 of file TimeDisplayWidget.h.
Referenced by TimeDisplayWidget(), setDisplayMode(), and updateTime().
m_spinBoxesLayout
QHBoxLayout lmms::gui::TimeDisplayWidget::m_spinBoxesLayout private
Definition at line 63 of file TimeDisplayWidget.h.
Referenced by TimeDisplayWidget().
The documentation for this class was generated from the following files:
include/TimeDisplayWidget.h
src/gui/widgets/TimeDisplayWidget.cpp