LMMS: lmms::Song Class Reference
lmms::Song Class Reference
#include <Song.h>
Classes
class PlayPos
struct SaveOptions
Public Types
enum class PlayMode {
None ,
Song ,
Pattern ,
MidiClip ,
AutomationClip ,
Count
}
Public Types inherited from lmms::TrackContainer
using TrackList = std::vector<Track*>
enum class Type {
Pattern ,
Song
}
Public Slots
void addPatternTrack ()
void clearProject ()
void playAndRecord ()
void playMidiClip (const lmms::MidiClip *midiClipToPlay, bool loop=true)
void playPattern ()
void playSong ()
void record ()
void setModified ()
void startExport ()
void stop ()
void stopExport ()
void togglePause ()
Signals
void controllerAdded (lmms::Controller *)
void controllerRemoved (lmms::Controller *)
void keymapListChanged (int index)
void lengthChanged (int bars)
void modified ()
void playbackPositionChanged ()
void playbackStateChanged ()
void projectFileNameChanged ()
void projectLoaded ()
void scaleListChanged (int index)
void stopped ()
void tempoChanged (lmms::bpm_t newBPM)
void timeSignatureChanged (int oldTicksPerBar, int ticksPerBar)
void updateSampleTracks ()
Signals inherited from lmms::TrackContainer
void trackAdded (lmms::Track *_track)
Signals inherited from lmms::Model
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
void addController (Controller *c)
AutomatedValueMap automatedValuesAt (TimePos time, int clipNum=-1) const override
void clearErrors ()
void collectError (const QString error)
const ControllerVector & controllers () const
void createNewProject ()
void createNewProjectFromTemplate (const QString &templ)
QString errorSummary ()
void exportProjectMidi (QString const &exportFileName) const
virtual bool fixedClips () const
int getBars () const
int getBeat () const
int getBeatTicks () const
int getExportProgress () const
f_cnt_t getFrames () const
std::shared_ptr< const Keymap > getKeymap (unsigned int index) const
int getLoadingTrackCount () const
int getLoopRenderCount () const
int getMilliseconds () const
int getMilliseconds (PlayMode playMode) const
PlayPos & getPlayPos ()
const PlayPos & getPlayPos () const
PlayPos & getPlayPos (PlayMode pm)
const PlayPos & getPlayPos (PlayMode pm) const
SaveOptions & getSaveOptions ()
std::shared_ptr< const Scale > getScale (unsigned int index) const
bpm_t getTempo ()
int getTicks () const
auto getTimeline () -> Timeline &
auto getTimeline () const -> const Timeline &
auto getTimeline (PlayMode mode) -> Timeline &
auto getTimeline (PlayMode mode) const -> const Timeline &
MeterModel & getTimeSigModel ()
AutomationTrack * globalAutomationTrack ()
bool guiSaveProject ()
bool guiSaveProjectAs (const QString &filename)
bool hasErrors ()
bool isCancelled ()
bool isExportDone () const
bool isExporting () const
bool isLoadingProject () const
bool isModified () const
bool isPaused () const
bool isPlaying () const
bool isRecording () const
bool isSavingProject () const
bool isStopped () const
bar_t length () const
void loadingCancelled ()
void loadProject (const QString &filename)
Metronome & metronome ()
QString nodeName () const override
PlayMode playMode () const
void processNextBuffer ()
const QString & projectFileName () const
void removeController (Controller *c)
bool saveProjectFile (const QString &filename, bool withResources=false)
void setExportLoop (bool exportLoop)
void setKeymap (unsigned int index, std::shared_ptr< Keymap > newMap)
void setLoadOnLaunch (bool value)
void setLoopRenderCount (int count)
void setRenderBetweenMarkers (bool renderBetweenMarkers)
void setScale (unsigned int index, std::shared_ptr< Scale > newScale)
void setToTime (TimePos const &pos)
void setToTime (TimePos const &pos, PlayMode playMode)
void setToTimeByTicks (tick_t ticks)
void setToTimeByTicks (tick_t ticks, PlayMode playMode)
const std::string & syncKey () const noexcept
IntModel & tempoModel ()
int ticksPerBar () const
void updateLength ()
Public Member Functions inherited from lmms::TrackContainer
TrackContainer ()
~TrackContainer () override
void addTrack (Track *_track)
void clearAllTracks ()
int countTracks (Track::Type _tt=Track::Type::Count) const
bool isEmpty () const
void loadSettings (const QDomElement &_this) override
void removeTrack (Track *_track)
void saveSettings (QDomDocument &_doc, QDomElement &_parent) override
void setType (Type newType)
const TrackList & tracks () const
Type type () const
virtual void updateAfterTrackAdd ()
Public Member Functions inherited from lmms::Model
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Public Member Functions inherited from lmms::JournallingObject
JournallingObject ()
~JournallingObject () override
void addJournalCheckPoint ()
jo_id_t id () const
bool isJournalling () const
bool isJournallingStateStackEmpty () const
void restoreJournallingState ()
void restoreState (const QDomElement &_this) override
void saveJournallingState (const bool newState)
QDomElement saveState (QDomDocument &_doc, QDomElement &_parent) override
void setJournalling (const bool _sr)
bool testAndSetJournalling (const bool newState)
Public Member Functions inherited from lmms::SerializingObject
SerializingObject ()
virtual ~SerializingObject ()
SerializingObjectHook * hook ()
void setHook (SerializingObjectHook *_hook)
Static Public Attributes
static constexpr auto PlayModeCount = static_cast<std::size_t>(PlayMode::Count)
Private Slots
void addAutomationTrack ()
void addSampleTrack ()
void insertBar ()
void masterVolumeChanged ()
void removeBar ()
void savePlayStartPosition ()
void setTempo ()
void setTimeSignature ()
void updateFramesPerTick ()
Private Member Functions
Song ()
Song (const Song &)
~Song () override
bar_t currentBar () const
f_cnt_t currentFrame () const
tick_t currentTick () const
mapPropertyFromModel (int, getTempo, setTempo, m_tempoModel)
mapPropertyFromModel (int, masterPitch, setMasterPitch, m_masterPitchModel)
mapPropertyFromModel (int, masterVolume, setMasterVolume, m_masterVolumeModel)
void processAutomations (const TrackList &tracks, TimePos timeStart, fpp_t frames)
void processMetronome (size_t bufferOffset)
void removeAllControllers ()
void restoreControllerStates (const QDomElement &element)
void restoreKeymapStates (const QDomElement &element)
void restoreScaleStates (const QDomElement &element)
void saveControllerStates (QDomDocument &doc, QDomElement &element)
void saveKeymapStates (QDomDocument &doc, QDomElement &element)
void saveScaleStates (QDomDocument &doc, QDomElement &element)
void setModified (bool value)
void setPlayPos (tick_t ticks, PlayMode playMode)
void setProjectFileName (QString const &projectFileName)
Private Attributes
ControllerVector m_controllers
bar_t m_elapsedBars
double m_elapsedMilliSeconds [PlayModeCount]
tick_t m_elapsedTicks
QHash< QString, int > m_errors
TimePos m_exportEffectiveLength
volatile bool m_exporting
volatile bool m_exportLoop
TimePos m_exportLoopBegin
TimePos m_exportLoopEnd
TimePos m_exportSongBegin
TimePos m_exportSongEnd
QString m_fileName
AutomationTrack * m_globalAutomationTrack
bool m_isCancelled
std::shared_ptr< Keymap > m_keymaps [MaxKeymapCount]
bar_t m_length
bool m_loadingProject
bool m_loadOnLaunch
bool m_loopMidiClip
int m_loopRenderCount
int m_loopRenderRemaining
IntModel m_masterPitchModel
IntModel m_masterVolumeModel
Metronome m_metronome
const MidiClip * m_midiClipToPlay
bool m_modified
int m_nLoadingTrack
AutomatedValueMap m_oldAutomatedValues
QString m_oldFileName
int m_oldTicksPerBar
volatile bool m_paused
volatile bool m_playing
PlayMode m_playMode
PlayPos m_playPos [PlayModeCount]
volatile bool m_recording
volatile bool m_renderBetweenMarkers
SaveOptions m_saveOptions
bool m_savingProject
std::shared_ptr< Scale > m_scales [MaxScaleCount]
IntModel m_tempoModel
std::array< Timeline, PlayModeCount > m_timelines
MeterModel m_timeSigModel
VstSyncController m_vstSyncController
Friends
class Engine
class gui::ControllerRackView
class gui::SongEditor
Additional Inherited Members
Static Public Member Functions inherited from lmms::TrackContainer
static const QString classNodeName ()
Protected Member Functions inherited from lmms::JournallingObject
void changeID (jo_id_t _id)
Static Protected Member Functions inherited from lmms::TrackContainer
static AutomatedValueMap automatedValuesFromTracks (const TrackList &tracks, TimePos timeStart, int clipNum=-1)
Protected Attributes inherited from lmms::TrackContainer
QReadWriteLock m_tracksMutex
Detailed Description
Definition at line 64 of file Song.h.
Member Enumeration Documentation
PlayMode
enum class lmms::Song::PlayMode strong
Enumerator
None
Song
Pattern
MidiClip
AutomationClip
Count
Definition at line 71 of file Song.h.
Constructor & Destructor Documentation
Song() [1/2]
lmms::Song::Song () private
Definition at line 67 of file Song.cpp.
References lmms::TrackContainer::TrackContainer(), lmms::Engine::audioEngine(), lmms::Model::dataChanged(), lmms::Model::dataUnchanged(), lmms::DefaultTempo, lmms::DefaultTicksPerBar, m_elapsedBars, m_elapsedMilliSeconds, m_elapsedTicks, m_exporting, m_exportLoop, m_fileName, m_globalAutomationTrack, m_isCancelled, m_keymaps, m_length, m_loadingProject, m_loadOnLaunch, m_loopMidiClip, m_loopRenderCount, m_loopRenderRemaining, m_masterPitchModel, m_masterVolumeModel, m_midiClipToPlay, m_modified, m_nLoadingTrack, m_oldAutomatedValues, m_oldFileName, m_oldTicksPerBar, m_paused, m_playing, m_playMode, m_recording, m_renderBetweenMarkers, m_savingProject, m_scales, m_tempoModel, m_timeSigModel, masterVolumeChanged(), lmms::MaxTempo, lmms::MinTempo, None, setTempo(), setTimeSignature(), lmms::TrackContainer::setType(), lmms::TrackContainer::Song, lmms::TrackContainer::Track, and updateFramesPerTick().
Referenced by Song, and Song().
Song() [2/2]
lmms::Song::Song (const Song &) private
References Song().
~Song()
lmms::Song::~Song () override private
Definition at line 128 of file Song.cpp.
References m_globalAutomationTrack, and m_playing.
Member Function Documentation
addAutomationTrack
void lmms::Song::addAutomationTrack () private slot
Definition at line 838 of file Song.cpp.
References lmms::Track::Automation, and lmms::Track::create().
addController()
void lmms::Song::addController (Controller * c)
Definition at line 1447 of file Song.cpp.
References controllerAdded(), m_controllers, and setModified().
Referenced by lmms::gui::ControllerRackView::addController(), and restoreControllerStates().
addPatternTrack
void lmms::Song::addPatternTrack () slot
Definition at line 821 of file Song.cpp.
References lmms::Track::create(), lmms::Track::Pattern, lmms::Engine::patternStore(), and lmms::TrackContainer::Track.
Referenced by lmms::PatternStore::updateAfterTrackAdd().
addSampleTrack
void lmms::Song::addSampleTrack () private slot
Definition at line 830 of file Song.cpp.
References lmms::Track::create(), and lmms::Track::Sample.
automatedValuesAt()
AutomatedValueMap lmms::Song::automatedValuesAt (TimePos time, int clipNum = -1) const override virtual
Reimplemented from lmms::TrackContainer.
Definition at line 852 of file Song.cpp.
References lmms::TrackContainer::automatedValuesFromTracks(), m_globalAutomationTrack, and lmms::TrackContainer::tracks().
clearErrors()
void lmms::Song::clearErrors ()
Definition at line 1479 of file Song.cpp.
References m_errors.
Referenced by loadProject().
clearProject
void lmms::Song::clearProject () slot
Definition at line 862 of file Song.cpp.
References lmms::Engine::audioEngine(), lmms::gui::GuiApplication::automationEditor(), lmms::AutomationClip::clear(), lmms::gui::MixerView::clear(), lmms::gui::ProjectNotes::clear(), lmms::Mixer::clear(), lmms::gui::TrackContainerView::clearAllTracks(), lmms::TrackContainer::clearAllTracks(), lmms::ProjectJournal::clearJournal(), lmms::Model::dataChanged(), lmms::AudioEngine::doneChangeInModel(), lmms::gui::getGUI(), lmms::gui::GuiApplication::getProjectNotes(), lmms::AutomationClip::globalAutomationClip(), i, lmms::gui::PatternEditorWindow::m_editor, lmms::gui::SongEditorWindow::m_editor, m_masterPitchModel, m_masterVolumeModel, m_oldAutomatedValues, m_playing, m_tempoModel, m_timeSigModel, lmms::Engine::mixer(), lmms::gui::GuiApplication::mixerView(), lmms::gui::GuiApplication::patternEditor(), lmms::Engine::patternStore(), lmms::gui::GuiApplication::pianoRoll(), PlayModeCount, lmms::Engine::projectJournal(), removeAllControllers(), lmms::AudioEngine::requestChangeInModel(), lmms::gui::PianoRollWindow::reset(), lmms::gui::AutomationEditorWindow::setCurrentClip(), lmms::ProjectJournal::setJournalling(), setPlayPos(), lmms::gui::GuiApplication::songEditor(), and stop().
Referenced by createNewProject(), and loadProject().
collectError()
void lmms::Song::collectError (const QString error)
Definition at line 1486 of file Song.cpp.
References m_errors.
Referenced by lmms::Plugin::collectErrorForUI(), lmms::EnvelopeAndLfoParameters::loadSettings(), lmms::LfoController::loadSettings(), and lmms::SampleClip::loadSettings().
controllerAdded
void lmms::Song::controllerAdded (lmms::Controller *) signal
Referenced by lmms::gui::ControllerRackView::ControllerRackView(), and addController().
controllerRemoved
void lmms::Song::controllerRemoved (lmms::Controller *) signal
Referenced by lmms::gui::ControllerRackView::ControllerRackView(), and removeController().
controllers()
const ControllerVector & lmms::Song::controllers () const inline
Definition at line 344 of file Song.h.
References m_controllers.
Referenced by lmms::gui::ControllerConnectionDialog::ControllerConnectionDialog(), lmms::ControllerConnection::saveSettings(), and lmms::gui::ControllerConnectionDialog::selectController().
createNewProject()
void lmms::Song::createNewProject ()
Definition at line 943 of file Song.cpp.
References lmms::Track::Automation, clearProject(), lmms::Track::create(), createNewProjectFromTemplate(), lmms::DefaultTempo, lmms::ConfigManager::factoryProjectsDir(), lmms::ConfigManager::inst(), lmms::Track::Instrument, m_loadingProject, m_loadOnLaunch, m_masterPitchModel, m_masterVolumeModel, m_oldFileName, m_tempoModel, m_timeSigModel, lmms::Track::Pattern, lmms::Engine::patternStore(), lmms::Engine::projectJournal(), lmms::Track::Sample, lmms::ProjectJournal::setJournalling(), setModified(), setProjectFileName(), lmms::PatternStore::updateAfterTrackAdd(), updateLength(), and lmms::ConfigManager::userTemplateDir().
Referenced by lmms::gui::MainWindow::createNewProject(), and loadProject().
createNewProjectFromTemplate()
void lmms::Song::createNewProjectFromTemplate (const QString & templ)
Definition at line 1005 of file Song.cpp.
References loadProject(), m_loadOnLaunch, m_oldFileName, and setProjectFileName().
Referenced by createNewProject(), and lmms::gui::TemplatesMenu::createNewProjectFromTemplate().
currentBar()
bar_t lmms::Song::currentBar () const inline private
Definition at line 421 of file Song.h.
References getPlayPos(), and m_playMode.
Referenced by getBars().
currentFrame()
f_cnt_t lmms::Song::currentFrame () const inline private
Definition at line 431 of file Song.h.
References lmms::Engine::framesPerTick(), getPlayPos(), and m_playMode.
Referenced by getFrames(), processNextBuffer(), and stop().
currentTick()
tick_t lmms::Song::currentTick () const inline private
Definition at line 426 of file Song.h.
References getPlayPos(), and m_playMode.
Referenced by getTicks(), and processMetronome().
errorSummary()
QString lmms::Song::errorSummary ()
Definition at line 1501 of file Song.cpp.
References i, and m_errors.
Referenced by loadProject().
exportProjectMidi()
void lmms::Song::exportProjectMidi (QString const & exportFileName) const
Definition at line 1402 of file Song.cpp.
References getTempo(), lmms::Plugin::instantiate(), m_masterPitchModel, lmms::Engine::patternStore(), lmms::TrackContainer::tracks(), and lmms::ExportFilter::tryExport().
Referenced by lmms::gui::MainWindow::onExportProjectMidi().
fixedClips()
virtual bool lmms::Song::fixedClips () const inline virtual
Definition at line 335 of file Song.h.
getBars()
int lmms::Song::getBars () const inline
Definition at line 172 of file Song.h.
References currentBar().
getBeat()
int lmms::Song::getBeat () const inline
Definition at line 183 of file Song.h.
References getPlayPos(), and m_timeSigModel.
getBeatTicks()
int lmms::Song::getBeatTicks () const inline
Definition at line 188 of file Song.h.
References getPlayPos(), and m_timeSigModel.
getExportProgress()
int lmms::Song::getExportProgress () const
Definition at line 462 of file Song.cpp.
References getPlayPos(), m_exportEffectiveLength, m_exportLoopBegin, m_exportLoopEnd, m_exportSongBegin, m_exportSongEnd, m_loopRenderCount, m_loopRenderRemaining, and pos.
Referenced by lmms::ProjectRenderer::run().
getFrames()
f_cnt_t lmms::Song::getFrames () const inline
Definition at line 196 of file Song.h.
References currentFrame().
Referenced by lmms::LfoController::updatePhase().
getKeymap()
std::shared_ptr< const Keymap > lmms::Song::getKeymap (unsigned int index) const
Definition at line 1536 of file Song.cpp.
References m_keymaps, and lmms::MaxKeymapCount.
Referenced by lmms::InstrumentTrack::baseFreq(), lmms::InstrumentTrack::baseNote(), lmms::InstrumentTrack::firstKey(), lmms::InstrumentTrack::isKeyMapped(), lmms::Microtuner::keyToFreq(), lmms::InstrumentTrack::lastKey(), lmms::Microtuner::octaveSize(), lmms::gui::MicrotunerConfig::saveKeymapToFile(), and lmms::gui::MicrotunerConfig::updateKeymapForm().
getLoadingTrackCount()
int lmms::Song::getLoadingTrackCount () const inline
Definition at line 135 of file Song.h.
References m_nLoadingTrack.
getLoopRenderCount()
int lmms::Song::getLoopRenderCount () const inline
Definition at line 239 of file Song.h.
References m_loopRenderCount.
getMilliseconds() [1/2]
int lmms::Song::getMilliseconds () const inline
Definition at line 140 of file Song.h.
References getMilliseconds(), and m_playMode.
Referenced by getMilliseconds(), and lmms::gui::TimeDisplayWidget::updateTime().
getMilliseconds() [2/2]
int lmms::Song::getMilliseconds (PlayMode playMode) const inline
Definition at line 145 of file Song.h.
References m_elapsedMilliSeconds, and playMode().
getPlayPos() [1/4]
PlayPos & lmms::Song::getPlayPos () inline
Definition at line 265 of file Song.h.
References getPlayPos(), and m_playMode.
Referenced by getExportProgress(), insertBar(), isExportDone(), processNextBuffer(), removeBar(), savePlayStartPosition(), setPlayPos(), startExport(), and stop().
getPlayPos() [2/4]
const PlayPos & lmms::Song::getPlayPos () const inline
Definition at line 269 of file Song.h.
References getPlayPos(), and m_playMode.
getPlayPos() [3/4]
PlayPos & lmms::Song::getPlayPos (PlayMode pm) inline
Definition at line 257 of file Song.h.
References m_playPos.
Referenced by currentBar(), currentFrame(), currentTick(), getBeat(), getBeatTicks(), getPlayPos(), getPlayPos(), lmms::gui::MidiClipView::paintEvent(), lmms::gui::PianoRoll::setCurrentMidiClip(), setToTime(), setToTimeByTicks(), lmms::gui::PianoRoll::updatePositionAccompany(), and lmms::gui::TimeDisplayWidget::updateTime().
getPlayPos() [4/4]
const PlayPos & lmms::Song::getPlayPos (PlayMode pm) const inline
Definition at line 261 of file Song.h.
References m_playPos.
getSaveOptions()
SaveOptions & lmms::Song::getSaveOptions () inline
Definition at line 363 of file Song.h.
References m_saveOptions.
Referenced by lmms::AutomatableModel::saveSettings().
getScale()
std::shared_ptr< const Scale > lmms::Song::getScale (unsigned int index) const
Definition at line 1528 of file Song.cpp.
References m_scales, and lmms::MaxScaleCount.
Referenced by lmms::Microtuner::keyToFreq(), lmms::Microtuner::octaveSize(), lmms::gui::MicrotunerConfig::saveScaleToFile(), and lmms::gui::MicrotunerConfig::updateScaleForm().
getTempo()
bpm_t lmms::Song::getTempo ()
Definition at line 846 of file Song.cpp.
References m_tempoModel.
Referenced by lmms::gui::TempoSyncBarModelEditor::contextMenuEvent(), lmms::gui::TempoSyncKnob::contextMenuEvent(), exportProjectMidi(), mapPropertyFromModel(), processNextBuffer(), setPlayPos(), setToTime(), and setToTimeByTicks().
getTicks()
int lmms::Song::getTicks () const inline
Definition at line 192 of file Song.h.
References currentTick().
Referenced by processNextBuffer(), and stop().
getTimeline() [1/4]
auto lmms::Song::getTimeline () ->Timeline & inline
Definition at line 276 of file Song.h.
References getTimeline(), and m_playMode.
Referenced by getTimeline().
getTimeline() [2/4]
auto lmms::Song::getTimeline () const->constTimeline & inline
Definition at line 277 of file Song.h.
References getTimeline(), and m_playMode.
Referenced by getTimeline().
getTimeline() [3/4]
auto lmms::Song::getTimeline (PlayMode mode) ->Timeline & inline
Definition at line 274 of file Song.h.
References m_timelines.
Referenced by loadProject(), lmms::gui::PianoRollWindow::loadSettings(), processNextBuffer(), savePlayStartPosition(), saveProjectFile(), startExport(), and stop().
getTimeline() [4/4]
auto lmms::Song::getTimeline (PlayMode mode) const->constTimeline & inline
Definition at line 275 of file Song.h.
References m_timelines.
getTimeSigModel()
MeterModel & lmms::Song::getTimeSigModel () inline
Definition at line 350 of file Song.h.
References m_timeSigModel.
Referenced by lmms::gui::AutomationEditor::paintEvent(), lmms::gui::PianoRoll::paintEvent(), lmms::gui::SampleClipView::paintEvent(), lmms::SampleClip::setSampleFile(), setTimeSignature(), and lmms::gui::TimeDisplayWidget::updateTime().
globalAutomationTrack()
AutomationTrack * lmms::Song::globalAutomationTrack () inline
Definition at line 288 of file Song.h.
References m_globalAutomationTrack.
Referenced by lmms::AutomationClip::globalAutomationClip().
guiSaveProject()
bool lmms::Song::guiSaveProject ()
Definition at line 1272 of file Song.cpp.
References guiSaveProjectAs(), and m_fileName.
Referenced by lmms::gui::MainWindow::guiSaveProject().
guiSaveProjectAs()
bool lmms::Song::guiSaveProjectAs (const QString & filename)
Definition at line 1281 of file Song.cpp.
References m_saveOptions, lmms::DataFile::nameWithExtension(), saveProjectFile(), setModified(), setProjectFileName(), and lmms::DataFile::SongProject.
Referenced by guiSaveProject(), and lmms::gui::MainWindow::guiSaveProjectAs().
hasErrors()
bool lmms::Song::hasErrors ()
Definition at line 1494 of file Song.cpp.
References m_errors.
Referenced by loadProject().
insertBar
void lmms::Song::insertBar () private slot
Definition at line 791 of file Song.cpp.
References Song, getPlayPos(), lmms::TrackContainer::m_tracksMutex, lmms::TrackContainer::Track, and lmms::TrackContainer::tracks().
isCancelled()
bool lmms::Song::isCancelled () inline
Definition at line 320 of file Song.h.
References m_isCancelled.
Referenced by loadProject(), restoreControllerStates(), restoreKeymapStates(), and restoreScaleStates().
isExportDone()
bool lmms::Song::isExportDone () const
Definition at line 457 of file Song.cpp.
References getPlayPos(), isExporting(), and m_exportSongEnd.
isExporting()
bool lmms::Song::isExporting () const inline
Definition at line 215 of file Song.h.
References m_exporting.
Referenced by lmms::AudioEngine::criticalXRuns(), and isExportDone().
isLoadingProject()
bool lmms::Song::isLoadingProject () const inline
Definition at line 309 of file Song.h.
References m_loadingProject.
isModified()
bool lmms::Song::isModified () const inline
Definition at line 325 of file Song.h.
References m_modified.
isPaused()
bool lmms::Song::isPaused () const inline
Definition at line 200 of file Song.h.
References m_paused.
isPlaying()
bool lmms::Song::isPlaying () const inline
Definition at line 205 of file Song.h.
References m_exporting, and m_playing.
Referenced by setPlayPos().
isRecording()
bool lmms::Song::isRecording () const inline
Definition at line 225 of file Song.h.
References m_recording.
isSavingProject()
bool lmms::Song::isSavingProject () const
Definition at line 1523 of file Song.cpp.
References m_savingProject.
Referenced by lmms::AutomatableModel::saveSettings().
isStopped()
bool lmms::Song::isStopped () const inline
Definition at line 210 of file Song.h.
References m_paused, and m_playing.
Referenced by playMidiClip(), playPattern(), and playSong().
keymapListChanged
void lmms::Song::keymapListChanged (int index) signal
Referenced by restoreKeymapStates(), and setKeymap().
length()
bar_t lmms::Song::length () const inline
Definition at line 280 of file Song.h.
References m_length.
Referenced by processAutomations().
lengthChanged
void lmms::Song::lengthChanged (int bars) signal
Referenced by updateLength().
loadingCancelled()
void lmms::Song::loadingCancelled () inline
Definition at line 314 of file Song.h.
References lmms::Engine::audioEngine(), and m_isCancelled.
Referenced by lmms::TrackContainer::loadSettings().
loadProject()
void lmms::Song::loadProject (const QString & filename)
Definition at line 1020 of file Song.cpp.
References Song, lmms::ConfigManager::addRecentlyOpenedProject(), lmms::Engine::audioEngine(), lmms::gui::GuiApplication::automationEditor(), clearErrors(), clearProject(), lmms::DataFile::content(), createNewProject(), lmms::AudioEngine::doneChangeInModel(), errorSummary(), lmms::ControllerConnection::finalizeConnections(), lmms::PatternStore::fixIncorrectPositions(), lmms::gui::GuiApplication::getControllerRackView(), lmms::gui::getGUI(), lmms::gui::GuiApplication::getProjectNotes(), lmms::Engine::getSong(), getTimeline(), hasErrors(), lmms::DataFile::hasLocalPlugins(), lmms::DataFile::head(), i, lmms::PeakController::initGetControllerBySetting(), lmms::ConfigManager::inst(), isCancelled(), m_controllers, lmms::gui::AutomationEditorWindow::m_editor, m_fileName, m_isCancelled, m_loadingProject, m_loadOnLaunch, m_masterPitchModel, m_masterVolumeModel, m_nLoadingTrack, m_oldFileName, m_tempoModel, m_timeSigModel, lmms::Engine::mixer(), lmms::gui::GuiApplication::mixerView(), nodeName(), lmms::Track::Pattern, lmms::Engine::patternStore(), lmms::gui::GuiApplication::pianoRoll(), lmms::Engine::projectJournal(), projectLoaded(), lmms::gui::MixerView::refreshDisplay(), lmms::AudioEngine::requestChangeInModel(), lmms::AutomationClip::resolveAllIDs(), restoreControllerStates(), restoreKeymapStates(), restoreScaleStates(), lmms::gui::PianoRollWindow::restoreState(), lmms::JournallingObject::restoreState(), lmms::SerializingObject::restoreState(), lmms::ProjectJournal::setJournalling(), setModified(), setProjectFileName(), and updateLength().
Referenced by createNewProjectFromTemplate(), lmms::gui::TrackContainerView::dropEvent(), lmms::gui::MainApplication::event(), lmms::gui::FileBrowserTreeWidget::handleFile(), lmms::gui::MainWindow::openProject(), and lmms::gui::RecentProjectsMenu::openProject().
mapPropertyFromModel() [1/3]
lmms::Song::mapPropertyFromModel (int , getTempo , setTempo , m_tempoModel) private
References getTempo(), m_tempoModel, and setTempo().
mapPropertyFromModel() [2/3]
lmms::Song::mapPropertyFromModel (int , masterPitch , setMasterPitch , m_masterPitchModel) private
References m_masterPitchModel.
mapPropertyFromModel() [3/3]
lmms::Song::mapPropertyFromModel (int , masterVolume , setMasterVolume , m_masterVolumeModel) private
References m_masterVolumeModel.
masterVolumeChanged
void lmms::Song::masterVolumeChanged () private slot
Definition at line 137 of file Song.cpp.
References lmms::Engine::audioEngine(), m_masterVolumeModel, and lmms::AudioEngine::setMasterGain().
Referenced by Song().
metronome()
Metronome & lmms::Song::metronome () inline
Definition at line 376 of file Song.h.
References m_metronome.
Referenced by lmms::gui::MainWindow::onToggleMetronome().
modified
void lmms::Song::modified () signal
Referenced by setModified().
nodeName()
QString lmms::Song::nodeName () const inline override virtual
Implements lmms::SerializingObject.
Definition at line 330 of file Song.h.
Referenced by loadProject().
playAndRecord
void lmms::Song::playAndRecord () slot
Definition at line 524 of file Song.cpp.
References m_recording, and playSong().
playbackPositionChanged
void lmms::Song::playbackPositionChanged () signal
Referenced by setPlayPos().
playbackStateChanged
void lmms::Song::playbackStateChanged () signal
Referenced by playMidiClip(), playPattern(), playSong(), stop(), and togglePause().
playMidiClip
void lmms::Song::playMidiClip (const lmms::MidiClip * midiClipToPlay, bool loop = true) slot
Definition at line 554 of file Song.cpp.
References isStopped(), m_loopMidiClip, m_midiClipToPlay, m_paused, m_playing, m_playMode, MidiClip, playbackStateChanged(), savePlayStartPosition(), and stop().
Referenced by lmms::gui::AutomationEditor::play(), lmms::gui::PianoRoll::play(), lmms::gui::PianoRoll::record(), and lmms::gui::PianoRoll::setCurrentMidiClip().
playMode()
PlayMode lmms::Song::playMode () const inline
Definition at line 252 of file Song.h.
References m_playMode.
Referenced by getMilliseconds(), lmms::gui::MidiClipView::paintEvent(), processMetronome(), setPlayPos(), setToTime(), setToTimeByTicks(), and lmms::gui::PianoRoll::updatePositionAccompany().
playPattern
void lmms::Song::playPattern () slot
Definition at line 533 of file Song.cpp.
References isStopped(), m_paused, m_playing, m_playMode, m_vstSyncController, Pattern, playbackStateChanged(), savePlayStartPosition(), and stop().
Referenced by lmms::gui::PatternEditorWindow::play(), lmms::PatternStore::play(), and lmms::gui::PianoRoll::recordAccompany().
playSong
void lmms::Song::playSong () slot
Definition at line 492 of file Song.cpp.
References Song, isStopped(), m_paused, m_playing, m_playMode, m_recording, m_vstSyncController, playbackStateChanged(), savePlayStartPosition(), and stop().
Referenced by lmms::gui::AutomationEditor::play(), lmms::gui::SongEditorWindow::play(), playAndRecord(), lmms::gui::PianoRoll::recordAccompany(), and startExport().
processAutomations()
void lmms::Song::processAutomations (const TrackList & tracks, TimePos timeStart, fpp_t frames) private
Definition at line 353 of file Song.cpp.
References Song, lmms::TrackContainer::TrackContainer(), lmms::TrackContainer::automatedValuesAt(), lmms::Track::Automation, lmms::AutomatableModel::controllerConnection(), lmms::AutomatableModel::inverseScaledValue(), length(), m_oldAutomatedValues, m_playMode, Pattern, lmms::Track::Pattern, lmms::Engine::patternStore(), lmms::AutomatableModel::setUseControllerValue(), lmms::TrackContainer::Track, lmms::TrackContainer::tracks(), and lmms::AutomatableModel::value().
Referenced by processNextBuffer().
processMetronome()
void lmms::Song::processMetronome (size_t bufferOffset) private
Definition at line 437 of file Song.cpp.
References Song, currentTick(), m_exporting, m_metronome, m_timeSigModel, MidiClip, Pattern, playMode(), and ticksPerBar().
Referenced by processNextBuffer().
processNextBuffer()
void lmms::Song::processNextBuffer ()
Definition at line 194 of file Song.cpp.
References Song, lmms::Engine::audioEngine(), currentFrame(), lmms::Song::PlayPos::currentFrame(), lmms::PatternTrack::findPatternTrack(), lmms::AudioEngine::framesPerPeriod(), lmms::Engine::framesPerTick(), lmms::TimePos::getBar(), getPlayPos(), getTempo(), getTicks(), lmms::TimePos::getTicks(), getTimeline(), lmms::EnvelopeAndLfoParameters::instances(), lmms::PatternStore::lengthOfCurrentPattern(), m_elapsedBars, m_elapsedMilliSeconds, m_elapsedTicks, m_exporting, m_loopMidiClip, m_loopRenderRemaining, m_midiClipToPlay, m_playing, m_playMode, m_vstSyncController, MidiClip, Pattern, lmms::Engine::patternStore(), processAutomations(), processMetronome(), lmms::EnvelopeAndLfoParameters::LfoInstances::reset(), lmms::Song::PlayPos::setCurrentFrame(), lmms::Song::PlayPos::setJumped(), lmms::TimePos::setTicks(), setToTime(), ticksPerBar(), lmms::TimePos::ticksToMilliseconds(), lmms::TrackContainer::tracks(), and updateSampleTracks().
Referenced by lmms::AudioEngine::renderStageNoteSetup().
projectFileName()
const QString & lmms::Song::projectFileName () const inline
Definition at line 304 of file Song.h.
References m_fileName.
Referenced by lmms::PathUtil::baseLocation(), lmms::gui::MainWindow::exportProject(), lmms::gui::MainWindow::guiSaveProject(), lmms::gui::MainWindow::onExportProjectMidi(), lmms::gui::MainWindow::saveProjectAs(), lmms::gui::MainWindow::saveProjectAsNewVersion(), and setProjectFileName().
projectFileNameChanged
void lmms::Song::projectFileNameChanged () signal
Referenced by setProjectFileName().
projectLoaded
void lmms::Song::projectLoaded () signal
Referenced by loadProject().
record
void lmms::Song::record () slot
Definition at line 515 of file Song.cpp.
References m_recording.
removeAllControllers()
void lmms::Song::removeAllControllers () private
Definition at line 1340 of file Song.cpp.
References m_controllers, and removeController().
Referenced by clearProject().
removeBar
void lmms::Song::removeBar () private slot
Definition at line 806 of file Song.cpp.
References Song, getPlayPos(), lmms::TrackContainer::m_tracksMutex, lmms::TrackContainer::Track, and lmms::TrackContainer::tracks().
removeController()
void lmms::Song::removeController (Controller * c)
Definition at line 1462 of file Song.cpp.
References controllerRemoved(), m_controllers, and setModified().
Referenced by lmms::gui::ControllerRackView::deleteController(), and removeAllControllers().
restoreControllerStates()
void lmms::Song::restoreControllerStates (const QDomElement & element) private
Definition at line 1321 of file Song.cpp.
References addController(), lmms::Controller::create(), lmms::Controller::Dummy, isCancelled(), and m_controllers.
Referenced by loadProject().
restoreKeymapStates()
void lmms::Song::restoreKeymapStates (const QDomElement & element) private
Definition at line 1389 of file Song.cpp.
References i, isCancelled(), keymapListChanged(), m_keymaps, and lmms::MaxKeymapCount.
Referenced by loadProject().
restoreScaleStates()
void lmms::Song::restoreScaleStates (const QDomElement & element) private
Definition at line 1364 of file Song.cpp.
References i, isCancelled(), m_scales, lmms::MaxScaleCount, and scaleListChanged().
Referenced by loadProject().
saveControllerStates()
void lmms::Song::saveControllerStates (QDomDocument & doc, QDomElement & element) private
Definition at line 1307 of file Song.cpp.
References m_controllers.
Referenced by saveProjectFile().
saveKeymapStates()
void lmms::Song::saveKeymapStates (QDomDocument & doc, QDomElement & element) private
Definition at line 1377 of file Song.cpp.
References m_keymaps.
Referenced by saveProjectFile().
savePlayStartPosition
void lmms::Song::savePlayStartPosition () private slot
Definition at line 186 of file Song.cpp.
References getPlayPos(), and getTimeline().
Referenced by playMidiClip(), playPattern(), and playSong().
saveProjectFile()
bool lmms::Song::saveProjectFile (const QString & filename, bool withResources = false)
Definition at line 1235 of file Song.cpp.
References Song, lmms::gui::GuiApplication::automationEditor(), lmms::DataFile::content(), lmms::gui::GuiApplication::getControllerRackView(), lmms::gui::getGUI(), lmms::gui::GuiApplication::getProjectNotes(), getTimeline(), lmms::DataFile::head(), lmms::gui::AutomationEditorWindow::m_editor, m_masterPitchModel, m_masterVolumeModel, m_savingProject, m_tempoModel, m_timeSigModel, lmms::Engine::mixer(), lmms::gui::GuiApplication::pianoRoll(), saveControllerStates(), saveKeymapStates(), saveScaleStates(), lmms::gui::PianoRollWindow::saveState(), lmms::JournallingObject::saveState(), lmms::SerializingObject::saveState(), lmms::DataFile::SongProject, and lmms::DataFile::writeFile().
Referenced by lmms::gui::MainWindow::autoSave(), guiSaveProjectAs(), and lmms::gui::MainWindow::saveProjectAsDefaultTemplate().
saveScaleStates()
void lmms::Song::saveScaleStates (QDomDocument & doc, QDomElement & element) private
Definition at line 1352 of file Song.cpp.
References m_scales.
Referenced by saveProjectFile().
scaleListChanged
void lmms::Song::scaleListChanged (int index) signal
Referenced by restoreScaleStates(), and setScale().
setExportLoop()
void lmms::Song::setExportLoop (bool exportLoop) inline
Definition at line 220 of file Song.h.
References m_exportLoop.
Referenced by lmms::gui::ExportProjectDialog::startExport().
setKeymap()
void lmms::Song::setKeymap (unsigned int index, std::shared_ptr< Keymap > newMap)
Definition at line 1555 of file Song.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), keymapListChanged(), m_keymaps, lmms::MaxKeymapCount, and lmms::AudioEngine::requestChangeInModel().
Referenced by lmms::gui::MicrotunerConfig::applyKeymap().
setLoadOnLaunch()
void lmms::Song::setLoadOnLaunch (bool value) inline
Definition at line 362 of file Song.h.
References m_loadOnLaunch.
Referenced by lmms::gui::MainWindow::onImportProject().
setLoopRenderCount()
void lmms::Song::setLoopRenderCount (int count) inline
Definition at line 230 of file Song.h.
References m_loopRenderCount, and m_loopRenderRemaining.
Referenced by lmms::gui::ExportProjectDialog::closeEvent(), and lmms::gui::ExportProjectDialog::startExport().
setModified [1/2]
void lmms::Song::setModified () slot
Definition at line 1430 of file Song.cpp.
References setModified().
Referenced by addController(), lmms::gui::ProjectNotes::alignmentChanged(), lmms::StepRecorder::applyStep(), lmms::gui::MidiClipView::bulkClearNotesOutOfBounds(), lmms::gui::PianoRoll::constrainNoteLengths(), createNewProject(), lmms::gui::PianoRoll::cutSelectedNotes(), lmms::gui::PianoRoll::deleteSelectedNotes(), lmms::gui::PianoRoll::dragNotes(), lmms::gui::InstrumentTrackWindow::dropEvent(), lmms::gui::AutomationEditor::fineTuneValue(), lmms::gui::PianoRoll::fitNoteLengths(), lmms::gui::ProjectNotes::formatChanged(), guiSaveProjectAs(), loadProject(), lmms::gui::MidiClipView::mergeClips(), lmms::gui::AutomationEditor::mouseMoveEvent(), lmms::gui::PianoRoll::mouseMoveEvent(), lmms::gui::AutomationEditor::mousePressEvent(), lmms::gui::MidiClipView::mousePressEvent(), lmms::gui::PianoRoll::mousePressEvent(), lmms::gui::PianoRoll::pasteNotes(), lmms::gui::PianoRoll::quantizeNotes(), lmms::gui::MixerChannelView::randomizeColor(), lmms::gui::TrackOperationsWidget::randomizeTrackColor(), lmms::ProjectJournal::redo(), lmms::Track::removeClip(), lmms::gui::TrackContentWidget::removeClipView(), removeController(), lmms::TrackContainer::removeTrack(), lmms::gui::TrackContainerView::removeTrackView(), lmms::gui::MixerChannelView::renameFinished(), lmms::InstrumentTrack::replaceInstrument(), lmms::gui::TrackOperationsWidget::resetClipColors(), lmms::gui::MixerChannelView::resetColor(), lmms::gui::TrackOperationsWidget::resetTrackColor(), lmms::gui::PianoRoll::reverseNotes(), lmms::gui::SampleClipView::reverseSample(), lmms::gui::MixerChannelView::selectColor(), lmms::gui::TrackOperationsWidget::selectTrackColor(), lmms::gui::ClipView::setColor(), setModified(), lmms::gui::AutomationEditor::setProgressionType(), lmms::SampleClip::setSampleBuffer(), lmms::TempoSyncKnobModel::setTempoSync(), lmms::gui::ProjectNotes::textBold(), lmms::gui::InstrumentTrackWindow::textChanged(), lmms::gui::SampleTrackWindow::textChanged(), lmms::gui::ProjectNotes::textFamily(), lmms::gui::ProjectNotes::textItalic(), lmms::gui::ProjectNotes::textSize(), lmms::gui::ProjectNotes::textUnderline(), lmms::gui::MidiClipView::transposeSelection(), lmms::ProjectJournal::undo(), lmms::SampleClip::updateLength(), lmms::MidiPort::updateMidiPortMode(), and lmms::gui::MidiClipView::wheelEvent().
setModified() [2/2]
void lmms::Song::setModified (bool value) private
Definition at line 448 of file Song.cpp.
References m_loadingProject, m_modified, and modified().
setPlayPos()
void lmms::Song::setPlayPos (tick_t ticks, PlayMode playMode) private
Definition at line 606 of file Song.cpp.
References getPlayPos(), getTempo(), lmms::TimePos::getTicks(), isPlaying(), m_elapsedMilliSeconds, m_elapsedTicks, playbackPositionChanged(), playMode(), lmms::Song::PlayPos::setCurrentFrame(), lmms::Song::PlayPos::setJumped(), lmms::TimePos::setTicks(), lmms::TimePos::ticksToMilliseconds(), and updateSampleTracks().
Referenced by clearProject().
setProjectFileName()
void lmms::Song::setProjectFileName (QString const & projectFileName) private
Definition at line 1435 of file Song.cpp.
References m_fileName, projectFileName(), and projectFileNameChanged().
Referenced by createNewProject(), createNewProjectFromTemplate(), guiSaveProjectAs(), and loadProject().
setRenderBetweenMarkers()
void lmms::Song::setRenderBetweenMarkers (bool renderBetweenMarkers) inline
Definition at line 247 of file Song.h.
References m_renderBetweenMarkers.
Referenced by lmms::gui::ExportProjectDialog::startExport().
setScale()
void lmms::Song::setScale (unsigned int index, std::shared_ptr< Scale > newScale)
Definition at line 1544 of file Song.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), m_scales, lmms::MaxScaleCount, lmms::AudioEngine::requestChangeInModel(), and scaleListChanged().
Referenced by lmms::gui::MicrotunerConfig::applyScale().
setTempo
void lmms::Song::setTempo () private slot
Definition at line 145 of file Song.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::doneChangeInModel(), m_tempoModel, m_vstSyncController, lmms::AudioEngine::playHandles(), lmms::AudioEngine::requestChangeInModel(), tempoChanged(), and lmms::Engine::updateFramesPerTick().
Referenced by Song(), and mapPropertyFromModel().
setTimeSignature
void lmms::Song::setTimeSignature () private slot
Definition at line 172 of file Song.cpp.
References lmms::Model::dataChanged(), getTimeSigModel(), m_oldTicksPerBar, m_vstSyncController, lmms::TimePos::setTicksPerBar(), ticksPerBar(), and timeSignatureChanged().
Referenced by Song().
setToTime() [1/2]
void lmms::Song::setToTime (TimePos const & pos) inline
Definition at line 150 of file Song.h.
References m_playMode, pos, and setToTime().
Referenced by lmms::gui::TimeLineWidget::mouseMoveEvent(), processNextBuffer(), setToTime(), and stop().
setToTime() [2/2]
void lmms::Song::setToTime (TimePos const & pos, PlayMode playMode) inline
Definition at line 155 of file Song.h.
References getPlayPos(), getTempo(), m_elapsedMilliSeconds, playMode(), and pos.
setToTimeByTicks() [1/2]
void lmms::Song::setToTimeByTicks (tick_t ticks) inline
Definition at line 161 of file Song.h.
References m_playMode, and setToTimeByTicks().
Referenced by setToTimeByTicks().
setToTimeByTicks() [2/2]
void lmms::Song::setToTimeByTicks (tick_t ticks, PlayMode playMode) inline
Definition at line 166 of file Song.h.
References getPlayPos(), getTempo(), m_elapsedMilliSeconds, playMode(), and lmms::TimePos::ticksToMilliseconds().
startExport
void lmms::Song::startExport () slot
Definition at line 728 of file Song.cpp.
References Song, getPlayPos(), getTimeline(), m_exportEffectiveLength, m_exporting, m_exportLoop, m_exportLoopBegin, m_exportLoopEnd, m_exportSongBegin, m_exportSongEnd, m_length, m_loopRenderCount, m_loopRenderRemaining, m_renderBetweenMarkers, m_vstSyncController, playSong(), lmms::TimePos::setTicks(), stop(), and updateLength().
Referenced by lmms::ProjectRenderer::run().
stop
void lmms::Song::stop () slot
Definition at line 648 of file Song.cpp.
References lmms::Engine::audioEngine(), lmms::Timeline::BackToStart, lmms::Timeline::BackToZero, lmms::AudioEngine::clear(), currentFrame(), lmms::AudioEngine::doneChangeInModel(), lmms::Engine::framesPerTick(), getPlayPos(), getTicks(), getTimeline(), lmms::Timeline::KeepPosition, m_elapsedMilliSeconds, m_exporting, m_midiClipToPlay, m_oldAutomatedValues, m_paused, m_playing, m_playMode, m_recording, m_vstSyncController, MidiClip, None, playbackStateChanged(), lmms::AudioEngine::requestChangeInModel(), lmms::Song::PlayPos::setCurrentFrame(), lmms::TimePos::setTicks(), setToTime(), lmms::AutomatableModel::setUseControllerValue(), and stopped().
Referenced by clearProject(), lmms::gui::MainWindow::mayChangeProject(), lmms::gui::MainWindow::openProject(), lmms::gui::AutomationEditor::play(), playMidiClip(), playPattern(), playSong(), startExport(), lmms::gui::AutomationEditor::stop(), lmms::gui::PatternEditorWindow::stop(), lmms::gui::PianoRoll::stop(), lmms::PatternStore::stop(), and stopExport().
stopExport
void lmms::Song::stopExport () slot
Definition at line 780 of file Song.cpp.
References m_exporting, m_playing, m_vstSyncController, and stop().
Referenced by lmms::ProjectRenderer::run().
stopped
void lmms::Song::stopped () signal
Referenced by stop().
syncKey()
const std::string & lmms::Song::syncKey () const inline noexcept
Definition at line 374 of file Song.h.
References m_vstSyncController.
tempoChanged
void lmms::Song::tempoChanged (lmms::bpm_t newBPM) signal
Referenced by setTempo().
tempoModel()
IntModel & lmms::Song::tempoModel () inline
Definition at line 355 of file Song.h.
References m_tempoModel.
ticksPerBar()
int lmms::Song::ticksPerBar () const inline
Definition at line 177 of file Song.h.
References m_timeSigModel, and lmms::TimePos::ticksPerBar().
Referenced by processMetronome(), processNextBuffer(), setTimeSignature(), timeSignatureChanged(), and lmms::gui::TimeDisplayWidget::updateTime().
timeSignatureChanged
void lmms::Song::timeSignatureChanged (int oldTicksPerBar, int ticksPerBar) signal
References ticksPerBar().
Referenced by setTimeSignature().
togglePause
void lmms::Song::togglePause () slot
Definition at line 626 of file Song.cpp.
References lmms::Engine::audioEngine(), lmms::AudioEngine::clear(), m_paused, m_playing, m_vstSyncController, and playbackStateChanged().
Referenced by lmms::gui::AutomationEditor::play(), lmms::gui::PatternEditorWindow::play(), lmms::gui::PianoRoll::play(), lmms::gui::SongEditorWindow::play(), lmms::PatternStore::play(), and lmms::gui::Editor::togglePause().
updateFramesPerTick
void lmms::Song::updateFramesPerTick () private slot
Definition at line 1422 of file Song.cpp.
References lmms::Engine::updateFramesPerTick().
Referenced by Song().
updateLength()
void lmms::Song::updateLength ()
Definition at line 579 of file Song.cpp.
References lengthChanged(), m_exporting, m_length, m_loadingProject, lmms::TrackContainer::m_tracksMutex, and lmms::TrackContainer::tracks().
Referenced by lmms::Clip::changeLength(), createNewProject(), loadProject(), lmms::Clip::movePosition(), lmms::Track::removeClip(), and startExport().
updateSampleTracks
void lmms::Song::updateSampleTracks () signal
Referenced by processNextBuffer(), and setPlayPos().
Friends And Related Symbol Documentation
Engine
friend class Engine friend
Definition at line 519 of file Song.h.
References Engine.
Referenced by Engine.
gui::ControllerRackView
friend class gui::ControllerRackView friend
Definition at line 521 of file Song.h.
gui::SongEditor
friend class gui::SongEditor friend
Definition at line 520 of file Song.h.
Member Data Documentation
m_controllers
ControllerVector lmms::Song::m_controllers private
Definition at line 465 of file Song.h.
Referenced by addController(), controllers(), loadProject(), removeAllControllers(), removeController(), restoreControllerStates(), and saveControllerStates().
m_elapsedBars
bar_t lmms::Song::m_elapsedBars private
Definition at line 500 of file Song.h.
Referenced by Song(), and processNextBuffer().
m_elapsedMilliSeconds
double lmms::Song::m_elapsedMilliSeconds[PlayModeCount] private
Definition at line 498 of file Song.h.
Referenced by Song(), getMilliseconds(), processNextBuffer(), setPlayPos(), setToTime(), setToTimeByTicks(), and stop().
m_elapsedTicks
tick_t lmms::Song::m_elapsedTicks private
Definition at line 499 of file Song.h.
Referenced by Song(), processNextBuffer(), and setPlayPos().
m_errors
QHash<QString, int> lmms::Song::m_errors private
Definition at line 487 of file Song.h.
Referenced by clearErrors(), collectError(), errorSummary(), and hasErrors().
m_exportEffectiveLength
TimePos lmms::Song::m_exportEffectiveLength private
Definition at line 510 of file Song.h.
Referenced by getExportProgress(), and startExport().
m_exporting
volatile bool lmms::Song::m_exporting private
Definition at line 475 of file Song.h.
Referenced by Song(), isExporting(), isPlaying(), processMetronome(), processNextBuffer(), startExport(), stop(), stopExport(), and updateLength().
m_exportLoop
volatile bool lmms::Song::m_exportLoop private
Definition at line 476 of file Song.h.
Referenced by Song(), setExportLoop(), and startExport().
m_exportLoopBegin
TimePos lmms::Song::m_exportLoopBegin private
Definition at line 507 of file Song.h.
Referenced by getExportProgress(), and startExport().
m_exportLoopEnd
TimePos lmms::Song::m_exportLoopEnd private
Definition at line 508 of file Song.h.
Referenced by getExportProgress(), and startExport().
m_exportSongBegin
TimePos lmms::Song::m_exportSongBegin private
Definition at line 506 of file Song.h.
Referenced by getExportProgress(), and startExport().
m_exportSongEnd
TimePos lmms::Song::m_exportSongEnd private
Definition at line 509 of file Song.h.
Referenced by getExportProgress(), isExportDone(), and startExport().
m_fileName
QString lmms::Song::m_fileName private
Definition at line 469 of file Song.h.
Referenced by Song(), guiSaveProject(), loadProject(), projectFileName(), and setProjectFileName().
m_globalAutomationTrack
AutomationTrack* lmms::Song::m_globalAutomationTrack private
Definition at line 457 of file Song.h.
Referenced by Song(), ~Song(), automatedValuesAt(), and globalAutomationTrack().
m_isCancelled
bool lmms::Song::m_isCancelled private
Definition at line 483 of file Song.h.
Referenced by Song(), isCancelled(), loadingCancelled(), and loadProject().
m_keymaps
std::shared_ptr<Keymap> lmms::Song::m_keymaps[MaxKeymapCount] private
Definition at line 513 of file Song.h.
Referenced by Song(), getKeymap(), restoreKeymapStates(), saveKeymapStates(), and setKeymap().
m_length
bar_t lmms::Song::m_length private
Definition at line 493 of file Song.h.
Referenced by Song(), length(), startExport(), and updateLength().
m_loadingProject
bool lmms::Song::m_loadingProject private
Definition at line 482 of file Song.h.
Referenced by Song(), createNewProject(), isLoadingProject(), loadProject(), setModified(), and updateLength().
m_loadOnLaunch
bool lmms::Song::m_loadOnLaunch private
Definition at line 472 of file Song.h.
Referenced by Song(), createNewProject(), createNewProjectFromTemplate(), loadProject(), and setLoadOnLaunch().
m_loopMidiClip
bool lmms::Song::m_loopMidiClip private
Definition at line 496 of file Song.h.
Referenced by Song(), playMidiClip(), and processNextBuffer().
m_loopRenderCount
int lmms::Song::m_loopRenderCount private
Definition at line 504 of file Song.h.
Referenced by Song(), getExportProgress(), getLoopRenderCount(), setLoopRenderCount(), and startExport().
m_loopRenderRemaining
int lmms::Song::m_loopRenderRemaining private
Definition at line 505 of file Song.h.
Referenced by Song(), getExportProgress(), processNextBuffer(), setLoopRenderCount(), and startExport().
m_masterPitchModel
IntModel lmms::Song::m_masterPitchModel private
Definition at line 463 of file Song.h.
Referenced by Song(), clearProject(), createNewProject(), exportProjectMidi(), loadProject(), mapPropertyFromModel(), and saveProjectFile().
m_masterVolumeModel
IntModel lmms::Song::m_masterVolumeModel private
Definition at line 462 of file Song.h.
Referenced by Song(), clearProject(), createNewProject(), loadProject(), mapPropertyFromModel(), masterVolumeChanged(), and saveProjectFile().
m_metronome
Metronome lmms::Song::m_metronome private
Definition at line 517 of file Song.h.
Referenced by metronome(), and processMetronome().
m_midiClipToPlay
const MidiClip* lmms::Song::m_midiClipToPlay private
Definition at line 495 of file Song.h.
Referenced by Song(), playMidiClip(), processNextBuffer(), and stop().
m_modified
bool lmms::Song::m_modified private
Definition at line 471 of file Song.h.
Referenced by Song(), isModified(), and setModified().
m_nLoadingTrack
int lmms::Song::m_nLoadingTrack private
Definition at line 467 of file Song.h.
Referenced by Song(), getLoadingTrackCount(), and loadProject().
m_oldAutomatedValues
AutomatedValueMap lmms::Song::m_oldAutomatedValues private
Definition at line 515 of file Song.h.
Referenced by Song(), clearProject(), processAutomations(), and stop().
m_oldFileName
QString lmms::Song::m_oldFileName private
Definition at line 470 of file Song.h.
Referenced by Song(), createNewProject(), createNewProjectFromTemplate(), and loadProject().
m_oldTicksPerBar
int lmms::Song::m_oldTicksPerBar private
Definition at line 461 of file Song.h.
Referenced by Song(), and setTimeSignature().
m_paused
volatile bool lmms::Song::m_paused private
Definition at line 479 of file Song.h.
Referenced by Song(), isPaused(), isStopped(), playMidiClip(), playPattern(), playSong(), stop(), and togglePause().
m_playing
volatile bool lmms::Song::m_playing private
Definition at line 478 of file Song.h.
Referenced by Song(), ~Song(), clearProject(), isPlaying(), isStopped(), playMidiClip(), playPattern(), playSong(), processNextBuffer(), stop(), stopExport(), and togglePause().
m_playMode
PlayMode lmms::Song::m_playMode private
Definition at line 491 of file Song.h.
Referenced by Song(), currentBar(), currentFrame(), currentTick(), getMilliseconds(), getPlayPos(), getPlayPos(), getTimeline(), getTimeline(), playMidiClip(), playMode(), playPattern(), playSong(), processAutomations(), processNextBuffer(), setToTime(), setToTimeByTicks(), and stop().
m_playPos
PlayPos lmms::Song::m_playPos[PlayModeCount] private
Definition at line 492 of file Song.h.
Referenced by getPlayPos(), and getPlayPos().
m_recording
volatile bool lmms::Song::m_recording private
Definition at line 474 of file Song.h.
Referenced by Song(), isRecording(), playAndRecord(), playSong(), record(), and stop().
m_renderBetweenMarkers
volatile bool lmms::Song::m_renderBetweenMarkers private
Definition at line 477 of file Song.h.
Referenced by Song(), setRenderBetweenMarkers(), and startExport().
m_saveOptions
SaveOptions lmms::Song::m_saveOptions private
Definition at line 485 of file Song.h.
Referenced by getSaveOptions(), and guiSaveProjectAs().
m_savingProject
bool lmms::Song::m_savingProject private
Definition at line 481 of file Song.h.
Referenced by Song(), isSavingProject(), and saveProjectFile().
m_scales
std::shared_ptr<Scale> lmms::Song::m_scales[MaxScaleCount] private
Definition at line 512 of file Song.h.
Referenced by Song(), getScale(), restoreScaleStates(), saveScaleStates(), and setScale().
m_tempoModel
IntModel lmms::Song::m_tempoModel private
Definition at line 459 of file Song.h.
Referenced by Song(), clearProject(), createNewProject(), getTempo(), loadProject(), mapPropertyFromModel(), saveProjectFile(), setTempo(), and tempoModel().
m_timelines
std::array<Timeline, PlayModeCount> lmms::Song::m_timelines private
Definition at line 489 of file Song.h.
Referenced by getTimeline(), and getTimeline().
m_timeSigModel
MeterModel lmms::Song::m_timeSigModel private
Definition at line 460 of file Song.h.
Referenced by Song(), clearProject(), createNewProject(), getBeat(), getBeatTicks(), getTimeSigModel(), loadProject(), processMetronome(), saveProjectFile(), and ticksPerBar().
m_vstSyncController
VstSyncController lmms::Song::m_vstSyncController private
Definition at line 502 of file Song.h.
Referenced by playPattern(), playSong(), processNextBuffer(), setTempo(), setTimeSignature(), startExport(), stop(), stopExport(), syncKey(), and togglePause().
PlayModeCount
auto lmms::Song::PlayModeCount = static_cast<std::size_t>(PlayMode::Count) static constexpr
Definition at line 80 of file Song.h.
Referenced by clearProject().
The documentation for this class was generated from the following files:
include/Song.h
src/core/Song.cpp