LMMS: lmms::Model Class Reference
lmms::Model Class Reference
#include <Model.h>
Signals
void dataChanged ()
void dataUnchanged ()
void propertiesChanged ()
Public Member Functions
Model (Model *parent, QString displayName=QString(), bool defaultConstructed=false)
~Model () override=default
virtual QString displayName () const
virtual QString fullDisplayName () const
bool isDefaultConstructed () const
Model * parentModel () const
virtual void setDisplayName (const QString &displayName)
Private Attributes
bool m_defaultConstructed
QString m_displayName
Detailed Description
Definition at line 36 of file Model.h.
Constructor & Destructor Documentation
Model()
lmms::Model::Model (Model * parent, QString displayName = QString(), bool defaultConstructed = false)
Definition at line 30 of file Model.cpp.
References Model(), displayName(), m_defaultConstructed, and m_displayName.
Referenced by lmms::AutomatableModel::AutomatableModel(), lmms::Clip::Clip(), lmms::Clip::Clip(), lmms::Controller::Controller(), lmms::EffectChain::EffectChain(), lmms::EffectControls::EffectControls(), lmms::EnvelopeAndLfoParameters::EnvelopeAndLfoParameters(), lmms::graphModel::graphModel(), lmms::InstrumentFunctionArpeggio::InstrumentFunctionArpeggio(), lmms::InstrumentFunctionNoteStacking::InstrumentFunctionNoteStacking(), lmms::InstrumentSoundShaping::InstrumentSoundShaping(), lmms::LadspaControl::LadspaControl(), lmms::LinkedModelGroup::LinkedModelGroup(), lmms::MeterModel::MeterModel(), lmms::Microtuner::Microtuner(), lmms::MidiPort::MidiPort(), lmms::Mixer::Mixer(), Model(), lmms::Piano::Piano(), lmms::Plugin::Plugin(), lmms::Track::Track(), lmms::TrackContainer::TrackContainer(), ~Model(), lmms::Controller::create(), lmms::Controller::create(), lmms::Controller::hasModel(), lmms::Plugin::instantiate(), lmms::Plugin::instantiateWithKey(), lmms::MeterModel::mapPropertyFromModel(), and parentModel().
~Model()
lmms::Model::~Model () override default
References Model(), displayName(), fullDisplayName(), isDefaultConstructed(), parentModel(), and setDisplayName().
Member Function Documentation
dataChanged
void lmms::Model::dataChanged () signal
Referenced by lmms::gui::Draggable::Draggable(), lmms::Effect::Effect(), lmms::EnvelopeAndLfoParameters::EnvelopeAndLfoParameters(), lmms::gui::Fader::Fader(), lmms::InstrumentTrack::InstrumentTrack(), lmms::LadspaControl::LadspaControl(), lmms::LfoController::LfoController(), lmms::MeterModel::MeterModel(), lmms::gui::MicrotunerConfig::MicrotunerConfig(), lmms::MidiPort::MidiPort(), lmms::gui::PatternEditorWindow::PatternEditorWindow(), lmms::PeakController::PeakController(), lmms::gui::PianoRoll::PianoRoll(), lmms::SampleClip::SampleClip(), lmms::SampleClip::SampleClip(), lmms::Song::Song(), lmms::gui::SongEditor::SongEditor(), lmms::gui::TrackContentWidget::TrackContentWidget(), lmms::LinkedModelGroup::addModel(), lmms::AutomationClip::addObject(), lmms::EffectChain::appendEffect(), lmms::AutomationClip::clear(), lmms::Song::clearProject(), lmms::gui::MixerView::connectToSoloAndMute(), lmms::gui::MixerView::disconnectFromSoloAndMute(), lmms::AutomationClip::flipX(), lmms::AutomationClip::flipY(), lmms::AutomatableModel::linkModel(), lmms::AutomatableModel::linkModels(), lmms::EffectChain::loadSettings(), lmms::Mixer::loadSettings(), lmms::AutomationClip::objectDestroyed(), lmms::AutomationClip::putValue(), lmms::AutomationClip::putValues(), lmms::EffectChain::removeEffect(), lmms::AutomationClip::removeNode(), lmms::AutomatableModel::setAutomatedValue(), lmms::AutomatableModel::setControllerConnection(), lmms::Piano::setKeyState(), lmms::Clip::setName(), lmms::AutomationClip::setProgressionType(), lmms::TempoSyncKnobModel::setSyncMode(), lmms::Song::setTimeSignature(), lmms::AutomatableModel::setUseControllerValue(), lmms::AutomatableModel::setValue(), lmms::Clip::toggleMute(), lmms::SampleClip::toggleRecord(), and lmms::EnvelopeAndLfoParameters::updateSampleVars().
dataUnchanged
void lmms::Model::dataUnchanged () signal
Referenced by lmms::Song::Song(), and lmms::AutomatableModel::setValue().
displayName()
QString lmms::Model::displayName () const virtual
Reimplemented in lmms::Clip, lmms::DetuningHelper, lmms::Plugin, and lmms::Track.
Definition at line 47 of file Model.cpp.
References m_displayName.
Referenced by lmms::AutomatableModel::AutomatableModel(), lmms::BoolModel::BoolModel(), lmms::ComboBoxModel::ComboBoxModel(), lmms::gui::ControllerView::ControllerView(), lmms::FloatModel::FloatModel(), lmms::IntModel::IntModel(), Model(), ~Model(), lmms::gui::TempoSyncBarModelEditor::contextMenuEvent(), lmms::Plugin::displayName(), lmms::gui::AutomatableModelViewSlots::execConnectionDialog(), fullDisplayName(), and setDisplayName().
fullDisplayName()
QString lmms::Model::fullDisplayName () const virtual
Reimplemented in lmms::Instrument.
Definition at line 57 of file Model.cpp.
References displayName(), fullDisplayName(), and parentModel().
Referenced by ~Model(), and fullDisplayName().
isDefaultConstructed()
bool lmms::Model::isDefaultConstructed () const
Definition at line 37 of file Model.cpp.
References m_defaultConstructed.
Referenced by lmms::ComboBoxModel::ComboBoxModel(), and ~Model().
parentModel()
Model * lmms::Model::parentModel () const
Definition at line 42 of file Model.cpp.
References Model().
Referenced by ~Model(), fullDisplayName(), and lmms::EffectChain::loadSettings().
propertiesChanged
void lmms::Model::propertiesChanged () signal
Referenced by lmms::ComboBoxModel::clear(), lmms::ComboBoxModel::replaceItem(), lmms::AutomatableModel::setRange(), and lmms::AutomatableModel::setStep().
setDisplayName()
void lmms::Model::setDisplayName (const QString & displayName) virtual
Definition at line 52 of file Model.cpp.
References displayName(), and m_displayName.
Referenced by ~Model(), lmms::Mixer::clearChannel(), lmms::DummyEffect::setName(), and lmms::MidiPort::setName().
Member Data Documentation
m_defaultConstructed
bool lmms::Model::m_defaultConstructed private
Definition at line 58 of file Model.h.
Referenced by Model(), and isDefaultConstructed().
m_displayName
QString lmms::Model::m_displayName private
Definition at line 57 of file Model.h.
Referenced by Model(), displayName(), and setDisplayName().
The documentation for this class was generated from the following files:
include/Model.h
src/core/Model.cpp