LMMS: lmms::gui::StringPairDrag Class Reference
lmms::gui::StringPairDrag Class Reference
#include <StringPairDrag.h>
Public Member Functions
StringPairDrag (const QString &_key, const QString &_value, const QPixmap &_icon, QWidget *_w)
~StringPairDrag () override
Static Public Member Functions
static QString decodeKey (QDropEvent *_de)
static QString decodeValue (QDropEvent *_de)
static bool processDragEnterEvent (QDragEnterEvent *_dee, const QString &_allowed_keys)
Detailed Description
Definition at line 42 of file StringPairDrag.h.
Constructor & Destructor Documentation
StringPairDrag()
lmms::gui::StringPairDrag::StringPairDrag (const QString & _key, const QString & _value, const QPixmap & _icon, QWidget * _w)
Definition at line 42 of file StringPairDrag.cpp.
~StringPairDrag()
lmms::gui::StringPairDrag::~StringPairDrag () override
Definition at line 70 of file StringPairDrag.cpp.
References lmms::gui::MainWindow::clearKeyModifiers(), lmms::gui::getGUI(), and lmms::gui::GuiApplication::mainWindow().
Member Function Documentation
decodeKey()
QString lmms::gui::StringPairDrag::decodeKey (QDropEvent * _de) static
Definition at line 106 of file StringPairDrag.cpp.
References lmms::Clipboard::decodeKey().
Referenced by lmms::gui::AutomationClipView::dropEvent(), lmms::gui::AutomationEditorWindow::dropEvent(), lmms::gui::AutomationTrackView::dropEvent(), lmms::gui::ClipView::dropEvent(), lmms::gui::EnvelopeAndLfoView::dropEvent(), lmms::gui::FloatModelEditorBase::dropEvent(), lmms::gui::Graph::dropEvent(), lmms::gui::InstrumentTrackWindow::dropEvent(), lmms::gui::PatternEditor::dropEvent(), lmms::gui::SampleClipView::dropEvent(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), and lmms::gui::TrackView::dropEvent().
decodeValue()
QString lmms::gui::StringPairDrag::decodeValue (QDropEvent * _de) static
Definition at line 114 of file StringPairDrag.cpp.
References lmms::Clipboard::decodeValue().
Referenced by lmms::gui::AutomationClipView::dropEvent(), lmms::gui::AutomationEditorWindow::dropEvent(), lmms::gui::AutomationTrackView::dropEvent(), lmms::gui::ClipView::dropEvent(), lmms::gui::EnvelopeAndLfoView::dropEvent(), lmms::gui::FloatModelEditorBase::dropEvent(), lmms::gui::Graph::dropEvent(), lmms::gui::InstrumentTrackWindow::dropEvent(), lmms::gui::PatternEditor::dropEvent(), lmms::gui::SampleClipView::dropEvent(), lmms::gui::SampleTrackView::dropEvent(), lmms::gui::TrackContainerView::dropEvent(), and lmms::gui::TrackView::dropEvent().
processDragEnterEvent()
bool lmms::gui::StringPairDrag::processDragEnterEvent (QDragEnterEvent * _dee, const QString & _allowed_keys) static
Definition at line 83 of file StringPairDrag.cpp.
Referenced by lmms::gui::AutomationClipView::dragEnterEvent(), lmms::gui::AutomationEditorWindow::dragEnterEvent(), lmms::gui::AutomationTrackView::dragEnterEvent(), lmms::gui::ClipView::dragEnterEvent(), lmms::gui::EnvelopeAndLfoView::dragEnterEvent(), lmms::gui::FloatModelEditorBase::dragEnterEvent(), lmms::gui::Graph::dragEnterEvent(), lmms::gui::SampleClipView::dragEnterEvent(), lmms::gui::SampleTrackView::dragEnterEvent(), lmms::gui::TrackContainerView::dragEnterEvent(), lmms::gui::TrackContentWidget::dragEnterEvent(), lmms::gui::TrackView::dragEnterEvent(), and lmms::gui::InstrumentTrackWindow::dragEnterEventGeneric().
The documentation for this class was generated from the following files:
include/StringPairDrag.h
src/gui/StringPairDrag.cpp