LMMS: Jack::JackWinThread Class Reference
Jack::JackWinThread Class Reference
Windows threads.
#include <JackWinThread.h>
Public Member Functions
JackWinThread (JackRunnableInterface *runnable)
~JackWinThread ()
int AcquireRealTime ()
int AcquireRealTime (int priority)
int AcquireSelfRealTime ()
int AcquireSelfRealTime (int priority)
int DropRealTime ()
int DropSelfRealTime ()
jack_native_thread_t GetThreadID ()
bool IsThread ()
int Kill ()
int Start ()
int StartSync ()
int Stop ()
void Terminate ()
Public Member Functions inherited from Jack::JackMMCSS
JackMMCSS ()
~JackMMCSS ()
Public Member Functions inherited from Jack::detail::JackThreadInterface
JackThreadInterface (JackRunnableInterface *runnable, int priority, bool real_time, int cancellation)
int AcquireRealTime ()
int AcquireRealTime (int priority)
int AcquireSelfRealTime ()
int AcquireSelfRealTime (int priority)
int DropRealTime ()
int DropSelfRealTime ()
kThreadState GetStatus ()
jack_native_thread_t GetThreadID ()
bool IsThread ()
int Kill ()
void SetParams (UInt64 period, UInt64 computation, UInt64 constraint)
void SetStatus (kThreadState status)
int Start ()
int StartSync ()
int Stop ()
void Terminate ()
Static Public Member Functions
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority)
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint)
static int DropRealTimeImp (jack_native_thread_t thread)
static int KillImp (jack_native_thread_t thread)
static int StartImp (jack_native_thread_t *thread, int priority, int realtime, ThreadCallback start_routine, void *arg)
static int StartImp (jack_native_thread_t *thread, int priority, int realtime, void *(*start_routine)(void *), void *arg)
static int StopImp (jack_native_thread_t thread)
Static Public Member Functions inherited from Jack::JackMMCSS
static int MMCSSAcquireRealTime (jack_native_thread_t thread, int priority)
static int MMCSSDropRealTime (jack_native_thread_t thread)
Static Public Member Functions inherited from Jack::detail::JackThreadInterface
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority)
static int AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint)
static int DropRealTimeImp (jack_native_thread_t thread)
static int KillImp (jack_native_thread_t thread)
static int StartImp (jack_native_thread_t *thread, int priority, int realtime, void *(*start_routine)(void *), void *arg)
static int StopImp (jack_native_thread_t thread)
Static Private Member Functions
static DWORD WINAPI ThreadHandler (void *arg)
Private Attributes
HANDLE fEvent
HANDLE fThread
Additional Inherited Members
Public Types inherited from Jack::detail::JackThreadInterface
enum kThreadState {
kIdle ,
kStarting ,
kIniting ,
kRunning
}
Protected Attributes inherited from Jack::detail::JackThreadInterface
int fCancellation
int fPriority
bool fRealTime
JackRunnableInterface * fRunnable
volatile kThreadState fStatus
Detailed Description
Windows threads.
Definition at line 41 of file JackWinThread.h.
Constructor & Destructor Documentation
JackWinThread()
Jack::JackWinThread::JackWinThread (JackRunnableInterface * runnable)
Definition at line 57 of file JackWinThread.cpp.
References Jack::JackMMCSS::JackMMCSS(), Jack::detail::JackThreadInterface::JackThreadInterface(), FALSE, fEvent, and fThread.
Referenced by ThreadHandler().
~JackWinThread()
Jack::JackWinThread::~JackWinThread ()
Definition at line 65 of file JackWinThread.cpp.
References fEvent, and fThread.
Member Function Documentation
AcquireRealTime() [1/2]
int Jack::JackWinThread::AcquireRealTime ()
Definition at line 179 of file JackWinThread.cpp.
References AcquireRealTimeImp(), Jack::detail::JackThreadInterface::fPriority, and fThread.
Referenced by AcquireRealTime().
AcquireRealTime() [2/2]
int Jack::JackWinThread::AcquireRealTime (int priority)
Definition at line 189 of file JackWinThread.cpp.
References AcquireRealTime(), and Jack::detail::JackThreadInterface::fPriority.
AcquireRealTimeImp() [1/2]
int Jack::JackWinThread::AcquireRealTimeImp (jack_native_thread_t thread, int priority) static
Definition at line 201 of file JackWinThread.cpp.
References BASE_REALTIME_PRIORITY, jack_error, jack_log(), and Jack::JackMMCSS::MMCSSAcquireRealTime().
Referenced by AcquireRealTime(), AcquireRealTimeImp(), and AcquireSelfRealTime().
AcquireRealTimeImp() [2/2]
int Jack::JackWinThread::AcquireRealTimeImp (jack_native_thread_t thread, int priority, UInt64 period, UInt64 computation, UInt64 constraint) inline static
Definition at line 75 of file JackWinThread.h.
References AcquireRealTimeImp().
AcquireSelfRealTime() [1/2]
int Jack::JackWinThread::AcquireSelfRealTime ()
Definition at line 184 of file JackWinThread.cpp.
References AcquireRealTimeImp(), and Jack::detail::JackThreadInterface::fPriority.
Referenced by AcquireSelfRealTime().
AcquireSelfRealTime() [2/2]
int Jack::JackWinThread::AcquireSelfRealTime (int priority)
Definition at line 195 of file JackWinThread.cpp.
References AcquireSelfRealTime(), and Jack::detail::JackThreadInterface::fPriority.
DropRealTime()
int Jack::JackWinThread::DropRealTime ()
Definition at line 219 of file JackWinThread.cpp.
References DropRealTimeImp(), and fThread.
DropRealTimeImp()
int Jack::JackWinThread::DropRealTimeImp (jack_native_thread_t thread) static
Definition at line 229 of file JackWinThread.cpp.
References jack_error, jack_log(), and Jack::JackMMCSS::MMCSSDropRealTime().
Referenced by DropRealTime(), and DropSelfRealTime().
DropSelfRealTime()
int Jack::JackWinThread::DropSelfRealTime ()
Definition at line 224 of file JackWinThread.cpp.
References DropRealTimeImp().
GetThreadID()
jack_native_thread_t Jack::JackWinThread::GetThreadID ()
Definition at line 242 of file JackWinThread.cpp.
References fThread.
IsThread()
bool Jack::JackWinThread::IsThread ()
Definition at line 247 of file JackWinThread.cpp.
References fThread.
Kill()
int Jack::JackWinThread::Kill ()
Definition at line 127 of file JackWinThread.cpp.
References Jack::detail::JackThreadInterface::fStatus, fThread, jack_log(), and Jack::detail::JackThreadInterface::kIdle.
KillImp()
int Jack::JackWinThread::KillImp (jack_native_thread_t thread) static
Definition at line 156 of file JackWinThread.cpp.
Start()
int Jack::JackWinThread::Start ()
Definition at line 71 of file JackWinThread.cpp.
References Jack::detail::JackThreadInterface::fPriority, Jack::detail::JackThreadInterface::fRealTime, Jack::detail::JackThreadInterface::fStatus, fThread, Jack::detail::JackThreadInterface::kIdle, Jack::detail::JackThreadInterface::kStarting, StartImp(), and ThreadHandler().
StartImp() [1/2]
int Jack::JackWinThread::StartImp (jack_native_thread_t * thread, int priority, int realtime, ThreadCallback start_routine, void * arg) static
Definition at line 100 of file JackWinThread.cpp.
References jack_error, and jack_log().
StartImp() [2/2]
int Jack::JackWinThread::StartImp (jack_native_thread_t * thread, int priority, int realtime, void *(* start_routine)(void *), void * arg) inline static
Definition at line 80 of file JackWinThread.h.
References StartImp().
Referenced by Start(), StartImp(), and StartSync().
StartSync()
int Jack::JackWinThread::StartSync ()
Definition at line 84 of file JackWinThread.cpp.
References Jack::detail::JackThreadInterface::fPriority, Jack::detail::JackThreadInterface::fRealTime, Jack::detail::JackThreadInterface::fStatus, fThread, JackSleep(), Jack::detail::JackThreadInterface::kIdle, Jack::detail::JackThreadInterface::kStarting, StartImp(), and ThreadHandler().
Stop()
int Jack::JackWinThread::Stop ()
Definition at line 142 of file JackWinThread.cpp.
References fEvent, Jack::detail::JackThreadInterface::fStatus, fThread, jack_log(), and Jack::detail::JackThreadInterface::kIdle.
StopImp()
int Jack::JackWinThread::StopImp (jack_native_thread_t thread) static
Definition at line 168 of file JackWinThread.cpp.
Terminate()
void Jack::JackWinThread::Terminate ()
Definition at line 252 of file JackWinThread.cpp.
References jack_log().
ThreadHandler()
DWORD WINAPI Jack::JackWinThread::ThreadHandler (void * arg) static private
Definition at line 29 of file JackWinThread.cpp.
References JackWinThread(), Jack::JackRunnableInterface::Execute(), fEvent, Jack::detail::JackThreadInterface::fRunnable, Jack::detail::JackThreadInterface::fStatus, Jack::JackRunnableInterface::Init(), jack_error, jack_log(), Jack::detail::JackThreadInterface::kIniting, and Jack::detail::JackThreadInterface::kRunning.
Referenced by Start(), and StartSync().
Member Data Documentation
fEvent
HANDLE Jack::JackWinThread::fEvent private
Definition at line 47 of file JackWinThread.h.
Referenced by JackWinThread(), ~JackWinThread(), Stop(), and ThreadHandler().
fThread
HANDLE Jack::JackWinThread::fThread private
Definition at line 46 of file JackWinThread.h.
Referenced by JackWinThread(), ~JackWinThread(), AcquireRealTime(), DropRealTime(), GetThreadID(), IsThread(), Kill(), Start(), StartSync(), and Stop().
The documentation for this class was generated from the following files:
src/3rdparty/jack2/windows/JackWinThread.h
src/3rdparty/jack2/windows/JackWinThread.cpp