LMMS: hiir::PhaseHalfPi8F64Avx512< NC > Class Template Reference
hiir::PhaseHalfPi8F64Avx512< NC > Class Template Reference
#include <PhaseHalfPi8F64Avx512.h>
Public Types
typedef double DataType
Public Member Functions
PhaseHalfPi8F64Avx512 () noexcept
PhaseHalfPi8F64Avx512 (const PhaseHalfPi8F64Avx512< NC > &other)=default
PhaseHalfPi8F64Avx512 (PhaseHalfPi8F64Avx512< NC > &&other)=default
~PhaseHalfPi8F64Avx512 ()=default
void clear_buffers () noexcept
PhaseHalfPi8F64Avx512< NC > & operator= (const PhaseHalfPi8F64Avx512< NC > &other)=default
PhaseHalfPi8F64Avx512< NC > & operator= (PhaseHalfPi8F64Avx512< NC > &&other)=default
void process_block (double out_0_ptr[], double out_1_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (__m512d &out_0, __m512d &out_1, __m512d input) noexcept
void set_coefs (const double coef_arr[]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 8
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Avx512, NBR_COEFS+2 > Filter
typedef std::array< Filter, _nbr_phases > FilterBiPhase
Private Member Functions
bool operator!= (const PhaseHalfPi8F64Avx512 &other) const =delete
bool operator== (const PhaseHalfPi8F64Avx512 &other) const =delete
Private Attributes
FilterBiPhase _bifilter
int _phase
double _prev [_nbr_chn]
Static Private Attributes
static constexpr int _nbr_phases = 2
Detailed Description
template<int NC>
class hiir::PhaseHalfPi8F64Avx512< NC >
Definition at line 49 of file PhaseHalfPi8F64Avx512.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::PhaseHalfPi8F64Avx512< NC >::DataType
Definition at line 58 of file PhaseHalfPi8F64Avx512.h.
Filter
template<int NC> typedef std::array<StageDataF64Avx512, NBR_COEFS + 2> hiir::PhaseHalfPi8F64Avx512< NC >::Filter private
Definition at line 95 of file PhaseHalfPi8F64Avx512.h.
FilterBiPhase
template<int NC> typedef std::array<Filter, _nbr_phases> hiir::PhaseHalfPi8F64Avx512< NC >::FilterBiPhase private
Definition at line 97 of file PhaseHalfPi8F64Avx512.h.
Constructor & Destructor Documentation
PhaseHalfPi8F64Avx512() [1/3]
template<int NC> hiir::PhaseHalfPi8F64Avx512< NC >::PhaseHalfPi8F64Avx512 () noexcept
Definition at line 57 of file PhaseHalfPi8F64Avx512.hpp.
References _bifilter, _phase, clear_buffers(), i, and NBR_COEFS.
Referenced by PhaseHalfPi8F64Avx512(), PhaseHalfPi8F64Avx512(), ~PhaseHalfPi8F64Avx512(), operator!=(), operator=(), operator=(), and operator==().
PhaseHalfPi8F64Avx512() [2/3]
template<int NC> hiir::PhaseHalfPi8F64Avx512< NC >::PhaseHalfPi8F64Avx512 (const PhaseHalfPi8F64Avx512< NC > & other) default
References PhaseHalfPi8F64Avx512().
PhaseHalfPi8F64Avx512() [3/3]
template<int NC> hiir::PhaseHalfPi8F64Avx512< NC >::PhaseHalfPi8F64Avx512 (PhaseHalfPi8F64Avx512< NC > && other) default
References PhaseHalfPi8F64Avx512().
~PhaseHalfPi8F64Avx512()
template<int NC> hiir::PhaseHalfPi8F64Avx512< NC >::~PhaseHalfPi8F64Avx512 () default
References PhaseHalfPi8F64Avx512().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::PhaseHalfPi8F64Avx512< NC >::clear_buffers () noexcept
Definition at line 226 of file PhaseHalfPi8F64Avx512.hpp.
References _bifilter, _phase, _prev, i, and NBR_COEFS.
Referenced by PhaseHalfPi8F64Avx512(), and operator=().
operator!=()
template<int NC> bool hiir::PhaseHalfPi8F64Avx512< NC >::operator!= (const PhaseHalfPi8F64Avx512< NC > & other) const private delete
References PhaseHalfPi8F64Avx512().
operator=() [1/2]
template<int NC> PhaseHalfPi8F64Avx512< NC > & hiir::PhaseHalfPi8F64Avx512< NC >::operator= (const PhaseHalfPi8F64Avx512< NC > & other) default
References PhaseHalfPi8F64Avx512().
operator=() [2/2]
template<int NC> PhaseHalfPi8F64Avx512< NC > & hiir::PhaseHalfPi8F64Avx512< NC >::operator= (PhaseHalfPi8F64Avx512< NC > && other) default
References PhaseHalfPi8F64Avx512(), clear_buffers(), hiir_FORCEINLINE, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::PhaseHalfPi8F64Avx512< NC >::operator== (const PhaseHalfPi8F64Avx512< NC > & other) const private delete
References PhaseHalfPi8F64Avx512().
process_block()
template<int NC> void hiir::PhaseHalfPi8F64Avx512< NC >::process_block (double out_0_ptr[], double out_1_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 150 of file PhaseHalfPi8F64Avx512.hpp.
References _bifilter, _nbr_chn, _nbr_phases, _phase, _prev, NBR_COEFS, pos, process_sample(), and hiir::StageProc8F64Avx512< REMAINING >::process_sample_neg().
Referenced by operator=().
process_sample()
template<int NC> void hiir::PhaseHalfPi8F64Avx512< NC >::process_sample (__m512d & out_0, __m512d & out_1, __m512d input) noexcept
Definition at line 117 of file PhaseHalfPi8F64Avx512.hpp.
References _bifilter, _phase, _prev, NBR_COEFS, and hiir::StageProc8F64Avx512< REMAINING >::process_sample_neg().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::PhaseHalfPi8F64Avx512< NC >::set_coefs (const double coef_arr[]) noexcept
Definition at line 87 of file PhaseHalfPi8F64Avx512.hpp.
References _bifilter, i, and NBR_COEFS.
Referenced by operator=().
Member Data Documentation
_bifilter
template<int NC> FilterBiPhase hiir::PhaseHalfPi8F64Avx512< NC >::_bifilter private
Definition at line 99 of file PhaseHalfPi8F64Avx512.h.
Referenced by PhaseHalfPi8F64Avx512(), clear_buffers(), process_block(), process_sample(), and set_coefs().
_delay
template<int NC> double hiir::PhaseHalfPi8F64Avx512< NC >::_delay = 0 static constexpr
Definition at line 61 of file PhaseHalfPi8F64Avx512.h.
_nbr_chn
template<int NC> int hiir::PhaseHalfPi8F64Avx512< NC >::_nbr_chn = 8 static constexpr
Definition at line 59 of file PhaseHalfPi8F64Avx512.h.
Referenced by process_block().
_nbr_phases
template<int NC> int hiir::PhaseHalfPi8F64Avx512< NC >::_nbr_phases = 2 static constexpr private
Definition at line 93 of file PhaseHalfPi8F64Avx512.h.
Referenced by process_block().
_phase
template<int NC> int hiir::PhaseHalfPi8F64Avx512< NC >::_phase private
Definition at line 102 of file PhaseHalfPi8F64Avx512.h.
Referenced by PhaseHalfPi8F64Avx512(), clear_buffers(), process_block(), and process_sample().
_prev
template<int NC> double hiir::PhaseHalfPi8F64Avx512< NC >::_prev[_nbr_chn] private
Definition at line 101 of file PhaseHalfPi8F64Avx512.h.
Referenced by clear_buffers(), process_block(), and process_sample().
NBR_COEFS
template<int NC> int hiir::PhaseHalfPi8F64Avx512< NC >::NBR_COEFS = NC static constexpr
Definition at line 60 of file PhaseHalfPi8F64Avx512.h.
Referenced by PhaseHalfPi8F64Avx512(), clear_buffers(), process_block(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/PhaseHalfPi8F64Avx512.h
src/3rdparty/hiir/hiir/PhaseHalfPi8F64Avx512.hpp