LMMS: hiir::Upsampler2x4F64Avx< NC > Class Template Reference
hiir::Upsampler2x4F64Avx< NC > Class Template Reference
#include <Upsampler2x4F64Avx.h>
Public Types
typedef double DataType
Public Member Functions
Upsampler2x4F64Avx () noexcept
Upsampler2x4F64Avx (const Upsampler2x4F64Avx< NC > &other)=default
Upsampler2x4F64Avx (Upsampler2x4F64Avx< NC > &&other)=default
~Upsampler2x4F64Avx ()=default
void clear_buffers () noexcept
Upsampler2x4F64Avx< NC > & operator= (const Upsampler2x4F64Avx< NC > &other)=default
Upsampler2x4F64Avx< NC > & operator= (Upsampler2x4F64Avx< NC > &&other)=default
void process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
hiir_FORCEINLINE void process_sample (__m256d &out_0, __m256d &out_1, __m256d input) noexcept
void set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Static Public Attributes
static constexpr double _delay = 0
static constexpr int _nbr_chn = 4
static constexpr int NBR_COEFS = NC
Private Types
typedef std::array< StageDataF64Avx, NBR_COEFS+2 > Filter
Private Member Functions
bool operator!= (const Upsampler2x4F64Avx< NC > &other) const =delete
bool operator== (const Upsampler2x4F64Avx< NC > &other) const =delete
Private Attributes
Filter _filter
Detailed Description
template<int NC>
class hiir::Upsampler2x4F64Avx< NC >
Definition at line 54 of file Upsampler2x4F64Avx.h.
Member Typedef Documentation
DataType
template<int NC> typedef double hiir::Upsampler2x4F64Avx< NC >::DataType
Definition at line 63 of file Upsampler2x4F64Avx.h.
Filter
template<int NC> typedef std::array<StageDataF64Avx, NBR_COEFS + 2> hiir::Upsampler2x4F64Avx< NC >::Filter private
Definition at line 96 of file Upsampler2x4F64Avx.h.
Constructor & Destructor Documentation
Upsampler2x4F64Avx() [1/3]
template<int NC> hiir::Upsampler2x4F64Avx< NC >::Upsampler2x4F64Avx () noexcept
Definition at line 56 of file Upsampler2x4F64Avx.hpp.
References _filter, clear_buffers(), i, and NBR_COEFS.
Referenced by Upsampler2x4F64Avx(), Upsampler2x4F64Avx(), ~Upsampler2x4F64Avx(), operator!=(), operator=(), operator=(), and operator==().
Upsampler2x4F64Avx() [2/3]
template<int NC> hiir::Upsampler2x4F64Avx< NC >::Upsampler2x4F64Avx (const Upsampler2x4F64Avx< NC > & other) default
References Upsampler2x4F64Avx().
Upsampler2x4F64Avx() [3/3]
template<int NC> hiir::Upsampler2x4F64Avx< NC >::Upsampler2x4F64Avx (Upsampler2x4F64Avx< NC > && other) default
References Upsampler2x4F64Avx().
~Upsampler2x4F64Avx()
template<int NC> hiir::Upsampler2x4F64Avx< NC >::~Upsampler2x4F64Avx () default
References Upsampler2x4F64Avx().
Member Function Documentation
clear_buffers()
template<int NC> void hiir::Upsampler2x4F64Avx< NC >::clear_buffers () noexcept
Definition at line 182 of file Upsampler2x4F64Avx.hpp.
References _filter, i, and NBR_COEFS.
Referenced by Upsampler2x4F64Avx(), and operator=().
operator!=()
template<int NC> bool hiir::Upsampler2x4F64Avx< NC >::operator!= (const Upsampler2x4F64Avx< NC > & other) const private delete
References Upsampler2x4F64Avx().
operator=() [1/2]
template<int NC> Upsampler2x4F64Avx< NC > & hiir::Upsampler2x4F64Avx< NC >::operator= (const Upsampler2x4F64Avx< NC > & other) default
References Upsampler2x4F64Avx().
operator=() [2/2]
template<int NC> Upsampler2x4F64Avx< NC > & hiir::Upsampler2x4F64Avx< NC >::operator= (Upsampler2x4F64Avx< NC > && other) default
References Upsampler2x4F64Avx(), clear_buffers(), hiir_FORCEINLINE, NBR_COEFS, process_block(), process_sample(), and set_coefs().
operator==()
template<int NC> bool hiir::Upsampler2x4F64Avx< NC >::operator== (const Upsampler2x4F64Avx< NC > & other) const private delete
References Upsampler2x4F64Avx().
process_block()
template<int NC> void hiir::Upsampler2x4F64Avx< NC >::process_block (double out_ptr[], const double in_ptr[], long nbr_spl) noexcept
Definition at line 147 of file Upsampler2x4F64Avx.hpp.
References _nbr_chn, pos, and process_sample().
Referenced by operator=().
process_sample()
template<int NC> void hiir::Upsampler2x4F64Avx< NC >::process_sample (__m256d & out_0, __m256d & out_1, __m256d input) noexcept
Definition at line 113 of file Upsampler2x4F64Avx.hpp.
References _filter, NBR_COEFS, and hiir::StageProc4F64Avx< REMAINING >::process_sample_pos().
Referenced by operator=(), and process_block().
set_coefs()
template<int NC> void hiir::Upsampler2x4F64Avx< NC >::set_coefs (const double coef_arr[NBR_COEFS]) noexcept
Definition at line 84 of file Upsampler2x4F64Avx.hpp.
References _filter, i, and NBR_COEFS.
Referenced by operator=().
Member Data Documentation
_delay
template<int NC> double hiir::Upsampler2x4F64Avx< NC >::_delay = 0 static constexpr
Definition at line 66 of file Upsampler2x4F64Avx.h.
_filter
template<int NC> Filter hiir::Upsampler2x4F64Avx< NC >::_filter private
Definition at line 98 of file Upsampler2x4F64Avx.h.
Referenced by Upsampler2x4F64Avx(), clear_buffers(), process_sample(), and set_coefs().
_nbr_chn
template<int NC> int hiir::Upsampler2x4F64Avx< NC >::_nbr_chn = 4 static constexpr
Definition at line 64 of file Upsampler2x4F64Avx.h.
Referenced by process_block().
NBR_COEFS
template<int NC> int hiir::Upsampler2x4F64Avx< NC >::NBR_COEFS = NC static constexpr
Definition at line 65 of file Upsampler2x4F64Avx.h.
Referenced by Upsampler2x4F64Avx(), clear_buffers(), operator=(), process_sample(), and set_coefs().
The documentation for this class was generated from the following files:
src/3rdparty/hiir/hiir/Upsampler2x4F64Avx.h
src/3rdparty/hiir/hiir/Upsampler2x4F64Avx.hpp